### PR TITLE
Adds a cow which untips itself and moos when it collides with an entity

### PR DESCRIPTION
**Pull request by ericrius1**

### CODE REVIEW

**Comment by ericrius1** [comment]
Test url: https://rawgit.com/ericrius1/hifi/cowTipper/examples/cows/cowSpawner.js

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e250097348be1087b0859827fabceb7066e8781 available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc92294d16efc60dbf1d221b96168a74303017e5 available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Comment by imgntn** [comment]
@eric headers!! :)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 721b94044164fe446c325a6d0687857af8f91d0c available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be499747f2b9e70d9a2a6c4ce49cd4e459ffc122 available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Comment by cozza13** [comment]
Tipped over and could hear sounds.

**Comment by bluetoe** [comment]
This seems to work well for me.
I managed to get the cow stuck by pulling it sideways into sloping ground but as far as I could see, it was able to pull itself out eventually by sliding down hill a tiny bit at a time. Good bovine fun. Got milk?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8176852503e5793ea0860b83c0ff8d4756f23c02 available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0f843d6ebf4c0b3282eb7e43ef7d8d62ae32a91 available at: https://gist.github.com/8ba3ac9da211a3d2818f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7477.dmg

**Pull request merged**
