### PR TITLE
4684 Add collapse button on the virtual keyboard 

### PR DESCRIPTION
**Pull request by ElderOrb**
*** Test plan ***: 

1. Switch to VR
2. Open 'go to location', select input field so that virtual keyboard appear. 
3. Ensure virtual keyboard has new 'collapse' button like on the picture below:

image

4. Ensure clicking on 'collapse' button collapses keyboard in the same way as clicking outside the keyboard.
5. Ensure re-selecting input field after collapsing keyboard still raises keyboard. 

Note: It turned out that some dialogs are implemented in a bit different way than others, so please check as much different screens with virtual keyboard as possible and let me know what screen causes issues (hopefully no one, but still..)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4514/HighFidelity-Beta-PR11705-f98d1efde881861452ce2d748a747db493a935f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4514/HighFidelity-Beta-PR11705-f98d1efde881861452ce2d748a747db493a935f3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4518/HighFidelity-Beta-PR11705-2a8e800e5cadd715e32efa53a6bea8f88ad282be.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4518/HighFidelity-Beta-PR11705-2a8e800e5cadd715e32efa53a6bea8f88ad282be.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4548/HighFidelity-Beta-PR11705-77ca3aa42d6dda4e0d43ad19cdb6c526bc4060c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4550/HighFidelity-Beta-PR11705-939408c366641aac0c4208bfdadfc1e8a86d7614.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4550/HighFidelity-Beta-PR11705-939408c366641aac0c4208bfdadfc1e8a86d7614.exe

**Comment by Nex-Pro** [comment]
### Feedback:

@ElderOrb Does the collapse arrow have a tooltip? Will users know what it is for without having been informed ?

**Comment by ElderOrb** [comment]
@Nex-Pro No tool tip at the moment, I assume the intention was to make self-explainable UI.

**Comment by Nex-Pro** [comment]
@ElderOrb By adding mystery icons ?

**Comment by themelissabrown** [comment]
@ElderOrb let me know when this is ready for QA

**Comment by ElderOrb** [comment]
Should be ready now. Please check as much different dialogs as possible - not all of them are made in the same way so theoretically there might be some differences in behaviour which might require more tweaking.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4620/HighFidelity-Beta-PR11705-70cb8b94889fd180ecebb496c026481a88ca759e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4620/HighFidelity-Beta-PR11705-70cb8b94889fd180ecebb496c026481a88ca759e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4639/HighFidelity-Beta-PR11705-70cb8b94889fd180ecebb496c026481a88ca759e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4639/HighFidelity-Beta-PR11705-70cb8b94889fd180ecebb496c026481a88ca759e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4722/HighFidelity-Beta-PR11705-ae6166b01f29521bb67970804053fe318589d88c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4722/HighFidelity-Beta-PR11705-ae6166b01f29521bb67970804053fe318589d88c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4727/HighFidelity-Beta-PR11705-aa42e7b2ba03a802e1885ec00e80371f1258bf97.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4727/HighFidelity-Beta-PR11705-aa42e7b2ba03a802e1885ec00e80371f1258bf97.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4732/HighFidelity-Beta-PR11705-31935ad6a557dfb60cf6a7e608f480e8b8690068.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4732/HighFidelity-Beta-PR11705-31935ad6a557dfb60cf6a7e608f480e8b8690068.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4759/HighFidelity-Beta-PR11705-ec6bb545f5868d97db2b13aab3e907b814c56a62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4759/HighFidelity-Beta-PR11705-ec6bb545f5868d97db2b13aab3e907b814c56a62.exe

**Comment by changxc** [comment]
could we get some QA rockstar help please? @Nex-Pro

**Comment by Nex-Pro** [comment]
@themelissabrown Yes !

**Comment by Nex-Pro** [comment]
I'm going to ignore the fact that the instructions have not been updated.

Button has now been re-located to bottom right of keyboard.

kc8212-hifi-snap-by-piper-peppercorn-on-2017-11-08_21-41-23

Much better than the weird wings.

Works fine. (insert Piper 'However' here )

However, in instances where the keyboard does not need to be collapsed the icon is still active.
For instance when using the filter to load a local script. The icon highlights on hover but does nothing. Maybe it would be better to have this greyed-out where it should be inactive.

tu8212-hifi-snap-by-piper-peppercorn-on-2017-11-08_21-46-06

**Comment by ElderOrb** [comment]
@changxc so what should be done in cases when keyboard should not be collapsed? greyout key / hide or do something else? Also would be great if I could get list of such cases as I'm still not fully familiar with the product.

**Comment by ElderOrb** [comment]
Fixed 'Running Scripts', please re-check

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4812/HighFidelity-Beta-PR11705-35a052d84240b683df745fc43f7985bd4c7e7611.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4812/HighFidelity-Beta-PR11705-35a052d84240b683df745fc43f7985bd4c7e7611.exe

**Comment by changxc** [comment]
looks good to me! thank you!

**Comment by Nex-Pro** [comment]
Will test shortly.

**Comment by Nex-Pro** [comment]
awaiting new build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4828/HighFidelity-Beta-PR11705-777a5fa69c97584f294ec970ad8306f97dc9640b.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4828/HighFidelity-Beta-PR11705-777a5fa69c97584f294ec970ad8306f97dc9640b.dmg

**Comment by Nex-Pro** [comment]
@ElderOrb I've spent more than thirty minutes trying to get this working. I'm having a lot of problems with the lasers either working strangely or not at all. Also I can no longer interact with the tablet. I have rebooted my vive, cleared cache and reset scripts all to no avail. My lasers and tablet interactions are fine in 7413

**Comment by ElderOrb** [comment]
@Nex-Pro I've gone through the same sequence, including reboot & reset settings and I see no issues like you described. But I recall very similar situation when one particular PR refused to work for @changxc and was 'fixed' only by uninstalling all other PRs. Could you please try this approach? 

Just in case I've also prepared variation of this PR https://github.com/highfidelity/hifi/pull/11792 - it should have *zero* impact on lasers (well, in fact this PR should also have zero impact on lasers). Please check it and let me know if it behaves differently than this one.

**Comment by Nex-Pro** [comment]
@ElderOrb Ok will check ( other PRs never have any connection BTW they are completely isolated from each other ) Should I test using 11792 ?

**Comment by Nex-Pro** [comment]
@ElderOrb uninstalled and cleaned all folders for all other PRs. Re-installing this build. and testing.

**Comment by Nex-Pro** [comment]
@ElderOrb problem persists after full cleanup ( very thorough ) and reinstall. I suspect some odd build issue.

Did you install the build or your locally compiled version ?

Here's a screen-grab of one of the issues.

v11444-hifi-snap-by-piper-peppercorn-on-2017-11-10_17-11-01

See the orphaned lasers. I don't get this happening in any of the current builds, this one only. I was also getting the raypick  target sphere's being left as persistent overlay ents.

**Comment by Nex-Pro** [comment]
@ElderOrb crash on exit. Splat submitted.

**Comment by changxc** [comment]
^laser behavior indeed looks strange. I will check again as well.

**Comment by ElderOrb** [comment]
Ok. Purely theoretically this might really be some build machine-related issue. Although in this case I don't understand why it works for me. I've tried this link: 

https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4828/HighFidelity-Beta-PR11705-777a5fa69c97584f294ec970ad8306f97dc9640b.exe

**Comment by ElderOrb** [comment]
Probably I should rebase this PR on top of the latest master (assuming master is stable enough) to force rebuild,

**Comment by ElderOrb** [comment]
done: https://github.com/highfidelity/hifi/pull/11794

**Comment by changxc** [comment]
the build i marked thumbs down has a weird laser bug, little sphere stays on tablet

**Comment by Nex-Pro** [comment]
@changxc I mentioned the spheres in my notes. Thank you for confirming.

**Pull request closed without merging**
