### PR TITLE
fix crash in lambda

### PR DESCRIPTION
**Pull request by AndrewMeadows**
Zach and I were noticing a crash with a callstack, the top of which, looked something like this:

    0   io.highfidelity.Interface     	0x0000000105ba86fc 0x105588000 + 6424316
    1   org.qt-project.QtCore         	0x000000010a405ef2 QMetaObject::activate(QObject*, int, int, void**) + 1986
    2   io.highfidelity.Interface     	0x0000000105b74cac EntityTreeRenderer::mousePressOnEntity(RayToEntityIntersectionResult const&, QMouseEvent const*, unsigned int) + 76
    3   io.highfidelity.Interface     	0x0000000105b7c0f7 EntityTreeRenderer::mousePressEvent(QMouseEvent*, unsigned int) + 775
    4   io.highfidelity.Interface     	0x00000001055cf90c Application::mousePressEvent(QMouseEvent*, unsigned int) + 268
    5   io.highfidelity.Interface     	0x00000001055cf20c Application::event(QEvent*) + 588
    6   org.qt-project.QtWidgets      	0x00000001078044bb QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
    7   org.qt-project.QtWidgets      	0x000000010780789e QApplication::notify(QObject*, QEvent*) + 8318
    8   org.qt-project.QtCore         	0x000000010a3d5983 QCoreApplication::notifyInternal(QObject*, QEvent*) + 115
    9   io.highfidelity.Interface     	0x000000010584c5a8 GLWidget::event(QEvent*) + 88
    10  io.highfidelity.Interface     	0x00000001056164c7 GLCanvas::event(QEvent*) + 39

When I made the changes below the problem went away for me.

The problem appears to be that the context of class method was not properly dereferenced from **this** inside a lambda.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ffa2f7e4b9039a5b574639ff2f040fee9408d85f available at: https://gist.github.com/da03f5e4be64eb93c619<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6764.dmg

**Comment by ZappoMan** [comment]
cool... I wonder what it was evaluating `this` to without the explicit reference.

**Comment by howard-stearns** [comment]
I'm not sure this fixes it:
  1) I don't understand why it would.
  2) I can reproduce a crash at this line, with or without the ```this->```, as follows:
     Run from Xcode.
     Make a web entity. Click and poke at it.  (By the way, it doesn't render.)
     Delete the web entity.  Wait a while and/or poke around at other things. Eventually...
     Crash at if (intersection.entityID == this->getID())

**Comment by AndrewMeadows** [comment]
Yeah, I guess this doesn't fix it -- I just didn't try hard enough.

The internal asana task for this is here:

https://app.asana.com/0/26225263936266/75927873229456

And it is probably related to this one (marked as duplicate -- has a similar but distinct callstack):

https://app.asana.com/0/26225263936266/76683668549882/f

**Comment by Atlante45** [comment]
the use of `this->` should be implicit, I think the problem comes from those 4 lines line 159:
```
QObject::connect(renderer, &EntityTreeRenderer::mousePressOnEntity, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::mouseReleaseOnEntity, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::mouseMoveOnEntity, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::hoverLeaveEntity, [=](...) { ... });
```

There should be context objects here, so that those are automatically disconnected if `renderer` dies:
```
QObject::connect(renderer, &EntityTreeRenderer::mousePressOnEntity, this, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::mouseReleaseOnEntity, this, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::mouseMoveOnEntity, this, forwardMouseEvent);
QObject::connect(renderer, &EntityTreeRenderer::hoverLeaveEntity, this, [=](...) { ... });
```

`_connection = QObject::connect(_webSurface, &OffscreenQmlSurface::textureUpdated, [&](GLuint textureId) { ... });` line 80 should probably have one too.

**Comment by Atlante45** [comment]
Actually if the renderer dies, it gets cleaned up, but if RenderableWebEntity dies first, which happens when we delete a web entity, then we will get a crash if one of those signals trigger.

**Comment by AndrewMeadows** [comment]
@Atlante45 will attempt a fix.

**Pull request closed without merging**
