### PR TITLE
Shadow on Mac bug fix

### PR DESCRIPTION
**Pull request by Zvork**
Fixes the shadows on Mac with AMD GPU. See [Manuscript bug #13762](https://highfidelity.fogbugz.com/f/cases/13762/Mac-AMD-Shadows-do-not-correctly-render). It could possibly also fix another [shadow bug on Windows on AMD GPU #13081](https://highfidelity.fogbugz.com/f/cases/13081/Shadow-is-showing-grid-of-dots-on-AMD-GPU-systems).

# Test Plan
The PR should be tested on Mac (ideally with NVidia and AMD GPU), on Window (to check second bug) with AMD and NVidia as well as on Android.
Run the [tests/engine/render/shadows test](https://github.com/highfidelity/hifi_tests/tree/master/tests/engine/render/shadows).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11046/HighFidelity-Beta-PR13515-419e8e6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11046/HighFidelity-Beta-PR13515-419e8e6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11046/HighFidelity-Beta-Interface-PR13515-419e8e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11046/HighFidelity-Beta-PR13515-419e8e6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11046/HighFidelity-Beta-Interface-PR13515-419e8e6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11047/HighFidelity-Beta-PR13515-1a5c382.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11047/HighFidelity-Beta-Interface-PR13515-1a5c382.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11047/HighFidelity-Beta-PR13515-1a5c382.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11047/HighFidelity-Beta-Interface-PR13515-1a5c382.exe

**Comment by vegaslon** [comment]
Not seeing a glitch of shadows on AMD GPU with Windows in this PR.

**Comment by Zvork** [comment]
@vegaslon Would it be possible to see you log file, please?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11048/HighFidelity-Beta-PR13515-51fe60e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11048/HighFidelity-Beta-PR13515-51fe60e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11048/HighFidelity-Beta-Interface-PR13515-51fe60e.dmg

**Comment by vegaslon** [comment]
Sure, please note I am not a tester or employee of High Fidelity. 
https://pastebin.com/duC7Weps

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11048/HighFidelity-Beta-PR13515-51fe60e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11048/HighFidelity-Beta-Interface-PR13515-51fe60e.exe

**Comment by samcake** [comment]
@vegaslon THanks for the feedback but we don;t really see any report of an error with the shaders.
Can you double check that you have Shadows globally enabled ? (in the graphics setting menu)
If you run stable or even the current dev-master, you should see shadows on PC +AMD gpu with the known bug of some  "holes" or "acnee" in the shadow casted.
This pr doesn't fix that specifically, but focus on Mac implying with AMD gpu (since the only discrete gpu for mac or amd since the past 4 years) and seems to be successful there.

We haven't tested on pc amd yet but we know this pr works fine on Nvida PC too.
Inlight of this context could you confirm or inform what you experience ?

Thanks

**Comment by vegaslon** [comment]
Perhaps you have misread what I have stated, in my experience with this PR the so called holes, translucent triangles, seams. When shadows are on, have disappeared with my hardware.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Shadows look good on all platforms. No Shadows on Android, but build ran well.

**Comment by samcake** [comment]
@vegaslon Follow up with me directly if you still see your problem
ping me here on github
I m currently in france
CHeers

**Pull request merged**
