### PR TITLE
workload: Merging upstream master into workload

### PR DESCRIPTION
**Pull request by samcake**
Merging master into workload

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8000/app_12630_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8000/HighFidelity-Beta-PR12630-6d02aa064a9b531c6d537f414d5fa9d425db5575.dmg

**Comment by ZappoMan** [comment]
I don't think you have your target branch set correctly... this is a merge into master... 0 files changed.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8000/HighFidelity-Beta-PR12630-6d02aa064a9b531c6d537f414d5fa9d425db5575.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8004/app_12630_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8004/HighFidelity-Beta-PR12630-6d02aa064a9b531c6d537f414d5fa9d425db5575.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8004/HighFidelity-Beta-PR12630-6d02aa064a9b531c6d537f414d5fa9d425db5575.exe

**Comment by samcake** [comment]
totally fucked up that one, closing

**Pull request closed without merging**
