### PR TITLE
reduce users window flicker when restart script

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Test Notes

Before: If you restart users.js with the users window expanded there's a very noticeable interval in which the window looks borked before it displays property. (And if there was a problem communicating with the users Web API it would most likely stay like this).

borked-users

After: This interval is much reduced.

**Comment by kevinmthomasse** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79cfd2e9dc4f67d0bd1167c86f7e9a501e551f66 available at: https://gist.github.com/ec75ef5792de1eaf8af9d36316deebea<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8145.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8145.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Upon installing PR the ```users.js``` appeared normally as I was logged in.  I was at a maximized screen size.  Attempted multiple screen sizes and the UI looked perfect in a fixed dimension.  Upon reload of ```users.js``` there was a brief flicker however there was no distortion of view or "borked" experience of any kind.

**Pull request merged**
