### PR TITLE
update default avatar to be better with oculus grab triggers

### PR DESCRIPTION
**Pull request by birarda**
- update default mannequin avatar to interact better with grab triggers

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

This PR introduces a slightly different version of the default avatar.

Run this PR. Do not copy settings from your production install. You should be the following avatar.

https://highfidelity.io/marketplace/items/7fe80a1e-f445-4800-9e89-40e677b03bee

You can use the mirror mode (H key) to better see your avatar.

Use an HMD and hand controllers to be sure that the movements of the avatar's body are what you expect.

Have another user connect to your Sandbox (because of the packet version change). Make sure the other user has an empty avatar URL (in Settings -> Avatar) and that you see them as the new default avatar. They should not be in t-pose and you should also see their body movements as you expect.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1614/HighFidelity-Beta-PR10956-9a88a9376712e97dac1fd13b72ca846d5ca1865d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1625/HighFidelity-Beta-PR10956-4caf1e751cf366d5883a73cccf8e096405184918.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1625/HighFidelity-Beta-PR10956-4caf1e751cf366d5883a73cccf8e096405184918.dmg

**Comment by YuppyPlays** [comment]
Testing w/ @CainFoool

**Comment by YuppyPlays** [comment]
Testing complete:

[Myself in HMD, Cain in Desktop to spectate as required]

This PR introduces a slightly different version of the default avatar. **Check, hands look different**
Run this PR. Do not copy settings from your production install. You should be the following avatar.
https://highfidelity.io/marketplace/items/7fe80a1e-f445-4800-9e89-40e677b03bee **Check**
You can use the mirror mode (H key) to better see your avatar. **Fail, mirror mode not working in HMD in this PR**
Use an HMD and hand controllers to be sure that the movements of the avatar's body are what you expect. **Pass**
Have another user connect to your Sandbox (because of the packet version change). Make sure the other user has an empty avatar URL (in Settings -> Avatar) and that you see them as the new default avatar. They should not be in t-pose and you should also see their body movements as you expect. **Pass**

Go to dev-welcome and try sitting on a stool. The mannequin's butt should look like it's appropriate sitting on the stool (as opposed to going through the stool). **Fail, could not connect to dev-welcome, got error <See notes at bottom of comment> however tested a chair in sandbox and avatar was seen inside the chair partially, image below.**

image

Notes: Error when connecting to dev-welcome:
**The domain-server denied a connection request:  "Protocol version mismatch - Domain version: 6888"**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1767/HighFidelity-Beta-PR10956-86ae1c3e912f9a6563981cc84950d6ed738db276.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1767/HighFidelity-Beta-PR10956-86ae1c3e912f9a6563981cc84950d6ed738db276.exe

**Comment by RyanDowne** [comment]
Does this need to be re-reviewed?

**Comment by themelissabrown** [comment]
@birarda does this need another QA pass?

**Comment by birarda** [comment]
@themelissabrown yes please

**Comment by ShoaibSmith** [comment]
Testing

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2856/HighFidelity-Beta-PR10956-86ae1c3e912f9a6563981cc84950d6ed738db276.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2856/HighFidelity-Beta-PR10956-86ae1c3e912f9a6563981cc84950d6ed738db276.exe

**Comment by ShoaibSmith** [comment]
"You can use the mirror mode (H key) to better see your avatar."

Fail. Mirror mode does not work.  

"Use an HMD and hand controllers to be sure that the movements of the avatar's body are what you expect."

Pass.

"Have another user connect to your Sandbox (because of the packet version change). Make sure the other user has an empty avatar URL (in Settings -> Avatar) and that you see them as the new default avatar. They should not be in t-pose and you should also see their body movements as you expect."

Couldn't fully test this part because I could not find anyone available during the time of testing.  

"Go to dev-welcome and try sitting on a stool. The mannequin's butt should look like it's appropriate sitting on the stool (as opposed to going through the stool)."

Fail. Could not connect to dev welcome, I get a error every time I try to connect, but I did test in sandbox and had no problems.

**Comment by sethalves** [comment]
mirror mode was recently moved to ctrl-H

**Comment by ShoaibSmith** [comment]
Ok, Mirror mode works! I was not aware of the update.

**Comment by anshuman64** [comment]
@birarda this has merge conflicts now :(

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3965/HighFidelity-Beta-PR10956-78c5e8414048852026a2df073b0441c3965211de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3967/HighFidelity-Beta-PR10956-1fb7b0df7a2a04946992b898caf6244061e98c32.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3967/HighFidelity-Beta-PR10956-1fb7b0df7a2a04946992b898caf6244061e98c32.exe

**Pull request merged**
