### PR TITLE
Add placeholder image when previous snapshot can't be loaded

### PR DESCRIPTION
**Pull request by zfox23**
**Test Plan:**
Clear your settings. You can use desktop or HMD mode for this test plan.
1. Using the Snapshot app, choose a Snapshot location and take a "Still + GIF" snapshot.
2. When the GIF finishes processing, verify that both images appear in the Snapshot app, and that both images have the "Share" overlay appear on top of them.
3. Close the Snapshot app.
4. From your file explorer, delete the GIF snapshot from your local disk.
5. Open the Snapshot app.
6. Verify that the Still snapshot still appears and has the Share overlay appear on top of it.
7. Verify that the GIF snapshot no longer appears, and is instead replaced by a placeholder image that reads "Could not find last image taken". Also verify that the Share overlay does not appear on top of this placeholder image.
8. Take another set of Still + GIF snapshots.
9. When the GIF finishes processing, verify that both images appear in the Snapshot app, and that both images have the "Share" overlay appear on top of them.

### CODE REVIEW

**Comment by OmegaHeron** [comment]
QA In progress.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/264/HighFidelity-Beta-PR10576-0441d8c70364550cee596b5e0f9a0bbc8de2a5a6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/264/HighFidelity-Beta-PR10576-0441d8c70364550cee596b5e0f9a0bbc8de2a5a6.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Compared this PR behavior to Master 6619 - also tested deleting !gif, both and what happens if interface is closed, reopened and snap dialog opened with last image(s) missing.  All good.

**Pull request merged**
