### PR TITLE
undo bad script-engine AC change

### PR DESCRIPTION
**Pull request by sethalves**
- undo a change that broke script-engines in ACs

### CODE REVIEW

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5660063702344d9261fa4ce00e549afd994be52e available at: https://gist.github.com/5c933ea9e2de6bb8f06d80839a036222<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8877-5660063.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8877-5660063.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5660063702344d9261fa4ce00e549afd994be52e available at: https://gist.github.com/5c933ea9e2de6bb8f06d80839a036222<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8877-5660063.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8877-5660063.dmg

**Pull request merged**
