### PR TITLE
Tablet should work even when not connected to any domain.

### PR DESCRIPTION
**Pull request by hyperlogic**
handControllerGrab.js and WebTablet.js now parents objects to the AVATAR_SELF_ID parentID, instead of using MyAvatar.sessionUUID, which is unavailable when not connected to any domain.

I removed several early returns handControllerGrab.js that prevented grabbing from working if MyAvatar.sessionUUID was invalid.

There were places in the EntityItem.cpp and EntityScriptingInterface.cpp C++ that would log an error if parentID was set to AVATAR_SELF_ID. This was to prevent AVATAR_SELF_ID from ever going over the network. Instead, we now prevent this by replacing all outgoing references of AVATAR_SELF_ID with the sessionID of the current node.

### CODE REVIEW

**Comment by hyperlogic** [comment]
Test Plan:  Verify that the tablet works even when not connected to any domain.  Try the following.

In Desktop Mode:
   * You should be able to use the mouse to move the tablet, by mouse dragging the edge of the tablet.
   * You should be able to navigate the tablet surface by clicking on it with the mouse.
   * You should be able to scroll the tablet surfface by click dragging the surface with the mouse.
   * The tablet should remain stationary on screen as you drive (using the arrow keys) through the world.
   * The close button on the tablet should be functional when clicked on via the mouse.

HMD Mode.
   * The tablet should appear and disappear when you press the APP menu button.  On vive it's the button above the touchpad.
   * When the tablet appears it should appear just above your hand and facing your head.
   * You should be able to grab the tablet by near-grabbing the edge of the tablet.
   * You should be able to click and scroll the tablet content using the far grab laser.
   * You should be able to click and scroll the tablet content using the stylus.
   * When the tablet is visible, it should remain stationary (with respect to your room) as you drive or teleport.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e2e19884bb3f1d5ef8320bd58f16c17f9a01cd4a available at: https://gist.github.com/cba0b58c4879939aca887037a27ff0d3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9571-e2e1988.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9571-e2e1988.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### FAIL


In Desktop Mode:

You should be able to use the mouse to move the tablet, by mouse dragging the edge of the tablet.: 
Can move but bad judder looks like several tablets distributed randomly to left and righ while dragging.
Problem is related to content in view as it does not happen when not connected to a domain.

You should be able to navigate the tablet surface by clicking on it with the mouse. **: SUCCESS**

You should be able to scroll the tablet surfface by click dragging the surface with the mouse.**: SUCCESS**
However scrolling one part of a page a time is tedious. Better to use the scroll-bar.
Scroll bar works if dragging and continues to work if user allows pointer to drift onto page.
Scroll bar stops if user allows pointer to drift onto tablet frame.

The tablet should remain stationary on screen as you drive (using the arrow keys) through the world.**: SUCCESS**

The close button on the tablet should be functional when clicked on via the mouse.**: SUCCESS**


HMD Mode.

The tablet should appear and disappear when you press the APP menu button. On vive it's the button above the touchpad.**: SUCCESS**

When the tablet appears it should appear just above your hand and facing your head.**: SUCCESS**

You should be able to grab the tablet by near-grabbing the edge of the tablet.**: SUCCESS**

You should be able to click and scroll the tablet content using the far grab laser.**: SUCCESS**

You should be able to click and scroll the tablet content using the stylus.**: SUCCESS**
Not good, user has to take a lot of care while scrolling with stylus.
User has to keep the stylus tip in the surface of the tablet, this can be tricky especially if the tablet is held in the other hand.

When the tablet is visible, it should remain stationary (with respect to your room) as you drive or teleport.**: FAIL**
to repro fail: 

	Open tablet.
	Walk.
	While walking touch tablet.
	Observe that tablet becomes detached.

	Open tablet.
	Fly
	While flying touch tablet.
	Observe that tablet initially behaves erratically then disapears from view.
	Rotate view using hand controllers and look for a distant ( 80m ) moving object.
	Press menu button.
	Observe the distant object disappears. ( it was the tablet )


Also had a single occasion where teleport left tablet behind ( might be linked to Walk touch of tablet )

Have not yet tested other avatar viewing tablet position etc.

### Observations:

It might be good to have the tablet remember where it was last closed in desktop mode.

Scrolling for any length of time is tedious and tiring.

**Comment by hyperlogic** [comment]
I cannot reproduce these issues, Can you provide more information about the repro:  For example the first one:


    Open tablet.
    Walk.
    While walking touch tablet.
    Observe that tablet becomes detached.

    * Are you connected to a domain?
    * Are you in desktop or HMD mode?
    * How are you opening the tablet?  Mouse right click? menu button on the hand controller?
    * Define "while walking".  Are you driving using the arrow keys? or physically walking in the room?
    * Define "touch the tablet".  Are you performing a near-grab?  touching with the stylus?

**Comment by sethalves** [comment]
I'm also not able to reproduce either of these problems.  More detail would be very helpful.

**Comment by Nex-Pro** [comment]
did that at dev-welcome

**Comment by Nex-Pro** [comment]
Are you connected to a domain? YES
Are you in desktop or HMD mode? HMD
How are you opening the tablet? Mouse right click? menu button on the hand controller? YES
Define "while walking". Are you driving using the arrow keys? or physically walking in the room? driving
Define "touch the tablet". Are you performing a near-grab? touching with the stylus?

start driving    then while driving  grab the tablet

**Comment by Nex-Pro** [comment]
same for flying ...
start flying with the tablet open

then while flying  grab the tablet

**Comment by cozza13** [comment]
I tested this and could not repro the issue. I think we merge and see if we can repro the issue in dev

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6bef9e888b267a4654e67e6cbfa65d244ce0f32c available at: https://gist.github.com/cba0b58c4879939aca887037a27ff0d3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9571-6bef9e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9571-6bef9e8.dmg

**Pull request merged**
