### PR TITLE
Beta Release Candidate 7 - including up to Development Release 4790

### PR DESCRIPTION
**Pull request by ZappoMan**
- fix zombie process on shutdown in case of pending resource downloads
- fix zombie process on shutdown from windows "close" button while modal dialog box was up
- better logging or resource retries
- new model icon in edit tools
- fix crash related to resource reload
- fix "Go Home" on OSX
- fix star shader compile failure on some video cards
- new renderRates.js script to show render and simulation rates over time
- add "Reveal Scripts Folder" to the Running Scripts dialog box
- new scripts for render performance testing
- fix memory leak related to avatar motion states
- fix crash related to canceled resource downloads
- fix crash on shutdown in save settings
- fix ATP failure for networks with smaller than 1500 byte MTU
- reduce GPU texture memory usage on video cards with less memory
- physics performance improvements
- fix crash in OBJ file parsing
- move default avatar animations locally
- styling changes to edit tools
- improved performance of stereo (HMD) rendering
- new default avatar: being of light
- fixes to larger than 35 minute clock skew between clients and servers
- fixes to avatar eye position/look at behavior

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88ab52d3409a465ea3d8632bd17eecf39c1528fd available at: https://gist.github.com/4bbbc3947ab16d8a5e02d296d7c385cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7749.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7749.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7749
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience |free  
----------------------------------|----------|---------|------------|-----
Render Rate:                      |52.97     |57.91    |57.98       |60.52
Present Rate:                     |60.00     |60.03    |60.00       |60.00
Simrate:                          |56.11     |57.00    |53.99       |59.90
Render Stats Num Buffers:         |2539      |3093     |6494        |1573
Render Stats gpu::Buffer Memory:  |38.4Mb    |50.4Mb   |23.9Mb      |137.0Mb
Render Stats Num Textures:        |241       |264      |44          |162
Render Stats gpu::Texture Memory: |729.6Mb   |1012.5Mb |250.4Mb     |503.0Mb
Render Stats Triangles:           |606k      |860k     |1091k       |1001k
Render Stats Drawcalls:           |253       |1458     |296         |171
Render Stats State Changes:	  |236       |183      |46          |126
Render Stats Items:               |288       |254      |1193        |299
Render Stats Timing:              |12.1ms    |55.9ms   |13.8ms      |21.7ms
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      |4096Mb
GPU-Z Initial Memory		  |278Mb     |278Mb    |278Mb       |278Mb
GPU-Z Memory Used		  |1633Mb    |3347Mb   |691Mb       |983Mb
GPU-Z Memory Load		  |23%       |31%      |16%         |28%

**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Partially successful test.  Upon running test at ```cellscience``` the Interface crashed, bugsplat reported and log file included for deeper inspection.  Upon a relog, successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** Partially successful test.  @judasshuffle installed identcial PR build on a Windows 10 Desktop.  Upon install of PR, I attempted to connect to him by clicking on his name in the ```users.js``` list and it would not allow me to successfully connect to him.  @judasshuffle checked his Kaspersky firewall settings and found ```sandbox.exe``` was set to ```Prompt For Action``` however never alerted him to make a selection.  @judasshuffle then manually selected ```Allow``` and I thought I was able to successfully go to his ```localhost``` domain however I was unable to see his avatar and he was unable to see my avatar.  All 5 servers were up however each avatar did not register a value.  I suspect I was actually on my own ```localhost``` and not his.  @judasshuffle moved furniture around and the change did not happen in my view further suspecting I am not connecting to his ```localhost```.  I will attach the log for further inspection.  Upon installing the PR on my machine, @judasshuffle was able to successfully connect to me at my ```localhost```.  Unexpected behavior that is not consistent between users.  
**Successful Logout/Crash:** Initial crash on ```cellscience``` details listed above.  Final logout successful.
localhost performance
playa performance
cellscience performance
free performance
judas firewall settings
localhost test to judas however remaining on my own localhost
[hifi-log.txt](https://github.com/highfidelity/hifi/files/233467/hifi-log.txt)

**Comment by judasshuffle** [comment]
Smokeys log failing to access my local host on the above build 
[hifi-log Smokey trying to enter Judas local host 240416 [24179].txt](https://github.com/highfidelity/hifi/files/233475/hifi-log.Smokey.trying.to.enter.Judas.local.host.240416.24179.txt)

**Comment by OmegaHeron** [comment]
Windows 7 (64 bit) - Core i7 cpu 16G RAM/Nvidia GTX660M GPU 2G VRAM

Running playaPerformanceTest.js at playa - I lost all graphics - pure black screen.  Interface did not crash nor log anything meaningful - once script finished I was returned to unconnected space (still pure black screen - no stars) - Hit enter and typed a domain name in - connected to it (via connection sound and log display) did not recover visuals.  CPU use was very high once I enter the black hole.

Next attempt - it ran its test - I returned to unconnected space - a black screen with a "glob of pixels" in center - interface GUI would disappear showing desktop briefly - menus/mouse were very unresponsive - I finally manged to grab a screen shot by timing disappearance of Interface UI and some luck.

badreaction

Third try - same thing - it seemed as was about to succeed then a photo-real AV dropped in and things went to hades rapidly leading to loss of graphics in disconntected space and connected.

badreaction3

Fourth try success - no avatars other than my own were in visible space

playa4

I'll continue with this after dinner.

**Comment by OmegaHeron** [comment]
I submitted a few bugsplats with this - I'm not sure anything I've found is a deal breaker, RC6 simply crashes while this survives if not pushed too far on my 2 gig vram card.

Tested server side with Linux, no issues.

Had a friend who I've worked with for a very long time spend 4+ hours in HF this evening (using this PR) and overall it was a stable experience for both of us.  It'll be interesting to see how much this all changes for me sometime in next week to ten days when I move from the old GTX660M to GTX970

**Comment by cozza13** [comment]
QA PAss

**Comment by Nex-Pro** [comment]
## QA Test
**PR Build:** 7749
**Testing Architecture:** 64-bit PC Desktop 16gb ram
**Testing OS:** Windows 10

**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience 
----------------------------------|---------:|--------:|-----------:
Render Rate:                      |~60.00    |~60.00   |~60.00      
Present Rate:                     |~60.00    |~60.00   |~60.00      
Simrate:                          |~60.00    |~60.00   |57.0 to 60.0
Render Stats Num Buffers:         |4519      |2449     |1994        
Render Stats gpu::Buffer Memory:  |47.4Mb    |39.9Mb   |18.9Mb      
Render Stats Num Textures:        |211       |266      |48          
Render Stats gpu::Texture Memory: |774.3Mb   |1352.5Mb |249.7Mb     
Render Stats Triangles:           |450k      |1070k    |443k       
Render Stats Drawcalls:           |136       |1232     |159         
Render Stats State Changes:	  	  |127       |204      |30          
Render Stats Items:               |161       |257      |732        
Render Stats Timing:              |7.3ms     |1016.2ms |21.3ms      
                                  |          |         |              
GPU-Z Memory Size                 |2048Mb    |2048Mb   |2048Mb      
GPU-Z Memory Used Initial 	      |386Mb     |386Mb    |386Mb       
GPU-Z Memory Used		          |1481Mb    |1613Mb   |1765Mb       
GPU-Z GPU Load initial  	      |3%        |3%       |3%          
GPU-Z GPU Load		              |19 to 60% |~40%     |19 to 45%          
GPU-Z Mem Controller Load Initial |5%        |  5%     |5%          
GPU-Z Mem Controller Load         |11 to 52% |~20%     |~37%          
GPU-Z Power Consumption	 Initial  |5.7%      |5.7%     |5.7%        
GPU-Z Power Consumption	          |17.5%     |~32%     |~15%        

**localhost ‘createtestblocks.js’ Result:** Success.
**localhost ATP Upload :** Success.
**localhost ‘playaPerformanceTest.js’ Result:** Success.  Test results well below red line.  See Screen shot.
**playa ‘playaPerformanceTest.js’ Result:** Success.  Test results below red line.  See Screen shot.
**cellscience ‘playaPerformanceTest.js’ Result:** success. Results well below red line. See Screen shot.
**Additional Test Results:** 
changing to various avatars: Success.
upload of models: Success.
creation of primitives: Success.
**Successful Logout/Crash:** Successful logout.
localhost_performance_test_result
cellscience_performance_test_result
playa_performance_test_result
result_of_right_click_in_model_upload_dialog

**Pull request merged**
