### PR TITLE
make file dialog resizable and movable

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- File browser dialog can be resized
- File browser dialog successfully selects files after being resized
- File browser dialog can be moved
- File browser dialog successfully selects files after being moved

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9ec6b774608026ef53d9d14e050b8b85e4997003 available at: https://gist.github.com/134cbcc0fb1a3bed77bee309e9793380<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7966.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7966.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Testing Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**
Standard tests pass.

File browser dialog can be resized - Yes
File browser dialog successfully selects files after being resized - Yes
File browser dialog can be moved - Yes
File browser dialog successfully selects files after being moved - Yes

**Comment by RyanDowne** [comment]
Worked well for me on PC

**Pull request merged**
