### PR TITLE
0.73.0: tweak avatar update priority coefs for load tests

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR for 0.73.

This PR provides a change to the way we compute the priority of avatar updates when there are large crowds.  We're dropping the priority of the "proximity to center of view" component of the formula which will allow nearby avatars with large "apparent size" but who are off to the side of center to get higher update rates.  The hope is to provide a slightly better experience when hanging out in large avatar crowd.

The internal manuscript case for this effort is 18571:

https://highfidelity.manuscript.com/f/cases/18571/Tune-OtherAvatar-prioritization-to-give-more-weight-to-those-nearby-but-off-center-from-view

**Test Plan**:

**(1)** Login to engine-dev.  Makprobablye sure there is a big crowd  of bot avatars.  If no bot army is present please ask Birarda to deploy it.

**(2)** Enable the following debug option:
**Developer --> Avatar --> Show Receive Stats**
This will add per-avatar bandwidth and update rate to the display name.  The text may be hard to see because of the density of the crowd and some rendering bugs, but the thing you're trying to pay attention to is the update rate (Hz).

Note: the measured value of the update rate is an average has a slow update timescale of a 2-3 seconds.  So when the the true update rate for an avatar changes it may take 6 - 10 seconds for the measured value shown in the display name to actually reflect that change.  However, the apparent animation update of the joints of the avatar should be immediately visible.

Another Note: measuring joint update rate with the naked eye is a little tricky and suffers from a complication where if the interface render pipeline is severely loaded the true update rate might be lower than the packet update rate received from the server and shown in the debug stats.  In other words: don't try this test on a low-end machine.

**(3)** While standing in the crowd pay attention to the animation update rate of people near and far, close to center of view and off to the left or right.  The goals here are: (a) we want nearby avatars to update faster than those far away (sort by apparent **size**), (b) we want avatars near the center of the view to update faster than those off to the side (sort by **center**), (c) we want all avatars to update at some rate (none should be completely unmoving) (sort by **age** of last update).

The goals are at odds with each other when we don't have enough resources to go around (crowd is too big) so we blend them together and compile a total priority.  The blending coefficients are what are being changed in this PR.

**(4)** The old blending coefficients are:
```
size = 8
center = 4
age = 1
```
The new blending coefficients are:
```
size = 8
center = 0.25
age = 1
```
The question we're trying to answer is: **Are the new coefficients better than the old ones?**

**(5)** An avatar with kick rights in the domain can change these coefficients real-time for testing purposes.  The values are changed on both the tester's interface and the domain's avatar-mixer, but only as long as those processes are running: a restart will revert to old coefficients.  You can query the values by typing the following commands into the JS console (CTRL + ALT + J):
```
AvatarManager.getAvatarSortCoefficient("size")
AvatarManager.getAvatarSortCoefficient("center")
AvatarManager.getAvatarSortCoefficient("age")
```
The values can be changed like so:
```
AvatarManager.setAvatarSortCoefficient("size", 1)
AvatarManager.setAvatarSortCoefficient("center", 2)
AvatarManager.setAvatarSortCoefficient("age", 3)
```

**(6)** You can verify the test feature is working by setting the values to like so:
**size = 1, This PR provides a change to the way we compute the priority of avatar updates when there are large crowds.  We're dropping the priority of the "proximity to center of view" component of the formula which will allow nearby avatars with large "apparent size" but who are off to the side of center to get higher update rates.  The hope is to provide a slightly better experience when hanging out in large avatar crowd.

The internal manuscript case for this effort is 18571:

https://highfidelity.manuscript.com/f/cases/18571/Tune-OtherAvatar-prioritization-to-give-more-weight-to-those-nearby-but-off-center-from-view

**Test Plan**:

**(1)** Login to engine-dev.  Makprobablye sure there is a big crowd  of bot avatars.  If no bot army is present please ask Birarda to deploy it.

**(2)** Enable the following debug option:
**Developer --> Avatar --> Show Receive Stats**
This will add per-avatar bandwidth and update rate to the display name.  The text may be hard to see because of the density of the crowd and some rendering bugs, but the thing you're trying to pay attention to is the update rate (Hz).

Note: the measured value of the update rate is an average has a slow update timescale of a 2-3 seconds.  So when the the true update rate for an avatar changes it may take 6 - 10 seconds for the measured value shown in the display name to actually reflect that change.  However, the apparent animation update of the joints of the avatar should be immediately visible.

Another Note: measuring joint update rate with the naked eye is a little tricky and suffers from a complication where if the interface render pipeline is severely loaded the true update rate might be lower than the packet update rate received from the server and shown in the debug stats.  In other words: don't try this test on a low-end machine.

**(3)** While standing in the crowd pay attention to the animation update rate of people near and far, close to center of view and off to the left or right.  The goals here are: (a) we want nearby avatars to update faster than those far away (sort by apparent **size**), (b) we want avatars near the center of the view to update faster than those off to the side (sort by **center**), (c) we want all avatars to update at some rate (none should be completely unmoving) (sort by **age** of last update).

The goals are at odds with each other when we don't have enough resources to go around (crowd is too big) so we blend them together and compile a total priority.  The blending coefficients are what are being changed in this PR.

**(4)** The old blending coefficients are:
```
size = 8
center = 4
age = 1
```
The new blending coefficients are:
```
size = 8
center = 0.25
age = 1
```
The question we're trying to answer is: **Are the new coefficients better than the old ones?**

**(5)** An avatar with kick rights in the domain can change these coefficients real-time for testing purposes.  The values are changed on both the tester's interface and the domain's avatar-mixer, but only as long as those processes are running: a restart will revert to old coefficients.  You can query the values by typing the following commands into the JS console (CTRL + ALT + J):
```
AvatarManager.getAvatarSortCoefficient("size")
AvatarManager.getAvatarSortCoefficient("center")
AvatarManager.getAvatarSortCoefficient("age")
```
The values can be changed like so:
```
AvatarManager.setAvatarSortCoefficient("size", 1)
AvatarManager.setAvatarSortCoefficient("center", 2)
AvatarManager.setAvatarSortCoefficient("age", 3)
```

**(6)** You can verify the test feature is working by setting the values to like so:
**size = 1, center = 0, age = 0**    --> avatars with large apparent size will update fast, update rate falls offas avataThis PR provides a change to the way we compute the priority of avatar updates when there are large crowds.  We're dropping the priority of the "proximity to center of view" component of the formula which will allow nearby avatars with large "apparent size" but who are off to the side of center to get higher update rates.  The hope is to provide a slightly better experience when hanging out in large avatar crowd.

The internal manuscript case for this effort is 18571:

https://highfidelity.manuscript.com/f/cases/18571/Tune-OtherAvatar-prioritization-to-give-more-weight-to-those-nearby-but-off-center-from-view

**Test Plan**:

**(1)** Login to engine-dev.  Makprobablye sure there is a big crowd  of bot avatars.  If no bot army is present please ask Birarda to deploy it.

**(2)** Enable the following debug option:
**Developer --> Avatar --> Show Receive Stats**
This will add per-avatar bandwidth and update rate to the display name.  The text may be hard to see because of the density of the crowd and some rendering bugs, but the thing you're trying to pay attention to is the update rate (Hz).

Note: the measured value of the update rate is an average has a slow update timescale of a 2-3 seconds.  So when the the true update rate for an avatar changes it may take 6 - 10 seconds for the measured value shown in the display name to actually reflect that change.  However, the apparent animation update of the joints of the avatar should be immediately visible.

Another Note: measuring joint update rate with the naked eye is a little tricky and suffers from a complication where if the interface render pipeline is severely loaded the true update rate might be lower than the packet update rate received from the server and shown in the debug stats.  In other words: don't try this test on a low-end machine.

**(3)** While standing in the crowd pay attention to the animation update rate of people near and far, close to center of view and off to the left or right.  The goals here are: (a) we want nearby avatars to update faster than those far away (sort by apparent **size**), (b) we want avatars near the center of the view to update faster than those off to the side (sort by **center**), (c) we want all avatars to update at some rate (none should be completely unmoving) (sort by **age** of last update).

The goals are at odds with each other when we don't have enough resources to go around (crowd is too big) so we blend them together and compile a total priority.  The blending coefficients are what are being changed in this PR.

**(4)** The old blending coefficients are:
```
size = 8
center = 4
age = 1
```
The new blending coefficients are:
```
size = 8
center = 0.25
age = 1
```
The question we're trying to answer is: **Are the new coefficients better than the old ones?**

**(5)** An avatar with kick rights in the domain can change these coefficients real-time for testing purposes.  The values are changed on both the tester's interface and the domain's avatar-mixer, but only as long as those processes are running: a restart will revert to old coefficients.  You can query the values by typing the following commands into the JS console (CTRL + ALT + J):
```
AvatarManager.getAvatarSortCoefficient("size")
AvatarManager.getAvatarSortCoefficient("center")
AvatarManager.getAvatarSortCoefficient("age")
```
The values can be changed like so:
```
AvatarManager.setAvatarSortCoefficient("size", 1)
AvatarManager.setAvatarSortCoefficient("center", 2)
AvatarManager.setAvatarSortCoefficient("age", 3)
```

**(6)** You can verify the test feature is working by setting the values to like so:
**size = 1, center = 0, age = 0**    --> avatars with large apparent size will update fast, update rate falls offas avatars get smaller with distance , but some far away may never update

**size = 0, center = 1, age = 0**  --> avatars near center of view update fast, update rate falls off the further they are to the side, some avatars way off to the side may never update

**size = 0, center = 0, age = 1** --> all avatars update at the same slow rate

**(7)** Set the values to the old defaults:
**size = 8, center = 4, age = 1**
Note the update rate of people who are nearby but off to the side of the window (probably terribly slow) and compare with the update rate of someone further away but right in the center of the screen (should be plenty fast).

**(8)** Set the values to the new defaults:
**size = 8, center = 0.25, age = 1**
Note the update rate of people who are nearby but off to the side of the window (should be slow but not terrible) and compare with the update rate of someone further away but right in the center of the screen (should be slow but not terrible).

**(9)** Optional: play with the values to try to find the best compromise.  Note: only the relative values of the parameters matter, so **8:4:1** is the same as **16:8:2**.  Best to set one of the values to 1.0 and then set the other two as multiples or fraction of that.  If you come up with a better balance of coefficients for the crowd in engine-dev feel free to share.rs get smaller with distance , but some far away may never update

**size = 0, center = 1, age = 0**  --> avatars near center of view update fast, update rate falls off the further they are to the side, some avatars way off to the side may never update

**size = 0, center = 0, age = 1** --> all avatars update at the same slow rate

**(7)** Set the values to the old defaults:
**size = 8, center = 4, age = 1**
Note the update rate of people who are nearby but off to the side of the window (probably terribly slow) and compare with the update rate of someone further away but right in the center of the screen (should be plenty fast).

**(8)** Set the values to the new defaults:
**size = 8, center = 0.25, age = 1**
Note the update rate of people who are nearby but off to the side of the window (should be slow but not terrible) and compare with the update rate of someone further away but right in the center of the screen (should be slow but not terrible).

**(9)** Optional: play with the values to try to find the best compromise.  Note: only the relative values of the parameters matter, so **8:4:1** is the same as **16:8:2**.  Best to set one of the values to 1.0 and then set the other two as multiples or fraction of that.  If you come up with a better balance of coefficients for the crowd in engine-dev feel free to share.center = 0, age = 0**    --> avatars with large apparent size will update fast, update rate falls offas avatars get smaller with distance , but some far away may never update

**size = 0, center = 1, age = 0**  --> avatars near center of view update fast, update rate falls off the further they are to the side, some avatars way off to the side may never update

**size = 0, center = 0, age = 1** --> all avatars update at the same slow rate

**(7)** Set the values to the old defaults:
**size = 8, center = 4, age = 1**
Note the update rate of people who are nearby but off to the side of the window (probably terribly slow) and compare with the update rate of someone further away but right in the center of the screen (should be plenty fast).

**(8)** Set the values to the new defaults:
**size = 8, center = 0.25, age = 1**
Note the update rate of people who are nearby but off to the side of the window (should be slow but not terrible) and compare with the update rate of someone further away but right in the center of the screen (should be slow but not terrible).

**(9)** Optional: play with the values to try to find the best compromise.  Note: only the relative values of the parameters matter, so **8:4:1** is the same as **16:8:2**.  Best to set one of the values to 1.0 and then set the other two as multiples or fraction of that.  If you come up with a better balance of coefficients for the crowd in engine-dev feel free to share.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13140/HighFidelity-Beta-PR14039-a59d7eb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13140/HighFidelity-Beta-PR14039-a59d7eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13140/HighFidelity-Beta-Interface-PR14039-a59d7eb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13140/HighFidelity-Beta-PR14039-a59d7eb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13140/HighFidelity-Beta-Interface-PR14039-a59d7eb.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin941
New update rate looks good and makes close avatars much more smooth.

**Comment by samcake** [comment]
@conklin94122 good to merge asap, thanks

**Pull request merged**
