### PR TITLE
Support for running Interface without a microphone

### PR DESCRIPTION
**Pull request by kencooke**
When a client has no audio input devices, the audio-mixer doesn't receive an inbound stream, and does not generate an outbound mix for that client. Fixed in this PR by emulating a silent mic when no input devices are present.

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by kencooke** [comment]
### Test Plan

With no input devices, you should now hear audio from the server. When input devices are connected, Interface should behave as before.

- Verify you can hear audio from the server with no input devices (either unplug them all, or disable using Windows "Recording devices" Properties). In the Interface "stats" window, you should see 100 packets/second of SILENT packets.
- While running with no input devices, verify that you can plug in and select a new input device. Once selected, mic audio should begin to work.
- With only one input device, unplug it while running and verify that you continue to receive audio from the server.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2405/HighFidelity-Beta-PR11158-ee752df653944297e020ed2a776bcbace68d9954.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2405/HighFidelity-Beta-PR11158-ee752df653944297e020ed2a776bcbace68d9954.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
-------- | --------
Verify you can hear audio from the server with no input devices (either unplug them all, or disable using Windows "Recording devices" Properties). In the Interface "stats" window, you should see 100 packets/second of SILENT packets. | Pass (See notes)
While running with no input devices, verify that you can plug in and select a new input device. Once selected, mic audio should begin to work. | Pass
With only one input device, unplug it while running and verify that you continue to receive audio from the server. | Pass

## Test Notes

The stats window was differentiating between 99 and 100 silent packets. Pretty sure this is normal but just wanted to take note.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
