### PR TITLE
Update sit script in the repo

### PR DESCRIPTION
**Pull request by Atlante45**
The animation roles filter of the sit script was changed a while ago but was never propagated to the repo.

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
1) Download the green chair from the marketplace.
2) Edit the entity properties and change the script URL to: https://raw.githubusercontent.com/Atlante45/hifi/c0da0cb43904773a0f46a11574fa48cdd1f33dd1/scripts/tutorials/entity_scripts/sit.js
3) Make sure that when you sit, your avatar actually is in a seated position.

NOTE: There are currently other bugs filed that relate to the sit script. That means managing to sit on the chair might be very unreliable. This PR does not attempt to fix this.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1813/HighFidelity-Beta-PR11013-c0da0cb43904773a0f46a11574fa48cdd1f33dd1.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1813/HighFidelity-Beta-PR11013-c0da0cb43904773a0f46a11574fa48cdd1f33dd1.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

Tested script in this PR & Master just for the sake of consistency and curiosity:

PR (11013): **Pass?** See notes.
Master (6898): **Pass?** See notes.


Notes:
In PR & Master avatar is shown a bit inside the chair? I'm almost certain this is normal given that the chair does this normally, if not please let me know. (Image below taken in PR, but is the same for with/without script in either build)
image

**Comment by Atlante45** [comment]
@YuppyPlays Yes, this is a content issue related to the Woody avatar.
But from your screenshot, I can see that the avatar is in the sitting animation, so this is a QA PASS.

**Pull request merged**
