### PR TITLE
case 2287: adding back null check for default devices

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2287

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21638/HighFidelity-Beta-PR16280-c3a2d8f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21638/HighFidelity-Beta-Interface-PR16280-c3a2d8f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21638/HighFidelity-Beta-PR16280-c3a2d8f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21638/HighFidelity-Quest-Beta-PR16280-c3a2d8f.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21647/HighFidelity-Beta-PR16280-98f2617.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21647/HighFidelity-Beta-Interface-PR16280-98f2617.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21647/HighFidelity-Beta-PR16280-98f2617.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21647/HighFidelity-Quest-Beta-PR16280-98f2617.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21647/HighFidelity-Beta-PR16280-98f2617.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21647/HighFidelity-Beta-Interface-PR16280-98f2617.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21666/HighFidelity-Beta-PR16280-436d840.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21666/HighFidelity-Quest-Beta-PR16280-436d840.apk)

**Comment by JeffClinton** [comment]
Pre-merge test of PR16280 failed.  A crash was discovered when connecting air pods while audio settings were open.  Please note this was done with simplified UI active due to an issue with radio buttons being unselectable in master.
https://github.com/highfidelity/hifi/pull/16280

This resulted in 3 different backtraces:
https://share.backtrace.io/api/share/wvx3DoyyqZwRVcSuldkcSy1
https://share.backtrace.io/api/share/YcGBOkosyiuox3vKM8qdEO3
https://share.backtrace.io/api/share/fFCVosYolx1jK84kwhcbx1D1

Steps to repro:
1. Pair air pods to Mac, then disconnect them (verify in bluetooth settings in top bar)
2. Launch PR16280
3. Enter a domain
4. Enable simplified UI
5. Put air pods into ears (they auto-detect when inserted)

Result:
Crash.

Expected result:
Output switches to air pods.

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21672/HighFidelity-Beta-PR16280-436d840.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21672/HighFidelity-Quest-Beta-PR16280-436d840.apk)

**Pull request closed without merging**
