### PR TITLE
Revert "Defer avatar PoP check"

### PR DESCRIPTION
**Pull request by howard-stearns**
Reverts highfidelity/hifi#15579

Let's see where we are now in current code, per https://highfidelity.atlassian.net/browse/BUGZ-236

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20391/HighFidelity-Beta-PR15930-07e4452.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20391/HighFidelity-Beta-Interface-PR15930-07e4452.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20391/HighFidelity-Beta-PR15930-07e4452.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20391/HighFidelity-Beta-Interface-PR15930-07e4452.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20391/HighFidelity-Beta-PR15930-07e4452.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20391/HighFidelity-Quest-Beta-PR15930-07e4452.apk)

**Comment by howard-stearns** [comment]
Closed in favor of https://github.com/highfidelity/hifi/pull/15954

**Pull request closed without merging**
