### PR TITLE
Beta Release 26 - Includes up to Developer Release 5648

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

Smoke Test

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7cca8f0a6600b2927e44051cfc86e6f267127875 available at: https://gist.github.com/4b384b9e7b8a0aeefb792412421739f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-7cca8f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-7cca8f0.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |58
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |53
**CPU Buffer Count**: |1912 |3491 |2582
**GPU Buffer Count**: |551 |310 |365
**CPU Memory Usage**: |21778432 |62840832 |42307584
**GPU Memory Usage**: |11141120 |8732672 |15249408
**CPU Texture Count**: |230 |284 |243
**GPU Texture Count**: |179 |112 |146
**GPU Transfer Count**: |44 |0 |17
**CPU Texture Memory Usage**: |493241340 |675237136 |373943568
**GPU Texture Memory Usage**: |290212538 |489807886 |299770125
**GPU Virtual Memory Usage**: |775347676|485203809|484264818
**Triangle Count**: |267861 |210131 |299355
**Triangle Rate**: |16741312 |11673944 |11974200
**API Drawcall Count**: |160 |103 |155
**Drawcall Count**: |167 |103 |155
**Drawcall Rate**: |10437 |5722 |6200
**State Changes Texture Count**:|304 |141 |309
**Pipeline Count**: |59 |45 |110
**Item Opaques**: |217 |106 |117
**Item Translucents**: |66 |13 |97
**Item Lights**: |13 |23 |16
**Timing Opaques**: |0.86 |0.368 |0.46
**Timing Translucents**: |0.124 |0.014 |0.278
**Timing Lighting**: |0.085 |0.065 |0.087
**Render Frame**: |1.85 |1.042 |1.752


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|N/A
**Test 7**|Retest the kick function|N/A
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop Mode - 1600x900 Full Screen - Vsync locked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60|60|60
**CPU Buffer Count**: |2638 |4671 |4182
**GPU Buffer Count**: |876 |1521 |1161
**CPU Memory Usage**: |32804864 |79839232 |83087360
**GPU Memory Usage**: |21618688 |54288384 |43327488
**CPU Texture Count**: |247 |321 |297
**GPU Texture Count**: |215 |272 |274
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |87338160 |185273616 |88866064
**GPU Texture Memory Usage**: |687777363 |1199656093 |1096867170
**GPU Virtual Memory Usage**: |687777363|1199656093|1096867170
**Triangle Count**: |222061 |892608 |296078
**Triangle Rate**: |14804066 |55788000 |18504875
**API Drawcall Count**: |144 |321 |144
**Drawcall Count**: |151 |364 |147
**Drawcall Rate**: |10066 |22750 |9187
**State Changes Texture Count**:|259 |317 |233
**Pipeline Count**: |18 |39 |41
**Item Opaques**: |256 |454 |121
**Item Translucents**: |101 |57 |32
**Item Lights**: |16 |81 |4
**Timing Opaques**: |1.014 |1.586 |0.549
**Timing Translucents**: |0.261 |0.072 |0.1
**Timing Lighting**: |0.113 |0.108 |0.12
**Render Frame**: |2.307 |2.938 |1.677

Desktop Mode - 1600x900 Full Screen - Vsync unlocked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |378 |238 |359
**Present Rate**: |378 |238 |359
**Present New Rate**: |335 |226 |286
**CPU Buffer Count**: |1739 |3929 |4059
**GPU Buffer Count**: |657 |1337 |1158
**CPU Memory Usage**: |15917056 |63991808 |87912448
**GPU Memory Usage**: |10547200 |43950080 |48705536
**CPU Texture Count**: |219 |297 |297
**GPU Texture Count**: |189 |252 |272
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |78621040 |173083088 |88930768
**GPU Texture Memory Usage**: |598103584 |1117497114 |1096781074
**GPU Virtual Memory Usage**: |598103584|1117497114|1096781074
**Triangle Count**: |258826 |836496 |428890
**Triangle Rate**: |129413000 |278832000 |142963333
**API Drawcall Count**: |229 |329 |274
**Drawcall Count**: |5849 |373 |2090
**Drawcall Rate**: |2924500 |124333 |696666
**State Changes Texture Count**:|442 |349 |390
**Pipeline Count**: |100 |46 |92
**Item Opaques**: |251 |462 |232
**Item Translucents**: |70 |64 |44
**Item Lights**: |16 |79 |14
**Timing Opaques**: |0.856 |1.591 |0.727
**Timing Translucents**: |0.132 |0.091 |0.132
**Timing Lighting**: |0.057 |0.149 |0.147
**Render Frame**: |1.588 |3.052 |1.925

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |2386 |4481 |4070
**GPU Buffer Count**: |912 |1482 |1272
**CPU Memory Usage**: |41955328 |89833472 |87924736
**GPU Memory Usage**: |28565504 |66428928 |58109952
**CPU Texture Count**: |223 |297 |296
**GPU Texture Count**: |199 |254 |286
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |65579376 |162138576 |22153680
**GPU Texture Memory Usage**: |788184897 |1302859830 |1356587272
**GPU Virtual Memory Usage**: |788184897|1302859830|1356587272
**Triangle Count**: |430304 |1837832 |1027524
**Triangle Rate**: |33100307 |141371692 |79040307
**API Drawcall Count**: |150 |329 |306
**Drawcall Count**: |294 |723 |4185
**Drawcall Rate**: |22615 |55615 |321923
**State Changes Texture Count**:|284 |336 |444
**Pipeline Count**: |62 |43 |92
**Item Opaques**: |198 |466 |274
**Item Translucents**: |101 |56 |51
**Item Lights**: |14 |83 |14
**Timing Opaques**: |0.737 |1.75 |1.193
**Timing Translucents**: |0.224 |0.127 |0.16
**Timing Lighting**: |0.152 |0.308 |0.115
**Render Frame**: |2.122 |3.442 |2.476

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and do tutorial|N/A
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Retest the kick function|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A

CPU use remains same as RC25, no need to attach graphs.
Memory Leak testing shows none for system RAM.
Tested with Dynamic Texture Management and Incremental Texture Transfer **off**.

**Comment by Nex-Pro** [comment]
### PR #8996 Beta Release 26

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive


## QA Test

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP** SUCCESS
**Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js'** SUCCESS

QA Pass** SUCCESS

**Additional Test Results + Observations**: ***Michelle assisted with harmonic oscillator test.***


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |90 |78
**CPU Buffer Count**: |2730 |4839 |1475
**GPU Buffer Count**: |1036 |1296 |376
**CPU Memory Usage**: |42418176 |90701824 |35028992
**GPU Memory Usage**: |28614656 |56872960 |27136000
**CPU Texture Count**: |232 |359 |141
**GPU Texture Count**: |211 |285 |137
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |38562992 |334236944 |15797520
**GPU Texture Memory Usage**: |1031447449 |1438871101 |676441661
**GPU Virtual Memory Usage**: |1219223749|1737042955|982898670
**Triangle Count**: |799096 |2040288 |290799
**Triangle Rate**: |72645090 |185480727 |29079900
**API Drawcall Count**: |235 |344 |30
**Drawcall Count**: |6070 |758 |37
**Drawcall Rate**: |551818 |68909 |3700
**State Changes Texture Count**:|418 |346 |45
**Pipeline Count**: |97 |39 |38
**Item Opaques**: |265 |551 |6
**Item Translucents**: |95 |47 |16
**Item Lights**: |16 |97 |0
**Timing Opaques**: |0.938 |1.517 |0.108
**Timing Translucents**: |0.171 |0.065 |0.035
**Timing Lighting**: |0.194 |0.111 |0.222
**Render Frame**: |2.443 |2.77 |1.293


After switching to desktop mode:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |322 |235 |342
**Present Rate**: |317 |230 |342
**Present New Rate**: |207 |162 |222
**CPU Buffer Count**: |2730 |4542 |4414
**GPU Buffer Count**: |1030 |1145 |1287
**CPU Memory Usage**: |42418176 |94019584 |88371200
**GPU Memory Usage**: |28336128 |45600768 |53854208
**CPU Texture Count**: |233 |291 |301
**GPU Texture Count**: |211 |184 |286
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |38562992 |371887376 |104185104
**GPU Texture Memory Usage**: |838070557 |979758002 |1223851204
**GPU Virtual Memory Usage**: |1025846857|1176600523|1460036940
**Triangle Count**: |663816 |1122197 |811496
**Triangle Rate**: |165954000 |187032833 |270498666
**API Drawcall Count**: |304 |391 |350
**Drawcall Count**: |2990 |477 |364
**Drawcall Rate**: |747500 |79500 |121333
**State Changes Texture Count**:|536 |389 |486
**Pipeline Count**: |74 |65 |92
**Item Opaques**: |241 |447 |195
**Item Translucents**: |96 |48 |49
**Item Lights**: |16 |80 |13
**Timing Opaques**: |0.903 |1.23 |0.658
**Timing Translucents**: |0.18 |0.058 |0.137
**Timing Lighting**: |0.127 |0.125 |0.138
**Render Frame**: |2.12 |2.424 |1.841

**There is an issue with the validity of the stats when frame rates are un-capped.
	I observed that there was cross-column updating of stats. This did not happen
	in the stats below or in the HMD stats.**

In desktop mode after restart:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |59 |58
**CPU Buffer Count**: |2575 |4365 |4249
**GPU Buffer Count**: |895 |1111 |887
**CPU Memory Usage**: |34365440 |91721728 |72908800
**GPU Memory Usage**: |22425600 |37601280 |31150080
**CPU Texture Count**: |251 |287 |285
**GPU Texture Count**: |218 |192 |197
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |80488816 |340855248 |278702544
**GPU Texture Memory Usage**: |903128257 |972119902 |798552172
**GPU Virtual Memory Usage**: |885847903|1043067766|869636731
**Triangle Count**: |372545 |320235 |482157
**Triangle Rate**: |23284062 |18837352 |37089000
**API Drawcall Count**: |206 |97 |212
**Drawcall Count**: |2934 |97 |212
**Drawcall Rate**: |183375 |5705 |16307
**State Changes Texture Count**:|354 |139 |271
**Pipeline Count**: |64 |32 |25
**Item Opaques**: |251 |111 |248
**Item Translucents**: |69 |6 |39
**Item Lights**: |16 |22 |14
**Timing Opaques**: |0.866 |0.457 |0.892
**Timing Translucents**: |0.139 |0.019 |0.113
**Timing Lighting**: |0.116 |0.15 |0.193
**Render Frame**: |2.011 |1.544 |2.454

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**Check**
**Test 2**|Install a fresh copy of "Home' and do tutorial|**Success**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**Success**
**Test 4**|Launch firework, on dev-playa, can other hear?|**Success**
**Test 6**|Test group functions|**Success**
**Test 7**|Retest the kick function|TBT
**Test 8**|Enrure that you can distance grab|**Success**
**Test 9**|Bring up and edit an objects with hand controllers|**Success** Worked fine also added some user data successfully.
**Test 11**||Carried out in full and with relish.


### Additional notes:
	
	On-screen keyboard remains unavailable when using playaPerformanceTest.js

	While attempting to enter additional notes for the QA the numeric button did not work on the QML keyboard.

	If the intent of playaPerformanceTest.js is to display performance when all content is loaded I would recommend multiple runs or slowly rotating view prior to running to ensure that all content-in-view is loaded. Failure to do so can show spikes in the result that are not present when content is fully loaded.

Michelle noticed that one of the hud icons was absent on startup.

**Comment by howard-stearns** [comment]
Any repro for that missing "switch" button?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 836aad7d0b8b5c48c0b293fbb183dee9c68899e4 available at: https://gist.github.com/4b384b9e7b8a0aeefb792412421739f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-836aad7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-836aad7.dmg

**Comment by Nex-Pro** [comment]
@howard-stearns  I believe Michelle started interface with existing settings after installing the RC.
I'll get more detail for you.

**Comment by Nex-Pro** [comment]
@howard-stearns 

Repro seems to be:  Start interface with steam VR **not** running.

With steam VR running the icon is displayed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a774553ae1ab1668dd2eff23f13340879bb0631 available at: https://gist.github.com/4b384b9e7b8a0aeefb792412421739f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-9a77455.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-9a77455.dmg

**Comment by howard-stearns** [comment]
I cannot repro the missing button. Here's what I did, using this PR:
- With steamVR running, sandbox->GoHome. Puts you in HMD with full toolbar.
- Exit while still in HMD. Shut down steamVR (and also repeated with Steam also shut down). Sandbox->GotHome puts you in Desktop, with full toolbar. (It also starts up SteamVR, but it is too late to start up in HMD mode, which may or may not be intended. I don't know.)

In no case do I get any missing toolbar items. But I'm on a full-performance machine.

**Comment by Atlante45** [comment]
I'm closing this since it's retriggering builds for no reason and adding unnecessary strain on jenkins.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2684aed52329dcfff68c192ad38b139dc4e6a865 available at: https://gist.github.com/4b384b9e7b8a0aeefb792412421739f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-2684aed.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-2684aed.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e763082afc920e970256f01755d4eaf886208a76 available at: https://gist.github.com/4b384b9e7b8a0aeefb792412421739f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-e763082.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8996-e763082.dmg

**Pull request closed without merging**
