### PR TITLE
Fix dynamic entities not colliding with avatar when a grab action is removed

### PR DESCRIPTION
**Pull request by druiz17**
When an action is removed we check if we need to clear the bootstrapping bit from the dirty flags if it has no more grab actions. we actually remove the action after we perform this check resulting in the entity thinking it still has a grab action thus never clear the bootstrapping bit 

ticket - https://highfidelity.fogbugz.com/f/cases/11104/Grabbable-objects-stop-colliding-with-avatars-after-being-near-grabbed-far-grabbed-or-clicked-with-the-mouse

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- create a dynamic entity and make sure it collides with your avatar
- far grab an dynamic entity in desktop and HMD
- after you let go of the entity make sure the entity still collides with your avatar

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6411/app_12204_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6411/HighFidelity-Beta-PR12204-3e3b3a0a9ee482046a09df30e3e3c4d80686b042.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6411/HighFidelity-Beta-PR12204-3e3b3a0a9ee482046a09df30e3e3c4d80686b042.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
