### PR TITLE
add Clipboard.getContentsDimensions() JavaScript method

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
Run attached script, clipboardContentsDimensions.js.
Make sure you have edit.js and examples.js running.
Import an entity or two from the Examples window. For example a large entity such as the palm tree and a smaller entity such as the bean bag.
Compare the dimensions reported in the program log with the dimensions given when you edit the entity. They should be roughly comparable. (Dimension y always appears to be spot on; x and z are a bit more variable  - possibly octree related - but still comparable.)

[clipboardContentsDimensions.zip](https://github.com/highfidelity/hifi/files/283070/clipboardContentsDimensions.zip)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f3fa80b96eab8a8130fcb6be580932c38e74f00 available at: https://gist.github.com/1142f5d1cb0f8d7134339dfe20efbb8b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7973.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7973.dmg

**Comment by Triplelexx** [comment]
I see what you mean, the difference can be quite off for smaller values in x & z, tested it on a few items.
All worked for me.

**Comment by cozza13** [comment]
@ctrlaltdavid , can you update with master to get the protocol changes so we can test.

**Comment by ctrlaltdavid** [comment]
Updated to the latest master. Amended test notes: dimensions reported may not be the object's dimensions because the object may be being imported as rotated (meaning that its extents in world coordinates will be greater than its extents in object coordinates).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a8954d8516e76df72678662be474de2b72dab3d available at: https://gist.github.com/1142f5d1cb0f8d7134339dfe20efbb8b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7973.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7973.dmg

**Comment by Nex-Pro** [comment]
Dimensions of palm tree very accurate: to 4 decimals

Bean bag off due to rotation in all three axes as expected.

Buddah  as above.

**Pull request merged**
