### PR TITLE
revert commit that broke sendToScript

### PR DESCRIPTION
**Pull request by sethalves**
- revert commit that broke sendToScript

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4056/qml-sendToScript-doesn-t-work-in-tablet

**Comment by sethalves** [comment]
to test:
- make sure apps in the tablet work, esp PEOPLE

**Comment by hifi-gustavo** [comment]
Build console output for commit: 36940b4dfe1fabcbc4e00932b76271795653b3a7 available at: https://gist.github.com/09fba1f5bba964f173f45e21f7d59bb5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10177-36940b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10177-36940b4.dmg

**Comment by davidkelly** [comment]
Yea this seems to have fixed it 👍

**Pull request merged**
