### PR TITLE
Hand pucks and Calibration UI

### PR DESCRIPTION
**Pull request by druiz17**
Added support for the hand pucks and calibrating from an UI

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/821/HighFidelity-Beta-PR10729-da29157a3c0abec0eb17a13a0570b64e46f88687.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/821/HighFidelity-Beta-PR10729-da29157a3c0abec0eb17a13a0570b64e46f88687.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/879/HighFidelity-Beta-PR10729-13dff29bd55781dacfb295b964b90ef46be83cf7.dmg

**Comment by druiz17** [comment]
Test Plan
- Open the controller settings UI from settings menu options
- go through all the calibration combination and calibrate (make sure they work properly)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/933/HighFidelity-Beta-PR10729-17832b602244e22767a0f2075524dbc83bc5439d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/933/HighFidelity-Beta-PR10729-17832b602244e22767a0f2075524dbc83bc5439d.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/943/HighFidelity-Beta-PR10729-729065749f05a524fd07a6652c80fec541293557.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/943/HighFidelity-Beta-PR10729-729065749f05a524fd07a6652c80fec541293557.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/944/HighFidelity-Beta-PR10729-729065749f05a524fd07a6652c80fec541293557.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/944/HighFidelity-Beta-PR10729-729065749f05a524fd07a6652c80fec541293557.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/946/HighFidelity-Beta-PR10729-f369303bfed4abfe5e5bdef9e6f4c921f0d2cef9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/946/HighFidelity-Beta-PR10729-f369303bfed4abfe5e5bdef9e6f4c921f0d2cef9.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/966/HighFidelity-Beta-PR10729-c4699e00ca2ace25e9bc73f633948eb102aee654.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/966/HighFidelity-Beta-PR10729-c4699e00ca2ace25e9bc73f633948eb102aee654.dmg

**Comment by anshuman64** [comment]
QA Pass with 2 known issues: 
1. Shoulder pucks & head puck combination does not work well.
2. Shoulder pucks & chest puck combination does not work well.

Will address in future work. Otherwise, looks great. Good job @druiz17 !

**Pull request merged**
