### PR TITLE
8244 Rename captionColorOverride to captionColor

### PR DESCRIPTION
**Pull request by ElderOrb**
This PR shouldn't result in any functionality changes, but just refactoring of https://github.com/highfidelity/hifi/pull/11383

As for the test plan, please use the one from https://github.com/highfidelity/hifi/pull/11383 for regression check.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5005/HighFidelity-Beta-PR11830-c5d2f598d75728ad3e80acfa14672f3a28a8ea50.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5005/HighFidelity-Beta-PR11830-c5d2f598d75728ad3e80acfa14672f3a28a8ea50.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Go to the domain without edit access | Pass
Open tablet | Pass
Ensure text on 'Edit' button is not getting white when the button is hovered (in both desktop & VR) mode | Pass
As a smoke test, make sure Create mode works in domains where you have edit access and does not work in domains where you don't have edit access. | Pass

All good!

**Pull request merged**
