### PR TITLE
fix GL 4.5 when glTextureSubImage2DEXT unavailable

### PR DESCRIPTION
**Pull request by ChristophHaag**
For example mesa

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 966cbb768dca3fc3de1cc8f8b1abe4f0fc2d290a available at: https://gist.github.com/1864bd7f55add474008d8a750e08e611<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9264-966cbb7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9264-966cbb7.dmg

**Comment by samcake** [comment]
Brilliant!

**Comment by Nex-Pro** [comment]
@ChristophHaag Hi, Are there specific QA testing instructions for this ? What does 'For example mesa' mean with regard to this PR ?

**Comment by ChristophHaag** [comment]
On the mesa radeonsi driver glTextureSubImage2DEXT() is a null pointer, which means this function is not available and the hifi gl 4.5 backend segfaulted at that line.

I saw the comment above with a commented out ARB version of a similar call and tried it, and what do you know, hifi works fine (well, mostly) with it.

I don't think there is any real testing needed For drivers that do have glTextureSubImage2DEXT() nothing changes and only for drivers that don't have glTextureSubImage2DEXT() the previously commented out call is used now.

**Comment by Nex-Pro** [comment]
@ChristophHaag So are you saying this needs smoke testing on Radeon cards or no testing at all ?

**Comment by ChristophHaag** [comment]
I only know it affects the open source AMD driver on Linux but likely also intel and nouveau.

On my RX 480 this change makes it run and it renders basically the same as the 4.1 backend, where it previously segfaulted. I mean it's only restoring behavior from before https://github.com/highfidelity/hifi/commit/af915c79235f3bc83595f1473ddbcfd5f33511f2 for the drivers where glTextureSubImage2DEXT() is not available...

**Comment by OmegaHeron** [comment]
I'm going to smoke test this on my Linux box - it won't cover case of Radeon/Intel as I have Nvidia, but, will at least confirm it's good to go for Ubuntu + Nvidia GTX660M and Win 10 + Nvidia GTX970.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU
Desktop/DK2 HMD tested at all usual locations + general smoke tests.  Pass

Ubuntu 16.04.1 - i7-3720QM CPU - GTX660M GPU
Same as tests above for Windows (less HMD).  Pass

**Comment by AndrewMeadows** [comment]
Excellent.

**Pull request merged**
