### PR TITLE
Commerce Checkout and Purchases

### PR DESCRIPTION
**Pull request by zfox23**
Does what it says on the tin. Don't formally test.

I'm exhausted and going home. Play around with it! :) Search for **"Test Flaregun"**.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2827/HighFidelity-Beta-PR11252-4c1636656291e8aa58885e0b0e25f426a5f30ff2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2827/HighFidelity-Beta-PR11252-4c1636656291e8aa58885e0b0e25f426a5f30ff2.exe

**Comment by zfox23** [comment]
[confirmation design (and already purchased)](https://trello.com/c/uNhM5sdM/295-confirmation-design-and-already-purchased)

**Comment by zfox23** [comment]
[balance/purchases design](https://trello.com/c/91Xcnom4/294-balance-purchases-design)

**Comment by zfox23** [comment]
[inventory button still in marketplace. (should it be there?)](https://trello.com/c/cDI74P0R/317-inventory-button-still-in-marketplace-should-it-be-there)

**Comment by zfox23** [comment]
[purchased items and buy to set up wallet if it hasn't been already.](https://trello.com/c/rDztFGWE/319-purchased-items-and-buy-to-set-up-wallet-if-it-hasnt-been-already)

**Comment by zfox23** [comment]
[ui: get rid of quantity/Total Cost on confirmation page](https://trello.com/c/jnPAX8TD/346-ui-get-rid-of-quantity-total-cost-on-confirmation-page)

**Comment by zfox23** [comment]
[ui: BUY AGAIN => BUY ANOTHER](https://trello.com/c/C8OiJdhr/347-ui-buy-again-buy-another)

**Comment by zfox23** [comment]
[ui: Buy button only for entities (.json, .json.gz, not avatars or interface scripts. Those remain Get,Free,Wear or whatever it was.)](https://trello.com/c/OyT2Y9aM/344-ui-buy-button-only-for-entities-json-jsongz-not-avatars-or-interface-scripts-those-remain-getfreewear-or-whatever-it-was)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2843/HighFidelity-Beta-PR11252-ea0066872581dc60eb28dd808768837e7b62db7b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2843/HighFidelity-Beta-PR11252-ea0066872581dc60eb28dd808768837e7b62db7b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2845/HighFidelity-Beta-PR11252-ceb38e261ddada76a621e4b1eb783c6a943e6dba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2845/HighFidelity-Beta-PR11252-ceb38e261ddada76a621e4b1eb783c6a943e6dba.exe

**Comment by davidkelly** [comment]
moving the images means we have to update wallet slightly.  So --  line 422 of Wallet.cpp needs to have the new relative path popped in there.

**Comment by zfox23** [comment]
nice catch - thank you @davidkelly!

**Comment by davidkelly** [comment]
I dev approved -- just need to add that to wallet.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2846/HighFidelity-Beta-PR11252-1c1b841a8671b2505e5638402b8d8c1515955145.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2846/HighFidelity-Beta-PR11252-1c1b841a8671b2505e5638402b8d8c1515955145.exe

**Comment by zfox23** [comment]
[ui: Rez purchased items (after server output includes root_file_url)](https://trello.com/c/31yR7vbL/343-ui-rez-purchased-items-after-server-output-includes-rootfileurl)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2847/HighFidelity-Beta-PR11252-37b6099f36b296b96a5d77d7722dc7301eeda593.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2847/HighFidelity-Beta-PR11252-37b6099f36b296b96a5d77d7722dc7301eeda593.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2853/HighFidelity-Beta-PR11252-22d385750193986149707ee5bdd5b915f0ec5eda.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2860/HighFidelity-Beta-PR11252-22d385750193986149707ee5bdd5b915f0ec5eda.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2860/HighFidelity-Beta-PR11252-22d385750193986149707ee5bdd5b915f0ec5eda.exe

**Comment by davidkelly** [comment]
I see purchases fail, but when I look at the logs, it is clear that the issue is the percent encoding in the keys.  I fixed that in https://github.com/highfidelity/hifi/pull/11260.  Things look good otherwise, lets call this qa approved and merge it, get 11260 merged, and then start cleaning up any remaining errors.

**Pull request merged**
