### PR TITLE
Logging improvements

### PR DESCRIPTION
**Pull request by ZappoMan**
- removes some log spam
- also filters script logging more specifically to allow finer grain filtering
- cleans up all the naked qDebug() logs so that logging can be filtered by compenent
- script engine related errors, warnings, info have all been better classified 
- script engine related messages are now sent out as signals on the script engine, and as signals on the script services, so that other scripts could access them as debugging tools
- new `script/developer/debugging/debugWindow.js` that allows for a debugging window visible in the HMD

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- Smoke test
- verify you no longer see any of these messages in your log:
```
[12/19 15:05:22] [DEBUG] [default] Building circle3d overlay
[12/19 15:05:22] [DEBUG] [default] Building line3D overlay
[12/19 15:05:23] [DEBUG] [default] Destroying circle3d overlay
[12/19 15:05:23] [DEBUG] [default] Destryoing line3D overlay
[12/19 15:05:23] [DEBUG] [default] Building circle3d overlay
[12/19 15:05:23] [DEBUG] [default] Building line3D overlay
```
- verify that script prints now appear like this in the log...
```
[12/19 16:14:06] [DEBUG] [hifi.scriptengine.script] script:print()<< unloading teleport script
[12/19 16:14:06] [DEBUG] [hifi.scriptengine.script] script:print()<< unloading teleport script
[12/19 16:14:06] [DEBUG] [hifi.scriptengine.script] script:print()<< unloading teleport script
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: df954cab1038507604be9fdbea5b22a21c4d7ca1 available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-df954ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-df954ca.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e5e6a12db4a369c334fb06f90d243404c0c6369 available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-1e5e6a1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-1e5e6a1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c65471e88018d54c9285ae2502f4ba3d93e71cc2 available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-c65471e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-c65471e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a7fa63327c1f67aa73554b5352bb7bc5a4bf3fe available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-6a7fa63.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-6a7fa63.dmg

**Comment by claudioshg** [comment]
- Smoke test: Success

## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:


**Domain** |localhost | |
---|---|---|---
**Render Rate**: |0 | |
**Present Rate**: |0 | |
**Present New Rate**: |0 | |
**CPU Buffer Count**: |2122 | |
**GPU Buffer Count**: |735 | |
**CPU Memory Usage**: |23608144 | |
**GPU Memory Usage**: |15235184 | |
**CPU Texture Count**: |230 | |
**GPU Texture Count**: |188 | |
**GPU Transfer Count**: |0 | |
**CPU Texture Memory Usage**: |84995248 | |
**GPU Texture Memory Usage**: |848765057 | |
**GPU Virtual Memory Usage**: |835438910||
**Triangle Count**: |459978 | |
**Triangle Rate**: |45997800 | |
**API Drawcall Count**: |174 | |
**Drawcall Count**: |5956 | |
**Drawcall Rate**: |595600 | |
**State Changes Texture Count**:|337 | |
**Pipeline Count**: |65 | |
**Item Opaques**: |253 | |
**Item Translucents**: |103 | |
**Item Lights**: |11 | |
**Timing Opaques**: |0.82 | |
**Timing Translucents**: |0.132 | |
**Timing Lighting**: |0.013 | |
**Render Frame**: |1.667 | |

- verify you no longer see any of these messages in your log: Success

- verify that script prints now appear like this in the log...: Success
log

- from the Running Scripts dialog, run the developer/debugging/debugWindow.js script and verify that you get a Debug Window. This window should display a text window that logs all of the script printed output from scripts. In a format like this....: Fail
debugwindow

**Comment by ZappoMan** [comment]
@claudioshg  - your last comment with the screen shot of the debug window is not a fail... it's printing your script output as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b11c7cc9c762520c22d777564d04607f4a3620d available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-9b11c7c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-9b11c7c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f8bae603616b264c353d7f01500ba4421efb18ad available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-f8bae60.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-f8bae60.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0448023a0f2b05f8349b3ec6d88a83e59e1e0260 available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-0448023.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-0448023.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2320d317cd58a90a4b38275073620ffac76cd5d available at: https://gist.github.com/a9d1609bf76172bdc51d87965c197d29<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-c2320d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9238-c2320d3.dmg

**Pull request merged**
