### PR TITLE
Teleport.js: can now teleport small distances with small avatar scale

### PR DESCRIPTION
**Pull request by hyperlogic**
* You can now teleport small distances even when avatar is scaled to a small size.
* Reduced teleport cooldown from 500 ms to 300 ms.
* Made teleport.js eslint clean.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
  * Make your avatar very small.
  * Attempt to teleport small distances.  You should be able to, where previously you could not.

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/7652/IPD-Tertiary-Task-List-Teleport-Cancel-Distance-when-Small-is-too-large

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3653/HighFidelity-Beta-PR11465-a7cfb5d6351ea55ef50c1bbf6da9fc6c659130ba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3653/HighFidelity-Beta-PR11465-a7cfb5d6351ea55ef50c1bbf6da9fc6c659130ba.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Make your avatar very small. **Check**
Attempt to teleport small distances. You should be able to, where previously you could not. **Check**

All looks good to me, **Pass**

**Pull request merged**
