### PR TITLE
case BUGZ-1168: adding default script location setting for defaultscriptoverride run…

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/BUGZ-1168
Adding setting for default scripts path after shutting down lillypad run. Previously we've exited the save function before this was possible and on subsequent runs the standard interface would run without a ui. This prevents the possibly of interface run without ui.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20743/HighFidelity-Beta-PR16024-a37ef7d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20743/HighFidelity-Beta-Interface-PR16024-a37ef7d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20743/HighFidelity-Beta-PR16024-a37ef7d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20743/HighFidelity-Beta-Interface-PR16024-a37ef7d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20743/HighFidelity-Beta-PR16024-a37ef7d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20743/HighFidelity-Quest-Beta-PR16024-a37ef7d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20744/HighFidelity-Beta-PR16024-cf3fc5b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20744/HighFidelity-Beta-Interface-PR16024-cf3fc5b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20744/HighFidelity-Beta-PR16024-cf3fc5b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20744/HighFidelity-Quest-Beta-PR16024-cf3fc5b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20744/HighFidelity-Beta-PR16024-cf3fc5b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20744/HighFidelity-Beta-Interface-PR16024-cf3fc5b.exe

**Comment by jakram** [comment]
QA approved. Pre-merge testing passes.

**Pull request merged**
