### PR TITLE
Fix Edit -> Export Entities exporting gzipped json

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 * Run through testrail https://highfidelity.testrail.net/index.php?/cases/view/7049
 * While still in your sandbox after finishing the testrail case, restart your sandbox server. You should see your boxes are still there after the server comes back up.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7648/app_12538_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7650/app_12538_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7650/HighFidelity-Beta-PR12538-70bdedc4b398293d30168666517f34904573cef3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7650/HighFidelity-Beta-PR12538-70bdedc4b398293d30168666517f34904573cef3.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Comment by conklin94122** [comment]
@huffman needs dev review

**Pull request merged**
