### PR TITLE
Keep requesting render update until textures load (RC62)

### PR DESCRIPTION
**Pull request by SamGondelman**
same as https://github.com/highfidelity/hifi/pull/12136

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6191/app_12137_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6191/HighFidelity-Beta-PR12137-6072780d243b7e3d1e74dd77bda260a980642f78.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6194/app_12137_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6194/HighFidelity-Beta-PR12137-6072780d243b7e3d1e74dd77bda260a980642f78.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6194/HighFidelity-Beta-PR12137-6072780d243b7e3d1e74dd77bda260a980642f78.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
