### PR TITLE
Fix teleport when something equipped

### PR DESCRIPTION
**Pull request by sethalves**
- teleport ray-test now ignores equipped or grabbed entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- go to welcome's game area
- laser the boxing gloves so that they equip onto your avatar's hand
- attempt to teleport

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/3863/teleport-ray-can-intersect-with-equipped-entities

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e4e10759f3753445eab30971dbe52e1c10a264d available at: https://gist.github.com/4c243951ae4dbadbe1e01c58de7df9a5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10133-2e4e107.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10133-2e4e107.dmg

**Comment by 68chase** [comment]
testing

**Comment by 68chase** [comment]
Passed - I teleported no problem

image

image

**Pull request merged**
