### PR TITLE
Fix closing Clara download domain permissions warning with controllers

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Possible fix for not being able to close the error message box when you try to download a model from Clara.io but don't have permissions to write to the domain.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a4ff08496904b20808d57e697e1ccab6f79d78e2 available at: https://gist.github.com/679e3d6e15a0e0c3070ff7717e5ebeb6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9398-a4ff084.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9398-a4ff084.dmg

**Comment by nbq** [comment]
Testing this now

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d485e085e3114190e65db5306dc1bd6c052d351 available at: https://gist.github.com/679e3d6e15a0e0c3070ff7717e5ebeb6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9398-3d485e0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9398-3d485e0.dmg

**Comment by ctrlaltdavid** [comment]
Unfortunately, work-around didn't work around the underlying issue.

**Pull request closed without merging**
