### PR TITLE
make settings thread safe

### PR DESCRIPTION
**Pull request by sethalves**
- attempt to fix memory corruption associated with Settings

https://highfidelity.fogbugz.com/f/cases/17459/Interface-json-contains-corrupted-entries
https://highfidelity.fogbugz.com/f/cases/17458/Duplicate-fields-in-Interface-json-Settings
https://highfidelity.fogbugz.com/f/cases/18463/crash-in-Setting-Manager-saveAll

https://github.com/highfidelity/hifi/pull/14010
https://github.com/highfidelity/hifi/pull/14056

### CODE REVIEW

**Comment by sethalves** [comment]
to test, use plan from https://github.com/highfidelity/hifi/pull/14010

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13191/HighFidelity-Beta-PR14057-7d9e35d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13191/HighFidelity-Beta-PR14057-7d9e35d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13191/HighFidelity-Beta-Interface-PR14057-7d9e35d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing PR14057

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar settings and wearables persist.

**Pull request merged**
