### PR TITLE
fix bug preventing simulation ownership on localhost domain

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5898/HighFidelity-Beta-PR12074-a009ba35e7772f5c1b5cf17cfb35f84bf5efb4ca.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5898/HighFidelity-Beta-PR12074-a009ba35e7772f5c1b5cf17cfb35f84bf5efb4ca.exe

**Comment by AndrewMeadows** [comment]
I noticed an intermittent bug where my interface client would not successfully obtain simulation ownership of dynamic objects when in a domain running on the localhost (very short ping-times).  The problem turned out to be a missing edge case in the logic that analyzes simulation ownership changes coming from the entity-server.

**Test Plan:**

**(1)** Run a hifi domain on localhost

**(2)** Login to localhost domain and run the attached script to generate a grid of dynamic objects of different shapes.

**(3)** Enable the following menu items:

**Settings --> Developer Menus
Developer --> Physics --> Highlight Simulation Ownership**

**(4)** Navigate to a place that is clear of all ojbects.

**(5)** Copy the attached script to local file and run it.  It will create a green floor and a temporary grid of basic shape entities that are dynamic.

```
// create a grid of dynamic "shape" entities

var floorColor = { red:100, green: 200, blue: 80 };
var sampleColor = { red: 200, green: 255, blue: 255 };
var dynamicColor = { red: 200, green: 100, blue: 80 };

// connect cleanup()
var sampleEntityIds = [];
var dynamicEntityIds = [];
var floorId;
function cleanup() {
    for (var i in sampleEntityIds) {
        Entities.deleteEntity(sampleEntityIds[i]);
    }
    for (var i in dynamicEntityIds) {
        Entities.deleteEntity(dynamicEntityIds[i]);
    }
    Entities.deleteEntity(floorId);
}
Script.scriptEnding.connect(cleanup);

var LIFETIME = 120; // 2 min

// build a floor
if (true) {
    var thickness = 1.0;
    var width = 40.0;
    var position = MyAvatar.position;
    position.y = position.y - 1.0 * MyAvatar.scale - 0.5 * thickness;
    var properties = {
        type: "Shape",
        shape: "Cube",
        name: "floor",
        position: position,
        dimensions: { x: width, y: thickness, z: width },
        lifetime: LIFETIME,
        color: floorColor
    };
    floorId = Entities.addEntity(properties);
}

// These are the shape types:
// NOTE: commented out shapes are not yet supported by the C++
var shapes = [
    "Triangle",
    //"Quad",
    "Hexagon",
    "Octagon",
    "Circle",
    "Cube",
    "Sphere",
    "Tetrahedron",
    "Octahedron",
    "Dodecahedron",
    "Icosahedron",
    //"Torus",
    "Cone",
    "Cylinder"
];

// We will create a grid of entities, one instance of each shape,
var numShapes = shapes.length;
var numColumns = 3;
var numRows = Math.ceil(numShapes / numColumns);
var gridDistance = 3.0;
//var gridStep = 0.5;
var gridStep = 1.0;

var shapeDimensions = { x: 0.4, y: 0.4, z: 0.4 };
// build a grid of entities in front of avatar
var shapeCount = 0;
var gridCenter = Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, {x:0, y: 0, z: -5.0}));
for (var i = 0; i < numRows && shapeCount < numShapes; ++i) {
    //var yOffset = (i - 0.5 * (numRows - 1)) * gridStep;
    var zOffset = (i - 0.5 * (numRows - 1)) * gridStep;
    for (var j = 0; j < numColumns && shapeCount < numShapes; ++j) {
        // compute position
        var xOffset = (j - 0.5 * (numColumns - 1)) * gridStep;
        var offset = { x: xOffset, y: 0, z: zOffset};
        offset = Vec3.multiplyQbyV(MyAvatar.orientation, offset);
        var worldPosition = Vec3.sum(gridCenter, offset);

        // create the entitiy
        var properties = {
            type: "Shape",
            shape: shapes[shapeCount],
            name: shapes[shapeCount],
            position: worldPosition,
            dimensions: shapeDimensions,
            dynamic: true,
            gravity: {x: 0, y: -3, z: 0},
            lifetime: LIFETIME,
            color: sampleColor
        };
        var id = Entities.addEntity(properties);
        sampleEntityIds.push(id);
        shapeCount++;
    }
}
```

**(6)** Use far-grab to poke one entity at a time and notice the debug icons that show up.  As long as you're the only avatar poking the objects the fourth icon on the right should always show up as blue.

physics-debug-icons

Note the meaning of the icons from left to right:

(A) Red arrow pointing down = an update has been received (within the last 200 msec) for that object from the entity-server to the interface client.

(B) Cyan arrow pointing up = an update has been sent (within the last 200 msec) for that object from the local interface client

(C) Blue triangle in circle = the object is "active" in the Bullet physics simulation

(D) Blue silhouette of human head and shoulders = the object's simulation is owned by local interface client.  When the silhouette is red then the simulation is owned by someone else in the same domain.

The bug in `hifi/master` was: **sometimes** the local simulation would not take ownership of the dynamic object, and only three debug icons would be visible: the fourth icon would not be present because simulation ownership of the object was not being properly handled at the interface client.

In this PR the dynamic object should always show a blue ownership icon as soon as you set it moving.

**Comment by NissimHadar** [comment]
No comments.

**Comment by QAadahlin** [comment]
Currently testing.

**Comment by QAadahlin** [comment]
@conklin94122 Passed

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5938/app_12074_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5938/HighFidelity-Beta-PR12074-3f50d595c7350e9f4dc7171e2752854df38b0480.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5938/HighFidelity-Beta-PR12074-3f50d595c7350e9f4dc7171e2752854df38b0480.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5958/app_12074_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5958/HighFidelity-Beta-PR12074-fbe2dd8a41f9b93d2a011f4003d3c82c8c1164b1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5958/HighFidelity-Beta-PR12074-fbe2dd8a41f9b93d2a011f4003d3c82c8c1164b1.dmg

**Pull request merged**
