### PR TITLE
fix a bug that caused dynamic children to wink in and out and then vanish

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that caused dynamic children to wink in and out and then vanish

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/7117/Dynamic-child-entity-of-dynamic-entity-randomly-stops-displaying

**Comment by sethalves** [comment]
to test:
- make sure the repro no longer repros:

Repro:
- Using edit.js, create two cube entities.
- Make one entity the child of the other.
- Make both entities dynamic.
- Observe over a couple of minutes: the child entity occasionally stops displaying then resumes displaying.

Notes:
- When the child entity isn't displaying, moving your camera often makes it display again.
- Eventually, the child entity is almost always not displaying.
- When the child entity is not displaying it is also not listed in the edit tool's entities list.
- The child displays properly while you're grabbing the root entity.
- If you manage to unlink the child from the parent the child starts displaying properly again.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2931/HighFidelity-Beta-PR11280-d04eda80774509febea8cef59cef02ef73a7af37.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2931/HighFidelity-Beta-PR11280-d04eda80774509febea8cef59cef02ef73a7af37.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2935/HighFidelity-Beta-PR11280-23e378555c66d399fb0d739af707194db296aa66.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2935/HighFidelity-Beta-PR11280-23e378555c66d399fb0d739af707194db296aa66.exe

**Pull request closed without merging**
