### PR TITLE
Case 19709: Delete old nodes with identical socket

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.manuscript.com/f/cases/19709/Avatars-staying-as-white-orbs)

On reconnect, 2 node objects can briefly share a connection object which can lead to data loss.
Don't allow 2 nodes to have the same socket.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17553/HighFidelity-Beta-PR15005-d66b786.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17553/HighFidelity-Beta-PR15005-d66b786.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17553/HighFidelity-Beta-Interface-PR15005-d66b786.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17553/HighFidelity-Beta-PR15005-d66b786.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17553/HighFidelity-Beta-Interface-PR15005-d66b786.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17636/HighFidelity-Beta-PR15005-d66b786.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17636/HighFidelity-Quest-Beta-PR15005-d66b786.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17636/HighFidelity-Beta-PR15005-d66b786.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17636/HighFidelity-Beta-Interface-PR15005-d66b786.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17636/HighFidelity-Beta-PR15005-d66b786.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17636/HighFidelity-Beta-Interface-PR15005-d66b786.exe

**Pull request merged**
