### PR TITLE
make hand-controller ui work in third person

### PR DESCRIPTION
**Pull request by howard-stearns**
Provides some HMD UI  in Third Person.

- Vive/Oculus hand-controllers (HMD) and Hydra (HMD and Desktop).
- HUD and lasers based on hardware positions (camera and physical hand-controller position), not avatar.
- "Right click" menus.
- All HUD elements (buttons, Running Scripts, Goto, etc.)
- Far grab.
- Third person HMD shows the location of the hand controllers (because it is not at your hands). Provided by @hyperlogic!

Issues:
- Near grab acquisition is based on the above (physical user's hand position), but the grabbed object then warps to the avatar hand.
- The 3D overlay search lines appear to somehow have two parts, one of which goes through the avatar and the other which doesn't. The actual picking is stopped by the avatar. I don't know what that's about.
- Does not attempt to deal with mirror, entity or indpendent views, and these menu items remain disabled in HMD.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e2fded846f5e35d1cba697e8b0f3bbc54efab64a available at: https://gist.github.com/7fb40a40d7c126886f7ca3cc05995bfc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-e2fded8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-e2fded8.dmg

**Comment by RyanDowne** [comment]
This works pretty well as is. One thing I noticed is that it is hard to bring up the menu. They quickly appear and then disappear. 

One thing I think would make this better is to render the Vive or Touch controllers when in third person. This would be consistent with other places in the code where when you real hands get further away than some meters, you see the controllers.

**Comment by howard-stearns** [comment]
The mechanism for displaying controllers is a bit dodgey:
  - reliability - POSSIBLE timing dependency between state of various competing scripts. 
  - display mechanism is currently designed to show controllers at hands, even in third person. I'll have to look into tearing that up a bit.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47bef18bd4c09526f7a9841d690c572ff76beb4a available at: https://gist.github.com/7fb40a40d7c126886f7ca3cc05995bfc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-47bef18.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-47bef18.dmg

**Comment by ZappoMan** [comment]
Please make sure we test this PR with oculus/HMD+Xbox controller to make sure it still functions.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 270adfe692eea68efc0accba36bd902893420580 available at: https://gist.github.com/7fb40a40d7c126886f7ca3cc05995bfc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-270adfe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-270adfe.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  Crash on first try.  Second attempt no crash however unable to integrate xbox controlers to respond.

**Comment by Nex-Pro** [comment]
**QA PASS/FAIL undetermined**

Tried this extensively with Michelle our experiences were very different.

For me it was fine. For Michelle the hand controllers would mostly disappear after a Local TP via friend list.

In addition we discovered that items can be grabbed at the hand controller but move instantly to the avatar hand location. In order to pass an entity from one hand to the other one needs to do an overhead back-pass. See first video clip in video contained in the zip file.

Michelle commented that she felt very uncomfortable/disconnected and slightly nauseous when in third person. I had no issue with it.

Grabbed entities maintain world rotational orientation when grabbed/held by avatars using third person view. See second video clip.

**Video clips.**  https://dl.dropboxusercontent.com/u/5350673/FH/High%20Fidelity%20-%20PR9054.zip

**Image below shows missing controller geometry. We tried restarting, clearing cache to no avail. Controllers were fine until after local TP. via user list click.**

**Comment by howard-stearns** [comment]
Thanks, all. I also don't like that it near-grabs using the hand controller position and then shifts it to the avatar's hand. The consensus here is that we're tentatively calling that out of scope.

I think that's good data from Michelle about the third-person experience. It's definitely not for everyone. Still trying to decide if it's for anyone.

Not sure what's going on with the controller disappearing. I've had some odd behavior that way outside of this PR, but could not reproduce. I suspect it's separate. Similarly for crashes.

@ZappoMan we still don't have an xbox test. Are you configured to try it out?

**Comment by cozza13** [comment]
was unable to select the HHUD elements when I was in 3rd person

**Comment by hyperlogic** [comment]
The xbox laser should now work in third person camera mode

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f840d3a08bf874ad86f3fb3ebbdc9fb77ca1e29 available at: https://gist.github.com/7fb40a40d7c126886f7ca3cc05995bfc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-7f840d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9054-7f840d3.dmg

**Comment by cozza13** [comment]
retested with the xbox controller and it works

**Pull request merged**
