### PR TITLE
Do not merge-- haptic vest Stable

### PR DESCRIPTION
**Pull request by mikeperrotta**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by SamGondelman** [comment]
build this please

**Comment by SamGondelman** [comment]
add to whitelist

**Comment by marko8904** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7110/app_12380_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7110/HighFidelity-Beta-PR12380-5a475bfaf30f4eead3e3bc58ae680863d603b06c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7110/HighFidelity-Beta-PR12380-5a475bfaf30f4eead3e3bc58ae680863d603b06c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7206/app_12380_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7207/app_12380_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7207/HighFidelity-Beta-PR12380-aa435acbb326395b99952eb348e6ec1cad3a7c68.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7207/HighFidelity-Beta-PR12380-aa435acbb326395b99952eb348e6ec1cad3a7c68.exe

**Comment by birarda** [comment]
Closing this, we are removing the stable branch

**Pull request closed without merging**
