### PR TITLE
Promoting Build 4626 to Stable

### PR DESCRIPTION
**Pull request by ZappoMan**
- This release includes all the latest improvements
- Several bug fixes
- New versions of example content and domains
- Improvements to hand controllers and grabbing behavior
- Fixes to jitter in avatar hands when moving

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d60fcdbf42d56d3b3e8a2914d3fe30a1e57a89c6 available at: https://gist.github.com/eb6c694d5f9130a453fdc1d9076dc7c3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7572.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7572.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d60fcdbf42d56d3b3e8a2914d3fe30a1e57a89c6 available at: https://gist.github.com/eb6c694d5f9130a453fdc1d9076dc7c3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7572.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7572.dmg

**Comment by cozza13** [comment]
smoke test and approved.

**Pull request merged**
