### PR TITLE
DO NOT MERGE - Testing Android PR Build

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5671/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5671/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.exe

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5675/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5675/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.exe

**Comment by murillodigital** [comment]
build this please

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5678/app_$ghprbPullId_PR.apk

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5679/app_11998_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5679/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5679/HighFidelity-Beta-PR11998-747ee941c12c37da56878f84685a98fc07528e6f.dmg

**Pull request closed without merging**
