### PR TITLE
Move SimplifiedUI folder again, and make the associated defaultScripts.js actually work

### PR DESCRIPTION
**Pull request by zfox23**
Implements [BUGZ-340](https://highfidelity.atlassian.net/browse/BUGZ-340) correctly.

I tested it by running `interface.exe` with the correct `--scripts` directory and everything worked as I anticipated.

### CODE REVIEW

**Comment by MiladNazeri** [comment]
Lol, only < 5 characters of code change though. Easy review :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19644/HighFidelity-Beta-PR15628-f69e4cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19644/HighFidelity-Beta-Interface-PR15628-f69e4cd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19644/HighFidelity-Beta-PR15628-f69e4cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19644/HighFidelity-Quest-Beta-PR15628-f69e4cd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19644/HighFidelity-Beta-PR15628-f69e4cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19644/HighFidelity-Beta-Interface-PR15628-f69e4cd.exe

**Pull request merged**
