### PR TITLE
Support toolbar API

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: eaa313449e692e8695ed9670d26d1441a446f495 available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Comment by thoys** [comment]
Hi @jherico , what is the test plan for this?

**Comment by howard-stearns** [comment]
Hang on @thoys. Not quite there yet.

**Comment by jherico** [comment]
Here is a test script that simulates the current edit toolbar using the new API.  Only the 'edit' button actually does anything, which is to show or hide all the other buttons.

```
var isActive = false;

var toolBar = (function() {
    var that = {},
        toolBar,
        activeButton,
        newModelButton,
        newCubeButton,
        newSphereButton,
        newLightButton,
        newTextButton,
        newWebButton,
        newZoneButton,
        newParticleButton

	var toolIconUrl = Script.resolvePath("assets/images/tools/");

    function initialize() {
        print("Toolbars: " + Toolbars);
        toolBar = Toolbars.getToolbar("highfidelity.edit.toolbar");
        print("Toolbar: " + toolBar);
        activeButton = toolBar.addButton({
            objectName: "activeButton",
            imageURL: toolIconUrl + "edit-01.svg",
            visible: true,
            alpha: 0.9,
        });

        print("Button " + activeButton);
        print("Button signal " + activeButton.clicked);
        activeButton.clicked.connect(function(){
            print("Clicked on button " + isActive);
            that.setActive(!isActive);
        });

        newModelButton = toolBar.addButton({
            objectName: "newModelButton",
            imageURL: toolIconUrl + "model-01.svg",
            alpha: 0.9,
            visible: false
        });

        newCubeButton = toolBar.addButton({
            objectName: "newCubeButton",
            imageURL: toolIconUrl + "cube-01.svg",
            alpha: 0.9,
            visible: false
        });

        newSphereButton = toolBar.addButton({
            objectName: "newSphereButton",
            imageURL: toolIconUrl + "sphere-01.svg",
            alpha: 0.9,
            visible: false
        });

        newLightButton = toolBar.addButton({
            objectName: "newLightButton",
            imageURL: toolIconUrl + "light-01.svg",
            alpha: 0.9,
            visible: false
        });

        newTextButton = toolBar.addButton({
            objectName: "newTextButton",
            imageURL: toolIconUrl + "text-01.svg",
            alpha: 0.9,
            visible: false
        });

        newWebButton = toolBar.addButton({
            objectName: "newWebButton",
            imageURL: toolIconUrl + "web-01.svg",
            alpha: 0.9,
            visible: false
        });

        newZoneButton = toolBar.addButton({
            objectName: "newZoneButton",
            imageURL: toolIconUrl + "zone-01.svg",
            alpha: 0.9,
            visible: false
        });

        newParticleButton = toolBar.addButton({
            objectName: "newParticleButton",
            imageURL: toolIconUrl + "particle-01.svg",
            alpha: 0.9,
            visible: false
        });

        toolBar.writeProperties({ x: 10, y: 10 });
        that.setActive(false);
        newModelButton.clicked();
    }

    that.setActive = function(active) {
        if (active != isActive) {
            isActive = active;
            that.showTools(isActive);
        }
    };

    // Sets visibility of tool buttons, excluding the power button
    that.showTools = function(doShow) {
        newModelButton.writeProperty('visible', doShow);
        newCubeButton.writeProperty('visible', doShow);
        newSphereButton.writeProperty('visible', doShow);
        newLightButton.writeProperty('visible', doShow);
        newTextButton.writeProperty('visible', doShow);
        newWebButton.writeProperty('visible', doShow);
        newZoneButton.writeProperty('visible', doShow);
        newModelButton.writeProperty('visible', doShow);
        newParticleButton.writeProperty('visible', doShow);
    };

    initialize();
    return that;
}());
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f5c1642cfd0f71abb3ce77806830d9793f259ae available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b539fea21fd5068e14a426ccf08e34e0b422a850 available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a7c4b5bba14f598cc82596aee32abf7dea71908 available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3edd4478727395e5e35261da2ae5ba0401e2198a available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec615caa80d66ec3e7f2544a904951ef85856522 available at: https://gist.github.com/ef449d3b9d76fb8fb0aa84d969f5c291<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8093.dmg

**Pull request merged**
