### PR TITLE
update server-console dependency hook

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9491/app_13098_PR_79576e0f48f9dd7b080d333d9d4b5113853e89e7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9491/HighFidelity-Beta-PR13098-79576e0f48f9dd7b080d333d9d4b5113853e89e7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9491/HighFidelity-Beta-Interface-PR13098-79576e0f48f9dd7b080d333d9d4b5113853e89e7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9491/HighFidelity-Beta-PR13098-79576e0f48f9dd7b080d333d9d4b5113853e89e7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Basic Sandbox features are still functional.

**Pull request merged**
