### PR TITLE
Created playaSpawner

### PR DESCRIPTION
**Pull request by AlanZimmerman**
Created playaSpawner. Spawns a desert landscape and 200 stone blocks.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by AlanZimmerman** [comment]
Test URL: https://rawgit.com/AlanZimmerman/hifi/playa/examples/playa/playaSpawner.js
Run where you are.

**Comment by howard-stearns** [comment]
add to whitelist

**Comment by AlanZimmerman** [comment]
Also: There is a big section of this script that is commented out. It is the portion that spawns dust particles when anything collides with the ground. Because there's a bug right now that makes it possible to pick/grab particles and that interferes with the picking of objects, I've temporarily commented out the dust system till the bug is resolved.

**Comment by imgntn** [comment]
@AlanZimmerman is that particle grabbing thing still a problem? i thought i saw a PR that fixed that.  can you check your script with a recent build?  would be cool to merge it with the dust stuff.

**Comment by imgntn** [comment]
@AlanZimmerman you can just push to the branch with a new PR when it's sorted :+1: i'll merge, its a sweet environment, looking fwd to the dust

**Pull request merged**
