### PR TITLE
fix create tab load on OS X

### PR DESCRIPTION
**Pull request by birarda**
- fixed loading of create app tabs on OS X

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1783/HighFidelity-Beta-PR10999-3936ee93f0e08da594a3279fe7505c09994658f5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1783/HighFidelity-Beta-PR10999-3936ee93f0e08da594a3279fe7505c09994658f5.exe

**Comment by birarda** [comment]
#### Test Plan

Test this PR, on Mac and on windows.

In a domain where you have the permissions to do so, pull up the 'Create' menu. On both operating systems the tabs 'List', 'Properties', and 'Grid' should load as you expect and show the resulting HTML. If you click 'Particle' under the 'Create' tab you should see the particle explorer.

**Comment by cain-kilgore** [comment]
Testing now on Windows.

**Comment by cain-kilgore** [comment]
# Test Passed (Windows)
Test | Result
-------- | --------
Pull up the Create Menu | Pass
List, Properties and Grid should load as expected | Pass
Particle Explorer loads upon clicking Particle | Pass

### Image:
image

Let me know if this needs further testing.


###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by kevinmthomasse** [comment]
testing on mac

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested on ```Sandbox``` domain where I have the permissions to do so and successfully pulled up the ```Create``` menu. On MAC the tabs ```List```, ```Properties```, and ```Grid``` loaded as expected and showed the resulting HTML. Clicked ```Particle``` under the ```Create``` tab and saw the particle explorer.
screen shot 2017-07-24 at 12 41 33 pm

**Pull request merged**
