### PR TITLE
username stays around now when tabbing to connections

### PR DESCRIPTION
**Pull request by davidkelly**
fixes [this bug](https://highfidelity.fogbugz.com/f/cases/4036/), where you would see your username disappear (beneath your display name) when tabbing to connections tab.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 174b2978e37d08321e292d89db21b88610b8a87a available at: https://gist.github.com/b608875c807bcd19248d221ee74734d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10168-174b297.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10168-174b297.dmg

**Comment by howard-stearns** [comment]
I know this is crazy, but I still get the permanent spinning in connections tab, only in  HMD

**Comment by howard-stearns** [comment]
ah but of course, this doesn't have the "fix"(?) from 1054. Which alas, is still wrong.
So both PRs are suffering from the spin-connections-in-hmd problem.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd557284909725d659986544f5bbabcee054f3d6 available at: https://gist.github.com/b608875c807bcd19248d221ee74734d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10168-cd55728.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10168-cd55728.dmg

**Pull request merged**
