### PR TITLE
Fix entity list selection failing when selecting entities not in list

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13067/HighFidelity-Beta-PR14014-ae1ff96.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13067/HighFidelity-Beta-Interface-PR14014-ae1ff96.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13067/HighFidelity-Beta-PR14014-ae1ff96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13067/HighFidelity-Beta-Interface-PR14014-ae1ff96.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13076/HighFidelity-Beta-PR14014-ae1ff96.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13076/HighFidelity-Beta-PR14014-ae1ff96.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13076/HighFidelity-Beta-Interface-PR14014-ae1ff96.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13076/HighFidelity-Beta-PR14014-ae1ff96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13076/HighFidelity-Beta-Interface-PR14014-ae1ff96.exe

**Comment by huffman** [comment]
# Test Plan

https://highfidelity.testrail.net/index.php?/cases/view/17767

**Comment by QliCknox** [comment]
Pass @conklin94122 

The entity list no longer loses its highlighting functionality when lowering the search radius

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13088/HighFidelity-Beta-PR14014-ae1ff96.apk

**Pull request merged**
