### PR TITLE
camera steers avatar when walking

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This is a theoretical fix for the bug reported in this forum thread:

https://forums.highfidelity.com/t/hmd-steering-changed-in-4790/10918

I don't have an HMD at home to test with, but it works for 2D screen mode.  Someone with an HMD should test:

(1) Walk forward while wearing the HMD and steer your avatar left and right by turning your head.
(2)  Avatar should not walk into the sky (should stay on the ground) when walking forward and looking up at the sky.
(3) Avatar should not walk backwards into the sky (should stay on the ground) when waking backwards and looking at the ground.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49c835b6fc72707cedc9c8a66708daaeabe28a95 available at: https://gist.github.com/6d76b2b33aaf15c9c7f3ffef07a8a989<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8021.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8021.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e6844e246884a5181e016746b7df2c41771e71f8 available at: https://gist.github.com/6d76b2b33aaf15c9c7f3ffef07a8a989<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8021.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8021.dmg

**Comment by hyperlogic** [comment]
Nice use of swing twist decomp.  +1

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successfully tested with Oculus. Walked forward while wearing the HMD and steered my avatar left and right by turning my head as it followed properly in the HMD. Avatar did not walk into the sky and stayed on the ground when walking forward and looking up at the sky. Avatar did not walk backwards into the sky and stayed on ground when waking backwards and looking at the ground.

**Comment by howard-stearns** [comment]
It looks like this also fixes https://highfidelity.fogbugz.com/f/cases/685/vive-jump-is-flakey
nice!

**Pull request merged**
