### PR TITLE
tablet-ui: button icon images now work with http urls.

### PR DESCRIPTION
**Pull request by hyperlogic**
Test plan:

run the following script:

    var tablet = Tablet.getTablet("com.highfidelity.interface.tablet.system");
    var button = tablet.addButton({
        icon: "http://s3.amazonaws.com/hifi-public/tony/icons/star.png",
        text: "CLICK ME"
    });

It should add a button to the tablet with a star icon.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf855391af34d47a44e0ca5e46a7b9da534701c2 available at: https://gist.github.com/1030e2489d8f749806c599158e1793ed<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-cf85539.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-cf85539.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c147b9bec0672aa9253c406ab0a2f75005906adc available at: https://gist.github.com/1030e2489d8f749806c599158e1793ed<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-c147b9b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-c147b9b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 008a58f9d708e00ce4d8de9de1d9ff70805bb903 available at: https://gist.github.com/1030e2489d8f749806c599158e1793ed<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-008a58f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-008a58f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c04f54e7509b08c36eff7311f16a3f6b636c391 available at: https://gist.github.com/1030e2489d8f749806c599158e1793ed<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-3c04f54.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9576-3c04f54.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
## PASS !

Click me icon with star added.

**Pull request merged**
