### PR TITLE
Added wantsTrigger to userData for a couple toys to avoid breakage …

### PR DESCRIPTION
**Pull request by ericrius1**
…with new grab script changes

### CODE REVIEW

**Comment by imgntn** [comment]
@ericrius1 can you plz add a link for testing?  ty

**Comment by ericrius1** [comment]
https://rawgit.com/ericrius1/hifi/grabFixes/unpublishedScripts/masterReset.js

**Comment by ericrius1** [comment]
https://rawgit.com/ericrius1/hifi/grabFixes/unpublishedScripts/immediateClientReset.js

**Comment by imgntn** [comment]
lgtm

**Pull request merged**
