### PR TITLE
Transition between walk/emote should be faster

### PR DESCRIPTION
**Pull request by dooglifeSF**
https://highfidelity.atlassian.net/browse/DEV-644

Locomotion interrupts emotes, but we can return to emotes faster by skipping the settle anim when in an emote.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21478/HighFidelity-Beta-PR16237-7307bea.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21478/HighFidelity-Beta-Interface-PR16237-7307bea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21478/HighFidelity-Beta-PR16237-7307bea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21478/HighFidelity-Beta-Interface-PR16237-7307bea.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21478/HighFidelity-Beta-PR16237-7307bea.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21478/HighFidelity-Quest-Beta-PR16237-7307bea.apk)

**Comment by dooglifeSF** [comment]
TEST PLAN: 
- verify that you can emote, walk, and return more quickly to the emote, compared to before this change.  You no longer need to wait for the settle transition anim to play out before returning to emote.  This works well for clap, raisehand and point.   It works if you trigger happy/sad emotes during settle, but those are one-time triggers and not persistent emotes like clap/raisehand/point.

**Pull request merged**
