### PR TITLE
Fix thrust not being applied w/ Physics + Avatar

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 870f1112e4bd213b0c4a03acee70180e85bf1442 available at: https://gist.github.com/f28ae22020f4526651f1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4467.dmg

**Comment by jherico** [comment]
Looking at this, I'm distressed by the amount of duplicated code between updatePositionWithPhysics and updatePosition.  Currently it looks as if updatePosition could be updated to simply call updatePositionWithPhysics at the appropriate point in the code.  However, I'm not clear on the purpose of updatePositionWithPhysics, since it seems to be way *less* complicated than updatePosition, which is somewhat counterintuitive.

**Comment by sethalves** [comment]
I think they could be combined (updatePosition could call updatePositionWithPhysics).  The only real difference is that updatePositionWithPhysics relies on bullet to make the changes to position.

**Comment by huffman** [comment]
I agree.  I will update updatePosition to call updatePositionWithPhysics.

**Comment by sethalves** [comment]
consider a name-change for updatePositionWithPhysics, if you do this.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 870f1112e4bd213b0c4a03acee70180e85bf1442 available at: https://gist.github.com/f28ae22020f4526651f1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4467.dmg

**Comment by AndrewMeadows** [comment]
I'm going to merge this now.  I'll go in and cleanup the updatePosition*() methods.

**Pull request merged**
