### PR TITLE
BUGZ-352: Persist the audio volume settings across sessions

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.atlassian.net/browse/BUGZ-352

Implemented in the engine instead of UI scripts, to solve tricky synchronization issues and to work regardless of UI.

### Test Plan
Verify that when Interface is closed and restarted, all volume sliders are preserved.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20735/HighFidelity-Beta-PR16021-0b97f2b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20735/HighFidelity-Beta-Interface-PR16021-0b97f2b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20735/HighFidelity-Beta-PR16021-0b97f2b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20735/HighFidelity-Beta-Interface-PR16021-0b97f2b.dmg

**Comment by MiladNazeri** [comment]
I've tested on PC, but this probably needs to be tested on mac as well

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20735/HighFidelity-Beta-PR16021-0b97f2b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20735/HighFidelity-Quest-Beta-PR16021-0b97f2b.apk)

**Pull request merged**
