### PR TITLE
Fix OS X warning

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Test Plan:
Run a server with the PR and login to it with the interface from this PR.
Make sure that:
    - You can see entities
    - You can add/modify entities (relog to check they're still there)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71fb0e665ffbb92e18dc092934b62d3dba1298a5 available at: https://gist.github.com/c7a95df5a3eda56b6dcfd1c5f75c05f5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8035.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8035.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested with OS X.  Successfully ran a server with the PR and logged into the interface from this PR and successfully viewed entities and was able to create new ones such as a box entity which I was able to add/modify.

**Pull request merged**
