### PR TITLE
Enable parabolic teleport

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/17051/Parabolic-Pointer-Implementation
https://highfidelity.manuscript.com/f/cases/17270/Pointers-ParabolaPointerProperties-is-mis-defined-in-JSDoc
https://highfidelity.manuscript.com/f/cases/17220/PickType-Parabola-missing-from-JSDoc
https://highfidelity.manuscript.com/f/cases/17350

Plus Mukul's design changes.

Test plan:
- Use teleport.
- The beam should be parabolic.
- When the beam is orange, there will be no pad on the end.
- When you start to teleport, the beam should turn blue immediately, as opposed to having a 0.3 second cool-in time like on master.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11669/HighFidelity-Beta-PR13715-19cf2b0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11669/HighFidelity-Beta-PR13715-19cf2b0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11669/HighFidelity-Beta-Interface-PR13715-19cf2b0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11669/HighFidelity-Beta-PR13715-19cf2b0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11669/HighFidelity-Beta-Interface-PR13715-19cf2b0.exe

**Comment by ctrlaltdavid** [comment]
/scripts/system/+android/radar.js uses the teleport-cancel.fbx file which this PR deletes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11770/HighFidelity-Beta-PR13715-e11030b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11770/HighFidelity-Beta-PR13715-e11030b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11770/HighFidelity-Beta-Interface-PR13715-e11030b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11770/HighFidelity-Beta-PR13715-e11030b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11770/HighFidelity-Beta-Interface-PR13715-e11030b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11774/HighFidelity-Beta-PR13715-7ed823c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11776/HighFidelity-Beta-PR13715-a8c408a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11776/HighFidelity-Beta-Interface-PR13715-a8c408a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11776/HighFidelity-Beta-PR13715-a8c408a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11776/HighFidelity-Beta-Interface-PR13715-a8c408a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11810/HighFidelity-Beta-PR13715-9c1f294.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11811/HighFidelity-Beta-PR13715-a92a345.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11811/HighFidelity-Beta-Interface-PR13715-a92a345.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11811/HighFidelity-Beta-PR13715-a92a345.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11811/HighFidelity-Beta-Interface-PR13715-a92a345.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11840/HighFidelity-Beta-PR13715-e9d1423.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11840/HighFidelity-Beta-PR13715-e9d1423.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11840/HighFidelity-Beta-Interface-PR13715-e9d1423.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11840/HighFidelity-Beta-PR13715-e9d1423.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11840/HighFidelity-Beta-Interface-PR13715-e9d1423.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11870/HighFidelity-Beta-PR13715-6b7f5b6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11870/HighFidelity-Beta-PR13715-6b7f5b6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11870/HighFidelity-Beta-Interface-PR13715-6b7f5b6.dmg

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
New teleport looks good and does not have delay.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
New teleport looks good and does not have delay.

**Comment by ctrlaltdavid** [comment]
Need to add "drawInFront" property to JSDoc.

**Comment by SamGondelman** [comment]
@ctrlaltdavid That isn't added in this PR.  If we decided to add it, I'll do the jsdoc in the other PR.

**Pull request merged**
