### PR TITLE
Fixed Sinking Trump Avatar Bug: Stops unnecessary vertical re-centering with big-headed avatar 

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses the underlying bug associated with Philip's Trump avatar sinking into the ground.  There were two issues:
1) the unity avatar exporter didn't assign a neck to the humanoid mapping.  we need to flag an warning for this.  (this will be addressed separately with a warning in the unity exporter code)
2) when the big-headed Trump nods it raises the hips and causes an unintended recentering(addressed here)

### Test plan:
1)open interface. get this trump avatar. https://hifi-content.s3.amazonaws.com/doug/avatar/trump/trump.fst
2) use mirror.json to view yourself.
3) nod forward slowly until looking down.  then look back up.
4)result: your knees should not be bent.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16392/HighFidelity-Beta-PR14695-8cba727.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16392/HighFidelity-Beta-PR14695-8cba727.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16392/HighFidelity-Beta-Interface-PR14695-8cba727.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16392/HighFidelity-Beta-PR14695-8cba727.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16392/HighFidelity-Beta-Interface-PR14695-8cba727.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
MS ticket: https://highfidelity.manuscript.com/f/cases/20512/Trump-Avatar-sinks-into-ground-as-user-is-looking-and-moving-around

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16773/HighFidelity-Beta-PR14695-91fddf7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16773/HighFidelity-Beta-Interface-PR14695-91fddf7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16773/HighFidelity-Beta-PR14695-91fddf7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16773/HighFidelity-Beta-Interface-PR14695-91fddf7.exe

**Comment by qlistephens95** [comment]
PASS. Trump avatars knees do not bend and behaves as expected.

**Pull request merged**
