### PR TITLE
Switch to nvtt with no openmp dependency (remove vcomp140.dll dependency)

### PR DESCRIPTION
**Pull request by jherico**
Remove depdency on vcomp140.dll

manuscript here https://highfidelity.manuscript.com/f/cases/20818/Missing-VCOMP140-dll

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16718/HighFidelity-Beta-PR14767-4b80510.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16718/HighFidelity-Beta-PR14767-4b80510.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16718/HighFidelity-Beta-Interface-PR14767-4b80510.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16718/HighFidelity-Beta-PR14767-4b80510.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16718/HighFidelity-Beta-Interface-PR14767-4b80510.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS

Moved vcomp140.dll and verified that master (build 9886) threw an error that it was missing. After this, PR14767 ran successfully. General testing showed no new issues.

**Pull request merged**
