### PR TITLE
Simplified UI - two quick fixes.

### PR DESCRIPTION
**Pull request by zfox23**
Implements:
[BUGZ-305](https://highfidelity.atlassian.net/browse/BUGZ-305)
[BUGZ-306](https://highfidelity.atlassian.net/browse/BUGZ-306)

### CODE REVIEW

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19583/HighFidelity-Beta-PR15606-6f7557b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19583/HighFidelity-Beta-Interface-PR15606-6f7557b.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19583/HighFidelity-Beta-Interface-PR15606-6f7557b.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19583/HighFidelity-Beta-PR15606-6f7557b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19583/HighFidelity-Quest-Beta-PR15606-6f7557b.apk)

**Pull request merged**
