### PR TITLE
Fix for incorrectly sized avatar capsule collision

### PR DESCRIPTION
**Pull request by hyperlogic**
This should fix issues with the marketplace mannequin and gamebot avatars.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/6825/mannequin-avatar-from-marketplace-is-floating-up

**Comment by hyperlogic** [comment]
QA Test plan:
  * Go to the marketplace and switch to the mannequin.  The mannequin avatar should no longer float above the ground.
  * Go to the marketplace and run the GameBot avatar switcher script. Use the GameBot tablet app to switch to one of the GameBot avatar variants.  Then switch to the Matthew avatar.  The Matthew avatar's feet should not appear sunken into the ground.

**Comment by YuppyPlays** [comment]
Testing [Awaiting build to finish checks]

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2521/HighFidelity-Beta-PR11196-e9b8e5431d2bebc74995f1a17209fece32a9bac5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2521/HighFidelity-Beta-PR11196-e9b8e5431d2bebc74995f1a17209fece32a9bac5.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Start interface with the Matthew avatar. Then use the marketplace app to switch to the mannequin avatar. The mannequin avatar should no longer float above the ground. **Though I would call this a pass, the feet appear to be on the floor at the heel and raised at the toe' area (See pic)
image

Start interface with the Matthew avatar. Then, go to the marketplace and run the GameBot avatar switcher script. Use the GameBot tablet app to switch to one of the GameBot avatar variants. Then switch back to the Matthew avatar. The Matthew avatar's feet should not appear sunken into the ground. **Pass, Matthews feet remain the same throughout the test, though I do see the bottom of the "rubber" to the shoe is ever so slightly in the floor, but I would say you'd have to be looking for miscellaneous detail to notice it.**

Not sure what to mark this as whether pass/fail.

**Comment by anshuman64** [comment]
@YuppyPlays Took a look at it myself. What you're noticing is fine.

**Pull request merged**
