### PR TITLE
CR for Job #20618 - Move Reload Content item to Developer menu.

### PR DESCRIPTION
**Pull request by kevinmthomas-carpool**
Code Review for Job #20618 - Workitem available at https://www.worklist.net/20618

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
test this please

**Comment by cozza13** [comment]
ok to test

**Comment by cozza13** [comment]
@kevinmthomas-carpool you need to update with master.

**Comment by kevinmthomas-carpool** [comment]
Successfully updated master to correct the adjustments for AudioClient.h

**Comment by kevinmthomas-carpool** [comment]
Done

**Pull request merged**
