### PR TITLE
prevent spectator cam from updating secondary cam aspect ratio when it's in use by mirrors

### PR DESCRIPTION
**Pull request by dback2**
Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/5160

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5129/HighFidelity-Beta-PR11869-1aeadcbc648c9cefb760e7241f4e0bf1e87da320.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5130/HighFidelity-Beta-PR11869-1aeadcbc648c9cefb760e7241f4e0bf1e87da320.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5130/HighFidelity-Beta-PR11869-1aeadcbc648c9cefb760e7241f4e0bf1e87da320.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
### TestRail Run [1155](https://highfidelity.testrail.net/index.php?/runs/view/1155&group_by=cases:section_id&group_order=asc)
##### See notes on last step in run

**Comment by dback2** [comment]
@cain-kilgore Thanks. Your note in the last step - when you say approaching the mirrors with spectator camera in your hand, did you mean that spectator camera was on? Because yes that is expected behavior that the mirrors do not turn on in that case and I have added a note about that to the test. If spectator camera was only open but not on then that is a problem.

**Comment by cain-kilgore** [comment]
@dback2 Yup spectator camera was on. I saw the note about it but wanted to confirm. In this case, the PR is all good from a QA perspective. :smile:

**Pull request merged**
