### PR TITLE
Instance Logger earlier

### PR DESCRIPTION
**Pull request by Atlante45**
Instance the logger earlier so we have access to the entire log.
And keep it running until the application shuts down.

This PR removes the Logger's constraint to have an existing QApplication so that it can run for the entirety of the program's lifetime.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ebf60c18a5999b9d887ac5d3f5d89dac7a7827f available at: https://gist.github.com/eccd6cba78102a074219777373adb333<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10442-4ebf60c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10442-4ebf60c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/107/HighFidelity-Beta-PR10442-67bf9b3f2ef19846b0074eab72582e50047351b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/219/HighFidelity-Beta-PR10442-4a9ac85080243b88f9717aca4bea66584c47a3dd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/219/HighFidelity-Beta-PR10442-4a9ac85080243b88f9717aca4bea66584c47a3dd.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/286/HighFidelity-Beta-PR10442-4a9ac85080243b88f9717aca4bea66584c47a3dd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/286/HighFidelity-Beta-PR10442-4a9ac85080243b88f9717aca4bea66584c47a3dd.dmg

**Pull request closed without merging**
