### PR TITLE
Latest changes from master

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by birarda** [comment]
Added a new label so these are more easily identifiable on PR page.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 606cf55b1be67cd76b2119864cc35a01e49c1559 available at: https://gist.github.com/e8e451f7384682dcc02678ec91f25590<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7567.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7567.dmg

**Comment by ZappoMan** [comment]
this is the wrong approach... the other approach is actually better....

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4fb53246a904314a956d9dc8c8982661203db975 available at: https://gist.github.com/e8e451f7384682dcc02678ec91f25590<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7567.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7567.dmg

**Pull request closed without merging**
