### PR TITLE
Remove 'Ignore IK' checkbox

### PR DESCRIPTION
**Pull request by misslivirose**
Fixed per PM guidance in FB 7461 - removes the 'Ignore IK' checkbox on the entity properties page.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6986/app_12352_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6986/HighFidelity-Beta-PR12352-204e00f8b8145ef7561e65524fa29bcc380496ee.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6986/HighFidelity-Beta-PR12352-204e00f8b8145ef7561e65524fa29bcc380496ee.dmg

**Comment by sethalves** [comment]
If we are going to do this, there is some C++ code that should also be removed.  We should understand why we used to believe we needed this and no longer believe.  We should also consider the stretch-arm PR in this context.

**Comment by sethalves** [comment]
stretchy-arm pr is here: https://github.com/highfidelity/hifi/pull/12190

**Comment by sethalves** [comment]
in scripts/system/controllers/controllerModules/nearActionGrabEntity.js is code that uses `ignoreIK` -- this should be adjusted.

**Comment by sethalves** [comment]
scripts/system/controllers/controllerModules/equipEntity.js also attempts to use ignoreIK

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7176/app_12352_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7176/HighFidelity-Beta-PR12352-22f15f5961f255cec13fceb0781aa616a20790f4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7176/HighFidelity-Beta-PR12352-22f15f5961f255cec13fceb0781aa616a20790f4.dmg

**Pull request closed without merging**
