### PR TITLE
Make it easier to switch between STABLE and STAGING Metaverses

### PR DESCRIPTION
**Pull request by zfox23**
**NOTE** that properly QAing this PR will require you to fetch the branch associated with this code, minimally modify it, and build High Fidelity from source yourself! Please only QA this PR if you are comfortable doing this.

# What's New
1. Changing from the Stable backend (https://metaverse.highfidelity.com) to the Staging backend (https://staging.highfidelity.com) is now as easy as changing two strings in the code and recompiling! One of those strings changes settings for Interface and all ACs, while the other string changes settings for the Domain Server.

## Known Issues/Incomplete
- There doesn't exist a staging ICE server, so functionality like place names won't work on the Staging backend environment.

# Future Work
- N/A

# Test Plan
## STABLE Metaverse
1. Launch Sandbox and Interface
2. Log in to Interface using your HiFi account - verify that this works as normal
3. Verify that your Sandbox gets a temporary place name
4. Verify that you can navigate to your Sandbox
5. Open the GOTO app and verify that you can see some domains and snapshots in there
6. Click on some domain in the GOTO app and verify that you go there
7. Click on the "BACK" button in the GOTO app and verify that you return to your Sandbox
8. Open the PEOPLE app (PAL), then click on the Connections tab. Verify that you see your Connections there (if you don't have any, simply verify that you don't see the "loading" GIF forever)
9. Enable the Commerce feature. Set up your Wallet. Buy a "Test Confetti Gun" from the marketplace and rez it. Verify that all of this worked as you expected.
10. Right click the Confetti Gun, then click the (i) Context Overlay. Ensure that opens up the Certificate for the Confetti Gun.
11. Use the SNAPSHOT app to take a Snapshot, then share it to the SNAPS feed. Ensure that process works as you expect it to.

## STAGING Metaverse
1. Pull the `zfox23:stagingSetting` branch to your PC.
2. Open `<HiFi Repo>\libraries\networking\src\NetworkingConstants.h`, then modify the line that reads `const QUrl METAVERSE_SERVER_URL = METAVERSE_SERVER_URL_STABLE;` to say `const QUrl METAVERSE_SERVER_URL = METAVERSE_SERVER_URL_STAGING`
3. Open `<hifi repo>\domain-server\resources\web\settings\js\settings.js`, then modify the line that reads `METAVERSE_URL: 'https://metaverse.highfidelity.com',` to say `METAVERSE_URL: 'https://staging.highfidelity.com',`
4. In your file explorer, navigate to `C:\Users\<Username>\AppData\Roaming\High Fidelity - dev\domain-server\`. Rename `AccountInfo.bin` (if it exists) to `AccountInfo.bin.stable`. Rename `config.json` (if it exists) to `config.json.stable`.
    - This is necessary due to a bug that @birarda is aware of. This step shouldn't be necessary forever.
5. Compile the solution.
6. Launch your built version of Sandbox and Interface
7. Create a new HiFi account (you're creating an account on the Staging backend; your normal accounts don't work here) - verify that this works as normal
8. Verify that you can navigate to your Sandbox by navigating to `localhost`
9. Open the PEOPLE app (PAL), then click on the Connections tab. Verify that you don't see the "loading" GIF forever
10. Enable the Commerce feature. Set up your Wallet. Buy a "Test Confetti Gun" from the marketplace and rez it. Verify that all of this worked as you expected.
11. Right click the Confetti Gun, then click the (i) Context Overlay. Ensure that opens up the Certificate for the Confetti Gun.
12. Use the SNAPSHOT app to take a Snapshot, then share it to the SNAPS feed. Ensure that process works as you expect it to.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4402/HighFidelity-Beta-PR11670-7998984d8e7e337978d77134193549eda4da28cf.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4414/HighFidelity-Beta-PR11670-d7bdbfb37bae8b95652eea01411c43bfa459d2ef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4414/HighFidelity-Beta-PR11670-d7bdbfb37bae8b95652eea01411c43bfa459d2ef.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4426/HighFidelity-Beta-PR11670-14150c09acf8539e8ae4122405e0b68f4c0d7264.dmg

**Comment by cain-kilgore** [comment]
## Test Partially Passed
### Stable
Test | Result
--- | ---
Launch Sandbox and Interface | Pass
Log in to Interface using your HiFi account - verify that this works as normal | Pass
Verify that your Sandbox gets a temporary place name | Pass
Verify that you can navigate to your Sandbox | Pass
Open the GOTO app and verify that you can see some domains and snapshots in there | Pass
Click on some domain in the GOTO app and verify that you go there | Pass
Click on the "BACK" button in the GOTO app and verify that you return to your Sandbox | Pass
Open the PEOPLE app (PAL), then click on the Connections tab. Verify that you see your Connections there (if you don't have any, simply verify that you don't see the "loading" GIF forever) | Pass
Enable the Commerce feature. Set up your Wallet. Buy a "Test Confetti Gun" from the marketplace and rez it. Verify that all of this worked as you expected. | Pass
Right click the Confetti Gun, then click the (i) Context Overlay. Ensure that takes you to the Certificate. | Pass
Use the SNAPSHOT app to take a Snapshot, then share it to the SNAPS feed. Ensure that process works as you expect it to. | Pass

This still needs to be compiled and **will need another QA Tester**. Spent most of the day trying to get my compiler to work properly with the assignment client but it wasn't working right.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4438/HighFidelity-Beta-PR11670-3f0108528d17632921f42cd448e8ca3e1f773d3b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4438/HighFidelity-Beta-PR11670-3f0108528d17632921f42cd448e8ca3e1f773d3b.exe

**Comment by howard-stearns** [comment]
domain-server.exe segfaults when compiled against staging

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4478/HighFidelity-Beta-PR11670-002141724bc14ef9615c4d21195cd2b27f107eda.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4478/HighFidelity-Beta-PR11670-002141724bc14ef9615c4d21195cd2b27f107eda.exe

**Comment by zfox23** [comment]
@howard-stearns is QAing the rest

**Comment by howard-stearns** [comment]
I don't know how to test on staging.  We can't run the tests, and I'm told it's expected fail. So I guess that means everything in staging is an automatic pass, so I'm just going to market this qa pass

**Pull request merged**
