### PR TITLE
undo part of #12312

### PR DESCRIPTION
**Pull request by sethalves**
- fix HMD account-name/logout-button and goto search results

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- with flat-screen, open GOTO, see that destinations are listed
- log in (if not already logged it)
- put on HMD
- open tablet
- see that name and logout button are in upper-right corner of tablet
- open GOTO, see that destinations are listed

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7018/HighFidelity-Beta-PR12360-84f44539907b8846c803a14dfd02e51c2708428f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7018/HighFidelity-Beta-PR12360-84f44539907b8846c803a14dfd02e51c2708428f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7019/app_12360_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7019/HighFidelity-Beta-PR12360-fdbfeab3ea59a319db8a6029441f495afb23f9c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7019/HighFidelity-Beta-PR12360-fdbfeab3ea59a319db8a6029441f495afb23f9c4.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing for PR#12360. PASSED.

**Pull request merged**
