### PR TITLE
Tablet ui as overlay

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2e95772d6dde810489c4846551884cb56fd8e8b available at: https://gist.github.com/bbd87c5b03536cb54e57d7faf3087aff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-a2e9577.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-a2e9577.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa950071ae8c1e378cefdd18822fb465b24341ff available at: https://gist.github.com/bbd87c5b03536cb54e57d7faf3087aff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-fa95007.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-fa95007.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e5fa84a207967f51fd61a0f552a0c9194df951a2 available at: https://gist.github.com/bbd87c5b03536cb54e57d7faf3087aff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-e5fa84a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-e5fa84a.dmg

**Comment by Atlante45** [comment]
@sethalves This PR is huge, I think you need to update both `highfidelity:tablet-ui` and `sethalves:tablet-ui-overlay` so we can see the actual diff.

**Comment by sethalves** [comment]
yeah this isn't ready for review or anything

**Comment by hifi-gustavo** [comment]
Build console output for commit: d4e3e57ac118937fbdc0c67d73da8ac7a5b734a4 available at: https://gist.github.com/bbd87c5b03536cb54e57d7faf3087aff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-d4e3e57.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9181-d4e3e57.dmg

**Pull request closed without merging**
