### PR TITLE
Low-level performance improvements to audio-mixer

### PR DESCRIPTION
**Pull request by kencooke**
Additional SIMD optimizations (using AVX2) for HRTF processing in the audio-mixer.
Individual speedups of 1.5 to 1.8x, overall performance (Intel i7-6700K) improved by around 10%.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

Using Sandbox from this PR, just verify that audio spatialization still works as before.
There should be no observable change (other than performance, only measurable with profiler).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12611/HighFidelity-Beta-PR13927-f5b7232.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12611/HighFidelity-Beta-PR13927-f5b7232.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12611/HighFidelity-Beta-Interface-PR13927-f5b7232.dmg

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Ran Audio test: https://highfidelity.testrail.net/index.php?/tests/view/115954&group_by=cases:title&group_order=asc&group_id=-1

No noticeable difference in audio and spacial works as it should. PR passes.

**Pull request merged**
