### PR TITLE
add support for ambient occlusion texture and lightmap texture for fbx exported from Blender

### PR DESCRIPTION
**Pull request by samcake**
This PR provide a way to specify an Occlusion Texture and a Lightmap texture from Blender export path.

To specify an Occlusion Texture for a material, in Blender, assign the texture to the "AmbientFactor" field and make sure the material property value "Ambient" in the "Shading" sub panel is on 1.0
THis Material will get translated properly through FBX and Hifi will recognize the texture as an occlusion Map as expected.

To Specify a Lightmap Texture for a material, in BLender, assign the texture to the "AmbientFactor" field and in the material properties, set the "Ambient" in the "Shading sub panel to 0.0
This Material will get translated properly through FBX and Hifi will recognize the texture as a Lightmap.

From Blender export path, Lightmap and Occlusion Map are mutually exclusive for a given Material.

We are recommending to stay away from using Lightmap as much as possible as they will not scale well with our plan for evolving lighting technology in Hifi.
Occlusion map however are well suited to provide extra ambient occlusion information which is solely dependent on the geometry of the model, as such, this can be taken advantage for extra information during dynamic lighting.
We recommend the Occlusion Map to be generated for a search sphere of influence of about 1 meter radius as this is the expected radius of influence of the Occlusion map which has to be combined with other shadowing and occlusion information computed at runtime.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c06c1a6ab9915b255812d994c1c88886d454a4f available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5050456c3299f051d2b697feed718d4eeef6ddfa available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1fa096e78847f9aef8ef95bd730105f5188bb66 available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a12e56f8802b0e52d9683a683499aaefb6be2b43 available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d06c6e2a5967ef72a8333749623457d6820377f6 available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25eb5694333dd128ad4e0cc0a8c9a03fbb53df6c available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2489df8229bba1903c4445ba01f64a28adcdc5e7 available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 681da201fc7dfcec6f9649be1b11972ccab97657 available at: https://gist.github.com/ed129983ca2d67d9a27163914a484639<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7889.dmg

**Comment by Menithal** [comment]
Testing.

**Comment by Menithal** [comment]
Left is testing Emit, 
Center is testing Lightmap (Material Factor 0)
Right is testing AO (Material Factor 1)

Binding wise looks good,
Not sure though on implementation, i dont see much different with or without AO, but that just might be my scene lighting and the textures I am using being too noisy.

Here are the results from my performance test running on my localhost, but someone else may want to do it as well as I now am running a 1080..

**Domain** |localhost | |
---|---|---|---
**Render Rate**: |60 | |
**Present Rate**: |60 | |
**Present New Rate**: |60 | |
**CPU Buffer Count**: |5600 | |
**GPU Buffer Count**: |2283 | |
**CPU Memory Usage**: |57126912 | |
**GPU Memory Usage**: |36425728 | |
**CPU Texture Count**: |271 | |
**GPU Texture Count**: |803 | |
**GPU Transfer Count**: |0 | |
**CPU Texture Memory Usage**: |165231948 | |
**GPU Texture Memory Usage**: |933139273 | |
**GPU Virtual Memory Usage**: |1116721993||
**Triangle Count**: |474594 | |
**Triangle Rate**: |26366333 | |
**API Drawcall Count**: |180 | |
**Drawcall Count**: |181 | |
**Drawcall Rate**: |10055 | |
**State Changes Texture Count**:|173 | |
**Pipeline Count**: |25 | |
**Item Opaques**: |210 | |
**Item Translucents**: |8 | |
**Item Lights**: |25 | |
**Timing Opaques**: |2557 | |
**Timing Translucents**: |192 | |
**Timing Lighting**: |242 | |
**Render Frame**: |4059 | |

**Comment by cozza13** [comment]
tested with Alan using Blender models:

http://hifi-content.s3.amazonaws.com/alan/dev/PR-7889--Test-Object-AO.fbx
http://hifi-content.s3.amazonaws.com/alan/dev/PR-7889--Test-Object-Lightmap.fbx

QA pass

**Comment by ZappoMan** [comment]
did we test this on mac? on AMD cards?

**Comment by ZappoMan** [comment]
tested on mac... it works.

**Pull request merged**
