### PR TITLE
make sure the AC agent has an AudioScriptingInterface

### PR DESCRIPTION
**Pull request by birarda**
- fixed the missing AudioScriptingInterface in agents

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Run an AC script that uses Audio.playSound. On this PR it will play the sound. On master it will not.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b53cb5934bf6ded9999cfec9b2eef028fa7343bc available at: https://gist.github.com/2b1523618a6d0a3dcfe0653c45e4a4fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9980-b53cb59.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9980-b53cb59.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAIL
**Additional Test Results + Observations**:  Ran ```https://raw.githubusercontent.com/highfidelity/hifi/d83600a22ee1579b15acf742e2fa83a84ce9951c/unpublishedScripts/DomainContent/CellScience/backgroundMusicAC.js``` AC Script on ```localhost``` and nothing happened.  I ran it is a regular script and it did work successfully as a test to ensure the script was functioning however did not work as an AC.
capture

**Comment by birarda** [comment]
Hmm, it seems that there is more than just a missing AudioScriptingInterface causing audio injection from AC agents to fail.

**Comment by birarda** [comment]
@kevinmthomasse I tried that script with this PR and specifically needed to go to the positions shown in the script to hear audio. At that point I did hear the injected sounds.

`position: { x: 15850, y: 15850, z: 15850 }` is an example.

**Comment by kevinmthomasse** [comment]
@birarda let me retry at those coordinates.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Ran ```https://raw.githubusercontent.com/highfidelity/hifi/d83600a22ee1579b15acf742e2fa83a84ce9951c/unpublishedScripts/DomainContent/CellScience/backgroundMusicAC.js``` AC Script on ```localhost``` at location ```localhost/15850, 15850, 15850``` and I successfully heard the AC music script.

**Pull request merged**
