### PR TITLE
Fix QML achoring warnings on Layouts

### PR DESCRIPTION
**Pull request by vladest**
Test steps:

1.Run Interface
2. Check if there is no warnings about TabletHome anchoring

https://highfidelity.fogbugz.com/f/cases/20110/QML-prints-warnings-about-achoring

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15250/HighFidelity-Beta-PR14423-53b7cc1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15250/HighFidelity-Beta-Interface-PR14423-53b7cc1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15250/HighFidelity-Beta-PR14423-53b7cc1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15250/HighFidelity-Beta-Interface-PR14423-53b7cc1.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15251/HighFidelity-Beta-PR14423-932d1db.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15251/HighFidelity-Beta-PR14423-932d1db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15251/HighFidelity-Beta-Interface-PR14423-932d1db.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15251/HighFidelity-Beta-PR14423-932d1db.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15251/HighFidelity-Beta-Interface-PR14423-932d1db.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15253/HighFidelity-Beta-PR14423-db82994.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15253/HighFidelity-Beta-Interface-PR14423-db82994.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15253/HighFidelity-Beta-PR14423-db82994.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15253/HighFidelity-Beta-Interface-PR14423-db82994.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15450/HighFidelity-Beta-PR14423-db82994.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15450/HighFidelity-Beta-PR14423-db82994.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15450/HighFidelity-Beta-Interface-PR14423-db82994.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15450/HighFidelity-Beta-PR14423-db82994.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15450/HighFidelity-Beta-Interface-PR14423-db82994.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
