### PR TITLE
Fix Overlay-as-child of model entity with reg point

### PR DESCRIPTION
**Pull request by huffman**
This fixes as issue where when you set the parent of an overlay to be a
model entity with a non-(0.5, 0.5, 0.5) registration point, the overlay would
still be positioned relative to the center of the model. The issue is
that the default parent joint index was 0, which is the center of the
model.

Entities, avatars, and overlays all now have a default parent joint index of `-1`.

Notes about avatars:

Avatars previously defaulted to `0`, but now default to -`1`. This subtle change will mean that you will need to set the parent joint index to `0` if you want the avatar to be positioned relative to the center of the model.

What are the repercussions of this? As far as I can tell, none, unless a script is dynamically adjusting the registration point of an entity. I haven't been able to find a way to set the avatar's local position (the position relative to the parent), so being positioned relative to the center vs registration point of an entity is irrelevant.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0f5f8871cbd83acdaf4e25ee027cc0eee7d8a04 available at: https://gist.github.com/a044831e1e5d81f6b72f9f6eeea19a9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9486-f0f5f88.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9486-f0f5f88.dmg

**Comment by huffman** [comment]
To test:

 1. Create a model entity
 1. Create a sphere overlay and set its parent id to that of the model entity you created
 1. Adjust the registration point of the model entity. The sphere should follow the registration point. (In practice this means the sphere will not move but the model entity will)
 1. Attach your avatar to the model entity (`MyAvatar.setParentID(...)`)
 1. Adjust the registration point of the model entity. Your avatar should not be moved.
 1. Set the avatar parent joint index to `0`. (`MyAvatar.setParentJointIndex(0)`)
 1. Adjust the registration point of the model entity. Your avatar should move relative to the center of the model.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e4f47d57f6101c2107e0f37ee1204f84140f182 available at: https://gist.github.com/a044831e1e5d81f6b72f9f6eeea19a9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9486-9e4f47d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9486-9e4f47d.dmg

**Comment by Nex-Pro** [comment]
Will test this

**Comment by Nex-Pro** [comment]
### PASS

Create a model entity: **Made a cube**
Create a sphere overlay and set its parent id to that of the model entity you created: **created via console.**
Moving the model entity should move the sphere: **Success**
Adjust the registration point of the model entity. The sphere should follow the registration point. (In practice this means the sphere will not move but the model entity will): **Success**
Attach your avatar to the model entity (MyAvatar.setParentID(...)):**Done**
Moving the model entity should move your avatar: **Success**
Adjust the registration point of the model entity. Your avatar should not be moved.:**Success**
Set the avatar parent joint index to 0. (MyAvatar.setParentJointIndex(0)): **Done**
Moving the model entity should move your avatar: **Success**
Adjust the registration point of the model entity. Your avatar should move relative to the center of the model.: **Success** as per the overlay.

**Pull request merged**
