### PR TITLE
hide default port from addresses, fix localhost scheme (RC66.2)

### PR DESCRIPTION
**Pull request by druiz17**
https://github.com/highfidelity/hifi/pull/13014 - refer to this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9230/app_13015_PR_c8d7dc9b915c6217ba3931c69753a5c96136491c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9230/HighFidelity-Beta-PR13015-c8d7dc9b915c6217ba3931c69753a5c96136491c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9230/HighFidelity-Beta-Interface-PR13015-c8d7dc9b915c6217ba3931c69753a5c96136491c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9230/HighFidelity-Beta-PR13015-c8d7dc9b915c6217ba3931c69753a5c96136491c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9230/HighFidelity-Beta-Interface-PR13015-c8d7dc9b915c6217ba3931c69753a5c96136491c.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Home button works with the bookmark set. However the Avatar is facing 180 degrees in the wrong direction when going home. The camera is no longer pointed at the 'Welcome' Gif.

**Pull request merged**
