### PR TITLE
Don't fetch avatars' .fst files from within the AvatarData class

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
PR: https://highfidelity.manuscript.com/f/cases/20122/

The avatar mixer was observed to be attempting to download fst files even though it doesn't need them. Tony suggested removing the download entirely from the avatar classes, since the client doesn't rely on this mechanism; therefore the PR does this.
The ScriptableAvatar class had references to the avatar FBX file, but they don't seem to be necessary for Agent scripts.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15631/HighFidelity-Beta-PR14529-eb097af.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15631/HighFidelity-Beta-PR14529-eb097af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15631/HighFidelity-Beta-Interface-PR14529-eb097af.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15631/HighFidelity-Beta-PR14529-eb097af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15631/HighFidelity-Beta-Interface-PR14529-eb097af.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15650/HighFidelity-Beta-PR14529-f3236e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15650/HighFidelity-Beta-Interface-PR14529-f3236e0.dmg

**Comment by SimonWalton-HiFi** [comment]
I have asked for QA to check scripts against PR. I am not sure how to search all sample code and marketplace scripts for references to API methods. My initial check of scripting on the client indicated the joint APIs still worked (because they are overridden in Avatar), but maybe some bots use them.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15704/HighFidelity-Beta-PR14529-16144b6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15704/HighFidelity-Beta-Interface-PR14529-16144b6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15704/HighFidelity-Beta-PR14529-16144b6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15704/HighFidelity-Beta-Interface-PR14529-16144b6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15709/HighFidelity-Beta-PR14529-e03104c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15709/HighFidelity-Beta-PR14529-e03104c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15709/HighFidelity-Beta-Interface-PR14529-e03104c.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by ZappoMan** [comment]
@SimonWalton-HiFi - So it looks like you added it back to ScriptableAvatar, but the other classes that derive from AvatarData also exposed this API, and may no longer... so for example MyAvatar derives from AvatarData too. - @hyperlogic can you please comment on this?

**Comment by SimonWalton-HiFi** [comment]
@ZappoMan Derivation is AvatarData -> Avatar -> (MyAvatar, OtherAvatar)
Avatar overrides the joint name accessors. I'll do some more verification of this today.

**Comment by qlipdahlin** [comment]
PR Passes.

Tested with Desktop, Rift, and Vive. Tested with fingerpaint app with drawing, drawing on ourselves, and drawing on others. Switched avatars, wearables, avatar entities, and loaded bots from listed script.

**Pull request merged**
