### PR TITLE
tweak mouse look to be slower

### PR DESCRIPTION
**Pull request by ZappoMan**
fixes this complaint - https://highfidelity.fogbugz.com/f/cases/2082/Mouse-sensitivity-option

### CODE REVIEW

**Comment by OmegaHeron** [comment]
Will test

**Comment by ZappoMan** [comment]
Test plan:
- Verify Mouse look still works
- Verify Mouse look is "less sensitive"

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1715/HighFidelity-Beta-PR10977-21018a5df07b5a0ccad58456077dcf88d73f6454.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1715/HighFidelity-Beta-PR10977-21018a5df07b5a0ccad58456077dcf88d73f6454.exe

**Comment by OmegaHeron** [comment]
Tested Windows 10 - Desktop mode
QA Pass (for test criteria)

Mouse look still works
Pan speed is obviously slower than previous.

Feedback:  Massively too slow now for my preference.  I'd suggest something a little closer to midway between this pan speed and previous.

**Comment by ZappoMan** [comment]
@anshuman64 @tapalisa - we need to get a PM to make a decision on the "speed" -- this is a P1 bug! So we need to deal with it asap! ;)

**Comment by CainFoool** [comment]
I'll give this a go too for opinion.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Verify Mouse look still works | Pass
Verify Mouse look is "less sensitive" | Pass

@OmegaHeron is right, it's wayyyy too slow - to a point where it takes multiple drags to even get your character to look behind you. IMO I quite liked the speed the way it was - maybe just toned down a bit ever so slightly. Even a configuration slider would be nice to set the Sensitivity?

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by anshuman64** [comment]
I will find a good intermediate value and re-commit for additional feedback. In another PR, we can add the configuration slider.

**Comment by humbletim** [comment]
This change will likely "break" all Users currently lowering the mouselook speed by adjusting the values under "Settings > Avatar... > Avatar Settings > (Camera pitch speed + Camera yaw speed)".

Also both the hardware mouse DPI and OS-level mouse configuration seem to affect the mouselook speed... so it doesn't seem like an "absolute scaling factor" should be assumed to work in most cases here.

**Comment by anshuman64** [comment]
Good point, @humbletim. I think we should close this PR and open another one that sets to the default values to:

- Camera Pitch Speed: 45
- Camera Yaw Speed: 60

**Pull request closed without merging**
