### PR TITLE
Better imports for controls and styles

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/13955/Audio-Stats-are-blank

PR introduces possibility of importing controlsUit & stylesUit as modules. It doesn't introduce any behavior changes or new functionality.

Test plan: 

Ensure QML applications still load / functional.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10650/HighFidelity-Beta-PR13401-23a7b2c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10650/HighFidelity-Beta-PR13401-23a7b2c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10650/HighFidelity-Beta-Interface-PR13401-23a7b2c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10650/HighFidelity-Beta-PR13401-23a7b2c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10650/HighFidelity-Beta-Interface-PR13401-23a7b2c.exe

**Comment by ElderOrb** [comment]
potential fix for https://highfidelity.fogbugz.com/f/cases/15906/MAC-Controls-Gallery-application-displays-as-an-empty-window-when-ran-on-OSX

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10818/HighFidelity-Beta-PR13401-b5cb197.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10818/HighFidelity-Beta-PR13401-b5cb197.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10818/HighFidelity-Beta-Interface-PR13401-b5cb197.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10818/HighFidelity-Beta-PR13401-b5cb197.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10818/HighFidelity-Beta-Interface-PR13401-b5cb197.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10995/HighFidelity-Beta-PR13401-3c16ae3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10995/HighFidelity-Beta-PR13401-3c16ae3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10995/HighFidelity-Beta-Interface-PR13401-3c16ae3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10995/HighFidelity-Beta-PR13401-3c16ae3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10995/HighFidelity-Beta-Interface-PR13401-3c16ae3.exe

**Comment by wayne-chen** [comment]
This should fix MS[#13955](https://highfidelity.fogbugz.com/f/cases/13955/Audio-Stats-are-blank).

**TEST PLAN** (to ensure [#13955](https://highfidelity.fogbugz.com/f/cases/13955/Audio-Stats-are-blank) fix)

- Launch Interface
- Enable `Settings->Developer Menu`
- Open audio statistics via `Developer->Audio->Stats...`
- The popup window should display audio interface statistics

**Comment by ElderOrb** [comment]
Re-based on master to resolve conflicts

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11226/HighFidelity-Beta-PR13401-3ccc5aa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11226/HighFidelity-Beta-PR13401-3ccc5aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11226/HighFidelity-Beta-Interface-PR13401-3ccc5aa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11226/HighFidelity-Beta-PR13401-3ccc5aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11226/HighFidelity-Beta-Interface-PR13401-3ccc5aa.exe

**Comment by ElderOrb** [comment]
Rebased on master to resolve conflicts

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11348/HighFidelity-Beta-PR13401-6b49303.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11350/HighFidelity-Beta-PR13401-e4045f3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11350/HighFidelity-Beta-PR13401-e4045f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11350/HighFidelity-Beta-Interface-PR13401-e4045f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11350/HighFidelity-Beta-PR13401-e4045f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11350/HighFidelity-Beta-Interface-PR13401-e4045f3.exe

**Comment by wayne-chen** [comment]
Made changes to fix [#13955](https://highfidelity.manuscript.com/f/cases/13955).  This PR won't fix that case, but it will bring a change to the loading of `controls-uit` in that QML file.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11828/HighFidelity-Beta-PR13401-2d43c4c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11828/HighFidelity-Beta-PR13401-2d43c4c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11828/HighFidelity-Beta-Interface-PR13401-2d43c4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11828/HighFidelity-Beta-PR13401-2d43c4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11828/HighFidelity-Beta-Interface-PR13401-2d43c4c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12254/HighFidelity-Beta-PR13401-da905af.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12254/HighFidelity-Beta-PR13401-da905af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12254/HighFidelity-Beta-Interface-PR13401-da905af.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12254/HighFidelity-Beta-PR13401-da905af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12254/HighFidelity-Beta-Interface-PR13401-da905af.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12378/HighFidelity-Beta-PR13401-c378ca3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12378/HighFidelity-Beta-Interface-PR13401-c378ca3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12378/HighFidelity-Beta-PR13401-c378ca3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12378/HighFidelity-Beta-Interface-PR13401-c378ca3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12880/HighFidelity-Beta-PR13401-d4a7334.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12880/HighFidelity-Beta-PR13401-d4a7334.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12880/HighFidelity-Beta-Interface-PR13401-d4a7334.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12880/HighFidelity-Beta-PR13401-d4a7334.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12880/HighFidelity-Beta-Interface-PR13401-d4a7334.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13756/HighFidelity-Beta-PR13401-5cba435.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13756/HighFidelity-Beta-PR13401-5cba435.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13756/HighFidelity-Beta-Interface-PR13401-5cba435.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13949/HighFidelity-Beta-PR13401-5cba435.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13949/HighFidelity-Beta-PR13401-5cba435.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13949/HighFidelity-Beta-Interface-PR13401-5cba435.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13949/HighFidelity-Beta-PR13401-5cba435.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13949/HighFidelity-Beta-Interface-PR13401-5cba435.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Both tickets mentioned in this PR work in desktop mode, and easily-accessed QML apps (like the avatar app) work as expected in both views. However, audio stats shows a white screen on the tablet when in VR mode. Also, luci.js no longer displays anything in either view. Both of these work in both views on master (9446).

image
image
image


[hifi-log.txt](https://github.com/highfidelity/hifi/files/2484586/hifi-log.txt)

**Comment by ElderOrb** [comment]
what is luci.js ? is it possible to attach it here?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14108/HighFidelity-Beta-PR13401-64f67d5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14108/HighFidelity-Beta-PR13401-64f67d5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14108/HighFidelity-Beta-Interface-PR13401-64f67d5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14108/HighFidelity-Beta-PR13401-64f67d5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14108/HighFidelity-Beta-Interface-PR13401-64f67d5.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

All tested QML apps functioned as expected in both views

**Pull request merged**
