### PR TITLE
Handle input plugin register/remove when activated/deactivated by menus

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed87ae3d5a4461dacdef532188af3763293c205e available at: https://gist.github.com/1e4cd6a93707c255779f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d37a1d2497dba09d1a03bf54a1c5d8d5fc6e170 available at: https://gist.github.com/1e4cd6a93707c255779f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 851460b2bd973e42d8c1f46b3346000c36013ce5 available at: https://gist.github.com/1e4cd6a93707c255779f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 851460b2bd973e42d8c1f46b3346000c36013ce5 available at: https://gist.github.com/1e4cd6a93707c255779f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6222.dmg

**Pull request merged**
