### PR TITLE
Don't update avatar entities of the avatars ID is AVATAR_SELF_ID

### PR DESCRIPTION
**Pull request by druiz17**
When transitioning between domains we set the sessionUUID to be AVATAR_SELF_ID, instead of being the Null UUID. The avatar will update its avatar entities, but when the avatar receives the actual sessionUUID it will not update the avatar entities owningAvatarID. Thus resulting of you unable to edit your avatar entities.

Ticket - https://highfidelity.fogbugz.com/f/cases/12339/Avatar-entity-usually-cannot-be-edited-after-changing-domains

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- run the script below, with creates a sphere that is parent to you
- switch domains
- press shift button and the color of the sphere should change

[testControl.zip](https://github.com/highfidelity/hifi/files/1729764/testControl.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7246/app_12419_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7246/HighFidelity-Beta-PR12419-bbcf865db39364881bc0d4a35bbfb9aa77d056f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7246/HighFidelity-Beta-PR12419-bbcf865db39364881bc0d4a35bbfb9aa77d056f3.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122

**Pull request merged**
