### PR TITLE
MyAvatar: Improved body recentering for room scale

### PR DESCRIPTION
**Pull request by hyperlogic**
Split body following behavior into three types:
* Rotation - When your head facing is away from your avatar body hip facing, the body will rotate underneath your head.
* Horizontal - When your head is too far to the side or in front of your hips.  Your body will stop leaning and begin to walk underneath your head.
* Vertical - When your head raises in the world, or you hit the forward/strafe button your body will straighten underneath you.

This enables deeper crouching and also prevents the vertical recentering from bumping your view up or down when you walk around in room scale.  Unfortunately, though the deeper crouching does expose issues with the body IK, occasionally the knees will lock straight and the knee orientation is wrong as your but gets closer to the floor.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dfc517d146eb2da172b887ea3af11600228bb4e available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e80665107c29c4d294509b66e9f77cbf9e73684 available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a750845797e45cb5f0932e0f4053a0fdfa33807 available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc456cbdbebbabf7c1518cc8e79db0aed3d720e7 available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37ba0ecd9f4b6cdb94fa28279edfaf4d8f8147af available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0de19d13c4b0af5c3ab285f3d9f5f61140646da3 available at: https://gist.github.com/50cb20e2db583d792b98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7238.dmg

**Comment by PhilipRosedale** [comment]
QA tested, seems great!

**Pull request merged**
