### PR TITLE
RC71: check node data pointers in handleNodeIgnoreRequestPacket

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11912/HighFidelity-Beta-PR13772-d82cde0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11912/HighFidelity-Beta-PR13772-d82cde0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11912/HighFidelity-Beta-Interface-PR13772-d82cde0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11912/HighFidelity-Beta-PR13772-d82cde0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11912/HighFidelity-Beta-Interface-PR13772-d82cde0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
We are still seeing issue 12330 occur but tested in local sandbox and high load domain, AvatarMixer did not crash.

**Pull request merged**
