### PR TITLE
RC84: BUGZ-1451: Update links in controller reference

### PR DESCRIPTION
**Pull request by zfox23**
https://highfidelity.atlassian.net/browse/BUGZ-1451

### CODE REVIEW

**Comment by ZappoMan** [comment]
This build failed on android for what appears to be unrelated to the code changed in the PR.

Android:
```
12:40:35  > git config core.sparsecheckout # timeout=10
12:40:35  > git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:35 FATAL: Could not checkout c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:35 hudson.plugins.git.GitException: Command "git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c" returned status code 128:
12:40:35 stdout: 
12:40:35 stderr: fatal: reference is not a tree: c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:35 
12:40:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
12:40:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
12:40:35 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2315)
12:40:35 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Ubuntu instance for Jenkins (i-0b5040220ee55a44e)
```
MacOS:

```
12:40:51  > git config core.sparsecheckout # timeout=10
12:40:51  > git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:51 FATAL: Could not checkout c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:51 hudson.plugins.git.GitException: Command "git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c" returned status code 128:
12:40:51 stdout: 
12:40:51 stderr: fatal: reference is not a tree: c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:51 
12:40:51 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
12:40:51 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
12:40:51 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2315)
12:40:51 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to macos(5)
12:40:5
```

Unix:

```
12:40:34 Checking out Revision c76e1b102c37eaedd695778b2e5058fb4814834c (refs/remotes/origin/pr/16228/merge)
12:40:34  > git config core.sparsecheckout # timeout=10
12:40:34  > git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:34 FATAL: Could not checkout c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:34 hudson.plugins.git.GitException: Command "git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c" returned status code 128:
12:40:34 stdout: 
12:40:34 stderr: fatal: reference is not a tree: c76e1b102c37eaedd695778b2e5058fb4814834c
12:40:34 
12:40:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
12:40:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
12:40:34 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2315)
```

Windows:

```
12:50:53 Checking out Revision c76e1b102c37eaedd695778b2e5058fb4814834c (refs/remotes/origin/pr/16228/merge)
12:50:54  > git config core.sparsecheckout # timeout=10
12:50:54  > git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c
12:50:54 FATAL: Could not checkout c76e1b102c37eaedd695778b2e5058fb4814834c
12:50:54 hudson.plugins.git.GitException: Command "git checkout -f c76e1b102c37eaedd695778b2e5058fb4814834c" returned status code 128:
12:50:54 stdout: 
12:50:54 stderr: fatal: reference is not a tree: c76e1b102c37eaedd695778b2e5058fb4814834c
12:50:54 
12:50:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
12:50:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
12:50:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2315)
12:50:54 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Windows instance for Jenkins 4 Jun 2019 (i-0e43d0aca337155ca)
12:50:54 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
```

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21523/HighFidelity-Beta-PR16228-efc3384.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21523/HighFidelity-Quest-Beta-PR16228-efc3384.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21523/HighFidelity-Beta-PR16228-efc3384.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21523/HighFidelity-Beta-Interface-PR16228-efc3384.dmg

**Comment by shanzzam** [comment]
Closing as we didn't hotfix this in 84

**Pull request closed without merging**
