### PR TITLE
added desktopSharing var

### PR DESCRIPTION
**Pull request by MiladNazeri**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22597/HighFidelity-Beta-PR16504-59511d2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22597/HighFidelity-Beta-Interface-PR16504-59511d2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22597/HighFidelity-Beta-PR16504-59511d2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22597/HighFidelity-Quest-Beta-PR16504-59511d2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22597/HighFidelity-Beta-PR16504-59511d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22597/HighFidelity-Beta-Interface-PR16504-59511d2.exe

**Pull request merged**
