### PR TITLE
Fix audio mixer crash

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.manuscript.com/f/cases/19955/audio-mixer-crash-in-addStream)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15499/HighFidelity-Beta-PR14492-c29f634.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15499/HighFidelity-Beta-PR14492-c29f634.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15499/HighFidelity-Beta-Interface-PR14492-c29f634.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15499/HighFidelity-Beta-PR14492-c29f634.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15499/HighFidelity-Beta-Interface-PR14492-c29f634.exe

**Comment by antoninahifi** [comment]
@conklin94122 PASS

**Pull request merged**
