### PR TITLE
Call updateGeometry before Model::createRenderItemSet

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.atlassian.net/projects/DEV/issues/DEV-2804

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22659/HighFidelity-Beta-PR16526-79d470c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22659/HighFidelity-Beta-Interface-PR16526-79d470c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22659/HighFidelity-Beta-PR16526-79d470c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22659/HighFidelity-Quest-Beta-PR16526-79d470c.apk)

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22661/HighFidelity-Beta-PR16526-79d470c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22661/HighFidelity-Quest-Beta-PR16526-79d470c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22661/HighFidelity-Beta-PR16526-79d470c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22661/HighFidelity-Beta-Interface-PR16526-79d470c.dmg

**Pull request merged**
