### PR TITLE
Solve Jitteriness when scrolling the content in HMD mode -> Marketplace  using the scrollbar.

### PR DESCRIPTION
**Pull request by volansystech**
Fix for Bug WL 21298 : Marketplace scrolling in HMD is jittery when using the scrollbar

**# QA To Test**

HMD / Handcontrollers required

1. Put on HMD.
2. Open Tablet UI
3. Select Marketplace
4. Scroll the content. [Select any category]

**Expected Result** : You will not see any kind of jitteriness while scrolling the content. Scrolling is smooth now.

_Note: Dev tested on Windows 10 + Oculus Rift_

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2ac4381eb935e89eb907e523501f2330ae0a425 available at: https://gist.github.com/911d7cf26453af1752fc16d97c4702fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10496-b2ac438.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10496-b2ac438.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10496-b2ac438.exe

PASS:
- Followed testing plan. Scrolled through every category in Marketplace. Scrolling was smooth all the time.

NOTE: (When Tablet is enabled) While in VR, going to Menu > Settings > General, always causes a crash. No Splat notification ever came up.

**Comment by ctrlaltdavid** [comment]
Problem: Hover events do not work on the tablet, for example tablet app buttons don't highlight when mouse-over them. This for both desktop using mouse, and HMD using stylus.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2691855e2b40c8921d6fc2031576c9d7e2d76d21 available at: https://gist.github.com/911d7cf26453af1752fc16d97c4702fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10496-2691855.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10496-2691855.dmg

**Comment by volansystech** [comment]
@claudioshg , Thanks for testing.
We built latest hifi master and we are facing same issue. Looks like problem is in master itself. Scrollbar jitterness changes does not affect that.

@ctrlaltdavid 
We incorporated your findings and with latest fix we tested following things.

1) Mouse hover effect
2) Mouse click / tap
3) Scroll in Center of UI [tablet contents]
4) Scrollbar scrolling using stylus
5) Scroll using trigger in scrollbar and center of UI [tablet contents]

We also tested with PC mouse as well. Everything works fine.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/53/HighFidelity-Beta-PR10496-d9a186c33ee93a13abff00ba170f791100b24263.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/53/HighFidelity-Beta-PR10496-d9a186c33ee93a13abff00ba170f791100b24263.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/87/HighFidelity-Beta-PR10496-1cbf6851331ad9c0a356e201cbbe58e04ce7eb91.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**When using the laser in HMD to scroll up or down through the categories / items in the market, it worked perfectly.**

**When using the pen in-game on the scrollbar, it is still jittery,**

Not sure if that's a pass or fail?, depends on which one is in question (or both).

Let me know if there is any more info I can provide.

**Comment by volansystech** [comment]
Hi @YuppyPlays,
Thank you for testing this.

Can you please tell me when jittery starts? 
If you just move down or move up scrollbar using stylus.
Or 
If you just hold scrollbar using stylus after some scrolling.

**Comment by YuppyPlays** [comment]
@volansystech The latter, when holding the scroll bar with the stylus. holding it and dragging up or down, always seems to cause jittery movement of the scrollbars location itself (going up and down very quickly scrolling the page in the process)

Hope this helps. :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/170/HighFidelity-Beta-PR10496-aab80629eaf421f51d02f7a9deb76c8235666315.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/170/HighFidelity-Beta-PR10496-aab80629eaf421f51d02f7a9deb76c8235666315.dmg

**Comment by YuppyPlays** [comment]
Does this require a second round of testing?

**Comment by volansystech** [comment]
@YuppyPlays, Yes, please :)
We just incorporated your findings. We resolved jitteriness while scrolling in marketplace using a pen (stylus).

Expected Result: You will not see any kind of jitteriness while scrolling the content using pen (stylus). Scrolling is smooth now.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/171/HighFidelity-Beta-PR10496-cab6f3f7c37aa7e07965564a4341187ef8345971.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/171/HighFidelity-Beta-PR10496-cab6f3f7c37aa7e07965564a4341187ef8345971.dmg

**Comment by YuppyPlays** [comment]
Excellent! Testing now :)

**Comment by YuppyPlays** [comment]
Testing Complete:

Absolutely brilliant!, first time in the game for me the scrollbar has worked flawlessly, makes it much easier to search now.



**Pass!**

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/196/HighFidelity-Beta-PR10496-98d5d2319840c5bdff642a4d72e60a5c8a8e21a8.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/197/HighFidelity-Beta-PR10496-8d9cfbdf31a97aab13c46966be0657ae85be1aa3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/197/HighFidelity-Beta-PR10496-8d9cfbdf31a97aab13c46966be0657ae85be1aa3.dmg

**Comment by volansystech** [comment]
Hi @sethalves , we have removed unwanted white spaces. Thank you !

**Pull request merged**
