### PR TITLE
Allow asynchronous editing of non-QML overlays

### PR DESCRIPTION
**Pull request by jherico**
Only QML overlays really need to be restricted to the main thread (and technically only for a subset of their properties).  This PR allows edits to non-QML overlays on background threads, hopefully fixing https://highfidelity.fogbugz.com/f/cases/edit/7144/Can-t-Grab-Tablet

## Testing

Attempt to grab tablet in HMD mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2677/HighFidelity-Beta-PR11233-0a5bef22fce6a5b24bf4f3b0504652f52c827bae.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2677/HighFidelity-Beta-PR11233-0a5bef22fce6a5b24bf4f3b0504652f52c827bae.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Attempt to grab tablet in HMD mode **Pass**

Grabbing the tablet essentially acted as expected as far as using the tablet goes, with trigger or grips it grabs when in proximity and has a slight haptic feedback of vibration to let the player know they've grabbed / touched it.

Please let me know if there is anything more I can do/provide to assist.

**Pull request merged**
