### PR TITLE
Case 22407: Quat JSDoc update

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namepaces:
- Quat

Globals:
- Quat

Other:
- Minor update to Camera API's description.

Primary Manuscript case: https://highfidelity.manuscript.com/f/cases/22407/JSDoc-Quat

Other Manuscript cases addressed: None

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19087/HighFidelity-Beta-PR15476-7db1e33.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19087/HighFidelity-Quest-Beta-PR15476-7db1e33.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19087/HighFidelity-Beta-PR15476-7db1e33.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19087/HighFidelity-Beta-Interface-PR15476-7db1e33.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19097/HighFidelity-Beta-PR15476-7db1e33.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19097/HighFidelity-Beta-Interface-PR15476-7db1e33.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19097/HighFidelity-Beta-PR15476-7db1e33.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19097/HighFidelity-Quest-Beta-PR15476-7db1e33.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19097/HighFidelity-Beta-PR15476-7db1e33.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19097/HighFidelity-Beta-Interface-PR15476-7db1e33.exe

**Pull request merged**
