### PR TITLE
Guard against unloaded env cube maps

### PR DESCRIPTION
**Pull request by zzmp**
Fixes the crashing caused by setting an invalid url for an ambient or skybox texture.
Also sets the texture as loaded in the EntityTreeRenderer so that invalid textures do not cause infinite retries.

### CODE REVIEW

**Comment by zzmp** [comment]
https://app.asana.com/0/74051501495175/95957371936715

**Comment by hifi-gustavo** [comment]
Build console output for commit: e84cd066edb9d0e0c2a22ab93a10ba2857838913 available at: https://gist.github.com/e5356139f6de279efd75<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d3663d0c0a01b01665a7f46e0765de618f5f664 available at: https://gist.github.com/e5356139f6de279efd75<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7629e4761836f59c41b182895a4f8b804f85d08 available at: https://gist.github.com/e5356139f6de279efd75<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7239.dmg

**Comment by zzmp** [comment]
This was fixed by the PBS merge. I will do upkeep/cleaning in a separate PR.

**Pull request closed without merging**
