### PR TITLE
Fix and improve the WAV file loader

### PR DESCRIPTION
**Pull request by kencooke**
More robust WAV parser. Skips extraneous chunks, handles WAVE_FORMAT_EXTENSIBLE, supports arbitrary sample rates.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

1) Run Interface and verify that existing WAV assets load and play as before.
2) Modify a script, or use PlaySound via the JS console, to load a WAV file with sample rate other than 48khz, and verify it plays

**Comment by OmegaHeron** [comment]
@kencooke -- any chance you might have some url(s) for test wav files we could use?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f10975a59371aef84ccc60bd99f935aac48b00d available at: https://gist.github.com/dcb51beaf5103b08a7e190cbfa6554d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9188-0f10975.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9188-0f10975.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass - I think - unless the one wav file that refused to play should have.  See last line of comments for source.

Sounds at playa work as expected along with other locations known to have sound assets.

Using test link provided - yes, rather loud 1k sine.  My ear drums thank you for cleaning.  Able to manipulate volume as expected.  I still have to trigger play sound *twice* the first time I play a sound before it will play.  I suspect that's a load/cache/time issue.

Tried a few samples from this page - all worked - static/white noise tests. http://riotorto.users.sourceforge.net/sound/sample/

This file fails.  http://riotorto.users.sourceforge.net/sound/sample/boo.wav

**Comment by kencooke** [comment]
@OmegaHeron, that last one fails because it's an 8-bit WAV file, which we don't support. So that is the expected behavior.

**Comment by OmegaHeron** [comment]
Then QA Pass - everything else I threw at it worked.  I had to dig deep to find that one.

**Pull request merged**
