### PR TITLE
Fix the Create selection box not always matching outline

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11439/HighFidelity-Beta-PR13656-2305099.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11439/HighFidelity-Beta-PR13656-2305099.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11439/HighFidelity-Beta-Interface-PR13656-2305099.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11439/HighFidelity-Beta-PR13656-2305099.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11439/HighFidelity-Beta-Interface-PR13656-2305099.exe

**Comment by huffman** [comment]
Original ticket: https://highfidelity.fogbugz.com/f/cases/14861/TranslateXZ-s-bounding-box-isn-t-aligned-with-displayed-bounding-box

# Test Plan

 1. Enable Create
 1. Create 1 box
 1. Select the box
 1. Press f to focus on it
 1. Adjust the camera so you are looking straight down on it
 1. Rotate the box 45 degrees around the y axis
 1. Ensure that you can mouse press on the box and drag it around. Ensure that you can do this for each corner of the box.
 1. Press `t` to switch to World Space mode
 1. Ensure that you can drag the box around in the same way as in step 7, but for each corner of the wireframe bounding box
 1. Create a new box and select both of the boxes you have created
 1. Ensure that you can drag the box around in the same way as in step 7, but for each corner of the wireframe bounding box

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Stopped Testing, awaiting further clarification from Dev

**Comment by QliCknox** [comment]
Currently Testing

**Comment by qligmaloney** [comment]
Build this please

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

The selection box matches up to the bounding box. User is able to move the entities around by grabbing the edges of the bounding box.

**Pull request merged**
