### PR TITLE
RC69: Fix MS16074, MS16076, MS16012: Fix links to Go To BankOfHighFidelity

### PR DESCRIPTION
**Pull request by zfox23**
RC69: Fixes [MS16074](https://highfidelity.fogbugz.com/f/cases/16074/Wallet-Home-page-link-button-to-Bank-of-High-Fidelity-do-not-work-in-production-or-staging-environments) and [MS16076](https://highfidelity.fogbugz.com/f/cases/16076/Wallet-Help-page-link-for-Bank-of-High-Fidelity-doesn-t-work-in-staging), and [MS16012](https://highfidelity.manuscript.com/f/cases/16012/Missing-message-on-Wallet-Home-about-Hifi-Bank).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Connect to the Staging metaverse environment. Log into an account whose wallet has no Recent Activity, and authenticate that wallet..
2. Verify that clicking the following links takes you to `hifi://hifiqa-master-metaverse-staging`:
    - In Wallet Home, the link in Recent Activity
    - In Wallet Home, the button in Recent Activity
    - In Wallet Help, the link in "where do I get HFC?"
3. Connect to the Stable metaverse environment. Log into an account whose wallet has no Recent Activity, and authenticate that wallet..
4. Verify that clicking the following links takes you to `hifi://BankOfHighFidelity`:
    - In Wallet Home, the link in Recent Activity
    - In Wallet Home, the button in Recent Activity
    - In Wallet Help, the link in "where do I get HFC?"

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10840/HighFidelity-Beta-PR13445-1189a78.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10840/HighFidelity-Beta-PR13445-1189a78.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10840/HighFidelity-Beta-Interface-PR13445-1189a78.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10840/HighFidelity-Beta-PR13445-1189a78.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10840/HighFidelity-Beta-Interface-PR13445-1189a78.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Connected to both Stable/Production metaverse and the Staging metaverse and tested all 3 buttons in each metaverse, each button connected to the correct corresponding domain, though there was a protocol version mismatch, which is expected.

**Pull request merged**
