### PR TITLE
Avoid setting the pipeline within GeometryCache draw calls

### PR DESCRIPTION
**Pull request by zzmp**
Instead, have consumers of GeometryCache draw calls set their own pipelines, so that the pipeline codepath is easier to follow/change.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fecde0cc7b18a6e092b581db7324549c4c7f68e6 available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c724bcf1455926e4365a2eaf6f6c6b6792afdaf available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by samcake** [comment]
THe rendering of the normal is wrong leading to bad lighting
probably the normal attribute is not getting to the vertex shader correctly  compared that what is done with the model meshes

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c04230925db4b585bd1a2d37e29421254f9c87b available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59465a216b9f6f360b804215a48d0b6df89e9038 available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59465a216b9f6f360b804215a48d0b6df89e9038 available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by zzmp** [comment]
So what was happening with the normal was that setupNamedCalls was deferring the rendering, and other pipelines were getting set in the meantime. This new commit changes it to include the pipeline in a lambda called just before the instanced/named draw call.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 05755b7946179354dccd1021502cea5f21c9103f available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fadfeba86b6d9bfe7bfc12e648bc2e0ca859a75c available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5801830f26b3048ed883feb97d1d51e0c5bcc34 available at: https://gist.github.com/7fac2ea654956b30f2bb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6998.dmg

**Comment by zzmp** [comment]
I had to change the way that this worked to use a ShapePipeline instead, and I've since finished the feature that this was leading to, so I am closing in favor of that.

**Pull request closed without merging**
