### PR TITLE
Fix for reset sensors while in desktop mode.

### PR DESCRIPTION
**Pull request by hyperlogic**
Previously hitting ' a.k.a. reset sensors, would teleport you to the last
position you were in before you switched into desktop mode, or the spawn location.

This fixes that behavior but not re-centering the avatar while in desktop mode.

Similarly, away.js would also teleport the user when in desktop mode
Because, away.js calls MyAvatar.centerBody.  However, centerBody is only meaningful in HMD mode.
To guard against this, MyAvatar::centerBody is now a no-op if the application is not in HMD mode.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/2428/Resetting-settings-in-desktop-resets-position-of-avatar-to-initial-login-location

**Comment by hyperlogic** [comment]
QA Test:
  * while in desktop mode press the "apostrophe" button.  This will trigger reset sensors.
  * The avatar position should *NOT* teleport you back to the spawn point.
  * Enter away mode by pressing ESC
  * Exit away mode by pressing ESC.
  * Exiting away mode should *NOT* teleport you back to the spawn point.
  * Enter HMD mode.  move the avatar around the scene.  the "apostrophe" button should work as expected and recenter the avatar beneath you.
  * Exit HMD mode, then move the avatar around the scene.
  * While in desktop mode, pressing the "apostrophe" key should *NOT* teleport you back to your last location while in HMD mode.
  * Enter away mode by pressing ESC.
  * Exit away mode by pressing ESC.
  * exiting away mode should *NOT* teleport you back to your last location while in HMD mode.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d82410bc5f44d7804441bd17db6aaa01bcbc150 available at: https://gist.github.com/d45ba60c1e5a2125e7e09aa0321fd48a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9151-6d82410.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9151-6d82410.dmg

**Comment by OmegaHeron** [comment]
Testing

**Comment by OmegaHeron** [comment]
Windows 10
QA Pass

Tested all permutations of test list plus my own.

**Pull request merged**
