### PR TITLE
fixed looping sample sound bug

### PR DESCRIPTION
**Pull request by druiz17**
fixed looping sample sound bug

link to fogzbug - https://highfidelity.fogbugz.com/f/cases/6342/Play-Sample-Sound-becomes-playable-while-audio-is-still-looping

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan 
- open the audio window
- quickly toggle "play sample sound" button
- the sample sound should never be playing when the play icon is shown on the button.

**Comment by Nex-Pro** [comment]
Awaiting Win Build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3969/HighFidelity-Beta-PR11550-cd97ab0fdfd4f23ee5d90d37c979590a377c2dc7.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3975/HighFidelity-Beta-PR11550-cd97ab0fdfd4f23ee5d90d37c979590a377c2dc7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3975/HighFidelity-Beta-PR11550-cd97ab0fdfd4f23ee5d90d37c979590a377c2dc7.exe

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### PASS

Couldn't break it.

**Pull request merged**
