### PR TITLE
Fix tablet not loading webpage when tablet root not initialized 

### PR DESCRIPTION
**Pull request by druiz17**
Fix tablet not loading webpage when tablet root not initialized

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
 - launch interface
-  do not open your tablet
- follow is test plan https://highfidelity.testrail.net/index.php?/cases/view/2184&group_by=cases:section_id&group_order=asc&group_id=442
- when you reach step 13 (this step should be the first time the tablet is opened), the market place item page should appear when the tablet comes up. The tablet should not be on the home page.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5066/HighFidelity-Beta-PR11850-427f6768597cf437a8133a2f17669a0fea6f0f3b.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5078/HighFidelity-Beta-PR11850-427f6768597cf437a8133a2f17669a0fea6f0f3b.dmg

**Comment by cain-kilgore** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5081/HighFidelity-Beta-PR11850-427f6768597cf437a8133a2f17669a0fea6f0f3b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5081/HighFidelity-Beta-PR11850-427f6768597cf437a8133a2f17669a0fea6f0f3b.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
[TestRail Run 1028](https://highfidelity.testrail.net/index.php?/runs/view/1028&group_by=cases:section_id&group_order=asc)

**Pull request merged**
