### PR TITLE
Higher quality standing and seated reactions

### PR DESCRIPTION
**Pull request by hyperlogic**
* The clap, applaud and pointing reactions now include a sequence of intro, loop and outro animation clips.  This improves the overall quality of the reactions as they are enabled and disabled.
* All reactions work while seated and some include several variations.
* Small bug fix to the evaluateBoth interpType, when reactions are triggered repeatedly.

https://highfidelity.atlassian.net/browse/DEV-329
https://highfidelity.atlassian.net/browse/DEV-272
https://highfidelity.atlassian.net/browse/DEV-333

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20803/HighFidelity-Beta-PR16045-ef81cca.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20803/HighFidelity-Beta-Interface-PR16045-ef81cca.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20803/HighFidelity-Beta-PR16045-ef81cca.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20803/HighFidelity-Quest-Beta-PR16045-ef81cca.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20803/HighFidelity-Beta-PR16045-ef81cca.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20803/HighFidelity-Beta-Interface-PR16045-ef81cca.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20805/HighFidelity-Beta-PR16045-b486950.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20805/HighFidelity-Beta-Interface-PR16045-b486950.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20807/HighFidelity-Beta-PR16045-b486950.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20807/HighFidelity-Beta-Interface-PR16045-b486950.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20807/HighFidelity-Beta-PR16045-b486950.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20807/HighFidelity-Beta-Interface-PR16045-b486950.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20807/HighFidelity-Beta-PR16045-b486950.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20807/HighFidelity-Quest-Beta-PR16045-b486950.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20811/HighFidelity-Beta-PR16045-733d745.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20811/HighFidelity-Beta-Interface-PR16045-733d745.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20811/HighFidelity-Beta-PR16045-733d745.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20811/HighFidelity-Beta-Interface-PR16045-733d745.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20811/HighFidelity-Beta-PR16045-733d745.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20811/HighFidelity-Quest-Beta-PR16045-733d745.apk)

**Pull request merged**
