### PR TITLE
Add support for new Touch grip mappings to tutorial

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7e234f07ce0fbbcba3d6d1087a171d1126f4f8a available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-c7e234f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-c7e234f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d4e0ebed4ab0935f500bc3fa03362de2d186fe72 available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-d4e0ebe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-d4e0ebe.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 28e88c4895e907f249195ace87a98ee763a90df6 available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-28e88c4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-28e88c4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b5a05c409a193df7a1fe2061c8265b8b4014459 available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-8b5a05c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-8b5a05c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ddacd4b1a12dcf215124397a826f2696dbe44118 available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-ddacd4b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-ddacd4b.dmg

**Comment by huffman** [comment]
To test:
 1. Confirm that far grabbing and near grabbing work
 1. Confirm that scaling your avatar works using your controller's grip buttons
 1. Confirm that scaling entities works using your controller's grip buttons

**Comment by hifi-gustavo** [comment]
Build console output for commit: 627a5d56daedef1c0761584596b6a5541a2b690e available at: https://gist.github.com/9ba9986bf925e8f3509934334b2ca76c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-627a5d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9247-627a5d5.dmg

**Comment by claudioshg** [comment]
### Tested Windows 10 - CV1 HMD

    Confirm that far grabbing and near grabbing work: SUCCESS
    Confirm that scaling your avatar works using your controller's grip buttons: SUCCESS
    Confirm that scaling entities works using your controller's grip buttons: PENDING
    Confirm that the tutorial works: SUCCESS

**Pull request merged**
