### PR TITLE
Show invalidated items in My Purchases

### PR DESCRIPTION
**Pull request by zfox23**
Previously, we didn't show invalid items in My Purchases. Now we do (which should have been the behavior all along).

Also, we make sure that you cannot REZ or GIFT an item that is invalidated.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9755/HighFidelity-Beta-PR13166-81ebb681bb185ff5ec5430e981333425b79f7be8.apk

**Comment by zfox23** [comment]
## Test Plan
### Notes
This will require some coordination with Zach (or some other Marketplace admin) -- so perhaps we will test this internally.

### Prerequisites
- A HiFi account on the Staging marketplace and auth'd Wallet

### Test Plan
1. Purchase an item from the Staging marketplace - this item needs to be one that Zach knows about, so that he knows which item to invalidate
    i. Verify that the purchase goes through just fine, and gets confirmed
2. Have Zach create an update for the item from (1).
    i. Verify that your Purchases shows that you have an update available for the item from (1).
    ii. Verify that you can still Rez or Gift the item from (1).
3. Have Zach invalidate the item from (1).
    i. Verify that you cannot Rez or Gift the item from (1).
    ii. Verify that you still see the item from (1) in Purchases.
    iii. Verify that you can no longer Rez or Gift the item from (1).
4. Attempt to update the item from (1).
    i. Verify that you can update the app just fine.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9756/HighFidelity-Beta-PR13166-2a1c2ba7b1ce7fe3e583117f4d2a3c2f18f0f2d4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9756/HighFidelity-Beta-PR13166-2a1c2ba7b1ce7fe3e583117f4d2a3c2f18f0f2d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9756/HighFidelity-Beta-Interface-PR13166-2a1c2ba7b1ce7fe3e583117f4d2a3c2f18f0f2d4.exe

**Comment by howard-stearns** [comment]
Just checking: does the "invalidated" label still work in My Purchases? (or did it get ripped out at some point?) 
See the wireframes in https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/60466632/PoP+Coin
(search for "state pending and invalidated", "invalidated mean", "transitions look like"...)

**Comment by zfox23** [comment]
@howard-stearns great question, thanks for asking.

I don't think that labeling has worked for a long time. At some point (I don't remember when or why, but I could find out), we switched from the backend labeling invalid purchases via the `purchaseStatus = "invalid"` to `valid = false`. I don't think we switched the label to look for that logic, and I don't know what all of the repercussions of that switch are.

I'll look more into this in a couple of minutes (once I get my sandwich and arrive in the office).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9767/HighFidelity-Beta-PR13166-fbec2859234d205f9129ed025d9247fdf19b53d6.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9768/HighFidelity-Beta-PR13166-83cae5460101cae5f8f5c3c76d3e76a24790ce3a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9768/HighFidelity-Beta-PR13166-83cae5460101cae5f8f5c3c76d3e76a24790ce3a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9768/HighFidelity-Beta-Interface-PR13166-83cae5460101cae5f8f5c3c76d3e76a24790ce3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9768/HighFidelity-Beta-PR13166-83cae5460101cae5f8f5c3c76d3e76a24790ce3a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9768/HighFidelity-Beta-Interface-PR13166-83cae5460101cae5f8f5c3c76d3e76a24790ce3a.exe

**Comment by zfox23** [comment]
QA'd by @howard-stearns

**Pull request merged**
