### PR TITLE
Tablet ui fix edit props race

### PR DESCRIPTION
**Pull request by sethalves**
- work around a race that can cause edit's properties page to not update correctly when something is selected before the page's tab is shown

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 531b77928a21568d1579db0cdec79536bc3bf6ce available at: https://gist.github.com/1de5b6204e4c6b36f6d1ba021be87bdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9853-531b779.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9853-531b779.dmg

**Comment by sethalves** [comment]
to test:
- with HMD on, open edit
- select an entity
- switch to properties tab
- make sure the selected entity's properties are shown
- close edit
- repeat a few times

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88e74251a160fb8efb6e3b889abba32589bde61b available at: https://gist.github.com/1de5b6204e4c6b36f6d1ba021be87bdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9853-88e7425.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9853-88e7425.dmg

**Comment by Nex-Pro** [comment]
testing this.

**Comment by Nex-Pro** [comment]
In general this works.
However, on multiple occasions I found the edit icon was lit on opening tablet after previous editing event.
See image.
edit_icon_lit_when_inactive

**Pull request merged**
