### PR TITLE
test for new home content set, random port with AC audio search script

### PR DESCRIPTION
**Pull request by birarda**
This is a DNM PR for a company test this AM with a new home content set, a randomized domain-server listening port and the AC audio search script.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b1a2e3a5b726537ebffa59ab8872a4c6fe079bab available at: https://gist.github.com/5631c00def3e55e4f8cbc5b77134d881<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a2182aee54124ea3ac956a5954cea52fab89c22 available at: https://gist.github.com/5631c00def3e55e4f8cbc5b77134d881<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 77d5edcd0c65b3388b294869e2c1f848886ee76f available at: https://gist.github.com/5631c00def3e55e4f8cbc5b77134d881<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10fbd1d00bd18f4a4c21f0b9ca1bcad374989a4b available at: https://gist.github.com/5631c00def3e55e4f8cbc5b77134d881<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7526.dmg

**Pull request closed without merging**
