### PR TITLE
DOC-241: ContextOverlay JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- ContextOverlay

Also:
- Updated WalletScripingInteface JSDoc with links to a relevant ContextOverlay method.

Case: https://highfidelity.atlassian.net/browse/DOC-241

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22802/HighFidelity-Beta-PR16570-9234970.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22802/HighFidelity-Beta-Interface-PR16570-9234970.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22802/HighFidelity-Beta-PR16570-9234970.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22802/HighFidelity-Quest-Beta-PR16570-9234970.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22802/HighFidelity-Beta-PR16570-9234970.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22802/HighFidelity-Beta-Interface-PR16570-9234970.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22808/HighFidelity-Beta-PR16570-9234970.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22808/HighFidelity-Beta-Interface-PR16570-9234970.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22808/HighFidelity-Beta-PR16570-9234970.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22808/HighFidelity-Quest-Beta-PR16570-9234970.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22808/HighFidelity-Beta-PR16570-9234970.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22808/HighFidelity-Beta-Interface-PR16570-9234970.exe

**Pull request merged**
