### PR TITLE
DOC-55: Miscellaneous JSDoc additions and fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
JSDoc updates for recent API changes and various other API doc fixes.

Note: No executable code changes.

Case: https://highfidelity.atlassian.net/browse/DOC-55

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22816/HighFidelity-Beta-PR16578-a04e57d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22816/HighFidelity-Beta-Interface-PR16578-a04e57d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22816/HighFidelity-Beta-PR16578-a04e57d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22816/HighFidelity-Quest-Beta-PR16578-a04e57d.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22816/HighFidelity-Beta-PR16578-a04e57d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22816/HighFidelity-Beta-Interface-PR16578-a04e57d.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22817/HighFidelity-Beta-PR16578-a04e57d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22817/HighFidelity-Beta-Interface-PR16578-a04e57d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22817/HighFidelity-Beta-PR16578-a04e57d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22817/HighFidelity-Quest-Beta-PR16578-a04e57d.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22817/HighFidelity-Beta-PR16578-a04e57d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22817/HighFidelity-Beta-Interface-PR16578-a04e57d.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22823/HighFidelity-Beta-PR16578-00bd81b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22823/HighFidelity-Quest-Beta-PR16578-00bd81b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22823/HighFidelity-Beta-PR16578-00bd81b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22823/HighFidelity-Beta-Interface-PR16578-00bd81b.dmg

**Comment by hd23408** [comment]
Closing in favor of https://github.com/highfidelity/hifi/pull/16583

**Pull request closed without merging**
