### PR TITLE
Mac OS X fixes

### PR DESCRIPTION
**Pull request by hyperlogic**
* don't crash if touchscreenDevice is null
* as a post build step, copy scripts folder into the appropriate place.  If you don't do this default scripts will fail to load and relative script paths are broken as well.  NOTE: this only affects building from source.

### CODE REVIEW

**Comment by hyperlogic** [comment]
Test plan:
  * On Mac OS X use the track pad with two fingers and drag.  On master this will cause a crash, this PR fixes this issue.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad7fa971aa601ad1427694160d48409d9a07c095 available at: https://gist.github.com/e887d61e7a0fc0d5fca8d37ee4cd988a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8272-ad7fa97.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8272-ad7fa97.dmg

**Comment by hyperlogic** [comment]
Jenkins git fail?

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)

lets' try this again. test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad7fa971aa601ad1427694160d48409d9a07c095 available at: https://gist.github.com/e887d61e7a0fc0d5fca8d37ee4cd988a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8272-ad7fa97.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8272-ad7fa97.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Was successfully able to use the track pad with two fingers and drag on Mac OS.

**Pull request merged**
