### PR TITLE
switch to backtrace's newer crashpad blob

### PR DESCRIPTION
**Pull request by sethalves**
- switch to backtrace's newer crashpad blob

### CODE REVIEW

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8703/app_12864_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8703/HighFidelity-Beta-PR12864-625905007fc2224908d308e19d67480cd77fce71.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by L370** [comment]
We've confirmed receipt of a generated crash in PR12864.  We are seeing @ 1 hour delay between the time the crash occurs and the time it is reported in Backtrace.  There are a total of 3 crashes that have been generated.  Once we confirm all 3 events were received, we can approve this PR.

**Comment by Atlante45** [comment]
@L370 That doesn't sound right. Crashes show up instantly on backtrace.
I just tested and was able to confirm it.
I was only seeing 1 crash for the PR prior to me testing it.
One thing worth mentioning is that we do not catch all types of crashes.
Is it possible used some crash options that we do not catch, tried again 1h later with one we do catch and thought that was the first one showing up?
To reliably test this, I recommend using the "Pure virtual call" (not the threaded one) crash that we do catch every time.

**Comment by L370** [comment]
@Atlante45 we followed the guidance Seth provided, which was to install the pr and then invoke the crash via the developer menu.

**Comment by L370** [comment]
OK so we're going to invoke each crash type 5 times to see how well backtrace is capturing these events

**Comment by L370** [comment]
In order to test backtrace, we invoked each crash from the dev menu several times.  From that test, @Atlante45 found that threaded crashes are not being captured correctly.  Therefore this PR has failed and we look forward to the next PR that will address this.

**Comment by L370** [comment]
Manuscript ticket 14215 has been opened and assigned to @Atlante45

**Comment by Atlante45** [comment]
@L370 @conklin94122 this is a QA PASS, as mentioned in my previous comment, the issue found is something separate that's been here from the start.

**Pull request merged**
