### PR TITLE
Fix opened running scripts

### PR DESCRIPTION
**Pull request by vladest**
check case: https://highfidelity.fogbugz.com/f/cases/5711/Switching-to-HMD-with-Running-Scripts-open-causes-floating-dialog

Test steps:
- In desktop mode, open Running Scripts dialog
- Switch to tablet mode
- Make sure desktop's Running Scripts dialog is closed
- Make sure Tablet opened with Running Scripts dialog

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2136/HighFidelity-Beta-PR11088-e30e0b1a5f43f92c6ef0cc7e6117da209a6f3812.dmg

**Comment by sethalves** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2147/HighFidelity-Beta-PR11088-e30e0b1a5f43f92c6ef0cc7e6117da209a6f3812.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2147/HighFidelity-Beta-PR11088-e30e0b1a5f43f92c6ef0cc7e6117da209a6f3812.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Failed**

Everytime I loaded up the game to try this for test, tablet showed this, regardless of opening running scripts beforehand or not.

image

Logs attached.
[Logs.zip](https://github.com/highfidelity/hifi/files/1189009/Logs.zip)

**Comment by YuppyPlays** [comment]
Further to previous comment:

This issue occured with the following steps:
 - Launched Sandbox
 - Launched Interface
 - When game loads into VR automatically with HMD plugged in, used top menu bar of the application to change to Desktop mode.
 - Desktop mode gives up a message regarding going to Home within sandbox due to tutorial.
 - From here I pressed the VR icon within the desktop modes toolbar
 - Now in VR, using the corresponding button on the motion controller open tablet
 - Tablet shows blank page with the microphone icon and username displayed.

[Re-tested this now just to ensure these steps are accurate to what gave me the bug]

Hope this helps.

**Comment by themelissabrown** [comment]
The above black tablet is a bug. Will have a different QA person test this.

**Comment by vladest** [comment]
@YuppyPlays probably you got some non related issue, I have something similar issue in cases, which is not related to reopening Running Scripts

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
Same issue as @YuppyPlays  

This does not occur in 6945

**Comment by Nex-Pro** [comment]
Additionally:  
This does not affect HMD mode when switching between toolbar and tablet modes via the toolbar(hud) menu.
I re-ran this a few times and did get a working tablet in desktop mode.
This is an odd one.

 I completely un-installed this and deleted the folders in local and roaming.  I unplugged my vive. 
Installed this again.
Followed the steps above and the tablet was fine.

Clean installed again. This time plugged vive in.
Followed steps above. Issue came back.

This may somehow be linked with swapping from HMD to desktop.

**Comment by Nex-Pro** [comment]
I just repro'd this in 6945 so this is not specific to this build.

**Comment by anshuman64** [comment]
@YuppyPlays Once this builds, can you test again please? You should not have that blank tablet issue.

**Comment by YuppyPlays** [comment]
@anshuman64  No problem, I believe it was fixed in another PR I'd had a go on also, will test once build finishes :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2235/HighFidelity-Beta-PR11088-a439cc18372164e81290faeb325061ba7ab69afd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2235/HighFidelity-Beta-PR11088-a439cc18372164e81290faeb325061ba7ab69afd.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In desktop mode, open Running Scripts dialog **Check**
Switch to tablet mode **Check**
Make sure desktop's Running Scripts dialog is closed **If this is referring to the desktop window displaying whilst in HMD, then Check :)**
Make sure Tablet opened with Running Scripts dialog **Check**

All **Pass** - Please let me know if there is anything more I can do/provide to assist.

**Pull request merged**
