### PR TITLE
Fix crash when switching to desktop mode from oculus HMD mode

### PR DESCRIPTION
**Pull request by hyperlogic**
Removed internalPresent in oculus uncustomizeContext.  It had no ill effects.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1870/crash-on-oculus-when-trying-to-switch-from-HMD-to-desktop-mode

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ab76984ad8f08900fd27c63f20f0c3e60dbca84 available at: https://gist.github.com/b1e9e3411c827bb149fdfa197fed4950<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-7ab7698.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-7ab7698.dmg

**Comment by ZappoMan** [comment]
Can you explain this fix?

**Comment by hyperlogic** [comment]
During the code review for #8755, @jherico suggested that the hmdPresent that I removed, to prevent a deadlock in openvr, was there to fix an issue on oculus. So I moved the hmdPresent from HMDPlugin to OculusBasePlugin. Unfortunately, it caused this crash.

I could not reproduce the issue that @jherico mentioned, the screen being frozen on the last image from interface after switching into desktop mode.  So, the easiest, least risk fix is to remove hmdPresent altogether when switching away from the oculus display plugin.

**Comment by OmegaHeron** [comment]
QA Fail
Windows 10 - i5 6500 CPU - GTX 970 GPU
Starting in desktop mode, switched to DK2 HMD, back to desktop mode and crash 3 for 3 attempts.  Bugsplats sent for all.

**Comment by hyperlogic** [comment]
So, all the bug splats that @OmegaHeron posted were crashes in AudioClient.  I have not been able to reproduce this.  However, I made a speculative fix.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 350977f03e77ca73043e24159d20893acd53de60 available at: https://gist.github.com/b1e9e3411c827bb149fdfa197fed4950<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-350977f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-350977f.dmg

**Comment by OmegaHeron** [comment]
That fixes my crashing on DK2->Desktop mode change.  Now trying to see why I lose my HUD icon strip once I return to desktop mode.

**Comment by jherico** [comment]
This functions fine for me, although I'm still seeing a crash on exit if the Oculus plugin was in use.  Appears to be a distinct issue though.

**Comment by hyperlogic** [comment]
Build failed FTPing symbols to bugsplat, let's try again.  test this please.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 350977f03e77ca73043e24159d20893acd53de60 available at: https://gist.github.com/b1e9e3411c827bb149fdfa197fed4950<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-350977f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8774-350977f.dmg

**Comment by RyanDowne** [comment]
This prevents the crash but the HUD is only visible in HMD mode.

**Comment by OmegaHeron** [comment]
Well - HUD is initially there in desktop mode but is no seen after moving to HMD mode then back to desktop until Interface is restarted - then it's usually located just inside screen bounds on far right for Desktop.  Outside this PR, but, I re-iterate my desire for Interface to simply remember my choice of posits for elements in each mode rather than try to constantly guess where things should be on mode switches.

**Comment by ZappoMan** [comment]
QA Approved by Austin... there's other bugs that might cause crashes. but this fix definitely fixes some.

**Pull request merged**
