### PR TITLE
DEV-565/Reconsider-the-emoji-pop-sound-on-the-out-animation

### PR DESCRIPTION
**Pull request by MiladNazeri**
https://highfidelity.atlassian.net/browse/DEV-565

### CODE REVIEW

**Comment by MiladNazeri** [comment]
👍

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21256/HighFidelity-Beta-PR16177-275350c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21256/HighFidelity-Beta-Interface-PR16177-275350c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21259/HighFidelity-Beta-PR16177-4c34074.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21259/HighFidelity-Quest-Beta-PR16177-4c34074.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21259/HighFidelity-Beta-PR16177-4c34074.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21259/HighFidelity-Beta-Interface-PR16177-4c34074.dmg

**Comment by MiladNazeri** [comment]
rebuild please

**Comment by MiladNazeri** [comment]
please rebuild

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21260/HighFidelity-Beta-PR16177-4c34074.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21260/HighFidelity-Quest-Beta-PR16177-4c34074.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21260/HighFidelity-Beta-PR16177-4c34074.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21260/HighFidelity-Beta-Interface-PR16177-4c34074.dmg

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21265/HighFidelity-Beta-PR16177-4c34074.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21265/HighFidelity-Quest-Beta-PR16177-4c34074.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21265/HighFidelity-Beta-PR16177-4c34074.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21265/HighFidelity-Beta-Interface-PR16177-4c34074.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21265/HighFidelity-Beta-PR16177-4c34074.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21265/HighFidelity-Beta-Interface-PR16177-4c34074.exe

**Pull request merged**
