### PR TITLE
Build 44.1 Hotfix Fix for lights, crash on switching domains and import objects

### PR DESCRIPTION
**Pull request by cozza13**
Build 44.1 Hotfix Fix for lights, crash on switching domains and import objects

### CODE REVIEW

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/885/HighFidelity-Beta-PR10752-03f3a7eefd9a52063a1186312f6c9115702bbacc.exe

**Comment by CainFoool** [comment]
# Test Passed 

Game appears to work okay, was able to run through the tutorial with no problems. Switching domains didn't cause any issues.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/892/HighFidelity-Beta-PR10752-03f3a7eefd9a52063a1186312f6c9115702bbacc.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/894/HighFidelity-Beta-PR10752-03f3a7eefd9a52063a1186312f6c9115702bbacc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/894/HighFidelity-Beta-PR10752-03f3a7eefd9a52063a1186312f6c9115702bbacc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/901/HighFidelity-Beta-PR10752-08b6c4f829998634e8de697767639cbc84b183ad.exe

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/907/HighFidelity-Beta-PR10752-08b6c4f829998634e8de697767639cbc84b183ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/907/HighFidelity-Beta-PR10752-08b6c4f829998634e8de697767639cbc84b183ad.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/910/HighFidelity-Beta-PR10752-08b6c4f829998634e8de697767639cbc84b183ad.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/910/HighFidelity-Beta-PR10752-08b6c4f829998634e8de697767639cbc84b183ad.dmg

**Pull request merged**
