### PR TITLE
DO NOT MERGE: Temporary fix for Create issues

### PR DESCRIPTION
**Pull request by huffman**
The only purpose of this PR is to get a build. A separate merge-able fix for the bug this "addresses" will come later.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20467/HighFidelity-Beta-PR15958-81def52.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20467/HighFidelity-Beta-Interface-PR15958-81def52.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20467/HighFidelity-Beta-PR15958-81def52.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20467/HighFidelity-Quest-Beta-PR15958-81def52.apk)

**Comment by huffman** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20478/HighFidelity-Beta-PR15958-81def52.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20478/HighFidelity-Quest-Beta-PR15958-81def52.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20478/HighFidelity-Beta-PR15958-81def52.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20478/HighFidelity-Beta-Interface-PR15958-81def52.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20478/HighFidelity-Beta-PR15958-81def52.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20478/HighFidelity-Beta-Interface-PR15958-81def52.exe

**Pull request closed without merging**
