### PR TITLE
Android - Make the virtual pad (joystick) position fixed. Change assets.

### PR DESCRIPTION
**Pull request by Cristo86**
Changes on joystick:
- Aspect (new assets).
- Position (bottom left).
- Activation surface (only in the circle of the joystick base, not all the left side of the screen)
- Show it always.
- Relocate when showing the bottom bar.
- Limit the drag visualization inside the circle (not an square as now).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7584/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7584/HighFidelity-Beta-PR12519-428f4b7b9d625f2af340fc10a38acbe8ce6dbe38.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7584/HighFidelity-Beta-PR12519-428f4b7b9d625f2af340fc10a38acbe8ce6dbe38.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7597/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7597/HighFidelity-Beta-PR12519-55d52f92df2e2df7ee2d4169c07bb36baf06b9b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7597/HighFidelity-Beta-PR12519-55d52f92df2e2df7ee2d4169c07bb36baf06b9b1.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7605/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7605/HighFidelity-Beta-PR12519-9acb83632c4efcc1e709359a5f7b0a2898de0847.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7605/HighFidelity-Beta-PR12519-9acb83632c4efcc1e709359a5f7b0a2898de0847.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7636/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7636/HighFidelity-Beta-PR12519-b5c3b78d57ee6e85bf3deefdab5533e1e4111655.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7636/HighFidelity-Beta-PR12519-b5c3b78d57ee6e85bf3deefdab5533e1e4111655.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7681/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7681/HighFidelity-Beta-PR12519-76e4a5bef2c4524d467236e14797e163c7f62ff3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7681/HighFidelity-Beta-PR12519-76e4a5bef2c4524d467236e14797e163c7f62ff3.exe

**Comment by jherico** [comment]
Please fix the build warnings:  https://ci.highfidelity.io/job/pr-build/7681/label=ubuntu/warnings21Result/new/

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7724/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7724/HighFidelity-Beta-PR12519-c091bc0bb3d27258ab3d7538b757f573a0d80546.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7724/HighFidelity-Beta-PR12519-c091bc0bb3d27258ab3d7538b757f573a0d80546.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7725/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7725/HighFidelity-Beta-PR12519-0bb56d837d01e8105671b8919e6d567b5e172ec1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7725/HighFidelity-Beta-PR12519-0bb56d837d01e8105671b8919e6d567b5e172ec1.exe

**Comment by Cristo86** [comment]
Ubuntu build is now ok https://ci.highfidelity.io/job/pr-build/7725/label=ubuntu/ . But an unrelated to this PR file (Ktx) generates a warning in macos build @jherico.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7803/app_12519_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7803/HighFidelity-Beta-PR12519-4f0cecefc3be71923edb454874d2f66d3c547ed2.dmg

**Pull request merged**
