### PR TITLE
Don't override place name path with index path

### PR DESCRIPTION
**Pull request by Atlante45**
Test Plan:

With Master:
- Go to `sandbox`, you should be in the sandbox
- Go to `sandbox/`, you should be a 0,0,0

With this PR:
- Go to `sandbox`, you should be in the sandbox
- Go to `sandbox/`, you should be in the sandbox

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5cbe9b1b073c638883255fee3af295e47542bf3d available at: https://gist.github.com/ee8c754d8a3dc7d9f2a363902c178521<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-5cbe9b1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-5cbe9b1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3955c6c4c681c6d08262a9fb021bd1b162750259 available at: https://gist.github.com/ee8c754d8a3dc7d9f2a363902c178521<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f1b2dd8b1ae23910fc72949f82e5659e253a92b4 available at: https://gist.github.com/61fb3a94ff830cea21b7b68c1d26874d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-f1b2dd8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-f1b2dd8.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3955c6c4c681c6d08262a9fb021bd1b162750259 available at: https://gist.github.com/ee8c754d8a3dc7d9f2a363902c178521<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3955c6c4c681c6d08262a9fb021bd1b162750259 available at: https://gist.github.com/ee8c754d8a3dc7d9f2a363902c178521<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8834-3955c6c.dmg

**Comment by cozza13** [comment]
With Master:
- Go to `sandbox`, you should be in the sandbox **CONFIRMED**
- Go to `sandbox/`, you should be a 0,0,0 **CONFIRMED**

With this PR:
- Go to `sandbox`, you should be in the sandbox **CONFIRMED**
- Go to `sandbox/`, you should be in the sandbox **CONFIRMED**

**Pull request merged**
