### PR TITLE
Fix orientation of rectangle3d overlays to match other 3D overlays

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f7cba8a1b6e2f96c48c53b9efb02c584bfa9613 available at: https://gist.github.com/ca3fae8ee74a9cd6acf0

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f7cba8a1b6e2f96c48c53b9efb02c584bfa9613 available at: https://gist.github.com/9af58e3539d39a67302f<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4214.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4214.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f7cba8a1b6e2f96c48c53b9efb02c584bfa9613 available at: https://gist.github.com/80562f4d98f9c8272b89<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4214.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4214.dmg

**Pull request merged**
