### PR TITLE
add -Wsuggest-override to compile flags and deal with fallout

### PR DESCRIPTION
**Pull request by sethalves**
- enable -Wsuggest-override for gcc builds

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- smoke test?  hopefully no functional change.

**Comment by jherico** [comment]
`virtual ... override` is redundant.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 722e88253df8ef7d3da75f555a4a93126cd5f1e1 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-722e882.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-722e882.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 87dbfa7e4748cd142efa70eeed4282196fb93189 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-87dbfa7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-87dbfa7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09b7a5188c8d312ea97e5b3049329f162154c141 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-09b7a51.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-09b7a51.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ccaf7379fc001e7f629a52da898bdc31e4ac457e available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-ccaf737.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-ccaf737.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43c5735baa31c0a1978a1dc0fa7b895d4298f381 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-43c5735.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-43c5735.dmg

**Comment by ZappoMan** [comment]
@jherico while technically `virtual` is not needed for any of the derived classes, I personally think it provides clarity... and yeah... well - `override` is then redundant... but... meh.

**Comment by jherico** [comment]
@ZappoMan `override` is _never_ redundant.  `override` specifically prevents bugs caused by changing the signature of a virtual method in a parent class....

Suppose I have 

```
class Foo {
   virtual int foo() { return 1; }
};

class Bar {
   virtual int foo() { return 2; }
};
```

But then I need to change the signature of the method...

```
class Foo {
   virtual int foo(void * p = nullptr) { return 1; }
};
```

Given the original version of bar, the code will continue to compile, but now anything that takes a `Foo*` and calls `foo()` will be getting `Foo::foo()` even though the intent is to get `Bar::foo()`.  

If the original `Bar::foo()` method had been declared with `int foo() override { return 2; }` (with or without `virtual` in front of it) then as soon as the signature on the base class changed, the code would stop compiling until you changed the signature on all the derived classes that override the base class implementation.  

I'm actually astonished that `override` enforcement isn't available as a warning option in compilers.  The Java equivalent has been for quite a long time.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15ce40ecf40d35c9fdc1597d0cd78a751b2d93bf available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-15ce40e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-15ce40e.dmg

**Comment by sethalves** [comment]
IT BUILT!

**Comment by jherico** [comment]
What do you want, a medal?

**Comment by sethalves** [comment]
Something that will fix my ocd.

**Comment by OmegaHeron** [comment]
Testing Windows 10 - General smoke test, all passes.
Built all on Ubuntu Linux 16.04.1 -- all built and function.
QA Pass

**Comment by ZappoMan** [comment]
@jherico - you misunderstood me... no need for a C++ lesson - I am well aware of the value of `override`. Thanks.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bcda1bb45a1f0741aae3a9c50d85c61da1acc81 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.dmg

**Comment by sethalves** [comment]
I hate you, gustavo

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bcda1bb45a1f0741aae3a9c50d85c61da1acc81 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bcda1bb45a1f0741aae3a9c50d85c61da1acc81 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bcda1bb45a1f0741aae3a9c50d85c61da1acc81 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bcda1bb45a1f0741aae3a9c50d85c61da1acc81 available at: https://gist.github.com/4fcac74d66c336ff5e035f0494e2f808<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8470-9bcda1b.dmg

**Pull request merged**
