### PR TITLE
Eliminated toe wiggle while pucks are enabled.

### PR DESCRIPTION
**Pull request by hyperlogic**
Also, IK is more stable when feet sensors are used without a hip puck.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1110/HighFidelity-Beta-PR10822-8602d57a577c8344962bffd4d2a11a272ac17561.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1110/HighFidelity-Beta-PR10822-8602d57a577c8344962bffd4d2a11a272ac17561.exe

**Comment by hyperlogic** [comment]
The hips still waggle when feet sensors are used without a hip puck.  I'll have a fix for this ASAP

**Comment by hyperlogic** [comment]
QA Test:
  * While wearing feet & hips pucks, driving forward should no longer wiggle the toes.
  * While wearing feet pucks only.  driving forward should no longer wiggle the toes or hips.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1118/HighFidelity-Beta-PR10822-2814c945821edc60f14d692df69812896407e9c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1118/HighFidelity-Beta-PR10822-2814c945821edc60f14d692df69812896407e9c2.exe

**Comment by anshuman64** [comment]
PASS: While wearing feet & hips pucks, driving forward should no longer wiggle the toes. Looks good now.
FAIL: While wearing feet pucks only. driving forward should no longer wiggle the toes or hips. The upper body still does a "pop" once in a while. I think that's a residual of the animation remaining.

**Comment by anshuman64** [comment]
Okay, Tony and I talked about it; it's complicated :) That "pop" will be added to the punchlist, but let's get this PR merged

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1126/HighFidelity-Beta-PR10822-d4122cff5ad20cf5b9db00d62f2e72c3cc9b4a61.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1126/HighFidelity-Beta-PR10822-d4122cff5ad20cf5b9db00d62f2e72c3cc9b4a61.exe

**Pull request merged**
