### PR TITLE
restore WebEntity url sync

### PR DESCRIPTION
**Pull request by howard-stearns**
Web entities have a sourceUrl property accessible to javascript and the create tool, replicated to other participants, and persisted in the entity server.  This PR ensures that each person sees the same thing as people click around on a normal Web page. E.g. a slide deck in which each slide is a separate URL. 

https://highfidelity.fogbugz.com/f/cases/14626/Web-entity-doesn-t-update-sourceUrl

 (This makes no attempt to handle embedded non-html players, nor those poorly designed "single page apps" that maintain state in a cookie instead of through the URL.)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9964/HighFidelity-Beta-PR13207-750ed2ca3c69db8d791b00cc0ce8c971e1cbe185.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9964/HighFidelity-Beta-PR13207-750ed2ca3c69db8d791b00cc0ce8c971e1cbe185.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9964/HighFidelity-Beta-Interface-PR13207-750ed2ca3c69db8d791b00cc0ce8c971e1cbe185.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9964/HighFidelity-Beta-PR13207-750ed2ca3c69db8d791b00cc0ce8c971e1cbe185.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9964/HighFidelity-Beta-Interface-PR13207-750ed2ca3c69db8d791b00cc0ce8c971e1cbe185.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10328/HighFidelity-Beta-PR13207-5595b1f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10328/HighFidelity-Beta-PR13207-5595b1f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10328/HighFidelity-Beta-Interface-PR13207-5595b1f.exe

**Comment by howard-stearns** [comment]
Test Plan:

1. Use the Create tool to create a Web entity.  Note the Source Url property.
2. Click around as rapidly as you can through various links.
3. Keeping track of what page you're now on, quickly open the GoTo and go to a different domain. 
4. Use the GoTo back button to return to the domain that has the Web entity.
5. Use the Create tool to examine the Source Url of the Web entity. It should be the same as you left it in step 3, and indeed the that page should be displayed.
6. Repeat steps 2-5 a few times.

**Comment by howard-stearns** [comment]
Rats. This is missing a checkin from a machine at home. This will have to wait until tomorrow.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10356/HighFidelity-Beta-PR13207-777f8dc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10356/HighFidelity-Beta-PR13207-777f8dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10356/HighFidelity-Beta-Interface-PR13207-777f8dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10356/HighFidelity-Beta-PR13207-777f8dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10356/HighFidelity-Beta-Interface-PR13207-777f8dc.exe

**Comment by howard-stearns** [comment]
now updated with the right code

**Pull request closed without merging**
