### PR TITLE
Don't clip local audio sounds 

### PR DESCRIPTION
**Pull request by howard-stearns**
Fix https://app.asana.com/0/32622044445063/37633564937422

Also, while in that file, quiet one debug logger that occurs with collision sounds (of https://app.asana.com/0/32622044445063/37620738098871).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d99d50f722e7bcd662e3e749e0f47d2a0b9453f available at: https://gist.github.com/813cc55875b0b601024b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5135.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5135.dmg

**Comment by ctrlaltdavid** [comment]
Appears not to play the "microphone muted" sound at all per the updated dialTone.js https://github.com/highfidelity/hifi/pull/5120 ?

**Comment by howard-stearns** [comment]
@ctrlaltdavid: Works for me, e.g., on Mac adding the following to my local dialTone.js:
AudioDevice.muteToggled.connect(function () {
    print('mute');
    if (AudioDevice.getMuted()) {
        print('isMuted');
        Audio.playSound(connectSound, connectSoundOptions);
    }
 });

So, let's try to narrow this down some. Suppose you get a console in Interface by doing Tools->Console, and enter the following:
var web goodbye = SoundCache.getSound("http://public.highfidelity.io/sounds/ConnectionSounds/goodbye.wav");
var localgoodbye = SoundCache.getSound("file://" + Paths.resources + "sounds/goodbye.wav");

Then see which of the following four work. (All four work for me.):
Audio.playSound(webgoodbye, {localOnly: true})
Audio.playSound(webgoodbye, {localOnly: false, position: MyAvatar.position})
Audio.playSound(localgoodbye, {localOnly: true})
Audio.playSound(localgoodbye, {localOnly: false, position: MyAvatar.position})

**Comment by PhilipRosedale** [comment]
I too am seeing what seems to be no local sound playback on windows.

**Comment by ctrlaltdavid** [comment]
Firstly, note that Windows needs 3 x "/"s, i.e., "file:///", in order for local sounds to play.

Secondly, I worked out that using the PR installer, Paths.resources has spaces in it because Inteface is installed into
C:\Program Files (x86)\High Fidelity - Development\Interface PR#5135\ and Windows doesn't like the directory unless it has quotes on each end of the string.
Hence why I didn't get any sound in my previous test. After fixing this ...

I cleared my cache and ran the script starting from "var webgoodbye = ...", with all Audio.playSound() lines commented bar one.
Restarted Interface afresh as I tried out each line.

Windows build 2650:
- { localOnly: true } for both Web and local files played only half the sound.
- { localOnly: false } for both Web and local files played the full sound but there was distortion in the middle.

This PR's Windows build: Same as Windows buil 2650.

My local build that I was working on this morning:
- { localOnly: true } for both Web and local files played the full sound.
- { localOnly: false } for both Web and local files played the full sound but there was still distortion in the middle.

The problem playing the full sound I attributed to the bufferEmpty() signal stopping the audio before the audio completes playing.

Seems to be a separate problem with non-local playback.

**Comment by howard-stearns** [comment]
ok, so let me see if I'm understanding/summarizing correctly:
1) My localgoodbye diagnostic, above, will not work on Windows. Use file:/// instead of file://.
2) local (Paths.resources) won't work on dev builds on Windows anyway. So:
   a) as a diagnostic in this PR ("Don't clip local audio sounds"), use some workaround such as the web url instead.
   b) the PR that defines and uses local resources (DO NOT MERGE - QA for #20576 - Play sound when mic is muted #5120) cannot be tested using the Windows build. I"m not sure what to do about that. Maybe just have faith that it will work in release installer, or else change the use of Paths.resources in dialTone.js, or else change the definition of Paths.resources on Windows. (My intuition is that the latter is best, but verifying that is outside of my immediate concerns.)
3) Using the diagnostic (http url), I find that:
   a) localOnly: false works with and without this PR on Mac and Windows. i.e., it is unaffected. That fits my understanding. For me, it sounds like crap on Windows the first time it is played (with or without this PR), but that has nothing to do with the bug or the PR at hand.
   b) localOnly: true works with this PR on Mac, and clips on Mac without the PR. (as expected)
   c) localOnly: true work better with this PR on Windows than without the PR, but it still clips a bit. (Less clipping than without the PR. Given the variability, maybe other Windows machines are just as bad with and without the PR.) Getting this to work better is going to require setting up a dev environment on Windows (which I am starting to do now).

My understanding (confirmed by these result, I believe) is that @ctrlaltdavid is correct that the problem is bufferEmpty during localOnly injection.  My way of dealing with that is a bit kludgey. Do you have a better way? (Note that the playback does have to be shut down. For example, you can just not emit bufferEmpty at all, but then QT will attempt to keep reading the sound forever, and the various threads will never stop.)

**Comment by ctrlaltdavid** [comment]
@howard-stearns I'll send you a patch in Slack per my description in second to last paragraph, demonstrating a possible solution (not fully tested). AudioClient.h and .cpp changes, plus possible change to AudioInjector.cpp.

**Comment by howard-stearns** [comment]
@ctrlaltdavid I've incorporated your changes. I think the result is a lot cleaner. Can you give this a spin and let me know how it works for you? Thanks so much!

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4dfaba55ec57bf18830723e0691fc2a73ffed1d available at: https://gist.github.com/813cc55875b0b601024b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5135.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5135.dmg

**Comment by ctrlaltdavid** [comment]
@howard-stearns Tested OK by me.

**Comment by howard-stearns** [comment]
Yup. Works for me, too. Thanks David!

**Pull request merged**
