### PR TITLE
Should fix crash in general setting dialog

### PR DESCRIPTION
**Pull request by davidkelly**
This fixes https://highfidelity.fogbugz.com/f/cases/4756/CRASH-Tablet-in-Desktop-Settings-General

If you don't have a vive, when you bring up the settings -> general dialog, you crash.  In desktop you can see this by bringing up the dialog, and unchecking the Desktop Tablet Becomes Toolbar button.  Then try to bring it up again.  Note if you have a vive, this will not crash.

### CODE REVIEW

**Comment by davidkelly** [comment]
Test Plan

(1) you must be on a machine that doesn't (maybe never?) has a vive on it.
(2) open Settings -> General, uncheck the 'Desktop Tablet Becomes Toolbar' checkbox and save changes
(3) open Settings -> General again
(4) on master, you crash
(5) with this PR, you don't

**Comment by CainFoool** [comment]
Testing when built.

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/99/HighFidelity-Beta-PR10527-ae54f9c80a981d1e0d25ad5ba7f040231b8931bb.dmg

**Comment by CainFoool** [comment]
# Test Failed

Crashed with the following (attached logs).
d4995

[hifi-log_172.16.0.150_2017-05-23_01.00.37.txt](https://github.com/highfidelity/hifi/files/1020547/hifi-log_172.16.0.150_2017-05-23_01.00.37.txt)

**Comment by davidkelly** [comment]
hmm -- worked locally so I must have made a mistake -- thx @CainFoool

**Comment by CainFoool** [comment]
@davidkelly No worries! I'll be happy to test again once you send a push out.

**Comment by davidkelly** [comment]
yup this crashes for me on my home machine.  K -- I'll have to fix tomorrow!

**Comment by CainFoool** [comment]
Shall retest.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/114/HighFidelity-Beta-PR10527-1c71d2e6b1808b74f775673f879ed339c88d8022.exe

**Comment by CainFoool** [comment]
# Test Passed 

Settings > General opens up in game as expected.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/114/HighFidelity-Beta-PR10527-1c71d2e6b1808b74f775673f879ed339c88d8022.dmg

**Pull request merged**
