### PR TITLE
Add link in Running Scripts that opens scripts folder

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c5335cfa76f555ba494c05b16183644eefe0b55 available at: https://gist.github.com/329541fb78c45798ab81c98fc194f6c0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7728.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7728.dmg

**Comment by imgntn** [comment]
To test:
1. Open Running Scripts
2. Click "Reveal Scripts Folder"
3. The OS level file browser (windows explorer or finder) should open into the /scripts directory

**Comment by imgntn** [comment]
pass win10

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7728
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Successful test.  Opened running scripts, clicked, "Reveal Scripts Folder" and  The OS level file browser (Windows Explorer) opened into the /scripts directory to the PR successfully.  Screen shot enclosed.
**Successful Logout/Crash:** Successful logout.
capture

**Comment by AlanZimmerman** [comment]
I ran into a sticky and unexpected situation with this:
Despite this not being a supported feature for the HMD, the link still appears and can be clicked. As expected, once clicked it opens the OS file explorer on screen and it's somewhat helpful that Interface goes into away/paused mode at this point, but once I tried to close the open OS window on my 2D screen (still in HMD mode, just peeking at my screen,) it goes away and then seemingly any mouse click to get mouse focus back to Interface's window causes the file explore window to reopen. Also, escape does not seem to unpause. 
Obviously people who click this while wearing an HMD will probably be able to go about their business unaware that an OS window has focus on their monitor, but it seems a little rough. I don't suppose we could hide this feature altogether while in HMD mode, could we?

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7728
**Testing Architecture:** 64-bit MacBook Pro
**Testing OS:** OS X El Capitan
**Testing Locations:** localhost
**Additional Test Results Requested:** Additional Test Results Requested: Successful test on MacBook Pro. Opened running scripts, clicked, "Reveal Scripts Folder" and The OS level file browser (Finder) opened into the /scripts directorysuccessfully. Screen shot enclosed.
**Successful Logout/Crash:** Successful logout.
screen shot 2016-04-21 at 6 16 17 pm

**Pull request merged**
