### PR TITLE
Guard against failure to load skybox tex

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
https://app.asana.com/0/74051501495175/100229456076372

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6322164cfbc7e3da3e20e80c7d3789985710785 available at: https://gist.github.com/7258e0a5060a81fdb8c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7349.dmg

**Comment by zzmp** [comment]
#### Testing

Switch the skybox texture to new, uncached textures until they load. Do it a lot. It shouldn't crash. On current build it will presumably crash.

**Comment by cozza13** [comment]
Test notes for this:

Switch the skybox texture to new, uncached textures until they load. Do it a lot. It shouldn't crash. On current build it will presumably crash.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6322164cfbc7e3da3e20e80c7d3789985710785 available at: https://gist.github.com/7258e0a5060a81fdb8c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7349.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Made 20 unique textures (by drawing random crap on one source 20 times) - Loaded 20 per suggestion above - no crash.  That said, I couldn't get current production build to crash either with same process after deleting cache.  Not sure if 20 is a "lot".

**Comment by zzmp** [comment]
This PR is in response to a crash recorded by @hyperlogic. @hyperlogic do you know if there is a reliable way to repro it? I thought switching through many skybox textures would do it...

**Pull request merged**
