### PR TITLE
Move cubic interpolation method to shared library

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Note: This is a straightforward implementation and use of the cubic interpolation formula hence the short variable names.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa959c4554bfe5b13afa44b66dd1d07353700374 available at: https://gist.github.com/4bacf45655aefba7b6d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.dmg

**Comment by ctrlaltdavid** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa959c4554bfe5b13afa44b66dd1d07353700374 available at: https://gist.github.com/4bacf45655aefba7b6d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d4b35ba5e1c3926b28d9750abe16d5f99e2b38b available at: https://gist.github.com/4bacf45655aefba7b6d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 016f3964ed5fcba9722984f9ddc2dc43afb3c778 available at: https://gist.github.com/4bacf45655aefba7b6d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 016f3964ed5fcba9722984f9ddc2dc43afb3c778 available at: https://gist.github.com/4bacf45655aefba7b6d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5765.dmg

**Pull request merged**
