### PR TITLE
Set UAL default value earlier to be caught by crashpad

### PR DESCRIPTION
**Pull request by Atlante45**
The default value for the UAL is initialized too late to be picked up by the crash handler on first run.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10451/HighFidelity-Beta-PR13335-747c7fd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10451/HighFidelity-Beta-PR13335-747c7fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10451/HighFidelity-Beta-Interface-PR13335-747c7fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10451/HighFidelity-Beta-PR13335-747c7fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10451/HighFidelity-Beta-Interface-PR13335-747c7fd.exe

**Comment by Atlante45** [comment]
## Test Plan:

**Pre-requisite:** Make sure the 2 following directories do **NOT** exist, if they do, delete them.
(You will need to do that between each run of the test plan)
- `C:\Users\<username>\AppData\Roaming\High Fidelity - PR13335`
- `C:\Users\<username>\AppData\Local\High Fidelity - PR13335`


1. Launch Interface
2. Enable the Developper menu
3. Select the option "Developper > Crash > Pure Virtual Function Call"
4. Make sure the following folder contains 1 `.dmp` file:
    - `C:\Users\<username>\AppData\Local\High Fidelity - PR13335\Interface\crashpad-db\reports`

On the current dev and stable releases, you should observe that the `crashpad-db` folder doesn't exist after the first interface run, it is only created on the second run of Interface.

**Comment by Atlante45** [comment]
@conklin94122 does this one needs to be tested as well?

**Comment by conklin94122** [comment]
yup. milestone set. Windows only.

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10514/HighFidelity-Beta-PR13335-747c7fd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10514/HighFidelity-Beta-PR13335-747c7fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10514/HighFidelity-Beta-Interface-PR13335-747c7fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10514/HighFidelity-Beta-PR13335-747c7fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10514/HighFidelity-Beta-Interface-PR13335-747c7fd.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Installed build and verified that the 2 directories were removed. Launched interface and caused crash to occur. A .dmp file appeared in the location specified.

**Comment by sethalves** [comment]
This went into rc68 and then into master via a mergeback.  closing...

**Pull request closed without merging**
