### PR TITLE
DEV-1867: Fix toolbarTest.js

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Case: https://highfidelity.atlassian.net/browse/DEV-1867

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21881/HighFidelity-Beta-PR16336-5292ddd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21881/HighFidelity-Quest-Beta-PR16336-5292ddd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21881/HighFidelity-Beta-PR16336-5292ddd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21881/HighFidelity-Beta-Interface-PR16336-5292ddd.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21897/HighFidelity-Beta-PR16336-5292ddd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21897/HighFidelity-Beta-Interface-PR16336-5292ddd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21897/HighFidelity-Beta-PR16336-5292ddd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21897/HighFidelity-Quest-Beta-PR16336-5292ddd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21897/HighFidelity-Beta-PR16336-5292ddd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21897/HighFidelity-Beta-Interface-PR16336-5292ddd.exe

**Pull request merged**
