### PR TITLE
Re-enable OpenVR support

### PR DESCRIPTION
**Pull request by hyperlogic**
* Re-added OpenVR plugin to Windows build.
* Updated OpenVR plugin to work under threaded present.
* Bug fix for sensor reset in Vive
* Added preview rendering in main window.

Oculus Rift DK2 works in OpenVR but only in mono mode for some reason, I don't think it's due to anything on our side, because the same code path works in the Vive Developer Edition.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 90f0821c2b1a06fc1aa2e00b30d4e87756cb574b available at: https://gist.github.com/a230843b3712985fda66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7067.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7067.dmg

**Comment by ZappoMan** [comment]
Not sure how QA can test this without access to a Vive... certainly they can test that it doesn't break other users... but we need either someone from the HiFi SF office, or @jherico to test this build since they have the only Vives.

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/67945753172062

**Comment by jherico** [comment]
@ZappoMan actually, you can use the OpenVR plugin with a DK2.  However I will attempt to test with the Vive as well.

**Comment by cozza13** [comment]
I have been testing with the vive with @hyperlogic and still testing. @jherico if you can so some on your side that would be great.

**Comment by ZappoMan** [comment]
@jherico as @hyperlogic mentioned - the OpenVR+DK2 doesn't seem to behave that well with the latest OpenVR sdk, so I don't think that's a useful test... testing with the real Vive seems like the more appropriate test path.

**Comment by hyperlogic** [comment]
I'm seeing a conflict with displayPlugin ordering/loading.  Basically, once you have the openVR plugin you can never use the Oculus display plugin.

**Comment by cozza13** [comment]
I have tried this on DK2 and on Vive, both worked for me. Without threaded present on the vive you really notice when/if it drops below 90

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8e6aee3e795eed0c07bd26d757662fddcdccb80 available at: https://gist.github.com/a230843b3712985fda66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7067.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7067.dmg

**Comment by hyperlogic** [comment]
Ok, it's all good now

**Pull request merged**
