### PR TITLE
Fix name conflict with c++ class and qml file(master)

### PR DESCRIPTION
**Pull request by druiz17**
When using the AudioScope class in AudioScope.qml. The qml thought you where referencing the file, instead of the object.

ticket - https://highfidelity.manuscript.com/f/cases/13706/Audio-Scope-Broken

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8354/app_12740_PR.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Audio scope works and basic features work as expected.

**Comment by conklin94122** [comment]
@sethalves ok by you to merge this in?

**Pull request merged**
