### PR TITLE
Adopt path to certain Tablet dialogs to new loading subsystem and pat…

### PR DESCRIPTION
**Pull request by vladest**
Adopt path to certain Tablet dialogs to new loading subsystem and path resolver

https://highfidelity.fogbugz.com/f/cases/10854/The-Running-Scripts-dialog-and-Asset-Browser-windows-won-t-open-in-HMD

Test steps:
- Open tablet -> Menu -> Edit
- Open Running scripts
- Open Asset Browser
- Make sure dialogs are opened

### CODE REVIEW

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5821/app_12041_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5821/HighFidelity-Beta-PR12041-7985c39f2a0c1bf46d1c3d51a96fdc4bb7af293c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5821/HighFidelity-Beta-PR12041-7985c39f2a0c1bf46d1c3d51a96fdc4bb7af293c.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
--- | ---
Open tablet -> Menu -> Edit | 👍 
Open Running scripts | 👍 
Open Asset Browser | 👍 
Make sure dialogs are opened | 👍 

image

Dialogs do open however some look funky - for example in the screen up above; not sure if this is because of this PR or not.

**Comment by vladest** [comment]
@cain-kilgore I think its not related to this PR but can ou please compare to master?

**Comment by tapalisa** [comment]
Additional Test Request:
Can you please check if the Chat App works in this PR?

**Pull request merged**
