### PR TITLE
case Bugz-968 adding a null check to the display plugin. Possible that display plug…

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/BUGZ-968

dangling pointer crash noted in backtrace on QMetaProperty::read for the AbstractHMDScriptingInterface::isHMDMode().  The function gets the activedisplay plugin which may or may not be active especially if the app was requested to shut down as based on bugz info.  

Found that display plugin is destroyed pretty early before scripting interface and qml overlays including offscreenui.  There's potential here that scripts could be referencing display plugin after its been destroyed. 

Test case:

1. Start the app
2. Switch to hmd mode
3. Very quickly shut down the app and watch for a crash from the HDMScriptign interface referencing displayplugin->isHmd()

As a side effect, watch for other crashes that could be caused because display plugin .reset() call is moved after scripting and qml destroy calls.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20318/HighFidelity-Beta-PR15911-d5d5741.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20318/HighFidelity-Quest-Beta-PR15911-d5d5741.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20318/HighFidelity-Beta-PR15911-d5d5741.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20318/HighFidelity-Beta-Interface-PR15911-d5d5741.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20318/HighFidelity-Beta-PR15911-d5d5741.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20318/HighFidelity-Beta-Interface-PR15911-d5d5741.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20338/HighFidelity-Beta-PR15911-efccd10.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20338/HighFidelity-Beta-Interface-PR15911-efccd10.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20338/HighFidelity-Beta-PR15911-efccd10.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20338/HighFidelity-Quest-Beta-PR15911-efccd10.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20338/HighFidelity-Beta-PR15911-efccd10.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20338/HighFidelity-Beta-Interface-PR15911-efccd10.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20343/HighFidelity-Beta-PR15911-15e7663.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20343/HighFidelity-Beta-Interface-PR15911-15e7663.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20343/HighFidelity-Beta-PR15911-15e7663.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20343/HighFidelity-Quest-Beta-PR15911-15e7663.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20343/HighFidelity-Beta-PR15911-15e7663.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20343/HighFidelity-Beta-Interface-PR15911-15e7663.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20363/HighFidelity-Beta-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20363/HighFidelity-Beta-Interface-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20363/HighFidelity-Beta-PR15911-ba6307e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20363/HighFidelity-Quest-Beta-PR15911-ba6307e.apk)

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20369/HighFidelity-Beta-PR15911-ba6307e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20369/HighFidelity-Quest-Beta-PR15911-ba6307e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20369/HighFidelity-Beta-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20369/HighFidelity-Beta-Interface-PR15911-ba6307e.dmg

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20373/HighFidelity-Beta-PR15911-ba6307e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20373/HighFidelity-Quest-Beta-PR15911-ba6307e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20373/HighFidelity-Beta-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20373/HighFidelity-Beta-Interface-PR15911-ba6307e.dmg

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20385/HighFidelity-Beta-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20385/HighFidelity-Beta-Interface-PR15911-ba6307e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20385/HighFidelity-Beta-PR15911-ba6307e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20385/HighFidelity-Beta-Interface-PR15911-ba6307e.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20385/HighFidelity-Beta-PR15911-ba6307e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20385/HighFidelity-Quest-Beta-PR15911-ba6307e.apk)

**Pull request merged**
