### PR TITLE
Case 19373 - Lowering volume on another user in PAL mutes them

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.manuscript.com/f/cases/19373/Lowering-volume-on-another-user-in-PAL-mutes-them

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14614/HighFidelity-Beta-PR14328-9ca862a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14614/HighFidelity-Beta-PR14328-9ca862a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14614/HighFidelity-Beta-Interface-PR14328-9ca862a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14614/HighFidelity-Beta-PR14328-9ca862a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14614/HighFidelity-Beta-Interface-PR14328-9ca862a.exe

**Comment by roxanneskelly** [comment]
Test Plan
* Install Sandbox
* Log in with two users on two computers, and send both to the sandbox where they can hear one another.
* Bring up PAL on one user, and select the other
* Produce audio on the other user (talk, etc.) and verify that the per-user volume slider on the first user attenuates properly.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14933/HighFidelity-Beta-PR14328-0dc8a79.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14933/HighFidelity-Beta-PR14328-0dc8a79.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14933/HighFidelity-Beta-Interface-PR14328-0dc8a79.dmg

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14933/HighFidelity-Beta-PR14328-0dc8a79.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14933/HighFidelity-Beta-Interface-PR14328-0dc8a79.exe

**Comment by qlilaseguinolaza** [comment]
PASS @conklin94122 
The per-user volume slider in the People Nearby tab adjust the user's volume correctly without muting the user.

**Pull request merged**
