### PR TITLE
Make sure Flickable for GridView for TabletHome will not flick

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.manuscript.com/f/cases/edit/12332/Home-page-of-the-tablet-allows-vertical-scroll

Test steps:
- Open Tablet
- Make sure its not flickable vertically
- Make sure its not flickable horizontally when apps <= 12

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7301/app_12435_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7301/HighFidelity-Beta-PR12435-e5f953c103a5df5738b26affc6316ef751555e77.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7301/HighFidelity-Beta-PR12435-e5f953c103a5df5738b26affc6316ef751555e77.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
