### PR TITLE
Remove notifications and print outs when degrading LOD

### PR DESCRIPTION
**Pull request by samcake**
This is just too much noise so we decided to remove the  logging and the notifications whenever the LOD drops.
Bug [13743](https://highfidelity.fogbugz.com/f/cases/13743/REmove-notification-and-logging-of-LOD-change)

## TEST PLAN
In an heavy domain (such as dev-welcome for example) with stats expanded enabled ('/' key and clicked once in that ui)
You can observe the current LOD on the 4th column, bottom row.

In this PR, as the LOD varies and degreade (thus hidding smaller objects) no more notifications appears.
in the log file (ctrl + shipt + l) you don;t see anymore messages about the LOD dropping or improving.

IN master you see all the above

IN HMD, the LOD warning notifications are not visisble anymore either.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8432/app_12762_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8434/app_12762_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8434/HighFidelity-Beta-PR12762-077b2dab30d527136dfbd5b09ce9b38514af12cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8434/HighFidelity-Beta-PR12762-077b2dab30d527136dfbd5b09ce9b38514af12cd.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8452/HighFidelity-Beta-PR12762-2dc4630e68abcb8833df1543109a0647be5d8f4b.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
LOD messages no longer appear as notification in HMD and desktop and do not appear in the log.

**Pull request merged**
