### PR TITLE
[DNM] Marketplace tablet theft prevention

### PR DESCRIPTION
**Pull request by thoys**
This prevents the tablet from being taken by other avatars, and also allows you to teleport to another domain while the market tablet entity stays with you, as well as being able to create the tablet on domains without the requirement of rez permissions.

## Test plan

- Click the market button in HMD
- Ask another avatar to take or edit the marketplace tablet. (This should be impossible)
- Try teleporting to other domains and notice that the marketplace tablet follows you.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4673800d2f0f38534e3ed47aab80934a954b6ab available at: https://gist.github.com/a777b45f758e3598e7c4f737a2c477fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8658-b467380.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8658-b467380.dmg

**Comment by thoys** [comment]
Small bug, on restart, the old tablet still there and is not being detected by the marketplace script yet. Working on a fix

**Comment by Nex-Pro** [comment]
### This is not ready for QA.

**Comment by thoys** [comment]
Howard will take care of this in https://github.com/highfidelity/hifi/issues/8794

**Pull request closed without merging**
