### PR TITLE
Allow the ability to grab attachments

### PR DESCRIPTION
**Pull request by druiz17**
Allow the ability to grab attachments

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- goto dev-distributed...make sure that you can grab and attach attachments

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3858/HighFidelity-Beta-PR11514-33e9a71000c95d3ab4d8434023b3a9f8aa859b2c.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3861/HighFidelity-Beta-PR11514-33e9a71000c95d3ab4d8434023b3a9f8aa859b2c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3861/HighFidelity-Beta-PR11514-33e9a71000c95d3ab4d8434023b3a9f8aa859b2c.exe

**Comment by cain-kilgore** [comment]
# Test Failed

Unable to attach attachments. Grabbing them and dropping them on to my Avatar in HMD causes the Attachment to just sit in mid air.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
