### PR TITLE
New avatar record and playback script

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b29bfd4bb42954a2718fe05afcc35c02ee310fcd available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-b29bfd4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-b29bfd4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23c937e55d03d1d21a65d0e23bf9cc23ff5b80dc available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-23c937e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-23c937e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ef5f048a3460cb61469842662e795f31ea0b10f available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-1ef5f04.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-1ef5f04.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef4f3368f9fadbadcf38195e0b378a0f57cf4b82 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-ef4f336.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-ef4f336.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d60d4d0755d77dd3045467dc3c380343b6952dba available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d60d4d0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d60d4d0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5bf7dc12f661169d6ac55b47ef5d5004869a550 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-b5bf7dc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-b5bf7dc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9495bf6a478d01a3ba9a112b06734afff1f87856 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-9495bf6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-9495bf6.dmg

**Comment by ctrlaltdavid** [comment]
TEST PLAN

Interface script: 		/scripts/system/record.js
Assignment client script: 	/scripts/system/playbackAC.js

"RECORD" icon is displayed on tablet / toolbar for desktop and HMD.

Clicking the "RECORD" icon opens a dialog.

In the dialog:
- The "Enable recording" checkbox defaults to off when you restart the script or restart Interface.
- When you enabling recording with the checkbox instruction text appears:
	If using the tablet (in desktop or HMD mode) the instructions say to close the tablet to start recording.
	If using the toolbar (in desktop or HMD mode) the instructions say to close the window to start recording.
- When you disable recording with the checkbox the instruction text disappears.

If recording is enabled, when you close the tablet / desktop dialog, recording starts:
- Large countdown numbers are displayed - 3, 2, 1 - then recording starts.
- Start of countdown is commented to program log.
- Start of recording at end of countdown is commented to program log.

The countdown numbers are displayed as overlays:
- Desktop countdown overlay is centred in the Interface window, and stays centered as you change screen size.
- HMD countdown overlay is in front of you, anchored to your avatar.

Test recording starting when you close the tablet / dialog in a variety of ways:
- Right-click in space to close tablet.
- Click "x" button on the tablet.
- Controller "B" button to close the tablet.
- Click "x" button on the dialog.
- Click icon in the toolbar.

If counting down, when you open the tablet / dialog countdown stops:
- Termination of countdown is commented to program log.
- Recording is not started (no comment on start of recordeing appears in program log).

If recording, when you open the tablet / dalog recording stops:
- Finish of recording is commented to program log.

If in tablet mode, when you open the tablet to stop recording:
- The icon is highlighted as "on" to indicate that recording is enabled.
- If you close the tablet with the icon highlighted as "on", countdown to recording starts again.

If in toolbar mode :
- ... TBD: icon state reflecting "will record" if close dialog.
- ... TBD: icon state reflecting  "currently recording".

If you stop the script with the dialog open (tablet or window), the dialog closes.

If you stop the script while recording the recording is abandoned:
- Abandonment of recording is commented to program log.
- ... TBD: .hfr file; recording not added to asset server etc.

When you make a recording it is added to the Asset Server as /recordings/yyyymmdd-hhmmss.hfr, where the date and time values are UTC.
If the recording file cannot be added to the Asset Server an error dialog is displayed. (For example, stop the server before finishing the recording.)
If the recording file cannot be mapped to /recordings/yyyymmdd-hhmmss.hfr an error dialog is displayed. (There may be no easy way to test this.)

With N instances of the playRecordingAC.js script running on the server...
A recording just made is automatically played from the original start location and orientation of the recording (not your avatar's current end-of-recording location and orientation; i.e., the recording plays out at its original location and orientation) if there is a spare AC script available to play it.
If there isn't a spare AC script available to play it, you are informed of this in an error dialog.
If the recording fails to start playing, you are informed of this in an error dialog. (For example, AC script can't create an entity. There may be no easy way to generate this condition.)

When you (re)start the server, recordings are automatically played. (Up to N recordings if you have N instances of the playback script running.)

The recordings dialog displays a table of the recordings currently being played in the domain.

The recordings dialog displays a count of the number of AC player scripts running.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd639608767150076b0a52d74d24e9b608264729 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-bd63960.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-bd63960.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 86baf785aa29bc939b96cdd9b53e5022b4d3493d available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-86baf78.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-86baf78.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50a06db1b9bb0f386236e5fc68ee2484ccc75f47 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-50a06db.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-50a06db.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 75e4fb3820e22772d43f6a3a55b0c0cb587cbf9d available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-75e4fb3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-75e4fb3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 072e06123f5c18634974b01371bb554bfd437a48 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-072e061.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-072e061.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f71585076630655f332dde4cf9abc9a337d9c933 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-f715850.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-f715850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e91cf4a4e8a8f01f1beb79f5da04ec1b085b8be3 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-e91cf4a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-e91cf4a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15128faa490a54e4544a3a1de068cfe7d1e8e5d6 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-15128fa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-15128fa.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7dcda47f95f5cb2cb63b5784e6db286653bf411a available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7dcda47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7dcda47.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7dcda47f95f5cb2cb63b5784e6db286653bf411a available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7dcda47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7dcda47.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 00b6b2a2c0d52ee0bfe6d23cae50da8bcbac72ed available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-00b6b2a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-00b6b2a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f7d87c4c28b79269a4d60f3bffbf3feef2003941 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-f7d87c4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-f7d87c4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43619d1db1bb9513ad3e9312f30aae5c8f2f3aa7 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-43619d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-43619d1.dmg

**Comment by zzmp** [comment]
Is it possible for you to split the scripts into modules? Many of these files are too long to digest, which means they will be harder to debug if something is wrong or a change breaks them in the future.

**Comment by ctrlaltdavid** [comment]
@zzmp The main record.js file - this is the long one - is split into modules internally (which you can collapse in Visual Studio): RecordingIndicator, Recorder, Player, Dialog.
This "app" is going to be put on the marketplace so I imagine the fewer files the better.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 076bf0943e7e481b256a07fd920d6428a1b774ac available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 076bf0943e7e481b256a07fd920d6428a1b774ac available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 076bf0943e7e481b256a07fd920d6428a1b774ac available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-076bf09.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce86ce45302d4b87c24aa2c055e896232582b65d available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-ce86ce4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-ce86ce4.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7fe0ba19b503aca8784a292b26ccb67ea6ea8aec available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7fe0ba1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7fe0ba1.dmg

**Comment by anshuman64** [comment]
Have QA tester that is looking at this!

**Comment by hifi-gustavo** [comment]
Build console output for commit: d73fd6e08d34c734134cd448e5d6befee79a3a36 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d73fd6e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d73fd6e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c0a258f9b30f47712bf4fcc1e484e4e8fcc4a87a available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c0a258f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c0a258f.dmg

**Comment by sharsein** [comment]
Windows build http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c0a258f.exe is fail, grid only appears when zooming out, can't teleport.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79346673ed14c64c567478fabd6e9a2e6b999b35 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7934667.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7934667.dmg

**Comment by sharsein** [comment]
Buzzing avatar issue on Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7934667.exe
Bubble is turned off
I had deleted all previous recordings, reset the script instances in my domain settings, and installed the latest build. I recorded myself without speaking. When I teleport off my recorded avatar, a loud noisey buzzing sound occurred. I encountered this issue an older build as well http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7fe0ba1.exe

Things that were different in current PR10130-7934667 that did not occur in the older build:
- The buzzing sound stopped when I created another recording
- A blue audio bar appeared on my screen during my second recording, but not my third

Also even though I have bubble turned off, teleporting on top of the recording causes it to shrink and disappear.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d682924b0053458b2753c889d22d1ebf4f9c4357 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d682924.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-d682924.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: c83f82f5da252c3159cbe58ff1da7af0759bfd97 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c83f82f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c83f82f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c83f82f5da252c3159cbe58ff1da7af0759bfd97 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c83f82f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c83f82f.dmg

**Comment by ZappoMan** [comment]
This PR seems to have a lot of unrelated stuff in it.... am I misreading?

**Comment by ctrlaltdavid** [comment]
@ZappoMan No, no unrelated stuff. I had to fix a few bugs as part of getting it working, plus add a Window.browseAssets() dialog in order to be able to load a previously made recording, and make user activity logging available to Interface and AC client scripts.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c2e1aa84683a2e0d91e25f683a3055b2cbe4d72 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7c2e1aa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-7c2e1aa.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5f384d8fb923fe359fe3a12efbda6ecc562f544 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c5f384d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c5f384d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 06f56f024be55d7e90fee88c131d7364a2fe5400 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-06f56f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-06f56f0.dmg

**Comment by sharsein** [comment]
Bugs found in Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-c5f384d.exe

- If you close the record menu after the countdown without pressing stop, when you reopen the countdown is stuck on 3. However if you press stop, your actions/noise are recorded successfully

-Only places that show in my nav bar are dev-welcome and dev-playa. Even though my go to menu says I've teleported there, nothing loads. 

Will continue testing on more recent build.

**Comment by sharsein** [comment]
Finished test run Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive. 
QA failed in Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-06f56f0.exe
Bugs:
- The shrinking bug, as posted above. I believe it can be consistently repro'd by any of these 3 ways:
1. After deleting all recordings in your asset browser, make a new recording. 
2. Have multiples of the same recording running at the same time
3. Restart sandbox server while recording is playing. 

- When launching for the first time after install, audio from recording will not play until user resets the sandbox server. Recordings after that will immediately play sound

- The Stop button still has the gradient, however it's difficult to notice the difference between gradient and solid color on Desktop, let alone the Vive. As a user, this didn't provide too much confusion since label on the button changes from Record to Stop, and red already feels stoppy even if a subtle gradient

- Recordings will eventually stop playing, or stop from the user pausing for an extended period of time. User will need to unload and reload them or restart the sandbox server for them to play again. Since restarting sandbox server to resume playing the animations is in test plan, is this expected?

- playerACs takes a while to load. It took over 5 minutes to load 10 slots.

- Escheology appeared in Places, so I was able to go to a domain outside my home directory. However after the world loaded, I paused to listen to background music and teleport somewhere. When I opened up the record menu, it said I had no playerAC slots available and I could not record. Only other places available were the broken dev-playa and dev-welcome

- I am able to go-to a snapshot. No domain will load.

**Comment by ctrlaltdavid** [comment]
A - Thank you very much for finding and gibing the repro for the countdown-stuck-on-3 bug. Will be fixed in the next PR build.

... TO BE CONTINUED

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4581b9a0df5fcf16e7f7ec20830fbd8a2bd123cb available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-4581b9a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-4581b9a.dmg

**Comment by anshuman64** [comment]
Okay, I know what's going on: I didn't update the AC script in the public folder that Sharon must be using. I retested all of this using the correct AC script and none of the errors that Sharon mentioned are reproducible. Therefore, marking this as a QA Pass!

**Comment by hifi-gustavo** [comment]
Build console output for commit: a68ee02e8df04d526fc0b4c04010f0f0f40e0ad7 available at: https://gist.github.com/7bf76884ee7f24d9603a929bffb06839<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-a68ee02.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10130-a68ee02.dmg

**Pull request merged**
