### PR TITLE
21292 - Implement a script to hand-raise while in desktop mode

### PR DESCRIPTION
**Pull request by Triplelexx**
Added one script:
- hifi/unpublishedScripts/marketplace/tablet-raiseHand/tablet-raiseHand.js

**Test Plan:**
Running the script should create a button on the tablet UI. The button should be labeled RAISE HAND with an icon of a hand.

Pressing the button should raise the avatar's right hand in the air. The button should be highlighted in this state.
This new functionality should not interfere with the handshake functionality. If a handshake is started the button should disable. The handshake animation should have priority.

**Note:**
Hand icons adapted from https://linearicons.com, created by Perxis https://perxis.com CC BY-SA 4.0 license.
Added directly to the resource folder with other tablet icons.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b5f19399c6512d92ee1e79fdb1913e482e02253 available at: https://gist.github.com/94af8bea9d7d137f7bf6878984abb22c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10272-9b5f193.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10272-9b5f193.dmg

**Comment by themelissabrown** [comment]
As per testing notes, please test functionality and interaction with handshake to confirm no interference.

**Comment by ImRichardJackson** [comment]
Windows 10 

When running the script I don't see raise hand icon.

hifi-snap-by-im_rj-on-2017-04-25_13-16-11

**Comment by Triplelexx** [comment]
@ImRichardJackson Did you run the installer build above? If not you will not see the icons. The script should operate correctly running the build using the raw url from here, or from the install path listed.
Please confirm if otherwise.

**Comment by ImRichardJackson** [comment]
I am running  build PR10272.

**Comment by Triplelexx** [comment]
@ImRichardJackson Sorry, I am confused then, I am able to run the script from https://github.com/Triplelexx/hifi/blob/9b5f19399c6512d92ee1e79fdb1913e482e02253/unpublishedScripts/marketplace/tablet-raiseHand/tablet-raiseHand.js  😕 

The button works for me and displays the new icons.

**Comment by themelissabrown** [comment]
Tested by @misslivirose 
feedback:
Raise hand > hit X = a punching motion that can be rapidly repeated to actually look like punching.
Raise hand > hit X = if only pushed once, hand is no longer raised, but button stays pressed

**Comment by ImRichardJackson** [comment]
@themelissabrown Hitting X also worked for me, did the icon pop up for misslivirose?

**Comment by Triplelexx** [comment]
@themelissabrown 
Raise hand > hit X = a punching motion that can be rapidly repeated to actually look like punching.
**I think I would need a suggestion as to what I might do to remedy this unexpected behavior.**
Raise hand > hit X = if only pushed once, hand is no longer raised, but button stays pressed
**I am unable to reproduce this issue.**

**Comment by themelissabrown** [comment]
@Triplelexx have you made any progress with smoothing this motion out?

**Comment by Triplelexx** [comment]
@themelissabrown It's using a single pose to drive the right hand to the target position using the IK system. The only thing I thought of is updating the target position, but that has to be when detecting a handshake. I'm unsure how good the results would be. I'm not sure if a fbx animation would be preferable in this case, or if it would override the handshake.

**Comment by themelissabrown** [comment]
@Triplelexx we can't use FBX animations so we'll live with the potential punch. I need to get you an icon for it from Alan and then we can approve and merge.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b5f19399c6512d92ee1e79fdb1913e482e02253 available at: https://gist.github.com/94af8bea9d7d137f7bf6878984abb22c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10272-9b5f193.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10272-9b5f193.dmg

**Comment by hyperlogic** [comment]
The svg files aren't required to be added to the project.  They can be uploaded to an external hosting site, and referenced via a url.  Concidering this is an unpublished script, it might be best to move the svg's from the interface resource directory, because it will (very slightly) increase our install size.

**Comment by Triplelexx** [comment]
@hyperlogic I tried using resolvePath initially. It would not work. I asked around for a solution.

**Comment by hyperlogic** [comment]
The svg's are small, we'll just move forward on this.

**Pull request merged**
