### PR TITLE
File Dialog Fixes

### PR DESCRIPTION
**Pull request by dback2**
When opening a folder in the file chooser dialogs, fix automatically appending the first sub directory to the path and fix showing button text as Open instead of Choose when no row selected.

Also fix the file chooser dialog Open/Choose and Cancel buttons not working in tablet Snap app settings.

Fixes:
https://highfidelity.manuscript.com/f/cases/6054/
https://highfidelity.manuscript.com/f/cases/15566/

Test Plan:
-Launch Interface in desktop mode
-Open Snap app, choose Settings, and select Browse next to "Put my snapshots here" path
-Open a directory that contains sub directories
-Verify that a sub directory is not appended to the path at the bottom when the directory is opened, but that it is appended once a sub directory row is selected
-Verify when opening any directory that the blue button displays as "Choose" until any sub directory row is selected at which point it becomes "Open"
-Select Choose after opening a directory with sub directories and verify the path that is set under "Put my snapshots here" matches and does not have a sub directory appended
-Open Edit -> Running Scripts and select From Disk
-Verify the script file chooser behaves as expected with no issues
-Open Edit -> Asset Brower and select Choose File
-Verify the asset file chooser behaves as expected with no issues
-Switch to HMD mode and verify the above tests again using tablet's Snap app as well as tablet's Menu -> Edit -> Running Scripts and Menu -> Edit -> Asset Browser
-In the tablet Snap app also verify the Choose/Open and Cancel button texts display and that the buttons behave as expected in tablet Snap app
-Perform above tests on Android as well

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10336/HighFidelity-Beta-PR13292-0748925.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10336/HighFidelity-Beta-Interface-PR13292-0748925.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10336/HighFidelity-Beta-PR13292-0748925.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10336/HighFidelity-Beta-Interface-PR13292-0748925.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10349/HighFidelity-Beta-PR13292-7b2a977.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10349/HighFidelity-Beta-PR13292-7b2a977.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10349/HighFidelity-Beta-Interface-PR13292-7b2a977.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10349/HighFidelity-Beta-PR13292-7b2a977.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10349/HighFidelity-Beta-Interface-PR13292-7b2a977.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Sub-directories are no longer automatically selected when choosing a snapshot location. File dialogs for asset browser and scripts are not negatively affected.

Android was tested, but appears to have none of these functionalities.

**Pull request merged**
