### PR TITLE
BinaryFaceHMD SDK Support

### PR DESCRIPTION
**Pull request by rcloud2**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 760200a6528f3913237654dfb4ea50d83480aa40 available at: https://gist.github.com/5774ee7fd9613f8e1b0d77daf341e149<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-760200a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-760200a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 262eab2f96738baf1affbc34d389ff5f719bbf43 available at: https://gist.github.com/5774ee7fd9613f8e1b0d77daf341e149<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-262eab2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-262eab2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 08e10e5525b1ea38d3d564a82cbd6209b1c9f029 available at: https://gist.github.com/5774ee7fd9613f8e1b0d77daf341e149<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-08e10e5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9333-08e10e5.dmg

**Pull request closed without merging**
