### PR TITLE
RC62: Bug fix to prevent wrists entering the avatar's torso. 

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hyperlogic** [comment]
whoops, I think i messed this up

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6182/app_12133_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6182/HighFidelity-Beta-PR12133-3132d88aaa41109cbfabdf6bd1fb5e88a94b9516.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6182/HighFidelity-Beta-PR12133-3132d88aaa41109cbfabdf6bd1fb5e88a94b9516.dmg

**Pull request closed without merging**
