### PR TITLE
add teleport.fbx back to avatar/animations

### PR DESCRIPTION
**Pull request by dooglifeSF**
compiled and tested in local sandbox but need to test with Jamil in HMD to see that teleport plays correctly for remote viewer

### CODE REVIEW

**Comment by dooglifeSF** [comment]
This is to fix https://highfidelity.atlassian.net/browse/BUGZ-999

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20390/HighFidelity-Beta-PR15929-413a089.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20390/HighFidelity-Beta-Interface-PR15929-413a089.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20390/HighFidelity-Beta-PR15929-413a089.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20390/HighFidelity-Beta-Interface-PR15929-413a089.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20390/HighFidelity-Beta-PR15929-413a089.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20390/HighFidelity-Quest-Beta-PR15929-413a089.apk)

**Comment by dooglifeSF** [comment]
Confirmed fixed by meeting Jamil in Eschatology and watching each other teleport, correctly playing the animation.

**Comment by dooglifeSF** [comment]
Video of working teleport in this PR: https://hifi-content.s3.amazonaws.com/doug/video/debug/teleport_test.mov

**Pull request merged**
