### PR TITLE
Fix edit.js to make particle and other properties undoable

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
https://app.asana.com/0/26224634468389/100018394466038

**Comment by huffman** [comment]
To test:

- Run https://rawgit.com/huffman/hifi/particle-undo/examples/edit.js
- Create a particle
- Edit the particle
- Select `Undo` in the `Edit` menu
- Observe that your changes to the particle were undone
- Confirm that changing and undoing other properties still works, including: position, dimensions, color

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0495ede4273a92a6ad5a16a74128e68d292e343 available at: https://gist.github.com/542d02fb55bbbb04ae86<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7368.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7368.dmg

**Comment by imgntn** [comment]
this breaks undo for normal things -- showed it to @huffman this morning

**Comment by ZappoMan** [comment]
@huffman - I'm going to close this PR, since it's over month old and we don't need to fix this before MVP

**Pull request closed without merging**
