### PR TITLE
Case 21902: System-wide independent volume controls

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.manuscript.com/f/cases/21902/Implement-System-Environment-volume-settings

Audio engine changes that add 4 new get/set functions to the Audio Scripting Interface:
- setAvatarGain() to set the master avatar gain at the server
- setInjectorGain() to set the audio injector gain at the server
- setLocalInjectorGain() to set the local injector gain at the client
- setSystemInjectorGain() to set the system-sound injector gain at the client

Gains are in dB from -100 (mute) to +30 applied in cascade with other gains (scripted volume, PAL volumes, distance attenuation).

All gains preserve HDR audio (large amplification without digital clipping) by implementing as floating-point mixing gains prior to peak-limiting. Stacking large gains (eg. +30dB scripted volume +30dB injector gain) will not clip but may result in audible dynamic-range compression/pumping.

Server-side settings are now persistent across domain changes and server resets.
Settings are currently not saved/restored across Interface sessions.

NOTE: protocol change was not required. 
An old client will lack the new functionality. 
An old server will ignore the new packet type.

The updated Audio tab has 3 volume sliders, with range of -60dB to +20dB:
- "Avatar volume" adjusts the master avatar gain
- "Environment volume" adjusts the local/server injector gains
- "System Sound volume" adjusts the gain of non-spatialized sounds (eg. Tablet clicks)

volume_controls

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18365/HighFidelity-Beta-PR15260-b5e8176.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18365/HighFidelity-Quest-Beta-PR15260-b5e8176.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18365/HighFidelity-Beta-PR15260-b5e8176.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18365/HighFidelity-Beta-Interface-PR15260-b5e8176.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18365/HighFidelity-Beta-PR15260-b5e8176.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18365/HighFidelity-Beta-Interface-PR15260-b5e8176.exe

**Comment by kencooke** [comment]
### Test Plan ###

Using both Interface and Sandbox from this PR:
1) Verify that "Avatar volume" controls the loudness of all other avatars in the domain, as before
2) Verify that "Environment volume" controls the loudness of audio injectors coming from other avatars (or server-side scripts) in the domain
3) Verify that "Environment volume" also controls the loudness of local injectors coming from client-side scripts
4) Verify that "System Sound volume" controls the loudness of non-spatialized mono or stereo local injectors, such as "Test Your Sound" button and UI click sounds.
5) Verify these settings are preserved when you close and reopen the Audio tab, and when you restart the server
6) Verify that audio otherwise works as expected

To help test, the script below will play all 6 types of injectors, by pressing keys "1" to "6".
The first two should be affected by "System Sound volume", the rest by "Environment volume."

```
var sound1 = SoundCache.getSound("http://hifi-content.s3.amazonaws.com/ken/samples/whisper.wav");       // mono
var sound2 = SoundCache.getSound("http://hifi-content.s3.amazonaws.com/ken/samples/Happy_Rock.mp3");    // stereo
var sound3 = SoundCache.getSound("http://hifi-content.s3.amazonaws.com/ken/samples/Brahms_ambiX.wav");  // ambisonic

var injector = null;

function infront() {
    return Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, { x: 0, y: 0, z: -2 }));
}

function keyPressEvent(event) {  
    var sound = null;
    switch (event.text) {
        case "0": if (injector) injector.stop(); break;
        case "1": sound = sound1; options = { localOnly: true }; break;  // system sound
        case "2": sound = sound2; options = { localOnly: true }; break;  // system sound
        case "3": sound = sound3; options = { localOnly: true }; break;
        case "4": sound = sound1; options = { localOnly: true, position: infront() }; break;
        case "5": sound = sound2; options = { localOnly: true, position: infront() }; break;
        case "6": sound = sound3; options = { localOnly: true, position: infront() }; break;
    }
    if (sound) {
        if (injector) injector.stop();
        injector = Audio.playSound(sound, options); 
    }
}

Controller.keyPressEvent.connect(keyPressEvent);
```

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18371/HighFidelity-Beta-PR15260-afe46cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18371/HighFidelity-Beta-Interface-PR15260-afe46cd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18371/HighFidelity-Beta-PR15260-afe46cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18371/HighFidelity-Quest-Beta-PR15260-afe46cd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18371/HighFidelity-Beta-PR15260-afe46cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18371/HighFidelity-Beta-Interface-PR15260-afe46cd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18398/HighFidelity-Beta-PR15260-b1d4753.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18398/HighFidelity-Quest-Beta-PR15260-b1d4753.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18398/HighFidelity-Beta-PR15260-b1d4753.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18398/HighFidelity-Beta-Interface-PR15260-b1d4753.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18398/HighFidelity-Beta-PR15260-b1d4753.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18398/HighFidelity-Beta-Interface-PR15260-b1d4753.exe

**Comment by kencooke** [comment]
Sorry @JeffClinton, recent changes in master seem to have broken the Audio tab layout. It should be fixed now, if you want to retest.

**Pull request merged**
