### PR TITLE
Zone update

### PR DESCRIPTION
**Pull request by NissimHadar**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4374/HighFidelity-Beta-PR11660-94531450bddedb6e834a57d97a49ce4aecc4eac0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4374/HighFidelity-Beta-PR11660-94531450bddedb6e834a57d97a49ce4aecc4eac0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4415/HighFidelity-Beta-PR11660-63b4d8052733d5a267eef0d97e4788c39d93e001.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4415/HighFidelity-Beta-PR11660-63b4d8052733d5a267eef0d97e4788c39d93e001.exe

**Comment by samcake** [comment]
closing for now

**Pull request closed without merging**
