### PR TITLE
Updating defaultAvatar_full.fbx to fixed version

### PR DESCRIPTION
**Pull request by murillodigital**
Update defaultAvatar bundled with installer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 946a292cfbd777e5e51e25d67fae4b9d1de7d554 available at: https://gist.github.com/2ad3a18900b036dfcd2d620a00f16a2c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7540.dmg

**Comment by OmegaHeron** [comment]
I can't see a visual change to AV when Avatar is set to a blank input - it looks same in Production as this PR unless it's such a subtle change I'm missing it or it's under the hood change.

**Comment by OmegaHeron** [comment]
I end up with two folders in Meshes
defaultAvatar containing head.fbx, body.fbx and textures
defaultAvatar_full containing defaultAvatar_full.fbx, json file and textures folder.

Is one of those cruft?

**Comment by OmegaHeron** [comment]
And it is loading defaultAvatar_full - confirmed via deletion of each folder until default AV failed to appear.

**Pull request merged**
