### PR TITLE
Enable Inspection Mode for all; change Commerce setting name

### PR DESCRIPTION
**Pull request by zfox23**
Marketplace inspection: Entities from the marketplace can be inspected through a context overlay, bringing up the marketplace page for that item.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3525/HighFidelity-Beta-PR11431-57b5a233739d8dd2af24a84572089ab94000c2fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3525/HighFidelity-Beta-PR11431-57b5a233739d8dd2af24a84572089ab94000c2fa.exe

**Comment by howard-stearns** [comment]
**Test plan for marketplace inspection:**
[Note to testers: if you find that a screen shot would help future regression testers, please make one and attach to this PR.]

**Objective**: Items downloaded from the marketplace are selectable with mouse and lasers, producing a context overlay that, when clicked, opens the marketplace page for that item.
**Background**: There is an entity picking/selection API that uses outline shader rendering to indicate the pickable item. The only thing in the system so far that uses it is the Context Overlay, which does not have a a final Javascript API yet, but which is currently hardcoded in Interface to provide the marketplace inspection capability.
**Setup**: Rez an entity from the marketplace, or use an exisiting entity that came from the marketplace and thus has a non-empty marketplaceID property. It is desirable to try marketplace items that have multiple entity pieces, such as the chess set.

**Mouse test**:
1. In desktop, move the mouse over various entities. Any that have a non-empty marketplaceID property (per setup) should highlight with a gold glow and outline. Any with an empty marketplaceID property should not highlight at all (unless some app is making other use of the selection Javascript API).
2. Right click on one without an outline. Nothing should happen (unless some app has defined additional right click behavior).
3. Right click on one with an outline. There should appear an "i" overlay. The position may vary depending on your position relative to the entity, but in any case it should be visible.
4. Click anywhere off the "i" and it should go away.
5. Repeat 3 and click on the "i" overlay. The corresponding marketplace item page should appear in the HUD (or tablet if "toolbar becomes tablet in desktop" is enabled).
6. Repeat 1-5 in HMD using the mouse. (Depending on settings, step 5 marketplace will appear in tablet instead of HUD.)

**Hand-controller test**:
1. In HMD with hand-controller, half-squeeze to get the blue seek laser.
2. Wave the seek laser over entities. Any that have a non-empty marketplaceID property (per setup) should highlight with a gold glow and outline. Any with an empty marketplaceID property should not highlight at all (unless some app is making other use of the selection Javascript API).
3. Hold the seek laser over one without an ouline. Nothing should happen.
4. Hold the seek laser over one with an outline. There should appear an "i" overlay. The position may vary depending on your position relative to the entity, but in any case it should be visible.
5. Release the trigger and the "i" should go away.
6. Repeat 4 and full-trigger on the "i" overlay. The corresponding marketplace item page should appear in the tablet (or HUD if "toolbar becomes tablet in HMD" is not enabled).

**Comment by cain-kilgore** [comment]
Hey @zfox23: Is this ready for normal QA from us non-Discovery guys?

**Comment by zfox23** [comment]
@cain-kilgore Yes

**Comment by zfox23** [comment]
build this please

**Comment by zfox23** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3537/HighFidelity-Beta-PR11431-57b5a233739d8dd2af24a84572089ab94000c2fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3537/HighFidelity-Beta-PR11431-57b5a233739d8dd2af24a84572089ab94000c2fa.exe

**Comment by changxc** [comment]
Please do not merge yet. 

Proposed design tweak (pending approval) 
- Outline Color: make it 50% of current thickness and 90% of opacue
- Filing: no filing 
- HMD: when full-trigger directly on the object, the (i) and outline should not show up 
- desktop: the behavior change to right click bring up (i) and highlight the object (current behavior is that mouse hover over will show outline, this needs to be changed)

Note that the last two will change test plan steps as well

**Comment by cain-kilgore** [comment]
Hey @changxc: I was just about to test this. Will I hold off?

**Comment by changxc** [comment]
I do not want to hold off the process. Please go ahead with testing the current PR (up to before my comment). If we manage to get the new design tweaks in, we can test again.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3562/HighFidelity-Beta-PR11431-e3f2e70bca4b728595e874d9882d5bb67f9d2f27.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3562/HighFidelity-Beta-PR11431-e3f2e70bca4b728595e874d9882d5bb67f9d2f27.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3566/HighFidelity-Beta-PR11431-0eafdeab14267c078a4944b9d6cc2e7fa249342b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3566/HighFidelity-Beta-PR11431-0eafdeab14267c078a4944b9d6cc2e7fa249342b.exe

**Comment by zfox23** [comment]
OK, this is now QA ready (once the build comes out) :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3570/HighFidelity-Beta-PR11431-702a4e9adeeff9fa0f6e4d4c0e601f1324fe83fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3570/HighFidelity-Beta-PR11431-702a4e9adeeff9fa0f6e4d4c0e601f1324fe83fb.exe

**Comment by Nex-Pro** [comment]
T E S T I N G this

**Comment by Nex-Pro** [comment]
Tested on Win10

## FAIL

Mouse test:

In desktop, move the mouse over various entities. Any that have a non-empty marketplaceID property (per setup) should NOT highlight with an orange outline. Any with an empty marketplaceID property should also not highlight at all (unless some app is making other use of the selection Javascript API).
Right-click on an entity with an empty marketplaceID property. Nothing should happen (unless some app has defined additional right click behavior).
Right-click on an entity with an non-empty marketplaceID property. There should appear an "i" overlay. The position may vary depending on your position relative to the entity, but in any case it should be visible and not completely occluding the selected entity.
Left-click anywhere off the "i" and it should go away.
Repeat step 3 and left-click on the "i" overlay. The corresponding marketplace item page should appear in the HUD (or tablet if "toolbar becomes tablet in desktop" is enabled).
Repeat 1-5 in HMD using the mouse. (Depending on settings, step 5 marketplace will appear in tablet instead of HUD.)
Hand-controller test:

In HMD with hand-controller, half-squeeze the primary trigger to get the blue seek laser.

Wave the seek laser over entities. Any that have a non-empty marketplaceID property (per setup) should highlight with an orange outline. **FAIL** Does not work for the chess set ( chess set works in desktop ) I think it might be because it is grabbable but non-dynamic.

Any with an empty marketplaceID property should not highlight at all (unless some app is making other use of the selection Javascript API). **SUCCESS**

Hold the seek laser over an entity with an empty marketplaceID property for 1 second. Nothing should happen. **SUCCESS**

Hold the seek laser over an entity with an non-empty marketplaceID property for 1 second. There should appear an "i" overlay after 0.5 seconds have elapsed but not sooner. **SUCCESS**
The position may vary depending on your position relative to the entity, but in any case it should be visible and not completely occluding the selected entity. **FAIL** Too many ways for the 'i' to be out of the view of the avatar see images.

hifi-snap-by--on-2017-09-23_00-52-37
hifi-snap-by--on-2017-09-23_00-46-00

hifi-snap-by--on-2017-09-23_00-44-22

hifi-snap-by--on-2017-09-23_00-44-05
hifi-snap-by--on-2017-09-23_00-44-33

hifi-snap-by--on-2017-09-23_00-44-33
hifi-snap-by--on-2017-09-23_00-47-33

Release the trigger and the "i" should go away. **SUCCESS**

Repeat step 4 to reveal the "i' i overlay and full-trigger on the "i" overlay. The corresponding marketplace item page should appear in the tablet (or HUD if "toolbar becomes tablet in HMD" is not enabled). **SUCCESS**

Full-trigger quickly on an entity with a non-empty marketplaceID property. The outline may briefly appear but disappear as soon as the trigger is fully depressed. The "i" icon should not appear. **SUCCESS**


Other issues seen.  The 'i' can appear inside the object and therefore be unclickable.
To repro get the game table from market. When you try to click on the 'i'
you will grab the table.

Ents set to be grabbable but non-dynamic don't respond to the lasers.

Really easy to get the 'i' in a place where it can't be seen.

Doesn't play well with 3rd person view.

Can walk towards the 'i' and go right past it. 

'i' can sometimes appear behind the avatar can't see it until turned around or walked backwards.

'i' can completely obscure the item.

**Comment by changxc** [comment]
Wave the seek laser over entities. Any that have a non-empty marketplaceID property (per setup) should highlight with an orange outline. FAIL Does not work for the chess set ( chess set works in desktop ) I think it might be because it is grabbable but non-dynamic.


**The fail is not related to our inspection PR, but a laser bug (laser go thru solid chess sets board)
https://highfidelity.fogbugz.com/f/cases/7857/Hand-controller-laser-doesn-t-intersect-with-certain-entities**

**Comment by zfox23** [comment]
Thanks for your QA, @nex-pro. Based on your feedback, I'm going to call this a QA pass and merge it.

The bug regarding not being able to select the chess set is because of this known bug: https://highfidelity.fogbugz.com/f/cases/7857/Hand-controller-laser-doesn-t-intersect-with-certain-entities

The issues you're seeing with the positioning of the context overlay definitely need to be solved, but the positioning being annoying is not enough to fail this particular PR. We will iterate on the overlay positioning in the future.

**Pull request merged**
