### PR TITLE
Case 21888: Revert changes that impacted animation performance

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21888/Fix-animation-performance-for-82

https://github.com/highfidelity/hifi/pull/15250

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18339/HighFidelity-Beta-PR15251-c1c45d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18339/HighFidelity-Beta-Interface-PR15251-c1c45d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18339/HighFidelity-Beta-PR15251-c1c45d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18339/HighFidelity-Beta-Interface-PR15251-c1c45d8.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18341/HighFidelity-Beta-PR15251-c1c45d8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18341/HighFidelity-Quest-Beta-PR15251-c1c45d8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18341/HighFidelity-Beta-PR15251-c1c45d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18341/HighFidelity-Beta-Interface-PR15251-c1c45d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18341/HighFidelity-Beta-PR15251-c1c45d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18341/HighFidelity-Beta-Interface-PR15251-c1c45d8.exe

**Pull request merged**
