### PR TITLE
switch various status to use thread safe atomics

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 66a2b38f50ae9362aa69919f7469473bf97e23ee available at: https://gist.github.com/267fef19513bd362311a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 14a6e1fb6b043d27a1f2e3ff39b76525bf2da671 available at: https://gist.github.com/267fef19513bd362311a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 33110eda30e2e0eb91192b91a31f79e4dff1df98 available at: https://gist.github.com/267fef19513bd362311a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8bfb368a61021975ffd1d4fcfae06aa5049075a0 available at: https://gist.github.com/267fef19513bd362311a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.dmg

**Comment by Atlante45** [comment]
All those statics benefit from the zero-initialization so you don't really need to assign 0 to them, for the rest, you can use `Atomic var = ATOMIC_VAR_INIT(val);`

**Comment by hifi-gustavo** [comment]
Build console output for commit: da651ac47555c0aa31c48e7406cedf45a61a54c5 available at: https://gist.github.com/267fef19513bd362311a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6378.dmg

**Pull request merged**
