### PR TITLE
add photo replacement for hyperlinked places

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0df52e8609c1e5559f466e74695e09a59b65356 available at: https://gist.github.com/def8842e4ac760e87986<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b84eabd18e2530ab369c800deb4928212d63cbb available at: https://gist.github.com/def8842e4ac760e87986<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ff33922716991221febe5f43235630f8d6314421 available at: https://gist.github.com/def8842e4ac760e87986<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5213.dmg

**Comment by jherico** [comment]
Tested on my desktop.

**Pull request merged**
