### PR TITLE
Beta Release 19 - Includes up to Developer Release 5335

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* HandControllerGrab and web entity input integration
* Fix address bar being opened when moving between places on same domain
* Center HMD Hud after teleport
* Snapshot of Snapshot-Discovery to master
  * There is now a snapshot button in the toolbar
* Fix default skybox behavior
* New Editor for UserData JSON
https://cloud.githubusercontent.com/assets/843228/17876459/2c716e28-688f-11e6-8cef-aa1a2fa540fd.PNG
* Speed up spherical harmonics calculation with minimal error
* Clicking the marketplace icon while wearing an HMD with hand controllers will spawn the marketplace web site within a handheld tablet, instead of on the overlay UI sphere. When not actively held, the marketplace tablet should follow the user as they navigate the world by teleporting or using the arrow keys.  
* Fix vive crash in AMD driver
* Include default scripts instead of loading them
* Raised max iterations for IK to 16 from 4
* Render collision geometry
* Improved web entity rendering
* Fix Screen Space ambient occlusion which was broken since a while
* Include the codec name in the agent avatar audio stream
* (AMD) OpenGL Fixes
* Silence address bar log warning
* Custom OpenGL context creation
* No more delete with backspace in edit.js
* Bug fix for click events received by entity scripts
* Add shareable address from default name, leverage for steam join/invite
* When trigger is pulled, snap search beam to correct length instead of animating
* Support for fbx2016 format
* Restore onNewViewRequested
* Workaround for Script.resolvePath() bug
* Skybox fixes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 02afa460ff9c93cdcac9308f8fe7d0d047f76a40 available at: https://gist.github.com/bb75f125e4f268f2c64872bd7b40f65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8558-02afa46.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8558-02afa46.dmg

**Comment by nbq** [comment]
testing now

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |59 |61 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |3198 |2696 |3469
**GPU Buffer Count**: |436 |209 |319
**CPU Memory Usage**: |70332416 |50900992 |68382720
**GPU Memory Usage**: |15282176 |5165056 |15085568
**CPU Texture Count**: |265 |271 |315
**GPU Texture Count**: |916 |903 |870
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |510264348 |556073272 |408310344
**GPU Texture Memory Usage**: |322605171 |171816770 |583622451
**GPU Virtual Memory Usage**: |448376779|297588378|709394059
**Triangle Count**: |339141 |56025 |200728
**Triangle Rate**: |19949470 |3501562 |11807529
**API Drawcall Count**: |106 |54 |106
**Drawcall Count**: |101 |54 |106
**Drawcall Rate**: |5941 |3375 |6235
**State Changes Texture Count**:|97 |67 |175
**Pipeline Count**: |25 |25 |35
**Item Opaques**: |128 |42 |78
**Item Translucents**: |16 |7 |24
**Item Lights**: |20 |16 |7
**Timing Opaques**: |400 |252 |293
**Timing Translucents**: |33 |21 |80
**Timing Lighting**: |109 |114 |141
**Render Frame**: |1320 |1444 |1314


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Success
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Sounds were NOT present however not sure if this is an error or if they are not loaded in the env.
**Test 4**|Launch firework, make sure others can hear thr sound|NA
**Test 5**|Retest the kick function|NA
**Test 6**|Switch avatar and make sure it does not crash|Success
**Test 7**|Test group functions|NA
**Test 8**|Retest the kick function|NA
**Test 9**|Ensure that you can distance grab|Success
**Test 10**|Being up and edit an objects with hand controllers|Success
**Test 11**|Modify a models userdata and make sure it works|Success

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

This will not be an exhaustive test - part of life in sub-tropics = tropical storms and hurricanes.  Of which one is making my net and power unhappy at the moment.

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Domain Stats - 1600x900 maximized window - vsync unlocked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |221 |213 |221
**Present Rate**: |221 |279 |359
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4008 |8186 |4791
**GPU Buffer Count**: |1557 |3632 |1357
**CPU Memory Usage**: |65798144 |100958208 |97054720
**GPU Memory Usage**: |52957184 |75702272 |54648832
**CPU Texture Count**: |302 |396 |445
**GPU Texture Count**: |627 |1047 |1402
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |72488884 |130713368 |216347032
**GPU Texture Memory Usage**: |1115110415 |2284149428 |1420999962
**GPU Virtual Memory Usage**: |1205560483|2374599496|1511450030
**Triangle Count**: |448933 |1261762 |1032220
**Triangle Rate**: |149644333 |315440500 |344073333
**API Drawcall Count**: |222 |621 |364
**Drawcall Count**: |275 |666 |1288
**Drawcall Rate**: |91666 |166500 |429333
**State Changes Texture Count**:|219 |548 |565
**Pipeline Count**: |33 |46 |64
**Item Opaques**: |290 |589 |320
**Item Translucents**: |31 |69 |75
**Item Lights**: |19 |79 |34
**Timing Opaques**: |779 |1720 |910
**Timing Translucents**: |37 |85 |159
**Timing Lighting**: |122 |203 |180
**Render Frame**: |1810 |3476 |2419

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75|75 |75
**Present Rate**: |75 |74 |75
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4401 |7218 |4825
**GPU Buffer Count**: |1666 |1495 |1504
**CPU Memory Usage**: |90189824 |101642240 |97042432
**GPU Memory Usage**: |62148608 |34717696 |64286720
**CPU Texture Count**: |336 |276 |444
**GPU Texture Count**: |1551 |2220 |2320
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |80969716 |150407064 |182628760
**GPU Texture Memory Usage**: |1335852570 |610511463 |1477447443
**GPU Virtual Memory Usage**: |1586201590|860860483|1727796463
**Triangle Count**: |1679501 |1959078 |1735047
**Triangle Rate**: |129192384 |150698307 |133465153
**API Drawcall Count**: |264 |488 |360
**Drawcall Count**: |725 |959 |2545
**Drawcall Rate**: |55769 |73769 |195769
**State Changes Texture Count**:|291 |330 |475
**Pipeline Count**: |52 |75 |67
**Item Opaques**: |273 |649 |359
**Item Translucents**: |36 |163 |81
**Item Lights**: |18 |82 |33
**Timing Opaques**: |760 |1947 |1176
**Timing Translucents**: |75 |294 |216
**Timing Lighting**: |127 |301 |203
**Render Frame**: |2012 |4256 |2897

**Comment by howard-stearns** [comment]
I've confirmed that the suggestions/feed/snapshots all work as expected, in desktop and HMD.

However, my **HMD frame rate is in the 50's in home, and only in the 20's in dev-playa.** (Using Vive on desktop cyberpowerpc).

**Comment by howard-stearns** [comment]
In beta release 5312 I get 90 in playa (not dev-playa), and highly variable in home: 50-80's.

**Comment by howard-stearns** [comment]
Performance ok now:

I'm now getting 90 in dev-playa. Chris said he removed some stuff, so maybe that was it.

Meanwhile, it turns out that I still had the dressing-room lights on in home. Good performance with those turned off. (Oddly, I can't seem to turn the dressing room lights back on now, but I guess that's a content problem not an Interface issue.)

**Comment by Nex-Pro** [comment]
Nearly through testing.

**Comment by Nex-Pro** [comment]
**PR #8558**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used

**Starting conditions:**

        Fresh install of interface and sandbox.
        Requested reset of settings prior to launch.
        Steam VR renderTargetMultiplier at default setting.
        Two PCs available for tests requiring more than one avatar.

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS
**Additional Test Results + Observations**:

### DOMAIN STATS

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |3836 |8228 |4063
**GPU Buffer Count**: |9395 |11392 |9348
**CPU Memory Usage**: |57257984 |117387264 |81653760
**GPU Memory Usage**: |77631488 |101212160 |70840320
**CPU Texture Count**: |284 |416 |361
**GPU Texture Count**: |436 |960 |748
**GPU Transfer Count**: |0 |11 |0
**CPU Texture Memory Usage**: |87918396 |518503144 |468917432
**GPU Texture Memory Usage**: |1075291868 |1910395430 |919654748
**GPU Virtual Memory Usage**: |1444882616|2279986178|1289245496
**Triangle Count**: |1805634 |2750556 |1466320
**Triangle Rate**: |180563400 |250050545 |146632000
**API Drawcall Count**: |266 |693 |278
**Drawcall Count**: |626 |1456 |2395
**Drawcall Rate**: |62600 |132363 |239500
**State Changes Texture Count**:|296 |392 |411
**Pipeline Count**: |38 |39 |58
**Item Opaques**: |305 |868 |304
**Item Translucents**: |34 |71 |74
**Item Lights**: |22 |83 |34
**Timing Opaques**: |991 |2511 |950
**Timing Translucents**: |27 |81 |135
**Timing Lighting**: |63 |198 |99
**Render Frame**: |1707 |4293 |1954

#### HMD Eye tests:

**EYE-01 Test Result**: SUCCESS
**EYE-02 Test Result**: SUCCESS
**EYE-03 Test Result**: SUCCESS
**EYE-04 Test Result**: SUCCESS
**EYE-05 Test Result**: SUCCESS
**EYE-06 Test Result**: SUCCESS
**EYE-07 Test Result**: SUCCESS

**Additional Test Results + Observations**: 

Had a number of occasions where my frame rate at localhost dropped as low as 40fps in HMD.
Problems with hand controllers with grabbed objects moving negative to the hand or moving to the wrist. I have mentioned this before.
Occasionally after a few moments some objects move off in the distance and cannot be pulled back other than by the other controller.
On more than one occasion the grabbed object suddenly moved rapidly downwards taking the beam with it despite no hand movement being made.
We both saw equipped items becoming invisble to an observer.

Whilst in my sandbox MichelleLeckrone activated marketplace. When the no permissions alert was displayed behind her it was not possible to dismiss it.
Also I was watching on screen-share we both observed that the laser became locked to the get button on the market tablet. This behaviour was consistent and repeatable.

There is still the issue with the snapshots where on first click of the icon it throws up a windows file picker that cannot be seen whilst in HMD. This had the effect of making interface appear to be frozen. This should be done in the HMD.


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Fan switch is unreliable.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Used dev-demo for this test: **Success**
**Test 4**|Launch firework, make sure others can hear thr sound|**Success**
**Test 5**|Retest the kick function|
**Test 6**|Switch avatar and make sure it does not crash|**Success**
**Test 7**|Test group functions|untested
**Test 8**|Retest the kick function|Untested
**Test 9**|Enrure that you can distance grab|I 'E N R U R E D' that distance grab basically works. **Success**
**Test 10**|Being up and edit an objects with hand controllers| This makes no sense.
**Test 11**|Modify a models userdata and make sure it works| code and tree view works. Expand and collapse work. Modify data in code view with save works. Changes persist. **Success**

#### Group function testing to be concluded later.

**Comment by nbq** [comment]
This test was performed on a MacBook Pro Late 2013 Model with a GeForce GT 750M 2048MB VRam machine.

## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: For an older 2013 MBP with GeForce GT 750M it performed ok except for the harmonic ocillator which I will include a screen shot of

nooscillator

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |10 |13 |18
**Present Rate**: |10 |12 |18
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4505 |3199 |3699
**GPU Buffer Count**: |928 |654 |692
**CPU Memory Usage**: |90689536 |76754944 |77361152
**GPU Memory Usage**: |49590272 |39260160 |37662720
**CPU Texture Count**: |185 |178 |324
**GPU Texture Count**: |1074 |1098 |1227
**GPU Transfer Count**: |0 |0 |1
**CPU Texture Memory Usage**: |87185980 |312644504 |550533672
**GPU Texture Memory Usage**: |480539529 |809845960 |476322578
**GPU Virtual Memory Usage**: |756485677|1085792108|777434544
**Triangle Count**: |341169 |205533 |96371
**Triangle Rate**: |4110469 |2635038 |1927420
**API Drawcall Count**: |80 |118 |96
**Drawcall Count**: |82 |118 |96
**Drawcall Rate**: |987 |1512 |1920
**State Changes Texture Count**:|96 |142 |170
**Pipeline Count**: |15 |46 |35
**Item Opaques**: |96 |93 |75
**Item Translucents**: |8 |3 |32
**Item Lights**: |18 |24 |14
**Timing Opaques**: |574 |610 |805
**Timing Translucents**: |95 |163 |279
**Timing Lighting**: |48 |63 |62
**Render Frame**: |1482 |1773 |

**Comment by Nex-Pro** [comment]
@howard-stearns I read what you wrote about the changing room lights and went back in just to test that.  With the lights off  and using the thumb turn on the right controller it is all smooth. With the lights on it is horribly jerky. Can a handfull of lights really mess this up so much ? I'm using a gtx 1070.

**Comment by howard-stearns** [comment]
Yes, it can make that much of a difference. @samcake is working on it, but it is a thorny problem.

**Comment by ZappoMan** [comment]
Tested on my iMac - performance is consistent with current Mac Beta 5312 - Pass

**Comment by Nex-Pro** [comment]
@howard-stearns 

Kick function observations:

Works, however it is possible for an avatar to kick the sandbox owner if kick perms are granted.


Group functions test observations:

**FAIL**

All tests were repeated both ways with two geographically separated sandboxes.

Group permissions are comprehensively broken.

We could not allow or deny sandbox access via the group settings.

We tried all combinations that made sense. ( with and without logged-in checked and combinations that included friends ) 

The friends checkbox somehow initiated a sequence where the non-local avatar would continuously connect and disconnect at regular intervals. ( 5 to 10 seconds ).

Permissions for and permissions denied failed whether the connect checkboxes were clicked or not. ( no effect )

After every checkbox change or group addition or removal the 'Save and restart' button was clicked and we both observed the server restarting ( we used skype screensharing ).

***It may be that we have misunderstood the intent of the group perms but I feel we approached this in the manner of a user seeing the group settings for the first time.***

In addition 'undefined' appears in the ranks area of the group perms. See image.
8558groups

**Comment by Nex-Pro** [comment]
@ZappoMan ^

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8754d522f342e3c2fe5138027e11fb906ef9dbe1 available at: https://gist.github.com/bb75f125e4f268f2c64872bd7b40f65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8558-8754d52.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8558-8754d52.dmg

**Comment by Nex-Pro** [comment]
@ZappoMan  @howard-stearns  Apologies I had overlooked hooking up the domain ID. The group functions are in fact ok. I won't make that mistake again.

**Pull request merged**
