### PR TITLE
9461 Keyboard for create appear then disappears immediately (HMD)

### PR DESCRIPTION
**Pull request by ElderOrb**
*** Test plan ***

1. Switch to VR
2. Go to 'Create' 
3. Ensure clicking 'Filter' input field and 'Search Radius' combo box in 'List' shows virtual keyboard without any issues (could show & hide before the fix)
4. Ensure clicking 'Major grid size' and 'Minor grid size' combo boxes in 'Grid' shows virtual keyboard without any issues. (could show & hide before the fix)

Bonus: Please check as much different keyboards in different places as possible. All of them should behave in the same way - should appear on clicking input field.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5329/HighFidelity-Beta-PR11912-48b50e33dda8d0e7dde9b03991dbd1f2ee33b730.dmg

**Comment by marko8904** [comment]
build this please

**Comment by Nex-Pro** [comment]
@ElderOrb Is this addressing the bug report I made ? If so I'd like to check this one.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5330/HighFidelity-Beta-PR11912-48b50e33dda8d0e7dde9b03991dbd1f2ee33b730.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5330/HighFidelity-Beta-PR11912-48b50e33dda8d0e7dde9b03991dbd1f2ee33b730.dmg

**Comment by tapalisa** [comment]
Fixes this bug

**Comment by Nex-Pro** [comment]
Testing Win10 and Vive.

**Comment by Nex-Pro** [comment]
Tester: Piper.Peppercorn

###Test: PR #11912

System information.
CPU: Intel i7 4.0 ghz.
RAM: 16gb
GPU: Nvidia GTX1070 8gb
HMD: HTC Vive.
Controllers: Vive hand controllers.
Audio: USB headset.

Testing conditions:

Fresh installation of this build.(any previous installation completely removed)#


I checked the following places where the QML keyboard should be raised and persist.
In each case the keyboard behaves correctly. 
In cases where there were other keyboard related issues I compared to latest dev build where they also exist.

### MENU Items

EDIT -> Running scripts: **SUCCESS**

EDIT -> Open and run script from url: **SUCCESS**

EDIT -> Asset browser -> rename: **SUCCESS**

EDIT -> Import entities from url: **SUCCESS**

EDIT -> Entity list: **FAIL** ***not due to this pr*** Ent list does not open in HMD or desktop.


AVATAR -> Attachments: **SUCCESS**

AVATAR -> Bookmark Avatar: **SUCCESS**

NAVIGATE -> Bookmark location: **SUCCESS**

SETTINGS -> General: **SUCCESS** However there are a plethora of usablity problems when using this dialog with the QML keyboard.
    Namely that the input fields are often covered by the keyboard. See images. ( this is not due to this PR )

Images.
***Input field hidden by keyboard***
hifi-snap-by-piper-peppercorn-on-2017-12-04_19-57-05

***Input field hidden by 'cancel' button***
hifi-snap-by-piper-peppercorn-on-2017-12-04_19-57-49

***Camera yaw speed input field hidden by 'cancel' button***
hifi-snap-by-piper-peppercorn-on-2017-12-04_19-59-56
***Same field after dismissing keyboard***
![hifi-snap-by-piper-peppercorn-on-2017-12-04_19-59-50](https://user-images.githubusercontent.com/7314019/33574928-dc453dd8-d932-11e7-8cc7-dab6b1ca1dce.jpg

SETTINGS -> Avatar: **SUCCESS** Problems as above.


### Tablet Icons

GOTO type an address: **SUCCESS**

CREATE grid: **SUCCESS**

CREATE Entity list: **SUCCESS**

CREATE Properties **SUCCESS** Tested most of the available input fields.

There remain a number of useability issues with the keyboard when setting values in the properties pane.
Mainly that when a user clicks on the next input box, say going from dimensions X to dimensions Y  the the keyboard is dismissed and the properties pane instantly scrolls to the top. Now the user has to scroll all the way down again in order to locate where they were working.
This can be mitigated by using the 'collapse keyboard' button. IMO this is not intuitive and leads to user frustration.
I have never had a conversation with another user where they state that they enjoy using the properties pane in HMD mode.

### PASS

@ElderOrb  Thanks for fixing the disappearing keyboard issue.

**Pull request merged**
