### PR TITLE
allow splitting of edit or add entity packets across multiple edit packets when property list is larger than MTU

### PR DESCRIPTION
**Pull request by ZappoMan**
Fixes this bug - https://highfidelity.fogbugz.com/f/cases/8873/Sufficiently-large-entities-fail-to-make-it-to-the-entity-server

Test Plan:
- Test edit/add entity editing thoroughly
- Follow repro steps in bug report verify you can import jsons with combined properties larger than MTU, but each property smaller than ~1100 bytes. (larger than 1100 byte properties are not supported)

Here's a possible json you could test with...
```
{
    "Entities": [
      {
        "clientOnly": 0,
        "created": "2017-11-04T01:16:45Z",
        "description": "description-123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890",
        "dimensions": {
          "x": 2.4574809074401855,
          "y": 1.9560555219650269,
          "z": 3.6256515979766846
        },
        "id": "{6d1c790b-af87-4cd0-b6a7-52bb3ead0a04}",
        "lastEdited": 1509758286686279,
        "lastEditedBy": "{0cbb3ed7-6b69-4e53-aa70-543413d74e6e}",
        "marketplaceID": "60f54c7e-7291-46a6-88ff-e1cc139da3eb",
        "modelURL": "http://mpassets.highfidelity.com/60f54c7e-7291-46a6-88ff-e1cc139da3eb-v1/Bed.fbx",
        "name": "name-12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789",
        "owningAvatarID": "{00000000-0000-0000-0000-000000000000}",
        "queryAACube": {
          "scale": 4.796948432922363,
          "x": -2.3984742164611816,
          "y": -2.3984742164611816,
          "z": -2.3984742164611816
        },
        "rotation": {
          "w": 1,
          "x": -1.52587890625e-05,
          "y": -1.52587890625e-05,
          "z": -1.52587890625e-05
        },
        "shapeType": "static-mesh",
        "type": "Model",
        "userData": "user-data-123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"
      }
    ],
    "Version": 79
}
```

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4686/HighFidelity-Beta-PR11749-d4b4d188ed28bdf6875dd66ef34598aa0ad2005b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4686/HighFidelity-Beta-PR11749-d4b4d188ed28bdf6875dd66ef34598aa0ad2005b.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Test edit/add entity editing thoroughly | Pass
Follow repro steps in bug report verify you can import jsons with combined properties larger than MTU, but each property smaller than ~1100 bytes. (larger than 1100 byte properties are not supported) | Pass

Looks good to me. Tried creating a few entities with large byte properties and they appeared, along with their info on other Interfaces too.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by Nex-Pro** [comment]
@ZappoMan I read the repro and notes in the fogbugz on this. Users are going to cram the user data with a ton of stuff, guaranteed.

**Comment by birarda** [comment]
Are there cases where we won't want this to be the behaviour? Where the user will expect all of the properties they pass to add to land at the same time?

Does certification require N properties to pass and will it fail if the add packet only includes M of the N required properties?

**Comment by zfox23** [comment]
I think @birarda has a point...

If `processEditPacketData()` gets called on the first add packet, and the packet only contains _some_ of the certified properties, the add will fail.

**Comment by ZappoMan** [comment]
@zfox23 - this has always been the case with entity properties... you can't assume that properties will be atomic...

**Comment by ZappoMan** [comment]
After discussing with @howard-stearns I will look into the possibility of making AddEntity atomic in it's property sets

**Pull request merged**
