### PR TITLE
Build 49.3 Hotfix: Fix crash on double tap of stylus

### PR DESCRIPTION
**Pull request by cozza13**
Build 49.3 Hotfix: Fix crash on double tap of Stylus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2111/HighFidelity-Beta-PR11082-ec4023794f54a11bf1a0cd04405de2137b8df231.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2111/HighFidelity-Beta-PR11082-ec4023794f54a11bf1a0cd04405de2137b8df231.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2120/HighFidelity-Beta-PR11082-160756145b2996cfea5570cf334814582350736c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2120/HighFidelity-Beta-PR11082-160756145b2996cfea5570cf334814582350736c.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2139/HighFidelity-Beta-PR11082-43ec898c874557b28d72eb61366ac7c9d1563552.exe

**Comment by marko8904** [comment]
failed on Mac due to github outage.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2151/HighFidelity-Beta-PR11082-43ec898c874557b28d72eb61366ac7c9d1563552.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2151/HighFidelity-Beta-PR11082-43ec898c874557b28d72eb61366ac7c9d1563552.exe

**Pull request merged**
