### PR TITLE
TEAM TEACHING - merge from master

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 763e6dd97b4cb957980ef633548f97c0638abc50 available at: https://gist.github.com/53afc514f7f23f13ab21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63c19f7c111ae36b74be771929dfc2a85b206806 available at: https://gist.github.com/53afc514f7f23f13ab21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63c19f7c111ae36b74be771929dfc2a85b206806 available at: https://gist.github.com/53afc514f7f23f13ab21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4984.dmg

**Pull request merged**
