### PR TITLE
Case 19682: Disable interstitial on android

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19682/Disable-interstitial-on-android

Test plan:
- Go to a domain on Android
- You should be able to move right away.  The interstitial page shouldn't come up.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14540/HighFidelity-Beta-PR14311-8633dc0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14540/HighFidelity-Beta-PR14311-8633dc0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14540/HighFidelity-Beta-Interface-PR14311-8633dc0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14540/HighFidelity-Beta-PR14311-8633dc0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14540/HighFidelity-Beta-Interface-PR14311-8633dc0.exe

**Comment by qlimnavarro** [comment]
Tested on Android. Interstitial no longer appears.

**Pull request merged**
