### PR TITLE
add OverlayWebWindow resized, moved, and closed signals

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

WebWindow already has these signals / events. Add the same for OverlayWebWindow.

The zip file attached has two scripts:
- testOverlayWebWindow.js
- testWebWindow.js

Each opens a window. When you move, resize, or close the window messages reflecting these events should be written to the program log.

[Test Scripts.zip](https://github.com/highfidelity/hifi/files/395021/Test.Scripts.zip)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 31ac7a2812dc6775d7a4596cfb30283a21af6329 available at: https://gist.github.com/89a26c8d17e8ae919272ef00294c2797<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8345-31ac7a2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8345-31ac7a2.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
@cozza13 can you trigger a re-build thanks!

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 31ac7a2812dc6775d7a4596cfb30283a21af6329 available at: https://gist.github.com/89a26c8d17e8ae919272ef00294c2797<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8345-31ac7a2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8345-31ac7a2.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: SUCCESS
**Additional Test Results + Observations**:  Successfully ran both scripts locally and upon resize and close the activity was immediately logged in the log.

**Pull request merged**
