### PR TITLE
Add joint rotation offset to the avatar multi-sphere shapes

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR takes into account the joint rotation offsets when computing the k-dops that are later used for extracting the multi-sphere detailed shaped. 
https://highfidelity.manuscript.com/f/cases/21987/Detailed-multi-spheres-appear-rotated-in-some-avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18487/HighFidelity-Beta-PR15296-a7c36c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18487/HighFidelity-Beta-Interface-PR15296-a7c36c9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18487/HighFidelity-Beta-PR15296-a7c36c9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18487/HighFidelity-Quest-Beta-PR15296-a7c36c9.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18487/HighFidelity-Beta-PR15296-a7c36c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18487/HighFidelity-Beta-Interface-PR15296-a7c36c9.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
1.- Wear this avatar: https://hifi-content.s3.us-west-1.amazonaws.com/davidback/avatars/NotFlushWithGround/Bandit/avatar.fst
2.- Activate Developer/Avatar/Show detailed collision. Detailed collisions should appear correctly positioned and rotated

**Pull request merged**
