### PR TITLE
FB16560 Active  Avatar App - New Bookmarks Not correctly Starred

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.manuscript.com/f/cases/16560/Avatar-App-New-Bookmarks-Not-correctly-Starred

*** Test plan *** 

1. Select avatar with some wearables
2. Adjust wearables, save changes
3. Save bookmark under new name
4. Ensure newly-saved bookmark is the first in list of bookmarks, it has selection rectangle and star is yellow. 
5. Repeat 1-4 several times for different avatars making different adjustments of wearables.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11329/HighFidelity-Beta-PR13612-55d76a8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11329/HighFidelity-Beta-PR13612-55d76a8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11329/HighFidelity-Beta-Interface-PR13612-55d76a8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11329/HighFidelity-Beta-PR13612-55d76a8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11329/HighFidelity-Beta-Interface-PR13612-55d76a8.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Bookmarks tested are now correctly applied when saved, including when wearables were rotated.

**Pull request merged**
