### PR TITLE
Threaded present

### PR DESCRIPTION
**Pull request by jherico**
Move the buffer swapping from the main application thread to a dedicated thread devoted only to keeping the screen updated.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc3a68d3bf7a477afca21a4f011c99a00fc36f2f available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e04ad21d5a5eada923210404ed50f2e8225fdbda available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 274d73fd8995cb1d4e3008c01cfb1724b32d81f1 available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bbd4f09fd614f11cf5274219ab5548af314328d available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 01c54e701f0bd5cdee1f51d44c95e73409bf75ab available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 739d241b424ce1c96dc9e63cc8dba0ae3fc8d3a0 available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 90ef7c6bf763d77be56ced44f4325a22ef673a93 available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 90ef7c6bf763d77be56ced44f4325a22ef673a93 available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Comment by howard-stearns** [comment]
What do Render Rate and Present Rate signify?

**Comment by ZappoMan** [comment]
@howard-stearns - 
"present rate" - is the hz for actually "blitting" to the display...
"render rate" - is the hz for the generation from the geometry (batch) to the frame buffer

Recall our conversation on threading from a couple weeks ago.

**Comment by howard-stearns** [comment]
So, on Mac debug build, e.g., shouldn't I see a Present Rate of 60Hz? I'm seeing an unstable range from 120-130.
Meanwhile my Render Rate = Simrate= 18fps in simple scene. Expected?

**Comment by ZappoMan** [comment]
@howard-stearns - I think there is something wrong with the "present rate" calculations in desktop mode...

**Comment by howard-stearns** [comment]
Could I get an expert opinion on whether https://github.com/highfidelity/hifi/pull/6541 is consistent with this? i.e., the idea of a target frame rate defined by the DisplayPlugin which I guess would be "render rate", and a boolean (called isVSynchronized in that pr) for whether it's meaningful to expect the (render rate?) to reach target.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11917ca501226493a83e26257d82725b0c3dc086 available at: https://gist.github.com/52422fc6382b09bfb34b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6548.dmg

**Pull request merged**
