### PR TITLE
[WIP] - Numeric pad prototyping

### PR DESCRIPTION
**Pull request by ElderOrb**
This PR is ongoing work on numeric pad prototyping. No QA attention is needed atm.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6543/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6543/HighFidelity-Beta-PR12237-72d9c862c5c2860e8317628b9556e4e4345960d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6543/HighFidelity-Beta-PR12237-72d9c862c5c2860e8317628b9556e4e4345960d9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6546/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6546/HighFidelity-Beta-PR12237-84c2d2492111752c0f9b927e5b76254f9b5080da.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6546/HighFidelity-Beta-PR12237-84c2d2492111752c0f9b927e5b76254f9b5080da.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6549/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6549/HighFidelity-Beta-PR12237-8eee01913ab7da0bae8f03f751d68a956b714a3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6549/HighFidelity-Beta-PR12237-8eee01913ab7da0bae8f03f751d68a956b714a3d.exe

**Comment by changxc** [comment]
Hi @ElderOrb 

Thank you so much for making great progress! Alan and I come up with some feedback from design perspective: 
- in HMD, when I press trigger on circle to draw the link, it works great. If I swipe or drag, it does not work as great. Could we do some more tuning? if it is hard, we can disable swipe / drag and let people just trigger laser
- I will use number for example: I can go from 9 to 7 by (a) 9->8->7 (b) 9->7 directly, skipping 8. It results in different patterns and might confuse users 
- I can even go 9->7->8, or 9->7->8->7 again, can we not allow lines to coincide?


On engineering perspective, Could you please specify in writing about the logic that you implemented / plan to implement? that will really help commerce team to understand your codes and review. Thank you!

later, we will also get your a number pad design assets after this prototype is more or less finalized, and discuss how to integrate with the rest of the product. thank you again!

**Comment by ElderOrb** [comment]
Implementations details (might be changed during code polishing): 

1. Numpad items are implemented as GridView with ObjectModel as the model. It allows to get x/y of every item directly from model items. At the moment model is populated during component initialization. 
I've reviewed possibility to use Repeater with manual positioning or GridView with ListModel or even manual positioning of array of numpad items but decided to stick to GridView/ObjectModel as it seemed like it will require less code. 
2. Area with numpad items is covered with a single MouseArea. It allows to move currently invisible 'dragHandle' freely (and implement 'drag constraints', like dragging x/y/diagonal-only if required). Pressing on numpad item moves drag handle into the center of numpad item and adds model index of selected item into selectedItems array. 
3. There is 'allowedTargets' array which keeps all the numpad items where possible to get from the currently selected one. At the moment the logic is pretty simple - all not selected items are allowed. Per request from @changxc this place will be adjusted to allow selecting only nearest items. 
4. Every time numpad item gets 'selected' - it is added into 'selectedItems' array. Selection triggers when drag handle is above numpad item on 'positionChanged' of mouse area. This area could probably benefit from some animation to improve UX. At the moment selection is delayed, which allows to skip selection of closest item and reach far one (this is subject to change per request from @changxc )
5. There is also 'adjustPosition' function which has experimental logic for snapping drag handle to one of predefined paths (between selected item and one of 'allowedTargets'). Looks like it is not required so will be deleted during code cleanup.

**Comment by howard-stearns** [comment]
Thanks for the statement of design, @ElderOrb. Looks good...
1. I imagine you were just asked to prototype the interaction itself, rather than the integration, but do you have any thoughts on how this can be integrated securely? E.g., in which other Interface or even Entity Scripts that you (might be phished to) run can access everything?
2. Within the interaction itself, Zach had two questions:
 - Why number displays?  Some of the existing swipey things use just dots or circles, presumably because: a) the numbers don't have any numeric meaning, and b) when one sees a button, one wants to push it rather than stroke it.
 - Why timers? The swipe is already quite constrained (e.g., stroking to an adjacent area only), so do we really need the complication (for developers, maintainers, and users) of the timers?

**Comment by ElderOrb** [comment]
>> 1. I imagine you were just asked to prototype the interaction itself, rather than the integration, but do you have any thoughts on how this can be integrated securely? E.g., in which other Interface or even Entity Scripts that you (might be phished to) run can access everything?

Right, I've been asked only to prototype numpad itself. As for the possible ways of integration - it depends on the planned usage of this component. Will it be wallet-specific or global (like virtual keyboard) ? If it is planned to use it globally (although I can't think of any scenarios not related to wallet) - then probably makes sense to follow the same approach as with virtual keyboard or even consider integration of numpad directly into keyboard (after all this is just alternative way to enter password). 

>> Why number displays? Some of the existing swipey things use just dots or circles, presumably because: a) the numbers don't have any numeric meaning, and b) when one sees a button, one wants to push it rather than stroke it.

Right, I was also wondering why requirements from FB issue mentioned numbers: 

> attached picture is a swiping pad that has no number. I would suggest to include 1-9 on the number pad 

.. but after some thinking I realized that probably for some users numbers might be easier to memorize than gesture. Agree that numbers shouldn't make users to want to click button. I wasn't sure how to achieve it from design prospective so just put them outside the 'button' area. 

>> Why timers? The swipe is already quite constrained (e.g., stroking to an adjacent area only), so do we really need the complication (for developers, maintainers, and users) of the timers?

Timer was required only to allow selecting far item without selecting near one. For sure, after clarifying requirements timer is not needed anymore and I'll remove it.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6633/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6633/HighFidelity-Beta-PR12237-33299367839f1c67f2f05f8df56636b83126a587.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6633/HighFidelity-Beta-PR12237-33299367839f1c67f2f05f8df56636b83126a587.exe

**Comment by ElderOrb** [comment]
pushed updated version

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6659/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6659/HighFidelity-Beta-PR12237-73b671f70d6d6d743ba734501745e3ce9141ca27.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6659/HighFidelity-Beta-PR12237-73b671f70d6d6d743ba734501745e3ce9141ca27.exe

**Comment by changxc** [comment]
seems that i cannot do all number combination - i cannot do 1->2->3->4 for example. 

what design choice we want to make here? If we want to keep the number pad as available for both desktop and HMD, then we should not have a passphrase combination (e.g. 1234) not accessible in HMD number pad. what do you think? @AlanZimmerman @ElderOrb

**Comment by ElderOrb** [comment]
>> seems that i cannot do all number combination - i cannot do 1->2->3->4 for example.

Right, in this version you can't get to the far item without selecting near one first. That's how I understood requirements and that's how similar unlocker works in android OS. Please let me know if it needs to be changed. 

>> If we want to keep the number pad as available for both desktop and HMD, then we should not have a passphrase combination (e.g. 1234) not accessible in HMD 

This should be pretty easy to add. But then we need some indication for available variants on every step. So when use type '1', he will see that next item can be 2, 4 or 5 etc. In fact such indication already exists in form of 'dots' but it needs to be more explicit. Maybe green dots vs red dots or something? 

But I think having the same approach in HMD & desktop is good idea. User will get more consistent experience, users with touchscreen UI will get ability to unlock by swipe etc.

**Comment by changxc** [comment]
seems that i cannot do all number combination - i cannot do 1->2->3->4 for example.

Right, in this version you can't get to the far item without selecting near one first. That's how I understood requirements and that's how similar unlocker works in android OS. Please let me know if it needs to be changed.

***can't get to the far item without selecting near one first <---but this was when the numbers are in one-line? not 2 lines?ie we do not want 9->7->8, but we should allow  1->2->3->4 ***

        If we want to keep the number pad as available for both desktop and HMD, then we should not have a passphrase combination (e.g. 1234) not accessible in HMD

This should be pretty easy to add. But then we need some indication for available variants on every step. So when use type '1', he will see that next item can be 2, 4 or 5 etc. In fact such indication already exists in form of 'dots' but it needs to be more explicit. Maybe green dots vs red dots or something?

But I think having the same approach in HMD & desktop is good idea. User will get more consistent experience, users with touchscreen UI will get ability to unlock by swipe etc.

**Comment by ElderOrb** [comment]
>>> ie we do not want 9->7->8, but we should allow 1->2->3->4 ***

That's exactly how it should work at the moment.

**Comment by ElderOrb** [comment]
Hmmm... If we allow 3 -> 4, then what about 1 -> 8 ? If this should be allowed as well - then it looks like I should just remove all the restrictions at all.

**Comment by changxc** [comment]
my comment is in *** above, thank you :)

***can't get to the far item without selecting near one first <---but this was when the numbers are in one-line? not 2 lines?ie we do not want 9->7->8, but we should allow 1->2->3->4 ***

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6954/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6954/HighFidelity-Beta-PR12237-4c3f73f921c277a5e4e4355290e1fb9334bf0eed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6954/HighFidelity-Beta-PR12237-4c3f73f921c277a5e4e4355290e1fb9334bf0eed.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6970/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6970/HighFidelity-Beta-PR12237-d14870ee1be761dcd776634d029e95dab8e092b4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6970/HighFidelity-Beta-PR12237-d14870ee1be761dcd776634d029e95dab8e092b4.dmg

**Comment by changxc** [comment]
image
****

**Comment by changxc** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7112/app_12237_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7112/HighFidelity-Beta-PR12237-d14870ee1be761dcd776634d029e95dab8e092b4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7112/HighFidelity-Beta-PR12237-d14870ee1be761dcd776634d029e95dab8e092b4.exe

**Comment by changxc** [comment]
this is great, thank you!

@AlanZimmerman  let us get some design assets for you

**Pull request closed without merging**
