### PR TITLE
fix flying

### PR DESCRIPTION
**Pull request by danteruiz**
This PR makes sure that flying is enabled by default in desktop on launch.
Desktop:
Jumping/flying is always enabled.
VR Movement menu shows, allowing users to toggle HMD Flying/Jumping.
Users can change this behavior through scripting, console.
The setting does not save or persist between sessions if the behavior is changed.

VR:
Jumping/flying is disabled by default.
VR Movement menu shows, allowing users to toggle HMD Flying/Jumping.
Users can change this behavior through scripting, console.
The setting saves and persists between sessions if the behavior is changed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11847/HighFidelity-Beta-PR13751-f30b552.apk

**Comment by danteruiz** [comment]
Test plan
* Desktop mode
- launch interface
- you should be able to fly by default
- open the developer javascript console, type `MyAvatar.setEnabledFlying(false)`, flying should be disabled
 then type MyAvatar.setEnabledFlying(true), flying should be enabled again. Set flying back to false and exit interface.
- launch interface again and flying should be enable right off the bat.
- goto `settings > controls`  there should be no flying toggle button available

* HMD Mode
- launch interface
- goto `settings > controls` there should be a flying toggle button. (should not be checked by default)
check the button and save settings... you should be able to fly. uncheck button and save settings..you should not be able to jump or fly.
- open the developer javascript console, type `MyAvatar.setEnabledFlying(false)`, flying should be disabled
 then type MyAvatar.setEnabledFlying(true), flying should be enabled again
- If you disabled flying in HMD from either the console or menu when you  switch back to desktop flying should be enabled (unless if you disabled flying before you switched to HMD).

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11847/HighFidelity-Beta-PR13751-f30b552.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11847/HighFidelity-Beta-Interface-PR13751-f30b552.exe

**Comment by JeffClinton** [comment]
Currently testing (forgot to add this message)

**Comment by danteruiz** [comment]
please wait for new build

**Comment by alexiamandeville** [comment]
NO THIS IS NOT A PASS YET. Please wait for the new build to test.

"There is no menu option present to toggle flying in desktop mode." <--- this is incorrect and is (hopefully) fixed in the changes Dante had made and he had requested you wait for a new build.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11857/HighFidelity-Beta-PR13751-9bebd1e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11857/HighFidelity-Beta-Interface-PR13751-9bebd1e.exe

**Comment by alexiamandeville** [comment]
Desktop is as I expect it. I cannot thoroughly test with VR or persisting settings at the moment though so don't treat this statement as a pass. @JeffClinton please test it now. Thanks!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11857/HighFidelity-Beta-PR13751-9bebd1e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11857/HighFidelity-Beta-Interface-PR13751-9bebd1e.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
