### PR TITLE
Fix Image3DOverlay isFacingAvatar

### PR DESCRIPTION
**Pull request by SamGondelman**
- Download something from the marketplace, like the chessboard
- Right click on it.  The context overlay should appear.
- Move around.  The "i" overlay should rotate to follow you.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4329/HighFidelity-Beta-PR11643-88b8d7bc46316b50abedafa0ee44810b70a50083.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4329/HighFidelity-Beta-PR11643-88b8d7bc46316b50abedafa0ee44810b70a50083.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Download something from the marketplace, like the chessboard **Check**
Right click on it. The context overlay should appear. **Check**
Move around. The "i" overlay should rotate to follow you.a **Check**

All looks good here **Pass**

**Pull request merged**
