### PR TITLE
Revert flying disabled

### PR DESCRIPTION
**Pull request by danteruiz**
This PR reverts the commits of this PR https://github.com/highfidelity/hifi/pull/13471 which caused a falling through the floor issues.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11132/HighFidelity-Beta-PR13547-442215d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11132/HighFidelity-Beta-PR13547-442215d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11132/HighFidelity-Beta-Interface-PR13547-442215d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11132/HighFidelity-Beta-PR13547-442215d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11132/HighFidelity-Beta-Interface-PR13547-442215d.exe

**Comment by AndrewMeadows** [comment]
Test Plan:

This repro recipe for the bug worked for me:

**(1)** Login to eschatology.
**(2)** Verify this setting is disable by default:  **Settings --> Controls --> Flying & Jumping**
**(3)** Clear cache: **Edit --> Reload Content (Clears all caches)**
**(4)** Go to: dev-avatarisland
--> fall through the floor and continue to fall

The intention of this PR is to prevent the disaster at step **(4)** by default.  It is still possible for people suffer the problem if they manually disable the checkbox at **(2)** but we're just reverting the default behavior.

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 "Flying & Jumping" option is enabled by default when tested on Desktop platform.
Log included.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2171621/hifi-log.txt)

**Pull request closed without merging**
