### PR TITLE
Disable Vive teleport button if transitioning from direction button

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12114/HighFidelity-Beta-PR13826-2034162.apk

**Comment by ctrlaltdavid** [comment]
### Test Plan

The intention is that when using the Vive controller with advancement movement enabled (Settings > Controls > Advanced movement for hand controllers), if you use one of the left/right or up/down buttons and move your thumb across the center button to use the other button of the pair, the teleport beam should not display.

HMD mode

A) Vive
1) Standard movement: there should be no change in behavior compared to master.
2) Advanced movement, smooth turn (Settings > Controls > Smooth turn): on each controller, sliding your thumb from using each of left, right, up, down buttons onto the center pad should not activate the teleport beam.
3) Advanced movement, snap turn (Settings > Controls > Snap turn): 
a) on the left controller, sliding your thumb from using each of left, right, up, down buttons onto the center pad should not activate the teleport beam.
b) on the right controller, sliding your thumb from using each of up, down buttons onto the center pad should not activate the teleport beam, however sliding your thumb from each of the left, right (i.e., snap turn) buttons should activate the teleport beam.

B) Oculus: there should be no change in behaviour compared to master.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12114/HighFidelity-Beta-PR13826-2034162.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12114/HighFidelity-Beta-Interface-PR13826-2034162.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12114/HighFidelity-Beta-PR13826-2034162.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12114/HighFidelity-Beta-Interface-PR13826-2034162.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12153/HighFidelity-Beta-PR13826-5328b48.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12153/HighFidelity-Beta-Interface-PR13826-5328b48.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12153/HighFidelity-Beta-PR13826-5328b48.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12153/HighFidelity-Beta-Interface-PR13826-5328b48.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
FAIL @conklin94122 

Vive
Pass - all individual triggers and motions work as expected both in and out of "Advanced" mode.
Fail - Transitions between "left and right"/"top and bottom" still trigger the teleport.

As seen in the attached image, the thumb shows the Vive can detect touch contact with the control plate/Joystick.  When moving casually around the edge, avoiding direct center pressure, the teleport still triggers.
hifi-snap-by--on-2018-08-17_12-06-11
The avatar thumb stays in the lowered position for as long as the pad is in contact with the user's thumb.

Oculus:
Pass - Controls handle as expected, no additional strange behavior that was not in Master.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12173/HighFidelity-Beta-PR13826-26576fa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12173/HighFidelity-Beta-PR13826-26576fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12173/HighFidelity-Beta-Interface-PR13826-26576fa.dmg

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

Vive:
Pass- Basic controls are as expected. Lockout does not affect control scheme.
Pass- in Advanced mode, Lockout prevents teleport when passing over the center region. Direct center press allows teleport.

Oculus:
Pass - Controls act appropriately, and no new problems seen.

**Pull request merged**
