### PR TITLE
stop rebinding

### PR DESCRIPTION
**Pull request by howard-stearns**
https://highfidelity.atlassian.net/browse/BUGZ-672

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19974/HighFidelity-Beta-PR15765-8f9fa4a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19974/HighFidelity-Quest-Beta-PR15765-8f9fa4a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19974/HighFidelity-Beta-PR15765-8f9fa4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19974/HighFidelity-Beta-Interface-PR15765-8f9fa4a.exe

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19983/HighFidelity-Beta-PR15765-11d3f0a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19983/HighFidelity-Quest-Beta-PR15765-11d3f0a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19983/HighFidelity-Beta-PR15765-11d3f0a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19983/HighFidelity-Beta-Interface-PR15765-11d3f0a.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19984/HighFidelity-Beta-PR15765-11d3f0a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19984/HighFidelity-Quest-Beta-PR15765-11d3f0a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19984/HighFidelity-Beta-PR15765-11d3f0a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19984/HighFidelity-Beta-Interface-PR15765-11d3f0a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19986/HighFidelity-Beta-PR15765-b69d850.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19986/HighFidelity-Beta-Interface-PR15765-b69d850.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19986/HighFidelity-Beta-PR15765-b69d850.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19986/HighFidelity-Beta-Interface-PR15765-b69d850.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19986/HighFidelity-Beta-PR15765-b69d850.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19986/HighFidelity-Quest-Beta-PR15765-b69d850.apk)

**Pull request merged**
