### PR TITLE
Fix for bad static_pointer_cast on exit.

### PR DESCRIPTION
**Pull request by hyperlogic**
Identified by Address Sanatizer on Linux.

On exit ~Applicaiton calls AvatarManager::deleteAllAvatars.  This iterates over all avatars remaining in the _avatarHash. Typically this includes the MyAvatar instance.  In this case, the previous code would attempt to static cast an AvatarData pointer to an instance of OtherAvatar.  This might be harmless, but could also lead hard to diagnose issues such as memory corruption.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/18492/bad-static-cast-of-MyAvatar-to-OtherAvatar

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13235/HighFidelity-Beta-PR14068-b467267.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13235/HighFidelity-Beta-PR14068-b467267.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13235/HighFidelity-Beta-Interface-PR14068-b467267.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13235/HighFidelity-Beta-PR14068-b467267.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13235/HighFidelity-Beta-Interface-PR14068-b467267.dmg

**Comment by hyperlogic** [comment]
There is no functional difference in this PR, it is just removing an Address Sanitizer (developer tool) warning.
No QA is required

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13477/HighFidelity-Beta-PR14068-58df72a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13477/HighFidelity-Beta-PR14068-58df72a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13477/HighFidelity-Beta-Interface-PR14068-58df72a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13477/HighFidelity-Beta-PR14068-58df72a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13477/HighFidelity-Beta-Interface-PR14068-58df72a.exe

**Comment by ZappoMan** [comment]
Test Plan - can we just get a basic "smoke" test.. does the build startup and run.

**Pull request merged**
