### PR TITLE
BUGZ-987: fix depth testing of HUD layer 3D objects

### PR DESCRIPTION
**Pull request by jherico**
Add a depth/stencil attachment to the "blit" framebuffer so that the HUD level drawlayer3D task properly executes with depth testing.  

Addresses https://highfidelity.atlassian.net/browse/BUGZ-987

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20485/HighFidelity-Beta-PR15966-449f3d0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20485/HighFidelity-Beta-Interface-PR15966-449f3d0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20485/HighFidelity-Beta-PR15966-449f3d0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20485/HighFidelity-Quest-Beta-PR15966-449f3d0.apk)

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20487/HighFidelity-Beta-PR15966-449f3d0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20487/HighFidelity-Beta-Interface-PR15966-449f3d0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20487/HighFidelity-Beta-PR15966-449f3d0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20487/HighFidelity-Quest-Beta-PR15966-449f3d0.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20487/HighFidelity-Beta-PR15966-449f3d0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20487/HighFidelity-Beta-Interface-PR15966-449f3d0.exe

**Pull request merged**
