### PR TITLE
Update server console tray icons to include status

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: eabe3188b3afdb523fdb5b38b6745037e1d5eb5d available at: https://gist.github.com/b8b2385969f5a0cba21a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.dmg

**Comment by huffman** [comment]
Need to test on OSX

**Comment by hifi-gustavo** [comment]
Build console output for commit: c4c1fdc6db925f49365e1d4a9a903ef3a0da9f1b available at: https://gist.github.com/b8b2385969f5a0cba21a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76c9e298f52ee3aa968e817841b72fd21c843c0e available at: https://gist.github.com/b8b2385969f5a0cba21a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d55c5223c15e984c23ae8369be6cb416d76c995 available at: https://gist.github.com/b8b2385969f5a0cba21a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7068.dmg

**Pull request merged**
