### PR TITLE
keep buttons from drifing away from in-world display of controllers

### PR DESCRIPTION
**Pull request by sethalves**
- change parenting structure of in-world display of hand controllers to avoid buttons drifting away from base

https://highfidelity.fogbugz.com/f/cases/16399/HMD-requestShowHandControllers-model-for-the-touch-controllers-breaks-visually-when-tracking-is-lost

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- launch interface, open Scripting Console, paste in `HMD.requestShowHandControllers()`
- switch to HMD
- observe hand-controllers
- move the buttons and joysticks on the controllers and make sure the in-world version also moves
- if using oculus touch, squeeze the "grip" button and vigorously shake the controller
- make sure the buttons don't drift away from the controller
- rescale your avatar and then resqueeze "grip" while shaking the controller
- make sure the buttons don't drift
- do all this for an oculus and a vive

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11131/HighFidelity-Beta-PR13546-73071df.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11131/HighFidelity-Beta-PR13546-73071df.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11131/HighFidelity-Beta-Interface-PR13546-73071df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11131/HighFidelity-Beta-PR13546-73071df.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11131/HighFidelity-Beta-Interface-PR13546-73071df.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Buttons look good on all platforms.

**Pull request merged**
