### PR TITLE
Dk/agent avatar audio artifacts

### PR DESCRIPTION
**Pull request by davidkelly**
This fixes both the screaming when`summon.js` is stopped, and the click at the beginning of the audio when using `Avatar.playAvatarSound`.  Also fixed some weird whitespace issue and removed some commented out code.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b09364c288ac2a53aebf0dd8cadbdc0045a9698b available at: https://gist.github.com/b37bc50eeeaaf053fd0f2bc19675f136<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8911-b09364c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8911-b09364c.dmg

**Comment by davidkelly** [comment]
# Test Plan

(1) Run a few (say, 2 or 3) instances of `scripts/developer/tests/performance/crowd-agent.js` on your server.  I like to use python -m SimpleHTTPServer 8888, when in the `scripts/developer/tests/performance` directory, and put `http://localhost:8888/crowd-agent.js` in the server settings.
(2) in interface, run `scripts/developer/tests/performance/summon.js`
(3) it should sound good -- wait awhile and hear it multiple times, etc...
(4) stop `summon.js`.  Should hear no horrible screaming as the avatars shrink away to nothing.

**Comment by howard-stearns** [comment]
... (5) and then repeat steps (2)-(4)?   Do we expect it to work multiple times in a row?

**Comment by davidkelly** [comment]
(5) it does for me -- didn't really think that was an issue.

**Pull request merged**
