### PR TITLE
filenames on Linux are case-sensitive

### PR DESCRIPTION
**Pull request by sethalves**
- on Linux, fix bug which cause scripts run from local disk to not load upon interface restart

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- Load a script which has a camel-case name from local disk
- restart interface
- note that the script no longer causes a "script failed to load" dialog after restart and that the script runs

**Comment by hifi-gustavo** [comment]
Build console output for commit: f2c9bbc32d8b483e84ac3cc8fd8ba7be6d842640 available at: https://gist.github.com/d6e641e1c844052cc91c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7119.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7119.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 164d5d9c7e15a71bc8fe4aa82e0060c3fdfaf4e7 available at: https://gist.github.com/d6e641e1c844052cc91c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7119.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7119.dmg

**Comment by OmegaHeron** [comment]
OS X can go either way - the default HFS+ FS is case insensitive, but in the past you could format with a more unix like FS (I forget the name) that is case sensitive.  It's like 99.9% have HFS+, but that .1% is always one that will bite you in nether regions.

**Comment by OmegaHeron** [comment]
apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not

Has some maybe useful background

**Pull request merged**
