### PR TITLE
Make procedural dirty marker atomic

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ff07e476266cd5038982dde7f6f1dff1612808b4 available at: https://gist.github.com/58d68f0f500d49f8708a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7358.dmg

**Comment by zzmp** [comment]
@AndrewMeadows according to http://en.cppreference.com/w/cpp/language/memory_model, this is a data race, and data races have undefined behavior. While it may not do anything unexpected, nothing guarantees that. Other than this, I agree with everything you've said.

The mutex locks are only there for the `_proceduralData`. I am going to move the reads/writes of the `std::atomic<bool>` out of its scope to avoid the confusion that they are also intended to cover `_proceduralDataDirty`. Do you feel OK about that?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a8cca3dcca0f4e59b5d25429b9b9a03962b1c30 available at: https://gist.github.com/58d68f0f500d49f8708a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7358.dmg

**Comment by OmegaHeron** [comment]
Is this going to be just a general smoke test or is there anything specific to exercise?

**Comment by zzmp** [comment]
@OmegaHeron general smoke test.

**Comment by OmegaHeron** [comment]
Tested Windows 7 - No issue seen, everything seems to work as expected.  I did have a flurry of startup crashes in QtQML, but, that's reasonably common with debug builds and doesn't seem to follow to production builds.  QA Pass

**Pull request merged**
