### PR TITLE
Fix a crash in Image Provider when logging in or reloading all scripts

### PR DESCRIPTION
**Pull request by zfox23**

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- A set-up wallet
- An HMD that you are wearing
- You're logged out

### Tests
1. Log out of your High Fidelity account using the Tablet
    - Verify that you're logged out and that you didn't crash.
2. Log in to your High Fidelity account using the Tablet
    - Verify that you're logged in and that you didn't crash.
3. Repeat steps 1 and 2 a large number of times (10+)
4. Press CTRL+R to reload all scripts.
    - Verify that you didn't crash
5. Repeat step 4 a medium number of times (5+)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9356/app_13063_PR_cd76336e6a937128a5b8f227ae57a3e856431914.apk

**Comment by zfox23** [comment]
@ZappoMan IMO, we don't need to log. The instances where the `get`s would realistically fail to return pointers AND we're even executing this codepath are rare, and, even if they happen, the codepath will be executed again at a later time, correcting the `get` failure.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9356/HighFidelity-Beta-PR13063-cd76336e6a937128a5b8f227ae57a3e856431914.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9356/HighFidelity-Beta-Interface-PR13063-cd76336e6a937128a5b8f227ae57a3e856431914.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Logged in and out over ten times and never crashed! Reloaded scripts like no tomorrow and did not crash either.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9431/app_13063_PR_cd76336e6a937128a5b8f227ae57a3e856431914.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9431/HighFidelity-Beta-PR13063-cd76336e6a937128a5b8f227ae57a3e856431914.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9431/HighFidelity-Beta-Interface-PR13063-cd76336e6a937128a5b8f227ae57a3e856431914.dmg

**Pull request merged**
