### PR TITLE
Fix aligning selection to grid

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.manuscript.com/f/cases/edit/16559

Test Plan:
-Enter Interface in desktop mode
-Open Create and select any entity or entities
-Select the Grid tab and make it visible
-Click Align to Selection and verify the grid is now aligned to the bottom of the selected entities
-Click Align to Avatar and verify the grid is now aligned to the bottom of your avatar
-Click on any selected entity to set focus in world and away from Create window
-Press G key and verify the grid is now aligned to the bottom of the selected entity
-Repeat a few times selecting different entities and aligning them to selection either via Align to Selection button on grid window or pressing G when focused in world

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11302/HighFidelity-Beta-PR13608-151f948.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11302/HighFidelity-Beta-PR13608-151f948.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11302/HighFidelity-Beta-Interface-PR13608-151f948.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11302/HighFidelity-Beta-PR13608-151f948.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11302/HighFidelity-Beta-Interface-PR13608-151f948.exe

**Comment by QliCknox** [comment]
Pass @conklin94122 

Both "Align To Selection" and "Align to Avatar" work as expected

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11325/HighFidelity-Beta-PR13608-151f948.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11325/HighFidelity-Beta-PR13608-151f948.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11325/HighFidelity-Beta-Interface-PR13608-151f948.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11325/HighFidelity-Beta-PR13608-151f948.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11325/HighFidelity-Beta-Interface-PR13608-151f948.exe

**Pull request merged**
