### PR TITLE
Change tablet model and spawn position

### PR DESCRIPTION
**Pull request by druiz17**
This PR changes the tablet model and spawn position.

Details in this doc - https://highfidelity.atlassian.net/wiki/spaces/DES/pages/283607116/Tablet+Improvements

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- open the tablet
- the model should have a smaller bezel than before.
- press create button and make sure that the tablet screen position looks right.
- Open the tablet using the left hand - tablet should appear more towards your left view.
- Open the tablet using the right hand - tablet should appear more towards your right hand

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8904/app_12936_PR_9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8904/HighFidelity-Beta-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8904/HighFidelity-Beta-Interface-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8904/HighFidelity-Beta-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8904/HighFidelity-Beta-Interface-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Tablet size and bezels look much better and appears on the correct side depending on what hand the tablet was opened.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9232/app_12936_PR_9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9232/HighFidelity-Beta-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9232/HighFidelity-Beta-Interface-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9232/HighFidelity-Beta-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9232/HighFidelity-Beta-Interface-PR12936-9d6fc13a0470317e3d6472e141a2f0c1cb6e184f.exe

**Pull request merged**
