### PR TITLE
fix blank create tabs in HMD

### PR DESCRIPTION
**Pull request by birarda**
- fix for blank create tabs in HMD

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

In HMD, open Create. The List, Properties, Grid, and Particle tabs should all render their respective interfaces.

Follow the same steps in Desktop. All interfaces for create tabs should be properly rendered.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2093/HighFidelity-Beta-PR11076-17dd028ec7ffc761920dbcf4226bf691ef66acba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2093/HighFidelity-Beta-PR11076-17dd028ec7ffc761920dbcf4226bf691ef66acba.exe

**Comment by conklin94122** [comment]
Verified.

**Pull request merged**
