### PR TITLE
Remove unused avatar attachment constant

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Avatar attachment code was removed in: https://github.com/highfidelity/hifi/pull/14251
This PR just removes a now-unused string constant. It was used in the now removed "Avatar Attachment" option in the Edit > Package Model as FST menu item.

No testing needed - apart from verifying that the code has successfully built.

https://highfidelity.manuscript.com/f/cases/17990

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15485/HighFidelity-Beta-PR14489-1683179.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15485/HighFidelity-Beta-Interface-PR14489-1683179.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15485/HighFidelity-Beta-PR14489-1683179.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15485/HighFidelity-Beta-Interface-PR14489-1683179.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
