### PR TITLE
HMD keyboard polishing

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Only raise keyboard if in HMD display mode. (Current exception: Web entities.)
Included "," and "." in both alpha and numeric layouts; 
Added extra keys to numeric layout via a shift key.
Added keyboard to some dialogs that were missing it.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
@AlanZimmerman , @RyanDowne There are still some things to do to finish off the keyboard but here's the new layout with extended characters available. Particular changes:
- Period (plus comma to balance the spacebar) added to lower row, so that it's readily available for both URLs and numeric values.
- Shift key added to numeric set of keys, to provide extra keys.

Note: The keyboard only displays in HMD mode now (except on Web entity which I've deferred work on until after addressing some other things.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a75925d1e358da1043e201c53de2757cd3c8549a available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-a75925d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-a75925d.dmg

**Comment by RyanDowne** [comment]
This looks great, David and fixes this too: https://highfidelity.fogbugz.com/f/cases/1914/virtual-keyboard-shift-keys

It's still true that the keyboard doesn't appear on browser popups : https://highfidelity.fogbugz.com/f/cases/1828/no-keyboard-in-browser-pop-ups

That could be a separate job however.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f42a3fe9e2dfe51c9e824b2c61cd3fc366ba643 available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-8f42a3f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-8f42a3f.dmg

**Comment by ctrlaltdavid** [comment]
QA

Test using the keyboard's alpha and numeric layouts. Including the shift keys for both (capitals and extra characters respectively)

Check that the keyboard can be used if in HMD display mode in at least the following dialogs:
* Login dialog
* Address bar dialog
* Browser popped up from address bar's card details (click on "camera" or "person" icon then click on social media share button to open in new browser window)
* Running Scripts
* Entities editor
* Settings dialogs
* Avatar Browser from Avatar settings
* Attachments dialogs
* Attachments browser from Attachments dialog
* Browser
* Web entity
* Marketplace
* Add asset to world
* Rename asset
* Export entities

Check that the keyboard does not raise in the above dialogs if in desktop display mode.

Check program log for QML errors, i.e., errors referring to ".qml" files.

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

Desktop mode - login dialog display as blank square - no text.  Tested against last dev build (5499) that does display dialog.

Log displays at time of opening login dialog;

[10/13 20:14:07] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR8799/resources//qml/LoginDialog/LinkAccountBody.qml:152:5: KeyboardPunctuation is not a type

hifi-snap-by--on-2016-10-13_20-14-30

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94e20d9a13fa35c91c4a3888feb4764eb1b54be7 available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-94e20d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-94e20d9.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

Test | Desktop | DK2 HMD
--- | --- | ---
Login dialog | **Pass**
dialog | **Pass** | **Pass**
Browser popped up from address bar's card details (click on "camera" or "person" icon then click on social media share button to open in new browser window) | **Pass** | **Pass**
Running Scripts | **Pass** | **Pass**
Entities editor | **Pass** | **Pass**
Settings dialogs | **Pass** | **Pass**
Avatar Browser from Avatar settings | **Pass** | **Pass**
Attachments dialogs | **Pass** | **Pass**
Attachments browser from Attachments dialog | **Pass** | **Pass**
Browser | **Pass** | **Pass**
Web entity | Shows Keyboard for input fields | **Pass**
Marketplace | **Pass** | **Pass**
Add asset to world | **Pass** | **Pass**
Rename asset | **Pass** | See notes
Export entities | **Pass** | **Pass**

Renaming an asset shows HMD keyboard if using rename button - it does not if you click item in list making its name editable.

Package model from Edit menu displays a non QML dialog, bad in HMD.

Keyboard covers input fields if input field near bottom of dialog (like in some of the vertically tall scrollable settings) -- not sure there's an elegant solution to that.

Tested OS Keyboard - all elements produce expected text.

Saw no QML warnings.

**Comment by OmegaHeron** [comment]
Note - I *think* this is a QA Pass unless anything in my review raises red flag.

I don't believe Package model issue problem has scope in this PR - it's just a note since I saw it while going through all menu items.  Renaming model issue, I don't think, should be a block to pass.  OS Keyboard showing in Desktop mode for web entity is, I think, expected.

**Comment by AlanZimmerman** [comment]
Crashing when switching from 2D to HMD overtime on Windows. This happens using Display->OpenVR (Vive) and also when using the HUD "Switch" button.

**Comment by RyanDowne** [comment]
@alan if that crashing bug was not introduced in this PR then I think it's a PASS

**Comment by ctrlaltdavid** [comment]
@OmegaHeron Thanks very much for the test report.
- Web entity showing keyboard in desktop mode is a known issue for this PR and will be fixed at soem later stage.
- Renaming assets in Asset Browser directly in the list is a new one on me; I'll need to add keyboard support for that.
- Keyboard covering input fields in settings dialogs: the dialog should auto-scroll. It used to but I see that it's no longer working for some reason; I'll fix this. (Window should also auto-scroll as necessary in other dialogs and Web entity. I'll double check these too.)

**Comment by ctrlaltdavid** [comment]
@AlanZimmerman Check that you have SteamVR running. This PR build is based on Windows build 5499, i.e., before the Vive crash fix of build 5500.

**Comment by ctrlaltdavid** [comment]
Fixed renaming assets in Asset Browser directly in the list plus keyboard covering input fields in settings and other QML dialogs when it is raised.

**Comment by hifi-gustavo** [comment]
Build console output for commit: eff8502f6757d686397237c5dea88304ed9b5c37 available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-eff8502.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-eff8502.dmg

**Comment by RyanDowne** [comment]
@ctrlaltdavid I think I agree with Alan here in that we should move the comma next to the period on the right even if that makes the space bar unbalanced.

**Comment by ctrlaltdavid** [comment]
@RyanDowne I've just sent Alan a mock-up with 3 keyboard layout alternatives to have a look at.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfc9974fb7feeaadd809400f065c0c5bf7b988e3 available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-bfc9974.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-bfc9974.dmg

**Comment by AlanZimmerman** [comment]
Looks good to me on the Vive.

**Comment by ZappoMan** [comment]
@ctrlaltdavid - looks like you need to rebase with the latest master.

**Comment by ctrlaltdavid** [comment]
Keyboard in address bar dialog:
- Only displays in HMD mode.
- Does not hide if click outside address entry field.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a767a27e7e36bd870bb1def39580086b006a1b69 available at: https://gist.github.com/38bec42057e5e8bab171060ed83a3000<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-a767a27.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8799-a767a27.dmg

**Pull request merged**
