### PR TITLE
Add AudioNoiseGate to recordings played through Interface

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
### QA Plan

#### General tests
Ensure interface audio works as expected.

#### Specific tests
Silent audio was previously not recorded. For this test, use `recorder.js` to record something with intermittent silences, while your noise reduction is turned off (`Developer > Audio > Audio Noise Reduction`) (similar to [this](https://github.com/highfidelity/hifi/files/778569/recording.hfr.txt)).
Play that using the recorder.js script.

Watch your domain's audio-mixer's statistic for `silent_packets_per_frame`. You should see it increasing when the recording is silent, indicating that Interface is correctly sending silent packets.
You should also be able to see these statistics directly in Interface (@zappoman, could you edit this comment to clarify?).

Do all of those with another connected client, to ensure that the Agent sounds as it should. Verify that the noise gate strips any "fuzz" on the silent audio (this includes verifying that the "fuzz" is there when the noise gate is off).

Ensure that "server echo" continues to work. Ensure that "mute" continues to mute, even if playing a recording.

**Comment by zzmp** [comment]
QA - I have not tested this yet, as I don't have access to Interface because of a nor'easter. I will test it myself tomorrow and add `QA Ready`. Feel free to test beforehand, just know that I haven't vetted it yet.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e86d21b186c38c48cc89e7ba78007344b76659a8 available at: https://gist.github.com/1e8ed6b3c9da988ac5f0ff04c1d6e65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-e86d21b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-e86d21b.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e86d21b186c38c48cc89e7ba78007344b76659a8 available at: https://gist.github.com/1e8ed6b3c9da988ac5f0ff04c1d6e65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-e86d21b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-e86d21b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 324b9d2aebe00df8474f8428c179cd9127e4bb50 available at: https://gist.github.com/1e8ed6b3c9da988ac5f0ff04c1d6e65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-324b9d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-324b9d2.dmg

**Comment by zzmp** [comment]
test this please

**Comment by zzmp** [comment]
I looked through the Jenkins output and could not find why this failed - can someone look at the Jenkins UI for me?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 324b9d2aebe00df8474f8428c179cd9127e4bb50 available at: https://gist.github.com/1e8ed6b3c9da988ac5f0ff04c1d6e65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-324b9d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-324b9d2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 789bb7c8550d439748d894d54b7f8e896d319dce available at: https://gist.github.com/1e8ed6b3c9da988ac5f0ff04c1d6e65e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-789bb7c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9897-789bb7c.dmg

**Comment by OmegaHeron** [comment]
Windows 10
QA Fail, I think.  I created recording as specified - I see no indication of silent frames being registered either in audio-mixer stats from DS web interface or on screen stats in Interface.  For #9896 I do see indications of bot impacting silent frame stats.

**Comment by zzmp** [comment]
@OmegaHeron I retested this on my system and could see silent frames.

Can you ping me to go over your test?

**Comment by OmegaHeron** [comment]
Re-testing now.

**Comment by OmegaHeron** [comment]
QA Pass - it passes test outlined.  What happened here was a failure on my part where I got instructions for this PR's sibling mixed up with what I used to test this one.  After clarification and re-test it passes general and specific tests.

**Pull request merged**
