### PR TITLE
Pull back the stylus position in hand.

### PR DESCRIPTION
**Pull request by druiz17**
Move the stylus z position backwards. The does not change any stylus functionality or behavior

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- this PR does not change the stylus functionality or behavior
- perform a smoke screen of using the stylus on tablet.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3483/HighFidelity-Beta-PR11416-92f3dfe2ab02159c13203f148e414672ddc3bb9b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3483/HighFidelity-Beta-PR11416-92f3dfe2ab02159c13203f148e414672ddc3bb9b.exe

**Comment by YuppyPlays** [comment]
Testing

**Comment by YuppyPlays** [comment]
Testing complete:

this PR does not change the stylus functionality or behavior **Check**
perform a smoke screen of using the stylus on tablet. **Check**

Everything seems to be behaving as expected when going through tablet with stylus in HMD. **Pass**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3499/HighFidelity-Beta-PR11416-2c55419c603856336b7ef5efeb5d27b3049977c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3499/HighFidelity-Beta-PR11416-2c55419c603856336b7ef5efeb5d27b3049977c2.exe

**Pull request merged**
