### PR TITLE
10024 Wallet: TextField Focus Problems

### PR DESCRIPTION
**Pull request by ElderOrb**
This PR attempts to fix 'https://highfidelity.fogbugz.com/f/cases/10024/Wallet-TextField-Focus-Problems' and simplify code by removing excessive MouseArea-s. 

It also removes additional 'collapse keyboard' button in Wallet (90-degree-rotated symbol '>' like on the screenshot below): 

image

***Test plan*** 

1. Switch to VR
2. Open the Wallet app. 
3. Click the "Show passphrase" checkbox on the "Please Enter Your Passphrase" screen.
4. Ensure you still can click inside the passphrase TextField to give keyboard focus to the TextField.
5. Ensure virtual keyboard appears on clicking into text edit on all the Wallet screens
6. Ensure virtual keyboard don't have additional 'collapse keyboard' button.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5370/HighFidelity-Beta-PR11921-f7328f05fb3c3fc5af3fc2ba11763af8d2e1840d.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5371/HighFidelity-Beta-PR11921-f7328f05fb3c3fc5af3fc2ba11763af8d2e1840d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5371/HighFidelity-Beta-PR11921-f7328f05fb3c3fc5af3fc2ba11763af8d2e1840d.dmg

**Comment by Nex-Pro** [comment]
After a pile of vive issues were resolved this worked ok.

But I noticed that I could log out. Then log in again but the wallet did not ask me for the passphrase after logging back in. That is not related to this PR but maybe should be checked.

### Pass based on the now missing test notes.

**Comment by Nex-Pro** [comment]
@ElderOrb I assume you mean only one collapse keyboard button. ( the new style one, bottom left of keyboard )

**Comment by ElderOrb** [comment]
> I assume you mean only one collapse keyboard button. ( the new style one, bottom left of keyboard )

Right, new style one at bottom right of keyboard should present, but old one temporarily-added by Zach looking like 90-degree-rotated symbol '>' should gone

**Comment by Nex-Pro** [comment]
@ElderOrb indeed.

**Pull request merged**
