### PR TITLE
Fix the cookie cutter issue in stereo

### PR DESCRIPTION
**Pull request by samcake**
IN stereo the right side objects with an opacity map wasn't fragment killed correctly because the alphaTreshold wasn;t assigned correctly

THis is now fixed

### CODE REVIEW

**Comment by samcake** [comment]
FIrst Merge this PR: https://github.com/highfidelity/hifi/pull/5168

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5a2d2485c0805fc28da390cbc08ccaff2ba4f1c1 available at: https://gist.github.com/67408f2fff600891b1e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2920197e885973866ee05278fecee0d04a811659 available at: https://gist.github.com/67408f2fff600891b1e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 873955b17e66497becf430a821221b4f77894081 available at: https://gist.github.com/67408f2fff600891b1e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5170.dmg

**Pull request merged**
