### PR TITLE
Case 19495 for v0.75.0-rc: zero velocities of non-dynamic entities on nearGrab release

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
https://highfidelity.fogbugz.com/f/cases/19495/In-VR-mode-grabbed-non-dynamic-entities-retain-linear-velocity-if-released-while-avatar-is-moving

**Test Plan:**
**(1)** Make a non-dynamic Entity
**(2)** In HMD: near-grab Entity
**(3)** While walking avatar around: release grab on Entity
**-->** on bugged version: entity leaves grab with non-zero velocity
**-->** on fixed version: entity leaves grab and has zero velocity

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14521/HighFidelity-Beta-PR14306-1a8045b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14521/HighFidelity-Beta-PR14306-1a8045b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14521/HighFidelity-Beta-Interface-PR14306-1a8045b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14521/HighFidelity-Beta-PR14306-1a8045b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14521/HighFidelity-Beta-Interface-PR14306-1a8045b.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Bug is not completely fixed. Far grabbed non-dynamic objects keep linear velocity. This does not occur in 0.74.0.

hifi-snap-by--on-2018-10-31_08-53-29
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2534965/hifi-log.txt)

**Comment by ZappoMan** [comment]
For the record: I am very much NOT A FAN of this. @sethalves we need to get your project finished to make sure that grabbing is not editing fundamental properties of entities.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14528/HighFidelity-Beta-PR14306-13016f2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14528/HighFidelity-Beta-PR14306-13016f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14528/HighFidelity-Beta-Interface-PR14306-13016f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14528/HighFidelity-Beta-PR14306-13016f2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14528/HighFidelity-Beta-Interface-PR14306-13016f2.exe

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
