### PR TITLE
Move Shapes app files from scripts directory to marketplace directory

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Install the PR  and check that there is NOT a directory, C:\Program Files\High Fidelity - PR11548\scripts\shapes\.

**Comment by ctrlaltdavid** [comment]
QA ready

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3959/HighFidelity-Beta-PR11548-765f3fc38175a6ab53d0c1c50b0821da08f72dda.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3959/HighFidelity-Beta-PR11548-765f3fc38175a6ab53d0c1c50b0821da08f72dda.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
Pass

**Comment by Nex-Pro** [comment]
untitled-1

**Comment by YuppyPlays** [comment]
Testing complete:
[apologies for delay]
This was a **Pass**, shapes folder does not get created.
image

**Pull request merged**
