### PR TITLE
Make Clara.io downloads convert textures to PNG

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
In particular, many models by default have textures in TGA format which Interface doesn't support.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Test notes:
- Desktop and tablet.
- "Download" button repositioned top-right of image in tablet.
- Redirected to register/sign-in if not logged in.
- Cancel download while model is being prepared.
- Download model.
- Models with TGAs successfully downloaded with PNGs.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8cd7e1b3771dbab2f3da6ce49b2cfa7eab7bf48c available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-8cd7e1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-8cd7e1b.dmg

**Comment by cozza13** [comment]
I am testing this and talking with @ctrlaltdavid . Does not need others to test at this time.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 288c069687b6d90e739ed5882c66127004a5745d available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-288c069.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-288c069.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d45e6f00cbbe012e28baee53745c2e81f137e508 available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-d45e6f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-d45e6f0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f2386eabd02dc0b0560d50bd4a0324934426bcb available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-6f2386e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-6f2386e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 632989e031f557f4f4793662e6a9c4638c5f5b25 available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-632989e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-632989e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7ab7316a89286c370e9adb0775e9b8dcc69a261 available at: https://gist.github.com/b9f1cc3d0ad73e1809dbbd80e47bce89<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-d7ab731.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9363-d7ab731.dmg

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
Tester: Coal
CPU: i7 6700k
GPU: GF 970

Noticed at the bottom the blue `See also other marketplaces.` Though the english seems off on that, I would think it would be something like `Check out other marketplaces.`
Verified the `Create an account here` link functioned properly. Clicked `Back` as I did not need to create an account.
Clicked `Explore` for **Clara.io** market.
Saw `Flail weapon` as new on the list so I clicked it and then clicked `Download to High Fidelity` and was asked to login, which I did.
Per the test notes I canceled the download as the model was being prepared.
I went back and tested the model again to make sure it prepared and downloaded correctly.
This worked just fine and I got a message that said `Adding Flail to the asset server`
The item also was placed infront of my avatar in world.

From my tests I would say this is a PASS

**Pull request merged**
