### PR TITLE
BUGZ-996: Android app crashes on startup

### PR DESCRIPTION
**Pull request by annabrewer**
On Android, we do not pull information about the CPU, GPU or display in order to set the performance level of Interface. So when getting that information, the index is -1, but the bounds checking logic did not handle that case, causing a bad memory access.
https://highfidelity.atlassian.net/browse/BUGZ-996

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20494/HighFidelity-Beta-PR15968-a6c569d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20494/HighFidelity-Quest-Beta-PR15968-a6c569d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20494/HighFidelity-Beta-PR15968-a6c569d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20494/HighFidelity-Beta-Interface-PR15968-a6c569d.dmg

**Comment by annabrewer** [comment]
jenkins rebuild this please

**Comment by annabrewer** [comment]
Android crash is fixed, hopefully Jenkins error on Windows was a one-time thing.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20500/HighFidelity-Beta-PR15968-2051a99.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20500/HighFidelity-Quest-Beta-PR15968-2051a99.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20500/HighFidelity-Beta-PR15968-2051a99.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20500/HighFidelity-Beta-Interface-PR15968-2051a99.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20500/HighFidelity-Beta-PR15968-2051a99.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20500/HighFidelity-Beta-Interface-PR15968-2051a99.dmg

**Pull request merged**
