### PR TITLE
WL 21446: Add doppleganger "move-as-you-move" roomscale functionality

### PR DESCRIPTION
**Pull request by humbletim**
#### Testing (Roomscale HMD required):

* Launch this PR's marketplace script:
  - https://raw.githubusercontent.com/humbletim/hifi/b5f5a037/unpublishedScripts/marketplace/doppleganger-attachments/dist/app-doppleganger-marketplace.js
* Activate the doppleganger mirror.
* Using *hand controllers*: move around and examine the doppleganger.
  - Verify that it "stays put as you move."
* Using *your legs and body*: move around (within roomscale) and examine the doppleganger.
  - Verify that it "moves as you move."
   (ie: that it mimics your horizontal steps like forward/backward and sideways).
* Perform a quick doppleganger smoke test by adding/removing/observing attachments to verify overall behavior has remained consistent.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1714/HighFidelity-Beta-PR10976-7bcd9f9f9544256638657ca15c78671c4b7e47d6.exe

**Comment by CainFoool** [comment]
@humbletim: Looks like this failed the Mac build.

**Comment by humbletim** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1716/HighFidelity-Beta-PR10976-7bcd9f9f9544256638657ca15c78671c4b7e47d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1716/HighFidelity-Beta-PR10976-7bcd9f9f9544256638657ca15c78671c4b7e47d6.exe

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
 Launch this PR's marketplace script: https://raw.githubusercontent.com/humbletim/hifi/7bcd9f9f/unpublishedScripts/marketplace/doppleganger-attachments/dist/app-doppleganger-marketplace.js | Pass
Activate the doppleganger mirror. | Pass
Using hand controllers: move around and examine the doppleganger. | Pass
Verify that it "stays put as you move." | Pass
Using your legs and body: move around (within roomscale) and examine the doppleganger. | Pass
Verify that it "moves as you move." | Pass
Perform a quick doppleganger smoke test by adding/removing/observing attachments to verify overall behavior has remained consistent. | Pass

One thing I noticed however was with the Avatar Attachments, on your own body they aren't grabbable/interactive however they were on the Doppleganger. When you tried to grab them, it picked them up but there were parented to the Avatar so they weren't able to move but you could see the Attachment glitching out, especially if you moved away from the Doppleganger while you were still holding on to the item.

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2130/HighFidelity-Beta-PR10976-b5f5a037f007e91b22d27cb39507e347637e7bed.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2131/HighFidelity-Beta-PR10976-b5f5a037f007e91b22d27cb39507e347637e7bed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2131/HighFidelity-Beta-PR10976-b5f5a037f007e91b22d27cb39507e347637e7bed.exe

**Comment by hyperlogic** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2251/HighFidelity-Beta-PR10976-b5f5a037f007e91b22d27cb39507e347637e7bed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2251/HighFidelity-Beta-PR10976-b5f5a037f007e91b22d27cb39507e347637e7bed.exe

**Pull request merged**
