### PR TITLE
DO NOT MERGE - 20871 prototyping

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ec761bd9492dffa72b65e0a82c82b2131ffb68b available at: https://gist.github.com/07b70d2b61bc1ad16af73e5fa5109a5e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.dmg

**Comment by kevinmthomas-carpool** [comment]
PR Build: 7588
Testing Architecture:  64-bit Mac Notebook 
Testing OS:  OS X
Testing Location:  hifi://sandbox
Test Results:  
- All tabs: section headings are red and the text is a serif font. (What we want is a sans-serif font that the CSS specifies.)  VERIFIED
- Entity list tab: table headings are green and text is a serif font. (What we want is a sans-serif font that the CSS specifies.)  VERIFIED
- Entity properties tab: drop-down lists have a cyan drop-down icon on their right. Probably a big "X" multi-directional arrow. (What we want is a nice little drop-down triangle.)  FAILED - Similar behavior:  Cyan check boxes, san-serif font, unable to open dropdown and observed large numeric values near the drop-down areas.  Attached screen shots for further inspection.
- Entity properties tab: the spin boxes have dotted yellow rectagles where the up/down spin triangles should be. But the spin triangles will probably not be showing at all or may be misplaced or the wrong glyphs. (What we want is the spin triangles in the dotted yellow boxes.)  VERIFIED
*** Attached screenshots *** 
[attachments.zip](https://github.com/highfidelity/hifi/files/205549/attachments.zip)

**Comment by kevinmthomas-carpool** [comment]
Snapshot after the result of an edit.js reload and not selecting any entity.
screen shot 2016-04-05 at 7 49 01 pm

**Comment by kevinmthomas-carpool** [comment]
To make a proper control test - Results of main Mac release 4633 indicating a cyan enlarged numeric 5.  Results are NOT expected.
screen shot 2016-04-05 at 7 54 41 pm
screen shot 2016-04-05 at 7 55 04 pm

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91f5d77e92808e60f4c1729e679f9a46bc3816f6 available at: https://gist.github.com/07b70d2b61bc1ad16af73e5fa5109a5e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 86ddf0ff0220b193b7e6cd26cbf68ab73151f67c available at: https://gist.github.com/07b70d2b61bc1ad16af73e5fa5109a5e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7588.dmg

**Comment by kevinmthomas-carpool** [comment]
screen shot 2016-04-06 at 6 58 12 am
screen shot 2016-04-06 at 6 58 46 am

Confirmed Yellow Section Headings

Confirmed Dotted Yellow Boxes enclosing spin boxes

Confirmed no horizontal scroll bar on entity properties tab

Confirmed right margin of entities table adjusted to match left

enclosed screen shots

**Pull request closed without merging**
