### PR TITLE
Fix font loading for MacOS via completely different font loading method

### PR DESCRIPTION
**Pull request by zfox23**
For some reason, loading `.ttf` fonts via `qrc:/` on MacOS doesn't work, even though it works on Windows and is supposedly supported. This PR fixes glyph loading on MacOS, with no behavioral change to font loading on other platforms.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. This one's simple! Open up various QML apps from within Interface in both HMD and Desktop. Also open those apps in Desktop mode when using the MacOS client.
    - Verify that all of the text you see isn't garbled nonsense or visually corrupted. Examples of QML apps include Wallet, GOTO, and Spectator Camera.

If you see this (or something like it), fail this PR:
image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7883/app_12596_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7884/app_12596_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7884/HighFidelity-Beta-PR12596-d0cc64f63d07104ee40737e83a86424d86f6f8c0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7884/HighFidelity-Beta-PR12596-d0cc64f63d07104ee40737e83a86424d86f6f8c0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7897/app_12596_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7898/app_12596_PR.apk

**Comment by sethalves** [comment]
I've built this PR on osx and it appears to solve the problem.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7898/HighFidelity-Beta-PR12596-409f5293bfe7214c3bdb71e79daa3cbe480a85cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7898/HighFidelity-Beta-PR12596-409f5293bfe7214c3bdb71e79daa3cbe480a85cd.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

On Mac, Wallet, GoTo, and Marketplace were tested. No glyphs!

On Windows/HMD, Wallet, GoTo, Marketplace, and Spectator Cam were tested. No glyphs there either. Solid pass!

**Comment by conklin94122** [comment]
@zfox23 Needs dev review

**Comment by zfox23** [comment]
thanks @conklin94122 !

**Pull request merged**
