### PR TITLE
data url for web entity

### PR DESCRIPTION
**Pull request by howard-stearns**
Recognize data: URLs in Web entities.

### CODE REVIEW

**Comment by howard-stearns** [comment]
Fixes https://highfidelity.fogbugz.com/f/cases/20430/Web-entities-don-t-handle-data-urls

To test - make Web entities with various supported URL schemes, which should now include the examples on, e.g., https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16137/HighFidelity-Beta-PR14637-af65e59.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16137/HighFidelity-Beta-PR14637-af65e59.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16137/HighFidelity-Beta-Interface-PR14637-af65e59.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16137/HighFidelity-Beta-PR14637-af65e59.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16137/HighFidelity-Beta-Interface-PR14637-af65e59.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16242/HighFidelity-Beta-PR14637-af65e59.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16242/HighFidelity-Beta-PR14637-af65e59.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16242/HighFidelity-Beta-Interface-PR14637-af65e59.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16242/HighFidelity-Beta-PR14637-af65e59.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16242/HighFidelity-Beta-Interface-PR14637-af65e59.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS

image

**Pull request merged**
