### PR TITLE
Move "away" animation from S3 bucket to local resource

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Put away animation into compiled animation resource and update script to use local resource path.

https://highfidelity.atlassian.net/browse/DEV-2537

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by DouglasWilcox** [comment]
TEST NOTES:
You can't see yourself when you hit esc and go "away", so you'll need to buddy up and get someone to watch and verify that you do NOT tpose during away state, but do play the "looking at phone and texting" animation.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22655/HighFidelity-Beta-PR16523-b8d7f50.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22655/HighFidelity-Beta-Interface-PR16523-b8d7f50.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22655/HighFidelity-Beta-PR16523-b8d7f50.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22655/HighFidelity-Quest-Beta-PR16523-b8d7f50.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22655/HighFidelity-Beta-PR16523-b8d7f50.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22655/HighFidelity-Beta-Interface-PR16523-b8d7f50.exe

**Pull request merged**
