### PR TITLE
Fix non self-sufficient headers.

### PR DESCRIPTION
**Pull request by Atlante45**
Code health
No QA needed

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15816/HighFidelity-Beta-PR14551-d179b91.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15816/HighFidelity-Beta-PR14551-d179b91.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15816/HighFidelity-Beta-Interface-PR14551-d179b91.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15816/HighFidelity-Beta-PR14551-d179b91.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15816/HighFidelity-Beta-Interface-PR14551-d179b91.exe

**Comment by antoninahifi** [comment]
smoke check passed

**Pull request merged**
