### PR TITLE
Leopoly

### PR DESCRIPTION
**Pull request by sethalves**
pull from upstream

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 515ceeaa781bb00f278f20ee0018fcca0b1c40f9 available at: https://gist.github.com/37eb09f98f0b99867cf4ed3ad9475557<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 515ceeaa781bb00f278f20ee0018fcca0b1c40f9 available at: https://gist.github.com/37eb09f98f0b99867cf4ed3ad9475557<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.dmg

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 515ceeaa781bb00f278f20ee0018fcca0b1c40f9 available at: https://gist.github.com/37eb09f98f0b99867cf4ed3ad9475557<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 515ceeaa781bb00f278f20ee0018fcca0b1c40f9 available at: https://gist.github.com/37eb09f98f0b99867cf4ed3ad9475557<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9090-515ceea.dmg

**Pull request merged**
