### PR TITLE
fix for injector restart not restarting

### PR DESCRIPTION
**Pull request by birarda**
- fixed an issue where an injector would not restart from the beginning when `restart()` was called

### CODE REVIEW

**Comment by birarda** [comment]
**Testing**

Run the script below. You should hear the speech restart from the beginning each time and stops and is restarted. On master, it will think it was behind the previous position and start at a different point in the clip.

```
var testSound = {
    url: "http://hifi-public.s3.amazonaws.com/birarda/speech.wav",
    audioOptions: {
        position: { x: 0, y: 0, z: 0 },
        volume: 1.0,
        loop: false
    }
};

var speech = SoundCache.getSound(testSound.url);
var injector = null;

speech.ready.connect(function(){
    injector = Audio.playSound(speech, testSound.audioOptions);
});

// every 2 seconds stop or start the clip
// if broken it won't restart in the right place
Script.setInterval(function() {
    if (injector) {
        if (injector.isPlaying) {
            injector.stop();
        } else {
            injector.restart();
        }
    }
}, 2 * 1000);
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3028606c5ae844ac8388ecc1f92ec716a476abe available at: https://gist.github.com/3ea6033bc0cbe6cb1978<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6986.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6986.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7990bf88af976a3c9fbe7afe3080988ee5cf5bd available at: https://gist.github.com/3ea6033bc0cbe6cb1978<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6986.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6986.dmg

**Comment by huffman** [comment]
Tested and working

**Pull request merged**
