### PR TITLE
Hifi 2 20069

### PR DESCRIPTION
**Pull request by MarcelEdward**
From https://github.com/highfidelity/hifi/pull/5351

Somehow I could not get the merge conflict out and somehow cannot go back to a previous a faulty commit

For now without a merge conflict. 

Updated the menu name.

Still have to look at the fast zooming and yaw on windows, probably have to add a var to prevent the button changes to be pushed to fast. Not sure why the yaw thing does not always work, could be that the position is also send at the same time and the input mapper does not not process all those synchronical. Probably will have to do something with masking the postion when the rotation is set for yaw.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by MarcelEdward** [comment]
ok to test

**Comment by murillodigital** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32d051396262b35956d1cf8b545744ac49861266 available at: https://gist.github.com/29a54dd454cd908db9d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34d63cdb43eceef33bd8ed4b66e06aae698ec2d1 available at: https://gist.github.com/29a54dd454cd908db9d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.dmg

**Comment by SamGondelman** [comment]
Working great!  Try to fix up some of the style issues Andrew had mentioned in case those changes were undone.  I still see some tabs.  Almost there!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d29fb9d7f9b2c482a352881cb6595904671e657 available at: https://gist.github.com/29a54dd454cd908db9d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5435.dmg

**Comment by AndrewMeadows** [comment]
This PR has been reconstructed a few times which is unfortunate because the previous comments are now obfuscated.  @MarcelEdward if you need some help resolving git conflicts or tips on how to minimize them with git best practices I can probably help you out.

There are still a few tabs and some strange Hungarian notation dialect going on for some class data members but it I'll just merge and clean it up myself.

**Comment by AndrewMeadows** [comment]
For posterity the worklist item is here:  https://worklist.net/20069

**Pull request merged**
