### PR TITLE
Updates to the Calibration UI

### PR DESCRIPTION
**Pull request by druiz17**
The PR make some visual changes the were requested and made sure you can not select the shoulder and chest trackers at the same time.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- goto to menu > settings > controllerSettings
1. 
- make sure that you can not have the shoulder and chest options clicked at the same time.
2.
- select any configuration and press the calibrate button.
- check that the T-Pose avatar glyph has its feet together.
3. 
- go back to the main page and click on the text that says "See Recommended Tracker Placement...new page should pop up showing an image of where to place the vive tracker.
- click on the X button to close the page.

**Comment by YuppyPlays** [comment]
Will test once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1384/HighFidelity-Beta-PR10899-6e1f9d275cc6a741a6eb54f9bdc14d1a491bfc47.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1384/HighFidelity-Beta-PR10899-6e1f9d275cc6a741a6eb54f9bdc14d1a491bfc47.dmg

**Comment by YuppyPlays** [comment]
Testing~

**Comment by YuppyPlays** [comment]
Testing complete:

Can confirm all steps in test plan work as expected. **Pass**

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1389/HighFidelity-Beta-PR10899-9e4b5693c744340ad31bb60231a877567257004d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1389/HighFidelity-Beta-PR10899-9e4b5693c744340ad31bb60231a877567257004d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1402/HighFidelity-Beta-PR10899-1fcb3b32d60e921776f824529e9b4bd1b3030887.dmg

**Comment by druiz17** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1408/HighFidelity-Beta-PR10899-1fcb3b32d60e921776f824529e9b4bd1b3030887.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1408/HighFidelity-Beta-PR10899-1fcb3b32d60e921776f824529e9b4bd1b3030887.dmg

**Pull request merged**
