### PR TITLE
Emphasize mute state with red

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
@AlanZimmerman's QA should be sufficient.

- Check that the checkbox in the audio menu is red when muted.
- Check tablet and toolbar icons in active/inactive mute/muted states.

**Comment by CainFoool** [comment]
Hey @zzmp: Is this QA Ready once it's built?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/870/HighFidelity-Beta-PR10746-7512332104f3ac3351201401b39f58f0d3f1dc3b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/870/HighFidelity-Beta-PR10746-7512332104f3ac3351201401b39f58f0d3f1dc3b.dmg

**Comment by zzmp** [comment]
@CainFoool: @AlanZimmerman is going to QA this one - changes are minimal and it is just to ensure the design is correct.

**Comment by CainFoool** [comment]
@zzmp: Ah okay no worries - was confused by the first comment you left, thought it was steps provided by Alan.

**Comment by AlanZimmerman** [comment]
PR looks good. Tested on Toolbar and Tablet and button icons appear with the correct color in all states.

**Pull request merged**
