### PR TITLE
CR for Job #21671 - Window.copyToClipboard() doesn't work in .js files

### PR DESCRIPTION
**Pull request by mnafees**
Code Review for Job #21671 - Workitem available at https://www.worklist.net/21671

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6278/app_12171_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6278/HighFidelity-Beta-PR12171-8d343b4d768d5bd338645fa482b9655fe17e7623.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6278/HighFidelity-Beta-PR12171-8d343b4d768d5bd338645fa482b9655fe17e7623.dmg

**Comment by themelissabrown** [comment]
Does this need a test plan?

**Comment by mnafees** [comment]
@themelissabrown Ah, my bad. Adding the test plan now.

**Comment by mnafees** [comment]
## Test plan
- Create a JS file with the contents `Window.copyToClipboard("test");`
- Open the script in interface
- Try to paste the clipboard text anywhere and "test" should be pasted

**Comment by MiladNazeri** [comment]
@mnafees  Hi, just added on the worklist, but adding here just incase.

Can we tack on these two that basically need the same implementation used here?

location.copyAddress() and location.copyPath()

**Comment by mnafees** [comment]
@MiladNazeri On it :)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6325/app_12171_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6326/app_12171_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6326/HighFidelity-Beta-PR12171-885801c5ca7e19ead63880112ebc672d7e2c787a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6326/HighFidelity-Beta-PR12171-885801c5ca7e19ead63880112ebc672d7e2c787a.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12171. PASSED

**Pull request merged**
