### PR TITLE
Zip file structures replicated in asset server

### PR DESCRIPTION
**Pull request by elisa-lj11**
Other minor changes: URL in Blocks app updated to Poly, updated an unzip debug print

Test plan:
1. Download https://hifi-content.s3.amazonaws.com/elisalj/blocks/lego_obj.zip
2. Open Interface, then open the asset browser (Ctrl + Shift + A)
3. Drag "lego_obj.zip" into Interface
4. The model should load in front of you (ignore the lack of textures)
5. Check that in the asset browser there is a "lego_obj" folder; expanding it should reveal a hierarchical file structure that matches what's inside lego_obj.zip
6. Delete "lego_obj" from the asset server
7. Load "Blocks" from the marketplace and open
8. Search for "Lego Moon Buggy" and select this: https://poly.google.com/view/8kSHCCK66fa
9. Download the obj for that; the model should still appear in front of you with no textures
10. Check in the asset browser for a file "8kSHC...", it should have the same file structure as "lego_obj"

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5063/HighFidelity-Beta-PR11849-be0d4646fac4e3fcdd0e45a88ae78e6a3510d479.exe

**Comment by elisa-lj11** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5093/HighFidelity-Beta-PR11849-be0d4646fac4e3fcdd0e45a88ae78e6a3510d479.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5093/HighFidelity-Beta-PR11849-be0d4646fac4e3fcdd0e45a88ae78e6a3510d479.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Download https://hifi-content.s3.amazonaws.com/elisalj/blocks/lego_obj.zip | Pass
Open Interface, then open the asset browser (Ctrl + Shift + A) | Pass
Drag "lego_obj.zip" into Interface | Pass
The model should load in front of you (ignore the lack of textures) | Pass
Check that in the asset browser there is a "lego_obj" folder; expanding it should reveal a hierarchical file structure that matches what's inside lego_obj.zip | Pass
Delete "lego_obj" from the asset server | Pass (Kept solely for screenshot purposes)
Load "Blocks" from the marketplace and open | Pass
Search for "Lego Moon Buggy" and select this: https://poly.google.com/view/8kSHCCK66fa | Pass
Download the obj for that; the model should still appear in front of you with no textures | Pass
Check in the asset browser for a file "8kSHC...", it should have the same file structure as "lego_obj" | Pass

interface_2017-11-20_15-00-30

**Comment by misslivirose** [comment]
@elisa-lj11 - I think the test plan should also include non-Blocks import confirmation of expected behavior

**Comment by elisa-lj11** [comment]
New test plan (now with non-blocks zip file):

1. Download https://hifi-content.s3.amazonaws.com/elisalj/blocks/lego_obj.zip and https://hifi-content.s3.amazonaws.com/elisalj/blocks/testing/top_dir.zip
2. Open Interface, then open the asset browser (Ctrl + Shift + A)
3. Drag "lego_obj.zip" into Interface
4. The model should load in front of you (ignore the lack of textures)
5. Check that in the asset browser there is a "lego_obj" folder; expanding it should reveal a hierarchical file structure that matches what's inside lego_obj.zip
6. Drag "top_dir.zip" into Interface
7. Check that the asset browser's file structure for top_dir matches that of the original .zip
8. Load "Blocks" from the marketplace and open
9. Search for "Lego Moon Buggy" and select this: https://poly.google.com/view/8kSHCCK66fa
10. Download the obj for that; the model should still appear in front of you with no textures
11. Check in the asset browser for a file "8kSHC...", it should have the same file structure as "lego_obj"

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5096/HighFidelity-Beta-PR11849-ecd45534dd7641e258b74499b4f0d91b0b231ce1.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5102/HighFidelity-Beta-PR11849-fb6287503edbf70e7f443ee6da9a4832b93c3ff5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5102/HighFidelity-Beta-PR11849-fb6287503edbf70e7f443ee6da9a4832b93c3ff5.dmg

**Comment by cain-kilgore** [comment]
Testing with new steps.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Download https://hifi-content.s3.amazonaws.com/elisalj/blocks/lego_obj.zip and https://hifi-content.s3.amazonaws.com/elisalj/blocks/testing/top_dir.zip | Pass
Open Interface, then open the asset browser (Ctrl + Shift + A) | Pass
Drag "lego_obj.zip" into Interface | Pass
The model should load in front of you (ignore the lack of textures) | Pass
Check that in the asset browser there is a "lego_obj" folder; expanding it should reveal a hierarchical file structure that matches what's inside lego_obj.zip | Pass
Drag "top_dir.zip" into Interface | Pass
Check that the asset browser's file structure for top_dir matches that of the original .zip | Pass
Load "Blocks" from the marketplace and open | Pass
Search for "Lego Moon Buggy" and select this: https://poly.google.com/view/8kSHCCK66fa | Pass
Download the obj for that; the model should still appear in front of you with no textures | Pass
Check in the asset browser for a file "8kSHC...", it should have the same file structure as "lego_obj" | Pass

All good, even with the new steps.

**Pull request merged**
