### PR TITLE
Update master from stable

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
@sethalves 3 of your commits above were merged directly into stable.
Did they also make their way into master?
Should this PR have changes that need to be pulled back to master?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2911/HighFidelity-Beta-PR11277-9de4c3d0aface85877d49a08a1873d3c5636d5ef.exe

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2918/HighFidelity-Beta-PR11277-9de4c3d0aface85877d49a08a1873d3c5636d5ef.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2918/HighFidelity-Beta-PR11277-9de4c3d0aface85877d49a08a1873d3c5636d5ef.dmg

**Pull request merged**
