### PR TITLE
Local velocity for scripts

### PR DESCRIPTION
**Pull request by sethalves**
- local velocities are now more correctly translated between local and world frames for scripts
- when something is unequipped by being pulled away from your hand, it can then be thrown.

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- general testing of handControllerGrab.js
- equip something, use your free hand to pull it away from the equipping hand, and give the thing a toss
- previously, it would be released with no velocity, now it will act as expected.

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1400/when-auto-unequipping-by-pulling-something-away-with-your-other-hand-the-entity-gets-no-velocity-when-thrown

**Comment by hifi-gustavo** [comment]
Build console output for commit: f5f88fbacc35c56651c1f61865e18d6e4505dc40 available at: https://gist.github.com/6a4daaa0cebdefe16aef10353678f8ef<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8446-f5f88fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8446-f5f88fb.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: Success
**Additional Test Results + Observations**:  Tested of handControllerGrab.js equipped several items in ```dev-demo```, where I used my free hand to pull several items away from my equipping hand, and give each items a toss as there was velocity and natural physical response.

**Pull request merged**
