### PR TITLE
Disable AO in mini mirror

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
@samcake this PR is in response to https://app.asana.com/0/74051501495175/83359467372418, but I don't understand how AO is broken. Can you explain it? This simply turns it off in the mini mirror.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2036b8362cc8da2551eeebee3350a29a43eddb53 available at: https://gist.github.com/2797e2d6c3ee34550942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7081.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7081.dmg

**Comment by zzmp** [comment]
#### Testing
Make sure Ambient Occlusion does not affect the mini mirror.

##### Before
Ambient occlusion was on in the mini mirror. Sometimes it looked bad. No need to confirm that it looked bad.
##### Now
Ambient occlusion is off in the mini mirror. It should have no effect.

**Comment by ZappoMan** [comment]
So apparently this doesn't do the trick. It appears as if the AO is actually operating on top of the mini mirror... we may need to do some kind of a stencil to prevent the AO from rendering on top of the mirror.

ao-mini-mirror

**Comment by zzmp** [comment]
@ZappoMan thanks for the screenshots - I'll try again knowing what to test for.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d516e9da78581ae4e15cb3976dad915a9024fde6 available at: https://gist.github.com/2797e2d6c3ee34550942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7081.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7081.dmg

**Comment by cozza13** [comment]
tested and it works

**Pull request merged**
