### PR TITLE
Fix Stylus in Tablet + Grab with Hand Results in the other Stylus being Dysfunctional

### PR DESCRIPTION
**Pull request by druiz17**
Fix Stylus in Tablet + Grab with Hand Results in the other Stylus being Dysfunctional

- ticket that this PR fixes - https://highfidelity.fogbugz.com/f/cases/8353

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1. At the edge of the tablet, put your left stylus into the tablet
2. While your stylus is in the tablet, grab the tablet with the same hand
3. While still grabbing the tablet, you should be able to interact with the tablet with your right stylus

perform the test with the other hand.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4121/HighFidelity-Beta-PR11587-6799b9ca13996ceed554206f8bcc386f535d6981.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4121/HighFidelity-Beta-PR11587-6799b9ca13996ceed554206f8bcc386f535d6981.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

At the edge of the tablet, put your left stylus into the tablet **Check, tried this at edge of tablet itself and edge of screen on the tablet for good measure**
While your stylus is in the tablet, grab the tablet with the same hand **Check**
While still grabbing the tablet, you should be able to interact with the tablet with your right stylus **Check**
perform the test with the other hand. **Check**

**Pass** I personally cannot find any issues unless the stylus touching the screen when letting go is considered an issue, but to be honest that to me makes sense for the tablet to do overall.

**Pull request merged**
