### PR TITLE
CR 21190 unit_tests: add support for jasmine.done() and pending

### PR DESCRIPTION
**Pull request by humbletim**
This PR updates the jasmine Client unit tests to:

* Make jasmine `done()` usable (per FIXME).
* Include disabled tests in reported results (jasmine refers to these as "pending" tests).
* Activate `avatarUnitTests.js`

These changes make it possible to use jasmine's `done()` callback feature to create async Client tests that depend on future events (like waiting for a model to load).  And also to more safely leverage the prefixed `xdescribe()` / `xit()` functions for pre-staging or temporarily disabling tests.  The avatarUnitTests were apparently disabled at some point while awaiting `done()` support.

#### Testing testRunner.js 
* Run this PR's Interface
* Launch `Developer -> Tests -> Run Client Script Tests`
* The Test results should include:
  * a passing `jasmine internal test` group
  * (as part of final report lines) a yellow "disabled test:" entry

*note: for purposes of testing this PR it is OK if some of the `Avatar` and `Entities` unit tests fail*

--------

image

### CODE REVIEW

**Comment by humbletim** [comment]
ps: it's also possible to test on current builds by opening the Console... and running:
```javascript
Script.include('https://raw.githubusercontent.com/humbletim/hifi/21190-fix-unit-tests/scripts/developer/tests/unit_tests/testRunner.js');
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30b7ee3b50e493da4879fd383c969cefd982591e available at: https://gist.github.com/262df508e12a85ee562587ec766a17bb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-30b7ee3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-30b7ee3.dmg

**Comment by OmegaHeron** [comment]
Will be testing this, per request, in a few hours.

**Comment by OmegaHeron** [comment]
Tested Windows 10

QA Fail for now as it's a 100% crash while running test.

Test ran from standard sandbox (this PR) at default location.

First attempt, crashed after requesting test run.
Second attempt, crashed loading sandbox (standard scene) - I see it trying to load stylized_female.fbx (That seems to come from Run Client Script Tests).
Each subsequent load of interface results in crash until settings are reset or one catches running scripts window quickly enough to remove test script that's added by devel menu test option.

Multiple bugsplat reports sent.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 524806b2d99568f68b12b790d169ccee5fce05f4 available at: https://gist.github.com/262df508e12a85ee562587ec766a17bb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-524806b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-524806b.dmg

**Comment by humbletim** [comment]
Wow, sounds like activating that dormant avatar test is hitting a lurking edge case somewhere.
 
Maybe the avatar model it uses crashes Interface on Windows in general?  https://hifi-metaverse.s3-us-west-1.amazonaws.com/marketplace/contents/e76946cc-c272-4adf-9bb6-02cde0a4b57d/8fd984ea6fe1495147a3303f87fa6e23.fst?1460131758

This PR contains only JavaScript changes, but I've just rebased onto RELEASE-6106 / Beta 35 (before the PR build reflected whatever was current as of master c9c04a9a).

Please retest -- and if it still crashes could file a new bug report against Beta 35 using this PR or the avatar model as a reproducible test case.

**Comment by OmegaHeron** [comment]
Re-testing and will grab that avatar to rez in on master to see what happens.

**Comment by OmegaHeron** [comment]
Using Master (6134) loaded test av manually and it rezzed into scene with no issue.
Using this PR loaded test av manually, same as above.

Test also now runs without crashing... maybe was a bad merge or something before rebase.

I think a possible issue that may lead to unexpected behavior is how the avatar test expects the av to load in a fairly short time... if it's in cache it's sort of reasonable, if not then it's nowhere near long enough to load that AV from Amazon source.  It's taking more like 30-50 seconds vs 10 to load.  Once I manually loaded AV insuring it's in cache test functions perfectly.



In the former crashy version I would see that timeout but lost it before I could read it or capture its output due to app terminating.

QA Pass - though it's likely the timeout for av unit should be *much* longer.

**Comment by OmegaHeron** [comment]
Test result with model insured in cache.

**Comment by ZappoMan** [comment]
@cozza13 @humbletim @OmegaHeron - what's the status on this PR? are we going to get it fixed/merged? looks like this is a QA pass, but it's got a merge conflict?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c0f6a65b4917b4a1f76d35e635e16d82d46f57f available at: https://gist.github.com/262df508e12a85ee562587ec766a17bb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-4c0f6a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-4c0f6a6.dmg

**Comment by humbletim** [comment]
@ZappoMan resolved the merge conflict.   This PR only impacts developer test scripts living under `/~/developer/unit_tests`; in my estimation it's good to go for merge.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c0f6a65b4917b4a1f76d35e635e16d82d46f57f available at: https://gist.github.com/262df508e12a85ee562587ec766a17bb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-4c0f6a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9735-4c0f6a6.dmg

**Pull request merged**
