### PR TITLE
Add missing line3d overlay property getters and setters

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Inspect and run the attached script. Test and expected results are written to the program log. Confirm that the expected results are obtained.

[testLine3D.zip](https://github.com/highfidelity/hifi/files/1511780/testLine3D.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5223/HighFidelity-Beta-PR11891-b9ad15b19ee9a8206b064b2410ac22cb7b393d62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5223/HighFidelity-Beta-PR11891-b9ad15b19ee9a8206b064b2410ac22cb7b393d62.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
```
[11/29 13:45:32] [INFO] [hifi.scriptengine] [testLine3D.js] Script Engine starting:testLine3D.js
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] $$$$$$$ Test missing property setters for "p1" and "p2"...
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] ....... Start points (should be identical): {"x":-2.5030908584594727,"y":-10.34804916381836,"z":7.636567115783691} ; {"x":-2.5030908584594727,"y":-10.34804916381836,"z":7.636567115783691} ; {"x":-2.5030908584594727,"y":-10.34804916381836,"z":7.636567115783691}
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] ....... End points (should be identical): {"x":-4.503029823303223,"y":-10.34804916381836,"z":7.620947360992432} ; {"x":-4.503029823303223,"y":-10.34804916381836,"z":7.620947360992432} ; {"x":-4.503029823303223,"y":-10.34804916381836,"z":7.620947360992432}
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] $$$$$$$ Test missing property getters for "endParentID", "endParentJointIndex", and "glow"...
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] ....... endParentID: {b12bc197-dab7-410d-88f6-30b9c9bdfa4d} ; should be: {b12bc197-dab7-410d-88f6-30b9c9bdfa4d}
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] ....... endParentJointIndex: 2 ; should be: 2
[11/29 13:45:32] [DEBUG] [hifi.scriptengine.script] [testLine3D.js] ....... glow: 0.4000000059604645 ; should be: 0.4
```

Prints out the expected results.

**Pull request merged**
