### PR TITLE
Adding handshake control to image in Controls Reference

### PR DESCRIPTION
**Pull request by alexiamandeville**
tablet-help-keyboard

Updating image in controls to reflect handshake in the keyboard controls.

Test plan :
Open Help > Controls Reference
Make sure Keyboard + Mouse image has handshake button

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13042/HighFidelity-Beta-PR14012-5c9d316.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13042/HighFidelity-Beta-PR14012-5c9d316.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13042/HighFidelity-Beta-Interface-PR14012-5c9d316.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13042/HighFidelity-Beta-PR14012-5c9d316.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13042/HighFidelity-Beta-Interface-PR14012-5c9d316.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
PASS @Conklin94122 Handshake control image is visible in Controls Reference

**Comment by qlihifitest** [comment]
PASS @conklin94122 Handshake control image is visible in Controls Reference

**Comment by qligmaloney** [comment]
Build this please

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13999/HighFidelity-Beta-PR14012-5c9d316.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13999/HighFidelity-Beta-PR14012-5c9d316.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13999/HighFidelity-Beta-Interface-PR14012-5c9d316.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13999/HighFidelity-Beta-PR14012-5c9d316.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13999/HighFidelity-Beta-Interface-PR14012-5c9d316.exe

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
