### PR TITLE
DO NOT MERGE - test build for testing DEV-360

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20890/HighFidelity-Beta-PR16064-4287dfc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20890/HighFidelity-Beta-Interface-PR16064-4287dfc.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20895/HighFidelity-Beta-PR16064-4287dfc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20895/HighFidelity-Quest-Beta-PR16064-4287dfc.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20895/HighFidelity-Beta-PR16064-4287dfc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20895/HighFidelity-Beta-Interface-PR16064-4287dfc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20895/HighFidelity-Beta-PR16064-4287dfc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20895/HighFidelity-Beta-Interface-PR16064-4287dfc.exe

**Pull request closed without merging**
