### PR TITLE
68.1: Fix avatarHash crash

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/13339

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10843/HighFidelity-Beta-PR13447-01d676b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10843/HighFidelity-Beta-PR13447-01d676b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10843/HighFidelity-Beta-Interface-PR13447-01d676b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10843/HighFidelity-Beta-PR13447-01d676b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10843/HighFidelity-Beta-Interface-PR13447-01d676b.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No crash

**Pull request merged**
