### PR TITLE
base palm position on finger joint rather than an offset from hand joint

### PR DESCRIPTION
**Pull request by sethalves**
- base palm position on finger joint rather than an offset from hand joint
- double size of near-grab sphere

### CODE REVIEW

**Comment by sethalves** [comment]
To test -- grab small things with handControllerGrab.js.  See if the small things need to be in front of the avatar's hand to be grabbed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e69c12e87c1eb20d38cf5cdb80200e252bfb889 available at: https://gist.github.com/36d70148472a31ba7758<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7012.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7012.dmg

**Comment by nbq** [comment]
Testing this one

**Comment by nbq** [comment]
I have tested and I say it PASSED. I checked and small things do need to be in front of the hand to be picked up, I tested with multiple small objects. I also put two small items side by side and then used the hand to pick it up, each time it only picked up the object my hand was facing.

**Pull request merged**
