### PR TITLE
aim reticle at head

### PR DESCRIPTION
**Pull request by howard-stearns**
Change how mouse reticle is oriented in HMD.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
Make the mouse visible in hmd by moving it (leaving hand controllers off, or at least still on stable desk). As you move your head around within the HUD sphere, the reticle should look reasonable.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e4dbb5e61a8ff9fd69f9a78039bb8ec95eb51f61 available at: https://gist.github.com/07b61a475fc0dda17943c366925a8d48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8120.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8120.dmg

**Comment by thoys** [comment]
## Test results

I have had the symptoms of the angled/twisted cursor (offset sphere) before. I am unable to reproduce it in this build. I have tried to switch between HMD and desktop mode several times, and it all looked good.

:+1: QA Passed

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bhW9Dn9p&#x2F;73-reticle-gets-stuck-at-lookat"> reticle gets stuck at lookAt</a>

**Pull request merged**
