### PR TITLE
BUGZ-173: Fix deadlock on startup

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.atlassian.net/browse/BUGZ-173

Test plan:
- You won't deadlock on startup

### CODE REVIEW

**Comment by hyperlogic** [comment]
Introduced inadvertently with #15542

**Comment by SamGondelman** [comment]
build this please

**Comment by SamGondelman** [comment]
BUILD THIS PLEASE YOU GARBAGE ROBOT

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19398/HighFidelity-Beta-PR15548-652ac17.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19398/HighFidelity-Quest-Beta-PR15548-652ac17.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19398/HighFidelity-Beta-PR15548-652ac17.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19398/HighFidelity-Beta-Interface-PR15548-652ac17.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19406/HighFidelity-Beta-PR15548-652ac17.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19406/HighFidelity-Quest-Beta-PR15548-652ac17.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19406/HighFidelity-Beta-PR15548-652ac17.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19406/HighFidelity-Beta-Interface-PR15548-652ac17.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19406/HighFidelity-Beta-PR15548-652ac17.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19406/HighFidelity-Beta-Interface-PR15548-652ac17.exe

**Pull request merged**
