### PR TITLE
Agent needs to be sure audio is ready before trying to use it

### PR DESCRIPTION
**Pull request by davidkelly**
Seems we just forgot to check it here.

### CODE REVIEW

**Comment by davidkelly** [comment]
Fixes https://highfidelity.manuscript.com/f/cases/assign/20032/Agent-crash-in-processAgentAvatarAudio-Only-affects-bots?ixPersonAssignedTo=60

Hard to test - we need to run bots in a domain, and just notice it doesn't happen but sounds still comes out.  Thing is, I'm not sure exactly how this was triggered (specific bot script with specific sound files, etc...)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15940/HighFidelity-Beta-PR14577-2b21ceb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15940/HighFidelity-Beta-PR14577-2b21ceb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15940/HighFidelity-Beta-Interface-PR14577-2b21ceb.dmg

**Comment by howard-stearns** [comment]
Depending on availability, I'm not sure that we have to do a whole bot test on this -- maybe just smoke it. But... if we have the time, this is as good a chance as any to learn how to run bots: see https://highfidelity.atlassian.net/wiki/spaces/NT/pages/437747722/Concurrency+Validation

However, on the third hand sadly, see 
https://highfidelity.fogbugz.com/f/cases/20173/AC-running-a-Persistent-Script-frequently-crashes-upon-DS-restart and 
https://highfidelity.fogbugz.com/f/cases/20106/AC-agents-spawned-with-n-don-t-come-back-with-the-expected-amount-after-a-domain-restart, which do want to fix this sprint, but which do not yet have fixes and will effect such bot testing.

**Comment by qlilaseguinolaza** [comment]
I smoke tested this PR and everything appears to be functioning correctly.

**Pull request merged**
