### PR TITLE
Remove checking of empty model url and add sanity for checking modelU…

### PR DESCRIPTION
**Pull request by vladest**
…rl field existing
https://highfidelity.fogbugz.com/f/cases/9080/Avatar-attachments-dialog-NEW-ATTACHMENT-button-not-working

Test plan:
- open menu Avatar -> Attachments
- press New Attachment button
- make sure new attachment added

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by Nex-Pro** [comment]
@vladest thanks for jumping on this one so quickly.

**Comment by vladest** [comment]
@Nex-Pro no problems. It seems its long standing issue

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4774/HighFidelity-Beta-PR11773-6685b74c2a9e73a6e7a19e52e02842ee5cd50fd9.dmg

**Comment by Nex-Pro** [comment]
@vladest I was surprised when I filed it that it wasn't a duplicate on fogbugz.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4774/HighFidelity-Beta-PR11773-6685b74c2a9e73a6e7a19e52e02842ee5cd50fd9.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

open menu Avatar -> Attachments **Check**
press New Attachment button **Check**
make sure new attachment added **Check**

This is a solid **Pass** Glad to see this get fixed as I had this pop up when testing a separate PR, good work :)

**Pull request merged**
