### PR TITLE
DOC-209: AudioStats JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- AudioStats

Classes:
- AudioStreamStats

Case: https://highfidelity.atlassian.net/browse/DOC-209

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22545/HighFidelity-Beta-PR16495-ef45a60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22545/HighFidelity-Quest-Beta-PR16495-ef45a60.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22545/HighFidelity-Beta-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22545/HighFidelity-Beta-Interface-PR16495-ef45a60.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22575/HighFidelity-Beta-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22575/HighFidelity-Beta-Interface-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22575/HighFidelity-Beta-PR16495-ef45a60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22575/HighFidelity-Quest-Beta-PR16495-ef45a60.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22580/HighFidelity-Beta-PR16495-ef45a60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22580/HighFidelity-Quest-Beta-PR16495-ef45a60.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22580/HighFidelity-Beta-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22580/HighFidelity-Beta-Interface-PR16495-ef45a60.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22593/HighFidelity-Beta-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22593/HighFidelity-Beta-Interface-PR16495-ef45a60.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22593/HighFidelity-Beta-PR16495-ef45a60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22593/HighFidelity-Quest-Beta-PR16495-ef45a60.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22593/HighFidelity-Beta-PR16495-ef45a60.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22593/HighFidelity-Beta-Interface-PR16495-ef45a60.exe

**Pull request merged**
