### PR TITLE
Update stylus touch hysteresis values

### PR DESCRIPTION
**Pull request by SamGondelman**
Updated based on testing with Mukul to improve stylus interaction.

Test plan:
- Use the stylus on the tablet.  "Press" and "release" behavior should happen much closer to the surface.  Change was very minimal so no need to fully test tablet functionality, just the distance at which you click.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5587/HighFidelity-Beta-PR11966-ce96fa70788bbce962f4e2d53bfc9ad7f00f2bfc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5587/HighFidelity-Beta-PR11966-ce96fa70788bbce962f4e2d53bfc9ad7f00f2bfc.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Failed** - I cannot even get the stylus to register tapping the tablet, having same issue I experienced in #11964 and I believe me & Cain also got it in #11833 previously.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5638/HighFidelity-Beta-PR11966-4fbf5db6977d62711191e451fa0e0b9e9106f503.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5638/HighFidelity-Beta-PR11966-4fbf5db6977d62711191e451fa0e0b9e9106f503.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Use the stylus on the tablet. "Press" and "release" behavior should happen much closer to the surface.  | 👍 

Looks good to me - feels much more natural IMO.

**Pull request merged**
