### PR TITLE
JSDoc updates

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Updates the JavaScript API JSDoc for:
- Camera
- Clipboard
- Menu
- Paths
- PickRay
- StylusTip
- Uuid
- ViewFrustum

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4833/HighFidelity-Beta-PR11791-036ac8de6d750a23e0dd26ba7e16d01e009c4190.dmg

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4836/HighFidelity-Beta-PR11791-036ac8de6d750a23e0dd26ba7e16d01e009c4190.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4836/HighFidelity-Beta-PR11791-036ac8de6d750a23e0dd26ba7e16d01e009c4190.exe

**Comment by ctrlaltdavid** [comment]
**Test Plan**

- Check importing of entities still works.

**Comment by YuppyPlays** [comment]
Awaiting latest build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4845/HighFidelity-Beta-PR11791-c77a12f5fa5c0af32248ec58086ba6bdb0e72ea2.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4847/HighFidelity-Beta-PR11791-c77a12f5fa5c0af32248ec58086ba6bdb0e72ea2.dmg

**Comment by YuppyPlays** [comment]
@ctrlaltdavid  I think Gustavo is drunk.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4849/HighFidelity-Beta-PR11791-c77a12f5fa5c0af32248ec58086ba6bdb0e72ea2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4849/HighFidelity-Beta-PR11791-c77a12f5fa5c0af32248ec58086ba6bdb0e72ea2.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Tested  some .jsons I had lying around, acted the same with each as it does in Master 7360, all good :) **Pass**

**Comment by ctrlaltdavid** [comment]
No new executable code changes so doesn't need to be re-QA'd.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4866/HighFidelity-Beta-PR11791-dba16c265c17c9de6b26e4e2a30e3fd761db5cad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4866/HighFidelity-Beta-PR11791-dba16c265c17c9de6b26e4e2a30e3fd761db5cad.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4871/HighFidelity-Beta-PR11791-9c5149733d7e4a623e50f1f19b8e998ea1af73f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4871/HighFidelity-Beta-PR11791-9c5149733d7e4a623e50f1f19b8e998ea1af73f3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4883/HighFidelity-Beta-PR11791-fb550d59f0f19e0d48aab305f8386fa7738cf698.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4883/HighFidelity-Beta-PR11791-fb550d59f0f19e0d48aab305f8386fa7738cf698.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4991/HighFidelity-Beta-PR11791-6f820490210eda2835f844198650e9f37baa630e.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5002/HighFidelity-Beta-PR11791-6f820490210eda2835f844198650e9f37baa630e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5002/HighFidelity-Beta-PR11791-6f820490210eda2835f844198650e9f37baa630e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5151/HighFidelity-Beta-PR11791-425e2eb82cb8169a5ff20b55b49440e8933519da.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5151/HighFidelity-Beta-PR11791-425e2eb82cb8169a5ff20b55b49440e8933519da.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5251/HighFidelity-Beta-PR11791-4269cc4004e1189808673f96e14e678e102a9d8a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5251/HighFidelity-Beta-PR11791-4269cc4004e1189808673f96e14e678e102a9d8a.exe

**Pull request merged**
