### PR TITLE
Case 22229: Create Grid ignorePickIntersection

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/22229/Create-Grid-is-blocking-mouse-events

Test plan:
- Make a box:
```
var entityID = Entities.addEntity({
    type: "Box",
    position: Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, { x: 0, y: 0, z: -5 })),
    rotation: MyAvatar.orientation,
    script: "https://hifi-content.s3.amazonaws.com/robin/dev/testEntityPrototype.js?5",
    dimensions: { x: 0.5, y: 0.5, z: 0.5 }
}, "local");
```
- Open Create, go to the grid tab, and make the grid visible.  Fly above the box you created and click "Align to Avatar".  The grid should be between you and the box.
- Click on the box.  In the logs, you should see "Pressed entity! Count 0".

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18761/HighFidelity-Beta-PR15401-54d7bde.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18761/HighFidelity-Beta-Interface-PR15401-54d7bde.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18761/HighFidelity-Beta-PR15401-54d7bde.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18761/HighFidelity-Quest-Beta-PR15401-54d7bde.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18763/HighFidelity-Beta-PR15401-54d7bde.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18763/HighFidelity-Beta-Interface-PR15401-54d7bde.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18763/HighFidelity-Beta-PR15401-54d7bde.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18763/HighFidelity-Quest-Beta-PR15401-54d7bde.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18763/HighFidelity-Beta-PR15401-54d7bde.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18763/HighFidelity-Beta-Interface-PR15401-54d7bde.exe

**Pull request merged**
