### PR TITLE
fixes Sam made in my branch while trying to get a mesh to render

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 258e3b901d1a7561a98505b5a5fc7b571f2358de available at: https://gist.github.com/dae7aea559ca77386aba<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4935.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4935.dmg

**Comment by PhilipRosedale** [comment]
This is in the running for "least informative title"  :)

**Comment by sethalves** [comment]
The sad truth: the title accurately indicates my full understanding of the situation.  I would let Sam merge it.  I suspect there are problems; there's some very suspicious memory management.

**Comment by samcake** [comment]
Indead Sam Approves :)

**Pull request merged**
