### PR TITLE
Support the marketplace in QML

### PR DESCRIPTION
**Pull request by jherico**
If you want to try it out, you need to 

* load edit.js from https://raw.githubusercontent.com/jherico/hifi/marketplace/examples/edit.js
* click the marketplace button to show the marketplace dialog
* the marketplace links should now work

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 65cae5221d61b017c5e40529a81e6fcf63b610ad available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by birarda** [comment]
You should be able to add access_token as a query parameter to any requests made against *.highfidelity.io/*.highfidelity.com and be properly authenticated. Then, we should be able to put the user agent back to hide the header.

**Comment by jherico** [comment]
@birarda will try that, but doing so means I have to expose the oauth token to JS, which seems insecure.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fbb37d261e0fc894620bc872ca710b0041308e9d available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76a2332ec49ac5ed80e3d7dabf929a8d6f6b7129 available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc079e9a9994c2401b510d096bbd10c00f81b496 available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 61257aa8b2ffc0e058ccd4c42285177b8cd7c474 available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cd648e7cc80466c090d7bb68e01aafd540106df available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by ZappoMan** [comment]
when I run this PR build, and attempt to load that edit.js URL, I crash with this call stack....

```
 	Qt5Core.dll!0000000060bfb6d2()	Unknown
 	Qt5Core.dll!0000000060bfd15e()	Unknown
 	Qt5Core.dll!0000000060bfced1()	Unknown
>	interface.exe!QObject::connect<void (__cdecl QObject::*)(QObject * __ptr64) __ptr64,void (__cdecl QObject::*)(void) __ptr64>(const QObject * sender, void (QObject *) * signal, const QObject * receiver, void (void) * slot, Qt::ConnectionType type) Line 240	C++
 	interface.exe!QmlWebWindowClass::constructor(QScriptContext * context, QScriptEngine * engine) Line 112	C++
 	Qt5Script.dll!00007ffd919b1d33()	Unknown
 	Qt5Script.dll!00007ffd91937db2()	Unknown
 	Qt5Script.dll!00007ffd91920a50()	Unknown
 	Qt5Script.dll!00007ffd91918c27()	Unknown
 	Qt5Script.dll!00007ffd91918d3d()	Unknown
 	Qt5Script.dll!00007ffd9199abd6()	Unknown
 	Qt5Script.dll!00007ffd9199a59d()	Unknown
 	interface.exe!ScriptEngine::evaluate(const QString & sourceCode, const QString & fileName, int lineNumber) Line 660	C++
 	interface.exe!ScriptEngine::run() Line 684	C++
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0043fddd08e6ad1ae9172f089bbf81bc41517d6f available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by ZappoMan** [comment]
I tested again, it doesn't crash (I assume @jherico fixed something, but since you did `--amend` I can't see the diff to fix it.

The login behavior is very flaky and random. When I first ran the modified edit, there was no login link visible, but I when I clicked to import something, it imported without an issue. But then I switched to HMD mode and could no longer import things, it said I needed to log in, but there was no link to log in. I tried logging in using the "Ctrl+B/Browser" but that didn't seem to correct the marketplace.

Based on this behavior, I don't think we should merge these changes into the default `edit.js` - until we can fix this login behavior. Maybe we should make a second version of `edit.js` that shows the overlay marketplace.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ef77bc46aeab1fb17186855271fd16284da9102 available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Comment by jherico** [comment]
The explicit login should no longer be required.  I've updated the instructions at the top to reflect this.  Links should always work as long as you're logged in to the application.

**Comment by ZappoMan** [comment]
This still doesn't seem to work for me... I get "login required" in the Marketplace.

marketplace-requires-login

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95c524fba1c2e4b78f28991be507a475a8b2e7af available at: https://gist.github.com/4380c7ed32af8190fa1c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6687.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6687.dmg

**Pull request merged**
