### PR TITLE
Fix MS18608: Use new connections api endpoint

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS18608](https://highfidelity.fogbugz.com/f/cases/18608/something-s-wrong-with-kerry-s-location-in-people).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13469/HighFidelity-Beta-PR14111-59eabbb.apk

**Comment by howard-stearns** [comment]
**Test Plan**:
PAL connections tab regressions, please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13469/HighFidelity-Beta-PR14111-59eabbb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13469/HighFidelity-Beta-Interface-PR14111-59eabbb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13469/HighFidelity-Beta-PR14111-59eabbb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13469/HighFidelity-Beta-Interface-PR14111-59eabbb.exe

**Comment by rickcarr044** [comment]
Currently testing PR14111

**Comment by rickcarr044** [comment]
FAIL @conklin94122

Did not see the original problem where the names were not appearing as expected in the PAL list of connections.

Did find a reproducible error with this PR where two users are connected (As Friends).  When User A leaves a public domain and goes to serverless home, the Location link to the public domain remains in User B's Connections list.  

MS ticket = 19081
https://highfidelity.manuscript.com/f/cases/19081/People-Connections-list-Connection-to-domain-remains-in-list-after-connected-user-returns-to-serverless-domain

**Comment by davidkelly** [comment]
This is a backend problem, not a problem with this PR's code.  However, I can fix the backend and then we can retest here.

**Comment by howard-stearns** [comment]
the back end has been changed (on staging). this pr should now be ready for re-test. (No need to get a new build, as the change was purely back end)

**Comment by rickcarr044** [comment]
Currently testing PR14111

**Pull request merged**
