### PR TITLE
Beta Release 59 - Includes up to Developer Release 7426

### PR DESCRIPTION
**Pull request by conklin94122**
- Audio codec updated for all platforms
- Fixed bugs in Avatar Attachment dialog 
- Removed hack for missing inttypes.h header on VS2010
- Fix when Exiting or entering VR after sitting in a chair then standing character remains in sitting position
- Fixed logging in with HMD results in black world
- Lag with tablet and some attachments when moving around fixed
- Create -> Model allows setting dynamic and 'Exact - All Polygons', resulting in silent fail fixed
- Fix: HMD friendly Script log option can spawn multiple times
- Fix: Overlay display issue when editing entities
- Fix: Sufficiently large entities fail to make it to the entity server
- Removed Keylight attenuation from .js (as well as .html).
- Fix: Floor not loading
- Fix: Able to See Second User's Location Data
- Desktop mode: Audio can be heard while bubble is on both users with one avatar's size is at 7 or greater fixed
- Fix: Anyone can delete someone's avatar entity with Entities.deleteEntity(ID)
- Fix: "BLAST TO CONNECTIONS" button overlaid on top of the GIF does not appear
- Fix: Haze rendering problems in black stenciled areas
- Changed UI for Haze from an input field to a slider
- Resolved issues with far-grabbing: you can now far-grab groups of objects and your
- Fix: laser hits where y
- ou aimed, not in the center of the entity
- Adjusted the way Bubble works when avatar rescales
- Windows (HMD Only): Avatar Sinks into Floor When Jumping in Mirror Mode fixed
- Added support for non-English names of audio devices in audio menu
- Fixed issue where Avatar's size does not save when changing domains
- Disabled Mirror Mode in HMD since it makes people sick. Stay tuned for our upcoming
- awesome in-world mirror!
- Fixed bug where changing avatars while sitting breaks or locks animations

New Docs
[Host Your Domain with DigitalOcean](https://docs.highfidelity.com/create-and-explore/start-working-in-your-sandbox/digital-ocean): Learn how to host your domain on the cloud with DigitalOcean

Updated Docs
[Coding Standards](https://docs.highfidelity.com/build-guide/coding-standards): Included naming for protected vars
[Archive: Using DigitalOcean](https://docs.highfidelity.com/create-and-explore/start-working-in-your-sandbox/digital-ocean/archive): Archived doc for hosting with DigitalOcean
[High Fidelity API Reference: MyAvatar](https://docs.highfidelity.com/api-reference/myavatar): Adding scaleChanged signal
[Set Up Your Sandbox](https://docs.highfidelity.com/create-and-explore/start-working-in-your-sandbox/set-up-your-sandbox): Updated setup wizard process

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4875/HighFidelity-Beta-PR11801-9ff4541ee3bf4ed8bbe4c91a05095ea7a9789376.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4875/HighFidelity-Beta-PR11801-9ff4541ee3bf4ed8bbe4c91a05095ea7a9789376.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4924/HighFidelity-Beta-PR11801-49abb441e6b793c7015f60cf6e3deb061cf21be3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4924/HighFidelity-Beta-PR11801-49abb441e6b793c7015f60cf6e3deb061cf21be3.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4989/HighFidelity-Beta-PR11801-21503a635f2ed1c479db09d9ec637c4677a69103.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4989/HighFidelity-Beta-PR11801-21503a635f2ed1c479db09d9ec637c4677a69103.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5016/HighFidelity-Beta-PR11801-d4afd7fa0de337c9166eadace807b2ac00703e66.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5024/HighFidelity-Beta-PR11801-d4afd7fa0de337c9166eadace807b2ac00703e66.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5026/HighFidelity-Beta-PR11801-c255e29fa5576fdf4330765f550c72afc5230673.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5026/HighFidelity-Beta-PR11801-c255e29fa5576fdf4330765f550c72afc5230673.exe

**Pull request merged**
