### PR TITLE
Fix stand talk pops

### PR DESCRIPTION
**Pull request by dooglifeSF**
Fix for https://highfidelity.atlassian.net/browse/DEV-2356.  Blend time between randomly selected talks was too short, changed to 20 frames.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21869/HighFidelity-Beta-PR16332-9651042.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21869/HighFidelity-Beta-Interface-PR16332-9651042.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21869/HighFidelity-Beta-PR16332-9651042.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21869/HighFidelity-Quest-Beta-PR16332-9651042.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21878/HighFidelity-Beta-PR16332-0b38236.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21878/HighFidelity-Quest-Beta-PR16332-0b38236.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21878/HighFidelity-Beta-PR16332-0b38236.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21878/HighFidelity-Beta-Interface-PR16332-0b38236.dmg

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21885/HighFidelity-Beta-PR16332-0b38236.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21885/HighFidelity-Quest-Beta-PR16332-0b38236.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21885/HighFidelity-Beta-PR16332-0b38236.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21885/HighFidelity-Beta-Interface-PR16332-0b38236.dmg

**Comment by dooglifeSF** [comment]
TEST PLAN:
Watch yourself in a mirror or from 3p or selfie cam and  talk continuously for 20-30 seconds.  You should no longer see pops as the talk animations randomly switch (every 7-12 seconds) between talk anim options.   Stand talk animation, particularly the arms and head, should just look smooth and natural on extended runs of talking.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21885/HighFidelity-Beta-PR16332-0b38236.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21885/HighFidelity-Beta-Interface-PR16332-0b38236.exe

**Pull request merged**
