### PR TITLE
Reduce logging from some Commerce/Discovery features

### PR DESCRIPTION
**Pull request by zfox23**
First pass at this. Cleans up some unnecessary logs from Commerce/Discovery features.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan

### Notes
- This PR should not _functionally_ change any features, so this test plan will be light on details.

### Tests
Perform a general smoke test of the following features, looking for visual and functional changes:
- Wallet authentication screen
- PAL sphere overlay selection ("sphere overlays" === "the bubbles that appear on top of avatars when the PAL is open")
- Wallet "Send Money" sphere overlay selection
- Inspection Certificates (try inspecting a few rezzed entities. additionally, try bringing up the inspection cert of a few items in Purchases.)

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8680/app_12849_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8680/HighFidelity-Beta-PR12849-9de56a3bb046e1f54186dc4bfaff732e12a50491.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8680/HighFidelity-Beta-PR12849-9de56a3bb046e1f54186dc4bfaff732e12a50491.exe

**Comment by howard-stearns** [comment]
closed in favor of https://github.com/highfidelity/hifi/pull/12862

**Pull request closed without merging**
