### PR TITLE
Case 21316: Unable to click tablet app icons with lasers when in HMD (0.80.0)

### PR DESCRIPTION
**Pull request by danteruiz**
ticket - https://highfidelity.manuscript.com/f/cases/21316/Unable-to-click-tablet-app-icons-with-lasers-when-in-HMD

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan
make sure you can interact with the tablet

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17414/HighFidelity-Beta-PR14961-1096a7f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17414/HighFidelity-Beta-PR14961-1096a7f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17414/HighFidelity-Beta-Interface-PR14961-1096a7f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17414/HighFidelity-Beta-PR14961-1096a7f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17414/HighFidelity-Beta-Interface-PR14961-1096a7f.exe

**Pull request merged**
