### PR TITLE
Change to Log Font and Formatting

### PR DESCRIPTION
**Pull request by kunalgosar**
Different font on log window (Courier) and colored/bolded timestamps. Feedback welcome!

New log window looks like:
final

### CODE REVIEW

**Comment by kunalgosar** [comment]
In response to: https://highfidelity.fogbugz.com/f/cases/3322/Font-in-log-window-is-hard-to-read

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce6abf395abfeb2d85dd16530d954550aa72a66f available at: https://gist.github.com/cf815fde8ca7ebbc640830bef2b1d519<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-ce6abf3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-ce6abf3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42b33ecca5abc1bbacd42b0e6ed1eeb774efc59e available at: https://gist.github.com/cf815fde8ca7ebbc640830bef2b1d519<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-42b33ec.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-42b33ec.dmg

**Comment by OmegaHeron** [comment]
Looked at this on Windows 10.

It's certainly more readable.  Problem I have with this font and former font is one echoed in many places from other uses (forums).  It's not precisely what's wanted and the real (harder) solution is to give users options to set font type and size vs hard coding it.  Maybe a glorious future thing.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8360e7180681d785e436dfb869a0c5e5ffec386f available at: https://gist.github.com/cf815fde8ca7ebbc640830bef2b1d519<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-8360e71.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-8360e71.dmg

**Comment by Nex-Pro** [comment]
Looking at this.

**Comment by Nex-Pro** [comment]
Definite improvement in readability. I can now read the log on my 4k monitor. this means I can pretty much read each log entry as a single line.

If I type, say **fbx** in the filter the blue color of the timestamps changes to be black. Now all instances of the search string **fbx** are blue The original highlighting of the timestamps is not restored.

Would be good if the highlighting of found strings was more obvious and different to the timestamps.
But like @OmegaHeron says Options gotta love options.

**Comment by kunalgosar** [comment]
Having git issues -- closing PR and reopening another.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e095774adc8fe24835800f9b7a7e5385778cc7ca available at: https://gist.github.com/cf815fde8ca7ebbc640830bef2b1d519<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-e095774.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9826-e095774.dmg

**Pull request closed without merging**
