### PR TITLE
Case 21757: show up audio screen using Settings > Audio

### PR DESCRIPTION
**Pull request by wayne-chen**
# TEST PLAN
- Open Interface in desktop mode
- Open audio settings screen using the menu with `Settings > Audio`
- Screen should be visually/functionally the same as opening through the audio app in the toolbar
- Switch to HMD mode
- Open tablet
- Open audio settings screen by clicking through `Menu > Settings > Audio`
- Screen should be visually/functionally the same as opening through the audio app and desktop mode `Settings > Audio` screen through the menu

https://highfidelity.manuscript.com/f/cases/21757/RC81-Audio-Settings-window-accessed-by-Settings-Audio-is-blank

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18224/HighFidelity-Beta-PR15210-a16980a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18224/HighFidelity-Quest-Beta-PR15210-a16980a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18224/HighFidelity-Beta-PR15210-a16980a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18224/HighFidelity-Beta-Interface-PR15210-a16980a.exe

**Comment by wayne-chen** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18226/HighFidelity-Beta-PR15210-a16980a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18226/HighFidelity-Beta-Interface-PR15210-a16980a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18226/HighFidelity-Beta-PR15210-a16980a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18226/HighFidelity-Quest-Beta-PR15210-a16980a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18226/HighFidelity-Beta-PR15210-a16980a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18226/HighFidelity-Beta-Interface-PR15210-a16980a.exe

**Pull request merged**
