### PR TITLE
Case 20407 - Pay-In API doesn't display error when no username specified

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/20407/Pay-In-API-script-error-checking-No-username-in-script-returns-blank-dialog

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18278/HighFidelity-Beta-PR15233-3775633.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18278/HighFidelity-Quest-Beta-PR15233-3775633.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18278/HighFidelity-Beta-PR15233-3775633.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18278/HighFidelity-Beta-Interface-PR15233-3775633.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18278/HighFidelity-Beta-PR15233-3775633.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18278/HighFidelity-Beta-Interface-PR15233-3775633.exe

**Pull request merged**
