### PR TITLE
speed up spherical harmonics calculation with minimal error

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* faster calculation of ambient lighting from cubemapped sky texture

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR speeds up the calculation of the spherical harmonic (SH) coefficients that are used for ambient lighting of non-reflective objects.  This is something that is done shortly after loading a zone's skybox texture and you know it is complete when the lighting of all objects "pops" into their final shades.  The time for a skybox with 1024x1024 faces goes from about 450 msec down to 12 msec (for release build on my i7, 8-core, 16GB linux machine) however these calculations are done on a separate thread so they shouldn't noticeably block the render pipeline... which means the speedup is hard to measure without explicit timing code.

The new calculations make some approximations which means the results are slightly different (on the order of only 1% from my measurements).  So, to test all we need to do is make sure the lighting is not noticeably changed:

(1) Login to a domain that uses a zone with a skybox texture
(2) Take a screenshot of final lighting with this PR and then again with the dev-download.
(3) Compare the two images -- the lighting on the non-reflective objects should look about the same.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2d905fc86831028a8b982c6bc9f53a71fd2523b available at: https://gist.github.com/300f4ddfa651333578c2cec039c235c9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8495-d2d905f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8495-d2d905f.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

DEV 5305

hifi-snap-by-omegaheron-on-2016-08-24_16-19-29

This PR

hifi-snap-by-omegaheron-on-2016-08-24_16-21-08

DEV 5305

hifi-snap-by-omegaheron-on-2016-08-24_16-23-11

This PR

hifi-snap-by-omegaheron-on-2016-08-24_16-22-12

**Comment by OmegaHeron** [comment]
If there's any difference it's beyond my detection range -  things looked a tiny bit brighter at hifi://heron at first, then I realized I had a different zoom between shots.  Repeating without changing 3rd person zoom seemed = for look of this PR to current RC/DEV.

**Comment by OmegaHeron** [comment]
General smoke tests pass - I looked at my own domains, dev-playa and dev-demo with Desktop and DK2 HMD.  I can't see any delta from this to current RC/DEV visually or functionally.  QA Pass for windows.  Suggest Mac and testing on AMD before full pass.

**Pull request merged**
