### PR TITLE
fix keyboard mapping (keyboardMouse.js)

### PR DESCRIPTION
**Pull request by AlessandroSigna**
fix keyboardMouse.json

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelise

**Comment by murillodigital** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bce95189b5a0716185d8a134f00ad468e7b66dc available at: https://gist.github.com/3fa343abc6a3705417b8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6192.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6192.dmg

**Comment by ZappoMan** [comment]
lolz -- whitelise

**Pull request merged**
