### PR TITLE
Remove UndoStack API

### PR DESCRIPTION
**Pull request by huffman**
edit.js shares a global undo stack through the UndoStack API. Because
the stack is globally shared, disabling the feature while create is
disabled doesn't make a lot of sense because it might disabling the
ability to undo/redo with another feature. Because UndoStack is only
used by edit.js, UndoStack is being removed in favor of a local undo
stack implemented within edit.js.

https://highfidelity.fogbugz.com/f/cases/16864/UndoStack-fails-to-work-as-a-globally-shared-resource-and-should-be-deprecated

### CODE REVIEW

**Comment by huffman** [comment]
# Test Plan

 1. Activate Create
 1. Create a cube
 1. Select `Edit > Undo` from the menu. The cube should be removed.
 1. Create a cube (1)
 1. Move cube (1)
 1. Create another cube (2)
 1. Move cube (2)
 1. Press ctrl-z. Cube (2) should move back to where it was first created
 1. Press ctrl-z. Cube (2) should be removed, and cube (1) should be selected
 1. Press ctrl-z. Cube (1) should move back to where it was first created
 1. Press ctrl-z. Cube (1) should be removed, and there should be no selected
 1. Press ctrl-shift-z 4 times, each time observing that the actions are taking place in reverse (Cube (1) is created, then moved, Cube (2) is created, then moved)
 1. Do a general smoke test on editing other properties of an entity and undoing/redoing the actions.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13112/HighFidelity-Beta-PR14027-73c3ab3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13112/HighFidelity-Beta-PR14027-73c3ab3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13112/HighFidelity-Beta-Interface-PR14027-73c3ab3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13112/HighFidelity-Beta-PR14027-73c3ab3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13112/HighFidelity-Beta-Interface-PR14027-73c3ab3.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13216/HighFidelity-Beta-PR14027-73c3ab3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13216/HighFidelity-Beta-PR14027-73c3ab3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13216/HighFidelity-Beta-Interface-PR14027-73c3ab3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13216/HighFidelity-Beta-PR14027-73c3ab3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13216/HighFidelity-Beta-Interface-PR14027-73c3ab3.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Fail @conklin94122 

Sometimes, when the user closes Create, then reopens Create the undo/redo function does not kick in until the user makes another entity.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2412458/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13364/HighFidelity-Beta-PR14027-09b2565.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13364/HighFidelity-Beta-PR14027-09b2565.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13364/HighFidelity-Beta-Interface-PR14027-09b2565.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13500/HighFidelity-Beta-PR14027-09b2565.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13500/HighFidelity-Beta-PR14027-09b2565.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13500/HighFidelity-Beta-Interface-PR14027-09b2565.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13500/HighFidelity-Beta-PR14027-09b2565.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13500/HighFidelity-Beta-Interface-PR14027-09b2565.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Undo/Redo works as expected

**Pull request merged**
