### PR TITLE
Report previous session data

### PR DESCRIPTION
**Pull request by howard-stearns**
Report whether or not previous session crashed, and what the session time was.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/104349881708294

**Comment by hifi-gustavo** [comment]
Build console output for commit: dbdf79f96ffa6598ba3bd7c730f5ee2051b83883 available at: https://gist.github.com/e65e43920c35e72f515d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.dmg

**Comment by ZappoMan** [comment]
```
In file included from /data/jenkins/Jenkins/workspace/beta_pr-master@2/label/ubuntu/interface/src/Application.cpp:12:0:
/data/jenkins/Jenkins/workspace/beta_pr-master@2/label/ubuntu/interface/src/Application.h: In constructor ‘Application::Application(int&, char**, QElapsedTimer&)’:
/data/jenkins/Jenkins/workspace/beta_pr-master@2/label/ubuntu/interface/src/Application.h:380:20: warning: ‘Application::_sessionRunTimer’ will be initialized after [-Wreorder]
     QElapsedTimer& _sessionRunTimer;
                    ^
/data/jenkins/Jenkins/workspace/beta_pr-master@2/label/ubuntu/interface/src/Application.h:379:17: warning:   ‘MainWindow* Application::_window’ [-Wreorder]
     MainWindow* _window;
                 ^
/data/jenkins/Jenkins/workspace/beta_pr-master@2/label/ubuntu/interface/src/Application.cpp:454:1: warning:   when initialized here [-Wreorder]
 Application::Application(int& argc, char** argv, QElapsedTimer& startupTimer) :
 ^
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: a393f36978dfc04083acb8507e424d390b38dc06 available at: https://gist.github.com/e65e43920c35e72f515d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.dmg

**Comment by howard-stearns** [comment]
Testing notes:
You can't see the new data unless you're at the anonymous data-collection server, or are looking on the wire.  (We could log the sent data. Not sure why we're not doing that now.)
Otherwise, just make sure nothing bad happens when:
  starting after success
  starting after a crash (with .ini retained)
  starting for new user (e.g., no .ini file)

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a393f36978dfc04083acb8507e424d390b38dc06 available at: https://gist.github.com/e65e43920c35e72f515d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7449.dmg

**Comment by ZappoMan** [comment]
Tested it, checked the values in the metaverse server, it seems to me working. Pass

**Pull request merged**
