### PR TITLE
Fix browser "back" button in tablet snapshot and goto "i" pages

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Test the following in tablet mode (HMD or desktop).

Snapshot dialog ...
- Twitter page:
	- "Back" button is disabled (greyed out and performs no action).
	- "Close" button closes Twitter page and goes back to the snapshot dialog.
- Facebook page: ditto.

Goto dialog, place "i" page ...
- "Back" button is disabled (greyed out and performs no action).
- "Close" button closes "i" page and goes back to the goto dialog.
- Twitter page:
	- "Back" button goes back to "i" page. The "back" button is disabled on the "i" page.
	- "Close" button closes Twitter page and goes back to the goto dialog.
- Facebook page: ditto.
- host/user page: 
	- "Back" button goes back to "i" page. The "back" button is disabled on the "i" page.
	- "Close" button closes host/user page and goes back to the goto dialog.
- host/user page -> Twitter page:
	- "Back" button goes back to host/user page. The "back" button then goes back to "i" page, and it's disabled on the "i" page.  <<< FAIL BECAUSE Can't go back to "i".
	- "Close" button closes Twitter page and goes back to the goto dialog.
- host/user page -> Facebook page: ditto.

Goto dialog, snapshot "i" page ...
"Back" and "Close" buttons behave similar to place "i" page, including through the paths:
- user -> tweet.
- place -> host/user -> tweet.


People, "i" page for person...
- "Back" button is disabled (greyed out and performs no action).
- "Close" button closes Twitter page and goes back to the snapshot dialog.
- Twitter page:
	- "Back" button goes back to "i" page. The "back" button is disabled on the "i" page.
	- "Close" button closes Twitter page and goes back to the goto dialog.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b26ba22cbc323f1f46aebf09608981fad9dac96 available at: https://gist.github.com/cc50e15fa77bed6bff834eb1bde9b62f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10395-1b26ba2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10395-1b26ba2.dmg

**Comment by anshuman64** [comment]
Behavior is improved, but there is at least one case where the behavior is not desirable:

1. Get to Twitter page by any means (ex. GoTo > "i" > Tweet)
2. Click "Forgot password" to go to another page
3. Hit Back. Goes back to login page as expected.
4. Hit Back again. Just reloads the page.
Expected behavior: Ideally, goes back to "i" page. At the very least, should be grayed out.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 116175cf9fe422d8d525dc5ba9fa391f369dc75e available at: https://gist.github.com/cc50e15fa77bed6bff834eb1bde9b62f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10395-116175c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10395-116175c.dmg

**Pull request merged**
