### PR TITLE
Fix default collision values RC75

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.fogbugz.com/f/cases/19685/Models-imported-into-test-case-have-Automatic-Collisions-set-to-No-Collision-allowing-test-avatar-to-walk-through-model

# Test Plan

 * Create a cube, and stretch it out so you can walk
 * You should be able to collide with and walk on the cube

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14574/HighFidelity-Beta-PR14318-4234e84.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14574/HighFidelity-Beta-PR14318-4234e84.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14574/HighFidelity-Beta-Interface-PR14318-4234e84.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14574/HighFidelity-Beta-PR14318-4234e84.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14574/HighFidelity-Beta-Interface-PR14318-4234e84.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Collisions are enabled by default, user can walk on new entities and collides when walking to them

**Pull request merged**
