### PR TITLE
End seeding

### PR DESCRIPTION
**Pull request by howard-stearns**
Remove notices about closed beta commerce, replacing with link to BankOfHighFidelity.
Since metaverse server no longer seeds accounts, we can now inform user when their local wallet doesn't match server records, and prompt users to either supply a wallet (e.g., from backup or a different installation), or to proceed with making a new one.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7499/app_12497_PR.apk

**Comment by howard-stearns** [comment]
Testing must be done using the staging metaverse.
1. Perform the standard wallet setup acceptance tests.
2. At the end of setup with a new account (per #1), you should have zero HFC, and the wallet "Home" should have a message about going to BankOfHighFidelity. (But since you are on the staging metaverse, the link actually goes to hifiqa-master-metaverse-staging.)
3. Move (don't copy) your .hifikey file from its location to a distinctive name (e.g., WalletA.hifikey) in another directory (such as Desktop). (Recall that the .hifikey file location is described in the browser during wallet setup, and in the wallet help.) Restart and try to open the wallet. You should be told that there is an existing wallet, and be given the choice to find the existing one. Use that, and supply the one you just moved elsewhere, which should work. The renamed one should still be where you put it (e.g., Destkop/WalletA.hifikey).
4. Delete the wallet .hifikey (from AppData, not the copy). Restart and open the Wallet app, but this time make a new one, which should work.
5. Move this new wallet from AppData to another name, such as Desktop/WalletB.hifikey. Restart and open the Wallet app. When you pick Wallet B it should work as expected. (Similar to #3 with a new name.)
6. Repeat #4, picking WalletA. It should tell you that this choice doesn't match, at which point you can pick WalletB, which should work.
7. Repeat #4, picking WalletA. It should tell you this choice doesn't match, at which point pick the choice to make a new one out of your choice of WalletA. This should work. (It may repeat the notice about backing up your keys, which is a little weird, but that's ok.)
8. Now repeat #3-7, but instead of doing so by opening the Wallet, open Marketplace => My Purchases instead.
9. Now repeat #3-7, but instead of doing so by opening the Wallet or My Purchases, try to buy something from the Marketplace.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7499/HighFidelity-Beta-PR12497-dee3df5299d5d1028934026c413a1cd5d6617692.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7499/HighFidelity-Beta-PR12497-dee3df5299d5d1028934026c413a1cd5d6617692.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7514/app_12497_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7514/HighFidelity-Beta-PR12497-4e4aebc7ee66ff152c3f782fae9343b9ae557443.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7514/HighFidelity-Beta-PR12497-4e4aebc7ee66ff152c3f782fae9343b9ae557443.exe

**Comment by howard-stearns** [comment]
should be right now, as soon as it builds....

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7517/app_12497_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7517/HighFidelity-Beta-PR12497-8223ebf393ad5f04a49f162abf338351a29f4ef7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7517/HighFidelity-Beta-PR12497-8223ebf393ad5f04a49f162abf338351a29f4ef7.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Fail
Step 9 fails with an error message when a new or old key is selected and after setting up a new wallet.

All other steps pass as expected. Attached Image of error, and zip which contains Logs, Videos, and the full error message in text.
[12497 Files.zip](https://github.com/highfidelity/hifi/files/1760400/12497.Files.zip)
purchaseitemfindkeys

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7523/app_12497_PR.apk

**Comment by howard-stearns** [comment]
ok, this should be good to go when it builds.
However,
1. If you try to buy something with your wallet not setup and then get prompted to set one (test case #9), there are paths by which you might end up (after choosing or creating a wallet) at the marketplace page or the item page, but not at confirmation page. I.e., you have to try again to buy.
2. In the wallet setup path of this case, you might have to say you want to say ok twice. (Once to make one, and then to be told that, "hey, this is different" and agree.)

We're going to call these cases acceptable for now. We certainly don't want error screens, but this project was only about making some more obscure cases work at all, rather than redesign everything to optimize all error flows.

I'll update step 9 to note this.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7523/HighFidelity-Beta-PR12497-0802bd2c219f6520543e1d2ae9565066183eac37.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7523/HighFidelity-Beta-PR12497-0802bd2c219f6520543e1d2ae9565066183eac37.exe

**Comment by EthanMaasdam** [comment]
@conklin94122  Passes on Mac and Desktop
Fails on HMD. Fails on headsets due to button doing nothing
[hifi-log locate my keys.zip](https://github.com/highfidelity/hifi/files/1760852/hifi-log.locate.my.keys.zip)

**Comment by conklin94122** [comment]
@howard-stearns ^

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7562/app_12497_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7562/HighFidelity-Beta-PR12497-917024431207c5dd77efa6a96c26f142ae69bbd6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7562/HighFidelity-Beta-PR12497-917024431207c5dd77efa6a96c26f142ae69bbd6.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
