### PR TITLE
Beta Release 38 - Includes up to Developer Release 6383

### PR DESCRIPTION
**Pull request by cozza13**
- Kinect hand filter 
 - Make userInfoViewer button always clickable for myCard 
 - The Snapshot Review dialog now appears as soon as the snapshot is finished capturing (versus the current behavior, where it appears after the GIF finishes processing). While the GIF is processing, the Snapshot Review dialog displays a "Loading" image until the GIF is finished processing. 
 - turn on handControllerGrab debug prints 
 - cleanup Agent RSI handling, make loadRecording async 
 - Make it easier to exit FingerPaint 
 - fix can't grab tablet 
 - Fix GIFs not sharing
 - Uploading a gif now returns a new shareable_url
 - Fix getAvatar() not working for AC scripts
' - Fix GoTo text field focus; other GoTo tweaks
 - Added quadratic ease-in-and-out smoothing to remote avatars 
 -  **Allow people to save avatar bookmarks** ( https://github.com/highfidelity/hifi/pull/10046 )
 - Cleanup dependencies in Avatar class in preparation for migration to new lib 
 - Fix issue of tablet proxy not choose the correct root
 - Fix Entities.setLocalJointTranslations 
 - Adding support for variable allocated textures to the GL 4.1 backend 
 - Far grab improvement to draw held entity toward yourself 
 - Don't render (or heavily use GPU) when window in minimized
 - Update Display menu on unsuccesful selection
 - Cleaning the Engine/Task/Job interface 
 - Make setBlendshape changes persist 
 - Introducing support for the ResourceBuffer binding point in the gpu lib,
 - **Added tetherball create and entity scripts**  ( https://github.com/highfidelity/hifi/pull/10106 )
 - Clean up plugins/hifiCodec dependencies 
 - Add a column to edit.js to identity baked models 
 - **Bullet constraints + far-grab bootstrap fix** https://github.com/highfidelity/hifi/pull/10225
 - force DS to use new node ID if connect is re-sent 
 - Running this client script allows the use of an open mic/speaker configuration, such as when not using headphones. 
 - **Add textures BC compression** (  https://github.com/highfidelity/hifi/pull/10215 )
 - Add support for ignore radius from agent scripts 
 - Added tabletwebview keyboard for HMD
 - Fix incorrect logging in makeUserConnection  
 - Fix entity script unloads
 - **New Tutorial and entity scripts nbody.js - creates a planet and two moons in front of you**  ( https://github.com/highfidelity/hifi/pull/10175 )
 - Condition tutorial on active HMD 
 - Newly created entities in Edit.js should be grabbable 
 - **New avatar record and playback script** ( https://github.com/highfidelity/hifi/pull/10130 )
 - Make the Particle Emitter Easier to Use 
 - makeUserConnection.js Fix for alternative skeletons
 - **Doppleganger Mirror**  ( https://github.com/highfidelity/hifi/pull/10271 )
 - Input recorder/ input playback system for all input actions 
 - **Add progressive load for KTX textures**  ( https://github.com/highfidelity/hifi/pull/10261 )
 - **Make record script able to be put on the marketplace**
 - Fix excessive copying when querying the size of a KTX backed texture 
 - Fix two cases for avatars stuck in T-Pose
 - Fixes to a couple of different bug vectors for avatars getting stuck in t-pose

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f688a08cdb943f2d1cd8d1ceb33dcf370db5b91 available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-9f688a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-9f688a0.dmg

**Comment by Atlante45** [comment]
Windows build available at:
http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-aaa4cdb.exe

**Comment by hifi-gustavo** [comment]
Build console output for commit: aaa4cdb28391017cd2984c7f416b7d79f5ecdad9 available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-aaa4cdb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-aaa4cdb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11ed8c9ce1d59bfc49bc0635eb2bb89b6c861b4c available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11ed8c9ce1d59bfc49bc0635eb2bb89b6c861b4c available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11ed8c9ce1d59bfc49bc0635eb2bb89b6c861b4c available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-11ed8c9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f12031c5160cc0dd4175919202311fceb0d24ac available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-2f12031.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-2f12031.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21bb4080ab978ada1d425f7c46811717b34482fd available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-21bb408.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-21bb408.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b5851b7c3e13caaa41bf217af2ed334def9e2d2 available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-3b5851b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-3b5851b.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Textures loaded significantly faster from domain to domain.  Literally within a few seconds everything rezzed.  Jumped quickly through all the dev domains without any issue.  Interestingly ``Render Rate`` did not drop much as before we had wild swings in values where it was more stable in this build.  After a domain has fully rezzed, when TP back and forth INSTANT load of textures as a completely seamless experience!


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |70
**Present Rate**: |53 |52 |70
**Present New Rate**: |60 |70 |52
**CPU Buffer Count**: |2286 |720 |848
**GPU Buffer Count**: |861 |201 |232
**CPU Memory Usage**: |21719056 |5758352 |10795056
**GPU Memory Usage**: |13559088 |3296624 |5086576
**CPU Texture Count**: |242 |71 |85
**GPU Texture Count**: |194 |46 |52
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |565498076 |35912404 |30124752
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |98115 |88381 |64954
**Triangle Rate**: |7008214 |5892066 |4059625
**API Drawcall Count**: |89 |51 |49
**Drawcall Count**: |2898 |47 |54
**Drawcall Rate**: |207000 |3133 |3375
**State Changes Texture Count**:|138 |42 |78
**Pipeline Count**: |37 |29 |27
**Item Opaques**: |99 |194 |81
**Item Translucents**: |13 |25 |15
**Item Lights**: |5 |40 |15
**Timing Opaques**: |0.381 |0.525 |0.313
**Timing Translucents**: |0.039 |0.043 |0.086
**Timing Lighting**: |0.031 |0.021 |0.021
**Render Frame**: |0.98 |2.163 |1.261


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS

**Comment by Nex-Pro** [comment]
testing this.

**Comment by Nex-Pro** [comment]
### #10304 QA. Beta Release 38

## FAIL  too many crashes.

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.

## QA Test 10304

## QA Test
**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**:


I started this up with my vive disconnected but steam vr running. 
Then connected vive usb and power. When the vive was up and running I switched to HMD mode.
On starting the tutorial I was able to use all three fireworks leaving none behind and unable to proceed. I assume this was due to an unseen modal.
I tried to quit hifi using the title bar menu. This did not work. When I tried using the enter key HiFi exited, I guess it was that unseen modal.

Had a crash x2  while running playa performance test at dev-playa. Two other avatars present. One was Pinocchio default robot.
One additional crash when attempting to paste test results into text editor.
One crash I had to force interface to close as it became unresponsive.

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |89 |90 |
**Present Rate**: |88 |89 |
**Present New Rate**: |50 |90 |
**CPU Buffer Count**: |2322 |32141 |
**GPU Buffer Count**: |780 |1549 |
**CPU Memory Usage**: |21096592 |197051632 |
**GPU Memory Usage**: |12740016 |60413360 |
**CPU Texture Count**: |224 |224 |
**GPU Texture Count**: |182 |196 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |560233636 |906732984 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |497252 |2375497 |
**Triangle Rate**: |45204727 |215954272 |
**API Drawcall Count**: |184 |242 |
**Drawcall Count**: |4356 |756 |
**Drawcall Rate**: |396000 |68727 |
**State Changes Texture Count**:|315 |257 |
**Pipeline Count**: |39 |40 |
**Item Opaques**: |277 |405 |
**Item Translucents**: |52 |40 |
**Item Lights**: |10 |49 |
**Timing Opaques**: |1.08 |1.466 |
**Timing Translucents**: |0.115 |0.058 |
**Timing Lighting**: |0.019 |0.016 |
**Render Frame**: |1.783 |2.525 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|check
**Test 2**|Install a fresh copy of "Home' and do tutorial|**SUCCESS but see notes**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?|not done
**Test 5**|Switch avatar and make sure it does not crash|**SUCCESS**
**Test 6**|Test group functions|not done
**Test 7**|Test Ambisonic audio with markeplace item|**SUCCESS**
**Test 8**|Enrure that you can distance grab|**success**
**Test 9**|Bring up and edit an objects with hand controllers|**Pretty bad I rotated a cube on its side and trying to scale it on its local Y axis was miserable.**
**Test 10**|Test PAL functionality|undefined
**Test 11**|Test Tablet in 2D and 3D|**SUCCESS**

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested:  Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-3b5851b.exe

## Smoke Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: 

Failures:
- Going into EDIT causes my avatars left hand's, blue laser, to animate. As long as I point outside of the tablet, the laser stays triggered. 
The right hand does the same, but the opposite. As long as I point inside the tablet the laser stays triggered. 
It all goes away once I close EDIT.
- ATP Upload: It took approx. 30sec. for the entity to load on it's initial load. Further attempts to load the same entity loaded instantly.
- Echo Server Audio: Never hear that before. Some kind of "feedback" when I say anything loud.
- Reverb Test: When trying to move the WET slider, or any other slider, for the reverb test, the laser animation turns into a mouse cursor and stops the slider from moving any further. 
3 seconds later the cursor disappears and the laser animation returns.
- Dev-Demo: Unable to access Domain. "Connection refused: You lack the required permissions to connect to this domain."




**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2052 |31146 |
**GPU Buffer Count**: |357 |962 |
**CPU Memory Usage**: |20976688 |174655376 |
**GPU Memory Usage**: |7198128 |29472176 |
**CPU Texture Count**: |198 |242 |
**GPU Texture Count**: |55 |160 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |145989900 |609526940 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |68830 |647732 |
**Triangle Rate**: |6257272 |161933000 |
**API Drawcall Count**: |44 |180 |
**Drawcall Count**: |74 |317 |
**Drawcall Rate**: |6727 |79250 |
**State Changes Texture Count**:|62 |215 |
**Pipeline Count**: |31 |33 |
**Item Opaques**: |30 |314 |
**Item Translucents**: |15 |20 |
**Item Lights**: |4 |62 |
**Timing Opaques**: |0.113 |1.057 |
**Timing Translucents**: |0.037 |0.054 |
**Timing Lighting**: |0.013 |0.019 |
**Render Frame**: |0.601 |1.955 |

Notes: My avatars hands were noticeably vibrating/shivering in Dev-Cell.


## RC Specific tests

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|untested
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|untested
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|Please read notes
**Test 11**|Test Tablet in 2D and 3D|Please read notes


Failures:

Test 10: 
- Tweet, Like, Share buttons do nothing in PAL.
- Clicking on Twitter, Like, Share makes Like and Share buttons disappear. This only happens in HMD with hand devices.
The buttons disappearing doesn't happen immediately. Constant clicking on the buttons will produce this bug. I was able to reproduce every time.

Test11:  
- The dialog in HELP interprits 1 click as 2 clicks. This happens in both Desktop and HMD modes.
- Take a SNAP>go to settings>click cancel> Tablet screen goes blank. This happens in both Desktop and HMD modes.

**Comment by OmegaHeron** [comment]
Testing

**Comment by OmegaHeron** [comment]
Tablet (In HMD with CV1+Touch controller) *continues* to be totally unreliable.  After some random calls to table (usually 3rd to 6th request for it), all further calls to table result in it being blank screen.  Totally unusable, have to either quit interface or pause and attempt to reload scripts from desktop display menu (which doesn't always seem to restore tablet to operation).  Only 100% reliable method to make table work again for (3...6 or so times) is restart Interface.

No - this is not new behavior, but, it's persistent across last RCs and should be addressed sooner vs later.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ba5ea42293f9f967ecf85b1120d060c98addc0a available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-7ba5ea4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-7ba5ea4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: de134adb9537150aee968db62b5084d1a01f8cac available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-de134ad.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-de134ad.dmg

**Comment by Nex-Pro** [comment]
Re-Testing as requested.

**Comment by Nex-Pro** [comment]
@cozza13  I'm testing this !

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20051b970a4da51d40a6c744e027688e97720294 available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-20051b9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-20051b9.dmg

**Comment by Nex-Pro** [comment]
### #10304 QA. Beta Release 38 pass 2

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.


**QA Tester**: Piper.Peppercorn

localhost 'createTestBlocks.js' Result**: SUCCESS**
localhost ATP Upload + Edit  Result**: SUCCESS**
Echo Server Audio Result**: SUCCESS**
localhost 'harmonicOscillator.js'  Result**: SUCCESS**
localhost 'reverbTest.js'  Result**: SUCCESS**
localhost 'playaPerformanceTest.js' Result**: SUCCESS on performance**
dev-playa 'playaPerformanceTest.js' Result**: SUCCESS on performance**
dev-demo 'playaPerformanceTest.js' Result**: N/A**

QA Pass**: FAIL**

**Additional Test Results + Observations**:

Had 3x identical crashes running playa performance test at both localhost ( 1 crash )  and dev-playa ( 2 crashes ).
This was from a cold install. IE previous installation and folders removed.

Also during each attempt to run playa performance test my HMD was dropping into the steam room on multiple occasions.

While in the tutorial during the teleport segment try grabbing the vases in the middle room. They instantly get moved to 0, 0, 0 ( this is same in master )

**Not related to this PR but important to me:**

Having the tablet be inactive until all content is loaded has to be fixed. ( there's a PR to address this, I think )

Transfer from far grab to held is really annoying. I'd want this as an option.

Also since we now can rotate a far grabbed entity using the second controller,
I feel that this functionality should only work when both lasers are on the object.
Currently I can pull the trigger on almost anything in view and get the entity
in the far grab laser to rotate.
This means we cannot lift two items at once which seems counter intuitive and debilitating. ( not caused by this PR )



HMD

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |90 |89 |
**Present Rate**: |89 |89 |
**Present New Rate**: |90 |90 |
**CPU Buffer Count**: |1705 |28304 |
**GPU Buffer Count**: |194 |885 |
**CPU Memory Usage**: |15676528 |159567760 |
**GPU Memory Usage**: |2642544 |33971568 |
**CPU Texture Count**: |200 |201 |
**GPU Texture Count**: |63 |156 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |214067096 |625278724 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |55966 |1442021 |
**Triangle Rate**: |5087818 |131092818 |
**API Drawcall Count**: |39 |127 |
**Drawcall Count**: |5342 |526 |
**Drawcall Rate**: |485636 |47818 |
**State Changes Texture Count**:|55 |149 |
**Pipeline Count**: |31 |35 |
**Item Opaques**: |28 |197 |
**Item Translucents**: |16 |23 |
**Item Lights**: |1 |36 |
**Timing Opaques**: |0.074 |0.62 |
**Timing Translucents**: |0.025 |0.061 |
**Timing Lighting**: |0.009 |0.046 |
**Render Frame**: |0.382 |1.916 |

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f6a1be2c7b2d294254d130d291ab2a2d7d44773 available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-7f6a1be.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-7f6a1be.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f9002d724e94d0776b5c5d2dca9f9a71934b1ef available at: https://gist.github.com/a8257ccf153b657b05110f80d6e71bdc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-0f9002d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10304-0f9002d.dmg

**Pull request merged**
