### PR TITLE
Event installer interface options

### PR DESCRIPTION
**Pull request by howard-stearns**
Defines:
  --version filename
  --protocolVersion filename
  --skipTutorial
The first two write the requested data to the given filename and quit.
The last skips tutorial and/or help if either would have been run (with no effect otherwise), but does not alter any settings (e.g., does not alter firstRun or tutorialComplete).

### CODE REVIEW

**Comment by howard-stearns** [comment]
This is for use in micro-installer development. E.g., the micro-installer can check for this pr version and install the pr installer if needed.

It can be thought of as the real way to implement https://github.com/highfidelity/hifi/pull/10753, which it will supersede. (I won't close 10753 until folks are done evaluating the effect.)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/914/HighFidelity-Beta-PR10758-41003bd3079d1309b17134950f6c94922c8b4520.dmg

**Comment by zfox23** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/919/HighFidelity-Beta-PR10758-41003bd3079d1309b17134950f6c94922c8b4520.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/919/HighFidelity-Beta-PR10758-41003bd3079d1309b17134950f6c94922c8b4520.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/934/HighFidelity-Beta-PR10758-fea8a95fc7ab9f8e4c09313f5d72b167d928bcd9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/934/HighFidelity-Beta-PR10758-fea8a95fc7ab9f8e4c09313f5d72b167d928bcd9.exe

**Comment by howard-stearns** [comment]
**test plan:**
In the following:
- _interfacePath_ is the path from wherever you are to Interface.exe (e.g., likely in Program Files, etc.)
- _writeablePath_ is a filename in which you have write permission.
1. Execute in a cmd shell: `_interfacePath_ --version _writeablePath_` -- It should write "PR10758" to _writeablePath_, and quit.
 - Try with _writeablePath_ existing and not existing.
 - If you run interface normally before this, you should be able to run it normally after this, without being prompted to reset settings.
 - If you run interface with a crash before this (or, e.g., Developer -> Ask To Reset Settings), then asking for --version as above should still work, but when you run interface afterwords in the normal way, it should indeed prompt you to reset settings (just as if you had never run with --version).

2. Same thing for --versionProtocol, except that the value written to _writeablePath_ is `L4L4dBnPWvX1Oiw2LKbVaw==` (which is the same thing as `location.protocolVersion()` returns in the jascript console).

3. Run  `_interfacePath_ --skipTutorial` -- it should not run the tutorial on startup, nor pop open the help screen on startup.
 - Do this with your existing settings and with no settings.
 - Do this (with and without settings) while in HMD and in Desktop.
 - Do this (all four combinations of the above) with and and without sandbox running.
 - Do this (all eight combinations of the above) with and without some --url argument, such as `--url hifi://dev-welcome`.

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Failed
Test | With/Without Settings (Desktop) | With/Without Settings (HMD) | With/Without Sandbox Running | With/Without URL
-------- | -------- | -------- | -------- | --------
Execute in a cmd shell: _interfacePath_ --version _writeablePath_ -- It should write "PR10758" to writeablePath, and quit. | Pass (The game didn't launch, though I assume this is intended for these arguments) | Pass | Pass | Pass 
Try with writeablePath existing and not existing. | Pass (It creates the file and adds the text if not existing) | Pass | Pass | Pass
If you run interface normally before this, you should be able to run it normally after this, without being prompted to reset settings. | Pass | Pass | Pass | Pass
If you run interface with a crash before this (or, e.g., Developer -> Ask To Reset Settings), then asking for --version as above should still work, but when you run interface afterwords in the normal way, it should indeed prompt you to reset settings (just as if you had never run with --version). | Pass | Pass | Pass | Pass
Same thing for --versionProtocol, except that the value written to writeablePath is L4L4dBnPWvX1Oiw2LKbVaw== (which is the same thing as location.protocolVersion() returns in the jascript console). | Fail (The game started up normally and didn't write anything to the writeablePath, can confirm however that location.protocolVersion() returns the expected result in console) | Fail | Fail | Fail | Fail
Run _interfacePath_ --skipTutorial -- it should not run the tutorial on startup, nor pop open the help screen on startup. | Pass | Pass | Pass | Pass | Pass

Let me know if there's anything you'd like me to run over again.

**Comment by howard-stearns** [comment]
Ah, I see the problem! I made a typo in the test plan!
Test 2 should have been `_interfacePath_ --protocolVersion _writeablePath_ `
(I had mistakenly written _--versionProtocol_ up above.)

I'm so sorry about that!
Can you try again?

**Comment by CainFoool** [comment]
# Test Passed
Test | With/Without Settings (Desktop) | With/Without Settings (HMD) | With/Without Sandbox Running | With/Without URL
-------- | -------- | -------- | -------- | --------
... same thing for --protocolVersion, except that the value written to writeablePath is L4L4dBnPWvX1Oiw2LKbVaw== (which is the same thing as location.protocolVersion() returns in the jascript console). | Pass | Pass | Pass | Pass | Pass 

@howard-stearns 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
