### PR TITLE
Web overlays and entities are always non anti-aliased

### PR DESCRIPTION
**Pull request by SamGondelman**
All web overlays and web entities ignore anti-aliasing to increase readability.

Test plan:
- Tablet should appear readable on desktop and in HMD
- Create a web entity.  The text should be readable.

### CODE REVIEW

**Comment by SamGondelman** [comment]
fxaa_blend outputs outFragColor.x = 1 to show when blending is applied:
nonaatest6

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2750/HighFidelity-Beta-PR11242-4a49801217652f1ffe3169ece58fad33bf1d7bac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2750/HighFidelity-Beta-PR11242-4a49801217652f1ffe3169ece58fad33bf1d7bac.exe

**Comment by samcake** [comment]
build this please

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
--- | --- | ---
Tablet should appear readable on desktop and in HMD | Pass | Pass
Create a web entity. The text should be readable. | Pass | Pass

All good from here! 😄 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2755/HighFidelity-Beta-PR11242-4a49801217652f1ffe3169ece58fad33bf1d7bac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2755/HighFidelity-Beta-PR11242-4a49801217652f1ffe3169ece58fad33bf1d7bac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2771/HighFidelity-Beta-PR11242-4e7818180b50859a4a8b1036d69c68e7f6ed63c9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2771/HighFidelity-Beta-PR11242-4e7818180b50859a4a8b1036d69c68e7f6ed63c9.exe

**Pull request merged**
