### PR TITLE
for interview

### PR DESCRIPTION
**Pull request by gitrah**
added 'pogo' to avatar menu which calls _characterController.jump() 
added announce pogo option to avatar menu which opens a dialog before the jump
added a creators.scala  which makes a file creator histogram
added selectCompatibleQt.env to select Qt5.10 in a multi Qt environment

### CODE REVIEW

**Comment by huffman** [comment]
test this please

**Comment by huffman** [comment]
@gitrah Here is the error message:

```
16:26:00 CMakeFiles/interface.dir/src/avatar/MyAvatar.cpp.o: In function `MyAvatar::pogo()':
16:26:00 /home/jenkins/workspace/pr-build/label/ubuntu/interface/src/avatar/MyAvatar.cpp:2370: undefined reference to `PogoDialog::announcePogo()'
16:26:00 collect2: error: ld returned 1 exit status
```

Did this compile for you without changes? I don't think we pick up `.cpp`/`.h` files in the `interface/ui` directory. You could try moving them to somewhere in `interface/src`

**Comment by gitrah** [comment]
Sorry, I thought I was just cc-d on the first message.   
Anyway, I never got your link error.  Since cmake (which is not familiar to me) generated the makefiles initially, I just re-ran that after adding new source and everything built fine.

**Comment by gitrah** [comment]
My apologies, I see what I did.  
When it finally came time to commit stuff, I started second-guessing myself about the 'PogoDialog.h/cpp' files not really needing to exist, as they didn't actually subclass a dialog and the sole static method just a few lines of code,  so I removed them and put the dialog code directly in MyAvatar.cpp.  
But this required a lot of new dialog-related include  statements in MyAvatar.cpp which seemed even worse, so I meant to restore PogoDialog.h/cpp, but I see from the commit that I put them in the wrong place (interface/ui instead of interface/src/ui).
Do I need to do a new pull request or can you pull the latest commit from my fork?

**Comment by huffman** [comment]
@gitrah No problem. It will get picked up automatically in the PR because it's from your fork. Our build server automatically picks up any updates as well - it is building right now.

**Pull request closed without merging**
