### PR TITLE
Fix issue of not being able to grab attachments

### PR DESCRIPTION
**Pull request by druiz17**
Fix issue of not be able to grab attachments

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- goto to dev-content/testing and check that you can grab the attachments and attach them you your-self
- do the same in dev-welcome

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3849/HighFidelity-Beta-PR11511-4c8e7bd20887d138b725826b5b9e52462f01db70.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3849/HighFidelity-Beta-PR11511-4c8e7bd20887d138b725826b5b9e52462f01db70.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3850/HighFidelity-Beta-PR11511-cd8fc4917ece11995c0ccdcffe249acfa3433da3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3850/HighFidelity-Beta-PR11511-cd8fc4917ece11995c0ccdcffe249acfa3433da3.exe

**Pull request closed without merging**
