### PR TITLE
RC63 Fix Edit/Asset Browser in HMD mode

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR fix a bug where Edit/Asset Browser and Create/OPEN THIS DOMAIN'S ASSET SERVER are not accessible while in HMD mode

https://highfidelity.fogbugz.com/f/cases/11444/In-HMD-opening-asset-browser-via-Menu-Edit-Asset-Browser-opens-a-black-screen
https://highfidelity.manuscript.com/f/cases/11718/PR12235-Black-Screen-when-Asset-Browser-opened-from-Create-Menu

# Test Plan
- Launch Interface in HMD mode and go to your sandbox. Open Edit/Asset Browser. The Asset Browser window should appear.
- Open Create and click on OPEN THIS DOMAIN'S ASSET SERVER. The Asset Browser window should appear.
- Repeat previous steps in desktop mode. The Asset Browser window should also appear.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6538/app_12235_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6538/HighFidelity-Beta-PR12235-3c12ae892545e568606eecd62ac5ee4cc52f4abc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6538/HighFidelity-Beta-PR12235-3c12ae892545e568606eecd62ac5ee4cc52f4abc.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing on hold, pending fix. Will retest.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6542/app_12235_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6542/HighFidelity-Beta-PR12235-fddbf13796376c989f7f4c980a690140b207c8c7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6542/HighFidelity-Beta-PR12235-fddbf13796376c989f7f4c980a690140b207c8c7.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing completed - PASS @conklin94122

**Pull request merged**
