### PR TITLE
Beta Release 19 - Includes up to Developer Release 5293

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Add priority loading for model entities
* Automatically show address bar after disconnected for X seconds
* Speed up gamma correction in cube map processing
* Default skybox change
* Disable Asset Browser's right-click popup menu if in HMD mode
* eslintrc: accept spaces after function keyword in anonymous functions
* Teleport works with xbox controllers
* Add fade in loading effect
* Add support for ATP protocol to QML
* Fix crash when adding new attachment
* Miscellaneous cmake and render engine improvements
* Mini mirror fades with overlays
* Fix procedural entity transparency
* Faster image processing on load
* Default DS to allow connect for standard groups
* 3D Overlays can be children
* Fix ignore icon stuck in hover state
* Open Asset Browser with Button from Edit.js Toolbar
* Threaded rendering
  * Migrates the rendering of a frame (consisting of an arbitrary number of batches) to the present thread
  * Uses the main window GL context as the execution context for all rendering 
  * Update plugin functionality to use GPU library batches 
* Fix assets example not using correct API
* Fix cubemaps on AMD cards running GL 4.5
* Don't show equip sphere until hand is in position to equip. widen unequip/drop cone
* Add asset server bandwidth to stats
* Fix transparency on procedural shapes
* Entities created using edit.js or imported from marketplace have better positions. 
* Add a button to the sandbox log window to open the log directory
* Fix Asset Browser dialog
* Map oculus touch grip to trigger
* Fix flashing in default skybox, and allow skybox lighting without textures
* Address issues with random camera locations caused by bad HMD sensor poses 
* Fix log flood in debug mode from Buffer::Iterator 
* Don't do fade effect once physics kick in
* Add backup directory setting to domain server
* Add more user activity data

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74cb2d4bcfb634bd1fe6699c5c0c6d54f1b32cfc available at: https://gist.github.com/2520b0c1cffef2ae744a6138d556ee3a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8491-74cb2d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8491-74cb2d4.dmg

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74cb2d4bcfb634bd1fe6699c5c0c6d54f1b32cfc available at: https://gist.github.com/2520b0c1cffef2ae744a6138d556ee3a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8491-74cb2d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8491-74cb2d4.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**FAIL^^
**Additional Test Results + Observations**: No issues of any kind. Expected behavior until trying to test domain stats where it crashed and sent bug splat.

**Comment by cozza13** [comment]
@kevinmthomasse I did not have this issue. It did not crash for me.

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  No issue of any kind now doing quick TP from doman to domain.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |56
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4770 |1515 |3865
**GPU Buffer Count**: |1114 |480 |511
**CPU Memory Usage**: |75505664 |28999680 |79011840
**GPU Memory Usage**: |29270016 |10027008 |20410368
**CPU Texture Count**: |328 |146 |261
**GPU Texture Count**: |769 |817 |816
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |441192300 |142456728 |459972472
**GPU Texture Memory Usage**: |729482338 |363411239 |577145811
**GPU Virtual Memory Usage**: |854617826|488546727|702281299
**Triangle Count**: |139498 |377946 |207815
**Triangle Rate**: |8718625 |23621625 |12224411
**API Drawcall Count**: |174 |139 |147
**Drawcall Count**: |305 |139 |147
**Drawcall Rate**: |19062 |8687 |8647
**State Changes Texture Count**:|128 |172 |159
**Pipeline Count**: |27 |34 |44
**Item Opaques**: |173 |322 |168
**Item Translucents**: |45 |59 |196
**Item Lights**: |17 |67 |34
**Timing Opaques**: |617 |921 |1099
**Timing Translucents**: |56 |121 |638
**Timing Lighting**: |114 |108 |273
**Render Frame**: |1681 |2186 |3809

**Comment by Nex-Pro** [comment]
**PR #8491**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used

## QA Test
**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**: 

Still some annoyances. 
Clicking on a name in the friend list remains unreliable. 
AO and shadows are not good. 
I regularly see the address bar while the GOTO icon is unlit.
The usual gripes with editing objects.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4104 |4454 |4324
**GPU Buffer Count**: |1419 |825 |719
**CPU Memory Usage**: |65691648 |75616256 |81530880
**GPU Memory Usage**: |33411072 |24154112 |33472512
**CPU Texture Count**: |310 |286 |344
**GPU Texture Count**: |561 |814 |783
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |336560372 |789255656 |484474800
**GPU Texture Memory Usage**: |831699137 |1190988538 |840466769
**GPU Virtual Memory Usage**: |956834625|1316124026|965602257
**Triangle Count**: |235645 |845621 |597591
**Triangle Rate**: |13861470 |49742411 |37349437
**API Drawcall Count**: |194 |308 |210
**Drawcall Count**: |285 |351 |1025
**Drawcall Rate**: |16764 |20647 |64062
**State Changes Texture Count**:|159 |330 |338
**Pipeline Count**: |58 |41 |37
**Item Opaques**: |184 |464 |269
**Item Translucents**: |54 |59 |79
**Item Lights**: |24 |78 |32
**Timing Opaques**: |460 |1720 |1204
**Timing Translucents**: |43 |103 |236
**Timing Lighting**: |91 |167 |210
**Render Frame**: |1247 |3393 |2600

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|CHECK
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|POP gun shoots from alongside the barrel.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Can hear wind noises.
**Test 5**|Retest the kick function|SUCCESS
**Test 6**|Switch avatar and make sure it does not crash|SUCCESS
**Test 7**|Test group functions|FAIL See attached image.
**Test 9**|Enrure that you can distance grab|SUCCESS


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|CHECK
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|POP gun shoots from alongside the barrel.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Can hear wind noises.
**Test 5**|Retest the kick function|SUCCESS
**Test 6**|Switch avatar and make sure it does not crash|SUCCESS
**Test 7**|Test group functions|FAIL. See screenshot.
**Test 8**|Retest the kick function|SUCCESS
**Test 9**|Ensure that you can distance grab|SUCCESS


Group ranks were not visible in the settings page. I went through this with thoys and he could not solve it either.
Granting connect permissions to groups did not allow the members to join.
We believe we went though all the necessary steps to make this work.


groupproblem

**HMD RC Test:**

**EYE-01 Test:** 
        Eyes stare straight ahead for the most part.
        But as head is tilted further the eyes eventually rotate upwards or downwards and the iris/pupil becomes hidden by the open eyelid.

**EYE-02 Test: SUCCESS**

**EYE-03 Test: SUCCESS**

**EYE-04 Test: SUCCESS**

**EYE-05 Test: SUCCESS**

**EYE-06 Test: SUCCESS**

**EYE-07 Test: SUCCESS**

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Everything worked smoothly for me

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |3652 |5015 |4694
**GPU Buffer Count**: |905 |981 |950
**CPU Memory Usage**: |71901184 |86581248 |82898944
**GPU Memory Usage**: |27987968 |26161152 |39198720
**CPU Texture Count**: |230 |293 |344
**GPU Texture Count**: |1189 |1562 |1545
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |324666364 |1139458280 |326850752
**GPU Texture Memory Usage**: |591870812 |600300139 |1050427190
**GPU Virtual Memory Usage**: |734774940|743204267|1193331318
**Triangle Count**: |508239 |827501 |872196
**Triangle Rate**: |31764937 |51718812 |54512250
**API Drawcall Count**: |193 |304 |294
**Drawcall Count**: |195 |347 |1216
**Drawcall Rate**: |12187 |21687 |76000
**State Changes Texture Count**:|210 |315 |447
**Pipeline Count**: |19 |37 |62
**Item Opaques**: |244 |444 |308
**Item Translucents**: |43 |45 |78
**Item Lights**: |21 |77 |34
**Timing Opaques**: |547 |1074 |825
**Timing Translucents**: |37 |45 |146
**Timing Lighting**: |76 |81 |109
**Render Frame**: |1259 |2020 |1829

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Ok
**Test 4**|undefined|
**Test 5**|Retest the kick function|Ok
**Test 6**|Switch avatar and make sure it does not crash|Ok
**Test 7**|Test group functions|Failed, had same issue as @Nex-Pro
**Test 8**|Retest the kick function|Ok
**Test 9**|Enrure that you can distance grab|NA

**Comment by sethalves** [comment]
regarding the group-ranks now showing up, could you grep/search your domain-server (not ac, not interface) logs for "No valid access token present"?

**Pull request closed without merging**
