### PR TITLE
Fix hips position when flying

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/13380/Avatar-becomes-invisible-after-shrinking-and-jumping-HMD-mode-only

This PR fix the computation of the hips' position when the avatar is flying and its scale is less than 1/3

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9820/HighFidelity-Beta-PR13175-4b09f1dc308d251b19a9fc393f6556c86b21d93a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9820/HighFidelity-Beta-PR13175-4b09f1dc308d251b19a9fc393f6556c86b21d93a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9820/HighFidelity-Beta-Interface-PR13175-4b09f1dc308d251b19a9fc393f6556c86b21d93a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9820/HighFidelity-Beta-PR13175-4b09f1dc308d251b19a9fc393f6556c86b21d93a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9820/HighFidelity-Beta-Interface-PR13175-4b09f1dc308d251b19a9fc393f6556c86b21d93a.exe

**Comment by luiscuenca** [comment]
# Test Plan
- Launch Interface in HMD mode. 
- Reduce the scale of your avatar to the smallest size possible.
- Try to fly and make sure that your avatar won't disappear.

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 
Decreasing size to minimum possible size does not cause avatar to disappear but increasing avatar size will now cause avatar to disappear.
Log attached
hifi-snap-by--on-2018-05-16_08-30-37


[logs PR13175 fail.zip](https://github.com/highfidelity/hifi/files/2009776/logs.PR13175.fail.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9837/HighFidelity-Beta-PR13175-7b48dc23707ac130be2af21ccad06d356c2b723f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9837/HighFidelity-Beta-PR13175-7b48dc23707ac130be2af21ccad06d356c2b723f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9837/HighFidelity-Beta-Interface-PR13175-7b48dc23707ac130be2af21ccad06d356c2b723f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9837/HighFidelity-Beta-PR13175-7b48dc23707ac130be2af21ccad06d356c2b723f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9837/HighFidelity-Beta-Interface-PR13175-7b48dc23707ac130be2af21ccad06d356c2b723f.exe

**Comment by qligmaloney** [comment]
PASS @conklin94122 
Avatar does not disappear when increasing or decreasing in size and flying

**Pull request merged**
