### PR TITLE
Fix intermittent ability to select particle and light entities

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes the following problems:
- Fix inability to select a particle/light entity after unselecting it by clicking on its icon again in desktop mode. (Cannot click to deselect in HMD mode.)
- Fix inability to select another particle/light entity while inside the entity's bounding box in HMD mode.

Changes made:
- Clicking a selected particle/light entity's icon does not unselect it.
- If your camera is inside an entity's bounding box, you cannot click on the bounding box to x-z translate the entity. (In HMD mode, the laser no longer intersects the bounding box when inside it.)
- If your camera is in side a particle or light entity's bounding box, you can use the entity icon to x-z translate the entity.
- Laser clicking in sky clears current selection.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9460/app_13085_PR_ebd46f1861480037ced290d0cfd04be945709e76.apk

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1. Rez a particle entity, a light entity, and one or two cube or sphere entities in the sky somewhere where there's no entity behind them that can be clicked. 
With the Create app open...
a) Click each entity in turn. Each should get the focus in turn with the manipulation handles displayed for it.
b) Click the light entity once, and then a second time. The entity should retain focus on the second click.
c) Click the light entity twice, and then the particle entity. The particle entity should end up with the focus.
d) Click the light entity, then the background sky. The light entity should lose focus. Click the light entity again. The light entity should get focus.
e) Click the light entity. The entity should get focus. Click and hold the light entity's icon. You should be able to drag it in the x-z plane.

2. Repeat 1) but rez the entities somewhere where there are entities behind that can also be clicked.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9460/HighFidelity-Beta-PR13085-ebd46f1861480037ced290d0cfd04be945709e76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9460/HighFidelity-Beta-Interface-PR13085-ebd46f1861480037ced290d0cfd04be945709e76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9460/HighFidelity-Beta-PR13085-ebd46f1861480037ced290d0cfd04be945709e76.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9460/HighFidelity-Beta-Interface-PR13085-ebd46f1861480037ced290d0cfd04be945709e76.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9575/app_13085_PR_1ccde9a1b29bed5dba20a6231aa13b34c1583bc3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9575/HighFidelity-Beta-PR13085-1ccde9a1b29bed5dba20a6231aa13b34c1583bc3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9575/HighFidelity-Beta-Interface-PR13085-1ccde9a1b29bed5dba20a6231aa13b34c1583bc3.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9872/HighFidelity-Beta-PR13085-6c3174ccf10c71cbad65aeaf97e9d2bf950bfecb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9872/HighFidelity-Beta-PR13085-6c3174ccf10c71cbad65aeaf97e9d2bf950bfecb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9872/HighFidelity-Beta-Interface-PR13085-6c3174ccf10c71cbad65aeaf97e9d2bf950bfecb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9872/HighFidelity-Beta-PR13085-6c3174ccf10c71cbad65aeaf97e9d2bf950bfecb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9872/HighFidelity-Beta-Interface-PR13085-6c3174ccf10c71cbad65aeaf97e9d2bf950bfecb.exe

**Comment by misslivirose** [comment]
@sethalves, @druiz17 - there's a small addition to the edit controller module.  It looks safe to me but as an FYI

**Comment by QliCknox** [comment]
FAIL @conklin94122 
PC Desktop:
With a particle/light entity selected, and your camera outside of the entity's bounding box:
Click-holding the entity's icon or bounding box and dragging the mouse does not allow the entity to travel on the x-plane.

With a particle/light entity selected, and your camera inside of the entity's bounding box:
Click-holding the entity's icon and dragging the mouse does not allow the entity to travel on the x-plane.


Note: The controls are also inverted 90 percent of the time but revert back to normal after moving the objects a few times

**Comment by ctrlaltdavid** [comment]
I've updated the test plan:
- Removed the following item from test 1.v: "Click-holding the entity's icon and dragging the mouse translates the entity in the x-z plane." And have added a note that you're really clicking on the entity's bounding box.
- Added note to test 1.v: "Note: If in doubt as to what the expected behavior is, check translating a sphere entity with similar size and relative location."

Also, note that you shouldn't open Developer > Script Log (HMD Friendly) when using the Create app: doing so stops the Create app from working properly. (Manuscript case 15198.)

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Particle and Light selection appear to be working correctly

**Pull request merged**
