### PR TITLE
don't require authentication to send usage data

### PR DESCRIPTION
**Pull request by birarda**
- enables usage data collection for anonymous users if they are not opted out (Settings -> General -> Privacy)

### CODE REVIEW

**Comment by birarda** [comment]
To test:

Launch the client while not logged in with "Send Data" checked. I'll confirm that I have an event from you for launching the client in the DB.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 688389174841ead7b11ce901382dd8a1b990234f available at: https://gist.github.com/667eb8dbfabd4a7cb57d613306978f2b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7790.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7790.dmg

**Comment by Nex-Pro** [comment]
@birada did it work?

**Comment by birarda** [comment]
@Nex-Pro it did! QA pass!

**Comment by Nex-Pro** [comment]
### That's a pass then.

**Pull request merged**
