### PR TITLE
add audio peak limiter to audio mixer

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
I need to write a test plan.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e7cd06d0e5ed13497977cc30e89519a08393e51 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7fd531541c3436fc75fdf1c009fc8cc88a664025 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f65f99a3e0bff366e422c7b6ab7a959cce779714 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f65f99a3e0bff366e422c7b6ab7a959cce779714 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1fb8f659a7c6908282e82e83e39561a4b47a4d87 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by ZappoMan** [comment]
Test Plan:
- Smoke test... in particular focus on Audio
    - turn on "Developer > Audio > Echo Server Audio" - check that you hear your own voice as expected
    - make sure to have multiple people in a domain and talk to each other, play sounds, and make sure audio works as expected

- Test the peak limiter
    - turn on server echo
    - run this script: [testPeakLimiter.js](https://rawgit.com/ZappoMan/hifi/2ed95542a9070ae20ebe095184e743f00abee2c5/script-archive/tests/audio/testPeakLimiter.js)
    - notice that if you are `dev-playa` or some other "head" build, and you run this script and talk you will hear the audio shift around, back and forth between your ears, you will sometimes hear the audio become quiet when you talk and then get louder again when you stop talking.
    - in *this verison of sandbox/audio-mixer* you will not hear this swimming or apparent noise reduction/increasing... instead you will hear a relatively constant level loud tone and your voice mixed at approximately the same volume constantly

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ed95542a9070ae20ebe095184e743f00abee2c5 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b3a43c40a969d313edb775ec878d5312fc518a00 available at: https://gist.github.com/8ffc765f9e77282647f184f637f5d670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7985.dmg

**Comment by OmegaHeron** [comment]
Ok - number one.  Shattered ear-drum.  Seriously that test tone is INSANELY loud with headphones on.  Anyone else testing this be **warned**.

**Comment by OmegaHeron** [comment]
Stack running on Linux this PR code.  Interface running Windows 10.

It's not working.  Yes, it's limiting loudest input but it's **absolutely not doing the following.**

`in this verison of sandbox/audio-mixer you will not hear this swimming or apparent noise reduction/increasing... instead you will hear a relatively constant level loud tone and your voice mixed at approximately the same volume constantly.`

Note version number for my server console web display.

sc0

It swims, it clicks, the tone swamps other input, it clicks sounding like it's over-running ADC/DAC -/+ max and is just as bad, if not a little worse, than production code.

**Comment by ZappoMan** [comment]
@OmegaHeron - can you please retest using the stack manager built from jenkins on windows. And report. Also -- what results are you getting with the Audio scope?

**Comment by OmegaHeron** [comment]
I'm reinstalling for Windows stack now. I'll grab a picture vs typing.

**Comment by OmegaHeron** [comment]
Before script
hifi-snap-by-omegaheron-on-2016-05-31_12-31-14

During script
hifi-snap-by-omegaheron-on-2016-05-31_12-32-00

**Comment by OmegaHeron** [comment]
Yes @ZappoMan it works on stack + windows.  Now to find out why that's the case for Windows and not for Linux as that's a deal breaker.

**Comment by OmegaHeron** [comment]
I think I see why it's not working on my Linux setup.  I had set noise muting threshold to no muting (1.0) - I *think* this would lead to it not having value for clipped set?  Also - are you just discarding samples where clipping is true?

**Comment by ZappoMan** [comment]
@OmegaHeron - I just tested (the windows build from this PR) with the ​*Noise Muting Threshold*​ set to 1.0 and it works fine as expected -- so long as the PR version of the code doesn't show "flat tops" to the signal, then this is a QA Pass... there's still a possibility of phase effects even with the audio peak limiter in place.

**Comment by ZappoMan** [comment]
I've updated the test plan to reflect the goal of looking for no "flat tops"

**Comment by OmegaHeron** [comment]
I threw it back to QA Pool - I think I'm not the right tester for this one.

**Comment by Triplelexx** [comment]
Worked as expected on Win10, The output was a lot more squared off with the appearance of limiting when running the script.

**Comment by ZappoMan** [comment]
@Triplelexx - squared off for this PR = Fail... this PR should not be squared off... can you confirm? the production/dev build would be squared off... this PR should be pointy.

Thanks.

**Comment by Triplelexx** [comment]
I'll post a few pictures

**Comment by Triplelexx** [comment]
**Production 4904**:
beta

**Dev**

dev

**Comment by PhilipRosedale** [comment]
I think what is screwing up the test is that the audio mixer will mute these streams randomly if "Noise Muting Threshold" in audio environment settings is < 1.0.

**Comment by ZappoMan** [comment]
I have updated the test plan... Please NOTE:

1) You are testing the Stack Manager... not the client... you must run a stack manager that is included in this PR, or is built from this PR's branch.

2) Make sure to **set "Noise Muting Threshold" in audio environment settings is < 1.0.**

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Tested before behavior using a local sandbox and the BETA build of the sandbox.  Installed the PR and run the PR version of the sandbox to gather the "after".  Screen shots included.
4970 before
pr7985 after

**Pull request merged**
