### PR TITLE
Fix MS13500: create-app camera orbit to not jump around on secondary monitor

### PR DESCRIPTION
**Pull request by thoys**
Fixes https://highfidelity.fogbugz.com/f/cases/13500/Manipulating-camera-on-non-primary-monitor-results-in-incorrect-movement

## QA test plan
- Requires dual monitor setup

1. Move Interface to secondary monitor
2. Go to create mode
3. Create entity
4. Hit the F key to focus the entity
5. Hold down the right mouse button and drag it, to orbit around the entity. It should go smooth, like on the primary monitor.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10285/HighFidelity-Beta-PR13279-a06c9ec.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10285/HighFidelity-Beta-PR13279-a06c9ec.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10285/HighFidelity-Beta-Interface-PR13279-a06c9ec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10285/HighFidelity-Beta-PR13279-a06c9ec.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10285/HighFidelity-Beta-Interface-PR13279-a06c9ec.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10297/HighFidelity-Beta-PR13279-3779a47.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10297/HighFidelity-Beta-PR13279-3779a47.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10297/HighFidelity-Beta-Interface-PR13279-3779a47.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10297/HighFidelity-Beta-PR13279-3779a47.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10297/HighFidelity-Beta-Interface-PR13279-3779a47.exe

**Comment by QliCknox** [comment]
Currently testing

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10407/HighFidelity-Beta-PR13279-3779a47.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10407/HighFidelity-Beta-PR13279-3779a47.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10407/HighFidelity-Beta-Interface-PR13279-3779a47.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10407/HighFidelity-Beta-PR13279-3779a47.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10407/HighFidelity-Beta-Interface-PR13279-3779a47.exe

**Comment by QliCknox** [comment]
PASS @conklin94122 
Moving the users view around the entity works smooth on secondary monitors while focused

**Pull request merged**
