### PR TITLE
Phase walk fix bug 17770

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses https://highfidelity.manuscript.com/f/cases/17770/Walking-Running-animation-does-not-transition-smoothly

### **Test** Plan:
1) open interface and go into 3rd person.  
2) push up arrow and back arrow and watch the transition from forward to backward walking. 
3) expected result is less sliding.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12366/HighFidelity-Beta-PR13874-671bf32.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12366/HighFidelity-Beta-PR13874-671bf32.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12366/HighFidelity-Beta-Interface-PR13874-671bf32.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12366/HighFidelity-Beta-PR13874-671bf32.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12366/HighFidelity-Beta-Interface-PR13874-671bf32.dmg

**Comment by hyperlogic** [comment]
This change is minimal and has already been QA'ed on the RC72 branch.  See #13875

**Pull request merged**
