### PR TITLE
[DNM][Case 7734] Asset Browser: Drag & Drop Export Functionality

### PR DESCRIPTION
**Pull request by 1P-Cusack**
Case Link: https://highfidelity.manuscript.com/f/cases/7734

* Drag & Drop world export is currently triggered by the Right Mouse Button pressAndHold as opposed to the expected Left Mouse Button pressAndHold event.
    * If the currently selected item is a viable type (obj, fbx, png, jpg) then the drag event is initiated.
    * If the user right click pressAndHolds on an unselected item, the selection will be changed to the item under the cursor _if_and_only_if_ the item is a viable type after which the drag event is initiated.
    * If the user releases the drag event anywhere within the AssetBrowser window the drag event is canceled without triggering any export functionality.
    * If the user releases the drag event anywhere outside the AssetBrowser window the drag event transitions to a drop event, triggering the export functionality of the dragged asset.
* Objects exported via this method utilize the default settings previously exclusive to addToWorld within the Asset Browser.
* Verified by that [Case 10865] Make Asset Browser multi-select work with Ctrl/Cmd/Shift+Click is still fixed with the changes within this commit.

* Known Issue(s):
    * Left Button pressAndHold control is the desired functionality; however, is currently
      hindered by what appears to be a bug in the interaction of mouse areas/cursor handling
      within Qt.
        * When enabling LeftButton events for treeViewMousePad the treeView rows no longer highlight when clicked.  The treeViewMousePad has propagateComposedEvents: true, which should mean that the events aren't eaten by the mouseArea if things beneath it accept mouse clicks/events.
            * A secondary issue, that seemed to be tied enabling LeftButton events for treeViewMousePad, was what appeared to hovering/tooltip type behavior triggering on the top 2 rows in the browser; however, none of the other rows exhibited this behavior when testing.  This didn't occur when LeftButton events weren't enabled for treeViewMousePad.
        * Looking through the Qt BugReports for open, re-opened, or in progress items related to MouseArea, there appear to be several that may be related at least somewhat to the observed behavior, but aren't an exact match.  See the Related Qt Bugs section below.
    * The icon snippet when dragging doesn't draw outside the AssetBrowser.
        * This could be solved by figuring out how to trigger a re-parenting event along with a position conversion for the drag object when it leaves the bounds of the AssetBrowser/assetBrowseArea to the assetExportArea.
    * pressAndHold interval, though the default interval, seems a bit long, this should
      be tweak-able; however, is lower priority than the Left Button control.

* Related Qt Bugs:
    * Potential Influencer(s) Issue(s)
        * Items under MouseArea don't catch press event if it's not accepted
            * https://bugreports.qt.io/browse/QTBUG-63271
        * MouseArea falsely reports hover when it is a root item or receives a right click
            * https://bugreports.qt.io/browse/QTBUG-36442
        * Hover events can't be propagated from a MouseArea to a QQuickItem
            * https://bugreports.qt.io/browse/QTBUG-34354

    * Bypassed or Circumvented Issue(s)
      _Note_: Implementation Details section within  Commit 40df4b7 may contain more info.
        * DropAreas work weirdly when they intersect
            * https://bugreports.qt.io/browse/QTBUG-30305

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9807/HighFidelity-Beta-PR13174-3191a5b6317d8133ea43cf806d0e81726a6ee0a2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9807/HighFidelity-Beta-PR13174-3191a5b6317d8133ea43cf806d0e81726a6ee0a2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9807/HighFidelity-Beta-Interface-PR13174-3191a5b6317d8133ea43cf806d0e81726a6ee0a2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9807/HighFidelity-Beta-PR13174-3191a5b6317d8133ea43cf806d0e81726a6ee0a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9807/HighFidelity-Beta-Interface-PR13174-3191a5b6317d8133ea43cf806d0e81726a6ee0a2.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
