### PR TITLE
Fix crash

### PR DESCRIPTION
**Pull request by SamGondelman**
When resolving the conflict between two PRs with protocol version changes, I messed up the order.

Test plan:
- Just a protocol version bump, no real way to test this

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16314/HighFidelity-Beta-PR14668-f60b272.apk

**Comment by antoninahifi** [comment]
currently testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16314/HighFidelity-Beta-PR14668-f60b272.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16314/HighFidelity-Beta-Interface-PR14668-f60b272.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16314/HighFidelity-Beta-PR14668-f60b272.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16314/HighFidelity-Beta-Interface-PR14668-f60b272.exe

**Comment by antoninahifi** [comment]
PASS

**Pull request merged**
