### PR TITLE
String pass on Chat.js

### PR DESCRIPTION
**Pull request by misslivirose**
**Test Plan:**
Run the new version of Chat.js and confirm the messages below appear with /help: 

Type "/?" or "/help" for help',
Type "/name <name>" to set your chat name, or "/name" to use your display name. If your display name is not defined, a random name will be used.
Type "/close" to close your overhead chat message.
Type "/say <something>" to display a new message.
Type "/clear" to clear your chat log.
Type "/who" to ask who is in the chat session.
Type "/bigger", "/smaller" or "/normal" to change your avatar size.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1562/HighFidelity-Beta-PR10944-62be0af32d9634d597ff26baa2ccb2e934e18f55.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1562/HighFidelity-Beta-PR10944-62be0af32d9634d597ff26baa2ccb2e934e18f55.dmg

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Run the new version of Chat.js and confirm the messages below appear with /help: `...` | Pass

All good! However /close doesn't actually close out of the chat. It returns an Unknown chat command.

interface_2017-07-12_00-41-03

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by misslivirose** [comment]
@CainFoool that doesn't look like the new version of Chat.js from this PR - all of those are the old messages. Just to confirm, did you load it from /system/chat.js specifically in this build? I've tested on both this PR and on the release client with the new chat script and I'm seeing the expected strings.

**Comment by CainFoool** [comment]
@misslivirose: Sorry, I was using the one from the Marketplace.
All good here!

interface_2017-07-12_01-27-40

**Pull request merged**
