### PR TITLE
Wrap text in query dialogs. Add right margins for input field and but…

### PR DESCRIPTION
**Pull request by vladest**
…tons

https://highfidelity.manuscript.com/f/cases/12818/Asset-import-dialog-has-cosmetic-issues

Test plan:
- Open the Tablet
- Navigate to MENU->EDIT->ASSET BROWSER
- Click the CHOOSE FILE button
- Navigate to a directory with importable assets
- Select a file and click OPEN
- Make sure all elements located in bounds of gray dialog's area and no striked out text

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7699/app_12552_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7700/app_12552_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7700/HighFidelity-Beta-PR12552-126f05f8bd1bb78a808661b361fe6b736d08a86a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7700/HighFidelity-Beta-PR12552-126f05f8bd1bb78a808661b361fe6b736d08a86a.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Fail - @conklin94122 
Line still appears when uploading a file to asset browser.
lines
[hifi-log.txt](https://github.com/highfidelity/hifi/files/1781822/hifi-log.txt)

**Comment by conklin94122** [comment]
@sethalves needs milestone

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7740/app_12552_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7740/HighFidelity-Beta-PR12552-8723b317c907bbab98d6ca4ae61ed4afb713b8b0.dmg

**Comment by vladest** [comment]
please recheck this one

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No strikethrough on text. Looks good.

**Comment by conklin94122** [comment]
@sethalves Needs dev review

**Pull request merged**
