### PR TITLE
Add tealight.js entity server script

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f88433b7bb25c1ad3862d1e302f4507dc32e9e45 available at: https://gist.github.com/dc2db90581f7b73fb09b60115a977da1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9539-f88433b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9539-f88433b.dmg

**Comment by huffman** [comment]
To test:

 1. Add this **server entity script** to a light: https://raw.githubusercontent.com/huffman/hifi/f88433b7bb25c1ad3862d1e302f4507dc32e9e45/unpublishedScripts/marketplace/teaLight/teaLight.js
    1. Use the `Server Script URL` and **not** the `Script URL`
    1. You can use the tea lights at the back of the tutorial room. You will need to remove the `Script URL` first if you do this.
 1. You should see the light flicker a few times a second as shown in the example gif below.

Example gif:
hifi-snap-by-huffman-on-2017-01-27_16-31-23

**Comment by nbq** [comment]
Testing this one now

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Created a new model entity using `atp:/DomainContent/Tutorial/Models/tea_light.fbx`
* Added the script provided to the `Server Script URL` box
 * ***I noticed no flickering on the candle and there are no errors in the Interface logs or the Assignment-Client logs but nothing showed.***

candle-entity-fail

* ***I tested the script on a new box entity using the same method and got the same results***

box-entity-fail

**FAIL**

**Comment by huffman** [comment]
@nbq The script will need to be added to a light entity - it won't create a light on top of a non-light entity.

**Comment by nbq** [comment]
@huffman Revised test:

Tested with a light entity and script provided and it does indeed flicker where it did not before

**PASS**

**Pull request merged**
