### PR TITLE
Combined API docs update

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Condenses the following PRs into a single PR and resolves the merge conflicts:
- https://github.com/highfidelity/hifi/pull/16578
- https://github.com/highfidelity/hifi/pull/16579
- https://github.com/highfidelity/hifi/pull/16580
- https://github.com/highfidelity/hifi/pull/16581

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by kasenvr** [comment]
To new beginnings. :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22825/HighFidelity-Beta-PR16583-ec1e6bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22825/HighFidelity-Beta-Interface-PR16583-ec1e6bc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22825/HighFidelity-Beta-PR16583-ec1e6bc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22825/HighFidelity-Quest-Beta-PR16583-ec1e6bc.apk)

**Pull request merged**
