### PR TITLE
Make Xylophone mallets equipable, make the mallets provide haptic fee…

### PR DESCRIPTION
**Pull request by rabelaiis**
…dback, fix a closing bracket bug stopping the xylophone from working and clean up code according to coding standards. Also fixed cslint issues

### CODE REVIEW

**Comment by rabelaiis** [comment]
## Test plan
This pull request involves only js script changes. 
Load the xylophone in hifi by going to Edit > Open and Run Script File > select 'unpublishedScripts/marketplace/xylophone/xylophoneRezzer.js' (Make sure advanced menus are turned on)
The xylophone should spawn. Verify that the mallets are equipable and that the xylophone keys play music, changes shade and vibrates the controllers when they are hit with the mallet.
I've only tested with the HTC Vive so having someone test with the Oculus wouldn't hurt although I don't know why there would be a difference.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows2016/2030/HighFidelity-Beta-PR11062-dd76c30de5b703a5250fddd4978e869b517922ce.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2066/HighFidelity-Beta-PR11062-119b10886f0f513f0599e99623fabdb45ced26f0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2066/HighFidelity-Beta-PR11062-119b10886f0f513f0599e99623fabdb45ced26f0.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
@rabelaiis Quick question, how do I locate the script? followed your instruction and checked the PR's directory, appdata/local and roaming including scripts folder, cannot seem to locate.

**Comment by rabelaiis** [comment]
@YuppyPlays thanks for looking at this. I'm not sure the unpublished scripts are included in the windows build. I'll have to check. I think the best way to proceed if they are not included is to download the files in the xylophone folder on the branch that is being merged in. The key.js and rezzer.js files are the only ones that change but I think you will need all the files in the folder together to get it to work. You can find them here:
https://github.com/rabelaiis/hifi/tree/119b10886f0f513f0599e99623fabdb45ced26f0/unpublishedScripts/marketplace/xylophone
I'll do a quick look and check if they are in the windows build.

**Comment by YuppyPlays** [comment]
@rabelaiis No problem, I shall await :)

I'll be up for another 2-4hours and will monitor, if no update before I leave I'll release ticket for another tester to test.

**Comment by rabelaiis** [comment]
@YuppyPlays I think I found a better way. Edit > Open and Run Script from URL... > paste in 
https://raw.githubusercontent.com/rabelaiis/hifi/119b10886f0f513f0599e99623fabdb45ced26f0/unpublishedScripts/marketplace/xylophone/xylophoneRezzer.js

That will load all the files you need from github. Let me know if you run into any other problems.

**Comment by rabelaiis** [comment]
Note, I didn't find any references in the windows build.

**Comment by YuppyPlays** [comment]
@rabelaiis 
Excellent thank you! :) Continuing testing now.

**Comment by YuppyPlays** [comment]
Unfortunately did not work - script spawns for a few seconds in the list but nothing shows in game, then disappears from scripts list.

**Comment by rabelaiis** [comment]
It might take a bit to download all the needed files. Do you see the loading bar at the bottom of the hifi screen? I'll re-try on my system

**Comment by rabelaiis** [comment]
I tried uploading the files to the marketplace. So you could also try this url: http://mpassets.highfidelity.com/dddfdb33-0493-427f-9fbf-006958ce6cf2-v1/Xylophone/xylophoneRezzer.js

**Comment by YuppyPlays** [comment]
Tried old and new link and waited, loading content shows for around 2 seconds and disappears around the same time as the script from the list.

Also just for the sake of trying everything, I tried saving the file and loading from disk but to no avail.

Strange.

**Comment by rabelaiis** [comment]
Also make sure to look behind your avatar. Sometimes things spawn there. If you have the developer menus open, you can check the log (ctrl+shift+L) or developer > log to see notifications on when the script is loaded, when the assets are loaded and if there is a bug in the script.

**Comment by YuppyPlays** [comment]
@rabelaiis 

Absolutely correct!, I looked around the first 5 times but with the new link forgot, that seemed to do the trick though!

Will comment results in 2 ticks, just gonna go in HMD :) Thanks again!

**Comment by rabelaiis** [comment]
Thanks, I'll make sure to give a hifi marketplace link next time. Maybe there is something odd with permissioning and github links.

**Comment by YuppyPlays** [comment]
No worries! :)

Also, Testing Complete:

Tested the xylophone to ensure it passes all checks of rezzing correctly, changing the shades of the bars when hit, vibrating controllers upon impact, making the correct tones and had a general time abusing the poor thing as I played many notes for the past 5 minutes to see how it held up. **Pass**

Not sure if it's just because I've only used it in Welcome area, but it's working much smoother now, very responsive to the point where I can actually create a solid beat with ease!

Notes: Vibration occurs in both controllers regardless which one taps, not sure if this is by design or something that needs fixing?

**Comment by rabelaiis** [comment]
Thanks @YuppyPlays! For the controller vibration, the drum set I was basing things on vibrates both controllers. I thought that the xylophone felt responsive enough with that so I didn't spend the time investigating how to vibrate each controller individually.

**Comment by Nex-Pro** [comment]
@rabelaiis

The point made by @YuppyPlays  with regard to both hand controllers vibrating is a good one and has been commented on by several users. As a budding musician I also feel that only the hammer that is hitting a note should vibrate. This isn't a drumset. It is really off-putting to have both hands vibrate for all notes struck rather than the notes struck by individual hands. It feels like you are making mistakes.
If the job designer wants this you should probably look at one of the following API calls: 


 "triggerHapticPulse(float,float,controller::Hand)"

"triggerHapticPulseOnDevice(uint,float,float,controller::Hand)"

"triggerShortHapticPulse(float,controller::Hand)",
or
"triggerShortHapticPulseOnDevice(uint,float,controller::Hand)"

@themelissabrown 
Not part of this Job but the hammer position/length/angle combination is horrible( for the photo real avatar ). I will definitely be customising this. It is easy to re-position one hammer by using the other hand but any equipped hand cannot then be used to re-position an object in the other.
Would be nice if the notes could recover faster( x4 ) can't play fast on this.
( ***goes back to practising the Flintstones theme*** ) 

I'm pretty sure I had a conversation about the haptic on both hands months ago. It was already happening.

@rabelaiis Good work. Thanks.

**Comment by rabelaiis** [comment]
@Nex-Pro I'm curious what your preferred position, length and angle is. It would be nice if the user could toggle between grabbing an object and equipping/wearing it in the position they want. This would accommodate different avatars and preferences. 

I'm familiar with the haptic API and I used it in the code. I'm just not sure how to determine what hand is holding the mallet. I didn't find it readily apparent in the docs so I would have to do some more investigation. 

Thanks for reaching out with feedback @Nex-Pro. It's always useful to get more perspectives.

**Comment by Nex-Pro** [comment]
@rabelaiis @themelissabrown As I wrote, this hand positioning isn't part of this PR. With the photo real male avatar ( Matthew ) the hammers equip between the middle and ring fingers of each hand and tilted down. Worse, the hands are open and thumb up. Looks strange and feels wrong.  @davidkelly  Would be nice to have the volume of each note be related to the striking speed. A little piano-forte, so to speak.

The xylophone is good fun tho.

**Comment by rabelaiis** [comment]
I figured out how to make just a single controller vibrate so I've added that in. I also increased the note recovery. At 4x faster the notes sometimes failed to change color so I only increased the recovery by 3x. It makes the xylophone much more responsive. 

I tried out the photo real avatar (Matthew) and I didn't get the same hand position that you describe @Nex-Pro. For me the mallet is between the index and middle finger and tilted slightly up. I get the same position for the default wooden avatar and this matches the position of the drum stick in the drum set. I'm not sure what could be causing the discrepancy how it equips. 

I also updated the script on the marketplace so it reflects the changes:
http://mpassets.highfidelity.com/dddfdb33-0493-427f-9fbf-006958ce6cf2-v1/Xylophone/xylophoneRezzer.js

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2134/HighFidelity-Beta-PR11062-1f6b92a5190966886712a5356ecef593215eb75b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2134/HighFidelity-Beta-PR11062-1f6b92a5190966886712a5356ecef593215eb75b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2178/HighFidelity-Beta-PR11062-f1d7ef76e7f28cce1bee01f47af6229903327bd9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2178/HighFidelity-Beta-PR11062-f1d7ef76e7f28cce1bee01f47af6229903327bd9.exe

**Comment by misslivirose** [comment]
Looks good to me!

**Pull request merged**
