### PR TITLE
Add performance information to entities list

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Columns added to entities list to provide values for each entity:
- Number of vertices
- Number of textures
- Total size of textures (in GPU)
- Whether or not the entity has transparency
- Number of draw calls

I've obtained the count of textures from existing _textureNames entity property. However I haven't managed to work out how to obtain the other four values from the rendering engine. Any suggestions?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 06f0e76647456c8e518d0adaf91944c0fdfb0ba6 available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-06f0e76.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-06f0e76.dmg

**Comment by RyanDowne** [comment]
@ctrlaltdavid, @ZappoMan is gonna assist you in getting access to this data.

**Comment by hifi-gustavo** [comment]
Build console output for commit: db30e36b3bdbe0d630162d6c7f2e58be6c37509b available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-db30e36.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-db30e36.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 28cfca993f1f3d0050fc33e5f4efaca75759f010 available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-28cfca9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-28cfca9.dmg

**Comment by ZappoMan** [comment]
@ctrlaltdavid - is this still "Do Not Merge"? Do you want someone to review it?

**Comment by ctrlaltdavid** [comment]
@ZappoMan Yes, this is still "do not merge": I've pinged @AlanZimmerman a couple of things about the UI and I still have the "show entities in view" functionality to finish off.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 487cb7d893c827f1318006cecc5a31550a3fb4d2 available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-487cb7d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-487cb7d.dmg

**Comment by ctrlaltdavid** [comment]
Ready for Ryan and Alan to have a look at.

**Comment by RyanDowne** [comment]
I am not seeing any result with number of textures even though I see a result of the total size of them next to it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a06f49f79109b5cd39c13bea705faf4dddad2291 available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-a06f49f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-a06f49f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44282499c5e03eb74e4daaa4c29399c630fd15ea available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-4428249.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-4428249.dmg

**Comment by OmegaHeron** [comment]
On thing I'm seeing that's potentially confusing is; an object has to have moved into view before it populates stats.  So - you start out seeing a lot of zero values then repeatedly refresh list to fill in the blanks.

**Comment by OmegaHeron** [comment]
Also - with limited screen width it might be worth thinking of outputting texture use as megabytes?

**Comment by OmegaHeron** [comment]
Testing Windows 10
It works well in simple domains like heron, but, In dev-playa if you bring entity list to view stats columns you start out seeing like picture below - blank fields - if you hit refresh you **briefly** see stats populate then it returns to blank. 

hifi-snap-by-omegaheron-on-2016-09-12_14-10-41

**Comment by OmegaHeron** [comment]
Disregard above - operator error.  Those first items don't have stats - what I see flashing on reload are items that do that then get pushed out of view in list.

**Comment by OmegaHeron** [comment]
Testing Windows 10
Tested in dev-playa, dev-demo heron and standard home scene.  Data is populated for all entities supported and seem to make sense.  Other than, maybe, wanting to see T-Size as megabytes to ease reading.. no complaints.  Also Verts as K/M might make sense too - I can't seem to resize columns so only way to see full value on large numbers is to continue widening entity list window.

I did notice on some passes it failed to give a T Size value > 0 until I left domain and returned.  That seems to come from opening entity list before a complex entity has fully loaded (visually).

**Comment by OmegaHeron** [comment]
Testing Windows 10

General smoke test passes - specific function seems to pass within notes included above - i.e. this seems to work within expectations.  QA Pass pending any other more specific test criteria.

**Comment by ctrlaltdavid** [comment]
Numbers being populated only when object moves into view... vertex count, texture count, texture size, draw calls, and has transparent are "as rendered" numbers, calculated in the rendering code. So they do need to be loaded and rendered in order to populate the numbers.

Texture size units should be able to be changed to kB or MB, provided all numbers are in that unit, i.e., almost certainly can't have differing units within the column otherwise it won't sort properly. I can try changing to kB or MB if people want.

Texture size erroneously 0 until leave and return to domain: thanks, I'll look into that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa0aeb4563457e529d51fae00f60643bea33c620 available at: https://gist.github.com/18c6a71e13f36256a8207e499e92461c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-fa0aeb4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8532-fa0aeb4.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
All standard tests pass.
Specific functions of this pr pass.
QA Pass.

**Pull request merged**
