### PR TITLE
Add lock on model texs

### PR DESCRIPTION
**Pull request by zzmp**
In response to consistent crashes on parseTexturesToMap.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa82a6f15342e225a01e029c5dd20d1aeb38978f available at: https://gist.github.com/2885596c9a83a3cc228268dca8c9741c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7514.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7514.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54b8a9278d2d99826f1517b10d954edd8bd89d2b available at: https://gist.github.com/2885596c9a83a3cc228268dca8c9741c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7514.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7514.dmg

**Comment by zzmp** [comment]
https://app.asana.com/0/74051501495175/106421247207470

#### Testing

Go to demo and playa and make sure you don't crash.
Import a model with textures, and change those textures a lot. Make sure functionality hasn't degraded, and you don't crash.

**Comment by cozza13** [comment]
-I ran this build in sandbox, playa, demo, cellscience for 10 minutes and no crash
-Switched back to the release build and I in playa after a minute

**Pull request merged**
