### PR TITLE
Defaulting the color formats used in the rendering pipeline to sRGB

### PR DESCRIPTION
**Pull request by samcake**
This is improving the banding.
THe framebuffer rendering is respecting the encoding color forrmat for the render texture.
Thanks to Geenz for raising that problem

### CODE REVIEW

**Comment by samcake** [comment]
You should see way more banding in lighted area like in Playa looking at the lit signs.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5a9d39edf87b484a615a1c343530d2a0739d105 available at: https://gist.github.com/68bf404e246df04d3b7cbe256c98fe8b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7871.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse only**
All standard function tests pass.  No negative change to baseline CPU/GPU/RAM use seen.

As to purpose of this PR - I can't say anything to its impact.  Maybe my monitor or 50 something year old eyes, but, I really can't see much, if any, difference between this and any other variants of Interface.

**Comment by ZappoMan** [comment]
tested on mac as well...

**Pull request merged**
