### PR TITLE
New AFK "away" animation

### PR DESCRIPTION
**Pull request by dooglifeSF**
Change away "kneel" anim to hosted "afk_texting" animation, after review of several options with Joshua.  

Related task:  https://highfidelity.atlassian.net/browse/DEV-402

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by dooglifeSF** [comment]
TEST PLAN:
This is easiest to test with two machines, both going to the same domain.  I tested this in HQ at the avatar pod.  Both machines do not need to run the PR - just the one that will be going "away".  Once both avatars are standing next to each other, hit the "esc" key on the PR-running machine to trigger the away.js script.  This should put the avatar into an animation where they stand and look at their phone, texting etc.  Hitting "esc" again or any other input should break out of away.js and return the avatar to a normal idle.  The script is largely unchanged so should work exactly as before.  The only difference is that we play the "looking at phone and self-absorbedly texting" anim instead of the "kneel" anim.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21918/HighFidelity-Beta-PR16346-589d4e9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21918/HighFidelity-Quest-Beta-PR16346-589d4e9.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21918/HighFidelity-Beta-PR16346-589d4e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21918/HighFidelity-Beta-Interface-PR16346-589d4e9.dmg

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21923/HighFidelity-Beta-PR16346-589d4e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21923/HighFidelity-Beta-Interface-PR16346-589d4e9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21923/HighFidelity-Beta-PR16346-589d4e9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21923/HighFidelity-Quest-Beta-PR16346-589d4e9.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21923/HighFidelity-Beta-PR16346-589d4e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21923/HighFidelity-Beta-Interface-PR16346-589d4e9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21928/HighFidelity-Beta-PR16346-e757a6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21928/HighFidelity-Beta-Interface-PR16346-e757a6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21928/HighFidelity-Beta-PR16346-e757a6f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21928/HighFidelity-Beta-Interface-PR16346-e757a6f.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21931/HighFidelity-Beta-PR16346-e757a6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21931/HighFidelity-Beta-Interface-PR16346-e757a6f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21931/HighFidelity-Beta-PR16346-e757a6f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21931/HighFidelity-Quest-Beta-PR16346-e757a6f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21931/HighFidelity-Beta-PR16346-e757a6f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21931/HighFidelity-Beta-Interface-PR16346-e757a6f.exe

**Pull request merged**
