### PR TITLE
7429 IPD Secondary Task List: bubble.js Scale

### PR DESCRIPTION
**Pull request by Delanir**
7429 IPD Secondary Task List: bubble.js Scale

Delanir/hifi@4a1dd97

Test Plan:

Find someone who can help you activate the bubble.
Turn on the Bubble
Increase your avatar size (double size is ok).
Walk up to your helper.
Expected: The Bubble will trigger and will scale up with your avatar when you reach your helper.

Find someone who can help you activate the bubble.
Turn on the Bubble
Make yourself tiny (think ant-man is ok).
Walk up to your helper.
Expected: The Bubble will trigger and will scale down with your avatar when you reach your helper.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by themelissabrown** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4262/HighFidelity-Beta-PR11626-e9f3dd6e4486f4bbf2236267c8dcc45fb70ad08e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4262/HighFidelity-Beta-PR11626-e9f3dd6e4486f4bbf2236267c8dcc45fb70ad08e.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Find someone who can help you activate the bubble. | Pass
Turn on the Bubble | Pass
Increase your avatar size (double size is ok). | Pass
Walk up to your helper. | Pass
Expected: The Bubble will trigger and will scale up with your avatar when you reach your helper. | Pass
Make yourself tiny (think ant-man is ok). | Pass
Walk up to your helper. | Pass
Expected: The Bubble will trigger and will scale down with your avatar when you reach your helper.  | Pass

All good to me.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by changxc** [comment]
@Delanir @themelissabrown  could you pls direct me to the original spec when you have time? I want to make sure it does not conflict with other bubble functions - thanks

**Pull request merged**
