### PR TITLE
Updated Build Guide language

### PR DESCRIPTION
**Pull request by robin-k-wilson**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10076/HighFidelity-Beta-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.apk

**Comment by AndrewMeadows** [comment]
The windows build failed for some mysterious reason.  Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10086/HighFidelity-Beta-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10086/HighFidelity-Beta-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10086/HighFidelity-Beta-Interface-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10086/HighFidelity-Beta-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10086/HighFidelity-Beta-Interface-PR13228-05a81190083491b2cda2de92c9ae5f03e801681e.exe

**Pull request merged**
