### PR TITLE
Conditional support from JS

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57445557a31e0ef53b0aede7b1e234c274e25280 available at: https://gist.github.com/9000ea8bf9d667df5ca5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.dmg

**Comment by jherico** [comment]
Probably screwed up a cherry-pick, will fix later.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8f6fbf2a3a939092d69cced2217d4c7f447d604 available at: https://gist.github.com/9000ea8bf9d667df5ca5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e6f64833fa2cb6fcffdb2705e77d82007231274 available at: https://gist.github.com/9000ea8bf9d667df5ca5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6167.dmg

**Pull request merged**
