### PR TITLE
Make it easier to exit FingerPaint

### PR DESCRIPTION
**Pull request by kunalgosar**
Exits FingerPainting on press of B button. On your first time running FingerPaint, it will prompt a message telling you how to exit.

Testing instructions:
- Load Fingerpaint script
- Run the script for the first time and see that it prompts a window telling you to press B to exit
- It should show controllers and highlight the B button
- All later instances of running the script should not prompt the window

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a5b10cc51eac56b76b60d07c084665d8f8c51fc7 available at: https://gist.github.com/b885af73571fefd8b62864897dfc85ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10128-a5b10cc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10128-a5b10cc.dmg

**Comment by Nex-Pro** [comment]
@kunalgosar My vive doesn't have a 'B' button.

**Comment by OmegaHeron** [comment]
Tested Windows 10 - CV1 + Touch Controllers
QA Pass

First run - given dialog, able to finger paint and able to exit.  A confirmation that you've exited finger paint mode might be nice, but, that's design not this PR's problem.  

Just to see what happens, I also engaged this from desktop mode with xbox controller.  On first run it presents dialog saying press B to exit.  Not within this PR scope, but, what happens if you have no controllers (like oculus touch/vive or xbox controller?  Does it even make sense to allow this script running in Desktop mode or an HMD without touch controls present?)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 891d52909e5fcca4bf1dfc65f5af7032a4b21303 available at: https://gist.github.com/b885af73571fefd8b62864897dfc85ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10128-891d529.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10128-891d529.dmg

**Pull request merged**
