### PR TITLE
Remove some debug logging left in the safe landing module

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**

### CODE REVIEW

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
PR only affects interface.

Test for normal connection and performance to a domain.
With this PR there should be no messages in the Interface log (Ctrl+Shift+L) of the form
"Safe Landing: Tracking entity ..." or "Safe Landing: load sequence complete".

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12629/HighFidelity-Beta-PR13931-fff6a10.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12629/HighFidelity-Beta-Interface-PR13931-fff6a10.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12629/HighFidelity-Beta-PR13931-fff6a10.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12629/HighFidelity-Beta-Interface-PR13931-fff6a10.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by jakram** [comment]
Currently testing

**Pull request merged**
