### PR TITLE
Grip buttons can grab entities

### PR DESCRIPTION
**Pull request by PhilipRosedale**
Changes to address the Oculus touch - grip buttons can grab/equip objects in a manner similar to the trigger.    Also added a slight delay to the onset of the far search beam.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8506b01f2a0a382f6ac9a7c6c7a17c88ed86c970 available at: https://gist.github.com/eaeb336732f480be21021bfd96d382a2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-8506b01.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-8506b01.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: daa442a1b81ea9c6079d3670b440225081e5982e available at: https://gist.github.com/eaeb336732f480be21021bfd96d382a2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-daa442a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-daa442a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e99210835770e4674fe4aaedc620649f18fceedd available at: https://gist.github.com/eaeb336732f480be21021bfd96d382a2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-e992108.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-e992108.dmg

**Comment by RyanDowne** [comment]
I don't care for the delay. It makes typing on the keyboard frustrating.

**Comment by cozza13** [comment]
I agree with @RyanDowne on the fact typing is a little frustrating. The functionality works per described.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b24a5118a73e41f4511e2f4c2f2d97ee0033f8ce available at: https://gist.github.com/eaeb336732f480be21021bfd96d382a2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-b24a511.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9237-b24a511.dmg

**Comment by birarda** [comment]
This attempts to use the secondary (middle finger button on Oculus Touch) to equip but also uses it to release the equip. This means that if you try and equip something with the middle finger button it equips and immediately drops. 

I'll be making changes to the equip behaviour for a re-submission to Oculus. I'll close this and cherry-pick Philip's initial work on grab to my PR.

**Pull request closed without merging**
