### PR TITLE
auto-show reticle on mouse click

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Fixes this bug... https://app.asana.com/0/26320649018758/95561166865996

Testing notes:
- Run interface
- Run [this version of depthReticle.js script](https://rawgit.com/ZappoMan/hifi/depthReticleWork/examples/depthReticle.js)
- wait about 5 seconds without moving the mouse
- notice the mouse hides
- click the mouse
- notice the mouse auto-shows

**Comment by hifi-gustavo** [comment]
Build console output for commit: 082bb8c4b8d773add9c0fbacb4668c762cf24fa2 available at: https://gist.github.com/3138f15ad98d8cace669<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7330.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7330.dmg

**Comment by howard-stearns** [comment]
This works per the testing notes, but there is a case not covered (which case might also be the same in release?). Is it intended/expected that the mouse NOT hide (ever) if the mouse is held still over a dialog? (Running Scripts, or a Settings dialog, e.g.)

**Comment by ZappoMan** [comment]
@howard-stearns - re "Is it intended/expected that the mouse NOT hide (ever) if the mouse is held still over a dialog? (Running Scripts, or a Settings dialog, e.g.)" -- yes... that's expected behavior

**Comment by howard-stearns** [comment]
OK, thanks. With that def, this passes.

**Pull request merged**
