### PR TITLE
Add error handling to JSConsole

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cd60782e79c5c7a9784efc324626c1dfacc1bd1 available at: https://gist.github.com/fc73a3f2d2f1d72863c8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4871.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4871.dmg

**Comment by PhilipRosedale** [comment]
What's the status on this?

**Comment by huffman** [comment]
@PhilipRosedale This is ready.  I originally wrote this to fix the issue with the Script Editor debug window not showing errors - this doesn't fix that bug because the script editor doesn't use the console for displaying prints/errors, but it does fix a bug with the console itself not showing errors.

**Comment by howard-stearns** [comment]
@huffman, If you’re working in this area, does it make sense to have a look at proper line handling when the text of an entity script is pasted into the script property? (https://app.asana.com/0/32622044445063/33562012389758 <https://app.asana.com/0/32622044445063/33562012389758>)

**Comment by huffman** [comment]
@howard-stearns Are you talking about it in the entity properties window?

**Comment by howard-stearns** [comment]
yes.

**Comment by huffman** [comment]
@howard-stearns That is separate from this PR, but I can look into it.

**Pull request merged**
