### PR TITLE
Fix regression with 'Log in/Sign up' dialog is missing "Forgot Username?" and "Forgot Password?" links

### PR DESCRIPTION
**Pull request by ElderOrb**
*** Test plan ***

Go through login dialogs in desktop and VR and ensure "Forgot Username?" and "Forgot Password?" links are visible and clickable

https://highfidelity.fogbugz.com/f/cases/13789/Log-in-Sign-up-dialog-is-missing-Forgot-Username-and-Forgot-Password-links

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8419/app_12757_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8419/HighFidelity-Beta-PR12757-0a10f961a9cd01113e40fd49a88cedade8d11a1c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8419/HighFidelity-Beta-PR12757-0a10f961a9cd01113e40fd49a88cedade8d11a1c.exe

**Comment by RyanDowne** [comment]
Can this be marked QA ready?

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Wallet, Marketplace, standard login, and create account dialogs checked. Forgot Username/Password buttons are visible, clickable, and the resulting page correctly sends an Email for recovery. Create account works without issue.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8441/HighFidelity-Beta-PR12757-0a10f961a9cd01113e40fd49a88cedade8d11a1c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8441/HighFidelity-Beta-PR12757-0a10f961a9cd01113e40fd49a88cedade8d11a1c.exe

**Comment by sethalves** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/12768

**Pull request closed without merging**
