### PR TITLE
experimental head driven hand pose

### PR DESCRIPTION
**Pull request by ZappoMan**
Just a little script that adds hand controller support for users with only an xbox controller...

Press the X button to toggle on/off the left hand tracking the head.
Press the B button to toggle on/off the left hand tracking the head.

Could use some tweaking still, but this is just an idea for people without hand controllers.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f2962fc807841e73ea45d6f332fd3293435e151 available at: https://gist.github.com/e7097b8763d56499d80f054ce7aa351d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-6f2962f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-6f2962f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ec618b1e2c80cabba389d685795734c984e9755 available at: https://gist.github.com/e7097b8763d56499d80f054ce7aa351d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-0ec618b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-0ec618b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c922591fe475165cf13cc05f4f2963294e4231c7 available at: https://gist.github.com/e7097b8763d56499d80f054ce7aa351d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-c922591.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-c922591.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3dbdde007cf768d960b94bb88fb53aeed4abeee available at: https://gist.github.com/e7097b8763d56499d80f054ce7aa351d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-c3dbdde.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8961-c3dbdde.dmg

**Comment by cozza13** [comment]
Fun!

**Comment by RyanDowne** [comment]
Yeah this worked great! A little hard to learn at first but then you get the hang of it.

**Comment by RyanDowne** [comment]
This doesn't work well with the HUD buttons or the menu

**Comment by ZappoMan** [comment]
@RyanDowne - yeah - I noticed that too... right now I put this in "script-archive" so it wouldn't even be available if someone merged it... I will try to fix the HUD/laser behavior.... I am not sure if the HUDs should still use the 3rd eye -- or if teleport and laser should use the laser from the hand... that's the source of the hud not playing well problem.

**Pull request closed without merging**
