### PR TITLE
Reregister and scale after model change

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/88548846164996

**Comment by howard-stearns** [comment]
Testing notes in ticket.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1891062dd2b84b907885c52811191a864d8023e8 available at: https://gist.github.com/3ac62d746f7bbe42bbdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7365.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7365.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Production code exhibits described issue while this PR behaves proper as model changes.  Tested with a few other models as well - didn't see any issue.  QA Pass

**Pull request merged**
