### PR TITLE
EntityScriptServer should wait for script engine to complete for deleting itself

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Top-level AC class EntityScriptServer contains the EntityEditPacketSender (derived from OctreeEditPacketSender). A pointer to it is registered with the singleton EntityScriptingInterface. When the EntityScriptServer is shutting down it tells the script engine to stop but does not wait for it. By the time the script engine finishes the EntityScriptServer is deleted via a deferred delete and therefore the OctreeEditPacketSender is also deleted and crash occurs when it is used.

This change adds a wait for the script engine to complete when called from EntityScriptServer::shutdownScriptEngine(). It also clears the dangling pointer.

https://highfidelity.manuscript.com/f/cases/11071/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8047/app_12648_PR.apk

**Comment by SimonWalton-HiFi** [comment]
## Test plan

* Run an entity script server (assignment-client -t 5).
* Run a domain-server. The entity script server will connect to it.
* Kill the domain server. After ~5 s the entity script server will notice the failed connection and reset.

### Before fix
The entity script server will crash 100% of the time.

### After fix
The entity script server will not crash. The domain-server can be restarted and will reconnect.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8047/HighFidelity-Beta-PR12648-4fd6eb559bda55ecc7869174fa50bf4dabc8e8ca.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8047/HighFidelity-Beta-PR12648-4fd6eb559bda55ecc7869174fa50bf4dabc8e8ca.exe

**Comment by SimonWalton-HiFi** [comment]
On Win32, if the domain server is repeatedly killed and restarted the entity script server will crash in the native event filter. This appears to be caused by the QFileSystemWatcher that is used to monitor script files. It may be a Qt bug.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Entity script server never crashed and always reconnected to the domain server when it came back online.

**Pull request merged**
