### PR TITLE
Beta Release 34 - Includes up to Developer Release 6083

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Better scrolling and fixed button touching 
* Tablet should work even when not connected to any domain. 
* Adding instrumentation for traces regarding Image and texture loading and preparation 
* Don't auto-bid for sim ownership on entity creation in ESI 
* tablet-ui: Added sortOrder property to buttons 
* use tablet models from s3 until relative model urls work 
* Fix kinect plugin claiming to have hands when not enabled 
* Remove open hours and timezone from domain settings 
* Reduce audio clicks/pops caused by packet loss 
* Physics results use a distinguished packet type. All such packets run through the entity server filter (when supplied), regardless of lock rights.
* Don't send AVATAR_SELF_ID over wire 
* Fix for findEntities not returning some entities that are within range. 
* Send UserActivityLogger events when tablet is opened or closed 
* Remove duplicate snapshot settings in general settings and avatar settings 
* Add injector/avatar attenuation to audio-mixer throttling 
* Cap fbx texture size https://github.com/highfidelity/hifi/pull/9594
* Update crowd-agent and summon for bubble, avatar-mixer optimizations. 
* Allow multiple instances to run if environment variable is set
* Fix for default value insertion in domain server settings 
* PAL performance improvements
* In desktop mode create tablet near mouse click location. 
* More consistent haptics on web overlays and entities
* Make jumping easier in the Vive
* Fixes bugs related to recorded bots
* Fix for hidden cursor while using Export Entities / Import Entities
* Ported PAL to tablet 
* Fix rescale avatar bug. Avatar rescaling was sometimes happening with just the grip buttons. 
* Fix Server Entity Script w/ high update rate causing issues 
* Remove avatarEntityData cruft from settings
* More intrumentation, Pixel Format clean up and minor improvments in texture transfers 
* Add thread names and scripts to chrome traces 
* Add log window for the EntityScriptServer in interface. 
* Update the stopwatch spawn script so that it shows up further in front of your avatar and faces you.
* Log AVX2 support in audio-mixer 
* Implement support for binary data over messages 
This adds `MessageClient` APIs for sending binary data over the message-mixer.
* Fix the filtering problem on color and normals 
* Add silent_packets stat to audio mixer 
* Don't allow a ban of any node on same machine as domain-server 
* lastEditedBy is set by add/edit, but not by physics packets 
* Allow scripts to capture entity clicks. 
* Removed ColorOverlay from TabletButton, added more icon & text states 
* Optimize ignore zone checks for audio mixer 
* Fix entity scripts not loading in certain cases 
* Fix performance problem for invalid "avatarEntityData"
* Fix some bugs that appear when an avatar is a child of something else
*  Moved general preference settings to the tablet
* Added isAway (paused) property to myAvatar 
* Make it Easier to Change Audio Settings in the Tablet UI 
* fix empty descriptors map bug in DS 
* Fix far grabbing making entity jump upon grab 
* Revamped Search Feature on Log Window 
* Parallelize audio packet decoding in mixer 
* Log full i/o stat
* Fix SSE2 macros for Macs
* We have a global entity edit filter in the domain settings
* Loosen audio memoization precondition
* Inform gatekeeper immediately when kicking someone 
* Cleanup some accumulated cruft in pal code. 
* Fix audio packet queue behavior 
* Fix rquestsDomainListData 
* By default, tablet icons will display on the toolbar in desktop mode. https://github.com/highfidelity/hifi/pull/9694
* Logging HMD/Desktop Transitions
* Add finger painting script https://github.com/highfidelity/hifi/pull/9696
* Give implicit access to family tree of server scripted entities in ESS 
* Overlays are now identified by UUIDs rather than unsigned integers
* Fix sorting algorithm for avatar render updates 
* MacOS: Fix for audio, toolbar and tablet. 
* Fix for system toolbar hiding when scripts are reloaded 
* Multi-core Avatar Mixer https://github.com/highfidelity/hifi/pull/9706
* More consistent tablet angle when first creating the tablet. 
* Don't do a haptic pulse when av's hand goes near grabbable tablet 
* More consistent highlights/toggle for toolbar buttons
* Fix recorder.js playback in interface
* Add QMetaObject for AvatarEntityMap
* Avatar bandwidth budget improvements https://github.com/highfidelity/hifi/pull/9726

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e723385df2f382c57270f8a4f6d9a0fcf4e57cdb available at: https://gist.github.com/fd6d875c22c106fbf86db405b8633471<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-e723385.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-e723385.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e723385df2f382c57270f8a4f6d9a0fcf4e57cdb available at: https://gist.github.com/fd6d875c22c106fbf86db405b8633471<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-e723385.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-e723385.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success.  Oculus Touch worked very well with tablet and had no issues of any kind with functionality like closing out the tablet, etc.  


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |62
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |62
**CPU Buffer Count**: |2280 |1301 |1362
**GPU Buffer Count**: |646 |267 |401
**CPU Memory Usage**: |30348560 |15918352 |16831920
**GPU Memory Usage**: |17098160 |8357296 |8635824
**CPU Texture Count**: |249 |133 |141
**GPU Texture Count**: |175 |84 |89
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |244953060 |139871964 |124040948
**GPU Texture Memory Usage**: |591799216 |319043920 |313728771
**GPU Virtual Memory Usage**: |591799216|319043920|313728771
**Triangle Count**: |258923 |64273 |203143
**Triangle Rate**: |15230764 |2216310 |12696437
**API Drawcall Count**: |152 |44 |122
**Drawcall Count**: |2970 |39 |126
**Drawcall Rate**: |174705 |1344 |7875
**State Changes Texture Count**:|301 |62 |174
**Pipeline Count**: |61 |33 |37
**Item Opaques**: |246 |184 |221
**Item Translucents**: |92 |33 |33
**Item Lights**: |11 |52 |23
**Timing Opaques**: |0.901 |0.469 |0.49
**Timing Translucents**: |0.095 |0.04 |0.069
**Timing Lighting**: |0.012 |0.027 |0.016
**Render Frame**: |1.422 |1.833 |1.115


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|undefined
**Test 11**|Test Tablet in 2D and 3D|undefined

**Comment by claudioshg** [comment]
Testing

**Comment by Nex-Pro** [comment]
Testing this Win 10 and Vive

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU
Desktop mode/keyboard mouse/xbox controller/DK2

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desk 1600x900 maximized window.

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |61 |60 |
**CPU Buffer Count**: |1902 |4430 |
**GPU Buffer Count**: |654 |1287 |
**CPU Memory Usage**: |19358160 |67700688 |
**GPU Memory Usage**: |11620976 |42313840 |
**CPU Texture Count**: |246 |318 |
**GPU Texture Count**: |197 |246 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |123006752 |292396032 |
**GPU Texture Memory Usage**: |710230765 |1156632927 |
**GPU Virtual Memory Usage**: |710230765|1190187359|
**Triangle Count**: |258863 |861896 |
**Triangle Rate**: |16178937 |61564000 |
**API Drawcall Count**: |182 |293 |
**Drawcall Count**: |2995 |534 |
**Drawcall Rate**: |187187 |38142 |
**State Changes Texture Count**:|374 |362 |
**Pipeline Count**: |57 |42 |
**Item Opaques**: |277 |483 |
**Item Translucents**: |69 |71 |
**Item Lights**: |11 |48 |
**Timing Opaques**: |0.963 |1.494 |
**Timing Translucents**: |0.235 |0.105 |
**Timing Lighting**: |0.015 |0.039 |
**Render Frame**: |1.634 |3.241 |

DK2

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |75 |76 |
**Present Rate**: |75 |75 |
**Present New Rate**: |75 |75 |
**CPU Buffer Count**: |2052 |3440 |
**GPU Buffer Count**: |672 |1045 |
**CPU Memory Usage**: |20624720 |56121296 |
**GPU Memory Usage**: |12186224 |23300208 |
**CPU Texture Count**: |252 |289 |
**GPU Texture Count**: |206 |185 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |96442808 |500101504 |
**GPU Texture Memory Usage**: |921370964 |904652158 |
**GPU Virtual Memory Usage**: |921370964|904652158|
**Triangle Count**: |397400 |701935 |
**Triangle Rate**: |33116666 |53995000 |
**API Drawcall Count**: |160 |131 |
**Drawcall Count**: |5154 |1428 |
**Drawcall Rate**: |429500 |109846 |
**State Changes Texture Count**:|328 |171 |
**Pipeline Count**: |56 |48 |
**Item Opaques**: |232 |181 |
**Item Translucents**: |72 |36 |
**Item Lights**: |9 |37 |
**Timing Opaques**: |0.801 |0.661 |
**Timing Translucents**: |0.099 |0.072 |
**Timing Lighting**: |0.016 |0.024 |
**Render Frame**: |1.307 |1.803 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok (minus dev-demo)
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass
**Test 11**|Test Tablet in 2D and 3D|It functions in either, if allowed via toggle setting for its use.

Checked - Entity script server and its log display function.  Pass.
Checked - AVX2 detection for audio mixer, win/linux.  Pass.
Checked - Thread count setting and auto detect thread count for audio mixer, win/linux.  Pass.
Checked - Thread count setting and auto detect thread count for avatar mixer, win/linux.  Pass.
Checked defaults for thread setting from fresh sandbox install (Auto off and count = 1).  Pass.
Confirmed issue 9748 is to fix with large numbers of avatars - I saw it in the PR test but convinced myself it was a problem with my setup.  Never again.  So - 9748 will need to get into this once it gets certified.

I'm unable to access dev-distribtuted or distributed or dev-chris2.highfidelity.io;  so I used dev-chris.highfidelity.io to see avatar swarms.

Confirmed bandwidth from AV mixer raises/lowers based on av swarm in/out of view and performance (Interface render) remains acceptable.

Not passing for now due to 9748 issue needing to be fixed.

**Comment by Nex-Pro** [comment]
# P A S S 

Hardware:  Win10 workstation 16gb ram
gtx 1070 8gb


## QA Test
**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: **PASS**
**localhost ATP Upload + Edit Result**: **PASS**
**Echo Server Audio**: **PASS**
**localhost 'harmonicOscillator.js' Result**: **PASS**
**localhost 'reverbTest.js' Result**: **PASS**
**localhost 'playaPerformanceTest.js' Result**: **PASS**
**dev-playa 'playaPerformanceTest.js' Result**: **PASS**
**dev-demo 'playaPerformanceTest.js' Result**: **N/A**
**QA Pass**: **PASS**

**Additional Test Results + Observations**: Finger paint works well.**



**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |89 |89 |
**Present Rate**: |89 |88 |
**Present New Rate**: |90 |90 |
**CPU Buffer Count**: |2829 |4897 |
**GPU Buffer Count**: |895 |1730 |
**CPU Memory Usage**: |39202320 |84773968 |
**GPU Memory Usage**: |23259952 |57576240 |
**CPU Texture Count**: |347 |337 |
**GPU Texture Count**: |295 |307 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |102560860 |137470232 |
**GPU Texture Memory Usage**: |1256159685 |1308428579 |
**GPU Virtual Memory Usage**: |1347940805|1757380899|
**Triangle Count**: |409004 |788741 |
**Triangle Rate**: |37182181 |87637888 |
**API Drawcall Count**: |118 |202 |
**Drawcall Count**: |6986 |662 |
**Drawcall Rate**: |635090 |73555 |
**State Changes Texture Count**:|251 |217 |
**Pipeline Count**: |56 |45 |
**Item Opaques**: |164 |216 |
**Item Translucents**: |89 |86 |
**Item Lights**: |6 |40 |
**Timing Opaques**: |0.595 |0.575 |
**Timing Translucents**: |0.116 |0.156 |
**Timing Lighting**: |0.016 |0.014 |
**Render Frame**: |1.296 |1.48 |

VSYNC on Desktop 1080

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2832 |4241 |
**GPU Buffer Count**: |891 |503 |
**CPU Memory Usage**: |39218704 |71133168 |
**GPU Memory Usage**: |22989616 |23751472 |
**CPU Texture Count**: |350 |309 |
**GPU Texture Count**: |295 |186 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |103300460 |520415840 |
**GPU Texture Memory Usage**: |1050618697 |938479829 |
**GPU Virtual Memory Usage**: |1134504777|1022365909|
**Triangle Count**: |37253 |332207 |
**Triangle Rate**: |2483533 |20762937 |
**API Drawcall Count**: |28 |114 |
**Drawcall Count**: |2666 |235 |
**Drawcall Rate**: |177733 |14687 |
**State Changes Texture Count**:|50 |157 |
**Pipeline Count**: |28 |38 |
**Item Opaques**: |18 |144 |
**Item Translucents**: |9 |37 |
**Item Lights**: |1 |26 |
**Timing Opaques**: |0.089 |0.463 |
**Timing Translucents**: |0.013 |0.084 |
**Timing Lighting**: |0.016 |0.02 |
**Render Frame**: |0.577 |1.547 |

VSYNC on Desktop 4k

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2820 |5226 |
**GPU Buffer Count**: |953 |1707 |
**CPU Memory Usage**: |41384784 |91493904 |
**GPU Memory Usage**: |26888304 |65005680 |
**CPU Texture Count**: |245 |316 |
**GPU Texture Count**: |191 |271 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |136550828 |180547912 |
**GPU Texture Memory Usage**: |1090611962 |1561937537 |
**GPU Virtual Memory Usage**: |1124166394|1813595777|
**Triangle Count**: |215913 |324780 |
**Triangle Rate**: |12700764 |20298750 |
**API Drawcall Count**: |155 |127 |
**Drawcall Count**: |2844 |127 |
**Drawcall Rate**: |167294 |7937 |
**State Changes Texture Count**:|327 |168 |
**Pipeline Count**: |56 |35 |
**Item Opaques**: |232 |155 |
**Item Translucents**: |100 |36 |
**Item Lights**: |10 |25 |
**Timing Opaques**: |0.693 |0.467 |
**Timing Translucents**: |0.118 |0.077 |
**Timing Lighting**: |0.015 |0.017 |
**Render Frame**: |1.362 |1.456 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and do tutorial|**PASS** Perfect
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**PASS**
**Test 4**|Launch firework, on dev-playa, can other hear?|**PASS** , checked with Claudio
**Test 5**|Switch avatar and make sure it does not crash|**PASS**
**Test 6**|Test group functions|untested
**Test 7**|Test Ambisonic audio with markeplace item|**PASS**
**Test 8**|Enrure that you can distance grab|**PASS**
**Test 9**|Bring up and edit an objects with hand controllers|**PASS**
**Test 10**|Test PAL functionality|**PASS**
**Test 11**|Test Tablet in 2D and 3D|**PASS**

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-e723385.exe
## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |3132 |5003 |
**GPU Buffer Count**: |1096 |1454 |
**CPU Memory Usage**: |54518768 |89097968 |
**GPU Memory Usage**: |39563312 |56324848 |
**CPU Texture Count**: |246 |285 |
**GPU Texture Count**: |200 |205 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |113482180 |458420608 |
**GPU Texture Memory Usage**: |981753080 |1127738278 |
**GPU Virtual Memory Usage**: |981753080|1127738278|
**Triangle Count**: |398474 |1672352 |
**Triangle Rate**: |44274888 |152032000 |
**API Drawcall Count**: |164 |277 |
**Drawcall Count**: |5852 |1024 |
**Drawcall Rate**: |650222 |93090 |
**State Changes Texture Count**:|325 |309 |
**Pipeline Count**: |51 |43 |
**Item Opaques**: |217 |470 |
**Item Translucents**: |50 |46 |
**Item Lights**: |8 |51 |
**Timing Opaques**: |0.679 |1.178 |
**Timing Translucents**: |0.079 |0.046 |
**Timing Lighting**: |0.013 |0.015 |
**Render Frame**: |1.15 |2.151 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|PASS: dev-demo was N/A
**Test 2**|Install a fresh copy of "Home' and do tutorial|PASS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|PASS
**Test 4**|Launch firework, on dev-playa, can other hear?|PASS
**Test 5**|Switch avatar and make sure it does not crash|PASS
**Test 6**|Test group functions|undefined
**Test 7**|Test Ambisonic audio with markeplace item|PASS
**Test 8**|Enrure that you can distance grab|PASS
**Test 9**|Bring up and edit an objects with hand controllers|PASS
**Test 10**|Test PAL functionality|PASS
**Test 11**|Test Tablet in 2D and 3D|PASS

Tested with @Nex-Pro

**Comment by nbq** [comment]
testing

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Everything worked as it should


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|All but dev-demo
**Test 2**|Install a fresh copy of "Home' and do tutorial|Done
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|success
**Test 4**|Launch firework, on dev-playa, can other hear?|Yes
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Success
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|Success
**Test 11**|Test Tablet in 2D and 3D|Success

**I noticed the same bug in the QA script again, for the domain stats generator it just checks off and on but does nothing**

**PASS**

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7472efc6376f0abf87aa8536ff79b9eff4b2b75d available at: https://gist.github.com/fd6d875c22c106fbf86db405b8633471<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-7472efc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-7472efc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9527c51ff1d944b26e8b2e79db346e5cae0919c0 available at: https://gist.github.com/fd6d875c22c106fbf86db405b8633471<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-9527c51.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-9527c51.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9527c51ff1d944b26e8b2e79db346e5cae0919c0 available at: https://gist.github.com/a9adb0740700c3db4ff47594ac4eac8c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-9527c51.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9746-9527c51.dmg

**Pull request merged**
