### PR TITLE
Add color support to debug draw marker rendering

### PR DESCRIPTION
**Pull request by hyperlogic**
DebugDraw::addMarker() and addMyAvatarMarker() now use color argument.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test:
   * enter Desktop mode.
   * Select Show Position from the Developer > Avatar menu.
   * A red ringed set of axes should appear about the avatar's hips.  You can see this by going into third person mode.
   * Select Show SensorToWorld Matrix from the Developer > Avatar menu.
   * A white ringed set of axes should appear around the avatar's head.

Both of these calls are using DebugDraw::addMarker calls, one uses a red color, the other white.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 620fd3713c367e6a7efcf9342744823c4aef88a6 available at: https://gist.github.com/fb2bd1518ea6e0c936928c28df90fde5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9008-620fd37.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9008-620fd37.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### Fail

enter Desktop mode. **Check**

Select Show Position from the Developer > Avatar menu. **FAIL** Menu item absent.

A red ringed set of axes should appear about the avatar's hips. You can see this by going into third person mode.

Select Show SensorToWorld Matrix from the Developer > Avatar menu. **Check**

A white ringed set of axes should appear around the avatar's head.: **SUCCESS**

menu

**Comment by hyperlogic** [comment]
@Nex-Pro I mis typed the name of the menu option, it's the `Developer > Avatar > Debug Draw Position` not `Developer > Avatar > Show Position`.

**Comment by OmegaHeron** [comment]
Testing Windows 10 - with revised menu item to select - it works for me.

This PR

hifi-snap-by-omegaheron-on-2016-11-11_12-56-54

Master

hifi-snap-by-omegaheron-on-2016-11-11_12-58-32

**Pull request merged**
