### PR TITLE
RC72: mark and cycle trait instances needing to be sent on mixer reconnect

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

For this test you will need two interface clients. Make sure avatar for interface client A has at least one wearable (there are multiple avatars in the avatars app with wearables).

Connect to the an RC 72 domain with both interface clients. Disconnect from the domain with interface client A and reconnect. Ensure that the interface client B sees the avatar A re-appear in the domain with the correct avatar URL and the correct wearables.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12510/HighFidelity-Beta-PR13906-ae8820c.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12511/HighFidelity-Beta-PR13906-aad1f06.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12511/HighFidelity-Beta-PR13906-aad1f06.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12511/HighFidelity-Beta-Interface-PR13906-aad1f06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12511/HighFidelity-Beta-PR13906-aad1f06.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12511/HighFidelity-Beta-Interface-PR13906-aad1f06.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122  FAIL

Using two clients, each disconnecting multiple different ways while wearing wearables from avatar app.

User A on desktop.
User B on Vive (HMD)

Quitting interface - Using File > Quit and used X to quit the interface, each time the user relaunched and reconnected, the correct wearables were present that the person quit on. There was one instance where a wearable was missing, but was removed entirely and was not an update issue.

Logging in / out - Logging into Hifi or out caused both users to not see the other's wearables. Wearables returned for the other user if that user went into avatar app or wearables app. On further testing, it was not always both users that were affected. Occurs 80%+ of the time.


 Fails PR.

Connecting to another Hifi domain - Changed to another hifi domain for User A and returned, both users saw each other's wearables. User B then did the same and User B could not see User A's wearables when they returned. Additonal attempts to reproduce this were unsuccessful, the wearables appearing every time after for both users.

Connecting to sandbox - User A goes to sandbox and then reconnects to hifi domain, both users saw the others wearables. User B does the same and sees both wearables. Tested 1-2 more times and no difficulties found.

Using back button - User A goes to other hifi domain / home and uses back button to return. Wearables were often not visible to the other party, occurs about 75% of the time when testing this.

Disconnecting network (unplug ethernet) - User A disconnects network cable, reconnects, User B and User A saw each other's wearables. User B disconnects / reconnects, User B does not see User A's wearables while User A does see User B's wearables. Attempted multiple repro's and got it to occur for both users about 50% of the time with the user that is reconnecting not able to see the other users wearables.

Ignore - Tested both sides ignoring each other and both, then with logged in with one and both, no difficulties with any ignoring.

[User_A_Logs.zip](https://github.com/highfidelity/hifi/files/2336955/User_A_Logs.zip)
[User_B_Logs.zip](https://github.com/highfidelity/hifi/files/2336959/User_B_Logs.zip)
Will add video shortly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12530/HighFidelity-Beta-PR13906-0d10a2a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12530/HighFidelity-Beta-PR13906-0d10a2a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12530/HighFidelity-Beta-Interface-PR13906-0d10a2a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12530/HighFidelity-Beta-PR13906-0d10a2a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12530/HighFidelity-Beta-Interface-PR13906-0d10a2a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12537/HighFidelity-Beta-PR13906-edc5f24.apk

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12537/HighFidelity-Beta-PR13906-edc5f24.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12537/HighFidelity-Beta-Interface-PR13906-edc5f24.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12537/HighFidelity-Beta-PR13906-edc5f24.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12537/HighFidelity-Beta-Interface-PR13906-edc5f24.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12542/HighFidelity-Beta-PR13906-0005a8d.apk

**Comment by birarda** [comment]
@JeffClinton the build that got posted appears to have been for the wrong SHA - I'll take the QA ready tag off and wait until it seems like the right build is ready

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12542/HighFidelity-Beta-PR13906-0005a8d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12542/HighFidelity-Beta-Interface-PR13906-0005a8d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12542/HighFidelity-Beta-PR13906-0005a8d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12542/HighFidelity-Beta-Interface-PR13906-0005a8d.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by conklin94122** [comment]
@birarda Going to get a fail, Peter is finishing tests to provide full details.

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Using two clients, each disconnecting multiple different ways while wearing wearables from avatar app.

User A on desktop.
User B on Vive (HMD)

Quitting interface - Using File > Quit and used X to quit the interface, each time the user relaunched and reconnected, the correct wearables were present that the person quit on.

Logging in / out - Change in behaviour here. If user A signed in, User A could not see User B's wearable while User B could see User A's wearable.

Connecting to another Hifi domain - At least twice in a row, connecting to another hifi domain and returning caused one user to be unable to see the others hat. Repeated attempts later did not have any trouble seeing the wearables.

Connecting to sandbox - User A goes to sandbox and then reconnects to hifi domain, both users saw the others wearables. User B does the same and sees both wearables. 

Connect to home (serverless) - User A goes to serverless and then reconnects to hifi domain, both users saw the others wearables. User B does the same and sees both wearables. 

Using back button - User A goes to sandbox and uses back button to return. Wearables were visible.

Disconnecting network (unplug ethernet) - User A disconnects ethernet, reconnects, and could not see User B's wearables while User B could see User A's. Same results in reverse.

Ignore - No difficulties.

[User_B_Logs_8-30.zip](https://github.com/highfidelity/hifi/files/2341688/User_B_Logs_8-30.zip)
[User_A_Logs_8-30.zip](https://github.com/highfidelity/hifi/files/2341689/User_A_Logs_8-30.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12591/HighFidelity-Beta-PR13906-97614e2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12594/HighFidelity-Beta-PR13906-8252d41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12594/HighFidelity-Beta-Interface-PR13906-8252d41.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12594/HighFidelity-Beta-PR13906-8252d41.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12594/HighFidelity-Beta-Interface-PR13906-8252d41.exe

**Comment by conklin94122** [comment]
Marking as QA Ready and rebuilding, per @birarda via @qlipdahlin

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12622/HighFidelity-Beta-PR13906-8252d41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12622/HighFidelity-Beta-Interface-PR13906-8252d41.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12622/HighFidelity-Beta-PR13906-8252d41.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12622/HighFidelity-Beta-Interface-PR13906-8252d41.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Using two clients, each disconnecting multiple different ways while wearing wearables from avatar app.

User A on desktop.
User B on Vive (HMD)

Quitting interface - Using File > Quit and used X to quit the interface, each time the user relaunched and reconnected, the correct wearables were present that the person quit on.

Logging in / out - Both users saw each other's wearables on every login or logout.

Connecting to another Hifi domain - Changing to another domain and back still had wearable's present.

Connecting to sandbox - Changing to sandbox and back still had wearable's present.

Connect to home (serverless) - Changing to serverless and back still had wearable's present.

Using back button - Wearables were present.

Disconnecting network (unplug ethernet) - Wearables were present.

Ignore - No difficulties.

PR Passes.

**Pull request merged**
