### PR TITLE
DOC-187: Mat4 JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- Mat4

Case: https://highfidelity.atlassian.net/browse/DOC-187

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21739/HighFidelity-Beta-PR16299-6e6d438.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21739/HighFidelity-Quest-Beta-PR16299-6e6d438.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21739/HighFidelity-Beta-PR16299-6e6d438.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21739/HighFidelity-Beta-Interface-PR16299-6e6d438.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21739/HighFidelity-Beta-PR16299-6e6d438.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21739/HighFidelity-Beta-Interface-PR16299-6e6d438.exe

**Comment by ctrlaltdavid** [comment]
Fix for getForward() etc. is in: https://github.com/highfidelity/hifi/pull/16300

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21747/HighFidelity-Beta-PR16299-70577b8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21747/HighFidelity-Quest-Beta-PR16299-70577b8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21747/HighFidelity-Beta-PR16299-70577b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21747/HighFidelity-Beta-Interface-PR16299-70577b8.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21750/HighFidelity-Beta-PR16299-70577b8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21750/HighFidelity-Quest-Beta-PR16299-70577b8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21750/HighFidelity-Beta-PR16299-70577b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21750/HighFidelity-Beta-Interface-PR16299-70577b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21750/HighFidelity-Beta-PR16299-70577b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21750/HighFidelity-Beta-Interface-PR16299-70577b8.exe

**Pull request merged**
