### PR TITLE
DNM, getting a build for demo

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0346469828b3da5c00923a16fbb931abd1af72d1 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-0346469.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-0346469.dmg

**Comment by RyanDowne** [comment]
test this please

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0346469828b3da5c00923a16fbb931abd1af72d1 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-0346469.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-0346469.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef9fb5bfc80593e9217fb943b7e4777743ef77c4 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-ef9fb5b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-ef9fb5b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22d2eb8e59a2dc3bd01e8f6ae4af6eb4bea85321 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-22d2eb8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-22d2eb8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: acc676f40d9e871c7e5cb89403b631c7eb80c74b available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-acc676f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-acc676f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a87659d180a5fc8fbcda226c13141853a9f6d19a available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-a87659d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-a87659d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11627c48c11a5c01e30559587be7b0c740373545 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-11627c4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-11627c4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bac4842390096ead5e42be08abda8773735d1070 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-bac4842.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-bac4842.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81804c0f7a0bb39d2d6bff6056ba88165d207ccd available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-81804c0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-81804c0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be9956f2af4c69439fe0e4542378801b4b448bf8 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-be9956f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-be9956f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9fb2a24cc10236a2eadc21677e75bc6597d59df8 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-9fb2a24.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-9fb2a24.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ceeaedc1be50a4cd1221bcafa7ee4fb585ec56de available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-ceeaedc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-ceeaedc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d146e674ae29cfce1b124e75394c3ab341e02868 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-d146e67.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-d146e67.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46bf8de84cc0d53c3c3687f4b8c8bc932842ff52 available at: https://gist.github.com/cc3295acec76698ca93d707ade4ddf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-46bf8de.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8602-46bf8de.dmg

**Pull request closed without merging**
