### PR TITLE
Revert "removed const keyword from Q_INVOKABLE for avatar getter meth…

### PR DESCRIPTION
**Pull request by sethalves**
Reverts highfidelity/hifi#4973

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ba0467aafe8359add5b4b8cc28d1c5ab56fc900b available at: https://gist.github.com/aa8c929398bb45b1bf65<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4977.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4977.dmg

**Comment by AndrewMeadows** [comment]
What was the motivation for reverting these changes?  Did #4973 introduce a bug?

**Comment by sethalves** [comment]
Yes -- see https://github.com/highfidelity/hifi/pull/4978 for all(?) the needed changes.  The upshot was that some other code ended up returning a reference to a local variable.

**Comment by AndrewMeadows** [comment]
Oh right.  **That's** why I made those methods return const reference.  Sigh...

**Pull request merged**
