### PR TITLE
BUGZ-882: Improve error handling on Windows Launcher

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/BUGZ-882

This PR adds some code to catch more errors on the Windows Launcher.
It also creates a copy of the log with the error information (log_error.txt).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20218/HighFidelity-Beta-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20218/HighFidelity-Beta-Interface-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20218/HighFidelity-Beta-PR15871-1f6c4dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20218/HighFidelity-Beta-Interface-PR15871-1f6c4dc.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20223/HighFidelity-Beta-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20223/HighFidelity-Beta-Interface-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20223/HighFidelity-Beta-PR15871-1f6c4dc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20223/HighFidelity-Quest-Beta-PR15871-1f6c4dc.apk)

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20227/HighFidelity-Beta-PR15871-1f6c4dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20227/HighFidelity-Beta-Interface-PR15871-1f6c4dc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20227/HighFidelity-Beta-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20227/HighFidelity-Beta-Interface-PR15871-1f6c4dc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20227/HighFidelity-Beta-PR15871-1f6c4dc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20227/HighFidelity-Quest-Beta-PR15871-1f6c4dc.apk)

**Pull request merged**
