### PR TITLE
BUGZ-658: Don't let the user switch avatar models to Woody

### PR DESCRIPTION
**Pull request by zfox23**
[BUGZ-658](https://highfidelity.atlassian.net/browse/BUGZ-658)

### CODE REVIEW

**Comment by zfox23** [comment]
oops, i just pressed the merge button even though _i was the one who specified pre-merge testing required_

way to go zach

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19961/HighFidelity-Beta-PR15759-4ccd7bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19961/HighFidelity-Beta-Interface-PR15759-4ccd7bd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19961/HighFidelity-Beta-PR15759-4ccd7bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19961/HighFidelity-Quest-Beta-PR15759-4ccd7bd.apk)

**Pull request merged**
