### PR TITLE
Checkbox fix

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a7883aa866706cdf703aed11c68081b741d129e available at: https://gist.github.com/c918bddba6d261011608<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: df591f9ad74aac9de9b1ebe6d237f8fe2b988fdf available at: https://gist.github.com/c918bddba6d261011608<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.dmg

**Comment by huffman** [comment]
Checkboxes in a QWebView are broken on Yosemite + Qt 5.4 using the default QStyle, but setting the style for the QWebView used in WebWindow fixes the issue.  The style-fix was mentioned in a comment in the bug report at https://bugreports.qt.io/browse/QTBUG-42948

**Comment by hifi-gustavo** [comment]
Build console output for commit: 547b0e5ee64ffd1f850cb71a70c97414b91e35c7 available at: https://gist.github.com/c918bddba6d261011608<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4692.dmg

**Comment by huffman** [comment]
This has been tested and is good to go.

**Pull request merged**
