### PR TITLE
Settings > Controls > User Recenter Model now saves properly

### PR DESCRIPTION
**Pull request by hyperlogic**
User Recenter Model in 'Settings > Controls' should now properly save in user preferences.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/20237/Avatar-Leaning-Behavior-Does-Not-Persist-When-Restarting-Interface

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16570/HighFidelity-Beta-PR14742-205e375.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16570/HighFidelity-Beta-PR14742-205e375.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16570/HighFidelity-Beta-Interface-PR14742-205e375.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16671/HighFidelity-Beta-PR14742-205e375.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16671/HighFidelity-Beta-PR14742-205e375.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16671/HighFidelity-Beta-Interface-PR14742-205e375.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16671/HighFidelity-Beta-PR14742-205e375.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16671/HighFidelity-Beta-Interface-PR14742-205e375.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS

Setting is remembered and has the expected effect on startup

**Pull request merged**
