### PR TITLE
Fix hyperlink when far/near grabbing enitities

### PR DESCRIPTION
**Pull request by druiz17**
If an entity as a link to a domain, when you far or near grab the entity. You will be teleport-ed for that domain

Ticket - https://highfidelity.fogbugz.com/f/cases/11744/HMD-Far-or-Near-grabbing-object-with-Hyperlink-does-not-teleport-user

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- create an entity
- edit the entity hyperlink to property to be a valid domain name.
- far or near grabbing the entity should teleport to that domain.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7683/app_12546_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7685/app_12546_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7686/app_12546_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7686/HighFidelity-Beta-PR12546-d12a4f0c18e80f45411e71c44d67b777b9a0c875.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7686/HighFidelity-Beta-PR12546-d12a4f0c18e80f45411e71c44d67b777b9a0c875.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
