### PR TITLE
added collidesWith property to entities list

### PR DESCRIPTION
**Pull request by ericrius1**

### CODE REVIEW

**Comment by ericrius1** [comment]
test script: http://rawgit.com/ericrius1/hifi/editProps/examples/edit.js
https://app.asana.com/0/31759584831097/82794415094071

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a3443968d5547a0e69c9384c41373390344f845 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 168fb67d675971e9133d76de8ba26db9b5f3fc77 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by nbq** [comment]
Testing this one now

**Comment by nbq** [comment]
I loaded the new edit.js as directed and then created a cube in world. Under edit I was able to set the collidesWith flags to the cube.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f8f67ef0b6a1be1b4c3f774958eb47b033ef559 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by nbq** [comment]
In this new build, all the collidesWith are checked and unchecking them does nothing. If you go back to Edit, they are rechecked.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f85916e8083ba1425afae190dd93dd1c974378b2 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94fdf6b091efbc680f696454433a539d810414b3 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by ericrius1** [comment]
@nbq- Thanks for the testing! The checkboxes should be working now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19cd3ec15290ee39c003b1dfa15367e76330e0f1 available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89039747a29cd3868e376b6244955ce1371aedfc available at: https://gist.github.com/2fd53c0f06b02c7023cf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7123.dmg

**Comment by thoys** [comment]
Hi @ericrius1 , tested the script, but cant get any entities showing up. Used your link http://rawgit.com/ericrius1/hifi/editProps/examples/edit.js .
and 2 different viewer builds. See:
fail1
fail2

**Comment by imgntn** [comment]
@thoys i just tested this link and it worked for me -- perhaps add a query string at the end in case it's cached?  http://rawgit.com/ericrius1/hifi/editProps/examples/edit.js?123

**Comment by thoys** [comment]
Works fine now using the regular script link. The rawgit link made it redirect to https:// somehow and gave me messages like these:
```
[02/18 19:12:29] [DEBUG] Web Window JS message: https://rawgit.com/ericrius1/hifi/editProps/examples/html/entityList.html 0 Mixed Content: The page at 'https://rawgit.com/ericrius1/hifi/editProps/examples/html/entityList.html' was loaded over HTTPS, but requested an insecure resource 'qrc:///qtwebchannel/qwebchannel.js'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by imgntn** [comment]
@thoys yeah that mixed content error is a known issue... edit.js scripts can't be served over https at the moment because the qrc connection is not secure-- there's a fix in QT 5.6...

**Comment by thoys** [comment]
:+1:

**Pull request merged**
