### PR TITLE
DO NOT MERGE - STEREO - first cut at attempting to hide menu in full screen

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9aef4b6e763b51707a1a41abfaec3daa50180dd2 available at: https://gist.github.com/3dd9341d61855d75d835<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7c917ce17766c1c72dd39af30d72fa1488f11a3 available at: https://gist.github.com/3dd9341d61855d75d835<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.dmg

**Comment by ZappoMan** [comment]
reopened on master, since this isn't really stereo related

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd0f8d1f9b0ab68a46bd0c71fa006bb87b766d79 available at: https://gist.github.com/3dd9341d61855d75d835<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5620.dmg

**Pull request closed without merging**
