### PR TITLE
[DNM] CreateLite prototype (combined)

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18956/HighFidelity-Beta-PR15451-ca804aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18956/HighFidelity-Quest-Beta-PR15451-ca804aa.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18956/HighFidelity-Beta-PR15451-ca804aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18956/HighFidelity-Beta-Interface-PR15451-ca804aa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18956/HighFidelity-Beta-PR15451-ca804aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18956/HighFidelity-Beta-Interface-PR15451-ca804aa.exe

**Comment by huffman** [comment]
Closing due to DNM

**Pull request closed without merging**
