### PR TITLE
Case 21128: AccountServices, HifiAbout, and WalletScriptingInterface JSDoc review

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
https://highfidelity.manuscript.com/f/cases/21128

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

There are no executable code changes so no testing required.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17558/HighFidelity-Beta-PR15008-4e9d162.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17558/HighFidelity-Beta-PR15008-4e9d162.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17558/HighFidelity-Beta-Interface-PR15008-4e9d162.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17558/HighFidelity-Beta-PR15008-4e9d162.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17558/HighFidelity-Beta-Interface-PR15008-4e9d162.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17562/HighFidelity-Beta-PR15008-2bcee4e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17562/HighFidelity-Beta-Interface-PR15008-2bcee4e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17565/HighFidelity-Beta-PR15008-e20f13f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17565/HighFidelity-Beta-Interface-PR15008-e20f13f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17565/HighFidelity-Beta-PR15008-e20f13f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17565/HighFidelity-Beta-PR15008-e20f13f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17565/HighFidelity-Beta-Interface-PR15008-e20f13f.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17626/HighFidelity-Beta-PR15008-ba3895e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17626/HighFidelity-Quest-Beta-PR15008-ba3895e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17626/HighFidelity-Beta-PR15008-ba3895e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17626/HighFidelity-Beta-Interface-PR15008-ba3895e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17626/HighFidelity-Beta-PR15008-ba3895e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17626/HighFidelity-Beta-Interface-PR15008-ba3895e.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request merged**
