### PR TITLE
VR edit app - Multiple entities test

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1924/HighFidelity-Beta-PR11042-b36ec06b13e957d6ef517c8ac53bf930aec36a80.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1927/HighFidelity-Beta-PR11042-b36ec06b13e957d6ef517c8ac53bf930aec36a80.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1928/HighFidelity-Beta-PR11042-b36ec06b13e957d6ef517c8ac53bf930aec36a80.dmg

**Comment by themelissabrown** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1935/HighFidelity-Beta-PR11042-b36ec06b13e957d6ef517c8ac53bf930aec36a80.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1935/HighFidelity-Beta-PR11042-b36ec06b13e957d6ef517c8ac53bf930aec36a80.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1964/HighFidelity-Beta-PR11042-e0cb0132790ddbe306ed5696ec86d26d01be90e6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1964/HighFidelity-Beta-PR11042-e0cb0132790ddbe306ed5696ec86d26d01be90e6.dmg

**Pull request closed without merging**
