### PR TITLE
Menu polish

### PR DESCRIPTION
**Pull request by jherico**
The OSX and Win32 looks of the menu didn't quite match.  I want them to both look polished and good, so I had to go through several iterations of trying to make changes on one system and then moving it over to see how it looks.  This PR should provide a reasonably nice looking menu with the checkboxes and text well placed in the highlight rectangle on both platforms.

### CODE REVIEW

**Comment by ZappoMan** [comment]
@murillodigital - can you double check this, it looks like Jenkins called this a build failure, but maybe because the only cpp that changed was the test directory, and so maybe it was confused...

**Comment by jherico** [comment]
test this please

**Comment by birarda** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
guys I need to do some more testing to solve this, I won't have time until later tonight, will update the funked PRs then.

**Comment by PhilipRosedale** [comment]
@leo did this work?

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e2106e8313d7a629817ffff33858113cd8aa4d5 available at: https://gist.github.com/79838e3a83092dbbb217<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4724.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4724.dmg

**Comment by murillodigital** [comment]
@PhilipRosedale @jherico issue fixed, review/merge when ready

**Pull request merged**
