### PR TITLE
Fix the spot light direction

### PR DESCRIPTION
**Pull request by samcake**
This pr fix a bug introduced in RC58 where the spot light are rendered with a incorrect rotation 

## TEST PLAN
Run this test rail case:
https://highfidelity.testrail.net/index.php?/cases/view/2965&group_by=cases:section_id&group_order=asc&group_id=621

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5141/HighFidelity-Beta-PR11875-9a31a3dc9523febf490e7257c558d9bfcfd62b34.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5141/HighFidelity-Beta-PR11875-9a31a3dc9523febf490e7257c558d9bfcfd62b34.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
**Pass**
TestRail Result: https://highfidelity.testrail.net/index.php?/tests/view/17038&group_by=cases:section_id&group_order=asc&group_id=621

**Comment by samcake** [comment]
I don;t know how to resolve the license problem?
i tried to get to the linked form and sign it but it doesn't work.
I cannot fill in the fields

**Pull request merged**
