### PR TITLE
RC69: fix case where vegas congestion control would not re-send lost ACK

### PR DESCRIPTION
**Pull request by birarda**
This fixes an issue that affects all reliable connections but most notably was sometimes causing invisible avatars or stuck avatar entities.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10993/HighFidelity-Beta-PR13504-9547bd7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10993/HighFidelity-Beta-PR13504-9547bd7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10993/HighFidelity-Beta-Interface-PR13504-9547bd7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10993/HighFidelity-Beta-PR13504-9547bd7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10993/HighFidelity-Beta-Interface-PR13504-9547bd7.exe

**Comment by birarda** [comment]
#### Test Plan

1. Contact me to coordinate, I will be testing with you.
2. With the latest 0.69.0 RC PR, connect to "canada". It has an avatar-mixer that is specifically "patched" to force the bug this fixes to occur.
3. I will change avatars multiple times - we will confirm that at some point you will stop seeing my avatar change which confirms the bug.
4. Re-perform steps 2-3 with the Interface client from this PR. We will confirm that you see all of my avatar changes.

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Proceeded to DS Canada and worked with Birarda to reproduce the issue of stuck avatar entities. After a bit of work, reproduced 5 of 5 times fairly quickly. He would use clapp app rapidly and then change avatar, this would result in particle effects not appearing and when avatar is changed, the avatar would change its position to the position of the new avatar but would not change to the new avatar (being of light, artemis, small skeleton).

Installed new PR13504 build and using same steps, the system quickly (1-4 seconds) recovered 5 of 5 times. Avatar would change appropriately and particle effects would occasionally reappear.

Birarda confirmed things were good on his end.

**Pull request merged**
