### PR TITLE
Add "size" as synonym for "dimensions" in model overlay property setter

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Model overlay's setProperties() function was missing "size" as a synonym for "dimensions". It was already a synonym in getProperties() and in other overlays' getProperties() and setProperties().


**Test Plan**

Run the attached script.
Two models of an icosahedron should appear in front of you. (These are overlays rather than entities.)
In the program log both overlays' "dimensions" and "size" properties should be reported.
Check that all four sets of values are the same.

[21615.zip](https://github.com/highfidelity/hifi/files/1495074/21615.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5128/HighFidelity-Beta-PR11868-3535071178a43a1338263e9ef3e452831607ce07.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5128/HighFidelity-Beta-PR11868-3535071178a43a1338263e9ef3e452831607ce07.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Pass**

Run the attached script. **Check**
Two models of an icosahedron should appear in front of you. (These are overlays rather than entities.) **Check**
In the program log both overlays' "dimensions" and "size" properties should be reported. **Check**
Check that all four sets of values are the same. **Check**

21615.zip


image

**Pull request merged**
