### PR TITLE
BUGZ-991: Added conditionals to shortcuts to remove overlap

### PR DESCRIPTION
**Pull request by PrestonB1123**
https://highfidelity.atlassian.net/browse/BUGZ-991

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20372/HighFidelity-Beta-PR15923-526b210.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20372/HighFidelity-Quest-Beta-PR15923-526b210.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20372/HighFidelity-Beta-PR15923-526b210.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20372/HighFidelity-Beta-Interface-PR15923-526b210.dmg

**Comment by PrestonB1123** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20375/HighFidelity-Beta-PR15923-526b210.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20375/HighFidelity-Quest-Beta-PR15923-526b210.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20375/HighFidelity-Beta-PR15923-526b210.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20375/HighFidelity-Beta-Interface-PR15923-526b210.dmg

**Pull request merged**
