### PR TITLE
Add Frame Timing and GPU memory to the Stats and user activity log

### PR DESCRIPTION
**Pull request by samcake**
Add Frame Timing and GPU memory to the Stats and user activity log

The gpu::Context now runs a gpu::RangeTimer systematically around the frame execution.
The average values are then available from gpu::Context  and are a fair measurement of the raw performances to render the frame at anytime.

These 2 timings are the most significant work durations  needed to produce the frame
One is on CPU to perform the Batch
Second is on GPU to actually execute the Batch and draw the frame.
These durations are typically the inverse of the frequence aka frame rate (FPS) reported.
when in HMD running at 90Hz, you should see timings <10ms

In a scene performing slower (lower frame rate than 90Hz) then the timings should typically go over 10ms meaning that the interface is not able to produce a new frame fast enough to keep up with the target framerate.

Added these 2 new measurements (GPU_Frame_Time and Batch_Frame_Time) to the user activity log
Added the information of the current GPU memory accounted for in Interface.exe to the user activity log

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76aa541d4aed128201e7ab61cb4b954408ef0629 available at: https://gist.github.com/875f9f5b7340211e14abd8f4beabaca4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9000-76aa541.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9000-76aa541.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 449add6b3452fea62e0df7e890564357206d9183 available at: https://gist.github.com/875f9f5b7340211e14abd8f4beabaca4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9000-449add6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9000-449add6.dmg

**Comment by samcake** [comment]
Test Plan:
No performance or feature changes for the user regardless of the platform.

In the stats ui (press '/') you should now see 2 new counters in the 4th column:
Frame Timing "Batch: XX.X ms" and "GPU: XX.X ms" these values should be representing the duration in ms to produce the frame as measured on the GPU and running the Batch on CPU.

**Comment by samcake** [comment]
I checked that the new fields are coming up in the user logging, all good

**Comment by OmegaHeron** [comment]
Smoke tested Windows 10 - QA Pass

**Pull request merged**
