### PR TITLE
EZRECORD app

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Testing**

Run default scripts plus /scripts/developer/EZrecord.js

"EZRECORD" app icon should display in toolbar/tablet.

Cliking app icon should:
- Start making a recording. 
	Counts down for 3 seconds then starts the actual recording.
	A beep is made each countdown second, with a bigger beep when recording starts.
	A red "REC" indicator is displayed once countdown completes.
- Cancel making a recording if started but haven't finished countdown.
	The "REC" indicator disappears.
	No beep is made.
	No file is saved.
- Finish making a recording.
	The "REC" indicator disappears.
	A beep is made.
	Recording file is saved (on Windows) in C:/Users/USERNAME/AppData/Local/High Fidelity/Interface/Avatar Recordings/yyyymmdd-hhmmss.hfr
		Note: Directory name's "High Fidelity" part may be modified with PR number.
		Note: Filename is in UTC.
	The recording filename is logged in the program log.

Test in:
- Toolbar mode.
- Tablet mode.

Test using:
- Mouse.
- Controller.
- Keyboard shortcut: Ctrl-R

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1083/HighFidelity-Beta-PR10811-48caad1ad252d7841fe1fbabc87f3d9a688412cb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1083/HighFidelity-Beta-PR10811-48caad1ad252d7841fe1fbabc87f3d9a688412cb.exe

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Failed 
| Test | Toolbar | Tablet
-------- | -------- | --------
Start making a recording. | M: Fail, K: Fail | M: Pass, K: Fail
Counts down for 3 seconds then starts the actual recording. | M: Fail, K: Fail | M: Pass, K: Fail
A beep is made each countdown second, with a bigger beep when recording starts. | M: Pass, K: Fail
A red "REC" indicator is displayed once countdown completes. | M: Fail, K: Fail | M: Pass, K: Fail
Cancel making a recording if started but haven't finished countdown. | M: Fail, K: Fail | M: Pass, K: Fail
The "REC" indicator disappears. | M: Fail, K: Fail | M: Pass, K: Fail
No beep is made. | M: Fail, K: Fail | M: Pass, K: Fail
No file is saved. | M: Fail, K: Fail | M: Pass, K: Fail
Finish making a recording. | M: Fail, K: Fail | M: Pass, K: Fail
The "REC" indicator disappears. | M: Fail, K: Fail | M: Pass, K: Fail
A beep is made. | M: Fail, K: Fail | M: Pass, K: Fail
Recording file is saved (on Windows) in C:/Users/USERNAME/AppData/Local/High Fidelity/Interface/Avatar Recordings/yyyymmdd-hhmmss.hfr | M: Fail, K: Fail | M: Pass, K: Fail
Note: Directory name's "High Fidelity" part may be modified with PR number. | M: Fail, K: Fail | M: Pass, K: Fail
Note: Filename is in UTC. | M: Fail, K: Fail | M: Pass, K: Fail
The recording filename is logged in the program log. | M: Fail, K: Fail | M: Pass, K: Fail

(I don't have a controller on me at the moment ready for testing)

Trying to record from the toolbar simply wasn't working at all. Switching to Tablet Mode was the only one which was working. The only way I could get the Toolbar to work was by loading the script, then switching from Tablet to Toolbar - I didn't note them down in the table above but for all of the tests above, it resulted in the Toolbar column resulting in a Pass for the Mouse but still a fail for the Keyboard.

Let me know if you'd like a retest!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by CainFoool** [comment]
# Test Failed

I looked through your commits to see as to why the shortcut wasn't working and noticed that there was a conflict with the reload scripts + your script, and found that you changed the Keyboard Shortcut to Alt + R instead of Ctrl +R so your test plan threw me off. Re-running through the test script provides the results:

| Test | Toolbar (M Mouse, K Keyboard Alt-R) | Tablet (M Mouse, K Keyboard Alt-R)
-------- | -------- | --------
Start making a recording. | M: Fail, K: Pass | M: Pass, K: Pass
Counts down for 3 seconds then starts the actual recording. | M: Fail, K: Pass  | M: Pass, K: Pass
A beep is made each countdown second, with a bigger beep when recording starts. | M: Fail, K: Pass | M: Pass, K: Pass
A red "REC" indicator is displayed once countdown completes. | M: Fail, K: Pass | M: Pass, K: Pass
Cancel making a recording if started but haven't finished countdown. | M: Fail, K: Pass | M: Pass, K: Pass
The "REC" indicator disappears.  | M: Fail, K: Pass | M: Pass, K: Pass
No beep is made. | M: Fail, K: Pass | M: Pass, K: Pass
No file is saved. | M: Fail, K: Pass | M: Pass, K: Pass
Finish making a recording. | M: Fail, K: Pass | M: Pass, K: Pass
The "REC" indicator disappears. | M: Fail, K: Pass | M: Pass, K: Pass
A beep is made. | M: Fail, K: Pass | M: Pass, K: Pass
Recording file is saved (on Windows) in C:/Users/USERNAME/AppData/Local/High Fidelity/Interface/Avatar Recordings/yyyymmdd-hhmmss.hfr | M: Fail, K: Pass | M: Pass, K: Pass
Note: Directory name's "High Fidelity" part may be modified with PR number. | M: Fail, K: Pass | M: Pass, K: Pass
Note: Filename is in UTC. | M: Fail, K: Pass | M: Pass, K: Pass
The recording filename is logged in the program log. | M: Fail, K: Pass | M: Pass, K: Pass

Once again in regards to the toolbar not working, I can only get it to work when switching from Tablet to Toolbar. The icon won't highlight etc when you try to record from either clicking on it or using the shortcut until you do this.

Let me know if you'd like a retest!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by ctrlaltdavid** [comment]
Thanks @CainFoool . Yes, keyboard shortcut was originally meant to be Ctrl-R but got changed because of conflict. Test plan updated.
The toolbar is busted in all latest dev builds. Great that you found a work-around to get it going for testing!

**Comment by CainFoool** [comment]
As the toolbar issue isn't related to your PR (Though I have no clue when that slipped in, I didn't notice until now) this would probably be considered a QA Pass as the toolbar functions normally after switching from the tablet (and your steps pass).

**Pull request merged**
