### PR TITLE
Don't show SPECTATOR app in Desktop mode

### PR DESCRIPTION
**Pull request by zfox23**
#### Test Plan

| Test | Expected Result | Pass/Fail | Notes |
|------|-----------------|-----------|-------|
| Look at your toolbar. | Verify that the "SPECTATOR" button _is not_ present. |||
| Navigate to Settings->General and _uncheck_ "Desktop Tablet Becomes Toolbar". Open your Tablet. | Verify that the "SPECTATOR" app _is not_ present. |||
| Switch to VR mode. Open your Tablet. | Verify that the "SPECTATOR" app _is_ present. |||

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test this when built

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1502/HighFidelity-Beta-PR10930-f170449b887954eb2acd66ee8fcb9cd245d58ec3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1502/HighFidelity-Beta-PR10930-f170449b887954eb2acd66ee8fcb9cd245d58ec3.exe

**Comment by Nex-Pro** [comment]
### PASS

Test | Expected Result | Pass/Fail | Notes
-- | -- | -- | --
Look at your toolbar. | Verify that the "SPECTATOR" button is not present. |  PASS |  
Navigate to Settings->General and uncheck"Desktop Tablet Becomes Toolbar". Open your Tablet. | Verify that the "SPECTATOR" app is notpresent. | PASS  | 
Switch to VR mode. Open your Tablet. | Verify that the "SPECTATOR" app ispresent. |  PASS

in addition checked that spectator app icon is present in HMD toolbar mode. ( non tablet )

**Comment by zfox23** [comment]
[Set "showSpectatorInDesktop" to "false" before merging spectator-camera to master](https://trello.com/c/g2651h5T/233-set-showspectatorindesktop-to-false-before-merging-spectator-camera-to-master)

**Pull request merged**
