### PR TITLE
Prevent Script retries when HTTP errors are irrecoverable

### PR DESCRIPTION
**Pull request by humbletim**
This PR increases the resolution of errors reported by `HTTPResourceRequest` and then uses it in `ScriptCache` to bail early when automatic retry would be futile (such as in the case of HTTP 404 Not Found errors).

[edit: links to client scripts moved to test plan comment below]

_I also had a change available that adds debug stream support to ResourceRequest -- which then allows ScriptCache to quickly log a more specific reason as to why the request failed -- but wasn't sure about including as part of this PR._ https://github.com/highfidelity/hifi/compare/master...humbletim:add-resource-request-dbgstreams

### CODE REVIEW

**Comment by sethalves** [comment]
test plan?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 61452c21a2d877a75be54686e91e15cec6abb9cc available at: https://gist.github.com/b2dc27736e43be4f2830f387da3a1066<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9016-61452c2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9016-61452c2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 144983a9438893d6699b4878c3fb27d07f641628 available at: https://gist.github.com/b2dc27736e43be4f2830f387da3a1066<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9016-144983a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9016-144983a.dmg

**Comment by humbletim** [comment]
To test:

#### Non-Retry Scenarios:

1. Run each of these `client-test-40X.js` scripts (one at a time):
 * https://raw.githubusercontent.com/humbletim/hifi-aux/master/tests/script-cache/test-client-404.js _(tests `ResourceRequest::NotFound`)_
 * https://raw.githubusercontent.com/humbletim/hifi-aux/master/tests/script-cache/test-client-400.js _(tests `ResourceRequest::InvalidURL`)_ 
 * https://raw.githubusercontent.com/humbletim/hifi-aux/master/tests/script-cache/test-client-401.js _(tests `ResourceRequest::AccessDenied`)_
2. Observe that the script prints `BEFORE HTTP 40x ... ...` to the logs
3. Observe that the logs promptly indicate `Error loading file: QUrl("https://httpbin.org/...")` (with any `Retrying...` messages appearing in between)
4. Observe that the script prints `//AFTER HTTP 40X ... ...`

#### Retry Scenario (regression testing):

1. Run https://raw.githubusercontent.com/humbletim/hifi-aux/master/tests/script-cache/test-client-503.js _(tests `ResourceRequest::ServerUnavailable`)_
2. Observe that the script prints `BEFORE HTTP 503 Service Unavailable...` to the logs
3. Observe that the script retries several times to load `https://httpbin.org/status/503?...`, then fails to load (it will take a minute or so to get to get to the last retry)
4. Observe that the script prints `//AFTER HTTP 503 Service Unavailable.`

**Comment by OmegaHeron** [comment]
Testing Windows 10

QA Pass

404, 400, 401 each attempts one load with no subsequent reload attempts.  Pass
503 attempts to load multiple times, ultimately giving up as intended.  Pass
Default scripts load proper, general smoke tests pass.

**Pull request merged**
