### PR TITLE
case BUGZ-690 & BUGZ382 : adding a null check escape to the activeItem. On right click back to …

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/BUGZ-690
https://highfidelity.atlassian.net/browse/BUGZ-382

Found that using the simplified tool bar or any other non window root will set activeFocusItem to null after clicking back to the root window. This does not occur each time and it only seems to happen with right click, as if you are trying to change avatar rotation.

Test case:

1. Click on the simplified tool bar
2. Right click and hold the interface window
3. move mouse around to rotate avatar
4. If your avatar rotates, release right click and try again

you might have to try clicking on icons such as settings, busy, mute and then repeating steps 2 and on. 

The result should be that avatar will rotaate as well as wasd keys should function normally on the first try after clicking on the simplified tool bar. (really any non root app window)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20235/HighFidelity-Beta-PR15877-39fd16f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20235/HighFidelity-Quest-Beta-PR15877-39fd16f.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20235/HighFidelity-Beta-PR15877-39fd16f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20235/HighFidelity-Beta-Interface-PR15877-39fd16f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20235/HighFidelity-Beta-PR15877-39fd16f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20235/HighFidelity-Beta-Interface-PR15877-39fd16f.exe

**Comment by JeffClinton** [comment]
Currently pre-merge testing

**Comment by JeffClinton** [comment]
Updated ticket with issue regarding keyboard focus

**Comment by amerhifi** [comment]
Adding do not merge at the moment. There is second part to this  bug that is not addressed.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20239/HighFidelity-Beta-PR15877-e429b7a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20239/HighFidelity-Quest-Beta-PR15877-e429b7a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20239/HighFidelity-Beta-PR15877-e429b7a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20239/HighFidelity-Beta-Interface-PR15877-e429b7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20239/HighFidelity-Beta-PR15877-e429b7a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20239/HighFidelity-Beta-Interface-PR15877-e429b7a.exe

**Comment by amerhifi** [comment]
I took off dev approved. Testing focusin even and setting the main window as the activeItem

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20242/HighFidelity-Beta-PR15877-9384c5b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20242/HighFidelity-Beta-Interface-PR15877-9384c5b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20242/HighFidelity-Beta-PR15877-9384c5b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20242/HighFidelity-Quest-Beta-PR15877-9384c5b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20242/HighFidelity-Beta-PR15877-9384c5b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20242/HighFidelity-Beta-Interface-PR15877-9384c5b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20270/HighFidelity-Beta-PR15877-386d945.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20270/HighFidelity-Beta-Interface-PR15877-386d945.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20270/HighFidelity-Beta-PR15877-386d945.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20270/HighFidelity-Quest-Beta-PR15877-386d945.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20270/HighFidelity-Beta-PR15877-386d945.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20270/HighFidelity-Beta-Interface-PR15877-386d945.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20272/HighFidelity-Beta-PR15877-84055a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20272/HighFidelity-Beta-Interface-PR15877-84055a6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20272/HighFidelity-Beta-PR15877-84055a6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20272/HighFidelity-Beta-Interface-PR15877-84055a6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20272/HighFidelity-Beta-PR15877-84055a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20272/HighFidelity-Quest-Beta-PR15877-84055a6.apk)

**Comment by qaAdamSmith82** [comment]
Pre-Merge tests pass.  I can easily repro both issues (and Jeff's issue in the Jira ticket) in Master, but I cannot in this PR.

**Pull request merged**
