### PR TITLE
fix sparse rectification for small textures, export for same model at diff URL

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug where texture baking could crash for textures smaller than 128x128

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5406/HighFidelity-Beta-PR11932-0caafba82e692e17bf1b85df95f06851dee79700.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5406/HighFidelity-Beta-PR11932-0caafba82e692e17bf1b85df95f06851dee79700.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5408/HighFidelity-Beta-PR11932-5688a166f8e245c8b3a7a798e516ab1eaeed03ba.dmg

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5452/HighFidelity-Beta-PR11932-5688a166f8e245c8b3a7a798e516ab1eaeed03ba.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6371/app_11932_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6371/HighFidelity-Beta-PR11932-5688a166f8e245c8b3a7a798e516ab1eaeed03ba.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6371/HighFidelity-Beta-PR11932-5688a166f8e245c8b3a7a798e516ab1eaeed03ba.dmg

**Comment by birarda** [comment]
#### Test Plan

1. Run Sandbox/Interface from latest master. Download http://hifi-content.s3.amazonaws.com/alan/dev/radio-mast-3.fbx and drag and drop it onto Interface to upload it to your Asset Server. You should see that it fails to bake and there is a "hazard" symbol beside the asset in your Asset Browser to show that the bake has failed.
2. Run Sandbox/Interface from this PR. Download http://hifi-content.s3.amazonaws.com/alan/dev/radio-mast-3.fbx and drag and drop it onto Interface to upload it to your Asset Server. You should see that baking succeeds and there is checkmark beside the asset in your Asset Browser to show that the bake has succeeded. Note that it may show pending for some time as there are assets in the models folder that will likely be baking first.
3. None of the assets in the models folder should fail to bake (denoted by the "hazard" symbol in the "Use Baked" column). You may need to wait some time for all of those models to bake, but they should always show either "Pending" or a checkmark denoting that they have successfully baked.

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing for PR#11932. PASSED.

**Pull request merged**
