### PR TITLE
Fix security image index clear after back nav

### PR DESCRIPTION
**Pull request by zfox23**
## Test Plan
1. Select the "Wallet" button from the tablet/toolbar
2. Select the "Set up" button on step one of the wallet set up wizard
3. Attempt to select the next button before select a security picture
4. Select a security picture from the group provided (don't press NEXT), then click the back button.
5. Click the "Set Up Wallet" button
6. Verify that no security image is selected and that the "NEXT" button is greyed out.
7. Select a security image, then press NEXT
8. Press the "BACK" button
9. Verify that no security image is selected and that the "NEXT" button is greyed out.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6541/app_12236_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6541/HighFidelity-Beta-PR12236-86ce9766f3ff8b5d746c5b437c8084b8b2c8fc12.exe

**Comment by davidkelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6565/app_12236_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6565/HighFidelity-Beta-PR12236-86ce9766f3ff8b5d746c5b437c8084b8b2c8fc12.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6565/HighFidelity-Beta-PR12236-86ce9766f3ff8b5d746c5b437c8084b8b2c8fc12.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
