### PR TITLE
Beta Release 8 - including up to Development Release 4819

### PR DESCRIPTION
**Pull request by ZappoMan**
- installers named beta
- improve eye tracking when face to face
- installed scripts cleanup: tutorials, tools, default scripts
- fix auto-resize of models on import
- support for equi-rectangular skybox images
- fix bug in rendering Text3DOverlay
- fix bugs in placement and resizing of overlay windows
- position default toolbars on bottom of screen
- reset avatar tracking on exit from away mode
- fix crash during model loading
- fix memory leak in asset download
- fix avatar eye gaze in HMDs
- improve eye contact and saccade behavior
- don't require login for sending usage data
- minor optimization in entities
- move some scripting examples into better location
- fix placement of directory, examples, and edit tool bars
- correctly handle upgrades and tool bar positions
- fix light position for lamp in home set
- remove directory from default scripts
- fix bug in editing tools that didn't show lock and visible icons in entity list
- fix crash in gpu details

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2d4ba277db7461e1d96b945ce8beea0cc4ea74f available at: https://gist.github.com/a537482483eeb4ebd973aa6978df095b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7794.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7794.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7794
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |58.19     |55.05    |59.91       
Present Rate:                     |60.00     |60.00    |60.00       
Present New Rate:                 |58.07     |55.00    |60.02      
Render Stats Num Buffers:         |4942      |4298     |2781        
Render Stats gpu::Buffer Memory:  |39.9Mb    |61.9Mb   |35.4Mb      
Render Stats Num Textures:        |301       |258      |99          
Render Stats gpu::Texture Memory: |801.7Mb   |1170.2Mb |336.3Mb     
Render Stats Triangles:           |454k      |668k     |467k       
Render Stats Drawcalls:           |402       |327      |228         
Render Stats State Changes:	  |256       |187      |62          
Render Stats Items:               |358       |376      |567        
Render Stats Timing:              |31.6ms    |24.8ms   |18.2ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |291Mb     |291Mb    |291Mb       
GPU-Z Memory Used		  |2219Mb    |3099Mb   |2145Mb      
GPU-Z Memory Load		  |24%       |26%      |17%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** (none)
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Comment by judasshuffle** [comment]
Has a look at this

**Comment by judasshuffle** [comment]
Seems fine to me no crashes ran it for a couple of hours with and without the rift.
Colours seem kinda washed out I never get a rich deep black.
Shadows move as if I have a light attached to the back of my head,its peculiar.
Neither of these are specific to the build but want looking at

**Comment by Nex-Pro** [comment]
**PR Build: #7794**
**Intel Desktop 16GB - Nvida GTX770 2GB**
**Testing OS: Windows 10 PRO** 
**Testing Locations: playa, sandbox**
**Smoke Test Results:**   

                                  | playa | cellscience | forum   
----------------------------------|-------|-------------|--------
Render Rate:                      | 60.00 | 57.00-60.00 | 55-60      
Present Rate:                     | 60.00 |       60.00 | 60.00       
Simrate:                          | 59-60 | 57.00-58.00 | 58-60      
Render Stats Num Buffers:         |  6543 |        5362 | 5769             
Render Stats gpu::Buffer Memory:  |  80.4 |        43.0 | 75.1            
Render Stats Num Textures:        |   262 |          62 |  304         
Render Stats gpu::Texture Memory: |1365.9 |       532.7 | 873.5         
Render Stats Triangles:           | 674 K |      1180 K | 426 K        
Render Stats Drawcalls:           |   268 |         346 | 533         
Render Stats Items:               |   380 |        1112 | 537          

**sandbox ‘createtestblocks.js’ Result: Success for blocks and additional FBX, Michelle also observed correct behaviour**
**sandbox Import FBX Result: Success**
**sandbox ‘harmonicOscillator.js’ Result: Success ( Michelle Leckrone present )**
**sandbox Echo Server Audio Result: Success**
**sandbox ‘reverbTest.js’ Result: Success ( Michelle provided a nice commentatary for the test )**
**Additional Test Results Requested:**
**Successful Logout/Crash: Success**

##### Additional notes:
I deleted the ini file before launching this. On launch only two buttons appeared at bottom of screen - 'EXAMPLES' and 'EDIT'
Michelle Lekrone's avatar was not visible at all times ( relaunch was necessary ).
Cellscience destination overlays conflict with and occupy same screen position as example and edit buttons.
My render rates took a big (20-30%) hit when I expanded the stats!
Manipulating the blocks was nice. I was easily able to stand each block on end just using grab.js with mouse.
**HMDs: None**
**Hand Controllers: None**

**Comment by RyanDowne** [comment]
createdice.js didn't work for me. Everything else looked good.

**Pull request merged**
