### PR TITLE
Gcc53

### PR DESCRIPTION
**Pull request by OmegaHeron**
Fix instances of  error: isnan was not declared in this scope with GCC5.3.1/Ubuntu 16.04

In all but these 3 files isnan is prefixed with glm:: - GCC5.2.x accepted this - GCC5.3.1 does not.

Testing would be general smoke test as this should have no impact/change to current function.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by jherico** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5cad1d53c2e211f61dadd06079b95ece65566dc available at: https://gist.github.com/ba80f04c2c2e1e6bbf033fd3672d783f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64f6a59bb3b1d8fc8c46fa3d093ddab0d8c56e96 available at: https://gist.github.com/ba80f04c2c2e1e6bbf033fd3672d783f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 647e991b05773212fc2964eb0a191a6acba9ade0 available at: https://gist.github.com/ba80f04c2c2e1e6bbf033fd3672d783f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7699.dmg

**Comment by ZappoMan** [comment]
Test Plan:
- Smoke Test

**Pull request merged**
