### PR TITLE
Update application to process events in idle loop

### PR DESCRIPTION
**Pull request by huffman**
@birarda @ZappoMan This seemed to fix the issue for me.  It forces events to be processed on the idle loop, and isn't rate limited.

### CODE REVIEW

**Comment by birarda** [comment]
You've got some other changes in here - and I think something like this IS the right approach, but do we really want the Application to process ALL events in the idle?

**Comment by birarda** [comment]
Basically there are categories of things we will want to make sure that no matter the FPS we get off the event stack, input events being one of those things. Are there other things the application might be doing that we DO want performed at the FPS, no matter what that might be?

**Comment by birarda** [comment]
I'm also a little confused as to why this would work? To call idle the Application by definition MUST be processing events, since idle is called as a signal for the idle timer. What about calling processEvents in the idle method kicks it the right way?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 97efe84e86335c65a00f15811213c103c1b8a43d available at: https://gist.github.com/40ab14fba53ff67f8f9d

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a1b438c480af97c506fc17f9a828bc41ec3d5ca available at: https://gist.github.com/2942fff8dd04998b8ce2

**Comment by birarda** [comment]
Found the root cause of the slurping, it's a separate issue. If we're able to call idle with high frequency, we will also be processing touch events at high frequency.

**Pull request closed without merging**
