### PR TITLE
don't accidently fly

### PR DESCRIPTION
**Pull request by sethalves**
- when walking on uneven ground or ramps, the avatar is less likely to accidently fly

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- walk around on ramps or uneven ground, make sure you don't accidentally fly
- make sure you can still fly on purpose

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1290/when-walking-on-an-uneven-surface-avatar-will-sometimes-unexpectedly-fly

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78e59106b40b63c833c7f533ff4fe7bb078d729e available at: https://gist.github.com/b25a4eda244f4b30dc1775d33715029a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-78e5910.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-78e5910.dmg

**Comment by nbq** [comment]
testing this one now

**Comment by sethalves** [comment]
okay, thanks coal.  it sounds like I need to adjust the numbers some more.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1c7ced652720642ed032a966fa38400828245cb available at: https://gist.github.com/b25a4eda244f4b30dc1775d33715029a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-e1c7ced.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-e1c7ced.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aeadbda1e171cfe67f19af7dcf687c02812b5171 available at: https://gist.github.com/b25a4eda244f4b30dc1775d33715029a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-aeadbda.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8360-aeadbda.dmg

**Comment by nbq** [comment]
testing again

**Pull request merged**
