### PR TITLE
Fix deleting entities with children depth > 1 

### PR DESCRIPTION
**Pull request by misslivirose**
Fixes Fogbugz Case 11839 where entities that had 'grandchildren' entities would not delete. 

**Test Plan**
Create three entities such that A is the parent of B, which is the parent of C
Select A
Delete A
All children should delete in addition to A

Import http://mpassets.highfidelity.com/3c6e7cf9-494b-427e-a1b3-87877f99012b-v1/whiteboard_v2.json

Grab the top level entity for the whiteboard (Whiteboard, file wbFrameNew_framed.fbx) and delete
All should delete

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6701/app_12285_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6701/HighFidelity-Beta-PR12285-3aa12eb7df2a36d2d12786f4a2b7669407d479d5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6701/HighFidelity-Beta-PR12285-3aa12eb7df2a36d2d12786f4a2b7669407d479d5.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
