### PR TITLE
[BUGZ-1073] - Add extra padding to the nametag

### PR DESCRIPTION
**Pull request by MiladNazeri**
https://highfidelity.atlassian.net/browse/BUGZ-1073

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20588/HighFidelity-Beta-PR15989-f87e306.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20588/HighFidelity-Quest-Beta-PR15989-f87e306.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20588/HighFidelity-Beta-PR15989-f87e306.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20588/HighFidelity-Beta-Interface-PR15989-f87e306.dmg

**Comment by MiladNazeri** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20597/HighFidelity-Beta-PR15989-f87e306.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20597/HighFidelity-Beta-Interface-PR15989-f87e306.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20597/HighFidelity-Beta-PR15989-f87e306.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20597/HighFidelity-Beta-Interface-PR15989-f87e306.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20597/HighFidelity-Beta-PR15989-f87e306.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20597/HighFidelity-Quest-Beta-PR15989-f87e306.apk)

**Pull request merged**
