### PR TITLE
Disable silence + ban buttons for replicated users

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1001/HighFidelity-Beta-PR10784-0e7ddfd29f478ad8f39c14cf2dc59ad5584643a4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1001/HighFidelity-Beta-PR10784-0e7ddfd29f478ad8f39c14cf2dc59ad5584643a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1075/HighFidelity-Beta-PR10784-86ed61a15dccda8fd29196b72e8ad347c9ad6786.dmg

**Comment by huffman** [comment]
test this please

**Comment by huffman** [comment]
To test you will need 2 computers that can run interface.

1. Setup computer 1 to broadcast you to computer 2
 1. You can do this in the domain settings under "Broadcasting."
 1. On computer 1, `Receiving Servers` should include the ip and ports of the audio mixer and avatar mixer on computer 2.
 1. On computer 2, `Broadcasting Server` should include the ip and ports of the audio mixer and avatar mixer on computer 1.
 1. On computer 1, `Broadcasted Users` should include your hifi account name.
1. Open interface and connect to computer 1, be logged into the account that is being broadcasted (the name you added to `Broadcasted Users`).
1. Open another interface and connect to computer 1. Open the PAL. You should be able to see the other user and be able to silence and ban the user (make sure you have admin privileges). The silence and ban buttons are on the far right.
1. Now connect to computer 2. Open the PAL again, but this time the silence and ban buttons should be disabled.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1078/HighFidelity-Beta-PR10784-86ed61a15dccda8fd29196b72e8ad347c9ad6786.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1078/HighFidelity-Beta-PR10784-86ed61a15dccda8fd29196b72e8ad347c9ad6786.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed 
Test | Result
-------- | --------
Setup computer 1 to broadcast you to computer 2 (You can do this in the domain settings under "Broadcasting.") | Pass
On computer 1, Receiving Servers should include the ip and ports of the audio mixer and avatar mixer on computer 2. | Pass
On computer 2, Broadcasting Server should include the ip and ports of the audio mixer and avatar mixer on computer 1. | Pass
On computer 1, Broadcasted Users should include your hifi account name. | Pass
Open interface and connect to computer 1, be logged into the account that is being broadcasted (the name you added to Broadcasted Users). | Pass
Open another interface and connect to computer 1. Open the PAL. You should be able to see the other user and be able to silence and ban the user (make sure you have admin privileges). The silence and ban buttons are on the far right. | Pass
Now connect to computer 2. Open the PAL again, but this time the silence and ban buttons should be disabled. | Pass

Let me know if you'd like anything else tested.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by huffman** [comment]
Thank you @CainFoool

**Pull request merged**
