### PR TITLE
Enable Map/List storage in the settings

### PR DESCRIPTION
**Pull request by Atlante45**
This enables storing maps and lists in the Settings.

## Test Plan:
- Open your scripting console
- Enter the following
```js
Settings.setValue("Map", { a: 1, b: "2", c: [3, "4"] });
Settings.setValue("List", [ 1, "2", { a: 3, b: "4" }]);
```
- Restart Interface
- Open your scripting console
- Enter the following
```js
JSON.stringify(Settings.getValue("Map"));
```
- The console should print out:
```js
{"a":1,"b":"2","c":[3,"4"]}
```
- Enter the following
```js
JSON.stringify(Settings.getValue("List"));
```
- The console should print out:
```js
[1,"2",{"a":3,"b":"4"}]
```

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Will test when built.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d779779364606de02c30d6c9b085a968a148a22 available at: https://gist.github.com/fb9da3c1ca3f7a15c357cd7785cc886a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10490-0d77977.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10490-0d77977.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

When inputting the first 2 commands, they gave back "undefined" in the console.

With the rest, all went as expected and showed the exact messages.

**Pass**

**Pull request merged**
