### PR TITLE
bake shortbow

### PR DESCRIPTION
**Pull request by thoys**
Baked shortBow's textures.

# QA test
1. Test this using the current release client is ok. You do need a HMD and Hand-Controllers
2. Spawn shortBow by running the following script from the URL: 
`https://raw.githubusercontent.com/thoys/hifi/57692051c0c2bf38177b83cac08134782675450f/unpublishedScripts/marketplace/shortbow/spawnShortbow.js`.
 3. Test if shortBow still works, and all the assets are still visible. You could compare against the shortBow from the marketPlace.

### CODE REVIEW

**Comment by thoys** [comment]
@YuppyPlays you don't need to wait see 1. :)

**Comment by YuppyPlays** [comment]
@thoys Oh my, how did I miss that, My eyes doth lied to me!

Thank you, will test now :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/819/HighFidelity-Beta-PR10728-57692051c0c2bf38177b83cac08134782675450f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/819/HighFidelity-Beta-PR10728-57692051c0c2bf38177b83cac08134782675450f.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

In the latest Dev-download/master, the shortbow and challenges appear to work as expected, **Pass** :)

Please let me know if there is anything more I can do/provide to assist.

**Pull request merged**
