### PR TITLE
8495 No mirror camera in HMD mode

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.fogbugz.com/f/cases/8495
...

## TEST PLAN
- Make sure the menu option view/mirror doesn't appear while in HMD mode.
- Using the shortcut CTRL+H should change to mirror camera only in Desktop mode.  
- Change to mirror mode using this script:
`(function() {
	Camera.setModeString("mirror");
}());`
- You should be allow to change to mirror mode while in HMD.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4680/HighFidelity-Beta-PR11747-f226835876238da2e6852552f72feeda15fd00ab.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4680/HighFidelity-Beta-PR11747-f226835876238da2e6852552f72feeda15fd00ab.dmg

**Comment by ZappoMan** [comment]
What about the scripting interface? Do we still allow people to change the mode via scripts?
I think the answer is "yes"... but we should make sure we have a clear spec/agreement on this.

What happens if I change the mode via script, what do the menus display?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4694/HighFidelity-Beta-PR11747-31b63ffbe6617bfe8ee418488ba2589bdc7662bc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4694/HighFidelity-Beta-PR11747-31b63ffbe6617bfe8ee418488ba2589bdc7662bc.exe

**Comment by ZappoMan** [comment]
So let me give a couple of suggestions. Ultimately we need the PM team @RyanDowne to own deciding how this feature should behave. But here are a couple alternatives I can think of:

Background: there are two ways to change the camera mode: 
a) manually as a user, using the menus
b) using the scripting API

The request was to make it impossible to go into mirror mode while in the HMD. What is ambiguous about that request is, does that mean make it completely impossible, or simply make it so the menu doesn't allow you to do it. We might want to continue to allow the script API to be available so that application developers can build sophisticated applications using the mirror mode. (I don't know if such an application makes sense, I'm just saying this is a possible thing we want to enable.)

Some possible options are:
1) we could disable the menu AND disable the scripting API. If someone calls the scripting API while in HMD mode it has no effect, and subsequent calls to the "get mode" api would return first person or third person, but never mirror mode. There is already code to put you into first person when you switch to HMD, so no need to change that behavior.

2) we could disable the menus, either hiding them or disabling them, but keep the scripting API intact... if someone calls the scripting API while in HMD, it takes effect, and the menu is either readded and check or checked but disabled.

There are other alternatives that relate to the actual treatment of the menus: do we remove it, disabled, etc.... but those are probably less important than first answering the question above about the scripting interface.

**Comment by RyanDowne** [comment]
Back in the day, we rigged up a button on the Hyrdas to show mirror mode while in HMD. It only worked while the button was held down. We did this in response to user tests where people almost always asked: What do I look like? For now, I'd suggest option #2, removing or greying out the option to get into this mode via menu while in HMD. We don't need to, yet, disable the option on the scripting API. Don't even bother coding a special menu case for when you have found your way to that mode via script and have the menu open and want to get out. I think, for now, we protect ourselves from people getting in this mode via menu then re-address what the right design is in a more comprehensive project.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4829/HighFidelity-Beta-PR11747-055fe16677ac075b508a593e84fe248c18ae3fda.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4829/HighFidelity-Beta-PR11747-055fe16677ac075b508a593e84fe248c18ae3fda.exe

**Comment by Nex-Pro** [comment]
testing

**Comment by Nex-Pro** [comment]
Tested with Win10 and Vive.

Make sure the menu option view/mirror doesn't appear while in HMD mode. **SUCCESS**
Using the shortcut CTRL+H should change to mirror camera only in Desktop mode. **SUCCESS**
Change to mirror mode using this script:
(function() { Camera.setModeString("mirror"); }());
You should be allow to change to mirror mode while in HMD. **The view is mirrored but I do not see the avatar.** Tried this several times. ( was not in pause mode ) 
I can switch out of the mirrored mode with ctrl F

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4872/HighFidelity-Beta-PR11747-d75c176fef8e9768926bfcebfb34a6f4c7c5b940.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4872/HighFidelity-Beta-PR11747-d75c176fef8e9768926bfcebfb34a6f4c7c5b940.exe

**Comment by Nex-Pro** [comment]
As I don't know from the test notes what the actual intention of this is I am unable to pass or fail.

Make sure the menu option view/mirror doesn't appear while in HMD mode. **SUCCESS**

Using the shortcut CTRL+H should change to mirror camera only in Desktop mode. **SUCCESS**

Change to mirror mode using this script:
(function() { Camera.setModeString("mirror"); }()); **Mirrors the view but avatar cannot be seen.** Also there is a lot of judder if the user moves their head.

You should be allow to change to mirror mode while in HMD. **Can only change to mirror view by running running the script each time.**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4886/HighFidelity-Beta-PR11747-d75c176fef8e9768926bfcebfb34a6f4c7c5b940.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4886/HighFidelity-Beta-PR11747-d75c176fef8e9768926bfcebfb34a6f4c7c5b940.exe

**Pull request merged**
