### PR TITLE
Fix crash in sit script

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- Try to sit on chair at dev-welcome 
- make sure no crash occurs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc10fc81b79cdd7139e683b3967dd844f30f2e7c available at: https://gist.github.com/242f54959329bb226ed0f68847caa60c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10457-cc10fc8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10457-cc10fc8.dmg

**Comment by YuppyPlays** [comment]
Is this ready for testing? (Don't see QA Ready, just inquiring)

**Comment by vladest** [comment]
I dont have permissions to set flags

**Comment by YuppyPlays** [comment]
Oh right, no worries, I will test shortly, just finishing another task up.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Went to dev-welcome in the provided PR build and sat in seat at spawn, all works fine, no crashing.

**Passed**

**Pull request merged**
