### PR TITLE
Avatar: fix for rendering avatar attachments

### PR DESCRIPTION
**Pull request by hyperlogic**
Repro: open the attachment dialog, Avatar > Attachments... add this cowboy hat to your head.

https://s3.amazonaws.com/hifi-public/tony/cowboy-hat.fbx

The hat is not visible.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/26225263936266/94867778816772
https://app.asana.com/0/26225263936266/94882927820251

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a01c933221c5a65499e75442668adc08c804474 available at: https://gist.github.com/d3e4096786f829a50b4e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7216.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7216.dmg

**Comment by Menithal** [comment]
Attachments work again :+1:

**Comment by Nex-Pro** [comment]
Attachments are not showing. Tried several models and various bones and scales to no effect.

**Comment by Nex-Pro** [comment]
tried  after resetting everything. Logged in as a robot at HQ and no attachments show up when dialog is used.

**Comment by Menithal** [comment]
Thats odd. I couldnt reproduce having the attachments not load on this build. Cleared the PR folders as well.

**Comment by Nex-Pro** [comment]
unistalled my pr builds and re-installed.  Konstantin and I see the problem persists.

**Comment by Menithal** [comment]
Ill try the same. I saw you guys with your attachments in HQ though. Although I kept teleporting out to my own domain to test them. [My results in video format](https://youtu.be/Zh1x8KSOoTg)

**Comment by Nex-Pro** [comment]
Ok. Menithal suggested caming away with ALT and when I cammed back my attachments were visible.

**Pull request merged**
