### PR TITLE
Fix erratic seated idles and fidgets.

### PR DESCRIPTION
**Pull request by dooglifeSF**
Remove all transitions from seated except  seated->idle via isNotSeated.

Fix for https://highfidelity.atlassian.net/browse/DEV-2403

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by dooglifeSF** [comment]
TEST PLAN: run this PR seated on a sit point and look for erratic glitching or slow-mo behavior. Turn on debug text ( and look for stategraph thrashing.  Turn on (in old UI)  developer/showAnimStats and see onscreen printout every frame of what the stategraph is evaluating.  If you screen record this, you would see this ping pong every frame between seated and idle in the buggy version.  Fix should not thrash back and forth.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21865/HighFidelity-Beta-PR16330-df11977.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21865/HighFidelity-Beta-Interface-PR16330-df11977.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21865/HighFidelity-Beta-PR16330-df11977.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21865/HighFidelity-Beta-Interface-PR16330-df11977.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21865/HighFidelity-Beta-PR16330-df11977.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21865/HighFidelity-Quest-Beta-PR16330-df11977.apk)

**Pull request merged**
