### PR TITLE
Case 21517: Fix resource crash on invalid resource (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21517/resource-crash-fix-for-80

https://github.com/highfidelity/hifi/pull/15077

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17824/HighFidelity-Beta-PR15079-a3bc488.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17824/HighFidelity-Quest-Beta-PR15079-a3bc488.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17824/HighFidelity-Beta-PR15079-a3bc488.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17824/HighFidelity-Beta-Interface-PR15079-a3bc488.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17824/HighFidelity-Beta-PR15079-a3bc488.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17824/HighFidelity-Beta-Interface-PR15079-a3bc488.exe

**Comment by qlimnavarro** [comment]
pre merge testing

**Comment by qlimnavarro** [comment]
Pre Merge Pass

**Pull request merged**
