### PR TITLE
MeshPartPayload keeps weak pointer to Model

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
There is an uncommon crash mode where a `MeshPartPayload` instance dereferences a non-null naked pointer to its `Model` and crashes.  The callstack info seems to indicate that the `Model` pointer is a dangling pointer to memory that has already been cleaned up.  For reference see the internal **fogbugz case 4392**.

To solve the problem this PR changes `**MeshPartPayload**` to keep a "weak shared pointer" to its Model.  The payload must lock() it to create a shared_ptr, which is checked for validity before being dereferenced.

There is no way to verify if these changes actually prevent the crash because we do not know how to reproduce it.  The 

### Test Plan:

(1) Login to some domains that have several ModelEntityItems.
(2) Verify that all objects still render correctly.
(3) Teleport around to several domains with objects in them... the interface should not crash as Models are created and deleted.
(4) Make sure the animated robot still animates its limbs in dev-playa.
(5) Verify Avatars still render and update their joints.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/103/HighFidelity-Beta-PR10528-f7db877b7f5d0fa00e5435221df6753ad5dd6e4b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/103/HighFidelity-Beta-PR10528-f7db877b7f5d0fa00e5435221df6753ad5dd6e4b.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed

- (1) Login to some domains that have several ModelEntityItems. ✅
- (2) Verify that all objects still render correctly. ✅
- (3) Teleport around to several domains with objects in them... the interface should not crash as Models are - created and deleted. ✅
- (4) Make sure the animated robot still animates its limbs in dev-playa. ✅
- (5) Verify Avatars still render and update their joints. ✅
- (6) Logout: the interface shouldn't crash on logout. ✅

Everything seemed to go smoothly.

**Pull request merged**
