### PR TITLE
Beta Release 61 - Includes up to Developer Release 7548

### PR DESCRIPTION
**Pull request by conklin94122**
- Login screen now displays properly in the tablet.
- Fixed a minor issue with the on-hover effect of the tablet X button.
- Fixed an issue where the tablet keyboard appears and disappears in the Create menu.
- Fixes tablet "x" button triggering on mouse click.
- Laser scrolling on tablet has been improved.
- Tablet works faster while a domain is still loading.
- Fixed scrollbar on certain Tablet pages while in VR mode. 
- Added a scroll bar for Marketplace categories for cases where the tablet is too small to see all the categories.
- Fixed an issue where the laser didn’t hit the X button on the tablet properly.
- "Edit mode" is now referred to as "Create mode".
- Fixed an issue where equipable items don't always equip when reeled in by far grab.
- Fixed physics issue where grabbing dynamic parent/child entities and bringing them close to the avatar sends you flying.
- Fixed issue where editing in the attachments window scrolled the screen to the top.
- Made it easier to scale the avatar up and down with hand gestures.
- Domain owners can set an objective height limit on avatars, rather than a scale limit.
- Fixed issue where avatar attachment parameters don't scroll.
- Adjusted flying in HMD to be more comfortable and prevent veering off course.
- Improved joystick navigation for gamepad.
- Minor bugfix for keyboard focus when using the Go To app.
- Improved HMD scrolling on certain screens.
- Fixed issue with security picture becoming gray sometimes.
- Multiple outlines and highlight features are exposed to Interface via the selection js API.
- Fixes problem where users having many connections experience a UI lockup when accessing the Connections tab in the People app.
- In the Wallet, onTextField Focus and virtual keyboard collapse bug fixed. 
- A major crash causing deadlocks has been fixed.
- Improved loading performance when entering Avatar Island.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5591/HighFidelity-Beta-PR11969-b2c4cdc6139852e26f832b76602638148ef36878.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5591/HighFidelity-Beta-PR11969-b2c4cdc6139852e26f832b76602638148ef36878.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5610/HighFidelity-Beta-PR11969-d0f088164b6770102646f3c7fa87bea574e0716b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5610/HighFidelity-Beta-PR11969-d0f088164b6770102646f3c7fa87bea574e0716b.dmg

**Comment by tapalisa** [comment]
Four people have tested this PR in the last 24 hours who do not have their environment variable set. Please set your tester environment variable!!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5632/HighFidelity-Beta-PR11969-1c83d7a1ef1ea44ac34ead1c4ba92317e427d02a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5632/HighFidelity-Beta-PR11969-1c83d7a1ef1ea44ac34ead1c4ba92317e427d02a.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5637/HighFidelity-Beta-PR11969-68177c7e719ed72e7635b4eb90dd637ad4c675f2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5637/HighFidelity-Beta-PR11969-68177c7e719ed72e7635b4eb90dd637ad4c675f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5650/HighFidelity-Beta-PR11969-cccd08072722b7e31495aa3cecba90af06d4afcf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5660/HighFidelity-Beta-PR11969-d25dfbb957ba698e34f248845d823e981db95f43.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5660/HighFidelity-Beta-PR11969-d25dfbb957ba698e34f248845d823e981db95f43.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5661/HighFidelity-Beta-PR11969-6be7a3662cc417a2dc2b214dd722bb555d34ecb5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5661/HighFidelity-Beta-PR11969-6be7a3662cc417a2dc2b214dd722bb555d34ecb5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5666/HighFidelity-Beta-PR11969-11eaf435c96fe7f703ce1be7fc886c71e96f5ed2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5666/HighFidelity-Beta-PR11969-11eaf435c96fe7f703ce1be7fc886c71e96f5ed2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5701/app_11969_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5701/HighFidelity-Beta-PR11969-f0499c8b640ec8f49102b1ae48e7628d03308183.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5701/HighFidelity-Beta-PR11969-f0499c8b640ec8f49102b1ae48e7628d03308183.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5713/app_11969_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5713/HighFidelity-Beta-PR11969-9fc47c8e528e30024e79ac13341604560777ef23.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5713/HighFidelity-Beta-PR11969-9fc47c8e528e30024e79ac13341604560777ef23.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5727/app_11969_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5727/HighFidelity-Beta-PR11969-09e9707404e80658ffbe7ffa5c970088284b564c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5727/HighFidelity-Beta-PR11969-09e9707404e80658ffbe7ffa5c970088284b564c.dmg

**Pull request merged**
