### PR TITLE
Hotfix: Fix black flashing on transparent objects

### PR DESCRIPTION
**Pull request by SamGondelman**
same as https://github.com/highfidelity/hifi/pull/12193, against stable

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6396/app_12197_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6396/HighFidelity-Beta-PR12197-46a209037040f688a450e29a5b8a18d2b16fe0dc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6396/HighFidelity-Beta-PR12197-46a209037040f688a450e29a5b8a18d2b16fe0dc.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed. 

@conklin94122

**Pull request merged**
