### PR TITLE
VR edit UI test A

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2068/HighFidelity-Beta-PR11066-6cfcbb727cff0cd8697e7f100d5fe97fdd4ac2fe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2068/HighFidelity-Beta-PR11066-6cfcbb727cff0cd8697e7f100d5fe97fdd4ac2fe.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2079/HighFidelity-Beta-PR11066-6899603aa11584b791875404625d81e0afeca85b.dmg

**Comment by afauch** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2079/HighFidelity-Beta-PR11066-6899603aa11584b791875404625d81e0afeca85b.exe

**Pull request closed without merging**
