### PR TITLE
Fix for address sanitizer warning

### PR DESCRIPTION
**Pull request by hyperlogic**
This fixes a potential null pointer dereference.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
   * connect to the local sandbox.
   * does your avatar appear in the same position that it does in master? i.e. underneath your HMD.

**Comment by Nex-Pro** [comment]
Testing awaiting win build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4809/HighFidelity-Beta-PR11783-9724a5e5b83d98e591e24b2f23110b025657a6ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4809/HighFidelity-Beta-PR11783-9724a5e5b83d98e591e24b2f23110b025657a6ae.exe

**Comment by Nex-Pro** [comment]
### PASS

I look down and I see my feet as expected.

**Pull request merged**
