### PR TITLE
Cleanup and separate some uniform buffer slots

### PR DESCRIPTION
**Pull request by SamGondelman**
No real effect, just moving around some slots in a way that I think is clearer.

Test plan:
- General smoke test.  Things should render normally.  Try in domains with lots of content and interesting zones, like dev-welcome, etc.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6397/app_12198_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6397/HighFidelity-Beta-PR12198-dc51c8c7461a60bbde187d5bd6824bb2a52f44ee.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6397/HighFidelity-Beta-PR12198-dc51c8c7461a60bbde187d5bd6824bb2a52f44ee.dmg

**Comment by samcake** [comment]
I d like to postpone this change to think about it.
Olivier is also working on a pr that add lights to forward rendered items and another pr to Scribe that will help in this direction.
i d like to hold on so his work gets merged first

**Comment by samcake** [comment]
Useful but not critical yet

**Pull request closed without merging**
