### PR TITLE
Case 21627: Fix text rendering on AMD/Mac (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21627/text-entity-transparency-bug-on-AMD-for-80

Test plan: https://github.com/highfidelity/hifi/pull/15133

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17973/HighFidelity-Beta-PR15134-6ce906c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17973/HighFidelity-Quest-Beta-PR15134-6ce906c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17973/HighFidelity-Beta-PR15134-6ce906c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17973/HighFidelity-Beta-Interface-PR15134-6ce906c.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17984/HighFidelity-Beta-PR15134-6ce906c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17984/HighFidelity-Beta-Interface-PR15134-6ce906c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17984/HighFidelity-Beta-PR15134-6ce906c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17984/HighFidelity-Quest-Beta-PR15134-6ce906c.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17991/HighFidelity-Beta-PR15134-e29f2d2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17991/HighFidelity-Quest-Beta-PR15134-e29f2d2.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17991/HighFidelity-Beta-PR15134-e29f2d2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17991/HighFidelity-Beta-Interface-PR15134-e29f2d2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17991/HighFidelity-Beta-PR15134-e29f2d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17991/HighFidelity-Beta-Interface-PR15134-e29f2d2.exe

**Pull request merged**
