### PR TITLE
Case 20896: Fix continual edit handle translation when moving

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.manuscript.com/f/cases/20896/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18438/HighFidelity-Beta-PR15277-33c8d8c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18438/HighFidelity-Beta-Interface-PR15277-33c8d8c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18438/HighFidelity-Beta-PR15277-33c8d8c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18438/HighFidelity-Quest-Beta-PR15277-33c8d8c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18438/HighFidelity-Beta-PR15277-33c8d8c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18438/HighFidelity-Beta-Interface-PR15277-33c8d8c.exe

**Comment by dback2** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18448/HighFidelity-Beta-PR15277-33c8d8c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18448/HighFidelity-Beta-Interface-PR15277-33c8d8c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18448/HighFidelity-Beta-PR15277-33c8d8c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18448/HighFidelity-Quest-Beta-PR15277-33c8d8c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18448/HighFidelity-Beta-PR15277-33c8d8c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18448/HighFidelity-Beta-Interface-PR15277-33c8d8c.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18550/HighFidelity-Beta-PR15277-8dbdee4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18550/HighFidelity-Quest-Beta-PR15277-8dbdee4.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18550/HighFidelity-Beta-PR15277-8dbdee4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18550/HighFidelity-Beta-Interface-PR15277-8dbdee4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18550/HighFidelity-Beta-PR15277-8dbdee4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18550/HighFidelity-Beta-Interface-PR15277-8dbdee4.exe

**Pull request merged**
