### PR TITLE
centered toolbar

### PR DESCRIPTION
**Pull request by howard-stearns**
The system toolbar is initially centered, and the buttons are aranged in a particular order with the HUD button in the center.
Also adds a help button.

fixes https://highfidelity.fogbugz.com/f/cases/2028/placeholder-review-device-specific-window-placement

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8eb6699420414d5f604bb85241c444af145d9737 available at: https://gist.github.com/77116ccf915f3cd91f76fbab0e2e4faa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-8eb6699.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-8eb6699.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3d482157906c7268a068f1a3706418d6a4cef90 available at: https://gist.github.com/77116ccf915f3cd91f76fbab0e2e4faa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-f3d4821.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-f3d4821.dmg

**Comment by howard-stearns** [comment]
test plan:

1. With old settings, start up and observe that toolbar is centered horizontally. 
 - You can move the toolbar up and down, but not side to side. 
 - Switching between Desktop and HMD should keep it centered (as always, turning your head will not keep it centered, but it should recenter after you move linearly).
 - When the hud turns off (either by moving linearly or by pressing the HUD button), the toolbar should collapse around the hud button. I.e., it should remain centered when collapsed, and still be centered when restored.
 - Same for resizing desktop.
 - When you move the toolbar vertically and quit/restart Interface, the toolbar should come back again in the same vertical location (and still centered).

2. Toggle Settings -> General... -> "Constrain Toolbar Position to Horizontal Center" off.
 - You can now move the toolbar horizontally as well as vertically. The full x/y position should be saved and restored when you quit/restart Interface.
 - When switching between HMD and Desktop, or when resizing Desktop, it should work as before this PR.
 - When toggling the HUD off/on, it should work as before this PR, which means maintaining the left edge as the toolbar collapses.

3. Toggle the setting back on, and repeat #1.

4. Remove Interface.ini and go through first-time experience. All should be as expected, with toolbar behavior as in #1.  Should also be able to toggle and repeat step #2.  [Issue: how do we test first-time experience launching under steam?]

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3a072b5bf972ad6af351c6abdddef0c1719268f3 available at: https://gist.github.com/77116ccf915f3cd91f76fbab0e2e4faa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-3a072b5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8990-3a072b5.dmg

**Pull request merged**
