### PR TITLE
v0.74.0: go to error-room when failing to connect to a full domain

### PR DESCRIPTION
**Pull request by sethalves**
- go to error-room when failing to connect to a full domain

https://highfidelity.fogbugz.com/f/cases/19295/Interstitial-page-freezes-when-trying-to-connect-to-domain-that-has-reached-maximum-user-capacity

https://github.com/highfidelity/hifi/pull/14196

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13846/HighFidelity-Beta-PR14199-d1a4330.apk

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13852/HighFidelity-Beta-PR14199-d1a4330.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13852/HighFidelity-Beta-PR14199-d1a4330.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13852/HighFidelity-Beta-Interface-PR14199-d1a4330.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13852/HighFidelity-Beta-PR14199-d1a4330.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13852/HighFidelity-Beta-Interface-PR14199-d1a4330.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
