### PR TITLE
quick hack to test Vive at half frame rate

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9756ca819ac0b373b2d6d572c18d98f29f723ea9 available at: https://gist.github.com/9702da4db2fcbc714bb0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a9116c4aa7da3c7f2d4bcd036458863948d1840d available at: https://gist.github.com/9702da4db2fcbc714bb0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5a32f63f7c8ec6e2e801271b642266c169378c02 available at: https://gist.github.com/9702da4db2fcbc714bb0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7371.dmg

**Comment by ZappoMan** [comment]
This experiment was a failure... basically at 45fps you still see the shaking.

**Pull request closed without merging**
