### PR TITLE
Removing tutorial paths for first run experience

### PR DESCRIPTION
**Pull request by misslivirose**
This change is to align with the modification of the existing sandbox default content set to remove the tea house tutorial and to land the user directly on the builder grid, which will be moved to /0,-10,0 as part of a content set update that will go with this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2834/HighFidelity-Beta-PR11255-59fe5ffdc12acb2d2f7fee14c16344ca5f0f9ce1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2834/HighFidelity-Beta-PR11255-59fe5ffdc12acb2d2f7fee14c16344ca5f0f9ce1.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2884/HighFidelity-Beta-PR11255-59deccaeb5db0479b44c5f83e1687dc2b809bb7e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2884/HighFidelity-Beta-PR11255-59deccaeb5db0479b44c5f83e1687dc2b809bb7e.dmg

**Comment by misslivirose** [comment]
**Test Plan: Test all steps with an HMD and then without HMD plugged in**

1) Do a custom, clean install of the build in this PR. Check the box to automatically launch Sandbox after installation completes, but do not automatically launch interface.

2) Confirm that all nodes are up on your Sandbox server settings page before launching Interface _through a shortcut or from where you installed this PR, not from right clicking the task tray icon and selecting Go Home_

**Note Test Result:** Do you land in dev-welcome, or your Sandbox?

3) Open up your log files and search for the string _handleSandboxStatus_

**Note Test Result:** What does _handleSandboxStatus_ return?

**Expected Behavior**
This PR should make it so that you never land in the tutorial house, even if it is your first run and you are in HMD mode. The test _may_ fail due to an unrelated bug about sandbox status, which would result in you being sent to dev-welcome even when you are on a first run and have your sandbox running.

**Comment by YuppyPlays** [comment]
@misslivirose Do I need to wait for newer build or use the one above?

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
**Testing complete:**

Test Plan:
Do a custom, clean install of the build in this PR. Check the box to automatically launch Sandbox after installation completes, but do not automatically launch interface. **Check**

Confirm that all nodes are up on your Sandbox server settings page before launching Interface through a shortcut or from where you installed this PR, not from right clicking the task tray icon and selecting Go Home **Check, see pic for nodes**
image


Note Test Result: Do you land in dev-welcome, or your Sandbox? **Sandbox**

Open up your log files and search for the string handleSandboxStatus
Note Test Result: What does handleSandboxStatus return?
**[08/30 03:43:14] [DEBUG] [default] HandleSandboxStatus true**

Expected Behavior
This PR should make it so that you never land in the tutorial house, even if it is your first run and you are in HMD mode with hand controllers. The test may fail due to an unrelated bug about sandbox status, which would result in you being sent to dev-welcome even when you are on a first run and have your sandbox running. **Pass**

Unless any of the information given would indicate otherwise, I believe this is a **Pass** :)

**Comment by misslivirose** [comment]
Thanks @YuppyPlays! Would you also be able to retest with both Sandbox and Interface checked to launch at startup after the install?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2896/HighFidelity-Beta-PR11255-2f2b406047cf34aef208bf2a0e07b6a4e840eaa6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2896/HighFidelity-Beta-PR11255-2f2b406047cf34aef208bf2a0e07b6a4e840eaa6.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

I can confirm the results with Interface/Sandbox set to Run after install works the same as the previous.

**Pass** :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3074/HighFidelity-Beta-PR11255-930243539cd01d1f6d3c210fdca95a309793c7a4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3074/HighFidelity-Beta-PR11255-930243539cd01d1f6d3c210fdca95a309793c7a4.exe

**Pull request merged**
