### PR TITLE
Commerce frontend now uses asynchronous API

### PR DESCRIPTION
**Pull request by zfox23**
Don't formally review.

Uses @howard-stearns' most recent asynchronous version of the API.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2460/HighFidelity-Beta-PR11180-0835b7b8e6be09ae59af39cbd0aa825e0d46d138.dmg

**Comment by howard-stearns** [comment]
The inventory button conflicts spatially with the username button in the marketplace (and functionally with the users 'My Items' button). This isn't a blocker for our purposes right now, but do keep it in mind as we get UX designs and adapt to them.

**Comment by zfox23** [comment]
@howard-stearns: Understood!

**Comment by zfox23** [comment]
test this please

**Comment by howard-stearns** [comment]
dev-tests ok from a dev-build. qa-approving, but let's not merge until it builds.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2475/HighFidelity-Beta-PR11180-0835b7b8e6be09ae59af39cbd0aa825e0d46d138.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2475/HighFidelity-Beta-PR11180-0835b7b8e6be09ae59af39cbd0aa825e0d46d138.exe

**Pull request merged**
