### PR TITLE
Bring of menu window if tablet is closed on desktop 

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
test in desktop mode (only)
- be in tablet mode and have the tablet closed
- select the following menu item from the menu bar General Setting, Avatar Settings, and Running scripts
- The resulting windows should show even tho the tablet is closed

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78da936344d403c8c768b7b6b880641487e9a268 available at: https://gist.github.com/9f92352ce3dd60fa6fadcf0ac09becc9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9856-78da936.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9856-78da936.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a973dae3c077b7c5da386c0deb66a55d5ecf570 available at: https://gist.github.com/9f92352ce3dd60fa6fadcf0ac09becc9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9856-8a973da.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9856-8a973da.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9856-8a973da.exe

100%PASS

**Pull request merged**
