### PR TITLE
Watch for attachment texture loading

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/11457/Material-with-a-transparent-texture-not-transparent

Test plan:
- Add an attachment with transparent textures (Avatars > Attachments > New attachment, https://hifi-content.s3.amazonaws.com/jazmin/production/Greeters/greeter.fbx).  It should render correctly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6426/app_12209_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6426/HighFidelity-Beta-PR12209-b1fbb5e676f241696916dd2fc56876ee548880b2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6426/HighFidelity-Beta-PR12209-b1fbb5e676f241696916dd2fc56876ee548880b2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6431/app_12209_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6431/HighFidelity-Beta-PR12209-c8aded068814b238348a409516e2fd46a224edcf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6431/HighFidelity-Beta-PR12209-c8aded068814b238348a409516e2fd46a224edcf.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
