### PR TITLE
initial dnm pr for demo

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4107/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4107/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.exe

**Comment by howard-stearns** [comment]
built this please

**Comment by howard-stearns** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4109/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4109/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.exe

**Comment by marko8904** [comment]
oops. the warnings parser was still broken. build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4111/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4111/HighFidelity-Beta-PR11583-2dfa75882c15673b8a84a596783305d171c9527c.exe

**Comment by howard-stearns** [comment]
not needed any more, as 57 was cut around the same time and we're using that instead.

**Pull request closed without merging**
