### PR TITLE
Comment on #ifdef Q_OS_WIN usage

### PR DESCRIPTION
**Pull request by Roamfire**
Something to consider about cross platform coding style.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3062/HighFidelity-Beta-PR11261-d4d9e57e21553e59cd073f1bfb055d124ea793a2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3062/HighFidelity-Beta-PR11261-d4d9e57e21553e59cd073f1bfb055d124ea793a2.dmg

**Comment by ZappoMan** [comment]
Thanks for the feedback.

**Pull request closed without merging**
