### PR TITLE
fix login links RC69

### PR DESCRIPTION
**Pull request by danteruiz**
Fixed the issue of the forgot password/username not showing up on the login dialog

https://highfidelity.fogbugz.com/f/cases/13789/Log-in-Sign-up-dialog-is-missing-Forgot-Username-and-Forgot-Password-links

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan at this PR https://github.com/highfidelity/hifi/pull/13466

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10893/HighFidelity-Beta-PR13467-44207d9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10893/HighFidelity-Beta-PR13467-44207d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10893/HighFidelity-Beta-Interface-PR13467-44207d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10893/HighFidelity-Beta-PR13467-44207d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10893/HighFidelity-Beta-Interface-PR13467-44207d9.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Links are there and work.

**Pull request merged**
