### PR TITLE
Fixed crash when asking the user to load a script from the marketplace.

### PR DESCRIPTION
**Pull request by druiz17**
If a WebEngineView asks if the user wants to load a script and the user destroys the WebEngineView then responses back to the modal. Interface will crash.

In this PR I made that OffscreenUi can create a question modal with out hold up the thread by using signals and slots.

here is the ticket to the issue.  https://highfidelity.fogbugz.com/f/cases/6687/Crash-with-Create-Button

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan (Must be in toolbar mode)
- Open Marketplace and click the darts but do not accept the prompt of loading the script
- Open Create Button 
- Accept or cancel prompt to load the dart script. (Interface should not crash when accepting the prompt)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2250/HighFidelity-Beta-PR11115-405b59460f122e1103109b8e24c18756b6d9b48a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2250/HighFidelity-Beta-PR11115-405b59460f122e1103109b8e24c18756b6d9b48a.dmg

**Comment by YuppyPlays** [comment]
@druiz17  @anshuman64 
To my understanding the deadlock tag means testing wise we are to look out for some extra things if I recall to ensure stability given the sensitive nature of the request, is there anything in particular steps on top of the usual test plan I should follow before testing?

**Comment by anshuman64** [comment]
Great question for @conklin94122

**Comment by YuppyPlays** [comment]
@anshuman64 
No worries, I think he may be away currently though, I will leave this to a tester who knows the procedure better than myself for now as to not waste anyones time, thank you :)

**Comment by anshuman64** [comment]
@YuppyPlays Just added a line "Additionally, please do a general smoke test and report any problems/crashes/anomalies that you face." Feel free to begin QA.

**Comment by YuppyPlays** [comment]
@anshuman64 Thank you very much :)

Will test now.

**Comment by YuppyPlays** [comment]
@anshuman64    May need to get to rebuild - previous build brings up XML error when attempting to download.

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2254/HighFidelity-Beta-PR11115-405b59460f122e1103109b8e24c18756b6d9b48a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2254/HighFidelity-Beta-PR11115-405b59460f122e1103109b8e24c18756b6d9b48a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
@anshuman64 
Weirdly it's happened again even with new build. Pic attached.

image

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2255/HighFidelity-Beta-PR11115-5407dd12d8a43e0092d1dc0f4ca2b6daece0e669.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2255/HighFidelity-Beta-PR11115-5407dd12d8a43e0092d1dc0f4ca2b6daece0e669.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Open Marketplace and click the darts but do not accept the prompt of loading the script **Check**
Open Create Button **Check**
Accept or cancel prompt to load the dart script. (Interface should not crash when accepting the prompt) **Checked both**
Additionally, please do a general smoke test and report any problems/crashes/anomalies that you face. **Check, no issues found**

**Pass** :)

**Comment by hyperlogic** [comment]
Will this code work for multiple overlapping dialogs? It doesn't seem to handle that case.

**Pull request closed without merging**
