### PR TITLE
MS9539: Update Controls Reference pages

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix MS bug [#9539](https://highfidelity.manuscript.com/f/cases/9539/MSFT-HMD-Help-should-display-the-correct-images-and-help-for-the-MS-HMD-Hand-contollers)

<strike>**Test Plan**
In Windows MR:
- Launch Interface
- Open `Help > Controls Reference`
- Controls for Windows MR should show up

In other display modes:
- Launch Interface
- Open `Help > Controls Reference`
- Controls for other display modes should show up</strike>

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11259/HighFidelity-Beta-PR13587-cea2b94.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11259/HighFidelity-Beta-PR13587-cea2b94.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11259/HighFidelity-Beta-Interface-PR13587-cea2b94.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11259/HighFidelity-Beta-PR13587-cea2b94.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11259/HighFidelity-Beta-Interface-PR13587-cea2b94.exe

**Comment by wayne-chen** [comment]
As stated in the updated comment, no test plan is required.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Help now displays Windows MR controllers.

**Pull request merged**
