### PR TITLE
Point index finger and raise thumb if not touching controller

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

In Rift with Touch controllers.
- If you raise your index finger off the trigger, your avatar's index finger points. Left and right hands independently.
- If you raise your thumb so that it's not touching any controls, your avatar's thumb raises. Left and right hands independently.
- Squeezing the grip still curls the fingers and thumbs, but index finger pointing and thumb raising overrides the curling.
- If you're painting with the fingerPaint.js script, both index fingers point regardless of whether your fingers are on the triggers or not.

Test operation in Vive with Vive controllers, also.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dda628fbfa6f66c7fda6c1d46f88c46a1893edb available at: https://gist.github.com/50dbfb3e9b098284193696be19352d66<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9709-2dda628.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9709-2dda628.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2fff1eca4db5a7b10c605e4805c567baab3b21b available at: https://gist.github.com/50dbfb3e9b098284193696be19352d66<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9709-b2fff1e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9709-b2fff1e.dmg

**Comment by PhilipRosedale** [comment]
looks great!

**Comment by hyperlogic** [comment]
So, this works, but it goes against the grain of how the animation system is designed to work.  IMHO you can use the features of the animation system to implement this with no code changes (other than js) and get interpolation and blending for free.

   1) create 3 new fbx hand poses for each hand.  point, thumbs-up, point & thumbs-up.
   2) insert a 3 new states into the "rightHandStateMachine" and "leftHandStateMachine" nodes.  These states will contain AnimClip nodes that reference the new fbx poses.
   3) modify squeeze hands to set animVar triggers to cause the state machine to switch between the states based on user input.

In this approach no C++ code needs to be changed.  I'd prefer you used this approach.

**Comment by PhilipRosedale** [comment]
@ctrlaltdavid happy to put more time/billing on this job to have you see if you can follow what @hyperlogic is suggesting here.

**Comment by ctrlaltdavid** [comment]
Will have another stab at this on a new branch / PR.

**Pull request closed without merging**
