### PR TITLE
Fix tractor action initial crazy

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6907/app_12332_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6907/HighFidelity-Beta-PR12332-639f7a52d862d9fb56f4d1b20c73926c893b9fcf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6907/HighFidelity-Beta-PR12332-639f7a52d862d9fb56f4d1b20c73926c893b9fcf.dmg

**Comment by sethalves** [comment]
To test:
- create a cube, make it non-dynamic
- have someone watch while you repeatedly far grab and adjust it
- make sure, as the a far-grab starts, it never warps the cube far-away and then quickly returns it

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/11442/initial-far-grab-often-warps-target-far-away-and-quicky-returns-it

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
