### PR TITLE
Create BUILD_LINUX_CHEATSHEET.md

### PR DESCRIPTION
**Pull request by chamberlainjoshuam**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
@MiladNazeri please review

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5785/app_11866_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5785/HighFidelity-Beta-PR11866-572e208a1ef86078755325e12388e93d5645f47c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5785/HighFidelity-Beta-PR11866-572e208a1ef86078755325e12388e93d5645f47c.dmg

**Pull request merged**
