### PR TITLE
Fix erroneous 2D overlay unhandled property messages for bounds property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

- Run the attached script in desktop mode.
- One each of a 2D rectanble, 2D image, and 2D text overlay should be displayed.
- In the program log there should NOT be any messages, "OVERLAY Unhandled rectangle property bounds".

[testBoundsMessage.zip](https://github.com/highfidelity/hifi/files/1520444/testBoundsMessage.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5321/HighFidelity-Beta-PR11910-fd76c7a88bb9b0a463c86d161e425ab346ed0b1b.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5322/HighFidelity-Beta-PR11910-fd76c7a88bb9b0a463c86d161e425ab346ed0b1b.dmg

**Comment by Nex-Pro** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5324/HighFidelity-Beta-PR11910-fd76c7a88bb9b0a463c86d161e425ab346ed0b1b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5324/HighFidelity-Beta-PR11910-fd76c7a88bb9b0a463c86d161e425ab346ed0b1b.dmg

**Comment by Nex-Pro** [comment]
### PASS

Tester: Piper.Peppercorn

System information.
CPU: Intel i7 4.0 ghz.
RAM: 16gb
GPU: Nvidia GTX1070 8gb
HMD: HTC Vive.
Controllers: Vive hand controllers.
Audio: USB headset.

Testing conditions:

Fresh installation of this build.

**result.**
Log files devoid of unwanted rectangle property messages.

**Pull request merged**
