### PR TITLE
comment to get build

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f4229c18291b6e018cf47f9a2abc8b3ab083f7b available at: https://gist.github.com/34cb1538a6864fb5ed405095a8b23cc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f4229c18291b6e018cf47f9a2abc8b3ab083f7b available at: https://gist.github.com/34cb1538a6864fb5ed405095a8b23cc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f4229c18291b6e018cf47f9a2abc8b3ab083f7b available at: https://gist.github.com/34cb1538a6864fb5ed405095a8b23cc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9036-6f4229c.dmg

**Pull request closed without merging**
