### PR TITLE
Fix Avatar collision sounds triggering all the time.

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Test plan:
Go to playa and walk around, you shouldn't hear those tapping sounds anymore except if you jump or hit something at a fast pace.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 854bf82631664b329bf2682c093cb5bcda87aaf2 available at: https://gist.github.com/e9efff6608dae9f358c074a136c01c81<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8002.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8002.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Failure as when at ```playa``` the simple slow collition of the avatar hitting literally any object generates the tapping sound.

**Comment by ZappoMan** [comment]
@kevinmthomas-carpool - I want to double check what you are saying here: "Failure as when at playa the simple slow collition of the avatar hitting literally any object generates the tapping sound." 

The avatar SHOULD make a sound when it collides with stuff... that is expected... but it depends on the speed. If you collide at over 0.3m/s you should get a sound. Are you able to verify that you're traveling less than that speed and still getting a sound?

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: The issue is I have to move extremely slow however while monitoring Speed I can verify if I literally take very small steps, at an unnaturally slow space, I can verify there is NO collision sound.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e2fa7340240f2beee7b2fc31f35f95c7691d8810 available at: https://gist.github.com/e9efff6608dae9f358c074a136c01c81<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8002.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8002.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** FAILURE
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test. Verified on ```playa``` collisions under a speed of 0.3 do not make a collision sound.

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |53 |55 |52
**Present Rate**: |60 |60 |60
**Present New Rate**: |52 |54 |51
**CPU Buffer Count**: |4510 |3740 |2160
**GPU Buffer Count**: |821 |409 |242
**CPU Memory Usage**: |62799872 |59174912 |28553216
**GPU Memory Usage**: |16162816 |18878464 |10784768
**CPU Texture Count**: |232 |275 |140
**GPU Texture Count**: |1704 |1631 |1545
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |326518624 |353088768 |96334920
**GPU Texture Memory Usage**: |302860239 |303451472 |111648106
**GPU Virtual Memory Usage**: |471144399|471735632|279932266
**Triangle Count**: |204418 |345720 |271738
**Triangle Rate**: |12776125 |21607500 |16983625
**API Drawcall Count**: |199 |106 |52
**Drawcall Count**: |250 |106 |52
**Drawcall Rate**: |15625 |6625 |3250
**State Changes Texture Count**:|133 |116 |29
**Pipeline Count**: |29 |24 |15
**Item Opaques**: |232 |158 |54
**Item Translucents**: |38 |7 |15
**Item Lights**: |20 |26 |0
**Timing Opaques**: |1583 |1370 |468
**Timing Translucents**: |183 |207 |181
**Timing Lighting**: |155 |254 |54
**Render Frame**: |2797 |3042 |1280

**Pull request merged**
