### PR TITLE
Add "pitch" property to allow pitch shifting an audio effect

### PR DESCRIPTION
**Pull request by kencooke**
This PR adds a "pitch" property to AudioInjectorOptions. A value other than default (1.0) will cause playSound() to pitch shift the audio up or down by an arbitrary factor, up to 4 octaves.

NOTES:
 - This is implemented by resampling, so there will be a corresponding change to the duration.
 - This is implemented when the injector is created. Once an injector is running, dynamic changes will have no effect.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6500/app_12226_PR.apk

**Comment by kencooke** [comment]
### Test Plan

With Interface from this PR,
1) Join a domain and verify that everything sounds as before. This PR should have no effect, unless scripts are edited with a non-default value for pitch.

2) Open the JavaScript console (ctrl-alt-J) and manually script some sounds via playSound():
 - load a sound asset, for example:
```var sound = SoundCache.getSound("http://www.mediacollege.com/audio/tone/files/440Hz_44100Hz_16bit_05sec.wav");```
 - wait a few seconds for it to finish loading
 - test playing with default pitch:
```injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true});```
 - test pitch-shifted up by an octave:
```injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 2 });```
 - test pitch-shifted down by an octave:
```injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 0.5 });```
 - other properties such as ```loop``` and ```volume``` should still work as expected

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6500/HighFidelity-Beta-PR12226-e2e4e7f423a12cebf94cc59bfb2c7b5715b3d0ea.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6500/HighFidelity-Beta-PR12226-e2e4e7f423a12cebf94cc59bfb2c7b5715b3d0ea.dmg

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
--- | ---
Join a domain and verify that everything sounds as before. This PR should have no effect, unless scripts are edited with a non-default value for pitch. | Pass
Open the JavaScript console (ctrl-alt-J) and manually script some sounds via playSound(): | Pass
load a sound asset, for example: | Pass
var sound = SoundCache.getSound("..."); | Pass
wait a few seconds for it to finish loading | Pass
test playing with default pitch: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true}); | Pass
test pitch-shifted up by an octave: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 2 }); | Fail
test pitch-shifted down by an octave: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 0.5 }); | Fail
other properties such as loop and volume should still work as expected | Pass

This doesn't appear to modify the pitch, but more so the playback rate. (Test w/ `https://cain.sh/i/Marius%20-%20Existence%20Problem.wav`). At 0.5, the speed of the song is cut in half. Whereas, at 2.0 the speed of the song is doubled.

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
--- | ---
Join a domain and verify that everything sounds as before. This PR should have no effect, unless scripts are edited with a non-default value for pitch. | Pass
Open the JavaScript console (ctrl-alt-J) and manually script some sounds via playSound(): | Pass
load a sound asset, for example: | Pass
var sound = SoundCache.getSound("..."); | Pass
wait a few seconds for it to finish loading | Pass
test playing with default pitch: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true}); | Pass
test pitch-shifted up by an octave: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 2 }); | Fail
test pitch-shifted down by an octave: | 
injector = Audio.playSound(sound, { position: MyAvatar.position, loop: false, localOnly: true, pitch: 0.5 }); | Fail
other properties such as loop and volume should still work as expected | Pass

This doesn't appear to modify the pitch, but more so the playback rate. (Test w/ `https://cain.sh/i/Marius%20-%20Existence%20Problem.wav`). At 0.5, the speed of the song is cut in half. Whereas, at 2.0 the speed of the song is doubled.

@conklin94122

**Comment by kencooke** [comment]
Thanks @cain-kilgore. The change in duration is expected. As I put in the spec, it's currently implemented via resampling so any change in pitch will have a corresponding change in timescale. This was the original request, and works well for looped sounds. A timescale-preserving pitch shifter (using something complex like a phase vocoder) is outside the scope of this PR.

**Comment by cain-kilgore** [comment]
@kencooke: Just seeing about the duration note now in the spec. In that case,
# Test Passed.

**Comment by 1st-BrainStormer** [comment]
Seems 4th octive is incorrect.    Pitch 1=A,   Pitch 2=A  Pitch 3=A   Pitch 4=E

**Comment by kencooke** [comment]
Hi Bruce,

 

The “pitch” property is a direct multiplier (to match other APIs like Unity).

So pitch=2 is one octave, 4 is two octaves, … 16 is four octaves.

Does that explain what you are hearing? My spec was a bit confusing…

 

As you’re doing some good work on MIDI, I’d be interested in your feedback regarding audio features we might need to enable great music experiences.

 

Ken

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
