### PR TITLE
WARNING: protocol change - reduce joint-data bandwidth

### PR DESCRIPTION
**Pull request by sethalves**
- Interface only sends a joint's data to avatar-mixer if it has changed enough since the last send.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f80c484b4eeb8e7c675138a6e766f81a25cf6c3 available at: https://gist.github.com/8626424537d7505b679b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5692.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5692.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e32b9191f55b4a99a2bdc49ad6bff6b83015e387 available at: https://gist.github.com/8626424537d7505b679b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5692.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5692.dmg

**Comment by howard-stearns** [comment]
Looks good. Here are some number I'm seeing:

With no animation:
  Receive Stats: 15-20 Kpbs @30Hz / avatar
  Bandwidth Details -> Avatars Bandwidth In/Out: 35-40 Kbps In and out (with 2 avatars total)

* Master vs PR should be about the same in this case (and they are) because Master doesn't do joints because they're all in bind pose, PR doesn't do joints because they're not changing.
* We think the difference between Receive Stats and Bandwidth Details is that the latter includes headers?

With animations, Master:
  Receive Stats: 120 @ 30Hz
  Bandwidth Details: 145 / 55-80

With animations, PR:
  Receive Stats: 75-80
  Bandwidth Details: 50-120 / 40-80

**Comment by howard-stearns** [comment]
I am not seeing any problems from this.

**Pull request merged**
