### PR TITLE
Hotfix: Disable JS baking

### PR DESCRIPTION
**Pull request by birarda**
There was a bug in master and temporarily in stable that would have produced completely empty JS files that were "baked". Until we have tested/merged code that correctly deals with baking version changes, we need to disable JS baking so that users with scripts in the Asset Server get the right behaviour.

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

1. Upload a JS file to your asset server.
2. The "Use Baked" column should show two dashes to indicate that baking of that file type is not supported.
3. Use that script in interface (as an entity script or client script). Ensure that the behaviour is correct.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4428/HighFidelity-Beta-PR11680-7716b042f6d19588d5e76849406fe4e94977e17a.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4432/HighFidelity-Beta-PR11680-7716b042f6d19588d5e76849406fe4e94977e17a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4432/HighFidelity-Beta-PR11680-7716b042f6d19588d5e76849406fe4e94977e17a.exe

**Pull request closed without merging**
