### PR TITLE
WL 21571 - Remove "common questions" button

### PR DESCRIPTION
**Pull request by cain-kilgore**
> The button on the bottom of the tablet "common questions" doesn't launch or show anything when tapped by the stylus. Please remove it.

WL [21571](https://worklist.net/21571)

## Test Plan
- Open up the Tablet and Launch the Help App
- Confirm that the Bottom of the Window no longer has a "Common Questions" button on all the pages.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4243/HighFidelity-Beta-PR11620-16467128a2e5ed3601cd395378ccd084c16177b6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4243/HighFidelity-Beta-PR11620-16467128a2e5ed3601cd395378ccd084c16177b6.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
## PASS

All four tablet help screens have been updated to the new versions. And match the files showing on the commit page. Hud mode all pages correct also.

@cain-kilgore  Easiest pass ever.

201860-hifi-snap-by--on-2017-10-18_15-57-17
201860-hifi-snap-by--on-2017-10-18_15-57-12
201860-hifi-snap-by--on-2017-10-18_15-57-07
201860-hifi-snap-by--on-2017-10-18_15-56-43


Crashed for unrelated reason detailed splat submitted.

**Pull request merged**
