### PR TITLE
RC72: Send ignoring avatar removal to ignored avatar 

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

You will need two avatars for this test. You will need to connect to the sandbox from this PR.

From Interface client A, ignore the avatar from Interface client B. Confirm that neither of the avatars are able to each other. Without this fix, client B continues to see client A in a frozen position.

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12555/HighFidelity-Beta-PR13915-5986b4d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12555/HighFidelity-Beta-PR13915-5986b4d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12555/HighFidelity-Beta-Interface-PR13915-5986b4d.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12562/HighFidelity-Beta-PR13915-5986b4d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12562/HighFidelity-Beta-PR13915-5986b4d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12562/HighFidelity-Beta-Interface-PR13915-5986b4d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12562/HighFidelity-Beta-PR13915-5986b4d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12562/HighFidelity-Beta-Interface-PR13915-5986b4d.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
FAIL @Conklin94122

If a user ignores another user, they will appear frozen in place to the ignored user.  This only appears to happen in public domains.  We were unable to repro in my domain where I am the admin.

Steps to repro:
1. Two users enter a public domain (we used hifiqa-pr-metaverse-staging)
2. Have user 1 ignore user 2
3. Observe user 1 is frozen in place to user 2
4. Un-ignore user 2
5. Have user 2 ignore user 1
6. Observe user 2 is frozen in place to user 1
7. Repeat steps in domain in which one of the users is an admin
8. Observe users are ignored successfully in this domain

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2341624/hifi-log.txt)
frozen

**Pull request merged**
