### PR TITLE
Discovery Notifications Project: Notifications for PEOPLE, WALLET, MARKET, and GOTO

### PR DESCRIPTION
**Pull request by zfox23**
[Parent, MS18504](https://highfidelity.manuscript.com/f/cases/18504/Discovery-Notifications-Project-Checkpoint).

[MS18792](https://highfidelity.manuscript.com/f/cases/18792/Implement-the-notifications-design-for-PEOPLE-WALLET-MARKET-and-GOTO).

Implements the notifications design for PEOPLE, WALLET, MARKET, and GOTO [as documented here.](https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/393805837/Zach+s+Notification+Implementation+Details)

Finishes out the MVP of ["Notify Presence/Economic Activity"](https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/242712602/Notify+Presence+Economic+Activity). Does not complete Stretch.2, since Stretch.1 wasn't done.

Test Plan here:
https://highfidelity.testrail.net/index.php?/suites/view/1539

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13123/HighFidelity-Beta-PR14031-ed84b49.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13123/HighFidelity-Beta-PR14031-ed84b49.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13123/HighFidelity-Beta-Interface-PR14031-ed84b49.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13123/HighFidelity-Beta-PR14031-ed84b49.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13123/HighFidelity-Beta-Interface-PR14031-ed84b49.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13142/HighFidelity-Beta-PR14031-87e91a4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13142/HighFidelity-Beta-PR14031-87e91a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13142/HighFidelity-Beta-Interface-PR14031-87e91a4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13142/HighFidelity-Beta-PR14031-87e91a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13142/HighFidelity-Beta-Interface-PR14031-87e91a4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13148/HighFidelity-Beta-PR14031-33c0463.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13148/HighFidelity-Beta-PR14031-33c0463.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13148/HighFidelity-Beta-Interface-PR14031-33c0463.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13156/HighFidelity-Beta-PR14031-33c0463.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13156/HighFidelity-Beta-PR14031-33c0463.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13156/HighFidelity-Beta-Interface-PR14031-33c0463.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13156/HighFidelity-Beta-PR14031-33c0463.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13156/HighFidelity-Beta-Interface-PR14031-33c0463.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13171/HighFidelity-Beta-PR14031-e75a45a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13171/HighFidelity-Beta-PR14031-e75a45a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13171/HighFidelity-Beta-Interface-PR14031-e75a45a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13171/HighFidelity-Beta-PR14031-e75a45a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13171/HighFidelity-Beta-Interface-PR14031-e75a45a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13181/HighFidelity-Beta-PR14031-6284074.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13181/HighFidelity-Beta-PR14031-6284074.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13181/HighFidelity-Beta-Interface-PR14031-6284074.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13181/HighFidelity-Beta-PR14031-6284074.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13181/HighFidelity-Beta-Interface-PR14031-6284074.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13219/HighFidelity-Beta-PR14031-57c3034.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13219/HighFidelity-Beta-PR14031-57c3034.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13219/HighFidelity-Beta-Interface-PR14031-57c3034.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13219/HighFidelity-Beta-PR14031-57c3034.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13219/HighFidelity-Beta-Interface-PR14031-57c3034.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13259/HighFidelity-Beta-PR14031-a76c3f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13259/HighFidelity-Beta-Interface-PR14031-a76c3f0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13259/HighFidelity-Beta-PR14031-a76c3f0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13259/HighFidelity-Beta-Interface-PR14031-a76c3f0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13277/HighFidelity-Beta-PR14031-be304ea.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13280/HighFidelity-Beta-PR14031-1ac2800.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13280/HighFidelity-Beta-PR14031-1ac2800.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13280/HighFidelity-Beta-Interface-PR14031-1ac2800.exe

**Comment by rickcarr044** [comment]
Currently testing PR14031
Luis and Rick

**Comment by rickcarr044** [comment]
Test Update: In the PEOPLE Test case there is an issue in Step 14 where the expected result indicates that for Client A: "Verify that you do not see a red dot on the PEOPLE app."  but a red dot does appear after less than a minute or two.

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13302/HighFidelity-Beta-PR14031-1ac2800.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13302/HighFidelity-Beta-PR14031-1ac2800.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13302/HighFidelity-Beta-Interface-PR14031-1ac2800.exe

**Comment by rickcarr044** [comment]
WALLET: Client B saw the red dot on the WALLET icon after sending items in Steps 2-4 - The test case did not mention this as a result.  Client A did see the text banners and the red dot on the WALLET icon.

MARKET: We both had messages in WALLET home where an update appeared as a "Gift sent to marketplace with memo:  "Update of ...".  We think this occurs if the test account is already signed in, whereas the expected "Update of ... " occurs after the user starts up Interface and is logged in.  

PEOPLE: We had one case this morning where the red dot appeared on Step 14.  We were both using HighFidelity-Beta-PR14031-1ac2800.exe

**Comment by zfox23** [comment]
@rickcarr044 Thank you!

>WALLET: Client B saw the red dot on the WALLET icon after sending items in Steps 2-4 - The test case did not mention this as a result. Client A did see the text banners and the red dot on the WALLET icon.

What text notification did Client B see at this time? Do you have timestamped logs for this instance? (The logs would make it clear as to why this happened.)

>MARKET: We both had messages in WALLET home where an update appeared as a "Gift sent to marketplace with memo: "Update of ...". We think this occurs if the test account is already signed in, whereas the expected "Update of ... " occurs after the user starts up Interface and is logged in.

This is very very strange - please submit this as a bug to Manuscript against Marketplace features. This bug is not related to the notification feature.

>PEOPLE: We had one case this morning where the red dot appeared on Step 14. We were both using HighFidelity-Beta-PR14031-1ac2800.exe

Has that happened to you since? Do you have timestamped logs for this instance? (The logs would make it clear as to why this happened.)

**Comment by qlilaseguinolaza** [comment]
Here's a screenshot and logs for the issue where I get a notification on my wallet after purchasing an item and then the other user that sold the item closes and reopens the interface. 
[hifi-log_2018-09-25_15.47.15.txt](https://github.com/highfidelity/hifi/files/2417244/hifi-log_2018-09-25_15.47.15.txt)
[hifi-log_2018-09-25_15.55.51.txt](https://github.com/highfidelity/hifi/files/2417245/hifi-log_2018-09-25_15.55.51.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2417246/hifi-log.txt)

wallet_notification

**Comment by zfox23** [comment]
@qlilaseguinolaza These logs do not contain any lines about processing notification data. Do you have verbose logging on?

Also, I'm still unclear on your language here:
>Here's a screenshot and logs for the issue where I get a notification on my wallet after purchasing an item and then the other user that sold the item closes and reopens the interface.

>I get a notification on my wallet
Do you mean a line in "Recent Activity"? Do you mean a text banner notification in the top right of your screen?

>after purchasing an item
YOU are purchasing the item? The same person who got the aforementioned "notification"?

Do you see "Marketplace sale of Test Item 001" in your Wallet's Recent Activity at this time?

**Comment by zfox23** [comment]
@rickcarr044 and @qlilaseguinolaza - thank you both for finding this! This bug report unearthed a big discussion among the team - we're talking about it. I'm going to end up changing the code and the WALLET test plan.

**Comment by rickcarr044** [comment]
GOTO :  It appears Client A does not get the GOTO notifications while they are logged in (Or press CTRL+R to refresh the cache).  Client A can log out, then log back in and then they will also see the notifications (Red dot on GOTO icon and text banner notification).  

Marketplace bug entered as Manuscript ticket 18794
https://highfidelity.manuscript.com/f/cases/18794/Updated-Marketplace-item-appears-in-Wallet-Home-as-a-Gift

**Comment by zfox23** [comment]
@rickcarr044 I don't yet understand.

>It appears Client A does not get the GOTO notifications while they are logged in
Does this mean Client A doesn't receive a notification while they are logged in when Client B closes Interface, waits 60 seconds, and re-opens Interface?

>(Or press CTRL+R to refresh the cache)
I do not understand how this comes into play.

>Client A can log out, then log back in and then they will also see the notifications
Do you mean "close Interface", or use File -> Log Out?

**Comment by rickcarr044** [comment]
At Step 2 in the GOTO test case - Client B takes a snap and blasts it to Connections (While Client A is open).  The text notification did not appear and there wasn't a red dot over the GOTO icon.  
We had similar behavior with New Announcement in Step 9 - the behavior there was inconsistent also.  

CTRL+R was one means of seeing the notifications.  And it was reliable in displaying them

It is possible we were too impatient and should have waited longer than the 60 seconds.  It could also be we have fairly dirty machines at this point.  I have not restored my primary machine since 3PM yesterday.  

File->Log Out then logging back in displayed the notifications as expected.

**Comment by zfox23** [comment]
@rickcarr044 
>At Step 2 in the GOTO test case - Client B takes a snap and blasts it to Connections (While Client A is open). The text notification did not appear and there wasn't a red dot over the GOTO icon.

Could Client A see the Blast in GOTO at this time?

**Comment by rickcarr044** [comment]
Yes - the blast can be seen after opening the GOTO app.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13370/HighFidelity-Beta-PR14031-6a3fa28.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13370/HighFidelity-Beta-PR14031-6a3fa28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13370/HighFidelity-Beta-Interface-PR14031-6a3fa28.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13370/HighFidelity-Beta-PR14031-6a3fa28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13370/HighFidelity-Beta-Interface-PR14031-6a3fa28.dmg

**Comment by rickcarr044** [comment]
PASS @conklin94122

Passed the final two tests (WALLET and GOTO) on Windows 10 with last build.  
MARKET passed with Manuscript ticket 18794 reported (Not related to this PR)
PEOPLE passed after the 'Step 14' issue was not reproducible

**Comment by howard-stearns** [comment]
Also fixes https://highfidelity.fogbugz.com/f/cases/edit/18784/Go-To-Icon-disappears-when-user-receives-Notification-Pop-Up

**Pull request merged**
