### PR TITLE
Remember adjustment made to equipped entities

### PR DESCRIPTION
**Pull request by druiz17**
Remember adjustment made to equipped entities for specific avatar. Adjustments are cleared when you exit interface. 

- ticket - https://highfidelity.fogbugz.com/f/cases/7288/Incorrect-equip-attachment-after-switching-avatars

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- equip an item..such as a fire-gun
- adjust the entity and drop it
- when you reequip the entity. the adjustment you made should be appiled
- switch avatars
- equip the entity again and the adjustment should not be applied
- perform steps 1 - 3 again
- switch back to your previous avatar
- when you equip the entity, the last adjustment you made for that entity while wearing that avatar should be applied

- note - adjustments clear when you exit interface

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4528/HighFidelity-Beta-PR11709-e9298b6ff8e6b806051b260ec4c0637a91c52ecb.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4528/HighFidelity-Beta-PR11709-e9298b6ff8e6b806051b260ec4c0637a91c52ecb.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
equip an item..such as a fire-gun | Pass
adjust the entity and drop it | Pass
when you reequip the entity. the adjustment you made should be appiled | Pass
switch avatars | Pass
equip the entity again and the adjustment should not be applied | Pass
perform steps 1 - 3 again | Pass
switch back to your previous avatar | Pass
when you equip the entity, the last adjustment you made for that entity while wearing that avatar should be applied | Pass
note - adjustments are cleared when you exit interface | Pass

All good - the attachments all were differently placed when I moved them around and switched avatars.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
