### PR TITLE
Fixing a potential crash when a texture is not loaded properly

### PR DESCRIPTION
**Pull request by samcake**
Protecting the case when a texture is not created at all in the Image reader loader call back. 
This was raised in this bug:
https://highfidelity.fogbugz.com/f/cases/4304/CRASH-ImageReader-read-in-the-textureCache-cpp-ln-563
The stack crashes there in the ImageReader:
Function    File(Line)
interface!std::basic_string,std::allocator >::assign    c:/program files (x86)/microsoft visual studio 12.0/vc/include/xstring(1138)
interface!ImageReader::read    c:/jenkins/workspace/release-build/label/windows/libraries/model-networking/src/model-networking/texturecache.cpp(563)
interface!Reader::run    c:/jenkins/workspace/release-build/label/windows/libraries/model-networking/src/model-networking/texturecache.cpp(482)

I don't have a repro case for it. So i don't know if that fixes the problem precisely, but it should help.

## TEST PLAN
At this point, we don't have a repro case so we need a simple check that the textures of a domain are looking the same compared to current Master.
Also in the same session jump in and out in between 2 "big" domains (like welcome and playa)  and checking that the textures shows up always the same and no oddities appear.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ed37a062edb761cbbbd100752da9f9c076c5236 available at: https://gist.github.com/f94353329dd229a2bca078206827b903<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-4ed37a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-4ed37a0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: caed7ad81efd4806897c28b8e242e18240580ac0 available at: https://gist.github.com/f94353329dd229a2bca078206827b903<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-caed7ad.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-caed7ad.dmg

**Comment by Nex-Pro** [comment]
Looking at this now

**Comment by Nex-Pro** [comment]
@samcake  I'm seeing a shift in the colours when I take a snapshot in the same location at dev-welcome. This seems to make the colours muted. Is the lighting constant in dev-welcome ?

**Comment by samcake** [comment]
@nex-pro, I don;t think that is the case.
I see that the trees are moving.
I m trying to get the info weither some script is animating the global zone lighting in some way.
You don't have a script running locally that does that do you ? :)

**Comment by cozza13** [comment]
@Nex-Pro is the change of color related to this PR? Or is it in master? Also if it is in Master is it also in Stable

**Comment by ZappoMan** [comment]
This PR is reported to fix a bug that represented more than 50% of our crashes yesterday... **Please get this tested/merged ASAP!**

**Comment by Nex-Pro** [comment]
@sam the tree movement is not causing the color change as far as I can tell

**Comment by OmegaHeron** [comment]
Per request of Chris;
Tested Windows 10
Compared master (latest) to this PR in Welcome, Playa and a few other places.
Moved between playa and welcome multiple times.
I can't find any visual difference between master/this pr - multiple visits to welcome/playa in same sessions shows no loss of textures, again, that I can catch.  I often miss subtle (very subtle) things when it comes to visuals, but, nothing blatant seen.
General smoke test = pass.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 013784cdccc2118ca4da4f8ea752141a6e4d8a41 available at: https://gist.github.com/f94353329dd229a2bca078206827b903<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-013784c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10250-013784c.dmg

**Comment by samcake** [comment]
And this pr is not relevant anymore since the bug has been addressed by another pr

**Pull request closed without merging**
