### PR TITLE
Beta Release 16 - Includes up to Developer Release 5176

### PR DESCRIPTION
**Pull request by cozza13**
Testing script: http://cdn.rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Don't show user’s border when hover mouse if logged out
* Improved audio pipeline: remove all hard clipping and improve audio quality.
* Prevent users window from being dragged off screen
* Snapshot takes picture of HMD window instead of preview
* Fix TypedArray byte ordering and .subarray indexing. Fixes a few small but critical bugs in the JS TypedArrays implementation: 
* Fix canRezTmp logic (incorrectly) resets valid lifetimes to the maximum value
* Fix export entities by region
* Fix modTouchscreen camera input for Interface
* Fixes a crash that occurs when switching between several domains too fast.
* Add teleportation to the array of movement options. 
* Support alpha and color gradients in circle overlays
* New javascript for ray picking against avatars
* Various snapshot improvements
* Fix MyAvatar name and url accessors.
* Expand frame decoration when mouse is over a window in HMD mode
* Fix orientation being reset to 0,0,0,1
* Audio codecs support.
* Update max request limit and number of processing threads
* Spatialization and HRTF for local audio injectors
* Ignore Avatar featureel overlays not correctly scaling
* Basic hand-controller editing
* Added Mac preview image if VSync is enabled
* Add missing loading images for Asset Browser
* Various performance optimizations
* Fix rendering of overlay spheres with alpha
* Ensure newly shown windows are popped to the top of the zorder
* Fixed issues in some popup windows
* New entity collision shape options
* Support for glowing 3D line overlays
* Interface changes for new Marketplace
* Refresh feature/grab script polish
* * Support for scale property on model overlays.
* Improved throwing with hand-controllers.
* Improved HRTF
* Update all asset server responses to be reliable
* Menu & hand controller polish
* Toolbar improvements
* Delete old Interface logs
* Fix the AudioMixer distance attenuation.
* Fix hover states for toolbar buttons
* Make search line termination a circle, like 2D UI
* Grab Script Improvements
* Fix decoration inflation
* Grab Script Polish
* Make search line termination a circle, like 2D UI
* Fix hover states for toolbar buttons
* Fix the AudioMixer distance attenuation.
* Support triangle and hexagon shapes, add shape support to overlays.
* Injectors now always play locally, and send to server without echo
* Actually delete textures we're not using
* improve throwing release velocity
* Changes for hifiCodec plugin building on Linux
* Cleanup resources used by offscreen GL surfaces 
* Ensure the pause overlay is unlit (emissive)
* Far-grabbed objects no longer fly away when the avatar body shifts
* fix crash with multiple solo nodes in closeCurrentPacket
* Show up to three suggested domains when you bring up the GoTo address bar. Clicking on picture takes you there. Can filter results by typing.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0b5cdcef4262d8ddd5d7b16df9a7a73595253e7c available at: https://gist.github.com/3e7bd49c702f101fbbe7724513725876<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8281-0b5cdce.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8281-0b5cdce.dmg

**Comment by ZappoMan** [comment]
BUG - I just got some bad audio... I'm not sure how it happened... I was in the vive, trying to get my hand controllers to work.... all of a sudden I got bad audio and then interface crashed.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. Successful audio experience as I experience crisp and clear echo of server audio.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |54 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |53 |60 |60
**CPU Buffer Count**: |4111 |1053 |4285
**GPU Buffer Count**: |676 |259 |743
**CPU Memory Usage**: |64294912 |30281728 |95592448
**GPU Memory Usage**: |19935232 |8196096 |39833600
**CPU Texture Count**: |246 |111 |334
**GPU Texture Count**: |295 |258 |551
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |335794116 |375578368 |455714944
**GPU Texture Memory Usage**: |600553224 |268102135 |987417458
**GPU Virtual Memory Usage**: |745889544|413438455|1132753778
**Triangle Count**: |485194 |250524 |707195
**Triangle Rate**: |30324625 |15657750 |41599705
**API Drawcall Count**: |243 |122 |254
**Drawcall Count**: |298 |135 |1153
**Drawcall Rate**: |18625 |8437 |67823
**State Changes Texture Count**:|228 |95 |285
**Pipeline Count**: |28 |31 |35
**Item Opaques**: |284 |291 |266
**Item Translucents**: |11 |33 |51
**Item Lights**: |19 |44 |27
**Timing Opaques**: |1394 |1534 |2987
**Timing Translucents**: |95 |260 |681
**Timing Lighting**: |156 |402 |295
**Render Frame**: |2367 |3732 |5655

**Comment by OmegaHeron** [comment]
Windows 10 64 bit - i5 6500 CPU - GTX970 GPU

**Note** for stats o2tech = localhost.  It remains impossible to run Interface AND Stack on my machine at same time (known issue nothing to do with this PR).  o2tech contains exact content as downloaded by Server Console loader and lives on second machine via LAN.

Desktop mode vsync unlocked 1600x900 maximized window.

**Domain** |o2tech |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |147 |118 |149
**Present Rate**: |1646 |1805 |2040
**Present New Rate**: |145 |118 |150
**CPU Buffer Count**: |5101 |5942 |4478
**GPU Buffer Count**: |1568 |1949 |989
**CPU Memory Usage**: |75665408 |108351488 |80433152
**GPU Memory Usage**: |56631296 |75689984 |43298816
**CPU Texture Count**: |305 |428 |325
**GPU Texture Count**: |532 |1172 |717
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |54467924 |111460488 |278771400
**GPU Texture Memory Usage**: |1107684977 |2508793856 |1191961971
**GPU Virtual Memory Usage**: |1225217777|2642353856|1309494771
**Triangle Count**: |296249 |773242 |616308
**Triangle Rate**: |42321285 |96655250 |77038500
**API Drawcall Count**: |187 |290 |240
**Drawcall Count**: |189 |351 |1148
**Drawcall Rate**: |27000 |43875 |143500
**State Changes Texture Count**:|205 |339 |282
**Pipeline Count**: |37 |37 |39
**Item Opaques**: |231 |458 |245
**Item Translucents**: |37 |55 |51
**Item Lights**: |28 |43 |25
**Timing Opaques**: |7596 |4821 |2879
**Timing Translucents**: |515 |234 |1070
**Timing Lighting**: |272 |324 |415
**Render Frame**: |5089 |6679 |6056

DK2

**Domain** |o2tech |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |62 |75
**Present Rate**: |75 |62 |75
**Present New Rate**: |75 |60 |75
**CPU Buffer Count**: |5361 |6022 |5400
**GPU Buffer Count**: |1352 |2477 |1492
**CPU Memory Usage**: |84914176 |95485952 |88248320
**GPU Memory Usage**: |26161152 |71090176 |39723008
**CPU Texture Count**: |278 |400 |324
**GPU Texture Count**: |3334 |4454 |3503
**GPU Transfer Count**: |23 |23 |23
**CPU Texture Memory Usage**: |250302808 |63687712 |534717360
**GPU Texture Memory Usage**: |799083207 |2444228628 |906567985
**GPU Virtual Memory Usage**: |1179729351|2894092692|1301057713
**Triangle Count**: |618213 |2369279 |1191204
**Triangle Rate**: |47554846 |91126115 |91631076
**API Drawcall Count**: |208 |376 |282
**Drawcall Count**: |391 |759 |2331
**Drawcall Rate**: |30076 |29192 |179307
**State Changes Texture Count**:|217 |363 |290
**Pipeline Count**: |43 |44 |40
**Item Opaques**: |240 |501 |263
**Item Translucents**: |32 |59 |51
**Item Lights**: |30 |55 |27
**Timing Opaques**: |1827 |3205 |1858
**Timing Translucents**: |224 |278 |363
**Timing Lighting**: |193 |405 |216
**Render Frame**: |3095 |5223 |3400

More to follow - I don't want to have to collect these numbers all over again in case of crash.

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Went fairly smooth, we had to fix an audio issue with Leo, but apart from that the basic tests all went well

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |59 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |6508 |2297 |4688
**GPU Buffer Count**: |1727 |975 |1424
**CPU Memory Usage**: |128729088 |40423424 |81666048
**GPU Memory Usage**: |84852736 |26542080 |45887488
**CPU Texture Count**: |238 |139 |295
**GPU Texture Count**: |5908 |5413 |5663
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |134189648 |69492952 |346287616
**GPU Texture Memory Usage**: |891807097 |508830217 |932864246
**GPU Virtual Memory Usage**: |1054095097|664626697|1088660726
**Triangle Count**: |2207196 |240388 |883739
**Triangle Rate**: |137949750 |17170571 |55233687
**API Drawcall Count**: |355 |131 |294
**Drawcall Count**: |355 |147 |294
**Drawcall Rate**: |22187 |10500 |18375
**State Changes Texture Count**:|272 |85 |303
**Pipeline Count**: |41 |35 |39
**Item Opaques**: |412 |316 |318
**Item Translucents**: |28 |63 |52
**Item Lights**: |21 |53 |27
**Timing Opaques**: |3547 |1675 |3924
**Timing Translucents**: |178 |538 |421
**Timing Lighting**: |202 |601 |219
**Render Frame**: |5365 |6850 |6350


--- Eye tests upcoming

**Comment by Nex-Pro** [comment]
**PR Build:** #8281
**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Many peaks over red-line in performance test at dev-playa


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |61 |60 |58
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |58
**CPU Buffer Count**: |4158 |5272 |5265
**GPU Buffer Count**: |664 |857 |1121
**CPU Memory Usage**: |61308928 |97935360 |112578560
**GPU Memory Usage**: |19824640 |21925888 |57597952
**CPU Texture Count**: |258 |375 |330
**GPU Texture Count**: |748 |974 |726
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |454557156 |906467104 |575525032
**GPU Texture Memory Usage**: |479456539 |1281217675 |837297037
**GPU Virtual Memory Usage**: |669121819|1470882955|1026962317
**Triangle Count**: |427961 |760237 |587514
**Triangle Rate**: |25174176 |47514812 |36719625
**API Drawcall Count**: |212 |284 |238
**Drawcall Count**: |212 |339 |1154
**Drawcall Rate**: |12470 |21187 |72125
**State Changes Texture Count**:|198 |323 |266
**Pipeline Count**: |24 |35 |38
**Item Opaques**: |259 |444 |243
**Item Translucents**: |8 |29 |50
**Item Lights**: |23 |44 |25
**Timing Opaques**: |1710 |2529 |1385
**Timing Translucents**: |101 |180 |270
**Timing Lighting**: |133 |211 |126
**Render Frame**: |2841 |4016 |2496

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**SUCCESS**
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|**SUCCESS**
**Test 3**|Retest that creating physicshulls is working|**SUCCESS**
**Test 4**|Test Ignore and make sure it works|Check. I can no longer see @Thoys **SUCCESS**
**Test 5**|test audio with multiple people|Patchy results with Philip, Thoys and Leo. Leo was very clipped.
**Test 6**|Test that you can go to suggested places|Not sure if this worked. Only option was Howard and I did not connect.

**Comment by SkimiMission** [comment]
With this build I don't hear audio anymore. Also the interface crashs permanently when switch from desktop to HMD. 

Windows 10 Pro, 16 GB, 970 GTX, i7 4790.

**Comment by thoys** [comment]
@SkimiMission please try again. There was some issue with the deploy of the (dev-)servers which caused some codec issues on dev-demo and dev-playa

**Comment by SkimiMission** [comment]
Okay, updated the server and re-installed/installed it. With this build 8281 its not possible for me to switch from desktop to HMD (Vive). When i try it, the log spawn only this (tons of this):

`[07/20 22:00:09] [WARNING] OpenGL error in presentation:  Invalid OpenGL operation`

the screen freeze, sometimes switch to just white. 

I was running the last PR8260 without any problems - and switched back to this for a test this afternoon. So in PR8260 I can switch between desktop and HMD with no problems.

**Pull request closed without merging**
