### PR TITLE
Fix audio packet queue behavior

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Code Review

Please look through my use of this queue and make sure the rest of it is good.

#### QA Plan

Run a domain with the audio-mixer using this build. Ensure that this doesn't pop up in your logs:
> [02/16 13:13:54] [DEBUG] [hifi.networking] [7896] [audio-mixer] unreasonable sequence number: 2485 (possible duplicate)

Ensure that there is not high audio packet loss.

Ensure that audio is smooth in a group of (at least) 5 people.

**Comment by zzmp** [comment]
I'm prepping a 5-person test right now, so **QA** you can ignore that part of the testing plan.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07e97a0cabefde7f739d116849e3c58fd91a3f03 available at: https://gist.github.com/583cfe130a6f5ba561e07a81fea35824<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9691-07e97a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9691-07e97a0.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07e97a0cabefde7f739d116849e3c58fd91a3f03 available at: https://gist.github.com/583cfe130a6f5ba561e07a81fea35824<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9691-07e97a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9691-07e97a0.dmg

**Pull request merged**
