### PR TITLE
[Scripts] Prevent mouse grab from moving 'ungrabbable' objects 

### PR DESCRIPTION
**Pull request by imgntn**
This PR gives the default grab.js script parity with the handControllerGrab.js script in respect to ungrabbable objects.

https://rawgit.com/imgntn/hifi/hand_grab/examples/grab.js

### CODE REVIEW

**Comment by ZappoMan** [comment]
@imgntn this PR needs to be updated from master... `git pull upstream master` and handle the merge conflicts

**Comment by imgntn** [comment]
@ZappoMan any idea why the whole merge history gets pulled in like that?  its kind of hard to see which files were actually changed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfab1fc6855cf3b65beff69573b280daead98246 available at: https://gist.github.com/048fd8bb1c95fc4f1d6d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5934.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5934.dmg

**Comment by ZappoMan** [comment]
I don't understand the question

**Comment by sethalves** [comment]
http://headache.hungry.com/~seth/respond-to-it.gif

**Pull request merged**
