### PR TITLE
hmd button

### PR DESCRIPTION
**Pull request by howard-stearns**
basic button to toggle between desktop and hmd

### CODE REVIEW

**Comment by howard-stearns** [comment]
this is for the vive-ui branch

**Comment by howard-stearns** [comment]
This is basic functionality, some of it just placeholder. For example, the image used is currently the same as the edit.js button.  It does not yet attempt to use button state to reflect the current mode.

test plan -- assumes that exactly one of vive or oculus is present. (Does not disable itself if neither is present.)

button should toggle between desktop and whichever of vive and oculus is present. Each transition will put you in pause mode (e.g., so that you can actually put on/off the headset), which then requires input to clear (unchanged in this pr).   Although the button state does not reflect desktop vs hmd, the Display menu items should reflect the actual state.

**Comment by howard-stearns** [comment]
(Initially, I'm not even concerned with the default placement of the button, although it should generally be "at the bottom" by the edit.js button.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68819561175d8495be22975dafd39b784ced661e available at: https://gist.github.com/bb680db59f28ffb4a685d2afd39c187d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8012.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8012.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xx3yBH3e&#x2F;3-the-user-can-enter-exit-hmd-mode-by-clicking-on-a-dedicated-overlay"> The user can enter&#x2F;exit HMD mode by clicking on a dedicated overlay</a>

**Comment by howard-stearns** [comment]
Hmmm. Merge comments are more buried than I had realized, so I'll surface the comment here for reference:

"I'm going to go ahead in merge this myself because it's isolated and I want to bring the branch to a consistent/known/planned state for evaluation. (We will be modifying the implementation going forward.) It's too confusing to equivocate as to what functionality "in" the vive-ui branch when this is pending."

**Pull request merged**
