### PR TITLE
activate RigidBody when removing physics Action

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR to fix a bug where is is possible to: grab a dynamic object with non-zero gravity, hold it very still for two seconds, let it go, and the physics engine could deactivate it such that it would "hang" in the air without falling.  The internal bug is manuscript issue 11443:
https://highfidelity.fogbugz.com/f/cases/11443/Some-dynamic-objects-float-when-juggled

**Test Plan**

**(1)** Make a dynamic object with low gravity = <0.0, -1.0, 0.0>
**(2)** Far-grab the object, hold it up in the air very still for two seconds, then let go
--> when using `hifi/master` the object would deactivate **(X)** in the physics simulation and remain in the air
--> when using this PR the object should always fall after the grab is released

**(X)**  Note: In order for the object to deactivate  when letting go you must hold it with a velocity smaller than 0.05 m/sec for two seconds

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10018/HighFidelity-Beta-PR13215-b41d20fe762225e31ce1e480219082f539543fd0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10018/HighFidelity-Beta-PR13215-b41d20fe762225e31ce1e480219082f539543fd0.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10018/HighFidelity-Beta-Interface-PR13215-b41d20fe762225e31ce1e480219082f539543fd0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10071/HighFidelity-Beta-PR13215-52c106edc8fe34e3d0aeb9172bc391231d034984.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10071/HighFidelity-Beta-PR13215-52c106edc8fe34e3d0aeb9172bc391231d034984.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10071/HighFidelity-Beta-Interface-PR13215-52c106edc8fe34e3d0aeb9172bc391231d034984.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10071/HighFidelity-Beta-PR13215-52c106edc8fe34e3d0aeb9172bc391231d034984.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10071/HighFidelity-Beta-Interface-PR13215-52c106edc8fe34e3d0aeb9172bc391231d034984.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Interface crashes after letting go of dynamic object. Defect did not occur when tested against Master (Build 8332). 
[PR13215.zip](https://github.com/highfidelity/hifi/files/2040744/PR13215.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10203/HighFidelity-Beta-PR13215-bc57003cfb917b028e869a461b34e4f10537575a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10203/HighFidelity-Beta-PR13215-bc57003cfb917b028e869a461b34e4f10537575a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10203/HighFidelity-Beta-Interface-PR13215-bc57003cfb917b028e869a461b34e4f10537575a.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qlihifitest** [comment]
PASS @conklin94122 Dynamic object always fall after grab is released

**Pull request merged**
