### PR TITLE
High Dynamic Range Audio injectors

### PR DESCRIPTION
**Pull request by kencooke**
This PR implements HDR audio injectors on both the client and the server. It allows the scripted injector "volume" to exceed 1.0, to a maximum of 32.0 (+30dB), which is handled without clipping by the floating-point audio pipeline. The final output to the audio device is still limited to 0dBFS (via a dynamic range compressor) but has several useful effects:
 - a "too quiet" sound asset can easily be made louder, without editing
 - a "loud" sound such as thunder at high volume, eg. 10.0 (+20dB) will travel farther before attenuating
 - an "overloud" sound like the thunder above, will overpower other sounds. Relative loudness is preserved by the final dynamic range compression to 0dB, so quiet sounds will be ducked.

This PR requires a protocol change, to send log-encoded stream gains over the wire.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 719c89e800fe60ba95c2257bff482b03390a9cc8 available at: https://gist.github.com/3c821bf5f1618c0261fc341ec45f7926<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9309-719c89e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9309-719c89e.dmg

**Comment by kencooke** [comment]
### Test Plan

Using both Interface and Sandbox from this build, verify that a sound played with volume > 1.0 is *louder*. There should never be clipping, only dynamic range compression (pumping/breathing) that may become audible at extreme gains.

For example, in a script or the JS Console:
```
sound = SoundCache.getSound("http://hifi-content.s3.amazonaws.com/ken/samples/1Shot Weather Thunderclap ST450 01_ambiX.wav");
Audio.playSound(sound, {volume:1});    // normal
Audio.playSound(sound, {volume:10});   // overloud
```

**Comment by nbq** [comment]
Testing now

**Comment by davidkelly** [comment]
I marked as dev approved.  But -- just as an aside, should we namespace the AudioHelpers?  I'm ok either way -- I've not really looked through the code to see if we _always_ namespace helpers or not.

**Pull request merged**
