### PR TITLE
Beta Release 11 - includes up to Developer Release 4901 with Roughness fix

### PR DESCRIPTION
**Pull request by ZappoMan**
- Show debug icons when someone else is the simulation owner
- Defer mipmap generation to GPU
- Fixing the bad color format on skymaps
- Switch OctreeSendThread and OctreePersistThread to use std::this_thread::sleep_for() instead of usleep()
- Make ResourceCache::resetResourceCounters threadsafe
- Fixes the collision sounds not playing for avatar and entities
- Add state changes to the ScriptableResource
- Updates to improve Grab script
- Linux client updates
- Use sleep_until for ScriptEngine
- Add an example gravity script
- Remove the recurring deadlock status log message
- Fix Script.include(/~/system/libraries/utils.js) to work from web
- Resurrection of threadsafe ViewFrustum
- Clean up resource cache's encapsulation of asynchronous loading
- Updates to default idle and turn animations
- Use smart pointers for entity simulations
- Enabling the use of QScriptEngineDebugger in Interface for script debugging
- Control the mouse with hand controllers (Razer Hydra and Vive)
- Don't show help or login on first run
- Fix for Vive controllers sometimes not working
- Eye tracking bug fix and debug rendering improvements
- Updates to Home content
- Introduce the "Unlit" shading model support and apply it to Web Entities
- Check vector access in fbx reader
- Fix reticle position offset
- Defaulting the color formats used in the rendering pipeline to sRGB
- Fix invisible default avatars
- Fix for better out of Away mode in Vive
- Fix procedural rendering on primitives
- Support partial CPU->GPU buffer transfers
- Fix texture sampler calculation
- Fix hang on exit from dying scripts
- Remove the last of the avatar billboard code
- When a ModelEntityItem moves, also update its meta-render-item
- Wait and cleanly exit the scripting thread
- Fix roughness/metallic of some materials

Test Notes:

This is a combination of overall smoke testing, combined with specific tests.

There is a QA script that you can use for general testing : http://rawgit.com/cozza13/QAtesting/master/qaTest20.js

Within this script there is a help section they you should take a look at, As a first step you can run through the smoke testing section.

### CODE REVIEW

**Comment by ZappoMan** [comment]
**Test Notes:**

This is a combination of overall smoke testing, combined with specific tests. 

There is a QA script that you can use for general testing : http://rawgit.com/cozza13/QAtesting/master/qaTest20.js

Within this script there is a help section they you should take a look at, As a first step you can run through the smoketesting section. 

capture

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd16d4ede986205e24306e97c0e9f422def8c4d0 available at: https://gist.github.com/7fee59be0ee0265234ff029e6e590719<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7915.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7915.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Edit** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test. Metallic feature working properly. Screen shot included.

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |55 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |55 |60
**CPU Buffer Count**: |3007 |4539 |2214
**GPU Buffer Count**: |308 |526 |331
**CPU Memory Usage**: |62005248 |86425600 |32763904
**GPU Memory Usage**: |11259904 |19779584 |14573568
**CPU Texture Count**: |154 |257 |139
**GPU Texture Count**: |86 |110 |69
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |213872604 |357918932 |127862420
**GPU Texture Memory Usage**: |294533951 |387335153 |253420263
**GPU Virtual Memory Usage**: |294533951|387335153|253420263
**Triangle Count**: |137184 |292522 |265493
**Triangle Rate**: |8069647 |17207176 |15617235
**API Drawcall Count**: |83 |125 |67
**Drawcall Count**: |82 |130 |67
**Drawcall Rate**: |4823 |7647 |3941
**State Changes Texture Count**:|78 |136 |47
**Pipeline Count**: |27 |23 |20
**Item Opaques**: |88 |188 |178
**Item Translucents**: |9 |4 |19
**Item Lights**: |22 |22 |1
**Timing Opaques**: |800 |6080 |597
**Timing Translucents**: |115 |21 |173
**Timing Lighting**: |165 |249 |72
**Render Frame**: |1844 |7553 |1422
pr7915 music

**Comment by Nex-Pro** [comment]
## QA Test: #7915
**Testing Architecture: Desktop PC 4.0 ghz i7  Nvidia gtx770 2gb**
**Testing OS: win 10 pro** 

## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Edit** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**: 
Shiny was shiny.( drumkit ) 

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |56 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |55 |60
**CPU Buffer Count**: |4525 |4385 |2569
**GPU Buffer Count**: |851 |918 |678
**CPU Memory Usage**: |64266240 |81293312 |36704256
**GPU Memory Usage**: |28102656 |28835840 |18378752
**CPU Texture Count**: |289 |215 |196
**GPU Texture Count**: |212 |176 |165
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |306881740 |222332896 |195594208
**GPU Texture Memory Usage**: |1206245028 |857798045 |817253116
**GPU Virtual Memory Usage**: |1206245028|857798045|817253116
**Triangle Count**: |493348 |660741 |400666
**Triangle Rate**: |30834250 |38867117 |23568588
**API Drawcall Count**: |238 |222 |128
**Drawcall Count**: |235 |223 |128
**Drawcall Rate**: |14687 |13117 |7529
**State Changes Texture Count**:|229 |193 |82
**Pipeline Count**: |31 |27 |21
**Item Opaques**: |279 |347 |658
**Item Translucents**: |15 |50 |26
**Item Lights**: |24 |40 |1
**Timing Opaques**: |1539 |1822 |1399
**Timing Translucents**: |92 |154 |262
**Timing Lighting**: |115 |188 |75
**Render Frame**: |2385 |2998 |2521

**Comment by Menithal** [comment]
## QA Test
**QA Tester**: Menithal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Add To World + Move Around + Delete - SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Metal Works again

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |58 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |57 |59
**CPU Buffer Count**: |6158 |5148 |1722
**GPU Buffer Count**: |1798 |1575 |472
**CPU Memory Usage**: |79495168 |96006144 |31059968
**GPU Memory Usage**: |46219264 |62947328 |16486400
**CPU Texture Count**: |390 |330 |180
**GPU Texture Count**: |336 |281 |155
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |267906108 |689841992 |174730312
**GPU Texture Memory Usage**: |1713579724 |2116636634 |907020274
**GPU Virtual Memory Usage**: |1713579724|2116636634|907020274
**Triangle Count**: |152024 |608390 |28599
**Triangle Rate**: |8942588 |32020526 |1787437
**API Drawcall Count**: |186 |191 |21
**Drawcall Count**: |314 |192 |21
**Drawcall Rate**: |18470 |10105 |1312
**State Changes Texture Count**:|124 |203 |22
**Pipeline Count**: |36 |26 |16
**Item Opaques**: |204 |305 |12
**Item Translucents**: |43 |10 |2
**Item Lights**: |21 |28 |0
**Timing Opaques**: |1541 |2373 |230
**Timing Translucents**: |246 |75 |53
**Timing Lighting**: |222 |206 |56
**Render Frame**: |2857 |3636 |969

**Comment by cozza13** [comment]
tested hand controllers grabing and eyes. QA Pass

**Comment by kevinmthomas-carpool** [comment]
Additional RC testing:
1)Successfully completed various crash modes (rapid restart, rapid domain switch, 
shutdown while resources are loading) to which there was no issue.
2)Ran ```test.js``` it worked without issue except on shutdown it deadlocked the screen white.  Had to manually close Interface.  No bugsplat or crash message.
3)Ran ```loop.js``` as an entity script in a cube and the result was:[WARNING] [UncaughtException] Error: Timed out (entity constructors are limited to 250ms) in (EntityID:{663dd815-be07-49c4-8901-6d6ecdc3fb49}, https://dl.dropboxusercontent.com/u/17344741/loop.js):1
4)Ran ```unloadloop.js``` as an entity script in a cube:[DEBUG] Done downloading script at: "https://dl.dropboxusercontent.com/u/17344741/unloadloop.js" and did nothing beyond that.  Switched domains rapidly and no issue.

**Pull request merged**
