### PR TITLE
fix can't grab tablet

### PR DESCRIPTION
**Pull request by sethalves**
- grab script checks for hand-controllers continually rather than just at startup

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- pull the batteries out of your touch controllers
- start interface
- switch to HMD mode
- put batteries back in touch controllers
- open tablet
- grab and move tablet

**Comment by zfox23** [comment]
I'll QA this once the build is ready.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6420ddd03806cda8f8cc988f5f6a399768238c06 available at: https://gist.github.com/410b3f73f063d50d6a7505e04ddf73dd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10222-6420ddd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10222-6420ddd.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 110cfb47d1bca930fd3e6a5235a33a24ddf49142 available at: https://gist.github.com/410b3f73f063d50d6a7505e04ddf73dd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10222-110cfb4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10222-110cfb4.dmg

**Comment by cozza13** [comment]
tested, repro'ed the issue on the older build. Fixed on this one.

**Pull request merged**
