### PR TITLE
Beta Release 66 - includes up to Developer Release 8013

### PR DESCRIPTION
**Pull request by conklin94122**
**New Features**

- [Marketplace item update](https://forums.highfidelity.com/t/marketplace-updates-have-arrived/14027): content creators can upload an updated version of their Marketplace item and replace the old one. When an item you own gets updated, you’ll receive a notification. 
- New installer allows for downloading and running the High Fidelity client without the local server-based tutorial. The new installer will be rolled out in phases after this release, starting with Steam. Tutorial is now part of the client and it is your default home.
- You can make objects cast shadows in your domain via the Create menu!
- Added ability to swap out material on primitive models. The steps to do this on primitives are the same as the ones for entities in Beta Release 65.
- QT upgrade to 5.10.1. You should upgrade your QT library if you are building from source code.
- Improved audio quality for streaming music 
- Tablet reposition and resize to address feedback about it being in the way and too large when it first appears.
- Support for OBJ baking in Oven tool. This standalone Oven tool now supports baking of assets in OBJ format in addition to the already-supported FBX format.

**Bug Fixes**

- Fix bug causing avatars to disappear when scaled using Vive controllers 
- Fixed bug causing Mac client to crash when mirrors are activated
- Fixed bug causing the audio scope to not appear
- Fixed bug causing audio toggle to become unresponsive
- Fixed issue which caused extra entities to be created unintentionally
- Fixed bug causing avatar hand jitters
- QML crash fixes
- Show instructions for sending HFC when user has not make any connections yet  
- Improve font loading 
- Assorted bug fixes for the Android project

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8257/HighFidelity-Beta-PR12705-11f5e7812b2a92b6c5f8e3c273d5a2523970b2f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8257/HighFidelity-Beta-PR12705-11f5e7812b2a92b6c5f8e3c273d5a2523970b2f7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8266/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8266/HighFidelity-Beta-PR12705-3e23ad49004800918ef611415c98810c7848d123.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8266/HighFidelity-Beta-PR12705-3e23ad49004800918ef611415c98810c7848d123.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8301/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8301/HighFidelity-Beta-PR12705-7c505a0b85ed96bb18790bcb372208f4c674b586.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8301/HighFidelity-Beta-PR12705-7c505a0b85ed96bb18790bcb372208f4c674b586.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8306/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8306/HighFidelity-Beta-PR12705-0862f345feb4bb8c526c289ba2a9a0631fcf5953.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8306/HighFidelity-Beta-PR12705-0862f345feb4bb8c526c289ba2a9a0631fcf5953.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8318/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8318/HighFidelity-Beta-PR12705-d59a721f1675c7bd02809e06e407f573475d3bf3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8318/HighFidelity-Beta-PR12705-d59a721f1675c7bd02809e06e407f573475d3bf3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8345/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8345/HighFidelity-Beta-PR12705-c4b46d0a5ff9cf1141d3fd2cba7dedd152db1405.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8345/HighFidelity-Beta-PR12705-c4b46d0a5ff9cf1141d3fd2cba7dedd152db1405.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8362/HighFidelity-Beta-PR12705-c7f7e2487c0fbb30792e26659d25f9b37aac348e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8371/HighFidelity-Beta-PR12705-90dec1d3efd0ea14402f06359c27bc2d49c22cb0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8379/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8379/HighFidelity-Beta-PR12705-5013760aa1cb3a976bc98c337b0af4cf6b9bc56b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8379/HighFidelity-Beta-PR12705-5013760aa1cb3a976bc98c337b0af4cf6b9bc56b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8398/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8398/HighFidelity-Beta-PR12705-8c8400947f2b753d60acedf7f212f40f50d74e90.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8423/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8423/HighFidelity-Beta-PR12705-aceb3d13b49ed49cddd58a9d4d15256a13780565.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8423/HighFidelity-Beta-PR12705-aceb3d13b49ed49cddd58a9d4d15256a13780565.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8458/HighFidelity-Beta-PR12705-5151041e4a71c289c444e0b54ece08793f52f8be.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8498/HighFidelity-Beta-PR12705-c3cad62bff572836fa462730be1a9ee6044ae056.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8498/HighFidelity-Beta-PR12705-c3cad62bff572836fa462730be1a9ee6044ae056.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8523/HighFidelity-Beta-PR12705-3bc764a020f7bc317f1e570c54ff71bec767501f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8582/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8582/HighFidelity-Beta-PR12705-c8d109854bbc94598072721eab7461ec97e77ce0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8582/HighFidelity-Beta-PR12705-c8d109854bbc94598072721eab7461ec97e77ce0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8588/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8591/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8591/HighFidelity-Beta-PR12705-fe5e797a24b873818f07a5036b5dc39378abc182.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8595/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8591/HighFidelity-Beta-PR12705-fe5e797a24b873818f07a5036b5dc39378abc182.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8595/HighFidelity-Beta-PR12705-02422ba5383690a8bfcb643ae5ef11f66402eb73.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8595/HighFidelity-Beta-PR12705-02422ba5383690a8bfcb643ae5ef11f66402eb73.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8631/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8631/HighFidelity-Beta-PR12705-d281d7b2cbfcb96dd2036285f7cbf09712b16843.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8631/HighFidelity-Beta-PR12705-d281d7b2cbfcb96dd2036285f7cbf09712b16843.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8637/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8639/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8639/HighFidelity-Beta-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.exe

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8660/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8660/HighFidelity-Beta-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8660/HighFidelity-Beta-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.exe

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8662/HighFidelity-Beta-Interface-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8667/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8667/HighFidelity-Beta-Interface-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8667/HighFidelity-Beta-Interface-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8698/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8698/HighFidelity-Beta-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8698/HighFidelity-Beta-PR12705-4dcab95b40387c85cf811bfd8c6acde0870d1551.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8704/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8704/HighFidelity-Beta-PR12705-b2bc2b6e439de3cf9487173a5d2a8cfd93a8bf3c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8704/HighFidelity-Beta-PR12705-b2bc2b6e439de3cf9487173a5d2a8cfd93a8bf3c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8710/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8710/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8710/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8720/app_12705_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8720/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8720/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8720/HighFidelity-Beta-Interface-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8733/app_12705_PR_005b55f997efb8b41baede31f175e8d229e4178f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8733/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8733/HighFidelity-Beta-Interface-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8733/HighFidelity-Beta-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8733/HighFidelity-Beta-Interface-PR12705-005b55f997efb8b41baede31f175e8d229e4178f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8751/app_12705_PR_9ccf23ec94619299de52093698ab485ac3c598c2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8751/HighFidelity-Beta-PR12705-9ccf23ec94619299de52093698ab485ac3c598c2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8751/HighFidelity-Beta-Interface-PR12705-9ccf23ec94619299de52093698ab485ac3c598c2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8789/app_12705_PR_2b9cf829a20b03691996e62b036bbb967b4d9175.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8789/HighFidelity-Beta-PR12705-2b9cf829a20b03691996e62b036bbb967b4d9175.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8789/HighFidelity-Beta-Interface-PR12705-2b9cf829a20b03691996e62b036bbb967b4d9175.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8789/HighFidelity-Beta-PR12705-2b9cf829a20b03691996e62b036bbb967b4d9175.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8789/HighFidelity-Beta-Interface-PR12705-2b9cf829a20b03691996e62b036bbb967b4d9175.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8793/app_12705_PR_3982472cf2ec31ea76385ba6fde667e2470df27d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8793/HighFidelity-Beta-PR12705-3982472cf2ec31ea76385ba6fde667e2470df27d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8793/HighFidelity-Beta-Interface-PR12705-3982472cf2ec31ea76385ba6fde667e2470df27d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8793/HighFidelity-Beta-PR12705-3982472cf2ec31ea76385ba6fde667e2470df27d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8793/HighFidelity-Beta-Interface-PR12705-3982472cf2ec31ea76385ba6fde667e2470df27d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8817/app_12705_PR_40e34f578a6cbb51f40139a541dcadbf11de2cd9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8817/HighFidelity-Beta-PR12705-40e34f578a6cbb51f40139a541dcadbf11de2cd9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8817/HighFidelity-Beta-Interface-PR12705-40e34f578a6cbb51f40139a541dcadbf11de2cd9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8817/HighFidelity-Beta-PR12705-40e34f578a6cbb51f40139a541dcadbf11de2cd9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8817/HighFidelity-Beta-Interface-PR12705-40e34f578a6cbb51f40139a541dcadbf11de2cd9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8853/HighFidelity-Beta-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8853/HighFidelity-Beta-Interface-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8853/HighFidelity-Beta-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8853/HighFidelity-Beta-Interface-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8874/app_12705_PR_44e0a2acc51ec90643f4ac7155edca261d8da085.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8874/HighFidelity-Beta-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8874/HighFidelity-Beta-Interface-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8874/HighFidelity-Beta-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8874/HighFidelity-Beta-Interface-PR12705-44e0a2acc51ec90643f4ac7155edca261d8da085.exe

**Pull request merged**
