### PR TITLE
Innocuous change to default avatar preference text for build test

### PR DESCRIPTION
**Pull request by vormooth**
⚠️ Do not merge ⚠️ 

This is a proof-of-build test.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
Ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2326/HighFidelity-Beta-PR11136-eed8534ff1a47fbe16d9855ba1e84750792ca8d2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2326/HighFidelity-Beta-PR11136-eed8534ff1a47fbe16d9855ba1e84750792ca8d2.exe

**Pull request closed without merging**
