### PR TITLE
Update styling of property spinners in edit.js

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 775bbdaebb245e10f8fa4cc882010a4cb43ee579 available at: https://gist.github.com/da820aa944628fa304f7<br/><br/>No installer was built for this commit

**Comment by murillodigital** [comment]
this is stable

**Comment by murillodigital** [comment]
this is stable

**Comment by murillodigital** [comment]
this is stable

**Pull request merged**
