### PR TITLE
6819 - Create button not disabled

### PR DESCRIPTION
**Pull request by ElderOrb**
for QA: 

1. Go to the domain "Zaru". 
2. Ensure that both Create icon and text below becomes grey
3. Go to the domain 'localhost' 
4. Ensure that both Create icon and text below are white

https://highfidelity.fogbugz.com/f/cases/6819/Create-button-not-disabled

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2876/HighFidelity-Beta-PR11266-180acbc188db5c7fb43df46dfaf4185567c7ec23.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2876/HighFidelity-Beta-PR11266-180acbc188db5c7fb43df46dfaf4185567c7ec23.exe

**Comment by skytoad** [comment]
testing

**Comment by zfox23** [comment]
[Zach's Punchlist of Random Things (see desc)](https://trello.com/c/g0SHpa8q/353-zachs-punchlist-of-random-things-see-desc)

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2883/HighFidelity-Beta-PR11266-180acbc188db5c7fb43df46dfaf4185567c7ec23.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2888/HighFidelity-Beta-PR11266-180acbc188db5c7fb43df46dfaf4185567c7ec23.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2888/HighFidelity-Beta-PR11266-180acbc188db5c7fb43df46dfaf4185567c7ec23.exe

**Comment by skytoad** [comment]
Pass. As an extra facet, I attempted to interact with the create button by clicking with the mouse in desktop view and laser pointers on VR toolbar. Neither showed any response.

**Pull request merged**
