### PR TITLE
Case20615 - Changing Avatars doesn't update to everyone intermittently

### PR DESCRIPTION
**Pull request by roxanneskelly**
Pull of Case20615 (pull request 14701) into 0.78.0 rc

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16427/HighFidelity-Beta-PR14708-0f822b1.apk

**Comment by roxanneskelly** [comment]
Test Plan: see test plan from
https://github.com/highfidelity/hifi/pull/14701

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16427/HighFidelity-Beta-PR14708-0f822b1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16427/HighFidelity-Beta-Interface-PR14708-0f822b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16427/HighFidelity-Beta-PR14708-0f822b1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16427/HighFidelity-Beta-Interface-PR14708-0f822b1.exe

**Comment by roxanneskelly** [comment]
https://highfidelity.fogbugz.com/f/cases/20615/Changing-Avatars-doesn-t-update-to-everyone-intermittently

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
Avatar changes and Avatar attachments - Pass

Setup sandbox with two users on this PR, both users connected and were able to change their avatars multiple times (20+ times) with no issues of the avatars becoming stuck. Attachments worked without issue, appearing, disappearing, or resizing correctly for both users.

Antonina is testing the Distributed3 portion of the test.

**Pull request merged**
