### PR TITLE
make self-reverb depend on wetDryMix

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a51cc9d12abb4d0415e2d139ef86dc47a1912c45 available at: https://gist.github.com/8a47c363fcab276100d1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7496.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7496.dmg

**Comment by AndrewMeadows** [comment]
@kencooke, could you provide a basic testplan for this PR?  How to dial the wet/dry ratio and how would someone know if it is working or not?  Does it require a trained ear or should it be clear to just about anyone?

**Comment by kencooke** [comment]
Freidrica did some testing and can document when she gets in.  You need to create a reverb zone in the domain settings, and verify that wetDryMix now modulates the amount of self-reverb in that zone.

**Comment by Freidrica** [comment]
I detected the issue in the first place (wet/dry zone setting not modulating self reverb) and have verified that it works well now in this PR.

**Pull request merged**
