### PR TITLE
Case 21304: Fix text overlay color property (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/14952

https://highfidelity.manuscript.com/f/cases/21304/Text-Overlay-color-property-doesn-t-work-anymore

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17387/HighFidelity-Beta-PR14953-b02355f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17387/HighFidelity-Beta-PR14953-b02355f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17387/HighFidelity-Beta-Interface-PR14953-b02355f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17387/HighFidelity-Beta-PR14953-b02355f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17387/HighFidelity-Beta-Interface-PR14953-b02355f.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
