### PR TITLE
Unifying Windows PR and Release installer pipeline

### PR DESCRIPTION
**Pull request by murillodigital**
The NSIS and CMake code to produce an installable package is now consolidates across release types and all part of the hifi repo.

Note to reviewer: This PR removes the use of CPack (which skips the generation of the PACKAGE.vcxproj file), and requires build pipeline changes to become live. I need this code merged so I can work on further changes of the build pipeline, talk to me to make you feel comfortable.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 66770cc907c654d03b01dd6dc3b5a294467955b8 available at: https://gist.github.com/61fa67ba8ea9747eca90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6674-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7b61cf791387695126b9da9a56233ab06ab170a available at: https://gist.github.com/61fa67ba8ea9747eca90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6674-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbe444ffc1a4833f7b4bab49d81d02a02494782c available at: https://gist.github.com/61fa67ba8ea9747eca90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6674-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6674.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbe444ffc1a4833f7b4bab49d81d02a02494782c available at: https://gist.github.com/61fa67ba8ea9747eca90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6674-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6674.dmg

**Comment by ZappoMan** [comment]
smoked this on windows... the installer looks the same as release, and the interface and stack manager ran ok

**Pull request merged**
