### PR TITLE
Scribe now outputs shaders as cpp files

### PR DESCRIPTION
**Pull request by Zvork**
This PR changes the way shader files are referenced inside the code. The scribe tool (combined with a modified cmake macro AutoScribeShader) now outputs for each shader a C++ source file (and not a header file as before). This cuts source dependencies between shader code and C++ code as shader sources are referenced through an "extern const char*" for each shader source, yielding quicker build times, especially when shader code is modified. This will enable quicker iterations when working on shaders.

**Update**: in latest version, shaders are now built by Scribe as a .h and .cpp file containing a static class for each shader.

# Test Case
To test this PR, users should previously erase all *.h files inside all _shaders_ directories in the build subtree to be sure there is no pollution (even though these shouldn't be referenced anymore). Building the solution should create all the shader "cpp" files and be successfull (not compilation or link errors) for all projects.

On running "interface", no shader compilation error should be launched (see developer log).

There should no visual difference between this PR and master when using "interface".

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6251/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6251/HighFidelity-Beta-PR12161-814de4ab81f335d550d09ee42b6d84b0b1dff196.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6251/HighFidelity-Beta-PR12161-814de4ab81f335d550d09ee42b6d84b0b1dff196.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6252/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6252/HighFidelity-Beta-PR12161-420b58fd5b031bac28f11e281e006cd6d891f113.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6252/HighFidelity-Beta-PR12161-420b58fd5b031bac28f11e281e006cd6d891f113.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6258/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6258/HighFidelity-Beta-PR12161-98a47e56fc447f9ad3ad2fd1057ed1ee218ac146.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6359/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6359/HighFidelity-Beta-PR12161-157a229a4fd57c571a4c05b656bb6ab9efa09342.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6360/app_12161_PR.apk

**Comment by Zvork** [comment]
Following discussions with @samcake , Scribe now can output a .h/.cpp per shader for a cleaner interface. It also allows us to limit the number of generated shader OpenGL objects. As a bonus, generated files are now in Shaders/generated sub group in project solution.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6360/HighFidelity-Beta-PR12161-efa6a8c0b53994ba22220e602d1d1399469a4d9e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6360/HighFidelity-Beta-PR12161-efa6a8c0b53994ba22220e602d1d1399469a4d9e.dmg

**Comment by Zvork** [comment]
Build failed on Android as expected because it is using the old Scribe.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6368/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6368/HighFidelity-Beta-PR12161-604817bb59ee3fac1211bd2e743e1107def4556e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6564/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6564/HighFidelity-Beta-PR12161-95882e0cded6b7be61b4750dbcc4d4dc8a40df4d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6564/HighFidelity-Beta-PR12161-95882e0cded6b7be61b4750dbcc4d4dc8a40df4d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6707/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6707/HighFidelity-Beta-PR12161-5e6300ce46b1bcbcf18cb0769883c8ec23265f2b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6707/HighFidelity-Beta-PR12161-5e6300ce46b1bcbcf18cb0769883c8ec23265f2b.exe

**Comment by mrnapz** [comment]
@hifi-gustavo cannot download the apk no permition

**Comment by Zvork** [comment]
@mrnapz Yes, the android version doesn't build because the build process on that platform doesn't build scribe. It's known.

**Comment by themelissabrown** [comment]
@Zvork @samcake what are next steps on this PR? Does it need QA?

**Comment by Zvork** [comment]
@themelissabrown I was under the impression that this was a low priority PR, right @samcake ? Personnally, I must admit that it would be great to validate as it will accelerate further shader based developments. And by the way, @samcake , this PR has the side effect of limiting the number of shader compilations. Wouldn't this help solve the crash identified on Mac?

**Comment by themelissabrown** [comment]
@zvork even low priority PRs get checked in on once they start to age. I poke at everything over 2 weeks old.

**Comment by Zvork** [comment]
@themelissabrown QA would nice I suppose, then!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6862/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6862/HighFidelity-Beta-PR12161-ac92b3c130aab25fb2ff3e0c5ae85248113ed4ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6862/HighFidelity-Beta-PR12161-ac92b3c130aab25fb2ff3e0c5ae85248113ed4ad.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6915/app_12161_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6915/HighFidelity-Beta-PR12161-92279b593921a1a2c955d50ee813d4e5cab030df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6915/HighFidelity-Beta-PR12161-92279b593921a1a2c955d50ee813d4e5cab030df.exe

**Pull request merged**
