### PR TITLE
clean and comment AudioRingBuffer

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b740b9802a1a4084e6f7b4b2b2289bd21400e3c9 available at: https://gist.github.com/9bafe195325462a32385df5de87810c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-b740b98.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-b740b98.dmg

**Comment by zzmp** [comment]
Hold off on `QA Ready` until dev approval.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ba96ab25dce8ffe307033964f46e326d8e893213 available at: https://gist.github.com/9bafe195325462a32385df5de87810c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-ba96ab2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-ba96ab2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d4a68d706e1ea760f7f5cfd03e30019fd512505 available at: https://gist.github.com/9bafe195325462a32385df5de87810c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-4d4a68d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8553-4d4a68d.dmg

**Comment by zzmp** [comment]
Adding DNM in case this project takes a different direction, so the CR effort is not wasted.

**Comment by zzmp** [comment]
QA: Audio smoke test

**Comment by nbq** [comment]
Testing this now

**Pull request merged**
