### PR TITLE
fix wallet login (and share code with snapshot login)

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
internal test only:
to test, try to share a snapshot or set up wallet while not being logged in, from all four of desktop/hmd x toolbar/tablet.  The toolbar versions should bring up login modal, and the tablet versions should bring up login screen. (I haven't attempted to fix the lack of keyboard focus in the tablet.)

**Comment by zfox23** [comment]
testing after building myself

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2880/HighFidelity-Beta-PR11268-5b264a867aefa0b6e5ed509f9706724844924701.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2880/HighFidelity-Beta-PR11268-5b264a867aefa0b6e5ed509f9706724844924701.dmg

**Pull request merged**
