### PR TITLE
Disable user hand controllers if they are too far away or not moving.

### PR DESCRIPTION
**Pull request by hyperlogic**
This is to make users avatars look more natural when their hand controllers are left sitting on the desk, or resting on the arm rests of a chair.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/17534/Disable-arm-IK-when-hand-controllers-are-very-far-away

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13989/HighFidelity-Beta-PR14221-27c4954.apk

**Comment by hyperlogic** [comment]
QA test plan:
* Enter VR mode
* Ensure that your user height is set correctly in the Settings > Controls screen.
* Place your hand controllers on the desk in front of you, but still within reach.  After a few seconds, the hands of you avatar should drop to a resting idle position.
* Rest your hand controllers on the desk in front of you, and walk away from them so they are no longer within reach, the hands of your avatar should drop to an idle resting position as we detect the controllers are beyond your reach.
* Your hands should not drop to your sides in normal use, i.e. your hands are moving.  Even if you reach as far as you can.

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13989/HighFidelity-Beta-Interface-PR14221-27c4954.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13989/HighFidelity-Beta-PR14221-27c4954.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13989/HighFidelity-Beta-Interface-PR14221-27c4954.dmg

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by FlameSoulis** [comment]
Just throwing this in: be sure to also ensure this does not interrupt full body tracking. If a user is posed, say laying down, that the lack of movement doesn't suddenly cause this feature to interrupt that pose. In that case, even sitting down would make sense to not disable the hand controllers since users can tell the user is sitting due to the tracking.

**Pull request merged**
