### PR TITLE
Migrate Linux to use GLEW and move to parity with windows for Opengl (compatibility 4.3)

### PR DESCRIPTION
**Pull request by samcake**
- Require GLEW for linux and impose a minimu building gl version of 4.3 compatibility 
THIS WILL MAKE USER OF OLD HW on LINUX unhappy...

- remove all the includes for GPUConfig.h and GLBackend.h all over the place, try to keep it as clean as possible

- Hide the fact that the UniformBUffer are not supported on MAC GL Legacy by detecting the uniform with the name of a required uniform buffer binding and then expose it as a BUffer (The mac issue)

- CLean up the initialization process for gpuCOntext and the assignment of a unique Backend Type

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8dd85aab1431884474be92a301070e72661c503c available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76acbde5955c1cd3f33d8e7228e19ae8899b6f34 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17650dde74598fb1cdff9df8979d7f8db096546c available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by AndrewMeadows** [comment]
I know this PR adds a new dependency to linux (**libglew-dev** package) but does it also add installation dependencies on the other supported operating systems?  Should the BUILD*.md files document new dependencies?

**Comment by samcake** [comment]
Good point Andrew, i need to add the requirements for LInux

**Comment by hifi-gustavo** [comment]
Build console output for commit: 661f29924fd79f6be76468ff5f6376b8153db557 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c96096a67cffab2a379221691af2eaa4392d3ff available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9601e09ba9301005057a608893e82e23f7734427 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c934af297617fcceb90b5b70366c673be5dc768 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c934af297617fcceb90b5b70366c673be5dc768 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 269db0ff6fc71aeca8179e173ad3e9e042f1da6c available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5baf993c24a70b26de159259a5a6fbb5d6ffbc0f available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by jherico** [comment]
stars look good again on Windows, but there appears to be a state management bug, since if I turn on smoothing on both the grid and stars pipeline, the stars render as squares.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b84302a44a1cdc9774285c170dfb540d541d442d available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d84e2d31ea6e206fce7d1e14abd56fac5839c6cf available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by ZappoMan** [comment]
screen shot 2015-07-30 at 1 19 17 pm

Mac rendering is borked... models render as "transparent" and primitives (box, sphere) render as black

**Comment by hifi-gustavo** [comment]
Build console output for commit: 14f4c9c6c04b462f177828717803f52256902887 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by samcake** [comment]
This should be good to go now

**Comment by hifi-gustavo** [comment]
Build console output for commit: fbf21cb089a4579b507dee31110266f183429243 available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b08b2d29ccde80a143b0a080e0732b88c03ab71d available at: https://gist.github.com/aceab8c0d717422d8d69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5452.dmg

**Comment by sethalves** [comment]
I've tested this on Ubuntu 14.10 on a newish macbook, and it works.  It fails on an older macbook, but so does master.

**Comment by ZappoMan** [comment]
tested on windows and mac. looks great.

**Pull request merged**
