### PR TITLE
Make zones, lights, and particles not grabbable when created in edit.js

### PR DESCRIPTION
**Pull request by misslivirose**
**FB Case 10583**
By default, lights, zones, and particle effects should not be created as grabbable. This PR changes the functionality for these types of entities only and updates the menu in Interface to reflect which entities _will_ be made grabbable if 'Create Entities as Grabbable' (Advanced Menus on) is checked.

Test plan:
- Run Create Tab test plan 6766 and confirm that the cube creation still follows the expected behavior as written in that test plan
- Run Create Tab test plans 6768, 6769, and 6771 and confirm that instead of user data showing `userData {1} section with grabbableKey {1} grabbable: true ` for the Zone, Particles, and Light entity types, it shows as `userData {1} section with grabbableKey {1} grabbable: false`
- Confirm that with Advanced Menus enabled, the 'Create Entities as Grabbable' menu item now reads Create Entities as Grabbable (except Zones, Particles, and Lights)

I have created FB Case 11214 to reflect changes to the test cases with the new expected behavior per this PR

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6076/app_12105_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6076/HighFidelity-Beta-PR12105-d1e176ee9d236350a13288505f009572601f9508.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6076/HighFidelity-Beta-PR12105-d1e176ee9d236350a13288505f009572601f9508.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing complete. PASSED.

**Pull request merged**
