### PR TITLE
Add force delete to internal EntityTree deletes

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
@ZappoMan I tested this around apartment and it fixed the errors that were popping up.  That said, I was having a hard time testing with lifetime - settings lifetime > 0 seemed to either cause it to disappear immediately or seemingly change nothing at all.

**Comment by huffman** [comment]
@ZappoMan Actually, after trying another time around, I'm able to test with a lifetime of 10 (I assume it is in seconds?  Seems to be) + locked and get the correct behavior client-side.  The entity still exists when reconnecting, but I would expect that given the server hasn't been updated and so won't have deleted the locked item successfully.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b00e3fadc61872b005e9dff072b16d2ecdf16d8 available at: https://gist.github.com/4ccc255d96d198172733<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4227.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4227.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b00e3fadc61872b005e9dff072b16d2ecdf16d8 available at: https://gist.github.com/ab47297fb0ce5ba270d3<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4227.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4227.dmg

**Pull request merged**
