### PR TITLE
Case 21708: Remove .vs folder from version control

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.manuscript.com/f/cases/21708/Remove-vs-folder-from-version-control

no testing necessary

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18118/HighFidelity-Beta-PR15177-d8139af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18118/HighFidelity-Beta-Interface-PR15177-d8139af.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18118/HighFidelity-Beta-PR15177-d8139af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18118/HighFidelity-Quest-Beta-PR15177-d8139af.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18118/HighFidelity-Beta-PR15177-d8139af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18118/HighFidelity-Beta-Interface-PR15177-d8139af.exe

**Comment by SamGondelman** [comment]
whoops my bad, thanks for fixing

**Pull request merged**
