### PR TITLE
Fix reliability of keyboard enabling in tablet Web pages

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Test another recent PR build:
- In HMD, in tablet, click "GOTO".
- Click the "i" for a place or snapshot.
- Click the Twitter button.
- The keyboard should display on the tablet when your cursor is in the username or password fields. Does it?
- Restart Interface and repeat this test N times. How often does the keyboard display?

If the keyboard doesn't always display, repeat the above test with this PR build. The keyboard should display 100% of the time.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7b387c52c37cd0a777e9a408869811c2d6a908bd available at: https://gist.github.com/87d3da9f8c6085e9719048aec38e265e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10360-7b387c5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10360-7b387c5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30604ab901d23196820cba121fb75b5af37c95d8 available at: https://gist.github.com/137c9adce21b0bc91cb5439156902258<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10360-30604ab.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10360-30604ab.dmg

**Comment by anshuman64** [comment]
Works really well now. Good job @ctrlaltdavid!

**Pull request merged**
