### PR TITLE
Fixed EntityTreeSendThread crash after an entity has been deleted

### PR DESCRIPTION
**Pull request by orenh1**
EntityTreeSendThread sometimes Asserts, causing the assignment-client to terminate (well, in Debug mode; but the bug happens in Release mode as well; it's just harder to see).

EntityTreeSendThread stores weak_ptr's to entities. Sometimes it tries to remove an entity from its internal data structures after the weak_ptr has expired. This causes an assertion: not immediately, but very soon. I don't know what causes entities to become expired: presumably because an entity already in the queue has been deleted? Anyway, when that happens, the previous code had a bug:

1. _sendQueue.pop() removed the entity from _sendQueue successfully
2. _entitiesInQueue.erase(entity.get()) did NOT remove the entity from _entitiesInQueue, because entity.get() is null
3. As a result, assert(_entitiesInQueue.empty()) fired

I was able to reproduce this bug by repeatedly creating entities and then deleting them. The bug often occurred after less than a minute of doing this.

I have included two log messages that help show what happens. They're commented-out, but should be uncommented when testing this.

Side note: I believe that there may be another bug lurking in this class. When I had the log messages enabled, occasionally I saw a case of mismatched Push and Pop statements: e.g., 4 Push but only 3 Pop. I suspect that when this happens, an entity update isn't sent to some client that is expecting it. I did not pursue this lead since it doesn't cause a crash...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8861/app_12916_PR_d80ec31bc952670e9add2d21cd20cee8fbbcd674.apk

**Comment by Atlante45** [comment]
@orenh1 this conflicts with incoming that overhaul this module to add support for multi-frustum traversals. We'll add a fix for this in those changes.

I'm curious about those mismatched push/pop you've seen. Can you be more specific where you saw those mismatches?
One feature of those traversals is that are time constrained and can be broken up between different frames. And the send queue might not wend everything right away since it's rate and bandwidth constrained.

**Comment by orenh1** [comment]
When I saw mismatched push/pop, the mismatch did indeed disappear after a while. E.g., I saw 4 push and 3 pop; then I made some more changes in-world; and then the "missing" pop occurred, followed by new push/pop's for my new changes. But the missing pop only happened after I made additional changes: it didn't happen automatically.

**Comment by Atlante45** [comment]
Interesting, that definitely doesn't sound right. I'll give it a look.

**Pull request closed without merging**
