### PR TITLE
RC62: Fix 'Browse Avatars' button from Avatar Settings

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS11361](https://highfidelity.manuscript.com/f/cases/11361/Unable-to-switch-avatar-from-marketplace-on-stable-and-on-dev-builds).

Duplicate of https://github.com/highfidelity/hifi/pull/12165 but for RC62

## Test Plan
Perform the steps below in Desktop mode, and then in HMD mode.
1. Go to Settings -> Avatar
2. Click "Browse Avatars"
3. Choose a new avatar to use, then verify that your avatar has changed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6267/app_12167_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6267/HighFidelity-Beta-PR12167-e627925bd3fa4f42e0fc3cc2908ef1ed6eb7af8d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6267/HighFidelity-Beta-PR12167-e627925bd3fa4f42e0fc3cc2908ef1ed6eb7af8d.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result (Desktop) | Result (HMD)
--- | --- | ---
Go to Settings -> Avatar | 👍 | 👍 
Click "Browse Avatars" | 👍 | 👍 
Choose a new avatar to use, then verify that your avatar has changed. | 👍 | 👍 

Solid pass, works good.

**Pull request merged**
