### PR TITLE
DEV-2309: Report ESS stats to domain server

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Jira: https://highfidelity.atlassian.net/browse/DEV-2309

The ESS doesn't have its own NodeData-derived class for client-specific data. I've included some generic client stats such as bits-per-second, reliable-packets-per-second, etc., and some overall octree stats such as number of tree nodes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21714/HighFidelity-Beta-PR16295-6a4406a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21714/HighFidelity-Quest-Beta-PR16295-6a4406a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21714/HighFidelity-Beta-PR16295-6a4406a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21714/HighFidelity-Beta-Interface-PR16295-6a4406a.dmg

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21722/HighFidelity-Beta-PR16295-6a4406a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21722/HighFidelity-Quest-Beta-PR16295-6a4406a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21722/HighFidelity-Beta-PR16295-6a4406a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21722/HighFidelity-Beta-Interface-PR16295-6a4406a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21722/HighFidelity-Beta-PR16295-6a4406a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21722/HighFidelity-Beta-Interface-PR16295-6a4406a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21746/HighFidelity-Beta-PR16295-67d80cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21746/HighFidelity-Beta-Interface-PR16295-67d80cd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21746/HighFidelity-Beta-PR16295-67d80cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21746/HighFidelity-Quest-Beta-PR16295-67d80cd.apk)

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21748/HighFidelity-Beta-PR16295-67d80cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21748/HighFidelity-Quest-Beta-PR16295-67d80cd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21748/HighFidelity-Beta-PR16295-67d80cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21748/HighFidelity-Beta-Interface-PR16295-67d80cd.dmg

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21753/HighFidelity-Beta-PR16295-67d80cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21753/HighFidelity-Beta-Interface-PR16295-67d80cd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21753/HighFidelity-Beta-PR16295-67d80cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21753/HighFidelity-Quest-Beta-PR16295-67d80cd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21753/HighFidelity-Beta-PR16295-67d80cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21753/HighFidelity-Beta-Interface-PR16295-67d80cd.exe

**Comment by howard-stearns** [comment]
build this please

**Comment by howard-stearns** [comment]
oops, didn't see that it was already merged. coolio

**Pull request merged**
