### PR TITLE
clean up children of deleted avatar-entity

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that would leave children of deleted avatar-entities in limbo

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/3446/Entities-deleteEntity-on-an-entity-that-is-a-parent-of-other-entities-should-delete-the-children-entities-too

**Comment by sethalves** [comment]
to test:
- run this script:
```javascript
/* global Entities, MyAvatar, Vec3, Script */

(function() {

    function go() {
        var pos = Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, {x: 0, y: -0.5, z: -2}));
        var lifetime = -1;
        var isAvatarEntity = true;


        var aID = Entities.addEntity({
            name: "test entity parent",
            type: "Box",
            color: { blue: 255, green: 0, red: 0 },
            dimensions: { x: 0.5, y: 0.5, z: 0.5 },
            position: Vec3.sum(pos, { x: 0, y: 0.5, z:0 }),
            dynamic: true,
            collisionless: false,
            gravity: { x: 0, y: 0, z: 0 },
            lifetime: lifetime
        }, true);


        var FLARE_TEXTURE =
            "http://mpassets.highfidelity.com/df227a80-069b-4d01-9aec-d016fbc1fbe3-v1/textures/flaresparks.png";
        var bID = Entities.addEntity({
            name: "FLARE_SPARKS",
            position: Vec3.sum(pos, { x: 0, y: 0.8, z:0 }),
            lifetime: lifetime,
            type: "ParticleEffect",
            color: {
                red: 255,
                green: 255,
                blue: 255
            },
            isEmitting: 1,
            maxParticles: 50,
            lifespan: 2,
            emitRate: 20,
            emitSpeed: 0,
            speedSpread: 4,
            emitOrientation: {
                x: -0.7071220278739929,
                y: -0.000015258869098033756,
                z: -0.000015258869098033756,
                w: 0.7070915699005127
            },
            emitDimensions: {
                x: 0,
                y: 0,
                z: 0
            },
            polarStart: 0,
            polarFinish: 3,
            azimuthStart: -3.1415927410125732,
            azimuthFinish: 3.1415927410125732,
            emitAcceleration: {
                x: 0,
                y: -2,
                z: 0
            },
            accelerationSpread: {
                x: 1,
                y: 1,
                z: 1
            },
            particleRadius: 0.12999999523162842,
            radiusSpread: 1,
            radiusStart: 0,
            radiusFinish: 0,
            colorSpread: {
                red: 0,
                green: 0,
                blue: 0
            },
            colorStart: {
                red: 255,
                green: 255,
                blue: 255
            },
            colorFinish: {
                red: 255,
                green: 255,
                blue: 255
            },
            alpha: 1,
            alphaSpread: 0,
            alphaStart: 1,
            alphaFinish: 0,
            emitterShouldTrail: 1,
            textures: FLARE_TEXTURE,
            parentID: aID
        }, false);

        print("parent is " + aID + ", child is " + bID);


        Script.setTimeout(function() {
            Entities.deleteEntity(aID);
        }, 3000);
    }

    function cleanup() {
    }

    go();
}());
```
- it will create an avatar-entity box and a particle system which is a child of the box
- after 3 seconds it will delete the box
- make sure that the particle system doesn't leave leftover spots on the screen
- make sure someone watching you sees the same

**Comment by YuppyPlays** [comment]
Myself & Cain can test this when build is up.

**Comment by CainFoool** [comment]
^ Confirmed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e4e2cc1b4810247bb26c36d2d393a64d249d8f7 available at: https://gist.github.com/22748f359bb4993b31aab2369fe0641f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10478-1e4e2cc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10478-1e4e2cc.dmg

**Comment by YuppyPlays** [comment]
We're testing now.

**Comment by CainFoool** [comment]
**PASSED: Box appeared, particles appeared and deleted soon afterwards. Nothing left over.**

**Comment by YuppyPlays** [comment]
**Pass** Boxes appeared as Cain spawned them in using the code, then shortly afterwards all deleted by itself, no particles / "Spots" leftover.

**Pull request merged**
