### PR TITLE
fix hudOverlayPointer logic

### PR DESCRIPTION
**Pull request by druiz17**
This PR fixes a logic error in the hudOverlayPointer module that caused the module run when it was not suppose to.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in HMD mode
- have no hud elements on the screen
- rapidly click the triggers, you should not see the laser intersect an invisible wall (hud) right in front of you

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3863/HighFidelity-Beta-PR11516-6b3d89d18f23dc2b02b0099c5f3acf9c6d8e5355.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3863/HighFidelity-Beta-PR11516-6b3d89d18f23dc2b02b0099c5f3acf9c6d8e5355.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
be in HMD mode | Pass
have no hud elements on the screen | Pass
rapidly click the triggers, you should not see the laser intersect an invisible wall (hud) right in front of you | Pass

All good to me!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
