### PR TITLE
use a unique_ptr for linkedData in Node

### PR DESCRIPTION
**Pull request by birarda**
Raw pointers are bad.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271387f96e0a1947cf62f19603cfae4312067747 available at: https://gist.github.com/accdc70b2c7751bdc3d6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271387f96e0a1947cf62f19603cfae4312067747 available at: https://gist.github.com/accdc70b2c7751bdc3d6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271387f96e0a1947cf62f19603cfae4312067747 available at: https://gist.github.com/accdc70b2c7751bdc3d6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b34934b849694f4891f4f8394539723833c6c162 available at: https://gist.github.com/accdc70b2c7751bdc3d6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6430.dmg

**Pull request merged**
