### PR TITLE
include release message to controller modules

### PR DESCRIPTION
**Pull request by druiz17**
include release message to controller modules

Addresses this issue - https://highfidelity.fogbugz.com/f/cases/8243/grab-script-no-longer-anounces-release-to-Hifi-Object-Manipulation-channel

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4016/HighFidelity-Beta-PR11562-e77ac9fd104d16ba9bb6c4203d8f72e261a00a43.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4018/HighFidelity-Beta-PR11562-e77ac9fd104d16ba9bb6c4203d8f72e261a00a43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4018/HighFidelity-Beta-PR11562-e77ac9fd104d16ba9bb6c4203d8f72e261a00a43.exe

**Comment by druiz17** [comment]
Test plan
- have some grabbable objects near you
- run this script https://gist.github.com/druiz17/08f7ed50788b54a45bff15bc75426d5a to rez a box with a light on it
- when you grab and release a grabbable  object the light should turn green and red.

**Comment by druiz17** [comment]
test this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4043/HighFidelity-Beta-PR11562-e77ac9fd104d16ba9bb6c4203d8f72e261a00a43.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4045/HighFidelity-Beta-PR11562-67944c40a1a9a1044048be32bcb8270776e4b5b5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4045/HighFidelity-Beta-PR11562-67944c40a1a9a1044048be32bcb8270776e4b5b5.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

have some grabbable objects near you **Check**
run this script https://gist.github.com/druiz17/08f7ed50788b54a45bff15bc75426d5a to rez a box with a light on it **Check**
when you grab and release a grabbable object the light should turn green and red. **Check**

**Pass**
**Notes: Only works with near-grab, but I assume this is the intention.**

**Pull request merged**
