### PR TITLE
case 18450: Do not show login dialog if requested not to on the command line.

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
https://highfidelity.fogbugz.com/f/cases/18450/Auto-Tester-Test-accounts-are-being-signed-out-of-the-localhost-between-test-runs

An option has been added to the command line parameters.
If `--no-login-suggestion` appears on the command line then "Sign Into High Fidelity" pop up will not appear.
This is required for automatic testing
# Testing
1.  Run interface, logout and close interface.
2.  Run interface from the command line with the `--no-login-suggestion` option and wait 30".
     Ensure that the Login window does not appear.
3.  Logout and quit interface
4.  Run interface from the command line without any options and verify that the Login window appears after about 3".
5.  Check the box "Keep me logged in", login to interface and quit.
6.  Run interface from the command line without any options and verify that:
   a.  you are still logged in
   b.  no Login window appears.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14148/HighFidelity-Beta-PR14237-12d0926.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14148/HighFidelity-Beta-Interface-PR14237-12d0926.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14148/HighFidelity-Beta-PR14237-12d0926.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14148/HighFidelity-Beta-Interface-PR14237-12d0926.dmg

**Comment by NissimHadar** [comment]
Now there is - https://highfidelity.fogbugz.com/f/cases/19429/Do-not-show-login-dialog-if-requested-not-to-on-the-command-line

This may be be postponed if required, but it fixes an issue that can cause auto-tester to fail (and is also a security risk).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14244/HighFidelity-Beta-PR14237-c9f9679.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14244/HighFidelity-Beta-PR14237-c9f9679.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14244/HighFidelity-Beta-Interface-PR14237-c9f9679.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14244/HighFidelity-Beta-PR14237-c9f9679.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14244/HighFidelity-Beta-Interface-PR14237-c9f9679.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14715/HighFidelity-Beta-PR14237-c9f9679.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14715/HighFidelity-Beta-PR14237-c9f9679.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14715/HighFidelity-Beta-Interface-PR14237-c9f9679.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14715/HighFidelity-Beta-PR14237-c9f9679.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14715/HighFidelity-Beta-Interface-PR14237-c9f9679.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Step 6 fails, when opening interface without any options and previously logged in, interface will open logged out and log in prompt will appear.

[Logs.zip](https://github.com/highfidelity/hifi/files/2550864/Logs.zip)

**Comment by NissimHadar** [comment]
The "Keep me logged in" checkbox has to be checked to remember the previous state.
I have added this to step 5.

**Comment by qaAdamSmith82** [comment]
Pass @conklin94122 

Command to disable login works as intended
Normal login path is unaffected and works as intended

**Pull request merged**
