### PR TITLE
ModelEntityItem: Fix for missing pre-rotations for animated models.

### PR DESCRIPTION
**Pull request by hyperlogic**
This should fix the issue with the Kaya and Claire models, while also not breaking the windmill model in demo.

To test: Add this model to the scene.

    https://hifi-public.s3.amazonaws.com/cozza13/apartment/kaya/Kaya.fbx

And apply this animation:

    https://hifi-public.s3.amazonaws.com/cozza13/apartment/kaya/Kaya%40t-pose_46.fbx

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f71a5fda548e3a7e2f424b2fd08abb2be4476af available at: https://gist.github.com/7afc54efd2459ea6853e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6751.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6751.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f71a5fda548e3a7e2f424b2fd08abb2be4476af available at: https://gist.github.com/7afc54efd2459ea6853e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6751.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6751.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f71a5fda548e3a7e2f424b2fd08abb2be4476af available at: https://gist.github.com/7afc54efd2459ea6853e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6751.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6751.dmg

**Pull request merged**
