### PR TITLE
Fix duplicating multiple entities causing infinite looping (RC71 fix)

### PR DESCRIPTION
**Pull request by huffman**
Fixes https://highfidelity.manuscript.com/f/cases/17421/Cloning-multiple-entities-results-in-massive-entity-creation

### CODE REVIEW

**Comment by huffman** [comment]
# Test notes

  1. Go to the serverless tutorial ([hifi:///~/serverless/tutorial.json](url))
  1. Go into Create mode
  1. Create a cube and select it
  1. Alt-drag the cube to duplicate it
  1. Shift-click the original cube to select both cubes
  1. Alt-drag the cubes to duplicate them
  1. You should now have 4 cubes, with no noticeable issues. Previously interface would slow down considerably while continuously creating duplicate cubes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11907/HighFidelity-Beta-PR13769-c72c9a5.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11907/HighFidelity-Beta-PR13769-c72c9a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11907/HighFidelity-Beta-Interface-PR13769-c72c9a5.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Cloning multiple boxes at once no longer results in devastation.

**Pull request merged**
