### PR TITLE
Fix snapshot settings issue in HMD

### PR DESCRIPTION
**Pull request by danteruiz**
This PR fix the issue described in this PR - https://highfidelity.manuscript.com/f/cases/18429/In-VR-mode-cannot-save-changes-or-cancel-after-going-to-Settings-from-the-Snap-app

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13015/HighFidelity-Beta-PR14003-ff52639.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13015/HighFidelity-Beta-Interface-PR14003-ff52639.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13015/HighFidelity-Beta-PR14003-ff52639.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13015/HighFidelity-Beta-Interface-PR14003-ff52639.exe

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
