### PR TITLE
Fix for auto-reopening of closed query dialogs (aka hack-on-top-of-hack)

### PR DESCRIPTION
**Pull request by ElderOrb**
Test plan: 

1) Switch to desktop
2) Enable advanced settings and go to Edit
3) Go to Import Entities from URL and paste this in the pop up dialogue box http://mpassets.highfidelity.com/9e0267fa-69c8-455a-ad81-fc0f82cab599-v1/guitar.json
4) Press ok to apply url and close the dialog
5) Create should open and the json should load 
6) Move your avatar around, ensure dialog from item 3 doesn't self-reopen

https://highfidelity.manuscript.com/f/cases/13962/Import-Entity-URL-Dialogue-Box-Will-not-Disappear

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8549/app_12807_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8553/app_12807_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8553/HighFidelity-Beta-PR12807-995d678d2037a52b31196582b998ba3317bbb31a.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
The import entities popup dialog dismissed upon upload and did not ever reopen or become stuck open.

**Pull request merged**
