### PR TITLE
cleanup Actions and Constraints part-1

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* remove `ObjectActionSpring` which was replaced by `ObjectActionTractor` in a previous PR
* remove unused API from `ObjectDynamic` base class
* replace `"spring"` with `"tractor"` in JS examples

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
The "spring" Action wasn't springy at all.  It was, effectively, a critically damped spring with zero history: it would slam the velocity of an object to always approach its target position no matter what else happened.  Hence we've changed the name to be "Tractor" to reflect that it is acting more as a "tractor beam" that magically enforces a target position.

In the short term "spring" action type will still work in JS scripts but it will create a "tractor" instead. Eventually we'll add a proper spring that is springy.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d705f529a096edb1840c041e410a57c900028731 available at: https://gist.github.com/6530fa9010c32d575ac2ab57543827dc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-d705f52.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-d705f52.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d705f529a096edb1840c041e410a57c900028731 available at: https://gist.github.com/6530fa9010c32d575ac2ab57543827dc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-d705f52.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-d705f52.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9c703b14728b3043a3d9f0efc7e0e0e674f0f42 available at: https://gist.github.com/6530fa9010c32d575ac2ab57543827dc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-e9c703b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10468-e9c703b.dmg

**Comment by AndrewMeadows** [comment]
### Test Plan:
```// create an object, put an "tractor" action on it

// some general constants
var ORIGIN = { x: 0.0, y: 0.0, z: 0.0 };
var IDENTITY_ROTATION = { x: 0.0, y: 0.0, z: 0.0, w: 1.0 };

// compute a position to create the object relative to avatar
var forwardOffset = Vec3.multiply(2.0, Quat.getFront(MyAvatar.orientation));
var objectPosition = Vec3.sum(MyAvatar.position, forwardOffset);

// the properties of the object
var BOX_WIDTH = 1.0; // meters
var BOX_HEIGHT = 0.5; // meters
var BOX_DEPTH = 1.5; // meters
var LIFETIME = 300; // seconds
var properties = {
    type: "Box",
    name: "test-box",
    dimensions: {x: BOX_WIDTH, y: BOX_HEIGHT, z: BOX_DEPTH},
    position: objectPosition,
    lifefime: LIFETIME, // just in case this script crashes before it can cleanup the object
    dynamic: true,
    damping: 0.01,
    angularDamping: 0.01
};

// create the object
var entityId = Entities.addEntity(properties);

// the properties of the action
var LINEAR_TIMESCALE = 2.0;
var ANGULAR_TIMESCALE = 2.0;
var actionProperties = {
        targetPosition: ORIGIN,
        targetRotation: IDENTITY_ROTATION,
        linearTimeScale: LINEAR_TIMESCALE,
        angularTimeScale: ANGULAR_TIMESCALE
    };

// create the action
var actionId = Entities.addAction("tractor", entityId, actionProperties);


// delete the object when this script is stopped
deleteEntity = function() {
    Entities.deleteEntity(entityId);
}
Script.scriptEnding.connect(deleteEntity);
```

(1) Run the script above to create a box with a `"tractor"` action on it.  The tractor action will slam the velocities of the object to always move toward some target position/rotation with an exponential decay.

(2) Once the box is created use the "create" UI to set its position about two or three meters away --> the tractor action will move it back

(3) Use the "create" UI to rotate the box --> the tractor will rotate it back

(4) Change the script to use a `"spring"` action type rather than `"tractor" `--> you should get the same behavior as the `"tractor"` (because `"spring"` now maps to `"tractor"` which is replacing it).

(5) Run scripts/developer/tests/dynamics/dynamicsTests.js

(6) Click each button in turn, interact with the results.

(7) For each created thing, export it and then import it.

(8) Make sure near and far grab are still working as expected.

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
@sethalves  PASS but see notes re script/html error in dynamicTests.

(1) Run the script above to create a box with a "tractor" action on it. The tractor action will slam the velocities of the object to always move toward some target position/rotation with an exponential decay. **DONE**

(2) Once the box is created use the "create" UI to set its position about two or three meters away --> the tractor action will move it back **PASS**

(3) Use the "create" UI to rotate the box --> the tractor will rotate it back **PASS**

(4) Change the script to use a "spring" action type rather than "tractor"--> you should get the same behavior as the "tractor" (because "spring" now maps to "tractor" which is replacing it). **PASS PASS**

(5) Run scripts/developer/tests/dynamics/dynamicsTests.js Done.

(6) Click each button in turn, interact with the results. **DONE**

(7) For each created thing, export it and then import it. **SUCCESS all types**

(8) Make sure near and far grab are still working as expected. **SUCCESS**

***Had to debug and hack dynamicTests.js script to get it to work.  Line 708 is expecting "cone-twist-and-tractor-lever-test" and the message being sent to the script is "cone-twist-and-spring-lever-test"***

Changes needed to dynamicTests.html on lines 12 and 13 are below

"button" id="cone-twist-and-tractor-lever-test" value="Cone-Twist and Tractor-Action Lever"

A platform with a lever.  The lever can be moved in a cone and rotated.  A tractor brings it back to its neutral position.

**Pull request merged**
