### PR TITLE
Fix Reverb Zone settings to work correctly with new reverb

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c6ca984782348f4c5a5f9cacbe3cf2d53cf4ca69 available at: https://gist.github.com/41efb760e99bab401702<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7459.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7459.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 063891d65eff3615d923b2fe31dd814589e0b90e available at: https://gist.github.com/41efb760e99bab401702<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7459.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7459.dmg

**Comment by kencooke** [comment]
To test, set up a Reverb Zone on your local domain, and those settings should be reflected in Interface when you enter that zone.

**Comment by cozza13** [comment]
I could not get this to work. Do it with domain zones. 

capture


It does work for me if I do a entity script to change audio. 

QA fail until I know what I need to do

**Comment by cozza13** [comment]
My 'y' coordinates where not set correctly. I set those back up and it is good to go.

**Pull request merged**
