### PR TITLE
Moved the context menu to the tablet

### PR DESCRIPTION
**Pull request by druiz17**
Moved the context menu to the tablet and removed any unused code and files

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2fc76d64fd6becb75bcecb1bf35f8ae71c770524 available at: https://gist.github.com/c4c761482e5b641aafd26074c65722d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.dmg

**Comment by hyperlogic** [comment]
Ubuntu build failed, because of some weird npm error:

    There was an error writing the packaged console: ENOENT: no such file or directory, rename '/tmp/electron-packager/linux-x64/server-console-linux-x64/electron' -> '/tmp/electron-packager/linux-x64/server-console-linux-x64/server-console'

Let's try again.  Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2fc76d64fd6becb75bcecb1bf35f8ae71c770524 available at: https://gist.github.com/c4c761482e5b641aafd26074c65722d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.dmg

**Comment by hyperlogic** [comment]
*sigh* test this please.  OSX build failed downloading glm

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2fc76d64fd6becb75bcecb1bf35f8ae71c770524 available at: https://gist.github.com/c4c761482e5b641aafd26074c65722d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9343-2fc76d6.dmg

**Pull request merged**
