### PR TITLE
QA READY: fix solid sphere overlays not rendering

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Attached script creates 4 overlays:
- wireframe sphere
- wireframe cube
- solid (partly transparent) sphere
- solid (partly transparent) cube

Latest build displays only three of these (solid sphere doesn't display).
PR build displays all four.

[sphere3DOverlayBug.zip](https://github.com/highfidelity/hifi/files/353080/sphere3DOverlayBug.zip)

**Comment by SamGondelman** [comment]
Overlaps https://github.com/highfidelity/hifi/pull/8206

**Comment by ctrlaltdavid** [comment]
Exact same fix, groan.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a4ce5c05ece9600a8da8745b029f605618e2df66 available at: https://gist.github.com/987c8a25b7faee40776526c81f5ae399<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8207.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8207.dmg

**Pull request closed without merging**
