### PR TITLE
Clean up interfaces for JS Scene/Render

### PR DESCRIPTION
**Pull request by zzmp**
- Use context-dependent titles for properties
- Nest properties in conventional JS style
- Add back deferred debugging to Render interface

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1cdee44214db7ce8eca338044125a5b44dc732e8 available at: https://gist.github.com/a936c786f8eea35ea1e0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6715.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6715.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1cdee44214db7ce8eca338044125a5b44dc732e8 available at: https://gist.github.com/b105e9964f944219eed3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6715.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6715.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f146b207c40ddbb0b34fe7f92055510856615a34 available at: https://gist.github.com/a936c786f8eea35ea1e0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6715.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6715.dmg

**Comment by zzmp** [comment]
Although examples/utilities/tools/renderEngineDebug.js works, it doesn't properly position the item sliders (opaque, transparent, overlay3D) when *any* of them are collapsed.

**Comment by samcake** [comment]
@zzmp Yep this is a knwon bug

**Comment by samcake** [comment]
Did a simple testing on Demo with the new renderEngineDebug.js of the pr with success
Good to go

**Pull request merged**
