### PR TITLE
fix cylinder collision shape

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
**Test plan:**

**(1)** In a recent dev-download build...

**(2)** Make a cylinder that is a long pole (e.g. `dimensions = { x: 1, y: 10, z: 1 }`).

**(3)** Rotate it 90 degrees about the **X** or **Z** axis (so it is a horizontal bar) and lower it to a height in which your avatar can collide with it.

**(4)** Bump your avatar into the cylinder to see how it collides.  It will actually colliding as a sphere with a radius equal to half largest dimension component (so radius of 5 for the suggested dimensions in (2)).

**(5)** Repeat steps **(2)** through **(4)** using this PR: the cylinder should collide as it appears.

**(6)** Make a cylinder with unequal **X** and **Z** components (e.g. `dimensions = { x: 3, y: 7, z: 5 }`) and make sure it collides approximately as it appears.  (In this case it will use a convex hull collision shape with a maximum of 42 surface points, which should provide a decent collision approximation).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4949/HighFidelity-Beta-PR11814-d538a9aaa8debb76476f234aa221f8dca21d40b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4949/HighFidelity-Beta-PR11814-d538a9aaa8debb76476f234aa221f8dca21d40b1.exe

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

(1) In a recent dev-download build... **Check, Build 7435 Dev-download**
(2) Make a cylinder that is a long pole (e.g. dimensions = { x: 1, y: 10, z: 1 }). **Check**
(3) Rotate it 90 degrees about the X or Z axis (so it is a horizontal bar) and lower it to a height in which your avatar can collide with it. **Check**
(4) Bump your avatar into the cylinder to see how it collides. It will actually colliding as a sphere with a radius equal to half largest dimension component (so radius of 5 for the suggested dimensions in (2)). **Check**
(5) Repeat steps (2) through (4) using this PR: the cylinder should collide as it appears. **Check**
(6) Make a cylinder with unequal X and Z components (e.g. dimensions = { x: 3, y: 7, z: 5 }) and make sure it collides approximately as it appears. (In this case it will use a convex hull collision shape with a maximum of 42 surface points, which should provide a decent collision approximation). **Check**

Solid **Pass** - I'm glad to see this fixed after discovering this bug with Cain earlier this morning, nice one Andrew! :D

**Pull request merged**
