### PR TITLE
Case 21274, Case 21267, Case 21290: Working on overlay bugs (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21274/Teleport-Teleport-frame-remains-active-after-teleporting-and-projects-onto-the-avatar-when-in-HMD
https://highfidelity.manuscript.com/f/cases/21267/Users-cannot-click-PAL-spheres
https://highfidelity.manuscript.com/f/cases/21290/Can-t-click-context-overlay-if-there-s-an-entity-behind-it

https://github.com/highfidelity/hifi/pull/14947

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17378/HighFidelity-Beta-PR14948-e41ee29.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17380/HighFidelity-Beta-PR14948-adc0e1a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17380/HighFidelity-Beta-PR14948-adc0e1a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17380/HighFidelity-Beta-Interface-PR14948-adc0e1a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17380/HighFidelity-Beta-PR14948-adc0e1a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17380/HighFidelity-Beta-Interface-PR14948-adc0e1a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17382/HighFidelity-Beta-PR14948-80ef300.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17382/HighFidelity-Beta-PR14948-80ef300.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17382/HighFidelity-Beta-Interface-PR14948-80ef300.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17382/HighFidelity-Beta-PR14948-80ef300.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17382/HighFidelity-Beta-Interface-PR14948-80ef300.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
PreMerge Pass

**Pull request merged**
