### PR TITLE
Recording fixes from Clement.

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80a0fc5344d358ee59dc7f5ec9d7f0531cc8b95b available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07b3597ae363f79202a5f59cbf3de353f29c648b available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2302d8ec5c0b9e8d5b77d7cc5f91d558698cee42 available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Comment by Atlante45** [comment]
Jesus christ, MSVC, you're not even making any efforts!!!
```
(ClCompile target) -> 
         ..\..\..\libraries\audio-client\src\AudioClient.cpp(805): error C2057: expected constant expression [D:\jenkins\workspace\pull-request-win\build\libraries\audio-client\audio-client.vcxproj]
         ..\..\..\libraries\audio-client\src\AudioClient.cpp(805): error C2466: cannot allocate an array of constant size 0 [D:\jenkins\workspace\pull-request-win\build\libraries\audio-client\audio-client.vcxproj]
         ..\..\..\libraries\audio-client\src\AudioClient.cpp(805): error C2133: 'inputAudioSamples' : unknown size [D:\jenkins\workspace\pull-request-win\build\libraries\audio-client\audio-client.vcxproj]
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: ffafd3194e7eb5451ac34e3b65dc03fcce029a1b available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c35ae48b09bd270598ac9d1713c398f74d75705 available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dbe25651cf3b8a67ad300e8a52799e8ee82c6153 available at: https://gist.github.com/b313c63ccdfc2904dbc5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6322.dmg

**Pull request merged**
