### PR TITLE
Fixed Blocks downloads (now Google Poly)

### PR DESCRIPTION
**Pull request by elisa-lj11**
The problem: 
Since Google made Blocks a part of Poly, the URL references for download filters had to be updated.

Test plan:
1. Get the Blocks app from marketplace
2. Open Blocks
3. Select a model and click download, then select "OBJ File" and select "Download" from the pop-up
4. The model should appear in front of you

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4786/HighFidelity-Beta-PR11778-45b9a150dca0954fccb817a6c3f0582ae95c2dc5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4786/HighFidelity-Beta-PR11778-45b9a150dca0954fccb817a6c3f0582ae95c2dc5.exe

**Comment by Nex-Pro** [comment]
Testing Win10

**Comment by Nex-Pro** [comment]
Was able to download OBJs
Noticed a couple of issues.

If an obj is repeatedly downloaded the asset appears in the list each time with an increment number ( after the first one ) 

See image.

wm1848-hifi-snap-by--on-2017-11-09_01-11-37

OBJs with textures appear grey.

yb1848-hifi-snap-by--on-2017-11-09_00-55-51

Some objects are placed in world at completely wrong angles. See image below.

ge1848-hifi-snap-by--on-2017-11-09_01-00-26

Others arrive in world but are invisible.

zp1848-hifi-snap-by--on-2017-11-09_01-08-12

As I don't know what the full scope of this PR is I've added the feedback above. I hope it is helpful.

**Comment by Nex-Pro** [comment]
@elisa-lj11 ^ Those issues are probably outside the scope but I feel they are important.

**Comment by elisa-lj11** [comment]
@Nex-Pro thank you for this feedback. I have a bug filed for these problems and will work on them, but for now I will merge since some other projects depend on downloading from Blocks.

**Pull request merged**
