### PR TITLE
v0.76-RC - fixing keyboard mallets dimensions 

### PR DESCRIPTION
**Pull request by danteruiz**
In this PR #14409 I forgot to properly set the correct dimensions for the keyboard mallets, in this PR I property set the mallets dimensions

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14445

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15301/HighFidelity-Beta-PR14447-4423ded.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15301/HighFidelity-Beta-PR14447-4423ded.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15301/HighFidelity-Beta-Interface-PR14447-4423ded.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15307/HighFidelity-Beta-PR14447-4423ded.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15307/HighFidelity-Beta-PR14447-4423ded.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15307/HighFidelity-Beta-Interface-PR14447-4423ded.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15307/HighFidelity-Beta-PR14447-4423ded.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15307/HighFidelity-Beta-Interface-PR14447-4423ded.exe

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
