### PR TITLE
hide progress overlays if interstitial mode

### PR DESCRIPTION
**Pull request by wayne-chen**
- Hides "LOADING CONTENT" bar in HMD/desktop mode if interstitial mode is enabled
- Fixes MS#[19357](https://highfidelity.manuscript.com/f/cases/19357/Loading-Content-Should-not-be-Visible)

## TEST PLAN
- Launch interface
- Navigate between domains
- When looking around in HMD/desktop mode in the interstitial page, you should not see the "LOADING CONTENT" message (similar to the image below)
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14048/HighFidelity-Beta-PR14225-fd3c0d2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14048/HighFidelity-Beta-PR14225-fd3c0d2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14048/HighFidelity-Beta-Interface-PR14225-fd3c0d2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14048/HighFidelity-Beta-PR14225-fd3c0d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14048/HighFidelity-Beta-Interface-PR14225-fd3c0d2.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14115/HighFidelity-Beta-Interface-PR14225-6cf9608.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14115/HighFidelity-Beta-PR14225-6cf9608.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14115/HighFidelity-Beta-Interface-PR14225-6cf9608.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14118/HighFidelity-Beta-PR14225-6cf9608.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14118/HighFidelity-Beta-PR14225-6cf9608.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14118/HighFidelity-Beta-Interface-PR14225-6cf9608.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14118/HighFidelity-Beta-PR14225-6cf9608.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14118/HighFidelity-Beta-Interface-PR14225-6cf9608.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
Stopped testing.  The protocol issues are skewing the results.  I need working domains for this test.  Will kick off a new build and see if that helps.

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14141/HighFidelity-Beta-PR14225-6cf9608.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14141/HighFidelity-Beta-Interface-PR14225-6cf9608.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14141/HighFidelity-Beta-PR14225-6cf9608.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14141/HighFidelity-Beta-Interface-PR14225-6cf9608.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
