### PR TITLE
Quit VRMode before aboutToQuit runs

### PR DESCRIPTION
**Pull request by Atlante45**
I think this got broken when we changed the close up routines.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3f807664118b34b0e0f499490c8b219b21eeadd available at: https://gist.github.com/de192365e70b22bae018<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4599.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4599.dmg

**Comment by ZappoMan** [comment]
What's the repro of the bug? Why/how does this fix whatever it is?

**Comment by jherico** [comment]
I suspect it's to do with the behavior of the HMD tools dialog.  Right now if you enter VR mode and exit the program, and then restart it, it starts up in VR mode, but the HMDTools dialog doesn't reflect that.  

However, on consideration, if we want to not start up in VR mode, why do we bother persisting the fact that we're in VR mode to the settings at all?  

Also, having the HMDTools dialog be responsible for causing us to exit VR mode seems fragile.  What if the HMDTools dialog has been closed?

**Comment by ZappoMan** [comment]
Ahh. I bet I know what the issue is. And I bet this doesn't fix it at all. I suspect that the real issue is that the aboutToQuit signal is getting fired in a random order and we hooked up the settings and/or menu cleanup code to that signal. And so now sometimes the HMDTools is getting its signal too late. 

I agree that there are other ways to clean this up. Like refactoring the VRMode and the HMDTools use of VRMode. 

VRMode probably doesn't need to be a menu item at all. It should just be a state in the app/HMD tools. 

The menu item getting persisted is the root problem.

**Comment by Atlante45** [comment]
AFAIK, slot are getting fired in the order they are registered.
@ZappoMan is right that the pb here is the the menu/window get persisted before we get out of VRMode.
I agree that this might not be the best way to go about it, but this does fix the issue since that way we get out of VRMode before the cleanup.

**Comment by jherico** [comment]
One problem I've run into with demoing for a couple of people is that right now it's possible for a novice to get stuck in VR mode (even if they restart).  If at the very least this resolves that problem, I think we should merge it.

**Comment by PhilipRosedale** [comment]
@jherico Did you test and does this resolve the problem?  If so, yes lets merge.

**Comment by jherico** [comment]
Testing this shows problems.  The change is only effective *if* the HMDTools dialog is open and *if* the dialog is properly synced with the state of the application.  If you don't have the HMDTools dialog open, then the code doesn't engage because the listener is there.  Additionally, if you start the application and it's in VR mode already the HMDTools dialog acts as if it's not (it displays 'Enter HMD Mode' rather than 'Leave HMD Mode', even though VR is already on from the previous run).

Since we can't rely on the HMDTools dialog being open at application shutdown, I don't think we should merge this as is.  Either we should simply ignore the persisted state of the VR Enabled flag, or we should work towards supporting launching in VR mode.  Or both, with one as a short term goal and the other long term.

**Comment by Atlante45** [comment]
I think I agree with both what you and Brad are saying, which would be, remove VRMode from the menu, that way it won't be persisted, because it doesn't really make sense any more to have it there anyway.

That won't solve the issue entirely though, because the app will still be saved to be fullscreen and on the oculus desktop (I think the later is do to OS X).

One solution would be to put all the handling of VRMode shenanigans in a dedicated class separate from the menu and the HDMTools that would always be called.

In the mean time, this PR, does create any issue and solves the pb in one particular case (HMDTools open, which personally is always the case if I'm in VRMode) so I think we should still merge it but knowing that fix the pb.
@jherico I'll let you make the call on this one.
I can create an asana task for me to work on later if you want to, this was just a quick fix I made while working on the offset stuff.

**Comment by jherico** [comment]
@Atlante45 I'm not saying that VRMode should be removed from the menu (not yet, anyway).  I'm just saying this approach doesn't always resolve the problem, and I think it ends up making it harder to refactor later on.  

Ultimately, I think the long term approach should be to have a number of 'display plugins'.  At launch the application should iterate over the plugins and query each of them to see if they're supported on the current platform.  We'd have one plugin for conventional display, one for 3DTV, and one or more for Oculus support (it may be easier to have multiple oculus plugins for things like supporting direct HMD mode vs extended mode, rather than trying to cover every possiblity in a single plugin using ifdefs and booleans), and probably another plugin for SteamVR and/or Vive.  

Rather than have an HMDTools dialog, we should just have an 'output plugin' selection UI (which may need to be a dialog, or may need to be represented inside the 3D UI).  

However, I'll go ahead and merge this, since it seems to be causing you development pain.  As you say, it shouldn't cause any new problems.

**Pull request merged**
