### PR TITLE
use normal script update frequency for handControllerPointer

### PR DESCRIPTION
**Pull request by howard-stearns**
Use normal Script.update (60hz) instead of a timer (@20hz).

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:

background: When we started, handControllerPointer was doing a lot of work all the time, and this was interfering with system performance. Now it's doing much less work, and only when the triggers are squeezed. Meanwhile, I think we're chasing our tails on feel and click-accuracy because we're not updating as fast as we're used to with the rest of the system. With that in mind:

Compare performance with current build, both with and without a hand-controller trigger partially squeezed. You shouldn't notice a difference. There should also be no difference in functionality when clicking and dragging HUD elements.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d650c50a5bc5754cfbdc7f0a7d3cd1df62e90428 available at: https://gist.github.com/f34ee35ed4d522257a5e34c0820a3eb7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8156.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8156.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NLZJLvOZ&#x2F;76-use-normal-script-update-60hz-in-handcontrollerpointer-instead-of-20hz"> Use normal script update (60Hz) in handControllerPointer instead of 20Hz.</a>

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d650c50a5bc5754cfbdc7f0a7d3cd1df62e90428 available at: https://gist.github.com/f34ee35ed4d522257a5e34c0820a3eb7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8156.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8156.dmg

**Comment by thoys** [comment]
# QA Test report

While in HMD/Vive: Cursor is only visible at start, while using the mouse. As soon as you move your head backwards the 2D cursor will get disconnected from the GUI and follow your head. I don't see any sign of a cursor with my hand controllers.

QA Fail

**Comment by thoys** [comment]
# QA Test revisit

After a discussion with @howard-stearns about the whereabouts of the cursor, it seemed that the cursor was expected to be invisible. All the window dragging behavior is still smooth, as well I am able to click the buttons.

QA Pass

**Comment by hyperlogic** [comment]
:+1: nice usage of higher order functions in setupHandler()

**Pull request merged**
