### PR TITLE
MS20366: Restarting interface and skipping login causes user to appear in serverless

### PR DESCRIPTION
**Pull request by wayne-chen**
MS#[20366](https://highfidelity.manuscript.com/f/cases/20366/Restarting-interface-and-skipping-login-causes-user-to-appear-in-serverless)

# TEST PLAN
- Launch Interface (with HMD attached)
- You should start in HMD mode
- Switch to desktop mode
- Dismiss login dialog
- You should be sent to serverless tutorial (check #1)
- Go to some domain in the `GOTO` app
- Relaunch interface
- You should launch in desktop mode (check #2)
- Dismiss login dialog
- You should be sent to your previously visited domain from the `GOTO` app in the last session (check #3)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16067/HighFidelity-Beta-PR14615-50d57e8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16067/HighFidelity-Beta-PR14615-50d57e8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16067/HighFidelity-Beta-Interface-PR14615-50d57e8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16067/HighFidelity-Beta-PR14615-50d57e8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16067/HighFidelity-Beta-Interface-PR14615-50d57e8.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
