### PR TITLE
get codecs to work with mac sandbox

### PR DESCRIPTION
**Pull request by ZappoMan**
This PR fixes the Mac Sandbox to properly support codecs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea38578c7d25a0a4146679cf1ff361a074b8ce6a available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-ea38578.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-ea38578.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d62a69be763c05074b8910e98a745ea5d777ded available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-1d62a69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-1d62a69.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 231f8cc8006573042a81fcc6981be0af3118f953 available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-231f8cc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-231f8cc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ab36dc05c565e9aa00591b6ec3f3a1b9b3bd9ff available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-7ab36dc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-7ab36dc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca45cd0308fc1b0733a364e9bb7b1ecb8114902c available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-ca45cd0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-ca45cd0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e7986a115a42ad8cfe681b9b0dcefc8eb0deeab available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-4e7986a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-4e7986a.dmg

**Comment by ZappoMan** [comment]
Damn you cmake!!!

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6ffabf5003228385b1543f13283aa44d5f7883a available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-b6ffabf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-b6ffabf.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3154c68769a54234b7f8ca26956a19d3bce124b8 available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-3154c68.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-3154c68.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7de1ff4c2342e81873abe56b8d39d5fce6ca9f19 available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-7de1ff4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-7de1ff4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99854f998e6229bd4e002e0b77b94a20d42dc286 available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-99854f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-99854f9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 897b837c522cca5402517d92794ccb700233a770 available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-897b837.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-897b837.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2fd055f0f12992cdd5d64cddf97a610d21badcb available at: https://gist.github.com/681dbf6c72ae9eccad2e139a4b99ae4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-c2fd055.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8234-c2fd055.dmg

**Comment by ZappoMan** [comment]
screen shot 2016-07-14 at 8 49 21 am

**Comment by Nex-Pro** [comment]
Ok after failing to locate the logs I had to grab the screen....

I think this is a **PASS**
@ZappoMan  ^

screen shot 2016-07-14 at 17 37 01

**Pull request merged**
