### PR TITLE
Don't sign a production Windows installer if there's no key file

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10571/HighFidelity-Beta-PR13369-929f6f3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10571/HighFidelity-Beta-PR13369-929f6f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10571/HighFidelity-Beta-Interface-PR13369-929f6f3.dmg

**Comment by conklin94122** [comment]
@SimonWalton-HiFi @birarda Test plan, please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11102/HighFidelity-Beta-PR13369-21b2187.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11102/HighFidelity-Beta-PR13369-21b2187.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11102/HighFidelity-Beta-Interface-PR13369-21b2187.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11102/HighFidelity-Beta-PR13369-21b2187.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11102/HighFidelity-Beta-Interface-PR13369-21b2187.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11798/HighFidelity-Beta-PR13369-dc5da4e.apk

**Comment by SimonWalton-HiFi** [comment]
I've updated the test plan to reflect the new variable.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11798/HighFidelity-Beta-PR13369-dc5da4e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11798/HighFidelity-Beta-Interface-PR13369-dc5da4e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11798/HighFidelity-Beta-PR13369-dc5da4e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11798/HighFidelity-Beta-Interface-PR13369-dc5da4e.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12145/HighFidelity-Beta-PR13369-dc5da4e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12145/HighFidelity-Beta-PR13369-dc5da4e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12145/HighFidelity-Beta-Interface-PR13369-dc5da4e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12145/HighFidelity-Beta-PR13369-dc5da4e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12145/HighFidelity-Beta-Interface-PR13369-dc5da4e.exe

**Comment by birarda** [comment]
Testing this now - requires a local dev environment with NSIS.

**Comment by conklin94122** [comment]
Thanks much @birarda

**Pull request merged**
