### PR TITLE
new wallet help

### PR DESCRIPTION
**Pull request by howard-stearns**
To match end of seeding, and other refinements.

### CODE REVIEW

**Comment by howard-stearns** [comment]
For internal testing only (by @changxc )

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7544/app_12505_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7548/app_12505_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7548/HighFidelity-Beta-PR12505-eb683d479367dfa9299d3a6e0f40ff516f0d8c29.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7548/HighFidelity-Beta-PR12505-eb683d479367dfa9299d3a6e0f40ff516f0d8c29.exe

**Comment by changxc** [comment]
1. should/could BankOfHighFidelity be a link that user can click and go to?
image

**Comment by changxc** [comment]
2. in this PR, i newly set up my wallet and still get the close beta msg. it should be the new open beta msg, with a button to go to  BankOfHighFidelity

image

**Comment by howard-stearns** [comment]
Re 1. Yes, I agree. I initially treated this entirely as a text change, since it is isn't scoped as a development project. The system doesn't just let you "add a link" like HTML, and instead, you have to program one. However, given that this won't get in tonight and thus there's a bit of time, I agree that we should go ahead and do this "one thing more".

Re 2. The scoped end-seeding project has this. Since that is not merged -- due to HMD problems that presumably have nothing to do with us, but we don't know that yet -- we don't want to have both the end-seeding and this change the same code. If the end-seeding result is not what you want, then fail that PR and we'll fix it there.

Additional: There are some ugly results. E.g., the last message is too long and looks ugly. The interaction with scrolling is bad. I don't know what we should do about that. Thoughts?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7556/app_12505_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7556/HighFidelity-Beta-PR12505-053640f2166f501bd0a84d2431274ecead31c249.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7556/HighFidelity-Beta-PR12505-053640f2166f501bd0a84d2431274ecead31c249.exe

**Comment by changxc** [comment]
I noticed that some of the messages a bit long...let me ask about scrolling to see if any new bug / improvement project is going on

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7571/app_12505_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7573/app_12505_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7573/HighFidelity-Beta-PR12505-e21d9f7950f3bf64618a77954c9e38251d4973b2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7573/HighFidelity-Beta-PR12505-e21d9f7950f3bf64618a77954c9e38251d4973b2.exe

**Comment by changxc** [comment]
Note - since this is purely a text swap with no additional functionality, I performed testing and QA approval.

**Comment by conklin94122** [comment]
Labeling as QA Approved, per Chang.

**Pull request merged**
