### PR TITLE
Fix vr 2d vr tablet crash

### PR DESCRIPTION
**Pull request by sethalves**
- fix crash bug triggered by switching between tablet and toolbar mode

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4141/VR-Tablet-Crash

**Comment by sethalves** [comment]
to test:
1. Load interface with reset settings so it starts in VR mode
2. Switch to Desktop mode
3. Use Toolbar to open edit dialog
4. Switch to VR mode with edit dialog open
5. Open the tablet if it is not open and hit the edit app. Notice that tablet is now blank.
7. (Physically) take off HMD

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b2caf808135496e1e875192d379efcb15c4afc8 available at: https://gist.github.com/7600f7d49295c337faf5c5cb29515697<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b2caf808135496e1e875192d379efcb15c4afc8 available at: https://gist.github.com/7600f7d49295c337faf5c5cb29515697<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b2caf808135496e1e875192d379efcb15c4afc8 available at: https://gist.github.com/7600f7d49295c337faf5c5cb29515697<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10350-6b2caf8.dmg

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
###  Pass.

Tried this several times with no issues.

**Pull request merged**
