### PR TITLE
21539: Added Use HMD in Desktop Mode to OpenVR

### PR DESCRIPTION
**Pull request by Menithal**
[WL 21539](https://worklist.net/21539)

- Added "Use HMD in Desktop Mode" under OpenVR Settings
- When turning off HMD in Desktop Mode, make sure to revert camera back to default.

# Test Plan
## Requires Vive

1. Stay in **Desktop Mode**
2. Visit Controller Settings
3. New checkbox (radial style) should be below "use Vive devices in Desktop mode", "Use HMD in Desktop Mode".
4. Turn on your controllers 
5. Turn on "Use Vive devices in Desktop Mode"
6. With Use HMD in Desktop Mode disabled: moving your HMD around will not move the camera around
7. Turning HMD in Desktop Mode on, your desktop view should move around when moving the HMD
8. Turning HMD in Desktop Mode off after moving in active, should revert the camera back to its original avatar position

Note: This will not effect controller positioning, and may still move your hands and your overall body about, as this is relative to your center of vr-space..

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4689/HighFidelity-Beta-PR11752-e28f80401f32760006489a1b021489343fee1bb4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4689/HighFidelity-Beta-PR11752-e28f80401f32760006489a1b021489343fee1bb4.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by MiladNazeri** [comment]
Test Rail case:
https://highfidelity.testrail.net/index.php?/cases/view/2933&group_by=cases:section_id&group_order=asc&group_id=574

**Comment by YuppyPlays** [comment]
Testing complete:

Stay in Desktop Mode **Check**
Visit Controller Settings **Check**
New checkbox (radial style) should be below "use Vive devices in Desktop mode", "Use HMD in Desktop Mode". **Check**
Turn on your controllers **Check**
Turn on "Use Vive devices in Desktop Mode" **Check**
With Use HMD in Desktop Mode disabled: moving your HMD around will not move the camera around **Check**
Turning HMD in Desktop Mode on, your desktop view should move around when moving the HMD **Check**
Turning HMD in Desktop Mode off after moving in active, should revert the camera back to its original avatar position **Check**


**Pass**

**Comment by Menithal** [comment]
@themelissabrown  this is still waiting for review

**Comment by hyperlogic** [comment]
Perhaps this worklist item was poorly worded.  The expected behavior should be that the vive HMD can still be used in desktop mode to control your avatar's head movements, but that the camera will not tilt wildly.  It's the unwanted camera rotation that is is the main issue.  Disabling head tracking all together isn't the prefered solution, fixing the camera is.

**Comment by Menithal** [comment]
@hyperlogic then it definitely is badly worded. Because it clearly says 

```
Task: Add checkbox option under "Use Vive devices in desktop mode" to turn off the HMD from being tracked while in Desktop mode.
```

**Comment by ZappoMan** [comment]
@Menithal - when you have a chance, can you please click through the CLA agreement, so we can process this and future PRs from you.

Secondly, it does sound like there is some confusion around what the spec was supposed to say, I've asked the PM team to clean up the WL/spec and make sure it reflects what was originally intended. Sorry for the confusion. @themelissabrown can make sure we get this sorted out and you're compensated appropriately for your time...

**Comment by Menithal** [comment]
@ZappoMan done, and yes, please make sure that any WL are clear and to point with updated information, this has happened twice now

**Comment by MiladNazeri** [comment]
Update on this PR - 

There was some confusion on which fogbugz ticket this was addressing.   

This was for case 8379 and not 6065 which involved having an option to turn off the HMD tracking all together.   

After talking with @hyperlogic, we are moving the checkbox from the bottom into the section where you can choose what tracks the head - Vive HMD / Pucks / None(new option).  

6065 is being addressed by @Menithal in a new WL/PR.  
https://worklist.net/21612

**Comment by Menithal** [comment]
Accidental removal. Reopening

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5163/HighFidelity-Beta-PR11752-e28f80401f32760006489a1b021489343fee1bb4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5163/HighFidelity-Beta-PR11752-e28f80401f32760006489a1b021489343fee1bb4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5164/HighFidelity-Beta-PR11752-ba1cd74ffed6c93ce19f8ab46e63c701ab54c3a4.dmg

**Comment by Menithal** [comment]
Can we have a PR refresh? I updated the logic so I think this should be reset to 

QA Ready and revisited

----

The following change was made:

Moved "Use HMD in Desktop Mode" to being a field "None" under `Configuration>Head`.
Based on @MiladNazeri's feedback

Once: "Use Vive devices in Desktop Mode" is true, "None" should be visible and usable. Should work similarly.

----

# New QA Plan:

1. Stay in Desktop Mode
2. Visit Controller Settings
3. Turn on your controllers
4. Turn on "Use Vive devices in Desktop Mode"
5. New Field "None" Should appear under "Configuration>Head"
5. With "None": moving your HMD around will not move the camera around
7. Switching to something else than "None", your desktop view should move around when moving the HMD / Pucks
8. Switching back to "None", should revert the camera back to its original avatar position.
9. Turning off "Use Vive devices in Desktop Mode" should switch "None" to "Hmd"

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5171/HighFidelity-Beta-PR11752-693da50a6849bf03d9c196835f6c6bd67d5de911.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5171/HighFidelity-Beta-PR11752-693da50a6849bf03d9c196835f6c6bd67d5de911.exe

**Comment by MiladNazeri** [comment]
Updated test plan:
https://highfidelity.testrail.net/index.php?/cases/view/3511

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
Solid **Pass**
TestRail Results: https://highfidelity.testrail.net/index.php?/runs/view/1161&group_by=cases:section_id&group_order=asc

**Pull request merged**
