### PR TITLE
Graphics merge into Master: Adding Gamma correction, Tone Mapping and Debugging tool

### PR DESCRIPTION
**Pull request by samcake**
- Added Gamma correction to the rendering pipeline making sure every color are input in sRGB space (Gamma 2.2) and used in shaders in Linear space.
-- DIffuse texture are considered sRGB and converted by the GPU at fetch time
-- Diffuse and Emissive colors in the Material are stored Linear in the Material class and converted on set and get
-- color attribute stream is converted in the vertex shader if used to feed the diffuse color

- Introduced the LightingBUffer as a known Buffer of FramebufferCache. THis is where all the lighted surface is output. This is a HDR buffer, color are expressed in linear space and can have higher range values than 1.0. this is the physically "accurate" light energy per pixel (at least for our shading model).

- Added the ToneMappingEffect as the job taking care of converting the Lightingbuffer generated during rendering to the final color buffer actually provided to Display-Plugin
 This job actually does 2 steps
 (1) the calibration of the Luminosity coming from the LightingBuffer pixel, for now this is acheived by a uniform called Exposure which is manually assigned. We will probably add an automatic calibration feature.
(2) The actual tone mapping using a tone curve that bring the calibrated color  (in linear space) back into sRGB space ready to be displayed by the DisplayPlugin
There are several ToneCurve available, the default beeing the simple Gamma 2.2 correction.
Also available are "Reinhard" and "Filmic" as detailed in this talk:
http://filmicgames.com/archives/6   (John Hable at GDC 2010)

- Split the SceneScriptingInterface in 2 moving all the RenderEngine specific properties to RenderScriptingInterface. The toneMpping exposure and toneCurve are exposed in the RenderScriptingInterface js api "Render"

- Added a debugging tool (in renderEngineDebug.js) allowing to inspect the deferred buffers, the lighting buffer and eventually custom shader result in split screen together with the official rendering. amazing!

- Fixed a bug in the current shading equation where the diffuse was not scaled properly by the Fresnel contribution...

- Added the generateTextureMips command to the gpu::Batch to manually trigger the mips generation on a texture, the texure must have a linear mip sampler otherwise, the command doesn;t do anything.

- Reorganized the jobs in the RenderDeferredTask in order to execute everything cpu only upfront and only last the gpu jobs

- Procedural Shaders for skybox and Emissive typically do their own gamma correction, so we keep it working that way with the new gamma correction stage by actually counter gamma correcting the color produced by the shader. We will try to find a better solution for this...

- TODO:
-- Add an automatic exposure system
-- fix bugs...

This is team effort by Clement, Zach and Sam

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 154bf5978b26b1cdf6149fd11eb5e67062be1a6e available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by samcake** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5bac4c257869f000da7229504da7d824788ae18 available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 33a14b07b9a983ae1cb05c070af23c03d933bf1e available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by samcake** [comment]
THis is the build after the revert from upstream master  with the crash on launch

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e1a812ff3775f602634307573bcc410d58db58b available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f63a7ae111794453bd7f81996280b56b5f96624 available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f6466f107b783bbc5083fa4c0958195cbea47cf available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3ab230638c7dbb0d801b34b4f5b8b3761d0db8c available at: https://gist.github.com/2d020ae293825a64eccc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6701.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6701.dmg

**Pull request merged**
