### PR TITLE
disable grab.js in HMD

### PR DESCRIPTION
**Pull request by druiz17**
Ticket this PR addresses
https://highfidelity.fogbugz.com/f/cases/edit/7620/grab-js-is-not-disabled-in-HMD-mode

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- create some dynamic object
- in Desktop mode you should be able to grab these objects. you usually see a silver pole through the object to let know that you are grabbing the object.
- make sure that the previous step does not happen in HMD mode.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3746/HighFidelity-Beta-PR11484-45b8bfdb1f7522fb3128ea991bbf8edd0676e8c6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3746/HighFidelity-Beta-PR11484-45b8bfdb1f7522fb3128ea991bbf8edd0676e8c6.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

create some dynamic objects **Check**
in Desktop mode you should be able to grab these objects. you usually see a silver pole through the object to let know that you are grabbing the object. **Check**
make sure that the previous step does not happen in HMD mode. **Check**

**Pass**

**Pull request merged**
