### PR TITLE
More unit testing work

### PR DESCRIPTION
**Pull request by jherico**
Working toward continuous integration unit tests

## Testing

No QA required, only modifies unit test related code.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9901/HighFidelity-Beta-PR13191-1aba6e8fe1d70c56ad70bf8f232d06f8356e81dc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9901/HighFidelity-Beta-PR13191-1aba6e8fe1d70c56ad70bf8f232d06f8356e81dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9901/HighFidelity-Beta-Interface-PR13191-1aba6e8fe1d70c56ad70bf8f232d06f8356e81dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9901/HighFidelity-Beta-PR13191-1aba6e8fe1d70c56ad70bf8f232d06f8356e81dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9901/HighFidelity-Beta-Interface-PR13191-1aba6e8fe1d70c56ad70bf8f232d06f8356e81dc.exe

**Comment by samcake** [comment]
ENgine team is taking the repsonsability to merge this PR
It only touches on the unit tests

**Pull request merged**
