### PR TITLE
2017-10-10 Commerce Frontend Updates

### PR DESCRIPTION
**Pull request by zfox23**
This PR includes the following:
- Inspection certificate now includes real data!!!

# Test Plan:
**Note:** Currently, you must manually enable "commerce" by adding `"commerce": true,` in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating `Settings.setValue("commerce", true)` and restarting.

**Note:** If your wallet is already set up and there is a step that asks you to not have the wallet set up yet, open the "wallet" app, help tab, and press the red "DBG: RST Wallet" button. If your wallet is set up but broken (e.g., from testing something that didn't work), such that you are prompted for a pass phrase that is never accepted, you need to:
1. Quit interface and delete `%appdata%/Interface <build #>/<username.hifikey>`
2. Restart Interface, set up wallet, and then press the red "DBG: RST WALLET" button as above. Now you are in a truly clean state for wallet setup.

## Inspecting
1. Purchase a "test beach ball" from the Marketplace, then rez it.
2. Right click the rezzed beach ball, then click the "i". Verify that you see a certificate rather than the marketplace item page.
3. Clicking the "view in market" button of the certificate should proceed to the marketplace page for the item. Clicking the item name link in the cert should do the same thing.
4. The certificate should contain information that makes sense. Try inspecting an item whose status is still `pending`, and then whose status is `confirmed`. Also try inspecting an item before authenticating your wallet, then after (use the "clear passphrase" button in the "Help" tab of the wallet to "log out of your wallet").
5. Go to the Marketplace app, then My Purchases at the top. Verify that clicking to view the certificate on one of your purchases brings up the correct cert display.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4024/HighFidelity-Beta-PR11567-4ebccfa65c8205ea0b35c523b5034237b88e4d48.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4038/HighFidelity-Beta-PR11567-4ebccfa65c8205ea0b35c523b5034237b88e4d48.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4038/HighFidelity-Beta-PR11567-4ebccfa65c8205ea0b35c523b5034237b88e4d48.exe

**Comment by Nex-Pro** [comment]
T E S T I N G

**Comment by Nex-Pro** [comment]
### FAIL


Note: Currently, you must manually enable "commerce" by adding 

    "commerce": true, 

    in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating 

    Settings.setValue("commerce", true) and restarting.


Note: 

If your wallet is already set up and there is a step that asks you to not have the wallet set up yet, 
open the "wallet" app, help tab, and press the red "DBG: RST Wallet" button. 

If your wallet is set up but broken (e.g., from testing something that didn't work), 
such that you are prompted for a pass phrase that is never accepted, you need to:

    Quit interface and delete %appdata%/Interface <build #>/<username.hifikey>

Restart Interface, set up wallet, and then press the red "DBG: RST WALLET" button as above. 
Now you are in a truly clean state for wallet setup.

### Inspecting

Purchase a "test beach ball" from the Marketplace, then rez it. **FAIL**

Right click the rezzed beach ball, then click the "i". 

Verify that you see a certificate rather than the marketplace item page. **Unable to proceed**

Clicking the "view in market" button of the certificate should proceed to the marketplace page for the item. 

Clicking the item name link in the cert should do the same thing. **Unable to proceed**

The certificate should contain information that makes sense. Try inspecting an item whose status is still pending, and then whose status is confirmed. 

Also try inspecting an item before authenticating your wallet, **Unable to proceed**
then after (use the "clear passphrase" button in the "Help" tab of the wallet to "log out of your wallet").

Go to the Marketplace app, then My Purchases at the top.
Verify that clicking to view the certificate on one of your purchases brings up the correct cert display. **SUCCESS**


Notes:

Again the recent activity did not update.
Clicking on security and help then back did not refresh even after waiting a reasonable time.
Refreshed when wallet was reopened.

On clicking 'REZ IT' I got a notification saying "there was an error importing the entity file."
This was repeated. There was no log output on clicking 'REZ IT'

The 'REZ IT' button incorrectly changes to the 'REZZED' state even though nothing was rezzed.

Tried again with the flare gun. Problem persisted.

Problem persisted after restart.

Had a stuck dropdown on the 'My Purchases' page.

Good points:

Recent activity scrolls ok!

Recent activity scroll bar scales ok.

Balance is correctly updated.

Messages appear to be correct and in the correct order.

Debug clear pass works.

## Stuck dropdown and unrezzzable items.
sp4776-hifi-snap-by-rocketman-on-2017-10-11_14-03-57

### Scrolly stuff ! 
nv4776-hifi-snap-by-rocketman-on-2017-10-11_14-09-41

### Typing 'banana'
gm4776-hifi-snap-by-rocketman-on-2017-10-11_14-04-26

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4046/HighFidelity-Beta-PR11567-c2733a4186f622aa68fdf94240f2e9fb195e6d33.dmg

**Comment by Nex-Pro** [comment]
Retest as per request.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4046/HighFidelity-Beta-PR11567-c2733a4186f622aa68fdf94240f2e9fb195e6d33.exe

**Comment by Nex-Pro** [comment]
### PASS

Items now rez following backend fix.

Certs display correctly.

**Comment by Nex-Pro** [comment]
@zfox23

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4053/HighFidelity-Beta-PR11567-3f0ec73be687c7292a51c2b99ba2592dc68a92c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4053/HighFidelity-Beta-PR11567-3f0ec73be687c7292a51c2b99ba2592dc68a92c2.exe

**Pull request merged**
