### PR TITLE
Case 21091: Improved audio metering

### PR DESCRIPTION
**Pull request by kencooke**
This PR reimplements the audio input level metering on the client, to encourage better microphone level settings.

https://highfidelity.manuscript.com/f/cases/21091/Improved-audio-metering

Level detection is now done on the raw (unprocessed) audio input.
Audio.inputLevel now reports raw mic level, unaffected by mute or gate settings.
Digital clipping is accurately detected on the unprocessed input, as 3+ consecutive overs.

The audio meter is accurately calibrated from -48dbFS to -9dBFS, with a blue "gated" indicator and a red "clipping" indicator (with two second hold). Meter attack/release times approximate a conventional PPM meter. See images below.

The intent is that:
Scripts can warn when the input is muted, but high mic levels are present.
Calibrated metering with proper clipping detection will encourage more consistent mic settings.

Input is gated:

gated

Input is clipping:

clipping

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17148/HighFidelity-Beta-PR14880-5681a99.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17148/HighFidelity-Beta-PR14880-5681a99.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17148/HighFidelity-Beta-Interface-PR14880-5681a99.dmg

**Comment by kencooke** [comment]
### Test Plan ###

With Interface from this PR,
1) Verify that the audio meter works as described above.
2) Verify that the red "clipping" indicator comes on for 2 seconds when audio is clipping (shout into mic)
3) Verify that when noise-reduction is enabled, the blue "gated" indicator comes on when gate is closed

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17148/HighFidelity-Beta-PR14880-5681a99.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17148/HighFidelity-Beta-Interface-PR14880-5681a99.exe

**Pull request merged**
