### PR TITLE
make server entity scripts respect the script whitelist

### PR DESCRIPTION
**Pull request by birarda**
- make server entity scripts respect the same script whitelist that client scripts do

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

(1) Add a domain to your script whitelist in the advanced Entity Server settings in your Domain Server.
(2) Attempt to set a script URL for a client entity script and server entity script using a domain that is not in the whitelist. The edit should be rejected and the script URL should remain its previous value. You may need to switch tabs in the "Create" mode for the properties to refresh.
(3) Attempt to set a script URL for a client entity script and server entity script using a domain that is in the whitelist. The edit should be allowed and the script URL will change to show the new value.

On master, step (2) will not block a URL for a server entity script that is not in the whitelist.

**Comment by CainFoool** [comment]
Testing when built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/98/HighFidelity-Beta-PR10526-cecbf431297f1cd9e25f468eab1881f91217e5e3.exe

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/98/HighFidelity-Beta-PR10526-cecbf431297f1cd9e25f468eab1881f91217e5e3.dmg

**Comment by CainFoool** [comment]
# Test Passed 

The Server Script URL box will not let you save the changes to the box if it does not contain one of the domains in the advanced settings on the Domain Server. (You're right, it does require going from one tab to the other).

In master, it does not block the changes from being made and persists.

**Pull request merged**
