### PR TITLE
Fix for blendshapes playing back in recordings at 2x their proper values

### PR DESCRIPTION
**Pull request by hyperlogic**
This is fixed by having the Agent disable procedural blendshape generation on the client end by calling, setHasProceduralEyeFaceMovement(), setHasProceduralBlinkFaceMovement(), setHasAudioEnabledFaceMovement()

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/17879/Fumbles-Blendshapes-Fail-in-Recordings

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12790/HighFidelity-Beta-PR13962-949efff.apk

**Comment by hyperlogic** [comment]
QA Test plan:
   * Install and run the client AND server installer from this PR.
   * Follow the instructions in this document about how to make an avatar recording:  https://docs.highfidelity.com/create-and-explore/marketplace-apps/record-app
   * While making a single recording with mic audio observe the facial expressions of your avatar during the recording process.
   * Compare those facial expressions to the resulting avatar recording during playback.

Expected Result:
The facial expressions of the avatar should be recorded accurately.

Actual Result: (master & v0.72)
The facial expressions of the avatar are exaggerated by 2x.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12790/HighFidelity-Beta-PR13962-949efff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12790/HighFidelity-Beta-Interface-PR13962-949efff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12790/HighFidelity-Beta-PR13962-949efff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12790/HighFidelity-Beta-Interface-PR13962-949efff.exe

**Comment by jakram** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12798/HighFidelity-Beta-PR13962-949efff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12798/HighFidelity-Beta-PR13962-949efff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12798/HighFidelity-Beta-Interface-PR13962-949efff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12798/HighFidelity-Beta-PR13962-949efff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12798/HighFidelity-Beta-Interface-PR13962-949efff.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . Facial movement is accurately recorded.

**Comment by conklin94122** [comment]
@hyperlogic PR has conflicts. Let me know if we need to retest after you resolve them or if the existing test results stand. Thanks.

**Comment by qlistephens95** [comment]
FAIL @conklin94122 . With some avatars the facial expressions work as expected and are not experiencing facial exaggerations, but with other avatars i.e. finnegan, there are no facial expressions at all and the avatar is left looking blank and emotionless. attaching video.
[2018-09-10 10-42-23.zip](https://github.com/highfidelity/hifi/files/2367977/2018-09-10.10-42-23.zip)

**Comment by hyperlogic** [comment]
The regression identified with the Finnegon avatar, was introduced in #13919, and not related to this PR.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12837/HighFidelity-Beta-PR13962-1570ae6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12837/HighFidelity-Beta-PR13962-1570ae6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12837/HighFidelity-Beta-Interface-PR13962-1570ae6.dmg

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
PASS @conklin94122 

Based on @hyperlogic's input and excellent sleuthing skills, it was shown that the issue @qlistephens95 pointed out stems from Master 9287 since the mouths were working in Master 9286. See bug https://highfidelity.manuscript.com/f/cases/18307/Blendshapes-no-longer-work-for-certain-avatars for details. Additional testing with the recording script using Woody, Priscilla, Anime Boy, Anime Girl, Last Legends Male, Matthew, and Artemis revealed that no exaggerated facial features were found.

**Pull request merged**
