### PR TITLE
hide progress overlays if interstitial mode

### PR DESCRIPTION
**Pull request by wayne-chen**
- Hides "LOADING CONTENT" bar in HMD/desktop mode if interstitial mode is enabled

### CODE REVIEW

**Comment by wayne-chen** [comment]
## TEST PLAN
- Launch interface
- Navigate between domains
- When looking around in HMD/desktop mode in the interstitial page, you should not see the "LOADING CONTENT" message (similar to the image below)
image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13920/HighFidelity-Beta-PR14213-07d0d38.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13920/HighFidelity-Beta-PR14213-07d0d38.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13920/HighFidelity-Beta-Interface-PR14213-07d0d38.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13920/HighFidelity-Beta-PR14213-07d0d38.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13920/HighFidelity-Beta-Interface-PR14213-07d0d38.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13928/HighFidelity-Beta-PR14213-a2dfc3a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13928/HighFidelity-Beta-PR14213-a2dfc3a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13928/HighFidelity-Beta-Interface-PR14213-a2dfc3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13928/HighFidelity-Beta-PR14213-a2dfc3a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13928/HighFidelity-Beta-Interface-PR14213-a2dfc3a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13960/HighFidelity-Beta-PR14213-a010dc7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13960/HighFidelity-Beta-PR14213-a010dc7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13960/HighFidelity-Beta-Interface-PR14213-a010dc7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13960/HighFidelity-Beta-PR14213-a010dc7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13960/HighFidelity-Beta-Interface-PR14213-a010dc7.exe

**Comment by JeffClinton** [comment]
Removing QA ready tag since this was failed in 74

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14016/HighFidelity-Beta-PR14213-6b95bdd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14013/HighFidelity-Beta-PR14213-def05b9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14013/HighFidelity-Beta-Interface-PR14213-def05b9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14013/HighFidelity-Beta-PR14213-def05b9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14013/HighFidelity-Beta-Interface-PR14213-def05b9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14021/HighFidelity-Beta-PR14213-572fe78.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14021/HighFidelity-Beta-PR14213-572fe78.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14021/HighFidelity-Beta-Interface-PR14213-572fe78.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14021/HighFidelity-Beta-PR14213-572fe78.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14021/HighFidelity-Beta-Interface-PR14213-572fe78.exe

**Comment by wayne-chen** [comment]
Changed to #14225 due to the mess in here.

**Pull request closed without merging**
