### PR TITLE
Fix LODManager JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Check that the LOD items work in the following dialogs:
- Settings > LOD...
- Developer > Render > LOD Tools

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9344/app_13058_PR_f9bda6df15f125b2352dc19a1f6a70b38cea10a2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9344/HighFidelity-Beta-PR13058-f9bda6df15f125b2352dc19a1f6a70b38cea10a2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9344/HighFidelity-Beta-Interface-PR13058-f9bda6df15f125b2352dc19a1f6a70b38cea10a2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9344/HighFidelity-Beta-PR13058-f9bda6df15f125b2352dc19a1f6a70b38cea10a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9344/HighFidelity-Beta-Interface-PR13058-f9bda6df15f125b2352dc19a1f6a70b38cea10a2.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
LOD settings work and are updated. The Dev > Render > LOD tools option does not seem to save after the interface is restarted. LOD in settings does maintain user defined options after restart.

**Pull request merged**
