### PR TITLE
Fix the dice in /tutorials

### PR DESCRIPTION
**Pull request by imgntn**
This PR fixes an error in the dice script related to the toolbars library: it changes the toolbar reference to a production url.

### CODE REVIEW

**Comment by imgntn** [comment]
To test, run /tutorials/createDice.js

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc82780512fc3dc4c8addc00f54c9426bcd7e4ae available at: https://gist.github.com/2c9b0c4b8447d119310a3a0954743b48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7795.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7795.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7795
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Test Results:** Successful test.  Loaded ```createDice.js``` and the UI loaded and rolled a few instances.  Screen shot attached.
**Successful Logout/Crash:** Successful logout.
createdice

**Pull request merged**
