### PR TITLE
Allows model entity joint to be changed from scripts

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5783/app_12042_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5783/HighFidelity-Beta-PR12042-29f083547527adbdc74c86b71c62af1caefd861c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5783/HighFidelity-Beta-PR12042-29f083547527adbdc74c86b71c62af1caefd861c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5791/app_12042_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5791/HighFidelity-Beta-PR12042-77874de9093bebd98377dd4d8e8400ce32adce1f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5791/HighFidelity-Beta-PR12042-77874de9093bebd98377dd4d8e8400ce32adce1f.dmg

**Comment by vegaslon** [comment]
An excellent test for this is the script used for this issue. https://github.com/highfidelity/hifi/issues/10809

**Comment by druiz17** [comment]
Test plan
- run script-archive/dressing_room/doppelganger.js
- make sure that your doppelganger follows your avatar

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6529/app_12042_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6529/HighFidelity-Beta-PR12042-2d70e7654660cc3095a9be67a48fdbbfeec12a06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6529/HighFidelity-Beta-PR12042-2d70e7654660cc3095a9be67a48fdbbfeec12a06.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. Doppelganger follows avatar around, but does not mirror movements and is stuck in T pose.

@conklin94122 

frozen doppleganger

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6621/app_12042_PR.apk

**Comment by druiz17** [comment]
@sbennett77 please us the most up to date build when retesting. Your doppelganger should look like your current avatar.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6622/app_12042_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6622/HighFidelity-Beta-PR12042-5bb1b1bbffb006d651d9f9d74904bec9f725e5d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6622/HighFidelity-Beta-PR12042-5bb1b1bbffb006d651d9f9d74904bec9f725e5d9.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
