### PR TITLE
Label models.json.gz paths in server Content tab with operating system

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

In the server settings' "Content" tab the models.json.gz paths should be labeled with their operating systems, thus:

os-labels

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4737/HighFidelity-Beta-PR11766-ebe5d51ee8164eda2a6b2aca528df10c5b0fc49a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4737/HighFidelity-Beta-PR11766-ebe5d51ee8164eda2a6b2aca528df10c5b0fc49a.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

In the server settings' "Content" tab the models.json.gz paths should be labeled with their operating systems **Check**

Screenshot:
image

**Pass**

**Pull request merged**
