### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**
#11753

### CODE REVIEW

**Comment by Atlante45** [comment]
Please use the test plan from #11753

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4731/HighFidelity-Beta-PR11763-8a903c8b1232b34a3a0f78739b40539f9f7c9610.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4731/HighFidelity-Beta-PR11763-8a903c8b1232b34a3a0f78739b40539f9f7c9610.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

(1) from the marketplace: rez the circus hammer **Check**
(2) right-click to get info icon **Check**
(3) go into create mode **Check**
(4) select the hammer **Check**
(5) drag a selection handle as if to scale the hammer **Check**
(6) --> NO crash **Check**

**Pass**
image

**Comment by Nex-Pro** [comment]
### This is what we needed to check. 

a19348-hifi-snap-by--on-2017-11-07_23-22-48

No crash in this situation. The repro notes were slightly incorrect.

**Comment by Nex-Pro** [comment]
@Atlante45 ^

**Pull request merged**
