### PR TITLE
Fix MS14741, allowing uninstall of apps whose scripts are no longer running

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14741](https://highfidelity.manuscript.com/f/cases/14741). This is what the logic for app uninstallation should have been in the first place.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9451/HighFidelity-Beta-PR13081-56ba59681a95450a151b6e9bad59a35e731c3380.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9451/HighFidelity-Beta-Interface-PR13081-56ba59681a95450a151b6e9bad59a35e731c3380.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9451/HighFidelity-Beta-PR13081-56ba59681a95450a151b6e9bad59a35e731c3380.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9451/HighFidelity-Beta-Interface-PR13081-56ba59681a95450a151b6e9bad59a35e731c3380.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
