### PR TITLE
Use old controller data for 3 seconds when losing track of touch controllers

### PR DESCRIPTION
**Pull request by druiz17**
When oculus loses track of the touch controllers, use the last position data plus new rotation data for 3 seconds until dropping the hand to the avatars side.

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- When in interface, move the oculus controllers outside the eye tracker sight
- Once oculus has lost tracking of the controller, the avatar hand position should not move but still be able to rotate.
- after about three seconds the avatar hand should snap to your side.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81ae3e44fdd288b9aaa7cf2d3fad65a7161a08d8 available at: https://gist.github.com/c6967a9ec73af642f3d86e4eba956628<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10127-81ae3e4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10127-81ae3e4.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10127-81ae3e4.exe

PASS

- When in interface, move the oculus controllers outside the eye tracker sight.
Once oculus has lost tracking of the controller, the avatar hand position should not move but still be able to rotate.
PASS

- after about three seconds the avatar hand should snap to your side.
PASS

**Pull request merged**
