### PR TITLE
Remove old Leap Motion code

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This is a test build of preparations prior to reimplementing Leap Motion support as a plugin.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing: A brief smoke test to check that things still work - desktop and HMD operation, dialogs and tablet, mouse and controllers.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/743/HighFidelity-Beta-PR10700-a8501a7ac627cc968fd2a1ff43949548011f6c4b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/743/HighFidelity-Beta-PR10700-a8501a7ac627cc968fd2a1ff43949548011f6c4b.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

General smoke test: HMD w/ Motion Controllers [HTC Vive]: **Pass**
General smoke test: Desktop w/ M&KB: **Pass**

Please let me know if there is anything more I can do/provide to assist :)

**Pull request closed without merging**
