### PR TITLE
Fix QML warnings at shutdown

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Repro:
- Run default scripts.
- Open following windows open:
	Running Scripts
	Entities editor
	Address bar
- Press the "x" top right of Interface dialog to shut it down.
- Check near end of the program log.

Before, with Interface other than this PR: You'll see the following warnings related to particular .qml files (some repeated):
[04/16 11:28:30] [WARNING] file:///D:/Workspaces/CtrlAltStudio/HiFi/HiFi/build/interface/Release/resources/qml/hifi/dialogs/RunningScripts.qml:33: TypeError: Cannot read property 'scriptsModelFilter' of null
[04/16 11:28:31] [WARNING] file:///D:/Workspaces/CtrlAltStudio/HiFi/HiFi/build/interface/Release/resources/qml/Stats.qml:6: TypeError: Cannot read property of null
[04/16 11:28:31] [WARNING] file:///D:/Workspaces/CtrlAltStudio/HiFi/HiFi/build/interface/Release/resources/qml/windows/Window.qml:119: ReferenceError: raise is not defined
[04/16 11:28:31] [WARNING] file:///D:/Workspaces/CtrlAltStudio/HiFi/HiFi/build/interface/Release/resources/qml/windows-uit/Window.qml:253: ReferenceError: raise is not defined
[04/16 11:28:31] [WARNING] file:///D:/Workspaces/CtrlAltStudio/HiFi/HiFi/build/interface/Release/resources/qml/AddressBarDialog.qml:20: TypeError: Cannot read property of null

After, with Interface from this PR: There are no such warnings.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f6cfb72ea70f8f46e912e363ef3e4999402f65b available at: https://gist.github.com/a473593494d7492dc0f8dfce2b330517<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7691.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7691.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7691
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Partially successful test.  Closed existing ```defaultScripts.js``` and loaded from disk the proper PR ```defaultScripts.js``` and then opened running scrips and selected the entities editor address bar and pressed the ```x``` on the top right of the Interface dialog and the log reported no instances of any trace of the following search string ```Cannot read property``` however did find some instances of ```ReferenceError```.  Attached log file for deeper inspection. 
**Successful Logout/Crash:** Successful logout.
[attachments.zip](https://github.com/highfidelity/hifi/files/222671/attachments.zip)

**Comment by ctrlaltdavid** [comment]
Thanks @kevinmthomas-carpool ... I've added an Asana bug report on ...
[WARNING] file:///C:/Program Files/High Fidelity - PR7691/resources/qml/desktop/Desktop.qml:39: ReferenceError: GL is not defined
It's quite a separate issue.

**Pull request merged**
