### PR TITLE
kinematic grab fixes

### PR DESCRIPTION
**Pull request by sethalves**
- fix kinematic grab

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 93503d0a216019cff88a2b08441f88539881932f available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b102081f2f1dd0a0bc63c9f7d9c9972c7cb2eb38 available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Comment by AndrewMeadows** [comment]
There is a problem with this PR...

EntityItem properties are being poked directly inside **AvatarActionHold::doKinematicUpdate()** which is called inside **DynamicsWorld::stepSimulation()** which is something that we want to eventually move to its own thread.  The changes in this PR will make it harder to multithread the physics simulation, so they are  a step in the wrong direction (*).  

In general any changes to "RigidBodies" during the physics simulation should be relayed to their corresponding "game objects" (EntityItem's in this case) in the "post stepSimulation()" block inside **Application::update()**.  This currently works for dynamic objects, but not kinematic --> we should make it work for kinematic objects if they are being updated by fancy Actions.

(*) Hrm... after looking through the Action code I realize that there is some other stuff that needs to be changed before **stepSimulation()** could be made thread-safe.  It doesn't need to be fixed in this PR, but still needs to be done eventually.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c38a252b1290b4ded38699b8a87c6d98c6de6bbf available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf83ca22bbaa77a195268e49ff720096f61d5a15 available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 944f0965c059a1d9af6a30d8c18523d59c836cff available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Comment by AndrewMeadows** [comment]
There is a merge conflict in **handControllerGrab.js**.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 896ed3927c5730f955dc8e982f24b8cee090774c available at: https://gist.github.com/761580f48c7e07f67c56<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6244.dmg

**Pull request merged**
