### PR TITLE
re-enable web entity-items on linux

### PR DESCRIPTION
**Pull request by sethalves**
- re-enable web entity-items on Linux

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run interface on Linux, use edit.js to create a web entity
- observe that interface doesn't crash

**Comment by OmegaHeron** [comment]
QA Pass
Tested Ubuntu 16.04.1 with GTX-660M GPU on Alienware M18xR2 laptop.  Yes it's a fast QA Pass as I had not an hour ago made exact change and tested just to see how it would work.  Psychic pre-cognition QA testing FTW.

**Comment by OmegaHeron** [comment]
Second layer pass - it works as well from compiling this PR.  Considering it was a some had issue, some didn't thing... it may still be some Linux users will crash depending upon hardware and specific distro in use.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc5e63c4f146806f7e735de1df1b1c35fcae3f21 available at: https://gist.github.com/5a434fc78f11cadad2a64314575a1d83<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8640-dc5e63c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8640-dc5e63c.dmg

**Comment by sethalves** [comment]
I think that the upgrade to Qt5.6 made it work on Linux.

**Pull request merged**
