### PR TITLE
Domain-unreachable message remaining on slow connects

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
https://highfidelity.manuscript.com/f/cases/14417/

For the HMD case only the enable request was being handled, not the disable request (the desktop case handles both). This PR should fix that, although it is difficult to reliably test.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10277/HighFidelity-Beta-PR13278-7598c7a.apk

**Comment by SimonWalton-HiFi** [comment]
## Test Plan ##

See https://highfidelity.manuscript.com/f/cases/14417/#BugEvent.94623

In HMD use Menu -> Goto to visit a site that is slow to initially connect (>5 s).

Before PR: an in-tablet popup "Unable to connect to this domain. Click ..." may appear and persist while the site is loaded.

After PR: this popup will not appear or only briefly appear.

**Comment by birarda** [comment]
This looks good to me, though I feel like we might want to make sure that the connection failure is the active page on the tablet before we forcibly close it. I'm worried that this could could end up returning to the home screen and closing the tablet when the user has asked to connect to a domain and then has navigated elsewhere on the tablet?

We might be able to create a forcing test for this if we use clumsy to temporarily block incoming packets from the domain-server.

**Comment by SimonWalton-HiFi** [comment]
Yeah I wasn't sure about that. I think the normal GOTO action is to close the tablet but the user could be 'mousing ahead'. I could add a flag for the last action being the error popup.

**Comment by birarda** [comment]
Is there a way to check if it's still currently displaying `dialogs/TabletConnectionFailureDialog.qml`?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10277/HighFidelity-Beta-PR13278-7598c7a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10277/HighFidelity-Beta-Interface-PR13278-7598c7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10277/HighFidelity-Beta-PR13278-7598c7a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10277/HighFidelity-Beta-Interface-PR13278-7598c7a.exe

**Comment by SimonWalton-HiFi** [comment]
I threw a sleep call into the DS and was able to confirm that the popup appeared briefly then disappeared as content loaded.

**Comment by SimonWalton-HiFi** [comment]
The tablet's modal dialog wasn't being closed anyway - it was still there when you opened the tablet again. It's surprisingly difficult to just get rid of a qml popup; I think I now have a way.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10303/HighFidelity-Beta-PR13278-c277cc7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10303/HighFidelity-Beta-PR13278-c277cc7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10303/HighFidelity-Beta-Interface-PR13278-c277cc7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10312/HighFidelity-Beta-PR13278-2d9a5c6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10312/HighFidelity-Beta-PR13278-2d9a5c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10312/HighFidelity-Beta-Interface-PR13278-2d9a5c6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10313/HighFidelity-Beta-PR13278-f58e1eb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10313/HighFidelity-Beta-PR13278-f58e1eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10313/HighFidelity-Beta-Interface-PR13278-f58e1eb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10313/HighFidelity-Beta-PR13278-f58e1eb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10313/HighFidelity-Beta-Interface-PR13278-f58e1eb.exe

**Comment by qlipdahlin** [comment]
Currently testing.

**Comment by qlipdahlin** [comment]
@conklin94122 Pass

Tested using clumsy with a filter of 'udp and (udp.DstPort == 40102 or udp.SrcPort == 40102)', drop for inbound / outbound, and 100% chance. I started it, attempted to connect to dev-welcome and sat there without connecting to it until I got a could not connect error message. After I got that, I then stopped blocking the UDP port and almost immediately connected to the dev-welcome domain and the tablet went away immediately after.

If the tablet is opened to the Go-To menu, the tablet will close, even if the tablet was closed and opened again to the go-to menu. This was noted by Simon as not supposed to happen, but does not block the PR.

**Comment by SimonWalton-HiFi** [comment]
I was not able to repro the tablet getting closed after closing the popup tablet then reopening. I would not expect this due to the check for the popup being loaded before closing.

**Pull request merged**
