### PR TITLE
Fix 'Browse Avatars' button from Avatar Settings

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS11361](https://highfidelity.manuscript.com/f/cases/11361/Unable-to-switch-avatar-from-marketplace-on-stable-and-on-dev-builds).

## Test Plan
Perform the steps below in Desktop mode, and then in HMD mode.
1. Go to Settings -> Avatar
2. Click "Browse Avatars"
3. Choose a new avatar to use, then verify that your avatar has changed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6265/app_12165_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6265/HighFidelity-Beta-PR12165-6920e576137e8f03e0a1b4b1ad57e581aac37c54.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6265/HighFidelity-Beta-PR12165-6920e576137e8f03e0a1b4b1ad57e581aac37c54.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
