### PR TITLE
Make entity properties be undefined after entity is unloaded

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Take 2

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
This uses the EntityItem::_created value to determine whether the EntityItem has any non-zero default values set. If it doesn't then the JavaScript entity properties object created is not filled with zero default values (and so the entity properties are found to be "undefined" in JavaScript code, as desired.)

The assumption is that _created is always set when an EntityItem is created (which appears to be the case).

Scripts attached for demoing behaviour with Interface and entity scripts:
- [entityPropertiesAfterDeleteA.zip](https://github.com/highfidelity/hifi/files/104750/entityPropertiesAfterDeleteA.zip)
- [entityPropertiesAfterDeleteB.zip](https://github.com/highfidelity/hifi/files/104751/entityPropertiesAfterDeleteB.zip)

Have successfully run assignment-client and domain-server .exes from this PR to serve content without it disappearing when entities are added to the scene and json.gz server files are written.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2834dee00d46c66d05d687d5100fca998f41808e available at: https://gist.github.com/ca636f57defac2fd7d2e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6937.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6937.dmg

**Comment by OmegaHeron** [comment]
Windows 10.  Tested with current production stack server at domain with content.

Followed same test setup as previous version - no crash with PR.  Confirmed that asset reference is saved on stack side.  No issues seen.

**Comment by OmegaHeron** [comment]
One oddity I'm seeing - model isn't outlined when selected with this PR and if a model is selected *and* you turn off editor the properties window remains open until you toggle edit on/off 1 or 2 times.  Maybe just a fluke?  Current release build (4049) does not exhibit this.

**Comment by ctrlaltdavid** [comment]
@OmegaHeron Make sure you're running the updated edit.js included in this PR. I see the behaviour you describe when running the current "release"  version or edit.js with accompanying JavaScript exceptions reported in the program log, but works OK if running the updated edit.js.

**Comment by OmegaHeron** [comment]
Got it - I don't think that impacts validation of PR intent, but, does explain why it acts as it did.  I'll re-run QA test using proper edit.js just to be sure.  Thanks!

**Comment by OmegaHeron** [comment]
Works proper using PR included edit.js in reference to prior noted concern.  Works with either, for me, in respect to placing models and persisting + fixing issue intended to fix.

**Pull request merged**
