### PR TITLE
Fix blendshape crash on avatar removal

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/18688/crash-in-ModelBlender-setBlendedVertices

Test plan:
- Go to a domain with someone else.  Have them leave and come back repeatedly.  You shouldn't crash when they leave.  Blendshapes should be working.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13222/HighFidelity-Beta-PR14065-d772cdb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13222/HighFidelity-Beta-PR14065-d772cdb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13222/HighFidelity-Beta-Interface-PR14065-d772cdb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13222/HighFidelity-Beta-PR14065-d772cdb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13222/HighFidelity-Beta-Interface-PR14065-d772cdb.exe

**Comment by jakram** [comment]
currently testing

**Comment by jakram** [comment]
@conklin94122 PASS

Tested at The Spot with another test jumping in and out. Verified that blendshapes is working properly and that the other user could see my facial movements.

Additional items tested:

- Testing that mouths remain closed when user is muted
- Verified that mouths moved when the user turns the mic back on.
- Test in HMD and Desktop
- Tested on a variety of the default avatars.
- Tested jumping in and out of the same domain to verify no crashing behavior

**Comment by jakram** [comment]
Talked with @luiscuenca and @ZappoMan about the change. It has been approved and I'm adding the label. Additionally, I'm adding the QA Approved label as it did not affect testing of the teleporter.

**Pull request merged**
