### PR TITLE
Beta Release 33 - Includes up to Developer Release 5990

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Fix audio failures that occur when a broken driver returns mixFormat that is invalid/unsupported.
* Add opaques/skinned to forward rendering path 
* Add a volume slider beneath each user's VU meter in the PAL. Using this slider, users can adjust the volume of each avatar present in a domain individually. 
* When calling requestUsernameFromID() from a script you can call you own username
* Fixed a bug that kept physics and scripts from starting when logging-in near (but not looking at) something that's physical 
* Add a command line argument that enables heartbeat stats sending at 1s
* Remove ignored avatars from PAL when they disconnect 
* Allow users to edit their Display Name from within the PAL via an editable TextInput field
* Consume fewer cpu cores in AssetServer when interface is running locally 
* Add on/off switch to ambisonic/ambient sound emitter 
* Removing some PAL-related interface log spam 
* Introducing type Meta to the render items of the scene. The type Meta for a render item is used to indicate that a render item supervise sub items and act as a group of render items (typically shapes). https://github.com/highfidelity/hifi/pull/9410
* Create render forward version of pixel shaders 
* Additional trace details for GPU timing, frame data updates 
* Remove a line of old code in Clara.io download 
* Add "ADMIN" labels to the right of Display Names on PAL cards corresponding to domain administrators. 
* Updates the visual style of the letterbox popups that appear when clicking on "[?]" buttons. 
* Initial analytics for PAL usage 
*  Fix "Last Editor" popup bug
* Fix warnings for signed comp in AudioMixerSlavePool
* PAL: Fix card visibility when selecting out-of-table users 
* Fix Places / Paths anchor in domain settings 
* Use fromUserInput to avoid web entity crashes with bad URLs 
* Fix invalid volume values in injector options silencing all injectors 
* Do not allow grab or far-grab or click while editing objects 
* Update the name of the collision shapes used in edit.js properties 
* Connect audio injector signal to scripting
* Fix Edit.js rescale for decimal values 
* Fix a failure case where isFormatSupported(mixFormat) returns false on some systems, when format is WAVEFORMATEXTENSIBLE with channels > 2, audio enhancements in "Speaker Properties/Enhancements" are not disabled, and dwChannelMask is nonzero but does not match the speaker configuration. 
* Cleanup debug for safe web entity URLs 
* Use host check for entity script whitelist instead of startsWith 
* Fix a bug in the Steam JS API that caused the app to crash. 
* New Assignment type called the **Entity Script Server** as well as a new entity property called **serverScripts** 
* Fix intermittent Clara.io download crashes 
* Fix Overlay-as-child of model entity with reg point 
* Change server to default to not auto-muting 
* Optimize, prioritize, and timebox processing of avatar updates 
* Throttle audio with PI controller, by node 
* Edit entity filter
* Avatar mixer bandwidth optimization
* Fix audio-mixer timing for WIN32 
* Add debug logging to entity server startup in the case of having a filter 
* Display avatar count in table header 
* Fixes the audio encoding of a scripted agent that plays back a recording. 
* Fetch entity filter script asynchronously (but reject edits while waiting) 
* Fix label typo in help graphic 
* Fix animation jitter 
* Require password verification in domain-server settings
* Fix importing of PolyVox entities
* Fix Entities.isChildOfParent crashing if given unknown ID 
* Queues local audio in a separate ring buffer so responses do not lag with network jitter 
* ENTITY FILTERS: Improve zone filter; maxVelocity filter; documentation
* Fix for missed START collision events 
* Tablet UI 
* Avoid recursion to unchanged octree elements with frustumless queries too
*  Fix memory-leak in Windows audio stack 
* Adding support for disabling texturing from the material 
* Fix bug that causes GCC not to detect AVX2 
* Compute Model's local bounds outside pending changes queue 
* Hide webview context menus when clicked
* Fix simulation owned entities not to go to origin after cache reload (+ small priority fix) 
* Make table additions in DS settings more obvious
* Fixed a bug with empty entity script whitelist not skipping script check
* Cleanly log failed entity adds, and tell the client to delete his copy 
* Accept forced physics results from entity server (e.g., when filtered) 
* Fixed a bug adding rows in domain-server settings with default values
* PAL: Raise virtual keyboard when editing DisplayName in HMD 
* Rework users.js for Tablet: better jump to user & who can find me toggle 
* Adding instrumentation for traces regarding Image and texture loading and preparation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bac5bd5c0e6abefe33bb316da1fdd68005901dc2 available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-bac5bd5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-bac5bd5.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** Not available
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop 1600x900 maximized window

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2576 |4318 |
**GPU Buffer Count**: |769 |1337 |
**CPU Memory Usage**: |35940304 |66094160 |
**GPU Memory Usage**: |18917488 |44333168 |
**CPU Texture Count**: |332 |308 |
**GPU Texture Count**: |262 |264 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |140946608 |215551248 |
**GPU Texture Memory Usage**: |851158593 |1154632851 |
**GPU Virtual Memory Usage**: |855352897|1183992979|
**Triangle Count**: |207650 |847993 |
**Triangle Rate**: |12214705 |49881941 |
**API Drawcall Count**: |165 |274 |
**Drawcall Count**: |2978 |317 |
**Drawcall Rate**: |175176 |18647 |
**State Changes Texture Count**:|336 |328 |
**Pipeline Count**: |64 |39 |
**Item Opaques**: |255 |459 |
**Item Translucents**: |103 |64 |
**Item Lights**: |11 |44 |
**Timing Opaques**: |0.824 |1.493 |
**Timing Translucents**: |0.126 |0.122 |
**Timing Lighting**: |0.016 |0.023 |
**Render Frame**: |1.437 |3.017 |

DK2

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |75 |75 |
**Present Rate**: |75 |75 |
**Present New Rate**: |75 |75 |
**CPU Buffer Count**: |2817 |4323 |
**GPU Buffer Count**: |932 |1436 |
**CPU Memory Usage**: |37423952 |66114640 |
**GPU Memory Usage**: |20904048 |46278768 |
**CPU Texture Count**: |337 |307 |
**GPU Texture Count**: |288 |276 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |61451440 |99159312 |
**GPU Texture Memory Usage**: |1136703960 |1312732618 |
**GPU Virtual Memory Usage**: |1140898264|1509864906|
**Triangle Count**: |435886 |1714013 |
**Triangle Rate**: |33529692 |131847153 |
**API Drawcall Count**: |135 |287 |
**Drawcall Count**: |5628 |646 |
**Drawcall Rate**: |432923 |49692 |
**State Changes Texture Count**:|285 |348 |
**Pipeline Count**: |57 |38 |
**Item Opaques**: |196 |475 |
**Item Translucents**: |99 |73 |
**Item Lights**: |8 |45 |
**Timing Opaques**: |0.731 |1.373 |
**Timing Translucents**: |0.136 |0.133 |
**Timing Lighting**: |0.017 |0.019 |
**Render Frame**: |1.451 |2.813 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass
**Test 11**|Test Tablet in 2D and 3D|Will let others concentrate on this

Additional testing;
Entity script server (ESS) - functions as expected, excess CPU load on domains with large model counts corrected.  While still needing refinement (as has been discussed elsewhere), it now seems much more ready for RC inclusion.

CPU consumption remains consistent with past RC, no change seen of concern.

For things I'm able to fully test this PR seems a much better attempt at RC than last. 👍

**Comment by Nex-Pro** [comment]
Will test this win 10 and Vive

**Comment by Nex-Pro** [comment]
Overall I think this is a PASS for me.


### PR #9600 Beta Release 33

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive


## QA Test

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: **SUCCESS**
**localhost ATP Upload + Edit Result**: **SUCCESS**
**Echo Server Audio**: **SUCCESS**
**localhost 'harmonicOscillator.js' Result**: **SUCCESS**
**localhost 'reverbTest.js' Result**: **SUCCESS**
**localhost 'playaPerformanceTest.js' Result**: **SUCCESS**
**dev-playa 'playaPerformanceTest.js' Result**: **SUCCESS**
**dev-demo 'playaPerformanceTest.js' Result**: **SUCCESS** Used theatre.
**QA Pass**: **QA Pass** **SUCCESS**

**Additional Test Results + Observations**:

Two occasions left with stylii attached to hands.




Desktop

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2623 |4922 |2662
**GPU Buffer Count**: |760 |1490 |1007
**CPU Memory Usage**: |29267984 |91566960 |49557872
**GPU Memory Usage**: |14284080 |45312112 |34646128
**CPU Texture Count**: |243 |331 |211
**GPU Texture Count**: |184 |235 |169
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |98775680 |402068192 |60546400
**GPU Texture Memory Usage**: |665386468 |1134142362 |723203746
**GPU Virtual Memory Usage**: |665386468|1134142362|723203746
**Triangle Count**: |254248 |857856 |186013
**Triangle Rate**: |15890500 |53616000 |11625812
**API Drawcall Count**: |175 |269 |64
**Drawcall Count**: |2259 |312 |67
**Drawcall Rate**: |141187 |19500 |4187
**State Changes Texture Count**:|357 |311 |120
**Pipeline Count**: |53 |37 |33
**Item Opaques**: |272 |452 |73
**Item Translucents**: |58 |59 |8
**Item Lights**: |11 |46 |15
**Timing Opaques**: |1.304 |1.661 |0.379
**Timing Translucents**: |0.139 |0.05 |0.053
**Timing Lighting**: |0.02 |0.02 |0.025
**Render Frame**: |2.053 |2.835 |1.426

HMD:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |91
**Present Rate**: |89 |89 |89
**Present New Rate**: |89 |90 |90
**CPU Buffer Count**: |3298 |4253 |2906
**GPU Buffer Count**: |871 |870 |986
**CPU Memory Usage**: |42081104 |69866576 |42819952
**GPU Memory Usage**: |22616176 |22042736 |28665968
**CPU Texture Count**: |362 |320 |267
**GPU Texture Count**: |272 |183 |228
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |177762944 |480645856 |107831008
**GPU Texture Memory Usage**: |1143244676 |1129371800 |946133154
**GPU Virtual Memory Usage**: |1185187716|1171314840|988076194
**Triangle Count**: |528440 |1662927 |662928
**Triangle Rate**: |48040000 |166292700 |66292800
**API Drawcall Count**: |190 |271 |163
**Drawcall Count**: |4084 |614 |360
**Drawcall Rate**: |371272 |61400 |36000
**State Changes Texture Count**:|371 |289 |274
**Pipeline Count**: |60 |35 |41
**Item Opaques**: |275 |462 |255
**Item Translucents**: |108 |46 |43
**Item Lights**: |11 |41 |21
**Timing Opaques**: |1.084 |1.685 |1.021
**Timing Translucents**: |0.171 |0.046 |0.114
**Timing Lighting**: |0.027 |0.027 |0.053
**Render Frame**: |2.128 |3.374 |2.724



**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and do tutorial|**SUCCESS**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?|**SUCCESS**
**Test 5**|Switch avatar and make sure it does not crash|**SUCCESS** Several changes no problems
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|**SUCCESS**
**Test 8**|Enrure that you can distance grab|**SUCCESS**
**Test 9**|Bring up and edit an objects with hand controllers|**SUCCESS**
**Test 10**|Test PAL functionality|BASIC functions ok mute/ignore/volume
**Test 11**|Test Tablet in 2D and 3D|**SUCCESS**

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success - unable to connect to `dev-demo` as this not a failure of the PR however lacking permissions. Requesting again for permissions.


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |9 |
**CPU Buffer Count**: |2385 |1156 |
**GPU Buffer Count**: |761 |231 |
**CPU Memory Usage**: |28168656 |11991376 |
**GPU Memory Usage**: |18932336 |8531312 |
**CPU Texture Count**: |250 |63 |
**GPU Texture Count**: |192 |41 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |144558448 |55388624 |
**GPU Texture Memory Usage**: |582558451 |155481247 |
**GPU Virtual Memory Usage**: |582558451|155481247|
**Triangle Count**: |293549 |52192 |
**Triangle Rate**: |18346812 |4014769 |
**API Drawcall Count**: |174 |25 |
**Drawcall Count**: |2990 |22 |
**Drawcall Rate**: |186875 |1692 |
**State Changes Texture Count**:|325 |46 |
**Pipeline Count**: |54 |28 |
**Item Opaques**: |273 |205 |
**Item Translucents**: |64 |36 |
**Item Lights**: |11 |55 |
**Timing Opaques**: |1.084 |0.501 |
**Timing Translucents**: |0.138 |0.05 |
**Timing Lighting**: |0.014 |0.015 |
**Render Frame**: |1.662 |1.817 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success - unable to get into dev-demo not a failure of PR again requesting permissions.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|undefined

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
## QA Test - PASS WITH NOTES AT BOTTOM
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Some boxes still show up behind the lazers but with some clicking around they do finally become accessible to close via the lazer

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |275 |162 |191
**Present Rate**: |275 |166 |194
**Present New Rate**: |227 |117 |194
**CPU Buffer Count**: |2515 |3560 |1732
**GPU Buffer Count**: |738 |802 |493
**CPU Memory Usage**: |44870864 |67270992 |35018800
**GPU Memory Usage**: |18451824 |27766128 |11631984
**CPU Texture Count**: |231 |290 |142
**GPU Texture Count**: |182 |146 |95
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |112438448 |451284240 |132593200
**GPU Texture Memory Usage**: |642369748 |660980827 |335376271
**GPU Virtual Memory Usage**: |642369748|660980827|335376271
**Triangle Count**: |202739 |738461 |232540
**Triangle Rate**: |50684750 |123076833 |77513333
**API Drawcall Count**: |163 |241 |122
**Drawcall Count**: |1129 |390 |124
**Drawcall Rate**: |282250 |64999 |41333
**State Changes Texture Count**:|329 |266 |201
**Pipeline Count**: |67 |40 |38
**Item Opaques**: |255 |424 |161
**Item Translucents**: |96 |62 |37
**Item Lights**: |10 |49 |18
**Timing Opaques**: |0.65 |1.433 |0.42
**Timing Translucents**: |0.092 |0.102 |0.068
**Timing Lighting**: |0.017 |0.055 |0.021
**Render Frame**: |1.527 |3.682 |1.438

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Done
**Test 2**|Install a fresh copy of "Home' and do tutorial|Done
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Done
**Test 4**|Launch firework, on dev-playa, can other hear?|Yes
**Test 5**|Switch avatar and make sure it does not crash|Done
**Test 6**|Test group functions|Done
**Test 7**|Test Ambisonic audio with markeplace item|Done
**Test 8**|Enrure that you can distance grab|Done
**Test 9**|Bring up and edit an objects with hand controllers|Done
**Test 10**|Test PAL functionality|Done
**Test 11**|Test Tablet in 2D and 3D|Done but a note added below

*This is not a fail just a note on my part that I assume others ran into, in desktop mode the tablet appears in front of my body while the web/inner part appears behind my body. I am including a screen shot below.

hifi-snap-by-coal-on-2017-02-04_16-35-43

**Comment by Nex-Pro** [comment]
@coal I had already filed a bug report on that.  So it's all good. Thanks.

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift + Oculus Touch

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-bac5bd5.exe
## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** unable
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Unable to test harmonicOscillator.js. Otherwise, this smoke test seems to be a PASS.


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2345 |2252 |
**GPU Buffer Count**: |854 |942 |
**CPU Memory Usage**: |25253840 |24470608 |
**GPU Memory Usage**: |15919216 |19003504 |
**CPU Texture Count**: |238 |165 |
**GPU Texture Count**: |197 |140 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |84061360 |56642448 |
**GPU Texture Memory Usage**: |889258808 |678210641 |
**GPU Virtual Memory Usage**: |889258808|678210641|
**Triangle Count**: |519473 |528732 |
**Triangle Rate**: |47224818 |48066545 |
**API Drawcall Count**: |197 |134 |
**Drawcall Count**: |6006 |522 |
**Drawcall Rate**: |546000 |47454 |
**State Changes Texture Count**:|380 |200 |
**Pipeline Count**: |62 |41 |
**Item Opaques**: |282 |230 |
**Item Translucents**: |98 |64 |
**Item Lights**: |11 |52 |
**Timing Opaques**: |1.096 |0.686 |
**Timing Translucents**: |0.168 |0.057 |
**Timing Lighting**: |0.022 |0.012 |
**Render Frame**: |1.864 |1.547 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|unable
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|unable
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|unable
**Test 11**|Test Tablet in 2D and 3D|SUCCESS

NOTES:
- I'm able to open EDIT by toggling the EDIT icon on the tablet via the lasers, 
but using the lasers again on the EDIT icon will not close the EDIT window.
I can close the window by toggling the EDIT icon with the stylus, 
but the hand devices are not detected by the EDIT icon.

- I was unable to find anyone online during the time I was testing. Therefore all tests that required a second person, I was unable to perform.

**Comment by ZappoMan** [comment]
When I run this build - it starts up in Desktop mode at 2fps... when I switch the HMD it runs at 90hz, and then when I switch back to desktop it runs at 400fps... this is also true for the latest dev-download builds.

This seems broken.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40730c1d19376b455e8350d671696529372fd970 available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-40730c1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-40730c1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 725917af0d29615b0fdfdbd321f99d3ee9d5dfff available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-725917a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-725917a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1fc30435b210476f561c49db7870af345a9fdfd available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 725917af0d29615b0fdfdbd321f99d3ee9d5dfff available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-725917a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-725917a.dmg

**Comment by cozza13** [comment]
ok to test

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1fc30435b210476f561c49db7870af345a9fdfd available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.dmg

**Comment by Nex-Pro** [comment]
@ZappoMan  I've had the issue for a long time that when I switch to desktop the vsync is off. I then see anywhere up to 430 fps. 
 I'm sure I've reported this several times in the QA's. 
I can get vsync back by switching display to side-by-side then switch to desktop again.
 I had a conversation about this a couple of days ago with @PhilipRosedale

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1fc30435b210476f561c49db7870af345a9fdfd available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-d1fc304.dmg

**Comment by ZappoMan** [comment]
note: my comment above about bad (very low) fps was actually reproducing in the current beta as well - it turned out to be fixed with a video driver update

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d1d36e0f0a01881b2033052367b690aa8d061ad available at: https://gist.github.com/d58774fd66f8447aa78369f61e35bf48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-6d1d36e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9600-6d1d36e.dmg

**Pull request merged**
