### PR TITLE
Case 21893: Remove disabling of --url for Android.

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/21893/Enable-the-url-command-line-parameter-on-Android

Testing
1.  Verify that build runs on Android
2.  Verify that build runs on Quest
3.  Verify build runs on PC

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18463/HighFidelity-Beta-PR15287-171aebd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18463/HighFidelity-Beta-Interface-PR15287-171aebd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18463/HighFidelity-Beta-PR15287-171aebd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18463/HighFidelity-Quest-Beta-PR15287-171aebd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18463/HighFidelity-Beta-PR15287-171aebd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18463/HighFidelity-Beta-Interface-PR15287-171aebd.exe

**Comment by qaAdamSmith82** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18526/HighFidelity-Beta-PR15287-171aebd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18526/HighFidelity-Beta-Interface-PR15287-171aebd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18526/HighFidelity-Beta-PR15287-171aebd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18526/HighFidelity-Quest-Beta-PR15287-171aebd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18526/HighFidelity-Beta-PR15287-171aebd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18526/HighFidelity-Beta-Interface-PR15287-171aebd.exe

**Pull request merged**
