### PR TITLE
Port Avatar > Attachments to tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Dev Notes
- ComboBox.qml and TabletComboBox.qml have been refactored into a single ComboBox.qml file.
- AttachmentsDialog.qml and TabletAttachmentsDialog.qml use shared dialog content of AttachmentsContent.qml.
- ModelBrowserDialog.qml and TabletModelBrowserDialog.qml use shared dialog content of ModelBrowserContent.qml.
- There's a new TabletHeader.qml control used in a few dialogs for the tablet header.

**Comment by ctrlaltdavid** [comment]
Test Notes

Avatar Attachments dialog works in:
- Desktop window.
- HMD window.
- HMD tablet.

Dropdowns work in:
- Avatar Attachments.
- Other dialogs.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0fc45799ed1c8e768124110e8bb1fcd2f0ae4aa6 available at: https://gist.github.com/6e9365efe84f7cb8edb5f23dcf307eb3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-0fc4579.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-0fc4579.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4dd7667fd7e1708c0b980be309674ff454d06d39 available at: https://gist.github.com/6e9365efe84f7cb8edb5f23dcf307eb3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-4dd7667.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-4dd7667.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7504c124e40f3d86953951651bd0a7b3a8dfc7d8 available at: https://gist.github.com/6e9365efe84f7cb8edb5f23dcf307eb3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-7504c12.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-7504c12.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7504c124e40f3d86953951651bd0a7b3a8dfc7d8 available at: https://gist.github.com/6e9365efe84f7cb8edb5f23dcf307eb3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-7504c12.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9863-7504c12.dmg

**Pull request merged**
