### PR TITLE
Improve Translucent shapes global lighting with support for the ambient map reflection

### PR DESCRIPTION
**Pull request by samcake**
Added the specular lighting for translucent shapes using the ambient map provided with the global Light.

- refactor the shader code to share the same function for global Specular Lighting evaluation
- introduced enums in place of constants for the binding slots for resource of the shape shader

### CODE REVIEW

**Comment by samcake** [comment]
To Test:
checkout transparent surfaces and observe the reflection of the ambient map (or skybox map) according to the roughness (and metallic-ness) of the material.

The specular reflection on translucent surfaces should behave just like for opaques.
It s affected by the metallic and the roughness property of the material.

IN comparison, the current release doesn't do any reflection of the environment map on translucent surfaces

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52c403e980979c51cf0a0b787a1fa75d352e114e available at: https://gist.github.com/7316daa06c10dfcf6a2cf6d6ba5103cb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7796.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7796.dmg

**Comment by Nex-Pro** [comment]
Hi @samcake is there a particular model you want a comparison on ? If so, where ?

**Comment by samcake** [comment]
Hi Nex-pro
In the world called blue i have a bunch of transparent objects to look at
In the standard demo playa & cellscience let s make sure we didn t break
anything


Thanks

S

**Comment by Nex-Pro** [comment]
@samcake  I can't see any content at 0,0,0 in blue.

**Comment by samcake** [comment]
? Let me restart

**Comment by Nex-Pro** [comment]
@samcake  5 servers avatar ping -1

**Comment by samcake** [comment]
@Nex-Pro, it should work now no ?

**Comment by Nex-Pro** [comment]
@samcake  nothing, and now it says I am not connected

**Comment by Nex-Pro** [comment]
@samcake  question in slack

**Comment by kevinmthomas-carpool** [comment]
@Nex-Pro requested me to test as well as he is having connection issues with PR.

**Comment by bluetoe** [comment]
Cool stuff
hifi-snap-by-twa_hinkle-on-2016-04-29_14-13-40

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7796
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results:** Successful test of transparent surfaces and observation of the reflection of the ambient map according to the roughness (and metallic-ness) of the material.  Screen-shots included.
**Successful Logout/Crash:** Successful logout.

**Comment by samcake** [comment]
Can you also please in the 3 domains "demo", "playa" and "cellscience" making sure that nothing is broken (in particular in cellscience).

THanks

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7796
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** demo, playa, cellscience
**Additional Test Results:** Successful test and observation of the reflection of the ambient map according to the roughness (and metallic-ness) of the material.  Did an exhaustive run on ```cellscience``` and it worked as expected, no issues.
**Successful Logout/Crash:** Successful logout.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a5b32b59a74bd16aa32125d3a7b38048363c58d2 available at: https://gist.github.com/7316daa06c10dfcf6a2cf6d6ba5103cb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7796.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7796.dmg

**Comment by AlanZimmerman** [comment]
Based on the screenshots I saw above, I wanted to specifically test this in order to get a bright, discernable reflection of the ambient map on a sphere. After playing with lots of options, we did get a good result by setting the diffuse color to almost white. If the diffuse color is set to something else it profoundly diminishes the visibility and brightness of the ambient map.

hifi-snap-by-alan_-on-2016-05-02_12-27-21


In the attached  screenshot, (taken here: hifi://sandbox/4.09124,-75.233,507.595/0,-0.679618,0,0.733566 ,) the left column is metallic and right  is non-metallic. The alpha in each row is set higher in 30% increments. All of the objects have a hardness/gloss set to the maximum scalar value and all have a dark color set for the diffuse. The closest row is a duplicate of the farthest row, except with the diffuse color set to almost white.

**Pull request merged**
