### PR TITLE
replace the default avatar with the being of light

### PR DESCRIPTION
**Pull request by birarda**
- replaces the old default robot (RIP little buddy) with the being of light

### CODE REVIEW

**Comment by birarda** [comment]
To test:

- Download this PR build
- Clear your Interface settings
  - easiest way is to use `Developer - > Ask to Reset Settings`
  - NOTE: This will clear your Interface settings (other than auth) so make sure you know what that entails
- Confirm that your Avatar is now the being of light and not the robot
- Get another user with the same PR build to meet you in a domain - they should also see you as the being of light and not as the robot

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c59e9a1c484210162d3814a35950353fc76b3ab available at: https://gist.github.com/f3fe54d1cd985004a5a39ad5f746876b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7742.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7742.dmg

**Comment by hyperlogic** [comment]
Please merge master into this branch before merging, it will conflict with #7714

**Comment by birarda** [comment]
@hyperlogic already rebased because of that

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09a068e4726f6424c1843897dab0014b874520d8 available at: https://gist.github.com/f3fe54d1cd985004a5a39ad5f746876b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7742.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7742.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Manually removed interface.ini to be 100% sure.  I am being of light (eyerolls).

General smoke test = good.

QA Pass

**Pull request merged**
