### PR TITLE
use non-persistent settings to avoid lobby crash confusion

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40f7e683da4a19ce8dfb2d4e4a9824cd98c15999 available at: https://gist.github.com/5beb524c2a58af55ec22<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 862f26a0958e948fe407414aa7aabe9de53d037f available at: https://gist.github.com/5beb524c2a58af55ec22<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69f0c50a3cc2f0e4b87615feb8a459cb0772ae42 available at: https://gist.github.com/5beb524c2a58af55ec22<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12cacad8f8a429d0201aa8c1153369bbd2b554d3 available at: https://gist.github.com/5beb524c2a58af55ec22<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4580.dmg

**Comment by Atlante45** [comment]
I doubt it's related to that PR in particular, but when I load the lobby, the music goes to total white noise after about 10 sec.

**Comment by Atlante45** [comment]
merging since this PR is unrelated to the issue mentioned.

**Pull request merged**
