### PR TITLE
Particles emitter fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Texture is updated immediately you edit the textures URL.
- "No preview available" is displayed for ATP textures.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) When you change the texture of a particle emitter in the Create app's particle properties tab, both the image of the texture in the tab and the texture being emitted by the emitter immediately update while you're still in the tab. And the change in the emitter is seen by other people.

2) You can use images from the ATP server as particle emitter textures.
	The texture is used in the emitter.
	"No preview available" is displayed in the image preview in the particles UI.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4820/HighFidelity-Beta-PR11788-c53c356842090db17e55cb39595f3e2394e14afa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4820/HighFidelity-Beta-PR11788-c53c356842090db17e55cb39595f3e2394e14afa.exe

**Comment by Nex-Pro** [comment]
### PASS

When you change the texture of a particle emitter in the Create app's particle properties tab, both the image of the texture in the tab and the texture being emitted by the emitter immediately update while you're still in the tab. **SUCCESS**
And the change in the emitter is seen by other people. **SUCCESS**

You can use images from the ATP server as particle emitter textures.
The texture is used in the emitter. **SUCCESS**
"No preview available" is displayed in the image preview in the particles UI. **SUCCESS**

**Pull request merged**
