### PR TITLE
fixing keyboard mallets dimensions (Master)

### PR DESCRIPTION
**Pull request by danteruiz**
Forgot to create a PR for the master branch when I fixed this in the RC - https://github.com/highfidelity/hifi/pull/14447 - RC76 PR

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14447

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15439/HighFidelity-Beta-PR14481-9cc896c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15439/HighFidelity-Beta-PR14481-9cc896c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15439/HighFidelity-Beta-Interface-PR14481-9cc896c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15439/HighFidelity-Beta-PR14481-9cc896c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15439/HighFidelity-Beta-Interface-PR14481-9cc896c.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
