### PR TITLE
hide desktop windows when switching into HMD mode

### PR DESCRIPTION
**Pull request by druiz17**
This PR makes sure to hide any topLevelWindow on the HUD when switching to HMD mode

ticket - https://highfidelity.fogbugz.com/f/cases/13686/Opening-Asset-Browser-in-desktop-and-switching-to-HMD-causes-unexpected-behavior

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- start in desktop mode
- while in your sandbox open the asset browser
- switch into HMD mode and the asset browser should not appear on you HUD
- switch back to Desktop mode and make sure you can still open up the asset browser

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8496/HighFidelity-Beta-PR12787-475a3a29acdd36fe72270dde3f23cd9d3ac4a3ca.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8496/HighFidelity-Beta-PR12787-475a3a29acdd36fe72270dde3f23cd9d3ac4a3ca.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
When going into HMD and then back into desktop, the HUD disappears and requires a restart for it to return.

[Files.zip](https://github.com/highfidelity/hifi/files/1877924/Files.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8513/HighFidelity-Beta-PR12787-31783726a8f7fae4b55c1a31b2143058760a097d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8513/HighFidelity-Beta-PR12787-31783726a8f7fae4b55c1a31b2143058760a097d.exe

**Comment by druiz17** [comment]
@conklin94122 this issue @qlimnavarro posted also happens in master. This is a seperate issue that should be addressed in a different PR.

**Pull request merged**
