### PR TITLE
Batch parameters in GeometryCache

### PR DESCRIPTION
**Pull request by huffman**
This adds a batch parameter to the GeometryCache::render* calls to help begin the process of moving completely to gpu::Batch and removing all gl* calls.  This PR is to merge into branch team-teaching.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 776955b04026493fe7931ed826f553284ad38df8 available at: https://gist.github.com/28705561200a43484256<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 776955b04026493fe7931ed826f553284ad38df8 available at: https://gist.github.com/08c18c337dee979a8ab9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.dmg

**Comment by PhilipRosedale** [comment]
Can this get a description of what it will change in HF?

**Comment by Atlante45** [comment]
@huffman In DeferredLightingEffect you are only passing the batch to the GeometryCache once.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 776955b04026493fe7931ed826f553284ad38df8 available at: https://gist.github.com/28705561200a43484256<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4894.dmg

**Comment by Atlante45** [comment]
@huffman Ok, I couldn't sleep so I spent some time trying to figure out the issue.
Got a patch, turns out we had to register those gl* calls in the batch and more importantly port the simple program to be added in the batch.

You should be able to pull the patch from [here](https://github.com/highfidelity/hifi/compare/master...Atlante45:huffman-batch-param?expand=1) with:
`git pull https://github.com/Atlante45/hifi.git huffman-batch-param`

**Comment by huffman** [comment]
@PhilipRosedale Sorry about that, this was probably a little confusing coming out of the blue; I've updated the description.  This is a team-teaching task and is a PR to merge into the team-teaching branch, NOT master, so this won't affect any release builds until all of the work has been done.  This is only one part of a larger task that multiple people are working on.

**Comment by ZappoMan** [comment]
tested on mac... as expected everything works as usual.

**Pull request merged**
