### PR TITLE
Beta Release 39 - Includes up to Developer Release 6457

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

 - Fix for resource downloads getting capped
 - **Broadcast and announcements** 
 - Fix deadlock from minimizing 
 - Prevent possible crash in texture buffering thread 
 - Fixing the the mip gpu copy for compressed format texture in GL41Backend 
 - Fix event enum
 - **expose more bullet constraints to javascript: slider, ball-socket, cone-twist ** https://github.com/highfidelity/hifi/pull/10332
 - ** spring action can now be rotational, translational, or both **
 - **spring action can now have targets relative to another entity **
 - Fix numeric keys not displaying in social media sharing dialogs 
 - PAL WebView is now a TabletWebView 
 - Fix tablet webview showing incorrect url. 
 - Guard against bad hinge-constraint settings 
 - Fix deadlock from accessing an initializing tablet 
 - Fix reliability of keyboard enabling in tablet Web pages 
 - Don't warn that recording didn't start playing if you stop it 
 - Grab is driven by timer rather than update, load tablet model with high priority 
 - Migrate Avatar rendering code to library 
 - Fix OBJ material loading not working over ATP
 - Fixing the by region update transfer of the compressed texture
 - Store irradiance in cached KTX files 
 - Expire announcement when announcer leaves.
 - Lots of Snapshot app improvements
 - Removing logspam on toggling scripts window 
 - Feat/normal map compression
 - Announcement Card visual tweaks. 
 - "Set Availability" UI changes 
 - Fix progressive loading of KTX skybox textures
 - Fix -- dont send non-entity edits to entity-server 
 - Fixing potential crashes when loading invalid KTX cached textures

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37f339858ea9ea6840eb17ab4c9292b63fcff4ba available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-37f3398.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-37f3398.dmg

**Comment by Menithal** [comment]
Was there a change to where the eyes point for Blender Avatars?
https://gyazo.com/8cd384440ff75cd4b66d03ec36357b9b
https://gyazo.com/1596a3d0abae71923f5f5e9cca60fe02

Also the animations seem to be played back at a much higher framerate than previous.
https://gyazo.com/2c972b0881afa0571d7e47cf91da5de1

**Comment by kevinmthomasse** [comment]
testing

**Comment by cozza13** [comment]
@Menithal thanks for that I will get it on the list to get fixed before this goes out.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS however initially I was UNABLE to exit interface when I clicked on the ```X``` or ```File-Exit```.  I had to go into ```Task Manager``` and manually kill the process.  I was unable to reproduce the bug again after 5 more attempts.  ```ATTENTION OTHER TESTERS - PLEASE CHECK FOR THIS BUG IF YOU DO NOT HAVE THIS ISSUE IT IS AN ISOLATED ISSUE HOWEVER IF YOU ARE EXPERIENCING THIS MIGHT CAUSE THIS A FAIL```
**Additional Test Results + Observations**: Success.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |398 |217 |216
**Present Rate**: |389 |217 |223
**Present New Rate**: |198 |209 |108
**CPU Buffer Count**: |507 |1635 |1197
**GPU Buffer Count**: |237 |499 |366
**CPU Memory Usage**: |5750512 |20338128 |12988528
**GPU Memory Usage**: |4494768 |12191152 |7087536
**CPU Texture Count**: |74 |95 |114
**GPU Texture Count**: |65 |79 |73
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |169693104 |132162820 |110823064
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |70348 |382626 |176409
**Triangle Rate**: |23449333 |95656500 |22051125
**API Drawcall Count**: |43 |119 |89
**Drawcall Count**: |43 |115 |93
**Drawcall Rate**: |14333 |28750 |11625
**State Changes Texture Count**:|70 |122 |88
**Pipeline Count**: |28 |30 |27
**Item Opaques**: |30 |259 |126
**Item Translucents**: |8 |26 |5
**Item Lights**: |2 |47 |15
**Timing Opaques**: |0.117 |0.889 |0.287
**Timing Translucents**: |0.018 |0.023 |0.017
**Timing Lighting**: |0.011 |0.015 |0.015
**Render Frame**: |0.6 |1.988 |0.829


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by ZappoMan** [comment]
Isn't this 39?

**Comment by Nex-Pro** [comment]
Testing this now.

**Comment by Nex-Pro** [comment]
### #10399 QA. Beta Release 38 pass 3

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.


### PASS apart from 4x repro'd crashes at dev-welcome, HMD and desktop. And other unable to hear firework at dev-playa.

Splats posted.

## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**:

Previously I was able to re-cap render rates at 60 for desktop after changing via 3d side by side.  This would slam the frame rate back from up to 400fps down to 60.
This doesn't seem to work anymore. ( same in master now. )
Now I have to restart interface.
With interface not in focus I'm seeing frame rate of 15 and render rate of ~750 at home sandbox. Not good. Aren't we supposed to be saving gpu/cpu ?

Render rates below were fine but problem with stats harvesting persists.
Here they show as zero  but were 89~90.


### HMD Stats:

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |89 |90 |
**Present New Rate**: |79 |0 |
**CPU Buffer Count**: |1723 |30954 |
**GPU Buffer Count**: |219 |845 |
**CPU Memory Usage**: |17412944 |172729360 |
**GPU Memory Usage**: |3573168 |31421872 |
**CPU Texture Count**: |196 |233 |
**GPU Texture Count**: |70 |158 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |289144752 |604923632 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |35618 |1516573 |
**Triangle Rate**: |3561800 |137870272 |
**API Drawcall Count**: |30 |207 |
**Drawcall Count**: |134 |690 |
**Drawcall Rate**: |13400 |62727 |
**State Changes Texture Count**:|45 |237 |
**Pipeline Count**: |31 |36 |
**Item Opaques**: |20 |371 |
**Item Translucents**: |8 |34 |
**Item Lights**: |1 |40 |
**Timing Opaques**: |0.107 |1.06 |
**Timing Translucents**: |0.022 |0.028 |
**Timing Lighting**: |0.014 |0.014 |
**Render Frame**: |0.633 |2.07 |

Desktop stats:

WOAH !

See screengrab.


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|FAIL tried this from two clients failed on both. Each could hear own launch not other.
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Untested yet
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|PASS
**Test 9**|Bring up and edit an objects with hand controllers|Pass
**Test 10**|Test PAL functionality|undefined
**Test 11**|Test Tablet in 2D and 3D|Generally seems fine. 


Show audio level meter in HMD 2d mode does not work. Setting does not persist.

Help pane now working well for all pages.

Crashing while yawing with hand controllers and desktop at dev-welcome  4x splats posted.

### Unable to cap frame rate ( vsync )
hifi-snap-by--on-2017-05-08_13-49-28

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a27dae884d86862f3923634eeb7fdb4f5b8606f available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1a27dae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1a27dae.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a27dae884d86862f3923634eeb7fdb4f5b8606f available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1a27dae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1a27dae.dmg

**Comment by Nex-Pro** [comment]
Re-Testing Tutorial as per @themelissabrown

**Comment by Nex-Pro** [comment]
I uninstalled previous build and removed appropriate folders from local and roaming.

During the tutorial I had extremely laggy teleport beams. More than 1.25 seconds delay on each attempt to re-position the target. 
After completing the tutorial I restarted using the teleport in the garden.
Same result.

I moved down to the build platform/sandbox area and the problem persisted.

I restarted interface and the problem cleared.

I then completely uninstalled the build and removed the folders from local and roaming.

Repeated above sequence and had same issue. This looks like a reproducible first-run issue.

**Comment by Nex-Pro** [comment]
going to repeat above.

**Comment by Nex-Pro** [comment]
ok tried that a third time and although slightly better it definitely clears up on restarting interface. One restarted the TP target can be moved smoothly and quickly.

Tested on i7 Win10 and Vive. Controller charge level good.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1414254fc29573f65f89f114e62b57a7159edfd4 available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1414254.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-1414254.dmg

**Comment by PhilipRosedale** [comment]
I am seeing the same problem Piper is reporting: 

On the first run through the tutorial, when I get to the teleport section, the movement of the teleport target on the floor is hugely lagged - 1FPS or worse.  If I re-start interface while in my tutorial back yard, the problem is fixed.  

Do we see this problem with the current release, or on other machines?  I would think this would stop some new users from completing the tutorial or getting to welcome.

**Comment by PhilipRosedale** [comment]
Well crap - I also just downloaded the current release - 6435 - and it does NOT have the slow teleport beam problem.  So this is RC definitely a regression from release.

**Comment by PhilipRosedale** [comment]
My desktop MSi does NOT exhibit this problem.    My home machine does the same as Pipers.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9646569630f425f77f13b669ed1014934baebc85 available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-9646569.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-9646569.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6720c0c02b94184244692fb70f1d838d90599a39 available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-6720c0c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-6720c0c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91d439442d5089ff5697912790d02ff1f77add0c available at: https://gist.github.com/5775661be2abe0bd30b76f6ed792b50f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-91d4394.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10399-91d4394.dmg

**Comment by OmegaHeron** [comment]
Sandbox issue, never ending messages posted to AC log.  Removing script atp:/ACAudioSearchAndInject_tutorial.js stops.  Looks like scripted agent is triggering?

`[05/15 11:59:36] [DEBUG] [hifi.avatars] [6868] [avatar-mixer] Ignoring late identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identityUpdatedAt ( 1494863903033573 ) is greater than identity.updatedAt - clockSkew ( 1494863902016722 - -77 )`
`[05/15 11:59:37] [DEBUG] [hifi.avatars] [6868] [avatar-mixer] Ignoring late identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identityUpdatedAt ( 1494863903033573 ) is greater than identity.updatedAt - clockSkew ( 1494863902016722 - -77 )`
`[05/15 11:59:38] [DEBUG] [hifi.avatars] [6868] [avatar-mixer] Ignoring late identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identityUpdatedAt ( 1494863903033573 ) is greater than identity.updatedAt - clockSkew ( 1494863902016722 - -77 )`
`[05/15 11:59:39] [DEBUG] [hifi.avatars] [6868] [avatar-mixer] Ignoring late identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identityUpdatedAt ( 1494863903033573 ) is greater than identity.updatedAt - clockSkew ( 1494863902016722 - -22 )`
`[05/15 11:59:40] [DEBUG] [hifi.avatars] [6868] [avatar-mixer] Ignoring late identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identityUpdatedAt ( 1494863903033573 ) is greater than identity.updatedAt - clockSkew ( 1494863902016722 - -22 )`

**Comment by OmegaHeron** [comment]
Is it expected/intended behavior that (In HMD mode) Tablet disappears on domain change *then* briefly flashes in front of agent then disappears again on arrival?

It's a bit annoying to have it flash in front on each domain change.

**Comment by OmegaHeron** [comment]
In PAL, user details -- I've never understood logic where you have info page for user and, at top, you have options back and close.  Back does nothing, unless you've looked at another user which takes you back to previous viewed user info.  It's a *weird* context -- back "feels" like it should take you back to PAL list not back to another user you might have viewed info on....  it's just clunky.

Also -- should there be some sort of shading/button effect or *something* over back/close options?  Again - it simply looks odd.

palcap1

**Pull request merged**
