### PR TITLE
JSDoc fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9406/HighFidelity-Beta-PR13076-3febdcb141d540075c09739efae715d7543a1e14.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9406/HighFidelity-Beta-Interface-PR13076-3febdcb141d540075c09739efae715d7543a1e14.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9406/HighFidelity-Beta-PR13076-3febdcb141d540075c09739efae715d7543a1e14.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9406/HighFidelity-Beta-Interface-PR13076-3febdcb141d540075c09739efae715d7543a1e14.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9462/app_13076_PR_e95c38d939235d6dbe33a94af6f348927077d8c6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9462/HighFidelity-Beta-PR13076-e95c38d939235d6dbe33a94af6f348927077d8c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9462/HighFidelity-Beta-Interface-PR13076-e95c38d939235d6dbe33a94af6f348927077d8c6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9462/HighFidelity-Beta-PR13076-e95c38d939235d6dbe33a94af6f348927077d8c6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9462/HighFidelity-Beta-Interface-PR13076-e95c38d939235d6dbe33a94af6f348927077d8c6.exe

**Pull request merged**
