### PR TITLE
Several QML fixes

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by jherico** [comment]
https://app.asana.com/0/27650181942747/92966062858846
https://app.asana.com/0/27650181942747/93241442947131
https://app.asana.com/0/27650181942747/92628920509324

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa23e2023efdfb29cccbb3933c1bdaf78a03862d available at: https://gist.github.com/22fda7187ef226e97e8d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7180.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7180.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa23e2023efdfb29cccbb3933c1bdaf78a03862d available at: https://gist.github.com/22fda7187ef226e97e8d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7180.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7180.dmg

**Comment by OmegaHeron** [comment]
Tested windows 7.  It allows edit properties to be positioned in usable location and persists it, but, you have to either find and delete your interface settings or manually edit.  Starting with no interface.ini places edit tools window at 120,120.  A more elegant solution than saying destroy or edit your interface.ini to get edit tools usable again would be a detection window is badly placed or a one shot menu item to force to sane location.  In so far as it being possible to posit edit tool window proper and persist it, this passes.  No crash seen on close after many open/close cycles.  Did not test Window.Confirm() portion.

**Pull request merged**
