### PR TITLE
fix osx shadows

### PR DESCRIPTION
**Pull request by sethalves**
- fix shadow shader compilation on osx

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- enable shadows and confirm that they act as they do in master

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7479/app_12493_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7479/HighFidelity-Beta-PR12493-59bd05aa554ad6d433d50edae5b223a400a0765f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7479/HighFidelity-Beta-PR12493-59bd05aa554ad6d433d50edae5b223a400a0765f.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Here are our results thus far, we're unsure if it's a pass or fail.

Shadows on Master:
master shadows on eschatology

Shadows on PR12493:
pr12493 shadows on eschatology

Please advise!

**Comment by SamGondelman** [comment]
@Qliemillar That looks right to me but it's a little hard to tell in Eschatology because of the big trees.  Can you try a different domain where there's more light and just make sure you can see your avatar's shadow?  Thank you!

**Comment by Qliemillar** [comment]
Checked dev-welcome and the local sandbox. Tester could not see his own shadow, but shadows in general were improved. In addition, in the local sandbox, the Tester seemed to have a shadow 'over' him, almost like a zone that would move where he would move. 

See attached video:
https://drive.google.com/open?id=1j8Lnhod-bZlPSiUt152275HkzU9RnKJA

Here are a couple additional screenshots in dev-welcome for shadow comparison: 

Master:
master shadows on dev-welcome

PR12493:
pr12493 shadows on dev-welcome

**Comment by SamGondelman** [comment]
Gonna merge this because it fixes the shader compilation and I'll file a bug for what you're seeing.

**Pull request merged**
