### PR TITLE
MS20925: Oculus login button not appearing

### PR DESCRIPTION
**Pull request by wayne-chen**
MS#[20925](https://highfidelity.manuscript.com/f/cases/20925/Oculus-login-Oculus-login-button-no-longer-appears-when-launching-through-the-oculus-store)

# TEST PLAN
- Setup metaverse environment to staging
- Get this PR uploaded into Oculus store
- Launch PR through Oculus store
- Make sure Oculus login button appears
- Ensure Oculus login flow is successful 
- Test cases:
https://highfidelity.testrail.net/index.php?/cases/view/35637
https://highfidelity.testrail.net/index.php?/cases/view/40465

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16931/HighFidelity-Beta-PR14818-03789e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16931/HighFidelity-Beta-PR14818-03789e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16931/HighFidelity-Beta-Interface-PR14818-03789e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16931/HighFidelity-Beta-PR14818-03789e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16931/HighFidelity-Beta-Interface-PR14818-03789e0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17027/HighFidelity-Beta-PR14818-03789e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17027/HighFidelity-Beta-PR14818-03789e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17027/HighFidelity-Beta-Interface-PR14818-03789e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17027/HighFidelity-Beta-PR14818-03789e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17027/HighFidelity-Beta-Interface-PR14818-03789e0.exe

**Comment by jakram** [comment]
currently testing

**Pull request merged**
