### PR TITLE
Beta Release 9 - including up to Development Release 4824

### PR DESCRIPTION
**Pull request by ZappoMan**
- Fix dice tutorial script
- Move Toybox domain to an S3 production bucket
- Fix crash in AssetClient

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5dadfa9e7eed23a658f709dea41b180a30103a27 available at: https://gist.github.com/4752b3629530710192a644686b44cef2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7801.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7801.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7801
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, music, cellscience
**Smoke Test Results:** Partially successful test.

                                  |localhost |music    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |53.00     |58.26    |58.04      
Present Rate:                     |60.00     |60.00    |60.00       
Present New Rate:                 |52.98     |59.97    |60.00      
Render Stats Num Buffers:         |6317      |3874     |2732        
Render Stats gpu::Buffer Memory:  |57.3Mb    |48.8Mb   |26.5Mb      
Render Stats Num Textures:        |294       |394      |102          
Render Stats gpu::Texture Memory: |1009.7Mb  |764.9Mb  |317.9Mb     
Render Stats Triangles:           |592k      |719k     |358k       
Render Stats Drawcalls:           |928       |426      |178         
Render Stats State Changes:	  |282       |508      |100          
Render Stats Items:               |350       |517      |416        
Render Stats Timing:              |69.9ms    |32.1ms   |13.4ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |298Mb     |298Mb    |298Mb       
GPU-Z Memory Used		  |3171Mb    |3626Mb   |3062Mb      
GPU-Z Memory Load		  |27%       |26%      |19%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Failure.  No reverberation effect of any kind.  Nothing specific revealed in log file.  Log file attached for deeper inspection.  Attempted to reload several times and reloaded Interface twice however same result.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**music ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** Performance was very good overall.  The timing values in ```renderStats.js``` were elevated but no visible effect on performance.  Enclosed are the results of loading ```reverbTest.js``` - ```[05/01 23:26:53] [DEBUG] Done downloading script at: "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js"
[05/01 23:26:53] [DEBUG] Logging activity "loaded_script"
[05/01 23:26:53] [DEBUG] Loading script at  QUrl("http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/cookies.js")
[05/01 23:26:53] [DEBUG] Finished loading: atp:/kdancefloor10.fbx/kdancefloor10.fbm/Blue.png
[05/01 23:26:53] [DEBUG] Finished loading: atp:/kdancefloor10.fbx/kdancefloor10.fbm/Red.png
[05/01 23:26:53] [DEBUG] Finished loading: atp:/kdancefloor10.fbx/kdancefloor10.fbm/Green.png
[05/01 23:26:53] [DEBUG] Finished loading: atp:/kdancefloor10.fbx/kdancefloor10.fbm/Yellow.png
[05/01 23:26:53] [DEBUG] script:print()<< Reverb is ON.
[05/01 23:26:53] [DEBUG] script:print()<< creating panel at x: 10 y: 160
[05/01 23:26:56] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 713 elapsedMovingAverage: 2 maxElapsed: 195690 maxElapsedAverage: 929 samples: 1519432
[05/01 23:27:01] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 934 elapsedMovingAverage: 2 maxElapsed: 195690 maxElapsedAverage: 929 samples: 1853182
[05/01 23:27:06] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 47 elapsedMovingAverage: 3 maxElapsed: 195690 maxElapsedAverage: 929 samples: 2210012
[05/01 23:27:07] [DEBUG] Reload script http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js
[05/01 23:27:07] [DEBUG] Delete script from cache: "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js"
[05/01 23:27:07] [DEBUG] stopping script... QUrl("http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js")
[05/01 23:27:07] [DEBUG] script:print()<< Reverb is OFF.
[05/01 23:27:07] [DEBUG] Script Engine shutting down (destructor) for script: "reverbTest.js"
[05/01 23:27:07] [DEBUG] Done downloading script at: "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js"
[05/01 23:27:07] [DEBUG] Logging activity "loaded_script"
[05/01 23:27:07] [DEBUG] Loading script at  QUrl("http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/cookies.js")
[05/01 23:27:07] [DEBUG] script:print()<< Reverb is ON.
[05/01 23:27:07] [DEBUG] script:print()<< creating panel at x: 10 y: 160
[05/01 23:27:11] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 73 elapsedMovingAverage: 2 maxElapsed: 195690 maxElapsedAverage: 929 samples: 2568352
[05/01 23:27:16] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 6 elapsedMovingAverage: 3 maxElapsed: 195690 maxElapsedAverage: 929 samples: 2865870
[05/01 23:27:21] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 196 elapsedMovingAverage: 3 maxElapsed: 195690 maxElapsedAverage: 929 samples: 3204484
[05/01 23:27:26] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 568 elapsedMovingAverage: 3 maxElapsed: 195690 maxElapsedAverage: 929 samples: 3470928
[05/01 23:27:31] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 2024 elapsedMovingAverage: 3 maxElapsed: 195690 maxElapsedAverage: 929 samples: 3766282
[05/01 23:27:36] [DEBUG] Present thread shutdown
[05/01 23:27:36] [DEBUG] QTWEBENGINE_REMOTE_DEBUGGING = "false"```  Attaching log for deeper analysis.
**Successful Logout/Crash:** Successful logout.
localhost performance
music performance
cellscience performance
[hifi-log.txt](https://github.com/highfidelity/hifi/files/244483/hifi-log.txt)

**Comment by Nex-Pro** [comment]
**PR Build: #7801**
**Testing Architecture: Desktop 16gb nvidia gtx770 2gb**
**Testing OS: Win10 64** 
**Testing Locations: playa, cellscience, forum, localhost**
**Smoke Test Results:**   

                                  | playa | cellscience | forum   
----------------------------------|-------|-------------|--------
Render Rate:                      | 60.00    |  ~58       |  53-58        
Present Rate:                     | 60.00 |  60.00  |   60.00          
Simrate:                          | 60.00 |  ~57      |     ~56       
Render Stats Num Buffers:         | 6279  |   4788   |  5101       
Render Stats gpu::Buffer Memory:  | 94.5  |    23.1  | 50.2         
Render Stats Num Textures:        |  279  |  67      | 289      
Render Stats gpu::Texture Memory: |16368.8|  382.8  |  761.1    
Render Stats Triangles:           |  1236k|  1177k      |  564k      
Render Stats Drawcalls:           |  289  |  336       |  460      
Render Stats Items:               | 379   |  1116       | 433          

**sandbox ‘createtestblocks.js’ Result: Partial success. When thown blocks act as expected.  Seemed difficult to control blocks via grab.js compared to last time I tried, jumpy**
**sandbox Import FBX Result:Import success. Subsequent manipulation via grab.js rather erratic. Michelle also observed jittery behaviour**
**sandbox ‘harmonicOscillator.js’ Result:Reasonably smooth but not like butter.**
**sandbox Echo Server Audio Result: Success**
**sandbox ‘reverbTest.js’ Result:**
**Additional Test Results Requested:**
**Successful Logout/Crash (If  A Crash Occurs, Attach ‘hifi-log.txt’): Success clean exit.**

**Comment by Nex-Pro** [comment]
@kevinmthomas-carpool  is that the 5th. amendment ?

**Pull request merged**
