### PR TITLE
Beta Release 63.1 - hotfix

### PR DESCRIPTION
**Pull request by Atlante45**
- This hotfix resolves a packaging issue that added an incorrect component during the custom install process.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6735/app_12298_PR.apk

**Comment by Atlante45** [comment]
## Test Plan:
- Install the current release
- Rename `C:\Program FIles\High Fidelity` to `C:\Program FIles\High Fidelity - PR12298`
- There should be a folder named `client` inside `High Fidelity - PR12298`
- Install the PR build
- The `client` folder should have disappeared.
- There should be a file named `crashpad_handler.exe` inside `High Fidelity - PR12298`
- Make sure Interface starts up and connects to the local domain.
- Force crash interface with the `Developer>Crash` menu options and have someone verify the crash was filed.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6735/HighFidelity-Beta-PR12298-97729e8f410f1fdbcae09539a7ac0286c24d24af.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6740/app_12298_PR.apk

**Comment by conklin94122** [comment]
Waiting for Ryan to get a mac build he can test before passing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6740/HighFidelity-Beta-PR12298-97729e8f410f1fdbcae09539a7ac0286c24d24af.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6740/HighFidelity-Beta-PR12298-97729e8f410f1fdbcae09539a7ac0286c24d24af.dmg

**Pull request merged**
