### PR TITLE
MS14559: Fix sometimes being unable to click on 'Nearby' orb when sending Gift/HFC

### PR DESCRIPTION
**Pull request by zfox23**
Hopefully fixes [MS14559](https://highfidelity.fogbugz.com/f/cases/14559/Clicking-on-a-nearby-orb-when-sending-money-or-gifts-to-someone-nearby-sometimes-yields-no-result), which is a bug that occurs when trying to send HFC/Gifts to someone Nearby which prevents a user from clicking on the Nearby orb.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9240/HighFidelity-Beta-PR13019-fc324f67bd198500f1f445c37f15f8751e279708.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9240/HighFidelity-Beta-Interface-PR13019-fc324f67bd198500f1f445c37f15f8751e279708.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9240/HighFidelity-Beta-PR13019-fc324f67bd198500f1f445c37f15f8751e279708.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9240/HighFidelity-Beta-Interface-PR13019-fc324f67bd198500f1f445c37f15f8751e279708.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Stopped Testing

**Comment by qlimnavarro** [comment]
Stopped Testing

**Pull request merged**
