### PR TITLE
Case21085 - Changing domains with scripting APIs not working

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17166/HighFidelity-Beta-PR14886-e6b2c89.apk

**Comment by roxanneskelly** [comment]
Test Plan...
1) type a hifi:// address like hifi://dev-welcome into the goto app.  Validate you go to dev-welcome

2) in the scripts console, type:
Window.location="hifi://<anotherdomain>";
Hit return and validate you go to that domain.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17170/HighFidelity-Beta-PR14886-d9858bc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17170/HighFidelity-Beta-PR14886-d9858bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17170/HighFidelity-Beta-Interface-PR14886-d9858bc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17170/HighFidelity-Beta-PR14886-d9858bc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17170/HighFidelity-Beta-Interface-PR14886-d9858bc.exe

**Pull request closed without merging**
