### PR TITLE
Fix blurry tablet if overlay is drawing

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/16386/HMD-Create-Menu-List-Becomes-blurry

Test plan:
- Bring up the tablet.  Go to the list tab.  Click any entity.  The tablet should not become blurry.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11063/HighFidelity-Beta-PR13523-773efe8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11063/HighFidelity-Beta-PR13523-773efe8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11063/HighFidelity-Beta-Interface-PR13523-773efe8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11063/HighFidelity-Beta-PR13523-773efe8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11063/HighFidelity-Beta-Interface-PR13523-773efe8.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tablet is no longer blurry

**Pull request merged**
