### PR TITLE
Automatically show address bar after disconnected for X seconds

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 26b9da7eeff2ab2da9b16a894d3fa30407e649ce available at: https://gist.github.com/36ab5b2054f936db9edddaf84b44df1b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8368-26b9da7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8368-26b9da7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d775a92dabf9f0e6b530f1abbf6d0fdd61dc035d available at: https://gist.github.com/36ab5b2054f936db9edddaf84b44df1b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8368-d775a92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8368-d775a92.dmg

**Comment by huffman** [comment]
This PR will make it so that the address bar will pop up if you've been disconnected from a server for more than 5 seconds.

To test:

1. Go to your home server
2. Shut down your home server (you should get disconnected)
3. Ensure that after 5 seconds the address bar comes up
4. Go to `0.0.0.0`
5. Ensure that after 5 seconds the address bar comes up
5. Go to your home server again, but immediately bring the address bar up when you do
6. Ensure that the address bar does not get closed after 5 seconds
7. Go to `playa`
8. Ensure that the address bar does not come up after 5 seconds
9. Do a smoke test to ensure there aren't any issues with the address bar coming up when it shouldn't.

**Comment by nbq** [comment]
testing now

**Pull request merged**
