### PR TITLE
make table additions in DS settings more obvious

### PR DESCRIPTION
**Pull request by birarda**
- changed UI behaviour in DS settings to make it clearer when new table rows are staged to be saved

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Run the Sandbox in this PR. Test all tables in the domain-server settings. This should include:
- adding new rows
- removing old rows
- removing staged rows
- adding rows with invalid input (blank input, keys with spaces, duplicate keys)
- adding multiple new rows in one change

Please include any other actions you can take against the tables to ensure that they behave as you expect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 596c2fec5e7a8a03acc9ad8b1677b8154fa545a3 available at: https://gist.github.com/18406414715c3302b94167556e1e8fca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-596c2fe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-596c2fe.dmg

**Comment by AlanZimmerman** [comment]
Adding a new group or blacklist group name prompts the user to save and restart but doing so:
-  triggers a  failed to validate modal for that new row for some reason (checking against valid group names?) 
- mistakenly gives the 'empty field(s)' validation message, which I assume is the wrong message

**Comment by ZappoMan** [comment]
I think it looks like @AlanZimmerman is saying this is a QA fail.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1474f22fd72e31966088d166917a1c83e170eb60 available at: https://gist.github.com/18406414715c3302b94167556e1e8fca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-1474f22.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-1474f22.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 738319a5cc8f791227809ff0f8e768c3d1be3368 available at: https://gist.github.com/18406414715c3302b94167556e1e8fca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-738319a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-738319a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79cb0ba074787907827664242440ea87657a7ba3 available at: https://gist.github.com/18406414715c3302b94167556e1e8fca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-79cb0ba.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-79cb0ba.dmg

**Comment by nbq** [comment]
testing this

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Added new rows under `Zones` and left some blank and it would not let me save with them blank - Saved after fixed and it worked just fine
* Remove `Zones` I had created and saved and it worked just fine
* under `Scripts` I deleted the `atp:/ACAudioSearchAndInject_tutorial.js` row successfully and saved just fine
* Tried to add a group with a blank name, it would not let me add anything
* tried to add a group named `#$%@` which it allowed, even though it is not a valid group name *(not a fail, just a note)*
* tried to add an IP of `1/1/1/1` to IP Addresses permissions and it failed to save saying blank field (instead of invalid input)
* ***tried to add IP of `175.134.2.3` to same area as above and got error saying blank field even though connect was checked, this is a valid IP so I consider this a fail***

**FAIL**

**Comment by birarda** [comment]
@nbq 

I'm unable to reproduce the one bullet you correctly highlight that would QA fail this PR. You added that to the **Permissions for Users from IP Addresses** section, correct?

Are you 100% sure you didn't have an empty field somewhere on the form? It should highlight the row where it thinks there is an empty field.

**Comment by nbq** [comment]
@birarda Here is the screen shot of the red field telling me it is the problem.

ip field error

**Comment by hifi-gustavo** [comment]
Build console output for commit: f03d2988c1ad8f49407f912d6df1ceaaa809d57c available at: https://gist.github.com/18406414715c3302b94167556e1e8fca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-f03d298.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9554-f03d298.dmg

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Added new rows under `Zones` and left some blank and it would not let me save with them blank - Saved after fixed and it worked just fine
* Added a zone and then deleted it without saving (removed staged row)
* Remove `Zones` I had created and saved and it worked just fine
* under `Scripts` I deleted the `atp:/ACAudioSearchAndInject_tutorial.js` row successfully and saved just fine
* Tried to add a group with a blank name, it would not let me add anything
* tried to add a group named `#$%@` which it allowed, even though it is not a valid group name *(not a fail, just a note)*
* Added IP of `172.12.12.12` and clicked connect for permissions and saved it and the new page came back with the set permission (worked as expected)
* removed IP added above and saved and it worked just fine
* deleted all of the entries under `Paths` and it saved just fine
* added multiple paths at the same time and then saved and they all saved and returned just fine
* tried to add a path that was blank and it warned me that it was an empty field so I was unable to save that entry. (worked as expected)
* tried to add two machine finger prints with the same entry at the same time and it warned me that the duplicate was blank (should say unable to add duplicate items, but it did catch it at least)
* tried to add a duplicate IP after the save and it did not save the duplicate on the return page
* added multiple different IP addresses and saved and they returned fine, deleted them all at the same time and hit save and it saved and returned it blank just as expected

*Now all works as expected*

**PASS**

**Pull request merged**
