### PR TITLE
More reliable and usable UI sphere overlay location

### PR DESCRIPTION
**Pull request by hyperlogic**
We no longer resetSensors on display plugin initialization.  For Oculus and OpenVR this should preserve the system configured orientation/position.

As an additional step, for OpenVR, we manipulate the sensor origin to align the UI sphere with the front of the chaperone room.  This should position the overlay near their computer screen in the real world, assuming the user has run the SteamVR room configuration and has configured default facing of the room properly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5df616be37406f5385ec5f58965501c55438dcd2 available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 886457939d7a39c32f7f8308281687c197e7fe1d available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f1b8805cf76d9b7ef96341ac58a8a49e9a4c3df available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42d27557a11ed30db5c1869c87c72fabce0cae1b available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by ZappoMan** [comment]
Test plan:
This needs to be tested with Oculus AND Vive... make sure that both behavior correctly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 153f7fc3aa9088fffdcc22b3524a0877da9aa996 available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by ZappoMan** [comment]
IMO - this produces undesirable effects on the oculus
- When I enable the oculus while sitting, my character ends up in a squatting position
- The overlay is displayed too close to my camera and is off-angle
- in third person mode, the overlay is actually rendered behind my avatar
- when returning BACK to display mode, if my oculus is not level, my character and my view is actually tilted sideways, and my view is slanted.

**Comment by ZappoMan** [comment]
coming-back-from-hmd-pr-7302

**Comment by hyperlogic** [comment]
I'm working on a fix for the switch between desktop and oculus.

**Comment by hyperlogic** [comment]
@ZappoMan : here are some comments.

> * When I enable the oculus while sitting, my character ends up in a squatting position
> * The overlay is displayed too close to my camera and is off-angle

This is possibly due to a misconfigured Oculus default pose.  Launch Oculus Configuration utility and click the "Show Demo Scene" button.  Go thru the menu to seated mode and click reset, then quit the demo scene.  The Oculus runtime should remember this pose, and this should be the default orientation of the our UI sphere overlay.  Let me know if this is not the case.

> * in third person mode, the overlay is actually rendered behind my avatar

Not sure if I follow, I think this is per spec, the overlay is not drawn around your avatar, but around the sensor "room" that your HMD is in.

> * when returning BACK to display mode, if my oculus is not level, my character and my view is actually tilted sideways, and my view is slanted.

This should be fixed now, basically we reset the Avatar only when changing display mode, this will reset the head and the palms back to a neutral pose.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d11dd465ca50b2a7fffaf00b3da4dee5c0753a2 available at: https://gist.github.com/f42db7f86f07a9887f66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7302.dmg

**Comment by PhilipRosedale** [comment]
Works well on Vive, testing now on Oculus.

**Comment by PhilipRosedale** [comment]
tested a lot on oculus.

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/97782015534475

**Pull request merged**
