### PR TITLE
Detailed Avatar Collisions

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR adds simple collision hulls to every avatar joint. 
It also flats the avatar capsule to avoid interference.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8707/app_12865_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8707/HighFidelity-Beta-PR12865-e116c73951b44544979745e1a4624924b8f5c715.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8707/HighFidelity-Beta-PR12865-e116c73951b44544979745e1a4624924b8f5c715.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8723/app_12865_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8723/HighFidelity-Beta-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8723/HighFidelity-Beta-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8723/HighFidelity-Beta-Interface-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8732/app_12865_PR_5ff039d0d08bfd9a9f341268d69628dc37518f43.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8732/HighFidelity-Beta-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8732/HighFidelity-Beta-Interface-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8732/HighFidelity-Beta-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8732/HighFidelity-Beta-Interface-PR12865-5ff039d0d08bfd9a9f341268d69628dc37518f43.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8831/HighFidelity-Beta-PR12865-38140c45371162ac67ebd9ea1c33e26f690322d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8831/HighFidelity-Beta-Interface-PR12865-38140c45371162ac67ebd9ea1c33e26f690322d6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8863/HighFidelity-Beta-PR12865-79bab0511a74a0d80c66a9cf4c17296a0f9531d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8863/HighFidelity-Beta-Interface-PR12865-79bab0511a74a0d80c66a9cf4c17296a0f9531d4.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8873/HighFidelity-Beta-PR12865-3be8587e77f6daf3183911fe336dd3772257e1ea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8873/HighFidelity-Beta-Interface-PR12865-3be8587e77f6daf3183911fe336dd3772257e1ea.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8891/HighFidelity-Beta-PR12865-2c404f904d634ebb0cd02839f3abf6b7f6fcb744.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8891/HighFidelity-Beta-Interface-PR12865-2c404f904d634ebb0cd02839f3abf6b7f6fcb744.exe

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8927/HighFidelity-Beta-PR12865-7e42ac065fd8957f6c03a7e4e34acca400ce15ed.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8940/HighFidelity-Beta-PR12865-080c2e6556f5fb57a52c50734e803cd3e4f1e1dd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8940/HighFidelity-Beta-Interface-PR12865-080c2e6556f5fb57a52c50734e803cd3e4f1e1dd.exe

**Pull request closed without merging**
