### PR TITLE
Fix Interface crash importing JSON with duplicate entity IDs in file

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14278/HighFidelity-Beta-PR14256-7947671.apk

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Check that importing the invalid files, invalidPairOfEntities.json and cubesGreenAndBlueDuplicateIDs.json, both fail with an error notification (top right in desktop mode, bottom of view in VR mode) saying "There was an error importing the entity file", no cubes created in front of you, and without Interface crashing.

2) Check that importing the valid file, cubesGreenAndBlue.json, succeeds with a green cube and a blue cube created in front of you.

Files are in the attached zip.

[M17008 Files.zip](https://github.com/highfidelity/hifi/files/2504218/M17008.Files.zip)

https://highfidelity.manuscript.com/f/cases/17008

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14278/HighFidelity-Beta-PR14256-7947671.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14278/HighFidelity-Beta-Interface-PR14256-7947671.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14278/HighFidelity-Beta-PR14256-7947671.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14278/HighFidelity-Beta-Interface-PR14256-7947671.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Paused Testing

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14870/HighFidelity-Beta-PR14256-7947671.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14870/HighFidelity-Beta-PR14256-7947671.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14870/HighFidelity-Beta-Interface-PR14256-7947671.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14870/HighFidelity-Beta-PR14256-7947671.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14870/HighFidelity-Beta-Interface-PR14256-7947671.exe

**Comment by QliCknox** [comment]
Currently Testing

**Pull request merged**
