### PR TITLE
Interstitital Mode - disable teleport and fix avatar outside of interstitial bubble (RC74)

### PR DESCRIPTION
**Pull request by danteruiz**
Description in this PR. https://github.com/highfidelity/hifi/pull/14188

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR https://github.com/highfidelity/hifi/pull/14188

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13824/HighFidelity-Beta-PR14190-5b33dd6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13824/HighFidelity-Beta-PR14190-5b33dd6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13824/HighFidelity-Beta-Interface-PR14190-5b33dd6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13824/HighFidelity-Beta-PR14190-5b33dd6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13824/HighFidelity-Beta-Interface-PR14190-5b33dd6.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
