### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0338690c871d6bb38eb3caaec0a124a85ed6e0d available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0338690c871d6bb38eb3caaec0a124a85ed6e0d available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b9c2cde63489e863fe74b2e0f2f22163016af72 available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0b13fc523e022955325490b79d9d6cc798a7970 available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0b13fc523e022955325490b79d9d6cc798a7970 available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0b13fc523e022955325490b79d9d6cc798a7970 available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0b13fc523e022955325490b79d9d6cc798a7970 available at: https://gist.github.com/294bb704ac4a7947b942<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6785.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6785.dmg

**Pull request merged**
