### PR TITLE
Case 20132, Case 16928: First class Image Entities

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/20132/Create-real-Image-Entities-with-all-the-properties-that-Image-Overlays-have
https://highfidelity.manuscript.com/f/cases/16928/Image-entities-render-edges-in-white-when-image-is-transparent

Test plan:
- Run the content/entity/image tests from this branch: https://github.com/highfidelity/hifi_tests/tree/03d635c22c968bca8ecc73eadcdc2260dd483987/tests/content/entity/image
- Create an Image Entity with a transparent image.  Verify that it is transparent and doesn't have a white border.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15597/HighFidelity-Beta-PR14524-98f9dc0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15597/HighFidelity-Beta-PR14524-98f9dc0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15597/HighFidelity-Beta-Interface-PR14524-98f9dc0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15597/HighFidelity-Beta-PR14524-98f9dc0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15597/HighFidelity-Beta-Interface-PR14524-98f9dc0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15697/HighFidelity-Beta-PR14524-abef5c4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15697/HighFidelity-Beta-PR14524-abef5c4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15697/HighFidelity-Beta-Interface-PR14524-abef5c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15697/HighFidelity-Beta-PR14524-abef5c4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15697/HighFidelity-Beta-Interface-PR14524-abef5c4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15726/HighFidelity-Beta-PR14524-645508d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15726/HighFidelity-Beta-PR14524-645508d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15726/HighFidelity-Beta-Interface-PR14524-645508d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15726/HighFidelity-Beta-PR14524-645508d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15726/HighFidelity-Beta-Interface-PR14524-645508d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15731/HighFidelity-Beta-PR14524-d30dd4c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15731/HighFidelity-Beta-PR14524-d30dd4c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15731/HighFidelity-Beta-Interface-PR14524-d30dd4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15731/HighFidelity-Beta-PR14524-d30dd4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15731/HighFidelity-Beta-Interface-PR14524-d30dd4c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15749/HighFidelity-Beta-PR14524-2291c7e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15749/HighFidelity-Beta-PR14524-2291c7e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15749/HighFidelity-Beta-Interface-PR14524-2291c7e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15749/HighFidelity-Beta-PR14524-2291c7e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15749/HighFidelity-Beta-Interface-PR14524-2291c7e.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15782/HighFidelity-Beta-PR14524-2291c7e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15782/HighFidelity-Beta-PR14524-2291c7e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15782/HighFidelity-Beta-Interface-PR14524-2291c7e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15810/HighFidelity-Beta-PR14524-4c5ff0d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15810/HighFidelity-Beta-PR14524-4c5ff0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15810/HighFidelity-Beta-Interface-PR14524-4c5ff0d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15810/HighFidelity-Beta-PR14524-4c5ff0d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15810/HighFidelity-Beta-Interface-PR14524-4c5ff0d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15869/HighFidelity-Beta-PR14524-c7a0d87.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15869/HighFidelity-Beta-PR14524-c7a0d87.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15869/HighFidelity-Beta-PR14524-c7a0d87.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15869/HighFidelity-Beta-Interface-PR14524-c7a0d87.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16065/HighFidelity-Beta-PR14524-e890fc6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16065/HighFidelity-Beta-PR14524-e890fc6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16065/HighFidelity-Beta-Interface-PR14524-e890fc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16065/HighFidelity-Beta-PR14524-e890fc6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16065/HighFidelity-Beta-Interface-PR14524-e890fc6.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Merged before a test plan was written

**Pull request merged**
