### PR TITLE
fix equip fly-away

### PR DESCRIPTION
**Pull request by sethalves**
- possible fix for a bug that causes observers to see someone else's newly equipped item fly away

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f6e6082071998a6f5bbfe036fc6bd93f386bdd2 available at: https://gist.github.com/3439f96d1835b7f9568fd6bc9b589946<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-5f6e608.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-5f6e608.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be001a652ffdf6aea2ba3ce468618b6893d3c91c available at: https://gist.github.com/3439f96d1835b7f9568fd6bc9b589946<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-be001a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-be001a6.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 56726183f6674980d58eb996e8ab3977460bda0d available at: https://gist.github.com/3439f96d1835b7f9568fd6bc9b589946<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-5672618.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8278-5672618.dmg

**Comment by thoys** [comment]
Whats the testplan on this?

**Comment by cozza13** [comment]
@thoys you will need another person to be watching.

- With someone watching, repeatedly equip and unequip something.
- Before this PR, about 1/10 the observer would see the thing fly away (confirm the issue on an older builds)

**Comment by thoys** [comment]
## QA Report

Tested with @cozza13 , we threw various objects to eachother. Picked up different objects. Repeatedly (un)equipped objects.

It all worked out fine.

QA Pass

**Pull request merged**
