### PR TITLE
FB19400 during shutdown -- TypeError: Cannot read property 'buttons' of null

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.manuscript.com/f/cases/19400/during-shutdown-TypeError-Cannot-read-property-buttons-of-null

note: PR also contains experimental code which tries to resolve all the shutdown warnings from QML at once.

Test plan

1. Launch interface
2. Delete logs
3. Close interface
4. Ensure logs doesn't contain entries like the following:

[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/hifi/tablet/TabletHome.qml:118: TypeError: Cannot read property 'buttons' of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/hifi/tablet/TabletHome.qml:118: TypeError: Cannot read property 'buttons' of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/hifi/Desktop.qml:73: TypeError: Cannot read property 'buttons' of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/hifi/Desktop.qml:74: TypeError: Cannot read property 'toolbarMode' of null

[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/Stats.qml:34: TypeError: Cannot read property of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/AnimStats.qml:34: TypeError: Cannot read property of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/hifi/audio/MicBar.qml:43: TypeError: Cannot read property of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/windows/DefaultFrameDecoration.qml:49: TypeError: Cannot read property of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/controls-uit/Keyboard.qml:240: TypeError: Cannot read property of null
[10/19 17:00:25] [WARNING] [default] file:///D:/ai/hifi-elderorb-vs2-qt10/interface/resources/qml/controls-uit/Key.qml:123: TypeError: Cannot read property of null

Repeat steps 1,3 at least 5 times while in desktop & 5 times while in VR mode.
Ensure application didn't crash during step 5.

Please also ensure PR didn't re-introduced the following issues: 
https://highfidelity.manuscript.com/f/cases/19871/Tablet-errors
https://highfidelity.manuscript.com/f/cases/19872/Login-problems
https://highfidelity.manuscript.com/f/cases/19873/Tablet-apps-do-not-open

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15252/HighFidelity-Beta-PR14426-64d05e3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15252/HighFidelity-Beta-PR14426-64d05e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15252/HighFidelity-Beta-Interface-PR14426-64d05e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15252/HighFidelity-Beta-PR14426-64d05e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15252/HighFidelity-Beta-Interface-PR14426-64d05e3.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15618/HighFidelity-Beta-PR14426-64d05e3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15618/HighFidelity-Beta-PR14426-64d05e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15618/HighFidelity-Beta-Interface-PR14426-64d05e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15618/HighFidelity-Beta-PR14426-64d05e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15618/HighFidelity-Beta-Interface-PR14426-64d05e3.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
