### PR TITLE
Fixed the texture assignment for the OBJ loader

### PR DESCRIPTION
**Pull request by mittens**
- The existing code wasn't doing anything with the specular texture, so I just ensured that the reference was set to that.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by thoys** [comment]
Nice @mittens !, @hifi-gustavo test this please :call_me_hand:

**Comment by ZappoMan** [comment]
test this please

**Comment by ZappoMan** [comment]
@mittens - do you have a sample OBJ that includes these specular textures?

**Comment by Nex-Pro** [comment]
@mittens  How about some test notes ?

**Comment by hifi-gustavo** [comment]
Build console output for commit: f1e81c34a323ed992773861e0459b3514968a103 available at: https://gist.github.com/dae4b3aa09b48df02ce40de1ba9f1454<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9933-f1e81c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9933-f1e81c3.dmg

**Comment by mittens** [comment]
Apologies, I just used the models provided by this: https://worklist.net/21189

Exported out the FBX with all textures exported into motobug_assets/*

**Comment by OmegaHeron** [comment]
Testing Windows 10
Visually, I can see no difference between motobug model on Master vs this PR.  In master obj sourced model looks same as this PR.  In both master and this PR obj sourced model differs from fbx model.

Will need a specific test method to validate this PR's intent is met.  It fails as of now in that I can see no change to application behavior and no indication of difference between loading motobug as an obj in master vs PR.

OBJ on left, FBX on right - Master (6180).

hifi-snap-by-omegaheron-on-2017-03-21_12-03-49

OBJ on left, FBX on right - This PR.

hifi-snap-by-omegaheron-on-2017-03-21_12-07-29

**Comment by mittens** [comment]
@OmegaHeron Hey, can I ask you how you got into a simple test environment? I've been using the Interface EXE, but it's kinda heavy for simple testing (especially when stepping through file loading code).

**Comment by OmegaHeron** [comment]
@mittens - uhm.. not sure what you're asking.  I went to my domain, added the two models then took screen shots.  I could have used local sandbox install, but, using my always up domain was fastest.

**Pull request merged**
