### PR TITLE
DEV-123 & BUGZ-602: Adding bookmark arg and making launcher appear on top

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.atlassian.net/browse/DEV-123 https://highfidelity.atlassian.net/browse/BUGZ-602

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19959/HighFidelity-Beta-PR15758-667af85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19959/HighFidelity-Beta-Interface-PR15758-667af85.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19959/HighFidelity-Beta-PR15758-667af85.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19959/HighFidelity-Quest-Beta-PR15758-667af85.apk)

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19965/HighFidelity-Beta-PR15758-667af85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19965/HighFidelity-Beta-Interface-PR15758-667af85.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19965/HighFidelity-Beta-PR15758-667af85.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19965/HighFidelity-Quest-Beta-PR15758-667af85.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19965/HighFidelity-Beta-PR15758-667af85.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19965/HighFidelity-Beta-Interface-PR15758-667af85.exe

**Pull request merged**
