### PR TITLE
replace Sandbox default content set with Home

### PR DESCRIPTION
**Pull request by birarda**
- replaces the downloaded content set for sandbox with "home.tgz" from cachefly
- updates electron/electron-prebuilt so we're up to date
- uses gunzip/tar-fs for unarchiving of streamed home.tgz, more reliable than previous unzip
- allows for domain-server settings to be included in content set for custom index path and scripts

### CODE REVIEW

**Comment by birarda** [comment]
To test:

Download the PR build, install and do not copy content from your production install.

Your content set should successfully download with the new content set and domain-server settings. This means that "Go Home" goes to a custom index path and the that ACAudioSearchAndInject script is loaded from ATP immediately when your servers first run.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a9b342c712592559271a99566cf6c57e6b14b6a4 available at: https://gist.github.com/6e6cf28574f8236aec48faef0d8740a0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 829bbdbf5a7725d6d063b1b50b47f3b79e701295 available at: https://gist.github.com/6e6cf28574f8236aec48faef0d8740a0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7644
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** Sandbox, Playa, Cellscience, Entry
**Smoke Test Results:** Successful test.

                                  |Playa    |Cellscience |Entry  
----------------------------------|---------|------------|--------
Render Rate:                      |36.44    |33.14       |31.75           
Present Rate:                     |59.60    |59.71       |59.71          
Simrate:                          |36.10    |33.11       |31.77           
Render Stats Num Buffers:         |3521     |2632        |8358             
Render Stats gpu::Buffer Memory:  |47.6Mb   |17.7Mb      |35.4Mb              
Render Stats Num Textures:        |455      |483         |1163              
Render Stats gpu::Texture Memory: |2031.1Mb |1257.7Mb    |3130.0Mb              
Render Stats Triangles:           |785k     |672k        |536k            
Render Stats Drawcalls:           |30627    |12806       |6245             
Render Stats Items:               |236      |799         |211  
GPU-Z Memory Size                 |4096Mb   |4096Mb      |4096Mb
GPU-Z Initial Memory		  |240Mb    |240Mb	 |240Mb
GPU-Z Memory Used		  |2860Mb   |914Mb       |1325Mb
GPU-Z Memory Load		  |11%      |7%          |8%

**sandbox ‘createtestblocks.js’ Result:** Successful test.
**sandbox Import FBX Result:** Successful test.
**sandbox ‘harmonicOscillator.js’ Result:** Successful test.
**sandbox Echo Server Audio Result:** Successful test.
**sandbox ‘reverbTest.js’ Result:** Successful test.
**Additional Test Results Requested:**  Successful test content set successfully downloaded with the new content set and domain-server settings.
**Successful Logout/Crash:** Successful logout.

**Comment by cozza13** [comment]
I got the following error installing and the error comes back up when trying to run the server console. 

capture2

**Comment by kevinmthomas-carpool** [comment]
capture

**Comment by kevinmthomas-carpool** [comment]
Successful manual domain-server run and successful manual assignment-client spawn with 5 servers successful in a command window.

**Comment by kevinmthomas-carpool** [comment]
capture

**Comment by birarda** [comment]
I believe the install issues are due to Jenkins - I'm trying to work with @murillodigital to fix that before we can test this again.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 829bbdbf5a7725d6d063b1b50b47f3b79e701295 available at: https://gist.github.com/6e6cf28574f8236aec48faef0d8740a0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Installed - no issue with JS warnings, content loads and works for home scene.  Fish tank is a bit loud....

**Comment by cozza13** [comment]
I tested this and it works. I could not hear the sounds for the blocks, yet this issue is also on Demo.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7450b8178394bd2a0244245ce0fe75edb608796 available at: https://gist.github.com/6e6cf28574f8236aec48faef0d8740a0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7644.dmg

**Pull request merged**
