### PR TITLE
(Experiment) Added sound cues to tablet 

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2511/HighFidelity-Beta-PR11194-43e8061daf2748c80fd2b54fbc0a3dce86281840.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2511/HighFidelity-Beta-PR11194-43e8061daf2748c80fd2b54fbc0a3dce86281840.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2593/HighFidelity-Beta-PR11194-6e683779c6fefbae8caa3bb0fa90fd90e6095776.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2593/HighFidelity-Beta-PR11194-6e683779c6fefbae8caa3bb0fa90fd90e6095776.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2667/HighFidelity-Beta-PR11194-116cc847711a1e955167db1cf9b429a440f0b72f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2667/HighFidelity-Beta-PR11194-116cc847711a1e955167db1cf9b429a440f0b72f.exe

**Comment by anshuman64** [comment]
Closed in favor of #11387

**Pull request closed without merging**
