### PR TITLE
[INFRA-196] Add mac notarization script

### PR DESCRIPTION
**Pull request by MattHardcastle**
The `notarize` script signs and submits a bundle to Apple's notarization
service. This command is meant for use as the part of release process
and its us is documented on the internal wiki.

    https://highfidelity.atlassian.net/wiki/spaces/hifiOps/pages/532710623/Sign+and+notarize+a+build+on+macOS

Jira: https://highfidelity.atlassian.net/browse/INFRA-196

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21449/HighFidelity-Beta-PR16230-f0f9fa0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21449/HighFidelity-Quest-Beta-PR16230-f0f9fa0.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21449/HighFidelity-Beta-PR16230-f0f9fa0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21449/HighFidelity-Beta-Interface-PR16230-f0f9fa0.dmg

**Comment by ZappoMan** [comment]
This build seemed to fail because of a problem with the windows build machine.

```
15:19:20 "C:\jenkins\workspace\pr-build\label\windows\build\interface\interface.vcxproj" (default target) (80) ->
15:19:20 (ClCompile target) -> 
15:19:20   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(423,5): error MSB6003: The specified task executable "CL.exe" could not be run. The process cannot access the file 'C:\jenkins\workspace\pr-build\label\windows\build\interface\interface.dir\Release\interface.tlog\CL.1660.read.1.tlog' because it is being used by another process. [C:\jenkins\workspace\pr-build\label\windows\build\interface\interface.vcxproj]
```

cc: @joy-highfidelity @MattHardcastle - can you please confirm that this build host is not in a borked state?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21507/HighFidelity-Beta-PR16230-f0f9fa0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21507/HighFidelity-Beta-Interface-PR16230-f0f9fa0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21507/HighFidelity-Beta-PR16230-f0f9fa0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21507/HighFidelity-Quest-Beta-PR16230-f0f9fa0.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21507/HighFidelity-Beta-PR16230-f0f9fa0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21507/HighFidelity-Beta-Interface-PR16230-f0f9fa0.exe

**Pull request merged**
