### PR TITLE
fix crash on shutdown from web audio captures

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA:

Go to a domain, and open a web entity to this page: https://www.openprocessing.org/sketch/175689
Ensure that the website can hear you (the website will be animated if it can hear you).

Quit.

On current build, this will crash with a pure virtual function call.
On this PR build, this will quit cleanly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: be23668ca85b17bbeaaa16abd2c620f478897c35 available at: https://gist.github.com/e4ac638d2e9c8ddfafcf26e507bc7b6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8951-be23668.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8951-be23668.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e2826d311f9fbedaa2db2f45e45efb0628e99a28 available at: https://gist.github.com/e4ac638d2e9c8ddfafcf26e507bc7b6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8951-e2826d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8951-e2826d3.dmg

**Comment by cozza13** [comment]
tested the above.

**Pull request merged**
