### PR TITLE
Emit avatar scale changed signal when scaled with hand controllers

### PR DESCRIPTION
**Pull request by misslivirose**
For avatar store and re-calculating distance for avatar scale changes 

Test Plan (Requires HMD/Hand controllers)
1. In the developer console, type: MyAvatar.scaleChanged.connect(function(){print("Hi")}) and hit enter

2. Confirm 'Hi' prints when changing scale in desktop mode

3. Switch to HMD mode and scale your avatar by squeezing the grips and crossing your hands across your body inward (smaller) and outward (larger)

4. Confirm that 'Hi' prints when changing scale in HMD mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5008/HighFidelity-Beta-PR11831-dda32f1987363d6213ba459893418c33fddc2400.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5008/HighFidelity-Beta-PR11831-dda32f1987363d6213ba459893418c33fddc2400.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### PASS

**Note:**  There are some messages re unknown worker after each hmd scaling attempt. They do not show up when using desktop scaling.

[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.scriptengine.script] [about:console] Hi
[11/16 18:31:24] [DEBUG] [hifi.entities] actionWorker -- unknown entity QUuid("{00000000-0000-0000-0000-000000000000}")
[11/16 18:31:24] [DEBUG] [hifi.entities] actionWorker -- unknown entity QUuid("{00000000-0000-0000-0000-000000000000}")

**Comment by Nex-Pro** [comment]
Those actionWorker messages might be unconnected with scaling.

**Comment by Nex-Pro** [comment]
@misslivirose ^ Done.

**Comment by misslivirose** [comment]
@Nex-Pro I'll take a peek at the logs. I suspect they're unrelated but I'll look into it -- which domain were you in when testing?

**Comment by Nex-Pro** [comment]
dev-welcome.

**Comment by Nex-Pro** [comment]
@misslivirose Logs in slack

**Comment by misslivirose** [comment]
@Nex-Pro thanks! I think that's unrelated as I'm not able to repro, nothing too suspicious in logs that I can see - suspect something was deleted at a weird time in dev-content while your client may have been updating.

**Pull request merged**
