### PR TITLE
dev-79: Lilypad Launcher: (Mac) Implement the error state page.

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.atlassian.net/browse/DEV-79

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19877/HighFidelity-Beta-PR15724-adeedc8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19877/HighFidelity-Quest-Beta-PR15724-adeedc8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19877/HighFidelity-Beta-PR15724-adeedc8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19877/HighFidelity-Beta-Interface-PR15724-adeedc8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19877/HighFidelity-Beta-PR15724-adeedc8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19877/HighFidelity-Beta-Interface-PR15724-adeedc8.exe

**Comment by danteruiz** [comment]
found a problem with this PR. Do not merge.

**Comment by danteruiz** [comment]
Issue I found are fixed

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19926/HighFidelity-Beta-PR15724-fc1f761.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19926/HighFidelity-Beta-Interface-PR15724-fc1f761.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19926/HighFidelity-Beta-PR15724-fc1f761.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19926/HighFidelity-Beta-Interface-PR15724-fc1f761.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19926/HighFidelity-Beta-PR15724-fc1f761.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19926/HighFidelity-Quest-Beta-PR15724-fc1f761.apk)

**Pull request merged**
