### PR TITLE
mark and cycle trait instances needing to be sent on mixer reconnect

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

For this test you will need two interface clients. Make sure avatar for interface client A has at least one wearable (there are multiple avatars in the avatars app with wearables).

Connect to a master domain with both interface clients. Disconnect from the domain with interface client A and reconnect. Ensure that the interface client B sees the avatar A re-appear in the domain with the correct avatar URL and the correct wearables.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12512/HighFidelity-Beta-PR13907-797f6b0.apk

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12516/HighFidelity-Beta-PR13907-797f6b0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12516/HighFidelity-Beta-PR13907-797f6b0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12516/HighFidelity-Beta-Interface-PR13907-797f6b0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12516/HighFidelity-Beta-PR13907-797f6b0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12516/HighFidelity-Beta-Interface-PR13907-797f6b0.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Using two clients, each disconnecting multiple different ways while wearing wearables from avatar app.

User A on desktop.
User B on Vive (HMD)

Quitting interface - Using File > Quit and used X to quit the interface, each time the user relaunched and reconnected, the correct wearables were present that the person quit on.

Logging in / out - Logging into Hifi or out caused both users to not see the other's wearables. Wearables returned for the other user if that user went into avatar app or wearables app. On further testing, it was not always both users that were affected. Occurs 80%+ of the time. Fails PR.

Connecting to another Hifi domain - No other Hifi domain available at time of testing. RC72 version of this fix did not have an issue.

Connecting to sandbox - User A goes to sandbox and then reconnects to hifi domain, both users saw the others wearables. User B does the same and sees both wearables. Tested 1-2 more times and no difficulties found.

Connecting to Home (serverless) - User A goes to home and reconnects to hifi domain. Wearables were often not visible to the other party, occurs about 75% of the time when testing this.

Using back button - User A goes to other hifi domain / home and uses back button to return. Wearables were often not visible to the other party, occurs about 75% of the time when testing this.

Disconnecting network (unplug ethernet) - User A disconnects network cable, reconnects, User B and User A saw each other's wearables. User B disconnects / reconnects, User B does not see User A's wearables while User A does see User B's wearables. Attempted multiple repro's and got it to occur for both users about 50% of the time with the user that is reconnecting not able to see the other users wearables.

Ignore - Tested both sides ignoring each other and both, then with logged in with one and both, no difficulties with any ignoring.

[User_B_Logs.zip](https://github.com/highfidelity/hifi/files/2337353/User_B_Logs.zip)
[User_A_Logs.zip](https://github.com/highfidelity/hifi/files/2337354/User_A_Logs.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12546/HighFidelity-Beta-PR13907-9819f40.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12546/HighFidelity-Beta-PR13907-9819f40.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12546/HighFidelity-Beta-Interface-PR13907-9819f40.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12546/HighFidelity-Beta-PR13907-9819f40.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12546/HighFidelity-Beta-Interface-PR13907-9819f40.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12596/HighFidelity-Beta-PR13907-a37a19d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12596/HighFidelity-Beta-PR13907-a37a19d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12596/HighFidelity-Beta-Interface-PR13907-a37a19d.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12668/HighFidelity-Beta-PR13907-a37a19d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12668/HighFidelity-Beta-PR13907-a37a19d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12668/HighFidelity-Beta-Interface-PR13907-a37a19d.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Using two clients, each disconnecting multiple different ways while wearing wearables from avatar app.

User A on desktop.
User B on Vive (HMD)

Quitting interface - Using File > Quit and used X to quit the interface, each time the user relaunched and reconnected, the correct wearables were present that the person quit on.

Logging in / out - Both users saw each other's wearables on every login or logout.

Connecting to sandbox - Changing to sandbox and back still had wearable's present.

Connect to home (serverless) - Changing to serverless and back still had wearable's present.

Using back button - Wearables were present.

Disconnecting network (unplug ethernet) - Wearables were present.

Ignore - No difficulties.

PR Passes.

**Pull request merged**
