### PR TITLE
fix server scripts AC

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that kept server-side scripts from running

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run http://headache.hungry.com/~seth/hifi/stopwatch/spawnStopwatch.js
- click on the buttons, make sure the watch works

**Comment by OmegaHeron** [comment]
Will test Windows and Linux

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/5715/server-side-scripts-aren-t-working

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1157/HighFidelity-Beta-PR10841-2f3109e4beb86222227fcd89d53211626184407e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1157/HighFidelity-Beta-PR10841-2f3109e4beb86222227fcd89d53211626184407e.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10 and Ubuntu 16.04
QA Pass

This PR stack on Ubuntu + This PR Interface on Ubuntu *Pass*
This PR stack on Windows + This PR Interface on Windows *Pass*
This PR stack on Ubuntu + This PR Interface on Windows *Pass*
This PR stack on Windows + This PR Interface on Ubuntu *Pass*

**Pull request merged**
