### PR TITLE
fix blank tablet when switching between HMD and Desktop mode quickly

### PR DESCRIPTION
**Pull request by druiz17**
fix blank tablet when switching between HMD and Desktop mode quickly

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
-  Switch between desktop and HMD mode a few times really fast using ctrl+1 & ctrl+4. End in VR mode.
- open tablet and the tablet apps should appear on the tablet

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2185/HighFidelity-Beta-PR11099-cca29e849b50a8b982144439b3ca46d2cb2f73d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2185/HighFidelity-Beta-PR11099-cca29e849b50a8b982144439b3ca46d2cb2f73d9.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by druiz17** [comment]
@YuppyPlays Im adding some more this to the test plan.

**Comment by YuppyPlays** [comment]
@druiz17 
Oh okay, I just finished with the old steps, I experienced the bug myself in other PR's when simple changing to Desktop via top menu bar, then changing back to VR once it skips tutorial and sends me to home, then it would usually happen then when switching back

Will test though with updated plan, but so far referring to the old plan and my own replication of the issue before, this passed in that case.

Will further test with new steps now.

**Comment by YuppyPlays** [comment]
Testing complete:

[Using: HTC Vive / i7 4790k / 16GB RAM / GTX 1080Ti]

Test plan

Switch between desktop and HMD mode a few times really fast using ctrl+1 & ctrl+4. End in VR mode. **Check**
open tablet and the tablet apps should appear on the tablet **Check**

Additional Test to check for regression

1
Do a clean install and do not have your sandbox running **Check**
Start interface with in HMD mode **Check**
Open the tablet and you should be on the help screen **Check**
Pressing the x button on the tablet should bring you back to the home screen, pressing it again should close the tablet. **Check**
Open tablet again and you should be on the home-screen **Check**

2
Do a clean install and do not have your sandbox running **Check**
Start interface with in HMD mode **Check**
Quickly switch to desktop mode **Check**
Once in desktop mode, the only button in the toolbar that should be highlighted is the bubble button. **Check**
Without clicking anything switch back to HMD mode **Check**
Open the tablet and you should be on the home screen. (if your on the Help screen check it you can go back to the homescreen,) **Check**
If you on the home screen pressing the x on the tablet should close the tablet. **Check**
Open tablet again and you should be on the home-screen **Check**

3
Do a clean install and do not have your sandbox running **Check**
Start interface with in HMD mode **Check**
Quickly switch to desktop mode **Check**
Once in desktop mode, the only button in the toolbar that should be highlighted is the bubble button. **Check**
Click on help button to bring up the help page **Was already showing?.. This is the first time from all the clean installs this has happened and now it's acting consistently despite redoing clean installs. I am at a loss on why this is**
With the help page open, switch to HMD mode**Check**
Open the tablet and you should be on the home screen. (if your on the Help screen check it you can go back to the home screen,)**Check**
If you on the home screen pressing the x on the tablet should close the tablet.**Check**
Open tablet again and you should be on the home-screen**Check**
**Had a really weird occurrence with the last step, Help screen was showing for the first time out of 6 total clean installs within Desktop when the switch was made - bizarre considering it didn't do this prior.**


**Notes: Did get a weird issue where the help screen got stuck, but I accidentally made one slip up in test plan that caused this, though will post repro just in-case:
 - Clean installed, No sandbox running, Started interface in HMD Mode.
 - Quickly switched to desktop via Ctrl + 1
 - In desktop mode, I clicked the audio icon and muted myself, then went back into HMD mode
 - Opened tablet via Mouse right click instead of Vive controllers menu button
 - Help screen was open, used laser to click the X, it closed tablet.
 - Re-opened tablet. still had Help screen open
 - Tried to press X with laser and with stylus, neither would exit Help or close tablet
 - Pressing the Vive controller menu button or right click allowed me to toggle tablet on/off
 - Always stuck on Help screen at this point.**



Not sure what to make of the results for 100%, but I'd say this is a **Pass** for fixing the issue at hand [Blank tablet]. But if anyone thinks otherwise please let me know as the input/feedback is important.

**Comment by anshuman64** [comment]
@YuppyPlays is right, you can repro the "getting stuck on help" problem using his repro steps at the end of his comment. I would consider that a QA Fail.

**Comment by druiz17** [comment]
@YuppyPlays can I get a re-test of this PR, I made some changes that should fix both the blank tablet issue and being stuck on the help screen issue.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2201/HighFidelity-Beta-PR11099-8d69cd899909892ca0fc709949a95733ed60bc5a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2201/HighFidelity-Beta-PR11099-8d69cd899909892ca0fc709949a95733ed60bc5a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

To re-cap old steps by # 
Step 1: **Pass**
Step 2: **Pass**
Step 3: **Pass**
Step 4: **Pass**
Repro of issue regarding stuck on help screen: **Could not repro issue in latest build - Pass**

Great work man, all looks good to me! :)

**Pull request merged**
