### PR TITLE
Move to qqc2

### PR DESCRIPTION
**Pull request by vladest**
case https://highfidelity.fogbugz.com/f/cases/6840/Move-to-QQC2

Test plan:
- go thru Dialogs
- make sure Controls (buttons, checkboxes, input fileds etc) works and looks as expected

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5862/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5862/HighFidelity-Beta-PR12068-f5f19ea67fb1a978be0bd3db7fe208ee939483e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5862/HighFidelity-Beta-PR12068-f5f19ea67fb1a978be0bd3db7fe208ee939483e6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5882/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5882/HighFidelity-Beta-PR12068-c953251cfef5aadaa61b818789acf9cc8d15bf34.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5882/HighFidelity-Beta-PR12068-c953251cfef5aadaa61b818789acf9cc8d15bf34.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5892/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5892/HighFidelity-Beta-PR12068-09c3f93c74cd0b32cc8c6e828eb97b30310fbba7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5892/HighFidelity-Beta-PR12068-09c3f93c74cd0b32cc8c6e828eb97b30310fbba7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6038/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6038/HighFidelity-Beta-PR12068-00b1d4b0ea638a539d174ec664713f8d5cd80728.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6038/HighFidelity-Beta-PR12068-00b1d4b0ea638a539d174ec664713f8d5cd80728.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing FAILED. Properties tab in the Create Menu is cut off. 
create

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6221/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6221/HighFidelity-Beta-PR12068-45144bece6d429a609b1ea0fc01884ef2328b5f5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6221/HighFidelity-Beta-PR12068-45144bece6d429a609b1ea0fc01884ef2328b5f5.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing Completed for PR#12068. PASSED.

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12068. PASSED.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6336/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6336/HighFidelity-Beta-PR12068-b3b7a7636fa6d7f851e7bc055ae1901259634a4d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6336/HighFidelity-Beta-PR12068-b3b7a7636fa6d7f851e7bc055ae1901259634a4d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6484/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6484/HighFidelity-Beta-PR12068-e7a035f954ed16f58583c086bea1005dd515b9eb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6484/HighFidelity-Beta-PR12068-e7a035f954ed16f58583c086bea1005dd515b9eb.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6523/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6525/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6525/HighFidelity-Beta-PR12068-9fa6b8da6a5592e0f64f6edd15e36b2a60058e6e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6525/HighFidelity-Beta-PR12068-9fa6b8da6a5592e0f64f6edd15e36b2a60058e6e.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12068. FAILED. Scrollbar does not respond correctly to mouse input. When clicked, the scrollbar will only respond within a small vertical space, but when the user leaves that small space, scrolling stops. However, once the mouse click is released, the scrollbar is 'stuck' to the mouse cursor and will move up and down with the user's mouse despite not being selected. The user has to click again to 'unstick' the scrollbar and be able to use their mouse properly again. Please follow the attached link to view the video. 
https://drive.google.com/file/d/1aSi_Ipk_-79ifHWfrKgHnVvvpc6uXKxw/view?usp=sharing

**Comment by vladest** [comment]
I believe this is not related to the issue. I have reported this several times: mouse does not send release event when go out of the Tablet interface

**Comment by sethalves** [comment]
@QAadahlin @conklin94122 is this scrollbar behaviour different than what's in master?

**Comment by Qliemillar** [comment]
@sethalves It is quite different. When the scrollbar is clicked, it will initially only drag a little, and very slowly, but when the mouse leaves a certain area, the scrollbar stops moving entirely until the mouseclick is released, in which case it 'sticks' to the mouse and the scrollbar will move up and down as the mouse is moved (despite not being currently clicked). The user has to click again to 'unstick' the scrollbar. This issue is not present in master, where if you click and drag the scrollbar, it moves up and down correctly and does not abruptly stop scrolling or 'stick' when the mouseclick is released.

**Comment by Qliemillar** [comment]
@vladest @sethalves  https://highfidelity.fogbugz.com/f/cases/11962/PR12068-Scrollbars-within-Menus-do-not-behave-correctly

**Comment by vladest** [comment]
I've checked with master and can see same behavior
Obviously, issue must be addressed, but this PR is not root cause, imho

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6839/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6839/HighFidelity-Beta-PR12068-3346381db2697b0c646c1454f982daf24d39f896.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6839/HighFidelity-Beta-PR12068-3346381db2697b0c646c1454f982daf24d39f896.dmg

**Comment by themelissabrown** [comment]
@vladest how are we proceeding with this? Is it blocked until scrollbar issues in master are resolved?

**Comment by vladest** [comment]
@themelissabrown I dont think the issue with scroll bar in master is blocker for this PR, since sticked pressed mouse already in master and this PR is not root cause for this issue
For example its easy reproducible with scrolling domains in GoTo app
I think it good to investigate/fix this during work on case 12008

**Comment by themelissabrown** [comment]
@conklin94122 can we figure out how to get QA approval based on the information above?

**Comment by conklin94122** [comment]
@themelissabrown It sounds like the issue Erin is describing can not be reproduced in master or stable, so would block this PR until resolved. We can try to record the behavior on master and the behavior in this PR, but I'm afraid it's something that's felt, as opposed to being visual.

**Comment by themelissabrown** [comment]
@vladest sounds like you get to fix scrollbar prior to merging this. I'll post in QML

**Comment by samcake** [comment]
Samuel, @SamGondelman  can you review this pr and make sure that it s compatible with the Fall changes to the Pointer library ?
Thanks

**Comment by themelissabrown** [comment]
@conklin94122 this is ready for QA again. The behavior should now be the same as master (and master is broken, a known issue).

**Comment by themelissabrown** [comment]
QA- If mouse behavior is still different from master, please take video so we can further troubleshoot

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7165/app_12068_PR.apk

**Comment by conklin94122** [comment]
QA, if you think you have a fail please run it past me first.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7165/HighFidelity-Beta-PR12068-e8959b4cc050d49bcda5c4796477009a23b28b89.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7181/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7181/HighFidelity-Beta-PR12068-d71448d21740cd7343eaa8e1ba1ec8477d73139b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7181/HighFidelity-Beta-PR12068-d71448d21740cd7343eaa8e1ba1ec8477d73139b.exe

**Comment by sbennett77** [comment]
Currently Testing

**Comment by sbennett77** [comment]
On hold pending further instruction.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7233/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7233/HighFidelity-Beta-PR12068-a500ba8f2d79f93fcf1baf6bf82586163565769a.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by vladest** [comment]
please do not test it. the issue acknowledged and investigation ongoing

**Comment by sbennett77** [comment]
Stopped Testing.

**Comment by conklin94122** [comment]
Removed QA Ready for now. Please relabel once you want testing to start again.

**Comment by vladest** [comment]
The issue should be fixed now. Please retest

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7498/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7498/HighFidelity-Beta-PR12068-931696322f192080ecdc92fc0c90bf6523caf7b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7498/HighFidelity-Beta-PR12068-931696322f192080ecdc92fc0c90bf6523caf7b7.exe

**Comment by SamGondelman** [comment]
from a quick look:
- File -> Login window (also open file window, possibly others) has a scrollbar behind the text boxes.  Clicking it crashes interface.
- Menu window side-scrolling effect is broken
- Menu -> Settings -> General extends off bottom of window
- Goto extends outside of window
- Create -> Model doesn't bring up new model dialog

**Comment by vladest** [comment]
:( forgot to return clip. will check

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7554/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7554/HighFidelity-Beta-PR12068-90b891dbc3d4db70ba5950f39b56100310a6ae06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7554/HighFidelity-Beta-PR12068-90b891dbc3d4db70ba5950f39b56100310a6ae06.exe

**Comment by vladest** [comment]
Please retest it.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7620/HighFidelity-Beta-PR12068-8dd27a1a04a4c0f757ec6ded49fe44d30c48c646.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7620/HighFidelity-Beta-PR12068-8dd27a1a04a4c0f757ec6ded49fe44d30c48c646.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7622/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7622/HighFidelity-Beta-PR12068-8dd27a1a04a4c0f757ec6ded49fe44d30c48c646.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7622/HighFidelity-Beta-PR12068-8dd27a1a04a4c0f757ec6ded49fe44d30c48c646.exe

**Comment by SamGondelman** [comment]
Lots of windows still have a weird scrollbar behind things and Interface crashes when you click it.  For example, File -> Login.

**Comment by vladest** [comment]
@SamGondelman cant repro this on Linux. Can you please make a screenshot. Will have access to Win/Mac next week and check if its related

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Comment by SamGondelman** [comment]
You can see them on the right of most windows.  Clicking them causes a crash.
image

**Comment by qlimnavarro** [comment]
Fail
Selecting Scroll bars on the right of certain windows causes crash. In the login screen, a wild scroll bar appears. Clicking it will crash the Interface. In Asset Browser and Running Scripts windows there is a dark line on the right of the windows. Selecting them will crash the Interface. This only occurs in Desktop mode, the lines of crashing do not appear in HMD tablet. Video and Various logs of crashing attached.

[PR12068 Files.zip](https://github.com/highfidelity/hifi/files/1776695/PR12068.Files.zip)

@conklin94122

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7701/HighFidelity-Beta-PR12068-94e070eae25089e2a59498ba01414d99855607f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7701/HighFidelity-Beta-PR12068-94e070eae25089e2a59498ba01414d99855607f7.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Fail - @conklin94122 
Random scroll bars that crash the Interface appear in General Settings, Avatar Settings, and Running Scripts (This only occurs in desktop mode). Also files uploaded in the asset browser can no longer be selected (This occurs in desktop and HMD modes)
scroll
[PR12068 Filess.zip](https://github.com/highfidelity/hifi/files/1781712/PR12068.Filess.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7741/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7741/HighFidelity-Beta-PR12068-698a224bb0e17f54eab0f2042d90dc60d84dd165.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7741/HighFidelity-Beta-PR12068-698a224bb0e17f54eab0f2042d90dc60d84dd165.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7970/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7970/HighFidelity-Beta-PR12068-33e70be18a421eb587b51acb12e7f2c8d897f296.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7970/HighFidelity-Beta-PR12068-33e70be18a421eb587b51acb12e7f2c8d897f296.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
When opening create and emote menu, not all buttons fit. In addition to this, some scroll wheel seem to not work as expected, as they stop working when dragged then "stick" to the mouse pointer. 
1) Open Emote Menu
2) Click and hold on the scroll bar on the right
3) Drag down a bit
4) Let go of the mouse button
5) Scroll bar is now "Sticking" to pointer

NOTE: Previous crashing no longer occurs, and problems selecting items in Asset Browser are now functioning as expected.
See video and logs for more details:
[Files.zip](https://github.com/highfidelity/hifi/files/1804296/Files.zip)

**Comment by vladest** [comment]
the issue is long term know issue and not related to the PR. you can see
this stick kouse on master as well with any scroll bar

**Comment by conklin94122** [comment]
Moved to RC67 per Ryan

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8250/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8250/HighFidelity-Beta-PR12068-56150f89626cdd9f94297cc1113f8f2057acb7d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8250/HighFidelity-Beta-PR12068-56150f89626cdd9f94297cc1113f8f2057acb7d7.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8279/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8279/HighFidelity-Beta-PR12068-56150f89626cdd9f94297cc1113f8f2057acb7d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8279/HighFidelity-Beta-PR12068-56150f89626cdd9f94297cc1113f8f2057acb7d7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Build crashes on launch on both Windows and Mac, logs for windows attached.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/1852404/hifi-log.txt)
[hifi-log_2018-03-27_08.21.37.txt](https://github.com/highfidelity/hifi/files/1852405/hifi-log_2018-03-27_08.21.37.txt)
[hifi-log_2018-03-27_08.21.58.txt](https://github.com/highfidelity/hifi/files/1852406/hifi-log_2018-03-27_08.21.58.txt)
[hifi-log_2018-03-27_08.27.38.txt](https://github.com/highfidelity/hifi/files/1852407/hifi-log_2018-03-27_08.27.38.txt)
[hifi-log_2018-03-27_08.27.49.txt](https://github.com/highfidelity/hifi/files/1852408/hifi-log_2018-03-27_08.27.49.txt)

**Comment by vladest** [comment]
@conklin94122 Startup crash was due to switch over Qt 5.10, which contains its own Action item. 
Fixed now. 
Please retest

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8296/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8296/HighFidelity-Beta-PR12068-096b56395ebd10fe7601ede3326c9188b91eae7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8296/HighFidelity-Beta-PR12068-096b56395ebd10fe7601ede3326c9188b91eae7a.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
The buttons in the create and emote menu seem to be misaligned. Not all buttons are visible and it feels cramped.
create
emote
[hifi-log_2018-03-27_12.27.17_5e219a96-2e32-407f-b452-a2f5f4c66657.txt](https://github.com/highfidelity/hifi/files/1853351/hifi-log_2018-03-27_12.27.17_5e219a96-2e32-407f-b452-a2f5f4c66657.txt)
[hifi-log_2018-03-27_12.27.36_5e219a96-2e32-407f-b452-a2f5f4c66657.txt](https://github.com/highfidelity/hifi/files/1853352/hifi-log_2018-03-27_12.27.36_5e219a96-2e32-407f-b452-a2f5f4c66657.txt)
[hifi-log_2018-03-27_12.28.04_5e219a96-2e32-407f-b452-a2f5f4c66657.txt](https://github.com/highfidelity/hifi/files/1853353/hifi-log_2018-03-27_12.28.04_5e219a96-2e32-407f-b452-a2f5f4c66657.txt)

**Comment by vladest** [comment]
@conklin94122 fixed. please retest

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8327/app_12068_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8327/HighFidelity-Beta-PR12068-70ce1b2bf7e5b310fe2875f5bc965116ee69dd46.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8327/HighFidelity-Beta-PR12068-70ce1b2bf7e5b310fe2875f5bc965116ee69dd46.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Menus look good and respond well. Both desktop and HMD mode menus in tablet and toolbar continue to work as expected.

**Comment by sethalves** [comment]
We'll wait for https://github.com/highfidelity/hifi/pull/12862 before merging this.

**Comment by sethalves** [comment]
nevermind, we'll merge this one first and be ready to help out with https://github.com/highfidelity/hifi/pull/12862 if need be.

**Comment by misslivirose** [comment]
@conklin94122 - was the particle explorer tested as part of this change?

**Comment by conklin94122** [comment]
@misslivirose Checking...

**Comment by misslivirose** [comment]
Cool. We're seeing some weirdness that seemed to be exaggerated after the switch, but it's not consistent. Just wanted to check. Thank you!

**Pull request merged**
