### PR TITLE
Remove directory.js from default scripts

### PR DESCRIPTION
**Pull request by imgntn**
This PR removes the directory for now (and also a commented out attachments manager).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 90c59c5af079274826db3ee5b71cdeb2a9cc3f1a available at: https://gist.github.com/742becbcb7d7d2704d56902807c4a7d8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7780.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7780.dmg

**Comment by RyanDowne** [comment]
The works for me.

**Comment by kevinmthomas-carpool** [comment]
@ryan should I continue the test?

**Comment by kevinmthomas-carpool** [comment]
@RyanDowne I was testing before you moved it to QA Approved however I see it is now approved so I will abort the testing.

**Pull request merged**
