### PR TITLE
Case 21335: Use old tablet keyboard for quest

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.manuscript.com/f/cases/21335/Use-old-tablet-keyboard-by-default-for-quest

### CODE REVIEW

**Comment by danteruiz** [comment]
Test 
1. desktop - 3d keyboard shows up by default
2. quest - tablet keyboard shows up by default

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17467/HighFidelity-Beta-PR14970-bf8c671.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17467/HighFidelity-Beta-PR14970-bf8c671.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17467/HighFidelity-Beta-Interface-PR14970-bf8c671.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17467/HighFidelity-Beta-PR14970-bf8c671.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17467/HighFidelity-Beta-Interface-PR14970-bf8c671.exe

**Pull request merged**
