### PR TITLE
Fix tablet asset browser's add-to-world dialog

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Test popup dialog that opens from Asset Browser's "Add to World" button in:
- Desktop window mode. Keyboard should not display.
- Desktop tablet mode. Keyboard should not display.
- HMD window mode. Keyboard should display.
- HMD tablet mode. Keyboard should display.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1080e21afd707eea654d976e3a21e659e4680f90 available at: https://gist.github.com/d0e07cd4783f344914c847290899e9b7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9920-1080e21.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9920-1080e21.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9920-1080e21.exe

PASS:
- PASS: Desktop window mode. Keyboard should not display.
- PASS: Desktop tablet mode. Keyboard should not display.
- PASS: HMD window mode. Keyboard should display.
- PASS: HMD tablet mode. Keyboard should display.

Notes:
I'm was unable to delete the entity I loaded through the 'Add to World' button. EDIT>LIST>DELETE BUTTON. This only happened when I was in HMD tablet mode, in Desktop tablet mode, and only with the mouse. Clicking on the delete button would cause the highlighted entity to flicker, but would not delete.

**Comment by sethalves** [comment]
okay -- I noticed that problem with desktop+tablet also.  I'll file a separate issue for that and let's call this a pass.

**Pull request merged**
