### PR TITLE
Make grab beam visible to other users

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing:
- When an entity is far-grabbed the grab laser is visible to other people.
- The grab laser doesn't collide with avatars or other entities.

**Comment by ZappoMan** [comment]
I'm very concerned about this PR:
- it will create a great deal of visual noise...
- it will put a great deal more stress on the entity sever - especially at load... and will basically nullify all of our recent load testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c2a70d435a5d119d781d30ada020bd5c9374ead available at: https://gist.github.com/a6bd97ee7d5ddf9834d672ef153ef741<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9738-7c2a70d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9738-7c2a70d.dmg

**Comment by ctrlaltdavid** [comment]
@ZappoMan  Laser beam is visible to others (as an entity) only when an entity is grabbed. (Search beams aren't visible to others.) Discuss with @PhilipRosedale who requested this feature?

**Comment by OmegaHeron** [comment]
Just to stick in my 2 cents worth - understood that this applies only to grabbed items vs search beams, but - paint me jaded - soon as people figure out they can make a self contained laser light show - they will and it will be ugly in crowds.  That on top of potential to add rendering load, server load etc etc etc seems to make this fraught with many levels of peril.

**Comment by ZappoMan** [comment]
Chatting with @PhilipRosedale about this briefly... the goal is to help people who are attempting to far grab an object (that happens to be currently being far grabbed by another person at the moment) have some indication as to why they can't far grab.

@ctrlaltdavid - it seems to me that it would be able to detect this case in the client attempting the second far grab, and give them a visual indication (maybe only show the conflicting far grab to the person attempting the second grab, still using an overlay).

This type of approach would address both the concerns raised.

Do you believe it would be possible to implement that as an alternative?

**Comment by ctrlaltdavid** [comment]
@ZappoMan Any hints on the mechanism for the second client detecting that another client is grabbing?

**Comment by ctrlaltdavid** [comment]
Will take a different approach in a new branch.

**Pull request closed without merging**
