### PR TITLE
Dev-117 & Dev-147: Automate the signing of mac launcher and interface & update config file location

### PR DESCRIPTION
**Pull request by danteruiz**
ticket - https://highfidelity.atlassian.net/secure/RapidBoard.jspa?rapidView=46&modal=detail&selectedIssue=DEV-117&quickFilter=125&assignee=557058%3A56835251-5116-4703-a5d3-30bccdb21af4

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20761/HighFidelity-Beta-PR16031-4de3669.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20761/HighFidelity-Beta-Interface-PR16031-4de3669.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20761/HighFidelity-Beta-PR16031-4de3669.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20761/HighFidelity-Quest-Beta-PR16031-4de3669.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20766/HighFidelity-Beta-PR16031-5106731.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20766/HighFidelity-Beta-Interface-PR16031-5106731.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20766/HighFidelity-Beta-PR16031-5106731.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20766/HighFidelity-Quest-Beta-PR16031-5106731.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20771/HighFidelity-Beta-PR16031-a394902.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20771/HighFidelity-Beta-Interface-PR16031-a394902.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20771/HighFidelity-Beta-PR16031-a394902.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20771/HighFidelity-Quest-Beta-PR16031-a394902.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20771/HighFidelity-Beta-PR16031-a394902.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20771/HighFidelity-Beta-Interface-PR16031-a394902.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20775/HighFidelity-Beta-PR16031-9a796c9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20775/HighFidelity-Quest-Beta-PR16031-9a796c9.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20775/HighFidelity-Beta-PR16031-9a796c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20775/HighFidelity-Beta-Interface-PR16031-9a796c9.dmg

**Comment by shanzzam** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20784/HighFidelity-Beta-PR16031-9a796c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20784/HighFidelity-Beta-Interface-PR16031-9a796c9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20784/HighFidelity-Beta-PR16031-9a796c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20784/HighFidelity-Beta-Interface-PR16031-9a796c9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20784/HighFidelity-Beta-PR16031-9a796c9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20784/HighFidelity-Quest-Beta-PR16031-9a796c9.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20802/HighFidelity-Beta-PR16031-aa257d2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20802/HighFidelity-Beta-Interface-PR16031-aa257d2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20802/HighFidelity-Beta-PR16031-aa257d2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20802/HighFidelity-Quest-Beta-PR16031-aa257d2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20802/HighFidelity-Beta-PR16031-aa257d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20802/HighFidelity-Beta-Interface-PR16031-aa257d2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20812/HighFidelity-Beta-PR16031-2705455.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20812/HighFidelity-Beta-Interface-PR16031-2705455.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20812/HighFidelity-Beta-PR16031-2705455.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20812/HighFidelity-Beta-Interface-PR16031-2705455.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20812/HighFidelity-Beta-PR16031-2705455.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20812/HighFidelity-Quest-Beta-PR16031-2705455.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20821/HighFidelity-Beta-PR16031-e6b2c61.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20821/HighFidelity-Quest-Beta-PR16031-e6b2c61.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20821/HighFidelity-Beta-PR16031-e6b2c61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20821/HighFidelity-Beta-Interface-PR16031-e6b2c61.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20821/HighFidelity-Beta-PR16031-e6b2c61.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20821/HighFidelity-Beta-Interface-PR16031-e6b2c61.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20827/HighFidelity-Beta-PR16031-b9008b5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20827/HighFidelity-Beta-Interface-PR16031-b9008b5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20827/HighFidelity-Beta-PR16031-b9008b5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20827/HighFidelity-Beta-Interface-PR16031-b9008b5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20827/HighFidelity-Beta-PR16031-b9008b5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20827/HighFidelity-Quest-Beta-PR16031-b9008b5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20833/HighFidelity-Beta-PR16031-e097f37.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20833/HighFidelity-Beta-PR16031-e097f37.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20833/HighFidelity-Beta-Interface-PR16031-e097f37.exe

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20833/HighFidelity-Beta-Interface-PR16031-e097f37.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20833/HighFidelity-Beta-PR16031-e097f37.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20833/HighFidelity-Quest-Beta-PR16031-e097f37.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20869/HighFidelity-Beta-PR16031-e0fd9fc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20869/HighFidelity-Quest-Beta-PR16031-e0fd9fc.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20869/HighFidelity-Beta-PR16031-e0fd9fc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20869/HighFidelity-Beta-Interface-PR16031-e0fd9fc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20869/HighFidelity-Beta-PR16031-e0fd9fc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20869/HighFidelity-Beta-Interface-PR16031-e0fd9fc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20998/HighFidelity-Beta-PR16031-76a4418.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20998/HighFidelity-Beta-Interface-PR16031-76a4418.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20998/HighFidelity-Beta-PR16031-76a4418.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20998/HighFidelity-Quest-Beta-PR16031-76a4418.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20998/HighFidelity-Beta-PR16031-76a4418.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20998/HighFidelity-Beta-Interface-PR16031-76a4418.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21099/HighFidelity-Beta-PR16031-fbfa0a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21099/HighFidelity-Beta-Interface-PR16031-fbfa0a4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21099/HighFidelity-Beta-PR16031-fbfa0a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21099/HighFidelity-Beta-Interface-PR16031-fbfa0a4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21099/HighFidelity-Beta-PR16031-fbfa0a4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21099/HighFidelity-Quest-Beta-PR16031-fbfa0a4.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21160/HighFidelity-Beta-PR16031-5d36d63.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21160/HighFidelity-Beta-Interface-PR16031-5d36d63.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21160/HighFidelity-Beta-PR16031-5d36d63.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21160/HighFidelity-Beta-Interface-PR16031-5d36d63.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21160/HighFidelity-Beta-PR16031-5d36d63.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21160/HighFidelity-Quest-Beta-PR16031-5d36d63.apk)

**Comment by MattHardcastle** [comment]
@danteruiz and I
1) rebase this PR onto master here https://github.com/highfidelity/hifi/pull/16150
2) remove the post build changes and some debug changes
3) pulled updated location changes here https://github.com/highfidelity/hifi/pull/16147

We can close this PR and merge.

**Pull request closed without merging**
