### PR TITLE
allow upside-down equip

### PR DESCRIPTION
**Pull request by sethalves**
- if hand is already in 'drop gesture' position when equipping something, don't unequip until the hand has been upright

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- find an equippable item
- practice equipping it and releasing it with the "drop gesture" -- turn hand upside down until the blue sphere appears, and click the trigger (not to be confused with the "grip" button on oculus, see http://www.ovrnews.com/wp-content/uploads/2016/12/touch-button-layout.jpg)
- with the item unequipped, put your hand into the "drop gesture" position, and equip the item
- confirm that the item doesn't immediately unequip
- turn your hand upright, then upside down again and drop them item
- generally test other aspects of equipping and unequipping items

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6763/app_12304_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6763/HighFidelity-Beta-PR12304-c4f57877dd4e28c96d06dab04eac26f59351d005.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6763/HighFidelity-Beta-PR12304-c4f57877dd4e28c96d06dab04eac26f59351d005.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
