### PR TITLE
FB17381 - Reticle.setVisible isn't working (for rc75)

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/17381/

the same as https://github.com/highfidelity/hifi/pull/14280 but for RC75

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14707/HighFidelity-Beta-PR14345-37eac2e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14707/HighFidelity-Beta-PR14345-37eac2e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14707/HighFidelity-Beta-Interface-PR14345-37eac2e.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

After all the testing I've done, there are very few things that make me sick in VR.
Moving the mouse while this script is active is one of them.

Cursor disappeared in both views as expected!

**Pull request merged**
