### PR TITLE
MS13955: Audio Stats are blank

### PR DESCRIPTION
**Pull request by wayne-chen**
This should fix MS[#13955](https://highfidelity.fogbugz.com/f/cases/13955/Audio-Stats-are-blank).

**TEST PLAN**

- Launch Interface
- Open `GOTO` app in tablet/toolbar (in either HMD/Desktop mode)
- Go to a domain listed in the ones available
- Enable `Settings->Developer Menu`
- Open audio statistics via `Developer->Audio->Stats...`
- The popup window should display audio interface statistics

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11708/HighFidelity-Beta-PR13722-78001a4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11708/HighFidelity-Beta-PR13722-78001a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11708/HighFidelity-Beta-Interface-PR13722-78001a4.exe

**Comment by qlimguicheteau** [comment]
FAIL 
@conklin94122 

Pass - Regions for the various types of Data/Graphs appear on Desktop. 
Fail - Statistics do not populate (everything is empty)
Fail - Graphs do not update
Fail - Show Graphs Cannot close
Fail - HMD display is empty
nostatistics
emptyhmd

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11724/HighFidelity-Beta-PR13722-f19a553.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11724/HighFidelity-Beta-PR13722-f19a553.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11724/HighFidelity-Beta-Interface-PR13722-f19a553.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11724/HighFidelity-Beta-PR13722-f19a553.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11724/HighFidelity-Beta-Interface-PR13722-f19a553.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Fail
@conklin94122 

Pass - Regions for stats appear on both Desktop and HMD
Pass - Show Graphs now closes
Pass - Data populates Graphs and Stats pages
Fail - Data does not register Dropped packets (used Clumsy)
Fail - Hover titles extrude beyond the boundaries of the windows (Latency, Mixer, Client, hover spots)

Fail(?) - Audio data only appears on servers (None in Serverless even though it can run video audio, and almost nothing in Localhost)
Fail(?) -  Unable to tell Incoming/Outgoing rates of audio, as nothing seems to clearly react. Microphone output, video audio and conversation on a Hifiqa domain did not seem to visibly affect any stats.

-- these (?) may be passes, depending on what the actual design behind the data was meant to reveal, and/or if data was misinterpreted.

**Comment by conklin94122** [comment]
@wayne-chen We moved this to v0.72.0, keep working in master, testing will come back to it once the 71 branch is cut.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12271/HighFidelity-Beta-PR13722-9a0807e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12271/HighFidelity-Beta-PR13722-9a0807e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12271/HighFidelity-Beta-Interface-PR13722-9a0807e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12271/HighFidelity-Beta-PR13722-9a0807e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12271/HighFidelity-Beta-Interface-PR13722-9a0807e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12278/HighFidelity-Beta-PR13722-5cf6b57.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12278/HighFidelity-Beta-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12278/HighFidelity-Beta-Interface-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12278/HighFidelity-Beta-PR13722-5cf6b57.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12278/HighFidelity-Beta-Interface-PR13722-5cf6b57.exe

**Comment by sethalves** [comment]
Why does removing the descriptions help this?

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12461/HighFidelity-Beta-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12461/HighFidelity-Beta-Interface-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12461/HighFidelity-Beta-PR13722-5cf6b57.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12461/HighFidelity-Beta-Interface-PR13722-5cf6b57.exe

**Comment by wayne-chen** [comment]
@sethalves I did that because I thought that the titles alone with the field names are self-explanatory enough.

**Comment by wayne-chen** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12474/HighFidelity-Beta-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12474/HighFidelity-Beta-Interface-PR13722-5cf6b57.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12474/HighFidelity-Beta-PR13722-5cf6b57.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12474/HighFidelity-Beta-Interface-PR13722-5cf6b57.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12490/HighFidelity-Beta-PR13722-796a18a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12490/HighFidelity-Beta-Interface-PR13722-796a18a.dmg

**Comment by wayne-chen** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12517/HighFidelity-Beta-PR13722-796a18a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12517/HighFidelity-Beta-PR13722-796a18a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12517/HighFidelity-Beta-Interface-PR13722-796a18a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12517/HighFidelity-Beta-PR13722-796a18a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12517/HighFidelity-Beta-Interface-PR13722-796a18a.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
There is no data in the graphs or values. Attempted speaking
graph
nographs
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2337713/hifi-log.txt)


 in various domains and no values or graphs showed data.

**Comment by wayne-chen** [comment]
Updated test plan. Audio stats will not show in a serverless domain.

**Comment by JeffClinton** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12821/HighFidelity-Beta-PR13722-796a18a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12821/HighFidelity-Beta-PR13722-796a18a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12821/HighFidelity-Beta-Interface-PR13722-796a18a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12821/HighFidelity-Beta-PR13722-796a18a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12821/HighFidelity-Beta-Interface-PR13722-796a18a.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

Upstream packet loss isn't appearing, but this is not related to this PR, and will be bugged separately.
upstream

**Pull request merged**
