### PR TITLE
fix a bug that caused dynamic children to wink in and out and then vanish

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that caused dynamic children to wink in and out and then vanish

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make sure the repro no longer repros:

Repro:
- Using edit.js, create two cube entities.
- Make one entity the child of the other.
- Make both entities dynamic.
- Observe over a couple of minutes: the child entity occasionally stops displaying then resumes displaying.

Notes:
- When the child entity isn't displaying, moving your camera often makes it display again.
- Eventually, the child entity is almost always not displaying.
- When the child entity is not displaying it is also not listed in the edit tool's entities list.
- The child displays properly while you're grabbing the root entity.
- If you manage to unlink the child from the parent the child starts displaying properly again.

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/7117/

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2944/HighFidelity-Beta-PR11282-41b51804dc3cad47de9bfe8d1e406272ca96a964.dmg

**Comment by Nex-Pro** [comment]
test this please

**Comment by Nex-Pro** [comment]
awaiting build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2950/HighFidelity-Beta-PR11282-41b51804dc3cad47de9bfe8d1e406272ca96a964.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2950/HighFidelity-Beta-PR11282-41b51804dc3cad47de9bfe8d1e406272ca96a964.exe

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
## PASS

Tried this in my dev build and got a repro.

Ran this build and no issue seen.  All good.

Does this need a full smoke test ? @sethalves 

hifi-snap-by--on-2017-08-31_17-23-26

**Comment by sethalves** [comment]
I don't think a smoke test is needed.

**Pull request merged**
