### PR TITLE
fix the update dialog to not show blank lines for missing version numbers

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- smoke test... 
- the changed code only runs on non-PR builds so you can't actually test the behavior in the PR.

**Comment by ZappoMan** [comment]
Fixes bugzid:320

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7bb21d370084c96e4e0d9d2fa20091febf178136 available at: https://gist.github.com/c5ad3c0e7f9e2ffa895a71a8e3dbb538<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7852.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7852.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode / Keyboard+Mouse**
Passes all standard tests.  No changes to baseline metrics over current RC seen.

**Pull request merged**
