### PR TITLE
add option to kick logged in users by fingerprint too

### PR DESCRIPTION
**Pull request by birarda**
- added DS setting to kick logged in users (via PAL) by machine fingerprint / IP address as well

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

You will need two Interface clients to complete this test plan.

**Kicking logged in user**
1. With a user who has permissions to kick users in your domain, use the "People" application (PAL) to kick another logged in user.
2. Confirm that in your domain server settings you see the username in the "permissions for specific users" with the connect permission disabled.

**Kicking anonymous user**
1. With a user who has permissions to kick users in your domain, use the "People" application (PAL) to kick a user who is not logged in.
2. Confirm that in your domain server settings you see a machine fingerprint in the "permissions for specific users" with the connect permission disabled.

**Multi-Kick Off**

1. Running the Sandbox from this PR, ensure that the "Multi-Kick for Logged In Users" setting is OFF. Note that it is an advanced setting in the Security group.
2. Perform the "Kicking logged in user" test. Additionally confirm that no rows have been added in the "Permissions for Users from IP Addresses" or "Permissions for Users with Machine Fingerprints".
3. Perform the "Kicking anonymous user" test. Confirm that no rows have been added to security tables other than the row for the kicked machine fingerprint.

Clear all rows added to the security tables as a result of these tests.

**Multi-Kick On*

1. Running the Sandbox from this PR, ensure that the "Multi-Kick for Logged In Users" setting is ON. Note that it is an advanced setting in the Security group.
2. Perform the "Kicking logged in user" test. Additionally confirm that one row has been added in the "Permissions for Users with Machine Fingerprints".
3. Logout on the machine that was kicked. Confirm that you cannot connect from that machine.
4. Manually clear the row for the machine fingerprint from the domain server settings and confirm that you can re-connect to the domain anonymously.
4. Perform the "Kicking anonymous user" test. Confirm that no rows have been added to security tables other than the row for the kicked machine fingerprint.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5194/HighFidelity-Beta-PR11883-897825403753d9c93dfb146cb55f1a1d6037660b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5194/HighFidelity-Beta-PR11883-897825403753d9c93dfb146cb55f1a1d6037660b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5198/HighFidelity-Beta-PR11883-e2082c0bcf236e8b5a9dfd49b6e2de174fea6cea.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5198/HighFidelity-Beta-PR11883-e2082c0bcf236e8b5a9dfd49b6e2de174fea6cea.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
PR #11883 

### PASS

***note issues at foot of these notes.***

Two Win10 PCs 

Two accounts.


Multi-Kick Off

Running the Sandbox from this PR, ensure that the "Multi-Kick for Logged In Users" setting is OFF. Note that it is an advanced setting in the Security group. **DONE**

Perform the "Kicking logged in user" test. **SUCCESS**

Additionally confirm that no rows have been added in the "Permissions for Users from IP Addresses" **SUCCESS** 
or "Permissions for Users with Machine Fingerprints". **SUCCESS**


Perform the "Kicking anonymous user" test. **SUCCESS**

Confirm that no rows have been added to security tables other than the row for the kicked machine fingerprint. **SUCCESS**


Clear all rows added to the security tables as a result of these tests. **DONE**



Multi-Kick On

Running the Sandbox from this PR, ensure that the "Multi-Kick for Logged In Users" setting is ON. **DONE**

Perform the "Kicking logged in user" test. **SUCCESS**

Additionally confirm that one row has been added in the "Permissions for Users with Machine Fingerprints". **SUCCESS**


Logout on the machine that was kicked. **DONE** 

Confirm that you cannot connect from that machine. **SUCCESS**

Manually clear the row for the machine fingerprint from the domain server settings **DONE**  
and confirm that you can re-connect to the domain anonymously. **SUCCESS**


Perform the "Kicking anonymous user" test. **SUCCESS** 

Confirm that no rows have been added to security tables other than the row for the kicked machine fingerprint. **SUCCESS**



Sub-Steps

Kicking logged in user

With a user who has permissions to kick users in your domain, use the "People" application (PAL) to kick another logged in user.
Confirm that in your domain server settings you see the username in the "permissions for specific users" with the connect permission disabled.

Kicking anonymous user

With a user who has permissions to kick users in your domain, use the "People" application (PAL) to kick a user who is not logged in.
Confirm that in your domain server settings you see a machine fingerprint in the "permissions for specific users" with the connect permission disabled.

Typical domain server log entry. (actual values removed)

[11/28 11:25:11] [DEBUG] [default] Refusing connection from node at 192.168.0.12:51304 with hardware address "XX:XX:XX:XX:XX:XX" and machine fingerprint QUuid("{VALID FINGERPRINT SEEN HERE}")


Issues seen:

At one point in this test after opening the PAL 
a third avatar model appeared to be in the same position as the "admin avatar" 
which was not located at the default position. 
The third avatar model was raised up so that its feet were at hip level with the "admin avatar" 
it was also using the same non-zero heading ( Y value ) 
Unable to repro or grab screenshot. 
Duration for this event was maybe 3 seconds. 
Admin ( localhost ) avatar was not logged in so the extra avatar model could not have been a person with a connection. 
The domain was not visible to other users or connected to an account or place name.

One attempt to kick the anonymous user from the PAL required the PAL to be refreshed before the kick button worked. Unable to repro.

**Pull request merged**
