### PR TITLE
Fixed issues in Browser.qml and UpdateDialog.qml

### PR DESCRIPTION
**Pull request by SamGondelman**
- Fixed QML errors in both Browser.qml and UpdateDialog.qml
- If you press "Cancel" on the Update Dialog, the update window will no longer reappear if you toggle the HUD (fogbugz [1131](https://highfidelity.fogbugz.com/f/cases/1131/Bug-Update-dialog-keeps-re-appearing-after-cancel))

### CODE REVIEW

**Comment by SamGondelman** [comment]
Testing:

- Press CTRL-B to bring up the Browser.  No QML errors should be logged.
- If the update dialog pops up (which it might not because this is a PR), no QML errors should be logged, and if you close the dialog using the "x" button or the "Cancel" button, the dialog should not reappear when you toggle the HUD.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99fc472d772ab942f92249ff7d40eb13fd716374 available at: https://gist.github.com/a6406919acedd9b04acb4eb28342561d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8208.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8208.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99fc472d772ab942f92249ff7d40eb13fd716374 available at: https://gist.github.com/a6406919acedd9b04acb4eb28342561d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8208.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8208.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Tested Windows 10 Desktop/HMD DK2
Responds as test notes indicates.  No errors logged/

**Pull request merged**
