### PR TITLE
Fix Android clang warnings due to unused compiler flags

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.atlassian.net/browse/BUGZ-1596

`if (UNIX)` is true for Android, should be `(UNIX AND NOT ANDROID)`.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21552/HighFidelity-Beta-PR16257-97dab24.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21552/HighFidelity-Quest-Beta-PR16257-97dab24.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21552/HighFidelity-Beta-PR16257-97dab24.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21552/HighFidelity-Beta-Interface-PR16257-97dab24.dmg

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21555/HighFidelity-Beta-PR16257-97dab24.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21555/HighFidelity-Beta-Interface-PR16257-97dab24.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21555/HighFidelity-Beta-PR16257-97dab24.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21555/HighFidelity-Quest-Beta-PR16257-97dab24.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21555/HighFidelity-Beta-PR16257-97dab24.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21555/HighFidelity-Beta-Interface-PR16257-97dab24.exe

**Pull request merged**
