### PR TITLE
By default, tablet icons will display on the toolbar in desktop mode.

### PR DESCRIPTION
**Pull request by hyperlogic**
There are two new general settings:
 
* Desktop Tablet Becomes Toolbar - In desktop mode tablet icons will be displayed in the toolbar. By default this is true.
* HMD Tablet Becomes Toolbar - In HMD mode tablet icons will be displayed in the toolbar. By default this is false.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test:
Test all buttons in the toolbar in desktop mode to ensure they work in toolbar mode and in tablet mode, in HMD and desktop mode.

|            | Desktop Tablet | HMD Tablet | Desktop Toolbar | HMD Toolbar |
|------------|----------------|------------|-----------------|-------------|
| audio      |                |            |                 |             |
| vr/desktop |                |            |                 |             |
| menu       |                |            |                 |             |
| bubble       |                |            |                 |             |
| snapshot       |                |            |                 |             |
| help       |                |            |                 |             |
| people       |                |            |                 |             |
| goto      |                |            |                 |             |
| marketplace      |                |            |                 |             |
| edit      |                |            |                 |             |
| users     |                |            |                 |             |

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47e87e1ad439f9f5dd7676da5d24fe9a8549cb87 available at: https://gist.github.com/eaa9f1789f4506822283d77384303a4d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-47e87e1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-47e87e1.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
Desktop Tablet|HMD Tablet|Desktop|Toolbar|HMD Toolbar
------------|--------------|----------|-------|-------|------------
audio|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
vr/desktop|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
menu|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
bubble|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
snapshot|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
help|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
people|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
goto|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
marketplace|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
edit|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**
users|**SUCCESS**|**SUCCESS**|**SUCCESS**|**SUCCESS**

**Comment by Nex-Pro** [comment]
### FAIL

HMD/Desktop TOOLBAR: Using snapshot hides the toolbar but does not restore
Restarted scripts cleared cache does not fix.
Restart Interface fixes also using settings/general to unset and set toolbar mode fixes it. ( not practical in HMD )


Desktop Tablet|HMD Tablet|Desktop|Toolbar|HMD Toolbar
------------|--------------|----------|-------|-------|------------
audio|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
vr/desktop|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
menu|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
bubble|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
snapshot|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
help|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
people|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
goto|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
marketplace|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
edit|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**
users|**SUCCESS**|**SUCCESS**|**SUCCESS**|**OPEN ONLY**

HMD toolbar: Popup windows would not dismiss via toolbar ICON.

Sorry about the markdown.

**Comment by Nex-Pro** [comment]
@seth Thanks, this will be very popular.

**Comment by sethalves** [comment]
Don't thank me!  Tony wrote it.  All I did was try to find a QA-victim.

**Comment by Nex-Pro** [comment]
@sethalves Hmm boy , don't I feel special now. Lol.

**Comment by Nex-Pro** [comment]
@hyperlogic Thanks

**Comment by hifi-gustavo** [comment]
Build console output for commit: e4076e6244cedf30ce433ba205ceb4339a6c2572 available at: https://gist.github.com/eaa9f1789f4506822283d77384303a4d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-e4076e6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-e4076e6.dmg

**Comment by hyperlogic** [comment]
@Nex-Pro Ok try it now, the toolbar hiding/showing should be fixed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5963c6ddc3c66d0237eeb21e31b22efe49d5fcbb available at: https://gist.github.com/eaa9f1789f4506822283d77384303a4d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-5963c6d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9694-5963c6d.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
@hyperlogic I think the behaviour of the toolbar is incorrect. If I click on an icon that pops up a window  shouldn't the icon should show as active. On clicking the icon again it should toggle back to normal. This way if I click the wrong icon I don't have to move my pointer to the close icon of the popup. Also having the icon active informs the user that there's a window open that might not be in view.(HMD). Also compare the icon transparency with the icons of the edit toolbar. They are no longer consistent.

**Comment by sethalves** [comment]
@Nex-Pro we'll track down the buttons that don't highlight correctly in another PR.

**Pull request merged**
