### PR TITLE
Manage audio interval timer in PAL

### PR DESCRIPTION
**Pull request by davidkelly**
Now, it is only running when PAL is up.  Was running (but doing nothing) when PAL was not up before - so a bit of efficiency savings...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: baed3bc3b3493ad9c75a3b808378bd2437751ad2 available at: https://gist.github.com/d6f49ee49647f3f24d85334b39afae0d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9386-baed3bc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9386-baed3bc.dmg

**Comment by ZappoMan** [comment]
test plan?

**Comment by davidkelly** [comment]
Test Plan:

All this does is turn on/off the interval timer for the vu meters in the PAL.  So a smoke test of PAL is sufficient.  Be sure to open/close the PAL many times, and make sure VU meters work.

**Comment by ZappoMan** [comment]
@davidkelly - is this ready for QA? if so you need to add the QA Ready flag.

**Comment by OmegaHeron** [comment]
Testing now.

**Comment by OmegaHeron** [comment]
QA Pass

Tested Windows 10

VU Meter works as expected.  Repeatedly opened/closed PAL (at least 50 times) with second AV mic on/off.  No issues seen - VU meter worked each time as expected.  Other PAL functions work as expected.

**Pull request merged**
