### PR TITLE
(tabletUX improvement) stylus and laser combo

### PR DESCRIPTION
**Pull request by druiz17**
This PR adds a laser at the tip of the stylus, in hope to improve the user experience when using that stylus on the tablet.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Be in HMD
- Bring up the tablet
- when your hand is near the tablet the stylus should appear
- a laser should appear when the stylus tip direction faces the tablet.
- When the laser is showing and over the tablet you should be able to highlight buttons, click on buttons when the trigger is pressed.
- Move the stylus tip closer to tablet..the laser should disappear when you get close to the tablet
- with the laser gone you should be able to the stylus like normal...highlighting and clicking buttons

-note:  at times the highlighting of button does not work, this issue is in current master and will be addressed later.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3395/HighFidelity-Beta-PR11392-10b7d513e2c90003e1a9393550d06d0f1ea2c8c8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3395/HighFidelity-Beta-PR11392-10b7d513e2c90003e1a9393550d06d0f1ea2c8c8.exe

**Comment by skytoad** [comment]
Tested: Pass. 

One QOL comment I have is that the laser pointer does not appear when pointing at the border of the tablet, except near the X button. It feels a little disjointed because of this, so in my opinion, it would feel smoother to have the laser pointer show on all parts of the tablet.

**Comment by anshuman64** [comment]
@druiz17 @mukulHF Here's the plan
1. Create a new PR just with stylus position changes to be merged
2. Create a new PR with the highlighting fix included in this PR
3. Fix the laser offset bug
4. Mukul tweaks parameters of laser disappearance distance
5. Merge
6. Create a new ticket for changing laser opacity

**Pull request closed without merging**
