### PR TITLE
misc avatar-entity fixes

### PR DESCRIPTION
**Pull request by sethalves**
- avoid writing left-over/garbage avatar-entity data to settings file
- when changing domains, flag avatar-entities as needing to be re-rezzed after clearing the entity-tree

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run the tests for the store in hifi://empty/
- with some avatar-entities attached, log out and back in
- make sure you still see the avatar-entities
- change to a new domain
- make sure you still see the avatar-entities

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5003/HighFidelity-Beta-PR11829-93fd2a6a6b042e5dd69d232c2069856ea4657c55.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5003/HighFidelity-Beta-PR11829-93fd2a6a6b042e5dd69d232c2069856ea4657c55.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/9331/Philips-Interface-json-has-a-shitton-technical-term-of-entities-when-he-s-not-visibly-wearing-any

**Comment by Nex-Pro** [comment]
@sethalves 

Attached purchases are persisting across domain jumps. So PASS on that point.

Issues: Crashed going to dev-welcome

Ents attach to hips when worn.

**Comment by Nex-Pro** [comment]
@sethalves I used the step-up that removes all avatar entities that is located in dev-content before doing this. If a user has 42 avatar entities I think they can't wear any more.

**Comment by Nex-Pro** [comment]
@sethalves That is in reference to the issue Philip has reported ( I believe  )

**Comment by Nex-Pro** [comment]
There's an API call to show how many avatar ents the user has.
Try:
Object.keys(MyAvatar.getAvatarEntityData()).length

**Comment by sethalves** [comment]
@Nex-Pro -- for clarity, this is a QA pass?  the other problems are also present in master?

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5056/HighFidelity-Beta-PR11829-93fd2a6a6b042e5dd69d232c2069856ea4657c55.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5056/HighFidelity-Beta-PR11829-93fd2a6a6b042e5dd69d232c2069856ea4657c55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5089/HighFidelity-Beta-PR11829-df07b66872b92615a781f78c19a020a15a79e86a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5089/HighFidelity-Beta-PR11829-df07b66872b92615a781f78c19a020a15a79e86a.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
Testing - finally :smile:

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
have someone watch you and confirm that you both see the same things
use CREATE to import the file you saved, above
see that there is now a mirrored sphere on your head
again use CREATE and select the sphere
use menu Edit --> Export Entities and export the sphere to a new file on your Desktop
use CREATE to delete the sphere from your head
use menu Edit --> Import Entities and select the file you exported
see that there is again a sphere on your head
go to another domain
see that the sphere is still there
close and relaunch interface
see that the sphere is still there
delete the sphere
go to another domain
see that the sphere remains gone
close and relaunch interface
see that the sphere remains gone

Looks good!

**Pull request merged**
