### PR TITLE
don't add HMAC verification hash without setting HMAC key

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9031/app_12964_PR_13e8da0d30bed099c2db94dd1bb23c4667382b16.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9051/app_12964_PR_dddb841d8317ae3c78c14a3ff77c943d854ed82c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9051/HighFidelity-Beta-PR12964-dddb841d8317ae3c78c14a3ff77c943d854ed82c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9051/HighFidelity-Beta-Interface-PR12964-dddb841d8317ae3c78c14a3ff77c943d854ed82c.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9062/app_12964_PR_8f6b51f0e07e0c2f977c82ceb637d6bead4d7c4d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9062/HighFidelity-Beta-PR12964-8f6b51f0e07e0c2f977c82ceb637d6bead4d7c4d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9062/HighFidelity-Beta-Interface-PR12964-8f6b51f0e07e0c2f977c82ceb637d6bead4d7c4d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9068/app_12964_PR_72640450c5bf49589727dcc6d0eb90179a4e7600.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9068/HighFidelity-Beta-PR12964-72640450c5bf49589727dcc6d0eb90179a4e7600.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9068/HighFidelity-Beta-Interface-PR12964-72640450c5bf49589727dcc6d0eb90179a4e7600.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9068/HighFidelity-Beta-PR12964-72640450c5bf49589727dcc6d0eb90179a4e7600.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9068/HighFidelity-Beta-Interface-PR12964-72640450c5bf49589727dcc6d0eb90179a4e7600.exe

**Pull request closed without merging**
