### PR TITLE
Fix MS17215: Auto-show Confirmed txns in Recent Activity when many Pending txns present

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS17215](https://highfidelity.fogbugz.com/f/cases/17215/If-you-have-too-many-pending-transactions-the-Wallet-Recent-Activity-doesn-t-show-you-and-confirmed-ones).

A hopeful RC71 integration.

### CODE REVIEW

**Comment by zfox23** [comment]
TEST THIS ASAP!

## Test Plan
1. On the STABLE Metaverse, purchase enough items such that you have >= 7 Pending transactions.
2. Open your (authenticated) Wallet.
3. Verify that your "Recent Activity" list shows "<X> pending transactions" AND a big enough list of transactions to fill the entire initial Recent Activity view.
4. Scroll down in Recent Activity and verify that new data is added to the list as you scroll.
5. Open My Purchases and verify that list scrolling behaves as you expect it to.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11794/HighFidelity-Beta-PR13738-1035a09.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11796/HighFidelity-Beta-PR13738-67528cb.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11796/HighFidelity-Beta-PR13738-67528cb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11796/HighFidelity-Beta-Interface-PR13738-67528cb.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlilaseguinolaza** [comment]
Pass @conklin94122

**Pull request merged**
