### PR TITLE
case 2589:  Local injector crash when output devices switch

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2589

fixing stacktrace: https://highfidelity.sp.backtrace.io/p/Interface/debug?time=all&error=14b86&debug=(%2214b86%22,0,0)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22417/HighFidelity-Beta-PR16476-617c502.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22417/HighFidelity-Beta-Interface-PR16476-617c502.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22417/HighFidelity-Beta-PR16476-617c502.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22417/HighFidelity-Quest-Beta-PR16476-617c502.apk)

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22421/HighFidelity-Beta-PR16476-617c502.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22421/HighFidelity-Quest-Beta-PR16476-617c502.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22421/HighFidelity-Beta-PR16476-617c502.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22421/HighFidelity-Beta-Interface-PR16476-617c502.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22430/HighFidelity-Beta-PR16476-4d12675.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22430/HighFidelity-Quest-Beta-PR16476-4d12675.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22430/HighFidelity-Beta-PR16476-4d12675.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22430/HighFidelity-Beta-Interface-PR16476-4d12675.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22430/HighFidelity-Beta-PR16476-4d12675.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22430/HighFidelity-Beta-Interface-PR16476-4d12675.exe

**Pull request closed without merging**
