### PR TITLE
Batch compile shaders

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Defer compilation of shaders since they cause a bubble at startup.

I haven't done the antialiasing one as it looked fairly complex.

The makeProgram blocks no longer show up in the traces; the time may be just transferred to the render blocks.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8802/app_12892_PR_b469cdfda2ae733263456c2f89fc7e98e978a2e3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8802/HighFidelity-Beta-PR12892-b469cdfda2ae733263456c2f89fc7e98e978a2e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8802/HighFidelity-Beta-Interface-PR12892-b469cdfda2ae733263456c2f89fc7e98e978a2e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8802/HighFidelity-Beta-PR12892-b469cdfda2ae733263456c2f89fc7e98e978a2e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8802/HighFidelity-Beta-Interface-PR12892-b469cdfda2ae733263456c2f89fc7e98e978a2e3.exe

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
This PR should introduce no user-visible changes, except possibly faster start-up for low-end machines.

To test that the change is effective create a trace file by running interface from the command line:
`interface --traceFile trace.json`

Exit interface when a domain has loaded. See PR12850 for info on creating & viewing traces:
https://github.com/highfidelity/hifi/pull/12850

After the PR the trace should not display long blocks (0.5 s or more) labelled build::DrawHazeDeferred, build::SubSurfaceScattering, build::LinearDepth, build::ToneMapping or build::DrawDeferredTask.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8825/app_12892_PR_b2e736da70686b603b036e41b089686fb723efae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8825/HighFidelity-Beta-PR12892-b2e736da70686b603b036e41b089686fb723efae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8825/HighFidelity-Beta-Interface-PR12892-b2e736da70686b603b036e41b089686fb723efae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8825/HighFidelity-Beta-PR12892-b2e736da70686b603b036e41b089686fb723efae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8825/HighFidelity-Beta-Interface-PR12892-b2e736da70686b603b036e41b089686fb723efae.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Boot up times are lower and block in trace file are significantly smaller

**Pull request merged**
