### PR TITLE
Notification circumstances

### PR DESCRIPTION
**Pull request by howard-stearns**
Expire announcement when announcer leaves.
Goto message light should go away when last announcement expired.

Also update snapshot.js to use new request module.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
1. You need two machines and two logins, who are connections of each other. 
2. Go to place A with user A on machine A.
3. With user B on machine B in public place B, take a snapshot and share it to feed, and also to blast to connections. 
4. Using B, make sure the snapshot shows up in feed. (Depending on scoring, you might have to type your name into the address bar to see your snapshot.)
5 . Let user B stay in B, but check user A on machine A. A should have the Goto message light on within a minute of step 3.
6. Have user B go to a different place. (It could be place A, but anywhere other than B is fine.) Within a minute, user A should see the Goto message light go off.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e57e804655d5d5043b985c4d16e6ba48ae0f519 available at: https://gist.github.com/d575c5fddd845701acab0f75a17c4b18<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10374-3e57e80.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10374-3e57e80.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25ab8e7e9443632253e5a69b392998025a88e09f available at: https://gist.github.com/d575c5fddd845701acab0f75a17c4b18<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10374-25ab8e7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10374-25ab8e7.dmg

**Comment by howard-stearns** [comment]
testested (from pr builds) following json and string change. pass.

**Pull request merged**
