### PR TITLE
Finer grained entity property locking

### PR DESCRIPTION
**Pull request by sethalves**
- break out some properties from "locked" into "lockedUserData" and "lockedSpatial".  Give delete-ability its own lock

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4951/Allow-users-to-lock-scripted-items-without-breaking-them

**Comment by sethalves** [comment]
This has some problems still, but I don't think it would take much to polish it up.  Things I know about:
- create's property page is now uglier
- create's property page ghosts everything if "locked" is false -- the list of ghosted controls should be based on which of the 4 locks are true
- create's entity-list page doesn't show these new lock properties
- the 3 new locks are protected by plain "locked" -- this is probably confusing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1294/HighFidelity-Beta-PR10870-2081a9ec00adaaa7167003f89cf6de52e5d70ef2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1294/HighFidelity-Beta-PR10870-2081a9ec00adaaa7167003f89cf6de52e5d70ef2.exe

**Comment by sethalves** [comment]
- lockedUserData: Many script (sit/chair) don't need to change anything but userData, so userData gets its own lock.  You could set the other 3 locks to true and the sit script will work, but the chair can't be moved or deleted. There is still room for griefing: someone can edit userData on the chair you're sitting on.

Here's an explanation of why I split the properties among the 4 locks the way I did:

- lockedSpatial: I want to make a chest with a hinged lid, and I want it locked down. I can lock the bottom part, but if I lock the top part, it wont open. With this PR, I can lock everything except lockedSpatial.  The lid can now be moved, but only as far as the hinge lets it.  Again, there's still room for griefing here, because someone can edit the lid far away, but recovery is easier.

- lockedDelete: sometimes you want things to be deleteable (fired arrows, whatever), sometimes you don't. This seems orthogonal to the changeability of the properties.

- locked: for everything else.

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1297/HighFidelity-Beta-PR10870-2081a9ec00adaaa7167003f89cf6de52e5d70ef2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1297/HighFidelity-Beta-PR10870-2081a9ec00adaaa7167003f89cf6de52e5d70ef2.dmg

**Comment by sethalves** [comment]
consensus is that we need even more control than this.  closing

**Pull request closed without merging**
