### PR TITLE
summon crowd

### PR DESCRIPTION
**Pull request by howard-stearns**
ac script to provide an on-demand crowd, and an interface script to summon it

### CODE REVIEW

**Comment by howard-stearns** [comment]
To test:
Run n instances of crowd-agent.js on your domain server. (Note observations comment in script.)
Then run summon.js as an interface script. Will get min(25, n) avatars near you, in a random pattern surrounding you, facing loosely in your direction.

**Comment by howard-stearns** [comment]
This version does not turn on animations, as doing so has a bug that will be fixed separately. So the avatars are just T-pose.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43c29500bf8483a5c974f03053fa77e43a3f142b available at: https://gist.github.com/16fa19a354fbbb5406a906f2ff3b014a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8712-43c2950.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8712-43c2950.dmg

**Comment by howard-stearns** [comment]
closed because this was instead merged to domain-check

**Pull request closed without merging**
