### PR TITLE
Fix AssetRequest crash where signal was not disconnected

### PR DESCRIPTION
**Pull request by huffman**
This is a potential fix for an issue Seth was looking into.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63d98b1b5c9a6ff9ae7e0bf89a55bbc6ee92c9a8 available at: https://gist.github.com/a4ab7ad3657ec80372700a2fcb60f9d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7731.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7731.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Using standard home scene over internet connection (!LAN)

First 2 launches I got immediate crash on invoking tidybot cleanup
Third launch I was able to invoke it 10 times with no crash.
Fourth launch 10 attempts 10 success
Fifth launch 10 attempts 10 success

Compared to RC6 there is a definite slower load of home scene be it pre-cahced or not.  I have to wait and watch things ever so slowly appear in this PR and that has been consistent across all my test passes.  With RC6 (across 5 runs) I did not see the laggy scene rez at all.  That may be related to #7726 as I run DS on a Linux system, but, it's odd I do not see it in RC6 as I do in this PR.

There's a god of random at play here somewhere.  After first 2 crashes I've not been able to crash it again.  I'd like some more time to test this before giving it my QA final eval.  I just need dinner first - I missed lunch today .  :)

**Comment by OmegaHeron** [comment]
Based on discussing this with devel talent I'm going to give it a QA Pass in that it is a definite improvement over what I see in RC6 and I'm reasonably certain the slow loading scene comes from my Ubuntu server platform needing PR7726 appearance.  It's, after many many many, additional runs not clear that this impacts scene load time - I've now seen RC6 behave poorly in that aspect several times as well.

**Comment by huffman** [comment]
Thanks @OmegaHeron . I took a look at your 2 crashes and they looked unrelated. Thanks for the thorough testing!

**Pull request merged**
