### PR TITLE
Binaryvrsdk support

### PR DESCRIPTION
**Pull request by binaryvr**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3311/HighFidelity-Beta-PR11356-4a68864f9836f8023a4a845525a41037ce5a8c39.exe

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3370/HighFidelity-Beta-PR11356-4a68864f9836f8023a4a845525a41037ce5a8c39.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3370/HighFidelity-Beta-PR11356-4a68864f9836f8023a4a845525a41037ce5a8c39.exe

**Comment by anshuman64** [comment]
Need these DLL's in your %HIFI_INSTALL% directory for this PR to work:
1. https://hifi-public.s3.amazonaws.com/anshuman/BinaryVR%20dll/binaryfacehmd.dll
2. https://hifi-public.s3.amazonaws.com/anshuman/BinaryVR%20dll/BugSplat64.dll
3. https://hifi-public.s3.amazonaws.com/anshuman/BinaryVR%20dll/royale.dll

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3639/HighFidelity-Beta-PR11356-42ffbaf1438a44ac21670f1e1dde9e022ff3370a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3639/HighFidelity-Beta-PR11356-42ffbaf1438a44ac21670f1e1dde9e022ff3370a.dmg

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3963/HighFidelity-Beta-PR11356-594e1fa4070aeee5272ece7a2989afd63dbedf43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3963/HighFidelity-Beta-PR11356-594e1fa4070aeee5272ece7a2989afd63dbedf43.exe

**Comment by hyperlogic** [comment]
Hi, we noticed a problem with the eye tracking.  Previously the FaceShift tracker was the only one that we supported, it would actually return estimations for the eye rotations.  Because the binaryVR plugin does not have eye tracking, we should do the following:
* add a virtual bool doesTrackEyes() method to the FaceTracker base class.
* implement it for binaryVr as returning false.
* change the if statement in Application::updateMyAvatarLookAtPosition from:
```
        if (faceTracker && !faceTracker->isMuted()) {
```
to
```
        if (faceTracker && faceTracker->doesTrackEyes() && !faceTracker->isMuted()) {
```
Then the eyes should track again

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5456/HighFidelity-Beta-PR11356-5a943a99272b8af797d9fac243109eff7aefe3d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5456/HighFidelity-Beta-PR11356-5a943a99272b8af797d9fac243109eff7aefe3d0.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5593/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5593/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.dmg

**Comment by themelissabrown** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6084/app_11356_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6084/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6084/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7320/app_11356_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7320/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7320/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7888/app_11356_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7888/HighFidelity-Beta-PR11356-18472cb7ed738d2f82bbb3eb26c96c9e265a7fab.dmg

**Comment by birarda** [comment]
Before we merge this, can we get a version of the binary VR SDK that uses the VS 2015/2017 redistributables? We're going to be trying to make all externals require the same redistributables as our applications (so we only have to bundle the one) and I'd rather not make the list of SDKs needing an update longer if we merge this.

**Comment by MiladNazeri** [comment]
build this please

**Comment by MiladNazeri** [comment]
build this please

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8714/HighFidelity-Beta-PR11356-4ff896c34715661f5896a5ecf1bd81c24a366e06.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8714/HighFidelity-Beta-PR11356-4ff896c34715661f5896a5ecf1bd81c24a366e06.dmg

**Comment by ZappoMan** [comment]
I think we can officially close this, It's over 13 months old, and hasn't been updated in over 6 months

**Pull request closed without merging**
