### PR TITLE
fix ATP range requests for small ktx files

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug where range requests for small KTX files would always fail

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/550/HighFidelity-Beta-PR10656-b6d2dff051d4c579ab680392c9a48f4156db50de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/550/HighFidelity-Beta-PR10656-b6d2dff051d4c579ab680392c9a48f4156db50de.exe

**Comment by marko8904** [comment]
test this please

**Comment by birarda** [comment]
### Test Plan

On master, launch the sandbox with tutorial content and visit localhost/garden. Confirm that you see a failed request in your log for Blank.ktx.

Do the same test with this PR. In your log you should see that the Blank.ktx request is successful.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/551/HighFidelity-Beta-PR10656-b6d2dff051d4c579ab680392c9a48f4156db50de.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/557/HighFidelity-Beta-PR10656-b6d2dff051d4c579ab680392c9a48f4156db50de.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/557/HighFidelity-Beta-PR10656-b6d2dff051d4c579ab680392c9a48f4156db50de.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Fail** I cannot seem to compare as I can't even complete the tutorial in Master. Tried clean install / reloading scripts etc, but I cannot seem to teleport at the stage where you are supposed to go into the blue circle ahead, If I do teleport it just sends me on top of the building?. Logs did not show any Blank.ktx either due to this. Tried just teleporting into garden but didn't see anything in the log.

**Comment by YuppyPlays** [comment]
Testing complete:

Error I experienced persisted with this PR also?

Would you like me to attach logs?

**Comment by PhilipRosedale** [comment]
@YuppyPlays @birarda I think this needs to be rebuilt to get howard's fix to prob with teleport to roof of tutorial.

**Comment by birarda** [comment]
@YuppyPlays this is ready for a re-test now

**Comment by YuppyPlays** [comment]
@birarda no problem, I will test once ready :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/872/HighFidelity-Beta-PR10656-cf9a97cf101bb6003f8f50579e595efc74e751ae.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/872/HighFidelity-Beta-PR10656-cf9a97cf101bb6003f8f50579e595efc74e751ae.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

I can confirm now the error shows in Master but is successful at loading the blank.ktx in this PR.

**Pass** :)

**Pull request merged**
