### PR TITLE
possibly fix a couple of crashes

### PR DESCRIPTION
**Pull request by sethalves**
- possible fix to resizing-window crash

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/101885110279757

**Comment by ZappoMan** [comment]
What's the repro test case @sethalves ?

**Comment by sethalves** [comment]
I don't know

**Comment by hifi-gustavo** [comment]
Build console output for commit: db5c6d80d2b234d4759c1112d21ded747d10e2e2 available at: https://gist.github.com/4ea0e6abd561e2161413<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7379.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: db5c6d80d2b234d4759c1112d21ded747d10e2e2 available at: https://gist.github.com/4ea0e6abd561e2161413<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7379.dmg

**Comment by bluetoe** [comment]
I tried much window resizing with this on Win 7. No crash. I'll switch to latest now.

**Comment by bluetoe** [comment]
I could not make it crash. But maybe someone else should test this because I have not had many crashes from resizing the window and I do resize often. I tried most testing with overlays displayed but just for run I turned them off and ...Haha... tiny snapshots
hifi-snap-by-twa_hinkle-on-2016-03-17_11-21-06

**Pull request merged**
