### PR TITLE
reduce calls to isPointOnDesktopWindow in controllerModules

### PR DESCRIPTION
**Pull request by druiz17**
reduce calls to isPointOnDesktopWindow

ticket - https://highfidelity.fogbugz.com/f/cases/10867/Minimize-calls-to-blocking-OffscreenUi-isPointOnDesktopWindow-in-controller-modules

traces 
- desktop mode - 
[trace-20180118_1036.json.gz](https://github.com/highfidelity/hifi/files/1644067/trace-20180118_1036.json.gz)

- HMD mode - 
[trace-20180118_1038.json.gz](https://github.com/highfidelity/hifi/files/1644068/trace-20180118_1038.json.gz)

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in HMD
- make sure you can still far grab entity
- enable Script log (HMD friendly) under developer menu
- make sure that the laser still interact with the script log window

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6420/app_12206_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6420/HighFidelity-Beta-PR12206-d88ff701b5f9c21e5b3363d9edacea59af513311.exe

**Comment by conklin94122** [comment]
build this please

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6451/app_12206_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6451/HighFidelity-Beta-PR12206-d88ff701b5f9c21e5b3363d9edacea59af513311.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6451/HighFidelity-Beta-PR12206-d88ff701b5f9c21e5b3363d9edacea59af513311.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing completed. PASSED.

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
