### PR TITLE
OSX Rift functionality

### PR DESCRIPTION
**Pull request by jherico**
Re-enable Rift functionality on OSX.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 854754e9a2d610231d5c93beca7e793002f6b352 available at: https://gist.github.com/a679dc4bbb2f1bb079abb607b92ec9a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f768b13b9a61c10ead0dc072a3ca08fbf3a024a available at: https://gist.github.com/a679dc4bbb2f1bb079abb607b92ec9a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.dmg

**Comment by ZappoMan** [comment]
I tried running this on my MBP, and it doesn't show the Oculus as a Display Option. I have installed the Oculuse 0.5 runtime for mac, and it DOES show me the demo scene... So I'm not sure what else I need to do.

**Comment by jherico** [comment]
OSX builds currently have an issue with the plugin system.  The code is looking in the wrong place for the loadable plugins.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 335841bf0f2ddb9ad614fd0d34c011ebb9d89a94 available at: https://gist.github.com/a679dc4bbb2f1bb079abb607b92ec9a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7841.dmg

**Comment by ZappoMan** [comment]
Testing Plan:
- Make sure to do a basic smoke test on windows to make sure we didn't break anything
- Test in 2D desktop, Vive, and Oculus

**Pull request merged**
