### PR TITLE
Case 22273: Create lite snapping prototype

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.fogbugz.com/f/cases/22273/
https://highfidelity.fogbugz.com/f/cases/22341/
https://highfidelity.fogbugz.com/f/cases/22342/
https://highfidelity.fogbugz.com/f/cases/22367/
https://highfidelity.fogbugz.com/f/cases/22432/

Do Not Merge:
This is a prototype, work is still in progress

To snap an entity to the surface of another entity in Create, hold Ctrl while dragging the entity around by its bounding box. The entity will snap and align to the surface of the first hit entity under the mouse.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18781/HighFidelity-Beta-PR15407-fba90c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18781/HighFidelity-Beta-Interface-PR15407-fba90c1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18781/HighFidelity-Beta-PR15407-fba90c1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18781/HighFidelity-Quest-Beta-PR15407-fba90c1.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18781/HighFidelity-Beta-PR15407-fba90c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18781/HighFidelity-Beta-Interface-PR15407-fba90c1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18934/HighFidelity-Beta-PR15407-7bb5772.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18934/HighFidelity-Beta-Interface-PR15407-7bb5772.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18934/HighFidelity-Beta-PR15407-7bb5772.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18934/HighFidelity-Beta-Interface-PR15407-7bb5772.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18934/HighFidelity-Beta-PR15407-7bb5772.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18934/HighFidelity-Quest-Beta-PR15407-7bb5772.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18952/HighFidelity-Beta-PR15407-ef65d23.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18952/HighFidelity-Quest-Beta-PR15407-ef65d23.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18952/HighFidelity-Beta-PR15407-ef65d23.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18952/HighFidelity-Beta-Interface-PR15407-ef65d23.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18952/HighFidelity-Beta-PR15407-ef65d23.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18952/HighFidelity-Beta-Interface-PR15407-ef65d23.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18989/HighFidelity-Beta-PR15407-a921296.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18989/HighFidelity-Beta-Interface-PR15407-a921296.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18989/HighFidelity-Beta-PR15407-a921296.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18989/HighFidelity-Quest-Beta-PR15407-a921296.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18989/HighFidelity-Beta-PR15407-a921296.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18989/HighFidelity-Beta-Interface-PR15407-a921296.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19011/HighFidelity-Beta-PR15407-e0fdaac.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19011/HighFidelity-Beta-Interface-PR15407-e0fdaac.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19011/HighFidelity-Beta-PR15407-e0fdaac.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19011/HighFidelity-Quest-Beta-PR15407-e0fdaac.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19011/HighFidelity-Beta-PR15407-e0fdaac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19011/HighFidelity-Beta-Interface-PR15407-e0fdaac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19095/HighFidelity-Beta-PR15407-49d1de6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19095/HighFidelity-Beta-Interface-PR15407-49d1de6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19095/HighFidelity-Beta-PR15407-49d1de6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19095/HighFidelity-Quest-Beta-PR15407-49d1de6.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19095/HighFidelity-Beta-PR15407-49d1de6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19095/HighFidelity-Beta-Interface-PR15407-49d1de6.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19115/HighFidelity-Beta-PR15407-8fc5d08.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19115/HighFidelity-Quest-Beta-PR15407-8fc5d08.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19115/HighFidelity-Beta-PR15407-8fc5d08.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19115/HighFidelity-Beta-Interface-PR15407-8fc5d08.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19115/HighFidelity-Beta-PR15407-8fc5d08.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19115/HighFidelity-Beta-Interface-PR15407-8fc5d08.exe

**Comment by huffman** [comment]
Closing due to DNM

**Pull request closed without merging**
