### PR TITLE
DNM: test build for objects showing up at origin

### PR DESCRIPTION
**Pull request by AndrewMeadows**
There have been reports of objects incorrectly showing up at the origin after editing a lot of objects with edit.js, however I've been having trouble reproducing the problem.  This PR is for a hacked Interface that logs extra info about objects that are placed near the origin.  The hope is that someone will reproduce the bug and then supply their logs for analysis.

The internal bug link is:

https://highfidelity.fogbugz.com/f/cases/2041/Unlocking-entities-makes-them-move-to-0-0-0

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3eef355d7454f12bd8494200b64b4b57570a5eeb available at: https://gist.github.com/6d26d93cf64e1df743bbfe38772e6034<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8978-3eef355.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8978-3eef355.dmg

**Comment by ZappoMan** [comment]
I've been pondering this... it's possible we're seeing a case where the position property is ending up in a packet that gets lost... that would cause an entity to be at the default position which is zero... presumably though, this would be repaired as soon as you look around and move your head...

Maybe this only happens to people running in desktop mode, who aren't changing their view...

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3eef355d7454f12bd8494200b64b4b57570a5eeb available at: https://gist.github.com/6d26d93cf64e1df743bbfe38772e6034<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8978-3eef355.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8978-3eef355.dmg

**Comment by ZappoMan** [comment]
@AndrewMeadows  - I assume you don't need this PR anymore, I'm closing it... you can reopen if you need it again.

**Pull request closed without merging**
