### PR TITLE
Add adjustments to tablet model and screen offset

### PR DESCRIPTION
**Pull request by druiz17**
To allow the pointers to intersect with the tablet model. The tablet model need to be adjusted and the tablet screen offset to the model screen needed to be increased.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6156/app_12125_PR.apk

**Comment by druiz17** [comment]
Test plan
1
- make sure that the lasers can interact with the bezel of the tablet.

2. Perform the following tests for about 5 - 10 minutes.
- switch from desktop to HMD
- make sure that every area of the tablet screen is responsive...just different apps while performing this test
- repeat the last to steps
3. Perform the following test for about 5 - 10 minutes
- In HMD  mode open tablet and open create app
- make sure that every area of the tablet screen is responsive
- go back to the home screen and repeat steps.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6156/HighFidelity-Beta-PR12125-125eb9ce445132f7fcf6c3159b058953cf2af2b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6156/HighFidelity-Beta-PR12125-125eb9ce445132f7fcf6c3159b058953cf2af2b7.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
