### PR TITLE
Improve stability for HMD third person avatars

### PR DESCRIPTION
**Pull request by hyperlogic**
Previously there was a hack where the sensor to world matrix was NOT updated in HMD mode if the camera was third person. The reason the hack existed was to make third person camera less nauseating for users.  However this had a major drawback.  It led to avatar hip spasms when the user turned around in the tracked volume, while in third person camera.

To fix this issue properly, the hack which prevented updating the sensor to world matrix was removed, and now the third person camera is now computed in sensor space relative to the hmd.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/28/room-scale-third-person-makes-you-Jacob-s-Ladder-crazy-to-other-observers

**Comment by hyperlogic** [comment]
QA Test plan: 
  * While wearing an HMD, enter third person view.  (by using the mouse wheel) or via the tablet Menu > View > Third Person menu.
  * You should be able to see your avatar in front of you.
  * If you rotate 180 in the physical room.  You won't be able to see your avatar anymore, but the camera should not be yanked around behind the avatar.  
  * Also when other users look at your avatar after you have rotated, it should look natural, the avatar should not look twisted or move unnaturally.
  * Ensure that you can fly while in third person HMD camera.
  * Ensure that the mouse wheel can still be used to move the camera towards the avatar's head.
  * Ensure that the desktop first and third person camera still function as normal.
  * Ensure that the HMD first person camera still functions as normal.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6083/app_12107_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6083/HighFidelity-Beta-PR12107-61edd83987dbe2c5629f82b4387439d2f33af42d.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6086/app_12107_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6086/HighFidelity-Beta-PR12107-61edd83987dbe2c5629f82b4387439d2f33af42d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6094/app_12107_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6094/HighFidelity-Beta-PR12107-61edd83987dbe2c5629f82b4387439d2f33af42d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6094/HighFidelity-Beta-PR12107-61edd83987dbe2c5629f82b4387439d2f33af42d.exe

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing complete. FAILED. The avatar appeared jerky and twisted when viewing as an observer. Please reference the following image.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6145/HighFidelity-Beta-PR12107-e28f13c1dbdec22e38981526c3e1fefed49efa12.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6145/HighFidelity-Beta-PR12107-e28f13c1dbdec22e38981526c3e1fefed49efa12.exe

**Comment by hyperlogic** [comment]
I need more context on how this image was created.  I can imagine that putting your hand controllers behind you on the desk might cause this pose.  However, there is a specific kind of "the avatar should not look twisted or move unnaturally" that this issue is ment to fix.  which is a different then the above screen shot.  This PR is intended to fix the issue where the head is turned 180 degrees away from the toes, which can cause the avatar to twist unnaturally and begin twitching and making spastic motions.  Can you re-test and compare with the behavior on master to see if this use case is improved?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6174/app_12107_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6174/HighFidelity-Beta-PR12107-220b7f5e55b7532fcccdfaa6578bfae68f9b048e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6174/HighFidelity-Beta-PR12107-220b7f5e55b7532fcccdfaa6578bfae68f9b048e.dmg

**Comment by QAadahlin** [comment]
@conklin94122 Re-tested  PR#12107. PASSED as we could not reproduce the jerking and twisting that was observed previously.

**Pull request merged**
