### PR TITLE
10108 marketplace category cannot scroll

### PR DESCRIPTION
**Pull request by ElderOrb**
This PR should address the issue https://highfidelity.manuscript.com/f/cases/10108/marketplace-category-cannot-scroll

by introducing the following changes for 'marketplace' screen: 

On expanding categories:
- main scrollbar (at the right) will be hidden
- categories list will get its own scrollbar if doesn't fit into screen

On collapsing categories
- main scrollbar reappear
- categories scrollbar hidden together with categories

**Test plan**

0. Download 'marketplacesInject.js' from here: https://www.dropbox.com/s/6cp1b7mbyywedkz/marketplacesInject.js?dl=0
1. Put it to the following directory:  "<Hifi Install Folder\scripts\system\html\js\marketplacesInject.js". This is required to create additional categories 'Animation1' - 'Animation10'. 
2. Switch to VR
3. Open tablet, go to marketplace
4. Ensure expanding categories hides main scrollbar (at the right edge) and shows one for categories. 
5. Ensure collapsing categories returns main scrollbar and hides categories scrollbar
6. Repeat steps 3-5 for Desktop mode.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5414/HighFidelity-Beta-PR11936-c007c6d00f5317c0d9fc6afb7d1ff4da9eceeef6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5420/HighFidelity-Beta-PR11936-c007c6d00f5317c0d9fc6afb7d1ff4da9eceeef6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5420/HighFidelity-Beta-PR11936-c007c6d00f5317c0d9fc6afb7d1ff4da9eceeef6.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Download 'marketplacesInject.js' from here: https://www.dropbox.com/s/6cp1b7mbyywedkz/marketplacesInject.js?dl=0 | Pass
Put it to the following directory: "<Hifi Install Folder\scripts\system\html\js\marketplacesInject.js". This is required to create additional categories 'Animation1' - 'Animation10'. | Pass
Switch to VR | Pass
Open tablet, go to marketplace | Pass
Ensure expanding categories hides main scrollbar (at the right edge) and shows one for categories. | Pass
Ensure collapsing categories returns main scrollbar and hides categories scrollbar | Pass
Repeat steps 3-5 for Desktop mode. | Pass

Note: It seems like the scrollbar doesn't seem to want to change while the page is _still_ loading. After it's completely loaded however the scrollbar does move to the correct position.

**Pull request merged**
