### PR TITLE
21200 Transfer from far-grab to near grab when close

### PR DESCRIPTION
**Pull request by volansystech**
1) Implemented Far to near grab functionality.	

As we already mentioned in bugs comment distance between currentObjectPosition and Avatar's hand is **not precise / accurate**. In some scenarios it does gives value lesser than 0.75 though UI shows object very nearer. When it does, we can convert far-grab into near-grab.

2) If entity has capabilities of being equipped, then drawing entity form far to near also converts into Equipped state.

@PhilipRosedale , @sethalves : Please review and share your feedback.

@themelissabrown FYI

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by themelissabrown** [comment]
Testing notes: With a series of different objects, practice grabbing with far grab and transferring to near grab once the object is within reach.

**Comment by themelissabrown** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70855b1c5318288040314e6008b69e2ef7d6f1ae available at: https://gist.github.com/dbe9a5c3d16bafe70a5d126071ee7322<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-70855b1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-70855b1.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
Tested this with Win10 and Vive.

This has changed the existing near grab range to be almost 3 feet for small objects.
The transition from far to near-grab on larger objects, such as the blocks at dev-welcome doesn't seem very predictable/consistent.

Seems to only really work when the initial far-grab is just beyond the near-grab range.

On the basis of this initial test I don't see that this adds much as it is quicker to simply drag and re-drag as before.

**Comment by themelissabrown** [comment]
@sethalves will provide them feedback. Thanks piper!

**Comment by ctrlaltdavid** [comment]
Perhaps rather than transitioning to near-grab/equipped immediately the entity is closer than the threshold distance, continue far-grab until the distance starts increasing and only then transition to near-grab/equipped.

**Comment by volansystech** [comment]
@Nex-Pro 

This has changed the existing near grab range to be almost 3 feet for small objects.
--> Its changed while Far-grabbing only. Existing near-grab is as it is. Why we did put threshold of 0.75? Its long story written at https://worklist.net/21200

The transition from far to near-grab on larger objects, such as the blocks at dev-welcome doesn't seem very predictable/consistent.
--> If Object is large, then we have to try very Hard to drag it very closer. 

Seems to only really work when the initial far-grab is just beyond the near-grab range
--> Try to grab object while stretching your hand from chest level and then draw at chest level. Its not working accurately when we draw hand at hip level. Again question asked in, https://worklist.net/21200

We successfully grabbed following objects by pulling it down object under to 0.75.
1) EZ-Cube
2) EZ-Blok
3) EZ-Tube
4) Entity on which written:: "I am the Heaviest cube" [we could not get its name]
5) EZ-Arch
6) EZ-Ramp

Objective of WL #21200 is to develop functionality to convert object which drawn from far-grab if it is near. --> Done
Equip it if it has capabilities. --> Done

@Nex-Pro , @sethalves , @themelissabrown 
As we commented on WL, our calculations for distance between object to hand is not accurate / precise in all situations. Due to that conversion from far-grab to near-grab is affected. 

Correcting distance measuring calculations / algorithm is whole new different task.

**Comment by volansystech** [comment]
@themelissabrown , @sethalves  Any thoughts on this?

**Comment by hifi-gustavo** [comment]
Build console output for commit: abc87c0338c1417a86a9813a57a039864eacc256 available at: https://gist.github.com/dbe9a5c3d16bafe70a5d126071ee7322<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-abc87c0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-abc87c0.dmg

**Comment by volansystech** [comment]
@themelissabrown , We just resolved comments from @Nex-Pro . Please mark this PR again as **QA Ready** and please ask QA to re-test newer build.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e2899678a95c882f1de9749029a11433ccb2487 available at: https://gist.github.com/dbe9a5c3d16bafe70a5d126071ee7322<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-9e28996.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-9e28996.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1abbca6737d9426f0522743066deb3c7ab0c502b available at: https://gist.github.com/dbe9a5c3d16bafe70a5d126071ee7322<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-1abbca6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-1abbca6.dmg

**Comment by PhilipRosedale** [comment]
QA Pass for me.   Can we resolve conflicts?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 87ceebca826a9092331f7dd8a2622547804bc56f available at: https://gist.github.com/dbe9a5c3d16bafe70a5d126071ee7322<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-87ceebc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10210-87ceebc.dmg

**Comment by volansystech** [comment]
@PhilipRosedale , @themelissabrown 
Conflict has been resolved and we also tested above auto generated binaries, they works fine.

**Pull request merged**
