### PR TITLE
glTF importer fixes (Corruption while reading .bin files and allows loading local files)

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR adds some fixes to the way .bin files are read. 
It also fixes this crash:
https://highfidelity.manuscript.com/f/cases/16623/Crash-when-loading-GLTF-model-file-from-local-directory-on-Windows

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Download this file https://hifi-content.s3.amazonaws.com/luis/gltf/Fordish.zip and unzip it.
- You should be able to import the uncompressed/local file: fordish_filter.gltf.
- You should be able to import the remote file: https://hifi-content.s3.amazonaws.com/luis/gltf/fordish_filter.gltf

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11336/HighFidelity-Beta-PR13615-c574305.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11336/HighFidelity-Beta-Interface-PR13615-c574305.dmg

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11340/HighFidelity-Beta-PR13615-c574305.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11340/HighFidelity-Beta-PR13615-c574305.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11340/HighFidelity-Beta-Interface-PR13615-c574305.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11340/HighFidelity-Beta-PR13615-c574305.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11340/HighFidelity-Beta-Interface-PR13615-c574305.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Paused testing, need to learn how to import GLTF files

**Comment by qliejahner** [comment]
Resumed testing

**Comment by qliejahner** [comment]
PASS @qliacoombs @Qliemillar 

Create > Model worked for both URLs.

**Pull request merged**
