### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6746/app_12299_PR.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6746/HighFidelity-Beta-PR12299-399c24bf06b622309c3132153a464fb45b69ad6c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6750/app_12299_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6750/HighFidelity-Beta-PR12299-399c24bf06b622309c3132153a464fb45b69ad6c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6750/HighFidelity-Beta-PR12299-399c24bf06b622309c3132153a464fb45b69ad6c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6871/app_12299_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6871/HighFidelity-Beta-PR12299-399c24bf06b622309c3132153a464fb45b69ad6c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6871/HighFidelity-Beta-PR12299-399c24bf06b622309c3132153a464fb45b69ad6c.dmg

**Pull request merged**
