### PR TITLE
RC63.4 : Potential fix for crash in render : Backtrace #827

### PR DESCRIPTION
**Pull request by samcake**
This bug https://highfidelity.fogbugz.com/f/cases/12237/CRASH-in-Item-update-when-_payload-is-null
There is no real repro because in theory, a null Payload in a valid Render Item shouldn't happen.
I added a test before updating a render::Item to make sure it exists.

This may be not enough to avoid the crash, time and backtrace will tell...

TEST PLAN (edited by jcII)
There is no repro for that crash.
It shouldn't break anything.
Install, launch, walk around sandbox and any domain in desktop mode and in HMD (if applicable). If it doesn't crash or look seriously messed up it passes.
Compare any defects against stable
Please run on win/desk, mac/desk, win/hmd (either).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7128/app_12384_PR.apk

**Comment by conklin94122** [comment]
please build this

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7131/app_12384_PR.apk

**Comment by jherico** [comment]
cherry picked 0b71a1c directly into rc63.4

**Pull request closed without merging**
