### PR TITLE
Import av entities

### PR DESCRIPTION
**Pull request by sethalves**
- allow importing and exporting of avatar entities and correctly map avatar-as-parent

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- save this json file to your local disk
```javascript
{
    "Entities": [
        {
            "clientOnly": 1,
            "collidesWith": "",
            "collisionMask": 0,
            "collisionless": 1,
            "created": "2017-10-02T23:02:57Z",
            "dimensions": {
                "x": 0.5,
                "y": 0.5,
                "z": 0.5
            },
            "id": "{e2349542-bcdc-4578-a583-2f083bf045d5}",
            "ignoreForCollisions": 1,
            "lastEdited": 1506985436198104,
            "lastEditedBy": "{d522ba6c-e2cb-453a-8361-4688f478044a}",
            "modelURL": "http://headache.hungry.com/~seth/hifi/sphere/sphere.obj",
            "name": "avatar entity sphere",
            "owningAvatarID": "{00000000-0000-0000-0000-000000000000}",
            "parentID": "{00000000-0000-0000-0000-000000000001}",
            "parentJointIndex": 63,
            "queryAACube": {
                "scale": 2.598076105117798,
                "x": -1.299038052558899,
                "y": -1.299038052558899,
                "z": -1.299038052558899
            },
            "rotation": {
                "w": -0.1340387463569641,
                "x": -0.015055418014526367,
                "y": 0.9847862720489502,
                "z": -0.10955753922462463
            },
            "shapeType": "sphere",
            "type": "Model",
            "userData": "{\"grabbableKey\":{\"grabbable\":1}}"
        }
    ],
    "Version": 73
}
```
- have someone watch you and confirm that you both see the same things
- use CREATE to import the file you saved, above
- see that there is now a mirrored sphere on your head
- again use CREATE and select the sphere
- use menu Edit --> Export Entities and export the sphere to a new file on your Desktop
- use CREATE to delete the sphere from your head
- use menu Edit --> Import Entities and select the file you exported
- see that there is again a sphere on your head
- go to another domain
- see that the sphere is still there

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3985/HighFidelity-Beta-PR11554-f349ba3674d8d8b7c20f0758b513ebf0ae04ce60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3985/HighFidelity-Beta-PR11554-f349ba3674d8d8b7c20f0758b513ebf0ae04ce60.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
[Used 2 PC's to test]

have someone watch you and confirm that you both see the same things **Check**
use CREATE to import the file you saved, above **Check**
see that there is now a mirrored sphere on your head **Check**
again use CREATE and select the sphere **Check**
use menu Edit --> Export Entities and export the sphere to a new file on your Desktop **Check**
use CREATE to delete the sphere from your head **Check**
use menu Edit --> Import Entities and select the file you exported **Check**
see that there is again a sphere on your head **Check**
go to another domain **Check**
see that the sphere is still there **Check**
close and relaunch interface **Check**
see that the sphere is still there **Check**
delete the sphere **Check**
go to another domain **Check**
see that the sphere remains gone **Check**
close and relaunch interface **Check**
see that the sphere remains gone **Check**

also:
make sure the tablet and, in particular, the styluses still work **Check**

**Notes: some delays caused by extremely slow loading time into Dev-Welcome, specifically dev-welcome seemed to load slow, other domains seemed to load normally**

**Pull request merged**
