### PR TITLE
Fix the spectator camera

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

- Run Spectator Camera test plan (526) - confirm that view on viewfinder matches the display on screen with pixel perfection (not cropped).
- Check the render utilities.
- Confirm that raising/lowering keyboard on tablet functions properly in both desktop / hmd mode.
- Test the webTablet script, notifications, that they work properly in both desktop / hmd mode.
- Run Create Mode test plan (1938) - confirm pages look correct in desktop / hmd mode.
- Use the attached script to confirm the correct Interface window dimensions are reported.

[testWindowDimensions.zip](https://github.com/highfidelity/hifi/files/1701194/testWindowDimensions.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6972/app_12350_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6972/HighFidelity-Beta-PR12350-665bd6825fd43eb1933a1e5ebb952b3246ff09ca.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6972/HighFidelity-Beta-PR12350-665bd6825fd43eb1933a1e5ebb952b3246ff09ca.exe

**Pull request merged**
