### PR TITLE
Fix AssetClient not properly cleaning up canceled requests

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e46b434894bdf364b148a3297138250fffb95cb available at: https://gist.github.com/1c43c489a3742bdc46133ca4a265ffda<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7736.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7736.dmg

**Comment by OmegaHeron** [comment]
Initial testing points to this helping with tidybot crash.  But, since it can be somewhat random my plan is to repeatedly test this for the next few hours before weighing in on its overall effectiveness.

**Comment by huffman** [comment]
@OmegaHeron Good to hear - I wish we had a better way to repro this particular problem :(

**Comment by huffman** [comment]
This now includes changes by @sethalves (from https://github.com/highfidelity/hifi/pull/7735). This and that PR have similar testing procedures so it will be helpful to test both at the same time.

**Comment by huffman** [comment]
For whoever dev reviews this: @AndrewMeadows had already approved the changes @sethalves  had made.

**Comment by OmegaHeron** [comment]
If anyone else wishes to give this a test - it's aimed at stopping a crash while in standard HF home scene and clicking clean up on home's built in tidybot.  It's a fairly random crash - so repeated tests and testers will likely be a good thing.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b5b6a26096021ce153d8f092db1cf93bc2b3ba0 available at: https://gist.github.com/1c43c489a3742bdc46133ca4a265ffda<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7736.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7736.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
After repeated attempts to crash via tidybot I was unable to :+1: 
Playa - all looked/sounded well
Cellscience - all looked/sounded well
Built in entity type placement/function test - all good.
ATP upload/place - all good.

Overall eval is this... I'm still able to crash RC6 with tidybot cleanups - sometimes it's 100% crash per attempt - others far less, but, eventually I'm able to do so.  With this PR I have not yet been able to generate crash.  QA Pass.

**Pull request merged**
