### PR TITLE
Clear entities and avatars on exit

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 790e3252488f9e65c9cf2e1cefe8c98765a0fa20 available at: https://gist.github.com/fd54d4b851ba75ab0a8ff90b116e76b2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c87eec41823415750fc495df0e35865a2326ac4d available at: https://gist.github.com/fd54d4b851ba75ab0a8ff90b116e76b2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9dc642d76f00e04c42fe292abf816f62ae7e488 available at: https://gist.github.com/fd54d4b851ba75ab0a8ff90b116e76b2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 146ea066db1b31b6e95704a55bbbb830d16e01a3 available at: https://gist.github.com/fd54d4b851ba75ab0a8ff90b116e76b2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7702.dmg

**Comment by sethalves** [comment]
I've run this on Windows and with asan on Linux.  It fixes memory leaks and doesn't crash!

**Pull request merged**
