### PR TITLE
fix for 6760: Create Mode turns to Portrait when Reopening tablet

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by ElderOrb** [comment]
for QA: 

Steps to reproduce:
1. Open tablet
2. Open Create. Tablet should rotate to landscape mode.
3. Close tablet.
4. Reopen tablet. 

Observed result: Tablet reopens in portrait mode with Create sideways
Expected result: Tablet reopens in landscape mode as it was last closed.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2283/HighFidelity-Beta-PR11122-06c9378b0345092805fa2f90065974c953207298.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2283/HighFidelity-Beta-PR11122-06c9378b0345092805fa2f90065974c953207298.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
-------- | -------- | --------
Open tablet | Pass | Pass
Open Create. Tablet should rotate to landscape mode. | Pass | Pass
Close tablet. | Pass | Pass
Reopen tablet. | Pass | Pass

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
