### PR TITLE
Remove old ToolWindow code

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Briefly check that UI works.

Desktop:
- Create app.
- Menu app.
- People app.

HMD:
ditto

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6264/app_12164_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6264/HighFidelity-Beta-PR12164-1fa31d3c10545609f5816c726ba07ba1f47fa70a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6264/HighFidelity-Beta-PR12164-1fa31d3c10545609f5816c726ba07ba1f47fa70a.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
UI still functioning as normal, including Create, Menu and People apps on both Desktop and Vive/HMD.

@conklin94122

**Pull request merged**
