### PR TITLE
Position default toolbar buttons bottom center of screen

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
And expand edit toolbar horizontally.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing without resetting Interface.ini: 
Exit Interface.
Edit Interface.ini to remove the lines starting with each of the following. 
- highfidelity.examples.toolbar.fraction
- highfidelity.directory.toolbar.fraction
- highfidelity.edit.toolbar.fraction
Start Interface and the three toolbar buttons (Go To, Examples, and Edit) should be centred at the bottom of the Interface window.

Testing a la new user: Wipe your Interface.ini and when you start Interface, three toolbar buttons (Go To, Examples, and Edit) should be centred at the bottom of the Interface window.

**Comment by ctrlaltdavid** [comment]
PR for review with @AlanZimmerman ; not QA Ready.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3aec67bb364ae5ecd6907fd23fc152e284fc2fd6 available at: https://gist.github.com/f2bad364b0154f336fe68bd32338eb7a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 958c6f48c2665102d909e464f1893d1739356c8a available at: https://gist.github.com/f2bad364b0154f336fe68bd32338eb7a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 958c6f48c2665102d909e464f1893d1739356c8a available at: https://gist.github.com/f2bad364b0154f336fe68bd32338eb7a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7748.dmg

**Comment by ZappoMan** [comment]
@ctrlaltdavid - is this QA Ready? Is it mergable?

**Comment by ctrlaltdavid** [comment]
Better wait for @AlanZimmerman to review it, check that it's what he wanted, before QA'ing and merging.

**Comment by RyanDowne** [comment]
I tested this on both mac and pc and it seems to work as expected. The buttons are curved a bit and I am not sure that's totally desirable in the future but, I think that's a job for another time. In the interest of time, I am going to QA pass this.

**Pull request merged**
