### PR TITLE
fix logic in UpdateEntityOperator

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce3faa2916a0b9c56ba67940c3013d5203bd1329 available at: https://gist.github.com/7e47e6c9ad234170fca36cbe67987248<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.dmg

**Comment by ZappoMan** [comment]
1) the old logic definitely looks wrong.
2) I'm gonna go look at the history to see what the original old logic was... 
3) I'm concerned about removing the `_dontMove` because that used to be an important optimization... since it appears to be completely removed now, I'm very curious what happens in the case where a move is not required.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63073301ee9735821af9301ee51402b2a763eb1c available at: https://gist.github.com/7e47e6c9ad234170fca36cbe67987248<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bd4b4f8d8b30ec9ea873e8885c5a54ef9660b07 available at: https://gist.github.com/7e47e6c9ad234170fca36cbe67987248<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7872.dmg

**Comment by sethalves** [comment]
I'm combining these changes with https://github.com/highfidelity/hifi/pull/7884

**Pull request closed without merging**
