### PR TITLE
implement support for binary data over messages

### PR DESCRIPTION
**Pull request by ZappoMan**
This adds `MessageClient` APIs for sending binary data over the message-mixer. The signals are filtered between text vs data callers so applications using binary data can be confident that they are not getting text and visa versa.

**Test Plan:**
- Some test, everything should still work correctly, especially those things using messages.
- run `scripts/developer/tests/messageTests.js` you should see the following output:
```
[02/10 10:10:13] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  com.highfidelity.example.dataMessages  message: foo  from: {67918807-d890-4479-bbc3-706817a7bec3}  local: false

[02/10 10:10:15] [DEBUG] [hifi.scriptengine.script] script:print()<< about to call sendData() data.length: 7
[02/10 10:10:15] [DEBUG] [hifi.scriptengine.script] script:print()<< data recieved on  com.highfidelity.example.dataMessages  from: {67918807-d890-4479-bbc3-706817a7bec3}  local: false length of data: 7  data: 0, 1, 10, 2, 20, 3, 30
```

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 987f147ed4209394f6b65c3c717fee811c408c83 available at: https://gist.github.com/1341bd366d6fd6574c343211bd3f0095<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-987f147.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-987f147.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7fba30f0dd66800f3964616fea73545367494e75 available at: https://gist.github.com/1341bd366d6fd6574c343211bd3f0095<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-7fba30f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-7fba30f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6d4dbb7a41c2e285dedb0c407dad5f966abd13e available at: https://gist.github.com/1341bd366d6fd6574c343211bd3f0095<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-f6d4dbb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-f6d4dbb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 765500ebce792dbacfbc57014811f9a0128d08bd available at: https://gist.github.com/1341bd366d6fd6574c343211bd3f0095<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-765500e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9645-765500e.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
Seems fine.

Log Output from script.

[02/10 19:25:52] [DEBUG] [qml] Mouse exited RunningScripts_QMLTYPE_301(0x2121814aed0, "RunningScripts")

[02/10 19:25:53] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  com.highfidelity.example.dataMessages  message: foo  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false


[02/10 19:25:55] [DEBUG] [hifi.scriptengine.script] script:print()<< about to call sendData() data.length: 7

[02/10 19:25:55] [DEBUG] [hifi.scriptengine.script] script:print()<< data recieved on  com.highfidelity.example.dataMessages  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false length of data: 7  data: 0, 1, 10, 2, 20, 3, 30

[02/10 19:25:56] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  com.highfidelity.example.dataMessages  message: foo  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false


[02/10 19:25:58] [DEBUG] [hifi.scriptengine.script] script:print()<< about to call sendData() data.length: 7

[02/10 19:25:58] [DEBUG] [hifi.scriptengine.script] script:print()<< data recieved on  com.highfidelity.example.dataMessages  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false length of data: 7  data: 0, 1, 10, 2, 20, 3, 30

[02/10 19:26:00] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  com.highfidelity.example.dataMessages  message: foo  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false


[02/10 19:26:01] [DEBUG] [hifi.scriptengine.script] script:print()<< about to call sendData() data.length: 7

[02/10 19:26:01] [DEBUG] [hifi.scriptengine.script] script:print()<< data recieved on  com.highfidelity.example.dataMessages  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false length of data: 7  data: 0, 1, 10, 2, 20, 3, 30


[02/10 19:26:03] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  com.highfidelity.example.dataMessages  message: foo  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: false


Log output from console message api call I made.


[02/10 19:47:02] [DEBUG] [hifi.scriptengine.script] script:print()<< message recieved on  {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  message: Bananas are blue.  from: {8d7588bd-14dc-43ae-837a-a908f9bb67c5}  local: true

Should we be able to send text in this way to other agents ?

**Comment by Nex-Pro** [comment]
Also after running this script for some time ( left it to soak ) my right mouse drag view direction became very laggy. Cleared on restart. @ZappoMan

**Comment by ZappoMan** [comment]
@Nex-Pro - yes this works just like messages... all clients subscribed to the channel will get it.

re: laggy -- that is probably unrelated to this PR... but might be related to arrays in our script engine... or something else

**Comment by Nex-Pro** [comment]
@ZappoMan  Yep.

**Comment by ZappoMan** [comment]
merge after load test

**Pull request merged**
