### PR TITLE
Commerce: Extended Certificate Support, V1

### PR DESCRIPTION
**Pull request by zfox23**
This big PR implements the first phase of Extended Certificate Support to Interface and contains some machinery for supporting other kinds of certified content.

You can now purchase certified Content Sets and Avatars from the Marketplace. Purchased Content Sets and Avatars will appear in My Purchases.

Detailed list of changes:
- Refactored Checkout and Purchases screens and flows as per new designs
- Added support for `alreadyOwned()` endpoint
- Added `EntityScriptingInterface::canReplaceContent()`
- Added `skeletonModelURLChanged()` signal to `MyAvatar`
- Modified TextField font from Fira Sans SemiBold to Fira Sans Regular
- Modified UIT Separator, introducing a new Separator color

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7325/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7325/HighFidelity-Beta-PR12444-2daa30f12521b3a4055e03cbb68c2606caa57f36.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7325/HighFidelity-Beta-PR12444-2daa30f12521b3a4055e03cbb68c2606caa57f36.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7329/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7330/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7330/HighFidelity-Beta-PR12444-f08c66e3ac9b8538a30054cc86838806afb9f19c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7330/HighFidelity-Beta-PR12444-f08c66e3ac9b8538a30054cc86838806afb9f19c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7351/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7353/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7353/HighFidelity-Beta-PR12444-b548567f5acf5170c7dc6f26a136d42552a28ce5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7353/HighFidelity-Beta-PR12444-b548567f5acf5170c7dc6f26a136d42552a28ce5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7356/app_12444_PR.apk

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7357/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7357/HighFidelity-Beta-PR12444-74655bde49b878f81e2707af08b871702911ff7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7357/HighFidelity-Beta-PR12444-74655bde49b878f81e2707af08b871702911ff7a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7409/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7409/HighFidelity-Beta-PR12444-90f05f4db767f63e08a2c0f2cb3ae53d14ef87b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7409/HighFidelity-Beta-PR12444-90f05f4db767f63e08a2c0f2cb3ae53d14ef87b8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7413/app_12444_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7413/HighFidelity-Beta-PR12444-3d4e6de6abb4d638d844478f68e4adba3b686cbf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7413/HighFidelity-Beta-PR12444-3d4e6de6abb4d638d844478f68e4adba3b686cbf.exe

**Comment by zfox23** [comment]
This big PR implements the first phase of Extended Certificate Support to Interface and contains some machinery for supporting other kinds of certified content.

You can now purchase certified Content Sets and Avatars from the Marketplace. Purchased Content Sets and Avatars will appear in My Purchases.

Detailed list of changes:
- Refactored Checkout and Purchases screens and flows as per new designs
- Added support for `alreadyOwned()` endpoint
- Added `EntityScriptingInterface::canReplaceContent()`
- Added `skeletonModelURLChanged()` signal to `MyAvatar`
- Modified TextField font from Fira Sans SemiBold to Fira Sans Regular
- Modified UIT Separator, introducing a new Separator color

# Test Plan

## Notes
- This test is only required to be performed in Desktop mode. It is not necessary to run this entire test plan in both HMD and Desktop modes. If, at the tester's discretion, a step during the test appears as though it might behave differently in HMD, please let me know and perform the step in HMD mode.

## Prerequisites
- You have a High Fidelity account on the Staging backend environment
- Your environment variables are set up to point Interface/Sandbox at the Staging backend environment
    - `SETX HIFI_METAVERSE_URL https://staging.highfidelity.com`
- You have a valid Wallet that you have authenticated
- You do not have any Purchases tied to your Wallet
- You are connected to your local Sandbox where you _do NOT have Rez Certified, Rez Temp Certified, or Change Content permissions_

## Tests

### Test A: Wearable Purchase
1. Open the Marketplace. Go to the item page for a wearable entity (such as "Monztur Hat 2" on Staging). Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
2. Click Cancel
    i. Verify that you are returned to the marketplace item page for the item from (1).
3. Click "Purchase" on the marketplace item page again, then click "CONFIRM PURCHASE".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **wearable** [marketplace item] has been added..."
    iii. Verify that you see a "[hat icon] WEAR" button, and that it is enabled.
    iv. Verify that DO NOT see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
4. Click "View this item in My Purchases"
    i. Verify that you are taken to the My Purchases screen, and that the item you just purchased appears at the top of the list.
    ii. Verify that you see a "[hat icon] WEAR" button on the card of the item you just purchased, and that the button is enabled.
5. Click the item name of the marketplace item you just purchased.
    i. Verify that you are returned to the marketplace item page for the item from (1).
6. Click "Purchase" on the marketplace item page.
    i. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "VIEW THIS ITEM IN MY PURCHASES" button, a grey "BUY IT AGAIN" button, and a borderless "CANCEL" button.
7. Click "VIEW THIS ITEM IN MY PURCHASES"
    i. Verify that you are taken to the My Purchases screen, and that the filter bar contains the text corresponding to the title of the item you were about to buy.

### Test B: Entity Purchase
1. Open the Marketplace. Go to the item page for a regular entity (such as "Staging Jimi" on Staging). Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
2. Click Cancel
    i. Verify that you are returned to the marketplace item page for the item from (1).
3. Click "Purchase" on the marketplace item page again, then click "CONFIRM PURCHASE".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **entity** [marketplace item] has been added..."
    iii. Verify that you see a "[magic wand icon] REZ" button, and that it is disabled.
    iv. Verify that you see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
4. Click the red "You do not have Certified Rez..." text.
    i. Verify that you see a "Rez Permission Required" popup appear. Close the popup.
5. Click "What does 'Rez' mean?"
    i. Verify that you are taken to the "Introduction to My Purchases" tutorial. Click through the tutorial.
6. Click "View this item in My Purchases"
    i. Verify that you are taken to the My Purchases screen, and that the item you just purchased appears at the top of the list.
    ii. Verify that you see a "[magic wand icon] REZ" button on the card of the item you just purchased, and that the button is disabled.
    iii. Verify that you see an (i) icon to the right of the purchased item's name.
7. Click the (i) icon to the right of the purchased item's name.
    i. Verify that you see explanatory text, explaining that you don't have 'Rez Certified' permissions.
    ii. Verify that you see a clickable "Learn more" link
    iii. Verify that you see an (x) button on the right of the card, and verify that button responds to mouse hover events.
8. Click the "Learn more" link
    i. Verify that you see a "Rez Permission Required" popup appear. Close the popup. Click the "X" on the card.
9. Click the item name of the marketplace item you just purchased.
    i. Verify that you are returned to the marketplace item page for the item from (1).
10. Click "Purchase" on the marketplace item page.
    i. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "VIEW THIS ITEM IN MY PURCHASES" button, a grey "BUY IT AGAIN" button, and a borderless "CANCEL" button.
11. Click "VIEW THIS ITEM IN MY PURCHASES"
    i. Verify that you are taken to the My Purchases screen, and that the filter bar contains the text corresponding to the title of the item you were about to buy.
12. Go to your Domain Settings Page, and give yourself "Rez Certified" and "Rez Temp Certified" permissions.
13. From within Interface, go to My Purchases.
    i. Verify that you see a card corresponding to the item you just purchased.
    ii. Verify that you see a "[magic wand icon] REZ" button on the card of the item you just purchased, and that the button is enabled.
    iii. Verify that you _do not_ see an (i) icon to the right of the purchased item's name.

### Test C: Avatar Purchase
1. Open the Marketplace. Go to the item page for an avatar (such as "Finnegon" on Staging). Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
2. Click "CONFIRM PURCHASE".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **avatar** [marketplace item] has been added..."
    iii. Verify that you see a "[avatar icon] WEAR" button, and that it is enabled.
    iv. Verify that DO NOT see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
3. Click the "WEAR" button.
    i. Verify that you see a "Change Avatar" popup with explanitory text. Click "Cancel".
4. Click "View this item in My Purchases"
    i. Verify that you are taken to the My Purchases screen, and that the item you just purchased appears at the top of the list.
    ii. Verify that you see a "[avatar icon] WEAR" button on the card of the item you just purchased, and that the button is enabled.
5. Click the item name of the marketplace item you just purchased.
    i. Verify that you are returned to the marketplace item page for the item from (1).
6. Click "Purchase" on the marketplace item page.
    i. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "VIEW THIS ITEM IN MY PURCHASES" button, and a borderless "CANCEL" button.
7. Click "VIEW THIS ITEM IN MY PURCHASES"
    i. Verify that you are taken to the My Purchases screen, and that the filter bar contains the text corresponding to the title of the item you were about to buy.
8. Click the "WEAR" button on the card corresponding to the filtered avatar.
    i. Verify that you see a "Change Avatar" popup with explanitory text.
9. Click "CONFIRM".
    i. Verify that your avatar changed (by, for example, zooming out to third person view).
    ii. Verify that the "WEAR" button you just clicked changed to be a "[avatar icon] CURRENT" button, and that it is disabled.
10. Buy a second, different Avatar from the marketplace (for example, "Photo-real Male Avatar" on Staging), then open My Purchases.
    i. Verify that both avatars appear in My Purchases.
    ii. Verify that the button on the card corresponding to the avatar you're wearing still displays as a "[avatar icon] CURRENT" button, and that it is disabled.
    iii. Verify that the button on the card corresponding to the avatar you just purchased displays as a "[avatar icon] WEAR" button, and that the button is enabled.
11. Click the "WEAR" button on the card corresponding to the avatar that you just purchased.
    i. Verify that you see a "Change Avatar" popup with explanitory text.
12. Click "CONFIRM".
    i. Verify that your avatar changed (by, for example, zooming out to third person view).
    ii. Verify that the "WEAR" button you just clicked changed to be a "[avatar icon] CURRENT" button, and that it is disabled.
    iii. Verify that the button corresponding to the _first_ avatar you purchased changed _back_ to being a "[avatar icon] WEAR" button, and that the button is enabled.

### Test D: Content Set/Environment Purchase
1. Open the Marketplace. Go to the item page for a content set (such as "Oasis" on Staging). Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a red _warning_ box explaining that you need 'replace content' permission, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
2. Click "CONFIRM PURCHASE".
    i. Verify that you see a warning popup that explains that you need 'replace content' permission.
3. Click "CONFIRM".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **content set** [marketplace item] has been added..."
    iii. Verify that you see a "[globe icon] REPLACE CONTENT SET" button, and that it is disabled.
    iv. Verify that DO NOT see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
4. Click "View this item in My Purchases"
    i. Verify that you are taken to the My Purchases screen, and that the item you just purchased appears at the top of the list.
    ii. Verify that you see a "[globe icon] REPLACE" button on the card of the item you just purchased, and that the button is disabled.
    iii. Verify that you see an (i) icon to the right of the purchased item's name.
5. Click the (i) icon to the right of the purchased item's name.
    i. Verify that you see explanatory text, explaining that you don't have 'Replace Content' permissions.
    ii. Verify that you see a clickable "Learn more" link
    iii. Verify that you see an (x) button on the right of the card, and verify that button responds to mouse hover events.
6. Click the "Learn more" link
    i. Verify that you see a "Replace Content Permission" popup appear. Close the popup. Click the "X" on the card.
7. Go to your Domain Settings Page, and give yourself "Replace Content" permissions.
8. From within Interface, go to My Purchases.
    i. Verify that you see a card corresponding to the item you just purchased.
    ii. Verify that you see a "[globe icon] REPLACE" button on the card of the item you just purchased, and that the button is enabled.
    iii. Verify that you _do not_ see an (i) icon to the right of the purchased item's name.
9. Click the "REPLACE" button.
    i. Verify that you see a "Replace Content" popup. Verify that the information in the popup makes sense.
10. Click the "CONFIRM" button.
    i. Verify that the "REPLACE" button is replaced with a green "REPLACED" overlay for 2 seconds.
    ii. Verify that your Sandbox content has been replaced with the content from the set you just purchased.
11. Right click on any entity that you see in the domain.
    i. Verify that you see an (i) overlay.
12. Click the (i) overlay.
    i. Verify that you see a certificate of the content set you just purchased.

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
