### PR TITLE
MacOS: Fix for audio, toolbar and tablet.

### PR DESCRIPTION
**Pull request by hyperlogic**
There was a deadlock on the audio thread, This would prevent audio from playing, but it would also prevent defaultScripts from running properly.  Which affected pretty much everything, including the toolbar and tablet buttons.  Specifically selectAudioDevice.js would block when it called AudioDevice.getInputDevices().

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan: 
  * Verify that the toolbar buttons, and audio functions on MacOS.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 856a38af0cbe516280ef3f701e687421fb9bece8 available at: https://gist.github.com/7f2da4a7685c5edaf18f97dd8ae1418a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9707-856a38a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9707-856a38a.dmg

**Comment by zzmp** [comment]
@hyperlogic do you have a callstack for the deadlocking thread? This change looks good, but I'm confused as to which thread would be trying to obtain this lock twice, and in what situation.

**Comment by hyperlogic** [comment]
I don't at the moment, I don't have my mac laptop with me.  But it's pretty easy to reproduce on macos, I'll send you the stacktrace ASAP

**Comment by kevinmthomasse** [comment]
testing

**Comment by hyperlogic** [comment]
@zzmp 

<pre>
thread #24: tid = 0x154c2, 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10, name = 'Audio Thread'
  * frame #0: 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98d76696 libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x00007fff9b32bb6f libc++.1.dylib`std::__1::mutex::lock() + 9
    frame #3: 0x0000000100627c1d interface`AudioClient::AudioOutputIODevice::readData(char*, long long) + 717
    frame #4: 0x0000000107809a76 QtCore`QIODevice::read(char*, long long) + 1046
    frame #5: 0x0000000113ff0819 libqtaudio_coreaudio.dylib`CoreAudioOutputBuffer::fillBuffer() + 121
    frame #6: 0x0000000113ff0e52 libqtaudio_coreaudio.dylib`CoreAudioOutput::start(QIODevice*) + 114
    frame #7: 0x0000000100622ef5 interface`AudioClient::switchOutputToAudioDevice(QAudioDeviceInfo const&) + 2405
    frame #8: 0x0000000100621248 interface`AudioClient::start() + 920
    frame #9: 0x00000001078ffe11 QtCore`QMetaObject::activate(QObject*, int, int, void**) + 705
    frame #10: 0x0000000107711b40 QtCore`QThreadPrivate::start(void*) + 336
    frame #11: 0x00007fff98d7905a libsystem_pthread.dylib`_pthread_body + 131
    frame #12: 0x00007fff98d78fd7 libsystem_pthread.dylib`_pthread_start + 176
    frame #13: 0x00007fff98d763ed libsystem_pthread.dylib`thread_start + 13

thread #15: tid = 0x154ad, 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10, name = 'CheckDevices Thread'
    frame #0: 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98d76696 libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x00007fff9b32bb6f libc++.1.dylib`std::__1::mutex::lock() + 9
    frame #3: 0x000000010061de6c interface`AudioClient::getDeviceNames(QAudio::Mode) + 44
    frame #4: 0x000000010062820f interface`AudioClient::checkDevices() + 31
    frame #5: 0x0000000100628d48 interface`CheckDevicesThread::run() + 56
    frame #6: 0x0000000107711b5a QtCore`QThreadPrivate::start(void*) + 362
    frame #7: 0x00007fff98d7905a libsystem_pthread.dylib`_pthread_body + 131
    frame #8: 0x00007fff98d78fd7 libsystem_pthread.dylib`_pthread_start + 176
    frame #9: 0x00007fff98d763ed libsystem_pthread.dylib`thread_start + 13

thread #54: tid = 0x15618, 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10, name = 'Script Thread:defaultScripts.js'
    frame #0: 0x00007fff8ff4a166 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff98d76696 libsystem_pthread.dylib`_pthread_mutex_lock + 480
    frame #2: 0x00007fff9b32bb6f libc++.1.dylib`std::__1::mutex::lock() + 9
    frame #3: 0x000000010061de6c interface`AudioClient::getDeviceNames(QAudio::Mode) + 44
    frame #4: 0x000000010018f847 interface`AudioDeviceScriptingInterface::getInputDevices() + 39
    frame #5: 0x0000000100014f5a interface`AudioDeviceScriptingInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 570
    frame #6: 0x0000000100015370 interface`AudioDeviceScriptingInterface::qt_metacall(QMetaObject::Call, int, void**) + 80
    frame #7: 0x0000000101f8c046 QtScript`QScript::QtMethodCaller::operator()(QTJSC::ExecState*, QMetaMethod::MethodType, QMetaObject const*, QScript::QScriptMetaMethod const&, int, QVarLengthArray<QVariant, 9> const&) + 534
    frame #8: 0x0000000101f8ad87 QtScript`QTJSC::JSValue QScript::delegateQtMethod<QScript::QtMethodCaller>(QTJSC::ExecState*, QMetaMethod::MethodType, QTJSC::ArgList const&, QMetaObject const*, int, bool, QScript::QtMethodCaller&) + 18407
    frame #9: 0x0000000101f79ab2 QtScript`QScript::QtFunction::execute(QTJSC::ExecState*, QTJSC::JSValue, QTJSC::ArgList const&) + 514
    frame #10: 0x0000000101f7934f QtScript`QScript::QtFunction::call(QTJSC::ExecState*, QTJSC::JSObject*, QTJSC::JSValue, QTJSC::ArgList const&) + 175
    frame #11: 0x0000000101ec57b2 QtScript`QTJSC::NativeFuncWrapper::operator()(QTJSC::ExecState*, QTJSC::JSObject*, QTJSC::JSValue, QTJSC::ArgList const&) const + 114
    frame #12: 0x0000000101ea66a4 QtScript`cti_op_call_NotJSFunction + 212
    frame #13: 0x00004cd6b1977a51
    frame #14: 0x0000000101e5af84 QtScript`QTJSC::Interpreter::execute(QTJSC::FunctionExecutable*, QTJSC::ExecState*, QTJSC::JSFunction*, QTJSC::JSObject*, QTJSC::ArgList const&, QTJSC::ScopeChainNode*, QTJSC::JSValue*) + 740
    frame #15: 0x0000000101ee5bee QtScript`QTJSC::JSFunction::call(QTJSC::ExecState*, QTJSC::JSValue, QTJSC::ArgList const&) + 142
    frame #16: 0x0000000101f718a1 QtScript`QScriptValue::call(QScriptValue const&, QList<QScriptValue> const&) + 865
    frame #17: 0x00000001006c9a7e interface`std::__1::__function::__func<ScriptEngine::callWithEnvironment(EntityItemID const&, QUrl const&, QScriptValue, QScriptValue, QList<QScriptValue>)::$_15, std::__1::allocator<ScriptEngine::callWithEnvironment(EntityItemID const&, QUrl const&, QScriptValue, QScriptValue, QList<QScriptValue>)::$_15>, void ()>::operator()() + 30
    frame #18: 0x00000001006c361b interface`ScriptEngine::doWithEnvironment(EntityItemID const&, QUrl const&, std::__1::function<void ()>) + 123
    frame #19: 0x00000001006bc943 interface`ScriptEngine::timerFired() + 371
    frame #20: 0x00000001078ffe11 QtCore`QMetaObject::activate(QObject*, int, int, void**) + 705
    frame #21: 0x00000001078f8f00 QtCore`QObject::event(QEvent*) + 48
    frame #22: 0x000000010235e956 QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294
    frame #23: 0x0000000102361415 QtWidgets`QApplication::notify(QObject*, QEvent*) + 5941
    frame #24: 0x00000001078ccc84 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    frame #25: 0x0000000107924272 QtCore`QTimerInfoList::activateTimers() + 1266
    frame #26: 0x0000000107922fdf QtCore`QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 255
    frame #27: 0x00000001006b5dca interface`ScriptEngine::run() + 1322
    frame #28: 0x00000001078ffe11 QtCore`QMetaObject::activate(QObject*, int, int, void**) + 705
    frame #29: 0x0000000107711b40 QtCore`QThreadPrivate::start(void*) + 336
    frame #30: 0x00007fff98d7905a libsystem_pthread.dylib`_pthread_body + 131
    frame #31: 0x00007fff98d78fd7 libsystem_pthread.dylib`_pthread_start + 176
    frame #32: 0x00007fff98d763ed libsystem_pthread.dylib`thread_start + 13
</pre>

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAIL
**Additional Test Results + Observations**: Successfully tested on MAC.  Verified that the toolbar buttons and audio functions without any issue.  Smoke tested the windows build and everything worked properly except upon exit of interface where it crashed.  Sent Bugsplat report.

**Comment by cozza13** [comment]
tested and did not repro the crash on PC

**Pull request merged**
