### PR TITLE
Adding a basic vulkan library

### PR DESCRIPTION
**Pull request by jherico**
Adding a vulkan context, window and example (without integration into the GPU library)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74d4a39a3847d3839ed0c19668077d9cb5702ff7 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e5db0645716c3942c751e48d402a5294b5c3c27e available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by ZappoMan** [comment]
set'ki

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ea40c7202b3bcb272d32e1f4dfd6449d6dd2e60 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9158638b745d13c0f8e170c432f0b243835ccdb6 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by Geenz** [comment]
Not entirely related to this (though I assume for command buffers and what not, similar changes will need to be made anyways), but would something like including GLSLOptimizer for a potential Metal backend fall under the realm of being "okay"?  Or would the plan for shaders with a Vulkan backend be to pre-compile into SPIR-V?

Either way, there are translation paths for a potential Metal backend down the road.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80dcc632e115931940d737b3a390845c10ad8deb available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44c3fc94f47b97230552e58fba3546eadf5c3dd7 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8c6e5a3376f5a0981243a11b779d30898c4082d available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by jherico** [comment]
@Geenz Yes, the easiest path to Metal would be likely be some GLSL to Metal shader compiler.  Such a compiler would need to be incorporated into the application because we can't really do user-created procedural surfaces if we pre-compile all our shaders.  Additionally, we're not going to be dropping the GL backend anytime soon so we still need the GLSL shaders available at runtime anyway.

**Comment by Geenz** [comment]
Makes sense. I'd like to take a crack at writing C or C++ bindings for Metal if you guys wouldn't mind - though it'd probably be better just to mix Obj-C with C++ in a backend for the GPU class.

For the GLSL situation - I *think* GLSLOptimizer only works with GLSL 1.20 for desktop GL and GLSL 300 for GLES 3, would have to check. It is available in library form, and can be found here: https://github.com/aras-p/glsl-optimizer

It's mainly used in Unity3D's shader cross compilation.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f0290ae8855605d64aa049f585c772996d2bee3 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a560bdaca3fabebf821252c9c3ba92596cae9fd4 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by jherico** [comment]
@Geenz I'd be more tempted to do Metal by using https://github.com/KhronosGroup/SPIRV-Cross to compile from the GLSL to SPIR-V and then decompile to Metal shaders.

**Comment by Geenz** [comment]
@jherico Ah, cool.  I wonder what the overhead for GLSL->SPIR-V->MSL->MSL library would be - I can't imagine it would be great, but thankfully nowadays you can thread it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfa8ef03f957db811ad5e46fdaced1548430682d available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c4563f69ff05e90cfaac41ee27689f285fc4f68 available at: https://gist.github.com/fc657655bbb9c51f4910bba931458255<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7965.dmg

**Comment by jherico** [comment]
I'm closing this as I don't feel like embedding some mechanism to fetch the vulkan SDK, and unless Leo wants to be installing (and frequently updating) the SDK on the build machines, it's never going to build in Jenkins.

**Pull request closed without merging**
