### PR TITLE
Commerce: Login; punctuationMode; new images

### PR DESCRIPTION
**Pull request by zfox23**
Don't formally test.

Five more Trello cards off the list.

### CODE REVIEW

**Comment by zfox23** [comment]
[Fix login (hook up logged in signal to switch wallet screen)](https://trello.com/c/SWpD8cKd/363-fix-login-hook-up-logged-in-signal-to-switch-wallet-screen)

**Comment by zfox23** [comment]
[Handle not logged in/logged in status changed](https://trello.com/c/82xO1NOB/352-handle-not-logged-in-logged-in-status-changed)

**Comment by zfox23** [comment]
[Handle not logged in/logged in status changed](https://trello.com/c/82xO1NOB/352-handle-not-logged-in-logged-in-status-changed)

**Comment by zfox23** [comment]
[Fix `punctuationMode`](https://trello.com/c/MMRHg0Fb/364-fix-punctuationmode)

**Comment by zfox23** [comment]
[art: "coin" or "money" image as one of the security image choices (to help illustrate what is being secure in screen shots)](https://trello.com/c/jNUiDUiT/340-art-coin-or-money-image-as-one-of-the-security-image-choices-to-help-illustrate-what-is-being-secure-in-screen-shots)

**Comment by zfox23** [comment]
[genericize security image names (so they can be swapped out with no code changes)](https://trello.com/c/7ZLHoHTJ/326-genericize-security-image-names-so-they-can-be-swapped-out-with-no-code-changes)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2901/HighFidelity-Beta-PR11272-e0878e7a3ffda15a9d17e7eceb76a13f46482dc7.dmg

**Pull request merged**
