### PR TITLE
Bring back display names

### PR DESCRIPTION
**Pull request by Atlante45**
This brings back display names and their backgrounds.

- Fixed code that compute the correct scale for rendering (always the same size on the screen)
- Pixel aligned the rendering for a better looking font.
- Removed the specular from the text shaders
- Fixed bug in Transform
- Fixed bevel corners quads

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96494d5f0641a1b885baf4ebf4ab4e9f954697b8 available at: https://gist.github.com/840a1fa0532599bf8f24<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04d174df717a0101125429d58c3bc288c8c00b63 available at: https://gist.github.com/840a1fa0532599bf8f24<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7eac74d57f4fb257b0646e018f3e7889922ac69c available at: https://gist.github.com/840a1fa0532599bf8f24<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50178d4840e6330f1307053cae54ade3b9f4aaab available at: https://gist.github.com/d981ab90da6ce2557e7a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50178d4840e6330f1307053cae54ade3b9f4aaab available at: https://gist.github.com/840a1fa0532599bf8f24<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 26e8c490c3e8c5b8cca18b2588117c8140c44d9e available at: https://gist.github.com/840a1fa0532599bf8f24<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5145.dmg

**Pull request merged**
