### PR TITLE
[rc69.1] - Fix closed eyelids when head is tilted down

### PR DESCRIPTION
**Pull request by luiscuenca**
https://github.com/highfidelity/hifi/pull/13502

This PR fixes the bug where the avatar closes the eyes while looking at others at certain angles.
Now the eyebrows will be raised when looking up relative to the head.

https://highfidelity.manuscript.com/f/cases/16027/Avatar-eyelids-look-half-closed-when-head-is-tilted-down-only-slightly

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Load an avatar that contains standard blend shapes: i.e. http://mpassets.highfidelity.com/e76946cc-c272-4adf-9bb6-02cde0a4b57d-v1/9e8c5c42a0cbd436962d6bd36f032ab3.fst

- Move in front of other avatar, your eyes should look at its face while you move your head.
- Move your head up and down ( and to the sides) and make sure that the eyelids never close (only when blinking) .
- When increasing the eye angle relative to your head your eyelids should open accordingly.
- Make sure the avatar keeps blinking once in a while no matter where you're looking.
- If your avatar is looking up relative to the head the eyebrows should raise slightly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11198/HighFidelity-Beta-PR13566-3613970.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11198/HighFidelity-Beta-PR13566-3613970.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11198/HighFidelity-Beta-Interface-PR13566-3613970.exe

**Pull request closed without merging**
