### PR TITLE
avoid crash in soft-attachment code

### PR DESCRIPTION
**Pull request by sethalves**
- potential fix for a crash in soft-attachment code

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- wear a soft attachment
- no functional change

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/5451/CRASH-in-SoftAttachmentModel-updateClusterMatrices

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1682/HighFidelity-Beta-PR10966-12f52e8f20f3525586ff0ec351bc46bbac7bc217.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1682/HighFidelity-Beta-PR10966-12f52e8f20f3525586ff0ec351bc46bbac7bc217.exe

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
### Pass

@sethalves Let me know if this needs any kind of stress test.

**Pull request merged**
