### PR TITLE
Fix MS20161: Fix INVENTORY notification dot state

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS20161](https://highfidelity.manuscript.com/f/cases/20161/INVENTORY-app-red-dot-not-disappearing-as-expected).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15845/HighFidelity-Beta-PR14559-ab6aeae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15845/HighFidelity-Beta-PR14559-ab6aeae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15845/HighFidelity-Beta-Interface-PR14559-ab6aeae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15845/HighFidelity-Beta-PR14559-ab6aeae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15845/HighFidelity-Beta-Interface-PR14559-ab6aeae.exe

**Comment by rickcarr044** [comment]
Currently testing PR14559

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15868/HighFidelity-Beta-PR14559-75ba1cb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15868/HighFidelity-Beta-PR14559-75ba1cb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15868/HighFidelity-Beta-Interface-PR14559-75ba1cb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15868/HighFidelity-Beta-PR14559-75ba1cb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15868/HighFidelity-Beta-Interface-PR14559-75ba1cb.exe

**Pull request merged**
