### PR TITLE
User.js option to only disply users in current domain

### PR DESCRIPTION
**Pull request by Atlante45**
Thought it could be a cool new option

### CODE REVIEW

**Comment by PhilipRosedale** [comment]
does it still default to everyone?  I LOVE how it gets you to wander to other domains and so i don't want to lose that.

**Comment by Atlante45** [comment]
It does, I like that feature too.
It's just an additional option for when there is a ton of people online and you want to see who is in the same domain.

**Comment by ctrlaltdavid** [comment]
I believe that at some stage the semantics of "everyone" may change to mean "domain". In the meantime, if a "domain" option is wanted it would be better implemented as a filter in the API call, similar to the "friends" filter. This because the "everyone" option only returns up to 30(?) people (starting with the most recent logins, I think), and so if you filter these you may get fewer people than are actually on the domain. @birarda ?

**Comment by Atlante45** [comment]
Wait so if you set it to everyone and there is more than 30 people online, you don't actually get everyone?

**Comment by birarda** [comment]
@Atlante45 that's right and that is by design

**Comment by Atlante45** [comment]
No pb, I thought it would just be a matter of filtering out the result.

**Pull request closed without merging**
