### PR TITLE
remove polyvox fade, fix web fade, add light fade

### PR DESCRIPTION
**Pull request by SamGondelman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 130e64aabae475db0b917753bfa9ca066ba4a227 available at: https://gist.github.com/966c74cb10f321a0dddb21a89f112080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-130e64a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-130e64a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b13edc7b6adde15e8f917529290881b96fb54835 available at: https://gist.github.com/966c74cb10f321a0dddb21a89f112080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-b13edc7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-b13edc7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f2ee57f2de8b26a9b8848797be3cfff144057e64 available at: https://gist.github.com/966c74cb10f321a0dddb21a89f112080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-f2ee57f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-f2ee57f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 84944000476ac3722faec4b05456dd69f4fd40eb available at: https://gist.github.com/966c74cb10f321a0dddb21a89f112080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-8494400.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8375-8494400.dmg

**Comment by SamGondelman** [comment]
Gonna go ahead and merge this now, will get it dev approved and QAd along with everything else.

**Pull request merged**
