### PR TITLE
Fix edit log spam with -1 hand

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.fogbugz.com/f/cases/17323

Test Plan:
- Enter Interface in desktop mode
- Open Create and perform various different actions including manipulating entities with the edit handles, clicking around the entity list, and changing properties while observing the log output
- Verify there is no output lines of - Unknown input: "ffffffff"
- Verify Create actions perform as expected
- Enter HMD mode and open Create again
- Select and entity and perform various different actions with the edit handles using the lasers and verify all actions perform as expected
- Exit Create and verify the entity can be near-grabbed as expected with hands
- Verify the entity can be far-grabbed as expected with the lasers
- Add a flaregun from the marketplace
- Verify when your hand is near the flaregun that the purple sphere for equipping appears
- Verify the flaregun can be equipped to your hand and unequipped as expected

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11831/HighFidelity-Beta-PR13750-0565e04.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11831/HighFidelity-Beta-PR13750-0565e04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11831/HighFidelity-Beta-Interface-PR13750-0565e04.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11831/HighFidelity-Beta-PR13750-0565e04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11831/HighFidelity-Beta-Interface-PR13750-0565e04.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11901/HighFidelity-Beta-PR13750-0565e04.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11901/HighFidelity-Beta-PR13750-0565e04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11901/HighFidelity-Beta-Interface-PR13750-0565e04.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11901/HighFidelity-Beta-PR13750-0565e04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11901/HighFidelity-Beta-Interface-PR13750-0565e04.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Unknown input: "ffffffff" no longer appears in the log and all test steps pass

**Pull request merged**
