### PR TITLE
Emoji reaction animation

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Prototype of animations to support the universal Emoji app - mostly in prep for a design conversation with Joshua.  This PR randomly draws from a small library of various possibilities for this - we'll run it to discuss.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22307/HighFidelity-Beta-PR16450-2b1aaa8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22307/HighFidelity-Quest-Beta-PR16450-2b1aaa8.apk)

**Comment by DouglasWilcox** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22314/HighFidelity-Beta-PR16450-2b1aaa8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22314/HighFidelity-Quest-Beta-PR16450-2b1aaa8.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22314/HighFidelity-Beta-PR16450-2b1aaa8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22314/HighFidelity-Beta-Interface-PR16450-2b1aaa8.exe

**Pull request closed without merging**
