### PR TITLE
Fix Window hasFocus(), setFocus(), and raiseMainWindow()

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

On Windows...

Run the script hasFocusRepeat.js. This repeatedly reports the current value of Window.hasFocus() to the program log - best viewed using Developer > Script Log.

Note: Don't have the program log window open because this gains focus if you minimize the Interface window to the taskbar.

1) Check Window.hasFocus() reporting:
a) Interface window visible and has keyboard focus: Window.hasFocus() reports true.
b) Interface window visible but another window has keyboard focus: Window.hasFocus() reports false.
c) Interface window minimized to taskbar: Window.hasFocus() reports false.

2) The script setFocusDelayed.js calls Window.setFocus() after a 5 second delay. Use it (reload it as necessary) to test:
a) Leave the Interface window with focus, and wait for the setFocus() call to be made: Interface window continues to have focus and Window.hasFocus() continues to report true.
b) Minimize Window to the taskbar but don't use any other application, and wait for the setFocus() call to be made: the Interface taskbar item should highlight but Window.hasFocus() should continue to report false.
c) Minimize Window to the taskbar and use another application, and wait for the setFocus() call to be made: the taskbar Interface item should highlight and flash but Window.hasFocus() should continue to report false.


3) The script raiseWindowDelayed.js calls Window.raiseMainWindow() after a 5 second delay. Use it (reload it as necessary) to test:
a) Leave the Interface window with focus, and wait for the raiseMainWindow() call to be made: Interface window continues to have focus and Window.hasFocus() continues to report true.
b) Minimize Window to the taskbar but don't use any other application, and wait for the raiseMainWindow() call to be made: the Interface window should open and get focus, with Window.hasFocus() reporting true.
Test minimizing and raising Interface window both when window is normal (windowed) and when it is maximized.
b) Minimize Window to the taskbar and use another application, and wait for the raiseMainWindow() call to be made: the Interface window should open and get focus, with Window.hasFocus() reporting true.
Test minimizing and raising Interface window both when window is normal (windowed) and when it is maximized.

**Comment by ctrlaltdavid** [comment]
https://highfidelity.manuscript.com/f/cases/558/setFocus-causes-us-to-lose-focus
https://highfidelity.manuscript.com/f/cases/10693/Window-setFocus-doesn-t-set-focus-to-Interface-window
https://highfidelity.manuscript.com/f/cases/10694/Window-raiseMainWindow-doesn-t-work

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8016/app_12635_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8016/HighFidelity-Beta-PR12635-c1e256a4f39725446f1478355ac5b28f057e2cb1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8016/HighFidelity-Beta-PR12635-c1e256a4f39725446f1478355ac5b28f057e2cb1.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
All values appear as expected on windows. On Mac, when the interface is minimized it is still in focus on the activity bar and therefore reports true. When the desktop is selected it then reports false.

**Pull request merged**
