### PR TITLE
when using the fullscreen mirror hot key, return to the view mode you were in when leaving full screen mirror

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- smoke test
- using the "H" mirror key switch to full screen mirror... notice that you should return to the mode you were in.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81bb5ff07d4d54274e38ae8d3e9272e846eff10f available at: https://gist.github.com/e32f79ac59474653529b7edb35a33709<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7612.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7612.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09004680d08e5a48733ce65dc4c16cfe77d1664d available at: https://gist.github.com/e32f79ac59474653529b7edb35a33709<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7612.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7612.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Switching to FS Mirror (H) then back results in same person mode as it was.  Tested with mini mirror on as well and after adjusting view of FS mirror.  All seems good :+1: 

QA Pass

**Pull request merged**
