### PR TITLE
CR for Job #21222 - Clean up plugins/hifiCodec dependencies

### PR DESCRIPTION
**Pull request by mnafees**
Code Review for Job #21222 - Workitem available at https://www.worklist.net/21222

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3382f9f5eb5c670c254c2cd66d7f72c5df788a4c available at: https://gist.github.com/eda963ed99f6391fd7103faca3fe5574<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10276-3382f9f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10276-3382f9f.dmg

**Comment by thoys** [comment]
hi @mnafees , what is the test plan? I assume just a smoke test?

**Comment by mnafees** [comment]
@thoys Yup, just a smoke test :)

**Comment by kencooke** [comment]
Tested.. PASS

**Pull request merged**
