### PR TITLE
DOC-189: SpeechRecognizer JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- SpeechRecognizer

Case: https://highfidelity.atlassian.net/browse/DOC-189

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21781/HighFidelity-Beta-PR16308-570abba.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21781/HighFidelity-Quest-Beta-PR16308-570abba.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21781/HighFidelity-Beta-PR16308-570abba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21781/HighFidelity-Beta-Interface-PR16308-570abba.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21783/HighFidelity-Beta-PR16308-570abba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21783/HighFidelity-Beta-Interface-PR16308-570abba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21783/HighFidelity-Beta-PR16308-570abba.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21783/HighFidelity-Beta-Interface-PR16308-570abba.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21783/HighFidelity-Beta-PR16308-570abba.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21783/HighFidelity-Quest-Beta-PR16308-570abba.apk)

**Pull request merged**
