### PR TITLE
Center of Gravity Leaning

### PR DESCRIPTION
**Pull request by amantley**
This PR implements another body model function to go with the existing deriveBodyFromHMD function  we currently use to place the avatar hips correctly.  Here we use a center of gravity model to balance the head, hands and hips over the base of support of  the feet.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9613/app_13133_PR_8000bcd272fc907df4ffee73dcd6f93a3e8cfb1f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9613/HighFidelity-Beta-PR13133-8000bcd272fc907df4ffee73dcd6f93a3e8cfb1f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9613/HighFidelity-Beta-Interface-PR13133-8000bcd272fc907df4ffee73dcd6f93a3e8cfb1f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9613/HighFidelity-Beta-PR13133-8000bcd272fc907df4ffee73dcd6f93a3e8cfb1f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9613/HighFidelity-Beta-Interface-PR13133-8000bcd272fc907df4ffee73dcd6f93a3e8cfb1f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9636/app_13133_PR_a7955b642a791bf138e5f4e19cb7a9192c310e92.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9636/HighFidelity-Beta-PR13133-a7955b642a791bf138e5f4e19cb7a9192c310e92.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9636/HighFidelity-Beta-Interface-PR13133-a7955b642a791bf138e5f4e19cb7a9192c310e92.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9636/HighFidelity-Beta-PR13133-a7955b642a791bf138e5f4e19cb7a9192c310e92.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9636/HighFidelity-Beta-Interface-PR13133-a7955b642a791bf138e5f4e19cb7a9192c310e92.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9652/app_13133_PR_20c960c0da5406db331c600eb3af93284241c00d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9652/HighFidelity-Beta-PR13133-20c960c0da5406db331c600eb3af93284241c00d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9652/HighFidelity-Beta-Interface-PR13133-20c960c0da5406db331c600eb3af93284241c00d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9652/HighFidelity-Beta-PR13133-20c960c0da5406db331c600eb3af93284241c00d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9652/HighFidelity-Beta-Interface-PR13133-20c960c0da5406db331c600eb3af93284241c00d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9753/HighFidelity-Beta-PR13133-1cc7eb635fb8a955a0cc211b925aa1f4c3cab61b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9753/HighFidelity-Beta-Interface-PR13133-1cc7eb635fb8a955a0cc211b925aa1f4c3cab61b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9753/HighFidelity-Beta-PR13133-1cc7eb635fb8a955a0cc211b925aa1f4c3cab61b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9753/HighFidelity-Beta-Interface-PR13133-1cc7eb635fb8a955a0cc211b925aa1f4c3cab61b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9769/HighFidelity-Beta-PR13133-ec638d9d91716dd966cd071af66df19ed57c80b3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9769/HighFidelity-Beta-Interface-PR13133-ec638d9d91716dd966cd071af66df19ed57c80b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9769/HighFidelity-Beta-PR13133-ec638d9d91716dd966cd071af66df19ed57c80b3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9769/HighFidelity-Beta-Interface-PR13133-ec638d9d91716dd966cd071af66df19ed57c80b3.exe

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/15105/

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10354/HighFidelity-Beta-PR13133-558711f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10354/HighFidelity-Beta-PR13133-558711f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10354/HighFidelity-Beta-Interface-PR13133-558711f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10354/HighFidelity-Beta-PR13133-558711f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10354/HighFidelity-Beta-Interface-PR13133-558711f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10372/HighFidelity-Beta-PR13133-993d035.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10373/HighFidelity-Beta-PR13133-b5a3b25.apk

**Comment by hyperlogic** [comment]
QA Test Plan:

Verify that when compared to master, the avatar looks more balanced when performing the following actions in HMD mode.
  * crouching - the hips should move backward, resulting in a more natural crouching pose.
  * leaning backward - the hips should move forward slightly to counter balance, when you lean over your heels.
  * leaning forward - the hips should move backward slightly, as you begin to lean over your toes.
  * leaning side to side - the hips should look natural as you are leaning side to side, but your center of gravity should always seem like it is centered over one or both feet.

For reference here is a video comparing the behavior of master (on the left) and the new center of gravity leaning (on the right)

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=u15u5T9DkN0)

Also, perform the following actions to verify the behavior still works as expected:

* The jumping to flying transition should look smooth, to yourself and observers.
* The falling to flying transition should look smooth. to yourself and observers.
* Sittable chairs should still function the same as master. (please to not re-report known issues with [sitting](https://highfidelity.fogbugz.com/f/filters/?ixStatus=-2&sColumns=Category-Favorite-Case-TitleComment-Status-AssignedTo-RemainingTime-OpenedBy-Priority-Milestone&sSearchFor=tag%3ASitting&sView=grid-flat))
* Desktop mode avatar animations should not be affected.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10373/HighFidelity-Beta-PR13133-b5a3b25.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10373/HighFidelity-Beta-Interface-PR13133-b5a3b25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10373/HighFidelity-Beta-PR13133-b5a3b25.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10373/HighFidelity-Beta-Interface-PR13133-b5a3b25.exe

**Comment by amantley** [comment]
@hyperlogic Everything looks good.  I put in a couple comments above.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
All animations mentioned in test plan look good and as expected. leaning is responsive.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10486/HighFidelity-Beta-PR13133-c3da4e7.apk

**Comment by hyperlogic** [comment]
In this case it is fine because this work was handed off between us.

**Comment by hyperlogic** [comment]
The changes necessary for dev approval are minor, this PR does not need to be re-tested and can be merged once the build completes.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10486/HighFidelity-Beta-PR13133-c3da4e7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10486/HighFidelity-Beta-Interface-PR13133-c3da4e7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10486/HighFidelity-Beta-PR13133-c3da4e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10486/HighFidelity-Beta-Interface-PR13133-c3da4e7.exe

**Pull request merged**
