### PR TITLE
fix leak from qml surfaces' render controls

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 02b4c43cff0aa521b384d8dc37410527fbb020a5 available at: https://gist.github.com/edc679291ecfaa6d05f33d5e2c3efa10<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8862-02b4c43.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8862-02b4c43.dmg

**Comment by jherico** [comment]
## Testing notes

Application behavior should be unchanged, but moving between domains while holding a web tablet open should no longer cause GPU resources to leak and GPU memory usage (as reported by the OS) to grow without bounds.

**Comment by Nex-Pro** [comment]
Checking this on Win10

**Comment by Nex-Pro** [comment]
Got a crash changing domains with open tablet after more than an hour and a half of changing and leaving to soak. Probably changed domains in excess of 25 times with tablet open.

**Comment by PhilipRosedale** [comment]
How do you check GPU Memory usage?

**Comment by OmegaHeron** [comment]
@PhilipRosedale - renderStats.js should give you indication needed.

**Comment by ZappoMan** [comment]
regarding @Nex-Pro's crash... I've filed an independent bug on that.

**Comment by Nex-Pro** [comment]
@Philip I had GPU-Z open while interface was up.

**Pull request merged**
