### PR TITLE
Fix blender::run crash

### PR DESCRIPTION
**Pull request by hyperlogic**
Pass a shared_ptr of the HFMModel to the Blender.  This will prevent the HFMModel from being destroyed on the main thread if an Avatar changes their skeletonModelURL.

Also the _blendshapeOffset hash in Model has been eliminated, it was not necessary and was also a source of data races.

The body of Blender::run has been updated slightly to reduce the number of allocation necessary for temporary QVectors.

https://highfidelity.atlassian.net/browse/BUGZ-159

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19500/HighFidelity-Beta-PR15572-98fe059.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19500/HighFidelity-Quest-Beta-PR15572-98fe059.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19500/HighFidelity-Beta-PR15572-98fe059.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19500/HighFidelity-Beta-Interface-PR15572-98fe059.exe

**Comment by hyperlogic** [comment]
build failed
```
14:14:39 Build step 'Flexible publish' changed build result to FAILURE
```
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19515/HighFidelity-Beta-PR15572-98fe059.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19515/HighFidelity-Beta-Interface-PR15572-98fe059.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19515/HighFidelity-Beta-PR15572-98fe059.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19515/HighFidelity-Quest-Beta-PR15572-98fe059.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19520/HighFidelity-Beta-PR15572-3ae3335.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19520/HighFidelity-Quest-Beta-PR15572-3ae3335.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19520/HighFidelity-Beta-PR15572-3ae3335.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19520/HighFidelity-Beta-Interface-PR15572-3ae3335.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19520/HighFidelity-Beta-PR15572-3ae3335.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19520/HighFidelity-Beta-Interface-PR15572-3ae3335.exe

**Pull request merged**
