### PR TITLE
Temporarily disable magnification until further notice

### PR DESCRIPTION
**Pull request by vladest**
Test plan

- open Tablet
- Move mouse or laser over apps buttons 
- makes sure its not manified

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6222/app_12148_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6222/HighFidelity-Beta-PR12148-cff80e86b6573a727f8e9417d9c8cf3f8e2a9fe1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6222/HighFidelity-Beta-PR12148-cff80e86b6573a727f8e9417d9c8cf3f8e2a9fe1.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
