### PR TITLE
Snapshot sharing improvements

### PR DESCRIPTION
**Pull request by zfox23**
This PR modifies the snapshot behavior:
1. The Snapshot Review dialog now appears as soon as the snapshot is finished capturing (versus the current behavior, where it appears after the GIF finishes processing). While the GIF is processing, the Snapshot Review dialog displays a "Loading" image until the GIF is finished processing.

*Test Plan:*
1. From a clean install of Interface A in Desktop mode, press the "SNAP" button in the toolbar.
2. Verify that the following behavior occurs:
The Snapshot Review dialog now appears as soon as the snapshot is finished capturing.
While the GIF is processing, the Snapshot Review dialog displays a "Loading" image until the GIF is finished processing.
At that time, the captured GIF appears in the Snapshot Review dialog.
3. Check the box next to the GIF, then press "SHARE IN FEED". Wait a few seconds (up to a minute) until the GIF appears in the feed. If it never appears, click the "SNAP" button at the top of the feed, and see if it's there.
4. Open Settings -> General. UNCHECK the option next to "Take Animated GIF Snapshot", then save changes.
5. Press the "SNAP" button in the toolbar.
6. The Snapshot Review dialog appears almost immediately. There are no checkboxes in the dialog. Pressing "SHARE IN FEED" causes the still image to appear in the feed (click the "SNAP" button at the top of the feed if it doesn't automatically appear).

Verify that, throughout this test plan, HUD elements disappeared and reappeared as expected (i.e. disappeared during snapshot capture; reappeared when the review dialog appeared).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ece54c83fea75e0feaa88c5353f9f39394de2d99 available at: https://gist.github.com/8c3ecc147e9343299127fc855aee813e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-ece54c8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-ece54c8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c0ece02e821d939109715a07d395df91743e11f7 available at: https://gist.github.com/8c3ecc147e9343299127fc855aee813e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-c0ece02.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-c0ece02.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32d7a9221ced4bd4f1785f4b7cb6f86027a826c3 available at: https://gist.github.com/8c3ecc147e9343299127fc855aee813e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-32d7a92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-32d7a92.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f91fb8e554846b7bf3f84211c9cd4089698f526 available at: https://gist.github.com/8c3ecc147e9343299127fc855aee813e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-3f91fb8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10207-3f91fb8.dmg

**Comment by howard-stearns** [comment]
The "don't share" button is not working, but that's the way it is in master. QA PASS.

**Pull request merged**
