### PR TITLE
Prevent entering independent camera mode through edit.js in HMD mode

### PR DESCRIPTION
**Pull request by SamGondelman**
Right now it's possible, using edit.js in an HMD, to enter Independent camera mode and have your view stuck to an object, which makes you sick very easily. This makes it so you can't get in that state while in an HMD.

Combined with #8123, you also won't be able to get into that state by starting in Desktop mode.

### CODE REVIEW

**Comment by SamGondelman** [comment]
Testing:

- Starting in desktop mode with default scripts from this PR running, double click an entity on the entity list in the edit window to lock your view to it.
- Switch to an HMD.  Your view should be back in first person.
- While in the HMD, double click an entity in the entity list again.  Your view shouldn't change.
- By using edit.js, there should be no other way for you to get your view locked on an object while in an HMD (it's very headache inducing).

**Comment by hifi-gustavo** [comment]
Build console output for commit: a358e3c2d9f91f1c2215ffacab9ee62fdfcfeff8 available at: https://gist.github.com/594146215c8c82c936e387a43dffd27c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8135.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8135.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - Rift DK2
This PR met all points of test.  I'm new to having an HMD so this may not be fault of this PR but.

**In desktop mode** I opened edit and selected an object from list and locked view on by double clicking - I change to HMD Mode and am in paused/away mode.  I can't dismiss away dialog with a keypress.  I finally managed to find a mouse cursor and exit HMD mode.  I re-entered HMD Mode and was able to dismiss away dialog (once) and was able to test it doesn't cam lock on edit select.  Subsequent attempts to enter HMD mode while an object was selected and cam locked in Desktop mode resulted in same inability to dismiss away dialog.

**Comment by OmegaHeron** [comment]
Also title edit :)

~~Can't~~ Prevent enter independent camera mode through edit.js in HMD mode

**Comment by SamGondelman** [comment]
@OmegaHeron Yeah, sounds like focus issues, unrelated to this PR.  I'll look into it separately!

**Pull request merged**
