### PR TITLE
DO NOT MERGE - Threaded QML rendering

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5c2cca57cd77366c97951d4927bb08d7bcd1f98e available at: https://gist.github.com/e055d20000179d35a61b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12facdc3810b1dcd6d14ddb06de220b3d2f193ce available at: https://gist.github.com/e055d20000179d35a61b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3f70a356e9570848807589b2cab486d743d11a5 available at: https://gist.github.com/e055d20000179d35a61b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d6505508b8851af28f25ca42ea0856fc32cca06c available at: https://gist.github.com/e055d20000179d35a61b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5525.dmg

**Comment by ZappoMan** [comment]
are you planning on closing this PR? Or do we still want to work on this?

**Pull request closed without merging**
