### PR TITLE
ignore anonymous screenshare zone entry

### PR DESCRIPTION
**Pull request by howard-stearns**
https://highfidelity.atlassian.net/browse/DEV-2837

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by howard-stearns** [comment]
I have tested this locally, using additional logging.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22713/HighFidelity-Beta-PR16544-323007e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22713/HighFidelity-Beta-Interface-PR16544-323007e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22713/HighFidelity-Beta-PR16544-323007e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22713/HighFidelity-Quest-Beta-PR16544-323007e.apk)

**Comment by howard-stearns** [comment]
I may be doing something wrong, but I'm not convinced that this is working. Investigating...

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22717/HighFidelity-Beta-PR16544-323007e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22717/HighFidelity-Quest-Beta-PR16544-323007e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22717/HighFidelity-Beta-PR16544-323007e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22717/HighFidelity-Beta-Interface-PR16544-323007e.dmg

**Pull request merged**
