### PR TITLE
added stub for High Velocity Filter

### PR DESCRIPTION
**Pull request by alhighfidelity**
- started on high velocity filter for the vive inputs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/312/HighFidelity-Beta-PR10591-3f3b657090f5ca1e480c337b44dfa9981829bd15.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/312/HighFidelity-Beta-PR10591-3f3b657090f5ca1e480c337b44dfa9981829bd15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/422/HighFidelity-Beta-PR10591-cf41855c4fc406f0feaf4377a052e17167f93821.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/422/HighFidelity-Beta-PR10591-cf41855c4fc406f0feaf4377a052e17167f93821.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1127/HighFidelity-Beta-PR10591-b365e67840066335be7888af8ed263adc5375ae3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1127/HighFidelity-Beta-PR10591-b365e67840066335be7888af8ed263adc5375ae3.dmg

**Comment by ZappoMan** [comment]
This PR is a mess... it shouldn't have 655 files changed... it's been DNM for over a month. Closing it. @alhighfidelity you need to get a clean PR opened with your changes.

**Pull request closed without merging**
