### PR TITLE
turn ContextOverlays completely off/on

### PR DESCRIPTION
**Pull request by davidkelly**
This setting is temporary, and defaults to false so we don't have context overlays by default.

### CODE REVIEW

**Comment by howard-stearns** [comment]
nice

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2157/HighFidelity-Beta-PR11090-43c8079f0383c8f92ca44d1d21773d87a6c14221.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2157/HighFidelity-Beta-PR11090-43c8079f0383c8f92ca44d1d21773d87a6c14221.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2158/HighFidelity-Beta-PR11090-b371c875c47bf53a24857064c2dc5c3907fdbbc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2158/HighFidelity-Beta-PR11090-b371c875c47bf53a24857064c2dc5c3907fdbbc6.exe

**Pull request merged**
