### PR TITLE
fix crash on click on non-visible web-entity

### PR DESCRIPTION
**Pull request by jherico**
Fixes

* Crash when clicking an invisible web entity (that has never been visible to you)
* Crash when exiting the application with an invisible web entity selected in edit mode
* Invisible web entities should not gain keyboard focus

### CODE REVIEW

**Comment by jherico** [comment]
## Testing 

In the production build: 

* Create a web entity somewhere.  
* Edit the properties of the entity so it's not visible.  
* Click where the entity would be rendered....  instant crash

in this build, you should not crash.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e322c93bc1f50fb2238186ea4621d2c608a0f7e4 available at: https://gist.github.com/cd71a8517055be513cdf0e0b40e3b289<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.dmg

**Comment by Nex-Pro** [comment]
Crashes every time if invisible web entity is selected in edit mode and I quit interface.
Does not crash if an invisible cube or sphere is selected in edit mode and I quit.

Does not crash on clicking the invisible web entity in this pr or production.

crash described above also occurs in production.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef013fd38719c644501b9acfa6053b29bdee1872 available at: https://gist.github.com/cd71a8517055be513cdf0e0b40e3b289<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.dmg

**Comment by cozza13** [comment]
@jherico can you update this with master

**Comment by jherico** [comment]
@cozza13 done

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf734395e5db8a3eba70658d22e089725e5eed2f available at: https://gist.github.com/cd71a8517055be513cdf0e0b40e3b289<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7956.dmg

**Comment by Nex-Pro** [comment]
#7956

### See bugsplat as may be unassociated crash

**Fix 1:**

Create a web entity somewhere.
Edit the properties of the entity so it's not visible.
Exit the application and restart
Click where the entity would be rendered
**SUCCESS:** No crash experienced


**Fix 2:**

Create a web entity somewhere.
Edit the properties of the entity so it's not visible.
Leave the entity selected in edit mode
Exit the application
**PARTIAL SUCCESS:** Crashed once, but after resetting, a further 10 attempts to provoke a crash did not.

***Bugsplat submitted***


**Fix 3:**

Create a web entity somewhere.
Edit the properties of the entity so it's not visible.
Exit edit mode
Click on the (invisible) web entity
Web entity gains the glowing gold 'keyboard focus' indicator
In this build, you should not crash on the first two items and the third item should not allow the web entity to gain keyboard focus. 
**SUCCESS:** Web entity does not gain keyboard focus. Gold indicator does not appear.

**Pull request merged**
