### PR TITLE
add removal of resources folder before install

### PR DESCRIPTION
**Pull request by birarda**
- fix a bug with inclusion of old QML files that were not removed from resources
- make the client a required component during install

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

This fixes a specific bug that would occur on upgrading High Fidelity by re-running the installer.

(1) Install this PR build.
(2) Go to a domain where you have permissions to upload to the asset server, and confirm you can open the asset browser.
(3) Quit Interface.
(4) Drop [this file](https://gist.github.com/birarda/065e8454feae4526db4a3bd2bfa4ecc8) in your install folder for PR8519 (probably C:\Program Files\High Fidelity - PR8519\) at `resources/qml/styles-uit/MenuItem.qml`
(5) Relaunch Interface and re-attempt step 2. Confirm that you cannot open the asset browser. Close Interface.
(6) Re-run the installer from this PR build.  Confirm that `resources/qml/styles-uit/MenuItem.qml` is no longer in your install folder.
(7). Relaunch interface and attempt step 2. Confirm that you can open the asset browser.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5938a04db8ed39bda41867c158af8bee6aea42f2 available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-5938a04.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-5938a04.dmg

**Comment by birarda** [comment]
Don't QA this yet, it's running the delete commands after the install, so you don't get the resources dir at all. Need to see if we can make it respect the order.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e40e3539123915f343f7fb131dc3377cf01b7b8f available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-e40e353.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-e40e353.dmg

**Comment by imgntn** [comment]
afaik old javascript files stay around too...? @birarda

**Comment by huffman** [comment]
@imgntn We need to be careful not to delete files that a user has put in the install directory. Scripts is particularly hairy because there's a "Reveal Scripts Folder" right at the bottom of Running Scripts - I can imagine that at least some users store scripts there because of it.

**Comment by imgntn** [comment]
@huffman actually i'm totally down to remove that reveal scripts folder button.  you need admin access to edit anything anyways, so if you open a file in sublime or something you get an error when you save and you have to edit permissions.... perhaps this doesn't have much to do w. the QML files but that whole  ux loop is a little broken

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9ccf7b8831c4807dfbb5ee441ef0c505631f5e9b available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-9ccf7b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-9ccf7b8.dmg

**Comment by huffman** [comment]
@imgntn Good point, sounds like something we should probably do at some point then

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ade777567a49a3b77ac3f7552bf239ebc78cbe4 available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-5ade777.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-5ade777.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d0fce3bfed5c1f613a4d99a79f594558341bd1fe available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-d0fce3b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-d0fce3b.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

(1) Install this PR build. Confirm that it forces you to install Interface ("High Fidelity Client").

**No**  I was able to un-check client and install only sandbox.  The only thing that would block me moving to next step in install process was un-checking Interface and Sandbox options.

**Comment by OmegaHeron** [comment]
QA Pass

Testing Windows 10

(1) Install this PR build. Confirm that it forces you to install Interface ("High Fidelity Client").

Well -- yes/no.  If I've installed this PR before then it **does force me to install interface** - so it does work, I think I didn't understand it had to force Interface *if* it had been previously installed.  On a "clean" install it does not and that makes sense.  Sorry for red flag above.

(2) Go to a domain where you have permissions to upload to the asset server, and confirm you can open the asset browser.
**Yes - it works**

(3) Quit Interface.
(4) Drop this file in your install folder for PR8519 (probably C:\Program Files\High Fidelity - PR8519) at resources/qml/styles-uit/MenuItem.qml

(5) Relaunch Interface and re-attempt step 2. Confirm that you cannot open the asset browser. Close Interface.
**Yes - with qml file present asset browser does not work**

(6) Re-run the installer from this PR build. Confirm that resources/qml/styles-uit/MenuItem.qml is no longer in your install folder.
**Yes - file has been removed.**

(7). Relaunch interface and attempt step 2. Confirm that you can open the asset browser.
**Yes - asset browser launches.**

**Comment by birarda** [comment]
@OmegaHeron trying to figure out if we want to force that client install on first install - may need a re-QA depending on that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8272712bbb841a59eacf7a98ae85eded5492493 available at: https://gist.github.com/8fbb303b5f31ae6146f6cb7bbff9f5e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-a827271.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8519-a827271.dmg

**Comment by birarda** [comment]
@OmegaHeron if you could re-test this to confirm that Interface is always required, that would be great.

**Comment by OmegaHeron** [comment]
QA Pass
Testing Windows 10
Yes - Interface install is not optional on a clean install.  Sandbox portion remains an option.
Yes - It still clears out resources.
I expect some will object to this change that run stack on remote windows hosts.

**Comment by birarda** [comment]
@OmegaHeron I agree with you. I'll bounce this around - might go back to the previous method that only forces it on you if you've ever installed it.

**Pull request merged**
