### PR TITLE
Beta Release 54 - Includes up to Developer Release 7078

### PR DESCRIPTION
**Pull request by cozza13**
- Initial wallet app plus some encryption of security image 
 - More aggressive noise gate threshold 
 - Create home bookmark for new content sets loaded in 
 - Threaded rendering of Entities 
 - Fix ray pick crash on shutdown 
 - Blocks app accommodates updated Blocks website
 - Web overlays and entities are always non anti-aliased 
 - Additional locking in model entities 
 - Commerce Checkout and Purchases 
 - Fix crash close interface after switching from Desktop to VR
 - You can deselect your current view mode WIP on making proper fix
 - Updated Camera App
 - Remove most dependencies on 'onVisibleChanged' 
 - Implements a "Selection Scripting Interface", which allows JS or C++ to group gameplay items (entities, avatars, overlays) into a "selection", which then may or may not be pushed to the Scene.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3090/HighFidelity-Beta-PR11315-9bbcf3e1ae588dbe567012809262159e43c34268.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3090/HighFidelity-Beta-PR11315-9bbcf3e1ae588dbe567012809262159e43c34268.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3213/HighFidelity-Beta-PR11315-45a2c3d5d9d1b4a7a6762e36fa0e8f9724a995f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3213/HighFidelity-Beta-PR11315-45a2c3d5d9d1b4a7a6762e36fa0e8f9724a995f2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3233/HighFidelity-Beta-PR11315-bb26cf21791c0334d2810e4df6928bce078ac25f.dmg

**Comment by tapalisa** [comment]
2 people who tested this PR in the last 24 hours do not have their Tester Flag set. Please check your environment variable.

**Pull request merged**
