### PR TITLE
disable interstitial mode

### PR DESCRIPTION
**Pull request by danteruiz**
Disable interstitial mode

https://highfidelity.fogbugz.com/login?dest=%2ff%2fcases%2f19870%2fCompletely-disable-the-interstitial-loading-experience-for-a-75-1-hotfix-to-prevent-problems-with-FUTVRLANDS

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- Interstitial mode should be when switching domains.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15140/HighFidelity-Beta-PR14397-be2c254.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15140/HighFidelity-Beta-PR14397-be2c254.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15140/HighFidelity-Beta-Interface-PR14397-be2c254.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Interstitial mode is disabled.

**Pull request closed without merging**
