### PR TITLE
Fix interfaces scripts not copying from /scripts in local builds

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
https://app.asana.com/0/26225263936266/117911432935373

**Comment by huffman** [comment]
You will need to be able to build from source to test. To test:

 * Do a clean build of this code
 * Confirm that `/scripts` are available in your build directory
 * Confirm that in the Running Scripts window in Interface that the list of scripts at the bottom is populated.

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f92f29ecabe81c138be04e177fc240d105ea35d0 available at: https://gist.github.com/1ae3d1f0d7c99bc3870ef09f834b82e0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7776.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7776.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f92f29ecabe81c138be04e177fc240d105ea35d0 available at: https://gist.github.com/1ae3d1f0d7c99bc3870ef09f834b82e0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7776.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7776.dmg

**Pull request merged**
