### PR TITLE
Reinstate "reload" button for entity scripts in entities editor

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by howard-stearns** [comment]
Is this in response to a steam launch ticket? Which one?

**Comment by ctrlaltdavid** [comment]
QA

Previously, while entity scripts loaded locally from the file system were automatically refreshed periodically, entity scripts loaded from the Web were not.
This PR retains the auto-refresh of local scripts but adds a reload button after the entity script URL to force the immediate reload of local entity scripts and reload scripts from the Web.

Testing:
1) Script from local file system: Edited entity scripts are periodically reloaded but can be forced to immediately reload with the reload button.
2) Script from URL: Edited entity scripts can be reloaded with the reload button.

Simple test script that can be used (e.g., edit the string written to the program log) is attached.

[entityScript.zip](https://github.com/highfidelity/hifi/files/543057/entityScript.zip)

**Comment by ctrlaltdavid** [comment]
@howard-stearns No Steam FogBugz item that I'm aware of, just an odd job on my "to do" list.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c6558ebebd07a777c8de6148121ad8a893da5855 available at: https://gist.github.com/c4e00a0e58e0bce0a67cd704b2b2c1ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8870-c6558eb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8870-c6558eb.dmg

**Comment by thoys** [comment]
## QA-testing report

- tested ATP, local and HTTP(S) scripts. They all reload with the reload button.
- The behavior for the local scripts also reloading on change work. (After focussing the interface window)
- Also tested with an extra remote client, the log on that client showed an equal outcome with the reloads. Works perfectly.

QA Passed

(thanks for fixing this @ctrlaltdavid 🎉 )

**Pull request merged**
