### PR TITLE
Cruft removal

### PR DESCRIPTION
**Pull request by ZappoMan**
Removes old/unused features from the Octree. Specifically:
- *ability to request occlusion culling* - this feature never worked with entities
- *ability to request monochrome voxels* - this feature never worked with entities

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a471ee1a1bfa6fa8853883bab93da1212f0de104 available at: https://gist.github.com/eb79852ed189d2db8d27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 849a8707d2a1a91faa57ad4f809435e8904b8531 available at: https://gist.github.com/eb79852ed189d2db8d27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 849a8707d2a1a91faa57ad4f809435e8904b8531 available at: https://gist.github.com/eb79852ed189d2db8d27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.dmg

**Comment by Atlante45** [comment]
@ZappoMan Tested this PR, nothing suspicious at runtime.
It does add a couple warnings on mac though:
```
[ 55%] Building CXX object libraries/render/CMakeFiles/render.dir/src/render/Scene.cpp.o
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/octree/src/Octree.cpp: In member function ‘int Octree::encodeTreeBitstreamRecursion(OctreeElementPointer, OctreePacketData*, OctreeElementBag&, EncodeBitstreamParams&, int&, const ViewFrustum::location&) const’:
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/octree/src/Octree.cpp:1445:13: warning: variable ‘recursiveSliceSizes’ set but not used [-Wunused-but-set-variable]
         int recursiveSliceSizes[NUMBER_OF_CHILDREN];
             ^
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/octree/src/Octree.cpp:1446:30: warning: variable ‘recursiveSliceStarts’ set but not used [-Wunused-but-set-variable]
         const unsigned char* recursiveSliceStarts[NUMBER_OF_CHILDREN];
                              ^
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/octree/src/Octree.cpp:1447:13: warning: unused variable ‘firstRecursiveSliceOffset’ [-Wunused-variable]
         int firstRecursiveSliceOffset = packetData->getUncompressedByteOffset();
             ^
```

**Comment by ZappoMan** [comment]
Let me fix those warnings.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1df24dd174f57ec5394e3e0cf7239c2e37bf7930 available at: https://gist.github.com/eb79852ed189d2db8d27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 528b8e5d3f452937dba766f4fcb5f28bb06d9afe available at: https://gist.github.com/eb79852ed189d2db8d27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6538.dmg

**Pull request merged**
