### PR TITLE
remove code that sends entity 'touch' events

### PR DESCRIPTION
**Pull request by sethalves**
- remove hand-controller "touch" events

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- general testing of handControllerGrab.js

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/107214863719603

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0bd747fa06a8186cb6729d9178d190409fec32f2 available at: https://gist.github.com/d450b29e5a247db95f53a6ff5ce59c5e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7560.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7560.dmg

**Comment by ZappoMan** [comment]
are we sure we want to remove these events completely? having a touch event seems like a good thing -- maybe we just need to reduce the send rate and/or optimize them to not grab properties we don't need

**Comment by sethalves** [comment]
James, Philip and I talked it over.  We aren't currently using it in a significant way.  It's also possible for an entity script to get the same effect on its own, without support from handControllerGrab.js.

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0bd747fa06a8186cb6729d9178d190409fec32f2 available at: https://gist.github.com/d450b29e5a247db95f53a6ff5ce59c5e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7560.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7560.dmg

**Comment by imgntn** [comment]
@ZappoMan -- i added the touchtest a while back so that creators could just use startTouch and continueTouch events right on their entities, but it's just the 'point in extents' code from the touch entity example running all the time.  basically instead of the grab script doing that touch test all the time, we can put it into individual entities that need it.  a convenience method to wrap it up would be nice, but i dont think our current system supports an efficient enough way of running that touch test by default on all entities... very much open to suggestions.

**Comment by cozza13** [comment]
Have we changed how the reset happens on "demo" did it use this event?

**Comment by imgntn** [comment]
@cozza13 nope demo reset uses 'near trigger' event

**Comment by TNS-TrueNorth** [comment]
Performed the general testing of handControllerGrab.js and also general smoke test, we did not encounter any issues - passed on Windows 10.

**Pull request merged**
