### PR TITLE
Treat overlays as transparents

### PR DESCRIPTION
**Pull request by zzmp**
- Treat overlays as transparents in the rendering engine, delaying their rendering till after opaques
- Add a shader for explicitly transparent overlays (currently only applicable to `text3d`)

### CODE REVIEW

**Comment by zzmp** [comment]
An easy way to test this is to go to `0,0,5` and look in the -z direction, and run

```
set = []; for (var i = 0; i < 11; i++) set.push(Overlays.addOverlay('text3d', { position: { x: i - 1, y: 0, z: 0 }, backgroundAlpha: i * 0.01 }));
// set.forEach(Overlays.deleteOverlay); // to cleanup the overlays
```

Other types of overlays should also be tested to make sure their behavior is unchanged.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d685cebb0dfa2730948198d3701142b7f22b9e3 available at: https://gist.github.com/4f47175c17a476b6da27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 797de18a656678ea5209c711e538de26450c9e50 available at: https://gist.github.com/4f47175c17a476b6da27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.dmg

**Comment by zzmp** [comment]
I don't understand why 797de18 failed, and think it might have been a fluke.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e23accd05526ad0dcbeed201471772d30099ccb available at: https://gist.github.com/4f47175c17a476b6da27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6935.dmg

**Comment by zzmp** [comment]
This is broken, in that it should also update those places that ask for Overlay's, namely, `DrawOverlay3D`.

**Comment by zzmp** [comment]
Because overlays can be transparent/opaque and layered/not, they should be keyed appropriately and handled in the right draw tasks.
#6871 is pending to add instancing to the ShapePlumber, which overlays use heavily.

Once that is done, I will refactor this PR to:
- differentiate transparent/opaque
- include layered (drawInFront) bug
- retain instancing through the new ShapePlumber framework

Until then, this is on hold.

**Pull request closed without merging**
