### PR TITLE
Fix for avatar record only replaying once

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Minimal fix of https://highfidelity.manuscript.com/f/cases/12103/ for RC65.
Master PR: https://github.com/highfidelity/hifi/pull/12564/

### CODE REVIEW

**Comment by SimonWalton-HiFi** [comment]
Bug repro steps (from the fogbugz):

Using record.js app and associated playRecordingAc.js in unpublishedScripts/marketplace/record (https://raw.githubusercontent.com/highfidelity/hifi/master/unpublishedScripts/marketplace/record/playRecordingAC.js).

Simple repro:

- Make a recording with avatar movement and sound.
- Run 1 copy of playRecordingAC.js on the server.
- Load the recording. ... Avatar movement and sound plays back.
- Stop the recording.
- Load the recording. ... Only sound plays back.

You can reuse recordings for testing. Before the fix any recording will play the avatar once only; after the fix the avatar will play repeatedly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7797/app_12579_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7797/HighFidelity-Beta-PR12579-17c12fde9c66ca0fd723b478eee7aa4b93fab588.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7797/HighFidelity-Beta-PR12579-17c12fde9c66ca0fd723b478eee7aa4b93fab588.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Pass @conklin94122 

Animations and sounds were in sync and looped correctly!

**Pull request merged**
