### PR TITLE
Improved preview

### PR DESCRIPTION
**Pull request by ZappoMan**
Test plan:
- Smoke test
- With HMD - enable preview/mono-preview, you should now see a 16:9 preview.
- Make sure it's letterboxed and centered appropriately when you resize the desktop window.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8eb5f6682a7dbac0506f10b1e53fe554d5b9c0ff available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-8eb5f66.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-8eb5f66.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a39f81b961f053e10786c5b6cec6c9d56802f9d available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-0a39f81.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-0a39f81.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09b3292f94812fa7acdc98618cb037bf39439ec6 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-09b3292.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-09b3292.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f5c5ebf0e8fe120a4afa7d3b8a94a27151103e1 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-8f5c5eb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-8f5c5eb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 73a7d1b63b41ffddeaaab29f89f4c0653e3d5531 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-73a7d1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-73a7d1b.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAIL
**Additional Test Results + Observations**: HMD HUD icon not available.  I reloaded default scripts and it still did not work.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |58 |59 |58
**CPU Buffer Count**: |2838 |2644 |3858
**GPU Buffer Count**: |866 |770 |854
**CPU Memory Usage**: |51273728 |54034432 |84393984
**GPU Memory Usage**: |25907200 |31121408 |44576768
**CPU Texture Count**: |215 |225 |332
**GPU Texture Count**: |164 |147 |239
**GPU Transfer Count**: |9 |5 |0
**CPU Texture Memory Usage**: |299984604 |346191308 |411859224
**GPU Texture Memory Usage**: |310422447 |306250486 |889084670
**GPU Virtual Memory Usage**: |645742042|477807417|1014856278
**Triangle Count**: |1023746 |704306 |843716
**Triangle Rate**: |60220352 |44019125 |52732250
**API Drawcall Count**: |435 |245 |289
**Drawcall Count**: |436 |244 |1189
**Drawcall Rate**: |25647 |15250 |74312
**State Changes Texture Count**:|423 |266 |377
**Pipeline Count**: |50 |52 |57
**Item Opaques**: |278 |420 |309
**Item Translucents**: |24 |74 |58
**Item Lights**: |21 |78 |33
**Timing Opaques**: |0.768 |1.544 |0.997
**Timing Translucents**: |0.027 |0.194 |0.138
**Timing Lighting**: |0.066 |0.133 |0.129
**Render Frame**: |1.47 |3.032 |2.156

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52f0b5f6c864ac8ab6ded47f93239282ea1611a5 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-52f0b5f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-52f0b5f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c68d9abb363641d97b2415a1d007b5ea92a4e34 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-6c68d9a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-6c68d9a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc8aa540b4f027ceeea4101bcbc582a2e36fec79 available at: https://gist.github.com/202e5a6f1113d4cda5ddeb3575004f00<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-cc8aa54.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8623-cc8aa54.dmg

**Comment by kevinmthomasse** [comment]
Retest:
Enabling HMD - I enabled preview/mono-preview, I saw a 16:9 preview.
It is0 letterboxed and centered appropriately when you resize the desktop window as I unmaxed and then maxed the screen.

SUCCESS

**Comment by cozza13** [comment]
@kevinmthomasse Awesome. You will be able to now do some nice live streaming!

**Comment by kevinmthomasse** [comment]
@cozza13 Hell yea!  I cant wait to try!!!

**Pull request merged**
