### PR TITLE
Remove Entity Grab Highlighting for RC76

### PR DESCRIPTION
**Pull request by danteruiz**
Remove Grab Highlighting for RC76

- ticket - https://highfidelity.manuscript.com/f/cases/20021/

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14429

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15378/HighFidelity-Beta-PR14466-b54a028.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15378/HighFidelity-Beta-PR14466-b54a028.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15378/HighFidelity-Beta-Interface-PR14466-b54a028.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15407/HighFidelity-Beta-PR14466-b54a028.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15407/HighFidelity-Beta-PR14466-b54a028.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15407/HighFidelity-Beta-Interface-PR14466-b54a028.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15417/HighFidelity-Beta-PR14466-b54a028.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15417/HighFidelity-Beta-PR14466-b54a028.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15417/HighFidelity-Beta-Interface-PR14466-b54a028.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15421/HighFidelity-Beta-PR14466-b54a028.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15421/HighFidelity-Beta-PR14466-b54a028.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15421/HighFidelity-Beta-Interface-PR14466-b54a028.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15421/HighFidelity-Beta-PR14466-b54a028.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15421/HighFidelity-Beta-Interface-PR14466-b54a028.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
Passed @conklin94122 verified that grab highlighting has been removed.

**Pull request merged**
