### PR TITLE
Update BillboardOverlay to use NetworkTexture

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f24658f673495800eb8e3c62872fa4991bed8d7 available at: https://gist.github.com/77d0d328d5bf9ee6ebd6

**Comment by ZappoMan** [comment]
@huffman - looks like you need to merge with upstream

**Comment by huffman** [comment]
@ZappoMan I do this a lot...  Merged now

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42bab849905bc544c376de4d2f44c12ab849df9d available at: https://gist.github.com/687d2b8d2ff0104f833e

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42bab849905bc544c376de4d2f44c12ab849df9d available at: https://gist.github.com/ef8d209c42ee1cedae64

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42bab849905bc544c376de4d2f44c12ab849df9d available at: https://gist.github.com/6b0e9a5f3ea6d99a8aea

**Pull request merged**
