### PR TITLE
Fix projection & lighting issues identified with 2nd rendering pipeline In Master

### PR DESCRIPTION
**Pull request by samcake**
This PR is the cherry picked commit of this other PR against spectator Camera branch:
https://github.com/highfidelity/hifi/pull/10837

The test plan can be done through the 10837 pr

### CODE REVIEW

**Comment by CainFoool** [comment]
Testing when built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1195/HighFidelity-Beta-PR10853-b766c256dbfe20deb70a51df7df84f7ef2cad8cd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1195/HighFidelity-Beta-PR10853-b766c256dbfe20deb70a51df7df84f7ef2cad8cd.dmg

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Verify that the lighting bug & projection bug are solved in this pr compared to the spectator camera main branch. | Pass
Testing the HMD simulator (available in the choice of displays when the env variable HIFI_DEBUG_HMD is defined), verify that the rendered camera frame is correct. | Pass

I was having a small issue with regards to the lighting not updating in the HMD Simulator, it seemed to be focused on the middle and not moving where the camera was moving.

See [attached webm](https://files.cainkilgore.com/2017-06-29_10-48-48.mp4). Currently able to replicate in the latest dev-download so not relevant to this PR.

**Comment by howard-stearns** [comment]
confirmed from https://github.com/highfidelity/hifi/pull/10837

**Pull request merged**
