### PR TITLE
fix Places / Paths anchor in domain settings

### PR DESCRIPTION
**Pull request by birarda**
- fixed a broken settings group button in domain-server settings

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan 

Run the sandbox from this PR. Go to your domain-server settings. Scroll down the page and click on the "Places / Paths" button. You should jump to the "Places / Paths" section. This does not work on master.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab7ce1921159a21efac98932071b6ad0e97fbbb1 available at: https://gist.github.com/8a659f51d5757aa5d77065d9ce0a9add<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9471-ab7ce19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9471-ab7ce19.dmg

**Comment by birarda** [comment]
test this please

**Comment by birarda** [comment]
Faceshift download fail

**Comment by OmegaHeron** [comment]
Tested Windows 10/Ubuntu 16.04.1

QA Pass

Verified master has incorrect URL format for places anchor.

This PR fixes that and I went ahead and checked all anchor jumps with/without advanced settings shown.  All good.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab7ce1921159a21efac98932071b6ad0e97fbbb1 available at: https://gist.github.com/8a659f51d5757aa5d77065d9ce0a9add<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9471-ab7ce19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9471-ab7ce19.dmg

**Pull request merged**
