### PR TITLE
WL#21166 Cloneable Equipment

### PR DESCRIPTION
**Pull request by Menithal**
https://worklist.net/21166

Adds four new grabbableKey fields that can be adjusted from the edit window

- cloneable: boolean value to allow for cloneable or non-cloneable.
- cloneLifetime: sets the life time for the clones
- cloneLimit: sets the max amount of clones you can have within a 50m radius
- cloneDynamic: Allows the cloned object to be dynamic

new edit window

To test you will need hand controllers, Vive or Oculus Touch:

# Test Prep

1. Rez A Bow, Pingpong gun, Flaregun, or hookshotgun from the the marketplace
2. Set Cloneable on the objects
3. Dynamic and Grabbable should go off (edit.js only)
4. Turn off Edit window

# General Clonable Test 

1. Attempt to far grab object. It should not allow you to drag the source.
2. Go near the source and grab it with the trigger (or grips, but hold grips),
 a new clone of object should equip like any other object would.
3. You should be able to fire / use the object  
4. You should be able to drop object.

#  Limit Test

Suggest setting Cloneable dynamic, and gravity on source, then use the grip buttons to clone and throw the clone off as many times until it spawns none.

You  should only be able to clone the amount of clones that is set in cloneLimit.  Default, if not defined in the userdata, should be 10 units

# Lifetime Test

All cloned objects should have a lifetime and should expire eventually. This is set according to cloneLifetime. Default, if not defined in the userdata, should be 300s.

# Lock Test

You should have lock permissions: locking the entity should still allow others to interact and grab a clone.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d8be2aeaa682c3fa33b65077f6eb3543c09a995 available at: https://gist.github.com/1ae49de0f60dff21a1312d035891a216<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-1d8be2a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-1d8be2a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69949cd6b56c18bd173b9a59a209038c8e41d24f available at: https://gist.github.com/1ae49de0f60dff21a1312d035891a216<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-69949cd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-69949cd.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
@Menithal  This is disabling my lasers. They are fine until I equip a cloneable item.

**Comment by Menithal** [comment]
Hmm thats odd, will investigate and try and get it fixed.

**Comment by Menithal** [comment]
There was some oddities with the last build that I didnt experience with my local version of the script. Did some formating fixes and lets see if this is now correct build

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9fbde41dc45508324ac1feef09f647cc51b39c44 available at: https://gist.github.com/1ae49de0f60dff21a1312d035891a216<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-9fbde41.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-9fbde41.dmg

**Comment by Menithal** [comment]
I tried to repo the issue with the latest Gustavo build, but I dont seem to have any luck. Even cleared my cache but couldn't repeat the issue of the lasers stopping working.

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Menithal** [comment]
Did a Quick Resolve conficts. unfortunately since I ain't home I couldn't dev test the changes done.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e21785d5ecc8045aa19f0a0d506f9fa6660b33cd available at: https://gist.github.com/1ae49de0f60dff21a1312d035891a216<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-e21785d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-e21785d.dmg

**Comment by Menithal** [comment]
QA Fail, @Nex-Pro found some issues regarding the unequip event not triggering on initial clone, and I found some issues that happened after the merge.

**Comment by tapalisa** [comment]
[ClonableClass (1).pdf](https://github.com/highfidelity/hifi/files/809505/ClonableClass.1.pdf)

**Comment by Menithal** [comment]
@tapalisa not sure why you linked to the spec, as I had the link to the worklist ticket it self above.
 but I assume its something to do with the positioning of the UI:

 I took the liberty to moving the Cloneable settings to the side due to a couple of UX reasons:

A. Its closer to the Cloneable checkbox. thus more noticable when it is cloneable field is active (it is supposed to appear / dissapear when true / false
B. It is closer to the dynamic value, which makes it easier to notice that the object cannot be dynamic at the same time while it is cloneable. 
C.  The Property Edit is becoming long enough as it is. Needs really trimming down.

**Comment by tapalisa** [comment]
Hi, 

I think the default values for the lifetime and limit weren't in the test plan, which is why I included the spec. Sorry, I should have written a comment!

Alisa

**Comment by hifi-gustavo** [comment]
Build console output for commit: 231ebef1170822d1d7d71b1ccd5b043e676932a9 available at: https://gist.github.com/1ae49de0f60dff21a1312d035891a216<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-231ebef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9761-231ebef.dmg

**Comment by Menithal** [comment]
Ready to test.

**Comment by Nex-Pro** [comment]
testing this now

**Comment by Nex-Pro** [comment]
### PASS

Went thru the test notes exhaustively and all points were satisfied.

**Comment by sethalves** [comment]
Some of the indentation in the PR is wrong, but I'll patch it up in another PR.

**Comment by tapalisa** [comment]
What am I missing here?
-I create a sphere
-I make it 'cloneable' in the entity property menu
-I leave the default options
-I put my hand in the sphere and click trigger (or grip, either one) and pull my hand away
-I do not get a clone of the object.

**Comment by ZappoMan** [comment]
This only works on equip-able things. It should work on all things... sphere example, simple model example, etc.

**Comment by Menithal** [comment]
All entities, even non equippable ones were tested to be cloneable (we were cloning spheres to be shot at with the bow with @Nex-Pro )

You just have to make sure edit is off before grabbing anything that is cloneable. (it shouldnt be distinguishing  equippable or non-equippable) 

https://youtu.be/PgPXm4z8H64 
(using master build, default scripts)

If this doesnt work for others, I need more info

**Comment by tapalisa** [comment]
I did make sure edit was off...not sure what else might be going on.

**Comment by Menithal** [comment]
What the HMD set you are using? perhaps that has anything to do with it, but I doubt it as its using the very same equip/grab logic as it always has, with the addition of just creating a new entity.

I tried again by stopping all scripts, clearing my cache and loading the default scripts again and I still cannot replicate the issue you are describing. 

All cloneable objects, once the hand controllers are within near grab range and vibrate are cloneable.

 You can not, however use far grab on them and you must reach out and grab it.

**Comment by tapalisa** [comment]
I'm using a Rift. I did test in Dev-Welcome, but testing on the Bow proved successful in that space while the same actions on a sphere I'd just created or one of the building blocks were not successful. I did reach out and grab them- I did not attempt to far-grab.

**Comment by sethalves** [comment]
clonable, non-equippable entities are working for me.

**Comment by tapalisa** [comment]
Seth and I did some testing and there seems to be something broken about the clone limit.

**Comment by tapalisa** [comment]
Seth suggested removing the clone limit- Philip doesn't like it anyway :)

**Comment by Menithal** [comment]
We can remove it from the next iteration, atm the clone limit was based on the name. so if you had multiple boxes around it would have counted those, but I think the find method was incorrect. Ill make a PR with a fix that removes the limit.

**Comment by tapalisa** [comment]
Oh, then is it possible that if I was in a domain with a bunch of
identically named items (like dev welcome), that it won't make any more
copies?

**Comment by Menithal** [comment]
@tapalisa yes that can effect it,

I made a new PR addressing all of the issues discussed here

Limit is now by default off,
Range logic fixed
Cloneable count is now calculated by source.id instead of by name
Cloneable items are now identifiable
Fixes to tabs

https://github.com/highfidelity/hifi/pull/9807

**Pull request merged**
