### PR TITLE
Fix a few sitting bugs noticed at the meetup

### PR DESCRIPTION
**Pull request by Atlante45**
- Teleport target say cancel if someone is sitting in the chair
- Fingers can move while seated
- Prefetch sitting animation
- If several users manage to get in a seat at the same time, pop one out of it
- Tall avatar are less likely to get stuck in geometry

## Test Plan:

[Chair](https://s3-us-west-1.amazonaws.com/hifi-content/clement/dev/chair.json)
Make sure you are using the defaultScripts.js from this PR.

#### SIT-08 Test
Objective: Teleport target say cancel if someone is sitting in the chair.
Precondition: You must be in an HMD.
Step 1: Point your teleport beam at a chair with someone sitting in it.
Test Data: Use the chair provided.
Expected Result: The teleport target should turn yellow and say "Cancel"
#### SIT-09 Test
Objective: Fingers can move while seated.
Precondition: You must be in an HMD.
Step 1: Sit down on the chair
Step 2: Move your fingers, squeeze your hands with the grab button.
Test Data: Use the chair provided.
Expected Result: Your fingers should move as expected.
#### SIT-10 Test
Objective: Can't have several people sit in the same chair.
Precondition: Enter a domain with one other person or use 2 computers at the same time.
Step 1: Using voice to synchronize, try to sit in the same chair at the exact same time.
Test Data: Use the chair provided.
Expected Result: Both avatars should get teleported to the chair, but one should immediately pop out of it.
#### SIT-11 Test
Objective: Sitting animation is prefetched.
Precondition: Delete or save you interface cache if you don't want to lose it. `C:\Users\<username>\AppData\Local\High Fidelity[ - PRxxxx]\Interface\data8`
Step 1: Start interface.
Step 2: Go to a chair.
Step 3: Look at your legs while sitting down
Test Data: Use the chair provided.
Expected Result: There should be no perceivable delay between the time you get teleported to the chair and the time your avatar gets into a sitting pose.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: eab2c314d8cd6cb925f1fb8179a7bccda3b4fcb0 available at: https://gist.github.com/e19494b613aab7167fcc6716aa389138<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9940-eab2c31.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9940-eab2c31.dmg

**Comment by ZappoMan** [comment]
@Atlante45 - please flesh out these test plans as part of the test plan library... it sounds like you've got lots of good details for several different sit tests.

**Comment by Nex-Pro** [comment]
Hi @Atlante45  can you clarify the test plan ?

Does 'Teleport target say cancel if someone is sitting in the chair' mean a log message ?

Holding off testing until I get your reply.  Thanks.

**Comment by Atlante45** [comment]
@Nex-Pro I updated with a more detailed test plan.
What I meant by that is the end of the teleport beam that usual changes colors and say "Teleport" or "Sit" should be yellow and say "Cancel"

**Comment by Nex-Pro** [comment]
Ok will continue after other requests are completed.

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
Win10 and Vive and Oculus touch.

## FAIL
Test Plan:

SIT-08 Test

Objective: Teleport target say cancel if someone is sitting in the chair.
Precondition: You must be in an HMD.

Step 1: Point your teleport beam at a chair with someone sitting in it.

Test Data: Download chair from the marketplace. **: DONE**

Expected Result: The teleport target should turn yellow and say "Cancel"**: SUCCESS**

SIT-09 Test

Objective: Fingers can move while seated.**: FAIL**
Precondition: You must be in an HMD.
Step 1: Sit down on the chair
Step 2: Move your fingers, squeeze your hands with the grab button.
Test Data: Download chair from the marketplace.**: DONE**
Expected Result: Your fingers should move as expected.**: FAIL**

SIT-10 Test

Objective: Can't have several people sit in the same chair.**: FAIL**
Precondition: Enter a domain with one other person or use 2 computers at the same time.
Step 1: Using voice to synchronize, try to sit in the same chair at the exact same time.**: DONE**
Test Data: Download chair from the marketplace.**: DONE**
Expected Result: Both avatars should get teleported to the chair, but one should immediately pop out of it.**: FAIL** Able to do so several times did not get popped off.

SIT-11 Test

Objective: Sitting animation is prefetched.**: FAIL**
Precondition: Delete or save you interface cache if you don't want to lose it. C:\Users\<username>\AppData\Local\High Fidelity[ - PRxxxx]\Interface\data8**: DONE**
Step 1: Start interface.**: DONE**
Step 2: Go to a chair.**: DONE**
Step 3: Look at your legs while sitting down**: DONE**
Test Data: Download chair from the marketplace.**: DONE**
Expected Result: There should be no perceivable delay between the time you get teleported to the chair and the time your avatar gets into a sitting pose.**: FAIL**

Delay of approx 2 seconds.

**Comment by Atlante45** [comment]
@Nex-Pro Can you try again with the chair I added to the description?
Also make sure to use the defaultScripts.js from this PR.

**Comment by Nex-Pro** [comment]
testing this again.

**Comment by Nex-Pro** [comment]
## PASS

Make sure you are using the defaultScripts.js from this PR.**: DONE**

### SIT-08 Test: PASS

Objective: Teleport target say cancel if someone is sitting in the chair.

Precondition: You must be in an HMD.**: DONE**

Step 1: Point your teleport beam at a chair with someone sitting in it.
Test Data: Use the chair provided.**: DONE**

Expected Result: The teleport target should turn yellow and say "Cancel"**: SUCCESS**


## SIT-09 Test: PASS

Objective: Fingers can move while seated.

Precondition: You must be in an HMD.**: DONE**

Step 1: Sit down on the chair**: DONE**

Step 2: Move your fingers, squeeze your hands with the grab button.

Test Data: Use the chair provided.**: DONE**

Expected Result: Your fingers should move as expected.**: SUCCESS**


## SIT-10 Test: PASS

Objective: Can't have several people sit in the same chair.**: DONE**

Precondition: Enter a domain with one other person or use 2 computers at the same time.**: DONE**

Step 1: Using voice to synchronize, try to sit in the same chair at the exact same time.**: DONE**

Test Data: Use the chair provided.

Expected Result: Both avatars should get teleported to the chair, but one should immediately pop out of it.**: SUCCESS**


## SIT-11 Test: PASS

Objective: Sitting animation is prefetched.

Precondition: Delete or save you interface cache if you don't want to lose it. C:\Users\<username>\AppData\Local\High Fidelity[ - PRxxxx]\Interface\data8


Step 1: Start interface.

Step 2: Go to a chair.**: DONE**

Step 3: Look at your legs while sitting down**: DONE**

Test Data: Use the chair provided.**: DONE**

Expected Result: There should be no perceivable delay between the time you get teleported to the chair and the time your avatar gets into a sitting pose.**: SUCCESS**

**Pull request merged**
