### PR TITLE
Fix laser end not disappearing

### PR DESCRIPTION
**Pull request by SamGondelman**
Caused by https://github.com/highfidelity/hifi/pull/11786

Need to set dirty flag on visibility change,

To test:
- Use the hand lasers.
- When you let go of the trigger, the sphere at the end of the laser should disappear properly.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4825/HighFidelity-Beta-PR11790-9188ae9fb5ded91917cc251fdd6cdb5a7d1d6cc5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4825/HighFidelity-Beta-PR11790-9188ae9fb5ded91917cc251fdd6cdb5a7d1d6cc5.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Use the hand lasers. **Check**
When you let go of the trigger, the sphere at the end of the laser should disappear properly. **Check**

Went through trying to break it so the spheres would stay, but I am pleased to say nothing I did was able to have a negative effect, **Pass**

**Pull request merged**
