### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Atlante45**
This PR fixes some warnings introduced by #11349

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Use the same test plan as the one specified in #11349

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4019/HighFidelity-Beta-PR11563-cea0f48e5c73e3e98835122f590c5e4e8cade46d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4019/HighFidelity-Beta-PR11563-cea0f48e5c73e3e98835122f590c5e4e8cade46d.exe

**Comment by themelissabrown** [comment]
TEST PLAN
This test plan should be run an all types of GPUs (AMD, NVIDIA and Intel).
All sky maps should render as expected, without visually incorrect colors.
Ambient maps should render as expected, without visually incorrect colors.
To help visualize this, you can run the script scripts/developer/utilities/render/debugDeferredLighting.js and enable the "Zone Stack" checkbox.

**Comment by Nex-Pro** [comment]
Underway

**Comment by Nex-Pro** [comment]
Rendering looks fine.

Took several attempts to get the zone stack to show properly. I had to turn the zones on and off and click the stack checkbox a couple of times.

Apart from that and a crash when using ctrl+j ( probably not related to this pr )

**Comment by Nex-Pro** [comment]
207644-hifi-snap-by--on-2017-10-11_00-06-35
207644-hifi-snap-by--on-2017-10-11_00-15-36
207644-hifi-snap-by--on-2017-10-11_00-13-44
207644-hifi-snap-by--on-2017-10-11_00-08-09
207644-hifi-snap-by--on-2017-10-11_00-07-54

**Comment by Nex-Pro** [comment]
@Atlante45 ^

**Pull request merged**
