### PR TITLE
Merge RC67 stable into master

### PR DESCRIPTION
**Pull request by conklin94122**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9667/app_13145_PR_befb411f6ea3f5147dc93310dc39237f22caf145.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9667/HighFidelity-Beta-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9667/HighFidelity-Beta-Interface-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.dmg

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9683/app_13145_PR_befb411f6ea3f5147dc93310dc39237f22caf145.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9683/HighFidelity-Beta-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9683/HighFidelity-Beta-Interface-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9683/HighFidelity-Beta-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9683/HighFidelity-Beta-Interface-PR13145-befb411f6ea3f5147dc93310dc39237f22caf145.dmg

**Pull request merged**
