### PR TITLE
Case 20200: Update EntityScriptingInterface to not find local entities (#2)

### PR DESCRIPTION
**Pull request by SamGondelman**
Same as https://github.com/highfidelity/hifi/pull/14547 but it doesn't break everything

Test plan:
- run all the engine/interaction tests from hifi_tests
- Run [this](https://gist.githubusercontent.com/SamGondelman/33da7f2cb8d798f934aa6c11ee68bd64/raw/68cdfb200c626495cfdb17c22d2b6f275be67cdf/FindEntitiesTest.js).  You'll see this:
image
- Verify that the hand laser works on the tablet and that you can click on things.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16119/HighFidelity-Beta-PR14634-8dae250.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16119/HighFidelity-Beta-PR14634-8dae250.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16119/HighFidelity-Beta-Interface-PR14634-8dae250.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16119/HighFidelity-Beta-PR14634-8dae250.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16119/HighFidelity-Beta-Interface-PR14634-8dae250.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS

The script's cubes are colored correctly, without side effects on interactivity or engine tests.

**Pull request merged**
