### PR TITLE
be more defensive in FBXGeometry::convexHullContains

### PR DESCRIPTION
**Pull request by sethalves**
- possible fix for a crash in FBXGeometry::convexHullContains

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/101905459350876

**Comment by sethalves** [comment]
to test:
- smoke test, no known repro

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47fb85eaeb4057edbe2f302a4957c080923e3910 available at: https://gist.github.com/5f328234da025dc2b6a3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7425.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7425.dmg

**Comment by OmegaHeron** [comment]
Tested Window 7 - No issues seen - meshes + compounds work, added new one all good. :+1:

**Pull request merged**
