### PR TITLE
Move Shapes app from hifi to hifi-content

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9942/HighFidelity-Beta-PR13203-431c95cba964e9ee928b24df3058b87b89168b30.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9942/HighFidelity-Beta-PR13203-431c95cba964e9ee928b24df3058b87b89168b30.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9942/HighFidelity-Beta-Interface-PR13203-431c95cba964e9ee928b24df3058b87b89168b30.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9942/HighFidelity-Beta-PR13203-431c95cba964e9ee928b24df3058b87b89168b30.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9942/HighFidelity-Beta-Interface-PR13203-431c95cba964e9ee928b24df3058b87b89168b30.exe

**Pull request merged**
