### PR TITLE
never re-use node ID during domain connection

### PR DESCRIPTION
**Pull request by birarda**
https://highfidelity.manuscript.com/f/cases/15283/Invisible-avatars-at-The-Spot

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10019/HighFidelity-Beta-PR13216-666bdb03b72c569fee0f7d0039ded1b6babd1785.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10023/HighFidelity-Beta-PR13216-8f6600facf838a3155b552a4fe7d08a24e096922.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10023/HighFidelity-Beta-PR13216-8f6600facf838a3155b552a4fe7d08a24e096922.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10023/HighFidelity-Beta-Interface-PR13216-8f6600facf838a3155b552a4fe7d08a24e096922.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10023/HighFidelity-Beta-PR13216-8f6600facf838a3155b552a4fe7d08a24e096922.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10023/HighFidelity-Beta-Interface-PR13216-8f6600facf838a3155b552a4fe7d08a24e096922.exe

**Comment by birarda** [comment]
This needs an additional component so that `udt::Connection` objects are re-used, otherwise the first identity packet will not arrive

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10051/HighFidelity-Beta-PR13216-14ef2f52bbe2c7965906c75b4895c3834047508f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10055/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10055/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10055/HighFidelity-Beta-Interface-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10055/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10055/HighFidelity-Beta-Interface-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10056/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.apk

**Comment by birarda** [comment]
#### Test Plan

To test this fix you will need to use [Clumsy](https://jagt.github.io/clumsy/). You will perform the steps below on master and using this PR. On master, in step X you should not see the other avatar re-appear. With this PR, the other avatar should always re-appear.

1. Run a Sandbox that uses a temporary place name. You should get a temporary place name on first launch of the Sandbox. You may need to clear your settings file for the master Sandbox build to re-create a first launch.
2. Confirm your domain-server port is either the default (40102) or some other known value. 
3. Connect to the Sandbox with two Interface clients. One must be on a different machine.
4. Confirm that each Interface client can see the avatar of the other.
5. On the machine running only an Interface client, run clumsy. Filter `udp ipv4 against port` and change `udp.DstPort == X` and `udp.SrcPort == X` to match the port you noted in step 2. Enable Drop with a chance of 100%.
6. Start clumsy. As soon as you see the other avatar disappear in the Interface client on the machine running clumsy, stop clumsy.
7. On master, when you re-connect to the domain (which can be confirmed by the title bar or the stats) you should not see the other avatar re-appear. With this PR, when you re-connect to the domain you should see the other avatar re-appear.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10056/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10056/HighFidelity-Beta-Interface-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10056/HighFidelity-Beta-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10056/HighFidelity-Beta-Interface-PR13216-d1ace7914e8da8369942de4b84e5de9d0403c624.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 
web entities are causing crashes when zone is left while web entity is loading. Behavior exhibited is identical to Manuscript ticket 14596. Defect does not occur on Master

**Comment by qligmaloney** [comment]
PASS @conklin94122 
Crash occurred in stable. Avatars reappeared after dropping packets / returning back to the domain

**Pull request merged**
