### PR TITLE
filter out left/right hands from joints list in avatarapp (RC72)

### PR DESCRIPTION
**Pull request by ElderOrb**
should fix:
FB17884 - Wearable disappears when added to some joints
FB17885 - Changing werable joint moves the model and detaches from avatar body

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12480/HighFidelity-Beta-PR13898-8f9baf8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12480/HighFidelity-Beta-PR13898-8f9baf8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12480/HighFidelity-Beta-Interface-PR13898-8f9baf8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12480/HighFidelity-Beta-PR13898-8f9baf8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12480/HighFidelity-Beta-Interface-PR13898-8f9baf8.exe

**Comment by tapalisa** [comment]
Test Plan:
-In the Avatar Wearable Menu select "Add custom"
-Use this FBX link, as an example http://mpassets.highfidelity.com/f18a6b2b-6bd1-4c29-b2b7-9373782082fe-v1/model.fbx
-In the Joint dropdown menu, check that LeftHand and RightHand are not available
-Switch joints on the item several times, ensure that the wearable moves correctly between the joints and does not disappear.

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

User Wear app to add listed wearable .fbx, checked joints for LeftHand and RightHand which were not present. Moved between multiple joints and the object did not disappear and showed in the correct relation to the joint. PR Passes.

**Pull request merged**
