### PR TITLE
Prioritize file:// requests over http://

### PR DESCRIPTION
**Pull request by druiz17**
Prioritize the loading of local resources

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Do a clean install
- do not have your domain running
- start interface in HMD mode..bring up the tablet
- hover your hand over the tablet
- the stylus should be one of the first models to load.

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1697/HighFidelity-Beta-PR10968-68fa426da97c3288bd74b94c31aeaaefb81dba90.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1697/HighFidelity-Beta-PR10968-68fa426da97c3288bd74b94c31aeaaefb81dba90.exe

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Do a clean install | Pass
do not have your domain running | Pass
start interface in HMD mode..bring up the tablet | Pass
hover your hand over the tablet | Pass
the stylus should be one of the first models to load. | Pass

All working good - let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
