### PR TITLE
Fix finding the SSL binary path

### PR DESCRIPTION
**Pull request by jherico**
## Testing

* Install the PR.  
* If you do not already have dependency walker, install it from [here](http://www.dependencywalker.com/depends22_x64.zip)
* Open Dependency Walker
* In Dependency Walker, open the PR installation folder and select the ssleay32.dll
* Wait for it to load up the dependency tree.  Click through any warnings.  
* Hit Ctrl-W to collapse the tree, then re-expand the top level.
* Look down the tree, and locate either `MSVCR120.DLL` or `VCRUNTIME140.DLL`

If the installation depends on `VCRUNTIME140.DLL` then it's a pass.  If it depends on `MSVCR120.DLL` or includes any other VC Runtime DLLs that aren't labeled as 140, then it's a fail.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4657/HighFidelity-Beta-PR11738-56b1c7d0eeb03bc6ba1504ac71dd1ebbc26b2bec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4657/HighFidelity-Beta-PR11738-56b1c7d0eeb03bc6ba1504ac71dd1ebbc26b2bec.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Install the PR. | Pass
If you do not already have dependency walker, install it from here | Pass
Open Dependency Walker | Pass
In Dependency Walker, open the PR installation folder and select the ssleay32.dll | Pass
Wait for it to load up the dependency tree. Click through any warnings. | Pass
Hit Ctrl-W to collapse the tree, then re-expand the top level. | Pass
Look down the tree, and locate either MSVCR120.DLL or VCRUNTIME140.DLL | Pass (VCRUNTIME.dll)

Looks good!

**Pull request merged**
