### PR TITLE
Beta Release 14.1 - fix metadata hours migrations for new users/version bumps

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
Fixes gets to nested descriptors, which will crash if config.json is cleared, by validating the keys before fetching them.

**Comment by zzmp** [comment]
#### Testing

Clear your config.json (on Windows, it lives in %APPDATA%/Roaming/High Fidelity/domain-server/config.json), and ensure that the domain-server will still run.

Ensure your metadata still goes out correctly in the logs, when you change things like hours.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c406538301a4a30c8937a2475ae1c144b76a4cbe available at: https://gist.github.com/9dfb04d577639cc8d55458b9df14bdf6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8148.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8148.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** UNKNOWN
**Additional Test Results + Observations**: Deleted ```%APPDATA%/Roaming/High Fidelity/domain-server/config.json```.  Installed PR.  Ran PR.  Visited ```localhost```.  Nothing loaded as there was no content however 5 servers were present.  Log file included however I was unable to properly interpret data inside log so it is attached for further inspection.  Screen shot included as well.  I was able to successfully visit ```dev-demo``` and content did appear.  Please examine the log and report back additional testing steps to which I will do to get a better conclusive result for you.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/337956/hifi-log.txt)
capture

**Comment by zzmp** [comment]
Two more things to test:
- Make sure you can still enter operating hours after you've deleted the config.
- The config location that I included was for High Fidelity release - make sure you delete the config for the PR install.

**Comment by zzmp** [comment]
Domain server logs live in C:\Users\User\AppData\Roaming\High Fidelity\Server Console\logs

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS.  Worked step-by-step with @zzmp to ensure clarity.  I successfully set operating hours after deleting the config file as the result of the domain-server log ```QJsonObject({"capacity":0,"description":null,"hosts":[],"hours":{"utc_offset":-4,"weekday":[["02:00","13:59"]],"weekend":[["04:00","14:59"]]},"maturity":null,"restriction":"open","tags":[]})```.

**Pull request merged**
