### PR TITLE
Revert "Remove _model from ModelMeshPartPayload"

### PR DESCRIPTION
**Pull request by SamGondelman**
Reverts highfidelity/hifi#12026

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5841/app_12065_PR.apk

**Comment by samcake** [comment]
WE  will fix the new bug observed with overlay transparent and not revert that work

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5841/HighFidelity-Beta-PR12065-13ee511c726482cfaddd6c6271dd79c33fb8e38c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5841/HighFidelity-Beta-PR12065-13ee511c726482cfaddd6c6271dd79c33fb8e38c.exe

**Pull request closed without merging**
