### PR TITLE
fix avatar app from crashing when avatar entity variable is undefined.

### PR DESCRIPTION
**Pull request by danteruiz**
fix avatar app from crashing when avatar entity variable is undefined.

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- launch the avatar app
- the avatar app should display the persons personal bookmarks.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11461/HighFidelity-Beta-PR13661-ce3922a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11461/HighFidelity-Beta-PR13661-ce3922a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11461/HighFidelity-Beta-Interface-PR13661-ce3922a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11464/HighFidelity-Beta-PR13661-9bf6cff.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11464/HighFidelity-Beta-PR13661-9bf6cff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11464/HighFidelity-Beta-Interface-PR13661-9bf6cff.exe

**Comment by wayne-chen** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11465/HighFidelity-Beta-PR13661-9bf6cff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11465/HighFidelity-Beta-PR13661-9bf6cff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11465/HighFidelity-Beta-Interface-PR13661-9bf6cff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11465/HighFidelity-Beta-PR13661-9bf6cff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11465/HighFidelity-Beta-Interface-PR13661-9bf6cff.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @qliacoombs @conklin94122 
App opens and displays bookmarks

**Pull request merged**
