### PR TITLE
disable caching for asset requests in domain-server

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
Ran this locally, no data8 folder in domain-server folder but assets present in backups folder.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7366/app_12457_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7379/app_12457_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7379/HighFidelity-Beta-PR12457-946474c615815d8b209e3291fbe1c11a9fed9714.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7379/HighFidelity-Beta-PR12457-946474c615815d8b209e3291fbe1c11a9fed9714.exe

**Pull request merged**
