### PR TITLE
Beta Release 18 - Includes up to Developer Release 5232

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Fix depth state caching / resetting
* Better allocation of CPU time while loading scenes and when slow scripts are running
* Asset browser ui: Add dynamic and collision shape selection to add to world flow from asset browser. 
* Deferred batches: Part 1 of a project to migrate backend rendering execution off the main thread. This will cause all batches to be generated for a frame, and once the frame is complete, cause all the batches to be executed, rather than doing a per-batch build/execute 
* Tuned haptic pulses for grab, release, equip, de-quip on the Vive
* Fix alpha cut-outs and incorrect gamma on web overlays and entities
* Fixes a bug in `Assets.getMapping` where it wasn't providing the hash value back to the QML callback. 
* Groups: Permissions can be granted or revoked based on users' memberships in groups within the Domain Server security section.
* Add OverlayWebWindow resized, moved, and closed signals
* New Progress.js capability that corrects displays scene loading
* kick
- add the ability to kick (via mod.js) 
- add IP based permissions to domain-server settings 
- Allow the ability to grant other users kick permissions. 
* If the oculus HMD isn't on someone's head, don't take input from the controllers
* Bug fix for avatar debug marker rendering.
* Tweak Teleport + Hand Lasers
* Added dead zones to Hydra and Oculus Touch joysticks
* Implement codec renegotiation in client
* Fix remote triggering handControllerGrab 
* Fix bug which caused getValue for a non-existent key to return the integer 2
* Fix some group-related code to handle CamelCase usernames

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0338ceb4914310271732efe429451a4657b00e6 available at: https://gist.github.com/093d00832f3a27c9eec74483c77d6056<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8376-f0338ce.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8376-f0338ce.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Everything worked as expected and hydras were effective again as their was an earlier bug that is now resolved.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |52 |51
**Present Rate**: |60 |59 |60
**Present New Rate**: |60 |55 |59
**CPU Buffer Count**: |2802 |1750 |3852
**GPU Buffer Count**: |756 |427 |892
**CPU Memory Usage**: |57806848 |45379584 |68386816
**GPU Memory Usage**: |23056384 |12279808 |38129664
**CPU Texture Count**: |228 |148 |322
**GPU Texture Count**: |1153 |992 |1106
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |271277020 |138992832 |329097528
**GPU Texture Memory Usage**: |526445098 |320695290 |1031056383
**GPU Virtual Memory Usage**: |697476266|491726458|1202087551
**Triangle Count**: |526971 |259614 |240970
**Triangle Rate**: |32935687 |21634500 |15060625
**API Drawcall Count**: |239 |138 |155
**Drawcall Count**: |240 |150 |1061
**Drawcall Rate**: |15000 |12500 |66312
**State Changes Texture Count**:|237 |121 |195
**Pipeline Count**: |40 |37 |42
**Item Opaques**: |280 |289 |169
**Item Translucents**: |15 |30 |26
**Item Lights**: |19 |43 |9
**Timing Opaques**: |667 |829 |930
**Timing Translucents**: |23 |74 |142
**Timing Lighting**: |45 |123 |135
**Render Frame**: |1152 |2050 |2245

**Comment by SkimiMission** [comment]
## QA Test
**QA Tester**: Skimi
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |59 |59 |60
**CPU Buffer Count**: |5403 |2820 |3756
**GPU Buffer Count**: |1033 |710 |850
**CPU Memory Usage**: |85393408 |43970560 |70008832
**GPU Memory Usage**: |36974592 |27742208 |41771008
**CPU Texture Count**: |415 |289 |323
**GPU Texture Count**: |1450 |1446 |1241
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |282144060 |185741504 |302492936
**GPU Texture Memory Usage**: |1198609611 |797740577 |953271109
**GPU Virtual Memory Usage**: |1523503389|1122634355|1240694839
**Triangle Count**: |574166 |177831 |829280
**Triangle Rate**: |35885375 |11114437 |51830000
**API Drawcall Count**: |296 |87 |298
**Drawcall Count**: |429 |87 |1246
**Drawcall Rate**: |26812 |5437 |77875
**State Changes Texture Count**:|275 |97 |381
**Pipeline Count**: |52 |37 |60
**Item Opaques**: |335 |150 |321
**Item Translucents**: |49 |13 |59
**Item Lights**: |20 |22 |31
**Timing Opaques**: |994 |445 |1082
**Timing Translucents**: |55 |33 |117
**Timing Lighting**: |111 |102 |63
**Render Frame**: |1859 |1299 |1973

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok in Desktop mode. In HMD (vive, gtx 970) localhost ~50fps, dev-playa max. ~30fps, dev-demo max. ~30fps.
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Ok
**Test 4**|undefined|--
**Test 5**|Retest the kick function|
**Test 6**|Switch avatar and make sure it does not crash|Ok
**Test 7**|Test group functions|Ok
**Test 8**|Retest the kick function|Works on Web interface of domain server, it changed the icon in interface. Unfortunately no one online to kick.
**Test 9**|Enrure that you can distance grab|Ok

**Comment by nbq** [comment]
testing now

**Comment by cozza13** [comment]
I can not see "Show Advanced" button in the Domain settings section 

capture

**Pull request closed without merging**
