### PR TITLE
Fixing the broken "on hud" overlay's render transform

### PR DESCRIPTION
**Pull request by samcake**
Turns out that the on hud ovelrlays (the overlays used to be rendered over the HUD) are not added to the scene. So their render transform was never assigned correctly (because it relied on them beeing in the scene).
The fix is that if an overlay is not in the scene (doesn't have a renderItemID), the renderTransform is updated directly in the Update call instead of pushing  a transaction to the scene.

## TEST PLAN
In the Audio app, enable "Show audio level meter"
then in HMD, try to hover the hand laser on the widget (top left corner.

In this pr, the laser shows up correctly over the widget.
IN master, no thing shows, no laser representation at all.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3698/HighFidelity-Beta-PR11477-3bd6e35e301c828b464d571a4f576da699546395.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3698/HighFidelity-Beta-PR11477-3bd6e35e301c828b464d571a4f576da699546395.exe

**Comment by anshuman64** [comment]
build this please

**Comment by samcake** [comment]
build this please

**Comment by anshuman64** [comment]
build this please

**Comment by anshuman64** [comment]
build this please

**Comment by samcake** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by samcake** [comment]
build this please

**Comment by Nex-Pro** [comment]
Testing windows build when available.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3715/HighFidelity-Beta-PR11477-29da0c663f6d315d84a37c7a00bca87cff10713e.dmg

**Comment by Nex-Pro** [comment]
Tick Tock

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3715/HighFidelity-Beta-PR11477-29da0c663f6d315d84a37c7a00bca87cff10713e.exe

**Comment by Nex-Pro** [comment]
T E S T I N G this now

**Comment by Nex-Pro** [comment]
This works partially. (probably enough to satisfy the requirement of this PR)

But if the laser is moved across the audio meter widget from outside of it it will never act like it intersected.
The user has to move the laser to the widget then release and pull the trigger again. This seems incorrect.
Shouldn't we expect the laser to intersect the surface of the widget after a moment or two ? I just see the laser pass right through until I re-trigger the laser.

**Comment by samcake** [comment]
Thanks Piper, I think the problem you describe was there regardless, (probably in current RC)
Am I correct ?

**Comment by sethalves** [comment]
Yeah, we know about how the laser wont intersect with the HUD windows unless you're pointing at the window before you pull the trigger.  That will be fixed in some other PR.

**Pull request merged**
