### PR TITLE
Fix aspect ratio of splash logo in win32 launcher

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20116/HighFidelity-Beta-PR15833-2824d6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20116/HighFidelity-Beta-Interface-PR15833-2824d6f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20116/HighFidelity-Beta-PR15833-2824d6f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20116/HighFidelity-Quest-Beta-PR15833-2824d6f.apk)

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20128/HighFidelity-Beta-PR15833-2824d6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20128/HighFidelity-Beta-Interface-PR15833-2824d6f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20128/HighFidelity-Beta-PR15833-2824d6f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20128/HighFidelity-Quest-Beta-PR15833-2824d6f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20128/HighFidelity-Beta-PR15833-2824d6f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20128/HighFidelity-Beta-Interface-PR15833-2824d6f.exe

**Pull request merged**
