### PR TITLE
Case 22012: Morph Targets for glTF Avatars

### PR DESCRIPTION
**Pull request by raveenajain**
https://highfidelity.manuscript.com/f/cases/22012/adding-glTF-Morph-Targets

### CODE REVIEW

**Comment by raveenajain** [comment]
Test Plan: 

1. Open Interface -> Avatar Tool
2. Update your avatar by linking to the FST (included in zip) 
3. Run blendshape script
    - Edit -> Running Scripts -> From URL -> https://gist.githubusercontent.com/hyperlogic/a677c6d81eb0c25f40bf231827b615e3/raw/7ef2d4f8135f93747b60628b4e41c7f6a51e8abd/blendshapetest.js
4. Toggle the sliders for each blendshape 
    - the name on the slider will correspond with the part of the face that should be moving 
    - some of the sliders _will not_ trigger any movement; if the FST file does not contain the name of that blendshape, then it will not move (for example, CheekSquint_L exists on the script, but not within the FST file; therefore, it should not do anything).

[gltfAvatar.zip](https://github.com/highfidelity/hifi/files/3119244/gltfAvatar.zip)

*Note: This avatar is not textured and her legs are off; this is due to the export from Blender.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19014/HighFidelity-Beta-PR15468-66ad645.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19014/HighFidelity-Quest-Beta-PR15468-66ad645.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19014/HighFidelity-Beta-PR15468-66ad645.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19014/HighFidelity-Beta-Interface-PR15468-66ad645.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19017/HighFidelity-Beta-PR15468-0be3678.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19017/HighFidelity-Quest-Beta-PR15468-0be3678.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19017/HighFidelity-Beta-PR15468-0be3678.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19017/HighFidelity-Beta-Interface-PR15468-0be3678.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19017/HighFidelity-Beta-PR15468-0be3678.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19017/HighFidelity-Beta-Interface-PR15468-0be3678.exe

**Pull request merged**
