### PR TITLE
Fixed QML errors from issue 10151

### PR DESCRIPTION
**Pull request by vladest**
Test plan:
-Run app
- make sure no QML errors

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7205efea474c96b5db5cc2d78773c98a0347c145 available at: https://gist.github.com/7bde70202e0ef017e3734e9a995bb7d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-7205efe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-7205efe.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9778a822f4683b7f98f123801f05669570714f6 available at: https://gist.github.com/7bde70202e0ef017e3734e9a995bb7d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-d9778a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-d9778a8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e1df994dcf45a5edcf7697aebff153e10afae7b available at: https://gist.github.com/7bde70202e0ef017e3734e9a995bb7d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-6e1df99.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-6e1df99.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ec40ab96d01141116a32719d9bb00504be9edf9 available at: https://gist.github.com/7bde70202e0ef017e3734e9a995bb7d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-0ec40ab.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10228-0ec40ab.dmg

**Comment by Nex-Pro** [comment]
@cozza13 Can we get some more detail on the test plan for this. Cheers.

**Comment by vladest** [comment]
@Nex-Pro the goal for the task - eliminate QML errors and warnings

**Comment by Nex-Pro** [comment]
repeats question.

**Comment by cozza13** [comment]
@Nex-Pro Open Interface and load up the Tablet and run through the dialogs. Looks at the logs for errors related to QML. 
- Switch to desktop mode and run through the dialogs. Note any QML related errors that show up in the logs.

**Comment by Nex-Pro** [comment]
@cozza13  Thanks.

**Comment by Nex-Pro** [comment]
Found a few ( what I think ) errors after trawling though as many qml dialogs as I could find.

There's a summary of them at the bottom. Let me know if you need the logs.


errors found:

[05/11 12:01:40] [DEBUG] [qml] No callback for message fromScript {"method":"palIsStale","params":["{a7be8a96-dc56-4bdd-a0db-4623d8b0ca43}","avatarAdded"]}

[05/11 12:01:40] [DEBUG] [qml] No callback for message fromScript {"method":"palIsStale","params":[null,"avatarSessionChanged"]}

[05/11 12:01:40] [DEBUG] [qml] No callback for message fromScript {"method":"clearLocalQMLData"}





 1893: [05/11 12:26:36] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function

 1896: [05/11 12:26:37] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function 

 1898: [05/11 12:26:38] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function

  1900: [05/11 12:26:39] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function


   2377: [05/11 12:36:24] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function
 2378: [05/11 12:36:29] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined
 2379: [05/11 12:36:29] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined
 2380: [05/11 12:36:29] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined
 2381: [05/11 12:36:29] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined
 2382: [05/11 12:36:30] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined
 2383: [05/11 12:36:30] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/html/js/list.min.js 1 Uncaught TypeError: Cannot read property 'values' of undefined

   259: [05/11 12:41:26] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function
  260: [05/11 12:41:26] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function
  261: [05/11 12:41:26] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function
  262: [05/11 12:41:27] [DEBUG] [qml] Web Entity JS message: qrc:///qtwebchannel/qwebchannel.js 131 Uncaught TypeError: channel.execCallbacks[message.id] is not a function

  692: [05/11 13:25:34] [DEBUG] [qml] Web Entity JS message: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&ref_src=twsrc%5Etfw&text=Explore%20blue%20in%20High%20Fidelity&tw_p=tweetbutton&url=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&via=highfidelityinc 7 The value "device-width;" for key "width" is invalid, and has been ignored.
  693: [05/11 13:25:34] [DEBUG] [qml] Web Entity JS message: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&ref_src=twsrc%5Etfw&text=Explore%20blue%20in%20High%20Fidelity&tw_p=tweetbutton&url=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&via=highfidelityinc 7 The value "1.0;" for key "initial-scale" was truncated to its numeric prefix.
  694: [05/11 13:25:34] [DEBUG] [qml] Web Entity JS message: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&ref_src=twsrc%5Etfw&text=Explore%20blue%20in%20High%20Fidelity&tw_p=tweetbutton&url=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&via=highfidelityinc 7 The value "1.0;" for key "maximum-scale" was truncated to its numeric prefix.
  695: [05/11 13:25:34] [DEBUG] [qml] Web Entity JS message: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&ref_src=twsrc%5Etfw&text=Explore%20blue%20in%20High%20Fidelity&tw_p=tweetbutton&url=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&via=highfidelityinc 7 Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
  696: [05/11 13:25:35] [DEBUG] [qml] Web Entity JS message: https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&ref_src=twsrc%5Etfw&text=Explore%20blue%20in%20High%20Fidelity&tw_p=tweetbutton&url=https%3A%2F%2Fmetaverse.highfidelity.com%2Fplaces%2Fblue&via=highfidelityinc 0 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://connect.facebook.net https://cm.g.doubleclick.net https://ssl.google-analytics.com https://graph.facebook.com https://twitter.com 'unsafe-eval' https://*.twimg.com https://api.twitter.com 'nonce-EoX2Sfvz6aGJT06n3/J1Lg==' https://analytics.twitter.com https://publish.twitter.com https://ton.twitter.com https://syndication.twitter.com https://www.google.com https://t.tellapart.com https://platform.twitter.com https://www.google-analytics.com 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-P6-Rno4Rt5NcfQEMdBIhra0447nNH8z8GA5UZ3DBE60='), or a nonce ('nonce-...') is required to enable inline execution.

Note the line below. It has no message content!

697: [05/11 13:25:35] [DEBUG] [qml] 

  698: [05/11 13:26:22] [DEBUG] [qml] Web Entity JS message: https://connect.facebook.net/en_US/fbevents.js 4 Facebook Pixel Error: Duplicate Pixel ID: 1132013920192757

  533  [05/11 15:18:32] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:51: TypeError: Cannot read property 'enabled' of null
  534  [05/11 15:18:32] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:50: TypeError: Cannot read property 'enabled' of null
  ...

  586  [05/11 15:21:48] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:51: TypeError: Cannot read property 'enabled' of null
  587  [05/11 15:21:48] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:50: TypeError: Cannot read property 'enabled' of null
  ...
  606  [05/11 15:21:48] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:64: TypeError: Cannot read property 'pressed' of null
  607  [05/11 15:21:48] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:44:41: Unable to assign ComboBox_QMLTYPE_140 to ComboBox_QMLTYPE_447
  608: [05/11 15:22:07] [DEBUG] [qml] Triggering Open and Run Script from URL...
  609  [05/11 15:22:07] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:51: TypeError: Cannot read property 'enabled' of null
  610  [05/11 15:22:07] [WARNING] [default] qrc:/QtQuick/Controls/Styles/Desktop/ComboBoxStyle.qml:50: TypeError: Cannot read property 'enabled' of null
  ...

  849: [05/11 15:37:53] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/particle_explorer/particleExplorer.js 397 Uncaught TypeError: Cannot set property 'closed' of null
  850: [05/11 15:37:53] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/particle_explorer/particleExplorer.js 397 Uncaught TypeError: Cannot set property 'closed' of null
  851: [05/11 15:37:54] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/particle_explorer/particleExplorer.js 397 Uncaught TypeError: Cannot set property 'closed' of null
  852: [05/11 15:38:59] [DEBUG] [qml] Web Entity JS message: file:///E:/Program%20Files/High%20Fidelity%20-%20PR10228/scripts/system/particle_explorer/particleExplorer.js 397 Uncaught TypeError: Cannot set property 'closed' of null

Hope this helps.

**Comment by vladest** [comment]
@Nex-Pro thanks, I'll go thru the list.

**Comment by ZappoMan** [comment]
status on this PR?

**Comment by vladest** [comment]
@ZappoMan in progress.

**Pull request closed without merging**
