### PR TITLE
possible fix for tablet freezing

### PR DESCRIPTION
**Pull request by sethalves**
- try harder to keep setTimeout loop going in controller-dispatcher

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/10479/controllerModules-not-updating-since-setTimeout-change

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5598/HighFidelity-Beta-PR11971-3a00d31c15c78f7b0d7e6fe74782573bb862a608.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5598/HighFidelity-Beta-PR11971-3a00d31c15c78f7b0d7e6fe74782573bb862a608.dmg

**Comment by sethalves** [comment]
to test:
- with hmd and hand-controllers, use the tablet
- especially right after logging in or changing domains, make sure the tablet continues to work

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
with hmd and hand-controllers, use the tablet | Pass
especially right after logging in or changing domains, make sure the tablet continues to work | Pass

Tried with a few domains - tablet still working as expected.

**Pull request merged**
