### PR TITLE
CR for Job #20276 - Add Scripting Support for changes in Audio Devices

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Code Review for Job #20276 - Workitem available at https://www.worklist.net/20276

### CODE REVIEW

**Comment by ZappoMan** [comment]
@ctrlaltdavid - looks like you need to merge with upstream on this branch. But I'll start code review now.

**Comment by ZappoMan** [comment]
Looks good once merge conflict is resolved.

**Comment by ctrlaltdavid** [comment]
@ZappoMan Merged.

**Comment by ZappoMan** [comment]
@ctrlaltdavid - David, I think another emergency PR got merged before yours because it's still showing as not being auto-mergable. Can you give it another go?

**Comment by ctrlaltdavid** [comment]
@ZappoMan This time, fingers crossed!

**Pull request merged**
