### PR TITLE
Remove oglplus usage in Offscreen QML rendering

### PR DESCRIPTION
**Pull request by jherico**
The OGLPlus functionality of calling `glGetError()` after every function is impacting performance.

## Testing

This should not impact application functionality at all.  It may have a minor performance improvment on i5 systems

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 753322677b3cfccf673a495db0bb9a9ac9724985 available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-7533226.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-7533226.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4251276fcc98cd7e65035521f864a77913ba8b1 available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-b425127.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-b425127.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4251276fcc98cd7e65035521f864a77913ba8b1 available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-b425127.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-b425127.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f013e65cac5532b17096d4d4a6e34901464b7a8b available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-f013e65.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-f013e65.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f013e65cac5532b17096d4d4a6e34901464b7a8b available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-f013e65.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-f013e65.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 933388bc61c136312f4bd31fa655b0813fc5361b available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-933388b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-933388b.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 933388bc61c136312f4bd31fa655b0813fc5361b available at: https://gist.github.com/6957a40103e0ebb6e26cbe02109cae63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-933388b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8669-933388b.dmg

**Comment by ZappoMan** [comment]
Tested:
- Windows 8.1 - i7/980xt 
    - Desktop - Pass
    - CV1 - Pass
    - Vive - Pass
- Windows 10 - i5/970
    - Desktop - Pass
    - CV1 - Pass
    - Vive - Pass

**Pull request merged**
