### PR TITLE
Case21707 - Wallet doesn't work if user has unicode characters in windows username

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.manuscript.com/f/cases/21707/User-has-blank-Inventory-page-and-HFC-Balance-shows-two-dashes

https://highfidelity.manuscript.com/f/cases/22046/Feature-request-Warn-upon-install-update-if-user-has-special-character-in-installation-path

https://highfidelity.manuscript.com/f/cases/22023/New-user-being-asked-for-wallet-passphrase

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18712/HighFidelity-Beta-PR15384-3bf8fb5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18712/HighFidelity-Quest-Beta-PR15384-3bf8fb5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18712/HighFidelity-Beta-PR15384-3bf8fb5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18712/HighFidelity-Beta-Interface-PR15384-3bf8fb5.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18719/HighFidelity-Beta-PR15384-e36a8fc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18719/HighFidelity-Quest-Beta-PR15384-e36a8fc.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18719/HighFidelity-Beta-PR15384-e36a8fc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18719/HighFidelity-Beta-Interface-PR15384-e36a8fc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18719/HighFidelity-Beta-PR15384-e36a8fc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18719/HighFidelity-Beta-Interface-PR15384-e36a8fc.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18721/HighFidelity-Beta-PR15384-8f9d837.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18721/HighFidelity-Quest-Beta-PR15384-8f9d837.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18721/HighFidelity-Beta-PR15384-8f9d837.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18721/HighFidelity-Beta-Interface-PR15384-8f9d837.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18728/HighFidelity-Beta-PR15384-3949ca2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18728/HighFidelity-Quest-Beta-PR15384-3949ca2.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18728/HighFidelity-Beta-PR15384-3949ca2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18728/HighFidelity-Beta-Interface-PR15384-3949ca2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18728/HighFidelity-Beta-PR15384-3949ca2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18728/HighFidelity-Beta-Interface-PR15384-3949ca2.exe

**Comment by howard-stearns** [comment]
[what about special characters?](https://trello.com/c/37RTIsfd/50-what-about-special-characters)

**Pull request merged**
