### PR TITLE
preserve audio data during pal refresh

### PR DESCRIPTION
**Pull request by howard-stearns**
fix https://highfidelity.fogbugz.com/f/cases/3376/pal-refresh-doesn-t-preserve-volume-sort

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan, with two avatars:
- open pal with one avatar and make noise with the other.
- sort by loudness and make sure the value is right.
- refresh, and make sure it's still right.

In master, refresh was doing the sort based on no data being carried over, so all loudnesses were zero.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15d680d4f9fd1ed08ccddd7396ad4a18051fe5b1 available at: https://gist.github.com/e4fb9167e27058e8042208c0cafe31dd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9806-15d680d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9806-15d680d.dmg

**Comment by nbq** [comment]
Testing

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Went to Welcome where other avatars are talking
* Opened PAL and watched other people talk
* Sorted by loudness and made sure the value was right
* Refreshed and made sure on refresh it put the loudest person as the first on the list

**QA PASS**

**Pull request merged**
