### PR TITLE
Fix text sizing per text3d overlay lineHeight property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Makes text size correct for multiple lines of text.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Run the attached script. 
- It draws one 2D and two 3D text overlays. 
- The text should fit vertically snugly within the overlay backgrounds. (You can compare the script running on latest master: the 3D text vertically overflows the background.)
- The 3D text size corresponds to the size of the overlay. (See the comments in the script.)

2) The text in text3d overlays is rendered slightly smaller with this PR but the sizes calculated using Overlays.textSize() are correct. So scripts that user text3d overlays without using Overlays.textSize() should display text strings within their allotted spaces OK (just smaller) and scripts that user Overlays.textSize() should size the text and backgrounds etc. correctly. Most or all of the following scripts should be tested to check that the text3d overlays display OK.

System scripts that use text3d overlays:
- \scripts\developer\debugging\actionInspector.js
- \scripts\developer\debugging\debugAvatarMixer.js
- \scripts\developer\debugging\grabInspector.js
- \scripts\developer\EZrecord.js
- \scripts\system\libraries\entitySelectionTool.js (Displays the degrees of rotation when you're rotating an entity using the Create app.)
- \scripts\system\chat.js (Display text at the avatar of the user that typed something in chat.)
- \scripts\system\notifications.js (Display the "toast" notifications with "x" button, such as for LOD changes.)
- \scripts\tutorials\entity_scripts\sit.js (Displays the "Click to sit" text.)
Test at least the last four, non-developer scripts.

Marketplace scripts that use text3d overlays:
- Avatar Recording and Playback (Displays the red "REC" text when a recording is being made.)
- Nametags x 2 scripts (Displays nametags above each avatar.)
- Green chair (Possibly displays text, somewhere.)

Other scripts that use text3d overlays:
- \DomainContent\Start\support.js (Displays a speech bubble, somewhere, in some domain content.)

[lineHeights.zip](https://github.com/highfidelity/hifi/files/1870371/lineHeights.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8439/HighFidelity-Beta-PR12765-ab55f2097670119bfb624a7463df072ee19f2747.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8439/HighFidelity-Beta-PR12765-ab55f2097670119bfb624a7463df072ee19f2747.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Text appears and is sized correctly in 3d and 2d dialogs, scripts and marketplace items in test plan were used.

**Pull request merged**
