### PR TITLE
fix the messages printed by domain-server about which name it's using to find ice-servers

### PR DESCRIPTION
**Pull request by sethalves**
- fix the messages printed by domain-server about which name it's using to find ice-servers

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run domain-server with -i flag and specify a non-default ice-server
- look at the log messages printed and see that they reflect what was given to -i
- run domain-server with no -i flag, make sure it still connects to the expected ice-server

**Comment by CainFoool** [comment]
Testing when ready.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1025/HighFidelity-Beta-PR10789-f1c7d54010b311d0661199507e1b91e7dd30a8f4.exe

**Comment by CainFoool** [comment]
Test | Result
-------- | --------
run domain-server with -i flag and specify a non-default ice-server | Pass
look at the log messages printed and see that they reflect what was given to -i | Pass
run domain-server with no -i flag, make sure it still connects to the expected ice-server | Pass

Let me know if there's anything else to do!
###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by acloudiator** [comment]
Hi Folks,

A question about the Test, 
"look at the log messages printed and see that they reflect what was given to -i" [https://github.com/highfidelity/hifi/pull/10789#issuecomment-310507962](url)

- Was this ice-server running on same or different node?

**Comment by sethalves** [comment]
I'm not sure I understand the question.

I believe that domain-server was correctly interpreting the -i flag, but the messages it was printing were not reflecting that.  If there's [other] evidence that it's not obeying the -i flag, we should look into it.

**Pull request merged**
