### PR TITLE
Beta Release 64 - includes up to Developer Release 7818

### PR DESCRIPTION
**Pull request by conklin94122**
**New Features**

- Avatar entity wearables will now be saved as part of the avatar bookmarks
- Avatar entity wearables will now not obstruct the user's view
- The enter key now closes the go-to menu as well as opening it up
- Normal map support on translucent objects
- Additional "pitch" property to allow pitch shifting an audio effect
- Allow model entity joints to be changed from scripts
- A redesign of the Inspection Certificates for clarity and visual appeal. Also adds "Purchase Price" to the cert
- When you pay someone nearby there is a particle effect that goes from you to the person you paid

**Various Bug Fixes** 

- Fix for certain avatars seeing their own eyeballs when moving
- Fixed a Parenting loop crash
- Fixed an issue where an empty tablet would show up during checkout in avatar island
- Fixed an issue where downloaded tablet apps get sorted above the default app
- Fixed issue where if an entity has child entities it could not be deleted in the Create menu
- Fixed issue where multiple tablet buttons became highlighted when tablet page scrolled

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7020/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7020/HighFidelity-Beta-PR12361-40851b097fe8a54771eee9749dba41d8f5bb7746.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7020/HighFidelity-Beta-PR12361-40851b097fe8a54771eee9749dba41d8f5bb7746.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7045/app_12361_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7048/app_12361_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7063/app_12361_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7071/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7071/HighFidelity-Beta-PR12361-ba92191fbbdbd47ac4367ed3e1229227089cb33b.dmg

**Comment by RyanDowne** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7076/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7076/HighFidelity-Beta-PR12361-ba92191fbbdbd47ac4367ed3e1229227089cb33b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7076/HighFidelity-Beta-PR12361-ba92191fbbdbd47ac4367ed3e1229227089cb33b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7081/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7081/HighFidelity-Beta-PR12361-199321a5f27facec2e196b8d1ef2190e2de06cb9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7081/HighFidelity-Beta-PR12361-199321a5f27facec2e196b8d1ef2190e2de06cb9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7100/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7100/HighFidelity-Beta-PR12361-858e3e987cf7da818d594ac29b8fd0f241d3952f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7100/HighFidelity-Beta-PR12361-858e3e987cf7da818d594ac29b8fd0f241d3952f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7102/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7102/HighFidelity-Beta-PR12361-5b63c0523d8bcb80af5a93cb789b04baf05d9432.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7102/HighFidelity-Beta-PR12361-5b63c0523d8bcb80af5a93cb789b04baf05d9432.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7119/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7119/HighFidelity-Beta-PR12361-5a59e0409627a1fb5f4163dd39d5d3ffda9c4312.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7121/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7121/HighFidelity-Beta-PR12361-5a59e0409627a1fb5f4163dd39d5d3ffda9c4312.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7121/HighFidelity-Beta-PR12361-5a59e0409627a1fb5f4163dd39d5d3ffda9c4312.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7217/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7217/HighFidelity-Beta-PR12361-db399a47eb8b480d05e356404fce61162656c5c1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7217/HighFidelity-Beta-PR12361-db399a47eb8b480d05e356404fce61162656c5c1.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7267/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7268/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7267/HighFidelity-Beta-PR12361-bc8ea1be1767aa58e6f4553dd6079040d39cbfdf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7268/HighFidelity-Beta-PR12361-a621cb3c2caa026b583398a399f198abe08b3f8b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7267/HighFidelity-Beta-PR12361-bc8ea1be1767aa58e6f4553dd6079040d39cbfdf.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7268/HighFidelity-Beta-PR12361-a621cb3c2caa026b583398a399f198abe08b3f8b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7414/app_12361_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7414/HighFidelity-Beta-PR12361-e1ed0977e8accd545405191764ad4179db550215.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7414/HighFidelity-Beta-PR12361-e1ed0977e8accd545405191764ad4179db550215.exe

**Pull request merged**
