### PR TITLE
Fix default avatar feet

### PR DESCRIPTION
**Pull request by dback2**
Fixes default avatar's feet being angled slightly upward.

Fixes https://highfidelity.fogbugz.com/f/cases/13914/Woody-Avatar-Rigging-Issue-Toes-Angle-Upward-Slightly

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10384/HighFidelity-Beta-PR13315-c294dd4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10384/HighFidelity-Beta-PR13315-c294dd4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10384/HighFidelity-Beta-Interface-PR13315-c294dd4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10384/HighFidelity-Beta-PR13315-c294dd4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10384/HighFidelity-Beta-Interface-PR13315-c294dd4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10397/HighFidelity-Beta-PR13315-a246c9f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10397/HighFidelity-Beta-PR13315-a246c9f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10397/HighFidelity-Beta-Interface-PR13315-a246c9f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10397/HighFidelity-Beta-PR13315-a246c9f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10397/HighFidelity-Beta-Interface-PR13315-a246c9f.exe

**Comment by hyperlogic** [comment]
QA Testplan:
  * In Settings > Avatar, change the Avatar URL to be blank.
  * You should see the default woody mannequin avatar.
  * Other users in the domain with you should also see the default woody mannequin avatar.
  * When compared to the master branch, The feet on the new mannequin avatar feet should not be upturned and should appear flat on the ground.

**Comment by qligmaloney** [comment]
Currently testing

**Comment by QliCknox** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Avatars feet are no longer angled upward. No other defective behavior introduced

**Pull request merged**
