### PR TITLE
Fix entities not loading when Interface doesn't have focus

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Reverts https://github.com/highfidelity/hifi/pull/14286

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15061/HighFidelity-Beta-PR14386-e12833d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15061/HighFidelity-Beta-PR14386-e12833d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15061/HighFidelity-Beta-Interface-PR14386-e12833d.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15061/HighFidelity-Beta-Interface-PR14386-e12833d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by ctrlaltdavid** [comment]
Test plan fixed: don't minimize Interface - keep it running in a window but without focus in the second test. (This is part of the automated testing process.)

**Comment by qlistephens95** [comment]
PASS @conklin94122. The two folders of snapshots contain identical sets of images. Entities are not missing in the second set of images.

**Pull request merged**
