### PR TITLE
Fix loading of incorrect joint data for the avatar recording

### PR DESCRIPTION
**Pull request by druiz17**
Fix the issue of the avatar recording writing the wrong joint data.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- With the avatar recording app make a simple recording of you slightly leaning side to side (make sure your avatar does not move)
- when playing the recording your feet should not slide.
- If you happen to have old recordings that have feet sliding, test those as well

**Comment by Nex-Pro** [comment]
Testing this with Vive.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1152/HighFidelity-Beta-PR10838-96ae39989eec76903a7f8d57d176c1717288f19a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1152/HighFidelity-Beta-PR10838-96ae39989eec76903a7f8d57d176c1717288f19a.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
Tested with win10 and Vive.

Crashed on first attempt to record.
I've added the playback AC link and set 2 instances then restarted domain(localhost).
When I try to use the record app I see that there are no instances available.

This is due to:

[06/28 18:09:20] [WARNING] [default] [66004] [agent] Failed to download script at "https://content.highfidelity.com/Scripts/playRecordingAC.jshttps://content.highfidelity.com/Scripts/playRecordingAC.js%09"  - bailing on assignment.

Is there another link ?

**Comment by druiz17** [comment]
@Nex-Pro I think you added a space or tab when you entered the url. Hence the %09 at the end of url in the log. If you remove the space at the end it should work.

**Comment by Nex-Pro** [comment]
@druiz17 nope

**Comment by druiz17** [comment]
@Nex-Pro I look like you copied the url in twice

**Comment by Nex-Pro** [comment]
@druiz17  Weird !

**Comment by Nex-Pro** [comment]
@druiz17 I need to wear my glasses when I'm using 4k monitor !  lol.

### PASS

Shuffling is now gone.

**Comment by anshuman64** [comment]
I want to QA this as well while wearing pucks. Will do it tomorrow.

**Comment by anshuman64** [comment]
Good job finding the problem @druiz17 . Works great now :)

**Pull request merged**
