### PR TITLE
Shadow performance / acnee improvements

### PR DESCRIPTION
**Pull request by Zvork**
This PR adds a number of small performance improvements with cascaded shadows. It also adds a number of configuration parameters to further tweak the shadow bias to diminish shadow acnee. A new sloped based bias is added for all shadow cascades which adds a light / surface normal angle dependent bias to a constant bias.

Detailed performance improvements:

- A single octree query, pipeline / depth sort is performed for all cascades
- Small objects are culled away from the shadow cascades based on their relative size as projected on the orthographic shadow frustums.
- Objects from lower cascades are culled away from higher cascades
- Small shadow resolve shader improvements

There should be no visual difference with the current shadow cascade implementation except for small objects being discarded from higher level cascades (farthest cascades from the camera).

# Test cases
This PR should be tested on PC / Mac, various GPUs and HMD with the tests proposed in [hifi_tests PR #38](https://github.com/highfidelity/hifi_tests/pull/38/commits)

Objects that are not invisible in the HMD view should NEVER cast shadows. This can be tested by forcing a really high FPS in the LOD settings, for instance. This will force an agressive distance culling.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6863/app_12323_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6863/HighFidelity-Beta-PR12323-e9747e9d85336baa56c12f664aa0dcda54ee2e6b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6863/HighFidelity-Beta-PR12323-e9747e9d85336baa56c12f664aa0dcda54ee2e6b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6868/app_12323_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6868/HighFidelity-Beta-PR12323-8a011036ef4f9be5b5412936a3f0cfe6a0de208b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6868/HighFidelity-Beta-PR12323-8a011036ef4f9be5b5412936a3f0cfe6a0de208b.exe

**Comment by ZappoMan** [comment]
@Zvork - there are merge conflicts... please repair.

**Comment by Zvork** [comment]
@ZappoMan working on it...

**Comment by Zvork** [comment]
@ZappoMan Done.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6940/app_12323_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6940/HighFidelity-Beta-PR12323-179aca2bf99f24340c60ef98a52cdc832f3e8091.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6940/HighFidelity-Beta-PR12323-179aca2bf99f24340c60ef98a52cdc832f3e8091.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. On 3.4GHz Intel Core i5, Radeon Pro 560 (Mac), when shadows enabled, entire domain renders grey/black and no details can be seen (see screenshot)
hifi-snap-by--on-2018-02-12_10-04-26
On i5-AMD r9 280 (Windows), shadows are showing various pixilation (see screenshots)
pr12323windesktopscreen3
pr12323windesktopscreen2
pr12323windesktopscreen1
On the i7-6700 @ 3.4GHz, NVIDIA GTX 970 (Occulus) (Windows) and Intel (R) Core(TM) i7-7700 CPU…NVIDIA GeForce GTX 1070 (Vive) (Windows), testing functioned as expected.

@conklin94122

**Comment by samcake** [comment]
Arg
it s a problem accross all amd apparently
sigh
thanks

**Comment by conklin94122** [comment]
Erin, please retest to repro and confirm what Sam said, that this occurs in master as well.

**Comment by Qliemillar** [comment]
@conklin94122 Retested on Master, can confirm what @samcake found, pixelation is also present on Master.

**Comment by conklin94122** [comment]
Given Sam's comments, passed.

**Pull request merged**
