### PR TITLE
Fix tutorial showing multiple instructions and update content set

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3d12c00f53dd6b28823ead576b450bb76c5493d available at: https://gist.github.com/66976fffad7a3897839af4a446c15757<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9814-f3d12c0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9814-f3d12c0.dmg

**Comment by huffman** [comment]
To test:

 1. Make sure you can run through the tutorial successfully
 2. If you go to `localhost` or "go home" it should take you to the builder area on your home domain
 3. If you go through the portal in the builder area it should take you to the garden area, not inside the tutorial room

**Comment by Nex-Pro** [comment]
testing this as requested.

**Comment by Nex-Pro** [comment]
### FAIL

Make sure you can run through the tutorial successfully: **FAIL**
I see only static controllers at the start of the tutorial.  None at my hand locations.
I tried several times but to no avail.
I then shut-down interface and domain server.  Deleted Interface.json both in this PR and in the regular build.  Did not fix the problem.

If you go to localhost or "go home" it should take you to the builder area on your home domain: **SUCCESS**
If you go through the portal in the builder area it should take you to the garden area, not inside the tutorial room: **SUCCESS**

**Comment by Nex-Pro** [comment]
@huffman ^ any suggestions ?

**Comment by huffman** [comment]
@Nex-Pro Could you try rerunning this once it builds? The same bug existed in https://github.com/highfidelity/hifi/pull/9801 which has now been fixed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fe52a44d012a91df37a09805c01d3a64d93e3cff available at: https://gist.github.com/66976fffad7a3897839af4a446c15757<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9814-fe52a44.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9814-fe52a44.dmg

**Comment by Nex-Pro** [comment]
@huffman  Ok doing it now... is the bug in the client or sandbox ?

**Comment by huffman** [comment]
@Nex-Pro The problem is in the client. Thanks!

**Comment by Nex-Pro** [comment]
@huffman  Np I nuked the previous installation to make sure there's no contamination of settings.

**Comment by Nex-Pro** [comment]
@huffman On first run I was at dev-welcome.  My tablet displayed the private notice.
I went to my sandbox and used the Teleporter to get to the garden.
Used the start tutorial TP to go to the tutorial.  I had controllers but no lasers.
Restarted Interface.  Tutorial worked. Ran thru it four times all good.  
Still tablet shows private screen.

**Comment by Nex-Pro** [comment]
@huffman  had to press enter in HMD mode to get the goto dialog ^

**Comment by huffman** [comment]
@Nex-Pro Did it take you directly to the tutorial the second time you launched interface?

**Comment by Nex-Pro** [comment]
@huffman No

**Comment by huffman** [comment]
@Nex-Pro Had you blown away your interface.json? Were you expecting it to automatically take you to the tutorial?

**Comment by Nex-Pro** [comment]
I had deleted the folders in app data local and roaming after uninstalling

**Comment by Nex-Pro** [comment]
for this PR

**Comment by Nex-Pro** [comment]
also selected not to copy settings  during install

**Comment by Nex-Pro** [comment]
Do you want me to wipe this build again  and dleted interface.json from my regular client ?

**Comment by huffman** [comment]
@Nex-Pro So you had launched interface after having cleared AppData/Roaming/High Fidelity -PR9814, it took you to dev-welcome. Then you went to the tutorial manually - did you finish it?

**Comment by Nex-Pro** [comment]
As I said  completed it 4 times

**Comment by huffman** [comment]
@Nex-Pro I thought that was after you had restarted it?

**Comment by Nex-Pro** [comment]
yes 4 times AFTER restarting as I had no lasers

**Comment by huffman** [comment]
@Nex-Pro Got it, missed that detail, my mistake, thanks. Can you delete your `~/AppData/Roaming/High Fidelity - PR9814/interface.json` file and try running through it again? I am concerned that it isn't sending you to the tutorial.

**Comment by Nex-Pro** [comment]
Ok

**Pull request closed without merging**
