### PR TITLE
Add asset server bandwidth to stats

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6620f128bfdafc1f10ec5a0730ecfee727efd46 available at: https://gist.github.com/2fc265f607f547e86b5aedd09dd6bd41<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-b6620f1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-b6620f1.dmg

**Comment by huffman** [comment]
I'll throw more information on why this is DNM shortly...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 473a7e95934e6e13cddce46ba99d9348aef86407 available at: https://gist.github.com/2fc265f607f547e86b5aedd09dd6bd41<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-473a7e9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-473a7e9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5e2913eb90bea2b1ee36bbb67dc7f94ad0b02b1 available at: https://gist.github.com/2fc265f607f547e86b5aedd09dd6bd41<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-b5e2913.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8413-b5e2913.dmg

**Pull request merged**
