### PR TITLE
DO NOT MERGE - This is just a test

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 277d9142fd566bb4bcaa52f7862c974de77c397a available at: https://gist.github.com/acd8afaf560d75354b14<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 277d9142fd566bb4bcaa52f7862c974de77c397a available at: https://gist.github.com/acd8afaf560d75354b14<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b28fc43abe4e839aeab2b41aa4f372cf33d62f85 available at: https://gist.github.com/acd8afaf560d75354b14<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4367.dmg

**Pull request closed without merging**
