### PR TITLE
Move controller test to app

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c30771c06badb8a9c1e8cb59e6605090f959de74 available at: https://gist.github.com/7c2667c9eb3a4a36954d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57be59935d79e6594eced9e44320c133f93a967f available at: https://gist.github.com/7c2667c9eb3a4a36954d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57be59935d79e6594eced9e44320c133f93a967f available at: https://gist.github.com/7c2667c9eb3a4a36954d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6107.dmg

**Pull request merged**
