### PR TITLE
Build 49.2 Hotfix: Edit display in HMD white screen fix

### PR DESCRIPTION
**Pull request by cozza13**
Build 49.2 Hotfix: Edit display in HMD white screen fix

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2096/HighFidelity-Beta-PR11078-ce35b83f618c53e74be291d2bdf4b010cbb6d467.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2096/HighFidelity-Beta-PR11078-ce35b83f618c53e74be291d2bdf4b010cbb6d467.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2097/HighFidelity-Beta-PR11078-bf30f81f73044fc4aa5be61ddf5ae94d0d2aec33.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2097/HighFidelity-Beta-PR11078-bf30f81f73044fc4aa5be61ddf5ae94d0d2aec33.exe

**Comment by conklin94122** [comment]
Both fixes are good, very quick test pass ok. Verified.

**Pull request merged**
