### PR TITLE
DEV-2292: Alerting requirements for domain-server failure cases

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Jira: https://highfidelity.atlassian.net/browse/DEV-2292

I've marked the logging messages that indicate critical failures in Lilypad scenarios with the keyword PAGE: and serious failures (that maybe should be on a dashboard) with ALERT:.
Also tweaked a few messages.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21677/HighFidelity-Beta-PR16285-b458098.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21677/HighFidelity-Quest-Beta-PR16285-b458098.apk)

**Comment by SimonWalton-HiFi** [comment]
Certainly would be logical to use critical level, although they may be events that are critical for full networking but not other scenarios.

**Comment by howard-stearns** [comment]
Fair enough. I suppose we could either:
a) note in the logged message that the event may not be critical for manually networked domains (either always or if the domain is set that way).
b) conditionalize the message altogether to not appear in manually networked domains, or to not be critical. (Indeed, why is the operation even being tried in those cases.)
c) just go ahead and be qCCritical and let manual people ignore it, because why not?

Up to you

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21677/HighFidelity-Beta-PR16285-b458098.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21677/HighFidelity-Beta-Interface-PR16285-b458098.exe

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21692/HighFidelity-Beta-PR16285-b458098.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21692/HighFidelity-Beta-Interface-PR16285-b458098.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21692/HighFidelity-Beta-PR16285-b458098.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21692/HighFidelity-Beta-Interface-PR16285-b458098.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21711/HighFidelity-Beta-PR16285-d5d1c08.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21711/HighFidelity-Quest-Beta-PR16285-d5d1c08.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21711/HighFidelity-Beta-PR16285-d5d1c08.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21711/HighFidelity-Beta-Interface-PR16285-d5d1c08.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21711/HighFidelity-Beta-PR16285-d5d1c08.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21711/HighFidelity-Beta-Interface-PR16285-d5d1c08.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21731/HighFidelity-Beta-PR16285-db14cdb.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21731/HighFidelity-Quest-Beta-PR16285-db14cdb.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21731/HighFidelity-Beta-PR16285-db14cdb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21731/HighFidelity-Beta-Interface-PR16285-db14cdb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21731/HighFidelity-Beta-PR16285-db14cdb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21731/HighFidelity-Beta-Interface-PR16285-db14cdb.exe

**Pull request merged**
