### PR TITLE
Update entity server to always make resource directory if it does not…

### PR DESCRIPTION
**Pull request by huffman**
… exist

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a731a571e02809882abe638680d5813c4475b6dc available at: https://gist.github.com/3a1c8c01f4d98b1606c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6947.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6947.dmg

**Comment by huffman** [comment]
How to test on Windows:

Start server console.
Stop the server console.
Ensure that the `~/AppData/High Fidelity - PR6947/assignment-client/entities` directory does not exist. If it does (it will if you downloaded the default content set), delete it.
Start the server console.
Ensure that `~/AppData/High Fidelity - PR6947/assignment-client/entities` exists.

**Comment by nbq** [comment]
Starting testing this one now

**Comment by nbq** [comment]
I have verified that this build of console did auto download content as usual, as part of the test I stopped the hifi server and deleted the entities folder then started the hifi server again and the entities folder is created with blank content. I went into the localhost domain and created something to verify it saved a models.json.gz and it did.

**Comment by huffman** [comment]
@nbq Thanks!

**Pull request merged**
