### PR TITLE
Update Spacemouse plugin + Proposal to main build

### PR DESCRIPTION
**Pull request by FlameSoulis**
This PR updates the 3DSpacemouse plugin that restores functionality to the 3Dconnexion SpaceNavigator 3D mouse. It also adds access to all axis to be accessible, which was per popular request.

The only concern is that this will require our good friend, gustavo, to have an extra build instruction for the Windows builds: specifying where the library is installed.

That in itself is also a bit weird since it's really looking for a specific header (I3dMouseParams.h) which has to be added to the SDK's inc folder and then specify where the SDK inc folder is (with 3DCONNEXIONCLIENT_INCLUDE_DIRS or -D3DCONNEXIONCLIENT_INCLUDE_DIRS in the cmake command).

The SDK also seems to require some developer registration, so I'm not sure what (if any) kind of licensing agreements exist. That can be found here: https://www.3dconnexion.com/service/software-developer.html

Testing will require the SpaceNavigator, but there seems to be an odd quirk with older SpaceNavigators for some weird reason I was never able to determine. However, using a custom controller script (http://voxel.flamesoulis.com/ele/library/spaceNavigator.js) can be used as a workaround and also just controls better. It doesn't seem to play nicely with the default scheme, but that is outside the scope of the PR.

If anything, the PR updates the code so it can be compiled. The most optimal goal is to have it naturally included in the Windows builds (which requires the SDK).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14395/HighFidelity-Beta-PR14272-f1f5f57.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14395/HighFidelity-Beta-PR14272-f1f5f57.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14395/HighFidelity-Beta-Interface-PR14272-f1f5f57.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14395/HighFidelity-Beta-PR14272-f1f5f57.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14395/HighFidelity-Beta-Interface-PR14272-f1f5f57.exe

**Comment by FlameSoulis** [comment]
screenshot 2018-10-26 06 48 40
Please note that the building process for the Space Navigator's plugin is considered optional. This will require more manual testing unless gustavo can be given extra files (the SDK) and told the location of the SDK (with the extra header file included).

**Comment by MarcusLlewellyn** [comment]
The SDK is not necessary to build the Spacemouse plugin. All that the hifi code needs is to have ```3DCONNEXION_INCLUDE_DIRS``` properly defined. That location is currently ```hifi/interface/external/3dconnexionclient/include```

**Comment by FlameSoulis** [comment]
Hmm, if this is true, I'll try to look into CMAKE and figure out what is going on with that. Could have sworn you needed the SDK but I'll be happy to be wrong.

**Comment by ZappoMan** [comment]
QA Plan - this PR doesn't directly change the installer or the standard builds, and so from a "main code base" QA perspective we don't need to do any testing of this.

**Pull request merged**
