### PR TITLE
DO NOT MERGE: Texture Allocation and transfer investigation

### PR DESCRIPTION
**Pull request by samcake**
Texture Streaming Investigation

Methodology:
6 sec captures with nsight starting from one location (Welcome) to Playa
Jump (pressing enter from the address bar)
Click focus on nsight window
Click on start capture
This should take less than the first sec.
Using a script (renderTextureStats.js) to enable disable the different mode.
If the "Do Storage" is unchecked, then the texture is created but not allocated, so it will show garbage pixels. IN this case, the transfer does happen in 2 global textures allocated at the start of the application but never used
If the "Do Transfer" is unchecked, this work is skipped,  so it will show garbage pixels.
If the "Use PBO" is checked then the transfer is done using PBO.

The script also shows the measured time (cpu) for each individual actions
- Storage: the time to allocate the texture (call glTextureStorage) and to setup the tex parameter
- Transfer: the time to execute the transfer from sysmem to video mem of the pixel values
- Waiting: the time measured on cpu from the end of transfer until the gl work is actually executed and finished. THis is measuring the time for a fence added at the end of Transfer to be signaled later. THe fence is checked potentially multiple time through a call to glClienWaitSync(,,0), (supposedely not blocking), when the fence is done, the texture is signaled ready and can be used for rendering

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20747b6849f1c31ee6441ffdae14692fd486657d available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-20747b6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-20747b6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9de4d25df26ec7950c42232f4598aad6671d6c83 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-9de4d25.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-9de4d25.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d7b0daff3d7292a62fb0a4e5784bbc2e63b9776 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-3d7b0da.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-3d7b0da.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3a99fd8a6fd1dadc68b89d406c53c83e83e537b8 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-3a99fd8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-3a99fd8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd869624c5e2e2d20597fdbf2fee801d3c5561c1 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-bd86962.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-bd86962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 119cc05593157778578e6db152c216bba5db4d29 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-119cc05.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-119cc05.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 41f451ccf5344ed726da53dbfea7a1e27345c97b available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-41f451c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-41f451c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8fe28f20101e235836426c35b86c1029328e03f available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-c8fe28f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-c8fe28f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc9cb480ca28c00ad7242b26991aeb9f860d54b4 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-dc9cb48.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-dc9cb48.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ba95c3489b1eb99191c5b8bdf524e9d82569709 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-7ba95c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-7ba95c3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 77dd787c9198cb96ca973716aaa6463173e05b6d available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-77dd787.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-77dd787.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7eab331e49cf48f4b1026cb721025ef66a079bee available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-7eab331.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-7eab331.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5c11c842f34a6061b2f9f5f9c1587a86201a8c0f available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-5c11c84.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-5c11c84.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c3d4a8d318e93380a3ca9b13513ab3160e16734 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-8c3d4a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-8c3d4a8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bed2dcb9ba5bd909996820c7586064df1dcbbad2 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-bed2dcb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-bed2dcb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e1a5dbcd38058f12163eda7e1f126acb8db0aed available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-9e1a5db.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-9e1a5db.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0184e3ec5349a7ce4fd673a4a15f91c1c05c0113 available at: https://gist.github.com/94fc677f50798bfec8b0cc7c740b9481<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-0184e3e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8449-0184e3e.dmg

**Comment by samcake** [comment]
JUst close that

**Pull request closed without merging**
