### PR TITLE
More aggressive noise gate threshold

### PR DESCRIPTION
**Pull request by kencooke**
### Test Plan
With "Noise Reduction" enabled, verify that the noise gate still behaves as expected. This PR will be slightly more aggressive at gating background noise.

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2734/HighFidelity-Beta-PR11240-684b7fee5a73fffc5d8b0dc880233285fc863044.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2741/HighFidelity-Beta-PR11240-684b7fee5a73fffc5d8b0dc880233285fc863044.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2741/HighFidelity-Beta-PR11240-684b7fee5a73fffc5d8b0dc880233285fc863044.exe

**Comment by kencooke** [comment]
test this please

**Comment by cain-kilgore** [comment]
@kencooke: Will I hold off?

**Comment by kencooke** [comment]
@cain-kilgore Go ahead and test the Windows version. The random build failures look like a build system issue.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
With "Noise Reduction" enabled, verify that the noise gate still behaves as expected. This PR will be slightly more aggressive at gating background noise. | Pass

@kencooke Okay cool, I was in the middle of testing before I saw you started the build again. It's working perfect on my end. 😄 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2749/HighFidelity-Beta-PR11240-684b7fee5a73fffc5d8b0dc880233285fc863044.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2749/HighFidelity-Beta-PR11240-684b7fee5a73fffc5d8b0dc880233285fc863044.exe

**Comment by marko8904** [comment]
build this please

**Pull request merged**
