### PR TITLE
Updating Woody avatar for new UV seams

### PR DESCRIPTION
**Pull request by alexiamandeville**
Updating the baked asset for the woody avatar. Jimi updated the UV seams.

Test plan: 
1. Start HiFi in Desktop mode.
2. Go into 3rd person.
3. Look at back of Woody's head.
4. It should have no seams on the back of the model.
5. Test that mobile looks the same as desktop.

It should look like this:
image

### CODE REVIEW

**Comment by SamGondelman** [comment]
I think you can delete the +gles folder that has the android versions of the textures now.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13705/HighFidelity-Beta-PR14159-f2a5b1f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13705/HighFidelity-Beta-PR14159-f2a5b1f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13705/HighFidelity-Beta-Interface-PR14159-f2a5b1f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13705/HighFidelity-Beta-PR14159-f2a5b1f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13705/HighFidelity-Beta-Interface-PR14159-f2a5b1f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13719/HighFidelity-Beta-PR14159-911e5e6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13719/HighFidelity-Beta-PR14159-911e5e6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13719/HighFidelity-Beta-Interface-PR14159-911e5e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13719/HighFidelity-Beta-PR14159-911e5e6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13719/HighFidelity-Beta-Interface-PR14159-911e5e6.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15026/HighFidelity-Beta-PR14159-911e5e6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15026/HighFidelity-Beta-Interface-PR14159-911e5e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15026/HighFidelity-Beta-PR14159-911e5e6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15026/HighFidelity-Beta-Interface-PR14159-911e5e6.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . verified that there are no seams on the back of model on win/desk  and mobile

**Pull request merged**
