### PR TITLE
Temporal Anti-Aliasing

### PR DESCRIPTION
**Pull request by Zvork**
This PR introduces a replacement anti-aliasing technique to FXAA in the form of temporal antialiasing, and is based on @samcake's initial TAA proposal. The effect gives a finer result than FXAA albeit with some slight flickering. It generally removes aliasing everywhere, including shadows and shading. The temporal anti-aliasing technique is a filtering technique that averages pixel samples across time instead of space. Pixel samples at each frame are averaged with the previously rendered pixel samples after reprojection, taking into account camera movement.

# Tweaking
The effect is always on but can be edited and compared with FXAA with the help of the _scripts/developer/utilities/render/antialiasing.js_ script. This adds a new tablet app. Once the app is launched, the antialiasing effect can be tweaked:
- Antialiasing can be switched between TAA and FXAA
- TAA parameters can be tweaked, especially the source blend and post sharpen effect.

The intensity of the effect is controlled generally with the "source blend" and "covariance gamma" parameters. A low source blend will give a smoother result but with potential overblur. A low "covariance gamma" will lower the antialiasing effect as it determines how "far" appart both pixel and previous pixel color should be before averaging is performed. Low values give less tolerance to this color distance and can be used if rapidly moving camera movements tend to overblur.

# Test case
The automated test case proposed in hifi_tests/tests/engine/render/antialiasing with [hifi_tests PR #70](https://github.com/highfidelity/hifi_tests/pull/70) can be used to validate the effect.

**IMPORTANT**: this effect touches on a number of things and thus should be tested on all GPU platforms, Windows and Mac, all display types (Desktop, HMD, etc...) and on a maximum number of varied domains.

It has been tested on a Windows Augmented Reality headset and desktop on Windows.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7474/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7475/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7477/HighFidelity-Beta-PR12490-c935111c43af619ab2f2fabf9c0c2a516c9a812b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7477/HighFidelity-Beta-PR12490-c935111c43af619ab2f2fabf9c0c2a516c9a812b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7483/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7483/HighFidelity-Beta-PR12490-37fdf81f1bfd932ef471e7c5769e7f53376ed107.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7487/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7487/HighFidelity-Beta-PR12490-65f3408458a37377c44d12e3c643b2e3a4e848b5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7487/HighFidelity-Beta-PR12490-65f3408458a37377c44d12e3c643b2e3a4e848b5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7490/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7490/HighFidelity-Beta-PR12490-d3114cbc672f0d91fccb550e6d5db3c01d6caac5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7490/HighFidelity-Beta-PR12490-d3114cbc672f0d91fccb550e6d5db3c01d6caac5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7506/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7506/HighFidelity-Beta-PR12490-12d7e89d7e23da7bc1dad7afaf94b7825501fe30.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7553/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7553/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7553/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7624/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7624/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7624/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.exe

**Comment by samcake** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7825/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7825/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7825/HighFidelity-Beta-PR12490-2eb7be26cfd7b26e8903aa1171a4e85d0323a963.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Tested on Windows 10 with nVidia and AMD GPU's, with both Vive and Rift. This script failed on Mac OS. Was not able t use the AA app as it was blank.
screen shot 2018-03-08 at 10 06 10 am
[Mac Logs.zip](https://github.com/highfidelity/hifi/files/1794134/Mac.Logs.zip)

**Comment by Zvork** [comment]
@qlimnavarro Was the antialiasing effect working on Mac?

**Comment by Zvork** [comment]
Judging from the mac logs (hifi-log(1).txt), it seems that the import "qrc:///qml/styles-uit" failed. Does that ring a bell anyone?
There's also a lot of warnings concerning missing font files...

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7919/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7919/HighFidelity-Beta-PR12490-da6bd92ff6de42203b65e3f5c6e482682e64a551.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7919/HighFidelity-Beta-PR12490-da6bd92ff6de42203b65e3f5c6e482682e64a551.exe

**Comment by samcake** [comment]
"Judging from the mac logs (hifi-log(1).txt), it seems that the import "qrc:///qml/styles-uit" failed. Does that ring a bell anyone?
There's also a lot of warnings concerning missing font files..."

Right that is different bug not related to this pr
so i would say it s a pass

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by samcake** [comment]
I confirm that it s a pass
The problem of the UI not showing on mac because of the Path to the qml components is not related to this pr.

**Comment by Qliemillar** [comment]
@conklin94122 Confirmed as a pass!

**Comment by conklin94122** [comment]
Removed QA Ready. Please add relabel once the changes are made, we will retest. Thanks.

**Comment by Zvork** [comment]
@samcake And voilà, unused fonts removed in the scripts folder (not the qml as stated in the review, right?)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7971/app_12490_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7971/HighFidelity-Beta-PR12490-aad571f6bdba69cc039587bc9d01c0f2136272ea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7971/HighFidelity-Beta-PR12490-aad571f6bdba69cc039587bc9d01c0f2136272ea.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Seeing same results as earlier, therefore this passes.

**Pull request merged**
