### PR TITLE
Porting goto to the tablet 

### PR DESCRIPTION
**Pull request by druiz17**
Test Plan. 
- In tablet mode...use goto and ensure that everything works as before

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8eac7abef903c6f65206db6ff8106a74eb25620 available at: https://gist.github.com/76424978a0da559baf3c8b2331b34665<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10016-b8eac7a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10016-b8eac7a.dmg

**Comment by claudioshg** [comment]
testing

**Comment by sethalves** [comment]
claudioshg -- I'm merging this into the tablet-ui branch, but interested in your results.

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10016-b8eac7a.exe

GOTO in Desktop Mode: Success
GOTO in HMD Mode: Success

Notes:
- Tested in Tablet Mode.
- All functions work. Address bar, Home button, Browsing buttons (Left, Right), etc.
- Scrolling the GOTO dialog, with the right-click button in desktop mode, the avatars head moves up and down as you scroll.
- When you type in an address and then hit enter on the keyboard, the old GOTO window appears.

Fails:
- Switch to Desktop Mode. Then go to domain A. Once in domain A, switch to VR and then go to domain B. Once in Domain B, the tablet does not load anymore.

**Pull request merged**
