### PR TITLE
Automatically upgrade toolbar position to bottom center of window

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing Notes
Delete Interface.ini
Run up old version of Interface
Toolbars (directory, examples, edit) should be on the right-hand side of window
Optionally drag toolbars to adjust their positions a little
Run up this PR version of Interface
Toolbars should be bottom centre of window
Drag toolbars to change positions
Toolbars should remember their new positions
Subsequent adjustments in toolbar position should be remembered between Interface runs

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7188bad30510298f4810f22b2009444cf5bc553 available at: https://gist.github.com/14ce6f28c9bd09d607f932441eda6792<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7782.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7782.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by RyanDowne** [comment]
This did not work for me. The examples overlay gets centered but the other ones don't. I let David know and he is looking into it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1cf53829d3adab9875ec28962e75ece01c60cbc7 available at: https://gist.github.com/14ce6f28c9bd09d607f932441eda6792<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7782.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7782.dmg

**Comment by RyanDowne** [comment]
@Nex-Pro can you test this now too? Thanks!

**Comment by Nex-Pro** [comment]
@RyanDowne  Hi, you want me to test this now ?

**Comment by Nex-Pro** [comment]
Platform Win10 desktop 16gb ram  GTX770 2gb
This worked fine for me.

**Pull request merged**
