### PR TITLE
domain-server tells metaverse if it has no ice-server

### PR DESCRIPTION
**Pull request by sethalves**
- domain-server tells metaverse if it has no ice-server

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6bce73db800aa1c97116cdb8fe99d0475c3a4911 available at: https://gist.github.com/b782cdb2d837e0721f324aef706a379c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-6bce73d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-6bce73d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7dc8a48dbad4b341831802060bb5b7f92fa75bd8 available at: https://gist.github.com/b782cdb2d837e0721f324aef706a379c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-7dc8a48.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-7dc8a48.dmg

**Comment by sethalves** [comment]
to test:
- make sure servers from this PR work as expected

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1690/Metaverse-stats-domains-api-returns-invalid-data-when-all-ice-servers-are-down

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2c53786277899bed1ad4df5b22b66e740326e7b available at: https://gist.github.com/b782cdb2d837e0721f324aef706a379c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-d2c5378.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-d2c5378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8cadd299a2c0e681c4f3d9af0a5730d8fc073d49 available at: https://gist.github.com/b782cdb2d837e0721f324aef706a379c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-8cadd29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8629-8cadd29.dmg

**Comment by cozza13** [comment]
Network testing by connected to local host and dev domains

**Pull request merged**
