### PR TITLE
Bloom

### PR DESCRIPTION
**Pull request by Zvork**
This PR introduces a new post processing bloom / glare effect that operates on the entire screen which simulates light diffusion in the lens and light bleeding on the camera sensor. This has the visual effect of highlighting the very bright parts of the image by surrounding them with a halo-like effect.
The algorithm operates on the bright pixels of the rendered image, before tone mapping, by applying a multi level blur on these bright pixels and compositing a mix of these multi-level blurs on top of the rendered image. The bright pixels are selected by thresholding the input image with an adjustable parameter.

## Parameters
The effect is configured with three parameters:

- **Intensity** : this controls the level of compositing of the blur on top of the rendered image. At 0 no bloom is visible.
- **Size** : this determines the size of the bloom on the screen or, said another way, how far the bright lights bleed.
- **Threshold**: this is the threshold parameter used to select which bright parts of the image to use for the bloom input. Higher values can be used to use only very bright pixels. At 0, virtually all pixels are used.

# TEST PLAN
This test plan should be done with the _debugBloom.js_ script running - which can be found under scripts/developer/utilities/render - to modify the various parameters.

Please note that this effect can be very sensitive to rapidly changing bright pixels (such as in real life!) such as very bright thin specular highlights on bumpy surfaces.

0. Enable the bloom by checking the "Enabled" checkbox on the Bloom debug window 
1. A subtle halo should surround very bright parts of the image, such as specular highlights on metallic objects or emissive objects.
2. The halo color should be of the same color as the bright objects it surrounds.
3. The halo should move with the bright objects when these or the camera moves.
4. The effect should feel comfortable in stereo / HMD display mode.
5. Unchecking the "Enabled" checkbox on the Bloom debug window should disable the effect.
6. Modifying the "Intensity" slider on the Bloom debug window should modify the visual intensity of the halo.
7. Modifying the "Size" slider on the Bloom debug window should modify the scale of the halo.
8. Increasing the "Threshold" slider should gradually limit the halo to only the very bright parts of the image. Decreasing it should gradually add the halo on the entire screen.

Verify that Ambient Occlusion is working correctly (enabling it in developer/graphics dialog.

Verify that skin Subsurface scattering material works correctly using the avatar 
https://highfidelity.com/marketplace/items/f3fbb9f4-e159-49ed-ac32-03af9056b17e
in various environement and check that the skin displays correctly

This test plan should be tested on various GPU platforms.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4006/HighFidelity-Beta-PR11559-d3add89b3c3a8b0cc88f589a55131c269535dccc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4006/HighFidelity-Beta-PR11559-d3add89b3c3a8b0cc88f589a55131c269535dccc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4084/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4084/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4532/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4532/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4603/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4603/HighFidelity-Beta-PR11559-055270df9c6bec1d20b97f4f9df0b2bee44d829b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4677/HighFidelity-Beta-PR11559-fcf1c301b61fa605bfb4e047dbf7547b34c02087.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4677/HighFidelity-Beta-PR11559-fcf1c301b61fa605bfb4e047dbf7547b34c02087.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4697/HighFidelity-Beta-PR11559-fcf1c301b61fa605bfb4e047dbf7547b34c02087.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4697/HighFidelity-Beta-PR11559-fcf1c301b61fa605bfb4e047dbf7547b34c02087.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4753/HighFidelity-Beta-PR11559-39604363eaeefb11ceae5c3870b117c0a21bcc5b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4753/HighFidelity-Beta-PR11559-39604363eaeefb11ceae5c3870b117c0a21bcc5b.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4802/HighFidelity-Beta-PR11559-bccd6df57c14c6586218597db4fcc9bc61a4676f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4802/HighFidelity-Beta-PR11559-bccd6df57c14c6586218597db4fcc9bc61a4676f.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4913/HighFidelity-Beta-PR11559-bccd6df57c14c6586218597db4fcc9bc61a4676f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4922/HighFidelity-Beta-PR11559-5102c8e1b1e96ddd75193531de8a5ed56f9f3cb0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4922/HighFidelity-Beta-PR11559-5102c8e1b1e96ddd75193531de8a5ed56f9f3cb0.exe

**Comment by YuppyPlays** [comment]
Testing w/ GTX 1080Ti GPU.

**Comment by YuppyPlays** [comment]
Testing complete:

All fields are a solid **Pass** as per their descriptions within test plan, I found the initial enabling to almost be un-noticeable until i carefully scaled the intensity to max then back down to its original default, beyond that all is good.

**Pull request merged**
