### PR TITLE
DEV-243 | DEV-221: Display Window Launcher version number and autoupdate

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-243
https://highfidelity.atlassian.net/browse/DEV-221

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20555/HighFidelity-Beta-PR15981-4d9557d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20555/HighFidelity-Quest-Beta-PR15981-4d9557d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20555/HighFidelity-Beta-PR15981-4d9557d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20555/HighFidelity-Beta-Interface-PR15981-4d9557d.dmg

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20559/HighFidelity-Beta-PR15981-4d9557d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20559/HighFidelity-Beta-Interface-PR15981-4d9557d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20559/HighFidelity-Beta-PR15981-4d9557d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20559/HighFidelity-Quest-Beta-PR15981-4d9557d.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20559/HighFidelity-Beta-PR15981-4d9557d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20559/HighFidelity-Beta-Interface-PR15981-4d9557d.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20568/HighFidelity-Beta-PR15981-c3ad65f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20568/HighFidelity-Beta-Interface-PR15981-c3ad65f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20568/HighFidelity-Beta-PR15981-c3ad65f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20568/HighFidelity-Beta-Interface-PR15981-c3ad65f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20568/HighFidelity-Beta-PR15981-c3ad65f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20568/HighFidelity-Quest-Beta-PR15981-c3ad65f.apk)

**Pull request merged**
