### PR TITLE
Case: 21139 gltf model parts

### PR DESCRIPTION
**Pull request by raveenajain**
https://highfidelity.manuscript.com/f/cases/21139/gltf-models-loading-with-incorrect-parts
https://github.com/highfidelity/hifi_tests/pull/374

### CODE REVIEW

**Comment by raveenajain** [comment]
Test Plan: 

TBD

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17436/HighFidelity-Beta-PR14966-b94807a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17436/HighFidelity-Beta-PR14966-b94807a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17436/HighFidelity-Beta-Interface-PR14966-b94807a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17436/HighFidelity-Beta-PR14966-b94807a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17436/HighFidelity-Beta-Interface-PR14966-b94807a.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17723/HighFidelity-Beta-PR14966-c1516df.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17723/HighFidelity-Quest-Beta-PR14966-c1516df.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17723/HighFidelity-Beta-PR14966-c1516df.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17723/HighFidelity-Beta-Interface-PR14966-c1516df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17723/HighFidelity-Beta-PR14966-c1516df.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17723/HighFidelity-Beta-Interface-PR14966-c1516df.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17793/HighFidelity-Beta-PR14966-dfb17c9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17793/HighFidelity-Quest-Beta-PR14966-dfb17c9.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17793/HighFidelity-Beta-PR14966-dfb17c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17793/HighFidelity-Beta-Interface-PR14966-dfb17c9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17793/HighFidelity-Beta-PR14966-dfb17c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17793/HighFidelity-Beta-Interface-PR14966-dfb17c9.exe

**Pull request merged**
