### PR TITLE
Avatar App: stop reloading existing selected bookmarks on app relaunch (master)

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.manuscript.com/f/cases/17982/Avatar-App-reloads-existing-selected-bookmark-on-app-relaunch

**Test plan**

Ensure AvatarApp still can detect whether current avatar is bookmarked and highlight it.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12536/HighFidelity-Beta-PR13911-daf81bb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12536/HighFidelity-Beta-PR13911-daf81bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12536/HighFidelity-Beta-Interface-PR13911-daf81bb.dmg

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12864/HighFidelity-Beta-PR13911-daf81bb.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12864/HighFidelity-Beta-PR13911-daf81bb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12864/HighFidelity-Beta-Interface-PR13911-daf81bb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12864/HighFidelity-Beta-PR13911-daf81bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12864/HighFidelity-Beta-Interface-PR13911-daf81bb.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Avatar app remembers when current avatar is bookmarked, including when changes are made and then reverted while the app is closed

**Pull request merged**
