### PR TITLE
remove noisy logging added by auto baking

### PR DESCRIPTION
**Pull request by birarda**
- removed noisy logging from ModelCache

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

1. Run this PR build in a domain that uses OBJ collision hulls (eschatology should be a good test).
2. Confirm you see no messages in your log that start with "setGeometryDefinition()" or "Created network material with base url:"

**Comment by OmegaHeron** [comment]
Will test this.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3628/HighFidelity-Beta-PR11461-b77ceab661715c851f4213ad2d92f48277846d76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3628/HighFidelity-Beta-PR11461-b77ceab661715c851f4213ad2d92f48277846d76.exe

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Confirmed seeing messages in master.
Confirmed not seeing messages in PR.

**Pull request merged**
