### PR TITLE
Fix "Reset Settings" window poping up every time

### PR DESCRIPTION
**Pull request by Atlante45**
## Test plan:
- Launch PR build
- Enable Developer Settings
- Go through several Interface runs by randomly shutting down interface properly or selecting one of the options in "Developer > Crash"
- The "Reset Settings" popup should only show up after a crash

### CODE REVIEW

**Comment by marko8904** [comment]
github still occasionally triggers builds on the old cluster. This PR resulted in a duplicate. Please ignore the incoming "All checks failed" message. The real build will update the status within the next 30min.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2e2682effa3c048591b2311a248fb7c23a08b0d available at: https://gist.github.com/dfb22be66f7e478e73613a9c6e46e9de<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10512-c2e2682.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10512-c2e2682.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/39/HighFidelity-Beta-PR10512-c2e2682effa3c048591b2311a248fb7c23a08b0d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/39/HighFidelity-Beta-PR10512-c2e2682effa3c048591b2311a248fb7c23a08b0d.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
Testing *PASSED*

Reset dialog only appears after a crash. Went through some of the options in the Developer Menu to crash the game, and when starting up normally the reset settings dialog never came up.

**Pull request merged**
