### PR TITLE
Hotfix: disable baking of JS files in Asset Server

### PR DESCRIPTION
**Pull request by birarda**
- disable baking of JS files in Asset Server until bake version is pushable

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

1. Upload a JS file to your asset server.
2. The "Use Baked" column should show two dashes to indicate that baking of that file type is not supported.
3. Use that script in interface (as an entity script or client script). Ensure that the behaviour is correct.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4436/HighFidelity-Beta-PR11685-60fbbe4bc0e4f725353202650b93d7f44675a6c1.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4441/HighFidelity-Beta-PR11685-60fbbe4bc0e4f725353202650b93d7f44675a6c1.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4443/HighFidelity-Beta-PR11685-60fbbe4bc0e4f725353202650b93d7f44675a6c1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4443/HighFidelity-Beta-PR11685-60fbbe4bc0e4f725353202650b93d7f44675a6c1.exe

**Comment by Nex-Pro** [comment]
Testing Win 10

**Comment by Nex-Pro** [comment]
### PASS 

scripts run from ent server.  double dashes in atp list for scripts.

Also fresh FBX baked as normal

**Pull request merged**
