### PR TITLE
Port audio stats to tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Developer > Audio > Stats in the tablet menu displays the stats dialog in the tablet.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 854292b19364e9e635748210595a0d6d1a1624a2 available at: https://gist.github.com/6a58454012cd71a02de810ae18c55aa4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9802-854292b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9802-854292b.dmg

**Comment by ZappoMan** [comment]
this PR is massive... maybe you shouldn't be merging into master? should this go into some other branch?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6403e51d20d179015e90c1f36eee88254f3ac18c available at: https://gist.github.com/6a58454012cd71a02de810ae18c55aa4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9802-6403e51.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9802-6403e51.dmg

**Comment by ctrlaltdavid** [comment]
@ZappoMan The intention is to merge this branch into Seth's tablet UI branch. (This is where the majority of the changes originate from.)

**Comment by ctrlaltdavid** [comment]
Testing:
- Developer > Audio > Stats works the same in the tablet as it does in desktop window.
- Desktop window still works the same as in current  dev-download build.

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Opened Developer > Audio > Stats on HMD and it showed in the tablet just fine
* Did the same thing in desktop mode and it showed as a floating QML type window same as before

**QA PASS**

**Comment by ctrlaltdavid** [comment]
Merged into Seth's tablet-ui-edit-js branch.

**Pull request closed without merging**
