### PR TITLE
glTF import DEMO

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR allows users to create and import new models using the glTF file format.

...

## TEST PLAN
- Go to the Sandbox or other domain where you can create entities.
- Create a new model with the url: https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf
- The glTF model should appear in front of you.

...

## KNOWN ISSUES
- It will only import static geometry.
- No bone information or animations will be imported.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3060/HighFidelity-Beta-PR11308-d7c525cf3ae32ceb0928f6d6e6d81d563384cf89.exe

**Comment by AndrewMeadows** [comment]
The build is failing on ubuntu for these errors:
```
20:46:05 libraries/fbx/src/GLTFReader.h:582:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
20:46:05  #endif hifi_GLTFReader_h
20:46:05         ^
20:46:05 [ 36%] Building CXX object libraries/fbx/CMakeFiles/fbx.dir/src/ModelFormatLogging.cpp.o
20:46:06 [ 36%] Building CXX object libraries/recording/CMakeFiles/recording.dir/src/recording/Logging.cpp.o
20:46:06 ubuntu/libraries/fbx/src/GLTFReader.h:566:34: error: extra qualification ‘GLTFReader::’ on member ‘requestData’ [-fpermissive]
20:46:06      std::tuple<bool, QByteArray> GLTFReader::requestData(QUrl& url);
20:46:06                                   ^
20:46:06 ubuntu/libraries/fbx/src/GLTFReader.h:567:20: error: extra qualification ‘GLTFReader::’ on member ‘request’ [-fpermissive]
20:46:06      QNetworkReply* GLTFReader::request(QUrl& url, bool isTest);
20:46:06                     ^
20:46:06 ubuntu/libraries/fbx/src/GLTFReader.cpp: In member function ‘bool GLTFReader::getIndexFromObject(const QJsonObject&, const QString&, int&, QMap<QString, bool>&)’:
20:46:06 ubuntu/libraries/fbx/src/GLTFReader.cpp:308:75: error: invalid initialization of non-const reference of type ‘QMap<QString, bool>&’ from an rvalue of type ‘QMap<QString, bool>’
20:46:06          return getIntVal(subobject, "index", outidx, QMap<QString, bool>());
20:46:06                                                                            ^
20:46:06 ubuntu/libraries/fbx/src/GLTFReader.cpp:47:6: note:   initializing argument 4 of ‘bool GLTFReader::getIntVal(const QJsonObject&, const QString&, int&, QMap<QString, bool>&)’ 
20:46:06  bool GLTFReader::getIntVal(const QJsonObject& object, const QString& fieldname, int& value, QMap<QString, bool>&  defined) {
20:46:06       ^
```

**Comment by luiscuenca** [comment]
Thanks for the info Andrew.

**Comment by ZappoMan** [comment]
@samcake @cozza13 @luiscuenca - Luis, please repair the build errors and Chris and Sam, let's get this fixed up and merged!

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3249/HighFidelity-Beta-PR11308-e1ac16498e51d03a0aac7de5fbbf04276a3cfd2e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3250/HighFidelity-Beta-PR11308-f25288178baaa36c638a8b74529b393e65d9ab35.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3258/HighFidelity-Beta-PR11308-68bce3c09c029c2d663a8f204cd10cec14e9d6aa.exe

**Comment by luiscuenca** [comment]
Any hints on why it keeps failing? (I don't have access to the error details)
Thanks.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3842/HighFidelity-Beta-PR11308-7cbf50e000f2ca23257434dc4cf1aed4077a8c77.exe

**Comment by themelissabrown** [comment]
@luiscuenca are you going to be addressing this PR? Or should we close it?

**Comment by Menithal** [comment]
@themelissabrown I think @luiscuenca just submitted a new commit 6 days ago so he was still working on it. Probably not actively looking at PR comments.

In anycase, here are the following failures @luiscuenca 

MACOS:

```
15:58:29 /home/jenkins/workspace/pr-build/label/ubuntu/libraries/model-networking/src/model-networking/ModelCache.cpp: In member function ‘virtual void GeometryReader::run()’:
15:58:29 /home/jenkins/workspace/pr-build/label/ubuntu/libraries/model-networking/src/model-networking/ModelCache.cpp:203:56: error: ‘make_unique’ is not a member of ‘std’
15:58:29                  std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
15:58:29                                                         ^
15:58:29 /home/jenkins/workspace/pr-build/label/ubuntu/libraries/model-networking/src/model-networking/ModelCache.cpp:203:83: error: expected primary-expression before ‘>’ token
15:58:29                  std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
15:58:29                                                                                    ^
15:58:29 /home/jenkins/workspace/pr-build/label/ubuntu/libraries/model-networking/src/model-networking/ModelCache.cpp:203:85: error: expected primary-expression before ‘)’ token
15:58:29                  std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
15:58:29                                                                                      ^
15:58:30 libraries/model-networking/CMakeFiles/model-networking.dir/build.make:86: recipe for target 'libraries/model-networking/CMakeFiles/model-networking.dir/src/model-networking/ModelCache.cpp.o' failed
15:58:30 make[2]: *** [libraries/model-networking/CMakeFiles/model-networking.dir/src/model-networking/ModelCache.cpp.o] Error 1
15:58:30 CMakeFiles/Makefile2:2275: recipe for target 'libraries/model-networking/CMakeFiles/model-networking.dir/all' failed
15:58:30 make[1]: *** [libraries/model-networking/CMakeFiles/model-networking.dir/all] Error 2
15:58:30 make[1]: *** Waiting for unfinished jobs....
```

UBUNTU:

``` 
16:01:47 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/libraries/model-networking/src/model-networking/ModelCache.cpp:203:61: error: no member named 'make_unique' in namespace 'std'
16:01:47                 std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
16:01:47                                                        ~~~~~^
16:01:47 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/libraries/model-networking/src/model-networking/ModelCache.cpp:203:73: error: 'GLTFReader' does not refer to a value
16:01:47                 std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
16:01:47                                                                         ^
16:01:47 In file included from /Users/jenkins/Jenkins/workspace/pr-build/label/macos/libraries/model-networking/src/model-networking/ModelCache.cpp:17:
16:01:47 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/libraries/fbx/src/GLTFReader.h:508:7: note: declared here
16:01:47 class GLTFReader : public QObject {
16:01:47       ^
16:01:47 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/libraries/model-networking/src/model-networking/ModelCache.cpp:203:85: error: expected expression
16:01:47                 std::unique_ptr<GLTFReader> glreader = std::make_unique<GLTFReader>();
16:01:47                                                                                     ^
16:01:47 3 errors generated.
16:01:47 
```

I hope that helps, I'd like to see this PR get implemented as it would really help Creation via Blender, and especially the newer version of it.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3961/HighFidelity-Beta-PR11308-7cbf50e000f2ca23257434dc4cf1aed4077a8c77.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3982/HighFidelity-Beta-PR11308-297f591ce22c332a2a30990189f8cffd92c6ce84.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3982/HighFidelity-Beta-PR11308-297f591ce22c332a2a30990189f8cffd92c6ce84.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4011/HighFidelity-Beta-PR11308-a7a1329c5f51abfd281d688013743ca5a83ca8c9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4011/HighFidelity-Beta-PR11308-a7a1329c5f51abfd281d688013743ca5a83ca8c9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4013/HighFidelity-Beta-PR11308-25b419a1a1b8a631c7d7e02154f5d3fa7aa7b490.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4017/HighFidelity-Beta-PR11308-1da5c221ac19b973f3232c5d3b266ee3d0e3c94c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4017/HighFidelity-Beta-PR11308-1da5c221ac19b973f3232c5d3b266ee3d0e3c94c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4027/HighFidelity-Beta-PR11308-efa4911fe3b8d92c4c65ee0d965ba3a735846645.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4027/HighFidelity-Beta-PR11308-efa4911fe3b8d92c4c65ee0d965ba3a735846645.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4309/HighFidelity-Beta-PR11308-efa4911fe3b8d92c4c65ee0d965ba3a735846645.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4309/HighFidelity-Beta-PR11308-efa4911fe3b8d92c4c65ee0d965ba3a735846645.exe

**Comment by YuppyPlays** [comment]
Testing complete:

Go to the Sandbox or other domain where you can create entities. **Check**
Create a new model with the url: https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF/DamagedHelmet.gltf **Check**
The glTF model should appear in front of you. **Check**

**Pass** 

image

**Comment by Menithal** [comment]
Hey, Quick interruption to QA:

I think the QA should also include testing Skeletons, Bones, Morph Targets and animations. the GLTF standard also supports these, and these are crucial to check. We shouldnt do half of this but do it partally.

Were these also implemented according to standard @luiscuenca ?

**Pull request merged**
