### PR TITLE
[EXPERIMENT] Create a Client-only Installer that Doesn't Connect to a Domain

### PR DESCRIPTION
**Pull request by TurnMeUp-OG**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3148/HighFidelity-Beta-PR11328-93f49abe4082f35d8512561dffef362c48a731f6.exe

**Comment by TurnMeUp-OG** [comment]
We don't understand about what we should to do? Or very short problem description on our script. Could you check and explain more?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3369/HighFidelity-Beta-PR11328-93f49abe4082f35d8512561dffef362c48a731f6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3369/HighFidelity-Beta-PR11328-93f49abe4082f35d8512561dffef362c48a731f6.exe

**Comment by MiladNazeri** [comment]
@TurnMeUp-OG This looks like the build went through this time.  Not sure if that is what was the issue from before.  Can you provide a test plan though and I can send it to QA?

**Comment by TurnMeUp-OG** [comment]
Test Plan:
-Create the installer from the following scripts: NSIS.client.template.in and the parameters CPackProperties.client.cmake.in
-Run installer
-Set to the selected folder
-Run
-Check the absence of connection to domains.

**Comment by MiladNazeri** [comment]
@TurnMeUp-OG 
Can you provide more detailed instructions on how to create the installer?  A step by step would be helpful.

**Comment by TurnMeUp-OG** [comment]
The variable of the build CPACK_PACKAGE_FILE_NAME = “the address of the file NSIS.client.template.in” is to be set in “Сmake”

The variables can be set either through the console (for example, Cmake -DCPACK_PACKAGE_FILE_NAME=/.../NSIS.client.template.in ) or through the programme GUI

All the other variables are secondary and influence only the window style. Open the “Visual studio” project and assemble the “CPack” project

**Comment by OmegaHeron** [comment]
QA in progress.  Will take a bit to complete.

**Comment by OmegaHeron** [comment]
@TurnMeUp-OG 

Need confirmation that this is at latest level of codebase - In *specific*;

This seems to not work with new method where libSSL is found via vpkg system.  cmake for this branch fails to find SSL lib/include where all other recent PR branches and master is fine.

Something is either lagging too far behind master or something has been broken in cmake for this branch.

**Comment by TurnMeUp-OG** [comment]
Looks like we were waiting for QA for such a long time that this is now a problem. We've committed it for more then a month ago and being waited for this to be tested for weeks, so no surprise it is no longer supported.

**Comment by MiladNazeri** [comment]
@TurnMeUp-OG 
Thank you for your patience.  Can you give me an estimate on how long those changes will take?  I'll make sure this gets QA'd on time now that the test plan is clear.

**Comment by themelissabrown** [comment]
Since this is experimental, we'll close for now and reopen the WL task if it's still a priority. thanks for your work @TurnMeUp-OG

**Pull request closed without merging**
