### PR TITLE
refuse to handle positional audio streams with NaN position

### PR DESCRIPTION
**Pull request by birarda**
- fixed audio mixer behaviour where it would mix sources with bad positions as having no attenuation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6577/app_12249_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6578/app_12249_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6578/HighFidelity-Beta-PR12249-02eb95f5b08ce244cb471aec0ea2f0b2aef56031.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6578/HighFidelity-Beta-PR12249-02eb95f5b08ce244cb471aec0ea2f0b2aef56031.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6609/app_12249_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6609/HighFidelity-Beta-PR12249-02eb95f5b08ce244cb471aec0ea2f0b2aef56031.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6609/HighFidelity-Beta-PR12249-02eb95f5b08ce244cb471aec0ea2f0b2aef56031.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6878/app_12249_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6878/HighFidelity-Beta-PR12249-ffd10b79bf7db2e27722ffab80210d3014f058b6.dmg

**Comment by birarda** [comment]
#### Test Plan

1. Reach out to me to get a special client you will test with this PR.
2. Run that client with a master domain. Confirm that you hear everybody else in the domain with no attenuation, and everybody else in the domain hears you with no attenuation. Test with at least one other person.
3. Run that client with the sandbox from this PR. Confirm that you do not hear anybody else in the domain and that nobody else in the domain can hear you. Test with at least one other person.

**Comment by RyanDowne** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6912/app_12249_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6912/HighFidelity-Beta-PR12249-ffd10b79bf7db2e27722ffab80210d3014f058b6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6912/HighFidelity-Beta-PR12249-ffd10b79bf7db2e27722ffab80210d3014f058b6.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by conklin94122** [comment]
Needs a special build which is not yet available.

Moving to RC65, per @divyaelango88 and removing QA Ready label.

**Comment by conklin94122** [comment]
Schedule changed, moved this back to RC64.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
