### PR TITLE
Fixing info-view popup on every launch

### PR DESCRIPTION
**Pull request by jherico**
Forgot to add the code that sets the value once we've decided to launch the dialog.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c0fc0a226b6eacc83d4a38f601a40a64b95e3ddf available at: https://gist.github.com/c26dc89d500766f9c61a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.dmg

**Comment by jherico** [comment]
@ZappoMan will test on OSX, but I don't see why that would happen.

**Comment by jherico** [comment]
Hmmm... setting the value to 0 in my ini seems to work, but removing the ini file completely seems to fail.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 14efe912a6cbc1b22c3c509053ce29cae1d5e2c7 available at: https://gist.github.com/c26dc89d500766f9c61a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.dmg

**Comment by jherico** [comment]
OK, I'm awake this time.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d53010ab0d5a16555e74ec0b54186d569c6e9ec available at: https://gist.github.com/c26dc89d500766f9c61a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4829.dmg

**Pull request merged**
