### PR TITLE
Case 21129: improve nitpick usability

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/21129/

To use this version:
1) add the path to python.exe to the Windows PATH environment variable.
2) add the path to adb.exe to the Windows PATH environment variable (note that it is in adb\platform-tools).

If this is not done - an error message will appear only where these are required:
1) Python - while using the Web interface (TestRail or AWS)
2) adb - when testing on mobile.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17219/HighFidelity-Beta-PR14903-305ce74.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17219/HighFidelity-Beta-PR14903-305ce74.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17219/HighFidelity-Beta-Interface-PR14903-305ce74.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17219/HighFidelity-Beta-PR14903-305ce74.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17219/HighFidelity-Beta-Interface-PR14903-305ce74.exe

**Comment by NissimHadar** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17251/HighFidelity-Beta-PR14903-305ce74.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17251/HighFidelity-Beta-PR14903-305ce74.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17251/HighFidelity-Beta-Interface-PR14903-305ce74.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17251/HighFidelity-Beta-PR14903-305ce74.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17251/HighFidelity-Beta-Interface-PR14903-305ce74.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17252/HighFidelity-Beta-PR14903-9ed1470.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17252/HighFidelity-Beta-PR14903-9ed1470.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17252/HighFidelity-Beta-Interface-PR14903-9ed1470.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17252/HighFidelity-Beta-PR14903-9ed1470.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17252/HighFidelity-Beta-Interface-PR14903-9ed1470.exe

**Pull request merged**
