### PR TITLE
far-grabbed objects no longer fly away when the avatar body shifts

### PR DESCRIPTION
**Pull request by hyperlogic**
Before this fix, a hand vector was being tracked that was the difference between the avatar's hand in avatar space with the avatar's hand in avatar space the previous frame.  This hand vector was used to move the gripped object position.  However, when the body shifts, objects in the avatar's space will change rapidly, this would cause this hand vector to be incorrect and cause the object to shoot off in the distance.

Now, we track this hand delta in sensor a.k.a. room space.  This is immune to the shifts caused by body shifting.

Also, handControllerMouse.js has been removed.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1056/During-far-grab-body-shifting-zooms-object-away-from-you

**Comment by hyperlogic** [comment]
Test plan:
  * while wearing an HMD far grab an object, while holding it lean backward slightly while watching your feet.
  * when your feet animate to recenter the body underneath your head, the object in your hand should NOT zoom away from you.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 959a2f9915e6ef06816135cf4d25b2b9d2b68c46 available at: https://gist.github.com/4dc3c459008c22fef9989cf0911a7b6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.dmg

**Comment by hyperlogic** [comment]
another jenkins git fail

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:505)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)

test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 959a2f9915e6ef06816135cf4d25b2b9d2b68c46 available at: https://gist.github.com/4dc3c459008c22fef9989cf0911a7b6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PXMDOfju&#x2F;82-far-grab-improvements"> far-grab improvements</a>

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 959a2f9915e6ef06816135cf4d25b2b9d2b68c46 available at: https://gist.github.com/4dc3c459008c22fef9989cf0911a7b6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-959a2f9.dmg

**Comment by thoys** [comment]
## QA Testing results

This definitely fixes that the grabbed object doesn't fly away on recenter. Although I managed to get the grabbing beam working in reverse for some reason. After you pick up the object (In my case an apple from the sandbox home), and you turn around a few times, pulling the apple seems to make it go further away, and pushing the apple makes it come closer.

QA Fail

**Comment by hyperlogic** [comment]
The question I have is, is this secondary issue already present in master or not?

**Comment by thoys** [comment]
Let me check that @hyperlogic

**Comment by hyperlogic** [comment]
@thoys don't worry about checking this in master, it's definitely something I introduced.  The last commit 212175b should fix it.

**Comment by thoys** [comment]
## QA test update

That definitely fixed it! I wasn't able to reproduce the reverse beam after this.

Dear QA Curators: I didn't use the build for this fixing commit, but replaced the JS from the old installer. That's how I tested it before installer is available.


QA Pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: 212175bdaabf4db973a978f3ebba487a7987d4e1 available at: https://gist.github.com/4dc3c459008c22fef9989cf0911a7b6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-212175b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8273-212175b.dmg

**Pull request merged**
