### PR TITLE
BUGZ-1242: Fix linux specific script engine crash

### PR DESCRIPTION
**Pull request by Atlante45**
[JIRA ticket](https://highfidelity.atlassian.net/browse/BUGZ-1242)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20885/HighFidelity-Beta-PR16063-5be1cfc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20885/HighFidelity-Quest-Beta-PR16063-5be1cfc.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20885/HighFidelity-Beta-PR16063-5be1cfc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20885/HighFidelity-Beta-Interface-PR16063-5be1cfc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20885/HighFidelity-Beta-PR16063-5be1cfc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20885/HighFidelity-Beta-Interface-PR16063-5be1cfc.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20911/HighFidelity-Beta-PR16063-5be1cfc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20911/HighFidelity-Beta-Interface-PR16063-5be1cfc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20911/HighFidelity-Beta-PR16063-5be1cfc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20911/HighFidelity-Quest-Beta-PR16063-5be1cfc.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20911/HighFidelity-Beta-PR16063-5be1cfc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20911/HighFidelity-Beta-Interface-PR16063-5be1cfc.exe

**Pull request merged**
