### PR TITLE
(BUGZ-955) Disable unnecessary picking (conservative subset)

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.atlassian.net/browse/BUGZ-955

This PR is a subset of https://github.com/highfidelity/hifi/pull/15949, discluding changes involving grab.js and simplifiedUI settings.

It disables picking for certain picks in situations when they are not needed, improving performance.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20490/HighFidelity-Beta-PR15967-d48c8d8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20490/HighFidelity-Quest-Beta-PR15967-d48c8d8.apk)

**Comment by sabrina-shanman** [comment]
Double checking this is working as expected

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20490/HighFidelity-Beta-PR15967-d48c8d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20490/HighFidelity-Beta-Interface-PR15967-d48c8d8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20490/HighFidelity-Beta-PR15967-d48c8d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20490/HighFidelity-Beta-Interface-PR15967-d48c8d8.dmg

**Pull request merged**
