### PR TITLE
don't log spam on empty URL

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
1) run interface
2) create a box or other shape
3) you shouldn't see the following log message:
```
[06/15 08:54:40] [WARNING] Invalid shader URL:  QUrl("")
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e459085ac650ef121b7a7ca53c096da12a50a7f available at: https://gist.github.com/07ca3053e86a92a48502c897cef35fe2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8076.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8076.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Created a box and found no reference to ```[WARNING] Invalid shader URL:  QUrl("")``` however did find which may or may not be relevant```[06/16 13:45:38] [DEBUG] Web Window JS message: file:///C:/Program%20Files/High%20Fidelity%20-%20PR8076/scripts/system/html/entityProperties.html 809 Uncaught TypeError: undefined is not a function```

**Pull request merged**
