### PR TITLE
Update Leap Motion script to use animation state handlers

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Known bug: In desktop mode, restarting the script has an incorrect calibration pose. Work around is to restart Interface.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Known bug mentioned above is fixed in: https://github.com/highfidelity/hifi/pull/6578

**Comment by imgntn** [comment]
@ctrlaltdavid is this one i need to test with the leap attached to a HMD?  get some weird results with the leap on my desk.  thanks! :)

**Comment by ctrlaltdavid** [comment]
@imgntn Set Developer > Hands > Leap Motion > Leap Motion on HMD according to whether you're using the device on your desk or on your HMD. ... Leap on desk: place your two hands above it in a "zero position" to calibrate it (i.e., similar to what your avatar does when Leap Motion data is first detected).

**Comment by imgntn** [comment]
cool, seems to be working a bit better now -- i'm not sure i understand exactly how to calibrate it (does it do it automatically?  i usually have one hand on the mouse or keyboard to reset the script)
capture

**Comment by ctrlaltdavid** [comment]
All it does is set a reference position for the hands so that it can map Leap-measured hand positions to avatar hand positions (just height and forward/aft position, from memory).

**Pull request merged**
