### PR TITLE
Add option to start up at home location

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Menu item: Navigate > Start-Up Location with the following options:
- Home
- Last Location

Default is Last Location.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

A) Desktop mode

1) Initial start-up. (Delete PR's Bookmarks.json and Interface.json files.)
- Interface starts up in tutorial.
- Navigate > Bookmarks menu item is disabled.
- Navigate > Start-Up Location is set to Last Location.

2) Start-Up Location = Home with no Home set.
- Without setting any bookmarks or a home location, navigate to a memorable location.
- Set Navigate > Start-Up Location > Home.
- Restart Interface.
- Interface should start up at you last location.

3) Start-Up Location = Home with a Home set.
- Use Navigate > Set Home Location to set your home location to a memorable place.
- Move somewhere else and check that Navigate > Bookmarks > Home teleports you to your home location.
- Set Navigate > Start-Up Location > Home.
- Move to a location that isn't your home location.
- Restart Interface.
- Interface should start up at you home location.

4) Start-Up Location = Last Location.
- Move to a location that isn't your home location.
- Restart Interface.
- Interface starts up at your last location.

5) Start up with URL in command line.
- Navigate to a domain and location that's different from your current home location.
- Use Navigate > Copy Address To Clipboard to get the URL.
- Navigate to a different domain and location, that's different to this location and your current home location.
- Exit Interface.
- Start up Interface from the command line that specifies a URL. On Windows, open a command prompt and type in the following (including "s, replacing `<address>` with the address you copied before).
```
"C:\Program Files\High Fidelity - PRNNNNN\Interface.exe" --url hifi://<address>
```
- Interface should start up at the specified domain and location name rather than your previous location or your home location.

B) HMD mode
Check that the Navigate > Start-Up Location setting works.
- Setting is remembered between Interface runs.
- Setting is used correctly at Interface start.

https://highfidelity.manuscript.com/f/cases/18577

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14542/HighFidelity-Beta-PR14312-ae2715a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14542/HighFidelity-Beta-PR14312-ae2715a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14542/HighFidelity-Beta-Interface-PR14312-ae2715a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14542/HighFidelity-Beta-PR14312-ae2715a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14542/HighFidelity-Beta-Interface-PR14312-ae2715a.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15028/HighFidelity-Beta-PR14312-ae2715a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15028/HighFidelity-Beta-PR14312-ae2715a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15028/HighFidelity-Beta-Interface-PR14312-ae2715a.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Test passes with a bug:
It is possible to deselect both options while in VR. This has no side effects (the most recently-selected option remains chosen, and is visibly selected on the next launch) but it doesn't look good.

image

**Pull request merged**
