### PR TITLE
kick

### PR DESCRIPTION
**Pull request by birarda**
- add the ability to kick (via mod.js)
- rename ignore.js to mod.js and expand functionality
- add IP based permissions to domain-server settings
- remove the concept of master config in domain-server

### CODE REVIEW

**Comment by birarda** [comment]
This PR is branched from #8197. It cannot be code-reviewed or merged before that is merged, but is ready for QA.

#### Test Plan

This PR introduces a protocol change (new packet) so you will need to test with the Sandbox from this PR.

You will notice some groups specific UI in domain-server settings and some failures in log. Ignore both as they are part of a separate PR to be merged before this one.

Ping me should you need assistance with testing (for an additional Interface instance outside your network).

In the tests below, when asked to click on an overlay you must test both a desktop mouse click and an HMD hand controller trigger click.

**First, we'll test the detection of a user's ability to kick in a given domain.**

1. Make sure you are running mod.js.
2. You should see the Ignore button in the HUD from the previous Ignore work.
3. Go to your domain-server settings and give yourself the permission to kick other users. If connecting from the same machine the easiest way will be to check the "Kick" column for the localhost user.
4. You should see the Ignore button change to say "Kick".
5. Run another instance of Interface from this PR and connect to the same domain. Ensure you can see the other user from the machine running mod.js.
6. With kick permissions, click the Kick button in the HUD to show the Kick overlays. You should see an overlay above the other user that says "KICK" and points towards the user.
5. Toggle the kick permission back and forth a couple of times and confirm that the button in the HUD and the overlays change to reflect the correct state. It will show Ignore if you cannot kick in the domain and Kick if you can kick in the domain.

**Okay, now let's test kick via public IP.**

1. Make sure you are running mod.js and you have kick permissions in the domain.
2. Make sure the user you want to kick is not logged in but is connected to the domain (this will also require anonymous access to the domain) from a different network than the Sandbox.
3. Click on the HUD button to show the kick overlays.
4. Click on the kick overlay above the user you want to kick.
5. Confirm that the user immediately dissapears and you do not see them re-appear after any amount of time.
6. Confirm from the kicked user's machine that they are shown that they are not connected. If they have not been displayed a modal saying that they do not have permissions to enter the domain, it will be displayed at this time.
7. Go to the domain-server settings. Confirm that a row has been added to the IP permissions grid for the public IP of the kicked user. Connect will be unchecked for this row.
8. Have an additional Interface client from the same kicked public IP attempt to connect and confirm they are unable to connect.
8. Check the connect permission (granting the kicked user permission to connect again). Save the settings and confirm that you see the kicked user re-connect from both Interface machines.

**Okay, now let's test kick via local IP.**
1. Make sure you are running mod.js and you have kick permissions in the domain.
2. Make sure the user you want to kick is not logged in but is connected to the domain (this will also require anonymous access to the domain) from the same network as the Sandbox.
3. Click on the HUD button to show the kick overlays.
4. Click on the kick overlay above the user you want to kick.
5. Confirm that the user immediately dissapears and you do not see them re-appear after any amount of time.
6. Confirm from the kicked user's machine that they are shown that they are not connected. If they have not been displayed a modal saying that they do not have permissions to enter the domain, it will be displayed at this time.
7. Go to the domain-server settings. Confirm that a row has been added to the IP permissions grid for the local IP of the kicked user. Connect will be unchecked for this row.
8. Check the connect permission (granting the kicked user permission to connect again). Save the settings and confirm that you see the kicked user re-connect from both Interface machines.

**Okay, now let's kick via username.**

1. Make sure you are running mod.js and you have kick permissions in the domain.
2. Make sure the user you want to kick is logged in and is connected to the domain.
3. Click on the HUD button to show the kick overlays.
4. Click on the kick overlay above the user you want to kick.
5. Confirm that the user immediately dissapears and you do not see them re-appear after any amount of time.
6. Confirm from the kicked user's machine that they are shown that they are not connected. If they have not been displayed a modal saying that they do not have permissions to enter the domain, it will be displayed at this time.
7. Go to the domain-server settings. Confirm that a row has been added to the user permissions grid for the username of the kicked user. Connect will be unchecked for this row.
8. Check the connect permission (granting the kicked user permission to connect again). Save the settings and confirm that you see the kicked user re-connect from both Interface machines.

**Okay, let's test manual kicking and permission precedence.**

1. Manually add a row in the domain-server settings in both the IP table and the username table for the Interface being kicked/blocked.
2. Grant connect permissions in the IP row, but not in the user row.
3. Confirm that while logged in the Interface clien that is blocked cannot connect.
4. Log out in that Interface client and confirm that you can connect.
5. Remove the connect permission for the IP but add it for the username.
6. Log back in on the kicked user's Interface and confirm you can connect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 28b7e9b6cfc37485d661caf867781d2aff815bf9 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-28b7e9b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-28b7e9b.dmg

**Comment by thoys** [comment]
Can someone give Jenkins a `kick` its 3:12 am and me and @SydoxX wanna test this :D (joke of course, Jenkins is cool :+1: )

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d2bfae1d85fca947b36b25620be1ebd44c68fe9 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-6d2bfae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-6d2bfae.dmg

**Comment by thoys** [comment]
## QA testing report

Tested with @SydoxX .
- We went through all the steps smoothly (except the local network kicks ofcourse, which I did myself)
- Was able to kick by mouse, but not by Vive handcontroller. The Click event doesn't seem to get registered

QA Fail

**Comment by OmegaHeron** [comment]
Tested Linux (Ubuntu 16.04.1) for Stack - all functions work as advertised.  This was specific QA for Linux function of server side.  @thoys will need to look at issue found for HMD UI and validate.

**Comment by birarda** [comment]
test this please

**Comment by birarda** [comment]
@thoys if/when Jenkins builds this I believe the Vive clicking is fixed.

**Comment by birarda** [comment]
test this please

**Comment by thoys** [comment]
test this please

**Comment by thoys** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: baaeac4de159aee3be02496ffe493b873fb2c3d6 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-baaeac4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-baaeac4.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: baaeac4de159aee3be02496ffe493b873fb2c3d6 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-baaeac4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-baaeac4.dmg

**Comment by thoys** [comment]
## QA update

- Hand controllers fixed, will QA again after Group PR is merged

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf196f46f53ce2068c77aca06169ab4c69f3091d available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-bf196f4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-bf196f4.dmg

**Comment by birarda** [comment]
@thoys this is likely good for a re pass now that #8197 is merged

**Comment by thoys** [comment]
sure, could you just merge master in this?

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1220b87f13f57058b07bced6afca403a86634b8 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1220b87f13f57058b07bced6afca403a86634b8 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.dmg

**Comment by birarda** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1220b87f13f57058b07bced6afca403a86634b8 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.dmg

**Comment by thoys** [comment]
ty @marko8904

**Comment by thoys** [comment]
## QA testing update

- This all works still fine, was able to kick michelle and anonymous michelle. Permissions work fine, unblocking the user and still blocking the IP allows only that user to be entering from that IP.
- Kicking through HMD with the handcontrollers also still functions fine.

QA Pass

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1220b87f13f57058b07bced6afca403a86634b8 available at: https://gist.github.com/8572d82a552bfcf6a154bf0f098c076b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8326-a1220b8.dmg

**Pull request merged**
