### PR TITLE
Fix for "PAL orbs are no longer visible through tablet/toolbar and objects in world"

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
This PR addresses https://highfidelity.manuscript.com/f/cases/16595/.

# Testing
1.  Enter a domain with people in it and select People from the tablet.
2.  Verify that orbs (small spheres on avatars) appear over the tablet and any objects.

3.  In addition - run the automated test `tests\content\overlay\alpha\test.js`

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11269/HighFidelity-Beta-PR13595-7b56cfb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11269/HighFidelity-Beta-PR13595-7b56cfb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11269/HighFidelity-Beta-Interface-PR13595-7b56cfb.dmg

**Comment by NissimHadar** [comment]
Please build me

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11272/HighFidelity-Beta-PR13595-7b56cfb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11272/HighFidelity-Beta-PR13595-7b56cfb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11272/HighFidelity-Beta-Interface-PR13595-7b56cfb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11272/HighFidelity-Beta-PR13595-7b56cfb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11272/HighFidelity-Beta-Interface-PR13595-7b56cfb.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Orbs appear behind tablet and objects.

**Pull request merged**
