### PR TITLE
Beta Release 18 - Includes up to Developer Release 5240

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Fix depth state caching / resetting
* Better allocation of CPU time while loading scenes and when slow scripts are running
* Asset browser ui: Add dynamic and collision shape selection to add to world flow from asset browser. 
* Deferred batches: Part 1 of a project to migrate backend rendering execution off the main thread. This will cause all batches to be generated for a frame, and once the frame is complete, cause all the batches to be executed, rather than doing a per-batch build/execute 
* Tuned haptic pulses for grab, release, equip, de-quip on the Vive
* Fix alpha cut-outs and incorrect gamma on web overlays and entities
* Fixes a bug in `Assets.getMapping` where it wasn't providing the hash value back to the QML callback. 
* Groups: Permissions can be granted or revoked based on users' memberships in groups within the Domain Server security section.
* Add OverlayWebWindow resized, moved, and closed signals
* New Progress.js capability that corrects displays scene loading
* kick
- add the ability to kick (via mod.js) 
- add IP based permissions to domain-server settings 
- Allow the ability to grant other users kick permissions. 
* If the oculus HMD isn't on someone's head, don't take input from the controllers
* Bug fix for avatar debug marker rendering.
* Tweak Teleport + Hand Lasers
* Added dead zones to Hydra and Oculus Touch joysticks
* Implement codec renegotiation in client
* Fix remote triggering handControllerGrab 
* Fix bug which caused getValue for a non-existent key to return the integer 2
* Fix some group-related code to handle CamelCase usernames
* Close file browser dialog immediately after selecting asset to upload
* Use default avatar when avatar-url is bogus
* Fix parsing of embedded entity scripts
* Avoid DS heartbeats with non-metaverse domain ID
* Adjust some values so that it's easier to unequip something by pulling it away from the hand

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6585be036c1c736669bfc49fc6a1b26c510435c7 available at: https://gist.github.com/7f9ac8736a21e19f46a1a3b611900175<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8384-6585be0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8384-6585be0.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by Nex-Pro** [comment]
downloading for testing

**Comment by OmegaHeron** [comment]
## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: See below

A few things.  This seems to have regressed to previous behavior on my i5 CPU.

Initially all is well with home scene (localhost) - Interface manages to load it, eventually, but, what I'm seeing that seems a definite regression is in VRAM freeing. Visit localhost - let completely load change to an undefined domain address (essentially disconnected) and return to localhost repeatedly.  GPU RAM fills and log begins flooding with lines like below;

`[08/06 12:36:37] [DEBUG] QOpenGLDebugMessage("APISource", 131186, "Buffer performance warning: Buffer object 2134 (bound to NONE, usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.", "MediumSeverity", "PerformanceType")`

Once this state has been entered performance is < unacceptable and Interface becomes increasingly prone to deadlocking.  I'll backtrack to last few RC builds and see where this begins again.

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: works all as expected, I notice less big spikes on dev-demo while running the performance test

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |59
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |58
**CPU Buffer Count**: |915 |5714 |4433
**GPU Buffer Count**: |240 |1161 |769
**CPU Memory Usage**: |32251904 |110444544 |88518656
**GPU Memory Usage**: |16416768 |57016320 |43872256
**CPU Texture Count**: |93 |409 |406
**GPU Texture Count**: |844 |1265 |952
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |58573896 |360096512 |757947680
**GPU Texture Memory Usage**: |176802973 |2104893884 |810085053
**GPU Virtual Memory Usage**: |322146341|2250237252|955428421
**Triangle Count**: |57571 |935403 |609495
**Triangle Rate**: |3598187 |55023705 |38093437
**API Drawcall Count**: |22 |207 |143
**Drawcall Count**: |22 |207 |143
**Drawcall Rate**: |1375 |12176 |8937
**State Changes Texture Count**:|44 |276 |199
**Pipeline Count**: |24 |35 |45
**Item Opaques**: |9 |287 |123
**Item Translucents**: |3 |22 |20
**Item Lights**: |0 |35 |4
**Timing Opaques**: |63 |1089 |582
**Timing Translucents**: |16 |56 |62
**Timing Lighting**: |62 |61 |61
**Render Frame**: |511 |1945 |

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: ```dev-demo``` playaPerformaceTest failed twice in a row. Attached screen shots. Everything else worked as normal and the stats reported normally as did the other playaPerformance tests in the other domains listed.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |46 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |43 |60
**CPU Buffer Count**: |4738 |3305 |3985
**GPU Buffer Count**: |898 |630 |839
**CPU Memory Usage**: |81465344 |70066176 |88154112
**GPU Memory Usage**: |34488320 |23932928 |43855872
**CPU Texture Count**: |350 |309 |378
**GPU Texture Count**: |1916 |2091 |2314
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |413402404 |807151048 |520969216
**GPU Texture Memory Usage**: |1230012938 |1129101830 |946755102
**GPU Virtual Memory Usage**: |1416342666|1315431558|1133084830
**Triangle Count**: |486283 |448784 |797885
**Triangle Rate**: |28604882 |28049000 |49867812
**API Drawcall Count**: |254 |192 |292
**Drawcall Count**: |313 |207 |1215
**Drawcall Rate**: |18411 |12937 |75937
**State Changes Texture Count**:|248 |194 |362
**Pipeline Count**: |35 |45 |62
**Item Opaques**: |295 |342 |341
**Item Translucents**: |34 |61 |54
**Item Lights**: |21 |46 |29
**Timing Opaques**: |1170 |1019 |1036
**Timing Translucents**: |34 |82 |92
**Timing Lighting**: |58 |91 |40
**Render Frame**: |1969 |2132 |1673

**Comment by OmegaHeron** [comment]
I can repro Kevin's results easily - load localhost fully - move to dev-playa and load fully - move to dev-demo and note performance test fails with huge excursions above red line (even worse on my system due to i5 vs Kevin's i7).  Log is flooding with GPU to CPU RAM texture swaps.

I'm noticing this build also has gone back to a tendency to not fully load localhost scene - I've been sitting > 5 minutes waiting for it to load - I see Downloads 5/16, pending 0 and 5 ATP urls in list doing nothing.  ATP server is active and showing no distress.  Going to another domain and returning allows it to load, eventually.

@jherico - There's a "feeling" of something similar to issue where web entitiy was leaking GPU RAM again - repeated connections to home scene running on localhost and disconnected space show decreasing performance of reloading home content.  Visiting home scene > 1 time then going to dev-playa leads to vast lag spikes in loading (lots of GPU->CPU RAM shuffling).

When running this on an i5 with stack and interface on same machine it's critical nothing else is using much CPU time.  It's virtually impossible to get consistent results with i5 as one run it seems awesome - another it seems unusable.  Looking at process details explains why.  Good runs shows next to no CPU load from OTHER programs - bad runs shows other processes using 20-25%.  Interface + stack on i5s live on a cliff's edge - all it takes is one app to need some time and interface jumps off said cliff.

**Comment by ZappoMan** [comment]
Also note guys -- `dev-playa` has a bunch of crazy content in it... it's not the same as playa

Maybe we need to save that content as a torture test -- and then make sure dev-playa actually matches our intended playa content set.

**Comment by PhilipRosedale** [comment]
Yes, as @ZappoMan says - we may have made a mistake in that the current dev-demo and dev-playa content are torture tests right now with broken ATP links and way more content than before.  We need to revert the dev-XXX content to the same as was used for the last release.  @cozza13 can we do this?

**Comment by OmegaHeron** [comment]
This passes for me if I don't attempt to run Interface *and* stack on same machine.

**Comment by ZappoMan** [comment]
@OmegaHeron - but you're saying that all other things being equal - the current public beta release 5211 - can run Stack Manager and Interface on the same machine? If so - that's a regression. And in particular on the same (or nearly identical content set)?

Can you get us any stats on possible differences? As in - is the CPU for the stack manager higher on this build? Is the CPU for interface higher on this build?

**Comment by ZappoMan** [comment]
I am confident that the content in dev-playa is heavier than the content in playa... as well as the difference between dev-demo and demo... We've asked the ops team to restore the content in the dev-domains to match the production domains... so that will help with apples to apples comparisons.

**Comment by nbq** [comment]
testing this now

**Comment by Nex-Pro** [comment]
***Blue line issue in this pr.***
grab-1
grab-2

**Comment by OmegaHeron** [comment]
@zappoman - no, I had lost track that to run Interface + Stack on same machine with my config I have to insure everything else that uses any measurable amount of CPU that can be terminated is terminated.  The only change I see between this and last 2 RC builds is 1) I had a failure of ATP assets loading from localhost<->localhost like was more common in weeks past 2) This build and RC17 seem to be more prone to stuffing GPU VRAM driving it into swapping GPU->CPU texture RAM.

**Comment by Nex-Pro** [comment]
pr: #8384

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb
**Testing OS:** win 10 pro
**HMD:** HTC Vive.
**Hand Controllers:** Vive
**Leap Motion:** Not used.

## QA Test

**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Reverb test did not work. Tried several times. Script loaded but changing wet-dry had no effect.

General frustrations with hand controllers. Such as teleporting unexpectedly, inability to rotate right. Somtimes unable to take off and fly.  Had to restart hand controller script a few times.  Interface crashed twice while switching to HMD mode. Bug reports filed.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |6781 |7349 |6894
**GPU Buffer Count**: |2776 |3760 |3072
**CPU Memory Usage**: |90546176 |104402944 |123703296
**GPU Memory Usage**: |36507648 |79110144 |69513216
**CPU Texture Count**: |326 |396 |448
**GPU Texture Count**: |2373 |2084 |1576
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |391168988 |63421184 |546091112
**GPU Texture Memory Usage**: |766422552 |2376616338 |1428667141
**GPU Virtual Memory Usage**: |1092096280|2702290066|1714827269
**Triangle Count**: |515229 |592912 |591147
**Triangle Rate**: |34348600 |34877176 |36946687
**API Drawcall Count**: |244 |264 |113
**Drawcall Count**: |299 |399 |113
**Drawcall Rate**: |19933 |23470 |7062
**State Changes Texture Count**:|242 |381 |178
**Pipeline Count**: |37 |38 |30
**Item Opaques**: |272 |397 |93
**Item Translucents**: |11 |19 |19
**Item Lights**: |21 |35 |2
**Timing Opaques**: |650 |1336 |269
**Timing Translucents**: |36 |30 |60
**Timing Lighting**: |92 |54 |64
**Render Frame**: |1419 |2083 |849

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Dropped Will on pad but display avatar did not change.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|No background sounds heard.
**Test 4**|undefined|Full requirements of test 4 were met.
**Test 5**|Retest the kick function|Kick Icon not showing.
**Test 6**|Switch avatar and make sure it does not crash|Success
**Test 7**|Test group functions|Basic group functions Success.
**Test 8**|Retest the kick function|Still no kick Icon
**Test 9**|Enrure that you can distance grab|Success

**EYE-01 Test Result**: **EYE-01 Test** SUCCESS
**EYE-02 Test Result**: **EYE-02 Test** SUCCESS
**EYE-03 Test Result**: **EYE-03 Test** SUCCESS
**EYE-04 Test Result**: **EYE-04 Test** SUCCESS
**EYE-05 Test Result**: **EYE-05 Test** SUCCESS
**EYE-06 Test Result**: **EYE-06 Test** SUCCESS
**EYE-07 Test Result**: **EYE-07 Test** SUCCESS
**Additional Test Results + Observations**:

**Comment by ZappoMan** [comment]
@kevinmthomasse - when you have a chance can you retest this?  I believe you called it a fail because of the dev-playa performance... correct? We've repaired the content on dev-playa to match playa... so it should be a more fair test?

@Nex-Pro - can you clarify why you call this a QA Fail? I see two complaints from you... a "blue line" and some failure with Reverb. Are you the only tester seeing those failures? Do they happen 100% of the time? You also mention frustration with the movement controls... but this seems like a report that we've seen for a while - namely the Vive touch pads are not very reliable. I'm not inclined to fail this RC because of that.

**Comment by ZappoMan** [comment]
@OmegaHeron - you also seemed to have QA Failed this because of playa performance. Can you retest with the new dev-playa content.

**Comment by OmegaHeron** [comment]
I withdrew my failure some messages back - as long as I don't run stack on same machine as interface I can pass it.

**Comment by thoys** [comment]
@Nex-Pro the Kick icon only shows when you have kick permissions, the icon will replace the Ignore button in the button bar. Make sure that you have `kick` active for your group or user in the permissions table.

**Comment by Nex-Pro** [comment]
@ZappoMan  I normally have no issue with the reverb test. On this pr it did not work for some reason.

Also I heard no background sounds at dev-playa.

As for the hand controller issues I've only recently obtained a Vive. So I don't have sufficent experience to comment. I was just commenting on my experience. I'm underwhelmed by the whole Vive thing. Very poor image quality no peripheral vision uncomfortable, heavy like wearing a scuba mask. A PITA when doing QA testing.( these are not HiFi issues ) 

NB: Don't punch your new 4k monitor with your hand contoller.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success! Tried 14 tests on ```dev-demo```with new content and no issue of any kind. Performance worked perfectly.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |61 |60
**Present Rate**: |60 |46 |60
**Present New Rate**: |56 |30 |58
**CPU Buffer Count**: |2822 |3179 |2260
**GPU Buffer Count**: |842 |624 |500
**CPU Memory Usage**: |65916928 |88911872 |58191872
**GPU Memory Usage**: |32448512 |30089216 |27189248
**CPU Texture Count**: |229 |245 |181
**GPU Texture Count**: |2715 |2540 |2570
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |262721212 |607533640 |166385224
**GPU Texture Memory Usage**: |1122635481 |1181554261 |924456884
**GPU Virtual Memory Usage**: |1293666649|1352585429|1095488052
**Triangle Count**: |499782 |386776 |523577
**Triangle Rate**: |31236375 |24173500 |32723562
**API Drawcall Count**: |250 |185 |161
**Drawcall Count**: |251 |228 |162
**Drawcall Rate**: |15687 |14250 |10125
**State Changes Texture Count**:|229 |194 |193
**Pipeline Count**: |38 |33 |43
**Item Opaques**: |280 |364 |196
**Item Translucents**: |14 |24 |53
**Item Lights**: |19 |76 |35
**Timing Opaques**: |677 |2632 |631
**Timing Translucents**: |22 |50 |156
**Timing Lighting**: |42 |90 |93
**Render Frame**: |1237 |3534 |1607

**Pull request merged**
