### PR TITLE
Fix Wallet notification appearing when taking screenshots

### PR DESCRIPTION
**Pull request by zfox23**
I don't know how this passed my own CR or anyone else's.

**Test Plan:**
1. Install this build
2. Take a snapshot in Desktop mode. Verify that the notification you receive in the top right of the screen has to do with the snapshot and NOT to do with your Wallet.

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by Nex-Pro** [comment]
@howard-stearns is this the one that I tripped over earlier today ?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4173/HighFidelity-Beta-PR11601-1cf816a261b87a85620ed91266798bf72b5fb1a6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4173/HighFidelity-Beta-PR11601-1cf816a261b87a85620ed91266798bf72b5fb1a6.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Install this build | Pass
Take a snapshot in Desktop mode. Verify that the notification you receive in the top right of the screen has to do with the snapshot and NOT to do with your Wallet. | Pass

Processing GIF Message all good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
