### PR TITLE
Case 20662: Entity Properties - fix disabling draggable numbers

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.fogbugz.com/f/cases/20662

Also fixes disabling of Script and Collision Sound fields.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17348/HighFidelity-Beta-PR14938-e46b947.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17348/HighFidelity-Beta-PR14938-e46b947.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17348/HighFidelity-Beta-Interface-PR14938-e46b947.exe

**Comment by dback2** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17473/HighFidelity-Beta-PR14938-e46b947.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17473/HighFidelity-Beta-PR14938-e46b947.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17473/HighFidelity-Beta-Interface-PR14938-e46b947.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17473/HighFidelity-Beta-PR14938-e46b947.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17473/HighFidelity-Beta-Interface-PR14938-e46b947.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request merged**
