### PR TITLE
Fix JSDoc function definitions specifying properties instead of params

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code change.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9678/app_13147_PR_fab85c3f6d433940d7c503d3a103317447300593.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9678/HighFidelity-Beta-PR13147-fab85c3f6d433940d7c503d3a103317447300593.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9678/HighFidelity-Beta-Interface-PR13147-fab85c3f6d433940d7c503d3a103317447300593.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9678/HighFidelity-Beta-PR13147-fab85c3f6d433940d7c503d3a103317447300593.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9678/HighFidelity-Beta-Interface-PR13147-fab85c3f6d433940d7c503d3a103317447300593.exe

**Pull request merged**
