### PR TITLE
2017-10-09 Commerce Frontend Updates

### PR DESCRIPTION
**Pull request by zfox23**
This PR includes the following:
- Rez buttons now properly use the `download_url` returned from the backend. This means that rezzing items from the marketplace will rez a certified entity!
- New "Backup Instructions" HTML, including bugfixes
- Refactor Wallet Status (ported from other current working branch, `pop_dynamicTests`)
- Various marketplace improvements and fixes

# Test Plan:
**Note:** Currently, you must manually enable "commerce" by adding `"commerce": true,` in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating `Settings.setValue("commerce", true)` and restarting.

**Note:** If your wallet is already set up and there is a step that asks you to not have the wallet set up yet, open the "wallet" app, help tab, and press the red "DBG: RST Wallet" button. If your wallet is set up but broken (e.g., from testing something that didn't work), such that you are prompted for a pass phrase that is never accepted, you need to:
1. Quit interface and delete `%appdata%/Interface <build #>/<username.hifikey>`
2. Restart Interface, set up wallet, and then press the red "DBG: RST WALLET" button as above. Now you are in a truly clean state for wallet setup.

## Wallet Setup Tests
1. While not logged in, open "market" app. Should have a green prompt at top of page that prompts you to log in:
    1. Login button should open proper login screen (in both tablet and toolbar/HUD). Allows both sign-in and sign-up.
    2. Clicking X should dismiss the green prompt.
2. While logged in but without wallet setup, open "market" app. Should have a green prompt at top of page that prompts you to set up wallet:
    1. Link text should open "wallet" app setup.
    2. Clicking X should dismiss the green prompt.
3. Go through wallet setup, either by the above setup link, or just by opening the "wallet" app without having it already set up:
    1. Security picture setup should work, including "tip".
    2. Setting passphrase should work, including "Show passphrase" checkbox toggle, and prompts for too short or not matching.
    3. Cancel/Back and Next buttons should work as you expect.
    4. "Open instructions for later" should open your default browser (outside of Interface) with backup instructions, AND your default file explorer open to your .hifikey directory.
4. After finishing setup, you should be left at the Home tab, with 100 HFC starting balance, and one Recent Activity message.
5. Bonus: without having wallet set up, try to buy something (as below). Should get forced to set up wallet.

## Buying
1. Open "market" app and buy something that is NOT an entity (e.g., an avatar or script, like the "Red Knight"). It should work as it always has (e.g., you wear the avatar or run the interface script immediately, without any commerce stuff happening).
2. Now search for 'test' to find some test entity-items with a non-zero price (There currently exists "test beachball", "test flaregun" and "test confetti gun").
3. Buy it. It should ask for confirmation.
4. Cancel should work, but confirm should bring you to a thank you page. The links and buttons should all work as expected.
5. Quickly go to your Wallet app. You should see two new "Pending" transactions under "Recent Activity", and your balance should reflect the money spent on the purchase. After 90 seconds, refresh the Wallet app by restarting it. The "Wallet" app should now show the purchase under Recent Activity.
6. At the top of the "market" app, click the "my purchases" link. You should see a "first time use" tutorial. Click through the tutorial.
7. Verify that "My Purchases" shows the purchase you made above. All buttons/link should work, including "rez it".
8. Restart Interface, and open "market" => "my purchases".
9. You should be prompted for your passphrase. You should then see your purchase.
10. Click the item name to go to the marketplace page for the item.
11. Buy it again. You should be told that you already own it, and can buy another. Confirm the new purchase.

### Simulate a failed purchase:
1. Click "my purchases" to see both items, one of which is pending if you did this soon enough after 3.
2. Click the item name again to go to the marketplace page for the ite.
3. Click to buy it again, but with the focus still on the confirmation page, press ctrl-f. The confirmation button should turn red.
4. Click the red button, and go to "my purchases" to see the new purchase pending. After around 90 seconds, the failed purchase should disappear from your My Purchases view

## Inspecting
1. Repeat the "marketplace inspection" test from the standard test suite at https://highfidelity.testrail.net/index.php?/suites/view/39 . However, with the "commerce" setting enabled, clicking the "i" should bring up a certificate rather than the marketplace item page.
2. Clicking the "view in market" button of the certificate should proceed to the marketplace page for the item.

## Wallet Info Tests
1. Home tab should display the transactions from above.
2. Should be able to vertically scroll through all transactions.
3. Credits should be in green, debits in red.
4. Marketplace item names should be links that bring you to the given item page in the "market" app (with the market button highlighted if in toolbar/HUD mode).
5. Security tab should let you change passphrase, security picture, or "view backup instructions" (which should work as in setup tests).
6. Help tab should show questions that can be expended to answers. Answers should make sense.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test when Win Build shows up

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3986/HighFidelity-Beta-PR11555-b81a8a95eab181f794929c2ee9e1baee41435b72.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3988/HighFidelity-Beta-PR11555-b81a8a95eab181f794929c2ee9e1baee41435b72.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3988/HighFidelity-Beta-PR11555-b81a8a95eab181f794929c2ee9e1baee41435b72.exe

**Comment by Nex-Pro** [comment]
T E S T I N G   Win 10

**Comment by Nex-Pro** [comment]
### QA for #11555

Result: **FAIL**

Testing platform:
Intel i7 workstation.
16gb ram
gtx 1070
Win10.



Test Plan:

Note: Currently, you must manually enable "commerce" by adding "commerce": true, in your Interface.json (with Interface not running), **DONE**
or by opening Interface Javascript console and evaluating Settings.setValue("commerce", true) and restarting.

Note: If your wallet is already set up and there is a step that asks you to not have the wallet set up yet, open the "wallet" app, help tab, and press the red "DBG: RST Wallet" button. If your wallet is set up but broken (e.g., from testing something that didn't work), such that you are prompted for a pass phrase that is never accepted, you need to:

Quit interface and delete Interface/<username.hifikey (in the AppData/Roaming/High Fidelity for the particular build you are using).

Restart Interface, set up wallet, and then press the red "DBG: RST WALLET" button as above. Now you are in a truly clean state for wallet setup.



### Wallet Setup Tests

While not logged in, open "market" app. **DONE**
Should have a green prompt at top of page that prompts you to log in: **SUCCESS toolbar and tablet**

Login button should open proper login screen (in both tablet and toolbar/HUD). **SUCCESS toolbar and tablet**

Allows both sign-in and sign-up. **SUCCESS toolbar and tablet**

Clicking X should dismiss the green prompt. **SUCCESS toolbar and tablet**

While logged in but without wallet setup, open "market" app. **DONE**

Should have a green prompt at top of page that prompts you to set up wallet: **FAIL on first attempt. SUCCESS on second and subsequent attempts including after restarting interface. Toolbar mode.**
**SUCCESS on first attempt. Tablet mode.**

Link text should open "wallet" app setup. **SUCCESS toolbar and tablet**

Clicking X should dismiss the green prompt. **SUCCESS toolbar and tablet**

Go through wallet setup, either by the above setup link, or just by opening the "wallet" app without having it already set up:

Security picture setup should work, including "tip". **SUCCESS toolbar and tablet**

Setting passphrase should work,  **SUCCESS toolbar and tablet**
including "Show passphrase" checkbox toggle  **SUCCESS toolbar and tablet** 
and prompts for too short **SUCCESS toolbar and tablet**
or not matching. **SUCCESS toolbar and tablet**


Cancel/Back and Next buttons should work as you expect. **SUCCESS toolbar and tablet**

"Open instructions for later" should open your default browser (outside of Interface) with backup instructions, **SUCCESS**

AND your default file explorer open to your .hifikey directory. **SUCCESS**

After finishing setup, you should be left at the Home tab, with 100 HFC starting balance, and one Recent Activity message. **SUCCESS**

Bonus: without having wallet set up, try to buy something (as below). Should get forced to set up wallet. **SUCCESS** Got the hifi commerce login screen.

### Buying

Open "market" app and buy something that is NOT an entity (e.g., an avatar or script, like the "Red Knight"). **DONE**

It should work as it always has (e.g., you wear the avatar or run the interface script immediately, without any commerce stuff happening). **SUCCESS**

Now search for 'test' to find some test entity-items with a non-zero price 
(There currently exists "test beachball", "test flaregun" and "test confetti gun").

Buy it.**DONE**

It should ask for confirmation. **SUCCESS**

Cancel should work **SUCCESS**, 
but confirm should bring you to a thank you page. **SUCCESS**
The links and buttons should all work as expected. **FAIL IMO** I clicked the link for the item on the thank you page and it opened the marketplace page for the ball. Clicking 'back' however took me to the marketplace entry page rather than back to the 'thank you' page. This seems incorrect.

Quickly go to your Wallet app.
You should see two new "Pending" transactions under "Recent Activity", and your balance should reflect the money spent on the purchase. **SUCCESS**

After 90 seconds, refresh the Wallet app by restarting it.
The "Wallet" app should now show the purchase under Recent Activity. **SUCCESS**

At the top of the "market" app, click the "my purchases" link. **Did not show as I had seen and done the two page tutorial earlier**
You should see a "first time use" tutorial. ** Seen earlier in test. **
Click through the tutorial. **SUCCESS**

Verify that "My Purchases" shows the purchase you made above. **SUCCESS**

All buttons/link should work, including "rez it". **SUCCESS**

Restart Interface, and open "market" => "my purchases".

You should be prompted for your passphrase. **SUCCESS**

You should then see your purchase. **SUCCESS**

Click the item name to go to the marketplace page for the item. **SUCCESS**

Buy it again.

You should be told that you already own it, **SUCCESS** 
and can buy another.  **SUCCESS**

Confirm the new purchase. **SUCCESS**

### Simulate a failed purchase:

Click "my purchases" to see both items, one of which is pending if you did this soon enough after 3.

Click the item name again to go to the marketplace page for the ite.

Click to buy it again, but with the focus still on the confirmation page, press ctrl-f. The confirmation button should turn red. **SUCCESS** Saw debug message on button

Click the red button, and go to "my purchases" to see the new purchase pending. **SUCCESS**
After 90 seconds, the word "pending" should turn turn to "failed". **FAIL** Did not see 'failed' 

***Step omitted from test instructions. Clicking on the question mark next to pending shows a popup explanation. Can be dismissed with the close button.***


### Inspecting

Repeat the "marketplace inspection" test from the standard test suite at 
https://highfidelity.testrail.net/index.php?/suites/view/39 

However, with the "commerce" setting enabled, clicking the "i" should bring up a certificate rather than the marketplace item page. **SUCCESS**

Clicking the "view in market" button of the certificate should proceed to the marketplace page for the item. **SUCCESS**


### Wallet Info Tests

Home tab should display the transactions from above. **SUCCESS**

Should be able to vertically scroll through all transactions. **SUCCESS**

Credits should be in green, debits in red. **SUCCESS**

Marketplace item names should be links that bring you to the given item page in the "market" app 
(with the market button highlighted if in toolbar/HUD mode). **SUCCESS**

Security tab should let you change passphrase, security picture, or "view backup instructions" 
(which should work as in setup tests). **SUCCESS**

Help tab should show questions that can be expended to answers.

Answers should make sense.

**What are private keys?**

Text style error. Text turns to bold after a comma in the second line of the private keys help.

Text **makes sense** maybe. ***"A private key is a secret piece of text used to decrypt code."*** Is there a better way to express this?

**Where are my private keys stored?**

Style error. Text turns to bold part way through first line.

**Makes sense.**


**What happens if I lose my passphrase?**

Should My Purchases  be enclosed in quotes ?

**Makes sense** but is scary.


**What is a security pic?**

**Makes sense.** But will users go looking for the pic file expecting to see it in the folder ?


**My HFC balance isn't what I expect it to be. Why?**

**Makes sense.**  link is incorrect and simply opens the main hifi website.


**My friend purchased my item from the Marketplace, but I still haven't received the money from the sale. Why not?

Should 'money' be replaced with 'payment' in the above line and in the help for this question?

Same link issue as above.

**Makes sense.**


**Do I get charged money if a transaction fails.**

**makes sense**


**How do I convert HFC to other currencies?**

**makes sense**


Debug clear pass and debug reset wallet buttons were active. ( did not use these buttons )


**After checking the help I clicked on 'Wallet Home' There was no recent activity showing.
and my balance had reset to zero.**

Going to market showed that I had made no purchases.

After restarting interface my balance had been restored and Recent Activity was populated with the appropriate transaction history.

Debug clear pass and debug reset wallet buttons remained active after restart.

143088-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-10-57

143088-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-11-51

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-19-58

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-26-22

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-30-31

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-35-39

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-35-46


144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-45-21

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_02-45-26

144900-hifi-snap-by-piper-peppercorn-on-2017-10-10_03-10-29

**Comment by Nex-Pro** [comment]
@zfox23 ^

**Comment by Nex-Pro** [comment]
Let me know if I need to retest anything.

**Comment by howard-stearns** [comment]
Thanks, Piper! Good testing!

**Comment by Nex-Pro** [comment]
@howard-stearns You have to laugh when the reason for a fail is the absence of a fail

**Comment by zfox23** [comment]
Hey @Nex-Pro: Could you please re-test the section labelled **Wallet Setup Tests** after the latest build completes? Thanks.

A couple other notes:
- I'm modifying the test case you failed regarding "Did not see 'failed'". Instead of showing "failed," the item should simply disappear from the list. There's no need to re-test this.
- We're going to take a holistic look at the behavior of the "back" button, because we agree that it's confusing. No need to re-test anything here; that change will come in a different PR.

**Comment by Nex-Pro** [comment]
OK !  @zfox23

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4007/HighFidelity-Beta-PR11555-8d0d9a159fd35514777f8e22af700662bde1d595.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4007/HighFidelity-Beta-PR11555-8d0d9a159fd35514777f8e22af700662bde1d595.exe

**Comment by Nex-Pro** [comment]
T E S T I N G

**Comment by Nex-Pro** [comment]
### QA for #11555

## Result: PASS

Testing platform:
Intel i7 workstation.
16gb ram
gtx 1070
Win10.



Test Plan:

Note: Currently, you must manually enable "commerce" by adding "commerce": true, in your Interface.json (with Interface not running), **DONE**
or by opening Interface Javascript console and evaluating Settings.setValue("commerce", true) and restarting.



### Wallet Setup Tests

While not logged in, open "market" app. **DONE**
Should have a green prompt at top of page that prompts you to log in: **SUCCESS toolbar and tablet**

Login button should open proper login screen (in both tablet and toolbar/HUD). **SUCCESS toolbar and tablet**

Allows both sign-in and sign-up. **SUCCESS toolbar and tablet**

Clicking X should dismiss the green prompt. **SUCCESS toolbar and tablet**

While logged in but without wallet setup, open "market" app. **DONE**

Should have a green prompt at top of page that prompts you to set up wallet: **SUCCESS toolbar and tablet**

Link text should open "wallet" app setup. **SUCCESS toolbar and tablet**

Clicking X should dismiss the green prompt. **SUCCESS toolbar and tablet**

Go through wallet setup, either by the above setup link, or just by opening the "wallet" app without having it already set up:

Security picture setup should work, including "tip". **SUCCESS toolbar and tablet**

Setting passphrase should work,  **SUCCESS toolbar and tablet**
including "Show passphrase" checkbox toggle  **SUCCESS toolbar and tablet** 
and prompts for too short **SUCCESS toolbar and tablet**
or not matching. **SUCCESS toolbar and tablet**


Cancel/Back and Next buttons should work as you expect. **SUCCESS toolbar and tablet**

"Open instructions for later" should open your default browser (outside of Interface) with backup instructions, **SUCCESS** opened file:///C:/Users/NexPro/AppData/Roaming/High%20Fidelity%20-%20PR11555/Interface/backup_instructions.html

AND your default file explorer open to your .hifikey directory. **SUCCESS**

After finishing setup, you should be left at the Home tab, with 100 HFC starting balance, and one Recent Activity message. **SUCCESS** 100 HFC ( I'm rich ) 1 pending transaction.


Recent activity updated after reopening wallet.


Feedback: 

Might be good to have a refresh button on the wallet home page.

Cannot log out of wallet. Might be nice to be able to.

**Comment by Nex-Pro** [comment]
Wallet state persisted correctly after restarting interface.

**Comment by Nex-Pro** [comment]
@zfox23 ^

**Comment by zfox23** [comment]
Thank you, @Nex-Pro! I've forwarded your feedback.

**Pull request merged**
