### PR TITLE
Prefer HTTPS links in readme/build docs

### PR DESCRIPTION
**Pull request by thoys**
## QA
Please test if the links are correct in the following changed files:
 - [ ] BUILD.md
 - [ ] BUILD_OSX.md
 - [ ] BUILD_WIN.md
 - [ ] README.md

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d3be1607d7160c4add337a0a7f20f053f02c259 available at: https://gist.github.com/564dd732484e8f94b5192eafcd847da9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-1d3be16.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-1d3be16.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8911d14e622931c27fea6093b4e6269458781ae available at: https://gist.github.com/564dd732484e8f94b5192eafcd847da9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-c8911d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-c8911d1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f42f8cf6025c646447974203a3745ae541a9ceea available at: https://gist.github.com/564dd732484e8f94b5192eafcd847da9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-f42f8cf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9793-f42f8cf.dmg

**Comment by Nex-Pro** [comment]
### PASS

All links seem fine.

**Pull request merged**
