### PR TITLE
Case 20908: Fix SendAsset.qml has wrong color

### PR DESCRIPTION
**Pull request by danteruiz**
Fix SendAsset.qml has wrong color

Ticket - https://highfidelity.manuscript.com/f/cases/20908/SendAsset-qml-has-incorrect-background-color-after-PR14805

### CODE REVIEW

**Comment by danteruiz** [comment]
Test Plan-
There are three cases where a user can enter SendAsset:

    1. Through Wallet -> Send Money
        1. The background here is supposed to be a purple/blue gradient
    2. Through Inventory -> Gift
        2. The background here is supposed to be white
    3. Through the Scripting Interface or by using this tip jar https://hifi-content.s3.amazonaws.com/milad/ROLC/d/ROLC_High-Fidelity/02_Organize/O_Projects/hifi-scripts/tipJar/entityResources/entity/tipJarSpawner.js
        3. The background here is supposed to be grey

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16989/HighFidelity-Beta-PR14842-12ce802.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16989/HighFidelity-Beta-PR14842-12ce802.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16989/HighFidelity-Beta-Interface-PR14842-12ce802.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16989/HighFidelity-Beta-PR14842-12ce802.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16989/HighFidelity-Beta-Interface-PR14842-12ce802.exe

**Pull request merged**
