### PR TITLE
[DNM] WelcomeWagon entry point

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by themelissabrown** [comment]
Internal QA only at this point

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/948/HighFidelity-Beta-PR10767-257f04f24360abaed22427d56bc00bf02ea42342.dmg

**Comment by thoys** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/951/HighFidelity-Beta-PR10767-257f04f24360abaed22427d56bc00bf02ea42342.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/951/HighFidelity-Beta-PR10767-257f04f24360abaed22427d56bc00bf02ea42342.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/952/HighFidelity-Beta-PR10767-12ce9bfae25cf58c3a81dd8df0b31dd76df1cce9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/952/HighFidelity-Beta-PR10767-12ce9bfae25cf58c3a81dd8df0b31dd76df1cce9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1119/HighFidelity-Beta-PR10767-00683f24b6560cc1ad5dae84620480126af68b6d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1119/HighFidelity-Beta-PR10767-00683f24b6560cc1ad5dae84620480126af68b6d.dmg

**Comment by ZappoMan** [comment]
Why are we changing the default entry point in the C++ code? why isn't this something we're handling with the metaverse?

**Comment by thoys** [comment]
Good point, lets make a FogBugz on that. We will redirect welcome to WelcomeWagon soon, this is just a build to test it out.

**Comment by BillWindwalker** [comment]
Anyone else seeing the humor in this post

**Comment by birarda** [comment]
We already have the ability to do this on the DB side, by "re-pointing" welcome. AFAIK that's the point of the welcome place name.

Additionally, tutorial changes should be made as PRs to this repository - https://github.com/highfidelity/hifi-tutorial/

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1140/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1140/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.dmg

**Comment by thoys** [comment]
just changing the base branch to stable, I think Jenkins merges the last base branch while it builds.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1143/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1143/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.dmg

**Comment by thoys** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1302/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1302/HighFidelity-Beta-PR10767-c0da566d1a8613cfe9547ebcdc4f80bc1d3b05d1.dmg

**Pull request closed without merging**
