### PR TITLE
Fix paths to various Snapshot resource files

### PR DESCRIPTION
**Pull request by zfox23**
This fixes [MS12292](https://highfidelity.fogbugz.com/f/cases/12292/No-shutter-sound-after-taking-a-snapshot) and also fixes a couple of other problems with the Snapshot app (the loading GIF and "image not found" image).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Open the Snapshot app. Set up your Snapshot path if you haven't already. Click the red button.
    i. Verify that you hear a snapshot sound.
2. Set the camera to capture "Still + GIF". Click the red button. Wait for the Snapshot app to re-appear.
    i. Verify that you quickly see a blue "loading" GIF where the GIF snapshot eventually appears.
3. Delete the snapshots that you just took from your local disk. Close and re-open the Snapshot app.
    i .Verify that you see a "Could not find last image taken" image.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8871/app_12924_PR_95ee3c82f553965bc310f38f0831ba7004d03d9f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8871/HighFidelity-Beta-PR12924-95ee3c82f553965bc310f38f0831ba7004d03d9f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8871/HighFidelity-Beta-Interface-PR12924-95ee3c82f553965bc310f38f0831ba7004d03d9f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8871/HighFidelity-Beta-PR12924-95ee3c82f553965bc310f38f0831ba7004d03d9f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8871/HighFidelity-Beta-Interface-PR12924-95ee3c82f553965bc310f38f0831ba7004d03d9f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
