### PR TITLE
fix throttling when Interface is not in focus

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

*Make sure vsync is enabled!*

- Go somewhere with enough going on that your render rate drops below 60. (I use 
[this script](https://github.com/highfidelity/hifi/files/273408/stress.txt), from @jherico; by looking at more/less entities, I can modulate the render rate.)
- Ensure the render rate does not go from 60fps to 30fps. It should be capable of sustaining intermediate values, around 45fps. (This is assuming your monitor has a vsync target of 60fps).
- Ensure the GUI remains responsive (mouse clicks, etc.) and that you are able to start/stop scripts still.
- Ensure that throttling works. When on, in Desktop mode, when Interface does not have focus, it should drop to 15fps.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7dabce9cff02f74db3a9b737ca98b06708d57580 available at: https://gist.github.com/41a9e9e5a9c15a60d78b14001b85a778<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7962.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7962.dmg

**Comment by Nex-Pro** [comment]
##PR #7962 

**Testing Architecture:** Desktop PC
**CPU:**  4.0 ghz i7
**Ram:** 16gb
**GPU:** Nvidia gtx770 2gb
**Testing OS:** Win 10 64 pro

Monitor ( monitor1 ) was set to 60hz.
Minimum desktop FPS set at 60 in interface.
stress.js was run and I observed the result of changing focus to another app on my second monitor.

Interface maintained close to 60fps in focus ( level of detail was being adjusted automatically )
Interface dropped to ~15 FPS when not in focus.

Repeated the above several times.

In addition I grabbed cpu usage snapshot of the windows resource monitor in cpu view mode.

**This is with interface running stress.js and not in focus.**

pr7962_stress_test_cpu_out_of_focus

**Comment by OmegaHeron** [comment]
Tested as well and it resolves fogzid:629 Thanks Zach.

**Pull request merged**
