### PR TITLE
address bar ux

### PR DESCRIPTION
**Pull request by howard-stearns**
initial version of sizing and white-on-white-with-drop-shadow

DNM for now because it makes up announcement data in this version, so that I can test on mac and windows.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: aed762e986ba38fd42de41274050725e842e6c7e available at: https://gist.github.com/18d152a3d32a029a83e731bbbec02f2d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-aed762e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-aed762e.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: aed762e986ba38fd42de41274050725e842e6c7e available at: https://gist.github.com/18d152a3d32a029a83e731bbbec02f2d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-aed762e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-aed762e.dmg

**Comment by howard-stearns** [comment]
Having a lot of trouble with mac. Can't run local build (master or this pr), jenkins download doesn't open.   I'm merging so that we can get to a consistent state.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ad8f4d985ed7727f9d8cf76bf5d7fec5935c439 available at: https://gist.github.com/18d152a3d32a029a83e731bbbec02f2d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-0ad8f4d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10315-0ad8f4d.dmg

**Pull request merged**
