### PR TITLE
test build

### PR DESCRIPTION
**Pull request by MiladNazeri**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22163/HighFidelity-Beta-PR16413-93ce2ae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22163/HighFidelity-Beta-Interface-PR16413-93ce2ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22163/HighFidelity-Beta-PR16413-93ce2ae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22163/HighFidelity-Beta-Interface-PR16413-93ce2ae.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22163/HighFidelity-Beta-PR16413-93ce2ae.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22163/HighFidelity-Quest-Beta-PR16413-93ce2ae.apk)

**Pull request closed without merging**
