### PR TITLE
Introducing group culling to avoid the avatar model to be partially culled

### PR DESCRIPTION
**Pull request by samcake**
This work introduces 2 more flags on the render item Key:
- Meta Cull Group which allows for a meta render item to act as the sole cull test for it and all its sub items
- Sub Meta Culled that the sub items of Cull GRoup Meta item should carry in order to not be fetched twice (once by the Meta and once by itself) during the fetch/culling process.

Taking advantage of this new feature we can now tag the Avatar meta render item and the render items of its model appropriately so that the avatar model parts are always all visible or culled but not partially

## TEST PLAN ##
Using current master first
In desktop mode

in an heavy domain (for example Dev-welcome)
wear an avatar model with several parts, for example [Fighter](http://mpassets.highfidelity.com/ab466729-31da-4b4c-a33c-366f7c1d38e5-v1/M_MMAFig.fst)
In 3rd person camera back up as much as possible from the avatar

With developer menu enable, start the LOD dialog in developer/render/LOD...
Set the LOD to manual by checking "Manually adjust level of detail"
Now move the cursor of the level of detail slowly to the right and notice the smaller parts of the avatar disappearing partially

master 7849
This behavior is what we want to address with this new feature.

- Now redo the exact same experience with this PR build and you should never see the avatar model partially, always complete.

This PR

- Also check that when you pick the LOD level bad enough, the avatar disappear completely as one

- Do the same experience with Another person in the domain, observing them from a distance validating that the same behavior also applies correctly for other avatars.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7178/app_12399_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7178/HighFidelity-Beta-PR12399-6357f36a97b4475c0d87fe69853f4d34837f26a1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7178/HighFidelity-Beta-PR12399-6357f36a97b4475c0d87fe69853f4d34837f26a1.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing for PR#12399. PASSED.

**Pull request merged**
