### PR TITLE
Fix HMD strafe locomotion animation.

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Handle HMD in input vars in Rig.cpp, remove buggy json transitions between normal/HMD strafe states, and use isNotMoving to leave HMD strafe states.

https://highfidelity.atlassian.net/browse/DEV-2741

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by DouglasWilcox** [comment]
TEST NOTES:  You can use my sandbox with mirror to test this:
https://hifi-content.s3.amazonaws.com/doug/test/douglandia_newmirror_sitcubes.zip

Verify that locomotion in desktop still works correctly, and that now in HMD you see the expected side strafe steps with no floating.  The floating was caused by stategraph thrash going back and forth between the desktop strafe and hmd strafe states.  If you use developer/show_anim_stats you should see a relatively clean report of states that doesn't thrash every other frame.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22498/HighFidelity-Beta-PR16486-f9f28fc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22498/HighFidelity-Beta-Interface-PR16486-f9f28fc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22498/HighFidelity-Beta-PR16486-f9f28fc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22498/HighFidelity-Quest-Beta-PR16486-f9f28fc.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22498/HighFidelity-Beta-PR16486-f9f28fc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22498/HighFidelity-Beta-Interface-PR16486-f9f28fc.exe

**Pull request merged**
