### PR TITLE
RC75.1 - Add PolyLine/PolyVox to entity list/properties types

### PR DESCRIPTION
**Pull request by dback2**
Addresses:
https://highfidelity.fogbugz.com/f/cases/19878

Test Plan:

- Enter Interface in desktop mode into your sandbox
- Open the scripting console under Developer menu -> Scripting
- Enter the following lines into the console:
Entities.addEntity({type: "PolyLine", name: "PolyLine"});
Entities.addEntity({type: "PolyVox", name: "PolyVox"});
- Open Create to the entity list and verify a PolyVox and PolyLine entity are there
- Verify the PolyVox entity filters out when unchecking PolyVox in the All Types dropdown, and filters back in when rechecking it
- Verify the PolyLine entity filters out when unchecking PolyLine in the All Types dropdown, and filters back in when rechecking it

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15159/HighFidelity-Beta-PR14403-e6febc7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15159/HighFidelity-Beta-PR14403-e6febc7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15159/HighFidelity-Beta-Interface-PR14403-e6febc7.dmg

**Comment by jakram** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15166/HighFidelity-Beta-PR14403-158ce5d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15166/HighFidelity-Beta-PR14403-158ce5d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15166/HighFidelity-Beta-Interface-PR14403-158ce5d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15166/HighFidelity-Beta-PR14403-158ce5d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15166/HighFidelity-Beta-Interface-PR14403-158ce5d.exe

**Pull request merged**
