### PR TITLE
make legacy ignoreForCollision property work right

### PR DESCRIPTION
**Pull request by sethalves**
- make legacy ignoreForCollision entity property work right

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/12985/If-you-get-an-entity-s-ignoreForCollisions-property-value-you-probably-get-the-dynamic-property-value

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8501/HighFidelity-Beta-PR12789-a5668222cd88c624a7a4ad562a5dec49d602ae28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8501/HighFidelity-Beta-PR12789-a5668222cd88c624a7a4ad562a5dec49d602ae28.exe

**Comment by conklin94122** [comment]
QA: If this does need testing, check the age of the installers. If they're more than 3-4 days old, comment "please build this" to rebuild.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9806/HighFidelity-Beta-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9806/HighFidelity-Beta-Interface-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.exe

**Comment by QliCknox** [comment]
Please build this

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9967/HighFidelity-Beta-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9967/HighFidelity-Beta-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9967/HighFidelity-Beta-Interface-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9967/HighFidelity-Beta-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9967/HighFidelity-Beta-Interface-PR12789-f3b051d7c835ada1afcdb2093232da11f3dd3381.exe

**Comment by AndrewMeadows** [comment]
**Test Plan**

As far as I can tell, these test instructions should work the same in this PR and in hifi/master.  This change is not actually fixing a bug per-se, but just making the C++ code make more sense.  The typo in the code does not actually introduce a problem behavior.

**(1)** Run the script below:
```
// create a collisionless object using the legacy "ignoreForCollisions" property name
var forward = Quat.getFront(MyAvatar.orientation);
var forwardOffset = Vec3.multiply(2.0, forward);
var objectPosition = Vec3.sum(MyAvatar.position, forwardOffset);
var LIFETIME = 600; // seconds
var properties = {
    type: "Box",
    name: "CollisionlessBox",
    position: objectPosition,
    dimensions: { x: 0.8, y: 0.8, z: 0.8 },
    color: { red: 255, green: 255, blue: 0 }, // yellow
    ignoreForCollisions: true,
    lifetime: LIFETIME
};
var entityId = Entities.addEntity(properties);
```
--> Verify the object shows up **collisionless**, but not **dynamic**.

**(2)** Restart the entity-server, or the entire domain+assignment clients, before the object is deleted for expired lifetime (600 seconds = 10 min).
--> Verify the object is still **collionsless** after the domain reloads and not **dynamic**.

**Comment by AndrewMeadows** [comment]
These failure issues may be bugs, but I would expect them to reproduce in `hifi/master`.

**Comment by sethalves** [comment]
please check master for these behaviours.  If it's the same, consider this a pass.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10311/HighFidelity-Beta-PR12789-97b3fdf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10311/HighFidelity-Beta-PR12789-97b3fdf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10311/HighFidelity-Beta-Interface-PR12789-97b3fdf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10311/HighFidelity-Beta-PR12789-97b3fdf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10311/HighFidelity-Beta-Interface-PR12789-97b3fdf.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Cube created from script stays collisionless and does not become dynamic when domain server is restarted

**Pull request merged**
