### PR TITLE
Commerce: P2P Transfer Iteration 1

### PR DESCRIPTION
**Pull request by zfox23**
DNM until the corresponding backend component is merged, and the Commerce team tests the crap out of this.

Note that the "Avatar Selector logic" in `wallet.js` is largely copied from Dave's work in `pal.js`, with slight modifications. I didn't spend the time to make that a library (or something).

### Prerequisites
- The client running on Machine A will henceforth be referred to as Client A, etc.
- Testing this plan in HMD *is not currently required*. Testing this feature in HMD *will be required* once the UI is pixel-perfect.
- Run Sandbox and Interface on both machines.
- Sign into High Fidelity on both Clients A and B. Ensure that the wallets are setup on both accounts.
- Connect both clients to Sandbox A.
- Ensure that Avatar A and Avatar B are *not* Connections.
- Ensure that Avatar A and Avatar B have unique display names.
- Ensure that Avatar B's availability is "Appear Offline". If you had to change Avatar B's availability from something else to "Appear Offline," restart Interface after the change.
- Ensure that Avatar A's availability is "Everyone".
    - Use the PAL to change availability.

#### Sending Money to Someone Nearby
1. (Until noted, perform the steps below on Client A.) Open the Wallet.
2. Click the "Send Money" tab.
3. Click the Security Pic in the top right, verifying that the Security Pic popup appears. Close the popup.
4. Click the "Home" tab, verifying that you're taken back to Wallet Home.
5. Click the "Send Money" tab again.
6. Click the "Connection" button.
7. Verify that you do not see Avatar B in the list of Connections, but that you do see a list of Connections (as long as you have at least one)
8. Click the "x" button in the top right of the popup.
9. Click the "Nearby" button.
10. Using your mouse, click on the orb that appears overlaid on top of Avatar B. In the wallet, verify that you see Avatar B's display name.
11. Click the "Next" button.
12. Verify that you see a screen whose title is "Send To". Verify that you see Avatar B's display name on this screen.
13. Click the "CHOOSE" button.
14. Using your mouse, click on the orb that appears overlaid on top of Avatar B. In the wallet, verify that you see Avatar B's display name.
15. Click the "Next" button.
16. Verify that you see a screen whose title is "Send To". Verify that you see Avatar B's display name on this screen.
17. Press the "SEND" button. Verify that you remain on the same screen, except the AMOUNT field is now in focus and highlighted in red. Verify that you see an error message below the AMOUNT field.
18. Set the "AMOUNT" to 1 HFC. Set the "Optional Message" to something very long that bumps up against the character limit.
19. Press the "SEND" button. After a moment, verify that you see a "Payment Failed" screen.
20. *On Client B*, set Avatar B's availability to "Everyone".
21. *On Client A*, press the "RETRY" button. After a moment, verify that you see a "Payment Sent" screen with accurate information (the correct display name, 1 HFC sent, and your optional message).
22. On both clients, navigate to Wallet Home. Verify that you see the above transaction at the top of your Recent Activity.
23. Make a connection between Avatar A and Avatar B
    - Hold "X" on your keyboard to have your avatar hold their hand out for a handshake
    
#### Sending Money to a Connection
1. (Until noted, perform the steps below on Client B.) Open the Wallet.
2. Click the "Send Money" tab.
3. Click the "Connection" button.
4. Find Avatar A in the Connections list, click on their entry in the list, then click "CHOOSE".
5. Verify that you see a screen whose title is "Send To". Verify that you see Avatar A's username and profile picture on this screen.
6. Set the "AMOUNT" to 1 HFC. Set the "Optional Message" to something very long that bumps up against the character limit.
7. Press the "SEND" button. After a moment, verify that you see a "Payment Sent" screen with accurate information (the correct username, 1 HFC sent, and your optional message).
8. On both clients, navigate to Wallet Home. Verify that you see the above transaction at the top of your Recent Activity.
9. From Client A, click on Avatar B's username in the Recent Activity entry from (8). Verify that you see a browser window appear, pointed at Avatar B's HiFi user page.
10. On Machine B, quit Client B. On Client A, repeat all of the above steps. Verify that you achieve the same results.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6232/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6232/HighFidelity-Beta-PR12151-464bbe5d438496b971421cf5d080a19efbdd14a2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6232/HighFidelity-Beta-PR12151-464bbe5d438496b971421cf5d080a19efbdd14a2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6236/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6236/HighFidelity-Beta-PR12151-c216144015168521bc405ccdc698b8fe4c6aacaa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6236/HighFidelity-Beta-PR12151-c216144015168521bc405ccdc698b8fe4c6aacaa.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6289/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6289/HighFidelity-Beta-PR12151-f7ed8c10fa85b37f480e71193cc5a961aaf9039a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6289/HighFidelity-Beta-PR12151-f7ed8c10fa85b37f480e71193cc5a961aaf9039a.dmg

**Comment by zfox23** [comment]
[Wallet UI to pay nearby](https://trello.com/c/WYtXNyWB/443-wallet-ui-to-pay-nearby)

**Comment by zfox23** [comment]
[Wallet UI to pay connection](https://trello.com/c/OLaebLzA/447-wallet-ui-to-pay-connection)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6331/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6331/HighFidelity-Beta-PR12151-6b90ceaeb4c7573f8632fc82ab04b7f1d919d3ff.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6331/HighFidelity-Beta-PR12151-6b90ceaeb4c7573f8632fc82ab04b7f1d919d3ff.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6339/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6339/HighFidelity-Beta-PR12151-d64b35729fc76db1ae74cef8950d897050675842.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6339/HighFidelity-Beta-PR12151-d64b35729fc76db1ae74cef8950d897050675842.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6346/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6347/app_12151_PR.apk

**Comment by zfox23** [comment]
[transaction history wording and formatting](https://trello.com/c/DQKpNWVz/450-transaction-history-wording-and-formatting)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6347/HighFidelity-Beta-PR12151-8cc427a3740c8fdc625771cc32ad08c930715688.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6347/HighFidelity-Beta-PR12151-8cc427a3740c8fdc625771cc32ad08c930715688.dmg

**Comment by marko8904** [comment]
build this please

**Comment by zfox23** [comment]
@marko8904 this was a legit failure due to a new warning - talking to @davidkelly about the fix (it's his code)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6348/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6352/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6352/HighFidelity-Beta-PR12151-e700ff91d0b9e6125093b26e05d463d1de4f7067.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6352/HighFidelity-Beta-PR12151-e700ff91d0b9e6125093b26e05d463d1de4f7067.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6378/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6378/HighFidelity-Beta-PR12151-1d747bc0e4aa955cf5d9f927565dc85fb16b0be8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6378/HighFidelity-Beta-PR12151-1d747bc0e4aa955cf5d9f927565dc85fb16b0be8.dmg

**Comment by zfox23** [comment]
QA'd internally; will be comprehensively tested at RC time

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6421/app_12151_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6421/HighFidelity-Beta-PR12151-1d747bc0e4aa955cf5d9f927565dc85fb16b0be8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6421/HighFidelity-Beta-PR12151-1d747bc0e4aa955cf5d9f927565dc85fb16b0be8.dmg

**Pull request merged**
