### PR TITLE
Case 21792: don't ignore updates that originate from entityPropertiesTool itself [RC81]

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/21792

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18257/HighFidelity-Beta-PR15224-c7fc089.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18257/HighFidelity-Quest-Beta-PR15224-c7fc089.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18257/HighFidelity-Beta-PR15224-c7fc089.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18257/HighFidelity-Beta-Interface-PR15224-c7fc089.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18257/HighFidelity-Beta-PR15224-c7fc089.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18257/HighFidelity-Beta-Interface-PR15224-c7fc089.exe

**Comment by jakram** [comment]
Currently testing

**Pull request merged**
