### PR TITLE
CR for Job #21184 - Design Icon for fingerpaint. https://worklist.net/21168

### PR DESCRIPTION
**Pull request by Nex-Pro**
Code Review for Job #21184 - Workitem available at https://www.worklist.net/21184

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by huffman** [comment]
Has the use of the new images been QA'd?

**Comment by Nex-Pro** [comment]
@huffman I have no idea

**Comment by huffman** [comment]
@PhilipRosedale Does this pass QA? It looked you created the worklist job, so you would probably know best.

**Comment by themelissabrown** [comment]
I coordinated with Alan today. The worklist job has been marked as done.

**Pull request closed without merging**
