### PR TITLE
Ray-pick blacklisting

### PR DESCRIPTION
**Pull request by ericrius1**
This PR adds support for filtering out, or blacklisting, entities that one does not wish to be included in a ray pick. One example of how this may be used will be for creating collaborative, in-world UIs, where the content-creator wishes to create a semi-transparent panel to back the UI components visible to all users, but does not want such a panel to get in the way of users distance grabbing, or shooting, or interacting in any other way with objects behind that panel.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e7dfc07c0568616f06d66c0276337166cc03488 available at: https://gist.github.com/8dfce49560649e2f597b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6738.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6738.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 340c066b5ccba6a40bfd11d02604b554cb8ace2f available at: https://gist.github.com/8dfce49560649e2f597b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6738.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6738.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e95ca7947d54f9f99e46c44398d0fcadaf5fedc available at: https://gist.github.com/8dfce49560649e2f597b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6738.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6738.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 542d8a4b6cb292bc1e5bdd40c8b69675345c665d available at: https://gist.github.com/8dfce49560649e2f597b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6738.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6738.dmg

**Comment by ZappoMan** [comment]
:+1:

**Comment by imgntn** [comment]
lgtm

**Pull request merged**
