### PR TITLE
case 21873: add a button to Avatar panel to lock or unlock wearables. allow grabb…

### PR DESCRIPTION
**Pull request by sethalves**
- add a button to Avatar panel to lock or unlock wearables
- allow other avatars to grab / adjust your unlocked wearables

https://highfidelity.manuscript.com/f/cases/21873/v-81-Add-Grabbable-Checkbox-to-Wearables-in-Avatar-App
https://highfidelity.manuscript.com/f/cases/20773/Allow-user-to-adjust-try-on-wearables-on-other-avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18315/HighFidelity-Beta-PR15241-1ddf8ae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18315/HighFidelity-Beta-Interface-PR15241-1ddf8ae.dmg

**Comment by sethalves** [comment]
build this please, you cantankerous automaton

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18321/HighFidelity-Beta-PR15241-46a69aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18321/HighFidelity-Beta-Interface-PR15241-46a69aa.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18321/HighFidelity-Beta-PR15241-46a69aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18321/HighFidelity-Quest-Beta-PR15241-46a69aa.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18321/HighFidelity-Beta-PR15241-46a69aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18321/HighFidelity-Beta-Interface-PR15241-46a69aa.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18327/HighFidelity-Beta-PR15241-d5ba2db.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18327/HighFidelity-Quest-Beta-PR15241-d5ba2db.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18327/HighFidelity-Beta-PR15241-d5ba2db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18327/HighFidelity-Beta-Interface-PR15241-d5ba2db.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18327/HighFidelity-Beta-PR15241-d5ba2db.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18327/HighFidelity-Beta-Interface-PR15241-d5ba2db.exe

**Pull request merged**
