### PR TITLE
renaming of marketplace icon/window to examples

### PR DESCRIPTION
**Pull request by birarda**
- renames the "Marketplace" icon/window in default scripts to "Examples"

### CODE REVIEW

**Comment by birarda** [comment]
This won't be testable until the server-side pull is merged that updates the routing on that end. I will post here when it is ready.

**Comment by hifi-gustavo** [comment]
Build console output for commit: eaa0ba9e32050e606be26d6822b294477dc8649f available at: https://gist.github.com/35d405a813fe5289766da73bdf36ec53<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.dmg

**Comment by birarda** [comment]
Okay, server-side change is ready. This is testable now.

**Comment by birarda** [comment]
We will need to test that the user agent change doesn't screw anything up.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6df7ddeb16ca6f0c7658449643c75ce26ffdf5f2 available at: https://gist.github.com/35d405a813fe5289766da73bdf36ec53<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.dmg

**Comment by birarda** [comment]
Tested edit.js to confirm that the QML->C++ communication was unaffected by the user agent change.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e83ed5cccc08961b7d140d97cdac4d5a9ab7dbf available at: https://gist.github.com/35d405a813fe5289766da73bdf36ec53<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7545.dmg

**Comment by kevinmthomas-carpool** [comment]
Successful smoke test on Mac OS X El Capitan.  Tested on Music domain and unloaded all scripts and manually added edit.js for the PR build and was able to successfully add a new model from my Dropbox account, successfully manipulate fbx and then successfully deleted it.  Checked frame rate against current Mac build 4610 and was able to maintain exact frame rate on the PR build as the current release build which on my Mac was 40 frames per second.

**Pull request merged**
