### PR TITLE
Create ubuntu specific documentation.

### PR DESCRIPTION
**Pull request by elmanytas**
It is based on https://forums.highfidelity.com/t/how-to-compile-a-stable-build-of-the-linux-server-stack-on-ubuntu-16-04-lts/11528 and tested yesterday.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
Ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1692/HighFidelity-Beta-PR10967-f692a2e4bf7f202fb67ae34111e4afc5ccc58778.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1692/HighFidelity-Beta-PR10967-f692a2e4bf7f202fb67ae34111e4afc5ccc58778.exe

**Comment by OmegaHeron** [comment]
Pass in that this is a viable guide for compiling on Ubuntu with Qt5.6.x.  Of course, there's the looming specter of Qt5.9 so this will need an update when/if Qt5.9 becomes mandatory.

**Pull request merged**
