### PR TITLE
switchable placeholder for domain-connection failure, currently a modal

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes https://highfidelity.fogbugz.com/f/cases/1978/Do-not-show-GoTo-dialog-automatically-when-not-connected-to-a-domain per discussion with Ryan/Alan.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a3c14683ef92cc4bb244fc2ed5edfa41c509980 available at: https://gist.github.com/87c6218c9e5fabbc4d1fc77ea75a783c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8836-7a3c146.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8836-7a3c146.dmg

**Comment by RyanDowne** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a3c14683ef92cc4bb244fc2ed5edfa41c509980 available at: https://gist.github.com/87c6218c9e5fabbc4d1fc77ea75a783c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8836-7a3c146.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8836-7a3c146.dmg

**Comment by RyanDowne** [comment]
This works as described.

**Pull request merged**
