### PR TITLE
try again on queryAACube

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that made queryAACube wrong on newly uploaded model-entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- upload a new model entity
- make sure you can select the entity with edit.js

**Comment by sethalves** [comment]
https://app.asana.com/0/26225263936266/99753934970045/f

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8a03b725fc5ff06042bd9d0c7eec7f6e82fad0d available at: https://gist.github.com/d0eb8e99ca23df12257a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7350.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7350.dmg

**Comment by howard-stearns** [comment]
Still no good. It works on initial upload, but not after that.

**Comment by howard-stearns** [comment]
wait a minute, I might be wrong...

**Comment by howard-stearns** [comment]
mine was pilot error. This pr does appear to work.

**Pull request merged**
