### PR TITLE
Spawn the Spectator Camera facing the user; New icons; Sound

### PR DESCRIPTION
**Pull request by zfox23**
This PR will be code reviewed normally, but tested as part of the overall test plan on #10875.

### CODE REVIEW

**Comment by zfox23** [comment]
[Camera when rezzed should face you.](https://trello.com/c/6DfXoQw1/248-camera-when-rezzed-should-face-you)

**Comment by zfox23** [comment]
@Nex-Pro ?

**Comment by Nex-Pro** [comment]
@zfox23 I guess we don't see the reasoning for this but I'm used to filming scenes not me !  lol

Also feels a little strange to see w: in first place on line 71 ( I know it doesn't affect anything )

**Comment by Nex-Pro** [comment]
This is going to annoy people if they don't have the option to have it face forward when opened.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1632/HighFidelity-Beta-PR10958-483e2d1417fcb67703df6b0ba3adcc0bfc15abde.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1632/HighFidelity-Beta-PR10958-483e2d1417fcb67703df6b0ba3adcc0bfc15abde.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1652/HighFidelity-Beta-PR10958-dc1b4b5324dbf5b590ade4101b89073f3e2151e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1652/HighFidelity-Beta-PR10958-dc1b4b5324dbf5b590ade4101b89073f3e2151e9.exe

**Pull request merged**
