### PR TITLE
make room for keyboard and help in SendAsset

### PR DESCRIPTION
**Pull request by howard-stearns**
https://highfidelity.fogbugz.com/f/cases/13003/Move-Submit-button-above-the-Keyboard-in-Send-Money-window-in-VR

### CODE REVIEW

**Comment by howard-stearns** [comment]
**Test plan**:

There are four situations to check: 
- Wallet => Send Money => Nearby
- Wallet => Send Money => Connection
- (Wallet or Marketplace) => My Purchases => (item menu) => Gift => Nearby
- (Wallet or Marketplace) => My Purchases => (item menu) => Gift => Connection

In each case make sure everything is useable in Desktop and HMD.
The particular things changed are that in HMD, if you bring up the keyboard (by selecting any text box on this screen):
- The cancel and submit buttons were below the keyboard and not visible. Now they are.
- In the nearby case, there is a checkbox to show the effect, and that checkbox has a help link (a question mark) that brings up a letterbox help display that was obscured by the keyboard. Now the keyboard automatically lowers when you click help.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13794/HighFidelity-Beta-PR14185-30971cd.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13794/HighFidelity-Beta-PR14185-30971cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13794/HighFidelity-Beta-Interface-PR14185-30971cd.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by rickcarr044** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14091/HighFidelity-Beta-PR14185-30971cd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14091/HighFidelity-Beta-PR14185-30971cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14091/HighFidelity-Beta-Interface-PR14185-30971cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14091/HighFidelity-Beta-PR14185-30971cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14091/HighFidelity-Beta-Interface-PR14185-30971cd.exe

**Comment by qlihifitest** [comment]
Currently testing

**Comment by qlihifitest** [comment]
@conklin94122 Pass
Wallet and marketplace function as expected. 
Cancel and submit are now visible. 
Keyboard now lowers when help is selected. 
No defective behavior was found while doing smoke test.

**Pull request merged**
