### PR TITLE
Fargrab improvement

### PR DESCRIPTION
**Pull request by amvmoody**
# Info
- added a min and max reach zone that applies a steady velocity for pushing and pulling.
- added haptic feed back for added zones.
- HMD Required

# QA

## Setup
- install the version of hifi that is auto built from this PR.

## Steps - Single Person
1. Far grab an object and hold hand close to center of your chest. Observe that your hand controller now vibrates and reals in the garbed object.
2. Far grab an object and hold hand all the way out, the last ~10% of you reach should push the object forward. Observe that your hand controller now vibrates and pushes out the garbed object.
3. Test grabbing, rotating ect. and make sure existing behavior is not broken.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/285/HighFidelity-Beta-PR10584-52d29072c7e279c5873d9ed623c4787d5f685a9f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/285/HighFidelity-Beta-PR10584-52d29072c7e279c5873d9ed623c4787d5f685a9f.dmg

**Comment by sharsein** [comment]
Testing

**Comment by sharsein** [comment]
QA Pass
Tested with Windows 10 on Vive. Push, pull, push to extreme distance, rotating, letting go and grabbing again all work.

**Comment by tapalisa** [comment]
Typing in HMD is broken in this build. Please confirm if it was broken by this or was broken in master

**Comment by tapalisa** [comment]
Some observations: 
Holding your hand to your chest is likely not an intuitive gesture for a user to reel something in. They are more likely to try to pull straight back with their arm. This gesture sometimes is effective and sometimes not. For pushing an object away, holding your arm straight out works very well.

Moving a far-grabbed object left and right has become basically impossible in this build. You end up reeling things in when you try. This is probably an unacceptable deprecation of our current functionality. 

The haptics when something is being reeled in is a good idea, but I notice than when this happens, the haptic buzz that signals the far-grab to near-grab transition does not happen. This is pretty confusing.

**Comment by amvmoody** [comment]
@tapalisa You confirmed what I thought with using the bubbles I'll make it use bounded zones.
the intended gesture is moving hand strait back and strait forward for the applied velocity.

**Comment by tapalisa** [comment]
I confirmed that HMD typing was not broken in Master. QA, please add that to the test plan.

**Comment by amvmoody** [comment]
@tapalisa I am able to type with the stylus in the build Is that what you are referring too ?

**Comment by sharsein** [comment]
Here's what I'm thinking for a revised test plan(HMD):
Feature:
1) Far grab an object and pull your arm back. Should be a haptic buzz while reeling in
2) Change from far grab to near grab, haptic buzz should signal a switch
3) Move an object from left to right without pushing/pulling it in
4) Rotate arm while pushing object
5) Rotate arm while pulling object
6) Push an object into the distance until it is out of sight, then pull it back in
7) Test in edit/create mode
8) Move object horizontally while pushing
9) Move object horizontally while pulling
10) Pull an object, let go, grab it again
11) Push an object, let go, grab it again
12) Pull an object through another object
13) Push an object through another object
14) Transition between pulling and pushing without letting go

Edge cases:
15) Navigate tablet with laser
16) Test in create/edit mode
17) Test while a domain is still loading

Smoke:
1) Complete tutorial
2) Scroll through places in Go to menu
3) Enter text in Go-to menu
4) Navigate to home
5) Navigate to dev-welcome
6) Create an object using create/edit mode
7) Interact with an interactable object in a hanger

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/638/HighFidelity-Beta-PR10584-3f7e3a112eb39a9b4c5e6dfe3d01a4760292c696.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/638/HighFidelity-Beta-PR10584-3f7e3a112eb39a9b4c5e6dfe3d01a4760292c696.exe

**Comment by amvmoody** [comment]
@tapalisa @sharsein I've pushed the next version. Let me know how it feels, thanks :)

**Comment by sharsein** [comment]
Tested on Windows 10 with a Vive.

**Comment by themelissabrown** [comment]
@sharsein several of the areas you highlighted in a test plan don't apply here. The most important things to test on this one are @tapalisa's notes above: 

Holding your hand to your chest is likely not an intuitive gesture for a user to reel something in. They are more likely to try to pull straight back with their arm. This gesture sometimes is effective and sometimes not. For pushing an object away, holding your arm straight out works very well.

Moving a far-grabbed object left and right has become basically impossible in this build. You end up reeling things in when you try. This is probably an unacceptable deprecation of our current functionality.

And make sure the typing works again.

Mike will continue to add some improvements here.

**Pull request closed without merging**
