### PR TITLE
Fixed this issue of the spinner not displaying in create mode

### PR DESCRIPTION
**Pull request by druiz17**
Fixed this issue of the spinner not displaying in create mode

link to ticket - https://highfidelity.fogbugz.com/f/cases/6636/Arrows-do-not-show-anymore-in-properties

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- open create app
- create an object or click on an editable object
- goto the properties page
- make sure the arrows for the input spinners show up and work properly.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2316/HighFidelity-Beta-PR11133-38db4a6f472c82335fc90c300158b9cdfa109c60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2316/HighFidelity-Beta-PR11133-38db4a6f472c82335fc90c300158b9cdfa109c60.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
-------- | --------
open create app | Pass
create an object or click on an editable object | Pass
goto the properties page | Pass
make sure the arrows for the input spinners show up and work properly. | Pass

All working good, however I noticed that they don't follow the HiFi Styling per [this link](http://hifi-content.s3.amazonaws.com/alan/dev/UI%20Toolkit%2020160505.pdf).

6f129aff-9595-413e-898e-370ca509abe8

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
