### PR TITLE
More accurate and responsive stylus and finger touching.

### PR DESCRIPTION
**Pull request by hyperlogic**
The algorithm used to detect when and where the stylus or finger is touching the tablet has been improved.

* Hovering the finger/stylus over the surface of the tablet should cause buttons to highlight.
* Flicking or using the stylus like a drum stick, should more accurately click buttons on the tablet.
* Stabbing the tablet quickly, should also more accurately trigger button presses.
* Moving the hand/stylus from behind the tablet should be less likely to cause press events.
* If you are not using the stylus, your hand will animate into a pointing pose when it gets close to the tablet.

This PR also includes several crash fixes to the DebugDraw interface.

NOTE: this PR also includes changes to fingerPaint.js in order for it to play nicely with the tablet finger pointing feature.  We will have to update the market place with this new version.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
  * Verify that when the General Settings "Prefer Avatar Finger Over Stylus" works as expected.
  * Verify that interacting with the tablet using the stylus works as expected.
  * Verify that interacting with the tablet using your finger works as expected.
  * Verify that when interacting with the tablet using your finger, that your hand will point, when near the surface of the tablet.
  * Verify that you can still grab the tablet as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8f04d90a725c82b009dca505151596efa5d9a95 available at: https://gist.github.com/65e8aefe1a44db2970573ad9171729df<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9849-d8f04d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9849-d8f04d9.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9849-d8f04d9.exe

FAIL

- PASS: Hovering the finger/stylus over the surface of the tablet should cause buttons to highlight.
- PASS: Flicking or using the stylus like a drum stick, should more accurately click buttons on the tablet.
- PASS: Stabbing the tablet quickly, should also more accurately trigger button presses.
- PASS: Moving the hand/stylus from behind the tablet should be less likely to cause press events.
- PASS: If you are not using the stylus, your hand will animate into a pointing pose when it gets close to the tablet.
- PASS: Verify that interacting with the tablet using the stylus works as expected.
- FAIL: Verify that interacting with the tablet using your finger works as expected.
- PASS: Verify that when interacting with the tablet using your finger, that your hand will point, when near the surface of the tablet.
- FAIL: Verify that you can still grab the tablet as expected.

FAILS:
- Verify that interacting with the tablet using your finger works as expected.:
When the "Prefer Avatar Finger Over Stylus" option has been selected, both hands stop working as usual.
The closer the avatar's hands get to the tablet, it seems as someone has turned up the gravity and the hands animate as if they are very heavy. They slow down and are not in sync anymore with my real hands. Trying to touch an icon, with the avatar's hand, the hand works against you. No matter how much your real hand moves forward, the avatar's hand stays in the same spot as if being pushed back.
When I was able to click on an icon, the tablet works as usual.

- Verify that you can still grab the tablet as expected.:
When the stylus is out, clicking on the GOTO icon makes the tablet immovable. Grabbing the tablet stops working. Before clicking on GOTO the tablet was moveable as always.

**Comment by sethalves** [comment]
@claudioshg not being able to grab the tablet with the goto window on the hud is a known thing -- your lasers are hitting the hud so grab doesn't happen.

with the heavy-hand thing -- if you use a different avatar (like the blue-man/dr-manhattan), does it happen?

**Comment by claudioshg** [comment]
@sethalves The GOTO window is not open or above the tablet, in the forefront. After pressing the GOTO button and then closing the GOTO HUD, the tablet doesn't move anymore. I'm unable to grab the tablet and move it in any direction. As for the heavy thing, I'll look into it right now. Give me a few minutes.

**Comment by claudioshg** [comment]
@sethalves Switching to the "dr-manhattan" avatar does get rid of the heavy/gravity bug.

**Comment by sethalves** [comment]
okay, I'm going to merge this into the tablet-ui branch and we'll try to figure out what's going wrong when the goto window is open.

**Comment by cozza13** [comment]
speed of clicking on buttons feels a lot better. I got in a weird state were when I first switched to finger mode the laser I used to select the setting dialog was stuck in pressing mode.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07e10ae862668be3192d4827e49ba5bac0ffa432 available at: https://gist.github.com/65e8aefe1a44db2970573ad9171729df<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9849-07e10ae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9849-07e10ae.dmg

**Pull request merged**
