### PR TITLE
DO NOT MERGE: OSVR HMD

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 198a8f2db74134c72b19e300e1a3c6f514832a08 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-198a8f2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-198a8f2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 381c5f70c44684a4fac2b2d49eae6cf499b7fef6 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-381c5f7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-381c5f7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a53ba55efc0d75428339143aa3d18aa1f1bae407 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-a53ba55.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-a53ba55.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6642a07bb4d0a71c8255ec85de548595aa45831f available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-6642a07.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-6642a07.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a1bf8a9d5793abee90d710e6330f9681409e88f available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-7a1bf8a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-7a1bf8a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: feaa42446d03ce8efdf4c20842455bbdcc22cb3c available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-feaa424.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-feaa424.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 729d2d7a677a6aaad8c14064099d125c6fe3ab14 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 729d2d7a677a6aaad8c14064099d125c6fe3ab14 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 729d2d7a677a6aaad8c14064099d125c6fe3ab14 available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-729d2d7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c4b4b1b621e20d3840050efef42b22a49804af8f available at: https://gist.github.com/8446a1426202ded2f0ac84db5adfe79e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-c4b4b1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8452-c4b4b1b.dmg

**Pull request closed without merging**
