### PR TITLE
Verbose logging 2

### PR DESCRIPTION
**Pull request by howard-stearns**
Some little incremental improvements on sockets that I've been using and don't want to get lost, for https://highfidelity.atlassian.net/browse/BUGZ-7:
- When setting allow fragment on sockets, don't use Q_OS_WINDOWS which doesn't actually exist. (Just clean living because the default is normally allow fragmentation.)
- Report errors on setting.
- When reporting write errors: 
  - Do WSAGetLastError() before QT does, because QT ignores some of the data and it can't be meaningfully called twice.
  - Report any pending bytesToWrite(), consider a non-zero value as an error for logging, and distinguish a non-zero value as "pending bytes" so we can grep the logs.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19873/HighFidelity-Beta-PR15720-9c6ca60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19873/HighFidelity-Quest-Beta-PR15720-9c6ca60.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19873/HighFidelity-Beta-PR15720-9c6ca60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19873/HighFidelity-Beta-Interface-PR15720-9c6ca60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19873/HighFidelity-Beta-PR15720-9c6ca60.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19873/HighFidelity-Beta-Interface-PR15720-9c6ca60.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19891/HighFidelity-Beta-PR15720-d7f6685.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19891/HighFidelity-Quest-Beta-PR15720-d7f6685.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19891/HighFidelity-Beta-PR15720-d7f6685.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19891/HighFidelity-Beta-Interface-PR15720-d7f6685.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19891/HighFidelity-Beta-PR15720-d7f6685.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19891/HighFidelity-Beta-Interface-PR15720-d7f6685.exe

**Comment by SimonWalton-HiFi** [comment]
I think we actually set "don't fragment" to zero - i.e. do fragment (which is the default).

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19903/HighFidelity-Beta-PR15720-bd44619.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19903/HighFidelity-Quest-Beta-PR15720-bd44619.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19903/HighFidelity-Beta-PR15720-bd44619.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19903/HighFidelity-Beta-Interface-PR15720-bd44619.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19910/HighFidelity-Beta-PR15720-3111d2f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19910/HighFidelity-Quest-Beta-PR15720-3111d2f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19910/HighFidelity-Beta-PR15720-3111d2f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19910/HighFidelity-Beta-Interface-PR15720-3111d2f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19910/HighFidelity-Beta-PR15720-3111d2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19910/HighFidelity-Beta-Interface-PR15720-3111d2f.dmg

**Pull request merged**
