### PR TITLE
Commerce: Tons of Interface changes

### PR DESCRIPTION
**Pull request by zfox23**
There's no need to formally test any of this - we'll write the cumulative test plan when we're ready to enable the feature for all. **None of this PR should change the behavior of `master` code by default.**

This is my biggest PR of all time at 6500+ lines of changed code. **There will be bugs.** Please inform me of them.

There is still work to be done here. Please see [this Google Doc](https://docs.google.com/document/d/1kcQ7orggHqfJGWaaF3x1n5QJH8-gINzj8sP0zsdT9Jk/) for my todo list.

Additionally, *some of the data across Commerce functionality is fake*, including Certificate contents and Purchases item status.

At a high level, this PR includes at least the following:
1. **All-new Commerce pages**, including Checkout, Purchases, Wallet, Marketplace injections, and various modals/popups
2. New `getCanRez(Tmp)Certified()` permissions (client-side only; no change to server permissions page)
3. Changes to UIT elements to account for newly-specced UI elements (button, label, separator, constants etc)
4. Inspecting an item now opens its Certificate *if you have the `"commerce": true,` switch enabled in your Interface.json settings file*
5. Controlled-failure option for purchasing items (press `Ctrl+F` on the Checkout screen)
6. Slightly smaller security images (they were unnecessarily large by a hundred pixels) (they're probably temporary anyway)
7. Skeleton code for `ChallengeOwnership`

### CODE REVIEW

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3647/HighFidelity-Beta-PR11463-23416dd523925d4a83e5e3847240a667ccc4942b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3647/HighFidelity-Beta-PR11463-23416dd523925d4a83e5e3847240a667ccc4942b.exe

**Comment by howard-stearns** [comment]
Wow! Looks great!
Putting comments here that might ultimately belong in the TODO doc (i.e., you didn't mean to do them yet), but putting them here just to collect them:
- Marketplace has the login prompt, but not the wallet setup prompt.
- Marketplace username drop-down and "MY PURCHAES" username drop-down shows the useless submitted items, rather than the edition zero "artist's proof" items.
- Also, the two above aren't consistent wrt displaying "log out", and in the fake case (my purchaes), the menu doesn't go away when you click off of it. (Good luck trying to make this consistent. There's also a third case of a single marketplace item on a page, in which there is a hamburger menu that then adds a section with a name and a my items, in yet a third style. (I continue to believe that thinking about "MY PURCHASES" as "fake" marketetplace is sending us down a horrible road.) Check with Alan as to what to do here. Remember that we are supposed to be working on financial stuff, not fixing the broken existing web pages.
- If you click on "MY PURCHAESS" while wallet is not set up, the quasi-page-zero of setup looks as if it is behind a white translucent sheet. The buttons are clear, but the text ("Your wallet isn't set up. Set up your wallet....") is very light grey. Note that is also the wrong display -- it should be blue and say "Let's set up your wallet!..."
- First two pages of wallet setup show a greyed out security pic in the upper right corner. Intentional? (But see the item AFTER the next one.)
- "Page 2.5" of the wallet setup (the "tip" page in between step 2 and 3) does not show the same background as page 3. I find that confusing.
- Page 3 and 4 of wallet setup still have the greyed out security pic in the upper right corner. But at that point it DOES have a picture to use. What gives?
- Fucking focus problems. I had to click "Show passphrase" in order to type in the pass phrase boxes.
- Step 4 of wallet setup has a button next to the key file location that looks like a question mark (and which copies the location to the clipboard). How would a person know what to do with that?
- Pressing the "open for later" button on Step 4 of wallet setup just opens the highfidelity web site. Wha??? It also opens it in front, and I'm not sure what havoc that is going to cause for HMD users wrt to focus. And going back to Interface then has different text ("All set!..."), so you can't re-read wtf that was about.
- Reminder that the help text has issues.
- First-time purchases tutorial just has placeholder text.
- Back button in the "fake" marketplace (e.g. purchases) is confusing. (I continue to believe that thinking about "MY PURCHAES" as "fake" marketplace is sending us down a horrible road.) Check with Alan as to what to do here.
- My purchases doesn't yet display the count of other items with the same marketplaceID.
- My Purchases are not being displayed in the right order. (Should be newest first.)
- Controlled failures aren't working right. Presumably this is on the server side, but work with David to make sure. In addition to displaying "pending", "failed", etc., in My Purchases, remember that the transaction history should only show confirmed stuff, not failed nor pending. (It should say "n pending" below, when appropriate.)

**Comment by zfox23** [comment]
@howard-stearns: Thank you for the detailed comment! Some of this, like you say, is destined for the TODO doc (and will be done *soon*). The comments that aren't already there I will put there or address.

**Comment by howard-stearns** [comment]
While the _behavior_ of the commerce setting seemed right, I wasn't clear on the  _code_ relation between the "commerce" setting and the inspectionMode property.  (It might be ok, but it wasn't clear to me.)

There also seemed to be two Setting::Handles for the former (one in RequestFilters.cpp and one in ContextOverlayInterface.h), and I'm not certain that its supposed to work that way. (I'm not sure they both get set back to the file when reset by code.)

**Comment by zfox23** [comment]
@howard-stearns:
>While the behavior of the commerce setting seemed right, I wasn't clear on the code relation between the "commerce" setting and the inspectionMode property. (It might be ok, but it wasn't clear to me.)
Which "inspectionMode" property are you referring to? The `inspectionMode` setting should be completely gone - are you referring to something else?

>There also seemed to be two Setting::Handles for the former (one in RequestFilters.cpp and one in ContextOverlayInterface.h), and I'm not certain that its supposed to work that way. (I'm not sure they both get set back to the file when reset by code.)
I'm pretty sure it's OK to have multiple `Setting::Handles` - I think this is how we had it before, _and_ it's already done this way for other settings (like `Settings::firstRun`). Additionally, the `commerce` setting is never set directly from the CPP (only read).

**Comment by howard-stearns** [comment]
re inspectionMode - see the source, not the diff. There is a - ok, not a property in any formal sense, but an instance var with a getter and setter.

Re having multiple Handles for the same thing - I wouldn't count the fact that we do it as an indication that it is right. Particularly anything involving firstRun or tutorial! I'm not certain it is wrong as is, but I sure don't trust it. Check with Clement?

**Comment by zfox23** [comment]
Right - I know I need to look at the source, but I'm still confused. Here's a screenshot showing 0 results for that string:
image

Are you talking about `_isInMarketplaceInspectionMode`? Because that's something completely different - when that's set to true, we _could_ do things like highlight all marketplace items. Right now, we don't do anything with that information (we used to before the highlight shader was used).

Re: handles, I will check with Clement.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3670/HighFidelity-Beta-PR11463-3ec4c5d6a7b30d91ffcc95402deb333ffdc0b485.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3670/HighFidelity-Beta-PR11463-3ec4c5d6a7b30d91ffcc95402deb333ffdc0b485.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3686/HighFidelity-Beta-PR11463-0a85ea447f19a570e04b82c5fcbd6d73a68f3e96.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3686/HighFidelity-Beta-PR11463-0a85ea447f19a570e04b82c5fcbd6d73a68f3e96.exe

**Comment by RyanDowne** [comment]
purchase_error

I get this error by setting up my wallet and then trying to "purchase" the free confetti gun.

**Pull request merged**
