### PR TITLE
cant call gotohomescreen when tablet is closed

### PR DESCRIPTION
**Pull request by druiz17**
Fix the issue of tablet state being set to home when tablet is closed, result in the tablet screen being blank when you bring it up

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan

run this script https://gist.github.com/druiz17/89d794afb5cea9e5d9827972fd8c252e
then open and close the tablet multiple time. The tablet screen should not be white whenever you bring it up

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5156564f044813f1251e8c6dc6e212afc0f9c465 available at: https://gist.github.com/aa12751c197494fe98f17e5ff6259d02<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-5156564.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-5156564.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-5156564.exe

- I ran the script and opened and closed the tablet multiple times.
-In Desktop Mode: The tablet is performing as intended with no problems. No white screen.
-In HMD: I get this.
apr9817
No white screen, but I can't access the tablet.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 656720ae362f09a07baafe2497c23c506d2dc94f available at: https://gist.github.com/aa12751c197494fe98f17e5ff6259d02<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-656720a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-656720a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd3e1fb3209f528bded8ca078ed3fe6138e136c4 available at: https://gist.github.com/aa12751c197494fe98f17e5ff6259d02<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-fd3e1fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-fd3e1fb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9086460e3bd7f2ef3603ca1273096b51d74790c available at: https://gist.github.com/aa12751c197494fe98f17e5ff6259d02<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-e908646.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9817-e908646.dmg

**Pull request merged**
