### PR TITLE
Audio name conflict fix (fix for https://github.com/highfidelity/hifi/issues/11963)

### PR DESCRIPTION
**Pull request by ElderOrb**
PR fixes https://github.com/highfidelity/hifi/issues/11963

It doesn't introduce any new functionality, so there is no specific test plan.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5777/app_12038_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5777/HighFidelity-Beta-PR12038-9573ae3ea663120bd5c6a81500ed75d3d572c2e4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5777/HighFidelity-Beta-PR12038-9573ae3ea663120bd5c6a81500ed75d3d572c2e4.dmg

**Comment by sethalves** [comment]
to test:
- https://highfidelity.testrail.net/index.php?/cases/view/145&group_by=cases:section_id&group_order=asc&group_id=1447
- https://highfidelity.testrail.net/index.php?/cases/view/7047&group_by=cases:section_id&group_order=asc&group_id=1450

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5779/app_12038_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5779/HighFidelity-Beta-PR12038-bd3a056f4e99fcd6b4e89f507e15a006d6420772.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5779/HighFidelity-Beta-PR12038-bd3a056f4e99fcd6b4e89f507e15a006d6420772.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Sorry for delays, having a bit of issue with my OS  [Recently formatted so still going through some things

Got through half the testing, just going to reboot and I'll finish up :)

**Comment by YuppyPlays** [comment]
Testing complete:

[Apologies for delays, fresh computer format had some strange issues]

**Fail** though the fail is only 1 step particular.

TestRail Results: https://highfidelity.testrail.net/index.php?/runs/view/1747&group_by=cases:section_id&group_order=asc

Notes: For step 2: Test plan is incorrect as the feature is now labelled Developer>Audio>Show Scope and this echoes back the server audio.

**Comment by tapalisa** [comment]
Created https://highfidelity.manuscript.com/f/cases/10872/Audio-input-and-output-list-empty-with-Qt-5-10-0-11963

**Comment by ElderOrb** [comment]
I've compared 'master' build with Qt 5.9.2 with 'master' build with Qt 5.10.0 with this PR/Qt 5.9.2 with this PR/Qt 5.10.0 on Windows. The latest master built with Qt 5.10.0 suffers from the issue which this PR is intended to fix. In all other 3 cases I observed no issues with saving/restoring default devices for Desktop/VR. 

Here are the steps I followed: 

1. Launch interface
2. 'Reset settings but keep essential info'
3. Switch to Desktop
4. Go to audio
5. Select non-default device for Desktop and VR (I selected 2-nd from top for Desktop and 3-rd from top for VR). 
6. Exit APP
7. Launch interface
8. Ensure audio settings for Desktop and VR are the same as were selected in item 5

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Testing Passed.


@conklin94122

**Pull request merged**
