### PR TITLE
Use ~/Library/Cache/... as vcpkg_root on macOS

### PR DESCRIPTION
**Pull request by MattHardcastle**
The ~/Library/Cache directory is a more idomatic home for these files on
macOS.

From Apple's FileSystemProgrammingGuide
(https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html)

> Put data cache files in the Library/Caches/ directory. Cache data can be
> used for any data that needs to persist longer than temporary data, but
> not as long as a support file. Generally speaking, the application does
> not require cache data to operate properly, but it can use cache data to
> improve performance. Examples of cache data include (but are not limited
> to) database cache files and transient, downloadable content. Note that
> the system may delete the Caches/ directory to free up disk space, so
> your app must be able to re-create or download these files as needed.

A macOS user may be suprised to find that the high fidelity build
process has left a cache directory at the root of their home directory,
as this is not common practice on macOS.

### CODE REVIEW

**Comment by MattHardcastle** [comment]
@jherico Please consider this minor modification to the macOS build process.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15825/HighFidelity-Beta-PR14553-56e46a4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15825/HighFidelity-Beta-PR14553-56e46a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15825/HighFidelity-Beta-Interface-PR14553-56e46a4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15956/HighFidelity-Beta-PR14553-5349c6e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15956/HighFidelity-Beta-PR14553-5349c6e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15956/HighFidelity-Beta-Interface-PR14553-5349c6e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15956/HighFidelity-Beta-PR14553-5349c6e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15956/HighFidelity-Beta-Interface-PR14553-5349c6e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15962/HighFidelity-Beta-PR14553-a33726f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15962/HighFidelity-Beta-PR14553-a33726f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15962/HighFidelity-Beta-Interface-PR14553-a33726f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15962/HighFidelity-Beta-PR14553-a33726f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15962/HighFidelity-Beta-Interface-PR14553-a33726f.exe

**Comment by MattHardcastle** [comment]
> @jherico Please consider this minor modification to the macOS build process.

Just built the most recent master on my Mac and was bummed to find the hifi cache directory had returned to my home directory. Please consider this pull request as it makes the High Fidelity Mac build process more idiomatic on Macs.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16174/HighFidelity-Beta-PR14553-fc5aa95.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16174/HighFidelity-Beta-PR14553-fc5aa95.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16174/HighFidelity-Beta-Interface-PR14553-fc5aa95.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16174/HighFidelity-Beta-PR14553-fc5aa95.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16174/HighFidelity-Beta-Interface-PR14553-fc5aa95.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request closed without merging**
