### PR TITLE
Move cellscience to production s3 bucket

### PR DESCRIPTION
**Pull request by imgntn**
This PR puts all assets and scripts into the 'production' bucket on s3 and updates references.  The 'production' bucket will actually cache stuff, vs. the 'content' bucket which sends the content new every time.  Should help with load times.  AC scripts are running off of 'production' as well.

To test:
1. Go to cellscience.
2. You should hear music and see entities.
3. Click each of the buttons

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8899ac71a18fb96eb296859d6bdc6b126d1061dd available at: https://gist.github.com/84d0b030c8b2c1c7b7bcddb46f99c89f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.dmg

**Comment by Nex-Pro** [comment]
Seems faster and more reliable when changing location via buttons. 
Also of note the buttons are more reliable in the fact that they are more likely to display and respond to clicks.
But buttons are not 100% reliable in either this build or the current release.

Good improvement.

**Comment by imgntn** [comment]
ty for the testing! -- yeah those pesky buttons.  they try to read their destination from their userData, but there's no guarantee there actually is userdata when the preload method of the entity is called, so i try to wait to initialize... seems like its not working so great.  i think i'll give up and just make separate scripts for each button.

**Comment by OmegaHeron** [comment]
I'd suggest that make scripts for buttons idea... it's way too hit/miss with them and that's a shame as it's my fav place in HF.  I took a long time friend of mine on a tour of HF last night and we spent more time in Cellscience than anywhere else!  He's a medical doctor and it was fun listening to him go OMG OMG it's --something an engineer doesn't think about-- over and over then listen to narrations after.

**Comment by imgntn** [comment]
DNM hold while i add indivdidual nav buttons

**Comment by hifi-gustavo** [comment]
Build console output for commit: 61ff4d0f60bcc15290ac36ed0883af4d38dfc100 available at: https://gist.github.com/84d0b030c8b2c1c7b7bcddb46f99c89f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc5960fa1511b866fc0db11fffd57107f55c8125 available at: https://gist.github.com/84d0b030c8b2c1c7b7bcddb46f99c89f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7757.dmg

**Comment by imgntn** [comment]
so the individual buttons don't much seem to help the overlays sometimes not loading situation, which is a good piece of info.  we have a bug open for that issue, so i'm going to take the DNM off of this because it does put all of the other assets on production.  (well actually they're already there but keeping the repo in sync)

**Pull request merged**
