### PR TITLE
Tablet Prototype - Always hover

### PR DESCRIPTION
**Pull request by SamGondelman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5377/HighFidelity-Beta-PR11924-a395a84a26a9dc6634ff194ede20271baeed8015.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5384/HighFidelity-Beta-PR11924-a395a84a26a9dc6634ff194ede20271baeed8015.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5384/HighFidelity-Beta-PR11924-a395a84a26a9dc6634ff194ede20271baeed8015.dmg

**Pull request closed without merging**
