### PR TITLE
[QML] Fixes FogBugz Case 6107: Can't sort on import menu (details below).

### PR DESCRIPTION
**Pull request by 1P-Cusack**
Looking through the log revealed the following warning:
".../qml/dialogs/FileDialog.qml:489: Error: Cannot assign to non-existent property 'sortOrder'"

There was some refactoring to address some HMD functionality in 51b44d90
which resulted in an update to fileTableView's model.  This appears to be the point
at which sorting stopped working.

This updates the fileTableView's sorting methods to use fileTableModel as opposed
to fileTableView's model(filesModel).  This appears safe given fileTableModel internally wraps
around filesModel and is responsible for updating its value.  I'm relatively new
to QML/Qt; any comments or suggestions are welcome.

Tagging @vladest since they may want to be aware given 51b44d90.

Case Link:
https://highfidelity.fogbugz.com/f/cases/6107

**Testing:**
Open the Interface app.  Go to Edit -> Import Entities and click any of the column headers to sort.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3278/HighFidelity-Beta-PR11352-33c8e90e3415499c3bb083002fa57ac7c2cff8d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3278/HighFidelity-Beta-PR11352-33c8e90e3415499c3bb083002fa57ac7c2cff8d1.exe

**Comment by Nex-Pro** [comment]
testing this Win 10   Vive and desktop.( just in case )

**Comment by Nex-Pro** [comment]
### FAIL

I tried this in desktop and HMD.

Tablet:  **FAIL** for HMD and desktop. No sorting takes place. Sort order icon flips on the selected column header.

Toolbar: **SUCCESS** for HMD and desktop.

**Comment by birarda** [comment]
My guess would be you need to make the same change to `TabletFileDialog.qml` for this to work on the tablet.

I'm starting a separate conversation internally about how unfortunate it is that we're duplicating so much functionality between the X.qml and TabletX.qml files so that we can avoid this sort of thing in the future.

**Comment by 1P-Cusack** [comment]
@Nex-Pro:  Just updated this pull request to address the Tablet in VR mode failure.
@birarda:  Thanks!  It looks like the Tablet in desktop mode works because it uses a different version of the `TabletFileDialog.qml` rather than being covered by the `FileDialog.qml` as I previously thought.  I found that there are 2 versions of the `TabletFileDialog.qml.`
- `qml/dialogs/TabletFileDialog.qml`
    - This received a similar refactor update as `FileDialog.qml`
- `qml/hifi/tablet/tabletWindows/TabletFileDialog.qml`
    - This didn't receive the refactor that the other two files had.

The former is the version of the file used by the tablet within VR Mode; whereas, the later appears to be the version used when in Desktop Mode and bringing of up the Tablet via the Menu button which is why it wasn't broken when I tested it previously.

**Comment by 1P-Cusack** [comment]
It looks like the make build is failing due to an issue with cmake?

18:22:29 WARNING: Failed to get value for variable `CMAKE_BUILD_TOOL` from /Users/jenkins/Jenkins/workspace/pr-build/label/macos/build/CMakeCache.txt.

**Comment by 1P-Cusack** [comment]
It looks like the build failure has something to do with `nvtt` which is unrelated to my changes.  The windows build failed as well.

**Comment by MiladNazeri** [comment]
please build

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3320/HighFidelity-Beta-PR11352-24b6cd71fc5a249b7b18d3ecd84663e86e433af3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3320/HighFidelity-Beta-PR11352-24b6cd71fc5a249b7b18d3ecd84663e86e433af3.dmg

**Comment by 1P-Cusack** [comment]
@Nex-Pro:  I recently committed a change to address the VR Mode Tablet.  Could you retest this when you get the chance?

**Comment by Nex-Pro** [comment]
@1P-Cusack Yep in the morning.

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### PASS

Works in HMD and desktop. Tablet and toolbar.

Sorts columns as expected. Works with different folders. Arrows toggle correctly.

Only issue is the appearance of the column sort arrows. They cross the divide between columns. See images.

hifi-snap-by--on-2017-09-16_18-52-51
hifi-snap-by--on-2017-09-16_18-52-33

Don't think this is due to this PR.

**Comment by hifiwade** [comment]
works like it used to, thanks!

**Pull request merged**
