### PR TITLE
Fix Purchases sorting (again); Fix (i) icon loading

### PR DESCRIPTION
**Pull request by zfox23**
This PR accomplishes a few things:
1. Ensures that the order of My Purchases is correctly sorted (most recent purchase first)
2. Fixes the bug caused by #12238 where sorting was being done on a string when it should have been done on a number
3. Ensures that filtering My Purchases causes the Purchases listview to jump to the top (instead of confusingly being in the middle)
4. Fixes the (i) inspection icon

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Log into an account that has lots of Purchases made. Authenticate your wallet.
2. Open My Purchases
3. Experiment with the filter bar. Type in stuff. Filter your purchases. Make sure the results that show in My Purchases make sense with the filter you've used. For example, try typing gibberish and ensure nothing shows up. Another example: If you have both "Beach Ball" and "Balls & Marbles" in your Purchases, try typing in "ball" and verify that both items show up.
4. Verify that the items in My Purchases are sorted by "most recent item first". You can verify this by viewing the certificate of the bottom item, then the top item (for example).
5. Rez something in-world and right click it to bring up the (i) icon. Verify that the (i) icon appears.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6600/app_12258_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6600/HighFidelity-Beta-PR12258-afc71a5ac5090487961273f678a02b7363555cf8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6600/HighFidelity-Beta-PR12258-afc71a5ac5090487961273f678a02b7363555cf8.exe

**Comment by zfox23** [comment]
2X APPROVALS!!! double the quality :+1:

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by zfox23** [comment]
GAH! a conflict!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6614/app_12258_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6614/HighFidelity-Beta-PR12258-f117dd33a8b0ddf753017cc016c18d7e430f9a82.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6623/app_12258_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6623/HighFidelity-Beta-PR12258-f117dd33a8b0ddf753017cc016c18d7e430f9a82.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6623/HighFidelity-Beta-PR12258-f117dd33a8b0ddf753017cc016c18d7e430f9a82.exe

**Pull request merged**
