### PR TITLE
Connect audio injector signal to scripting

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
Testing through Jenkin's before asking for review.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cba0b295e8f5ef8ca57e63dc30b8a611d24e66bc available at: https://gist.github.com/bea35450f3709a335e0be687a5a91efa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9476-cba0b29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9476-cba0b29.dmg

**Comment by zzmp** [comment]
Fixes https://highfidelity.fogbugz.com/f/cases/2657/audio-injector-finished-signal-does-not-work

Test:

Create an audio injector and connect to its finished signal, ensuring that it is triggered when the sound stops.
Example:
```
// You may have to do this twice, as it won't play when the sound is not already loaded
sound = SoundCache.getSound("http://xiph.org/~xiphmont/demo/1kHz-0-dither.wav");
var dither = Audio.playSound(sound, { position: Vec3.sum(MyAvatar.position, Quat.getFront(MyAvatar.orientation)), loop: false, localOnly: false, volume: 1.0 });

dither.finished.connect(function() { print('finished'); });
```

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Master - no indication of finished printed.
This PR - finished is printed
General smoke tests = good.

**Pull request merged**
