### PR TITLE
Fix blendshapes crash one last time, one last time

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:

- The crash doesn't repro all the time because the timing is tricky. The easiest thing to do: go to engine-dev. There are a lot of avatars there. Spin around as they load, reload content, leave the domain and come back. Each time wait until the avatars all load. Their faces should render correctly, as should your own. You shouldn't crash.
- Try a lot.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12692/HighFidelity-Beta-PR13947-cde2dc2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12692/HighFidelity-Beta-PR13947-cde2dc2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12692/HighFidelity-Beta-Interface-PR13947-cde2dc2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12692/HighFidelity-Beta-PR13947-cde2dc2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12692/HighFidelity-Beta-Interface-PR13947-cde2dc2.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Stopped Testing pending further instructions.

**Comment by qlimnavarro** [comment]
Fail @conklin94122 @samcake 
Mac crashed 😢 
Logs: 
[hifi-log (1).txt](https://github.com/highfidelity/hifi/files/2358756/hifi-log.1.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2358757/hifi-log.txt)

**Comment by SamGondelman** [comment]
@qlimnavarro @conklin94122 I see the crashes on backtrace but none of them are the blendshapes crash.  If we think we've tested enough, then this would still be a pass, and we can investigate the other crashes separately.

**Comment by qlimnavarro** [comment]
@SamGondelman @conklin94122 
All other machines did not crash. This is good to pass. Updating comment.

**Pull request merged**
