### PR TITLE
Make the call to receiveAt more robust

### PR DESCRIPTION
**Pull request by zfox23**
QA on this one is nearly impossible because it's such an edge case, but We Promise (TM) it makes things better.

### CODE REVIEW

**Comment by davidkelly** [comment]
qa required some admin access - so we did it ourselves and it passed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6393/app_12196_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6393/HighFidelity-Beta-PR12196-16d51986a9b4b78207e042e52e2384940a1e9af0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6393/HighFidelity-Beta-PR12196-16d51986a9b4b78207e042e52e2384940a1e9af0.dmg

**Pull request merged**
