### PR TITLE
fixing compile errors as well as shader compile error on non supporte…

### PR DESCRIPTION
**Pull request by amerhifi**
…d devices

### CODE REVIEW

**Comment by amerhifi** [comment]
Testing on device, I'll pull do not merge off as soon as I validate

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17424/HighFidelity-Beta-PR14963-5bf3e28.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17424/HighFidelity-Beta-PR14963-5bf3e28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17424/HighFidelity-Beta-Interface-PR14963-5bf3e28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17424/HighFidelity-Beta-PR14963-5bf3e28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17424/HighFidelity-Beta-Interface-PR14963-5bf3e28.exe

**Pull request closed without merging**
