### PR TITLE
Fix snapshot connection errors

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1200/HighFidelity-Beta-PR10855-6e5eff9407b9a26226de7729ca1474d0cf2f955d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1200/HighFidelity-Beta-PR10855-6e5eff9407b9a26226de7729ca1474d0cf2f955d.exe

**Comment by Nex-Pro** [comment]
@jherico @AndrewMeadows Do you want me to QA this. I found this bug earlier today, I'm assuming this is the fix.

**Comment by Nex-Pro** [comment]
It seems the way to do QA now is never to wait for QA approved status.

**Comment by jherico** [comment]
@Nex-Pro sure

**Comment by Nex-Pro** [comment]
Yesterday we were getting messages like this:

[5/29 16:55:35] [defaultScripts.js] ERROR - [UncaughtException signalHandlerException] Error: Function.prototype.disconnect: failed to disconnect from TabletProxy::webEventReceived(QVariant) in file:///C:/Program Files (x86)/Steam/steamapps/common/High Fidelity/scripts/system/snapshot.js:665
[Backtrace]
    onTabletScreenChanged(type = 'Home', url = 'Tablet.qml') at file:///C:/Program Files (x86)/Steam/steamapps/common/High Fidelity/scripts/system/snapshot.js:665
    <global>() at -1

Not seeing any of those exceptions in the HMD friendly log using this build.

I think this is good @jherico

**Pull request merged**
