### PR TITLE
Prevent issues when bakers use the same worker thread as the DomainBaker

### PR DESCRIPTION
**Pull request by sabrina-shanman**
Possible fix for https://highfidelity.atlassian.net/browse/BUGZ-143

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19377/HighFidelity-Beta-PR15546-7694391.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19377/HighFidelity-Quest-Beta-PR15546-7694391.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19377/HighFidelity-Beta-PR15546-7694391.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19377/HighFidelity-Beta-Interface-PR15546-7694391.exe

**Comment by sabrina-shanman** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19385/HighFidelity-Beta-PR15546-7694391.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19385/HighFidelity-Beta-Interface-PR15546-7694391.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19385/HighFidelity-Beta-PR15546-7694391.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19385/HighFidelity-Beta-Interface-PR15546-7694391.exe

**Comment by sabrina-shanman** [comment]
Above builds appear to be broken due to Jenkins.

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19396/HighFidelity-Beta-PR15546-7694391.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19396/HighFidelity-Quest-Beta-PR15546-7694391.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19396/HighFidelity-Beta-PR15546-7694391.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19396/HighFidelity-Beta-Interface-PR15546-7694391.exe

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19429/HighFidelity-Beta-PR15546-7694391.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19429/HighFidelity-Quest-Beta-PR15546-7694391.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19429/HighFidelity-Beta-PR15546-7694391.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19429/HighFidelity-Beta-Interface-PR15546-7694391.dmg

**Comment by sabrina-shanman** [comment]
Closing as this appeared to not fix the bug after discussion later yesterday.

**Pull request closed without merging**
