### PR TITLE
Fix Avatar > Attachments joint and spinboxes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Fix setting attachment joint in Avatar > Attachments dialog.
- Fix QML spinbox min/max values.
- Fix QML spinbox not validating second time you enter invalid value.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Vive required.

Using default avatar, desktop mode, 3rd person view so that you can see your avatar.

1) Test the Avatar > Attachments dialog...

a) Test setting the attachment joint.
- Attach the following model to your avatar's "Head" joint: https://s3-us-west-1.amazonaws.com/hifidomain/New+folder/emohair.fbx. It should appear embedded in your avatar's head.
- Change the joint to "HeadTop_End" joint. The attachment should move up to near the top of your avatar's head.
- Try a few more joints.
- Restart Interface. The attachment should appear on the same joint and position as before.	

b) Test min/max translation values. Values should be able to range between -10 and 10. (Previously, they could only range from 0 to 10.)

c) Test min/max rotation values. Values shoudl be able to range between -180 and 180. (Previously, the could only range from 0 to 180.)

d) Test that the second time you type in an out of range value to a spinbox - e.g., enter 200 twice - the value is changed to the closest in-range value - e.g., 180 - both times. (Previously, the second time you entered the invalid value it would be changed.)

2) Check the spin box operations in other QML dialogs:
- Settings > General
- Settings > Control - Including OpenVR configuration dialog.
- Settings > Avatar

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10528/HighFidelity-Beta-PR13351-537665c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10528/HighFidelity-Beta-PR13351-537665c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10528/HighFidelity-Beta-Interface-PR13351-537665c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10528/HighFidelity-Beta-PR13351-537665c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10528/HighFidelity-Beta-Interface-PR13351-537665c.exe

**Comment by qlikmorales** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
@conklin94122 
Fail

Test plan fails: When restarting the interface the values in the spinbox (Avatar > Attachment: Rotation) don't save.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2095532/hifi-log.txt)
[Spinbox.zip](https://github.com/highfidelity/hifi/files/2095533/Spinbox.zip)

**Comment by ctrlaltdavid** [comment]
@qlihifitest Rotation values are converted to a quaternion when the dialog is closed, then converted back to 3 values for display when the dialog is re-opened, so values may appear to have changed when the dialog is reopened after an Interface restart but the attachment should be in the same position as before. For example, 180,180,180 redisplays as 0,0,0. And in the Spinbox.zip video 0, 180,-180 is redisplayed as 180,0,0. If the attachment was visible you'd see that it still had the same in-world orientation.

If added a note to set 1 > v to test values other than +/-180 and check the visible orientation of the attachment.

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
@conklin94122 
PASS

**Pull request merged**
