### PR TITLE
Desktop equip/unequip

### PR DESCRIPTION
**Pull request by dback2**
Left click equippable entities to equip them to your nearest available hand.
Press U on keyboard to unequip any equipped entities in both hands.

Test Plans:
https://highfidelity.testrail.net/index.php?/cases/view/15103
https://highfidelity.testrail.net/index.php?/cases/view/73

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8828/app_12905_PR_e86ef1c2d6781b4a97a3a5a224c134767611b518.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8828/HighFidelity-Beta-PR12905-e86ef1c2d6781b4a97a3a5a224c134767611b518.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8828/HighFidelity-Beta-Interface-PR12905-e86ef1c2d6781b4a97a3a5a224c134767611b518.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8828/HighFidelity-Beta-PR12905-e86ef1c2d6781b4a97a3a5a224c134767611b518.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8828/HighFidelity-Beta-Interface-PR12905-e86ef1c2d6781b4a97a3a5a224c134767611b518.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8884/app_12905_PR_46e040ca7b8ad2e0b0cd05d2b2cebe75f6a32b88.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8884/HighFidelity-Beta-PR12905-46e040ca7b8ad2e0b0cd05d2b2cebe75f6a32b88.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8884/HighFidelity-Beta-Interface-PR12905-46e040ca7b8ad2e0b0cd05d2b2cebe75f6a32b88.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8884/HighFidelity-Beta-PR12905-46e040ca7b8ad2e0b0cd05d2b2cebe75f6a32b88.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8884/HighFidelity-Beta-Interface-PR12905-46e040ca7b8ad2e0b0cd05d2b2cebe75f6a32b88.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8916/app_12905_PR_bf21a4cf563921a237506550dc3b917a9f519627.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8916/HighFidelity-Beta-PR12905-bf21a4cf563921a237506550dc3b917a9f519627.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8916/HighFidelity-Beta-Interface-PR12905-bf21a4cf563921a237506550dc3b917a9f519627.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8916/HighFidelity-Beta-PR12905-bf21a4cf563921a237506550dc3b917a9f519627.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8916/HighFidelity-Beta-Interface-PR12905-bf21a4cf563921a237506550dc3b917a9f519627.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8948/HighFidelity-Beta-PR12905-f7723a5bba6943d273996dc9fed714f31695a17e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8948/HighFidelity-Beta-Interface-PR12905-f7723a5bba6943d273996dc9fed714f31695a17e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8965/app_12905_PR_ef447cedfb0254d44cbfa2d8a492404f1e4e1e31.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8965/HighFidelity-Beta-PR12905-ef447cedfb0254d44cbfa2d8a492404f1e4e1e31.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8965/HighFidelity-Beta-Interface-PR12905-ef447cedfb0254d44cbfa2d8a492404f1e4e1e31.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8965/HighFidelity-Beta-PR12905-ef447cedfb0254d44cbfa2d8a492404f1e4e1e31.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8965/HighFidelity-Beta-Interface-PR12905-ef447cedfb0254d44cbfa2d8a492404f1e4e1e31.exe

**Comment by RyanDowne** [comment]
Is this ready to test?

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
equipabble objects look good from both user's perspective. We like this.

**Pull request merged**
