### PR TITLE
Fix not functional avatarapp when avatar bookmarks doesn't have 'avatarEntites' property

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/16683/Avatar-App-Add-to-Favorites-Button-Not-Working
https://highfidelity.fogbugz.com/f/cases/16661/Avatar-App-Older-avatar-favorites-do-not-appear-in-the-avatar-app
https://highfidelity.fogbugz.com/f/cases/16660/avatar-settings-not-accessible

*** Test plan *** 

1. Replace content of existing avatarbookmarks.json (or create it if doesn't exist) with the following (on Windows this file should be in "C:\Users\%user%\AppData\Roaming\High Fidelity - %build%\Interface"\ : 

{
    "Aisha": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "http://mpassets.highfidelity.com/e863348f-a777-4f36-86e6-af6e65ffa161-v1/F_BloSam.fst",
        "version": 3
    },
    "Fox Ears": {
        "attachments": [
        ],
        "avatarEntites": [
        ],
        "avatarScale": 1.0233054161071777,
        "avatarUrl": "https://hifi-content.s3.amazonaws.com/jimi/avatar/Niconico/fst/kitsune2_earsUp.fst",
        "version": 3
    },
    "Kitsune": {
        "attachments": [
        ],
        "avatarScale": 0.9788191914558411,
        "avatarUrl": "https://hifi-content.s3.amazonaws.com/jimi/avatar/Niconico/fst/kitsune2.fst",
        "version": 3
    },
    "One Wheel": {
        "attachments": [
        ],
        "avatarScale": 0.9846054315567017,
        "avatarUrl": "https://raw.githubusercontent.com/avatardz/reoiz/master/tf2/robot_medic_blue/robot_medic_hifi_blue.fst",
        "version": 3
    },
    "Pronama": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "http://mpassets.highfidelity.com/1de50887-048a-4a67-a4a2-72bd5e450afa-v1/PronamaChan.fst",
        "version": 3
    },
    "Purchase": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "http://mpassets.highfidelity.com/f823e831-d8c4-4191-a3bd-427e406e69f9-v1/F_Shinjuku.fst",
        "version": 3
    },
    "Purchase 2": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "http://mpassets.highfidelity.com/d293ef06-c659-467a-9288-c3cbaff0372a-v1/arya_avatar.fst",
        "version": 3
    },
    "Sarah": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "http://mpassets.highfidelity.com/da2ad4cd-47d4-41da-b764-41f39ff77e30-v1/F_JerGir.fst",
        "version": 3
    },
    "Tekken": {
        "attachments": [
        ],
        "avatarScale": 1.1398037672042847,
        "avatarUrl": "https://github.com/avatardz/reoiz/raw/master/Tekken_Avatar/Tekken_Avatar.fst",
        "version": 3
    },
    "Woody": {
        "attachments": [
        ],
        "avatarEntites": [
        ],
        "avatarScale": 0.9846054315567017,
        "avatarUrl": "https://highfidelity.com/api/v1/commerce/entity_edition/7fe80a1e-f445-4800-9e89-40e677b03bee.fst?certificate_id=MEYCIQDPRXtoe3iTvM0cHXkiDH8bOYsbW1UTBNoPv8jdKaNimwIhAJB3DExzH5kEZ7wfWIVOQsrVe7Dtjgyg6qI1Pes%2FVk8Y",
        "version": 3
    }
}

2. Launch 'Interface' 
3. Ensure AvatarApp is functional - show bookmarks, settings works etc.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11294/HighFidelity-Beta-PR13605-437f49a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11294/HighFidelity-Beta-PR13605-437f49a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11294/HighFidelity-Beta-Interface-PR13605-437f49a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11294/HighFidelity-Beta-PR13605-437f49a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11294/HighFidelity-Beta-Interface-PR13605-437f49a.exe

**Comment by sethalves** [comment]
for rc70 -- https://github.com/highfidelity/hifi/pull/13607

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Avatar app can be used as expected with the bookmarks in this test case

**Pull request merged**
