### PR TITLE
Fix typo in overlay "filled" property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Inspect and run the attached script.
- In current dev builds there will be two "undefined"s instead of Boolean values written to the program log.
- In the PR build there will be no "undefineds"; there will be "trues" and "falses" as indicated in the script.

**Code Review**

Could perhaps remove support for the "filed" case - I can find no instances of it being used in hifi or hifi-content repositories though in theory there could be user scripts.
What is the current practice on backwards-compatibility?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5035/HighFidelity-Beta-PR11840-a33162d7ffc03457f644055cc5e4a23ee470a34a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5035/HighFidelity-Beta-PR11840-a33162d7ffc03457f644055cc5e4a23ee470a34a.dmg

**Comment by SamGondelman** [comment]
In setProperties, "filled" is spelled correctly.  So there's no way to actually set "filed."  Given that, it seems like you could get rid of the misspelling completely without affecting any scripts.

**Comment by ctrlaltdavid** [comment]
In theory, an existing user script could use "filled" to set the property and "filed" to get it.

I would prefer to get rid of the misspelling and wouldn't be surprised if no currently used scripts at all use "filled" or "filed". However, what level of "possibly breaking user scripts" is OK these days?

**Comment by SamGondelman** [comment]
We've been discussing a deprecation process, through which you'd do something like post on the forum and then wait an acceptable amount of time before possibly breaking something, but I guess it's up to @ZappoMan to say whether or not that applies in this simple case.

**Comment by ZappoMan** [comment]
Let's fix the typo, leave in the old mode, post on the forum and the docs that the spelling is deprecated... give it a couple RCs and you can delete it.

**Comment by cain-kilgore** [comment]
@ctrlaltdavid Can you attach the script?

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
```
[11/18 01:33:29] [DEBUG] [hifi.scriptengine] Done downloading script at: "file:///d:/Cain/Desktop/filled.js"
[11/18 01:33:29] [DEBUG] [hifi.scriptengine] loadURL "file:///d:/Cain/Desktop/filled.js" "Success" QThread(0x21d67dbfa20, name = "Main Thread")
[11/18 01:33:29] [INFO] [hifi.scriptengine] [filled.js] Script Engine starting:filled.js
[11/18 01:33:29] [DEBUG] [hifi.audioclient] injector has no more data, marking finished for removal
[11/18 01:33:29] [DEBUG] [hifi.audioclient] removing injector
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] Should be 3 x 'true'...
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] isSolid = true
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] filled = true
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] filed = true
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] Should be 3 x 'false'...
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] isSolid = false
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] filled = false
[11/18 01:33:29] [DEBUG] [hifi.scriptengine.script] [filled.js] filed = false
```

**Comment by ctrlaltdavid** [comment]
I'm proceeding per ZappoMan's suggestions:
- There is no documentation on the "filled" or "filed" properties in the current API docs on the Web site.
- I've added "deprecated" to the JSDoc API documentation for Overlays which I'm currently working on.
- I've posted on the forums: https://forums.highfidelity.com/t/overlays-property-filed-is-deprecated/13378
- I've made a note to myself to remove the old, erroneous spelling code in a new PR after two RCs where both spellings are supported.

**Pull request merged**
