### PR TITLE
Fix for occasional crash on switching domains

### PR DESCRIPTION
**Pull request by jherico**
The current texture implementation using the KTX backing files to load mips on demand.  However, the mechanism assumes that the lifetime of the file in the cache will exceed the lifetime of the mip loading operations.  The current code doesn't guarantee this, because the `NetworkTexture` is the only object holding the lock on the cache entry and it can leave scope before the `gpu::Texture` object that is doing the transfers does.  

This PR modifies the code so that the `gpu::Texture::KtxStorage` class can optionally hold a copy of the cache entry pointer and thus ensure the lifetime of the cache file exceeds that of the buffering operations.  

Additional changes have been made to the texture transfer logic to ensure that if for any reason the texture mip face can't be accessed, we allow an uninitialized texture to be used instead of crashing.  

Fixes [FB5381](https://highfidelity.fogbugz.com/f/cases/5381/).

## Dev Reviewer notes

Because this PR is based on the branch which is used for #10727 you should focus on the changes contained in [this commit](https://github.com/highfidelity/hifi/pull/10735/commits/51662902b388dd7cbb8c1a6f2a7d6c6544769c7e) for this PR.  

## Testing

This fix is actually built on top of another pending fix in #10727.  When running master build, performing the test actions are probably equally like to crash from either the bug fixed in that PR or the bug fixed in this one, so comparison testing should be between this PR and #10727.  

Run interface and switch between two high texture domains like dev-distributed and dev-welcome.  In the #10727 build (and master) this will eventually crash.  It may take a few minutes to actually trigger a crash.  I believe the ideal time to switch domains in order to trigger this is when the stats display indicates that the allocated textures are high and the pending transfers are high.  

When examining the log file, there should be a line similar to this near the end of the file 

    [06/15 16:47:01] [WARNING] [hifi.core.storage] Failed to map file  "~/AppData/Local/High Fidelity/Interface/ktx_cache/54c9971dbf15112a19759d823c3ab27e.ktx"

In this PR, the application should not crash, at least not with this log output.

### CODE REVIEW

**Comment by CainFoool** [comment]
Will test.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/832/HighFidelity-Beta-PR10735-51662902b388dd7cbb8c1a6f2a7d6c6544769c7e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/832/HighFidelity-Beta-PR10735-51662902b388dd7cbb8c1a6f2a7d6c6544769c7e.exe

**Comment by CainFoool** [comment]
# Test Passed 

I was unable to reproduce the crashing in this latest PR, switching fairly aggressively between dev-welcome and dev-playa - pending counts were high.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/845/HighFidelity-Beta-PR10735-1d4b4431130e8d5899d4d0cf1227b472b58dde9d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/845/HighFidelity-Beta-PR10735-1d4b4431130e8d5899d4d0cf1227b472b58dde9d.exe

**Pull request merged**
