### PR TITLE
remove xmpp chat from interface

### PR DESCRIPTION
**Pull request by birarda**
Hold on this until we have an IRC up and available as alternative

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 03de43d451bc6c7dfd8912dcb004efadcc8e5e2c available at: https://gist.github.com/e78dd933700078945490<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a961cd8ff3910bbe892aea62014bf4cbef52470d available at: https://gist.github.com/e78dd933700078945490<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f2dc7e38b388e975a73518b1d20516099ddd30f available at: https://gist.github.com/e78dd933700078945490<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4370.dmg

**Comment by birarda** [comment]
tested on win, good to go

**Comment by birarda** [comment]
awaiting final conf from @cozza13 that he is ready for this to go through

**Comment by Atlante45** [comment]
Code looks good to me and smoke check passed.

**Pull request merged**
