### PR TITLE
Update interface to default to HMD display plugin

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbef07172349a785a9fc7913cf981f494db515ee available at: https://gist.github.com/d462232b61ef7c5a7677281828242f18<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-bbef071.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-bbef071.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 26e0d02d6067019e605b8ce3bf600aee5f8be9ad available at: https://gist.github.com/d462232b61ef7c5a7677281828242f18<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-26e0d02.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-26e0d02.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cec62b3a3681a21f6de3262c7b13b8442d009f8 available at: https://gist.github.com/d462232b61ef7c5a7677281828242f18<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-0cec62b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8980-0cec62b.dmg

**Comment by huffman** [comment]
You will need an HMD plugged in to test.

To test:

 1. Reset your settings
 1. Run interface
 1. Confirm that interface launches in HMD mode
 1. Shut down interface
 1. Remove your HMD
 1. Reset your settings
 1. Run interface
 1. Confirm that interface launches in Desktop mode

**Comment by Nex-Pro** [comment]
Testing this on Win10

**Comment by Nex-Pro** [comment]
Tested on Win10

### PASS

Reset your settings: ***Check***
Run interface: ***Check***
Confirm that interface launches in HMD mode: **Success**
Shut down interface: ***Check***
Remove your HMD: ***Check***
Reset your settings: ***Check***
Run interface: ***Check***
Confirm that interface launches in Desktop mode: **Success**
Shut down interface: ***Check***
Plug your HMD back in: ***Check***
Run interface: ***Check***
Confirm that interface launches in Desktop mode (because it was saved in settings): **Success**

**Pull request merged**
