### PR TITLE
debug prints for resolv path

### PR DESCRIPTION
**Pull request by sethalves**
DON'T LOOK AT MEEEE

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce7f64c1cde53f05f0614d9ab555a3350a59f5df available at: https://gist.github.com/b7db27bd54b56d9711f54aeecf9a1384<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-ce7f64c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-ce7f64c.dmg

**Comment by huffman** [comment]
:eyes:

**Comment by hifi-gustavo** [comment]
Build console output for commit: d77da58c99c99c3fbb7d54b5065c7c51becd2687 available at: https://gist.github.com/b7db27bd54b56d9711f54aeecf9a1384<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-d77da58.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-d77da58.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7345b4cc82f9a6410875e068f43c038ab05e7a8f available at: https://gist.github.com/b7db27bd54b56d9711f54aeecf9a1384<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-7345b4c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-7345b4c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 82e86c2f99d016781cd28b5a281aa74d3d62ef28 available at: https://gist.github.com/b7db27bd54b56d9711f54aeecf9a1384<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-82e86c2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8541-82e86c2.dmg

**Pull request closed without merging**
