### PR TITLE
Add thread names and scripts to chrome traces

### PR DESCRIPTION
**Pull request by huffman**
This adds:
 * Thread names to chrome traces
 * Scripting category
 * Scripting entities category

thread-names

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: aba441ee14e223d5bc152f01c86adff599aa7a68 available at: https://gist.github.com/8743ec0db1e2131478b190003e66ecc6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9603-aba441e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9603-aba441e.dmg

**Comment by huffman** [comment]
To test:

 1. Produce a trace file for the `trace.app` `trace.script` and `trace.script.*`
   1. You can use this script if you'd like (F1 to start the trace, F2 to stop): https://gist.githubusercontent.com/huffman/94bf32d568961ad8ba1915a94f0bf304/raw/af4beecab76affd51fcbe86e9b2d9a0e31340a97/scriptTest.js
 1. Ensure that local client scripts are working.
 1. Inspect the produced trace file to see that it shows a row for defaultScripts.js and any other scripts you run, and that the first column shows thread names ("Main Thread" "Present Thread" "Script name" etc.)
 1. Smoke test that scripts are working correctly.

**Comment by OmegaHeron** [comment]
Tested Windows 10

General smoke test = pass
All scripts I normally run continue to work as expected.

I can't get the test script to run - it's throwing an exception when triggered

`[02/09 13:27:55] [CRITICAL] [hifi.scriptengine] "[UncaughtException] ReferenceError: Can't find variable: Test in https://gist.githubusercontent.com/huffman/94bf32d568961ad8ba1915a94f0bf304/raw/af4beecab76affd51fcbe86e9b2d9a0e31340a97/scriptTest.js:30\n[Backtrace]\n    <anonymous>(event = [object Object]) at https://gist.githubusercontent.com/huffman/94bf32d568961ad8ba1915a94f0bf304/raw/af4beecab76affd51fcbe86e9b2d9a0e31340a97/scriptTest.js:30\n    <global>() at -1"`

**Comment by huffman** [comment]
@OmegaHeron Ah, you will need to launch interface with the `--testScript` flag. You can do this from the command line or by creating a shortcut to interface and append `--testScript PATH_TO_TEST_SCRIPT` to the `Target`. Please let me know if that isn't clear, it's a little tricky to get working the first time.

**Comment by OmegaHeron** [comment]
::facepalms::

Got it @huffman - I thought I could run it in interface from UI.  Will run it from command line, I've done it a "time or two".

**Comment by OmegaHeron** [comment]
QA Pass

Test script works as advertised, trace file contains data as shown in testing notes.

**Comment by huffman** [comment]
Thanks @OmegaHeron !

**Pull request merged**
