### PR TITLE
Prevent Context Overlay from flashing when briefly hovering over certified entity

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS13792](https://highfidelity.manuscript.com/f/cases/13792).

### CODE REVIEW

**Comment by zfox23** [comment]
### Test Plan
1. Rez or locate a certified entity. Briefly point a blue laser at it and release immediately
    i. Verify that the "i" overlay and orange outline DO NOT flash after a short delay
2. If the entity is non-grabbable, fully hold the trigger/far grab/point a red laser at it for any length of time, then release the laser.
    i. Verify that the "i" overlay and orange outline DO NOT flash after a short delay

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8465/HighFidelity-Beta-PR12778-5f47d511718595422f93ff859fedc8bfcddaa74d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8465/HighFidelity-Beta-PR12778-5f47d511718595422f93ff859fedc8bfcddaa74d.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Outline does not flash, tested with gnomes (Grabbable) and Flowers (non-grabbable).

**Comment by sethalves** [comment]
@qlimnavarro -- to be clear, this is a QA pass?

**Pull request merged**
