### PR TITLE
Explode Input/Output types in Jobs' run methods

### PR DESCRIPTION
**Pull request by zzmp**
Includes work from #9269.

Changes the Graphics internals such that:
- Varyings can be created with minimal typing
- Varyings can be concatenated or sliced to create another flat Varying (no nesting)
- Jobs' `run` methods no longer take Varyings, but their exploded types
- Debug runs include type checking, and will fail an assertion and log the type differences if Varyings are misused

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0722a2d91db9f04954b6593fa00b192479930ed3 available at: https://gist.github.com/7da5689180b24d7cc5b620c0887e95d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0722a2d91db9f04954b6593fa00b192479930ed3 available at: https://gist.github.com/7da5689180b24d7cc5b620c0887e95d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.dmg

**Comment by zzmp** [comment]
If anyone looks at this, could you look into Jenkins and see why exactly it is failing? From what I can see in the logs, it looks like it is failing to fetch an external resource, and is not tripping up on the actual PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0722a2d91db9f04954b6593fa00b192479930ed3 available at: https://gist.github.com/7da5689180b24d7cc5b620c0887e95d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-0722a2d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f522a924e7f8584f1643231d857d6a8344b9a026 available at: https://gist.github.com/7da5689180b24d7cc5b620c0887e95d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-f522a92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-f522a92.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f522a924e7f8584f1643231d857d6a8344b9a026 available at: https://gist.github.com/7da5689180b24d7cc5b620c0887e95d0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-f522a92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9277-f522a92.dmg

**Comment by samcake** [comment]
Let's close this one fo now as we haven;t agreed on the design yet with Zach

**Pull request closed without merging**
