### PR TITLE
Remove avatarEntityData cruft from settings

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* fix a bug where old 'client-side only entities' cruft could be left in the interface's settings file

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc301d1c1aaf7fb138a1f18682888c209eaa9ffa available at: https://gist.github.com/ff581e4b213b24f8bb90f3002fb11848<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9631-cc301d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9631-cc301d1.dmg

**Comment by AndrewMeadows** [comment]
This is a fix for a bug where if the interface were ever to exit after using "client-side only entities" (aka 'avatar entities') the entity data could be left inside the interface's settings file even though their count was "zero".

To test:

(1) Using a bugged interface:
(2) Login
(3) Run this script to create an "avatar entity" whose existence is governed by your avatar's login session (it vanishes from the world when you logout).
```
var forwardOffset = Vec3.multiply(2.0, Quat.getFront(MyAvatar.orientation));
var boxPosition = Vec3.sum(MyAvatar.position, forwardOffset);
var BOX_WIDTH = 0.5;

var properties = {
    type: "Box",
    name: "PR-9631 test box",
    dimensions: {x: BOX_WIDTH, y: BOX_WIDTH, z: BOX_WIDTH},
    position: boxPosition
};  

// create the object
var AVATAR_ENTITY = true;
var entityId = Entities.addEntity(properties, AVATAR_ENTITY);

// wait 20 seconds and then delete the object
deleteEntity = function() {
    Entities.deleteEntity(entityId);
}   
var LIFETIME = 20000; // msec
Script.setTimeout(deleteEntity, LIFETIME);
```
(4) Wait 20 seconds for object to be deleted.
(5) Stop running the test script from (3).
(6) Logout.
(7) Find your interface settings file and open in a text editor:
On Windows this will be: `C:\Users/YOURNAME\AppData\Roaming\High Fidelity - PR9631\Interface.json`

(8) Look for lines that have the string 'avatarEntityData' and you'll probably see something like this:
```
    "Avatar/avatarEntityData/1/id": "@Variant(\u0000\u0000\u0000\u001ekBDë<8e>\u0004I^»8Õ±yn<8c>â)",
    "Avatar/avatarEntityData/1/properties": "@ByteArray(qbjs\u0001\u0000... blah blah... u0000\u0000p\u0002\u0000\u0000)",
    "Avatar/avatarEntityData/size": 0,
```
--> the object was deleted but info about it still lives in the settings file!

(9) Login again with bugged interface, wait for everything to load and then logout again.
(10) Verify that the 'avatarEntityData' lines are still in your settings file
--> the data persist logins even though they are not used.

(11) Login with this PR
(13) Logout (settings changes will be saved).
(14) Verify that most of the 'avatarEntityData' lines are gone.  There should remain one line that looks like this:
`    "Avatar/avatarEntityData/size": 0,`
(15) Login again with this PR
(16) Run the script from (3) but once the object is visible... logout before it gets deleted by the script.
(17) Verify that the settings file lists one entry `avatarEntityData`
(18) Login again with this PR, wait for the new object to be deleted and then stop the script.
(19) Manually delete the old object from the previous session (16) and logout (settings will be saved).
(20) Verify that the `avatarEntityData` has size of zero.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e02810458b328305f05f97239b04c7d30001bef2 available at: https://gist.github.com/ff581e4b213b24f8bb90f3002fb11848<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9631-e028104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9631-e028104.dmg

**Comment by nbq** [comment]
testing

**Pull request merged**
