### PR TITLE
add initial support for local paths in domain

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c9a14cd9dbf1ae644c9050424acc8693f4b92f2 available at: https://gist.github.com/8150c56c62709c2f7352<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.dmg

**Comment by birarda** [comment]
I'm making my editor start to remove trailing whitespaces from lines - so you'll see extra additions and deletions from that in future pull requests.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89cb3d66e4ba3232732e069500f84b98d6a5703a available at: https://gist.github.com/8150c56c62709c2f7352<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e88cfc913f55f29c22c93fba108f8adc476941cd available at: https://gist.github.com/8150c56c62709c2f7352<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4847.dmg

**Pull request merged**
