### PR TITLE
Android audio tests

### PR DESCRIPTION
**Pull request by gcalero**
This PR aims to reduce the choppy audio based on two facts:
- In samsung devices we're forcing the audio input to be resampled as a workaround to a bug that attenuates the signal ~18dB. This PR reverts this and achieves the same non-attenuated input using the native sample rate which implies not adding extra latency
- Setting an input buffer size that is multiple of PROPERTY_OUTPUT_FRAMES_PER_BUFFER is recommended to have lower latency. This PR tunes up the buffer size to capture 20ms of audio which is multiple of all the android devices tested so far (S8, S9, Pixel, Pixel2, Huawei Mate 9 pro).
More info here:
[](https://developer.android.com/ndk/guides/audio/audio-latency?hl=en-419#input-latency)

Test plan:
- In different domains the audio should work as well or better (less choppy) than a build from master
- Speaking from a Samsung device should be heard as louder as a build from master
- Use different devices and write the results [in this excel ](https://docs.google.com/spreadsheets/d/1v-LCDa9KB7OtLPR2bO-UtSkOUCX-hhcG6vrX_LsKD0Y/edit?usp=sharing)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11726/HighFidelity-Beta-PR13724-f98c19f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11727/HighFidelity-Beta-PR13724-b8bab85.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11727/HighFidelity-Beta-PR13724-b8bab85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11727/HighFidelity-Beta-Interface-PR13724-b8bab85.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11734/HighFidelity-Beta-PR13724-b841a5f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11734/HighFidelity-Beta-PR13724-b841a5f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11734/HighFidelity-Beta-Interface-PR13724-b841a5f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11734/HighFidelity-Beta-PR13724-b841a5f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11734/HighFidelity-Beta-Interface-PR13724-b841a5f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11795/HighFidelity-Beta-PR13724-687f5e3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11795/HighFidelity-Beta-PR13724-687f5e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11795/HighFidelity-Beta-Interface-PR13724-687f5e3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11807/HighFidelity-Beta-PR13724-f0d058c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11807/HighFidelity-Beta-PR13724-f0d058c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11807/HighFidelity-Beta-Interface-PR13724-f0d058c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11807/HighFidelity-Beta-PR13724-f0d058c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11807/HighFidelity-Beta-Interface-PR13724-f0d058c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11898/HighFidelity-Beta-PR13724-5bb9acc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11898/HighFidelity-Beta-Interface-PR13724-5bb9acc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11898/HighFidelity-Beta-PR13724-5bb9acc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11898/HighFidelity-Beta-Interface-PR13724-5bb9acc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11899/HighFidelity-Beta-PR13724-cb215d3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11899/HighFidelity-Beta-PR13724-cb215d3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11899/HighFidelity-Beta-Interface-PR13724-cb215d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11899/HighFidelity-Beta-PR13724-cb215d3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11899/HighFidelity-Beta-Interface-PR13724-cb215d3.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12047/HighFidelity-Beta-PR13724-2e323ef.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12047/HighFidelity-Beta-Interface-PR13724-2e323ef.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12081/HighFidelity-Beta-PR13724-4b808fe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12081/HighFidelity-Beta-PR13724-4b808fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12081/HighFidelity-Beta-Interface-PR13724-4b808fe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12081/HighFidelity-Beta-PR13724-4b808fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12081/HighFidelity-Beta-Interface-PR13724-4b808fe.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Audio is improved across devices.

**Pull request merged**
