### PR TITLE
Fix typos in controller modules disabler

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Check that one or more of the following still work (i.e., hand lasers etc. are turned off while using):
- Home domain content's music box
- Toybox's bow
- Marketplace's bow or shortbox
- Game table's desk of cards

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3376/HighFidelity-Beta-PR11380-18b71f0c0fde0dc2b13c9aa078a908447e91a48b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3376/HighFidelity-Beta-PR11380-18b71f0c0fde0dc2b13c9aa078a908447e91a48b.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Check that **one or more** of the following still work (i.e., hand lasers etc. are turned off while using):
Home domain content's music box **Couldn't find**
Toybox's bow **Couldn't find**
Marketplace's bow or shortbox **Tested both of these, lasers disable when item is being used such as pulling back the arrow on the bow, Pass**
Game table's desk of cards **Couldn't find**

**Pass**

**Pull request merged**
