### PR TITLE
check for null node data pointers in handleIgnoreRequestPacket

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11913/HighFidelity-Beta-PR13773-c7ce8e5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11913/HighFidelity-Beta-PR13773-c7ce8e5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11913/HighFidelity-Beta-Interface-PR13773-c7ce8e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11913/HighFidelity-Beta-PR13773-c7ce8e5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11913/HighFidelity-Beta-Interface-PR13773-c7ce8e5.exe

**Comment by birarda** [comment]
#### Test Plan

- With the Sandbox from this PR, confirm that you can successfully ignore another avatar in the domain using the PAL

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by birarda** [comment]
@SimonWalton-HiFi In most cases it will be created as soon as we get data from that Node. The crash this fixes could occur if you ignore a node that has been removed.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Able to ignore successfully.

**Pull request merged**
