### PR TITLE
Remove deprecated Window.raiseMainWindow API function

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not needed because no code C++ or JavaScript code uses this function.

Forum notice: https://forums.highfidelity.com/t/window-raisemainwindow-being-removed-from-the-api/14130

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11267/HighFidelity-Beta-PR13594-46c9853.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11267/HighFidelity-Beta-PR13594-46c9853.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11267/HighFidelity-Beta-Interface-PR13594-46c9853.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11267/HighFidelity-Beta-PR13594-46c9853.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11267/HighFidelity-Beta-Interface-PR13594-46c9853.exe

**Pull request merged**
