### PR TITLE
command-line utility for fetching an asset from a remote asset-server

### PR DESCRIPTION
**Pull request by sethalves**
- command-line utility for fetching an asset from a remote asset-server

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run `./atp-get atp:/test-data.txt -d eschatology.hungry.com`
- look for "It worked!"

**Comment by hifi-gustavo** [comment]
Build console output for commit: 438fb42da45cc429d82a33a0b15f54bd07599601 available at: https://gist.github.com/35f51949857b6aa6c3aed10ac6ede173<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9918-438fb42.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9918-438fb42.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 60d10f3374c9bb7459570558f7052216e9fac5d9 available at: https://gist.github.com/35f51949857b6aa6c3aed10ac6ede173<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9918-60d10f3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9918-60d10f3.dmg

**Comment by PhilipRosedale** [comment]
So this basically logs into a remote domain server and gets the names asset?

**Comment by sethalves** [comment]
that's right.

**Comment by OmegaHeron** [comment]
Testing this now -- will be on Ubuntu Linux.  If atp-get.exe should be in Windows installed package then this is a QA Fail as it's not being installed.  Will post results of Linux test once it's built.

**Comment by OmegaHeron** [comment]
Ubuntu 16.04

`hftest@mylinuxbox:~/space/pr/hifi/build/tools/atp-get$ ./atp-get atp:/test-data.txt -d eschatology.hungry.com`
`ResourceManager disk cache setup at "/home/hftest/.local/share/High Fidelity - PR/ac-client" (size: 10 GB)`
`path is  "/test-data.txt"`
`found, hash is  "897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677"
hifi.networking.asset_client: "atp:897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677" not in disk cache`
`hifi.networking.asset_client: Got size of  "897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677"  :  11  bytes`
`hifi.networking.asset_client: Requesting data from 0 to 11 of "897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677" from asset-server.`
`hifi.networking.asset_client: Got reply for asset:  "897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677"`
`hifi.networking.asset_client: "atp:897253b5a1276bd28643d3ae40ed048910c20a8477353ba22de83d51a1287677" saved to disk cache`
`It worked!`

If compiled with HIFI_MEMORY_DEBUGGING=1 it's indicating numerous leaks on run.
It seems to only save fetched item to cache, this is intent?

**Comment by sethalves** [comment]
it put it in the cache, but it also sent it to stdout (It worked! is the contents of the file).  If you give a 2nd argument, it will treat that as a filename and send the data there.

I don't know if atp-get.exe should be in the package or not.  I'll leave that to someone else.

**Comment by OmegaHeron** [comment]
Thanks @sethalves

**Comment by AndrewMeadows** [comment]
Seriously I thought seth was suggesting to execute the `apt-get` command.  Maybe it should be named something other than `atp-get`?  Maybe a word with 'atp' in it like... "sweatpants"?

... ok maybe that isn't a very good idea.

**Comment by OmegaHeron** [comment]
Heh - I typed apt-get 3 times before finally copy/pasting it.  Not enough coffee and too much muscle memory in play.

**Comment by sethalves** [comment]
yeah... It should probably be called hifi-asset-tool and have multiple functions (get, put, list, delete)

**Pull request merged**
