### PR TITLE
CR #21308 Fix Script.print

### PR DESCRIPTION
**Pull request by humbletim**
Worklist item available at https://worklist.net/21308

This PR updates `print()` / `Script.print()` to work with the HMD-friendly Script Log window and JSConsole output (previously only the partial script name was being displayed and not message contents).

It also updates known debug print helpers (like `Vec3.print(label, vec3)` and `Quat.print(label, quat, asDegrees)`) to use consistent formatting and send output to the HMD Script Log and Console (previously these only output to the application log).

### Testing

* Launch Interface.
* Enable `Settings -> Developer Menus`.
* Open the `Developer -> Script Log (HMD friendly)...` window.
* Open the `Edit -> Console...` command prompt.
* Execute `Script.include('/~/developer/tests/printTest.js')` in the Console.
* Verify that both the HMD Script Log and Console window display full log messages (and not just the `about:` prefix like current master does).
* Example of what the output should look like:
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f71552c648af5c10e32e764c0601555a87bc35be available at: https://gist.github.com/909346e0cb3b75a666950f275ea3608f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-f71552c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-f71552c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c17d1a6d881333f196bd8272d2346cc062c98f71 available at: https://gist.github.com/369457e829c23426a38982c624fc3e6c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-c17d1a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-c17d1a6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25807a5258f3c6539acd6c8e739f5d50b6e354fb available at: https://gist.github.com/369457e829c23426a38982c624fc3e6c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-25807a5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10388-25807a5.dmg

**Comment by cozza13** [comment]
tested and approved

**Pull request merged**
