### PR TITLE
Restyle the Running Scripts dialog

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
This is the first pass at restyling the Running Scripts dialog per the style set out in the UI Toolkit document; the UI Toolkit spec can now be seen in operation.

Some particular notes for review:
- Running Scripts table: Contrary to the mock-up in the UI Toolkit doc, table headings are not displayed as they seemed to be unnecessary.
- Black button animation: I think the black button's hover and press states seem to be back to front compared with the other buttons. In particular, hover over the red and black buttons at the top of the Running Scripts dialogue. The hover "animation" appears to go in different directions. Similarly for pressed state. The black button animations should be swapped to be more similar to the other colours?
- "From URL" and "From disk" buttons: These should perhaps be moved to be at the bottom of the dialog because they're "expert" functions; new users should be guided to use the existing scripts list and filter as their first port of call.
- Script filter field: It has a label, "Filter", above it per the mock up in the UI Toolkit document. Keep this or revert back to using placeholder text "Filter" in the field like it was before?
- Available lists tree view: The expand / collapse arrows are on the left rather than on the right; this is what the QML TreeView control displays by default.

Also, the styling details need to be checked against the updated version of the UI Toolkit document when it comes out.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54b27f3ac3a9eceaacd8f7e6c461c1c947424bde available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by RyanDowne** [comment]
The mac version has a 2px fuchsia line at the bottom 
screen shot 2016-02-18 at 6 51 46 pm

**Comment by ctrlaltdavid** [comment]
That fuschia line is where a gradient is supposed to be.
Also noted in the screen snap: the top of the scrollbar in the available scripts list is not at the top of the scroll view as it should be.

**Comment by ctrlaltdavid** [comment]
@RyanDowne On OSX is the scrollbar of the running scripts list displayed OK when there are lots of scripts running? What about the scrollbar of the overall window when you resize the window so that the scrollbar needs to display?

**Comment by RyanDowne** [comment]
When I load lots of scripts I do get the scroll bar but when the window has focus I also get this...
screen shot 2016-02-19 at 9 59 32 am

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91e4fb478d0bcee0ddb811f0d3dbbdb3c1d736dd available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by ZappoMan** [comment]
Btw -- I think the edit control and the "Load" button at the bottom of this dialog box are no longer needed. They were added by Austin back when he first migrated the dialog box to QML because he couldn't get double-click in the listview to work... but since then he has got double-click working properly, and so the "Load" button is totally superfluous... Let's get rid of it... and as David suggested, move the "from Disk" and "from URL" buttons to below the list...

Also -- I'll note... the new style really does look beautiful! Kudos!

**Comment by ctrlaltdavid** [comment]
Would removing the "Load" button make it less obvious to new users that normally you'd load scripts from the tree view? (If there was just the "From URL" and "From disk" buttons under the list it may seem that you should select a script and then press one of those two buttons to load the script?)

Also, is double-clicking something that's readily done in HMD view?

**Comment by RyanDowne** [comment]
Because we don't have a lot of time and we have a lot to do, let's refrain from trying to redesign as we go, and just style for now unless it's really clear we should remove something. In this case I think David makes a good point: It's not clear that double clicking when using hand controllers is going to be easy so leaving the Load button at the bottom for now is fine. It's a two click operation. Leave the Load URL etc buttons where they are.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 558c8872b16ac5a729314420040bbf21c672ee06 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfedd24ad73ebfacd1992f18a8b881e6f51ea782 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: db6c76bf67784ff303ea24faa1be0177c777ae20 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by RyanDowne** [comment]
Fixes looked good on Mac when I tested over the weekend

**Comment by RyanDowne** [comment]
I've noticed on PC that when you close the dialog, some elements, I think some of the text, trail fading away. Have you seen this?

**Comment by jherico** [comment]
@RyanDowne the same thing happens with all our dialogs, it has to do with the alpha blending mechanism we use for hiding windows.  I may simply be more noticible with the inverted color scheme.

**Comment by jherico** [comment]
@ctrlaltdavid the from disk and from url buttons appear to have their bottom below the top of the Filter label.  Please adjust the alignment of the filter label down or revert to using filter placeholder text.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 942406e5d5a581c15bd21db883e39f43bb37cd28 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by ctrlaltdavid** [comment]
Remaining known issues:
- Tree view's expand/collapse triangles being inconsistent sizes and colors. (Will be addressed shortly.)
- Inconsistent font sizes across different screens. (Will be doing a separate "DO NOT MERGE" PR that tests setting font sizes in pixels instead of points.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: fec82e31256be6de9639c1cd4bbf96d02adb8259 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9dd1bfad2d0b0319eccf21303e2fa2a458783e1d available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: beef3f59eb0b011518bc5e17f6924179c94e1835 available at: https://gist.github.com/773c91b2dbc6a684a5d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7131.dmg

**Pull request merged**
