### PR TITLE
Case 22106: DebugDraw JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
NameSpaces:
- DebugDraw

Jira case: https://highfidelity.atlassian.net/browse/DOC-60

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20692/HighFidelity-Beta-PR16011-53e8f7c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20692/HighFidelity-Quest-Beta-PR16011-53e8f7c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20692/HighFidelity-Beta-PR16011-53e8f7c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20692/HighFidelity-Beta-Interface-PR16011-53e8f7c.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20696/HighFidelity-Beta-PR16011-53e8f7c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20696/HighFidelity-Beta-Interface-PR16011-53e8f7c.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20696/HighFidelity-Beta-PR16011-53e8f7c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20696/HighFidelity-Quest-Beta-PR16011-53e8f7c.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20734/HighFidelity-Beta-PR16011-53e8f7c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20734/HighFidelity-Quest-Beta-PR16011-53e8f7c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20734/HighFidelity-Beta-PR16011-53e8f7c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20734/HighFidelity-Beta-Interface-PR16011-53e8f7c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20734/HighFidelity-Beta-PR16011-53e8f7c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20734/HighFidelity-Beta-Interface-PR16011-53e8f7c.dmg

**Pull request merged**
