### PR TITLE
Edit handle pick plane improvements

### PR DESCRIPTION
**Pull request by dback2**
- Add a debug overlays to visualize pick plane and pick plane hits
- Separate stretch and scale handles into their own functions
- Modify stretch handles to use the same pick plane as translation handles which is axis-aligned but rotated towards camera
- Modify scale handle to use camera-facing pick plane
- Overall cleanup of edit handles

Addresses:
https://highfidelity.manuscript.com/f/cases/15770
https://highfidelity.manuscript.com/f/cases/18397

Test Plan:
- Enter Interface in desktop mode
- Open Create and create or select any entity
- Verify all rotation handles work as expected and then leave the entity partially rotated on all axes
- Verify translation on the XZ plane (by clicking and dragging the entity anywhere outside of the handles) works as expected
- Verify all translation arrows work as expected
- Verify alt-dragging the entity anywhere outside of the handles will duplicate the entity
- Verify all axis-based stretch cubes work as expected and stress test these handles from many different angles
- Verify the center scale cube works as expected (rightward or upward movement scale the entity upward, leftward or downward movement scale the entity downward, and scaling down passed the minimum inverts and scales the entity upward again) and stress test this from many different angles as well
- Verify all above handles again (besides alt-dragging) in HMD mode
- Go to your local directory for this PR build and find the scripts/system/libraries/entitySelectionTool.js file
- Change the false to true on the following line on line 794 of the entitySelectionTool.js file (you may need to be open in Administrator mode to edit it):
var debugPickPlaneEnabled = false;
- Re-run Interface in either desktop or HMD mode
- Open Create and select any entity again
- Verify when using every handle that you see a debug plane overlay and orange debug spheres that show where the mouse ray hits the debug plane as you drag
- Verify the debug overlays still visible until grabbing another handle, deleting the entity, or reloading all scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13416/HighFidelity-Beta-PR14101-8c306b8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13416/HighFidelity-Beta-PR14101-8c306b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13416/HighFidelity-Beta-Interface-PR14101-8c306b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13416/HighFidelity-Beta-PR14101-8c306b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13416/HighFidelity-Beta-Interface-PR14101-8c306b8.exe

**Comment by qlihifitest** [comment]
Currently testing

**Comment by qlihifitest** [comment]
PASS @Conklin94122 debug plane overlay and orange debug spheres follow the mouse ray when interacting with any plane, as expected; in both HMD and desktop mode.

**Comment by qlihifitest** [comment]
PASS @conklin94122 debug plane overlay and orange debug spheres follow the mouse ray when interacting with any plane, as expected; in both HMD and desktop mode.

**Comment by conklin94122** [comment]
@dback2 Changes since QA Approval and build is failing. Clearing labels. Please set to QA Ready when it is.

**Comment by huffman** [comment]
build this please

**Comment by conklin94122** [comment]
QA, the changes were minor, please do a sanity test of change, 5-10 minutes.

**Comment by dback2** [comment]
The conflict merge (the latest change) does not require a full QA retest as the merged changes are independent of these PR's changes and have already been verified. Just verifying that Create opens and edit works should be a sufficient sanity test.

**Comment by conklin94122** [comment]
Thanks @dback2

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13540/HighFidelity-Beta-PR14101-b5edf42.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13540/HighFidelity-Beta-PR14101-b5edf42.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13540/HighFidelity-Beta-Interface-PR14101-b5edf42.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Sanity check passes

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13566/HighFidelity-Beta-PR14101-b5edf42.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13566/HighFidelity-Beta-PR14101-b5edf42.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13566/HighFidelity-Beta-Interface-PR14101-b5edf42.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13566/HighFidelity-Beta-PR14101-b5edf42.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13566/HighFidelity-Beta-Interface-PR14101-b5edf42.exe

**Pull request merged**
