### PR TITLE
fix swapped buttons in oculus touch graphic

### PR DESCRIPTION
**Pull request by birarda**
- replaced the Oculus Touch help graphic that had swapped buttons

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

In Interface, with Oculus touch connected, open the "Help" dialog (under File -> Help). Verify that the buttons displayed on each touch controller in the dialog match the placement of the buttons on the actual touch controllers.

On master, A+B and X+Y are swapped.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3985354ff46a57e90efc476fe207c553f7100f5e available at: https://gist.github.com/9fe85555080612353bb6beaa1e29f52f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9998-3985354.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9998-3985354.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9998-3985354.exe

**PASS**

The Touch controllers are accurately pictured on the HELP graphic. The X,Y and A,B buttons are shown correctly.

**Pull request merged**
