### PR TITLE
Beta Release 29 - Includes up to Developer Release 5757

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Glow line replacement without geometry shader
* Reduce logspam, change some debug output to warning
*  Add AC Audio searcher for tutorial
* Location cleanup to make people more aware of their sandbox placename
*  Animate suggestions when available
* Fix the bad binding for polyline
* Introducing Clustered Lighting and improve Lighting performances ( https://github.com/highfidelity/hifi/pull/8560#issue-174639872 ) 
* Bubble on by default for new users
* Address the crash when no vertex format is specified
* Add bind polyfill and basic .editorconfig for indentation
* Support debugging issues where we are seeing crashes in the OpenGL drivers
* Select Audio DLL at runtime
* Fix a bug when using the gpu::Batch::_glUniform*() calls with a bad location
* Fix 'releaseGrab' not being called when using grip buttons
* Make hand-controller ui work in third person
* Vec3 and shader helpers
* Room Scale HMD comfort features. ( https://github.com/highfidelity/hifi/pull/8691 )
* Fix for teleport where you could not teleport to some location
* When using mouse to grab, reduce energy of the grab as you get farther away and as objects get larger
* Fixed children of parent object not being added back when performing an undo
* Added jsdocs for MyAvatar
* Support for the 3ds Max object offset feature ( https://github.com/highfidelity/hifi/pull/9138#issue-192940777 )
* Fix a crash if current shader is null
* Possible polyline crash fix

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10c054165fd53ba43cee3ed7f2fa49c071af62bb available at: https://gist.github.com/3c4834a34fb35da7b53cd756baf024a5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9145-10c0541.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9145-10c0541.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Fail. Server audio was not echoed. Local audio worked correctly however Server did not. Reverb test echoed low volume server audio but not enough to be normal.


## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Fail. Server audio was not echoed. Local audio worked correctly however Server did not. Reverb test echoed low volume server audio but not enough to be normal.


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Kick now includes MAC address|Untested
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Failure on Hydras
**Test 10**|Grab objects in dev-demo|undefined

**Comment by Nex-Pro** [comment]
### PR #9145 Beta release 29

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

## FAIL


## QA Test
**QA Tester**: Piper.Peppercorn assisted by Michelle Leckrone

We each verified problems.

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** FAILURE

**localhost ATP Upload + Edit Result**: **localhost ATP** FAILURE

**Echo Server Audio**: **Echo Server Audio** SUCCESS

**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS

**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS

**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** FAILURE
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE

**QA Pass**: **QA Pass** FAILURE

**Additional Test Results + Observations**:

While using test blocks in HMD mode I had a block attach to my left hand while it was being manipulated by Michelle Leckrone who was in desktop mode.
I had to leave the domain to remove it. Also two blocks became collisionless and non-dynamic in the process.

When avatar collisions are disabled I was unable to move up or down using the right hand controller. Switching collisions back on restored up and down control.

Jumping in HMD mode initiates rapid z axis oscillations visible to self and others.

Editing a dynamic object was impossible as any click on it resulted in it penetrating the ground surface and effectively becoming un-editable.
Also there was a strange offset between the laser and any control handle on the object meaning that squeezing the trigger selected objects behind or in front of the control handle.

The comfort mode has to be optional as it completely wrecks immersion. I'd insert more adjectives but this would turn into a rant.

Playa performance test does not work properly as the avatar body rotates below the head while the head points in one direction. the graphs looked ok but as the view isn't rotating I felt them to be invalid.

Enable kinematic movement triggers crash.



hifi-snap-by-piper-peppercorn-on-2016-12-03_15-47-46
hifi-snap-by-piper-peppercorn-on-2016-12-03_15-31-39

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

QA Fail

Privacy bubble no longer respects setting for radius not = 1M.  No matter what value you set its bubble space = 1M.  This seems to have been introduce prior to this PR - will attempt to find.

I did not have any issues with using ATP to upload a file then place in world at localhost (or any of my other 3 remote domains).  Audio was same with this PR vs last RC.

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop 1600x900 maximized window - vsync unlocked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |314 |310 |314
**Present Rate**: |313 |310 |315
**Present New Rate**: |219 |183 |218
**CPU Buffer Count**: |2502 |4624 |4241
**GPU Buffer Count**: |804 |1435 |1173
**CPU Memory Usage**: |39271248 |84464496 |89039600
**GPU Memory Usage**: |29358192 |58026096 |49674352
**CPU Texture Count**: |228 |293 |318
**GPU Texture Count**: |196 |250 |295
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |71690608 |259197392 |75889104
**GPU Texture Memory Usage**: |574712135 |1059388495 |1140995977
**GPU Virtual Memory Usage**: |574712135|1059388495|1140995977
**Triangle Count**: |237800 |801893 |329218
**Triangle Rate**: |39633333 |114556142 |109739333
**API Drawcall Count**: |184 |289 |205
**Drawcall Count**: |3000 |332 |1117
**Drawcall Rate**: |500000 |47428 |372333
**State Changes Texture Count**:|369 |342 |305
**Pipeline Count**: |64 |38 |54
**Item Opaques**: |257 |470 |225
**Item Translucents**: |94 |64 |72
**Item Lights**: |12 |42 |41
**Timing Opaques**: |0.961 |1.547 |0.676
**Timing Translucents**: |0.198 |0.15 |0.149
**Timing Lighting**: |0.026 |0.033 |0.021
**Render Frame**: |2.543 |4.056 |2.023

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |2502 |4744 |4261
**GPU Buffer Count**: |808 |1476 |1288
**CPU Memory Usage**: |39250768 |84915056 |89060080
**GPU Memory Usage**: |29608048 |54642800 |60065904
**CPU Texture Count**: |228 |296 |317
**GPU Texture Count**: |199 |261 |305
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |71690608 |105515472 |71436752
**GPU Texture Memory Usage**: |750611079 |1302510299 |1317353045
**GPU Virtual Memory Usage**: |750611079|1445116635|1317353045
**Triangle Count**: |362029 |1740977 |665677
**Triangle Rate**: |27848384 |133921307 |51205923
**API Drawcall Count**: |118 |296 |192
**Drawcall Count**: |4776 |664 |2192
**Drawcall Rate**: |367384 |51076 |168615
**State Changes Texture Count**:|245 |357 |295
**Pipeline Count**: |51 |35 |48
**Item Opaques**: |151 |483 |211
**Item Translucents**: |64 |69 |66
**Item Lights**: |6 |44 |41
**Timing Opaques**: |0.556 |1.765 |0.82
**Timing Translucents**: |0.187 |0.17 |0.16
**Timing Lighting**: |0.022 |0.047 |0.028
**Render Frame**: |1.946 |4.115 |2.302

**Comment by Nex-Pro** [comment]
In addition noticed strange issue with rendering.

Look at the edges of the avatars in the images. Top image has strange edge artifacts compared to current release.

9145_edgeissue


current_release

**Comment by zfox23** [comment]
@OmegaHeron I've found the source of the space bubble size bug and have fixed it in my development branch (PR #9142).

You'll notice that the bubble radius _is_ changed if you set it to less than 1.0. This is because of a call to min() that should have been a call to max().

**Comment by OmegaHeron** [comment]
@zfox23 -- Also keep an eye out for an inverted state in bubble toggle -- I saw once (maybe twice) case where HUD icon indicated bubble state = off yet it was clearly on.  Since I couldn't repro it I hadn't yet mentioned.  But - we keep getting reports of people unable to hear loopback server audio and I *suspect* it may well be coming from that, in that they think bubble is off yet it is actually on, killing server audio loopback in testing....

**Pull request closed without merging**
