### PR TITLE
Code Review for Job #21139 - Do not allow grab or far-grab or click while editing objects

### PR DESCRIPTION
**Pull request by humbletim**
Workitem available at https://www.worklist.net/21139

#### Testing

Note: This PR affects both Desktop and HMD based editing modes so the below test should be repeated once per mode.

* Open Interface to a Domain with Rez perms.
* Rez some grabbable Entities to work with.
* Verify Entities can be grabbed and moved around in general.
* Enter EDIT mode.
* Verify that you can no longer grab Entities (in the grab.js / handControllerGrab.js sense).
* Verify that you can still "select" and "drag" Entities around (in the edit.js sense).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15394056ebdfa7871fa4ad22d990bb4cf04d079b available at: https://gist.github.com/59a4e72a5ccdcf83318213c8fef46d25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9467-1539405.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9467-1539405.dmg

**Comment by Nex-Pro** [comment]
@humbletim is line 10 scripts/system/libraries/utils.js     io.highfidelity.isEditting a typo ?

**Comment by Nex-Pro** [comment]
@humbletim  is line 10 of scripts/system/libraries/utils.js

EDIT_SETTING = "io.highfidelity.isEditting";

a typo that was introduced on dec  2 2016 https://github.com/highfidelity/hifi/commit/348c0c95e5b5da5e73e8a54488582e692b8028e0

**Comment by humbletim** [comment]
@Nex-Pro that does seem to be a historical typo.  Are you suggesting it could be fixed inline with this PR?  I thought about that as well, but other scripts appear to depend on the current value remaining as-is for now.

**Comment by Nex-Pro** [comment]
Just noting the typo @humbletim

**Comment by PhilipRosedale** [comment]
Code looks good.  If anyone has hand controllers (my home machine not working this evening) and can test, that would be great.

**Comment by Nex-Pro** [comment]
@PhilipRosedale Testing this

**Comment by Nex-Pro** [comment]
### FAIL

Still possible to near grab in edit mode.  Spent some considerable time with @humbletim making changes to code in order to pin down where the issue was coming from. @humbletim  will write this up.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d20ac20ff2cf2256dd860e16c068c01f0f0f2ace available at: https://gist.github.com/59a4e72a5ccdcf83318213c8fef46d25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9467-d20ac20.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9467-d20ac20.dmg

**Comment by humbletim** [comment]
OK, all near grabs should now be prevented as well -- had to move the edit guard into the state change in order to block grabs while still letting lasers through.

Tested locally with Hydras, but should probably be verified again from a Vive or Touch.

**Comment by Nex-Pro** [comment]
Re-testing

**Comment by BillWindwalker** [comment]
Double click on object

**Comment by PhilipRosedale** [comment]
@Nex-Pro Yes please  can you test now?  I will pull when you confirm working.

**Comment by PhilipRosedale** [comment]
@BillWindwalker this version does not address mouse clicks.

**Comment by Nex-Pro** [comment]
@PhilipRosedale  Ok will do.

**Comment by BillWindwalker** [comment]
Render elodie has to be Max before attempting

**Comment by BillWindwalker** [comment]
LOD

**Comment by Nex-Pro** [comment]
The issue whereby if, while editing an entity, my hand moves into another entity the second would be grabbed is now gone.
Grabbing an entity in edit mode is now gone.


Control handles and widgets ( rotate, move vertical ) are no longer lighting up as often and there is a large offset between the lit up ( when they light ) control handles and the lasers.

Rotation widgets and up arrow are not illuminating when lasered.

Selection of entities that are in line visually with nearer entities cannot be reliably selected. ( may not be specific to this PR ) 

Also see images for control handle issues. ( seem worse in this PR ) 

pr9467_select_issue
pr9467_illuminate
pr9467_laser_offset

**Comment by PhilipRosedale** [comment]
@Nex-Pro I'm going to jump in and try it too.  Is it possible that this same picking problem exists in master?

**Comment by PhilipRosedale** [comment]
@Nex-Pro I agree that things are not always right with the editing controls.   Would you be able to write up some repro cases and test whether they happen in release or master or both?  This PR is definitely unrelated to that, as it does not in any way change the selection logic of edit.js.  

I just went through the test plan and this is a QA PASS for me.  But yeah, sometimes the edit selection seems to get screwed up, and this definitely pre-dates this build.

**Comment by BillWindwalker** [comment]
Some of this can be due to the item is still in the image file or cash file
of the viewer and not refreshing properly other instances can be the edit
box can still be there but the item can be gone this to is due to improper
cash import updating

On Jan 23, 2017 4:21 PM, "Philip Rosedale" <notifications@github.com> wrote:

Merged #9467 <https://github.com/highfidelity/hifi/pull/9467>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/highfidelity/hifi/pull/9467#event-933527721>, or mute
the thread

**Comment by Nex-Pro** [comment]
@PhilipRosedale Not the same in master as far as I could tell. But issues in both that make HMD entity editing a frustrating experience.

**Comment by BillWindwalker** [comment]
Seen that I am not in hmd I am unable to prove tests require a h MD

**Pull request merged**
