### PR TITLE
Add recording classes

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf39f67e02cb796d71ecc5651065f3fa8e2758e0 available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b8ffa0edbb14b304040ed21f8e9aa00ad1b776d available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b8ffa0edbb14b304040ed21f8e9aa00ad1b776d available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b8ffa0edbb14b304040ed21f8e9aa00ad1b776d available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b8ffa0edbb14b304040ed21f8e9aa00ad1b776d available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0bf29a441f2bade95193f6d7bc2052e6091e66a6 available at: https://gist.github.com/6f38d04e34d8e3498a67<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6328.dmg

**Pull request merged**
