### PR TITLE
Support oculus remote input

### PR DESCRIPTION
**Pull request by jherico**
Oculus Remote should function to open, nagivate and close the menu

### CODE REVIEW

**Comment by jherico** [comment]
https://app.asana.com/0/27650181942747/108742873752300

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca6dd9d44105f5400b792d2f60e7c7e95cdc4663 available at: https://gist.github.com/c7e44e247ee8e9f5ab7e473d807f4fa7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 458d8ad275894befa8646fd050156d8c3656e2f0 available at: https://gist.github.com/c7e44e247ee8e9f5ab7e473d807f4fa7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0cc733e628a0e9dfee5f9b4a1e0572bb9d73acd available at: https://gist.github.com/a796cdbb6e8c1a4d56f8cc4d968fea3c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7589.dmg

**Comment by cozza13** [comment]
I could not get the navigation menu up. However once it was up I could navigate with the remote. 

QA Fail - Could not load the menu with click

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72d8990fed562e445c6c9f8807bacea682dfbc37 available at: https://gist.github.com/c7e44e247ee8e9f5ab7e473d807f4fa7<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7589.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7589.dmg

**Comment by CaptainOculus** [comment]
Just pulled latest installer. Will test now.

**Comment by CaptainOculus** [comment]
Didn't see chris comment, but Thoys just told me inside Playa your results were similar to mine.

**Comment by cozza13** [comment]
tried again and it works

**Pull request merged**
