### PR TITLE
Update help window to auto select xbox or vive controller tab on availability of device

### PR DESCRIPTION
**Pull request by huffman**
You will need an Xbox 360 or Xbox one controller for this.

To test:

 1. If you have a Vive, unplug it
 2. Turn your Xbox controller on
 3. Reset your settings
 4. Launch interface
 5. Confirm that the help window comes up
 6. Confirm that the gamepad tab is selected, showing the xbox controller layout

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3147ea9e33c557d48881b849c1ad70a38956f5f3 available at: https://gist.github.com/6171b0c7b6df32a2d92848f19221792c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-3147ea9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-3147ea9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ba7eac5281e01b0457bddb1b337ba7f909088a3f available at: https://gist.github.com/6171b0c7b6df32a2d92848f19221792c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-ba7eac5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-ba7eac5.dmg

**Comment by OmegaHeron** [comment]
Windows 10

This fails for me.  I only see the vive controller tab selected.  Here's a bit of log showing it detected my XBox controller which is likely the issue as it's not a microsoft made one... It's a PowerA USB connected XBox controller.

[11/02 16:35:50] [DEBUG] [hifi.controllers] Registered input device < "GamePad" > deviceID =  1
[11/02 16:35:50] [DEBUG] [hifi.controllers] Device 1 : "GamePad"
[11/02 16:35:50] [DEBUG] [hifi.controllers] Device 65280 : "Application"
[11/02 16:35:50] [DEBUG] [hifi.controllers] Device 65281 : "Actions"
[11/02 16:35:50] [DEBUG] [hifi.plugins] init codec: "hifiAC"
[11/02 16:35:50] [DEBUG] [hifi.plugins] init codec: "pcm"
[11/02 16:35:50] [DEBUG] [hifi.plugins] init codec: "zlib"
[11/02 16:35:50] [DEBUG] [hifi.networking] Cannot create address path without a getter for position. Call AddressManager::setPositionGetter to pass a function that will return a const glm::vec3&
[11/02 16:35:50] [DEBUG] [hifi.networking] Cannot create address path without a getter for position/orientation.
[11/02 16:35:50] [DEBUG] [hifi.networking] AccountManager URL for authenticated requests has been changed to https://metaverse.highfidelity.com
[11/02 16:35:50] [DEBUG] [hifi.networking] Found metaverse API account information for https://metaverse.highfidelity.com
[11/02 16:35:50] [DEBUG] [hifi.plugins] Added device:  "Oculus Rift"
[11/02 16:35:50] [DEBUG] [hifi.plugins] Added subdevice:  "X360 Controller"

**Comment by huffman** [comment]
@OmegaHeron Do you have a vive plugged in when it selects the vive tab? Because it looks like your controller is being detected as an `X360 Controller`, it should work.

**Comment by OmegaHeron** [comment]
@huffman no vive but I do have a DK2.

**Comment by huffman** [comment]
@OmegaHeron And it's defaulting to the vive tab? Ok, that's a bug. I will look into it, thanks!

**Comment by huffman** [comment]
@OmegaHeron This is ready again when it finishes building

**Comment by hifi-gustavo** [comment]
Build console output for commit: 687605ad38425eee9825e9581e3f8ec6ae7892b1 available at: https://gist.github.com/6171b0c7b6df32a2d92848f19221792c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-687605a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8974-687605a.dmg

**Comment by OmegaHeron** [comment]
Windows 10

QA Pass - with clean settings and xbox controller attached I got tab for Xbox controller.  With controller unplugged I got standard keyboard/mouse tab.

**Pull request merged**
