### PR TITLE
Fix two bugs with Create Menu

### PR DESCRIPTION
**Pull request by misslivirose**
Fixes Manuscript Cases 12510 and 12511
Unblocks PR 12449 for testing once merged

Test Plan: 
- In HMD mode, run Test Rail case 1938 and confirm that you can now scroll the main page of the tablet and view the bottom two buttons
- In HMD mode, select the Asset Browser button from the Create Menu and confirm you can add a model to world from HMD mode 
- In Desktop Mode, run Test Rail case 1938 and confirm that you can resize and scroll the main page of the tablet
- In Desktop Mode, confirm you can still add a model to world from the Asset Browser

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7377/app_12463_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7377/HighFidelity-Beta-PR12463-aba1cae36d1c6fe172452dd75e1af02b0818955b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7377/HighFidelity-Beta-PR12463-aba1cae36d1c6fe172452dd75e1af02b0818955b.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
