### PR TITLE
Restyle entities editor

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
First pass at restyling "Entity List" tab. ("Grid" and "Entity Properties" tabs not restyled yet.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96ce912d3d8407f5dfd0c5efff761071ff7ecae0 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by ctrlaltdavid** [comment]
IMPORTANT: If you want to run the updated edit.js in this PR you need to copy the "scripts" and "resources" directories (and subdirectories) from the PR's install directory into another directory with no spaces in the path, and run edit.js from there.
(I haven't worked out why but it seems like events aren't getting through to edit.js somehow.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5541dd67327452f5310121f06d898b14a5d59009 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8185e13e18a9dd2909a6f95ca59c901a907e931c available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8185e13e18a9dd2909a6f95ca59c901a907e931c available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f85b7696b34a7ee7f9eb58ce57a10fb137fa9e5d available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a83df22816d350bff00e76681467b47ab2a9c04 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7

It looks good - takes up a lot more screen space to look balanced with new layout (I'm sure it's not as noticeable on higher resolution monitors - nor am I complaining, just saying.)

Zones.  Everything works, but, I preferred the previous layout for zones where its specific Zone properties were at top of list (Zone, Stage, Background, Skybox)

**Comment by RyanDowne** [comment]
The 'entity selected' doesn't some to be calculating correctly. I can multi-select two things and it says there are 6 selected and I can also multi-select two things and it says 0 things are selected. 

Looking great though and cool that you can collapse sections :)

**Comment by AlanZimmerman** [comment]
Looking really great so far! Here are my notes ( image attached for visual call outs):
edit-ui-qa-notes-20160330-az 001

**Comment by ctrlaltdavid** [comment]
@RyanDowne Fixed it reporting number of entities found rather than number selected when two multi-selected (typo). It reporting 6 selected when you think you have 2 selected I cannot reproduce but it could it have been that you had 4 selected but not visible in the list (e.g., distance filter lower than their distance or 4 of them scrolled off the bottom of the list)?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3457d1c21e88425ed661ee2486a5eaff7b9b2649 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 31b96c75ca8a09c425e8779559e418b861355bbc available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 31b96c75ca8a09c425e8779559e418b861355bbc available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ac9f282c70fbe2d5ea72c80d4bfad2e247ef12f available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by RyanDowne** [comment]
Confirmed that the entity selection works

**Comment by AlanZimmerman** [comment]
I've run through all my notes on the 2d screen and in the HMD. Everything seems in order–there are of course some additional styling tasks but I'd say this is good to merge.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 048865fb097745a87419913297e1cb31980b0db2 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2953595a5315706554f726f4d5da4a0035eece5 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by kevinmthomas-carpool** [comment]
Unloaded all scrips and manually added the PR scripts back to ensure testing the proper edit.js script.  First test was to edit an existing model on the ATP, specifically one of my Wine Boxes models that currently exists on the Music domain.  Successfully jumped to the selection and was able to move its physical location utilizing the edit UI and then tested manually with the drag properties as well as successfully locking and unlocking the item.  Second test was to delete the item to see if it was actually removed from the domain to which it did.  Third test was to import an fbx into the domain to which the model sits on my Dropbox account.  Successfully added, manipulated its size and location, tested for collisions and then successfully deleted object.

**Comment by TNS-TrueNorth** [comment]
Passes in Win10.

**Comment by ctrlaltdavid** [comment]
Re disabling right-click menu: The right-click menu before only had a "Copy..." option, no "Paste..." option. Copying and pasting using Ctrl-C and Ctrl-V work OK, though.

**Comment by TNS-TrueNorth** [comment]
@ctrlaltdavid Excellent, then there would be no problem, thanks!

**Comment by hifi-gustavo** [comment]
Build console output for commit: b900fcbbf0cf62ea5305368db449a1bb5860cd02 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f0529b5ea77e781fc251f3600f3b52656d147c4 available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9054897f77918c006711e79d18282a509e7ab3b available at: https://gist.github.com/4adb73aacfa45bccc5fb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7446.dmg

**Pull request merged**
