### PR TITLE
Hand controller mouse improvements

### PR DESCRIPTION
**Pull request by hyperlogic**
* Works better when body rotates under the avatar while using the handControllerMouse script.
* More consistent detection of which hand is moving the most, and thus has control over the reticle.
* Removed non-uniform scaling of mouse coordinates.  Thus, having consistent vertical and horizontal sensitivity.

This also exposes the MyAvatar.sensorToWorld matrix to script.  Which is necessary when you wish to position objects relative the user's sensor space / room.   As a side effect, full support for glm::mat4 to and from script is provided.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/26225263936266/98654005888908

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/97782015534477

**Comment by hifi-gustavo** [comment]
Build console output for commit: f82dc4569eedbbbc0ebb2153891bb78d5a709983 available at: https://gist.github.com/fc41bc3831f09b679c3f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.dmg

**Comment by ZappoMan** [comment]
@hyperlogic - you need to update with master.

**Comment by hifi-gustavo** [comment]
Build console output for commit: deb17e1f936a147299c76cbe599f1f60631bc8c5 available at: https://gist.github.com/fc41bc3831f09b679c3f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1a3c5b618eb42a87da22cbeb0d88e35b2f640c8 available at: https://gist.github.com/fc41bc3831f09b679c3f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7285.dmg

**Comment by cozza13** [comment]
Philip has tested this.

**Pull request merged**
