### PR TITLE
Created Landscaping App

### PR DESCRIPTION
**Pull request by RebeccaStankus**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2197/HighFidelity-Beta-PR11101-c5948f8b40807b607fac66b7d5b12f17f111acf1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2197/HighFidelity-Beta-PR11101-c5948f8b40807b607fac66b7d5b12f17f111acf1.exe

**Comment by themelissabrown** [comment]
@rebeccastankus can I get a test plan for this?

**Comment by RebeccaStankus** [comment]
@themelissabrown Yes, I haven't done a test plan before but have asked for some input on what it should include. I think I'm supposed to be meeting with someone tomorrow...

**Comment by themelissabrown** [comment]
No worries! All I really need to know is what steps should be followed to see the results of your code and what those results should be. If you look at other PR's marked QA Ready, they should all have test plans you can get ideas from.

**Comment by RebeccaStankus** [comment]
Ok. . great.  Thanks!

**Comment by RebeccaStankus** [comment]
TEST PLAN
Run script "landscaping.js"
- New button should appear on tablet titled "LANDSCAPE" with icon of hands holding a plant.
- Clicking on LANDSCAPE button should open an app with 4 buttons.
- "Tupelo" button should import an fbx entity of a tupelo tree in front of the avatar.
- "Cycas" button should import an fbx entity of a cycas plant in front of the avatar.
- "Dahlia" button should import an fbx entity of a dahlia flower in front of the avatar.
- "Grass" button should import an fbx entity of a grass patch in front of the avatar.
- Stopping the script should remove the LANDSCAPE button from the tablet

**Comment by tapalisa** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2512/HighFidelity-Beta-PR11101-c5948f8b40807b607fac66b7d5b12f17f111acf1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2512/HighFidelity-Beta-PR11101-c5948f8b40807b607fac66b7d5b12f17f111acf1.exe

**Pull request closed without merging**
