### PR TITLE
Improve HMD Menu page navigation

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Tablet menu page changes:
- Change title icon.
- Title icon visible only if not in root menu page.
- Title text made white and non-clickable.
- Clicking title icon takes you back a level (instead of to root).
- Make Save and Cancel in HMD settings dialogs return to Settings dialog (instead of to root).
- Miscellaneous fixes to a few dialogs.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12430/HighFidelity-Beta-PR13886-c29c9f9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12430/HighFidelity-Beta-PR13886-c29c9f9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12430/HighFidelity-Beta-Interface-PR13886-c29c9f9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12430/HighFidelity-Beta-PR13886-c29c9f9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12430/HighFidelity-Beta-Interface-PR13886-c29c9f9.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12574/HighFidelity-Beta-PR13886-f144308.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12574/HighFidelity-Beta-Interface-PR13886-f144308.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12574/HighFidelity-Beta-PR13886-f144308.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12574/HighFidelity-Beta-Interface-PR13886-f144308.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12700/HighFidelity-Beta-PR13886-ab47e16.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12700/HighFidelity-Beta-PR13886-ab47e16.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12700/HighFidelity-Beta-Interface-PR13886-ab47e16.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12700/HighFidelity-Beta-PR13886-ab47e16.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12700/HighFidelity-Beta-Interface-PR13886-ab47e16.exe

**Comment by ctrlaltdavid** [comment]
### Test Plan

A) HMD tablet. In HMD mode using the tablet, when navigating the Menu "app":
- Except on the first main menu dialog, the title should include a blue triangle icon that highlights when hovered and takes you to the previous dialog when pressed (i.e., not to the tablet home page).
- Each page's title should be white, non-highlighting, and non-clickable.
- In dialogs (e.g., the Settings dialogs) which have an "Save" and "Cancel" buttons down the bottom that closes the dialog, using these to close the dialog should return you to the previous screen (i.e., not to the tablet home page).

B) Desktop toolbar. In desktop mode using the toolbar, Settings meny dialogs with "Save" and "Cancel" buttons, the buttons should close the dialogs.

C) HMD toolbar. In HMD mode using the toolbar ... per A.

D) Desktop tablet. In desktop mode using the tablet ... per B except that "Save" and "Cancel" buttons take you to the main tablet page.

E) Miscellaneous fixes. Check the following in both HMD tablet and desktop toolbar modes:
- The title on the Menu > Settings > Controls page should be "Controls".
- The title on the Menu > Settings > Audio page should be "Audio Settings".
- The Menu > Developer > Network > Show Domain Connection Timing dialog should have a title "Domain Connection Timing" and there should not be an unusual amount of whitespace at the top of the page.
- The Menu > Developer > Entities > Entity Statistics dialog should have a title "Entity Statistics" and there should not be an unusual amount of whitespace at the top of the page.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
New menu arrows work across the board.

**Pull request merged**
