### PR TITLE
Fix skybox baking

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
[Bug](https://highfidelity.manuscript.com/f/cases/14039/Asset-Browser-files-used-for-skybox-URL-stay-in-a-pending-status-indefinitely-while-baking)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8612/app_12828_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8612/HighFidelity-Beta-PR12828-6e7f8a2ef69c31e3b9bc80a122ac0e021600a43a.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8632/app_12828_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8632/HighFidelity-Beta-PR12828-6e7f8a2ef69c31e3b9bc80a122ac0e021600a43a.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Image now has checkmark and functions as expected.

**Pull request merged**
