### PR TITLE
Emotes revisions per feedback

### PR DESCRIPTION
**Pull request by dooglifeSF**
Joshua's feedback on emotes was to increase the "size" of the actions so they are less subtle, more noticeable from a longer distance.  These emotes are pushed to be ~20% "bigger", more exaggerated.

A couple minor json tweaks as well.

Emote stand/sit claps, disagree, agree anims reworked.  13 anims in total.

https://highfidelity.atlassian.net/browse/DEV-539

### CODE REVIEW

**Comment by dooglifeSF** [comment]
Test plan:  
Run through the sit and stand versions of all clap variants, disagree variants and agree variants looking for any problems or pops.  These anims are largely the same as before, just exaggerated and accentuated to be visible at a larger distance.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21542/HighFidelity-Beta-PR16252-0fa7220.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21542/HighFidelity-Quest-Beta-PR16252-0fa7220.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21542/HighFidelity-Beta-PR16252-0fa7220.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21542/HighFidelity-Beta-Interface-PR16252-0fa7220.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21542/HighFidelity-Beta-PR16252-0fa7220.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21542/HighFidelity-Beta-Interface-PR16252-0fa7220.exe

**Pull request merged**
