### PR TITLE
Fix regression with 'Log in/Sign up' dialog is missing "Forgot Username?" and "Forgot Password?" links

### PR DESCRIPTION
**Pull request by ElderOrb**
the same as https://github.com/highfidelity/hifi/pull/12757 but for RC66

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8447/HighFidelity-Beta-PR12768-ccea3efe1e1d0714303d9c7aff54dc7a13db7b2c.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8451/HighFidelity-Beta-PR12768-ccea3efe1e1d0714303d9c7aff54dc7a13db7b2c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8451/HighFidelity-Beta-PR12768-ccea3efe1e1d0714303d9c7aff54dc7a13db7b2c.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Pull request merged**
