### PR TITLE
Fix away.js vulnerability

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
test this please

**Comment by huffman** [comment]
To test:
 1. Confirm that away.js works
 1. Confirm that if you open the scripting console and run `Messages.sendLocalMessage("Hifi-Away-Enable", "disable")` that away.js will no longer activate away mode
 1. Confirm that if you open the scripting console and run `Messages.sendLocalMessage("Hifi-Away-Enable", "enable")` that away.js will now activate away mode

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1782f97dbd9bacf23b0942beedb21d60f3a61fab available at: https://gist.github.com/4295dcbf347219b96749a2f1ace7de75<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8933-1782f97.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8933-1782f97.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1782f97dbd9bacf23b0942beedb21d60f3a61fab available at: https://gist.github.com/4295dcbf347219b96749a2f1ace7de75<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8933-1782f97.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8933-1782f97.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - QA Pass

**Pull request merged**
