### PR TITLE
MS17774: Enable advanced movement on first run

### PR DESCRIPTION
**Pull request by wayne-chen**
- Implementation of MS[#17774](https://highfidelity.manuscript.com/f/cases/17774)

**TEST PLAN**
- Launch Interface
- In `Settings > Controls`, "Advanced movement for VR" option should be checked
- Switch to HMD mode
- Moving with the left thumbpad / joystick to move around should work

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12318/HighFidelity-Beta-PR13863-4daa30c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12318/HighFidelity-Beta-PR13863-4daa30c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12318/HighFidelity-Beta-Interface-PR13863-4daa30c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12318/HighFidelity-Beta-PR13863-4daa30c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12318/HighFidelity-Beta-Interface-PR13863-4daa30c.exe

**Comment by qaAdamSmith82** [comment]
Mac/Desktop Pass

**Comment by jakram** [comment]
@conklin94122 WIN/VIVE PASS

**Comment by conklin94122** [comment]
We tested all platforms (including Android), both new and existing installs. All configurations look good.

**Comment by jakram** [comment]
@conklin94122 PR13863 PASS

Confirmed with all members. Marking as approved.

**Pull request merged**
