### PR TITLE
RC65: Fix font loading for MacOS via completely different font loading method

### PR DESCRIPTION
**Pull request by zfox23**
For some reason, loading `.ttf` fonts via `qrc:/` on MacOS doesn't work, even though it works on Windows and is supposedly supported. This PR fixes glyph loading on MacOS, with no behavioral change to font loading on other platforms.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. This one's simple! Open up various QML apps from within Interface in both HMD and Desktop. Also open those apps in Desktop mode when using the MacOS client.
    - Verify that all of the text you see isn't garbled nonsense or visually corrupted. Examples of QML apps include Wallet, GOTO, and Spectator Camera.

If you see this (or something like it), fail this PR:
image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7902/app_12602_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7902/HighFidelity-Beta-PR12602-c22d79041db348344ec3b16c3e9703410394ea29.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7902/HighFidelity-Beta-PR12602-c22d79041db348344ec3b16c3e9703410394ea29.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Checked Wallet, GoTo, and Marketplace, all text displayed without error. No glyphs to report! (Since this was Mac specific, could not check HMD or Spectator Cam, as neither is available on Mac)

**Comment by Qliemillar** [comment]
Reading more closely, we're going to check Windows/HMD as well for the sake of thoroughness. So! Currently testing again!

**Comment by Qliemillar** [comment]
Testing complete on Windows/HMD - PASS @conklin94122 

Checked Wallet, GoTo, Marketplace, and Spectator Cam. No glyphs on Windows either. Solid pass!

**Comment by conklin94122** [comment]
@sethalves Needs dev review, not just the label.

**Pull request merged**
