### PR TITLE
Fix reading model's "textures" property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This gets the model's "textures" property working again through to loading the modified textures in NetworkGeometry::setTextureWithNameToURL(), as evidenced by program log messages saying that the new texture has been requested and loaded.
This is ready for @sam / @clement to use and make the texture remapping apply to only the particular model (rather than all in the scene as used to be the case).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a59cbd1aca37e3fa5cb48a9f9717bd650fa8d02b available at: https://gist.github.com/5db50367e972b2306592<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6838.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6838.dmg

**Comment by ZappoMan** [comment]
How do we test this? Does this actually set the texture? what's the correct format of the "textures" property? Can you provide an example of a model with textures and what steps to take to replace the texture of it.

**Comment by ctrlaltdavid** [comment]
The format of the textures property is the same as the format of the "originalTextures" property, immediately below it in the entities editor.

Example model: 
    http://ctrlaltstudio.com/downloads/hifi/models/20763/external-textures.fbx

Example textures property that changes the diffuse texture: 
    diffuse:"http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png"

When you set the textures property to that value, you'll now see in the program log lines saying:
[01/15 14:15:23] [DEBUG] Updating texture named "diffuse" to texture at URL QUrl("http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png")
[01/15 14:15:23] [DEBUG] Starting request for: http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png
[01/15 14:15:24] [DEBUG] Request finished for http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png
[01/15 14:15:24] [DEBUG] Finished loading: http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png

When you delete the textures property, you'll now see in the program log a line saying:
[01/15 14:16:09] [DEBUG] Removing texture named "diffuse" by replacing it with no URL

**Comment by ZappoMan** [comment]
It doesn't seem to work David, this is what I get in my log...

```
[01/15 16:57:35] [WARNING] Could not evaluate textures property value: ""
[01/15 16:57:41] [WARNING] Could not evaluate textures property value: "diffuse:http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png,\nnormal:http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png,\nspecular:http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png,\nemissive:http://ctrlaltstudio.com/downloads/hifi/models/20763/target.png"
```

**Comment by ZappoMan** [comment]
never mind, now I see what I did wrong.... you must have the url's in quotes

**Pull request merged**
