### PR TITLE
Correctly grab tablet in 3rd person

### PR DESCRIPTION
**Pull request by druiz17**
Correctly grab tablet in 3rd person

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Be in HMD and third person
- bring up and the grab the tablet
- it should behave the same way if you grabbed it in first person

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3613/HighFidelity-Beta-PR11456-6332a53ee2bc9745ff7d0e5d9a8729a5be5f8759.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3613/HighFidelity-Beta-PR11456-6332a53ee2bc9745ff7d0e5d9a8729a5be5f8759.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Be in HMD and third person | Pass
bring up and the grab the tablet | Pass
it should behave the same way if you grabbed it in first person | Pass

All good to me!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
