### PR TITLE
CR for Job #20283 - Clean up scripts that have recently been added. 

### PR DESCRIPTION
**Pull request by cozza13**
Code Review for Job #20283 - Workitem available at https://www.worklist.net/20283

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
vrUI.js shouldn't really be added: it was just a prototype that I did to demonstrate what could possibly be done should people want it done. In particular, there's only one working menu item that pulls up an old vrChat prototype manually copied into the script.

**Comment by cozza13** [comment]
@ctrlaltdavid OK I can take it out. It was added to available scripts, so I wanted to correctly categorize it.

**Comment by ctrlaltdavid** [comment]
Heh, I didn't realize it had already been added! Thanks for removing it; it's not production quality.

**Comment by ZappoMan** [comment]
Will merge after demos are complete.

**Pull request merged**
