### PR TITLE
Fix blue screen in VR mode due to NaN values

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR fixes the bug that appears when CharacterController::playerStep add NaN values that end up affecting the avatar transform and corrupting all derived data.

https://highfidelity.manuscript.com/f/cases/16538/Randomly-going-blind-from-a-blue-screen-in-VR-mode-when-Interface-does-not-have-focus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11310/HighFidelity-Beta-PR13610-949cd39.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11310/HighFidelity-Beta-PR13610-949cd39.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11310/HighFidelity-Beta-Interface-PR13610-949cd39.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11310/HighFidelity-Beta-PR13610-949cd39.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11310/HighFidelity-Beta-Interface-PR13610-949cd39.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Pass @conklin94122 

Once again did all the things which tend to cause the blue screen, but it did not occur!

**Comment by hyperlogic** [comment]
Adding link to PR #13592

**Pull request closed without merging**
