### PR TITLE
Update Scene on ZoneEntity update

### PR DESCRIPTION
**Pull request by zzmp**
ZoneEntity is unique in that it is not updated
every frame that it is rendered, but only
when the avatar moves.

This introduces custom code so that the
RenderableZoneEntity initiates an update
in the EntityTreeRenderer on update,
to improve usability of zone editing.

### CODE REVIEW

**Comment by zzmp** [comment]
Set as DNM because I committed on top of #7186. This should be merged *after* that PR.

**Comment by zzmp** [comment]
#### Testing

- Ensure zone's are still detected properly.
- Ensure zone edits result in immediate changes to the zone.
- Ensure other edits don't result in anything unexpected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17657ab702e3e7a33b28721fc9ba15d518a5da1f available at: https://gist.github.com/84de9385c9fea38f44e2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7192.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7192.dmg

**Comment by cozza13** [comment]
With https://github.com/highfidelity/hifi/pull/7186 merged I removed Do Not Merge.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c20bd6cbbc0b9b368806711842b12ea56f9ed2e3 available at: https://gist.github.com/84de9385c9fea38f44e2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7192.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7192.dmg

**Comment by OmegaHeron** [comment]
QA Passes.  Tested with Windows - all settings apply in real time without need to move AV.  It should be noted visibility of skybox toggle still does nothing, but, that's really not within scope of this PR as I see it.

**Comment by zzmp** [comment]
@OmegaHeron what do you mean by "skybox toggle"? Can you include a screenshot? Do you mean the combobox?

**Comment by OmegaHeron** [comment]
@zzmp - visible flag for zone - it used to toggle zone visibility/action on scene.  It's a handy thing for just seeing before/after.

capture2

**Comment by zzmp** [comment]
@OmegaHeron noted in Asana. Not sure if you had already. Thanks for the heads up and the screenshot!

**Pull request merged**
