### PR TITLE
Beta Release 41 - Includes up to Developer Release 6603

### PR DESCRIPTION
**Pull request by cozza13**
- Force locked entities to be static in bullet 
 - Treat locked like other properties that affect simulation 
 - Add unpublishedScripts content to the JS project
 - Fix AC playback script not logging 
 - Prevent ping-ponging of texture quality when oversubscribed 
 - Add BC7 compression support 
 - Make server entity scripts respect the script whitelist
 - Fix crash for Zone with 'compoundURL' property 
 - Added refreshing of Account Managers access token 
 - Fix eye behavior in recording playback 
 - MeshPartPayload keeps weak pointer to Model 
 - IK tuning and bug fixes 
 - Remove version difference from update dialog 
 - This PR will fix the attachments to be scaled based on a models naturalDimensions
 - Fix crash in entity ScriptEngine 
 - Ensure AvatarMixerClientData AvatarData has session ID 
 - Display spinner in Web controls when they're loading an HTTP page 
 - DS HTTP auth will no longer accept any password if the assigned password is blank 
 - Should fix crash in general setting dialog 
 - Fix/check extension running scripts 
 - Added a LowVelocityFilter to the input system 
 - Fix compressed texture size evaluation and Cleaning up the texture counters (number and memory) for better reporting 
 - Fix rotation axes of stopwatch hands 
 - Replace the original noise gate with a pro-audio style noise gate
 - Fix up queryAACubes before sending imported entities to server 
 - If something is locked but in motion, make it kinematic rather than static 
 - Never store an address with an empty host 
 - Require a valid access token and expiry to attempt token refresh 
 - Do not allow divide by zero on assigning mip data 
 - Update baking tool to enable compression and re-baking 
 - Fix code that was using old raypickInfo.properties field 
 - Prevent Infinite loop in FBXReader 
 - Fix collision signal emission for static objects

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/193/HighFidelity-Beta-PR10556-54bca1e53d419643f0c1661eca4d295c77b61e9c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/193/HighFidelity-Beta-PR10556-54bca1e53d419643f0c1661eca4d295c77b61e9c.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  Fail, protocol mismatch when trying to visit ```dev-playa``` and ```dev-demo```.   Tried 4 separate times to reload Sandbox and the same effect occurred.  If we can check the code for the ```protocol mismatch``` issue as I just posted in Slack to alert the dev team this might be a simple fix.


**Domain** |localhost | |
**Render Rate**: |51 
**Present Rate**: |52 
**Present New Rate**: |52 
**CPU Buffer Count**: |2116 
**GPU Buffer Count**: |709 
**CPU Texture Count**: |230
**GPU Texture Count**: |171
**Triangle Count**: |235897
**Triangle Rate**: |13105388
**API Drawcall Count**: |179
**Drawcall Count**: |1619
**Drawcall Rate**: |89944
**State Changes Texture Count**:|302
**Pipeline Count**: |48
**Item Opaques**: |269
**Item Translucents**: |60
**Item Lights**: |12
**Timing Opaques**: |1.057
**Timing Translucents**: |0.199
**Timing Lighting**: |0.017
**Render Frame**: |1.89


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|FAILURE - Protocol mismatch when attempting to get to ```dev-playa``` and ```dev-demo```
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|FAILURE - Unable to get to ```dev-playa``` protocol mismatch
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by OmegaHeron** [comment]
Same issue for me as @kevinmthomasse with dev-welcome being incompatible with this build.  Will need a mitigation for that @cozza13

**Comment by ZappoMan** [comment]
Bug Report - I only see "Loading Content" constantly... even though it seems like all content is loaded... I think this is a QA Fail.

**Comment by OmegaHeron** [comment]
Yeah @zappoman - I tried to bring that up a few days ago in that Loading Content is never dismissed even though every indicator points to that being incorrect.  It's not new to this PR but has crept in somewhere leading up to here.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/213/HighFidelity-Beta-PR10556-252298938b89a98235efe0d58306435d67c5b50d.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/215/HighFidelity-Beta-PR10556-0a7a42bdc3855b1b08e92930f182815276130f86.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/215/HighFidelity-Beta-PR10556-0a7a42bdc3855b1b08e92930f182815276130f86.dmg

**Comment by ZappoMan** [comment]
Bug Report - when I start up in my Life domain (which is just the tutorial content with a couple of cube primitives) -- it takes a very long time before audio can be heard, and the "Processing" value seems to hang out at 3 for a very long time (several minutes)... if I quit while processing is > 0... the interface will hang in the background and must be stopped via Task Manager.

This feels like a QA Fail.

**Comment by kevinmthomasse** [comment]
re-testing 0a7a42b

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/218/HighFidelity-Beta-PR10556-bf057219acdeb201a1f78be085aa017eae187bd9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/218/HighFidelity-Beta-PR10556-bf057219acdeb201a1f78be085aa017eae187bd9.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: SUCCESS bf057219acdeb201a1f78be085aa017eae187bd9.exe```  I tried to replicate @ZappoMan issue however was unable to.  Audio was fluid and flawless on  ```https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/218/HighFidelity-Beta-PR10556-bf057219acdeb201a1f78be085aa017eae187bd9.exe``` Everything worked as expected.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |52 |60
**Present Rate**: |60 |70 |52
**Present New Rate**: |50 |43 |4
**CPU Buffer Count**: |581 |601 |1077
**GPU Buffer Count**: |146 |122 |239
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |98 |78 |111
**GPU Texture Count**: |52 |44 |59
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |69062 |126528 |162555
**Triangle Rate**: |4316375 |7908000 |54185000
**API Drawcall Count**: |45 |44 |74
**Drawcall Count**: |45 |40 |79
**Drawcall Rate**: |2812 |2500 |26333
**State Changes Texture Count**:|69 |49 |80
**Pipeline Count**: |26 |30 |29
**Item Opaques**: |35 |189 |111
**Item Translucents**: |8 |34 |6
**Item Lights**: |4 |36 |15
**Timing Opaques**: |0.119 |0.484 |0.468
**Timing Translucents**: |0.018 |0.028 |0.019
**Timing Lighting**: |0.012 |0.029 |0.016
**Render Frame**: |0.524 |1.742 |1.66


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by Nex-Pro** [comment]
### #10556 QA. Beta Release 41

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam

HMD: Htc Vive.

## QA Test
**QA Tester**: Unknown user
**localhost 'createTestBlocks.js' Result**:  SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**:  FAIL
**Additional Test Results + Observations**:

Loading Content indicator never goes away.

No audio on startup. Normal system devices were selected.
Teleport target very laggy. Laggy behaviour went away on restart of interface. This has been reported previously.
Crash attempting to activate audio. ( selected alternate output device )
No audio on restart.
Audio became active after swapping mic back to default USB headset ( for my system ) Then setting 4k monitor as output. Sound then became active. Setting USB headset as output correctly changed output to Headset.

Attempted and succeeded in rebuilding the test blocks using only far grab with two controllers.

In tutorial I grabbed the vase in the room before the exit.
The other items on the shelf were immediately moved to 0,0,0 as previously reported.
On restarting interface those items were in fact still on the shelf. This is possibly diagnostic of a client-side error ( as seen some time ago ) where interface somehow gets/creates positional updates for the entities that were moved via collions. The domain server correctly locates the entities. Restarting interface reveals the true positions of those ents.

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |89 |90 |
**Present Rate**: |89 |89 |
**Present New Rate**: |39 |89 |
**CPU Buffer Count**: |1888 |30639 |
**GPU Buffer Count**: |386 |858 |
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |218 |212 |
**GPU Texture Count**: |96 |154 |
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |165630 |2102759 |
**Triangle Rate**: |15057272 |210275900 |
**API Drawcall Count**: |69 |199 |
**Drawcall Count**: |2974 |5228 |
**Drawcall Rate**: |270363 |522800 |
**State Changes Texture Count**:|108 |216 |
**Pipeline Count**: |32 |38 |
**Item Opaques**: |79 |351 |
**Item Translucents**: |24 |36 |
**Item Lights**: |5 |47 |
**Timing Opaques**: |0.221 |0.982 |
**Timing Translucents**: |0.046 |0.053 |
**Timing Lighting**: |0.01 |0.02 |
**Render Frame**: |0.599 |2.101 |


desktop VSYNC off:

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |424 |313 |
**Present Rate**: |419 |318 |
**Present New Rate**: |250 |215 |
**CPU Buffer Count**: |2017 |30651 |
**GPU Buffer Count**: |682 |872 |
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |213 |212 |
**GPU Texture Count**: |160 |153 |
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |238089 |661330 |
**Triangle Rate**: |47617800 |220443333 |
**API Drawcall Count**: |170 |169 |
**Drawcall Count**: |1979 |169 |
**Drawcall Rate**: |395800 |56333 |
**State Changes Texture Count**:|298 |197 |
**Pipeline Count**: |49 |34 |
**Item Opaques**: |234 |290 |
**Item Translucents**: |76 |12 |
**Item Lights**: |10 |23 |
**Timing Opaques**: |0.748 |1.007 |
**Timing Translucents**: |0.195 |0.02 |
**Timing Lighting**: |0.013 |0.014 |
**Render Frame**: |1.36 |2.051 |


Desktop VSYNC on:

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |34 |
**CPU Buffer Count**: |1721 |30454 |
**GPU Buffer Count**: |517 |636 |
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |193 |207 |
**GPU Texture Count**: |137 |123 |
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |179044 |685739 |
**Triangle Rate**: |11190250 |40337588 |
**API Drawcall Count**: |149 |198 |
**Drawcall Count**: |2919 |444 |
**Drawcall Rate**: |182437 |26117 |
**State Changes Texture Count**:|269 |230 |
**Pipeline Count**: |46 |33 |
**Item Opaques**: |220 |340 |
**Item Translucents**: |66 |35 |
**Item Lights**: |10 |35 |
**Timing Opaques**: |0.781 |1.207 |
**Timing Translucents**: |0.125 |0.038 |
**Timing Lighting**: |0.015 |0.015 |
**Render Frame**: |1.404 |2.316 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**Check**
**Test 2**|Install a fresh copy of "Home' and do tutorial|**PASS**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**PASS** After changing sound settings. See other notes.
**Test 4**|Launch firework, on dev-playa, can other hear?|**PASS**
**Test 5**|Switch avatar and make sure it does not crash|**PASS**
**Test 6**|Test group functions|**UNTESTED**
**Test 7**|Test Ambisonic audio with markeplace item|**PASS**
**Test 8**|Enrure that you can distance grab|**PASS**
**Test 9**|Bring up and edit an objects with hand controllers|**PASS**
**Test 10**|Test PAL functionality|**Insufficient users available to make a good test**
**Test 11**|Test Tablet in 2D and 3D|**PASS**

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 - gtx970

Overall = Pass

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Windows 10 - i5 6500 - GTX970

Desktop mode - 1600x900 maximized window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |70 |60 |70
**CPU Buffer Count**: |2044 |30945 |341
**GPU Buffer Count**: |691 |1254 |163
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |220 |227 |60
**GPU Texture Count**: |168 |202 |56
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |208302 |770073 |30048
**Triangle Rate**: |11572333 |48129562 |1669333
**API Drawcall Count**: |167 |207 |18
**Drawcall Count**: |2982 |1029 |18
**Drawcall Rate**: |165666 |64312 |1000
**State Changes Texture Count**:|299 |252 |44
**Pipeline Count**: |50 |35 |24
**Item Opaques**: |241 |353 |4
**Item Translucents**: |72 |32 |3
**Item Lights**: |11 |37 |0
**Timing Opaques**: |0.936 |1.293 |0.087
**Timing Translucents**: |0.169 |0.055 |0.037
**Timing Lighting**: |0.025 |0.031 |0.041
**Render Frame**: |1.927 |3.059 |1.397

HMD CV1 shows 90/90/90 FPS my new room setup makes it near impossible to collect stats and copy as I can't reach keyboard/mouse with HMD on to copy it out.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok - other than no access to dev-demo as has been case for months.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Ok
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Partial Fail - will document further, not new to this PR.
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|Not tested
**Test 10**|Test PAL functionality|Pass in so far as what I could see with myself and my alt on LAN domain.
**Test 11**|Test Tablet in 2D and 3D|Pass

Other tests
Progress indicator for scene load dismisses properly.  Pass
Domain server problem with access token fail.  Pass
Ping-pong texture loading/unloading/reloading issue.  Seems to be cleaned up now.
GPU Ram can drop to 0 instantly then textures fail to load.  Fixed/Pass.


Groups
Will discuss this on fogbugz or elsewhere - Problem I'm seeing is not unique to this PR.  Basically if I connect a stack to my HF ID and do all the rest as in assign it to a domain/place -- then add my group it no longer gives me ranks and ability to assign permissions to those ranks in DS web console.  I went back several master builds and see same in all.  Needs to be looked into for sure.

**Comment by OmegaHeron** [comment]
Issue with groups I found self-resolved, suspect it was a temporary issue with backend or just gods of random at play.

**Pull request merged**
