### PR TITLE
reformat operating hours to [[open,close]]

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

- Check that the domain-server sends out its operating hours as [[ OPEN_TIME, CLOSE_TIME ]], where X_TIME is formatted as HH:MM.

See #8111 for what to look for in the logs to check this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e03974181acca42ee1a333ded811e09b2b951709 available at: https://gist.github.com/b92325a3d4e46f38f8d2238c8cac1980<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8119.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8119.dmg

**Comment by Nex-Pro** [comment]
#### PASS

***See attached log snippet***

[domain_server_log_snippet.txt](https://github.com/highfidelity/hifi/files/327761/domain_server_log_snippet.txt)

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Tw92w85i&#x2F;18-re-format-operating-hours"> re-format operating hours</a>

**Pull request merged**
