### PR TITLE
Adjustment to position and visibility of grab sphere.

### PR DESCRIPTION
**Pull request by hyperlogic**
* The grab sphere used to detect objects for near grabbing is now 10 cm in radius instead of 4 cm.
* The grab sphere position and far grab laser origin has been moved to be centered around the vive hand controller.
* The vive hand controller position has been adjusted to better fit in the avatar's hand.
* The visual representation of this grab sphere is always hidden, by default.
* The visual sphere can be re-enabled via the "Developer > Show Grab Sphere" menu item.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1950/more-work-on-grab-indicators

**Comment by hyperlogic** [comment]
QA Test plan:
* Ensure that the gray equip sphere is no longer visible.
* Make sure that near grab still functions.
* Make sure that the far laser still functions and is not misaligned when used to pick up objects in the world.
* Make sure that the far laser still functions and is not misaligned when used over UI elements.
* Make sure that the far lasar still functions and is not misalgiend when used on the marketplace tablet.

**Comment by hyperlogic** [comment]
@huffman when this PR gets approved, please make sure the the changes to tutorial/viveControllerConfiguration.js are migrated to the asset set used for the steam tutorial.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 55c062098a514350a5463d21c673f24e74fccbd1 available at: https://gist.github.com/2c5c25085e3248bcb1ada8e39b6acb06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8864-55c0620.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8864-55c0620.dmg

**Comment by PhilipRosedale** [comment]
Used and seems great.  @tony @huffman can you fix the mentioned config stuff and pull?

**Pull request merged**
