### PR TITLE
Fix application names in installer prompt

### PR DESCRIPTION
**Pull request by huffman**
Fixes the "X cannot be installed while X is running." dialogs in the installer. The text would previously say "interface" for the console and "console" for interface, that is now fixed. The text would also include the version in non-production builds, I have removed that.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f72a7601514e8f635e6321ab38d562be885dad2a available at: https://gist.github.com/44f14dabb2dfe71de959254c43076e3e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.dmg

**Comment by huffman** [comment]
To test:

1. With interface and the console running in the background, try to install this build. Confirm that:
  1. The installer says "Interface" when prompting for you to close interface. Then close interface.
  1. The installer says "Sandbox" when prompting for you to close the console. Then close the console.
1. Ensure the console is not running. Run the domain server and assignment-client separate from the console. You can do this by navigating to C:\Program Files\High Fidelity in your file browser and double clicking "domain-server.exe" and "assignment-client.exe." Try installing this build again. Confirm that:
  1. The installer says "Domain Server" when prompting for you to stop the domain server. Then close the domain server.
  1. The installer says "Assignment Client" when prompting for you to stop the assignment client. Then close the domain server.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a4b7e54e4d776b6f4aee969791fa863e2457ce49 available at: https://gist.github.com/44f14dabb2dfe71de959254c43076e3e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37469f16c823b725e93dbdfea6f777cfbede881a available at: https://gist.github.com/44f14dabb2dfe71de959254c43076e3e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7695.dmg

**Pull request merged**
