### PR TITLE
Fix deadlock on shutdown from blocking texture/model loads

### PR DESCRIPTION
**Pull request by zzmp**
- Register gpu::TexturePointer with Qt
- Alias FBXGeometry::Pointer and register with Qt
- Change threaded resource readers to use smart pointers

### CODE REVIEW

**Comment by zzmp** [comment]
See: https://app.asana.com/0/74051501495175/109187623266499.

#### Testing

Go to a domain (like default Home content) and quit mid-load.
Interface will sometimes hang (appear to quit, but process sticks around).
With this PR, it should quit cleanly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8cce5742659572d487d611df4ccf8c4d25d95582 available at: https://gist.github.com/f5c74b1eac108e372797b1b957ca6997<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 449567a74bc0ec4a330d092ec3e4fb65b7a95b7c available at: https://gist.github.com/f5c74b1eac108e372797b1b957ca6997<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 449567a74bc0ec4a330d092ec3e4fb65b7a95b7c available at: https://gist.github.com/f5c74b1eac108e372797b1b957ca6997<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ee151d26dc08918626ebea81446de5446cd7b9b available at: https://gist.github.com/f5c74b1eac108e372797b1b957ca6997<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 948af75f8a6f342a65c5b281b3994c5a15f8ad70 available at: https://gist.github.com/f5c74b1eac108e372797b1b957ca6997<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7722.dmg

**Comment by sethalves** [comment]
I've been running this for a couple of hours and haven't seen a hang-on-exit yet.

**Comment by OmegaHeron** [comment]
Windows 7
This PR
10 Launches into Home scene - quitting from appearance of first object to maybe +2 seconds after to shake things up a bit.  All 10 tries Interface terminated.  3 Times it took an extended time to terminate 10-15 seconds.

Current Production release (RC6)
Same mechanic as above.  10 cycles - 8 fails to close requiring manual terminate via task manager.

General functional smoke test looks good as well.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7722
**Testing Architecture:** 64-bit PC Laptop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Successful test.  Confirmed similar results as @seth and @omegaheron, no issue upon exit.
**Successful Logout/Crash:** Successful test.

**Pull request merged**
