### PR TITLE
removing old game sample from script-archive

### PR DESCRIPTION
**Pull request by misslivirose**

### CODE REVIEW

**Comment by ZappoMan** [comment]
No need for QA Approve since this is removing old code... Presumably once the build completes we can merge... just as a sanity check.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6723/app_12293_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6723/HighFidelity-Beta-PR12293-d0a0120dfe129e095525349b94a6bb3038ff7828.dmg

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6771/app_12293_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6771/HighFidelity-Beta-PR12293-d0a0120dfe129e095525349b94a6bb3038ff7828.dmg

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6798/app_12293_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6798/HighFidelity-Beta-PR12293-d0a0120dfe129e095525349b94a6bb3038ff7828.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6798/HighFidelity-Beta-PR12293-d0a0120dfe129e095525349b94a6bb3038ff7828.dmg

**Pull request merged**
