### PR TITLE
New Controller interfaces/api

### PR DESCRIPTION
**Pull request by ZappoMan**
This PR adds the following:
* New JS APIs to allow you to access input controllers as a standard canonical controller, or directly as specific types of hardware.
* You can now add "mappings" that act as filter graph style routes to map hardware inputs through standard input formats and into application actions.
* Standard input mappings for Gamepads and Hydras have been reworked
* Built in mappings are managed as json files (in the future we could use this to allow people to load their own custom mappings)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5233577d249521fdd7e700e50d65fd77922556c0 available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49e7d42c2ccb8181e90afe646ff7ca83958f744d available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2f27054f48781ad11adb012e993241dceb54395 available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80d3d848a29ce325f239c27f760dec7b562acfe7 available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2f27054f48781ad11adb012e993241dceb54395 available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5fd3424b8503956c44a43f67baddc2bca3209b8 available at: https://gist.github.com/729f9aeaa1b291c584ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6242.dmg

**Pull request merged**
