### PR TITLE
Fix memory corruption when running scripts using Script.require().

### PR DESCRIPTION
**Pull request by hyperlogic**
The lambdas in ScriptEngine::fetchModuleSource() were referencing local stack variables by reference.  If loading the script takes longer then 500 ms, this can result in these lambdas being invoked AFTER the captured locals have been destroyed.  This could lead to un-expected results including memory corruption.

To workaround this issue the QTimer and QEventLoop variables are allocated on the heap and held onto by a shared_ptr. This shared_ptr is passed to the lambda. This will not result in cycles and should result in the QTimer and QEventLoop being destroyed when the BatchLoader object they are connected to is deleted.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10977/HighFidelity-Beta-PR13497-ac6fcf0.apk

**Comment by hyperlogic** [comment]
Sadly, there is no easy way to reproduce this crash, because it is timing related and there aren't that many scripts that use Script.require().  It is more likely to happen on slower machines tho.

QA Test plan:
  * Run interface
  * Load the clap app from the marketplace.
  * Load the emoji app from the marketplace.

Expected result:
  * The clap app and the emoji app work as expected and interface doesn't crash.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10977/HighFidelity-Beta-PR13497-ac6fcf0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10977/HighFidelity-Beta-Interface-PR13497-ac6fcf0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10977/HighFidelity-Beta-PR13497-ac6fcf0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10977/HighFidelity-Beta-Interface-PR13497-ac6fcf0.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Interface does not crash when running Clap app and Emoji app from Marketplace

**Pull request merged**
