### PR TITLE
V0.86.0 RC

### PR DESCRIPTION
**Pull request by shanzzam**
Release Candidate for RC86

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22379/HighFidelity-Beta-PR16466-10a1ee2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22379/HighFidelity-Quest-Beta-PR16466-10a1ee2.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22379/HighFidelity-Beta-PR16466-10a1ee2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22379/HighFidelity-Beta-Interface-PR16466-10a1ee2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22379/HighFidelity-Beta-PR16466-10a1ee2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22379/HighFidelity-Beta-Interface-PR16466-10a1ee2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22416/HighFidelity-Beta-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22416/HighFidelity-Beta-Interface-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22416/HighFidelity-Beta-PR16466-b14c1ee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22416/HighFidelity-Quest-Beta-PR16466-b14c1ee.apk)

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22419/HighFidelity-Beta-PR16466-b14c1ee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22419/HighFidelity-Quest-Beta-PR16466-b14c1ee.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22419/HighFidelity-Beta-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22419/HighFidelity-Beta-Interface-PR16466-b14c1ee.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22423/HighFidelity-Beta-PR16466-b14c1ee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22423/HighFidelity-Quest-Beta-PR16466-b14c1ee.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22423/HighFidelity-Beta-PR16466-b14c1ee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22423/HighFidelity-Beta-Interface-PR16466-b14c1ee.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22423/HighFidelity-Beta-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22423/HighFidelity-Beta-Interface-PR16466-b14c1ee.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22452/HighFidelity-Beta-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22452/HighFidelity-Beta-Interface-PR16466-b14c1ee.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22452/HighFidelity-Beta-PR16466-b14c1ee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22452/HighFidelity-Quest-Beta-PR16466-b14c1ee.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22452/HighFidelity-Beta-PR16466-b14c1ee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22452/HighFidelity-Beta-Interface-PR16466-b14c1ee.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22525/HighFidelity-Beta-PR16466-f38509d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22525/HighFidelity-Quest-Beta-PR16466-f38509d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22525/HighFidelity-Beta-PR16466-f38509d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22525/HighFidelity-Beta-Interface-PR16466-f38509d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22525/HighFidelity-Beta-PR16466-f38509d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22525/HighFidelity-Beta-Interface-PR16466-f38509d.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22578/HighFidelity-Beta-PR16466-f38509d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22578/HighFidelity-Beta-Interface-PR16466-f38509d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22578/HighFidelity-Beta-PR16466-f38509d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22578/HighFidelity-Quest-Beta-PR16466-f38509d.apk)

**Comment by shanzzam** [comment]
Released!

**Pull request closed without merging**
