### PR TITLE
RC63 hotfix: fixing lighting on scattering skin bug 11802

### PR DESCRIPTION
**Pull request by samcake**
FIx the scattering ambient lighting diffuse which was too dark (got divided by PI) compared to non 
scattering
## TEST PLAN and repro
https://highfidelity.manuscript.com/f/cases/11802/Photo-Real-Female-Avatar-has-hair-seaming-issues

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6660/app_12273_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6660/HighFidelity-Beta-PR12273-3d9985fa6732e1a0a1f5431f866c56a34c65ab06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6660/HighFidelity-Beta-PR12273-3d9985fa6732e1a0a1f5431f866c56a34c65ab06.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Repro:**

**PR Fix:**


**Pass** @divyaelango88  @conklin94122

**Pull request merged**
