### PR TITLE
Fix another audio failure

### PR DESCRIPTION
**Pull request by kencooke**
This PR fixes a failure case where isFormatSupported(mixFormat) returns false on some systems, when format is WAVEFORMATEXTENSIBLE with channels > 2,  audio enhancements in "Speaker Properties/Enhancements" are not disabled, and dwChannelMask is nonzero but does not match the speaker configuration.

Solved by updating WASAPI plugins to convert WAVEFORMATEX to WAVEFORMATEXTENSIBLE with dwChannelMask = KSAUDIO_SPEAKER_DIRECT.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

On a system with an integrated "Realtek High Definition Audio" device, use the Windows audio settings to configure "Speaker Setup" as 5.1 channel, and do not check "disable all enhancements". Then launch Interface from this PR, and verify that audio output now works in this configuration.

speakersetup
speakerproperties

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1b313d9aa2ff05cf240d912223e540e03c757a4 available at: https://gist.github.com/f8ac1834ca9cfd9c3d45dc02f22268ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9468-e1b313d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9468-e1b313d.dmg

**Comment by nbq** [comment]
Testing this one now

**Comment by nbq** [comment]
Tester: Coal
CPU: i7 6700k
GPU: GF 970
OS: Windows 10

Configured Sound setup to use 5.1 audio and made sure that `Disable all enhancements`, or as it was called on my machine `Disable all sound effects`, was not checked, applied all of the settings and ran this PR. I tested using speakers as output and webcam as input and I was able to hear the server echo of myself and was also able to hear system sounds such as the sounds on the tutorial and other Interface sound effects.

QA PASS

**Pull request merged**
