### PR TITLE
Bug fix 8610

### PR DESCRIPTION
**Pull request by NissimHadar**
Looking at this test:
https://github.com/highfidelity/hifi_tests/blob/master/tests/engine/render/material/roughness/test.md

the metallic raw of shapes should look much more shiny and reflective on the left.  Before the fix, the objects are a matte grey colour.  After the fix - the reflections are clear. 
The bug can be seen in build 7340 .. 7348.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4435/HighFidelity-Beta-PR11684-bfab4668279a14f683a26b35778e328c8c1e6260.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4435/HighFidelity-Beta-PR11684-bfab4668279a14f683a26b35778e328c8c1e6260.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by Nex-Pro** [comment]
@NissimHadar Could you please clarify what metallic raw means.

**Comment by YuppyPlays** [comment]
Testing complete:

[Using test plan steps from: https://github.com/highfidelity/hifi_tests/blob/master/tests/engine/render/material/roughness/test.md]

**Pass** - the only difference I can see in image below compared to test plan is the skybox which spawns in the script, though I assume this is intended, let me know if otherwise.
image

**Comment by NissimHadar** [comment]
Correct.  What is being demonstrated is the reflections on the upper-left
objects.

**Pull request merged**
