### PR TITLE
Restore text3d overlay

### PR DESCRIPTION
**Pull request by howard-stearns**
Update text3d shader post pbr.

### CODE REVIEW

**Comment by howard-stearns** [comment]
The real 'diff' for this PR is libraries/render-utils/src/sdf_text3D.slf vs the new sdf_text3D_overlay.slf

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/107202720063021

**Comment by howard-stearns** [comment]
Testing notes: see ticket.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f60bb1faa5ef0ebb829795f67803b99459807505 available at: https://gist.github.com/2a54d04595c6e7025e2d56c3084c04e4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7599.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7599.dmg

**Comment by howard-stearns** [comment]
Copying repro steps from ticket:
1) run latest interface, with edit.js
2) enable edit, select an entity...
3) grab the rotate handles... notice you don't see the rotate percentage text

**Comment by Triplelexx** [comment]
Tested & passed on Win 10 with Radeon.

**Pull request merged**
