### PR TITLE
Fix js array never being cleared

### PR DESCRIPTION
**Pull request by danteruiz**
Fixes the issue of an js array not being cleared and keeps on consuming memory

- ticket
https://highfidelity.manuscript.com/f/cases/19329/Memory-Leak-GoTo-transition

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- switch between domain
- memory consumption should not get out of control.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13850/HighFidelity-Beta-PR14202-ec877c2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13850/HighFidelity-Beta-PR14202-ec877c2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13850/HighFidelity-Beta-Interface-PR14202-ec877c2.dmg

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13854/HighFidelity-Beta-PR14202-ec877c2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13854/HighFidelity-Beta-PR14202-ec877c2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13854/HighFidelity-Beta-Interface-PR14202-ec877c2.dmg

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

Pass- Tested by jumping between several Domains and waiting for a few minutes, Used the same pattern that procured the defect prior. No unusual memory load (<3k MB).
Pass- Tested by Refreshing content, normal load below 3k
Pass -Tested by Logout/Login, normal load below 3k

**Pull request merged**
