### PR TITLE
use Qt menu hotkeys to drive camera-mode changes

### PR DESCRIPTION
**Pull request by sethalves**
- use Qt menu hotkeys to drive camera-mode changes

### CODE REVIEW

**Comment by sethalves** [comment]
Test Plan
- launch interface and click on interface to gain focus
- press Alt-F to enable first person view
- press Alt-O to enable third person view
- press Alt-H to enable mirror-mode view, but not when using an HMD

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1901/HighFidelity-Beta-PR11037-97756e6140dc1677282c114bc008ae927ac5c5ea.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1901/HighFidelity-Beta-PR11037-97756e6140dc1677282c114bc008ae927ac5c5ea.dmg

**Comment by anshuman64** [comment]
@ZappoMan should these be "Alt" or "Ctrl"?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1907/HighFidelity-Beta-PR11037-766c6f48c3b9acf016aae10b8e342eb8b1d39e61.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1907/HighFidelity-Beta-PR11037-766c6f48c3b9acf016aae10b8e342eb8b1d39e61.dmg

**Comment by ZappoMan** [comment]
I think Qt has a modifier that is ctrl on windows and the splat key on the mac. Generally we should use that modifier. Alisa has a great summary of best hot key suggestions.

**Comment by sethalves** [comment]
http://doc.qt.io/qt-5/qkeysequence.html

`Note that on macOS, the Ctrl value corresponds to the Command keys on the Macintosh keyboard, and the Meta value corresponds to the Control keys.`

...and now I'm paralysed with confusion.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1995/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.dmg

**Comment by sethalves** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1998/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2009/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2024/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows2016/2024/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.exe

**Comment by Nex-Pro** [comment]
Giving this a workout.

**Comment by Nex-Pro** [comment]
Tested on windows with Vive. 

**PASS on Windows**

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2033/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows2016/2033/HighFidelity-Beta-PR11037-9c9cfad4c483ad8d626c2721ad8fb245ec76cfff.exe

**Pull request merged**
