### PR TITLE
fix obj sans material

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that caused obj models with no material to randomly use the materials of other things in the view

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- in a complicated scene, rez an obj model that has no material.  Here is one: http://headache.hungry.com/~seth/hifi/hifi-openscad/models/0968f354-8e46-42db-b1ae-c3ff54ab2678-visual.obj
- move around it and view it from different angles.
- note that it stays a matt grey rather than taking on the look of other things in the scene

**Comment by hifi-gustavo** [comment]
Build console output for commit: b945d9c4cb92b80a78846108444556c35d57bb4f available at: https://gist.github.com/dcfff44ae5dd80b5896043f82c82b203<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9948-b945d9c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9948-b945d9c.dmg

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
#9948 QA.

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.

Specific tests:

in a complicated scene, rez an obj model that has no material. Here is one: http://headache.hungry.com/~seth/hifi/hifi-openscad/models/0968f354-8e46-42db-b1ae-c3ff54ab2678-visual.obj **DONE**

move around it and view it from different angles. **DONE**

note that it stays a matte grey rather than taking on the look of other things in the scene **SUCCESS**

smoke test:

**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**:  SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: N/A
**QA Pass**: SUCCESS

**Additional Test Results + Observations**:

Domain stats were not showing render rate or present new rate. ??? No idea why. I did restart and restart the scripts etc.

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |90 |90 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2570 |3826 |
**GPU Buffer Count**: |852 |1158 |
**CPU Memory Usage**: |45880112 |62407664 |
**GPU Memory Usage**: |29823728 |39580400 |
**CPU Texture Count**: |220 |258 |
**GPU Texture Count**: |172 |205 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |91636908 |136769040 |
**GPU Texture Memory Usage**: |1007207718 |1144403299 |
**GPU Virtual Memory Usage**: |1007207718|1144403299|
**Triangle Count**: |323400 |2201323 |
**Triangle Rate**: |29400000 |200120272 |
**API Drawcall Count**: |67 |347 |
**Drawcall Count**: |122 |1166 |
**Drawcall Rate**: |11090 |106000 |
**State Changes Texture Count**:|85 |313 |
**Pipeline Count**: |32 |40 |
**Item Opaques**: |59 |508 |
**Item Translucents**: |23 |70 |
**Item Lights**: |4 |54 |
**Timing Opaques**: |0.225 |1.387 |
**Timing Translucents**: |0.038 |0.11 |
**Timing Lighting**: |0.018 |0.021 |
**Render Frame**: |0.814 |2.783 |

**Pull request merged**
