### PR TITLE
Updating placeholder.js to use a url that points to example scripts

### PR DESCRIPTION
**Pull request by misslivirose**
Test Plan:
- Install build
- Confirm that in domain settings, you see the new URL to example acScripts under 'New Assignment'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3804/HighFidelity-Beta-PR11502-f150d77d318517975fa32996cb162eca8f9158e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3804/HighFidelity-Beta-PR11502-f150d77d318517975fa32996cb162eca8f9158e5.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by Nex-Pro** [comment]
@misslivirose is this the fix for the fogbugz I put up relating to this?

**Comment by YuppyPlays** [comment]
Testing complete:

Install build **Check**
Confirm that in domain settings, you see the new URL to example acScripts under 'New Assignment' **Check**
image

**Pass**

**Comment by misslivirose** [comment]
@Nex-Pro Didn't see a case but saw the issue mentioned in some feedback notes. Feel free to message me the bug #

**Pull request merged**
