### PR TITLE
make procedural data a first class entity property

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
CR: Refer to https://highfidelity.atlassian.net/wiki/display/HOME/How+to+Add+an+Entity+Property+in+20+Easy+Steps

**Comment by zzmp** [comment]
QA:
- Make sure all procedural entities still work as before (skyboxes, too!)
- When using a procedural entity where the `proceduralData` is specified as `userData`, changing `userData`'s `ProceduralEntity` field should update `proceduralData`, and then the `ProceduralEntity` field should disappear
- Make sure all procedural entities work by specifying the procedural component in `proceduralData`

**Comment by zzmp** [comment]
I forgot to make the UI, closing. Will reopen tomorrow.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 657da9c9e192ec14640b8201f4c046368c518541 available at: https://gist.github.com/19d1ed2a3c0c870bc0ebc5846874df69<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8450-657da9c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8450-657da9c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71a28708dfd63aea26cce49b144082e1b008b0b8 available at: https://gist.github.com/19d1ed2a3c0c870bc0ebc5846874df69<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8450-71a2870.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8450-71a2870.dmg

**Pull request closed without merging**
