### PR TITLE
Giant Disco Floor Files for Worklist task 21535. 

### PR DESCRIPTION
**Pull request by jmo7**
While developing I worked on using a smaller discofloor than the 32km by 32km size for this task. (At 2m x 2m that means 16k squared.) While I got it working with smaller quantities (100x 100 or even 1000 x 100)  it takes so long with anything larger that it freezes high fidelity (in Linux, on Windows it just crashes out
to the crash reporter). At this point there's not much more I can do, so I'm checking these files in for posterity's sake.

I'm very sorry I have not gotten it working all the way

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4368/HighFidelity-Beta-PR11657-59068ff1c3d23444d5ae013494f1b3e3698f6d05.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4368/HighFidelity-Beta-PR11657-59068ff1c3d23444d5ae013494f1b3e3698f6d05.exe

**Comment by themelissabrown** [comment]
@jmo7 this probably needs to be submitted against the hifi-content repo. Let me know if you have questions on how to do that.

**Comment by MiladNazeri** [comment]
I added a do not merge for now, I haven't had a chance to go through everything related this.

**Pull request closed without merging**
