### PR TITLE
update wireshark dissector with correct control packet types

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
I'll mark this for 0.77.0 so it doesn't get in the way of 0.76.0 cut, but it's a change to a wireshark dissector in the tools folder only. It won't affect the build and won't need to be QAed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15285/HighFidelity-Beta-PR14438-e52c7d9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15285/HighFidelity-Beta-PR14438-e52c7d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15285/HighFidelity-Beta-Interface-PR14438-e52c7d9.dmg

**Pull request merged**
