### PR TITLE
PAL: Scrollbar refinement & visual updates

### PR DESCRIPTION
**Pull request by zfox23**
This PR exists to improve the scrolling behavior of the PAL and bring the PAL more in line with Alan's latest concepts.

There are no functional differences in this PR; they are purely visual. The only behavioral difference is that the PAL will scroll to the selected avatar in the table when selecting an avatar's overlay.

*Test plan*
* Click around and make sure the PAL works the same as it always has.
* Use the PAL's scrollbar and ensure it doesn't feel dangerously close to the "BAN" button.
* Click an overlay of an avatar whose table row is out of view in the PAL. Ensure the PAL scrolls so that that avatar's row is in view.
* Note the nifty new VU meter colors.

### CODE REVIEW

**Comment by zfox23** [comment]
[scrolling refinement](https://trello.com/c/3OQYkgYq/72-scrolling-refinement)

**Comment by zfox23** [comment]
[Adding padding on the side so admins don't accidentally ban someone when trying to scroll](https://trello.com/c/16ogYY5W/78-adding-padding-on-the-side-so-admins-don-t-accidentally-ban-someone-when-trying-to-scroll)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e1a70891d802b40ea35779cc877ac64e4b785bf available at: https://gist.github.com/1a1787508c0e83beaef91a1cef0be3e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9373-8e1a708.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9373-8e1a708.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7e95a348690cb6084f200ca8bc712704808b6b0 available at: https://gist.github.com/1a1787508c0e83beaef91a1cef0be3e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9373-b7e95a3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9373-b7e95a3.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
See attached image

### PASS

palchanges

**Pull request merged**
