### PR TITLE
fix for default value insertion in domain server settings

### PR DESCRIPTION
**Pull request by birarda**
- fixed empty default values in domain server settings

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

On master, open your domain-server settings and go to the scripts section. Click the + button multiple times - note that the first show shows the default value of 1 for number of instances but each row after does not have the default 1. 

On this PR, each row you add should show the default number of instances.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5c46cecf6a28d24ebadbca16fcdd412e1488dfcf available at: https://gist.github.com/1625b1b758d91881ecbd4623762ba017<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9619-5c46cec.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9619-5c46cec.dmg

**Comment by nbq** [comment]
Testing this one

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Tested with the current master build 5909 and opened domain-server settings
* went to script settings and clicked the + multiple times and noticed the first addition showed 1 under `Instances` but the others added did not.
* tested with this PR and now every time I click the + button it adds a 1 under `Instances`

PASS

**Pull request merged**
