### PR TITLE
Second fix to null file path return (specific to music visualizer) 

### PR DESCRIPTION
**Pull request by elisa-lj11**
The first [PR](https://github.com/highfidelity/hifi/pull/11767) was altered, so this is a new PR with the same change.

Test plan:

1. Download music visualizer app: https://hifi-content.s3.amazonaws.com/elisalj/music_visualizer/musicVisualizer.js and test sound: https://hifi-content.s3.amazonaws.com/elisalj/music_visualizer/test_sounds/UpbeatFunk_mono.wav
2. Open the app and click "Choose Audio File"
3. Select "Upbeat Funk"
4. Click on any particle, you should hear the music and the particle should "dance"

Additional testing:
5. Open up the "Running Scripts" dialog (Ctrl + J)
6. Select "From Disk" and choose a script to load; script should load in (visible in the Running Scripts list)
7. Select "Edit" from the menu bar and select "Open and Run Script File" from the drop-down and choose a script; this should also load in

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4816/HighFidelity-Beta-PR11787-119c66289931b385982ee4bb56f5126ef4c0e0cf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4816/HighFidelity-Beta-PR11787-119c66289931b385982ee4bb56f5126ef4c0e0cf.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

[Had a bit of trouble posting this at first, I think Github got a little slowed down]

Download music visualizer app: https://hifi-content.s3.amazonaws.com/elisalj/music_visualizer/musicVisualizer.js and test sound: https://hifi-content.s3.amazonaws.com/elisalj/music_visualizer/test_sounds/UpbeatFunk_mono.wav **Check & Check&&
Open the app and click "Choose Audio File" **Check**
Select "Upbeat Funk" **Check**
Click on any particle, you should hear the music and the particle should "dance" **Check**

Additional testing:
5. Open up the "Running Scripts" dialog (Ctrl + J) **Check**
6. Select "From Disk" and choose a script to load; script should load in (visible in the Running Scripts list) **Check**
7. Select "Edit" from the menu bar and select "Open and Run Script File" from the drop-down and choose a script; this should also load in **Check**

All **Pass**

**Pull request merged**
