### PR TITLE
Case 20940: Goto the spot on first launch (78.1)

### PR DESCRIPTION
**Pull request by danteruiz**
Goto the spot on first launch

Ticket: https://highfidelity.manuscript.com/f/cases/20940/Redirect-FTUE-URL-To-Welcome

Test case:
https://highfidelity.testrail.net/index.php?/cases/view/40859

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan 
1on first launch you should be directed to the spot even if the is a protocol change
2. Pressing the home button in the goto should bring you back to the serverless domain if you didn't override your home destination

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16960/HighFidelity-Beta-PR14833-4637698.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16960/HighFidelity-Beta-PR14833-4637698.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16960/HighFidelity-Beta-Interface-PR14833-4637698.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16960/HighFidelity-Beta-PR14833-4637698.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16960/HighFidelity-Beta-Interface-PR14833-4637698.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Pull request merged**
