### PR TITLE
DEV-2619: WebRTC spamming logs

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.atlassian.net/browse/DEV-2619
https://highfidelity.atlassian.net/browse/DEV-2605

It has diagnostic value to log a warning when AEC is disabled due to unsupported audio device configuration (in this case, 3-channel microphone and 192khz sample rate).

This PR logs only a single warning (per audio device configuration) to prevent log spam.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22260/HighFidelity-Beta-PR16434-30564a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22260/HighFidelity-Quest-Beta-PR16434-30564a6.apk)

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22262/HighFidelity-Beta-PR16434-30564a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22262/HighFidelity-Quest-Beta-PR16434-30564a6.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22262/HighFidelity-Beta-PR16434-30564a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22262/HighFidelity-Beta-Interface-PR16434-30564a6.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22265/HighFidelity-Beta-PR16434-30564a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22265/HighFidelity-Quest-Beta-PR16434-30564a6.apk)

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22268/HighFidelity-Beta-PR16434-30564a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22268/HighFidelity-Quest-Beta-PR16434-30564a6.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22268/HighFidelity-Beta-PR16434-30564a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22268/HighFidelity-Beta-Interface-PR16434-30564a6.exe

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22269/HighFidelity-Beta-PR16434-30564a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22269/HighFidelity-Beta-Interface-PR16434-30564a6.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22269/HighFidelity-Beta-PR16434-30564a6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22269/HighFidelity-Quest-Beta-PR16434-30564a6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22270/HighFidelity-Beta-PR16434-3cdf25f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22270/HighFidelity-Beta-Interface-PR16434-3cdf25f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22270/HighFidelity-Beta-PR16434-3cdf25f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22270/HighFidelity-Beta-Interface-PR16434-3cdf25f.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22270/HighFidelity-Beta-PR16434-3cdf25f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22270/HighFidelity-Quest-Beta-PR16434-3cdf25f.apk)

**Pull request merged**
