### PR TITLE
fixing AddressManager keyboard when switching domains

### PR DESCRIPTION
**Pull request by druiz17**
fixing AddressManager keyboard when switching domains

- ticket - https://highfidelity.manuscript.com/f/cases/12864/HMD-In-some-cases-virtual-keyboard-fails-to-appear-if-interface-does-not-have-focus

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan 

1) Enter VR
2) Verify that virtual keyboard can appear on the goto page
3) Click on another window to remove focus from interface
4) Virtual keyboard continues to appear when needed
5) Change domains
6) Virtual keyboard should continue to appear on the goto page.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8123/app_12676_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8123/HighFidelity-Beta-PR12676-652faaa116bcede8000b613fed957aa10e3a3206.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8123/HighFidelity-Beta-PR12676-652faaa116bcede8000b613fed957aa10e3a3206.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8285/app_12676_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8285/HighFidelity-Beta-PR12676-652faaa116bcede8000b613fed957aa10e3a3206.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8285/HighFidelity-Beta-PR12676-652faaa116bcede8000b613fed957aa10e3a3206.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Keyboard stays consistently.

**Comment by L370** [comment]
@conklin94122 Verified does not occur in 12676.  Ready to close

**Pull request merged**
