### PR TITLE
Use timer instead of dedicated thread to tick AC scripted avatar audio

### PR DESCRIPTION
**Pull request by Atlante45**
We currently use a dedicated thread to tick the agent's avatar audio.
That thread is never shut down properly and will sometimes prevent the AC from shutting down altogether.

Since that thread throws an event into the Qt event system it does not make it any more accurate than a Qt timer at the cost of having a dedicated thread running just for that and code that can possibly be broken.

I did some tests using a Qt Precise timer instead and confirmed the timings are very similar.
This also fixes a stall on shutdown.

### CODE REVIEW

**Comment by Atlante45** [comment]
Here is the code I've used to measure the accuracy of the timing:
```cpp
diff --git a/assignment-client/src/Agent.cpp b/assignment-client/src/Agent.cpp
index 7dd7200785..23f638dacb 100644
--- a/assignment-client/src/Agent.cpp
+++ b/assignment-client/src/Agent.cpp
@@ -668,7 +668,22 @@ void Agent::computeLoudness(const QByteArray* decodedBuffer, QSharedPointer<Scri
     scriptableAvatar->setAudioLoudness(lastInputLoudness);
 }

+#include <SimpleMovingAverage.h>
 void Agent::processAgentAvatarAudio() {
+    static SimpleMovingAverage average;
+    static quint64 timestamp = 0;
+    static quint64 count = 0;
+    auto now = usecTimestampNow();
+    if (timestamp != 0) {
+        average.updateAverage(glm::abs(10000 - (qint64)(now - timestamp)));
+
+        if (++count > 100) {
+            qDebug() << "Avarage deviation from target:" << average.getAverage();
+            count = 0;
+        }
+    }
+    timestamp = now;
+
     auto recordingInterface = DependencyManager::get<RecordingScriptingInterface>();
     bool isPlayingRecording = recordingInterface->isPlaying();
```

And some samples of the results I got:
```
Old code:
[07/17 17:34:48] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 1101.65
[07/17 17:34:49] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 1016.8
[07/17 17:34:50] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 930.611
[07/17 17:34:51] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 943.842
[07/17 17:34:52] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 970.152
[07/17 17:34:53] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 879.947
[07/17 17:34:54] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 857.903
[07/17 17:34:55] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 925.7
[07/17 17:34:56] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 942.019
[07/17 17:34:57] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 912.156
[07/17 17:34:58] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 868.879
[07/17 17:34:59] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 955.073
[07/17 17:35:01] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 847.458
[07/17 17:35:02] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 936.639
[07/17 17:35:03] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 899.963
[07/17 17:35:04] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 844.501
[07/17 17:35:05] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 918.402
[07/17 17:35:06] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 903.754
[07/17 17:35:07] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 997.054
[07/17 17:35:08] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 961.319
[07/17 17:35:09] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 878.423
[07/17 17:35:10] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 982.279
[07/17 17:35:11] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 1006.95
[07/17 17:35:12] [DEBUG] [default] [77696] [agent] Avarage deviation from target: 897.523
```

```
New code:
[07/17 17:32:05] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 758.952
[07/17 17:32:06] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 822.442
[07/17 17:32:07] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 799.03
[07/17 17:32:08] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 862.291
[07/17 17:32:09] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 804.514
[07/17 17:32:10] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 798.632
[07/17 17:32:11] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 798.246
[07/17 17:32:12] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 778.843
[07/17 17:32:13] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 846.515
[07/17 17:32:14] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 909.589
[07/17 17:32:15] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 969.186
[07/17 17:32:16] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 937.315
[07/17 17:32:17] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 926.831
[07/17 17:32:18] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 889.574
[07/17 17:32:19] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 858.284
[07/17 17:32:20] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 877.446
[07/17 17:32:21] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 860.602
[07/17 17:32:22] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 797.099
[07/17 17:32:23] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 821.177
[07/17 17:32:24] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 1017.61
[07/17 17:32:25] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 979.239
[07/17 17:32:26] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 862.758
[07/17 17:32:27] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 925.058
[07/17 17:32:28] [DEBUG] [default] [76791] [agent] Avarage deviation from target: 969.492
```

As you can see, the timer seems slightly more precise than the dedicated thread.

**Comment by Atlante45** [comment]
## Repro:
1) Launch the sandbox
2) Wait for it to load the content set
3) Shut down the sandbox
4) Manually run a domain server: `./domain-server`
5) Manually run an agent: `./assignment-client -t2`
6) Close the assignment client using `Ctrl + C`

On master, this should result in the process spinning indefinitely and never finishing. Forcing you to kill it with you task manager.
On this PR, the AC should quit right away.

## Test Plan:

1) Launch your Sandbox
2) Launch Interface
3) Download the recording app from the market place
4) Follow the setup instruction of the recording app
5) Make several recording and make sure the recorded audio comes through as expected.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1737/HighFidelity-Beta-PR10986-91d65469a0a92015e07e9de222cfe220060dd145.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1737/HighFidelity-Beta-PR10986-91d65469a0a92015e07e9de222cfe220060dd145.exe

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Launch your Sandbox | Pass
Launch Interface | Pass
Download the recording app from the market place | Pass
Follow the setup instruction of the recording app | Pass
Make several recording and make sure the recorded audio comes through as expected. | Pass

Everything looking good from here, tried recording from multiple audio devices too per recording.

##### Intel i5-7200U @ 2.7Ghz, 8GB DDR4 RAM, GTX 940MX (Laptop)

**Pull request merged**
