### PR TITLE
snap turn default

### PR DESCRIPTION
**Pull request by howard-stearns**
Proper default for snapTurn preference (and new name so as to update old users).

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/94455201563178

**Comment by howard-stearns** [comment]
To test: Settings -> Avatar -> Snap Turn should be true with this PR, regardless of whether you blow away your Interace.ini or use an old one. After running this PR, whatever you set should stick.

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8fe55ddc533f14446e6e974b0f5d87defe5c0b1 available at: https://gist.github.com/7c2370ed7d28048b6151<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7198.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7198.dmg

**Comment by ZappoMan** [comment]
Tested - performs as expected. 

Now let me turn off "old man mode" so I can live like the child's mind I am.

**Pull request merged**
