### PR TITLE
8269  controllerDispatcher is creating log spam with web entities

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR turn off debug mode in controllerDispacher.js

https://highfidelity.fogbugz.com/f/cases/8269

...

## TEST PLAN
- Activate the advance and developer menus.
- On developer menu activate Script Log(HMD friendly).
- Create a new web entity or get near one.
- Move your hands, meanwhile you touch the web entity.
- No debug output from controllerDispacher appears on the Script Log.

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/8269/controllerDispatcher-is-creating-log-spam-with-web-entities

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4264/HighFidelity-Beta-PR11628-6e8756e8afd366bd771ebd0a56106b4257595821.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4264/HighFidelity-Beta-PR11628-6e8756e8afd366bd771ebd0a56106b4257595821.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Activate the advance and developer menus. | Pass
On developer menu activate Script Log(HMD friendly). | Pass
Create a new web entity or get near one. | Pass
Move your hands, meanwhile you touch the web entity. | Pass
No debug output from controllerDispacher appears on the Script Log.  | Pass

All good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
