### PR TITLE
Fix for 'Login page for steam is blank'

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**
Open steam login dialog and ensure it is shown/works correctly

https://highfidelity.fogbugz.com/f/cases/14818/Login-page-for-steam-is-blank

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9560/app_13116_PR_b4cfea2fbc4793bc9f3fddcf8949ab67cf826c19.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9560/HighFidelity-Beta-PR13116-b4cfea2fbc4793bc9f3fddcf8949ab67cf826c19.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9560/HighFidelity-Beta-Interface-PR13116-b4cfea2fbc4793bc9f3fddcf8949ab67cf826c19.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9560/HighFidelity-Beta-PR13116-b4cfea2fbc4793bc9f3fddcf8949ab67cf826c19.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9560/HighFidelity-Beta-Interface-PR13116-b4cfea2fbc4793bc9f3fddcf8949ab67cf826c19.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Stopped Testing

**Pull request merged**
