### PR TITLE
Beta Release 62 - includes up to Developer Release 7646

### PR DESCRIPTION
**Pull request by conklin94122**
Includes up to developer release 7646 (PR 12106).

- To make the tablet easier to use, we removed the stylus (available in settings) and when your hand is pointed at the tablet you get a laser in your dominant hand.
- Tablet apps now scroll as pages. Swipe left and right to see your apps.
- Clothing purchased from the Marketplace will scale with you when your avatar scales. Avatar entities scale with the avatar. 
- Reduce communication/server load in handshakes.
- Google Poly API is now usable in High Fidelity.
- Fixed issue where unsupported audio formats make a loud static sound.
- Fixed issue where pressing “x” to make a connection does not work when capslock is on.
- Fixed a crash when using the AnimSkeleton::getNumJoints() API.
- Fixed issue where animation property changes are not applying to animated fbxs.
- Fixed issue where user can get stuck in handshake mode.
- Fixed issue with avatar entities (such as those generated by the clap app) that caused all
- other avatar entities, such as clothing, not to appear to other users.
- Tablet will be resized correctly to small avatars.
- Solved issue where using High Fidelity enabled the webcam.
- Scrolling will now work on the edges of the tablet home screen.
- Fixed bug with certain tablet screens not opening in VR mode.
- Fixed bug where thrown objects rotated incorrectly using the oculus touch controllers.
- When using the Vive pucks you should see fewer glitches caused by jiggling pucks.
- We now send Controller data in the status event of the Midi class to connect Launchpad MIDI control events.
- Fixed getting teleported in front of a user when clicking their username in the people app (nearby tab).
- Fixed the issue with the tablet close button appearing black.
- Fixed issue with teleport entities changing rendered color in default sandbox content set.
- Crash on start up with i5 AMD card is fixed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6090/app_12110_PR.apk

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6098/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6098/HighFidelity-Beta-PR12110-fab28e7d4405206197e13ae944005aa0997ee731.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6098/HighFidelity-Beta-PR12110-fab28e7d4405206197e13ae944005aa0997ee731.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6140/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6141/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6141/HighFidelity-Beta-PR12110-fd6c5e72f0dc475ea70361a34a77f924fc2a7ae4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6141/HighFidelity-Beta-PR12110-fd6c5e72f0dc475ea70361a34a77f924fc2a7ae4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6146/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6146/HighFidelity-Beta-PR12110-b1790cccbe7c242fe278b7c7ccfdb9260488c31b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6146/HighFidelity-Beta-PR12110-b1790cccbe7c242fe278b7c7ccfdb9260488c31b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6196/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6197/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6197/HighFidelity-Beta-PR12110-36a76dad2beb3fa19da050c4046201eb29307ff1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6197/HighFidelity-Beta-PR12110-36a76dad2beb3fa19da050c4046201eb29307ff1.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6203/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6203/HighFidelity-Beta-PR12110-7f1a01fb3a046af4a0b6c19791e35034969f38c6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6203/HighFidelity-Beta-PR12110-7f1a01fb3a046af4a0b6c19791e35034969f38c6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6214/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6214/HighFidelity-Beta-PR12110-da2c56dbc9721f3666fc0f45e341d07c8acef66f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6214/HighFidelity-Beta-PR12110-da2c56dbc9721f3666fc0f45e341d07c8acef66f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6224/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6224/HighFidelity-Beta-PR12110-96babdf2e299fffbfaf6e4adde9d52daed055070.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6224/HighFidelity-Beta-PR12110-96babdf2e299fffbfaf6e4adde9d52daed055070.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6225/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6225/HighFidelity-Beta-PR12110-3c36b8ffee48604e07f83668ce2ddf0af4f7e19b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6225/HighFidelity-Beta-PR12110-3c36b8ffee48604e07f83668ce2ddf0af4f7e19b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6270/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6270/HighFidelity-Beta-PR12110-810c5b657757fa2be8f995ac6d5d35583453c11a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6270/HighFidelity-Beta-PR12110-810c5b657757fa2be8f995ac6d5d35583453c11a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6290/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6290/HighFidelity-Beta-PR12110-c3648fb04c5102e1769b1e8b374c6ab0c8bea860.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6290/HighFidelity-Beta-PR12110-c3648fb04c5102e1769b1e8b374c6ab0c8bea860.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6311/app_12110_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6311/HighFidelity-Beta-PR12110-b26b99fec5d6f52e4d8a996444af2ecd21b82ec3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6311/HighFidelity-Beta-PR12110-b26b99fec5d6f52e4d8a996444af2ecd21b82ec3.dmg

**Pull request merged**
