### PR TITLE
DOC-55: Model API JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- Model

Globals:
- MeshFace

Also:
- Update MeshProxy JSDoc
- Update Entities.getMeshes() and getMeshesCallback() JSDoc

Case: https://highfidelity.atlassian.net/browse/DOC-55

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22818/HighFidelity-Beta-PR16579-8255a50.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22818/HighFidelity-Quest-Beta-PR16579-8255a50.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22818/HighFidelity-Beta-PR16579-8255a50.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22818/HighFidelity-Beta-Interface-PR16579-8255a50.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22818/HighFidelity-Beta-PR16579-8255a50.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22818/HighFidelity-Beta-Interface-PR16579-8255a50.exe

**Comment by hd23408** [comment]
Closing in favor of https://github.com/highfidelity/hifi/pull/16583

**Pull request closed without merging**
