### PR TITLE
[Experimental Client-RC67] Balanced Hips using Center of Gravity

### PR DESCRIPTION
**Pull request by hyperlogic**
* added the swing twist code to update the follow rotation in MyAvatar.cpp
* added step.js and cg_lean.js to the developer folder
* added menu item for toggling the hips following between head and hips
* added new function to return true if the root of MyAvatar is translating
to be under the head.  Used to smooth the path of the hips
* added computeCounterBalance to MyAvatar.h and cpp
* added the menu item under developer/avatar to enable debug draw of the base of support in menu.h menu.cpp MyAvatar.h MyAvatar.cpp
* added head yaw into the calculation of the hip rotation for the center
of gravity.  This is already was happening in the deriveBodyFromHMD code
that is default
* Changed Constants in Avatar constants for the base of support
* fixed the over rotation of the shoulders
* fixed scaling problem in cg computation
* added room for going up on the toes without stretching
* added test function to cancel out roll and pitch
* code review changes to declare functions static
* cleaned up cg code ie computeNewHipsRotation
* changed lerp to saferLerp in cg code
* removed the follow hips code from pre physics update
* removed debug code from cg code in MyAvatar.cpp
* added more straight forward computation of the hips rotation inMyAvatar.cpp contributed by AJT
* removed white space in MyAvatar.cpp

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9655/app_13142_PR_2f9e45af8720c97c23523596dc4a9e92de832d9e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9655/HighFidelity-Beta-PR13142-2f9e45af8720c97c23523596dc4a9e92de832d9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9655/HighFidelity-Beta-Interface-PR13142-2f9e45af8720c97c23523596dc4a9e92de832d9e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9655/HighFidelity-Beta-PR13142-2f9e45af8720c97c23523596dc4a9e92de832d9e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9655/HighFidelity-Beta-Interface-PR13142-2f9e45af8720c97c23523596dc4a9e92de832d9e.exe

**Comment by hyperlogic** [comment]
We never ended up using this PR for the Fireside Chat event.

**Pull request closed without merging**
