### PR TITLE
Android enhancement

### PR DESCRIPTION
**Pull request by Sudakatux**
Android performance enhancements

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by Sudakatux** [comment]
ok to test

**Comment by cozza13** [comment]
ok to test

**Comment by cozza13** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10a821f5ee03428f8ccbf842b68545463571839a available at: https://gist.github.com/7e73c9f0cef38226d0fb19cf5ac79b3b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10353-10a821f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10353-10a821f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10a821f5ee03428f8ccbf842b68545463571839a available at: https://gist.github.com/7e73c9f0cef38226d0fb19cf5ac79b3b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10353-10a821f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10353-10a821f.dmg

**Pull request merged**
