### PR TITLE
fix near-grab attaching entity to hips

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that would sometimes cause a near-grabbed entity to be a child of the avatar's hips

https://highfidelity.fogbugz.com/f/cases/15067/near-grab-sometimes-attaches-entity-to-hips-rather-than-hand

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- launch interface
- use CREATE to rez a cube.  Leave all the properties as their defaults.
- take off the HMD
- press ctrl-4 to put interface into HMD mode
- exit interface
- launch interface so that it starts up directly into HMD mode
- put on the HMD
- near-grab the cube
- note that the cube stays with the avatar's hand rather than hips
- release the cube

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9729/HighFidelity-Beta-PR13163-dea87b32f9bd7f2a507a5511b652eb5e7d590f9d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9729/HighFidelity-Beta-PR13163-dea87b32f9bd7f2a507a5511b652eb5e7d590f9d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9729/HighFidelity-Beta-Interface-PR13163-dea87b32f9bd7f2a507a5511b652eb5e7d590f9d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9734/HighFidelity-Beta-PR13163-dea87b32f9bd7f2a507a5511b652eb5e7d590f9d.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9738/HighFidelity-Beta-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Interface crashes when restarted. When interface is closed after initial launch from install, launching it again will crash. 

Video and log attached:
[Files.zip](https://github.com/highfidelity/hifi/files/2001613/Files.zip)

**Comment by sethalves** [comment]
build this please

**Comment by sethalves** [comment]
I believe that crash was unrelated to this PR.  I also believe that rebuilding will re-merge with master and avoid this.  I'll set this QA-ready again, please retry once the build has finished.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9775/HighFidelity-Beta-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9775/HighFidelity-Beta-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9775/HighFidelity-Beta-Interface-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9775/HighFidelity-Beta-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9775/HighFidelity-Beta-Interface-PR13163-898dec29cbb48dd59a0303aa52d04ba37b2e5473.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Pass @conklin94122 
Cubes consistently stay with the hands.

**Pull request merged**
