### PR TITLE
fix domain-server command-line arguments

### PR DESCRIPTION
**Pull request by sethalves**
- repair doman-server's ability to parse command-line arguments

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make sure servers from this PR work as expected
- run domain-server with a temporary domain

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd2ee56a27058706ea1455c70c49d411c31cdb1b available at: https://gist.github.com/09be45c261bab3dd32125629e5ffa5dc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8641-bd2ee56.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8641-bd2ee56.dmg

**Comment by OmegaHeron** [comment]
Could we, eventually, please have a --help option for DS as AC does?  :)

**Comment by sethalves** [comment]
--help doesn't work, but -? does:

```./domain-server -?
hifi.embeddedwebserver: Attempting to bind TCP socket on port  "40100"
"Unknown option '?'." 

Usage: ./domain-server [options]
High Fidelity Domain Server

Options:
  -h, --help                     Displays this help.
  -i <IP:PORT or HOSTNAME:PORT>  ice-server address
  -d                             domain-server uuid
  --get-temp-name                Request a temporary domain-name
  --master-config                Deprecated config-file option
```

**Comment by OmegaHeron** [comment]
Ty sir ;)  I never thought to use that.

**Pull request merged**
