### PR TITLE
Correct desktop icon name

### PR DESCRIPTION
**Pull request by anshuman64**
QA Test:
During installation, make sure to create desktop icons. Desktop icon name should be "High Fidelity Interface - PR..." instead of "High Fidelity High Fidelity Interface - PR.."

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2455/HighFidelity-Beta-PR11177-3bc185e67cefb7fb007442ae306f72c45cf39018.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2455/HighFidelity-Beta-PR11177-3bc185e67cefb7fb007442ae306f72c45cf39018.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

I can confirm this is a **Pass**, please see image below.

image

**Pull request merged**
