### PR TITLE
Add tools for debugging entity workload proxies

### PR DESCRIPTION
**Pull request by AndrewMeadows**
This PR introduces some debug tools for examining entity workload proxies.  The hope is this will allow us to get more clues about the "sometimes fall through ground" problem (DEV-2189).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22474/HighFidelity-Beta-PR16483-5203061.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22474/HighFidelity-Quest-Beta-PR16483-5203061.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22474/HighFidelity-Beta-PR16483-5203061.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22474/HighFidelity-Beta-Interface-PR16483-5203061.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22486/HighFidelity-Beta-PR16483-cf08a41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22486/HighFidelity-Beta-Interface-PR16483-cf08a41.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22486/HighFidelity-Beta-PR16483-cf08a41.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22486/HighFidelity-Quest-Beta-PR16483-cf08a41.apk)

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22500/HighFidelity-Beta-PR16483-cf08a41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22500/HighFidelity-Beta-Interface-PR16483-cf08a41.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22500/HighFidelity-Beta-PR16483-cf08a41.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22500/HighFidelity-Quest-Beta-PR16483-cf08a41.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22503/HighFidelity-Beta-PR16483-1c399f5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22503/HighFidelity-Beta-Interface-PR16483-1c399f5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22503/HighFidelity-Beta-PR16483-1c399f5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22503/HighFidelity-Beta-Interface-PR16483-1c399f5.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22503/HighFidelity-Beta-PR16483-1c399f5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22503/HighFidelity-Quest-Beta-PR16483-1c399f5.apk)

**Pull request merged**
