### PR TITLE
Remove redundant code in getOrCreateChildElementAt()

### PR DESCRIPTION
**Pull request by nnesse**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by nnesse** [comment]
ok to test

**Comment by ZappoMan** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85f06639a5a67117be3c7ff644f4ffc771d97123 available at: https://gist.github.com/4b49660107f6f6d79813<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5464.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5464.dmg

**Pull request merged**
