### PR TITLE
Revamp the render engine ui

### PR DESCRIPTION
**Pull request by zzmp**
- Replaces `renderEngineDebug.js` with qml ui.
- Fixes loading of JS-defined render configurations with `Render.load(config)`.

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent
- Streamline debugging of render engine by exposing its configuration as an interface.
- Make render engine configuration scriptable to allow for easier definitions at runtime.

#### Testing
##### UI
Run the script, `examples/utilities/tools/render/debug.js` and make sure the toggles all work as expected. It's not so important that their use is apparent, because it is mainly for use in development, not in normal use.

##### Loading
1. Define a config object: `config = JSON.parse(Render.toJSON())` should do it, and you can change it as you see fit.
2. Change something in the live configuration (e.g., turning shadows on or off, `Render.RenderShadowTask.enabled = true`).
3. Reload the config object to make sure it reverts (`Render.load(config)`).

Check that it reverts visually, as well as through the scripted object.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b3a6a9a2af636ed6bceee1946a4503f78a1b9ecc available at: https://gist.github.com/e160096a7d256c6a78ec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 137aceb8a58e307a0d49bcda4b61b73e5ba03c03 available at: https://gist.github.com/e160096a7d256c6a78ec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.dmg

**Comment by OmegaHeron** [comment]
Testing windows 7.

UI is a bit hard to work with - fully transparent background seen here.

hifi-snap-by-omegaheron-on-2016-02-09_14-07-12

All the toggles/sliders seem to work
Loading to config var works and reloading it into active does as well.  For someone having no full idea how to wield this it passes.  Additional input from a consumer of its function might disagree. :)

**Comment by zzmp** [comment]
@jherico gave me lots of feedback on qml so I am going to go over this again.

**Comment by zzmp** [comment]
@jherico do you know how to make this overlay more opaque?

**Comment by hifi-gustavo** [comment]
Build console output for commit: fae7fda2c20b80eebd56712b19d656a896743755 available at: https://gist.github.com/e160096a7d256c6a78ec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6b13a0a975f51059473fe068eb6bb693272ebd5 available at: https://gist.github.com/e160096a7d256c6a78ec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3bace3cdbb07636bc1d76764337cfbf57bef6a7e available at: https://gist.github.com/e160096a7d256c6a78ec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7043.dmg

**Pull request merged**
