### PR TITLE
19942 Mac installation procedure

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
The nitpicker readme has been updated to include both creating a Mac installer, and the installation itself.
# Testing
Follow the Mac installation procedure and verify that `nitpick` runs.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15289/HighFidelity-Beta-PR14440-e24eee8.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15289/HighFidelity-Beta-PR14440-e24eee8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15289/HighFidelity-Beta-Interface-PR14440-e24eee8.exe

**Comment by AndrewMeadows** [comment]
The ubuntu build failed for this error:
```
06:22:25 /home/jenkins/workspace/pr-build/label/ubuntu/tools/nitpick/src/TestRunner.cpp:343:26: error: ‘dataDirectory’ was not declared in this scope
06:22:25          _appDataFolder = dataDirectory + "/High Fidelity";
```

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Nitpick has been successfully installed on Mac.  Waiting for some improvements to be added to the readme before giving it the green

**Comment by qaAdamSmith82** [comment]
Pass @conklin94122 Nitpick installs on Mac!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15398/HighFidelity-Beta-PR14440-ebc7875.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15401/HighFidelity-Beta-PR14440-e587820.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15401/HighFidelity-Beta-Interface-PR14440-e587820.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15442/HighFidelity-Beta-PR14440-e587820.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15442/HighFidelity-Beta-PR14440-e587820.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15442/HighFidelity-Beta-Interface-PR14440-e587820.exe

**Pull request merged**
