### PR TITLE
Zones will inherit and control their components.

### PR DESCRIPTION
**Pull request by NissimHadar**
The zone components (keylight, ambient light, haze, etc) will be inheritable and will respect the zone orientation.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4225/HighFidelity-Beta-PR11616-fd2b0da76d6b40ec4bdde79585504d45099e2a7e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4252/HighFidelity-Beta-PR11616-99e13a89654e3bbb5999a6518a68d64b5bc50bd0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4252/HighFidelity-Beta-PR11616-99e13a89654e3bbb5999a6518a68d64b5bc50bd0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4260/HighFidelity-Beta-PR11616-5448178e166e4bf6da9f6f329ffd5361fb8c8622.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4260/HighFidelity-Beta-PR11616-5448178e166e4bf6da9f6f329ffd5361fb8c8622.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4299/HighFidelity-Beta-PR11616-aeda8c6b169a0482f86c3666bf947df35fc411e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4299/HighFidelity-Beta-PR11616-aeda8c6b169a0482f86c3666bf947df35fc411e3.exe

**Comment by ZappoMan** [comment]
this PR needs a test plan

**Comment by samcake** [comment]
closing for now

**Pull request closed without merging**
