### PR TITLE
Enable sideloading .app.json Apps from local disk

### PR DESCRIPTION
**Pull request by zfox23**
This PR enables the sideloading of .app.json Apps from a user's local disk via a special hidden screen. That same hidden screen also displays all installed marketplace apps so that you can open and uninstall sideloaded apps.

This is mainly useful when testing, because it allows someone to verify the state of a .app.json App that they are developing.

To find the hidden Sideload Apps, open My Purchases, click in the "filter items" filter bar (to focus the screen), then press `CTRL + F` on your keyboard. Fancy!

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9291/app_13039_PR_dbd7d7e2b4872ed16e4c0862f662daed369e2a77.apk

**Comment by zfox23** [comment]
This is a dev/tester feature and doesn't affect normal operation, so a full QA pass isn't necessary. Merging...

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9291/HighFidelity-Beta-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9291/HighFidelity-Beta-Interface-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.dmg

**Comment by zfox23** [comment]
for cryin' out loud

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9298/app_13039_PR_dbd7d7e2b4872ed16e4c0862f662daed369e2a77.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9298/HighFidelity-Beta-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9298/HighFidelity-Beta-Interface-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9298/HighFidelity-Beta-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9298/HighFidelity-Beta-Interface-PR13039-dbd7d7e2b4872ed16e4c0862f662daed369e2a77.exe

**Pull request merged**
