### PR TITLE
Debug path printouts (EXPERIMENTAL)

### PR DESCRIPTION
**Pull request by BingShearer**
This is just a PR to have installer for AC built with additional printouts.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by AndrewMeadows** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: a224f50f4b4d6749ece22129c0747159ecd1b073 available at: https://gist.github.com/4bc94c902eea998b2303986ce59130a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8230-a224f50.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8230-a224f50.dmg

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a224f50f4b4d6749ece22129c0747159ecd1b073 available at: https://gist.github.com/4bc94c902eea998b2303986ce59130a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8230-a224f50.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8230-a224f50.dmg

**Comment by AndrewMeadows** [comment]
This test is done.

**Pull request closed without merging**
