### PR TITLE
Fix controllerDispatcherUtils file path

### PR DESCRIPTION
**Pull request by MidnightRift**
Changed the include to what should be the correct file path. it does not exist in the controllers folder.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4693/HighFidelity-Beta-PR11755-e2ca3c6de04e6662f83ff80f550871220bd8afb8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4693/HighFidelity-Beta-PR11755-e2ca3c6de04e6662f83ff80f550871220bd8afb8.exe

**Comment by ZappoMan** [comment]
Is there a test plan for this?

**Comment by MidnightRift** [comment]
You want a test plan for a one word, one line change? How about follow the directory tree and you will see the filed doesn't exist as referenced.

**Comment by druiz17** [comment]
Test plan 
- In your logs you should not get this warning - Error loading script from URL  QUrl("file:///~//system/controllers/controllerDispatcherUtils.js") ( "NotFound" )
- this PR should have no functional change to clone of entities.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In your logs you should not get this warning - Error loading script from URL QUrl("file:///~//system/controllers/controllerDispatcherUtils.js") ( "NotFound" ) **Check, no errors of the like**
this PR should have no functional change to the cloning of entities. **Check**

**Pass**

**Pull request merged**
