### PR TITLE
Enable LOD manager on android

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan (Android only):
- Go to a few domains.  Confirm that you see the LOD kicking in (in domains with lots of things, small things might vanish until you get closer to them).  Confirm that the LOD is well behaved (no crazy oscillations of things flashing in and out).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11474/HighFidelity-Beta-PR13663-e9ab2b8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11474/HighFidelity-Beta-PR13663-e9ab2b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11474/HighFidelity-Beta-Interface-PR13663-e9ab2b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11474/HighFidelity-Beta-PR13663-e9ab2b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11474/HighFidelity-Beta-Interface-PR13663-e9ab2b8.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11626/HighFidelity-Beta-PR13663-e9ab2b8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11626/HighFidelity-Beta-PR13663-e9ab2b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11626/HighFidelity-Beta-Interface-PR13663-e9ab2b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11626/HighFidelity-Beta-PR13663-e9ab2b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11626/HighFidelity-Beta-Interface-PR13663-e9ab2b8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12773/HighFidelity-Beta-PR13663-5727542.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12773/HighFidelity-Beta-Interface-PR13663-5727542.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12773/HighFidelity-Beta-PR13663-5727542.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12773/HighFidelity-Beta-Interface-PR13663-5727542.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
