### PR TITLE
(BUGZ-1040) Fix LOD randomly being too low in simplified UI

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.atlassian.net/browse/BUGZ-1040

This PR fixes simplified UI not initializing the LOD correctly, and does some cleanup in related code.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20556/HighFidelity-Beta-PR15982-3a4ce44.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20556/HighFidelity-Beta-Interface-PR15982-3a4ce44.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20556/HighFidelity-Beta-PR15982-3a4ce44.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20556/HighFidelity-Quest-Beta-PR15982-3a4ce44.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20585/HighFidelity-Beta-PR15982-3a4ce44.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20585/HighFidelity-Beta-Interface-PR15982-3a4ce44.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20585/HighFidelity-Beta-PR15982-3a4ce44.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20585/HighFidelity-Quest-Beta-PR15982-3a4ce44.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20591/HighFidelity-Beta-PR15982-601b579.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20591/HighFidelity-Beta-Interface-PR15982-601b579.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20591/HighFidelity-Beta-PR15982-601b579.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20591/HighFidelity-Beta-Interface-PR15982-601b579.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20591/HighFidelity-Beta-PR15982-601b579.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20591/HighFidelity-Quest-Beta-PR15982-601b579.apk)

**Pull request merged**
