### PR TITLE
Redo entity scale handles to fix scaling into avatars causing undesirable physics/dimensions

### PR DESCRIPTION
**Pull request by dback2**
Fixes bug: https://highfidelity.manuscript.com/f/cases/12943

Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/11450

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7757/app_12570_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7757/HighFidelity-Beta-PR12570-b74be92fd8965ae297ad442ede65c4cd933b5fb8.dmg

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7767/app_12570_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7771/app_12570_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7777/app_12570_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7784/app_12570_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7784/HighFidelity-Beta-PR12570-47e8e26255d267f450d7143f0c35ea2d8eece588.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7784/HighFidelity-Beta-PR12570-47e8e26255d267f450d7143f0c35ea2d8eece588.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
FAIL @conklin94122 

It is no longer possible to use any of the handles for scaling (they are non-responsive to user input). Video and log attached.

[PR12570 Files.zip](https://github.com/highfidelity/hifi/files/1790085/PR12570.Files.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7866/HighFidelity-Beta-PR12570-9681f0eb779278c7170ccbb6647cef940cbdff56.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7874/HighFidelity-Beta-PR12570-554c37d14b5c1b25669eff2c9e9568d0e554b39f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7874/HighFidelity-Beta-PR12570-554c37d14b5c1b25669eff2c9e9568d0e554b39f.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
