### PR TITLE
Needle tool changes

### PR DESCRIPTION
**Pull request by ravi-raman**
Changes of needle tool containing :
1. Needle.html
2. 3 javascript files draw-trace.js, tell-trace.js and load-trace.js
3. Stylesheet file style.css

### CODE REVIEW

**Comment by ravi-raman** [comment]
Needle tool changes to show the average statistics for each function. Details are as follows:
1. Y-axis shows the function names
2. X-axis is scaled on time in ms
3. Each horizontal bar depicts the average duration of the particular function
4. On hovering the mouse over the bar, there is a tool-tip displaying the average start time, end time and duration of the function in ms
5. There is a Reset button on top left corner. On clicking the Reset button, the view is reset back to the initial view.
6. In the initial view, the X-axis starts with the minimum average start time and ends with the maximum average end time in ms so that all the functions are covered
7. In the initial view, you will see only the function names (without the bars). The function names are displayed in the appropriate X and Y locations on purpose, so that the user knows roughly the average start time of these functions. The bars are not shown in the initial view as the average duration value is much lesser than the start time. So, for this we have implemented the zoom-in and zoom-out feature.
8. Zoom-in and Zoom-out feature: To zoom in, the user needs to rotate the mouse-wheel in forward direction and to zoom out , the user needs to rotate the mouse-wheel in the backward direction. On zooming in, the user would eventually see the bars appearing for various functions as soon as the zoom-in is to such an extent that it comes closer to the duration of the function
9. Panning feature: The user can pan the view from left to right or right to left using the mouse by clicking and dragging the mouse in the respective direction.
10. Reset view option: At any point the user can go back to the initial view by clicking on the Reset button placed around top left corner.

**Comment by AndrewMeadows** [comment]
Jenkins, ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1379/HighFidelity-Beta-PR10896-aa65cf2a45ffd68b8fb8cce1dc9ebead7e8b41a3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1379/HighFidelity-Beta-PR10896-aa65cf2a45ffd68b8fb8cce1dc9ebead7e8b41a3.exe

**Comment by themelissabrown** [comment]
@samcake please review this and test for desired outcome

**Comment by ravi-raman** [comment]
@Melissa, in response to your mail asking for test plan:

How to test this:
1. Open needle.html on the browser
2. You can either drag the required trace json file onto the rectangular area highlighted with text "or drop trace file here" OR You can click "Choose Files" and then browse and pick the required json file.
3. After step 2, you would see the graph. Also please refer to my comment above (with 10 points) for the details of the graph.

**Comment by samcake** [comment]
I have tried several toim to load a trace, i see the general diagram, with a horizontal line for each functions but i don;t see any representation (horizontal bars) of the duration of each individual functions.
As if the style wasn't applied
I did see the pop up showing start time average etc

I downloaded all the files in a local folder, used chrome to look at the trace.
I don;t understand why it s not working properly.
i also tried with edge (win10 internet) but got the same result.
another oddity, if i drop a gz file, the code path doesn;t seem to recognize the file as gzipped and goes into the normal (raw json) content instead, whichof course fails....

**Comment by ravi-raman** [comment]
Hey Sam,
I have tested on chrome. It works correctly. 
In the initial view, you would see only the function names. You would not see the horizontal bars, that is because the initial scale of the X-axis is such that it would cover all the function names with their positions matching with their average start times (in the initial view, X-axis starts with minimum of average start time and ends with maximum of average end time). This is done on purpose to ensure that all functions are seen in the initial view.
In order to see the horizontal bars, you would have to zoom-in using the mouse (you need to rotate the mouse wheel in the forward direction to zoom-in and in backward direction to zoom-out). You would have to keep zooming in till the zoomed in state is such that it comes closer to the average duration of the function. You would keep seeing the bar growing in width as you keep zooming in.
Also, please note you can also pan the view by clicking and dragging the mouse from left to right and right to left.
Also, you can reset the view to initial view, by clicking the Reset button around top left corner.

Please note all the details are covered in one of my previous comments above having 10 points. I have posted that comment 5 days ago. Please check that for further details.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1528/HighFidelity-Beta-PR10896-f19bc54627475706600cd40a750b6d60ea5e73cf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1528/HighFidelity-Beta-PR10896-f19bc54627475706600cd40a750b6d60ea5e73cf.dmg

**Comment by samcake** [comment]
testing this today, thank for you patience

**Comment by AndrewMeadows** [comment]
A couple of weeks ago I recall that samcake mentioned a new tool he was working on called "needle", however I don't see it in the hifi/master branch yet and no evidence of it in the logs.  Is this PR the complete needle tool?  or changes to an existing needle implementation?

Meanwhile @samcake is on vacation until late July.  This PR probably needs to wait until he is back online.

**Comment by ravi-raman** [comment]
@AndrewMeadows 
Samuel Gateau sent me the base needle implementation files containing needle.html and the 3 java scripts along with the stylesheet css file.
I then made changes to the base needle implementation as per requirement. The entire changes are in GIT branch https://github.com/ravi-raman/hifi/tree/21153. The corresponding worklist issue is https://worklist.net/21153
At the moment it is in Code Review stage and Sam and myself are having a few discussions regarding the changes.

**Comment by samcake** [comment]
No exactly what we wanted yet.
Putting aside for now

**Pull request closed without merging**
