### PR TITLE
Interface changes for new Marketplace

### PR DESCRIPTION
**Pull request by birarda**
- hide the long CDN URL when prompting to run scripts from marketplace
- run .json files (that aren't .svo.json) if they come from the marketplace CDN

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 216e47b29a79fdce98e6cab450c6281e05a7fd84 available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e7ec7f5944a2303ba67863bd6d20e2886acc0c8c available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Comment by birarda** [comment]
Test notes:

In Interface, while running examples.js, pick a scripted item to run from the Marketplace. 

"Thetherless Tetherball!" is a good option.

Whereas in master you will see something like:

"Do you want to run http://mpassets.highfidelity.com/524fe1bf-22c5-4b2e-9e0b-33cf054e1df8-v1/playTetherball.js"

With this PR you should see:

"Do you want to run playTetherball.js"

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bce924eda4dcb16be76ddd89346cd1503c47474 available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43967dc9a629111221be0f899697d5d4474eb0eb available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11aafc0f48fc3c574c77f87864ae1d908e73d0cb available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11aafc0f48fc3c574c77f87864ae1d908e73d0cb available at: https://gist.github.com/bcf8b5ee62c219fcf811169343eb34d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8213.dmg

**Pull request merged**
