### PR TITLE
add a way for scripts to disable an action before removing them

### PR DESCRIPTION
**Pull request by sethalves**
- scripts can "disable" an action to work around asynchronous nature of their removal.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9808690b59ec584fdab8ed40be5851593f0d4719 available at: https://gist.github.com/4cc0cad02e9e2a21e50e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5913.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5913.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9808690b59ec584fdab8ed40be5851593f0d4719 available at: https://gist.github.com/ea4a160c124d43eed646<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5913.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5913.dmg

**Comment by sethalves** [comment]
This appears to not solve the problem it was trying to fix.  closing.

**Pull request closed without merging**
