### PR TITLE
Case 21513: Keyboad doesn't scale to avatar after reloading content

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.manuscript.com/f/cases/21513/Keyboard-doesn-t-scale-to-avatar-after-reloading-content-with-a-different-size-of-avatar

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18539/HighFidelity-Beta-PR15310-d88a13f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18539/HighFidelity-Beta-Interface-PR15310-d88a13f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18539/HighFidelity-Beta-PR15310-d88a13f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18539/HighFidelity-Quest-Beta-PR15310-d88a13f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18539/HighFidelity-Beta-PR15310-d88a13f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18539/HighFidelity-Beta-Interface-PR15310-d88a13f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18553/HighFidelity-Beta-PR15310-5f5e7d5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18553/HighFidelity-Beta-Interface-PR15310-5f5e7d5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18553/HighFidelity-Beta-PR15310-5f5e7d5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18553/HighFidelity-Quest-Beta-PR15310-5f5e7d5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18553/HighFidelity-Beta-PR15310-5f5e7d5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18553/HighFidelity-Beta-Interface-PR15310-5f5e7d5.exe

**Comment by JeffClinton** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18774/HighFidelity-Beta-PR15310-5f5e7d5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18774/HighFidelity-Beta-Interface-PR15310-5f5e7d5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18774/HighFidelity-Beta-PR15310-5f5e7d5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18774/HighFidelity-Quest-Beta-PR15310-5f5e7d5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18774/HighFidelity-Beta-PR15310-5f5e7d5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18774/HighFidelity-Beta-Interface-PR15310-5f5e7d5.exe

**Pull request merged**
