### PR TITLE
fix bug that caused tractor action to go crazy

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that caused tractor action to go crazy if only one of the two entities it connected were known to interface

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- client-A will watch, client-B would have caused the problem (try it with master to see)
- with client-A go to this position:  hifi://eschatology:0/79.9225,33.5162,78.6227/0,0.348905,0,0.937158
- after client-A is connected and watching, with client-B go to this position: hifi://eschatology/76.273,33.4611,73.7273/0,0.920282,0,0.391257 and be careful to not change client-B's position or orientation
- once client-B is in place, close client-B's interface
- relaunch client-B's interface, be careful to not change client-B's position or orientation
- the drawers in the table that client-A can see (but client-B cannot) shouldn't go crazy

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8804/HighFidelity-Beta-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8804/HighFidelity-Beta-Interface-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8804/HighFidelity-Beta-PR12894-22fd4a7116cbfa641341004db81983453e379166.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8804/HighFidelity-Beta-Interface-PR12894-22fd4a7116cbfa641341004db81983453e379166.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8805/app_12894_PR_22fd4a7116cbfa641341004db81983453e379166.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8805/HighFidelity-Beta-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8805/HighFidelity-Beta-Interface-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8806/app_12894_PR_22fd4a7116cbfa641341004db81983453e379166.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8806/HighFidelity-Beta-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8806/HighFidelity-Beta-Interface-PR12894-22fd4a7116cbfa641341004db81983453e379166.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8806/HighFidelity-Beta-PR12894-22fd4a7116cbfa641341004db81983453e379166.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8806/HighFidelity-Beta-Interface-PR12894-22fd4a7116cbfa641341004db81983453e379166.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Drawers look good and physics respond well.

**Pull request merged**
