### PR TITLE
Remove "Avatar Attachment" option from Edit > Package Model as FST

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Check that the "Avatar Attachment" has been removed as an option from the model packager.
- Select Edit > Package Model as FST.
- A "Select Model" dialog should open.
- The "Model Type" drop-down in the dialog should have only the following two options:
  - Avatar Body with Head
  - Entity Model
  I.e., the drop-down should not have an option, "Avatar Attachment".

2) Check that you can use the other two options to package models.

https://highfidelity.manuscript.com/f/cases/17990

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14846/HighFidelity-Beta-PR14364-ea165ad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14846/HighFidelity-Beta-PR14364-ea165ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14846/HighFidelity-Beta-Interface-PR14364-ea165ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14846/HighFidelity-Beta-PR14364-ea165ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14846/HighFidelity-Beta-Interface-PR14364-ea165ad.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
Removed QA approved tag since this was originally tested 19 days ago, and now there are branch conflicts.

**Pull request closed without merging**
