### PR TITLE
Set minimum timeout for retransmits within reliable network service

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Fogbugz: https://highfidelity.fogbugz.com/f/cases/20300/Avatar-mixer-disconnect

An attempt to prevent the pile-ups in retransmitted packets observed above by putting a floor on the retransmission time for unacknowledged packets of 10 ms.
The more time-critical data, such as audio data and avatar movement data, is not sent via reliable service so any slight latency increase should not be detectable.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16004/HighFidelity-Beta-PR14601-0d14e0b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16004/HighFidelity-Beta-PR14601-0d14e0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16004/HighFidelity-Beta-Interface-PR14601-0d14e0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16004/HighFidelity-Beta-PR14601-0d14e0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16004/HighFidelity-Beta-Interface-PR14601-0d14e0b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16045/HighFidelity-Beta-PR14601-e7fe4af.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16045/HighFidelity-Beta-PR14601-e7fe4af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16045/HighFidelity-Beta-Interface-PR14601-e7fe4af.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16045/HighFidelity-Beta-PR14601-e7fe4af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16045/HighFidelity-Beta-Interface-PR14601-e7fe4af.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16051/HighFidelity-Beta-PR14601-d59e24e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16051/HighFidelity-Beta-PR14601-d59e24e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16051/HighFidelity-Beta-Interface-PR14601-d59e24e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16051/HighFidelity-Beta-PR14601-d59e24e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16051/HighFidelity-Beta-Interface-PR14601-d59e24e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16073/HighFidelity-Beta-PR14601-094bc4c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16073/HighFidelity-Beta-PR14601-094bc4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16073/HighFidelity-Beta-Interface-PR14601-094bc4c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16080/HighFidelity-Beta-PR14601-47365db.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16080/HighFidelity-Beta-PR14601-47365db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16080/HighFidelity-Beta-Interface-PR14601-47365db.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16085/HighFidelity-Beta-PR14601-cfdec0b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16085/HighFidelity-Beta-PR14601-cfdec0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16085/HighFidelity-Beta-Interface-PR14601-cfdec0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16085/HighFidelity-Beta-PR14601-cfdec0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16085/HighFidelity-Beta-Interface-PR14601-cfdec0b.exe

**Comment by howard-stearns** [comment]
This is one of five fixes that are being evaluated against server-under-load issues:
https://github.com/highfidelity/hifi/pull/14601
https://github.com/highfidelity/hifi/pull/14621
https://github.com/highfidelity/hifi/pull/14633
https://github.com/highfidelity/hifi/pull/14627
https://github.com/highfidelity/hifi/pull/14558
Please Do Not Merge until either:
- all five have been evaluated for how they do under server load, or
- you need the fix right away and check with Brad

**Comment by howard-stearns** [comment]
server under load testing:
PREVENTS DROPS (but currently always limits, which adds 10ms latency on reliable packet retransmission)

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16257/HighFidelity-Beta-PR14601-cfdec0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16257/HighFidelity-Beta-Interface-PR14601-cfdec0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16257/HighFidelity-Beta-PR14601-cfdec0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16257/HighFidelity-Beta-Interface-PR14601-cfdec0b.exe

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16270/HighFidelity-Beta-PR14601-cfdec0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16270/HighFidelity-Beta-Interface-PR14601-cfdec0b.exe

**Comment by SimonWalton-HiFi** [comment]
Current branch state: the attempts to only apply the floor during high load periods haven't worked in my tests (before the holiday break) on dist3. Probably it is too late by the time the high congestion is noticed. I would recommend returning to the original unconditional floor for now and looking for any delay issues with avatar entities.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16302/HighFidelity-Beta-PR14601-c88af5c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16302/HighFidelity-Beta-PR14601-c88af5c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16302/HighFidelity-Beta-Interface-PR14601-c88af5c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16302/HighFidelity-Beta-PR14601-c88af5c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16302/HighFidelity-Beta-Interface-PR14601-c88af5c.exe

**Comment by howard-stearns** [comment]
dnm until we complete testing of the "five fixes"

**Comment by antoninahifi** [comment]
no additional testing required

**Comment by howard-stearns** [comment]
Removing the DNM that was placed until the "five fixes" were concurrency-tested.

**Pull request merged**
