### PR TITLE
Quit consistently

### PR DESCRIPTION
**Pull request by howard-stearns**
Make quitting from the operating system window-close button work the same as quitting through the menu. This removes a source of zombie process where there is no application window, but Interface was still running.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/113440034852103

**Comment by howard-stearns** [comment]
To test:

A: Quit from menu Quit:
 - Make sure the log reports "Normal exit".
 - Make sure there are no zombie Interface process running without a window (using Task Manager or the 'ps' command).

B: Repeat by clicking the operating system window-close button.

C: Repeat A and B when a modal dialog is open. 
- This can be done with a 'ok/cancel' modal by opening the Examples button (formerly known as marketplace), picking an avatar, and being prompted as to whether or not you want to wear this avatar.
- It can also be done with an 'ok only' modal by going to a domain that you don't have edit rights in, and opening the edit button. 
- With both kinds of dialog, and regardless of whether you quit by A or B, the application should not actually quit until you dismiss the dialog (with cancel or ok).
- The log and process cleanup should then be as for A.

D: Repeat on Mac if possible (in addition to Windows).

**Comment by ZappoMan** [comment]
Nice find!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0544bcaacd15d83485352ace2e9f5446ed3a948b available at: https://gist.github.com/f92d2df95d040d34284465fa18fd7405<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7725.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7725.dmg

**Comment by Nex-Pro** [comment]
Tested on win10.  Works as per test.
Clean exit when no modal dialogs.
Application quit on dismissing modal dialogs  as in description.
No zombie processes showing in Task manager.

last line of log in each case were all as follows: (

[04/21 02:36:45] [DEBUG] Stopping QML Renderer Thread  0x3888

[04/21 02:44:58] [DEBUG] Stopping QML Renderer Thread  0x2b8c 

etc.

Pass on Win10.

**Pull request merged**
