### PR TITLE
Accept textures as list or json

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent

In the entityProperties window, model textures can be changed to different files.
In current master, they take a ,\n-delimited list of filename:"texturepath".
This allows them to accept json as well: { "filename": "texturepath" }.

#### Testing

Load a model with multiple textures.
Ensure you can change them using the old notation and json.

**Comment by zzmp** [comment]
@imgntn I couldn't take it anymore. Also, I left it backwards-compatible!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 413c3b88cf3012c64d7faa472c4d56ca5db56be7 available at: https://gist.github.com/1c9c813d01584efea30c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7470.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7470.dmg

**Comment by ZappoMan** [comment]
Fixes this crash - https://app.asana.com/0/26225263936266/104901077166745

**Comment by thoys** [comment]
## QA - report

Tested the carpet in the sandbox with `PropSet3_Diffuse_jpg:"http://render911.com/textures/carpet/carpet_7.jpg"` and `{"PropSet3_Diffuse_jpg":"http://render911.com/textures/carpet/carpet_7.jpg"}`

Both methods are working in this PR Build :+1: :heavy_check_mark: 

P.S. it would be nice if the original textures are also displayed as JSON, for clarity

**Comment by zzmp** [comment]
@thoys I agree, but I'm punting that for later.

**Pull request merged**
