### PR TITLE
MS17434: modifying MyAvatar.scale get property

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixes MS[#17434](https://highfidelity.fogbugz.com/f/cases/17434/MyAvatar-scale-doesn-t-report-correct-values)

**TEST PLAN**
- Launch Interface in desktop mode
- In a domain that limits avatar heights
- Change to default wooden avatar
- Use the Avatar app to change the scale to 0.1.
- Enable Developer Menu via `Settings > Developer Menu`
- Open `Developer > Console...`
- Type `MyAvatar.scale` into the Scripting Console.  The scale should be clamped to the domain limit (i.e. `MyAvatar.scale` should return a value larger than 0.1)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12011/HighFidelity-Beta-PR13801-769e7ea.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12011/HighFidelity-Beta-PR13801-769e7ea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12011/HighFidelity-Beta-Interface-PR13801-769e7ea.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by wayne-chen** [comment]
Updated the test plan

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

MyAvatar.scale now reports the avatar's current scale as limited by the domain, rather than what the user tried to set it to in the avatar app.

**Pull request merged**
