### PR TITLE
changed USE_STABLE_GLOBAL_SERVICES to use 1

### PR DESCRIPTION
**Pull request by flipside**
This fixes a production build problem for Ubuntu 16.04 so the `ICE_SERVER_DEFAULT_HOSTNAME` is properly set to `ice.highfidelity.com` for production.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1966a710b58c64d5b91ad455c6ee27522395c302 available at: https://gist.github.com/da6e9764e78bdd24d4b9726debf1b0c8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8801-1966a71.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8801-1966a71.dmg

**Comment by sethalves** [comment]
When I do a dev build with cmake version 3.5.1, the currend code appears to do the right thing.  When you build, do you end up using the production services?

**Comment by flipside** [comment]
These are production changes, before the flag would result it use of the
dev ice server no matter what. This was tested with docker and ubuntu:16.04
and the latest cmake.

**Comment by sethalves** [comment]
Okay, I see that you're right, though I still don't understand why...

**Comment by flipside** [comment]
I don't understand either, I'm guessing it's something with the c++ #if.

**Pull request merged**
