### PR TITLE
Fix icon for polylines in entities editor properties page

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Use fingerPaint.js to create some polylines.
- Using the editor, select one of the polylines (e.g., from entities list) then view its entities properties tab.
- There should be a single icon top left of the dialog representing the polyline (i.e., not a bunch of icons messing up the dialog).

**Comment by CainFoool** [comment]
Will test.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/375/HighFidelity-Beta-PR10608-58c4a2f12ad197631cb3f9424c9e03d35aaf59fc.exe

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by CainFoool** [comment]
# Test Passed 

Fingerpaint entities now have an icon in the dialog which doesn't break the dialog.
02s7a

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/377/HighFidelity-Beta-PR10608-58c4a2f12ad197631cb3f9424c9e03d35aaf59fc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/377/HighFidelity-Beta-PR10608-58c4a2f12ad197631cb3f9424c9e03d35aaf59fc.dmg

**Pull request merged**
