### PR TITLE
Beta Release 65 - includes up to Developer Release 7911

### PR DESCRIPTION
**Pull request by conklin94122**
**New Features**

- You can now bring a 2D image into world as a 3D "poster" object via the Create menu.
- When you rotate a zone, you can now see the outlines.
- Added: new handles in Create mode that are similar to industry standard 3D modeling tool paradigms
- Domain server settings are now split into Content settings (settings associated with content) and Server settings (settings associated with your Sandbox or cloud server). You will find content settings under content tab and server settings under the settings tab. Please note: No functionality has been removed.
- Added functionality to download, upload and create content archives from Content tab. Each content archive will include models.json file, assets in ATP and content settings.
- You can now download and upload server settings archives from the Settings tab to allow easy transfer of settings across different servers.
- Ability to add a material entity in world.
- Ability to certify avatars, apps and content sets.
- During the last stage of Wallet setup, you will see new instructions on how to get HFC. You’ll also get info on generating another private-public key pair when the original pair is lost, or the passphrase has been forgotten.

**Bug Fixes**

- Minor bug fixes around the color picker in Create mode in VR  
- Mac: Minor graphical errors in client resolved
- Logging into the wallet app now correctly logs the user into High Fidelity.
- HMD now correctly tracks the head of an avatar in T-pose
- Fixed issue causing avatar models to scale disproportionately.
- Fixed defect affecting the usability of the people app.
- Fixed bug causing reversion to an older avatar on crashing
- Fixed bug affecting hair offset and scale.
- Fix for not being able to delete zones which have entity children.
- Fix for Create mode property tab UI oddities.
- Fix for behavior in the x,y,z fields of Create menu properties tab.
- Additional support for Google Poly materials
- User does not collide with objects when editing so that editing does not cause the user to be pushed around. 
- Toggle for audiometer now highlights correctly.
- Wallet / send money UI and inspection certificate redesign fixes

**Known Issue**

- When in “Away” mode, you can still see your avatar--normally it should be invisible to you, and seen as kneeling to others.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7595/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7595/HighFidelity-Beta-PR12522-328b5a1e8bd5509f7109c2e7931033b6a3cfd59f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7595/HighFidelity-Beta-PR12522-328b5a1e8bd5509f7109c2e7931033b6a3cfd59f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7658/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7658/HighFidelity-Beta-PR12522-678584538d17c827a97e83710d2e4e31f40bb964.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7658/HighFidelity-Beta-PR12522-678584538d17c827a97e83710d2e4e31f40bb964.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7676/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7676/HighFidelity-Beta-PR12522-be30d8d4ec28bf608516276368c75d18c0b603bb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7676/HighFidelity-Beta-PR12522-be30d8d4ec28bf608516276368c75d18c0b603bb.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7680/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7680/HighFidelity-Beta-PR12522-746f43c0fc8ea1cd20e580ed8b0d4d3918e76ac9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7680/HighFidelity-Beta-PR12522-746f43c0fc8ea1cd20e580ed8b0d4d3918e76ac9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7731/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7731/HighFidelity-Beta-PR12522-acf1f48d9eeab2411e55d4e3887bde2de4f1e00a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7731/HighFidelity-Beta-PR12522-acf1f48d9eeab2411e55d4e3887bde2de4f1e00a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7762/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7762/HighFidelity-Beta-PR12522-9294ae0dd21edfb131a2add688f0abd24bd0eeaa.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7770/app_12522_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7782/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7782/HighFidelity-Beta-PR12522-9294ae0dd21edfb131a2add688f0abd24bd0eeaa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7782/HighFidelity-Beta-PR12522-9294ae0dd21edfb131a2add688f0abd24bd0eeaa.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7830/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7831/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7831/HighFidelity-Beta-PR12522-e0a11271bfbc916711181134a37132d96f70c628.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7831/HighFidelity-Beta-PR12522-e0a11271bfbc916711181134a37132d96f70c628.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7833/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7833/HighFidelity-Beta-PR12522-7381bb0d7e468937ccb3e7013f6aa863272535ee.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7879/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7879/HighFidelity-Beta-PR12522-3e9e55c3db863acad33ab3456dfc8abd82e7c07a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7879/HighFidelity-Beta-PR12522-3e9e55c3db863acad33ab3456dfc8abd82e7c07a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7891/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7891/HighFidelity-Beta-PR12522-c5514f51208b8111974e1b4013c38fe59daff6a6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7896/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7896/HighFidelity-Beta-PR12522-260715d6164ac3d31906e1fda2d28d6686881daf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7896/HighFidelity-Beta-PR12522-260715d6164ac3d31906e1fda2d28d6686881daf.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7909/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7909/HighFidelity-Beta-PR12522-fe0d354d26f5f47babab1e257e4c2580c14713b1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7909/HighFidelity-Beta-PR12522-fe0d354d26f5f47babab1e257e4c2580c14713b1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7925/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7926/app_12522_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7929/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7929/HighFidelity-Beta-PR12522-407dfec34295b71a7a141dca84020df542a591ef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7929/HighFidelity-Beta-PR12522-407dfec34295b71a7a141dca84020df542a591ef.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7934/app_12522_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7934/HighFidelity-Beta-PR12522-25b93d9fd76d1eb186ea32a4db3543193de49c51.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7934/HighFidelity-Beta-PR12522-25b93d9fd76d1eb186ea32a4db3543193de49c51.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8103/HighFidelity-Beta-PR12522-25b93d9fd76d1eb186ea32a4db3543193de49c51.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8103/HighFidelity-Beta-PR12522-25b93d9fd76d1eb186ea32a4db3543193de49c51.exe

**Pull request merged**
