### PR TITLE
Vive: send invalid poses when trackers tracking state is Running_OutOfRange

### PR DESCRIPTION
**Pull request by druiz17**
Vive: send invalid poses when trackers tracking state is Running_OutOfRange

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- @anshuman64 check if these are the desired result that you want when the trackers lost tracking

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1725/HighFidelity-Beta-PR10982-57d85525c1a32ef798917c108f8add75ecd9c4ca.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1728/HighFidelity-Beta-PR10982-75b005a69adf29abd3476d0a400de96bae94e059.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1733/HighFidelity-Beta-PR10982-75b005a69adf29abd3476d0a400de96bae94e059.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1735/HighFidelity-Beta-PR10982-2e042ab6cbeb66b556543778616fcbce4c49d207.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1735/HighFidelity-Beta-PR10982-2e042ab6cbeb66b556543778616fcbce4c49d207.dmg

**Comment by anshuman64** [comment]
@druiz17 This behaves extremely poorly when SteamVR has slight tracking issues. For example, the legs frequently jitter and pops. We need to rethink this approach.

**Comment by anshuman64** [comment]
Here are new findings:
- Running_OK: the only flag that gives good data
- Running_OutOfRange: the puck is "floating". This causes the IK to fail the worst.
- Calibrating_OutOfRange: SteamVR has no idea where the puck is and has essentially turned it off.
- Calibrating_InProgress: Never occurs in Interface.

@druiz17 will rework this code so that it only considers Running_OK as valid data.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1856/HighFidelity-Beta-PR10982-83a5cfd9c01a1b1d5caf1dc7073e136d791d4b8f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1856/HighFidelity-Beta-PR10982-83a5cfd9c01a1b1d5caf1dc7073e136d791d4b8f.exe

**Comment by anshuman64** [comment]
Closing in favor of different implementation: https://highfidelity.fogbugz.com/f/cases/6592/Mocap-Better-Handling-of-Dropped-Frames

**Pull request closed without merging**
