### PR TITLE
Case 22333: Master: Fix asset server auto-baking

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.fogbugz.com/f/cases/22333/Asset-Server-Baking-broken-in-master)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18932/HighFidelity-Beta-PR15443-2c3dd15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18932/HighFidelity-Beta-Interface-PR15443-2c3dd15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18932/HighFidelity-Beta-PR15443-2c3dd15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18932/HighFidelity-Beta-Interface-PR15443-2c3dd15.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18932/HighFidelity-Beta-PR15443-2c3dd15.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18932/HighFidelity-Quest-Beta-PR15443-2c3dd15.apk)

**Comment by howard-stearns** [comment]
[fix asset server for new oven](https://trello.com/c/8FNHKUU2/79-fix-asset-server-for-new-oven)

**Pull request merged**
