### PR TITLE
rename .app on OS X to Interface

### PR DESCRIPTION
**Pull request by birarda**
- changes the client bundle name on OS X back to "Interface"

### CODE REVIEW

**Comment by birarda** [comment]
Test notes:

- Install the PR build on OS X. Ensure that the application name is Interface and not High Fidelity, and that it runs.

**Comment by birarda** [comment]
This is a fix for https://app.asana.com/0/11984398816645/112314198840126

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e02b302276c078b49b6b2e094932809f5493ea0 available at: https://gist.github.com/2d5dc38507e81eed749de70e0d9c22f4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7666.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7666.dmg

**Comment by kevinmthomas-carpool** [comment]
Confirmed MAC build is application name is Interface and not High Fidelity, and that it runs.

**Pull request merged**
