### PR TITLE
Add logging to the windows installer to track install options and install steps

### PR DESCRIPTION
**Pull request by roxanneskelly**
Some very basic setup logging.

Logging ends up in %APPDATA%\Local\Temp\hifi_install.log

### CODE REVIEW

**Comment by roxanneskelly** [comment]
Test Plan

* Perform an install.
* Validate %APPDATA%\Local\Temp\hifi_install.log shows up and contains logging representing the install steps and options that were chosen.

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/19427/Windows-installer-logging

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14144/HighFidelity-Beta-PR14236-659302d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14144/HighFidelity-Beta-PR14236-659302d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14144/HighFidelity-Beta-Interface-PR14236-659302d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14495/HighFidelity-Beta-PR14236-1dc96fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14495/HighFidelity-Beta-Interface-PR14236-1dc96fe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14495/HighFidelity-Beta-PR14236-1dc96fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14495/HighFidelity-Beta-Interface-PR14236-1dc96fe.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14534/HighFidelity-Beta-PR14236-2482bb9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14534/HighFidelity-Beta-PR14236-2482bb9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14534/HighFidelity-Beta-Interface-PR14236-2482bb9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14534/HighFidelity-Beta-PR14236-2482bb9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14534/HighFidelity-Beta-Interface-PR14236-2482bb9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14926/HighFidelity-Beta-PR14236-04a3d6f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14926/HighFidelity-Beta-PR14236-04a3d6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14926/HighFidelity-Beta-Interface-PR14236-04a3d6f.dmg

**Pull request merged**
