### PR TITLE
Automatic creation of MD file.

### PR DESCRIPTION
**Pull request by NissimHadar**
Can write first few lines of MD file.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8314/app_12725_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8314/HighFidelity-Beta-PR12725-1279c5c8992d3c2ebd37a403ee5cb5310e908c26.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8314/HighFidelity-Beta-PR12725-1279c5c8992d3c2ebd37a403ee5cb5310e908c26.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8326/app_12725_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8326/HighFidelity-Beta-PR12725-d60898ffd22c87b31bec947fa5494960e7d015d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8326/HighFidelity-Beta-PR12725-d60898ffd22c87b31bec947fa5494960e7d015d0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8338/app_12725_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8339/app_12725_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8339/HighFidelity-Beta-PR12725-d8bd850e7753b10dc33e274f67ccf74032885ad0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8437/HighFidelity-Beta-PR12725-cc8c4ee181f066f3bd3819a863bfd5a41356e84b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8437/HighFidelity-Beta-PR12725-cc8c4ee181f066f3bd3819a863bfd5a41356e84b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8438/HighFidelity-Beta-PR12725-5f738bcd8a1b6888dfd18051098f9d91c251ed6e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8438/HighFidelity-Beta-PR12725-5f738bcd8a1b6888dfd18051098f9d91c251ed6e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8444/HighFidelity-Beta-PR12725-75230f1a1f6f77d35da66a975a9e4b779541324f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8444/HighFidelity-Beta-PR12725-75230f1a1f6f77d35da66a975a9e4b779541324f.exe

**Comment by NissimHadar** [comment]
For future implementation

**Pull request closed without merging**
