### PR TITLE
Case 21317: Unable to click icons on tablet when in HMD (0.81.0)

### PR DESCRIPTION
**Pull request by danteruiz**
ticket - https://highfidelity.manuscript.com/f/cases/21317/Unable-to-click-icons-on-tablet-when-in-HMD-0-81-0

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan
make sure you can interact with the tablet

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17412/HighFidelity-Beta-PR14960-d1c46e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17412/HighFidelity-Beta-PR14960-d1c46e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17412/HighFidelity-Beta-Interface-PR14960-d1c46e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17412/HighFidelity-Beta-PR14960-d1c46e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17412/HighFidelity-Beta-Interface-PR14960-d1c46e1.exe

**Pull request merged**
