### PR TITLE
Fix the AudioMixer distance attenuation.

### PR DESCRIPTION
**Pull request by kencooke**
The zone settings are still used, and still match the documentation where 0 = no attenuation and 1 = max attenuation.  The default is now 0.5 which corresponds to -6dB per doubling of distance. This is the attenuation for a spherical wave in the free field.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59ac2a789ff9bd406bc20c4605754f64f9effe3c available at: https://gist.github.com/324937ecec3b15f7751e0b3eff72acc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-59ac2a7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-59ac2a7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ee608ad2cb13ce7f23374ea93f7f040a717d16b available at: https://gist.github.com/324937ecec3b15f7751e0b3eff72acc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-1ee608a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-1ee608a.dmg

**Comment by kencooke** [comment]
## Test Plan
This PR fixes a serious bug in the audio falloff in Sandbox.  To test,
1) Make sure to install Sandbox from this PR
2) Verify that you hear server-echo and other avatars on your server
3) Try changing "Default Domain Attenuation" in your server settings to a small value (0.1) and verify you can now hear scripted sounds or avatars for a very long distance.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b03686c37f53c8362595cb9b65fe75bc2890d4b9 available at: https://gist.github.com/324937ecec3b15f7751e0b3eff72acc2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-b03686c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8259-b03686c.dmg

**Pull request merged**
