### PR TITLE
Fix bug with disappearing certificate info

### PR DESCRIPTION
**Pull request by zfox23**
**Test Plan:**
1. Rez a certified entity
2. Right click on the entity, then click on the (i) context overlay that appears
3. Verify that the certificate you see appears to be valid
4. Defocus the cert popup (i.e. click outside it), then walk forward until the cert disappears from your screen
5. Stop walking. Wait for the cert to reappear on-screen. Verify that the information in the cert display is the same as in (3).
6. Close the cert. Repeat steps 2 and 3 again.
7. Repeat steps 1-3 again, this time with a different certified entity.
8. With the cert from (7) visible on-screen, right click the _other_ entity and open its cert.
9. Verify that the cert displayed on-screen is valid and relevant to the entity you right clicked

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4877/HighFidelity-Beta-PR11803-641c4656c44c30de082c0b889f0a1ef2d7aafc21.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4877/HighFidelity-Beta-PR11803-641c4656c44c30de082c0b889f0a1ef2d7aafc21.exe

**Comment by YuppyPlays** [comment]
Tseting.

**Comment by YuppyPlays** [comment]
Testing complete:

Rez a certified entity **Check**
Right click on the entity, then click on the (i) context overlay that appears **Check**
Verify that the certificate you see appears to be valid **Check**
Defocus the cert popup (i.e. click outside it), then walk forward until the cert disappears from your screen **Check**
Stop walking. Wait for the cert to reappear on-screen. Verify that the information in the cert display is the same as in (3). **Check**
Close the cert. Repeat steps 2 and 3 again. **Check**
Repeat steps 1-3 again, this time with a different certified entity. **Check**
With the cert from (7) visible on-screen, right click the other entity and open its cert. **Check**
Verify that the cert displayed on-screen is valid and relevant to the entity you right clicked **Check**

**Notes: Tested with Flaregun and Beach ball**

**Pass** :D

**Pull request merged**
