### PR TITLE
DEV-2044 - add notification that temporary domains won't show up in domain list

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21708/HighFidelity-Beta-PR16293-38afa6b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21708/HighFidelity-Quest-Beta-PR16293-38afa6b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21708/HighFidelity-Beta-PR16293-38afa6b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21708/HighFidelity-Beta-Interface-PR16293-38afa6b.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21721/HighFidelity-Beta-PR16293-38afa6b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21721/HighFidelity-Beta-Interface-PR16293-38afa6b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21721/HighFidelity-Beta-PR16293-38afa6b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21721/HighFidelity-Quest-Beta-PR16293-38afa6b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21721/HighFidelity-Beta-PR16293-38afa6b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21721/HighFidelity-Beta-Interface-PR16293-38afa6b.exe

**Pull request merged**
