### PR TITLE
Fix for black screen on HMDs on startup

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by conklin94122** [comment]
RC59 base of https://github.com/highfidelity/hifi/pull/11826

**Comment by conklin94122** [comment]
https://github.com/highfidelity/hifi/pull/11826

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4994/HighFidelity-Beta-PR11827-302b532279ba830948ec140e4c79f878d1edfc69.dmg

**Comment by ZappoMan** [comment]
This PR looks very risky to me.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5007/HighFidelity-Beta-PR11827-0755e4aa214031b95733a6dcd6c69478bb178110.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5007/HighFidelity-Beta-PR11827-0755e4aa214031b95733a6dcd6c69478bb178110.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by conklin94122** [comment]
Also running https://highfidelity.testrail.net/index.php?/plans/view/1017

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Start Interface | Pass
Switch to the HMD Simulator display plugin in the Display menu | Pass
Shut down Interface | Pass
Restart interface | Pass

##### [In Addition to TestRail Run 1018](https://highfidelity.testrail.net/index.php?/runs/view/1018&group_by=cases:section_id&group_order=asc&group_id=594)
Solid Pass!

**Pull request merged**
