### PR TITLE
Fixed the keyboard not showing  up for goto in HMD mode

### PR DESCRIPTION
**Pull request by druiz17**
Fixed the keyboard not showing  up for goto in desktop mode

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1. Desktop
- open goto and check that typing in the address line still work
- check that the address line still gains focus after you clicking off the address line.

2. HMD
- open goto ..click on the address line, the keyboard should pop up
- click on any white space in goto, and the keyboard should disappear, then repeat the previous step.

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by Nex-Pro** [comment]
@druiz17  Title makes more sense now.

**Comment by Nex-Pro** [comment]
sorry have to drop this

**Comment by CainFoool** [comment]
Testing now.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1395/HighFidelity-Beta-PR10901-2d876377d58071255f4dc0e9fa4150f98da13e9a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1395/HighFidelity-Beta-PR10901-2d876377d58071255f4dc0e9fa4150f98da13e9a.dmg

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
**Desktop** | 
open goto and check that typing in the address line still work | Pass
check that the address line still gains focus after you clicking off the address line. | Pass
**HMD** | 
open goto ..click on the address line, the keyboard should pop up | Pass
click on any white space in goto, and the keyboard should disappear, then repeat the previous step. | Pass

All good here.

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
