### PR TITLE
clean audio stats and remove jitter padding

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ddc1fa8be882d2aad2e8949d05a7bb19c3ed99 available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d88b96b77b356e1aefabc8eac40660b8d0d53a6f available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-d88b96b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-d88b96b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ddc1fa8be882d2aad2e8949d05a7bb19c3ed99 available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ddc1fa8be882d2aad2e8949d05a7bb19c3ed99 available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-76ddc1f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f9a725ab37dff4ca8a49d381c515722521f2a308 available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-f9a725a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-f9a725a.dmg

**Comment by zzmp** [comment]
QA:

- The audio stats should still work: `Developer > Audio > Audio Network Stats...`
- Smoke test audio

I removed padding on the jitter buffer. What this should do is allow audio to normalize to a lower latency faster when network latency lowers. Listen for crackles and pops and dropped audio that you did not hear before. Note that audio may take a half minute after startup to stabilize (normal, existing behavior).

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: SUCCESS
**Additional Test Results + Observations**:  Enabled ```Developer > Audio > Audio Network Stats```.  I observed no crackles or pops or dropped audio.  Included a snap-shot of the ```Audio Network Statistics``` web UI as well.
stats

**Comment by OmegaHeron** [comment]
Since I've had such a "fun" time with my exotic (wireless) audio headset -- I gave this a try too.  I'm able to set output buffer initial size to 1 and have stable audio as I traverse domains ranging from localhost to second LAN machine to sever Inet connected domains.  I saw audio server ping time from 0 to 120 and was able to maintain stable pop free audio across them all.  A huge improvement.

**Comment by ZappoMan** [comment]
@zzmp - maybe we should convert this dialog box to a Developer JS/QML overlay... we can make that a different PR from this, but I think that's a bit of cleanup that would help with overall code cleanliness.

**Comment by ZappoMan** [comment]
@zzmp - I'm not a huge fan of your new formatting, I'm a little confused by it... (admittedly the old stats were also confusing)...

Some suggestions: let's include the units next to (following) any value... so... 

```
ping (client->mixer->client): 84 ms
input read: 10 ms // ??? is that ms or buffers?
...
```

Also... I noticed that you've include the ping as a combined number... which is fine, the intent of the old format was to show the delays essentially in the order the appear... so...

- Audio Input Buffer --- this is first, it's what's coming from the OS/mic...
- Input Ring Buffer --- this is second, we stick the samples here, until we have enough to make a full packet to send
- Network to mixer --- this was half the ping, and it's intended to demonstrate the time to send the packet from the client to mixer
- Network to client --- the other half of ping
- Output Ring Buffer --- basically the receiving ring buffer to smooth out potential jitter from the mixer
- Audio Output Buffer --- number of samples deep we "believe" the OS output queue is...

As you can see that's basically an "in order" tally of the buffers....

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3cbae189362d941338598bf06ae86de7970023ee available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-3cbae18.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-3cbae18.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3e36b0db9ea038d881f623b8996c7f3484fd73d available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-e3e36b0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-e3e36b0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e315a0a0551bde23f77402a7c7b3e4b70626cef available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-6e315a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-6e315a0.dmg

**Comment by zzmp** [comment]
Ken heard clicks. Hold off on the merge until I check it with a sinusoid.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbbc48c7acc2b74b497aed3a19fdcd52b2d7036a available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-bbbc48c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-bbbc48c.dmg

**Comment by zzmp** [comment]
QA (these are updated instructions, I've removed the old ones):

- The audio stats should still work: `Developer > Audio > Audio Network Stats...`
- Smoke test audio
  - If you are on a bad network with occasional audio dropouts, you should only hear a single 'click' from each dropout (before, you would sometimes hear multiple subsequent clicks)
- There are two new settings, only available in DEV/PR builds, both under `Settings > Audio`
  - `Packet jitter simulator` - overrides `Packet throttle threshold` - audio packets are held, and there is a 60% chance on any audio packet receipt that the held packets will be flushed. This simulates varied network simulation (jitter) because our internet is too good :/
  - `Packet throttle threshold` - holds the set number of audio packets before flushing them, forcing the jitter buffer to grow to be the set number of frames

Listen for crackles and pops and dropped audio that you did not hear before. Note that audio may take a half minute after startup to stabilize (normal, existing behavior).

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3350356ae2f97cef5a387d2a20091e12ca8f6a6 available at: https://gist.github.com/ba18783440456c8ee3d2dabfb3069f80<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-f335035.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8597-f335035.dmg

**Comment by zzmp** [comment]
Closed because of scope creep.

Audio network statistics cleanup is now #8609.
Audio jitter simulator is now #8610.
Audio jitter padding removal is no longer being PRed.

**Pull request closed without merging**
