### PR TITLE
Haze

### PR DESCRIPTION
**Pull request by NissimHadar**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3144/HighFidelity-Beta-PR11327-5d7249af7230906beb6ef49b252bcd2bc6ca217c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3144/HighFidelity-Beta-PR11327-5d7249af7230906beb6ef49b252bcd2bc6ca217c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3225/HighFidelity-Beta-PR11327-d4e35c605c2d3dbbe5f5b754fb420696d9e5214c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3225/HighFidelity-Beta-PR11327-d4e35c605c2d3dbbe5f5b754fb420696d9e5214c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3262/HighFidelity-Beta-PR11327-049882bbc068297fd3bbb99a9ea883909806b4ff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3262/HighFidelity-Beta-PR11327-049882bbc068297fd3bbb99a9ea883909806b4ff.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3275/HighFidelity-Beta-PR11327-2f8dd6e8576d9299838d2507418fe1c98597b3ce.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3276/HighFidelity-Beta-PR11327-2f8dd6e8576d9299838d2507418fe1c98597b3ce.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3276/HighFidelity-Beta-PR11327-2f8dd6e8576d9299838d2507418fe1c98597b3ce.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3383/HighFidelity-Beta-PR11327-531fcd64f1b6fb436235c2509352b9f500eb9e3b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3383/HighFidelity-Beta-PR11327-531fcd64f1b6fb436235c2509352b9f500eb9e3b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3419/HighFidelity-Beta-PR11327-24bf96d64bd123e0eec8e7fee919a48ef9f192f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3430/HighFidelity-Beta-PR11327-f296e6b1ab288b95f3c91c919aaf76db55bc15b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3430/HighFidelity-Beta-PR11327-f296e6b1ab288b95f3c91c919aaf76db55bc15b7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3468/HighFidelity-Beta-PR11327-9327ecf0e266b7f2db80a292c05d5cc8d5e14eb2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3468/HighFidelity-Beta-PR11327-9327ecf0e266b7f2db80a292c05d5cc8d5e14eb2.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3471/HighFidelity-Beta-PR11327-6f0a5a9293dde1ee222c626ddbf04b9a5cea5280.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3488/HighFidelity-Beta-PR11327-f5f898679c6fbd7116dbd11299c7441a6340cc1a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3488/HighFidelity-Beta-PR11327-f5f898679c6fbd7116dbd11299c7441a6340cc1a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3509/HighFidelity-Beta-PR11327-23afde837da5bde24708fa4478864541ccbeabe2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3509/HighFidelity-Beta-PR11327-23afde837da5bde24708fa4478864541ccbeabe2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3517/HighFidelity-Beta-PR11327-6a829d2e81a0be7cf40de26cbafb710627e0fdb3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3517/HighFidelity-Beta-PR11327-6a829d2e81a0be7cf40de26cbafb710627e0fdb3.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3610/HighFidelity-Beta-PR11327-e4c60309e91330ab9cc0da4f78e276afcdf31fda.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3610/HighFidelity-Beta-PR11327-e4c60309e91330ab9cc0da4f78e276afcdf31fda.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3643/HighFidelity-Beta-PR11327-a6037f0486d13042d3f72fd3eade1bf795f7b17f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3643/HighFidelity-Beta-PR11327-a6037f0486d13042d3f72fd3eade1bf795f7b17f.dmg

**Comment by samcake** [comment]
This pr can be closed, this was the draft for the hazeZOne other PR coming up shortly

**Pull request closed without merging**
