### PR TITLE
Adds support for "lasers" to the Oculus+xbox controller

### PR DESCRIPTION
**Pull request by ZappoMan**
- Using the Xbox triggers, and looking around will give you lasers similar to the vive hand controllers
- laser comes from "third eye" like the xbox teleport does
- lasers can control HUD items, click on items from the directory, open/close dialog boxes, etc...
- far grab will work (unexpected/happy side effect)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ca3aa546df72d2674a8147bf2f548357dad33a available at: https://gist.github.com/99c2591e96f9f3cac6703cc1565c6a6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8894-76ca3aa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8894-76ca3aa.dmg

**Comment by hyperlogic** [comment]
Nice work, glad to hear far grabbing works with this change. I'll test it on my CV1 when I get home.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c28316e39a46116cbb5544027356d8b15bd5d58 available at: https://gist.github.com/99c2591e96f9f3cac6703cc1565c6a6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8894-2c28316.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8894-2c28316.dmg

**Comment by OmegaHeron** [comment]
I looked at this with DK2/Desktop modes and XBox controller - it seems to work, but, honestly... never used any of the hand controlled stuff before and am not feeling qualified to say it's a pass.

I was able to see laser when triggered, things laser intersected with that could be moved did move with my head motion.  In old home scene if I intersected with pingpong gun beam turned purple, but I didn't have a notion what to do to attach.

**Pull request merged**
