### PR TITLE
Rendering the background elements after opaque and only work on the far pixels

### PR DESCRIPTION
**Pull request by samcake**
- Introduce a stencil buffer generated after the deferred opaque items are rendered. This stencil buffer can then be used to do stencil test for background items rendering

- Tweek the pipeline.state.stencilTest of all the elments rendered as background.

- Clean up the static elements initialization of the skybox rendering and unify the rendering with or without skymap. Theuniform bufer containing the constant color is now part of the skybox instance

- Implement the missing features for stencil buffer /framebuffer in gpu

- Todo: IMprove perf, not a win right now but we are talking of ~2% of the total frame time so  not too bad for a usefu new feature

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b86f21491359c8f96918969439ed80f224ba82b available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be9b244779a6b4e34156a22d43004f2fde06d18d available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3d47752327dd0a90fee77e30993d5c16bcb0193 available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69c40754390f7e70dcfcd16f79bf14f278e5286f available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by samcake** [comment]
THis should be good to go
I do see a perf improvment sometime :)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0398f9429e9d7d21f181167664b52eb0799aecd7 available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3490e08521360bde1d0f0266f64ddacbab48a410 available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 690620d74d7889f831a078f18c26f81b7958d935 available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71ad6195f2e1d0b188e6eb85ca88d5f1622b550c available at: https://gist.github.com/42d08a38713540624814<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5962.dmg

**Comment by ZappoMan** [comment]
runs on mac - downloading windows now

**Comment by ZappoMan** [comment]
smoked on windows too

**Pull request merged**
