### PR TITLE
Case 21071: Handle models with no materials

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21071/Towlie-avatar-fbx-gets-rendered-with-the-textures-of-nearby-models

Test plan:
- create a model with this URL: https://hifi-content.s3.amazonaws.com/samuel/Ovoid.fbx in a domain with lots of other models with textures
- you should see a white ovoid in front of you. It shouldn't pick up the textures of the things around it.
- move around and confirm that the thing always renders white

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17529/HighFidelity-Beta-PR14993-a31b09b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17529/HighFidelity-Beta-PR14993-a31b09b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17529/HighFidelity-Beta-Interface-PR14993-a31b09b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17529/HighFidelity-Beta-PR14993-a31b09b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17529/HighFidelity-Beta-Interface-PR14993-a31b09b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17533/HighFidelity-Beta-PR14993-dbc3ae3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17533/HighFidelity-Beta-PR14993-dbc3ae3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17533/HighFidelity-Beta-Interface-PR14993-dbc3ae3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17533/HighFidelity-Beta-PR14993-dbc3ae3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17533/HighFidelity-Beta-Interface-PR14993-dbc3ae3.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17622/HighFidelity-Beta-PR14993-6e4ec15.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17622/HighFidelity-Quest-Beta-PR14993-6e4ec15.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17622/HighFidelity-Beta-PR14993-6e4ec15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17622/HighFidelity-Beta-Interface-PR14993-6e4ec15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17622/HighFidelity-Beta-PR14993-6e4ec15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17622/HighFidelity-Beta-Interface-PR14993-6e4ec15.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request merged**
