### PR TITLE
Reduce echo when push-to-talk is used

### PR DESCRIPTION
**Pull request by kencooke**
This PR ducks the audio output by 20dB when PTT is active. It reduces the feedback from the push-to-talker's speakers into the mic, while avoiding the loss of immersion (very noticeable on headphones) of completely muting the output. Gain changes are interpolated to prevent clicking artifacts.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19306/HighFidelity-Beta-PR15534-1b733d3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19306/HighFidelity-Quest-Beta-PR15534-1b733d3.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19306/HighFidelity-Beta-PR15534-1b733d3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19306/HighFidelity-Beta-Interface-PR15534-1b733d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19306/HighFidelity-Beta-PR15534-1b733d3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19306/HighFidelity-Beta-Interface-PR15534-1b733d3.exe

**Comment by kencooke** [comment]
### Test Plan ###
With Interface from this PR, enable PTT in the Audio tab and confirm that when you press T to talk, the output volume becomes quieter. When you release T, it should become normal again.

**Pull request merged**
