### PR TITLE
Beta Release 19 - Includes up to Developer Release 5298

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Add priority loading for model entities
* Automatically show address bar after disconnected for X seconds
* Speed up gamma correction in cube map processing
* Default skybox change
* Disable Asset Browser's right-click popup menu if in HMD mode
* eslintrc: accept spaces after function keyword in anonymous functions
* Teleport works with xbox controllers
* Add fade in loading effect
* Add support for ATP protocol to QML
* Fix crash when adding new attachment
* Miscellaneous cmake and render engine improvements
* Mini mirror fades with overlays
* Fix procedural entity transparency
* Faster image processing on load
* Default DS to allow connect for standard groups
* 3D Overlays can be children
* Fix ignore icon stuck in hover state
* Open Asset Browser with Button from Edit.js Toolbar
* Threaded rendering
  * Migrates the rendering of a frame (consisting of an arbitrary number of batches) to the present thread
  * Uses the main window GL context as the execution context for all rendering 
  * Update plugin functionality to use GPU library batches 
* Fix assets example not using correct API
* Fix cubemaps on AMD cards running GL 4.5
* Don't show equip sphere until hand is in position to equip. widen unequip/drop cone
* Add asset server bandwidth to stats
* Fix transparency on procedural shapes
* Entities created using edit.js or imported from marketplace have better positions. 
* Add a button to the sandbox log window to open the log directory
* Fix Asset Browser dialog
* Map oculus touch grip to trigger
* Fix flashing in default skybox, and allow skybox lighting without textures
* Address issues with random camera locations caused by bad HMD sensor poses 
* Fix log flood in debug mode from Buffer::Iterator 
* Don't do fade effect once physics kick in
* Add backup directory setting to domain server
* Add more user activity data
* Movement changes for Hand Controllers
* Workaround bad FBXMesh data rather than assert
* Allow temp domains to use access token when present
* IgnoreIK flag on action-grabbable objects works again

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c80a35c4bbad9b123dce726e85802dc87dcbca8 available at: https://gist.github.com/35e7eda8cdd3ad02e503d7e3e17bb54c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-6c80a35.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-6c80a35.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by OmegaHeron** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: No issues. Expected behavior.  No issues with HMD/ using Oculus, tested back and forth with 'h' mode and eye-level tests were all successful.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |51
**Present Rate**: |60 |60 |59
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4231 |1267 |2494
**GPU Buffer Count**: |623 |161 |273
**CPU Memory Usage**: |70717440 |24047616 |41201664
**GPU Memory Usage**: |22224896 |6160384 |15761408
**CPU Texture Count**: |239 |130 |238
**GPU Texture Count**: |601 |619 |637
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |410479876 |154280608 |482163528
**GPU Texture Memory Usage**: |518204394 |267405680 |417534299
**GPU Virtual Memory Usage**: |643339882|392541168|542669787
**Triangle Count**: |158310 |81175 |138893
**Triangle Rate**: |9894375 |5073437 |8170176
**API Drawcall Count**: |98 |46 |93
**Drawcall Count**: |151 |46 |93
**Drawcall Rate**: |9437 |2875 |5470
**State Changes Texture Count**:|100 |61 |151
**Pipeline Count**: |34 |30 |35
**Item Opaques**: |81 |35 |64
**Item Translucents**: |9 |2 |37
**Item Lights**: |20 |16 |6
**Timing Opaques**: |405 |136 |326
**Timing Translucents**: |26 |9 |168
**Timing Lighting**: |185 |156 |88
**Render Frame**: |1521 |933 |1328

**Comment by nbq** [comment]
testing this now

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** FAILURE
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Create test blocks JS refused to load, but, I think it's an error in RC script or network issue.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|ok
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|I don't hear anything at dev-playa.  I do hear sounds at localhost content.
**Test 4**|undefined|
**Test 5**|Retest the kick function|ok
**Test 6**|Switch avatar and make sure it does not crash|ok
**Test 7**|Test group functions|Unable -have no groups
**Test 8**|Retest the kick function|ok - again.
**Test 9**|Enrure that you can distance grab|unable to test

Desktop mode 1600x900 maximized window - vsync unlocked.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |248 |244 |262
**Present Rate**: |248 |246 |382
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4045 |4396 |5220
**GPU Buffer Count**: |1545 |1248 |1151
**CPU Memory Usage**: |65441792 |67248128 |101171200
**GPU Memory Usage**: |52895744 |44265472 |50302976
**CPU Texture Count**: |302 |293 |389
**GPU Texture Count**: |524 |731 |1042
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |92368372 |234543848 |321678992
**GPU Texture Memory Usage**: |1088605321 |1863473957 |1292355561
**GPU Virtual Memory Usage**: |1178599689|1953468325|1382349929
**Triangle Count**: |582797 |883016 |820094
**Triangle Rate**: |194265666 |220754000 |273364666
**API Drawcall Count**: |203 |335 |305
**Drawcall Count**: |257 |378 |1238
**Drawcall Rate**: |85666 |94500 |412666
**State Changes Texture Count**:|216 |399 |465
**Pipeline Count**: |36 |45 |65
**Item Opaques**: |264 |448 |288
**Item Translucents**: |38 |67 |77
**Item Lights**: |18 |78 |32
**Timing Opaques**: |714 |1212 |875
**Timing Translucents**: |49 |76 |153
**Timing Lighting**: |117 |83 |113
**Render Frame**: |1667 |2483 |2139

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4585 |4826 |5244
**GPU Buffer Count**: |1431 |1375 |1374
**CPU Memory Usage**: |79060992 |83116032 |101179392
**GPU Memory Usage**: |52502528 |53858304 |63238144
**CPU Texture Count**: |302 |329 |388
**GPU Texture Count**: |1463 |1307 |1174
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |202829468 |624708328 |204926608
**GPU Texture Memory Usage**: |1087034855 |1449203571 |1448068211
**GPU Virtual Memory Usage**: |1336232895|1698401611|1697266251
**Triangle Count**: |1780796 |1888919 |1518907
**Triangle Rate**: |136984307 |145301461 |116839000
**API Drawcall Count**: |248 |318 |286
**Drawcall Count**: |590 |705 |2394
**Drawcall Rate**: |45384 |54230 |184153
**State Changes Texture Count**:|269 |347 |432
**Pipeline Count**: |49 |38 |65
**Item Opaques**: |273 |477 |299
**Item Translucents**: |52 |66 |78
**Item Lights**: |22 |85 |34
**Timing Opaques**: |804 |1541 |1099
**Timing Translucents**: |58 |113 |152
**Timing Lighting**: |90 |107 |122
**Render Frame**: |1750 |3017 |2374

**Comment by Nex-Pro** [comment]
**PR Build:** #8508
**Testing Architecture:** Desktop
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** OSX El Capitan
**HMD:** None
**Hand Controllers:** None

**Test Script employed:** http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

## QA Test

**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**:  SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**:  SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE Does not work but not specific to this PR.
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: FAILURE
**Additional Test Results + Observations**:

Unable to manipulate entities in edit mode via handles or rotators. This is not specific to this PR !


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |57
**Present Rate**: |60 |60 |58
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |3094 |5086 |8565
**GPU Buffer Count**: |893 |1223 |2091
**CPU Memory Usage**: |61947904 |92352512 |164397056
**GPU Memory Usage**: |23257088 |43327488 |89706496
**CPU Texture Count**: |236 |320 |599
**GPU Texture Count**: |1104 |1613 |2369
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |312719348 |611659564 |284329796
**GPU Texture Memory Usage**: |749866604 |1413799329 |2620897829
**GPU Virtual Memory Usage**: |874256172|1538188897|2745287397
**Triangle Count**: |509007 |1046758 |934898
**Triangle Rate**: |31812937 |69783866 |34625851
**API Drawcall Count**: |231 |345 |583
**Drawcall Count**: |286 |389 |1273
**Drawcall Rate**: |17875 |25933 |47148
**State Changes Texture Count**:|253 |403 |468
**Pipeline Count**: |44 |50 |314
**Item Opaques**: |270 |521 |446
**Item Translucents**: |25 |68 |324
**Item Lights**: |21 |86 |38
**Timing Opaques**: |607 |1432 |1003
**Timing Translucents**: |65 |167 |283
**Timing Lighting**: |30 |31 |29
**Render Frame**: |1179 |2506 |2028

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Fail no fish ! Tried everything to get them. Toys could see them I could not
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|No background sounds heard. Sounds at dev-demo work fine.
**Test 4**|undefined|This test had no issues whatsoever.
**Test 5**|Retest the kick function|No kick overlays visible in this or 5244.
**Test 6**|Switch avatar and make sure it does not crash|SUCCESS
**Test 7**|Test group functions|Added earth group and granted rez perms applied and restarted. Did not work.
**Test 8**|Retest the kick function|Fail. No overlays
**Test 9**|Enrure that you can distance grab|No Vive support in OSX

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: All works fine

# Desktop Stats:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |58
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |1205 |4513 |5638
**GPU Buffer Count**: |766 |1111 |1459
**CPU Memory Usage**: |16310272 |73641984 |87121920
**GPU Memory Usage**: |10215424 |20938752 |44666880
**CPU Texture Count**: |51 |145 |410
**GPU Texture Count**: |1485 |1943 |2077
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |36607320 |96965976 |399391872
**GPU Texture Memory Usage**: |57757770 |237077331 |1096788112
**GPU Virtual Memory Usage**: |164152018|343471579|1203182360
**Triangle Count**: |42201 |583793 |806368
**Triangle Rate**: |2637562 |34340764 |50398000
**API Drawcall Count**: |26 |304 |285
**Drawcall Count**: |27 |298 |1242
**Drawcall Rate**: |1687 |17529 |77625
**State Changes Texture Count**:|47 |267 |440
**Pipeline Count**: |28 |135 |65
**Item Opaques**: |13 |406 |293
**Item Translucents**: |3 |114 |73
**Item Lights**: |0 |84 |34
**Timing Opaques**: |158 |1562 |1268
**Timing Translucents**: |36 |140 |156
**Timing Lighting**: |343 |279 |235
**Render Frame**: |1974 |3768 |3116

# Vive stats: 

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |89 |89 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |1357 |5535 |5104
**GPU Buffer Count**: |735 |1881 |1591
**CPU Memory Usage**: |21184512 |84430848 |85901312
**GPU Memory Usage**: |13791232 |55373824 |45903872
**CPU Texture Count**: |57 |287 |344
**GPU Texture Count**: |2296 |2264 |2531
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |426771800 |624643624 |688181808
**GPU Texture Memory Usage**: |101322236 |1319222916 |1077184101
**GPU Virtual Memory Usage**: |469221564|1687122244|1445083429
**Triangle Count**: |116367 |717575 |1877365
**Triangle Rate**: |11636700 |65234090 |170669545
**API Drawcall Count**: |29 |182 |390
**Drawcall Count**: |39 |629 |759
**Drawcall Rate**: |3900 |57181 |69000
**State Changes Texture Count**:|51 |186 |574
**Pipeline Count**: |28 |49 |64
**Item Opaques**: |11 |177 |363
**Item Translucents**: |3 |29 |88
**Item Lights**: |0 |36 |35
**Timing Opaques**: |208 |806 |1362
**Timing Translucents**: |76 |45 |243
**Timing Lighting**: |512 |263 |214
**Render Frame**: |2787 |2687 |3181

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|I did.
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Check.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|didn't hear them on dev-playa but now I hear them on other domains (fire crackling at dev-demo etc. ) , So I guess this is a server side issue
**Test 4**|undefined|?
**Test 5**|Retest the kick function|works
**Test 6**|Switch avatar and make sure it does not crash|No crash
**Test 7**|Test group functions|Works
**Test 8**|Retest the kick function|Still works,, see above.
**Test 9**|Enrure that you can distance grab|works

QA Pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48bab49210c69cff1f9d86a1e13d4e0dc731de3f available at: https://gist.github.com/35e7eda8cdd3ad02e503d7e3e17bb54c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48bab49210c69cff1f9d86a1e13d4e0dc731de3f available at: https://gist.github.com/35e7eda8cdd3ad02e503d7e3e17bb54c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.dmg

**Comment by marko8904** [comment]
this this please

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48bab49210c69cff1f9d86a1e13d4e0dc731de3f available at: https://gist.github.com/35e7eda8cdd3ad02e503d7e3e17bb54c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-48bab49.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c99a330093807f25e85e7204373f191925155c1 available at: https://gist.github.com/35e7eda8cdd3ad02e503d7e3e17bb54c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-6c99a33.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8508-6c99a33.dmg

**Comment by OmegaHeron** [comment]
There's still something odd with zones (using latest build just made)

Starting interface with AV at dev-playa I initially see;

hifi-snap-by-omegaheron-on-2016-08-24_14-21-59

Then I move forward a bit (there's a second zone in dev-playa directly in front of default landing posit) and I see;

hifi-snap-by-omegaheron-on-2016-08-24_14-22-12

Then I back up to exit 2nd zone and I see;

hifi-snap-by-omegaheron-on-2016-08-24_14-22-21

Moving to another domain and returning to dev-playa I continue to see cloudy sky.  I'm not sure if this is a bug or something screwy with zone settings at dev-playa.

Then moving to playa I only see the default no zone image;

hifi-snap-by-omegaheron-on-2016-08-24_14-28-56

Moving to hifi://heron I see what I expect;

hifi-snap-by-omegaheron-on-2016-08-24_14-29-46

Back to playa and waiting to insure all has loaded;

hifi-snap-by-omegaheron-on-2016-08-24_14-30-37

Quit Interface and start again at Playa;

hifi-snap-by-omegaheron-on-2016-08-24_14-31-44

Starting at Playa with DEV build 5303 I see;

hifi-snap-by-omegaheron-on-2016-08-24_14-32-28

With DEV 5303 if I move to dev-playa, I initially see starfield sky - I move into zone as shown above and can tell I'm in via brightness and change of sky.  Back out to landing point and I see cloudy sky again.  So - this is present in current DEV tree and not new to this PR.

**Pull request merged**
