### PR TITLE
WL 21551 - Flocking Fish Aquarium

### PR DESCRIPTION
**Pull request by cain-kilgore**
> replace the basic block with a nice looking model of a fish. 
> And when the script is run, also create a simple translucent walled 'aquarium' that the fish stay inside. 
> use a tablet button to make/delete the acquarium and fish. 
> put the results in the marketplace

Worklist [21551](https://worklist.net/21551)

## Test Plan
1. Run the FlockOfFish.js script from here: [FlockOfFish.js](https://s3-eu-west-1.amazonaws.com/cainkilgore-prod/files/FlockOfFish.js
)
2. Confirm that a "FishTank" Toolbar/Tablet Button gets added
3. Confirm that clicking on it toggles the state off and on and a fishtank appears in front of you.
4. Make sure the fishes spawned in correctly and move around.

Marketplace Item: [here (not available yet)](https://highfidelity.com/marketplace/items/4535b57c-f35a-4d9d-a3ee-1233c457dc8e
)

5e209ad7-8628-4c9e-bf5b-1745e676fbd0

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3749/HighFidelity-Beta-PR11487-9a02f48204ab24b4aa7317749cc6fef51ec5680d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3749/HighFidelity-Beta-PR11487-9a02f48204ab24b4aa7317749cc6fef51ec5680d.exe

**Comment by huffman** [comment]
We should probably move this to hifi-content. Thoughts @misslivirose ?

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Run the FlockOfFish.js script from here: FlockOfFish.js **Check**
Confirm that a "FishTank" Toolbar/Tablet Button gets added **Check**
Confirm that clicking on it toggles the state off and on and a fishtank appears in front of you. **Check**
Make sure the fishes spawned in correctly and move around. **Check**

Solid **Pass**

**Notes: The fish move similarly to as the pic describes, though I feel this is a bit odd looking, it does follow the test plans desc. Another small note is the icon appears to take place at the far left side of the toolbar and at the top of the tablet, pics below:**
image

image

**Comment by PhilipRosedale** [comment]
Fish are moving wrong - compare to the original with the teal blocks.... fish should be aligned with each other and slowly turning, etc.

**Comment by cain-kilgore** [comment]
@PhilipRosedale I'm not sure why they're acting like this - the only property which I changed of the fish entity was the ModelURL.

**Comment by cain-kilgore** [comment]
3f368d8a-3020-4c9e-b043-ffc6673ded11

**Comment by misslivirose** [comment]
@huffman Yeah, I think this is a perfect candidate for hifi-content. There seems to still be an issue having projects auto-fork to that repo, we're looking into it. I believe @themelissabrown is following up.

**Comment by PhilipRosedale** [comment]
@cain-kilgore I have no idea, we must have a bug, but I certainly wouldn't want to put this up - the motion looks terrible.  Perhaps changing the model changes some other aspect we aren't thinking of... are they physical, do they have collisions set?  Does the model align with the direction of motion (is the fish lined with the forward axis)?  It should be easy to figure out.

**Comment by cain-kilgore** [comment]
@PhilipRosedale The fish have no collision box, though the same effect seems to happen even with a collision box.

**Comment by Nex-Pro** [comment]
@PhilipRosedale @cain-kilgore 
Fish model was build with positive X from the nose.

**Comment by Nex-Pro** [comment]
259,240 verts per shoal of tiny fishies.

**Comment by cain-kilgore** [comment]
@Nex-Pro There's a Worklist available to create a Model for this PR now :)

**Comment by Nex-Pro** [comment]
@cain-kilgore Have you tried feeding the fish ?

**Comment by Nex-Pro** [comment]
@cain-kilgore 

97 & 98 
        var birdPositionsCounted = 0;
        var birdVelocitiesCounted = 0;

unused ?

**Comment by cain-kilgore** [comment]
@Nex-Pro Yup - there's a FlockOfBirds aswell which is where I think the Fish script originated from.

**Comment by Nex-Pro** [comment]
Line 68 never gets called.

**Comment by Nex-Pro** [comment]
I think the fish are created with collisions on. Should this be avoided ? Collision mask is 31.

Might be worth adding
collisionless: 1,
 collisionMask: 0,
to the propeties when they are created.

**Comment by cain-kilgore** [comment]
@Nex-Pro: I don't think it matters too much. The Aquarium in theory would have caused more issues than the fishes colliding with each other.

**Comment by cain-kilgore** [comment]
@Nex-Pro How's the model going?

**Comment by themelissabrown** [comment]
https://s3-eu-west-1.amazonaws.com/cainkilgore-prod/files/7f676280-b301-44bf-91a4-6e94075679b8.gif

**Comment by themelissabrown** [comment]
https://s3-eu-west-1.amazonaws.com/cainkilgore-prod/files/ea2a50a4-93bc-4bd5-8771-53c30ffc7a90.mp4

**Comment by cain-kilgore** [comment]
https://github.com/highfidelity/hifi-content/pull/24 - moved to hifi-content.

**Pull request closed without merging**
