### PR TITLE
Fix for avatar eye tracking when looking at mouths.

### PR DESCRIPTION
**Pull request by hyperlogic**
Improve reliability of Head::getMouthPosition()
This would return incorrect values for avatars with a head joint higher than the eyes.
Which was the case for the Priscilla and Matthew avatars.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfc1567eef76717743e2b700f431e024f7f06356 available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20133dae6dc94ceaf4142bb967b52acded214e73 available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0406e9da0503acda4998b5e190a044b1af7a62a available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8f27a6a4e65f20855e1257279a7eac9b473258d available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b763fabbd1a42b2179b2c8105bb5fba2e13bb2c4 available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Comment by hyperlogic** [comment]
gonna re open this with a better more concise PR

**Comment by hifi-gustavo** [comment]
Build console output for commit: 294e3cc47201678a7d57b3192a32cda849f932ae available at: https://gist.github.com/3a5c7cdf402dbdf94baf8a86bf71a060<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7744.dmg

**Pull request closed without merging**
