### PR TITLE
make Script.include(/~/system/libraries/utils.js) work from web again

### PR DESCRIPTION
**Pull request by sethalves**
- make Script.include(/~/system/libraries/utils.js) work from web again

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- create a script that loads from the standard libraries that come with interface using the /~/ shortcut
- host this script on a webserver
- make sure it works
- make sure the script is unable to load things like file:///C:/Users/someone/Desktop/bad.js
- smoke test

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0a5d8b719fe701896529c463540cb90b8acef89 available at: https://gist.github.com/04bf4ff7363a3abbc05ecef7e5122df8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7843.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7843.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68201746aa89f3f985182aaa80ebb21ee64c5f27 available at: https://gist.github.com/04bf4ff7363a3abbc05ecef7e5122df8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7843.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7843.dmg

**Comment by imgntn** [comment]
works for me win10

[05/09 20:36:53] [DEBUG] Done downloading script at: "http://hifi-content.s3.amazonaws.com/james/bad2.js"
[05/09 20:36:53] [DEBUG] Logging activity "loaded_script"
[05/09 20:36:53] [DEBUG] Loading script at  QUrl("file:///C:/Program Files/High Fidelity/scripts/system/libraries/utils.js")
[05/09 20:36:53] [DEBUG] ScriptEngine::include -- skipping "/~/../Users/james_000/Desktop/naughty.js" -- outside of standard libraries

**Pull request merged**
