### PR TITLE
Auto tester

### PR DESCRIPTION
**Pull request by NissimHadar**
First version.
A full description can be found here: https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/79069240/Automated+Testing+Tool

To test:  compile and run tools/auto-tester.
Expected result: 
image

Press Close to exit.

### CODE REVIEW

**Comment by NissimHadar** [comment]
Please build me

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4928/HighFidelity-Beta-PR11805-a2925518c251176220896896282163714d38bf95.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4928/HighFidelity-Beta-PR11805-a2925518c251176220896896282163714d38bf95.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5036/HighFidelity-Beta-PR11805-7b2fed6db2735fbe05dbea0fabbb50389d982ede.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5084/HighFidelity-Beta-PR11805-861c33d5a9fd23165f603a61c59dd68d10e57a5d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5084/HighFidelity-Beta-PR11805-861c33d5a9fd23165f603a61c59dd68d10e57a5d.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5094/HighFidelity-Beta-PR11805-fef5d95e943e493bd95fef9395e1b5ac3b7e00d9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5094/HighFidelity-Beta-PR11805-fef5d95e943e493bd95fef9395e1b5ac3b7e00d9.dmg

**Pull request merged**
