### PR TITLE
fix step translate actions

### PR DESCRIPTION
**Pull request by sethalves**
- fix step translate actions

I don't believe anyone is currently using these input actions, but in case someone does, let's fix them.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21925/HighFidelity-Beta-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21925/HighFidelity-Beta-Interface-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21925/HighFidelity-Beta-PR16348-1f8a7cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21925/HighFidelity-Quest-Beta-PR16348-1f8a7cf.apk)

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21929/HighFidelity-Beta-PR16348-1f8a7cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21929/HighFidelity-Quest-Beta-PR16348-1f8a7cf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21929/HighFidelity-Beta-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21929/HighFidelity-Beta-Interface-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21929/HighFidelity-Beta-PR16348-1f8a7cf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21929/HighFidelity-Beta-Interface-PR16348-1f8a7cf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21933/HighFidelity-Beta-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21933/HighFidelity-Beta-Interface-PR16348-1f8a7cf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21933/HighFidelity-Beta-PR16348-1f8a7cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21933/HighFidelity-Quest-Beta-PR16348-1f8a7cf.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21933/HighFidelity-Beta-PR16348-1f8a7cf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21933/HighFidelity-Beta-Interface-PR16348-1f8a7cf.exe

**Pull request merged**
