### PR TITLE
FIxing the dark ambient lighting on scattering surface

### PR DESCRIPTION
**Pull request by samcake**
THis pr address a problem found in RC63 QA
it s the same change (almost) as pr #12273 

THe scattering surface's ambient diffuse lighting was too dark because it was divided by PI.
it s not the case for non scattering surface so you would see that difference of intensity at the border.
this is now fixed.

I also took the liberty to apply the standard ambient specular to scattering surfaces because i think it looks better and is more PBR anyway.

### TEST PLAN
In master the bug https://highfidelity.manuscript.com/f/cases/11802/Photo-Real-Female-Avatar-has-hair-seaming-issues is visisble,
image

Not anymore with this pr

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6661/app_12274_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6661/HighFidelity-Beta-PR12274-221475d7d9097b8c097656e57f4f5d1b567c568b.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6668/app_12274_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6668/HighFidelity-Beta-PR12274-221475d7d9097b8c097656e57f4f5d1b567c568b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6668/HighFidelity-Beta-PR12274-221475d7d9097b8c097656e57f4f5d1b567c568b.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed testing for PR#12274. FAILED. Interface crashes on launch. This occurs only on the Mac. 
Master crashes
Stable does not crash
RC63 doesn't crash
RC63 PR (12273) doesn't crash
Master PR (12274) crashes
Please see attached bug for further reference: https://highfidelity.fogbugz.com/f/cases/11853/PR12274-Interface-crashes-when-attempting-to-launch-on-Mac-only

**Comment by conklin94122** [comment]
@hyperlogic FYI

**Comment by samcake** [comment]
wtf

**Comment by conklin94122** [comment]
@samcake Conflicts. Please resolve and kick off a fresh build for testing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6770/app_12274_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6770/HighFidelity-Beta-PR12274-582ef2a8a2788329f36e4a8bcb914d5049b47d7b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6770/HighFidelity-Beta-PR12274-582ef2a8a2788329f36e4a8bcb914d5049b47d7b.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed testing. PASSED!

**Pull request merged**
