### PR TITLE
cancel effects of --replaceAvatarURL when avatar is changed with preference dialog

### PR DESCRIPTION
**Pull request by sethalves**
- setting avatar with dialog will now cancel effects of --replaceAvatarURL command-line flag

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run interface with --replaceAvatarURL http://mpassets.highfidelity.com/f3fbb9f4-e159-49ed-ac32-03af9056b17e-v1/matthew.fst
- observe that you have the matthew avatar
- use Menu --> Settings --> Avatar to change your avatar to http://mpassets.highfidelity.com/67d7c7aa-c300-4d03-85f4-86480130eaa5-v1/F_StarCrew.fst
- observe that you are the star-trek lady
- go to a new domain
- make sure you still are the star-trek lady

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2426/HighFidelity-Beta-PR11168-ff83a8158bee3be1e1cd9b0054dfb0459de472b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2426/HighFidelity-Beta-PR11168-ff83a8158bee3be1e1cd9b0054dfb0459de472b7.exe

**Comment by cain-kilgore** [comment]
Testing now.

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
-------- | --------
run interface with --replaceAvatarURL http://mpassets.highfidelity.com/f3fbb9f4-e159-49ed-ac32-03af9056b17e-v1/matthew.fst | Pass
observe that you have the matthew avatar | Fail
use Menu --> Settings --> Avatar to change your avatar to http://mpassets.highfidelity.com/67d7c7aa-c300-4d03-85f4-86480130eaa5-v1/F_StarCrew.fst | Pass
observe that you are the star-trek lady | Pass
go to a new domain | Pass
make sure you still are the star-trek lady | Pass

I tried running the interface multiple times from the command line with the `--replaceAvatarURL` argument, which wasn't working.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2429/HighFidelity-Beta-PR11168-1d07bc3b4e854d925a67abfb0e93df3f2997aa58.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2429/HighFidelity-Beta-PR11168-1d07bc3b4e854d925a67abfb0e93df3f2997aa58.exe

**Comment by cain-kilgore** [comment]
Re-testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
------- | --------
run interface with --replaceAvatarURL http://mpassets.highfidelity.com/f3fbb9f4-e159-49ed-ac32-03af9056b17e-v1/matthew.fst | Pass
observe that you have the matthew avatar | Pass
use Menu --> Settings --> Avatar to change your avatar to http://mpassets.highfidelity.com/67d7c7aa-c300-4d03-85f4-86480130eaa5-v1/F_StarCrew.fst | Pass
observe that you are the star-trek lady | Pass
go to a new domain | Pass
make sure you still are the star-trek lady | Pass

All good - yay!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
