### PR TITLE
Fix audio artifacts by flushing decoder in silence

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4af74bc348a27308d5520d920ed149760c7c0d07 available at: https://gist.github.com/ddff22f48a65137de6caa33ef6f927ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-4af74bc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-4af74bc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e58cffa46c0351ed466e04d254e94eb30ae66a6 available at: https://gist.github.com/ddff22f48a65137de6caa33ef6f927ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-4e58cff.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-4e58cff.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 539b1b259389bc37045cf4f73a4704cb3e3fc7f5 available at: https://gist.github.com/ddff22f48a65137de6caa33ef6f927ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.dmg

**Comment by ZappoMan** [comment]
we have a better fix

**Comment by zzmp** [comment]
This is an unrelated issue from #9842 - reopening - it still needs modification before it can be rereviewed.

**Comment by zzmp** [comment]
oops...meant to reopen #9830...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 539b1b259389bc37045cf4f73a4704cb3e3fc7f5 available at: https://gist.github.com/ddff22f48a65137de6caa33ef6f927ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 539b1b259389bc37045cf4f73a4704cb3e3fc7f5 available at: https://gist.github.com/ddff22f48a65137de6caa33ef6f927ec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9838-539b1b2.dmg

**Pull request closed without merging**
