### PR TITLE
Avoid deadlock on 10k mesh fbx

### PR DESCRIPTION
**Pull request by sethalves**
- avoid interface hanging on "static-mesh" models with a large number of meshes

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- import
```javascript
        {
            "dimensions": {
                "x": 13.265490531921387,
                "y": 6.6746721267700195,
                "z": 20.865068435668945
            },
            "modelURL": "https://7mv1ptvrbi5wq61rlfll.g0v.sandcats.io/coart02/coart02.fbx",
            "shapeType": "static-mesh",
            "type": "Model"
        }
```
- observe that interface doesn't deadlock

**Comment by hifi-gustavo** [comment]
Build console output for commit: aaa78d108b380726fe374a782d30f7ffdb38e284 available at: https://gist.github.com/1ed679512cb46775d3c44f8738e97ff7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9994-aaa78d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9994-aaa78d1.dmg

**Comment by OmegaHeron** [comment]
@seth - clarify what you mean by deadlock, please.  Deadlock as in Interface bugsplats and terminates or absolute absence of deadlock messages in log?  I routinely see deadlock messages in Interface log -- thus my question.

**Comment by OmegaHeron** [comment]
@sethalves - clarify what you mean by deadlock, please.  Deadlock as in Interface bugsplats and terminates or absolute absence of deadlock messages in log?  I routinely see deadlock messages in Interface log -- thus my question.

**Comment by sethalves** [comment]
For me, interface didn't actually deadlock, but a loop took too long to run and the deadlock detector decided that the program had stopped.  The deadlock messages in the interface log are generally normal.  You're looking for: interface keeps working.

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Master (6195) - Imported, waited for model to load - when it began placing in scene Interface went non-responsive (as indicated by windows warning in title bar) and spinning cursor.  After some time model appeared in scene.  Interface didn't crash or trigger deadlock detector, though it likely should have considering intervals Interface was totally unresponsive.

PR - Imported, waited and model eventually appeared - Interface didn't go unresponsive.

Also tested placing normal "sane" models and general smoke test.

**Pull request merged**
