### PR TITLE
Quat JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Updates the JavaScript API JSDoc for:
- Quat

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no code changes other than those already covered in preceding JSDdoc PR, https://github.com/highfidelity/hifi/pull/11791.

Do not merge this PR until after the preceding JSDoc PR.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5199/HighFidelity-Beta-PR11884-07a7cb412a360c56403bd7b05d954eefe97f4aa2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5199/HighFidelity-Beta-PR11884-07a7cb412a360c56403bd7b05d954eefe97f4aa2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5269/HighFidelity-Beta-PR11884-a01d118c57e32ee6891a180fb22933784f2d5f25.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5269/HighFidelity-Beta-PR11884-a01d118c57e32ee6891a180fb22933784f2d5f25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5273/HighFidelity-Beta-PR11884-f5b12a0a9d3febba6dc480c080c0d7753b28eb3e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5273/HighFidelity-Beta-PR11884-f5b12a0a9d3febba6dc480c080c0d7753b28eb3e.dmg

**Pull request merged**
