### PR TITLE
Adding trace profiling feature Script

### PR DESCRIPTION
**Pull request by samcake**
This PR adds the trace profiling feature to the js api through the new 2 calls:
Script.beginProfileRange
Script.endProfileRange

These calls are no ops when using Interface normally.
When running interface in test mode, and if tracing is enabled then these will trigger the corresponding events in the trace so the duration of the begin to end call should show up in the trace.

As usual the trace is generated (typically in Documents/traces) and can be explored with Chrome using the tracing view of chrome.

## TEST PLAN
Nothing changes at all in normal mode

only record the events in a trace.
You need to use a script that actually  begin end ranges while recording the trace.

Here is a modified version of HandControllerGrab.js containing some profiling:
https://gist.githubusercontent.com/samcake/d46f49d6d8e5e55d74d0249bb344f90f/raw/408fb97d47308489a0a5fff58f9a9d852b077c6d/handControllerGrab.js

Download this script and replace the "official" version installed along the Interface exe in the sub folder: scripts/system/controllers

After that, download from the hifi_tests repository the folder "benchmarks":
https://github.com/highfidelity/hifi_tests/tree/master/benchmarks

From this folder, in command line, run the interface build from this pr with the following command arguments (for example here with the pr installed in the default path):
"C:\Program Files\High Fidelity - PR10795\interface.exe" --testScript manual.js

This should start interface in test mode in a no domain. 
a new button should show in the toolbar (or the tablet in hmd mode)
Go to a valid domain and after it s loaded, click the "capture trace" button
acknowledge the next 2 dialog boxes. the button turns white actually capturing a trace.
 and start moving around the mouse or the hand controller. eventually grabbing objects
after 20 seconds the button should go back to normal.

You can turn off interface,
in your document folder, there should be a traces subfolder
and there a brand new trace captured.

This file can be explored from chrome by creating a new tab with the address: chrome://tracing
you can drop the file there and normally see a timeline and various tracks showing different "threads" of activity captured in the trace.
IN the one called controller.js, there should be some new ranges corresponding to the HandControllerGrab.js modified version....
Ping me when this happen, or share the trace here so we can validate that the profiling worked as expected.
Thanks

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1041/HighFidelity-Beta-PR10795-bda52c33e615e6be9210d041e4196854d5fef7d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1041/HighFidelity-Beta-PR10795-bda52c33e615e6be9210d041e4196854d5fef7d0.exe

**Comment by Atlante45** [comment]
Be aware that `chrome://tracing` does not handle trace files bigger that ~15MB.
This is probably gonna bloat the trace file quickly and make it unparsable.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1047/HighFidelity-Beta-PR10795-c24e254257deee74bb7e0da65c2eeff367b2e1d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1047/HighFidelity-Beta-PR10795-c24e254257deee74bb7e0da65c2eeff367b2e1d9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1073/HighFidelity-Beta-PR10795-c0e8b6c8bcf617b7ef1b64360e6c08085a312811.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1073/HighFidelity-Beta-PR10795-c0e8b6c8bcf617b7ef1b64360e6c08085a312811.exe

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1095/HighFidelity-Beta-PR10795-619b357ad0533e9ace37198355206f6250160892.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1095/HighFidelity-Beta-PR10795-619b357ad0533e9ace37198355206f6250160892.dmg

**Comment by CainFoool** [comment]
# Test Passed (smoke)

Game appears to run okay, nothing appears to be broken other than the toolbar though that's been fixed in another PR. Teleported around multiple domains, restarted multiple times, tested some scripting - all working well.

**Comment by Nex-Pro** [comment]
@Sam I will re-test this following our discussion.

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1123/HighFidelity-Beta-PR10795-1fbaac12ecb4ee339d7ce8aaf40d86e2f6e2556d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1123/HighFidelity-Beta-PR10795-1fbaac12ecb4ee339d7ce8aaf40d86e2f6e2556d.exe

**Comment by Nex-Pro** [comment]
@samcake 
 Here's the trace info. All looks ok as far as implementation.

[trace-20170627_1546TestForSam.json.gz](https://github.com/highfidelity/hifi/files/1105709/trace-20170627_1546TestForSam.json.gz)
traceoutputforsam-10795

@CainFoool  What's your current score ?

**Comment by CainFoool** [comment]
@Nex-Pro Sam had asked me at the time just to check everything was still working okay. I didn't do any tracing.

**Comment by Nex-Pro** [comment]
@CainFoool , yeah but what's your score ?

**Pull request merged**
