### PR TITLE
Improve Create properties for particles + materials

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.fogbugz.com/f/cases/20137/Particle-entity-properties-page-has-some-fields-hidden-or-off-screen
https://highfidelity.fogbugz.com/f/cases/20141/Material-entity-properties-page-has-some-field-labels-obscured-and-an-incorrect-tooltip

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15725/HighFidelity-Beta-PR14544-3160339.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15725/HighFidelity-Beta-PR14544-3160339.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15725/HighFidelity-Beta-Interface-PR14544-3160339.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass

Tooltips appear, Particle properties appear, and user can still change particle colors

**Pull request merged**
