### PR TITLE
Glow line replacement without geometry shader

### PR DESCRIPTION
**Pull request by jherico**
This re-implements the glow line effect without using a geometry shader, which broken when the stereo amplification code changed.  This uses a vertex shader to create a ribbon given two points in space, using the eye space locations of the points to ensure that the flat surface of the ribbon is always facing the camera.

Additionally, I've modified the code in the HmdDisplayPlugin base class to reproduce the same effect without relying on the GeometryCache class, which is not thread safe and should not be used on the rendering thread.  

## Testing

Lasers should once again glow, as in the current steam build.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f8e38927dc2f1e4d60dd3868d028c43b6d32603b available at: https://gist.github.com/2cc60f679535e291c4c23b51c6813e9d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-f8e3892.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-f8e3892.dmg

**Comment by ZappoMan** [comment]
Warnings on mac and unix

**Comment by hifi-gustavo** [comment]
Build console output for commit: d21570b694c4026a44f06e9f79704c62d858383f available at: https://gist.github.com/2cc60f679535e291c4c23b51c6813e9d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-d21570b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-d21570b.dmg

**Comment by zfox23** [comment]
Two things I noticed:
1. The laser still isn't appearing when I'm using it over 2D HUD elements. I'm going to try clearing my settings to see if that does anything.
2. I was holding the laser trigger halfway down and hovering over the top HUD bar when Interface suddenly crashed. I'm not sure if this is related to this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 362976645b764b2516d905fcaf513748c19823d8 available at: https://gist.github.com/2cc60f679535e291c4c23b51c6813e9d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-3629766.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9092-3629766.dmg

**Comment by Nex-Pro** [comment]
Testing this on Win10 with Vive

**Comment by Nex-Pro** [comment]
### PASS 

Looks fine. Near and far, red and blue, left and right controllers all ok.

**Pull request merged**
