### PR TITLE
CR for Job #20216 - Integrate the Intel Realsense camera SDK

### PR DESCRIPTION
**Pull request by thoys**
Code Review for Job #20216 - Workitem available at https://www.worklist.net/20216

### CODE REVIEW

**Comment by thoys** [comment]
:+1:

**Comment by murillodigital** [comment]
@thoys @cozza13 RSSDK is in the build box, found and passed. Need to test a release with this before merging. If any further review on the code needs to happen please go ahead.

**Comment by murillodigital** [comment]
ok @thoys @cozza13 just tried a "releaseable" version and I didnt crash, I think we can merge this and test, not sure if I could do any further testing without one of the realsense cameras.

**Comment by thoys** [comment]
thanks @murillodigital , you can test the recorded rssdk file. Which can be found here: https://drive.google.com/file/d/0B76YuDlpp2i8TnhwWElveHVTTXc/view

**Comment by thoys** [comment]
You can find the load rssdk file option in the developer menu under Hands IIRC

**Comment by ZappoMan** [comment]
@thoys - Can you pull from upstream and merge your branch with the latest changes? Thanks.

**Comment by thoys** [comment]
There you go!

**Comment by ZappoMan** [comment]
@thoys -- /Users/jenkins/Jenkins/workspace/hifi-pull-request-mac/interface/src/devices/RealSense.cpp:244:30: error: use of undeclared identifier 'QFileDialog'
    QString fileNameString = QFileDialog::getOpenFileName(Application::getInstance()->getWindow(), tr("Open RSSDK clip"),

**Comment by thoys** [comment]
@ZappoMan - that did the trick

**Pull request merged**
