### PR TITLE
add control button mapping for controller API

### PR DESCRIPTION
**Pull request by druiz17**
add control button mapping for controller API ```Contoller.Hardware.Keyboard.Control```

Ticket - https://highfidelity.manuscript.com/f/cases/12299

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1.
- Run the script below, a sphere should appear in front of you
- press Control button on your keyboard and the sphere should change colors

2.
- Take a snapshot with CTRL-S. You shouldn't start moving backwards.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7155/app_12390_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7155/HighFidelity-Beta-PR12390-ddcee05b14637a342dd286c93482fba289300a0f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7155/HighFidelity-Beta-PR12390-ddcee05b14637a342dd286c93482fba289300a0f.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12390. PASSED.

**Pull request merged**
