### PR TITLE
Remove Developer > Network > Bandwith Details dialog

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing: Developer > Network > Bandwidth details menu option is not present in desktop or tablet.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 51739f2f99bbbe4a1f8a4f9ed6bb538a85fff19e available at: https://gist.github.com/a54948715f20f69bf9b3c47afb260a9a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9818-51739f2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9818-51739f2.dmg

**Comment by nbq** [comment]
testing

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Checked that Developer > Network > Bandwidth Details is not present in tablet or desktop menu

**QA PASS**

**Pull request merged**
