### PR TITLE
MS20825: Login Screen Aspect/Crop with resizing

### PR DESCRIPTION
**Pull request by wayne-chen**
MS#[20825](https://highfidelity.manuscript.com/f/cases/20825/Add-cropping-and-scaling-to-the-background-image-on-the-login-screen)

# TEST PLAN
- Launch interface in desktop mode (ensure you are not logged in)
- See the login dialog pop up
- resize the window
- the background image of the login dialog should crop and the aspect ratio should be preserved

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16731/HighFidelity-Beta-PR14772-4880c70.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16731/HighFidelity-Beta-PR14772-4880c70.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16731/HighFidelity-Beta-Interface-PR14772-4880c70.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16731/HighFidelity-Beta-PR14772-4880c70.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16731/HighFidelity-Beta-Interface-PR14772-4880c70.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlilaseguinolaza** [comment]
PR PASS: Background image of the login dialog  crops and maintains aspect ratio when resizing the window.

**Comment by qlilaseguinolaza** [comment]
PR14772 PASS: Background image of the login dialog  crops and maintains aspect ratio when resizing the window.

**Pull request merged**
