### PR TITLE
New Action (Offer)

### PR DESCRIPTION
**Pull request by luiscuenca**
Added an "Offer Action" that allows users to offer assets to other users.
The asset shows attached to the hand for now ( should hold methods be used?? ).
The action is trigger with the "F" key.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by cozza13** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2639/HighFidelity-Beta-PR11222-28527a1c5911dbe47972b7a1d598aefbbdbb5483.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2639/HighFidelity-Beta-PR11222-28527a1c5911dbe47972b7a1d598aefbbdbb5483.exe

**Pull request closed without merging**
