### PR TITLE
Updated Windows build guide's markdown

### PR DESCRIPTION
**Pull request by seefo**
Updated the Windows build guide's markdown to be more readable and consistent.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/448/HighFidelity-Beta-PR10627-40823bf5827526f6aae65bd89718c624bf63a724.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/448/HighFidelity-Beta-PR10627-40823bf5827526f6aae65bd89718c624bf63a724.dmg

**Comment by YuppyPlays** [comment]
Hi @seefo 
Is there a test plan available for this?

**Comment by seefo** [comment]
@YuppyPlays There isn't, I apologize about that.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/458/HighFidelity-Beta-PR10627-aa13812e3fcb48453c78955b91ed07650e1043d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/458/HighFidelity-Beta-PR10627-aa13812e3fcb48453c78955b91ed07650e1043d3.exe

**Pull request merged**
