### PR TITLE
updating emote app icon

### PR DESCRIPTION
**Pull request by alexiamandeville**
image

This PR replaces the emote app icon with a new one. 

It also adds an active icon, so when a user clicks on the emote app button, the icon turns black.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11821/HighFidelity-Beta-PR13746-eda80fb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11821/HighFidelity-Beta-PR13746-eda80fb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11821/HighFidelity-Beta-Interface-PR13746-eda80fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11821/HighFidelity-Beta-PR13746-eda80fb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11821/HighFidelity-Beta-Interface-PR13746-eda80fb.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11838/HighFidelity-Beta-PR13746-c583223.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11838/HighFidelity-Beta-PR13746-c583223.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11838/HighFidelity-Beta-Interface-PR13746-c583223.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11838/HighFidelity-Beta-PR13746-c583223.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11838/HighFidelity-Beta-Interface-PR13746-c583223.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11845/HighFidelity-Beta-PR13746-b3426f6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11845/HighFidelity-Beta-PR13746-b3426f6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11845/HighFidelity-Beta-Interface-PR13746-b3426f6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11845/HighFidelity-Beta-PR13746-b3426f6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11845/HighFidelity-Beta-Interface-PR13746-b3426f6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12004/HighFidelity-Beta-PR13746-38973f0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12004/HighFidelity-Beta-Interface-PR13746-38973f0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12004/HighFidelity-Beta-PR13746-38973f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12004/HighFidelity-Beta-Interface-PR13746-38973f0.dmg

**Comment by alexiamandeville** [comment]
Test Plan:

1. Open HiFi
2. Make sure emote app icon matches the one from the description.
3. Click on the emote app button.
4. Make sure the icon turns black when the app is in an active state.
5. Click emote app button again, make sure the icon turns white in an inactive state.

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12102/HighFidelity-Beta-PR13746-38973f0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12102/HighFidelity-Beta-PR13746-38973f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12102/HighFidelity-Beta-Interface-PR13746-38973f0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12102/HighFidelity-Beta-PR13746-38973f0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12102/HighFidelity-Beta-Interface-PR13746-38973f0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
New icon appears and active state works as intended.

**Pull request merged**
