### PR TITLE
manually rename Raleway font with incorrect casing after install

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by ZappoMan** [comment]
:+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1457f457d36e8e7d9181a872fb32b385e53625d0 available at: https://gist.github.com/54aca66463029e74f042<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.dmg

**Comment by OmegaHeron** [comment]
Needs to be brought up to current main code? - 100% crash on open.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bdc2ac73f6439971f73ed66eda171d7ff1699bb7 available at: https://gist.github.com/54aca66463029e74f042<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.dmg

**Comment by OmegaHeron** [comment]
100% Crash on open persists with Windows and last build.  It looks like crash fixed by 7293.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c45ed038cb54542117f2976aad8262f5e68c0da available at: https://gist.github.com/54aca66463029e74f042<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.dmg

**Comment by birarda** [comment]
False OS X fail - tested this on Windows and it does the right thing.

You'll need to install this build, then manually rename `C:\Program Files\High Fidelity\resources\qml\styles-uit\RalewaySemiBold.qml` to `C:\Program Files\High Fidelity\resources\qml\styles-uit\RalewaySemibold.qml`.

Then, re-install and confirm the file is `C:\Program Files\High Fidelity\resources\qml\styles-uit\RalewaySemiBold.qml` and not `C:\Program Files\High Fidelity\resources\qml\styles-uit\RalewaySemibold.qml`

**Comment by birarda** [comment]
test this please

**Comment by OmegaHeron** [comment]
Tested Windows 7 - manually changed name - reinstalled and see correct name.  All functions otherwise work as expected.  QA Pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c45ed038cb54542117f2976aad8262f5e68c0da available at: https://gist.github.com/54aca66463029e74f042<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c45ed038cb54542117f2976aad8262f5e68c0da available at: https://gist.github.com/54aca66463029e74f042<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7295.dmg

**Pull request merged**
