### PR TITLE
Change release type of PR builds from debug to release

### PR DESCRIPTION
**Pull request by gcalero**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15947/HighFidelity-Beta-PR14579-6094381.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15947/HighFidelity-Beta-Interface-PR14579-6094381.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15947/HighFidelity-Beta-PR14579-6094381.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15947/HighFidelity-Beta-Interface-PR14579-6094381.exe

**Comment by gcalero** [comment]
Closing this PR since now there is a parameter called ANDROID_BUILD_TARGET. Check android/containerized_build.sh

**Pull request closed without merging**
