### PR TITLE
Fix 'Go Home' not working on OSX

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47d0b8f28fff58bd802940415a442cceb7a4549c available at: https://gist.github.com/f8754f0ab9e3d1494534cf35c993c548<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7729.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7729.dmg

**Comment by huffman** [comment]
To test:

1. Confirm that the Sandbox "Go Home" menu item correctly opens interface.

**Comment by huffman** [comment]
https://app.asana.com/0/26224634468389/114651040502234

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7729
**Testing Architecture:** 64-bit MacBook Pro
**Testing OS:** OS X El Capitan
**Testing Locations:** music
**Additional Test Results Requested:** Successful test.  Confirmed that the Sandbox "Go Home" menu item correctly opens interface.  Screen shot enclosed.
**Successful Logout/Crash:** Successful logout.
screen shot 2016-04-21 at 2 28 12 pm

**Pull request merged**
