### PR TITLE
Fix MS20215: Fix incorrect display of unavailable items on Marketplace main page

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS20215](https://highfidelity.fogbugz.com/f/cases/20215/Sold-out-Marketplace-item-allows-user-to-click-BUY-and-then-Confirm-purchase-then-get-Purchase-Failed-message).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15837/HighFidelity-Beta-PR14557-ed99da2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15837/HighFidelity-Beta-PR14557-ed99da2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15837/HighFidelity-Beta-Interface-PR14557-ed99da2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15837/HighFidelity-Beta-PR14557-ed99da2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15837/HighFidelity-Beta-Interface-PR14557-ed99da2.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Pull request merged**
