### PR TITLE
Improve address bar and edit.js entity properties list.

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
Add headers to break up logical sections, and reorder/relabel a few
properties.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1f6dd3b3bba7b32870e780f15c9902e5d3b8fbe available at: https://gist.github.com/7f87fe57f9d12dddc619<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f2e38b20b2400f9e4211912795bb09f27ef8101 available at: https://gist.github.com/7f87fe57f9d12dddc619<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 05b668484c94c3780ae30916f43d644023192777 available at: https://gist.github.com/7f87fe57f9d12dddc619<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5188.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5188.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c77fd369bc7cb5ce9bf3900a14cf5ba88e4ab4d available at: https://gist.github.com/7f87fe57f9d12dddc619<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5188.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5188.dmg

**Pull request merged**
