### PR TITLE
tablet-ui: Fix for keyboard focus

### PR DESCRIPTION
**Pull request by hyperlogic**
Don't allow clicks on non-web entities from stealing focus away from web overlays.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA test plan:
   * Bring up the tablet
   * press the marketplace button
   * press the search field to give it focus.
   * verify that you can use the hardware keyboard (not the keyboard tray on the tablet) to enter text into the search field.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca79397ee8335e0a140de5c1e851a9a0a7178781 available at: https://gist.github.com/dd7171ee6b3e13d3a5601f81df0f2693<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-ca79397.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-ca79397.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9be6fe2192def4a995c971878a199fb96ee732c2 available at: https://gist.github.com/dd7171ee6b3e13d3a5601f81df0f2693<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-9be6fe2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-9be6fe2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2760065ee160c27214809bebda650e4c6fe18cae available at: https://gist.github.com/dd7171ee6b3e13d3a5601f81df0f2693<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-2760065.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9579-2760065.dmg

**Comment by nbq** [comment]
Will test this

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Brought up tablet
* Pressed marketplace button
* Clicked in the search field to give it focus
* In desktop mode I searched for `gnome` which worked to enter text into the field
* the proper responses came up in the results

**PASS**

**Pull request merged**
