### PR TITLE
added dart scripts

### PR DESCRIPTION
**Pull request by MrRoboman**
Worklist
https://worklist.net/21342

Test Plan:
Rez darts by running createDart.js
Five blue darts on a small orange platform appear in front of avatar.

Use hand controllers to grab darts and throw.
They stick in static objects.
They collide with but do not stick to dynamic objects.
They make a sound when they collide. 
They only make a sound once after being released.

Far grab a dart that has been thrown
Should have normal far grab behavior.

Platform should disappear after one minute.
Darts disappear after 300 seconds.

I asked Wade Watts to host the sound effect. Should be hosted by the time this is tested.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1894/HighFidelity-Beta-PR11034-507368726f21561af92fd917c9938a4a8fb5a868.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1894/HighFidelity-Beta-PR11034-507368726f21561af92fd917c9938a4a8fb5a868.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing Complete:

Rez darts by running createDart.js **Fail, Cannot findCreateDart.js??**
Five blue darts on a small orange platform appear in front of avatar.

Use hand controllers to grab darts and throw.
They stick in static objects.
They collide with but do not stick to dynamic objects.
They make a sound when they collide.
They only make a sound once after being released.

Far grab a dart that has been thrown
Should have normal far grab behavior.

Platform should disappear after one minute.
Darts disappear after 300 seconds.


Notes: Cannot find the createDart.js script?

**Comment by MrRoboman** [comment]
@YuppyPlays 
unpublishedScripts/marketplace/dart/createDart.js

**Comment by YuppyPlays** [comment]
@MrRoboman 
apologies I may be doing something wrong here, I can't find that it any folders for the game (appdata/local, appdata/roaming, program files <pr build> etc)
Can't see it inside running scripts hierarchy of scripts either.

**Comment by MrRoboman** [comment]
@YuppyPlays 
you can test it straight off github by going to files changed tab and clicking view and then raw on the file you want to run.

https://raw.githubusercontent.com/MrRoboman/hifi/507368726f21561af92fd917c9938a4a8fb5a868/unpublishedScripts/marketplace/dart/createDart.js

Hit ctrl+j in interface to bring up Scripts Running and click run from URL and punch in the above.

**Comment by YuppyPlays** [comment]
Someone else has added their name to test so I will have to forfeit this for now.

Let me know if I'm needed for anything else.

**Comment by MrRoboman** [comment]
Sounds good.

**Comment by hifiwade** [comment]
re testing

**Comment by hifiwade** [comment]
Everything checks out except, I was not able to find the script in interface, I did run the script via URL from the raw git to test the darts.

**Comment by hifiwade** [comment]
Pass

**Pull request merged**
