### PR TITLE
drop avatar data rate to 45hz & bump default per client bandwidth from mixer

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- run this client against any server, and notice that in the expanded stats you will send ~45hz or 1/2 your simulation rate in packets to the avatar mixer.
- also notice that running this version of the sandbox will result in lower inbound pps and bit rate from the avatar mixer

**Comment by OmegaHeron** [comment]
I'll be giving this a look once built

**Comment by ZappoMan** [comment]
@OmegaHeron - made another tweak

**Comment by hifi-gustavo** [comment]
Build console output for commit: 92632e72b6ef8a8b4eb96079d0258c06161666ef available at: https://gist.github.com/12298a205aa31ecf41a240bcf4da8f40<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9205-92632e7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9205-92632e7.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 (Against Linux stack running master revision code 5797)

Interface 5797
AV Mixer In ~18Kb/s 65 pps
Desktop mode out ~200Kb/s 60 pps
DK2 HMD ~160kb/s 39pps

This PR
AV Mixer In ~18kb/s 65 pps
Desktop mode out ~125 kb/s 31 pps 30hz
DK2 HMD out ~170 kb/s 39 pps 37.5hz

Now - running this against this PR sandbox (all on win 10) I see;
AV Mixer In ~44 kb/s 34pps
Out same(ish) as above - as in very close to same but !exactly same.  Within variance seen run to run though.

So -- this works as expected.  My sim rate = either 60 or 75 giving correct values for seen values.

With vsync unlocked and sim rates nearing 300 I see hard limit at 45 pps/45 hz in master it pushes up to 61.  So - again - this works.

I don't have any fancy hand controls etc etc, but, I did watch myself from second computer while moving my HMD around and didn't see any difference in movement shown this PR vs master.

**Comment by ZappoMan** [comment]
That's a QA Pass - @OmegaHeron ! thanks!

**Pull request merged**
