### PR TITLE
Bump avatar mixer packet version

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Ordering of nodes changed in https://github.com/highfidelity/hifi/pull/12314

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6840/app_12320_PR.apk

**Comment by sethalves** [comment]
to test:
- run the test from #12314

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6840/HighFidelity-Beta-PR12320-f46362906dfe344ab967ffcfa85129e0a004d565.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6840/HighFidelity-Beta-PR12320-f46362906dfe344ab967ffcfa85129e0a004d565.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing. PASSED.

**Comment by conklin94122** [comment]
@sethalves Fastest PR label in the west!

**Pull request merged**
