### PR TITLE
DEV-653 - give warning not to change address for cloud domains

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21673/HighFidelity-Beta-PR16284-04f13cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21673/HighFidelity-Quest-Beta-PR16284-04f13cd.apk)

**Comment by roxanneskelly** [comment]
build this please

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21698/HighFidelity-Beta-PR16284-04f13cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21698/HighFidelity-Quest-Beta-PR16284-04f13cd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21698/HighFidelity-Beta-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21698/HighFidelity-Beta-Interface-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21703/HighFidelity-Beta-PR16284-04f13cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21703/HighFidelity-Quest-Beta-PR16284-04f13cd.apk)

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21719/HighFidelity-Beta-PR16284-04f13cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21719/HighFidelity-Quest-Beta-PR16284-04f13cd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21719/HighFidelity-Beta-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21719/HighFidelity-Beta-Interface-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21719/HighFidelity-Beta-PR16284-04f13cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21719/HighFidelity-Beta-Interface-PR16284-04f13cd.exe

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21720/HighFidelity-Beta-PR16284-04f13cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21720/HighFidelity-Quest-Beta-PR16284-04f13cd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21720/HighFidelity-Beta-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21720/HighFidelity-Beta-Interface-PR16284-04f13cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21720/HighFidelity-Beta-PR16284-04f13cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21720/HighFidelity-Beta-Interface-PR16284-04f13cd.exe

**Pull request merged**
