### PR TITLE
Remove erroneous "filed" Overlay property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
The impending removal of this erroneous property spelling was notified in https://forums.highfidelity.com/t/overlays-property-filed-is-deprecated/13378.

**Test Plan**

Run the attached testFiled.js script and check its output.

[testFiled.zip](https://github.com/highfidelity/hifi/files/1598771/testFiled.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5907/app_12077_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5907/HighFidelity-Beta-PR12077-7013f6471409a5658ae473b3e0509a6c299b3a1e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5907/HighFidelity-Beta-PR12077-7013f6471409a5658ae473b3e0509a6c299b3a1e.exe

**Comment by conklin94122** [comment]
Testing

**Comment by conklin94122** [comment]
Found instances of "filled" and "isFilled", found zero instances of "filed" or "isFiled".

PASS.

**Pull request merged**
