### PR TITLE
Edge case fix for seated rotation - it would bounce forward if you let go of Q/E at exact right time.

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Clamp rotation velocity if hit trigger angle, but only bounce forward if cameraYaw is true.

https://highfidelity.atlassian.net/browse/DEV-2753

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22626/HighFidelity-Beta-PR16513-8ccdfaf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22626/HighFidelity-Quest-Beta-PR16513-8ccdfaf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22626/HighFidelity-Beta-PR16513-8ccdfaf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22626/HighFidelity-Beta-Interface-PR16513-8ccdfaf.dmg

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22628/HighFidelity-Beta-PR16513-8ccdfaf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22628/HighFidelity-Quest-Beta-PR16513-8ccdfaf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22628/HighFidelity-Beta-PR16513-8ccdfaf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22628/HighFidelity-Beta-Interface-PR16513-8ccdfaf.dmg

**Comment by DouglasWilcox** [comment]
TEST NOTES:
This PR fixes an edge case where avatar would "bounce" forward if you were rotating with Q/E keys and released at almost but not quite the limit of rotation.  To verify, try all variations of Q/E rotation and mouse l-click camera orbiting.  You should never have avatar get stuck facing back toward camera, and avatar should never "bounce" unexpectedly forward if you are just using Q/E keys to adjust orientation.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22631/HighFidelity-Beta-PR16513-19aacde.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22631/HighFidelity-Quest-Beta-PR16513-19aacde.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22631/HighFidelity-Beta-PR16513-19aacde.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22631/HighFidelity-Beta-Interface-PR16513-19aacde.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22631/HighFidelity-Beta-PR16513-19aacde.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22631/HighFidelity-Beta-Interface-PR16513-19aacde.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22643/HighFidelity-Beta-PR16513-19aacde.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22643/HighFidelity-Beta-Interface-PR16513-19aacde.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22643/HighFidelity-Beta-PR16513-19aacde.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22643/HighFidelity-Quest-Beta-PR16513-19aacde.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22643/HighFidelity-Beta-PR16513-19aacde.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22643/HighFidelity-Beta-Interface-PR16513-19aacde.exe

**Pull request merged**
