### PR TITLE
fix crash in ObjectMotionState::handleEasyChanges()

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* fix interface crash when making very small colliding objects

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1320/HighFidelity-Beta-PR10879-ede6c70233a40295b10ed935befcea5073a28f78.dmg

**Comment by marko8904** [comment]
test this please

**Comment by AndrewMeadows** [comment]
### Test plan:

(1) Login UserA with HMD.

(2) UserA: Make two copies of the flare gun from the marketplace

(3) UserA: Edit each flaregun and change its "Script URL" property to use this:  https://s3.eu-west-2.amazonaws.com/norteclabs.com/HF/debug/hookgun/hookgun.js

The flareguns are now "hook guns".  When you point and shoot they will send out a line that will pull the avatar toward the point where they hit.

(4) Login UserB using some interface that is NOT from this PR.  UserB will be the observer and will be the one to crash (or not).

(5) UserA: in view of UserB, use the guns to pull yourself straight into a wall, such that the hook guns' ropes change from long to small.  Flip around and pull yourself toward UserB and repeat pulling yourself into the wall.  There is a small possibility upon each hit of the wall that UserB will crash, so you may need to do this several times.

The reason for the crash is: upon hitting the wall tthe hook gun script is setting the size of the ropes to be so small that collision shapes are not generated for them.  The null shapes will sometimes violate an assumption in the code and will cause a crash.

(6) Repeat step (5) where UserB uses this PR.  UserB should not crash no matter how many times the ropes are set to very small lengths.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1326/HighFidelity-Beta-PR10879-ede6c70233a40295b10ed935befcea5073a28f78.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1326/HighFidelity-Beta-PR10879-ede6c70233a40295b10ed935befcea5073a28f78.dmg

**Comment by YuppyPlays** [comment]
Setting up for test.

Will comment when complete.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Just to give an update - Experiencing a very strange issue with weird blocks of colour effecting my game... Going to test Master to see if this is PR or My computer dying, etc...

image

**Comment by YuppyPlays** [comment]
Testing thus far; the weird colour blocks issue (looks almost like when a video has a low bitrate with random colors) appears to be just this PR

Should I continue with this issue and confirm if test works? I'd imagine this needs to be fixed first. Not happening in Master 6820.

**Comment by CainFoool** [comment]
@YuppyPlays This was an issue with the latest NVIDIA Update - has already been resolved and will be in the next Hotfix.

**Comment by AndrewMeadows** [comment]
I rebased onto the lastest master.

**Comment by cozza13** [comment]
@YuppyPlays @CainFoool this just got updated with master so will have the nvidia fix

**Comment by YuppyPlays** [comment]
Ah, excellent, will test once the build completes :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1387/HighFidelity-Beta-PR10879-2299bb7718c51dabb764b9874f4d229c80036b44.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1387/HighFidelity-Beta-PR10879-2299bb7718c51dabb764b9874f4d229c80036b44.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Note: Tried to find a empty place to do this in, could not do it within Sandbox as it wouldn't connect oddly from User B's interface to A's sandbox. So I used a quiet area within Dev-welcome, far away from players.

(1) Login UserA with HMD. **Pass**

(2) UserA: Make two copies of the flare gun from the marketplace **Pass**

(3) UserA: Edit each flaregun and change its "Script URL" property to use this: https://s3.eu-west-2.amazonaws.com/norteclabs.com/HF/debug/hookgun/hookgun.js **Pass**

The flareguns are now "hook guns". When you point and shoot they will send out a line that will pull the avatar toward the point where they hit. **Pass**

(4) Login UserB using some interface that is NOT from this PR. UserB will be the observer and will be the one to crash (or not). **Pass, used latest master for B**

(5) UserA: in view of UserB, use the guns to pull yourself straight into a wall, such that the hook guns' ropes change from long to small. Flip around and pull yourself toward UserB and repeat pulling yourself into the wall. There is a small possibility upon each hit of the wall that UserB will crash, so you may need to do this several times. **Pass, the guns kept disappearing over a set anount of time (Dev-welcome auto-clean up I'd imagine?) I re-spawned the guns 3 times and used that time to repeatedly hook into a wall in-front of User B, no crashes occurred. Went into the wall what I believe was 20+ times overall.**

The reason for the crash is: upon hitting the wall the hook gun script is setting the size of the ropes to be so small that collision shapes are not generated for them. The null shapes will sometimes violate an assumption in the code and will cause a crash.

(6) Repeat step (5) where UserB uses the interface from this PR. UserB should not crash no matter how many times the ropes are set to very small lengths. **Pass, Did not get a crash in this PR, game locked up a bit more during this phase (couldn't teleport in VR mode properly after loading the flare guns + hook script into them, but managed to test a few times without fail going directly back and fourth into a wall**

**Comment by AndrewMeadows** [comment]
The tester couldn't reproduce the crash.

I was able to reproduce the crash (semi-reliably) using the hook-guns in hifi/master but when I tried to make a custom script that set the dimensions of various entities to very small values I couldn't reproduce it.  The callstack pointed at a null shape pointer as the problem and when I changed the code to avoid null pointers the crashes went away for me.

Meanwhile, on this PR there is the report about "couldn't teleport in VR mode properly after loading the flare guns + hook script into them".  Was that just a glitch or do we need more testing?  It is hard to imagine how the changes in this PR would introduce something like that.

**Comment by AndrewMeadows** [comment]
I'm going to call it: QA_APPROVED.  It isn't more crashy.

**Pull request merged**
