### PR TITLE
Make resource swapchains immutable

### PR DESCRIPTION
**Pull request by jherico**
RC67 version of #13072, Fix for FB14638.  See #13072 for testing notes and details.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9418/app_13077_PR_233c60a5063573cb55770b382013deeefadfba6f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9418/HighFidelity-Beta-PR13077-233c60a5063573cb55770b382013deeefadfba6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9418/HighFidelity-Beta-Interface-PR13077-233c60a5063573cb55770b382013deeefadfba6f.dmg

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Sized the window via click and drag, never crashed.

**Pull request merged**
