### PR TITLE
Input Calibration UI

### PR DESCRIPTION
**Pull request by druiz17**
Created a new UI and system that will allow you to calibrate input Plugins

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- Have vive trackers on.
- open up the calibration UI Menu->Settings->InputConfiguration
- select an option from the Additional Trackers (note: head and hands option currently do not do anything)
- select the amount of time to wait to perform the calibration
- press calibrate button and wait for the results

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/593/HighFidelity-Beta-PR10668-e4e261287a0c6dba8ee7a3c83dd23097ec32d1ce.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/597/HighFidelity-Beta-PR10668-89b0e31edca001430e6d5cf2f467122fccd94c61.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/613/HighFidelity-Beta-PR10668-89b0e31edca001430e6d5cf2f467122fccd94c61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/623/HighFidelity-Beta-PR10668-e125e1f608230c3129530b77127ab50127dde49f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/623/HighFidelity-Beta-PR10668-e125e1f608230c3129530b77127ab50127dde49f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/746/HighFidelity-Beta-PR10668-d65c0dfbaca135a8f270ccc070bcccd5cdbb3908.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/746/HighFidelity-Beta-PR10668-d65c0dfbaca135a8f270ccc070bcccd5cdbb3908.exe

**Pull request closed without merging**
