### PR TITLE
Fix load from disk

### PR DESCRIPTION
**Pull request by sethalves**
- don't put empty folders in running-scripts list
- allow /~/ magic path to work from outside scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cfa847ba546006168a2da807026dc6a9f754f5e2 available at: https://gist.github.com/acc24c370055ab7dce4a6bfc296a06d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.dmg

**Comment by sethalves** [comment]
to test:
- generally exercise the running-scripts dialog.
- stop all scripts, use Menu --> Settings --> General --> load default scripts
- stop individual scripts
- load a script from local disk
- load a script from the web

**Comment by TNS-TrueNorth** [comment]
The buttons/icons on the right of the screen do not appear in PR7525 (Go To, Market, Edit), even after the user loads default scripts.  If this is expected, then the rest of the testing steps pass for Win10.

**Comment by sethalves** [comment]
yeah... I'm seeing that also.  I don't think ti's from this PR, but let me resolve it before we proceed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: aea06914b4b1d899c03616f608383d5cffecd7c9 available at: https://gist.github.com/acc24c370055ab7dce4a6bfc296a06d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63595e196e17e74fa084949636a56ff4dff532ef available at: https://gist.github.com/acc24c370055ab7dce4a6bfc296a06d9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7525.dmg

**Comment by sethalves** [comment]
@TNS-TrueNorth could you retest?

**Comment by TNS-TrueNorth** [comment]
Testing PR7525

**Pull request merged**
