### PR TITLE
JSDoc that an entity's clientOnly property can be set at entity creation

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8140/app_12682_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8141/app_12682_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8141/HighFidelity-Beta-PR12682-541d798a6be1ad242b6088f4d93580d9423dc9ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8141/HighFidelity-Beta-PR12682-541d798a6be1ad242b6088f4d93580d9423dc9ad.exe

**Pull request merged**
