### PR TITLE
Case 22095: Disable JSBaker for now (RC82)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/22095/Re-disable-JSBaker-for-now-for-82

Test plan: https://github.com/highfidelity/hifi/pull/15348

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18637/HighFidelity-Beta-PR15349-f08b5e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18637/HighFidelity-Beta-Interface-PR15349-f08b5e3.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18637/HighFidelity-Beta-PR15349-f08b5e3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18637/HighFidelity-Quest-Beta-PR15349-f08b5e3.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18643/HighFidelity-Beta-PR15349-f08b5e3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18643/HighFidelity-Quest-Beta-PR15349-f08b5e3.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18643/HighFidelity-Beta-PR15349-f08b5e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18643/HighFidelity-Beta-Interface-PR15349-f08b5e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18643/HighFidelity-Beta-PR15349-f08b5e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18643/HighFidelity-Beta-Interface-PR15349-f08b5e3.exe

**Pull request merged**
