### PR TITLE
don't draw head-descendant entitys with 1st-person camera

### PR DESCRIPTION
**Pull request by sethalves**
- entities that are children of a joint above the neck wont be drawn in 1st-person camera mode

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/10289/avatar-entities-should-not-cover-the-face

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6247/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6247/HighFidelity-Beta-PR12158-9d4ab13a10df7ffc139df39c5fc24b33f473b302.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6247/HighFidelity-Beta-PR12158-9d4ab13a10df7ffc139df39c5fc24b33f473b302.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6253/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6253/HighFidelity-Beta-PR12158-9bdb89df2ea40108f440df59f89feb2a8d92c144.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6253/HighFidelity-Beta-PR12158-9bdb89df2ea40108f440df59f89feb2a8d92c144.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6259/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6260/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6262/HighFidelity-Beta-PR12158-f81f50a6d282061fe2e5a271b4d852513f0513b4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6407/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6407/HighFidelity-Beta-PR12158-d897b1c1eb05cbf6eae0419c10b617bffa4db618.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6408/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6408/HighFidelity-Beta-PR12158-97a4f141eb6048c3d245a02716f58c0bb4f67cdc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6408/HighFidelity-Beta-PR12158-97a4f141eb6048c3d245a02716f58c0bb4f67cdc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6413/HighFidelity-Beta-PR12158-1c819c84224b077fa1e203429478a0916d9b4805.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6416/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6416/HighFidelity-Beta-PR12158-fb974b0b9c93f77d75fe460ae7fcfa03c83e43ad.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6416/HighFidelity-Beta-PR12158-fb974b0b9c93f77d75fe460ae7fcfa03c83e43ad.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6437/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6437/HighFidelity-Beta-PR12158-0ad4cdc41b47618bdb712fad907b54e980281c12.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6439/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6439/HighFidelity-Beta-PR12158-7c32d3c5360497bb8e531ad1fc1e49edc2879136.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6440/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6440/HighFidelity-Beta-PR12158-31c007d1672a970dc5a1bfbe11b88801fb36f55b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6440/HighFidelity-Beta-PR12158-31c007d1672a970dc5a1bfbe11b88801fb36f55b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6468/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6468/HighFidelity-Beta-PR12158-bce9b5f4590c1bdf8dbba13dcc032aaba84aaaa2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6468/HighFidelity-Beta-PR12158-bce9b5f4590c1bdf8dbba13dcc032aaba84aaaa2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6488/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6488/HighFidelity-Beta-PR12158-c622cd8293943206f056b2553393be6df60844e2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6488/HighFidelity-Beta-PR12158-c622cd8293943206f056b2553393be6df60844e2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6513/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6513/HighFidelity-Beta-PR12158-f6b4cf4c60f6cb84f4b727d5984b5be7bda93495.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6513/HighFidelity-Beta-PR12158-f6b4cf4c60f6cb84f4b727d5984b5be7bda93495.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6554/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6554/HighFidelity-Beta-PR12158-1cbc2e31cf846d22730179d691dbe23ddf52db2d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6554/HighFidelity-Beta-PR12158-1cbc2e31cf846d22730179d691dbe23ddf52db2d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6683/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6684/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6684/HighFidelity-Beta-PR12158-98e0e663e7b49c2f7be2a0e6f414bb39acc63f9e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6684/HighFidelity-Beta-PR12158-98e0e663e7b49c2f7be2a0e6f414bb39acc63f9e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6769/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6769/HighFidelity-Beta-PR12158-64a46bf5dfdc2f593ca0f0256dfe219f78dc916e.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6777/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6783/app_12158_PR.apk

**Comment by sethalves** [comment]
to test:
- go to avatar island and try on a bracelet and something that goes on your face
- in 1st person camera (with hmd and without) make sure you can see the bracelet but not the thing on your face
- look in the mirror and make sure you can see both
- buy them, leave the shop
- return to the shop, look in the mirror, make sure they behave as before

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6824/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6824/HighFidelity-Beta-PR12158-482be7ba4ecf3db2cb162ae864b4dd4ef16e29b6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6824/HighFidelity-Beta-PR12158-482be7ba4ecf3db2cb162ae864b4dd4ef16e29b6.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6838/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6838/HighFidelity-Beta-PR12158-bdf6736a5429ddd8629b01e1d6e24a851df4627c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6838/HighFidelity-Beta-PR12158-bdf6736a5429ddd8629b01e1d6e24a851df4627c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6867/app_12158_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6867/HighFidelity-Beta-PR12158-861497e90791eb54770806c27052c1c8634267a1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6867/HighFidelity-Beta-PR12158-861497e90791eb54770806c27052c1c8634267a1.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122

**Pull request merged**
