### PR TITLE
fix metadata tags, hosts, restriction

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Ensure that the correct tags, hosts, and restriction are sent to metaverse.highfidelity.com/api/v1/domains/DOMAIN_ID when the domain-server is saved.

Possible restrictions are:
- `open`: anonymous and logged in users can connect
- `anon`: anonymous users can connect, logged in users cannot
- `hifi`: anonymous users cannot connect, logged in users can
- `acl`: anonymous and logged in users cannot connect

Ensure that the correct users numbers are sent to high fidelity. You'll be able to see this numbers both from the API endpoint and the logs. Ensure they are only generated (visible in the domain-server logs as) when a heartbeat is being sent (every 15s).

This is visible through two log messages, which you should check are accurate:
- `Domain metadata users change detected`: logged when a user connects/disconnects, not throttled
- `Domain metadata users updated: UPDATED_JSON`: logged when the users JSON is regenerated, throttled to only occur at heartbeats (every 15s).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74f62e031b3e17d597322b8802be6400a0b33f80 available at: https://gist.github.com/e61cb05b0a969b50103448890639a5ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25b21dacda246e7ff691bdf4db9cf67d8b57cbd0 available at: https://gist.github.com/e61cb05b0a969b50103448890639a5ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cfe9ac32d4ff761fe07817959e9f89a19a0c4535 available at: https://gist.github.com/e61cb05b0a969b50103448890639a5ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8107.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Testing Ubuntu Linux 16.04/QT5.6.0
Trying various combos of restrictions shows correct stats from metaverse server - as user(s) connect/disconnect count changes and message is logged.  And I also confirmed scripted agents are **not** counted in any stat of interest here :+1: 

Will take #8111 when ready.

**Comment by OmegaHeron** [comment]
Also - forgot to mention - hosts and tags add/delete/edit is again working proper from DS web UI.  :+1:

**Pull request merged**
