### PR TITLE
fix -- work around asset-upload dialog crash

### PR DESCRIPTION
**Pull request by sethalves**
- don't free dialogs to avoid crash in setKeyboardRaised

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8297/app_12717_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8298/app_12717_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8298/HighFidelity-Beta-PR12717-4f7d856a1c0ac7849542e03065f26740c6f6d09e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8298/HighFidelity-Beta-PR12717-4f7d856a1c0ac7849542e03065f26740c6f6d09e.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8299/app_12717_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8299/HighFidelity-Beta-PR12717-4f7d856a1c0ac7849542e03065f26740c6f6d09e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8299/HighFidelity-Beta-PR12717-4f7d856a1c0ac7849542e03065f26740c6f6d09e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Did not crash when uploading FBX.

**Comment by conklin94122** [comment]
@sethalves Needs dev review

**Comment by druiz17** [comment]
@conklin94122 Did @qlimnavarro test this on the tablet?

**Comment by qlimnavarro** [comment]
Currently testing

**Comment by conklin94122** [comment]
@sethalves needs dev review

**Pull request merged**
