### PR TITLE
Spectator Camera

### PR DESCRIPTION
**Pull request by zfox23**
## Description
By default, your monitor shows a preview of what you're seeing in VR. Using the Spectator Camera app, your monitor can display the view from a virtual hand-held camera - perfect for taking selfies or filming your friends!

The Discovery team slowly started working on the Spectator Camera towards the end of May. There have been some pauses and hiccups along the way - including temporarly moving all effort to a brand-new project - but we are finally ready and proud to share the Spectator Camera and its test plan. Enjoy!

## Spectator Camera Test Plan
[Follow this link for a copy of the Spectator Camera Master Test Plan.](https://docs.google.com/spreadsheets/d/1ohM8hzqHAfT2P9Qy9jtBUtrESSPWV6cTSYTCJOp-L9k/edit?usp=sharing) This copy is meant for 2017-07-13's tests and can be edited directly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1306/HighFidelity-Beta-PR10875-fcc131187d426e43cfb6d649e073f9476dcd3319.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1306/HighFidelity-Beta-PR10875-fcc131187d426e43cfb6d649e073f9476dcd3319.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1323/HighFidelity-Beta-PR10875-44cb48b17d6bb624c8adf99e2e403b64fceae1e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1323/HighFidelity-Beta-PR10875-44cb48b17d6bb624c8adf99e2e403b64fceae1e0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1356/HighFidelity-Beta-PR10875-8c0697f26b036145e2e4e9a2fce4377d531032d5.dmg

**Comment by davidkelly** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1359/HighFidelity-Beta-PR10875-8c0697f26b036145e2e4e9a2fce4377d531032d5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1359/HighFidelity-Beta-PR10875-8c0697f26b036145e2e4e9a2fce4377d531032d5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1366/HighFidelity-Beta-PR10875-8c36e5c69f7361f40c6d791ff65d1054cfcf7033.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1366/HighFidelity-Beta-PR10875-8c36e5c69f7361f40c6d791ff65d1054cfcf7033.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1385/HighFidelity-Beta-PR10875-ee86638c4e6ff6ba3b4b68cbf0fe70a53619ad3a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1385/HighFidelity-Beta-PR10875-ee86638c4e6ff6ba3b4b68cbf0fe70a53619ad3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1423/HighFidelity-Beta-PR10875-ee4ef14152bb87c29e1543acdbf01f0bb70c1a0b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1423/HighFidelity-Beta-PR10875-ee4ef14152bb87c29e1543acdbf01f0bb70c1a0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1470/HighFidelity-Beta-PR10875-dbb48cd1aa42c0b7559125a9d2eea02ce56df96b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1470/HighFidelity-Beta-PR10875-dbb48cd1aa42c0b7559125a9d2eea02ce56df96b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1481/HighFidelity-Beta-PR10875-cdfbb02471854c3774fc9df05871bce079f0f8c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1481/HighFidelity-Beta-PR10875-cdfbb02471854c3774fc9df05871bce079f0f8c5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1499/HighFidelity-Beta-PR10875-4843b91f47b6f8582d3dcbef0098d8a8a9380471.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1499/HighFidelity-Beta-PR10875-4843b91f47b6f8582d3dcbef0098d8a8a9380471.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1505/HighFidelity-Beta-PR10875-91ffb003fd53fd911ba5ae99a5db37b3ecae9181.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1505/HighFidelity-Beta-PR10875-91ffb003fd53fd911ba5ae99a5db37b3ecae9181.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1512/HighFidelity-Beta-PR10875-78d12f27eda62d79a5a5e7b14424e462703ef41d.dmg

**Comment by zfox23** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1514/HighFidelity-Beta-PR10875-78d12f27eda62d79a5a5e7b14424e462703ef41d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1514/HighFidelity-Beta-PR10875-78d12f27eda62d79a5a5e7b14424e462703ef41d.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1521/HighFidelity-Beta-PR10875-ea62ef165cd8c953bf0c020580150f95cbe4f378.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1521/HighFidelity-Beta-PR10875-ea62ef165cd8c953bf0c020580150f95cbe4f378.dmg

**Comment by sharsein** [comment]
testing.

**Comment by sharsein** [comment]
QA Fail.
Tested on Windows 10 with a Vive
One major crash, one large issue that I got to happen twice but would need further investigating to find a consistent repro and some more minor issues.  Pretty nifty feature though.

Spreadsheet with notes: https://docs.google.com/spreadsheets/d/1igPEMTWqA2m2QzRoD-rng1XdibkBfzEn5_xP2Psy2yU/edit?usp=sharing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1547/HighFidelity-Beta-PR10875-8fd02c1d0cc23533ba9c1be7d88b6e233319355a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1547/HighFidelity-Beta-PR10875-8fd02c1d0cc23533ba9c1be7d88b6e233319355a.dmg

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1567/HighFidelity-Beta-PR10875-d78682067068fc990ce37999936e2f7cc883ce67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1567/HighFidelity-Beta-PR10875-d78682067068fc990ce37999936e2f7cc883ce67.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by conklin94122** [comment]
New test plan - https://docs.google.com/spreadsheets/d/1Ifis_FyHQC7_WcfbDoyWRfpjMJo9MKxKLoSDrSIfNVk

**Comment by zfox23** [comment]
@conklin94122 - that is the same test plan as linked in the description of this PR, right?

**Comment by conklin94122** [comment]
@zfox23 Not exactly. The link at the top is of the parent/master copy of this test plan, which is for High Fidelity use and not for execution and mark-up.

The link I provided is of a copy of that doc which everyone has permissions to edit and comment on.

Apologies for any confusion.

**Comment by zfox23** [comment]
@conklin94122 - I gave @Nex-Pro view permissions of the original spreadsheet, so he made a copy of it and is working off of that copy.

**Comment by Nex-Pro** [comment]
Results here.

https://docs.google.com/spreadsheets/d/1NoL4neO6XBKSB0NJrGzG_YxxFMVZB2Cwu9sRE4ckYTY/edit?usp=sharing

Mostly good !  nice work @zfox23

**Comment by Nex-Pro** [comment]
hifi-snap-by--on-2017-07-12_02-58-24

**Comment by Nex-Pro** [comment]
Procedural shaders for the sky are  rendering strangely in the camera. See this vid.
https://www.dropbox.com/s/rnglfzisxv0ksrr/Spectator%20Camera%20%2310875%20background%20sky%20problems.mp4?dl=0

**Comment by Nex-Pro** [comment]
So with the issues in the spreadsheet and the above : **FAIL**

**Comment by zfox23** [comment]
There are two takeaways I noticed from that video:
1. You're noticing the reduced draw distance in the spectator camera. I don't see a problem with the skybox, unless I'm missing something. We will consider changing that. 
2. The "piece of glass" is indeed affecting the viewfinder preview. The model is not final, and this glass may be changed.

**Comment by Nex-Pro** [comment]
@zfox23 Yeah it's just clipping not the shader or skybox

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1624/HighFidelity-Beta-PR10875-34d0363ae50c8f82c80b3d13d7e9b2a34a641e29.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1630/HighFidelity-Beta-PR10875-d6798c070e25a9b19c33fb210fbde04258e083be.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1630/HighFidelity-Beta-PR10875-d6798c070e25a9b19c33fb210fbde04258e083be.dmg

**Comment by Nex-Pro** [comment]
@zfox23 You want me to re-test this when ready ?

**Comment by zfox23** [comment]
@Nex-Pro - no thanks, not yet. We want a new camera model and preview bugfix in (and maybe the new camera spawn orientation) before we re-test.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1642/HighFidelity-Beta-PR10875-8553277c5694c0fa60a99fae909d3eb2a104c817.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1642/HighFidelity-Beta-PR10875-8553277c5694c0fa60a99fae909d3eb2a104c817.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1649/HighFidelity-Beta-PR10875-b5a1c65622843244b56f59d7c45f75748b01b5f6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1653/HighFidelity-Beta-PR10875-a6ae50fcd9a493935a5c248c77c234594be33e3c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1653/HighFidelity-Beta-PR10875-a6ae50fcd9a493935a5c248c77c234594be33e3c.exe

**Comment by zfox23** [comment]
After this build completes, this PR will be QA ready once again.

[Please use this spreadsheet for testing.](https://docs.google.com/spreadsheets/d/1ohM8hzqHAfT2P9Qy9jtBUtrESSPWV6cTSYTCJOp-L9k/edit?usp=sharing) You can edit it directly.

**Comment by Nex-Pro** [comment]
Will test this as requested

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1671/HighFidelity-Beta-PR10875-60751f07bd573adec9be0ea91082e6ebe75e6eab.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1671/HighFidelity-Beta-PR10875-60751f07bd573adec9be0ea91082e6ebe75e6eab.dmg

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
### Possible Fail

@zfox23 
See results below.

https://docs.google.com/spreadsheets/d/1ohM8hzqHAfT2P9Qy9jtBUtrESSPWV6cTSYTCJOp-L9k/edit#gid=251389392

Clipping in the camera is resolved.

**Desktop user can get an unresponsive display. See spreadsheet.
 Basic functionality tab cell E:16**

**Comment by zfox23** [comment]
Thanks for your detailed QA, @Nex-Pro! I have resolved the bug you mentioned. QA Pass now!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1681/HighFidelity-Beta-PR10875-2c94917fb8d32cbe41828452df0b4b3779abc429.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1681/HighFidelity-Beta-PR10875-2c94917fb8d32cbe41828452df0b4b3779abc429.exe

**Pull request merged**
