### PR TITLE
Case 21759: Entities.emitScriptEvent works now (RC81)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21759/Entities-emitScriptEvent-doesn-t-work-on-web-entities-for-81

Test plan: https://github.com/highfidelity/hifi/pull/15201

### CODE REVIEW

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18209/HighFidelity-Beta-PR15202-9f7d1f7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18209/HighFidelity-Beta-Interface-PR15202-9f7d1f7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18209/HighFidelity-Beta-PR15202-9f7d1f7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18209/HighFidelity-Quest-Beta-PR15202-9f7d1f7.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18209/HighFidelity-Beta-PR15202-9f7d1f7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18209/HighFidelity-Beta-Interface-PR15202-9f7d1f7.exe

**Comment by conklin94122** [comment]
Confirming priority, please do not merge yet.

**Comment by conklin94122** [comment]
Will not go into 81.0, closing, per Mark.

**Pull request closed without merging**
