### PR TITLE
Reset filtering when clearing log search box

### PR DESCRIPTION
**Pull request by Atlante45**
## Test plan:
- Enter a search term in the log dialog.
- Log should get filtered.
- Clear search term.
- log shouldn't be filtered anymore.

### CODE REVIEW

**Comment by huffman** [comment]
Congratulations.

**Comment by birarda** [comment]
I can't believe you opened an issue to immediately close it with this PR.

https://en.wikipedia.org/wiki/Barry_Bonds

**Comment by ZappoMan** [comment]
sorry - but we're removing this functionality as part of the tablet UI work... 

closing.

**Comment by huffman** [comment]
Go home, there's nothing to see here.

**Comment by zfox23** [comment]
boooooooo

**Comment by Atlante45** [comment]
This is oppression! You're denying a perfectly reasonable bug fix!

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6ec0b1e530eae41d3a2442f231eac64b58958c4 available at: https://gist.github.com/42ecf5421902802468c196ddf1a16040<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10000-b6ec0b1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10000-b6ec0b1.dmg

**Pull request closed without merging**
