### PR TITLE
Add ability to parent overlays to MyAvatar for use across servers

### PR DESCRIPTION
**Pull request by huffman**
Right now you can only parent to your avatar's sessionID, which changes when switching domains. This PR let's you use the special AVATAR_SELF_ID as a unique identifier for your own avatar.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e50649102678dde1b8e2d497125f97900eeb684a available at: https://gist.github.com/90851d3bcccf226685cc0757ae025198<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8596-e506491.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8596-e506491.dmg

**Comment by huffman** [comment]
Test notes coming soon, I need to put together a script to properly test this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e50649102678dde1b8e2d497125f97900eeb684a available at: https://gist.github.com/90851d3bcccf226685cc0757ae025198<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8596-e506491.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8596-e506491.dmg

**Comment by huffman** [comment]
To test:

 1. Go to localhost
 1. Create an overlay attached to your avatar, something like:
   1. `Overlays.addOverlay("sphere", { parentID: "{00000000-0000-0000-0000-000000000001}", parentJointIndex: MyAvatar.getJointIndex("RightHand"), localPosition: { x: 0, y: 0, z: 0 } });`
 1. Confirm that a sphere is attached to your avatar's right hand
 1. Confirm that the sphere does not disappear when you shut your server down or when you switch servers

**Comment by thoys** [comment]
## QA Testing report

Sphere is attached to my right hand, sphere is still attached on disconnect/switching-servers.

The special parent UUID did not work for an entity, shouldn't this be acceptable if clientOnly = true? Entities.addEntity({_yourProps..._}, **true**); // <---

QA Pass

**Comment by huffman** [comment]
@thoys Yeah, that might be doable. I think internally it does something like that actually, but you have to pass the actual session id in. This would be a good future improvement.

**Pull request merged**
