### PR TITLE
2017-10-18: Merge RC57 into Master

### PR DESCRIPTION
**Pull request by zfox23**
There are just a few things missing from `master` that went into `RC57`.

From oldest to newest:
#11596 
#11594 
#11601 
#11606 
#11610 

The test plans for all of the above are small and straightforward. Please perform them all in order on this build to QA this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4255/HighFidelity-Beta-PR11623-a669aff4530f5eb929eba81a475b7df3eeb0c643.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4255/HighFidelity-Beta-PR11623-a669aff4530f5eb929eba81a475b7df3eeb0c643.exe

**Comment by ShoaibSmith** [comment]
Testing

**Comment by ShoaibSmith** [comment]
Tested this with @Starphys

#11596 - Pass 
#11594: Pass, but for 2.i. the html file doesn't always open. However, 9.i. worked just fine.
#11601 - Pass
#11606 - Pass
#11610 - Pass

**Pull request merged**
