### PR TITLE
Addressing thread safety issues

### PR DESCRIPTION
**Pull request by jherico**
* Make controller scripting interface members thread safe
* Make ScriptCache members thread safe

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee017cf0a570d9a830804ac7400d335c3d9cd4ef available at: https://gist.github.com/c0bdd2bbb96914569c80<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7310.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7310.dmg

**Comment by OmegaHeron** [comment]
Any testing specific testing notes or just basic does it obviously break anything test?

**Comment by ZappoMan** [comment]
@OmegaHeron - yeah, this is basically a smoke test, and make sure nothing breaks... scripts in general need to still work. There's a feature in the controller interface that allows a script t "capture" the mouse events, so that the application doesn't get them... you could test that feature... but this PR really is about making sure that two threads don't attempt to access the script cache at the same time.

**Comment by ZappoMan** [comment]
My quick smoke test reveals it to be working fine.

**Comment by OmegaHeron** [comment]
Same - Tested Windows 7, all my expected scripts run and work proper.  Didn't check out capture thing as it's not central point and have no idea how to wield it.  QA Pass

**Pull request merged**
