### PR TITLE
enable continuous collision detection (CCD) for MyAvatar

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR is to address a bug where it is possible to tunnel MyAvatar into a state of trapped penetration of mesh objects by flying really fast.  The problem was: we were not using Bullet's continuous collision detection (CCD) feature for MyAvatar's RigidBody in the physics simulation.

**Test Plan**:
**(1)** Login to a domain with a mesh wall.
**(2)** Fly your avatar far away from the wall so you have enough distance to ramp up to high speeds.
**(3)** Turn around and fly directly at the wall as fast as you can.
--> on hifi/master you might tunnel completely through the wall, or maybe get stuck in the middle of the wall's mesh
--> on this PR you should never tunnel through or get stuck

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12322/HighFidelity-Beta-PR13864-8167542.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12322/HighFidelity-Beta-PR13864-8167542.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12322/HighFidelity-Beta-Interface-PR13864-8167542.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12350/HighFidelity-Beta-PR13864-55eb302.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12350/HighFidelity-Beta-PR13864-55eb302.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12350/HighFidelity-Beta-Interface-PR13864-55eb302.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12350/HighFidelity-Beta-PR13864-55eb302.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12350/HighFidelity-Beta-Interface-PR13864-55eb302.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Fail @conklin94122 

After 4 or 5 tries I was able to fly into a wall.  Performance does feel a little choppier as well.

**Comment by AndrewMeadows** [comment]
I think the problem has to do with how MyAvatar's fly motor works: it continues to push the avatar into penetration even after CCD does its part.  The solution will be more difficult than just turning on CCD.  I'm going to close this PR and try again later.

**Pull request closed without merging**
