### PR TITLE
Rename libraries/model -> libraries/graphics

### PR DESCRIPTION
**Pull request by humbletim**
This PR renames the `model` library as `graphics` (per discussions with @samcake).
 
Overall premise is to head away from the overloaded "Model" name/abstraction and move towards a more focused "Graphics" abstraction.

Changes:
    - rename folder: `/libraries/model` => `/libraries/graphics`
    - rename C++ namespace: `model::` => `graphics::`
    - rename nested includes: `#include <model/...>` => `#include <graphics/...>`
    - rename class: `ModelLogging.h/cpp` => `GraphicsLogging.h/cpp`

#### Testing
General smoke test to verify that this PR doesn't affect application functionality.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6324/app_12181_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6324/HighFidelity-Beta-PR12181-b91d536dd0ee17c0572e4cb39b8bd0b337fa9e5e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6324/HighFidelity-Beta-PR12181-b91d536dd0ee17c0572e4cb39b8bd0b337fa9e5e.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
