### PR TITLE
Test highp floats for Android

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/14575

Test plan:
- Textures should render properly on Android
- On Android, in Top View mode, the teleport beam should exactly follow your finger.
- Shouldn't see any shader compilation issues on Windows (NVIDIA and AMD), Mac, or Android

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9570/app_13117_PR_c2004debd57921c6d2f3658ea05e0b0e2232b94a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9570/HighFidelity-Beta-PR13117-c2004debd57921c6d2f3658ea05e0b0e2232b94a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9570/HighFidelity-Beta-Interface-PR13117-c2004debd57921c6d2f3658ea05e0b0e2232b94a.dmg

**Comment by qlimnavarro** [comment]
Currently Testing Desktop Interface.

**Comment by qlimnavarro** [comment]
Interface Passes @conklin94122 
All basic features work well and look good.

**Comment by qlimnavarro** [comment]
Currently Testing Android

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
PR plan and Smoke pass.

**Pull request merged**
