### PR TITLE
Updated the license date

### PR DESCRIPTION
**Pull request by marko8904**
Test Plan:

- Run the installers.
- Ensure that the license shown in the installer correctly indicates "Copyright (c) 2013-2018, High Fidelity, Inc." at the top.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9348/app_13059_PR_ec7fcb60f3ebaa8ce1a7b05d0065f083d3f4be4b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9348/HighFidelity-Beta-PR13059-ec7fcb60f3ebaa8ce1a7b05d0065f083d3f4be4b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9348/HighFidelity-Beta-Interface-PR13059-ec7fcb60f3ebaa8ce1a7b05d0065f083d3f4be4b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9348/HighFidelity-Beta-PR13059-ec7fcb60f3ebaa8ce1a7b05d0065f083d3f4be4b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9348/HighFidelity-Beta-Interface-PR13059-ec7fcb60f3ebaa8ce1a7b05d0065f083d3f4be4b.exe

**Comment by AndrewMeadows** [comment]
Actually I only tested the Windows installers.  Do we want to bother to test on Mac and Android?

**Comment by QliCknox** [comment]
Currently Testing

**Comment by marko8904** [comment]
@AndrewMeadows Mac license should be updated too. I don't think that Android shows the license at all.

**Pull request merged**
