### PR TITLE
Check qml gl context on create

### PR DESCRIPTION
**Pull request by zzmp**
Propagates the status of gl context creation through to the creation of the OffscreenQmlSurface, and logs data and crashes Interface if it fails.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 60f22c51b94a5be0f3f9b8a9f71ff69fad09db97 available at: https://gist.github.com/fe9f63794a778e18b8b9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7384.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7384.dmg

**Comment by ZappoMan** [comment]
Test Plan: Run a basic smoke test... make sure things work as expected.

**Comment by zzmp** [comment]
I would also like to crash this at a specific breakpoint to ensure it logs correctly and still goes through bugsplat. QA Ready, but DNM until I perform that, probably in the morning.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12aa057ff6dc671ab091d443daf9fd8327772211 available at: https://gist.github.com/fe9f63794a778e18b8b9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7384.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7384.dmg

**Comment by ZappoMan** [comment]
I smoked this PR, running in several domains. It crashed once in an unrelated part of the code (the known `QmlWindowClass::isVisible`crash. So I think this smokes ok. And I will QA Approve it.

**Pull request merged**
