### PR TITLE
(Experiment) Changing tablet position - based on PR 11134 [Do not merge]

### PR DESCRIPTION
**Pull request by mukulHF**
Plz tag this as Do not merge and Feedback welcome

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2452/HighFidelity-Beta-PR11175-db4ae8be87be40a6c2d0eed3e0ba6359167004db.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2452/HighFidelity-Beta-PR11175-db4ae8be87be40a6c2d0eed3e0ba6359167004db.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2458/HighFidelity-Beta-PR11175-6ce11a27b48967f0fad8c47fe15f88df565e4f31.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2474/HighFidelity-Beta-PR11175-6ce11a27b48967f0fad8c47fe15f88df565e4f31.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2474/HighFidelity-Beta-PR11175-6ce11a27b48967f0fad8c47fe15f88df565e4f31.exe

**Pull request closed without merging**
