### PR TITLE
quiet gcc 5 warnings

### PR DESCRIPTION
**Pull request by sethalves**
- quiet gcc 5 compiler warnings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40e862cf9e624b50f91f267c87148ceeb7fef505 available at: https://gist.github.com/814309c1472f3672b86c49680015a366<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40e862cf9e624b50f91f267c87148ceeb7fef505 available at: https://gist.github.com/814309c1472f3672b86c49680015a366<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7142aee806e570ea07cef9c360ff89cc1c7ca89 available at: https://gist.github.com/814309c1472f3672b86c49680015a366<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7955.dmg

**Comment by sethalves** [comment]
to test:
- SMOKE TEST!  HAHAHAHA

**Comment by Nex-Pro** [comment]
@sethalves  Awesome work!
I'm currently using CASE695ST to break in with no effect I'll upgrade to a JS370-T4i to get the job done.

**Comment by Nex-Pro** [comment]
@sethalves In the meanwhile It's looking fine on localhost.

**Comment by OmegaHeron** [comment]
Tested Linux Ubuntu 16.04 QT5.6.0 - DS/AC compile and operate proper.  No issues found there.  :+1:

**Pull request merged**
