### PR TITLE
fix script load from disk on windows

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that sometimes made loading scripts with the "FROM DISK" button fail

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open running-scripts dialog (ctrl j)
- load a script from disk (perhaps by navigating to C:\Program Files\High Fidelity\scripts and loading dice.js)

**Comment by kevinmthomas-carpool** [comment]
Installed Windows build 4579, successfully loaded for example dice.js and it functioned properly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 651d2c89542fb76ad807f9856a38eaaf86f6417e available at: https://gist.github.com/f7d08d88d9fcb13ca72b5cfec6712cb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7521.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7521.dmg

**Comment by kevinmthomas-carpool** [comment]
In addition installed and tested on windows PR build 7521 and was able to successfully test for example dice.js.

**Pull request merged**
