### PR TITLE
don't do a haptic pulse when av's hand goes near grabbable tablet

### PR DESCRIPTION
**Pull request by sethalves**
- don't do a haptic pulse when av's hand goes near grabbable tablet

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- ready hmd and haptic-enabled hand-controllers
- with hmd on, open tablet and move hand near tablet
- note that there is no haptic pulse, even though the tablet is grabbable
- make sure the haptic pulse still happens for other grabbable things

**Comment by hifi-gustavo** [comment]
Build console output for commit: aed1d693776047ba0f6fe001cd9700e7df8aed9d available at: https://gist.github.com/b1813dbd4e69391ae6186fe33b7459b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9729-aed1d69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9729-aed1d69.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift + Oculus Touch

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9729-aed1d69.exe

- Haptic pulse does not happen when hand is near tablet.
- Haptic pulse does happen when tablet is grabbed.
- Haptic pulse does happen when near and grabbing other entities.

**NOTE**
Tested with left and right devices.

**Pull request merged**
