### PR TITLE
Fix for AMD crashes in QML rendering

### PR DESCRIPTION
**Pull request by jherico**
Resolves a crash occurring on systems with AMD video cards

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6781/app_12307_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6782/app_12307_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6782/HighFidelity-Beta-PR12307-e5559fa865473af6d550253167ba1358877dd4c7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6782/HighFidelity-Beta-PR12307-e5559fa865473af6d550253167ba1358877dd4c7.dmg

**Comment by ZappoMan** [comment]
Hotfix version of #12300 

# Test Plan:
Follow same test plan as #12300

**Comment by ZappoMan** [comment]
Also do we really want to directly put this into stable? or do we want to make an RC63.2 branch?

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Machines tested: 
Mac - 3.4 GHz Intel Core i5 / Radeon Pro 560 4096 MB
Win - i5-6400 / AMD R9 290
Win - i7-6700 @ 3.4GHz / NVIDIA GTX 970
Win - Intel (R) Core(TM) i7-7700 CPU / NVIDIA GeForce GTX 1070

All machines ran for approximately 20 minutes, checked several domains (hifiqa-rc, dev-welcome, sandbox, etc), flew around. Only one crash occurred on the i5 AMD, but it appeared to be unrelated to the PR. Solid pass.

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122

Machines tested:
Mac - 3.4 GHz Intel Core i5 / Radeon Pro 560 4096 MB
Win - i5-6400 / AMD R9 290
Win - i7-6700 @ 3.4GHz / NVIDIA GTX 970
Win - Intel (R) Core(TM) i7-7700 CPU / NVIDIA GeForce GTX 1070

All machines ran for approximately 20 minutes, checked several domains (hifiqa-rc, dev-welcome, sandbox, etc), flew around. Only one crash occurred on the i5 AMD, but it appeared to be unrelated to the PR. Solid pass.

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6794/app_12307_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6794/HighFidelity-Beta-PR12307-e5559fa865473af6d550253167ba1358877dd4c7.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6800/app_12307_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6800/HighFidelity-Beta-PR12307-e5559fa865473af6d550253167ba1358877dd4c7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6800/HighFidelity-Beta-PR12307-e5559fa865473af6d550253167ba1358877dd4c7.dmg

**Pull request merged**
