### PR TITLE
FB19514 - Interface crashes on attempt to apply new animation url via…

### PR DESCRIPTION
**Pull request by ElderOrb**
… AvatarApp

https://highfidelity.fogbugz.com/f/cases/19514/Interface-crashes-on-attempt-to-apply-new-animation-url-via-AvatarApp

**Test plan**

1. Reset interface settings 
2. Open interface
3. Open avatarapp
4. Go to settings and specify custom animation url: https://s3.amazonaws.com/hifi-public/tony/scoot-animation.json
5. Press save
6. Ensure new avatar animation applied and interface didn't crash.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14689/HighFidelity-Beta-PR14343-cdfa38d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14689/HighFidelity-Beta-PR14343-cdfa38d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14689/HighFidelity-Beta-Interface-PR14343-cdfa38d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14689/HighFidelity-Beta-PR14343-cdfa38d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14689/HighFidelity-Beta-Interface-PR14343-cdfa38d.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15097/HighFidelity-Beta-PR14343-cdfa38d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15097/HighFidelity-Beta-PR14343-cdfa38d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15097/HighFidelity-Beta-Interface-PR14343-cdfa38d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15097/HighFidelity-Beta-PR14343-cdfa38d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15097/HighFidelity-Beta-Interface-PR14343-cdfa38d.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
