### PR TITLE
Blocks dont collide when held

### PR DESCRIPTION
**Pull request by ericrius1**
Prevents blocks from bumping into an avatar holding one.

### CODE REVIEW

**Comment by ericrius1** [comment]
test: https://rawgit.com/ericrius1/hifi/noBlockCollisions/unpublishedScripts/immediateClientReset.js

**Comment by RyanDowne** [comment]
This worked

**Comment by RyanDowne** [comment]
But I wonder now that we have "parents" if we can't make the blocks collide with each other but not an avatar?

**Comment by PhilipRosedale** [comment]
no - parenting doesn't affect the physics engine

**Comment by PhilipRosedale** [comment]
we need the 'collision groups' feature

**Pull request merged**
