### PR TITLE
fix avatar mixer sending empty avatar identities

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug with empty avatar identity packets being sent from the avatar mixer
- fixed a bug with avatar mixer possibly not sending identity packets after race

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1128/HighFidelity-Beta-PR10829-af79555e4b03ec401a541698bc381738a62a486c.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1129/HighFidelity-Beta-PR10829-af79555e4b03ec401a541698bc381738a62a486c.dmg

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1131/HighFidelity-Beta-PR10829-af79555e4b03ec401a541698bc381738a62a486c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1131/HighFidelity-Beta-PR10829-af79555e4b03ec401a541698bc381738a62a486c.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1135/HighFidelity-Beta-PR10829-e6cf7cf106cc00b8bdd443f95b87689b7278b352.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1142/HighFidelity-Beta-PR10829-e6cf7cf106cc00b8bdd443f95b87689b7278b352.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1142/HighFidelity-Beta-PR10829-e6cf7cf106cc00b8bdd443f95b87689b7278b352.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1147/HighFidelity-Beta-PR10829-e6cf7cf106cc00b8bdd443f95b87689b7278b352.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1147/HighFidelity-Beta-PR10829-e6cf7cf106cc00b8bdd443f95b87689b7278b352.dmg

**Comment by birarda** [comment]
#### Test Plan

This PR fixes an issue where the Avatar Mixer would send out identity updates about other agents before it had even processed an identity packet from them.

(1) Run the sandbox from this PR. 
(2) Connect to it from Interface and open the Interface log.
(3) Start a second Interface client and ensure that this client is using a non-default avatar URL. Connect to the same sandbox. 
(4) On the first Interface client, ensure that first time you process an identity packet for the other avatar you receive the correct skeleton model URL. You should not see a message about setting the skeleton model URL to an empty string (followed by a log about using the default avatar from your file system).

Repeat the steps above on master. It may take a couple of attempts (disconnecting and re-connecting the second client to the domain) but you should be able to reproduce the receipt of an identity packet with an empty skeleton model by the first Interface client.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
@birarda Not sure if I'm seeing what I'm supposed to be seeing, I've repeatedly connected/disconnected within Master, I get the following when using Photo realistic male avatar:

[Interface A's logs as Interface B' joins / leaves A's sandbox

[06/28 20:59:46] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{6a97093c-d3dd-49fb-aa78-eba29669ddf5}") - 38
[06/28 20:59:51] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{01ced18b-6026-4d1e-82cb-b95e0da8b5e7}") - 44
[06/28 20:59:55] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{1b1ba02f-4d12-43c1-be0d-cb1ce1654149}") - 48
[06/28 20:59:59] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{4136cfeb-4f4c-42f8-a610-d9932d0d41ec}") - 52
[06/28 21:00:04] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{29c1b457-2b2a-49f0-ad68-577f7ca054e0}") - 57
[06/28 21:00:08] [DEBUG] [hifi.avatars] Processing first identity packet for QUuid("{e6408bcb-0cac-4dba-9ebd-ae4450468656}") - 62

**Pull request merged**
