### PR TITLE
support certified content sets

### PR DESCRIPTION
**Pull request by davidkelly**
Which is as simple as considering .json.gz as being certified.

### CODE REVIEW

**Comment by davidkelly** [comment]
For now I didn't change the name of the variable (itemIsJson), as we will soon expand this to include other things (apps, scripts, avatars, etc...) and probably that will be re-worked a bit again.  

NOTE: this depends on a data web PR (https://github.com/highfidelity/data-web/pull/1315), so after that is in staging I'll create a purchasable content set there, and note that here so it can be tested.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6756/app_12301_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6756/HighFidelity-Beta-PR12301-331717584ddc4cf19317f929c3689f29f7646efa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6756/HighFidelity-Beta-PR12301-331717584ddc4cf19317f929c3689f29f7646efa.dmg

**Comment by davidkelly** [comment]
Test Plan:

(1) we will test in staging.  So, point this PR to staging
(2) go to marketplace, purchase the oasis content set
(3) observe that this looks the same as when you have purchased other things 
(4) go to your localhost domain if not already there
(5) rez oasis
(6) note that you can now inspect things in this content set
(7) verify that the certificate looks correct, takes you to marketplace item as expected.

**Comment by howard-stearns** [comment]
DNM until the back end goes to production. But it does need testing - in staging.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by howard-stearns** [comment]
prototype superseeded by other work

**Pull request closed without merging**
