### PR TITLE
RC69: add version code for increasing android appVersionCode

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10992/HighFidelity-Beta-PR13503-c1573aa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10992/HighFidelity-Beta-PR13503-c1573aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10992/HighFidelity-Beta-Interface-PR13503-c1573aa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10992/HighFidelity-Beta-PR13503-c1573aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10992/HighFidelity-Beta-Interface-PR13503-c1573aa.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10997/HighFidelity-Beta-PR13503-c1573aa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10997/HighFidelity-Beta-PR13503-c1573aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10997/HighFidelity-Beta-Interface-PR13503-c1573aa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10997/HighFidelity-Beta-PR13503-c1573aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10997/HighFidelity-Beta-Interface-PR13503-c1573aa.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11009/HighFidelity-Beta-PR13503-178b273.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11009/HighFidelity-Beta-PR13503-178b273.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11009/HighFidelity-Beta-Interface-PR13503-178b273.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11009/HighFidelity-Beta-PR13503-178b273.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11009/HighFidelity-Beta-Interface-PR13503-178b273.exe

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11036/HighFidelity-Beta-PR13503-178b273.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11036/HighFidelity-Beta-PR13503-178b273.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11036/HighFidelity-Beta-Interface-PR13503-178b273.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11036/HighFidelity-Beta-PR13503-178b273.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11036/HighFidelity-Beta-Interface-PR13503-178b273.dmg

**Comment by changxc** [comment]
what is the description or manuscript ticket for this PR?

**Comment by marko8904** [comment]
The Android version to test is https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11036/HighFidelity-Beta-PR0.13.37-178b273.apk

**Comment by birarda** [comment]
Tested by producing an APK and verifying the versionCode and versionName

**Pull request merged**
