### PR TITLE
Add backup directory setting to domain server

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 727d59ab27f290317654902e1f1903824643ed70 available at: https://gist.github.com/a5471965f303b103df790270af90bc8e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8448-727d59a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8448-727d59a.dmg

**Comment by huffman** [comment]
You will need an HMD and hand controllers for this.

To test:

1. Start in desktop mode (HMD off)
1. Disable your hand controllers
1. Go to your home domain
1. Run https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?pr8448
1. Enable edit
1. Create an entity
1. Move an entity
1. Delete an entity
1. Wait 20 seconds
1. Enable HMD mode
1. Enable your hand controllers
1. Move your head around
1. Move your hands around

Let me know when you are done and I will confirm everything worked.

**Comment by huffman** [comment]
This PR adds the ability to specify the location to store entity server `models.json.gz` backups.

To test:
 1. To start, I would recommend adding a backup rule that is set to run backups every 5 seconds or so. Example: http://prntscr.com/c6zd0l
  1. The entity server will only make backups if entities have changed, so if nothing changes in your domain then a backup won't be made. To force a backup, just make sure to make modification to at least 1 entity in your domain using edit.js.
 1. Open your domain settings. Show advanced. Go to `Entity Server Settings`. You should find a new `Backup directory` input. This will specify where backups are stored. There are 3 values for the directory you will want to test:
  1. Empty. This should then use the same directory that your models.json.gz file is in to store backups. You will want to also try changing the location of your models.json.gz so make sure backups are still stored next to it.
  1. A relative path. A relative path will be relative to your AppData directory
  1. An aboslute path. For instance, `C:\some_directory`
 1. Directories should also be created automatically if they don't already exist. Please test this as well.

**Comment by OmegaHeron** [comment]
Testing this on Linux and Windows

**Comment by OmegaHeron** [comment]
Tested Ubuntu Linux 16.04.1 - pass. It's critical end user understands where they do and do not have write perms -- presumably anyone savy enough to hack this to a working state on a Linux box would be that level of savvy.  There seems to be no indication of "bad things" if a path is given DS can't write to.

Tested Windows 10 - pass.

**Pull request merged**
