### PR TITLE
removed dead code for overlays/entities glow level

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Noticed we still had some of those laying around while reviewing Andrew's last PR.

**Comment by Atlante45** [comment]
Test plan:
- Smoke Test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12d8683704486eb2370bd9a126574a064a0c2a6e available at: https://gist.github.com/170241ac105173ab04fb08b5ef1cd62d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.dmg

**Comment by Nex-Pro** [comment]
@Atlante45  Not clear to me what we should be looking for on this test.

**Comment by Atlante45** [comment]
@Nex-Pro Nothing in particular, I just removed dead code.
Just make sure you're getting entities from the server and they get drawn correctly.

**Comment by AndrewMeadows** [comment]
Looking through the JS scripts I see a few that try to access the **glowLevel** property.  Those scripts should probably be updated.

**Comment by cozza13** [comment]
Happy to debate why the QA fail. Based on Andrews comments, I think it could be easy to go through the scripts to clean up references to glowLevel

**Comment by imgntn** [comment]
there's a reference in edit.js line 805 that could be updated, but that's all i see in developer/default

**Comment by Atlante45** [comment]
@AndrewMeadows nice catch.
There was 2 in the archives and edit.js, but it's in a part of edit.js that unused currently so it shouldn't have any effect.
@Nex-Pro can you smoke test edit.js for entity selection, creation, deletion, movement?

**Comment by hifi-gustavo** [comment]
Build console output for commit: c70a3bb78c4892018a7e5a12503f5509f969d78f available at: https://gist.github.com/170241ac105173ab04fb08b5ef1cd62d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.dmg

**Comment by ZappoMan** [comment]
@Atlante45 - this PR needs rebasing

**Comment by hifi-gustavo** [comment]
Build console output for commit: f75f54220b119c1b59dd5d611f4f89a1c917bdc0 available at: https://gist.github.com/170241ac105173ab04fb08b5ef1cd62d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5acbed647ca1f47473b6ca37cc6ecd40ebe54021 available at: https://gist.github.com/502c9553169fa1042165d51252170b64<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.dmg

**Comment by Atlante45** [comment]
Test Plan:

- Edit.js: Entity selection, creation, edition, deletion. (Only change I made is removing the highlightEntity function and related variables, but none of them were used anymore.)
- Overlays: test pulse functionality, here a bit of code you can paste in the console to do that:
(Sphere will be at the origin of the domain so make sure to jump there or to modify the position of the overlay)
```javascript
    var sphereProperties = {
        position: { x: 0, y: 0, z: 0 },
        size: 1.0,
        color: { red: 255, green: 0, blue: 0 },
        alpha: 1.0,
        pulseMin: 0.5,
        pulseMax: 1.0,
        alphaPulse: 1.0,
        solid: true,
        visible: true
    }
   var sphereOverlay = Overlays.addOverlay("sphere", sphereProperties);
```
To delete it:
```
   Overlays.deleteOverlay(sphereOverlay);
```

You can also try by replacing `alphaPulse` by `colorPulse`.

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b1497fdf4ddd04bffeac34aba16d6ee3a75e277 available at: https://gist.github.com/170241ac105173ab04fb08b5ef1cd62d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7858.dmg

**Comment by Nex-Pro** [comment]
glowLevel had no effect.
alphaPulse varied the alpha as expected
colorPulse varied the color in some way.

After deleting the overlay sphere and changing the code to colorPulse the last alpha state was apparent  when the next overlay sphere rezzed for the colorPulse test ( due to sphereProperties ) 
I set alpha to 1.0 which fixed that.

**Pull request merged**
