### PR TITLE
Don't run Script Editor scripts from the cache

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fed5e8e573320ce27dee28c96dd7e5d4f06dbd4e available at: https://gist.github.com/b78a2e342f49e561b661<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5875.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5875.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: fed5e8e573320ce27dee28c96dd7e5d4f06dbd4e available at: https://gist.github.com/b78a2e342f49e561b661<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5875.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5875.dmg

**Comment by cozza13** [comment]
QA'ed and it works

**Pull request merged**
