### PR TITLE
Fix a bug introduced in PR14566, actually fixing MS17811

### PR DESCRIPTION
**Pull request by zfox23**
Actually fixes [MS17811](https://highfidelity.manuscript.com/f/cases/17811) by fixing a bug I introduced in #14566.

Test Case:
open pal -> close pal -> ensure all users in the domain stick around.

The bug was when closing the pal, other user avatars would randomly reload.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15919/HighFidelity-Beta-PR14574-4e7b734.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15919/HighFidelity-Beta-PR14574-4e7b734.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15919/HighFidelity-Beta-Interface-PR14574-4e7b734.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15919/HighFidelity-Beta-PR14574-4e7b734.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15919/HighFidelity-Beta-Interface-PR14574-4e7b734.exe

**Comment by rickcarr044** [comment]
Currently testing PR14574

**Pull request merged**
