### PR TITLE
Case 20496: Windows (NSIS) installer shouldn't remove unselected component upon reinstall

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Ticket: https://highfidelity.manuscript.com/f/cases/20496/HiFi-Interface-uninstalls-if-user-attempts-to-install-Sandbox-without-Interface

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17043/HighFidelity-Beta-PR14853-e62f67a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17043/HighFidelity-Beta-PR14853-e62f67a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17043/HighFidelity-Beta-Interface-PR14853-e62f67a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17043/HighFidelity-Beta-PR14853-e62f67a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17043/HighFidelity-Beta-Interface-PR14853-e62f67a.exe

**Comment by rickcarr044** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17209/HighFidelity-Beta-PR14853-e62f67a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17209/HighFidelity-Beta-PR14853-e62f67a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17209/HighFidelity-Beta-Interface-PR14853-e62f67a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17209/HighFidelity-Beta-PR14853-e62f67a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17209/HighFidelity-Beta-Interface-PR14853-e62f67a.exe

**Pull request merged**
