### PR TITLE
include the codec name in the agent avatar audio stream

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
test plan:
- using the domain/"New Assignment" feature - run this script...
- go to 0,0,0 in that domain
- you should see the blue man avatar
- you should hear "audio" it's kinda a background/water noise...

```
// audioLoadTest.js 
//
// Copyright (c) 2016 HighFidelity, Inc. All rights reserved.
//
// This is an example script that does basic audio load testing
//
//

//For procedural walk animation
HIFI_PUBLIC_BUCKET = "http://s3.amazonaws.com/hifi-public/";

function getRandomFloat(min, max) {
    return Math.random() * (max - min) + min;
}

function getRandomInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function printVector(string, vector) {
    print(string + " " + vector.x + ", " + vector.y + ", " + vector.z);
}

function clamp(val, min, max) {
    return Math.max(min, Math.min(max, val))
}

Agent.isAvatar = true;
Agent.isListeningToAudioStream = true;

// change the avatar's position to wayPoints[0]
Avatar.position = { x: 0, y: 0, z: 0 };

function loadSounds() {
    // https://s3.amazonaws.com/hifi-public/sounds/EnvironmentalBackgroundsForLooping/water1+-+long+sample.raw


    var sound_filenames = ["water1+-+long+sample.raw"

      /*"AB1.raw", "Anchorman2.raw", "B1.raw", "B1.raw", "Bale1.raw", "Bandcamp.raw",
    "Big1.raw", "Big2.raw", "Brian1.raw", "Buster1.raw", "CES1.raw", "CES2.raw", "CES3.raw", "CES4.raw",
    "Carrie1.raw", "Carrie3.raw", "Charlotte1.raw", "EN1.raw", "EN2.raw", "EN3.raw", "Eugene1.raw", "Francesco1.raw",
    "Italian1.raw", "Japanese1.raw", "Leigh1.raw", "Lucille1.raw", "Lucille2.raw", "MeanGirls.raw", "Murray2.raw",
    "Nigel1.raw", "PennyLane.raw", "Pitt1.raw", "Ricardo.raw", "SN.raw", "Sake1.raw", "Samantha1.raw", "Samantha2.raw",
    "Spicoli1.raw", "Supernatural.raw", "Swearengen1.raw", "TheDude.raw", "Tony.raw", "Triumph1.raw", "Uma1.raw",
    "Walken1.raw", "Walken2.raw", "Z1.raw", "Z2.raw"*/

    ];

    //var SOUND_BASE_URL = HIFI_PUBLIC_BUCKET + "sounds/Cocktail+Party+Snippets/Raws/";
    var SOUND_BASE_URL = HIFI_PUBLIC_BUCKET + "sounds/EnvironmentalBackgroundsForLooping/";

    for (var i = 0; i < sound_filenames.length; i++) {
        var soundURL = SOUND_BASE_URL + sound_filenames[i];
        print("loading sound:" + soundURL);
        sounds.push(SoundCache.getSound(soundURL));
    }
}

var sounds = [];
loadSounds();


function playRandomSound() {
    if (true || !Agent.isPlayingAvatarSound) {
        var whichSound = Math.floor((Math.random() * sounds.length));
        print("Agent.playAvatarSound()");
        Agent.playAvatarSound(sounds[whichSound]);
    }
}

var CHANCE_OF_SOUND = 0.5;

function handleTalking() {
    if (Math.random() < CHANCE_OF_SOUND) {
        playRandomSound();
    }
}


function updateBehavior(deltaTime) {
    print("updateBehavior");
    handleTalking();
}

Script.update.connect(updateBehavior);
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 376756d41399521c42bc52d6d8a714df6c0e3c76 available at: https://gist.github.com/ee2fb383c3f57f670876ad69cf9f59cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8523-376756d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8523-376756d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e26916b65bc06b3c5fdf96dfe05a304ea041501 available at: https://gist.github.com/ee2fb383c3f57f670876ad69cf9f59cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8523-6e26916.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8523-6e26916.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

Sanity check - I can hear sounds in standard home scene from audioInjector and UI noises.

Try 1 - created assignment script in empty domain - being of light appears at 0,0,0 and nothing heard.  AC log shows endless;

[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:00] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< Agent.playAvatarSound()
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior
[08/26 14:44:01] [DEBUG] [1404] [agent] script:print()<< updateBehavior

Try 2 - ran this in standard home where audio injector script is running.  This produced a second being of light over the audioInjector one at 0,0,0 - I hear sounds inside HF home but nothing at 0,0,0

Interface log shows nothing other than hits for adding new being of light and injector.

**Pull request merged**
