### PR TITLE
Fix touch controller button handling when Oculus remote is paired (MASTER)

### PR DESCRIPTION
**Pull request by jherico**
Master branch version of #13387

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10611/HighFidelity-Beta-PR13388-197fb46.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10611/HighFidelity-Beta-PR13388-197fb46.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10611/HighFidelity-Beta-Interface-PR13388-197fb46.dmg

**Comment by sethalves** [comment]
these changes were QA'ed in https://github.com/highfidelity/hifi/pull/13387

**Pull request merged**
