### PR TITLE
 Adding showHidden properties to file dialogs to allow for showing hidden files/folders

### PR DESCRIPTION
**Pull request by wayne-chen**
Fixing file dialog in QML to allow for displaying hidden files/folders.
https://highfidelity.manuscript.com/f/cases/14515/#

### CODE REVIEW

**Comment by wayne-chen** [comment]
To test:

Compile Interface project (if not already done)
Launch Interface
Log in with High Fidelity credentials in Menu->Login/Sign Up
Go to Marketplace
Click My Purchases
Type in passphrase for account (if prompted)
In the "Hmm, your keys are different" screen, click "LOCATE MY KEYS"
Hidden files/folders should be displayed (i.e. %APPDATA% folder in Windows 10)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10006/HighFidelity-Beta-PR13213-1774b401c805257e2662bdbf462f7a065d93326e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10006/HighFidelity-Beta-Interface-PR13213-1774b401c805257e2662bdbf462f7a065d93326e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10006/HighFidelity-Beta-PR13213-1774b401c805257e2662bdbf462f7a065d93326e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10006/HighFidelity-Beta-Interface-PR13213-1774b401c805257e2662bdbf462f7a065d93326e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10008/HighFidelity-Beta-PR13213-e3414c320ec6b6bdf7a5ac974c6c820b27f43f4f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10008/HighFidelity-Beta-PR13213-e3414c320ec6b6bdf7a5ac974c6c820b27f43f4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10008/HighFidelity-Beta-Interface-PR13213-e3414c320ec6b6bdf7a5ac974c6c820b27f43f4f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10008/HighFidelity-Beta-PR13213-e3414c320ec6b6bdf7a5ac974c6c820b27f43f4f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10008/HighFidelity-Beta-Interface-PR13213-e3414c320ec6b6bdf7a5ac974c6c820b27f43f4f.exe

**Comment by wayne-chen** [comment]
The reason why I hard-coded showHidden to be true was that there is currently a bug in the FolderListModel QML object.  This is not solved in Qt 5.11, as I had tested it earlier with the updated object.  It seems like with a configurable showHidden property using FolderListModel, there is only an update in one direction (i.e. toggling showHidden to be true, but if setting back to false, is impossible).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10045/HighFidelity-Beta-PR13213-345138f4ff98fb1de79fd2eab3a3e55b48bdefbd.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10045/HighFidelity-Beta-PR13213-345138f4ff98fb1de79fd2eab3a3e55b48bdefbd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10045/HighFidelity-Beta-Interface-PR13213-345138f4ff98fb1de79fd2eab3a3e55b48bdefbd.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10217/HighFidelity-Beta-PR13213-345138f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10217/HighFidelity-Beta-PR13213-345138f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10217/HighFidelity-Beta-Interface-PR13213-345138f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10217/HighFidelity-Beta-PR13213-345138f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10217/HighFidelity-Beta-Interface-PR13213-345138f.exe

**Comment by qligmaloney** [comment]
Currently testing Desktop and HMD

**Comment by qligmaloney** [comment]
PASS @conklin94122 Hidden folders (application support/App data) display. Unable to test on Android Interface as importing scripts functionality does not exist

**Pull request merged**
