### PR TITLE
Draggable numbers - RC76 fixes to master

### PR DESCRIPTION
**Pull request by dback2**
PRs #14448 and #14456 into master

Pre-Merge Test Plan:
Run test plans from both PRs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15505/HighFidelity-Beta-PR14495-e5f4f67.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15505/HighFidelity-Beta-PR14495-e5f4f67.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15505/HighFidelity-Beta-Interface-PR14495-e5f4f67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15505/HighFidelity-Beta-PR14495-e5f4f67.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15505/HighFidelity-Beta-Interface-PR14495-e5f4f67.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15527/HighFidelity-Beta-PR14495-ec4726a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15527/HighFidelity-Beta-PR14495-ec4726a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15527/HighFidelity-Beta-Interface-PR14495-ec4726a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15527/HighFidelity-Beta-PR14495-ec4726a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15584/HighFidelity-Beta-PR14495-a05e831.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15584/HighFidelity-Beta-PR14495-a05e831.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15584/HighFidelity-Beta-Interface-PR14495-a05e831.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15584/HighFidelity-Beta-PR14495-a05e831.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15584/HighFidelity-Beta-Interface-PR14495-a05e831.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass

PR retains passes from prior pro

**Pull request merged**
