### PR TITLE
fix collision of isPlaying property and slot for AudioInjectors

### PR DESCRIPTION
**Pull request by birarda**
- rename the isPlaying property to playing so avoid a collision with slot isPlaying
- change usage of isPlaying property in archived scripts to use renamed property

### CODE REVIEW

**Comment by birarda** [comment]
**Test Notes**

In both master and for this PR, run 

https://gist.githubusercontent.com/birarda/fdd6dbc6b59241aaf7abeb2aad7b51aa/raw/fbb17fcfd60c45da7ae79ea9582229b5d991e8e2/isPlayingTest.js 

as a client script in Interface. 

On master, you should expect to see an exception that isPlaying is not a function.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64720444cf4527f10eebb360018269af366cb72c available at: https://gist.github.com/4a1eed05e405dd2b34c79a901948f670<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7968.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7968.dmg

**Comment by OmegaHeron** [comment]
If log output from test script is what's expected  QA Pass.  I'm unclear if its output should be what's seen or not @birarda can confirm.

Test Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**
Standard tests pass.
Master behaves as described throwing errors.

This PR endless loop of... playing: true - start engines, already playing, restarting  - I think that's correct.

[05/25 20:31:26] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:26] [DEBUG] script:print()<< playing:true
[05/25 20:31:26] [DEBUG] script:print()<< Start engines
[05/25 20:31:26] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:26] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:26] [DEBUG] script:print()<< playing:true
[05/25 20:31:26] [DEBUG] script:print()<< Start engines
[05/25 20:31:26] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:26] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:26] [DEBUG] script:print()<< playing:true
[05/25 20:31:26] [DEBUG] script:print()<< Start engines
[05/25 20:31:26] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:26] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:26] [DEBUG] script:print()<< playing:true
[05/25 20:31:26] [DEBUG] script:print()<< Start engines
[05/25 20:31:26] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:26] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:26] [DEBUG] script:print()<< playing:true
[05/25 20:31:27] [DEBUG] script:print()<< Start engines
[05/25 20:31:27] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:27] [DEBUG] script:print()<< isPlaying(): true
[05/25 20:31:27] [DEBUG] script:print()<< playing:true
[05/25 20:31:27] [DEBUG] script:print()<< Start engines
[05/25 20:31:27] [DEBUG] script:print()<< Already playing, restarting
[05/25 20:31:27] [DEBUG] script:print()<< isPlaying(): true

**Comment by birarda** [comment]
That output is good! QA Approved. Thanks @OmegaHeron.

**Pull request merged**
