### PR TITLE
Default skybox change

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58e292449a5c1073baab71e2ea16aff12aee25b7 available at: https://gist.github.com/68c388c72caeffcb9a3e8fbc4f93bb28<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-58e2924.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-58e2924.dmg

**Comment by ZappoMan** [comment]
Do we want to allow content creators to use the old stars if they really want it? does that mean we need a zone skybox property?

**Comment by huffman** [comment]
We could do that or provide a similar stars shader in the marketplace.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 942cdee6c9851c778346d8a39a9dfcdd1405730a available at: https://gist.github.com/68c388c72caeffcb9a3e8fbc4f93bb28<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-942cdee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-942cdee.dmg

**Comment by huffman** [comment]
Alan created an alternative that he will be uploading to the marketplace. Once that is up I can remove the DNM on this (along with a little cleanup).

**Comment by huffman** [comment]
A marketplace item will be added that matches the old skybox. I will remove the DNM on this PR when that is in.

**Comment by huffman** [comment]
This PR replaces the default starfield skybox. The new skybox looks like this: https://github.com/huffman/hifi/blob/942cdee6c9851c778346d8a39a9dfcdd1405730a/interface/resources/images/Default-Sky-9-cubemap.jpg

To test:

1. When you first load up interface, you should see a new default skybox instead of the star field.
1. When connecting to your home server with the default content you should see the usual mountainscape skybox replace the default skybox once it loads.
1. When not connected to a server you should see the new default skybox (you can try connecting to a bogus ip like `0.0.0.0`)
1. Try jumping around to servers with different skyboxes to make sure it behaves as expected.

**Comment by SkimiMission** [comment]
## QA Pass

- [Ok] When you first load up interface, you should see a new default skybox instead of the star field.
- [Ok] When connecting to your home server with the default content you should see the usual mountainscape skybox replace the default skybox once it loads.
- [Ok] When not connected to a server you should see the new default skybox (you can try connecting to a bogus ip like 0.0.0.0)
- [Ok] Try jumping around to servers with different skyboxes to make sure it behaves as expected.

It behaves as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d909f92fd3eb8c4ec06662abd8d5640ce7b4d972 available at: https://gist.github.com/68c388c72caeffcb9a3e8fbc4f93bb28<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-d909f92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-d909f92.dmg

**Comment by huffman** [comment]
@SkimiMission Can you retest this? I made several updates and made a change to the test plan.

**Comment by SkimiMission** [comment]
## QA Pass

@huffman Everything works as expected. Even toggle on/off under Developer > Render > Default Skybox.

Just one thing I've noticed, but maybe that's how it should be. With the standard blue alien avatar, the new deep dark blue horizon looks really cool. But if I load my fuse/maximo avatar, the skin of the body looks very 'plastic'. Just to mention it:

hifi-snap-by-skimi-on-2016-08-08_19-59-03

hifi-snap-by-skimi-on-2016-08-08_20-00-34

**Comment by huffman** [comment]
@SkimiMission Does that same avatar's skin look plastic with other skyboxes?

**Comment by SkimiMission** [comment]
No, for example, first pic is made with the old 'Stars' skybox, the second with skybox is also used at playa. Guess it is from @jherico 

hifi-snap-by-skimi-on-2016-08-08_20-20-33

hifi-snap-by-skimi-on-2016-08-08_20-20-55

**Comment by huffman** [comment]
@SkimiMission What about with the home content?

**Comment by SkimiMission** [comment]
@huffman When the home_zone_skyboxis loaded, it looks fine. With the new default skybox you can see the difference also on any glossy surface, like the glass of the windows.

hifi-snap-by-skimi-on-2016-08-08_20-30-28

hifi-snap-by-skimi-on-2016-08-08_20-33-31

**Comment by huffman** [comment]
@SkimiMission Ok, what I can do is decrease the ambient lighting setting which will help, but after talking with @AlanZimmerman it sounds like it's likely to be because of the roughness/hardness values for your avatar material. Are you able to adjust that in fuse?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d11f13f60d39faa53dfc6ab9daffdc278bb2df8 available at: https://gist.github.com/68c388c72caeffcb9a3e8fbc4f93bb28<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-1d11f13.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-1d11f13.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ee3f680c91b1b3e4324bc92b1a59ac18fbe7971 available at: https://gist.github.com/68c388c72caeffcb9a3e8fbc4f93bb28<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-8ee3f68.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8365-8ee3f68.dmg

**Comment by SkimiMission** [comment]
## QA Pass

@huffman Works fine and looks better with the new ambient intensity for me.

**Comment by huffman** [comment]
@SkimiMission Great, thanks for testing!

**Pull request merged**
