### PR TITLE
Selfie Stick Script

### PR DESCRIPTION
**Pull request by fayeli**
This script turns your interface into a camera that can be used to stream events.
- It changes your avatar to the camera eye 
- It includes a selfie stick that lets other control the camera by grabbing and moving the selfie stick

Usage:
1) Run selfieStick.js in desktop mode
2) You're now in "free movement mode" which means you can move around the camera with first person controls (WASD + mouse)
3) Hit space bar toggle you to give away free movement. You may no longer control the camera with your keyboard, but others around you can grab the selfie stick under you and move your camera around.
4) When you end the script, it should put you back to your original avatar.

Test Plan:
- requires 2+ testers. One runs selfieStick.js in desktop mode following Usage instructions above, other tester can try grabbing and moving the camera via hand controller.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 97d75e654e22cf732d104334e66357bb99b43054 available at: https://gist.github.com/c183526d06a1abc5b718bb2cc552acce<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10137-97d75e6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10137-97d75e6.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
@fayeli Would it be good to use...

Menu.setIsOptionChecked("Enable avatar collisions", 0);

**Comment by Nex-Pro** [comment]
@fayeli  Script isn't in the build.

**Comment by Nex-Pro** [comment]
I copied source and ran locally.

**Comment by Nex-Pro** [comment]
Crashed on closing script

**Comment by Nex-Pro** [comment]
### FAIL

Crashes on reloading or killing script.
If an attempt to kill script is made the script is loaded on restart.
Had to edit interface.json

### CALL STACK
>	KernelBase.dll!00007ff8fc1a7788()	Unknown
 	msvcr120.dll!00007ff8e7f1ef63()	Unknown
 	interface.exe!handleSignal(int signal) Line 109	C++
 	[External Code]	
 	Qt5Core.dll!0000000070f50aad()	Unknown
 	Qt5Core.dll!0000000070f509b5()	Unknown
 	interface.exe!AvatarData::setJointMappingsFromNetworkReply() Line 1621	C++
 	Qt5Core.dll!0000000071015454()	Unknown
 	Qt5Core.dll!00000000710141aa()	Unknown
 	Qt5Widgets.dll!00000000716b7d12()	Unknown
 	Qt5Widgets.dll!00000000716b6c2f()	Unknown
 	Qt5Core.dll!0000000070fef689()	Unknown
 	Qt5Core.dll!0000000070ff140e()	Unknown
 	qwindows.dll!00007ff8e61529df()	Unknown
 	Qt5Core.dll!0000000071036a65()	Unknown
 	[External Code]	
 	Qt5Core.dll!00000000710361d9()	Unknown
 	qwindows.dll!00007ff8e61529b9()	Unknown
 	Qt5Core.dll!0000000070febf91()	Unknown
 	Qt5Core.dll!0000000070fee477()	Unknown
 	interface.exe!main(int argc, const char * * argv) Line 250	C++
 	[External Code]	
Bug splats sent.

Also stick becomes detached from camera thingy.

Camera thingy wasn't moved by stick.

**Comment by fayeli** [comment]
Thanks for the test @Nex-Pro ! The script is in script-archive/selfieStick.js. I wonder if the issue we saw here has to do with the way it was ran. Looking into in right now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3caea886413f63e6835ece7c3f3858d4f05c3f0e available at: https://gist.github.com/c183526d06a1abc5b718bb2cc552acce<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10137-3caea88.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10137-3caea88.dmg

**Pull request merged**
