### PR TITLE
Update teleport destination model and alphas of parabolas

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12547/HighFidelity-Beta-PR13917-ab03575.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12547/HighFidelity-Beta-Interface-PR13917-ab03575.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12575/HighFidelity-Beta-PR13917-ab03575.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12575/HighFidelity-Beta-Interface-PR13917-ab03575.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12575/HighFidelity-Beta-PR13917-ab03575.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12575/HighFidelity-Beta-Interface-PR13917-ab03575.dmg

**Comment by ctrlaltdavid** [comment]
Changes have been included in: https://github.com/highfidelity/hifi/pull/14075

**Pull request closed without merging**
