### PR TITLE
expose MyAvatar.leftHandPosition and MyAvatar.rightHandPosition to JS

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3900a954b7e9c1db9a17a0a867a24b73ecf573c available at: https://gist.github.com/6ac4d849c0198b14ea38<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6146.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6146.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68a2985b7abedd08d49c1bfb73abfeae4dca1c83 available at: https://gist.github.com/6ac4d849c0198b14ea38<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6146.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6146.dmg

**Comment by hyperlogic** [comment]
Too late now, but this code will have threading issues with the main thread.

   * If script is calling this while you are adding or removing controllers, it could lead to reading memory that has been freed or garbage.
   * Updating palm data and their positions is not attomic, so it is quite possible for script to see frame "tearing" i.e. some values are from frame t0 and some values are from frame t1.

**Comment by ZappoMan** [comment]
Great comments Tony. I agree. This particular PR was just moving existing code in master from one class to another. The existing master branch code has all the problems you highlight. I've added a card to our sprint board to make all these controller related accessors thread safe.

**Pull request merged**
