### PR TITLE
Made the output audio listview dynamically change height base on content size

### PR DESCRIPTION
**Pull request by druiz17**
Made the output audio listview dynamically change height base on content size. If content height passes the bottom of the tablet. set listview height the to the bottom of the tablet.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- No functional changes. smoke test Audio Menu.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1415/HighFidelity-Beta-PR10906-1ac415aa14d3be3b9782aa813690b7dfe5ff148c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1415/HighFidelity-Beta-PR10906-1ac415aa14d3be3b9782aa813690b7dfe5ff148c.exe

**Comment by Nex-Pro** [comment]
Will test when ready

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### PASS

Saw 6 outputs listed

In addition plugging and removing USB audio devices updated the device list automatically.

**Pull request merged**
