### PR TITLE
Hand Azimuth improvement

### PR DESCRIPTION
**Pull request by amantley**
This pr puts the hand azimuth computation in shoulder space.  That means that we can now sit down with hmd lean recenter off and have the hands behind the origin of MyAvatar without messing up the azimuth computation.  I think it also look slightly better when walking and leaning sideways.

### Test Plan:
1. open interface and go to vr mode.
2. open settings/controls/Avatar Lean Behavior and set it to Disabled
3. Sit down on the floor or a chair in real life.  Your avatar knees should bend and you will be sitting behind the location of your feet.
4. rotate your arms to the right and left and verify that the torso follows the arms

https://highfidelity.manuscript.com/f/cases/19436/Bug-fix-for-shoulder-turning-with-HMD-lean-recenter-off

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14062/HighFidelity-Beta-PR14230-83ec346.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14062/HighFidelity-Beta-Interface-PR14230-83ec346.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14092/HighFidelity-Beta-PR14230-8f4fafe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14092/HighFidelity-Beta-Interface-PR14230-8f4fafe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14092/HighFidelity-Beta-PR14230-8f4fafe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14092/HighFidelity-Beta-Interface-PR14230-8f4fafe.exe

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/19436/Bug-fix-for-shoulder-turning-with-HMD-lean-recenter-off

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14333/HighFidelity-Beta-PR14230-5063d0b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14333/HighFidelity-Beta-PR14230-5063d0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14333/HighFidelity-Beta-Interface-PR14230-5063d0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14333/HighFidelity-Beta-PR14230-5063d0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14333/HighFidelity-Beta-Interface-PR14230-5063d0b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14385/HighFidelity-Beta-PR14230-7fe53d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14385/HighFidelity-Beta-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14385/HighFidelity-Beta-Interface-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14385/HighFidelity-Beta-PR14230-7fe53d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14385/HighFidelity-Beta-Interface-PR14230-7fe53d4.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14448/HighFidelity-Beta-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14448/HighFidelity-Beta-Interface-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14448/HighFidelity-Beta-PR14230-7fe53d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14448/HighFidelity-Beta-Interface-PR14230-7fe53d4.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15048/HighFidelity-Beta-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15048/HighFidelity-Beta-Interface-PR14230-7fe53d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15048/HighFidelity-Beta-PR14230-7fe53d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15048/HighFidelity-Beta-Interface-PR14230-7fe53d4.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
