### PR TITLE
DNM - Tutorial testing

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1099/HighFidelity-Beta-PR10818-98dc169727eb2ddb20ed921d5501b01fe6642787.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1099/HighFidelity-Beta-PR10818-98dc169727eb2ddb20ed921d5501b01fe6642787.exe

**Comment by huffman** [comment]
To test:

 1. Go through the tutorial, make sure everything looks and works correctly.
 1. Confirm that the tutorial portal in the garden is no longer there.
 1. Explore the domain to confirm that everything else looks the same as before
    1. Go to `/`
    1. Go to `/garden`
 1. Everything should load fairly quickly

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1104/HighFidelity-Beta-PR10818-03291054e92f17ca984a511cb5d92e746ff52144.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1104/HighFidelity-Beta-PR10818-03291054e92f17ca984a511cb5d92e746ff52144.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

Go through the tutorial, make sure everything looks and works correctly. **Pass**
Confirm that the tutorial portal in the garden is no longer there. **Pass**
Explore the domain to confirm that everything else looks the same as before **Pass**
Go to / **Pass**
Go to /garden **Pass**
Everything should load fairly quickly **Pass, everything would load in the sandbox domain within 5 seconds**

**Comment by huffman** [comment]
Thanks @YuppyPlays !

**Pull request closed without merging**
