### PR TITLE
Merge latest in master

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 650e8a54afc3b12d4a485b24125027c98850174d available at: https://gist.github.com/d5c585070a082ee41ff7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: edf963ab8fffaa1cd81974ccadf8bef1c51e8095 available at: https://gist.github.com/d5c585070a082ee41ff7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d00393eff0e280bc2cbaad5bf3073d832101749 available at: https://gist.github.com/d5c585070a082ee41ff7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.dmg

**Comment by PhilipRosedale** [comment]
What is this PR for?  Can it have a descriptive name?

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf6d5af16d37469477d6fe82e11e345421c71646 available at: https://gist.github.com/d5c585070a082ee41ff7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.dmg

**Comment by AndrewMeadows** [comment]
This is a merge into upstream/team-teaching from upstream/master -- so this is in reverse order compared to most of our other PR's.  So... maybe team-teaching is maintaining their own collaborative branch in upstream.  If so, I'll let someone from team-teaching merge this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f8008e5b5b299d52fb5a232a401b484ce6b1d51 available at: https://gist.github.com/d5c585070a082ee41ff7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4892.dmg

**Comment by huffman** [comment]
@PhilipRosedale @AndrewMeadows Sorry about that.  Yes, Andrew is right, this was a PR to pull the latest into the team-teaching branch.  The team-teaching branch is for testing and merging team teaching work without polluting the master branch.

In any case, I think we are going to hold off on merging the latest and close this branch.

**Pull request closed without merging**
