### PR TITLE
html drill-down user story

### PR DESCRIPTION
**Pull request by howard-stearns**
Current behavior out of the box, but if you change AddressBarDialog.qml to point to a private metaverse that is running the next-gen server, you can also change the useHTML property to true, and it will use the drill-down html user story cards from the private metaverse server.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f415abd6b36fa279ce26137e3f901fec611787f available at: https://gist.github.com/4ee72eef61bce648e1dfba45a05d26aa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-0f415ab.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-0f415ab.dmg

**Comment by howard-stearns** [comment]
Don't bother to qatesters this. The customization relationship between different servers is too hard to explain.

**Comment by howard-stearns** [comment]
note to reviewer: persisting the "open feed after" checkbox was complicated by https://highfidelity.fogbugz.com/f/cases/1514/Settings-getValue-of-boolean-gives-string-in-NEXT-session

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e8722ccf549a1f2b48c93d3dfc8d2c06787e773 available at: https://gist.github.com/4ee72eef61bce648e1dfba45a05d26aa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-5e8722c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-5e8722c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aab3b83ad9a138e3356a4851fa9758ec12d74562 available at: https://gist.github.com/4ee72eef61bce648e1dfba45a05d26aa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-aab3b83.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8463-aab3b83.dmg

**Comment by davidkelly** [comment]
Works for me.  I switched it to point to my local metaverse server, and to display html.  It looks right.  Of course, the styling in the html is an abomination, but that is to be expected since I did it.  Lets merge!

**Pull request merged**
