### PR TITLE
BUGZ-1171: Fix audio output not working (alternate fix)

### PR DESCRIPTION
**Pull request by kencooke**
Attempt to fix https://highfidelity.atlassian.net/browse/BUGZ-1171 
without regression of the bug in https://highfidelity.atlassian.net/browse/BUGZ-395

On a system with the 8-channel bug, attempt to use native sample rate with channels forced to 2 or 1. This is effectively the same workaround as https://github.com/highfidelity/hifi/pull/16027

Avoid enumerating all formats when the native format fails, to prevent crashing when AirPods have been disconnected.

### CODE REVIEW

**Comment by kencooke** [comment]
Can @ctrlaltdavid, @ZappoMan (or someone who can reproduce the 8-channel audio failure) verify that this also solves the problem?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20757/HighFidelity-Beta-PR16029-86adc60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20757/HighFidelity-Beta-Interface-PR16029-86adc60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20757/HighFidelity-Beta-PR16029-86adc60.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20757/HighFidelity-Beta-Interface-PR16029-86adc60.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20757/HighFidelity-Beta-PR16029-86adc60.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20757/HighFidelity-Quest-Beta-PR16029-86adc60.apk)

**Pull request merged**
