### PR TITLE
treat children of avatars and children of entities differently until velocity handling is fixed

### PR DESCRIPTION
**Pull request by sethalves**
- make spinning things work again while still keeping equipped things from drifting out of the avatar's hand

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- go to playa and make sure the high-fidelity neon signs are still spinning
- do an equipping (parenting) grab on something, and while maintaining the grab, move (walk) the avatar.  make sure the thing stays firmly in hand
- make sure that examples/moving-platform.js works the same way it does in master

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3890a71433ba67a8cfd9f09a0d738f4c5f3313e8 available at: https://gist.github.com/c5b0cd5405abddb0ff227705288a809f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7631.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7631.dmg

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/110577420589354

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2aa3e5d418b3180ffd1a57597194b705996f7e66 available at: https://gist.github.com/c5b0cd5405abddb0ff227705288a809f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7631.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7631.dmg

**Comment by Nex-Pro** [comment]
Tested this on WIN10 64bit 16gb ram. GTX770
Parented a cube near my head. Moved around and the cube remained with me.
Also ran the moving platform script. Cube remained near my head as it should.
Rotating signs worked well apart from some minor glitches when changing view direction.

**Pull request merged**
