### PR TITLE
Change tablet model's screen

### PR DESCRIPTION
**Pull request by AlanZimmerman**
Changed the texture for the model's screen to say: "Loading... If nothing happens shortly, re-open tablet"

The screen should not be visible in normal use, but if an issue occurs that causes the tablet's QML "screen" to not be visible, the new message should help guide users to resolving the issue. 

Test plan:

Download and run PR Interface. Reload your content (Edit -> Reload Content) When opening the tablet, tablet model should appear at the correct scale and orientation as it does in the stable release. The QML screen of the tablet should not be intersecting or coplanar (z-fighting) with any of the mesh's geometry.

Performance smoke test.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4256/HighFidelity-Beta-PR11624-6a2ee8c6324ffda664e6f2fe86b1a9a16ecbaedb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4256/HighFidelity-Beta-PR11624-6a2ee8c6324ffda664e6f2fe86b1a9a16ecbaedb.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Download and run PR Interface. Reload your content (Edit -> Reload Content) When opening the tablet, tablet model should appear at the correct scale and orientation as it does in the stable release. The QML screen of the tablet should not be intersecting or coplanar (z-fighting) with any of the mesh's geometry. | Pass
Performance smoke test. | Pass

All looks good to me.

**Pull request merged**
