### PR TITLE
Raypick avatars

### PR DESCRIPTION
**Pull request by sethalves**
- new javascript call exposed: AvatarManager.findRayIntersection which is like Entities.findRayIntersection but returns an avatarID rather than an entityID

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- experiment with AvatarManager.findRayIntersection which takes the same sort of pickRay object as the Entities version
- ready hand controllers
- import this and try shooting at other avatars: http://headache.hungry.com/~seth/hifi/raygun/raygun.json

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52d017ac743a6f3eeba49e6d8c9c904a19814494 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52d017ac743a6f3eeba49e6d8c9c904a19814494 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52d017ac743a6f3eeba49e6d8c9c904a19814494 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by thoys** [comment]
## QA Testing report

- Used hydra's to test.
- Imported/Equipped rayGun
- First it didn't work got warnings `[06/29 16:53:19] [WARNING] Entities.findRayIntersectionBlocking() is obsolete, use Entities.findRayIntersection() instead.`
- Then I re-uploaded the raygunscript: https://gist.githubusercontent.com/thoys/b2b5b3d43af9c35b3da001426fa18e97/raw/d1e1fd30f25a831e4b337b4976d8c41919c3200b/rayGun.js so I could edit it and figured the messages made no sense, since `Entities.findRayIntersectionBlocking()` was not present in any of these files.
- The re-uploaded version worked, so it must have been a cached version.
- I loaded another thoys on my laptop and managed to shoot him, it showed greenish transparant spheres at the hitpoints.

### QA Successful :+1: 

P.S. small minor non-breaking quality issue. I was able to shoot him 15 cm above his head, and wasn't able to hit his feet. I think this is acceptable for now, but should be dealt with in the future.

**Comment by sethalves** [comment]
Let's not merge this yet -- I want to see if it's possible to pick against the meshes rather than the capsules.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 03ed36cf3303b41c63d94955b2532da28bb477f4 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9114ebb548aa2384fb16584c197704a272483511 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3dbe5d9c43e23a84392442de5a036a4c0030b8a available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f9c7b6ea5cb5df7392777a9976a53b0e9e2480a available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52a6a1c65ef1f5a2125226bce1d9e3e997e26d80 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6786a07ac2ed839a4fb6021e3b8bbc6f804a58c0 available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11542aeca2b9b01b6e2d6fb9ec58abd8c41d1dcb available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5c69e55475dfdd5386b12f7b26ad784a4db34a7c available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85cc5f89560ed937a0184880fc620c69193fb91c available at: https://gist.github.com/09f0c2b337e7de19cb80abd2b0f9d11a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158-85cc5f8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8158-85cc5f8.dmg

**Comment by thoys** [comment]
## QA Testing report

Tested with @kevinmthomasse , was able to hit his T-pose with the raygun as expected.

QA passed :+1:

**Pull request merged**
