### PR TITLE
MS14758: Fix avatar reset when gifting worn avatar

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14758](https://highfidelity.manuscript.com/f/cases/14758/Avatar-URL-is-not-removed-when-user-gifts-an-avatar-they-are-wearing).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan

### Prerequisites
- A Wallet set up
- You're logged in to HiFi and your wallet is auth'd
- You have a connection to whom you can send a gift.

### Tests
1. Open Marketplace and filter for Avatars
2. Select the Buy/Get button for an avatar
3. Wear recently purchased avatar
4. Select "My Purchases" link on Marketplace homepage
5. Select the Context Menu (...) button on the card of current/recently purchased avatar
6. Select "Gift" button
7. Select "Confirm" button on "Change to Default Avatar" popup
8. Send avatar to another user
9. Reload content (Edit>Reload Content)
10. Verify that your avatar is still the default "woody" avatar.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9499/HighFidelity-Beta-PR13101-e48d39ec38c3012b019e928bf05718dc23d9ba1d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9499/HighFidelity-Beta-Interface-PR13101-e48d39ec38c3012b019e928bf05718dc23d9ba1d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9499/HighFidelity-Beta-PR13101-e48d39ec38c3012b019e928bf05718dc23d9ba1d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9499/HighFidelity-Beta-Interface-PR13101-e48d39ec38c3012b019e928bf05718dc23d9ba1d.exe

**Comment by howard-stearns** [comment]
I'm testing this....

**Pull request merged**
