### PR TITLE
Threaded Rendering - Alternative Build

### PR DESCRIPTION
**Pull request by jherico**
Alternate build of #8325 for A/B testing on Vive.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6bf81bcce44df3a8b7ecc5bf13b481ebf2a5223 available at: https://gist.github.com/0bde112923671e00e78d2fdca94659cf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8394-a6bf81b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8394-a6bf81b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ac17a381506369401091d5e250083e62611c0d9b available at: https://gist.github.com/0bde112923671e00e78d2fdca94659cf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8394-ac17a38.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8394-ac17a38.dmg

**Comment by SkimiMission** [comment]
@jherico , here are my results with this build.

- dev-demo was perfect, ~90 fps. 
- dev-playa while looking towards lights it falls down to ~60 fps, but I felt it less stressful as in the other build #8325, and hat less black frames even the low fps. 
- localhost it was hard flickering with around ~50 fbs, but also not so many black frames. 

So I would give a 'thumbs up' for this build.

**Comment by ZappoMan** [comment]
@SkimiMission - how does this build compare to the current beta for your machine for these three locations?

**Comment by SkimiMission** [comment]
@ZappoMan Compared to the beta is the performance of build # 8394 much better. I've noticed it esp. on dev-playa, higher fps and less dropped frames. dev-demo is okay even in beta. localhost is always hard, but smoother with this build. Hope that helps.

**Pull request closed without merging**
