### PR TITLE
Add and Update CellScience Environment

### PR DESCRIPTION
**Pull request by imgntn**
This PR adds the scripts for the cell science environment to the repository.  

**NOTE: This script will clear content where you run it**

To test: 

1. In an empty domain, go to running scripts and import this script from url: http://hifi-content.s3.amazonaws.com/DomainContent/CellScience/importCellScience.js
2. Stop the importCellScience.js script.
3. From the Scripts section of your server Settings page, add this script: http://hifi-content.s3.amazonaws.com/DomainContent/CellScience/motorProteinControllerAC.js 
4. Click Save and Restart.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e036d3e2cb349dad50482eb70a574ea1b8353ee available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 514edee3f13c39c3185ff0b8b339fa06fdb8f4e2 available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d0eb79115d397f0b5fd5f058bdd40631c48e903 available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fb6fcab078bbdb881eb2a0d3a557b4b2199c3469 available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e43821a52a9ea31ea48560965ae1a1016c3daaa available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
I have ran the test as described by @imgntn and I have cellscience running fine on my localhost. I am also running the AC script and it works without issue too. I have clicked all the buttons on the bottom and they work just fine. All testing parameters seem to pass to me.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bad6a15f092ff50ab97a2fced3b05580133e30a7 available at: https://gist.github.com/f1b74f2cd020d776e966<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6992.dmg

**Pull request merged**
