### PR TITLE
use correct jount count for other avatar last sent resize

### PR DESCRIPTION
**Pull request by birarda**
Previously when looking at the joint data for avatar B we were resizing the last sent joint data to the number of joints for avatar A. This change corrects that so that we resized to the number of joints we currently have for avatar B.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9171/HighFidelity-Beta-PR12998-eeed5192b5919e8081dc6d4aee3dc6ea9f9e2d93.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9171/HighFidelity-Beta-Interface-PR12998-eeed5192b5919e8081dc6d4aee3dc6ea9f9e2d93.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9171/HighFidelity-Beta-PR12998-eeed5192b5919e8081dc6d4aee3dc6ea9f9e2d93.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9171/HighFidelity-Beta-Interface-PR12998-eeed5192b5919e8081dc6d4aee3dc6ea9f9e2d93.exe

**Comment by birarda** [comment]
Closing this so it can be brought back in 66.1 merge back

**Pull request closed without merging**
