### PR TITLE
BUGZ-657; BUGZ-713: Add a copy of the most default JS files because lots of system scripts depend on them being in the default scripts location

### PR DESCRIPTION
**Pull request by zfox23**
[BUGZ-657](https://highfidelity.atlassian.net/browse/BUGZ-657)
[BUGZ-713](https://highfidelity.atlassian.net/browse/BUGZ-713)

The dependency tree between system scripts is very very tangled. I spent a long time trying to figure it out, but I couldn't, so I'm giving up and just copying most of the scripts.

[I made this ticket so we can improve this.](https://highfidelity.atlassian.net/browse/BUGZ-801)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20029/HighFidelity-Beta-PR15795-7a4aa1e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20029/HighFidelity-Beta-Interface-PR15795-7a4aa1e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20029/HighFidelity-Beta-PR15795-7a4aa1e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20029/HighFidelity-Beta-Interface-PR15795-7a4aa1e.exe

**Comment by ZappoMan** [comment]
test this please

**Comment by ZappoMan** [comment]
This is great @zfox23 - thanks for jumping on this. One thought, that I'm sure you had, is it's a bummer to have to duplicate all the scripts into two locations. I wonder if there's a way to do this with copying steps in the installer builders?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20033/HighFidelity-Beta-PR15795-7a4aa1e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20033/HighFidelity-Beta-Interface-PR15795-7a4aa1e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20033/HighFidelity-Beta-PR15795-7a4aa1e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20033/HighFidelity-Beta-Interface-PR15795-7a4aa1e.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20033/HighFidelity-Beta-PR15795-7a4aa1e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20033/HighFidelity-Quest-Beta-PR15795-7a4aa1e.apk)

**Comment by zfox23** [comment]
I just realized that this isn't the complete fix :( I need to spend some more time with this.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20044/HighFidelity-Beta-PR15795-8fdfdba.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20044/HighFidelity-Quest-Beta-PR15795-8fdfdba.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20044/HighFidelity-Beta-PR15795-8fdfdba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20044/HighFidelity-Beta-Interface-PR15795-8fdfdba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20044/HighFidelity-Beta-PR15795-8fdfdba.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20044/HighFidelity-Beta-Interface-PR15795-8fdfdba.exe

**Comment by jherico** [comment]
why are there .vscode files in this PR?

**Comment by zfox23** [comment]
@jherico I'm not done with this yet (it's DNM)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20054/HighFidelity-Beta-PR15795-d49205b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20054/HighFidelity-Beta-Interface-PR15795-d49205b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20054/HighFidelity-Beta-PR15795-d49205b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20054/HighFidelity-Beta-Interface-PR15795-d49205b.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20054/HighFidelity-Beta-PR15795-d49205b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20054/HighFidelity-Quest-Beta-PR15795-d49205b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20067/HighFidelity-Beta-PR15795-d546550.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20067/HighFidelity-Beta-Interface-PR15795-d546550.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20067/HighFidelity-Beta-PR15795-d546550.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20067/HighFidelity-Quest-Beta-PR15795-d546550.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20067/HighFidelity-Beta-PR15795-d546550.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20067/HighFidelity-Beta-Interface-PR15795-d546550.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20074/HighFidelity-Beta-PR15795-9f1768a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20074/HighFidelity-Quest-Beta-PR15795-9f1768a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20074/HighFidelity-Beta-PR15795-9f1768a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20074/HighFidelity-Beta-Interface-PR15795-9f1768a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20074/HighFidelity-Beta-PR15795-9f1768a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20074/HighFidelity-Beta-Interface-PR15795-9f1768a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20076/HighFidelity-Beta-PR15795-21454f6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20076/HighFidelity-Beta-Interface-PR15795-21454f6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20076/HighFidelity-Beta-PR15795-21454f6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20076/HighFidelity-Quest-Beta-PR15795-21454f6.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20076/HighFidelity-Beta-PR15795-21454f6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20076/HighFidelity-Beta-Interface-PR15795-21454f6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20086/HighFidelity-Beta-PR15795-8044b33.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20086/HighFidelity-Beta-Interface-PR15795-8044b33.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20086/HighFidelity-Beta-PR15795-8044b33.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20086/HighFidelity-Quest-Beta-PR15795-8044b33.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20086/HighFidelity-Beta-PR15795-8044b33.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20086/HighFidelity-Beta-Interface-PR15795-8044b33.exe

**Pull request merged**
