### PR TITLE
Tablet screen shifts up or down when grabbed if avatar's current height is taller or shorter than the default mannequin

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixing `WEB_ENTITY_Y_OFFSET` calculation when scaling up/down avatar

https://highfidelity.fogbugz.com/f/cases/14901/Tablet-screen-shifts-up-or-down-when-grabbed-if-avatar-s-current-height-is-taller-or-shorter-than-the-default-mannequin

### CODE REVIEW

**Comment by wayne-chen** [comment]
**TEST PLAN**:

- Enter Interface in HMD mode
- Change avatar size, either by selecting a short avatar (Robimo) or scaling yourself
- Bring up the tablet and grab it
- Tablet screen should stay the same size and not have an offset

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10291/HighFidelity-Beta-PR13281-b644916.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10291/HighFidelity-Beta-PR13281-b644916.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10291/HighFidelity-Beta-Interface-PR13281-b644916.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10291/HighFidelity-Beta-PR13281-b644916.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10291/HighFidelity-Beta-Interface-PR13281-b644916.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10406/HighFidelity-Beta-PR13281-b644916.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10406/HighFidelity-Beta-PR13281-b644916.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10406/HighFidelity-Beta-Interface-PR13281-b644916.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10410/HighFidelity-Beta-PR13281-b644916.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10410/HighFidelity-Beta-PR13281-b644916.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10410/HighFidelity-Beta-Interface-PR13281-b644916.dmg

**Comment by QliCknox** [comment]
Currently testing

**Comment by conklin94122** [comment]
Moved to RC70 per Chang

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10717/HighFidelity-Beta-PR13281-a1f02c8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10717/HighFidelity-Beta-PR13281-a1f02c8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10717/HighFidelity-Beta-Interface-PR13281-a1f02c8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10717/HighFidelity-Beta-PR13281-a1f02c8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10717/HighFidelity-Beta-Interface-PR13281-a1f02c8.exe

**Comment by wayne-chen** [comment]
This MS issue is fixed in [PR#13321](https://github.com/highfidelity/hifi/pull/13321).

**Pull request closed without merging**
