### PR TITLE
some reinterpret/dynamic cast cleanup in domain-server

### PR DESCRIPTION
**Pull request by birarda**
- corrected some code in domain-server target

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1802e1520db6fe59809f2a5f10a3417d7240e1ed available at: https://gist.github.com/d768487ed3d8820c6b83ddb42c65dbd8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.dmg

**Comment by birarda** [comment]
test this please

**Comment by birarda** [comment]
#### Test Plan

General smoke test of the Sandbox to ensure the domain-server is functioning as it should.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1802e1520db6fe59809f2a5f10a3417d7240e1ed available at: https://gist.github.com/d768487ed3d8820c6b83ddb42c65dbd8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1802e1520db6fe59809f2a5f10a3417d7240e1ed available at: https://gist.github.com/d768487ed3d8820c6b83ddb42c65dbd8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.dmg

**Comment by RyanDowne** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1802e1520db6fe59809f2a5f10a3417d7240e1ed available at: https://gist.github.com/d768487ed3d8820c6b83ddb42c65dbd8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9478-1802e15.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
Tested on win10
###PASS

All seems good.

Started and stopped server. Success
Quit and restart server: Success.

Add entites to ATP: Success
Add entities to domain from ATP: Success
Delete entities from domain: Success
Delete entities from atp restart client observe deleted asset removed: Success.
Ban avatar from domain: Success.
Unban avatar from domain: Success.
Run script that changes properties of multiple entities: Success.
Added some extra agents: Success.
@birarda  let me know if this is enough.

**Pull request merged**
