### PR TITLE
use a setting handle for UAL disabled to fix startup race

### PR DESCRIPTION
**Pull request by birarda**
- fixes an issue where two events would go out for users not wanting to send usage data due to Menu load race

### CODE REVIEW

**Comment by birarda** [comment]
To test:

- Toggle "Send Data" in Settings -> General -> Privacy to off.
- Restart your client
- You should NOT see `Logging activity "launch"` at the start of your log file

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09981db83461bbadc3f56a78c03af743d3d13a4e available at: https://gist.github.com/b1d92cca9e199333a1d406ef05383968<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7791.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7791.dmg

**Comment by birarda** [comment]
Build fail is fine, was an npm error on ubuntu which this touches none of.

**Comment by birarda** [comment]
test this please

**Comment by Nex-Pro** [comment]
@birarda You want me to check this ?

**Comment by birarda** [comment]
That would be excellent!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09981db83461bbadc3f56a78c03af743d3d13a4e available at: https://gist.github.com/b1d92cca9e199333a1d406ef05383968<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7791.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7791.dmg

**Comment by Nex-Pro** [comment]
Platform win10 Desktop 16gb GTX770 2gb.

Tested 3 times with setting on and off. ( 6 launches ) Success.
Behaves correctly each time.

#### Pass.

**Pull request merged**
