### PR TITLE
DO NOT MERGE - Test change - Testing build environment

### PR DESCRIPTION
**Pull request by murillodigital**
This is just a test - do not merge

### CODE REVIEW

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/63d5c1aa4ea19484821c439454d78846<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/63d5c1aa4ea19484821c439454d78846<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/63d5c1aa4ea19484821c439454d78846<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/63d5c1aa4ea19484821c439454d78846<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8493-271a871.dmg

**Comment by ZappoMan** [comment]
closing

**Pull request closed without merging**
