### PR TITLE
Case 21486: Fix context overlay

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21486/context-overlay-fix-for-81

Test plan:
- Use the context overlay in desktop and HMD.  It should work.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17721/HighFidelity-Beta-PR15053-a8e6d01.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17721/HighFidelity-Quest-Beta-PR15053-a8e6d01.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17721/HighFidelity-Beta-PR15053-a8e6d01.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17721/HighFidelity-Beta-Interface-PR15053-a8e6d01.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17721/HighFidelity-Beta-PR15053-a8e6d01.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17721/HighFidelity-Beta-Interface-PR15053-a8e6d01.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17729/HighFidelity-Beta-PR15053-a8e6d01.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17729/HighFidelity-Quest-Beta-PR15053-a8e6d01.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17729/HighFidelity-Beta-PR15053-a8e6d01.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17729/HighFidelity-Beta-Interface-PR15053-a8e6d01.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17729/HighFidelity-Beta-PR15053-a8e6d01.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17729/HighFidelity-Beta-Interface-PR15053-a8e6d01.exe

**Pull request merged**
