### PR TITLE
Possible fix to abandoned lines/entities

### PR DESCRIPTION
**Pull request by ZappoMan**
don't apply out of order edits to entities that have been deleted

### CODE REVIEW

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 449beab985923768e7ab18aa50e72856a777c7bc available at: https://gist.github.com/409278941344b0ef5a39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f3cf82202b3418456916ae22d8616242770cc8e available at: https://gist.github.com/409278941344b0ef5a39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f3cf82202b3418456916ae22d8616242770cc8e available at: https://gist.github.com/409278941344b0ef5a39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6421.dmg

**Comment by RyanDowne** [comment]
Chris and I tested this morning and could not create abandoned lines. We even tried with the whiteboard and all was well. We did still see some behavior where one person sees themselves holding something and the other person doesn't until they let go and re-grab but I think that is a sep issue.

**Pull request merged**
