### PR TITLE
7469 Mouse Pointer Depth is Incorrect in HMD Mode

### PR DESCRIPTION
**Pull request by ElderOrb**
fix for '7469 Mouse Pointer Depth is Incorrect in HMD Mode'

*** Test plan *** 

1. In HMD, open the tablet
2. Move your mouse so that it is over the tablet
3. The depth of the mouse should be drawn correctly so that the mouse appears on top of the tablet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4337/HighFidelity-Beta-PR11648-cadf00fecf92ef6c529834179a559b6d5babc4be.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4337/HighFidelity-Beta-PR11648-cadf00fecf92ef6c529834179a559b6d5babc4be.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
In HMD, open the tablet | Pass
Move your mouse so that it is over the tablet | Pass
The depth of the mouse should be drawn correctly so that the mouse appears on top of the tablet | Pass

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
