### PR TITLE
Remove old versions of the VC Runtime from the installation directory

### PR DESCRIPTION
**Pull request by jherico**
Some of the recent dumps have been showing different versions of VCRUNTIME140.dll and MSVCP140.dll, due to one being loaded from the Windows system directory, and the other being loaded from old leftover DLLs located in the Interface installation directory.  This PR should remove any old versions of the runtime DLLs in the installation directory preventing this version mismatch.  

## Testing

If you have any of these dlls (`msvcp140.dll`, `msvcr140.dll` or `vcruntime140.dll`) in your `C:\Program Files\High Fidelity` folder, create a `C:\Program Files\High Fidelity - PR11353` folder and copy them to it.  Then install this PR.  Once the PR installation finishes the DLLs should no longer be there.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3290/HighFidelity-Beta-PR11353-e595541da0cebf3c443c3854c4821cbbc4fa4d8e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3290/HighFidelity-Beta-PR11353-e595541da0cebf3c443c3854c4821cbbc4fa4d8e.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
I believe I may have to withdraw unfortunately as I do not have any of the DLL's in my primary High Fidelity folder present.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
--- | ---
msvcp140.dll | Deleted
msvcr140.dll | Deleted
vcruntime140.dll | Untouched

`vcruntime140.dll` did not delete after the installation had finished.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by jherico** [comment]
@cain-kilgore can you retest after build?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3416/HighFidelity-Beta-PR11353-2eff3dcbd6dfd54a8d787cb96523ebbb7d9b2022.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3434/HighFidelity-Beta-PR11353-2eff3dcbd6dfd54a8d787cb96523ebbb7d9b2022.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3438/HighFidelity-Beta-PR11353-2eff3dcbd6dfd54a8d787cb96523ebbb7d9b2022.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3438/HighFidelity-Beta-PR11353-2eff3dcbd6dfd54a8d787cb96523ebbb7d9b2022.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
msvcp140.dll | Deleted
msvcr140.dll | Deleted
vcruntime140.dll | Deleted

All good.

**Pull request merged**
