### PR TITLE
simplify fileOnUrl to only look for external textures right beside FBX

### PR DESCRIPTION
**Pull request by birarda**
- removed special handling for absolute and relative paths inside FBX reading

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/566/HighFidelity-Beta-PR10660-d2bea94768ffd8f0595db7ecb59d557927fb0467.dmg

**Comment by birarda** [comment]
Note: This PR will break loading of external textures at a relative or absolute path for FBXes loading from the local filesystem. It puts the local file behaviour in line with the remote behaviour (always loading right beside the FBX).

### Test Plan

1. Load a reference domain (welcome) and confirm that all models and textures load as you expect. This test is to confirm that remote texture loading is unchanged.
2. Load an FBX from the local file system with an external texture that is placed beside the FBX. Confirm that the FBX and the texture load as you expect.
3. Move the texture away from the FBX and confirm that it fails to load.

**Comment by OmegaHeron** [comment]
QA In progress.

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

dev-welcome and dev-playa look as expected.
Created model with embedded texture AND without.
Rezzed model with embedded, model appeared as expected.
Cleared cache manually.
Rezzed model with external referenced texture (exported 3 different ways from blender for handling of texture path refs).
Added texture to atp in a subdir matching relative dir to FBX source.
No texture seen on models (as expected).
Added texture to atp beside FBX source.
Texture appeared on model as expected.

**Pull request merged**
