### PR TITLE
Make create apps not grab tablet if editing an entity with hand

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Fixes tablet being grabbed in addition to lasered entity in Create and Shapes apps.
- Makes far grabbing an entity ignore tablet (no longer stops far grab when laser or hand intersect tablet). Near grabbing already does this.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

A) Repro the problems:

1) Create app grabs tablet in addition to entity:
- HMD mode.
- Create app running.
- Laser-click an entity so that it is selected.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity manipulation handle and your hand nears the tablet.

2) Shapes app grabs tablet in addition to entity:
- HMD mode.
- Shapes app from Marketplace running.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity scale handle (Scale tool) and your hand nears the tablet.

B) Confirm that the PR and attached Shapes zip fixes the above problems:
- Tablet is not grabbed if you're editing an entity using either apps and your hand nears the tablet.
- Tablet is also not highlighted when your hand nears the tablet while editing an entity.

[shapes.zip](https://github.com/highfidelity/hifi/files/2513010/shapes.zip)

hifi-content repository PR: https://github.com/highfidelity/hifi-content/pull/210

https://highfidelity.manuscript.com/f/cases/19345

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14389/HighFidelity-Beta-PR14276-1460e43.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14389/HighFidelity-Beta-PR14276-1460e43.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14389/HighFidelity-Beta-Interface-PR14276-1460e43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14389/HighFidelity-Beta-PR14276-1460e43.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14389/HighFidelity-Beta-Interface-PR14276-1460e43.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14869/HighFidelity-Beta-PR14276-1460e43.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14869/HighFidelity-Beta-PR14276-1460e43.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14869/HighFidelity-Beta-Interface-PR14276-1460e43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14869/HighFidelity-Beta-PR14276-1460e43.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14869/HighFidelity-Beta-Interface-PR14276-1460e43.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
FAIL @conklin94122 

PASS - Create mode does not grab both the object and the tablet at the same time.
FAIL - Shapes still grabs the object and the Tablet at the same time.
??? - Normal grab is cut-off by the tablet.

Every mode grabs in a different manner, Attached video shows the differences.
[GrabDifferences.zip](https://github.com/highfidelity/hifi/files/2563163/GrabDifferences.zip)

**Comment by ctrlaltdavid** [comment]
Regarding the FAIL on the Shapes app: You need to run the Shapes app from the zip file. It has changes that work in conjuction with the Interface changes.

Regarding the ???s on normal grab: Yhe same thing happens in master. It is, I believe, intentional behavior: the tablet has precedence over grabbing an entity.

Also, PR updated to latest master to resolve merge conflict resulting from new 3D keyboard. Test case C) added.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14986/HighFidelity-Beta-PR14276-a34e1f6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14986/HighFidelity-Beta-PR14276-a34e1f6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14986/HighFidelity-Beta-Interface-PR14276-a34e1f6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14986/HighFidelity-Beta-PR14276-a34e1f6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14986/HighFidelity-Beta-Interface-PR14276-a34e1f6.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
FAIL @conklin94122 

PASS - Create mode does not grab both the object and the tablet at the same time.
PASS - Shapes does not grab the object and tablet at the same time.
PASS - Keyboard operates well, even when holding an item. Focus does not change even though mallets can hit the keyboard.


I think I got the right Shapes build this time.
FAIL 
1 PR Bug: Shapes app has targeting through the Tablet. You can grab things while using the tablet. Builders Grid in Localhost was most visible.
2 PR Bug: Laser holding an object can grab onto tablet and slide page if slowly moved across.

1 Ignore: (Bug in Master/Stable) Web entities take targeting precedence over objects. (Months Old defect, has a fix for normal grab and create, but never adjusted for the Shapes app)

**Comment by ctrlaltdavid** [comment]
### Test Plan

A) Repro the problems:

1) Create app grabs tablet in addition to entity:
- HMD mode.
- Create app running.
- Laser-click an entity so that it is selected.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity manipulation handle and your hand nears the tablet.

2) Shapes app grabs tablet in addition to entity:
- HMD mode.
- Shapes app from Marketplace running.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity scale handle (Scale tool) and your hand nears the tablet.

B) Confirm that the PR and attached Shapes zip fixes the above problems:
- Tablet is not grabbed if you're grabbing an entity while using the Create app and your hand nears the tablet.
- Tablet is also not highlighted when your hand nears the tablet in the preceding test.
- Tablet is not grabbed if you're grabbing an entity while using the Shapes app and your hand nears the tablet.
- Tablet is also not highlighted when your hand nears the tablet in the preceding test.

C) Check that the new 3D keyboard works as expected w.r.t. grabbing entities. See the relevant bits of https://highfidelity.testrail.net/index.php?/cases/view/30666 per https://github.com/highfidelity/hifi/pull/13948.

D) Check that Shapes hands don't grab entity you're inside while trying to operate the tablet.
- In localhost and standing on the builders grid, unlock the builders grid.
- Confirm that grabbing with either hand grabs the gride and moves it. Tip: Use the undo button at bottom of the Shapes UI to return the grid to its previous position.)
- Display the tablet.
- You should be able to laser on and use the tablet without the builders grid being grabbed and moved.
- You should be able to put your hand near the tablet so that it highlights and grab the tablet without the builders grid being grabbed and mode.

E) Check that Shapes laser grab finish when the laser intersects the tablet.
- Create app.
- Tablet open.
- Far grab an entity and move the laser to intersect the tablet.
- The entity stops being moved in favor of interacting with the tablet.
- The entity does not resume movement after the laser stops intersecting the tablet. I.e., the entity is no longer grabbed.
- Similarly, using a Stretch tool handle stops when the laser intersects the tablet.
- Also if you start teleporting.

F) Check that Create laser grab finish when the laser intersects the tablet.
- ... Per E except with the Create app, including the editing handles.

G) General test of the Create app, including:
- Using the grab handles in HMD mode, before and after entity or handle is stopped being grabbed because laser intersected tablet.

[shapes.zip](https://github.com/highfidelity/hifi/files/2587900/shapes.zip)

hifi-content repository PR: https://github.com/highfidelity/hifi-content/pull/210

https://highfidelity.manuscript.com/f/cases/19345

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15211/HighFidelity-Beta-PR14276-b24c482.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15211/HighFidelity-Beta-PR14276-b24c482.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15211/HighFidelity-Beta-Interface-PR14276-b24c482.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15211/HighFidelity-Beta-PR14276-b24c482.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15211/HighFidelity-Beta-Interface-PR14276-b24c482.exe

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

Only one _potential PR bug_ (more of an aesthetics choice) listed below.

Shapes from new test plan used.
PASS - Create mode does not grab both the object and the tablet at the same time.
PASS - Shapes does not grab the object and tablet at the same time.
PASS - Keyboard operates well, even when holding an item. Focus does not change even though mallets can hit the keyboard.
PASS - Shapes app targeting laser breaks when tablet gets between object and actively grabbing controller.


Possible PR Bug:
When holding an object, the laser toggles two things, Location Tracking, and Dynamics. 
When the laser holding an object passes over the tablet, the Location Tracking will disconnect immediately. 

**The Dynamics state** will remain linked to the controller, and will only release when the controller button is lifted. This allows for a Dynamic object to be held in place.

From a use standpoint it was kind of nice not having to worry about the tablet or another overlay breaking the grab connection. But a menu/overlay abruptly disconnecting a grabbed item is standardized interaction.


Old Bugs: (Not from PR)
-Web entities take targeting precedence over objects.
-App Bug: When a laser holding an object (in Shapes app) passes over the  tablet, it can grab the page and cause it to slide or scroll. (Main menu can change page. Market can scroll listings.)

New Master Bugs:  (Not from PR)
-Items cannot be Rez'd. All market items etc, have an import error.
-Loading certain objects will crash the Interface. Something in Usagi (hifiqa-master-metaverse-staging).

**Comment by ctrlaltdavid** [comment]
Re "App Bug: When a laser holding an object (in Shapes app) passes over the tablet, it can grab the page and cause it to slide or scroll. (Main menu can change page. Market can scroll listings.)" … The Shapes app from the zip file included in the test plan needs to be used for parts B onward.

**Comment by shanzzam** [comment]
Moving to 77

**Comment by shanzzam** [comment]
> PASS @conklin94122

> New Master Bugs: (Not from PR)
> -Items cannot be Rez'd. All market items etc, have an import error.
> -Loading certain objects will crash the Interface. Something in Usagi (hifiqa-master-metaverse-staging).

@qlimguicheteau Is there an issue opened for that?

**Comment by qligmaloney** [comment]
@shanzzam Both of these issues have manuscript tickets opened

Cant Rez - https://highfidelity.manuscript.com/f/cases/19902/There-was-an-error-importing-the-entity-file-when-trying-to-Rez-an-entity-or-Wear-an-item-Replace-content-not-replacing

Crash in usagi - https://highfidelity.manuscript.com/f/cases/19904/Crash-on-Object-load-View-angle-loads-item-Hifiaq-Master-Metaverse-Staging

**Comment by ctrlaltdavid** [comment]
### Test Plan

#### A) Repro the problems using a recent dev build of Interface master and the Shapes app from the Marketplace.

1) Create app grabs tablet in addition to entity:
- HMD mode.
- Create app running.
- Laser-click an entity so that it is selected.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity manipulation handle and your hand nears the tablet.

2) Shapes app grabs tablet in addition to entity:
- HMD mode.
- Shapes app from Marketplace running.
- Laser-click-and-hold the entity so that it is grabbed by your hand.
- While continuing to grab the entity, move your hand near the tablet.
- The tablet is grabbed in addition to the entity (i.e., both are grabbed and move with your hand).
- Similarly if you've grabbed an entity scale handle (Scale tool) and your hand nears the tablet.

3) Entity far grabbed is dropped if hand or laser intersects tablet.
- Create a sphere and a cube. Make the cube dynamic and give it some gravity (gravity y value = -9, say).
- Exit the Create app but keep the tablet open.
- Far grab the non-dynamic sphere and make the laser interset the tablet. The entity stops being grabbed. The same happens if your hand intersects the tablet.
- Far grab the dynamic cybe and make the laser interset the tablet. The entity is dropped. The same happens if your hand intersects the tablet.

4) When an entity is near grabbed the hand (correctly) ignores the tablet when intersected.
- Near grab the non-dynamic sphere. You can move it and your hand through the tablet without anything happening.
- Near grab the dynamic cube. You can move it and your hand through the tablet without anything happening.



#### B) Confirm that the PR build of Interface and Shapes app from attached zip file fixes the above problems:

1) 
- Tablet is not grabbed if you're grabbing an entity while using the Create app and your hand nears the tablet.
- Tablet is also not highlighted when your hand nears the tablet in the preceding test.

2) 
- Tablet is not grabbed if you're grabbing an entity while using the Shapes app and your hand nears the tablet.
- Tablet is also not highlighted when your hand nears the tablet in the preceding test.

3) Entities continue to be far grabbed when hand or laser intersect tablet; the tablet is ignored.
- Non-dynamic sphere.
- Dynamic cube.

4) Entites contine to be near grabbed when hand or laser intersect tablet; the tablet is ignored.
- Non-dynamic sphere.
- Dynamic cube.


#### C) Check that Shapes hands don't grab entity you're inside while trying to operate the tablet.
- In localhost and standing on the builders grid, unlock the builders grid.
- Confirm that grabbing with either hand grabs the gride and moves it. Tip: Use the undo button at bottom of the Shapes UI to return the grid to its previous position.)
- Display the tablet.
- You should be able to laser on and use the tablet without the builders grid being grabbed and moved.
- You should be able to put your hand near the tablet so that it highlights and grab the tablet without the builders grid being grabbed and mode.


#### D) General tests of related functionality.
- Create app in HND mode: using the edit handles displayed on an entity being edited.
- Test that far to near grab still works: far grab an entity and draw it towards you so that it is near grabbed. (Known problem: you may get a repeated series of haptic pulses during the transition. If this occurs, push your hand forward a little to complete the near grab. https://highfidelity.manuscript.com/f/cases/17406)

- Test that far trigger of an entity still works. Host the following script on a Web server and puts its URL in the "Script" property in a cube entity and set the entity's "triggerable" property. Clicking it with your laser in HMD mode (and mouse in desktop mode mode) should make it change colour.
```
(function () {
    this.startFarTrigger = function (entityID) {
	console.log("$$$$$$$ startFarTrigger");
        Entities.editEntity(entityID, color : { red: 255, green: 0, blue: 0 });
    };
    this.clickDownOnEntity = function (entityID) {
	console.log("$$$$$$$ startFarTrigger");
        Entities.editEntity(entityID, color : { red: 255, green: 0, blue: 0 });
    };
})
```
- Test that equip still works. E.g., https://highfidelity.testrail.net/index.php?/cases/view/17849.
- Check that the new 3D keyboard works as expected w.r.t. grabbing entities. See the relevant bits of https://highfidelity.testrail.net/index.php?/cases/view/30666 per https://github.com/highfidelity/hifi/pull/13948.

[shapes.zip](https://github.com/highfidelity/hifi/files/2601634/shapes.zip)

hifi-content repository PR: https://github.com/highfidelity/hifi-content/pull/210

https://highfidelity.manuscript.com/f/cases/19345

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15310/HighFidelity-Beta-PR14276-c3a0805.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15310/HighFidelity-Beta-PR14276-c3a0805.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15310/HighFidelity-Beta-Interface-PR14276-c3a0805.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15310/HighFidelity-Beta-PR14276-c3a0805.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15310/HighFidelity-Beta-Interface-PR14276-c3a0805.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15333/HighFidelity-Beta-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15333/HighFidelity-Beta-Interface-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15333/HighFidelity-Beta-PR14276-5e51ba0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15333/HighFidelity-Beta-Interface-PR14276-5e51ba0.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15492/HighFidelity-Beta-PR14276-5e51ba0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15492/HighFidelity-Beta-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15492/HighFidelity-Beta-Interface-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15492/HighFidelity-Beta-PR14276-5e51ba0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15492/HighFidelity-Beta-Interface-PR14276-5e51ba0.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15720/HighFidelity-Beta-PR14276-5e51ba0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15720/HighFidelity-Beta-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15720/HighFidelity-Beta-Interface-PR14276-5e51ba0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15720/HighFidelity-Beta-PR14276-5e51ba0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15720/HighFidelity-Beta-Interface-PR14276-5e51ba0.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Paused testing due to 0.76.1

**Comment by qliejahner** [comment]
Resumed testing

**Comment by ctrlaltdavid** [comment]
Removed "QA Approved" label until disconnect between Shapes apps in Testrail and used for testing is resolved.

**Comment by qliejahner** [comment]
Pass - The updated version of the shapes app behaves as expected.

**Pull request merged**
