### PR TITLE
Vec3 API JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA testing not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8976/app_12952_PR_8173ac87a864d69ff3fcde338aa1170af6d9198b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8976/HighFidelity-Beta-PR12952-8173ac87a864d69ff3fcde338aa1170af6d9198b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8976/HighFidelity-Beta-Interface-PR12952-8173ac87a864d69ff3fcde338aa1170af6d9198b.dmg

**Pull request merged**
