### PR TITLE
Move Sandbox logs to AppDataLocal

### PR DESCRIPTION
**Pull request by Atlante45**
Moves the logs out of Roaming

### CODE REVIEW

**Comment by Atlante45** [comment]
[ticket](https://highfidelity.manuscript.com/f/cases/14102/server-console-logs-should-be-in-local-not-roaming#BugEvent.98565)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10193/HighFidelity-Beta-PR13253-ca43f3f87df50aa50c5b0a81bb623d72dbffd096.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10193/HighFidelity-Beta-PR13253-ca43f3f87df50aa50c5b0a81bb623d72dbffd096.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10193/HighFidelity-Beta-Interface-PR13253-ca43f3f87df50aa50c5b0a81bb623d72dbffd096.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10193/HighFidelity-Beta-PR13253-ca43f3f87df50aa50c5b0a81bb623d72dbffd096.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10193/HighFidelity-Beta-Interface-PR13253-ca43f3f87df50aa50c5b0a81bb623d72dbffd096.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Sandbox gets stuck on "Extracting" screen upon installing of PR build. User cannot restart Sandbox except by killing the application from Task Manager. Logs directory and log.txt file do move back to Local App data as expected.
Screenshot and logs attached

[PR13253.zip](https://github.com/highfidelity/hifi/files/2063280/PR13253.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10374/HighFidelity-Beta-PR13253-2995636.apk

**Comment by Atlante45** [comment]
@qligmaloney Pushed a new build that will fix this issue.
Make sure to delete `AppData/Local/High Fidelity - PR13253` and `AppData/Roaming/High Fidelity - PR13253` for before re-running the test plan as specified in the pre-requisite.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10374/HighFidelity-Beta-PR13253-2995636.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10374/HighFidelity-Beta-Interface-PR13253-2995636.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10374/HighFidelity-Beta-PR13253-2995636.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10374/HighFidelity-Beta-Interface-PR13253-2995636.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Tested using test steps of moving the logs folder and .txt from the local to the roaming and then relaunching the sandbox. When sandbox was relaunched, the files moved back from the roaming to the local.

Further tested with sandbox to verify it still loads and will shut down properly. The sandbox loaded fine and was usable and properly allowed us to close the sandbox.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10511/HighFidelity-Beta-PR13253-ffac96d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10511/HighFidelity-Beta-PR13253-ffac96d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10511/HighFidelity-Beta-Interface-PR13253-ffac96d.exe

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10515/HighFidelity-Beta-PR13253-ffac96d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10515/HighFidelity-Beta-PR13253-ffac96d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10515/HighFidelity-Beta-Interface-PR13253-ffac96d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10515/HighFidelity-Beta-PR13253-ffac96d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10515/HighFidelity-Beta-Interface-PR13253-ffac96d.exe

**Pull request merged**
