### PR TITLE
fix typo in tablet avatar browser

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- open Avatar browser in Tablet
- Make sure it is working

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4543/HighFidelity-Beta-PR11712-b1601dcd4c2375c4ff407df606941b20d7ad364c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4543/HighFidelity-Beta-PR11712-b1601dcd4c2375c4ff407df606941b20d7ad364c.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

open Avatar browser in Tablet **Check**
Make sure it is working **Check**

**Menu>Settings>Avatar>Browse Avatar**
image

Selecting avatars also works and changes accordingly. **Pass**

**Comment by howard-stearns** [comment]
This appears to interact with marketplace. (In lieu of a more focused marketplace test,) Please go through https://highfidelity.testrail.net/index.php?/suites/view/192&group_by=cases:section_id&group_order=asc in _both tablet and desktop_.

**Pull request merged**
