### PR TITLE
Growing plant

### PR DESCRIPTION
**Pull request by ericrius1**
This PR adds a pot of soil from which springs a cactus and some fragmenty flowers when the pot is watered.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d00b650ee2aceb8325938f2330afd6c29acaed73 available at: https://gist.github.com/2350bf8455bf4e0f22df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.dmg

**Comment by ericrius1** [comment]
To test:  run https://rawgit.com/ericrius1/hifi/growingPlant/examples/homeContent/plant/growingPlantSpawner.js

Now click and hold on the faucet above the pot, and you should see water flowing, flowers blooming, and a cactus growing!

https://app.asana.com/0/31759584831097/82864779674833

**Comment by hifi-gustavo** [comment]
Build console output for commit: f8c846f5d11b2fd3384a327805807638cc1be186 available at: https://gist.github.com/2350bf8455bf4e0f22df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.dmg

**Comment by imgntn** [comment]
@ericrius1 
[02/16 09:28:44] [DEBUG] Done downloading script at: "https://rawgit.com/ericrius1/hifi/growingPlant/examples/homeContent/plant/growingPlantEntityScript.js"
[02/16 09:28:44] [WARNING] [UncaughtException] ReferenceError: Can't find variable: loadTween in Entities:18
[02/16 09:28:44] [WARNING] [Backtrace]
@ eric[02/16 09:28:44] [WARNING]     <anonymous>() at (EntityID:{478a2183-ec7c-4985-a6c1-a55e44e3a285}, https://rawgit.com/ericrius1/hifi/growingPlant/examples/homeContent/plant/waterHoseEntityScript.js):18

**Comment by ericrius1** [comment]
@imgntn I don't know why the tween was failing to load, but I wasn't using it in final version anyway, so I removed it. That error should no longer appear

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc6e806ef2b728e7982dd4e8b6fed3aa0be45bd6 available at: https://gist.github.com/2350bf8455bf4e0f22df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ad4d6474833c5603ef5e1512a40d209cc5a9cfe available at: https://gist.github.com/2350bf8455bf4e0f22df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7115.dmg

**Comment by imgntn** [comment]
@ericrius1 no error now, but just a big gray pistil in the middle with no flowers :/

**Comment by ericrius1** [comment]
Going to do a redesign, so closing

**Pull request closed without merging**
