### PR TITLE
Add support for multiple textures and subimages to particles

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Add support for multiple textures and subimages within each texture:
 - textures: "url", or [ "url1", "url2", ... ] : This property already exists with the "url" form and is also used by model entities. In order to maintain compatibility, the property accepts either a string or an array of strings.
 - textureOrder: "random", "sequence" (default "sequence")
 - subImages: [ { x, y, width, height }, ... ] : Specifies a list of subimages to use within each texture over its lifetime.
 - subImageOrder: "random", "sequence" (default "sequence")
 - subImageInterval: seconds : How long to display each texture or subimage before advancing to the next.
 - subImageStart: "random", "first" (default "first")
 Fix the naming of the model overlays "subImage" property to "subimage" and update all scripts.

Worklist #20733

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Notes on testing:
- Protocol change means that Interface needs to be run against updated assignment client.
- Multiple textures and subimages are demonstrated in particlesTest.js.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c03f61a453e216e5f7d921d09fff4c914650b565 available at: https://gist.github.com/64bd2e0f3605727ee70a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd2a3736fc0b5a50f0144d7baf083a3fa5bc8a3c available at: https://gist.github.com/64bd2e0f3605727ee70a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.dmg

**Comment by cozza13** [comment]
I tested this and it works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45baba89c2eac0a5358e5f698bb899251077f935 available at: https://gist.github.com/64bd2e0f3605727ee70a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.dmg

**Comment by ctrlaltdavid** [comment]
Particle textures ...
- The particle emitter is configured with a set of possible textures to choose among as each particle is created.
- Each particle keeps using the texture it was assigned at its creation even as the emitter's set of textures is changed while the particle is in flight.
- To render each texture we need the value of DependencyManager::get<TextureCache>()->getTexture("http...")->getGPUTexture().

This is achieved in the current code as follows ...
- ParticleEffectEntityItem::_emitterTextures[] stores the values of DependencyManager::get<TextureCache>()->getTexture("http...") for the current set of emitter textures. These values are used as each particle is created.
- ParticleEffectEntityItem::_particleTextures[] stores a DependencyManager::get<TextureCache>()->getTexture("http...") value from _emitterTextures[] for each particle in flight. These values are used for rendering.
- The NetworkTexturePointer value for each particle from _particleTextures[] is included in the ParticleDetails passed through to ParticlePayload::render() via a gpu::BufferPointer.
- ParticlePayload::render() does the getGPUTexture() as necessary to render a set of particles in a batch with a particular specified texture.

Note: The _emitterTextures[] values are obtained in RenderableParticleEffectEntityItem::update() when the textures property is changed because RenderableParticleEffectEntityItem has access to the TextureCache.
In effect, the ParticleEffectEntityItem variables are caching the NetworkTexturePointer values on behalf of RenderableParticleEffectEntityItem.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9044dc42eb16c6e9ff3f7f6af96a346413a08660 available at: https://gist.github.com/64bd2e0f3605727ee70a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2579cc60d552ad8f420e1f7af2929faeb602292 available at: https://gist.github.com/64bd2e0f3605727ee70a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6379.dmg

**Comment by ZappoMan** [comment]
@ctrlaltdavid - I'm closing this, since it's old, and not building. Please coordinate with @Atlante45 and @samcake to determine if/how/when to reopen and/or add these features to particles.

**Comment by ctrlaltdavid** [comment]
@ZappoMan : @Atlante45 is going to merge this into his particles stuff.

**Pull request closed without merging**
