### PR TITLE
omit unknown device names from clear-story data

### PR DESCRIPTION
**Pull request by danteruiz**
This makes sure that device names that are empty string are not sent to our data base. The only way the a device name would be empty is if the user is using steamvr but does not have their headset connected. So when our system callls `getOpenVrDeviceName()` it gets a null pointer from `acquireOpenVrSystem` which in that case we just return an empty string.

Ticket - https://highfidelity.manuscript.com/f/cases/16539/A-large-percentage-of-our-HMD-headsets-are-showing-up-as-NA

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16221/HighFidelity-Beta-PR14655-fe1a8a6.apk

**Comment by danteruiz** [comment]
Two Phase test plan
Phase 1.
- Using a vive or oculus through steamvr
- Have the devices connected and launch interface
- look through the log window and make sure you see this `[default] UserActivityLogger::connectedDevice -> type:  "display"  - deviceName:  "NAME OF DEVICE"` in the log and the `NAME OF DEVICE` is not an empty string.
- close interface and disconnect your headsets from the computer but make sure that steamvr is still running.
- launch interface...open the logs window  you should not be seeing this `[default] UserActivityLogger::connectedDevice -> type:  "display"  - deviceName:  "NAME OF DEVICE"` in the logs

Phase 2
- Once phase one has passed, I will remove my debug statement (which I do not want in final code) creating a new build, probably just do a sanity check test


- Will need to check clear story a few hours later to make sure `N/A` data was not sent for device names

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16221/HighFidelity-Beta-PR14655-fe1a8a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16221/HighFidelity-Beta-Interface-PR14655-fe1a8a6.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16224/HighFidelity-Beta-PR14655-f5de217.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16224/HighFidelity-Beta-PR14655-f5de217.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16224/HighFidelity-Beta-Interface-PR14655-f5de217.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16224/HighFidelity-Beta-PR14655-f5de217.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16224/HighFidelity-Beta-Interface-PR14655-f5de217.exe

**Pull request merged**
