### PR TITLE
Update JSDoc with some deprecations

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code has changed.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6115/HighFidelity-Beta-PR12115-3d9d2a1859a03ccd36c7eef9316712e3f8e6509d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6115/HighFidelity-Beta-PR12115-3d9d2a1859a03ccd36c7eef9316712e3f8e6509d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6115/app_12115_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6121/HighFidelity-Beta-PR12115-3d9d2a1859a03ccd36c7eef9316712e3f8e6509d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6121/app_12115_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6121/HighFidelity-Beta-PR12115-3d9d2a1859a03ccd36c7eef9316712e3f8e6509d.dmg

**Pull request merged**
