### PR TITLE
Prevent crash during long backup web requests

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7691/app_12548_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7691/HighFidelity-Beta-PR12548-40aa04ab9ae11654dbc45530a8972bf2fe1ce32d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7691/HighFidelity-Beta-PR12548-40aa04ab9ae11654dbc45530a8972bf2fe1ce32d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7765/app_12548_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by Atlante45** [comment]
## Test plan:
- Launch Interface and sandbox
- Upload a few hundred MB of data to your Asset Server (A few HF installers will do the trick)
- Go to the Domain Settings: http://localhost:40100
- Go to the content section and make a manual archive
- Wait for the archiving process to finish
- Click on `Download` for the manual archive you just created.
- Go to the `Nodes` page
- Make sure the uptime correlates with when you started the Sandbox, if they are only a few seconds old, then this is a fail.

Note: The download will not actually go through. This is expected and a fix for that is coming soon.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7772/app_12548_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7785/app_12548_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7785/HighFidelity-Beta-PR12548-a23884d0e03407841616b4d0bfc6109cc961bcac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7785/HighFidelity-Beta-PR12548-a23884d0e03407841616b4d0bfc6109cc961bcac.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Stopped Testing.

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
