### PR TITLE
Update the default edit.js collidesWith to include myAvatar

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.fogbugz.com/f/cases/19685/Models-imported-into-test-case-have-Automatic-Collisions-set-to-No-Collision-allowing-test-avatar-to-walk-through-model

### CODE REVIEW

**Comment by huffman** [comment]
# Test Plan

 * Create a cube, and stretch it out so you can walk
 * You should be able to collide with and walk on the cube

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14585/HighFidelity-Beta-PR14320-01b2918.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14585/HighFidelity-Beta-PR14320-01b2918.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14585/HighFidelity-Beta-Interface-PR14320-01b2918.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14585/HighFidelity-Beta-PR14320-01b2918.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14585/HighFidelity-Beta-Interface-PR14320-01b2918.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14877/HighFidelity-Beta-PR14320-01b2918.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14877/HighFidelity-Beta-PR14320-01b2918.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14877/HighFidelity-Beta-Interface-PR14320-01b2918.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Cubes collide with avatars by default

**Pull request merged**
