### PR TITLE
Fix for Camera-perspective-is-off-in-first-person-view, master branch 

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses:
https://highfidelity.manuscript.com/f/cases/20350/Camera-perspective-is-off-in-first-person-view
This fixes the problem where the eye joints were not being found for determining camera position in first person mode.

It also removes cruft code that used hfm members that redundantly kept the the indexes for essential joints of the skeleton. These included head, neck, eyes, hands, and toes indexes.

With the new joint mapping fields in the avatar fst files these essential joints will be mapped to hifi joint names and are no longer needed.

Test Plan
part 1
Avatar 1 Wear "Matthew" avatar
Avatar 2 walks in front of Matthew
Avatar 2 notices Matthews eyes do not follow Avatar 2
part 2
Wear Robimo avatar, available in store, in first person mode. Turnoff draw mesh and turn on debug draw default pose.
Use the mouse wheel to enter 3rd person and then re-enter 1st person. As you approach the back of the avatar head the camera should be at the level of the eyes. Not the neck.

Same PR as #14594 except for master branch

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15998/HighFidelity-Beta-PR14598-defdc9f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16000/HighFidelity-Beta-PR14598-3e1beb2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16000/HighFidelity-Beta-PR14598-3e1beb2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16000/HighFidelity-Beta-Interface-PR14598-3e1beb2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16005/HighFidelity-Beta-PR14598-42a1798.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16005/HighFidelity-Beta-PR14598-42a1798.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16005/HighFidelity-Beta-Interface-PR14598-42a1798.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16005/HighFidelity-Beta-PR14598-42a1798.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16005/HighFidelity-Beta-Interface-PR14598-42a1798.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass 

Avatar eyes seem to be tracking correctly again

**Pull request merged**
