### PR TITLE
adding back reload scripts shortcut and clean up AboutUtil(RC68)

### PR DESCRIPTION
**Pull request by danteruiz**
I added back the shortcut to reload scripts and I update the class AboutUtil so that it conforms to our coding standard

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan in this PR. https://github.com/highfidelity/hifi/pull/13254

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10221/HighFidelity-Beta-PR13257-646b852.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10221/HighFidelity-Beta-PR13257-646b852.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10221/HighFidelity-Beta-Interface-PR13257-646b852.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10221/HighFidelity-Beta-PR13257-646b852.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10221/HighFidelity-Beta-Interface-PR13257-646b852.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Reload scripts shortcut works, build type info displays on "About High Fidelity" page

**Pull request merged**
