### PR TITLE
remove createTetherballStick.js cache buster

### PR DESCRIPTION
**Pull request by Triplelexx**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6789/app_12310_PR.apk

**Comment by MiladNazeri** [comment]
No Qa needed for this, only removing of caching.

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6801/app_12310_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6801/HighFidelity-Beta-PR12310-257932cedcd22d9979ccb5399cd18a715d65622f.dmg

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6808/app_12310_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6808/HighFidelity-Beta-PR12310-257932cedcd22d9979ccb5399cd18a715d65622f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6808/HighFidelity-Beta-PR12310-257932cedcd22d9979ccb5399cd18a715d65622f.exe

**Pull request merged**
