### PR TITLE
Fix shared unit tests

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
While prototyping some unit tests I learned that the internal `shared` lib's unit tests had suffered bit-rot over the last few months.  This PR fixes a few compile issues and also one test failure.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7029/app_12367_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7029/HighFidelity-Beta-PR12367-64ec4dac7a697771af4782c9e959d1dc3ad14b62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7029/HighFidelity-Beta-PR12367-64ec4dac7a697771af4782c9e959d1dc3ad14b62.exe

**Pull request merged**
