### PR TITLE
RC-59 patch - Removed Keylight attenuation from .js (as well as .html).

### PR DESCRIPTION
**Pull request by Atlante45**
See original PR for test plan: #11799

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4892/HighFidelity-Beta-PR11808-b4b148367e959bb6ced05705663186574d206528.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4892/HighFidelity-Beta-PR11808-b4b148367e959bb6ced05705663186574d206528.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

Make sure that the attenuation check box, range and altitude fields are not visible in the Zone/Haze edit.js properties. **Seems like a fail as I can see Range & Altitude**

**Fail**

image

**Comment by YuppyPlays** [comment]
Testing complete:

Make sure that the attenuation check box, range and altitude fields are not visible in the Zone/Haze edit.js properties. **Seems like a fail as I can see Range & Altitude**

**Fail**

image

**Comment by Nex-Pro** [comment]
Checking this result.

**Comment by Nex-Pro** [comment]
I think this is a **PASS** 

I believe the intention here is to remove the "Keylight Attenuation" range and height paramaters.
This has been achieved.

See image.

hifi-snap-by--on-2017-11-14_17-35-33

Haze range and altitude remain. ( They are separate ) .

This would have been better if before and after images were posted for the QAs.

**Comment by samcake** [comment]
THanks @YuppyPlays  & @Nex-Pro 
yes it s a pass
there is no checkbox and range and altitude for the "keylight attenuation " section
All good
Sorry for the bad wording of the test...

**Pull request merged**
