### PR TITLE
fix shadow box that appears when flying

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

- Use Desktop (try HMD, but I think something else is wrong with shadows there)
- Enable shadows (in console, `Render.RenderShadowTask.enabled = true`)
- Fly up
- When you reach a certain height, you will notice a shadow box underneath you

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1971f5ed34f7bb692e49d1c53066277149cc2a9 available at: https://gist.github.com/f00ae908c5e72247cd493301fc288a74<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7932.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7932.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1971f5ed34f7bb692e49d1c53066277149cc2a9 available at: https://gist.github.com/f00ae908c5e72247cd493301fc288a74<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7932.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7932.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Tested Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**
All standard tests pass.  In no case was I able to get phantom shadow with this RC. :+1:  * 1bazillion.

Current RC
hifi-snap-by-omegaheron-on-2016-05-19_13-58-53

This PR
hifi-snap-by-omegaheron-on-2016-05-19_14-00-04

May we never see Mr Rectangle again.

**Pull request merged**
