### PR TITLE
(RC82) Fix out of bounds computing KDOPs when the model url is incorrect

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/22086/Out-of-bounds-error-in-HFMModel-computeKdops

This PR fixes the crash that occurs when visiting dev-content.

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to dev-content and make sure interface doesn't crash while loading the domain's content

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18634/HighFidelity-Beta-PR15346-c4d43e7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18634/HighFidelity-Quest-Beta-PR15346-c4d43e7.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18634/HighFidelity-Beta-PR15346-c4d43e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18634/HighFidelity-Beta-Interface-PR15346-c4d43e7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18639/HighFidelity-Beta-PR15346-4b7274f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18639/HighFidelity-Beta-Interface-PR15346-4b7274f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18639/HighFidelity-Beta-PR15346-4b7274f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18639/HighFidelity-Quest-Beta-PR15346-4b7274f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18639/HighFidelity-Beta-PR15346-4b7274f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18639/HighFidelity-Beta-Interface-PR15346-4b7274f.exe

**Pull request merged**
