### PR TITLE
OrbusVR style Scabbard

### PR DESCRIPTION
**Pull request by sethalves**
- provide an over-the-shoulder gesture for stashing and retrieving equippable items

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6667/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6667/HighFidelity-Beta-PR12277-bed9dce7ef72aadf0aa4385e16e73157f7e6139b.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6689/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6689/HighFidelity-Beta-PR12277-bed9dce7ef72aadf0aa4385e16e73157f7e6139b.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6697/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6697/HighFidelity-Beta-PR12277-bed9dce7ef72aadf0aa4385e16e73157f7e6139b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6697/HighFidelity-Beta-PR12277-bed9dce7ef72aadf0aa4385e16e73157f7e6139b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6752/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6752/HighFidelity-Beta-PR12277-d1e91ff2ee33e7ccb4dfb94fcfdab287d6cf48ac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6752/HighFidelity-Beta-PR12277-d1e91ff2ee33e7ccb4dfb94fcfdab287d6cf48ac.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6809/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6809/HighFidelity-Beta-PR12277-bd47f42bccf4c6ba54aa754bd49de0c09016ba21.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7696/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7696/HighFidelity-Beta-PR12277-ff0f32e1ba8c139195938937a584938728da6ddd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7696/HighFidelity-Beta-PR12277-ff0f32e1ba8c139195938937a584938728da6ddd.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7734/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7734/HighFidelity-Beta-PR12277-5bdf3042d542d0fd78063fb46e31eeea6ee40919.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7734/HighFidelity-Beta-PR12277-5bdf3042d542d0fd78063fb46e31eeea6ee40919.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7735/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7735/HighFidelity-Beta-PR12277-b665f93f0b065e80b19aa962ce5deaa3eb017fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7735/HighFidelity-Beta-PR12277-b665f93f0b065e80b19aa962ce5deaa3eb017fe9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7931/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7931/HighFidelity-Beta-PR12277-2349943b82919dd54c8529a11fdf53c1655bf713.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7931/HighFidelity-Beta-PR12277-2349943b82919dd54c8529a11fdf53c1655bf713.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8129/app_12277_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8129/HighFidelity-Beta-PR12277-38757255895e8c77693a349c97a504611a8b5577.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8129/HighFidelity-Beta-PR12277-38757255895e8c77693a349c97a504611a8b5577.exe

**Pull request closed without merging**
