### PR TITLE
BUGZ-1398: HMD Tablet Apps blocked by Web access error RC-84

### PR DESCRIPTION
**Pull request by danteruiz**
https://github.com/highfidelity/hifi/pull/16190 refer to this PR

### CODE REVIEW

**Comment by shanzzam** [comment]
build this please

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21318/HighFidelity-Beta-PR16192-adc2eaa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21318/HighFidelity-Beta-Interface-PR16192-adc2eaa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21318/HighFidelity-Beta-PR16192-adc2eaa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21318/HighFidelity-Beta-Interface-PR16192-adc2eaa.exe

**Pull request merged**
