### PR TITLE
on first run, send user to serverless tutorial rather than checking for local sandbox

### PR DESCRIPTION
**Pull request by sethalves**
- on first run, send user to serverless tutorial rather than checking for local sandbox

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- install interface and sandbox
- run interface
- make sure you're visiting the serverless tutorial (look for file:/// in url) rather than the sandbox

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/13957/User-should-res-in-Serverless-Tutorial-on-First-Run

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8518/HighFidelity-Beta-PR12791-4b0d338e5751ef43d85184c3e1dc5cb88f82c008.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8518/HighFidelity-Beta-PR12791-4b0d338e5751ef43d85184c3e1dc5cb88f82c008.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Serverless domain loaded rather than sandbox on first launch for all testers.

**Pull request merged**
