### PR TITLE
Bug fixes in oculus_touch default mapping

### PR DESCRIPTION
**Pull request by hyperlogic**
* Made sticks less sensitive. Raised deadSpot min from 0.05 to 0.3.
* Fixed problem were grip and trigger was mapped to Standard triggers. This was causing all sorts of problems
  with the handControllerGrab script.  Including double lasers and a stuck right hand laser.
* mapped grip to standard grip. So now you can use the grip button to drop equipped objects.
* increased deadZone on grip to make inadvertent drops less likely to happen.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1849/Double-lasers-when-over-HUD

**Comment by hifi-gustavo** [comment]
Build console output for commit: ace8639f5baf55331085adb7ec80e122dfd8a73e available at: https://gist.github.com/b600c8ce059975dd95ff603c04ed4a6d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8777-ace8639.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8777-ace8639.dmg

**Comment by ZappoMan** [comment]
Test plan?

**Comment by hyperlogic** [comment]
QA Test plan:
  * Run with Oculus Rift and Touch controllers.
  * Ensure that both right trigger and left trigger work as expected.  (freakin laser beams)
  * Equip the ping pong gun, Ensure that the the left and right grip buttons drop the gun when squeezed.
  * Ensure snap turn still works with the left and right sticks when Settings > Advanced Controller navigation is disabled.
  * Ensure that snap turn and walking forward, backward function as expected with the left stick when Settings > Advanced Controller navigation is enabled.
  * Make sure teleport still works (face buttons on touch)

**Comment by cozza13** [comment]
* Run with Oculus Rift and Touch controllers.
  * Ensure that both right trigger and left trigger work as expected.  (freakin laser beams) **(YES)**
  * Equip the ping pong gun, Ensure that the the left and right grip buttons drop the gun when squeezed. **(YES)**
  * Ensure snap turn still works with the left and right sticks when Settings > Advanced Controller navigation is disabled. **(YES)**
  * Ensure that snap turn and walking forward, backward function as expected with the left stick when Settings > Advanced Controller navigation is enabled. **(YES)**
  * Make sure teleport still works (face buttons on touch) **(YES)**

Deadzone issues on the touch controller, spoke with @hyperlogic and he is going to make an update

**Comment by hyperlogic** [comment]
@cozza13 I've increased the deadspot for the grip paddles.  Let me know if it makes it easier to use with your touch controllers.

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa52963e5d12156bf15c27c76190be5edc25031c available at: https://gist.github.com/b600c8ce059975dd95ff603c04ed4a6d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8777-aa52963.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8777-aa52963.dmg

**Comment by cozza13** [comment]
Deadzone issues on the touch controller, spoke with @hyperlogic and he is going to make an update (**Sorted**)

**Pull request merged**
