### PR TITLE
DEV-2391: Fix Recording.stopRecording() crash

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fix crash and add missing threading checks.

Case: https://highfidelity.atlassian.net/browse/DEV-2391

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21934/HighFidelity-Beta-PR16350-185d699.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21934/HighFidelity-Beta-Interface-PR16350-185d699.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21934/HighFidelity-Beta-PR16350-185d699.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21934/HighFidelity-Quest-Beta-PR16350-185d699.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21951/HighFidelity-Beta-PR16350-185d699.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21951/HighFidelity-Beta-Interface-PR16350-185d699.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21951/HighFidelity-Beta-PR16350-185d699.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21951/HighFidelity-Beta-Interface-PR16350-185d699.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21951/HighFidelity-Beta-PR16350-185d699.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21951/HighFidelity-Quest-Beta-PR16350-185d699.apk)

**Pull request merged**
