### PR TITLE
Remove Limitless API

### PR DESCRIPTION
**Pull request by thoys**
Replacement PR for https://github.com/highfidelity/hifi/pull/12837 (merged with latest master)

## QA Test Plan
- General smoke test.
- Open the Script Console (CTRL + ALT + J)     ,
   - type `LimitlessSpeechRecognition`
   - press Enter 
   - it should reply with:
```
[UncaughtException evaluate] Error: Can't find variable: LimitlessSpeechRecognition in about:console:1 [Backtrace] <global>() at about:console:1
ReferenceError: Can't find variable: LimitlessSpeechRecognition
```

Original notes from Triplelexx: "I have renamed a performance timer from "limitless" to "AnimDebugDraw" in the final commit, as that is handled in the scope."

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10599/HighFidelity-Beta-PR13380-05bc32b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10599/HighFidelity-Beta-PR13380-05bc32b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10599/HighFidelity-Beta-Interface-PR13380-05bc32b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10599/HighFidelity-Beta-PR13380-05bc32b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10599/HighFidelity-Beta-Interface-PR13380-05bc32b.exe

**Comment by QliCknox** [comment]
Pass @conklin94122 

Verified LimitlessSpeechRecognition returns with `ReferenceError: Can't find variable: LimitlessSpeechRecognition`

**Pull request merged**
