### PR TITLE
Fix avatar mouth movement when driven by audio loudness

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This is an alternate fix to #10415.

To test:

Login UserA and UserB in a domain and stand facing each other.
UserA: go into mirror mode while UserB watches UserA's face.
UserA: speak into the microphone
--> the mouth movement seen for UserA should more or less match cadence on both screens.

Swap places such that UserB is in mirror mode and UserA watches UserB and repeat the test with UserB speaking into their microphone.

**Comment by anshuman64** [comment]
Will QA once it builds

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2be6d19dfe5399438611780b1d6cd6995c849abf available at: https://gist.github.com/01908c89403d0befa75a4f4fdeeecedd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10424-2be6d19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10424-2be6d19.dmg

**Comment by anshuman64** [comment]
So, I compared the three versions of this:
1. No fix on blend shapes = looks as if the person is taaaalkiiingg veeerryyy slooooowwly
2. ctrlaltdavid's fix = blend shapes move quickly and are expressive as one would expect
3. Andrew's fix = seems somewhere in between 1 & 2. I am not satisfied with what I am seeing.

Not sure if I'm just crazy, but it seems like ctrlaltdavid's fix performs better. Can someone confirm?

**Comment by CainFoool** [comment]
anshuman64: Can confirm, tested both. David's works much better.

**Pull request merged**
