### PR TITLE
Stuttering: global thread pool management

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c0d129e277e6d4a147a5b8c59c79973f06f0f5eb available at: https://gist.github.com/0919ca2500725b9b793a9f864183e1ac<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-c0d129e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-c0d129e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50aef7fd2aea0367ada846481c09a6364195e6a4 available at: https://gist.github.com/0919ca2500725b9b793a9f864183e1ac<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-50aef7f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-50aef7f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96472186fde790cf9400d0749c2802d5adc665c1 available at: https://gist.github.com/0919ca2500725b9b793a9f864183e1ac<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-9647218.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-9647218.dmg

**Comment by ZappoMan** [comment]
**Test plan:**
- Smoke test
- Focus on rendering performance - this should see generally less "stutter" while scenes are loading... and it should also see less stutter in general even after a scene has loaded. This reduced stutter should be more dramatic on lower end CPU machines (machines with fewer cores).
- We do expect that some scenes may load "slower" on lower end CPU machines. So if you see that, it's not a QA Fail.
- Vive users - when the scene is "heavy" you should see better "time warp" instead of hard stutters

**Comment by OmegaHeron** [comment]
Will be testing this on my i5 machine once I have inet again that's not ~90KB/s 3g wireless.  ::glares at departing hurricane/trop storm::

**Comment by ZappoMan** [comment]
QA Report Mac - this build is as good as the current beta 5312 - so this is a Pass on Mac.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94210d2e69ba10f22d1530c6b1e780867c5bfac0 available at: https://gist.github.com/eb9ef39ecbc3ea0982fb71e24f701ac6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-94210d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-94210d2.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94210d2e69ba10f22d1530c6b1e780867c5bfac0 available at: https://gist.github.com/0919ca2500725b9b793a9f864183e1ac<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-94210d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8555-94210d2.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

There's a minor improvement loading standard home scene, dev-playa and dev-demo.  I had to run this PR versus current RC/DEV several times to determine there is a difference at all as it's small.  But - any improvement in scene load and stuttering is a plus.  FPS values for Desktop and DK2 for this PR versus RC/DEV are, within range of normal variance, identical.  Visually all things looked same in this PR versus other RC/DEV builds.

Using DK2 I still get some stuttering at dev-playa when looking up toward sky.  I see same thing in my test domain that has very little content and has same starry sky zone.  As you look upward and begin to have content move out of field of view and more sky in view the stutter becomes apparent.  Same again as you transit from mostly sky back to entities in view.  It's a difficult to explain thing.  This PR is either same as current RC/DEV or slightly better for this.

Standard tests (Audio, ATP functions, Edit operations) all pass.

**Pull request merged**
