### PR TITLE
Added preferences for the Perception Neuron plugin.

### PR DESCRIPTION
**Pull request by hyperlogic**
This PR disables this plugin by default because it is infrequently used and sometimes crashes on initialization if there is a TCP service already running on port 7001.

The plugin can be enabled via the General Preferences dialog.  The preferences also include fields for the server address and port.  NOTE: changes to these settings won't take effect until the next launch of interface.

To prevent the Neuron Plugin section showing up as the top section of the General Preferences dialog, a change was made to qml/dialogs/PreferencesDialog.qml which preserves the sort order of the showCategories array.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test:

With this PR, by default you should no longer see the following log message on start up.

    [DEBUG] [hifi.inputplugins] NeuronPlugin: socket status =  Connecting to localhost:7001 ...
    [WARNING] [hifi.inputplugins] NeuronPlugin: error connecting to  "localhost" : 7005 , error =  Failed to connect to 'localhost:7001'.

This message is printed out as the neuron plugin attempts to connect to the axis server and fails.

If you go into Preferences > General...  you should see a Perception Neuron section at the bottom.
Click the enable button and restart interface.  You should now see the log message appear.

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/2365/Deadlock-on-startup-in-latest-beta

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbf514a738e0116d39b7d83e703af9dc7a5d9420 available at: https://gist.github.com/b4c896833dfd5d0a225c1c1a6765ad4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9113-cbf514a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9113-cbf514a.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

QA Pass

General smoke tests pass.
By default Neuron Plugin did not activate on first run of this PR
Setting Neuron Plugin to enabled via preferences and restarting interface = neuron on.
Setting Neuron Plugin to disable via preferences and restarting interface = neuron off.

*I don't have neuron hardware, but, there's no change to plugin loading binder to port 7001 when enabled -- so I suspect it would work as expected if I had one.*

**Pull request merged**
