### PR TITLE
Add users.js to default, start visible to friends only

### PR DESCRIPTION
**Pull request by imgntn**
This PR returns users.js to the default scripts, but changes its starting setting to be 'friends only'. It also makes the window a bit wider so you can see where people are before teleporting.

To test:
1. Dont copy settings from production.
2. users.js should start as part of default scripts
3. it should start with 'friends' selected as visibility level
4. you should not appear on https://metaverse.highfidelity.com/api/v1/users?status=online
5. switch to visiblity 'everyone' 
6. you should appear on https://metaverse.highfidelity.com/api/v1/users?status=online
7. switch back to 'friends' and make sure you are visible to a friend who is also online

### CODE REVIEW

**Comment by ZappoMan** [comment]
We might want to also increase the width... since it's pretty much useless at it's current width.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1755649b1e0e7129ecf1ef0830fdf194b157d7e available at: https://gist.github.com/4c003dba8c565a9ea93aade860b5672a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7820.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7820.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 97e1621776d5950fc6d8a3afb27a327c81f9a9cd available at: https://gist.github.com/4c003dba8c565a9ea93aade860b5672a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7820.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7820.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7820
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** music
**Additional Test Results/Observations:** Installed PR without copying production settings.  ```users.js``` did load and display properly upon loading Interface.  It initialized with friends selected at visibility level.  Unexpected behavior as I DID appear in ```Visible To Friends
https://metaverse.highfidelity.com/api/v1/users?status=online
{"status":"success","data":{"users":[{"username":"KevinMThomas","location":{"path":"/2.03688,1.01745,3.89174/0,0.672415,0,0.740174","root":{"id":"6ea48bd6-3dda-47ba-b997-9a0e1872d499","name":"Music","domain":{"id":"967c4f19-9bd1-40ce-93f7-f13060713f9a","network_address":"192.34.62.151","network_port":40102,"online":true}}},"online":true},{"username":"Judas","location":{"path":"/0.0460747,1.54685,3.70029/0,-0.740174,0,0.672415","root":{"id":"6ea48bd6-3dda-47ba-b997-9a0e1872d499","name":"Music","domain":{"id":"967c4f19-9bd1-40ce-93f7-f13060713f9a","network_address":"192.34.62.151","network_port":40102,"online":true}}},"online":true},{"username":"jyoum","location":{"path":"/-0.791382,-0.606879,-0.605324/0,0.653395,0,0.757017","domain":{"id":"e1aed571-39a8-4a1a-9e08-99bffedf93fe","ice_server_address":"54.183.56.32"}},"online":true}]}}```  Upon switching visibility to everyone the following occurred:  ```Visible To Everyone
https://metaverse.highfidelity.com/api/v1/users?status=online
{"status":"success","data":{"users":[{"username":"jyoum","location":{"path":"/-0.791382,-0.606878,-0.605324/0,0.653395,0,0.757017","domain":{"id":"e1aed571-39a8-4a1a-9e08-99bffedf93fe","ice_server_address":"54.183.56.32"}},"online":true}]}}``. Successfully verified that I was displaying online to @Judasshuffle.
**Successful Logout/Crash:** Successful logout.

**Comment by Geenz** [comment]
It would be nice if it were resize all as well.

**Comment by imgntn** [comment]
@kevinmthomas - hmm okay i'll look into it

**Comment by imgntn** [comment]
@kevinmthomas-carpool couple of things i learned about that API:  1) if you're also logged in you would see yourself, so maybe use an incognito window 2) it can take typically take between 5 and 30 seconds (although i've seen upwards of a minute) for the change in online status to update, so could be a timing thing.   do you mind giving it another spin?  seems to be working for me if i give it a second to settle out.  also im online as jamespollack

**Comment by kevinmthomas-carpool** [comment]
@imgntn I can take another stab at it in a few you got it!

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**PR Build:** 7820
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** music
**Additional Test Results/Observations:** Tested PR with @imgntn and our visibility appeared appropriate to each other.
**Successful Logout/Crash:** Successful logout.

**Pull request merged**
