### PR TITLE
Procedural Material crashes in shadow pass  on deformed shape renderItems

### PR DESCRIPTION
**Pull request by samcake**
Now that avatars can potentially have their own custom pipeline, shadow pass needs to support it

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hd23408** [comment]
This is for https://github.com/highfidelity/hifi/pull/16470

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22392/HighFidelity-Beta-PR16470-86b62f9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22392/HighFidelity-Beta-Interface-PR16470-86b62f9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22392/HighFidelity-Beta-PR16470-86b62f9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22392/HighFidelity-Beta-Interface-PR16470-86b62f9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22392/HighFidelity-Beta-PR16470-86b62f9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22392/HighFidelity-Quest-Beta-PR16470-86b62f9.apk)

**Comment by HifiExperiments** [comment]
this one also needs the change in HighlightEffect.cpp

**Pull request merged**
