### PR TITLE
Fix duplicating multiple entities causing infinite looping

### PR DESCRIPTION
**Pull request by huffman**
Fixes https://highfidelity.manuscript.com/f/cases/17421/Cloning-multiple-entities-results-in-massive-entity-creation

### CODE REVIEW

**Comment by huffman** [comment]
# Test notes

  1. Go to the serverless tutorial ([hifi:///~/serverless/tutorial.json](url))
  1. Go into Create mode
  1. Create a cube and select it
  1. Alt-drag the cube to duplicate it
  1. Shift-click the original cube to select both cubes
  1. Alt-drag the cubes to duplicate them
  1. You should now have 4 cubes, with no noticeable issues. Previously interface would slow down considerably while continuously creating duplicate cubes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11908/HighFidelity-Beta-PR13770-61fdce9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11908/HighFidelity-Beta-PR13770-61fdce9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11908/HighFidelity-Beta-Interface-PR13770-61fdce9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11908/HighFidelity-Beta-PR13770-61fdce9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11908/HighFidelity-Beta-Interface-PR13770-61fdce9.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
FAIL @conklin94122 

The build crashed when trying to copy multiple entities at the same time. Specifically it fails between steps 5 and 6 on the above test plan.

5. Shift-click the original cube to select both cubes
6. Alt-drag the cubes to duplicate them

When attempting to alt-drag more than one entity, the program freeze for a few moments and then tells the user that it is no longer responding.

Attached is a screenshot of the crash and logs of the last three crashes.

multentitescrash
[hifi-log_2018-08-07_11.59.39.txt](https://github.com/highfidelity/hifi/files/2267800/hifi-log_2018-08-07_11.59.39.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2267801/hifi-log.txt)
[hifi-log_2018-08-07_11.52.47.txt](https://github.com/highfidelity/hifi/files/2267802/hifi-log_2018-08-07_11.52.47.txt)

**Comment by jakram** [comment]
My mistake @huffman! Currently testing.

**Comment by jakram** [comment]
@conklin94122 PASS

Deleting previous comment to avoid confusion.

**Comment by huffman** [comment]
Thank you @jakram !

**Pull request merged**
