### PR TITLE
add single quote tests to JS baking tests

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8215/app_12696_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8216/app_12696_PR.apk

**Comment by birarda** [comment]
Changes to test only, doesn't need QA

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8217/app_12696_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8217/HighFidelity-Beta-PR12696-74a7b65d33183a75961408c446e7deee076eb1ac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8217/HighFidelity-Beta-PR12696-74a7b65d33183a75961408c446e7deee076eb1ac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8218/HighFidelity-Beta-PR12696-ab4f110ea4e68aea09eb6b4da01d281c0a941ec9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8218/HighFidelity-Beta-PR12696-ab4f110ea4e68aea09eb6b4da01d281c0a941ec9.exe

**Pull request merged**
