### PR TITLE
Add animations to Avatar Transit

### PR DESCRIPTION
**Pull request by luiscuenca**
Continuing with the Avatar Transit work done in https://github.com/highfidelity/hifi/pull/14079
This PR add animations to the avatar before, meanwhile and after transit.
The objective is to give the observer a hint of what it's about to happen, specially when teleporting.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13819/HighFidelity-Beta-PR14187-2f10327.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13820/HighFidelity-Beta-PR14187-de1b6e7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13820/HighFidelity-Beta-PR14187-de1b6e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13820/HighFidelity-Beta-Interface-PR14187-de1b6e7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13842/HighFidelity-Beta-PR14187-52ed6cb.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13912/HighFidelity-Beta-PR14187-ad09007.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13912/HighFidelity-Beta-PR14187-ad09007.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13912/HighFidelity-Beta-Interface-PR14187-ad09007.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13912/HighFidelity-Beta-PR14187-ad09007.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13912/HighFidelity-Beta-Interface-PR14187-ad09007.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13962/HighFidelity-Beta-PR14187-7da5fa9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13962/HighFidelity-Beta-PR14187-7da5fa9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13962/HighFidelity-Beta-Interface-PR14187-7da5fa9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13962/HighFidelity-Beta-PR14187-7da5fa9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13962/HighFidelity-Beta-Interface-PR14187-7da5fa9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13970/HighFidelity-Beta-PR14187-078baa8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13970/HighFidelity-Beta-PR14187-078baa8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13970/HighFidelity-Beta-Interface-PR14187-078baa8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13970/HighFidelity-Beta-PR14187-078baa8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13970/HighFidelity-Beta-Interface-PR14187-078baa8.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14150/HighFidelity-Beta-PR14187-bb5c042.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14150/HighFidelity-Beta-Interface-PR14187-bb5c042.exe

**Comment by shanzzam** [comment]
Manuscript here https://highfidelity.manuscript.com/f/cases/19328/Animation-improvement-for-3ptv
This work was found during development of "Add animation poses to 3rd person teleport movement" that is in our initial RC75 Release notes, manuscript items filed out in development.

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to a domain with other avatars.
- When they teleport you should see them moving in a straight line to their destination. An animation should play during transit. 
- When you teleport you should move instantaneously to your destination (default behavior) and no animations should play on your own client

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14191/HighFidelity-Beta-PR14187-31d0999.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14191/HighFidelity-Beta-PR14187-31d0999.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14191/HighFidelity-Beta-Interface-PR14187-31d0999.exe

**Comment by ZappoMan** [comment]
There's still a mac/unix warning:

```

Rig.cpp:1141, Clang (LLVM based), Priority: Normal
--
comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long')

```

And a conflict in the file: `libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp`

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14229/HighFidelity-Beta-PR14187-e1c760b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14229/HighFidelity-Beta-PR14187-e1c760b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14229/HighFidelity-Beta-Interface-PR14187-e1c760b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14229/HighFidelity-Beta-PR14187-e1c760b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14229/HighFidelity-Beta-Interface-PR14187-e1c760b.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
@conklin94122 PASS

Teleporting is working as indicated.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14354/HighFidelity-Beta-PR14187-fa67e1b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14354/HighFidelity-Beta-Interface-PR14187-fa67e1b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14354/HighFidelity-Beta-PR14187-fa67e1b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14354/HighFidelity-Beta-Interface-PR14187-fa67e1b.exe

**Pull request merged**
