### PR TITLE
Address tablet scrollbar issues

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Edit:
- Entities list scrollbar works on the tablet (in desktop with mouse; in HMD with mouse, stylus/finger, and laser).
- Entity properties page's scrollbar works on the tablet (in desktop with mouse; in HMD with mouse, stylus/finger, and laser).

Known issue: Using the scrollbar in these pages can at times cause the content to vibrate up-and-down a little. If this is too much of a problem, it might be better to remove the scrollbars on the tablet.

Marketplace:
- On the tablet, scrollbars are not displayed for the HiFi, directory, and Clara.io pages.
- In a window, scrollbars are displayed for HiFi, directory, and Clara.io pages. And the same scrollbar styling is used for each.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c4414cff6083c75953940138162de1ccbc5be28 available at: https://gist.github.com/d88caa13974d323a914588205958e2c9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-9c4414c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-9c4414c.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-9c4414c.exe

Edit:
- PASS: Entities list scrollbar works on the tablet (in desktop with mouse; in HMD with mouse, stylus/finger, and laser).
- IMO FAIL: Entity properties page's scrollbar works on the tablet (in desktop with mouse; in HMD with mouse, stylus/finger, and laser).


Marketplace:
- PASS: On the tablet, scrollbars are not displayed for the HiFi, directory, and Clara.io pages.
- PASS: In a window, scrollbars are displayed for HiFi, directory, and Clara.io pages. And the same scrollbar styling is used for each.

Fails:
- Scrolling works as intended with the stylus, finger, mouse, and laser. The problem during scrolling is that the scroll bar stops scrolling consistently. I noticed that this happens when my mouse cursor, lasers, finger, stylus deviates too far off to the left or right. The borders to scroll within are too small. The Entities List window does not have this problem. It's the opposite. I can veer off far left or right without any penalty.
- The Left-Click button on the mouse gets stuck. Clicking on the scroll bar, once, freezes the (Hold+Left-Click) function. I was scrolling up and down without holding the mouse button.

**Comment by ctrlaltdavid** [comment]
@claudioshg 
- Not scrolling when move too far left/right off scroll handle: Which particular dialogs are you finding this a problem in?
- Left-click with mouse getting stuck: which particular dialogs are you encountering this problem in?

**Comment by claudioshg** [comment]
@ctrlaltdavid When scrolling in EDIT> PROPERTIES

**Comment by ctrlaltdavid** [comment]
Fixed not scrolling when move pointer too far off scroll handle in entity properties list.

"Mouse button pressed" getting stuck is a more general tablet problem that will be addressed in a separate PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a5c683192b06727a4675964392be616d44349df1 available at: https://gist.github.com/d88caa13974d323a914588205958e2c9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-a5c6831.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-a5c6831.dmg

**Comment by claudioshg** [comment]
Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10065-a5c6831.exe

@ctrlaltdavid I re-tested this PR. The EDIT> PROPERTIES scrolling handle problem is gone. Everything works great. PASS

**Pull request merged**
