### PR TITLE
Bloom and Temporal Anti-Aliasing improvements #12861 with a fix

### PR DESCRIPTION
**Pull request by samcake**
Same pr as  #12861 with a fix with mac
Same TEST PLAN

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9105/app_12984_PR_382161659e9adb8c8bcf7f8f6d1d4260ba7ecd8e.apk

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9121/app_12984_PR_f2c76abafa30317d5b6fb992286dcd1f55ab80d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9121/HighFidelity-Beta-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9121/HighFidelity-Beta-Interface-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9121/HighFidelity-Beta-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9121/HighFidelity-Beta-Interface-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9135/app_12984_PR_f2c76abafa30317d5b6fb992286dcd1f55ab80d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9135/HighFidelity-Beta-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9135/HighFidelity-Beta-Interface-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9135/HighFidelity-Beta-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9135/HighFidelity-Beta-Interface-PR12984-f2c76abafa30317d5b6fb992286dcd1f55ab80d4.exe

**Pull request closed without merging**
