### PR TITLE
BUGZ-1360: Avoid bad normal values leading to black pixels in Forward

### PR DESCRIPTION
**Pull request by samcake**
https://highfidelity.atlassian.net/browse/BUGZ-1360

This PR fixes the black pixels showing up in forward renderer due to the unpacking of normal map texel leading to unormalized normals which breaks the lighting equation as a consequence.
We added a protection on the unpacking equation in the shader to avoid that case and now it s fixed.

This also resolve the problem of these black pixels bleeding through the transparent surfaces

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21192/HighFidelity-Beta-PR16149-bc0f719.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21192/HighFidelity-Quest-Beta-PR16149-bc0f719.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21192/HighFidelity-Beta-PR16149-bc0f719.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21192/HighFidelity-Beta-Interface-PR16149-bc0f719.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21198/HighFidelity-Beta-PR16149-9c14838.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21198/HighFidelity-Quest-Beta-PR16149-9c14838.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21198/HighFidelity-Beta-PR16149-9c14838.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21198/HighFidelity-Beta-Interface-PR16149-9c14838.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21198/HighFidelity-Beta-PR16149-9c14838.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21198/HighFidelity-Beta-Interface-PR16149-9c14838.exe

**Pull request merged**
