### PR TITLE
restyle file browser

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This PR restyles the file browser and replaces the (Windows) drive drop-down plus editable path at the top of the dialog with a drop-down.

Testing:
Test on both Windows and OSX.
Test general dialog operation.
Test dialog can be used to choose files / directories:
- Running Scripts > From Disk
- Asset Browser > Choose File
- Settings > General > Snapshots > Browse
- Settings > General > Scripts > Browse

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f214a6b140a4bca12a859c1ecc49f1dd0451144 available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by RyanDowne** [comment]
Testing on PC - when I click on the Name, Date, etc it does nothing. I think this is true on master as well so you'd be fixing an existing bug to get this working.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0483585b85822a4d6220fefc8e08683a89d236f available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0483585b85822a4d6220fefc8e08683a89d236f available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17d41dd7b977c833e97961c64df3752ed574a73b available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by RyanDowne** [comment]
This dialog should be moveable I think

**Comment by hifi-gustavo** [comment]
Build console output for commit: dac043a52d5c7f47255373e10cad89446d3297be available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17b3101ca575669a4d36ff4f02c414fffcdac3af available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17b3101ca575669a4d36ff4f02c414fffcdac3af available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17b3101ca575669a4d36ff4f02c414fffcdac3af available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17b3101ca575669a4d36ff4f02c414fffcdac3af available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17b3101ca575669a4d36ff4f02c414fffcdac3af available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5a27d656c52d6524940d38a84d55799259c56e4b available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 504516b627341f601d13d335db40c95c8d910e47 available at: https://gist.github.com/7bda3b7bc5259bc4d9d7ec6fd098194a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7873.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Performance on MAC was completely unworkable.  Render rate averaging 30 and would take about 30 seconds before a moment would actually work in the Interface.  Unable to do anything.

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Per request of @ctrlaltdavid.  Installed commit ```5a27d65```.  Unable to connect to any domain but ```localhost``` and the new ```dev-demo.hifidelity.io```
.  Error in log stays ```limit of silent domains reached```. Log file attached for further inspection.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/278467/hifi-log.txt)

**Pull request merged**
