### PR TITLE
Small avatars now have a minimum jump height of 0.25 meters

### PR DESCRIPTION
**Pull request by hyperlogic**
This should improve the quality of the jump animation and improve the mobility of small avatars.

https://highfidelity.manuscript.com/f/cases/18148/Smallest-avatars-jump-is-stifiled

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
1) Open the interface.
2) In the tutorial, go to the Avatars station and choose any avatar.
3) One the avatar is loaded, navigate from the tool bar to Avatar Icon > Adjustments icon > Avatar Scale.
4) Most the slider to the left all the way to choose the smallest sized avatar.
5) Once adjusted, close out of the avatar app.
6) Press SPACE to what the avatar jump standing still.
7) Press SHIFT + 'w' and SPACE to make the avatar do a run jump.

The avatar jump will be slightly higher then master, but the animation quality should be improved when compared to master, i.e. not stifled or truncated.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14190/HighFidelity-Beta-PR14243-ef74014.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14190/HighFidelity-Beta-PR14243-ef74014.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14190/HighFidelity-Beta-Interface-PR14243-ef74014.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14190/HighFidelity-Beta-PR14243-ef74014.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14190/HighFidelity-Beta-Interface-PR14243-ef74014.dmg

**Comment by conklin94122** [comment]
As this PR didn't have a milestone QA was unaware it was ready for testing. The milestone has been set, QA will test.

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
