### PR TITLE
use ConvexHull shape for irregular "spheres"

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* entities that collide like "spheres" actually use ellipsoidal convexHull if they don't have a cubic bounding box

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
To test:

(1) Create a sphere entity
(2) Set its dimensions to something irregular like <1, 2, 3>
(3) Set the entity dynamic and give it gravity so that it falls to the ground
(4) Bump into the entity or thow it to convince yourself that it collides like an ellipse rather than a sphere.

**Comment by AndrewMeadows** [comment]
The internal bug for this is issue-2050:

https://highfidelity.fogbugz.com/f/cases/2050/Sphere-entity-collision-shape-does-not-match-when-spheroid

**Comment by ZappoMan** [comment]
Sweeeeeeeet!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b623f72c3a1f2a950de505b9a0477c6f97d6efd available at: https://gist.github.com/1f4088571aecd6fd1f2bcedf728683f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8998-4b623f7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8998-4b623f7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d2cec290d3b20add7c35c196982571e8be39929 available at: https://gist.github.com/1f4088571aecd6fd1f2bcedf728683f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8998-0d2cec2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8998-0d2cec2.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10

QA Pass

It's clear to me that this works - firstly it collides like its shape visually compared to like a sphere with current code.  Secondly, if ellipsoid is bumped such that its flatter face is up you can actually jump onto it and stand, briefly, until it slips away or rotates.  It doesn't seem to inject any changes to other shapes either that it shouldn't -- so, looks good to me.

**Pull request merged**
