### PR TITLE
Audio codec update for all platforms (includes Android)

### PR DESCRIPTION
**Pull request by kencooke**
This PR updates the audio codecs on all platforms, with these improvements:
- Adds an Android version of the codec
- Adds encoder and decoder support for first-order Ambisonics
- Fixes a HUGE slowdown in the Linux codec, which had somehow deployed a debug build
- Fixes a minor slowdown in the Mac codec, which was emulating the POPCNT instruction
- Built with the latest compilers

The changes are backward compatible and do not require a protocol change.
There should be no observable differences (except for performance).

### Build notes:
Windows library compiled with VS2017 15.4 for x64
MacOS library compiled with clang/LLVM 9.0.0 for x64
Linux library compiled with GCC 7.2 for x64
Android library compiled with NDK r15c for armeabi-v7a

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4800/HighFidelity-Beta-PR11780-6d019b43029d579ea1f01502f13b9b743492a5dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4800/HighFidelity-Beta-PR11780-6d019b43029d579ea1f01502f13b9b743492a5dd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4806/HighFidelity-Beta-PR11780-9a1386bf0d9c1ee157f6b4ec199eb2c9c3479b87.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4806/HighFidelity-Beta-PR11780-9a1386bf0d9c1ee157f6b4ec199eb2c9c3479b87.exe

**Comment by kencooke** [comment]
### Test Plan

This PR should probably be tested on all 3 platforms (Win, Mac, Linux). Just a quick smoke-test of audio is needed. There should be no functional changes.

1) Install Interface from this PR, and join dev-welcome or your own domain. The server from this PR is fine but not necessary.
2) Verify that incoming audio from the domain sounds clean.
3) Verify that your outgoing mic audio sounds clean. You can use server-echo to do this.
4) Open the Developer/Stats in the menu, click once on the stats, and verify you are using hifiAC (see below). You can also search the hifi-log.txt for "Selected Codec:"

image

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**[Windows Build]**

Install Interface from this PR, and join dev-welcome or your own domain. The server from this PR is fine but not necessary. **Check**
Verify that incoming audio from the domain sounds clean. **Check**
Verify that your outgoing mic audio sounds clean. You can use server-echo to do this. **Check**
Open the Developer/Stats in the menu, click once on the stats, and verify you are using hifiAC (see below). You can also search the hifi-log.txt for "Selected Codec:" **Checked in Stats**



**Pass**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4821/HighFidelity-Beta-PR11780-c324f342b4bae05044f9c072127dc8c009b85761.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4821/HighFidelity-Beta-PR11780-c324f342b4bae05044f9c072127dc8c009b85761.exe

**Comment by YuppyPlays** [comment]
@Kencooke does Windows require re-testing on latest Gustavo build?

**Comment by kencooke** [comment]
@YuppyPlays nope, Windows is unchanged. 
Still looking for someone to test Mac and Linux builds though.

**Comment by kencooke** [comment]
**[Linux Build]** 

**PASS** (verified by Seth)

**Comment by kencooke** [comment]
**[Android Build]**

**PASS** (verified by cduante)

**Comment by kencooke** [comment]
**[ MacOSX Build]**

**PASS** (verified by kencooke)

**Pull request merged**
