### PR TITLE
MS20501 [CreateApp/Properties] ignore scripted key events from the JSON Editors

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/20501/Delete-key-deletes-entity-when-entering-text

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16743/HighFidelity-Beta-PR14778-992ce9f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16743/HighFidelity-Beta-PR14778-992ce9f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16743/HighFidelity-Beta-Interface-PR14778-992ce9f.dmg

**Comment by qlimguicheteau** [comment]
Pass
- Delete key does not remove the entity when focus is set inside a field.
Fail
- HMD and Desktop modes react differently to the Delete key.
In Desktop mode the DEL key works as in a standard text editor.
In HMD mode, the DEL key removes the all text that seems connected to its right..
 Ex:  If the cursor was at | location  "hay|lloooooooo there" one use results in  "hay| there".

In HMD Tree mode, DEL will delete that entire code segment, and when all segments are gone will delete the object itself.

**Comment by huffman** [comment]
@qlimguicheteau Can you see if this doesn't also happen in current stable or dev?

**Comment by qlimguicheteau** [comment]
On Master(9886), int Tree mode, both HMD and Desktop completely delete the object when a text cursor is active and DEL is pressed.
The Behavior of the DEL key in the Code side is the same as described above.

**Comment by qlimguicheteau** [comment]
Okay, the strange text-deletion issue looks to be a non-issue for this PR,
And the Secondary HMD deletion in the Tree mode may qualify for different types of code changes, so it might be a separate bug.  I see. 

Okay then,

PASS
--
Primary deletion error has been removed.

**Pull request merged**
