### PR TITLE
Fix MS16701: Uninstall installed app before updating

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS16701](https://highfidelity.manuscript.com/f/cases/16701/updating-spectator-camera-2-2-to-2-3-gave-me-double-spectator-camera-app-buttons).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. On the Staging marketplace, purchase and install the [App v2.0 - Green Version](https://staging.highfidelity.com/marketplace/items/b2c128be-c62c-4b10-aae4-de1f807303f5).
2. Tell Zach that you've done this. Wait for him to tell you to continue. He will post an update to the App, bumping its version to v3.0.
3. Go to My Purchases. Verify that you have an update available to the app you purchased in (1).
4. Attempt to update the app. Verify that you see a popup explaining that you need to uninstall the app first. Click CANCEL.
5. Manually uninstall the app.
6. Attempt to update the app. Verify that you DO NOT see a popup explaining that you need to uninstall the app, but are instead taken to the update's Marketplace page.
7. Return to My Purchases. Reinstall the app from (1).
8. Attempt to update the app. Verify that you see a popup explaining that you need to uninstall the app first. Click CONTINUE. Verify that the app is uninstalled and that you are taken to the update's Marketplace page.
9. Update to the newest version of the app. Verify that it installs and runs correctly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11291/HighFidelity-Beta-PR13603-04f8560.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11291/HighFidelity-Beta-PR13603-04f8560.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11291/HighFidelity-Beta-Interface-PR13603-04f8560.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11291/HighFidelity-Beta-PR13603-04f8560.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11291/HighFidelity-Beta-Interface-PR13603-04f8560.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Popup displays correctly when app is install, does not display when app is uninstalled. Only 1 "Open" button displays in My Purchases after updating application

**Pull request merged**
