### PR TITLE
MS15529: Add secondary camera snapshot notification flag

### PR DESCRIPTION
**Pull request by zfox23**
A quick addition to implement [MS15529](https://highfidelity.manuscript.com/f/cases/15529/Secondary-camera-snapshot-notifications) for @NissimHadar.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Have the `Spectator Camera v2` app running:
    1. Download [this folder](https://www.dropbox.com/sh/udlx0afoknqmd9e/AABY_M1DdaKsoLTXwiRZCmDxa?dl=0) from Dropbox as a ZIP, then extract its contents anywhere on your computer.
    2. Drag `spectatorCamera.js` from <unzipped "v2.0" directory> onto Interface from this PR
    3. Say "Yes" when asked whether or not you want to run the script
- In `Settings -> General`, ensure the "Put my snapshots here" text field is filled-in.
- You're in an interesting domain that you're excited to take snapshots in 😄 

### Tests
1. Write down the XYZ coordinates of an "interesting location" in your domain (for example, `(0, 0, 0)`, or your avatar's current location (discoverable from GOTO)). Open the JS console (`CTRL + ALT + J`). Input the following command in the JS console and press enter (replacing what's in the angle brackets below):
    i. `Window.takeSecondaryCamera360Snapshot(JSON.stringify({x: <x coordinate of interesting location>, y: <y coordinate of interesting location>, z: <z coordinate of interesting location>}))`
2. Wait a few moments.
    i. Verify that you see a notification in the top right of your screen that a snapshot has been saved.
    ii. You see a `.jpg` 360 snapshot taken from the XYZ location from (1) in your snapshots directory
    iii. The 360 snapshot is in equirectangular format (i.e. its width is double its height)
3. Input the following command in the JS console and press enter (replacing what's in the angle brackets below):
    i. `Window.takeSecondaryCamera360Snapshot(JSON.stringify({x: <x coordinate of interesting location>, y: <y coordinate of interesting location>, z: <z coordinate of interesting location>}), false, false)`
4. Wait a few moments.
    i. Verify that you **DO NOT** see a notification in the top right of your screen that a snapshot has been saved.
    ii. You see a `.jpg` 360 snapshot taken from the XYZ location from (3) in your snapshots directory
    iii. The 360 snapshot is in equirectangular format (i.e. its width is double its height)
5. Using the Spectator Camera v2 app, turn on the Spectator Camera. Open the JS console (`CTRL + ALT + J`). Input the following command in the JS console and press enter:
    i. `Window.takeSecondaryCameraSnapshot()`
6. Wait a few moments.
    i. Verify that you **DO** see a notification in the top right of your screen that a snapshot has been saved.
    ii. You see a `.jpg` snapshot taken from the spectator camera's location in your snapshots directory
7. Open the JS console (`CTRL + ALT + J`). Input the following command in the JS console and press enter:
    i. `Window.takeSecondaryCameraSnapshot(false)`
8. Wait a few moments.
    i. Verify that you **DO NOT** see a notification in the top right of your screen that a snapshot has been saved.
    ii. You see a `.jpg` snapshot taken from the spectator camera's location in your snapshots directory

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10321/HighFidelity-Beta-PR13288-7f344c3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10321/HighFidelity-Beta-PR13288-7f344c3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10321/HighFidelity-Beta-Interface-PR13288-7f344c3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10321/HighFidelity-Beta-PR13288-7f344c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10321/HighFidelity-Beta-Interface-PR13288-7f344c3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Due to https://highfidelity.manuscript.com/f/cases/15472/Add-Back-Notification-Script-as-Default, I had to run the notification script to get notifications to work. This also occurred in Master. Notifications appear and look good.

**Pull request merged**
