### PR TITLE
Don't save user location if not connected to domain

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Check that your location is not remembered when you're at a domain with a protocol mismatch.

Find two hosted domains:
A: A domain you can successfully connect to, without a "protocol version mismatch" error.
B: A domain you cannot successfully connect to, with a "protocol version mismatch" error.

Go to some place in domain A. Note the domain and your current location coordinates (e.g., as reported in the diagnostics overlay displayed when you press "/").

Use the GOTO dialog to teleport to domain B and move about in it a little. Wait until after the "protocol mismatch" warning dialog. Note the domain and your current location coordinates.

Exit Interface.

Start up Interface.

You should resume at the location you were at in domain A (i.e., your last known "good" location).


2) Check that your location is remembered when you're connected to localhost.

Run the Sandbox server.

Go to some location on it and not your coordinates.

Restart Interface.

You should resume at your previous position.


3) Check that your location is remembered when you're at your serverless tutorial.

Go to the serverless tutorial. (Press the home button in the GOTO dialog.)

Restart Interface.

You should resume in the serverless tutorial.

Note: Your location will be reset to the default, start-up location for the tutorial. (This because the URL stored at Interface.json's "AddressManager/address" key is, "file:///~/serverless/tutorial.json".)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10453/HighFidelity-Beta-PR13337-8e1e93a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10453/HighFidelity-Beta-PR13337-8e1e93a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10453/HighFidelity-Beta-Interface-PR13337-8e1e93a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10453/HighFidelity-Beta-PR13337-8e1e93a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10453/HighFidelity-Beta-Interface-PR13337-8e1e93a.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10500/HighFidelity-Beta-PR13337-8e1e93a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10500/HighFidelity-Beta-PR13337-8e1e93a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10500/HighFidelity-Beta-Interface-PR13337-8e1e93a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10500/HighFidelity-Beta-PR13337-8e1e93a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10500/HighFidelity-Beta-Interface-PR13337-8e1e93a.exe

**Comment by qlikmorales** [comment]
Currently Testing

**Comment by qlikmorales** [comment]
@conklin94122 
PASS

**Pull request merged**
