### PR TITLE
Various shadow bug fixes

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes bugs:
- [#17108](https://highfidelity.manuscript.com/f/cases/17108/Shadows-don-t-render-if-shadow-frustum-starts-inside-opaque-object-s-bounding-box)
- [#16723](https://highfidelity.manuscript.com/f/cases/16723/Rendering-Shadow-Grazing-test-image-doesn-t-match-expected-test-image)
- [#17106](https://highfidelity.manuscript.com/f/cases/17106/Grazing-angle-shadows)

It partially fixes bug [#17286](https://highfidelity.fogbugz.com/f/cases/17286/Shadow-resolution-bug-and-other-shadow-issues#BugEvent.113869) (only the faint rectangular outline bug, not the loss of resolution).

It could also possibly fix bug [#16198](https://highfidelity.manuscript.com/f/cases/16198/Shadow-rendering-issue-in-Maker-domain) but I can't verify this as the Maker domain's protocol isn't compatible with master.

The PR also fixes the Luci visualisation of the depth buffer and shadow cascade indices.

# TEST PLAN
1. Run all _tests/engine/render/shadows_ tests from this update in [hifi_tests PR #248](https://github.com/highfidelity/hifi_tests/pull/248)
2. Also: go to a domain where shadows are visible (Home for instance), run the _developer\utilities\workload\workload.js_ script as described in bug report #17108, click the Workload button on the task bar 
- in the newly appeared app, check the "Show views" checkbox: shadows should remain the same and still be visible
- in the newly appeared app, check the "Show proxies" checkbox: shadows should remain the same and still be visible

3. Run all _tests/content/overlay_ tests from master as the fix for Luci may have some incidence on the overlays.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11767/HighFidelity-Beta-PR13731-d1d6782.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11767/HighFidelity-Beta-Interface-PR13731-d1d6782.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11767/HighFidelity-Beta-PR13731-d1d6782.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11767/HighFidelity-Beta-Interface-PR13731-d1d6782.exe

**Comment by Zvork** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11768/HighFidelity-Beta-PR13731-d1d6782.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11768/HighFidelity-Beta-PR13731-d1d6782.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11768/HighFidelity-Beta-Interface-PR13731-d1d6782.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11865/HighFidelity-Beta-PR13731-d457cf4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11865/HighFidelity-Beta-PR13731-d457cf4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11865/HighFidelity-Beta-Interface-PR13731-d457cf4.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Shadows look good.

**Comment by samcake** [comment]
we will need to merge with the new shader tool chain and to qa again.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11933/HighFidelity-Beta-PR13731-2584ce4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11933/HighFidelity-Beta-PR13731-2584ce4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11933/HighFidelity-Beta-Interface-PR13731-2584ce4.dmg

**Comment by Zvork** [comment]
To validate this PR I have to reupdate the shadow tests. Unfortunately there seems to be a bug with zone management in master that prevents to correctly set a zone from the test scripts, @samcake . I tried with the material tests and there's the same issue.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11933/HighFidelity-Beta-PR13731-2584ce4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11933/HighFidelity-Beta-Interface-PR13731-2584ce4.exe

**Comment by samcake** [comment]
need qa review again please

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
