### PR TITLE
Implements landscape mode for tablet as rotation instead of stretching [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by vladest**
Test plan:
- Open tablet, press Create button
- make sure Tablet rotated and everything works in Landscape mode
- close Create mode. Make sure Tablet returned back to portrait

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/306/HighFidelity-Beta-PR10589-b0e4b752d5c58208b2a8d0028177727d3a70af69.exe

**Comment by CainFoool** [comment]
Hey @vladest: Is this ready for QA?

**Comment by sethalves** [comment]
@CainFoool yes go ahead

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/306/HighFidelity-Beta-PR10589-b0e4b752d5c58208b2a8d0028177727d3a70af69.dmg

**Comment by CainFoool** [comment]
Alright @sethalves - Testing momentarily.

**Comment by CainFoool** [comment]
# Test Passed 

Tablet rotates as expected, however regardless of where you place the tablet on the screen, it always seems to go back to the middle of the screen when it's rotated. See gif.
35zd5

**Comment by sethalves** [comment]
Is anyone able to test with an HMD on?

**Comment by CainFoool** [comment]
Will retest with a HMD.

**Comment by CainFoool** [comment]
# Test Failed (HMD)

The tablet screen rotated, the tablet itself however did not - and it did it with a slight tilt which persisted through opening and closing the tablet and would not clear up until a relaunch, however it continues to happen. (See screenshots)
74wcn


c7xb2

**Comment by vladest** [comment]
Please test again in HMD mode

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/365/HighFidelity-Beta-PR10589-8068e7201d764986b4633ae1148610d45c02db3d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/365/HighFidelity-Beta-PR10589-8068e7201d764986b4633ae1148610d45c02db3d.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Open tablet, press Create button **Pass**
make sure Tablet rotated and everything works in Landscape mode **Pass** Tested creating objects, going through properties, etc.
close Create mode. Make sure Tablet returned back to portrait **Pass** 

Also can confirm it does not reset position as it did in previous tests, it now changes whilst in its last location.

**Pull request merged**
