### PR TITLE
fix for cleanup of SettingsManager thread

### PR DESCRIPTION
**Pull request by birarda**
This is a fix for `QObject::killTimer: Timers cannot be stopped from another thread`

### CODE REVIEW

**Comment by birarda** [comment]
@Atlante45 would you look at this to make sure it makes sense in the context of the SettingsManager and qAddPostRoutine

**Comment by birarda** [comment]
Accidentally pulled in some other commits with the rebase but the diff is correct.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f63e55ec5c8f85137fa45151eb206e292218ad85 available at: https://gist.github.com/4326b6aa9bef66d70046<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1cb12bd1dae5e8b20a2281564b4f99a884e74b99 available at: https://gist.github.com/4326b6aa9bef66d70046<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d5b8c430a281ec4ade9e4345aff49aa5fea8218 available at: https://gist.github.com/4326b6aa9bef66d70046<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4539.dmg

**Pull request merged**
