### PR TITLE
Add README.md file to tools/jsdoc/out dir to prevent jsdoc build failures

### PR DESCRIPTION
**Pull request by hyperlogic**
When building the hifi repo the first time, users will hit a difficult to diagnose build failure due to the fact this output directory does not exist.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/19864/error-MSB3073-when-trying-to-Build-cmake

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17397/HighFidelity-Beta-PR14957-9a0163f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17397/HighFidelity-Beta-PR14957-9a0163f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17397/HighFidelity-Beta-Interface-PR14957-9a0163f.dmg

**Comment by hyperlogic** [comment]
some weird jenkins git pull failure.  let's try again.  build this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17463/HighFidelity-Beta-PR14957-9a0163f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17463/HighFidelity-Beta-PR14957-9a0163f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17463/HighFidelity-Beta-Interface-PR14957-9a0163f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17463/HighFidelity-Beta-PR14957-9a0163f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17463/HighFidelity-Beta-Interface-PR14957-9a0163f.exe

**Pull request merged**
