### PR TITLE
Commerce: Send Money Nearby particle effect!

### PR DESCRIPTION
**Pull request by zfox23**
Adds an optional particle effect to nearby HFC transfers. Enjoy!

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6807/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6807/HighFidelity-Beta-PR12315-33ff668e5181a47689e0e7444966499c8ed1d929.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6827/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6827/HighFidelity-Beta-PR12315-bd26c9dfc0fc922a0e635af5641f4284112277c9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6832/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6833/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6834/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6836/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6836/HighFidelity-Beta-PR12315-89e52561e39c0f117bdeb85825b9ee27532c99a6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6836/HighFidelity-Beta-PR12315-89e52561e39c0f117bdeb85825b9ee27532c99a6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6846/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6846/HighFidelity-Beta-PR12315-dd2b7eb10703b93550a4704e91e2f345d7429264.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6846/HighFidelity-Beta-PR12315-dd2b7eb10703b93550a4704e91e2f345d7429264.exe

**Comment by zfox23** [comment]
## Test Plan
- This test plan requires two Interface clients and at least one HMD user.
- Have Avatar A and Avatar B enter Sandbox A. Ensure that _neither_ of their availabilities are set to "Appear Offline".
- Have Client A start the below test in HMD (Step 5 switches you to Desktop mode)
- Have Avatar A perform all of the steps below.
1. Open the Wallet -> Send Money tab. Select "Nearby". Select Avatar B.
2. On the confirmation screen, ensure that the "Show Effect" checkbox is CHECKED by default.
3. Click on the "[?]" link next to the "Show Effect" checkbox. Verify that the popup that appears "makes sense" and contains no visual errors.
4. Close the "Show Effect" lightbox popup. Click the "SUBMIT" button. **Verify that, when you see the "Payment Sent" screen, you also see a very pretty particle effect jump between you and Avatar B.**
5. Perform steps 1-4 in Desktop mode, then continue to step 6 below.
6. Open the Wallet -> Send Money tab. Select "Nearby". Select Avatar B.
7. On the confirmation screen, ensure that the "Show Effect" checkbox is CHECKED.
8. Uncheck the "Show Effect" checkbox, then close the wallet.
9. Open the Wallet -> Send Money tab. Select "Nearby". Select Avatar B.
10. On the confirmation screen, ensure that the "Show Effect" checkbox is UNCHECKED.
11. Open the Wallet -> Send Money tab. Select "Connection". Select some random connection.
12. On the confirmation screen, ensure that the "Show Effect" checkbox is NOT VISIBLE.
13. *Try to break the "Send Money" particle effect!* For example, ensure the "Show Effect" checkbox is checked, then try sending money while really far away, or while one or both avatars are moving around, etc. Ensure the particle effect still looks great in as many circumstances as you can think of.

**Comment by howard-stearns** [comment]
Additional test: maybe check that it looks right from a third-person observer.

**Comment by howard-stearns** [comment]
Have either party exit while the effect is on?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6875/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6876/app_12315_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6876/HighFidelity-Beta-PR12315-f26477b3e16d00215593b51c296c05cef2e5c167.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6876/HighFidelity-Beta-PR12315-f26477b3e16d00215593b51c296c05cef2e5c167.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122

**Pull request merged**
