### PR TITLE
Show Server Console Version

### PR DESCRIPTION
**Pull request by imgntn**
This PR displays the server console version.

To test: 
1. Install this build and start the server console.
2. Right click and observe the version number in the list!

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23fd2e93b523a370dca7605eaa9bf9f93ecf8584 available at: https://gist.github.com/4e7f0d3f399012dbb83c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7331.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7331.dmg

**Comment by imgntn** [comment]
https://app.asana.com/0/search/100200841818872/99197097766893

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42e3d0bdadc40c96e8e9a1aee915d7869dc120ca available at: https://gist.github.com/4e7f0d3f399012dbb83c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7331.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7331.dmg

**Comment by Nex-Pro** [comment]
Works fine on Win10 64bit.  
serverconsole7331

**Pull request merged**
