### PR TITLE
fix auto-unequip

### PR DESCRIPTION
**Pull request by sethalves**
- adjust some values so that it's easier to unequip something by pulling it away from the hand

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1369/pulling-an-equipped-item-away-from-the-hand-should-unequip-it

**Comment by sethalves** [comment]
to test:
- ready your hand controllers
- equip something
- with your free hand, grab the thing and pull it away from your equipping hand
- when released by the previously free hand, the thing should no longer be equipped

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc22b579f749827f6b278af15a38cd29247dbe7b available at: https://gist.github.com/a9717a354047e58baee975eec0190425<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-dc22b57.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-dc22b57.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e59c010642a4e376c293cbe7d677d50f1cbf6d73 available at: https://gist.github.com/a9717a354047e58baee975eec0190425<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-e59c010.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-e59c010.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 090a0a6e9a7f9fc85184f80bb76410ec80172b51 available at: https://gist.github.com/a9717a354047e58baee975eec0190425<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-090a0a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8378-090a0a6.dmg

**Pull request merged**
