### PR TITLE
Relax deadlock watchdog

### PR DESCRIPTION
**Pull request by ZappoMan**
- Deadlock watchdog is relaxed to 2 minutes before a crash is forced
- The "meta verse stats" now included deadlock watchdog data in it's regular stats checkin so we can better see if people on low end machines are experiencing long sections of unresponsive behavior
- A new debug menu is added to "force" an unresponsive state of 35 seconds to help test this feature

# Test plan
- Run this build and do basic startup/smoke test to ensure that nothing obvious is broken
- Choose Debug > Unresponsive Interface -- see that the application pauses for 35 seconds, but does not crash
- Check the log file and see that after the 35 second pause a message is displayed as follows:
```
[02/22 17:47:43] [DEBUG] [hifi.interface] Intentionally cause Interface to be unresponsive for  35  seconds
```
and that several messages of the following format are displayed
```
[02/22 17:48:16] [DEBUG] [hifi.interface.deadlock] DEADLOCK WATCHDOG WARNING: lastHeartbeatAge: 33075317 elapsedMovingAverage: 822 PREVIOUS maxElapsed: 32074849 NEW maxElapsed: 33075317 ** NEW MAX ELAPSED ** maxElapsedAverage: 822 samples: 882
[02/22 17:48:17] [DEBUG] [hifi.interface.deadlock] DEADLOCK WATCHDOG WARNING: lastHeartbeatAge: 34075478 elapsedMovingAverage: 822 PREVIOUS maxElapsed: 33075317 NEW maxElapsed: 34075478 ** NEW MAX ELAPSED ** maxElapsedAverage: 822 samples: 882
```
- Choose Debug > Deadlock Interface -- see that the application will pause for 2 minutes and then crash
- After running these tests, please contact me and let me know so I can check our metabase database to verify that the deadlock watchdog stats were sent for your session.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7453/app_12484_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7453/HighFidelity-Beta-PR12484-9f68accb302e6ea59120a9bb5717df00e2788fc7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7453/HighFidelity-Beta-PR12484-9f68accb302e6ea59120a9bb5717df00e2788fc7.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 

@ZappoMan 2 Deadlock crashes were performed, checking to see if they appear on your end.

**Comment by ZappoMan** [comment]
@qlimnavarro - I am not seeing any metaverse data from you for this PR. I ran this same PR and I do see my own metaverse data. 

Did you disable "Send Data"? 
Were you logged in?
When did you run this test?
Can you please send me your log files from when you ran your test. (send them to me on slack please)

**Comment by qlimnavarro** [comment]
@ZappoMan Retested and doubled checked Staging environment variable. Originally I was logged into asusrog35 in both highfidelity.com and the Interface.

**Comment by ZappoMan** [comment]
After looking at the staging server - I do see your traffic. So this is a pass.

**Pull request merged**
