### PR TITLE
Stack manager - integration checkpoint

### PR DESCRIPTION
**Pull request by murillodigital**
Integrating stack manager into primary repo, adding zlib and quazip as externals. Stack Manager release is still NOT built off this, this is just an initial step towards that goal.

Added packaging code for OS X releases to remove need for outside scripted handling.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fee50a56e5e1882611fcebd81a5d52ed07400e3c available at: https://gist.github.com/fe9f92d4cddc9a1ad925<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 66803ce3566906c84efd19fcb641cf8959f84169 available at: https://gist.github.com/22414c94e28ea9e0351a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d58b11f0a2ba325bec0a84092f24fcef7a8825a6 available at: https://gist.github.com/22414c94e28ea9e0351a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f759fa2cfa24b10a9c5a0eeee2aed24bb50bf572 available at: https://gist.github.com/22414c94e28ea9e0351a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6472.dmg

**Pull request merged**
