### PR TITLE
72: send MyAvatar avatar entity updates through entity tree

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Make sure you are using an avatar with wearables (there are a couple of options in the Avatar app. Using the Avatar app, open the "Wearables" dialog. Click Cancel. With this PR, your number of wearables should not increase or double. On master your number of wearables increases or doubles.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12491/HighFidelity-Beta-PR13902-77fe4c4.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12495/HighFidelity-Beta-PR13902-4afc198.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12491/HighFidelity-Beta-PR13902-77fe4c4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12491/HighFidelity-Beta-Interface-PR13902-77fe4c4.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Pull request merged**
