### PR TITLE
Fix Window API position and size reporting

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes and makes consistent:
- Window.x, .y, innerWidth, innerHeight
- Window.geometryChanged()
- Window.getDeviceSize()

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Desktop mode with Interface running as a window, run the attached script. It reports Window properties, Window.geometryChanged() values, and Window.getDeviceSize(). All values reported should be the same when you:
(a) Start the script.
(b) Move the window.
(c) Resize the window from the top left corner.
(d) Resize the window from the bottom right corner.

2) Check that the x, y, width, and height values reported are correct. (E.g., do a screen snap, paste the snap into an image editor, and measure the values.)
x, y: display coordinate of the top left of the "drawable" interior of the Interface window (i.e., where the world view is rendered, excluding menu bar and window borders etc.).
width, height: the size of the "drawable" interior of the Interface window.

3) Check that the tablet displays correctly in portrait and landscape (e.g., in Create app) modes.

4) Check that the spectator camera app works correctcly: run the Spectator Camera test plan (526) - confirm that view on viewfinder matches the display on screen with pixel perfection (not cropped).

5) Run Create Mode test plan (1938) - confirm pages look correct in desktop / HMD mode.

6) Confirm that raising/lowering keyboard on tablet functions properly in both desktop / HMD mode.

7) Check that Interface starts up at the same size and position as when it was closed.

[testWindowGeometry.zip](https://github.com/highfidelity/hifi/files/1873588/testWindowGeometry.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8464/HighFidelity-Beta-PR12777-095c1b837c43ba9bb387cff37b34d8fde8081f14.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8464/HighFidelity-Beta-PR12777-095c1b837c43ba9bb387cff37b34d8fde8081f14.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Window sizes are consistent and look good. All other features work as expected.

**Pull request merged**
