### PR TITLE
reduce sound from crashed avatars

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9ad29387d5e72a6b7c43ff30d486ee5216c4f62 available at: https://gist.github.com/281e56cdc1037583f04d5cfbdf9f86f2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-d9ad293.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-d9ad293.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9ad29387d5e72a6b7c43ff30d486ee5216c4f62 available at: https://gist.github.com/281e56cdc1037583f04d5cfbdf9f86f2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-d9ad293.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-d9ad293.dmg

**Comment by zzmp** [comment]
Testing locally

**Comment by zzmp** [comment]
QA:

- Run the server
- Connect to it
- Have someone else (avatar B) connect to it
- Have avatar B hum loudly and crash while humming (*not quit, crash - use the developer menu to induce a crash*)

On master, the crashed avatar's sound will fade out over 3+ seconds.
On this PR, the crashed avatar's sound should fade out within half a second.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3bea1069f2a456ed4e3e338dba8b54b0b7b8bec4 available at: https://gist.github.com/281e56cdc1037583f04d5cfbdf9f86f2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-3bea106.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8878-3bea106.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
@thoys can you assist?

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test. Tested with @thoys as he successfully made a humming sound and manually crashed himself. The sound lasted about a half a second.

**Pull request merged**
