### PR TITLE
Os window vs modal overlay in script editor

### PR DESCRIPTION
**Pull request by howard-stearns**
Disable the closing of script editor (or a tab in the script editor) when asking the user about whether to reload due to an external file change.

Also, don't ask over and over again after the user says no -- until the external file changes again.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/101207921338605

**Comment by howard-stearns** [comment]
testing notes in ticket

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cbddb217cf8f1894363f6af2d3e86083993b7ad available at: https://gist.github.com/6d154aecc08b7b80ed97<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7388.dmg

**Comment by howard-stearns** [comment]
code review notes:
Read the code from the bottom up:
- A new ivar and method in ScriptEditorWindow.h.
- Two uses (in the close and tab close callbacks), and the method definition in ScriptEditorWindow.cpp.
- ScriptEditorWidget.cpp mostly just breaks the existing code into two parts, so that the first part where the dialog does a blocking open can now seth that ivar and reset it after.  (The other change is to set update the _currentScriptModified as noted in the second part of the high-level PR description above.)

**Comment by cozza13** [comment]
tested this and did not crash. I had to accept the update dialog before closing the script editor

**Pull request merged**
