### PR TITLE
Possible fix for getContainingElement crash.

### PR DESCRIPTION
**Pull request by howard-stearns**
Make access to entityToElementMap thread safe.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/103221698547796

**Comment by ZappoMan** [comment]
Testing Notes:
- Run a basic smoke test.
- Make sure you can connect to several domains
- Try rapidly switching domains

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88585592470af655c96b06585b266e1e91c3fe1f available at: https://gist.github.com/a3c42d2d77c2712335ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7415.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7415.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Basic smoke test.  Changed domains rapidly between 5distinct named places 10+ times, no crash.  Previously that was > 50% chance of crash.  :+1:

**Pull request merged**
