### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7433/app_12477_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7433/HighFidelity-Beta-PR12477-7bad82818b86748c7a853d3f0f08d161e4321a01.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7542/app_12477_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7542/HighFidelity-Beta-PR12477-7bad82818b86748c7a853d3f0f08d161e4321a01.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7542/HighFidelity-Beta-PR12477-7bad82818b86748c7a853d3f0f08d161e4321a01.dmg

**Pull request merged**
