### PR TITLE
Beta Release 15 - Includes up to Developer Release 5103

### PR DESCRIPTION
**Pull request by ZappoMan**
- Don't entering independent camera mode through edit.js in HMD mode
- Mini mirror/multi-monitor bug fixes
- Cleamup camera scripting interface
- Fix bugs with Entities.addEntity
- Reduce users window flicker when restart script
- Vive UI improvements
- Fix metadata hours parsing on mac
- Improve hand controller pointer accuracy
- Limit hand controller actions to recommended area
- Simplify domain connection refusal dialog checking
- Updates to bow and arrow
- Limit static mesh vertex count
- Update reticle from hand controllers only when triggered
- Don't automatically hide the Tool window when toggling the pinned state on the desktop 
- Remove the head pose roll from the cursor transformation
- Fix snapshot dialog rendering
- Allow scripts to receive a visibility changed signal from their windows
- Allows the ability to override position and radius of equip-hotspot 
- Allows multiple equip-hotspots per entity with different attach-points per hotspot. 
- Allows the user to equip an object while near or far grabbed by the other hand. 
- Don't render wire geometry with lighting effects
- Distinguish between file name and directory as prompt in file chooser
- The HUD/Switch/Mute/Goto/Examples/Edit buttons now have an "activated" visual that reflects their state.
- When the keyboard is dismissed, unfocus the text field in a window 
- Don't auto-focus text fields when opening most dialogs 
- Properly render UI coloring based on activeFocus, not focus
- Fix multiple sessions being created for some users

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e784d7c400a831636db6ae2de50be6773d073e7f available at: https://gist.github.com/2b4e018365cc72681709f107d1713165<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8181.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8181.dmg

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: I did not have access to dev-playa so I could not test it. I used Playa instead for the performance test.

**Domain** |localhost | |dev-demo
---|---|---|---
**Render Rate**: |60 | |51
**Present Rate**: |60 | |60
**Present New Rate**: |60 | |50
**CPU Buffer Count**: |4695 | |4209
**GPU Buffer Count**: |948 | |857
**CPU Memory Usage**: |62738432 | |75493376
**GPU Memory Usage**: |26005504 | |38658048
**CPU Texture Count**: |183 | |273
**GPU Texture Count**: |2199 | |2437
**GPU Transfer Count**: |0 | |0
**CPU Texture Memory Usage**: |209406392 | |348247304
**GPU Texture Memory Usage**: |418668001 | |960376431
**GPU Virtual Memory Usage**: |611113441||1152821871
**Triangle Count**: |498848 | |800033
**Triangle Rate**: |31178000 | |50002062
**API Drawcall Count**: |286 | |281
**Drawcall Count**: |419 | |283
**Drawcall Rate**: |26187 | |17687
**State Changes Texture Count**:|209 | |316
**Pipeline Count**: |34 | |40
**Item Opaques**: |339 | |300
**Item Translucents**: |44 | |52
**Item Lights**: |20 | |26
**Timing Opaques**: |1754 | |1617
**Timing Translucents**: |163 | |306
**Timing Lighting**: |129 | |127
**Render Frame**: |2740 | |2733

**Comment by Nex-Pro** [comment]
#### QA Test
**QA Tester**: Piper.Peppercorn

##### OS used: OSX El Capitan
##### CPU: Intel i7 4.4 ghz
##### Ram: 16 GB
##### GPU: 2gb nvidia GTX770
##### HMDs: none
##### Controllers: none

**localhost 'createTestBlocks.js' Result**: SUCCESS**localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |8549 |7652 |6969
**GPU Buffer Count**: |1400 |1194 |1465
**CPU Memory Usage**: |178790400 |157343744 |157118464
**GPU Memory Usage**: |97427456 |99004416 |93978624
**CPU Texture Count**: |773 |657 |651
**GPU Texture Count**: |2084 |2002 |1993
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |535055256 |360925808 |378800752
**GPU Texture Memory Usage**: |2468810787 |2293627045 |2244693495
**GPU Virtual Memory Usage**: |2632672291|2457488549|2408554999
**Triangle Count**: |232066 |340969 |710141
**Triangle Rate**: |13650941 |21310562 |41773000
**API Drawcall Count**: |170 |112 |256
**Drawcall Count**: |255 |234 |1259
**Drawcall Rate**: |15000 |14625 |74058
**State Changes Texture Count**:|144 |135 |286
**Pipeline Count**: |28 |23 |42
**Item Opaques**: |207 |168 |252
**Item Translucents**: |12 |10 |52
**Item Lights**: |18 |21 |26
**Timing Opaques**: |3151 |3401 |3843
**Timing Translucents**: |95 |49 |415
**Timing Lighting**: |161 |170 |167
**Render Frame**: |3982 |4227 |5030

**Comment by Nex-Pro** [comment]
**PR Build:** #8081
**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None

**QA Tester**: Piper.Peppercorn


**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**: 

***Some dialogs are not displaying on top such as load script from url.*** 
***Also occurs in OSX on same hardware***

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |3189 |5987 |4058
**GPU Buffer Count**: |954 |1328 |809
**CPU Memory Usage**: |53796864 |96083968 |71823360
**GPU Memory Usage**: |33460224 |52776960 |35438592
**CPU Texture Count**: |188 |425 |272
**GPU Texture Count**: |1975 |2100 |1744
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |179533480 |445875720 |330734344
**GPU Texture Memory Usage**: |413610820 |1417432172 |848069520
**GPU Virtual Memory Usage**: |587470660|1591292012|1021929360
**Triangle Count**: |470341 |1101451 |737929
**Triangle Rate**: |27667117 |64791235 |43407588
**API Drawcall Count**: |265 |299 |287
**Drawcall Count**: |311 |361 |1389
**Drawcall Rate**: |18294 |21235 |81705
**State Changes Texture Count**:|218 |344 |317
**Pipeline Count**: |34 |33 |44
**Item Opaques**: |336 |480 |303
**Item Translucents**: |40 |47 |55
**Item Lights**: |23 |46 |26
**Timing Opaques**: |1782 |2800 |4662
**Timing Translucents**: |146 |178 |1422
**Timing Lighting**: |123 |222 |760
**Render Frame**: |2739 |4135 |9152

dialogincorrectorder

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: No issues, expected behavior.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |51
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |48
**CPU Buffer Count**: |4038 |1809 |5100
**GPU Buffer Count**: |649 |305 |830
**CPU Memory Usage**: |64868352 |39591936 |107327488
**GPU Memory Usage**: |23252992 |18022400 |49410048
**CPU Texture Count**: |180 |111 |347
**GPU Texture Count**: |613 |609 |889
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |205964408 |103154168 |470736720
**GPU Texture Memory Usage**: |335296377 |244218398 |907039880
**GPU Virtual Memory Usage**: |503580537|412502558|1075324040
**Triangle Count**: |265370 |124551 |742793
**Triangle Rate**: |16585625 |7326529 |46424562
**API Drawcall Count**: |190 |65 |256
**Drawcall Count**: |324 |66 |1526
**Drawcall Rate**: |20250 |3882 |95375
**State Changes Texture Count**:|158 |58 |297
**Pipeline Count**: |30 |22 |40
**Item Opaques**: |225 |120 |253
**Item Translucents**: |15 |4 |53
**Item Lights**: |17 |19 |26
**Timing Opaques**: |1553 |683 |1532
**Timing Translucents**: |208 |115 |385
**Timing Lighting**: |207 |186 |145
**Render Frame**: |2828 |1750 |2776

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Performance test gives a huge spike at dev-demo
dev-demo-spike-pr8181

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |59
**CPU Buffer Count**: |7055 |1478 |3257
**GPU Buffer Count**: |1631 |324 |761
**CPU Memory Usage**: |117731328 |25063424 |61292544
**GPU Memory Usage**: |72572928 |10412032 |35819520
**CPU Texture Count**: |416 |163 |278
**GPU Texture Count**: |1988 |2123 |2197
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |261565912 |170276544 |227293832
**GPU Texture Memory Usage**: |1179552990 |284368084 |867289913
**GPU Virtual Memory Usage**: |1322366430|427181524|1010103353
**Triangle Count**: |1261518 |122296 |715434
**Triangle Rate**: |78844875 |7643500 |44714625
**API Drawcall Count**: |297 |72 |279
**Drawcall Count**: |355 |74 |1378
**Drawcall Rate**: |22187 |4625 |86125
**State Changes Texture Count**:|314 |45 |325
**Pipeline Count**: |49 |24 |45
**Item Opaques**: |353 |232 |299
**Item Translucents**: |40 |14 |55
**Item Lights**: |29 |34 |28
**Timing Opaques**: |4257 |1112 |2588
**Timing Translucents**: |337 |53 |458
**Timing Lighting**: |306 |263 |246
**Render Frame**: |6135 |2484 |4318

Using HTC-Vive:
**EYE-01 Test Result**: **EYE-01 Test** SUCCESS
**EYE-02 Test Result**: **EYE-02 Test** SUCCESS
**EYE-03 Test Result**: **EYE-03 Test** SUCCESS
**EYE-04 Test Result**: **EYE-04 Test** SUCCESS
**EYE-05 Test Result**: **EYE-05 Test** SUCCESS
**EYE-06 Test Result**: **EYE-06 Test** SUCCESS
**EYE-07 Test Result**: **EYE-07 Test** SUCCESS
**Additional Test Results + Observations**: Eye tests work as expected


Have repeated the performance test 3 times at dev-demo each time I got the same result. I have no idea if this should fail the entire QA. So I will fail the QA until that is cleared up.

QA-Fail

**Comment by OmegaHeron** [comment]
There's a definite severe drop in performance with this build loading localhost content vs last RC (build 5086).  Since I can't capture data using js tools (it simply skips any "bad parts" as it has no ability to record data when it's not working) I'm left with having to use a screen capture method.  And, since efficient screen capture attached to framebuffer terminates when it erroneously thinks Interface is done - I have to use a more creative capture approach.  I'll be attaching captures when processing is complete.

QA Fail.

**Comment by thoys** [comment]
Dev-Demo seems fixed for me now, @cozza13 requested me to re-test it. Did someone remove something there? Would be interesting to know what caused it.

image

QA-Successful

**Comment by OmegaHeron** [comment]
I'm withdrawing my QA Fail as well - while it does fail for loading localhost content - there's no specific constant failure mode or any one DEV build leading up to this PR exhibiting a measurable performance hit.  It seems more likely it's a known issue with ATP/UDT manifesting on my machine.  Having ran many additional tests using stacks on LAN and over net - I find failures seen too random to quantify as a hard fail and mostly come from very high speed ATP transfers as seen on LAN/Localhost.  Having discussed that failure mode with @ZappoMan yesterday, and with additional testing this morning I believe it's, most likely what led me to fail this PR is actually present in past RC with it being a matter of luck whether or not it manifests fully, partially or not at all.

**Pull request merged**
