### PR TITLE
Winter Smash up Target Practice game

### PR DESCRIPTION
**Pull request by thoys**
This is the pull request for Worklist jobs: #20736, #20737 and #20751

- Target practice game (shoot multiple targets with a bow) (#20736, #20737)
- Trigger a recording on entering an entity (WL #20751)

### CODE REVIEW

**Comment by thoys** [comment]
@cozza13 ^

**Comment by imgntn** [comment]
just a heads up that you'll have some conflicts to resolve with recent merges to handControllerGrab.js -- i dont think you'll have trouble with your changes but let me know

**Comment by thoys** [comment]
ty for the heads up @imgntn , that should do it

**Comment by imgntn** [comment]
this looks good to me so i'm going to merge -- just curious -- are you manually attaching the script to the 'start' button that we shoot?  i don't actually see where that is created.  anyhow, good stuff

**Pull request merged**
