### PR TITLE
66 fix - installer changes for client only name and clean install

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8542/HighFidelity-Beta-PR12802-55a3dc3a497f0026204c0aec5ca7ca6220800de5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8542/HighFidelity-Beta-PR12802-55a3dc3a497f0026204c0aec5ca7ca6220800de5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8551/app_12802_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8551/HighFidelity-Beta-PR12802-9973b64b7724b84047a01b76332b2335cc8f3a9f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8557/app_12802_PR.apk

**Comment by birarda** [comment]
#### Test Plan

1. Download the build posted by Jenkins for this PR.
2. Run the installer. Confirm that it says "Welcome to High Fidelity - PR12802 Setup".
3. Choose custom install.
4. Confirm that the default install location is "C:\Program Files\High Fidelity - PR12802".
5. Confirm that the default Start Menu folder is "High Fidelity - PR12802".
6. Complete the install and ask the installer to launch the Sandbox and Interface at the conclusion of the install. When Interface launches, login and setup your wallet.
7. Close Interface but leave the Sandbox running.
8. Check "Apps & Features" and ensure that the entry there is named "High Fidelity - PR12802".
9. Confirm that the following files and folders exist:
```
$APPDATA\Roaming\High Fidelity - PR12802\domain-server.json
$APPDATA\Roaming\High Fidelity - PR12802\domain-server\
$APPDATA\Roaming\High Fidelity - PR12802\assignment-client\
$APPDATA\Roaming\High Fidelity - PR12802\Server Console\
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
$APPDATA\Roaming\High Fidelity - PR12802\Interface\$USERNAME.hifikey
```
10. Download this client only version of the installer for this PR - http://hifi-public.s3.amazonaws.com/birarda/HighFidelity-Beta-Interface-PR12802.exe.
11. Run the client only installer.
12. Confirm that the client only installer complains that one of Sandbox or domain-server or assignment-client are still running.
13. Close the Sandbox.
14. Confirm that the client only installer says "Welcome to High Fidelity Interface - PR12802 Setup".
15. Choose custom install. 
16. Confirm that the default install location is "C:\Program Files\High Fidelity Interface - PR12802\".
17. Confirm that the default start menu folder is "High Fidelity Interface - PR12802".
18. On the Setup Options page check the option to perform a clean install. Do not check the option to run the Interface.
19. Confirm that the following files no longer exist:
 ```
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
```
20. Confirm that the following files still exist:
```
$APPDATA\Roaming\High Fidelity - PR12802\domain-server.json
$APPDATA\Roaming\High Fidelity - PR12802\domain-server\
$APPDATA\Roaming\High Fidelity - PR12802\assignment-client\
$APPDATA\Roaming\High Fidelity - PR12802\Server Console\
$APPDATA\Roaming\High Fidelity - PR12802\Interface\$USERNAME.hifikey
```
21. Run the Interface from "C:\Program Files\High Fidelity Interface - PR12802\interface.exe"
22. Login and confirm that you are able to use the wallet you created before by entering the passphrase you selected.
23. Confirm that the following files now exist:
 ```
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
```
24. Close Interface.
25. Run the installer that Jenkins posted on the PR. Perform a custom install, selecting only "High Fidelity Interface" and not "High Fidelity Sandbox" on the components page. Do not ask for the Interface to be run at the conclusion of the install. Select the option to perform a clean install.
26. Confirm that the following files no longer exist:
 ```
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
```
27. Run Interface from "C:\Program Files\High Fidelity - PR12802\interface.exe". Login and confirm that you are able to use the wallet you created before by entering the passphrase you selected.
28. Confirm that the following files now exist:
 ```
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
```
29. Run the installer that Jenkins posted on the PR. Perform a custom install, selecting both components on the components page. Do not ask for the Sandbox or Interface to be run at the conclusion of the install. Select the option to perform a clean install.
30. Confirm that none of the following files and folders exist:
```
$APPDATA\Roaming\High Fidelity - PR12802\domain-server.json
$APPDATA\Roaming\High Fidelity - PR12802\domain-server\
$APPDATA\Roaming\High Fidelity - PR12802\assignment-client\
$APPDATA\Roaming\High Fidelity - PR12802\Server Console\
$APPDATA\Roaming\High Fidelity - PR12802\Interface.json
$APPDATA\Roaming\High Fidelity - PR12802\Interface\AccountInfo.bin
$APPDATA\Roaming\High Fidelity - PR12802\Interface\$USERNAME.hifikey
```
31. Confirm that the following file still exists
```
$APPDATA\Roaming\High Fidelity - PR12802\Interface\$USERNAME.hifikey
```

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8557/HighFidelity-Beta-PR12802-16335a3b4ba2b3b1db046e849577293bbcdaceff.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8557/HighFidelity-Beta-PR12802-16335a3b4ba2b3b1db046e849577293bbcdaceff.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8570/app_12802_PR.apk

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
Both the server/client and client/only installers worked as expected, and with various elements checked/unchecked during clean installs, files were added and deleted correctly.

**Comment by birarda** [comment]
Commerce confirmed they are onboard with the wallet file changes here

**Pull request merged**
