### PR TITLE
"Set Availability" UI changes

### PR DESCRIPTION
**Pull request by zfox23**
Old on the left; new on the right.

image

*Test Plan:*
1. Ensure the language in the PAL -> Set Availability menu matches what you see on the right side of the screenshot above.
2. Make sure that the language makes sense to you!

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b41fb952ae18156045b3bee3c992509175d6a442 available at: https://gist.github.com/af6caaa08506afee9560971e674868a4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-b41fb95.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-b41fb95.dmg

**Comment by zfox23** [comment]
Hold off on the QA, please - still deliberating language.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 905f36976ff85cdffb5a1eb61c2cd2e992d9fc92 available at: https://gist.github.com/af6caaa08506afee9560971e674868a4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-905f369.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-905f369.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a10606b9949f12d13fc7dc7052d0594471d4e819 available at: https://gist.github.com/af6caaa08506afee9560971e674868a4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-a10606b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10392-a10606b.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
@zfox23 are the sentences in this build's 'Set your availability' dialog supposed to match the screenshot exactly?

**Comment by zfox23** [comment]
@claudioshg haha! That's a very scary question. What are you seeing?

**Comment by howard-stearns** [comment]
FWIW, when I open the 'set availability' dialog in this PR, for me it does look identical to the picture on the right (above), which is what I expect.

**Comment by claudioshg** [comment]
@zfox23 
apr10392

**Comment by zfox23** [comment]
@claudioshg This is like playing "Spot the Difference" :joy:

I don't see any differences between your image and the image on the right. What are they?

**Comment by claudioshg** [comment]
@zfox23  I see that now. The image I posted is the same as the screenshot on the right. I thought it had to resemble the left screenshot. Sorry, I'm just confused. lol. So... It's a pass? It's supposed to resemble the right side?

**Comment by zfox23** [comment]
@claudioshg Yes, this is a pass! This was totally my fault; I reversed the language in the original description 😅. Sorry about that, and thanks!

**Comment by claudioshg** [comment]
@zfox23 This was awesome. lol NP

**Pull request merged**
