### PR TITLE
Merge Stable back into Master.

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb03e08e1614567d3fd85980b4d0f7e15a065b1a available at: https://gist.github.com/2083fdf775fbfb71de3588efc896ea5c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9884-bb03e08.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9884-bb03e08.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb03e08e1614567d3fd85980b4d0f7e15a065b1a available at: https://gist.github.com/2083fdf775fbfb71de3588efc896ea5c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9884-bb03e08.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9884-bb03e08.dmg

**Comment by ZappoMan** [comment]
Dev/QA approve since these are already in stable...

**Pull request merged**
