### PR TITLE
Bug fixes for avatarData protocol

### PR DESCRIPTION
**Pull request by hyperlogic**
Two issues were recently discovered after they were introduced by PR #14733

1) The Avatar Mixer would sometimes have incorrect translation scale when splitting BulkAvatarData across multiple MTUs
2) Old avatar recordings would no longer work properly.

This PR should fix both of these issues.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/20821/Avatar-s-bounce-when-4-or-more-avatars-are-in-the-same-domain

**Comment by hyperlogic** [comment]
QA Test plan, for avatar translations.
------------------
* Enter a domain (running this PR) with five other avatars, (also running this PR)
* All five avatars render correctly, and do not "bounce" up and down.


QA test plan for old avatar recordings:
-----------
* In the domain settings for a domain (running this PR) Enter the agent script url below.
* Enter the domain, at location (0, 0, 0) you should see a small dark skinned avatar in a sitting pose, moving his arms about.

https://gist.githubusercontent.com/hyperlogic/61c4c32b845683169d2472af42de7c24/raw/6d3872a6c2a878dbbcd4f95c4732f7ac9f401042/botPlayback.js
       
QA test plan for new avatar recordings:
---------------
* Follow these [directions](https://docs.highfidelity.com/create-and-explore/marketplace-apps/record-app) for using the avatar recording app in the market place.
* Recordings made with this app should work as expected when server and clients are running this PR.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16724/HighFidelity-Beta-PR14771-77fb208.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16724/HighFidelity-Beta-PR14771-77fb208.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16724/HighFidelity-Beta-Interface-PR14771-77fb208.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16724/HighFidelity-Beta-PR14771-77fb208.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16724/HighFidelity-Beta-Interface-PR14771-77fb208.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
PR Passes.

Avatar translations - Pass, had 5 clients load into sandbox and no bouncing occurred.

Old avatar recordings - Pass, loaded the script on the server and the bot appeared correctly and was moving.

New avatar recordings - Pass, but some issues with some white spheres in place of avatars occurred regularly. Would be a separate ticket if a defect.

**Pull request merged**
