### PR TITLE
Fix asset server qml sorting

### PR DESCRIPTION
**Pull request by druiz17**
Fix asset server qml sorting
ticket - https://highfidelity.manuscript.com/f/cases/12871/Tablet-UI-Asset-Browser-File-sorting-is-broken

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Launch Sandbox
- Within the Tablet UI.  Navigate to Menu->Edit->Asset Browser
- Within the default asset directory, navigate to the models folder
- Click the column labels ("NAME" or "USE BAKED?") a few times to change the sort order
- also when you click the column "Use Baked" , the text should not disappear

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8020/app_12637_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8020/HighFidelity-Beta-PR12637-d6b3e91de192f1791e5ede7deb1b6b5a362dceba.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8021/app_12637_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8021/HighFidelity-Beta-PR12637-d6b3e91de192f1791e5ede7deb1b6b5a362dceba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8021/HighFidelity-Beta-PR12637-d6b3e91de192f1791e5ede7deb1b6b5a362dceba.exe

**Comment by conklin94122** [comment]
@druiz17 Needs milestone

**Comment by conklin94122** [comment]
build this please

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8303/app_12637_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8303/HighFidelity-Beta-PR12637-d6b3e91de192f1791e5ede7deb1b6b5a362dceba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8303/HighFidelity-Beta-PR12637-d6b3e91de192f1791e5ede7deb1b6b5a362dceba.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Sorting by name and baked status in asset browser does not function in HMD. In desktop mode the arrow will sort all files by name or baked status.
[Files.zip](https://github.com/highfidelity/hifi/files/1853705/Files.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8311/app_12637_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8311/HighFidelity-Beta-PR12637-ad9ca0da204e09e4676952f42192f9d07607416c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8311/HighFidelity-Beta-PR12637-ad9ca0da204e09e4676952f42192f9d07607416c.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Arrow sorts and functions as expected in both desktop and HMD.

**Pull request merged**
