### PR TITLE
MS16537: Updating "Forgot Username/Forgot Password" behavior

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for MS[#16537](https://highfidelity.manuscript.com/f/cases/16537/Web-views-open-behind-Log-in-Sign-up-dialog)

**TEST PLAN**

- Launch Interface
- If signed in, log out via `Menu > Log out <username>`
- Click `Menu > Login/Sign Up`
- Click `Forgot Username?` or `Forgot Password?` (test both behaviors)
- Login dialog should disappear, and browser should be set in focus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11392/HighFidelity-Beta-PR13629-0cbcae9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11392/HighFidelity-Beta-Interface-PR13629-0cbcae9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11392/HighFidelity-Beta-PR13629-0cbcae9.exe

**Comment by QliCknox** [comment]
Currently testing

**Comment by QliCknox** [comment]
Pass @Qliemillar 

Log in prompt closes when the user selects "Forgot Password" and "Forgot Username" and the browser comes into focus

**Pull request merged**
