### PR TITLE
Remove some dead code in edit.js

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing: Should be no effect on edit.js.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a23f3a59b1501cd3ce0801e38f480406485a510 available at: https://gist.github.com/427ef1c3e919897e48b024582eb98edc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10092-6a23f3a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10092-6a23f3a.dmg

**Comment by 68chase** [comment]
Testing

@ctrlaltdavid  For this build, do you want me to just verify that clicking on  the edit button in the standard toolbar, brings up the edit dialog?   Is that about right?

**Comment by ctrlaltdavid** [comment]
@68chase For testing should just have a brief run through using entities editor to check that things still work. In theory, the code removed was not used and you should see no change in operations (except perhaps a fractional improvement in responsiveness because the code is doing less, though probably not noticeable unless on a slow PC).

**Comment by 68chase** [comment]
@ctrlaltdavid Thanks for the clarification,  Testing now...

**Comment by 68chase** [comment]
Passed - Not strange behavior noticed.

**Pull request merged**
