### PR TITLE
Wallet locker

### PR DESCRIPTION
**Pull request by howard-stearns**
This is a prototype. We will be going through several steps, and at each one, we will be repeating something similar to the tests below.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12082/HighFidelity-Beta-PR13822-4eee026.apk

**Comment by howard-stearns** [comment]
**First Test Plan:** 

1. _All wallet tests_ with master against staging. (To confirm that staging data-web is compatible with existing client.)
1. _Existing user test_:
   1. Pre-req: Confirm with any other release on the metaverse you are test with, that you have an account, a wallet, and something Rezzable in My Purchases. Rez it and make sure it appears. Exit Interface.
   1. In a new session using a fresh installation of this PR (e.g., in which AppData/Roaming/High Fidelity - PR13822 does not yet exist and you choose to _NOT_ copy settings from production), log in to the same account.
   1. Try to open the wallet app. It should tell you that a wallet was already used on this account, and prompt you for it. Use the one from step 2.i.
   1. Confirm that you still have the same things in My Purchases (as in step 2.i). Rez one and make sure it appears. Exit Interface.
   1. Delete or rename the wallet in AppData/Roaming/High Fidelity - PR13822/Interface/_your_user_name_.hifikey.
   1. In a new session (this PR), confirm that you are now NOT prompted for a wallet, but are prompted for a password just as if the wallet file were still there.
   1. Confirm that you still have the items from step 2.i in My Purchases. Rez one and make sure it appears.
1. _New user test_:
   1. Create a new username on the metaverse you are testing with.
   1. In a new session, make a wallet.
   1. Buy something Rezzable and free, and confirm that you have it in My Purchases. Rez it and make sure it appears.
   1. Exit Interface, delete or rename the new wallet (AppData/Roaming/High Fidelity - PR13822/Interface/_your_user_name_.hifikey)
   1. In a new session, confirm that you are now NOT prompted for a wallet, but are prompted for a password just as if the wallet file were still there.
   1. Confirm that you still have what you bought in step 3.iii. Rez it and make sure it appears.
1. _New machine test_:
   1. On a new machine or a fresh re-installation (in which AppData/Roaming/High Fidelity - PR13822 does not yet exist), log in as the new user from test 3.
   1. Confirm that you are not prompted for a wallet, but are prompted for a password just as if the wallet file was already there.
   1. Confirm that you still have what you bought in step 3.iii. Rez it and make ssure it appears.
1. _All other wallet tests_ with this PR against staging. (Might overlap some of the above. This is to confirm that we haven't broken something else, not related to the above.)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12082/HighFidelity-Beta-PR13822-4eee026.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12082/HighFidelity-Beta-Interface-PR13822-4eee026.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12082/HighFidelity-Beta-PR13822-4eee026.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12082/HighFidelity-Beta-Interface-PR13822-4eee026.exe

**Comment by rickcarr044** [comment]
Currently testingPR13822

**Comment by rickcarr044** [comment]
Changing the Passphrase in this PR does not work as expected. When the user selects My Purchasesing the new passphrase results in an Authentication failed error.  Old passphrase remains valid.   Scenario tested against current build (RC71) and close to current dev build (#9219).  In both cases, the user was successfully able to change their passphrase.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12101/HighFidelity-Beta-PR13822-d1d0812.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12101/HighFidelity-Beta-PR13822-d1d0812.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12101/HighFidelity-Beta-Interface-PR13822-d1d0812.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12101/HighFidelity-Beta-PR13822-d1d0812.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12101/HighFidelity-Beta-Interface-PR13822-d1d0812.exe

**Comment by rickcarr044** [comment]
Currently testing PR13822

**Comment by rickcarr044** [comment]
Passed this version of PR13822

**Comment by howard-stearns** [comment]
Just recording some notes: Rick reports:
"Passphrase bug is fixed.
There is a small bug in the Help file.  It does not repro in Build 9219.  In 13822 if the user clicks on the BankOfHighFidelity link in the first help topic question - they get a dialog with the message 'You'll need a new app ...'"

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12119/HighFidelity-Beta-PR13822-687e2bd.apk

**Comment by howard-stearns** [comment]
This version bypasses wallet setup, and lockers the internal encryption for this user, who does not then enter it.

**Test Plan**

_Existing user test_ is now as follows:
1. Pre-req: Confirm with any _other_ release (i.e, _not_ a previous version of this PR!), on the metaverse you are test with, that you have an account, a wallet, and something Rezzable in My Purchases. Rez it and make sure it appears. Exit Interface. _If you have used this account with a previous version of this PR, tell Howard the account name so that he can remove previous lockering on the staging metaverse server. This must be completed before going on to the next steps._
1. In a new session using a fresh installation of this PR (e.g., in which AppData/Roaming/High Fidelity - PR13822 does not yet exist and you choose to NOT copy settings from production), log in to the same account.
1. Try to open the wallet app. It should tell you that a wallet was already used on this account, and prompt you for it. Use the one from step 1. Confirm that it asks you for the passphrase you used in step 1. 
1. Confirm that you still have the same things in My Purchases (as in step 1). Rez one and make sure it appears. Exit Interface.
1. Delete or rename the wallet in AppData/Roaming/High Fidelity - PR13822/Interface/_your_user_name_.hifikey.
1. In a new session (this PR), confirm that you are now NOT prompted for a wallet, nor for a passphrase. You should see your previous activity.
1. Confirm that you still have the items from step 1 in My Purchases. Rez one and make sure it appears.

An additional _Alternate Existing user test_ is exactly the same (including pre-req), except:
- In step 2, _DO_ copy settings during installation (advanced installation). Before opening the wallet, confirm that AppData/Roaming/High Fidelity - PR13822/Interface/_your_user_name_.hifikey is a correct copy (e.g, same file size and contents) as the one from step 1.
- The idea here is that this is almost the same case as the _Existing user test_ above, but more closely simulates what an existing user will experience the first time they use this version after it is released.

_New user test_:
1. Create a new username on the metaverse you are testing with (that was not used in a previous test, nor in a previous version of this PR).
1. In a new session, make a wallet. _It won't ask you to set anything up, but will just work._
1. Buy something Rezzable and free, and confirm that you have it in My Purchases. Rez it and make sure it appears.
1. Exit Interface, delete or rename the new wallet (AppData/Roaming/High Fidelity - PR13822/Interface/_your_user_name_.hifikey)
1. In a new session, confirm that you are now NOT prompted for a wallet _nor for a passphrase_.
1. Confirm that you still have what you bought in step 2. Rez it and make sure it appears.

_New machine test_:
1. On a new machine or a fresh re-installation (in which AppData/Roaming/High Fidelity - PR13822 does not yet exist), log in as the new user from the new user test.
1. Confirm that you are not prompted for a wallet _nor passphrase._
1. Confirm that you still have what you bought in the New user test. Rez it and make sure it appears.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12119/HighFidelity-Beta-PR13822-687e2bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12119/HighFidelity-Beta-Interface-PR13822-687e2bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12119/HighFidelity-Beta-PR13822-687e2bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12119/HighFidelity-Beta-Interface-PR13822-687e2bd.exe

**Comment by rickcarr044** [comment]
Currently testing PR13822

**Comment by rickcarr044** [comment]
Passed this version of PR13822

**Pull request closed without merging**
