### PR TITLE
tidy zone flying and ghosting entities editor options

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Move options to top of section from under "skybox" subsection
Fix capitalization of labels

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Before:
zone-before

After: 
zone-after

**Comment by ctrlaltdavid** [comment]
Testing
- Options should be positioned and capitalized per the "after" screensnap.
- Options should still have the desired effect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3391430f0a2f061c95a9bdf7f74bbfdbc0ab62ec available at: https://gist.github.com/b25eb88852e78e13e54d163c908ca838<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7963.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7963.dmg

**Comment by Nex-Pro** [comment]
#### QA PASS


Edit panel rendered as per description.
Image attached.
No apparent side effects.
Interface exited cleanly on each occasion.

edit_pane_pr763

**Pull request merged**
