### PR TITLE
Fix for visible empty toolbar when switching from desktop to HMD mode.

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40b7e34c0be04b4a0c905a2b8734e631a2719775 available at: https://gist.github.com/dd64299e560079e7dde553cbfe8c74ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9874-40b7e34.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9874-40b7e34.dmg

**Comment by Nex-Pro** [comment]
@hyperlogic  Hey, is this the tiny toolbar remnant I've been telling you guys about for months ?

**Comment by hyperlogic** [comment]
@Nex-Pro The feature that caused this issue is only 3 weeks old, so not sure about the months part.

**Comment by hyperlogic** [comment]
QA test:
  * Make sure the 'Desktop Tablet Becomes Toolbar' option is checked.
  * Switch from desktop to HMD mode.
  * While in HMD mode ensure that no part of system toolbar is visible.  Previously a small transparent lozenge would appear

**Comment by Nex-Pro** [comment]
@hyperlogic 3 weeks ago is when you guys finally noticed what I've been mentioning for months !

**Pull request merged**
