### PR TITLE
Avatar should vanish when teleporting far away

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* fix bug where avatar would still be visible after teleporting far away

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This is how to reproduce the bug:

(1) Login with two users: UserA and UserB and stand looking at each other
(2) UserB: teleport far away (say to (1000, 1000, 1000))
(3) --> Bugged behavior: UserA can still see UserB's avatar
--> Expected behavior: UserA should see UserB vanish

Note: the bug fix requires an updated avatar-mixer assignment client because part of the bug is caused by the fact that the old avatar-mixer would cease sending updates to UserA about UserB when UserB teleports far out of view.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8a3c856be0e697ef34f8d01731a2ed0855c4cd3 available at: https://gist.github.com/70ff57768df32cd37a808f3242b02929<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10199-b8a3c85.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10199-b8a3c85.dmg

**Comment by OmegaHeron** [comment]
Testing this

**Comment by OmegaHeron** [comment]
Tested Windows 10 and Ubuntu 16.04
QA Pass

Machine A - Windows 10, this PR Stack and Interface
Machine B - Ubuntu 16.04, this PR Interface

Machine A and B has user standing eye to eye at 0,0,0
Machine B moves in same domain to 16000,16000,16000 - Machine A sees Machine B disappear
Machine B comes back to 0,0,0 and Machine A sees Machine B.
Machine A moves to new location in domain as above, Machine B sees or does not see Machine A as proper.

General smoke test pass.

**Pull request merged**
