### PR TITLE
Disable thumbsticks on Oculus Touch.

### PR DESCRIPTION
**Pull request by r3tk0n**
Disable the thumbsticks on the Oculus Touch in an effort to force users to discover `drive.js` functionality.

### CODE REVIEW

**Comment by r3tk0n** [comment]
Ignore this, accidentally start this pull request.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12449/HighFidelity-Beta-PR13892-e51b5a8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12449/HighFidelity-Beta-PR13892-e51b5a8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12449/HighFidelity-Beta-Interface-PR13892-e51b5a8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12449/HighFidelity-Beta-PR13892-e51b5a8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12449/HighFidelity-Beta-Interface-PR13892-e51b5a8.exe

**Pull request closed without merging**
