### PR TITLE
fix physics related crash-on-exit

### PR DESCRIPTION
**Pull request by sethalves**
- fix a physics-related crash-on-exit

https://highfidelity.fogbugz.com/f/cases/assign/14667/physics-related-crash-on-exit

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9354/app_13062_PR_f1e1c6a34817563ac0a9da876a968561361b9ee6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9354/HighFidelity-Beta-Interface-PR13062-f1e1c6a34817563ac0a9da876a968561361b9ee6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9354/HighFidelity-Beta-PR13062-f1e1c6a34817563ac0a9da876a968561361b9ee6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9354/HighFidelity-Beta-Interface-PR13062-f1e1c6a34817563ac0a9da876a968561361b9ee6.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Moving sphere did not crash interface on exit. Tested 6 times.

**Pull request merged**
