### PR TITLE
Fix Steam scripting interface calls

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes a bug in the Steam JS API that caused the app to crash.

## Test plan:
- Open the JS console
- Run `Steam.isRunning` and `Steam.openInviteOverlay()`
- This crashes on master but not with this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 808d336fe6071cc4560aa38ef171e874cf3ce665 available at: https://gist.github.com/606d970582204b4e7161d209aecaf25c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-808d336.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-808d336.dmg

**Comment by ctrlaltdavid** [comment]
Test results:
- The two commands above in the console do not crash Interface. PASS
- currentAPI.js successfully lists Steam.isRunning and Steam.isRunning() without Interface crashing: PASS
- var x = Steam.isRunning(); results in error: "[UncaughtException] TypeError: Result of expression 'Steam.isRunning' [false] is not a function." FAIL

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4400af026bb158a24831514ebb195a41f185645 available at: https://gist.github.com/606d970582204b4e7161d209aecaf25c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-b4400af.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-b4400af.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4400af026bb158a24831514ebb195a41f185645 available at: https://gist.github.com/606d970582204b4e7161d209aecaf25c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-b4400af.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9501-b4400af.dmg

**Comment by ctrlaltdavid** [comment]
Test results:
- The two console commands (Steam.running and Steam.isRunning() do not crash Interface., PASS
- currentAPI.js successfully lists Steam.running and Steam.isRunning(). PASS
- var x = Steam.running; and var y = Steam.isRunning(); both retrieve a Boolean without error. PASS

**Pull request merged**
