### PR TITLE
Remove QML threaded rendering

### PR DESCRIPTION
**Pull request by jherico**
Now that primary rendering is no longer on the main thread, the driving force behind moving QML rendering off the main thread is gone.  By moving QML rendering back to the main thread, we should reduce the total number of threads executing content as well as potential concurrent OpenGL context work.  This should have a positive impact on systems that are thread constrained, like i5 based computers.

## Testing

Application behavior should be unchanged.  There may be a slight performance improvement / less stuttering on core-constrained systems.

### CODE REVIEW

**Comment by ZappoMan** [comment]
**Testing notes: make sure to run performance tests on all platforms.**

**Comment by hifi-gustavo** [comment]
Build console output for commit: caf7d878416cce64f89dc3eae99fcdaddded74cd available at: https://gist.github.com/ca9e182ba91fdde32aada71f4a6b814f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-caf7d87.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-caf7d87.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: afbbd398dc380bfa9b9ba41b5e9cd7f322d94dbd available at: https://gist.github.com/ca9e182ba91fdde32aada71f4a6b814f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-afbbd39.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-afbbd39.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6afe5360fe3d7f417769ff4d1368817493388b1c available at: https://gist.github.com/ca9e182ba91fdde32aada71f4a6b814f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6afe5360fe3d7f417769ff4d1368817493388b1c available at: https://gist.github.com/ca9e182ba91fdde32aada71f4a6b814f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6afe5360fe3d7f417769ff4d1368817493388b1c available at: https://gist.github.com/ca9e182ba91fdde32aada71f4a6b814f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8743-6afe536.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU
Desktop mode 1600x900 Maximized window
5 runs each lasting 2 minutes.  Blue = 5407, Green = 5429 and Red = This PR 8743

5407vs5429vs8743

No great change to CPU use seen for this PR, but, as with 5429, there's a steady small improvement of CPU use and lesser spikes of high CPU use leading to a smoother experience overall.

**Very brief** smoke testing passes - everything looks as expected, but, I'm time constrained today, so if there's any worry this could impact visuals, please have another QA person give it a more detailed look.  Standard home scene looks fine as does playa, dev-demo and my own content.

**Comment by hevyw8** [comment]
### Test system:

system: win10-64
gpu: nvidia gtx1060
cpu: i5-6500 @ 3.2
mem: 32gb ddr4
### Actions

'go home' from domain task bar menu
went to 'welcome' 
flew around and interacted with cubes
went back to default home
loaded marketplace tablet
rezzed and deleted bowling alley
rezzed and edited throne
deleted throne


### Comments

I also had a short walkthrough with this. Performance is drastically improved over current beta release. With current beta release I am unable to run interface and domain server concurrently. With this PR I have a few stutters on initial load in local home domain. Other much less significant stuttering during audio toggling, and rezzing items. I should be able to give a full smoke test this weekend if the PR is still pending.

**Pull request merged**
