### PR TITLE
Add Hifi-Hand-Drop so scripts can cause grabbed items to be dropped

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Equip an object in your left hand
 1. In the console, run `Messages.sendLocalMessage("Hifi-Hand-Drop", "left")` - You should see the object drop out of your hand
 1. Equip an object in your righthand
 1. In the console, run `Messages.sendLocalMessage("Hifi-Hand-Drop", "left")` - You should not see the object drop out of your hand
 1. Equip an object in your righthand
 1. In the console, run `Messages.sendLocalMessage("Hifi-Hand-Drop", "right")` - You should not see the object drop out of your hand
 1. Equip an object in your righthand
 1. In the console, run `Messages.sendLocalMessage("Hifi-Hand-Drop", "both")` - You should not see the object drop out of your hand

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c3840dc788f4a828d748c9ae3b011bf5f1e37d2 available at: https://gist.github.com/0444108961a720aff3223438aae98da2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9792-1c3840d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9792-1c3840d.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: 
CTRL - ALT - J in HMD Oculus with Touch did NOT rez JS console.  It did in Desktop so I had to manipulate the commands below going back and forth was very tricky.
1)Equip an object in your left hand.
In the console, run ```Messages.sendLocalMessage("Hifi-Hand-Drop", "left")``` - You should see the object drop out of your hand. = SUCCESS
2)Equip an object in your righthand.
In the console, run ```Messages.sendLocalMessage("Hifi-Hand-Drop", "left")``` - You should not see the object drop out of your hand. = SUCCESS
3)Equip an object in your righthand.
In the console, run ```Messages.sendLocalMessage("Hifi-Hand-Drop", "right")``` - You should not see the object drop out of your hand. = FAIL
4)Equip an object in your righthand.
In the console, run ```Messages.sendLocalMessage("Hifi-Hand-Drop", "both")``` - You should not see the object drop out of your hand. = FAIL

**Comment by huffman** [comment]
@kevinmthomasse Thanks for testing. Those last 2 were incorrectly written by me (well, copy-paste fail). Those should have dropped the object, so I will mark this as a QA pass.

**Pull request merged**
