### PR TITLE
hide default port from addresses, fix localhost scheme

### PR DESCRIPTION
**Pull request by druiz17**
tickets - https://highfidelity.manuscript.com/f/cases/14331/Users-sometimes-get-multiple-instances-of-HOME-bookmarked-which-renders-bookmark-and-home-button-non-functional#BugEvent.89568

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9229/app_13014_PR_97d793f867b7d181c28ead31fc8c27a8364842bd.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9229/HighFidelity-Beta-PR13014-97d793f867b7d181c28ead31fc8c27a8364842bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9229/HighFidelity-Beta-Interface-PR13014-97d793f867b7d181c28ead31fc8c27a8364842bd.exe

**Comment by druiz17** [comment]
Test plan
- have sandbox running
- goto sandbox
- bookmark the sandbox location as your home.
- goto another domain
- click either the home location bookmark or the home button in the goto
- you should be taken to your sandbox.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9229/HighFidelity-Beta-PR13014-97d793f867b7d181c28ead31fc8c27a8364842bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9229/HighFidelity-Beta-Interface-PR13014-97d793f867b7d181c28ead31fc8c27a8364842bd.dmg

**Comment by druiz17** [comment]
@ZappoMan this is for RC68, I have another PR against RC66.2 branch

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Setting sandbox as home will still take me home.

**Pull request merged**
