### PR TITLE
RC67: Fix white textures on android

### PR DESCRIPTION
**Pull request by SamGondelman**
Same as https://github.com/highfidelity/hifi/pull/13066

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9361/app_13067_PR_56f5d677c93e2016d882aebaf6df2a4b507ec0c1.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9364/app_13067_PR_200df8f1ebb0f4ee39330adc597c065fa1aecdc3.apk

**Comment by ZappoMan** [comment]
Why is this tagged 67? Is it an Acceptance test failure?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9364/HighFidelity-Beta-PR13067-200df8f1ebb0f4ee39330adc597c065fa1aecdc3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9364/HighFidelity-Beta-Interface-PR13067-200df8f1ebb0f4ee39330adc597c065fa1aecdc3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9364/HighFidelity-Beta-PR13067-200df8f1ebb0f4ee39330adc597c065fa1aecdc3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9364/HighFidelity-Beta-Interface-PR13067-200df8f1ebb0f4ee39330adc597c065fa1aecdc3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Interface Passes @conklin94122 
Interface basic features work as expected.

**Comment by conklin94122** [comment]
@SamGondelman This isn't necessary for RC67, closing this PR. Please open a version of the PR against RC68.

**Pull request closed without merging**
