### PR TITLE
Fix: Interstitial page restoring ignored entities

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for restoring entity interaction with ignored entities in interstitial page

## TEST PLAN

Launch interface in HMD mode
Go to a domain that has entities blocking the abort button (i.e. hifi://gigs)
Try to hover over the abort button without clicking it
Land in attemped domain (i.e. hifi://gigs)
Entity originally attempted should be clickable with lasers

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13710/HighFidelity-Beta-PR14161-ea8229f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13710/HighFidelity-Beta-PR14161-ea8229f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13710/HighFidelity-Beta-Interface-PR14161-ea8229f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13710/HighFidelity-Beta-PR14161-ea8229f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13710/HighFidelity-Beta-Interface-PR14161-ea8229f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13733/HighFidelity-Beta-PR14161-6f9593d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13733/HighFidelity-Beta-PR14161-6f9593d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13733/HighFidelity-Beta-Interface-PR14161-6f9593d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13733/HighFidelity-Beta-PR14161-6f9593d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13733/HighFidelity-Beta-Interface-PR14161-6f9593d.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14003/HighFidelity-Beta-PR14161-6f9593d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14003/HighFidelity-Beta-PR14161-6f9593d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14003/HighFidelity-Beta-Interface-PR14161-6f9593d.dmg

**Comment by qlimguicheteau** [comment]
Currently Testing

**Comment by qlimguicheteau** [comment]
Fail @conklin94122 

FAIL - Web Entity at the doorway of hifi://gigs does not render.
FAIL - Abort cannot be highlighted.

I left the Domain, traveled to a few other areas, then back. Web entity remained invisible.

(also are the two white cats and the cat on the shelf near the doorway supposed to be non-clickable?)
(If you turn interstitial off, then back on, the web entity appears)
(Note, on Staging, if the abort button is being held, the outline highlight for the abort button persists on the screen after loading is complete)

Web entity in domain did not appear. I made this GIF while investigating the cats, but then realized that there was supposed to be a Web Entity in the entrance.
hifi-snap-by-kyrrenell-on-2018-10-17_08-45-28

When hovering over the abort button but a web-entity is in the way, target cannot be highlighted.
nohover

**Comment by wayne-chen** [comment]
merged into PR#14249.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14243/HighFidelity-Beta-PR14161-afd8bac.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14243/HighFidelity-Beta-PR14161-afd8bac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14243/HighFidelity-Beta-Interface-PR14161-afd8bac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14243/HighFidelity-Beta-PR14161-afd8bac.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14243/HighFidelity-Beta-Interface-PR14161-afd8bac.exe

**Pull request closed without merging**
