### PR TITLE
RC66: fix unreadable baked textures in serverless tutorial

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
Should fix the same 2 issues fixed by (https://github.com/highfidelity/hifi/pull/12804):

too loud tutorial voice
HMD instructions showing up on the "explore" station before entering the zone.

Also ensure that the textures of the models are all loaded. For example, the floor should have a wood texture on it.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8684/app_12853_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8684/HighFidelity-Beta-PR12853-e6cada778141a0339da8a469fb436181c1a11bcd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8684/HighFidelity-Beta-PR12853-e6cada778141a0339da8a469fb436181c1a11bcd.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8687/app_12853_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8687/HighFidelity-Beta-PR12853-7ec65e8c0ca8f850fd576db77b9e97c6251d9583.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8687/HighFidelity-Beta-PR12853-7ec65e8c0ca8f850fd576db77b9e97c6251d9583.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tutorial voice is now much better volume, and the explore content appears at the correct time, not before.

**Pull request merged**
