### PR TITLE
case 21042: fix interface crash on early shutdown, 0.80.0 redux

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/21042/Crash-Interface-crashes-on-shut-down-when-closing-during-domain-loading-0-80-0-redux

This PR fixes an Interface crash when quitting application before scene has loaded.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17052/HighFidelity-Beta-PR14856-16ef30c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17052/HighFidelity-Beta-PR14856-16ef30c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17052/HighFidelity-Beta-Interface-PR14856-16ef30c.dmg

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17065/HighFidelity-Beta-PR14856-16ef30c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17065/HighFidelity-Beta-PR14856-16ef30c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17065/HighFidelity-Beta-Interface-PR14856-16ef30c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17065/HighFidelity-Beta-PR14856-16ef30c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17065/HighFidelity-Beta-Interface-PR14856-16ef30c.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
