### PR TITLE
Emoji Tablet App

### PR DESCRIPTION
**Pull request by elisa-lj11**
# **Test plan**

## **Part 1: Loading the tablet app**

All emojis should have a lifetime of 30 seconds at most
1. Go to _unpublishedScripts\marketplace\emoji-tablet_ in your hifi root and load _emojiTablet.js_ from disk (alternatively, you can load the script via this URL: https://hifi-content.s3.amazonaws.com/elisalj/emoji_scripts/emojiTablet.js)
2. An emoji app button should appear next to other apps; click on this
3. A tablet app should appear that looks like this 
emoji_tablet_app_preview

## **Part 2: Testing the Emojis**
1. Click on "Corny" - a corn model will appear in front of you, you'll hear a rimshot and high pitched laughter, and the corn will look like it's laughing (alternating between a smiling and laughing face) as it rolls around on the floor
2. "Fireworks" - a 3D button will appear in front of you which you can press, then a firework will shoot out
3. "Flower" - a flower will appear in front of you and float down, clicking it will replace the flower model with overlays of pink 2D flowers
4. "Heart" - a 3D heart will float down in front of you
5. "Monster" - a red monster will appear in front of you and walk away from you (even if you turn your avatar and walk towards it), you'll hear a growling sound
6. "Pickle" - a pickle will appear in front of you. If you bring the pickle to your face, you'll hear a crunch and the pickle will disappear
7. "Pizza" - a pizza slice will appear in front of you. If you bring the pizza to your face, you'll hear an "om-nom-nom" sound and the pizza will explode
8. "Poo" - a rainbow poo will appear in front of you. If you click it, it'll make a fart sound

## **Known Issues**
1. Tablet app icon should be white

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2561/HighFidelity-Beta-PR11203-930f163ca160db3824f4dc7d015e07883ae6feac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2561/HighFidelity-Beta-PR11203-930f163ca160db3824f4dc7d015e07883ae6feac.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by ShoaibSmith** [comment]
Testing this.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2576/HighFidelity-Beta-PR11203-a9d5cb45e9345e0b56aa823697de861ab93c1aa5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2576/HighFidelity-Beta-PR11203-a9d5cb45e9345e0b56aa823697de861ab93c1aa5.exe

**Comment by YuppyPlays** [comment]
load the script via this URL: https://hifi-content.s3.amazonaws.com/elisalj/emoji_scripts/emojiTablet.js) **Check**
An emoji app button should appear next to other apps; click on this **Check**
A tablet app should appear that looks like this **Check**

Click on "Corny" - a corn model will appear in front of you, you'll hear a rimshot and high pitched laughter, and the corn will look like it's laughing (alternating between a smiling and laughing face) as it rolls around on the floor **I see the face but it seems to alternate between a laughing face and disappearing whilst doing the movement, also no audio**
"Fireworks" - a 3D button will appear in front of you which you can press, then a firework will shoot out **Pass, Audio did work for this one.**
"Flower" - a flower will appear in front of you and float down, clicking it will replace the flower model with overlays of pink 2D flowers **Clicking had no effect**
"Heart" - a 3D heart will float down in front of you **Pass**
"Monster" - a red monster will appear in front of you and walk away from you (even if you turn your avatar and walk towards it), you'll hear a growling sound **Everything works except audio for this one**
"Pickle" - a pickle will appear in front of you. If you bring the pickle to your face, you'll hear a crunch and the pickle will disappear **Pass, including that great crunch!**
"Pizza" - a pizza slice will appear in front of you. If you bring the pizza to your face, you'll hear an "om-nom-nom" sound and the pizza will explode **Pass, though the om nom made me jump a tad at first**
"Poo" - a rainbow poo will appear in front of you. If you click it, it'll make a fart sound **Pass**

**Comment by elisa-lj11** [comment]
@YuppyPlays 
For Corny, are you not seeing the model at all for a significant period of time or does it look like it's disappearing for a split second? I increased the volume so you should be able to hear this now.
For Flowers, you will see the overlays on a hand controller grab, not a mouse click (my mistake).
For Mosnter, I increased the volume as well, so now you should be able to hear it.
For Pizza, I decreased the volume a bit.

**Comment by ShoaibSmith** [comment]
Was able to load the tablet with no problems. 

>>Click on "Corny" - a corn model will appear in front of you, you'll hear a rimshot and high pitched laughter, and the corn will look like it's laughing (alternating between a smiling and laughing face) as it rolls around on the floor.

Corny shows up and is rolling around, but he is also glitching and flickering while he's moving around. I see @YuppyPlays was not able to hear the audio, I hear it just fine. 

>>"Fireworks" - a 3D button will appear in front of you which you can press, then a firework will shoot out.

It will not allow me to click 

>>"Flower" - a flower will appear in front of you and float down, clicking it will replace the flower model with overlays of pink 2D flowers.

Also will not allow me to click. 

>>"Heart" - a 3D heart will float down in front of you.

Will not let me click. 

>>"Monster" - a red monster will appear in front of you and walk away from you (even if you turn your avatar and walk towards it), you'll hear a growling sound.

Pass

>>"Pickle" - a pickle will appear in front of you. If you bring the pickle to your face, you'll hear a crunch and the pickle will disappear.

The pickle showed up but the crunch sound only occurred when I pushed it away from my avatar.  

>>"Pizza" - a pizza slice will appear in front of you. If you bring the pizza to your face, you'll hear an "om-nom-nom" sound and the pizza will explode." 

Same situation with the pickle, only worked when I pushed it away. The sound effect may be a bit too loud. 

>>"Poo" - a rainbow poo will appear in front of you. If you click it, it'll make a fart sound.

This works, the sound effect may be too loud as well.

**Comment by elisa-lj11** [comment]
@ShoaibSmith I removed the switch between a laughing and smiling corn because the flutter is fairly distracting; now it should just be the laughing model. I'm not sure why the clicks aren't working for you; do you mean when you click on the emoji button the emoji doesn't appear? Or does the emoji appear but not respond to clicks?

**Comment by ShoaibSmith** [comment]
@elisa-lj11 When I click on the emoji button it does not respond.

**Comment by elisa-lj11** [comment]
all volumes have been updated to 0.5

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Re-testing complete:

To my understanding this is for Desktop, I have done them all within VR but it seems it's not designed for VR on most of these, will mention where VR is applicable.

you can load the script via this URL: https://hifi-content.s3.amazonaws.com/elisalj/emoji_scripts/emojiTablet.js) **Pass**
An emoji app button should appear next to other apps; click on this
A tablet app should appear that looks like this **Pass**

Click on "Corny" - a corn model will appear in front of you, you'll hear a rimshot and high pitched laughter, and the corn will look like it's laughing (alternating between a smiling and laughing face) as it rolls around on the floor **Fail, I cannot hear the audio, however, Corny now seems to not disappear in and out, previously he would do so for half a second at a time appearing and disappearing.**
"Fireworks" - a 3D button will appear in front of you which you can press, then a firework will shoot out **Pass**
"Flower" - a flower will appear in front of you and float down, clicking it will replace the flower model with overlays of pink 2D flowers **Fail within Desktop, however as mentioned by dev doing so with Vive controllers / hand grab does work and give the desired effect.**
"Heart" - a 3D heart will float down in front of you **Pass**
"Monster" - a red monster will appear in front of you and walk away from you (even if you turn your avatar and walk towards it), you'll hear a growling sound **Did not hear the growl still**
"Pickle" - a pickle will appear in front of you. If you bring the pickle to your face, you'll hear a crunch and the pickle will disappear **Pass, though not sure if this is PR specific, but I found that the mouth of avatar is too far down, I found myself jamming the pickle (and pizza) into my throat! haha :)**
"Pizza" - a pizza slice will appear in front of you. If you bring the pizza to your face, you'll hear an "om-nom-nom" sound and the pizza will explode **Pass**
"Poo" - a rainbow poo will appear in front of you. If you click it, it'll make a fart sound **Pass**

Notes: I have made sure my Audio is correct and nice and loud to listen out but some audio not working in this.

**Comment by elisa-lj11** [comment]
@YuppyPlays Corny should be a fixed model (so no more disappearing in and out). I'm wondering if the actual audio files of Corny and Monster are too quiet for standard volume settings, I will try making them louder. The flower is only activated with hand controllers, not with click.

**Comment by misslivirose** [comment]
@YuppyPlays - The flower behavior is by design that way, it only spawns flower particles when in HMD mode. By design. The eat script is measured against the head joint, so depending on where your avatar's head joint is, this may be slightly above or below where you'd anticipate a mouth joint. Out of curiosity, which avatar were you using? 

For those, I would say from your description that's a pass. As far as the audio goes, @elisa-lj11, we could check the levels on regular playback of the sound files and see if it's specific to interface.

**Comment by elisa-lj11** [comment]
@misslivirose @YuppyPlays The audio is playing when I tested on another computer, but it's very quiet. I updated the playback volume in the Corn and Monster scripts so now it should be audible (and hopefully not too loud).

**Comment by YuppyPlays** [comment]
@elisa-lj11 
Shall I re-test?
also, I assume not a new build but update goes through the files listed via the .js URL?
(Apologies I am still a bit of a noob 😂

**Comment by elisa-lj11** [comment]
@YuppyPlays that is correct, you won't need a new build, but you may need to clear your cache. A re-test of Corny and Monster sounds good :)

**Comment by YuppyPlays** [comment]
@elisa-lj11 Awesome, will do this and test now :D

**Comment by YuppyPlays** [comment]
Testing complete:

Corny: **Pass** Although the audio is a tad quiet still in my opinion in contrast to other things, but this is purely subjective.

Monster: **Pass** Although the audio is a tad quiet still in my opinion in contrast to other things, but this is purely subjective.

@elisa-lj11 - Great work on this! :D

**Comment by elisa-lj11** [comment]
@YuppyPlays Thank you 😄

**Pull request merged**
