### PR TITLE
Fix warnings in Qt 59 / VS 2017 build

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/738/HighFidelity-Beta-PR10698-d770e2a8c62dbb3c67ba9e9e341376b52750bbfb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/738/HighFidelity-Beta-PR10698-d770e2a8c62dbb3c67ba9e9e341376b52750bbfb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/742/HighFidelity-Beta-PR10698-5a3cf924d5d4d5248bd2c639f32246438f7e35c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/955/HighFidelity-Beta-PR10698-6651fc74737aeeb5adb441de877e2fccfe4471bb.dmg

**Comment by marko8904** [comment]
test this please

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1353/HighFidelity-Beta-PR10698-32a63827e24c2eb11ebf96bddab1ef44d4ba3e9e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1398/HighFidelity-Beta-PR10698-d70d80894e6c911ad7b7c8726734e003fe09c8ed.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1398/HighFidelity-Beta-PR10698-d70d80894e6c911ad7b7c8726734e003fe09c8ed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1420/HighFidelity-Beta-PR10698-5eb7805222f33b3ff0315d1fbbe3593f27fa8751.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1424/HighFidelity-Beta-PR10698-5c24721f61984edab94f35bbc068cc51d20a931a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1424/HighFidelity-Beta-PR10698-5c24721f61984edab94f35bbc068cc51d20a931a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1701/HighFidelity-Beta-PR10698-bbd352ddc33fbb8295ff8ab1b23219afb8204ec2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1701/HighFidelity-Beta-PR10698-bbd352ddc33fbb8295ff8ab1b23219afb8204ec2.dmg

**Pull request closed without merging**
