### PR TITLE
Case 21278: Fix avatar deadlock (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21278/fix-avatar-deadlock-for-80

https://github.com/highfidelity/hifi/pull/14942

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17363/HighFidelity-Beta-PR14943-4de37ea.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17363/HighFidelity-Beta-PR14943-4de37ea.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17363/HighFidelity-Beta-Interface-PR14943-4de37ea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17363/HighFidelity-Beta-PR14943-4de37ea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17363/HighFidelity-Beta-Interface-PR14943-4de37ea.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
