### PR TITLE
Fix for assert in AnimBlendDirectional on startup

### PR DESCRIPTION
**Pull request by hyperlogic**
Specifically, std::vector subscript out of range.

https://highfidelity.atlassian.net/browse/DEV-2699

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22351/HighFidelity-Beta-PR16458-6e7f222.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22351/HighFidelity-Beta-Interface-PR16458-6e7f222.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22351/HighFidelity-Beta-PR16458-6e7f222.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22351/HighFidelity-Quest-Beta-PR16458-6e7f222.apk)

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22381/HighFidelity-Beta-PR16458-6e7f222.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22381/HighFidelity-Beta-Interface-PR16458-6e7f222.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22381/HighFidelity-Beta-PR16458-6e7f222.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22381/HighFidelity-Quest-Beta-PR16458-6e7f222.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22381/HighFidelity-Beta-PR16458-6e7f222.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22381/HighFidelity-Beta-Interface-PR16458-6e7f222.exe

**Pull request merged**
