### PR TITLE
remove initial glitch in Tractor (grab) action

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
TODO: write notes and test plan

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6956/app_12347_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6956/HighFidelity-Beta-PR12347-672520f3bfa53be81acac93d1a9f69298fa12a5b.exe

**Comment by sethalves** [comment]
To test:
- create a cube, make it non-dynamic
- have someone watch while you repeatedly far grab and adjust it
- make sure, as each far-grab starts, it never warps the cube far-away and then quickly returns it

**Comment by sethalves** [comment]
build this please

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/11442/initial-far-grab-often-warps-target-far-away-and-quicky-returns-it

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6966/app_12347_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6966/HighFidelity-Beta-PR12347-672520f3bfa53be81acac93d1a9f69298fa12a5b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6966/HighFidelity-Beta-PR12347-672520f3bfa53be81acac93d1a9f69298fa12a5b.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Stopped Testing, EOD.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. Per the test plan, when a non-dynamic cube is far grabbed, there is no interaction or response at all, and there was no warping. When the cube is near-grabbed, it would occasionally disappear and reappear on or near the user's back. When a cube is switched to dynamic, the far-grabbing works correctly, but when it is near-grabbed the cube will completely disappear from the domain, and cannot be seen from an observer or in the create menu list.

@conklin94122 

https://drive.google.com/open?id=1u7JJvOoicsRVdQjADH2EwPAHXa1gtfs3

12347 back cube

12347 cube

**Comment by AndrewMeadows** [comment]
@sbennett77, just verifying: this bad behavior does NOT happen in hifi/master?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7007/app_12347_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7008/app_12347_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7008/HighFidelity-Beta-PR12347-d056e606c115a28f4901b6627fe2a1799b37eb6c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7008/HighFidelity-Beta-PR12347-d056e606c115a28f4901b6627fe2a1799b37eb6c.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 None of the issues we saw this morning were present, all worked swimmingly!

**Pull request merged**
