### PR TITLE
Attachments Dialog QML updates (from contractor)

### PR DESCRIPTION
**Pull request by birarda**
- updated the styling of the attachments dialog

### CODE REVIEW

**Comment by birarda** [comment]
This work is not mine, comes from a contractor Ryan was working with. He was unable to get a fork setup to submit a PR so I've taken his changes manually and created this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34fb06a7bd43ba12aba32ef65470cb6b47ea0087 available at: https://gist.github.com/34348d913ed4adc1156d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7444.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7444.dmg

**Comment by ctrlaltdavid** [comment]
Each of the "Model URL" etc. labels should not have trailing colons.
The "Is soft" checkbox control should be vertically centred with "Scale" input box.
The "Is soft" checkbox control should have a gap between it and the "Scale" control at low dialog widths: see screen snap for them colliding. (Scale control could perhaps be the same width as the z: controls?)
There should be more whitespace above the "Delete" button, same as between other rows of controls.
The OK button should be on the left and the Cancel button on the right.

attachments-is-soft

**Comment by Nex-Pro** [comment]
2 decimal places is inadequate for positioning small attachments.
maybe change the Translation.qml file

to at least 3  decimals thus.

import "."

Vector3 {
    decimals: 3;
    stepSize: 0.01;
    maximumValue: 10
    minimumValue: -10
}

better still have a key combo that allows fine adjustments.

I was going to test changing the qml file but I'm getting unassociated build errors. Gah

**Comment by RyanDowne** [comment]
I think it would be faster to have @ctrlaltdavid fix these things rather than go back and forth with the contractor. @ctrlaltdavid we'd just create another small worklist job or you could fee in on the one that you have open now.

**Comment by Nex-Pro** [comment]
Oh and what ctrlaltdavid said.  

why is the attachments dialog labelled "Attachments Dialog" and not simply Attachments ?
+ tiny arrows are just too tiny.
+ maybe delete should read  either detach or remove. 
+ Maybe joint should read Attach to or Attachment point.

IMO these dialogs are rather unattractive.

**Comment by Nex-Pro** [comment]
I checked that Translation.qml change and it works fine. Increments in centimeters and allows millimeters.

**Comment by ctrlaltdavid** [comment]
@RyanDowne Sure, a new Worklist job for this would be fine. Would do once this PR is merged with master.
@Nex-Pro Thanks for trying out the Translation.qml change.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  I'm not familar with any of this qml stuff but I changed a couple of the labels.
attachments_dialog

also I found what is probably a typo pair.

                    id: modelBrowserBuiler;
                    ModelBrowserDialog {}
                }

                onClicked: {
                    var browser = modelBrowserBuiler.createObject(desktop);
                    browser.selected.connect(function(newModelUrl){
                        modelUrl.text = newModelUrl;

maybe should be id: modelBrowserBuilder;

**Comment by ctrlaltdavid** [comment]
@Nex-Pro Good catch on the typo! I'll fix that after this PR is merged. ... Labels: I'll probably leave them as they are unless Ryan / Alan want them changed; I think they're pretty much as they want them (apart from the erroneous colons, that is).

**Comment by Nex-Pro** [comment]
@ctrlaltdavid @RyanDowne  Maybe label things for non-programmer users rather than labels that match the field names. Even translation should probably be position. Or Adjust position.

**Pull request merged**
