### PR TITLE
Added steps to run interface in Ubuntu 18.04 .

### PR DESCRIPTION
**Pull request by elmanytas**
Based on leviatan comments published here: https://forums.highfidelity.com/t/please-publish-the-correct-installation-for-linux-ubuntu-16-04-1-lts/11985/17 .

### CODE REVIEW

**Comment by FlameSoulis** [comment]
### Ubuntu 18.04 - Servers only
#### Test without new instructions
Domain Server: **Passed**
Assignment Client: **Failed**
```
./assignment-client/assignment-client: error while loading shared libraries: libnvimage.so: cannot open shared object file: No such file or directory
```

#### Testing Assignment Client with libnvtt2 & libnvtt-dev installed
For some reason, libnvtt2 and libnvtt-dev are not part of the instructions. I installed them anyway and:
Assignment Client: **Failed**
```
./assignment-client/assignment-client: symbol lookup error: /home/flame/hifi/build/ext/makefiles/nvtt/project/lib/libnvtt.so: undefined symbol: _ZN3ZOH5Utils6FORMATE
```

#### Test with new instructions
Domain Server: **Passed**
Assignment Client: **Passed**

I will test Ubuntu 16.04 later on (will be interesting to see how it fairs with libnvtt compiling). However, Ubuntu 16.04's issue is the cmake requirement. At this time, Ubuntu 18.04 is using cmake version 3.10.2. Ubuntu 16.04 is using 3.5.1, resulting in an issue with glad45.

Since the scope of this PR is for Ubuntu 18.04. I can confirm all is good.

**Comment by samcake** [comment]
THis doesn't need QA per say (Flamesoulis did it)

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15830/HighFidelity-Beta-PR13966-0807743.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15830/HighFidelity-Beta-PR13966-0807743.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15830/HighFidelity-Beta-Interface-PR13966-0807743.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15830/HighFidelity-Beta-PR13966-0807743.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15830/HighFidelity-Beta-Interface-PR13966-0807743.exe

**Pull request merged**
