### PR TITLE
Disable flying by default

### PR DESCRIPTION
**Pull request by danteruiz**
This PR disables flying by default

ticket - https://highfidelity.fogbugz.com/f/cases/16206/Flying-jumping-needs-to-be-turned-off-by-default

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan
- make sure you reset your settings / clean install
- goto to settings > controllers, flying option should be checked off.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10906/HighFidelity-Beta-PR13471-3cf36be.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10906/HighFidelity-Beta-PR13471-3cf36be.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10906/HighFidelity-Beta-Interface-PR13471-3cf36be.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Flying is disabled.

**Pull request merged**
