### PR TITLE
Update serverless tutorial for RC68

### PR DESCRIPTION
**Pull request by huffman**
Test Plan:
Ensure changes made to RC68 Tutorial are reflected. Run Tutorial Test suite plus changes outlined in https://highfidelity.manuscript.com/f/cases/15285/Update-tutorial-test-plan-to-include-RC68-Tutorial-Updates

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10025/HighFidelity-Beta-PR13218-153b39ef94f3c797e6aef09637b7e2502f172063.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10026/HighFidelity-Beta-PR13218-76b6f88854ba233765aebff099c212a0ab51fe93.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10026/HighFidelity-Beta-PR13218-76b6f88854ba233765aebff099c212a0ab51fe93.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10026/HighFidelity-Beta-Interface-PR13218-76b6f88854ba233765aebff099c212a0ab51fe93.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10026/HighFidelity-Beta-PR13218-76b6f88854ba233765aebff099c212a0ab51fe93.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10026/HighFidelity-Beta-Interface-PR13218-76b6f88854ba233765aebff099c212a0ab51fe93.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10033/HighFidelity-Beta-PR13218-e40cb7a2544b8f6d9e4032818c5f51395592ee0c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10033/HighFidelity-Beta-PR13218-e40cb7a2544b8f6d9e4032818c5f51395592ee0c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10033/HighFidelity-Beta-Interface-PR13218-e40cb7a2544b8f6d9e4032818c5f51395592ee0c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10033/HighFidelity-Beta-PR13218-e40cb7a2544b8f6d9e4032818c5f51395592ee0c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10033/HighFidelity-Beta-Interface-PR13218-e40cb7a2544b8f6d9e4032818c5f51395592ee0c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
*Finnigon avatar is an inconsistent or oddly sized when compared to the rest
*Grabbing section audio still references cube
*The RMB and LMB phrases are still on the instructions
Other things noted:
*There appears to be a piece of floor missing or not loading. When compared to localhost, there is a builders grid and the tutorial itself is not floating as seen in the pic below.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2031553/hifi-log.txt)
nofloor
finny
lmb

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10052/HighFidelity-Beta-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10052/HighFidelity-Beta-Interface-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10052/HighFidelity-Beta-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10052/HighFidelity-Beta-Interface-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.exe

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10057/HighFidelity-Beta-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10057/HighFidelity-Beta-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10057/HighFidelity-Beta-Interface-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10057/HighFidelity-Beta-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10057/HighFidelity-Beta-Interface-PR13218-5ce784b537dc72550a4b230eb8f6868ccd19ce3a.exe

**Comment by huffman** [comment]
QA Ready, but please wait for the next build

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10066/HighFidelity-Beta-PR13218-ae37b9db6f34522d49431d4da871352a320d535b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10066/HighFidelity-Beta-PR13218-ae37b9db6f34522d49431d4da871352a320d535b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10066/HighFidelity-Beta-Interface-PR13218-ae37b9db6f34522d49431d4da871352a320d535b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10066/HighFidelity-Beta-PR13218-ae37b9db6f34522d49431d4da871352a320d535b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10066/HighFidelity-Beta-Interface-PR13218-ae37b9db6f34522d49431d4da871352a320d535b.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
RMB and LMB are still visible in welcome and avatar sections, while the grabbing section has no label for the mouse button. 
In addition the arrow under "Need more help?" is grabbable.
Everything else is a pass. Audio from grab tutorial is now a good volume.
Log and Video attached.
[Files.zip](https://github.com/highfidelity/hifi/files/2035958/Files.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10083/HighFidelity-Beta-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10083/HighFidelity-Beta-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10083/HighFidelity-Beta-Interface-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 @huffman 
All features look as explained in the ticket. Looks good.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10090/HighFidelity-Beta-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10090/HighFidelity-Beta-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10090/HighFidelity-Beta-Interface-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10090/HighFidelity-Beta-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10090/HighFidelity-Beta-Interface-PR13218-3554334dfcb54a0cf9100ee56fa6e7bb039e9aee.exe

**Pull request merged**
