### PR TITLE
No physics until ready

### PR DESCRIPTION
**Pull request by sethalves**
- Load model geometry as soon as we learn about the entity from the server, rather than the first time we look at the entity.
- When arriving in a new domain, don't enable physics until everything within 3 meters has their hulls loaded.

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/66264103181929

**Comment by hifi-gustavo** [comment]
Build console output for commit: d10221f53a1fddc09987d710fce705ae97deabd1 available at: https://gist.github.com/5d6f2ecfcce4f8c3bf90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6612-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6612.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 98acd14bcce63d2f942e7e5147c304729a3fdc15 available at: https://gist.github.com/5d6f2ecfcce4f8c3bf90<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6612-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6612.dmg

**Comment by howard-stearns** [comment]
smokes ok

**Pull request merged**
