### PR TITLE
Fix users.js maximize button unclickable with hand controllers

### PR DESCRIPTION
**Pull request by huffman**
Using hand controllers, you cannot click closer than 25px to the edge of HUD/Overlay region. This becomes a problem with users.js because the maximize button is within this region. To fix this, I've added padding on all sides of the users window so that you cannot move the window itself too close to the edge of the screen, making the maximize button unclickable.

To test:

 1. Move the users.js window as far to the bottom left of the overlay area as possible.
 1. Make sure you can maximize and minimize the users.js window
 1. Move the users.js window as far to the bottom right of the overlay area as possible.
 1. Make sure you can maximize and minimize the users.js window

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5dab2ac2a7b492b46d741f818bfdb3ccd4aaf412 available at: https://gist.github.com/1a5a2c58248d679dafc1a08180d63535<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9033-5dab2ac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9033-5dab2ac.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
### PASS works fine

**Comment by huffman** [comment]
Thanks @Nex-Pro !

**Pull request merged**
