### PR TITLE
Beta Release 14 - Includes up to Developer Release 5068

### PR DESCRIPTION
**Pull request by ZappoMan**
- make audio device selection available to basic menus
- fix reporting of JSON export failure
- fix to edit.js logging
- log file spam cleanup
- add face camera option to edit.js text entity properties
- let user choose an existing file in the file save dialog
- hide users.js options when logged out
- fix domain-server permissions-grid usernames to be case insensitive
- fix skeleton switching bug
- fix entity lifetime guards for temporary object domain rights
- fix domain metadata settings
- add operating hours to domain metadata
- fix setting velocity of inactive kinematic RigidBody
- add client-side session id generation and new user activities
- support physics from visual mesh for static mesh entities
- add heartbeats to metaverse for temporary domains
- add build version to heartbeat
- removed buggy Mac Hydra support
- fix initial visibility of QML windows from scripts
- fix for grab script search ray length
- cap lifetime rather than reject edits from nodes which only have tmp-rez rights
- automatically enter first person when in HMD mode
- improve Vive hand controller UI
    - manipulate and interact with HUD elements using hand controller trigger. 
    - text fields open the Vive virtual keyboard.
    - better HUD positioning
    - UI buttons for common operations
- updates to hand controller/equip behavior
    - equipable entities display a green ball when you partially trigger.
    - equip by trigger with your hand inside the equip location
    - you can then use trigger to "fire".
    - release by holding the object upside down and shaking while triggering

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: de7738e644e5a3709be65a10be9be8fe9ed14e73 available at: https://gist.github.com/ecf5f06c978a990b6b4387b6ee388d01<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8140.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8140.dmg

**Comment by judasshuffle** [comment]
Just a first test opinion It seems to be working really well on my own domain and on dev playa.The jumpiness I was getting on the cv1 has gone and i really like the new headset on off button so much easier to use. Ill keep on this build for the weekend and see how I get on :)

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Extremely smooth integration with Rift and Hydras.  Solid framerates and agree with @judasshuffle that the new headset UI is a great enhancement to the user experience.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2507 |2513 |3683
**GPU Buffer Count**: |444 |216 |576
**CPU Memory Usage**: |39440384 |58593280 |71110656
**GPU Memory Usage**: |8904704 |24399872 |33984512
**CPU Texture Count**: |177 |187 |286
**GPU Texture Count**: |303 |260 |318
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |213412868 |607634692 |507518148
**GPU Texture Memory Usage**: |755959910 |248939432 |677139385
**GPU Virtual Memory Usage**: |885997670|378977192|807177145
**Triangle Count**: |218943 |280867 |619185
**Triangle Rate**: |13683937 |18724466 |36422647
**API Drawcall Count**: |158 |55 |225
**Drawcall Count**: |158 |201 |226
**Drawcall Rate**: |9875 |13400 |13294
**State Changes Texture Count**:|126 |64 |253
**Pipeline Count**: |22 |20 |34
**Item Opaques**: |197 |111 |212
**Item Translucents**: |4 |3 |47
**Item Lights**: |15 |18 |25
**Timing Opaques**: |1257 |561 |1352
**Timing Translucents**: |53 |48 |330
**Timing Lighting**: |99 |149 |167
**Render Frame**: |2105 |1440 |2538

**Comment by OmegaHeron** [comment]
Windows 10 64 Bit - i5 6500 CPU - GTX970 GPU

General Notes:

My setup continues to have issue with poor performance.  Nothing new, nothing improved and nothing worsened.  Once GPU RAM gets tight - things go poorly.  I have a fix - when it goes nuts - quit Interface and start again.  :)  That's a far more efficient and smooth experience to free GPU RAM and keep performance high - and is faster than waiting for Interface to finish thrashing or, eventually, deadlock crash and force me to restart.

By the book - I would have to give QA Fail as playaPerformanceTest.js fails for dev-playa and dev-demo with spikes well above red line.  Localhost is worse (the insane number of lights seems to "accentuate" failure mode) - removing them from scene or insuring those that have toggles are off makes a great difference.  I can't attach a playaPerformanceTest.js graph for localhost as it never captures its true data - dirty little secret... if Interface is deadlocked (temporary), CPU is red-lined - it seems script engine doesn't get run time, and it doesn't capture what should be a vertical spike to vertical bounds of graph window.  Just reminding that this continues to be an issue on a system that is above minimal requirements.

Users.js display continues to be corrupted for me.  Did the fix for not get into this PR or is it failing for me?

I'll continue with standard test battery + HMD (via DK2) tests shortly.

**Comment by ZappoMan** [comment]
@OmegaHeron - thanks for the report, can you please include your performance screen shots on this. And also can you pleas include the comparison tests with the current beta 13 build. It sounds like you're sayin there is a difference between performance with Beta 13 and this build. And if there is, then this is a Fail.

**Comment by OmegaHeron** [comment]
@ZappoMan - No, not saying that - it's same as RC13 same as RC12 etc.  I'm just refreshing that I'm continuing to have the same problems I've complained of since I built this new system as outlined in fogbugz report.  It's not a fail.  I just haven't refreshed my complaints of the standard poor performance in a while.  I'll attach graphs and all the trimmings along with my full report - be a bit.

**Comment by OmegaHeron** [comment]
Testing Windows 10 64 bit - i5 6500 CPU - GTX 970 GPU
**Desktop mode - keyboard/mouse**
All standard tests pass - compared to RC12 and RC13 no negative change seen to GPU/CPU loading.

**HMD Mode - DK2 - keyboard/mouse/xbox controller**
All standard test pass - having only just gotten HMD I went over RC12 and RC13 to get baseline numbers and feel.  RC14 Shows improvement in complex scenes like Playa.

Other than users.js continuing to have a corrupted display it's a QA Pass.

**Comment by OmegaHeron** [comment]
## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: playaPerformanceTest.js pass conditional upon not allowing GPU VRAM to fill - per known issue with i5 CPU + GTX970.

**Desktop Mode Stats**

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |5462 |5852 |4514
**GPU Buffer Count**: |1610 |1890 |1102
**CPU Memory Usage**: |87621632 |105406464 |86913024
**GPU Memory Usage**: |56893440 |67903488 |48324608
**CPU Texture Count**: |332 |418 |315
**GPU Texture Count**: |541 |1464 |1055
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |142869704 |214912576 |260574208
**GPU Texture Memory Usage**: |1113891748 |2133561771 |1228376240
**GPU Virtual Memory Usage**: |1227343388|2276609491|1371423960
**Triangle Count**: |833987 |335361 |574626
**Triangle Rate**: |52124187 |19727117 |35914125
**API Drawcall Count**: |170 |107 |215
**Drawcall Count**: |172 |108 |1131
**Drawcall Rate**: |10750 |6352 |70687
**State Changes Texture Count**:|217 |140 |276
**Pipeline Count**: |27 |25 |37
**Item Opaques**: |221 |157 |210
**Item Translucents**: |5 |2 |27
**Item Lights**: |22 |18 |23
**Timing Opaques**: |1439 |1354 |1889
**Timing Translucents**: |112 |114 |363
**Timing Lighting**: |132 |213 |166
**Render Frame**: |2330 |2607 |3234

**HMD Mode Stats (Oculus DK2)**

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |73 |75 |75
**Present Rate**: |73 |75 |75
**Present New Rate**: |72 |75 |75
**CPU Buffer Count**: |5426 |5709 |4662
**GPU Buffer Count**: |1710 |1946 |1258
**CPU Memory Usage**: |86863872 |105185280 |84492288
**GPU Memory Usage**: |65261568 |80379904 |48144384
**CPU Texture Count**: |359 |427 |336
**GPU Texture Count**: |656 |1056 |1156
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |57502316 |96068280 |183864320
**GPU Texture Memory Usage**: |1328361446 |2355720862 |1334849864
**GPU Virtual Memory Usage**: |2042769686|3070129102|2049258104
**Triangle Count**: |2584091 |790369 |1035166
**Triangle Rate**: |198776230 |60797615 |79628153
**API Drawcall Count**: |390 |164 |224
**Drawcall Count**: |1023 |511 |599
**Drawcall Rate**: |78692 |39307 |46076
**State Changes Texture Count**:|415 |183 |236
**Pipeline Count**: |41 |29 |33
**Item Opaques**: |492 |194 |191
**Item Translucents**: |44 |3 |24
**Item Lights**: |25 |26 |23
**Timing Opaques**: |2813 |1895 |1608
**Timing Translucents**: |217 |141 |380
**Timing Lighting**: |81 |276 |248
**Render Frame**: |3658 |3166 |3171

**Comment by OmegaHeron** [comment]
In reference to users.js being broken #8139 would resolve and, in my humble opinion, should be dealt with before a RC pass.

**Comment by OmegaHeron** [comment]
Upon review of https://highfidelity.fogbugz.com/f/cases/1029/CTRL-Q-stopped-working

I checked this build and found that none of following worked in Desktop or HMD mode;
Ctrl Q, Ctrl J, Ctrl Shift A

I had noticed Ctrl J didn't work on one run before seeing fobugz case, but couldn't reproduce it across runs.  It's currently random for me - one run keyboard commands work, another they don't - if I'm in a session where they're not working - using mouse to open a menu item like ATP browser seems to restore keyboard controls.

**Comment by thoys** [comment]
# QA Test

## Smoke Test
**QA Tester**: @thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: All the smoketests ran smooth.


## Domain stats

### Desktop Mode

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |5507 |5603 |4587
**GPU Buffer Count**: |1258 |842 |938
**CPU Memory Usage**: |74649600 |108576768 |82853888
**GPU Memory Usage**: |26140672 |29409280 |43065344
**CPU Texture Count**: |285 |339 |332
**GPU Texture Count**: |1956 |1990 |2275
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |287941112 |880671488 |320030112
**GPU Texture Memory Usage**: |595705655 |977273755 |1115435296
**GPU Virtual Memory Usage**: |729471287|1111039387|1249200928
**Triangle Count**: |482654 |365666 |683872
**Triangle Rate**: |30165875 |20314777 |42742000
**API Drawcall Count**: |457 |117 |271
**Drawcall Count**: |591 |240 |1173
**Drawcall Rate**: |36937 |13333 |73312
**State Changes Texture Count**:|289 |159 |322
**Pipeline Count**: |32 |22 |40
**Item Opaques**: |507 |173 |276
**Item Translucents**: |40 |3 |52
**Item Lights**: |17 |19 |26
**Timing Opaques**: |4535 |3346 |3405
**Timing Translucents**: |330 |177 |487
**Timing Lighting**: |299 |405 |264
**Render Frame**: |6529 |5815 |5372

### Vive

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |90 |90
**CPU Buffer Count**: |4070 |6071 |5409
**GPU Buffer Count**: |1480 |1323 |1524
**CPU Memory Usage**: |57077760 |111169536 |106569728
**GPU Memory Usage**: |31191040 |38264832 |58720256
**CPU Texture Count**: |203 |371 |345
**GPU Texture Count**: |595 |720 |611
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |212457060 |876175784 |412247292
**GPU Texture Memory Usage**: |436022933 |1056720701 |1051392304
**GPU Virtual Memory Usage**: |792785813|1413483581|1408155184
**Triangle Count**: |1057893 |823138 |1471988
**Triangle Rate**: |96172090 |82313800 |147198800
**API Drawcall Count**: |485 |189 |310
**Drawcall Count**: |927 |557 |2369
**Drawcall Rate**: |84272 |55700 |236900
**State Changes Texture Count**:|265 |194 |343
**Pipeline Count**: |34 |28 |43
**Item Opaques**: |520 |232 |300
**Item Translucents**: |11 |12 |53
**Item Lights**: |19 |30 |25
**Timing Opaques**: |3681 |1883 |2552
**Timing Translucents**: |44 |127 |289
**Timing Lighting**: |96 |312 |104
**Render Frame**: |4614 |3345 |3483

## Eye Tests

**EYE-01 Test Result**: **EYE-01 Test** SUCCESS
**EYE-02 Test Result**: **EYE-02 Test** SUCCESS
**EYE-03 Test Result**: **EYE-03 Test** SUCCESS
**EYE-04 Test Result**: **EYE-04 Test** SUCCESS
**EYE-05 Test Result**: **EYE-05 Test** SUCCESS
**EYE-06 Test Result**: **EYE-06 Test** SUCCESS
**EYE-07 Test Result**: **EYE-07 Test** SUCCESS
**Additional Test Results + Observations**: All the eye-tests worked out perfectly fine.


## Bug(s)

- The users.js script doesn't seem to function properly (Add friends button and the two selectboxes are missing)


QA Fail (users.js is an important part of the Beta, it helps us finding eachother. Please fix.)

**Comment by ZappoMan** [comment]
@thoys - what was the issue with these failures: 

```
playa 'playaPerformanceTest.js' Result: dev-playa 'playaPerformanceTest.js' FAILURE
cellscience 'playaPerformanceTest.js' Result: dev-demo 'playaPerformanceTest.js' FAILURE
```
Can you please elaborate?

**Comment by thoys** [comment]
@ZappoMan I overlooked 2 checkboxes in the test script. Sorry about that!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bde849ed6b5a673121e2248571d660b761600bd available at: https://gist.github.com/ecf5f06c978a990b6b4387b6ee388d01<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8140.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8140.dmg

**Comment by kevinmthomasse** [comment]
re-testing

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass:  FAILURE**
**localhost 'createTestBlocks.js' Result**:  The ```users.js``` issue is still present.  Screen-shot attached.
capture

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass:  PARTIAL-SUCCESS**
**localhost Result**: I logged out upon entering ```localhost``` in Interface. Upon login, ```users.js``` was working properly. The init phase appears to have an issue.  Updated screen share.
capture

**Comment by thoys** [comment]
# QA Update

QA Success , users.js loads and shows correctly for me.

**Comment by OmegaHeron** [comment]
It loads and does all its bits proper for me as well.  Brief brush over standard tests shows no issues.  QA Pass.

**Pull request merged**
