### PR TITLE
fix includeActions so places show up in All

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug in goto page that kept places from showing up in the All tab

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4078

**Comment by sethalves** [comment]
to test:
- open the goto page, make sure places (and not just snapshots) show up in the "All" tab.

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb281389f5ceb715f77acfaaa0b5cbd83394c8b7 available at: https://gist.github.com/270cb815bb56e704129ec439122a46f8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10186-eb28138.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10186-eb28138.dmg

**Comment by OmegaHeron** [comment]
QA Pass given since I had already began test.

**Pull request merged**
