### PR TITLE
Remove verbose logging of keyboard messages in edit.js and gridTool.js

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
# Test plan

 1. This addresses https://highfidelity.manuscript.com/f/cases/16951/Web-event-error-for-Virtual-Keyboard-while-in-Desktop-mode - please ensure that you no longer see this error in your logs using the repro steps in the ticket.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13116/HighFidelity-Beta-PR14029-8805ce4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13116/HighFidelity-Beta-PR14029-8805ce4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13116/HighFidelity-Beta-Interface-PR14029-8805ce4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13116/HighFidelity-Beta-PR14029-8805ce4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13116/HighFidelity-Beta-Interface-PR14029-8805ce4.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13217/HighFidelity-Beta-PR14029-8805ce4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13217/HighFidelity-Beta-PR14029-8805ce4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13217/HighFidelity-Beta-Interface-PR14029-8805ce4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13217/HighFidelity-Beta-PR14029-8805ce4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13217/HighFidelity-Beta-Interface-PR14029-8805ce4.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

Virtual keyboard errors no longer appear in desktop mode.

**Pull request merged**
