### PR TITLE
Fixed not being able to load a script url that has a white space

### PR DESCRIPTION
**Pull request by druiz17**
If you load a script using a url and that url has whitespace it still should load.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Open Running Scripts
-Click "From URL"
- Paste https://s3-us-west-1.amazonaws.com/hifi-content/zfox/spectator-camera/spectatorCamera.js with whitespace before and after and press OK
- the script should load
- remove the script and reload it with no whitespace and it still should load

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1752/HighFidelity-Beta-PR10989-bcc15dd4aeba553b70f55a9166d0f332a4aa2875.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1752/HighFidelity-Beta-PR10989-bcc15dd4aeba553b70f55a9166d0f332a4aa2875.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
[Had a bit of weird delay due to slow speeds on the build download]

Loading w/ whitespaces: **Pass**
Loading w/o whitespaces: **Pass**

Notes: Script loaded both times, but did not show an app on toolbar/tablet either time. Not sure if intended or not, but following the test plan wording, this is a pass.

**Pull request merged**
