### PR TITLE
Fix frame dtor crash

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/15576/Frame-dtor-crash-on-exit

When the CompositorHelper is destroyed, it destroys the DisplayPlugin, which destroys a bunch of Frames, which call the FramebufferRecycler, which calls DependencyManager::get\<FramebufferCache\>(), which has already been destroyed.  Now we destroy the CompositorHelper before the FramebufferCache.

Test plan:
- I don't have a solid repro, but you shouldn't crash on exit.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10826/HighFidelity-Beta-PR13442-203f471.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10826/HighFidelity-Beta-PR13442-203f471.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10826/HighFidelity-Beta-Interface-PR13442-203f471.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10826/HighFidelity-Beta-PR13442-203f471.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10826/HighFidelity-Beta-Interface-PR13442-203f471.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by SamGondelman** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/13436

**Pull request closed without merging**
