### PR TITLE
Allow the tablet to be closed when a modal dialog is open.

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Will test when build and test plan becomes available :)

**Comment by druiz17** [comment]
Test plan
- In tablet mode
- try to connect to a domain that is down (like your sandbox)
- A message should appear on your tablet
- without responding to the message box, close and open the tablet. If you can do that. QA PASS

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1597/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1597/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Pass** I am able to close and re-open tablet without effecting the dialogue box on tablet screen. Dialogue does disappear after clicking OK also as expected.

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1618/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1634/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1648/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1648/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1664/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1664/HighFidelity-Beta-PR10951-12206cf711cf0de06a8e55eeba98120653742198.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1673/HighFidelity-Beta-PR10951-b46dc7d389224d3ee609974df5ef406885502911.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1673/HighFidelity-Beta-PR10951-b46dc7d389224d3ee609974df5ef406885502911.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1675/HighFidelity-Beta-PR10951-03fbd2a1e6a029723ebb063e7392bd38ce593d34.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1675/HighFidelity-Beta-PR10951-03fbd2a1e6a029723ebb063e7392bd38ce593d34.exe

**Pull request merged**
