### PR TITLE
Fix orientation of non-solid rectangle3d overlays, too

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Oops, I only fixed the orientation of solid rectangle3d overlays before.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8297bbd5e7622d59b87425aed3542eea834f174a available at: https://gist.github.com/98a325651a27b35c0862<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by ctrlaltdavid** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8297bbd5e7622d59b87425aed3542eea834f174a available at: https://gist.github.com/7eeddc841b40087a9d45<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8297bbd5e7622d59b87425aed3542eea834f174a available at: https://gist.github.com/a38268d929d1e7e74d28<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.dmg

**Comment by ctrlaltdavid** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8297bbd5e7622d59b87425aed3542eea834f174a available at: https://gist.github.com/1f3624e8db2420d0bfca<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8297bbd5e7622d59b87425aed3542eea834f174a available at: https://gist.github.com/8ed6ad8558ea950cdc48<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4216.dmg

**Pull request merged**
