### PR TITLE
Updating repo script to match marketplace script

### PR DESCRIPTION
**Pull request by alexiamandeville**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8100/app_12668_PR.apk

**Comment by sethalves** [comment]
could we run this script through jshint.com?  there are many minor troubles with it.

**Comment by alexiamandeville** [comment]
Updated with jshint suggestions.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8191/app_12668_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8191/HighFidelity-Beta-PR12668-35551f045c120bb2664be13dc85c0c4da1bf0bee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8191/HighFidelity-Beta-PR12668-35551f045c120bb2664be13dc85c0c4da1bf0bee.exe

**Comment by Atlante45** [comment]
@alexiamandeville The jshint changes look fine to me. We should run it once to make sure everything still works, but otherwise, it looks good.

**Comment by alexiamandeville** [comment]
I run it, it works as expected.

**Pull request merged**
