### PR TITLE
Fix models starting as green boxes

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- Go to a domain with lots of models (dev-welcome is good).
- In master, green boxes show up everywhere until the models load.  In this PR, models won't show up until they actually load.
- Create a model with a junk url.  It should show up as a green box after a few seconds.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10426/HighFidelity-Beta-PR13326-c18602d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10426/HighFidelity-Beta-PR13326-c18602d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10426/HighFidelity-Beta-Interface-PR13326-c18602d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10426/HighFidelity-Beta-PR13326-c18602d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10426/HighFidelity-Beta-Interface-PR13326-c18602d.exe

**Comment by QliCknox** [comment]
Currently testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Domains load as intended in this PR. Models with proper URLs load with out green boxes surrounding them.
Models created with a junk URL do still appear fairly quickly.
Green boxes do still appear while loading if their model URLs are broken.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10463/HighFidelity-Beta-PR13326-c18602d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10463/HighFidelity-Beta-PR13326-c18602d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10463/HighFidelity-Beta-Interface-PR13326-c18602d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10463/HighFidelity-Beta-PR13326-c18602d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10463/HighFidelity-Beta-Interface-PR13326-c18602d.exe

**Pull request merged**
