### PR TITLE
WL 21545: Fix up the doppleganger mirror script

### PR DESCRIPTION
**Pull request by humbletim**
This PR implements a potential fix for the doppleganger "scrunching up into a ball" issue.

#### Test plan:
This is a pure JavaScript change -- so the current Beta release should be fine for testing.
* Load [app-doppleganger-marketplace.js](https://raw.githubusercontent.com/humbletim/hifi/708698f/unpublishedScripts/marketplace/doppleganger-attachments/dist/app-doppleganger-marketplace.js) from this PR branch.
* Use the "Mirror Mode" button to test doppleganger use across a few different avatar models and attachment combos. 
  image
* Verify that none of the dopplegangers appear scrunched up.

#### Deployment:
* Once approved the existing [Mirror Mode](https://highfidelity.com/marketplace/items/d7d6f41b-6e3e-49a3-b195-7afa0d91c6d0) marketplace item will need to have its app-doppleganger-marketplace.js script replaced with the one from this PR.
* Users running the earlier version will need to stop via Running Scripts... and then re-install from the marketplace. 

*Note: The underlying issue might be that `MyAvatar.getJointTranslations()` now returns translations in meters (as opposed to centimeters) -- or maybe the opposite with how underlying Model/Rig code works behind `ModelOverlay`'s application of the `jointTranslations` property.*

// WL item https://worklist.net/21545

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3460/HighFidelity-Beta-PR11410-708698f07913a887ea674b3d5a1b90ecd6118a03.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3460/HighFidelity-Beta-PR11410-708698f07913a887ea674b3d5a1b90ecd6118a03.exe

**Comment by cain-kilgore** [comment]
Testing

**Comment by cain-kilgore** [comment]
# Test Passed
Avatars | Avatars
--- | ---
bec1e71d-f6a6-40ae-a8d7-fb2b7be30478 | 55855120-b17e-475b-a850-f353d6718dd7
3e490fe1-22f0-4a07-94e7-1eaaff30bdac | 312b7278-3d28-4614-80c6-611c823ff521
7f1ebc2e-a65b-45bd-be53-0876c86ca779 | 0c720c9a-e3c0-405b-bfd4-f4b964acc621 | f01d6186-10b7-475d-879d-dbe68d09760d

All seemed to appear okay. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
