### PR TITLE
fix senderID in messages, dry up code

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: abf169ebd9fe7328883efc07a6af6dad7e599ced available at: https://gist.github.com/446d8b3e832d48f01bb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e5e33446e0fcf26d746c6b0734cfc0c1c85614e available at: https://gist.github.com/446d8b3e832d48f01bb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e530aa6545b925f35e1651a9c5def71f9f0bc38d available at: https://gist.github.com/446d8b3e832d48f01bb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: caa8b0b5b6ff02dca0a7d71bd10cbeb26ccbdc1d available at: https://gist.github.com/446d8b3e832d48f01bb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7441e20f5842ab2b7d1fe8ff175a05feafd41d5d available at: https://gist.github.com/446d8b3e832d48f01bb4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6448.dmg

**Comment by jherico** [comment]
I don't get why all the `const QString&` were replaced with `QString`, but I doubt it's critical.

**Pull request merged**
