### PR TITLE
Fix MS17495: Initially wire sendMessage to ignore in appUi module

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS17495](https://highfidelity.manuscript.com/f/cases/17495). Also fixes an unticketed bug where an app that uses the `appUi.js` module and doesn't define a `sortOrder` would break the app.

### CODE REVIEW

**Comment by howard-stearns** [comment]
developer tested. no additional testing needed

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11983/HighFidelity-Beta-PR13794-d2828fb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11983/HighFidelity-Beta-PR13794-d2828fb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11983/HighFidelity-Beta-Interface-PR13794-d2828fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11983/HighFidelity-Beta-PR13794-d2828fb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11983/HighFidelity-Beta-Interface-PR13794-d2828fb.exe

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12016/HighFidelity-Beta-PR13794-394f93f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12016/HighFidelity-Beta-PR13794-394f93f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12016/HighFidelity-Beta-Interface-PR13794-394f93f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12016/HighFidelity-Beta-PR13794-394f93f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12016/HighFidelity-Beta-Interface-PR13794-394f93f.dmg

**Pull request merged**
