### PR TITLE
Case 21159: fixes for more grab bugs

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/21159/More-grab-bugs-fixed-in-0-79-need-to-also-go-into-0-80

Two grab bugs were fixed in 0.79.0 (in PR-14894) and the fixes need to be ported to hifi/master for 0.80.0.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17236/HighFidelity-Beta-PR14909-ed8481e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17236/HighFidelity-Beta-PR14909-ed8481e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17236/HighFidelity-Beta-Interface-PR14909-ed8481e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17236/HighFidelity-Beta-PR14909-ed8481e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17236/HighFidelity-Beta-Interface-PR14909-ed8481e.exe

**Comment by samcake** [comment]
REady for pre merge qa

**Pull request merged**
