### PR TITLE
progress.js updates

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1b86fe3d2309d9f344520001f9360d0ef6fa49a available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-c1b86fe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-c1b86fe.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 873e7b63dfe7366e487111695523d31a5b1b9a36 available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-873e7b6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-873e7b6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a786224297f229728af9c2dbce03ccce7b352885 available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-a786224.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-a786224.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58932a6806f726b2337c94166d80b567d3d7f208 available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-58932a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-58932a6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91f847a7f0aa8561a63119bb612d6b9c4e2e34b7 available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-91f847a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-91f847a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f6da23b15b7d9d14ce24dd7353383c34a38665e available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-9f6da23.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-9f6da23.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5d50389e29adaead7dc9428ddab62af704d9d9d6 available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-5d50389.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-5d50389.dmg

**Comment by huffman** [comment]
The goal of this PR is to improve the behavior of the progress bar. Previously it would be based on the progress of active downloads, which caused it to jump around as new downloads started because the overall progress would decrease. This PR makes the following changes:

- Makes sure the progress bar never goes down
- Is more resilient to many downloads starting at once
- Smooths out the animation
- Updates the look of the progress bar
- Removes the 3D overlay when in HMD and instead displays the same HUD progress bar

To test:

- Stop progress.js if you are running it
- Run https://rawgit.com/huffman/hifi/feat/progress-updates/scripts/system/progress.js
- Go to a domain with a lot of content like `playa`.
- Observe that the loading bar works, has a new look, never goes down (unless it has already reached 100%), and has a smooth animation.
- Try doing the same but turning around when you get to the domain. You should again see that the progress bar should not go down as you see new entities.
- Test going to different domains and make sure that the progress bar works as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: adbd9ff85428bc99fcb28cc8db6bf190b0f0eb4e available at: https://gist.github.com/13cbae98d4ce026751a35c999eaae3cc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-adbd9ff.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8331-adbd9ff.dmg

**Comment by nbq** [comment]
testing this now

**Pull request merged**
