### PR TITLE
Fix move after import

### PR DESCRIPTION
**Pull request by sethalves**
- fix movement of hierarchical entity structures when parents and children are both in the selection

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open CREATE
- import http://mpassets.highfidelity.com/a567337a-7bba-462a-b07e-feeeca26a284-v1/piano.json
- without changing the selection, grab an affordance and translate the piano vigorously
- also vigorously rotate the piano
- observe that the keys stay in place, relative to the piano base
- also try this with http://mpassets.highfidelity.com/3809f3ac-a842-43a2-af62-acfadbb72c7c-v1/mirror%20with%20handle.json

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/13715/Complex-multi-piece-parent-child-hierarchies-children-lose-accurate-position

**Comment by sethalves** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/12770

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8449/HighFidelity-Beta-PR12769-6a6e91903112c154ddc1f17d5f75ef7ca95f7ffb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8449/HighFidelity-Beta-PR12769-6a6e91903112c154ddc1f17d5f75ef7ca95f7ffb.dmg

**Pull request closed without merging**
