### PR TITLE
CR for Job #21299 - Save category on Marketplace when using back button

### PR DESCRIPTION
**Pull request by mnafees**
Code Review for Job #21299 - Workitem available at https://www.worklist.net/21299

### CODE REVIEW

**Comment by mnafees** [comment]
## How to test

Open marketplace. Select a category and select one of the items. Then click the "back" button. The category is still stored. Now that it uses native browser history to navigate back, the back button works on all pages, like a normal back browser button.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/466/HighFidelity-Beta-PR10633-608becef7dd7f3af88bc7f81ecc90c30ae816980.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/466/HighFidelity-Beta-PR10633-608becef7dd7f3af88bc7f81ecc90c30ae816980.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested in Desktop Mode and VR

Tested: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/466/HighFidelity-Beta-PR10633-608becef7dd7f3af88bc7f81ecc90c30ae816980.exe

Pass:
- Clicking on Back does return you to the previous page as intended.
- Tested on a few categories and items. Back works as intended.

**Pull request merged**
