### PR TITLE
fix agent audio underflow

### PR DESCRIPTION
**Pull request by zzmp**
- prevent agents' audio clocks from sleeping too long

### CODE REVIEW

**Comment by zzmp** [comment]
QA:

Run 20 or more bots using the [attached script, bot.js.txt](https://github.com/highfidelity/hifi/files/557036/bot.js.txt) (you will need to rename it bot.js), as agents.
Go to your domain-settings' Nodes page, and click on the audio-mixer to get the stats.
Ensure that each bot has a stream by verifying the number in "avg_streams_per_frame" (may take a moment for them all to start up).

**Comment by zzmp** [comment]
Fixes https://highfidelity.fogbugz.com/f/cases/edit/2095/Large-number-of-scripted-agents-causes-their-audio-to-fail.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32040a904740c8c2fede6c41ddc217cd8fdf554e available at: https://gist.github.com/86b3dc7436e551b1fffbfbe8fb7c776b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-32040a9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-32040a9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c14a928db5957f9338529b6fd0126ccb557cf57e available at: https://gist.github.com/86b3dc7436e551b1fffbfbe8fb7c776b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-c14a928.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-c14a928.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c14a928db5957f9338529b6fd0126ccb557cf57e available at: https://gist.github.com/86b3dc7436e551b1fffbfbe8fb7c776b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-c14a928.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8937-c14a928.dmg

**Comment by howard-stearns** [comment]
tested per plan, and also using crowd-agent/summon.
Also tested a local build that also pulled in #8936

**Pull request merged**
