### PR TITLE
Assign lowest available suffix when display-names collide

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
https://highfidelity.manuscript.com/f/cases/19503/_1-_2-_3-etc-appended-after-displaynames

Upon display-name collisions the automatically suffixed number was monotonically increasing, per display-name, per domain. This is annoying to users who often leave and quickly return.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16975/HighFidelity-Beta-PR14837-d0fb09a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16976/HighFidelity-Beta-PR14837-e4ffc93.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16976/HighFidelity-Beta-PR14837-e4ffc93.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16976/HighFidelity-Beta-Interface-PR14837-e4ffc93.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16980/HighFidelity-Beta-PR14837-322030f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16980/HighFidelity-Beta-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16980/HighFidelity-Beta-Interface-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16980/HighFidelity-Beta-PR14837-322030f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16980/HighFidelity-Beta-Interface-PR14837-322030f.exe

**Comment by howard-stearns** [comment]
There are some subtle intended behaviors for session display name, for which alas don't seem to be documented. (My bad.) Thanks for diving into this - could you dive in a bit more and let me know which of the following ideals the new code conforms to?

1. Session display name is stable throughout the bearer's domain session. (So that observers are not confused into thinking the bearer is a different user.)
2. (1) is true even when the bearer changes their display name during the domain session.
3. Session display name is unique among those present. (So that observers do not confuse one user for another.)
4. (3) is true even over the domain session of each observer. (E.g., during a single observer domain session, one bearer comes and goes, and then another bearer comes with the same display name, but should get a different session display name so that the observer doesn't think the first guy is back.)
5. All observers see the same unique session display name. (So that two observers can accurately communicate with each other about the bearer.)

**Comment by SimonWalton-HiFi** [comment]
Howard - (2) is not true; if the user changes their display name via the Avatar or PAL menus then their session name will change. I think the other points are true - the session name is universal within the domain and the suffixes guarantee uniqueness.

**Comment by howard-stearns** [comment]
Excellent! How hard would it be to make 2 be true? (Not clear to me whether we lost that somewhere along the way by fiddling with the code, or whether it just happened now with the switch from nodeData->getBaseDisplayName. Might not be worth it to keep, but it's worth looking a bit.

**Comment by SimonWalton-HiFi** [comment]
Is the requirement that a user be assigned a session name the first time they enter a domain and then that becomes permanent for the lifetime of the domain? That could be done but it seems like a change from the current approach. The PR just enforces uniqueness with display-name collisions.

**Comment by howard-stearns** [comment]
definitely not needed for the lifetime of the domain.

The original implementation (which we may have lost along the way, and in any case isn't a hard requirement now, but it is a desirable result that it worth trying to have if it isn't too hard to do in a timely way,) is that it was enforced while people were still there. IIRC, it was implemented with a high water mark that was retained up until the last person had left the domain and then reset to zero. But I may be misremembering.

**Comment by SimonWalton-HiFi** [comment]
I think we need a separate confluence doc to track the session-name requirements.
The existing code keeps a high-water mark per basename; it resets it when the last of that basename leaves. E.g. when the last display-name "Fred" leaves the next to enter becomes Fred, then Fred_1 etc. It does not wait for the domain to be empty to reset the counts. If the existing behaviour is required we should just drop the PR.

**Comment by howard-stearns** [comment]
got it. Let's go with this then.

I get the desire to work out the requirement, but frankly, it's not going to happen. It's too technical and too obscure to take the time of business and user stakeholders, and thus it ends up being a bunch of geeks trying to figure out what's cool.

**Comment by antoninahifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17094/HighFidelity-Beta-PR14837-322030f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17094/HighFidelity-Beta-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17094/HighFidelity-Beta-Interface-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17094/HighFidelity-Beta-PR14837-322030f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17094/HighFidelity-Beta-Interface-PR14837-322030f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17168/HighFidelity-Beta-PR14837-322030f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17168/HighFidelity-Beta-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17168/HighFidelity-Beta-Interface-PR14837-322030f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17168/HighFidelity-Beta-PR14837-322030f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17168/HighFidelity-Beta-Interface-PR14837-322030f.exe

**Pull request merged**
