### PR TITLE
Case 21621: Fix crash on startup

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21621/fix-crash-on-startup-in-ParseFlowDataTask

Test plan:
- you don't crash on startup

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17967/HighFidelity-Beta-PR15132-1d63647.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17967/HighFidelity-Quest-Beta-PR15132-1d63647.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17967/HighFidelity-Beta-PR15132-1d63647.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17967/HighFidelity-Beta-Interface-PR15132-1d63647.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17969/HighFidelity-Beta-PR15132-1d63647.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17969/HighFidelity-Beta-Interface-PR15132-1d63647.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17969/HighFidelity-Beta-PR15132-1d63647.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17969/HighFidelity-Quest-Beta-PR15132-1d63647.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17969/HighFidelity-Beta-PR15132-1d63647.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17969/HighFidelity-Beta-Interface-PR15132-1d63647.exe

**Pull request merged**
