### PR TITLE
RC81: Fixed Memory Corruption in AnimClip.cpp

### PR DESCRIPTION
**Pull request by amantley**
The case is here https://highfidelity.manuscript.com/f/cases/21731/Crash-Memory-Corruption-in-AnimClip-copyFromNetworkAnim

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18156/HighFidelity-Beta-PR15193-a0de6c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18156/HighFidelity-Beta-Interface-PR15193-a0de6c1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18156/HighFidelity-Beta-PR15193-a0de6c1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18156/HighFidelity-Quest-Beta-PR15193-a0de6c1.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18156/HighFidelity-Beta-PR15193-a0de6c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18156/HighFidelity-Beta-Interface-PR15193-a0de6c1.exe

**Comment by hyperlogic** [comment]
QA Test plan:
There is none, just run the app as normal.  This memory corruption happens on every avatar load.

**Pull request merged**
