### PR TITLE
Setup a higher memory limit for android build

### PR DESCRIPTION
**Pull request by gcalero**
Jenkins android build is throwing java.lang.OutOfMemoryError

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14162/HighFidelity-Beta-PR14241-a9b9f48.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14162/HighFidelity-Beta-PR14241-a9b9f48.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14162/HighFidelity-Beta-Interface-PR14241-a9b9f48.dmg

**Comment by gcalero** [comment]
build this please

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14168/HighFidelity-Beta-PR14241-a9b9f48.apk

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14171/HighFidelity-Beta-PR14241-a9b9f48.apk

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14172/HighFidelity-Beta-PR14241-a9b9f48.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14172/HighFidelity-Beta-PR14241-a9b9f48.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14172/HighFidelity-Beta-Interface-PR14241-a9b9f48.dmg

**Comment by conklin94122** [comment]
QA: If this builds successfully, confirm Android, Windows, and Mac all install and run. Quick sanity only.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14172/HighFidelity-Beta-PR14241-a9b9f48.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14172/HighFidelity-Beta-Interface-PR14241-a9b9f48.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
All platforms pass sanity check.

**Pull request merged**
