### PR TITLE
Audio meters

### PR DESCRIPTION
**Pull request by zzmp**
- Add VU meters to Audio Input Selection list

### CODE REVIEW

**Comment by zzmp** [comment]
@kencooke:
5e492dd works under the compiler (VS2013) compiled as Release.
5efdb55 has a lot of stuttering, but works when not running under the compiler. I've tried undoing small things (disabling `getLoudness`, `loudnessTimer`, and messing with the way `readyRead` is emitted), but none help. I think that just having multiple input devices open may be slowing the emission of `readyRead`, and slowing audio input to a stutter.

It's not an issue (because it works fine when not under the compiler), but if you have any insight I would like to resolve it, for the sake of future maintenance.

**Comment by zzmp** [comment]
### QA Plan

Make sure audio selection still works.
Unplug and replug your audio inputs, and make sure it still works as expected.
Unplug your active input - it should just fall off the list.
Unplug your inactive input - it should just fall off the list.
Make sure your audio input isn't stuttery (you may need to use "Echo local/server audio").
Make sure the VU (loudness) meters in the audio input selection menu reflect reality.

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1108/HighFidelity-Beta-PR10820-18d1adf2554c78b23e1f02791d1c661632f6d593.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1111/HighFidelity-Beta-PR10820-c93b8f393887d45081181a079902ae1a741ee504.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1111/HighFidelity-Beta-PR10820-c93b8f393887d45081181a079902ae1a741ee504.dmg

**Comment by kencooke** [comment]
@zzmp The failure to get clean audio when run under the debugger is a bad sign, as if the audio capture is barely real-time. Does this change open and activate all attached audio devices, all of the time? If so, I don't think that is a maintainable architecture.

**Comment by zzmp** [comment]
@kencooke yep, it changes open to activate all attached audio input devices, all of the time.

I'll spend through tomorrow going over the last commit bit-by-bit and seeing where the slow-down is (if it is in multiple open devices or not), but I don't see any other way to have VU-meters for all of the attached devices short of opening them all, at least not through Qt.

I do want to  leave it as `QA Ready`, though, and have someone else test for any other issues.

**Comment by YuppyPlays** [comment]
Make sure audio selection still works. **Pass**
Unplug and replug your audio inputs, and make sure it still works as expected. **Fail, Crashed when disabling any input,**
Unplug your active input - it should just fall off the list. **Fail, Crashed when disabling any input,**
Unplug your inactive input - it should just fall off the list. **Fail, Crashed when disabling any input,**
Make sure your audio input isn't stuttery (you may need to use "Echo local/server audio"). **Fail, the audio through the HTC Vive microphone came out distorted and deep, overall not correctly - also audio input for my Blue Yeti did not work at all, but the Vive microphone was picking up audio just fine (Tested externally from application and works perfectly, worked previously in HF also**
Make sure the VU (loudness) meters in the audio input selection menu reflect reality. **Cannot determine given the previous fails**

**Comment by kencooke** [comment]
I tested on my system. My normal input device fails to open, with this in the log:
```
[06/26 14:40:31] [DEBUG] [hifi.audioclient] defaultAudioDeviceForMode mode:  Input  [ "Analog (1+2) (RME Babyface)" ] [ "Analog (1+2) (RME Babyface)" ]
[06/26 14:40:31] [DEBUG] [hifi.audioclient] AudioInputs - device unavailable: "Analog (1+2) (RME Babyface)"
[06/26 14:40:31] [DEBUG] [hifi.audioclient] AudioInputs - see device initialization for details
```
It may be due to this being a stereo capture device (wired as dual mono). Normally AudioClient opens as stereo and downmixes to mono.

My other devices opened (and showed meters) but the audio was horribly distorted.

**Pull request closed without merging**
