### PR TITLE
Tighter version of sample sound

### PR DESCRIPTION
**Pull request by kencooke**
Starting with PR #11681, the sample sound is always in-memory but rarely used. To reduce the size from 60s to 11s, this trims to the last musical phrase, cleanly fades in/out, and removes leading silence for less latency when the button is pressed.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

- When you open the audio menu and press "Play sample sound", it should play immediately
- It should sound musically pleasing

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4471/HighFidelity-Beta-PR11698-2156729a756594cf7e504f6808338d6e7c76b995.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4471/HighFidelity-Beta-PR11698-2156729a756594cf7e504f6808338d6e7c76b995.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
When you open the audio menu and press "Play sample sound", it should play immediately
It should sound musically pleasing | Pass

All good, and sounds good.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
