### PR TITLE
Command line parsing using extras for android

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.manuscript.com/f/cases/19113/Debug-mode-Jump-to-a-domain-on-start

Testing

Ability to load and execute scripts from command line on Android.

Process

Run the app using adb with the following command:

adb shell am start -n io.highfidelity.hifiinterface/.PermissionChecker --es args "--url file:///~/serverless/tutorial.json --no-updater --no-login-suggestion --testScript quitWhenFinished --testResultsLocation /sdcard/snapshots"

watch logcat for any scripting errors.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16898/HighFidelity-Beta-PR14804-f4eeff5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16898/HighFidelity-Beta-PR14804-f4eeff5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16898/HighFidelity-Beta-Interface-PR14804-f4eeff5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16898/HighFidelity-Beta-PR14804-f4eeff5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16898/HighFidelity-Beta-Interface-PR14804-f4eeff5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16906/HighFidelity-Beta-PR14804-3c0dfcd.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16907/HighFidelity-Beta-PR14804-23b9876.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16907/HighFidelity-Beta-PR14804-23b9876.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16907/HighFidelity-Beta-Interface-PR14804-23b9876.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16907/HighFidelity-Beta-PR14804-23b9876.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16907/HighFidelity-Beta-Interface-PR14804-23b9876.exe

**Comment by NissimHadar** [comment]
Note that the URL of a script needs  to appear after --testScript.

**Pull request closed without merging**
