### PR TITLE
fix a memory leak in OctreePacketProcessor packet piggybacking

### PR DESCRIPTION
**Pull request by birarda**
- fixes a memory leak when unpacked piggybacked packets in OctreePacketProcessor

### CODE REVIEW

**Comment by birarda** [comment]
QA'ing with @sethalves who has the memory analysis tool that spotted this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b28523cb540b3091165db13fb6350b5ddb88f0a available at: https://gist.github.com/faa19ded9290bab791ae<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b28523cb540b3091165db13fb6350b5ddb88f0a available at: https://gist.github.com/faa19ded9290bab791ae<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.dmg

**Comment by sethalves** [comment]
after this change, I no longer see this memory leak.  QA pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20c923db322e351020442a5259519fc364aeb10d available at: https://gist.github.com/faa19ded9290bab791ae<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7420.dmg

**Pull request merged**
