### PR TITLE
80.0/master: Fix small miscalculation in space requirements for serialized avatar-data

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
This was causing an overrun of up to 3 bytes, which was giving an assert in the debug build of avatar mixer.

Ticket: https://highfidelity.manuscript.com/f/cases/20914/Fix-small-miscalculation-in-space-requirements-for-serialized-avatar-data

RC-79 version of this: https://github.com/highfidelity/hifi/pull/14815

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16920/HighFidelity-Beta-PR14812-08b2110.apk

**Comment by ZappoMan** [comment]
Don't we need this in 79.

**Comment by howard-stearns** [comment]
yes.

**Comment by howard-stearns** [comment]
https://highfidelity.manuscript.com/f/cases/20914/Fix-small-miscalculation-in-space-requirements-for-serialized-avatar-data

test plan is to smoke, which I will do when it builds (either by jenkins or my own machine in parallel, whichever comes first)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16920/HighFidelity-Beta-PR14812-08b2110.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16920/HighFidelity-Beta-Interface-PR14812-08b2110.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16920/HighFidelity-Beta-PR14812-08b2110.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16920/HighFidelity-Beta-Interface-PR14812-08b2110.exe

**Comment by howard-stearns** [comment]
smokes ok with both the scripts mentioned in the ticket.
master interface to PR sandbox running scripts
PR interface to PR sandbox running script
PR interface to other domains

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16944/HighFidelity-Beta-PR14812-08b2110.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16944/HighFidelity-Beta-PR14812-08b2110.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16944/HighFidelity-Beta-Interface-PR14812-08b2110.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16944/HighFidelity-Beta-PR14812-08b2110.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16944/HighFidelity-Beta-Interface-PR14812-08b2110.exe

**Pull request merged**
