### PR TITLE
FB10621 "HIFI-Commerce Login" page title change to "Log in to continue"

### PR DESCRIPTION
**Pull request by ElderOrb**
Based on https://highfidelity.fogbugz.com/f/cases/10621/

Test plan:   
Ensure title in "HIFI Commerce - Login" page changed to "Log in to continue" like here:

image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6006/app_12095_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6006/HighFidelity-Beta-PR12095-437b78dce5ae961ed1f47c3f6e6b52d4be77604d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6006/HighFidelity-Beta-PR12095-437b78dce5ae961ed1f47c3f6e6b52d4be77604d.exe

**Comment by QAadahlin** [comment]
Currently testing.

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
