### PR TITLE
5351: Help Button has Old UI

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/5351/Help-Button-has-Old-UI

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2365/HighFidelity-Beta-PR11146-836b09b83d286edf854d852f82ef0a46f3108706.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2365/HighFidelity-Beta-PR11146-836b09b83d286edf854d852f82ef0a46f3108706.exe

**Comment by anshuman64** [comment]
Test Plan:
Check to see if the help app has these new images
[Help-basic-controls-update-2.zip](https://github.com/highfidelity/hifi/files/1213274/Help-basic-controls-update-2.zip)

Check in both HMD and Desktop mode.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
-------- | -------- | --------
Check to see if the help app has these new images: `...` | Pass | Pass

All good - correct images in place on HMD and Desktop.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
