### PR TITLE
Secondary camera frame buffer / texture fixes

### PR DESCRIPTION
**Pull request by dback2**
-Ensure spectator camera frame buffer is initialized on first getResourceTexture call if it hadn't been initialized yet. This fixes issues when the mirror overlay is being created from the mirror client script it sometimes attempts to get the spectator camera network texture before the rendering thread has a chance to make the first call to textureCache->getSpectatorCameraFramebuffer in SecondaryCameraJob::run where it is currently being initialized.

-Update spectator camera network texture whenever spectator camera frame buffer is reset. This fixes issues where the resizing of secondary camera's texture width/height (changing mirror dimensions or resizing desktop viewport) causes the spectator camera frame buffer to be reset for the new aspect ratio but the mirror overlay's network texture continues to point to the original one and the mirror image no longer updates.

Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/5170

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5217/HighFidelity-Beta-PR11890-710171929559cd934d72a89b3a32a578449722b7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5224/HighFidelity-Beta-PR11890-710171929559cd934d72a89b3a32a578449722b7.dmg

**Comment by dback2** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5229/HighFidelity-Beta-PR11890-710171929559cd934d72a89b3a32a578449722b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5229/HighFidelity-Beta-PR11890-710171929559cd934d72a89b3a32a578449722b7.exe

**Comment by dback2** [comment]
@Nex-Pro this one is probably for you as you have the needed permissions for dev-content

**Comment by Nex-Pro** [comment]
Testing win10

**Comment by Nex-Pro** [comment]
### FAIL

see testrail.

https://highfidelity.testrail.net/index.php?/tests/view/18307&group_by=cases:title&group_order=desc&group_id=-1

**Comment by dback2** [comment]
Mirror script updated to fix the fail case and test plan also updated.

@Nex-Pro ready for re-test

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### Fail

Tester: Piper.Peppercorn

System information.
CPU: Intel i7 4.0 ghz.
RAM: 16gb
GPU: Nvidia GTX1070 8gb
HMD: HTC Vive.
Controllers: Vive hand controllers.
Audio: USB headset.

Testrail result.

https://highfidelity.testrail.net/index.php?/tests/view/18307&group_by=cases:title&group_order=desc&group_id=-1

@dback2  Some problems with the mirrors persist. I'm sure you can fix them.

**Comment by dback2** [comment]
@Nex-Pro Test plan step 7 clarified and ready for retest - we do not want to open the Spectator Camera after getting it from marketplace

**Comment by Nex-Pro** [comment]
Retesting

**Comment by Nex-Pro** [comment]
Further fail

https://highfidelity.testrail.net/index.php?/tests/view/21920&group_by=cases:title&group_order=desc&group_id=-1

**Comment by dback2** [comment]
@Nex-Pro Unable to repro the issue from the image you posted in the latest fail. Would it be possible to provide a video of this from load in until the issue occurs (skipping step 3)? The mirrors not having models was an already existing issue in dev-content and unrelated to this PR.

**Comment by Nex-Pro** [comment]
@dback2 will do in the morning. I saw the mirrors had been fixed when I returned to the location later.

**Comment by Nex-Pro** [comment]
### PASS
https://highfidelity.testrail.net/index.php?/tests/view/21936&group_by=cases:title&group_order=desc&group_id=-1

Worked ok this time. Maybe the broken model URL was the issue. Also tried scaling the mirror in tablet mode. The video of that will no doubt be published at some time in the future on a show most likely called. "VR the good old days."

Good fix @dback2

**Pull request merged**
