### PR TITLE
Commerce: More security images!

### PR DESCRIPTION
**Pull request by zfox23**
Commerce: Now with 34 security images!

**Test Plan:**
1. Create a new account, log in to that account, and open the Wallet app
2. Click the "Set Up Wallet" button
3. Verify that you see six random security images, none of which are duplicates
4. Click the "Back" button, then click "Set Up Wallet" again.
5. Verify that you see six new random security images (i.e. not the same set of six as in (3)), none of which are duplicates
6. Continue through the wallet setup process, ensuring that you see your selected security image throughout
7. After setting up your wallet (it doesn't matter if you're seeded or not), restart Interface
8. Open the Wallet app. Verify that you see your selected security image on the authentication page.
9. Go to the "Security" tab
10. Next to "Security Pic", click "Change"
11. Verify that you see six random security images, none of which are duplicates
12. Click "Cancel", then click "Change" next to "Security Pic" again
13. Verify that you see six new random security images (i.e. not the same set of six as in (11)), none of which are duplicates
14. Select a new security image and ensure that the new one appears throughout the Wallet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5698/app_12007_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5698/HighFidelity-Beta-PR12007-89795272c77aa379364697d2f7f1aff89690de22.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5698/HighFidelity-Beta-PR12007-89795272c77aa379364697d2f7f1aff89690de22.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Create a new account, log in to that account, and open the Wallet app | Pass
Click the "Set Up Wallet" button | Pass
Verify that you see six random security images, none of which are duplicates | Pass
Click the "Back" button, then click "Set Up Wallet" again. | Pass
Verify that you see six new random security images (i.e. not the same set of six as in (3)), none of which are duplicates | Pass
Continue through the wallet setup process, ensuring that you see your selected security image throughout | Pass
After setting up your wallet (it doesn't matter if you're seeded or not), restart Interface | Pass
Open the Wallet app. Verify that you see your selected security image on the authentication page. | Pass
Go to the "Security" tab | Pass
Next to "Security Pic", click "Change" | Pass
Verify that you see six random security images, none of which are duplicates | Pass
Click "Cancel", then click "Change" next to "Security Pic" again | Pass
Verify that you see six new random security images (i.e. not the same set of six as in (11)), none of which are duplicates | Pass
Select a new security image and ensure that the new one appears throughout the Wallet | Pass

Solid pass, as always. 👍 🎉

**Pull request merged**
