### PR TITLE
Build 39.1 Hotfix for 30 second wifi check causing an issue with Audio

### PR DESCRIPTION
**Pull request by cozza13**
Build 39.1 Hotfix for 30 second wifi check causing an issue with Audio

Ensure Audio works with wired and wifi network on PC and Mac. Set your audio to echo server loopback and make sure you do not hear bad audio

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Can test when ready.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 00fb328f2fc129d135fce6df8cb4c2ae15912096 available at: https://gist.github.com/6f318473d1fa42906a05536c5f53455c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10495-00fb328.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10495-00fb328.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing Complete:

Tested the audio over a wired PC and a wireless laptop, both when listening back and also checking the scope acted essentially the same.

Audio fed back also was working normally.

**Pass**

**Pull request merged**
