### PR TITLE
catch QString exceptions that ModelCache can throw

### PR DESCRIPTION
**Pull request by sethalves**
- catch QString exceptions that ModelCache can throw

https://highfidelity.manuscript.com/f/cases/19904/Crash-on-Object-load-View-angle-loads-item-Hifiaq-Master-Metaverse-Staging

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15274/HighFidelity-Beta-PR14434-cd177a4.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15275/HighFidelity-Beta-PR14434-26a50e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15275/HighFidelity-Beta-PR14434-26a50e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15275/HighFidelity-Beta-Interface-PR14434-26a50e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15275/HighFidelity-Beta-PR14434-26a50e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15275/HighFidelity-Beta-Interface-PR14434-26a50e1.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
