### PR TITLE
Case 18800: Change default skybox per Alan's specs

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.manuscript.com/f/cases/18800

Do Not Merge because:
- We need to determine if we should add versioning to this so as to not affect existing default skyboxes, or if we should do something different like an option somewhere that allows you to choose your default skybox setting
- Will also need review and feedback from Alan

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16329/HighFidelity-Beta-PR14673-c5f0b94.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16329/HighFidelity-Beta-PR14673-c5f0b94.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16329/HighFidelity-Beta-Interface-PR14673-c5f0b94.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16329/HighFidelity-Beta-PR14673-c5f0b94.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16329/HighFidelity-Beta-Interface-PR14673-c5f0b94.exe

**Comment by changxc** [comment]
this has been moved out of RC80 to give priority to other recent issues

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by dback2** [comment]
Removing milestone since this won't open for 81

**Comment by huffman** [comment]
Closing due to DNM

**Pull request closed without merging**
