### PR TITLE
Remove debug logging message spam for avatar entities that have scripts

### PR DESCRIPTION
**Pull request by roxanneskelly**
Remove logging messages for behaviors that are expected.

Attached entities with scripts are now being sold on the marketplace
(rWatch) and are now being worn by various users.  Because of this, it's
now common for the 'removing entity scripts' case to be hit in code for
every update, which causes debug log messages every 60 seconds for each
entity entity with a script.

Repro: Have an avatar wear rWatch.  With a second instance of interface,
turn on verbose logging while the first avatar is local.  See debug logging
60 times a second.

Fix: Given attached entities with scripts are happening, it's not an
exceptional case and should probably not be logged.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by AndrewMeadows** [comment]
Jenkins, please add to whitelist.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10799/HighFidelity-Beta-PR13392-5bc7694.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10799/HighFidelity-Beta-PR13392-5bc7694.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10799/HighFidelity-Beta-Interface-PR13392-5bc7694.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10799/HighFidelity-Beta-PR13392-5bc7694.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10799/HighFidelity-Beta-Interface-PR13392-5bc7694.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10860/HighFidelity-Beta-PR13392-5bc7694.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10860/HighFidelity-Beta-PR13392-5bc7694.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10860/HighFidelity-Beta-Interface-PR13392-5bc7694.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10860/HighFidelity-Beta-PR13392-5bc7694.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10860/HighFidelity-Beta-Interface-PR13392-5bc7694.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Logging appears as expected.

**Pull request merged**
