### PR TITLE
Prevent connection timestamp map from growing unboundedly

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
This PR converts the _lastConnectionTimes from time->event to event->time. On ACs the map can grow forever as the connection times are not considered complete.

It also changes the DomainConnectionDialog to use this format. I changed the DomainConnectionModel also but nothing appears to use it currently.

https://highfidelity.manuscript.com/f/cases/16232/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10920/HighFidelity-Beta-PR13477-c60ed13.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10920/HighFidelity-Beta-Interface-PR13477-c60ed13.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10920/HighFidelity-Beta-PR13477-c60ed13.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10920/HighFidelity-Beta-Interface-PR13477-c60ed13.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10930/HighFidelity-Beta-PR13477-2736ba5.apk

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
In an development build of interface:
1. Ensure developer menus are enabled under Settings
2. Enter a domain
3. Go to Developer->Network->Show Domain Connection Timing

Before & after this PR a popup table showing the events that comprise a domain connect, including columns for timestamp, delta and time elapsed.

For release builds and other components there should be no change in behaviour.

**Comment by SimonWalton-HiFi** [comment]
Note that it should be impossible for the map to now grow with bound as the key is now a small enum type.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10948/HighFidelity-Beta-PR13477-30a62d8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10948/HighFidelity-Beta-PR13477-30a62d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10948/HighFidelity-Beta-Interface-PR13477-30a62d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10948/HighFidelity-Beta-PR13477-30a62d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10948/HighFidelity-Beta-Interface-PR13477-30a62d8.exe

**Comment by birarda** [comment]
The connection times functionality is sparingly used AFAIK, and probably only by me. Changes here are pretty low risk.

I'm worried though that we'll lose functionality by making this change. In the current setup, it's possible to see the timestamp for multiple iterations of the same step (ex sending multiple check in packets during connection). With the `std::map` keyed on event->time won't we lose that?

**Comment by SimonWalton-HiFi** [comment]
Yes, with this change you would lose the multiple timestamps, although nothing currently uses that..

It's not a major leak - 40 bytes maybe three times per second.

**Comment by birarda** [comment]
Closing this in favour of an approach that keeps the multiple timestamps per step. We'll disable this functionality on the AC to remove the leak.

**Pull request closed without merging**
