### PR TITLE
Prevent dragging and dropping files onto Create windows

### PR DESCRIPTION
**Pull request by dback2**
Addresses: https://highfidelity.manuscript.com/f/cases/19084

Pre-Merge Test Plan:
1. Enter Interface in desktop mode into any domain
2. Open Create and verify that any file from file explorer being dragged onto either the Entity List or Entity Properties window shows a forbidden slash icon like below before releasing and does nothing once released
hashicon
3. Verify step 2 on all tabs of the Entity Properties window
4. Verify step 2 on both PC and Mac (on Mac it is expected that there is no icon indicating you can't do that before releasing it)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15290/HighFidelity-Beta-PR14441-a94fec7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15290/HighFidelity-Beta-PR14441-a94fec7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15290/HighFidelity-Beta-Interface-PR14441-a94fec7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15290/HighFidelity-Beta-PR14441-a94fec7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15290/HighFidelity-Beta-Interface-PR14441-a94fec7.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15740/HighFidelity-Beta-PR14441-a94fec7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15740/HighFidelity-Beta-PR14441-a94fec7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15740/HighFidelity-Beta-Interface-PR14441-a94fec7.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15740/HighFidelity-Beta-PR14441-a94fec7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15740/HighFidelity-Beta-Interface-PR14441-a94fec7.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Fail

On PC user is still able to drag files onto the Entity List
[Archive.zip](https://github.com/highfidelity/hifi/files/2655041/Archive.zip)


On Mac user is not able to drag files onto the create windows

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15776/HighFidelity-Beta-PR14441-1a3708c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15776/HighFidelity-Beta-Interface-PR14441-1a3708c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15776/HighFidelity-Beta-PR14441-1a3708c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15776/HighFidelity-Beta-Interface-PR14441-1a3708c.exe

**Comment by QliCknox** [comment]
Fail 

[Archive.zip](https://github.com/highfidelity/hifi/files/2657904/Archive.zip)
There is no "Can not do that" cursor icon on Mac

**Comment by dback2** [comment]
@QliCknox Test plan edited to note that Mac is expected to not have a "can't do that" icon like the forbidden slash icon on PC before releasing

**Comment by QliCknox** [comment]
Pass

With the expected result for Mac being updated, this PR works as expected

**Pull request merged**
