### PR TITLE
Make stopwatch buttons work properly

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Host \HiFi\unpublishedScripts\marketplace\stopwatch\ content, including subdirectories, on a Web server.
- In a domain you have permissions in (e.g., local Sandbox) run spawnStopwatch.js from the Web server.
- A stop watch should rez in front if you, facing you.
- Click on the start/stop button at the top to start/stop timing. 
	- Start makes the hands start moving from their current position.
	- Stop makes the hands stop moving and remain in their current position.
- Click on the reset button beside the start/stop button to reset.
	- If timing was under way, timing is stopped.
	- The hands reset to their zero positions.
- The hands should rotate around the dial.
- Create a second stopwatch. Check that buttons affect only appropriate stopwatch.

**Comment by CainFoool** [comment]
Will test.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/192/HighFidelity-Beta-PR10555-8a659955ccc314778afd064bd01fa1d4baf136fe.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/192/HighFidelity-Beta-PR10555-8a659955ccc314778afd064bd01fa1d4baf136fe.dmg

**Comment by CainFoool** [comment]
# Test Passed 

I was having an issue unrelated to this PR. The clocks move around and act accordingly, each function being separated from each.

**Comment by ctrlaltdavid** [comment]
Doesn't work in HMD.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/221/HighFidelity-Beta-PR10555-019e92b2a348e61d9286e355cf3863dbfa067b85.exe

**Comment by CainFoool** [comment]
Retesting with HMD.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/221/HighFidelity-Beta-PR10555-019e92b2a348e61d9286e355cf3863dbfa067b85.dmg

**Comment by CainFoool** [comment]
# Test Passed 

Stopwatch, incl multiple stopwatches now work in HMD as expected.

**Pull request merged**
