### PR TITLE
Fix equirectangular skybox loading

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/12010

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5706/app_12011_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5706/HighFidelity-Beta-PR12011-ee3c47d5eca3f008cf67693be5dfe092bb7b0600.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5711/app_12011_PR.apk

**Comment by cain-kilgore** [comment]
@SamGondelman Will a pass on #12010 be a pass here too? Or will this need tested individually?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5711/HighFidelity-Beta-PR12011-ee3c47d5eca3f008cf67693be5dfe092bb7b0600.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5711/HighFidelity-Beta-PR12011-ee3c47d5eca3f008cf67693be5dfe092bb7b0600.dmg

**Comment by SamGondelman** [comment]
@cain-kilgore I think @conklin94122 likes to have them tested again, so if you could take a look that would be great 😃

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Find an equirectangular skybox image (easy to google, aspect ratio should be 2x1). Create a zone and set the image as the background. It should load properly. | 👍 
Clear your KTX Cache (Developer -> Render -> Clear KTX Cache). Restart Interface.| 👍 
The image should still appear properly.| 👍 

Looks good on this build too!

**Pull request merged**
