### PR TITLE
Spectator Camera - Mergeable Rendering Components

### PR DESCRIPTION
**Pull request by zfox23**
Introduces some core plumbing that allows for a second, independent rendering pass (camera, mirror, etc.)

The reason for merging this now is make sure that the code doesn't become obsolete as we temporarily shift our work. It _does not_ include any of the JavaScript or QML application code. It is mostly dedicated to rendering changes that should not change the normal operation of Interface.

**Test Plan:**
- Run through the standard rendering acceptance and performance tests. 
 -- In particular, make sure to exercise shadows and ambient occlusion (e.g., from Developer -> Graphics).
 -- The performance (e.g., show stats and look at Engine, Batch, and GPU times) should be basically the same with and without this.
- There isn't enough here to actually run the spectator camera, but you can test the effect on rendering performance by evaluating this in a javascript console: Render.getConfig("SecondaryCameraFrame").enabled = Render.getConfig("BeginSecondaryCamera").enabled = true;. You should find that the Engine, Batch, and GPU times are nearly doubled when you do this.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/847/HighFidelity-Beta-PR10739-5245237bb264012cf79ffe3903bd4218c5ef5f67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/847/HighFidelity-Beta-PR10739-5245237bb264012cf79ffe3903bd4218c5ef5f67.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Testing Shadows, ambient occlusion within performance tests**

I could not seem to get ambient occlusion to show up in graphics, it just had "None" within it's box and had no other available options.

NoShadows/NoOcclusion:
noshadow
Shadows/NoOcclusion:
shadow

**Evaluating the secondary camera**
As soon as I entered the command to enable it with "true;" it crashed, sent report with info regarding this.

**Fail**

Please let me know of anything else I can do to assist.

**Comment by howard-stearns** [comment]
@YuppyPlays - Interesting find about problems enabling the render.  It looks like maybe you enabled one config but not the other? 

The priority for this is whether it works without being enabled, and works when enabled correctly, as opposed to whether or not the api is safe for misuse. With that in mind please cut the following, all on one line, exactly as is. (It will look like two lines in your browser, but if you highlight with one continuous motion and ctrl-c, it will capture it all on one line, and that's that way it should appear when pasted into console.)

Render.getConfig("BeginSecondaryCamera").enabled = Render.getConfig("SecondaryCameraFrame").enabled = false

When you do that, does it work as described?

Also, you are correct about there being no "enabled" option for Ambient Occlusion in the Developer->Graphics dialog. That's fine.

**Comment by YuppyPlays** [comment]
@zfox23 thank you for explaining, apologies for my error there, I keep accidentally thinking it's one line per, my bad. :)

image

image


I believe this is how it should work, output brings our true/false

**False**
image

**True**
image

**Pass**?

**Comment by zfox23** [comment]
@YuppyPlays that looks like a PASS to me :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/862/HighFidelity-Beta-PR10739-2e215e6544a9ac82174487fab4385980c8d63e25.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/862/HighFidelity-Beta-PR10739-2e215e6544a9ac82174487fab4385980c8d63e25.dmg

**Comment by samcake** [comment]
As a test plan, please make sure that enabling disabling the graphics settings (ambient Occlusion and shadows) is working and is persistent across several sessions (stays enabled from one session to the next...)

**Comment by howard-stearns** [comment]
@samcake - There doesn't seem to be any options under Developer -> Graphics... -> Ambient Occlusion. Just "None". (With or without this PR.)

Meanwhile, I can confirm that shadows works and is persistent across sessions -- regardless of which rendering pass is enabled when shadows are toggled.

**Pull request merged**
