### PR TITLE
Remove unused HFMetaEvents

### PR DESCRIPTION
**Pull request by SamGondelman**
In the process of improving the tablet interaction, we're trying to clean up some Qt events and unnecessary signals so the Qt event queue doesn't fill up.  HFMetaEvents don't look like they are being used anymore, so they're a good first candidate for removal.

Test Plan:
- There shouldn't be any real functional change.  Just make sure you can still click on QML windows, and that spacebar and escape still work everywhere you'd expect them to.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Awaiting Win build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4067/HighFidelity-Beta-PR11576-403b18977b4b301f11e87ffb850b06c630878253.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4067/HighFidelity-Beta-PR11576-403b18977b4b301f11e87ffb850b06c630878253.exe

**Comment by Nex-Pro** [comment]
Rolling up sleeves

**Comment by Nex-Pro** [comment]
### PASS
All good.

**Pull request merged**
