### PR TITLE
Changed user agent for new one and attempt to fix busy indicator [DNM]

### PR DESCRIPTION
**Pull request by vladest**
…bility

https://highfidelity.manuscript.com/f/cases/13791/Please-fill-out-this-field-error-message-is-offset-on-password-username-recovery-webview

Test plan:
- Open web browser with Ctrl/Command-B
- Goto https://highfidelity.com -> Login -> forgot password
- Press "Send me reset password instructions".
- Make sure popup "Please fill out this field" points on email input field

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8524/HighFidelity-Beta-PR12795-1e369c482d6857a63a6bf726c809e21d9abf9b50.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8524/HighFidelity-Beta-PR12795-1e369c482d6857a63a6bf726c809e21d9abf9b50.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8622/HighFidelity-Beta-PR12795-c5e3d66bad2c5278e6043ca12a6255a3011abbc7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8622/HighFidelity-Beta-PR12795-c5e3d66bad2c5278e6043ca12a6255a3011abbc7.exe

**Comment by ZappoMan** [comment]
closed - super old

**Pull request closed without merging**
