### PR TITLE
Beta Release 25 - Includes up to Developer Release 5622

### PR DESCRIPTION
**Pull request by cozza13**
- Changes to texture loading rules
- Improve domain check
  - Simply tester questions 
  - Include crowd summoning, with control over number and number making noise
- Dk/agent avatar audio artifacts
- Fix shutdown order of qml/audio
- Fix potential race in NodeList
- Add a timer to Socket to check for readyRead backup
- Disable OpenVR submit thread when async reprojection is enabled
- Fix for crash in openvr on startup
- Fix the timing of the launchedFromSteam property
- Add a menu item to run audio stats script
- Fix race condition in BatchLoader
- Add getter for SteamVR's buildID to SteamClient
- Fix away.js vulnerability
- Update help image for gamepad to include grab and click lasers
- When vive is on i5 report a correct target frame rate so we can see that in metaverse stats
- Disable console splash screen
- Fix agent audio underflow
- Clean audio mixer
- Display warning overlay instead of scene when below min spec
- Fix for crash in QtWebEngineCore when rapidly switching domains
- Updates for min spec check for Steam
- Debug last sequence number and socket when readyRead is stuck
- Revise loading progress bar
- Fix for weird avatar when switch Vive -> Desktop mode
- Updating min spec overlay image
- Update being of light model
- Exit Sandbox instead of asking to quit
- Fix race condition in BatchLoader
- Add tutorial tracking for going through the welcome portal

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95c175ae74518968bb54b8f91729da1595f4e27c available at: https://gist.github.com/b401a1d966751796e679440dca9e1612<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8959-95c175a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8959-95c175a.dmg

**Comment by Nex-Pro** [comment]
### PR #8959 Beta Release 25

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

On startup had to restart vive which crashed interface no bugsplat was raised.
Selecting objects with right hand controller seemed less reliable than with the left.
Observed several issues not previously noted with existing and recently added content ( not related to this PR )
Will make necessary reports.
Large particles rotate with HMD roll in forward axis. This has been observed independently by several HMD users. Bug report filed.
Not specific to this PR but content fix for tutorial content filed #2142.


## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: UNTESTED
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: PARTIAL SUCCESS unrestrained frame rates on switching to desktop otherwise all good.

**Additional Test Results + Observations**:
I was unable to edit an objects user data whilst in HMD as no keyboard is presented. Bug report filed #2141.
See additional domain stats for unrestrained frame rate issue on switching to desktop mode.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |89 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |78 |90
**CPU Buffer Count**: |1994 |3934 |3963
**GPU Buffer Count**: |739 |1078 |1247
**CPU Memory Usage**: |23494656 |64503808 |74698752
**GPU Memory Usage**: |13312000 |36196352 |50298880
**CPU Texture Count**: |206 |283 |319
**GPU Texture Count**: |186 |211 |318
**GPU Transfer Count**: |0 |2 |0
**CPU Texture Memory Usage**: |34031752 |524765776 |30598488
**GPU Texture Memory Usage**: |1018456526 |1853091700 |1709578641
**GPU Virtual Memory Usage**: |1013617640|2115737996|1698235303
**Triangle Count**: |456499 |2764690 |307457
**Triangle Rate**: |41499909 |251335454 |30745700
**API Drawcall Count**: |203 |396 |93
**Drawcall Count**: |4741 |862 |170
**Drawcall Rate**: |431000 |78363 |17000
**State Changes Texture Count**:|366 |397 |153
**Pipeline Count**: |67 |41 |43
**Item Opaques**: |237 |532 |76
**Item Translucents**: |72 |42 |25
**Item Lights**: |16 |89 |6
**Timing Opaques**: |0.704 |1.57 |0.319
**Timing Translucents**: |0.125 |0.106 |0.091
**Timing Lighting**: |0.059 |0.186 |0.214
**Render Frame**: |1.493 |3.274 |1.626

### Switching to desktop had the following results.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |352 |260 |466
**Present Rate**: |358 |258 |479
**Present New Rate**: |198 |194 |194
**CPU Buffer Count**: |2428 |4485 |3659
**GPU Buffer Count**: |839 |1206 |1121
**CPU Memory Usage**: |44937216 |79859712 |62500864
**GPU Memory Usage**: |29257728 |46018560 |38969344
**CPU Texture Count**: |204 |348 |285
**GPU Texture Count**: |179 |274 |277
**GPU Transfer Count**: |0 |2 |0
**CPU Texture Memory Usage**: |51905656 |679630160 |24044888
**GPU Texture Memory Usage**: |710448840 |1798498556 |1392354874
**GPU Virtual Memory Usage**: |705664569|2323222806|1382398747
**Triangle Count**: |193915 |635611 |193681
**Triangle Rate**: |38783000 |63561100 |48420250
**API Drawcall Count**: |189 |122 |155
**Drawcall Count**: |2450 |122 |155
**Drawcall Rate**: |490000 |12200 |38750
**State Changes Texture Count**:|355 |152 |265
**Pipeline Count**: |75 |38 |52
**Item Opaques**: |243 |154 |77
**Item Translucents**: |89 |18 |26
**Item Lights**: |16 |25 |2
**Timing Opaques**: |1 |0.562 |0.306
**Timing Translucents**: |0.264 |0.039 |0.116
**Timing Lighting**: |0.259 |0.222 |0.339
**Render Frame**: |3.092 |2.323 |2.562

This behaviour is consistent with that observed in recent builds.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|
**Test 2**|Install a fresh copy of "Home' and do tutorial|success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|success
**Test 4**|Launch firework, on dev-playa, can other hear?|untested
**Test 5**|Switch avatar and make sure it does not crash|success
**Test 6**|Test group functions|untested
**Test 7**|Retest the kick function|untested
**Test 8**|Enrure that you can distance grab|success
**Test 9**|Bring up and edit an objects with hand controllers|success i think.
This is actually unclear. Is it edit an object or an attribute such as user data of an object.
**Test 11**||blank prompt

### This content could/should be set to invisible or removed after tutorial.
hifi-snap-by-piper-peppercorn-on-2016-10-29_12-39-32

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Retest the kick function|Pass
**Test 8**|Enrure that you can distance grab|Not tested
**Test 9**|Bring up and edit an objects with hand controllers|Not tested

1600x900 Maximized window - vsync locked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2555 |4558 |3905
**GPU Buffer Count**: |858 |1502 |1073
**CPU Memory Usage**: |38051840 |83935232 |82485248
**GPU Memory Usage**: |18440192 |51277824 |47288320
**CPU Texture Count**: |230 |298 |298
**GPU Texture Count**: |200 |259 |278
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |86944944 |161811728 |79428880
**GPU Texture Memory Usage**: |602995661 |1130253503 |1109537459
**GPU Virtual Memory Usage**: |602995661|1130253503|1109537459
**Triangle Count**: |251798 |905432 |383472
**Triangle Rate**: |15737375 |56589500 |23967000
**API Drawcall Count**: |220 |335 |236
**Drawcall Count**: |5804 |378 |2052
**Drawcall Rate**: |362750 |23625 |128250
**State Changes Texture Count**:|409 |342 |359
**Pipeline Count**: |101 |38 |72
**Item Opaques**: |261 |476 |224
**Item Translucents**: |91 |58 |42
**Item Lights**: |16 |83 |14
**Timing Opaques**: |1.052 |1.477 |0.829
**Timing Translucents**: |0.208 |0.091 |0.125
**Timing Lighting**: |0.129 |0.111 |0.207
**Render Frame**: |2.412 |2.754 |2.367

1600x900 Maximized Window - vsync unlocked

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |336 |190 |335
**Present Rate**: |338 |191 |335
**Present New Rate**: |254 |150 |253
**CPU Buffer Count**: |1736 |3944 |3998
**GPU Buffer Count**: |649 |1339 |1106
**CPU Memory Usage**: |15892480 |63995904 |79253504
**GPU Memory Usage**: |10493952 |43638784 |38346752
**CPU Texture Count**: |218 |296 |297
**GPU Texture Count**: |186 |253 |272
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |101362032 |166070736 |88930768
**GPU Texture Memory Usage**: |566384284 |1124487620 |1096781074
**GPU Virtual Memory Usage**: |566384284|1124487620|1096781074
**Triangle Count**: |405124 |900280 |615626
**Triangle Rate**: |135041333 |225070000 |123125200
**API Drawcall Count**: |294 |322 |369
**Drawcall Count**: |3107 |365 |2187
**Drawcall Rate**: |1035666 |91250 |437400
**State Changes Texture Count**:|547 |325 |505
**Pipeline Count**: |64 |40 |98
**Item Opaques**: |260 |462 |220
**Item Translucents**: |61 |50 |41
**Item Lights**: |15 |82 |15
**Timing Opaques**: |0.977 |1.362 |0.678
**Timing Translucents**: |0.173 |0.062 |0.112
**Timing Lighting**: |0.063 |0.17 |0.14
**Render Frame**: |1.952 |2.985 |1.727

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |2578 |4570 |3927
**GPU Buffer Count**: |921 |1506 |1193
**CPU Memory Usage**: |38121472 |83963904 |82477056
**GPU Memory Usage**: |27537408 |48193536 |56614912
**CPU Texture Count**: |230 |297 |297
**GPU Texture Count**: |210 |250 |291
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |34843824 |182062352 |61934864
**GPU Texture Memory Usage**: |844631938 |1274022710 |1303632895
**GPU Virtual Memory Usage**: |844631938|1274022710|1303632895
**Triangle Count**: |520716 |2676800 |837317
**Triangle Rate**: |40055076 |205907692 |59808357
**API Drawcall Count**: |205 |410 |235
**Drawcall Count**: |10602 |881 |2246
**Drawcall Rate**: |815538 |67769 |160428
**State Changes Texture Count**:|372 |386 |325
**Pipeline Count**: |100 |48 |56
**Item Opaques**: |245 |506 |241
**Item Translucents**: |109 |65 |44
**Item Lights**: |16 |87 |16
**Timing Opaques**: |0.818 |1.766 |0.792
**Timing Translucents**: |0.232 |0.092 |0.142
**Timing Lighting**: |0.284 |0.201 |0.41
**Render Frame**: |2.497 |3.779 |2.608

CPU use comparison to RC24 (5585).  This PR, red trace -- RC24, blue trace.

5585vs8959r5

Memory leak checks - multiple domains visited, interrupted scene loads, cold cache loads etc etc.

8959mem

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Works all as expected

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** FAILURE
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |55 |60 |60
**CPU Buffer Count**: |1758 |1410 |1486
**GPU Buffer Count**: |613 |476 |330
**CPU Memory Usage**: |17154048 |23592960 |21700608
**GPU Memory Usage**: |11345920 |15962112 |13553664
**CPU Texture Count**: |219 |100 |193
**GPU Texture Count**: |182 |78 |124
**GPU Transfer Count**: |0 |5 |13
**CPU Texture Memory Usage**: |107325808 |122489296 |334113232
**GPU Texture Memory Usage**: |613209377 |266031030 |267669685
**GPU Virtual Memory Usage**: |599850451|365405299|455342911
**Triangle Count**: |244897 |356116 |306060
**Triangle Rate**: |15306062 |25436857 |19128750
**API Drawcall Count**: |185 |156 |149
**Drawcall Count**: |3003 |153 |149
**Drawcall Rate**: |187687 |10928 |9312
**State Changes Texture Count**:|343 |234 |292
**Pipeline Count**: |55 |40 |81
**Item Opaques**: |262 |267 |132
**Item Translucents**: |65 |118 |67
**Item Lights**: |16 |79 |16
**Timing Opaques**: |1.042 |0.942 |0.433
**Timing Translucents**: |0.188 |0.424 |0.256
**Timing Lighting**: |0.097 |0.123 |0.089
**Render Frame**: |2.079 |2.764 |1.523


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|N/A
**Test 7**|Retest the kick function|N/A
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Hydra menus work however unable to close UI by clicking the X with Hydra unresponsive

**Pull request merged**
