### PR TITLE
Use AnimationCache for models

### PR DESCRIPTION
**Pull request by zzmp**
Migrates models to use the AnimationCache, instead of a static map that was in use to load all models. This reduces the memory use of AnimationCache, especially when lots of animations are loaded.

### CODE REVIEW

**Comment by zzmp** [comment]
See: https://app.asana.com/0/74051501495175/112486925085462.

#### Testing

After #7661 lands, you can use cacheStats.js to test this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a153396318d226e293c70d3c26465c5a66b3baf available at: https://gist.github.com/31f92958d66ac5ee79fb8aa0f4650f47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7662.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7662.dmg

**Comment by zzmp** [comment]
Waiting to mark `QA Ready` until #7661 lands, as it should be used for testing.

**Comment by ZappoMan** [comment]
#7661 is now merged, so @zzmp you can update this PR so it's QA ready

**Comment by hifi-gustavo** [comment]
Build console output for commit: e80898f0950a5f75b0d2a63aeb459b9fd4ff2ac5 available at: https://gist.github.com/31f92958d66ac5ee79fb8aa0f4650f47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7662.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7662.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - I don't have access to demo so I looked at playa - I saw things that move there move as they do in production.  I saw my animation count increase and my cache counts increase.  After setting RAM cache to 0 I saw cached drop to 0 and size drop to 0.

You can also see animations cached counts vary from login as you move AV and it invokes additional animations for it.

Loaded a ancient model with animation and changed it - It seemed to work in that it animated and changed animation.

Also looked at cellscience - it seems fine as well.

I admit to groping in the dark a bit with this one, but, it seems a QA Pass based on test methods  outlined.

**Pull request merged**
