### PR TITLE
Fix AC recording playback audio encoding

### PR DESCRIPTION
**Pull request by thoys**
Fixes the audio encoding of a scripted agent that plays back a recording.

## QA Test
- Run the Sandbox of this PR
- Make the recording using Interface
   1. Use the `developer/utilities/record/recorder.js` script to make a simple recording while the microphone is  not muted. 
   2. Save the file to disk
- Run the scripted agent:
    1. Go to your local `Create JS Assignment` page (http://localhost:40100/assignment/# )
    2. Copy paste the contents of the following script in the page: 
https://raw.githubusercontent.com/highfidelity/hifi/d83600a22ee1579b15acf742e2fa83a84ce9951c/script-archive/acScripts/PlayRecordingOnAC.js
    3. Replace `http://your.recording.url` with the `file:///` path  of your recording (e.g. `file:///C:/Users/Thijs/Desktop/testThisOnAC.hfr`)
    4. Leave the `Pool` field empty and set `# of Instances` to `1` and press the Run button
- Go back into Interface and verify that you can hear the audio of the recording playing.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cdc0f3ddd2495d5e27599a6f4c4fd58c56cb92a4 available at: https://gist.github.com/f98562eeeefb2999edb9388ac3896abf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9527-cdc0f3d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9527-cdc0f3d.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
#### FAIL due to garbled audio.

Observed by and confirmed with @thoys

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2da1e3dc125b7d9cb077df8b59a0eff5f0d836d available at: https://gist.github.com/f98562eeeefb2999edb9388ac3896abf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9527-a2da1e3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9527-a2da1e3.dmg

**Comment by thoys** [comment]
@Nex-Pro Can you please test it again with the new installer? I have tested it on my other machine and it works well for me. Thanks

**Comment by Nex-Pro** [comment]
Checking this out. ( not in a git sense )

**Comment by Nex-Pro** [comment]
### PASS

Successfully recorded avatar motion and voice and replayed with clear audio.

**Pull request merged**
