### PR TITLE
add a global toggle for restricted users

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
This incorporates changes from #4919 so it would be helpful to have that merged first.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6306b69ec84497cfc2313f6f307686ac204ac561 available at: https://gist.github.com/317e410aee4d681761c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4475ca46430dae06bef2398de288d92969a47132 available at: https://gist.github.com/317e410aee4d681761c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 427e2e7dbf305b52c02df273de4657dda35fd75c available at: https://gist.github.com/317e410aee4d681761c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4921.dmg

**Pull request merged**
