### PR TITLE
RC78: Case 20411: Fix crash on subsequent entitlements checks

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/14728

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16522/HighFidelity-Beta-PR14729-d8e5898.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16522/HighFidelity-Beta-PR14729-d8e5898.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16522/HighFidelity-Beta-Interface-PR14729-d8e5898.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16522/HighFidelity-Beta-PR14729-d8e5898.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16522/HighFidelity-Beta-Interface-PR14729-d8e5898.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
