### PR TITLE
Tooltip / Cursor logic in ApplicationOverlay

### PR DESCRIPTION
**Pull request by jherico**
This is in support for  the clickable portal feature.  It allows the application overlay code to alter the tooltip whenever the cursor is hovering over an item that contains an href property.  Additionally, it has supporting logic for enabling a tooltip to be displayed after a short interval, but currently there is no tooltip UI implemented yet.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 73f25945b7d5e666ca4df0c5ecd08493a33426fb available at: https://gist.github.com/db747da54664ba04c2c9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4f6d87bf451b2b8466b51c0fd4cf72b34f1ba2b7 available at: https://gist.github.com/db747da54664ba04c2c9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 82b690de016cec3f97533baeb890d440e82b6f5a available at: https://gist.github.com/db747da54664ba04c2c9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5112.dmg

**Comment by jherico** [comment]
Closing and integrating with other overlay changes

**Pull request closed without merging**
