### PR TITLE
Change window title

### PR DESCRIPTION
**Pull request by simon-walton**
Change the title of the top-level window to "Modified Window Title"
as simple demo of pull request for hifi.

NB: Not for actual pull into highfidelity!

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by birarda** [comment]
build this please

**Comment by birarda** [comment]
@simon-walton Going to close this PR since it was just for build proof. Thanks!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6601/app_12256_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6601/HighFidelity-Beta-PR12256-0350d24a92cd944bc0b65780d38c4678613e19bc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6601/HighFidelity-Beta-PR12256-0350d24a92cd944bc0b65780d38c4678613e19bc.exe

**Pull request closed without merging**
