### PR TITLE
On Linux, remove quazip5 dynamic libs

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22660/HighFidelity-Beta-PR16527-a2c5295.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22660/HighFidelity-Quest-Beta-PR16527-a2c5295.apk)

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22662/HighFidelity-Beta-PR16527-a2c5295.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22662/HighFidelity-Quest-Beta-PR16527-a2c5295.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22662/HighFidelity-Beta-PR16527-a2c5295.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22662/HighFidelity-Beta-Interface-PR16527-a2c5295.dmg

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22664/HighFidelity-Beta-PR16527-a2c5295.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22664/HighFidelity-Quest-Beta-PR16527-a2c5295.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22664/HighFidelity-Beta-PR16527-a2c5295.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22664/HighFidelity-Beta-Interface-PR16527-a2c5295.dmg

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22665/HighFidelity-Beta-PR16527-a2c5295.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22665/HighFidelity-Quest-Beta-PR16527-a2c5295.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22665/HighFidelity-Beta-PR16527-a2c5295.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22665/HighFidelity-Beta-Interface-PR16527-a2c5295.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22665/HighFidelity-Beta-PR16527-a2c5295.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22665/HighFidelity-Beta-Interface-PR16527-a2c5295.exe

**Pull request merged**
