### PR TITLE
Build libplugins_libhifiCodec.so

### PR DESCRIPTION
**Pull request by gcalero**
Fix for crash when entering a domain in android ([MS19157](https://highfidelity.manuscript.com/f/cases/19157))

**Test plan**
1. Connecting to any domain that uses 'hifiAC' as audio codec shouldn't crash
2. Check that hifiAC codec is still selected in android
3. Check hifiAC codec still works in desktop

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13695/HighFidelity-Beta-PR14154-1719f4a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13695/HighFidelity-Beta-PR14154-1719f4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13695/HighFidelity-Beta-Interface-PR14154-1719f4a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13695/HighFidelity-Beta-PR14154-1719f4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13695/HighFidelity-Beta-Interface-PR14154-1719f4a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13696/HighFidelity-Beta-PR14154-4228524.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by amerhifi** [comment]
Tested on Android, no crash. able to open a domain without issues

**Comment by divyaelango88** [comment]
@amerhifi it looks like you need to also approve it. There needs to be 3 Checks for merge

**Pull request merged**
