### PR TITLE
Fix crash when closing the Audio menu

### PR DESCRIPTION
**Pull request by kencooke**
On some machines, checkPeakValues() takes long enough that timer callbacks overlap and activeClients gets clobbered while in use.

Fixes https://highfidelity.manuscript.com/f/cases/11310/crash-in-interface-AudioClient-checkPeakValues

Replaces PR #12568

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

If possible, this should be tested by someone who experienced crashes when closing the Audio tab.

On Windows, using Interface from this PR,
 - Open the Audio tab, verify the input level meters (to the right of each input device) update as before.
 - Open and close the Audio tab many times, and verify that Interface does not crash.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7826/app_12586_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7826/HighFidelity-Beta-PR12586-91b7acec1f150023b088f2cbfa69eb1750114651.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7826/HighFidelity-Beta-PR12586-91b7acec1f150023b088f2cbfa69eb1750114651.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Audio tab now opens and closes without crashing the interface.

**Pull request merged**
