### PR TITLE
case 21357: Mute setting and warning

### PR DESCRIPTION
**Pull request by sethalves**
- auto-mute on startup if muted on shutdown.
- show "Muted" warning if the mic is picking up sound while interface is muted
- add a way to disable the warning in audio panel
- add a button in audio panel to enable audio loopback from server

https://highfidelity.manuscript.com/f/cases/21357/persistent-mute-mute-warning-audio-loopback-button

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17396/HighFidelity-Beta-PR14956-afde793.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17396/HighFidelity-Beta-PR14956-afde793.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17396/HighFidelity-Beta-Interface-PR14956-afde793.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17396/HighFidelity-Beta-PR14956-afde793.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17396/HighFidelity-Beta-Interface-PR14956-afde793.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17464/HighFidelity-Beta-PR14956-ea92f0d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17464/HighFidelity-Beta-PR14956-ea92f0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17464/HighFidelity-Beta-Interface-PR14956-ea92f0d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17464/HighFidelity-Beta-PR14956-ea92f0d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17464/HighFidelity-Beta-Interface-PR14956-ea92f0d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17493/HighFidelity-Beta-PR14956-88a7c35.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17493/HighFidelity-Beta-PR14956-88a7c35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17493/HighFidelity-Beta-Interface-PR14956-88a7c35.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17493/HighFidelity-Beta-PR14956-88a7c35.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17493/HighFidelity-Beta-Interface-PR14956-88a7c35.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17513/HighFidelity-Beta-PR14956-bb42e49.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17513/HighFidelity-Beta-PR14956-bb42e49.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17513/HighFidelity-Beta-Interface-PR14956-bb42e49.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17513/HighFidelity-Beta-PR14956-bb42e49.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17513/HighFidelity-Beta-Interface-PR14956-bb42e49.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17557/HighFidelity-Beta-PR14956-ed15001.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17557/HighFidelity-Beta-PR14956-ed15001.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17557/HighFidelity-Beta-Interface-PR14956-ed15001.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17557/HighFidelity-Beta-PR14956-ed15001.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17557/HighFidelity-Beta-Interface-PR14956-ed15001.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17639/HighFidelity-Beta-PR14956-cbdc3bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17639/HighFidelity-Beta-Interface-PR14956-cbdc3bc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17639/HighFidelity-Beta-PR14956-cbdc3bc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17639/HighFidelity-Quest-Beta-PR14956-cbdc3bc.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17639/HighFidelity-Beta-PR14956-cbdc3bc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17639/HighFidelity-Beta-Interface-PR14956-cbdc3bc.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17887/HighFidelity-Beta-PR14956-51050dc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17887/HighFidelity-Quest-Beta-PR14956-51050dc.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17887/HighFidelity-Beta-PR14956-51050dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17887/HighFidelity-Beta-Interface-PR14956-51050dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17887/HighFidelity-Beta-PR14956-51050dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17887/HighFidelity-Beta-Interface-PR14956-51050dc.exe

**Comment by sethalves** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/15098/files and https://github.com/highfidelity/hifi/pull/15097

**Pull request closed without merging**
