### PR TITLE
Insure visibility is set upon starting users.js

### PR DESCRIPTION
**Pull request by davidkelly**
See [bug 1512](https://highfidelity.fogbugz.com/f/cases/edit/1512/Inconsistency-between-User-js-visible-to-and-API-value).  Each instance of interface stores your visibility to others locally.  So, if you login on multiple interface clients (different installs on same machine, or different machines entirely), you could set them to different values (`everyone`, `friends`, `none`).  The issue was that the script didn't _set_ that visibility at startup.  So, you set it to `none` on one client and stop.  Then on another, it could have last been set to `everyone`.  You start that client, it _says_ `everyone`, but you are still visible to nobody.  

Simple fix:  just set it when you startup.  Then, whatever the script says is correct.  Since there is no simple api to read the current visibility, this seems to be the best way to make this consistent.

### CODE REVIEW

**Comment by davidkelly** [comment]
# Test Plan
You need 2 accounts.  And, you need 3 instances of the client.  I'll call them user A and B, and clients 1, 2, 3.  For my tests, user A and B were friends.
(1) Run client 1, login as user A
(2) Run client 2, login as user B, and set the visibility to everyone.
(3) On client 1, you should see user A show up in the users
(4) Stop client 2.
(5) Run client 3, set visibility to none.
(6) On client 1, you should see user A go away.
(7) Stop client 3
(8) Start client 2.  
(9) On client 1, you should see user A show up (since client 2 has it set to everyone)

**Comment by hifi-gustavo** [comment]
Build console output for commit: a336b61800a10d6d901cc307ccb3f502694e3b22 available at: https://gist.github.com/69b414055be439127213ddee244d2114<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8803-a336b61.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8803-a336b61.dmg

**Comment by thoys** [comment]
Hey @davidkelly whats the difference with this PR and the recently merged one https://github.com/highfidelity/hifi/pull/8746 ?

**Comment by thoys** [comment]
A comparison is that they're both submitted by a David :)

**Comment by davidkelly** [comment]
closing as this was worked on by someone else.  <sigh>

**Pull request closed without merging**
