### PR TITLE
Changes for hifiCodec plugin building on Linux

### PR DESCRIPTION
**Pull request by murillodigital**
Few changes to make hifiCodec plugin build on Linux.  

## Test Plan:

**On Linux:**
1) Build from source, as follows:

```cmake ..
make assignment-client domain-server hifiCodec```

2) Confirm that the hifiCodec target has been built, and you have a libhifiCodec.so file in your `build/plugins/hifiCodec` directory.

3) Open a second terminal window on your build directory, on the first terminal run `domain-server/domain-server` and on the second terminal `assignment-client/assignment-client -n 5 | grep -i codec`

4) Using either of the installers available for download in this PR, connect to your localhost domain server and inspect your assignment-client terminal output, you should see the following lines as soon as your interface connects:

```
[07/15 12:59:34] [DEBUG] [27616] [audio-mixer] all requested and available codecs: ("hifiAC")
[07/15 12:59:34] [DEBUG] [27616] [audio-mixer] Selecting codec: "hifiAC"
[07/15 12:59:34] [DEBUG] [27616] [audio-mixer] selectedCodecName: "hifiAC"
[07/15 12:59:34] [DEBUG] [27616] [audio-mixer] creating new AvatarAudioStream... codec: "hifiAC"
```

Test your audio using both Server Echo as well as with another interactive agent.

**On all other platforms:**

There should be no changes, please run the usual suite of tests, making sure that you do get a hifiCodec dll or dylib in the installer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce67d57279209593daa18c033c1e601450273f0f available at: https://gist.github.com/cc1e61faba99532a301e1965ec10a423<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8254-ce67d57.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8254-ce67d57.dmg

**Comment by OmegaHeron** [comment]
Perhaps I'm being premature in commenting here, but.

In a perfect world... cmake -DSERVER-ONLY=TRUE .. then make assignment-client should result in ac + its codec plugins.

`cmake -DSERVER-ONLY=TRUE ..`
`make assignment-client`

No plugins made.

`cmake ..`
`make assignment-client`

No plugins made

`cmake ..`
`make assignment-client`
`make interface`

Plugins made

**Comment by murillodigital** [comment]
@OmegaHeron that's a very valid comment, however I'll deal with that afterwards, just want to get this building on Linux so I can deploy the codec support to our production infra.

**Comment by OmegaHeron** [comment]
Built this for Ubuntu 16.04 against QT5.6.0 for stack running in docker container.

Yes, it builds plugin using cmake command listed.
Yes, it produced a valid set of codecs on Ubuntu 16.04 (using QT5.6.0 here) with resultant stack ran in a docker container.
Yes, it negotiates hifiAC as codec (assuming you haven't changed codec priority in DS) - it also honors user defined changes to codec priority.
Interface -> Linux stack seems fully functional with audio for both server echo back and another AV.

I feel pretty solid on giving QA Pass here - there's a not related (precisely) issue where audio stream can go a little nuts producing most unpleasant noise, once that's resolved I'd be 100% confident all good vs 99%.

**Comment by OmegaHeron** [comment]
There is one non-critical issue with this that's more of a heads up to Linux compilers.  I didn't notice this in my testing due to not having cleaned out my plugins directory on runtime machine.  If you use;

make assignment-client domain-server hifiCodec

You won't get libpcmCodec.so, only libhifiCodec.so - if you want the zlib codec you still have to make interface

When this is refined to handle making plugins for server only build, hopefully, a call to make assignment-client will produce codecs proper without need to build Interface.

**Pull request merged**
