### PR TITLE
fix invalid ShapeKey ref

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA: Smoke test with a few models.

**Comment by zzmp** [comment]
In response to https://highfidelity.fogbugz.com/f/cases/1985/crash-in-getShapeKey

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf82cc3f5087df26ab451eec7f8092ec3f4a8634 available at: https://gist.github.com/cce91fde8f02c8567fbf1a8fd8e626a0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8849-cf82cc3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8849-cf82cc3.dmg

**Comment by ZappoMan** [comment]
The crash this fixes is rare and hard to repro, so we just need a smoke test on this.

Test plan:
- Basic smoke test.

**Comment by thoys** [comment]
## QA Report

Performance is unchanged, tested this in ova-welcome with 2 clients, while seth had his array of avatars setup, and many more avatars present. My dev-download interfaces both crashed, and these stayed online both, could have been a repro, could've been luck.

QA Pass

**Pull request merged**
