### PR TITLE
Android Work

### PR DESCRIPTION
**Pull request by jherico**
Pre-creating PR for testing by PMs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6572/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6574/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6574/HighFidelity-Beta-PR12246-7d0c21019672fbf6dbfa7750a3032b0d9e228622.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6574/HighFidelity-Beta-PR12246-7d0c21019672fbf6dbfa7750a3032b0d9e228622.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6612/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6612/HighFidelity-Beta-PR12246-ee66ee8d00693766118cd5503dad7d2935e45fac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6612/HighFidelity-Beta-PR12246-ee66ee8d00693766118cd5503dad7d2935e45fac.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6754/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6754/HighFidelity-Beta-PR12246-af06e1c89e6d9c01e7078ff49c9d1cb6484e8a52.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6754/HighFidelity-Beta-PR12246-af06e1c89e6d9c01e7078ff49c9d1cb6484e8a52.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6765/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6765/HighFidelity-Beta-PR12246-443a518c5d95ca75d38b812739c9c4e4f78efe1e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6775/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6775/HighFidelity-Beta-PR12246-443a518c5d95ca75d38b812739c9c4e4f78efe1e.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6787/app_12246_PR.apk

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6790/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6790/HighFidelity-Beta-PR12246-443a518c5d95ca75d38b812739c9c4e4f78efe1e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6790/HighFidelity-Beta-PR12246-443a518c5d95ca75d38b812739c9c4e4f78efe1e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7060/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7060/HighFidelity-Beta-PR12246-3342950108960dd1b1c7fe7976f8e589d92cf2ce.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7074/app_12246_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7074/HighFidelity-Beta-PR12246-3342950108960dd1b1c7fe7976f8e589d92cf2ce.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7074/HighFidelity-Beta-PR12246-3342950108960dd1b1c7fe7976f8e589d92cf2ce.exe

**Pull request closed without merging**
