### PR TITLE
Add comment to Assets.sendFakeHandshake about excluding jsdoc

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
No QA needed, just a comment in the code.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12809/HighFidelity-Beta-PR13967-22df1b3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12809/HighFidelity-Beta-PR13967-22df1b3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12809/HighFidelity-Beta-Interface-PR13967-22df1b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12809/HighFidelity-Beta-PR13967-22df1b3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12809/HighFidelity-Beta-Interface-PR13967-22df1b3.exe

**Pull request merged**
