### PR TITLE
make settings thread safe

### PR DESCRIPTION
**Pull request by sethalves**
- attempt to fix memory corruption associated with Settings

https://highfidelity.fogbugz.com/f/cases/17459/Interface-json-contains-corrupted-entries
https://highfidelity.fogbugz.com/f/cases/17458/Duplicate-fields-in-Interface-json-Settings
https://highfidelity.fogbugz.com/f/cases/18463/crash-in-Setting-Manager-saveAll

https://github.com/highfidelity/hifi/pull/14010
https://github.com/highfidelity/hifi/pull/14057

### CODE REVIEW

**Comment by sethalves** [comment]
to test, use plan from https://github.com/highfidelity/hifi/pull/14010

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13190/HighFidelity-Beta-PR14056-1007c5a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13190/HighFidelity-Beta-PR14056-1007c5a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13190/HighFidelity-Beta-Interface-PR14056-1007c5a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13190/HighFidelity-Beta-PR14056-1007c5a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13190/HighFidelity-Beta-Interface-PR14056-1007c5a.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
PASS @conklin94122 

Settings persist across launches and wearables persist across multiple launches and domain changes. I was not able to force settings to revert short of uninstalling.

**Pull request merged**
