### PR TITLE
Case 21862: Fix shadows when tablet is open and misc threading issues (RC81)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21862/Shadows-appear-wrong-when-tablet-is-shown

Test plan: https://github.com/highfidelity/hifi/pull/15256

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18354/HighFidelity-Beta-PR15257-59fa84b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18354/HighFidelity-Beta-Interface-PR15257-59fa84b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18354/HighFidelity-Beta-PR15257-59fa84b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18354/HighFidelity-Quest-Beta-PR15257-59fa84b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18354/HighFidelity-Beta-PR15257-59fa84b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18354/HighFidelity-Beta-Interface-PR15257-59fa84b.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18372/HighFidelity-Beta-PR15257-7bcbff9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18372/HighFidelity-Beta-Interface-PR15257-7bcbff9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18372/HighFidelity-Beta-PR15257-7bcbff9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18372/HighFidelity-Quest-Beta-PR15257-7bcbff9.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18372/HighFidelity-Beta-PR15257-7bcbff9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18372/HighFidelity-Beta-Interface-PR15257-7bcbff9.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Pull request merged**
