### PR TITLE
switching from LZMA (default) to BZIP2 for NSIS compression

### PR DESCRIPTION
**Pull request by marko8904**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2166/HighFidelity-Beta-PR11094-46966b11321254fd96e5b14d0a052f85b68e0857.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2166/HighFidelity-Beta-PR11094-46966b11321254fd96e5b14d0a052f85b68e0857.exe

**Comment by marko8904** [comment]
Test plan:
- ensure that installer works on all supported Windows OSs
- ensure that PR build time is lower than average (by looking at Console Log output for builds on this PR)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2171/HighFidelity-Beta-PR11094-6855dcbacf253d630e15c1d82340434da1a4c9e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2171/HighFidelity-Beta-PR11094-6855dcbacf253d630e15c1d82340434da1a4c9e0.exe

**Comment by marko8904** [comment]
Note that the switch was finally made only for PR builds. Release builds will be compressed the old way (which gives smaller installers).

**Comment by Nex-Pro** [comment]
Checking windows version of this.

**Comment by Nex-Pro** [comment]
extremely slow download speed on this.

**Comment by Nex-Pro** [comment]
NM it sped up

**Comment by Nex-Pro** [comment]
Installer works fine on Win10 pro

**Pull request merged**
