### PR TITLE
Fix dpi setting in edit.js

### PR DESCRIPTION
**Pull request by ZappoMan**
DPI is an integer value in the Web Entity... because of how edit.js works, you have to specify that numbers have 0 decimals if you want them to be integers.

fixes this bug: https://highfidelity.fogbugz.com/f/cases/5182/Can-t-change-Resolution-DPI-on-a-web-entity

test plan:
- create a web entity
- open properties
- set the DPI setting to some value... see that the setting takes, and that the apparent DPI of the web view changes

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Awaiting Win build to test.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4423/HighFidelity-Beta-PR11679-dcb6530b8a5662700f0932a01e4d8665c587a6a3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4423/HighFidelity-Beta-PR11679-dcb6530b8a5662700f0932a01e4d8665c587a6a3.exe

**Comment by Nex-Pro** [comment]
Testing Win10

**Comment by Nex-Pro** [comment]
Dpi is working fine now across a large range of numbers.

I still feel the input should be sanitized better.

0 = 0 dpi
-1 = 65535 dpi
2e4 = 20000 dpi
3e-1 = 0 dpi
e = well, just e
+12 shows as +12

Most of these clear up on reopening the properties.  However crazy large numbers don't.

**Comment by Nex-Pro** [comment]
tested in desktop mode.

**Comment by Nex-Pro** [comment]
@ZappoMan  Thanks for looking at this.

**Comment by ZappoMan** [comment]
@Nex-Pro - so that's a PASS? I mean - the bug is.. you can't change the DPI at all... now you can... 

There's a general problem with all the entry fields that they don't do that much to sanitize inputs.

**Pull request merged**
