### PR TITLE
Android: Local texture compression using Etc2Comp

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/14785/Compression-of-texture-for-Mobile-format

Test plan (Android):
- We need to do some testing to determine if this is actually beneficial or not.  Run the following steps on multiple phones, once using this PR, and once using the latest from https://github.com/highfidelity/hifi/pull/13152.  Between tests, **make sure to completely uninstall Interface from the phone**.
- Go to a domain (dev-mobile, dev-mobile-master, and Eschatology, etc.).  Don't move or rotate.  Bring up the stats and watch the bottom two rows of the middle expanded column.  The top line is downloads and the bottom line is textures.  Record how long it takes for all of the numbers to go to 0 and stay there.  Record your game and render rates.
- Start a new timer and look all the way around.  Continue rotating your view until all 4 of the numbers go to 0 again.  Record that time.  Close Interface.
- Go into your device settings and find the memory usage for Interface.  It's in a different place on different phones.  Record the memory usage.
- Uninstall interface or press "Clear Data" in Storage.
- Repeat the steps on a few domains.
- In each domain, also make sure that textures look correct (possibly with more artifacts than on desktop).  Make sure that the skybox looks correct (possibly lower resolution), and on domains with irradiance like dev-mobile, make sure the lighting looks correct.

Test plan (Desktop):
- Open Interface, click Developer -> Render -> Clear KTX Cache.  Restart Interface.
- Make sure textures look correct in a few domains.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9870/HighFidelity-Beta-PR13186-a9126f4072829f9dd39cff17637cb396b986fd04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9870/HighFidelity-Beta-Interface-PR13186-a9126f4072829f9dd39cff17637cb396b986fd04.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9884/HighFidelity-Beta-PR13186-8e640c208ba54185b1e0022a113c53815bd9ca83.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9884/HighFidelity-Beta-Interface-PR13186-8e640c208ba54185b1e0022a113c53815bd9ca83.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9936/HighFidelity-Beta-PR13186-12b91a2ab720e8eb5c8c73822b01220003996e96.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9936/HighFidelity-Beta-PR13186-12b91a2ab720e8eb5c8c73822b01220003996e96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9936/HighFidelity-Beta-Interface-PR13186-12b91a2ab720e8eb5c8c73822b01220003996e96.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9970/HighFidelity-Beta-PR13186-2364d35b72319e73b71496cf1f06d43a0bc06355.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9970/HighFidelity-Beta-PR13186-2364d35b72319e73b71496cf1f06d43a0bc06355.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9970/HighFidelity-Beta-Interface-PR13186-2364d35b72319e73b71496cf1f06d43a0bc06355.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9977/HighFidelity-Beta-PR13186-7c7da734034c495d89668f545f2aa9c7a59d8b76.apk

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9980/HighFidelity-Beta-PR13186-7c7da734034c495d89668f545f2aa9c7a59d8b76.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9982/HighFidelity-Beta-PR13186-282e61c085563fd58f3430a66bc7eb634e587f69.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9982/HighFidelity-Beta-PR13186-282e61c085563fd58f3430a66bc7eb634e587f69.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9982/HighFidelity-Beta-Interface-PR13186-282e61c085563fd58f3430a66bc7eb634e587f69.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9982/HighFidelity-Beta-PR13186-282e61c085563fd58f3430a66bc7eb634e587f69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9982/HighFidelity-Beta-Interface-PR13186-282e61c085563fd58f3430a66bc7eb634e587f69.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Results were not as expected.
Noticed some broken textures in both PR's. Does not fail this PR though. Textures look good in Desktop Interface
_**RESULTS**_
PR13186 (This PR)
dev-mobile
Only 1 download left at 45s, After 3m+ did not reach 0
Game Rate: 61
Render Rate: 59.6
While spinning got stuck on 81 pending downloads
187mb RAM on Google Pixel 2 

dev-mobile-master
7m in and 6 downloads left and 42 textures left, did not reach 0
Game Rate: ~2-25 FPS
Render Rate: 15.8
Spinning: Crashed at 1m, had 6 downloads left and 200+ textures left
500mb 
------------------------------------------
PR13152
dev-mobile
1m 19s to load and numbers to reach 0
Game Rate: 40 FPS
Render Rate: 29 FPS
While spinning got stuck on 58 pending downloads
97mb RAM on Galaxy S8 +

dev-mobile-master
Crashed at 1m 54s still had 90+ downloads left did not reach 0
Game Rate: 2-25
Render Rate: 21
Spinning Test: Unable to get reliable results as it kept crashing.
174mb

screenshot_20180525-093321

**Comment by samcake** [comment]
@SamGondelman You need to resolve the conflict and refresh it for build and qa, thanks

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10258/HighFidelity-Beta-PR13186-ae3b933.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10258/HighFidelity-Beta-PR13186-ae3b933.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10258/HighFidelity-Beta-Interface-PR13186-ae3b933.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10258/HighFidelity-Beta-PR13186-ae3b933.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10258/HighFidelity-Beta-Interface-PR13186-ae3b933.exe

**Comment by SamGondelman** [comment]
@qlimnavarro can we try this one again?  I haven't made any major changes, but some clarifications:

1.  Those broken textures in that image are ktx textures that haven't been rebaked since we added Android support to the oven.  I assume that's in hifi-qa-metastable-master or whatever, which I know hasn't been rebaked.  We should stick to testing domains that we know have supported textures.
2.  We've added bot-testing to dev-mobile-master, which is causing an unrelated crash (which, as you found, is present on master, too).  Let's test on a different domain, like dev-mobile and Eschatology.
3.  Can you perform all the tests on one phone, and then repeat them all on another phone, so we can compare the numbers independent of phone type?
4.  If you get stuck on a download again, can you give me the URL of the thing that's downloading?  It should show up in the expanded stats.

Thanks!

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Results were not as expected. Loading times and avg memory used were higher on PR13186 (this PR) than those of 13152 (Master). Interface runs as expected on Desktop with no new issues introduced. No defects discovered during smoke test. Results listed below:
PR13186 (This PR)

Google Pixel 2 XL (8.1.0):

Boot up (Dev-Mobile): 42.39s
Spinning (Dev-Mobile): 5m 44s
Memory (Dev-Mobile): 494mb

Boot up (Dev-Welcome): 6m 50s (149 pending textures, no pending URLs)
Spinning (Dev-Welcome): 5m 48s (358 pending textures, no pending URLs)
Memory (Dev-Welcome): 570mb

 
Samsung Galaxy S9 (8.0.0):

Boot up (Dev-Mobile: 42.7s
Spinning (Dev-Mobile): 7m 28s
Memory (Dev-Mobile): 114mb


Boot up (Dev-Welcome): 6m 12s
Spinning (Dev-Welcome): 5m 25s (153 pending textures, no pending URLs)
Memory (Dev-Welcome): 141mb



PR13152 (Master)

Google Pixel 2 XL (8.1.0):

Boot up (Dev-Mobile): 44.1s
Spinning: (Dev-Mobile): 59.9s
Memory (Dev-Mobile): 686mb

Boot up (Dev-Welcome): 6m 13s (274 pending textures, no pending URLs)
Spinning (Dev-Welcome): 9m 44s (8 pending textures, no pending URLs)
Memory (Dev-Welcome): 785mb


Samsung Galaxy S9 (8.0.0):

Boot up (Dev-Mobile): 41.44s
Spinning (Dev-Mobile): 1m (120 pending textures, no pending URLs)
Memory (Dev-Mobile): 191mb

Boot up (Dev-Welcome): 7m 46s
Spinning (Dev-Welcome): 6m 31s (145 pending textures, no pending URLs)
Memory (Dev-Welcome): 153mb

**Comment by SamGondelman** [comment]
@qligmaloney Are those reversed?  It looks like this PR has lower memory usage across the board.  I would expect higher load times from this PR, since we're doing extra work when we receive the textures.  Also, when you list the pending textures in parentheses, does that mean those textures never finished, even though the processing was at 0?

**Comment by qligmaloney** [comment]
Those are not reversed no. The Pixel 2 had very high usage across the board compared to Galaxy. I stopped the clock at the time shown with pending textures in parenthesis as the value had not gone up or down in 1+ min

**Comment by SamGondelman** [comment]
There's no sense comparing Pixel 2 to Galaxy since different phones manage memory so differently.  The important thing is that the Pixel 2 measurements are lower on this PR (which it looks like they are) and the Galaxy measurements are lower on this PR (which it looks like they are).  It looks like Pixel doesn't manage memory as aggressively, which is in line with some of our other tests.

As for the pending downloads, I'm concerned that they're getting stuck.  It's possible that they're just taking a long time, since some very large images could theoretically take more than a minute or two to process.

Perhaps a better test would be to spin once, slowly, and then stop spinning.  As long as we never get stuck with 0 processing and >0 pending on the bottom row, we should be good.  Can you try it one more time?  I realize the testing takes a while, thank you for doing this!

**Comment by samcake** [comment]
We (Engine Team ) are taking responsability for completing the qa for this PR.
we think it s good to go

**Pull request merged**
