### PR TITLE
edit.js indicates errors via notifications.js

### PR DESCRIPTION
**Pull request by sethalves**
- edit.js no longer uses modal (hand-controller breaking) dialogs to indicate errors
- messages displayed by notifications.js no longer shake when the avatar moves

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1612/You-can-not-click-on-the-dialog-for-you-do-not-have-permissions-when-using-handcontroller

**Comment by sethalves** [comment]
to test:
- use and HMD and hand-controllers
- do things that used to cause edit.js to pop up a modal dialog
- go to a domain where you have to edit rights.  attempt to edit.  attempt to import things from the market.
- observe that the failures are indicated via notifications rather than via modal popups

**Comment by hifi-gustavo** [comment]
Build console output for commit: 785e187a270302784c5cf2628d0b16def0f664ca available at: https://gist.github.com/ebb921f16689ed9990b65e479db8a928<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8631-785e187.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8631-785e187.dmg

**Comment by Nex-Pro** [comment]
tested on Win10: **PASS**

use and HMD and hand-controllers: Check
do things that used to cause edit.js to pop up a modal dialog: Check
go to a domain where you have to edit rights. attempt to edit. attempt to import things from the market: Check
observe that the failures are indicated via notifications rather than via modal popups: **SUCCESS**

**Pull request merged**
