### PR TITLE
fix -- make 3d-line overlays work again

### PR DESCRIPTION
**Pull request by sethalves**
- "start" and "end" parameters of a 3d-line overlay are now relative to its "position".

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1500/Rendering-of-hand-lasers-is-broken

**Comment by sethalves** [comment]
to test:
- use handControllerGrab.js to distance grab something
- observer that the lasers are visible in the expected places

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ff35768aa9ecfb9743ed35fd63939c8023befd1 available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ff35768aa9ecfb9743ed35fd63939c8023befd1 available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ff35768aa9ecfb9743ed35fd63939c8023befd1 available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ff35768aa9ecfb9743ed35fd63939c8023befd1 available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ff35768aa9ecfb9743ed35fd63939c8023befd1 available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-2ff3576.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8487f825a0ff1c924befa4f6a8cf0fd99ce3edff available at: https://gist.github.com/78b7980418935ca9980b79bc24397d6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-8487f82.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8465-8487f82.dmg

**Comment by imgntn** [comment]
grab, hold, teleport lasers appear as expected (oculus touch)

**Comment by Nex-Pro** [comment]
@imgntn I posted in Slack 50 minutes ago that I was testing this! I just finished.

**Comment by Nex-Pro** [comment]
#### Pass

**Comment by Nex-Pro** [comment]
Sigh

**Comment by sethalves** [comment]
I'll never complain about too much testing.

**Pull request merged**
