### PR TITLE
use QVariant instead of ScriptValue for most of EntityScriptingInterface API

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* Vec3, Quat, and other data types use QVariant under the hood
* orientedAngle() is now reported in radians
* from/toPolar() renamed to from/toSpherical()

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Testing:

(1) Make sure edit.js still works correctly:
  (1A) Set position
  (1B) Set rotation
  (1C) Set dimensions
(1D) Set dynamic and add gravity
(2) Make sure handControllerGrab.js works the same as in hifi/master
(3) Grab a copy of the pingPongGun and verify that it properly shoots ping pong balls
(4) Open the JavaScript console and make sure this statement returns true: `Vec3.orientedAngle({x: 1, y: 0, z: 0}, {x: 0, y: 1, z: 0}, {x: 0, y: 0, z: 1}) - (Math.PI / 2) < 0.00001;`

**Comment by AndrewMeadows** [comment]
This is a resurrection of #8349.

**Comment by hifi-gustavo** [comment]
Build console output for commit: de9a2e88d7aad98b46919eefae92e811c8a97e13 available at: https://gist.github.com/297126f594dffdbe7ea0e88dbf018771<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8482-de9a2e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8482-de9a2e8.dmg

**Comment by AndrewMeadows** [comment]
Hrm... I'm seeing a performance drop in this PR.  Using 10 scripts that just do a bunch of Vec3 math inside their `update()` methods and looking at number of profile samples spent in ScriptEngine::run():

this PR = 9.46%
master = 7.44%

It appears to be mostly in `Vec3::qt_static_metacall` which went from 0.01% in master to 2.39% in this PR.

**Comment by Nex-Pro** [comment]
**PR #8482**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used

**QA Tester**: Piper.Peppercorn

**IMO PASS** **Does not seem to have broken anything.**


(1) Make sure edit.js still works correctly: **See observations below.**
(1A) Set position: **SUCCESS** Using desktop mode.
(1B) Set rotation: **SUCCESS** Using desktop mode.
(1C) Set dimensions: **SUCCESS** Using desktop mode.
(1D) Set dynamic and add gravity: **SUCCESS** Using desktop mode.
(2) Make sure handControllerGrab.js works the same as in hifi/master: **Seems ok but as usual there are incomplete laser-beams occasionally. **
(3) Grab a copy of the pingPongGun and verify that it properly shoots ping pong balls: **Balls are fired adjacent to the right side of the muzzle rather than from the center.**  ***This is NOT related to this PR.** 
(4) Open the JavaScript console and make sure this statement returns true: Vec3.orientedAngle({x: 1, y: 0, z: 0}, {x: 0, y: 1, z: 0}, {x: 0, y: 0, z: 1}) - (Math.PI / 2) < 0.00001; : **SUCCESS**

Additional observations:

(1) IMO edit.js never works correctly ( In HMD with hand controllers ). So I am comparing this to current 'normal' for edit.js
Try to edit a value such as for restitution using hand controllers is, or seems to be,  an impossible task as arrows only allow values of 1.0 or 0.0. Attempts to enter values via the virtual keyboard (on the seemingly random occasions it pops-up) fail as the value submitted does not seem to pass to the edit pane.
-------------------------------------------------------------------------

***This is not related specifically to this PR but I noticed it here first.***

In edit window I set the scale to a decimal value less than 1 and clicked rescale.
This resulted in the decimal value remaining displayed  without a leading zero and having no effect on the scale of the object.

Submitted to fogbugz case #1527

https://highfidelity.fogbugz.com/f/cases/1527/Scale-value-in-edit-window-can-be-set-to-a-decimal-less-than-one-Clicking-RESCALE-then-has-no-effect

**Comment by ZappoMan** [comment]
closing for now. review later in context of future refactoring

**Pull request closed without merging**
