### PR TITLE
DO NOT MERGE - Testing

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/4f6bee952c4758674a41<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/301c66f123f9eb067325<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/68d0584a3fee78fa404a<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/79e7c1f2230abe2c06a3<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/16b7b1fad782a53d92f4<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/f8076713e6e03c75df50<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/09119b5032f45f1508f4<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/e0542251e381e58eb005<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/b90a36f4cd2c58fc9050<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by hifi-gustavo** [comment]
OS X Yosemite functional test completed with errors
Download recording here:
https://s3.amazonaws.com/hifi-public/pr-builds/recordings/4295

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
OS X Yosemite functional test completed with errors
Download recording here:
https://s3.amazonaws.com/hifi-public/pr-builds/recordings/4295.mov

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/1d0b187df11e6697a68a<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/b6c7e55cc4bc3ab89d52<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/d08b1c5a0a07df28e94c<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21f9e9ca23094cf5be7f8c0b8c38067c46e41f99 available at: https://gist.github.com/833d8ba105d04d207f4e<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4295.dmg

**Pull request closed without merging**
