### PR TITLE
BUGZ-1167: remove unwanted binaries from bad client-only installers

### PR DESCRIPTION
**Pull request by jherico**
[BUGZ-1167](https://highfidelity.atlassian.net/browse/BUGZ-1167)

The behavior of the console app is determined based on the presence or absence of the _server binaries_ (and nothing else).  Although the build system has been fixed to stop including these server binaries in the new builds, the installer doesn't clean them out if they already exist, _even_ when the installer UI is told to clean up old settings and resources.  

This PR will force the installer to delete pre-existing server binaries in the target folder.

# Testing

Verify that the sandbox version of the installer for this PR works and properly installs the binaries.

To test the actual functionality of this PR

* install the client-only version of the PR
* Verify the console is acting in client only mode
* Go into the install folder and copy the `interface.exe` to `assignment-client.exe` and also to `domain-server.exe`
* Quit the console
* Restart the console
* Verify the console is acting in sandbox mode
* Quit the console
* Uninstall the application
* Verify that the copied `assignment-client.exe` and `domain-server.exe` are still present in the folder
* Re-install the client-only version of the PR
* Verify after re-install that the copied `assignment-client.exe` and `domain-server.exe` are **NO LONGER** present in the folder
* Verify the console is acting in client-only mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21236/HighFidelity-Beta-PR16169-a49fe48.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21236/HighFidelity-Quest-Beta-PR16169-a49fe48.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21236/HighFidelity-Beta-PR16169-a49fe48.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21236/HighFidelity-Beta-Interface-PR16169-a49fe48.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21236/HighFidelity-Beta-PR16169-a49fe48.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21236/HighFidelity-Beta-Interface-PR16169-a49fe48.exe

**Comment by JeffClinton** [comment]
Currently pre-merge testing

**Comment by JeffClinton** [comment]
Pre-merge test fail.

I am not seeing the sandbox in the non-client-only build.  The sandbox appears in the start menu, but when you launch it only the console opens and you cannot reach localhost.  I'm not seeing assignment-client.exe or domain-server.exe in the programs file folder.  Because of this, I haven't been able to follow the test plan by copying those files into the client-only install.

Steps to repro:
1. Download and install the sandbox build https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21236/HighFidelity-Beta-PR16169-a49fe48.exe
2. Observe system tray just has the console without the sandbox
3. Open the sandbox in the start menu, and observe the system tray is still missing the sandbox
4. Attempt to go to localhost

Result:
Sandbox is missing from non-client-only build.

Please note these were all clean installs.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/3597900/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21241/HighFidelity-Beta-PR16169-967e7db.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21241/HighFidelity-Quest-Beta-PR16169-967e7db.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21241/HighFidelity-Beta-PR16169-967e7db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21241/HighFidelity-Beta-Interface-PR16169-967e7db.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21241/HighFidelity-Beta-PR16169-967e7db.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21241/HighFidelity-Beta-Interface-PR16169-967e7db.exe

**Comment by JeffClinton** [comment]
Currently pre-merge testing

**Comment by JeffClinton** [comment]
Pre-merge test fail.  The sandbox is present in the client-only installer.

Steps to repro:
1. Clean install client-only PR
2. Open system tray and observe sandbox is present
3. Go to localhost

Result:
Sandbox is present.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/3598249/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21246/HighFidelity-Beta-PR16169-9be475b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21246/HighFidelity-Beta-Interface-PR16169-9be475b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21246/HighFidelity-Beta-PR16169-9be475b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21246/HighFidelity-Quest-Beta-PR16169-9be475b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21246/HighFidelity-Beta-PR16169-9be475b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21246/HighFidelity-Beta-Interface-PR16169-9be475b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21247/HighFidelity-Beta-PR16169-790ac6a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21247/HighFidelity-Beta-Interface-PR16169-790ac6a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21247/HighFidelity-Beta-PR16169-790ac6a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21247/HighFidelity-Quest-Beta-PR16169-790ac6a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21247/HighFidelity-Beta-PR16169-790ac6a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21247/HighFidelity-Beta-Interface-PR16169-790ac6a.exe

**Comment by JeffClinton** [comment]
Pre-merge test pass

Assignment-client.exe and domain-server.exe were removed during uninstall process, and sandbox was no longer present on reinstall.  Sandbox is present in client+sandbox build.

**Pull request merged**
