### PR TITLE
Entity list - fix resizing

### PR DESCRIPTION
**Pull request by dback2**
Addresses: https://highfidelity.manuscript.com/f/cases/19911

Pre-Merge Test Plan:
- Enter Interface in desktop mode into any domain
- Open Create to the entity list
- Resize the entity list window to be smaller and verify the body of the entity list adjusts to accommodate the new window size
- Resize the entity list window to be larger and verify the body of the entity list adjusts to accommodate the new window size
- Resize some columns within the entity list, resize the entity list window more, and verify the column proportions maintain themselves in the adjusted list

Post-Merge Test Plan:
- Above checks for resizing windows should be added to https://highfidelity.testrail.net/index.php?/cases/view/32704

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15200/HighFidelity-Beta-PR14413-de7f4a4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15200/HighFidelity-Beta-PR14413-de7f4a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15200/HighFidelity-Beta-Interface-PR14413-de7f4a4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15200/HighFidelity-Beta-PR14413-de7f4a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15200/HighFidelity-Beta-Interface-PR14413-de7f4a4.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Entity List window resizes correctly.

It may be worth noting, I saw the Create Window come in very wide while testing, once. I cleared my settings when checking master and it never happened again.

**Pull request merged**
