### PR TITLE
fix asset browser for tablet

### PR DESCRIPTION
**Pull request by druiz17**
Test plan - https://github.com/highfidelity/hifi/pull/12168

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6273/app_12169_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6273/HighFidelity-Beta-PR12169-8e4bd2d66240390d84d32b5b36e9938de3b7106b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6273/HighFidelity-Beta-PR12169-8e4bd2d66240390d84d32b5b36e9938de3b7106b.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Start interface with HMD | 👍 
Open tablet and click Create | 👍 
Click "Open this domain's asset server" | 👍 
Asset Browser page should open | 👍 

@conklin94122

**Pull request merged**
