### PR TITLE
fixed issue of tablets buliding up when flying fast

### PR DESCRIPTION
**Pull request by druiz17**
Test
- fly around really fast
- toggle the button the bring up the tablet
- while toggling tablets should not build

Second test
- bring up the tablet and go into menu
- confirm that when clicking on menu items you hear a clicking sound

### CODE REVIEW

**Comment by claudioshg** [comment]
Will test when build is ready

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2af72f1a507b72aee5f8c066781d2f76069c8580 available at: https://gist.github.com/f2deca3f88bb4f86cf81dc9c4aa53f7c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9591-2af72f1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9591-2af72f1.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2cc1ee008d32720b0fa455c8048a2228afd1f143 available at: https://gist.github.com/f2deca3f88bb4f86cf81dc9c4aa53f7c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9591-2cc1ee0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9591-2cc1ee0.dmg

**Comment by claudioshg** [comment]
Testing ^^

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift and in Desktop Mode

Test 1
- fly around really fast: **PASS**
- toggle the button the bring up the tablet: **PASS**
- while toggling tablets should not build: **FAIL**

Test 2
- bring up the tablet and go into menu: **PASS**
- confirm that when clicking on menu items you hear a clicking sound: **SEE NOTES**

**Notes**
Test 1 and 2 were performed in Desktop mode and in Oculus VR. 
At every attempt, the tablet materialized when the menu button was toggled during mid-flight.
I flew the avatar at full speed up, down, front, and back.

Clicking on items in the menu did produce a clicking sound. Except,
the only place that did not produce a sound was in MENU>AUDIO>DEVICES>(choosing an option here produced no sound)

**Comment by druiz17** [comment]
@claudioshg  I miss typed the instruction for test 1 part 3. Please test that multiple tablets do not start building up around you while flying.

**Comment by claudioshg** [comment]
Understood @druiz17 will test

**Comment by claudioshg** [comment]
### PASS
Retested in Oculus VR and in Desktop mode. 
- No build up of tablets resulted.
- I flew in every direction at full speed. Toggling the tablet, many times, in mid-flight and no sign of other tablets anywhere.

**Pull request merged**
