### PR TITLE
make laser pointers work even while content is loading

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- Basic smoke test 
- make sure: laser pointers, grabbing, and distance grabbing are still working as before.
- New feature: While content is loading (after going to a new domain) --- the laser pointers should still work to click on things like mute/unmute, go to, kick, etc...

Note: Distance grabbing won't actually allow you to move anything until physics is started... but the lasers will appear. This is expected behavior.

**Comment by howard-stearns** [comment]
Approving, but I do think we should add a note (in both) files, with the good reason that we're opting out of the usual update mechanism that we expect other good citizens to live by. (I.e., to work while content is loading.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: ddce0ef74ad0c82e97034eba8ccc5309fb9cc322 available at: https://gist.github.com/ce8bff8ab06d14d801789082f1e3ef47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-ddce0ef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-ddce0ef.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ddce0ef74ad0c82e97034eba8ccc5309fb9cc322 available at: https://gist.github.com/ce8bff8ab06d14d801789082f1e3ef47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-ddce0ef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-ddce0ef.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 652af860edccc8152499db972681550b15b2c8c6 available at: https://gist.github.com/ce8bff8ab06d14d801789082f1e3ef47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-652af86.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8810-652af86.dmg

**Comment by nbq** [comment]
testing

**Comment by nbq** [comment]
After testing this for a bit I see that that the buttons on the HUD menu are not clickable unless you are in HMD mode (I assume) since it did not work for me. Passing this off to someone else

**Comment by ZappoMan** [comment]
Thanks anyway @nbq -- you're right - this one pretty much requires an HMD.

**Comment by howard-stearns** [comment]
tested. works.
Also fixes https://highfidelity.fogbugz.com/f/cases/1848/There-is-no-way-to-close-the-Goto-dialogs-without-keboard <== @ZappoMan that suggests that the  slow-script-punisher is somewhat dangerous. Something to be aware of, anyway.

**Comment by howard-stearns** [comment]
(above is edited. I cited the wrong ticket.)

**Pull request merged**
