### PR TITLE
fix an initialization order fiasco

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that could cause a static variables in the input system to have a bad value

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change
- or, if you can build on Linux with asan enabled (HIFI_MEMORY_DEBUGGING=1 in environment before running cmake), run interface like this: `ASAN_OPTIONS="new_delete_type_mismatch=0:check_initialization_order=1" ./interface`

see https://isocpp.org/wiki/faq/ctors#static-init-order

**Comment by YuppyPlays** [comment]
Can test when built :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1087/HighFidelity-Beta-PR10813-05f0ec267e2f1fadbcfafbd4f1166928b73acfd3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1087/HighFidelity-Beta-PR10813-05f0ec267e2f1fadbcfafbd4f1166928b73acfd3.exe

**Comment by YuppyPlays** [comment]
Testing complete:

**Fail** The Taskbar does not appear to be working (Cannot click on anything). The tablet however functions as normal.
The Taskbar worked after changing back from tablet mode on Desktop, I am unsure if this is directly related to PR?.. I cannot see list of current bugs as I do not have access to the FogBugz.

**Comment by CainFoool** [comment]
@yuppyplays this is normal, check latest comment on the RC PR.

**Pull request merged**
