### PR TITLE
Update BUILD_WIN.md

### PR DESCRIPTION
**Pull request by robin-k-wilson**
Added environment variable 

PreferredToolArchitecture = x64

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18277/HighFidelity-Beta-PR15232-435c58c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18277/HighFidelity-Beta-Interface-PR15232-435c58c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18277/HighFidelity-Beta-PR15232-435c58c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18277/HighFidelity-Beta-Interface-PR15232-435c58c.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18277/HighFidelity-Beta-PR15232-435c58c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18277/HighFidelity-Quest-Beta-PR15232-435c58c.apk)

**Comment by ZappoMan** [comment]
This is a small change to the docs, no risk, let's merge.

**Pull request merged**
