### PR TITLE
Fix rotation handle crash

### PR DESCRIPTION
**Pull request by Atlante45**
Circle overlay now render in batches which fixes the crash we've been having when trying to rotate entities via edit.js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7209825dd646e1d21c0e7273c5d25b8bc950528c available at: https://gist.github.com/4d602435549869db0d9d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.dmg

**Comment by PhilipRosedale** [comment]
You need to pull?

**Comment by Atlante45** [comment]
@PhilipRosedale Updated, but I'm actually I'm gonna push one more commit, because the rotation rings get culled and we don't see them if we are on the wrong side.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 67473ac2541bc4a088ef4acce098a07efac569e3 available at: https://gist.github.com/4d602435549869db0d9d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c7f24eeb6385e8c34cf6f2877a519d4883d29bc available at: https://gist.github.com/4d602435549869db0d9d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5169.dmg

**Comment by samcake** [comment]
OK on mac, crash on windows, i keep on testing

**Comment by samcake** [comment]
My bad triple checked and it works correctly on windows
ON mac it worls too
I think it's not part of this PR, the text panel showing the rotation angle is not displayed on mac but correctly shown on windows

**Pull request merged**
