### PR TITLE
Move DS config version to config file

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4583/HighFidelity-Beta-PR11723-c4af883cf5bbceb5961b1d2b9fe177cad98f29c3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4583/HighFidelity-Beta-PR11723-c4af883cf5bbceb5961b1d2b9fe177cad98f29c3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4589/HighFidelity-Beta-PR11723-7616fe193cff920299d44b39cc98c7e97efe8029.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4589/HighFidelity-Beta-PR11723-7616fe193cff920299d44b39cc98c7e97efe8029.exe

**Comment by Atlante45** [comment]
[Test Plan - Config version subsection](https://highfidelity.testrail.net/index.php?/suites/view/193&group_by=cases:section_id&group_id=453&group_order=asc)

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
### Results available on [TestRail Run 606](https://highfidelity.testrail.net/index.php?/runs/view/606&group_by=cases:section_id&group_id=453&group_order=asc)

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
