### PR TITLE
Set GL in QML immediately

### PR DESCRIPTION
**Pull request by zzmp**
Avoids a ton of reference errors on startup, which potentially disabled nVidia shading.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62c252e8ef8e7d10b121d65810008e6b75f68b39 available at: https://gist.github.com/d64e56410db9dd6e484745484ad52da1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7703.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7703.dmg

**Comment by ZappoMan** [comment]
Test Plan:
- Basic Smoke Test
- Verify that log file doesn't include these messages:
```
[04/19 07:49:45] [WARNING] file:///C:/Program Files/High Fidelity - PR7703/resources/qml/desktop/Desktop.qml:39: ReferenceError: GL is not defined
[04/19 07:49:45] [WARNING] file:///C:/Program Files/High Fidelity - PR7703/resources/qml/desktop/Desktop.qml:39: ReferenceError: GL is not defined
[04/19 07:49:45] [WARNING] file:///C:/Program Files/High Fidelity - PR7703/resources/qml/desktop/Desktop.qml:39: ReferenceError: GL is not defined
```

**Comment by OmegaHeron** [comment]
Tested Windows 7
Basic smoke test showed no difference from stable.
Multiple runs/multiple domains no sign of ReferenceError: GL is not defined seen in logs.

In my case with current stable version I do see ReferenceError: GL is not defined messages so this is a definite fix for my setup.

**Comment by zzmp** [comment]
See: https://app.asana.com/0/74051501495175/113562124483499.

**Comment by Nex-Pro** [comment]
Tested Windows 10 64bit  16GB
Nvidia GTX770 2GB

Message present in #4703
Message absent in PR7703

Success.

**Pull request merged**
