### PR TITLE
AC shutdown info + PPID watcher on Unix

### PR DESCRIPTION
**Pull request by Atlante45**
- AC monitor now prints the error code the child AC returned when it finished.
- Implemented automatic shutdown of child processes when the parent dies for Mac/Linux

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1700/HighFidelity-Beta-PR10970-2d246d25637edc69902a8ebe0ac2d639ca523cfb.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1702/HighFidelity-Beta-PR10970-2d246d25637edc69902a8ebe0ac2d639ca523cfb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1702/HighFidelity-Beta-PR10970-2d246d25637edc69902a8ebe0ac2d639ca523cfb.exe

**Comment by AndrewMeadows** [comment]
Needs a test plan.

**Comment by Atlante45** [comment]
## Test Plan:

Requirements:
- Mac or Linux

1) Run a domain server manually by running `./domain-server`
2) Run an Assignment client monitor and filter its log by running `./assignment-client -n7 | grep "assignment-client-monitor] Child"`
3) Use `ps | grep assignment-client` to list the running ACs
4) Pick on of the ACs that is not the AC Monitor (the one with `-n7` and kill it using `kill -s INT 41402` (Replace `41402` with the appropriate PID)
    - You should see a line similar to this in the monitor's log:
> [07/17 11:32:31] [DEBUG] [default] [27094] [assignment-client-monitor] Child process 41402 has returned with exit code 0. Removed from internal map.

5) Pick another AC and kill it using `kill -s ABRT 41403` (Replace `41403` with the appropriate PID)
    - You should see a line similar to this in the monitor's log:
> [07/17 11:33:49] [CRITICAL] [default] [41396] [assignment-client-monitor] Child process 41403 has crashed with exit code 6. Removed from internal map.

6) Finally kill the monitor using `kill -s ABRT 27094` and make sure no assignment-clients are still running using `ps | grep assignment-client` (this could take a couple seconds).

**Comment by OmegaHeron** [comment]
I'll try to test this later tonight (3 hours or so from time of this writing).  If someone else can do before I post again that I have it in progress, please do.

**Comment by OmegaHeron** [comment]
Testing in progress.

**Comment by OmegaHeron** [comment]
Tested Ubuntu 16.04
QA Pass

Works exactly as outlined in test framework.  General smoke test ok as well.  Also tested my systemd based launch/management with this PR -- I launch ACs with (-n1) -tX -aIP individually versus -n7 and this PR has no negative impact running/restarting/recovering ACs under that method.

**Pull request merged**
