### PR TITLE
Disk cache tweaks

### PR DESCRIPTION
**Pull request by Atlante45**
Some disk cache improvements:
- Force load from cache when the resource is in the cache
- check for new version at the resource URL
- Refresh resource if needed

Added an editor: (Developer > Network > Disk Cache)
- Shows cache size/max size
- Shows path
- Let you clear the cache

### CODE REVIEW

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7690301e582ec54d9947fefc86f6294313cdfba6 available at: https://gist.github.com/bf567e3815fb453f07f2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4381.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4381.dmg

**Comment by ZappoMan** [comment]
This seems weird, is this expected? Max size 1GB?
screen shot 2015-03-08 at 11 34 40 am

**Comment by Atlante45** [comment]
Arf nope, labels are inverted, #4396 fixes it.

**Pull request merged**
