### PR TITLE
log AVX2 support in audio-mixer

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d830d7ea95ba5760edc7e286243fafee232a557 available at: https://gist.github.com/8870883ada18e56ddc42784fc4f13c93<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9641-9d830d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9641-9d830d7.dmg

**Comment by OmegaHeron** [comment]
@zzmp - since this was something I wanted for my own info I went ahead and tested Win 10 and Ubuntu 16.  tldr version = pass.  Will add full QA blurb when/if it goes QA Ready.

**Comment by kencooke** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d830d7ea95ba5760edc7e286243fafee232a557 available at: https://gist.github.com/8870883ada18e56ddc42784fc4f13c93<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9641-9d830d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9641-9d830d7.dmg

**Comment by OmegaHeron** [comment]
QA Pass

I'm pretty much perfectly setup to test this....

Linux box 1 - Ubuntu 16.04.1 - Intel(R) Core(TM) i7-3720QM
Linux box 2 - Ubuntu 16.04.1 - Intel(R) Xeon(R) CPU E5-2650L v3
Windows 10 - i5 6500

Looking at processor feature flags - Linux box 1 does not have AVX2 support, Linux box 2 and windows 10 machine does.

Linux box 1:  `Feb 09 14:28:03 M18xR2 assignment-client[20251]: [02/09 14:28:03] [DEBUG] [default] [20251] [audio-mixer] AVX2 Support: disabled`

Linux box 2: Will test once this hits dev release build queue and deploys to my remotes - it's a bit more complex to deploy a PR build to (but I have no doubt it will reflect a correct value based on next line).

Windows 10:   `[02/09 14:44:28] [DEBUG] [default] [11548] [audio-mixer] AVX2 Support: enabled`

General smoke test = pass (audio injectors/voice server echoback, etc).

**Pull request merged**
