### PR TITLE
Restore eye joint rotations

### PR DESCRIPTION
**Pull request by howard-stearns**
Also, do not correct for camera position on my avatar. (That will be done by zero or one receivers.)

### CODE REVIEW

**Comment by howard-stearns** [comment]
Should fix https://app.asana.com/0/26225263936266/44434971607953

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88505c180d2796794965fa5b131332b60651e70c available at: https://gist.github.com/d89be409172b5a908d9f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5544.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5544.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88505c180d2796794965fa5b131332b60651e70c available at: https://gist.github.com/d89be409172b5a908d9f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5544.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5544.dmg

**Pull request merged**
