### PR TITLE
fix model export

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
@imgntn This should fix the directory and file selection for model export and import. (I.e., doesn't address handling import of invalid models or missing properties when exporting.)

**Comment by ZappoMan** [comment]
@ctrlaltdavid - can you add a test plan please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3780b18cc07efc1dc2696c9a64ce7999024abcef available at: https://gist.github.com/31414a66e84456985b24916af5ced8ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8044.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8044.dmg

**Comment by ctrlaltdavid** [comment]
Testing

Model import: edit.js running, Edit > Import Entities
- Table lists directories and .json files, only.
- Double-click on a directory to navigate into it.
- Highlight a directory and press Open button to navigate into it.
- Up button (top right) navigates up a directory level.
- Home button navigates to the "home" directory.
- Drop-down navigates to parent directories.
- Open button is disabled when no table entry is highlighted.
- Highlight a JSON model file and press "Open" imports the model.
- On Windows: able to navigate to another drive and import a model.

Model export: edit.js running, select a model in-world, Edit > Export Entities
- Table lists directories and .json files, only.
- Can navigate per model import.
- When type a filename into the input field, lower left, the primary button text changes to "Save".
- Deleting all filename text disables the primary button.
- Pressing the Save button writes a JSON file with the specified name.

Other dialog uses continue to function:
- Running Scripts, From Disk: you can select a script to run.
- Settings > General > Put my snapshots here: you can select a directory.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf6945b40363a1879c0e27b6cf34eb968fbda1fb available at: https://gist.github.com/31414a66e84456985b24916af5ced8ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8044.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8044.dmg

**Comment by Nex-Pro** [comment]
**pr #8044**



Model Import:

Testing Observations.

It would seem to me that importing and exporting should fall under the file menu.

On selecting import entities in the edit menu the directory shown was:
    C:/Windows/system32.

This seems a little odd.

On clicking the drop-down arrow adjacent to the address the choices shown were:

    C:/Windows/system32
    C:
    This PC

On clicking the home button ( which looks like an up arrow ) the directory changed appropriately to my user folder. C:/users/me

Using the up/left arrow allowed me to navigate down to root on C:

Clicking the home button took me, correctly back to my user directory.

I navigated to C:\Logs where there are no appropriate files and none were listed.
I then clicked on the drop-down arrow.

C:/Windows/system32 was no longer in the list and had been replaced by
my user folder C:/users/me
__________________________________________________________________________________

Table lists directories and .json files, only. **PASS**
Double-click on a directory to navigate into it. #### PASS
Highlight a directory and press Open button to navigate into it. **PASS**
Up button (top right) navigates up a directory level. ***Button is top left.**
Home button navigates to the "home" directory. **PASS**

Drop-down navigates to parent directories. **Partial Success IMO**
    ***Each time the import window is open it defaults to C:/Windows/system32***

Open button is disabled when no table entry is highlighted. **PASS**
Highlight a JSON model file and press "Open" imports the model. **PASS**
On Windows: able to navigate to another drive and import a model. **PASS**
    ***Correctly listed the 4 drives I have currently switched on.***
________________________________________________________________________________


Model export: edit.js running, select a model in-world, Edit > Export Entities

Table lists directories and .json files, only. **PASS**
Can navigate per model import. **FAIL**
    ***Annoyingly this dialog closes on importing a model. Then, on re-opening the dialog, defaults to C:/Windows/system32***

When type a filename into the input field, lower left, the primary button text changes to "Save". **PASS**
Deleting all filename text disables the primary button. **PASS**
Pressing the Save button writes a JSON file with the specified name. **PASS**

 Also correctly deals with cases where user types filename.json

 I was a bit cheeky and typed filename.json.json and the file was saved as such ( expected behaviour ). 

I am accustomed to being able to click on an entry in the file list and that would subsequently appear in the input field for editing. This is not the case.
The input field is labeled 'Path:'

 I typed C:\dodecahedron.json in the expectation that it would save dodecahedron.json in c:\  it did not. (daft thing to do but worth a check)

I did the same for my home folder and it saved ok.

___________________________________________________________________________

Running Scripts, From Disk: you can select a script to run. **PASS**

Settings > General > Put my snapshots here: you can select a directory. **PARTIAL**


Clicking 'BROWSE' adjacent to where it says C:/users/me/Desktop opens the dialog which is pointing to C:/Windows/system32 again.

**Pull request merged**
