### PR TITLE
0.74.0: new treatment for hmd/tablet login

### PR DESCRIPTION
**Pull request by howard-stearns**
see https://github.com/highfidelity/hifi/pull/14205

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13858/HighFidelity-Beta-PR14206-4553930.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13858/HighFidelity-Beta-PR14206-4553930.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13858/HighFidelity-Beta-Interface-PR14206-4553930.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13858/HighFidelity-Beta-PR14206-4553930.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13858/HighFidelity-Beta-Interface-PR14206-4553930.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13911/HighFidelity-Beta-PR14206-4553930.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13911/HighFidelity-Beta-PR14206-4553930.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13911/HighFidelity-Beta-Interface-PR14206-4553930.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13911/HighFidelity-Beta-PR14206-4553930.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13911/HighFidelity-Beta-Interface-PR14206-4553930.exe

**Comment by qliejahner** [comment]
PASS @conklin94122 

All logins worked in VR and desktop modes.

**Pull request merged**
