### PR TITLE
Add support for .content.zip content uploads

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8062/app_12654_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8063/app_12654_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8063/HighFidelity-Beta-PR12654-03c8c14f612847024374e3ea822a11fc36a5fbc7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8071/app_12654_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8071/HighFidelity-Beta-PR12654-d140ccb790b3b29a5a86fa665039885acc551075.dmg

**Comment by huffman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8085/app_12654_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8085/HighFidelity-Beta-PR12654-d140ccb790b3b29a5a86fa665039885acc551075.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8085/HighFidelity-Beta-PR12654-d140ccb790b3b29a5a86fa665039885acc551075.exe

**Comment by huffman** [comment]
1. Open interface and go to your local sandbox
 1. Drag and drop this link to your interface window: [model_obj_3tB8CXKd_zz_8p9JvjI_rDp.zip](https://github.com/highfidelity/hifi/files/1820985/model_obj_3tB8CXKd_zz_8p9JvjI_rDp.zip)
    1. You should see a popup that says "Couldn't unzip file"
 1. Drag and drop this link to your interface window: http://mpassets.highfidelity.com/21eec2fc-a1c9-4fed-893a-d69fdd103a57-v1/backup-test-archive-2018-03-16_11-42-53.content.zip
    1. You should see a prompt to replace your domain content, click Yes
    1. After a few moments you should see the domain update. You should see a light blue floor, a disc golf basket with the High Fidelity logo and text, and a text entity that says "Test Text"

**Comment by qlimnavarro** [comment]
Currently testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Files could not unzip, and content was updated.

**Pull request merged**
