### PR TITLE
Revert "Revert "fix for invisible avatars after radius ignore""

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug with interface refusing to render an avatar it believed it was still ignoring

### CODE REVIEW

**Comment by birarda** [comment]
Reverts highfidelity/hifi#10922, which reverted #10835

**Comment by birarda** [comment]
QA and development approval was done on #10835 so I am flagging this PR as such. This was reverted because it introduced a protocol version change.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1603/HighFidelity-Beta-PR10952-f6d9a79fb5283798face33bfc68b231094b5eb5e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1603/HighFidelity-Beta-PR10952-f6d9a79fb5283798face33bfc68b231094b5eb5e.dmg

**Pull request merged**
