### PR TITLE
Implement MS16413: Improve angularVelocity of printed Snaps

### PR DESCRIPTION
**Pull request by zfox23**
Implements [MS16413](https://highfidelity.manuscript.com/f/cases/16413/Snap-tool-prints-fall-face-down-when-yaw-is-facing-180).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Print a snapshot. Verify that it doesn't fall on its face when it hits the ground after printing it.
2. Turn 180 degrees. Print the same snapshot. Verify that it doesn't fall on its face when it hits the ground after printing it.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11106/HighFidelity-Beta-PR13539-6efb895.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11106/HighFidelity-Beta-PR13539-6efb895.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11106/HighFidelity-Beta-Interface-PR13539-6efb895.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11106/HighFidelity-Beta-PR13539-6efb895.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11106/HighFidelity-Beta-Interface-PR13539-6efb895.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 all snapshots fall face up when being printed

**Pull request merged**
