### PR TITLE
Fix issue with scaling prior to KTX serialization

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5cb786555119dc98d1bd614ed97352e99767229f available at: https://gist.github.com/bd1b62e1dcba29971959aec30ba82bf0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-5cb7865.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-5cb7865.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8af1ca6b69f332a5cb4f86cf9e34c8652202cb5 available at: https://gist.github.com/bd1b62e1dcba29971959aec30ba82bf0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-e8af1ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-e8af1ca.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b54bfee451dff91a2b8a1c9f7d79da3408ef6f3c available at: https://gist.github.com/bd1b62e1dcba29971959aec30ba82bf0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-b54bfee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-b54bfee.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 813e3a1bcaa147db3f236373f58287390a736cb8 available at: https://gist.github.com/bd1b62e1dcba29971959aec30ba82bf0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-813e3a1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9930-813e3a1.dmg

**Comment by samcake** [comment]
OK we are good with that

**Pull request merged**
