### PR TITLE
Clean up spatial tree item fetch in graphics pipeline

### PR DESCRIPTION
**Pull request by zzmp**
This will be useful to build on later, if a new setup task is made.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c14e3272e6e01593edc21c9234043361ba3c3516 available at: https://gist.github.com/faa6af643cb740a0da0966a20c1b24d4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9204-c14e327.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9204-c14e327.dmg

**Comment by zzmp** [comment]
QA: Make sure graphics still work as expected.

**Comment by OmegaHeron** [comment]
Tested Windows 10 - i5 6500 CPU - GTX 970 GPU

Desktop and DK2 HMD tested.  No changes to visuals/FPS -- Looked at dev-playa, dev-demo, local sandbox, old apartment scene and my own content.  Basic smoke tests pass.

**Comment by zzmp** [comment]
@samcake wants this to stay as a placeholder for later functionality.

**Pull request closed without merging**
