### PR TITLE
Use UI Toolkit border styles for various dialogs

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
File > Help...
File > About Interface
Settings > Avatar Settings > Browse
Go To button (directory.js)
Examples button (examples.js)

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Test notes:
1) Verify that the following dialogs now have their border, title (if any), close button, and resize handle styled the same as the preferences dialogs:
	File > Help...
	File > About Interface
	Settings > Avatar Settings > Browse
	Go To button (directory.js)
	Examples button (exeamples.js)
2) Verify that the above dialogs still work.
3) Verify that the following dialogs still work:
	edit.js

**Comment by ZappoMan** [comment]
@ctrlaltdavid - does this also fix the "browser window" ?? e.g. the Ctrl+B

**Comment by hifi-gustavo** [comment]
Build console output for commit: 16874baf5f4da43be5f1c2e4a365985e9b738616 available at: https://gist.github.com/55e6640ee830ce7ca16c1442126a7d43<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7775.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7775.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e5ee98ee60ed3cf6b7eb81fabe4060c4e5503fef available at: https://gist.github.com/55e6640ee830ce7ca16c1442126a7d43<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7775.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7775.dmg

**Comment by ctrlaltdavid** [comment]
@ZappoMan No, that dialog hasn't been updated. This PR just fixes the borders of some common general user windows with HTML content. The browser window needs a full restyle (i.e., address bar etc. as well as borders) per the UI Toolkit sometime.

**Comment by Nex-Pro** [comment]
Platform Win10 desktop 16gb GTX770 2gb

Noticed that the top border on the settings/avatar/browse window is taller than the others by maybe 16px.

Dialogs seem to work as normal. 
Apart from Edit does not pop up on top if settings/avatar/browse has been clicked.  In which case the edit window is above the avatar settngs window but under the avatar/browse window.
Any reason that avatar appearance has "Everything" available ?

**Comment by ctrlaltdavid** [comment]
Will fix the Settings > Avatar > Browse window top border, thanks! And also remove the "Close" button from the bottom border (there's no reason for this dialog to have it's own "Close" button in addition to the normal "x" top right.
Have filed an Asana but report on the Edit window opening under the avatar browser window.
Avatar appearance window is just the Examples directory with the avatar section preselected. Yes, this is a bit weird. Have filed an Asana item on this too.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b8109f16422a4f6d17e9fd92fea63e0f292d599 available at: https://gist.github.com/55e6640ee830ce7ca16c1442126a7d43<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7775.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7775.dmg

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  Yeah I wondered about the close button. I should have mentioned it.

**Pull request merged**
