### PR TITLE
case 20705: Allow log window to stay on top

### PR DESCRIPTION
**Pull request by danteruiz**
Add a menu option in developers to keep the log window on top.

Ticket: https://highfidelity.manuscript.com/f/cases/20705/Set-the-Qt-WindowStaysOnTopHint-for-the-main-log-window

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16734/HighFidelity-Beta-PR14774-52a6944.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16734/HighFidelity-Beta-PR14774-52a6944.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16734/HighFidelity-Beta-Interface-PR14774-52a6944.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16740/HighFidelity-Beta-PR14774-2c22fb8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16740/HighFidelity-Beta-Interface-PR14774-2c22fb8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16740/HighFidelity-Beta-PR14774-2c22fb8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16740/HighFidelity-Beta-Interface-PR14774-2c22fb8.exe

**Comment by danteruiz** [comment]
Test plan: 
    1. Log window on top = TRUE: The log window remains visible in front of interface regardless of whether the user clicks on the interface menu bar, or minimizes and enlarges interface, etc
    2. Log window on to = FALSE: (current behavior) The low window can be behind interface if the user clicks on the interface menu bar or minimizes and enlarges interface, etc.

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16769/HighFidelity-Beta-PR14774-db58173.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16769/HighFidelity-Beta-PR14774-db58173.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16769/HighFidelity-Beta-Interface-PR14774-db58173.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16769/HighFidelity-Beta-PR14774-db58173.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16769/HighFidelity-Beta-Interface-PR14774-db58173.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
