### PR TITLE
File dialogs and modal message boxes in QML

### PR DESCRIPTION
**Pull request by jherico**
* Removes the old `DialogContainer`, `VrDialog` types, migrating to `Window`
* Always use `visible` on the top level window instead of `enabled` to hide / show windows
* Add pure QML support for basic message boxes 
* Consolidate use of customized WebEngineViews 
* Remove dead / unused QML dialogs
* File open dialog
* Better modal / always-on-top window handling 
* Better focus handling, clicking off a window will remove it's focus, allowing keyboard shortcuts to work

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5804890ab37bf4505364d004559be18f5e9249b4 available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d47b54d20a8d63c03368c95f22e033b06a4b1e6c available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a1a5226c4866df01b2b4ec4555ae0b29d17175e available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8d93342b8f31adfdd47b3d7a3da1ba8f00dd74be available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c2fe499b7b2f4d7de15093bd3228c342f800b78 available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 396eca960e65d5713cc6bf934c43e977f704deec available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf8d2c518212e3d2545063b3ae1332f95a580372 available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5aa8398adbbda8aeb8973313ef5a8ae26eb80533 available at: https://gist.github.com/8b89f5bffa5533c186ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6840.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6840.dmg

**Comment by howard-stearns** [comment]
Big improvement on focus!
It still doesn't toggle off, but definitely better.
E.g., ctrl-j bring up scripts, and ctrl-alt-j brings up console, but a second such chord does not make them go away.

**Pull request merged**
