### PR TITLE
Case 20966: glb files

### PR DESCRIPTION
**Pull request by raveenajain**
https://highfidelity.manuscript.com/f/cases/20966/glTF-glb-format
https://github.com/highfidelity/hifi_tests/pull/346

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17142/HighFidelity-Beta-PR14878-446176d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17142/HighFidelity-Beta-PR14878-446176d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17142/HighFidelity-Beta-Interface-PR14878-446176d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17142/HighFidelity-Beta-PR14878-446176d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17142/HighFidelity-Beta-Interface-PR14878-446176d.exe

**Comment by raveenajain** [comment]
Test Plan:

1 - Run interface. Enter a domain with minimal external influences.
2 - Go to Edit -> Running Scripts -> From URL
3 - You should see the same output if you run a script calling a .glb file as you would see if you run a script running a .gltf file. For example, you should see the same thing if you run https://raw.githubusercontent.com/raveenajain/hifi_tests/gltf_binary/tests/content/entity/model/modelReaders/gltfReader/glbTestSuite/city/test.js and https://raw.githubusercontent.com/raveenajain/hifi_tests/gltf_binary/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/city/test.js

All .glb scripts: 
https://github.com/raveenajain/hifi_tests/tree/gltf_binary/tests/content/entity/model/modelReaders/gltfReader/glbTestSuite

All corresponding .gltf scripts:
https://github.com/raveenajain/hifi_tests/tree/gltf_binary/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite  

(Note some models do not render; see Expected images)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17173/HighFidelity-Beta-PR14878-709f784.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17173/HighFidelity-Beta-PR14878-709f784.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17173/HighFidelity-Beta-Interface-PR14878-709f784.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17173/HighFidelity-Beta-PR14878-709f784.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17173/HighFidelity-Beta-Interface-PR14878-709f784.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17186/HighFidelity-Beta-PR14878-cfc13de.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17186/HighFidelity-Beta-PR14878-cfc13de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17186/HighFidelity-Beta-Interface-PR14878-cfc13de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17186/HighFidelity-Beta-PR14878-cfc13de.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17186/HighFidelity-Beta-Interface-PR14878-cfc13de.exe

**Pull request merged**
