### PR TITLE
FBX reader fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes:
- Fix root nodes sometimes being appended to a preceding tree.
- Handle geometric offset in root nodes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6700/app_12284_PR.apk

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Test loading of problematic FBX file.
- Put the attached FBX file on a Web server (or use the following URL: http://ctrlaltstudio.com/downloads/hifi-dev/goblin/gob.fbx).
- Use Create > Model > Model URL to add model to a domain.
- The model should render per the attached image. (Body, knife in hand, and square on ground.)

2) Smoke test loading of other FBX files in general.

gob fbx

[gob.zip](https://github.com/highfidelity/hifi/files/1676126/gob.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6700/HighFidelity-Beta-PR12284-cadd4e61ad5bb2c2e5e3025614f16fcf7feac00b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6700/HighFidelity-Beta-PR12284-cadd4e61ad5bb2c2e5e3025614f16fcf7feac00b.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
