### PR TITLE
Remove Entities.currentAvatarEnergy and related from the API

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8360/app_12741_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8366/app_12741_PR.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Scripts had correct output, cube remained changed after a reboot.

**Pull request merged**
