### PR TITLE
Guard against dereferencing a empty SharedSoundPointer

### PR DESCRIPTION
**Pull request by hyperlogic**
This fixes a somewhat rare crash

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/18290/

**Comment by hyperlogic** [comment]
QA Test plan:
* import the following entities into a domain: [fifteen-sounds.json](https://gist.githubusercontent.com/hyperlogic/dd9270d3fd3997e834b03aa12098be4e/raw/b9bd65b3fee177584a2e464b2d8cb3dd78b2c27e/fifteen-sounds.json)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13074/HighFidelity-Beta-PR14016-87efc1d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13074/HighFidelity-Beta-PR14016-87efc1d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13074/HighFidelity-Beta-Interface-PR14016-87efc1d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13074/HighFidelity-Beta-PR14016-87efc1d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13074/HighFidelity-Beta-Interface-PR14016-87efc1d.exe

**Comment by rickcarr044** [comment]
Currently testing PR14016

**Comment by rickcarr044** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13232/HighFidelity-Beta-PR14016-87efc1d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13232/HighFidelity-Beta-PR14016-87efc1d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13232/HighFidelity-Beta-Interface-PR14016-87efc1d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13232/HighFidelity-Beta-PR14016-87efc1d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13232/HighFidelity-Beta-Interface-PR14016-87efc1d.exe

**Comment by rickcarr044** [comment]
FAIL @conklin94122

Ran three test runs in staging metaverse.  The first run ended with Interface crashing before I could quit it.  I was able to complete the second and third runs by quitting Interface, but the log files ended with the message:  DependencyManager::destroy(): class AvatarManager was not properly destroyed!

That outcome seems to contradict "You should not crash when closing interface."

Note: The crash dialog came up after the first run, but did not appear after the last two.
Details written up in MS: 18748
https://highfidelity.manuscript.com/f/cases/18748/DependencyManager-destroy-class-AvatarManager-was-not-properly-destroyed-when-closing-PR14016
[Logs.20180924.Crash.zip](https://github.com/highfidelity/hifi/files/2412866/Logs.20180924.Crash.zip)

**Comment by QliCknox** [comment]
Currently Testing

**Comment by hyperlogic** [comment]
I used backtrace to investigate the crash you encountered. It is a known issue affecting master so I marked the bug you filed as a duplicate.  I don't think we should hold up this PR because of that crash.

**Comment by conklin94122** [comment]
@rickcarr044 As long as the pre-existing issues don't block your ability to test this PR, and this PR passes it's own tests, it's ok to pass it. Let me know if you feel strongly otherwise.

**Comment by hyperlogic** [comment]
Turns out Austin submarine fixed this in #14073

**Comment by rickcarr044** [comment]
PASS @conklin94122

Agreed with the assessment after checking MS: 18506.  First instance occurred before I quit, second and third instances did not crash and only left the warning message.

**Pull request closed without merging**
