### PR TITLE
Keyboard menu option in general settings

### PR DESCRIPTION
**Pull request by danteruiz**
Move the keyboard toggle option from developers to Settings > general

ticket - https://highfidelity.manuscript.com/f/cases/20042/Add-toggle-to-turn-off-on-3D-Keyboard

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
1. There should be a option to toggle between the old and new keyboard, it should be in settings -> general and called `Use Virtual Keyboard`.
2. confirm that you can switch from the old to new 
3. confirm that the old keyboard still appears on Web Entities.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15448/HighFidelity-Beta-PR14483-2902838.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15448/HighFidelity-Beta-PR14483-2902838.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15448/HighFidelity-Beta-Interface-PR14483-2902838.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
