### PR TITLE
Replace the linear interpolation embedded in the .WAV/.RAW loader with high quality polyphase resampling.

### PR DESCRIPTION
**Pull request by kencooke**
When downsampling 48khz to 24khz, linear interpolation creates aliasing distortion that is quite audible.  This change greatly improves the audio quality for all sound assets.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 280289045c91e43541e21de7bd3b74ed155b5a44 available at: https://gist.github.com/6f9f60fc20450b87ab252d44236aeb91<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.dmg

**Comment by kencooke** [comment]
To test, verify that you can still hear sounds from audio injectors.  The only discernable difference is the audio should sound cleaner than before.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89bfa5bc0930da99113592f6c231ac6a94db10cb available at: https://gist.github.com/6f9f60fc20450b87ab252d44236aeb91<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.dmg

**Comment by kencooke** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89bfa5bc0930da99113592f6c231ac6a94db10cb available at: https://gist.github.com/6f9f60fc20450b87ab252d44236aeb91<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8015.dmg

**Comment by Nex-Pro** [comment]
Listened to the Pink Floyd track at playa big speakers. Sound had some popping and glitches.
I don't know how often the track should trigger but after bookmarking the spot I returned several times and the sound track would not start properly.
After a considerable time and after restarting interface the track did trigger again.

**Comment by ZappoMan** [comment]
@Nex-Pro - your test case didn't really test this code at all... the injectors running in playa aren't actually using this new code. So by going to listen to Pink Floyd in the playa you were not testing this new code.

Here are several tests that WILL test this new code:
1) run local sandbox with default content (background noises) make sure your sandbox is the sandbox from THIS PR... connect with this client... if you hear sounds... it's running this code and it's working.

2) using any script that injects sounds locally if you hear those sounds... it's running this code... and it's working... examples: collision sounds, ping pong gun.

3) Make sure your'e running dialTone.js with this Client, if this script is running and you connect/disconnect from a domain, and hear the sounds... it's working... it's a pass.

**Comment by ZappoMan** [comment]
I tested a local sand box, heard sounds, jumped between domains, and heard the dialTone sound... PASS.

**Comment by Nex-Pro** [comment]
@ZappoMan ok I **WILL** test **THIS** pr in **THE LOCAL SANDBOX** of **THIS PR** but I read **THESE** testing notes and  had a conversation with **THE** guy who wrote **THE** code. So I guess it WILL be **OK**.

**Comment by Nex-Pro** [comment]
@ZappoMan or maybe I won't ! 
:)

**Pull request merged**
