### PR TITLE
remove href property for non-owned avatar entities

### PR DESCRIPTION
**Pull request by misslivirose**
**Test plan: 2 users** 
Go to a domain where you do not have rez rights. Import the following JSON: https://hifi-content.s3.amazonaws.com/liv/dev/teleporter.json

A second tester should click on the red sphere that appears and should not be teleported to dev-welcome.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4497/HighFidelity-Beta-PR11702-c7857d4fc310a9e4cef99c74d14c431d90e17685.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4497/HighFidelity-Beta-PR11702-c7857d4fc310a9e4cef99c74d14c431d90e17685.exe

**Comment by YuppyPlays** [comment]
Testing [w/ Cain].

**Comment by YuppyPlays** [comment]
Testing complete:

Go to a domain where you do not have rez rights. Import the following JSON: https://hifi-content.s3.amazonaws.com/liv/dev/teleporter.json **I think this is a pass but you cannot import without Tester 1 having rights to rez? - Tester 2 in this instance does not have rez rights.**

A second tester should click on the red sphere that appears and should not be teleported to dev-welcome. **Tester 2 does not get teleported, Tester 1 teleports when clicking**

I believe this is a **Pass** and just a small typo in the test plan, please let me know if otherwise though :)

**Comment by themelissabrown** [comment]
Needs one more re-test based on original testing plan before QA approved tag can be added.

**Comment by misslivirose** [comment]
**Test Rail Case: https://highfidelity.testrail.net/index.php?/cases/view/2173**

**Pull request merged**
