### PR TITLE
[DNM] 404 domain redirection

### PR DESCRIPTION
**Pull request by wayne-chen**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12601/HighFidelity-Beta-PR13923-c95cb97.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12601/HighFidelity-Beta-Interface-PR13923-c95cb97.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12603/HighFidelity-Beta-PR13923-4c36c9c.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12605/HighFidelity-Beta-PR13923-5eb80d0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12605/HighFidelity-Beta-PR13923-5eb80d0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12605/HighFidelity-Beta-Interface-PR13923-5eb80d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12605/HighFidelity-Beta-PR13923-5eb80d0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12605/HighFidelity-Beta-Interface-PR13923-5eb80d0.exe

**Comment by JeffClinton** [comment]
Notes:
-The floor is missing for the teleport beam.  It falls through the world.  You are stuck if you do not have advanced controls enabled for HMD mode.
-There's a hole in the ground behind the portals where you can fall through the world.
-There's no ceiling, so you can fly away from the portals.
-The hit boxes may need a slight adjustment.  I only really notice this in desktop 1st person mode.  I can clip through the right edges of the portals and not trigger them.
-I assume the audio cues (ping on load, background neutral sound clip) will come when it gets merged with Dante's stuff?
-User has create permissions in the domain (this is a design decision)

**Comment by alexiamandeville** [comment]
In response to @JeffClinton:

> -User has create permissions in the domain

The user should not have create permissions in the domain. Thanks for catching all these!

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12641/HighFidelity-Beta-PR13923-002c654.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12641/HighFidelity-Beta-Interface-PR13923-002c654.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12654/HighFidelity-Beta-PR13923-1ce6c84.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12654/HighFidelity-Beta-Interface-PR13923-1ce6c84.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12655/HighFidelity-Beta-PR13923-0be7a5f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12655/HighFidelity-Beta-PR13923-0be7a5f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12655/HighFidelity-Beta-Interface-PR13923-0be7a5f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12655/HighFidelity-Beta-PR13923-0be7a5f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12655/HighFidelity-Beta-Interface-PR13923-0be7a5f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12656/HighFidelity-Beta-PR13923-29b96d0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12656/HighFidelity-Beta-PR13923-29b96d0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12656/HighFidelity-Beta-Interface-PR13923-29b96d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12656/HighFidelity-Beta-PR13923-29b96d0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12656/HighFidelity-Beta-Interface-PR13923-29b96d0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12657/HighFidelity-Beta-PR13923-afd7321.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12657/HighFidelity-Beta-PR13923-afd7321.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12657/HighFidelity-Beta-Interface-PR13923-afd7321.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12657/HighFidelity-Beta-PR13923-afd7321.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12657/HighFidelity-Beta-Interface-PR13923-afd7321.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12663/HighFidelity-Beta-PR13923-f38a26a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12663/HighFidelity-Beta-PR13923-f38a26a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12663/HighFidelity-Beta-Interface-PR13923-f38a26a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12663/HighFidelity-Beta-PR13923-f38a26a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12663/HighFidelity-Beta-Interface-PR13923-f38a26a.exe

**Comment by wayne-chen** [comment]
Closing since this is a partial implementation of #13938.

**Pull request closed without merging**
