### PR TITLE
Fix wallets passphrase focus problem

### PR DESCRIPTION
**Pull request by druiz17**
This PR address the issue of the wallet passphrase unable to be selected after you check the show passphrase checkbox

Ticket https://highfidelity.fogbugz.com/f/cases/10024/Wallet-TextField-Focus-Problems

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
-If you don't already have a Wallet set up, set one up, then restart Interface.
- Open the Wallet app. Click the "Show passphrase" checkbox on the "Please Enter Your Passphrase" screen.
- You should be able to click inside the passphrase TextField to give keyboard focus to the TextField.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5393/HighFidelity-Beta-PR11928-23303a00735e8f285ca4b4527a84e3abda6b5e13.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5393/HighFidelity-Beta-PR11928-23303a00735e8f285ca4b4527a84e3abda6b5e13.dmg

**Pull request closed without merging**
