### PR TITLE
Fix fast talking

### PR DESCRIPTION
**Pull request by sethalves**
- tie the rate of audio-driven facial animation to the update rate

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- start in flat-screen mode
- switch to the mathew avatar
- press h to enter mirror mode
- talk into your mic, watch the audio-driven facial animation
- switch to hmd
- switch to flat-scren
- press / and observe that the update rates are in the hundreds
- talk into you mic, observe that the facial animations are still okay

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/2134/Avatar-lips-moving-super-fast

**Comment by hifi-gustavo** [comment]
Build console output for commit: 55c2d367527ab76bd3cdbefbdbd9a161d9233b87 available at: https://gist.github.com/ae8b777f70bbf08d6e475f37b6196fe5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10115-55c2d36.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10115-55c2d36.dmg

**Comment by 68chase** [comment]
Testing

**Comment by 68chase** [comment]
I don't see a Matthew or Mathew Avatar
image

**Comment by sethalves** [comment]
sorry -- I think that was the name of the guy they scanned to make it.  In the market it's the first one: "Photo-Real Male Avatar"

**Comment by 68chase** [comment]
@sethalves Thanks testing now

**Comment by 68chase** [comment]
Passed 
image

**Pull request merged**
