### PR TITLE
Fix script reload icon not working in Windows developer builds

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4442/HighFidelity-Beta-PR11687-da33c4fcf23e3ca173bd946482743914148683e9.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Test on both Windows and OSX:
- In the Running Script window, load a script (e.g., the chat.js script).
- Check that the script entry's "reload" circular arrow works (i.e., script stops and restarts).

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4446/HighFidelity-Beta-PR11687-da33c4fcf23e3ca173bd946482743914148683e9.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4450/HighFidelity-Beta-PR11687-da33c4fcf23e3ca173bd946482743914148683e9.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4452/HighFidelity-Beta-PR11687-da33c4fcf23e3ca173bd946482743914148683e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4452/HighFidelity-Beta-PR11687-da33c4fcf23e3ca173bd946482743914148683e9.exe

**Comment by ctrlaltdavid** [comment]
QA ready

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
In the Running Script window, load a script (e.g., the chat.js script). | Pass
Check that the script entry's "reload" circular arrow works (i.e., script stops and restarts). | Pass

All good.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
