### PR TITLE
case 20654: Updating user activity logging for login experience

### PR DESCRIPTION
**Pull request by wayne-chen**
MS#[20654](https://highfidelity.manuscript.com/f/cases/20654/Implement-full-user-activity-logging-for-login-experience)

# TEST PLAN
- Launch interface 
- login screen should pop up
- log every action you take and the steps you visually go through in the login (i.e. having login fail with bad credentials, etc.)
- Ensure that [Metabase](https://metabase.highfidelity.com) gets data logged based on every user action that occurs in the login experience with the handle "encourageLoginDialog" in the `Details Json` column

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16342/HighFidelity-Beta-PR14676-ba8620b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16342/HighFidelity-Beta-PR14676-ba8620b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16342/HighFidelity-Beta-Interface-PR14676-ba8620b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16342/HighFidelity-Beta-PR14676-ba8620b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16342/HighFidelity-Beta-Interface-PR14676-ba8620b.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16455/HighFidelity-Beta-PR14676-ba8620b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16455/HighFidelity-Beta-PR14676-ba8620b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16455/HighFidelity-Beta-Interface-PR14676-ba8620b.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
Stopped testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16461/HighFidelity-Beta-PR14676-3b913db.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16461/HighFidelity-Beta-PR14676-3b913db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16461/HighFidelity-Beta-Interface-PR14676-3b913db.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16461/HighFidelity-Beta-PR14676-3b913db.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16461/HighFidelity-Beta-Interface-PR14676-3b913db.exe

**Comment by JeffClinton** [comment]
The following events were triggered

win/desktop
login - switch to desktop mode
login - can't access your account
login - username/pw incorrect
login - pw incorrect
login - Keep me logged in toggle on/off
login - PW visibility toggle on/off
login - Click sign up
login - No thanks button
login - Log in with keep me logged in checked
login - Log in with keep me logged in not checked
Sign-up - click cancel
Sign up - email taken
Sign up - username taken
Sign up - PW blank
Sign up - PW visibility toggle on/off
Sign up - Keep me logged in toggle on/off
Sign up - New account with keep me logged in checked
Sign up - New account with keep me logged in not checked

win/hmd
login - switch to hmd mode
Repeated the rest of the above

**Pull request merged**
