### PR TITLE
Desktop equip - deleted/cleared entities fix

### PR DESCRIPTION
**Pull request by dback2**
Ensure deleted or cleared entities are properly unequipped

Test Plans:
https://highfidelity.testrail.net/index.php?/cases/view/15103
https://highfidelity.testrail.net/index.php?/cases/view/73

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9076/app_12980_PR_e21c451815bb89d34f7ac5889ab78f4773108fd0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9076/HighFidelity-Beta-PR12980-e21c451815bb89d34f7ac5889ab78f4773108fd0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9076/HighFidelity-Beta-Interface-PR12980-e21c451815bb89d34f7ac5889ab78f4773108fd0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9076/HighFidelity-Beta-PR12980-e21c451815bb89d34f7ac5889ab78f4773108fd0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9076/HighFidelity-Beta-Interface-PR12980-e21c451815bb89d34f7ac5889ab78f4773108fd0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Desktop equipping works and looks great!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9123/app_12980_PR_71dc75b2081b26de1d969727b00d4d63766fe533.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9123/HighFidelity-Beta-PR12980-71dc75b2081b26de1d969727b00d4d63766fe533.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9123/HighFidelity-Beta-Interface-PR12980-71dc75b2081b26de1d969727b00d4d63766fe533.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9123/HighFidelity-Beta-PR12980-71dc75b2081b26de1d969727b00d4d63766fe533.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9123/HighFidelity-Beta-Interface-PR12980-71dc75b2081b26de1d969727b00d4d63766fe533.exe

**Pull request merged**
