### PR TITLE
Add option to enable/disable the mini tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Settings > General > "Use mini tablet" option added that enables/disables the mini tablet.

Scripting API changes:
- HMD.miniTabletEnabled Boolean property added.
- HMD.miniTabletEnabledChanged(enabled) signal added.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Settings > General > .... should enable/disable the mini tablet on the fly and the setting should be remembered over program runs. By default it should be enabled.
- Clean install of PR build.
- Run Interface.
- Check Settings > General > Use mini tablet : it should be enabled by default.
- Check that the mini tablet displays in HMD mode. (Palm facing your camera and your camera looking at your palm.)
- Disable Settings > General > Use mini tablet while in HMD mode. The mini tablet should no longer display.
- Re-enable Settings > General > Use mini tablet option while in HMD mode. The mini tablet should resume displaying.
- Disable Settings > General > Use mini tablet option in desktop mode and restart Interface. The the option should be disabled and the mini tablet should not display.
- Enable Settings > General > Use mini tablet option in desktop mode and enter HMD mode. The mini tablet should display.

https://highfidelity.manuscript.com/f/cases/19768

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14844/HighFidelity-Beta-PR14362-2809793.apk

**Comment by JeffClinton** [comment]
Currently testing

**Comment by ctrlaltdavid** [comment]
The problem occurred when starting up Interface in HMD mode.
I've added two items to the end of the bulleted list in the test plan.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14899/HighFidelity-Beta-PR14362-371919b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14899/HighFidelity-Beta-PR14362-371919b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14899/HighFidelity-Beta-Interface-PR14362-371919b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14899/HighFidelity-Beta-PR14362-371919b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14899/HighFidelity-Beta-Interface-PR14362-371919b.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14974/HighFidelity-Beta-PR14362-de61f0f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14974/HighFidelity-Beta-PR14362-de61f0f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14974/HighFidelity-Beta-Interface-PR14362-de61f0f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14974/HighFidelity-Beta-PR14362-de61f0f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14974/HighFidelity-Beta-Interface-PR14362-de61f0f.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15081/HighFidelity-Beta-PR14362-de61f0f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15081/HighFidelity-Beta-PR14362-de61f0f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15081/HighFidelity-Beta-PR14362-de61f0f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15081/HighFidelity-Beta-Interface-PR14362-de61f0f.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
