### PR TITLE
add 1s heartbeat interval command line switch

### PR DESCRIPTION
**Pull request by birarda**
- adds a command line argument that enables heartbeat stats sending at 1s

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

(1) Run this PR normally for 1 minute or so. Quit.
(2) Run this PR with the `--fast-hearbeat` command line switch. Quit.

Ping me here to check user activities and confirm that they arrive with the expected frequency.

**Comment by OmegaHeron** [comment]
Testing this - will ping once completed.

**Comment by OmegaHeron** [comment]
Test 1 complete @birarda  - I can compile Interface on Linux pretty quick ;)  Will run again from Windows 10 when Jenkins gets done.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e04aebb8d33e9e9bb4a4e072690dc7d5b7f381f available at: https://gist.github.com/d77c3e203073eef4021b19237ba2f01d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9409-1e04aeb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9409-1e04aeb.dmg

**Comment by birarda** [comment]
Confirming that your Ubuntu tests looked good - first test had 10s heartbeats, second had 1s.

**Comment by OmegaHeron** [comment]
Test 2 complete - Windows 10 - same as above.

**Comment by birarda** [comment]
Test 2 looks good as well. QA Pass.

**Pull request merged**
