### PR TITLE
reformatted main.cpp for additional readability

### PR DESCRIPTION
**Pull request by skarstensen**
Added some linefeeds to space out cramped code blocks.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
Ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2720/HighFidelity-Beta-PR11236-5185ebdd3186ca6ab4f281e6de075146a20cb322.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2720/HighFidelity-Beta-PR11236-5185ebdd3186ca6ab4f281e6de075146a20cb322.exe

**Comment by OmegaHeron** [comment]
Smoke testing now.

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Since, after looking at code change, this is all cosmetic so a simple smoke test of Interface suffices to QA.

**Pull request closed without merging**
