### PR TITLE
Display resource-access events in marketplace item tester

### PR DESCRIPTION
**Pull request by kkurian**
Display resource-access events in the marketplace item tester.

Also, convert the marketplace item tester into a single-page app.

### CODE REVIEW

**Comment by kkurian** [comment]
[tester: capture & display resources](https://trello.com/c/28O8eN9v/692-tester-capture-display-resources)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13555/HighFidelity-Beta-PR14127-d663853.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13555/HighFidelity-Beta-PR14127-d663853.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13555/HighFidelity-Beta-Interface-PR14127-d663853.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13580/HighFidelity-Beta-PR14127-bd1af96.apk

**Comment by kkurian** [comment]
This test refers to an "asset." Example assets are provided here:
https://www.dropbox.com/sh/77y67519q7ult25/AACRkBRFkdAe6p5hRFgdTlXSa?dl=0

Test plan:

1. Open Developer > Marketplace Item Tester
2. Select "Load File"; a file picker should appear
3. Use the file picker a asset to load; any kind of asset _except_ application is fine for this test
4. Verify: name and path of asset appears in the marketplace item tester panel
5. If the combo box displays "unknown" then select "entity" or "wearable" as appropriate; otherwise verify: the combo box automatically displays the correct kind of asset
6. Select the icon next to the trash can, which should instantiate the asset
7. Verify: the asset instantiates
8. Verify: "0 resources loaded..." changes to reporting some number of resources loaded
9. Select the maximize "+" icon next to "... resources loaded ..."
10. Verify: a text area appears and "... resources loaded ..." is replaced by a list of resources, one line each, each line containing a timestamp followed by a url (it is possible that instead of a url there is just a number -- this is okay)
11. Verify: the number of resources in the maximized view matches the number of resources reported in the minimized view
12. Select the minimize "-" icon next to the text area
13. Verify: the text area minimizes back to the "... resources loaded ..." line and that the line correctly reports the number of resources as seen in the maximized view
14. Close the marketplace item tester
15. Open the marketplace item tester
16. The asset(s) previously loaded into the panel should still appear however all should report "0 resources loaded..." and their maximized views should show no assets loaded.
17. Repeat 6-14

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13581/HighFidelity-Beta-PR14127-6a58073.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13581/HighFidelity-Beta-PR14127-6a58073.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13581/HighFidelity-Beta-Interface-PR14127-6a58073.dmg

**Comment by kkurian** [comment]
Pulling QA Ready b/c we may decide to ditch this PR in favor of https://github.com/highfidelity/hifi/pull/14133, which is a continuation of the work here.

**Pull request closed without merging**
