### PR TITLE
HOTFIX - Fix crash in variable allocation management

### PR DESCRIPTION
**Pull request by jherico**
Hotfix for stable branch based on #10246

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4f5624a237580e4e96ed911e7b15dc7d5f72e47b available at: https://gist.github.com/8efa8c851d53d0b4ac76bf90324b284e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10247-4f5624a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10247-4f5624a.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4f5624a237580e4e96ed911e7b15dc7d5f72e47b available at: https://gist.github.com/8efa8c851d53d0b4ac76bf90324b284e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10247-4f5624a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10247-4f5624a.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

Without anything specific to look for; ran standard smoke test (full run of QA script plus my own tests).  All pass.

**Pull request merged**
