### PR TITLE
Fix for laggy avatar attachments

### PR DESCRIPTION
**Pull request by hyperlogic**
This was difficult to notice, as it only affected movement that occurred after physics.  But it is very noticeable if you disable avatar physics.

There was a one frame lag in rotation only if avatar collisions are enabled.  If avatar collisions are disabled, the lag affects both rotation and position.  This PR fixes both issues.

### CODE REVIEW

**Comment by hyperlogic** [comment]
Test plan: run the examples/tests/avatarAttachmentTest.js

1. Attach the hat and the coat, by pressing the icons on the right hand side of the screen.
2. Disable avatar physics by unchecking the "Developer > Avatar > Enable avatar collisions" menu items.
3. Fly around quickly.

On the release build, you'll notice that the hat and the coat detach slightly from the base avatar.
After this PR, the hat and the coat should be firmly attached.

**Comment by hyperlogic** [comment]
https://app.asana.com/0/26225263936266/113405783853938

**Comment by hifi-gustavo** [comment]
Build console output for commit: 544928b46eafaf45e42c94b3e4541f708d6048fa available at: https://gist.github.com/0f26293e735f8d71b81b166fb4cf12cb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7705.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7705.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 279e77f523e8ccf7b12b485dbe52cf9bd2b02fe2 available at: https://gist.github.com/0f26293e735f8d71b81b166fb4cf12cb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7705.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7705.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7705
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Successful test.  Attached the hat and the coat by pressing the icons on the right hand side of the screen and disabled avatar physics by unchecking the "Developer > Avatar > Enable avatar collisions" menu items and flew around quickly and clothes stayed attached perfectly.  Screen shot attached.
**Successful Logout/Crash:** Successful test.
capture

**Pull request merged**
