### PR TITLE
Do Not Merge -- Model.cpp has no global position or rotation

### PR DESCRIPTION
**Pull request by sethalves**
- remove Model classes instance variables for position and rotation

### CODE REVIEW

**Comment by sethalves** [comment]
I'm not convinced this is the right way to go, but I've created this PR in case someone wants to make fun of it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed0bd47df103b462e86418ce7462395a235c7966 available at: https://gist.github.com/c8c11b90f294487b87bd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5859.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5859.dmg

**Comment by ZappoMan** [comment]
what's the intent of this change?

**Comment by sethalves** [comment]
I have, on several occasions, had trouble with the position and rotation in the Model class not matching what was in AvatarData or EntityItem.  There is always a way to fix it, but I wondered if we really needed the position in Model.cpp.  This is an exploration of the consequences of removeing Model's position and rotation member variables.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f26f4159a4ea8b3f5cda49f8db98937bea095fd0 available at: https://gist.github.com/c8c11b90f294487b87bd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5859.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5859.dmg

**Pull request closed without merging**
