### PR TITLE
Change Avatar App design for avatar collisions

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR changes the checkboxes on the Avatar App used to configure avatar collisions.
https://highfidelity.manuscript.com/f/cases/20296/New-Setting-to-Disable-Avatar-Avatar-Collisions

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Pre-merge and Post-merge plans included on the ticket:
https://highfidelity.manuscript.com/f/cases/20296/New-Setting-to-Disable-Avatar-Avatar-Collisions

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16422/HighFidelity-Beta-PR14705-43d9673.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16422/HighFidelity-Beta-PR14705-43d9673.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16422/HighFidelity-Beta-Interface-PR14705-43d9673.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16432/HighFidelity-Beta-PR14705-824a93f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16432/HighFidelity-Beta-PR14705-824a93f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16432/HighFidelity-Beta-Interface-PR14705-824a93f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16432/HighFidelity-Beta-PR14705-824a93f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16432/HighFidelity-Beta-Interface-PR14705-824a93f.exe

**Pull request merged**
