### PR TITLE
Fix audio qt59

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- build with Qt 5.9
- open Tablet
- click Audio button
- make sure there is a list of audio devices available

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/840/HighFidelity-Beta-PR10737-36ff765d7f15a54a9ab19e5872ad38cd28bf7de2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/840/HighFidelity-Beta-PR10737-36ff765d7f15a54a9ab19e5872ad38cd28bf7de2.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/844/HighFidelity-Beta-PR10737-9fb947ea3c07ccd75e5d0e76b23c5fb3572238ec.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/844/HighFidelity-Beta-PR10737-9fb947ea3c07ccd75e5d0e76b23c5fb3572238ec.dmg

**Comment by AndrewMeadows** [comment]
The changes in this PR relate to a single name change.  It is not clear to me how/why this fixes anything.  Was an API used incorrectly?  Is the name change to avoid namespace collision?

**Comment by vladest** [comment]
Yes, the name Audio for import alias overlap "Audio" context export from C++ code. Porbably, qml engine login changed since Qt 5.6, so it doesnt works anymore in Qt 5.9

**Comment by druiz17** [comment]
I confirm that this fix works for qt59 and the build produced above

**Pull request merged**
