### PR TITLE
be more careful about grab action -- if it somehow expires, reinstate it

### PR DESCRIPTION
**Pull request by sethalves**
- work around bug in action expiration which causes equipped items to sometimes come loose.
- make sure that held entities never go "inactive" in bullet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5d0604b8d31f1f8c81e7e3a911f86d2bbc07e79f available at: https://gist.github.com/29a02f037393bd92f4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6757.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6757.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c210928089b4b8753272655b6a5392e76ef315b available at: https://gist.github.com/29a02f037393bd92f4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6757.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6757.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 212d2d9e8fc7cc0eda2d882b2431fe1f6dd76bf4 available at: https://gist.github.com/948765a763d739938bd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6757.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6757.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 212d2d9e8fc7cc0eda2d882b2431fe1f6dd76bf4 available at: https://gist.github.com/29a02f037393bd92f4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6757.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6757.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd82383d3370d12b607f5bbf8392b9c0af154584 available at: https://gist.github.com/29a02f037393bd92f4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6757.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6757.dmg

**Comment by howard-stearns** [comment]
I'm merging this because the code looks ok and it doesn't blow up.
However, I find that I'm having a lot of problems with both equip and grab -- both with this PR and in master. (Bow attaches upside down. Ping pong gun sometimes fails to attach. Grab a cube is flakey with left sometimes not working,...)  I think we need an acceptance test of grab and equip.

**Pull request merged**
