### PR TITLE
BUGZ-447: Use new performance preset API

### PR DESCRIPTION
**Pull request by zfox23**
[BUGZ-447](https://highfidelity.atlassian.net/browse/BUGZ-447): Use new performance preset API

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19720/HighFidelity-Beta-PR15657-8e5c94a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19720/HighFidelity-Beta-Interface-PR15657-8e5c94a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19720/HighFidelity-Beta-PR15657-8e5c94a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19720/HighFidelity-Quest-Beta-PR15657-8e5c94a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19720/HighFidelity-Beta-PR15657-8e5c94a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19720/HighFidelity-Beta-Interface-PR15657-8e5c94a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19729/HighFidelity-Beta-PR15657-97bd0d5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19729/HighFidelity-Beta-Interface-PR15657-97bd0d5.dmg

**Comment by zfox23** [comment]
DO NOT MERGE until I get final signoff from Joshua on the language

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19729/HighFidelity-Beta-PR15657-97bd0d5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19729/HighFidelity-Beta-Interface-PR15657-97bd0d5.exe

**Comment by joshuamdavis** [comment]
Ship it.

**Comment by ZappoMan** [comment]
Removed the DNM because @joshuamdavis gave us the green light.

**Pull request merged**
