### PR TITLE
remove version difference from update dialog

### PR DESCRIPTION
**Pull request by birarda**
- remove the version number difference from the update dialog

### CODE REVIEW

**Comment by birarda** [comment]
##### Test Plan

This dialog doesn't show up in PR builds. Should be tested by someone with a local build environment.

Trick the dialog into showing up in dev with a difference in build numbers. Confirm that the dialog does not show the number of versions behind you are.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/91/HighFidelity-Beta-PR10522-3e09c911f57dc02fbba3a81ad6bf2da234c7a352.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/91/HighFidelity-Beta-PR10522-3e09c911f57dc02fbba3a81ad6bf2da234c7a352.dmg

**Comment by Atlante45** [comment]
This cannot be tested conventionally.
Testing it with a custom built interface.

**Pull request merged**
