### PR TITLE
Fix the text input for edit's newModelDialog

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- In tablet mode click on model in edit.
- Check the text box is visible
- In HMD mode click on the text box and make sure that the keyboard comes up and works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34f3c4abee6bfbf6af3126fb5bdec14ea4af3a1e available at: https://gist.github.com/8c7afa14b75caa3729b73c42b591317e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10131-34f3c4a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10131-34f3c4a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: de8b7eeb27ae691e3b867334329c7ef1d25a40b5 available at: https://gist.github.com/8c7afa14b75caa3729b73c42b591317e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10131-de8b7ee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10131-de8b7ee.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10131-de8b7ee.exe

PASS:
- In tablet mode click on model in edit. Check the text box is visible.
PASS
- In HMD mode click on the text box and make sure that the keyboard comes up and works.
PASS: I clicked on the text box with stylus, finger, laser, mouse

NOTE:
- It's very difficult to read the text. Text is very small.
apr10131

**Pull request merged**
