### PR TITLE
Fix Entity Certificate display upon inspection in RC-57

### PR DESCRIPTION
**Pull request by zfox23**
# What's New
- Fix a bug that caused inspecting an entity to yield a blank certificate

# Known Issues/Incomplete
- N/A

# Future Work
- This hack will have to be reversed after our 10/24 demo, since, at that point, @davidkelly will merge a PR to the backend that will normalize all instances of `Certificate ID` strings when sending/receiving data to/from the server.

# Test Plan

## Prerequisites

Currently, you must manually enable "commerce" by adding `"commerce": true,` in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating `Settings.setValue("commerce", true)` and restarting.

If your wallet is already set up OR if you have previously set up a wallet on a different build (and thus you have a record of your wallet on the backend), you must perform the following steps to rest your wallet:
1. Open the Wallet app. If you're just resetting your wallet because there's a record of a previous wallet on the backend, go through setup.
2. Go to the "Help" tab in the Wallet app
3. Press the red "DBG: RST Wallet" button at the top of the window

If your wallet is set up but broken (e.g., from testing something that didn't work) such that you are prompted for a passphrase that is never accepted, you need to:
1. Quit interface and delete `%appdata%/Interface <build #>/<username.hifikey>`
2. Restart Interface, set up wallet, and then press the red `DBG: RST WALLET` button as above. Now you are in a truly clean state for wallet setup.

## Tests
1. Launch Interface
2. Set up your Wallet if it isn't already set up
3. Buy the "Test Beach Ball" from the Marketplace
4. Buy the "Cowboy Hat" from the Marketplace
5. Go to "My Purchases"
6. Click on "VIEW CERTIFICATE" on the Cowboy Hat
7. Verify that the certificate display makes sense and that no fields are blank.
8. Click "Close" at the bottom
9. Click on "VIEW CERTIFICATE" on the Test Beach Ball
10. Verify that the certificate display makes sense and that no fields are blank.
11. Click "Close" at the bottom
12. Rez both the Cowboy Hat (which will appear at your hips) and the Test Beach Ball
13. Right click the Test Beach Ball, then click the (i) Context Overlay
14. Verify that a Certificate appears
15. Verify that the certificate display makes sense and that no fields are blank.
16. Zoom out to third-person using your mouse wheel (so you can see the cowboy hat on your hips)
17. Right click the cowboy hat, then click the (i) Context Overlay
18. Verify that a Certificate appears
19. Verify that the certificate display makes sense and that no fields are blank.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4312/HighFidelity-Beta-PR11637-ae1b2bd9312a34f5f0476b5e7f8b7b10837c8580.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4312/HighFidelity-Beta-PR11637-ae1b2bd9312a34f5f0476b5e7f8b7b10837c8580.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by zfox23** [comment]
YOU DA MAN, @YuppyPlays !

**Comment by YuppyPlays** [comment]
Testing complete:

Launch Interface **Check**
Set up your Wallet if it isn't already set up **Check**
Buy the "Test Beach Ball" from the Marketplace **Check**
Buy the "Cowboy Hat" from the Marketplace **Check, also asked me to do passphrase, assumably because multiple purchases, good safety measure.**
Go to "My Purchases" **Check**
Click on "VIEW CERTIFICATE" on the Cowboy Hat **Check**
Verify that the certificate display makes sense and that no fields are blank. **Check**
Click "Close" at the bottom **Check**
Click on "VIEW CERTIFICATE" on the Test Beach Ball **Check**
Verify that the certificate display makes sense and that no fields are blank. **Check**
Click "Close" at the bottom **Check**
Rez both the Cowboy Hat (which will appear at your hips) and the Test Beach Ball **Check**
Right click the Test Beach Ball, then click the (i) Context Overlay **Check**
Verify that a Certificate appears **Check**
Verify that the certificate display makes sense and that no fields are blank. **Check**
Zoom out to third-person using your mouse wheel (so you can see the cowboy hat on your hips) **Check**
Right click the cowboy hat, then click the (i) Context Overlay **Check**
Verify that a Certificate appears **Check**
Verify that the certificate display makes sense and that no fields are blank. **Check**

Solid **Pass** Great work!

**Pull request merged**
