### PR TITLE
Prevent Interface from crashing when a Snapshot upload fails

### PR DESCRIPTION
**Pull request by zfox23**
Previously, `snapshot.js` would attempt to print any error string that it received from the backend. In the case of a snapshot upload error, that error string would be thousands of characters in length. Attempting to print this string would result in Interface freezing. After this fix, that is no longer a problem.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Log in to your High Fidelity account
- Navigate to a "shareable" domain (such as dev-welcome)

### Tests
1. Open the Snap app
    i. Verify that Interface doesn't crash
2. Take a Snapshot using the big red button
    ii.  Wait for 20 seconds. Verify that Interface is still responsive.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8530/HighFidelity-Beta-PR12799-8e46ebf83bace5fb06ae53036ba09d5cff3d2f79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8540/HighFidelity-Beta-PR12799-ac2721fe6a7b410a2d9682008e7ec4150e24f584.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8540/HighFidelity-Beta-PR12799-ac2721fe6a7b410a2d9682008e7ec4150e24f584.dmg

**Pull request merged**
