### PR TITLE
Pr build screenshare bugs

### PR DESCRIPTION
**Pull request by MiladNazeri**
part of https://highfidelity.atlassian.net/browse/DEV-2812

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22714/HighFidelity-Beta-PR16543-9be75e2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22714/HighFidelity-Beta-Interface-PR16543-9be75e2.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22714/HighFidelity-Beta-PR16543-9be75e2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22714/HighFidelity-Quest-Beta-PR16543-9be75e2.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22721/HighFidelity-Beta-PR16543-b99deee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22721/HighFidelity-Quest-Beta-PR16543-b99deee.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22725/HighFidelity-Beta-PR16543-21f4697.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22725/HighFidelity-Quest-Beta-PR16543-21f4697.apk)

**Pull request closed without merging**
