### PR TITLE
Comment out TabletAddressDialog logging of long messages

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/11231/In-HMD-eventually-the-GoTo-app-causes-severe-freezing-lag-spikes-whenever-it-is-opened

Test plan:
- In HMD in a content heavy domain (dev-welcome, eschatology, etc.), open the goto app on the tablet.  You should not notice any long freezes.
- Give the app a little while to load and then close and re-open it a few times.  You should still not see any freezes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6158/app_12127_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6158/HighFidelity-Beta-PR12127-a42b0cf485183186c0c1571e8d26c1e23e583633.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6158/HighFidelity-Beta-PR12127-a42b0cf485183186c0c1571e8d26c1e23e583633.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
