### PR TITLE
Fix MS16113: Use alternate method for creating backup instructions

### PR DESCRIPTION
**Pull request by zfox23**
Attempts to fix [MS16113](https://highfidelity.fogbugz.com/f/cases/16113/Hifikey-file-path-on-backup-instructions-page-is-incorrect) by doing more in-memory operations.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Preconditions
- User has done a clean install
- User is signed into a High Fidelity account
- User has NOT YET set up their wallet

### Tests
1) Select the "Wallet" app from the Tablet/Toolbar
2) Select the "Setup Wallet" button to start the Wallet setup wizard
3) Complete steps 1-3 of Wallet setup wizard
4) On step 4 of the wizard, select the "Open Backup Instructions for Later" button
5) Observe the web browser that opens to file:////users/testmonster/Library/Application%20Support/High%20Fidelity/Interface/backup_instructions.html
6) Under the "Where are my Private Keys Stored?" section, verify that the file path is correct and not "REPLACE_ME"

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10876/HighFidelity-Beta-PR13459-7a5d794.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10876/HighFidelity-Beta-PR13459-7a5d794.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10876/HighFidelity-Beta-Interface-PR13459-7a5d794.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10876/HighFidelity-Beta-PR13459-7a5d794.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10876/HighFidelity-Beta-Interface-PR13459-7a5d794.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
pass @conklin94122 
new file locations look good.

**Pull request merged**
