### PR TITLE
Fix new models not obeying dynamic checkbox

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.manuscript.com/f/cases/19706/New-Model-Entity-dialog-Clicking-Dynamic-does-not-enable-Dynamic-property-on-imported-model

# Test plan

 * From Create, create a model
 * A dialog should pop up. Check the "dynamic" checkbox.
 * Put anything you want into the url field
 * Click "ADD"
 * Confirm that the new model has "dynamic" checked in the properties window
 * Go through the same steps but don't check "dynamic." Confirm that the new model does not have "dynamic" checked.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14596/HighFidelity-Beta-PR14324-8cdc998.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14596/HighFidelity-Beta-PR14324-8cdc998.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14596/HighFidelity-Beta-Interface-PR14324-8cdc998.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14596/HighFidelity-Beta-PR14324-8cdc998.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14596/HighFidelity-Beta-Interface-PR14324-8cdc998.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Dynamic check stays

**Pull request merged**
