### PR TITLE
21231 - Remove About Interface from File menu

### PR DESCRIPTION
**Pull request by Triplelexx**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: eba6c8de5e64721c95083d15a0245d0074ef8147 available at: https://gist.github.com/eff634be5842bc40e6cbb10f865e69ad<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9932-eba6c8d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9932-eba6c8d.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Menu option, About Interface, is removed.  Remaining menu options in File category continue to work as expected.  General smoke tests pass.

**Pull request merged**
