### PR TITLE
Change default avatar to ball and stick avatar

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b6dd2a83587517500e728c05624d9ef431553b8 available at: https://gist.github.com/c9b2748c9f28a0e9702d26ab6f73eda9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10120-8b6dd2a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10120-8b6dd2a.dmg

**Comment by PhilipRosedale** [comment]
Yes, let's get this out and see what people think.  Separately, Ryan can think about how to add indication that it is talking.  The blue person's lips are not visible anyway.

**Comment by huffman** [comment]
To test:

1. Your default avatar should be the stick+ball avatar: https://highfidelity.com/marketplace/items/813addb9-b985-49c8-9912-36fdbb57e04a
1. Try connecting to dev-welcome - you should get a `Protocol version mismatch`
1. Have another user download this PR and connect to your domain with the default avatar. You should see the stick+ball avatar
1. The avatar IK should move as expected when in HMD
1. Confirm that you can use another avatar from the marketplace or a personal avatar

**Comment by kevinmthomasse** [comment]
testing

**Comment by ZappoMan** [comment]
Am I missing something here? How does this force a protocol mismatch?

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:   Attempted to run ```https://highfidelity.com/marketplace/items/813addb9-b985-49c8-9912-36fdbb57e04a``` and crashed without bugsplat.  Loaded PR on my PC and MAC and same result unable to proceed forward with test.

**Comment by huffman** [comment]
@ZappoMan You are right. I could have sworn I saw the changes here, but apparently I didn't push the changes. I reimplemented the changes and pushed them.

**Comment by huffman** [comment]
@kevinmthomasse Were you going to the marketplace and choosing the avatar? I wasn't able to reproduce the crash.

Side-note: My test instructions were not clear so I have updated them. The stick+ball avatar should be the default avatar instead of the blue avatar - you should *not* need to change to it manually.

**Comment by hifi-gustavo** [comment]
Build console output for commit: af11f5f3277250cf11cd6ea58b284d5d73921ba1 available at: https://gist.github.com/c9b2748c9f28a0e9702d26ab6f73eda9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10120-af11f5f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10120-af11f5f.dmg

**Comment by kevinmthomasse** [comment]
@huffman I will attempt the PR with your new instructions as my attempt was to try it manually.  Will re-attempt now.

**Comment by kevinmthomasse** [comment]
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** PARTIAL SUCCESS
**Additional Test Results + Observations**:  Made sure I cleared my settings. The new default avatar loaded correctly.  Confirmed I am not the blue alien avatar and confirmed that my avatar looks like this: ```https://highfidelity.com/marketplace/items/813addb9-b985-49c8-9912-36fdbb57e04a``` (I did NOT need to switch to this avatar manually).  Successfully connected to ```dev-welcome```- I did NOT get a Protocol version mismatch (UNEXPECTED BEHAVIOR).  Installed this PR on my MAC and connected to your my ```music``` domain with the default avatar. Successfully saw the stick+ball avatar.  The avatar IK moved as expected when in HMD.  Confirmed that you can use another avatar from the marketplace or a personal avatar.  SCREEN SHOTS ENCLOSED

**Comment by huffman** [comment]
@kevinmthomasse It's bizarre that you are able to connect to dev-welcome, I just tried it and got a protocol version mismatch. Were you using the new build from last night? (http://cachefly.highfidelity.com/HighFidelity-Beta-PR10120-af11f5f.exe)

**Comment by kevinmthomasse** [comment]
@huffman at work at the moment, tonight I will try installing the new version again on my MAC and clearing all settings to ensure this is accurate.

**Comment by OmegaHeron** [comment]
Tested Windows 10 and Ubuntu 16.04
QA Pass

Make sure you have cleared your settings. In particular, you should be using the default avatar.
**Confirmed clean install, no data for this PR in appdata tree**

Confirm that you are not the blue alien avatar *Pass*

Confirm that your avatar looks like this: https://highfidelity.com/marketplace/items/813addb9-b985-49c8-9912-36fdbb57e04a (you should NOT need to switch to this avatar manually) *Pass*

Try connecting to dev-welcome - you should get a Protocol version mismatch *Pass*

Have another user download this PR and connect to your domain with the default avatar. You should see the stick+ball avatar *Pass*

The avatar IK should move as expected when in HMD *Pass*

Confirm that you can use another avatar from the marketplace or a personal avatar *Pass*

**Pull request merged**
