### PR TITLE
Beta Release 22 - Includes up to Developer Release 5424

### PR DESCRIPTION
**Pull request by cozza13**
This release contains many fixes to RC 21. 

* Fixes to Audio for Windows 7
* Make static control packets class members
* Improve support for audio when input rate != output rate
* Fix crash on startup if default ambient map fails to load
* Fix crash in web entities
* Fix crash related to bouncing between domains.
* Rendering performance improvement.
* Fix crash in removing avatar attachments.
* Fixes crashes in calculateMaterialSize.
* Fix crash in initializing texture transfer thread.
* Fix video driver corruption related to OpenGL.
* Fix crash in scripted timer on shutdown
* Fix the Debug build of Interface on Windows
* Don't check for user membership in a null list of groups
* Loopback local injectors on server echo
* Assignment Client fixes
   * Sets the SessionUUID before emitting the connectedToDomain signal 
   * Could potentially fix multiple issues, but confirmed to fix “Agent AC fails to grab script added from DS assignment run page”
   * Fix warning message in assignment clients: `DependencyManager::get(): No instance available for class controller::ScriptingInterface` 
* Even lower audio latency
* Change the process for home content updates
* Fix an AC script's ability to delete entities
* Reload qml with scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b77636b5bf9783b77d7ac9fd66de167091876706 available at: https://gist.github.com/4d77152876fcfc6fe9d63cad6fd6d947<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8720-b77636b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8720-b77636b.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Unable to move forward with Hydras or edit any objects with hydras.   Successfully able to grab and throw objects with Hydras simply unable to use the edit menus or certain mouse functionality.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |59 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |59 |60
**CPU Buffer Count**: |2950 |3531 |2907
**GPU Buffer Count**: |832 |783 |710
**CPU Memory Usage**: |51630080 |60162048 |47153152
**GPU Memory Usage**: |33062912 |18595840 |27951104
**CPU Texture Count**: |231 |282 |360
**GPU Texture Count**: |187 |167 |244
**GPU Transfer Count**: |51 |6 |50
**CPU Texture Memory Usage**: |1382518816 |1499748904 |1454920200
**GPU Texture Memory Usage**: |116588544 |615727104 |265977856
**GPU Virtual Memory Usage**: |1964710303|1890363443|1819884159
**Triangle Count**: |542025 |555953 |455219
**Triangle Rate**: |33876562 |34747062 |28451187
**API Drawcall Count**: |262 |238 |209
**Drawcall Count**: |263 |281 |209
**Drawcall Rate**: |16437 |17562 |13062
**State Changes Texture Count**:|278 |282 |379
**Pipeline Count**: |44 |42 |73
**Item Opaques**: |285 |544 |169
**Item Translucents**: |21 |43 |107
**Item Lights**: |21 |59 |15
**Timing Opaques**: |0.752 |1.615 |0.678
**Timing Translucents**: |0.028 |0.083 |0.383
**Timing Lighting**: |0.122 |0.161 |0.089
**Render Frame**: |1.704 |3.431 |2.023

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|N/A
**Test 7**|Retest the kick function|N/A
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Being up and edit an objects with hand controllers|FAIL
**Test 10**|Modify a models userdata and make sure it works|Success
**Test 11**|Grab objects in dev-demo|Success

**Comment by kevinmthomasse** [comment]
Thank's to @thoys as I was successfully able to ```Settings-> Advanced movement for Handcontrollers`   enabled```.  I was now able to move around so there was NOT an issue with that after all now that this option was successfully selected however I was still UNABLE to edit the UI buttons with the Hydras.  I am able to press 4 on the controller to get a menu and use the joystick to select menu items and the fire button however not able to manipulate the UI buttons with the Hydras.

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** N/A
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** N/A
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Standard disclaimer - playaPerformanceTest.js does not run long enough on an i5 based system to fully load scenes.

Desktop Mode 1600x900 maximized window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |58 |60
**CPU Buffer Count**: |4018 |3925 |3303
**GPU Buffer Count**: |1598 |1354 |1045
**CPU Memory Usage**: |65331200 |64450560 |64434176
**GPU Memory Usage**: |53047296 |43745280 |44888064
**CPU Texture Count**: |301 |290 |291
**GPU Texture Count**: |267 |249 |255
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |73257268 |243498024 |122988376
**GPU Texture Memory Usage**: |0 |0 |0
**GPU Virtual Memory Usage**: |1206922067|1897320773|1151751490
**Triangle Count**: |718372 |1358252 |318184
**Triangle Rate**: |44898250 |79897176 |19886500
**API Drawcall Count**: |169 |498 |187
**Drawcall Count**: |170 |541 |186
**Drawcall Rate**: |10625 |31823 |11625
**State Changes Texture Count**:|192 |470 |270
**Pipeline Count**: |36 |40 |50
**Item Opaques**: |180 |451 |183
**Item Translucents**: |38 |70 |34
**Item Lights**: |18 |81 |10
**Timing Opaques**: |0.625 |1.536 |0.625
**Timing Translucents**: |0.047 |0.096 |0.192
**Timing Lighting**: |0.122 |0.197 |0.328
**Render Frame**: |1.616 |3.484 |2.315

DK2
**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |4911 |4544 |3828
**GPU Buffer Count**: |2190 |1861 |1193
**CPU Memory Usage**: |102383616 |80396288 |76996608
**GPU Memory Usage**: |82018304 |57233408 |47185920
**CPU Texture Count**: |431 |419 |308
**GPU Texture Count**: |403 |384 |301
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |60768564 |231009320 |72492888
**GPU Texture Memory Usage**: |0 |0 |0
**GPU Virtual Memory Usage**: |1903672176|2594070878|1481998580
**Triangle Count**: |1367015 |2052266 |1472521
**Triangle Rate**: |113917916 |157866615 |133865545
**API Drawcall Count**: |268 |363 |384
**Drawcall Count**: |627 |795 |949
**Drawcall Rate**: |52250 |61153 |86272
**State Changes Texture Count**:|273 |364 |507
**Pipeline Count**: |42 |43 |63
**Item Opaques**: |300 |475 |256
**Item Translucents**: |36 |60 |52
**Item Lights**: |20 |82 |15
**Timing Opaques**: |0.853 |1.465 |1.028
**Timing Translucents**: |0.049 |0.068 |0.193
**Timing Lighting**: |0.168 |0.177 |0.19
**Render Frame**: |2.115 |2.991 |2.553

Got notice new content is available, option to download or not - not was default.  It was clear what would happen if I updated content and that a backup would be made.

Re-test that missing default ambient texture gives no crash.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Ok
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Ok
**Test 6**|Test group functions|N/A
**Test 7**|Retest the kick function|N/A
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Being up and edit an objects with hand controllers|N/A
**Test 10**|Modify a models userdata and make sure it works|N/A
**Test 11**|Grab objects in dev-demo|N/A

5 Run CPU use comparison 5407 (blue) vs this PR 8720 (red)

5407vs8720-10042k16

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e46ed3cac6bbf8144bea6c75b8b2865ee65ead0 available at: https://gist.github.com/4d77152876fcfc6fe9d63cad6fd6d947<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8720-2e46ed3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8720-2e46ed3.dmg

**Comment by OmegaHeron** [comment]
Re-test Windows 10 - i5 6500 CPU - GTX 970 GPU

Audio = Ok, only tested Windows 10 - no access to Win 7/8.  Specifically tested changing devices among the 3 I have connected and played with default sample rates in windows sound control panel.  Was unable to find any combo leading to audio fail, but, I wasn't able to before either as I'm on Win 10.

All other tests same as seen with first test result listed above.

CPU use unchanged.

**Pull request merged**
