### PR TITLE
Fixing texture storage allocation on OSX/GL 4.1

### PR DESCRIPTION
**Pull request by jherico**
This fixes the black screen on macs in caused by the recent changes to GLBackendTexture.cpp

### CODE REVIEW

**Comment by jherico** [comment]
## Testing

* Smoke test on OSX and PC.  Ideally on nVidia, AMD, and Intel on PC
* Verify Mac does not render with a black screen

**Comment by hifi-gustavo** [comment]
Build console output for commit: 407e0c0dd74fa260a08de6e05e2c48bdd7ca2c46 available at: https://gist.github.com/ea38a3ca876795772059137d2ef6e48b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.dmg

**Comment by Atlante45** [comment]
No more black screen and I see the skybox correctly, but after a few second it switches to something like that:
hifi-snap-by-c-on-2016-04-22_16-06-34

**Comment by jherico** [comment]
@Atlante45 OK, can you try it again?

**Comment by Atlante45** [comment]
@jherico Hooray it works!

**Comment by jherico** [comment]
@Atlante45 I meant after the build completes.  if it works now it's a fluke.

**Comment by Atlante45** [comment]
@jherico Will test again with the PR build, but I pulled your branch and it was working.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 472d3dc45f1e851049c1129e2360772cdbf5a62e available at: https://gist.github.com/ea38a3ca876795772059137d2ef6e48b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d87c92baee34a6d555961266d9d02ced6fd74717 available at: https://gist.github.com/ea38a3ca876795772059137d2ef6e48b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7745.dmg

**Comment by Atlante45** [comment]
Passes smoke test on Mac and PC (Nvidia for both)

**Pull request merged**
