### PR TITLE
BUGZ-1522: Snap app on tablet is blocked when saving/canceling out of its Settings page RC 84

### PR DESCRIPTION
**Pull request by danteruiz**
ticket - https://highfidelity.atlassian.net/browse/BUGZ-1522

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21451/HighFidelity-Beta-PR16232-59c1371.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21451/HighFidelity-Beta-Interface-PR16232-59c1371.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21451/HighFidelity-Beta-PR16232-59c1371.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21451/HighFidelity-Quest-Beta-PR16232-59c1371.apk)

**Comment by AndySeattle** [comment]
build this

**Pull request merged**
