### PR TITLE
Do Not Merge -- interface decides on entityIDs rather than bouncing a temporary id  through entity server

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
It's likely I've broken some scripts, with this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f9d46b0cb5af090a4f668c473049ed4e5eb57c17 available at: https://gist.github.com/24f05809a9202237b47e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4916.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4916.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b32e069f1da043662db984a0ace737bdc54ea640 available at: https://gist.github.com/24f05809a9202237b47e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4916.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4916.dmg

**Comment by ZappoMan** [comment]
Lets discuss in the morning. I think we should keep the isKnownID and creatorTokenID properties of the EntityItemID as is.

**Comment by ZappoMan** [comment]
I definitely dont think we should be getting rid of the EntityItemID class completely. We should keep that class and just have it encapsulate the quuid.

**Comment by ZappoMan** [comment]
One thing we MUST do before we merge this is separate out the PacketTypeEntityAddOrEdit into PacketTypeEntityAdd and PacketTypeEntityEdit -- because by moving to QUUIDs we've lost the knowledge of whether or not the server should assume the editing client KNOWS that the entity exists or not... 

Without changing adds to be a different message than edits we will end up assuming a bad ID in an edit is actually an add...

**Pull request closed without merging**
