### PR TITLE
Faster HRTF

### PR DESCRIPTION
**Pull request by kencooke**
New AVX2 implementation of FIR_1x4() achieves 24 FLOPS per clock on HSW/BDW/SKL
Removed old AVX implementation
32-byte alignment of SIMD buffers and tables
Fixed the poorly optimized code produced by GCC -O2

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

Using Sandbox from this build, verify that spatialized audio sources (real/simulated avatars) still sound correct. This PR should only affect performance.

Using a Linux server, when mixing a large number of real/simulated avatars, the audio-mixer CPU usage should be significantly lower in this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a42ac89a6d83c909a45b75b31361c65243563836 available at: https://gist.github.com/f33ab05084c315667dc5491ca71b8691<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9288-a42ac89.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9288-a42ac89.dmg

**Comment by OmegaHeron** [comment]
Working on Linux server tests, but will be a bit for compile and test server setup.  claudioshg is doing the smoke tests.

**Comment by OmegaHeron** [comment]
Fairly informal (i.e. I didn't attach tracers and just eyeballed CPU stats via htop) Linux results look good.  I used a 25 AV swarm and compared AC audio process load in this PR vs current master  There's definite improvement.  In so far as a specific value of improvement... harder to tell.  I'd really need to setup a specific AC audio server vs the simple setup I have here on LAN to be sure.  But - it's a worthy reduction of CPU none the less.

I'm going to run some more tests just to get better numbers for my own knowledge and glorious future knowledge for provisioning AC audio servers, but, server side = QA Pass.  Client tests should be coming soon.  As far as I can tell from server side that should be fine as well, but, with only one properly working ear at the moment (long story) -- best to have another confirm.

::kicks bluemen off his roof::

hifi-snap-by-omegaheron-on-2016-12-30_18-59-58

**Comment by claudioshg** [comment]
## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Pull request merged**
