### PR TITLE
DOC-68: Fix the JSDoc @hideconstructor tag

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
And update all classes' JSDoc accordingly.

Case: https://highfidelity.atlassian.net/browse/DOC-68

Note: No executable code changes other than JSDoc generation.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22822/HighFidelity-Beta-PR16581-2dd9814.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22822/HighFidelity-Beta-Interface-PR16581-2dd9814.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22822/HighFidelity-Beta-PR16581-2dd9814.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22822/HighFidelity-Quest-Beta-PR16581-2dd9814.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22822/HighFidelity-Beta-PR16581-2dd9814.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22822/HighFidelity-Beta-Interface-PR16581-2dd9814.exe

**Comment by hd23408** [comment]
Closing in favor of https://github.com/highfidelity/hifi/pull/16583

**Pull request closed without merging**
