### PR TITLE
Fix icon name change in Asset Browser

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes a bug in the Asset Browser where the baked status icon wouldn't be displayed.

### CODE REVIEW

**Comment by Atlante45** [comment]
# Test Plan:
- Upload a simple FBX to the Asset Server
- Once it is baked, it should show a checkmark icon on the right.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3871/HighFidelity-Beta-PR11520-caac305c4d2e586e9f212d621be778d033699d70.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Upload a simple FBX to the Asset Server | Pass
Once it is baked, it should show a checkmark icon on the right. | Pass

e9ba2b1e-1f90-4e9a-8595-76dceecf150d

All good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by anshuman64** [comment]
Sorry, not gonna go in this time :( Too much going on in this RC already

**Pull request closed without merging**
