### PR TITLE
Fix for audio continuing on destroyed Web 3D overlays (RC70.1)

### PR DESCRIPTION
**Pull request by jherico**
Hotfix version of #13638  

See that PR for testing and notes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11421/HighFidelity-Beta-PR13647-70cf890.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11421/HighFidelity-Beta-PR13647-70cf890.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11421/HighFidelity-Beta-Interface-PR13647-70cf890.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11421/HighFidelity-Beta-PR13647-70cf890.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11421/HighFidelity-Beta-Interface-PR13647-70cf890.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 @qliacoombs @Qliemillar 

Audio no longer persists once the script has ended.

**Pull request merged**
