### PR TITLE
switch Interface from bugsplat to backtrace

### PR DESCRIPTION
**Pull request by sethalves**
- switch Interface from bugsplat to backtrace

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6586/app_12252_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6586/HighFidelity-Beta-PR12252-c01c03a62ed80b4b1d450bad7e1c3c85ff37ceed.dmg

**Comment by sethalves** [comment]
build this please, you wretched automaton

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6591/app_12252_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6591/HighFidelity-Beta-PR12252-c01c03a62ed80b4b1d450bad7e1c3c85ff37ceed.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6596/app_12252_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6596/HighFidelity-Beta-PR12252-c01c03a62ed80b4b1d450bad7e1c3c85ff37ceed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6596/HighFidelity-Beta-PR12252-c01c03a62ed80b4b1d450bad7e1c3c85ff37ceed.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6627/app_12252_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6627/HighFidelity-Beta-PR12252-b04629c39bad53b262ef33ed2d49566bba320687.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6627/HighFidelity-Beta-PR12252-b04629c39bad53b262ef33ed2d49566bba320687.exe

**Pull request closed without merging**
