### PR TITLE
Don't expose raw pointer to the display plugin

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by jherico** [comment]
https://app.asana.com/0/27650181942747/111649472166206

**Comment by jherico** [comment]
### Testing

Smoke test, very startup / shutdown, switching of display plugins all functions as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52e3474011d6ec78f4ae5c1b7d768f4c6335735c available at: https://gist.github.com/1bc0ba68ac97c938a77ec5021e6d5bd1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7759.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7759.dmg

**Comment by ZappoMan** [comment]
```
54>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\PluginContainerProxy.cpp(58): error C2440: 'return' : cannot convert from 'DisplayPluginPointer' to 'const DisplayPlugin *' [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 847620c876cafa9e485f5bcb6bb3744e16abfa08 available at: https://gist.github.com/1bc0ba68ac97c938a77ec5021e6d5bd1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f946c458292dd0cb12f5aea35ddb87afdd9775cb available at: https://gist.github.com/1bc0ba68ac97c938a77ec5021e6d5bd1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf8cec7a92faa661bc7c23857132948b81317ef5 available at: https://gist.github.com/1bc0ba68ac97c938a77ec5021e6d5bd1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c54d0bc9938dcd4106953c05e38620d6eb62b7aa available at: https://gist.github.com/1bc0ba68ac97c938a77ec5021e6d5bd1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7759.dmg

**Comment by OmegaHeron** [comment]
I took a, brief, look at this - it certainly improves experience running Interface with an i5 cpu and is smoother on i7 as well in so far as loading scenes, moving while loading etc.  I'll do full eval test in a bit.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Edit** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Attempted multiple quick start and shutdowns of Interface to which after the thrid attempt on ```playa```, upon trying to restart the Interface it would not load. Closed PR Sandbox and reloaded PR Sandbox and was able to successfully continue. No additional issues.  Log file attached for deeper analysis.

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |57 |48
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |56 |46
**CPU Buffer Count**: |4906 |3503 |2499
**GPU Buffer Count**: |816 |597 |614
**CPU Memory Usage**: |47412728 |43368588 |39998404
**GPU Memory Usage**: |23134208 |20583180 |17518080
**CPU Texture Count**: |288 |147 |129
**GPU Texture Count**: |172 |112 |91
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |380567312 |141572948 |233323348
**GPU Texture Memory Usage**: |618714347 |410337751 |339053833
**GPU Virtual Memory Usage**: |618714347|410337751|339053833
**Triangle Count**: |446336 |456303 |397610
**Triangle Rate**: |27896000 |26841352 |23388823
**API Drawcall Count**: |208 |117 |131
**Drawcall Count**: |212 |114 |131
**Drawcall Rate**: |13250 |6705 |7705
**State Changes Texture Count**:|199 |76 |94
**Pipeline Count**: |24 |27 |22
**Item Opaques**: |242 |231 |656
**Item Translucents**: |9 |12 |28
**Item Lights**: |23 |38 |1
**Timing Opaques**: |1661 |1031 |3350
**Timing Translucents**: |125 |43 |290
**Timing Lighting**: |135 |165 |93
**Render Frame**: |2743 |2083 |4820
[hifi-log.txt](https://github.com/highfidelity/hifi/files/260270/hifi-log.txt)

**Pull request merged**
