### PR TITLE
suppress Interface notification for DS decryption error

### PR DESCRIPTION
**Pull request by birarda**
- suppress login error message when connecting to a domain with a recently generated user key pair

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6454/app_12213_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6455/app_12213_PR.apk

**Comment by birarda** [comment]
#### Test Plan

To test this, you will need the Interface client from this PR, the Interface client from latest master, and a server running latest master (referenced in the test plan as "the test server"). This PR should be protocol compatible with master (it is at the time of writing this test plan).

1. Run Interface from this PR and login to your High Fidelity account. Confirm you can connect to the test server. Close Interface.
2. Run Interface from master and login to your High Fidelity account. Confirm you can connect to the test server. Confirm that while connecting, you see a notification with the following message "Error decrypting username signature". Close Interface.
3. Run Interface from this PR again. Confirm you can connect to the test server. Confirm that you do NOT see the notification stating "Error decrypting username signature". Close Interface.
4. Run Interface from master and login to your High Fidelity account. Confirm you can connect to the test server. Confirm that while connecting, you see a notification with the following message "Error decrypting username signature". Close Interface.
5. Change the test server permissions to specifically deny connect access from your user.
6. Run Interface from this PR again. Confirm that you cannot connect to the test server and that you are presented with a notification "You lack the required permissions to connect". Close Interface.
7. Change the test server permissions to allow access from your user but do not allow your user to bypass the maximum user restriction. Set the number of maximum users to 1.
8. Connect another authorized user to the test server so it is at max capacity.
9. Run Interface from this PR again. Confirm that you cannot connect to the test server and that you are presented with a notification "Too many connected users". 
10. Attempt to connect to a server with a protocol mismatch against this PR (this should be true for stable domains). Confirm that you are presented with the protocol version mismatch notification.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6455/HighFidelity-Beta-PR12213-a97b4b010dbc2c32089000d153fea86ac0209e47.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6455/HighFidelity-Beta-PR12213-a97b4b010dbc2c32089000d153fea86ac0209e47.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. The "Error decrypting username signature" message does not appear in the master or PR builds. All other messages were visible.

@conklin94122

**Comment by birarda** [comment]
@sbennett77 Let me outline the steps for that test separately just to make sure they are correct.

I just did this test locally an confirmed I saw the notification on master.

1. Run Interface from this PR. Log into your account. Connect to dev-welcome. Make sure you are connected. Close Interface from this PR.
2. Run Interface from master. Make sure you are logged in. Connect to dev-welcome. On desktop, in the top right "Connection Refused: Error decrypting username signature" should appear.
3. Run Interface from this PR. Connect to dev-welcome. On desktop, in the top right "Connection Refused: Error decrypting username signature" should NOT appear.

**Comment by sbennett77** [comment]
Retesting.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
