### PR TITLE
Fix the crash when Particle system entities are created and removed quickly

### PR DESCRIPTION
**Pull request by samcake**
This PR fixes the crash happening with the Gun when firing it.
The particle System Entity was created/updated/removed very quickly and there was no proper check/cleaning of the pointer after being removed.

We checked that the correct pattern is applied similarly to all the Entity Item Renderable types and Avatar.
Making sure the kept render::ItemID is cleared right after the item is removed from the scene.

Introduced 2 convenient functions in render::Item to clear and check validity of an ItemID.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e39cc7753a7cfc3d15a887ccc7350b60c0e399e available at: https://gist.github.com/16425fb731cd71bbfa1b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7169.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7169.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3cdc5117f27be74ef52999b18adb672a3630e4b available at: https://gist.github.com/16425fb731cd71bbfa1b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7169.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7169.dmg

**Comment by ZappoMan** [comment]
:+1:

**Comment by cozza13** [comment]
I will test

**Comment by cozza13** [comment]
tested with the pistol and it works!

**Comment by cozza13** [comment]
Baym!

**Pull request merged**
