### PR TITLE
Case 22387 : System cursor in desktop mode instead of rendering texture from Displayplugin

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.manuscript.com/f/cases/22378/Need-to-use-the-SYSTEM-Cursor-in-Desktop-instead-of-the-displayed-texture-from-DisplayPLugin

Removing system mouse override and cursor rendering  for non hmd devices. When running on low end devices or eco mode the mouse cursor updates cause jitter and on some macs a mouse trail.  

Test case:

1. Mouse cursor should be smooth on all "desktop" mode devices.
2. The cursor should be rendered by the OS 
3. None of the mouse interactions should be affected

### CODE REVIEW

**Comment by amerhifi** [comment]
Please do not merge!  Just sharing code change with Sam. Will be modifying this  to test not doing a separate mouse render.  Upcoming change will check if the device is non hmd and then bypass rendering the mouse.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19046/HighFidelity-Beta-PR15472-eff5cc6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19046/HighFidelity-Quest-Beta-PR15472-eff5cc6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19046/HighFidelity-Beta-PR15472-eff5cc6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19046/HighFidelity-Beta-Interface-PR15472-eff5cc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19046/HighFidelity-Beta-PR15472-eff5cc6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19046/HighFidelity-Beta-Interface-PR15472-eff5cc6.exe

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19070/HighFidelity-Beta-PR15472-2d1e9fd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19070/HighFidelity-Quest-Beta-PR15472-2d1e9fd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19070/HighFidelity-Beta-PR15472-2d1e9fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19070/HighFidelity-Beta-Interface-PR15472-2d1e9fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19070/HighFidelity-Beta-PR15472-2d1e9fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19070/HighFidelity-Beta-Interface-PR15472-2d1e9fd.exe

**Pull request closed without merging**
