### PR TITLE
Add virtual keyboard for steam username collision

### PR DESCRIPTION
**Pull request by Atlante45**
- Adds support for the virtual keyboard to the window for username collision during a Steam login.
- Inform user their Steam informations will not be shared

https://highfidelity.fogbugz.com/f/cases/1964/Virtual-keyboard-covers-textfield-in-Steam-username-taken-popup
https://highfidelity.fogbugz.com/f/cases/1863/Add-language-to-Steam-login-page-that-your-username-will-not-be-exposed

### CODE REVIEW

**Comment by Atlante45** [comment]
@cozza13 Can you test this one?

**Comment by hifi-gustavo** [comment]
Build console output for commit: c40a027108ce01298585fa29865c362108f8d7e4 available at: https://gist.github.com/33a08e0392ccbe221502cc9d3d96023c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-c40a027.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-c40a027.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0858b3fc8ddbd75b5d6679874541ee8ff35fef5b available at: https://gist.github.com/33a08e0392ccbe221502cc9d3d96023c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-0858b3f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-0858b3f.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0858b3fc8ddbd75b5d6679874541ee8ff35fef5b available at: https://gist.github.com/33a08e0392ccbe221502cc9d3d96023c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-0858b3f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8840-0858b3f.dmg

**Comment by howard-stearns** [comment]
I spoke with Ryan and Alan. The rules are:
-  if there is only one input and it is text, the keyboard should just be always open in HMD.
- if there are a mix of inputs, the keyboard should go up and down (in HMD) depending on whether you're in a text field.
- otherwise it's vague. In this case, there will be at least two text inputs (username and password), right?

Since it's already been QA approved, I'll dev-approve as well. But if we get reports of flickering when you go from username to password, or other issues from going up and down, we'll want to change it in the future.

**Pull request merged**
