### PR TITLE
RC66.1: don't try to build convex hulls with nan data

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Similar to #12974 against `hifi/master`...

We've been seeing a crash for bad data submitted to Bullet's `btConvexHullShape`.  Unfortunately we don't have a repro recipe for the content that tickles that crash.  This is a theoretical fix which is bolstered by evidence found in the visual studio `dmp` filed of one of the recorded crashes.

So nothing has changed and the **test plan** is to make sure objects that use convex hull collision shapes still collide correctly:

**(1)** Make a model entity item and for shape select either **Basic - Whole model** or else **Good - Sub-meshes** for the collision shape type.

**(2)** Make sure the model collides as one big convex hull around its shape (**Basic**) or as convex hulls around each of its various sub-meshes (**Good**).  That is, bump the object with your avatar, or grab a dynamic box and bump that into the model to measure its effective collision boundary.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9070/app_12978_PR_95d07345d46587a297d1c2cc5e52226b7db3f449.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9070/HighFidelity-Beta-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9070/HighFidelity-Beta-Interface-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9096/app_12978_PR_95d07345d46587a297d1c2cc5e52226b7db3f449.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9096/HighFidelity-Beta-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9096/HighFidelity-Beta-Interface-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9096/HighFidelity-Beta-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9106/HighFidelity-Beta-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9106/HighFidelity-Beta-Interface-PR12978-95d07345d46587a297d1c2cc5e52226b7db3f449.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Models looks good and react well to their respective collisions.

**Pull request merged**
