### PR TITLE
use current wearable index, not joint index!

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/18061/Avatar-favorites-cannot-be-moved-to-a-different-joint-At-Save-the-wearable-jumps-to-the-original-joint

**Test plan**

1.  Open High Fidelity
2.  Select Last Legends: Male as avatar
3.  Click Avatar on the toolbar/tab
4.  Click the Wearables 'hat' icon
5.  On the Adjust Wearables dialog select the Fedora.fbx from the Wearable list
6.  On the Joint list, select LeftHandMiddle4 (Or standard/common joint).
7.  Click the SAVE button
8.  Ensure joint change was applied

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13105/HighFidelity-Beta-PR14025-e5b7b7f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13105/HighFidelity-Beta-PR14025-e5b7b7f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13105/HighFidelity-Beta-Interface-PR14025-e5b7b7f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13105/HighFidelity-Beta-PR14025-e5b7b7f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13105/HighFidelity-Beta-Interface-PR14025-e5b7b7f.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13520/HighFidelity-Beta-PR14025-e5b7b7f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13520/HighFidelity-Beta-PR14025-e5b7b7f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13520/HighFidelity-Beta-Interface-PR14025-e5b7b7f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13520/HighFidelity-Beta-PR14025-e5b7b7f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13520/HighFidelity-Beta-Interface-PR14025-e5b7b7f.exe

**Comment by qlistephens95** [comment]
currently testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . Verified that when attaching wearable to joint location, wearable attaches properly.

**Pull request merged**
