### PR TITLE
Commerce: Extended Certificates - Apps!

### PR DESCRIPTION
**Pull request by zfox23**
This PR implements the second phase of Extended Certificate Support to Interface. You can now purchase certified Apps from the Marketplace. Purchased Apps will appear in My Purchases.

Other, minor changes:
- Quick font fix
- Better loading screen during Checkout

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7444/app_12480_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7444/HighFidelity-Beta-PR12480-e3ccfc9935733f8579944bcaa97c24b9090a0990.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7444/HighFidelity-Beta-PR12480-e3ccfc9935733f8579944bcaa97c24b9090a0990.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7447/HighFidelity-Beta-PR12480-249f0568a14157e8a48f0071b65283127e9f93d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7447/HighFidelity-Beta-PR12480-249f0568a14157e8a48f0071b65283127e9f93d1.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7481/app_12480_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7481/HighFidelity-Beta-PR12480-5ee28297f33693ce5c90e9fc1745cbdd7f461110.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7481/HighFidelity-Beta-PR12480-5ee28297f33693ce5c90e9fc1745cbdd7f461110.exe

**Comment by zfox23** [comment]
## Test Plan

## Notes
- This test is very similar to the test plan of #12444.
- This test is only required to be performed in Desktop mode. It is not necessary to run this entire test plan in both HMD and Desktop modes. If, at the tester's discretion, a step during the test appears as though it might behave differently in HMD, please let me know and perform the step in HMD mode.

## Prerequisites
- You have a High Fidelity account on the Staging backend environment
- Your environment variables are set up to point Interface/Sandbox at the Staging backend environment
    - `SETX HIFI_METAVERSE_URL https://staging.highfidelity.com`
- You have a valid Wallet that you have authenticated
- You do not have any Apps Purchases tied to your Wallet

## Tests

### Test E: Purchasing Apps

1. Open the Marketplace. Go to the item page for an app (such as "Zach's App - RED VERSION" on Staging). Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
2. Click "CONFIRM PURCHASE".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **app** [marketplace item] has been added..."
    iii. Verify that you see a "[download icon] INSTALL" button, and that it is enabled.
    iv. Verify that DO NOT see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
3. Open your Running Scripts window (CTRL+J) and move it to one side of the Checkout window.
4. Open your logs (CTRL+SHIFT+L) and expand the window to be large.
5. In Explorer, open the following directory: `%AppData%\High Fidelity - PR12480\Interface`
    i. Verify that you do NOT see an "Apps" folder in that directory
6. On the "Thank you for your purchase" screen, click the "INSTALL" button.
    i. Verify that your logs show that the app has started running
        - If you have just installed "Zach's App - RED VERSION", look for a little surprise :)
    ii. Verify that your "Running Scripts" window shows the script corresponding to the app you just installed
        - If you have just installed "Zach's App - RED VERSION", that script should be `simpleApp_red.js`
    iii. Verify that your Explorer window shows a new folder called "Apps". Open the folder and verify that there is one file inside that folder.
    iv. Verify that the "INSTALL" button has changed to "OPEN"
7. Click the "OPEN" button.
    i. Verify that the app's main screen has opened. Close the app.
8. Open My Purchases.
    i. Verify that the app you just purchased appears at the top of the Purchases list.
    ii. Verify that there are two buttons on that app's card: "OPEN" and "UNINSTALL"
9. Click the "OPEN" button.
    i. Verify that the app's main screen has opened. Close the app.
10. Open My Purchases. Click the "UNINSTALL" button on the card corresponding to the app you just bought.
    i. Verify that the two buttons are replaced by a single enabled "INSTALL" button.
    ii. Verify that the script corresponding to the purchased app has disappeared from the Running Scripts window.
    iii. Verify that there are now zero files in the `%AppData%\High Fidelity - PR12480\Interface\Apps` directory
11. Click the "INSTALL" button corresponding to the app you just bought.
    i. Verify that your logs show that the app has started running
        - If you have just installed "Zach's App - RED VERSION", look for a little surprise :)
    ii. Verify that your "Running Scripts" window shows the script corresponding to the app you just installed
        - If you have just installed "Zach's App - RED VERSION", that script should be `simpleApp_red.js`
    iii. Verify that your Apps folder shows one file inside that folder.
    iv. Verify that there are now two buttons on that app's card: "OPEN" and "UNINSTALL"
12. Open the Marketplace. Go to the item page for the same app as in (1). Click "Purchase".
    i. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "VIEW THIS ITEM IN MY PURCHASES" button, and a borderless "CANCEL" button.
13. Click "VIEW THIS ITEM IN MY PURCHASES"
    i. Verify that you are taken to the My Purchases screen, and that the filter bar contains the text corresponding to the title of the item you were about to buy.
    ii. Verify that there are two buttons on that card - "OPEN" and "UNINSTALL"
14. Open the Marketplace. Go to the item page for a different app from (1), such as "Zach's App - BLUE VERSION" on Staging. Click "Purchase".
    i. Verify that you see the "Review Purchase" screen.
    ii. Verify that you see an image [KNOWN BUG - image won't appear on Staging, do not report!], the title of the item, the price of the item, a blue "CONFIRM PURCHASE" button, and a borderless "CANCEL" button.
15. Click "CONFIRM PURCHASE".
    i. Verify that you see the "Thank you for your order!" screen.
    ii. Verify that you see the text "The **app** [marketplace item] has been added..."
    iii. Verify that you see a "[download icon] INSTALL" button, and that it is enabled.
    iv. Verify that DO NOT see red text that reads "You do not have Certified Rez permissions in this domain. What does 'Rez' mean?"
16. Click "View this item in My Purchases"
    i. Verify that you are taken to the My Purchases screen, and that the item you just purchased appears at the top of the list.
17. Click the "INSTALL" button corresponding to the app you just bought.
    i. Verify that your logs show that the app has started running
        - If you have just installed "Zach's App - BLUE VERSION", look for a little surprise :)
    ii. Verify that your "Running Scripts" window shows the script corresponding to the app you just installed
        - If you have just installed "Zach's App - BLUE VERSION", that script should be `simpleApp_blue.js`
    iii. Verify that your Explorer window shows one file in the Apps folder.
    iv. Verify that there are now two buttons on that app's card: "OPEN" and "UNINSTALL"
18. Click the "INSTALL" button corresponding to the FIRST app you bought.
    i. Verify that your logs show that the app has started running
    ii. Verify that your "Running Scripts" window shows the script corresponding to the app you just installed
    iii. Verify that your Explorer window shows **two** files in the Apps folder.
    iv. Verify that there are now two buttons on that app's card: "OPEN" and "UNINSTALL"

**Comment by changxc** [comment]
looks good to me!

**Comment by qlimnavarro** [comment]
Currently testing.

**Comment by qlimnavarro** [comment]
Pass. @conklin94122

**Pull request merged**
