### PR TITLE
Added Vive pucks as an input channel

### PR DESCRIPTION
**Pull request by seefo**
This PR adds standard and action support for tracked objects.  The main purpose is to allow the input recording tool to record and playback vive trackers position and orientations.  Test plan can be found below in @hyperlogic's comment.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2159/HighFidelity-Beta-PR11091-36d51bf7fb9889af38c7d8497ba5f431ab60c745.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2159/HighFidelity-Beta-PR11091-36d51bf7fb9889af38c7d8497ba5f431ab60c745.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2162/HighFidelity-Beta-PR11091-9a818795e299f84ecd9dbda50bd0f51a62edcb0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2162/HighFidelity-Beta-PR11091-9a818795e299f84ecd9dbda50bd0f51a62edcb0b.exe

**Comment by seefo** [comment]
Deleting the links to the old builds while gustavo builds the new one.

**Comment by seefo** [comment]
Deleting the links to the old builds while gustavo builds the new one.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2167/HighFidelity-Beta-PR11091-1046647dcbcb927ebec3b3c671190f0c6e9e0e4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2167/HighFidelity-Beta-PR11091-1046647dcbcb927ebec3b3c671190f0c6e9e0e4c.exe

**Comment by hyperlogic** [comment]
QA test plan:
  * with vive trackers attached run the `scripts/developer/tests/viveTrackedObjects.js` interface script.  When running you should be able to see the tracker's position and orienation as blue wire frame circles.
  * Then use the input recorder tool, `scripts/developer/inputRecording.js`.  Then record the pucks.
  * Then use the input recorder tool to play back a puck recording.  You should see the pucks as represented by blue wireframe spheres move along their recorded paths.

**Pull request closed without merging**
