### PR TITLE
Potential bug correction when constructing eye position from Z-buffer depths in shaders

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes a potential small visual bug in any shader that was reconstructing a pixel's position in eye space from that pixel's depth buffer value, when seen through HMD with the present thread faster than the game thread.

# Test plan
Use tests _engine/render/effect/haze_ and all _engine/render/effect/material_ sub tests.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8482/HighFidelity-Beta-PR12784-e3908662fe20ad42620b695d15f3a99f111b3f3e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8482/HighFidelity-Beta-PR12784-e3908662fe20ad42620b695d15f3a99f111b3f3e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
All materials look good and as expected. The rift station did notice https://highfidelity.manuscript.com/f/cases/13024 occur, but as this does not relate to pr, it still passes.

**Pull request merged**
