### PR TITLE
Whitelist functionality for tablet apps

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4698/HighFidelity-Beta-PR11751-2cd76be6c487de87bbdfa58fdf54e1d653311fba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4698/HighFidelity-Beta-PR11751-2cd76be6c487de87bbdfa58fdf54e1d653311fba.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4728/HighFidelity-Beta-PR11751-b7f31eb5b9cabf53c205178895aed8bb50ba48b0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4728/HighFidelity-Beta-PR11751-b7f31eb5b9cabf53c205178895aed8bb50ba48b0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4767/HighFidelity-Beta-PR11751-1a58aee385ad8c3bc68ac4b8d7da519b8d703eec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4767/HighFidelity-Beta-PR11751-1a58aee385ad8c3bc68ac4b8d7da519b8d703eec.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4781/HighFidelity-Beta-PR11751-25df649b44fac06719208228c24657c5444d2d6d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4850/HighFidelity-Beta-PR11751-e9d19878692dc8df2d666c3a1e3fedb4da6217c0.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4851/HighFidelity-Beta-PR11751-e9d19878692dc8df2d666c3a1e3fedb4da6217c0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4852/HighFidelity-Beta-PR11751-7bf1b176d72215077545d7fbac9743b24e26aa76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4852/HighFidelity-Beta-PR11751-7bf1b176d72215077545d7fbac9743b24e26aa76.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4880/HighFidelity-Beta-PR11751-8f85c7650b88a7e5e91a90f66f4b09d35fa25b02.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4880/HighFidelity-Beta-PR11751-8f85c7650b88a7e5e91a90f66f4b09d35fa25b02.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4894/HighFidelity-Beta-PR11751-d71fd151c5b802c66479ad4fae6c960fc7b7891c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4894/HighFidelity-Beta-PR11751-d71fd151c5b802c66479ad4fae6c960fc7b7891c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4963/HighFidelity-Beta-PR11751-0ad399974132417c0181d35af6dd46806730022e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4963/HighFidelity-Beta-PR11751-0ad399974132417c0181d35af6dd46806730022e.exe

**Comment by ZappoMan** [comment]
I believe this is all included in Zach's PR #11815

**Pull request closed without merging**
