### PR TITLE
Fix NVTT for mac

### PR DESCRIPTION
**Pull request by Atlante45**
I fixed up the archive we have on S3 so mac builds don't have that annoying NVTT issue anymore.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7615/app_12529_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7618/app_12529_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7615/HighFidelity-Beta-PR12529-44d0863aec9a12a278ccf1bcd70901b23b98942e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7615/HighFidelity-Beta-PR12529-44d0863aec9a12a278ccf1bcd70901b23b98942e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7618/HighFidelity-Beta-PR12529-c1e386bb56dfdb7672e0e4c06d2f5833102dc1dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7618/HighFidelity-Beta-PR12529-c1e386bb56dfdb7672e0e4c06d2f5833102dc1dd.exe

**Comment by sethalves** [comment]
CMake Error: The source directory "/home/seth/src/hifi-master/build/ext/makefiles/nvtt/project/src/nvtt" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

?

**Comment by Atlante45** [comment]
What? @sethalves are you able to extract this on Linux: http://hifi-public.s3.amazonaws.com/dependencies/nvidia-texture-tools-2.1.0.hifi.zip

**Comment by Atlante45** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7627/app_12529_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7627/HighFidelity-Beta-PR12529-c1e386bb56dfdb7672e0e4c06d2f5833102dc1dd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7627/HighFidelity-Beta-PR12529-c1e386bb56dfdb7672e0e4c06d2f5833102dc1dd.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7652/app_12529_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7652/HighFidelity-Beta-PR12529-c1e386bb56dfdb7672e0e4c06d2f5833102dc1dd.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7654/app_12529_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7654/HighFidelity-Beta-PR12529-2067c959311921a5ea1bb6017e4b8c929119e797.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7654/HighFidelity-Beta-PR12529-2067c959311921a5ea1bb6017e4b8c929119e797.exe

**Comment by Atlante45** [comment]
@sethalves @AndrewMeadows Fixed.
I was naive enough to use the native MacOS zipping tool to make my archive.

**Comment by Atlante45** [comment]
## Test Plan:
Simple smoke test, run interface and make sure you see textures.

**Comment by sethalves** [comment]
I've built this on osx and it works.

**Comment by samcake** [comment]
Can we consider this a QA by dev so we can merge ?

**Pull request merged**
