### PR TITLE
Revert "Drop network data after processing"

### PR DESCRIPTION
**Pull request by samcake**
Reverts highfidelity/hifi#7474

### CODE REVIEW

**Comment by zzmp** [comment]
@ZappoMan I don't understand what was wrong with this PR, so if this lands and fixes things I don't think we should try this again until after https://app.asana.com/0/26225263936266/101152412586454, at which point we can get rid of the `loaded` slot and rely on the virtual `downloadFinished` method.

That way it is not going through a black box of Qt and we can know exactly what we are changing and our data's scope.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f54b5eb954a62d6b2e2b2cb68acc3a2e6643bf4 available at: https://gist.github.com/7c8b46747955579d2b27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7485.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7485.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f54b5eb954a62d6b2e2b2cb68acc3a2e6643bf4 available at: https://gist.github.com/7c8b46747955579d2b27<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7485.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7485.dmg

**Comment by ZappoMan** [comment]
@zzmp - I am not saying there's anything wrong with this PR... I was saying some other crash SEEMED to start happening after the 7474 PR was merged... but sam has found some earlier cases... I am going to close this revert... it's not to blame!

**Pull request closed without merging**
