### PR TITLE
MS20000: [CreateApp/Tooltips] Add missing start/middle/finish tooltips

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/20000/Missing-Tooltips-for-start-middle-finish-properties (test-plan in ticket)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15436/HighFidelity-Beta-PR14480-ec19d2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15436/HighFidelity-Beta-Interface-PR14480-ec19d2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15436/HighFidelity-Beta-PR14480-ec19d2f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15436/HighFidelity-Beta-Interface-PR14480-ec19d2f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15734/HighFidelity-Beta-PR14480-ec19d2f.apk

**Comment by thoys** [comment]
@qligmaloney the merge conflicts are resolved

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15734/HighFidelity-Beta-PR14480-ec19d2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15734/HighFidelity-Beta-Interface-PR14480-ec19d2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15741/HighFidelity-Beta-PR14480-d25b5f0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15741/HighFidelity-Beta-Interface-PR14480-d25b5f0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15741/HighFidelity-Beta-PR14480-d25b5f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15741/HighFidelity-Beta-Interface-PR14480-d25b5f0.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15800/HighFidelity-Beta-PR14480-3a259d8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15800/HighFidelity-Beta-PR14480-3a259d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15800/HighFidelity-Beta-Interface-PR14480-3a259d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15800/HighFidelity-Beta-PR14480-3a259d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15800/HighFidelity-Beta-Interface-PR14480-3a259d8.exe

**Pull request merged**
