### PR TITLE
Fix circle3d FindRayIntersection

### PR DESCRIPTION
**Pull request by zzmp**
Fixes the intersection check (Overlays.findRayIntersection) for circle3d.

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent
Fix a bug where scaled circle3d (i.e. dimensions > 1) did not correctly register clicks outside of the area where an unscaled overlay would lie.
https://app.asana.com/0/74051501495175/83412258866005

#### Testing
```
// Test circle3d overlay click problem

var circle,
    DIMENSIONS_2D = { x: 2, y: 1 },
    RED = { red: 255, green: 0, blue: 0 };

function onMousePressEvent(event) {
    var pickRay, overlayIntersection;

    pickRay = Camera.computePickRay(event.x, event.y);
    overlayIntersection = Overlays.findRayIntersection(pickRay, true);

    if (overlayIntersection.intersects && overlayIntersection.overlayID === circle) {
        print("circle3d clicked");
    }
}

function setUp() {
    var avatarLookAtDirection = Vec3.multiplyQbyV(MyAvatar.orientation, Vec3.UNIT_Z);

    circle = Overlays.addOverlay("circle3d", {
        dimensions: DIMENSIONS_2D,
        isSolid: true,
        color: RED,
        alpha: 1.0,
        ignoreRayIntersection: false,
        visible: true,
        position: Vec3.sum(MyAvatar.position, Vec3.multiply(avatarLookAtDirection, -5.2)),
        rotation: MyAvatar.orientation
    });

    Controller.mousePressEvent.connect(onMousePressEvent);
}

function tearDown() {
    Overlays.deleteOverlay(circle);
    Controller.mousePressEvent.disconnect(onMousePressEvent);
}

setUp();
Script.scriptEnding.connect(tearDown);
```

Running this interactively will log `circle3d clicked` when you click on the circle3d. Make sure clicks register correctly.

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf8b745b45e39324710a298079a9108492657b1c available at: https://gist.github.com/526f4477199472784dd8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 03112a401bb5c6d5dd402363da94069a937c984f available at: https://gist.github.com/526f4477199472784dd8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b9f272ad58a1620bddad8c1fb5fe7dfdd551120 available at: https://gist.github.com/526f4477199472784dd8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb6ff725c48eeb15d1b5715763a66fecfb494667 available at: https://gist.github.com/526f4477199472784dd8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7065.dmg

**Comment by Triplelexx** [comment]
Tested with various dimensions > 1 & < 1, no issues found.

**Pull request merged**
