### PR TITLE
Add extra logging to Windows launcher

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by JeffClinton** [comment]
Looks like mac failed.  Kicking off a rebuild.

**Comment by JeffClinton** [comment]
Build this please

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20069/HighFidelity-Beta-PR15812-b28763a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20069/HighFidelity-Beta-Interface-PR15812-b28763a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20069/HighFidelity-Beta-PR15812-b28763a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20069/HighFidelity-Quest-Beta-PR15812-b28763a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20069/HighFidelity-Beta-PR15812-b28763a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20069/HighFidelity-Beta-Interface-PR15812-b28763a.exe

**Pull request merged**
