### PR TITLE
Beta Release 17 - Includes up to Developer Release 5206

### PR DESCRIPTION
**Pull request by cozza13**
* Skin sub-surface lighting. ( Documentation to add a skin shader to your avatar [Skin documentation] (https://docs.google.com/document/d/1fYXVkCezYbMguRl1J1q244pELFqw_sf9fbuu9-C7pqg/edit?usp=sharing) )
* Edit model dialog improvements. Dialog now allows selection of collision type and whether or not it should be dynamic. 

* Cleanup domain-server heartbeat code. 
* Fix bug breaking simple-compound shape type
* Updates to overlay web browser
* Make whiteboard marker spawning work with 'far trigger'

### CODE REVIEW

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Base smoke test seemed good as usual

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |3972 |5260 |3429
**GPU Buffer Count**: |800 |916 |739
**CPU Memory Usage**: |70209536 |92987392 |65085440
**GPU Memory Usage**: |27492352 |23547904 |34017280
**CPU Texture Count**: |233 |352 |281
**GPU Texture Count**: |1295 |1663 |1462
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |222124108 |875007136 |366011128
**GPU Texture Memory Usage**: |690293122 |1186501568 |855176519
**GPU Virtual Memory Usage**: |881772290|1377980736|1046655687
**Triangle Count**: |520343 |781670 |580621
**Triangle Rate**: |30608411 |45980588 |36288812
**API Drawcall Count**: |228 |290 |244
**Drawcall Count**: |315 |350 |1143
**Drawcall Rate**: |18529 |20588 |71437
**State Changes Texture Count**:|232 |363 |288
**Pipeline Count**: |40 |39 |43
**Item Opaques**: |266 |455 |249
**Item Translucents**: |16 |30 |51
**Item Lights**: |21 |44 |27
**Timing Opaques**: |1202 |2165 |1128
**Timing Translucents**: |116 |147 |250
**Timing Lighting**: |187 |213 |191
**Render Frame**: |2460 |3693 |2514

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Ok
**Test 4**|undefined|Blank
**Test 5**|Retest Skin creation workflow (see link in PR)|Used the provided fst for matthew and the light panel to confirm
**Test 6**|Switch avatar and make sure it does not crash|Ok
**Test 7**|Test that you can go to suggested places|Ok

**Comment by SkimiMission** [comment]
## QA Test
**QA Tester**: Skimi
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |15 |61
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |15 |60
**CPU Buffer Count**: |4761 |5261 |2937
**GPU Buffer Count**: |1084 |967 |703
**CPU Memory Usage**: |73486336 |79159296 |38154240
**GPU Memory Usage**: |31268864 |29351936 |23138304
**CPU Texture Count**: |272 |398 |274
**GPU Texture Count**: |2173 |2107 |1867
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |244468732 |474665656 |280566200
**GPU Texture Memory Usage**: |752208233 |1571147756 |826949749
**GPU Virtual Memory Usage**: |966616560|1785556083|1041358076
**Triangle Count**: |588607 |828567 |478354
**Triangle Rate**: |36787937 |12554045 |29897125
**API Drawcall Count**: |337 |304 |259
**Drawcall Count**: |698 |370 |1176
**Drawcall Rate**: |43625 |5606 |73500
**State Changes Texture Count**:|276 |385 |309
**Pipeline Count**: |52 |46 |50
**Item Opaques**: |384 |483 |270
**Item Translucents**: |50 |60 |52
**Item Lights**: |22 |48 |28
**Timing Opaques**: |2499 |3582 |1756
**Timing Translucents**: |221 |212 |323
**Timing Lighting**: |227 |376 |264
**Render Frame**: |4247 |4760 |3599

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|OK
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|OK
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|OK
**Test 4**|undefined|--

**Test 5**|Retest Skin creation workflow (see link in PR)| Tried to use the provided matthew.fst and priscilla.fst and the light panel to confirm. I was not able to load one of these avatars. If I try to download them in browser, I get a 404 Error.

**Test 6**|Switch avatar and make sure it does not crash|OK
**Test 7**|Test that you can go to suggested places|OK

**Comment by Nex-Pro** [comment]
**PR Build:** #8318
**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None

**Test Script employed:** http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS
**Additional Test Results + Observations**:

Got good frame rates even with 3 monitors hooked up.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |1407 |4862 |3368
**GPU Buffer Count**: |187 |274 |484
**CPU Memory Usage**: |23232512 |88199168 |65024000
**GPU Memory Usage**: |13774848 |7999488 |19820544
**CPU Texture Count**: |193 |364 |298
**GPU Texture Count**: |1275 |814 |1048
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |177005704 |1198590640 |514462400
**GPU Texture Memory Usage**: |419449037 |749119845 |767649891
**GPU Virtual Memory Usage**: |590480205|925765093|944295139
**Triangle Count**: |43914 |124932 |194507
**Triangle Rate**: |2744625 |7808250 |12156687
**API Drawcall Count**: |17 |65 |90
**Drawcall Count**: |17 |69 |90
**Drawcall Rate**: |1062 |4312 |5625
**State Changes Texture Count**:|33 |96 |146
**Pipeline Count**: |25 |28 |28
**Item Opaques**: |3 |69 |74
**Item Translucents**: |6 |4 |14
**Item Lights**: |0 |17 |2
**Timing Opaques**: |462 |665 |984
**Timing Translucents**: |89 |21 |280
**Timing Lighting**: |388 |193 |291
**Render Frame**: |3985 |1886 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**Check**
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|**Check**
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|**Check**
**Test 4**|undefined|Test 4 is blank ?
**Test 5**|Retest Skin creation workflow (see link in PR)|**Check**
**Test 6**|Switch avatar and make sure it does not crash|**Check**
**Test 7**|Test that you can go to suggested places|**Check**

**Comment by Nex-Pro** [comment]
**PR Build:** #8318  for OSX
**Testing Architecture:** Desktop
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** OSX El Capitan
**HMD:** None
**Hand Controllers:** None

**Test Script employed:** http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS

**QA Pass**: SUCCESS

**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |96 |5109 |6228
**GPU Buffer Count**: |60 |1091 |1185
**CPU Memory Usage**: |3932160 |91463680 |146190336
**GPU Memory Usage**: |3547136 |58241024 |91467776
**CPU Texture Count**: |45 |372 |613
**GPU Texture Count**: |408 |1245 |1745
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |16984328 |131024832 |355235976
**GPU Texture Memory Usage**: |60118369 |1552368451 |2228794776
**GPU Virtual Memory Usage**: |230127137|1722377219|2406406744
**Triangle Count**: |43914 |808939 |530996
**Triangle Rate**: |2744625 |50558687 |35399733
**API Drawcall Count**: |17 |292 |218
**Drawcall Count**: |17 |356 |1133
**Drawcall Rate**: |1062 |22250 |75533
**State Changes Texture Count**:|32 |356 |249
**Pipeline Count**: |23 |44 |43
**Item Opaques**: |3 |459 |213
**Item Translucents**: |5 |59 |50
**Item Lights**: |0 |43 |25
**Timing Opaques**: |87 |4413 |2400
**Timing Translucents**: |11 |226 |353
**Timing Lighting**: |137 |286 |175
**Render Frame**: |827 |6013 |3656

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|***Check***
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|***Check***
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|***Check***
**Test 4**|undefined|
**Test 5**|Retest Skin creation workflow (see link in PR)|***Check***
**Test 6**|Switch avatar and make sure it does not crash|***Check***
**Test 7**|Test that you can go to suggested places|***Check***

**Comment by Nex-Pro** [comment]
**PR Build:** #8362
**Testing Architecture:** Desktop
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** OSX El Capitan
**HMD:** None
**Hand Controllers:** None

## QA Test
**QA Tester**: Piper.Peppercorn


**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** FAILURE
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: FAILURE
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: FAILURE

**Additional Test Results + Observations**: 

Fan switch had no effect in apartment.

Unable to move entities rezzed via ATP.
Also noticed that the vertical move arrows were not showing When entiies selected.

Harmonic oscillator failed. Cube appeared stationary in the disc.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |54
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |54
**CPU Buffer Count**: |122 |5297 |6742
**GPU Buffer Count**: |71 |1056 |1292
**CPU Memory Usage**: |8986624 |100503552 |155795456
**GPU Memory Usage**: |8282112 |62537728 |99438592
**CPU Texture Count**: |50 |387 |616
**GPU Texture Count**: |421 |1320 |1858
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |16984328 |218139328 |387292816
**GPU Texture Memory Usage**: |57322164 |1577184748 |2195947614
**GPU Virtual Memory Usage**: |259255732|1779118316|2397881182
**Triangle Count**: |125518 |887398 |782361
**Triangle Rate**: |7844875 |55462375 |48897562
**API Drawcall Count**: |21 |281 |256
**Drawcall Count**: |21 |339 |1157
**Drawcall Rate**: |1312 |21187 |72312
**State Changes Texture Count**:|37 |343 |295
**Pipeline Count**: |25 |42 |44
**Item Opaques**: |4 |425 |253
**Item Translucents**: |6 |30 |53
**Item Lights**: |0 |43 |27
**Timing Opaques**: |38 |1066 |707
**Timing Translucents**: |53 |72 |126
**Timing Lighting**: |19 |30 |26
**Render Frame**: |316 |2158 |1380


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Some problems.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|No sounds heard.
**Test 5**|Retest the kick function| Fail. No overlay shows above nearby avatar.
**Test 6**|Switch avatar and make sure it does not crash| Success
**Test 7**|Test group functions| Not fully tested.

**Pull request merged**
