### PR TITLE
scrollable suggested places in address bar

### PR DESCRIPTION
**Pull request by howard-stearns**
Address bar suggestions is now based on places, rather than domains.
Although only three suggestions are shown at a time, the list is scrollable to show more.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
- (Note: The suggestions must match the protocol of your interface. I don't know if PR builds currently force a different protocol, in which case you will need to run a matching server and a second matching interface, because the default suggestions require there to already be a user present.)
- Bring up the address bar (e.g., GoTo button). It should display up to three initially visible suggestions. Each suggestion should have a picture, the name of the place, and the number of users present. The number present should be in non-increasing order among the three. (I.e., prefers those with more people present, up to a limit.)
- If there are more than three suggestions, you can drag them to the left, revealing more suggestions on the right. There should be a subtle blue border around the card underneath the mouse (or active laser), and the highlight border should disappear when no card is under the cursor/laser. The scroll should be "flickable" (e.g., keep going with a velocity), although any highlighted card (under the cursor/laser) will stay displayed, which will "stop" the flick.
- You can click on a picture to go to that domain.  You should go the specific place designated (and not merely another place within the same domain.) When you bring up the address bar again, the suggestions should NOT include the place you just entered, although it may show other places in the same domain. (The current definition of current place is the one you entered, even if you have since walked over to be at a different place's coordinates.)
- You can filter results by typing. It is based on whether the place's name, description, or any of it's domain's tags contain the given text, in any word order and case-insensitive. You should be able to delete characters to bring more suggestions back.  If you have typed any characters, all open matching named places are shown. However, if not characters are currently in the address bar, only places with at least one person and a place picture are suggested.

**Comment by howard-stearns** [comment]
hmm. two hours to build doesn't seem reasonable

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45a49c390bbdc2b1f9defdce9fa5245f5d88b75f available at: https://gist.github.com/92bc41a7f18009e7f4cd9ec866df3c4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-45a49c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-45a49c3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3bf52267d4c57af4aa2b291cfc8ae6d8f33a894 available at: https://gist.github.com/92bc41a7f18009e7f4cd9ec866df3c4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-c3bf522.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-c3bf522.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45a49c390bbdc2b1f9defdce9fa5245f5d88b75f available at: https://gist.github.com/92bc41a7f18009e7f4cd9ec866df3c4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-45a49c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-45a49c3.dmg

**Comment by nbq** [comment]
testing now

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70e07f329918ebf3883c217639dbd032eeec3234 available at: https://gist.github.com/92bc41a7f18009e7f4cd9ec866df3c4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-70e07f3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8343-70e07f3.dmg

**Pull request merged**
