### PR TITLE
Fix selecting values when tabbing between entity properties fields

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

In desktop mode, defaultScripts.js running, create some entities then do the following tests in the Create app.

1) Test changing field focus.
- Click on a field in a tuple (e.g., color properites, or dimensions) so that it gains focus; field's value is selected (i.e., highlighted). Click on another field in the tuple so taht it gains focus; other field's value is selected.
- Click on a field; field's value is selected. Tab through fields using Tab and Shift-Tab keys; values are selected as each field gains focus.
- Click on a field; field's value is selected. Type in new value so that the selected value is replaced. Click on another field; previous field's value takes effect; new field's value is selected.
- Click on a field; field's value is selected. Type in new value so that the selected value is replaced. Tab to next field; previous field's value takes effect; new field's value is selected.

2) Test changing entity focus.
- Click on an entity so that it gets focus.
- Click on a field in the Properties tab so that it gets focus; field value is selected.
- Click on another entity so that it gets focus.
- Dialog is populated with new entity's values, no form field has focus, and no value is selected.

3) Miscellaneous tests.
- Check that the up/down spinner values work.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7305/app_12438_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7305/HighFidelity-Beta-PR12438-65efeadf107e2a9171714d4a020c5f297338d453.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7305/HighFidelity-Beta-PR12438-65efeadf107e2a9171714d4a020c5f297338d453.exe

**Comment by qlimnavarro** [comment]
Currently testing.

**Comment by qlimnavarro** [comment]
Pass. @conklin94122

**Comment by sethalves** [comment]
does this fix https://highfidelity.fogbugz.com/f/cases/11509/field-highlighting-in-CREATE-doesn-t-work-right ?

**Comment by ctrlaltdavid** [comment]
@sethalves Yes. It fixes https://highfidelity.fogbugz.com/f/cases/12073/Inconsistences-with-x-y-z-coordinate-behavior-in-the-properties-tab-in-create-mode ... which appears to be a duplicate of the one you mentioned.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7312/app_12438_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7312/HighFidelity-Beta-PR12438-44aafd92a474504f5543763b40c3b0cd9f73612b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7312/HighFidelity-Beta-PR12438-44aafd92a474504f5543763b40c3b0cd9f73612b.exe

**Pull request merged**
