### PR TITLE
allow scripts on the web to refer to local libraries with /~/

### PR DESCRIPTION
**Pull request by sethalves**
- allow scripts on the web to refer to local libraries with /~/

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
create a script with has something like:

Script.include(["/~/system/libraries/toolBars.js"]);

and load it via an http(s) url.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c278563f5dbf5e09f18f56a5042f987da87adc5 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c278563f5dbf5e09f18f56a5042f987da87adc5 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by imgntn** [comment]
QA fail on security

**Comment by zzmp** [comment]
@imgntn Is there a way around security here? Not around - but to make it secure?

@sethalves Why did you choose `/~/` instead of just `~/`, like a shell?

**Comment by sethalves** [comment]
I think I can make it secure.  I used /~/ because ~username is a common http path.  Maybe ~/ isn't, but... I'm sure this is already a violation of some spec or another.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 648e6a74d7f159b588cce82de8590cf0b5421fe9 available at: https://gist.github.com/f92e8d8c77b7e25263313ed3c5f7b852<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 648e6a74d7f159b588cce82de8590cf0b5421fe9 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ced18fe6be06f255f2ce7b11eba567ba7c3aa029 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ced18fe6be06f255f2ce7b11eba567ba7c3aa029 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 36e84e626686dccf711ac4289fdbaa62c2fbf591 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f03130ff5ab857ae0e59e0d060b1b8693b9a7f11 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by imgntn** [comment]
win 10 pass 
[04/29 11:32:15] [DEBUG] Done downloading script at: "http://hifi-content.s3.amazonaws.com/james/bad.js"
[04/29 11:32:15] [DEBUG] Logging activity "loaded_script"
[04/29 11:32:15] [DEBUG] ScriptEngine::include -- skipping "/~/../Users/james/Desktop/naughty.js" -- outside of standard libraries

**Comment by hifi-gustavo** [comment]
Build console output for commit: 36e84e626686dccf711ac4289fdbaa62c2fbf591 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b28cfd27ec1cfdab9df4d66e2b18aeeb51972933 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 351a5d2cb1cf1c821a4c7933185d517fbfc7eaf8 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by cozza13** [comment]
@imgntn , can you retest this when you get a chance

**Comment by hifi-gustavo** [comment]
Build console output for commit: a9897f1cc4b3211188f1058b4fb2cf2528f82d10 available at: https://gist.github.com/f031003d5fa1da176dfb209376b71729<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7786.dmg

**Comment by imgntn** [comment]
tested again:  can't access file on my desktop from remote file (good), default scripts continue to work as i refresh.

**Pull request merged**
