### PR TITLE
fix a crash in RenderableModelEntityItem::getModel

### PR DESCRIPTION
**Pull request by sethalves**
- fix a rare crash during entity model loading

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- smoke test

**Comment by sethalves** [comment]
https://app.asana.com/0/26225263936266/116587920166014

**Comment by hifi-gustavo** [comment]
Build console output for commit: 16bf59f8a63ea005f346e6bd9a5bfabd684b8382 available at: https://gist.github.com/7ace311818a17ea2ff0aa180909d0f7a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7758.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7758.dmg

**Comment by bluetoe** [comment]
I crashed when rotating after arriving on localhost after being at cellscience. Things were still loading. I filled out crash report and it went to bugsplat.

**Comment by sethalves** [comment]
I see the bugsplat... I don't see anything in it that relates to this PR.  Is that crash repeatable?

**Comment by sethalves** [comment]
https://www.bugsplatsoftware.com/individualCrash/?id=3025

**Comment by bluetoe** [comment]
no. it is not repeatable at least not for me

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7758
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |59.99     |60.39    |59.04       
Present Rate:                     |60.00     |60.00    |60.00       
Simrate:                          |60.00     |60.04    |58.99       
Render Stats Num Buffers:         |2752      |2741     |1772        
Render Stats gpu::Buffer Memory:  |33.8Mb    |66.2Mb   |25.6Mb      
Render Stats Num Textures:        |270       |300      |93          
Render Stats gpu::Texture Memory: |839.6Mb   |961.3Mb  |247.9Mb     
Render Stats Triangles:           |479k      |237k     |290k       
Render Stats Drawcalls:           |247       |185      |77         
Render Stats State Changes:	  |212       |166      |47          
Render Stats Items:               |280       |232      |208        
Render Stats Timing:              |6.6ms     |6.0ms    |6.5ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |235Mb     |235Mb    |235Mb       
GPU-Z Memory Used		  |2337Mb    |2200Mb   |1920Mb      
GPU-Z Memory Load		  |26%       |28%      |17%        

**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** (none)  
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Pull request merged**
