### PR TITLE
Master : Fixing the zone entity not rendered properly when created

### PR DESCRIPTION
**Pull request by samcake**
Same as https://github.com/highfidelity/hifi/pull/11596 but in master
This PR fixes a bug that prevent a newly created zone entity to be rendered (background or keylight component).
We simply made sure to update the Entity Renderer as needed (creation and updates) before the update of the zone stack.

TEST PLAN

Run the zone stack debugging (from the js console, type:
Render.getConfig("RenderMainView.DrawZoneStack").enabled = true

In a domain, create a zone, change the default keylight settings or enable the background skybox.

Without changing your position, this new zone and skybox should be visible in the scene and also in the Zone stack debugger.

This works in this pr but fails in RC57 or master

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4156/HighFidelity-Beta-PR11597-31ea5d7417177968e2585cf465170f2a5f1a74cb.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4158/HighFidelity-Beta-PR11597-31ea5d7417177968e2585cf465170f2a5f1a74cb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4158/HighFidelity-Beta-PR11597-31ea5d7417177968e2585cf465170f2a5f1a74cb.exe

**Comment by Nex-Pro** [comment]
Testing, hmmm this seems soooo familiar !

**Comment by Nex-Pro** [comment]
### PASS

Updates to skybox texture, skybox colour and skybox keylight colour etc. are updated immediately and are correctly shown in the zone stack

***Don't worry I set the zone colour to green !***
yz8316-hifi-snap-by--on-2017-10-14_09-33-45
.

**Pull request merged**
