### PR TITLE
Sound cues for GoTo interface

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/8354/Add-Sound-Cues-in-GoTo-menu

Test plan
- Open Tablet
- Click on GoTo button
- Hover worlds cards. Make sure there is hover sound
- Click on an card. Make sure there is click sound

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4332/HighFidelity-Beta-PR11645-cf7b050680e4be7161bc761f1ae322de042e5776.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4332/HighFidelity-Beta-PR11645-cf7b050680e4be7161bc761f1ae322de042e5776.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open Tablet | Pass
Click on GoTo button | Pass
Hover worlds cards. Make sure there is hover sound | Pass
Click on an card. Make sure there is click sound | Pass

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
