### PR TITLE
Fix image2d overlay color property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA Notes
Copy the image2DColor.js script contained in the zip file into your Interface scripts directory (same level as defaultScripts.js).

image2DColor.js
- Rezzes two "friends" image 2D overlays in front of you; one red and the other green; both alpha 0.75.
- Click left mouse button to set visible = false on one; release mouse button to show again.
- Click right mosue button to half the alpha value on one; release mouse button to set alpha to original again.

Confirm that the overlays don't colour items behind, except in the lines of the image (i.e., rectangle enclosing overlays doesn't colour objects behind in the transparent parts of the overlays).

Test in desktop and HMD views.

Confirm that users.js no longer writes two of the following error message to the program log when it starts up:
[DEBUG] OVERLAY Unhandled image property color

Confirm that the 3D image overlay displayed by edit.js as the up/down grab handle still changes colour when you hover your mouse over it.

If you run image2DColor.js on a build other than the PR one you'll get two of the "Unhandled image property color" error messages logged and the "friends" overlays won't be coloured.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f9d6a7ba8d57cccb8e0feb16ecc9f4c344dbcdb5 available at: https://gist.github.com/bb99acfcc64b2682d1e26962822d290e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8036.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8036.dmg

**Comment by ctrlaltdavid** [comment]
[image2DColor.zip](https://github.com/highfidelity/hifi/files/312581/image2DColor.zip)

**Comment by OmegaHeron** [comment]
QA Pass

Testing Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**

Testing against Build 5016 as control.
Build 5016 2 Messages seen about Unhandled image property color as expected.  No color to overlays, as expected.

This PR - No error message in log, each overlay has its own color and does not color overlay behind - as specified in test case.

All standard tests pass - no divergence in FPS/performance seen from my system's normal baseline.

**Pull request merged**
