### PR TITLE
In desktop mode create tablet near mouse click location.

### PR DESCRIPTION
**Pull request by hyperlogic**
In desktop mode, when you right click to display the tablet, center the tablet at the location of your left click.  But at the same time avoid placing the tablet off the edge of the screen.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
   * In desktop mode, right clicking the screen should display the tablet, centered at the location that you clicked.
   * Verify that no matter where you click on the screen the tablet surface is not positioned off the edge of the screen when it appears.  (However, It is still possible to drag it off screen, by design).

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb58c567b837f1dff257afd4e921c1af940aff0e available at: https://gist.github.com/ca74432459de151dcb5c363cd5af54b0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9629-cb58c56.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9629-cb58c56.dmg

**Comment by nbq** [comment]
Testing

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* In desktop mode I verified right clicking on the screen displayed the table in the center of where I clicked
* Dragged the tablet to the outer edge of the screen and then right clicked somewhere near the middle to verify the tablet showed up in the center of where I clicked.
* Verified I was able to drag the tablet very far out to the edge of the window with almost just the tiny edge showing and it worked just fine

**PASS**

**Pull request merged**
