### PR TITLE
16726 - Remove Black Boxes ( HMD.requestShowHandControllers() )

### PR DESCRIPTION
**Pull request by r3tk0n**
Addresses MS ticket number 16726: https://highfidelity.fogbugz.com/f/cases/16726/Black-boxes-on-Vive-Wand-using-HMD-requestShowHandController

**Test Plan:**

**Note: REQUIRES HTC VIVE**

Open interface.exe scripting console and enter:

`HMD.requestShowHandControllers()`

Vive hand controllers should now show in user's field of view, without black boxes appearing all over it.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11389/HighFidelity-Beta-PR13628-a9eb810.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11389/HighFidelity-Beta-PR13628-a9eb810.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11389/HighFidelity-Beta-Interface-PR13628-a9eb810.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11389/HighFidelity-Beta-PR13628-a9eb810.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11389/HighFidelity-Beta-Interface-PR13628-a9eb810.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 @qliacoombs @Qliemillar 

Tested with the ESC key first, then the Script.
Tooltip Boxes were no longer visible surrounding virtualized controllers.

**Pull request merged**
