### PR TITLE
Reduce fidgety motions in seated fidgets

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Remove jitter and bounce from several seated idles and fidgets, also reduce look-around cone

Task:  https://highfidelity.atlassian.net/browse/DEV-2496

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by DouglasWilcox** [comment]
TEST NOTES:
This is a rework of these animations to reduce distracting motion and tone down any bounce or nervous motion:

sitting_idle05
sitting_idle04
sitting_idle_once_leanforward
sitting_idle_once_shiftweight
sitting_idle_once_shakelegs
sitting_idle_once_lookfidget

There is no change to duration on any of these, so no change to the json.  QA can turn on anim stats, use a sit-cube in front of a mirror (I'll attach my sandbox with a mirror+sitcube) and spend time watching the seated idles looking for hiccups or issues.  I tested this myself for about 20 minutes and did not see anything wrong, so I wouldn't suggest spending longer than that.   It does take some time since they are randomly triggered every 10-40 seconds.

**Comment by DouglasWilcox** [comment]
Here's my sandbox with mirror/sitcubes:  https://hifi-content.s3.amazonaws.com/doug/test/douglandia_newmirror_sitcubes.zip

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22370/HighFidelity-Beta-PR16464-15b935b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22370/HighFidelity-Quest-Beta-PR16464-15b935b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22370/HighFidelity-Beta-PR16464-15b935b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22370/HighFidelity-Beta-Interface-PR16464-15b935b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22370/HighFidelity-Beta-PR16464-15b935b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22370/HighFidelity-Beta-Interface-PR16464-15b935b.exe

**Pull request merged**
