### PR TITLE
Build 37.2 Hotfix to fix a crash with texture loading and Qt build 5.6.2

### PR DESCRIPTION
**Pull request by samcake**
- Fix to crash caused by image loading

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d4ac0fc436b05a7452e847d2f387fe1f0a6dbb6 available at: https://gist.github.com/9e4654bda0856b39b802a40f49e1e3fa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.dmg

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d4ac0fc436b05a7452e847d2f387fe1f0a6dbb6 available at: https://gist.github.com/9e4654bda0856b39b802a40f49e1e3fa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d4ac0fc436b05a7452e847d2f387fe1f0a6dbb6 available at: https://gist.github.com/9e4654bda0856b39b802a40f49e1e3fa<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10290-2d4ac0f.dmg

**Pull request merged**
