### PR TITLE
Case 22418: Fix model bounds on resize

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/22418/Orientation-tests-fail-on-AMD-Mac-and-Windows-for-84

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19101/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19101/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by raveenajain** [comment]
Test Plan: 

Running Interface: 
1. Avatars should continue to render correctly.

2. Open Luci -> check off "Opaques"
  - Edit -> Running Scripts -> filter "luci"
3. Edit Running Scripts -> https://raw.githubusercontent.com/highfidelity/hifi_tests/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/orientation/test.js
4. Scale the model (3 ways listed) - the rendering box should scale with the model
    - press n after loading the script
    - Open the Create Tool -> Properties -> edit the local dimension values
    - with the create tool open, select the model then use the scaling tools that appear on the model

5. Edit -> Running Scripts -> https://gist.githubusercontent.com/SamGondelman/c3851567b21ec1119279160a6593d3c0/raw/a7fb94128d6b3184103e7b3ccb6fb4d1d9d9f8d0/AnimationURLTest.js
    - this model should animate 
    - follow steps 2 and 4, but applied to the model this script creates

4. Run Interface -> Edit -> Running Scripts 
    - all existing hifi-test scripts should continue to work, but the following should now be fixed (i.e. the output of the testAuto.js scripts should match the ExpectedImage):
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/orientation
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/lantern
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/embedded/metalRoughSpheres
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/glbTestSuite/engine

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19105/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19105/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19105/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19105/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19127/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19127/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19131/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19131/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19133/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19133/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19133/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19133/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19138/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19138/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19138/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19138/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by qaAdamSmith82** [comment]
I wanted to get this in today, but QA is currently blocked from verifying Windows AMD by: https://highfidelity.manuscript.com/f/cases/22438/Cursor-is-invisible-on-Windows-AMD

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19143/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19143/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19143/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19143/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19143/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19143/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by SamGondelman** [comment]
build this PLEASE you PIECE of JUNK

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19145/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19145/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19145/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19145/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19145/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19145/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by NissimHadar** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19150/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19150/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19150/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19150/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19154/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19154/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19154/HighFidelity-Beta-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19154/HighFidelity-Beta-Interface-PR15480-5a184bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19154/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19154/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19158/HighFidelity-Beta-PR15480-5a184bd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19158/HighFidelity-Quest-Beta-PR15480-5a184bd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19158/HighFidelity-Beta-PR15480-5a184bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19158/HighFidelity-Beta-Interface-PR15480-5a184bd.exe

**Pull request merged**
