### PR TITLE
Steam account integration (Part 1)

### PR DESCRIPTION
**Pull request by Atlante45**
Added "Login through Steam" button to login window.
Will log you in with your steam account if it is linked to you High Fidelity account.

This requires a version of the website not yet live.

Included a commit that slipped through my last PR.
Makes it so that if SteamVR is running but interface is in 2D mode, closing SteamVR will not close interface.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d0d34e412ac349a2e2a058b9e433178c8ca6c9f available at: https://gist.github.com/a308cee79d035cf40a8c9a649e088f25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-3d0d34e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-3d0d34e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f70fb51beecbd04c07bfe4db1b95807bd78a053b available at: https://gist.github.com/a308cee79d035cf40a8c9a649e088f25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-f70fb51.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-f70fb51.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8d3533a1b692145d03f2d7552ff225df7ad54255 available at: https://gist.github.com/a308cee79d035cf40a8c9a649e088f25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-8d3533a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-8d3533a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1efcc24f2d26480a8564ad03e177f65317115996 available at: https://gist.github.com/a308cee79d035cf40a8c9a649e088f25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-1efcc24.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-1efcc24.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1efcc24f2d26480a8564ad03e177f65317115996 available at: https://gist.github.com/a308cee79d035cf40a8c9a649e088f25<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-1efcc24.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8264-1efcc24.dmg

**Pull request closed without merging**
