### PR TITLE
Launch the Sandbox as early as possible

### PR DESCRIPTION
**Pull request by Atlante45**
Launch Sandbox right away and don't wait for it to start before initializing the application.

## Test Plan:

- Download and install PR build
- Run the Sandbox and interface once to make sure they are added to the firewall
- Shut down both the Interface and the Sandbox.
- Open Steam
- Go to Library
- Click "Add a Game" > "Add non-Steam Game..." at the bottom left
- Select "Interface - PR10441" in the list
- Download and extract [this archive](https://s3-us-west-1.amazonaws.com/hifi-content/clement/dev/nvtt.zip) into `Program Files/High Fidelity - PR10441/`
- You should have the following directory structure:
> High Fidelity - PR10441/
> ....home/
> ........assignment-client/
> ........domain-server/

For each of the following test:
- Make sure to delete the following file:
  `AppData/Roaming/High Fidelity - PR10441/Interface.json`
- Right click in Steam on "Interface - PR10441"
- Go to "Properties" > "Set Launch Options..."
- Copy-Paste the specific launch options for each case.
- Click "Ok"
- Launch Interface via Steam
- You should spawn at the location specified in "Result"

NOTE: Do not switch display mode manually, sometimes the interface will start in desktop mode, sometimes in HMD mode, just go with the flow :)

1. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"`
Result: In the tutorial

2. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset`
Result: In dev-welcome

3. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --url "hifi://dev-playa"`
Result: In dev-playa

Delete the following file before doing the next cases:
`AppData/Roaming/High Fidelity - PR10441/assignment-client/content-version.txt`

4. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"`
Result: In the sandbox

5. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset`
Result: In dev-welcome

6. `--display="Desktop" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"`
Result: In dev-welcome

For the following case only, do **NOT** delete the `Interface.json` file.

7. `--display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --url "hifi://dev-playa"`
Result: In dev-playa

### Re-test
If you want to restart the QA from the beginning, simply delete `AppData/Roaming/High Fidelity - PR10441` and start over from:
- Download and extract [this archive](https://s3-us-west-1.amazonaws.com/hifi-content/clement/dev/nvtt.zip) into `Program Files/High Fidelity - PR10441/`

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 530d3e2b930a393b3ea0d2a68fb736d73b83e4d1 available at: https://gist.github.com/05a8253e8a1fcb2fef12f60ac7fc0448<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-530d3e2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-530d3e2.dmg

**Comment by RyanDowne** [comment]
Can this be dev reviewed?

**Comment by Atlante45** [comment]
Haven't tested every startup scenario yet, so it's not ready for QA, but it
could get a preliminary dev review.
If I do need to make any changes, they shouldn't be significant.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 201f81f20ad5b2bba3b05d6f9c007d74354d753c available at: https://gist.github.com/05a8253e8a1fcb2fef12f60ac7fc0448<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-201f81f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-201f81f.dmg

**Comment by YuppyPlays** [comment]
Let us know when ready for test, can do when ready.

**Comment by Atlante45** [comment]
Hi @YuppyPlays, It's ready to test.

**Comment by Atlante45** [comment]
test this please

**Comment by YuppyPlays** [comment]
Testing. :)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 201f81f20ad5b2bba3b05d6f9c007d74354d753c available at: https://gist.github.com/05a8253e8a1fcb2fef12f60ac7fc0448<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-201f81f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10441-201f81f.dmg

**Comment by YuppyPlays** [comment]
Should I test this with that latest build put up or carry on with the previous?

**Comment by Atlante45** [comment]
@YuppyPlays Carry on, the build system blocked on the linux build, I just asked for a re-test, it's the same thing.

**Comment by YuppyPlays** [comment]
Excellent, thank you, will post results shortly :)

**Comment by YuppyPlays** [comment]
Testing Complete:

Followed the instructions carefully, here are the results for launch options listed 1 - 3.

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"
Result: In the tutorial **

QA Result: Spawned in the tutorial in HMD Mode initially. ** PASS **

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset
Result: In dev-welcome **

QA Result: Spawned in the tutorial in HMD Mode (Again) ** FAIL **

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --url "hifi://dev-playa"
Result: In dev-playa **

QA Result: Spawned in the tutorial in HMD Mode (Again) ** FAIL **

Between each test as stated I deleted the interface.json, I also tried not deleting this a second time for each one to no difference.

Here are the next 4 - 6 instructed to test (Deleting interface.json & content-version.txt)

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"
Result: In the sandbox **

QA Result: Spawned in the Sandbox in HMD Mode **PASS**

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset
Result: In dev-welcome **

QA Result: Spawned again in the Sandbox in HMD Mode **FAIL**

**--display="Desktop" --checkMinSpec --no-updater --suppress-settings-reset --runServer --serverContentPath="home"
Result: In dev-welcome **

QA Result: Spawned in Dev-Welcome in Desktop Mode **PASS**


Test 7:

** --display="Oculus Rift","OpenVR (Vive)" --checkMinSpec --no-updater --suppress-settings-reset --url "hifi://dev-playa"
Result: In dev-playa **

QA Result: Spawned in Dev-playa in HMD Mode **PASS**

Overall I think this is a ** fail ** ?

**Comment by Atlante45** [comment]
@YuppyPlays 2) and 3) suggest that the sandbox was running.
I should probably have been clearer, but once you ran the Sandbox once at the beginning to make sure it's added to your firewall.
You should shut it down and never start it again.

The launch options will launch it when necessary, and it should shut down with Interface every time.
This is probably why 5 failed as well.

I added a section to explain how to clean up your current setup for a clean re-test.

**Comment by YuppyPlays** [comment]
@Atlante45

Tests 2, 3 & 6 now work fully as expected, sorry about that.

All tests **passed** :)

**Comment by Atlante45** [comment]
No worries, I should've made it clearer. Thanks!

**Pull request merged**
