### PR TITLE
Fix laser beam jumping upon grabbing entity

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing:
- Upon far grabbing an entity the red laser beam stays steady on the "hit point" (i.e., doesn't jump to the entity's registration point).
- As you move the entity the laser beam continues to target the original entity "hit point".

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c5782e4bb6a38119ed7b4d8bdc491681cacf872 available at: https://gist.github.com/7793e49c12189911dd4765aa3586a3e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9701-2c5782e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9701-2c5782e.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
### FAIL

@ctrlaltdavid  This shows great promise. Much more natural but at this moment it is a fail.

To repro. 

at dev-welcome or anywhere there are the tall moveable monoliths. 

Laser to the top of a monolith and observe what happens when you move the block around. 
The grab point becomes detached by several times the thickness of the entity.
This was repeatable.

Also happens when you transfer grab to the underside.

**Comment by ctrlaltdavid** [comment]
@Nex-Pro This should be more to your liking.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6827a288073001659749de38a55982264ce4a260 available at: https://gist.github.com/7793e49c12189911dd4765aa3586a3e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9701-6827a28.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9701-6827a28.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### PASS nice.
Thanks @ctrlaltdavid  This turns manipulating large objects into a pleasure. I can now far grab the point I want to near-grab and bring that right to my hand without shuffling. Occasionally there was some erratic movement but I don't think it was down to this pr. Laser is now firmly locked on the target.

**Pull request merged**
