### PR TITLE
fix settings getting reset

### PR DESCRIPTION
**Pull request by Atlante45**
fixes bugzid:531
When a setting handle was created but never initialized/used, it would override the current value with the default value on destruction.
This issue was affecting "firstRun" which then would affect the running scripts settings causing them to clear they setting array.
That operation would override the "Settings" menu settings since there was a setting key conflict. Both use "Settings" as a setting key.

I changed the running  scripts setting key to something more appropriate and added some code to move the settings to the new location on first run.

Test plan:
- On first run, make sure the scripts are loaded correctly (They should have been loaded from the old settings location and migrated to the new one)
- On second run, make sure the scripts are still loaded correctly (They should have been loaded from the new settings location)
- Make sure settings in general are correctly saved/loaded
- Test fix:

1. Start interface with "Go Home" in the sandbox menu
2. Enable Advanced/Developer menus
3. Close interface
4. Start interface with "Go Home" in the sandbox menu
5. Notice Advanced/Developer menus are still enabled

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 007eedf75517c5b91d856c121b11fa2b5f9517a3 available at: https://gist.github.com/0c5f22a9829c0aab3d69c40f433fd443<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a1463e54b6de3453485c0fb037cdb50d05953d9 available at: https://gist.github.com/0c5f22a9829c0aab3d69c40f433fd443<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.dmg

**Comment by Nex-Pro** [comment]
@Atlante45 I'll take a look at this.

**Comment by ZappoMan** [comment]
@Atlante45 - I have a question... was this bug exposed by something that's in RC 11 but not in Beta v10.1?

In other words... does RC 11 produce this "settings not being saved effect"? Where it does not occur in the current Beta 10.1 build?

If so... then I think we need to consider this PR as a candidate for split streaming into the current RC 11 build/branch.

Please comment. Thanks.

**Comment by Nex-Pro** [comment]
@Atlante45 First run on this following install I had no scripts running. The scripts folder using reveal on the scripts dialog showed as C:\Program Files\High Fidelity - PR7908\scripts

**Comment by Nex-Pro** [comment]
@Atlante45 Each time I start this using go home  I get no scripts running.

**Comment by Nex-Pro** [comment]
@Atlante45 If I load default scripts and then exit  I still have no scripts when I use go home.

**Comment by Atlante45** [comment]
@ZappoMan the changes to `firstRun` triggered a cascading effect that cause it to happen when you click "Go Home".
But that bug was already there, even though it was much less frequent (race condition requiring ScriptEngines to `saveScript` after the menus save their settings).

**Comment by jherico** [comment]
confirmed that this fixes the menu settings but resets running scripts to empty every run.

**Comment by Nex-Pro** [comment]
@jherico Thanks, I thought I broke it.

**Comment by Atlante45** [comment]
Ok, two weird things I just noticed:
- PR build come prepackaged with an `Interface.ini` (with `firstRun` = false).
- PR builds do not use the designated "High Fidelity - PRXXXX" directories, but the normal "High Fidelity" directory (At least for .ini files).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2368c09c7370772330504579f13c0a81b389a44a available at: https://gist.github.com/0c5f22a9829c0aab3d69c40f433fd443<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.dmg

**Comment by Atlante45** [comment]
@ZappoMan I changed
`if (!settings.contains(SETTINGS_KEY)) {`
to
`if (!settings.childGroups().contains(SETTINGS_KEY)) {`
in my amend. It was messing up on Windows.

@Nex-Pro This will test all the possible code path.
Updated test plan:
- Save your `C:\Users\<username>\AppData\Roaming\High Fidelity\Interface.ini` file and remove it from directory.
- Install PR build
- Start interface (Don't use "Go Home"), it should load the default scripts
- Load `/~/developer/utilities/cache/cacheStats.js`
- Quit Interface
- `C:\Users\<username>\AppData\Roaming\High Fidelity\Interface.ini` should have been recreated by interface automatically. Open it, inside you should see something like:
```
[RunningScripts]
1\script=file:///~/developer/utilities/cache/cacheStats.js
2\script=file:///~/defaultScripts.js
size=2

[Settings]
Advanced%20Menus=false
Control%20With%20Speech=false
Developer%20Menus=false
```
- Move the content of `[RunningScripts]` into `[Settings]` and remove the `[RunningScripts]` category. You should have something like that:
```
[Settings]
1\script=file:///~/developer/utilities/cache/cacheStats.js
2\script=file:///~/defaultScripts.js
size=2
Advanced%20Menus=false
Control%20With%20Speech=false
Developer%20Menus=false
```
- Save the changes
- Start interface, notice defaultScripts.js and cache.js are running
- Close interface
- `C:\Users\<username>\AppData\Roaming\High Fidelity\Interface.ini` should be back to this:
```
[RunningScripts]
1\script=file:///~/developer/utilities/cache/cacheStats.js
2\script=file:///~/defaultScripts.js
size=2

[Settings]
Advanced%20Menus=false
Control%20With%20Speech=false
Developer%20Menus=false
```
- Start Interface a last time and notice defaultScript.js and cache.js are still running


Don't forget to restore you're saved copy of `Interface.ini`


Regarding this step: "- Start interface (Don't use "Go Home"), it should load the default scripts"
I found a bug there, if the first time you ever run interface you use "Go Home", the default scripts won't load. Will file a bug.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9268a2e9ba0f1ad5537713e55382ade96079ab99 available at: https://gist.github.com/0c5f22a9829c0aab3d69c40f433fd443<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.dmg

**Comment by Nex-Pro** [comment]
#### FAIL
**PR Build: #7853**
**Testing Architecture: Desktop PC 4.0 ghz i7  Nvidia gtx770 2gb**
**Testing OS: win 10 pro** 
**Testing Locations:  playa**

#### interface.ini files attached.
[Interface.ini.modded.txt](https://github.com/highfidelity/hifi/files/270729/Interface.ini.modded.txt)
[Interface.ini.afterTests.txt](https://github.com/highfidelity/hifi/files/270730/Interface.ini.afterTests.txt)

I carefully followed the steps described in the description.

**cacheStats.js** persisted as per the test description.

However there were a number of problems:

Graphics issues ( see screen grabs )
Note textures missing from avatar ( they appeared momentarily and then avatar turned solid blue )

*After completing the steps in the description I launched the previous production build and graphics were fine.  I then launched 7908 again and the graphics issues persisted.*

Microphone icon was moved to bottom right corner of screen from top left.
Interface remained in task manager after closing on more than one occasion.
No bugsplats were generated.

#### Screen grab first run
7908_graphics_issue

#### Screen grab second run
7908_graphics_issue_second_launch

**Comment by Nex-Pro** [comment]
test this please

**Comment by Nex-Pro** [comment]
Thought I'd see if it would rebuild. In the meantime I'm re-downloading and re-installing this PR.

**Comment by Nex-Pro** [comment]
Ok this shows the same issues after re-installation.

**Comment by Atlante45** [comment]
Hmmm, it's extremely unlikely I affected graphics code. I might not have the RC fixes we made recently in there.

`Microphone icon was moved to bottom right corner of screen from top left.`
This is because when the icon were made movable, they weren't given correct defaults.

I'm gonna update to the latest RC.

**Comment by ZappoMan** [comment]
@Atlante45 - re: "Microphone icon was moved to bottom right corner of screen from top left. - This is because when the icon were made movable, they weren't given correct defaults."

We should note that the microphone has been movable for a while now, and the default settings haven't changed. In fact a PR as recently as Beta v9 time frame was tested and worked correctly related to the positioning of the microphone into the "recommended rectangle" of the display...

So... I am sure that that feature was working properly before your PR.

That being said... maybe something to do with when the QML is loading (and checking the values from the settings) is now not working as it once did because of your settings change.

QML does use the settings. So this could have broken the QML's expected behavior.

**Comment by hifi-gustavo** [comment]
Build console output for commit: de36cd150e8d00dd82df9e6b002c4730fd6eaa4c available at: https://gist.github.com/0c5f22a9829c0aab3d69c40f433fd443<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7908.dmg

**Comment by Atlante45** [comment]
@ZappoMan Just checked, it's a new regression. Happens in 9410 but not in 9404.
Tracking down the version it was introduced in right now.

**Comment by Atlante45** [comment]
That doesn't seem right. Bug was introduced in 4905 with PR #7881

**Comment by ZappoMan** [comment]
yeah - that makes no sense at all

**Comment by Atlante45** [comment]
@ZappoMan Got tricked by the non sequential release number we have now.
It was actually introduced in 4902 with PR #7816
Not exactly sure why yet, but I'm working on it.

**Comment by Nex-Pro** [comment]
@Atlante45 The graphics issues went away when I deleted the cache, prepared and data8 folders.
Simply clearing cache did not help.

**Comment by Atlante45** [comment]
That's odd, look like we might still have some caching issues then.

Regarding that PR, What's the QA Readiness status? 
Sounds like the only thing left is the mic icon, but that's a different bug that has been uncovered by resetting the `.ini. I'm gonna work on it independently.

**Comment by Nex-Pro** [comment]
@Atlante45  the problems return on subsequent relaunch  but are absent on production.

**Comment by Nex-Pro** [comment]
@Atlante45 I just sent a bugsplat

**Comment by Atlante45** [comment]
@Nex-Pro The graphics issues?

**Comment by Nex-Pro** [comment]
@Atlante45  yes.

**Comment by Nex-Pro** [comment]
@Atlante45  watch this video of the issue. https://dl.dropboxusercontent.com/u/96759331/2016-05-19-1950-41.mp4

**Comment by Nex-Pro** [comment]
@Atlante45 I carefully followed the steps again and the cache stats persisted as they should. 

### Pass on the test requirements

graphics issues persist.

**Comment by ZappoMan** [comment]
Removed dev approved because lots of changes made to the code since it had been dev approved.

**Pull request merged**
