### PR TITLE
TEAM-TEACHING: Try to move the rendering pipeline to the REnderDeferredTask

### PR DESCRIPTION
**Pull request by samcake**
- It's slow
- it's buggy
- the avatar are not rendered
- it doesn't do anything better than before
But, somewhere down the line it should take us to a better place

- Implemented RenderDeferredTask with several Jobs reproducing the current rendering pipeline (as it is in upstream master) so all the rendering goes through it

- Added monitoring tools exposed in js so we can follow what's happening

- Added the type Background for the stuff that needs to be rendered as such

Probably my most epic PR, take it or leave it...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 640071dd35783a4339c0ed9c5c20041d439d8f70 available at: https://gist.github.com/3a91b9426cf698ba81d1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eea7ddf4914c3f28a2421f6e18a35f61100e152d available at: https://gist.github.com/3a91b9426cf698ba81d1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8bf08b34d792a3977f51183812af16f449a405c7 available at: https://gist.github.com/3a91b9426cf698ba81d1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5028.dmg

**Comment by samcake** [comment]
Victory

**Pull request merged**
