### PR TITLE
fix import of invalid JSON file failing silently

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Test plan

Two files in attached zip: one a valid JSON import file and the other an invalid JSON import file.
- Import each file on recent official build: good file imports; bad file fails to import with no warning message.
- Import each file with PR build: good file imports; bad file fails to import but this time there's a warning message.

Check importing some other JSON and SVO files.

[20961 Test Files.zip](https://github.com/highfidelity/hifi/files/308122/20961.Test.Files.zip)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2953ca08cbe82e4134f9e0b449f8d1aef977e968 available at: https://gist.github.com/9d5dcdd873c1eb5f55cd73b34d9c6c0f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8048.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8048.dmg

**Comment by Nex-Pro** [comment]
Import each file on recent official build: good file imports; bad file fails to import with no warning message. **Checked**
Import each file with PR build: good file imports; bad file fails to import but this time there's a warning message **Pass**


**Notes:**

Export of entities is now broken in this PR.

** .svo** FILES are not shown in the import dialog.
Path defaults to c:/Program Files/High Fidelity
Also it is not possible to type in the input field of the import dialog.

**Comment by ZappoMan** [comment]
```
Export of entities is now broken in this PR.

** .svo** FILES are not shown in the import dialog.
Path defaults to c:/Program Files/High Fidelity
Also it is not possible to type in the input field of the import dialog.
```
That sounds like a fail not a pass. Am I missing something? ^

**Comment by ctrlaltdavid** [comment]
> Export of entities is now broken in this PR.
This is the subject of https://github.com/highfidelity/hifi/pull/8044

> ** .svo** FILES are not shown in the import dialog.
edit.js explicitly filtes for *.json files only. Should it also include *.svo in the filter? If so, this should be reported in FogBugz.

> Path defaults to c:/Program Files/High Fidelity
> Also it is not possible to type in the input field of the import dialog.
These two items are being addressed in https://github.com/highfidelity/hifi/pull/8044

**Comment by ZappoMan** [comment]
> Should it also include *.svo in the filter

No. We only support json files now.

re: #8044 - good to know, I guess I was thrown off by the comment that it no longer works in **this** PR.

**Pull request merged**
