### PR TITLE
Fixing the rendering of Image3D overlay when drawn in the scene

### PR DESCRIPTION
**Pull request by samcake**
This PR addresses this bug:
https://highfidelity.fogbugz.com/f/cases/3471/image3d-overlays-show-up-as-a-solid-color-unless-using-drawInFront-true

THe image 3D overlay were not rendered correctly when drawn in the scene depth (not in front).
we fixed and introduced specific shaders for these particular RenderItem::ShapeKey (non material, unlit or not, translucent or not) to address these in the main rendering pipeline (opaque and transparent)

THis code may have side effects to be tested for for any object that use the same pipeline (triggered form the same REnderItem:ShapeKey). As of now, I don't know which could they be...

## TEST PLAN
THis PR can be tested by triggering the following script in master and in this PR and compare
Here is the script code to test (which can be copy pasted in the js console):
```
(function() { // BEGIN LOCAL_SCOPE
    var pos1 = MyAvatar.position;
    pos1.z = pos1.z - 1.0;
    pos1.x = pos1.x + 1.0;
    var pos2 = MyAvatar.position;
    pos2.z = pos2.z - 1.0;
    pos2.x = pos2.x - 1.0;
    var pos3 = MyAvatar.position;
    pos3.z = pos3.z - 1.0;
    pos3.x = pos3.x - 3.0;
    var pos4 = MyAvatar.position;
    pos4.z = pos4.z - 1.0;
    pos4.x = pos4.x - 5.0;

    var pos1o = MyAvatar.position;
    pos1o.z = pos1o.z - 3.0;
    pos1o.x = pos1o.x + 1.0;

    var pos2o = MyAvatar.position;
    pos2o.z = pos2o.z - 3.0;
    pos2o.x = pos2o.x - 1.0;

    var pos3o = MyAvatar.position;
    pos3o.z = pos3o.z - 3.0;
    pos3o.x = pos3o.x - 3.0;

    var pos4o = MyAvatar.position;
    pos4o.z = pos4o.z - 3.0;
    pos4o.x = pos4o.x - 5.0;

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos1 });

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos2, emissive: true });

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos3, alpha: "1.0" });

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos4, emissive: true, alpha: "1.0" });


	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos1o, drawInFront: true });

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos2o, drawInFront: true, emissive: true });
    
	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos3o, drawInFront: true, alpha: "1.0" });

	Overlays.addOverlay("image3d", { url: "https://img.clipartfest.com/cdfbafa8c9607f1cfd243bc0f1ae98ca_leftarrow-arrow_500-375.jpeg", position: pos4o, drawInFront: true, emissive: true, alpha: "1.0" });
 
   // Entities.addEntity( 
}());
```

THis should show 2 rows of 4 image3d Overlays showing an horizontal arrow.
The front row are 4 overlays drawn in the scene depth (what we fixed).
THe back row are 4 overlays drawn in front (these are working correclty). 

IT should look correct in this pr
image

the front row is not rendering the texture correctly in current master
image

We want to make sure that this pr doesn't break any other overlay (or something else that i may not know about) that is potentially using the same pipelines.
This should apply to typically overlays Not model, not drawn in front.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6385a702cdefe23dfd9523636c12065fabe3fdec available at: https://gist.github.com/8c8fcbcb7bc7a9549ccd41f7972a0247<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-6385a70.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-6385a70.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b4696f4ec7909f4224de50da28a2809e3d3f337 available at: https://gist.github.com/8c8fcbcb7bc7a9549ccd41f7972a0247<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b4696f4ec7909f4224de50da28a2809e3d3f337 available at: https://gist.github.com/8c8fcbcb7bc7a9549ccd41f7972a0247<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.dmg

**Comment by Nex-Pro** [comment]
Testing this now.

**Comment by Nex-Pro** [comment]
@samcake  I got a virus warning on this.

**Comment by samcake** [comment]
test this please

**Comment by samcake** [comment]
rebuilding...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b4696f4ec7909f4224de50da28a2809e3d3f337 available at: https://gist.github.com/8c8fcbcb7bc7a9549ccd41f7972a0247<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-8b4696f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 309c6b8d9b60ce0a0e43246af03bb6a865930dd1 available at: https://gist.github.com/8c8fcbcb7bc7a9549ccd41f7972a0247<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-309c6b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10126-309c6b8.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
## PASS
see images.

### THIS PR
hifi-snap-by--on-2017-04-06_15-33-56

### MASTER
hifi-snap-by--on-2017-04-06_15-35-38



## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: Not tested
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |89 |0 |
**Present Rate**: |89 |90 |
**Present New Rate**: |89 |90 |
**CPU Buffer Count**: |1997 |3538 |
**GPU Buffer Count**: |316 |930 |
**CPU Memory Usage**: |24377712 |63089712 |
**GPU Memory Usage**: |7091632 |38819248 |
**CPU Texture Count**: |237 |218 |
**GPU Texture Count**: |83 |165 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |283793284 |680153148 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |312516 |1777329 |
**Triangle Rate**: |34724000 |161575363 |
**API Drawcall Count**: |73 |196 |
**Drawcall Count**: |982 |668 |
**Drawcall Rate**: |109111 |60727 |
**State Changes Texture Count**:|115 |202 |
**Pipeline Count**: |40 |41 |
**Item Opaques**: |67 |312 |
**Item Translucents**: |22 |24 |
**Item Lights**: |2 |54 |
**Timing Opaques**: |0.207 |0.778 |
**Timing Translucents**: |0.04 |0.045 |
**Timing Lighting**: |0.012 |0.016 |
**Render Frame**: |0.701 |1.865 |

**Pull request merged**
