### PR TITLE
Updates for min spec check for Steam

### PR DESCRIPTION
**Pull request by jherico**
* Increase timeout for overlay from 10 seconds to 30 seconds
* Shutdown early on any button input (vive controllers or otherwise)
* Increase the size of the overlay for legibility
* Update the overlay image (note, for some reason SteamVR seems to cache the image, so it might not pick up changes if you've previously tested this)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23fc865d405e1f2e831bb40c7faf3d4df6f7e779 available at: https://gist.github.com/8ad1c1676082bde9d29a60cfe2897568<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8942-23fc865.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8942-23fc865.dmg

**Comment by thoys** [comment]
Whats the testplan on this @jherico ?

**Comment by ZappoMan** [comment]
@thoys - I will test it... it takes an i5 machine and a little bit of steam trickery to test this.

**Comment by ZappoMan** [comment]
Testing now

**Pull request merged**
