### PR TITLE
Improve hand controller move and throw velocity

### PR DESCRIPTION
**Pull request by hyperlogic**
The improvements are most apparent with the vive controllers but also affect hydra as well.

The main idea is to use the velocity and angularVelocity returned from the controller pose when performing the physics hold action.  This is more accurate than recomputing the velocities based on previous positions.  In the case of the Vive the velocities are very accurate.  For the hydra we compute the velocities based on position deltas, which is no worse than before.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/26225263936266/92241192558345/f

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0fd260076bbcae43f4d7bcf11b752f85476a9d7e available at: https://gist.github.com/6428fabd46620db302dd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e544275500a10cce28427b8d088fb0df0a19fad6 available at: https://gist.github.com/6428fabd46620db302dd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 38b29f47091b0f22ef41bd2718e66d3851ed0edd available at: https://gist.github.com/6428fabd46620db302dd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7162.dmg

**Comment by pippilina** [comment]
FANTASTIC.  Great improvement when throwing things!

**Comment by AndrewMeadows** [comment]
I tested with hydras.  It works well.

**Pull request merged**
