### PR TITLE
Fix tablet attaching to hand while far-grabbing an entity

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
The entity is released in favour of grabbing the tablet.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

HMD mode.

1) Check that when far-grabbing an entity and your hand nears the tablet, the tablet is grabbed and the entity is released.
- Display the tablet.
- Squeeze a controller trigger to far-grab an entity.
- Move your hand near the tablet.
- The entity should be released and the tablet should be grabbed.
- Release the controller trigger. The tablet should stop being grabbed.

2) Check that when far-grabbing an entity and your hand nears another eneity, the original entity continues to be far-grabbed.
- Squeeze a controller trigger to far-grab an entity.
- Move your hand near another entity, such that it would normally be near-grabbed.
- The original entity should continue to be far-grabbed; the near entity should not be grabbed.
- Release the controller trigger. The entity should stop being grabbed.

Note: Separate known bug: The near entity will continue to be highlighed.

3) General test of near and far grabbing (e.g., per relevant standard tests).

https://highfidelity.manuscript.com/f/cases/12195

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10488/HighFidelity-Beta-PR13343-54b96cd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10488/HighFidelity-Beta-PR13343-54b96cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10488/HighFidelity-Beta-Interface-PR13343-54b96cd.dmg

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Tested with Rift system.

1. Opened tablet and then far grabbed object. While object is being moved around, moved hand over tablet and the object is let go and the tablet is then near grabbed for moving.

2. Moved next to a local entity that allows for grabbing and highlights when hand is over. Moved hand away and far grabbed object. While object is still grabbed, moved hand to be close enough to grab object as previously tested, object is not grabbed and does not highlight. Dropping the far grab then allows for highlight and grab of near object.

Note - Did get vibration feedback when hand was close enough to near grab object.

3. Played with the near and far grabbing of objects along with another user and no apparent defects.

**Pull request merged**
