### PR TITLE
new inventory icons, and align message waiting light in items tab

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15051/HighFidelity-Beta-PR14385-3431bdb.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15051/HighFidelity-Beta-PR14385-3431bdb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15051/HighFidelity-Beta-Interface-PR14385-3431bdb.exe

**Comment by changxc** [comment]
https://highfidelity.manuscript.com/f/cases/19830/minor-change-of-inventory-icon

**Pull request merged**
