### PR TITLE
Tweak transit animations

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/19527/Tune-animation-for-3ptv
This PR change the speed and animation file of the transit effect.
There is also some code renaming and refactoring. It also incorporates the animation file as part of the interface resources.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14762/HighFidelity-Beta-PR14351-dceeadd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14771/HighFidelity-Beta-PR14351-0f1b124.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14771/HighFidelity-Beta-Interface-PR14351-0f1b124.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14771/HighFidelity-Beta-PR14351-0f1b124.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14771/HighFidelity-Beta-Interface-PR14351-0f1b124.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to a domain with other avatars.
- When they teleport you should see them moving in a straight line to their destination. An animation should play during transit. 
- When you teleport you should move instantaneously to your destination (default behavior) and no animations should play on your own client

**Comment by jakram** [comment]
Currently testing

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15027/HighFidelity-Beta-PR14351-0f1b124.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15027/HighFidelity-Beta-PR14351-0f1b124.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15027/HighFidelity-Beta-Interface-PR14351-0f1b124.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . When you teleport you are instantaneously transported to your destination and when you see someone else teleport the teleport motion is smooth and transitions clearly.

**Pull request merged**
