### PR TITLE
update to latest electron version for server console

### PR DESCRIPTION
**Pull request by birarda**
Needed to fix a CVE for brace-expansion and decided it was probably better to get to 1.x electron that simply update to 0.37.8 (very old).

This PR updates electron used by server console to 1.8.4 (latest).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8468/HighFidelity-Beta-PR12779-32768fa9092e7cef2451326dccc58c3d097cfc4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8468/HighFidelity-Beta-PR12779-32768fa9092e7cef2451326dccc58c3d097cfc4c.exe

**Comment by birarda** [comment]
#### Test Plan

This will require a smoke test of all Sandbox functionality to ensure that it behaves as expected.

(1) Install Sandbox from this PR.
(2) Test each of the functions in the Sandbox menu and ensure they work as expected (I can provide clarification for their behavior if the menu option does not make it clear).

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8472/HighFidelity-Beta-PR12779-c23d4df93237ba53373df2a7024849518ee93475.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8472/HighFidelity-Beta-PR12779-c23d4df93237ba53373df2a7024849518ee93475.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8478/HighFidelity-Beta-PR12779-7638dceee39e8c3134f8cfdb92d32d2ea8fca934.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8478/HighFidelity-Beta-PR12779-7638dceee39e8c3134f8cfdb92d32d2ea8fca934.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Sandbox basic features were tested, no new strange behavior experienced.

**Pull request merged**
