### PR TITLE
avoid a deadlock when clearing avatar entities

### PR DESCRIPTION
**Pull request by sethalves**
- avoid a deadlock when clearing avatar entities

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/11474

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6403/app_12200_PR.apk

**Comment by sethalves** [comment]
to test:
- attach an avatar-entity to your avatar by opening the console and pasting:
```javascript
Entities.addEntity({
    type: "Model",
    modelURL: "http://hifi-content.s3.amazonaws.com/alan/dev/Cowboy-hat.fbx?2",
    localPosition: { x:0, y:0.0523, z:0 },
    name: "hat",
    dynamic: false,
    collisionless: true,
    parentID: MyAvatar.sessionUUID,
    parentJointIndex: MyAvatar.getJointIndex("head"),
    dimensions: { x: 0.3239, y: 0.15, z: 0.3779 },
    }, true);
```
- make sure you see the hat on (near?) your head
- paste this line into the console
```javascript
MyAvatar.setAvatarEntityData({});
```
- don't deadlock

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6403/HighFidelity-Beta-PR12200-45406177e517bbadd1e20c455aa2bc9c261ef743.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6403/HighFidelity-Beta-PR12200-45406177e517bbadd1e20c455aa2bc9c261ef743.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
