### PR TITLE
Move old recorder.js script to script-archive

### PR DESCRIPTION
**Pull request by anshuman64**
Use new record.js script in Running Scripts instead

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a22be93d69a113fc26ca9aeafc2c4d1035aa060b available at: https://gist.github.com/3798428c4a0e5b9a02e1561386b73745<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-a22be93.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-a22be93.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d1d6924e86deada4651c9c6b85a9e742e08e269 available at: https://gist.github.com/3798428c4a0e5b9a02e1561386b73745<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-0d1d692.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-0d1d692.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d1d6924e86deada4651c9c6b85a9e742e08e269 available at: https://gist.github.com/3798428c4a0e5b9a02e1561386b73745<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-0d1d692.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10352-0d1d692.dmg

**Pull request merged**
