### PR TITLE
Fix added entities not being undoable in Create

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
https://highfidelity.fogbugz.com/f/cases/16839/Adding-an-entity-is-not-undoable-in-Create

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11540/HighFidelity-Beta-PR13686-21d927c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11540/HighFidelity-Beta-Interface-PR13686-21d927c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11540/HighFidelity-Beta-PR13686-21d927c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11540/HighFidelity-Beta-Interface-PR13686-21d927c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11540/HighFidelity-Beta-PR13686-21d927c.apk

**Comment by huffman** [comment]
# Test Plan

 1. Activate Create
 1. Create a cube
 1. Select `Edit > Undo` from the menu. The cube should be removed.
 1. Create a cube (1)
 1. Move cube (1)
 1. Create another cube (2)
 1. Move cube (2)
 1. Press ctrl-z. Cube (2) should move back to where it was first created
 1. Press ctrl-z. Cube (2) should be removed, and cube (1) should be selected
 1. Press ctrl-z. Cube (1) should move back to where it was first created
 1. Press ctrl-z. Cube (1) should be removed, and there should be no selected
 1. Press ctrl-shift-z 4 times, each time observing that the actions are taking place in reverse (Cube (1) is created, then moved, Cube (2) is created, then moved)
 1. Do a general smoke test on editing other properties of an entity and undoing/redoing the actions.

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
FAIL @conklin94122 
Steps to Reproduce:
1: Launch assumed build.
2: Create cube.
3: Go to edit>undo and cube disappears.
4: Create 1st cube and move it then create second cube and move it.
5: Hit control-z and second cube moves to original location.
6:Hit control-z again and first cube disappears.
7: Actions are not being undone by the order in which they were created.
[2018-07-27 12-14-55.1.zip](https://github.com/highfidelity/hifi/files/2236795/2018-07-27.12-14-55.1.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11769/HighFidelity-Beta-PR13686-6369cee.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11769/HighFidelity-Beta-PR13686-6369cee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11769/HighFidelity-Beta-Interface-PR13686-6369cee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11769/HighFidelity-Beta-PR13686-6369cee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11769/HighFidelity-Beta-Interface-PR13686-6369cee.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
