### PR TITLE
Revert "Case 20200: Update EntityScriptingInterface to not find local entities"

### PR DESCRIPTION
**Pull request by SamGondelman**
Reverts highfidelity/hifi#14547

Test plan:
- Run the script from 14547.  All of the boxes should be red.
- The hand laser should work on the tablet.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16109/HighFidelity-Beta-PR14631-097d2d9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16109/HighFidelity-Beta-PR14631-097d2d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16109/HighFidelity-Beta-Interface-PR14631-097d2d9.exe

**Comment by shanzzam** [comment]
addresses this ticket https://highfidelity.manuscript.com/f/cases/20401/Tablet-Unable-to-open-tablet-apps-with-the-laser

**Comment by qliejahner** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16149/HighFidelity-Beta-PR14631-097d2d9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16149/HighFidelity-Beta-PR14631-097d2d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16149/HighFidelity-Beta-Interface-PR14631-097d2d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16149/HighFidelity-Beta-PR14631-097d2d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16149/HighFidelity-Beta-Interface-PR14631-097d2d9.exe

**Pull request merged**
