### PR TITLE
Fix failing POST_BUILD steps on Windows with spaces in build path

### PR DESCRIPTION
**Pull request by birarda**
- fix failing POST_BUILD steps on Windows with spaces in build path

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Run a clean build on Windows with a build path that has a space in it. With the code on this PR it should succeed. With the code on master it will have multiple errors in POST_BUILD steps.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9d1916eea0cf4c63689df333a2affa51046a84d available at: https://gist.github.com/51a586d0c3ef3df9320aeb680b5fae34<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9962-c9d1916.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9962-c9d1916.dmg

**Comment by zfox23** [comment]
Thank you for this! Notifying @anshuman64 and @cozza13

**Comment by cozza13** [comment]
Still had 1 error (this used to be 12)
capture

**Pull request merged**
