### PR TITLE
Fix tablet scrolling for QT 5.9 and  QT 5.6

### PR DESCRIPTION
**Pull request by druiz17**
Make scrolling work correctly on both Qt5.9 and Qt5.6

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Generally, use the tablet in HMD and Desktop mode
- make sure that scrolling works correctly in Tablet home screen, goto, and the marketplace.

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1549/HighFidelity-Beta-PR10940-2f192fd48a23e8895c7e898ebfcdf74bb5bd7fe7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1549/HighFidelity-Beta-PR10940-2f192fd48a23e8895c7e898ebfcdf74bb5bd7fe7.exe

**Comment by CainFoool** [comment]
# Test Passed
Test | HMD | Desktop
-------- | -------- | --------
Generally, use the tablet in HMD and Desktop mode | Pass | Pass
make sure that scrolling works correctly in Tablet home screen, goto, and the marketplace. | Pass | Pass

Working perfectly.

One issue I noticed (not related to this PR) during testing, when you load up the Tablet and click Menu, when you click on the Menu button at the top left it de-capitalizes all of the Menu Icons. See gif below:


I don't have FogBugz access else I'd report this - happening in latest Dev and Master.

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by sethalves** [comment]
Thanks @CainFoool .  I opened a fogbugz for the menu case change.

**Comment by CainFoool** [comment]
Thanks @sethalves - Appreciated!

**Pull request merged**
