### PR TITLE
Beta Release 33 - Includes up to Developer Release 5951

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Fix audio failures that occur when a broken driver returns mixFormat that is invalid/unsupported.
* Add opaques/skinned to forward rendering path 
* Add a volume slider beneath each user's VU meter in the PAL. Using this slider, users can adjust the volume of each avatar present in a domain individually. 
* When calling requestUsernameFromID() from a script you can call you own username
* Fixed a bug that kept physics and scripts from starting when logging-in near (but not looking at) something that's physical 
* Add an command line argument that enables heartbeat stats sending at 1s
* Remove ignored avatars from PAL when they disconnect 
* Allow users to edit their Display Name from within the PAL via an editable TextInput field
* Consume fewer cpu cores in AssetServer when interface is running locally 
* Add on/off switch to ambisonic/ambient sound emitter 
* Removing some PAL-related interface log spam 
* Introducing type Meta to the render items of the scene. The type Meta for a render item is used to indicate that a render item supervise sub items and act as a group of render items (typically shapes). https://github.com/highfidelity/hifi/pull/9410
* Create render forward version of pixel shaders 
* Additional trace details for GPU timing, frame data updates 
* Remove a line of old code in Clara.io download 
* Add "ADMIN" labels to the right of Display Names on PAL cards corresponding to domain administrators. 
* Updates the visual style of the letterbox popups that appear when clicking on "[?]" buttons. 
* Initial analytics for PAL usage 
*  Fix "Last Editor" popup bug
* Fix warnings for signed comp in AudioMixerSlavePool
* PAL: Fix card visibility when selecting out-of-table users 
* Fix Places / Paths anchor in domain settings 
* Use fromUserInput to avoid web entity crashes with bad URLs 
* Fix invalid volume values in injector options silencing all injectors 
* Do not allow grab or far-grab or click while editing objects 
* Update the name of the collision shapes used in edit.js properties 
* Connect audio injector signal to scripting
* Fix Edit.js rescale for decimal values 
* Fix a failure case where isFormatSupported(mixFormat) returns false on some systems, when format is WAVEFORMATEXTENSIBLE with channels > 2, audio enhancements in "Speaker Properties/Enhancements" are not disabled, and dwChannelMask is nonzero but does not match the speaker configuration. 
* Cleanup debug for safe web entity URLs 
* Use host check for entity script whitelist instead of startsWith 
* Fix a bug in the Steam JS API that caused the app to crash. 
* New Assignment type called the **Entity Script Server** as well as a new entity property called **serverScripts** 
* Fix intermittent Clara.io download crashes 
* Fix Overlay-as-child of model entity with reg point 
* Change server to default to not auto-muting 
* Optimize, prioritize, and timebox processing of avatar updates 
* Throttle audio with PI controller, by node 
* Edit entity filter
* Avatar mixer bandwidth optimization
* Fix audio-mixer timing for WIN32 
* Add debug logging to entity server startup in the case of having a filter 
* Display avatar count in table header 
* Fixes the audio encoding of a scripted agent that plays back a recording.

### CODE REVIEW

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: ae8d0d194887a42719e01afd2718f4120ec5baf1 available at: https://gist.github.com/43226f7256ef92ed8986831c076cd2cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-ae8d0d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-ae8d0d1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ae8d0d194887a42719e01afd2718f4120ec5baf1 available at: https://gist.github.com/43226f7256ef92ed8986831c076cd2cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-ae8d0d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-ae8d0d1.dmg

**Comment by Nex-Pro** [comment]
In progess

**Comment by OmegaHeron** [comment]
Here's some data for performance I was specifically asked to run.

CPU compared to last RC (5909) shows no change of consequence (i5 6500 CPU/GTX970 GPU)

5909vs9545

On stack side the addition of entity-script-server (ESS from here on) shows minor impact on system resources, *unless -- and this is an important unless*, running in a domain with a high object count.  With standard sandbox scene you'll never notice ESS has been added in so far as system resource use is concerned.  Running in a domain with thousands of objects you will definitely notice ESS has arrived as it can easily red line CPU.  This is known stuff as we discussed it during the ESS QA.  For what it's worth, my opinion is;  ESS should not be deployed to RC or, at least, not enabled by default until it has some additional refinements.

Stepping outside the numbers, this build tends to be less prone to stutter with DK2,but, load times are a bit longer (trade off for lowered thread count on i5).

Sparse texture code is disabled, regardless of cpu or menu choice (as intended).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 00b15ff74deb8b14244ce1802b4f432ebb33bdde available at: https://gist.github.com/43226f7256ef92ed8986831c076cd2cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-00b15ff.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-00b15ff.dmg

**Comment by OmegaHeron** [comment]
In so far as failure of ambisonic sound playing is concerned... I can't find a previous dev release where adding an ambisonic source from marketplace fails (within builds that would impact this PR).  I tried adding other objects from (HF) market and succeeded so.. it seems it's either a combination of PRs together that leads to ambisonic sound addition failure or a "just me thing".  Will wait for other QA Test persons to test ambisonic addition.

**Comment by kevinmthomasse** [comment]
testing

**Comment by Nex-Pro** [comment]
@OmegaHeron  we concur:  fail for ambisonic. For two geographically separate clients.

**Comment by Nex-Pro** [comment]
### PR #9545 Beta Release 33

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive


## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** 
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS Restart server after deleting ent from atp: Ent removed from domain.
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A ignore
**QA Pass**: **QA Pass** 

**Additional Test Results + Observations**:
Observed hesitancy in far grab manipulation. ( compared to current release )

### Domain Stats HMD Mode:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |89 |90 |89
**Present New Rate**: |89 |90 |90
**CPU Buffer Count**: |2719 |3885 |720
**GPU Buffer Count**: |787 |607 |185
**CPU Memory Usage**: |36961104 |62846032 |24058320
**GPU Memory Usage**: |16644208 |30640240 |17496176
**CPU Texture Count**: |291 |280 |123
**GPU Texture Count**: |240 |162 |104
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |113456576 |476272160 |19748384
**GPU Texture Memory Usage**: |1023552787 |939709411 |572096185
**GPU Virtual Memory Usage**: |1023552787|939709411|572096185
**Triangle Count**: |501946 |543624 |54460
**Triangle Rate**: |55771777 |49420363 |4950909
**API Drawcall Count**: |168 |113 |16
**Drawcall Count**: |3932 |480 |18
**Drawcall Rate**: |436888 |43636 |1636
**State Changes Texture Count**:|344 |168 |37
**Pipeline Count**: |64 |36 |22
**Item Opaques**: |247 |171 |3
**Item Translucents**: |114 |22 |4
**Item Lights**: |11 |36 |0
**Timing Opaques**: |1.012 |0.549 |0.085
**Timing Translucents**: |0.222 |0.042 |0.025
**Timing Lighting**: |0.032 |0.03 |0.034
**Render Frame**: |2.137 |2.101 |1.062



### Domain Stats Desktop Mode:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2615 |4199 |720
**GPU Buffer Count**: |754 |1366 |180
**CPU Memory Usage**: |41282384 |64045936 |24058320
**GPU Memory Usage**: |26376304 |44574832 |17221744
**CPU Texture Count**: |321 |287 |124
**GPU Texture Count**: |254 |252 |104
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |103429568 |97277472 |19748384
**GPU Texture Memory Usage**: |821666542 |1100717672 |371782805
**GPU Virtual Memory Usage**: |821666542|1343987304|371782805
**Triangle Count**: |253083 |212959 |27237
**Triangle Rate**: |15817687 |13309937 |1702312
**API Drawcall Count**: |169 |98 |16
**Drawcall Count**: |2983 |233 |16
**Drawcall Rate**: |186437 |14562 |1000
**State Changes Texture Count**:|343 |144 |37
**Pipeline Count**: |60 |32 |24
**Item Opaques**: |247 |144 |2
**Item Translucents**: |105 |18 |5
**Item Lights**: |11 |30 |0
**Timing Opaques**: |0.99 |0.617 |0.07
**Timing Translucents**: |0.166 |0.035 |0.046
**Timing Lighting**: |0.022 |0.025 |0.027
**Render Frame**: |1.961 |1.924 |1.036


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|check
**Test 2**|Install a fresh copy of "Home' and do tutorial|success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|success
**Test 4**|Launch firework, on dev-playa, can other hear?|success
**Test 5**|Switch avatar and make sure it does not crash|success
**Test 6**|Test group functions|Success
**Test 7**|Test Ambisonic audio with markeplace item|Fail see note:
**Test 8**|Ensure that you can distance grab|Can do but some weirdness noted see notes
**Test 9**|Bring up and edit an objects with hand controllers|works apart from user data
**Test 10**|Test PAL functionality|Success

Log spam non-stop on trying to get an ambisonic ent from market. Two clients attempted multiple times.

[01/30 21:19:30] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:30] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:30] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:30] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:30] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache
[01/30 21:19:31] [DEBUG] [hifi.scriptengine.script] script:print()<< Loading ambient sound into cache

ClaraIO Asset to atp: Success.

PAL: All working fine apart from... still able to ban self by clicking on anonymous.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** Untested
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** Unable to get access - not on list for some reason.
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  Ambisonic sounds did not work as expected.  The birds sound worked on and off and was unsuccessful with any of the other sounds from the marketplace.


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2377 |2113 |
**GPU Buffer Count**: |742 |629 |
**CPU Memory Usage**: |31881168 |27018320 |
**GPU Memory Usage**: |17406064 |15038576 |
**CPU Texture Count**: |274 |168 |
**GPU Texture Count**: |216 |100 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |130664816 |237414864 |
**GPU Texture Memory Usage**: |664763771 |381778329 |
**GPU Virtual Memory Usage**: |664763771|381778329|
**Triangle Count**: |275782 |261155 |
**Triangle Rate**: |16222470 |15362058 |
**API Drawcall Count**: |176 |74 |
**Drawcall Count**: |186 |74 |
**Drawcall Rate**: |10941 |4352 |
**State Changes Texture Count**:|383 |108 |
**Pipeline Count**: |74 |30 |
**Item Opaques**: |246 |117 |
**Item Translucents**: |129 |19 |
**Item Lights**: |10 |21 |
**Timing Opaques**: |1.022 |0.749 |
**Timing Translucents**: |0.261 |0.041 |
**Timing Lighting**: |0.014 |0.022 |
**Render Frame**: |1.941 |2.179 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success except `dev-demo` would not allow me rights, access denied.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item|Ambisonic sounds did not work as expected.  The birds sound worked on and off and was unsuccessful with any of the other sounds from the marketplace.
**Test 8**|Ensrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
## Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift
PR #9545 Beta Release 33
Tested Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-ae8d0d1.exe
## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNABLE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** Was unable to test harmonic oscillator. Excluding that test, the Smoke Test was a PASS.
**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2110 |1205 |
**GPU Buffer Count**: |780 |444 |
**CPU Memory Usage**: |20977616 |8267344 |
**GPU Memory Usage**: |13416560 |6367344 |
**CPU Texture Count**: |229 |84 |
**GPU Texture Count**: |190 |62 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |83799216 |30870800 |
**GPU Texture Memory Usage**: |823205528 |425138756 |
**GPU Virtual Memory Usage**: |823205528|425138756|
**Triangle Count**: |463243 |647204 |
**Triangle Rate**: |46324300 |58836727 |
**API Drawcall Count**: |184 |128 |
**Drawcall Count**: |4164 |242 |
**Drawcall Rate**: |416400 |22000 |
**State Changes Texture Count**:|356 |143 |
**Pipeline Count**: |59 |36 |
**Item Opaques**: |270 |320 |
**Item Translucents**: |94 |77 |
**Item Lights**: |11 |47 |
**Timing Opaques**: |0.724 |0.618 |
**Timing Translucents**: |0.103 |0.055 |
**Timing Lighting**: |0.013 |0.015 |
**Render Frame**: |1.211 |1.565 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|unable
**Test 7**|Test Ambisonic audio with markeplace item|FAIL
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|unable

**FAIL:**
Unable to download Ambisonic audio item from Marketplace. I would click on "Get Item" and the red sphere would appear and disappear just as fast.

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 00b15ff74deb8b14244ce1802b4f432ebb33bdde available at: https://gist.github.com/43226f7256ef92ed8986831c076cd2cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-00b15ff.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9545-00b15ff.dmg

**Comment by OmegaHeron** [comment]
@cozza13 - Ambisonic playback is *not* broken.  Using the test files from original ambisonic PR test method (#9125), I'm able to load ambisonic sound file and have it work proper.  I suspect the real issue is something borked on marketplace side and would explain why I couldn't find a PR point in this PR's lineage where it broke.

**Pull request closed without merging**
