### PR TITLE
Don't unnecessarily scroll HTML content when keyboard is raised

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Don't scroll field with focus into vertical middle of screen in Create screens; scroll only as necessary to show field when the keyboard raises.
- Don't scroll Marketplace content when click in Search field.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9543/app_13110_PR_5021778dc062ce669f7cd858025040ff6ecd5782.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9543/HighFidelity-Beta-PR13110-5021778dc062ce669f7cd858025040ff6ecd5782.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9543/HighFidelity-Beta-Interface-PR13110-5021778dc062ce669f7cd858025040ff6ecd5782.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9543/HighFidelity-Beta-PR13110-5021778dc062ce669f7cd858025040ff6ecd5782.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9543/HighFidelity-Beta-Interface-PR13110-5021778dc062ce669f7cd858025040ff6ecd5782.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Page does not scroll when the text box is still in view.

**Pull request merged**
