### PR TITLE
Remove some deprecated functions from the Controller API

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because functions not used in hifi or hifi-content repositories.

Forum notice: https://forums.highfidelity.com/t/controller-getbuttonvalue-and-2-related-being-removed-from-the-api/14010

Manuscript case: https://highfidelity.manuscript.com/f/cases/14139

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10348/HighFidelity-Beta-PR13297-a7a0cfe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10348/HighFidelity-Beta-PR13297-a7a0cfe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10348/HighFidelity-Beta-Interface-PR13297-a7a0cfe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10348/HighFidelity-Beta-PR13297-a7a0cfe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10348/HighFidelity-Beta-Interface-PR13297-a7a0cfe.exe

**Comment by sethalves** [comment]
This PR simply removes some unused code, so no QA is needed.

**Pull request merged**
