### PR TITLE
actually fix toolbar from completely dispersing

### PR DESCRIPTION
**Pull request by druiz17**
This PR fixes the issues I introduced in this PR, https://github.com/highfidelity/hifi/pull/11627

### CODE REVIEW

**Comment by druiz17** [comment]
- Test plan

- In desktop mode and open running script (make sure you have developer settings enabled from the menu)
 -reload just the default script a few times. The toolbar should be present after the script finishes reloading
- Move you avatar around and the toolbar should fade out, and when you stop moving the toolbar should reappear.

**Comment by Nex-Pro** [comment]
Fail 

Can have both hands in individual grabbable ents with only one lit. ( edge case )  Otherwise good.

**Comment by Nex-Pro** [comment]
ignore previous, was on wrong page

**Comment by Nex-Pro** [comment]
awaiting win build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4285/HighFidelity-Beta-PR11635-f2ad61934b597064e5bfb3cd3007b3e566412998.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4285/HighFidelity-Beta-PR11635-f2ad61934b597064e5bfb3cd3007b3e566412998.exe

**Comment by Nex-Pro** [comment]
T E S T I N G win10

**Pull request merged**
