### PR TITLE
Sign release apk. Remove daydream intent from manifest

### PR DESCRIPTION
**Pull request by gcalero**
Changes in this PR
- Add new Gradle variables that can be passed in gradle invocation (HIFI_ANDROID_KEYSTORE,
HIFI_ANDROID_KEYSTORE_PASSWORD, HIFI_ANDROID_KEY_ALIAS, HIFI_ANDROID_KEY_PASSWORD)
- The release build must be signed with the key provided in the keystore
- Removes the daydream intent from AndroidManifest.xml to fix the error during the upload to PlayStore

Changes needed in **development environment**
- Add the new variables to $HOME/.gradle/gradle.properties

Changes needed in **Jenkins environment**
- The new variebles need to be filled in gradle invocation using -P<VAR>=VALUE
- Get/generate the keystore that will be used for release build signing

Test plan
=======
- Generating a **release build** using the console should produce a signed build (i.e. 
_/opt/gradle/gradle-4.3.1/bin/gradle -PHIFI_ANDROID_PRECOMPILED=/Users/gcalero1984/android/hifi_externals/ -PRELEASE_NUMBER=8888 -PRELEASE_TYPE=RELEASE setupDependencies_
_/opt/gradle/gradle-4.3.1/bin/gradle -PHIFI_ANDROID_PRECOMPILED=/Users/gcalero1984/android/hifi_externals/ -PRELEASE_NUMBER=8888 -PRELEASE_TYPE=RELEASE assembleRelease_

- Use $ANDROID_HOME/build-tools/26.0.3/apksigner verify -v <apk> to check if an apk is signed
- Debug build shouldn't be signed

*** This PR only affects android builds ***

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10136/HighFidelity-Beta-PR13242-8c6166d6e5dbd92eda549693f6ca0ba4c63d2d5b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10136/HighFidelity-Beta-Interface-PR13242-8c6166d6e5dbd92eda549693f6ca0ba4c63d2d5b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10136/HighFidelity-Beta-PR13242-8c6166d6e5dbd92eda549693f6ca0ba4c63d2d5b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10136/HighFidelity-Beta-Interface-PR13242-8c6166d6e5dbd92eda549693f6ca0ba4c63d2d5b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10216/HighFidelity-Beta-PR13242-a36c41f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10216/HighFidelity-Beta-PR13242-a36c41f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10216/HighFidelity-Beta-Interface-PR13242-a36c41f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10216/HighFidelity-Beta-PR13242-a36c41f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10216/HighFidelity-Beta-Interface-PR13242-a36c41f.exe

**Comment by SamGondelman** [comment]
These changes only affect the android build process and we've tested them internally.

**Pull request merged**
