### PR TITLE
allow larger sized messages

### PR DESCRIPTION
**Pull request by ZappoMan**
Test plan:
- smoke test, make sure everything works
- try using Messages.sendMessage(channel, message) to send a message larger than 65535 characters in length. in master this will fail and cause random side effects, in this PR it will work.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 83638d3cd9fa85db39cf3b914a342df3be6ffecd available at: https://gist.github.com/cf14f20c1cb5499017d2a3fc0722ccb3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9654-83638d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9654-83638d3.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
dude I was like woah cus the thing was, well, it was heavy man I was like pastin all the words, like so many words and the words were good in their own way and righteous too and clean and without the things that would mess with the strings and stuff and there were so many and even tho they wus like cradled within. Within the quotey things like you know they look like those lil critters on the paper at each end of all the words and in the right places with spaces and no curly braces. 
And I like got the word man from , well you know the console and he said to me that it wasn't closed like the string thing wusnt like closed at the end and it was only a hundred twenny four thou man like not even a million. But that console dude spat it back at me and harshed my mellow with his prose. So like man I come to you with my hands and my heart open prayin for guidance as to how I can convince the console dude to accept my offerins and like chew on em and send em on their journey inside the channel of message cus without your wisdom dude this is gonna end up bad like a string that is unclosed or a scope that lost it brace of closiness.

**Comment by Nex-Pro** [comment]
Hey, 's all good man like, sweet and takes it and runs with it and like the stuff is all cool and it like gave me a sign from like the void and the void isn't a void cus it's like full of words and the words just keep on comin 'til there's like so many man, like so many you can't count em all cus there's like the right number but it's a big number it's like bigger than a lot but maybe less than all of em but sure a lot. And there was this flash of light and strange words were flyin from my fingers man to the tv and it was like some kind of weird incantation and  maybe like even wizardry or shaman chants or somesuch. But anyhow the the spell I counjoured made them, it made all the words till they waus dancin and flashin across my tv man. words man they were there then they got crushed man like seriously crushed then squeezed into like a zipper of smooshed words , like all of em in a space so small man like really really small and it's there man like really there.
[hifi-log_192.168.0.2_2017-02-13_02.08.24.txt.zip](https://github.com/highfidelity/hifi/files/769934/hifi-log_192.168.0.2_2017-02-13_02.08.24.txt.zip)

**Pull request merged**
