### PR TITLE
case 19562: GLES - Use TBO instead of SSBO and make shaders use it when it is not gl45 (v0.75.0-rc)

### PR DESCRIPTION
**Pull request by Cristo86**
https://highfidelity.manuscript.com/f/cases/19562/Avatars-do-not-load-in-Android

Rollback GLES to work as GL41 does as those storage blocks are not mandatory in GLES implementations/devices.

**Test plan**

1. Launch the app on Android
2. Enter any domain or last location
3. My Avatar should render (before this PR it isn't happening).
4. Windows/Linux/macOS rendering shouldn't be affected, please check.

**Note**
On some Mali GPU Devices (Like Huawei Mate 9 Pro - Use https://play.google.com/store/apps/details?id=de.saschawillems.glescapsviewer&hl=en app to confirm, OpenGL ES - Vendor and Renderer) Interface may flicker being unusable, that's a different issue not addressed in this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14649/HighFidelity-Beta-PR14333-6e281a7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14649/HighFidelity-Beta-PR14333-6e281a7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14649/HighFidelity-Beta-Interface-PR14333-6e281a7.exe

**Comment by qaAdamSmith82** [comment]
Fail @conklin94122 

This fixes the avatar issue on Adreno based devices, but break all rendering on Mali based devices.

Repro:
1.  Launch High Fidelity PR14333 on a device using a Mali GPU.
2.  Enter any domain
3. Observe results

Phones used for QA:
1. Samsung Galaxy Note 9 - Adreno
2. HUAWEI Mate 9 Pro - Mali

Currently running a rendering test for PC.  Mac has not built yet.

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14669/HighFidelity-Beta-PR14333-6e281a7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14669/HighFidelity-Beta-Interface-PR14333-6e281a7.dmg

**Comment by qaAdamSmith82** [comment]
Stopping Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14669/HighFidelity-Beta-PR14333-6e281a7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14669/HighFidelity-Beta-Interface-PR14333-6e281a7.exe

**Comment by qlimnavarro** [comment]
FAIL @conklin94122 
Mac is crashing consistently upon loading domains.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2550245/hifi-log.txt)

**Comment by Cristo86** [comment]
> FAIL @conklin94122
> Mac is crashing consistently upon loading domains.
> [hifi-log.txt](https://github.com/highfidelity/hifi/files/2550245/hifi-log.txt)

Lookiing into it
(I grabbed this crash report from the Console)
[interface_2018-11-05-165902_Cristians-MacBook-Pro copy.txt](https://github.com/highfidelity/hifi/files/2550403/interface_2018-11-05-165902_Cristians-MacBook-Pro.copy.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14836/HighFidelity-Beta-PR14333-6e281a7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14836/HighFidelity-Beta-PR14333-6e281a7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14836/HighFidelity-Beta-Interface-PR14333-6e281a7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14836/HighFidelity-Beta-PR14333-6e281a7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14836/HighFidelity-Beta-Interface-PR14333-6e281a7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by Cristo86** [comment]
What GPUs do QA Macs have?

**Comment by qlimnavarro** [comment]
@Cristo86 AMD Radeon Pro 560 4096MB

Got 2 of them here and they are still crashing.

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Build crashes after about 30 seconds on Mac. Tested on 2 machines with the following specs:

macOSx High Sierra
Intel i5 ~3.4 GHz (4 cores)
8GB RAM
AMD Radeon Pro 560 4096MB

[hifi-log (1).txt](https://github.com/highfidelity/hifi/files/2558207/hifi-log.1.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2558208/hifi-log.txt)

**Comment by Cristo86** [comment]
> Fail @conklin94122
> Build crashes after about 30 seconds on Mac. Tested on 2 machines with the following specs:
> 
> macOSx High Sierra
> Intel i5 ~3.4 GHz (4 cores)
> 8GB RAM
> AMD Radeon Pro 560 4096MB
> 
> _Additional Notes:_ Build is not crashing on Windows 10 with AMD Radeon R9 200 4072MB. Avatars are fully functional on Android.
> 
> [hifi-log (1).txt](https://github.com/highfidelity/hifi/files/2558207/hifi-log.1.txt)
> [hifi-log.txt](https://github.com/highfidelity/hifi/files/2558208/hifi-log.txt)

Hi, for more info can you add the "Report..." that is suggested by macOS after the crash?
Another way to access it is opening the Console.app application (it may be inside "Utilities") and check the log at the crash moment, the log itself provides a _link_ to the report.
That's important because it has stack traces by thread.

**Comment by qlimnavarro** [comment]
@Cristo86 Apologies for the delay, yes here is the log in rtf format.
[MacCrashReport.txt](https://github.com/highfidelity/hifi/files/2559050/MacCrashReport.txt)

Upon further testing, we got the Mac to **not** crash. Mac seems to crash in the serverless/localhost "Welcome to hifi" tutorial zone spawn point. 

This is still an issue as the average game rate on Mac is 5 in this PR. Flying around in serverless the FPS was between 1 and 2. Essentially unplayable.
In addition to this, I forced GL41 on Windows 10 AMD and did not crash.
image

**Comment by Cristo86** [comment]
Checking the log, it looks like the same crash I have on my end (but in theSpot-dev). So you could have Mac stable outside serverless/localhost?

**Pull request closed without merging**
