### PR TITLE
Fixing the warning issue and tweaking the ao blur constants

### PR DESCRIPTION
**Pull request by samcake**
- address the nasty double to float cast warning

- tweek the blur stride constant used in the AO blur effect

- removing unused attributes and lines from the shader

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6bcd7f10ad0089b5422016b30623d97a400ff244 available at: https://gist.github.com/06960dc4b21034c88532<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6901.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6901.dmg

**Comment by ZappoMan** [comment]
Ready to merge once it bullds!!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 24d1f113f8ca0bf65fde98ba65936579e57051d7 available at: https://gist.github.com/06960dc4b21034c88532<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6901.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6901.dmg

**Comment by murillodigital** [comment]
huh this actually passed across platforms... not sure why its declared failed. Looking into it.

**Comment by murillodigital** [comment]
@ZappoMan so this is success:

image

Considering the need of this PR to go in so the rest can pull upstream and get no warning, feel free to merge if you're comfortable with this. Dont want to delay merging until I figure out what happened here.

**Pull request merged**
