### PR TITLE
Fix tractor-action initial crazy

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/11442/initial-far-grab-often-warps-target-far-away-and-quicky-returns-it

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6859/app_12322_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6859/HighFidelity-Beta-PR12322-eace2268a8fa7b9d43f8e5587a53bd3b2ce1f219.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6859/HighFidelity-Beta-PR12322-eace2268a8fa7b9d43f8e5587a53bd3b2ce1f219.dmg

**Pull request closed without merging**
