### PR TITLE
Beta Release 23 - Includes up to Developer Release 5572

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* display location and connection status in address bar when it doesn't have focus 
* Support external GL textures with proper fencing
* Initial work towards making performance testing reproducible
* Remove all usage of oglplus
* Fix model overlay visibility and texture properties
* Add ability to parent overlays to MyAvatar for use across servers
* Add category to log lines
* Fix intermittent channel swapping
* Fix CMAKE warning about un-unit-testable CPP file in physics unit tests
* Add flag to interface to have it start the sandbox server
* Fix 16khz support and hot-unplugging audio devices
This PR fixes two unrelated audio issues on Windows, by updating qtaudio_wasapi.dll. 
* Fix ScriptEngine not properly resolving paths
* Trigger unequip at a more lenient angle and with the secondary trigger
* Add setMapping to ATP scripting interface and fix threading bug
* added a command-line tool for checking on health of a domain-server and ACs 
* Add retrying of script requests
* Remove QML threaded rendering
* Fix script paths not resolving correctly
* HMD Keyboard
* Kill agents in avatar mixer when they stop being avatars
* Update teleport.js to ignore invisible or collisionless objects and disallow teleporting to certain surfaces
* init the accumulator for script elapsed time
* Updated Tutorial content
* Fix page size usage in gpu buffers
* Fix away HMD unmouted logic
* Fix GPU texture counter, better logging for memory pressure
* Send High Fidelity user's visibility when users.js starts up
* Adjustments to grab indicators
* Adapt shader for GL ES support
* Allow equipped object to follow hand and not controller
* Fix Asset Browser add-to-world
* Prevent crashes in openvr on shutdown
* Have avatar sounds negotiate codecs
* Update ds path queries to be reliable
* Update window size automaticatlly
* Bug fixes in oculus_touch default mapping
* Fix edit.js not allowing imports when you only have temp rez permissions
* Prevent crash on exit
* Additional plugin debugging, better plugin resource cleanup
* Make agent avatar animations work again, and use them in crowds 
* Update ScriptCache to clear ATP assets when disconnected from a domain
* Don't crash on OpenVR activation when SteamVR isn't running
* Better handling of the teleport target overlays to prevent flashing
* Fix entity-import with only tmp-rez rights
* Make laser pointers work even while content is loading
* Make marketplace tablet be clientOnly fixes 
* Close button and frame on goto address bar. 
* Fix cellscience ac script load
* Fixes for various networking/ATP stuck download failure cases
* Fix AMD crash caused by missing glFlush
* Never interact with hud elements while holding something
* HMD keyboard polishing
* Avoid uninitialized oculus gl calls
* Update gamepad help image
* Switchable placeholder for domain-connection failure, currently a modal
* Directory picker works when choosing the initial value
* Don't override place name path with index path
* Add GPU buffer and texture current counts to the main stats display
* Fix play button in cellscience
* Speculative fix for crash in FBXReader.cpp
* Fix deadlock when removing tablet
* Fix bug in Script.include when urls is empty
* Fix suggestion card appearing behind keyboard
* Replaces UDT default congestion control with TCP (Vegas)
* Move HF access token to authorization header
* Add virtual keyboard for steam username collision
* Move HFWebEngineProfile to interface/networking
* Fixed HandcontrollerGrab distance unequip
* Ensure model attachment lifetimes
* Rate limit QML web surfaces
* Unit scaled address bar
* Force valid file path for asset file mapping operations
* Update users.js to be minimizable when logged out, and by default
* Fix invalid ShapeKey ref
* Adjustment to position and visibility of grab sphere.
* Fix intermittent crash on teleport from contextless Qt connection
* Remove the use of implicit ids in geometry cache
* Fix sequence number race condition
* Fix some audio mixer data races
* Added attachment support to crowd-agent
* Fix crash on startup
* Remove showing of overlays in away.js
* Fix flicker in system (inside the hud) hand-lasers.
* Fix offscreen QML texture leak, improve texture sharing for same size surfaces
* Always go to dev-welcome when not using stable services
* Fix for sandbox startup issue
* Undo bad script-engine AC change
* Fix some data-races in logging system
* Heartbeats need to happen while waiting for sandbox
* Show hand controllers in away.js
* Report offscreen texture memory usage in stats
* Add more GPU stats, make stats easier to read
* Add free GPU memory to the displayed stats
* New texture memory scheme
* Add Bullet profile info to PerformanceTimer stats

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 984661446855ee9c438bf5112afd8080776f185c available at: https://gist.github.com/9818cc10a581bc5398e03074b2970945<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-9846614.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-9846614.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. When using the ```playa-performance.js``` test on the ```localhost, dev-playa and dev-demo``` domains, when switching through the domains with the UI tool, a UI popped up saying , ```Unable to connect to the domain.  Click the GOTO button on the toolbar to connect to another domain```.  This is not an error or an issue as the tool worked successfully as expected with no issues however wanted to present this in the case that it should not be expected behavior.  Screen-shot attached.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |58 |51 |35
**CPU Buffer Count**: |3748 |2767 |1735
**GPU Buffer Count**: |943 |885 |383
**CPU Memory Usage**: |68255744 |42934272 |27439104
**GPU Memory Usage**: |27381760 |19001344 |14647296
**CPU Texture Count**: |335 |277 |173
**GPU Texture Count**: |242 |209 |62
**GPU Transfer Count**: |0 |21 |2
**CPU Texture Memory Usage**: |439309108 |482791408 |408081112
**GPU Texture Memory Usage**: |1051456846 |651294922 |209479268
**GPU Virtual Memory Usage**: |1046361316|907978231|333973299
**Triangle Count**: |541425 |516032 |102651
**Triangle Rate**: |36095000 |39694769 |5402684
**API Drawcall Count**: |242 |225 |42
**Drawcall Count**: |248 |225 |42
**Drawcall Rate**: |16533 |17307 |2210
**State Changes Texture Count**:|250 |231 |52
**Pipeline Count**: |17 |8 |18
**Item Opaques**: |297 |429 |97
**Item Translucents**: |34 |77 |94
**Item Lights**: |21 |80 |15
**Timing Opaques**: |0.922 |1.505 |0.322
**Timing Translucents**: |0.038 |0.172 |0.488
**Timing Lighting**: |0.065 |0.108 |0.132
**Render Frame**: |1.746 |3.002 |1.839

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

CPU Analysis compared to last RC (Build 5429).  5 Runs of 2 minute duration each, loading old standard home scene.  This shows only Interface CPU use.  Red = This PR (8899) Blue = RC22 (5429)

8899vs5429

This build is both much more consistent in CPU use and reflects a dramatically faster (from cache) scene loading time.  In 5429 (blue trace) scene was never fully loaded until the 3rd set of CPU spike where this PR is completed before 2nd set of spikes.

Continuing to Memory Leak tests then standard QA battery.

**Comment by Nex-Pro** [comment]
### PR #8899

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

## QA Test
**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: UNTESTED
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS

**Additional Test Results + Observations**:

	Observed models at devPlaya appearing at wrong locations until head rotated away and back
(*** not specific to this PR. This has been reported previously***).

	QML keyboard would not switch to symbol/numeric while typing this. 
We need a confirmation sound other than the click that the hand controller makes. 
Typing on the qml keyboard is an unrewarding experience. 

	It is still possible to light the fuse a second time in the vive tutorial.

	Squeezing hand controllers releases gripped items. 
This, IMO, is incorrect. I believe Philip concurs. Should only release equipped items.

	After leaving interface to run for more than 2 hours
I observed that framerates had climbed to ~180 and present rate almost 500 in desktop @1080. 
	@4k gpu use rose to 97% and frame and present rate of 149.
	Switching between 1080 and 4k shows an increase in gpu memory usage
of around 500mb.
	With interface @4k gpu was consuming 90% max power consumption 
with no other apps running apart from Slack and a text editor.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |90 |85
**CPU Buffer Count**: |1948 |3835 |3639
**GPU Buffer Count**: |670 |1044 |971
**CPU Memory Usage**: |23613440 |63713280 |51920896
**GPU Memory Usage**: |16646144 |32370688 |27312128
**CPU Texture Count**: |186 |281 |346
**GPU Texture Count**: |165 |195 |310
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |30689416 |647910736 |142559064
**GPU Texture Memory Usage**: |991790947 |2006549258 |1592408274
**GPU Virtual Memory Usage**: |987574664|2001284400|1581075787
**Triangle Count**: |522671 |1568126 |1322368
**Triangle Rate**: |47515545 |156812600 |132236800
**API Drawcall Count**: |195 |274 |359
**Drawcall Count**: |6003 |626 |2532
**Drawcall Rate**: |545727 |62600 |253200
**State Changes Texture Count**:|350 |305 |506
**Pipeline Count**: |74 |32 |67
**Item Opaques**: |233 |512 |349
**Item Translucents**: |62 |43 |46
**Item Lights**: |16 |85 |15
**Timing Opaques**: |0.773 |1.343 |1.314
**Timing Translucents**: |0.119 |0.098 |0.114
**Timing Lighting**: |0.098 |0.17 |0.136
**Render Frame**: |1.648 |2.77 |2.445

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**CHECK**
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|**USED NEW TUTORIAL as shipped.**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?|**UNTESTED**
**Test 5**|Switch avatar and make sure it does not crash|**SUCCESS**
**Test 6**|Test group functions|**UNTESTED**
**Test 7**|Retest the kick function|**UNTESTED**
**Test 8**|Enrure that you can distance grab|**SUCCESS**
**Test 9**|Being up and edit an objects with hand controllers|**SUCCESS** Not good but works
**Test 10**|Modify a models userdata and make sure it works|**SUCCESS**
**Test 11**|Grab objects in dev-demo|**SUCCESS** 

8899_framerates


Tests outstanding: These require more than one user.

Group functions
Kick
Harmonic Oscillator
3rd party hearing fireworks on dev-playa

**Comment by OmegaHeron** [comment]
System Memory use over 6 minutes or so - visiting multiple domains at random, interrupting loads by leaving, rapid domain changes etc etc.  No leak indications seen.

8899ram

Upward spike at end is Interface closing - that's normal and result of how I setup test instrumentation.

**Comment by Nex-Pro** [comment]
Interface exited cleanly. Then GPU load dropped to 10% power consumption to 24% memory dropped from 4990 to 1418

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop Mode - 1600x900 Maximized Window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |1618 |3978 |4030
**GPU Buffer Count**: |633 |1367 |1121
**CPU Memory Usage**: |15155200 |64147456 |76308480
**GPU Memory Usage**: |10108928 |43671552 |46325760
**CPU Texture Count**: |194 |298 |361
**GPU Texture Count**: |162 |253 |317
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |71256408 |160580888 |136799256
**GPU Texture Memory Usage**: |607472967 |1892053073 |1304054132
**GPU Virtual Memory Usage**: |607472967|1892053073|1304054132
**Triangle Count**: |231334 |882800 |413876
**Triangle Rate**: |14458375 |55175000 |24345647
**API Drawcall Count**: |185 |328 |266
**Drawcall Count**: |4364 |371 |2098
**Drawcall Rate**: |272750 |23187 |123411
**State Changes Texture Count**:|341 |339 |372
**Pipeline Count**: |88 |38 |87
**Item Opaques**: |224 |461 |252
**Item Translucents**: |97 |48 |42
**Item Lights**: |16 |84 |14
**Timing Opaques**: |0.75 |1.352 |0.783
**Timing Translucents**: |0.143 |0.068 |0.129
**Timing Lighting**: |0.1 |0.137 |0.113
**Render Frame**: |1.795 |2.747 |1.881

Desktop Mode 1600x900 Maximized Window - vsync unlocked via NV control panel.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |391 |256 |351
**Present Rate**: |391 |256 |350
**Present New Rate**: |341 |227 |273
**CPU Buffer Count**: |1555 |3936 |4320
**GPU Buffer Count**: |592 |1356 |1236
**CPU Memory Usage**: |14917632 |63971328 |74014720
**GPU Memory Usage**: |9969664 |44171264 |40632320
**CPU Texture Count**: |190 |296 |360
**GPU Texture Count**: |159 |255 |320
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |74679576 |156321048 |121005080
**GPU Texture Memory Usage**: |601880555 |1897645473 |1325091185
**GPU Virtual Memory Usage**: |601880555|1897645473|1325091185
**Triangle Count**: |228482 |879571 |748526
**Triangle Rate**: |114241000 |175914200 |187131500
**API Drawcall Count**: |173 |398 |443
**Drawcall Count**: |2984 |484 |1350
**Drawcall Rate**: |1492000 |96800 |337500
**State Changes Texture Count**:|313 |412 |598
**Pipeline Count**: |60 |59 |64
**Item Opaques**: |222 |461 |274
**Item Translucents**: |63 |75 |45
**Item Lights**: |16 |79 |13
**Timing Opaques**: |0.71 |1.49 |0.795
**Timing Translucents**: |0.119 |0.102 |0.129
**Timing Lighting**: |0.056 |0.188 |0.113
**Render Frame**: |1.42 |2.939 |1.814

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |2342 |4314 |4337
**GPU Buffer Count**: |849 |1456 |1315
**CPU Memory Usage**: |40513536 |78716928 |74047488
**GPU Memory Usage**: |20025344 |48066560 |42401792
**CPU Texture Count**: |199 |303 |359
**GPU Texture Count**: |175 |261 |348
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |33646472 |180737808 |17044504
**GPU Texture Memory Usage**: |848921800 |2085066569 |1634409281
**GPU Virtual Memory Usage**: |848921800|2085066569|1634409281
**Triangle Count**: |377419 |1842410 |1024951
**Triangle Rate**: |29032230 |141723846 |85412583
**API Drawcall Count**: |134 |347 |285
**Drawcall Count**: |4220 |755 |2347
**Drawcall Rate**: |324615 |58076 |195583
**State Changes Texture Count**:|248 |361 |436
**Pipeline Count**: |58 |48 |56
**Item Opaques**: |172 |482 |328
**Item Translucents**: |99 |77 |55
**Item Lights**: |14 |83 |14
**Timing Opaques**: |0.603 |1.558 |1.013
**Timing Translucents**: |0.146 |0.095 |0.14
**Timing Lighting**: |0.135 |0.225 |0.113
**Render Frame**: |1.809 |2.852 |2.107

**Comment by OmegaHeron** [comment]
**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Yes
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Yes
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Retest the kick function|Pass
**Test 8**|Enrure that you can distance grab|Not tested
**Test 9**|Being up and edit an objects with hand controllers|Not tested
**Test 10**|Modify a models userdata and make sure it works|Pass
**Test 11**|Grab objects in dev-demo|Pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a28ca670a1191b43abbec1aba88b7c7844567b2 available at: https://gist.github.com/9818cc10a581bc5398e03074b2970945<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-4a28ca6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-4a28ca6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8d692c1d162fddf8e2e344369f19f846c9f2f555 available at: https://gist.github.com/9818cc10a581bc5398e03074b2970945<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-8d692c1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-8d692c1.dmg

**Comment by ctrlaltdavid** [comment]
Tried using the Marketplace table in HMD with a mouse and can't: the tablet displays but the mouse pointer keeps getting recentred in the screen: as soon as you move the mouse pointer it jumps back to the centre so is unusable.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf7d19a8052ee5ba0340ff596929c3e4b53240a8 available at: https://gist.github.com/9818cc10a581bc5398e03074b2970945<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-bf7d19a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8899-bf7d19a.dmg

**Pull request merged**
