### PR TITLE
BUGZ-516: last-heard-from monitoring on domain server

### PR DESCRIPTION
**Pull request by roxanneskelly**
Test debug logging.  Will be spammy so do not merge

https://highfidelity.atlassian.net/projects/BUGZ/issues/BUGZ-516

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19735/HighFidelity-Beta-PR15664-c568e7c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19735/HighFidelity-Beta-Interface-PR15664-c568e7c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19735/HighFidelity-Beta-PR15664-c568e7c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19735/HighFidelity-Quest-Beta-PR15664-c568e7c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19735/HighFidelity-Beta-PR15664-c568e7c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19735/HighFidelity-Beta-Interface-PR15664-c568e7c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19757/HighFidelity-Beta-PR15664-6a66e15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19757/HighFidelity-Beta-Interface-PR15664-6a66e15.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19757/HighFidelity-Beta-PR15664-6a66e15.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19757/HighFidelity-Quest-Beta-PR15664-6a66e15.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19757/HighFidelity-Beta-PR15664-6a66e15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19757/HighFidelity-Beta-Interface-PR15664-6a66e15.exe

**Comment by howard-stearns** [comment]
Might also consider Simon's Socket::readPendingDatagrams() change from https://github.com/highfidelity/hifi/pull/15585/files

**Pull request merged**
