### PR TITLE
Beta Release 68 - branched at Developer Release 8318

### PR DESCRIPTION
**Pull request by conklin94122**
New Features

We have a new in-world landing spot for new High Fidelity users, a cool space cafe with color guns, sparkle launchers, and more. You can check it out at TheSpot. Our friendly Greeter staff will now be hanging out in Help. A new tutorial directs people to TheSpot, and cleans up a few problems users reported at some of the tutorial stations.
We are updating the Steam installer to be client-only. More on that here.
An alpha version of our mobile app, High Fidelity - Live VR Experiences, is now live. You can join domains like TheSpot, Mexico, SVVR domains from mobile to attend face to face events and interact with real people in the virtual world.
Faster Texture Transfer - we made some improvements to the way the texture was getting transferred to GPU. In testing, this helped improve loading time on domains significantly.
A developer function to enable sideloading .app.json Apps from local disk
The Cloneable property in the Create menu now works with no rez-rights! As a domain owner, when you set an item to Cloneable your guests will be able to grab clones of these items even without rez permissions in your domain. We hope this will enable you to create fun and interactive content while keeping your domain safe. We also made some technical changes: Cloneable items no longer require userdata to be set, and we fixed an issue with clone limits.
Reorganized Menu Layouts 
Help is now its own menu! It includes links to forums, documentation, controls, about, support contact and other things you might hope to find in a “Help” menu.
“Advanced Settings” is removed, and the items that were associated with that have been integrated into their respective menus. Most items were simply removed from this condition and are either on by default or have been curated.
Advanced movement for hand controllers" has been moved into a “VR Movement” category under Settings > Controls.
Flying and jumping functionality has been removed from the Advanced movement setting, and placed into its own setting. This is in the same place as advanced movement, under Settings > Controls.
Control settings from Settings > General moved into Settings > Controls

Avatar Scripts: Avatar authors now have the ability to add interface scripts directly to their avatar FBX files. When someone then wears that avatar, any associated avatar scripts will run automatically. When they change avatars, the avatar script will be automatically terminated. We believe that this feature will open huge possibilities for innovation and self-expression for High Fidelity content creators. 

Bug Fixes

Fixed a crash in the Snapshot save folder
Fixed various gifting bugs
Fixed wallet, Marketplace item upgrade, and certified content set bugs
Fixed several minor bugs in the Create menu
Crash fixes in QML and deadlocks
Fixed a bug that caused avatars to be invisible sometimes
Fixed login via Steam on High Fidelity website
.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10053/HighFidelity-Beta-PR13223-52a05680e770d5210198f42c50c4a8bce6e35188.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10053/HighFidelity-Beta-PR13223-52a05680e770d5210198f42c50c4a8bce6e35188.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10053/HighFidelity-Beta-Interface-PR13223-52a05680e770d5210198f42c50c4a8bce6e35188.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10053/HighFidelity-Beta-PR13223-52a05680e770d5210198f42c50c4a8bce6e35188.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10053/HighFidelity-Beta-Interface-PR13223-52a05680e770d5210198f42c50c4a8bce6e35188.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10093/HighFidelity-Beta-PR13223-c89c70fbaabdb1bc18ed264ffcfbb28e54500cc0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10093/HighFidelity-Beta-PR13223-c89c70fbaabdb1bc18ed264ffcfbb28e54500cc0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10093/HighFidelity-Beta-Interface-PR13223-c89c70fbaabdb1bc18ed264ffcfbb28e54500cc0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10097/HighFidelity-Beta-PR13223-cacc102fd0c8cab3d849899419d192d704ab1ab0.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10093/HighFidelity-Beta-PR13223-c89c70fbaabdb1bc18ed264ffcfbb28e54500cc0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10093/HighFidelity-Beta-Interface-PR13223-c89c70fbaabdb1bc18ed264ffcfbb28e54500cc0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10097/HighFidelity-Beta-PR13223-cacc102fd0c8cab3d849899419d192d704ab1ab0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10097/HighFidelity-Beta-Interface-PR13223-cacc102fd0c8cab3d849899419d192d704ab1ab0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10128/HighFidelity-Beta-PR13223-5dadfde63797b2a0ca4c5c53b0e2dbcff53eb4df.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10128/HighFidelity-Beta-PR13223-5dadfde63797b2a0ca4c5c53b0e2dbcff53eb4df.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10128/HighFidelity-Beta-Interface-PR13223-5dadfde63797b2a0ca4c5c53b0e2dbcff53eb4df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10128/HighFidelity-Beta-PR13223-5dadfde63797b2a0ca4c5c53b0e2dbcff53eb4df.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10128/HighFidelity-Beta-Interface-PR13223-5dadfde63797b2a0ca4c5c53b0e2dbcff53eb4df.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10236/HighFidelity-Beta-PR13223-6d505dd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10236/HighFidelity-Beta-PR13223-6d505dd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10236/HighFidelity-Beta-Interface-PR13223-6d505dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10236/HighFidelity-Beta-PR13223-6d505dd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10236/HighFidelity-Beta-Interface-PR13223-6d505dd.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10253/HighFidelity-Beta-PR13223-f5a0f3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10253/HighFidelity-Beta-PR13223-f5a0f3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10253/HighFidelity-Beta-Interface-PR13223-f5a0f3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10253/HighFidelity-Beta-PR13223-f5a0f3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10253/HighFidelity-Beta-Interface-PR13223-f5a0f3d.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10281/HighFidelity-Beta-PR13223-e51d2aa.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10281/HighFidelity-Beta-PR13223-e51d2aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10281/HighFidelity-Beta-Interface-PR13223-e51d2aa.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10304/HighFidelity-Beta-PR13223-e51d2aa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10304/HighFidelity-Beta-PR13223-e51d2aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10304/HighFidelity-Beta-Interface-PR13223-e51d2aa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10304/HighFidelity-Beta-PR13223-e51d2aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10304/HighFidelity-Beta-Interface-PR13223-e51d2aa.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10310/HighFidelity-Beta-PR13223-d564055.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10310/HighFidelity-Beta-PR13223-d564055.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10310/HighFidelity-Beta-Interface-PR13223-d564055.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10310/HighFidelity-Beta-PR13223-d564055.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10310/HighFidelity-Beta-Interface-PR13223-d564055.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10314/HighFidelity-Beta-PR13223-7c5da84.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10314/HighFidelity-Beta-PR13223-7c5da84.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10314/HighFidelity-Beta-Interface-PR13223-7c5da84.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10314/HighFidelity-Beta-PR13223-7c5da84.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10314/HighFidelity-Beta-Interface-PR13223-7c5da84.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10324/HighFidelity-Beta-PR13223-378e84b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10324/HighFidelity-Beta-PR13223-378e84b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10324/HighFidelity-Beta-Interface-PR13223-378e84b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10324/HighFidelity-Beta-PR13223-378e84b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10324/HighFidelity-Beta-Interface-PR13223-378e84b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10330/HighFidelity-Beta-PR13223-0d99953.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10330/HighFidelity-Beta-PR13223-0d99953.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10330/HighFidelity-Beta-Interface-PR13223-0d99953.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10333/HighFidelity-Beta-PR13223-29f2ab0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10333/HighFidelity-Beta-PR13223-29f2ab0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10333/HighFidelity-Beta-Interface-PR13223-29f2ab0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10333/HighFidelity-Beta-PR13223-29f2ab0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10333/HighFidelity-Beta-Interface-PR13223-29f2ab0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10366/HighFidelity-Beta-PR13223-dbd8e0f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10366/HighFidelity-Beta-PR13223-dbd8e0f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10366/HighFidelity-Beta-Interface-PR13223-dbd8e0f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10366/HighFidelity-Beta-PR13223-dbd8e0f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10366/HighFidelity-Beta-Interface-PR13223-dbd8e0f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10413/HighFidelity-Beta-PR13223-8d173e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10413/HighFidelity-Beta-PR13223-8d173e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10413/HighFidelity-Beta-Interface-PR13223-8d173e0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10432/HighFidelity-Beta-PR13223-954a86e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10432/HighFidelity-Beta-PR13223-954a86e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10432/HighFidelity-Beta-Interface-PR13223-954a86e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10432/HighFidelity-Beta-PR13223-954a86e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10432/HighFidelity-Beta-Interface-PR13223-954a86e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10460/HighFidelity-Beta-PR13223-0cadb95.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10460/HighFidelity-Beta-Interface-PR13223-0cadb95.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10460/HighFidelity-Beta-PR13223-0cadb95.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10460/HighFidelity-Beta-Interface-PR13223-0cadb95.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10530/HighFidelity-Beta-PR13223-ae79511.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10530/HighFidelity-Beta-PR13223-ae79511.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10530/HighFidelity-Beta-Interface-PR13223-ae79511.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10530/HighFidelity-Beta-PR13223-ae79511.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10530/HighFidelity-Beta-Interface-PR13223-ae79511.exe

**Pull request merged**
