### PR TITLE
MS19903: don't trigger virtual keyboard scroll on non input focus.

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/19903/virtual-keyboard-hook-script-causes-page-scroll-on-page-load (Test plan is available in ticket)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15265/HighFidelity-Beta-PR14430-84e8e21.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15265/HighFidelity-Beta-PR14430-84e8e21.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15265/HighFidelity-Beta-Interface-PR14430-84e8e21.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15265/HighFidelity-Beta-PR14430-84e8e21.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15265/HighFidelity-Beta-Interface-PR14430-84e8e21.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Test plan passed, and the properties tab stayed at the top on new entities.

**Pull request merged**
