### PR TITLE
4684 Add collapse button on the virtual keyboard 

### PR DESCRIPTION
**Pull request by ElderOrb**
*** Test plan ***:

Switch to VR
Open 'go to location', select input field so that virtual keyboard appear.
Ensure virtual keyboard has new 'collapse' button like on the picture below:

image

Ensure clicking on 'collapse' button collapses keyboard in the same way as clicking outside the keyboard.
Ensure re-selecting input field after collapsing keyboard still raises keyboard.

Update: 

Based on discussion with @mukulHF this PR also introduces the following changes: 

- The keyboard collapse button is moved to the lower right, replacing the keys there
- The button next to m is a hyphen instead of a underscore, it turns to a underscore when the user clicks on shift
- The input text at the top occupies the full width and is center aligned, when you start typing the text moves in both directions the left and the right

Please also ensure the changes above works according to the requirements. 

Note: It turned out that some dialogs are implemented in a bit different way than others, so please check as much different screens with virtual keyboard as possible and let me know what screen causes issues (hopefully no one, but still..)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4842/HighFidelity-Beta-PR11794-5fcde1186afb2dd3cb48dbb1b9e05c8f7771ce12.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4842/HighFidelity-Beta-PR11794-5fcde1186afb2dd3cb48dbb1b9e05c8f7771ce12.exe

**Comment by Nex-Pro** [comment]
@ElderOrb I'll hit this when it is ready. Same test as before?

**Comment by ElderOrb** [comment]
yes, please

**Comment by ElderOrb** [comment]
@Nex-Pro I beg pardon for possible confusion, previous PR was closed as it was based on the old codebase. This one is based on he latest master so shouldn't have any weird issues with lasers (I hope)

**Comment by Nex-Pro** [comment]
@ElderOrb Yep, we worked that out. I need a QA ready label to continue.

**Comment by Nex-Pro** [comment]
Will test shortly

**Comment by Nex-Pro** [comment]
### FAIL

Although the collapse button works fine across every place I could invoke it. I noticed that the underscore has been removed from the keyboard. It should be located right of the 'm' but has been replaced with the 'minus' symbol. As I do not think that this was intended I am failing this.

There are a number of other issues with the keyboard that are not related to this pr. In each case I compared to latest dev build.

**Comment by Nex-Pro** [comment]
**Issues noted with keyboard not due to this PR.**

Using menu->avatar-attachments [NEW ATTACHMENT] Attempting to enter url the keyboard is dismissed after each letter is clicked.

When trying to input values in the entity properties pane the keyboard does not persist.

Using **marketplace** search the keyboard persists after the return key is hit. The search takes place and the user has to dismiss the keyboard. This seems incorrect as the keyboard at this point has served its purpose.

**Settings.**

In each case below if the user does not first scroll the pane so that the input field is above where the keyboard will appear the input field will be hidden by the keyboard.

**Menu->settings->general** snapshot url

**Menu->settings->general** scripts folder

**Menu->settings->general** UI Horizontal angular size 

**Menu->settings->avatar** all of the avatar tuning fields can be hidden by the keyboard.

**Edit->open and run script from URL**  return key does not work. User has to use the OK button.

**settings->lod**  return key does not work.

**Comment by ElderOrb** [comment]
>>  I noticed that the underscore has been removed from the keyboard. It should be located right of the 'm' but has been replaced with the 'minus' symbol. As I do not think that this was intended I am failing this.

Actually it was intended. I beg pardon for not mentioning it in the test plan. This is requirement change from @mukulHF : 

1. The keyboard collapse button is moved to the lower right, replacing the keys there
2. The button next to m is a hyphen instead of a underscore, it turns to a underscore when the user clicks on shift
3. The input text at the top occupies the full width and is center aligned, when you start typing the text moves in both directions the left and the right

**Comment by Nex-Pro** [comment]
The idea of shift to swap hyphen and underscore works on a physical keyboard because both symbols are shown on the key.  In the same way that + and = are. That is not the case with this design.

**Comment by changxc** [comment]
This did not make it into RC 59, let's aim at finishing testing, review and merge by next week so it can go into RC 60

I am ok with the design that minus or underscore is controlled by 'shift' key. If designer @mukulHF has no further objections. 

i think other issues should be addressed in other PRs

--------------------------------------------------------------------------
# This one - I think it there was a PR that fixed it before, not sure why it comes back. please address this @ElderOrb 
Using marketplace search the keyboard persists after the return key is hit. The search takes place and the user has to dismiss the keyboard. This seems incorrect as the keyboard at this point has served its purpose.
--------------------------------------------------------------------------
# The below setting ones - I know mukul has new UI design that is not yet approved or developed. I would say let us not address this, until we got new design @ElderOrb 

Settings.

In each case below if the user does not first scroll the pane so that the input field is above where the keyboard will appear the input field will be hidden by the keyboard.

Menu->settings->general snapshot url

Menu->settings->general scripts folder

Menu->settings->general UI Horizontal angular size

Menu->settings->avatar all of the avatar tuning fields can be hidden by the keyboard. 

--------------------------------------------------------------------------
# The below setting ones - I am not sure I understand. are these caught in HMD mode? @Nex-Pro 

Edit->open and run script from URL return key does not work. User has to use the OK button.

settings->lod return key does not work.

**Comment by Nex-Pro** [comment]
@changxc  ***Edit->open and run script from URL return key does not work. User has to use the OK button.***  I am referring to the return key on the HMD keyboard.

**Comment by Nex-Pro** [comment]
enter key, carriage return key whatever you want to call it. @changxc

**Comment by mukulHF** [comment]
@Nex-Pro I agree that functionality needs to be there. I have it on my list and will create another ticket for it. This PR is not trying to solve that problem. I think this PR accomplished what it set out to do.

**Comment by Nex-Pro** [comment]
@mukulHF Ok. But let's keep the UX good. We should not add frustration.

**Comment by changxc** [comment]
Thank you everybody! let us get this one in and address other issues in different PR

[High priority, should go into RC 60] FB ticket: https://highfidelity.fogbugz.com/f/cases/9264/dismiss-keyboard-after-user-finished-typing-in-marketplace-search-bar-and-hit-search-or-return-key

Using marketplace search the keyboard persists after the return key is hit. The search takes place and the user has to dismiss the keyboard. This seems incorrect as the keyboard at this point has served its purpose.

---------------------------
DO NOT address the below issues until @mukulHF's new UI layout is approved and new ticket created. Chances are we are re-organizing where setting, avatar attachment menu, and keyboard changes should be done against the new page layout. 

I captured these issues in FB and labeled as 'do not address now': https://highfidelity.fogbugz.com/f/cases/9266
---------------------------

Using menu->avatar-attachments [NEW ATTACHMENT] Attempting to enter url the keyboard is dismissed after each letter is clicked.

When trying to input values in the entity properties pane the keyboard does not persist.

Settings.

In each case below if the user does not first scroll the pane so that the input field is above where the keyboard will appear the input field will be hidden by the keyboard.

Menu->settings->general snapshot url

Menu->settings->general scripts folder

Menu->settings->general UI Horizontal angular size

Menu->settings->avatar all of the avatar tuning fields can be hidden by the keyboard.

Edit->open and run script from URL return key does not work. User has to use the OK button.

settings->lod return key does not work.

**Comment by Nex-Pro** [comment]
### Pass
Issues being addressed elsewhere.

**Pull request merged**
