### PR TITLE
DNM: extend pal's notion of session when muting or ignoring

### PR DESCRIPTION
**Pull request by davidkelly**
DNM right now, as not done.  Need the PR for convenient testing on multiple machines, etc...

Ideally, if you mute or ignore someone, you want that to apply even if they leave and come back.  So, this should address that -- as long as you are in a particular domain, people you muted or ignored can leave and come back and they should still be ignored/muted.  An anonymous user (regardless of display name) will be tracked on the server-side by the machine fingerprint, as long as they are not logged in, any client on that machine will be muted/ignored.  A logged in user is tracked by username, and if they pop out and back in (still logged in), same will apply.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f16661d982616ba5a2e9d2b9f45567a0aeedd909 available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-f16661d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-f16661d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72a6bd36c31942abd671430a202a297f860fbb1b available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-72a6bd3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-72a6bd3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94869d68e560f307d816d8de8e4d0f15be0541bc available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-94869d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-94869d6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf8b2e7b6a4f7b1228c51aa804f915519d489dcb available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-bf8b2e7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-bf8b2e7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e2bb0eab5712b0cd90ef46ec2b7523161b620d69 available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-e2bb0ea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-e2bb0ea.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22bd3359997d869c82b8d37af014c8ca290f0da2 available at: https://gist.github.com/4746a36f2d4836719376d51185618939<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-22bd335.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9396-22bd335.dmg

**Comment by davidkelly** [comment]
closing this - we've decided we are comfortable (for now) with the session being defined the current way.  Always can revisit, but given that one could be tracked via muting them, ignore and mute would have to be different (mute only for length of mutee's session, where ignore persists for ignorer's session or longer), and this seems confusing, we are holding off on it.

**Pull request closed without merging**
