### PR TITLE
better handling of the teleport target overlays to prevent flashing

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- basic smoke
- use teleport several times
- the teleport destinations should no longer flash black every time they hide/show

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef3c9ba78a25e01a950fc2b95ee3bbc217840a1b available at: https://gist.github.com/dc6bc0bce344d61923ce6afb47761c9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8811-ef3c9ba.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8811-ef3c9ba.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4bcd8008deeee13f5e95c13ef3c5dbf2c6f6ddd6 available at: https://gist.github.com/dc6bc0bce344d61923ce6afb47761c9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8811-4bcd800.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8811-4bcd800.dmg

**Comment by nbq** [comment]
testing this one now

**Comment by nbq** [comment]
I have ran the smoke test and it passed, also I used the teleporters in Welcome and used the Go To option to visit places and I do not see a black flash. I did notice when I landed somewhere the place was the "black sunset" until the content loaded but nothing flashed black.

**Comment by thoys** [comment]
Uh , I see the confusion here, but with teleport they meant the HMD teleport.js script, @ZappoMan  @cozza13  please add special tags for HMD only or be more clear

**Pull request merged**
