### PR TITLE
Model overlay fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Make cloning a model overlay clone its animation properties.
- Add missing property "get" for "loadPriority" property.
- Some JSDoc updates.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Run the testCloneModel.js script.
- Two blue avatar overlays should be created.
- The animation setings reported for each in the program log should be identical.

2) Run the testLoadPriority.js script.
- The default loadPriority property value of 0 should successfully be retrieved.
- The loadPriority valued should be successfully changed to 10.

[21829 Tests.zip](https://github.com/highfidelity/hifi/files/1886057/21829.Tests.zip)

https://highfidelity.manuscript.com/f/cases/10191

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8616/app_12831_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8616/HighFidelity-Beta-PR12831-8093e3e5ae7c283b20acf3df6960ca6cd5f2a136.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8617/app_12831_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8617/HighFidelity-Beta-PR12831-f3a745b6cb52ed819f32cc591cea25777c30c577.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
Animation sections read the same. Default load value successfully changed from 0 to 10

**Pull request merged**
