### PR TITLE
[DO NOT MERGE] Slightly modified version of https://github.com/highfidelity/hifi/pull/11705 for testing purposes only

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4834/HighFidelity-Beta-PR11792-35a052d84240b683df745fc43f7985bd4c7e7611.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4834/HighFidelity-Beta-PR11792-35a052d84240b683df745fc43f7985bd4c7e7611.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4835/HighFidelity-Beta-PR11792-b45b0fa2824ec863fd0dcb2a83cd9186b36578b4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4835/HighFidelity-Beta-PR11792-b45b0fa2824ec863fd0dcb2a83cd9186b36578b4.exe

**Comment by Nex-Pro** [comment]
@ElderOrb Do you want me to repeat the 11705 test plan with this build ?

**Comment by ElderOrb** [comment]
yes, please.

**Comment by Nex-Pro** [comment]
Will do

**Comment by Nex-Pro** [comment]
@ElderOrb I'll need this set to QA ready please. Then I can proceed.

**Pull request closed without merging**
