### PR TITLE
fix for re-send timeout in SendQueue

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58f9830a94e1456b08d98cd37e661b1531b8a9bf available at: https://gist.github.com/144b25474c7ba725fb10<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6041.dmg

**Comment by birarda** [comment]
This built successfully - OS X failed to publish artifacts.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58f9830a94e1456b08d98cd37e661b1531b8a9bf available at: https://gist.github.com/144b25474c7ba725fb10<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6041.dmg

**Pull request merged**
