### PR TITLE
Report offscreen texture memory usage in stats

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bd398ae5eff52e2452a13a48ef23a8934c751e7 available at: https://gist.github.com/d05bb5c63b78b56cc07073f8c916e946<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8881-1bd398a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8881-1bd398a.dmg

**Comment by davidkelly** [comment]
I see the QML Textures in stats, so this looks like QA Approved to me.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9ac110072b4902ab25400e093b756655b61cc7e available at: https://gist.github.com/d05bb5c63b78b56cc07073f8c916e946<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8881-e9ac110.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8881-e9ac110.dmg

**Comment by ZappoMan** [comment]
it does display qml texture memory - PASS

**Pull request merged**
