### PR TITLE
remove jpg error popup behavior

### PR DESCRIPTION
**Pull request by howard-stearns**
Fix https://highfidelity.fogbugz.com/f/cases/1628/web-entities-should-not-display-error-popup-for-jpg-urls

### CODE REVIEW

**Comment by howard-stearns** [comment]
Test plan:
- Drag .png, .jpeg, and .jpg files onto interface in localhost. All should offer to upload the asset to sandbox. (Old behavior was to give error message only for .jpg that it wasn't an authentic snapshot, or to take you to that place if it was.)
- Visit a .jpg url in a ctrl-b HUD browser, and in a Web entity. The image should be displayed. (Old behavior was as above if the url ended in .jpg, without the e.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: b949c83a0514beb44478e91fdeebe85ccf05b4ec available at: https://gist.github.com/8fb767db8fd29767cb60cc84a1b1916c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8591-b949c83.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8591-b949c83.dmg

**Comment by Nex-Pro** [comment]
**PR #8591**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**QA PASS** but please read notes.


Drag .png, .jpeg, and .jpg files onto interface in localhost. All should offer to upload the asset to sandbox. (Old behavior was to give error message only for .jpg that it wasn't an authentic snapshot, or to take you to that place if it was.): **SUCCESS**


Visit a .jpg url in a ctrl-b HUD browser, and in a Web entity. The image should be displayed. (Old behavior was as above if the url ended in .jpg, without the e.): **SUCCESS**


#### NOTES:

**Testing this threw up a few issues.**

In a ctrl+b web browser right cliking on an image brings up the context menu which is never subsequently dismissed. Copy image URL and copy image work  but don't dismiss. Save image does not work. Back and Forward work but the context menu does not dismiss. This persists over fresh browser instances and restarts. Ie. right clicking reproduces the issue.

The browser context menu is different in this build to 5353. 5353 simply has back/forward/reload and the menu dismisses correctly.

Also there is a content issue with the highfidelity.com page in the ctrl+b browser which is not apparent in chrome. The hosting/creating/exploring animated icon does not work correctly with partial flips and the only word displaying correctly is Hosting.

**Comment by howard-stearns** [comment]
These browser issues are outside of this PR (so pass here). Ticketed as:
https://highfidelity.fogbugz.com/f/cases/1664/browser-context-menu-hangs
https://highfidelity.fogbugz.com/f/cases/1663/Highfidelity-Home-Page-animation-doesn-t-work-in-Interface-browsers

**Pull request merged**
