### PR TITLE
fix to default avatar model

### PR DESCRIPTION
**Pull request by ZappoMan**
If an avatar was using the default avatar (empty string), the avatar mixer wasn't considering the identity packet as changed, and was never sending out the packet so people wouldn't see the avatar.

### CODE REVIEW

**Comment by ZappoMan** [comment]
Fixes this bug - https://app.asana.com/0/26320649018758/103291791148307

Test Notes:
- **Make sure you are running the console from this build -- this is an avatar mixer fix.**
- Run interface, clear your avatar URL, **restart interface**
- Go to your local domain, have another user enter the domain and observe your avatar: they should be able to see you.
- Repeat steps with production server and you won't see the default avatar.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 691ee87c737fbbd9a56fe7db32052157ea313edd available at: https://gist.github.com/4d713710c2d35f85a197<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7426.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7426.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Current Interface to this PR stack (running on Linux remote) :+1: (Second AV can't see default AV)
PR Interface to this PR stack :+1: (Second AV can see default)

QA Passes

**Comment by hifi-gustavo** [comment]
Build console output for commit: 361aa3e6830a577c015e6116af1330d078769eee available at: https://gist.github.com/4d713710c2d35f85a197<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7426.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7426.dmg

**Comment by howard-stearns** [comment]
I guess if it solves the problem I'm all for it. But it would be interesting to know what's going wrong. There used to be logic that depended on the empty string meaning "default avatar", and (at one time), the various initializations and "did it really change" tests took this into account. I'm slightly nervous that we might be shifting a bug to someplace else. (But only slightly.)

**Comment by ZappoMan** [comment]
To answer @howard-stearns question... the thing that caused this bug to appear is that when we removed the "face URL" logic a couple days ago... that code was inadvertently tickling the "something has changed" logic, because the face was "" in the client, but was initialized as "invalid.com" in the mixer.... so it looked like a change to the mixer on the first packet.

**Pull request merged**
