### PR TITLE
fix import of particle systems

### PR DESCRIPTION
**Pull request by ZappoMan**
Fix importing and exporting of particle systems.

Test plan:
- follow the repro steps of these bugs, and verify that this build fixes these bugs: 
https://highfidelity.manuscript.com/f/cases/11377/Particle-properties-incorrect-and-incomplete-on-export
https://highfidelity.manuscript.com/f/cases/11413/Importing-a-particle-entity-from-a-JSON-does-not-import-all-particle-properties

- Verify that particle properties work as expected:
.... *more info needed*

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8249/app_12703_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8249/HighFidelity-Beta-PR12703-7c259ba1b659e9c2cd3cb874966a1c85232e75f5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8249/HighFidelity-Beta-PR12703-7c259ba1b659e9c2cd3cb874966a1c85232e75f5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8363/HighFidelity-Beta-PR12703-abfc6ac5d8a7951b6c722315a40e92dd4e1adaa6.dmg

**Comment by ZappoMan** [comment]
This fix is included in @SamGondelman's uber PR

**Pull request closed without merging**
