### PR TITLE
Fix UBSAN warning

### PR DESCRIPTION
**Pull request by kencooke**
UBSAN warning (left-shift on negative integer) is triggered in the audio peak limiter when processing absurdly large/inf/NaN samples. Fixed by clamping the floating-point exponent.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15501/HighFidelity-Beta-PR14493-11252a8.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15501/HighFidelity-Beta-PR14493-11252a8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15501/HighFidelity-Beta-Interface-PR14493-11252a8.exe

**Comment by kencooke** [comment]
### Test Plan

Using Interface from this PR, verify that audio works as expected.
This PR has no change for normally-occurring audio values.

**Pull request merged**
