### PR TITLE
Fix for Bow and Arrow Not Re-enabling Hands At Unequip

### PR DESCRIPTION
**Pull request by imgntn**
Previously, equipping the bow and arrow would result in one of your hands becoming permanently disabled.  Now, you can use the bow and arrow and have your hands function normally.

To test:
1. Make a bow with /toybox/createBow.js
2. Equip it
3. Unequip
4. Try to grab other things

With the master handControllerGrab.js, one of your hands will quit working.  You will not see a grab beam for this hand.

With this script, your hands will continue to function as normal.  
https://rawgit.com/imgntn/hifi/bowandarrowfixjan29/examples/controllers/handControllerGrab.js

https://app.asana.com/0/46580934041217/82053018733923

### CODE REVIEW

**Comment by cozza13** [comment]
I will test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8feba20ce7c1af3af532ca218d3031743f2d9305 available at: https://gist.github.com/916e572145255091f811<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6979.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6979.dmg

**Comment by nbq** [comment]
I tested this also, used the left hand to hold the bow and the right hand to shoot and then I put down the bow. I am able to use the left hand to control other stuff now but not the right so the "shooter hand" is still not freed up after the bow is put down.

**Comment by imgntn** [comment]
closing this PR, some changes coming to hand grab from seth

**Pull request closed without merging**
