### PR TITLE
Tablet homebutton dimension and position now scales with tablet

### PR DESCRIPTION
**Pull request by druiz17**
Home button scale and position is now based on both hmdTablet scale and desktopTabletScale

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan

-In general settings set the tablet hmd scale smaller than the desktop scale. 
-While in desktop mode bring up the tablet and you should be able to click on the home button.
-perform the same test in hmd mode

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0b203edf9824fbe8133057bf796dd887eba060a available at: https://gist.github.com/4f3bc0d2e459cf399a0dee95dc2b9943<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9786-b0b203e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9786-b0b203e.dmg

**Comment by claudioshg** [comment]
testing

**Comment by druiz17** [comment]
Fogzbug link 
https://highfidelity.fogbugz.com/f/cases/3166/Clicking-Users-on-the-tablet-will-sometimes-close-the-tablet

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9786-b0b203e.exe

-In general settings set the tablet hmd scale smaller than the desktop scale: SUCCESS
-While in desktop mode bring up the tablet and you should be able to click on the home button: SUCCESS
-perform the same test in hmd mode: SUCCESS

**PASS**

Notes
- I scaled the HMD tablet at 30%, 50%, and 80%
- Respectively, I scaled the Desktop tablet at 55%, 75%, and 100%

**Pull request merged**
