### PR TITLE
Fix EntitySelectioTool and improve far rotate

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan. (HMD mode)
1.
- open tablet and go into create mode.
- select an entity and check it you can rotate and move the object by using the overlay item
2.
- Create a dynamic object
- check that you can far rotate the object
To far rotate an object, first far grab an object, then with the second hand far grab the same object. you can use the second hand to rotate the object.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3689/HighFidelity-Beta-PR11475-58a00a89d788321115acf197f3c60460be189080.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3689/HighFidelity-Beta-PR11475-58a00a89d788321115acf197f3c60460be189080.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
open tablet and go into create mode. | Pass
select an entity and check that you can rotate and move the object by using the overlay icons | Pass
Create a dynamic object | Pass
check that you can far rotate the object | Pass

All appears to be working okay for me. In HMD, far grabbing with my left hand and rotating with my right works as expected. Far grabbing with my right hand and rotating with my left also works too. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
