### PR TITLE
IPD Secondary Task List: edit.js arrow orientation: Yaw, Pitch, Roll tools

### PR DESCRIPTION
**Pull request by Delanir**
The Rotation Tools of the edit mode (Yaw, Pitch, Roll) now work based on the avatar referential.

* Rotation around a certain axis aligned with the avatar
* The position and rotation of the gizmos overlay icons take into account the orientation of the avatar
* The position of the center of rotation of the tool is independent of the world axis.

### On Desktop Mode:
1. Go to your Sandbox or other domain where you have modification privileges.
2. Open the "Create" mode.
3. Spawn a Cube.
4. Note the position of the rotate gizmos. Try to use the rotation gizmos. 

5. Go to wikiplanet/newyork (you might need permission).
6. Repeat the same steps.
### On VR Mode:
1. Go to your Sandbox or other domain where you have modification privileges.
2. Open the "Create" mode.
3. Spawn a Cube.
4. Note the position of the rotate gizmos. Try to use the rotation gizmos. 

5. Go to wikiplanet/newyork .
6. Repeat the same steps.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5247/HighFidelity-Beta-PR11897-07c061053351e111fd104742bdd53d097d8ad6f7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5247/HighFidelity-Beta-PR11897-07c061053351e111fd104742bdd53d097d8ad6f7.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

On Desktop Mode:
Go to your Sandbox or other domain where you have modification privileges. **Check, my sandbox used**
Open the "Create" mode. **Check**
Spawn a Cube. **Check**
Note the position of the rotate gizmos. Try to use the rotation gizmos. **Check**
image

Go to wikiplanet/newyork (you might need permission). **Check, Wikiplanet**
Repeat the same steps. **Check**

On VR Mode:
Go to your Sandbox or other domain where you have modification privileges. **Check**
Open the "Create" mode. **Check**
Spawn a Cube. **Check**
Note the position of the rotate gizmos. Try to use the rotation gizmos. **Check**
Go to wikiplanet/newyork . **Check**
Repeat the same steps.  **Check, used Wikiplanet, I must note though it was impossible to rotate the cube with the earth behind my laser as I try to use the gizmo's to rotate - but against the sky this worked fine.**

**Pass**

**Pull request merged**
