### PR TITLE
fix Agent teardown of recording and ScriptEngine(s)

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Repeat the steps from https://highfidelity.manuscript.com/f/cases/17875/Bots-from-previous-server-script-load-in-place-of-different-bot-script. Ensure that the bots always show up in the expected location in the domain.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12425/HighFidelity-Beta-PR13885-a76b50c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12425/HighFidelity-Beta-PR13885-a76b50c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12425/HighFidelity-Beta-Interface-PR13885-a76b50c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12425/HighFidelity-Beta-PR13885-a76b50c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12425/HighFidelity-Beta-Interface-PR13885-a76b50c.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Script 1 bots: https://raw.githubusercontent.com/highfidelity/hifi/master/script-archive/acScripts/BetterClientSimulationBotFromRecording.js

Script 2 bots: https://gist.githubusercontent.com/birarda/2e84e5206c5b96748a565a85f244ed88/raw/142e826f5311034d5d4428e7e91b636fa18846e4/test-avatars.js

Loaded 1 set of 5 script 1 bots, removed them, then added the other set of 5 script 2 bots. New set all loaded properly.

Removed set of script 2 bots and added a group of script 1 bots. Only 3 of the 5 bots loaded and there was a woody avatar stuck in T-Pose at the /0,0,0 coordinates. Repeated removing the bots and re-added them, this time only 4/5 of the bots appeared and still a woody avatar appeared. Fails PR.

Added interface and server logs.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2332600/hifi-log.txt)
[Server_logs.zip](https://github.com/highfidelity/hifi/files/2332601/Server_logs.zip)
hifi-snap-by--on-2018-08-29_08-34-33

**Comment by birarda** [comment]
If you test this with the sandbox, I believe the "keep a spare" code is going to get in your way since it starts with a single script agent and builds up from there. When you change the running script, wait in the new location and you will slowly see the recorded instances appear.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12808/HighFidelity-Beta-PR13885-a76b50c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12808/HighFidelity-Beta-PR13885-a76b50c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12808/HighFidelity-Beta-Interface-PR13885-a76b50c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12808/HighFidelity-Beta-PR13885-a76b50c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12808/HighFidelity-Beta-Interface-PR13885-a76b50c.exe

**Comment by antoninahifi** [comment]
Currently testing

**Comment by antoninahifi** [comment]
PASS @conklin94122

**Pull request merged**
