### PR TITLE
Call Interface "High Fidelity" on macOS

### PR DESCRIPTION
**Pull request by MattHardcastle**
https://highfidelity.atlassian.net/browse/DEV-490

Screen Shot 2019-08-30 at 8 14 15 AM

### CODE REVIEW

**Comment by MattHardcastle** [comment]
@huffman I may be missing something but I believe this change is enough to have macOS call Interface High Fidelity while keeping the bundle name "interface.app".

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21112/HighFidelity-Beta-PR16124-5a5bcbf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21112/HighFidelity-Beta-Interface-PR16124-5a5bcbf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21112/HighFidelity-Beta-PR16124-5a5bcbf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21112/HighFidelity-Beta-Interface-PR16124-5a5bcbf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21112/HighFidelity-Beta-PR16124-5a5bcbf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21112/HighFidelity-Quest-Beta-PR16124-5a5bcbf.apk)

**Comment by MattHardcastle** [comment]
This does not change the name in the Dock. That seems to depend on the bundle name only. I tried `CFBundleDisplayName` but it doesn't impact it. The only thing that appears to change the dock name is the bundle name.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21115/HighFidelity-Beta-PR16124-f91ec8f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21115/HighFidelity-Beta-Interface-PR16124-f91ec8f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21115/HighFidelity-Beta-PR16124-f91ec8f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21115/HighFidelity-Quest-Beta-PR16124-f91ec8f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21115/HighFidelity-Beta-PR16124-f91ec8f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21115/HighFidelity-Beta-Interface-PR16124-f91ec8f.exe

**Pull request merged**
