### PR TITLE
QML Work

### PR DESCRIPTION
**Pull request by jherico**
* Removes a significant amount of dead code from `WindowScriptingInterface`
* Migrates `WindowScriptingInterface` UI elements to QML
* Support the use of naked file dialog filters `*.json` in addition to `JSON Files (*.json)`
* Support save operations with the current QML based file dialog
* Fixes some odd text rendering artifacts when mixing native and Qt text rendering
* Add a drive letter shortcut to the file dialog (on systems that support multiple drives)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 60d97c45affa260571218f9e732f6b4df9b7151a available at: https://gist.github.com/69c86054343eb9a46646<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.dmg

**Comment by OmegaHeron** [comment]
No "marching" text seen, all aligned cleanly.  Good. (Being intermittent will withhold final verdict on it really being gone)

All dialogs load/display proper.  Good

Running scripts window is placing downward and right of location it begins in production build -- not a bad thing, just saying.

Issue 1.  Pick a model - tell it to export - Fail. 

hifi-snap-by-omegaheron-on-2016-02-04_13-02-52

**Comment by nbq** [comment]
I also tested this just to see and I get "Unable to write to location file:///path/entity.json"

**Comment by OmegaHeron** [comment]
Using production build was able to export then import via this PR so, for me, only broken is entity export.  It could be an issue with needing to load modified edit.js and all pitfalls seen with getting that to work.  Or it could just be an extra \ in path.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64597f9d9f86c71dfe2d6e3a9b915a04d60d6032 available at: https://gist.github.com/69c86054343eb9a46646<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.dmg

**Comment by ZappoMan** [comment]
@OmegaHeron @nbq - Austin has fixed the bug in export.. can you retest?

**Comment by jherico** [comment]
@OmegaHeron the edit.js changes are actually unrelated to the file dialog stuff.  However there was a bug in the pre-save checks if you were writing to a new file as opposed to writing over an existing one.  THe updated version should work properly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc0e038535485d921ebcf051b72744487e9f2464 available at: https://gist.github.com/69c86054343eb9a46646<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7025.dmg

**Comment by OmegaHeron** [comment]
The reason for needing to run matching edit.js is its icon does not show on screen using current default.  Testing rest now, will advise shortly.

**Comment by OmegaHeron** [comment]
@ZappoMan Tested with latest build - works for exporting and re-import of on Windows 7.  All else works as expected.

**Comment by OmegaHeron** [comment]
One more general comment -- there needs to be a sane default path for things like this - first PR tested defaulted to c:\program files\High Fidelity\ for place to save.  This 2nd PR defaulted to C:\windows\system32 

An unaware end user could run into heaps of annoyance accepting those defaults, if not do something really system breaking if running with admin rights.  Without admin rights windows isn't going to let you write to program files hierarchy etc.... but - it's a problem causer.  Make a script - go to save it - program file\high fidelity -- try to save (maybe) bad things happen.

**Pull request merged**
