### PR TITLE
Show toolbar only if Show Overlays selected in menu.

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
This PR fixes a bug where the toolbar would be shown, even though the menu option was not checked.  This would happen under the following scenario:
1.  Clear Show Overlays checkbox in the menu.
2.  Shutdown and then restart interface
     The toolbar would be seen, even though the option was unchecked.

Fixes https://highfidelity.manuscript.com/f/cases/15467/Toolbar-ignores-saved-state

# Testing
## UI
1.  Start interface
2.  Uncheck Show Overlays
     Verify toolbar not shown
3.  Close and then restart interface
    Verify toolbar not shown
    Verify Show Overlays option is unchecked
4.  Check Show Overlays
     Verify tool bar shown
5.  Close and then restart interface
    Verify toolbar shown
    Verify option is checked
6.  Clear Developer->UI->Desktop Tablet Becomes Toolbar
     Verify toolbar not shown
     Verify  Show Overlays option is checked
7.  Close and then restart interface
     Verify toolbar not shown
     Verify  Show Overlays option is checked
8.  Set Developer->UI->Desktop Tablet Becomes Toolbar
     Verify toolbar shown
9.  Close and then restart interface
     Verify toolbar shown

## Scripting
1.  Start interface
2.  Uncheck Show Overlays
     Verify toolbar not shown
3.  In the Scripting console (CTRL+ALT+J) - enter `Menu.setIsOptionChecked("Show Overlays", true);`
     Verify toolbar shown
    Verify Show Overlays option is checked
4.  Enter `Menu.setIsOptionChecked("Show Overlays", false);`
     Verify toolbar not shown
     Verify Show Overlays option is not checked
5.  Set Developer->UI->Desktop Tablet Becomes Toolbar
     Verify toolbar shown

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10260/HighFidelity-Beta-PR13268-5e3de7e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10260/HighFidelity-Beta-PR13268-5e3de7e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10260/HighFidelity-Beta-Interface-PR13268-5e3de7e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10260/HighFidelity-Beta-PR13268-5e3de7e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10260/HighFidelity-Beta-Interface-PR13268-5e3de7e.exe

**Comment by danteruiz** [comment]
closing this PR in favior of https://github.com/highfidelity/hifi/pull/13273

**Pull request closed without merging**
