### PR TITLE
remove confusing sandbox content update/backup system

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

1. Run the Sandbox from this PR. Confirm that it displays the window to show download progress for content set. Confirm that the content set downloads and is present when you connect to the Sandbox.
2. Confirm the the tray menu for the Sandbox does not contain an item "Restore Backup Instructions".
3. Quit the Sandbox.
4. Restart the Sandbox and confirm you are not prompted for any content set download or update and that the content that was downloaded in step 1 is still present.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10192/HighFidelity-Beta-PR13252-5dc17fa39ebc434e85d1b5ddb0aba8dd789d1c8f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10192/HighFidelity-Beta-PR13252-5dc17fa39ebc434e85d1b5ddb0aba8dd789d1c8f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10192/HighFidelity-Beta-Interface-PR13252-5dc17fa39ebc434e85d1b5ddb0aba8dd789d1c8f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10192/HighFidelity-Beta-PR13252-5dc17fa39ebc434e85d1b5ddb0aba8dd789d1c8f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10192/HighFidelity-Beta-Interface-PR13252-5dc17fa39ebc434e85d1b5ddb0aba8dd789d1c8f.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin Local sandbox domain does not appear to create a server or is having issues connecting to the network. Cannot access domain server using "localhost:40100" in web browser, nor can the user connect to the Sandbox in the Interface. Defect does not occur on Master. Tested on OSX and Windows platforms.
Screenshot and logs included
[PR13252.zip](https://github.com/highfidelity/hifi/files/2060251/PR13252.zip)

**Comment by birarda** [comment]
@qligmaloney amended the commit with a fix, thanks

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10289/HighFidelity-Beta-PR13252-de6db6f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10289/HighFidelity-Beta-PR13252-de6db6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10289/HighFidelity-Beta-Interface-PR13252-de6db6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10289/HighFidelity-Beta-PR13252-de6db6f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10289/HighFidelity-Beta-Interface-PR13252-de6db6f.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Content set downloads and is visible when connecting to sandbox, restore instructions do not display, user is not prompted upon restarting.

**Pull request merged**
