### PR TITLE
quiet warnings in Linux build

### PR DESCRIPTION
**Pull request by sethalves**
- quiet some compiler warnings

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional changes

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e73330e8e7df8e51b99f0c5fce23b246458a071 available at: https://gist.github.com/afa5793093c70136b36028184b901e24<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8848-2e73330.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8848-2e73330.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9362526098ee34c8c43a065337b780d3c2e9ca1 available at: https://gist.github.com/afa5793093c70136b36028184b901e24<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8848-b936252.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8848-b936252.dmg

**Comment by OmegaHeron** [comment]
Smoke test and pass.  Compiled Ubuntu 16.04.1

**Pull request merged**
