### PR TITLE
Add Photo Sphere Example

### PR DESCRIPTION
**Pull request by imgntn**
This PR shows how to load a photo sphere model and set its texture.

To test:
1. Run this script  https://rawgit.com/imgntn/hifi/photosphere/examples/data_visualization/photo_sphere.js

### CODE REVIEW

**Comment by imgntn** [comment]
https://app.asana.com/0/46580934041217/100200841818881

**Comment by imgntn** [comment]
https://app.asana.com/0/46580934041217/100200841818881

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0109133c0af3f95370177192ba1c25fa87f7ff5 available at: https://gist.github.com/b060e9a4fc7a54f9c79e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cecebc9ae499ea6f3136620e6d45c683b7c0792e available at: https://gist.github.com/b060e9a4fc7a54f9c79e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0109133c0af3f95370177192ba1c25fa87f7ff5 available at: https://gist.github.com/b060e9a4fc7a54f9c79e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.dmg

**Comment by judasshuffle** [comment]
It works but seems kinda specular at least where I tried it, needs to be more mat. But that said its going to be a really useful script.

**Comment by imgntn** [comment]
its washed out even without the light, i'll try to see if i can tweak the fbx settings -- open to recommendations.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96bc17cd5ee84dda5f2a9c7280b2c8befcada4cd available at: https://gist.github.com/b060e9a4fc7a54f9c79e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7335.dmg

**Pull request merged**
