### PR TITLE
Takeout deadlock exit for testing purposes

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8565/HighFidelity-Beta-PR12811-24a5f2f67bf63aa45bc9ff43ab97a545081fe47f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8565/HighFidelity-Beta-PR12811-24a5f2f67bf63aa45bc9ff43ab97a545081fe47f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8596/app_12811_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8596/HighFidelity-Beta-PR12811-071ec38be35997ba84d03b5ed5f76148177df747.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8596/HighFidelity-Beta-PR12811-071ec38be35997ba84d03b5ed5f76148177df747.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8643/app_12811_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8643/HighFidelity-Beta-PR12811-2351b25882e4d5837ae4811690f74e8200259e62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8643/HighFidelity-Beta-PR12811-2351b25882e4d5837ae4811690f74e8200259e62.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8647/app_12811_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8647/HighFidelity-Beta-PR12811-baac500e20fc1f5be69f8e1bb274f2377e39d85f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8670/app_12811_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8670/HighFidelity-Beta-PR12811-8d0ec319af33221eaee07a34dfddee8d4cead8e0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8670/HighFidelity-Beta-PR12811-8d0ec319af33221eaee07a34dfddee8d4cead8e0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8842/app_12811_PR_fc5526cdadd00e5f1c2a39ac0b295eff8c8e3c8c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8842/HighFidelity-Beta-PR12811-fc5526cdadd00e5f1c2a39ac0b295eff8c8e3c8c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8869/app_12811_PR_1c1ca83cfdd11036e8f5824c8e92f22029432fbb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8869/HighFidelity-Beta-PR12811-1c1ca83cfdd11036e8f5824c8e92f22029432fbb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8869/HighFidelity-Beta-Interface-PR12811-1c1ca83cfdd11036e8f5824c8e92f22029432fbb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8869/HighFidelity-Beta-PR12811-1c1ca83cfdd11036e8f5824c8e92f22029432fbb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8869/HighFidelity-Beta-Interface-PR12811-1c1ca83cfdd11036e8f5824c8e92f22029432fbb.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8882/app_12811_PR_ddd22b3d022f46b8f7dfda10da88fce06dfae40b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8882/HighFidelity-Beta-PR12811-ddd22b3d022f46b8f7dfda10da88fce06dfae40b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8882/HighFidelity-Beta-Interface-PR12811-ddd22b3d022f46b8f7dfda10da88fce06dfae40b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8882/HighFidelity-Beta-PR12811-ddd22b3d022f46b8f7dfda10da88fce06dfae40b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8882/HighFidelity-Beta-Interface-PR12811-ddd22b3d022f46b8f7dfda10da88fce06dfae40b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8893/app_12811_PR_5416e4832f840b816f727487b2bc0cc9cc0cd7d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8893/HighFidelity-Beta-PR12811-5416e4832f840b816f727487b2bc0cc9cc0cd7d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8893/HighFidelity-Beta-Interface-PR12811-5416e4832f840b816f727487b2bc0cc9cc0cd7d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8893/HighFidelity-Beta-PR12811-5416e4832f840b816f727487b2bc0cc9cc0cd7d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8893/HighFidelity-Beta-Interface-PR12811-5416e4832f840b816f727487b2bc0cc9cc0cd7d4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8914/app_12811_PR_b563783bebb62bea43309b84c52831ff30c8e0d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8914/HighFidelity-Beta-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8914/HighFidelity-Beta-Interface-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.dmg

**Comment by SimonWalton-HiFi** [comment]
Please build this for Windows.

**Comment by SimonWalton-HiFi** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8922/app_12811_PR_b563783bebb62bea43309b84c52831ff30c8e0d4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8922/HighFidelity-Beta-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8922/HighFidelity-Beta-Interface-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8922/HighFidelity-Beta-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8922/HighFidelity-Beta-Interface-PR12811-b563783bebb62bea43309b84c52831ff30c8e0d4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9001/app_12811_PR_0e8a64013c4d8810f483f155da83006c9aec21c7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9001/HighFidelity-Beta-PR12811-0e8a64013c4d8810f483f155da83006c9aec21c7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9001/HighFidelity-Beta-Interface-PR12811-0e8a64013c4d8810f483f155da83006c9aec21c7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9012/app_12811_PR_81e7087e280db2c4eb1a6a99d6a049e457f411f4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9012/HighFidelity-Beta-PR12811-81e7087e280db2c4eb1a6a99d6a049e457f411f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9012/HighFidelity-Beta-Interface-PR12811-81e7087e280db2c4eb1a6a99d6a049e457f411f4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9063/app_12811_PR_11b1cb82aa5ff520e2cc9b0ccdec3509dd4c05ab.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9063/HighFidelity-Beta-PR12811-11b1cb82aa5ff520e2cc9b0ccdec3509dd4c05ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9063/HighFidelity-Beta-Interface-PR12811-11b1cb82aa5ff520e2cc9b0ccdec3509dd4c05ab.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9063/HighFidelity-Beta-PR12811-11b1cb82aa5ff520e2cc9b0ccdec3509dd4c05ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9063/HighFidelity-Beta-Interface-PR12811-11b1cb82aa5ff520e2cc9b0ccdec3509dd4c05ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9264/HighFidelity-Beta-PR12811-06011046b67953fad7609473e1e1eac5dbc273a7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9264/HighFidelity-Beta-Interface-PR12811-06011046b67953fad7609473e1e1eac5dbc273a7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9783/HighFidelity-Beta-PR12811-aafae6b58cda83bae21c5b9dd4a91d788f07970b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9783/HighFidelity-Beta-PR12811-aafae6b58cda83bae21c5b9dd4a91d788f07970b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9783/HighFidelity-Beta-Interface-PR12811-aafae6b58cda83bae21c5b9dd4a91d788f07970b.exe

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9788/HighFidelity-Beta-PR12811-81e6ee487cef1469b70522d485810489fb4ce269.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9788/HighFidelity-Beta-PR12811-81e6ee487cef1469b70522d485810489fb4ce269.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9788/HighFidelity-Beta-Interface-PR12811-81e6ee487cef1469b70522d485810489fb4ce269.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9788/HighFidelity-Beta-PR12811-81e6ee487cef1469b70522d485810489fb4ce269.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9803/HighFidelity-Beta-PR12811-1fd03c482dad2da3bc8e2a6476ef4e9a73e0ea6c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9803/HighFidelity-Beta-PR12811-1fd03c482dad2da3bc8e2a6476ef4e9a73e0ea6c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9803/HighFidelity-Beta-Interface-PR12811-1fd03c482dad2da3bc8e2a6476ef4e9a73e0ea6c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10335/HighFidelity-Beta-PR12811-0123c9a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10335/HighFidelity-Beta-PR12811-0123c9a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10335/HighFidelity-Beta-Interface-PR12811-0123c9a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10335/HighFidelity-Beta-PR12811-0123c9a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10335/HighFidelity-Beta-Interface-PR12811-0123c9a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10423/HighFidelity-Beta-PR12811-1f5b9e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10423/HighFidelity-Beta-PR12811-1f5b9e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10423/HighFidelity-Beta-Interface-PR12811-1f5b9e1.dmg

**Pull request closed without merging**
