### PR TITLE
fix bug that caused localAngularVelocity to get zeroed out

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that caused localAngularVelocity to get zeroed out

https://github.com/highfidelity/hifi/pull/13781
https://highfidelity.manuscript.com/f/cases/17131
https://highfidelity.manuscript.com/f/cases/17380/QuickFix-localAngularVelocity-in-Edit-js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13027/HighFidelity-Beta-PR14008-f86075b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13027/HighFidelity-Beta-PR14008-f86075b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13027/HighFidelity-Beta-Interface-PR14008-f86075b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13027/HighFidelity-Beta-PR14008-f86075b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13027/HighFidelity-Beta-Interface-PR14008-f86075b.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13237/HighFidelity-Beta-PR14008-f86075b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13237/HighFidelity-Beta-Interface-PR14008-f86075b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13237/HighFidelity-Beta-PR14008-f86075b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13237/HighFidelity-Beta-Interface-PR14008-f86075b.dmg

**Comment by qlimguicheteau** [comment]
Now Testing

**Pull request merged**
