### PR TITLE
Bubble button blink fix

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.manuscript.com/f/cases/13034/Bubble-icon-blinks-three-times-when-clicked-on

Test plan
- Press Bubble button (if its active, press it to deactivate)
- make sure button does not blinking when activating

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8058/app_12653_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8058/HighFidelity-Beta-PR12653-3e00243c379285e06014152a754829f5bb86c6b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8058/HighFidelity-Beta-PR12653-3e00243c379285e06014152a754829f5bb86c6b3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Bubble button no longer blinks when selected. However there is now a delay when activating the bubble button. The original goal of the PR is successful. Currently when the user activates the bubble, it takes about 3 - 4 seconds for the icon to show it is activated. A user may see that the bubble icon is not activating and begin spamming the button, frustrating the user.
Logs and video of new behavior attached.
[Files.zip](https://github.com/highfidelity/hifi/files/1868872/Files.zip)

**Pull request merged**
