### PR TITLE
Menu organization updates

### PR DESCRIPTION
**Pull request by alexiamandeville**
Organized top menu and QML submenus. Added TODOs inline for an engineer.

This PR addresses all or part of the following tickets;
https://highfidelity.manuscript.com/f/cases/11624/get-rid-of-unused-or-useless-preference-settings
https://highfidelity.manuscript.com/f/cases/8137/General-Settings-menu
https://highfidelity.manuscript.com/f/cases/7795/Menu-Edit-Entity-List-Nothing-Happens

Additional changes need to be applied (menu actions, submenu QMLs) for this change to be complete: https://highfidelity.atlassian.net/wiki/spaces/DES/pages/200966265/Developer+Notes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7981/app_12625_PR.apk

**Comment by alexiamandeville** [comment]
Reverted commits from other PR that pollute this request.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7982/app_12625_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7982/HighFidelity-Beta-PR12625-c5b8a2d06ecd933279334ae47858c1a0ef6756c4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7982/HighFidelity-Beta-PR12625-c5b8a2d06ecd933279334ae47858c1a0ef6756c4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8353/HighFidelity-Beta-PR12625-31ab39834461afb448bd3a21c55c94bd4cb6a87f.dmg

**Comment by vladest** [comment]
work on the task continued at https://github.com/highfidelity/hifi/pull/12895

**Comment by sethalves** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/12895

**Pull request closed without merging**
