### PR TITLE
Added dead zones to Hydra and Oculus Touch joysticks

### PR DESCRIPTION
**Pull request by SamGondelman**
Added dead zones to Hydras and Oculus Touch controllers

### CODE REVIEW

**Comment by SamGondelman** [comment]
Testing:
- using touches, if you don't touch the joysticks (within dead zone), you shouldn't drift
- otherwise, movement with touch controllers should work as before

**Comment by SamGondelman** [comment]
I'm going to add this to the hydras, too.  Tomorrow.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ce7623f413c351c5c455f9e4b8b9b44f4c6e128 available at: https://gist.github.com/8171a86b27fd6a8a41bdacce5c5d7be4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8355-1ce7623.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8355-1ce7623.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 458e43fadc782322dd389c1c753ee7c8a75dc821 available at: https://gist.github.com/8171a86b27fd6a8a41bdacce5c5d7be4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8355-458e43f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8355-458e43f.dmg

**Comment by PhilipRosedale** [comment]
cozza13 tested this

**Pull request merged**
