### PR TITLE
Audio-mixer optimizations

### PR DESCRIPTION
**Pull request by kencooke**
Add HRTF reset() for use by audio-mixer throttling.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

No QA needed (not currently used). If it compiles, PASS.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13386/HighFidelity-Beta-PR14095-9dc0aa5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13386/HighFidelity-Beta-PR14095-9dc0aa5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13386/HighFidelity-Beta-Interface-PR14095-9dc0aa5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13386/HighFidelity-Beta-PR14095-9dc0aa5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13386/HighFidelity-Beta-Interface-PR14095-9dc0aa5.exe

**Pull request merged**
