### PR TITLE
DEV-2202: Apply same random factors to both eyes blink

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-2202

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21694/HighFidelity-Beta-PR16291-f7a5895.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21694/HighFidelity-Beta-Interface-PR16291-f7a5895.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21694/HighFidelity-Beta-PR16291-f7a5895.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21694/HighFidelity-Quest-Beta-PR16291-f7a5895.apk)

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21707/HighFidelity-Beta-PR16291-f7a5895.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21707/HighFidelity-Quest-Beta-PR16291-f7a5895.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21707/HighFidelity-Beta-PR16291-f7a5895.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21707/HighFidelity-Beta-Interface-PR16291-f7a5895.dmg

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21723/HighFidelity-Beta-PR16291-f7a5895.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21723/HighFidelity-Quest-Beta-PR16291-f7a5895.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21723/HighFidelity-Beta-PR16291-f7a5895.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21723/HighFidelity-Beta-Interface-PR16291-f7a5895.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21723/HighFidelity-Beta-PR16291-f7a5895.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21723/HighFidelity-Beta-Interface-PR16291-f7a5895.exe

**Pull request merged**
