### PR TITLE
repairs to user heartbeats

### PR DESCRIPTION
**Pull request by birarda**
- support anonymous user heartbeats
- send a user location even if not connected to a known place/domain
- use the session ID returned by the metaverse API
- remove wallet balance tracking code

### CODE REVIEW

**Comment by birarda** [comment]
To test:

(1) Confirm that jumping to users running this PR build still works.
(2) Run the interface client while logged in, ping me so I can confirm that DB records are correct.
(3) Run the interface client while logged out, ping me so I can confirm that DB records are correct.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f6221840eb94bd58bae4249cd0819870e8b8773 available at: https://gist.github.com/15f1e084d19de3b3b4387229bae918c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7832.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7832.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f6221840eb94bd58bae4249cd0819870e8b8773 available at: https://gist.github.com/15f1e084d19de3b3b4387229bae918c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7832.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7832.dmg

**Pull request merged**
