### PR TITLE
SSE2 optimization of new resampler. 

### PR DESCRIPTION
**Pull request by kencooke**
3.5x faster for all modes.  Dither is always enabled.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e29d8382dc4a026b60fccd81c050776c34d17bc available at: https://gist.github.com/a6a3553126b581abc049<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e29d8382dc4a026b60fccd81c050776c34d17bc available at: https://gist.github.com/a6a3553126b581abc049<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3555e90cf60360273f3fac159c05009b9528c223 available at: https://gist.github.com/a6a3553126b581abc049<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5969.dmg

**Comment by AndrewMeadows** [comment]
I've verified that the new code is being built on linux.  What's the best way to test it?  Just login and use audio or do I need to play a soundfile with a particular format/sample-rate that requires resampling?

**Comment by kencooke** [comment]
@AndrewMeadows Thanks!  A quick test is just enabling the mic and using Echo Server Audio.  Looking at the QT 5.4.1 source, it never attempts to open the audio device at 24khz for any of our platforms.  So the 48khz -> 24khz -> 48khz will always be done by our resampler.

You can also test with dice.js which does resamples by arbitrary fractions during PlaySound.

I validated the correctness on Windows with a unit test framework, so my main concern is that the SSE2 intrinsics are compiling correctly on other platforms.

**Comment by AndrewMeadows** [comment]
I was wondering why you weren't adding any unit tests...

**Pull request merged**
