### PR TITLE
Fix avatar highlighting

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/18749/Highlight-on-avatars-broken

Test plan:
- Run this from the console:
```
var style = {        
    outlineUnoccludedColor: { red: 0, green: 255, blue: 250 },
    outlineOccludedColor: { red: 0, green: 255, blue: 250 },
    fillUnoccludedColor: { red: 255, green: 0, blue: 0 },
    fillOccludedColor: { red: 255, green: 0, blue: 0 },

    outlineUnoccludedAlpha: 1.0,
    outlineOccludedAlpha: 1.0,
    fillUnoccludedAlpha: 1.0,
    fillOccludedAlpha: 1.0,
                
    outlineWidth: 5,
    isOutlineSmooth: true
}
Selection.enableListHighlight("test", style)
Selection.addToSelectedItemsList("test", "avatar", "{00000000-0000-0000-0000-000000000001}")
```
- Your avatar should be highlighted correctly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13250/HighFidelity-Beta-PR14072-ad73cb3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13250/HighFidelity-Beta-PR14072-ad73cb3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13250/HighFidelity-Beta-Interface-PR14072-ad73cb3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13250/HighFidelity-Beta-PR14072-ad73cb3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13250/HighFidelity-Beta-Interface-PR14072-ad73cb3.exe

**Comment by QliCknox** [comment]
Currently Testing

**Pull request merged**
