### PR TITLE
Parallelize audio packet decoding in mixer

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 41a4ec4200a17aa3f986f03f51347750d885d223 available at: https://gist.github.com/033cdc12045382820a094bfc73d78b84<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9673-41a4ec4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9673-41a4ec4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09cc4bf48d7c82229b76c71ef3769a2479159b20 available at: https://gist.github.com/033cdc12045382820a094bfc73d78b84<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9673-09cc4bf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9673-09cc4bf.dmg

**Comment by zzmp** [comment]
This changes the way that some audio packets are processed, so behaviors surrounding those packets must be tested.

Audio packets fall into two general categories: node-isolated packets, and general packets. The former only affects data on a node and it's own data (`AudioMixerClientData*`); the latter affects shared data across nodes' data, and may take locks to do so. Thus, in parallelizing audio packet processing, only the former was parallelized (by queuing it on the node's data and processing across a threadpool).

The behaviors that must be tested:
- Audio (client, no server echo)
- Audio (client, server echo)
- Audio (silent frames, these will be sent by client automatically)
- Audio (injector)
*All audio behavior should work if one of them do*

- Audio stats (use debug menu to access it)
- Codecs
- Mute
- Node ignore (blocking other users)
- Radius ignore (privacy bubble)
- Avatar gain (PAL)

### Load testing

This decreases time for the mixer to process events, using agents running [this script](http://hifi-content.s3.amazonaws.com/DomainContent/Event%20/Scripts/BetterClientSimulationBotFromRecording.js) with the `hifiCodec`:

| build | branch | avatars | us_per_events | us_per_packets |
| :- | :- | -: | -: | -: |
| 442e8d6 | master | 60 | 3300 | - |
| 09cc4bf | PR9673 | 60 | 550 | 490 |
| 09cc4bf | PR9673 | 120 | 870 | 730 |

### QA Plan

Boot up a server with multiple users, using codecs (this occurs by default).
Ensure that you can still access the stats (from the debug menu).
Ensure that audio works normally, including injectors.
Ensure that blocking users, privacy bubbles, and PAL continue to work.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

Starting at this PR's merge (6055) with sandbox and interface on same win 10 machine with specs above; audio from wind chimes in default sandbox scene is corrupted - it skips in/out.  Dropping to 6054 or earlier it's fine.  Audio with this PR from voice server echo-back is fine, it's just the injector audio.

**Comment by OmegaHeron** [comment]
With no agent connected (other than scripted agent that comes with sandbox) I see unending repeats of this sort in AC audio-mixer log;

[02/16 13:13:54] [SUPPRESS] [] [7896] [audio-mixer] 2476 repeated log entries matching "unreasonable sequence number: \d+ \(possible duplicate\)" - Last entry: "unreasonable sequence number: 2484 (possible duplicate)"
[02/16 13:13:54] [DEBUG] [hifi.networking] [7896] [audio-mixer] unreasonable sequence number: 2485 (possible duplicate)
[02/16 13:13:59] [SUPPRESS] [] [7896] [audio-mixer] 2928 repeated log entries matching "unreasonable sequence number: \d+ \(possible duplicate\)" - Last entry: "unreasonable sequence number: 1806 (possible duplicate)"
[02/16 13:13:59] [DEBUG] [hifi.networking] [7896] [audio-mixer] unreasonable sequence number: 2985 (possible duplicate)
[02/16 13:14:01] [DEBUG] [hifi.audio] [7896] [audio-mixer] AudioRingBuffer::writeData has overflown the buffer. Overwriting old data.
[02/16 13:14:01] [DEBUG] [default] [7896] [audio-mixer] Just overflowed on stream from QUuid("{518214bf-277c-4f3c-846c-d15787be3a37}") at 192.168.0.6:62510
[02/16 13:14:01] [DEBUG] [default] [7896] [audio-mixer] This stream is for injected audio
[02/16 13:14:04] [SUPPRESS] [] [7896] [audio-mixer] 339 repeated log entries matching "AudioRingBuffer::writeData has overflown the buffer. Overwriting old data." - Last entry: "AudioRingBuffer::writeData has overflown the buffer. Overwriting old data."
[02/16 13:14:04] [SUPPRESS] [] [7896] [audio-mixer] 2697 repeated log entries matching "unreasonable sequence number: \d+ \(possible duplicate\)" - Last entry: "unreasonable sequence number: 3484 (possible duplicate)"
[02/16 13:14:04] [DEBUG] [hifi.networking] [7896] [audio-mixer] unreasonable sequence number: 3485 (possible duplicate)
[02/16 13:14:06] [DEBUG] [hifi.audio] [7896] [audio-mixer] AudioRingBuffer::writeData has overflown the buffer. Overwriting old data.
[02/16 13:14:06] [DEBUG] [default] [7896] [audio-mixer] Just overflowed on stream from QUuid("{518214bf-277c-4f3c-846c-d15787be3a37}") at 192.168.0.6:62510
[02/16 13:14:06] [DEBUG] [default] [7896] [audio-mixer] This stream is for injected audio
[02/16 13:14:09] [SUPPRESS] [] [7896] [audio-mixer] 380 repeated log entries matching "AudioRingBuffer::writeData has overflown the buffer. Overwriting old data." - Last entry: "AudioRingBuffer::writeData has overflown the buffer. Overwriting old data."
[02/16 13:14:09] [SUPPRESS] [] [7896] [audio-mixer] 2900 repeated log entries matching "unreasonable sequence number: \d+ \(possible duplicate\)" - Last entry: "unreasonable sequence number: 3984 (possible duplicate)"
[02/16 13:14:09] [DEBUG] [hifi.networking] [7896] [audio-mixer] unreasonable sequence number: 3985 (possible duplicate)

**Pull request merged**
