### PR TITLE
Introduce task abort feature for early exit of task branch

### PR DESCRIPTION
**Pull request by samcake**
Introducing a way to abort a task from one of its job, using it to skip highlight tasks if nothing to highlight

In the JobConfig base class we are adding a TaskFlow object which can be used to issue commands from within a job::run to control the flow of the calling task (of the job).

The first command we expose is "abortTask"
It allows a Job to tell the task to abort the rest of the job remaining that it owns.

We use this new feature to remove any Highlight effect processing early on if there is nothing to highlight. This shaves a few hundreds of nano seconds that where spend on that before all teh time.

## TEST PLAN ##
End result should be similar to master 
the render thread / engine time should be equal or lower in this PR than in master (With stats, the top of the 4th column)
- run the test plan described  here
https://github.com/highfidelity/hifi_tests/blob/master/tests/engine/render/effect/highlight/coverage/test.md

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7230/app_12412_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7230/HighFidelity-Beta-PR12412-0228392ac9d366c386b868492a10de4325325d8b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7236/app_12412_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7236/HighFidelity-Beta-PR12412-c70b655fbc5a170e180e9d99f800fb39d73c6af2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7236/HighFidelity-Beta-PR12412-c70b655fbc5a170e180e9d99f800fb39d73c6af2.dmg

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
