### PR TITLE
Restrict Resource reinsertion

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

General smoke screen.

**Comment by Atlante45** [comment]
Do you need that for your upcoming Resource PR?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b1a78bac0cfb2f3ae6d63f86b9a3d7844e740bd available at: https://gist.github.com/e41af750894625497aaf<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7441.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7441.dmg

**Comment by thoys** [comment]
## QA Report
:+1: :heavy_check_mark:  Runs fine, no anomalies in the log.

**Pull request merged**
