### PR TITLE
fix log flood in debug mode from Buffer::Iterator (c)end access

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
This is @samcake's work.

**Comment by samcake** [comment]
I approve this message

**Comment by zzmp** [comment]
QA
- Ensure that complex scenes render the same
- Smoke test (I think that's the right word...just a general test)

This only changes logging messages in DEBUG mode, so there should be no apparent change from this PR build.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 813fefd59901ff07b0e010c98111357a71efaba8 available at: https://gist.github.com/1ba247b468b4d1309f5df87d5c5fc7f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8472-813fefd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8472-813fefd.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Complex scenes render the same and non-complex. No issues.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |59 |60 |37
**Present Rate**: |60 |60 |60
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |4035 |1967 |2028
**GPU Buffer Count**: |854 |506 |398
**CPU Memory Usage**: |72019968 |34623488 |31727616
**GPU Memory Usage**: |32804864 |16056320 |14512128
**CPU Texture Count**: |365 |216 |167
**GPU Texture Count**: |1067 |1007 |1013
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |264019708 |204921368 |172585496
**GPU Texture Memory Usage**: |1142065885 |580086823 |426000408
**GPU Virtual Memory Usage**: |1267201373|705222311|551135896
**Triangle Count**: |538677 |377804 |275539
**Triangle Rate**: |33667312 |23612750 |17221187
**API Drawcall Count**: |236 |200 |149
**Drawcall Count**: |295 |197 |152
**Drawcall Rate**: |18437 |12312 |9500
**State Changes Texture Count**:|248 |193 |185
**Pipeline Count**: |40 |41 |47
**Item Opaques**: |271 |351 |169
**Item Translucents**: |34 |50 |65
**Item Lights**: |21 |77 |34
**Timing Opaques**: |729 |940 |687
**Timing Translucents**: |31 |46 |379
**Timing Lighting**: |110 |114 |294
**Render Frame**: |1557 |1972 |2220

**Pull request merged**
