### PR TITLE
Changed Step Back Threshold to Stop Unnatural Backward Lean

### PR DESCRIPTION
**Pull request by amantley**
This pr changed the step back threshold and leaning base edge in AvatarConstants.h to stop unnatural leaning back.

This PR address the bug 16942 in Manuscript

https://highfidelity.manuscript.com/f/cases/16942/HMD-Chair-Leaning-makes-Avatar-Bend-Unnaturally

### Test Plan: 
1) open Interface and enter vr mode. press '3' for third person view
2) when you step back your avatar should step backward
3) when you lean back your avatar should match your lean or take a small step back 
4) sit in a chair. your avatar should be standing.
5) lean back in the chair and your avatar should lean back slightly or take a step back

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11478/HighFidelity-Beta-PR13665-c87f6c3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11478/HighFidelity-Beta-PR13665-c87f6c3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11478/HighFidelity-Beta-Interface-PR13665-c87f6c3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11478/HighFidelity-Beta-PR13665-c87f6c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11478/HighFidelity-Beta-Interface-PR13665-c87f6c3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @qliacoombs @conklin94122 
Leaning does move the Avatar appropriately. Sitting down and leaning back in chari fails as the avatar begins to limbo and then moves to crouching position. Screenshot, Video and Log attached:
sitting
[13665.zip](https://github.com/highfidelity/hifi/files/2219785/13665.zip)

**Comment by amantley** [comment]
@qlimnavarro @qliacoombs @conklin94122
I just watched the video.  Step 4 of the test plan might be confusing.  When you are sitting down, your avatar should be standing.  Then try leaning back.  From the video it looks like you are just sitting and leaning back, which is not currently supported behavior.  For that you need to use the sit script, I think.

**Comment by qlimnavarro** [comment]
@amantley 
While user is sitting and then leaning, the Avatar moves correctly.

**Comment by amantley** [comment]
@glimnavarro
can I remove the QA Failed label?

**Pull request merged**
