### PR TITLE
Controller Confguration Page fixes

### PR DESCRIPTION
**Pull request by danteruiz**
This PR fixes unable to scroll to content that is out of view in OpenVrConfiguration, and also the combo-box selecting the wrong configuration page.

PR - https://highfidelity.manuscript.com/f/cases/14788/Use-Vive-devices-in-desktop-mode-not-avail-when-using-shoulder-puck-selection

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan (vive required)
part 1
- goto settings > controller settings
- click on the configuration tab
- check show all devices, then select HTC Vive from the drop box
- you should be presented with the vive configuration page 

part 2
- still on the vive configuration page
- Select Head: Tracker
- Select Hands: Trackers
- Select Additional Trackers: Shoulders
- The Advanced settings: 'use HTC Vive devices in desktop mode radio button should be out of view.
- scroll that section section up and you should be able to see  'use HTC Vive devices in desktop mode' radio button 

part3
- with pucks test that you are able to select a configuration and calibrate.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10350/HighFidelity-Beta-PR13298-f5e2a68.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10350/HighFidelity-Beta-Interface-PR13298-f5e2a68.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10350/HighFidelity-Beta-PR13298-f5e2a68.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10350/HighFidelity-Beta-Interface-PR13298-f5e2a68.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pause for BVT

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
When scrolling through menu a white line appeared and never disappeared. Was unable to calibrate, White calibrating animation was infinite.
[Files.zip](https://github.com/highfidelity/hifi/files/2082077/Files.zip)

**Comment by danteruiz** [comment]
@qlimnavarro how many vive trackers where you wearing?

**Comment by qlimnavarro** [comment]
@danteruiz 4 trackers, 2 on feet and 2 on hands.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10466/HighFidelity-Beta-PR13298-5d570f0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10466/HighFidelity-Beta-PR13298-5d570f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10466/HighFidelity-Beta-Interface-PR13298-5d570f0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10466/HighFidelity-Beta-PR13298-5d570f0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10466/HighFidelity-Beta-Interface-PR13298-5d570f0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Sensors now calibrate and menus look good.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10577/HighFidelity-Beta-PR13298-eb01b50.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10578/HighFidelity-Beta-PR13298-dc28e8f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10578/HighFidelity-Beta-PR13298-dc28e8f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10578/HighFidelity-Beta-Interface-PR13298-dc28e8f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10578/HighFidelity-Beta-PR13298-dc28e8f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10578/HighFidelity-Beta-Interface-PR13298-dc28e8f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Menu still looks good and calibration is successful.

**Pull request merged**
