### PR TITLE
Fix MS4382: Add a lifetime to handshake particle effects to prevent persistence

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS4382](https://highfidelity.manuscript.com/f/cases/4382/Handshake-sparkles-remain-after-handshake).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15853/HighFidelity-Beta-PR14560-3b9777d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15853/HighFidelity-Beta-PR14560-3b9777d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15853/HighFidelity-Beta-Interface-PR14560-3b9777d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15853/HighFidelity-Beta-PR14560-3b9777d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15853/HighFidelity-Beta-Interface-PR14560-3b9777d.exe

**Comment by qliejahner** [comment]
PASS

Particles now disappear on their own.

**Pull request merged**
