### PR TITLE
RC85: DEV-2413: Restate legacy first person camera mode

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-2413
`Kayla-Camera.js` script stopped working after the latest camera work. It relays on the previous first person camera mode to set the camera rotation.
This PR restate the old first person camera mode and rename the new one.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21994/HighFidelity-Beta-PR16369-e5b2f05.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21994/HighFidelity-Beta-Interface-PR16369-e5b2f05.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21994/HighFidelity-Beta-PR16369-e5b2f05.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21994/HighFidelity-Quest-Beta-PR16369-e5b2f05.apk)

**Comment by shanzzam** [comment]
Holding off merge until we release RC85 and can send this out with a hotfix

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22003/HighFidelity-Beta-PR16369-c9eca33.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22003/HighFidelity-Beta-Interface-PR16369-c9eca33.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22003/HighFidelity-Beta-PR16369-c9eca33.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22003/HighFidelity-Quest-Beta-PR16369-c9eca33.apk)

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22009/HighFidelity-Beta-PR16369-c9eca33.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22009/HighFidelity-Quest-Beta-PR16369-c9eca33.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22009/HighFidelity-Beta-PR16369-c9eca33.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22009/HighFidelity-Beta-Interface-PR16369-c9eca33.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22009/HighFidelity-Beta-PR16369-c9eca33.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22009/HighFidelity-Beta-Interface-PR16369-c9eca33.exe

**Comment by shanzzam** [comment]
Closing this as this RC 86 will be released this week.

**Pull request closed without merging**
