### PR TITLE
Perspective bug

### PR DESCRIPTION
**Pull request by amantley**
This pr fixes the bug 11293 in Manuscript.
https://highfidelity.fogbugz.com/f/cases/11293/When-entering-VR-mode-with-a-short-avatar-perspective-is-incorrect

The fix is to call rigready when we change modes vr/desktop.  This will reset the height of the model to be whatever the current. This resets the scale when you enter vr mode.  

### Test Plan
1.  Open interface and go to the market place and choose the robimo avatar.
2.  open the tablet and select 'exit vr'
3.  go back into vr mode 
4. Expected result: the avatar should have the same perspective that you had last time you were in vr mode.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11936/HighFidelity-Beta-PR13779-297e5b2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11936/HighFidelity-Beta-PR13779-297e5b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11936/HighFidelity-Beta-Interface-PR13779-297e5b2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11936/HighFidelity-Beta-PR13779-297e5b2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11936/HighFidelity-Beta-Interface-PR13779-297e5b2.exe

**Comment by JeffClinton** [comment]
build this please

**Comment by amantley** [comment]
@JeffClinton  Hi just wondering why this needed to be rebuilt?

**Comment by JeffClinton** [comment]
@amantley Per our PR testing instructions, if the build is more than 3-4 days old we should trigger a new one.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12226/HighFidelity-Beta-PR13779-297e5b2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12226/HighFidelity-Beta-Interface-PR13779-297e5b2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12226/HighFidelity-Beta-PR13779-297e5b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12226/HighFidelity-Beta-Interface-PR13779-297e5b2.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
