### PR TITLE
BUGZ-686: fix drawcalls stat broken in pr-15721

### PR DESCRIPTION
**Pull request by sethalves**
- fix drawcalls stat broken in pr-15721

https://highfidelity.atlassian.net/secure/RapidBoard.jspa?rapidView=17&modal=detail&selectedIssue=BUGZ-686

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19976/HighFidelity-Beta-PR15767-431ff0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19976/HighFidelity-Beta-Interface-PR15767-431ff0d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19976/HighFidelity-Beta-PR15767-431ff0d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19976/HighFidelity-Quest-Beta-PR15767-431ff0d.apk)

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19981/HighFidelity-Beta-PR15767-431ff0d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19981/HighFidelity-Quest-Beta-PR15767-431ff0d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19981/HighFidelity-Beta-PR15767-431ff0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19981/HighFidelity-Beta-Interface-PR15767-431ff0d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19981/HighFidelity-Beta-PR15767-431ff0d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19981/HighFidelity-Beta-Interface-PR15767-431ff0d.exe

**Pull request merged**
