### PR TITLE
BUGZ-1441: Update logo on login popup

### PR DESCRIPTION
**Pull request by huffman**
interface_2019-09-12_14-19-13

### CODE REVIEW

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21330/HighFidelity-Beta-PR16185-5370e67.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21330/HighFidelity-Beta-Interface-PR16185-5370e67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21330/HighFidelity-Beta-PR16185-5370e67.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21330/HighFidelity-Beta-Interface-PR16185-5370e67.exe

**Pull request merged**
