### PR TITLE
Reduce EntityItem access in EntityRenderer::needsRenderUpdateFromEntity

### PR DESCRIPTION
**Pull request by SamGondelman**
EntityRenderer::needsRenderUpdateFromEntity was repeatedly calling EntityItem::getVisible to see if it needed to request a render update.  Now, EntityItem notifies EntityRenderer only when _visible changes.

This somewhat breaks the rule that EntityRenderer should not know about its EntityItem...but we're trying to move away from the polling model and this is a first step.

Before:
getvisible3
Now:
getvisible4

Test plan:
- Toggle the visibility on an entity.  It should toggle properly.  Try every entity type.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5832/app_12060_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5832/HighFidelity-Beta-PR12060-5018edcfe00b701fdc5bcef243957a8fdd1150dd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5832/HighFidelity-Beta-PR12060-5018edcfe00b701fdc5bcef243957a8fdd1150dd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5833/app_12060_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5833/HighFidelity-Beta-PR12060-5018edcfe00b701fdc5bcef243957a8fdd1150dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5833/HighFidelity-Beta-PR12060-5018edcfe00b701fdc5bcef243957a8fdd1150dd.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Fail** Web entity didn't come back when setting to visible again.
image

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Fails for all entities EXCEPT Zone. 
box is invisible

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6099/app_12060_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6099/HighFidelity-Beta-PR12060-1395753fc87a40581f0f304e39784d9f1d91c928.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6109/app_12060_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6109/HighFidelity-Beta-PR12060-1395753fc87a40581f0f304e39784d9f1d91c928.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6109/HighFidelity-Beta-PR12060-1395753fc87a40581f0f304e39784d9f1d91c928.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6113/app_12060_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6113/HighFidelity-Beta-PR12060-4f5727e6b0c143a400c6e0be063fd91eb6eb8c4a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6113/HighFidelity-Beta-PR12060-4f5727e6b0c143a400c6e0be063fd91eb6eb8c4a.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
