### PR TITLE
Bulk Avatar Traits related ack data was not reset when avatars were ignored.

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.manuscript.com/f/cases/20584

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16373/HighFidelity-Beta-PR14688-f7df1c6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16373/HighFidelity-Beta-PR14688-f7df1c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16373/HighFidelity-Beta-Interface-PR14688-f7df1c6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16373/HighFidelity-Beta-PR14688-f7df1c6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16373/HighFidelity-Beta-Interface-PR14688-f7df1c6.exe

**Comment by antoninahifi** [comment]
PASS
Tested:
Log two avatars into domain
Open PAL
One ignores/bubble the other, then unignores/bubble
Verify there is no white sphere.

**Pull request merged**
