### PR TITLE
Fix alpha on Line3DOverlays with glow

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- Run [this](https://gist.githubusercontent.com/SamGondelman/760eb062444763ce34b1f51ff349573f/raw/63b06ef7e7e491453be5125794f42776a2009fdd/LineAlphaTest.js).  You should see something like:
linealpha

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3565/HighFidelity-Beta-PR11441-bc477608ee873b78f77ff246605a2b6ddc471841.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3565/HighFidelity-Beta-PR11441-bc477608ee873b78f77ff246605a2b6ddc471841.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Seems like a **Pass** to me.
image

**Pull request merged**
