### PR TITLE
don't call setQmlTabletRoot twice

### PR DESCRIPTION
**Pull request by druiz17**
creating a PR for master  link to original PR - https://github.com/highfidelity/hifi/pull/12113

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6138/app_12122_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6138/HighFidelity-Beta-PR12122-4cf40554c037abfe2252eded52fdde4184f29a19.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6138/HighFidelity-Beta-PR12122-4cf40554c037abfe2252eded52fdde4184f29a19.dmg

**Comment by druiz17** [comment]
Test plan
- follow the test plan in this PR https://github.com/highfidelity/hifi/pull/12113

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

**Comment by AndrewMeadows** [comment]
This work was merged separately into RC62 via #12113 and as such it doesn't really need an RC milestone.

**Pull request merged**
