### PR TITLE
Simplify Etc2Comp cmake

### PR DESCRIPTION
**Pull request by SamGondelman**
Simplify changes from https://github.com/highfidelity/hifi/pull/13394

Test plan:
- no QA necessary, if it builds it passes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10781/HighFidelity-Beta-PR13433-6e646be.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10781/HighFidelity-Beta-PR13433-6e646be.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10781/HighFidelity-Beta-Interface-PR13433-6e646be.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10790/HighFidelity-Beta-PR13433-64fdb8f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10790/HighFidelity-Beta-PR13433-64fdb8f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10790/HighFidelity-Beta-Interface-PR13433-64fdb8f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10790/HighFidelity-Beta-PR13433-64fdb8f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10790/HighFidelity-Beta-Interface-PR13433-64fdb8f.exe

**Comment by qlimnavarro** [comment]
Performed quick check on all platforms. All load and perform as expected. 
Pass @conklin94122

**Pull request merged**
