### PR TITLE
Fix MS16480: Disable active ContextOverlays when disabling ContextOverlayInterface

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS16480](https://highfidelity.manuscript.com/f/cases/16480/Domain-Content-Set-Highlighting-from-Marketplace-Inspection-makes-using-create-mode-difficult).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Right click a content set rezzed from the Marketplace (such that the inspection context overlay appears)
2. Open the CREATE app
3. Verify that the context overlay and its entity's edge highlighting disappears.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11192/HighFidelity-Beta-PR13563-01eb3ed.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11192/HighFidelity-Beta-PR13563-01eb3ed.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11192/HighFidelity-Beta-Interface-PR13563-01eb3ed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11192/HighFidelity-Beta-PR13563-01eb3ed.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11192/HighFidelity-Beta-Interface-PR13563-01eb3ed.exe

**Comment by zfox23** [comment]
Edge highlighting still sometimes (?) being shown while in Edit mode? Investigating

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11230/HighFidelity-Beta-PR13563-d3c0236.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11230/HighFidelity-Beta-PR13563-d3c0236.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11230/HighFidelity-Beta-Interface-PR13563-d3c0236.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11230/HighFidelity-Beta-PR13563-d3c0236.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11230/HighFidelity-Beta-Interface-PR13563-d3c0236.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11233/HighFidelity-Beta-PR13563-2fad55e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11233/HighFidelity-Beta-PR13563-2fad55e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11233/HighFidelity-Beta-Interface-PR13563-2fad55e.exe

**Comment by qligmaloney** [comment]
PASS @conklin94122 marketplace inspection overlay and border disappear when opening Create

**Pull request merged**
