### PR TITLE
fix issue when loading recording file into the input recorder

### PR DESCRIPTION
**Pull request by druiz17**
fix the issue when loading recording file into the input recorder

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Download the file below
- run the inputRecorder.js
- click the button IRecord for the tablet home screen
- click the 'load' button 
- click 'lay recording' button'
- the end result should be the avatar moving forward and backward

- press Alt-b to stop the playback

[Drive-forward-backward.tar.gz](https://github.com/highfidelity/hifi/files/991463/Drive-forward-backward.tar.gz)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cae299192f7662df27e0c1c8ca1ed9139ac2bb8 available at: https://gist.github.com/a410ecaa66ab5f6506eab2206f72780b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10438-0cae299.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10438-0cae299.dmg

**Comment by anshuman64** [comment]
QA Fail. Looks like you have the following switched:
1. Chest <-> Right foot
2. Hips <-> Left foot

**Comment by anshuman64** [comment]
QA Pass. Thanks for fixing. Merging.

P.S. Accidentally commented on this PR instead of your other one.

**Pull request merged**
