### PR TITLE
Elbow pole vectors improvements

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR is an extension of this one:
https://github.com/highfidelity/hifi/pull/13672
It behaves better now when bending and also when moving the hands behind.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11780/HighFidelity-Beta-PR13733-fde77ad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11780/HighFidelity-Beta-PR13733-fde77ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11780/HighFidelity-Beta-Interface-PR13733-fde77ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11780/HighFidelity-Beta-PR13733-fde77ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11780/HighFidelity-Beta-Interface-PR13733-fde77ad.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
- Get in front of a mirror in HMD mode and move your hands around. Make sure your elbows move appropriately.
- When you cross your arms in front of you your elbows should move forward to avoid that your arms penetrating your torso.
- Try the same process with different avatars.

Notes:
-- Sometimes when crossing arms or the hands are behind the body the controllers lose tracking. 
-- It's expected that the arms slightly penetrate the body under certain extreme conditions. What is important is that the elbow stay forward.

**Comment by qlistephens95** [comment]
This needs to be built please.

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11874/HighFidelity-Beta-PR13733-fde77ad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11874/HighFidelity-Beta-PR13733-fde77ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11874/HighFidelity-Beta-Interface-PR13733-fde77ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11874/HighFidelity-Beta-PR13733-fde77ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11874/HighFidelity-Beta-Interface-PR13733-fde77ad.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
