### PR TITLE
fix left-over run button when scripts are reloaded

### PR DESCRIPTION
**Pull request by sethalves**
- fix left-over run button when scripts are reloaded

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- turn on "advanced movement"
- open the running-scripts window
- type "run" into the search field and load run.js; close the running-scripts window
- test the run button
- reopen the running-scripts window, reload all scripts
- make sure that you still only have one "run" button
- test the run button

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6772/app_12305_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6772/HighFidelity-Beta-PR12305-a596e07464ef8746e54dd4c7d249d129f9214231.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6772/HighFidelity-Beta-PR12305-a596e07464ef8746e54dd4c7d249d129f9214231.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing. PASSED.

**Pull request merged**
