### PR TITLE
Increase content archive upload timeout

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- TBD

[ticket](https://highfidelity.manuscript.com/f/cases/19309/Content-archive-uploads-timeout-after-20-sec)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13822/HighFidelity-Beta-PR14189-d79a47e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13822/HighFidelity-Beta-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13822/HighFidelity-Beta-Interface-PR14189-d79a47e.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13997/HighFidelity-Beta-PR14189-d79a47e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13997/HighFidelity-Beta-PR14189-d79a47e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13997/HighFidelity-Beta-Interface-PR14189-d79a47e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13997/HighFidelity-Beta-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13997/HighFidelity-Beta-Interface-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14132/HighFidelity-Beta-PR14189-d79a47e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14132/HighFidelity-Beta-Interface-PR14189-d79a47e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14132/HighFidelity-Beta-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14132/HighFidelity-Beta-Interface-PR14189-d79a47e.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
PASS @conklin94122

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14210/HighFidelity-Beta-PR14189-d79a47e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14210/HighFidelity-Beta-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14210/HighFidelity-Beta-Interface-PR14189-d79a47e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14210/HighFidelity-Beta-PR14189-d79a47e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14210/HighFidelity-Beta-Interface-PR14189-d79a47e.dmg

**Pull request merged**
