### PR TITLE
Fix suppress frequest constraint log spam

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- load dynamicsTests.js
- try out each test
- check logs to make sure it's not constantly spamming about "no rigidBody"

**Comment by CainFoool** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b1fe60b7c3f3407f240a430dcf33ea8a437fb40 available at: https://gist.github.com/d8af72fdfb02e0d1cc03caff40cd2c44<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10484-9b1fe60.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10484-9b1fe60.dmg

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
Testing *PASSED*

"no rigidBody" appears, however it doesn't spam it in console.

**Pull request merged**
