### PR TITLE
JSDoc fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9957/HighFidelity-Beta-PR13206-e44e7ca35f3b92687dd42988e9eb0ec97ffaa16a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9957/HighFidelity-Beta-PR13206-e44e7ca35f3b92687dd42988e9eb0ec97ffaa16a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9957/HighFidelity-Beta-Interface-PR13206-e44e7ca35f3b92687dd42988e9eb0ec97ffaa16a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9957/HighFidelity-Beta-PR13206-e44e7ca35f3b92687dd42988e9eb0ec97ffaa16a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9957/HighFidelity-Beta-Interface-PR13206-e44e7ca35f3b92687dd42988e9eb0ec97ffaa16a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9971/HighFidelity-Beta-PR13206-fa54461788d592ff96567fa4aa8025eb5b1b813a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9971/HighFidelity-Beta-Interface-PR13206-fa54461788d592ff96567fa4aa8025eb5b1b813a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9971/HighFidelity-Beta-PR13206-fa54461788d592ff96567fa4aa8025eb5b1b813a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9971/HighFidelity-Beta-Interface-PR13206-fa54461788d592ff96567fa4aa8025eb5b1b813a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10014/HighFidelity-Beta-PR13206-6a75e7acb63d90c8930006a6e07d095e53fdcc30.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10014/HighFidelity-Beta-PR13206-6a75e7acb63d90c8930006a6e07d095e53fdcc30.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10014/HighFidelity-Beta-Interface-PR13206-6a75e7acb63d90c8930006a6e07d095e53fdcc30.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10014/HighFidelity-Beta-PR13206-6a75e7acb63d90c8930006a6e07d095e53fdcc30.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10014/HighFidelity-Beta-Interface-PR13206-6a75e7acb63d90c8930006a6e07d095e53fdcc30.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10040/HighFidelity-Beta-PR13206-ebeee515811fde971d5656aa8a1cd6231d3d19e2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10040/HighFidelity-Beta-PR13206-ebeee515811fde971d5656aa8a1cd6231d3d19e2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10040/HighFidelity-Beta-Interface-PR13206-ebeee515811fde971d5656aa8a1cd6231d3d19e2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10040/HighFidelity-Beta-PR13206-ebeee515811fde971d5656aa8a1cd6231d3d19e2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10040/HighFidelity-Beta-Interface-PR13206-ebeee515811fde971d5656aa8a1cd6231d3d19e2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10092/HighFidelity-Beta-PR13206-bc757ddd41c7bb8c48636462478cb8ade231a94b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10092/HighFidelity-Beta-PR13206-bc757ddd41c7bb8c48636462478cb8ade231a94b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10092/HighFidelity-Beta-PR13206-bc757ddd41c7bb8c48636462478cb8ade231a94b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10092/HighFidelity-Beta-Interface-PR13206-bc757ddd41c7bb8c48636462478cb8ade231a94b.dmg

**Pull request merged**
