### PR TITLE
Add ccache support for Linux and Mac

### PR DESCRIPTION
**Pull request by Atlante45**
This is a test integration of ccache for Mac (Xcode compatible) and Linux.
Early results:
domain-server rebuild: 6s
assignment-client rebuild: 37s
interface rebuild: 1:22
full repo rebuild: 2:22
(4 core MacBook Pro from 2015)

Usage:
Just install ccache via `apt-get`, `brew`, etc
Set the max size of the cache on disk here: `~/.ccache/ccache.conf`
You can monitor the cache with: `ccache -s`

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3748/HighFidelity-Beta-PR11486-52a71f5b210593e5a32a0cb9014d50dd79ce97f8.exe

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3750/HighFidelity-Beta-PR11486-52a71f5b210593e5a32a0cb9014d50dd79ce97f8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3750/HighFidelity-Beta-PR11486-52a71f5b210593e5a32a0cb9014d50dd79ce97f8.exe

**Comment by AndrewMeadows** [comment]
@Atlante45, I cloned this branch and tried to build on my linux machine.  The build failed because I had already setup distcc and my configuration was incorrect for working with ccache.  I did some research on how to set things up correctly and learned: when ccache is setup correctly it will build the hifi codebase just fine, no CMake changes are required!  I verified: it works great.

Therefore I recommend that we don't merge this PR.  It should be up to each dev to correctly configure ccache for themselves.  In fact, the configureation overrides in this PR could actually interfere with a dev's working ccache setup.

**Comment by Atlante45** [comment]
@AndrewMeadows Sounds good. I'm interested to know how you configured that.

**Pull request closed without merging**
