### PR TITLE
fix -- munge collision-hull at last minute rather than store munged url as a property

### PR DESCRIPTION
**Pull request by sethalves**
- munge collision-hull at last minute rather than store munged url as a property

### CODE REVIEW

**Comment by sethalves** [comment]
this fixes a problem introduced in https://github.com/highfidelity/hifi/pull/10178

to test:
- rez http://headache.hungry.com/~seth/hifi/well/brick-well.obj and stand it up
- set the collision-type to compound, and use the same url for the compound-shape-url
- press ctrl-J to open the running-scripts dialog
- type "dice" into the filter, and run createDice.js
- throw dice against the ring and through it
- rez http://headache.hungry.com/~seth/hifi/motobug/motobug.obj and make sure its textures line up right

**Comment by hifi-gustavo** [comment]
Build console output for commit: b99959c73df3bd109f5b256e464ca0208d444bfb available at: https://gist.github.com/cd567e3ab881e835fd4999a48e4c78e6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10191-b99959c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10191-b99959c.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Rezzed ```http://headache.hungry.com/~seth/hifi/well/brick-well.obj``` and stood it up and set the collision-type to compound, and used the same url for the compound-shape-url and pressed ```ctrl-J``` to open the running-scripts dialog and typed ```dice``` into the filter, and ran ```createDice.js``` and threw dice against the ring and through it and rezzed ```http://headache.hungry.com/~seth/hifi/motobug/motobug.obj``` and made sure its textures line up right.  SCREEN SHOT ENCLOSED
capture

**Pull request merged**
