### PR TITLE
Fix MS15721: Delete app.json if installed script isn't running

### PR DESCRIPTION
**Pull request by zfox23**
Implements [MS15721](https://highfidelity.fogbugz.com/f/cases/15721/Installed-tablet-apps-automatically-re-install-themselves-when-visiting-My-Purchases).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Purchase an App from the Marketplace (for example, the HRTF app on Staging).
2. From My Purchases, Install the app.
3. In Windows Explorer, open the folder: `C:\Users\<username>\AppData\Roaming\High Fidelity - <build>\Interface\Apps`. Verify that there's one `.app.json` file in that folder.
4. Close My Purchases.
5. From Running Scripts (CTRL+J), kill the script associated with the app you just installed.
6. Re-open My Purchases.
7. Verify that the script associated with the app you purchased in (1) does NOT re-run.
8. Verify that the `.app.json` file in the folder from (3) has been deleted.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10509/HighFidelity-Beta-PR13347-d4a19e7.apk

**Comment by howard-stearns** [comment]
dev approved, but DNM pending review of ticket by PM.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10509/HighFidelity-Beta-PR13347-d4a19e7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10509/HighFidelity-Beta-Interface-PR13347-d4a19e7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10509/HighFidelity-Beta-PR13347-d4a19e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10509/HighFidelity-Beta-Interface-PR13347-d4a19e7.exe

**Comment by qlikmorales** [comment]
Currently Testing

**Comment by qlikmorales** [comment]
@conklin94122 
PASS

**Pull request merged**
