### PR TITLE
only attempt default asset upload for local files

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

1. In a domain where you have permissions to write assets, drag and drop a local file from your machine and confirm you are able to upload it to the asset server.
2. Open the marketplace and drag a link from the marketplace onto your Interface window. It should not pop open the prompt to upload to the asset server. 
3. Confirm that performing step 2 on master/stable you do see the modal pop up prompting to upload (which doesn't mean anything since you're attempting to upload a remote URL).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5537/HighFidelity-Beta-PR11935-3265eb42f191d726e98494de89f30a80581d218c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5537/HighFidelity-Beta-PR11935-3265eb42f191d726e98494de89f30a80581d218c.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
In a domain where you have permissions to write assets, drag and drop a local file from your machine and confirm you are able to upload it to the asset server. | Pass
Open the marketplace and drag a link from the marketplace onto your Interface window. It should not pop open the prompt to upload to the asset server. | Pass
Confirm that performing step 2 on master/stable you do see the modal pop up prompting to upload (which doesn't mean anything since you're attempting to upload a remote URL). | Pass

Did not get the popup on this version vs master. Looks good to me!

**Pull request merged**
