### PR TITLE
Expand frame decoration when mouse is over a window in HMD mode

### PR DESCRIPTION
**Pull request by jherico**
When mousing over a window in the HMD, make the frame decorations bigger to make it easier to move the window with hand controllers.

### CODE REVIEW

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9X72uQnS&#x2F;71-increase-the-target-areas-for-window-close-pin-and-move"> Increase the target areas for window close, pin and move</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 998afef8759e88db36ba778d528de030e57ab4e2 available at: https://gist.github.com/16e1942f7d852413528f40b5f9b2ac53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8229-998afef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8229-998afef.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Unable to move the window with hand controllers testing with hydras.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6336362d40fbd2e5e76c7d0000f83ee07da68934 available at: https://gist.github.com/16e1942f7d852413528f40b5f9b2ac53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8229-6336362.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8229-6336362.dmg

**Comment by RyanDowne** [comment]
@kevinmthomasse I don't think this is meant to work with Hydras only Vive hand controllers but I will let @jherico chime in.

**Comment by jherico** [comment]
it's intended to work with any hand controller that works with handControllerGrab.js and handControllerPointer.js.  If the hydras were working with it before, they should still be working with it.  The PR has been updated though, so can you re-test?

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  On second attempt, with a very careful movement within an active UI window such as an edit window, control allows movement within the UI as long as the mouse is within the UI.  Successfully able to manipulate the window including selecting check-boxes and clicking on the X to close the window.  After a deeper inspection assuming the window is in complete focus, the control does work appropriately.

**Pull request merged**
