### PR TITLE
RC67: Fix a crash in Image Provider when logging in or reloading all scripts

### PR DESCRIPTION
**Pull request by zfox23**
RC67 version of #13063.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- A set-up wallet
- An HMD that you are wearing
- You're logged out

### Tests
1. Log out of your High Fidelity account using the Tablet
    - Verify that you're logged out and that you didn't crash.
2. Log in to your High Fidelity account using the Tablet
    - Verify that you're logged in and that you didn't crash.
3. Repeat steps 1 and 2 a large number of times (10+)
4. Press CTRL+R to reload all scripts.
    - Verify that you didn't crash
5. Repeat step 4 a medium number of times (5+)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9379/app_13071_PR_d5f809c3c08730a3016c772a4b710fd8e7b10d85.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9379/HighFidelity-Beta-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9379/HighFidelity-Beta-Interface-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9379/HighFidelity-Beta-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9379/HighFidelity-Beta-Interface-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.exe

**Comment by Qliemillar** [comment]
@conklin94122 

Crash was not unique to this PR (also occurs in Master and previous build of RC67), so updating to a Pass.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9432/app_13071_PR_d5f809c3c08730a3016c772a4b710fd8e7b10d85.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9432/HighFidelity-Beta-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9432/HighFidelity-Beta-Interface-PR13071-d5f809c3c08730a3016c772a4b710fd8e7b10d85.dmg

**Pull request merged**
