### PR TITLE
Add some debugging stats to entity server

### PR DESCRIPTION
**Pull request by ZappoMan**
This adds some additional viewer/sending stats to the entity server so we can see if/when viewers have been sent the latest data about an entity vs when that entity was last edited.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 08ba535c384a62a09ca67583409405694038e9df available at: https://gist.github.com/69945cde0a907496ab69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ac8e519924650eb316478273c05782e910822ce0 available at: https://gist.github.com/69945cde0a907496ab69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e51a902046304ea8f6619e79a319ef1578c440e available at: https://gist.github.com/69945cde0a907496ab69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee3e51274e777921f62c0ec5edecf9ec4ac496f6 available at: https://gist.github.com/69945cde0a907496ab69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4497d21aecde9b69babd1434252c599ed76f1f56 available at: https://gist.github.com/69945cde0a907496ab69<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6527.dmg

**Comment by AndrewMeadows** [comment]
So that's where the code lives that generates the status page.

**Comment by AndrewMeadows** [comment]
That might be good way to DOS an entity-server: pound it with status requests.  But there's probably a few easy ways to refuse service, or supply stale data when under attack -- we can wait until people try it.

**Comment by ZappoMan** [comment]
The stats page should not generally be enabled for most servers... we have it on our servers for debugging and testing purposes... but it's not enabled by default for stack managers.

**Comment by ZappoMan** [comment]
for people running serious server infrastructure they can/should be setting up network security groups that would only allow access to those domain/server web consoles from allowed clients - we'd have the same issue with the domain server.

**Pull request merged**
