### PR TITLE
prevent Script.include() from including the same file multiple times

### PR DESCRIPTION
**Pull request by ZappoMan**
this will prevent scripts from causing infinite recursive includes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ede0a39b5b8dffd24de50e539b6b9c39c659ea75 available at: https://gist.github.com/f2104ac16f031ef8e817<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5761.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5761.dmg

**Comment by howard-stearns** [comment]
I'm afraid this isn't working for me.

Tested as follows with three scripts (start, a, and b, in a directory named test-includes):

///start.js:
var a, b;
print('initially: a:' + a + ' b:' + b);
Script.include(['a.js', '../test-includes/a.js', 'b.js', 'a.js']);
print('finally a:' + a + ' b:' + b);

/// a.js:
Script.include('b.js');
if (a === undefined) {
    a = 0;
}
a++;
print('script a:' + a);

/// b.js:
if (b === undefined) {
    b = 0;
}
b++;
print('script b: ' + b);

Release (2988) loads a and b several times, with some odd "loading" messages:
[DEBUG] [09/09 21:04:23] stopping script... "/Users/howardstearns/models/scripts/test-includes/start.js"
[DEBUG] [09/09 21:04:23] ScriptEngine loading file: "/Users/howardstearns/models/scripts/test-includes/start.js"
[DEBUG] [09/09 21:04:23] Logging activity "loaded_script"
[DEBUG] [09/09 21:04:23] script:print()<< "initially: a:undefined b:undefined"
[DEBUG] [09/09 21:04:23] Loading script at QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" )
[DEBUG] [09/09 21:04:23] Loading script at QUrl( "file:///Users/howardstearns/models/scripts/test-includes/a.js" )
[DEBUG] [09/09 21:04:23] Loading script at QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" )
[DEBUG] [09/09 21:04:23] script:print()<< "script b: 1"
[DEBUG] [09/09 21:04:23] script:print()<< "script a:1"
[DEBUG] [09/09 21:04:23] Loading script at QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" )
[DEBUG] [09/09 21:04:23] script:print()<< "script b: 2"
[DEBUG] [09/09 21:04:23] script:print()<< "script a:2"
[DEBUG] [09/09 21:04:23] script:print()<< "script b: 3"
[DEBUG] [09/09 21:04:23] Loading script at QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" )
[DEBUG] [09/09 21:04:23] script:print()<< "script b: 4"
[DEBUG] [09/09 21:04:23] script:print()<< "script a:3"
[DEBUG] [09/09 21:04:23] script:print()<< "finally a:3 b:4"

The PR build (5761 build 1397) is better, but still loads too many times:
[DEBUG] [09/09 21:06:10] ScriptEngine loading file: "/Users/howardstearns/models/scripts/test-includes/start.js"
[DEBUG] [09/09 21:06:10] Logging activity "loaded_script"
[DEBUG] [09/09 21:06:10] script:print()<< "initially: a:undefined b:undefined"
[DEBUG] [09/09 21:06:10] Loading script at   QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/09 21:06:10] Loading script at   QUrl( "file:///Users/howardstearns/models/scripts/test-includes/a.js" ) 
[DEBUG] [09/09 21:06:10] Loading script at   QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/09 21:06:10] script:print()<< "script b: 1"
[DEBUG] [09/09 21:06:10] script:print()<< "script a:1"
[DEBUG] [09/09 21:06:10] Script.include() ignoring previously included url:  QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/09 21:06:10] script:print()<< "script a:2"
[DEBUG] [09/09 21:06:10] script:print()<< "script b: 2"
[DEBUG] [09/09 21:06:10] Script.include() ignoring previously included url:  QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/09 21:06:10] script:print()<< "script a:3"
[DEBUG] [09/09 21:06:10] script:print()<< "finally a:3 b:2"

**Comment by ZappoMan** [comment]
I'll test your repro case. But to be clear, my goal was to to prevent loading of the same fully qualified urls.

**Comment by ZappoMan** [comment]
Ok. I see what you did here and why it didn't work. I can fix it. The main issue is that I waited till the file was downloaded before adding it to the set of previously loaded includes. I your case I suspect the asynchronous loads are started before the first include is completed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f45e182d33331f3ffd49db37ab0a5d24fe6ade6e available at: https://gist.github.com/f2104ac16f031ef8e817<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5761.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5761.dmg

**Comment by howard-stearns** [comment]
Looks good. My test output is:
[DEBUG] [09/10 09:21:43] ScriptEngine loading file: "/Users/howardstearns/models/scripts/test-includes/start.js"
[DEBUG] [09/10 09:21:43] Logging activity "loaded_script"
[DEBUG] [09/10 09:21:43] script:print()<< "initially: a:undefined b:undefined"
[DEBUG] [09/10 09:21:43] Script.include() ignoring previously included url:  QUrl( "file:///Users/howardstearns/models/scripts/test-includes/a.js" ) 
[DEBUG] [09/10 09:21:43] Script.include() ignoring previously included url:  QUrl( "file:///Users/howardstearns/models/scripts/test-includes/a.js" ) 
[DEBUG] [09/10 09:21:43] Loading script at   QUrl( "file:///Users/howardstearns/models/scripts/test-includes/a.js" ) 
[DEBUG] [09/10 09:21:43] Loading script at   QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/10 09:21:43] Script.include() ignoring previously included url:  QUrl( "file:///Users/howardstearns/models/scripts/test-includes/b.js" ) 
[DEBUG] [09/10 09:21:43] script:print()<< "script a:1"
[DEBUG] [09/10 09:21:43] script:print()<< "script b: 1"
[DEBUG] [09/10 09:21:43] script:print()<< "finally a:1 b:1"

**Pull request merged**
