### PR TITLE
Move animation stats into its own Menu

### PR DESCRIPTION
**Pull request by hyperlogic**
Animations stats are no longer are displayed when the `Developer > Show Statistics` menu is checked.  Instead a new stats menu can be used to display animation stats `Developer > Show Animation Stats`.

It contains three panels
1. State Machine information, current state, or previous state and alpha value when changing states.
2. AnimVars a list of all anim variables that have changed in the last 2 seconds.  Values that have not changed in 2 seconds will fade out.
3. Alpha values for each animation clip currently playing.   If a clip's alpha has not changed in 2 seconds it will fade out.

Here is an example screen shot:
image

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/18141/Animation-Stats-are-cluttering-up-the-Stats-Menu

**Comment by hyperlogic** [comment]
QA Test plan:
  * Ensure that animation stats no longer are displayed when `Developer > Show Statistics` Menu is active
  * Ensure that `Developer > Show Animation Stats` shows a panel similar to the image below.

It is expected that the stats screens overlap if they are both active.
QA does not need to verify the contents of the stats display are working, just that they are visible.

image

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12758/HighFidelity-Beta-PR13956-6508533.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12758/HighFidelity-Beta-Interface-PR13956-6508533.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12758/HighFidelity-Beta-PR13956-6508533.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12758/HighFidelity-Beta-Interface-PR13956-6508533.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12770/HighFidelity-Beta-PR13956-5a059e9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12770/HighFidelity-Beta-PR13956-5a059e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12770/HighFidelity-Beta-Interface-PR13956-5a059e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12770/HighFidelity-Beta-PR13956-5a059e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12770/HighFidelity-Beta-Interface-PR13956-5a059e9.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
PASS @conklin94122 

- Animatations stats display under `Developer > Show Animation Stats`.
- Animation stats displays three panels as described: State Machines, Animations Vars (Current State), Alpha values.
- Alpha values clip after two seconds of inactivity, as expected.
- `Developer > Show Statistics` does not show the Animation Statistics.

Additional Testing:

- Changed multiple avatars.
- Changed domains.
- Verified that multiple states (standing, sitting, flying) display statistics.
- Verified that the emotes display stats.
- Verified that attachments do not interfere with the animation stats.
- Verified closing the animation stats page multiple times does not affect it.
- Verified that showing (and removing) both the stats page and animation stats page multiple times does not affect either.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12784/HighFidelity-Beta-PR13956-5a059e9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12784/HighFidelity-Beta-PR13956-5a059e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12784/HighFidelity-Beta-Interface-PR13956-5a059e9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12784/HighFidelity-Beta-PR13956-5a059e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12784/HighFidelity-Beta-Interface-PR13956-5a059e9.dmg

**Pull request merged**
