### PR TITLE
DDE miscellaneous

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
@cozza13 It would be great if you can check that DDE still runs OK on OSX with this PR, just in case.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 766087c032e0e35287d6349109d391946e7f3700 available at: https://gist.github.com/f9da17bedba42ee7d5e7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4665.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4665.dmg

**Comment by PhilipRosedale** [comment]
@cozza13 Can you check tomorrow?

**Comment by cozza13** [comment]
@ctrlaltdavid it works

**Comment by ctrlaltdavid** [comment]
Thanks @cozza13 ... Should be good to CR and merge then.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 35e2b87a70d43cef7447db218df548584528987a available at: https://gist.github.com/f9da17bedba42ee7d5e7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4665.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4665.dmg

**Pull request merged**
