### PR TITLE
Update eye look at interest calculation

### PR DESCRIPTION
**Pull request by hyperlogic**
This now takes distance, your facing toward other avatars, and their facing toward you into the interest calculation.

Also, separate the logic for myAvatar look at from other avatars snapping their gaze toward myAvatar.
Previously these two separate elements where merged together in a single loop.

https://highfidelity.manuscript.com/f/cases/19728/Improve-Avatar-Eye-Look-At-Calculation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16168/HighFidelity-Beta-PR14647-d87bc3e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16168/HighFidelity-Beta-PR14647-d87bc3e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16168/HighFidelity-Beta-Interface-PR14647-d87bc3e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16178/HighFidelity-Beta-PR14647-71991c2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16178/HighFidelity-Beta-PR14647-71991c2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16178/HighFidelity-Beta-Interface-PR14647-71991c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16178/HighFidelity-Beta-PR14647-71991c2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16178/HighFidelity-Beta-Interface-PR14647-71991c2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16232/HighFidelity-Beta-PR14647-7e68f53.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16232/HighFidelity-Beta-PR14647-7e68f53.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16232/HighFidelity-Beta-Interface-PR14647-7e68f53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16232/HighFidelity-Beta-PR14647-7e68f53.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16232/HighFidelity-Beta-Interface-PR14647-7e68f53.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS. Verified that eye tracking works as expected.(With HMD eye tracking still works even when avatar turns head away)

**Pull request merged**
