### PR TITLE
undo rayTest() optimization to prevent crash

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.fogbugz.com/f/cases/16045/crash-on-strafing

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
The crash repro recipe is:

Login with HMD.
Press **SHIFT + LeftArrow** to strafe left
Crash!

**Test Plan:**

**(1)** Verify crash recipe above works in `hifi/master`.

**(2)** Verify crash recipe does NOT work in this PR.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10714/HighFidelity-Beta-PR13420-fd3510b.apk

**Comment by sabrina-shanman** [comment]
For those interested, here were the measurements of the performance difference:
https://github.com/highfidelity/hifi/pull/13304#issuecomment-395900303

**Comment by sabrina-shanman** [comment]
I am looking into why the crash is occurring to see if we can figure out the underlying cause.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10714/HighFidelity-Beta-PR13420-fd3510b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10714/HighFidelity-Beta-Interface-PR13420-fd3510b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10714/HighFidelity-Beta-PR13420-fd3510b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10714/HighFidelity-Beta-Interface-PR13420-fd3510b.exe

**Comment by AndrewMeadows** [comment]
Closing this branch.  The rollback isn't necessary after a more correct fix in #13425.

**Pull request closed without merging**
