### PR TITLE
Fixed typo in qWarning message.

### PR DESCRIPTION
**Pull request by Nex-Pro**
Replaced "Count" with "Could" in debug message.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3945/HighFidelity-Beta-PR11539-24974fdae3f3797b625c3d19a425ab1280e73057.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3945/HighFidelity-Beta-PR11539-24974fdae3f3797b625c3d19a425ab1280e73057.exe

**Comment by Nex-Pro** [comment]
This should not need QA it's just a Typo in a debug message string.

**Comment by hyperlogic** [comment]
No QA necessary.

**Pull request merged**
