### PR TITLE
Add grid entities to create

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.manuscript.com/f/cases/20171

Pre-Merge Test Plan:
- Enter Interface in desktop mode into any domain with edit permissions
- Enter the following line into Developer menu > Scripting > Console and hit Enter:
Entities.addEntity({type: "Grid", position: MyAvatar.position})
- Refresh your Entity List to verify a Grid entity is created as expected
- In the Entity List, open the Types dropdown, verify Grid is the last type choice with a Grid icon next to it, and verify that it filters Grid entities in and out of the list as expected
- Select the Grid entity in the list and then view the Properties tab
- Verify the same Grid icon appears at the top left of the Properties tab
- Verify Grid entity properties contain the Spatial, Behavior, and Physics properties groups but not the Collision property gorup
- Verify the Grid-specific properties that appear at the top under Parent Joint Index are:
Color - defaults to white
Follow Camera - checkbox defaults to checked
Major Grid Every - number defaults to 5
Minor Grid Every - number defaults to 1.00
- Uncheck Follow Camera (it's behavior is not working as intended and will be bugged)
- Expand the Grid entity dimensions to be large (at least 50 X and 50 Y dimensions). It is expected that Z dimensions cannot change.
- Verify changing the Color property changes the grid line colors
- Verify that Minor Grid Every changes the distance between grid lines (enter numbers manually such as 0.5, 1.0, 2.0, 5.0 to see the changes instead of dragging)
- Verify that Major Grid Every changes the interval of smaller grid lines at which a thicker line is drawn (use the step arrows instead of dragging to see the changes more closely)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16275/HighFidelity-Beta-PR14662-3dc857c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16275/HighFidelity-Beta-PR14662-3dc857c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16275/HighFidelity-Beta-Interface-PR14662-3dc857c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16275/HighFidelity-Beta-PR14662-3dc857c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16275/HighFidelity-Beta-Interface-PR14662-3dc857c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16290/HighFidelity-Beta-PR14662-11de279.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16290/HighFidelity-Beta-Interface-PR14662-11de279.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16290/HighFidelity-Beta-PR14662-11de279.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16290/HighFidelity-Beta-PR14662-11de279.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16290/HighFidelity-Beta-Interface-PR14662-11de279.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16303/HighFidelity-Beta-PR14662-fbb7ea6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16303/HighFidelity-Beta-PR14662-fbb7ea6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16303/HighFidelity-Beta-Interface-PR14662-fbb7ea6.dmg

**Comment by QliCknox** [comment]
Currently Testing when built

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16303/HighFidelity-Beta-PR14662-fbb7ea6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16303/HighFidelity-Beta-Interface-PR14662-fbb7ea6.exe

**Comment by dback2** [comment]
Fixed color picker issues that Cheyenne found above.

Follow Camera is not working as intended and the above issues with it should be opened as a bug for RC79 and assigned to Sam Gondelman. These issues are not regressions and are not RC blockers.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16313/HighFidelity-Beta-PR14662-4766ce5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16313/HighFidelity-Beta-PR14662-4766ce5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16313/HighFidelity-Beta-Interface-PR14662-4766ce5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16313/HighFidelity-Beta-PR14662-4766ce5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16313/HighFidelity-Beta-Interface-PR14662-4766ce5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16316/HighFidelity-Beta-PR14662-d9e229d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16316/HighFidelity-Beta-PR14662-d9e229d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16316/HighFidelity-Beta-Interface-PR14662-d9e229d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16316/HighFidelity-Beta-PR14662-d9e229d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16316/HighFidelity-Beta-Interface-PR14662-d9e229d.exe

**Comment by QliCknox** [comment]
Fail

Grid Entity button does not appear on the Create Tab
Major Grid Every still breaks the grid when brought to values above 24

screen shot 2019-01-08 at 8 42 35 am
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2737465/hifi-log.txt)

**Comment by dback2** [comment]
Grid Entity button does not appear on the Create Tab:
The fact that Grid entities should appear on Create tab was removed from the test plan above, apologies it wasn't also updated on the MS ticket's test plan.

**Comment by QliCknox** [comment]
Pass

Talked with David about the fails, changing fail to a pass.
Writing up bug on the follow camera issue I noticed yesterday.

**Pull request merged**
