### PR TITLE
add support for redirection on domain at max capacity

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c32e65feb04d0aea516bea0ecc4e248b03c1782 available at: https://gist.github.com/e5b48d7fa8ad214adcec198462274afe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8637-3c32e65.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8637-3c32e65.dmg

**Comment by ZappoMan** [comment]
Test Plan:
- Run the sandbox from this build 
- go to domain settings, set the "Redirect to Location on Maximum Capacity" to some place name (also running this build)
- set the "Maximum User Capacity" to 1, and make sure that localhost is not ignored in max connections
- connect 2 clients (from this build) to the domain
- the second one should get redirected to the other place name.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5d3d4bdbd944b2111d21812695fc02921ad186d1 available at: https://gist.github.com/e5b48d7fa8ad214adcec198462274afe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8637-5d3d4bd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8637-5d3d4bd.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Test setup - stack running on Ubuntu 16.04 (LAN box) running this PR - Client 1 Windows 10 - Client 2 Linux.  Max cap set to 1 no allowance for over-population granted.

Works as expected for basic test case - over capacity user is redirected to fallback.
Tested that giving a specific user rights to connect even if over capacity works - yes.
One oddity I noticed (just for pedantic info).  If you have capacity set to 1, and 1 AV is in domain + 1 AV given ignore max capacity then you revoke right to ignore max capacity and apply (restarting DS) you still have 2 AVs until 1 leaves, tries to return.  This makes sense in a way as changing that would likely be complex.

**Comment by Atlante45** [comment]
Brace yourselves, infinite redirects are coming!

**Pull request merged**
