### PR TITLE
Photobooth Improvements - Stage, Camera Angles, and Lights

### PR DESCRIPTION
**Pull request by fayeli**
To Test: 
- follow the same instruction from https://github.com/highfidelity/hifi/pull/9174
- make sure your avatar stands inside of the zone so that lighting works correctly. If you stand on the stage(white big platform), it should be good.
- confirm that the framing now looks better

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78c96293a7fbb5e33934bb274f7f742fd036c1c9 available at: https://gist.github.com/8f869d98ff547feacda25a0c0d158e11<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9182-78c9629.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9182-78c9629.dmg

**Comment by Nex-Pro** [comment]
Testing this following preceding test of #9174

**Comment by Nex-Pro** [comment]
Limited success.

On running script while standing on the grid surface at welcome 3  the set loaded half buried in the surface.

The default test object photgraphed ok after re-running the script a few metres higher.

Importing the hot dog  did not initially resize.
Hitting the redo icon on the model URL resized the hotdog but IMO too small. and again too low.

Each camera option worked as expected.
Script cleanup succeeded.


hifi-snap-by-hyperdeity-on-2016-12-10_11-26-44
hifi-snap-by-hyperdeity-on-2016-12-10_11-26-44
hifi-snap-by-hyperdeity-on-2016-12-10_11-27-52
hifi-snap-by-hyperdeity-on-2016-12-10_11-27-56
hifi-snap-by-hyperdeity-on-2016-12-10_11-28-01
hifi-snap-by-hyperdeity-on-2016-12-10_11-28-47
hifi-snap-by-hyperdeity-on-2016-12-10_11-28-54
hifi-snap-by-hyperdeity-on-2016-12-10_11-29-01
hifi-snap-by-hyperdeity-on-2016-12-10_11-29-06
hifi-snap-by-hyperdeity-on-2016-12-10_11-29-13
hifi-snap-by-hyperdeity-on-2016-12-10_11-29-18

hifi-snap-by-hyperdeity-on-2016-12-10_11-29-23

**Comment by Nex-Pro** [comment]
Feedback: How about replace camera dropdown with buttons.

**Pull request merged**
