### PR TITLE
enable workload regulation by default

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12617/HighFidelity-Beta-PR13928-49e48f5.apk

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12617/HighFidelity-Beta-Interface-PR13928-49e48f5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12617/HighFidelity-Beta-PR13928-49e48f5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12617/HighFidelity-Beta-Interface-PR13928-49e48f5.dmg

**Comment by AndrewMeadows** [comment]
**Test Plan**:

TODO: write this test plan

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Objects react accordingly when in their respected zones.

**Pull request merged**
