### PR TITLE
Add version number and make adding new menu items to Server Console easier

### PR DESCRIPTION
**Pull request by imgntn**
This PR changes the Menu items functions in the server console to make it easier to add new menu items.  The last PR threw off the menu index; now the updates happen without reference by index.

To test:
1. Download this PR and run server console
2. Click on tray icon and try each menu option, ensuring that they work as expected.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b929089af7644977621f13fc8a3ff06b5b4cd837 available at: https://gist.github.com/e1091e564fd71eff184e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7342.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7342.dmg

**Comment by Nex-Pro** [comment]
having a look at this now.

**Comment by Nex-Pro** [comment]
Tested on Win10 64bit. No problems.

**Comment by ZappoMan** [comment]
I've also tested this and confirmed that not only does the menu show the version, but all the menu items still work. I am willing to merge this now.

**Pull request merged**
