### PR TITLE
Make Animation Unit Tests Pass Again

### PR DESCRIPTION
**Pull request by hyperlogic**
Also, minor fix to animation triggers

### CODE REVIEW

**Comment by hyperlogic** [comment]
No QA necessary, unit tests can only be run by developers

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16941/HighFidelity-Beta-PR14822-2c40b12.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16941/HighFidelity-Beta-PR14822-2c40b12.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16941/HighFidelity-Beta-Interface-PR14822-2c40b12.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16941/HighFidelity-Beta-PR14822-2c40b12.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16941/HighFidelity-Beta-Interface-PR14822-2c40b12.exe

**Comment by hyperlogic** [comment]
QA Test plan:
* Ensure avatar running and jumping animations work correctly
* Ensure that avatar emote app works correctly.

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/21015/Animation-Unit-Tests-Do-Not-Compile

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
Forgot to approve!

**Pull request merged**
