### PR TITLE
Interstitial page/redirect domain improvements

### PR DESCRIPTION
**Pull request by wayne-chen**
- Improvement for MS#[18755](https://highfidelity.manuscript.com/f/cases/18755/Update-Visual-Assets-Within-404-Redirect-Room)
- Implicit fix for MS#[18557](https://highfidelity.manuscript.com/f/cases/18557/interstitial-page-on-desktop-cannot-see-call-to-action-text-on-the-ground)

## TEST PLAN
- Launch Interface
- In the menu, open `Settings > Developer Menu`
- In the menu, open `Developer > Console...`
- Run `Window.interstitialModeEnabled = true;` to enable the interstitial page for loading
- `CTRL-R` to reload cache/scripts
- The interstitial page should show up when navigating between domains
- When there is an error connecting to a domain via connection timeout, not logged in as an authorized user, or with a protocol version mismatch, the interstitial page should disappear and the user should land in the 404 serverless domain with text showing the error that occurred and a "Try Again" or "Back" button to either navigate to the same domain again or to go back to the domain before the one attempted
### Notes 
- toggling `Window.interstitialModeEnabled` and hitting `CTRL-R` afterwards to reload caches/scripts should toggle the interstitial page appearing and landing in the 404 redirect serverless domain accordingly

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13377/HighFidelity-Beta-PR14092-fda3ec8.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13379/HighFidelity-Beta-PR14092-33db8e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13379/HighFidelity-Beta-PR14092-33db8e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13379/HighFidelity-Beta-Interface-PR14092-33db8e1.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Stopped testing (for obvious reasons)

@wayne-chen 
Preliminary results:

Ghostly web entity from the serverless domain stuck around at its coordinates through the interstitial pages. However, this appears to happen in master. (9393)

I was uncertain whether this PR should have fixed this.

hifi-snap-by--on-2018-09-27_09-14-15


Other issues, which I could not reproduce in master (but might just need more time to do so):

In VR, the loading bar page ended up far above and behind/to the right of me.
The back button sent me to the wrong domain.




[hifi-log_2018-09-27_09.30.12.txt](https://github.com/highfidelity/hifi/files/2425052/hifi-log_2018-09-27_09.30.12.txt)
[hifi-log_2018-09-27_09.15.33_fa329876-dee3-4a35-9a2d-f0eaf2e98c8d.txt](https://github.com/highfidelity/hifi/files/2425053/hifi-log_2018-09-27_09.15.33_fa329876-dee3-4a35-9a2d-f0eaf2e98c8d.txt)

**Pull request closed without merging**
