### PR TITLE
Shadow dithered filtering

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes broken percentage closer filtering (PCF) of shadows. Shadows are now filtered with a dithered world space noise pattern. The noise pattern is very apparent at this time but should benefit a lot with the future introduction of temporal anti-aliasing (TAA) in a future PR.

# Test Case
This PR should be tested with the updated automated test case that can be found in my [mirror repository under branch "pcf"](https://github.com/Zvork/hifi_tests/tree/pcf/tests/engine/render/shadows)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4874/HighFidelity-Beta-PR11800-fa58cf2e603761fa31ce1f4e9249fa88942e2f12.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4874/HighFidelity-Beta-PR11800-fa58cf2e603761fa31ce1f4e9249fa88942e2f12.exe

**Comment by Nex-Pro** [comment]
@Zvork Won't the world-space noise make the shadows look odd? Ie. the pattern will be effectively static to the world while the shadow moves across it.

**Comment by Zvork** [comment]
@Nex-Pro I haven't really found a good solution. If the noise pattern is in screen space, then it also looks weird. For me this is just a temporary solution. I think the ideal would be an animated screen space noise to break the shadow aliasing combined with temporal anti-aliasing to smooth it out.

My initial plan was to just use a fixed screen space dithering pattern (as it was initially the pseudo-case in the shadow shader, inspired by chapter 11 of the first GPU Gems book) without noise but the dithering pattern led to some really clearly visible aliasing in various situations, especially along the shadow silhouette diagonals. Or maybe I did that wrong...

Another option would be to remove dithering / noise and just do a simple 4-tap filtering.

I'm really opened to discussion about this and maybe I should add some configuration options to test the various solutions. @samcake , what's your opinion on this?

**Comment by Zvork** [comment]
@Nex-Pro , @samcake Here are some screenshots with screen space dithering bug with noise off. There are some "ugly" cases, but which are probably due to shadow acne after second thought (shadow resolution is poor). Now that I think of it, it is probably nicer in this configuration than with noise off, especially without TAA to smooth it.

Tell me what you think. I can push this version with only dithering and update the test case in consequence if you feel it is a nicer option (which I think, now).

**Comment by Nex-Pro** [comment]
@Zvork  I appreciate you asking. Main issue for me is that these things tend to move with the POV. But probably a lot of users are just ready for shadows even if imperfect. Eager to QA this.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4948/HighFidelity-Beta-PR11800-e4818f1b4f5c42ce8b045116e5493794c26e59e0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4948/HighFidelity-Beta-PR11800-e4818f1b4f5c42ce8b045116e5493794c26e59e0.dmg

**Comment by Zvork** [comment]
I finally switched back to dithered, non noise PCF. Test case has been updated in consequence.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5004/HighFidelity-Beta-PR11800-d2c28c3c2163be31fc5660ee9aba47627a0e28a8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5004/HighFidelity-Beta-PR11800-d2c28c3c2163be31fc5660ee9aba47627a0e28a8.dmg

**Comment by ZappoMan** [comment]
This PR appears to touch more than just shadows, specifically it touches aspects of the lighting setup... we probably need to include test cases that read on the non-shadow lighting behavior as well.

**Comment by samcake** [comment]
Closing it since it s superseeded by 11938

**Pull request closed without merging**
