### PR TITLE
Merge Account & GlobalServices follow-up

### PR DESCRIPTION
**Pull request by dback2**
Follow-up PR to https://github.com/highfidelity/hifi/pull/11669 

-Delete AccountScriptingInterface class
-Rename GlobalServicesScriptingInterface class to AccountServicesScriptingInterface
-Deprecate Account and GlobalServices contexts pointing to AccountServicesScriptingInterface
-Add AccountServices context pointing to AccountServicesScriptingInterface

Final PR will be killing Account & GlobalServices contexts with advanced public notice.

Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/7536 (Desktop)
https://highfidelity.testrail.net/index.php?/cases/view/7535 (HMD)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6116/HighFidelity-Beta-PR12116-13c34b2d3321fcdea7a0f21103cd91258435104f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6116/HighFidelity-Beta-PR12116-13c34b2d3321fcdea7a0f21103cd91258435104f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6116/app_12116_PR.apk

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing completed. PASSED

**Pull request merged**
