### PR TITLE
fix crash in workload on timeout with entity-server

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11141/HighFidelity-Beta-PR13550-59fcee6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11141/HighFidelity-Beta-PR13550-59fcee6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11141/HighFidelity-Beta-Interface-PR13550-59fcee6.dmg

**Comment by AndrewMeadows** [comment]
The repro recipe for this crash works for the DEBUG interface build.  It might work for a RELEASE build, or might only be semi-reliable (dunno):

**(1)** Go to **rust-dev** domain
**(2)** Wait for it... wait for it... wait for it...
(It takes a long time for content to show up, then when the rendering system tries to update lighting and load all the objects into the physics engine it will take such a long time that the interface will loose connection with the entity-server, at which point...)
**(3)** Screen goes blank after loosing connection with entity-server
**(4)** crash

So try this instead (might work):

**(1)** Go to **rust-dev** domain
**(2)** After about half of the stuff has loaded...
**(3)** Remove the RJ-45 ethernet plug from the interface computer
**(4)** Count 6 seconds (screen should go dark after 5 and connection to entity-server is lost)
--> at this point `hifi/master` build might crash
--> this PR should not crash
**(5)** Reconnect ethernet plug and let domain show up again


I don't think it is necessary to verify the crash in a RELEASE build, but

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11141/HighFidelity-Beta-PR13550-59fcee6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11141/HighFidelity-Beta-Interface-PR13550-59fcee6.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Workload works well and no crashes.

**Pull request merged**
