### PR TITLE
Add a constant hud toggle button to the UI

### PR DESCRIPTION
**Pull request by jherico**
## Testing

This should add a constantly visible 2-state button to new the bottom center of the overlay pane.  Clicking it should toggle the pinned state of the UI.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9ee0c087e6f79b36850799bf476e80ab93c5938 available at: https://gist.github.com/ad65551a5daee0b57d53159a1b9a48b9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.dmg

**Comment by howard-stearns** [comment]
Nice.
One problem I encountered is that when you toggle off, the View->Overlays menu display is still checked/on.  I have no preference as to whether we fix that as part of this PR, or merge and fix later.

**Comment by howard-stearns** [comment]
Also, it must be the case that
  Reticle.pointingAtSystemOverlay || Overlays.getOverlayAtPoint(Reticle.position)
answers truthy (in Javascript) when the Reticle is over this button.
It is a bug that in this PR so far it answers 0.

(Although it would presumably be the system overlay part that answers, I don't care whether the system overlay part or the 2d overlay part answers.)

**Comment by jherico** [comment]
@howard-stearns I've fixed both the issues.  The button should now reflect the menu and it should return true for `Reticle.pointingAtSystemOverlay`

**Comment by howard-stearns** [comment]
Cool, I'll recheck when it builds.

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2R2r8JsR&#x2F;24-add-a-pinned-state-toggle-to-the-desktop"> Add a pinned state toggle to the desktop.</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: ba61491ee605d44fd5c39babb134cf85f07e8331 available at: https://gist.github.com/ad65551a5daee0b57d53159a1b9a48b9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.dmg

**Comment by howard-stearns** [comment]
Oops, now it doesn't work as a button. Click on it with the mouse. Nothing happens. 

(I was in desktop, using hardware mouse, with or without default scripts running. Other buttons do work, including 2d overlays, buttons on qml windows, and stats toggle.)

**Comment by jherico** [comment]
@howard-stearns whoops... missed a file on my checkin.  should be fixed.

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 29d9f51b584e205d62bf944af6400cf0beebc1a3 available at: https://gist.github.com/ad65551a5daee0b57d53159a1b9a48b9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8032.dmg

**Comment by howard-stearns** [comment]
Should we consider the following a bug?
  Start drving forward with 'w' key.
  While still driving, click the HUD toggle button.
  Expected: continue driving, but have HUD toggle.
  Actual: stops driving and toggles HUD. Need to click in world to get focus to continue.

**Comment by howard-stearns** [comment]
After discussion, we'll deal with the focus issue separately -- i.e., decide separately whether it's a bug and deal with it that way.

**Pull request merged**
