### PR TITLE
Addressbar close fix

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.manuscript.com/f/cases/9223/The-Enter-key-does-not-close-the-address-bar-in-hmd

Test plan:

Open address bar pressing enter
Move focus out of address input field by clicking on empty space within Tablet
Press enter. Tablet should close

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6793/app_12312_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6793/HighFidelity-Beta-PR12312-bca903a6dfbdecaaa494345b2a31b17addbe6756.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6796/app_12312_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6796/HighFidelity-Beta-PR12312-bca903a6dfbdecaaa494345b2a31b17addbe6756.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6796/HighFidelity-Beta-PR12312-bca903a6dfbdecaaa494345b2a31b17addbe6756.exe

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing. PASSED.

**Pull request merged**
