### PR TITLE
Controller Experiment 3

### PR DESCRIPTION
**Pull request by r3tk0n**
Experiment to see if gaze + pointing can be used to comfortably activate teleport or FarGrab.

**Notes:**

- This PR requires a user's wrist be rotated correctly for a given action. [-45, 45] degrees from the controller's Z axis is FarGrab, [45, 135] degrees from same is Teleport.

- The user's pointing vector (from their controller(s)) must be within a distance threshold on the horizontal plane from the avatar's look vector. The distance threshold is presently defined as one-tenth of the distance from the controller ray intersection to the controller.

- The user's head must be steady, with rotational velocity below a certain threshold (meaning the user's head is "stable") in order for the beams to activate.

- Pointing "downward" will cancel the beams.

- Pointing 80 degrees away from the avatar's look vector will cancel the beams.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12079/HighFidelity-Beta-PR13821-310b3e2.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12080/HighFidelity-Beta-PR13821-a2d882a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12080/HighFidelity-Beta-PR13821-a2d882a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12080/HighFidelity-Beta-Interface-PR13821-a2d882a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12080/HighFidelity-Beta-PR13821-a2d882a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12080/HighFidelity-Beta-Interface-PR13821-a2d882a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12084/HighFidelity-Beta-PR13821-27b7b2e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12084/HighFidelity-Beta-PR13821-27b7b2e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12084/HighFidelity-Beta-Interface-PR13821-27b7b2e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12084/HighFidelity-Beta-PR13821-27b7b2e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12084/HighFidelity-Beta-Interface-PR13821-27b7b2e.exe

**Comment by r3tk0n** [comment]
The build just above this comment is for the first draft.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12086/HighFidelity-Beta-PR13821-a2794b1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12086/HighFidelity-Beta-PR13821-a2794b1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12086/HighFidelity-Beta-Interface-PR13821-a2794b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12086/HighFidelity-Beta-PR13821-a2794b1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12086/HighFidelity-Beta-Interface-PR13821-a2794b1.exe

**Comment by r3tk0n** [comment]
Last thing on core to-do: Test methods to deactivate lasers.
Candidates:
- Rotational Velocity-based (shake controller erratically)
- Angle between look vector and aim (probably the easiest)

Additional goals:
- Enable laser activation on Oculus with pointing of finger.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12088/HighFidelity-Beta-PR13821-798e78d.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12090/HighFidelity-Beta-PR13821-30430df.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12090/HighFidelity-Beta-PR13821-30430df.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12090/HighFidelity-Beta-Interface-PR13821-30430df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12090/HighFidelity-Beta-PR13821-30430df.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12090/HighFidelity-Beta-Interface-PR13821-30430df.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12104/HighFidelity-Beta-PR13821-8e57586.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12104/HighFidelity-Beta-PR13821-8e57586.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12104/HighFidelity-Beta-Interface-PR13821-8e57586.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12109/HighFidelity-Beta-PR13821-c5d6350.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12109/HighFidelity-Beta-PR13821-c5d6350.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12109/HighFidelity-Beta-Interface-PR13821-c5d6350.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12109/HighFidelity-Beta-PR13821-c5d6350.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12109/HighFidelity-Beta-Interface-PR13821-c5d6350.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12112/HighFidelity-Beta-PR13821-dfba968.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12112/HighFidelity-Beta-PR13821-dfba968.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12112/HighFidelity-Beta-Interface-PR13821-dfba968.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12113/HighFidelity-Beta-PR13821-4468df4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12113/HighFidelity-Beta-PR13821-4468df4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12113/HighFidelity-Beta-Interface-PR13821-4468df4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12120/HighFidelity-Beta-PR13821-ddd87de.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12120/HighFidelity-Beta-PR13821-ddd87de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12120/HighFidelity-Beta-Interface-PR13821-ddd87de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12120/HighFidelity-Beta-PR13821-ddd87de.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12120/HighFidelity-Beta-Interface-PR13821-ddd87de.exe

**Comment by r3tk0n** [comment]
There's now a toggle switch, EXP3_USE_DISTANCE, in `controllerDispatcherUtils.js`. Meant to allow demoing of pointing-based interactions only.

Default still uses distance between look vector and controller raypick vector _in addition to_ index finger pointing as an option.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12133/HighFidelity-Beta-PR13821-fcdc97f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12133/HighFidelity-Beta-PR13821-fcdc97f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12133/HighFidelity-Beta-Interface-PR13821-fcdc97f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12133/HighFidelity-Beta-PR13821-fcdc97f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12133/HighFidelity-Beta-Interface-PR13821-fcdc97f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12136/HighFidelity-Beta-PR13821-2b314e3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12136/HighFidelity-Beta-PR13821-2b314e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12136/HighFidelity-Beta-Interface-PR13821-2b314e3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12136/HighFidelity-Beta-PR13821-2b314e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12136/HighFidelity-Beta-Interface-PR13821-2b314e3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12148/HighFidelity-Beta-PR13821-1690fef.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12148/HighFidelity-Beta-PR13821-1690fef.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12148/HighFidelity-Beta-Interface-PR13821-1690fef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12148/HighFidelity-Beta-PR13821-1690fef.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12148/HighFidelity-Beta-Interface-PR13821-1690fef.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12150/HighFidelity-Beta-PR13821-41fc98e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12150/HighFidelity-Beta-PR13821-41fc98e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12150/HighFidelity-Beta-Interface-PR13821-41fc98e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12150/HighFidelity-Beta-PR13821-41fc98e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12150/HighFidelity-Beta-Interface-PR13821-41fc98e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12157/HighFidelity-Beta-PR13821-400d5e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12157/HighFidelity-Beta-PR13821-400d5e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12157/HighFidelity-Beta-Interface-PR13821-400d5e0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12162/HighFidelity-Beta-PR13821-5b4d646.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12157/HighFidelity-Beta-PR13821-400d5e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12157/HighFidelity-Beta-Interface-PR13821-400d5e0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12162/HighFidelity-Beta-PR13821-5b4d646.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12162/HighFidelity-Beta-Interface-PR13821-5b4d646.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12162/HighFidelity-Beta-PR13821-5b4d646.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12162/HighFidelity-Beta-Interface-PR13821-5b4d646.exe

**Pull request closed without merging**
