### PR TITLE
Fixing Log in/Sign up dialog is missing "Forgot Username?" and "Forgot Password"

### PR DESCRIPTION
**Pull request by druiz17**
This issue was fixed in merged in RC66 but never merged back into master.
Here is that PR - https://github.com/highfidelity/hifi/pull/12768

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- logout of high fidelity
- open the login dialog
- there should be links if you forgot your username or password.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9975/HighFidelity-Beta-PR13211-d659696b60a3d205cb0967a42f52f9ab9dc9ac9d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9975/HighFidelity-Beta-PR13211-d659696b60a3d205cb0967a42f52f9ab9dc9ac9d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9975/HighFidelity-Beta-Interface-PR13211-d659696b60a3d205cb0967a42f52f9ab9dc9ac9d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9975/HighFidelity-Beta-PR13211-d659696b60a3d205cb0967a42f52f9ab9dc9ac9d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9975/HighFidelity-Beta-Interface-PR13211-d659696b60a3d205cb0967a42f52f9ab9dc9ac9d.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 "Forgot Username" and "Forgot Password" links exist on sign in dialog on both production and staging metaverses

**Pull request merged**
