### PR TITLE
WL 21386: ShortBow Improvements

### PR DESCRIPTION
**Pull request by CainFoool**
# Test Plan

1. Confirm that you can hear a sound effect and you can see a smoke effect appear for one second when you hit a ball with an arrow.
2. Confirm that the game ends okay and doesn't hang waiting for any balls.

Test this in your Local Sandbox, and running the 'startShortbow.js' script inside the zip attached. [shortbow.zip](https://github.com/highfidelity/hifi/files/1089823/shortbow.zip)

NOTE: Sound effect is a placeholder and will be swapped out prior to merging.

Per worklist https://worklist.net/21386

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
add to whitelist

**Comment by themelissabrown** [comment]
Note: sound effect is a placeholder and will be swapped out prior to merging

**Comment by YuppyPlays** [comment]
Will test when built :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/908/HighFidelity-Beta-PR10757-02b3a07e67aaa9984ac1ae0bf2d5ee012cabf3ac.dmg

**Comment by themelissabrown** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/911/HighFidelity-Beta-PR10757-02b3a07e67aaa9984ac1ae0bf2d5ee012cabf3ac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/911/HighFidelity-Beta-PR10757-02b3a07e67aaa9984ac1ae0bf2d5ee012cabf3ac.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested Windows Build: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/911/HighFidelity-Beta-PR10757-02b3a07e67aaa9984ac1ae0bf2d5ee012cabf3ac.exe

PASS:
- **PASS:** Confirm that you can hear a sound effect and you can see a smoke effect appear for one second when you hit a ball with an arrow.
    
- **PASS:** Confirm that the game ends okay and doesn't hang waiting for any balls.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6135/app_10757_PR.apk

**Pull request merged**
