### PR TITLE
Sitting emote variants, revisions on stand emote agree anims, point bug fix

### PR DESCRIPTION
**Pull request by dooglifeSF**
sitting emotes added:  agree_acknowledge, disagree_dismiss, emote_raisehand03
emotes reworked per Joshua comments: stand emote agree set, point
bug fix for sitting, stand point that had a hitch in the loop

Bugs/Tasks:
https://highfidelity.atlassian.net/browse/BUGZ-1412
https://highfidelity.atlassian.net/browse/DEV-453
https://highfidelity.atlassian.net/browse/DEV-452

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21176/HighFidelity-Beta-PR16143-b5d2675.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21176/HighFidelity-Beta-Interface-PR16143-b5d2675.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21176/HighFidelity-Beta-PR16143-b5d2675.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21176/HighFidelity-Beta-Interface-PR16143-b5d2675.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21176/HighFidelity-Beta-PR16143-b5d2675.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21176/HighFidelity-Quest-Beta-PR16143-b5d2675.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21201/HighFidelity-Beta-PR16143-422ad52.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21201/HighFidelity-Quest-Beta-PR16143-422ad52.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21201/HighFidelity-Beta-Interface-PR16143-422ad52.dmg

**Comment by hyperlogic** [comment]
Mysterious windows build failure, build this please.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21206/HighFidelity-Beta-PR16143-932093b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21206/HighFidelity-Quest-Beta-PR16143-932093b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21206/HighFidelity-Beta-PR16143-932093b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21206/HighFidelity-Beta-Interface-PR16143-932093b.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21209/HighFidelity-Beta-PR16143-932093b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21209/HighFidelity-Beta-Interface-PR16143-932093b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21209/HighFidelity-Beta-PR16143-932093b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21209/HighFidelity-Quest-Beta-PR16143-932093b.apk)

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21219/HighFidelity-Beta-PR16143-932093b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21219/HighFidelity-Beta-Interface-PR16143-932093b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21219/HighFidelity-Beta-PR16143-932093b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21219/HighFidelity-Beta-Interface-PR16143-932093b.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21219/HighFidelity-Beta-PR16143-932093b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21219/HighFidelity-Quest-Beta-PR16143-932093b.apk)

**Pull request merged**
