### PR TITLE
Removed ColorOverlay from TabletButton, added more icon & text states

### PR DESCRIPTION
**Pull request by hyperlogic**
Now uses separate images for each state. Now tabletButtonProxy has 4 state properties, one for icon and images.  This gives us support for full color on icons, and is a prerequisite for future work unifying the Toolbar and Tablet APIs

  * icon
  * hoverIcon
  * activeIcon
  * activeHoverIcon
  * text
  * hoverText
  * activeText
  * activeHoverText

Updated scripts to set new button states, if necessary.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:

No functional changes should be noticeable.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c783031b134284d66883f8f22e1ae63212c1b6c available at: https://gist.github.com/b991b5e5c2e17921aa3c11cbd47f94f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9668-1c78303.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9668-1c78303.dmg

**Comment by hyperlogic** [comment]
gifcreator download failure. let's try again. test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c783031b134284d66883f8f22e1ae63212c1b6c available at: https://gist.github.com/b991b5e5c2e17921aa3c11cbd47f94f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9668-1c78303.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9668-1c78303.dmg

**Comment by nbq** [comment]
testing this one

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* I tested every button on the tablet and noticed it change highlight on mouse over and color on click and they all function fine

**PASS**

**Pull request merged**
