### PR TITLE
Better webview handing for the tablet

### PR DESCRIPTION
**Pull request by druiz17**
When using the web view with the tablet and the web pages request a new web view window. That web view will appear in the tablet

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- While in tablet mode open goto (test on HMD and desktop mode)
- click on the info ( the 'i' icon) on one of the cards
- one the info page loads, click on the facebook or twitter icon.
- A new web page should appear in the tablet

- Note: That some web pages will not be in mobile format and when returning to a previous page the text boxes might not work. These issues will be fixed in a separate PR

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70d2d695577852fb0ce8fe092b37302c4faa1c58 available at: https://gist.github.com/945da6e686342e605717f10b3ebfd783<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10087-70d2d69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10087-70d2d69.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10087-70d2d69.exe

Test Plan:
- While in tablet mode open goto (test on HMD and desktop mode)
click on the info ( the 'i' icon) on one of the cards
one the info page loads, click on the facebook or twitter icon.
A new web page should appear in the tablet
- PASS: in HMD and Desktop Mode

hifi-snap-by-claudioshg-on-2017-03-31_13-05-10

**Pull request merged**
