### PR TITLE
Oculus store commerce

### PR DESCRIPTION
**Pull request by howard-stearns**
Removes the inappropriate parts of Market and Wallet apps for Oculus Store version of Interface.
See https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/407994404/Oculus+Store+-+Commerce+Part

Prototype of https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/407994404/Oculus+Store+-+Commerce+Part / https://highfidelity.fogbugz.com/f/cases/19450/Parent-ticket-oculus-store-commerce-part

Also implements/fixes:
https://highfidelity.fogbugz.com/f/cases/18612/appUi-js-spamming-logs
https://highfidelity.manuscript.com/f/cases/edit/19642/Incorrect-messaging-when-clicking-three-dots-context-menu-icon-on-an-item-in-My-Purchases-list-and-then-scrolling-up-and-down

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14309/HighFidelity-Beta-PR14261-a79fe4d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14309/HighFidelity-Beta-PR14261-a79fe4d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14309/HighFidelity-Beta-Interface-PR14261-a79fe4d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14309/HighFidelity-Beta-PR14261-a79fe4d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14309/HighFidelity-Beta-Interface-PR14261-a79fe4d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14329/HighFidelity-Beta-PR14261-7707d92.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14329/HighFidelity-Beta-PR14261-7707d92.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14329/HighFidelity-Beta-Interface-PR14261-7707d92.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14329/HighFidelity-Beta-PR14261-7707d92.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14329/HighFidelity-Beta-Interface-PR14261-7707d92.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14358/HighFidelity-Beta-PR14261-ce20b82.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14358/HighFidelity-Beta-PR14261-ce20b82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14358/HighFidelity-Beta-Interface-PR14261-ce20b82.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14360/HighFidelity-Beta-PR14261-993cb0c.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14361/HighFidelity-Beta-PR14261-e1e9b78.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14366/HighFidelity-Beta-PR14261-1ff50bc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14361/HighFidelity-Beta-PR14261-e1e9b78.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14361/HighFidelity-Beta-Interface-PR14261-e1e9b78.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14361/HighFidelity-Beta-PR14261-e1e9b78.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14361/HighFidelity-Beta-Interface-PR14261-e1e9b78.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14366/HighFidelity-Beta-PR14261-1ff50bc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14366/HighFidelity-Beta-Interface-PR14261-1ff50bc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14406/HighFidelity-Beta-PR14261-6284c90.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14406/HighFidelity-Beta-PR14261-6284c90.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14406/HighFidelity-Beta-Interface-PR14261-6284c90.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14406/HighFidelity-Beta-PR14261-6284c90.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14406/HighFidelity-Beta-Interface-PR14261-6284c90.exe

**Comment by rickcarr044** [comment]
Currently testing PR14261

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14409/HighFidelity-Beta-PR14261-936c2b2.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14410/HighFidelity-Beta-PR14261-9095df4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14410/HighFidelity-Beta-PR14261-9095df4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14410/HighFidelity-Beta-Interface-PR14261-9095df4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14410/HighFidelity-Beta-PR14261-9095df4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14410/HighFidelity-Beta-Interface-PR14261-9095df4.exe

**Comment by qlilaseguinolaza** [comment]
Looking this over also, do these pages look right? Not sure if they should be wrapped inside the Assets app:

screen shot 2018-10-25 at 3 35 16 pm

screen shot 2018-10-25 at 3 55 37 pm

**Comment by howard-stearns** [comment]
good finds. exactly the kind of issues we're looking for. Thanks.

**Comment by rickcarr044** [comment]
1.  On staging after setting "Wallet.limitedCommerce = true" in the console and then clicking Assets in the toolbar I get a flashing set of screens between the Wallet Setup dialog ("Where are your private keys?") and the Inventory screen.  

Does not occur on production with a different test account where clicking ASSETS goes to Inventory tab.

walletsetup

2.  Are the Systray notifications going to be installed with the Oculus Store builds?  If they are, note that "Wallet" is still one of the options when it should probably be "Asset"

**Comment by howard-stearns** [comment]
WRT the last (10/28) comments:

1. Are you going between staging and production on the same machine, with the same account login? (Recall that using the same login on production and staging is not recommended, because the key files are different between the two, but the file names are based on login alone. So using the same login on both is bound to lead to confusion, such that you'll be trying to use your production key file on staging, or vice versa, and then the system will tell you.)

2. No sys tray console in oculus store. (Note parenthetical remark in second to last item in test plan.)

**Comment by howard-stearns** [comment]
**To Do List**
- [ ] The text "UNAVAILABLE(sold out)" (where "sold out" varies for different unavailability reasons) is missing a space before parenthesis.
- [ ] Remove My Purchases link from !limitedCommerce version of marketplace header. (Already gone in limitedCommerce version.)
- [ ] Certificate display appears within the wallet/assets frame. Should be "naked", like before.
- [ ] Change user agent for limitedCommerce, or pass parameter, depending on server-side implementation.
- [ ] Available-update lights up marketplace instead of assets button + inventory tab ("You have n item updates available" in Inventory seems to work ok.)
- [ ] When not limitedCommerce, bring back the economic activity notifications (in addition to the available update notifications above), and have it light up assets button and activity tab.
- [ ] Make Wallet.limitedCommerce be available in .qml, and use it directly there rather than passing it in from .js.
- [ ] Make variable/function names consistent with the new labeling.
- [ ] Clean up `FIXME` comments.
- [ ] Respond to general code review.

The following are ok for now, but could change after this work is complete:
- minor: There was a general pm/ux/tl agreement to change purchase/buy to get, and My Purchases to Inventory, and this has been done, but I might have missed things, or there might be some cases where this was a bad idea. E.g.,
   - First use Tutorial already has wording changed already, but the underlying graphic still says "marketplace" (which might not be a terrible thing).
   - Your item is marked "pending" while it is being confirmed.`: The word "it" is referring to "your item" - but nobody is going to know what it means to have "an item" be confirmed. "A purchase" being confirmed (as in the old language) makes more sense.
   - "Thank you for your order" screen still has fake header that has link to inventory. Is that link necessary/inconsistent?
- *major*: Don't show tabs row at all on the bottom of assets, so only "Inventory" can be displayed.
   - Depends crucially on wallet security tab removal, which has not been started, and so is a schedule risk.
   - No help?
   - Awkward that references and screen say "Inventory". Screen was designed to be within header, and so the label "Inventory" is not app-label (header) styled, but tab-label (further down and indented). Do we change that? Does that mean two different layouts for that screen (even ignoring tab/header).
   - Do we get rid of "Assets" header? Where does Security pic go? Do we not need it at all? What is the overal security redesign and what does that entail?
   - Maybe solution is to keep header, but conditionally change "ASSETS" to "INVENTORY" (in button, and in header, conditionalized on limitedCommerce), and then also remove the page label "Inventory" (just leave blank) when in limitedCommerce. But is "INVENTORY" button label too crowded? If we're telling the same users to go back and forth between versions (desktop to get money and spend it, Quest to use what they bought), is are the different names confusing?

**Comment by changxc** [comment]
minor: There was a general pm/ux/tl agreement to change purchase/buy to get, and My Purchases to Inventory, and this has been done, but I might have missed things, or there might be some cases where this was a bad idea. E.g.,
       

-  First use Tutorial already has wording changed already, but the underlying graphic still says "marketplace" (which might not be a terrible thing). <---I am going to live with it for now....
-  Your item is marked "pending" while it is being confirmed.`: The word "it" is referring to "your item" - but nobody is going to know what it means to have "an item" be confirmed. "A purchase" being confirmed (as in the old language) makes more sense. <--- how about 'your item is marked "pending" while the transfer is being confirmed?'
-  "Thank you for your order" screen still has fake header that has link to inventory. Is that link necessary/inconsistent? <----My proposal (a) in oculus store version, “thank you for your order" should follow with “view this item in inventory", (b) in non-oculus store version, "thank you for your order" should follow with ”view this item inventory" and "view receipt of the transaction"

**Comment by changxc** [comment]
major: Don't show tabs row at all on the bottom of assets, so only "Inventory" can be displayed.
-(a) in oculus store version, there is no tabs, the 'wallet' app is renamed to 'inventory', (b) in non-oculus store version, there are 5 tabs, the 'wallet' app is renamed to 'inventory', the 'security' tab is replaced with 'items' tab, which is basically old my purchase

-          Depends crucially on wallet security tab removal, which has not been started, and so is a schedule risk.
- noted, see[ ticket 18279](https://highfidelity.fogbugz.com/f/cases/18279/Wallet-Automatically-Log-Out-when-Exiting-Interface-overrides-PR13961-and-Keep-me-signed-in-checkbox)
-         No help?
- (a) in oculus store version, no help, (b) in non-oculus store version, 'help' tab is still there, no need to change anything
-         Awkward that references and screen say "Inventory". Screen was designed to be within header, and so the label "Inventory" is not app-label (header) styled, but tab-label (further down and indented). Do we change that? Does that mean two different layouts for that screen (even ignoring tab/header).
- I do not understand the above problem or I do not see why it is a problem. Help me to understand why it is bad?
-         Do we get rid of "Assets" header? Where does Security pic go? Do we not need it at all? What is the overal security redesign and what does that entail?
- There is not 'assets' header. Please do not mention Assets, we already have an assets browser, it could be quite confusing. In oculus store version, there is only 'inventory' (see Mukul's mockup). In non-oculus store version,  The 'wallet' app is renamed to 'inventory' app with 5 tabs (see Mukul's mockup). 
-         Maybe solution is to keep header, but conditionally change "ASSETS" to "INVENTORY" (in button, and in header, conditionalized on limitedCommerce), and then also remove the page label "Inventory" (just leave blank) when in limitedCommerce. But is "INVENTORY" button label too crowded? If we're telling the same users to go back and forth between versions (desktop to get money and spend it, Quest to use what they bought), is are the different names confusing?
- See my previous comment. Oculus store version, the user see an 'inventory' app, there is no sub-tab. In non-oculus store version, the user see an 'inventory' app with 5 tabs, one of the 5 tab is 'items', which is the same as what the oculus store version user is seeing.

**Comment by changxc** [comment]
image

**Comment by changxc** [comment]
I am attaching both Mukul's doc as per below

https://docs.google.com/document/d/1br5JlgqHFSchU9pFGRC6TzVR7htJ3mUKyttugSqn_DU/edit

https://docs.google.com/document/d/1YaFZoEWdzPv3_Qhuf6UVKzJUeqU7nXZdYiYIWH0z2IM/edit

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14511/HighFidelity-Beta-PR14261-b6344ac.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14511/HighFidelity-Beta-PR14261-b6344ac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14511/HighFidelity-Beta-Interface-PR14261-b6344ac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14511/HighFidelity-Beta-PR14261-b6344ac.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14511/HighFidelity-Beta-Interface-PR14261-b6344ac.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14529/HighFidelity-Beta-PR14261-b5a48d3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14529/HighFidelity-Beta-PR14261-b5a48d3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14529/HighFidelity-Beta-Interface-PR14261-b5a48d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14529/HighFidelity-Beta-PR14261-b5a48d3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14529/HighFidelity-Beta-Interface-PR14261-b5a48d3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14546/HighFidelity-Beta-PR14261-efcda12.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14550/HighFidelity-Beta-PR14261-a1276ba.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14546/HighFidelity-Beta-PR14261-efcda12.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14546/HighFidelity-Beta-Interface-PR14261-efcda12.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14552/HighFidelity-Beta-PR14261-34fb849.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14546/HighFidelity-Beta-PR14261-efcda12.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14546/HighFidelity-Beta-Interface-PR14261-efcda12.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14552/HighFidelity-Beta-PR14261-34fb849.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14552/HighFidelity-Beta-Interface-PR14261-34fb849.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14552/HighFidelity-Beta-PR14261-34fb849.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14552/HighFidelity-Beta-Interface-PR14261-34fb849.exe

**Comment by howard-stearns** [comment]
A couple more things (sorry):
- [ ] Certificat spins.
- [ ] Wallet.qml has some referecnes to walletInventory.isShowingMyItems, which doesn't exist any more.
- [ ] Get rid of "Inventory" link near top of Recent Activity listing. (I failed to include this on original todo list.)
- [ ] Make sure this works with People => Appear Offline. I keep getting a stack overlfow. _This might not be the code here that breaks - it could be from before. But either way..._

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14562/HighFidelity-Beta-PR14261-a1eee35.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14562/HighFidelity-Beta-PR14261-a1eee35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14562/HighFidelity-Beta-Interface-PR14261-a1eee35.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14562/HighFidelity-Beta-PR14261-a1eee35.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14562/HighFidelity-Beta-Interface-PR14261-a1eee35.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14579/HighFidelity-Beta-PR14261-6e470d5.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14581/HighFidelity-Beta-PR14261-4a56f76.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14581/HighFidelity-Beta-PR14261-4a56f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14581/HighFidelity-Beta-Interface-PR14261-4a56f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14581/HighFidelity-Beta-PR14261-4a56f76.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14581/HighFidelity-Beta-Interface-PR14261-4a56f76.exe

**Comment by rickcarr044** [comment]
Currently testing PR14261

**Comment by howard-stearns** [comment]
Rick notes that there are priced items being shown while browsing the Market while in limitedCommerce mode. (It may be that these come from pages after the first page, filled in by a data endpoint called by the main page.) In any case, we're investigating.

**Comment by howard-stearns** [comment]
There are two items noted on https://github.com/highfidelity/hifi/pull/14319 that apply here as well.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14630/HighFidelity-Beta-PR14261-2b50c40.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14667/HighFidelity-Beta-PR14261-402c23e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14667/HighFidelity-Beta-PR14261-402c23e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14667/HighFidelity-Beta-Interface-PR14261-402c23e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14667/HighFidelity-Beta-PR14261-402c23e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14667/HighFidelity-Beta-Interface-PR14261-402c23e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14675/HighFidelity-Beta-PR14261-a87142b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14675/HighFidelity-Beta-PR14261-a87142b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14675/HighFidelity-Beta-Interface-PR14261-a87142b.exe

**Comment by howard-stearns** [comment]
Another "purchase" missed: 
login-to-purchase

**Comment by howard-stearns** [comment]
Open Assets while not logged in, and press the login button. Then login. It "works", but the wall/assets app still displays the Please Log In to High Fidelity screen.

**Comment by howard-stearns** [comment]
missing the inventory tab. (I'll fix it.)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14692/HighFidelity-Beta-PR14261-8906b90.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14692/HighFidelity-Beta-PR14261-8906b90.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14692/HighFidelity-Beta-Interface-PR14261-8906b90.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14692/HighFidelity-Beta-PR14261-8906b90.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14692/HighFidelity-Beta-Interface-PR14261-8906b90.exe

**Comment by zfox23** [comment]
- Fixed log: "Unrecognized message from Checkout.qml: {"method":"purchases_updateWearables"}" when assets app opened
- Fixed: Gifting item to someone nearby doesn't work; logs show "Unrecognized message from Checkout.qml: {"method":"enable_ChooseRecipientNearbyMode"}"
- Fixed: Inventory red dot was vertically misaligned
- Fixed: Cliicking on 'view receipt in recent activity' link in Checkout confirmation, user is taken to Inventory tab
- Fixed: In help: "get it by going to BankOfHighFidelity. and meeting" - there's a huge space between "to" and "Bank"
- Fixed: Filter text persists across ASSETS app close and open in certain cases
- Fixed: Wallet tab highlight bug when switching tabs

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14725/HighFidelity-Beta-PR14261-515ff01.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14725/HighFidelity-Beta-PR14261-515ff01.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14725/HighFidelity-Beta-Interface-PR14261-515ff01.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14733/HighFidelity-Beta-PR14261-515ff01.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14738/HighFidelity-Beta-PR14261-3631e30.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14743/HighFidelity-Beta-PR14261-5b042ec.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14738/HighFidelity-Beta-PR14261-3631e30.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14738/HighFidelity-Beta-Interface-PR14261-3631e30.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14738/HighFidelity-Beta-PR14261-3631e30.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14738/HighFidelity-Beta-Interface-PR14261-3631e30.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14743/HighFidelity-Beta-PR14261-5b042ec.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14743/HighFidelity-Beta-Interface-PR14261-5b042ec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14743/HighFidelity-Beta-PR14261-5b042ec.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14743/HighFidelity-Beta-Interface-PR14261-5b042ec.exe

**Pull request merged**
