### PR TITLE
Fix a few UNIX warnings

### PR DESCRIPTION
**Pull request by Atlante45**
Fix a few OS X warnings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 01eb618c55bf0460e2631015d11c8116b7d433da available at: https://gist.github.com/86fbe330ec1d95262943<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6622-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6622.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 01eb618c55bf0460e2631015d11c8116b7d433da available at: https://gist.github.com/86fbe330ec1d95262943<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6622-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6622.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f72eb679c691ae53a399526345c1cc421efc701d available at: https://gist.github.com/86fbe330ec1d95262943<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6622-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6622.dmg

**Pull request closed without merging**
