### PR TITLE
fix up queryAACubes before sending imported entities to server

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that made some child-entities imported from a json file not show up for others

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/3500/On-relogging-many-entities-in-this-scene-will-not-load

**Comment by sethalves** [comment]
to test:
- In a large area in the welcome area, load the attached JSON to create a large detailed house made of about 500 or so entities.
- Walk around and enjoy looking in the different rooms and remembering the details. 
- Re-log and come back to same spot.  Walk around and ensure that all of the entities are still present.

**Comment by CainFoool** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9005a9e7653cba52284718e9931a1e1166137d5 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-b9005a9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-b9005a9.dmg

**Comment by CainFoool** [comment]
Testing Now.

**Comment by CainFoool** [comment]
Test Complete

Imported the Entity URL at a corner of spawn, everything worked as intended (However, the house seem to have completely disappeared after a while)

Logged out and logged back in, inside of the building which caused some positional glitches and some of the entities did not place correctly. As I know that I was inside where an Entity was supposed to be I decided to re-run the test.

Re-ran the test, however relogging outside. I wasn't inside any entities nor was anything clipping them however pieces of the road seemed to have disappeared.

Attached picture.

**FAILED**
e0ldv

**Comment by sethalves** [comment]
@CainFoool could you do this again, and when you find a missing part, slowly rotate around and see if that part ever re-appears?

The house disappearing after a while was likely due to dev-welcome's periodic auto-clean up.

**Comment by sethalves** [comment]
@CainFoool nevermind the above.  there's still something wrong.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d90843428df2579be44fd9ac305727da39eb8e92 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-d908434.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-d908434.dmg

**Comment by CainFoool** [comment]
@sethalves 

(Relaying what was said in Slack)

Furthering my experiences, when the road disappeared I went inside to see if anything else had disappeared. Rotating around one wall made it randomly appear and disappear, no other objects in the house seem to have had this issue.

Would you like me to test with the latest build?

**Comment by Nex-Pro** [comment]
@sethalves @CainFoool  never test anything requiring entities in dev-welcome  unless you can do it quickly.
Non-Admins only get a two minute lifespan for ents they create.

**Comment by CainFoool** [comment]
@Nex-Pro In this case I was able to test within the two minutes, as relogging simply took seconds. Will note to do it in the Sandbox in the future however.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ab676e627d0d8afe0ab9faebaab1639fd967b64 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-8ab676e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-8ab676e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ab676e627d0d8afe0ab9faebaab1639fd967b64 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-8ab676e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-8ab676e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8567e0550f7f2e1a155bf1b9d5937e054708290 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-b8567e0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-b8567e0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f35796259bbcbc46d815de6a1ab138af477e2c81 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-f357962.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-f357962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef556fae9b8292309bf88e5f60afe6e851d97af3 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-ef556fa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-ef556fa.dmg

**Comment by marko8904** [comment]
there are currently 2 builds in progress for this PR. One is about to finish. The other will take another 30min.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b0eeb9c2c8cc01a1e87a343cb205451fc0f383d available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-1b0eeb9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-1b0eeb9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4007133423cf3a342d11a3ef9cdb1e7c826ce533 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-4007133.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-4007133.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99dfd9ded164052b1d34339ba0fa4db08e98c4cc available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-99dfd9d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-99dfd9d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c12baa2584f101c279b5b019dd3f367451c7ae0 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-0c12baa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-0c12baa.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 77ce8a19cf6a0df3824bdd1078f6e9921a4ad92f available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-77ce8a1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-77ce8a1.dmg

**Comment by marko8904** [comment]
@seth your PR is the lucky winner of being the first to build on the new cluster. Let @murillodigital or me know if you notice anything unusual or if something's amiss.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7220fe0ad8493522cb4c9369c0c425f4ad7c8131 available at: https://gist.github.com/a9f4f1885813372078c02ef28e93b8f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-7220fe0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10476-7220fe0.dmg

**Comment by marko8904** [comment]
@sethalves Please ignore the "all checks failed" that came up now. That was a stale build from the old cluster.

**Comment by marko8904** [comment]
The build on the new cluster is in progress and will update here.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/36/HighFidelity-Beta-PR10476-7220fe0ad8493522cb4c9369c0c425f4ad7c8131.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/50/HighFidelity-Beta-PR10476-936d0e2d500b5e4b4020ebc9c4c8cfb2cf3f3d45.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/50/HighFidelity-Beta-PR10476-936d0e2d500b5e4b4020ebc9c4c8cfb2cf3f3d45.dmg

**Comment by marko8904** [comment]
bugsplat upload failed on the windows build. Trying again.

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/51/HighFidelity-Beta-PR10476-936d0e2d500b5e4b4020ebc9c4c8cfb2cf3f3d45.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/51/HighFidelity-Beta-PR10476-936d0e2d500b5e4b4020ebc9c4c8cfb2cf3f3d45.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/57/HighFidelity-Beta-PR10476-386c76545ce960c3c025fec023345c2117de268b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/57/HighFidelity-Beta-PR10476-386c76545ce960c3c025fec023345c2117de268b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/73/HighFidelity-Beta-PR10476-40c82611119b4c870d8923d4881858169151333d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/73/HighFidelity-Beta-PR10476-40c82611119b4c870d8923d4881858169151333d.dmg

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
Testing *PASSED*

Logged in and out 5 times with just one house spawned in, entities showed up correctly with no visual glitches. 

Made two more and repeated the above.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/76/HighFidelity-Beta-PR10476-a442181859485403b003a977c25511f40b9724fb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/76/HighFidelity-Beta-PR10476-a442181859485403b003a977c25511f40b9724fb.dmg

**Pull request merged**
