### PR TITLE
Apostrophe key resets animation state.

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71b7f9ee38a4d18fdbfe5d5ad9d5e7c5490718e3 available at: https://gist.github.com/410ebd62c5a2a98ab52c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.dmg

**Comment by howard-stearns** [comment]
It turns out this works best when the controllers are cradled (on-hook). We really want this to work just as well when off-hook, so I'll work on that. (I'll add it here if this hasn't been merged yet, or otherwise make a separate PR.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 401f83135a554ca96d2534336f65bb1ac84c0507 available at: https://gist.github.com/410ebd62c5a2a98ab52c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.dmg

**Comment by AndrewMeadows** [comment]
This PR reveals some bugs in the IK algorithm.  I'm hunting them now.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 401f83135a554ca96d2534336f65bb1ac84c0507 available at: https://gist.github.com/410ebd62c5a2a98ab52c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 401f83135a554ca96d2534336f65bb1ac84c0507 available at: https://gist.github.com/410ebd62c5a2a98ab52c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 266c69fc70712c304ed712f6eb932959e45940a6 available at: https://gist.github.com/410ebd62c5a2a98ab52c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5870.dmg

**Comment by howard-stearns** [comment]
Should be good to go now. The combination of IK cleanups and the old-school Rig::inverseKinematics during reset, is what allows us to properly reset while hydra is off hook.

**Comment by AndrewMeadows** [comment]
It works.

**Pull request merged**
