### PR TITLE
Dissectors: Limit message number & position values

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
https://highfidelity.atlassian.net/browse/BUGZ-579

With arbitrary captured packets the dissectors were locking up due to lua array-use with random 32-bit values. One packet was enough to break it.
I'm open to cleaner fixes, though I think we rarely need to analyze multi-part messages.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19795/HighFidelity-Beta-PR15687-ecbce82.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19795/HighFidelity-Quest-Beta-PR15687-ecbce82.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19795/HighFidelity-Beta-PR15687-ecbce82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19795/HighFidelity-Beta-Interface-PR15687-ecbce82.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19795/HighFidelity-Beta-PR15687-ecbce82.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19795/HighFidelity-Beta-Interface-PR15687-ecbce82.exe

**Comment by howard-stearns** [comment]
What would you think of adding this as well? (It's not complete, but it covers some of the dissection errors I've been getting while sharking the disconnects.)

local unsourced_packet_types = {
  ["DomainList"] = true,
  ["DomainConnectRequest"] = true,
  ["ICEPing"] = true,
  ["ICEPingReply"] = true,
  ["DomainServerConnectionToken"] = true,
  ["DomainSettingsRequest"] = true,
  ["ICEServerHeartbeatACK"] = true
}

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19801/HighFidelity-Beta-PR15687-a5c2ce4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19801/HighFidelity-Quest-Beta-PR15687-a5c2ce4.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19801/HighFidelity-Beta-PR15687-a5c2ce4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19801/HighFidelity-Beta-Interface-PR15687-a5c2ce4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19801/HighFidelity-Beta-PR15687-a5c2ce4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19801/HighFidelity-Beta-Interface-PR15687-a5c2ce4.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19818/HighFidelity-Beta-PR15687-d2e9abd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19818/HighFidelity-Beta-Interface-PR15687-d2e9abd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19818/HighFidelity-Beta-PR15687-d2e9abd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19818/HighFidelity-Quest-Beta-PR15687-d2e9abd.apk)

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19821/HighFidelity-Beta-PR15687-d2e9abd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19821/HighFidelity-Quest-Beta-PR15687-d2e9abd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19821/HighFidelity-Beta-PR15687-d2e9abd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19821/HighFidelity-Beta-Interface-PR15687-d2e9abd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19821/HighFidelity-Beta-PR15687-d2e9abd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19821/HighFidelity-Beta-Interface-PR15687-d2e9abd.exe

**Pull request merged**
