### PR TITLE
Revert the sRGB pixel format by default

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b18c0d5325feb2e24fd3a200344e4f79736795b5 available at: https://gist.github.com/1a7d7c973347d90f78d2c27562c143ae<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8546-b18c0d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8546-b18c0d5.dmg

**Comment by cozza13** [comment]
@samcake what is the test plan?

**Comment by samcake** [comment]
Test plan is:
Smoke test verify that the colors come out without any difference compared to master
there should be no difference overall in quality or performance

**Comment by nbq** [comment]
Testing this now

**Pull request merged**
