### PR TITLE
You can now properly grab and move the tablet in third person

### PR DESCRIPTION
**Pull request by druiz17**
You can know properly grab and move the tablet in third person

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Be in HMD mode and third person view
- bring up the tablet
- grab and move the tablet.
- the tablet should behave like in first person view

**Comment by Nex-Pro** [comment]
Testing this when built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1802/HighFidelity-Beta-PR11010-3805228b70635e4c18332fd1f941bffb8d6539a5.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1805/HighFidelity-Beta-PR11010-3805228b70635e4c18332fd1f941bffb8d6539a5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1805/HighFidelity-Beta-PR11010-3805228b70635e4c18332fd1f941bffb8d6539a5.dmg

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
### Pass.

Seems ok. Has revealed an issue that exists in master. I'll check fogbugz

**Pull request merged**
