### PR TITLE
Add #include of Forward.h to AudioMixer.h

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
This makes the compile by Qt MOC less dependent on order of processing.
See Manuscript case 12527.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by birarda** [comment]
Since this doesn't change any behaviour and simply fixes a compile error, CR is sufficient for merge.

**Comment by birarda** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7426/app_12451_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7426/HighFidelity-Beta-PR12451-a0a12258bf44cdc6e01da1e13cff504431936ac5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7426/HighFidelity-Beta-PR12451-a0a12258bf44cdc6e01da1e13cff504431936ac5.exe

**Pull request merged**
