### PR TITLE
DOC-124: Tidy JSDoc from some recent API changes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Entities' "unlit" properties
- Link to Entities "TextEffect" type
- Audio API's gain properties etc.
- Key light property's shadow values
- MyAvatar API's animation debug graphics methods

Case: https://highfidelity.atlassian.net/browse/DOC-124

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20470/HighFidelity-Beta-PR15959-8c92f97.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20470/HighFidelity-Beta-Interface-PR15959-8c92f97.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20470/HighFidelity-Beta-PR15959-8c92f97.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20470/HighFidelity-Quest-Beta-PR15959-8c92f97.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20474/HighFidelity-Beta-PR15959-8c92f97.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20474/HighFidelity-Quest-Beta-PR15959-8c92f97.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20474/HighFidelity-Beta-PR15959-8c92f97.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20474/HighFidelity-Beta-Interface-PR15959-8c92f97.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20474/HighFidelity-Beta-PR15959-8c92f97.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20474/HighFidelity-Beta-Interface-PR15959-8c92f97.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20733/HighFidelity-Beta-PR15959-789f9c7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20733/HighFidelity-Beta-Interface-PR15959-789f9c7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20733/HighFidelity-Beta-PR15959-789f9c7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20733/HighFidelity-Beta-Interface-PR15959-789f9c7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20733/HighFidelity-Beta-PR15959-789f9c7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20733/HighFidelity-Quest-Beta-PR15959-789f9c7.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20768/HighFidelity-Beta-PR15959-2939610.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20768/HighFidelity-Beta-Interface-PR15959-2939610.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20768/HighFidelity-Beta-PR15959-2939610.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20768/HighFidelity-Quest-Beta-PR15959-2939610.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20768/HighFidelity-Beta-PR15959-2939610.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20768/HighFidelity-Beta-Interface-PR15959-2939610.exe

**Pull request merged**
