### PR TITLE
Leopoly_Phase1_005_Buffer-View

### PR DESCRIPTION
**Pull request by humbletim**
... PR staging; description and test plan pending

Limited Scripting access to the existing native BufferView abstraction (eg: reading and writing glm::vec3 color, position, normal Vertex Attributes for a Mesh).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5780/app_12040_PR.apk

**Comment by MiladNazeri** [comment]
Overall Leopoly PR roadmap:
https://docs.google.com/document/d/1GJC6qYHICYccIqdmaGgtt30Nj12Q3FtFmejns7biyks/edit
This is 5/9

Labeling Do not merge until code is reviewed for #'s 1-8

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5941/app_12040_PR.apk

**Comment by samcake** [comment]
Hi @humbletim 
I wouldn't be able to accept this PR like that (in the gpu lib)
I understand that this work is part of a bigger project.
I would like to meet with you and go through what you want to achieve so i can answer you with more context :)
Sorry,
Cheers

**Pull request closed without merging**
