### PR TITLE
Align body to head on reset

### PR DESCRIPTION
**Pull request by howard-stearns**
Needs HMD testing...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1fc305ca6b6e2426754c62cc39f3a95e4be72a7c available at: https://gist.github.com/3dbb025d16f5f5ecf4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.dmg

**Comment by cozza13** [comment]
I tested this. It seemed like my avatar was recentered horizontally but my view point was at the base of my neck. Using Albert. https://hifi-public.s3.amazonaws.com/marketplace/contents/1e57c395-612e-4acd-9561-e79dbda0bc49/faafb83c63a3e5e265884d270fc29f8b.fst?1443487177

**Comment by howard-stearns** [comment]
Sorry, yes. I failed to report that my testing was not successful.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 652376db8a529578da77b845dbc5ba2821b085bf available at: https://gist.github.com/3dbb025d16f5f5ecf4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 700835a6d1462ef8ab3c03ec9a5b5e81977f78c6 available at: https://gist.github.com/3dbb025d16f5f5ecf4de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6012.dmg

**Comment by howard-stearns** [comment]
This is working pretty well for me -- much better than before. However, I do still get some very weird resets:
1. My oculus sometimes flakes out randomly.
2. There can be interactions with the lean-step code, which itself is subject to be altered/influenced by either stuff (https://github.com/highfidelity/hifi/pull/6011, https://github.com/highfidelity/hifi/pull/6031). One thing I've done for testing to eliminate lean from the mix is to set the preferences->avatar animation json to http://howard-stearns.github.io/models/avatars/animation-no-lean.json. Alas, if there are bad interactions with leaning that we do need to worry about now, changing the animation graph in this way will hide such issues. Still, I think it's a step forward.
3. There is an error of as much as 10 cm in the way we compute where the body should be. https://app.asana.com/0/32622044445063/56905694010643
4. Currently this code ignores the y value in avatar positioning, leaving the avatar at the same height when resetting. Eventually, we'll want to track this for figuring out whether to change whether the avatar is sitting or standing. (But I feel that's out of scope for now.)

**Pull request merged**
