### PR TITLE
Search main window by checking object name

### PR DESCRIPTION
**Pull request by vladest**
At some systems interface gets crash on startup due to invalid window choose as MainWindow

Test plan:
- Start inteface
- no crash on startup inside KeyboardFocusHack() class

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7503/app_12498_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7503/HighFidelity-Beta-PR12498-77ef0e05a1c3662cbd431b50b6b26bb22483a81f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7503/HighFidelity-Beta-PR12498-77ef0e05a1c3662cbd431b50b6b26bb22483a81f.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tested on all machines.

**Comment by tapalisa** [comment]
Someone using this PR has not set their tester flag. Please double check your tester flag.

**Pull request merged**
