### PR TITLE
support for fbx2016 format

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
**Test plan:**
- Regular smoke test.
- Verify that OLD FBX files loads. Make sure models load from regular domains. This code makes a small change to how we parse FBX files, I you are seeing any FBX files, then this "backward compatibility" test passes.
- Verify that NEW (2016) FBX files loads. Import a model with this [URL](https://s3-us-west-1.amazonaws.com/hifi-content/jazmin/dev/fbx_version_tests/scaffoldtest_binary_2016.fbx), it should look like the scaffold. In production it won't render at all, in this built it will.

Note: This is a client only change.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7397b884e7e33db0b4aaf7ae01844e5d4d3684a7 available at: https://gist.github.com/f1a7fcd6064b22de9aaba57fba248f47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8545-7397b88.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8545-7397b88.dmg

**Comment by Nex-Pro** [comment]
testing

**Comment by pippilina** [comment]
Caitlyn here!  

To our Maya users, please be sure to test aggressively with the StingrayPBS material

**Comment by ZappoMan** [comment]
@pippilina - I have not done anything to change how materials are parsed... hopefully that didn't actually change. From all I know the only change in the file was to support "larger than 2GB files" which they did by bumping a couple of values from 32bits to 64bits... that's all I added support for.

**Comment by samcake** [comment]
Brilliant!

**Comment by Nex-Pro** [comment]
@ZappoMan we are discussing an issue re this in slack. @OmegaHeron and I both see the same problem.

**Comment by Nex-Pro** [comment]
@ZappoMan  I fixed the model to scale  correctly and chris re-exported a 2016 version they both scale and display fine now

**Pull request merged**
