### PR TITLE
use DynamicCharacterController

### PR DESCRIPTION
**Pull request by AndrewMeadows**
The kinematic CharacterController suffered from poor performance when moving inside objects that used a complex btCompoundShape (i.e. the interior of a house that was one model).  However, dynamic objects can collide inside these shapes with very little load on the physics simulation, so we're moving to a dynamic character controller.

This DynamicCharacterController recovers most of the features of the old CharacterController.  A few things might not work very well (theoretially -- I haven't tested):

(1) might be impossible to walk up steps
(2) might be hard to walk up steep slopes
(3) might be impossible to stand on steep slopes or on the edges of objects
(4) dynamic objects won't settle if avatar is near or touching them
(5) avatars too easily movable by dynamic objects

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ccc25e380f4ab84006a16fc7dacb4f23bc2a6a3 available at: https://gist.github.com/14dfd0a63c619e43a0dd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4611.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4611.dmg

**Comment by jherico** [comment]
That's quite the sales pitch.

**Comment by ZappoMan** [comment]
Andrew - the "A" in ABC.

**Comment by PhilipRosedale** [comment]
works great for me so far in test on OSX

**Comment by PhilipRosedale** [comment]
Works for 30 degree angles (walking up) and 10cm steps.

**Comment by PhilipRosedale** [comment]
Works for me on Windows 8.1 (On my surface 3 to boot!).

**Pull request merged**
