### PR TITLE
move firstRun.set() to correct place

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
1) @Nex-Pro and @kevinmthomas-carpool - should test to make sure this PR doesn't bork their frame rate.
2) Everyone else also check to make sure FPS is still good to go...
3) Then we need to retest these First time user experience features:

---- **FUE tests** ----

1) do a CLEAN install...

2) on first run....
2a) verify that the "help"/"welcome" screen doesn't pop up
2b) verify that the "login" screen doesn't pop up
2c) IF you have sandbox running, you should be sent to your sandbox. Check the logs, you should see the following messages:
```
[05/10 10:43:59] [DEBUG] First run and no URL passed... attempting to Go Home...
[05/10 10:43:59] [DEBUG] Home sandbox is running, going to "hifi://localhost"
```
2d) IF you do not have sandbox running, on your first run, you should be sent to playa/entry. Check the logs, you should see the following messages:
```
[05/10 10:43:59] [DEBUG] First run and no URL passed... attempting to Go Home...
[05/10 10:43:59] [DEBUG] Home sandbox was not running, going to "hifi://entry" instead.
```

3) go to a domain that requires login, and verify that it does pop up the login screen

4) on second run, you should go back to wherever you last were... See something like this in your logs...
```
[05/10 10:43:59] [DEBUG] Not first run... going to previous location
[05/10 10:43:59] [DEBUG] Trying to go to URL "hifi://localhost/1101.79,460.271,-78.4844/0,-0.496747,0,0.867895"
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 65aae427145aa89175e490eb4049bf59d72ec292 available at: https://gist.github.com/dcba0c7e6761e35a472a4b0e039b3c01<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7896.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7896.dmg

**Comment by cozza13** [comment]
Tested all steps above. QA pass

**Comment by kevinmthomas-carpool** [comment]
SUCCESS 
capture

**Comment by Nex-Pro** [comment]
Render rates  60 60 60  at playa and cellscience. 
#### SUCCESS

**Pull request merged**
