### PR TITLE
Mini tablet in palm - C

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
#### Test Plan

A) HMD mode.

1) Mini tablet shows in hand only when both the hand is oriented toward the camera and the camera is oriented toward the hand.
a) In first person view.
b) In third person view.

2) With the mini tablet showing on a hand, grab it with the other hand.
- It should grow to tablet size and be replaced by the tablet proper.
- It should grow and move along the direction of the displaying hand's fingers such that it is held in the lower left if grabbed with the left hand, or lower right if grabbed with the right hand.

3) With the mini tablet showing on a hand, squeeze that hand's trigger.
- The mini tablet should be grabbed by that hand and it should grow to tablet size and be replaced by the tablet proper.
- It should grow and move along the direction of the displaying hand's fingers such that it is held in the lower left if grabbed with the left hand, or lower right if grabbed with the right hand.

4) With the mini tablet showing on a hand, click the "..." button on it.
- The mini tablet should grow and move along the direction of the displaying hand's fingers.

5) The mini tablet should display and grow the same position and size relative to your avatar at different avatar scales.

6) The mini tablet shouldn't show, and if already shown it should hide, if the tablet is opened by other means (e.g., pressing "show tablet" button on controller).

7) The mini tablet's buttons should reflect and keep up to date with the current states of mic muted and the bubble; they should look the same as on the tablet proper.

8) The mini tablet's buttons should highlight and take the relevant actions when clicked:
a) When using laser.
b) When using styluses (Settings > General > Prefer Stylus Over Laser).

9) Sounds should be played when the buttons are:
a) Highlighted.
b) Clicked.

10) The tablet and mini tablet should both have a smaller maximum grab distance than master (i.e., hand needs to be nearer them in order to grab them).

11) The default size of the tablet in HMD mode should be 60% (instead of the previous 70%).


B) Desktop mode.

1) The mini tablet does not show in the hand when the hand is oriented toward the camera.
a) In first person view.
b) In third person view.

2) The mini tablet is hidden when you switch to desktop mode from HMD mode with the mini tablet visible.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12233/HighFidelity-Beta-PR13848-4b12e18.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12233/HighFidelity-Beta-Interface-PR13848-4b12e18.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12233/HighFidelity-Beta-PR13848-4b12e18.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12233/HighFidelity-Beta-Interface-PR13848-4b12e18.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12329/HighFidelity-Beta-PR13848-b6e4a22.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12329/HighFidelity-Beta-PR13848-b6e4a22.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12329/HighFidelity-Beta-Interface-PR13848-b6e4a22.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12329/HighFidelity-Beta-PR13848-b6e4a22.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12329/HighFidelity-Beta-Interface-PR13848-b6e4a22.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12417/HighFidelity-Beta-PR13848-b6e4a22.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12417/HighFidelity-Beta-PR13848-b6e4a22.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12417/HighFidelity-Beta-Interface-PR13848-b6e4a22.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12417/HighFidelity-Beta-PR13848-b6e4a22.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12417/HighFidelity-Beta-Interface-PR13848-b6e4a22.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12452/HighFidelity-Beta-PR13848-49f5d5f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12452/HighFidelity-Beta-PR13848-49f5d5f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12452/HighFidelity-Beta-Interface-PR13848-49f5d5f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12452/HighFidelity-Beta-PR13848-49f5d5f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12452/HighFidelity-Beta-Interface-PR13848-49f5d5f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12459/HighFidelity-Beta-PR13848-15fcafa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12459/HighFidelity-Beta-Interface-PR13848-15fcafa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12459/HighFidelity-Beta-PR13848-15fcafa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12459/HighFidelity-Beta-Interface-PR13848-15fcafa.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12499/HighFidelity-Beta-PR13848-15fcafa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12499/HighFidelity-Beta-Interface-PR13848-15fcafa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12499/HighFidelity-Beta-PR13848-15fcafa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12499/HighFidelity-Beta-Interface-PR13848-15fcafa.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12506/HighFidelity-Beta-PR13848-a5c3450.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12508/HighFidelity-Beta-PR13848-ec20fb7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12508/HighFidelity-Beta-PR13848-ec20fb7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12508/HighFidelity-Beta-Interface-PR13848-ec20fb7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12508/HighFidelity-Beta-PR13848-ec20fb7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12508/HighFidelity-Beta-Interface-PR13848-ec20fb7.exe

**Pull request closed without merging**
