### PR TITLE
Reduce entity fade-in time

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
This PR reduces the fade-in time for when entities are created or rezzed, from 1.0 to 0.5s.
This so that creating entities feels more immediate and not so laggy (in particular, when using the VR edit app).

Testing:
Compare the rez fade-in times of a recent dev build with this PR. The 
- Run edit.js and position the dialog window to one side so that you can see entities when they are created.
- Create a cube, say, and note how long it takes to appear and fade in.
- The PR build should take about half the time to fade in compared to the dev build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3190/HighFidelity-Beta-PR11333-6ba6c6ee35b4001bbbd7401b8d0d4ef81b61f14d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3190/HighFidelity-Beta-PR11333-6ba6c6ee35b4001bbbd7401b8d0d4ef81b61f14d.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Run edit.js and position the dialog window to one side so that you can see entities when they are created. | Pass
Create a cube, say, and note how long it takes to appear and fade in. | Pass
The PR build should take about half the time to fade in compared to the dev build. | Pass

All good.

**Comment by AndrewMeadows** [comment]
The code diff for this is trivial and correct, but is a UX change.  I understand that @tapalisa requested it.  Meanwhile the render pipeline has a new and fancy `Transition` system that will eventually be applied to entities but is not yet hooked up: when it is this code could probably be removed and we'll have to tune the fade-in effect.

**Pull request merged**
