### PR TITLE
Fix for unused avatar transit warnings on mac and linux

### PR DESCRIPTION
**Pull request by hyperlogic**
This was introduced by PR #16403

https://github.com/highfidelity/hifi/pull/16403

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22136/HighFidelity-Beta-PR16407-8cf58f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22136/HighFidelity-Beta-Interface-PR16407-8cf58f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22136/HighFidelity-Beta-PR16407-8cf58f2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22136/HighFidelity-Beta-Interface-PR16407-8cf58f2.exe

**Comment by hyperlogic** [comment]
random ubuntu electron packager failure.  lets try this again.

build this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22138/HighFidelity-Beta-PR16407-8cf58f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22138/HighFidelity-Beta-Interface-PR16407-8cf58f2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22138/HighFidelity-Beta-PR16407-8cf58f2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22138/HighFidelity-Quest-Beta-PR16407-8cf58f2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22138/HighFidelity-Beta-PR16407-8cf58f2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22138/HighFidelity-Beta-Interface-PR16407-8cf58f2.exe

**Pull request merged**
