### PR TITLE
Avoid crashing on missed pipelines

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
See: https://app.asana.com/0/74051501495175/118038028990841.

This does not fix the problem of us not supporting the specific texture. The test case was marked as being a skinned lightmap. It only stops us from crashing. I am opening a separate issue about the textures.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f20e583014e4152f30bc1f4c9f19f6ce234a5b8 available at: https://gist.github.com/67553103839823dcb30a6c2df7c764d5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7779.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7779.dmg

**Comment by kevinmthomas-carpool** [comment]
I cant get the Avatar to load successfully.  Is it perhaps missing from the directory? [04/28 13:38:27] [DEBUG] Server unavailable for QUrl(http://metaversecafes.com/images/version_d_v7_CLOTHED.fst) - retrying asset load - attempt 1  of  8

**Comment by zzmp** [comment]
It is loading fine for me :/. You can repro with an avatar that uses a skinned lightmapped texture.

**Comment by kevinmthomas-carpool** [comment]
[04/28 14:55:59] [DEBUG] Timed out loading QUrl("http://metaversecafes.com/images/version_d_v7_CLOTHED.fst") received 0 total 0
[04/28 14:55:59] [DEBUG] Server unavailable for QUrl(http://metaversecafes.com/images/version_d_v7_CLOTHED.fst) - may retry in 16000 ms if resource is still needed

@zzmp do you have a link to another avatar that meet this criteria for me please?

**Comment by kevinmthomas-carpool** [comment]
Attempted to test locally with the avatar provided from @zzmp however not loading.

[04/28 15:52:32] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 2 elapsedMovingAverage: 3 maxElapsed: 537757 maxElapsedAverage: 945 samples: 2213681
[04/28 15:52:36] [DEBUG] Downloading avatar file at  "c:%5CUsers%5Ckevin%5CDesktop%5Cavatars%5Cversion_d_v7_CLOTHED.fst"
[04/28 15:52:36] [DEBUG] Changing skeleton model for avatar to "c:%5CUsers%5Ckevin%5CDesktop%5Cavatars%5Cversion_d_v7_CLOTHED.fst"
[04/28 15:52:36] [DEBUG] Starting request for: c:%5CUsers%5Ckevin%5CDesktop%5Cavatars%5Cversion_d_v7_CLOTHED.fst
[04/28 15:52:36] [DEBUG] Logging activity "changed_model"
[04/28 15:52:36] [DEBUG] Request finished for c:%5CUsers%5Ckevin%5CDesktop%5Cavatars%5Cversion_d_v7_CLOTHED.fst
[04/28 15:52:36] [DEBUG] Starting request for: c:version_d_v7_CLOTHED/version_d_v7_CLOTHED.fbx
[04/28 15:52:36] [DEBUG] Error loading  QUrl("c:version_d_v7_CLOTHED/version_d_v7_CLOTHED.fbx")
[04/28 15:52:36] [DEBUG] Failed to load: c:version_d_v7_CLOTHED/version_d_v7_CLOTHED.fbx
[04/28 15:52:36] [DEBUG] Failed to load: c:%5CUsers%5Ckevin%5CDesktop%5Cavatars%5Cversion_d_v7_CLOTHED.fst
[04/28 15:52:37] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 6 elapsedMovingAverage: 3 maxElapsed: 537757 maxElapsedAverage: 945 samples: 2701110
[04/28 15:52:37] [DEBUG] Total allocation  "227.85 MB"

**Comment by kevinmthomas-carpool** [comment]
@zzmp thank you for helping with the path that was my error.

Successfully loaded the avatar and the behavior was quite unexpected as eyes were popping out and physics did not behave normally as shown below:

**Comment by kevinmthomas-carpool** [comment]
[hifi-log.txt](https://github.com/highfidelity/hifi/files/241363/hifi-log.txt)

**Comment by zzmp** [comment]
I deal with the log flood in #7781.

**Comment by hyperlogic** [comment]
As far as the face goes, this is an unfinished model.  The vertex weighting on the face is not good, many bones other than the head influence it, so it doesn't properly follow the head as it animates.  This is a bug with the content not the animation system, loading up this avatar fbx in Maya shows the same results.

However, another issue with this model is that the pants are missing.  Perhaps this is the mesh that is causing the issue with the rendering pipelines?

**Comment by zzmp** [comment]
@hyperlogic the pants are missing because the pipeline is not supported. This PR just prevents the crash from unsupported pipelines, but doesn't add the support. I added a separate issue (https://app.asana.com/0/26225263936266/118038028990848).

**Comment by kevinmthomas-carpool** [comment]
@zzmp confirmed no crash on this build.

**Pull request merged**
