### PR TITLE
don't send a login-denied packet when we're still waiting for user's public key

### PR DESCRIPTION
**Pull request by sethalves**
- don't display spurious "insufficient data" message when logging in

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- ensure that you're able to log into your domain-server
- restart your domain-server
- connect to the domain-server
- make sure you can still connect and make sure the message about "insufficient data" doesn't appear in the upper right corner of the interface window

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1361/don-t-display-connection-refused-insufficient-data-to-someone-logging-in

**Comment by hifi-gustavo** [comment]
Build console output for commit: ac4ecc9907299e4639b9aee651e3400088535198 available at: https://gist.github.com/a864806b36837049ca4991b80caac7a7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8480-ac4ecc9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8480-ac4ecc9.dmg

**Comment by hevyw8** [comment]
# QA Test

### Criteria:
- use the domain-server from this PR - _**pass**_
- ensure that you're able to log into your domain-server -  _**pass**_
- restart your domain-server -  _**pass**_ 
- connect to the domain-server -  _**pass**_
- make sure you can still connect and make sure the message about "insufficient data" doesn't appear in the upper right corner of the interface window -  _**pass**_

### Comments:
 I restarted the server about 10x. logged in/logged out about 10x and never saw the "insufficient data" message. A couple of times I did see "Connection Refused: Error decrypting username signature." When logging back in ([screencap](https://www.dropbox.com/s/rro1f6sqxhoiqrc/Screenshot%20%2861%29.png?dl=0)). Left domain and reconnected around 3x.

I don't have access to fogbugz. Let me know if I there's pertinent info I missed from there. Happy to run through again.

### Log dump:
[domain-server](https://www.dropbox.com/sh/pappd3ip8p4hwt6/AABKZMSTsYOgN61nxph4XfIba?dl=0)
[interface](https://www.dropbox.com/sh/xrsk1nqhv8229ug/AABMNQJfzbeq3dZnDhjHOsJaa?dl=0)

### Test system:
system: win10-64
gpu: nvidia gtx1060
cpu: i5-6500 @ 3.2
mem: 32gb

**Pull request merged**
