### PR TITLE
Beta Release 40 - Includes up to Developer Release 6565

### PR DESCRIPTION
**Pull request by cozza13**
Beta Release 40 - Includes up to Developer Release 6565
 - Avatar can walk up steps 
 - Update WASAPI audio plugin for Qt5.6.2 
 - Fix lookAt eye snapping 
 - Minor handshake improvements
 - Fix OBJ model load hang 
 - Use new images in api/v1/users response json 
 - Cleanup Audio background threads on shutdown 
 - Moved the puck configuration to actions into the vive controller plugin 
 - Fix crackle in local audio
 - Enable the PAL to update data about a single connection  
 - Fix avatar mouth movement when driven by audio loudness 
 - Fix: When you are in HMD and you go to file menu quit, it crashes and you have no menus when you come back
 - HMD now routes through the vive input plugin. 
 - Fix unreachable eye blink code 
 - Fix randFloat error in ac audio searcher 
 - Hand controller lasers work better in thirdPerson camera mode. 
 - Fix possible corruption of ktx cache files 
 - Fixing crash in texture transfer logic
 - Add launch.tester to user_actions 
 - Minor handshake script update
 - Fix issue when loading recording file into the input recorder 
 - Audience applause meter 
 - Avoid floating point error when generating fake mouth shapes 
 - Modified StretchTool to allow for movement in 3D 
 - Fix tablet showing up for a short period of time on launch 
 - Fix for multiple settings dialogs 
 - Fix avatar recording playback mouth not moving 
 - Audio source sync 
 - Added the ability to choose puck configuration from the general settings 
 - Fix the PAL not showing user info for user who opened PAL 
 - Implement a script to hand-raise while in desktop mode 
 - Lock in Overlays::findRayIntersectionInternal 
 - Desktop users of different height can shake hands 
 - Fixed pucks sorting issue and added debug 
 - Animate scroll of partially visible cards 
 - Avoid crash in glTextureSubImage2D
 - Use baked default skybox 
 - Add an internal tool for domain/model/skybox KTX texture baking 
 - Implemented chat interface script and tablet web page
 - Don't send avatars to previous lookup on server restart 
 - Fix the Twitter @mention reference 
 - Fixed input recorder crash 
 - Misc action/constraint changes 
 - Added floating lantern box that spawns floating lanterns 
 - More stable IK when hips, feet and chest are controlled via external input 
 - Better handing when the pucks lose tracking and openvr still send you a "valid" data 
 - Add the ability to duplicate an object with hand controller 
 - Fixing potential crashes when loading invalid KTX cached textures 
 - Market crash fix 
 - Fix crash in sit script 
 - cleanup Head::simulate() code 
 - Fix the default skybox texture 
 - Snapshots: Fix case when user story would be incorrectly deleted 
 - Change Puck Calibration Time from 2 sec to 1 sec 
 - Remove unnecessary assert in Model.cpp 
 - Clean up children of deleted avatar-entity 
 - Fix the Face Camera checkbox on the text entity properties tab. 
 - TriangleSet optimizations - ~80% improvement in Ray picking against models 
 - Add domain to record script user activity logging 
 - Launch the Sandbox as early as possible 
 - Fix recording playback not clearing attachments and nametags 
 - Fix erroneous "did not start playing recording" messages 
 - Set max packet per second on the agent 
 - Send smoothed orientation from a local client when a snap-turn is done across the network so all remote agents don't see the snap. 
 - Add function findEntitiesByType 
 - Fix progressive loading of KTX cubemaps 
 - Cleanup Actions and Constraints part-1 
 - Improve robustness of display name focus in PAL 
 - Fix suppress frequest constraint log spam 
 - Remove extraneous calls to sendIdentityPacket() 
 **- Enable Map/List storage in the settings** https://github.com/highfidelity/hifi/pull/10490
 - Add protections when accessing the mip bytes of a texture when provided from a KtxStorage 
 - Switch from timestamp to sequence id for avatar identity 
 - Fix domain settings not getting cleared on re-assignment 
 - Close audio device when switching outputs 
 - Fix ktx image size in progrssively loaded cubemaps 
 - Prevent another GIF from being captured while one is processing 
 - Ensure snapshots without story_ids get uploaded

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/58/HighFidelity-Beta-PR10514-5e8f1201389f341891741fcd736d81d6e4dbdecd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/58/HighFidelity-Beta-PR10514-5e8f1201389f341891741fcd736d81d6e4dbdecd.dmg

**Comment by OmegaHeron** [comment]
This is a QA Fail for me due to assignment-client (avatar mixer) throwing log errors once per second for as long as AC is running.

`[05/19 18:18:51] [DEBUG] [hifi.avatars] [10872] [avatar-mixer] Ignoring older identity packet for avatar QUuid("{00000000-0000-0000-0000-000000000000}") _identitySequenceId ( 4 ) is greater than 2`

Reproduction case:
Install Sandbox/Interface with clean install.
Launch Sandbox and allow to download content set.
Once stack is running view logs by your choice of viewing method

Note that removing audio injector script will stop log flood.

Also - you might want to look for case of first run on a clean install spamming absolutely huge amounts of failure to punch through messages and others that do not occur on Sandbox second (and beyond) runs.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/67/HighFidelity-Beta-PR10514-53a963726d2c1d76341ab3707ce73d565363d6d1.exe

**Comment by howard-stearns** [comment]
@OmegaHeron - 

1. What are the next few "ignoring older identity packet" messages. E.g., are they all 4 is greater than 2, or is the next 5 is greater than 2, or 4 is greater than 3, or what?

2. What is the "failure to punch through" message?  It sound like there might be an issue with your specific network that we're not dealing with well.

**Comment by zfox23** [comment]
@howard-stearns:

(1):
image

This is caused by the fact that scripted agents never increment their `_identitySequenceId`s. I am testing a fix for this right now.

(2): @birarda is, as far as I know, actively investigating this precise issue.

**Comment by OmegaHeron** [comment]
So I'll not bother collecting tons of additional data and typing.  Will test again, as time permits, once a fix is in place.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/67/HighFidelity-Beta-PR10514-53a963726d2c1d76341ab3707ce73d565363d6d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/72/HighFidelity-Beta-PR10514-5cb25b1ef1692c5daffc647efd86e0bf9a2a668e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/72/HighFidelity-Beta-PR10514-5cb25b1ef1692c5daffc647efd86e0bf9a2a668e.dmg

**Comment by YuppyPlays** [comment]
Have done some testing on the sheet given, may finish off some more by the end of the night.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/80/HighFidelity-Beta-PR10514-2928507e4898cc863d701398598895d360f9f6ba.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/80/HighFidelity-Beta-PR10514-2928507e4898cc863d701398598895d360f9f6ba.dmg

**Comment by OmegaHeron** [comment]
@birarda - Are you making any progress with case of Sandbox first run (from totally clean install) and Entity Script Server going nuts with example log listing below?  It **seems** that it's a first run issue only as any number of 2 ... x runs does not give error -- if one removes all config for PR in appData/roaming and appData/local it, for 1 run, exhibits precisely same behavior.

[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] LimitedNodeList::sendPacket called without active socket for node "Asset Server" (A) {e4fb1c45-be61-4157-b975-1f886f86147c} 173.170.6.26:63823 / 192.168.0.2:63823 - not sending
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] LimitedNodeList::sendPacket called without active socket for node "Entity Server" (o) {5cfcb877-6b96-44ed-96cb-10ea482b7de9} 173.170.6.26:63826 / 192.168.0.2:63826 - not sending
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] LimitedNodeList::sendPacket called without active socket for node "Audio Mixer" (M) {f0faeb5b-abec-4247-a835-7816563ac47f} 173.170.6.26:64867 / 192.168.0.2:64867 - not sending
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] LimitedNodeList::sendPacket called without active socket for node "Avatar Mixer" (W) {789b120c-c809-4808-a2b7-c9018d571ced} 173.170.6.26:64868 / 192.168.0.2:64868 - not sending
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] No response to UDP hole punch pings for node QUuid("{789b120c-c809-4808-a2b7-c9018d571ced}") in last second.
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] No response to UDP hole punch pings for node QUuid("{f0faeb5b-abec-4247-a835-7816563ac47f}") in last second.
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] No response to UDP hole punch pings for node QUuid("{5cfcb877-6b96-44ed-96cb-10ea482b7de9}") in last second.
[05/21 13:53:51] [DEBUG] [hifi.networking] [12108] [entity-script-server] No response to UDP hole punch pings for node QUuid("{e4fb1c45-be61-4157-b975-1f886f86147c}") in last second.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAIL
**Additional Test Results + Observations**:  When new content was being downloaded, it took an abnormally long time where the percentage was stuck at 80% - 84% cycling for about 2 minutes and then functioned properly.  During the home tutorial test, the hands did not rez only the colored lights that illuminate when pressed.  The lighter also failed to grip in the hand and kept flying about 3 feet in front of my avatar.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |52 |60
**Present Rate**: |60 |52 |60
**Present New Rate**: |60 |52 |36
**CPU Buffer Count**: |950 |1001 |1253
**GPU Buffer Count**: |219 |282 |353
**CPU Memory Usage**: |10199216 |11425008 |12796016
**GPU Memory Usage**: |3863984 |6297008 |6469040
**CPU Texture Count**: |127 |71 |121
**GPU Texture Count**: |55 |52 |71
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |146974004 |56053772 |50005704
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |66743 |71656 |180262
**Triangle Rate**: |4171437 |4215058 |11266375
**API Drawcall Count**: |50 |44 |92
**Drawcall Count**: |50 |37 |97
**Drawcall Rate**: |3125 |2176 |6062
**State Changes Texture Count**:|77 |65 |115
**Pipeline Count**: |27 |35 |30
**Item Opaques**: |35 |177 |123
**Item Translucents**: |15 |37 |20
**Item Lights**: |5 |47 |15
**Timing Opaques**: |0.134 |0.329 |0.696
**Timing Translucents**: |0.031 |0.062 |0.081
**Timing Lighting**: |0.015 |0.024 |0.014
**Render Frame**: |0.764 |1.651 |1.599

**Comment by Nex-Pro** [comment]
testing build ...f6ba

**Comment by Nex-Pro** [comment]
Reminder to @cozza13 I'm working my way thru the spreadsheet.

**Comment by OmegaHeron** [comment]
I'm finding this build to be rather crashy, to point that I'm unable to do much in Interface before crashing (bug splats sent).  I found similarities to Kevin's experience (suspect that's due to oculus cv1+touch controls for us both).  I was able to grip lighter and light firework in tutorial, but, it took multiple attempts to find a sweet spot.  I'll keep plugging away at this, but, with Interface being so prone to crashing it's difficult making much progress in QA list...

**Pull request merged**
