### PR TITLE
Add Desktop object to JavaScript with width and height properties

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d3d104ec3aad16415db6edff73edadf4ea707e4 available at: https://gist.github.com/fc7cda565b887ba40d43<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5658.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5658.dmg

**Comment by cozza13** [comment]
tested and this works on Mac

**Comment by jherico** [comment]
What's the use case for this?

**Comment by ctrlaltdavid** [comment]
Positioning a WebWindow on screen. For example, when restoring a WebWindow's position at script start-up, ensure that it is visible on the user's desktop (screen resolution may have changed). Or preventing WebWindow from being dragged off desktop.

**Pull request merged**
