### PR TITLE
Support relative paths for material images

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- Create a material entity with url: https://hifi-content.s3.amazonaws.com/samuel/TestMaterialAbsolute.json
- Create a material entity with url: https://hifi-content.s3.amazonaws.com/samuel/TestMaterialRelative.json
- They should be identical (both textured).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8133/app_12680_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8133/HighFidelity-Beta-PR12680-8ddf360c796ff22d8d6f85fdbca7f692931860b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8133/HighFidelity-Beta-PR12680-8ddf360c796ff22d8d6f85fdbca7f692931860b1.exe

**Comment by qlimnavarro** [comment]
Currently testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Both Spheres look identical.

**Pull request merged**
