### PR TITLE
Display spinner in Web controls when they're loading an HTTP page

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Check that a spinner is displayed in the middle of the page when Web content is being loaded in the following dialogs...

Desktop, toolbar mode:
- Ctrl-B Web browser window.
- Settings > Avatar > Browse Avatars window.
- Marketplace button.

HMD, tablet mode:
- Settings > Avatar > Browse Avatars window.
- Marketplace button.


Check that a spinner is NOT displayed in the following dialogs...

Desktop, toolbar mode:
- Help window.
- Entities editor tabs.

HMD, tablet mode:
- Help window.
- Entities editor tabs.

**Comment by YuppyPlays** [comment]
Will test when built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/111/HighFidelity-Beta-PR10532-bc4af86b57f6be7a3e3a5e8a01d0e665c6be6276.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/113/HighFidelity-Beta-PR10532-bc4af86b57f6be7a3e3a5e8a01d0e665c6be6276.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/113/HighFidelity-Beta-PR10532-bc4af86b57f6be7a3e3a5e8a01d0e665c6be6276.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Desktop toolbar mode (Showing spinner)**
**Browser** Experienced a crash at first with the browser, but after this it worked fine. **Pass**
**Browse Avatars**    **Pass**
**Marketplace**     **Pass**

**HMD tablet mode (Showing spinner)**
**Browse Avatars**    **Pass**
**Marketplace**     **Pass**

**Desktop toolbar mode ( Not showing spinner)**
**Help Window** **Pass**
**Entities editor tabs** **Pass**

**HMD Tablet mode ( Not showing spinner)**
**Help Window** **Pass**
**Entities editor tabs** **Pass**

**Pass** in all tests :)

**Pull request merged**
