### PR TITLE
fix cubemaps on AMD cards running GL 4.5

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA

*On both NVidia and AMD graphics cards:*
- Go somewhere with a cubemap (skybox), and ensure it renders
- Ensure other textures continue to render as expected

*On AMD:*
- Verify that current master build only renders a small part of a cubemap (skybox)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39ae8e2be541162de6dc40dfa5aec3938146ff15 available at: https://gist.github.com/82e5bed6cf82a60791fc85e2e1450aee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8438-39ae8e2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8438-39ae8e2.dmg

**Comment by zzmp** [comment]
According to this wiki (https://www.opengl.org/wiki/Cubemap_Texture#Cubemap_array_textures) cubemaps should work with `glTextureSubImage3D` if the target type is `GL_TEXTURE_CUBE_MAP_ARRAY`. We were using `GL_TEXTURE_CUBE_MAP` and it was working on NVidia. I switched to `GL_TEXTURE_CUBE_MAP_ARRAY` and it continued to fail on AMD.

**Comment by jherico** [comment]
This can't actually be the issue.  Either we're incorrectly using the `glTextureSubImage3D` or we're doing allocation wrong.  Investigating.

**Comment by zzmp** [comment]
The ARB states that both GL_TEXTURE_CUBE_MAP and GL_TEXTURE_CUBE_MAP_ARRAY are valid.
This thread states that AMD has a bug around this feature: https://community.amd.com/thread/194748.

Switched to the EXT method at @jherico's suggestion, so that we continue using DSA and do not bind any textures.

**Comment by hifi-gustavo** [comment]
Build console output for commit: af915c79235f3bc83595f1473ddbcfd5f33511f2 available at: https://gist.github.com/82e5bed6cf82a60791fc85e2e1450aee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8438-af915c7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8438-af915c7.dmg

**Comment by jherico** [comment]
Appears to work fine on my nVidia system.

**Pull request merged**
