### PR TITLE
make voxels.js buttons work, again

### PR DESCRIPTION
**Pull request by sethalves**
- voxels.js works, again

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21c688390cea000f05d1b49b288e42e07915956c available at: https://gist.github.com/e81f1f4783c729b5e27a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7405.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7405.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b60000030774550b8a6ec026213ef3efcbdb1c89 available at: https://gist.github.com/e81f1f4783c729b5e27a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7405.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7405.dmg

**Comment by judasshuffle** [comment]
loaded the pr build then loaded voxel.js from the library the button loaded but nothing happened when I pressed it.

**Comment by sethalves** [comment]
Try loading from url:

https://rawgit.com/sethalves/hifi/fix-voxels-js/examples/voxels.js

**Comment by judasshuffle** [comment]
Aha much better working now , I have terrain . On the edges of the grass I have dirt on 2 sides and nothing on the other 2. But it tiles nice and easily. I was about to say the add buttons didn't do anything but now I see it sculpting the ground,amazing very cool, nice work

**Pull request merged**
