### PR TITLE
add guards to getShapeKey

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- basic smoke test - make sure things still render.

Note: still looking for a better repro case on how to cause the crash this hopefully fixes

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04f654794069b451039f04bd139af994758e0103 available at: https://gist.github.com/5441f615384dcd04e95717bbb09fb605<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8701-04f6547.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8701-04f6547.dmg

**Comment by ZappoMan** [comment]
Got word from Twa_Hinkle that this fixes his crash.

**Comment by bluetoe** [comment]
Seems to have fixed my attachment delete crash.

**Pull request merged**
