### PR TITLE
fix concurrency drillDown

### PR DESCRIPTION
**Pull request by howard-stearns**
Fix part 1 of https://highfidelity.fogbugz.com/f/cases/15965/Unexpected-behavior-with-suggestions-in-Go-To-app

### CODE REVIEW

**Comment by howard-stearns** [comment]
Also uses the preferred is_stacked from the server, instead of isStacked.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10631/HighFidelity-Beta-PR13393-97fa22b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10631/HighFidelity-Beta-PR13393-97fa22b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10631/HighFidelity-Beta-Interface-PR13393-97fa22b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10631/HighFidelity-Beta-PR13393-97fa22b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10631/HighFidelity-Beta-Interface-PR13393-97fa22b.exe

**Pull request merged**
