### PR TITLE
fix typo that broke avatar motion

### PR DESCRIPTION
**Pull request by AndrewMeadows**
Accidentally bypassed class data member by using a local variable with the same name.

### CODE REVIEW

**Comment by birarda** [comment]
Looks good - merging once built.

**Comment by birarda** [comment]
whoops - didn't mean to close

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9739d6837064e0648cc496f9ad7bd5230734e41d available at: https://gist.github.com/73eae01f8726ae09869b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4548.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9739d6837064e0648cc496f9ad7bd5230734e41d available at: https://gist.github.com/73eae01f8726ae09869b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4548.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4548.dmg

**Pull request merged**
