### PR TITLE
DO NOT MERGE - DevOps test

### PR DESCRIPTION
**Pull request by marko8904**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3994/HighFidelity-Beta-PR11556-38824a7e246ebf1b5b0ad10a7ef91a46e49f5eeb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4082/HighFidelity-Beta-PR11556-d97ea9953f284c1088db74d6a614bb49b88a9d65.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4082/HighFidelity-Beta-PR11556-d97ea9953f284c1088db74d6a614bb49b88a9d65.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4118/HighFidelity-Beta-PR11556-d97ea9953f284c1088db74d6a614bb49b88a9d65.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4118/HighFidelity-Beta-PR11556-d97ea9953f284c1088db74d6a614bb49b88a9d65.exe

**Pull request closed without merging**
