### PR TITLE
Fix Goto app cards staying highlighted if move off dialog while dragging

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

A) Reproduce the problem
- Recent master.
- Desktop mode.
- GOTO app.
- Mouse over a place or a snap image. The place or snap's rectangle highlights.
- Click down and drag horizontally to move the list.
- Keep holding mouse down and move cursor off the dialog then release the mouse: The place or snap's rectangle is still highlighted. (It shouldn't be.)
- Repeat in HMD: Same problem.

B) Check the PR fixes the problem
- PR build, desktop mode.
- Check that the place or snap's rectangle unhighlights when the list starts moving.
- Check that the place or snap's rectangle stays unhighlighted when the held-down mouse is moved off the dialog.
- Check that place or snap rectangles start highlighting again - once the list stops moving and the mouse button is released - if the mouse stays in the list while it's being dragged and ends up on an item.
- Repeat checks in HMD.

https://highfidelity.manuscript.com/f/cases/17640

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14478/HighFidelity-Beta-PR14298-1a12933.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14478/HighFidelity-Beta-PR14298-1a12933.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14478/HighFidelity-Beta-Interface-PR14298-1a12933.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14478/HighFidelity-Beta-PR14298-1a12933.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14478/HighFidelity-Beta-Interface-PR14298-1a12933.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14861/HighFidelity-Beta-PR14298-1a12933.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14861/HighFidelity-Beta-PR14298-1a12933.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14861/HighFidelity-Beta-Interface-PR14298-1a12933.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
