### PR TITLE
Re-added mouse sensitivity settings to General Preferences dialog.

### PR DESCRIPTION
**Pull request by r3tk0n**
**Relevant Manuscript Case:**
https://highfidelity.fogbugz.com/f/cases/16259/Mouse-Sensitivity-is-missing-from-Settings-General

### CODE REVIEW

**Comment by r3tk0n** [comment]
**Test Plan**:
_Objective:_ Check if Mouse Sensitivity section has been re-added to General Settings desktop dialog as well as HMD Tablet General Settings dialog.

**Part 1:**
- Open Interface.exe
- Navigate to Settings -> General... (or press CTRL+G)
- Scroll through options to find "Mouse Sensitivity" menu section, below "User Interface" and above "Snapshots"

**Part 2:**
- Open Interface.exe in HMD mode
- Open the Tablet
- Open the Menu app
- Click on Settings
- Click on General
- Scroll through options to find "Mouse Sensitivity" menu section, below "User Interface" and above "Snapshots"

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10961/HighFidelity-Beta-PR13489-f36ba49.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10961/HighFidelity-Beta-PR13489-f36ba49.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10961/HighFidelity-Beta-Interface-PR13489-f36ba49.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10961/HighFidelity-Beta-PR13489-f36ba49.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10961/HighFidelity-Beta-Interface-PR13489-f36ba49.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Mouse sensitivity settings are now present

**Pull request merged**
