### PR TITLE
various HMD fixes and improvements

### PR DESCRIPTION
**Pull request by ZappoMan**
Fixes included:
- don't move mouse to center of screen on reset sensors
- if in the HMD and you lose mouse capture, go into away mode

### CODE REVIEW

**Comment by ZappoMan** [comment]
Fixes this bug:
https://app.asana.com/0/26320649018758/92378533916438

Testing notes:
- Run interface, press the ' key, notice that mouse doesn't move to center of window.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f602a938d7a9e17c9bbc328057f55ecc0a26aba available at: https://gist.github.com/e8475cd9f9a3f8caa6a1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7154.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7154.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbe80bffd679ca6ba211fee45c03cf0bc53f3070 available at: https://gist.github.com/e8475cd9f9a3f8caa6a1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7154.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7154.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - works as expected, no jumping mouse pointer in screen mode.

**Comment by cozza13** [comment]
tested with HMD

**Pull request merged**
