### PR TITLE
Reduce memory usage for loaded models

### PR DESCRIPTION
**Pull request by zzmp**
- Move FBX data into the network geometry (don't retain it)
- Construct animations from Joints and AnimationFrames, not entire Geometries
- Change entity tree interface to avoid exposing geometry ptr

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e8f8d9e9909d61d7a2445fda815db6bb3a9e77f available at: https://gist.github.com/dce3dd89d16b0191ddade3eb70c0cb79<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12a297457a1b58697bf67f46e0fb4fbf1206f601 available at: https://gist.github.com/dce3dd89d16b0191ddade3eb70c0cb79<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68e30a7934363fa3ab70852fae409a39237ed66b available at: https://gist.github.com/dce3dd89d16b0191ddade3eb70c0cb79<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7621.dmg

**Comment by zzmp** [comment]
This breaks avatar textures, and I don't have time to fix it up until next week, so I am closing for now. WIll reopen when it is ready.

**Pull request closed without merging**
