### PR TITLE
FB16992 - Layout changes to the two lightboxes in the Avatar app

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/16992/Layout-changes-to-the-two-lightboxes-in-the-Avatar-app

**Test plan**

1. Open avatarapp
2. Click 'get more avatars' (at the end of bookmarks)
3. Ensure popup has the same data/layout as on the image below (from https://highfidelity.fogbugz.com/f/cases/16992/Layout-changes-to-the-two-lightboxes-in-the-Avatar-app): 

image

4. Click 'Add' button to show 'get wearables' popup (button visible if bookmark with no wearables selected)
5. Ensure popup has the same data/layout as on the image below (https://highfidelity.fogbugz.com/f/cases/16992/Layout-changes-to-the-two-lightboxes-in-the-Avatar-app): 

image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11500/HighFidelity-Beta-PR13673-e12569c.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11501/HighFidelity-Beta-PR13673-fd7fb42.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11501/HighFidelity-Beta-PR13673-fd7fb42.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11501/HighFidelity-Beta-Interface-PR13673-fd7fb42.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11712/HighFidelity-Beta-PR13673-fd7fb42.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11712/HighFidelity-Beta-PR13673-fd7fb42.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11712/HighFidelity-Beta-Interface-PR13673-fd7fb42.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11712/HighFidelity-Beta-PR13673-fd7fb42.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11712/HighFidelity-Beta-Interface-PR13673-fd7fb42.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

However, the lack of punctuation on "Visit "AvatarIsland" to get wearables" is inconsistent.

**Pull request merged**
