### PR TITLE
Fixed avatar billboards not displaying

### PR DESCRIPTION
**Pull request by SamGondelman**
- fixed billboards being completely transparent
- fixed billboards being covered by other elements during generation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: c19115a4852b870cf7a6f994870aabe21f4f677f available at: https://gist.github.com/2461a328a49c57abf712<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5007.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5007.dmg

**Comment by samcake** [comment]
Bravo for your first PR!

**Pull request merged**
