### PR TITLE
Fix blendshapes crash one last time

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:

- The crash doesn't repro all the time because the timing is tricky. The easiest thing to do: go to engine-dev. There are a lot of avatars there. Spin around as they load, reload content, leave the domain and come back. Each time wait until the avatars all load. Their faces should render correctly, as should your own. You shouldn't crash.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12578/HighFidelity-Beta-PR13919-028092f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12578/HighFidelity-Beta-PR13919-028092f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12578/HighFidelity-Beta-Interface-PR13919-028092f.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by AndrewMeadows** [comment]
For the record: I was reliably crashing 100% on linux when connecting to engine-dev domain.  I cloned this branch, built it, and tested --> no crash.

**Comment by qaAdamSmith82** [comment]
I am crashing _less_
[hifi-log_2018-08-31_15.54.19.txt](https://github.com/highfidelity/hifi/files/2341827/hifi-log_2018-08-31_15.54.19.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2341828/hifi-log.txt)

**Comment by qaAdamSmith82** [comment]
Pass @conklin94122 Haven't been able to repro the crash other than that one time. This is a vast improvement at the very least.

**Pull request merged**
