### PR TITLE
 Case 19548, Case 20827: Group cull all entity descendants of avatars (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19548/Wearables-on-avatars-are-popping
https://highfidelity.manuscript.com/f/cases/20827/Tablet-is-disappering

https://github.com/highfidelity/hifi/pull/14949

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17384/HighFidelity-Beta-PR14950-857db2f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17384/HighFidelity-Beta-PR14950-857db2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17384/HighFidelity-Beta-Interface-PR14950-857db2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17384/HighFidelity-Beta-PR14950-857db2f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17384/HighFidelity-Beta-Interface-PR14950-857db2f.exe

**Comment by qlimguicheteau** [comment]
Currently Testing

**Comment by qlimguicheteau** [comment]
Need a bit more information to continue:

This is a bit of a coin flip. On one hand, all of the wearables seemed to disappear properly and at the same time as the avatars, but when the bots were at the edge of the visible area, they began to have full-body popping in and out rapidly.

Video of edge popping included.
[BodyLODPop.zip](https://github.com/highfidelity/hifi/files/2881399/BodyLODPop.zip)

If this is a buried bug, then a new PR must be made,
If this is a newly created bug, then this PR is a Fail.

**Comment by qlimguicheteau** [comment]
Testing Paused for clarification reasons.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17441/HighFidelity-Beta-PR14950-f31bc49.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17441/HighFidelity-Beta-PR14950-f31bc49.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17441/HighFidelity-Beta-Interface-PR14950-f31bc49.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17441/HighFidelity-Beta-PR14950-f31bc49.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17441/HighFidelity-Beta-Interface-PR14950-f31bc49.exe

**Comment by qlimguicheteau** [comment]
Resuming Testing

**Comment by qlimguicheteau** [comment]
PASS
--
Avatars and their wearables appear and disappear at the same time.

The edge of the LOD range no longer sprawls across several meters, and while the LOD is still jumpy at the edges, it is much better than the previous version. The jumpiness matches general LOD occurrences closer.

[LodAvatars.zip](https://github.com/highfidelity/hifi/files/2885909/LodAvatars.zip)
I had a video with far more bots, but the recording software became jittery and made things look artificially worse.

**Pull request merged**
