### PR TITLE
Update interstitial process. (WIP)

### PR DESCRIPTION
**Pull request by danteruiz**
Update interstitial process.

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- run this app https://hifi-content.s3.amazonaws.com/dante/scripts/InterstitialToggle.js
- press the button to enable and disable  interstitial mode. Reload of default script is required.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13354/HighFidelity-Beta-PR14089-7e138eb.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13354/HighFidelity-Beta-PR14089-7e138eb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13354/HighFidelity-Beta-Interface-PR14089-7e138eb.exe

**Pull request merged**
