### PR TITLE
Add finished signal to Resource loading

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent

This is unused, but I'd like to use it for cache rewrites. I'm working on ModelCache right now, and there is no great async way to see when something is both loaded (from the network) and processed. I *could* add it on a per-derived-class basis, but derived classes already need to call finishedLoading, so this seems more appropriate.

#### Testing

General smoke screen.

**Comment by Atlante45** [comment]
Do you need that for your upcoming Resource PR?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17aa2845a8d8f365002ddb7c419cce7bd2739df6 available at: https://gist.github.com/5285ce2d272a7fef4d33<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17aa2845a8d8f365002ddb7c419cce7bd2739df6 available at: https://gist.github.com/5285ce2d272a7fef4d33<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17aa2845a8d8f365002ddb7c419cce7bd2739df6 available at: https://gist.github.com/5285ce2d272a7fef4d33<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7440.dmg

**Pull request merged**
