### PR TITLE
adding back notifcations to default scripts

### PR DESCRIPTION
**Pull request by danteruiz**
re adding notification back to default scripts.

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- check that the notifications appear on the side of the screen. Like when you take a snap shot.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10228/HighFidelity-Beta-PR13262-072d8b7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10228/HighFidelity-Beta-PR13262-072d8b7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10228/HighFidelity-Beta-Interface-PR13262-072d8b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10228/HighFidelity-Beta-PR13262-072d8b7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10228/HighFidelity-Beta-Interface-PR13262-072d8b7.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Notifications appear on desktop and HMD

**Pull request merged**
