### PR TITLE
allow custom metaverse URL to be used with env var

### PR DESCRIPTION
**Pull request by birarda**
- allow a custom metaverse URL to be used via HIFI_METAVERSE_URL

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5606/HighFidelity-Beta-PR11974-7a81c3e8e785d775ac736310daff443eeed52722.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5606/HighFidelity-Beta-PR11974-7a81c3e8e785d775ac736310daff443eeed52722.dmg

**Comment by marko8904** [comment]
Test Plan:

- run the downloaded client, it should behave the same way as the one built from master. A general smoke test should be done. 
- Try connecting to hifi://hifiqa-metaverse-staging. This should fail. Shutdown the client.
- set the Environment variable on your system called HIFI_METAVERSE_URL and set its value to https://staging.highfidelity.com. For Windows 10 see the Env var instructions here: https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them
- run the same Interface client again and run another smoke test.
- try connecting to hifi://hifiqa-metaverse-staging.  This time it should work.

**Comment by Nex-Pro** [comment]
### PASS 
general smoke test of desktop and HMD modes.
Goto, Snap, Market, Create, Audio, Help general movement and flying.
Let me know if this is sufficient. With and without that env var set.
Able to connect to https://staging.highfidelity.com/ with env var set.

**Pull request merged**
