### PR TITLE
(TabletUX improvement) changing tablet spawn position

### PR DESCRIPTION
**Pull request by druiz17**
Change the tablet spawn position.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in HMD and bring up the tablet
- the tablet should spawn in the direction you are looking at.

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3394/HighFidelity-Beta-PR11391-9df3b6c211abaa5f57d2a4053d302eeeae9adb35.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3394/HighFidelity-Beta-PR11391-9df3b6c211abaa5f57d2a4053d302eeeae9adb35.exe

**Comment by anshuman64** [comment]
I am also testing this

**Comment by Nex-Pro** [comment]
@anshuman64 Should I drop this ?

**Comment by anshuman64** [comment]
1. Enter third person mode.
2. Grab the tablet
Observed: the tablet rotates according to avatar hand, not controller
Expected: tablet rotates according to controller

**Comment by anshuman64** [comment]
@Nex-Pro Yea I got it.

**Comment by anshuman64** [comment]
Checking spawn distance with Mukul...

**Pull request merged**
