### PR TITLE
Remove unnecessary prints and code for tabletWebView.qml

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- in tablet mode and toolbar mode
- open goto and click the info of the card
- ensure that card info web page shows up

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3090629f77fc43b18e1702356db5a1cdcabbb8c1 available at: https://gist.github.com/802c37c54f32562a56250cdde43bc8af<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10104-3090629.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10104-3090629.dmg

**Comment by StarmanF** [comment]
testing

**Comment by StarmanF** [comment]
**Desktop PC - Windows 10 Education - CPU 4.0GHz Intel i7 - GTX1080 - RAM 16GB - Vive**

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10104-3090629.exe

**Pass**

Notes:

- Tested both in tablet mode and toolbar mode, in desktop and VR modes.

- Opened goto and clicked the info of the card

- The web page shows up, it takes several seconds though, bit more than I would've expected. Though the latency is likely unrelated to the removal of unnecessary code. I've put a couple gif links below in case the latency is of any relevance. Overall, it does what it's supposed to do.

https://vgy.me/v3vosc.gif
https://vgy.me/XH5dar.gif

**Pull request merged**
