### PR TITLE
Introducing the custom shape pipeline & apply to Polyvox and Particle system entities

### PR DESCRIPTION
**Pull request by samcake**
This PR introduce a way to provide customized render shape pipeline for new rendering path not supported by the default one....

We added a new "prepareShapeItem" functor to the shape pipeline which can be used to specifiy an extra piece of rendering applied to each items and specific to the shape pipeline. THis feature will be used in the upcoming fading effect work.

We apply the new custom shape pipeline to the Polyvox and particle system rendering which were so far using a "ownPipeline" shapeKey. Using the custom shape pipeline, the specific path can be specified and bookmarked in the ShapePlumber map under the shape key just like the classic shape pipelines. This way these custom pipelines benefit state sorting and bucketing too (it was not the case with ownPipeline)

While applying the feature to Particle system i found that without texture the particles wouldn't render at all. so i "fixed" that case by rendering the no texture case filled (with the default white texture).
This removed the need for the "untextured_particles " shaders.

## TEST PLAN
Everything should look the same in this PR compared to master.
Performances should identical or better, no worse.
QA should specifically look for any issue on polyvox or particle systems. everything should look the same except for the case when a particle system doesn't have a texture URL specified, in this case, we use the default white texture showing full quads for the particles.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1588/HighFidelity-Beta-PR10950-5394ac86726111ea5d6790def85a5529ac79055d.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Performance: Could not tell of any difference in this and Master currently **Pass**
Polyvox: I am unsure what this refers to? may need a bit of a nudge in the right direction on that one
Particles: **Pass** Particles work as expected, no texture adds pure white boxes which I believe are what test plan refers to.

Can carry on after response :)

**Comment by Nex-Pro** [comment]
I am testing this.

**Comment by themelissabrown** [comment]
test this please

**Comment by Nex-Pro** [comment]
Also checking polyvox entities

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1605/HighFidelity-Beta-PR10950-5394ac86726111ea5d6790def85a5529ac79055d.exe

**Comment by Nex-Pro** [comment]
### Pass looks good.

No noticeable difference between this and master on polyvox.
Particles with no texture set are using blank white texture as per @YuppyPlays.
Exited cleanly.
Performance seems roughly on par with master.

**Comment by YuppyPlays** [comment]
Testing complete:

See image for voxel comparison. All looks good to me **Pass**
testvs

**Comment by AndrewMeadows** [comment]
The build failure on linux can be fixed by declaring `class ShapePlumber;` somewhere near the top of `ShapePipeline.h`.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1660/HighFidelity-Beta-PR10950-b065b99b0b845d0171094bcbd9b9389384e4effc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1660/HighFidelity-Beta-PR10950-b065b99b0b845d0171094bcbd9b9389384e4effc.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1661/HighFidelity-Beta-PR10950-1557b985c49d0964c84242b0d4a49b9e2eb5abed.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1661/HighFidelity-Beta-PR10950-1557b985c49d0964c84242b0d4a49b9e2eb5abed.dmg

**Pull request merged**
