### PR TITLE
Added login button to Tablet

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/6874/Add-Login-Button-to-Tablet

Test plan:
- Open Tablet
- log out and open Tablet again
- Observe "Log in" in top right corner
- Press it and do a log in
- Observe user name in top right corner of the Tablet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2599/HighFidelity-Beta-PR11209-2e5e0c94f13ab3cfed9bd1583a17a003de2003d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2599/HighFidelity-Beta-PR11209-2e5e0c94f13ab3cfed9bd1583a17a003de2003d8.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
--- | --- | ---
Open Tablet | Pass | Pass
log out and open Tablet again | Pass | Pass
Observe "Log in" in top right corner | Pass | Pass
Press it and do a log in | Pass | Pass
Observe user name in top right corner of the Tablet | Pass | Pass

All good from here.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by anshuman64** [comment]
@mukulHF Can you design QA this before it gets merged? I feel like you will have some design feedback.

**Comment by mukulHF** [comment]
Hi Vlad, Could you align the right part of the text "Log in" with the right side of the tablet icons? thanks

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2625/HighFidelity-Beta-PR11209-bad8c39444384aa3853815bc54e011c1d9dc4293.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2625/HighFidelity-Beta-PR11209-bad8c39444384aa3853815bc54e011c1d9dc4293.exe

**Comment by anshuman64** [comment]
Vlad, this is great. Do you think we can add a logout button as well? Screenshot attached.

loginbuttontabletv2

Username should truncate after 8 characters.

**Comment by vladest** [comment]
sure

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2784/HighFidelity-Beta-PR11209-26026cb2b578e5394a6d80522749e64746168935.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2788/HighFidelity-Beta-PR11209-26026cb2b578e5394a6d80522749e64746168935.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2837/HighFidelity-Beta-PR11209-d8fb7300c3cd96652bea8bd50202e783f6e4cf3f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2837/HighFidelity-Beta-PR11209-d8fb7300c3cd96652bea8bd50202e783f6e4cf3f.exe

**Comment by anshuman64** [comment]
logoutbug

@vladest Bug:
1. Log in
2. Click log out
Notice that the UI on the tablet doesn't change, even though Interface has recognized you are logged out.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2921/HighFidelity-Beta-PR11209-b547b2573e16b26b6d90bf6cab54be0b78f73238.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2921/HighFidelity-Beta-PR11209-b547b2573e16b26b6d90bf6cab54be0b78f73238.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Open Tablet **Check**
log out and open Tablet again **Check**
Observe "Log in" in top right corner **Check**
Press it and do a log in **Check**
Observe user name in top right corner of the Tablet **Check**

**Pass** :)

**Pull request merged**
