### PR TITLE
Use JSON for application Settings

### PR DESCRIPTION
**Pull request by Atlante45**
Given the way the ini "file format" (There is no actually specified format) works and the way Qt decided to interpret it means that integer value and boolean don't retain their type past the life of the process. Any subsequent read will return a String.

To address that I wrote a QSetting format that uses JSON which is strongly typed and encodes non trivial types into a string (The same way Qt does in ini files).
- Switched Settings to use a JSON file
- Added a converter to get settings from ini files if no json file is found
- Cleaned up uses of QSettings throughout the codebase.
- Removed old backward compatible code that is no longer needed.
- Set Application Name, Organisation, Version earlier in it's lifetime (This is used by QSettings, QDebug and other services to determine where to put their files).
- Simplified Setting init process (only one call to `init` needed now, no more `preInit`)
- Removed ApplicationInfo.ini and moved values to BuildInfo.h
- Fixed an old bug that made it so the interface.ini file was shared by all installs (Now stable, dev and PRs each have their own .ini file)
# Fixes:

https://highfidelity.fogbugz.com/f/cases/1033/Boolean-Settings-values-are-sometimes-read-as-type-Boolean-and-other-times-as-type-string
https://highfidelity.fogbugz.com/f/cases/1514/Settings-getValue-of-boolean-gives-string-in-NEXT-session
# Test plan:
- Run Interface and Sandbox. (This should look like a normal first run)
- Close both.
- Go to `C:\Users\<username>\AppData\Roaming\High Fidelity`
- Copy `interface.ini` and `domain-server.ini`
- Paste them in `C:\Users\<username>\AppData\Roaming\High Fidelity - PR8789`
- Run Interface and Sandbox. (This should look like a normal first run)
- In `C:\Users\<username>\AppData\Roaming\High Fidelity - PR8789` `interface.json` and `domain-server.json` should appear.
- Compare them to their `.ini` counter part to make sure the settings were ported correctly.
- Play around with changing settings and restarting interface, make sure the settings persist correctly.
- Compare framerates in the main domains between the current Master and this PR.
# Test Bug Fix:
### On current Master:
- Starting with a clean .ini file
- Open JS Console
- Paste this and press enter:

``` js
function write(name, value) {
    Settings.setValue(name, value);
    print("Storing (" +  typeof value + ") " + name + " => " + value);
}

function read(name) {
    var value = Settings.getValue(name);
    print("Reading: (" +  typeof value + ") " + name + " => " + value);
}

write("IntInt", 10);
write("IntString", "10");
write("BoolBool", true);
write("BoolString", "true");
write("String", "This is a string");

read("IntInt");
read("IntString");
read("BoolBool");
read("BoolString");
read("String");
```
- You should observe the following output:

```
Storing (number) IntInt => 10
Storing (string) IntString => 10
Storing (boolean) BoolBool => true
Storing (string) BoolString => true
Storing (string) String => This is a string
Reading: (number) IntInt => 10
Reading: (string) IntString => 10
Reading: (boolean) BoolBool => true
Reading: (string) BoolString => true
Reading: (string) String => This is a string
```
- Notice the type read match the type written
- Restart interface
- Run the above JS code again
- You should observe the following output:

```
Storing (number) IntInt => 10
Storing (string) IntString => 10
Storing (boolean) BoolBool => true
Storing (string) BoolString => true
Storing (string) String => This is a string
Reading: (string) IntInt => 10
Reading: (string) IntString => 10
Reading: (string) BoolBool => true
Reading: (string) BoolString => true
Reading: (string) String => This is a string
```
- Notice all the types have been collapsed to string
### On the PR build:
- Execute the above step and notice the types are conserved.
## Why the heck is that happening?

It's a combination of how QSettings locally keeps the types in RAM and how Qt implements the ini format.
Here is what the ini format looks like:

``` ini
IntInt=10
IntString=10
BoolBool=true
BoolString=true
String=This is a string
```

Notice ints, bools and string are all stored the exact same way.
And on read of the ini file, Qt interprets all\* types as string.
Another thing is that once a key is read/set into QSettings, it keeps it's current type until the end of the process.
Meaning that if I try to set a key to a boolean after it read a string, it'll stay a string.
## Why have we not noticed that before?

Most of our settings are used in the C++ code. The C++ statically associates a type to a key. So the value get converted all the time to the expected type. This doesn't happen with JS.
## Why JSON

Several reasons, first, JSON is strongly typed, it can differentiate between numbers, bools and strings.
Second, it was much easier to write a JSON read/write format than trying to fix and hack the INI format.

Here is how JSON stores the data:

``` json

{
    "IntInt": 10,
    "IntString": "10",
    "BoolBool": true,
    "BoolString": "true",
    "String": "This is a string",
}
```
## Misc

On top of that, this makes our settings slightly more readable.
1. Everything is sorted alphabetically
2. We can have spaces!
3. Support more native types:
interface.ini:

``` ini
; QRect
WindowGeometry=@Rect(39 201 1391 735)
; double
[Overlay.AvatarInputs]
y=11.343201518058777
; float
[Razer%20Hydra]
avatarPosition\x=@Variant(\0\0\0\x87\xbe\x80\0\0)
; QUrl
[AddressManager]
address="@Variant(\0\0\0\x11\0\0\0=hifi://welcome/-15.936,0.446346,-6.63038/0,0.85065,0,0.525733)"
```

interface.json:

``` json
{
    // QRect
    "WindowGeometry": "@Rect(17 230 1309 749)",
    // double
    "Overlay.AvatarInputs/y": 1.3715223073959351,
    // float
    "Razer Hydra/avatarPosition/x": -0.25,
    // QUrl
    "AddressManager/address": "hifi://welcome/-15.5723,0.446328,-6.88071/0,0.838931,0,0.544238",
}
```

* Comments in the above examples are not in the actual files.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bae69bb51ad1a12cce0fe99c503e0d0418cf6ac available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-5bae69b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-5bae69b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2524bf2d4e94259e31bea4e5a47830fabaf1348f available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-2524bf2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-2524bf2.dmg

**Comment by ZappoMan** [comment]
whoa!! What is this PR? What's it fixing?

**Comment by Atlante45** [comment]
@ZappoMan Updated the PR details with some JS code to exhibit the bug (100% repro).
Explanation why it happens and why I fixed it with JSON.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 36bd9ef4e6db4801056c1b49be10c7aa0c7951ce available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-36bd9ef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-36bd9ef.dmg

**Comment by thoys** [comment]
@Atlante45 since when can comments be used in JSON? :)

**Comment by hifi-gustavo** [comment]
Build console output for commit: f28d362ab2db6271d4c2dc321f144a1c78ece1ec available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-f28d362.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-f28d362.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3035d437727f1cad5435b87a369110c2b7e1a76c available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-3035d43.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-3035d43.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d8c97b3375562cd84b7b7ebba7893bc316140f6 available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-1d8c97b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-1d8c97b.dmg

**Comment by zzmp** [comment]
@Atlante45 echoing @thoys with the comments comments.

I *like* the comments, but it is no longer valid JSON if we allow them - technically, everything should just be self-documenting.

As long as this is replacing INI with a custom format, I'd rather keep the comments, though.

**Comment by Atlante45** [comment]
@zzmp OK, just to clarify, the comments are just here for the purpose of explaining what's going on.
**There are no comments in the actual file.**
Probably should've made that more clear =)

**Comment by OmegaHeron** [comment]
I'll work through testing this one.  Could we get a merge and rebuild first, please?

**Comment by hifi-gustavo** [comment]
Build console output for commit: e6b9d3604d8c8ed9c915c7386f8f43f94d8de572 available at: https://gist.github.com/449df1cf5a0d02efdcc0ebb65a570069<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-e6b9d36.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8789-e6b9d36.dmg

**Comment by OmegaHeron** [comment]
Testing -- will be a while to run through all.

**Comment by OmegaHeron** [comment]
Testing Windows 10

QA Passes.  It would likely by good to have others with more complex setups run this once as well (hand controls etc etc etc) just to be sure all migrates/persists in case there's anything I missed.  That said - it seems solid here.

Followed test procedure, settings were ported correctly to new json files.  Compared line by line and all look correct.  Exercised menu options and confirmed persistence in json settings.  FPS is unchanged between this PR and last RC.

Used console JS commands against build 5744 then this PR and results print as specified.

**Comment by kevinmthomasse** [comment]
Will test as well tonight.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Ran PR Interface and Sandbox and closed both.  Went to ```C:\Users\<username>\AppData\Roaming\High Fidelity``` and copied ```interface.ini``` and ```domain-server.ini``` and pasted them in ```C:\Users\<username>\AppData\Roaming\High Fidelity - PR8789``` and ran Interface and Sandbox   In ```C:\Users\<username>\AppData\Roaming\High Fidelity - PR8789``` ```interface.json``` and ```domain-server.json``` appeared.  Compared them to their .ini counter part and verified the settings were ported correctly as ```interface.ini``` had more a different order than its respective ```interface.json``` file which was not an issue.  Manipulated settings and restarted interface, as settings persisted.  Compared framerates in the main domains between the current Master and this PR no issues.  In current master started with clean .ini file.  Ran code in JS console:
```
function write(name, value) {
    Settings.setValue(name, value);
    print("Storing (" +  typeof value + ") " + name + " => " + value);
}

function read(name) {
    var value = Settings.getValue(name);
    print("Reading: (" +  typeof value + ") " + name + " => " + value);
}

write("IntInt", 10);
write("IntString", "10");
write("BoolBool", true);
write("BoolString", "true");
write("String", "This is a string");

read("IntInt");
read("IntString");
read("BoolBool");
read("BoolString");
read("String");
```
Successfully observed:
```
Storing (number) IntInt => 10
Storing (string) IntString => 10
Storing (boolean) BoolBool => true
Storing (string) BoolString => true
Storing (string) String => This is a string
Reading: (number) IntInt => 10
Reading: (string) IntString => 10
Reading: (boolean) BoolBool => true
Reading: (string) BoolString => true
Reading: (string) String => This is a string
```
Restarted interface and verified the following in a JS console:
```
Storing (number) IntInt => 10
Storing (string) IntString => 10
Storing (boolean) BoolBool => true
Storing (string) BoolString => true
Storing (string) String => This is a string
Reading: (string) IntInt => 10
Reading: (string) IntString => 10
Reading: (string) BoolBool => true
Reading: (string) BoolString => true
Reading: (string) String => This is a string
```
Verified string values collapsed except for BOOL.  Expected behavior.  Tested on PR build.  Successful results:
```
Storing (number) IntInt => 10
Storing (string) IntString => 10
Storing (boolean) BoolBool => true
Storing (string) BoolString => true
Storing (string) String => This is a string
Reading: (number) IntInt => 10
Reading: (string) IntString => 10
Reading: (boolean) BoolBool => true
Reading: (string) BoolString => true
Reading: (string) String => This is a string
```

**Comment by OmegaHeron** [comment]
@sethalves 

Compared to RC29 I see no FPS change -  looked at playa, sandbox default, old apartment and my old domain. FPS with vsync unlocked on desktop is essentially = RC or PR within normal run to run variances.  DK2 shows 75 fps everywhere tested as it does with RC.

**Pull request merged**
