### PR TITLE
Re-adding toggleSpaceMode function

### PR DESCRIPTION
**Pull request by wayne-chen**
There was an uncaught exception in scripts/system/edit.js called selectionDisplay.toggleSpaceMode() but is not defined anymore in the tip of master. I caught this while looking at the log window fixing some other ticket. I'm re-adding this function so that this uncaught exception will not appear.

### CODE REVIEW

**Comment by wayne-chen** [comment]
To test:

- Build latest Interface on tip of master
- Launch Interface
- Enable Settings->Developer Menu
- Open Developer->Log
- See UncaughtException in defaultScripts.js for toggleSpaceMode
- In fixed build:
    - Launch Interface
    - Enable Settings->Developer Menu
    - Open Developer->Log
    - UncaughtException in defaultScripts.js for toggleSpaceMode disappears

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10240/HighFidelity-Beta-PR13265-34120da.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10240/HighFidelity-Beta-Interface-PR13265-34120da.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10240/HighFidelity-Beta-PR13265-34120da.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10240/HighFidelity-Beta-Interface-PR13265-34120da.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10409/HighFidelity-Beta-PR13265-34120da.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10409/HighFidelity-Beta-PR13265-34120da.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10409/HighFidelity-Beta-Interface-PR13265-34120da.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10409/HighFidelity-Beta-PR13265-34120da.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10409/HighFidelity-Beta-Interface-PR13265-34120da.exe

**Comment by qlimguicheteau** [comment]
Currently Testing

**Pull request merged**
