### PR TITLE
Switching Windows builds over to a self-hosted runner

### PR DESCRIPTION
**Pull request by hd23408**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22824/HighFidelity-Beta-PR16582-e4acc18.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22824/HighFidelity-Quest-Beta-PR16582-e4acc18.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22824/HighFidelity-Beta-PR16582-e4acc18.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22824/HighFidelity-Beta-Interface-PR16582-e4acc18.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22824/HighFidelity-Beta-PR16582-e4acc18.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22824/HighFidelity-Beta-Interface-PR16582-e4acc18.exe

**Comment by hd23408** [comment]
Moving builds over to self-hosted Windows runner

**Pull request merged**
