### PR TITLE
make connection messaging when not logged in

### PR DESCRIPTION
**Pull request by howard-stearns**
Implements https://highfidelity.fogbugz.com/f/cases/3966/Make-the-text-for-the-non-logged-in-error-message-nicer

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan
Try to connect with someone (handshake) while not logged in.
Get results from ticket.

Note the issues raised by the ticket.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b089fd03b8ba9d3c0dba1cd13daf5cae2ffa61fc available at: https://gist.github.com/a56a541a613dc0cbfa595c0825a5c934<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10155-b089fd0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10155-b089fd0.dmg

**Comment by howard-stearns** [comment]
Now also fixes https://highfidelity.fogbugz.com/f/cases/4021/Notifier-wordWrap-doesn-t-or-doesn-t-do-it-well.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5d341778c5d558949a5c88905645dca2a9526483 available at: https://gist.github.com/a56a541a613dc0cbfa595c0825a5c934<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10155-5d34177.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10155-5d34177.dmg

**Comment by davidkelly** [comment]
I think we need to send a bool in the waiting and connectionRequest messages, with whether or not you are logged in, in the future.  Then, _both_ participants know that this isn't worth sending to metaverse, and we can have a different handshake experience for them if we want.  But this does what is intended in the ticket, so that works for me.

**Comment by howard-stearns** [comment]
I agree. The general handling of user flow was not thought through and needs some consideration -- and experience in use.

**Pull request merged**
