### PR TITLE
QA READY: Fix Asset Browser add-to-world

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Select an FBX model in Asset Browser. Use add to world button. Add a space to the end of the model name. Press Add. ... The model should successfully be added to the world.
- Select an FBX model in Asset Browser. Use add to world button. Use drop-down to set type. Press Add. ... The model should successfully be added to the world.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 86f6cee2ad4139015ff0bdccea2e8db629111701 available at: https://gist.github.com/738b8d8d2b0e01555f85a981c4692509<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8788-86f6cee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8788-86f6cee.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
All physics shape from pulldown work correctly
Tailing space on name is removed

Default choice of Exact - All polygons should disallow setting Dynamic, which it does, but only by allowing you to click Dynamic tick box then add model then nothing happens.  That should be fixed to behave better either disallowing tick box or warning user or both.

**Comment by ctrlaltdavid** [comment]
That's a quite different issue to the original FogBugz item but I'll add a fix for it on this branch, too.

**Comment by OmegaHeron** [comment]
Yes - sorry about that, but, it wasn't apparent until the former was fixed.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 18f19b07d4338430d728ad4944284b0016af76f4 available at: https://gist.github.com/738b8d8d2b0e01555f85a981c4692509<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8788-18f19b0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8788-18f19b0.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Tested placing model with each option, dynamic is allowed where it should and should not be, models placed with each combo of option reflect correct value in model properties.

**Pull request merged**
