### PR TITLE
21289 - Edit: Add the ability to duplicate an object with hand controller

### PR DESCRIPTION
**Pull request by amvmoody**
# QA

## Info
- verify that duplication of an entity works the same as alt + dragging an entity.
- HMD Required

## Setup
- install the version of hifi that is auto built from this PR.

## Steps - Single Person
1. Create an entity with Create and then select it.
2. click on the new green cube overlay that has been added and drag the entity creating a duplicate.
3. repeat 2. with a HMD use the selection beam to select the green cube and drag to duplicate.

### CODE REVIEW

**Comment by PhilipRosedale** [comment]
Add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: dae652d3db31309f90bbbb63df61c9c1b692187f available at: https://gist.github.com/f0984b91c807fb6bc05105e6b3f84783<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-dae652d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-dae652d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dae652d3db31309f90bbbb63df61c9c1b692187f available at: https://gist.github.com/f0984b91c807fb6bc05105e6b3f84783<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-dae652d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-dae652d.dmg

**Comment by PhilipRosedale** [comment]
My testing results:  Works well, but I see two problems: 

1.  'Light' objects do not get a green handle. 

2.  Can we made the green handle always appear on the bounding box face that is closest to you?  It is easy to create an entity and have the handle be behind the entity and therefore ungrabbable with the hand controller laser beam.

**Comment by amvmoody** [comment]
1.) I would make this its own wl item, nothing in edit.js changes colors atm, you can see the overlay boxes well enough even if you make the entity the same color. but the same cannot be said for the lines that are overlayed on the edges of the entities.

**Comment by PhilipRosedale** [comment]
@amvmoody For #1 I meant "The entity type which is a light", not "light colored objects".  When I made a light, I couldn't see the green box anywhere. 

#2.  Lemme try.  I didn't think that worked for me.  I was hitting the object, when the green box was on the opposite side.

**Comment by PhilipRosedale** [comment]
OK, so for #2 you are right the lasers do select through the object, though they don't 'seem' to because of the termination of the seek ray.   So I am OK with this if you can a duplicate box displayed for the case when it is an entity of type light that is selected.

**Comment by amvmoody** [comment]
@PhilipRosedale I've updated this to give the new overlay to all Entity types, light included.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89d93ee56db5022b6caa860ab0715f3b9c5ec915 available at: https://gist.github.com/f0984b91c807fb6bc05105e6b3f84783<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-89d93ee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10406-89d93ee.dmg

**Comment by themelissabrown** [comment]
@amvmoody is this ready for QA testing again?

**Comment by amvmoody** [comment]
@themelissabrown it is. :)

**Pull request merged**
