### PR TITLE
fix interface crash for bad QVector index in animation loop

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5700/app_12008_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5700/HighFidelity-Beta-PR12008-2d1ac3287417be09e8dcfbdd66a46fc8e5519bda.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5700/HighFidelity-Beta-PR12008-2d1ac3287417be09e8dcfbdd66a46fc8e5519bda.dmg

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/10722/crash-while-watching-an-animated-entity

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5703/app_12008_PR.apk

**Comment by sethalves** [comment]
to test:
- run this test: https://highfidelity.testrail.net/index.php?/cases/view/2957
- visit hifi://eschatology/85.5679,33.4396,84.3959/0,0.251603,0,0.96783
- watch the guy stand up and sit down, don't crash (don't worry about his messed up feet)
- visit hifi://eschatology/107.606,1.4362,95.2318/0,0.423425,0,0.905931
- see that the two characters are moving (animated)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5703/HighFidelity-Beta-PR12008-e97b61674542f9a9224adf9571b48355916fb791.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5703/HighFidelity-Beta-PR12008-e97b61674542f9a9224adf9571b48355916fb791.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

run this test: https://highfidelity.testrail.net/index.php?/cases/view/2957 **Check, TestRail Results: https://highfidelity.testrail.net/index.php?/tests/view/26501&group_by=cases:section_id&group_order=asc&group_id=1471**
visit hifi://eschatology/85.5679,33.4396,84.3959/0,0.251603,0,0.96783 **Fail, was unable to access domain (See image below steps)
watch the guy stand up and sit down, don't crash (don't worry about his messed up feet) **Fail**
visit hifi://eschatology/107.606,1.4362,95.2318/0,0.423425,0,0.905931 **Fail**
see that the two characters are moving (animated) **Fail**


Mismatch:
image

**Fail**

**Note: I'd reported crashes in last PR involving same initial TestRail test plan and had crashes on that terribly often, with this I've not crashed once, though due to the domain mismatch could not complete the plan for this PR.**

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5723/app_12008_PR.apk

**Comment by AndrewMeadows** [comment]
I'm not going to mark this as FAIL.  `hifi/master` picked up a protocol version change that made this PR out of date, but I've rebased it so when the installers are rebuilt then it will be **QA_READY** again.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5724/app_12008_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5724/HighFidelity-Beta-PR12008-bad2c1df7693f9794a6f935483a0c64529d9bfc8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5724/HighFidelity-Beta-PR12008-bad2c1df7693f9794a6f935483a0c64529d9bfc8.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

run this test: https://highfidelity.testrail.net/index.php?/cases/view/2957 **Pass same as previous build pass.**
visit hifi://eschatology/85.5679,33.4396,84.3959/0,0.251603,0,0.96783 **Pass**
watch the guy stand up and sit down, don't crash (don't worry about his messed up feet) **Pass**
visit hifi://eschatology/107.606,1.4362,95.2318/0,0.423425,0,0.905931 **Pass**
see that the two characters are moving (animated) **Pass**

Solid **Pass**

**Pull request merged**
