### PR TITLE
fix login links (forgot username and password)

### PR DESCRIPTION
**Pull request by danteruiz**
Fixed the issue of the forgot password/username not showing up on the login dialog

https://highfidelity.fogbugz.com/f/cases/13789/Log-in-Sign-up-dialog-is-missing-Forgot-Username-and-Forgot-Password-links

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10892/HighFidelity-Beta-PR13466-a906fba.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10892/HighFidelity-Beta-PR13466-a906fba.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10892/HighFidelity-Beta-Interface-PR13466-a906fba.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10892/HighFidelity-Beta-PR13466-a906fba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10892/HighFidelity-Beta-Interface-PR13466-a906fba.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Link appear and function as intended.

**Pull request merged**
