### PR TITLE
400 connections per page for Wallet and PAL

### PR DESCRIPTION
**Pull request by zfox23**
Fixes https://highfidelity.fogbugz.com/f/cases/11831/Connections-List-cutting-off-users-Not-seeing-all-of-them

### CODE REVIEW

**Comment by changxc** [comment]
This PR requires tester has 100+ friends, would appreciate very much!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6681/app_12281_PR.apk

**Comment by zfox23** [comment]
## Test Plan
1. Have a bunch of connections (more than 100)
2. Open the PAL, go to the Connections tab, and verify that you see all of your connections
3. Open the Wallet, go to Send Money, click Connection, and verify that you see all of your connections

**Comment by conklin94122** [comment]
QL, we're going to test this in-house as it requires 100+ connections.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6681/HighFidelity-Beta-PR12281-00555250a07bcc062f1ed5d77c70c65a7405e135.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6681/HighFidelity-Beta-PR12281-00555250a07bcc062f1ed5d77c70c65a7405e135.exe

**Comment by thoys** [comment]
Test result
1. check.
2. I can see all my 169 connections, which I couldn't do before.
3. I can also see all my connections in this list

QA Passed

**Comment by changxc** [comment]
Per @thoys Test passed

**Pull request merged**
