### PR TITLE
Commerce: Avatar Entity Tests

### PR DESCRIPTION
**Pull request by zfox23**
**IMPORTANT NOTE!** This PR interacts with the behavior of rezzing entities. Please perform the [Owner Verification for Certified Non-Avatar Entities](https://highfidelity.testrail.net/index.php?/cases/view/2187) test using this PR's build before starting QA of this PR.

# What's New
This PR adds one layer of avatar entity (wearable) security to High Fidelity. We do this by:
1. Performing static certificate verification on avatar entities upon inspection
2. Challenging ownership of avatar entities upon inspection
    * To do this, we use a similar method that is currently employed by the Entity Server with non-avatar entities upon rez. However, for avatar entities, the ownership challenge originates from the client performing the challenge.

# Future Work
- If the client that is `OwnershipChallenge`d hasn't authenticated their Wallet, notify that client that they need to authenticate for other clients to see valid certificates on their wearables

# Test Plan
The Test Plan for this PR is on TestRail here: https://highfidelity.testrail.net/index.php?/cases/view/2193

Please let me know if you can't access the above.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4614/HighFidelity-Beta-PR11730-bb1ffbc06f40a93a749a34b9b40857e0c9035b0d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4614/HighFidelity-Beta-PR11730-bb1ffbc06f40a93a749a34b9b40857e0c9035b0d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4640/HighFidelity-Beta-PR11730-f8718efe25dbeb5e6f3a8162e3bdaa5be19e4cd3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4643/HighFidelity-Beta-PR11730-19945c5991425745be0355d953f6537248837dd3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4643/HighFidelity-Beta-PR11730-19945c5991425745be0355d953f6537248837dd3.exe

**Comment by Nex-Pro** [comment]
Testing Awaiting win build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4656/HighFidelity-Beta-PR11730-23e627a46f740cb3f4e5ccb2384cde0876c6799f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4656/HighFidelity-Beta-PR11730-23e627a46f740cb3f4e5ccb2384cde0876c6799f.exe

**Comment by Nex-Pro** [comment]
T E S T I N G Win10

**Comment by Nex-Pro** [comment]
### Pass

See testrail

**Pull request merged**
