### PR TITLE
grab script preliminaries

### PR DESCRIPTION
**Pull request by hyperlogic**
* Use the recently introduced “entry” method functionality from PR#8025 to eliminate the continue states.
* Also remove the Release state and copy its logic into the entry method of the Off state.
* Remove the ability to toggle equip by pressing the thumb stick.  This gets rid of 4 states, and simplifies the state machine.  (WaitingForEquipThumbRelease, Equip, ContinueEquip, WaitingForReleaseThumbRelease)
* Now passes eslint check.
* Bug fix for vive RIGHT_GRIP, LEFT_GRIP buttons, which is also addressed in #PR8063.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb51d00c1d50090d43a1ae03eb236f3f8e2a8fdc available at: https://gist.github.com/e134f5ced5f67dd3098e9a0ffad50ef2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.dmg

**Comment by hyperlogic** [comment]
Test plan:
   * Enter the demo domain in HMD mode using the Vive with hand controllers.
   * Place your hand over a colored block on the table, press the trigger to near-grab the block.  You should be able to pick it up and move it, while the triggers depressed, it should drop when you release the trigger. 
   * Stand away from the table, press the trigger the far-grab laser should appear, when the far-grab laser lands on a colored block you should enter far-grab mode.  Releasing the trigger should drop the object.
   * Test the near-trigger behavior by placing your hand in the top marquee of the defender machine and pressing the trigger.  This should reset all the blocks on the table.

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9codoy8g&#x2F;25-grab-script-preliminaries"> Grab Script Preliminaries</a>

**Comment by RyanDowne** [comment]
I am seeing some differences between near grabbing a block in master and this PR. In this PR, when I near grab something with my right hand, the block snaps to a position that's not quite in my hand. In master, I can pass a block back and forth between the two hands without any "snapping"

**Comment by hyperlogic** [comment]
@RyanDowne I see this too, not initially, but after a series of grabs and releases.  Looking into the root cause.

**Comment by howard-stearns** [comment]
Maybe revise the test plan to use home content tidybot or lightswitch instead of demo->defender reset, in order to avoid problems with version incompatabilities?

**Comment by howard-stearns** [comment]
I'm not clear on what the beta release does about "throwing" -- imparting a velocity on an object. Do you intend to keep that? If so, maybe include a test for it in test plan?

**Comment by hyperlogic** [comment]
@RyanDowne This bug you mentioned is present in the last beta build as well.  It's just a bug in the grab script.  I can fix it, I'd rather do it in a future PR, and leave this PR for just changes that do not change behavior (except for the removal of the sticky-equip) feature.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 67aac09033d0e713adb1e41b4d5bd8dca2c607b2 available at: https://gist.github.com/e134f5ced5f67dd3098e9a0ffad50ef2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 071584597d11900803075e76d05bcf905203faa7 available at: https://gist.github.com/e134f5ced5f67dd3098e9a0ffad50ef2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8065.dmg

**Pull request merged**
