### PR TITLE
Make the rendering testing destination customizable 

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by jherico** [comment]
### Testing

Run the script playaPerformanceTest.js from https://rawgit.com/jherico/hifi/perf_testing/examples/tests/playaPerformanceTest.js

The dialog should now have a new control for entering the destination address you'd like to test.  Any valid address that you would put in the address bar should work:

* playa
* playa/10,100,100
* demo
* localhost
* 127.0.0.1
* @sam 

Verify that you can initiate a test and it works regardless of whether you're currently disconnect or already connected to your destination.  The test should always disconnect you from wherever you are (if you're connected to anything) and then immediately connect to the target and begin the test process for 30 second before spitting out a result.  Hitting `stop` during testing should abort early.  Once the test it complete it should disconnect you from the domain.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f91768bc0b17017d1ce7c6f21661a2e6d361de5 available at: https://gist.github.com/8a83cd85007e9bbc5dffccef0e2c4089<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7734.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7734.dmg

**Comment by OmegaHeron** [comment]
Tested this at cellscience - cellscience+location, playa, heron, o2tech and sandbox.  Works well - sometimes it leaves me spinning in disconnected free space - even more rarely it doesn't actually update graph at end, but, all in all it works well for a devel-centric tool.

Several runs at playa where I managed to not exceed my gpu ram...

playa-test

playa-test2

playa-test3

playa-test4

Standard HF Home scene at o2tech

o2t-test

o2t-test2

o2t-test3

**Comment by jherico** [comment]
@OmegaHeron any chance you could look at https://github.com/highfidelity/hifi/pull/7688 ?  It should reduce issues with running out of GPU memory in heavy domains.

**Comment by OmegaHeron** [comment]
I will @jherico - my previous look was less than promising.  Will see what latest changes do for it.

**Pull request merged**
