### PR TITLE
Fix MS14129: Prevent Marketplace buttons from getting stuck in hover state

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14129](https://highfidelity.fogbugz.com/f/cases/14129).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10517/HighFidelity-Beta-PR13348-a5ef3fa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10517/HighFidelity-Beta-PR13348-a5ef3fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10517/HighFidelity-Beta-Interface-PR13348-a5ef3fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10517/HighFidelity-Beta-PR13348-a5ef3fa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10517/HighFidelity-Beta-Interface-PR13348-a5ef3fa.exe

**Comment by zfox23** [comment]
## Test Plan
1. Open the MARKET app.
2. Scroll until you see an item's "BUY" button (the blue button that shows the item's price)
3. Hover over that button. Verify that the button says "BUY" when you hover over it.
4. Move your cursor off of that button. Verify that the button says the item's price.
5. VERY QUICKLY flick your mouse on and off of that button. Verify that, the final time that you remove the cursor from the button, the button says the item's price.

**Comment by qlikmorales** [comment]
Currently Testing

**Comment by qlikmorales** [comment]
@conklin94122 
Fail

Ran test plan and fails on step 5. 
When quickly hovering over and off the price button gets stuck on "BUY" hover state. 
Also tested on Master and Stable. Still occurs. 

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2094466/hifi-log.txt)

[Hover-BUY-button.zip](https://github.com/highfidelity/hifi/files/2094468/Hover-BUY-button.zip)

**Comment by zfox23** [comment]
Ah, @qlikmorales, after looking at your video, I can conclude that you have found a new bug with similar symptoms, although not exactly the same.

- The original bug occurred because the button got two `mouseenter` events before getting a `mouseleave` event. That bug is worse than this one, because not even re-hovering over the button would cause it to return to its original state.
- The bug you found occurred because the button never got a `mouseleave` event at all. You can "fix" the bug you found by hovering over the button, then leaving it.

I'm not actually sure if there's anything we can do about the browser not getting that event. I'll look into it...

**Comment by zfox23** [comment]
Yeah, I don't think this new bug is worth fixing. Lots of web developers complain about their `mouseleave` events getting missed:

https://javascript.info/mousemove-mouseover-mouseout-mouseenter-mouseleave
`If the mouse moves very fast from #FROM to #TO elements as painted above, then intermediate <div> (or some of them) may be skipped.`

https://stackoverflow.com/questions/7448468/why-cant-i-reliably-capture-a-mouseout-event
`I just don't get why this would be a hard problem for the browser vendors to solve.`

https://github.com/angular/angular/issues/13911
`probably because you moved your mouse too fast.`

Lots of people are saying to use CSS for this, but I'm not going to do that right now; this issue is too minor.

**Comment by zfox23** [comment]
@qlikmorales @conklin94122 Based on the video provided, and given the discussion about this bug here and on the ticket itself, I'm calling this a QA Pass and merging this PR.

**Pull request merged**
