### PR TITLE
Backup old content on update

### PR DESCRIPTION
**Pull request by Atlante45**
- Backup old content instead of deleting it during a sandbox content update.

(UI still need some work, will cleanup tomorrow)

Test plan:
- Launch sandbox (content set should get installed).
- Close sandbox.
- Go to `C:\Users\Clement\AppData\Roaming\High Fidelity - PRXXXX\Server Console\config.json`.
- Change the homeContentLastModified value to an old date (ie: 2012 should do it).
- Start sandbox.
- You should get prompted for an update.
- Accept and notice the content set getting re-downloaded.
- There should be another window explaining how to restore the content
- Follow instructions and restore original content.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4830b5c2a0d6e354fddbfc422cb299e704ea7ade available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4830b5c2a0d6e354fddbfc422cb299e704ea7ade available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4830b5c2a0d6e354fddbfc422cb299e704ea7ade available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4830b5c2a0d6e354fddbfc422cb299e704ea7ade available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-4830b5c.dmg

**Comment by kevinmthomasse** [comment]
Testing

**Comment by kevinmthomasse** [comment]
FAIL - New UI window generates every time you click ```yes``` and it simply generates a new UI rather than complete.
capture

**Comment by hifi-gustavo** [comment]
Build console output for commit: 701c710857794745300bd371a44d78da358c2864 available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 701c710857794745300bd371a44d78da358c2864 available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 701c710857794745300bd371a44d78da358c2864 available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-701c710.dmg

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  Launched sandbox (new content set installed) and closed sandbox.  Went to ```C:\Users\Clement\AppData\Roaming\High Fidelity - PR8680\Server Console\config.json```.  Changed the homeContentLastModified value to an old date.  Started sandbox.  Prompted for an update and accepted and noticed the content set getting re-downloaded.  Another window explaining how to restore the content and followed instructions and restore original content however when restarted server no content.
capture

**Comment by hifi-gustavo** [comment]
Build console output for commit: b83243d65d5f85453eed1849d15878f08b24a79b available at: https://gist.github.com/cc4257a1eedcd7582c0ba401ca1387e7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-b83243d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8680-b83243d.dmg

**Comment by Atlante45** [comment]
@kevinmthomasse Updated everything to a final state, hopefully this is the final QA.
I tested on windows 10 and the file restoration worked fine, let me know if that happens again for you and send me the exact step you took.
Thanks!

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Launched sandbox (new content set installed) and closed sandbox.  Went to ```C:\Users\Clement\AppData\Roaming\High Fidelity - PR8680\Server Console\config.json```.  Changed the homeContentLastModified value to an old date.  Started sandbox.  Prompted for an update and accepted and noticed the content set getting re-downloaded.  Another window explaining how to restore the content and followed instructions and restore original content.  Instructions are a NICE improvement and very clean to understand with graphics.  WELL DONE.  Successfully restored.

**Comment by Atlante45** [comment]
@kevinmthomasse Sweet! @AlanZimmerman deserves all the glory for the UI.

**Comment by kevinmthomasse** [comment]
@Atlante45 @AlanZimmerman you both did great!  I like the UI and I like the seamless integration.  I can say without being long-winded, being an early alpha, this is something that I have wanted for a very long time.  This makes it simple and easy especially if you have worked hard to create an entire domain.  Well done!

**Pull request merged**
