### PR TITLE
fix away HMD unmouted logic

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- smoke test
- make sure away mode still works:
    - If you switch from desktop to HMD - you should automatically enter away mode
    - If you are in the HMD and you take your HMD off (Oculus CV1 or Vive) you should automatically go into away mode
    - If you are in HMD mode, and you alt-tab to another application, you should go into away mode

- Special test case (these tests fail in master/beta):
    - Run interface starting in HMD mode (note: you start out as not away), place the HMD on your head, then remove it... you should automatically go into away mode
    - Run interface in desktop, switch into HMD mode (notice you will go into away mode), BEFORE putting on the HMD press ESC to leave away, then put on HMD, then take off HMD -- you should automatically go into away mode

**Comment by hifi-gustavo** [comment]
Build console output for commit: c4a80996d5f7e2a6ce21fd31ce108734179cb881 available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-c4a8099.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-c4a8099.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64ee0e8ec3b77692f72253117f5e0885df2da5bb available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-64ee0e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-64ee0e8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e1ea5c57d2ed5acc89f708f95ec431900fd5515 available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-8e1ea5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-8e1ea5c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f7228993a5f6db2cbc185d6a601fe2386924baae available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-f722899.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-f722899.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a92507cf995d8266189247fc2935c0666caa466 available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-6a92507.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-6a92507.dmg

**Comment by PhilipRosedale** [comment]
QA Fail: 

Using the Vive, when I re-start interface in HMD mode, with the headset resting still on the desk, I do NOT startup in away mode.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3aa1c36f53f2ad2c6b9847e5154465ef695188b0 available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-3aa1c36.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-3aa1c36.dmg

**Comment by ZappoMan** [comment]
Ok - I figured out why sometimes we start up not in away mode... I will have a fix shortly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20c522a9bcfac069c96b83886bd7d0eb7f4eaf89 available at: https://gist.github.com/4169bad09aac3d8290693dee2683e4b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-20c522a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8654-20c522a.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: Unknown user
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Switch from desktop to HMD - automatically enter away mode usiing Oculus and in the HMD and took HMD off  automatically went into away mode
HMD mode, and you alt-tab to another application, went into away mode. Started interface with the display mode set to HMD, and the HMD was not mounted, immediately go into AWAY mode.

**Pull request merged**
