### PR TITLE
Beta Release 18 - Includes up to Developer Release 5228

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Fix depth state caching / resetting
* Better allocation of CPU time while loading scenes and when slow scripts are running
* Asset browser ui: Add dynamic and collision shape selection to add to world flow from asset browser. 
* Deferred batches: Part 1 of a project to migrate backend rendering execution off the main thread. This will cause all batches to be generated for a frame, and once the frame is complete, cause all the batches to be executed, rather than doing a per-batch build/execute 
* Tuned haptic pulses for grab, release, equip, de-quip on the Vive
* Fix alpha cut-outs and incorrect gamma on web overlays and entities
* Fixes a bug in `Assets.getMapping` where it wasn't providing the hash value back to the QML callback. 
* Groups: Permissions can be granted or revoked based on users' memberships in groups within the Domain Server security section.
* Add OverlayWebWindow resized, moved, and closed signals
* New Progress.js capability that corrects displays scene loading
* kick
 - add the ability to kick (via mod.js) 
 - add IP based permissions to domain-server settings 
 - Allow the ability to grant other users kick permissions. 
* If the oculus HMD isn't on someone's head, don't take input from the controllers
* Bug fix for avatar debug marker rendering.
* Tweak Teleport + Hand Lasers
* Added dead zones to Hydra and Oculus Touch joysticks

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2473bbf1db137691bd1dfe202ecf016d8cd4bc3a available at: https://gist.github.com/24592882efebad098e0f144b9e6c3c2a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8362-2473bbf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8362-2473bbf.dmg

**Comment by nbq** [comment]
testing now

**Comment by SkimiMission** [comment]
## QA Test
**QA Tester**: Skimi
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |4915 |2831 |2198
**GPU Buffer Count**: |822 |501 |500
**CPU Memory Usage**: |83116032 |49049600 |30871552
**GPU Memory Usage**: |25165824 |14262272 |12107776
**CPU Texture Count**: |251 |236 |139
**GPU Texture Count**: |783 |841 |765
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |361558428 |580008656 |85819856
**GPU Texture Memory Usage**: |560747540 |494667594 |345508822
**GPU Virtual Memory Usage**: |817147595|751067649|601908877
**Triangle Count**: |452100 |313217 |213662
**Triangle Rate**: |28256250 |19576062 |13353875
**API Drawcall Count**: |212 |150 |162
**Drawcall Count**: |299 |162 |163
**Drawcall Rate**: |18687 |10125 |10187
**State Changes Texture Count**:|214 |138 |129
**Pipeline Count**: |40 |40 |41
**Item Opaques**: |245 |296 |177
**Item Translucents**: |36 |29 |35
**Item Lights**: |21 |42 |27
**Timing Opaques**: |661 |836 |543
**Timing Translucents**: |28 |67 |64
**Timing Lighting**: |35 |70 |49
**Render Frame**: |1289 |1724 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok, in HMD no more as mx 60 fps
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|Fail - I just hear sounds from windows resize
**Test 4**|undefined|--
**Test 5**|Retest the kick function|Ok
**Test 6**|Switch avatar and make sure it does not crash|Ok
**Test 7**|Test group functions|Ok

I've noticed some rays, they seems - when in HMD - coming from the eyes. They also appears, if the HMD controller is off in desktop mode. See pics.

In HMD, I always got no more as ~60 fps on localhost, dev-playa and dev-demo. My Inet connection is around 35 Mbps at moment. 

The background sounds was only playing in localhost. On dev-playa I've heard no bg-sounds.

hifi-snap-by-skimi-on-2016-08-04_09-13-46

hifi-snap-by-skimi-on-2016-08-04_09-21-27

**Comment by Nex-Pro** [comment]
Testing on WIn10

**Comment by Nex-Pro** [comment]
**PR Build:** #8362
**RC18**

#### QA test.

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** Leap Motion

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: #### FAIL

**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |124 |4909 |4156
**GPU Buffer Count**: |72 |831 |865
**CPU Memory Usage**: |11710464 |87289856 |81747968
**GPU Memory Usage**: |9719808 |27578368 |47046656
**CPU Texture Count**: |49 |351 |352
**GPU Texture Count**: |513 |1709 |1886
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |20065352 |785291872 |511882992
**GPU Texture Memory Usage**: |57408260 |1254040781 |947787636
**GPU Virtual Memory Usage**: |234053508|1446491469|1140238324
**Triangle Count**: |132010 |891189 |760794
**Triangle Rate**: |8250625 |59412600 |47549625
**API Drawcall Count**: |18 |281 |251
**Drawcall Count**: |18 |343 |1152
**Drawcall Rate**: |1125 |22866 |72000
**State Changes Texture Count**:|38 |342 |297
**Pipeline Count**: |25 |46 |48
**Item Opaques**: |5 |436 |249
**Item Translucents**: |17 |56 |53
**Item Lights**: |0 |43 |26
**Timing Opaques**: |92 |2035 |1008
**Timing Translucents**: |72 |129 |152
**Timing Lighting**: |187 |128 |85
**Render Frame**: |1274 |3502 |2091

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Some problems with the changing room. Models became duplicated somehow. Even ones that I did not interact with. Image attached.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|No sounds heard.
**Test 4**|undefined|No test specified.
**Test 5**|Retest the kick function|Success
**Test 6**|Switch avatar and make sure it does not crash|Success
**Test 7**|Test group functions|Some issues found see notes.

#### Observations:

Groups: Adding a new group in domain-server settings page shows message ***"- Save and reload to see ranks"*** this differs from the green button which says ***"Save and restart"***

Situation arose whereby two avatars with identical permissions had differing experiences. Thoys was able to remain in the server while the other continuously connected and had permissions revoked.

Both accounts were the same rank in The_Beta_List (group)

My test account "TuxedoKittyNamedOreo" was on my lan but connecting via external IP.

Log snippet:

[08/04 14:42:29] [DEBUG] Refusing connection from node at 82.30.118.55:59967
[08/04 14:42:29] [DEBUG] Username signature matches for "TuxedoKittyNamedOreo"
[08/04 14:42:29] [DEBUG] Added "Agent" (I) {b3738141-49fc-49e9-9f38-bf13739c3036} 82.30.118.55:59967 / 192.168.0.7:59967 
[08/04 14:42:29] [DEBUG] Activating public socket for network peer with ID "b3738141-49fc-49e9-9f38-bf13739c3036"
[08/04 14:42:29] [DEBUG] Domain metadata users change detected
[08/04 14:42:38] [DEBUG] Domain metadata users set: QJsonObject({"num_anon_users":0,"num_users":3,"user_hostnames":{"*":3}})
[08/04 14:42:38] [DEBUG] node QUuid("{b3738141-49fc-49e9-9f38-bf13739c3036}") no longer has permission to connect.
[08/04 14:42:38] [DEBUG] Killed "Agent" (I) {b3738141-49fc-49e9-9f38-bf13739c3036} 82.30.118.55:59967 / 192.168.0.7:59967 
[08/04 14:42:38] [DEBUG] Domain metadata users change detected
[08/04 14:42:44] [DEBUG] Requesting public key for user "TuxedoKittyNamedOreo"
[08/04 14:42:44] [DEBUG] Refusing connection from node at 82.30.118.55:59967

Two images showing settings that triggerd the above are attached.


**Fish:** missing occasionally.(maybe Ryan forgot to feed them)

**Users.js:** Cannot reliably see other avatars listed.

**Comment by Nex-Pro** [comment]
**PR Build:** #8362
**Testing Architecture:** Desktop
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** OSX El Capitan
**HMD:** None
**Hand Controllers:** None

## QA Test
**QA Tester**: Piper.Peppercorn


**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** FAILURE
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: FAILURE
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: FAILURE

**Additional Test Results + Observations**: 

Fan switch had no effect in apartment.

Unable to move entities rezzed via ATP.
Also noticed that the vertical move arrows were not showing When entiies selected.

Harmonic oscillator failed. Cube appeared stationary in the disc.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |54
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |54
**CPU Buffer Count**: |122 |5297 |6742
**GPU Buffer Count**: |71 |1056 |1292
**CPU Memory Usage**: |8986624 |100503552 |155795456
**GPU Memory Usage**: |8282112 |62537728 |99438592
**CPU Texture Count**: |50 |387 |616
**GPU Texture Count**: |421 |1320 |1858
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |16984328 |218139328 |387292816
**GPU Texture Memory Usage**: |57322164 |1577184748 |2195947614
**GPU Virtual Memory Usage**: |259255732|1779118316|2397881182
**Triangle Count**: |125518 |887398 |782361
**Triangle Rate**: |7844875 |55462375 |48897562
**API Drawcall Count**: |21 |281 |256
**Drawcall Count**: |21 |339 |1157
**Drawcall Rate**: |1312 |21187 |72312
**State Changes Texture Count**:|37 |343 |295
**Pipeline Count**: |25 |42 |44
**Item Opaques**: |4 |425 |253
**Item Translucents**: |6 |30 |53
**Item Lights**: |0 |43 |27
**Timing Opaques**: |38 |1066 |707
**Timing Translucents**: |53 |72 |126
**Timing Lighting**: |19 |30 |26
**Render Frame**: |316 |2158 |1380


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Some problems.
**Test 3**|Go to Dev-Playa - Make sure you can hear the background sounds.|No sounds heard.
**Test 5**|Retest the kick function| Fail. No overlay shows above nearby avatar.
**Test 6**|Switch avatar and make sure it does not crash| Success
**Test 7**|Test group functions| Not fully tested.

**Pull request closed without merging**
