### PR TITLE
Print what to BugSplat log

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Trigger a bugsplat crash...somehow. Check the log that was sent over. The final line should read:
> EXCEPTION: description_of_crash

**Comment by huffman** [comment]
You can trigger a bugsplat from the developer menu (Developer > Crash > ...)

**Comment by zzmp** [comment]
test this please

**Comment by zzmp** [comment]
In that case, QA should trigger different crashes and make sure they all log an EXCEPTION before sending over the BugSplat.

**Comment by huffman** [comment]
FWIW, not all of them will be caught, but a majority of them should be.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e56da0a094c34c0058e1b0e7411ef2cb381ffd8 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e56da0a094c34c0058e1b0e7411ef2cb381ffd8 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c85516e926524a47c22b42637d5d8905a8d49f5 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 90aa1dafa3e3acf18e0b8ea9c7cf1480cb425b5d available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 962bff6bc2f35c9f3b9b788b8c29facc32944aab available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 359e794e27cf12a1d5ca1c78c82512dd78d7b614 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 005dc90b25786355bd88a2cb6ea01819de985f18 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d4e9a1bfc723a2fc4b1e4c300307ff079a1ecd5 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fb478dba52190067d6282e73340d91133ee4a499 available at: https://gist.github.com/37b5f87062df1ecd287ffd9ffb63dd6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7861.dmg

**Comment by zzmp** [comment]
@huffman @ZappoMan I can't figure this out, so I'm closing it. When I've got less on my plate I'll set up bugsplat locally and try again. If you want to try LMK and I'll show you what I've found.

**Pull request closed without merging**
