### PR TITLE
fix crash when hmd context menu triggers a modal

### PR DESCRIPTION
**Pull request by howard-stearns**
e..g., Open and Run Script dialog

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
- Enable Settings->Advanced Menus
- In Vive HMD, open the context menu (with either mouse right click or hand-controller menu button, which is above the trackpad).
- Select "Edit->Open and Run Script File...". It creates a file chooser. (At some point after this, master locks up and crashes.)
- Repeat any combination of this and "Open and Run Script from Url...", including multiple open dialogs, and closing them in any order.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68be819ea25eecc159d1034869098a2f8e125b91 available at: https://gist.github.com/2bb3066de299c734f9cc9150d60ce0b6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8144.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8144.dmg

**Comment by BingShearer** [comment]
**QA PASS**
**Notes**

- Tested using Howard's QA plan.
- Also seems to resolve issue at https://highfidelity.fogbugz.com/f/cases/981/Crash-when-clicking-out-of-URL-to-Script-dialog
- Works in Rift DK2 as well

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;q87rnl59&#x2F;31-open-and-run-script-dialog-crashes"> Open and Run Script dialog crashes</a>

**Pull request merged**
