### PR TITLE
Fix entity list selection failing when selecting entities not in list

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
# Test Plan

https://highfidelity.testrail.net/index.php?/cases/view/17767

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13143/HighFidelity-Beta-PR14041-72adfb7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13143/HighFidelity-Beta-PR14041-72adfb7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13143/HighFidelity-Beta-Interface-PR14041-72adfb7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13143/HighFidelity-Beta-PR14041-72adfb7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13143/HighFidelity-Beta-Interface-PR14041-72adfb7.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

PR test plan acts as expected. User is able to selected items not in the entity list once search radius is lowered.

**Pull request merged**
