### PR TITLE
Show MyAvatar's head in the SpectatorCamera view!

### PR DESCRIPTION
**Pull request by zfox23**
Woohoo!!!

**Test Plan:**
1. Enter HMD mode
2. Enable the Spectator Camera using the Tablet App
3. Point the camera at your face. Verify that your face shows up in the camera's viewfinder preview.
4. Enter Desktop mode
5. Go into third person mode. Verify that your head still renders.
6. Go into first person mode. Verify that your head doesn't render (i.e. you can't see the inside of your head in first person mode)

### CODE REVIEW

**Comment by zfox23** [comment]
[what to do about cauterized head?](https://trello.com/c/oktxxpnY/185-what-to-do-about-cauterized-head)

**Comment by OmegaHeron** [comment]
QA In progress

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/758/HighFidelity-Beta-PR10706-47e5fb56d3639956105489f1c18c43bdd6fdf807.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/758/HighFidelity-Beta-PR10706-47e5fb56d3639956105489f1c18c43bdd6fdf807.dmg

**Comment by howard-stearns** [comment]
code looks good to me, as long as @samcake is good with it.

**Comment by OmegaHeron** [comment]
Windows 10 - CV1+Touch controllers
Pass with caveats.  See notes below test framework checks.

Enter HMD mode
Enable the Spectator Camera using the Tablet App
Point the camera at your face. Verify that your face shows up in the camera's viewfinder preview.
^^ Pass

Enter Desktop mode
Go into third person mode. Verify that your head still renders.
Go into first person mode. Verify that your head doesn't render (i.e. you can't see the inside of your head in first person mode)
^^ Pass

I'm not going to fail over below -- it's not reliably reproducing, but, should be monitored in case it's not a one shot/isolated issue.

Issue with photo real male:  It had a pixelated "weirdness to it in viewfinder.  Captured in desktop and HMD mode.  Could it be subsurface scatter related?  That seems only substantial difference between it and my PBR based AV (no SS).

Repro;
Start in default sandbox
Complete tutorial
Bring up Spectator
Bring tablet back up
Go to Marketplace and switch to photo real male

hifi-snap-by--on-2017-06-15_15-12-12

Avatars used:  Default "Woody", My custom fuse based, Photo realistic male, ancient robot and tiny skeleton.

A secondary issue, I'm not sure is related to this PR...

Spectator on
Close its dialog
Open tablet
Goto marketplace
"Do stuff"
Nothing I could do would return me to primary table iconic display or menus.  -- I was stuck in MP and had to switch to Desktop at that point as I could do nothing needing tablet action (other than continue to browse MP).

**Comment by zfox23** [comment]
Oooh, thanks for the detailed notes @OmegaHeron. There are indeed some remaining issues with the secondary camera, one of which is a lighting bug - which may be related to the "weirdness" you saw. I will take a note of this.

**Comment by samcake** [comment]
Sometimes, i got to admit, a mode is cool

**Pull request merged**
