### PR TITLE
warnings fixes

### PR DESCRIPTION
**Pull request by ZappoMan**
Fixes to the following warnings:
* unix warnings about comparing enums
* windows linker warnings about obj not including any new symbols
* windows fixup_bundle warnings about not copying resolved items
* windows "glew" warnings in oculus.dll plugin
* mac/unix warnings about unused variable in legacy oculus plugin

### CODE REVIEW

**Comment by ZappoMan** [comment]
note: we could also just remove these .cpp files from the project, but since I think developers assume we need the cpp they might re-add it. I'm open to suggestions on how we'd like to handle this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43df5b55fe5adf6c3fefdc61c431225fe7587668 available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a08329d22cd094b984622ab575a898b6a1de78b available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 13e805ac15f4ccf8ccefc51e9d722344adc8b8e4 available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fe4a6fa2bf562cd4a7f954d7260012b28ba8966d available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9d60e803b566dbcd8ae00c98202d8fc96936a20 available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 92bcd9ca9eb583252b63fbcd0c397390521a5779 available at: https://gist.github.com/50a90e30979df1b8ebd0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6265.dmg

**Pull request merged**
