### PR TITLE
Migrate android build location to accommodate Quest builds

### PR DESCRIPTION
**Pull request by jherico**
This refactors our Android development somewhat to support building multiple Android apps in the near future.  

* The existing Android version of interface is moved from `android/app` to `android/apps/interface` 
* The `setupDependencies` pre-requisite Gradle task is no longer required.  All the functionality it used to implement has been moved to the Python prebuild script called by CMake.  
* The Gradle functionality to meddle with the output APK names has been removed.  Renaming is now done by the shell scripts executed by Jenkins. 
* The name of the Android app is now exposed as a preprocessor definition to the C++ code, so that the client can switch behavior depending not just on the OS, but which particular application is being built

## Testing

This PR will have no impact on the non-Android builds.  The pre-build script modifications are all within conditional blocks that only apply to android builds, and all other changed files are underneath the android folder.  The Android build should be tested to verify it's behavior is unchanged.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16189/HighFidelity-Beta-PR14652-3713027.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16189/HighFidelity-Beta-Interface-PR14652-3713027.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16189/HighFidelity-Beta-PR14652-3713027.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16189/HighFidelity-Beta-Interface-PR14652-3713027.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16332/HighFidelity-Beta-PR14652-d03b28c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16332/HighFidelity-Beta-Interface-PR14652-d03b28c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16333/HighFidelity-Beta-PR14652-d4dd783.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16336/HighFidelity-Beta-PR14652-490497c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16336/HighFidelity-Beta-PR14652-490497c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16336/HighFidelity-Beta-Interface-PR14652-490497c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16338/HighFidelity-Beta-PR14652-1ae808a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16338/HighFidelity-Beta-Interface-PR14652-1ae808a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16338/HighFidelity-Beta-PR14652-1ae808a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16338/HighFidelity-Beta-Interface-PR14652-1ae808a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16343/HighFidelity-Beta-PR14652-639985b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16343/HighFidelity-Beta-PR14652-639985b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16343/HighFidelity-Beta-Interface-PR14652-639985b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16343/HighFidelity-Beta-PR14652-639985b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16343/HighFidelity-Beta-Interface-PR14652-639985b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16465/HighFidelity-Beta-PR14652-61ea0de.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16465/HighFidelity-Beta-PR14652-61ea0de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16465/HighFidelity-Beta-Interface-PR14652-61ea0de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16465/HighFidelity-Beta-PR14652-61ea0de.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16465/HighFidelity-Beta-Interface-PR14652-61ea0de.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16486/HighFidelity-Beta-PR14652-0bd6f9e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16486/HighFidelity-Beta-PR14652-0bd6f9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16486/HighFidelity-Beta-Interface-PR14652-0bd6f9e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16486/HighFidelity-Beta-PR14652-0bd6f9e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16486/HighFidelity-Beta-Interface-PR14652-0bd6f9e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16518/HighFidelity-Beta-PR14652-1879cd3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16518/HighFidelity-Beta-Interface-PR14652-1879cd3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16518/HighFidelity-Beta-PR14652-1879cd3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16518/HighFidelity-Beta-Interface-PR14652-1879cd3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16523/HighFidelity-Beta-PR14652-605ebe5.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16527/HighFidelity-Beta-PR14652-13ce893.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16527/HighFidelity-Beta-PR14652-13ce893.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16527/HighFidelity-Beta-Interface-PR14652-13ce893.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16527/HighFidelity-Beta-PR14652-13ce893.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16527/HighFidelity-Beta-Interface-PR14652-13ce893.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16536/HighFidelity-Beta-PR14652-56dc2bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16536/HighFidelity-Beta-Interface-PR14652-56dc2bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16539/HighFidelity-Beta-PR14652-eff42b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16539/HighFidelity-Beta-Interface-PR14652-eff42b8.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16542/HighFidelity-Beta-PR14652-f552f8d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16542/HighFidelity-Beta-PR14652-f552f8d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16542/HighFidelity-Beta-Interface-PR14652-f552f8d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16549/HighFidelity-Beta-PR14652-a3e9ad9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16549/HighFidelity-Beta-PR14652-a3e9ad9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16549/HighFidelity-Beta-Interface-PR14652-a3e9ad9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16549/HighFidelity-Beta-PR14652-a3e9ad9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16549/HighFidelity-Beta-Interface-PR14652-a3e9ad9.exe

**Comment by gcalero** [comment]
Just tested the latest build - HighFidelity-Beta-PR14652-a3e9ad9.apk - and it loads in Pixel 2 with Android 9 as well as Samsung S8 running Android 8

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
