### PR TITLE
Fix potential map.json corruption in Asset Server

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11095/HighFidelity-Beta-PR13535-23a2794.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11095/HighFidelity-Beta-PR13535-23a2794.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11095/HighFidelity-Beta-Interface-PR13535-23a2794.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11095/HighFidelity-Beta-PR13535-23a2794.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11095/HighFidelity-Beta-Interface-PR13535-23a2794.exe

**Comment by huffman** [comment]
# Test Plan

 * https://highfidelity.testrail.net/index.php?/cases/view/19059

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11244/HighFidelity-Beta-PR13535-23a2794.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11244/HighFidelity-Beta-PR13535-23a2794.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11244/HighFidelity-Beta-Interface-PR13535-23a2794.dmg

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11360/HighFidelity-Beta-PR13535-23a2794.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11360/HighFidelity-Beta-PR13535-23a2794.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11360/HighFidelity-Beta-Interface-PR13535-23a2794.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11360/HighFidelity-Beta-PR13535-23a2794.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11360/HighFidelity-Beta-Interface-PR13535-23a2794.exe

**Comment by qlimnavarro** [comment]
Currently Testing
@huffman If possible could you link the ticket associated with this fix?

**Comment by qlimnavarro** [comment]
Pass @Qliemillar 
File remains.

**Comment by huffman** [comment]
@qlimnavarro Yes, it is here: https://highfidelity.fogbugz.com/f/cases/16431/Corrupt-map-json

Thank you for testing!

**Pull request merged**
