### PR TITLE
Case 21230: work around vive crash

### PR DESCRIPTION
**Pull request by sethalves**
https://highfidelity.manuscript.com/f/cases/21230/Vive-HMD-cannot-launch-Crash

- work around vive crash

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17317/HighFidelity-Beta-PR14929-ae0d777.apk

**Comment by sethalves** [comment]
premerge test: run on a machine with a vive, and switch to HMD mode

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17317/HighFidelity-Beta-PR14929-ae0d777.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17317/HighFidelity-Beta-Interface-PR14929-ae0d777.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17317/HighFidelity-Beta-PR14929-ae0d777.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17317/HighFidelity-Beta-Interface-PR14929-ae0d777.exe

**Comment by jherico** [comment]
I have a slightly different fix incoming

**Comment by sethalves** [comment]
closing in favor of https://github.com/highfidelity/hifi/pull/14931

**Pull request closed without merging**
