### PR TITLE
Fix MS20208: Change an instance of 'ASSETS' to 'INVENTORY'

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS20208](https://highfidelity.manuscript.com/f/cases/20208/wrong-language-in-HMD-UI-change-from-asset-to-inventory).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15801/HighFidelity-Beta-PR14550-4cc5fc7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15801/HighFidelity-Beta-PR14550-4cc5fc7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15801/HighFidelity-Beta-Interface-PR14550-4cc5fc7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15801/HighFidelity-Beta-PR14550-4cc5fc7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15801/HighFidelity-Beta-Interface-PR14550-4cc5fc7.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlilaseguinolaza** [comment]
PR14550 PASS
In HMD mode going to Settings>Security when wallet is not yet set up, correctly states under Secure Transactions to open INVENTORY app.

**Pull request merged**
