### PR TITLE
Fix the jittering reflection bug and more Normal improvments

### PR DESCRIPTION
**Pull request by samcake**
This PR fixes the bug bugzid:500

- We changed the normal deferred buffer from eye space to world space which improved  a lot the precision of the reflected normal computation.

- We improved the quality of the packing/unpacking  algorithm of the normal on 24bits by using an  oct24 algorithm as suggested in this survey: http://jcgt.org/published/0003/02/01/
 This improves the previous technique we were using (Crytek Best Fit Normal) within the same storage footprint of 24bits and without having to bind an extra texture.
We will probably try to go one step further using RGB10_A2 trying to pack the encoding in 20bits but we didn't want to change too many things in one go.

- Doing so we found a bug in the color format used for normal buffer that has been introduced when improving the color rendering (sRGB), this is now fixed in this PR, the Normal Buffer is a LInear RGBA32.

### CODE REVIEW

**Comment by samcake** [comment]
To Test:
test 0
1) Run interface, enter HMD, go to hifi://forum
2) look at the Cellscience poster on the wall
3) notice that you can see the city skybox in a faint reflection in the glass covering the poster
4) notice that the reflection shakes alot in Master, not anymore in this build

test 1
Go to  hifi://blue
Look at the golden, mirror like sphere at /-21.0,0.3,-25.0
the reflection of the skymap is much cleaner in this PR compared to the master where it s very noisy
capture-reflection-7995
capture-reflection-4968

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7de5b80179b73aa3462f087b5dad4b88b6e165a7 available at: https://gist.github.com/cee1a582b8e69ba29793b5e494816964<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7995.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7995.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7de5b80179b73aa3462f087b5dad4b88b6e165a7 available at: https://gist.github.com/cee1a582b8e69ba29793b5e494816964<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7995.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7995.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Cellscience poster in ```forum``` successfully viewed city skybox covering the poster as a reflection. Went to ```blue``` golden, mirror like sphere at /-21.0,0.3,-25.0 the reflection of the skymap is very clean.

**Comment by ZappoMan** [comment]
My quick test also shows the jitter in the poster and the lights reflecting on the wood paneling to have gone away! Good Job!

**Pull request merged**
