### PR TITLE
Fix avatar displayname to point towards camera

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: abe8cfe90fda01e13fa10ac60dd53726dc27446a available at: https://gist.github.com/65573dfc79b5089ca55f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 760a5bfa37feca4b0ba9f4e6fc03893193fbc1c0 available at: https://gist.github.com/b0681a90a0d39a13a145<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.dmg

**Comment by ZappoMan** [comment]
I just tested this build vs the current production build - and I don't see a difference in behavior... they both appear to make the avatar display name rotate to face the camera... how does this PR improve things?

**Comment by Atlante45** [comment]
Yes, what it changes is that it rotate with your camera position and not your camera orientation.
I think @huffman is right that this is a better design. That way if you stay in the same spot and rotate your view, the display name will stay fixed.

**Comment by Atlante45** [comment]
@ZappoMan Duh, I didn't even think about that. The reason I had it rotate it that way is to be aligned in the z-plane, which means the text keeps the same pixels size over each glyph and it allows us to pixel align the font.
This might not be the best design (Could be annoying in HMD?) but that's how we get a better text rendering.

**Comment by Atlante45** [comment]
@huffman I think we're gonna pass on that one. The tilting is not really noticeable on HMD and it keeps the text a lot clearer. Especially on the sides of the screen.

**Comment by ZappoMan** [comment]
@PhilipRosedale check out this PR's behavior... I think it actually DOES implement what you want it to do.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 760a5bfa37feca4b0ba9f4e6fc03893193fbc1c0 available at: https://gist.github.com/b0681a90a0d39a13a145<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5218.dmg

**Pull request merged**
