### PR TITLE
Edit handle rotation ring size

### PR DESCRIPTION
**Pull request by dback2**
Small tweak to the rotation ring size to make them easier to grab. Didn't want to make them too big so will see if this change is enough.

Addresses: https://highfidelity.manuscript.com/f/cases/17466/

Test Plan:
- Ensure you have the Environment Variable HIFI_ALLOW_MULTIPLE_INSTANCES set to 1 in system properties to allow for 2 High Fidelity Interfaces to run simultaneously
- Open an Interface in desktop mode from both this PR and any other build
- Open Create in both Interfaces and select an entity
- Compare the rotation ring sizes between this PR and the other build and verify they are slightly bigger in this PR
- Stress test grabbing all 3 rotation rings from different angles/distances and verify they are always grabbable

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11989/HighFidelity-Beta-PR13797-cc953ab.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11989/HighFidelity-Beta-PR13797-cc953ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11989/HighFidelity-Beta-Interface-PR13797-cc953ab.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Rings are now slightly bigger
createcomp

**Pull request merged**
