### PR TITLE
added package-lock file for server console, remove electron-compilers

### PR DESCRIPTION
**Pull request by birarda**
- added the package-lock.json file from npm install

### CODE REVIEW

**Comment by birarda** [comment]
The added file performs the same task as `Gemfile.lock` does for bundler in our ruby stacks. 

From https://docs.npmjs.com/files/package-lock.json:
It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5530/HighFidelity-Beta-PR11956-d81e87771bd3e7d970840284a97297063d6acd26.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5533/HighFidelity-Beta-PR11956-1f54b1fcc311e4351f00ec047c84c825b9181a6d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5533/HighFidelity-Beta-PR11956-1f54b1fcc311e4351f00ec047c84c825b9181a6d.dmg

**Comment by birarda** [comment]
#### Test Notes

1. Smoke test the Sandbox from this PR. Ensure it runs and that you can see the domain-server and assignment-client logs by clicking on the menu item for the Sandbox.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test |  Result
--- | ---
Smoke test the Sandbox from this PR. Ensure it runs and that you can see the domain-server and assignment-client logs by clicking on the menu item for the Sandbox. | Pass

Everything looks normal and works as expected. Logs do show assignment-client & domain-server.

**Pull request merged**
