### PR TITLE
9264 dismiss keyboard after user finished typing in marketplace searc…

### PR DESCRIPTION
**Pull request by ElderOrb**
…h bar and hit search or return key

**Test plan**

1. Switch to VR
2. Open tablet, go to marketplace
3. Type 'hello' in the search field
4. Press search button
5. Ensure search executed & keyboard collapses
6. Type 'hello' in the search field
7. Click 'return' button on virtual keyboard
8. Ensure search executed & keyboard collapses
9. Type 'hello' in the search field
10. Click 'return' or 'enter' button on physical keyboard
11. Ensure search executed & keyboard collapses

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4967/HighFidelity-Beta-PR11820-78d89d886feae4f179cdf0af7b348607d9e7d4b4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4967/HighFidelity-Beta-PR11820-78d89d886feae4f179cdf0af7b348607d9e7d4b4.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Switch to VR | Pass
Open tablet, go to marketplace | Pass
Type 'hello' in the search field | Pass
Press search button | Pass
Ensure search executed & keyboard collapses | Pass
Type 'hello' in the search field | Pass
Click 'return' button on virtual keyboard | Pass
Ensure search executed & keyboard collapses | Pass
Type 'hello' in the search field | Pass
Click 'return' or 'enter' button on physical keyboard | Pass
Ensure search executed & keyboard collapses | Pass

**Comment by changxc** [comment]
thank you!!

**Pull request merged**
