### PR TITLE
Fix CPU and GPU not throttling when Interface minimized from maximized

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
https://highfidelity.fogbugz.com/f/cases/11699

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Using current master or release build on Windows, reproduce the problem so that you know what you're looking for:
a) Interface window windowed (i.e., not maximized). Note the CPU and GPU utilization in Windows' Task Manager graphs.
b) Minimize the Interface window. The CPU and GPU utilizations significantly reduces.
c) Maximize the Interface window. The CPU and GPU utilizations go up again.
d) Minimize the Interface window (direct from maximized state). The CPU and GPU utilizations do NOT significantly reduce.

2) Repeat the tests in 1) with the PR build on Windows.
a) - c) should the the same.
d) The CPU and GPU utiliziations should significantly reduce when the Interface window is minimized from being maximized.
e) Restore the Interface from d) and the CPU and GPU utilitizations should increase again and Interface should be usable as normal.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7966/app_12621_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7966/HighFidelity-Beta-PR12621-3001225cb723a4526e7a680e32e0a7730ce82437.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7966/HighFidelity-Beta-PR12621-3001225cb723a4526e7a680e32e0a7730ce82437.exe

**Comment by qlimnavarro** [comment]
Currently testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
After minimizing from a maximized state the interface's CPU and GPU usage drops very significantly.

**Pull request merged**
