### PR TITLE
Hud module. check if laser is pointing at UI element without moving the reticle first

### PR DESCRIPTION
**Pull request by druiz17**
Before to check is some intersection point is on an UI element you needed to first move the reticle. In this PR a created a function that allows you to properly check if the intersection point is on an UI element

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- In HMD mode open the debug logs window (located in developer menu)
- make sure that the laser can interaction with the window
- when the laser appears off the window...when you move the laser onto the window...the laser should be on the window and not going through it.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3832/HighFidelity-Beta-PR11509-86f580919c5d42f1ebf3f3130b86aa75e48e190e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3832/HighFidelity-Beta-PR11509-86f580919c5d42f1ebf3f3130b86aa75e48e190e.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In HMD mode open the debug logs window (located in developer menu) **Check**
make sure that the laser can interaction with the window **Check**
when the laser appears off the window...when you move the laser onto the window...the laser should be on the window and not going through it. **Check**

**Pass**

**Pull request merged**
