### PR TITLE
Fix tabbing behavior in edit.js

### PR DESCRIPTION
**Pull request by imgntn**
This PR fixes the behavior when using the tab key to switch between fields in edit.js

Previously, you couldn't go to a field like dimensions in entity properties and change it with the sequence "1 tab 1 tab 1".  Now you can quickly edit properties since the entire field is selected after the change.

To test:

1. Open edit.js
2. Create a cube.
3. Go to its properties page and find the dimensions fields.
4. Click in the x-field and then use this key sequence: 1 tab 1 tab 1
5. You should have a one meter cube.
6.  Test changing some other properties to make sure they still work as expected when using tab.

https://highfidelity.fogbugz.com/f/cases/830/Inconsistent-and-non-standard-behaviour-of-tab-key-in-edit-js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 188590a891010e44b0b5c188f3095db3a7af0498 available at: https://gist.github.com/8ae0a2adef07238d36d8685504cfd172<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8056.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8056.dmg

**Comment by huffman** [comment]
Does this ever cause issues where moving from, say, position.x to position.y, and you start to change the value quickly, it gets overwritten with the latest value?

**Comment by imgntn** [comment]
haven't seen that issue myself

**Comment by hifi-gustavo** [comment]
Build console output for commit: 188590a891010e44b0b5c188f3095db3a7af0498 available at: https://gist.github.com/8ae0a2adef07238d36d8685504cfd172<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8056.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8056.dmg

**Comment by Nex-Pro** [comment]
###PASS
Thanks for getting on my bug report so quickly and nailing it. This works great. Shift Tab also works correctly.

I was able to quickly set coarse size and rotations etc. using just the tab and arrow keys. 

Q: Should this tab past the behaviour checkbuttons ? Maybe we could also tab those and invert with spacebar.

**Pull request merged**
