### PR TITLE
DNM: interface client to test PR11811

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4954/HighFidelity-Beta-PR11818-feb12648c4eb865cfd8f60064225686a5e071682.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4962/HighFidelity-Beta-PR11818-feb12648c4eb865cfd8f60064225686a5e071682.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4962/HighFidelity-Beta-PR11818-feb12648c4eb865cfd8f60064225686a5e071682.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4972/HighFidelity-Beta-PR11818-c6673432d46fb769eebf39ebd3ca9f778f825963.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4982/HighFidelity-Beta-PR11818-c6673432d46fb769eebf39ebd3ca9f778f825963.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4982/HighFidelity-Beta-PR11818-c6673432d46fb769eebf39ebd3ca9f778f825963.dmg

**Pull request closed without merging**
