### PR TITLE
QML fixes

### PR DESCRIPTION
**Pull request by jherico**
* Fix bad window title on windows without close icons (Avatar attachments dialog had title cut off)
* Move add/edit friends webview to QML
* Set some desirable webengine settings globally

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc7fda0ae9c69f6153d1fc6b56a19009a01fe440 available at: https://gist.github.com/3a565b8508d0b8fb422c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7018.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7018.dmg

**Comment by nbq** [comment]
Testing this one now

**Comment by nbq** [comment]
Tested new users.js and the new qml add/remove friends. The window showed up at first but when I tried to add a new friend it asked me to sign in and then it took me to the main hifi web page within the tiny window. I had to close the add/remove friends window then reopen it for it to let me add anyone after I had signed in before.

**Comment by jherico** [comment]
@nbq The authentication issue is a known problem that has to be solved on the server side, and will probably be fixed later today.

**Comment by nbq** [comment]
Then I say it PASSED just fine. I like the new dialog!

**Pull request merged**
