### PR TITLE
Use third person camera mode when switching to My View from Top View mode.

### PR DESCRIPTION
**Pull request by Cristo86**
This makes it consistent with the default third person camera in My View.

Test plan:

- Start App
- Enter a domain, by default it should be in third person
- Go to Top View Mode clicking the "My View" eye button
- Click again the button to return to "My View"
- Resulting Camera should be in third person (previously it was first person at this step).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10425/HighFidelity-Beta-PR13325-664884c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10425/HighFidelity-Beta-PR13325-664884c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10425/HighFidelity-Beta-Interface-PR13325-664884c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10425/HighFidelity-Beta-PR13325-664884c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10425/HighFidelity-Beta-Interface-PR13325-664884c.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Android interface never goes into first person when selecting the "My View" eye button. No new defects introduced on desktop Interface

**Pull request merged**
