### PR TITLE
Beta Release 10 - includes up to Developer Release 4855

### PR DESCRIPTION
**Pull request by ZappoMan**
- fix issue with user stats in metaverse reporting
- add back users.js
- fix bug where similarly named FBX models would reuse each others textures
- use reliable and ordered packets for avatar identity
- fix crash in physics
- improved windows cpu usage
- fix bug preventing simulation ownership release
- home dressing room updates
- fix object position glitch of owned simulations on networks with long ping-time
- fix crash when calling Entities.callEntityMethod()
- add warnings for socket error and unexpected state change
- fix a crash in ScriptEngine when changing domains
- fix log flood on missing GPU pipeline
- improvements to Cell Science content
- fix to OSX compile warnings
- fix the placement of GUI for dice example
- improve translucent shapes global lighting with support for the ambient map reflection
- allow scripts on the web to refer to local libraries with /~/
- fix to sRGB color convversions
- fix to shutdown of interface when there are long running or looping scripts
- fix to crash in script engine
- new scripting interface to allow prefetch of cached resources
- fix to far grab with smoother simulation and rendering of actions
- new Interface "Home" bookmark function
- fix to crossed eyes effect when face to face with avatars
- fix to crash on missing GPU pipeline
- fix to UI Toolkit border styles for various dialogs
- move cellscience to production s3 bucket

### CODE REVIEW

**Comment by cozza13** [comment]
For testing, please go through these documents. If you do not have a device needed just let us know in your notes and keep testing the other areas. 

https://docs.google.com/document/d/1--HPq5vXze76OcPxAg9c4R7UQtQlaB4uupKOSDbLYMk/edit
https://docs.google.com/spreadsheets/d/1NbQFi-h59D6PFAIcLR7UfXLJUy9Tym-quTzeEiEmQbE/edit?ts=572a8b5b#gid=0

**Comment by hifi-gustavo** [comment]
Build console output for commit: b234d94d255c7389e70f29b1796f2b9108fe9c8a available at: https://gist.github.com/b009e2c5e21460d9217e38bde6e1e654<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7835.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7835.dmg

**Comment by nbq** [comment]
**PR Build: 7835**
**Testing Architecture: x64 PC**
**Testing OS: Windows 10** 
**Testing Locations: Playa, cellscience, forum **
**Smoke Test Results: Passed** 
**QA Status:** Pass  

                                  | playa | cellscience | forum   
----------------------------------|-------|-------------|--------
Render Rate:                      | 59.99 | 59.97       | 60.36            
Present Rate:                     | 59.95 | 59.95       | 59.95            
Simrate:                          | 59    | 59          | 60           
Render Stats Num Buffers:         | 5922  | 4371        | 7423             
Render Stats gpu::Buffer Memory:  | 98.7MB| 50MB        | 78.7MB             
Render Stats Num Textures:        | 438   | 116         | 374             
Render Stats gpu::Texture Memory: | 3387.7MB| 544.8MB   | 2396.1 MB             
Render Stats Triangles:           | 694K  |   218K      | 1166K            
Render Stats Drawcalls:           | 1225  |   316       | 572            
Render Stats Items:               | 304   |   102       | 552             

**sandbox ‘createtestblocks.js’ Result: Passed **
**sandbox Import FBX Result: Passed**
**sandbox ‘harmonicOscillator.js’ Result: Passed**
**sandbox Echo Server Audio Result: Passed**
**sandbox ‘reverbTest.js’ Result: Passed**
**Successful Logout/Crash (If A Crash Occurs, Attach ‘hifi-log.txt’): No crash on logout**

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7835
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.
**QA Status:** Pass/Fail

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |59.98     |59.99    |53.11       
Present Rate:                     |60.00     |60.00    |60.00       
Present New Rate:                 |60.00     |60.00    |54.10      
Render Stats Num Buffers:         |5089      |5800     |2343       
Render Stats gpu::Buffer Memory:  |39.1Mb    |168.5Mb  |20.5Mb      
Render Stats Num Textures:        |302       |469      |119          
Render Stats gpu::Texture Memory: |906.0Mb   |2085.3Mb |288.2Mb     
Render Stats Triangles:           |524k      |817k     |460k       
Render Stats Drawcalls:           |609       |290      |151         
Render Stats State Changes:	  |253       |236      |106          
Render Stats Items:               |307       |349      |730        
Render Stats Timing:              |20.2ms    |60.8ms   |21.8ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |233Mb     |233Mb    |233Mb       
GPU-Z Memory Used		  |2238Mb    |2790Mb   |1248Mb      
GPU-Z Memory Load		  |24%       |30%      |14%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results/Observations:** (none)
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Comment by OmegaHeron** [comment]
Server side tests for Linux all good.
Windows testing shows improvement over last RC on both my laptop i7 CPU + GTX660M and desktop i5 CPU + GTX970.  Running with i5 and having a good experience requires paring down running scripts to dead minimum, but, that's hopefully going to improve moving forward.  Right? :)  I did a series of xperf + Windows Performance Analysis runs and I won't clog this with a million graphs, but, it looks overall better there - confirming the feel of it in use.  Running through test list I saw similar results to nbq and Kevin reports.  Nothing stood out as obviously borked.

**Comment by Triplelexx** [comment]
Been running this over the weekend, no real problems. Performance does seem better. Not the best candidate for testing with my current setup, but another pass, for what it's worth.

**Pull request merged**
