### PR TITLE
FB19355 - When I have avatar entities as children of my avatar, the A…

### PR DESCRIPTION
**Pull request by ElderOrb**
…vatar app is not consistent in displaying wearables

https://highfidelity.fogbugz.com/f/cases/19355/When-I-have-avatar-entities-as-children-of-my-avatar-the-Avatar-app-is-not-consistent-in-displaying-wearables

Note: the issue is already partially fixed in master by other PRs. This PR adds correct presentation for such a wearables in wearables combobox. 

**Test plan**

1. Launch interface
2. Extract and drag&drop 1.json file into interface to apply wearables. 
[1.zip](https://github.com/highfidelity/hifi/files/2650575/1.zip)
3. Ensure avatar got 'bubble' wearable with animated cats inside .
4. Launch avatarapp, go to adjust wearables
5. Ensure both 'bubble' and 'cats' wearables are adjustable and visible in combobox.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15692/HighFidelity-Beta-PR14538-090bc4f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15692/HighFidelity-Beta-PR14538-090bc4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15692/HighFidelity-Beta-Interface-PR14538-090bc4f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16006/HighFidelity-Beta-PR14538-090bc4f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16006/HighFidelity-Beta-PR14538-090bc4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16006/HighFidelity-Beta-Interface-PR14538-090bc4f.dmg

**Comment by qliejahner** [comment]
Build this please

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16058/HighFidelity-Beta-PR14538-090bc4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16058/HighFidelity-Beta-Interface-PR14538-090bc4f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16058/HighFidelity-Beta-PR14538-090bc4f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16058/HighFidelity-Beta-Interface-PR14538-090bc4f.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
PASS

Extracted and loaded via drag and drop the 1.json file. The thought bubble and image appear (image visible from front) and show as wearable. Can adjust in wearable app with both items. PR Passes.

**Pull request merged**
