### PR TITLE
Outline effect

### PR DESCRIPTION
**Pull request by Zvork**
# Description
This PR introduces a prototype outline effect on model items. This can be used to highlight selected objects by adding a colored outline around an object's silhouette as well as filling the object's silhouette with a constant color. The opacity of that fill effect can be different whether the object's silhouette is occluded or not by another element of the scene.

# Visualizing the effect
At this time the effect is apparent only if you open and run the _debugOutline.js_ script which can be found in _scripts/developer/utilities/render/_. This will open up an editing window and enabling the "Edit Outline" checkbox wil apply the effect to the nearest model item in front of the camera.

# Effect parameters
Various parameters are available in the editing window (see paragraph above to display that window) to tweak the effect:

- **Glow** : this switches the effect from a thick outline to a blurred glow
- **Width** : this controls the width of the outline and glow
- **Intensity** : this controls the intensity of the outline and glow
- **Color** : this controls the color of both outline / glow and fill
- **Fill Opacity** : this controls the opacity of the fill color for unoccluded and occluded parts with different settings for both.
- View outlined depth : this is used for debugging purposes and displays a view of the outlined object's Z-depth values without any other object and isn't part of the test plan.

# TEST PLAN
The test plan should be done with the effect activated and edit window displayed as described in paragraph "Visualizing the effect". It should also be executed on various GPU platforms and with HMD.

### NOTE : about picking
Please note that the actual picking behaviour ISN'T part of the test plan. It is only for testing purposes and to be able to visualise the outline effect on various objects. In its actual state, the picking isn't perfect. If an imported objects is made up of many meshes, the picking will pick out only one of them, for instance.

1. With the "Edit Outline" checkbox enabled, a model item in front of the camera should have the outline effect applied to it.
2. Unchecking the "Edit Outline" checkbox should remove the outline effect.
3. If another object is "outlined" due to camera movement, for instance, the previous object should have it's outline effect removed.
4. With the "Glow" checkbox unchecked, an object outlined should have a line of constant color completely around the object's silhouette extending outside the object. If the silhouette has holes, the outline should also be seen around these holes extending outside the object.
5. With the "Glow" checkbox checked, an object outlined should have a glow of constant color  completely around the object's silhouette. If the silhouette has holes, the glow should also be seen around these holes extending towards the outside of the object.
6. Moving the "Width" slider should change the width of the outline or glow while still keeping it outside the object.
7. Moving the "Intensity" slider should change the opacity of the outline or glow.
8. Moving the three color sliders should change the color of the outline or glow as well as the fill effect accordingly
9. Moving the "Unoccluded" slider in the "Fill Opacity" section should change the opacity of the fill effect only on the parts of the silhouette that are NOT behind not outlined objects.
10. Moving the "Occluded" slider in the "Fill Opacity" section should change the opacity of the fill effect only on the parts of the silhouette that are behind not outlined objects.
11. Changing the aspect ratio of the application window should not modify the aspect of the outline or glow. It's relative width should remain constant.
12. The effect should work identically on various GPU platforms (AMD, Intel, NVidia)
13. The effect should work in stereo and HMD view.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2410/HighFidelity-Beta-PR11160-f88141aa31319a2d567276df15d52ecff9b5bd58.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2410/HighFidelity-Beta-PR11160-f88141aa31319a2d567276df15d52ecff9b5bd58.exe

**Comment by anshuman64** [comment]
@Zvork is this ready to test?

**Comment by Zvork** [comment]
@anshuman64 Yes absolutely

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
## Tested on Win10 with i7 4ghz and Nvidia GTX1070 8gb.


### Fail on my system due to rendering artifacts not seen in any previous build.

***To repro arrange your view to be close to that shown in screenshots.***

With the "Edit Outline" checkbox enabled, a model item in front of the camera should have the outline effect applied to it. **PASS**
Unchecking the "Edit Outline" checkbox should remove the outline effect. **PASS**
If another object is "outlined" due to camera movement, for instance, the previous object should have it's outline effect removed. **PASS**
With the "Glow" checkbox unchecked, an object outlined should have a line of constant color completely around the object's silhouette extending outside the object. If the silhouette has holes, the outline should also be seen around these holes extending outside the object. **PASS**
With the "Glow" checkbox checked, an object outlined should have a glow of constant color completely around the object's silhouette.  **PASS**
If the silhouette has holes, the glow should also be seen around these holes extending towards the outside of the object. **PASS**
Moving the "Width" slider should change the width of the outline or glow while still keeping it outside the object. **PASS**
Moving the "Intensity" slider should change the opacity of the outline or glow. **PASS**
Moving the three color sliders should change the color of the outline or glow as well as the fill effect accordingly **PASS**
Moving the "Unoccluded" slider in the "Fill Opacity" section should change the opacity of the fill effect only on the parts of the silhouette that are NOT behind not outlined objects. **PASS**
Moving the "Occluded" slider in the "Fill Opacity" section should change the opacity of the fill effect only on the parts of the silhouette that are behind not outlined objects. **PASS**
Changing the aspect ratio of the application window should not modify the aspect of the outline or glow. It's relative width should remain constant.
The effect should work identically on various GPU platforms (AMD, Intel, NVidia) **TESTED on NVIDIA GTX1070**
The effect should work in stereo and HMD view. **PASS**

**Good stuff:**

This will be useful.

This even works for animated entities such as the airplane at dev-welcome.

**Issues seen:** 

Strange rendering artifacts in desktop mode please see screengrabs.

All artifacts in upper right quarter of screen grabs.

It can be tricky to highlight any specific entity if that entity is in close proximity to or within the bounding box of another.

Also highlights the tablet. 

hifi-snap-by--on-2017-08-10_21-10-02
hifi-snap-by--on-2017-08-10_21-06-10
hifi-snap-by--on-2017-08-10_21-08-25
hifi-snap-by--on-2017-08-10_21-09-49


@Zvork I really would have liked to pass this.

**Comment by Nex-Pro** [comment]
Artifacts only occur within the highlight created by the script in this build.

**Comment by tapalisa** [comment]
I tried this with several google blocks objects and noticed that the effect was applied only to parts of the item. I would have expected the entire thing to have the effect applied since the objects aren't editable within High Fidelity

image

**Comment by Zvork** [comment]
@Nex-Pro First of all, about the difficulty to pick objects, sometimes, and the fact that the tablet is highlighted, these are both the same "issues". I should have been clearer (I'll edit the description) that this PR isn't about the picking really. The picking is just here to be able to visualise the outline effect and thus is here for debugging / testing purposes. So in its actual state it is quite rudimentary and could be much improved. I'll update the test plan about this.

**Comment by Zvork** [comment]
@Nex-Pro As for the rendering artefacts on your Nvidia card... that is more serious and I had anticipated potential problems like that. I'll try to reproduce it.

**Comment by Zvork** [comment]
@tapalisa I'm pretty sure this is a picking issue (I've edited the PR description about that adding that the actual picking behaviour isn't part of the test plan) and not an outline issue but I'll take a look nonetheless. Do you have an URL to this particular model?

**Comment by Zvork** [comment]
@Nex-Pro @tapalisa Is the effect comfortable in HMD mode?

**Comment by Zvork** [comment]
@Nex-Pro I've just pushed an update that should (hopefully) fix your GPU issues in desktop mode. I had a similar problem on some occasions on my NVidia GPU (while not as bad) and this has fixed it.

test this

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2442/HighFidelity-Beta-PR11160-d86c3c4f2af1924ac5af29538d7249341747aa06.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2442/HighFidelity-Beta-PR11160-d86c3c4f2af1924ac5af29538d7249341747aa06.dmg

**Comment by Nex-Pro** [comment]
Retesting.

**Comment by Nex-Pro** [comment]
Rendering artifacts are now absent.
Pass on test criteria.

Please look at this image. I could not work out why the highlighted object was picked.
hifi-snap-by-piper-peppercorn-on-2017-08-12_17-40-20

It is completely occluded by geometry in front and not near the centre of the view. (including unhighlighted parts of that model.)

**Comment by Zvork** [comment]
The picking is based on the bounding box of the objects. If you're inside an object's bounding box, picking will not pick out that object. So that excludes all the building meshes from the picking as you are inside it. The object picked has probably a big bounding box with corners that intersect with the center of the window. This is just a theory.
But again, the picking isn't part of the PR test plan and is here only to help "debug / visualize" the outline effect. It isn't a user feature of any sort more of a dev tool to help debugging so don't worry yourself too much about that.

**Comment by tapalisa** [comment]
@Zvork Any google blocks model I used had the issue of it picking the meshes separately. 
https://vr.google.com/blocks/
If that's not part of this test plan I understand. 

However, today when I tried the latest build I was unable to get the outline visual to show unless I had "view outline depth" checked. 

image

image

So, I wasn't able to test the comfort level in HMD.

**Comment by themelissabrown** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2493/HighFidelity-Beta-PR11160-d86c3c4f2af1924ac5af29538d7249341747aa06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2493/HighFidelity-Beta-PR11160-d86c3c4f2af1924ac5af29538d7249341747aa06.exe

**Comment by changxc** [comment]
I cannot find the  debugOutline.js script under scripts/developer/utilities/render/ anymore. anywhere i can get a copy of the script? thank you!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2566/HighFidelity-Beta-PR11160-1e4cf5d7971bda5395f32e3a3d3d909578cb9251.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2566/HighFidelity-Beta-PR11160-1e4cf5d7971bda5395f32e3a3d3d909578cb9251.exe

**Comment by Zvork** [comment]
@tapalisa I've tried with a code block object (a lamppost object at this URL https://vr.google.com/objects/7IgH6j3-4OE) that I've created as a model in a sandbox and although it is difficult to pick (but again, this is not the issue for this PR) I have managed (by finding a right camera angle) to pick it and outline it. If the "View Outline Depth" displays a silhouette then it indicates that something has been picked and that the outline effect is applied to it. If you do not see the outline when the "View Outline Depth" is disabled but see a silhouette when it is, then there is problem and I would need more information: 
* what build are you running?
* on what platform are you running? PC, Mac? What OS? What GPU?
* are you in desktop mode or in HMD mode?
* a hifi domain / URL where the issue is clearly visible with indications to the object

**Comment by Zvork** [comment]
@tapalisa I don't know if you were working on Mac but I've definitely found on issue there and just pushed a bug fix. Tell me if this fixes your "outline not working" issues too.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2568/HighFidelity-Beta-PR11160-7910b0d8ffc0293ba462c6c586ab90a5c6a5af5c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2568/HighFidelity-Beta-PR11160-7910b0d8ffc0293ba462c6c586ab90a5c6a5af5c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2624/HighFidelity-Beta-PR11160-20c7599c82bde20e4205d71258449a225dc780f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2624/HighFidelity-Beta-PR11160-20c7599c82bde20e4205d71258449a225dc780f2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3107/HighFidelity-Beta-PR11160-b9eb317d9b2f0f49e9d9de0a553c63fdf9e4616e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3107/HighFidelity-Beta-PR11160-b9eb317d9b2f0f49e9d9de0a553c63fdf9e4616e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3108/HighFidelity-Beta-PR11160-2003495166c81366c8a60c9e196d42f8e160eba0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3108/HighFidelity-Beta-PR11160-2003495166c81366c8a60c9e196d42f8e160eba0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3113/HighFidelity-Beta-PR11160-6b5ca0c6cee78567675ae60b0a416590fe8bc6f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3113/HighFidelity-Beta-PR11160-6b5ca0c6cee78567675ae60b0a416590fe8bc6f7.exe

**Comment by Zvork** [comment]
Replaced "dev debug" picking with selection based system introduced in PR #11232, the outline should also work on transparent objects. In consequence, this PR should be tested again, using the selection system of PR #11232.

# TEST PLAN
This test plan updates the previous test plan by replacing the first two tests.

1. An object added from the market place (as in test plan of PR #11232) should have an outline effect when the cursor hovers over it (mouse in desktop or laser in HMD).
2. If another object is "outlined", the previous object should have it's outline effect removed.

and adds:

14. Outline should work correctly on transparent or semi transparent objects
15. Outline should work correctly on skinned objects.

Please test this PR on all available GPU and display devices (HMD / desktop / Stereo TV) possible.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3116/HighFidelity-Beta-PR11160-7fb7ebca5728eda7e91853bcd2b0a85c4f8542a4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3116/HighFidelity-Beta-PR11160-7fb7ebca5728eda7e91853bcd2b0a85c4f8542a4.exe

**Comment by samcake** [comment]
## TEST PLAN BIS
Here is a script that you can use to test the features against any object you hover the mouse on
simply run the script, and hover the mouse over objects and expect to see outlines.

[LaserPointerAndOutlineTest.js.txt](https://github.com/highfidelity/hifi/files/1286269/LaserPointerAndOutlineTest.js.txt)

**Comment by samcake** [comment]
well i take that back, it sems to render correctly on everything i can pick
the problems seems to be telated to picking actually
If you come to blue, you can actually highlight the "cabin" on the beach and it s roof correctly
I 'd like to make sure it works for everythign like that

**Comment by samcake** [comment]
ok i tested again with transparent (in "blue" you can test the spheres with all the different materials)
ANd this is working correctly.
THe problem is with ray picking not the highlight code.
Waiting for confirmation from other qa and last feedback from olivier

**Comment by Nex-Pro** [comment]
Will be testing this as per @cozza13 request

**Comment by Zvork** [comment]
There's also an issue with some  objects having alpha clipping such as the huge arrows pointing to the "Shortbow" game in dev-welcome. The outline silhouette used is the entire quad, not the alpha clipped silhouette. I'll take a look.

**Comment by Zvork** [comment]
Voxels and Paint strokes don't seem to work either but for two different reasons, it seems.  For voxels, they are not extracted from the selection for outline (or for bounding box display as in PR #11232) because they are not filtered out into the "META" list in the render filter task. I'll fix this to also check for items in the "OPAQUE" and "TRANSPARENT" list.

As for, paint strokes it seems they don't react to your LaserPointerAndOutlineTest.js, @samcake (I checked this with the Log output to see if the printed out entity ID changed when passing my cursor over a paint stroke but nada).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3147/HighFidelity-Beta-PR11160-d6d36cbd43802776946375406eaa8f0a15fb7f0c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3147/HighFidelity-Beta-PR11160-d6d36cbd43802776946375406eaa8f0a15fb7f0c.exe

**Comment by Nex-Pro** [comment]
Testing with build ending in b7f0c

**Comment by Nex-Pro** [comment]
On hold til I resolve this....

viruswarning

Each time I attempt to install.

**Comment by samcake** [comment]
@zvork Yep some of the entities do not get picked correctly, this is one of the bug.
I am of the opinion we ship your pr as is
and we add the fixes step by step after

**Comment by samcake** [comment]
@Nex-Pro Piper, if you can qa and it s a pass then i want to merge this asap
thanks

**Comment by samcake** [comment]
build this please

**Comment by samcake** [comment]
just re-spawned a build

**Comment by samcake** [comment]
NOoooooooooooooooooooo

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3158/HighFidelity-Beta-PR11160-d6d36cbd43802776946375406eaa8f0a15fb7f0c.exe

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3161/HighFidelity-Beta-PR11160-d6d36cbd43802776946375406eaa8f0a15fb7f0c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3161/HighFidelity-Beta-PR11160-d6d36cbd43802776946375406eaa8f0a15fb7f0c.exe

**Comment by samcake** [comment]
i checked it works, let s ship it

**Pull request merged**
