### PR TITLE
Fix JSDoc for Entities.findEntitiesByName

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Skip build

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9313/app_13047_PR_8d71d72258a7de488b4a4a8f3e1aab6d4441599f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9313/HighFidelity-Beta-PR13047-8d71d72258a7de488b4a4a8f3e1aab6d4441599f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9313/HighFidelity-Beta-Interface-PR13047-8d71d72258a7de488b4a4a8f3e1aab6d4441599f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9313/HighFidelity-Beta-PR13047-8d71d72258a7de488b4a4a8f3e1aab6d4441599f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9313/HighFidelity-Beta-Interface-PR13047-8d71d72258a7de488b4a4a8f3e1aab6d4441599f.exe

**Pull request merged**
