### PR TITLE
DEV-2575: Automatically lower raised hand if talking

### PR DESCRIPTION
**Pull request by zfox23**
https://highfidelity.atlassian.net/browse/DEV-2575

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22137/HighFidelity-Beta-PR16408-4f7028f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22137/HighFidelity-Quest-Beta-PR16408-4f7028f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22137/HighFidelity-Beta-PR16408-4f7028f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22137/HighFidelity-Beta-Interface-PR16408-4f7028f.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22166/HighFidelity-Beta-PR16408-4f7028f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22166/HighFidelity-Beta-Interface-PR16408-4f7028f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22166/HighFidelity-Beta-PR16408-4f7028f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22166/HighFidelity-Quest-Beta-PR16408-4f7028f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22166/HighFidelity-Beta-PR16408-4f7028f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22166/HighFidelity-Beta-Interface-PR16408-4f7028f.exe

**Pull request merged**
