### PR TITLE
Make ATP respect request limit

### PR DESCRIPTION
**Pull request by Atlante45**
- ATP doens't ignore the request limit

### CODE REVIEW

**Comment by Atlante45** [comment]
This is related to https://app.asana.com/0/26551373415487/104301447586407
Though not a couple fix.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63e40fe060933425c30d00aff8d8366f9cd007a5 available at: https://gist.github.com/0310f87bcafe5cc1c28a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7453.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7453.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69c516caafe206fd3ec1a4f05b56b000b4f16701 available at: https://gist.github.com/0310f87bcafe5cc1c28a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7453.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7453.dmg

**Comment by cozza13** [comment]
@Atlante45 , what is the test plan for this?

**Comment by OmegaHeron** [comment]
Smoke tested Windows 7 - no issues seen, all ATP operations work as expected.  Real test is when target of fix tries.  QA Pass

**Comment by AndrewMeadows** [comment]
Deja-vu.  This reminds me of a problem we saw at LL when working on SL: too many http requests at once would cause problems with some (mostly consumer-grade) routers.  For example we learned that some routers have a memory leak which can be tickled by opening many simultaneous sockets and they will eventually run out of memory and requiring a reboot.

**Comment by OmegaHeron** [comment]
@AndrewMeadows - that's why I use my crappy 5 year old home grade router vs my much more current/better one for all my testing here.  Going back to dim mists of forgotten, that's how I came to find that avatar mixer was being flooded when animations were on -- it was updating (far) > 60 fps and would crash my old router.

**Pull request merged**
