### PR TITLE
Commerce: Owner Verification for Certified Entities

### PR DESCRIPTION
**Pull request by zfox23**
# What's New
1. Integration of `CanRez(Tmp)Certified` permission into Domain Settings page
2. `CanRez(Tmp)Certified` permission is now respected by the entity server (NOT the avatar mixer)
3. New `Ledger::updateLocation()` function which is called after a user rezzes (using any method) an **entity** (NOT an Avatar Entity) that has a certificate. **A note for the future:** Keep in mind that this will cost HFC when PoPs are on the blockchain. There will probably need to be some sort of backend/frontend protection about spending that money only if the current location doesn't match the recorded location.
4. There now exists an `_entityCertificateIDMap` `QHash` on the Entity Server. This `QHash` holds a dictionary that maps Certificate IDs to Entity IDs and is modified every time a certified entity enters or leaves the domain.
5. If user has `"commerce": true,` set in `Interface.json`, a Context Overlay will only appear on items whose Certificate ID property is not empty
6. If you rez 2 of the same certified items in the same domain, the first one disappears immediately after rezzing the second
7. If any static certificate property of an entity is changed, the entity server DOES NOT clear the certificate ID of that entity. The next time Dynamic Domain Verification runs, that entity will fail Static Certificate Verification and be deleted.
8. Entity Server performs Static Certificate Verification on all newly added entities. Upon failure, server deletes entity.
9. The Entity Server now performs Dynamic Owner Verification at some interval defined on the Domain Settings Page. The ES performs DOV via the following method:
    1. The Entity Server asynchronously hits the `/api/v1/commerce/proof_of_purchase_status/transfer` endpoint:
        - If the `invalid_reason` from reply is not empty, owner verification fails & server deletes entity
        - If the `transfer_status` from reply is `failed`, owner verification fails & server deletes entity
        - If the `transfer_status` from reply is `pending`, owner verification is scheduled for 90 seconds (i.e. this process restarts from (1) in 90 seconds).
        - If hitting the endpoint fails, owner verification fails, and the ES deletes the entity
    2. The Entity Server sends a `ChallengeOwnership` packet to adding client, which contains the `Certificate ID` string associated with the entity, an `Encrypted Nonce` (a QUuid temporarily stored in a map for verifying later), and an `Owner Public Key` (returned by the endpoint above):
        - The `ChallengeOwnership` request from entity server to client will timeout after 10 seconds. If that timer times out, the ES will delete the already-rezzed entity.
    3. The Interface Client (specifically Wallet.cpp) receives the `ChallengeOwnership` packet:
        - The Client processes the data and decrypts the `Encrypted Nonce` using its stored private key
        - The Client sends the Entity Server a `ChallengeOwnership` packet containing the `Certificate ID` string and `Decrypted Nonce` QUuid
    4. The Entity Server receives the `ChallengeOwnership` packet:
        - The Entity Server kills the timer associated with this specific `Certificate ID`
        - If `the Decrypted Nonce` sent from the Client matches the `Encrypted Nonce` stored in the map from earlier, the ownership challenge succeeds and nothing happens; the entity stays on the server
        - Otherwise, if the stored nonce doesn't match the decrypted text sent by the client, the ownership challenge fails and the server deletes the already-rezzed entity
10. The Entity Server now performs Dynamic Domain Verification. The ES performs DDV via the following method:
    1. Upon Entity Server (ES) startup, the ES calls "startDynamicDomainVerification()", which:
        a. Performs Static Certificate Verification - if that fails, the ES deletes the entity.
        b. If Static Certificate Verification succeeds, the ES makes an asynchronous call to the `/api/v1/commerce/proof_of_purchase_status/location` endpoint for every Cert ID in "_entityCertificateIDMap"
            - If the location reported for this cert ID by that endpoint does not match the current Domain ID, OR if contacting the endpoint fails, the ES deletes the entity.
        c. The ES then starts a timer that will call "startDynamicDomainVerification()" upon expiry
            - The duration of the timer is between "MINIMUM_DYNAMIC_DOMAIN_VERIFICATION_TIMER_MS" and "MAXIMUM_DYNAMIC_DOMAIN_VERIFICATION_TIMER_MS"
                - Server operators can change the min and max Dynamic Domain Verification times from the Domain Settings page under Entity Server settings (after enabling Advanced Settings)
11. Static Certificate Verification is working!

## Known Issues/Incomplete
- N/A

# Future Work
- Dynamic Owner Verification and Static Certificate Verification should be performed for Avatar Entities on the Avatar Mixer
- QML/engine changes following Austin's secure QML PRs

# Test Plan
Alright, let's get to it.

## Sandbox Settings
1. Launch Sandbox only (NOT Interface)
2. Go to your Domain Settings Page
3. Ensure that `Security` -> `Standard Permissions` -> `Rez Certified` and `Rez Temporary Certified` are CHECKED for `localhost`. Also ensure that `Security` -> `Standard Permissions` -> `Rez` and `Rez Temporary` are CHECKED for `localhost`.
4. Click "Show Advanced" on the left. Click "Entity Server Settings" on the left.
5. Under `Dynamic Domain Verification Time (seconds) - Minimum`, set the value to `20`.
6. Under `Dynamic Domain Verification Time (seconds) - Maximum`, set the value to `25`.

## Interface
1. Launch Interface
2. Set up your Wallet if it isn't already set up
3. Buy the "Test Beach Ball" from the Marketplace
4. Go to "My Purchases"
5. Wait for your Beach Ball's status to switch from `Pending` to `Confirmed` (should take between 90-180 seconds - you can refresh this page by clicking the "My Purchases" link at the top of the page)
6. Rez the Test Beach Ball
7. Wait 10 seconds. Verify that the Test Beach Ball is in front of you. *If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.*
8. Move slightly to the side, and, from within My Purchases, rez the same Test Beach Ball again. Verify that the previously-rezzed Test Beach Ball has disappeared; verify that there is only 1 test beach ball in the domain.
9. Wait 10 seconds. Verify that one and only one Test Beach Ball exists around you. *If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.*
10. Repeat steps 8 and 9 again two more times.
11. Go to a different domain (where you have at least temp rez rights) and perform the following actions quickly:
    1. Rez the Test Beach Ball from My Purchases
    2. Go back to the first domain.
    3. Find the Test Beach Ball that you rezzed earlier in your domain. Verify that, within 20 seconds, that beach ball disappears. Return to the second domain and confirm that the item is still there.
12. Return to your original domain.
13. Buy a second Test Beach Ball from the Market
14. Rez both of the Test Beach Balls that you own. Wait 10 seconds. Verify that there are now two rez'd items, identical except for edition number (as visible in their certificates upon right-click inspection). *If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.*
15. Export the rez'd Test Beach Ball to a JSON file:
    1. Open the Create app
    2. Click one of the Test Beach Balls
    3. Go to Interface's Edit menu, then `Export Entities`
16. Using your favorite text editor, modify the file you just exported and remove the line starting with `certificateID`. Save the file.
17. Import the modified JSON file from Interface's `Edit` -> `Import Entities`. Right click the beach ball you just rezzed and right click it. Verify that you do NOT see an (i) context overlay.
18. Delete all of the Beach Balls in your area.
19. Go to your Domain Settings Page
20. Go to `Security` -> `Standard Permissions` and UNCHECK `Rez` and `Rez Temporary` for `localhost`. Leave `Rez Certified` and `Rez Temporary Certified` CHECKED for `localhost`. Click "Save" on the left.
21. Return to Interface. Attempt to rez the same JSON file as in Step 17. Verify that a Beach Ball does NOT appear in front of you.
22. Go to My Purchases and rez one of the certified Test Beach Balls from there. Wait 10 seconds. Verify that the Test Beach Ball is in front of you. *If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.*
23. Export the rez'd Test Beach Ball to a JSON file:
    1. Open the Create app
    2. Click one of the Test Beach Balls
    3. Go to Interface's Edit menu, then `Export Entities`
24. Using your favorite text editor, modify the file you just exported and change the data for the `modelURL` key to `http://mpassets.highfidelity.com/df227a80-069b-4d01-9aec-d016fbc1fbe3-v1/models/flaregun.fbx`. Save the file.
25. Return to Interface. Attempt to rez the same JSON file as in Step 24. Verify that a Beach Ball (with the model of a flaregun) does NOT appear in front of you.
26. Delete all of the rezzed entities from the domain. Go to your Domain Settings Page, then go to `Security` -> `Standard Permissions` and CHECK `Rez` and `Rez Temporary` for `localhost`. Leave `Rez Certified` and `Rez Temporary Certified` CHECKED for `localhost`. Click "Save" on the left.
27. Buy a `Test Beach Ball` from the Marketplace. On the Purchase Confirmation page, verify that the red button says "REZ IT"
28. Buy a `Purple Scarf` from the Marketplace. On the Purchase Confirmation page, verify that the red button says "WEAR IT"
29. On your Purchases screen, verify that the red button next to the Purple Scarf says "WEAR IT"
30. On your Purchases screen, verify that the red button next to the Test Beach Ball says "REZ IT"
31. Close the Purchases screen
32. On your Domain Settings Page, make it so `localhost` does NOT have `Certified (Temp) Rez` permissions.
33. Buy a `Test Beach Ball` from the Marketplace. On the Purchase Confirmation page, verify that the "REZ IT" button is disabled and that there is red text below the "REZ IT" button explaining that you don't have permission to rez.
34. Buy a `Purple Scarf` from the Marketplace. On the Purchase Confirmation page, verify that the red button says "WEAR IT" and that it is enabled
35. On your Purchases screen, verify that the red button next to both Purple Scarves says "WEAR IT" and is enabled
36. On your Purchases screen, verify that the button next to the Test Beach Ball says "REZ IT" and is disabled
37. On your Purchases screen, verify that you see a red box at the top of the screen that explains that you don't have Rez permissions.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4370/HighFidelity-Beta-PR11658-3e139283ba03247fbd5d2a11e83fa60b070b20dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4370/HighFidelity-Beta-PR11658-3e139283ba03247fbd5d2a11e83fa60b070b20dc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4416/HighFidelity-Beta-PR11658-91333cdf7bc04f394aabb626fcb1ccdaf970b33c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4416/HighFidelity-Beta-PR11658-91333cdf7bc04f394aabb626fcb1ccdaf970b33c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4439/HighFidelity-Beta-PR11658-2f28cf1443cceef77cac4178514871f6fd57622a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4439/HighFidelity-Beta-PR11658-2f28cf1443cceef77cac4178514871f6fd57622a.exe

**Comment by Nex-Pro** [comment]
Testing win10

**Comment by Nex-Pro** [comment]
Awaiting backend fix

**Comment by Nex-Pro** [comment]
In progress.

**Comment by Nex-Pro** [comment]
### PASS (issues have been addressed.)

Launch Sandbox only (NOT Interface)
Go to your Domain Settings Page
Ensure that Security -> Standard Permissions -> Rez Certified and Rez Temporary Certified are CHECKED for localhost
Click "Show Advanced" on the left. Click "Entity Server Settings" on the left.
Under Dynamic Domain Verification Time (seconds) - Minimum, set the value to 20.
Under Dynamic Domain Verification Time (seconds) - Maximum, set the value to 25.
Interface

Launch Interface
Set up your Wallet if it isn't already set up
Buy the "Test Beach Ball" from the Marketplace
Go to "My Purchases"
Wait for your Beach Ball's status to switch from Pending to Confirmed **SUCCESS** was only a few seconds.
(should take between 90-180 seconds - you can refresh this page by clicking the "My Purchases" link at the top of the page)

Rez the Test Beach Ball
Wait 10 seconds. 
Verify that the Test Beach Ball is in front of you. **SUCCESS**
If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.

Move slightly to the side, and, from within My Purchases, 
rez the same Test Beach Ball again. 
Verify that the previously-rezzed Test Beach Ball has disappeared; **SUCCESS**
verify that there is only 1 test beach ball in the domain. **SUCCESS** searched to 1 million meters

Wait 10 seconds. 

Verify that one and only one Test Beach Ball exists around you. **SUCCESS**

If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.

Repeat steps 8 and 9 again two more times. **SUCCESS**

Go to a different domain (where you have at least temp rez rights) and perform the following actions quickly:

Rez the Test Beach Ball from My Purchases

Go back to the first domain.


Find the Test Beach Ball that you rezzed earlier in your domain. 
Verify that, within 20 seconds, that beach ball disappears. **SUCCESS**
Return to the second domain and confirm that the item is still there. **SUCCESS**

Return to your original domain.
Buy a second Test Beach Ball from the Market
Rez both of the Test Beach Balls that you own. 
Wait 10 seconds. 
Verify that there are now two rez'd items, identical except for edition number (as visible in their certificates upon right-click inspection). **SUCCESS**
If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.

Export the rez'd Test Beach Ball to a JSON file:
Open the Create app
Click one of the Test Beach Balls
Go to Interface's Edit menu, then Export Entities
Using your favorite text editor, modify the file you just exported and remove the line starting with certificateID. Save the file.

Import the modified JSON file from Interface's Edit -> Import Entities. 
Right click the beach ball you just rezzed and right click it. 
Verify that you do NOT see an (i) context overlay. **SUCCESS**

Delete all of the Beach Balls in your area.

Go to your Domain Settings Page
Go to Security -> Standard Permissions and UNCHECK Rez and Rez Temporary for localhost. Leave Rez Certified and Rez Temporary Certified CHECKED for localhost. Click "Save" on the left. **DONE**

Return to Interface. 
Attempt to rez the same JSON file as in Step 17. 
Verify that a Beach Ball does NOT appear in front of you. **SUCCESS**

Go to My Purchases and rez one of the certified Test Beach Balls from there. 
Wait 10 seconds. 
Verify that the Test Beach Ball is in front of you. **SUCCESS**
If this fails, attach the last 30 seconds of your Interface AND Entity Server log files to your QA report.

Export the rez'd Test Beach Ball to a JSON file:

Open the Create app
Click one of the Test Beach Balls
Go to Interface's Edit menu, then Export Entities

Using your favorite text editor, modify the file you just exported and change the data for the modelURL key to http://mpassets.highfidelity.com/df227a80-069b-4d01-9aec-d016fbc1fbe3-v1/models/flaregun.fbx. Save the file.

Return to Interface. Attempt to rez the same JSON file as in Step 24. 
Verify that a Beach Ball (with the model of a flaregun) does NOT appear in front of you.
Delete all of the rezzed entities from the domain. 

Go to your Domain Settings Page, then go to Security -> Standard Permissions and CHECK Rez and Rez Temporary for localhost. Leave Rez Certified and Rez Temporary Certified CHECKED for localhost. Click "Save" on the left.

Buy a Test Beach Ball from the Marketplace. On the Purchase Confirmation page, verify that the red button says "REZ IT" **SUCCESS**

Buy a Purple Scarf from the Marketplace. On the Purchase Confirmation page, verify that the red button says "WEAR IT" **SUCCESS**

On your Purchases screen, verify that the red button next to the Purple Scarf says "WEAR IT" **SUCCESS**

On your Purchases screen, verify that the red button next to the Test Beach Ball says "REZ IT" **SUCCESS**

Close the Purchases screen
On your Domain Settings Page, make it so localhost does NOT have Certified (Temp) Rez permissions. **DONE**

Buy a Test Beach Ball from the Marketplace. 

On the Purchase Confirmation page, 
verify that the "REZ IT" button is disabled  **SUCCESS**
and that there is red text below the "REZ IT" button explaining that you don't have permission to rez. **SUCCESS**

Buy a Purple Scarf from the Marketplace. 
On the Purchase Confirmation page, verify that the red button says "WEAR IT" **greyed out but** addressed in latest build.
and that it is enabled **FAIL** but addressed in latest build

On your Purchases screen, 
verify that the red button next to both Purple Scarves says "WEAR IT" **SUCCESS**
and is enabled **SUCCESS**

On your Purchases screen, verify that the button next to the Test Beach Ball says "REZ IT" and is disabled **SUCCESS**

On your Purchases screen, 
verify that you see a red box at the top of the screen that explains that you don't have Rez permissions. **SUCCESS** pink is the new red

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4495/HighFidelity-Beta-PR11658-9481824d0ab11cd35b8f9da991e99af367730e0e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4495/HighFidelity-Beta-PR11658-9481824d0ab11cd35b8f9da991e99af367730e0e.exe

**Comment by conklin94122** [comment]
Test Plan - https://highfidelity.testrail.net/index.php?/cases/view/2187

**Pull request merged**
