### PR TITLE
fix for segmented unordered packet writes in PacketList

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8517c01ffd1b604b2e7dd5661856f8e747bd9590 available at: https://gist.github.com/04bc2e163a2687a5a034<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 519df1565a519f5c5d09c03796e3f9e56f60f76c available at: https://gist.github.com/04bc2e163a2687a5a034<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.dmg

**Comment by hyperlogic** [comment]
This is fixing the issue with the avatarMixer, we are never hitting the overflow case

    Error in PacketList::writeData - attempted to write a segment to an unordered packet that is larger than the payload size.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d9421a65e6ba66ae5cdb4ceb1e48068c8028ffd available at: https://gist.github.com/04bc2e163a2687a5a034<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa2a8edc6f332154aafa68c6eff5002a6fd348a0 available at: https://gist.github.com/04bc2e163a2687a5a034<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6030.dmg

**Pull request merged**
