### PR TITLE
Pr 11960 for rc 61

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by themelissabrown** [comment]
** Test plan **
Open the Go To app in the toolbar
Click away from the Go To app (Click on the ground in the world)
Move the avatar in any way (Walk forward) so that UI hides while Avatar moves
Stop moving, wait until UI reappears
Ensure you can still type in the search bar

and

Launch interface with an HMD
Open the tablet and click on GoTo
Start using the address bar so that the virtual keyboard appears
Click on the hide keyboard button (see screenshot)
Try to use the address bar again
Address bar should work

**Comment by Nex-Pro** [comment]
Awaiting win build.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5624/HighFidelity-Beta-PR11981-aa0d581236d3dbace0abe9bb4af0e185f15cfa9f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5624/HighFidelity-Beta-PR11981-aa0d581236d3dbace0abe9bb4af0e185f15cfa9f.dmg

**Comment by Nex-Pro** [comment]
Testing Win 10

**Comment by Nex-Pro** [comment]
@themelissabrown To be thorough I tested this in  HMD tablet and from toolbar and Desktop toolbar and tablet.  All good.

### PASS

**Pull request merged**
