### PR TITLE
More render performace testing work

### PR DESCRIPTION
**Pull request by jherico**
* Add an on screen FPS counter
* Support culling (press `F9` to toggle culling)
* Correct color on screen
* Automatic loading of previous scene

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 36bd01452554dc0ebf33e6c76e70e6cf75b9dd27 available at: https://gist.github.com/196f7590a0e3c90974f9591f65e244de<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-36bd014.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-36bd014.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2f57209188572e4751bc60e69d3aa3f7cb86323 available at: https://gist.github.com/196f7590a0e3c90974f9591f65e244de<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-c2f5720.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-c2f5720.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 029251f29335442c5d3847b4ad1474d9d43962be available at: https://gist.github.com/196f7590a0e3c90974f9591f65e244de<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-029251f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-029251f.dmg

**Comment by jherico** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 029251f29335442c5d3847b4ad1474d9d43962be available at: https://gist.github.com/196f7590a0e3c90974f9591f65e244de<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-029251f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8228-029251f.dmg

**Pull request merged**
