### PR TITLE
Include inputCalibrationData in InputRecordings

### PR DESCRIPTION
**Pull request by hyperlogic**
This is mostly an internal tool, used to record performers wearing Vive trackers for analysis and debugging.
This change includes more detail in the recording, specifically the avatar's current position & orientation.  As well as the current location of the tracked volume in world space, i.e. the sensor to world matrix.  This can help our analysis and machine learning analysis.  Because we can now properly transform the input data into sensor or world space.

It also supports longer recordings which should fix the following issue: https://highfidelity.manuscript.com/f/cases/17464/Input-Recording-is-Corrupted-Empty

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11055/HighFidelity-Beta-PR13520-e9fc35c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11055/HighFidelity-Beta-PR13520-e9fc35c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11055/HighFidelity-Beta-Interface-PR13520-e9fc35c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11055/HighFidelity-Beta-PR13520-e9fc35c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11055/HighFidelity-Beta-Interface-PR13520-e9fc35c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11072/HighFidelity-Beta-PR13520-f22f979.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11072/HighFidelity-Beta-PR13520-f22f979.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11072/HighFidelity-Beta-Interface-PR13520-f22f979.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11072/HighFidelity-Beta-PR13520-f22f979.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11072/HighFidelity-Beta-Interface-PR13520-f22f979.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15411/HighFidelity-Beta-PR13520-97edbb5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15411/HighFidelity-Beta-PR13520-97edbb5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15411/HighFidelity-Beta-Interface-PR13520-97edbb5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15411/HighFidelity-Beta-PR13520-97edbb5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15411/HighFidelity-Beta-Interface-PR13520-97edbb5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15981/HighFidelity-Beta-PR13520-8554110.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15981/HighFidelity-Beta-PR13520-8554110.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15981/HighFidelity-Beta-Interface-PR13520-8554110.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15981/HighFidelity-Beta-PR13520-8554110.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15981/HighFidelity-Beta-Interface-PR13520-8554110.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16020/HighFidelity-Beta-PR13520-4701b96.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16020/HighFidelity-Beta-PR13520-4701b96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16020/HighFidelity-Beta-Interface-PR13520-4701b96.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
