### PR TITLE
Team Teaching - Move avatar rendering to Scene pipeline

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5a3edee0994071bf3db9ba4bcd1e9de32ad4919 available at: https://gist.github.com/16ad30a0c3ecd7a8cab1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.dmg

**Comment by ZappoMan** [comment]
@huffman - build error on windows...

```
interface.dir\Release\interface_automoc.obj
    88>AvatarManager.obj : error LNK2005: "class AABox const __cdecl render::payloadGetBound<class AvatarData>(class std::shared_ptr<class AvatarData> const &)" (??$payloadGetBound@VAvatarData@@@render@@YA?BVAABox@@ABV?$shared_ptr@VAvatarData@@@std@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>AvatarManager.obj : error LNK2005: "class render::ItemKey const __cdecl render::payloadGetKey<class AvatarData>(class std::shared_ptr<class AvatarData> const &)" (??$payloadGetKey@VAvatarData@@@render@@YA?BVItemKey@0@ABV?$shared_ptr@VAvatarData@@@std@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>AvatarManager.obj : error LNK2005: "void __cdecl render::payloadRender<class AvatarData>(class std::shared_ptr<class AvatarData> const &,class RenderArgs *)" (??$payloadRender@VAvatarData@@@render@@YAXABV?$shared_ptr@VAvatarData@@@std@@PAVRenderArgs@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
         faceshift.lib(fsbinarystream.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
            Creating library Y:/jenkins/workspace/hifi-pull-request-win/build/interface/Release/interface.lib and object Y:/jenkins/workspace/hifi-pull-request-win/build/interface/Release/interface.exp
         Generating code
         Finished generating code
    88>AvatarManager.obj : error LNK2005: "class AABox const __cdecl render::payloadGetBound<class AvatarData>(class std::shared_ptr<class AvatarData> const &)" (??$payloadGetBound@VAvatarData@@@render@@YA?BVAABox@@ABV?$shared_ptr@VAvatarData@@@std@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>AvatarManager.obj : error LNK2005: "class render::ItemKey const __cdecl render::payloadGetKey<class AvatarData>(class std::shared_ptr<class AvatarData> const &)" (??$payloadGetKey@VAvatarData@@@render@@YA?BVItemKey@0@ABV?$shared_ptr@VAvatarData@@@std@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>AvatarManager.obj : error LNK2005: "void __cdecl render::payloadRender<class AvatarData>(class std::shared_ptr<class AvatarData> const &,class RenderArgs *)" (??$payloadRender@VAvatarData@@@render@@YAXABV?$shared_ptr@VAvatarData@@@std@@PAVRenderArgs@@@Z) already defined in Avatar.obj [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>Y:\jenkins\workspace\hifi-pull-request-win\build\interface\Release\interface.exe : fatal error LNK1169: one or more multiply defined symbols found [Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj]
    88>Done Building Project "Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj" (default targets) -- FAILED.
    21>Done Building Project "Y:\jenkins\workspace\hifi-pull-request-win\build\interface\interface.vcxproj.metaproj" (default targets) -- FAILED.
     1>Done Building Project "Y:\jenkins\workspace\hifi-pull-request-win\build\hifi.sln" (default targets) -- FAILED.

Build FAILED.
```

**Comment by huffman** [comment]
@ZappoMan Thanks, checking now

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea6b620d8aedadf7dab04814bc98322d057dae8d available at: https://gist.github.com/16ad30a0c3ecd7a8cab1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.dmg

**Comment by huffman** [comment]
I'm going to debug this on my Windows machine when I get home.  No need to review.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8002014dcdfda313d9a8f86a6e94b7e239ef33fd available at: https://gist.github.com/16ad30a0c3ecd7a8cab1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4975.dmg

**Pull request merged**
