### PR TITLE
Raveenajain coop assessment

### PR DESCRIPTION
**Pull request by raveenajain**

### CODE REVIEW

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14957/HighFidelity-Beta-PR14289-91fac07.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14957/HighFidelity-Beta-PR14289-91fac07.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14957/HighFidelity-Beta-Interface-PR14289-91fac07.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14957/HighFidelity-Beta-PR14289-91fac07.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14957/HighFidelity-Beta-Interface-PR14289-91fac07.exe

**Pull request closed without merging**
