### PR TITLE
More dialog porting to tablet

### PR DESCRIPTION
**Pull request by druiz17**
Added the stack view for tablet menu and also ported modal Dialogs to the tablet as well of the runningScripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19110ecfee758210e01e2aa63490de99fe0a94bd available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-19110ec.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-19110ec.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: accff0a37ad392bd7292e93768a7061f02f04414 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-accff0a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-accff0a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58c1a2fb999afeab311c474a0dea2d5c4b349571 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-58c1a2f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-58c1a2f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea804578cec19dca30c923bc7cac3238f9e00404 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-ea80457.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-ea80457.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ba89e67afdac2dfabba6a3e3df4f5d4d5fae29b available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-5ba89e6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-5ba89e6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f5324d58220af8195ba70dd080cd91a0fb1e1941 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-f5324d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-f5324d5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88c0db969c56c70867cce43dbef9190fd1fa8c07 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-88c0db9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-88c0db9.dmg

**Comment by druiz17** [comment]
Ported modal dialogs- inputDialog, fileDialog and messageDialog. I also ported over the running scripts

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5948079c74946df9015b1bfe6e98aeab0f0f0b5 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-d594807.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-d594807.dmg

**Comment by druiz17** [comment]
Test Plan
-Perform the following tests in both desktop & HMD mode
1. Test in tablet mode 
- open up the tablet and click running scripts
- check that all the functionality of running scripts work and that any pages generated by running scripts show up in the tablet. 

2. test that the message modal show up in the tablet.
- click on goto and enter an incorrect location. The error should show up in the tablet
- go to the market place, sort by avatars and click on the photo-Real male Avatar. The messages dialog show up in the tablet ( ensure that the correct action is performed when responding to these messages)

3. When any modal is open, ensure that you can not close the tablet or return to the main screen.

4.  perform the same tests 1-3 in toolbar mode with the exception that every new page generate should use the new UI

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10ce732e914a3fc9f1b7a04fb9ba7687cd15acb4 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-10ce732.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-10ce732.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d84413d902fe70a7452480b30ae09066fa67ca1 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-6d84413.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-6d84413.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b740073358b392b4ba9be41a957a10d7284e1e93 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-b740073.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-b740073.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b58a27cf10a43677fdaeeaa87c4273cf0d9cfdb6 available at: https://gist.github.com/5d6d1316b999818452c15a024f43069c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-b58a27c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9785-b58a27c.dmg

**Comment by druiz17** [comment]
test is please

**Pull request merged**
