### PR TITLE
DEV-2871: signal connection check before emit of devices changed

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2817

Fixing logic to emit after scripting interface has initialized the audiodevices.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22658/HighFidelity-Beta-PR16525-87afa63.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22658/HighFidelity-Beta-Interface-PR16525-87afa63.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22658/HighFidelity-Beta-PR16525-87afa63.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22658/HighFidelity-Quest-Beta-PR16525-87afa63.apk)

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22667/HighFidelity-Beta-PR16525-87afa63.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22667/HighFidelity-Beta-Interface-PR16525-87afa63.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22667/HighFidelity-Beta-PR16525-87afa63.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22667/HighFidelity-Quest-Beta-PR16525-87afa63.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22667/HighFidelity-Beta-PR16525-87afa63.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22667/HighFidelity-Beta-Interface-PR16525-87afa63.exe

**Pull request merged**
