### PR TITLE
Login fix

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
Please hold off on merging

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09ffe0702858130c564621fbf15b327b6f458c7b available at: https://gist.github.com/2ac4d8e2c9f54bfd4000<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a25ecbaacec02e05bbcf020f211fd8f2d10076e3 available at: https://gist.github.com/534abac8711a40a567c7<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3fb7f914dd386c1cfecf3461e95be1740319aada available at: https://gist.github.com/ad7721b9b817b40b8404<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4272.dmg

**Comment by AndrewMeadows** [comment]
Is this ready for merging?

**Comment by huffman** [comment]
@AndrewMeadows I am going to go ahead and close this.  It wasn't as effective on Windows machines as hoped.  Thanks!

**Pull request closed without merging**
