### PR TITLE
Fix the reported amount of GPU memory physically available for GPPU with video mem larger than 4Gb

### PR DESCRIPTION
**Pull request by samcake**
This PR replaces the detection of the GPU on windows.
We replaced the former technique used by relying on DXGI, the windows library managing the adapters and outputs since windows Vista.

THis PR fixes the bug that GPU with memory over 4Gb wasn't reported correctly.
It now works correctly on a Geforce 1080 for example returning 8Gb as expected.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a23bbd1e4e067714dc7457689f1b25a772d9bffc available at: https://gist.github.com/e85e98f5dc4cc132068a15f07fd38a46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-a23bbd1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-a23bbd1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 861944ba71e718391c69554ac1405ba61a3d19c3 available at: https://gist.github.com/e85e98f5dc4cc132068a15f07fd38a46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-861944b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-861944b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49f1590e01ee2a1dfeed7b43b706a03cb1b82d02 available at: https://gist.github.com/e85e98f5dc4cc132068a15f07fd38a46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-49f1590.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-49f1590.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c777bb079fe93df3b3e4762dc75933c89f00845 available at: https://gist.github.com/e85e98f5dc4cc132068a15f07fd38a46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-3c777bb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-3c777bb.dmg

**Comment by samcake** [comment]
Test Plan:
No change to performances or features.
This PR should report in the log the correct name for the GPU, correct driver version and correct GPU similar to Master.
This information is visible at the beginning of the log file.
For example:
In current Master:
```
[11/02 12:40:27] [DEBUG] [hifi.interface] Created Display Window.
[11/02 12:40:27] [DEBUG] [hifi.glLogging] GL Version:  "4.5.0 NVIDIA 372.54"
[11/02 12:40:27] [DEBUG] [hifi.glLogging] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 12:40:27] [DEBUG] [hifi.glLogging] GL Vendor:  "NVIDIA Corporation"
[11/02 12:40:27] [DEBUG] [hifi.glLogging] GL Renderer:  "GeForce GTX 980/PCIe/SSE2"
[11/02 12:40:27] [DEBUG] [hifi.gpu.gl] GL Version:  "4.5.0 NVIDIA 372.54"
[11/02 12:40:27] [DEBUG] [hifi.gpu.gl] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 12:40:27] [DEBUG] [hifi.gpu.gl] GL Vendor:  "NVIDIA Corporation"
[11/02 12:40:27] [DEBUG] [hifi.gpu.gl] GL Renderer:  "GeForce GTX 980/PCIe/SSE2"
[11/02 12:40:28] [DEBUG] [hifi.gpu.gl] GPU:
[11/02 12:40:28] [DEBUG] [hifi.gpu.gl] 	card: "NVIDIA GeForce GTX 980"
[11/02 12:40:28] [DEBUG] [hifi.gpu.gl] 	driver: "21.21.13.7254"
[11/02 12:40:28] [DEBUG] [hifi.gpu.gl] 	dedicated memory: 4095 MB
```

In This PR we added more logging during the detection phase but the same information in conclusion as above:
```
[11/02 12:44:44] [DEBUG] [hifi.interface] Created Display Window.
[11/02 12:44:44] [DEBUG] [hifi.glLogging] GL Version:  "4.5.0 NVIDIA 372.54"
[11/02 12:44:44] [DEBUG] [hifi.glLogging] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 12:44:44] [DEBUG] [hifi.glLogging] GL Vendor:  "NVIDIA Corporation"
[11/02 12:44:44] [DEBUG] [hifi.glLogging] GL Renderer:  "GeForce GTX 980/PCIe/SSE2"
[11/02 12:44:44] [DEBUG] [hifi.gpu.gl] GL Version:  "4.5.0 NVIDIA 372.54"
[11/02 12:44:44] [DEBUG] [hifi.gpu.gl] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 12:44:44] [DEBUG] [hifi.gpu.gl] GL Vendor:  "NVIDIA Corporation"
[11/02 12:44:44] [DEBUG] [hifi.gpu.gl] GL Renderer:  "GeForce GTX 980/PCIe/SSE2"
[11/02 12:46:15] [DEBUG] [hifi.shared] Found adapter:  NVIDIA GeForce GTX 980  Driver version:  "21.21.13.7254"
[11/02 12:46:17] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY1  desktop:  true  Rect [ l= 0  r= 3840  b= 2160  t= 0  ]
[11/02 12:46:17] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY2  desktop:  true  Rect [ l= 3840  r= 5760  b= 2151  t= 1071  ]
[11/02 12:46:18] [DEBUG] [hifi.shared] Found adapter:  Microsoft Basic Render Driver  Driver version:  "10.0.14393.0"
[11/02 12:46:18] [DEBUG] [hifi.gpu.gl] GPU:
[11/02 12:46:18] [DEBUG] [hifi.gpu.gl] 	card: "NVIDIA GeForce GTX 980"
[11/02 12:46:18] [DEBUG] [hifi.gpu.gl] 	driver: "21.21.13.7254"
[11/02 12:46:18] [DEBUG] [hifi.gpu.gl] 	dedicated memory: 4060 MB
```

Check for bug 2155 gpu_memory reporting as maximum of 4GB even on GPUs with more memory
On a system with a a GPU with memory Larger than 4Gb, the amount of memory reported should be correct (8Gb for a Nvidia GTX 1080 for example) with this PR.
THe value is 4Gb (4095Mb) fon master which is wrong

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96bdeebc37549ef5be3b2cdd2ab49a90f9a872b8 available at: https://gist.github.com/e85e98f5dc4cc132068a15f07fd38a46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-96bdeeb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8967-96bdeeb.dmg

**Comment by OmegaHeron** [comment]
Windows 10 GTX970/4G

[11/02 16:25:51] [DEBUG] [hifi.interface] Created Display Window.
[11/02 16:25:51] [DEBUG] [hifi.glLogging] GL Version:  "4.5.0 NVIDIA 375.70"
[11/02 16:25:51] [DEBUG] [hifi.glLogging] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 16:25:51] [DEBUG] [hifi.glLogging] GL Vendor:  "NVIDIA Corporation"
[11/02 16:25:51] [DEBUG] [hifi.glLogging] GL Renderer:  "GeForce GTX 970/PCIe/SSE2"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] GL Version:  "4.5.0 NVIDIA 375.70"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] GL Shader Language Version:  "4.50 NVIDIA"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] GL Vendor:  "NVIDIA Corporation"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] GL Renderer:  "GeForce GTX 970/PCIe/SSE2"
[11/02 16:25:51] [DEBUG] [hifi.shared] Found adapter:  NVIDIA GeForce GTX 970  Driver version:  "21.21.13.7570"
[11/02 16:25:51] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY1  desktop:  true  Rect [ l= 0  r= 1600  b= 900  t= 0  ]
[11/02 16:25:51] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY2  desktop:  true  Rect [ l= 1600  r= 2880  b= 902  t= -122  ]
[11/02 16:25:51] [DEBUG] [hifi.shared] Found adapter:  Microsoft Basic Render Driver  Driver version:  "10.0.14393.0"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] GPU:
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] 	card: "NVIDIA GeForce GTX 970"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] 	driver: "21.21.13.7570"
[11/02 16:25:51] [DEBUG] [hifi.gpu.gl] 	dedicated memory: 4058 MB

**Comment by Nex-Pro** [comment]
### PR #8967

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

[11/03 10:23:13] [DEBUG] [hifi.interface] Created Display Window.
[11/03 10:23:13] [DEBUG] [hifi.glLogging] GL Version:  "4.5.0 NVIDIA 373.06"
[11/03 10:23:13] [DEBUG] [hifi.glLogging] GL Shader Language Version:  "4.50 NVIDIA"
[11/03 10:23:13] [DEBUG] [hifi.glLogging] GL Vendor:  "NVIDIA Corporation"
[11/03 10:23:13] [DEBUG] [hifi.glLogging] GL Renderer:  "GeForce GTX 1070/PCIe/SSE2"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] GL Version:  "4.5.0 NVIDIA 373.06"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] GL Shader Language Version:  "4.50 NVIDIA"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] GL Vendor:  "NVIDIA Corporation"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] GL Renderer:  "GeForce GTX 1070/PCIe/SSE2"
[11/03 10:23:13] [DEBUG] [hifi.shared] Found adapter:  NVIDIA GeForce GTX 1070  Driver version:  "21.21.13.7306"
[11/03 10:23:13] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY1  desktop:  true  Rect [ l= 0  r= 1920  b= 1080  t= 0  ]
[11/03 10:23:13] [DEBUG] [hifi.shared]     Found output:  \\.\DISPLAY2  desktop:  true  Rect [ l= 1920  r= 5760  b= 2160  t= 0  ]
[11/03 10:23:13] [DEBUG] [hifi.shared] Found adapter:  Microsoft Basic Render Driver  Driver version:  "10.0.14393.0"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] GPU:
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] 	card: "NVIDIA GeForce GTX 1070"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] 	driver: "21.21.13.7306"
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] 	dedicated memory: 8145 MB
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] Status: Using GLEW 1.13.0
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] 
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] V-Sync is ON
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] 
[11/03 10:23:13] [DEBUG] [hifi.gpu.gl] Using OpenGL 4.5 backend
[11/03 10:23:13] [DEBUG] [hifi.glLogging] New Offscreen GLContext, window size =  160  ,  160
[11/03 10:23:13] [DEBUG] [hifi.interface] Initialized Display.

**Pull request merged**
