### PR TITLE
Close toolbar windows when reloading scripts

### PR DESCRIPTION
**Pull request by druiz17**
Made sure that all default scripts close their windows when reloading scripts in toolbar mode

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1. Be in toolbar mode.
2. open running scripts
3. click on the buttons on the toolbar that bring up a window.
4. reload default scripts ( you should see the toolbar reload and any window create from the toolbar be destroyed)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 881213259dd0f5ac93b273889f18afca63da5acf available at: https://gist.github.com/b03303893057c19d43ff7b503f57bc90<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9835-8812132.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9835-8812132.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9835-8812132.exe

In Desktop Mode:
- PASS

In VR
- PASS, but...
After reloading the defaultScript.js script, a blue laser is stuck to whichever hand that triggered the reload. The blue laser disappears after clicking on any sort of UI.
cerrorpr9835
 
Note:
- All the windows closed, that were opened by way of the toolbar, after reloading the script.
- I clicked on the SNAP icon, in the toolbar, and immediately after I reloaded the defaultScript.js script. This caused 2 SNAP icons to appear side by side. You can see this in the image above.

**Comment by druiz17** [comment]
@claudioshg can I get retest this pr with the same test plan plus checking if you still get the duplicate snapshot button.

**Comment by claudioshg** [comment]
@druiz17 re-testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: d54005b62ec5ba5d41d49d2490d454031cf6fb92 available at: https://gist.github.com/b03303893057c19d43ff7b503f57bc90<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9835-d54005b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9835-d54005b.dmg

**Comment by claudioshg** [comment]
@druiz17  The two SNAP icon side by side bug is gone. Everything works as intended. Reloading defaultScript.js destroys all windows in VR and in Desktop Mode. 
However, the blue laser bug still happens.

**Pull request merged**
