### PR TITLE
Fixed buttons on Marketplace

### PR DESCRIPTION
**Pull request by kunalgosar**
Resolution to: https://highfidelity.fogbugz.com/f/cases/3347/See-All-Markets-not-Clickable

Open up marketplace in interface, clicking 'See All Markets' and then 'Back' should have normal behavior.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30d2ea0ea5f287334316a2ac914b6f24910ad83a available at: https://gist.github.com/faf5da59c907dfa32180ade3c84047ca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9972-30d2ea0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9972-30d2ea0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f09ee92fe1efacc07e5820fee707b78ae80d1eef available at: https://gist.github.com/faf5da59c907dfa32180ade3c84047ca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9972-f09ee92.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9972-f09ee92.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9972-f09ee92.exe

PASS: 
- Tested in HMD and in Desktop Mode. 
- Clicking on 'See All Markets' and then 'Back' works properly.

**Pull request merged**
