### PR TITLE
fix Linux default plugins

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that was causing Linux interface to fail to find any of the standard plugins

### CODE REVIEW

**Comment by sethalves** [comment]
gustavo?
test this please

**Comment by sethalves** [comment]
to test:
- build and run interface on Linux

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1088/HighFidelity-Beta-PR10812-ab20543819ae1c312e9f47a234a71f08426a96fd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1088/HighFidelity-Beta-PR10812-ab20543819ae1c312e9f47a234a71f08426a96fd.dmg

**Comment by sethalves** [comment]
closing this in favor of https://github.com/highfidelity/hifi/pull/10814

**Pull request closed without merging**
