### PR TITLE
Tablet webbrowser

### PR DESCRIPTION
**Pull request by vladest**
Implemented according to:
https://highfidelity.fogbugz.com/f/cases/4210/Worklist-Proposal-Add-private-browser-to-tablet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1298/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1298/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.exe

**Comment by misslivirose** [comment]
Will confirm that having this in default scripts is desired behavior

**Comment by thoys** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1684/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1684/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.dmg

**Comment by tapalisa** [comment]
I don't think it should be in default scripts, especially at the outset. Will ask Design.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1939/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1939/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2258/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2258/HighFidelity-Beta-PR10873-7cf4ca608be741bfc4aaa09743c2ffd1f55203bd.exe

**Pull request closed without merging**
