### PR TITLE
Basic address bar toggle button.

### PR DESCRIPTION
**Pull request by howard-stearns**
Adds a stand-alone button (that can be moved elsewhere) to toggle the address bar.

### CODE REVIEW

**Comment by howard-stearns** [comment]
this is for vive-ui branch

We'll likely do more with this, such as collect a bunch of buttons into a single toolbar, but this gets us going.

**Comment by howard-stearns** [comment]
test plan:

Clicking the button should toggle the address bar on and off.  (It is not yet meant to reflect the address bar state in the button highlighting.)

The button should be relocatable by dragging the (very tiny and hard to click on) border around the button.  When you restart Interface, the button should be where you left it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 247286c71f41ecc97dccdf57f7111175ad48c36e available at: https://gist.github.com/dd8a207c74a58b72bf57a037b6c71fff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8008.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8008.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;b1KowtYM&#x2F;5-bring-up-address-field-from-a-button-typing-in-general-is-a-separate-task"> bring up address field from a button (typing, in general, is a separate task)</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91450addd330ee269b045adf7cb9d023ef4d55c5 available at: https://gist.github.com/dd8a207c74a58b72bf57a037b6c71fff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8008.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8008.dmg

**Comment by howard-stearns** [comment]
see comment re merging on #8012

**Pull request merged**
