### PR TITLE
cleanup the Interface log with new design and Info category

### PR DESCRIPTION
**Pull request by birarda**
- removes the `LogDialog` and replaces with `DeveloperTools`. 
- re-categorizes some logging as Info instead of Debug - debug is hidden by default in DeveloperTools log

#### Why HTML?
Currently `DeveloperTools` only has the Log, but I envision adding other information that we currently have stuffed into different dialogs and stats displays into these HTML/JS/CSS developer tools. I believe this will be the most straightforward way for our developers to quickly add debugging views.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0c2294ebd8757be56389a6532d3152ad29e8b51 available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f9a51e64ce7ce6e461e264d0ddd7f5e349b99b7 available at: https://gist.github.com/a78a99961cd8b3e4085c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbe3d0c23e5039da001470ef9cbefb557e380a99 available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by ZappoMan** [comment]
I tried to do a quick smoke test of this on Windows 8.1, and it crashes immediately... I don't see any interface window.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ebe8225b2df98160976040411703d4ecb3bc7d4d available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c0796ade7180a2926f5c59e1f200d8587d2bb68 available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by birarda** [comment]
@ZappoMan the build that will publish for `4595f3f` fixes the crash on start

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4595f3fa27a677be5bb58ac0753500d92bbaf220 available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by birarda** [comment]
So there is one interesting thing I discovered while testing the log that we probably don't care about because it seems to be OS X only.

Scrolling in the log (this is also true for the previous log) impacts the simulation rate of Interface. I believe this to be due to the handling of OS X multi touch events. Not sure there's much we can do here given that the widget needs to live on the main thread - it seems to be OS X only and happens on intense scrolling.

**Comment by birarda** [comment]
I'm going to leave the DO NOT MERGE label on this so I can do some more performance testing with heavy debug

**Comment by birarda** [comment]
Alright, performance wise this is a little worse than the current log, but not by a massive amount. Basically lots of scrolling or lots of debug will slow down your sim rate (since the JS for the QWebView is also executed on same thread). In talking with @jherico it's possible his QWebEngine work will help - I think this can be merged before then, and I'll separately test it with his QWebEngine PR.

**Comment by birarda** [comment]
Leaving DO NOT MERGE on this until I fix an issue with suppressed messages

**Comment by hifi-gustavo** [comment]
Build console output for commit: eabfb684f9a17efb820cd0d4ab10696b75b37b0d available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7afddc36455609fb1ec6bbe02d5951268c943d1c available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7afddc36455609fb1ec6bbe02d5951268c943d1c available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Comment by birarda** [comment]
test this please

**Comment by birarda** [comment]
Applying DO NOT MERGE again since I think it makes sense to wait until we can use QWebEngine for this - should perform a lot better.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7afddc36455609fb1ec6bbe02d5951268c943d1c available at: https://gist.github.com/c5eae773e2de295e7ed1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6638-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6638.dmg

**Pull request closed without merging**
