### PR TITLE
Beta Release 35 - Includes up to Developer Release 6106

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Filter pal by view distance 
* Fix avatars slightly out of view in large audience from freezing 
* Make Debug defaultScripts.js option less error prone. 
* **Point index finger and raise thumb if not touching controller** 
* Fix for Web Entity not leaving Focus 
* Fix Password Setting Bug on domain server
* Fix a crash in ESS on ES shutdown 
* Add shortbow to marketplace scripts 
* Tablet homebutton dimension and position now scales with tablet 
* **Tablet is now an overlay** 
* Add hips pinning / Sit script 
* Faster avatar updates 
* No bullet shape for collisionless polyvox 
* Remember gain settings when pal is closed and reopened 
* PAL average volume sorting 
* Fix bug drawing avatar above ground 
* Increase max renderable web entity FPS to 30 for Youtube.com 
* Fix unmute when ignoring in PAL
* Add Hifi-Hand-Drop so scripts can cause grabbed items to be dropped

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1564c76ab40e9b188ea08adad44e1dadcc64bf06 available at: https://gist.github.com/fc68983b657e7d34c31ae9d9f13359a5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-1564c76.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-1564c76.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS

I admit that I've lost track, but, is PAL supposed to stay open on domain changes (I thought it used to close)?  If it is intended to remain open on domain changes then it needs a auto refresh trigger -- otherwise it's simply clutter leaving it open on change.

Checked for any other avatars not standing proper (i.e. floating once they have physics).  All good for the 3 I saw.

Checked various forms of youtube videos in web entities and web entities in general.  All good.

Checked entity script server - all good.

Desktop Mode 1600x900 maximized window

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2743 |3793 |
**GPU Buffer Count**: |920 |1184 |
**CPU Memory Usage**: |37066000 |62674384 |
**GPU Memory Usage**: |23856560 |43726256 |
**CPU Texture Count**: |312 |274 |
**GPU Texture Count**: |257 |234 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |149484588 |126460288 |
**GPU Texture Memory Usage**: |852573561 |948751508 |
**GPU Virtual Memory Usage**: |852573561|948751508|
**Triangle Count**: |258501 |742723 |
**Triangle Rate**: |16156312 |41262388 |
**API Drawcall Count**: |185 |241 |
**Drawcall Count**: |2386 |285 |
**Drawcall Rate**: |149125 |15833 |
**State Changes Texture Count**:|381 |289 |
**Pipeline Count**: |60 |34 |
**Item Opaques**: |268 |410 |
**Item Translucents**: |118 |50 |
**Item Lights**: |11 |39 |
**Timing Opaques**: |1.06 |1.323 |
**Timing Translucents**: |0.17 |0.072 |
**Timing Lighting**: |0.016 |0.031 |
**Render Frame**: |1.782 |2.976 |

DK2

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |75 |75 |
**Present Rate**: |75 |75 |
**Present New Rate**: |75 |75 |
**CPU Buffer Count**: |2891 |3800 |
**GPU Buffer Count**: |940 |1210 |
**CPU Memory Usage**: |38336656 |62723536 |
**GPU Memory Usage**: |24212912 |44430768 |
**CPU Texture Count**: |318 |273 |
**GPU Texture Count**: |263 |241 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |126066376 |106275244 |
**GPU Texture Memory Usage**: |1062084419 |1141135624 |
**GPU Virtual Memory Usage**: |1062084419|1141135624|
**Triangle Count**: |533146 |2146452 |
**Triangle Rate**: |41011230 |165111692 |
**API Drawcall Count**: |189 |247 |
**Drawcall Count**: |5988 |568 |
**Drawcall Rate**: |460615 |43692 |
**State Changes Texture Count**:|384 |296 |
**Pipeline Count**: |62 |39 |
**Item Opaques**: |272 |410 |
**Item Translucents**: |111 |67 |
**Item Lights**: |11 |48 |
**Timing Opaques**: |0.874 |1.163 |
**Timing Translucents**: |0.15 |0.073 |
**Timing Lighting**: |0.015 |0.027 |
**Render Frame**: |1.507 |2.682 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |296 |202 |237
**Present Rate**: |295 |202 |236
**Present New Rate**: |248 |203 |217
**CPU Buffer Count**: |2240 |1218 |1214
**GPU Buffer Count**: |410 |215 |271
**CPU Memory Usage**: |28135312 |16961616 |17051472
**GPU Memory Usage**: |10874928 |7790640 |7884848
**CPU Texture Count**: |231 |128 |120
**GPU Texture Count**: |97 |86 |76
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |452242992 |146272608 |142696864
**GPU Texture Memory Usage**: |362576484 |328365021 |279606381
**GPU Virtual Memory Usage**: |362576484|328365021|279606381
**Triangle Count**: |154645 |82809 |111795
**Triangle Rate**: |77322500 |20702250 |37265000
**API Drawcall Count**: |53 |37 |67
**Drawcall Count**: |2693 |37 |71
**Drawcall Rate**: |1346500 |9250 |23666
**State Changes Texture Count**:|105 |65 |121
**Pipeline Count**: |34 |26 |26
**Item Opaques**: |39 |45 |101
**Item Translucents**: |13 |6 |11
**Item Lights**: |2 |16 |19
**Timing Opaques**: |0.148 |0.17 |0.288
**Timing Translucents**: |0.039 |0.019 |0.024
**Timing Lighting**: |0.014 |0.018 |0.013
**Render Frame**: |0.632 |1.397 |0.818


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Success
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success

**Comment by Nex-Pro** [comment]
## Rc 35 #9801

Intel i7 4.0ghz desktop 16gb ram
win10
Nvidia GTX1070

## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**:  SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS
**Additional Test Results + Observations**:


***Had an issue during the HMD tutorial. Saw hand controllers prior to holding hands up.
Then no controllers or hands for duration of tutorial.***

Happened again after resetting scripts and restarting client.

## HMD

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |89 |90 |89
**Present Rate**: |90 |89 |89
**Present New Rate**: |90 |90 |89
**CPU Buffer Count**: |3351 |3883 |1460
**GPU Buffer Count**: |979 |1261 |338
**CPU Memory Usage**: |41658512 |62960880 |24598288
**GPU Memory Usage**: |22189488 |44144048 |12363184
**CPU Texture Count**: |345 |278 |161
**GPU Texture Count**: |290 |237 |127
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |96396268 |79401344 |65420316
**GPU Texture Memory Usage**: |1284205042 |1226591994 |723625183
**GPU Virtual Memory Usage**: |1284205042|1226591994|723625183
**Triangle Count**: |497245 |530666 |62502
**Triangle Rate**: |45204090 |53066600 |5682000
**API Drawcall Count**: |178 |114 |26
**Drawcall Count**: |3638 |482 |38
**Drawcall Rate**: |330727 |48200 |3454
**State Changes Texture Count**:|347 |166 |47
**Pipeline Count**: |67 |36 |26
**Item Opaques**: |254 |168 |11
**Item Translucents**: |115 |24 |6
**Item Lights**: |11 |35 |0
**Timing Opaques**: |0.86 |0.476 |0.086
**Timing Translucents**: |0.22 |0.036 |0.032
**Timing Lighting**: |0.023 |0.015 |0.02
**Render Frame**: |1.691 |1.275 |0.781

## DESKTOP

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2878 |3846 |1038
**GPU Buffer Count**: |769 |858 |216
**CPU Memory Usage**: |45402256 |68634064 |28702480
**GPU Memory Usage**: |24323504 |25011632 |15414704
**CPU Texture Count**: |303 |280 |109
**GPU Texture Count**: |231 |179 |82
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |171852900 |372262680 |65029912
**GPU Texture Memory Usage**: |760359947 |1063494835 |274800340
**GPU Virtual Memory Usage**: |827468811|1130603699|341909204
**Triangle Count**: |322219 |773475 |95131
**Triangle Rate**: |20138687 |48342187 |5945687
**API Drawcall Count**: |178 |279 |19
**Drawcall Count**: |1831 |334 |19
**Drawcall Rate**: |114437 |20875 |1187
**State Changes Texture Count**:|361 |358 |41
**Pipeline Count**: |64 |41 |23
**Item Opaques**: |258 |425 |3
**Item Translucents**: |102 |63 |4
**Item Lights**: |11 |46 |0
**Timing Opaques**: |0.84 |1.154 |0.186
**Timing Translucents**: |0.138 |0.124 |0.046
**Timing Lighting**: |0.025 |0.031 |0.043
**Render Frame**: |1.837 |3.026 |1.953


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|check
**Test 2**|Install a fresh copy of "Home' and do tutorial|Fail: see notes
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|success
**Test 4**|Launch firework, on dev-playa, can other hear?|success
**Test 5**|Switch avatar and make sure it does not crash|success
**Test 6**|Test group functions|untested
**Test 7**|Test Ambisonic audio with markeplace item|success
**Test 8**|Enrure that you can distance grab|success
**Test 9**|Bring up and edit an objects with hand controllers|success
**Test 10**|Test PAL functionality|SUCCESS
**Test 11**|Test Tablet in 2D and 3D|SUCCESS

Felt scrolling with mouse on the tablet still not super slick.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74323cb1f0065e3e41c97b8c615cdb12de50f370 available at: https://gist.github.com/fc68983b657e7d34c31ae9d9f13359a5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-74323cb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-74323cb.dmg

**Comment by kevinmthomasse** [comment]
re-testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Re-ran tutorial using the Oculus and Oculus Touch.  Hand controllers WERE present and behavior was expected as normal.  Success.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |332 |227 |224
**Present Rate**: |333 |226 |223
**Present New Rate**: |293 |207 |204
**CPU Buffer Count**: |2142 |1624 |1121
**GPU Buffer Count**: |896 |430 |318
**CPU Memory Usage**: |21788688 |21732752 |14345520
**GPU Memory Usage**: |15881520 |12004720 |8029488
**CPU Texture Count**: |256 |142 |119
**GPU Texture Count**: |232 |94 |86
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |65772668 |193436740 |106957900
**GPU Texture Memory Usage**: |776746646 |331816547 |315847747
**GPU Virtual Memory Usage**: |776746646|331816547|315847747
**Triangle Count**: |73938 |253822 |180221
**Triangle Rate**: |36969000 |63455500 |45055250
**API Drawcall Count**: |57 |100 |91
**Drawcall Count**: |2828 |109 |95
**Drawcall Rate**: |1414000 |27250 |23750
**State Changes Texture Count**:|99 |121 |139
**Pipeline Count**: |34 |39 |33
**Item Opaques**: |57 |271 |171
**Item Translucents**: |12 |59 |28
**Item Lights**: |2 |38 |22
**Timing Opaques**: |0.173 |0.969 |0.362
**Timing Translucents**: |0.04 |0.039 |0.055
**Timing Lighting**: |0.016 |0.013 |0.018
**Render Frame**: |0.646 |2.145 |1.143

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS

**Comment by hifi-gustavo** [comment]
Build console output for commit: c52c43e23d27142118fae920b37970f61f67cfc1 available at: https://gist.github.com/fc68983b657e7d34c31ae9d9f13359a5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-c52c43e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9801-c52c43e.dmg

**Comment by Nex-Pro** [comment]
### Beta Release 35
Testing platform: Win10 Pro 64
CPU 4.0 ghz i7
ram: 16gb
gpu: Nvidia GTX1070 8gb Vram.

## QA Test

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: ** SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: N/A

**QA Pass**: SEE NOTES

**Additional Test Results + Observations**: 
Had to reload createtestblocksjs in running scripts for it to work. Subsequent runs ok.
Had to reload harmonic oscillator in running scripts for it to work.


Stray hud element noticed ( known issue )
createtestblocks.js loaded but did not run until I refreshed it ( welcome )

### HMD STATS:
**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |89 |89
**Present Rate**: |89 |90 |89
**Present New Rate**: |89 |90 |90
**CPU Buffer Count**: |3465 |5227 |646
**GPU Buffer Count**: |880 |1360 |213
**CPU Memory Usage**: |43171920 |84722928 |28227344
**GPU Memory Usage**: |20598128 |39081392 |11748784
**CPU Texture Count**: |419 |472 |81
**GPU Texture Count**: |313 |349 |57
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |252243652 |361076836 |39338824
**GPU Texture Memory Usage**: |1348528177 |1385276827 |460002823
**GPU Virtual Memory Usage**: |1348528177|1515855259|501452295
**Triangle Count**: |529722 |896146 |65098
**Triangle Rate**: |52972200 |81467818 |5918000
**API Drawcall Count**: |187 |141 |32
**Drawcall Count**: |5118 |550 |50
**Drawcall Rate**: |511800 |50000 |4545
**State Changes Texture Count**:|374 |213 |52
**Pipeline Count**: |55 |35 |31
**Item Opaques**: |271 |225 |14
**Item Translucents**: |89 |29 |8
**Item Lights**: |11 |39 |0
**Timing Opaques**: |0.773 |0.878 |0.119
**Timing Translucents**: |0.205 |0.037 |0.081
**Timing Lighting**: |0.018 |0.014 |0.033
**Render Frame**: |1.616 |1.696 |1.312

### DESKTOP STATS:
**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2271 |2707 |589
**GPU Buffer Count**: |678 |651 |155
**CPU Memory Usage**: |35527184 |41447120 |20020240
**GPU Memory Usage**: |17603248 |17640112 |9181872
**CPU Texture Count**: |230 |217 |45
**GPU Texture Count**: |173 |143 |32
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |177183184 |222316292 |33572604
**GPU Texture Memory Usage**: |661383740 |654713834 |222700796
**GPU Virtual Memory Usage**: |661383740|654713834|222700796
**Triangle Count**: |203659 |697828 |27237
**Triangle Rate**: |12728687 |43614250 |1602176
**API Drawcall Count**: |163 |232 |16
**Drawcall Count**: |1157 |285 |16
**Drawcall Rate**: |72312 |17812 |941
**State Changes Texture Count**:|327 |262 |36
**Pipeline Count**: |63 |38 |21
**Item Opaques**: |251 |397 |3
**Item Translucents**: |96 |53 |2
**Item Lights**: |11 |40 |0
**Timing Opaques**: |0.827 |1.002 |0.035
**Timing Translucents**: |0.103 |0.05 |0.009
**Timing Lighting**: |0.018 |0.018 |0.014
**Render Frame**: |1.436 |2.074 |0.505


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo| **SUCCESS**
**Test 2**|Install a fresh copy of "Home' and do tutorial| **SUCCESS**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.| **SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?| **SUCCESS**
**Test 5**|Switch avatar and make sure it does not crash| **SUCCESS**
**Test 6**|Test group functions| **UNTESTED**
**Test 7**|Test Ambisonic audio with markeplace item| **SUCCESS**
**Test 8**|Enrure that you can distance grab| **SUCCESS**
**Test 9**|Bring up and edit an objects with hand controllers| **SUCCESS**
**Test 10**|Test PAL functionality| ** Tested volume and ignore  OK. Typing display name updates avatar display name. **
**Test 11**|Test Tablet in 2D and 3D| **SUCCESS**


Additional notes:

We observed that particles ( fireworks ) Are being culled when the emitter is out of view. This has the effect of making the particle trail either flash on and off with head movement or disappear prematurely.

**Pull request merged**
