### PR TITLE
Workaround buffer corruption rc68

### PR DESCRIPTION
**Pull request by gcalero**
Same PR [#13287](https://github.com/highfidelity/hifi/pull/13287) against RC68

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10322/HighFidelity-Beta-PR13289-44027f7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10322/HighFidelity-Beta-PR13289-44027f7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10322/HighFidelity-Beta-Interface-PR13289-44027f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10322/HighFidelity-Beta-PR13289-44027f7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10322/HighFidelity-Beta-Interface-PR13289-44027f7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No strange filter appears. Switching domains looks good.

**Pull request merged**
