### PR TITLE
Adds a fix for a rendering issue where models with a texture driving both color and opacity would be rendered fully opaque

### PR DESCRIPTION
**Pull request by ericrius1**
This PR also introduces an early draft of a weather box widget, which will eventually sit in the home space and display the current weather.

### CODE REVIEW

**Comment by imgntn** [comment]
@ericrius1 there are two weatherbox.js files here

**Comment by ericrius1** [comment]
I'm including this first draft because it demonstrates the rendering fix, and was what originally let to me noticing the issue. To see the difference, run the weather box with this build, and run it with current release. You'll notice with release build, the weather box is fully solid and obscures the lightning storm within.
I'm including this first draft because it demonstrates the rendering fix, and was what originally let to me noticing the issue. To see the difference, run the weather box with this build, and run it with current release. You'll notice with release build, the weather box is fully solid and obscures the lightning storm within, whereas with the build, you can see through the box into the brewing storm

https://rawgit.com/ericrius1/hifi/droplets/examples/flowArts/weatherBox.js

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ffcf437e9f7edbb78650f843f38757427115b12 available at: https://gist.github.com/84bb1d733fb7f2efc8a8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6876.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6876.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b75cbea3a6fd7ec7219f5f370096fbcb97446ab available at: https://gist.github.com/84bb1d733fb7f2efc8a8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6876.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6876.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f646dc193e5a3552360af0398cf9c8a9ba97e2b available at: https://gist.github.com/84bb1d733fb7f2efc8a8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6876.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6876.dmg

**Comment by judasshuffle** [comment]
Looks great but disappears  if either ambient occlusion or anti aliasing are enabled . Good to see transparent textures working

**Comment by cozza13** [comment]
@judasshuffle , thanks for this.

**Comment by samcake** [comment]
REvert because it has too much side effects with transparent textures
we will come up with a better fix

**Pull request merged**
