### PR TITLE
Don't include old attachment data on new avatar recordings

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/17590/Include-avatar-entities-in-recordings

This PR won't include avatar attachments on new avatar recordings. It will still load attachments included on previous recordings. Now avatar entities will be added to the recordings.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12200/HighFidelity-Beta-PR13841-c564119.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12200/HighFidelity-Beta-PR13841-c564119.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12200/HighFidelity-Beta-Interface-PR13841-c564119.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12200/HighFidelity-Beta-PR13841-c564119.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12200/HighFidelity-Beta-Interface-PR13841-c564119.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12207/HighFidelity-Beta-PR13841-dc0fbcc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12207/HighFidelity-Beta-PR13841-dc0fbcc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12207/HighFidelity-Beta-Interface-PR13841-dc0fbcc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12207/HighFidelity-Beta-PR13841-dc0fbcc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12207/HighFidelity-Beta-Interface-PR13841-dc0fbcc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12215/HighFidelity-Beta-PR13841-8bd9bf3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12215/HighFidelity-Beta-PR13841-8bd9bf3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12215/HighFidelity-Beta-Interface-PR13841-8bd9bf3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12215/HighFidelity-Beta-PR13841-8bd9bf3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12215/HighFidelity-Beta-Interface-PR13841-8bd9bf3.exe

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12219/HighFidelity-Beta-PR13841-8bd9bf3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12219/HighFidelity-Beta-PR13841-8bd9bf3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12219/HighFidelity-Beta-Interface-PR13841-8bd9bf3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12219/HighFidelity-Beta-PR13841-8bd9bf3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12219/HighFidelity-Beta-Interface-PR13841-8bd9bf3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12288/HighFidelity-Beta-PR13841-5f4903f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12289/HighFidelity-Beta-PR13841-5a5aa2f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12289/HighFidelity-Beta-PR13841-5a5aa2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12289/HighFidelity-Beta-Interface-PR13841-5a5aa2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12289/HighFidelity-Beta-PR13841-5a5aa2f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12289/HighFidelity-Beta-Interface-PR13841-5a5aa2f.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
- Install this PR including the server client. 
- Make sure your avatar is wearing some avatar entities.
- Make an avatar recording with this app: https://highfidelity.com/marketplace/items/27008ad4-292e-40be-80d5-0ebdcf2740fa.
- When playing back the recording, make sure the avatar entities are rendered.

**Comment by jakram** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12310/HighFidelity-Beta-PR13841-b3d127c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12310/HighFidelity-Beta-PR13841-b3d127c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12310/HighFidelity-Beta-Interface-PR13841-b3d127c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12310/HighFidelity-Beta-PR13841-b3d127c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12310/HighFidelity-Beta-Interface-PR13841-b3d127c.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
PASS @conklin94122 

Neither one avatar record or multiple ones make the attachment "blink".

Avatar entities render properly as required in the test plan.

**Pull request merged**
