### PR TITLE
fixed compile error if QT_CMAKE_PREFIX_PATH was not set

### PR DESCRIPTION
**Pull request by nbq**
The changes to the quazip cmake made it unable to run cmake unless QT_CMAKE_PREFIX_PATH was set, which not everyone has.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by murillodigital** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53e58aea439e0f5b04c9d33db43fd3c0082a3f6e available at: https://gist.github.com/062537b1a9ee6f67ca66<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6502.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6502.dmg

**Comment by hyperlogic** [comment]
Hey, I addressed this with https://github.com/highfidelity/hifi/pull/6501, which beat this PR by 1 hour.

**Pull request closed without merging**
