### PR TITLE
RC-58: Fix entity serialization bug due to Zone Haze group properties

### PR DESCRIPTION
**Pull request by NissimHadar**
The Packet Header has been bumped up to 79.
An issue with Haze Properties overlapping in the Zone packet has been resolved.

This should also resolve https://highfidelity.fogbugz.com/f/cases/8802 (Scene doesn't properly load)

## TEST PLAN 
Execute the repro case detailed in the bug 8802, it doesn't repro in this pr compare to current tip of RC-58

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4578/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4578/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4584/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4584/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4587/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.dmg

**Comment by Nex-Pro** [comment]
Testing Win10

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4587/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.exe

**Comment by Nex-Pro** [comment]
Using new build

**Comment by Nex-Pro** [comment]
I've tested this using the content file and running the sandbox locally. I see all the content load really fast each time. I moved between domains and back. Did multiple change domain and return. Multiple change domain, clear cache and return. Also restart interface. It all looks fine. Build c1d879

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4594/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4594/HighFidelity-Beta-PR11721-c1d8796f7d2384e808f067016e9a8934e29ac9b1.exe

**Comment by NissimHadar** [comment]
Based on wrong commit.

**Pull request closed without merging**
