### PR TITLE
Added Upstream Servers setting to domain server

### PR DESCRIPTION
**Pull request by seefo**
Should fix https://highfidelity.fogbugz.com/f/cases/5319/Add-upstream-servers-table-to-Replication-section

Looks like the commit for the previous PR disappeared so recreating this PR

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/749/HighFidelity-Beta-PR10703-d0b0382495b952c76644eb1be5f8bde9bccf0577.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/859/HighFidelity-Beta-PR10703-d4f98e6a850dc54d35684a442f7cddf7902cfbf6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/859/HighFidelity-Beta-PR10703-d4f98e6a850dc54d35684a442f7cddf7902cfbf6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/869/HighFidelity-Beta-PR10703-7ae69e0549dbf2253f276dad60f3e1b944415cb9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/869/HighFidelity-Beta-PR10703-7ae69e0549dbf2253f276dad60f3e1b944415cb9.dmg

**Comment by birarda** [comment]
Closing this because I picked it in to my PR

**Pull request closed without merging**
