### PR TITLE
Tablet webview now uses mobile format

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan 
- In tablet mode, in goto click the info of a card
- click on the tweet button, once on the login page click the sign-up button
- check that the sign-up page uses the mobile version (fix on the tablet screen)

**Comment by hifi-gustavo** [comment]
Build console output for commit: b10f491c6ed1236408c7f8b0a39bad7ccba52caf available at: https://gist.github.com/dcf7abfb92a1e6306bed75c3fafe4407<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-b10f491.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-b10f491.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b10f491c6ed1236408c7f8b0a39bad7ccba52caf available at: https://gist.github.com/dcf7abfb92a1e6306bed75c3fafe4407<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-b10f491.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-b10f491.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ca7ad5e0b97b797a9435f490673c7cfc74f649c available at: https://gist.github.com/dcf7abfb92a1e6306bed75c3fafe4407<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-7ca7ad5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-7ca7ad5.dmg

**Comment by StarmanF** [comment]
testing

**Comment by StarmanF** [comment]
**Desktop PC - Windows 10 Education - CPU 4.0GHz Intel i7 - GTX1080 - RAM 16GB - Vive**

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10095-7ca7ad5.exe

**Pass**

Notes:

- Tested in Tablet Mode

- Navigated to twitter sign up page, through the tweet button on the info page of a GOTO card.

- Twitter sign up page uses mobile version, as expected.

**Pull request merged**
