### PR TITLE
Resolved : Tablet "X" Button does not go back, just closes tablet.

### PR DESCRIPTION
**Pull request by NeetBhagat**
Fix for case 4980: Tablet "X" Button does not go back, just closes the tablet
https://highfidelity.fogbugz.com/f/cases/4980

**Bug details**
First start the Interface and End up in welcome (or dev-welcome), open the tablet, and the help screen is already up, and when you press the "X" button on tablet, it prevent the tablet to going back to the main app menu or closes the tablet.

**How To Test**
1. Clean the install of Interface (i.e.) NO config in appData tree.
2. Do NOT start sandbox.
3. Start Interface.
4. End up in welcome (or dev-welcome).
5. Bring up tablet immediately[using mouse right click].
6. it's displaying "help" content on tablet.
7. press the "X" button on tablet.

**Expected Result**
When you press "X" button on tablet, the tablet screen will go back to the main menu screen.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1585/HighFidelity-Beta-PR10949-be7a235c566c04b38d830d0dfe01fd654ceabf77.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1585/HighFidelity-Beta-PR10949-be7a235c566c04b38d830d0dfe01fd654ceabf77.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1659/HighFidelity-Beta-PR10949-f7f6dd6ae09dfea77fef2b96e58b25c2e9ad2218.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1659/HighFidelity-Beta-PR10949-f7f6dd6ae09dfea77fef2b96e58b25c2e9ad2218.dmg

**Comment by druiz17** [comment]
Here is the PR that solves to root issue.
https://github.com/highfidelity/hifi/pull/10959

**Pull request closed without merging**
