### PR TITLE
[RC75] Create APP tooltip / Adressed CR comments / Regression

### PR DESCRIPTION
**Pull request by thoys**
Addresses CR comments on https://github.com/highfidelity/hifi/pull/14229

## QA test
- https://highfidelity.testrail.net/index.php?/tests/view/138617 (tooltips desktop)
- https://highfidelity.testrail.net/index.php?/tests/view/138628 (tooltips HMD)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14532/HighFidelity-Beta-PR14309-20f6e69.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14532/HighFidelity-Beta-PR14309-20f6e69.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14532/HighFidelity-Beta-Interface-PR14309-20f6e69.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14532/HighFidelity-Beta-PR14309-20f6e69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14532/HighFidelity-Beta-Interface-PR14309-20f6e69.exe

**Comment by ZappoMan** [comment]
This is not a show stopper. It's too late. Fix it in master and all good.

**Pull request closed without merging**
