### PR TITLE
Case 15420: Fix ESS sometimes not getting the parents/children of entities with scripts.

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript ticket](https://highfidelity.manuscript.com/f/cases/15420/ESS-script-could-not-get-properties-of-its-parent)

In the current state, the ES would only send the ancestor/descendants of an entity with a server script if an edit was made to that entity by anyone after the server started.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17055/HighFidelity-Beta-PR14857-8b32a62.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17055/HighFidelity-Beta-PR14857-8b32a62.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17055/HighFidelity-Beta-Interface-PR14857-8b32a62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17055/HighFidelity-Beta-PR14857-8b32a62.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17055/HighFidelity-Beta-Interface-PR14857-8b32a62.exe

**Comment by AndrewMeadows** [comment]
Ok this looks good.  I cloned the branch and built on linux.  Then I stepped through the repro recipe on case 15420 and found it bugged on master but fixed in this PR.

**Pull request merged**
