### PR TITLE
case DEV-2709: reset QAudioDevInfo on switch

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2709

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22506/HighFidelity-Beta-PR16487-3939c7e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22506/HighFidelity-Beta-Interface-PR16487-3939c7e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22506/HighFidelity-Beta-PR16487-3939c7e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22506/HighFidelity-Quest-Beta-PR16487-3939c7e.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22506/HighFidelity-Beta-PR16487-3939c7e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22506/HighFidelity-Beta-Interface-PR16487-3939c7e.exe

**Comment by JeffClinton** [comment]
Pre-merge testing

**Pull request merged**
