### PR TITLE
remove the close activity from Interface

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc6ac9081fa42ed94fc89d28bc773f373bd28ff8 available at: https://gist.github.com/b76039afdc6a4da64093<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4440.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4440.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0fe843db019d644b4534e05f91c47e8d33d2d468 available at: https://gist.github.com/b76039afdc6a4da64093<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4440.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4440.dmg

**Comment by ZappoMan** [comment]
So we are still going to send launch, but not close? So basically back to where we were when Philip said the stats were wrong? I'm just confirming.

**Comment by birarda** [comment]
@ZappoMan yes - cleared it with him that the stats will be fixed using UserLocation data shortly but that this was preferable to the hang on shutdown on win, and preferable to ever having a TCP request we must get out while the application is closing.

**Comment by birarda** [comment]
I had removed launch in this PR but I think killing that entirely requires a bit more thought (we probably want to know what platform our users are on)

**Pull request merged**
