### PR TITLE
fix default skybox behavior

### PR DESCRIPTION
**Pull request by zzmp**
- shows default skybox when none is set
- shows color as skybox when a color other than black(0,0,0) is set
- shows texture as skybox when a texture is set
- shows tinted texture as skybox when a color other than black(0,0,0) and a texture are set

### CODE REVIEW

**Comment by zzmp** [comment]
QA:

Test this for skyboxes and procedural skyboxes:
- If there is a procedural skybox set, it should be shown, not the default (it may need to load first)
- If there is no skybox set, the default horizon should show
- If there is a color (other than 0,0,0) set, the color should be used as the skybox (this is new)
- If there is a texture set, the texture should be used as the skybox
- If there is a color (other than 0,0,0) and a texture set, a tinted version of the texture should be used as the skybox
- When you turn off your skybox, the default should come back

**Comment by hifi-gustavo** [comment]
Build console output for commit: c740b263a8ffe0c3cee2bd5722afe2961d1be9be available at: https://gist.github.com/d45117db8f8ae1b20adcfdff4cadb425<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8516-c740b26.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8516-c740b26.dmg

**Comment by Nex-Pro** [comment]
#### QA PASS

Win10

QA:

Test this for skyboxes and procedural skyboxes:

If there is a procedural skybox set, it should be shown, not the default (it may need to load first): **SUCCESS**
    Ocean skybox worked fine.
    Was unable to get procedural to work using the markeplace day night cycle skybox.(probably not due to this PR)

If there is no skybox set, the default horizon should show: **SUCCESS**

If there is a color (other than 0,0,0) set, the color should be used as the skybox (this is new): **SUCCESS**

If there is a texture set, the texture should be used as the skybox: **SUCCESS**

If there is a color (other than 0,0,0) and a texture set, a tinted version of the texture should be used as the skybox:  **SUCCESS**

When you turn off your skybox, the default should come back: **SUCCESS**
    I set skybox to not visible and the normal sky for the location became visible.

**Comment by Nex-Pro** [comment]
#### Feedback:

Seems odd that rgb 0,0,0  and 255,255,255 seem to have the same effect.

**Pull request merged**
