### PR TITLE
Small QML fixes

### PR DESCRIPTION
**Pull request by jherico**
* Modal frame decoration and title were missing
* Spurious logging warnings about null values in QML
* Better font awesome based button
* File dialog keyboard and layout polish
* Prevent window jumping on click.  Only re-position a window if it's fully off screen.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ba501deb7c099d2eedac9780e6c4910dbeff82f available at: https://gist.github.com/7328d14325d6a7b65a21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.dmg

**Comment by OmegaHeron** [comment]
Tested Windows - All dialogs presented in Setting option set have titles as well as running scripts, load script from file and load script from URL.  The only dialog I found that has no title was edit.js props window.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c71a20b2f0e3839ce8426bf6df25c5579acbb6e3 available at: https://gist.github.com/7328d14325d6a7b65a21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c71a20b2f0e3839ce8426bf6df25c5579acbb6e3 available at: https://gist.github.com/7328d14325d6a7b65a21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aecf582593ec9b3a28d2d9540ec6f55e42ffe7fc available at: https://gist.github.com/7328d14325d6a7b65a21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4860c7d4f17660377221739751637241d5a9bf39 available at: https://gist.github.com/7328d14325d6a7b65a21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7004.dmg

**Comment by imgntn** [comment]
tested on win10, working well

**Pull request merged**
