### PR TITLE
Incomplete sandbox content updates are now removed and reperformed

### PR DESCRIPTION
**Pull request by seefo**
Should fix https://highfidelity.fogbugz.com/f/cases/4565/Partial-content-set-download-leaves-ac-and-domain-server-in-partially-loaded-state

Test Plan 1:
1. Start sandbox -- once it's finished starting for the first time, close it
2. Create the following file: `AppData%/Roaming/High Fidelity - PR10693/.updating`
3. Start sandbox -- verify it begins the update process, and that it replaces the old content files as well as removing the `.updating` file that we had created

Test Plan 2:
1. Start sandbox -- while it downloads the content update, close/terminate it before it completes
2. Verify that `AppData%/Roaming/High Fidelity - PR10693/.updating` exists
3. Start sandbox -- verify it begins the update process, and that it replaces the old content files as well as removing the `.updating` file that we had created

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Will test when built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/720/HighFidelity-Beta-PR10693-9fa21fc79f8dc2ac6330327037b6da2fcd646819.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/720/HighFidelity-Beta-PR10693-9fa21fc79f8dc2ac6330327037b6da2fcd646819.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

(Sorry for the delay, had to briefly go AFK)

Test Plan 1:
**Fail** Unfortunately after creating file and re-running sandbox, it didn't seem to do any downloading or such.

image


Test Plan 2:
**Fail** Cannot proceed without the steps in Test Plan 1 working.

Please let me know if there's anything I can try to replicate correct behaviour. :)

**Comment by seefo** [comment]
@YuppyPlays Looks like I made a typo in the test plan.  We should be creating the file inside our Roaming folder, not our Local folder.  Apologies!  Please try again, I've updated the test plan.

**Comment by YuppyPlays** [comment]
Testing complete:

Good news, that did the trick :D 

Test Plan 1:
All **Passes**

Test Plan 2:
Also All **Passes** :)

Let me know if you require any further testing, but this looks good to me.

**Pull request merged**
