### PR TITLE
FB15569 - Debug default scripts no longer on developer menu

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/15569/Debug-default-scripts-no-longer-on-developer-menu

*** Test plan *** 

Ensure 'Developer' menu has menu item 'Debug defaultScripts.js'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10376/HighFidelity-Beta-PR13310-b954ac6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10376/HighFidelity-Beta-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10376/HighFidelity-Beta-Interface-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10376/HighFidelity-Beta-PR13310-b954ac6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10376/HighFidelity-Beta-Interface-PR13310-b954ac6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10386/HighFidelity-Beta-PR13310-b954ac6.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10385/HighFidelity-Beta-PR13310-b954ac6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10386/HighFidelity-Beta-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10386/HighFidelity-Beta-Interface-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10385/HighFidelity-Beta-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10385/HighFidelity-Beta-Interface-PR13310-b954ac6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10385/HighFidelity-Beta-PR13310-b954ac6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10385/HighFidelity-Beta-Interface-PR13310-b954ac6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10386/HighFidelity-Beta-PR13310-b954ac6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10386/HighFidelity-Beta-Interface-PR13310-b954ac6.exe

**Comment by qlimguicheteau** [comment]
Currently Testing

**Comment by qlimguicheteau** [comment]
Pass @conklin94122 
"Debug defaultScripts.js" appears as the last entry under the Developer settings.

**Pull request merged**
