### PR TITLE
make marketplace tablet be clientOnly

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes https://highfidelity.fogbugz.com/f/cases/1616/Market-tablet-can-be-moved-by-other-avatars

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan: 
-- let me know when you're testing this, and I'll join you. It takes two in HMD. Here's what we'll do:

Both run any recent build. It doesn't have to be the PR.
One person creates a marketplace tablet using the master/default scripts. The other person manipulates it (which is the bug).
The other person creates a marketplace tablet using the scripts from this PR. The first person cannot manipulate it.

I've been running into other issues which also happen in master, such as very low frame rate while trying to do this, or being unable to create tablets in certain domains. This pr doesn't address those.

**Comment by thoys** [comment]
duplicate https://github.com/highfidelity/hifi/pull/8658

**Comment by thoys** [comment]
The problem with this is that it will be still there on re-load, I have set my PR to DNM because I was planning to add it's entityID to the settings file.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b377127fc12edcccd5d06039a2bc079d3e526d6a available at: https://gist.github.com/be233082314d66482c953e9e3f067cca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-b377127.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-b377127.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78f96a80bd217827a439afa0862611eec5ac97ed available at: https://gist.github.com/be233082314d66482c953e9e3f067cca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-78f96a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-78f96a8.dmg

**Comment by thoys** [comment]
hi, sure @howard-stearns the parent check is a good solution aswell, but take note that the tablet would be saved in the settingsfile anyways as clientOnly entity,

Anyways the parent check should be fine too. Goodluck 👍

**Comment by howard-stearns** [comment]
additional test plan:
- open marketplace (desktop and hmd) and go to another domain. should still be there
- open marketplace (desktop and hmd) and quit with it open (or crash interface with it open). On restart, marketplace should not be open.
- open marketplace in hmd in a domain in which you don't have rez permission. should still work.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d232d115d5ae5e4870ccbfd9ccfeee5d78927102 available at: https://gist.github.com/be233082314d66482c953e9e3f067cca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-d232d11.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8794-d232d11.dmg

**Comment by howard-stearns** [comment]
Quite right @thoys. There are other issues with the parent-search check solution: semantics of what to use if someone else uses libraries/WebTablet.js for another purpose, possible race conditions, and small bugs that muddy the code.  So I went with the persisted data idea after all, checking on script-start for that data and deleting it to make us clean.

**Comment by cozza13** [comment]
Tested the tablet with @Nex-Pro and @thoys passed all requirements. Interestingly, if you close interface while still holding the tablet, the avatar goes small and the tablets zooms off into the sky.

QA pass

**Comment by sethalves** [comment]
That's just the tablet returning to its home planet.

**Pull request merged**
