### PR TITLE
use tablet model from distribution rather than from s3

### PR DESCRIPTION
**Pull request by sethalves**
- use tablet model from distribution rather than from s3

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- enable advanced menus
- Menu --> Edit --> Reload Content (Clears all caches)
- make sure the tablet still works

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9bdbb92efa9693c24a8eddcb88e233ba5a4162f available at: https://gist.github.com/b5807bf2520c7e538b75411868c46ed4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9585-d9bdbb9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9585-d9bdbb9.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### PASS

Works in HMD mode and desktop after clearing cache from tablet menu.

Had a crash bugsplat sent. Tried to repro but could not, so bugsplat message may not be relevant.

**Pull request merged**
