### PR TITLE
Case 21326 - missing marketplaceInject.js

### PR DESCRIPTION
**Pull request by roxanneskelly**
The re-addition of marketplaceInject.js didn't merge from 80
for some reason.

### CODE REVIEW

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/21326/See-All-Markets-page-is-missing-its-footer-and-the-two-Explore-buttons-no-longer-work

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18044/HighFidelity-Beta-PR15152-e4e8a61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18044/HighFidelity-Beta-Interface-PR15152-e4e8a61.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18044/HighFidelity-Beta-PR15152-e4e8a61.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18044/HighFidelity-Quest-Beta-PR15152-e4e8a61.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18044/HighFidelity-Beta-PR15152-e4e8a61.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18044/HighFidelity-Beta-Interface-PR15152-e4e8a61.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18052/HighFidelity-Beta-PR15152-e4e8a61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18052/HighFidelity-Beta-Interface-PR15152-e4e8a61.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18052/HighFidelity-Beta-PR15152-e4e8a61.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18052/HighFidelity-Beta-Interface-PR15152-e4e8a61.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18052/HighFidelity-Beta-PR15152-e4e8a61.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18052/HighFidelity-Quest-Beta-PR15152-e4e8a61.apk)

**Pull request merged**
