### PR TITLE
21378 : fading effect

### PR DESCRIPTION
**Pull request by Zvork**
Cleaned up a bit, working fade on loaded objects except certain items (need to generalize), generalized to all shaders in deferred render pipelines. Still need to move to uniforms and generalize to all objects.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
Ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/438/HighFidelity-Beta-PR10626-e7eca7728f791f52457948bafbbdf668c055b6fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/438/HighFidelity-Beta-PR10626-e7eca7728f791f52457948bafbbdf668c055b6fd.exe

**Comment by Zvork** [comment]
Extended fade to polyvox items. Faded objects cast correct shadows as well as skinned ones. Suspended work on fade on shape items as we can't handle it properly at this time with instanced objects.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/535/HighFidelity-Beta-PR10626-7d58c9a741d0eca2b46326847e79170a17ed8652.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/535/HighFidelity-Beta-PR10626-7d58c9a741d0eca2b46326847e79170a17ed8652.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/536/HighFidelity-Beta-PR10626-0850f9fcad3809003641d19336eccdae69b3057c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/536/HighFidelity-Beta-PR10626-0850f9fcad3809003641d19336eccdae69b3057c.exe

**Comment by Zvork** [comment]
This PR is ready for review and shouldn't be considered WIP anymore.

- Fade parameters and data centralized in FadeEffect singleton.
- Fade working on opaque & transparent Models, voxel items and shadow cast by these elements.
- Fade not working on shape items because of current design issues with instancing.
- debugFade.qml script adds two new parameters "Duration" and "Scale" to adjust time duration of fade effect and the scaling of the noise mask function.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/639/HighFidelity-Beta-PR10626-57ddd8f0ddf79451256d8ddcdccdb16cabfd4c0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/639/HighFidelity-Beta-PR10626-57ddd8f0ddf79451256d8ddcdccdb16cabfd4c0b.exe

**Comment by AndrewMeadows** [comment]
Needs a test plan.

**Comment by Zvork** [comment]
There seems to be an issue with rendering on this PR. Objects are sometimes tinted in red and it seems view dependent. I am debugging this and will report back, and add a test plan too.

**Comment by Zvork** [comment]
**Fade Effect Test Plan**

_Normal use case_
Goto a new world or place with uncached models.
1. New Models and Voxel items should appear with 3D inverse disolving fade effect.
2. Effect should last around 3s per object (unless modified by debug interface, see below).
3. Scale of effect should be the same for each object, whatever its size.
4. Disolve 3D pattern should be stable and not vary if an object is translating during fading.
5. Disolve 3D pattern should cast the correct disolved shadows.

_Debug use case_
Load and run the scripts\developer\utilities\render\debugFade.qml script file.
1. An interface should appear at the top left of the interface window
2. Moving the "Scale" slider should change the scale of the disolve 3D pattern (this can be viewed only when new models are loaded into the world, or if "Manual Fade" is enabled).
3. Moving the "Duration" slider should change the duration of the fade effect (this can be viewed only when new models are loaded into the world)
4. Enabling the "Manual Fade" checkbox should force the disolve on all objects. The fade percent slider to the right should vary the disolve intensity from full (left) to none (right).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/688/HighFidelity-Beta-PR10626-5eeff5aa28902033d0ea99de4062f24cb6346a3b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/688/HighFidelity-Beta-PR10626-5eeff5aa28902033d0ea99de4062f24cb6346a3b.exe

**Comment by samcake** [comment]
I m going to put DNM on this PR as it is a prototype branch where we try to demonstrate the fading effect while deveolping it.
I m going to work with @Zvork  to make an upstream branch with it for now because we will have more iteration on this before it s ready to go in master

**Comment by Zvork** [comment]
Removed test if physics was enabled in the "EntitiesShouldFadeFunction" to fix the cases when fade wasn't activated for new elements on some occasions (I haven't really pinpointed the causes for these cases but it usually happens when going back to a previously visited place that is in the navigation history). Not really sure of the side effects of this fix and why this test was there in the first place.

**Updated Test Plan**
This should be added to the previous test plan for the _Normal Use Case_.
6. Goto any new place and check that all new entities appear with the fade effect. Then go to another new place. Again, the entities should all appear with the fade effect. Ping-ponging back and forth between these two places with the navigation history should always yield the fading effect on all model and voxel entities.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/846/HighFidelity-Beta-PR10626-21276a85adaf708df4cf4ce50dc06862da57f28f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/846/HighFidelity-Beta-PR10626-21276a85adaf708df4cf4ce50dc06862da57f28f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/851/HighFidelity-Beta-PR10626-0211338657ab5d9cd6201aac9fd21fb19eee4c9c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/851/HighFidelity-Beta-PR10626-0211338657ab5d9cd6201aac9fd21fb19eee4c9c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1096/HighFidelity-Beta-PR10626-1bb0d51849fee2b175f4bd439b86b7bac05fde66.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1096/HighFidelity-Beta-PR10626-1bb0d51849fee2b175f4bd439b86b7bac05fde66.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1279/HighFidelity-Beta-PR10626-ec1cf9dc5068e22918db26e23e8deb73e4bfeac5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1280/HighFidelity-Beta-PR10626-972db8f54c04312eceee9cbe778c654b1358fbff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1280/HighFidelity-Beta-PR10626-972db8f54c04312eceee9cbe778c654b1358fbff.exe

**Comment by samcake** [comment]
test this please

**Comment by Zvork** [comment]
**FADE EDITION**
_Gradients_
The fade effect is based on the thresholding of a gradient in 3D space with values between 0 and 1. When the gradient has a value beneath the threshold, the object is transparent. This gradient is the sum of a base radial gradient centered on the object's position (with value 0 at this position) and a noise gradient. Each base and noise gradient level can be modified as well as the size of these gradients in the three dimensions.

The threshold result can be inverted with the "Invert" check box in which case the transparent pixels correspond to gradient values above the threshold. 

_Edges_
The outer edge of the fade effect is the limit between transparent and opaque pixels. The inner edge is set with the "edge width" parameter, between 0 and 1 as a ratio of the gradient size. Both edges have separate colors and color intensities, in the emissive channel.
 
**TEST PLAN**
Load and run the scripts\developer\utilities\render\debugFade.qml script file.

1. An interface should appear at the top left of the interface window
2. Checking the "Edit Fade" checkbox will apply the fade effect on the currently "selected" element. This "selected" element will have it's bounding box displayed. The selection is based on the closest intersecting bounding box in the direction of the camera.
3. The combo box to the right of the checkbox selects the fade event to edit. 
4. In edit mode, the events will "animate" automatically. To override this, check the "Manual" checkbox. The fade threshold is then controlled by the "threshold" slider.
5. At this time, only the "Elements enter/leave domain" & "Another user leaves/arrives" can be tested.
6. The fade parameters are event dependent.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1281/HighFidelity-Beta-PR10626-972db8f54c04312eceee9cbe778c654b1358fbff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1281/HighFidelity-Beta-PR10626-972db8f54c04312eceee9cbe778c654b1358fbff.exe

**Comment by Zvork** [comment]
**CHANGES**
- Events working in edit mode except the "avatar change" event.
- Minimal load and save functionnality, per event.
- Added timing parameters: ease in / out, noise animation
- Noise has a rounder look.

**TEST PLAN**
This test plan extends the previous test plan.
7. All events except the "avatar change" event can be edited.
9. Clicking on the save button saves a JSON configuration file under interface/resources/config with name corresponding to the currently edited event. This file contains the current settings only for the edited event.
9. Clicking on the load button loads back the settings stored in the JSON configuration file under interface/resources/config with name corresponding to the currently edited event.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1309/HighFidelity-Beta-PR10626-5cee2cff9fe2ba393b5703277740d65ffa520f43.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1310/HighFidelity-Beta-PR10626-23bfc2c13d9b87848c056f5e41de474d061840bf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1314/HighFidelity-Beta-PR10626-b1b11ec756ccdc75b6bfde884de66394f24c110c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1314/HighFidelity-Beta-PR10626-b1b11ec756ccdc75b6bfde884de66394f24c110c.exe

**Pull request closed without merging**
