### PR TITLE
Interface installer changes

### PR DESCRIPTION
**Pull request by Atlante45**
- Only launch interface if requested
- Allow Sandbox only install

Test Plan:
- On first run, `Launch Client` and `Launch Server` should both be checked by default.
- Once the installer finishes, the Sandbox should start, download the content (Don't check copy), and start interface afterward.
- Test Client only and Server only install.
- Test dual install with only launch server, only launch interface, launch none.

https://highfidelity.fogbugz.com/f/cases/2212/need-an-option-to-NOT-run-interface-on-install-for-people-installing-sandbox-on-remote-server

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e0230980bff8020f8d2bcf5fa4439c0803b7a6a available at: https://gist.github.com/b4a64404e7ea0b22f8a43d3fe15a72b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9084-9e02309.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9084-9e02309.dmg

**Comment by OmegaHeron** [comment]
QA Fail - See tests for start Interface after install or tl;dr -- Interface does not launch if doing Interface only install and option to start after install selected.


Testing Windows 10

First run;

Install Interface and Install Sandbox checked (default).
Launch Sandbox checked (default).
Launch Interface checked (default).

Interface only install - options to create shortcut, launch (and copy settings since PR) offered.  **Correct**

Stack only install - options to create shortcut, launch at startup (no selected by default), launch after install (and copy settings since PR) offered.  **Correct**

Neither Interface or Stack selected to install - can't proceed to next step.  **Correct**

Test 1 - Install all - Ask to launch both interface and stack after install.  No copy of existing settings.
Content Download presented.
Stack started.
Interface started.  Interface placed me at my last location - I almost expected to be sent to localhost in this context... not a fail, just saying.

Test 2 - Install Interface only.  Launch Interface, no copy setting selected.
Fail - Interface did not launch. (Tried twice)

Test 2b - Install interface only.  Launch Interface, copy settings selected.
Fail - Interface did not launch. (Tried twice)

Test 3 - Install Stack only.  Launch sandbox after install, no copy settings selected.
Pass

Test 3b - Install Stack only.  Launch sandbox after install, copy settings.
Pass

Tested start sandbox on system start enabled.  Pass

Behavior on re-installs was consistent as well.

**Comment by OmegaHeron** [comment]
Also - I think it's copying sandbox/stack content regardless of being told yes/no on that.  Worth double checking.

**Comment by Atlante45** [comment]
@OmegaHeron Was a silly copy paste error. Should be fixed now.
Nice find!

**Comment by OmegaHeron** [comment]
@Atlante45 - will recheck it in a couple hours, have an appointment that will trigger before build completes.  Thanks for fix.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f2da8ccd38e40338b3f2b44ef66a619025a40f3 available at: https://gist.github.com/b4a64404e7ea0b22f8a43d3fe15a72b3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9084-2f2da8c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9084-2f2da8c.dmg

**Comment by OmegaHeron** [comment]
QA Pass.  Interface launches on Interface only install and full stack+interface.  All other combinations of options work logically/proper.  Also confirmed that stack only installs correct binary set (no Interface) and opposite for Interface only.

**Pull request merged**
