### PR TITLE
Prevent call of getDomainLocalID() by domain server itself more robustly

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
https://highfidelity.manuscript.com/f/cases/14465/

This PR simply rearranges the order of the booleans in a conditional to prevent LimitedNodeList::getDomainLocalID() getting called, as it asserts in debug builds.

This shouldn't be possible in the existing code, but has been reported.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9378/app_13070_PR_0627099667378534ca182f3874e4a2e6df70fe79.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9380/app_13070_PR_bbcb07d9ab7aaea8b88bd1e79c00d2604bdfd91c.apk

**Comment by birarda** [comment]
No QA needed here - this was reproduced by me on a local broken build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9380/HighFidelity-Beta-PR13070-bbcb07d9ab7aaea8b88bd1e79c00d2604bdfd91c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9380/HighFidelity-Beta-Interface-PR13070-bbcb07d9ab7aaea8b88bd1e79c00d2604bdfd91c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9380/HighFidelity-Beta-PR13070-bbcb07d9ab7aaea8b88bd1e79c00d2604bdfd91c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9380/HighFidelity-Beta-Interface-PR13070-bbcb07d9ab7aaea8b88bd1e79c00d2604bdfd91c.exe

**Pull request merged**
