### PR TITLE
Attempt of making the interstitial loading bar to be more accurate. (RC74)

### PR DESCRIPTION
**Pull request by danteruiz**
Description in this PR - https://github.com/highfidelity/hifi/pull/14200

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14200

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13848/HighFidelity-Beta-PR14201-7277684.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13848/HighFidelity-Beta-PR14201-7277684.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13848/HighFidelity-Beta-Interface-PR14201-7277684.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13848/HighFidelity-Beta-PR14201-7277684.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13848/HighFidelity-Beta-Interface-PR14201-7277684.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
