### PR TITLE
Beta Release Candidate 3 - including up to Development Release 4677

### PR DESCRIPTION
**Pull request by ZappoMan**
- Fix collision hulls for entities that are attached and moving with an avatar
- Oculus CV1 Remote support
- Entity Editor fixes and improvements
- Fixes to loading of controller routes
- Leaving full screen mirror returns to previous view instead of always going to third person
- log spam reduction
- Fixes to reticle in HMD mode sometimes disappearing
- Fix crash on shutdown related to texture loading
- Fix crash in rendering of animated entities
- Fix rendering of particles on some AMD video cards
- Fix to crash when reloading resources
- Console Domain Server now supports SHA256 hash passwords
- Reverb zone examples entity scripts
- Improve entity script security by sandboxing include commands
- Fix 3D text overlay rendering
- Fix to checkboxes being clickable outside of their label bounds
- Fix redraw bug when logging in or out of a domain
- Start in first person view by default
- Improved error messages for entity scripts that fail to load
- Fixes icons associated with PolyVoxel edit tools
- Fix for some bad physics (popcorn effect) in some cases
- Fix export of some animation properties like firstFrame and lastFrame
- Fix for some cases of ghost avatars
- Fix to properly suppress keystrokes to the scripting layer, when an overlay dialog has focus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b758acb7d88d8aae4c78c7d86be28004c05dc861 available at: https://gist.github.com/f53fa43aa8898d71185e4e710ac33ec2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7638.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7638.dmg

**Comment by cozza13** [comment]
QA pass

Using Rift HMD
Went to demo - moved items around and attached things to myself
teleport to playa - Could see the moving objects and sounds. 
teleport to sandbox - everything worked

**Comment by OmegaHeron** [comment]
Agreed with @cozza13 but for Desktop Mode here - I'm double checking that stack side works as expected on Linux now.

**Comment by OmegaHeron** [comment]
Tested this PR stack on remote Linux server.  ATP, Audio and all services work for me as expected.  Current release Interface build works with proposed new release stack side.  Proposed new Interface works with current alpha and production Stack side code.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7538
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** Sandbox, Playa, Cellscience
**Smoke Test Results:** Successful test.

                                  |Playa    |Cellscience 
----------------------------------|---------|------------
Render Rate:                      |63       |61                    
Present Rate:                     |60       |60                  
Simrate:                          |62       |61                 
Render Stats Num Buffers:         |3361     |2486                  
Render Stats gpu::Buffer Memory:  |59.0Mb   |22.5Mb                  
Render Stats Num Textures:        |505      |207                   
Render Stats gpu::Texture Memory: |1026.3Mb |317.9Mb                  
Render Stats Triangles:           |791k     |150k                    
Render Stats Drawcalls:           |23505    |11370                   
Render Stats Items:               |234      |596           
**sandbox ‘createtestblocks.js’ Result:** Successful test.
**sandbox Import FBX Result:** Successful test.
**sandbox ‘harmonicOscillator.js’ Result:** Successful test.
**sandbox Echo Server Audio Result:** Successful test.
**sandbox ‘reverbTest.js’ Result:** Successful test.
**Additional Test Results Requested:** Successful test.
**Successful Logout/Crash:** Successful logout.

**Comment by Triplelexx** [comment]
**Testing Architecture**: 64-bit PC Desktop
**Testing OS**: Windows 10
**Testing GPU**: AMD Radeon R9

Tested most changes, various domains. Nothing out of the ordinary observed.
Had one crash but seems unrelated to changes, more likely due to resource usage.

**Comment by TNS-TrueNorth** [comment]
Passed on Win10, verified some of the fixed issues from the list such as:
- start in first person view by default
- fix to checkboxes being being clickable outside by default
- entity edtior fixes and improvements
- Fixes to reticle in HMD mode sometimes disappearing
- Leaving full screen mirror returns to previous view instead of always going to third person
- Fix collision hulls for entities that are attached and moving with an avatar

**Pull request merged**
