### PR TITLE
Model: Toggling Physics > Draw Collision Hulls works again

### PR DESCRIPTION
**Pull request by hyperlogic**
Collision renderItems were never getting removed when shouldShowCollisionHull became false.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/107601176054177

**Comment by hyperlogic** [comment]
To test: 
  * Enable collision geometry by selecting the Developer > Physics > Draw Collision Hulls menu.
  * Disable collision geometry

On master this collision geometry is still visible, this PR fixes that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a7a572b53206ad3aa4b118dbc6e1da36e87274b available at: https://gist.github.com/177daea4e296961b1bff8cb2676f829b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7576.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7576.dmg

**Comment by thoys** [comment]
## qa testing report

- Tested flipping the `Draw Collision Hulls` checkbox in both sandbox and playa with expected results

:+1:  QA successful

**Comment by hyperlogic** [comment]
test this please

**Comment by imgntn** [comment]
works on web entities for me, win10

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a4ae72270c41bbd68d0e4664e05b00e55b4d721 available at: https://gist.github.com/177daea4e296961b1bff8cb2676f829b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7576.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7576.dmg

**Pull request merged**
