### PR TITLE
Beta Release 29 - Includes up to Developer Release 5770

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Glow line replacement without geometry shader
* Reduce logspam, change some debug output to warning
*  Add AC Audio searcher for tutorial
* Location cleanup to make people more aware of their sandbox placename
*  Animate suggestions when available
* Fix the bad binding for polyline
* Introducing Clustered Lighting and improve Lighting performances ( https://github.com/highfidelity/hifi/pull/8560#issue-174639872 ) 
* Bubble on by default for new users
* Address the crash when no vertex format is specified
* Add bind polyfill and basic .editorconfig for indentation
* Support debugging issues where we are seeing crashes in the OpenGL drivers
* Fix a bug when using the gpu::Batch::_glUniform*() calls with a bad location
* Fix 'releaseGrab' not being called when using grip buttons
* Make hand-controller ui work in third person
* Vec3 and shader helpers
* Fix for teleport where you could not teleport to some location
* When using mouse to grab, reduce energy of the grab as you get farther away and as objects get larger
* Fixed children of parent object not being added back when performing an undo
* Added jsdocs for MyAvatar
* Support for the 3ds Max object offset feature ( https://github.com/highfidelity/hifi/pull/9138#issue-192940777 )
* Fix a crash if current shader is null
* Possible polyline crash fix
* Fixed pressing the grip button causes a near grabbed object to drop 
* Fix for driving/turning while flying in HMD mode 
* Fix for reset sensors while in desktop mode. 
* Client script test runner 
* New mic unmute art 
* Fix drop in text rendering quality when texture memory is low 
* Add dead zone to yaw controls 
* Fixes for building on MSVC 2015 / Qt 5.8 
* Fixed context menu showing up in the correct location with oculus touch

### CODE REVIEW

**Comment by kevinmthomasse** [comment]
testing

**Comment by Nex-Pro** [comment]
Waiting for build to complete.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e7ca61480e9ad791d32c2f9350306f03aa2b31d6 available at: https://gist.github.com/ddb4c01153351a5a3f91390584433eff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-e7ca614.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-e7ca614.dmg

**Comment by PhilipRosedale** [comment]
Looking great for my informal testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** FAILURE
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Fail. Server audio echo and reverb test fail on both Oculus HMD mode and desktop mode.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |314 |224 |514
**Present Rate**: |314 |218 |414
**Present New Rate**: |233 |175 |119
**CPU Buffer Count**: |2062 |2091 |1694
**GPU Buffer Count**: |762 |568 |433
**CPU Memory Usage**: |30865360 |32068464 |31150608
**GPU Memory Usage**: |21633136 |22403184 |22653040
**CPU Texture Count**: |214 |153 |175
**GPU Texture Count**: |187 |120 |121
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |40922288 |65834256 |154463504
**GPU Texture Memory Usage**: |592442641 |410828715 |464011434
**GPU Virtual Memory Usage**: |579160194|403963557|458839470
**Triangle Count**: |246268 |511521 |216010
**Triangle Rate**: |82089333 |127880250 |72003333
**API Drawcall Count**: |175 |173 |101
**Drawcall Count**: |181 |170 |99
**Drawcall Rate**: |60333 |42500 |33000
**State Changes Texture Count**:|347 |230 |212
**Pipeline Count**: |61 |43 |57
**Item Opaques**: |254 |341 |67
**Item Translucents**: |89 |79 |125
**Item Lights**: |10 |49 |42
**Timing Opaques**: |0.754 |1.015 |0.145
**Timing Translucents**: |0.198 |0.127 |0.301
**Timing Lighting**: |0.022 |0.024 |0.018
**Render Frame**: |2.04 |2.998 |1.563

**Comment by cozza13** [comment]
OK to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: e7ca61480e9ad791d32c2f9350306f03aa2b31d6 available at: https://gist.github.com/ddb4c01153351a5a3f91390584433eff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-e7ca614.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-e7ca614.dmg

**Comment by OmegaHeron** [comment]
Testing windows 10  - i5 6500 CPU - GTX 970 GPU

From last attempt at this RC;
Issue with privacy bubble not respecting config value = fixed.
Issue with HUD showing incorrect status of privacy bubble = fixed.
XBox controller drift now fixed
Reset Sensors "`'`" bug fixed
HMD 3rd person view while flying = good now (DK2)
CPU/GPU/Mem use remains stable in respect to previous RC(s). 

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: 👍 

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and do tutorial|Yes
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Pass (I could hear it while another laucnhed)
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass (Tested with my LAN/Remote machines and group access list controls)
**Test 7**|Test Kick now includes MAC address|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Grab objects in dev-demo| Was able to grab a few things with xbox controller -- still not very good at it (my QA fail, not code's)
**Test 11**|Test ignore function|Pass - respects user specified radius and operates as expected

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |73
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |73
**CPU Buffer Count**: |2627 |5010 |4415
**GPU Buffer Count**: |818 |1497 |1230
**CPU Memory Usage**: |41622352 |87831408 |78390000
**GPU Memory Usage**: |30296176 |51624048 |48834672
**CPU Texture Count**: |238 |299 |320
**GPU Texture Count**: |206 |258 |309
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |76933488 |163711440 |66193872
**GPU Texture Memory Usage**: |751274300 |1290765374 |1316093873
**GPU Virtual Memory Usage**: |751274300|1357874238|1316093873
**Triangle Count**: |434745 |1723047 |674109
**Triangle Rate**: |33441923 |132542076 |51854538
**API Drawcall Count**: |165 |275 |196
**Drawcall Count**: |3016 |622 |2176
**Drawcall Rate**: |232000 |47846 |167384
**State Changes Texture Count**:|325 |326 |301
**Pipeline Count**: |62 |34 |50
**Item Opaques**: |232 |462 |218
**Item Translucents**: |84 |45 |67
**Item Lights**: |11 |44 |43
**Timing Opaques**: |0.83 |2.003 |0.739
**Timing Translucents**: |0.178 |0.058 |0.146
**Timing Lighting**: |0.025 |0.024 |0.031
**Render Frame**: |2.077 |4.239 |2.177

DK2

Desktop Mode - 1600x900 maximized window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |325 |263 |269
**Present Rate**: |324 |263 |269
**Present New Rate**: |231 |165 |167
**CPU Buffer Count**: |1910 |4898 |4376
**GPU Buffer Count**: |687 |1388 |1124
**CPU Memory Usage**: |17446928 |86676336 |77992688
**GPU Memory Usage**: |11666736 |48990320 |39250032
**CPU Texture Count**: |227 |297 |321
**GPU Texture Count**: |200 |240 |297
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |34204016 |245828048 |80083408
**GPU Texture Memory Usage**: |629997833 |1017620229 |1137675488
**GPU Virtual Memory Usage**: |629997833|1017620229|1137675488
**Triangle Count**: |238184 |803186 |330315
**Triangle Rate**: |79394666 |114740857 |82578750
**API Drawcall Count**: |186 |287 |208
**Drawcall Count**: |2999 |330 |1118
**Drawcall Rate**: |999666 |47142 |279500
**State Changes Texture Count**:|366 |341 |306
**Pipeline Count**: |58 |36 |52
**Item Opaques**: |263 |466 |232
**Item Translucents**: |67 |57 |71
**Item Lights**: |11 |42 |41
**Timing Opaques**: |0.911 |1.52 |0.98
**Timing Translucents**: |0.146 |0.092 |0.177
**Timing Lighting**: |0.013 |0.025 |0.022
**Render Frame**: |1.823 |3.468 |2.381

**Comment by Nex-Pro** [comment]
### PR #9160 Beta release 29

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

## QA Test
**QA Tester**: Nex
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |90 |90
**CPU Buffer Count**: |1962 |4591 |3812
**GPU Buffer Count**: |678 |1007 |1148
**CPU Memory Usage**: |26875024 |87460656 |73041904
**GPU Memory Usage**: |18658608 |53067824 |49278320
**CPU Texture Count**: |231 |290 |306
**GPU Texture Count**: |193 |180 |290
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |86247792 |427534800 |50211280
**GPU Texture Memory Usage**: |897416999 |1090659808 |1398404849
**GPU Virtual Memory Usage**: |883845094|1083084688|1428709353
**Triangle Count**: |336260 |1608555 |1257624
**Triangle Rate**: |30569090 |146232272 |114329454
**API Drawcall Count**: |42 |146 |235
**Drawcall Count**: |70 |278 |2278
**Drawcall Rate**: |6363 |25272 |207090
**State Changes Texture Count**:|71 |200 |334
**Pipeline Count**: |26 |35 |49
**Item Opaques**: |33 |219 |253
**Item Translucents**: |3 |43 |80
**Item Lights**: |2 |39 |42
**Timing Opaques**: |0.115 |0.837 |0.734
**Timing Translucents**: |0.011 |0.102 |0.13
**Timing Lighting**: |0.011 |0.03 |0.013
**Render Frame**: |0.549 |3.025 |1.763

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo| CHECK
**Test 2**|Install a fresh copy of "Home' and do tutorial| SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.| SUCCESS 
**Test 4**|Launch firework, on dev-playa, can other hear?| SUCCESS
**Test 5**|Switch avatar and make sure it does not crash| SUCCESS
**Test 6**|Test group functions| UNTESTED
**Test 7**|Test Kick now includes MAC address| UNTESTED
**Test 8**|Enrure that you can distance grab| SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers| SUCCESS
**Test 10**|Grab objects in dev-demo| SUCCESS
**Test 11**|Test ignore function|undefined

**Comment by Nex-Pro** [comment]
Had some crashing bug splats forwarded.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 87dd8a46f8e4204d2c3c9bfdd29b7313a4206a51 available at: https://gist.github.com/54f2480398b79986c102d924bc579bdb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-87dd8a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-87dd8a4.dmg

**Comment by OmegaHeron** [comment]
Retested with added code/rebuild.  All tests pass.

CPU Analysis against 5734 (RC28.1)
5 Runs per sample set - 2 minutes duration - loading old apartment scene while rotating until fully loaded.  i5 6500 CPU - GTX 970 GPU - 1600 x 900 Desktop mode/maximized window.

rc29multicpuanalysis

Minor increase in average CPU use, but, not troublesome and render rates are improved over RC28.  Frame timing stats for Batch/GPU both show lower values in comparison to last RC (with a corresponding increase in FPS).

**Comment by ZappoMan** [comment]
@OmegaHeron - the CPU increase is likely from the change in lighting... if interested, you might compare in a scene with no lighting... check with @samcake on the expected impact there.

Lights now are less expensive in the GPU (a lot less) -- but slightly more expensive in CPU... although - honestly - that looks like a bigger impact than I would have expected.

**Comment by ZappoMan** [comment]
@OmegaHeron - also - can you explain why you're trying sparse on/off? We probably need to remove that feature, there's no reason people should be disabling it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f7e8d47426278f0f0e4e9fd22aefff079d7cea6f available at: https://gist.github.com/ddb4c01153351a5a3f91390584433eff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-f7e8d47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9160-f7e8d47.dmg

**Comment by OmegaHeron** [comment]
@ZappoMan - old habits die hard.  I'd already decided this was the last time I'd expend 20 minutes of sampling data on !sparse enabled.

**Comment by OmegaHeron** [comment]
Also @zappoman - yes, that's where CPU use increase came from and it's a much more than fair trade -- compared to the bad old days we're still a fraction of former CPU use on i5 and it continue to be a much improved experience on such hardware.  For the scene load times, FPS performance and general usability of this PR over last RC... 8-10% CPU + (avg) seems a much more than fair trade.  Also - that CPU use is a worst case(ish) scenario in that it's the old apartment scene.  Less taxing scenes like playa, demo and others show far less delta CPU.

**Pull request merged**
