### PR TITLE
Remove some unneeded Qt dependencies

### PR DESCRIPTION
**Pull request by jherico**
Currently a large number of our project have superfluous dependencies on two modules:  `Widgets`, which only a small number of UI related projects actually use, and `OpenGL`, which _none_ of our projects use (The `OpenGL` Qt module is actually an outdated system for using Widget specific GL.  All modern GL functionality is actually provided by the `Gui` module).

# Testing

This should cause _no_ changes in the application behavior from master.  This is strictly a build change.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6415/app_12205_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6415/HighFidelity-Beta-PR12205-cd6f0f18956fd659d048ba84eb7bb60ada75e04f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6415/HighFidelity-Beta-PR12205-cd6f0f18956fd659d048ba84eb7bb60ada75e04f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6449/app_12205_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6449/HighFidelity-Beta-PR12205-cda76b6e955a35358fb262022ce43a1cb070ada0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6449/HighFidelity-Beta-PR12205-cda76b6e955a35358fb262022ce43a1cb070ada0.dmg

**Comment by conklin94122** [comment]
@jherico I can't recall or find where you mentioned it, but is this the PR you said to ignore Android build failures and just go ahead and test?

**Comment by conklin94122** [comment]
So, sounds like the testing is to confirm the three builds succeed, and once downloaded and installed, the interface opens. Sound right, or is there more needed? @jherico

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6665/app_12205_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6665/HighFidelity-Beta-PR12205-0781d8eaf03a21a22c3050f633720a36aa874855.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6665/HighFidelity-Beta-PR12205-0781d8eaf03a21a22c3050f633720a36aa874855.exe

**Comment by EthanMaasdam** [comment]
Failed - Crashing on Mac platform

**Comment by conklin94122** [comment]
build this please

**Comment by conklin94122** [comment]
QA, please retest, mac crash should be fixed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6743/app_12205_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6743/HighFidelity-Beta-PR12205-0781d8eaf03a21a22c3050f633720a36aa874855.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6747/app_12205_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6747/HighFidelity-Beta-PR12205-0781d8eaf03a21a22c3050f633720a36aa874855.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6747/HighFidelity-Beta-PR12205-0781d8eaf03a21a22c3050f633720a36aa874855.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
Completed testing for PR#12205. PASSED on both Windows and Mac.

**Comment by QAadahlin** [comment]
@conklin94122 Completed testing for PR#12205. PASSED on both Windows and Mac.

**Pull request merged**
