### PR TITLE
Fix rotation axes of stopwatch hands

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Host \HiFi\unpublishedScripts\marketplace\stopwatch\ content, including subdirectories, on a Web server.
- In a domain you have permissions in (e.g., your local Sandbox) run spawnStopwatch.js from the Web server.
- A stop watch should rez in front if you, facing you.
- Click on the start/stop button at the top to start/stop the stopwatch.
- The hands should rotate around the dial (rather than horizontally).

**Comment by CainFoool** [comment]
Will test

**Comment by CainFoool** [comment]
Will test once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/155/HighFidelity-Beta-PR10545-504faf430d6b9a7f3d66ba3573534b5197939438.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/155/HighFidelity-Beta-PR10545-504faf430d6b9a7f3d66ba3573534b5197939438.dmg

**Comment by CainFoool** [comment]
# Test Passed
Clock arms rotate around the dial.

**Pull request merged**
