### PR TITLE
handControlledHead.js added

### PR DESCRIPTION
**Pull request by AlessandroSigna**
Drive the head's pitch and yaw with the rotation of the right hand controller

### CODE REVIEW

**Comment by imgntn** [comment]
@AlessandroSigna when i tested this last night, my view moved up and down and my head moved side to side in my mirror but my view did not move side to side.  is that expected?

**Comment by AlessandroSigna** [comment]
Did you tried in first person mode? If this is the case it's expected. At the moment it should work fine in the third person mode.

**Comment by imgntn** [comment]
yeah you're right i was in first person mode... seems to work like expected then --but why no turning in 1st person mode?  not sure i get it.

also, please add a header file!

**Comment by AlessandroSigna** [comment]
In first person the camera seems not following the yaw of the head, I don't know why. 
I can investigate on this later but i think that it's enough for the purpose of this example

**Comment by imgntn** [comment]
Cool -- can you just add that as a to do: in the comments?  then i think we are good to go

```To do: In first person the camera seems not following the yaw of the head.  ```

**Pull request merged**
