### PR TITLE
Atp client

### PR DESCRIPTION
**Pull request by sethalves**
- rename atp-get to atp-client so that debian users don't type the wrong thing
- added listing and upload ability to atp-client
- added a way to log in via a command-line argument to atp-client and ac-client

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1311/HighFidelity-Beta-PR10877-1192e8649431872942b9bf34804218f25e2b0b9c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1311/HighFidelity-Beta-PR10877-1192e8649431872942b9bf34804218f25e2b0b9c.exe

**Comment by sethalves** [comment]
to test:
- test atp-client's listing ability:  `./atp-client atp://dev-welcome/`
- test atp-client's login ability
-- get atp write access to a domain, replace `domain-name` below with its name
-- test login with `./atp-client -u yourusername:yourpassword atp://domain-name/
- test atp-client's upload ability
-- create a file called `somefile.txt`
-- run `./atp-client -T somefile.txt atp://domain-name/somefile.txt`
-- run `./atp-client atp://domain-name/somefile.txt` and see that the output matches the content of the original file

If you don't have access to a named domain, you can get similar effect using the -d flag and the ip-address of the domain-server.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1313/HighFidelity-Beta-PR10877-a05e9e12c15ab7b31ede11095d8cd577bd4bdf73.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1313/HighFidelity-Beta-PR10877-a05e9e12c15ab7b31ede11095d8cd577bd4bdf73.exe

**Comment by Nex-Pro** [comment]
dropping this

**Comment by OmegaHeron** [comment]
Will test this - building now, be a bit.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1336/HighFidelity-Beta-PR10877-b147c3a843a9df0f63befd9bb654b6d0dac8a41c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1336/HighFidelity-Beta-PR10877-b147c3a843a9df0f63befd9bb654b6d0dac8a41c.dmg

**Comment by OmegaHeron** [comment]
Tested Ubuntu 16.04
Sort of passes - it worked once for uploading a file then failed for subsequent attempts.  It's possibly a glitch with auth backend....

atp-client atp://dev-welcome/ *Pass*
atp-client -u yourusername:yourpassword atp://domain-name/  *Pass*

Following fails as it has no auth param (which is a pass)
atp-client -T somefile.txt atp://domain-name/somefile.txt

Now - doing atp-client -u myusername:mypass -T somefile.txt atp://heron/somefile.txt
Fails several times then works -- watching log output I see it saying waiting to generate keypair but it does **not** wait -- eventually after a few attempts it does generate keypair then authorizes and uploads file.

atp-client atp://domain-name/somefile.txt *Pass*

Repeating upload attempt I see;
`jlarge@jlarge-M18xR2:~/hfBuilds/bin$ /opt/o2t-hifi/pr/bin/atp-client -u obfuscated:obfuscated -T somefile.txt atp://heron/somefile.txt`
`QThread::setPriority: Cannot set priority, thread is not running`
`QObject: Cannot create children for a parent that is in a different thread.
(Parent is NodeList(0x199a470), parent's thread is QThread(0x19a3160), current thread is QThread(0x1980c30)`
`ResourceManager disk cache setup at "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client" (size: 10 GB)`
`[07/05 15:02:01] [INFO] [] Time zone: EDT`
`nodeKilled`
`nodeKilled`
`nodeKilled`
`nodeKilled`
`nodeKilled`
`hifi.networking.asset_client: Attempting to upload "somefile.txt" to asset-server.`
`hifi.networking.asset_client: Error uploading file to asset server`
`upload failed:  "You do not have permission to upload content to this asset-server."`
`[07/05 15:02:04] [DEBUG] [] LogHandler shutdown.`
`QObject::killTimer: Timers cannot be stopped from another thread`
`QObject::~QObject: Timers cannot be stopped from another thread`

Tried again and got;

`jlarge@jlarge-M18xR2:~/hfBuilds/bin$ /opt/o2t-hifi/pr/bin/atp-client -u obfuscated:obfuscated -T somefile.txt atp://heron/somefile.txt`
`QThread::setPriority: Cannot set priority, thread is not running`
`QObject: Cannot create children for a parent that is in a different thread.`
`(Parent is NodeList(0x21b8470), parent's thread is QThread(0x21c0ce0), current thread is QThread(0x219ec30)`
`ResourceManager disk cache setup at "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client" (size: 10 GB)`
`A keypair is required to present a username signature to the domain-server but no keypair is present. Waiting for keypair generation to complete.`
`hifi.networking.asset_client: Attempting to upload "somefile.txt" to asset-server.`
`hifi.networking.asset_client: Error uploading file to asset server`
`upload failed:  "You do not have permission to upload content to this asset-server."`

And again (5x times) failed same as above.

Something is screwy with authorization....  it only worked once for like 20 tries of uploading files.  Verbose output;

`jlarge@jlarge-M18xR2:~/hfBuilds/bin$ /opt/o2t-hifi/pr/bin/atp-client -v -u obfuscated:obfuscated -T somefile.txt atp://heron/somefile.txt`
`domain-server address is "hifi://heron"`
`hifi.shared: Settings file: "/home/jlarge/.config/High Fidelity - PR10877/ac-client.json"`
`hifi.shared: Settings thread started.`
`hifi.networking: Asynchronously looking up IP address for hostname "stun.highfidelity.io" - lookup ID is 1`
`hifi.networking: Changed socket "send" buffer size from 212992 to 425984 bytes`
`hifi.networking: Changed socket "receive" buffer size from 212992 to 425984 bytes`
`hifi.networking: NodeList socket is listening on 39385`
`hifi.networking: Local socket is 192.168.0.100:39385`
`hifi.networking: Registering a packet listener for packet list type 2 (DomainList)`
`hifi.networking: Registering a packet listener for packet list type 3 (Ping)`
`hifi.networking: Registering a packet listener for packet list type 4 (PingReply)`
`hifi.networking: Registering a packet listener for packet list type 39 (ICEPing)`
`hifi.networking: Registering a packet listener for packet list type 21 (DomainServerAddedNode)`
`hifi.networking: Registering a packet listener for packet list type 46 (DomainServerConnectionToken)`
`hifi.networking: Registering a packet listener for packet list type 16 (DomainConnectionDenied)`
`hifi.networking: Registering a packet listener for packet list type 48 (DomainSettings)`
`hifi.networking: Registering a packet listener for packet list type 22 (ICEServerPeerInformation)`
`hifi.networking: Registering a packet listener for packet list type 32 (DomainServerRequireDTLS)`
`hifi.networking: Registering a packet listener for packet list type 40 (ICEPingReply)`
`hifi.networking: Registering a packet listener for packet list type 20 (DomainServerPathResponse)`
`hifi.networking: Registering a packet listener for packet list type 56 (DomainServerRemovedNode)`
`hifi.networking: Registering a packet listener for packet list type 71 (UsernameFromIDReply)`
`QThread::setPriority: Cannot set priority, thread is not running`
`QObject: Cannot create children for a parent that is in a different thread.`
`(Parent is NodeList(0x214a500), parent's thread is QThread(0x2153570), current thread is QThread(0x2130c30)`
`hifi.networking: Trying to go to URL "hifi://heron"`
`hifi.networking: Registering a packet listener for packet list type 62 (AssetMappingOperationReply)`
`hifi.networking: Registering a packet listener for packet list type 54 (AssetGetInfoReply)`
`hifi.networking: Registering a packet listener for packet list type 50 (AssetGetReply)`
`hifi.networking: Registering a packet listener for packet list type 52 (AssetUploadReply)`
`ResourceManager disk cache setup at "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client" (size: 10 GB)`
`hifi.networking: AccountManager URL for authenticated requests has been changed to https://metaverse.highfidelity.com`
`hifi.networking: Found metaverse API account information for https://metaverse.highfidelity.com
cached username is "OmegaHeron" , isLoggedIn = true`
`hifi.networking: QHostInfo lookup result for "stun.highfidelity.io" with lookup ID 1 is "54.215.145.86"`
`hifi.networking: Sending intial stun request to stun.highfidelity.io`
`hifi.networking: New public socket received from STUN server is 173.170.6.26:39385`
`hifi.networking: Possible domain change required to connect to "ds1.o2t.info" on 40102`
`hifi.networking: Resetting current domain connection information.`
`hifi.networking: Soft reset`
`hifi.networking: Cannot create address path without a getter for position. Call AddressManager::setPositionGetter to pass a function that will return a const glm::vec3&`
`hifi.networking: Hard reset in NodeList DomainHandler.`
`hifi.networking: Updated domain hostname to "ds1.o2t.info"`
`hifi.networking: Looking up DS hostname ds1.o2t.info.`
`hifi.networking: Updated domain port to 40102`
`domainChanged`
`hifi.networking: DS at ds1.o2t.info is at 159.203.92.103`
`hifi.networking: Sending connect request to domain-server at "ds1.o2t.info"`
`hifi.networking: Sending connect request to domain-server at "ds1.o2t.info"`
`A keypair is required to present a username signature to the domain-server but no keypair is present. Waiting for keypair generation to complete.`
`hifi.networking: Clearing current private key in DataServerAccountInfo`
`hifi.networking: Starting worker thread to generate 2048-bit RSA keypair.`
`hifi.networking: Storing an account with access-token for https://metaverse.highfidelity.com`
`login successful`
`hifi.networking: Persisting AccountManager accounts to "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client/AccountInfo.bin"`
`hifi.networking: Resetting current domain connection information.`
`hifi.networking: Soft reset`
`hifi.networking: Sending connect request to domain-server at "ds1.o2t.info"`
`hifi.networking: Generated 2048-bit RSA keypair. Uploading public key now.`
`hifi.networking: NodeList UUID changed from "00000000-0000-0000-0000-000000000000" to "f50bfd0a-19fe-4870-b64f-2195e23a8ea8"`
`hifi.networking: Domain ID changed to "17bd87c6-5dca-4e72-8236-54c9d071ff3b"`
`hifi.networking: Requesting settings from domain server`
`hifi.networking: Added "Entity Server" (o) {53e53103-680c-49ea-9b17-1843e64fe928} 159.203.92.103:52920 / 159.203.92.103:52920`
`node added:  o`
`hifi.networking: Added "Audio Mixer" (M) {d5984d8d-2c07-4180-a4f6-88103754e993} 159.203.92.103:44899 / 159.203.92.103:44899`
`hifi.networking: Added "Asset Server" (A) {fa38e7df-44e7-497f-8937-614bec7aa91e} 159.203.92.103:59401 / 159.203.92.103:59401`
`node added:  M`
`hifi.networking: Added "Messages Mixer" (m) {d358b271-365e-456b-b462-e0ab2f16ee67} 159.203.92.103:43745 / 159.203.92.103:43745`
`node added:  A`
`hifi.networking: Added "Avatar Mixer" (W) {13bec785-1e9a-44b7-a584-f529c0c6b52d} 159.203.92.103:59333 / 159.203.92.103:59333`
`node added:  m`
`node added:  W`
`hifi.networking: Activating local socket for network peer with ID "53e53103-680c-49ea-9b17-1843e64fe928"`
`hifi.networking: Activating local socket for network peer with ID "d5984d8d-2c07-4180-a4f6-88103754e993"`
`hifi.networking: Activating local socket for network peer with ID "fa38e7df-44e7-497f-8937-614bec7aa91e"`
`path is  "/somefile.txt"`
`hifi.networking.asset_client: Attempting to upload "somefile.txt" to asset-server.`
`hifi.networking: Activating local socket for network peer with ID "13bec785-1e9a-44b7-a584-f529c0c6b52d"`
`hifi.networking: Activating local socket for network peer with ID "d358b271-365e-456b-b462-e0ab2f16ee67"`
`hifi.networking: Received domain settings:`
` QJsonObject({"avatars":{"avatar_whitelist":"","max_avatar_scale":3,"min_avatar_scale":0.25,"replacement_avatar":""}})`
`hifi.networking: Username changed to "OmegaHeron"`
`hifi.networking: Persisting AccountManager accounts to "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client/AccountInfo.bin"`
`hifi.networking.asset_client: Error uploading file to asset server`
`upload failed:  "You do not have permission to upload content to this asset-server."`
`hifi.networking: Uploaded public key to Metaverse API. RSA keypair generation is completed.`
`hifi.networking: Persisting AccountManager accounts to "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client/AccountInfo.bin"`
`hifi.networking: Soft reset`
`hifi.networking: LimitedNodeList::eraseAllNodes() removing all nodes from NodeList.`
`hifi.networking: Killed "Audio Mixer" (M) {d5984d8d-2c07-4180-a4f6-88103754e993} 159.203.92.103:44899 / 159.203.92.103:44899`
`hifi.networking: Killed "Messages Mixer" (m) {d358b271-365e-456b-b462-e0ab2f16ee67} 159.203.92.103:43745 / 159.203.92.103:43745`
`hifi.networking: Killed "Entity Server" (o) {53e53103-680c-49ea-9b17-1843e64fe928} 159.203.92.103:52920 / 159.203.92.103:52920`
`hifi.networking: Killed "Asset Server" (A) {fa38e7df-44e7-497f-8937-614bec7aa91e} 159.203.92.103:59401 / 159.203.92.103:59401`
`hifi.networking: Killed "Avatar Mixer" (W) {13bec785-1e9a-44b7-a584-f529c0c6b52d} 159.203.92.103:59333 / 159.203.92.103:59333`
`hifi.networking: Clearing all remaining connections in Socket.`
`hifi.networking: NodeList UUID changed from "f50bfd0a-19fe-4870-b64f-2195e23a8ea8" to "00000000-0000-0000-0000-000000000000"`
`hifi.networking: udt::Socket state changed - state is now QAbstractSocket::UnconnectedState`

**Comment by sethalves** [comment]
@OmegaHeron yeah that doesn't look right.  I'll take a look.

**Comment by OmegaHeron** [comment]
@sethalves  -- saw Slack, will give it a go in a bit once compiled latest rev.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1368/HighFidelity-Beta-PR10877-98ac2ccb908f04795736b23ddc5eb606544178e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1368/HighFidelity-Beta-PR10877-98ac2ccb908f04795736b23ddc5eb606544178e9.exe

**Comment by OmegaHeron** [comment]
Ok - again on Ubuntu 16.04

Better this time, but, it's still flaky about authorizations. 

First attempt fails...

`jlarge@jlarge-M18xR2:~/hfBuilds/bin$ /opt/o2t-hifi/pr/bin/atp-client -u obfuscated:obfuscated -T somefile.txt atp://heron/somefile.txt`
`ResourceManager disk cache setup at "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client" (size: 10 GB)`
`[07/05 21:23:18] [INFO] [] Time zone: EDT`
`hifi.networking.asset_client: Attempting to upload "somefile.txt" to asset-server.`
`hifi.networking.asset_client: Error uploading file to asset server
upload failed:  "You do not have permission to upload content to this asset-server."`
`[07/05 21:23:26] [DEBUG] [] LogHandler shutdown.`
`QObject::killTimer: Timers cannot be stopped from another thread`
`QObject::~QObject: Timers cannot be stopped from another thread`

Immediately run again and it works.

`jlarge@jlarge-M18xR2:~/hfBuilds/bin$ /opt/o2t-hifi/pr/bin/atp-client -u obfuscated:obfuscated -T somefile.txt atp://heron/somefile.txt`
`ResourceManager disk cache setup at "/home/jlarge/.local/share/High Fidelity - PR10877/ac-client" (size: 10 GB)`
`A keypair is required to present a username signature to the domain-server but no keypair is present. Waiting for keypair generation to complete.`
`hifi.networking.asset_client: Attempting to upload "somefile.txt" to asset-server.`
`hifi.networking.asset_client: Successfully uploaded asset to asset-server - SHA256 hash is  "c8e52c2b11d52859ff308562d3422e2149667bc17fb3f75396c8ea3b5c699d16"`

Note that I didn't have username:password wrong on first attempt ;)  Second try was simply an up arrow bash history repeat.  It's weird how on failed attempts console output has the Time zone output the loghandler shutdown messages while successful run does not - that's consistent too... every time it fails it has that, and does not on success (maybe because fail triggers "logging" rules?).

I was going to try it on windows for a comparison, but, it does not come with installer and I'm not currently setup to compile on Windows.

**Comment by OmegaHeron** [comment]
Also - it does, ultimately, pass all test conditions, it's simply the unreliable upload action that gives me pause.

**Comment by sethalves** [comment]
Yeah I think there's still some sort of race-condition in there.  If you use -u once and get your credentials save to disk, it's reliable after that, but the invocation with -u seems to fail too often.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1425/HighFidelity-Beta-PR10877-b8875a8902e9cb4d42048099de4483abdd6866f5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1425/HighFidelity-Beta-PR10877-b8875a8902e9cb4d42048099de4483abdd6866f5.exe

**Pull request merged**
