### PR TITLE
Fix sorting of entity list not working as expected

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
# Test Case

https://highfidelity.testrail.net/index.php?/cases/view/17767

Specifically, make sure that in a domain with many locked and unlocked entities, that they sort correctly when sorting by the locked column.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13144/HighFidelity-Beta-PR14043-1ee655c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13144/HighFidelity-Beta-PR14043-1ee655c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13144/HighFidelity-Beta-Interface-PR14043-1ee655c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13144/HighFidelity-Beta-PR14043-1ee655c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13144/HighFidelity-Beta-Interface-PR14043-1ee655c.exe

**Comment by rickcarr044** [comment]
Currently testing 14043

**Comment by rickcarr044** [comment]
PASS @conklin94122

Sort functionality now seems to work for the Lock and Visible columns in CREATE>Entity List dialog.  Also confirmed the TYPE, NAME and FILE column sorts continued to sort as expected.  Tested with WIN10 on Desktop and Rift.

**Pull request merged**
