### PR TITLE
Case 22065: Fix mac warnings

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.manuscript.com/f/cases/22065/Fix-mac-build-warnings)

Fix build warnings on mac

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18591/HighFidelity-Beta-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18591/HighFidelity-Beta-Interface-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18591/HighFidelity-Beta-PR15327-8a9916a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18591/HighFidelity-Quest-Beta-PR15327-8a9916a.apk)

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18593/HighFidelity-Beta-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18593/HighFidelity-Beta-Interface-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18593/HighFidelity-Beta-PR15327-8a9916a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18593/HighFidelity-Quest-Beta-PR15327-8a9916a.apk)

**Comment by shanzzam** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18604/HighFidelity-Beta-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18604/HighFidelity-Beta-Interface-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18604/HighFidelity-Beta-PR15327-8a9916a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18604/HighFidelity-Quest-Beta-PR15327-8a9916a.apk)

**Comment by shanzzam** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18614/HighFidelity-Beta-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18614/HighFidelity-Beta-Interface-PR15327-8a9916a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18614/HighFidelity-Beta-PR15327-8a9916a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18614/HighFidelity-Quest-Beta-PR15327-8a9916a.apk)

**Comment by howard-stearns** [comment]
[fix mac warnings](https://trello.com/c/gS79mdiR/17-fix-mac-warnings)

**Comment by howard-stearns** [comment]
This is on hold due to a technical problem that needs to be resolved: mac wants `this` to not be referenced in lambdas when not used, and windows seems to require it.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18858/HighFidelity-Beta-PR15327-6338dab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18858/HighFidelity-Beta-Interface-PR15327-6338dab.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18858/HighFidelity-Beta-PR15327-6338dab.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18858/HighFidelity-Quest-Beta-PR15327-6338dab.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18859/HighFidelity-Beta-PR15327-0f2dbd7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18859/HighFidelity-Beta-Interface-PR15327-0f2dbd7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18859/HighFidelity-Beta-PR15327-0f2dbd7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18859/HighFidelity-Beta-Interface-PR15327-0f2dbd7.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18859/HighFidelity-Beta-PR15327-0f2dbd7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18859/HighFidelity-Quest-Beta-PR15327-0f2dbd7.apk)

**Pull request merged**
