### PR TITLE
fix deadlock when removing tablet

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95eb52ad178ffd4601996a551f69a2d43c7e77d5 available at: https://gist.github.com/80cf7028ec96ddc2cb48717ed28cf48e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8835-95eb52a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8835-95eb52a.dmg

**Comment by zzmp** [comment]
Fixes https://highfidelity.fogbugz.com/f/cases/1970/random-deadlock

**Comment by zzmp** [comment]
QA:

- General smoke test, in Desktop & HMD
- Make sure the on-screen keyboards still work (in web entities, marketplace)
- Make sure attachments still work (like hats)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 301f3ced983d9eeae07511344140db14ae143727 available at: https://gist.github.com/80cf7028ec96ddc2cb48717ed28cf48e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8835-301f3ce.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8835-301f3ce.dmg

**Comment by ZappoMan** [comment]
tested passed

**Pull request merged**
