### PR TITLE
allow user move the cursor with the mouse for the add model URL textbox 

### PR DESCRIPTION
**Pull request by druiz17**
allow user move the cursor with the mouse for the add model URL text box

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan (desktop and HMD mode)
- open tablet, then click on create the app, under the create tab click  model
- type anything in the model url textbox
- check if you can move the cursor by clicking a location within the text box

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1699/HighFidelity-Beta-PR10969-93d1725b3c87333ce3055cd4f748ff8086aa05a7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1699/HighFidelity-Beta-PR10969-93d1725b3c87333ce3055cd4f748ff8086aa05a7.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

open tablet, then click on create the app, under the create tab click model **Check**
type anything in the model url textbox **Check**
check if you can move the cursor by clicking a location within the text box **Pass**

**Pull request merged**
