### PR TITLE
Use STUN RFC magic number to filter for such packets

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
The STUN packets are used to discover each Node's public addr/port. We use the IP standard format rather than our own NL packets. These packets were causing the wireshark dissectors to hang. The packets contain a magic number, as noted around `LimitedNodeList.cpp:944`.

i.e., Why isn't the existing address check working? How do we get them still decoded by wireshark?

https://highfidelity.atlassian.net/browse/BUGZ-438

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19699/HighFidelity-Beta-PR15650-d620d35.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19699/HighFidelity-Quest-Beta-PR15650-d620d35.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19699/HighFidelity-Beta-PR15650-d620d35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19699/HighFidelity-Beta-Interface-PR15650-d620d35.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19699/HighFidelity-Beta-PR15650-d620d35.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19699/HighFidelity-Beta-Interface-PR15650-d620d35.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19706/HighFidelity-Beta-PR15650-bffd87b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19706/HighFidelity-Beta-Interface-PR15650-bffd87b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19706/HighFidelity-Beta-PR15650-bffd87b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19706/HighFidelity-Quest-Beta-PR15650-bffd87b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19706/HighFidelity-Beta-PR15650-bffd87b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19706/HighFidelity-Beta-Interface-PR15650-bffd87b.exe

**Comment by SimonWalton-HiFi** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19712/HighFidelity-Beta-PR15650-bffd87b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19712/HighFidelity-Beta-Interface-PR15650-bffd87b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19712/HighFidelity-Beta-PR15650-bffd87b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19712/HighFidelity-Quest-Beta-PR15650-bffd87b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19712/HighFidelity-Beta-PR15650-bffd87b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19712/HighFidelity-Beta-Interface-PR15650-bffd87b.exe

**Pull request merged**
