### PR TITLE
Case 21260, Case 21352: Trying to fix overlay rotation (RC 80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/edit/21352/nametags-rotated-over
https://highfidelity.manuscript.com/f/cases/21260/Notifications-appear-off-center-and-sometimes-mirrored-in-HMD-mode

https://github.com/highfidelity/hifi/pull/15012

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17548/HighFidelity-Beta-PR15001-a541654.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17548/HighFidelity-Beta-PR15001-a541654.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17548/HighFidelity-Beta-Interface-PR15001-a541654.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17548/HighFidelity-Beta-PR15001-a541654.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17548/HighFidelity-Beta-Interface-PR15001-a541654.exe

**Comment by samcake** [comment]
I checked the 81 pr and it works correctly

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17572/HighFidelity-Beta-PR15001-9f5506a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17572/HighFidelity-Beta-Interface-PR15001-9f5506a.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17572/HighFidelity-Beta-PR15001-9f5506a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17572/HighFidelity-Beta-Interface-PR15001-9f5506a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17578/HighFidelity-Beta-PR15001-9f5506a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17578/HighFidelity-Beta-Interface-PR15001-9f5506a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17578/HighFidelity-Beta-PR15001-9f5506a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17578/HighFidelity-Beta-Interface-PR15001-9f5506a.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17596/HighFidelity-Beta-PR15001-9f5506a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17596/HighFidelity-Quest-Beta-PR15001-9f5506a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17596/HighFidelity-Beta-PR15001-9f5506a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17596/HighFidelity-Beta-Interface-PR15001-9f5506a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17596/HighFidelity-Beta-PR15001-9f5506a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17596/HighFidelity-Beta-Interface-PR15001-9f5506a.exe

**Pull request merged**
