### PR TITLE
WL 21665 - Window.takeSecondaryCameraSnapshot() should emit a stillSnapshotTaken signal

### PR DESCRIPTION
**Pull request by cain-kilgore**
> Window.takeSecondaryCameraSnapshot() should emit a stillSnapshotTaken signal
> 
> Refer to WindowScriptingInterface.h and takeSnapShot() and takeSecondaryCameraSnapshot()
> Worklist [21665](https://worklist.net/21665)

## Test Plan
1. Install and Run This PR
2. Enable Advanced/Developer Menus
3. Open the Console, and run: `Window.stillSnapshotTaken.connect(function(e) { print(e); });`
4. Now run `Window.takeSecondaryCameraSnapshot()` and confirm that the console prints the file path to the new Snapshot.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6169/app_12130_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6169/HighFidelity-Beta-PR12130-330b266ca89ef5bae9ed9eb607500de67d308fa9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6169/HighFidelity-Beta-PR12130-330b266ca89ef5bae9ed9eb607500de67d308fa9.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing completed for PR#12130. PASSED

**Pull request merged**
