### PR TITLE
tweak avatar update priority coefs for load tests

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
One more time for the Gipper!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13159/HighFidelity-Beta-PR14050-0e7a7d4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13159/HighFidelity-Beta-PR14050-0e7a7d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13159/HighFidelity-Beta-Interface-PR14050-0e7a7d4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13159/HighFidelity-Beta-PR14050-0e7a7d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13159/HighFidelity-Beta-Interface-PR14050-0e7a7d4.dmg

**Comment by qaAdamSmith82** [comment]
Pass @conklin94122

**Pull request merged**
