### PR TITLE
fix concurrent resize/read from summedBlendshapeCoefficients in RC62

### PR DESCRIPTION
**Pull request by birarda**
Candidate bug fix adding to  upcoming release RC62 for at least one of the recent P1 avatar mixer crashes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6117/app_12117_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6123/app_12117_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6124/app_12117_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6125/app_12117_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6126/app_12117_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6126/HighFidelity-Beta-PR12117-9b86762a7c17865d563963472ad18af61b616d02.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6126/HighFidelity-Beta-PR12117-9b86762a7c17865d563963472ad18af61b616d02.exe

**Comment by ZappoMan** [comment]
Is this really a hotfix? I mean, I like the idea of including this in 62... and so merging it into the 62 branch so it can get testing as part of 62 is great... maybe this is a naming issue?

**Comment by ZappoMan** [comment]
Note to: @conklin94122 @RyanDowne - I believe this fix should be included in RC62... but it's fixing a very old bug, that we only recently noticed in very specific contexts.

# Test Plan:
- this code changes the low level storage for the avatar "head" data... this means we need to run all tests related to avatars and their head/facial data.
- run a large crowd test
- run a lot of recording play back with facial animation
- run any sample code that messes with blendshapes
- run any tests related to facial capture
- make sure to test on a server that has > 16 cores and is unix

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by conklin94122** [comment]
@ZappoMan Would 20 bots and 5 testers work for a large crowd, or do we need more people and/or bots?

**Comment by birarda** [comment]
Closing this since it doesn't fix the P1 we're focused on for RC62. I'll re-open a PR against 63 (with some additional changes to make getMyHead and getHead return references) shortly.

**Pull request closed without merging**
