### PR TITLE
Updating highlight textures on Rift Controller

### PR DESCRIPTION
**Pull request by alexiamandeville**
Textures were updated for the Rift controller button highlights from a bright yellow to a bright blue.

Test plan:
1. Using Oculus Rift, enter VR
2. Press ESC to set Away mode
3. Look at controller overlays
4. Ensure all buttons are blue and none are yellow. 
5. Ensure buttons are correct corresponding to their physical counterpart (A, B, X, Y)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12436/HighFidelity-Beta-PR13889-805e19e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12436/HighFidelity-Beta-PR13889-805e19e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12436/HighFidelity-Beta-Interface-PR13889-805e19e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12436/HighFidelity-Beta-PR13889-805e19e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12436/HighFidelity-Beta-Interface-PR13889-805e19e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12482/HighFidelity-Beta-PR13889-9f0807c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12482/HighFidelity-Beta-PR13889-9f0807c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12482/HighFidelity-Beta-PR13889-9f0807c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12482/HighFidelity-Beta-Interface-PR13889-9f0807c.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13954/HighFidelity-Beta-PR13889-9f0807c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13954/HighFidelity-Beta-PR13889-9f0807c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13954/HighFidelity-Beta-Interface-PR13889-9f0807c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13954/HighFidelity-Beta-PR13889-9f0807c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13954/HighFidelity-Beta-Interface-PR13889-9f0807c.exe

**Comment by qliejahner** [comment]
PASS @conklin94122 

image

**Pull request merged**
