### PR TITLE
Grab Script Polish (part deux)

### PR DESCRIPTION
**Pull request by hyperlogic**
* now longer creating duplicate rendering of equip points (one for each hand)
* support for model overlay overrides for equip hotspots
* animate scale of hotspots
* play haptics when hand is drop gesture is detected
* highlight the grabbed hotspot when the drop gesture is detected

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb5107d9a510dcf6da5d117198bb13869cb6c267 available at: https://gist.github.com/b3a793a62f67c81be7def0c295b33e1c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-eb5107d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-eb5107d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6094fb3de3eb90e40d8e137bf20e0e0cacb14f1e available at: https://gist.github.com/b3a793a62f67c81be7def0c295b33e1c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-6094fb3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-6094fb3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37d60c6c8575b3423c74755c320782ebc4fd9e38 available at: https://gist.github.com/b3a793a62f67c81be7def0c295b33e1c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-37d60c6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-37d60c6.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;IRUL7B7G&#x2F;80-make-drop-without-shake-the-default"> Make Drop without Shake the default</a>

**Comment by hyperlogic** [comment]
Test plan:
 * Go to the dev-demo location.
 * Test to see if a lavender sphere appears when your hand comes close to the handle of the gun object, and disappears when your hand moves away from it. It should animate smoothly by scaling.
 * Test to see if the lavender sphere gets 10% larger when your hand is directly intersecting with it.  It should animate smoothly by scaling.
 * Equip an object, test to see if there is a haptic pulse when you turn your hand upside down.
 * Equip an object, test to see if the equip point of the object becomes visible when your hand is upside down.

Test the custom object hotspot feature:
 * Run the following script:  [handGrabTest.js](https://gist.githubusercontent.com/hyperlogic/187094aa7c7f234cff95ac101c1b0f80/raw/8f5d8b8c075738d9871cd26c74dd9be6f321cd54/handGrabTest.js) an object with red, green and blue arrows should appear before you and then fall to the ground.
* Put the object on the table in demo.
* This object should have two hotspots, one is large a oblong wire-frame sphere.  This tests the custom equip hotspot functionality.
* The second equip point should be much smaller and should appear at the tip of the red arrow.

Test the saved attach point feature:
* Equip an object, then with your other hand, near-grab the object to re-position it.   Drop the object on the table.
* Pick up the same object with the same hand.  It should remember how you repositioned the object in the previous step.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e4794450c202e38b13b837131bbb4f85de89843f available at: https://gist.github.com/b3a793a62f67c81be7def0c295b33e1c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-e479445.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8247-e479445.dmg

**Comment by thoys** [comment]
## QA testing results

### Test the equip scale animations:

- Go to the dev-demo location. 
- Test to see if a lavender sphere appears when your hand comes close to the handle of the gun object, and disappears when your hand moves away from it. It should animate smoothly by scaling.
- Test to see if the lavender sphere gets 10% larger when your hand is directly intersecting with it. It should animate smoothly by scaling.

#### works. There is a lavender sphere which slightly glows, it also gives your vive controller a short haptic impulse :white_check_mark: .     

### Test the drop indicator functionality:

- Equip an object, test to see if there is a haptic pulse when you turn your hand upside down.
- Equip an object, test to see if the equip point of the object becomes visible when your hand is upside down.

#### Haptic pulse is present and the lavender equip sphere is visible. Also when squeezing the trigger the object drops :white_check_mark:.

### Test the custom object hotspot feature:

- Run the following script: handGrabTest.js an object with red, green and blue arrows should appear before you and then fall to the ground.
- Put the object on the table in demo.
- This object should have two hotspots, one is large a oblong wire-frame sphere. This tests the custom equip hotspot functionality.
- The second equip point should be much smaller and should appear at the tip of the red arrow.

#### Works, wire-frame sphere is present, which is bigger then the small one on the red axis. Both are equip-able and trigger haptics.

### Bug(s)

- The equip spots for the pingpong gun / handpistol in the demo room seem to have changed. I am not sure if it changed in this PR though, but it is a little bit off.

QA passed successfully , but please check the equip re-check positions

**Pull request merged**
