### PR TITLE
Fix polyline crash and flicker

### PR DESCRIPTION
**Pull request by jherico**
Fix [FB7374](https://highfidelity.fogbugz.com/f/cases/7374)

# Testing 
- Run fingerPaint.js from scripts directory.
- Enter VR mode.
- Turn finger painting on.
- Press controller trigger to start drawing a line.

In the current master build this will crash.  In this build it should not crash.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3088/HighFidelity-Beta-PR11314-bf7c844e6e516eab442e2b95875c7a8296d12ef4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3088/HighFidelity-Beta-PR11314-bf7c844e6e516eab442e2b95875c7a8296d12ef4.exe

**Comment by Nex-Pro** [comment]
Testing this on win10 and Vive

**Comment by Nex-Pro** [comment]
For now this is a FAIL.

This is ok on not crashing. However fingerpaint is acting strangely. Strokes are moving to follow the hand movement. ( they are not fixed in 3d space ) I have not seen this before. Strokes are black.
hifi-snap-by--on-2017-09-06_19-26-20

**Comment by Nex-Pro** [comment]
Will compare to dev latest and comment.

**Comment by jherico** [comment]
@Nex-Pro I'm not sure what the blackness is about, but I believe the flicker / bad position should be corrected.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3106/HighFidelity-Beta-PR11314-178af19145f20a2fac276d282b9d8db372886fc1.exe

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3112/HighFidelity-Beta-PR11314-178af19145f20a2fac276d282b9d8db372886fc1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3112/HighFidelity-Beta-PR11314-178af19145f20a2fac276d282b9d8db372886fc1.exe

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
**Unsure if this is a PASS/FAIL please consult notes.**

Had this crash in HMD after I selected fingerpaint in the scripts list. Fingerpaint did not load, instead another script loaded (makeUserConnection.js). Closing that script instantly crashed interface. ( Not due to this PR. ) 

**Polylines are still black**

line 127 of RenderablePolyLineEntityItem.cpp

QString path = textures.isEmpty() ? PathUtils::resourcesPath() + "images/paintStroke.png" : textures;

I looked at images/paintStroke.png and it is a greyscale image with transparency. Little of the image appears solid as far as I can tell. See Below.

paintstroke


Polyline entities are no longer being dragged around by the hand while painting.

Polyline entities are not selectable in create mode other than through the entity list.

They work for both hands.

Line width is trigger dependent as expected.

Interface does not crash.

**Note:** I'm pretty sure I've previously  been able to paint polylines in desktop mode with the mouse. The icon can be activated on the toolbar. Nothing happens when I try. Unsure if this was changed by design.

**Comment by jherico** [comment]
@Nex-Pro OK, I believe the most recent commit should fix the color / texture of the polylines.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3309/HighFidelity-Beta-PR11314-aef85eb69d59768fdf7b7cf680b6b3bf071e53f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3309/HighFidelity-Beta-PR11314-aef85eb69d59768fdf7b7cf680b6b3bf071e53f3.exe

**Comment by cozza13** [comment]
ok to test

**Comment by jherico** [comment]
test this please

**Comment by Nex-Pro** [comment]
Will be testing this as requested.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3317/HighFidelity-Beta-PR11314-aef85eb69d59768fdf7b7cf680b6b3bf071e53f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3317/HighFidelity-Beta-PR11314-aef85eb69d59768fdf7b7cf680b6b3bf071e53f3.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by conklin94122** [comment]
Sorry, Piper, we want to try and get this out as a hotfix today. My fault Aaron grabbed this.

**Comment by YuppyPlays** [comment]
Testing complete:

Run fingerPaint.js from scripts directory. **Check**
Enter VR mode. **Check**
Turn finger painting on. **Check**
Press controller trigger to start drawing a line. **Check**

**Pass** :)

did not notice any issues, when avatar finger was pointing out it was on the spot I'd expect, only thing that I think may be off is the "Thickness" - but this is personal opinion.

**Pull request merged**
