### PR TITLE
center player in view mode

### PR DESCRIPTION
**Pull request by SamGondelman**
new mode will keep player in center of screen and rotate camera around the player's head

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22961fcc9ddcd3903060be1384eaedcc9503eedd available at: https://gist.github.com/0d4c2fc37b15d43a5a1e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5148.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5148.dmg

**Comment by ZappoMan** [comment]
what is the expected behavior of this PR in 3rd person mode? I thought it would keep my camera behind my head as I tilt my head up and down (shift+arrow) but instead it does a strange zooming effect, and I can actually end up with my camera in front of my avatar so I can't see the avatar at all.

**Comment by ZappoMan** [comment]
and even in 1st person mode it gets broken... I don't think we want to merge this as is.

**Comment by SamGondelman** [comment]
That's actually a separate issue that stems from accidental duplicate mappings of shift+up and shift+down (they control pitch but also zoom).  The camera doesn't actually end up in front of the player, it just zooms in to first person and then keeps tilting the camera up so it looks like it kept moving forward.  I've fixed that by removing the duplicate mapping in this PR (which I'm about to fix): https://github.com/highfidelity/hifi/pull/5150

You should see the expected behavior with shift+e, shift+c, and right click + drag.

**Comment by ZappoMan** [comment]
ok - I see now.

**Comment by SamGondelman** [comment]
yeah, sorry about that

**Pull request merged**
