### PR TITLE
BUGZ-1381 - domain server creates blank/undefined group when adding groups

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21533/HighFidelity-Beta-PR16249-434c63b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21533/HighFidelity-Quest-Beta-PR16249-434c63b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21533/HighFidelity-Beta-PR16249-434c63b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21533/HighFidelity-Beta-Interface-PR16249-434c63b.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21539/HighFidelity-Beta-PR16249-434c63b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21539/HighFidelity-Quest-Beta-PR16249-434c63b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21539/HighFidelity-Beta-PR16249-434c63b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21539/HighFidelity-Beta-Interface-PR16249-434c63b.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21546/HighFidelity-Beta-PR16249-434c63b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21546/HighFidelity-Beta-Interface-PR16249-434c63b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21546/HighFidelity-Beta-PR16249-434c63b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21546/HighFidelity-Quest-Beta-PR16249-434c63b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21546/HighFidelity-Beta-PR16249-434c63b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21546/HighFidelity-Beta-Interface-PR16249-434c63b.exe

**Pull request merged**
