### PR TITLE
Build 37.1 Hotfix to fix a crash bug for graphics and tablet

### PR DESCRIPTION
**Pull request by cozza13**
- Fix some graphics related crashes
- Fix a tablet related crash

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef03ca2a2c6eb004b40c97ce7218e0527d3c4bc3 available at: https://gist.github.com/c9d3d4e2b3c796493732459ff970ed46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10274-ef03ca2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10274-ef03ca2.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. Everything acted as expected.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |70
**CPU Buffer Count**: |2643 |1251 |1320
**GPU Buffer Count**: |932 |374 |340
**CPU Memory Usage**: |33338128 |17400112 |16833264
**GPU Memory Usage**: |21225520 |11456560 |5918768
**CPU Texture Count**: |245 |87 |116
**GPU Texture Count**: |200 |69 |68
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |575983840 |160692808 |90070048
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |351294 |200492 |181882
**Triangle Rate**: |20664352 |12530750 |12125466
**API Drawcall Count**: |207 |75 |90
**Drawcall Count**: |3030 |71 |95
**Drawcall Rate**: |178235 |4437 |6333
**State Changes Texture Count**:|347 |81 |99
**Pipeline Count**: |43 |32 |28
**Item Opaques**: |302 |234 |123
**Item Translucents**: |61 |11 |13
**Item Lights**: |11 |41 |15
**Timing Opaques**: |0.926 |0.628 |0.442
**Timing Translucents**: |0.088 |0.038 |0.095
**Timing Lighting**: |0.013 |0.017 |0.029
**Render Frame**: |1.443 |2.097 |1.354

**Comment by OmegaHeron** [comment]
Testing.

**Comment by claudioshg** [comment]
testing

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 - GTX970

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: No issues with this PR

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|Pass
**Test 10**|Test PAL functionality|Basic quick test Pass
**Test 11**|Test Tablet in 2D and 3D|Basic quick test Pass

Desktop Mode - 1600x900 maximized window

**Domain** |localhost |dev-playa |N/A
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |61 |60 |61
**Present New Rate**: |70 |60 |60
**CPU Buffer Count**: |1939 |30922 |11301
**GPU Buffer Count**: |668 |1159 |175
**CPU Memory Usage**: |18850256 |173545136 |65771280
**GPU Memory Usage**: |11211376 |43152816 |13612464
**CPU Texture Count**: |228 |229 |60
**GPU Texture Count**: |176 |193 |41
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |576465812 |792155300 |105425588
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |239884 |747692 |30048
**Triangle Rate**: |14992750 |43981882 |1878000
**API Drawcall Count**: |166 |204 |18
**Drawcall Count**: |1909 |348 |18
**Drawcall Rate**: |119312 |20470 |1125
**State Changes Texture Count**:|298 |247 |44
**Pipeline Count**: |41 |36 |23
**Item Opaques**: |245 |345 |4
**Item Translucents**: |64 |38 |3
**Item Lights**: |11 |38 |0
**Timing Opaques**: |0.85 |1.043 |0.045
**Timing Translucents**: |0.103 |0.1 |0.018
**Timing Lighting**: |0.013 |0.018 |0.016
**Render Frame**: |1.362 |2.391 |0.648

CV1

**Domain** |localhost |dev-playa |N/A
---|---|---|---
**Render Rate**: |0 |0 |0
**Present Rate**: |90 |90 |90
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |24147 |31434 |11801
**GPU Buffer Count**: |876 |1383 |309
**CPU Memory Usage**: |129090384 |177358512 |69674768
**GPU Memory Usage**: |26506672 |47306160 |16782768
**CPU Texture Count**: |298 |251 |82
**GPU Texture Count**: |242 |219 |60
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |0 |0 |0
**GPU Texture Memory Usage**: |883441916 |869339472 |144861024
**GPU Virtual Memory Usage**: |0|0|0
**Triangle Count**: |128144 |2339055 |126503
**Triangle Rate**: |12814400 |111383571 |12650300
**API Drawcall Count**: |60 |246 |36
**Drawcall Count**: |104 |766 |58
**Drawcall Rate**: |10400 |36476 |5800
**State Changes Texture Count**:|103 |313 |69
**Pipeline Count**: |33 |44 |35
**Item Opaques**: |45 |410 |18
**Item Translucents**: |16 |39 |19
**Item Lights**: |4 |44 |0
**Timing Opaques**: |0.251 |1.26 |0.09
**Timing Translucents**: |0.051 |0.069 |0.037
**Timing Lighting**: |0.016 |0.022 |0.013
**Render Frame**: |0.849 |2.705 |0.752

For whatever reason -- FPS while using CV1 remains broken.  It was actually 90 for localhost and dev-playa, not zero.

**Comment by claudioshg** [comment]
Having problems with PC. Can't test.

**Pull request merged**
