### PR TITLE
Experimenting with doesFade property

### PR DESCRIPTION
**Pull request by SamGondelman**
Fading is great!  Let's fade everything all the time!  Just kidding, here's an entity and model overlay property, "doesFade," that should let you disable fading on an object.  It defaults to true, but you can set it to false for things like scripts that repeatedly modify objects.

I needed a PR to make testing easier so DNM for now.  Once it's tested I'll fix the scripts that demonstrate the issue.

### CODE REVIEW

**Comment by ZappoMan** [comment]
this feels wrong to me... I don't think we should force content authors to make this choice.

I understand the complaints about content authors not all like fade all the time... but I don't think we should put the burden on them,

Let's think about this more.

**Comment by hifi-gustavo** [comment]
Build console output for commit: aebecfd0e017593b05552384bc24f686f0fe5c28 available at: https://gist.github.com/28d21a02273a1ea5214e899afbbe0a91<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8415-aebecfd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8415-aebecfd.dmg

**Comment by SamGondelman** [comment]
this is very broken

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6498361e164c5061b9bde1052804224176f9689 available at: https://gist.github.com/28d21a02273a1ea5214e899afbbe0a91<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8415-f649836.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8415-f649836.dmg

**Comment by ZappoMan** [comment]
We've decided to not add this as a property.

**Pull request closed without merging**
