### PR TITLE
RC65  Fix: Applying the fix for shadows and transitions on Dual Quat Skinned meshes

### PR DESCRIPTION
**Pull request by samcake**
Same as PR 12530

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7623/app_12532_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7623/HighFidelity-Beta-PR12532-9f9214e808df300810b2eb7b610262caa137656e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7623/HighFidelity-Beta-PR12532-9f9214e808df300810b2eb7b610262caa137656e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7625/app_12532_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7625/HighFidelity-Beta-PR12532-5440f62860ae8ca02943e1f9d27f5b80f99b6963.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7625/HighFidelity-Beta-PR12532-5440f62860ae8ca02943e1f9d27f5b80f99b6963.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass. Tested with dev-welcome, hifiqa-rc-bots and eschatology all with shadows on.
@conklin94122

**Pull request merged**
