### PR TITLE
Ensure newly shown windows are popped to the top of the zorder

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Start the running scripts dialog.  Select 'From URL' or 'From Disk'.  In the production build a new window will appear behind the running scripts dialog.  In this build, newly created windows should always be placed on the top of the z-order.

### CODE REVIEW

**Comment by OmegaHeron** [comment]
Could I also expect this to do same for uploading an ATP asset?  Currently those dialogs stack incorrectly as they appear too.

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8P8HgRpL&#x2F;69-window-z-order-bugs"> Window Z Order bugs</a>

**Comment by jherico** [comment]
@OmegaHeron can you provide a repro case?  I haven't used the ATP interface at all.

**Comment by OmegaHeron** [comment]
Oh - it's the same type of issue - asset browser open, click button to pick a file - as it opens subsequent dialogs those appear under other existing dialogs.  I suspect this might fix based on description/changes.  I'll let you know shortly.  ;)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23700dc90f3038de7397f9b43aa9cf59df1453b0 available at: https://gist.github.com/668f16b079a79ee5c4c910b8c895094b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.dmg

**Comment by jherico** [comment]
@OmegaHeron I can't reproduce that.  If I open the asset browser (Ctrl-Shift-A) and click on choose file in this build, I get a file open dialog on top of the asset browser window.

**Comment by OmegaHeron** [comment]
Weird - I get different behavior with current code.  Leave it to me to have the weirds.  I'll give this PR a pass for specific case in your test case once Jenkins plays nice.

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23700dc90f3038de7397f9b43aa9cf59df1453b0 available at: https://gist.github.com/668f16b079a79ee5c4c910b8c895094b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 23700dc90f3038de7397f9b43aa9cf59df1453b0 available at: https://gist.github.com/668f16b079a79ee5c4c910b8c895094b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8203.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Tested Windows 10 Desktop and HMD with DK2
In all cases most recent element came to top - tested with running scripts dialog, atp and edit windows along with opening menu items for configuration to create additional screen elements.  TY for this one.

**Pull request merged**
