### PR TITLE
Disable showing the entity edit tools when undoing while disabled

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
# Test notes

Ticket: https://highfidelity.fogbugz.com/f/cases/15436/Create-UI-displays-without-create-being-open-when-using-Undo-keyboard-shortcut

  1. Go to a domain where you can make edits
  1. Enable Create
  1. Add a cube
  1. Move the cube around several times
  1. Confirm that you can undo using ctrl-z or the menu item (Edit > Undo)
  1. Confirm that you can redo using ctrl-shift-z or the menu item (Edit > Redo)
  1. Disable Create
  1. Confirm that you can undo, but the edit widgets do not become visible around the entity that has its edit undone.
  1. Confirm that you can redo, but the edit widgets do not become visible around the entity that has its edit redone.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11396/HighFidelity-Beta-PR13630-b015845.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11396/HighFidelity-Beta-PR13630-b015845.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11396/HighFidelity-Beta-Interface-PR13630-b015845.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @qliacoombs @Qliemillar 
Can Undo and Redo.

**Pull request merged**
