### PR TITLE
In CCD IK chains, remove the LeftHand and RightHand constraint

### PR DESCRIPTION
**Pull request by hyperlogic**
When used in combination with the elbow pole vector, this was causing the hand to never properly reach its rotation target.  It was also having side effects causing the elbow to never straighten properly to reach its position target.

There is possibly a bug in how this tip constraint is enforced and I've verified that there are no ill effects in removing it.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/17124/HMD-Arm-Spasms-and-visual-Obstruction

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11955/HighFidelity-Beta-PR13786-3fa3cd8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11955/HighFidelity-Beta-PR13786-3fa3cd8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11955/HighFidelity-Beta-Interface-PR13786-3fa3cd8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11955/HighFidelity-Beta-PR13786-3fa3cd8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11955/HighFidelity-Beta-Interface-PR13786-3fa3cd8.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Targets follow hands much better.

**Pull request merged**
