### PR TITLE
Add startup_sent_to user activity event

### PR DESCRIPTION
**Pull request by huffman**
This PR adds extra user event information for users have not opted out of sending us usage data.

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Run https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?pr10606
 1. Go through tutorial
 1. Restart interface
 1. Switch to desktop
 1. Restart interface

Let me know when you have completed that

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/366/HighFidelity-Beta-PR10606-0fdbf4a34292d024415d2e30198d9e627845e815.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/366/HighFidelity-Beta-PR10606-0fdbf4a34292d024415d2e30198d9e627845e815.dmg

**Comment by CainFoool** [comment]
Will test.

**Comment by CainFoool** [comment]
# Test Pending

Followed testing steps - restarted interface after finally switching back to Desktop. Awaiting results.

**Comment by huffman** [comment]
Thanks @CainFoool Looks good!

**Pull request merged**
