### PR TITLE
Case 21516: Lasers scale with avatar (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21516/lasers-don-t-scale-with-you-for-80

https://github.com/highfidelity/hifi/pull/15076

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17823/HighFidelity-Beta-PR15078-57b2af8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17823/HighFidelity-Quest-Beta-PR15078-57b2af8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17823/HighFidelity-Beta-PR15078-57b2af8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17823/HighFidelity-Beta-Interface-PR15078-57b2af8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17823/HighFidelity-Beta-PR15078-57b2af8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17823/HighFidelity-Beta-Interface-PR15078-57b2af8.exe

**Comment by shanzzam** [comment]
Discussed QA testing in manuscript

**Pull request merged**
