### PR TITLE
Migrate to vcpkg version of OpenSSL

### PR DESCRIPTION
**Pull request by jherico**
This PR changes our SSL dependency on windows from a third party binary to one that gets built locally from the OpenSSL.org website via a [tool](https://github.com/Microsoft/vcpkg) from Microsoft.

This ensures that the built SSL dll will have the same runtime dependencies as the rest of our application.  Build ~~~notes need to be~~~ _have been_ updated with the following information...

* Clone the [vcpkg](https://github.com/Microsoft/vcpkg) repository 
* Follow the instructions in the readme to bootstrap the vcpkg tool
* Set a system environment variable `VCPKG_ROOT` to the location of the repository
* Using vcpkg, build the openssl dependency with the command `vcpkg install openssl:x64-windows`

These steps will replace the current step of downloading and installing the OpenSSL binary distribution.  

## Testing

Simple smoke test.  If you're able to install, run and connect to domains then this change is benign.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2960/HighFidelity-Beta-PR11287-fb79ba2c6c00f42055961e1af6d8df59e8864dd2.dmg

**Comment by marko8904** [comment]
build this please

**Comment by birarda** [comment]
Is there a way we could make this an external that we build automatically?

**Comment by marko8904** [comment]
build this please

**Comment by jherico** [comment]
@birarda Probably.  If you watch the vcpkg build process, it grabs the source from openssl.org, and then grabs a number of patches.  We could probably grab the source and patches, create a custom OpenSSL zip file, and then reference it as an external project.  However, that would require more work AND it would mean it would be on us to update that zip file whenever a new security fix was released.

**Comment by birarda** [comment]
Fair enough - this isn't really any more complicated than the current (bad) process so we can leave making it even easier for another PR later.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2965/HighFidelity-Beta-PR11287-fb79ba2c6c00f42055961e1af6d8df59e8864dd2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2965/HighFidelity-Beta-PR11287-fb79ba2c6c00f42055961e1af6d8df59e8864dd2.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2971/HighFidelity-Beta-PR11287-71a403f03fb125894aae723bd5be12b060535a2f.exe

**Comment by OmegaHeron** [comment]
Testing this one (I'm also going to build from source using new method just to check that out too -- but that's on my own time not QA time).

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

General smoke test ok (i.e.. Interface/sandbox run as expected and I can "do things" in world).
Compiled Stack/Interface on Linux, no problems there (as would be expected) and binaries are functional.

**Comment by OmegaHeron** [comment]
Built from source using new method on Windows 10 - no problem here with that as well.

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3024/HighFidelity-Beta-PR11287-71a403f03fb125894aae723bd5be12b060535a2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3024/HighFidelity-Beta-PR11287-71a403f03fb125894aae723bd5be12b060535a2f.exe

**Pull request merged**
