### PR TITLE
Adding baby steps to be able to display the workload space

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7313/app_12439_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7313/HighFidelity-Beta-PR12439-cd14fb65f043b3774606a945032c5fd5ba4db5d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7313/HighFidelity-Beta-PR12439-cd14fb65f043b3774606a945032c5fd5ba4db5d7.exe

**Comment by samcake** [comment]
using a different branch with a larger update from upstream

**Pull request closed without merging**
