### PR TITLE
fix removing attachments

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that either crashed or caused attachments to visually hang around after removal

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use the menus --> Avatar --> attachments dialog to add an attachment
- make sure you can see it on your avatar
- remove it

If it disappears, all is well.

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/96638070976678

**Comment by hifi-gustavo** [comment]
Build console output for commit: d95d0f59cbfd10fed966ff3c3a5c4829118bcd29 available at: https://gist.github.com/f48023b7c598ff4db06b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7300.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7300.dmg

**Comment by Nex-Pro** [comment]
Tested this multiple times.
Single attachments.
Multiple different attachments
Multiple identical attachments
Multiple identical attachments on the same attachment point.
Works fine. Attachments are removed instantly.

**Pull request merged**
