### PR TITLE
Update hand controller laser colors 

### PR DESCRIPTION
**Pull request by imgntn**
This PR updates the laser colors for grabbing, moving, teleporting, and equipping to be unified.  It also removes a lot of cruft related to now-unused visualization methods.  Particle systems are no longer used for distance hold.

To test
1. Stop all scripts.
2. Load default scripts.
3. Use hand controllers to:
 a)look for things to far grab - reddish
 b)far grab things and move them - purplish
 c)teleport - blue

there is a known issue where the 'glowing' lines here don't extend fully to the hands.  there's a case open for that.

### CODE REVIEW

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e81f65d992264521494a7bcbcb6f0c124bf70ca9 available at: https://gist.github.com/e3c98e4ab9e692fa5c17955db3a7e8f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-e81f65d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-e81f65d.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e81f65d992264521494a7bcbcb6f0c124bf70ca9 available at: https://gist.github.com/e3c98e4ab9e692fa5c17955db3a7e8f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-e81f65d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-e81f65d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3607a34f55c3e76a12ea761ab9c747480a4fca82 available at: https://gist.github.com/e3c98e4ab9e692fa5c17955db3a7e8f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-3607a34.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-3607a34.dmg

**Comment by PhilipRosedale** [comment]
The laser is still blue when over the UI, is that intentional?

**Comment by hifi-gustavo** [comment]
Build console output for commit: c04a41c3cb16420d6fe0701598a07c61b522cd0d available at: https://gist.github.com/e3c98e4ab9e692fa5c17955db3a7e8f1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-c04a41c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8298-c04a41c.dmg

**Comment by SkimiMission** [comment]
## QA Pass

- [SUCCESS]  a)look for things to far grab - reddish
- [SUCCESS]  b)far grab things and move them - purplish
- [SUCCESS]  c)teleport - blue

Just detected, that the purple laser is coming from the oppsite of the hand: 
combo

**Comment by RyanDowne** [comment]
What color is the 'seek' laser?

**Comment by imgntn** [comment]
@RyanDowne do you mean when you pull it halfway down vs all the way?  alan and i didnt understand why those were different so right now those two 'stages' are both the same red color.   i'll share the color palette doc w/ u

**Comment by AlanZimmerman** [comment]
The two different colors for half trigger and full trigger had the added negative effect of showing both nearly simultaneously when going to full trigger, which looked sorta wrong.

Alan Zimmerman
(415) 994-1979

**Pull request merged**
