### PR TITLE
Beta Release 32 - Includes up to Developer Release 5896

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Improve FBX parsing performance 
* Adding tracking of Oculus renders, submits, and frames that are over budget 
* Change default scripts to include clara 
* Add profiling in Context batch execution and shortcuts for trace names 
* The PAL click-nodes on the avatars now indicate audio level with brightness.
* Add a local HRTF gain adjustment 
* Add dependency to Ubuntu documentation 
* Add hover effect to PAL
* Add process and system CPU usage to traces 
* Eagerly cache QML surfaces for Web3D overlays 
* Minor cleanup for Model rendering code 
* Reduce min threads in threadpool to 1 
* PAL: Scrollbar refinement & visual updates
* Improve FBX parsing performance

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 584feef56dca247b11a75dcd08bc5698009c7b39 available at: https://gist.github.com/4eb939cb5eaccf66ee1c27cd78e8a00c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-584feef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-584feef.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SERVER DOWN
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. ```dev-demo``` was down but not a failure of this PR.  New Marketplace worked with access to Clara.


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |301 |211 |
**Present Rate**: |303 |210 |
**Present New Rate**: |253 |170 |
**CPU Buffer Count**: |2137 |1748 |
**GPU Buffer Count**: |719 |558 |
**CPU Memory Usage**: |26314704 |18486352 |
**GPU Memory Usage**: |18073712 |14432368 |
**CPU Texture Count**: |244 |145 |
**GPU Texture Count**: |186 |90 |
**GPU Transfer Count**: |0 |1 |
**CPU Texture Memory Usage**: |125618544 |107653584 |
**GPU Texture Memory Usage**: |604383424 |286838562 |
**GPU Virtual Memory Usage**: |604383424|291032865|
**Triangle Count**: |277055 |513450 |
**Triangle Rate**: |138527500 |102690000 |
**API Drawcall Count**: |180 |209 |
**Drawcall Count**: |2994 |206 |
**Drawcall Rate**: |1497000 |41200 |
**State Changes Texture Count**:|366 |218 |
**Pipeline Count**: |63 |40 |
**Item Opaques**: |270 |393 |
**Item Translucents**: |99 |61 |
**Item Lights**: |11 |48 |
**Timing Opaques**: |0.934 |1.231 |
**Timing Translucents**: |0.12 |0.092 |
**Timing Lighting**: |0.014 |0.047 |
**Render Frame**: |1.569 |3.36 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS (dev-demo server offline)
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by Nex-Pro** [comment]
testing this now.

**Comment by claudioshg** [comment]
Testing

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: Omega Heron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** N/A
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop - 1600x900 maximized window

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2738 |4355 |
**GPU Buffer Count**: |912 |1387 |
**CPU Memory Usage**: |37533648 |67159120 |
**GPU Memory Usage**: |23541872 |45615216 |
**CPU Texture Count**: |340 |302 |
**GPU Texture Count**: |282 |251 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |108178608 |237374736 |
**GPU Texture Memory Usage**: |859678272 |1152972617 |
**GPU Virtual Memory Usage**: |859678272|1178138441|
**Triangle Count**: |256054 |841849 |
**Triangle Rate**: |16003375 |49520529 |
**API Drawcall Count**: |177 |264 |
**Drawcall Count**: |2989 |308 |
**Drawcall Rate**: |186812 |18117 |
**State Changes Texture Count**:|357 |302 |
**Pipeline Count**: |62 |35 |
**Item Opaques**: |262 |451 |
**Item Translucents**: |113 |53 |
**Item Lights**: |11 |45 |
**Timing Opaques**: |1.061 |1.348 |
**Timing Translucents**: |0.271 |0.102 |
**Timing Lighting**: |0.02 |0.038 |
**Render Frame**: |2.212 |3.416 |

DK2

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |75 |75 |
**Present Rate**: |75 |75 |
**Present New Rate**: |75 |75 |
**CPU Buffer Count**: |2883 |4439 |
**GPU Buffer Count**: |980 |1403 |
**CPU Memory Usage**: |34892624 |67458128 |
**GPU Memory Usage**: |21895280 |45938800 |
**CPU Texture Count**: |330 |302 |
**GPU Texture Count**: |268 |254 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |131329200 |234687760 |
**GPU Texture Memory Usage**: |1009717144 |1260478601 |
**GPU Virtual Memory Usage**: |1009717144|1352753289|
**Triangle Count**: |511846 |635376 |
**Triangle Rate**: |39372769 |48875076 |
**API Drawcall Count**: |176 |154 |
**Drawcall Count**: |5962 |566 |
**Drawcall Rate**: |458615 |43538 |
**State Changes Texture Count**:|355 |193 |
**Pipeline Count**: |62 |35 |
**Item Opaques**: |261 |213 |
**Item Translucents**: |110 |29 |
**Item Lights**: |11 |37 |
**Timing Opaques**: |0.892 |0.784 |
**Timing Translucents**: |0.15 |0.044 |
**Timing Lighting**: |0.025 |0.03 |
**Render Frame**: |1.889 |2.355 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Pass
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass


Standard (for me) CPU analysis against old apartment scene shows no negative change against previous RC.

**Comment by Nex-Pro** [comment]
**PR #9382 Beta RC 32**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used


## QA Test

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** FAILURE
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** FAILURE
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:

It seems that a third party can completed the tutorial on your behalf.

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |90 |90 |
**Present Rate**: |90 |90 |
**Present New Rate**: |89 |90 |
**CPU Buffer Count**: |3352 |4550 |
**GPU Buffer Count**: |931 |1463 |
**CPU Memory Usage**: |38972848 |68428880 |
**GPU Memory Usage**: |20760688 |47843440 |
**CPU Texture Count**: |315 |326 |
**GPU Texture Count**: |238 |284 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |178891120 |114952656 |
**GPU Texture Memory Usage**: |1120234309 |1356981722 |
**GPU Virtual Memory Usage**: |1254691728|1813647044|
**Triangle Count**: |582067 |1097087 |
**Triangle Rate**: |52915181 |99735181 |
**API Drawcall Count**: |192 |101 |
**Drawcall Count**: |5994 |274 |
**Drawcall Rate**: |544909 |24909 |
**State Changes Texture Count**:|373 |157 |
**Pipeline Count**: |65 |34 |
**Item Opaques**: |275 |151 |
**Item Translucents**: |95 |27 |
**Item Lights**: |12 |32 |
**Timing Opaques**: |0.94 |0.496 |
**Timing Translucents**: |0.169 |0.056 |
**Timing Lighting**: |0.02 |0.02 |
**Render Frame**: |1.65 |1.635 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|dev-demo unavailable
**Test 2**|Install a fresh copy of "Home' and do tutorial|**SUCCESS**
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?|**SUCCESS**
**Test 5**|Switch avatar and make sure it does not crash|**SUCCESS**
**Test 6**|Test group functions|Extensive testing all good.
**Test 7**|Test Ambisonic audio with markeplace item|**SUCCESS**
**Test 8**|Enrure that you can distance grab|**SUCCESS**
**Test 9**|Bring up and edit an objects with hand controllers|Fails on editing the object's user data as no QML keyboard
**Test 10**|Test PAL functionality|See pal results


### PAL tests:

mute: ** SUCCESS **
ignore: ** SUCCESS **
silence: ** SUCCESS **
ban: ** SUCCESS **
admin cannot be muted by non-admin: ** SUCCESS **
non admins cannot mute admins: ** SUCCESS **

ban default agent no longer possible thanks ! 

last edited orange bounding box highlighting: **SUCCESS**

Error message for multiple editors ( pal icon in edit panel ) : No error message
last editor by entity ( pal icon in edit panel ) : **SUCCESS**
last edited by avatar ( click on avatar sphere) : **SUCCESS**
last edited by avatar (click on PAL list entry) : **SUCCESS**
Add hover effect to PAL: **SUCCESS**
Pal wider scroll bar and more space right of ban icons. **SUCCESS**
The PAL click-nodes on the avatars now indicate audio level with brightness: **SUCCESS**


Group tests: Extensive tests of group functions no issues seen.

Additional: Some tests carried out on AMD processor PC. worked fine (third client ) ( desktop mode )


### FAILS:

CLARA IO:
When Michelle does not have asset perms attempts to download from ClaraIO she is presented with a popup regarding permissions that cannot be dismissed. I was able to dismiss it on my client when in a domain where I had no asset perms.

**Comment by ctrlaltdavid** [comment]
@Nex-Pro Re asset permissions dialog not being able to be closed: which domain? And a program log would be useful if possible.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid Will be trying to get a further repro on this with @nbq  shortly

**Comment by nbq** [comment]
Testing this now

**Comment by ctrlaltdavid** [comment]
A separate bug: Pressing the "edit" toolbar button in domain that you don't have write permissions (e.g., Nex-Pro's) generates a JavaScript error.
```[01/15 11:19:53] [CRITICAL] [hifi.scriptengine] "[UncaughtException] TypeError: Result of expression 'Window.notifyEditError' [undefined] is not a function. in file:///C:/Program Files/High Fidelity/scripts/system/edit.js:453\n[Backtrace]\n    <anonymous>(active = true) at file:///C:/Program Files/High Fidelity/scripts/system/edit.js:453\n    <anonymous>() at file:///C:/Program Files/High Fidelity/scripts/system/edit.js:442\n    <anonymous>() at file:///C:/Program Files/High Fidelity/scripts/system/edit.js:244\n    <global>() at -1"```

**Comment by Nex-Pro** [comment]
Amended my results. I had forgotten to update the smoke test results after I restarted.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  @nbq  Has just reproduced the identical problem that Michelle had with that popup with lasers.

**Comment by nbq** [comment]
CPU: i7 6700k
GPU: GF 970
HMD: Vive

## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **FAIL**
**Additional Test Results + Observations**: Test FAILS for me because of the Clara.io dialog being non closable on @nex-pro's domain. Otherwise everything else passed.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|OK
**Test 2**|Install a fresh copy of "Home' and do tutorial|OK
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|OK
**Test 4**|Launch firework, on dev-playa, can other hear?|Yes
**Test 5**|Switch avatar and make sure it does not crash|OK
**Test 6**|Test group functions|OK
**Test 7**|Test Ambisonic audio with markeplace item|OK
**Test 8**|Enrure that you can distance grab|OK
**Test 9**|Bring up and edit an objects with hand controllers|Works
**Test 10**|Test PAL functionality|Works

***Generate Domain Stats for me is still just a check box that when clicked makes a check mark but does not pop up the usual test.***

While trying to log into clara.io account, all input stopped working, reloaded scripts and now market came up as a grey window. Tried to quit client for a fresh try and it locked up but did not produce a bug report window. It worked when I tried it a second time.

I found just like @Nex-Pro, that admins cannot be muted from the PAL menu if you are a non-admin.

I can also confirm like @Nex-Pro has said, I cannot click the popup with lazers that tells you that you do not have access on that domain for the clara.io atp domain

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  @claudioshg  has the same issue with that popup on oculus. He will add to his notes on the QA.

**Comment by OmegaHeron** [comment]
And, I can reproduce popup issue with with my DK2 and xbox controller as well.

Re: not being able to mute an admin if you are not an admin - I vaguely remember that being a feature, not a bug as the PAL stuff was going through.  The logic was something like - you shouldn't be able to mute an admin telling you why you're being -insert action- an admin might be taking.

**Comment by ctrlaltdavid** [comment]
The popup is a simple call to Window.alert() in marketplaces.js (though it is an event handler for event bridge message received). So one question is, is it a problem with Window.alert() in general? Here's a simple test script...
[testPopup.zip](https://github.com/highfidelity/hifi/files/706354/testPopup.zip)
.. in HMD mode, run it and see if you can dismiss the popup with controllers.

(My current rig really isn't up to testing this reliably ... next to impossible to click on the "Download to High Fidelity" button with my Hydra controllers, for starters.)

**Comment by nbq** [comment]
Checking @ctrlaltdavid's script now, will report back

**Comment by nbq** [comment]
(paste from slack chat):
@ctrlaltdavid I run that script and it closes that dialog just fine with the hand lazers --- when it happens from the clara.io instance, oddly enough one hand stays locked on a blue trigger (from clicking download to hifi), so it may be somehow tied to the fact that there is no release from THAT prompt before the new prompt is put up, thus locking the trigger

**Comment by OmegaHeron** [comment]
I don't think the dialog issue is really from this PR - it's a subtle interaction between several layers where you can get stuck.  For instance, here's 1 example;

Open ATP browser while in HMD - click in it with mouse so it has focus (I think this also works with selecting something with xbox/hand controls).  Press Alt-Tab to switch out of interface.  Come back to interface and note you're in away mode but there's *no* way to exit away mode.  There are other ways to get stuck in unresponsive states as well or left with artifacts of dead UI code.  Take the QML window that dumps stats from our QA script, select all the text in it and right click with mouse - you get a popup for copy text that 1) doesn't copy text and 2) can't be dismissed until you destroy the text box window.  This thing with clara.io is probably just another layer of this general dysfunction that likely needs deeper investigation and work.

**Comment by claudioshg** [comment]
## QA Test PR #9382 Beta RC 32
Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2868 |2949 |
**GPU Buffer Count**: |1051 |1056 |
**CPU Memory Usage**: |36051792 |40801360 |
**GPU Memory Usage**: |26306672 |30193776 |
**CPU Texture Count**: |258 |209 |
**GPU Texture Count**: |232 |170 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |38530224 |69700880 |
**GPU Texture Memory Usage**: |930701445 |731175706 |
**GPU Virtual Memory Usage**: |914344164|723196412|
**Triangle Count**: |451377 |1329720 |
**Triangle Rate**: |45137700 |132972000 |
**API Drawcall Count**: |185 |226 |
**Drawcall Count**: |5982 |438 |
**Drawcall Rate**: |598200 |43800 |
**State Changes Texture Count**:|355 |244 |
**Pipeline Count**: |67 |36 |
**Item Opaques**: |261 |425 |
**Item Translucents**: |104 |49 |
**Item Lights**: |11 |51 |
**Timing Opaques**: |0.683 |1.006 |
**Timing Translucents**: |0.158 |0.05 |
**Timing Lighting**: |0.025 |0.028 |
**Render Frame**: |1.839 |2.575 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|I was able to complete the tutorial and did not notice any problems other than my avatar and interface **disappeared** during the tutorial. I was only able to see the in world Oculus Touch controllers. Immediately after the tutorial was completed my avatar and interface reappeared. I switched to two other avatars, and I retried the tutorial six times. Every time it was the same.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|undefined
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|SUCCESS


**Clara.io**
I clicked to download an entity from Clara.io, and I received an error message. I wasn't able to close the error window with my hand devices. The animation for my avatar's hands stopped working. The lasers were not animating, nor the fingers. I was able to close the error window with the mouse pointer. I realized that I had not logged into Clara.io from within the in world tablet, so I did, and now the error message is no more. I'm able to download models from Clara.io without any problems. I uninstalled the PR Build and reinstalled it. Logged off Clara.io and logged back in. In order to replicate the error message, and the error message is no more. Now when I try to download an entity without logging in, I'm taken to register for Clara.io.

**RC Test 2**
As stated above: I was able to complete the tutorial and did not notice any problems other than my avatar and interface **disappeared** during the tutorial. I was only able to see the in world Oculus Touch controllers. Immediately after the tutorial was completed my avatar and interface reappeared. I switched to two other avatars, and I retried the tutorial six times. Every time it was the same.

**Comment by ctrlaltdavid** [comment]
Re @nbq's testing, yes, it seems like it's a more general problem of hand lasers interacting with (at least) the Web pages displayed on the tablet. @OmegaHeron's comments indicate that it could be a wider problem than just the 3D Web overlay used in the tablet.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 698d63bef9bd80a470879c2fe97a14021cdc14c6 available at: https://gist.github.com/4eb939cb5eaccf66ee1c27cd78e8a00c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-698d63b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-698d63b.dmg

**Comment by OmegaHeron** [comment]
Eye issue is introduced with 5896 (#9371)

It appears with photo real female, male but not with Art3mis or the series by morph3d.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb715bf7adb0c8b167709c85b970e47ae7ce41e0 available at: https://gist.github.com/4eb939cb5eaccf66ee1c27cd78e8a00c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-bb715bf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-bb715bf.dmg

**Comment by claudioshg** [comment]
Testing new build

**Comment by cozza13** [comment]
OK to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb715bf7adb0c8b167709c85b970e47ae7ce41e0 available at: https://gist.github.com/4eb939cb5eaccf66ee1c27cd78e8a00c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-bb715bf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-bb715bf.dmg

**Comment by nbq** [comment]
Testing the new build now

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef6e83788eb3f3c7451e39d49095a79e8e97974f available at: https://gist.github.com/4eb939cb5eaccf66ee1c27cd78e8a00c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-ef6e837.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9382-ef6e837.dmg

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
CPU: i7 6700k
GPU: GF 970

## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Tests show the same as before

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Done
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Done Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Test Successful
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Success
**Test 7**|Test Ambisonic audio with markeplace item|Test Successful
**Test 8**|Enrure that you can distance grab|Successful
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|Successful

I am still having the problem where if you do not have ATP access, you get the modal that does not go away for clara.io. This is a pass otherwise.

**Comment by Nex-Pro** [comment]
Testing this now.

**Comment by OmegaHeron** [comment]
Stack protocol mismatch to dev-* so testing limited to what can be done on localhost.

Not reposting standard smoke test items/FPS stats - same results as previous testing (Pass)

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Localhost only. dev-playa = protocol mismatch, dev-demo not available.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Initial clean install sends you to dev-welcome, can't get there so can't test.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Unable to use dev-playa, proto mismatch
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Not tested - can't connect to my usual test domains where I validate group functions - no reason to believe test would fail though.
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass

**Pull request merged**
