### PR TITLE
Corrected BUILD_LINUX.md regarding QT

### PR DESCRIPTION
**Pull request by FlameSoulis**
Corrected hifi-qt5.10.1_5.10.1_amd64.deb to hifiqt5.10.1_5.10.1_amd64.deb

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8892/HighFidelity-Beta-PR12931-410e7b50512d5f71e82e6e91a34ab66d40315174.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8892/HighFidelity-Beta-Interface-PR12931-410e7b50512d5f71e82e6e91a34ab66d40315174.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8892/HighFidelity-Beta-PR12931-410e7b50512d5f71e82e6e91a34ab66d40315174.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8892/HighFidelity-Beta-Interface-PR12931-410e7b50512d5f71e82e6e91a34ab66d40315174.exe

**Pull request merged**
