### PR TITLE
Implemented chat interface script and tablet web page for worklist #21280

### PR DESCRIPTION
**Pull request by SimHacker**
Created a directory hifi/unpublishedScripts/marketplace/chat .
Added the files Chat.js and ChatPage.html .
Chat.js is an interface script that adds a "CHAT" button to the tablet, which brings up the web page ChatPage.html in the tablet browser, for chatting.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: a9c1e2781e72b78ace4ce5aeeb855c3939e94102 available at: https://gist.github.com/62fb1497a824cc442119bcfc7badff50<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10385-a9c1e27.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10385-a9c1e27.dmg

**Comment by themelissabrown** [comment]
@SimHacker can you provide test notes?

**Comment by hifi-gustavo** [comment]
Build console output for commit: c6eb1aa4e8ad34326a2ff69c53d0bea56362f72e available at: https://gist.github.com/62fb1497a824cc442119bcfc7badff50<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10385-c6eb1aa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10385-c6eb1aa.dmg

**Comment by PhilipRosedale** [comment]
@SimHacker @themelissabrown can we get this dev reviewed and merged?

**Pull request merged**
