### PR TITLE
Wait for previous domain content to be cleared before safe landing

### PR DESCRIPTION
**Pull request by luiscuenca**
While changing domains, sometimes "safe landing" occurs before the previous domain content has been cleared. This will make "safe landing" position the avatar, taking into account non-existing geometry from previous domains. The avatar would end up in odd places.  
This PR fixes the following issues.
https://highfidelity.manuscript.com/f/cases/15882/Users-Spawning-Above-Buildings-Help-Domain
https://highfidelity.manuscript.com/f/cases/15881/Users-Spawning-Above-Buildings-bankofhighfidelity-domain
https://highfidelity.manuscript.com/f/cases/15595/Philip-stuck-in-floor-in-Tomb-domain

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10761/HighFidelity-Beta-PR13428-637878d.apk

**Comment by luiscuenca** [comment]
## HOW TO REPRO
- Go to dev-mobile and position your avatar under the covered structure that is situated in the middle of the map (on top of the skull rug). 
- Run this script: https://hifi-content.s3.amazonaws.com/luis/domainUtils/changeDomains.js
- Eventually (~40 tries) your avatar will end up landing in the middle of the air

## TEST PLAN
- Go to dev-mobile and position your avatar under the covered structure that is situated in the middle of the map (on top of the skull rug). 
- Run this script: https://hifi-content.s3.amazonaws.com/luis/domainUtils/changeDomains.js
- Your avatar should always land at the same point.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10761/HighFidelity-Beta-PR13428-637878d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10761/HighFidelity-Beta-Interface-PR13428-637878d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10761/HighFidelity-Beta-PR13428-637878d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10761/HighFidelity-Beta-Interface-PR13428-637878d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10780/HighFidelity-Beta-PR13428-3806f76.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10780/HighFidelity-Beta-PR13428-3806f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10780/HighFidelity-Beta-Interface-PR13428-3806f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10780/HighFidelity-Beta-PR13428-3806f76.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10784/HighFidelity-Beta-PR13428-43c192e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10784/HighFidelity-Beta-PR13428-43c192e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10784/HighFidelity-Beta-Interface-PR13428-43c192e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10784/HighFidelity-Beta-PR13428-43c192e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10784/HighFidelity-Beta-Interface-PR13428-43c192e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10785/HighFidelity-Beta-PR13428-be9ef7b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10785/HighFidelity-Beta-PR13428-be9ef7b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10785/HighFidelity-Beta-Interface-PR13428-be9ef7b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10785/HighFidelity-Beta-PR13428-be9ef7b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10785/HighFidelity-Beta-Interface-PR13428-be9ef7b.exe

**Comment by hyperlogic** [comment]
This code appears to break entering paths such as `/0,0,0`

**Comment by conklin94122** [comment]
Moving this PR from 68.1 to 69. It also needs to be against the 69 branch and not master if that's where it's going @luiscuenca @birarda

**Comment by hyperlogic** [comment]
Marked as DO NOT MERGE, until code review feedback has been addressed, bugs have been fixed, and another issue with Ray Picks is added.

**Comment by birarda** [comment]
This has shifted to #13463

**Pull request closed without merging**
