### PR TITLE
Fix toggling edit handles between local/world space

### PR DESCRIPTION
**Pull request by dback2**
Change input to be T for toggling between local and world space when editing.

Fix edit handles not staying in world space when toggling to world space for a single-selected entity and selecting a translation/rotation handle. Also make sure stretch/scale handles are not visible when in world space mode.

Addresses:
https://highfidelity.manuscript.com/f/cases/16309/

Test Plan:
-Enter Interface in desktop mode
-Open Create, create a shape entity, and select it
-Use each arrow to translate the entity along each axis, and verify it is directly following the entity's local x, y, or z axis
-Use each rotation ring to rotate the entity about each axis, and verify it is directly following the entity's local x, y, or z axis
-Press T on keyboard to switch to world space editing mode
-Verify the arrow and ring orientations change to be based on world x, y, z axes, and the stretch spheres and scale cubes are hidden
-Use each arrow to translate the entity along each axis, and verify it is directly following their respective world x, y, or z axis
-Use each rotation ring to rotate the entity about each axis, and verify it is directly following their respective world x, y, or z axis
-Press T on keyboard to switch back to local space editing mode
-Verify the arrow and ring orientations change back to be based on the entity's x, y, z axes, and the stretch spheres and scale cubes are visible again
-Switch back and forth between the 2 space modes, verify the arrows and rings are visibly oriented as expected for each mode, and that they translate/rotate in their expected directions

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10694/HighFidelity-Beta-PR13410-5b699d1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10694/HighFidelity-Beta-PR13410-5b699d1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10694/HighFidelity-Beta-Interface-PR13410-5b699d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10694/HighFidelity-Beta-PR13410-5b699d1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10694/HighFidelity-Beta-Interface-PR13410-5b699d1.exe

**Comment by conklin94122** [comment]
@dback2 Test plan, please.

**Comment by dback2** [comment]
@conklin94122 This is not QA ready yet because it is still TBD if we need to wait on the dependency PR or make a change to what input is used so that we don't need the other PR first.

**Comment by conklin94122** [comment]
OK, thanks @dback2 . FYI @divyaelango88

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11057/HighFidelity-Beta-PR13410-e1de226.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11057/HighFidelity-Beta-PR13410-e1de226.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11057/HighFidelity-Beta-Interface-PR13410-e1de226.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11057/HighFidelity-Beta-PR13410-e1de226.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11057/HighFidelity-Beta-Interface-PR13410-e1de226.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
T now switches between world and local. Nice!

**Pull request merged**
