### PR TITLE
Workload: Merge with master

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7910/app_12607_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7910/HighFidelity-Beta-PR12607-a0db5c6135dd2a51e68a8ef2f5baba758b354b9e.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7913/app_12607_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7913/HighFidelity-Beta-PR12607-a0db5c6135dd2a51e68a8ef2f5baba758b354b9e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7913/HighFidelity-Beta-PR12607-a0db5c6135dd2a51e68a8ef2f5baba758b354b9e.exe

**Pull request merged**
