### PR TITLE
fix collisions with non-default registration

### PR DESCRIPTION
**Pull request by sethalves**
- if entity registration isn't default, adjust physics shapes to match

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26225263936266/96753277565555

**Comment by sethalves** [comment]
to test:
- create a box
- change its registration
- collide with it
- repeat with a model
- for bonus points, repeat with a polyvox

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9346171695830c30442ffdd2dc2758e44828aed7 available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8bc2c76a8b59c995db92a65179e6d13e3b160586 available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f03ddb856becefb605383f6805fbaa06e5da187b available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by sethalves** [comment]
There's something transient about this failure.  I keep thinking it's fixed, and then later discovering that it's not.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59804a0f54df433a8ca89e014ee4fc131127f489 available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dcb720a8324b841be4204d2e1202bbc61b23bb73 available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5c585acd9a0f0e30a8f50d96fe8fe4c7bd5a0e8e available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6a478d970767a466c6dd5e86532837fff5f5ff9 available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c95d1f68f6a7d8988fe8e015336e81ed4f063e7c available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 7

First thing noticed is existing model with compound shape has incorrect collision to mesh match with this PR

This PR

hifi-snap-by-omegaheron-on-2016-03-07_10-13-40

hifi-snap-by-omegaheron-on-2016-03-07_10-17-00

Current Production Build;

hifi-snap-by-omegaheron-on-2016-03-07_10-14-02

hifi-snap-by-omegaheron-on-2016-03-07_10-18-29

**Comment by sethalves** [comment]
@OmegaHeron could you attach the json blob for that ground-plane?

**Comment by OmegaHeron** [comment]
I'll get that to you shortly

**Comment by OmegaHeron** [comment]
This should suffice - had to name scene.json.txt to get it here

[scene.json.txt](https://github.com/highfidelity/hifi/files/161774/scene.json.txt)

**Comment by sethalves** [comment]
I can't fetch the obj or fbs from here -- I get 403 forbidden

**Comment by OmegaHeron** [comment]
Yeah - Nginx only allows fetches from Users Agent = Interface.  I'll give you another source in a few.

**Comment by sethalves** [comment]
Oh, that's find.  I can change user-agent

**Comment by OmegaHeron** [comment]
Ok :)  It needs to be same one Interface spits out - it's strict.

**Comment by sethalves** [comment]
curl -A "Mozilla/5.0 (HighFidelityInterface)" for anyone following along

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b8604f9b0e518a5fde950ab06053c53efaaf07b available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40c953e0b9d0770111cb6a6349cb95766413923e available at: https://gist.github.com/66134c3e20c8f94550eb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7251.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Collision with Mesh+Compound shape at all registration offsets match.
Collision with cube entity at all registration offsets match.
Collision with PolyVox entity at all registration offsets match.

QA Pass

**Comment by zzmp** [comment]
@sethalves thanks for the curl tip!

**Pull request merged**
