### PR TITLE
Fix installer issues

### PR DESCRIPTION
**Pull request by jherico**
This fixes several installer issues.  

* Remove the vcruntime140.dll, msvcrt140.dll and mscvrp140.dll artifacts from the installer by using `CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP`.  The vcredist call does what we need, so we don't need these dlls in the installer.
* Eliminate the PDB files getting added to the installer.   Changing the install commands from `INSTALL(FILES ...` to `INSTALL(DIRECTORY ...` allows us to add patterns for files to be excluded.  The lib, exp and pdb files from the build process should not be sent packed into the installer.  
* Eliminate sixense plugin for now, until we either decide it can be retired or we can fix the installation of its dependent dlls which are based on a MUCH older version of visual studio.  

## Testing

Basic smoke test.  This only modifies the installer. 

* Does interface still run?
* Do the server components (assignment client and domain server) still run?
* Does the sandbox function?

Installer size for windows should be significantly smaller than the current installer.. ~100 MB in my tests.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2216/HighFidelity-Beta-PR11108-5a7a6bab7049b899b9b011fbb1bfda7f0a23639a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2216/HighFidelity-Beta-PR11108-5a7a6bab7049b899b9b011fbb1bfda7f0a23639a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
Does interface still run? **Pass**
Do the server components (assignment client and domain server) still run? **Pass**
Does the sandbox function? **Pass**

**Notes: not sure if intentional or not, but this installer actually ran the visual studio installer, never had that happen before with installs, was all fast and automated but just making sure these are desired results, please let me know if this changes the criteria from Pass to Fail**

**Comment by birarda** [comment]
Before this is merged we will need to make a change to a steam config file in the CI PR. Hold the merge of this PR until that is confirmed here.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2231/HighFidelity-Beta-PR11108-4756d4af66a44bd194188c1c038b816d822baf6a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2231/HighFidelity-Beta-PR11108-4756d4af66a44bd194188c1c038b816d822baf6a.exe

**Comment by birarda** [comment]
We won't need a CI PR but we will need to confirm that a change has been made to the config of the app on Steam. Hold merge for that confirmation.

**Pull request merged**
