### PR TITLE
DEV-2729: Mac startup/starve 

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2729

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22688/HighFidelity-Beta-PR16535-62a8dcf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22688/HighFidelity-Quest-Beta-PR16535-62a8dcf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22688/HighFidelity-Beta-PR16535-62a8dcf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22688/HighFidelity-Beta-Interface-PR16535-62a8dcf.dmg

**Comment by amerhifi** [comment]
build this please

**Pull request closed without merging**
