### PR TITLE
Fixed a bug where you could not print polaroids if you took a gif

### PR DESCRIPTION
**Pull request by seefo**
Should fix https://highfidelity.fogbugz.com/f/cases/5386/You-should-be-able-to-print-a-snapshot-of-still-if-you-take-a-still-GIF

Test Plan:
1. Take a snapshot while still and gif are enabled
2. Verify that after taking the snap, that you can print the polaroid

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/790/HighFidelity-Beta-PR10720-a4d008eec9bcc678533e7a0e37eb0b4a10601c12.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/790/HighFidelity-Beta-PR10720-a4d008eec9bcc678533e7a0e37eb0b4a10601c12.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed 

You can now take snapshots with the gif option enabled.

image

**Pull request merged**
