### PR TITLE
Add more texture options to Oven CLI

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10046/HighFidelity-Beta-PR13221-59ca2f99775047523f26aa320f453c456f63af63.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10046/HighFidelity-Beta-PR13221-59ca2f99775047523f26aa320f453c456f63af63.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10046/HighFidelity-Beta-Interface-PR13221-59ca2f99775047523f26aa320f453c456f63af63.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10046/HighFidelity-Beta-PR13221-59ca2f99775047523f26aa320f453c456f63af63.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10046/HighFidelity-Beta-Interface-PR13221-59ca2f99775047523f26aa320f453c456f63af63.exe

**Comment by huffman** [comment]
# Testing

 * TestRail 998
 * TestRail 3480

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Asset Browser works as expected.

**Pull request merged**
