### PR TITLE
use smart pointers to avoid leaking EntityTreeElementExtraEncodeData

### PR DESCRIPTION
**Pull request by sethalves**
- fix a memory leak in entity-server

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change
- cell-science entity-server should no longer bloat over time

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/2451/On-some-domains-entities-server-leaks-a-lot-of-memory-and-eventually-uses-up-all-the-system-resources

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6fe35ac0dad96485e9f0c7ea2204e1b939cc6fad available at: https://gist.github.com/38d90256211f0b2058237b398cd93789<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9192-6fe35ac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9192-6fe35ac.dmg

**Comment by OmegaHeron** [comment]
Smoke test Ubuntu 16.04.1 = Pass
Smoke test Windows 10 - Sandbox = Pass

**Pull request merged**
