### PR TITLE
lock in Overlays::findRayIntersectionInternal

### PR DESCRIPTION
**Pull request by sethalves**
- fix a crash involving raypicking (due to mouse movement) and overlays

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run http://headache.hungry.com/~seth/hifi/tmp/overlay-crash.js which is reproduced here:
```javascript
/* global Script, Overlays, MyAvatar */                                                                                                                                                                
(function() { // BEGIN LOCAL_SCOPE                                                                                                                                                                     
    function addAndDeleteOverlay() {                                                                                                                                                                   
        var overlayID = Overlays.addOverlay("cube", {                                                                                                                                                  
            position: MyAvatar.position,                                                                                                                                                               
            size: { x: 1, y: 1, z: 1 },                                                                                                                                                                
            color: {                                                                                                                                                                                   
                red: 0,                                                                                                                                                                                
                green: 0,                                                                                                                                                                              
                blue: 255                                                                                                                                                                              
            },                                                                                                                                                                                         
            alpha: 1,                                                                                                                                                                                  
            solid: false                                                                                                                                                                               
        });                                                                                                                                                                                            
        Overlays.deleteOverlay(overlayID);                                                                                                                                                             
        Script.setTimeout(addAndDeleteOverlay, 5);                                                                                                                                                     
    }                                                                                                                                                                                                  
    Script.setTimeout(addAndDeleteOverlay, 5);                                                                                                                                                         
}());                                                                                                                                                                                                  
```

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4533/Crash-in-Overlays-findRayIntersectionInternal
https://highfidelity.fogbugz.com/f/cases/3993/CRASH-when-using-edit-js

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1c805e76f0a02d499a78c52732764cceddb7354 available at: https://gist.github.com/96c0e84d3841a805665db2179fb610fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10449-e1c805e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10449-e1c805e.dmg

**Comment by YuppyPlays** [comment]
Testing

**Comment by YuppyPlays** [comment]
Test complete:

So I took some footage below and uploaded it (unlisted of course), this shows the behaviour going on when the mouse is moved in circles around the screen. The blue vector lines appear to constantly flicker in a somewhat random pattern.

https://www.youtube.com/watch?v=myqYTtaQWnQ&feature=youtu.be

Let me know if there is more I can do/provide.

**Comment by sethalves** [comment]
That's what should happen.  On master you'd get a crash rather than the flickering box.

**Comment by YuppyPlays** [comment]
Ah, excellent, great work on the fix :)

**Pull request merged**
