### PR TITLE
Reduce strength of teleport parabola

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12221/HighFidelity-Beta-PR13846-67eb03b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12221/HighFidelity-Beta-PR13846-67eb03b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12221/HighFidelity-Beta-Interface-PR13846-67eb03b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12221/HighFidelity-Beta-PR13846-67eb03b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12221/HighFidelity-Beta-Interface-PR13846-67eb03b.exe

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
