### PR TITLE
Fix some crash on exit

### PR DESCRIPTION
**Pull request by sethalves**
- fix some crashes-on-exit

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change.  maybe less crashing on exit

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2300/HighFidelity-Beta-PR11128-83a30e2f350ed9d9811c21bcee381c1730fbf280.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2300/HighFidelity-Beta-PR11128-83a30e2f350ed9d9811c21bcee381c1730fbf280.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
-------- | --------
no functional change. maybe less crashing on exit | Pass
test servers, as well as interface | Pass

All good - didn't experience any crashes during Interface and Server testing. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
