### PR TITLE
Tool window in QML

### PR DESCRIPTION
**Pull request by jherico**
Also includes some more polish to the window frames.

To test:  

* stop all scripts on your production build and exit.  
* launch the PR build
* verify you have no scripts running
* load the editing script from http://rawgit.com/jherico/hifi/tool_window/examples/edit.js
* click the button to go into edit mode.  

The tool window should pop up with the standard content.  It may take a moment to load for the first time.  The entity list, grid tool and entity property panes should be reasonably functional.

Because the tool window is now an overlay, *all* scripts that uses it need to be ported.  Aside from the edit related scripts, the only one in our codebase that uses the tool window is planky.js, which is also included in this PR

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64f852193c5fd7e640a73c25d97db001f4799e75 available at: https://gist.github.com/e3cffaa03ad3136a9f1a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6823.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6823.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64f852193c5fd7e640a73c25d97db001f4799e75 available at: https://gist.github.com/e3cffaa03ad3136a9f1a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6823.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6823.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a7d5a2734edf9f1d33068fa1c84f322f248785e available at: https://gist.github.com/e3cffaa03ad3136a9f1a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6823.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6823.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6272b7824e6fb8409682751b3bf47e74dfd42c7 available at: https://gist.github.com/e3cffaa03ad3136a9f1a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6823.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6823.dmg

**Comment by RyanDowne** [comment]
Tested on PC in @dreaming and @demo. 

Opened running scripts dialog. It's not easy for me to understand how to get the container window with the X and the expand icons to show up. I would expect that they would show up when my cursor is "on" the boundary but that doesn't seem to be the way to invoke it. The close and expand functionalities don't work for me. I tested with both the script window and the edit window.

**Comment by ZappoMan** [comment]
What is the Stubs.qml?? it looks like dead code... did you mean to include that? It has some menu stuff in there that looks like cruft... I fear it will confuse people.

**Comment by jherico** [comment]
@RyanDowne I've updated the PR to disable the explicit close button and to remove the show/hide behavior of the drag / controls frame.  The frame should now always be visible and can be used to drag.  The window will automatically open and close based on whether any tabs have been set visible by a script.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e76e13c05c53178cc746a4c4dcbedefca92096bc available at: https://gist.github.com/e3cffaa03ad3136a9f1a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6823.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6823.dmg

**Pull request merged**
