### PR TITLE
consider avatar traits bytes in budget and omit if over

### PR DESCRIPTION
**Pull request by birarda**
Fix for https://highfidelity.manuscript.com/f/cases/19960/avatar-trait-packets-are-not-considered-in-the-avatar-mixer-data-cap

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15262/HighFidelity-Beta-PR14428-a0a87e7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15262/HighFidelity-Beta-PR14428-a0a87e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15262/HighFidelity-Beta-Interface-PR14428-a0a87e7.exe

**Comment by qlipdahlin** [comment]
Currently Testing - Working with Birarda

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Worked with Birarda as he adjusted scripts and the Engine-dev domain for the test. Using a control test using master and then he switched the AVM around, saw the results we were looking for. Install launched an worked. PR Passes.

**Pull request merged**
