### PR TITLE
Don't remove entities from list when try to delete locked entity

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
** Test Plan**

When you delete an unlocked entity, its entry (plus those of any children) is removed from the entities list.
When you try to delete a locked entity, it is not delete and its entry (plus those of any childres) are not removed from the entities list.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4822/HighFidelity-Beta-PR11789-ad661cb34563844d52f69f7f19b06bf74184ffe2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4822/HighFidelity-Beta-PR11789-ad661cb34563844d52f69f7f19b06bf74184ffe2.dmg

**Comment by YuppyPlays** [comment]
Testing complete:
When you delete an unlocked entity, its entry (plus those of any children) is removed from the entities list. **Check**
When you try to delete a locked entity, it is not delete and its entry (plus those of any childres) are not removed from the entities list. **Check**

**Notes: If the parent is not locked, but the child is locked, both will get deleted. I assume this is intended but just adding it in.**

**Pass**

**Pull request merged**
