### PR TITLE
fix locking in GenericQueueThread::process

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that could crash interface if there was a lot of logging output

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/104817951964288

**Comment by sethalves** [comment]
to test:
- smoke-test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 13eddef3126e18a9d0fd0654b2db5f24b7848fb8 available at: https://gist.github.com/bcf62236265e23364281<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 13eddef3126e18a9d0fd0654b2db5f24b7848fb8 available at: https://gist.github.com/bcf62236265e23364281<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.dmg

**Comment by cozza13** [comment]
Loaded twice and crashed twice. https://www.bugsplatsoftware.com/individualCrash/?id=2271&database=interface_alpha

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1532800a4e3e3590dab8d296ed1c30abd774e98f available at: https://gist.github.com/bcf62236265e23364281<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7479.dmg

**Comment by cozza13** [comment]
this PR works. It has pulled in a crash bug that is also in master. However that should not stop this passing

**Pull request merged**
