### PR TITLE
No fly zones

### PR DESCRIPTION
**Pull request by sethalves**
- add properties to ZoneEntities to control if avatar flying or switching to non-physical is allowed

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make nested zones
- used edit.js to change their "flying allowed" and "ghosting allowed" properties
- experiment with jumping and the menu item Developer --> Avatar --> Enable avatar collisions

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4feb2944edaab41830588df38da2a12e788f401f available at: https://gist.github.com/b88a215af9526fd93541f65641a0dbf8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.dmg

**Comment by Nex-Pro** [comment]
##### Platform win10 desktop 16gb nvida gtx770 2gb.

Works as expected. See image for arrangement of zones. Each zone is the meter figure on a side.

With this arrangement flying up from A in the purple fly zone the avatar passes thru B and emerges from the yellow no-fly zone at point C. 

fly_zone_test

Making the yellow zone taller fixes this. So I guess it's inertia.

*On two occasions touching and releasing an arrow key resulted in the camera continuously orbiting the y axis of the avatar ( may not be related to this PR )*

**Comment by ZappoMan** [comment]
@sethalves - is there a specification for this change? Can you point us to what the specific business intent of this was? Why are we making this change?

**Comment by ZappoMan** [comment]
Also note: this seems like a feature that doesn't really require a forced protocol upgrade. Let's discuss... we used to support newer client/server versions talking to old version so long as the new feature wasn't used... maybe we should re-enable that code for this feature.

For example:
- old server <-> new client -- should work, no need to upgrade
- new server (not using new feature) <-> old client -- should work, no need to upgrade
- new server (using new feature) <-> new client, works
- new server (using new feature) <-> old client -- upgrade require

**Comment by sethalves** [comment]
No, there's no spec.  There's this: https://trello.com/c/aWreuorw and a couple of the hackathon participants asked for it and it's something I've wanted.  This doesn't do server-side enforcement and there are ways to work around it, but it still lets you customize an experiece.

Making new clients work with old servers sound reasonable.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9c619916c341847c99b8c7e4a042b5ff4c78d2a available at: https://gist.github.com/b88a215af9526fd93541f65641a0dbf8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0c322470594aed1b269df3f3792c69cc20bbebb available at: https://gist.github.com/b88a215af9526fd93541f65641a0dbf8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74520f5c925d30eb92732e734f5f334b951ada5e available at: https://gist.github.com/b88a215af9526fd93541f65641a0dbf8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7800.dmg

**Pull request merged**
