### PR TITLE
Case 20759: Possible fix for procedurals on mac (RC78)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/14748

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16608/HighFidelity-Beta-PR14749-54f931e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16629/HighFidelity-Beta-PR14749-3a984e5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16629/HighFidelity-Beta-Interface-PR14749-3a984e5.exe

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16633/HighFidelity-Beta-PR14749-3a984e5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16633/HighFidelity-Beta-PR14749-3a984e5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16633/HighFidelity-Beta-Interface-PR14749-3a984e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16633/HighFidelity-Beta-PR14749-3a984e5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16633/HighFidelity-Beta-Interface-PR14749-3a984e5.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass
Shaders looks good.

**Pull request merged**
