### PR TITLE
Improved assert system

### PR DESCRIPTION
**Pull request by Atlante45**
Proposal for a new way to do asserts that is much cleaner and more efficient!

### CODE REVIEW

**Comment by birarda** [comment]
I wish I could leave this open in perpetuity.

Let's let it build at least.

**Comment by huffman** [comment]
I really like this - I can't think of any reason we wouldn't want to make this improvement to our code base.

:+1:

**Comment by huffman** [comment]
bugcatcher

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c601516d049fc2e6f83fefec8a76d19681ac1cb available at: https://gist.github.com/675d6c05b844d5d68331<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5519.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5519.dmg

**Comment by birarda** [comment]
I have to close this because there are more additions than deletions

**Pull request closed without merging**
