### PR TITLE
Better deadlock crash

### PR DESCRIPTION
**Pull request by Atlante45**
This PR changes the way we send deadlock crash reports to Backtrace so that it considers the hanging thread as the faulting thread instead of the deadlock watcher thread.
The advantage is that we will be able to differentiate and filter on the different deadlock crashes instead of having them all look the same.

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Make sure you are logged in
- Enable the developer menu
- Click on `Developer > Crash > Deadlock crash`
- The Interface will hang for ~2 min, don't touch your mouse and keyboard during that time. Wait for it to crash.
- Send me your username so I can verify the crash was properly logged.

**Comment by Atlante45** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13572/HighFidelity-Beta-PR14131-3c4e543.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13572/HighFidelity-Beta-Interface-PR14131-3c4e543.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13572/HighFidelity-Beta-PR14131-3c4e543.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13572/HighFidelity-Beta-Interface-PR14131-3c4e543.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Pull request merged**
