### PR TITLE
case 15942: fix bug that caused avatar cauterization code to run constantly

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that caused avatar cauterization code to run constantly

https://highfidelity.manuscript.com/f/cases/15942/MyAvatar-simulate-executes-if-_cauterizationNeedsUpdate-body-each-frame

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16489/HighFidelity-Beta-PR14724-1104e56.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16489/HighFidelity-Beta-PR14724-1104e56.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16489/HighFidelity-Beta-Interface-PR14724-1104e56.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16489/HighFidelity-Beta-PR14724-1104e56.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16489/HighFidelity-Beta-Interface-PR14724-1104e56.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
