### PR TITLE
Avatar without Neck Joint bug 14620

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses the bug https://highfidelity.fogbugz.com/f/cases/14620/Avatar-without-neck-joint-renders-incorrectly-from-first-person-view-but-fine-in-3rd

The fix is to use the parent of the head joint as the proxy neck.  Then the cauterized model will render correctly and solve the bug in this case.

### Test Plan
Unusual rendering behavior with avatar which is missing a neck bone.  It renders great in 3rd person view and to other users in the same domain.  

1. Load and wear this avatar http://hifi-content.s3.amazonaws.com/caitlyn/scratch/nekoMMD/nekoMMD.fst
2. Observe how she looks in 3rd person view.  Notice she looks fine.
3. Switch to first person camera view. Notice you should now see yourself correctly
4. Look up into the sky at hifi://portalarium
5. You should no longer see the avatar mesh is projected very, very high up above, like a shadow against the skybox:

Look at the screenshot, that blue area is the model from below, crotch area
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11987/HighFidelity-Beta-PR13796-f26d6b8.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11987/HighFidelity-Beta-PR13796-f26d6b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11987/HighFidelity-Beta-Interface-PR13796-f26d6b8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11995/HighFidelity-Beta-PR13796-93baad7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11995/HighFidelity-Beta-PR13796-93baad7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11995/HighFidelity-Beta-Interface-PR13796-93baad7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11995/HighFidelity-Beta-PR13796-93baad7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11995/HighFidelity-Beta-Interface-PR13796-93baad7.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12471/HighFidelity-Beta-PR13796-93baad7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12471/HighFidelity-Beta-PR13796-93baad7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12471/HighFidelity-Beta-Interface-PR13796-93baad7.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12522/HighFidelity-Beta-PR13796-93baad7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12522/HighFidelity-Beta-PR13796-93baad7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12522/HighFidelity-Beta-Interface-PR13796-93baad7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12522/HighFidelity-Beta-PR13796-93baad7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12522/HighFidelity-Beta-Interface-PR13796-93baad7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Unable to confirm on portalarium ad the domain is only on stable protocol. Hair does not appear in avatarisland, the spot, dev-mobile.

**Pull request merged**
