### PR TITLE
DO NOT MERGE - Fix broken aspect ratio in mirror

### PR DESCRIPTION
**Pull request by jherico**
Currently the mirror inset is rendered as if its aspect we the same as the primary rendering window.  This is barely perceptible when the window is full screen, but if you resize the main window to make it very narrow and tall or very short and wide, the mirror rendering becomes correspondingly distorted.  

Changing the boolean parameter provided to `Application::updateProjectionMatrix(Camera& camera, bool updateViewFrustum)` to true seems to correct this without adverse effect.  Presumably the rendering pipeline used by Application requires the stored view frustum and the current projection matrix to match (or else perhaps it is somewhere using the internal frustum to override the projection matrix during rendering).  

In fact, this spot in the code is the only place I can find where `updateProjectionMatrix()` is used with an alternate camera and the only place where the second parameter is set to false, leading me to wonder what the purpose of this is.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f03baa12f31a90a211d53e1ca34a1ce3eddd36e6 available at: https://gist.github.com/6719bb19a087e96f6cb7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8752aef7a54a04dc4bfe08a410dc064955f15312 available at: https://gist.github.com/6719bb19a087e96f6cb7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 596ec7d923350d9ef6edd9681c4f324632bb6925 available at: https://gist.github.com/6719bb19a087e96f6cb7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4466.dmg

**Comment by ZappoMan** [comment]
Do you want to close this one? I like the other approach better indeed!

**Pull request closed without merging**
