### PR TITLE
WL 21664 - Window.innerHeight should not include the menu bar

### PR DESCRIPTION
**Pull request by cain-kilgore**
> 2D overlays are positioned with respect to the drawable area (i.e., excluding the menu bar): an overlay positioned at 0,0 is drawn immediately underneath the menu bar.
> 
> Similarly for the values returned by Window.getDeviceSize() and Window.geometryChanged()
> 
> These are all pulled from 
> qApp->getWindow()->geometry()
> 
> Task:
> Fix the return back from Window.innerHeight, Window.getDeviceSize, and Window.geometryChanged to reflect the actual height minus the menu bar.
[Worklist 21664](https://worklist.net/21664)

## Test Plan
1. Install this PR
2. Enable Developer/Advanced Menu
3. Open the Console and Run `Window.innerHeight` and `JSON.stringify(Window.getDeviceSize())`
4. Confirm that the Y value is the size of the Interface window (Excluding Title & Menu Bar) on both results.
5. Run this: `Window.geometryChanged.connect(function(e) { print(JSON.stringify(e)); });` and start changing the size of the Window and comparing the console output to the actual size - confirm it's all correct.
6. Quickly run `Window.menuHeight` and confirm it prints the height of the Menu Bar.
7. Check the scripts [listed here](https://github.com/highfidelity/hifi/pull/12102#issuecomment-356032365) and ensure they're still running as expected with no strange results.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6046/app_12102_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6046/HighFidelity-Beta-PR12102-47038e43495967e5a69c73588bff15ea69e772f7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6046/HighFidelity-Beta-PR12102-47038e43495967e5a69c73588bff15ea69e772f7.dmg

**Comment by ctrlaltdavid** [comment]
- I don't think it's useful to add a Window.menuHeight to the JavaScript API.
- If not done so already, need to check existing hifi and hifi-content repositories' scripts for how they currently use Window.innerHeight (in particular if they adjust for the menu bar height). I couldn't see any occurrences at first glance.
- Test plan should probably include testing hifi and hifi-content repositories' scripts / apps (all? some? particular ones?) that use Window.innerHeight to make sure they aren't broken with the change.

**Comment by cain-kilgore** [comment]
@MiladNazeri might know better about what scripts use it.

**Comment by MiladNazeri** [comment]
In Hifi-content the following are used:
Marketplace/camera-move/app.js
Marketplace/spectator-camera/spectatorCamera.js
Marketplace/camera-move/app-camera-move.js

In the main repo there are 22 occurances, but the ones that aren't archived and that look like they are signifigant are the following:
scripts/developer/utilities/render/debugAmbientOcclusionPass.js
scripts/developer/utilities/render/debugSubsurfaceScattering.js
interface/resources/html/raiseAndLowerKeyboard.js
scripts/system/libraries/progressDialog.js
scripts/system/libraries/WebTablet.js
scripts/system/libraries/entityCameraTool.js
scripts/system/notifications.js
scripts/system/edit.js
scripts/system/html/js/entityList.js

I think the above are the important ones to see if anything is breaking

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASSED @conklin94122

**Comment by ctrlaltdavid** [comment]
In addition to removing the Window.menuHeight property, the JSDoc comments at the top of WindowScriptingInterface.h needs to be to remove, "plus the height of the menu bar", from the description of the innerHeight property.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6133/app_12102_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6133/HighFidelity-Beta-PR12102-0e3913baffd9193cd6db957701a38331cc587fd5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6133/HighFidelity-Beta-PR12102-0e3913baffd9193cd6db957701a38331cc587fd5.exe

**Comment by cain-kilgore** [comment]
@misslivirose Done :)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6185/app_12102_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6185/HighFidelity-Beta-PR12102-b26e31a36244579a41516b79d84754ea122c34fd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6185/HighFidelity-Beta-PR12102-b26e31a36244579a41516b79d84754ea122c34fd.dmg

**Pull request merged**
