### PR TITLE
Preload Shapes app asset files so that they're in disk cache ready for use

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Testing**
- Start Interface and wait for content to load.
- Run the \unpublishedScripts\marketplace\shapes\shapes.js
- Inspect the program log: after the last script file, /unpublishedScripts/marketplace/shapes/modules/uit.js, is loaded you should see entries for around 50 or so FBX and SVG files being downloaded.

**Comment by ctrlaltdavid** [comment]
QA ready

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4062/HighFidelity-Beta-PR11574-f3b2ccf5f821d57c388d350ca3696244d9bb284a.dmg

**Comment by marko8904** [comment]
build this please

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4063/HighFidelity-Beta-PR11574-f3b2ccf5f821d57c388d350ca3696244d9bb284a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4063/HighFidelity-Beta-PR11574-f3b2ccf5f821d57c388d350ca3696244d9bb284a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Start Interface and wait for content to load. **Check**
Run the \unpublishedScripts\marketplace\shapes\shapes.js **Check, used github RAW link to .js**
Inspect the program log: after the last script file, /unpublishedScripts/marketplace/shapes/modules/uit.js, is loaded you should see entries for around 50 or so FBX and SVG files being downloaded.**Fail, errors shown in logs also regarding "getTransform"**
Check that each tool options dialog (Color, Stretch, etc.) displays. **Fail, Shapes app not opening, just changes highlight to white**

Logs attached.
[Logs.zip](https://github.com/highfidelity/hifi/files/1377342/Logs.zip)

**Comment by Nex-Pro** [comment]
### PASS all good.

Log file available if needed.

looks like ...

[10/11 23:28:45] [DEBUG] [hifi.scriptengine] Done downloading script at: "https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/modules/uit.js"
[10/11 23:28:45] [DEBUG] [hifi.scriptengine] Loaded:  "https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/modules/uit.js"
[10/11 23:28:47] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/tool-icon.fbx
[10/11 23:28:47] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/gray-header.fbx
[10/11 23:28:47] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/blue-header-bar.fbx
[10/11 23:28:47] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/create-heading.svg
[10/11 23:28:47] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/cube.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/sphere.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/tetrahedron.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/octahedron.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/icosahedron.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/dodecahedron.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/hexagon.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/prism.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/octagon.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/cylinder.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/cone.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/create/circle.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/green-header-bar.fbx
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/back-icon.svg
[10/11 23:28:48] [DEBUG] [hifi.networking.resource] Starting request for: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/tools-heading.svg

**Comment by ctrlaltdavid** [comment]
@YuppyPlays You log files look good to me. I've updated the test to say that you need to be in HMD mode to see the UI displayed on your non-dominant hand.

**Comment by ctrlaltdavid** [comment]
QA ready

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4075/HighFidelity-Beta-PR11574-74899e4798536886f5877387db57a1740c2d64a6.dmg

**Comment by Nex-Pro** [comment]
Testing with win build when it arrives.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4075/HighFidelity-Beta-PR11574-74899e4798536886f5877387db57a1740c2d64a6.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
@ctrlaltdavid 

Pngs show up in the log, everything else is fine.

[10/12 02:58:27] [DEBUG] [hifi.networking] Request finished for https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/color/color-circle-black.png
[10/12 02:58:27] [DEBUG] [hifi.networking] Request finished for https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/color/pick-color-label.svg
[10/12 02:58:27] [DEBUG] [hifi.networking] Finished loading: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/color/color-circle-black.png
[10/12 02:58:27] [DEBUG] [hifi.networking] Finished loading: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/color/slider-alpha.png
[10/12 02:58:27] [DEBUG] [hifi.networking] Finished loading: https://raw.githubusercontent.com/ctrlaltdavid/hifi/f3b2ccf5f821d57c388d350ca3696244d9bb284a/unpublishedScripts/marketplace/shapes/assets/tools/color/slider-white.png

**Comment by Nex-Pro** [comment]
IMO **Pass**

**Pull request merged**
