### PR TITLE
Added docker-supported build process for Android builds

### PR DESCRIPTION
**Pull request by marko8904**
The documentation for how to use the Dockerfile is in
build_recipes.md.

Build process is encapsulated in build_android.sh while
the environment is constructed and run with start_build_container.sh
using the Dockerfile.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10638/HighFidelity-Beta-PR13395-4f594fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10638/HighFidelity-Beta-Interface-PR13395-4f594fa.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10646/HighFidelity-Beta-PR13395-e2468b4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10646/HighFidelity-Beta-PR13395-e2468b4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10646/HighFidelity-Beta-Interface-PR13395-e2468b4.dmg

**Comment by MattHardcastle** [comment]
This Dockerfile is excellent. We should create more of these Dockerfile based build environments. For instance, I'd love a container that had Qt, CMake, OpenSSL, and the rest of High Fidelities dependencies installed. There is probably some natural dependency tree in them too:
* hifi-qt -> hifi-linux-builder
* hifi-qt -> hifi-android-builder

My only suggestion here is not to add the Dockerfile to hifi repository. Adding it here ties any changes to it to the hifi release process. It should go into a build system related repo.

Great work!

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10727/HighFidelity-Beta-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10727/HighFidelity-Beta-Interface-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10727/HighFidelity-Beta-PR13395-6081a79.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10727/HighFidelity-Beta-Interface-PR13395-6081a79.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10732/HighFidelity-Beta-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10732/HighFidelity-Beta-Interface-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10732/HighFidelity-Beta-PR13395-6081a79.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10732/HighFidelity-Beta-Interface-PR13395-6081a79.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14160/HighFidelity-Beta-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14160/HighFidelity-Beta-Interface-PR13395-6081a79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14160/HighFidelity-Beta-PR13395-6081a79.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14160/HighFidelity-Beta-Interface-PR13395-6081a79.exe

**Comment by shanzzam** [comment]
@marko8904 can you confirm this PR is no longer needed as we merged the PR https://github.com/highfidelity/hifi/pull/14521 from @jherico a few days ago.

**Comment by shanzzam** [comment]
Closing due to Austin's work that addressed this

**Pull request closed without merging**
