### PR TITLE
Tuning pass on anim-graph, using the new blend modes and engine features

### PR DESCRIPTION
**Pull request by dooglifeSF**
Change blend modes and times throughout the animation graph to take advantage of both-eval blends and non-linear blends.  Known issue: the evaluateBoth blends seem to speed up the animation 2x so there are some unintentional lurches.  I counter this effect in places with a reduced timeScale.  Bug is filed on that one.  Overall, this removes a lot of abrupt animation discontinuities, even with the framerate bug.

### CODE REVIEW

**Comment by dooglifeSF** [comment]
This is the task:  https://highfidelity.atlassian.net/browse/BUGZ-1182

**Comment by dooglifeSF** [comment]
And this is the evaluateBoth bug I discovered, logged today: https://highfidelity.atlassian.net/browse/BUGZ-1252

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20868/HighFidelity-Beta-PR16062-2f3f6be.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20868/HighFidelity-Beta-Interface-PR16062-2f3f6be.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20868/HighFidelity-Beta-PR16062-2f3f6be.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20868/HighFidelity-Quest-Beta-PR16062-2f3f6be.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20868/HighFidelity-Beta-PR16062-2f3f6be.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20868/HighFidelity-Beta-Interface-PR16062-2f3f6be.exe

**Pull request merged**
