### PR TITLE
Beta Release 46 - Includes up to Developer Release 6801

### PR DESCRIPTION
**Pull request by cozza13**
- Remove dependency between codec plugins and UI
 - Fix for eye direction when no look at targets are present. 
 - Added script that will attach an entity to a vive sensor
 - EZRECORD app 
 - Pole vector support for elbow and knee joints
 - Fix a bug that could cause a static variables in the input system to have a bad value 
 - Fix toolbar button mouse click when they were added via the tablet scripting interface 
 - Fix static plugin initialization on Linux
 - Fix warnings about creating QObjects with parents in different thread 
 - Integrate attachments into doppleganger mirror 
 - MoCap wide stance fix for calibration 
 - Disable silence + ban buttons for replicated users 
 - Fix toolbar button activation states 
 - Adding trace profiling feature Script 
 - Use QEventLoop and a timer for a less CPU using sleep + event-processing 
 - Eliminated toe wiggle while pucks are enabled. 
 - Cleanup entity dependencies 
 - Speeds up the azimuth/gain calculation by 4x and 2x, with negligible loss of precision (angular error < 0.0001 radians)
 - Update DomainMetadata.cpp 
 - Fix loading of incorrect joint data for the avatar recording 
 - Fix projection & lighting issues identified with 2nd rendering pipeline In Master 
 - Made changes to return the action "snapshot_taken" and location.href whenever a user takes a snapshot. 
 - Fix snapshot connection errors 

Smoke test : http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

RC functionality test: https://docs.google.com/spreadsheets/d/1F8S8a8lyze1wEczT8hc0dmz3_7QLDiHOxntKW6g0UjY/edit#gid=1080464620

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1262/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by cozza13** [comment]
ok to test

**Comment by cozza13** [comment]
http://builds.highfidelity.com/HighFidelity-Beta-6801.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1263/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1265/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1265/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.dmg

**Comment by cozza13** [comment]
ok to test

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS (SEE NOTES)
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: FAILURE.  Home tutorial did not physically exist in localhost.  Screen shot enclosed.  Keep note ```reverbTest.js``` did not work in the QA menu however it DID work when loading the script manually.  This is just an issue of the testing script being updated with the new link to the file and NOT a fail in my opinion.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |52 |60 |59
**Present Rate**: |70 |60 |52
**Present New Rate**: |52 |60 |70
**CPU Buffer Count**: |2177 |1482 |2518
**GPU Buffer Count**: |736 |638 |553
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |137 |115 |144
**GPU Texture Count**: |58 |92 |77
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |69643 |296423 |1628527
**Triangle Rate**: |4352687 |21173071 |108568466
**API Drawcall Count**: |51 |195 |181
**Drawcall Count**: |52 |203 |186
**Drawcall Rate**: |3250 |14500 |12400
**State Changes Texture Count**:|79 |222 |228
**Pipeline Count**: |25 |34 |27
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|FAILURE. I successfully installed a fresh copy of 'Home' however the tutorial object did not exist in localhost. Screen shot attached.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|UNABLE TO TEST as ```dev-playa``` does not have the firework as there is a theater there.
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED
capture

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1267/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1267/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.exe

**Comment by kevinmthomasse** [comment]
I re-did the test with the link provided by @cozza13 https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1267/HighFidelity-Beta-PR10867-3f48c7aef55f6bae111cbe68f1faf4a35df0a87e.exe and I can confirm that it did immediately take me to the tutorial which was a SUCCESS.

**Comment by OmegaHeron** [comment]
@cozza13 - Was late getting back from a trip, but, gave this a smoke test and it passes.  Will post formal test results first thing tomorrow.

**Comment by Nex-Pro** [comment]
Testing this as requested.

**Comment by Nex-Pro** [comment]
### Beta Release 46 - Includes up to Developer Release 6801

# #10867

#### Testing platform:

CPU: Intel Workstation i7 16gb ram.
GPU: Nvidia GTX1070 8gb vRam
AUDIO: USB headset
HMD: HTC Vive
Controllers: HTC Vive

#### Startup conditions:

Fresh install no copy of settings.

## QA Test
QA Tester: **Piper.Peppercorn**
localhost 'createTestBlocks.js' Result: **SUCCESS**
localhost ATP Upload + Edit Result: **SUCCESS**
Echo Server Audio: **SUCCESS**
localhost 'harmonicOscillator.js' Result: **SUCCESS**
localhost 'reverbTest.js' Result: **SUCCESS** had to load via scripts pane.
localhost 'playaPerformanceTest.js' Result: **FAILURE**
dev-playa 'playaPerformanceTest.js' Result: **FAILURE**
dev-demo 'playaPerformanceTest.js' Result: **FAILURE**
QA Pass: **FAILURE**

Additional Test Results + Observations**:

### Startup issues:

"Loading Content" indicator does not go away.
Staging room takes some while to load and pops in and out of view a couple of times.
Rest of tutorial zone was revealed momentarily prior to starting tutorial.
Content loading seems to be very slow.
Had to start tutorial with "Content Loading" indicator still on screen after several minutes.
After completing tutorial noted same issus as Kevin. The teleport used to repeat tutorial is absent.

Problem with Vive hand controller reliability seen in previous builds persists.
Individual actions on hand controllers seem to become unavailable.
Several other users have noted issues like this with the Vive controllers lately.

### Feedback:

The automatic far grab to near grab continues to annoy ! Please provide a way to turn this off.

There is an inconsistency in the naming of the ATP pane. In the menu it is called "Asset Browser" in the create panel it is "Asset Server".

We need to fix the issues with missing testing content such as dev-playa or come up with an alternative.

### Reverb test fail:

[6/3 13:53:39] [reverbTest.js] INFO - Script Engine starting:reverbTest.js
[6/3 13:53:39] [reverbTest.js] ERROR - [UncaughtException evaluate] Error: Can't find variable: AudioDevice in http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38
[Backtrace]
    <global>() at http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38
[6/3 13:53:50] [reverbTest.js] INFO - Script Engine stopping:reverbTest.js
[6/3 13:53:50] [reverbTest.js] INFO - Script Engine shutting down:reverbTest.js
Stats has been broken/unreliable for some time.

Able to load via scripts pane.

### Stats issues:

Unable to get good stats due to domains not being as expected.
Also Stats aren't reading correctly.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |0 |0 |0
**Present Rate**: |0 |0 |0
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |2203 |1435 |647
**GPU Buffer Count**: |841 |631 |296
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |200 |117 |55
**GPU Texture Count**: |158 |94 |48
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |60108 |402694 |25970
**Triangle Rate**: |6010800 |40269400 |2360909
**API Drawcall Count**: |49 |189 |24
**Drawcall Count**: |84 |380 |34
**Drawcall Rate**: |8400 |38000 |3090
**State Changes Texture Count**:|72 |216 |45
**Pipeline Count**: |30 |43 |29
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|**pfft**
**Test 2**|Install a fresh copy of "Home' and do tutorial|**success** apart from content forever loading. of note loading indicator was no longer showing on return to localhost.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**success**
**Test 4**|Launch firework, on dev-playa, can other hear?|**Cannot test** No available content.
**Test 5**|Switch avatar and make sure it does not crash|**Success**
**Test 6**|Test group functions|**Untested**
**Test 7**|Test Ambisonic audio with markeplace item|**Success**
**Test 8**|Enrure that you can distance grab|**Success**
**Test 9**|Bring up and edit an objects with hand controllers|**Success**
**Test 10**|Test PAL functionality|**Untested**
**Test 11**|Test Tablet in 2D and 3D|**FAIL** Toolbar remains on screen. See snapshot !

hifi-snap-by-piper-peppercorn-on-2017-07-03_14-33-35

hifi-snap-by-piper-peppercorn-on-2017-07-03_14-20-22

**Comment by OmegaHeron** [comment]
Having Internet issues today - but things of note (not failures since present in Master)

HMD will not track head movement and show in Interface unless hand controllers are present/on (nothing to do with AV in use - it does not work regardless of choice until hand controller(s) come on).  Applies to my setup with either an Oculus DK2 or CV1.

Audio state no longer follows traditional way of being in state left at last Interface run.  In past, if mic was *off* when Interface closed it would be *off* when Interface runs again -- if on it would be on.  Current behavior is always on at each run of Interface.

I was able to reproduce issue @Nex-Pro saw with tablet mode once - I was setup for using tablet mode in desktop or HMD but had began session with it set to use tablet in HMD and hud with desktop.  In past it was 100% reliable that if you were in HUD mode you'd not see table, if in Tablet mode you'd not see HUD.

Issue with reverb test persists -- workaround being to run reverb test manually from copy installed with Interface then it passes.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1285/HighFidelity-Beta-PR10867-ac87ea9660339db62ca1a801eec366c45cee6f8f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1285/HighFidelity-Beta-PR10867-ac87ea9660339db62ca1a801eec366c45cee6f8f.exe

**Pull request merged**
