### PR TITLE
Fix Interstitial GoTo button stretch

### PR DESCRIPTION
**Pull request by wayne-chen**
- Leave interstitial page GoTo button in its natural dimensions

## TEST PLAN
- Launch Interface
- - Enable `Settings > Developer Menu`
- Open `Developer > Console`
- Enter in `Settings.setValue("enableInterstitialMode", true);`
- Relaunch Interface 
- When navigating to a domain, the GOTO button should look like the one below (not stretched)
image
- Try this both in Desktop and HMD mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13137/HighFidelity-Beta-PR14038-8bd698b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13137/HighFidelity-Beta-PR14038-8bd698b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13137/HighFidelity-Beta-Interface-PR14038-8bd698b.exe

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Pull request merged**
