### PR TITLE
CR for Job #21412 - Add "Report a Problem" feature

### PR DESCRIPTION
**Pull request by mnafees**
Code Review for Job #21412 - Workitem available at https://www.worklist.net/21412

### CODE REVIEW

**Comment by mnafees** [comment]
## Testing Plan

Launch interface and open the "Help" page. There is a "Report Problem" link to the top-right corner of the tablet web window. Clicking on it should open the default email client with the recipient address as support@highfidelity.com

**Comment by tapalisa** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2215/HighFidelity-Beta-PR11107-93ad1b6cbf8c1f3fe1a979ef21d8419b5a634f08.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2215/HighFidelity-Beta-PR11107-93ad1b6cbf8c1f3fe1a979ef21d8419b5a634f08.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

All seems to be a **Pass** here - with windows 10 default set to outlook this works perfectly (also for Win10 Mail app)

:)

**Comment by ZappoMan** [comment]
I don't think this is going to work for people in the HMD...

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3018/HighFidelity-Beta-PR11107-93ad1b6cbf8c1f3fe1a979ef21d8419b5a634f08.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3018/HighFidelity-Beta-PR11107-93ad1b6cbf8c1f3fe1a979ef21d8419b5a634f08.exe

**Comment by anshuman64** [comment]
I think the behavior is fine in HMD. It just puts you in Pause mode while opening a new window. You can easily unpause and continue in HMD if you want, or take off your headset to make the email.

**Comment by themelissabrown** [comment]
@mnafees your test plan didn't include looking to be sure log files were included in the email sent. It appears that core functionality isn't working. Can you look into it?

**Comment by mnafees** [comment]
@themelissabrown Sp so you want me to zip up the log files even if we can't attach it to the email atm?

**Pull request merged**
