### PR TITLE
Fix RunningScripts in tablet mode

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Test Plan:
- Verify you can pull up the running script in tablet mode
- Verify you can add scripts by double-clicking it.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3535/HighFidelity-Beta-PR11434-6cdbf0c44a971efb836843967e0a8a1a5dfa7f9c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3535/HighFidelity-Beta-PR11434-6cdbf0c44a971efb836843967e0a8a1a5dfa7f9c.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Plan
Test | Result
--- | ---
Verify you can pull up the running script in tablet mode | Pass
Verify you can add scripts by double-clicking it. | Pass
Verify that the rest of the tablet hasn't broken | Pass

All good from here!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
