### PR TITLE
Steam store commerce 83

### PR DESCRIPTION
**Pull request by howard-stearns**
RC 83 version of https://github.com/highfidelity/hifi/pull/15994

https://highfidelity.atlassian.net/browse/DEV-325

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20635/HighFidelity-Beta-PR15999-d5d53af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20635/HighFidelity-Quest-Beta-PR15999-d5d53af.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20635/HighFidelity-Beta-PR15999-d5d53af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20635/HighFidelity-Beta-Interface-PR15999-d5d53af.dmg

**Comment by JeffClinton** [comment]
build this please

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20642/HighFidelity-Beta-PR15999-d5d53af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20642/HighFidelity-Beta-Interface-PR15999-d5d53af.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20642/HighFidelity-Beta-PR15999-d5d53af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20642/HighFidelity-Quest-Beta-PR15999-d5d53af.apk)

**Comment by JeffClinton** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20644/HighFidelity-Beta-PR15999-d5d53af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20644/HighFidelity-Beta-Interface-PR15999-d5d53af.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20644/HighFidelity-Beta-PR15999-d5d53af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20644/HighFidelity-Quest-Beta-PR15999-d5d53af.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20644/HighFidelity-Beta-PR15999-d5d53af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20644/HighFidelity-Beta-Interface-PR15999-d5d53af.dmg

**Pull request merged**
