### PR TITLE
fix domain-server settings change without password change

### PR DESCRIPTION
**Pull request by birarda**
- fixes a bug where domain-server settings could not be saved without an HTTP auth password change

### CODE REVIEW

**Comment by birarda** [comment]
Fix for https://app.asana.com/0/26225263936266/111189681307631.

**Comment by birarda** [comment]
Test:

- On current master, saving DS settings will fail if the HTTP basic auth password is not being changed (page locks up and error is shown in JS console)
- On this PR, saving DS settings with the HTTP basic auth password field left unchanged should succeed

**Comment by hifi-gustavo** [comment]
Build console output for commit: aad98cc25d60f9ad3d36d1986ced7a48f5d35ea3 available at: https://gist.github.com/5799ec9f5e6206ed124e7853957ff227<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7635.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7635.dmg

**Comment by OmegaHeron** [comment]
Tested with this PR stack running on Linux - Client side = Windows + Firefox.

Changing other things and not touching auth settings works as expected not corrupting login info.
Changing password alone works as expected.
Changing username **and** password works as expected.
QA Pass :+1: 

Now we come to messy bits where someone could conceivably mess things up.  Remove username and hit apply.  DS does not restart.  Change http username but do not change password and hit apply.  DS does not restart.  Once either of these actions have been triggered web page can't manipulate http auth username and password changes properly again until reloaded.

While I would expect a savvy user to do neither of the above, both lead to a case where you have to reload page to restore interaction with http username/password boxes as it seems to get confused when you try to do something ill advised.  If one thought I'm sick of doing this name password thing (maybe on a LAN only setup) and thought to blank out name/password and apply they get a fail.

**Comment by birarda** [comment]
I'll test through what you're describing to see if there's any quick fix for those odd cases. Thanks!

**Comment by birarda** [comment]
@OmegaHeron I've just included a fix to allow for the empty password.

I can't repro the cases above you're describing where one of the username or password are empty. Were you testing on this PR or on master when that was happening?

**Comment by OmegaHeron** [comment]
Was testing on this PR - I may have been unclear on what I saw.

Starting point.  A setup where you have defined a http username and password.
Remove user name - apply changes.
Note that DS does not restart, user name field is blank and password field is disabled.
Populate username field and note that password field remains disabled even if you hit apply change.

**Comment by birarda** [comment]
Started from that point - removed username. DS restarted and I was logged back in (since that effectively disables the auth). 
Added back a new username, was prompted to login. What browser are you using?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 455d2d50480b0e3fda9436e1a1265fd93322cb62 available at: https://gist.github.com/5799ec9f5e6206ed124e7853957ff227<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7635.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7635.dmg

**Comment by OmegaHeron** [comment]
Windows + Firefox and it's Lastpass modifying behavior.  Lastpass is trying to "protect" integrity of saved credentials and playing tricks with fields.  Tried it with Firefox on another system without Lastpass and it's ok.  Sorry about the wild goose chase there.  Testing applied change in a few minutes when compile is done.

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Firefox browser - Stack on Linux.
I can do other things not related to auth and not have auth borked :+1: 

I can change username keeping existing password.
I can change password keeping existing username.
I can remove auth by blanking username and password field.

QA Pass

**Pull request merged**
