### PR TITLE
Bugfix for #12759 Overlays.editOverlay not applying subImage property

### PR DESCRIPTION
**Pull request by WolfGangS**
The anchor property of image was not being recalculated after subImage was being applied from javascript.

This change moves the anchor margin calculation to its own method, and calls it in both places that it is needed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by WolfGangS** [comment]
What you should see with this fix.

  ✔️

What you saw before

  ❌

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8503/HighFidelity-Beta-PR12790-787127b149d35cae3565b87ca3e94e47c7a7149e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8503/HighFidelity-Beta-PR12790-787127b149d35cae3565b87ca3e94e47c7a7149e.exe

**Comment by WolfGangS** [comment]
Accidentally commited extra to my branch, have undone it, apologies.

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
Running the script from  #12759 causes the hifi logo to shift as it does in the provided gif. It does not remain still.

**Pull request merged**
