### PR TITLE
Restore packing of QRC qml and resources to interface.exe in DEV_BUILD

### PR DESCRIPTION
**Pull request by samcake**
The packing of the qml and resource folder was deactivated in DEV_BUILD (local builds of a developer)

This was preventing me from using qml contained in the QRC from tool scripts.

#### TEST PLAN
There shouldn't be any impact to release build.
this is only useful for local build of a developer.
a developer should be able to use a script such as luci.js (contained in developer/utilities/render) and see the ui properly. this is not the case before this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6030/app_12100_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6030/HighFidelity-Beta-PR12100-5a5d475c6c92509e13ce31508da2d5ed1b0790eb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6030/HighFidelity-Beta-PR12100-5a5d475c6c92509e13ce31508da2d5ed1b0790eb.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Stopped testing

**Pull request merged**
