### PR TITLE
fix skybox default

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA:

Test this for skyboxes and procedural skyboxes:

In testing, only use one skybox, so that the default will show if your skybox does not. Do not layer skyboxes.

- If there is a procedural skybox set, it should be shown, not the default (it may need to load first)
- If there is no skybox set, the default horizon should show
- If there is a color (other than 0,0,0) set, the color should be used as the skybox (this is new)
- If there is a texture set, the texture should be used as the skybox
- If there is a color (other than 0,0,0) and a texture set, a tinted version of the texture should be used as the skybox
- When you turn off your skybox, the default should come back

**Comment by hifi-gustavo** [comment]
Build console output for commit: 24162f0f3d26a235bb5a9833a2f5e9e4efa87aeb available at: https://gist.github.com/8fb6d9970559e49eee656e2adde2b75a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8527-24162f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8527-24162f0.dmg

**Comment by cozza13** [comment]
One problem is that it keeps the skybox of the previous domain until the new skybox has loaded.  e.g. https://gyazo.com/cb769ca1d97d54a36511d42a5d9df958

**Comment by hifi-gustavo** [comment]
Build console output for commit: 996346980d980b7d47a2e73dbacace2d0d78fe5c available at: https://gist.github.com/8fb6d9970559e49eee656e2adde2b75a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8527-9963469.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8527-9963469.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

Test 1 - Unconnected space.  It shows the blue horizon default.
Test 2 - Move to domain with zone using nothing but a texture.  Begins with default until zone texture loads then shows intended visual.
Test 3 - Move to domain with procedural zone (star field like at playa).  Begins with default - then loads cloudy sky - then loads stars (day/night cycle).
Test 4 - Moving to dev-demo.  Default - then sunny skies.
Test 5 - Moving to dev-playa.  Default - then cloudy skies - no transit to day/night procedural which is odd as looking at its zone entries I see it has the day/night procedural, but it may be an error with dev-playa as its user data looks.. odd.
Test 6 - Back to disconnected space.  Default blue horizon.

One thing about dev-playa.  It has nested zones.  There's a sub-zone just in front of default landing posit.

Other than the standard weirdness at dev-playa this PR seems to do what it claims to do.

**Comment by zzmp** [comment]
@OmegaHeron I am working on a separate fix to restore nested zones.

**Pull request merged**
