### PR TITLE
Replace Developer > Network > Disk cache editor with menu action 

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Old Developer > Network > Disk Cache Editor menu item is no longer avilable:
- In Interface's menu items.
- In the tablet's menu items.

New Developer > Network > Clear Disk Cache menu item is available and works:
- In Interface's menu items.
- In the tablet's menu items.

Hint: Clearing disk cache will output one of the following two messages to the program log:
- "AssetClient::clearCache(): Clearing disk cache."
- "No disk cache to clear."

**Comment by hifi-gustavo** [comment]
Build console output for commit: 939b4f16129c9d81f5b2ae145933cbf145fbb8f9 available at: https://gist.github.com/8c27ae173cc11a4eed1e25839934c996<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9929-939b4f1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9929-939b4f1.dmg

**Comment by ZappoMan** [comment]
@ctrlaltdavid - shouldn't the test plan also verify that the disk cache is cleared? I realize that you didn't change that behavior but we should still take the opportunity to document and test that the cache is actually cleared. :)

**Comment by cozza13** [comment]
QA Faile. 

Does not seem like the cache is cleared. 

repro 
- Go to Welcome, load assets
- Go to Playa
- Clear disk cache
- Go to Welcome, then I see it pulling things from cache 

[03/17 09:24:42] [INFO] [default] AssetClient::clearCache(): Clearing disk cache.
[03/17 09:24:46] [DEBUG] [hifi.scriptengine] Clearing ATP scripts from ScriptCache
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://hifi-content.s3.amazonaws.com/caitlyn/production/soundEmitter/soundLoopEmitter.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://hifi-content.s3.amazonaws.com/DomainContent/Welcome Area/Scripts/portal.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://hifi-content.s3.amazonaws.com/caitlyn/production/soundEmitter/soundLoopEmitter.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://mpassets.highfidelity.com/76711111-ef6d-457b-aef0-63e9206d2964-v1/startGameButtonClientEntity.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://mpassets.highfidelity.com/76711111-ef6d-457b-aef0-63e9206d2964-v1/utils.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://hifi-content.s3.amazonaws.com/caitlyn/production/soundEmitter/soundLoopEmitter.js"
[03/17 09:24:47] [DEBUG] [hifi.scriptengine] Found script in cache: "http://hifi-content.s3.amazonaws.com/DomainContent/Welcome Area/Scripts/portal.js"
-

**Comment by ctrlaltdavid** [comment]
@cozza13 The menu item doesn't do what you might think it does. It deletes the disk files but doesn't clear in-memory caches (AnimationCache, ModelCache, SoundCache, TextureCache) or clear entities out of the view frustum. I've updated the test notes with the location of the cache flies.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3b9d588ecacc5e6793aa61bee12d01bc332cbfb available at: https://gist.github.com/8c27ae173cc11a4eed1e25839934c996<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9929-e3b9d58.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9929-e3b9d58.dmg

**Comment by cozza13** [comment]
after retesting it is a pass

**Pull request merged**
