### PR TITLE
Try to fix ModelOverlay texture loading

### PR DESCRIPTION
**Pull request by SamGondelman**
Includes Howard's change from https://github.com/highfidelity/hifi/pull/13324

https://highfidelity.fogbugz.com/f/cases/11185/Crash-Tablet-people

Test Plan:
- Go to a domain with multiple avatars.
- While looking at the avatars, open the People app.  Spheres with a transparent "halo" like effect around them should appear over each avatar.
- Click on one of the spheres.  Both it and the halo should change color.
- Repeatedly open and close the People app.  You shouldn't crash.
- Run [this](https://gist.githubusercontent.com/SamGondelman/598039055c2ba58744c0bc3aa94cdb62/raw/0060ce9c563b388db1602171817bbef467e03285/ModelOverlayTextures.js).  You should see a yellow rectangle.  Press "u" and it should become lime green.  Press "u" again and it should go back to yellow.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10476/HighFidelity-Beta-PR13340-310e2ee.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10476/HighFidelity-Beta-PR13340-310e2ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10476/HighFidelity-Beta-Interface-PR13340-310e2ee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10476/HighFidelity-Beta-PR13340-310e2ee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10476/HighFidelity-Beta-Interface-PR13340-310e2ee.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10487/HighFidelity-Beta-PR13340-c9a5b6b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10487/HighFidelity-Beta-PR13340-c9a5b6b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10487/HighFidelity-Beta-Interface-PR13340-c9a5b6b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10487/HighFidelity-Beta-PR13340-c9a5b6b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10487/HighFidelity-Beta-Interface-PR13340-c9a5b6b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10493/HighFidelity-Beta-PR13340-2dae613.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10493/HighFidelity-Beta-PR13340-2dae613.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10493/HighFidelity-Beta-Interface-PR13340-2dae613.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10493/HighFidelity-Beta-PR13340-2dae613.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10493/HighFidelity-Beta-Interface-PR13340-2dae613.exe

**Comment by howard-stearns** [comment]
Yup, this looks good to me. Works well, and after consultation with @zfox23, we concur on the pal.js changes.

With regard to RC69 vs RC70, I'd personally like to see it in RC69, since it fixes a crash and a regression, and generally makes the product work more comprehensibly.

**Comment by zfox23** [comment]
I agree; I'd also like to see this in 69.

**Comment by SamGondelman** [comment]
Sounds good to me!

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Test plan passes but when script runs and U is pressed, the yellow rectangle changes from yellow to gray. And sometimes will flash red or white.
hifi-snap-by--on-2018-06-11_15-26-28

**Comment by SamGondelman** [comment]
@qlimnavarro for some reason that color looked greenish to me last week but neither that nor the flashing are a problem.  Considering this a pass.  Thank you!

**Pull request merged**
