### PR TITLE
Fix the local lights issue

### PR DESCRIPTION
**Pull request by samcake**
this one is on me when i did PR10659 

The first configuration of the LightClustering pass doesn't initialize the pass completely because the _lightClusters member is not created.
Before the PR10659 this configuration call would happen continuously for other bad reasons. so after the first time, the _lightClusters would be allocated and configured correctly.
I removed the bad continous call, but didon;t see that problem. my bad....

While i was at it,  i  noticed a bunch of my favorite Developer/Utilities/Render/ scripts were failing because the newly introduced second camera Pipeline screws the getCOnfig behavior...
Just did a pass over these scripts to work again.

## TEST PLAN
The local lights work in this PR, not in master

Optional: All the scripts in the Developer/Utilities/Render/ work fine, they don't in master

### CODE REVIEW

**Comment by samcake** [comment]
i m testing the Script an d noticed a problem, give few minutes to address

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/880/HighFidelity-Beta-PR10748-ba9dbbb4d46bac650feed2d9db137723e071d4e8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/880/HighFidelity-Beta-PR10748-ba9dbbb4d46bac650feed2d9db137723e071d4e8.dmg

**Comment by samcake** [comment]
I don;t really seem to be able to address the issues with the scripts because of QML
it s not really "worse" than the current master, so please qa this PR as is
Working on fixing the scripts in another PR...

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed 
Local lights are now rendering in this PR vs Master.
Optional tests/scripts however failed. (Being worked on in other PR)

interface_2017-06-20_03-52-02
###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by samcake** [comment]
thanks guys

**Pull request merged**
