### PR TITLE
Edit vs mouse grab

### PR DESCRIPTION
**Pull request by sethalves**
- use local messaging to disable mouse-grab when edit.js is active

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/95553201732289

**Comment by sethalves** [comment]
to test:
- enable developer menus
- enable physics overlays (Menus --> Developer --> Physics --> Highlight Simulation Ownership)
- create a box and make it dynamic
- turn off edit.js
- use grab.js (mouse grab) to move the box and notice the green lightening which indicates a bullet action on the entity
- enable edit.js and select the box
- move the entity with the mouse again, and notice that there is no green lightening.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04e36f925a0f9c40d5e03086c0c834b7986bd5fd available at: https://gist.github.com/0ae6046eb13fc5c6261b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7277.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7277.dmg

**Comment by bluetoe** [comment]
I get green lightning with both no edit grab and while box is selected when editing and it reacts when colliding with other box or my avatar, with both plain grab or edit move

**Comment by sethalves** [comment]
Make sure you are running the 2 scripts from this pr.

**Comment by bluetoe** [comment]
oops

**Comment by sethalves** [comment]
https://rawgit.com/sethalves/hifi/edit-vs-mouse-grab/examples/edit.js
https://rawgit.com/sethalves/hifi/edit-vs-mouse-grab/examples/grab.js

**Comment by bluetoe** [comment]
Yes, seems to work fine with the correct edit.js and grab.js. Green lightning with grab, no lightning with edit. Sorry about that. I should have noticed what you were changing.

**Comment by sethalves** [comment]
np -- my test plan was incomplete.

**Pull request merged**
