### PR TITLE
Destroy PointerManager before PickManager

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/11412/crash-on-exit-involving-LaserPointer

Test plan:
- Shouldn't crash on shutdown.  Try several times.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6328/app_12183_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6329/app_12183_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6329/HighFidelity-Beta-PR12183-c3eb4b5ecd12ebbec9fcf24058087df14055e30b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6329/HighFidelity-Beta-PR12183-c3eb4b5ecd12ebbec9fcf24058087df14055e30b.dmg

**Comment by sethalves** [comment]
I got clean exits 4/5 times on Linux with asan, this is much better.  The 1 crash didn't look related to this.

**Comment by QAadahlin** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. 8/10 attempts crashed on shutdown.

@conklin94122

**Comment by sethalves** [comment]
Hm, this is difficult to test well.  I see more than one crash-on-exit, and this PR fixes the most common one (for me, on Ubuntu).  Maybe we should consider this a pass and move on to the next one.

**Comment by conklin94122** [comment]
@divyaelango88 ^^^

**Comment by ZappoMan** [comment]
@sethalves can you verify that the crash from the pointer cleanup DOES NOT EVER occur with this PR? If so, I agree... that for the purpose of this PR that would be a pass.

**Comment by sethalves** [comment]
I no longer see the targeted crash on ubuntu.

**Pull request merged**
