### PR TITLE
Webentity touch events

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/6681/Ensure-that-qt5-9-touch-event-fix-is-applied-to-web-entities-as-well

Test plan:
- Create Web entity
- iterate with it using mouse/stylus/etc
- make sure there is no regressions comparing to master branch

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4804/HighFidelity-Beta-PR11781-b6a2be76cc162ec916ce9ee8e0dd5bd45a83518e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4804/HighFidelity-Beta-PR11781-b6a2be76cc162ec916ce9ee8e0dd5bd45a83518e.exe

**Comment by SamGondelman** [comment]
I've already made this change in the pointers branch as a part of the UI improvements project and would feel better about not merging this to avoid conflicts later.

**Comment by themelissabrown** [comment]
@SamGondelman in that case, we'll close this PR.

**Comment by sethalves** [comment]
@SamGondelman if your PR has a very similar change, and this PR stands on its own, doesn't it make sense to merge the changes in different PRs?  If this change turns out to be the cause of some problem, isn't it better that it be on its own (so that git bisect or whatever can identify it)?

**Comment by SamGondelman** [comment]
@sethalves This PR copies logic from Web3DOverlay to Web entities.  Our branch abstracts the logic into OffscreenQmlSurface, and we're already investigating a known bug in the existing code.  Instead of copying buggy code into a second place *and* having to deal with a merge conflict later, I would rather just handle it in our branch.

**Comment by SamGondelman** [comment]
Closing this now that the Pointers PR has been merged.

**Pull request closed without merging**
