### PR TITLE
Fix noise reduction checkbox not always working

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Run up Interface multiple times, sometimes with Settings > Audio > Enable Noise Reduction enabled and sometimes with it disabled.
Check that the checkbox can always be toggled.

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1786/HighFidelity-Beta-PR11002-091b666d7e492b0a57ba9e74014b5b49bc743407.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1786/HighFidelity-Beta-PR11002-091b666d7e492b0a57ba9e74014b5b49bc743407.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Run up Interface multiple times, sometimes with Settings > Audio > Enable Noise Reduction enabled and sometimes with it disabled.
Check that the checkbox can always be toggled.

**Pass**

Notes:
Ran the PR around 6 times, 3 with reduction enabled, 3 without, each restart it kept its previous state and was toggling as expected (and was working with the mic as expected)

**Pull request merged**
