### PR TITLE
Hide users.js options when logged out

### PR DESCRIPTION
**Pull request by imgntn**
This PR hides options that don't make sense when you're not logged in, and brings them back if you are.  It takes advantage of the polling that users.js already does to see who is logged in, so it might but up to 5 seconds to see state change.

To test:
1. Run users.js 
2. Logout 
3. Observe buttons disappear
4. Login 
5. Observe buttons reappear.
6. Start and stop the script in both states and see that buttons appear as expected. 
https://highfidelity.fogbugz.com/f/cases/507/Users-js-should-hide-bottom-options-for-logged-out-users

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ac946059258f7418d336d30c6ed95e5521b84b5 available at: https://gist.github.com/87fb926b3a052a79eb7eb0523731defd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47f2bd339c265611338910dd78fb46437b760115 available at: https://gist.github.com/87fb926b3a052a79eb7eb0523731defd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.dmg

**Comment by Nex-Pro** [comment]
### FAIL

**PR Build:** #8060
**Testing Architecture:** Desktop PC
**CPU:** 4.0 ghz i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None

Users JS Appears as shown in attached image.   User list on left is my android emulator showing users online. In Interface the Users list is collapsed and unusable. works fine in other PRs such as 8056 and 8057

8060issue

**Comment by imgntn** [comment]
hey @Nex-Pro i just tested this at home and it worked well.  can you please make sure you stopped all scripts and run the default scripts from this PR?  i didn't change anything about the top part that displays the actual users, so its strange that isn't appearing for you.  here are two of my screenshots, logged out and logged in.  thanks!
capture1
capture

**Comment by Nex-Pro** [comment]
ok will try again

**Comment by Nex-Pro** [comment]
@imgntn  I just double checked that I was using the scripts from 8060 and it is doing the same thing.

**Comment by Nex-Pro** [comment]
8060issue

**Comment by imgntn** [comment]
yeah i think i see what's happening --  you've got it minimized and when you open it its probably trying to show the buttons again... i'll look into it

**Comment by Nex-Pro** [comment]
@imgntn cool.

**Comment by imgntn** [comment]
cool, bug should be fixed, thanks!

**Comment by hifi-gustavo** [comment]
Build console output for commit: b97dc584ea59c8c69fb5e4d76b2d286488bbf4cb available at: https://gist.github.com/87fb926b3a052a79eb7eb0523731defd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8060.dmg

**Comment by Nex-Pro** [comment]
@imgntn  **PASS**

buttons  change correctly when going from logged in to logged out.

Note regarding appearance of users window:

Initially this started with  the users window messed up again but after uninstalling  and confirming the folder for this build was gone I re-installed this build and it looked ok.
I suspect some files persist if the previous build is not uninstalled first. 

Deleting all folders for this PR prior to a third installation made this work.

**Comment by OmegaHeron** [comment]
Seeing same failure with corrupted GUI element once I installed this as a dev-release (tag >= 5037).

users-js-oddity

users-js-oddity2

Fogbugz filed id:976

**Pull request merged**
