### PR TITLE
Hacky fix for AvatarManager. null smart_ptr deref.

### PR DESCRIPTION
**Pull request by hyperlogic**
The reason that this is a hack, is we don't know why the smart_ptr is null.
But hopefully this will get us running again in our weekly meetings.

### CODE REVIEW

**Comment by ZappoMan** [comment]
I applied this fix locally and it just moves the crash further down the line

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12df63a4738948d1b37809582330a4d3809dec8e available at: https://gist.github.com/1f78cd4b035dbcf3e4a2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b594ecb0c5fbe708638aa2f0b0e2dc8d58385524 available at: https://gist.github.com/1f78cd4b035dbcf3e4a2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ae3256f5c4bd26b60a6d0c87952e2945873e30b available at: https://gist.github.com/1f78cd4b035dbcf3e4a2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6249.dmg

**Comment by hyperlogic** [comment]
FWIW, I Haven't seen a crash on this PR for a bit.

**Pull request closed without merging**
