### PR TITLE
Fix alignment of audio devices input header

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/8071/Fix-Audio-Device-Title-Alignment

Test steps:
- Open Tablet, Audio
- Make sure "CHOOSE INPUT DEVICE" aligned with "CHOOSE OUTPUT DEVICE"

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3911/HighFidelity-Beta-PR11529-193dc83b99878a9aeea73b5688c78b0db13080bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3911/HighFidelity-Beta-PR11529-193dc83b99878a9aeea73b5688c78b0db13080bf.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open Tablet, Audio | Pass
Make sure "CHOOSE INPUT DEVICE" aligned with "CHOOSE OUTPUT DEVICE" | Pass

Looks good to me.

**Pull request merged**
