### PR TITLE
RC64 - fix lasers going to origin

### PR DESCRIPTION
**Pull request by druiz17**
RC64 - fix laser going to origin

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan in this PR. https://github.com/highfidelity/hifi/pull/12348

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7090/app_12375_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7090/HighFidelity-Beta-PR12375-6471780e210e52cac921c02cdc1bbafcde4e8575.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7090/HighFidelity-Beta-PR12375-6471780e210e52cac921c02cdc1bbafcde4e8575.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
