### PR TITLE
Prevent Infinite loop in FBXReader

### PR DESCRIPTION
**Pull request by Atlante45**
An infinite loop in the FBXReader was susceptible to lock up 1 processing thread and slow down the processing of all other tasks.

## Test Plan:
- Import [this model](https://s3.ap-northeast-2.amazonaws.com/leegab/TheCharlesClubChair/The++Charles++Club++Chair.FBX) into your sandbox.
    NOTE: Do not import it on a public domain as it will lock up a processing thread for all the people present.
- Wait for the model to load
- On the current master, this model will never load and you will have 1 item stuck processing in your stats.
- Log should contain the following line: `Ignoring loop detected in FBX connection map for`

NOTE: The bounding box of the model will be wrong, this is an unrelated issue.

[Bug](https://highfidelity.fogbugz.com/f/cases/4914)
[Bug](https://highfidelity.fogbugz.com/f/cases/4920)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/178/HighFidelity-Beta-PR10551-babae456d28b96376e4c3472c4ad7e1b0a73b8e1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/178/HighFidelity-Beta-PR10551-babae456d28b96376e4c3472c4ad7e1b0a73b8e1.dmg

**Comment by CainFoool** [comment]
Testing

**Comment by ZappoMan** [comment]
So what happens when this sort of event occurs? Does the model fail to load? Does it possibly load but appear broken? Is it undetermined what it looks like? Should we be reporting an error of some sort? Or a warning in the log?

**Comment by CainFoool** [comment]
@ZappoMan I would assume since it's a 9.3MB file which you're trying to import into the world as a model, this alone would be the reason why for the lockup. In this PR, it would load okay after some moments.

**Comment by CainFoool** [comment]
In this PR, once added to the Asset Server - appears to load okay.
3549t

**Comment by CainFoool** [comment]
# Test Passed 
In master, when you try to add it to the world it does get locked up in processing.
f9p58

In this PR, it gets added to the world successfully.
3549t

**Comment by Atlante45** [comment]
It's actually because of the connections in the FBX file. This file has really weird nodes, their IDs are string instead of numbers and there are connections unrelated to the hierarchy of nodes pointing to themselves.
So we would spin on that node forever trying to go up the chain.

Since we now ignore loops, we identify the correct hierarchy and the model should render correctly.

I don't know how that model was made but several things about it are weird. Another on is that we don't render the correct bounding box for it, which I'll file as a separate bug.

**Comment by ZappoMan** [comment]
@Atlante45 - I guess I'm saying I think we need some kind of a log or warning when we detect this. Especially since you're saying there are some problems with the model even after it loads (bounding box broken)...

**Comment by Atlante45** [comment]
@ZappoMan Fair enough, I'll add that now.

**Comment by Atlante45** [comment]
@CainFoool Slightly changed the logic, can you give it a re-test when it builds?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/181/HighFidelity-Beta-PR10551-ea870881eeb4111b2ea94a27785b36256dba2157.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/181/HighFidelity-Beta-PR10551-ea870881eeb4111b2ea94a27785b36256dba2157.dmg

**Comment by CainFoool** [comment]
@Atlante45 Testing now.

**Comment by CainFoool** [comment]
# Test Passed 

Error message appears `[05/25 21:44:14] [WARNING] [hifi.modelformat] Ignoring loop detected in FBX connection map for "/The++Charles++Club++Chair.FBX"` when the model is loaded in to the world.

**Pull request merged**
