### PR TITLE
fix for Packet read in AvatarHashMap

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8fbb64bbf11ff53ba3172e60aa47d3edd23c2a1 available at: https://gist.github.com/e762abcacfcef5e509cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5601.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5601.dmg

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
gustavo, I hate you

**Comment by sethalves** [comment]
test this please

**Comment by birarda** [comment]
test this please

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8fbb64bbf11ff53ba3172e60aa47d3edd23c2a1 available at: https://gist.github.com/e762abcacfcef5e509cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5601.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5601.dmg

**Pull request merged**
