### PR TITLE
don't bid for simulation ownership of locked entities

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR fixes a bug where an interface will constantly bid for ownerhip of a locked+spinning object.

**Test Plan**:
**(1)** Make EntityA and set its `angularDamping` property to zero.

**(2)** Give EntityA a non-zero angular-velocity (say <0, 80, 0>) and set the **locked** property to `true`.

**(3)** Logout and then back in.

**(4)** Enable this menu item:
**Developers --> Physics--> Highlight Simulation Ownership**

**(5)** Watch the spinning entities status icons...
--> on **hifi/master** there will be a cyan "up" arrow icon that shoes up a few times a second
--> on **this PR** there will NOT be any cyan "up" arrow icons on the spinning object.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12580/HighFidelity-Beta-PR13920-727bd6b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12580/HighFidelity-Beta-PR13920-727bd6b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12580/HighFidelity-Beta-Interface-PR13920-727bd6b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12580/HighFidelity-Beta-PR13920-727bd6b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12580/HighFidelity-Beta-Interface-PR13920-727bd6b.exe

**Comment by qaAdamSmith82** [comment]
Build this please

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12623/HighFidelity-Beta-PR13920-727bd6b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12623/HighFidelity-Beta-Interface-PR13920-727bd6b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12623/HighFidelity-Beta-PR13920-727bd6b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12623/HighFidelity-Beta-Interface-PR13920-727bd6b.dmg

**Comment by qaAdamSmith82** [comment]
PASS @conklin94122

**Pull request merged**
