### PR TITLE
Revert "Fix login fail twice call"

### PR DESCRIPTION
**Pull request by wayne-chen**
Reverts highfidelity/hifi#13989

### CODE REVIEW

**Comment by wayne-chen** [comment]
Needs to be reverted as per @JeffClinton since he got two `Login Failed` prints in his log.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12983/HighFidelity-Beta-PR13993-fd1e64e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12983/HighFidelity-Beta-PR13993-fd1e64e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12983/HighFidelity-Beta-Interface-PR13993-fd1e64e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12983/HighFidelity-Beta-PR13993-fd1e64e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12983/HighFidelity-Beta-Interface-PR13993-fd1e64e.exe

**Pull request merged**
