### PR TITLE
Case 21340: avatar doctor project page status

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/21340/Avatar-Packager-AvatarDoctor-Show-project-status-on-project-page
https://highfidelity.manuscript.com/f/cases/21548/Address-user-confusion-around-hosted-avatar-is-not-for-sale-by-default-text-change-on-UI-in-parent-ticket-PR

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17574/HighFidelity-Beta-PR15013-79d0a0a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17574/HighFidelity-Beta-Interface-PR15013-79d0a0a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17574/HighFidelity-Beta-PR15013-79d0a0a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17574/HighFidelity-Beta-Interface-PR15013-79d0a0a.exe

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17627/HighFidelity-Beta-PR15013-79d0a0a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17627/HighFidelity-Beta-Interface-PR15013-79d0a0a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17627/HighFidelity-Beta-PR15013-79d0a0a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17627/HighFidelity-Quest-Beta-PR15013-79d0a0a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17627/HighFidelity-Beta-PR15013-79d0a0a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17627/HighFidelity-Beta-Interface-PR15013-79d0a0a.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17903/HighFidelity-Beta-PR15013-5920010.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17903/HighFidelity-Beta-Interface-PR15013-5920010.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17903/HighFidelity-Beta-PR15013-5920010.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17903/HighFidelity-Quest-Beta-PR15013-5920010.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17903/HighFidelity-Beta-PR15013-5920010.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17903/HighFidelity-Beta-Interface-PR15013-5920010.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17908/HighFidelity-Beta-PR15013-a84a433.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17908/HighFidelity-Quest-Beta-PR15013-a84a433.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17908/HighFidelity-Beta-PR15013-a84a433.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17908/HighFidelity-Beta-Interface-PR15013-a84a433.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17908/HighFidelity-Beta-PR15013-a84a433.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17908/HighFidelity-Beta-Interface-PR15013-a84a433.exe

**Pull request merged**
