### PR TITLE
Add stopwatch example script

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8acb3f9b531dab813eff14ae99d8ecf7d9ab1d5b available at: https://gist.github.com/78063f1f82c3e436b4951afbe255d11e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9538-8acb3f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9538-8acb3f9.dmg

**Comment by huffman** [comment]
To test:

 1. Run https://raw.githubusercontent.com/huffman/hifi/8acb3f9b531dab813eff14ae99d8ecf7d9ab1d5b/unpublishedScripts/marketplace/stopwatch/spawnStopwatch.js
 1. You should see a stopwatch appear in front you.
 1. Clicking on the stopwatch should start it.
   1. The second (large) hand should move accurately (one full revolution for 1 minute)
   1. The minute (small) hand should tick forward each minute.
   1. A chime should play each minute

**Comment by huffman** [comment]
To test:

 1.  Run https://raw.githubusercontent.com/huffman/hifi/8acb3f9b531dab813eff14ae99d8ecf7d9ab1d5b/unpublishedScripts/marketplace/stopwatch/spawnStopwatch.js
 1. A stopwatch should spawn in front of you
 1. Clicking the stopwatch should start it
   1. The second (large) hand should tick forward each second, and should move a full revolution each minute
   1. A "tick" sound should play each second
   1. The minute (small) hand should tick forward each minute.
   1. A chime should play each minute
 1. Clicking the stopwatch again should reset it, stopping it and putting the hands back at 0.
 1. Clicking it again should start it again.

**Comment by nbq** [comment]
I will test this one

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Ran script provided and saw the stop watch spawn under me with me in the middle
* clicked stop watch to start it and watched it count down
* I hear the clicking noise but the hands are not moving so did not test further.

**FAIL**

**Comment by huffman** [comment]
@nbq Does it work if you restart interface after creating the stopwatch?

**Comment by nbq** [comment]
@huffman no it does not.

I have tried reloading and loading the script multiple times, restarting the Interface also.

Now when I click on it I do not even hear the sounds of it working.

**Comment by huffman** [comment]
@nbq Ok, I just tested it again. It looks like there is a bug with empty script whitelists in the domain settings not being respected. If you add `raw.githubusercontent.com` to `Entity Scripts Allowed From` in your domain settings, rerun the spawn script, then restart interface, it _should_ work. This works around a couple seemingly unrelated bugs.

**Comment by nbq** [comment]
@huffman I added it to the whitelist reran the script.

I first just heard the sounds but no arm movement. Once reloading the Interface the arms did move.

To me this is still a **FAIL** because you have to restart the interface after you spawn it for it to work properly with the arms.

**Comment by OmegaHeron** [comment]
It may be that changes introduced via #9563 will improve this.  It seems to be hitting up against the gods of random when dealing with rapid fire updates to entity items.

**Comment by huffman** [comment]
@nbq Can you retest this with dev build 5995 or later? This script doesn't introduce any c++ changes, so testing the PR build itself is unnecessary.

**Comment by nbq** [comment]
@huffman yes, I QA'd the fix for this and I can now say that in the CURRENT dev-download it passes but in the current RC (PR9600) it does NOT pass.

I will say in general this is a pass, but only for the next RC after this one. I see no reason it cannot be brought in currently though as it is just an example script.

**Comment by huffman** [comment]
@nbq Ok, that is expected. Thanks for testing!

**Pull request merged**
