### PR TITLE
(case 22163) Fix baked models unable to rebake

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.manuscript.com/f/cases/22163/Baked-Model-FSTs-cannot-be-rebaked-in-Oven-if-original-model-was-not-also-an-FST

This PR makes ModelBaker put an FST in the original output folder, to make rebaking possible for now.

### CODE REVIEW

**Comment by sabrina-shanman** [comment]
I discussed with Samuel about the details, but in a nutshell, these bugs would only show up with baking features we currently don't support in RC82/master: script baking and texture rebaking.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18776/HighFidelity-Beta-PR15404-ca15d3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18776/HighFidelity-Beta-Interface-PR15404-ca15d3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18776/HighFidelity-Beta-PR15404-ca15d3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18776/HighFidelity-Beta-Interface-PR15404-ca15d3d.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18776/HighFidelity-Beta-PR15404-ca15d3d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18776/HighFidelity-Quest-Beta-PR15404-ca15d3d.apk)

**Comment by kkurian** [comment]
[fix specs](https://trello.com/c/hYT8O5Yd/93-fix-specs)

**Pull request merged**
