### PR TITLE
Expose Avatar default pose to JavaScript

### PR DESCRIPTION
**Pull request by hyperlogic**
New JavaScript API to get the avatar's default pose.

   MyAvatar.getDefaultJointRotation(index);
   MyAvatar.getDefaultJointTranslation(index);

See `examples/tPose.js` for example usage

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 652ce5501f16699211541fe19a80572dd2f3a1c5 available at: https://gist.github.com/9d2e7c3c69abc9d72996<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6615-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6615.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 020836f536aa01260b853686bc1828cd78d26f6f available at: https://gist.github.com/9d2e7c3c69abc9d72996<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6615-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6615.dmg

**Comment by DaveDubUK** [comment]
Am very keen to check this out, but the installer will not start on my 64-bit machine (and actually crashes explorer.exe!)

I see from looking at the hifi-public folder that *some* of the PR builds have both a 32-bit and 64-bit installer - is it possible to get a 64-bit installer for this PR build?

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 020836f536aa01260b853686bc1828cd78d26f6f available at: https://gist.github.com/9d2e7c3c69abc9d72996<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6615-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6615.dmg

**Comment by imgntn** [comment]
@ZappoMan build and test script works for me

**Comment by DaveDubUK** [comment]
Thanks for putting up the 64-bit version. However, I still have the same issue with the 64-bit build. Same problem; explorer.exe hangs. 

I've tried the following:

1) Run current 64-bit release installer - installs no problem
2) Run 6615 PR build installer (both 32-bit & 64-bit versions) - hangs explorer
3) Run 6615 PR build installer (both 32-bit & 64-bit versions) as administrator - hangs explorer

Here's an image showing hung installer processes in task manager:

hifi-pr-build-6615-installer-hanging

I note both the 32-bit and 64-bit installers are only 56MB - over 100MB smaller than the release installer. Is something missing - do I need to have a C++ dev environment set up to run these PR build installers? (I have successfully installed PR builds before, but not since August)

**Comment by ZappoMan** [comment]
Needs update from master before it can be merged.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f0cdb3c02cbf44a44b51dd62055be806fc3ee8a available at: https://gist.github.com/9d2e7c3c69abc9d72996<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6615-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6615.dmg

**Comment by hyperlogic** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f0cdb3c02cbf44a44b51dd62055be806fc3ee8a available at: https://gist.github.com/9d2e7c3c69abc9d72996<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6615-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6615.dmg

**Pull request merged**
