### PR TITLE
Hitting Enter Key in Password Field To Login

### PR DESCRIPTION
**Pull request by wayne-chen**
MS [#14261](https://highfidelity.fogbugz.com/f/cases/14261/Clicking-enter-while-focus-is-in-password-field-should-attempt-login)

- adding enter/return key event to password field to allow for login

**TEST PLAN**
For signing in:

- Launch Interface
- If you are logged in, log out via `File > Logout <user>`
- Go to `File > Login/Sign up`
- Type in your username/email
- Type in password
- While still in password text box, hit `Enter`
- You should either see an error at the top of the dialog or see that the sign in was successful

For signing up:

- Launch Interface
- If you are logged in, log out via `File > Logout <user>`
- Go to `File > Login/Sign up`
- Click the `Sign Up` button
- Type in some email
- Type in some username
- Type in some password
- While still in password text box, hit `Enter`
- You should now either see an error at the top of the dialog or see that the sign up was successful

### CODE REVIEW

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11037/HighFidelity-Beta-PR13512-99a64f3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11037/HighFidelity-Beta-PR13512-99a64f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11037/HighFidelity-Beta-Interface-PR13512-99a64f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11037/HighFidelity-Beta-PR13512-99a64f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11037/HighFidelity-Beta-Interface-PR13512-99a64f3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Hitting enter logs in and creates account.

**Pull request merged**
