### PR TITLE
add operating hours to domain

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
Depends on #8107, do not QA until after that lands.

**Comment by zzmp** [comment]
#### Testing

Ensure that operating hours and utc offset is sent with the metadata and processed in the server.
You will see log messages in the domain-server indicating that they were read and sent:
- `Domain metadata descriptors set: DESCRIPTORS_JSON`: *logged if it was read*
- `Domain metadata update: UPDATE_JSON`: *logged if it was sent*

Make sure it is read on first startup, and when you change the operating hours.
You should not be able to have multiple operating hours, just on row for weekday and one for weekend.
You should not be able to delete the operating hours.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 754a3ddfa13103d6ad099fabfad96d467d4ec4c6 available at: https://gist.github.com/bd3eb48bbd6f1cf280b586f1876299ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.dmg

**Comment by zzmp** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oMc5TvYp&#x2F;16-add-hours-of-operation-to-metadata"> Add hours of operation to metadata</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 807596596f2923241f57f1349cafc7d0261aca5a available at: https://gist.github.com/bd3eb48bbd6f1cf280b586f1876299ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52170eb12e3a1bd4b12bc66b49a15043407a0a48 available at: https://gist.github.com/bd3eb48bbd6f1cf280b586f1876299ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 194a2ed2e23e211469f70f8e3dbd0cbf6bfeafd3 available at: https://gist.github.com/bd3eb48bbd6f1cf280b586f1876299ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.dmg

**Comment by zzmp** [comment]
test this please

**Comment by OmegaHeron** [comment]
QA Pass
Tested Linux Ubuntu 16.04/QT5.6.0 and Windows 10
Tests outlined pass.  Operating hours is persisted/restored

Verified by DS restarts and config file check;
`    "descriptors": {`
`        "description": "O2T Internal LAN Server",`
`        "hosts": [`
`            "OmegaHeron"`
`        ],`
`        "maturity": "adult",`
`        "tags": [`
`            "research"`
`        ],`
`        "utc_offset": "-4",`
`        "weekday_hours": [`
`            {`
`                "close": "17:00",`
`                "open": "09:00"`
`            }`
`        ],`
`        "weekend_hours": [`
`            {`
`                "close": "23:59",`
`                "open": "00:00"`
`            }`
`        ]`
`    },`

As a matter of discussion only - the current UTC offset selection is probably fine for a first cut and I'm not sure how prevalent use of this feature will even be, but, that said... there are MIT and Apache Licensed JS libs that are lightweight and capable of dealing with TZ selection much more cleanly than a you figure out offset and set method.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 52170eb12e3a1bd4b12bc66b49a15043407a0a48 available at: https://gist.github.com/bd3eb48bbd6f1cf280b586f1876299ba<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8111.dmg

**Comment by OmegaHeron** [comment]
Also confirmed that setting times to something like open at 00:00:00 close at 23:59:59 doesn't break anything.

**Pull request merged**
