### PR TITLE
Android fix bubble crash

### PR DESCRIPTION
**Pull request by gcalero**
Fix a crash that happens in android when bubble is pressed repeatedly

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7999/app_12629_PR.apk

**Comment by SamGondelman** [comment]
Do we know why this fixes it?  Is there a threading issue with editProperties?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7999/HighFidelity-Beta-PR12629-af70c0db5115a2f9ef4fe5089fd612d62967d319.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7999/HighFidelity-Beta-PR12629-af70c0db5115a2f9ef4fe5089fd612d62967d319.exe

**Comment by gcalero** [comment]
Checking ToolbarButtonProxy::editProperties I can see it's properly enqueuing the lower level "changeProperty" so they should run sequentialy, avoiding concurrency issues. 
On the other hand the backtrace had only Qt methods (from libQt5Qml.so), I mean, it's a qt internal stack. So may be there is a concurrency issue there, updating the UI or some other operation triggered by the property change.

backtrace:
#00 pc 00000000001c91b4  /data/app/io.highfidelity.hifiinterface-1/lib/arm64/libQt5Qml.so (_ZNK3QV46Object11internalGetEPNS_6StringEPb+448)
#01 pc 0000000000232b44  /data/app/io.highfidelity.hifiinterface-1/lib/arm64/libQt5Qml.so

| Do we know why this fixes it? Is there a threading issue with editProperties?

**Pull request closed without merging**
