### PR TITLE
Fix switch from Top View to My View

### PR DESCRIPTION
**Pull request by gcalero**
This PR fixes case 18057
https://highfidelity.manuscript.com/f/cases/18057/Android-Note-9-User-cannot-switch-from-Top-View-to-My-View

I could reproduce the issue in Huawei Mate 9 pro & pixel 2.

**Testing plan**
- Enter any domain and check that switching from My View <-> Top View works
- Test starting the app in both modes, My View and Top View

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13004/HighFidelity-Beta-PR13997-cb49635.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13004/HighFidelity-Beta-PR13997-cb49635.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13004/HighFidelity-Beta-Interface-PR13997-cb49635.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13004/HighFidelity-Beta-PR13997-cb49635.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13004/HighFidelity-Beta-Interface-PR13997-cb49635.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13211/HighFidelity-Beta-PR13997-cb49635.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13211/HighFidelity-Beta-PR13997-cb49635.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13211/HighFidelity-Beta-Interface-PR13997-cb49635.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13211/HighFidelity-Beta-PR13997-cb49635.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13211/HighFidelity-Beta-Interface-PR13997-cb49635.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
@conklin94122 PASS

- Moving to a domain and changing views (Top -> Front and Front ->Top) works as expected.
- Starting the view in either mode does not cause issues with switching to other view.

Additional testing:

- The view persists when the user leaves the domain and enters a new one.
- Logging in and out does not unexpectedly change the view.

**Pull request merged**
