### PR TITLE
hide progress overlays if interstitial mode

### PR DESCRIPTION
**Pull request by wayne-chen**
- Hides "LOADING CONTENT" bar in HMD/desktop mode if interstitial mode is enabled

### CODE REVIEW

**Comment by wayne-chen** [comment]
## TEST PLAN
- Launch interface
- Navigate between domains
- When looking around in HMD/desktop mode in the interstitial page, you should not see the "LOADING CONTENT" message (similar to the image below)
image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13918/HighFidelity-Beta-PR14212-3778127.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13918/HighFidelity-Beta-PR14212-3778127.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13918/HighFidelity-Beta-Interface-PR14212-3778127.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13918/HighFidelity-Beta-PR14212-3778127.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13918/HighFidelity-Beta-Interface-PR14212-3778127.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

"Loading content" overlay is always hidden, even when content is loading outside the interstitial page.

image



[hifi-log_2018-10-15_13.04.01.txt](https://github.com/highfidelity/hifi/files/2480141/hifi-log_2018-10-15_13.04.01.txt)
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2480142/hifi-log.txt)
[hifi-log_2018-10-15_12.50.21.txt](https://github.com/highfidelity/hifi/files/2480143/hifi-log_2018-10-15_12.50.21.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13927/HighFidelity-Beta-PR14212-5a9a0eb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13927/HighFidelity-Beta-PR14212-5a9a0eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13927/HighFidelity-Beta-Interface-PR14212-5a9a0eb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13927/HighFidelity-Beta-PR14212-5a9a0eb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13927/HighFidelity-Beta-Interface-PR14212-5a9a0eb.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

"Loading content" is never shown.

Huge number of errors in log files.



image

[hifi-log_2018-10-15_16.02.13_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt](https://github.com/highfidelity/hifi/files/2480730/hifi-log_2018-10-15_16.02.13_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt)
[hifi-log_2018-10-15_16.02.29_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt](https://github.com/highfidelity/hifi/files/2480731/hifi-log_2018-10-15_16.02.29_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt)
[hifi-log_2018-10-15_16.02.44_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt](https://github.com/highfidelity/hifi/files/2480732/hifi-log_2018-10-15_16.02.44_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt)
[hifi-log_2018-10-15_16.03.00_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt](https://github.com/highfidelity/hifi/files/2480733/hifi-log_2018-10-15_16.03.00_d7dde4da-cebd-4c15-bb7e-1816440d7813.txt)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13932/HighFidelity-Beta-PR14212-81e48ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13932/HighFidelity-Beta-Interface-PR14212-81e48ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13932/HighFidelity-Beta-PR14212-81e48ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13932/HighFidelity-Beta-Interface-PR14212-81e48ad.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13938/HighFidelity-Beta-PR14212-0a9d1cc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13938/HighFidelity-Beta-PR14212-0a9d1cc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13938/HighFidelity-Beta-Interface-PR14212-0a9d1cc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13938/HighFidelity-Beta-PR14212-0a9d1cc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13938/HighFidelity-Beta-Interface-PR14212-0a9d1cc.exe

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Almost a pass, but "Loading content" overlay is displayed as soon as physics is enabled, which is not the same time as the interstitial page is removed. This is usually a few seconds before the page is removed.

The following indicate to me that "physics is enabled": 
The connect noise is heard, the teleport beam becomes visible, and, if loading into the serverless tutorial, the welcome message starts playing (indicating that the zone's script is activated by the avatar's physical location)



[logs.zip](https://github.com/highfidelity/hifi/files/2483661/logs.zip)

**Comment by wayne-chen** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by wayne-chen** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13968/HighFidelity-Beta-PR14212-7e8294e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13968/HighFidelity-Beta-PR14212-7e8294e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13968/HighFidelity-Beta-Interface-PR14212-7e8294e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13968/HighFidelity-Beta-PR14212-7e8294e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13968/HighFidelity-Beta-Interface-PR14212-7e8294e.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Result is mostly unchanged; overlay is still displayed when physics is enabled, which is not necessarily the same time the interstitial page is removed.

The length of time between the overlay appearing and the page being removed seems to be somewhat shorter than before.


[logs.zip](https://github.com/highfidelity/hifi/files/2485006/logs.zip)

**Pull request closed without merging**
