### PR TITLE
case 21040: fix Interface crash on early shutdown

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/21040/Crash-Interface-crashes-on-shut-down-when-closing-during-domain-loading

This PR fixes an Interface crash when quitting application before scene has loaded.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17051/HighFidelity-Beta-PR14855-c8a0d61.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17051/HighFidelity-Beta-PR14855-c8a0d61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17051/HighFidelity-Beta-Interface-PR14855-c8a0d61.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17051/HighFidelity-Beta-PR14855-c8a0d61.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17051/HighFidelity-Beta-Interface-PR14855-c8a0d61.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by AndrewMeadows** [comment]
Jeff's new callstack is different.  It is crashing somewhere in `QtWebEngineCore` instead of in the `LogHandler` dtor.  I think we should merge this PR, file a new case for the distinct callstack, and fix that in a separate PR.

**Pull request merged**
