### PR TITLE
Ambisonic limiter

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f5d52c3d3be239680fd5d76caed0ee72ec3a3a21 available at: https://gist.github.com/0df502daa1626d81f8f7a724eb569ad1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9272-f5d52c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9272-f5d52c3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc2c2a190652680b008d982ac0fdd3e01ac71992 available at: https://gist.github.com/0df502daa1626d81f8f7a724eb569ad1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9272-fc2c2a1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9272-fc2c2a1.dmg

**Comment by kencooke** [comment]
### Test Plan
Just a quick smoke-test of Interface audio output is needed (new functionality not enabled yet).

**Comment by OmegaHeron** [comment]
Tested Windows 10

Voice pass (server loopback)
Sounds pass (windchimes etc at Sandbox)
Reverb pass (via reverb test in QA script)
Abmisonic sound play pass (using sound sample from previous ambisonic PRs)

**Pull request merged**
