### PR TITLE
don't automatically unhook overlays from hands unless they were grabbable overlays

### PR DESCRIPTION
**Pull request by sethalves**
- don't automatically unhook overlays from hands unless they were grabbable overlays

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- set tablet to not be visible to others
- make sure you can grab and move the tablet
- make sure the controllers show up in the tutorial
- make sure the controllers show up in away-mode

**Comment by Nex-Pro** [comment]
Will test this when built as per @cozza13

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ac576c9e61f2779eb7c8a38354d7b9b71c48960 available at: https://gist.github.com/d4aea8dcd771d7ef4b925aea324b0d8d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-6ac576c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-6ac576c.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19a31d76304393f5488196a3c70bf6475eaf410b available at: https://gist.github.com/d4aea8dcd771d7ef4b925aea324b0d8d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-19a31d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-19a31d7.dmg

**Comment by Nex-Pro** [comment]
### Pass ( assuming debug print removal didn't break it ) 

set tablet to not be visible to others: **SUCCESS**
make sure you can grab and move the tablet: **SUCCESS**
make sure the controllers show up in the tutorial: **SUCCESS**
make sure the controllers show up in away-mode: **SUCCESS**

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2d2c41f02876e90711e1c222044af048a5d4c84 available at: https://gist.github.com/d4aea8dcd771d7ef4b925aea324b0d8d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-a2d2c41.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9812-a2d2c41.dmg

**Pull request merged**
