### PR TITLE
fix for registration of AccountManagerAuth::Type

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 783fc692a574e36df9e57d410817363429f310b4 available at: https://gist.github.com/4e02c30677746b76f0e5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9ecf0c412bbc752ec5b434ddf49185af34618d6 available at: https://gist.github.com/0a47fea22aa2ef79482f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94f57c51309b5e132ff6d2d8f04442c699ea86ff available at: https://gist.github.com/4e02c30677746b76f0e5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by Atlante45** [comment]
Hmm I was consistently crashing until I reset all my settings. Can anyone else confirm if it happened to them too?

**Comment by ZappoMan** [comment]
This crashes on startup on Mac, but runs on windows.

**Comment by ZappoMan** [comment]
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x000000010847074a QMetaObject::cast(QObject*) const + 26
1   org.qt-project.QtCore         	0x00000001083b4dce QNonContiguousByteDeviceFactory::createShared(QIODevice*) + 30
2   org.qt-project.QtNetwork      	0x0000000104cb44e7 0x104c69000 + 308455
3   org.qt-project.QtNetwork      	0x0000000104cb2d3f 0x104c69000 + 302399
4   org.qt-project.QtNetwork      	0x0000000104caf804 0x104c69000 + 288772
5   org.qt-project.QtNetwork      	0x0000000104d32d3b 0x104c69000 + 826683
6   org.qt-project.QtCore         	0x0000000108496393 QObject::event(QEvent*) + 755
7   org.qt-project.QtWidgets      	0x0000000105f1932b QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
8   org.qt-project.QtWidgets      	0x0000000105f1c648 QApplication::notify(QObject*, QEvent*) + 8136
9   org.qt-project.QtCore         	0x000000010846ba5b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
10  libqcocoa.dylib               	0x000000010b3bbb8e 0x10b39b000 + 134030
11  libqcocoa.dylib               	0x000000010b3bb0cf 0x10b39b000 + 131279
12  io.highfidelity.Interface     	0x00000001036cfd06 RunningScriptsWidget::setRunningScripts(QStringList const&) + 3270
13  io.highfidelity.Interface     	0x00000001035429d8 Application::handleScriptEngineLoaded(QString const&) + 136
14  org.qt-project.QtCore         	0x000000010849d3c2 QMetaObject::activate(QObject*, int, int, void**) + 1986
15  io.highfidelity.Interface     	0x0000000103a07945 ScriptEngine::scriptLoaded(QString const&) + 53
16  io.highfidelity.Interface     	0x0000000103a21158 ScriptCache::scriptDownloaded() + 1592
17  org.qt-project.QtCore         	0x000000010849d3c2 QMetaObject::activate(QObject*, int, int, void**) + 1986
18  io.highfidelity.Interface     	0x0000000103865743 FileResourceRequest::doSend() + 275
19  io.highfidelity.Interface     	0x0000000103a2099b ScriptCache::getScript(QUrl const&, ScriptUser*, bool&, bool) + 1467
20  io.highfidelity.Interface     	0x0000000103a26726 ScriptEngine::loadURL(QUrl const&, bool) + 166
21  io.highfidelity.Interface     	0x0000000103523837 Application::loadScript(QString const&, bool, bool, bool, bool) + 743
22  io.highfidelity.Interface     	0x0000000103523a90 Application::loadScripts() + 272
23  io.highfidelity.Interface     	0x000000010351ebe6 Application::Application(int&, char**, QElapsedTimer&) + 16598
24  io.highfidelity.Interface     	0x00000001036241ce main + 254
25  libdyld.dylib                 	0x00007fff8f3f15c9 start + 1
```

**Comment by Atlante45** [comment]
Yup that what I had too I'm pretty sure.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ca038e3c369b44e2dafa137e6cd402b86d14107 available at: https://gist.github.com/4e02c30677746b76f0e5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by birarda** [comment]
Not getting the crash here - can you check the latest PR build?

**Comment by ZappoMan** [comment]
@birarda - I'm testing now... will let you know.

**Comment by ZappoMan** [comment]
crashes on startup... after main window appears... before anything renders

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtCore         	0x000000011022c05a QMetaObject::cast(QObject*) const + 26
1   org.qt-project.QtCore         	0x000000011016d95e QNonContiguousByteDeviceFactory::createShared(QIODevice*) + 30
2   org.qt-project.QtNetwork      	0x000000010feeda07 0x10fea3000 + 305671
3   org.qt-project.QtNetwork      	0x000000010feec26b 0x10fea3000 + 299627
4   org.qt-project.QtNetwork      	0x000000010fee8e04 0x10fea3000 + 286212
5   org.qt-project.QtCore         	0x0000000110251ba3 QObject::event(QEvent*) + 755
6   org.qt-project.QtWidgets      	0x000000010d5e7e13 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 307
7   org.qt-project.QtWidgets      	0x000000010d5eb215 QApplication::notify(QObject*, QEvent*) + 8293
8   org.qt-project.QtCore         	0x0000000110226f0c QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 956
9   libqcocoa.dylib               	0x000000011317c03e 0x11315b000 + 135230
10  libqcocoa.dylib               	0x000000011317c8b1 0x11315b000 + 137393
11  com.apple.CoreFoundation      	0x00007fff86cf9a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
12  com.apple.CoreFoundation      	0x00007fff86cebb8d __CFRunLoopDoSources0 + 269
13  com.apple.CoreFoundation      	0x00007fff86ceb1bf __CFRunLoopRun + 927
14  com.apple.CoreFoundation      	0x00007fff86ceabd8 CFRunLoopRunSpecific + 296
15  com.apple.HIToolbox           	0x00007fff89af556f RunCurrentEventLoopInMode + 235
16  com.apple.HIToolbox           	0x00007fff89af51ee ReceiveNextEventCommon + 179
17  com.apple.HIToolbox           	0x00007fff89af512b _BlockUntilNextEventMatchingListInModeWithFilter + 71
18  com.apple.AppKit              	0x00007fff8fefd8ab _DPSNextEvent + 978
19  com.apple.AppKit              	0x00007fff8fefce58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
20  com.apple.AppKit              	0x00007fff8fef2af3 -[NSApplication run] + 594
21  libqcocoa.dylib               	0x000000011317b80a 0x11315b000 + 133130
22  org.qt-project.QtCore         	0x0000000110223a2c QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 396
23  org.qt-project.QtCore         	0x00000001102267ea QCoreApplication::exec() + 346
24  io.highfidelity.Interface     	0x000000010b344ca3 main + 707
25  libdyld.dylib                 	0x00007fff8f3f15c9 start + 1

```

**Comment by ZappoMan** [comment]
another crash

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x000000010273bc60 vtable for QSGTransformNode + 16
1   org.qt-project.QtCore         	0x0000000105ad395e QNonContiguousByteDeviceFactory::createShared(QIODevice*) + 30
2   org.qt-project.QtNetwork      	0x0000000105856a07 0x10580c000 + 305671
3   org.qt-project.QtNetwork      	0x000000010585526b 0x10580c000 + 299627
4   org.qt-project.QtNetwork      	0x0000000105851e04 0x10580c000 + 286212
5   org.qt-project.QtCore         	0x0000000105bb7ba3 QObject::event(QEvent*) + 755
6   org.qt-project.QtWidgets      	0x0000000102f52e13 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 307
7   org.qt-project.QtWidgets      	0x0000000102f56215 QApplication::notify(QObject*, QEvent*) + 8293
8   org.qt-project.QtCore         	0x0000000105b8cf0c QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 956
9   libqcocoa.dylib               	0x0000000108af903e 0x108ad8000 + 135230
10  libqcocoa.dylib               	0x0000000108af98b1 0x108ad8000 + 137393
11  com.apple.CoreFoundation      	0x00007fff86cf9a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
12  com.apple.CoreFoundation      	0x00007fff86cebb8d __CFRunLoopDoSources0 + 269
13  com.apple.CoreFoundation      	0x00007fff86ceb1bf __CFRunLoopRun + 927
14  com.apple.CoreFoundation      	0x00007fff86ceabd8 CFRunLoopRunSpecific + 296
15  com.apple.HIToolbox           	0x00007fff89af556f RunCurrentEventLoopInMode + 235
16  com.apple.HIToolbox           	0x00007fff89af51ee ReceiveNextEventCommon + 179
17  com.apple.HIToolbox           	0x00007fff89af512b _BlockUntilNextEventMatchingListInModeWithFilter + 71
18  com.apple.AppKit              	0x00007fff8fefd8ab _DPSNextEvent + 978
19  com.apple.AppKit              	0x00007fff8fefce58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
20  com.apple.AppKit              	0x00007fff8fef2af3 -[NSApplication run] + 594
21  libqcocoa.dylib               	0x0000000108af880a 0x108ad8000 + 133130
22  org.qt-project.QtCore         	0x0000000105b89a2c QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 396
23  org.qt-project.QtCore         	0x0000000105b8c7ea QCoreApplication::exec() + 346
24  io.highfidelity.Interface     	0x0000000100cb0ca3 main + 707
25  libdyld.dylib                 	0x00007fff8f3f15c9 start + 1
```

**Comment by ZappoMan** [comment]
rebooted my mac, still crashes

**Comment by birarda** [comment]
That is on mac with the PR build it just posted?

**Comment by ZappoMan** [comment]
yes

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8d1bb344a4b45233747152cde8943ea94c85ec73 available at: https://gist.github.com/4e02c30677746b76f0e5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by birarda** [comment]
@ZappoMan mind giving this another test? Not sure that'll fix it but worth a try

**Comment by ZappoMan** [comment]
same crash - same stack trace

**Comment by hifi-gustavo** [comment]
Build console output for commit: 403c7caa291558d390a2c9d70d20a344359ca1fd available at: https://gist.github.com/4e02c30677746b76f0e5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5912.dmg

**Comment by ZappoMan** [comment]
what ever happened with this PR?

**Comment by birarda** [comment]
Somehow still crashes on your settings file. Let's close this for now I'll try and circle back next week or a bit later.

**Pull request closed without merging**
