### PR TITLE
Give audio menu mute checkbox its own row

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
### QA Plan

Make sure the audio menu still looks fine.
Make sure the mute button on the menu has the first row to itself.

**Comment by YuppyPlays** [comment]
Can test when built & confirmed ready :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/922/HighFidelity-Beta-PR10760-baafe1ad0935082aaecafffd8f694805b3436518.exe

**Comment by YuppyPlays** [comment]
Can test when/if ready for QA :)

**Comment by zzmp** [comment]
test this please

**Comment by zzmp** [comment]
@YuppyPlays go ahead and test the windows build.

**Comment by YuppyPlays** [comment]
@zzmp doing so with haste! :) Thank you!

Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

I can confirm the Mute microphone checkbox is on its own line as intended, checked in Tablet & Toolbar.

**Pass**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/924/HighFidelity-Beta-PR10760-baafe1ad0935082aaecafffd8f694805b3436518.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/924/HighFidelity-Beta-PR10760-baafe1ad0935082aaecafffd8f694805b3436518.exe

**Pull request merged**
