### PR TITLE
Beta Release 43 - Includes up to Developer Release 6661

### PR DESCRIPTION
**Pull request by cozza13**
- Changed the input recorder to store actions by strings 
 - Added head puck configuration 
 - FileCache refactoring and test, plus KTX unit tests 
 - Print the metaverse session ID to the debug log 
 - Make sure that there is only one connection created for web events
 - Saved recording are officially g zipped and pose are played back to the standard endpoint 
 - Add UserActivity calls for bubble usage 
 - Fix crash in EntityMotionState::handleDeactivation() 
 - Send a close event to API on shutdown 
 - Make stopwatch buttons work properly 
 - Add versioning support to the KTX cache 
 - Add startup_sent_to user activity event 
 - Fixes for some simulation ownership problems 
 - Improve positioning of assets when added / imported 
 - Update server-console to watch interface via pid rather than marker 
 - Taking a snapshot from both tablet mode and using the Ctrl-S shortcut should automatically cause snapshot.wav to play
 - Move record script files to unpublishedScripts directory
 - Fix icon for polylines in entities editor properties page 
 - Implements landscape mode for tablet as rotation instead of stretching
 - Introduce a stencil mask pass in the rendering to optimize HMD 
 - Fix generateBasisVectors() helper 
 - Optimized NVTT library with fast gamma conversion 
 - Teleport.js should still function on avatars with no feet.
 - Migrate to single QML engine 
 - Updated Windows build guide's markdown
 - Protect _text member of Text3DOverlay with mute
 - On Oculus Rift on/off, switch automatically to/from desktop mode 
 - **Added Polaroid Feature to Snapshot **
 - Added CLI to Oven tool 
 - **Mannequin Avatar**

Smoke test : http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

RC functionality test: https://docs.google.com/spreadsheets/d/1F8S8a8lyze1wEczT8hc0dmz3_7QLDiHOxntKW6g0UjY/edit#gid=1080464620

### CODE REVIEW

**Comment by kevinmthomasse** [comment]
testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/541/HighFidelity-Beta-PR10654-71bb55f6616692f2614df2d41826be6447bd68af.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/541/HighFidelity-Beta-PR10654-71bb55f6616692f2614df2d41826be6447bd68af.dmg

**Comment by claudioshg** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success, expected behavior.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |376 |199 |243
**Present Rate**: |379 |198 |243
**Present New Rate**: |348 |198 |204
**CPU Buffer Count**: |672 |892 |1278
**GPU Buffer Count**: |235 |170 |311
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |55 |73 |103
**GPU Texture Count**: |44 |51 |57
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |14858 |52360 |92463
**Triangle Rate**: |7429000 |13090000 |46231500
**API Drawcall Count**: |34 |31 |71
**Drawcall Count**: |35 |31 |76
**Drawcall Rate**: |17500 |7750 |38000
**State Changes Texture Count**:|61 |49 |76
**Pipeline Count**: |26 |24 |27
**Item Opaques**: |19 |58 |104
**Item Translucents**: |14 |6 |4
**Item Lights**: |2 |19 |13
**Timing Opaques**: |0.113 |0.214 |0.443
**Timing Translucents**: |0.041 |0.01 |0.017
**Timing Lighting**: |0.045 |0.03 |0.03
**Render Frame**: |0.589 |1.28 |1.054


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/541/HighFidelity-Beta-PR10654-71bb55f6616692f2614df2d41826be6447bd68af.exe

## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** Unable to access
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:




**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2022 |28660 |
**GPU Buffer Count**: |348 |979 |
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |199 |216 |
**GPU Texture Count**: |74 |163 |
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |41295 |1408971 |
**Triangle Rate**: |3441250 |140897100 |
**API Drawcall Count**: |41 |213 |
**Drawcall Count**: |66 |516 |
**Drawcall Rate**: |5500 |51600 |
**State Changes Texture Count**:|58 |246 |
**Pipeline Count**: |34 |38 |
**Item Opaques**: |23 |356 |
**Item Translucents**: |22 |37 |
**Item Lights**: |2 |42 |
**Timing Opaques**: |0.099 |0.907 |
**Timing Translucents**: |0.035 |0.044 |
**Timing Lighting**: |0.012 |0.014 |
**Render Frame**: |0.602 |1.93 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS/was unable to access dev-demo
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|UNTESTED
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|N/A
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|SUCCESS/tested everything but connections/handshakes
**Test 11**|Test Tablet in 2D and 3D|Please read Errors:


Errors: These errors happen on both 2D and 3D tablet.

- Go to Create > Properties : scroll does not move as intended. When I grab the scroll bar and move it up or down, the scroll bar moves the opposite way.
- Go to Help > : Clicking on an arrow, scrolls the page twice instead of once.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/567/HighFidelity-Beta-PR10654-7dfd7402857ceae1100054674c63259a12a934ad.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/567/HighFidelity-Beta-PR10654-7dfd7402857ceae1100054674c63259a12a934ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/570/HighFidelity-Beta-PR10654-4642f32fa7b5d59189c5fb3a439ef6656e2b7997.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/570/HighFidelity-Beta-PR10654-4642f32fa7b5d59189c5fb3a439ef6656e2b7997.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - Oculus CV1+Touch Controls

QA Fail.

Unable to complete tutorial.  At last step where you teleport hop to move from starting position to doorway (which completes tutorial) -- am absolutely unable to TP to target.  TP target never turns blue if aimed at target ring.  If one jumps in front of target ring you end up on roof of building.  Having done this tutorial now many dozens of times -- never seen this behavior.

Seeing same in from 6659 onwards (6659 references to PR #10553).  Am able to complete tutorial with Master 6658 and a clean install no problem.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/640/HighFidelity-Beta-PR10654-e68cf09b11320ace25d0b74af6324b3ac5b33a2d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/640/HighFidelity-Beta-PR10654-e68cf09b11320ace25d0b74af6324b3ac5b33a2d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/652/HighFidelity-Beta-PR10654-614d2f8ea1dcb801254fd66767e6a750424b5628.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/652/HighFidelity-Beta-PR10654-614d2f8ea1dcb801254fd66767e6a750424b5628.exe

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 - GTX970

Notes only - formal QA to follow;

This likely should migrate to fogbugz - it's not unique to this PR/RC, but, I managed to get all of the conditions to trigger again today and want to document it here before getting distracted in PR tests.

This is really difficult to reproduce, but, consider this;

You've launched interface, you have Oculus on head but not in down position and you have picked up your touch controls -- possibly still hanging from wrist on tethers.  Now you reach up to bring HMD down and this triggers Tutorial to think you've raised your hands above you head.  Two things can happen at this point from annoying to fatal.

Fatal = A perhaps one in a few hundred chance that you do it just before "things" seem to be ready in which case you see a "broken" scene as in just a little bit of tutorial area shows and HMD has a hourglass cursor.  Interface log will absolutely flood with message "[06/13 15:37:23] [WARNING] [hifi.plugins.display.oculus] Failed to present : Invalid ovrSession provided."

I'm including log files for a case like above as I managed to trigger it today.  I renamed log files to be in chrono order vs their normal long form name.

[Logs-Bad-Run.zip](https://github.com/highfidelity/hifi/files/1072747/Logs-Bad-Run.zip)

Annoying = Tutorial begins and has set your view orientation to something really screwy because it centered display while HMD was actually in resting location.

Suggest, strongly, that hand controllers be *ignored* until HMD is in place -- we now have the auto mode switch code in place...  like these events in log indicate;

[06/13 15:37:23] [DEBUG] [hifi.scriptengine.script] HMD mounted changed...
[06/13 15:37:23] [DEBUG] [hifi.scriptengine.script] NOW mounted...

Would it not make sense to ignore hand controller input until HMD is mounted?  Then we can have it on, raise hands, not have some weird viewpoint or have to fumble for keyboard to reset sensors -- which I don't think actually works during tutorial as it seems to ignore ALL input other than what it wants to see based on tutorial phase.

**Comment by OmegaHeron** [comment]
## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: None

Desktop Mode - 1600x900 maximized window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |11919 |30986 |255
**GPU Buffer Count**: |812 |1170 |77
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |257 |217 |50
**GPU Texture Count**: |210 |186 |41
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |237638 |748578 |9662
**Triangle Rate**: |14852375 |46786125 |483100
**API Drawcall Count**: |185 |203 |15
**Drawcall Count**: |1515 |246 |15
**Drawcall Rate**: |94687 |15375 |750
**State Changes Texture Count**:|325 |237 |34
**Pipeline Count**: |46 |35 |21
**Item Opaques**: |253 |361 |3
**Item Translucents**: |84 |20 |2
**Item Lights**: |11 |37 |0
**Timing Opaques**: |0.724 |0.98 |0.033
**Timing Translucents**: |0.129 |0.033 |0.01
**Timing Lighting**: |0.036 |0.045 |0.039
**Render Frame**: |1.353 |2.232 |0.549

HMD CV1 90 FPS all

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Ok-pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass - fully tested.
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|Not tested
**Test 10**|Test PAL functionality|Basic functions all seem well.
**Test 11**|Test Tablet in 2D and 3D|Same as ever - pass.

Additional notes;

Default avatar is showing as new intended model - may the got wood jokes begin.

HMD put on/taken off and corresponding automatic mode switch working proper for CV1

Left CV1 Touch controller should give oculus menu when pressing its lowest button just as right hand one does - see also; https://highfidelity.fogbugz.com/f/cases/4917/.  The key is - being left handed :)  It works as it should from right button -- left button should do exactly same.

**Pull request merged**
