### PR TITLE
feed display

### PR DESCRIPTION
**Pull request by howard-stearns**
Goto has a toggle to switch between place suggestions and a feed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 188e525efcdea070d2b227be4ae09abc2b918538 available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-188e525.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-188e525.dmg

**Comment by howard-stearns** [comment]
These will be saved for a later PR
- The feed cards will eventually be styled differently: smaller, less text, whitespace.
- Clicking on the fed cards will eventually bring up more info rather than going directly to the specified place as they do now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d0c5c5d19cc9febe1e456e0d306976056c47a1b available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-4d0c5c5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-4d0c5c5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c44ce0f5b59ad3f9249110f7def4fc8322a46723 available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-c44ce0f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-c44ce0f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 421707c5d84aaac954309b2945822aa51ea7042e available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-421707c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-421707c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d39446f340157e3bb4ed1b666219d3d39217c367 available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-d39446f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-d39446f.dmg

**Comment by howard-stearns** [comment]
test plan:
Bring up address bar.
- The buttons for home, back, forward, places and feed should all highlight with mouse-over or laser-over.
- The back and forward buttons should be enabled (visually and in fact) at the correct times - i.e., when the history has a place to go back to or forward to.
- The two buttons on the far right of the toolbar are radio buttons: the pressed one becomes disabled and the non-pressed one toggles. 
 - Initially, the places button is pressed. This displays the named places, showing the place name and the number of users present.
 - The feed button switches to the feed. (At this time, there is not feed data, and so the code currently provides two canned responses.) The feed objects have no title and display the date or time - e.g., how long ago. (Currently, the clicking a feed item just goes to where the action took place. Later it will bring up additional info/options.)
 - The toggling between places and feed should be remembered between uses of the address bar (but not between sessions).
 - The filtering as you type should work correctly for places and for feed. (The filtering uses other information that is not displayed, such as place description and domain tags.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a7bbbaaed84921548f4cfb8a8fbc45ca8b416ac available at: https://gist.github.com/347ddb93782a6d0e604ebfe579271e05<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-8a7bbba.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8356-8a7bbba.dmg

**Pull request merged**
