### PR TITLE
Beta Release 42 - Includes up to Developer Release 6626

### PR DESCRIPTION
**Pull request by cozza13**
- Fix collision signal emission for static objects 
 - Focus is now changed when adding a new list item in DS settings 
 - Add KTX validation routines 
 - Ensure user never loses its running scripts
 - Added pucks calibration for upper arm/shoulders 
 - Fix compressed KTX loading
 - Fix the flickering and other lighting issues related to zone entities
 - Solve Jitteriness when scrolling the content in HMD mode -> Marketplace using the scrollbar. 
 - Fixes the "Reset my settings but retain avatar info." option after a crash. 
 - Moved audio asset processing to a separate thread 
 - OpenSSL installer update 
 - Fix markdown headers 
 - Fix SendQueue not setting lastReceiverResponse when recv handshake ack 
 - Add placeholder image when previous snapshot can't be loaded 
 - Edit.js: Fix hidden dynamic property while clone-able is active 
 - Changed the DEFAULT_DISCOVERABILITY_MODE to Connections 
 - Remove extra activity logger call 
 - Don't allow sorting on non-sortable columns in PAL
 - Snapshots: Fix incorrect "for_url" share; ensure old snapshots don't get shared when they shouldn't

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/349/HighFidelity-Beta-PR10604-4e929f6d926303c9e9cb828e61c62be2606dca91.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/349/HighFidelity-Beta-PR10604-4e929f6d926303c9e9cb828e61c62be2606dca91.dmg

**Comment by OmegaHeron** [comment]
Testing in progress.

**Comment by OmegaHeron** [comment]
Any ideas were this log spam in assignment-client is coming from?  Endless repitition -- this is with default sandbox, attached to *my* HF ID and assigned a domain/place name.  Access is controlled via my group.  No agents are connected and removing scripted agent makes no difference.

`[06/02 13:14:03] [DEBUG] [hifi.networking] [732] [assignment-client] QMap()`
`[06/02 13:14:05] [DEBUG] [hifi.networking] [732] [assignment-client] Cannot create address path without a getter for position. Call AddressManager::setPositionGetter to pass a function that will return a const glm::vec3&`
`[06/02 13:14:05] [DEBUG] [hifi.networking] [732] [assignment-client] Trying to go to URL "hifi:"`
`[06/02 13:14:06] [DEBUG] [hifi.networking] [732] [assignment-client] Received an address manager API response with no location key or place key. Cannot parse.`
`[06/02 13:14:06] [DEBUG] [hifi.networking] [732] [assignment-client] QMap()`
`[06/02 13:14:08] [DEBUG] [hifi.networking] [732] [assignment-client] Cannot create address path without a getter for position. Call AddressManager::setPositionGetter to pass a function that will return a const glm::vec3&`
`[06/02 13:14:08] [DEBUG] [hifi.networking] [732] [assignment-client] Trying to go to URL "hifi:"`
`[06/02 13:14:08] [DEBUG] [hifi.networking] [732] [assignment-client] Received an address manager API response with no location key or place key. Cannot parse.`

**Comment by OmegaHeron** [comment]
Testing Windows 10

Stack (Sandbox):
Pass for Sandbox -- moving onto Interface.

Able to set/change/remove web setting user name/password.  Pass
Able to attach to HiFi Account.  Pass
Able to attach to Purchased HiFi Place Name.  Pass
Able to modify security settings (via standard perms, group, specific user, specific IP, MAC, Fingerprint):  Pass
Able to set/persist metadata (i.e.) Description section.  Pass
Groups function as intended, allow and deny types.  Pass
AC/DS stable with respect to CPU use and Memory footprint(s).  Pass
Other DS settings all apply and persist as expected.  Pass

Log spam that *seems* rather useless;
Every 10 seconds -- coming from atp:/ACAudioSearchAndInject_tutorial.js  -- This is a fairly reliable script/mechanism at this point and I'd think, certainly for "production" deploys this is no longer really necessary.

'[06/02 13:37:58] [DEBUG] [hifi.scriptengine.script] [14360] [agent] {"entities":188,"sounds":8,"playing":4,"getEntityPropertiesPerUpdate":6.88,"millisecondsPerUpdate":100.99}'

**Comment by OmegaHeron** [comment]
Windows 10

I have following setup for audio
CV1 with its mic/headphone
Logitech USB headset mic/headphone.
Bluetooth stereo headphone -- a playback device only.

My default playback (output) device in Windows is Bluetooth headset.
My default mic (input) device in Windows is Logitech device.

Why does Interface **not** select those?  It defaults on a no config present install to using Windows default device for Input but ignores default and uses Rift's output device.

This seems *wrong*.  If idea is to hold user's hand and ignore user's default device settings (partially at least) then why is it not selecting CV1 as Input and Output?  That said - I **do not** use CV1 playback - I removed ear pieces so I could use headset that's both compatible with my hearing needs AND fits fine with CV1 on.

**Comment by OmegaHeron** [comment]
## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Windows 10 - i5 6500 - gtx970 - CV1+Touch/Desktop

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes other than dev-demo being no access allowed, as usual.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested.
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass - fully tested.
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass via tutorial
**Test 9**|Bring up and edit an objects with hand controllers|Not tested
**Test 10**|Test PAL functionality|Basic tests work. (i.e. could see users, set my display name, had admin rights where I should and not where I shouldn't.)
**Test 11**|Test Tablet in 2D and 3D|Pass

Desktop mode 1600x900 maximized window.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |50 |50
**CPU Buffer Count**: |886 |31115 |270
**GPU Buffer Count**: |268 |1265 |175
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |110 |229 |61
**GPU Texture Count**: |67 |203 |57
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |61146 |782283 |42312
**Triangle Rate**: |3218210 |48892687 |2820800
**API Drawcall Count**: |61 |210 |22
**Drawcall Count**: |54 |255 |22
**Drawcall Rate**: |2842 |15937 |1466
**State Changes Texture Count**:|96 |266 |57
**Pipeline Count**: |38 |34 |25
**Item Opaques**: |39 |368 |8
**Item Translucents**: |23 |17 |3
**Item Lights**: |4 |40 |0
**Timing Opaques**: |0.416 |1.209 |0.146
**Timing Translucents**: |0.066 |0.05 |0.044
**Timing Lighting**: |0.085 |0.073 |0.047
**Render Frame**: |2.317 |3.264 |2.368

CV1 90FPS for localhost, dev-playa as usual.

**Comment by OmegaHeron** [comment]
General notes.
While in HMD bring up tablet, switch to third person mode and note what happens.  Suggest this should DISMISS tablet so its view can be properly (as proper as possible for 3rd P view + HMD + tablet -- since it's still a bit... messy to use tablet in 3rd P view).  3P view should not be considered a little used view mode -- how else will we see our AV is buckling at knees while in HMD.  :)

Create (edit.js) - Refreshing my desire/complaint going back at least 2 years that it should reliably refresh its entity list on open.  It's a lack of polish that you still can open it, be standing in a sea of objects and have an empty list then have to fumble for button to press.  

Audio device selection should either be consistent with forcing user to what HiFi thinks is right choice (i.e. prefer HMD mic AND speaker) or fully honor Window's defaults on first run with no config or, throwing out the crazy talk... *ask* user for some of these things before jumping blindly into tutorial.

**Comment by OmegaHeron** [comment]
Suggest a mapping of reset sensors command to a thumbstick button (i.e. push thumbstick down) for something like CV1+Touch controls or some method to very easily reset view (i.e. not bring up tablet, find right menu, attempt to get finger or stylus to get a hit on menu item).   It's tiresome to continually lose menus and feel your world view is not aligned with VR:RL orientations.  As you move around and there's a creep to initial point that naturally occurs when changing domains and just generally using platform - it, at least to me, begins to feel more and more disjointed which is why I'm a "reset sensors" junky.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/379/HighFidelity-Beta-PR10604-d89febac7197d7e840150bc62ef3118167981572.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/379/HighFidelity-Beta-PR10604-d89febac7197d7e840150bc62ef3118167981572.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/394/HighFidelity-Beta-PR10604-52c60b35df8d68c945f86c3d5c281b499c6e9ae6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/394/HighFidelity-Beta-PR10604-52c60b35df8d68c945f86c3d5c281b499c6e9ae6.exe

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. There was an initial framerate when I first loaded a new localhost which hit 10 which was abnormal as it normally loads and stays consistent to 60 FPS however it only lasted for a few seconds. I tried to reproduce and was unable.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |70 |70 |60
**Present Rate**: |69 |60 |60
**Present New Rate**: |70 |70 |15
**CPU Buffer Count**: |884 |656 |1138
**GPU Buffer Count**: |174 |206 |265
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |124 |73 |110
**GPU Texture Count**: |57 |54 |60
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |69644 |213687 |167344
**Triangle Rate**: |4352750 |13355437 |2173298
**API Drawcall Count**: |52 |75 |80
**Drawcall Count**: |53 |69 |84
**Drawcall Rate**: |3312 |4312 |1090
**State Changes Texture Count**:|79 |87 |82
**Pipeline Count**: |26 |33 |28
**Item Opaques**: |38 |207 |98
**Item Translucents**: |14 |32 |20
**Item Lights**: |4 |37 |15
**Timing Opaques**: |0.171 |0.445 |0.41
**Timing Translucents**: |0.026 |0.038 |0.063
**Timing Lighting**: |0.012 |0.043 |0.023
**Render Frame**: |0.568 |1.585 |1.239


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Pull request merged**
