### PR TITLE
BUGZ-374: Fix Mac getting stuck in mouse look

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20952/HighFidelity-Beta-PR16075-8097ece.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20952/HighFidelity-Beta-Interface-PR16075-8097ece.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20952/HighFidelity-Beta-PR16075-8097ece.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20952/HighFidelity-Quest-Beta-PR16075-8097ece.apk)

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20954/HighFidelity-Beta-PR16075-8097ece.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20954/HighFidelity-Quest-Beta-PR16075-8097ece.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20954/HighFidelity-Beta-PR16075-8097ece.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20954/HighFidelity-Beta-Interface-PR16075-8097ece.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20954/HighFidelity-Beta-PR16075-8097ece.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20954/HighFidelity-Beta-Interface-PR16075-8097ece.exe

**Pull request merged**
