### PR TITLE
CR for Job #20859 - Fix particle color selection

### PR DESCRIPTION
**Pull request by thoys**
Code Review for Job #20859 - Workitem available at https://www.worklist.net/20859

### CODE REVIEW

**Comment by thoys** [comment]
## Test notes:
- Open the edit.js script from https://rawgit.com/thoys/hifi/20859/examples/edit.js
- Create a new Particle effect, and change the color from the edit panel in the particle explorer tab.
- Create another Particle effect, and also change the color of this one.
- The particles should both co-exist without disappearing, and the colors shouldn't turn into black

**Comment by hifi-gustavo** [comment]
Build console output for commit: d47e8eb9991091799da66281baab2c5f300892ec available at: https://gist.github.com/32d501775ed269de0ebb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7423.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7423.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Works as said - 2 particle creates - set distinct colors, both maintain color and visibility.  Only odd thing of note is when I turned edit mode off the properties window remains open - that's unexpected.

**Comment by OmegaHeron** [comment]
Issue with edit properties window remaining open after working with a particle entity is not due to this PR - documenting now for reporting.  This PR passes QA for its intended fix :+1:

**Pull request merged**
