### PR TITLE
2017-10-23: Merge RC57 into Master

### PR DESCRIPTION
**Pull request by zfox23**
There are a few things missing from `master` that went into `RC57`.

From oldest to newest:
#11621 
#11615 
#11633 
#11629 
#11637 
#11639 
#11642 
#11651 

Please run through these test plans to QA.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4371/HighFidelity-Beta-PR11659-1f6d989044feb45a853e8496a629f95b7c0f195f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4371/HighFidelity-Beta-PR11659-1f6d989044feb45a853e8496a629f95b7c0f195f.exe

**Comment by Nex-Pro** [comment]
Testing. Win10

**Comment by Nex-Pro** [comment]
Hold awaiting update.

**Comment by Nex-Pro** [comment]
Awaiting updated test plan

**Comment by Nex-Pro** [comment]
In progress.

**Comment by Nex-Pro** [comment]
Still going ...

**Comment by Nex-Pro** [comment]
Tested on win 10 intel i7

11621 tests PASS

11615 tests PASS

11633 tests PASS woot !

11629 tests part 1 PASS see observations below.

Under the 'WEAR IT' button a link says  'What does "REZ" mean?' This seems out of context.

11637 tests PASS see observations below. 

Clicking "WEAR IT" the button swaps to blue "REZZED"
Wearable items cannot be "REZZED" only worn. I can't put my hat down to mop my brow.


11639 tests Works in general but there is an issue with non standard avatar scale. 

If the (i) is lasered while the avatar is small the tablet appears distant, small, out of reach and impossible to read. If the avatar is large the tablet appears right in your face.

Also I feel that the (i) should always be the same size as it is really a UI element. Seems odd that it can scale with changes in proximity.

11642 tests PASS

11651 tests PASS apart from: Took 16 seconds expected 4 to see 'pending' change to 'view certificate' on the beachball test.


Sorry this took so long

**Pull request merged**
