### PR TITLE
Worklist job #20672 - Create a script to record a users stats

### PR DESCRIPTION
**Pull request by thoys**
View the worklist job here: https://worklist.net/20672

Job description:
Create a script that will record an individuals stats and send the stats to a google spreadsheet. 

The information needed. username, date, time, FPS, Audio Ping, Avatar Ping, Entities avg Ping. 

The script will then send the data to a Google spreadsheet. 

The stats will only be recorded if the user is running the script. You can also set how often the stats are recorded. e.g. 30 seconds.

### CODE REVIEW

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d4e4af0a5677afa41afdabf68b78334c0804f04 available at: https://gist.github.com/a1f8e07143aefb7b87c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d4e4af0a5677afa41afdabf68b78334c0804f04 available at: https://gist.github.com/a1f8e07143aefb7b87c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.dmg

**Comment by cozza13** [comment]
I have tested and it works

**Comment by imgntn** [comment]
i tested it on mac and it seems to work, but what's the deal with the references to google spreadsheet @thoys ?? i don't see anything about this in the code or the example. also missing the ability to throttle the stats updates (it just happens once in the example).

i'm fine with not specifying a storage system, advanced users should be able to handle that themselves, same with the interval.  but it's in the job request, so if it's easy for you maybe you could throw an example in.

**Comment by cozza13** [comment]
@imgntn Here is the script that will send the spreadsheet @thoys  https://gist.githubusercontent.com/cozza13/43f576a8b9e51a038e75/raw/bb903d73484c8c5a9c28cbc93c77f120cd8833b9/mystats.js

**Comment by imgntn** [comment]
@thoys I did a pull request on your Hifi repository with some new functionality in the collectHifiStats.js script to batch updates together to make fewer network calls.

**Comment by thoys** [comment]
hi @imgntn , I did add a different test script for the high fidelity repository, but yours is great, will add it to this pr, ty!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9ed1397a63e027c59bafdc802053aea100d7986f available at: https://gist.github.com/a1f8e07143aefb7b87c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5fc053cf973227133724d175d2c54e8882ee46c7 available at: https://gist.github.com/a1f8e07143aefb7b87c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5896.dmg

**Pull request merged**
