### PR TITLE
Improve keyboard navigation in file dialog and running scripts

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by jherico** [comment]
https://app.asana.com/0/27650181942747/85549635935125

**Comment by hifi-gustavo** [comment]
Build console output for commit: 427644cb77c8d229d5aa261e543bcab42f1289e5 available at: https://gist.github.com/14af9ba61eadc749ca63<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7046.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7046.dmg

**Comment by OmegaHeron** [comment]
Tested against production build 4149 (Windows) - Am able to navigate running scripts fully with this PR with exception of being no (obvious) way to reach stop/restart script icon per script.  Tab now moves to running script list and all other fields.  Keyboard nav works from open file dialog as well.

**Comment by imgntn** [comment]
tested win10 -- works, agree with @OmegaHeron's observation that you can't restart or stop the scripts you're navigating through w/keyboard - maybe something like a right / left nav within the script list on those icons + enter to select (or some other pattern).

**Comment by imgntn** [comment]
i like the pulsing on the file browser icons too

**Pull request merged**
