### PR TITLE
Electron debug

### PR DESCRIPTION
**Pull request by MiladNazeri**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22149/HighFidelity-Beta-PR16411-a6c2d2f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22149/HighFidelity-Quest-Beta-PR16411-a6c2d2f.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22151/HighFidelity-Beta-PR16411-dadf5f9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22151/HighFidelity-Quest-Beta-PR16411-dadf5f9.apk)

**Pull request closed without merging**
