### PR TITLE
Add light icons when in edit mode

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ebf70f818aed6558eabe5111a5bbd9e668775e7c available at: https://gist.github.com/169c3d56eeae3595403b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 165199c69d5ea0a013e9c169f8a0d8041cff8a26 available at: https://gist.github.com/169c3d56eeae3595403b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3c2df5c775dfc6cc1bc4b7669917212fbb018f5 available at: https://gist.github.com/169c3d56eeae3595403b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.dmg

**Comment by huffman** [comment]
@AndrewMeadows Weird, there were no merge conflicts when I merged upstream.  Anyhow, should be fixed now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d512a67c8a91a3bfc4a40403682a801cab789968 available at: https://gist.github.com/169c3d56eeae3595403b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4435.dmg

**Pull request merged**
