### PR TITLE
Remove pending avatars data structure

### PR DESCRIPTION
**Pull request by Atlante45**
This fixes the stuck white spheres following the client to a different empty domain.

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- TBD

[ticket](https://highfidelity.fogbugz.com/f/cases/18136/stuck-white-spheres-when-changing-domains)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13865/HighFidelity-Beta-PR14207-d5dc6d6.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13865/HighFidelity-Beta-PR14207-d5dc6d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13865/HighFidelity-Beta-Interface-PR14207-d5dc6d6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13866/HighFidelity-Beta-PR14207-3bfc501.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13866/HighFidelity-Beta-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13866/HighFidelity-Beta-Interface-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13866/HighFidelity-Beta-PR14207-3bfc501.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13866/HighFidelity-Beta-Interface-PR14207-3bfc501.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13995/HighFidelity-Beta-PR14207-3bfc501.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13995/HighFidelity-Beta-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13995/HighFidelity-Beta-Interface-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13995/HighFidelity-Beta-PR14207-3bfc501.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13995/HighFidelity-Beta-Interface-PR14207-3bfc501.exe

**Comment by antoninahifi** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14142/HighFidelity-Beta-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14142/HighFidelity-Beta-Interface-PR14207-3bfc501.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14142/HighFidelity-Beta-PR14207-3bfc501.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14142/HighFidelity-Beta-Interface-PR14207-3bfc501.exe

**Comment by shanzzam** [comment]
refers to https://highfidelity.manuscript.com/f/cases/17922/Avatars-leaving-a-remnant-pose-behind-when-in-a-domain
Moved into 75 by zappoman 10/p "This should be a bug we are looking at ASAP... this should be in 75. "

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
PASS @conklin94122

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14220/HighFidelity-Beta-PR14207-3bfc501.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14220/HighFidelity-Beta-PR14207-3bfc501.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14220/HighFidelity-Beta-Interface-PR14207-3bfc501.exe

**Pull request merged**
