### PR TITLE
Tablet ui

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 645aad7bb0e14e5ab6a5509579c180ea21ff2ee2 available at: https://gist.github.com/7f9db8db2fcb542518f228c5d2463572<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9570-645aad7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9570-645aad7.dmg

**Comment by sethalves** [comment]
to test (use hmd and hand controllers):
- open tablet.  fly around with hand near tablet and make sure the stylus doesn't lag behind
- open edit and make sure you can still grab and move the tablet

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f01a7d276cdb498592e3a527375c96dc0858d47 available at: https://gist.github.com/7f9db8db2fcb542518f228c5d2463572<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9570-1f01a7d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9570-1f01a7d.dmg

**Comment by Nex-Pro** [comment]
Will test this @sethalves

**Comment by Nex-Pro** [comment]
@sethalves 

First attempt at flying resulted in having the tablet becoming 'not mine' but attached to me. I then had two tablets. I pressed the X on the one that wasn't mine and it vanished.

The tablet can get a large amount of rotational jitter in the axis perpendicular to the screen surface of the monitor after flying.

After third or fourth 'flight' I became aware that there was an object tracking me at some distance , maybe 80 feet. Michelle Leckrone was able to confirm that it was a tablet attached to me (may have been the other tablet).

After reloading scripts I had stylii but no tablet.

Crashed on second attempt to reload scripts.

In general the stylii remained in the hands whilst flying.
However if, while flying, the hands are close to, but not touching
and the stylii are close to but not touching, the tablet there is a lot of haptic
and the stylii jitter heavily fore and aft.
At times becoming momentarliy invisible.

Also note that when in desktop mode dragging the tablet is a mess.

**Comment by OmegaHeron** [comment]
I totally agree with @Nex-Pro on tablet dragging while in desktop mode - it reminds me of being in an earthquake.  The capture below is not nearly as bad as it really is due to capturing at < 60FPS to keep size to something that can be placed here.  Tablet also jitters if called up while flying - hovering shakes, moving shakes.

tabletjitter

**Comment by OmegaHeron** [comment]
Given a setup like DK2 with mouse and xbox controller connected;

Should mouse allow moving tablet while in HMD mode?
Should mouse allow closing tablet via its closure button at bottom?

If either = yes then QA fail as neither works.

**Comment by OmegaHeron** [comment]
Another area where things get, odd, with Tablet UI is editing - again, DK2 with mouse/xbox controller.  

It's difficult to move tablet with xbox controller (that's my problem, not the UI/code, but it is a problem) and impossible with mouse.

Look at the UI action to do this simple task in former way vs tablet UI way.

Old;
Click edit in hud - do edit work - dismiss edit tools by clicking in hud again.

New;
Bring up tablet, select edit, dismiss tablet, do edit work, fumble around to get tablet back, close edit tools and finally dismiss tablet.

Considering the display space tablet + edit toolbar + edit properties window takes up... things get crowded fast.  Maybe if edit.js toolbar had a closure button that would help.

**Comment by PhilipRosedale** [comment]
@OmegaHeron @Nex-Pro Couple things:  

1.  We are next going to move Edit.js into the tablet for the HMD use case, so let's not analyze the collision between tablet and Edit for that case.  

2.  In your opinion(s), should we just revert to the old HUD UI always for 2D mode?  Only show tablet for HMD?  We have an open platform here.

**Comment by OmegaHeron** [comment]
@PhilipRosedale - for desktop mode I would, at the least, prefer the option to use the classic HUD UI for it and would even go so far as to say I'd like the choice while in HMD as well.

**Comment by sethalves** [comment]
Nothing in this PR has anything to do with 2d mode.  Can I consider this a QA pass, despite the various other issues?

**Comment by sethalves** [comment]
I talked to the testers on slack -- they agree that this PR isn't worse that master and in some ways is better.  QA passing it

**Pull request merged**
