### PR TITLE
Vhacd improvements, quads in collision hulls, fix dice

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: acf30782b6e2f971d03e0606fa4a03875544e7a8 available at: https://gist.github.com/44877f4a8439a5f1b37e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4537.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4537.dmg

**Comment by PhilipRosedale** [comment]
Tested on OSX with various shapes, collisions, marketplace load, gun.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8e623ace7a4e55f809019977f820374b8e4db6d available at: https://gist.github.com/44877f4a8439a5f1b37e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4537.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4537.dmg

**Comment by murillodigital** [comment]
this is stable

**Pull request merged**
