### PR TITLE
Remove particle explorer

### PR DESCRIPTION
**Pull request by dback2**
As particle explorer was merged into the properties tab as part of https://github.com/highfidelity/hifi/pull/14172, the particle explorer code itself is no longer needed.

Addresses: https://highfidelity.manuscript.com/f/cases/19533

Test Plan:
Minimal QA necessary since this is removing code that was no longer referenced, however it would be good to do a ~5 minute or so sanity check of the Create app especially of the particle properties in the Properties tab.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14407/HighFidelity-Beta-PR14279-eb347c5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14407/HighFidelity-Beta-PR14279-eb347c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14407/HighFidelity-Beta-Interface-PR14279-eb347c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14407/HighFidelity-Beta-PR14279-eb347c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14407/HighFidelity-Beta-Interface-PR14279-eb347c5.exe

**Comment by QliCknox** [comment]
Pass @conklin94122 

Removing code did not effect particles in any obvious way

**Pull request merged**
