### PR TITLE
Beta Release 47 - Includes up to Developer Release 6825

### PR DESCRIPTION
**Pull request by cozza13**
- **Make Leap Motion a plugin**
 - [**Avatar Bookmarks now save Attachment Data and scale**](https://github.com/highfidelity/hifi/pull/10819)
 - fix avatar mixer sending empty avatar identities 
 - [**Xylophone scripts**](https://github.com/highfidelity/hifi/pull/9927)
 - Don't use blocking connections on the main thread 
 - Updated calibration UI visuals and added UserActivity events.
 - Don't use a blocking connection for a high-frequency script function 
 - Restore mutex in overlay interface 
 - Tweak the Snapshot 'Share' button to make its purpose more clear 
 - Fix ACClient on Linux 
 - Additional threaded tracing of CPU cores 
 - Allowing Vive controllers and trackers to be used in desktop mode 
 - [**God view app** ](https://github.com/highfidelity/hifi/pull/10607)
 - Fixed the keyboard not showing up for goto in HMD mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1476/HighFidelity-Beta-PR10923-e22a3c6af97eb7646f9de612d66a11866ff6a8d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1476/HighFidelity-Beta-PR10923-e22a3c6af97eb7646f9de612d66a11866ff6a8d1.exe

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-chris2.highfidelity.io 'playaPerformanceTest.js'** FAILURE - unable to connect to ```dev-chris2.highfidelity.io```
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  FAILURE, unable to find home tutorial object to run the home tutorial.  Unable to log to ```dev-chris2.highfidelity.io``` as the server was down.


**Domain** |localhost | |dev-demo
---|---|---|---
**Render Rate**: |392 | |220
**Present Rate**: |399 | |218
**Present New Rate**: |360 | |220
**CPU Buffer Count**: |1044 | |1635
**GPU Buffer Count**: |191 | |409
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |104 | |100
**GPU Texture Count**: |47 | |57
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |28496 | |146164
**Triangle Rate**: |14248000 | |36541000
**API Drawcall Count**: |46 | |91
**Drawcall Count**: |47 | |96
**Drawcall Rate**: |23500 | |24000
**State Changes Texture Count**:|69 | |87
**Pipeline Count**: |18 | |20
**Item Opaques**: |0 | |0
**Item Translucents**: |0 | |0
**Item Lights**: |0 | |0
**Timing Opaques**: |0 | |0
**Timing Translucents**: |0 | |0
**Timing Lighting**: |0 | |0
**Render Frame**: |0 | |0


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|UNABLE TO TEST - ```dev-playa``` does not have firework
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by Nex-Pro** [comment]
Giving this a workout.

**Comment by Nex-Pro** [comment]
### Beta Release 47 - Includes up to Developer Release 6825

#10923

#### Testing platform:

CPU: Intel Workstation i7 16gb ram.
GPU: Nvidia GTX1070 8gb vRam
AUDIO: USB headset
HMD: HTC Vive
Controllers: HTC Vive

Test script: https://rawgit.com/cozza13/QAtesting/master/QAofRC.js?2

#### Startup conditions:

Fresh install no copy of settings.

## FAIL

## QA Test
**QA Tester**: Piper.Peppercorn assisted by Michelle

**localhost 'createTestBlocks.js' Result**:  SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: Unable to enter
**QA Pass**: **QA Pass** Pass other than perms issue with dev-demo
**Additional Test Results + Observations**:

Bug filed for missing collision sounds on dynamic objects in tutorial area. https://highfidelity.fogbugz.com/f/cases/6090/Tutorial-content-missing-collision-sound

### Reproducible failure in tutorial. **confirmed by second user**
Grab and then drop a firework (not on the fire ) in the 'near grab' part of the tutorial.
Most often doing this will make near grabbing and lasers unreliable enough that a new user will give up in frustration.
They will be unable to grab a firework. Eventually it is possible to accidentaly grab one and continue. Observed issues with lasers acting incorrectly after dropping the firework.

###Teleport beam in tutorial laggy **confirmed by second user**

Switched to desktop had no toolbar. Right click did not invoke tablet.
Switched back to HMD and found myself in 3rd person mode.
Usual method of rolling mousewheel did not fix.

Second time tried this my viewpoint was from the hips.
**unable to go to dev-demo no perms**

Somehow snap turn got turned back on during testing. ( I always turn advanced movement on and snap turn off immediately I exit the tutorial ) Will try to get a repro.

Typed Reticle.scale in console and got back 'undefined' what changed ?

### Domain perms:
  Friends can only enter a domain if the logged in checkbox is checked. Is this correct ? if so why ?
  Friends with full perms cannot edit/create
  Perms for individuals work fine.

### Groups: 
Group perms don't seem to work.
Group ranks not working in domain settings.

**Domain** |localhost |dev-chris2.highfidelity.io |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |0
**Present Rate**: |80 |90 |0
**Present New Rate**: |90 |90 |0
**CPU Buffer Count**: |1690 |305 |312
**GPU Buffer Count**: |250 |178 |193
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |195 |56 |57
**GPU Texture Count**: |60 |49 |50
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |22464 |30505 |30482
**Triangle Rate**: |2246400 |2773181 |2771090
**API Drawcall Count**: |18 |27 |27
**Drawcall Count**: |22 |41 |40
**Drawcall Rate**: |2200 |3727 |3636
**State Changes Texture Count**:|39 |48 |47
**Pipeline Count**: |30 |31 |29
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Used localhost dev-chris2.highfidelity.io dev-demo
**Test 2**|Install a fresh copy of "Home' and do tutorial|Several issues noted. On dropping firework, before throwing on fire, lasers became inactive for more than a minute. Generally interaction with objects in the tutorial was not very smooth.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Yes ( used playa )
**Test 5**|Switch avatar and make sure it does not crash|Success used Robimo Ruby
**Test 6**|Test group functions|Problems encountered see notes.
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success. But was jerky in the tutorial area(first run)
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|Extensive testing: all looks good. Username banning and machine fingerprint banning work fine.
**Test 11**|Test Tablet in 2D and 3D|Problem with help in 2d mode persists. Only 2 of 4 screens can be viewed.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1485/HighFidelity-Beta-PR10923-ee1f6dfa4220754465891e8abe9313638177a2d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1485/HighFidelity-Beta-PR10923-ee1f6dfa4220754465891e8abe9313638177a2d3.exe

**Comment by Nex-Pro** [comment]
Will be testing this for the grab fail issue.

**Comment by OmegaHeron** [comment]
In reference to groups - those are currently working for me, but, I suspect what happened was a failure on HF's backend side - I've seen it before.  I.E. You start from a clean install - attempt to add a group then can't see its roles or you start with a populated install and groups don't work.  There seems to be a less than 100% reliable path to fetching group data/roles/membership.  Should be investigated further.

I can't reproduce grab issue described in tutorial with CV1+Touch controllers.  Maybe it's been rectified by latest build.

Attempting to connect to domain that you're not allowed access to no longer shows a warning/explanation in desktop + HUD mode.

Zone/skybox texture for my primary domain refused to display until I cleared cache which was odd since I had started with a empty cache.  Unable to reproduce issue, but, should be watched for by others (i.e. zone with a sky texture doesn't load and shows default blue horizon).

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-chris2.highfidelity.io 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** Invalid location
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: dev-demo = no access.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass
**Test 11**|Test Tablet in 2D and 3D|Pass

**Comment by Nex-Pro** [comment]
@kevinmthomasse Did you try resetting all ? It should automatically take you to the tutorial.
Also you should never leave the "Copy settings" checkbox checked when installing PR builds.

**Comment by Nex-Pro** [comment]
@OmegaHeron I think you're right on the groups thing. Did not see ranks. Grab issue was happily fixed in the new build.

**Comment by kevinmthomasse** [comment]
@Nex-Pro I always leave ```copy settings``` unchecked when installing PR builds. I did try resetting.  Same result.

**Pull request merged**
