### PR TITLE
Only dismiss letterbox when clicking on grey areas

### PR DESCRIPTION
**Pull request by zfox23**
This is actually reverting a change that was made due to [MS6718](https://highfidelity.fogbugz.com/f/cases/6718). It fixes [MS12217](https://highfidelity.fogbugz.com/f/cases/12217/Spec-Camera-OBS-Official-Guide-link-doesn-t-open) and makes the dismiss behavior of `letterboxMessage`s reasonable again.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- An HMD is required

### Tests
1. Don your HMD. Grab the Spectator Camera app from the Marketplace. Open the Spectator Camera app. Click "Learn More About Spectator".
  - Verify that you see a white popup appear. The background behind the popup is semitransparent grey.
2. Use the laser to click anywhere on the popup's text _except the link_.
  - Verify that the popup is still visible.
3. Use the laser to click the "OBS Official Overview Guide" link.
  - Verify that the guide has appeared on your desktop browser
4. Use the laser to click anywhere outside the white popup box (in the grey areas)
  - Verify that the popup is no longer visible

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8834/app_12910_PR_93cf399fd6667ea74108af842dd3b81b75d60766.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8834/HighFidelity-Beta-PR12910-93cf399fd6667ea74108af842dd3b81b75d60766.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8834/HighFidelity-Beta-Interface-PR12910-93cf399fd6667ea74108af842dd3b81b75d60766.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8834/HighFidelity-Beta-PR12910-93cf399fd6667ea74108af842dd3b81b75d60766.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8834/HighFidelity-Beta-Interface-PR12910-93cf399fd6667ea74108af842dd3b81b75d60766.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by zfox23** [comment]
@qlimnavarro - I just pushed a small commit (I had the change staged, but I forgot to push it). Please QA using the build that is currently in-progress.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8923/app_12910_PR_e348269f2ecd0846384215b4e68cc7d9951847b7.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8925/app_12910_PR_e01e7cc7bc3a814d4b11e3c7ce42f1ab33927ffa.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8925/HighFidelity-Beta-PR12910-e01e7cc7bc3a814d4b11e3c7ce42f1ab33927ffa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8925/HighFidelity-Beta-Interface-PR12910-e01e7cc7bc3a814d4b11e3c7ce42f1ab33927ffa.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Pop up and links look as expected, and disappear as intended.

**Pull request merged**
