### PR TITLE
Fix sorting of entity list not working as expected for visible/lock

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.manuscript.com/f/cases/18547/Sorting-the-Entity-List-by-icons-Lock-Visible-etc-does-not-actually-sort-the-list

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13083/HighFidelity-Beta-PR14019-0fa1465.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13083/HighFidelity-Beta-Interface-PR14019-0fa1465.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13083/HighFidelity-Beta-PR14019-0fa1465.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13083/HighFidelity-Beta-Interface-PR14019-0fa1465.exe

**Comment by huffman** [comment]
# Test Case

https://highfidelity.testrail.net/index.php?/cases/view/17767

Specifically, make sure that in a domain with many locked and unlocked entities, that they sort correctly when sorting by the locked column.

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Sorting works as intended for all sorting columns

**Pull request merged**
