### PR TITLE
7951 Reload button in Running Scripts dialog stops script

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Open running scripts dialog
2. On one of the scripts that are running, press the reload button

before the fix: 
3. Notice that the script is stopped without restarting again.

after the fix: 
3. Script should to stopped and restarted.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3807/HighFidelity-Beta-PR11503-cc8f1352da3993b81cd8b9bdbc9c052ef6a83692.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3807/HighFidelity-Beta-PR11503-cc8f1352da3993b81cd8b9bdbc9c052ef6a83692.exe

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
## PASS
 all looks good.

**Pull request merged**
