### PR TITLE
Beta Release 16 - Includes up to Developer Release 5162

### PR DESCRIPTION
**Pull request by ZappoMan**
- Don't show user’s border when hover mouse if logged out
- Improved audio pipeline: remove all hard clipping and improve audio quality.
- Prevent users window from being dragged off screen
- Snapshot takes picture of HMD window instead of preview
- Fix TypedArray byte ordering and .subarray indexing. Fixes a few small but critical bugs in the JS TypedArrays implementation: 
- Fix canRezTmp logic (incorrectly) resets valid lifetimes to the maximum value
- Fix export entities by region
- Fix model overlays not correctly scaling
- Basic hand-controller editing
- Added Mac preview image if VSync is enabled
- Add missing loading images for Asset Browser
- Various performance optimizations
- Fix rendering of overlay spheres with alpha
- Ensure newly shown windows are popped to the top of the zorder
- Fixed issues in some popup windows
- New entity collision shape options
- Support for glowing 3D line overlays
- Interface changes for new Marketplace
- Refresh feature/grab script polish
- Touchscreen camera input for Interface
- Fixes a crash that occurs when switching between several domains too fast.
- Add teleportation to the array of movement options. 
- Support alpha and color gradients in circle overlays
- New javascript for ray picking against avatars
- Various snapshot improvements
- Fix MyAvatar name and url accessors.
- Expand frame decoration when mouse is over a window in HMD mode
- Fix orientation being reset to 0,0,0,1
- Audio codecs support.
- Update max request limit and number of processing threads
- Spatialization and HRTF for local audio injectors
- Ignore Avatar feature
- Support for scale property on model overlays.
- Improved throwing with hand-controllers.
- Improved HRTF
- Update all asset server responses to be reliable
- Menu & hand controller polish
- Toolbar improvements
- Delete old Interface logs
- Fix the AudioMixer distance attenuation.
- Fix hover states for toolbar buttons
- Make search line termination a circle, like 2D UI
- Grab Script Improvements
- Fix decoration inflation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc2741950a46b46c7a9444c73ff06c60ad61805d available at: https://gist.github.com/0a2b2f161fe6190eacd29c7042b6ac42<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8260-dc27419.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8260-dc27419.dmg

**Comment by ZappoMan** [comment]
Testing script: https://rawgit.com/cozza13/QAtesting/master/dynamicrc.js

**Comment by OmegaHeron** [comment]
Windows 10 64 bit - i5 6500 CPU - GTX970 GPU

Still getting issues with intermittent audio distortions - it seems if a few packets are missed or one has a connection issue where there's a few bumps leading to reconnects then audio can enter a state where there's a pain inducing noise.  I've seen this with Windows <-> Windows for Interface/DS/AC Windows<->Linux Interface/AC and I can't sign off on this while that issue remains.  It's also been reported by at least 1 other QA tester.

**Comment by Nex-Pro** [comment]
**PR Build:** #8260
**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None



## QA Test

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**playa 'playaPerformanceTest.js' Result**: SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**:
**Additional Test Results + Observations**:

Horrendous noise whilst running tests at dev-demo and dev-playa See Omega's comments above.

I like the new arrangement of the hud buttons.

Ignore works but how to un-ignore ?

Audio falloff is good.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |2 |56
**Present Rate**: |60 |9 |60
**Present New Rate**: |60 |2 |55
**CPU Buffer Count**: |3755 |5791 |3968
**GPU Buffer Count**: |693 |842 |718
**CPU Memory Usage**: |53903360 |106479616 |79245312
**GPU Memory Usage**: |24784896 |43081728 |43581440
**CPU Texture Count**: |237 |412 |305
**GPU Texture Count**: |296 |655 |507
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |263610292 |658302608 |451560472
**GPU Texture Memory Usage**: |646463501 |1516571876 |866203337
**GPU Virtual Memory Usage**: |875642381|1745750756|1095382217
**Triangle Count**: |565113 |700143 |751295
**Triangle Rate**: |35319562 |766859 |46955937
**API Drawcall Count**: |238 |190 |259
**Drawcall Count**: |238 |191 |1175
**Drawcall Rate**: |14875 |209 |73437
**State Changes Texture Count**:|232 |221 |288
**Pipeline Count**: |29 |32 |36
**Item Opaques**: |291 |269 |264
**Item Translucents**: |14 |27 |52
**Item Lights**: |22 |29 |27
**Timing Opaques**: |1525 |5525 |2144
**Timing Translucents**: |106 |61992 |470
**Timing Lighting**: |116 |1407 |215
**Render Frame**: |2413 |170288 |3869

***dev-playa render rates higly dependent on yaw/heading***

**Comment by ZappoMan** [comment]
@OmegaHeron - do you have a solid repro case for how to cause this audio problem?

**Comment by ZappoMan** [comment]
@Nex-Pro - can you explain how/when you got this noise? what were your repro steps?

**Comment by ZappoMan** [comment]
Also @Nex-Pro - any comment on your performance in dev-playa? That's abysmal... how does the current beta perform in playa on your machine?

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: I noticed some issues with rendering lag depending on yaw in dev-playa. Everything else passed ok.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |5091 |5414 |4379
**GPU Buffer Count**: |1201 |978 |859
**CPU Memory Usage**: |81616896 |91254784 |79446016
**GPU Memory Usage**: |38412288 |31068160 |39866368
**CPU Texture Count**: |265 |349 |284
**GPU Texture Count**: |2495 |2701 |2840
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |212038556 |771722400 |339001704
**GPU Texture Memory Usage**: |813021135 |1183355840 |934488310
**GPU Virtual Memory Usage**: |1014214095|1384548800|1144428790
**Triangle Count**: |542326 |775571 |794878
**Triangle Rate**: |36155066 |48473187 |49679875
**API Drawcall Count**: |288 |286 |278
**Drawcall Count**: |421 |347 |1177
**Drawcall Rate**: |28066 |21687 |73562
**State Changes Texture Count**:|246 |338 |300
**Pipeline Count**: |37 |38 |38
**Item Opaques**: |352 |459 |293
**Item Translucents**: |46 |53 |53
**Item Lights**: |20 |43 |28
**Timing Opaques**: |1663 |2199 |1328
**Timing Translucents**: |152 |256 |255
**Timing Lighting**: |126 |186 |116
**Render Frame**: |2658 |3815 |2363

**Comment by OmegaHeron** [comment]
Windows 10 64 bit - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** FAILURE
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** FAILURE
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** 
**Additional Test Results + Observations**:

Playa performance test will pass if, and only if, I run each test at each location after restarting interface.  I.E. Launch at localhost scene - it passes.  Launch at dev-playa it passes, launch at dev-demo it passes.  If I try to do all 3 tests in one run session - depending on where I start, it may pass 1 or 2 of 3 but never 3 of 3 as it enters texture swapping mode.

**Desktop mode - 1600 x 900 maximized window - vsync disabled to get max realizable FPS**

**Domain** |localhost|dev-playa |dev-demo
---|---|---|---
**Render Rate**: |155 |131 |136
**Present Rate**: |1544 |2082 |2337
**Present New Rate**: |153 |130 |136
**CPU Buffer Count**: |5786 |5368 |4850
**GPU Buffer Count**: |1663 |1827 |1073
**CPU Memory Usage**: |103641088 |88608768 |100405248
**GPU Memory Usage**: |74465280 |64204800 |57741312
**CPU Texture Count**: |322 |379 |319
**GPU Texture Count**: |1053 |714 |800
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |120280796 |70469568 |274626248
**GPU Texture Memory Usage**: |1162421849 |2184417500 |1226991761
**GPU Virtual Memory Usage**: |1285297049|2291265500|1333839761
**Triangle Count**: |831586 |819346 |595831
**Triangle Rate**: |207896500 |117049428 |99305166
**API Drawcall Count**: |171 |240 |222
**Drawcall Count**: |172 |366 |1123
**Drawcall Rate**: |43000 |52285 |187166
**State Changes Texture Count**:|219 |371 |285
**Pipeline Count**: |28 |29 |37
**Item Opaques**: |216 |381 |225
**Item Translucents**: |20 |15 |50
**Item Lights**: |20 |20 |25
**Timing Opaques**: |2140 |3888 |3261
**Timing Translucents**: |185 |251 |404
**Timing Lighting**: |215 |341 |242
**Render Frame**: |3558 |5766 |4306

**DK2**

**Domain** |o2tech |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |67 |75
**Present Rate**: |75 |67 |75
**Present New Rate**: |75 |67 |75
**CPU Buffer Count**: |5893 |6165 |5157
**GPU Buffer Count**: |1822 |2176 |1490
**CPU Memory Usage**: |104075264 |115048448 |101593088
**GPU Memory Usage**: |75259904 |82780160 |60227584
**CPU Texture Count**: |329 |409 |331
**GPU Texture Count**: |1094 |1507 |1608
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |92253612 |118976648 |250550736
**GPU Texture Memory Usage**: |1199941479 |2364656205 |1259242876
**GPU Virtual Memory Usage**: |1612169703|2809545933|1704132604
**Triangle Count**: |1581495 |2367629 |1309263
**Triangle Rate**: |121653461 |65767472 |100712538
**API Drawcall Count**: |180 |366 |313
**Drawcall Count**: |337 |755 |2395
**Drawcall Rate**: |25923 |20972 |184230
**State Changes Texture Count**:|212 |381 |341
**Pipeline Count**: |31 |42 |41
**Item Opaques**: |212 |510 |298
**Item Translucents**: |22 |42 |54
**Item Lights**: |18 |47 |25
**Timing Opaques**: |1398 |3364 |2352
**Timing Translucents**: |166 |362 |483
**Timing Lighting**: |189 |395 |269
**Render Frame**: |2493 |5356 |4017

I wanted to do a comparison between last RC and this for Playa, but, protocol mismatch does not allow it access to dev-playa and play != dev-playa in content leading to no way to do backwards comp.

FPS at dev-playa will tank if Interface is actively swapping textures - I saw it < 10 FPS in DK2, but, you have to force interface into aggressive texture swapping.. visit localhost content, allow to fully load - rotate av 360 degrees at least twice - then visit dev-playa - do same with rotate av insuring **all** content has loaded and come to visible state - then visit dev-demo doing same thing - lastly return to dev-playa.  That pushes a GTX970 with 4G VRAM into heavy swapping mode.

Issue with audio distortion remains -  It's totally random, I heard it twice out of maybe 8+ runs mainly, again, when Interface was working very hard with swapping textures.  Maybe that's a clue - perhaps it's missing a audio packet process event leading to next packet being invalid in codec's context of next.  It does, for me, tend to recover as, I think, I'm mainly dealing with zlib compressed.  4:1 Codec may be more prone to not recovering if it loses stream integrity.

**Comment by Nex-Pro** [comment]
@ZappoMan  yep.  To repro go to dev-playa or dev-demo
that's it. To clear the sound reload all content.

The rendering performance at dev-playa is most likely lack of video ram.

**Comment by jherico** [comment]
@OmegaHeron Can you try the performance tests using this build:  https://github.com/highfidelity/hifi/pull/8187

I'm pretty sure that issue here is GPU texture memory usage.  That PR limits all textures to a max 512x512 size.  It lowers the visual quality (particularly of the skybox in Playa) a little more than would be acceptable in a production release, but if we can verify that the limiting factor is in fact texture memory, then we can focus our efforts on finding a more reasonable solution.

**Comment by OmegaHeron** [comment]
@jherico will do once I'm home - I have to admit I didn't expect to see as much issue with VRAM when I moved from a 2GB RAM GTX660M to a 4GB GTX970.  But - I will gather some data.  Likely be first thing Monday before I can report.

**Comment by ZappoMan** [comment]
I'm marking this as a QA fail for the audio problem. I will work on a fix.

**Pull request closed without merging**
