### PR TITLE
Exposing GPU & Batch running time to Engine gpu jobs

### PR DESCRIPTION
**Pull request by samcake**
- Adding the cpu elapsed time in the gpu::Query & gpu::RangeTImer . THis is the cpu time measured to perform the Batch commands from the gpu::Batch::beginQuery to the gpu::Batch::endQuery.
This timing is measured from within the specific Backend (gl).
The Batch run time is the actual time measured in the Render Thread.

- Introduce a systematic render::Job::Config exposing the needed gpuRunTime and batchRunTime. these properties are now visible from the Job relying on a GPUJobConfig.

- changed the type for the cpuRunTIme exposed from render::Job::Config in order to be more coherent with all these timing variables. They are now all double expressed in milliseconds

- Updated the renderStats..qml , GPUStats.qml and ambientOcclusionPass.qml to expose this new information

Testing plan:
Smoke test, nothing should behave or perform differently
Using the script "Developer/Utilities/Render/renderGPUStats.js" should show 2 Plots, one for gpu timing, the 2nd for Batch timing

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a5ee5d6b1ec34f5b2207413ba7d8855921bc427 available at: https://gist.github.com/ac7eb505854aac9a94480e5497301080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8548-2a5ee5d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8548-2a5ee5d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: af68a2550ec8db0f4b652d8f1db57a33aa918d0b available at: https://gist.github.com/ac7eb505854aac9a94480e5497301080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8548-af68a25.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8548-af68a25.dmg

**Comment by hevyw8** [comment]
# QA Test

## Comments:
The primary criteria passed. Both plots appear when running: _developer/utilities/render/renderStatsGPU.js_

The only behavior worth mentioning during smoke test was that asset loading seemed to stall intermittently when re-entering a domain. Sometimes I would jump in to Home and everything loaded as expected. This was with or without the script loaded. So possibly unrelated.

## Criteria:

1. Smoke test, nothing should behave or perform differently **_SEE COMMENTS_**
2. Using the script "Developer/Utilities/Render/renderGPUStats.js" should show 2 Plots, one for gpu timing, the 2nd for Batch timing **_PASS_**

### Test system:

Desktop Mode
system: win10-64
gpu: nvidia gtx1060
cpu: i5-6500 @ 3.2

**Comment by samcake** [comment]
Hi Adan,
Normally there shouldn't be any effect linked to this PR.
SInce you see somethign i d say it s worth having someone else testing to make sure before tagging it as pass.

THansk!

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. No issue of any kind during smoke test where assets loading seemed to stall intermittently when re-entering a domain.  Smooth and quick movement and loading.  Both plots appear when running: ```developer/utilities/render/renderStatsGPU.js```


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |51 |57
**Present Rate**: |60 |60 |57
**Present New Rate**: |0 |0 |0
**CPU Buffer Count**: |3792 |4197 |2218
**GPU Buffer Count**: |856 |1322 |578
**CPU Memory Usage**: |75780096 |76988416 |48742400
**GPU Memory Usage**: |21024768 |52539392 |27348992
**CPU Texture Count**: |225 |295 |258
**GPU Texture Count**: |1644 |1589 |1581
**GPU Transfer Count**: |2 |2 |2
**CPU Texture Memory Usage**: |319138324 |601405832 |184157528
**GPU Texture Memory Usage**: |621523162 |1361690408 |668949910
**GPU Virtual Memory Usage**: |747294770|1487462016|794721518
**Triangle Count**: |307722 |300248 |230329
**Triangle Rate**: |18101294 |17661647 |14395562
**API Drawcall Count**: |239 |125 |115
**Drawcall Count**: |416 |260 |115
**Drawcall Rate**: |24470 |15294 |7187
**State Changes Texture Count**:|230 |146 |124
**Pipeline Count**: |52 |33 |39
**Item Opaques**: |259 |137 |162
**Item Translucents**: |23 |20 |73
**Item Lights**: |21 |35 |34
**Timing Opaques**: |0.629 |0.469 |0.564
**Timing Translucents**: |0.032 |0.025 |0.209
**Timing Lighting**: |0.113 |0.085 |0.17
**Render Frame**: |1.868 |1.383 |2.239

**Pull request merged**
