### PR TITLE
Added HMD Avatar Alignment Type

### PR DESCRIPTION
**Pull request by hyperlogic**
This PR adds a new option to the AvatarApp.  This option can be used to change how the users HMD matches up with the avatar's head.

* **eye** - Match the user eyes with the avatar eyes.  This was the default behavior before this PR.
  However, if the avatar skull is larger then the user, it can cause the avatars body to lift off of the ground when the user looks down.
* **head** - Match the user head with the avatar head.  The new default behavior.
  This prevents the body from lifting off of the ground while wearing a large headed avatar.  But can cause an offset between the users eyes and the avatars eyes.  We believe this is a worthwhile trade off.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/20003/Looking-down-at-feet-in-VR-causes-avatar-s-center-of-gravity-to-raise-up

**Comment by hyperlogic** [comment]
QA Test Plan is attached to the above ticket.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16347/HighFidelity-Beta-PR14678-5d60698.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16347/HighFidelity-Beta-Interface-PR14678-5d60698.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16347/HighFidelity-Beta-PR14678-5d60698.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16347/HighFidelity-Beta-Interface-PR14678-5d60698.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16515/HighFidelity-Beta-PR14678-39cf50d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16515/HighFidelity-Beta-PR14678-39cf50d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16515/HighFidelity-Beta-Interface-PR14678-39cf50d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16515/HighFidelity-Beta-PR14678-39cf50d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16515/HighFidelity-Beta-Interface-PR14678-39cf50d.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16672/HighFidelity-Beta-PR14678-39cf50d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16672/HighFidelity-Beta-PR14678-39cf50d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16672/HighFidelity-Beta-Interface-PR14678-39cf50d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16672/HighFidelity-Beta-PR14678-39cf50d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16672/HighFidelity-Beta-Interface-PR14678-39cf50d.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Stopped testing, access denied to build link

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16698/HighFidelity-Beta-PR14678-96f55d2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16698/HighFidelity-Beta-PR14678-96f55d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16698/HighFidelity-Beta-Interface-PR14678-96f55d2.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Pass, reluctantly

Feedback left on https://highfidelity.manuscript.com/f/cases/20003

**Pull request merged**
