### PR TITLE
treat locked like other properties that affect simulation

### PR DESCRIPTION
**Pull request by sethalves**
- bullet actions will no longer act on locked entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- rez a box, make it dynamic
- use "create" to move the box up and down, make sure it moves smoothly.  exit from "create"
- bump into it with your avatar, watch it drift
- have someone else bump into it, watch it drift
- lock it
- bump into it with your avatar, see that it doesn't move and stops you
- have someone else bump into it, see that it stops them
- unlock it, bump it again, watch it drift

**Comment by CainFoool** [comment]
Take when ready

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/82/HighFidelity-Beta-PR10519-381de7a1e2abde0e26f63a19cc5b43b2d73e53fa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/82/HighFidelity-Beta-PR10519-381de7a1e2abde0e26f63a19cc5b43b2d73e53fa.dmg

**Comment by CainFoool** [comment]
# Test Passed

Box moved when it was dynamic and unlocked with both characters, did not move when locked.

**Comment by CainFoool** [comment]
Retesting when Ready.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/83/HighFidelity-Beta-PR10519-4142d8c6862ff06949cf2590326d8571be8493bf.exe

**Comment by sethalves** [comment]
test this please

**Comment by CainFoool** [comment]
# Test Passed

Bottom entity of the box locked:

- Unable to move it
- Was able to lift up the lid and move it and it remained attached just fine.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/84/HighFidelity-Beta-PR10519-4142d8c6862ff06949cf2590326d8571be8493bf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/84/HighFidelity-Beta-PR10519-4142d8c6862ff06949cf2590326d8571be8493bf.dmg

**Comment by Nex-Pro** [comment]
@seth Does this mean that an ent with an action such as a tractor or hinge with stop moving if locked ? If so then this isn't  a great idea.

**Comment by sethalves** [comment]
an action will stop moving a locked thing.  you can lock one entity on a hinge and leave the other one unlocked; the other one will still move.

**Comment by 1st-BrainStormer** [comment]
I could see some cases where it would be nice to keep people from deleting some things I want to keep on my domain that uses actions. I would think a dynamicly set item should remain dynamic. Perhaps a physics lock could be added rather than limiting some forms of creativity.

**Comment by sethalves** [comment]
It's possible to get this using server-side edit filters, but that's not an easy thing to set up.  Now that constraints are available, it may make sense to provide another locking level that allows location changes but nothing else.  I'll chat with other devs and see if any of them like this idea.

**Pull request merged**
