### PR TITLE
Delete web3d overlay "resolution" property JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
This property has been removed in the code.

No QA required because no executable code change.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6001/app_12094_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6001/HighFidelity-Beta-PR12094-d6a0457ee5f3c94e56fb334ced43ac5d8ef3f67d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6001/HighFidelity-Beta-PR12094-d6a0457ee5f3c94e56fb334ced43ac5d8ef3f67d.exe

**Pull request merged**
