### PR TITLE
fix new model path

### PR DESCRIPTION
**Pull request by druiz17**
fix new model path

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1) Go to the sandbox or another domain in which you can edit
2) Open Create
3) Click Model
4) New model dialog should load.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6693/app_12283_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6693/HighFidelity-Beta-PR12283-1acecfe66dff222e7d97bef2498f2418ac75ac49.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6693/HighFidelity-Beta-PR12283-1acecfe66dff222e7d97bef2498f2418ac75ac49.exe

**Comment by EthanMaasdam** [comment]
@conklin94122 - FAILED - Error message still occurs on desktop. Black screen still occurs on HMD.

**Pull request closed without merging**
