### PR TITLE
21399: Enable select tags to function properly in windowing UI

### PR DESCRIPTION
**Pull request by sachinmahapure**
- Embedded a demo script within the default script to show a button.
- Displayed a web screen containing select tag on click of the button.
- Handled the case of UI locking using custom event.
- The modal can now be closed smoothly though the drop down needs to be closed by clicking somewhere on the screen.
- For now, added a new button just for demonstrating the work for review.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2243/HighFidelity-Beta-PR11111-2373f535462c1b292d870f55f1ad406dd93b4cb1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2243/HighFidelity-Beta-PR11111-2373f535462c1b292d870f55f1ad406dd93b4cb1.exe

**Comment by themelissabrown** [comment]
@sachinmahapure can you add a test plan for this?

**Comment by sachinmahapure** [comment]
Test plan:

- Launch the interface in Desktop mode to show the HUD or the toolbar.
- Click on the “DEMO” button that will display the web screen containing select drop down (web page is designed in demo.html and demo.js is the script associated with it that renders the page as web screen).
- Attempt to change the select drop down values.
- Try to close the modal and reopen it, it works smoothly (the custom event, “openSelect” in the demo.html is handling the UI locking issue).
- This was not the case previously. The UI used to lock up and was no longer able to correctly be interacted with.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
-------- | --------
Launch the interface in Desktop mode to show the HUD or the toolbar. | Pass
Click on the “DEMO” button that will display the web screen containing select drop down (web page is designed in demo.html and demo.js is the script associated with it that renders the page as web screen). | Pass
Attempt to change the select drop down values. | Pass
Try to close the modal and reopen it, it works smoothly (the custom event, “openSelect” in the demo.html is handling the UI locking issue). | Pass

All working from here.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by misslivirose** [comment]
This doesn't seem to be a fix for the root cause of the problem, but an example of a workaround - I think that the proper solution here is to identify why the select tags require custom handling, and avoid having to implement custom behaviors in the HTML files. This could be useful to include in documentation as a stop-gap, but this shouldn't go in the system scripts as-is.

**Pull request closed without merging**
