### PR TITLE
Create APP tooltip / Adressed CR comments / Regression

### PR DESCRIPTION
**Pull request by thoys**
Manuscript ticket: https://highfidelity.manuscript.com/f/cases/19052

Addresses CR comments on https://github.com/highfidelity/hifi/pull/14229

## QA test

1. Open Create (in desktop mode)
2. Create a cube
3. Go its properties in the Create Tools Window
4. Hover over the property label of position. (A tooltip with information about the position property should appear)
5. Open Create (in HMD mode)
6. Select the cube you created on step 2.
7. Go to the properties tab
8. Hover over the label of the position property (NO tooltip should show up)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14533/HighFidelity-Beta-PR14310-92888e9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14533/HighFidelity-Beta-PR14310-92888e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14533/HighFidelity-Beta-Interface-PR14310-92888e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14533/HighFidelity-Beta-PR14310-92888e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14533/HighFidelity-Beta-Interface-PR14310-92888e9.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14876/HighFidelity-Beta-PR14310-92888e9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14876/HighFidelity-Beta-PR14310-92888e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14876/HighFidelity-Beta-Interface-PR14310-92888e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14876/HighFidelity-Beta-PR14310-92888e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14876/HighFidelity-Beta-Interface-PR14310-92888e9.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Properties tooltip appears for desktop users, but not in HMD

**Pull request merged**
