### PR TITLE
RC-58: Fix entity serialization bug due to Zone Haze group properties

### PR DESCRIPTION
**Pull request by NissimHadar**
The Packet Header has been bumped up to 79.
An issue with Haze Properties overlapping in the Zone packet has been resolved.

This should also resolve https://highfidelity.fogbugz.com/f/cases/8802 (Scene doesn't properly load)

TEST PLAN

Execute the repro case detailed in the bug 8802, it doesn't repro in this pr compare to current tip of RC-58

### CODE REVIEW

**Comment by conklin94122** [comment]
QA: Please update https://highfidelity.fogbugz.com/f/cases/8802/ when you verify as fixed.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4605/HighFidelity-Beta-PR11726-3d3c93f1a581a769001f58307e328a80d889f44f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4605/HighFidelity-Beta-PR11726-3d3c93f1a581a769001f58307e328a80d889f44f.exe

**Comment by NissimHadar** [comment]
Will do.

**Comment by Nex-Pro** [comment]
@NissimHadar do you want me to test this one ?

**Comment by NissimHadar** [comment]
Yes - to see if it solves 8802.  There is no need to test the Haze.
Thanks!!

**Comment by Nex-Pro** [comment]
T E S T I N G  Win 10

**Comment by Nex-Pro** [comment]
### Fail

Discussed issue with servers not showing up at localhost with this PR.

**Comment by samcake** [comment]
We found that the problem is not this pr (it actually is a QA pass)

**Comment by conklin94122** [comment]
Merging 11734 and this into RC58, will retest this in a resulting build.

**Comment by conklin94122** [comment]
Verified in 11715, approved, merging.

**Pull request merged**
