### PR TITLE
Remove Faceshift

### PR DESCRIPTION
**Pull request by jherico**
Faceshift no longer exists, so this PR removes support for the SDK.  Additionally, it moves the base classes for eye tracking and face tracking into a library.

## Testing

* Application behavior should be unchanged
* Verify that facial animation based on audio still functions
* ~~Verify that facial animation based on DDE still works~~ DDE doesn't work on master, never mind this
   * ~~DDE face tracking can be enabled in the Developer / Avatar / Face` Tracking menu by checking Use Camera.  However, you should ensure you can get it to work on master before trying it on this PR.~~
   * ~~Verify that face tracking muting (in the same menu) still works.  When checked, the face tracking should stop, even though `Use Camera` is still checked.~~

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e1bc0d908d63f81e852891c2efc27b1d6596fd7 available at: https://gist.github.com/5515fc3373e7e5daa5ebf6001be9c1a3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10327-5e1bc0d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10327-5e1bc0d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b43a1989f629662bb09f83b1644b7b88c543eab available at: https://gist.github.com/5515fc3373e7e5daa5ebf6001be9c1a3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10327-2b43a19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10327-2b43a19.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
### PASS

All seems good. Also eye tracking looks fine. Tested this with 'Mathew' avatar

**Pull request merged**
