### PR TITLE
Fix MS16600: Prevent duplicate Spectator Camera models after crash

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS16600](https://highfidelity.manuscript.com/f/cases/16600).

The "RC71" milestone isn't that accurate, because I'll make the fix live by publishing a marketplace app update once QA passes.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. [Download this folder](https://www.dropbox.com/sh/udlx0afoknqmd9e/AABY_M1DdaKsoLTXwiRZCmDxa?dl=0) and unzip it somewhere on your computer.
2. In Interface, run `spectatorCamera.js` from within that folder.
3. Start the SPECTATOR app, then turn on Spec Cam.
4. Force Interface to crash (developer -> crash)
5. Restart Interface. Open the SPECTATOR app.
6. Turn on Spec Cam. Verify that the old cam model disappears.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11229/HighFidelity-Beta-PR13578-b573b16.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11229/HighFidelity-Beta-PR13578-b573b16.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11229/HighFidelity-Beta-Interface-PR13578-b573b16.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11229/HighFidelity-Beta-PR13578-b573b16.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11229/HighFidelity-Beta-Interface-PR13578-b573b16.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

After triggering a crash, the spectator camera removes the old model and creates a new shell near the user, when the camera is turned on in the app.

Note: When re-activating the camera, if the top toggle is set for Camera View when the camera is turned back on, the computer viewpoint will be completely black. Switching to VR Preview and back to Camera View will restore vision.

**Pull request merged**
