### PR TITLE
terminate thread if it didn't complete during MAX_SCRIPT_QUITTING_TIME

### PR DESCRIPTION
**Pull request by sethalves**
https://github.com/highfidelity/hifi/pull/13311 for RC-68

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10427/HighFidelity-Beta-PR13327-da92ff9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10427/HighFidelity-Beta-Interface-PR13327-da92ff9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10427/HighFidelity-Beta-PR13327-da92ff9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10427/HighFidelity-Beta-Interface-PR13327-da92ff9.exe

**Comment by QliCknox** [comment]
Currently testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

No crashes encountered, interaction with the client works as expected.

**Pull request merged**
