### PR TITLE
Rename CPUID to CPUIdent to fix XCode 7.2 builds

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 470aac3acf91ff22eb9374aa9998f33b5f4213d8 available at: https://gist.github.com/5c615e1ec335a32c905ead04a9302c07<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7641.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7641.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32ccc1d68e6c1e1d45bb4e21cf2330aedff84884 available at: https://gist.github.com/5c615e1ec335a32c905ead04a9302c07<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7641.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7641.dmg

**Comment by hyperlogic** [comment]
For QA, other than a smoke test, no additional testing is required.

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Smoke test passes + compile on Linux for client and server binaries passes.

**Comment by TNS-TrueNorth** [comment]
Passes on Win10 - smoke test passes successfully.

**Pull request merged**
