### PR TITLE
Remove handControllerGrab.js, see controllerDispatcher.js instead.

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA test:
* does grabbing objects still work?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3291/HighFidelity-Beta-PR11354-745d2ff39536754c3219479efde62a1a98eebed8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3291/HighFidelity-Beta-PR11354-745d2ff39536754c3219479efde62a1a98eebed8.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Pass** Grabbing objects seemed to work normally, though I did experience an issue with the laser pointers acting strangely, but I brought this same issue up in a previous PR and it seemed it was unrelated.

**Pull request merged**
