### PR TITLE
Restoring Emote app to stable build state, adding sit and love emotes 

### PR DESCRIPTION
**Pull request by alexiamandeville**
These changes add Sit and Love emotes to the app, without any other changes to functionality within the Emote app. It restores the app to a state where it is in stable, with the two animations added.

When input is provided when sitting, the avatar's animation state gets restored. In any other emote, the avatar will slide while animating.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10907/HighFidelity-Beta-PR13472-6f6a9b2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10907/HighFidelity-Beta-PR13472-6f6a9b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10907/HighFidelity-Beta-Interface-PR13472-6f6a9b2.dmg

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10907/HighFidelity-Beta-PR13472-6f6a9b2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10907/HighFidelity-Beta-Interface-PR13472-6f6a9b2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10911/HighFidelity-Beta-PR13472-b3eec72.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10914/HighFidelity-Beta-PR13472-b3eec72.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10911/HighFidelity-Beta-PR13472-b3eec72.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10911/HighFidelity-Beta-Interface-PR13472-b3eec72.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10914/HighFidelity-Beta-PR13472-b3eec72.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10914/HighFidelity-Beta-Interface-PR13472-b3eec72.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10911/HighFidelity-Beta-PR13472-b3eec72.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10911/HighFidelity-Beta-Interface-PR13472-b3eec72.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10914/HighFidelity-Beta-PR13472-b3eec72.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10914/HighFidelity-Beta-Interface-PR13472-b3eec72.exe

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/13475

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10942/HighFidelity-Beta-PR13472-0f25ab7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10942/HighFidelity-Beta-PR13472-0f25ab7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10942/HighFidelity-Beta-Interface-PR13472-0f25ab7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10942/HighFidelity-Beta-PR13472-0f25ab7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10942/HighFidelity-Beta-Interface-PR13472-0f25ab7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Emote app works and animations work as expected.

**Pull request merged**
