### PR TITLE
More compact representation of meshes on GPU

### PR DESCRIPTION
**Pull request by Zvork**
This PR changes the format in which normal, tangents and color 3D mesh attributes are stored on the GPU to save memory and potentially slightly increase GPU vertex processing performance. Normals and tangents are now also interleaved.
This concerns only meshes imported through the FBX or OBJ format as well as there blend shapes.

# Test case
A thorough test case on mesh importing should be built, ideally, with a relevant set of assets. This is probably something that should be done with someone who masters the exporting toolchain from either Blender or Maya.
Anyway, in the mean time, the changes introduced by this PR should be totally transparent to the user and shouldn't modify any aspects of the rendering.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5770/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5770/HighFidelity-Beta-PR12033-0d34569b1a94ef05e2bc092d84fc494b5b2b1acb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5770/HighFidelity-Beta-PR12033-0d34569b1a94ef05e2bc092d84fc494b5b2b1acb.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5771/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5771/HighFidelity-Beta-PR12033-72ef716b13e8febbea1e1ddc4443684c86459558.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5771/HighFidelity-Beta-PR12033-72ef716b13e8febbea1e1ddc4443684c86459558.dmg

**Comment by Zvork** [comment]
This PR breaks ModelScriptingInterface... don't merge until I've fixed this.

**Comment by Zvork** [comment]
PR should now work with ModelScriptingInterface. Appended or transformed meshes via the scripting interface will encode the color and normal attributes in XYZ float format. We could extend the vertex attribute packing to other entities like voxel etc... in the future.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5819/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5820/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5820/HighFidelity-Beta-PR12033-1d5f65b082d00b3d2b3f2a917403b9e979b97a57.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5820/HighFidelity-Beta-PR12033-1d5f65b082d00b3d2b3f2a917403b9e979b97a57.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5965/app_12033_PR.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5988/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5988/HighFidelity-Beta-PR12033-1d5f65b082d00b3d2b3f2a917403b9e979b97a57.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5988/HighFidelity-Beta-PR12033-1d5f65b082d00b3d2b3f2a917403b9e979b97a57.dmg

**Comment by conklin94122** [comment]
@Zvork There's a merge conflict that needs to be resolved and we need a little guidance on what to test to confirm this isn't breaking existing functionality.

Can you give a few examples of existing things that would be broken, and how they'd be broken, so we can check? Also, please resolve the conflict.

I'm marking as QA Failed until we have the additional info and the conflict is resolved. If resolving the conflict won't need a new build, happy to test. Please put back to QA Ready and @ me here please.

**Comment by Zvork** [comment]
@conklin94122 I've just merged with master. As to what to test, well first of all we can inspect the lighting on various objects and note if anything seems peculiar, especially ones with bump mapping to see if the normal and tangents are ok. This could also be double checked with a graphics debugging tool such as NSight (which I have problems using on my machine) and see if the normals and tangents have valid values in the vertex buffers. Same thing should be done with objects with vertex colors.
Finally, this should also be checked on objects with blend shapes such as avatar faces. The lighting should remain correct when the face is animated when talking, for example.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6042/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6042/HighFidelity-Beta-PR12033-b296b96e5e61ec45502e0c2568260b72d919f806.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6042/HighFidelity-Beta-PR12033-b296b96e5e61ec45502e0c2568260b72d919f806.dmg

**Comment by Zvork** [comment]
Rendering is ok on my side.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6168/app_12033_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6168/HighFidelity-Beta-PR12033-5ae4b99b902bf2a66486a3e6ec5675f24e6c70e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6168/HighFidelity-Beta-PR12033-5ae4b99b902bf2a66486a3e6ec5675f24e6c70e6.exe

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing completed for PR#12033. PASSED.

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed for PR#12033. PASSED.

**Pull request merged**
