### PR TITLE
Fix bug where a pending asset request could receive a pending message after deletion

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
Asana task: https://app.asana.com/0/26224634468389/105153848426928

**Comment by huffman** [comment]
To test:

1. Add a bunch of different atp assets to a scene.
1. Test that you don't crash in the following cases:
  1. Changing domains while loading ATP assets
  1. Restarting your server while loading ATP assets

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96a35a8f43dc562fac2376b879daf92880a763a3 available at: https://gist.github.com/5b0f42e2330f662164c65c828e3e0279<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7502.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7502.dmg

**Comment by cozza13** [comment]
I tested this on my Sandbox. I followed the steps from above and did not get a crash

**Pull request merged**
