### PR TITLE
Fixed goto hmd keyboard not entering text

### PR DESCRIPTION
**Pull request by druiz17**
Fixing the issue that I introduced of HMD keyboard not entering when fixing the hmd keyboard no popping up for goto.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
-In HMD mode bring up the goto
- click on the address bar to bring up the keyboard
- make sure when clicking on the keyboard buttons. Text is entered in the address bar

**Comment by YuppyPlays** [comment]
Will test when built :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1503/HighFidelity-Beta-PR10931-89a072cfeed52dcfd22281b232aa4084a1c8cac1.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1503/HighFidelity-Beta-PR10931-89a072cfeed52dcfd22281b232aa4084a1c8cac1.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

**Pass** Stylus to virtual keyboard works normally in Goto when entering address.

**Pull request merged**
