### PR TITLE
obey QT_CMAKE_PREFIX_PATH for non DEV_BUILD on UNIX

### PR DESCRIPTION
**Pull request by AndrewMeadows**
Hack to make linux build run on current linux servers

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19553/HighFidelity-Beta-PR15593-8dcc617.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19553/HighFidelity-Beta-Interface-PR15593-8dcc617.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19553/HighFidelity-Beta-PR15593-8dcc617.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19553/HighFidelity-Beta-Interface-PR15593-8dcc617.exe

**Comment by shanzzam** [comment]
please build this

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19554/HighFidelity-Beta-PR15593-8dcc617.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19554/HighFidelity-Beta-Interface-PR15593-8dcc617.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19554/HighFidelity-Beta-PR15593-8dcc617.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19554/HighFidelity-Beta-Interface-PR15593-8dcc617.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19558/HighFidelity-Beta-PR15593-670effd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19558/HighFidelity-Beta-Interface-PR15593-670effd.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19558/HighFidelity-Beta-PR15593-670effd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19558/HighFidelity-Quest-Beta-PR15593-670effd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19558/HighFidelity-Beta-PR15593-670effd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19558/HighFidelity-Beta-Interface-PR15593-670effd.exe

**Pull request merged**
