### PR TITLE
fix math for transforming a compound collision hulls

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that was causing compound collision hulls to be slightly off from their visual models

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- visit hifi://eschatology/ and make sure your feet don't sink through the floor (compare to master)
- rez a model with visual url http://headache.hungry.com/~seth/hifi/test-hull/cube.obj and compound collision url http://headache.hungry.com/~seth/hifi/test-hull/cube-hull.obj
- stand on the cube, make sure your feet don't hover above or sink into it

**Comment by CainFoool** [comment]
Testing once built.

**Comment by sethalves** [comment]
nevermind, this isn't ready.  it works for some things, but not others.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/572/HighFidelity-Beta-PR10661-e0b4424896d9a3b865a03d5ae217335f2a1110c3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/572/HighFidelity-Beta-PR10661-e0b4424896d9a3b865a03d5ae217335f2a1110c3.dmg

**Comment by sethalves** [comment]
okay, maybe ready

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/573/HighFidelity-Beta-PR10661-320057a027f1547aa2b32e9226d25eba6a77834b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/573/HighFidelity-Beta-PR10661-320057a027f1547aa2b32e9226d25eba6a77834b.dmg

**Comment by sethalves** [comment]
I still don't have a good fix on what's wrong here.  This PR isn't the solution, though.

**Pull request closed without merging**
