### PR TITLE
Prevent deadlocks in AvatarUpdate

### PR DESCRIPTION
**Pull request by hyperlogic**
This has two parts:

1. Remove AvatarUpdate and all of it's internal locking.  This was left over from earlier avatar threading experiments, and is now unnecessary.
2. Prevent Application::idle from executing while still within Application::paintGL(), this can happen in rare cases where a Win32 dialog box is opened while inside of paintGL, apparently the nvidia driver can sometimes do this.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7cab8f63fb54a833238ad2ae43de5ddbb9b8a5c0 available at: https://gist.github.com/c17988655500a14e39d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7419.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7419.dmg

**Comment by cozza13** [comment]
I have smoke tested this and did not crash. Moved around, moved blocks, went to different locations.

**Comment by PhilipRosedale** [comment]
worked well for me.

**Comment by Nex-Pro** [comment]
Test notes ?

**Pull request merged**
