### PR TITLE
fix injector restart fail on lack of local interface

### PR DESCRIPTION
**Pull request by zzmp**
- consolidate codepaths for new/restarted injections
- allow network injection without local injection

### CODE REVIEW

**Comment by zzmp** [comment]
Fixes this bug:

Repro:
On your sandbox, run this: http://hifi-content.s3.amazonaws.com/ryan/development/ACAudioSearchAndInject_ryan.js
That script is a direct copy of the one that is in the hifi/master/script-archives folder
Make sure this is the only audio injector script being run on your server
On your sandbox create two cubes
In the first cube paste this info in the user data:
{
 "soundKey": {
  "url": "http://hifi-content.s3.amazonaws.com/DomainContent/Tutorial/Sounds/Shishi_odoshi.L.wav",
  "volume": 0.1,
  "loop": true,
  "playbackGap": 7000,
  "playbackGapRange": 700
 }
}

In the second cube paste: 
{
 "soundKey": {
  "url": "http://hifi-content.s3.amazonaws.com/DomainContent/Tutorial/Sounds/tone1.L.wav",
  "volume": 0.1,
  "loop": false,
  "playbackGap": 5000,
  "playbackGapRange": 500
 }
}

Note that the looped sound will play but the non looped one will not. 
Switch the non looped to loop. It MIGHT play once and then not continue to play randomly. 
It MIGHT not play at all
It MIGHT play once and then not repeat if you log out and then log back in. 

Expected behavior is that the non looped sound will play randomly as defined by the playbackGap and GapRange numbers in the user data.

**Comment by zzmp** [comment]
QA:

- In your sandbox, run this script: http://hifi-content.s3.amazonaws.com/ryan/development/ACAudioSearchAndInject_ryan.js
  - Make sure this is the only audio injector script run on your sever
- In your sandbox, create a cube with this userData:
```
{
"soundKey": {
"url": "http://hifi-content.s3.amazonaws.com/DomainContent/Tutorial/Sounds/tone1.L.wav",
"volume": 0.1,
"loop": false,
"playbackGap": 5000,
"playbackGapRange": 500
}
```

You should hear the sound once, and then no more. If you look at the log from your AC script, you will see that the injector failed because of something something local interface something something.

In the PR build, you should continue to hear the sound, and that error will no longer be in that log.

**Comment by hifi-gustavo** [comment]
Build console output for commit: faba165408e79dfd787e1b91bef96f77cdcd2ebf available at: https://gist.github.com/b4ef0e5dae0e491cfadacefa4c580f97<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8652-faba165.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8652-faba165.dmg

**Comment by cozza13** [comment]
Tested on sandbox and could hear the sound and it would continue

**Pull request merged**
