### PR TITLE
fix case where vegas congestion control would not re-send lost ACK

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11027/HighFidelity-Beta-PR13509-dce9cb0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11027/HighFidelity-Beta-PR13509-dce9cb0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11027/HighFidelity-Beta-Interface-PR13509-dce9cb0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11027/HighFidelity-Beta-PR13509-dce9cb0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11027/HighFidelity-Beta-Interface-PR13509-dce9cb0.exe

**Comment by birarda** [comment]
Based on the complicated test plan needed for this and the thorough testing we did for it going into RC69 I'm going to merge this without QA

**Pull request merged**
