### PR TITLE
Fix colliding fbx tex names

### PR DESCRIPTION
**Pull request by zzmp**
Fixes an issue where similarly named FBX models would reuse each others textures, because they would be cached under the texture name. Before, we only cached under the FST name, so reuse was an issue for FBX.

### CODE REVIEW

**Comment by zzmp** [comment]
@ozanserim can you make sure this fixes your issue?

**Comment by zzmp** [comment]
See: https://app.asana.com/0/74051501495175/119427448436029.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43245a76dd37cd6a586c4549d7b8ef61f443e221 available at: https://gist.github.com/fe7f8af7b7abf933932a5a1d7f5b8b6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7818.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7818.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by ozanserim** [comment]
Hi, I tested this and unfortunately, it's still incorrect. When I load multiple models with the same names, HF applies the incorrect textures. 

I'm using these as my source models: 
https://s3.amazonaws.com/hifi-public/hack/scans

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7818
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |57.99     |49.53    |59.95       
Present Rate:                     |60.00     |60.02    |60.00       
Present New Rate:                 |56.08     |49.19    |59.98      
Render Stats Num Buffers:         |5171      |4729     |3242        
Render Stats gpu::Buffer Memory:  |40.3Mb    |59.9Mb   |35.5Mb      
Render Stats Num Textures:        |302       |303      |143          
Render Stats gpu::Texture Memory: |591.1Mb   |1135.9Mb |690.6Mb     
Render Stats Triangles:           |568k      |1158k    |686k       
Render Stats Drawcalls:           |913       |449      |280         
Render Stats State Changes:	  |256       |307      |76          
Render Stats Items:               |332       |517      |728        
Render Stats Timing:              |18.8ms    |29.5ms   |17.6ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |309Mb     |309Mb    |309Mb       
GPU-Z Memory Used		  |1972Mb    |2794Mb   |2330Mb      
GPU-Z Memory Load		  |22%       |32%      |3%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results/Observations:** Successful smoke.  Received zip from from @zzmp however by the time the smoke test was done and I unzipped the folder, the models were missing.  @zzmp indicated this would be a QA fail.
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f496ea069e41821a3b76c407196ba50804eaa07 available at: https://gist.github.com/fe7f8af7b7abf933932a5a1d7f5b8b6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7818.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7818.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**PR Build:** 7818
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results/Observations:** ```aj``` model was significantly darker skin tone than the ```alan``` model.  They appeared different from each other.  Screen shots enclosed.
**Successful Logout/Crash:** Successful logout.
aj model
alan model
aj left alan right models
alan left aj right back models

**Pull request merged**
