### PR TITLE
don't send audio/avatar data for ignoree to ignored node

### PR DESCRIPTION
**Pull request by birarda**
- make ignoree invisible/silent to ignored nodes

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

You will need two Interface instances to test this change. 

While in Interface, using the ignore feature in your HUD, ignore the other avatar. 

On master, the ignored avatar would still see and hear the ignoree in their interface instance.

With this PR, the ignored avatar should not see or hear the ignoree. A restart of either Interface client should clear the ignored state and both avatars should be able to see each other again.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dadcaa99598345630acb9f12fa6ec4e60f35b390 available at: https://gist.github.com/4fee6535ddd1fad7ae74134536f4b360<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9066-dadcaa9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9066-dadcaa9.dmg

**Comment by kevinmthomasse** [comment]
testing on Mac and PC

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success.  Successfully tested with @Atlante45 as I was able to successfully ignore him however I was not able to un-ignore him however that is not a bug it is just not implemented.

**Pull request merged**
