### PR TITLE
Fixed blocks download issue with `noDownload=false` tag

### PR DESCRIPTION
**Pull request by elisa-lj11**
Test plan:

1. Download the Blocks importer app from marketplace
2. Try downloading anything; it should appear in front of you

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3392/HighFidelity-Beta-PR11390-a45cc88e555630177f3995c4dd98dd912497be45.dmg

**Comment by YuppyPlays** [comment]
Awaiting the Windows build :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3392/HighFidelity-Beta-PR11390-a45cc88e555630177f3995c4dd98dd912497be45.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Download the Blocks importer app from marketplace **Check**
Try downloading anything; it should appear in front of you **Pass, tried the "Log Cabin" - worked as expected.

Great work :)

**Pull request merged**
