### PR TITLE
keep grabbed and worn entities from spamming entity-server

### PR DESCRIPTION
**Pull request by sethalves**
- keep grabbed and worn entities from spamming entity-server

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4085/HighFidelity-Beta-PR11581-921488c0e609e789757ce970f294dc8fa72f9398.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4085/HighFidelity-Beta-PR11581-921488c0e609e789757ce970f294dc8fa72f9398.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4103/HighFidelity-Beta-PR11581-17a426590bebb4f2cd45db669f160ad92c626db6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4103/HighFidelity-Beta-PR11581-17a426590bebb4f2cd45db669f160ad92c626db6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4120/HighFidelity-Beta-PR11581-b1d976adc57d591132c799ec47f4e6600f88bd17.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4130/HighFidelity-Beta-PR11581-dabaf5ac2f47f91f8502ddd8eb0f3c2ff3a50101.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4130/HighFidelity-Beta-PR11581-dabaf5ac2f47f91f8502ddd8eb0f3c2ff3a50101.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4135/HighFidelity-Beta-PR11581-430b288a7bf1dce40f3fc2ab524ad285b0473219.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4135/HighFidelity-Beta-PR11581-430b288a7bf1dce40f3fc2ab524ad285b0473219.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4147/HighFidelity-Beta-PR11581-3aee437a6a19034079718ed4a11947aad3828fe4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4147/HighFidelity-Beta-PR11581-3aee437a6a19034079718ed4a11947aad3828fe4.exe

**Comment by sethalves** [comment]
## Test Plan
- visit domain settings page -- http://localhost:40100/settings/ or whatever
- click "show advanced", "entity-server settings", enable "Edit Logging (Terse)", save
- go someplace in the domain with a lot of open space
- create a cube, make it blue
- create a cube, make it dynamic and green
- get someone to watch you
- on both interfaces, open running-scripts window and run queryAACubeInspector.js (and then close running-scripts windows)
- arrange for someone to be "tailing" the entity-server log
- with hmd and hand-controllers, grab the blue (non-dynamic) cube
- see that the queryAACube puffs out
- see that the entity-server is not receiving constant edits (a few are expected, we don't want constant 60 Hz edits)
- when the cube touches the side of the puffed queryAACube, the cube should update and the server should get some edits
- confirm that both the grabber and the watcher are seeing the same thing
- release the cube and see that the queryAACube shrinks down to snugly fix around the cube
- do this all again with the green (dynamic) cube

**Comment by sethalves** [comment]
## Test Plan
- run the servers from this PR
- visit domain settings page -- http://localhost:40100/settings/ or whatever
- click "show advanced", "entity-server settings", enable "Edit Logging (Terse)", save
- go someplace in the domain with a lot of open space
- create a cube, make it blue
- create a cube, make it dynamic and green
- get someone to watch you (running interface from this PR)
- make sure nobody else is in the domain
- on both interfaces, open running-scripts window and run queryAACubeInspector.js (and then close running-scripts windows)
- arrange for someone to be "tailing" the entity-server log
- with hmd and hand-controllers, grab the blue (non-dynamic) cube
- see that the queryAACube puffs out
- see that the entity-server is not receiving constant edits (a few are expected, we don't want constant 60 Hz edits)
- when the cube touches the side of the puffed queryAACube, the cube should update and the server should get some edits
- confirm that both the grabber and the watcher are seeing the same thing
- release the cube and see that the queryAACube shrinks down to snugly fix around the cube
- do this all again with the green (dynamic) cube
- gently toss the green cube and see that the queryAACube updates anytime it's touched by the cube
- remember to turn off terse edit logging and stop the queryAACubeInspector scripts

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4154/HighFidelity-Beta-PR11581-d46c3bfcfbf0ad5a8cbb0ccd8adcefe9c558b268.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4154/HighFidelity-Beta-PR11581-d46c3bfcfbf0ad5a8cbb0ccd8adcefe9c558b268.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4245/HighFidelity-Beta-PR11581-ae54b0aec5c530e629ac749ce993d806ab6d45c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4245/HighFidelity-Beta-PR11581-ae54b0aec5c530e629ac749ce993d806ab6d45c4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4278/HighFidelity-Beta-PR11581-e00466c900e9ab30f98847674a8b88b4cec1f224.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4278/HighFidelity-Beta-PR11581-e00466c900e9ab30f98847674a8b88b4cec1f224.exe

**Comment by Nex-Pro** [comment]
@sethalves Do you want me to Test this ?

**Comment by sethalves** [comment]
this has been merged into rc-57, so I'll close this and wait for the rc to merge back into master.

**Pull request closed without merging**
