### PR TITLE
toolbar chicklet button state

### PR DESCRIPTION
**Pull request by howard-stearns**
The HUD/Switch/Mute/Goto/Examples/Edit buttons now have an "activated" visual that reflects their state.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
For each of the toolbar chicklet buttons (HUD, Mute, Go to, Switch, Market (was Examples)), plus the Edit button:
- Observe the visual appearance. Press the button (whether with mouse or hand controller) and compare the activated appearance. It should be different, although in some cases (Mute and Switch), the difference may be subtle.
- The visual appearance should reflect the state, even when the state is changed by means other than the button. For example, 
 - View->Overlays, 
 - Display->Desktop/OpenVR, 
 - Navigate->Show Address Bar and pressing "return" in the address bar to dismiss it
 - Clicking the "close" (x) button in the Marketplace window.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43c7fd1e27093ca5577c542919b439d14d6373cf available at: https://gist.github.com/fdae19e559f054857e57ff2461c4a4e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.dmg

**Comment by howard-stearns** [comment]
code review notes: There are three kinds of changes here:
- .svg files have changed (and their names).
- In mute.js, hmd.js, goto.js, examples.js, edit.js:
  - the .svg filenames have changed
  - buttonState is initialized rather than the lower level yOffset.
  - the connect/disconnect now properly uses a named function and an argument to disconnect. (Was always failing during reload.)
  - there is a new handler wired up to some signal, which varies with the different scripts, and which sets the buttonState.
- A change in the AdressBarDialog.qml 'shown' property is now propagated to the DialogsManagerScriptingInterface (where it used by goto.js). (This might have alternatively been done by exposing the AddressBarDialog.qml object directly to interface scripts, but the code here does seem to work reliably and shouldn't break anything else.)

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qYTy0KDQ&#x2F;43-the-switch-goto-examples-edit-buttons-do-not-have-an-on-display-that-reflects-their-toggled-state"> The Switch&#x2F;Goto&#x2F;Examples&#x2F;Edit buttons do not have an &quot;on&quot; display that reflects their toggled state.</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 02cc6cc567150909587d9f09c39882b354f5c4a3 available at: https://gist.github.com/fdae19e559f054857e57ff2461c4a4e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by howard-stearns** [comment]
additional test plan:
- The toolbar buttons should respond to mouse-over or hand-controller-laser-over.
- On action (click or full trigger), it should go to the other unhovered state. (To see the hover in the new state, you need to move the mouse/laser away and back again.)

additional code-review notes:
- ToolbarButton.qml tracks hover state and uses it in the yOffset calculation along with buttonState.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 02cc6cc567150909587d9f09c39882b354f5c4a3 available at: https://gist.github.com/fdae19e559f054857e57ff2461c4a4e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ad9cfde99c3a882537f3d39c4f1821939fde12f available at: https://gist.github.com/fdae19e559f054857e57ff2461c4a4e5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8178.dmg

**Comment by SamGondelman** [comment]
QA Pass

Button state is correct.  Tested with mouse and hand controllers.

No error messages on script reload, although there is a lot of seemingly unnecessary stuff that is printed (Completing route, Creating new Route builder proxy, Event bridge, Setting event bridge, Url changed to about:blank) and one thing that should definitely be fixed (OVERLAY Unhandled image property showButtonDown), but that all happens in master too.

**Pull request merged**
