### PR TITLE
Bug fix for unexpected avatar knee shifts for users wearing Vive Trackers.

### PR DESCRIPTION
**Pull request by hyperlogic**
When computing the orientation of the knees we orient the knees such that they are half way between the hips forward orientation and the foot forward orientation.  We use a pole vector constraint to enforce this orientation.  We also do smoothing on these pole vectors to smooth out discontinuities.  However, if we perform this smoothing in the avatar coordinate space, which is constantly shifting as the head turns/moves, it can lead to unexpected shifting of the knees.  We fix this issue in this PR by performing the smoothing in sensor space rather then avatar space.  This results in much more stable knee orientations.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/15755/Performers-knees-look-awkward-when-turning

**Comment by hyperlogic** [comment]
QA Test plan:
  * With a Vive HMD, wear three pucks one on each foot and one on your hips.
  * Open Settings > Controllers...  and Select hips + feet and calibrate.
  * While standing with your feet planted, turn your head 90 degrees or more from side to side

Expected result:
   * your knees and feet should remain stable and appear planted on the ground.

Current result:
  * The knees can shift awkwardly, as shown by this video:  https://youtu.be/Ik69oPXhQM0?t=39s

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11054/HighFidelity-Beta-PR13519-fff4348.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11054/HighFidelity-Beta-PR13519-fff4348.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11054/HighFidelity-Beta-Interface-PR13519-fff4348.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASSED. Verified that knees and feet remain stable and planted on the ground while torso and head is moving.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11067/HighFidelity-Beta-PR13519-3a88582.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11067/HighFidelity-Beta-Interface-PR13519-3a88582.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11067/HighFidelity-Beta-PR13519-3a88582.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11067/HighFidelity-Beta-Interface-PR13519-3a88582.exe

**Pull request merged**
