### PR TITLE
Move Wallet Security tab to new dialog; fixup Login dialog

### PR DESCRIPTION
**Pull request by zfox23**
https://highfidelity.fogbugz.com/f/cases/18279/

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
- Verify that the "Keep me logged in" checkbox in "File -> Log In" behaves as expected.
- Verify that the "Keep me logged in" checkbox in "Settings -> Security..." properly mirrors the value in the Login dialog
- Verify that there is no longer a "Security" tab in the Wallet
- Click around in the Wallet and verify that all functions perform as designed there
- Change your Security Image in "Settings -> Security..." and verify that the new Security Image shows up in your Wallet.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14560/HighFidelity-Beta-PR14317-162a08b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14560/HighFidelity-Beta-Interface-PR14317-162a08b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14560/HighFidelity-Beta-PR14317-162a08b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14560/HighFidelity-Beta-Interface-PR14317-162a08b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14593/HighFidelity-Beta-PR14317-0a15e94.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14593/HighFidelity-Beta-PR14317-0a15e94.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14593/HighFidelity-Beta-Interface-PR14317-0a15e94.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14593/HighFidelity-Beta-PR14317-0a15e94.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14593/HighFidelity-Beta-Interface-PR14317-0a15e94.exe

**Comment by rickcarr044** [comment]
Currently testing PR14317

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14628/HighFidelity-Beta-PR14317-917fc4a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14629/HighFidelity-Beta-PR14317-0a15e94.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14631/HighFidelity-Beta-PR14317-917fc4a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14631/HighFidelity-Beta-PR14317-917fc4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14631/HighFidelity-Beta-Interface-PR14317-917fc4a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14631/HighFidelity-Beta-PR14317-917fc4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14631/HighFidelity-Beta-Interface-PR14317-917fc4a.exe

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14665/HighFidelity-Beta-PR14317-917fc4a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14665/HighFidelity-Beta-PR14317-917fc4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14665/HighFidelity-Beta-Interface-PR14317-917fc4a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14665/HighFidelity-Beta-PR14317-917fc4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14665/HighFidelity-Beta-Interface-PR14317-917fc4a.exe

**Pull request merged**
