### PR TITLE
reset wallet

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2903/HighFidelity-Beta-PR11273-b8da08ca42657427d856483c8cca1c42bf877fee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2903/HighFidelity-Beta-PR11273-b8da08ca42657427d856483c8cca1c42bf877fee.exe

**Comment by zfox23** [comment]
[Commerce Testing: Reset Wallet](https://trello.com/c/73C8cSrV/362-commerce-testing-reset-wallet)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2928/HighFidelity-Beta-PR11273-962d1fc81dc991d5eb486d13c5654418ebfff2c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2928/HighFidelity-Beta-PR11273-962d1fc81dc991d5eb486d13c5654418ebfff2c7.exe

**Pull request merged**
