### PR TITLE
AnimInverseKinematics: fix for extra twist in lowerSpine joints.

### PR DESCRIPTION
**Pull request by hyperlogic**
* When computing tipPosition, for the next iteration of the CCD,
  use the leverArm before it's projected onto the lowerSpine twist axis.
* fix for acos() that was going outside of valid domain. (-1.0, 1.0)

This is a subtle thing to test for, but one good example would be to compare the avatar walking animation on master vs the walk animation in this PR.  The one on master will have exaggerated chest and shoulder rotation, which is not present in the original animation.  The version in this PR will match the original animation more closely.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/89525346205639
https://app.asana.com/0/26225263936266/89355451869002

**Comment by hifi-gustavo** [comment]
Build console output for commit: df21fffa4a9b30b2311e3cfbc731e4c21947095b available at: https://gist.github.com/f3f8e8f4aaaef7b5cb6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5a72225db175d8ee552322a09a77e7d6a9fd687 available at: https://gist.github.com/f3f8e8f4aaaef7b5cb6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d1304e0703420490210c65eebcc746a2d35881f available at: https://gist.github.com/f3f8e8f4aaaef7b5cb6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7125.dmg

**Comment by AndrewMeadows** [comment]
I tested this since it was the same problem I was working on yesterday.  This PR is good.

**Pull request merged**
