### PR TITLE
Case 20533: Fix export entities

### PR DESCRIPTION
**Pull request by SamGondelman**
broke here: https://github.com/highfidelity/hifi/pull/14547/files#diff-740cf92da8140802f67b5aac4dc2ffc0R4899

https://highfidelity.manuscript.com/f/cases/20533/Export-entities-Unable-to-export-entities

Test plan:
- Verify that you can export entities and open the resulting file

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16304/HighFidelity-Beta-PR14665-62dbca6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16304/HighFidelity-Beta-PR14665-62dbca6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16304/HighFidelity-Beta-Interface-PR14665-62dbca6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16304/HighFidelity-Beta-PR14665-62dbca6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16304/HighFidelity-Beta-Interface-PR14665-62dbca6.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS
--
Export and Import both worked Logged In and Logged Out
Grouped Objects that were imported retained their cardinal orientation (ex facing East every time)
Objects import directly in front of the user.

Drag and Drop worked the same as Create mode import.

**Pull request merged**
