### PR TITLE
Fix MS19743: Fix case where user couldn't update certain items

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS19743](https://highfidelity.fogbugz.com/f/cases/19743/Bug-when-updating-certain-Marketplace-items).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Have >10 updates available to the same item in your inventory.
2. Try to update each of them. Verify that you can update all of them.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14830/HighFidelity-Beta-PR14360-f22bbff.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14830/HighFidelity-Beta-PR14360-f22bbff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14830/HighFidelity-Beta-Interface-PR14360-f22bbff.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14834/HighFidelity-Beta-PR14360-8776028.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14834/HighFidelity-Beta-Interface-PR14360-8776028.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14834/HighFidelity-Beta-PR14360-8776028.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14834/HighFidelity-Beta-Interface-PR14360-8776028.exe

**Pull request merged**
