### PR TITLE
Miscellaneous logging fixes

### PR DESCRIPTION
**Pull request by SamGondelman**
There were some errors being logged that were bothering me.

Specifically:
- 3 backtraces from mismatched script connect/disconnects
- 1 error from a missing script disconnect
- 3 missing sendToScripts in QML

Test plan:
- Functionally nothing has changed.
- Reload default scripts and check your logs.
- Shouldn't see any backtraces from messed up signal disconnects.
- Shouldn't see an error about an undefined button in help.js.
- Shouldn't see logged errors about missing "sendToScript" signals.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2492/HighFidelity-Beta-PR11191-1c273351933424bcae61f277b8bbcedfc31d1753.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2492/HighFidelity-Beta-PR11191-1c273351933424bcae61f277b8bbcedfc31d1753.exe

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {9ae5c956-cd96-4b0c-9d4c-f3ce5c126645}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {2fcc72d4-5751-4d7c-9ac8-fba684a7376d}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {9c1413e7-0dfe-4d5d-ad1f-0a29da5b5ed2}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {dd220b3b-f8d5-40e5-b926-f7428542b469}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {2f940fa3-8ce9-4172-b30d-7576b4a20e26}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {33d8cd52-5d65-4f1d-b498-4021501ba799}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {712a6dae-b491-4a9d-a498-49199b21b720}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {c04d50fc-3779-421f-a169-48023f1cb213}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {3e24df3a-7c12-4a2b-b061-297fb29cb149}
[08/15 15:41:48] [DEBUG] [qml] Warning: Tablet.qml could not find button with uuid = {52b0a98e-b284-4c8b-83d0-88d3619a4889}


@SamGondelman Got those errors Apart from that ok in tablet and toolbar mode.

**Comment by Nex-Pro** [comment]
[Logs.zip](https://github.com/highfidelity/hifi/files/1225497/Logs.zip)
Logs.

**Comment by SamGondelman** [comment]
@Nex-Pro Since I can't repro that warning and it wasn't one of the ones I was trying to get rid of and since they are being handled properly anyways, I'm going to go ahead and claim that this is a pass.

**Pull request merged**
