### PR TITLE
Additional toolbar work

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37e9f666390c6f92dcdd0d731d2404b5fa2b4781 available at: https://gist.github.com/74071f2e56daa69e6d4e660f169fe21f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8108.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8108.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9p7BUo0R&#x2F;49-try-pinning-only-the-hud-button-not-whole-tray"> try pinning only the hud button (not whole tray)</a>

**Comment by howard-stearns** [comment]
test plan:
when the HUD goes away (either through clicking the HUD button, toggling View->Overlays, or moving with drive keys or in room-scale), the tool bar should collapse down to just the HUD button, and then restore when the HUD comes back.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0bc4beeffd4e85d353ece1219cdd3697a2b14ce6 available at: https://gist.github.com/74071f2e56daa69e6d4e660f169fe21f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8108.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8108.dmg

**Comment by jherico** [comment]
## Testing

* When the overlay layer is toggled either by driving or by clicking the hud button, all buttons other than the HUD button should disappear, and reappear when the overlay layer returns.
* The toolbar position should be properly remembered between sessions now

**Comment by SamGondelman** [comment]
QA Test:
- All other buttons and windows disappear and reappear properly when the HUD button is pressed or when the overlays are toggled by moving outside of the sphere
- Toolbar position is properly remembered between sessions

Possible issues:
- In HMD mode, if you drag the HUD toolbar very quickly up, down, or towards the part of the sphere that isn't "HUD-able", it's possible to lose it "offscreen."  Switching back to desktop fixes it.
- In HMD mode, when the HUD button is deactivated, it stays in the same place, but when you activate it, it moves as the sphere gets re-positioned around you, which is disorienting.
- When restarting Interface, the toolbar always starts in the "on" state, regardless of if it was off when you closed Interface.  This might be desirable, just want to make sure it's intentional.

**Comment by SamGondelman** [comment]
Actually, if you quit while in HMD mode and restart, the HUD button is gone, which is a big issue.  I think I can maybe see the top of it peeking out at the bottom of the HUD-able space if I look around carefully.

**Comment by jherico** [comment]
@SamGondelman those issues are all present in the vive-ui branch and aren't really what this PR was targeting, so I don't think that constitutes a QA fail.  Howard mentioned that he wasn't able to reproduce the issue with shutting down and restarting in HMD mode making the button appear mostly offscreen.  Is it possible that you ran the main vive-ui build between the shutdown and restart, because _that_ one will incorrectly position the toolbar and persist the bad position to the INI file.

**Comment by howard-stearns** [comment]
We'll deal with the following issues separately (quotes are names of cards):
- "HUD should reset when coming back from moving, but not when toggling overlays directly."
- "tray sometimes repositions inacessibly"

Pass (of this PR)

**Comment by SamGondelman** [comment]
@jherico I haven't even downloaded the main vive-ui branch so it was definitely this PR.  I'll try to find a way to reliably repro it.

**Pull request merged**
