### PR TITLE
DEV-108: Removed ctrl+b and ctrl+n as shortcuts

### PR DESCRIPTION
**Pull request by PrestonB1123**
removed ctrl+b and ctrl+n as shortcuts
https://highfidelity.atlassian.net/browse/DEV-108

### CODE REVIEW

**Comment by RebeccaStankus** [comment]
Looks good!

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19855/HighFidelity-Beta-PR15711-a0753f6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19855/HighFidelity-Quest-Beta-PR15711-a0753f6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19855/HighFidelity-Beta-PR15711-a0753f6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19855/HighFidelity-Beta-Interface-PR15711-a0753f6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19855/HighFidelity-Beta-PR15711-a0753f6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19855/HighFidelity-Beta-Interface-PR15711-a0753f6.exe

**Pull request merged**
