### PR TITLE
Android: Stats, disable IK, reduce impact of InputRecorder

### PR DESCRIPTION
**Pull request by SamGondelman**
- Adds a button to display stats on Android.
- Disables IK on Android.
- Don't call UserInputMapper::getActionName in ActionEndpoint::apply if InputRecorder is off (it's doing some QString list reallocations that are expensive)

Test plan:
- (Desktop) With hand controllers, verify that you can still move your hands and use the buttons to move/teleport.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8079/app_12661_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8079/HighFidelity-Beta-PR12661-0fa73c73ce24c107d6dc519607e95930881f0386.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8079/HighFidelity-Beta-PR12661-0fa73c73ce24c107d6dc519607e95930881f0386.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8124/app_12661_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8124/HighFidelity-Beta-PR12661-06c0b3afd3e9c324e6e9fc4858dfb1adfdc6d46d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8124/HighFidelity-Beta-PR12661-06c0b3afd3e9c324e6e9fc4858dfb1adfdc6d46d.exe

**Comment by samcake** [comment]
@SamGondelman We need a Test plan for this one

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Hand Controllers work as expected, build opens and runs on all platforms.

**Pull request merged**
