### PR TITLE
BUGZ-531: Quest tablet login missing keyboard

### PR DESCRIPTION
**Pull request by annabrewer**
Fixed the missing keyboard on "Menu > File > Log In / Sign Up" on Quest tablet. Also organized the properties in LoginDialog.qml and TabletLoginDialog.qml to make it easier to see the differences when merging the files in the future.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19946/HighFidelity-Beta-PR15753-4b30065.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19946/HighFidelity-Quest-Beta-PR15753-4b30065.apk)

**Comment by annabrewer** [comment]
Closing this because that stupid commit from May 20th got back into my commit history >:( Will make a fresh PR in a moment!

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19968/HighFidelity-Beta-PR15753-a640e18.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19968/HighFidelity-Quest-Beta-PR15753-a640e18.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19968/HighFidelity-Beta-PR15753-a640e18.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19968/HighFidelity-Beta-Interface-PR15753-a640e18.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19968/HighFidelity-Beta-PR15753-a640e18.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19968/HighFidelity-Beta-Interface-PR15753-a640e18.exe

**Pull request closed without merging**
