### PR TITLE
Fix heap alignment of MyAvatar

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes the following Windows build warning:
warning C4316: object allocated on the heap may not be aligned 16
in AvatarManager.cpp line 58

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ac158f2d5694b187b9a6f600fee600a98e9735a available at: https://gist.github.com/3e55cdf4bf54b422a317<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4946.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4946.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ac158f2d5694b187b9a6f600fee600a98e9735a available at: https://gist.github.com/3e55cdf4bf54b422a317<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4946.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4946.dmg

**Comment by ctrlaltdavid** [comment]
Linux doesn't like this approach; will implement a different approach.

**Pull request closed without merging**
