### PR TITLE
Edit handles trigger fixes

### PR DESCRIPTION
**Pull request by dback2**
Use a click handler on Controller.Standard.RTClick/LTClick inputs for consistency with trigger clicks in other controllers instead of specific trigger threshold values. Prevent both hands from triggering in entitySelectionTool at the same time.

Fixes: https://highfidelity.fogbugz.com/f/cases/14864/

Test Plan:
- Enter Interface in HMD mode on Rift
- Open Create app in Tablet and select any entity
- Point at different edit handles, slowly press trigger down to verify that it doesn't trigger the edit handle until the laser turns red, and verify the edit handles work as expected
- Point at the entity itself (outside of any edit handles) to perform XZ-plane translation, slowly press trigger down to verify that it doesn't trigger the translation until the laser turns red, and verify XZ-plane translation works as expected
- Point and trigger on any edit handle again, and while holding that handle attempt to point and trigger with the other hand anywhere on the entity including the already-triggered handle, and verify the other hand has no impact when triggering on the entity or handles
- Point and trigger on any edit handle again, and while holding that handle attempt to point and trigger on other entities to change selection as well as into the void to clear selection, and verify the other hand has no impact when triggering on other entities or into the void
- Verify when not triggering with either hand that the selected entity can be changed as expected by triggering on another entity with either hand's laser, as well as that the selection can be cleared as expected by triggering into the void with either hand's laser
- Continue to stress test around the above cases as well as edit handles themselves to verify all handles work as expected and there are no other issues
- Repeat above tests in HMD mode on Vive

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11610/HighFidelity-Beta-PR13703-dcdf734.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11610/HighFidelity-Beta-PR13703-dcdf734.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11610/HighFidelity-Beta-Interface-PR13703-dcdf734.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11611/HighFidelity-Beta-PR13703-cd842af.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11611/HighFidelity-Beta-PR13703-cd842af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11611/HighFidelity-Beta-Interface-PR13703-cd842af.exe

**Comment by qlistephens95** [comment]
FAIL @conklin94122 no editing is able to be done with controller triggers and lasers. When activating red laser on the edit handles nothing happens.
Steps to reproduce:
1: launch assumed build
2: In HMD open tablet and select create menu
3: create an entity
4: try to edit entity with trigger lasers and edit handles
5: Entities are unable to be edited.
[PR.1.zip](https://github.com/highfidelity/hifi/files/2236301/PR.1.zip)

**Comment by dback2** [comment]
Fix fail case on this is Vive-specific. Will continue investigating what's going wrong on Vive on Monday.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11682/HighFidelity-Beta-PR13703-b420ef8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11682/HighFidelity-Beta-PR13703-b420ef8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11682/HighFidelity-Beta-Interface-PR13703-b420ef8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11682/HighFidelity-Beta-PR13703-b420ef8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11682/HighFidelity-Beta-Interface-PR13703-b420ef8.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11731/HighFidelity-Beta-PR13703-ad9ec26.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11731/HighFidelity-Beta-PR13703-ad9ec26.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11731/HighFidelity-Beta-Interface-PR13703-ad9ec26.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11731/HighFidelity-Beta-PR13703-ad9ec26.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11731/HighFidelity-Beta-Interface-PR13703-ad9ec26.exe

**Comment by qliejahner** [comment]
Currently testing on Rift

**Comment by qliejahner** [comment]
FAIL @conklin94122 

On Rift and Vive, while editing an entity's position, the other hand can click on and select the icons of light sources and particle emitters.

interface 2018 07 31 - 15 24 59 02

There also seems to be a very large number of error logs being generated.

[hifi-logs.zip](https://github.com/highfidelity/hifi/files/2247235/hifi-logs.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11758/HighFidelity-Beta-PR13703-e8068fe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11758/HighFidelity-Beta-PR13703-e8068fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11758/HighFidelity-Beta-Interface-PR13703-e8068fe.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

While editing an entity with one hand, the other hand's laser no longer has an effect. No new problems were seen.

**Pull request merged**
