### PR TITLE
Fix GPU buffer leak in geometry cache / overlays

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Using scripts that create and destroy overlays should no longer cause log lines like `[10/17 12:14:11] [DEBUG] [hifi.gpu] New max GPU buffers  734` every time an overlay is created.  Affected overlays are line3d, circle3d, and rectangle3d.  The easiest way to test this is to use the hand controller triggers on Vive to create pointer lines repeatedly.  In production code this will lead to several log lines about new max GPU buffers corresponding to every time you pull the triggers and the lines become visible.  

Note that you will still see `max GPU buffers` increase as content is loaded for the first time or new content is loaded into an existing scene.  

Any content or script that appears to cause runaway creation of GPU buffers should be reported.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: dde79ef3c57582b89bbc12b87cc945ef17479360 available at: https://gist.github.com/ea1d306bcabebfc217b4c97ba7818bf1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-dde79ef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-dde79ef.dmg

**Comment by ZappoMan** [comment]
Passes basic smoke test. But did crash on exit... checking to see if that looks related.

**Comment by ZappoMan** [comment]
crash on exit is related to this PR...

```
Interface!QHash::remove	c:/qt/qt5.6.1/5.6/msvc2013_64/include/qtcore/qhash.h(769)
Interface!GeometryCache::releaseID	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/render-utils/src/geometrycache.cpp(446)
Interface!Line3DOverlay::~Line3DOverlay	c:/jenkins/workspace/beta_pr-master/label/windows/interface/src/ui/overlays/line3doverlay.cpp(38)
Interface!Line3DOverlay::scalar deleting destructor'	-
interface!render::Payload::~Payload	-
interface!std::vector >::_Destroy	c:/program files (x86)/microsoft visual studio 12.0/vc/include/vector(1567)
interface!render::Scene::~Scene	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/render/src/render/scene.h(58)
interface!std::_Ref_count::_Destroy	c:/program files (x86)/microsoft visual studio 12.0/vc/include/memory(159)
interface!Application::~Application
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: faed4a05ea55a7e946fcaa888e7bef451c7241a4 available at: https://gist.github.com/ea1d306bcabebfc217b4c97ba7818bf1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-faed4a0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-faed4a0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99ed7ac08cf00b7feb8fa222e251538620850e1c available at: https://gist.github.com/ea1d306bcabebfc217b4c97ba7818bf1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-99ed7ac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8829-99ed7ac.dmg

**Comment by ZappoMan** [comment]
smoked it, it no longer crashes on shutdown

**Pull request merged**
