### PR TITLE
Overlays JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Overlays namespace

Global types:
- Color
- KeyboardModifiers
- PointerEvent
- Rect
- Shape
- Size

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Do not merge this PR until after the preceding PR - https://github.com/highfidelity/hifi/pull/11884- has been merged.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5200/HighFidelity-Beta-PR11885-cd2922a560d21bcaf688b86e40f83187592c7c19.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5201/HighFidelity-Beta-PR11885-cd2922a560d21bcaf688b86e40f83187592c7c19.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5201/HighFidelity-Beta-PR11885-cd2922a560d21bcaf688b86e40f83187592c7c19.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5443/HighFidelity-Beta-PR11885-0146eca31506fc20e1f59176253627e4c100ff8a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5443/HighFidelity-Beta-PR11885-0146eca31506fc20e1f59176253627e4c100ff8a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5580/HighFidelity-Beta-PR11885-58fa8b9fbfb3463a6bb2b588ec63d7e4810529fa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5580/HighFidelity-Beta-PR11885-58fa8b9fbfb3463a6bb2b588ec63d7e4810529fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5602/HighFidelity-Beta-PR11885-92be33da315ba6fb063646ddde5cc55b84a1d4e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5602/HighFidelity-Beta-PR11885-92be33da315ba6fb063646ddde5cc55b84a1d4e1.exe

**Pull request merged**
