### PR TITLE
send lookup hostname to DS for split counts, correct number of DS connected users

### PR DESCRIPTION
**Pull request by birarda**
- Interface sends the place name it used to get to the domain-server
- domain-server separates the number of connected users by place name they used to connect
- domain-server reports unauthenticated users in the count of connected users

### CODE REVIEW

**Comment by birarda** [comment]
Testing notes:

You should not expect to be able to connect to current HF servers from this build, since they will not recognize your connect packets after the version change.

Connect to the Sandbox from this PR build. Confirm that you have no problems connecting using "localhost" and the assigned temporary name or any place name that you currently have pointing at your domain.

While your Sandbox is running, contact me to confirm that the metaverse API is receiving the updated values I expect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6875371bd097595e59cad66b40922325413b6d65 available at: https://gist.github.com/7fcef62bdd35e6c071d479c93b9b332d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.dmg

**Comment by OmegaHeron** [comment]
@birarda - o2tech is running this PR now.

**Comment by birarda** [comment]
@OmegaHeron keep it going, heading to check

**Comment by OmegaHeron** [comment]
It'll be up long as you need it - it's my spare server.

**Comment by birarda** [comment]
@OmegaHeron so far so good - I see that one user is in your domain from o2tech (I assume that's you right now).

I'm connecting from my client shortly.

**Comment by OmegaHeron** [comment]
Moment - let me open the door ;)

**Comment by OmegaHeron** [comment]
Good to go - note to self - investigate client not reconnecting to domain on restart vs previous auto-recover.

**Comment by birarda** [comment]
@OmegaHeron great! Needed a client side fix I will test with once built. 
We can pass the API side of things once I check that fix.

**Comment by OmegaHeron** [comment]
Cool - I'll leave this up.  Will consider it enhanced security for a time.  :+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f94f118d0349e8a21ad0f8d46124df721508667 available at: https://gist.github.com/7fcef62bdd35e6c071d479c93b9b332d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f638d111de6883225404ea6210a39be42d94e0f available at: https://gist.github.com/7fcef62bdd35e6c071d479c93b9b332d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.dmg

**Comment by birarda** [comment]
Tested what the final fix was for: switching from your place name to domain ID (without leaving the domain in the middle) causes a hostname switch for reported user hostnames. Pass on my end.

**Comment by OmegaHeron** [comment]
I'm content with performance on Linux box QA Pass for me as well.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 33379824c8d0ad122d0e5435a9fa7c88ae59042b available at: https://gist.github.com/7fcef62bdd35e6c071d479c93b9b332d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7860.dmg

**Pull request merged**
