### PR TITLE
DEV-2413: Restate legacy first person camera mode

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-2413
`Kayla-Camera.js` script stopped working after the latest camera work. It relays on the previous first person camera mode to set the camera rotation. 
This PR restate the old first person camera mode and rename the new one.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
I'll test out the script when the windows link pops up.  Code looks good from what I can tell though.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21993/HighFidelity-Beta-PR16368-63c2b41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21993/HighFidelity-Beta-Interface-PR16368-63c2b41.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21993/HighFidelity-Beta-PR16368-63c2b41.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21993/HighFidelity-Beta-Interface-PR16368-63c2b41.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21993/HighFidelity-Beta-PR16368-63c2b41.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21993/HighFidelity-Quest-Beta-PR16368-63c2b41.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22001/HighFidelity-Beta-PR16368-33ea63c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22001/HighFidelity-Quest-Beta-PR16368-33ea63c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22001/HighFidelity-Beta-PR16368-33ea63c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22001/HighFidelity-Beta-Interface-PR16368-33ea63c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22001/HighFidelity-Beta-PR16368-33ea63c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22001/HighFidelity-Beta-Interface-PR16368-33ea63c.exe

**Pull request merged**
