### PR TITLE
BUGZ-964: fix for incorrect color curve when rendering 3D into QML

### PR DESCRIPTION
**Pull request by jherico**
RC83 version of #15991

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20663/HighFidelity-Beta-PR16006-36b249d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20663/HighFidelity-Quest-Beta-PR16006-36b249d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20663/HighFidelity-Beta-PR16006-36b249d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20663/HighFidelity-Beta-Interface-PR16006-36b249d.dmg

**Comment by jherico** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20666/HighFidelity-Beta-PR16006-36b249d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20666/HighFidelity-Quest-Beta-PR16006-36b249d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20666/HighFidelity-Beta-PR16006-36b249d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20666/HighFidelity-Beta-Interface-PR16006-36b249d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20666/HighFidelity-Beta-PR16006-36b249d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20666/HighFidelity-Beta-Interface-PR16006-36b249d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20678/HighFidelity-Beta-PR16006-36b249d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20678/HighFidelity-Beta-Interface-PR16006-36b249d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20678/HighFidelity-Beta-PR16006-36b249d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20678/HighFidelity-Quest-Beta-PR16006-36b249d.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20678/HighFidelity-Beta-PR16006-36b249d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20678/HighFidelity-Beta-Interface-PR16006-36b249d.exe

**Pull request merged**
