### PR TITLE
Added readme and size field to avatar data packet dissector

### PR DESCRIPTION
**Pull request by hyperlogic**
Added readme that describes how to use wireshark plugins.
Added size field that prints the total size of the avatar data payload, as well as the section containing the actual joint data, (position and translation).

### CODE REVIEW

**Comment by hyperlogic** [comment]
No QA is required, this is an internal tool

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11878/HighFidelity-Beta-PR13763-2cd01ad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11878/HighFidelity-Beta-PR13763-2cd01ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11878/HighFidelity-Beta-Interface-PR13763-2cd01ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11878/HighFidelity-Beta-PR13763-2cd01ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11878/HighFidelity-Beta-Interface-PR13763-2cd01ad.exe

**Pull request merged**
