### PR TITLE
workaround bad FBXMesh data rather than assert

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* avoid debug crash when FBXMesh data is bad

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Some asserts were added that were putting strict requirements on the FBXMesh data being correct.  Unfortunately these asserts are being triggered and I don't have time to fix the FBXReader code at this time.  To help unblock my fellow developers I've commented out the asserts and added some workarounds instead.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb9a5466d551e6cac5a2cec9f496f0a4ed76a3a9 available at: https://gist.github.com/3ad85670f28b3e1130273c451cf8f271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-cb9a546.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-cb9a546.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6446c7c302007ae9d95740097022526157b4380f available at: https://gist.github.com/3ad85670f28b3e1130273c451cf8f271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-6446c7c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-6446c7c.dmg

**Comment by AndrewMeadows** [comment]
Testing the crash requires a debug build, so I tested that myself.  We had an example model that would crash (hit an assert) in debug mode -- in this PR the crash does not happen --> the object appears correctly but does not crash.

To test:

(1) Smoke test: make sure objects show up and collide correctly in some domains with several models: Home and Playa should be sufficient.

(2) Create a model entity that uses this modelURL:

https://hifi-content.s3.amazonaws.com/andrew//home/andrew/public_html/models/tablet.fbx

Set the shape to use the "static-mesh" (Exact).

The interface should not crash however in this PR the object should not collide -- the collision shape is just never generated.  Dunno how it collides on older versions.

(3) Give the tablet object a Box and it should collide.  Dunno about "simple-hull" (Basic) or "simple-compound" (Good) collision options -- might work or might not.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6446c7c302007ae9d95740097022526157b4380f available at: https://gist.github.com/3ad85670f28b3e1130273c451cf8f271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-6446c7c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-6446c7c.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Fail - existing content that collides proper (ground) in 5244 (and latest dev 5289) fails to collide with this.  hifi://heron if you want to examine what's happening.

**Comment by AndrewMeadows** [comment]
Thanks for testing that @omegaHeron.  There was definitely a bug: I was relying on `BufferView::Iterator::operator<()` which is not implemented (so I guess some default operator is created which doesn't work).

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3f165d9dafc82d4449ea19b9b54139f40a863dc available at: https://gist.github.com/3ad85670f28b3e1130273c451cf8f271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-c3f165d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-c3f165d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b5ed220bc2b81432e3da965a753661701c1f994 available at: https://gist.github.com/3ad85670f28b3e1130273c451cf8f271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-5b5ed22.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8471-5b5ed22.dmg

**Pull request merged**
