### PR TITLE
RC76: Entity properties - fix subproperty updates

### PR DESCRIPTION
**Pull request by dback2**
Addresses: https://highfidelity.manuscript.com/f/cases/20095

Pre-Merge Test Plan:
- Enter Interface in desktop mode into any domain with edit permissions
- Open Create and select or create any entity
- Make changes to the indented subproperties under Collides
- Press Ctrl + R to reload scripts and reselect the same entity
- Verify the subproperty values under Collides are still the same

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15526/HighFidelity-Beta-PR14500-b81fcb6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15526/HighFidelity-Beta-PR14500-b81fcb6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15526/HighFidelity-Beta-Interface-PR14500-b81fcb6.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Create retains collision values for entities

**Pull request merged**
