### PR TITLE
Add automaticLookAt.js to developer scripts

### PR DESCRIPTION
**Pull request by luiscuenca**
`automaticLookAt.js` is a script that automatically controls the avatar's head and eye to simulate human interaction during group interactions.
This PR adds that script to the developer script folder.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22715/HighFidelity-Beta-PR16545-f17caf4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22715/HighFidelity-Beta-Interface-PR16545-f17caf4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22715/HighFidelity-Beta-PR16545-f17caf4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22715/HighFidelity-Quest-Beta-PR16545-f17caf4.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22719/HighFidelity-Beta-PR16545-f17caf4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22719/HighFidelity-Quest-Beta-PR16545-f17caf4.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22719/HighFidelity-Beta-PR16545-f17caf4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22719/HighFidelity-Beta-Interface-PR16545-f17caf4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22719/HighFidelity-Beta-PR16545-f17caf4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22719/HighFidelity-Beta-Interface-PR16545-f17caf4.exe

**Pull request merged**
