### PR TITLE
Fix recording playback not clearing attachments and nametags

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Review Notes**
Calling `setAttachmentData()` only when the attachment data changes means that `markIdentityDataChanged()` is called only when the attachment data changes (rather than every pass when there is non-empty attachment data, which it did previously).

**Comment by ctrlaltdavid** [comment]
**Testing**

1) Using record.js and playRecordingAC.js...
Make a recording in which you add an attachment and then remove it. The recording playback should also have the attachment being added and removed. (Previously, the attachment would be added but not removed.)

2) Using record.js, playRecordingAC.js, and http://ctrlaltstudio.com/downloads/hifi/scripts/nametags.js (click the "nametags" button to display nametags above avatars' heads) ...
Make a recording in which you change your display name and then set it to "". The recording playback should also have the display name change and then set to "" (displayed as "anonymous").

**Comment by CainFoool** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7897bf8aa873d32235d3f2669b24cf3d8374d7b5 available at: https://gist.github.com/a93c62fc67f6cbc29be1150f9def4107<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10474-7897bf8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10474-7897bf8.dmg

**Comment by CainFoool** [comment]
^ Testing now.

**Comment by CainFoool** [comment]
Testing Complete

Pt 1.
Recorded my avatar adding and removing an attachment, played back as expected properly. Item did detach.

**PASS** 

Pt 2.
Set my initial name to Cain, started the recording and then went into the People tab and removed my name altogether which resulted in my name being anonymous. Once the recording was finished, the name changed however added a _ followed by an increment number each time.

**PASS** (Considering the name change did work)

(See Attachment)

58z34

**Pull request merged**
