### PR TITLE
Make background with default color. Fix few warnings

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- Open Tablet
- goto Menu -> Settings -> General
- press Browse button
- Make sure no black background under file list

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/996/HighFidelity-Beta-PR10782-30714d5d254cdb924ad35302a81355dd296a2e58.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/996/HighFidelity-Beta-PR10782-30714d5d254cdb924ad35302a81355dd296a2e58.exe

**Comment by CainFoool** [comment]
Hey @vladest: Is this QA Ready?

**Comment by vladest** [comment]
@CainFoool I think so

**Comment by CainFoool** [comment]
Alright - testing now :)

**Comment by CainFoool** [comment]
# Test Passed 
Test | Result
-------- | --------
Open Tablet | Pass
goto Menu -> Settings -> General | Pass
press Browse button | Pass
Make sure no black background under file list | Pass

Quick preview gif:


Let me know if you'd like anything else tested.
###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
