### PR TITLE
Fix particle uniform buffer issue (RC62)

### PR DESCRIPTION
**Pull request by SamGondelman**
same as https://github.com/highfidelity/hifi/pull/12141

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6216/app_12146_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6216/HighFidelity-Beta-PR12146-a3ca8e3a72d5c552e85681533e41d15380d24018.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6216/HighFidelity-Beta-PR12146-a3ca8e3a72d5c552e85681533e41d15380d24018.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
