### PR TITLE
Add silent_packets stat to audio mixer

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- run this sandbox
- connect a client
- open up the audio-mixer stats page
- see that the `silent_packets_per_frame` stat exists and changes periodically

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1cf04e0f0c352fd7acd7c59d207dfcfe9487b2f available at: https://gist.github.com/4d95b30bebe87c1f6e3b6323aa2f3ad7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9660-e1cf04e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9660-e1cf04e.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by OmegaHeron** [comment]
QA Pass
Tested Windows 10
Silent packets stat shows, seems to vary depending upon agents connected/not connected and mic muted/not muted.

General smoke test = pass

**Comment by ZappoMan** [comment]
waiting on build (with mac build) to complete - then I will merge

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1cf04e0f0c352fd7acd7c59d207dfcfe9487b2f available at: https://gist.github.com/4d95b30bebe87c1f6e3b6323aa2f3ad7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9660-e1cf04e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9660-e1cf04e.dmg

**Pull request merged**
