### PR TITLE
fix desktop press-x handshake

### PR DESCRIPTION
**Pull request by sethalves**
- fix desktop press-x handshake

https://highfidelity.manuscript.com/f/cases/14416/
https://highfidelity.manuscript.com/f/cases/17282/Unable-to-handshake-in-desktop-mode

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- using desktop mode, press X to shake hands with someone

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12073/HighFidelity-Beta-PR13817-4fa0c96.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12073/HighFidelity-Beta-PR13817-4fa0c96.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12073/HighFidelity-Beta-Interface-PR13817-4fa0c96.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12073/HighFidelity-Beta-PR13817-4fa0c96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12073/HighFidelity-Beta-Interface-PR13817-4fa0c96.exe

**Comment by QliCknox** [comment]
Currently Testing

**Pull request merged**
