### PR TITLE
Avatar entities

### PR DESCRIPTION
**Pull request by sethalves**
- Entities can be associated with an owning avatar (avatarEntities)
- avatarEntities live in local interface octrees but not in the entity-server octree
- avatarEntities are sent to other interfaces via the avatar-mixer rather than entity-server
- avatarEntities are saved to interface Settings and loaded from there on startup

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 995eb456990941a870d39cff0a560e2b68613dc4 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b2a7bebe37a05e5542d5690c3d75923631a6f90 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b745b74d9126ae7d89516da09d9374bbec610c2e available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 33f0bd77af0b9137ce8246acc5cc61b49b352ec6 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 03d1f51a4d885347b1e1c00c5879108b731c91a4 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2db3b5a7cccf6488b92968a77bac36c3eb5ef3c available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 648a15852da6e5ea9efae3948e8be2365d7efb13 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8911c8592cd2a55f2a50bb3fe0c1dd05ab0dc41 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0588b1dc4c9f6be0d2110ca3435d44e50f316587 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17f884c732c0cf3534589163e097da06aea85d7c available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f4ea935a69687d73658606c5109e59dbe0ced5a5 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7880961f385dca6561707fc310cea1845a173fd5 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef8abd8853ec5c01b04dc8ad6d6bb8be1f2c0ee8 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 463b98a1f7e6f5b6514c65091dcfc5e297564978 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b25722d838ec5933384945f0d46d79e01e5f51d1 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c105dac2bf91fdd6f7c0c543d9a7c55be7bce866 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c980f8653eb59638d0397019099730bd34af6aa available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e85e86ad3949ea10d782b6a031206c5c71fc233 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: efdcc02a1f7d63dec22d4d47b106065aa08e8a08 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c18c953a3a0180ff0de10297fb89de5e396dbac6 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 93d9ad4b65ed5de728ca6e3a9055bdc49851d095 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 063d8aa2510ef2d64bb32f59f3a60b96b13c74c5 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 922d610395ff48783d0e82bf93e9142d21cb4d6b available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f30dc39e05e3660f2ef622a5663eb7ca4320d0ab available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72ca367ae865a019514f5e3031e950ee3153a65b available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ebb28e648dfc85e07be74cb7edb4405b55a92f5 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e5877ed2d28d11177b09fc845d6bbb27fd3f439 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f66ebd659983688044a12f2b5f21b1f8777474c available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bee82835add3f788f99f9bace0d7b9d8e21118ea available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 16269c7e3bb54d442e3763ab68c1ed53aa293001 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0de227fd542bda6c012968152b5983dfd30e7cbe available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed32603c7a8d54b8d2a528267f630c7ffacd8926 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 410ba66b44b7bb8425432bd569e902b571e77f68 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a44bc5c8f1fb036258a62d9041438f58350c6eec available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40ff7363e1b66b271ac299ec494e53643fb5ec1a available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7cae1ecd99c6f5cda7cd6d68de6e9d38155c276e available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 615fccd58cfc6623c4c4e709b55e203ee9f9b740 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a57f356e2fe75e89fc482943c9e571cfea13ebbf available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11379183ef7cdeb5726f8ac72c2fd04c84d69a60 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59075135e395fae7ffc63ffcc0fb966834906a9b available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f784fcacc5b5e3f1d96d9d911f9482c7275c653f available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c10849c6ec593cd2eac4047f23eb999d109a12f available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48defe43e5bd9ea9a2810cf28c35cfd95feaf439 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d71bfb173e997ed4d0a7f29219ad85ed109170f9 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7aa0ce9da946162987b417176965c0ae53d9f13b available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57efefb56c3115a1c33e36703fcd7b9db53f15ca available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57efefb56c3115a1c33e36703fcd7b9db53f15ca available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 850d35f5579c603a185357ac23f59d00162f7916 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f8bf55261399f86db5d246cb00e6c2eb0c22714 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79bb7723561642db9ff56981108a1a88bc8e191b available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by nbq** [comment]
Is there a specific testing requirement for this PR?

**Comment by nbq** [comment]
I crashed a lot when trying to reposition an entity in my hands. I would either silent crash on logging out only to get a crash menu when I logged back in or I would get a hifi crash reporter popup which I submitted. I never got any crashes I could get my own crash report on.

I tested with these scripts:

https://rawgit.com/sethalves/hifi/avatar-entities/examples/attachedEntitiesManager.js
https://rawgit.com/sethalves/hifi/avatar-entities/examples/controllers/handControllerGrab.js

**Comment by hifi-gustavo** [comment]
Build console output for commit: 123f55be574fdd37bc2a2b8b88fef1bd961e94a7 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e8add51a96b0f04fa27014729e0f38686275ed4 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e8add51a96b0f04fa27014729e0f38686275ed4 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2413981ed3eae7814cb7fd02253cbd7b0df76a3d available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 462960a06f14b713e89ec8bb5d7228abbbb947b4 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec6cebe66dd4e418413931d1ea1c237e8e42c5ec available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3d627dcce18e0ca965601835c870924d5555db8 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7ed7d64ceba1f1cf4a60b02ad367fe3d3bae0cb available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee5ad95daa87f72d70c3a99d97492e05d515bc89 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee5ad95daa87f72d70c3a99d97492e05d515bc89 available at: https://gist.github.com/a9c81f45a149c8e660ff<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee5ad95daa87f72d70c3a99d97492e05d515bc89 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee5ad95daa87f72d70c3a99d97492e05d515bc89 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46da03d4c41e381edc5dbcfb127e6922740da816 available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7678b87ceed67636b3e9235540fa03b15246d6f available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cad65f84a805b277d8603587470dd734848c0c8e available at: https://gist.github.com/1ab9fa2e58ebd588175f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7020.dmg

**Comment by sethalves** [comment]
I'm leaving this open but re-marking DNM.  It seems unlikely we'll merge this before MVP.

**Pull request closed without merging**
