### PR TITLE
Alpha/Roughness G-Buffer debugging

### PR DESCRIPTION
**Pull request by Atlante45**
- Added alpha debugging
- Added roughness debugging
- Added mouse resizing
- Made the debug sub panels of the script collapsed on startup.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c4b9b90b1abbfa7a116921c9bf2699383518dbb0 available at: https://gist.github.com/0c4800917c36f932595f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e1832452ac52c49781a9ed33983937d0ddd3abf available at: https://gist.github.com/0c4800917c36f932595f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0603ead972cf4823d8a45bc32b1f0a39ac77bca1 available at: https://gist.github.com/0c4800917c36f932595f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0603ead972cf4823d8a45bc32b1f0a39ac77bca1 available at: https://gist.github.com/0c4800917c36f932595f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6569.dmg

**Pull request merged**
