### PR TITLE
BUGZ-707: HQ Launcher says "lastest and greatest"

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.atlassian.net/browse/BUGZ-707

### CODE REVIEW

**Comment by shanzzam** [comment]
Force merge to master so we can get a new launcher ASAP

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20000/HighFidelity-Beta-PR15777-11fb7e5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20000/HighFidelity-Beta-Interface-PR15777-11fb7e5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20000/HighFidelity-Beta-PR15777-11fb7e5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20000/HighFidelity-Quest-Beta-PR15777-11fb7e5.apk)

**Pull request merged**
