### PR TITLE
Moves text properties to top of Entity Properties panel

### PR DESCRIPTION
**Pull request by ericrius1**
Previously, these properties had been at the bottom of the panel.
https://app.asana.com/0/31759584831097/80715240133041

### CODE REVIEW

**Comment by ericrius1** [comment]
Test Script: https://rawgit.com/ericrius1/hifi/textEntityProps/examples/html/entityProperties.html

**Comment by imgntn** [comment]
@ericrius1 not sure that's the test script url you want

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40c66a94beb60a3490c54cfca3b8e30091270a78 available at: https://gist.github.com/e823a9b01e47a49a7b2c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.dmg

**Comment by imgntn** [comment]
@ericrius1 build is failing

**Comment by imgntn** [comment]
test this please

**Comment by imgntn** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40c66a94beb60a3490c54cfca3b8e30091270a78 available at: https://gist.github.com/e823a9b01e47a49a7b2c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.dmg

**Comment by imgntn** [comment]
@ericrius1 merge conflicts it seems

**Comment by hifi-gustavo** [comment]
Build console output for commit: 559fb9cbde93c5aea7da1c8936465d5a6d7b02bd available at: https://gist.github.com/e823a9b01e47a49a7b2c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6969.dmg

**Comment by imgntn** [comment]
just tried again and it seems to be still working.

**Pull request merged**
