### PR TITLE
Move mouse and hover slots out of Overlays API

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Test using the attached script:
- In desktop mode, run the script: it creates a cube overlay in front if you.
- Move your mouse over then off the overlay: the script should report "hover enter", "hover over", "mouse over", and "hover leave" events.
- Click your mouse on the overlay then release your mouse on the overlay: the script should report "mouse press" and "mouse release" events.

[mouseOverlayEvents.zip](https://github.com/highfidelity/hifi/files/1540762/mouseOverlayEvents.zip)

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5495/HighFidelity-Beta-PR11947-fd38b89f35383d1847be5174a08b4625bae07f0f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5495/HighFidelity-Beta-PR11947-fd38b89f35383d1847be5174a08b4625bae07f0f.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In desktop mode, run the script: it creates a cube overlay in front if you. **Check**
Move your mouse over then off the overlay: the script should report "hover enter", "hover over", "mouse over", and "hover leave" events. **Check**
Click your mouse on the overlay then release your mouse on the overlay: the script should report "mouse press" and "mouse release" events. **Check**

All **Pass** worth noting it is constantly printing this out many times a second, though I assume this is intentional.

**Comment by ctrlaltdavid** [comment]
Yes, it's intentional: that's the way the events occur.

**Pull request merged**
