### PR TITLE
Fix address bar becoming unusable after going backwards or forwards

### PR DESCRIPTION
**Pull request by huffman**
Problems:

 * Address bar was disabled but not hidden after receiving a requestFinished signal from the AddressManager
 * Hiding on requestFinished is probably not desired behavior because it means pressing back will cause the window to be closed when the request finishes.

With those problems in mind, I disabled the hide-on-requestFinished behavior altogether. When navigating by entering an address, the address bar is already hidden after pressing enter.

### CODE REVIEW

**Comment by huffman** [comment]
https://app.asana.com/0/26224634468389/116152658889504

**Comment by huffman** [comment]
To test:

 * Entering addresses in the address bar.
 * Navigating back/forwards using the arrows on the address bar. You should be able to do this more than once.
 * Any other stress testing you can do with the address bar to make sure it is functioning properly.

**Comment by ZappoMan** [comment]
What does this mean for the simple use case of "[enter]address[enter]"?

Is the location bar still visible after that?

**Comment by huffman** [comment]
Yes, the dialog is hidden when pressing enter.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4816380c9fcb3a97e52948029fb67401970f4853 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7767.dmg

**Comment by Nex-Pro** [comment]
This does not seem reliable. It seemed to forget places I had typed in after a while. 
Also I ended up with only the right arrow active until I got to the last place in the list then the left arrow re-activated itself.
This behaviour was repeated by using the left arrow until I arrived a

**Comment by huffman** [comment]
Hmm, I wonder if the back/forward buttons were ever fully working. I'll do more testing and see where the issue is. Thanks @Nex-Pro

**Comment by huffman** [comment]
@Nex-Pro Can you retest this when it builds? Thanks!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0db24581de899250303bcfde986102fe9f521bd5 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by Nex-Pro** [comment]
**PR Build: #7801**
**Testing Architecture: Desktop PC i7 4.4 (@ 4.0 ghz) 16gb nvidia gtx770 2gb**
**Testing OS: Win10 64** 
**Testing Locations: various**

Testing for address bar issues part 2

Works generally as expected. When trying to move locally from /2000/1999/2000  below a large flat cuboid to /2000,2100,2000 it would not tp/move me

trying to move from the top of the cuboid to /2000,2100,2000 worked fine.

Likewise trying to tp down past the cuboid did not work. This seems to be undesirable.

**Comment by huffman** [comment]
If there are issues with teleporting in general I would consider those to be a separate bug. Are you teleporting into the object? Does it have a collision hull that might be pushing you out, and that is what is actually happening?

"Additionally using direct locations within a region /x,y,z seems to destroy the history."

Ok, I will test that case.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58d640eb46e0768aa4f49e412c2ba9792b2be3c9 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e383ad87df1eafcc10a274c236e6e661c02b3e8 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by Nex-Pro** [comment]
@huffman Sorry for the delay in getting back to you. My Win10 installation decided to commit suicide. ( haven't recovered it yet ). Had to do a fresh install. 
Re the tp thing.  Was inputting co-ordinates that would have taken me far outside the objects.  Say 10x10x10 block adjacent to me  and inputting coords 200m beyond the block. It seems the avatar is physical whilst TPing.

**Comment by Nex-Pro** [comment]
@huffman  You want me to repeat the test on the fresh build?

**Comment by huffman** [comment]
@Nex-Pro Yes, that would be great, thanks!

I tried testing the TPing through physical objects problem but I couldn't replicate. Can you try testing this again with the latest build?

**Comment by Nex-Pro** [comment]
@huffman Testing now

**Comment by Nex-Pro** [comment]
**FAIL**
**PR Build: #7767**
Testing Architecture: Desktop PC i7 4.4 (@ 4.0 ghz) 16gb nvidia gtx770 2gb
Testing OS: Win10 64 
Testing Locations: various

This is adding each location visited via the use of the arrow icons thus the list of destinations grows with each click.   So the list quickly became localhost, playa, playa, playa, playa, playa, playa, alpha etc.  You get to  a point where it takes ten or more clicks to get from where you are the previous location.
Probably need to have some kind of check that the traveled to location hasn't already ( within a certain volume of space ) been appended/inserted into the list/array.

Could not reproduce the teleport behavior where I was previously blocked by nearby physical objects when TPing over short ranges.

**Comment by huffman** [comment]
Yikes, sorry @Nex-Pro, not sure how I missed that when I tested. I will fix.

**Comment by Nex-Pro** [comment]
@huffman
#### Np. If you need any coding advice just ask.

***(I've nearly completed 50% of a codecademy course )***

**Comment by huffman** [comment]
Haha, thanks :)

It's pretty hairy in the address manager, so if I can't find a simple fix I'll need to refactor a few things. Stay tuned...

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5b5171d0888dd5f9a4dec14295471e7faba07c7 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46cd5d2e41ec13738fe3454605f14322fa819ad8 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3345cec9dece0e2aba42bf1c2c234150209a297 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Comment by huffman** [comment]
@Nex-Pro Can you test this again? Thanks!

**Comment by Nex-Pro** [comment]
@huffman  sure thing

**Comment by Nex-Pro** [comment]
### FAIL

### 4x bugsplats submitted.

Address list built correctly with sandbox, playa, cellscience and forum. 

Repeated attempts to spam address list with "playa" were correctly ignored.

Address list  correctly recorded multiple different local locations (x,y,z) within the same region.

However I was able to build this list:

playa, cellscience, playa, forum, playa etc. do we want this ?

***side note:  Is that an arrow or house Icon?  If it's supposed to be a house it needs a chimney or a door.***

**Comment by Nex-Pro** [comment]
@huffman  Check my comment ^

**Comment by huffman** [comment]
> However I was able to build this list:
 playa, cellscience, playa, forum, playa etc. do we want this ?

I assume you are talking about multiple instances of the same location. Yes, I think that makes sense, otherwise we are modifying your history. It would be weird to me if I went to A, B, C, B, D, pressed back, and went to C because B appeared earlier in my history. IMO, of course.

re: house, yes, it is supposed to be a house. I actually mentioned the same internally, so I think it will be changed to be more clear in the future.

Regarding the crashes, I think these are existing bugs, not related to this PR, but I will take a look at the dumps you sent in. If they are related to ScriptEngine (that's what I've seen), then I think Zach has a pending PR that addresses that.

Thanks!

**Comment by huffman** [comment]
@Nex-Pro Yep, just checked, that's a separate bug that is being addressed separately. It's particularly noticeable when changing domains quickly.

**Comment by huffman** [comment]
@Nex-Pro Considering the crashes you saw were unrelated, would you consider this a PASS? Or were there other issues?

**Comment by Nex-Pro** [comment]
@huffman if the crashes were unrelated I guess this is a **PASS**

**Comment by huffman** [comment]
@Nex-Pro I'll rebase and do some tests myself - I believe the crash you were seeing has been fixed in master.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf6eba96a4a217603e458611a22283ca1ab3fbb7 available at: https://gist.github.com/af6843107f6920a60c483858a549cb15<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7767.dmg

**Pull request merged**
