### PR TITLE
Fix image overlay's subImage property's width and height support

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5453/HighFidelity-Beta-PR11942-efd72be96fd73068820973a88fd0d78a30b5078b.dmg

**Comment by ctrlaltdavid** [comment]
**Test Plan**

- Run the subImage.js script in the attached file. It should produce overlays as depicted in snapshot.png.

- Check the following items continue to display OK:
	- "Loading" bar in desktop and HMD mode.
	- Notifications messages in desktop and HMD mode.
	- directory.js script's toolbar icon in desktop and HMD mode.
	- avatarAttachmentsTest.js script's toolbar icon.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5454/HighFidelity-Beta-PR11942-d61f0584c3f5f5ec42b5a4684a87718f17b5a0e9.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5457/HighFidelity-Beta-PR11942-d61f0584c3f5f5ec42b5a4684a87718f17b5a0e9.dmg

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5457/HighFidelity-Beta-PR11942-d61f0584c3f5f5ec42b5a4684a87718f17b5a0e9.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Run the subImage.js script in the attached file. It should produce overlays as depicted in snapshot.png. | Pass
Check the following items continue to display OK: | 
"Loading" bar in desktop and HMD mode. | Pass
Notifications messages in desktop and HMD mode. | Pass
directory.js script's toolbar icon in desktop and HMD mode. | Pass
avatarAttachmentsTest.js script's toolbar icon. | Pass

Looks good to me!

**Pull request merged**
