### PR TITLE
Add "High Fidelity" to sandbox and interface description in Windows Task Manager

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
Note: I will be updating AC and DS as well

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f8cee787fa06a9e84d44395c1ef71553c3ca667 available at: https://gist.github.com/3c7e94350b08c6270210c4de18f61071<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8969-5f8cee7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8969-5f8cee7.dmg

**Comment by huffman** [comment]
To test:

 1. Run Sandbox and Interface
 2. Open the Task Manager
 3. Confirm that interface shows up as `High Fidelity Interface`
 4. Confirm that sandbox show up as `High Fidelity Sandbox`

**Comment by RyanDowne** [comment]
This looks pretty good. Do we also want to add High Fidelity - assignment client? In case those don't get shut down and people are looking for to debug

**Comment by huffman** [comment]
@RyanDowne Definitely! I had actually looked into it (hence my comment above) thinking it would be the same as the others, but the way we build AC and DS is slightly different. I was going to hold off so it wouldn't hold this PR back, but I'd be happy to add it as part of this PR, I just need to spend a little more time looking into it.

**Comment by huffman** [comment]
Marking DNM until that is in

**Comment by RyanDowne** [comment]
@huffman let's make that a sep job. Marking QA approved.

**Comment by huffman** [comment]
Whoops, I removed the DNM which also set QA Ready back :|

**Pull request merged**
