### PR TITLE
Add include with std::function

### PR DESCRIPTION
**Pull request by vladest**
Test plan:

- Build with gcc 7.x on Linux

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6918/app_12338_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6918/HighFidelity-Beta-PR12338-0715a7cae52be145150171a0b291e7dd7e4e70b0.dmg

**Comment by jherico** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6919/app_12338_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6919/HighFidelity-Beta-PR12338-0715a7cae52be145150171a0b291e7dd7e4e70b0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6919/HighFidelity-Beta-PR12338-0715a7cae52be145150171a0b291e7dd7e4e70b0.exe

**Pull request merged**
