### PR TITLE
Shadow bug fix : incorrect shadow map far plane when casting shadow on non-'shadow casters'

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes a bug with the shadow maps that can arise when objects that are not tagged as "Can Cast Shadows" are visible in the main camera view and should receive shadows. In this case, the shadow map cascade far planes can be wrongly evaluated because they do not take into account the presence of these "non casting shadow receivers". Visually, this gives big shadowed squares areas where there should be no shadows.

# Test plan
Use the _tests/engine/render/shadows_ test to evaluate this. This test has been updated to check this potential case in [tests/engine/render/shadows](https://github.com/highfidelity/hifi_tests/tree/master/tests/engine/render/shadows)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8576/app_12814_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8576/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8576/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Stopped Testing

**Comment by conklin94122** [comment]
Issues with shadows.js, Sam is addressing, removing QA Ready for now.

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8766/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8766/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8772/app_12814_PR_573f399023eafd625212284f827ea3207f006f76.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8772/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8772/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8772/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8772/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by Zvork** [comment]
A split shadow auto test case has been created in [hifi_test PR #44](https://github.com/highfidelity/hifi_tests/pull/44) to test this.

**Comment by L370** [comment]
@Zvork @NissimHadar For HMD testing it seems that we will need some manual intervention to get the script to function correctly, yes?   Regarding the various GPU's that all tests should be run against, I can get a list from our QA team of all systems we can run these tests against and build a matrix in testrail to qualify the various gpu/processor combos.

**Comment by samcake** [comment]
can you check without HMD first and make sure the test pass  on desktop ?

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9049/app_12814_PR_573f399023eafd625212284f827ea3207f006f76.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9049/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9049/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9049/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9049/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by samcake** [comment]
@qlimnavarro 
Can you confirm that the shadow global activation is enabled on that mac Machine where you don;t see the shadows ?
this is the checkbox in developer/render/Shadows

I m trying to repro the test exactly on a mac before the end of the day maybe....

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Currently when running the scripts in render/shadows/ only the black and white checkerboard appears.  This occurred on both Mac and PC.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/1975016/hifi-log.txt)
[hifi-logMAC.txt](https://github.com/highfidelity/hifi/files/1975017/hifi-logMAC.txt)
screen shot 2018-05-04 at 9 31 46 am
render_shadows_normal_00000
render_shadows_grazing_00000
render_shadows_front_00000
[hifi-log_2018-05-04_08.54.10.txt](https://github.com/highfidelity/hifi/files/1975018/hifi-log_2018-05-04_08.54.10.txt)

**Comment by Zvork** [comment]
Update shadow test in [hifi_test PR #96 ](https://github.com/highfidelity/hifi_tests/pull/96) to take into account non shadow casting background. This is the test that should be used.

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9751/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9751/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9751/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9751/HighFidelity-Beta-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9751/HighFidelity-Beta-Interface-PR12814-573f399023eafd625212284f827ea3207f006f76.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
All 3 of the shadow tests (Front, Grazing, and Normal) all produce the same image. Shadows were enabled in the correct zone and made sure Dev > Render > Shadows was enabled as well. Ran test.js and Autotest.js and both produced similar results. Example screenshot of Windows then Mac posted, below are the rest of the snaps with logs.

c_users_qliem_downloads_high__fidelity test files_hifi_tests-master_hifi_tests-master_tests_engine_render_shadows_front_00000
_testmonster_downloads_hifi_tests-aa69bb4b7cdb89ec31fc20a1ff5fd6b876d5ea17_tests_engine_render_shadows_normal_00000
[Files.zip](https://github.com/highfidelity/hifi/files/2001273/Files.zip)

**Comment by samcake** [comment]
I tried on my own and it was working fine 
i don;t auite understand why you would get that result
it seems to me that there was other zone messing with your lighting environment maybe

**Comment by qlimnavarro** [comment]
Will retest and change various lighting environments for more information.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Shadows look good.

**Comment by samcake** [comment]
double checked on mac too and with Michael
good to go

**Pull request merged**
