### PR TITLE
Crash fixes for avatars without Hips, and web overlays

### PR DESCRIPTION
**Pull request by hyperlogic**
* Crash fix for avatars without "Hips" joints.
* Crash fix for user created web3d overlays

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/6672/Problematic-Avatars

**Comment by hyperlogic** [comment]
QA Test plan for avatar crash:
  * Load the following avatar: http://www.owlboy.com/hf/avatars/owlblock-pug/owlblock-v2-hf.fst
  * Quit interface and restart using the above avatar.
  * You should not crash.
QA Test plan for web overlay crash:
  * Run the following script: [clipboard.js](https://gist.githubusercontent.com/hyperlogic/211dd0887f5da89fc6cea3f28ed526d3/raw/a02c4bba2464db0287528905d4a4428dc8501c8d/clipboard.js)
  * A clipboard should appear containing a web overaly showing the testrail.com website.
  * It should not cause a crash.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2270/HighFidelity-Beta-PR11117-9fdc044ae10d4ae34175169240a4c70bedc5a485.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2270/HighFidelity-Beta-PR11117-9fdc044ae10d4ae34175169240a4c70bedc5a485.exe

**Comment by cain-kilgore** [comment]
# Test Passed
## Avatar Crash
Test | Result
-------- | --------
Load the following avatar | Pass
Quit interface and restart using the above avatar. | Pass
You should not crash. | Pass

## Web Overlay Crash
Test | Result
-------- | --------
Run the following script: clipboard.js | Pass
A clipboard should appear containing a web overaly showing the testrail.com website. | Pass
It should not cause a crash. | Pass

All good here. Though I noticed when your Avatar doesn't have Hips you are able to clip through the floor..

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
