### PR TITLE
BUGZ-1316: Fix crashes in Assets API

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixed:
- Crash if callback undefined in Assets.getAsset().
- Crash if callback undefined in Assets.setBakingEnabled().

Case: https://highfidelity.atlassian.net/browse/BUGZ-1316

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
"invalid callback handler" JavaScript error message is reported to program log (same as before) but Interface no longer crashes afterwards.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21096/HighFidelity-Beta-PR16117-fb818c0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21096/HighFidelity-Beta-Interface-PR16117-fb818c0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21096/HighFidelity-Beta-PR16117-fb818c0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21096/HighFidelity-Quest-Beta-PR16117-fb818c0.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21096/HighFidelity-Beta-PR16117-fb818c0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21096/HighFidelity-Beta-Interface-PR16117-fb818c0.exe

**Pull request merged**
