### PR TITLE
For blocks demo -- Do Not Merge -- no QA

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3165/HighFidelity-Beta-PR11330-3eacb61509040c682ce349f75b6287e091e0fe29.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3169/HighFidelity-Beta-PR11330-3eacb61509040c682ce349f75b6287e091e0fe29.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3169/HighFidelity-Beta-PR11330-3eacb61509040c682ce349f75b6287e091e0fe29.dmg

**Comment by anshuman64** [comment]
Use this to load Google Blocks app: https://hifi-content.s3.amazonaws.com/elisalj/blocks/blocksApp.js

Note - Glass texture does not show properly in HiFi: https://vr.google.com/u/0/objects/7bfwMDtJK4L
Need to find out why

**Pull request closed without merging**
