### PR TITLE
Case 19740: Improve startup times by pre-compiling shaders with splash screen

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19740/Oculus-Performance-on-low-end-AMD-is-too-low

Test plan:
- Test the following on: a high end (i7) machine with an NVIDIA card and a low end (i5) machine with an AMD card.
- Take note of the startup time (time until things besides the skybox render) the first time you run Interface.  In this case, "first time" just means with an empty shader cache.  You can delete your shader cache between runs to replicate a first run.  It's `AppData/Local/High Fidelity <this PR>/Interface/shaders/cache.json`.
- Things should render (an in depth rendering test is not necessary, just make sure you see your avatar and some entities).
- Restart Interface and take note of the startup time.  It should be lower (but maybe not noticeable on a high end machine).
- Depending on how long Interface takes to start in each case, you may see the splash screen.  It will look very similar to the default skybox.  If you are able to see the splash screen, you should still be able to rotate your view/move your head in HMD.  If things load fast enough that you can't see the splash screen...that's great.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15234/HighFidelity-Beta-PR14419-cbe5814.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15234/HighFidelity-Beta-PR14419-cbe5814.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15234/HighFidelity-Beta-Interface-PR14419-cbe5814.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15234/HighFidelity-Beta-PR14419-cbe5814.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15234/HighFidelity-Beta-Interface-PR14419-cbe5814.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15245/HighFidelity-Beta-PR14419-6a9222c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15245/HighFidelity-Beta-Interface-PR14419-6a9222c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15248/HighFidelity-Beta-PR14419-0fccb4c.apk

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15249/HighFidelity-Beta-PR14419-0fccb4c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15249/HighFidelity-Beta-PR14419-0fccb4c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15249/HighFidelity-Beta-Interface-PR14419-0fccb4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15249/HighFidelity-Beta-PR14419-0fccb4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15249/HighFidelity-Beta-Interface-PR14419-0fccb4c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15277/HighFidelity-Beta-PR14419-372f439.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15277/HighFidelity-Beta-Interface-PR14419-372f439.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15460/HighFidelity-Beta-PR14419-1f354f8.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15462/HighFidelity-Beta-PR14419-a38cf17.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15460/HighFidelity-Beta-PR14419-1f354f8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15460/HighFidelity-Beta-Interface-PR14419-1f354f8.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15462/HighFidelity-Beta-PR14419-a38cf17.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15462/HighFidelity-Beta-Interface-PR14419-a38cf17.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15468/HighFidelity-Beta-PR14419-4d621ba.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15468/HighFidelity-Beta-PR14419-4d621ba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15468/HighFidelity-Beta-Interface-PR14419-4d621ba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15468/HighFidelity-Beta-PR14419-4d621ba.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15468/HighFidelity-Beta-Interface-PR14419-4d621ba.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15477/HighFidelity-Beta-PR14419-b249e6a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15477/HighFidelity-Beta-PR14419-b249e6a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15477/HighFidelity-Beta-Interface-PR14419-b249e6a.exe

**Comment by changxc** [comment]
sorry for messing with milestone! this PR is for 77. 
there will be another PR for 76.1 (for oculus submission)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15543/HighFidelity-Beta-PR14419-00eff4f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15543/HighFidelity-Beta-PR14419-00eff4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15543/HighFidelity-Beta-Interface-PR14419-00eff4f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15543/HighFidelity-Beta-PR14419-00eff4f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15543/HighFidelity-Beta-Interface-PR14419-00eff4f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15678/HighFidelity-Beta-PR14419-287878f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15678/HighFidelity-Beta-PR14419-287878f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15678/HighFidelity-Beta-PR14419-287878f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15678/HighFidelity-Beta-Interface-PR14419-287878f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15681/HighFidelity-Beta-PR14419-e5bdf2e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15681/HighFidelity-Beta-PR14419-e5bdf2e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15681/HighFidelity-Beta-Interface-PR14419-e5bdf2e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15681/HighFidelity-Beta-PR14419-e5bdf2e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15681/HighFidelity-Beta-Interface-PR14419-e5bdf2e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15790/HighFidelity-Beta-PR14419-92117d6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15790/HighFidelity-Beta-PR14419-92117d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15790/HighFidelity-Beta-Interface-PR14419-92117d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15790/HighFidelity-Beta-PR14419-92117d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15790/HighFidelity-Beta-Interface-PR14419-92117d6.exe

**Comment by qlimnavarro** [comment]
Pre-Merge Pass

**Pull request merged**
