### PR TITLE
ApplicationOverlay: Fix for gray line at top of HMD UI overlay

### PR DESCRIPTION
**Pull request by hyperlogic**
Use GL_CLAMP_TO_EDGE for wrapMode on overlay texture.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/95473155131515

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea95295e662d36f3c63f3cf67134354b4c5d40cf available at: https://gist.github.com/96d9e0d3481b2ba2bcbe<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7341.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7341.dmg

**Comment by hyperlogic** [comment]
To test:
1. make sure default scripts are running
2. switch to HMD mode
3. look at the face tracking/audio mute button in the upper left corner of the overlay.
4. On the release build you will see a gray line, just above those buttons.  With this PR that line should be gone.

**Comment by AndrewMeadows** [comment]
I confirm: the faint gray line is gone in this PR.

**Pull request merged**
