### PR TITLE
DNM : resetting qaudioinfo on change

### PR DESCRIPTION
**Pull request by amerhifi**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22390/HighFidelity-Beta-PR16469-8f0c996.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22390/HighFidelity-Beta-Interface-PR16469-8f0c996.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22390/HighFidelity-Beta-PR16469-8f0c996.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22390/HighFidelity-Quest-Beta-PR16469-8f0c996.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22390/HighFidelity-Beta-PR16469-8f0c996.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22390/HighFidelity-Beta-Interface-PR16469-8f0c996.exe

**Comment by JeffClinton** [comment]
Pre-merge testing

**Comment by JeffClinton** [comment]
Pre-merge testing paused.  Seeing some crashes when connecting Air Pods on the mac build.
https://share.backtrace.io/api/share/O2KVM1CH7ecCpOg0bNDVO1  NEW
https://share.backtrace.io/api/share/COQvx1S01OkWzYfX3BYsqJ3  EXISTING
https://share.backtrace.io/api/share/W9WBpRwwJeXkXY8YjGHfx21  EXISTING
https://share.backtrace.io/api/share/zvVKNKeW555ZLZ3HXS1tm3  NEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22396/HighFidelity-Beta-PR16469-ef22960.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22396/HighFidelity-Beta-Interface-PR16469-ef22960.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22396/HighFidelity-Beta-PR16469-ef22960.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22396/HighFidelity-Quest-Beta-PR16469-ef22960.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22396/HighFidelity-Beta-PR16469-ef22960.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22396/HighFidelity-Beta-Interface-PR16469-ef22960.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22407/HighFidelity-Beta-PR16469-861eda0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22407/HighFidelity-Beta-Interface-PR16469-861eda0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22407/HighFidelity-Beta-PR16469-861eda0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22407/HighFidelity-Quest-Beta-PR16469-861eda0.apk)

**Pull request closed without merging**
