### PR TITLE
Fixing 2D overlay mouse interaction

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3f034e73b096c7c7144b0f004b062d25b3501f0 available at: https://gist.github.com/5cc22c9a03e0d88d0ecb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d48678f9525bb69d50fb07d8102c80f841605f3 available at: https://gist.github.com/5cc22c9a03e0d88d0ecb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa8979570c56b4bcafc393af4c3c52d32e90ff2d available at: https://gist.github.com/5cc22c9a03e0d88d0ecb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5977.dmg

**Comment by ZappoMan** [comment]
Do we need to handle touch events too? I believe they also have window positions in them.

**Comment by jherico** [comment]
Do we use touch events for 'clicks'?  We just use them for dragging sort of functionality, right?

**Comment by ZappoMan** [comment]
I'm going to merge this, because like you said it doesn't get worse, but it does get better. However... it now exposes the fact that our "mouse to 3D ray computation" is totally broken for oculus mode.

**Pull request merged**
