### PR TITLE
Add a "dominant hand changed" signal

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Run the attached script and change Settings > Avatar > Dominant Hand setting a few times.
Each change should be reported to the program log.

Check that the setting changes are remembered over Interface restarts.

[dominantHandChangeTest.zip](https://github.com/highfidelity/hifi/files/1181821/dominantHandChangeTest.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2077/HighFidelity-Beta-PR11068-c1d179eba102819c43fb4146ef9c0836bfec0551.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2077/HighFidelity-Beta-PR11068-c1d179eba102819c43fb4146ef9c0836bfec0551.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Run the attached script and change Settings > Avatar > Dominant Hand setting a few times. **Pass**
Each change should be reported to the program log. **Pass**

Check that the setting changes are remembered over Interface restarts. **Pass**

**Pull request merged**
