### PR TITLE
Flex and weight IK tuning parameters

### PR DESCRIPTION
**Pull request by hyperlogic**
Added two major features to the IK system
* Each IK chain contains an array of "flex coefficients" which determine how flexible each joint in the chain is.  This is used to prevent the arm chains from exerting undue influence over the spine.
* Each IK chain also contains a dynamic tunable "weight" parameter. This weight is used when each combining each IK chain at the end of each solver iteration.  Typically the head has a higher weight than other IK chains.  Previously this was hard coded, now it is dynamically tunable at run-time via an animVar.

### CODE REVIEW

**Comment by hyperlogic** [comment]
General QA Testing:
  * Inspect avatar animations in desktop mode, and in HMD mode with hand controllers.  Verify there are no regressions.

Vive Puck QA Testing:
  * In general, the spine should be more stable, and less prone to bowing left/right.
  * specifically, When wearing the hips + feet pucks, the chest should not bow to the sides when the hands are alternately raised and lowered while at the sides.  See this input [recording](	https://s3.amazonaws.com/hifi-public/tony/input-recodings/ajt-shoulder-pull.json.gz)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e276d113cf792305df60607479a07307fd3daab available at: https://gist.github.com/86995a173e6fe55bd10c02e08b68441f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-1e276d1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-1e276d1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be7a9a2383aaa1cc9b84537458750d53f48acd4f available at: https://gist.github.com/86995a173e6fe55bd10c02e08b68441f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-be7a9a2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-be7a9a2.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

The handling in Desktop & HMD Both worked well, examined in First Person & Third Person modes, animations seem the same as before, if not slightly better tuned with movement (I find when I stretch my arms length out fully, it doesn't freak out as much as it did before due to my real arm length being slightly longer than the avatar relative to me)

Please let me know anything else I can do/provide to help :)

**Comment by anshuman64** [comment]
Video captures without and with this PR. Notice neck movements.

Without this PR: https://drive.google.com/open?id=0B_nmInIG19-udG42c2YtaHU1VnM
With this PR: https://drive.google.com/open?id=0B_nmInIG19-udkZRRUF2ekExQW8

**Comment by ZappoMan** [comment]
@hyperlogic - Apparently the mac build failed... according to Jenkins with...

```
Undefined symbols for architecture x86_64:
  "AnimInverseKinematics::MAX_FLEX_COEFFICIENTS", referenced from:
      AnimInverseKinematics::IKTargetVar::IKTargetVar(QString const&, QString const&, QString const&, QString const&, QString const&, float, std::__1::vector<float, std::__1::allocator<float> > const&) in libanimation.a(AnimInverseKinematics.o)
      AnimInverseKinematics::IKTargetVar::IKTargetVar(QString const&, QString const&, QString const&, QString const&, QString const&, float, std::__1::vector<float, std::__1::allocator<float> > const&) in libanimation.a(AnimInverseKinematics.o)
      AnimInverseKinematics::IKTargetVar::IKTargetVar(AnimInverseKinematics::IKTargetVar const&) in libanimation.a(AnimInverseKinematics.o)
      AnimInverseKinematics::IKTargetVar::IKTargetVar(AnimInverseKinematics::IKTargetVar const&) in libanimation.a(AnimInverseKinematics.o)
      AnimInverseKinematics::setTargetVars(QString const&, QString const&, QString const&, QString const&, QString const&, float, std::__1::vector<float, std::__1::allocator<float> > const&) in libanimation.a(AnimInverseKinematics.o)
      void std::__1::vector<AnimInverseKinematics::IKTargetVar, std::__1::allocator<AnimInverseKinematics::IKTargetVar> >::__push_back_slow_path<AnimInverseKinematics::IKTargetVar const&>(AnimInverseKinematics::IKTargetVar const&&&) in libanimation.a(AnimInverseKinematics.o)
      std::__1::vector<AnimInverseKinematics::IKTargetVar, std::__1::allocator<AnimInverseKinematics::IKTargetVar> >::__swap_out_circular_buffer(std::__1::__split_buffer<AnimInverseKinematics::IKTargetVar, std::__1::allocator<AnimInverseKinematics::IKTargetVar>&>&) in libanimation.a(AnimInverseKinematics.o)
      ...
  "IKTarget::MAX_FLEX_COEFFICIENTS", referenced from:
      IKTarget::setFlexCoefficients(unsigned long, float const*) in libanimation.a(IKTarget.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 warnings only
```

I'm going to try to kick Jenkins in case this was some kind of a whacky intermittent failure... but it looks like some kind of a mac specific linker issue.

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: be7a9a2383aaa1cc9b84537458750d53f48acd4f available at: https://gist.github.com/86995a173e6fe55bd10c02e08b68441f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-be7a9a2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-be7a9a2.dmg

**Comment by ZappoMan** [comment]
@hyperlogic - definitely seems like a Mac compiler/linker problem.. you'll need to fix that

**Comment by Nex-Pro** [comment]
Does this need testing with Vive pucks ? @hyperlogic

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78dd30f65636d42cb1766d2af299b1092e3adc28 available at: https://gist.github.com/86995a173e6fe55bd10c02e08b68441f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-78dd30f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-78dd30f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0018224fefb72e6c50041effe7b89e676fd2ef8b available at: https://gist.github.com/86995a173e6fe55bd10c02e08b68441f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-0018224.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10471-0018224.dmg

**Pull request merged**
