### PR TITLE
handle AC started before local assignment server

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
This also got some stray commits from #4919 - will pull from upstream to clear those out once that is merged

**Comment by birarda** [comment]
going to test to make sure shared mem changes work as expected on win

**Comment by hifi-gustavo** [comment]
Build console output for commit: bea387af7dc21d76dcd4ea85c157f64e22c842ed available at: https://gist.github.com/fc0abf47768f245f4558<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45daabc86fb279459736f24e7c9d227fe8c50ee5 available at: https://gist.github.com/fc0abf47768f245f4558<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.dmg

**Comment by birarda** [comment]
@sethalves tested this on win - good to go

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6f458eaf14fcd92a215d8c20c7aec054fb43bf5 available at: https://gist.github.com/fc0abf47768f245f4558<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4922.dmg

**Pull request merged**
