### PR TITLE
Logging to help find audio device issue

### PR DESCRIPTION
**Pull request by davidkelly**
We sometimes show duplicate devices in Audio > Devices menu.  But
I cannot reproduce it, so maybe best thing is log timing and contents
of input and output device arrays, to try to run down where the issue
is.

Test Plan: 
smoke test of the working and contents of Audio > Devices menu.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40914d979087db2d787a96c5d7cb3b6f60197dac available at: https://gist.github.com/335ea2b5e198c8a99f00fe6c84008d82<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9078-40914d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9078-40914d9.dmg

**Comment by davidkelly** [comment]
please test

**Comment by davidkelly** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40914d979087db2d787a96c5d7cb3b6f60197dac available at: https://gist.github.com/335ea2b5e198c8a99f00fe6c84008d82<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9078-40914d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9078-40914d9.dmg

**Comment by OmegaHeron** [comment]
Windows 10
QA Pass

I see correct audio device tree with this PR, same as master/rc.  General smoke test passes.

**Pull request merged**
