### PR TITLE
bullet slider constraint

### PR DESCRIPTION
**Pull request by sethalves**
- expose bullet's slider constraint to javascript
- make the "motor" on the hinge constraint work better

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open javascript console and paste:
```javascript
var pos = Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, {x: 0, y: 0.1, z: -2}));

var sliderEntityID = Entities.addEntity({
    name: "slider test",
    type: "Box",
    color: { blue: 128, green: 20, red: 20 },
    dimensions: { x: 0.2, y: 0.2, z: 0.2 },
    position: pos,
    dynamic: true,
    collisionless: false,
    gravity: { x: 0, y: 0, z: 0 },
    lifetime: 120,
    userData: "{ \"grabbableKey\": { \"grabbable\": true, \"kinematic\": false } }"
});

var sliderActionID = Entities.addAction("slider", sliderEntityID, {
    point: { x: -0.5, y: 0, z: 0 },
    axis: { x: 0, y: 1, z: 0 },
    linearLow: 0,
    linearHigh: 0.6,
    tag: "slider test"
});
```
The entity should be able to move only up and down over a range of 0.6 meters.

- paste into the console:
```javascript
var pos = Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, {x: 0, y: 0.1, z: -2}));

var offset = 0.28;
var prevEntityID = null;
for (var i = 0; i < 7; i++) {
    var newID = Entities.addEntity({
        name: "hinge test " + i,
        type: "Box",
        color: { blue: 128, green: 40 * i, red: 20 },
        dimensions: { x: 0.2, y: 0.1, z: 0.2 },
        position: Vec3.sum(pos, {x: 0, y: offset * i, z:0}),
        dynamic: true,
        collisionless: false,
        gravity: { x: 0, y: 0, z: 0 },
        lifetime: 120,
        userData: "{ \"grabbableKey\": { \"grabbable\": true, \"kinematic\": false } }"
    });
    if (prevEntityID) {
        Entities.addAction("slider", prevEntityID, {
            point: { x: 0, y: 0, z: 0 },
            axis: { x: 0, y: 1, z: 0 },
            otherEntityID: newID,
            otherPoint: { x: 0, y: -offset / 2, z: 0 },
            otherAxis: { x: 0, y: 1, z: 0 },
            linearLow: 0,
            linearHigh: 0.6,
            tag: "A/B slider test " + i
        });
    }
    prevEntityID = newID;
}
```
play with the chain and see if it moves as a bunch of linked sliders.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21df08aa8831fbec9bca9c7afe8e9891c5c16813 available at: https://gist.github.com/b0732b00d7c6be9f8d108255d6e422eb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10310-21df08a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10310-21df08a.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21df08aa8831fbec9bca9c7afe8e9891c5c16813 available at: https://gist.github.com/b0732b00d7c6be9f8d108255d6e422eb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10310-21df08a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10310-21df08a.dmg

**Comment by Nex-Pro** [comment]
testing this @sethalves

**Comment by Nex-Pro** [comment]
## PASS

Test 1.
DESKTOP mode.
Vertical movement is constrained to + 0.6M in vertical axis.  **SUCCESS**
Holding ctrl and dragging the cube rotates and horizontally displaces cube but it returns to resting position on release.
HMD mode
With lasers and grab, cube is constrained correctly.  **SUCCESS**
Cube cannot be rotated with double far grab action.  **SUCCESS**

Test 2.
Nice !  **SUCCESS**
works really well. I even managed to near-grab each end block at the same time and use it like a squeeze box.  Only negative thing I could mention is that it doesn't feel like the hands and blocks are connected.  There's that slight laggy ( rubber banding ) sensation.

@sethalves  Good work.  Let me know if this warrants a smoke test.

**Comment by sethalves** [comment]
closing this in favor of https://github.com/highfidelity/hifi/pull/10332

**Pull request closed without merging**
