### PR TITLE
Case 21379: Remove nitpick installer from Linux

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/21379/Remove-nitpick-installer-from-Linux

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17521/HighFidelity-Beta-PR14991-a6ad53e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17521/HighFidelity-Beta-PR14991-a6ad53e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17521/HighFidelity-Beta-Interface-PR14991-a6ad53e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17521/HighFidelity-Beta-PR14991-a6ad53e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17521/HighFidelity-Beta-Interface-PR14991-a6ad53e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17539/HighFidelity-Beta-PR14991-7cf79c1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17539/HighFidelity-Beta-PR14991-7cf79c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17539/HighFidelity-Beta-Interface-PR14991-7cf79c1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17539/HighFidelity-Beta-PR14991-7cf79c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17539/HighFidelity-Beta-Interface-PR14991-7cf79c1.exe

**Comment by NissimHadar** [comment]
Case 21379: remove nitpick installer from Linux

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request merged**
