### PR TITLE
List which contexts each namespace and class is available in

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA  not necessary because no executable code changes.

Do not merge until after https://github.com/highfidelity/hifi/pull/13048 has been merged.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9316/app_13049_PR_2cc3ed6287afbd5df4cb65a6f42f6389671eeabe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9316/HighFidelity-Beta-PR13049-2cc3ed6287afbd5df4cb65a6f42f6389671eeabe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9316/HighFidelity-Beta-Interface-PR13049-2cc3ed6287afbd5df4cb65a6f42f6389671eeabe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9316/HighFidelity-Beta-PR13049-2cc3ed6287afbd5df4cb65a6f42f6389671eeabe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9316/HighFidelity-Beta-Interface-PR13049-2cc3ed6287afbd5df4cb65a6f42f6389671eeabe.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9367/app_13049_PR_1aa28b7f54131eb872affcf1fc66155bcdeb4f06.apk

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9369/app_13049_PR_1aa28b7f54131eb872affcf1fc66155bcdeb4f06.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9369/HighFidelity-Beta-PR13049-1aa28b7f54131eb872affcf1fc66155bcdeb4f06.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9369/HighFidelity-Beta-Interface-PR13049-1aa28b7f54131eb872affcf1fc66155bcdeb4f06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9369/HighFidelity-Beta-PR13049-1aa28b7f54131eb872affcf1fc66155bcdeb4f06.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9369/HighFidelity-Beta-Interface-PR13049-1aa28b7f54131eb872affcf1fc66155bcdeb4f06.exe

**Pull request merged**
