### PR TITLE
cleanup of some warnings

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
@jherico you should double check the display-plugins changes here

**Comment by hifi-gustavo** [comment]
Build console output for commit: 050c733fca0498b7353b12ff289e8d701024b60d available at: https://gist.github.com/82b385e426bc48f8f83f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89e11c49581ff1a03aa525410e1f25afd012ad8b available at: https://gist.github.com/82b385e426bc48f8f83f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 13d2399d826f7c0786c4c7e890c4e7b807f66927 available at: https://gist.github.com/82b385e426bc48f8f83f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40696a048dccb319f790b6eedd05c7cb7db30cad available at: https://gist.github.com/82b385e426bc48f8f83f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca48d32b3565323f82890d4c19e0118f2bc3766f available at: https://gist.github.com/7e8de5e1c24cf198aeea<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5c73b7809d3eec6e9c73094eedd6307c8227fb3 available at: https://gist.github.com/82b385e426bc48f8f83f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5674.dmg

**Pull request merged**
