### PR TITLE
add throttle start and backoff to DS settings

### PR DESCRIPTION
**Pull request by birarda**
- Fix for https://highfidelity.manuscript.com/f/cases/19914/Audio-target-and-backoff-for-throttling-should-be-configurable-from-domain-server-settings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15207/HighFidelity-Beta-PR14417-bb0f046.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15207/HighFidelity-Beta-PR14417-bb0f046.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15207/HighFidelity-Beta-Interface-PR14417-bb0f046.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15207/HighFidelity-Beta-PR14417-bb0f046.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15207/HighFidelity-Beta-Interface-PR14417-bb0f046.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15224/HighFidelity-Beta-PR14417-6daac00.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15224/HighFidelity-Beta-PR14417-6daac00.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15224/HighFidelity-Beta-Interface-PR14417-6daac00.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by birarda** [comment]
build this please

**Comment by qlipdahlin** [comment]
Pause Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15226/HighFidelity-Beta-PR14417-6daac00.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15226/HighFidelity-Beta-PR14417-6daac00.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15226/HighFidelity-Beta-Interface-PR14417-6daac00.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15228/HighFidelity-Beta-PR14417-6daac00.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15228/HighFidelity-Beta-PR14417-6daac00.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15228/HighFidelity-Beta-Interface-PR14417-6daac00.dmg

**Comment by qlipdahlin** [comment]
Resume Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Tested by setting up DS with two users. Tested to be sure audio was working by default. Adjusted start and backoff values to 0.02 and 0.0 and then tested audio where audio was present after server restarted for about 15 seconds before audio was cut off.

Cleared the default values after this and audio worked correctly and for longer than 15 seconds.

Changed backoff target to be larger than start and saw a warning in audio-mixer log that said it was returning to default values (0.9 and 0.44). Audio worked correctly.

Changed start and backoff targets to be less than 0 and greater than 1, audio-mixer log gave error message about returning to default values. Audio worked correctly.

PR Passes.

**Pull request merged**
