### PR TITLE
Update help image for gamepad to include grab and click lasers

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
@AlanZimmerman Is the decreased size OK?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53262023137f29f67590a7c832ea12c250844004 available at: https://gist.github.com/95204e9c21a8c4d5a8b1c449ee505722<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.dmg

**Comment by huffman** [comment]
test this please

**Comment by huffman** [comment]
To test:
 1. Confirm that in the help menu, that the "gamepad" tab includes annotations for the click and grab lasers.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53262023137f29f67590a7c832ea12c250844004 available at: https://gist.github.com/95204e9c21a8c4d5a8b1c449ee505722<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.dmg

**Comment by cozza13** [comment]
@huffman build fail

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53262023137f29f67590a7c832ea12c250844004 available at: https://gist.github.com/95204e9c21a8c4d5a8b1c449ee505722<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8932-5326202.dmg

**Pull request merged**
