### PR TITLE
handle sequence number from reliably sent adds in OctreeEditPacketSender

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5740/app_12024_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5740/HighFidelity-Beta-PR12024-1a6546999aeead1a89ac89bccf97b358c661a61d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5740/HighFidelity-Beta-PR12024-1a6546999aeead1a89ac89bccf97b358c661a61d.dmg

**Comment by birarda** [comment]
#### Test Plan

1. Run Interface from this PR. Connect to dev-welcome.
2. Rez an entity. Edit an entity.
3. You should not see "Unexpected sequence number passed to" in the log.
4. Repeat this test with Interface from master. You should see the above in your log when you perform the edit.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Run Interface from this PR. Connect to dev-welcome. | 👍 
Rez an entity. Edit an entity. | 👍 
You should not see "Unexpected sequence number passed to" in the log. | 👍 
Repeat this test with Interface from master. You should see the above in your log when you perform the edit. | 👍 

### Master
`[12/22 19:17:08] [DEBUG] [hifi.networking] Unexpected sequence number passed to SentPacketHistory::packetSent()! Expected: 1753 Actual: 1754`

### 12024
theres-nothing-here-gif

**Pull request merged**
