### PR TITLE
if needed, set queryAACube when dimensions are updated

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that caused just-uploaded model entities to not immediately appear

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/99753934970045

**Comment by sethalves** [comment]
to test:
- pick a large model such at terrain
- use edit.js to create a new model-entity
- confirm that the thing is immediately visible (after loading the model from the network)

**Comment by hifi-gustavo** [comment]
Build console output for commit: f611d8f747f61347db4429ee8a84bc2b81b6cb70 available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a4dad8e51a1d04a33325de537c7485baea0ab4e available at: https://gist.github.com/016ae675a510501b98ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ad15f75682ea97dc98f08a09fe6b40b7438d517 available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1e8706b1da6eaee6396a6174c36bcb70ffd1dff9 available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f05d576cc5e5abff9d4632c40345c8fb653d1be available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 01659cf93b49cf511db242841ff4500fd9744bbf available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by cozza13** [comment]
I tested this

**Comment by hifi-gustavo** [comment]
Build console output for commit: 908481d5d4011c9365229668e66275c26c101ed0 available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5292e537ea5f5fb21f4669f681e697989c8b391d available at: https://gist.github.com/2b1eabc94618fc131115<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7327.dmg

**Pull request merged**
