### PR TITLE
Work in progress check-in for bug #21445 "Improve Thrid Person Avatar…

### PR DESCRIPTION
**Pull request by rickdaniels**
… Gaze"

The way desktop 3rd person control of the Avatar head works currently:
MyAvatar::updateOrientation() takes controler input and calculates
delta rotation for the avatar (yaw for the whole body, pitch for the head).
Application::paintGL() then takes the orientation of the avatar's head
and applies that to the camera.

To allow the avatar and camera to look at different things in this mode,
I added vars and accessors for the delta rotational angles (pitch and yaw)
calculated in MyAvatar::updateOrientation() so that Application::paintGL()
could use them to rotate the camera directly instead of being slaved to
the avatar head. (although to avoid the problem of not being able to
initialize the camera's orientation with the avatar if the game starts in
3rd Person mode, I wound up still slaving the camera's yaw to the avatar)

I then modified the 3rd person desktop case in MyAvatar::updateOrientation()
to cast a forward ray from the center of the camera and have the avatar head look
at the point of intersection (if there is one)

In practice, this produces very similar head rotation behavior to the
existing behavior, only differing in the case where the 3rd person camera
isn't centered on the avatar, but even then it's not a huge difference.

### CODE REVIEW

**Comment by PhilipRosedale** [comment]
This is the kind of thing we need a test for, btw.    An automated test could evaluate if when the camera had a certain object centered in the view, the avatar is looking at that object, as expected.

**Comment by themelissabrown** [comment]
@PhilipRosedale can you evaluate the work on this and let me know if it accomplishes what you're hoping for?

**Comment by rickdaniels** [comment]
The test procedure is to just look around in desk top 3rd person avatar centered and uncentered modes. There's not a lot of difference, since the avatar is looking at the point of the ray intersection on whatever object the ray hits. When I was testing the independent head tracking locally, I had hacked in a hard coded world position to look at, so if the avatar is given a point in the world to look at it will, but the method of looking at the point of intersection cast from the center of the camera produces very nearly the same results as the current behavior.

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2246/HighFidelity-Beta-PR11102-82b68de35164492151f3322a0bfa498f69c3c545.dmg

**Comment by themelissabrown** [comment]
build this please

**Comment by Nex-Pro** [comment]
Keeps checking for windows build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2249/HighFidelity-Beta-PR11102-82b68de35164492151f3322a0bfa498f69c3c545.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2256/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2256/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2269/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2269/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.dmg

**Comment by Nex-Pro** [comment]
Woot we got a windows build !

**Comment by Nex-Pro** [comment]
I don't see any noticeable difference using this vs. dev.  I switched between this and dev a few times. Switched centering on and off a few times in each. Maybe we need more specific notes in order to understand what is required.

**Comment by themelissabrown** [comment]
build this please

**Comment by themelissabrown** [comment]
@Nex-Pro That's essentially the argument- even changing the code to reflect the work the WL task asked for, it didn't really change much. I think @PhilipRosedale needs to review and give feedback.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2304/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2304/HighFidelity-Beta-PR11102-6bba577742c8d8aac9853c84f36c41d3c99669de.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2318/HighFidelity-Beta-PR11102-2bd3d1af2d148faa42270c9f5bcf128d01fadb75.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2318/HighFidelity-Beta-PR11102-2bd3d1af2d148faa42270c9f5bcf128d01fadb75.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2323/HighFidelity-Beta-PR11102-41946f16cf4a9b45a32a6e182213d58eec8588c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2323/HighFidelity-Beta-PR11102-41946f16cf4a9b45a32a6e182213d58eec8588c7.exe

**Comment by themelissabrown** [comment]
@Nex-Pro specifically try this: Go into 3rd person mode and look at (center in view) a small cube that is right in front of and to one side your avatar.  A second person should look at where your avatars eyes are looking.  If this work is done correctly, the avatar will look at the cube.  In production, the avatar will look parallel to the direction your camera is looking.

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
Test this please

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2879/HighFidelity-Beta-PR11102-41946f16cf4a9b45a32a6e182213d58eec8588c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2879/HighFidelity-Beta-PR11102-41946f16cf4a9b45a32a6e182213d58eec8588c7.exe

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
@themelissabrown Tested this with Xaos and compared it to latest dev.

We never see the avatar looking at the cube.

**Comment by Nex-Pro** [comment]
@themelissabrown @rickdaniels can we get an upstream merge.

**Comment by themelissabrown** [comment]
@rickdaniels the end result we;re looking for is: Go into 3rd person mode and look at (center in view) a small cube that is right in front of and to one side your avatar. A second person should look at where your avatars eyes are looking. If this work is done correctly, the avatar will look at the cube. In production, the avatar will look parallel to the direction your camera is looking.

**Comment by themelissabrown** [comment]
No significant changes seen with any approach. Will revisit at a later date.

**Pull request closed without merging**
