### PR TITLE
Fix injector looping issues when using audio that isn't a multiple of the sample size

### PR DESCRIPTION
**Pull request by huffman**
This fixes an issue on hq where looped audio would go static-y when looping when the audio data size was not a multiple of its sample size.

### CODE REVIEW

**Comment by huffman** [comment]
To test:
Run this ac script on your domain: https://gist.githubusercontent.com/huffman/f11b0705ccd09a766e47/raw/54f63d494fee048806aaffb3c9a4a25ca983b9ca/testLoopingAudio.js
Go into your server, here the audio
Wait for audio to loop (3 minutes)
Observe that the audio does not sound static-y

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e5eec55da1db5ca64daa7c152e195a231f9b6d9 available at: https://gist.github.com/27f5e0888e1c105d4745<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6958.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6958.dmg

**Comment by birarda** [comment]
Checked this out locally, tested with script from Ryan that previously had the issue.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ec201b85e4a6de5b985b9e689d669ba18b918ec available at: https://gist.github.com/27f5e0888e1c105d4745<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6958.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6958.dmg

**Pull request merged**
