### PR TITLE
Beta Release 49 - Includes up to Developer Release 6915

### PR DESCRIPTION
**Pull request by cozza13**
- **Update to using Qt 5.9.1 and Visual Studio 2017.**
 - Avoid crash in soft-attachment code 
 - Allow the tablet to be closed when a modal dialog is open. 
 - String pass on Chat.js 
 - Implement Create button disabled state (details below). 
 - Add a scale slider for avatar size 
 - Prioritize file:// requests over http://
 - Added option in the installer for a clean install
 - Fix tablet scripting interface setting its internal state to home when switching between toolbar and tablet mode 
 - Smooth IK when trackers are disabled / enabled. 
 - HoverOverlayInterface skeleton
 - Record total number of ATP/HTTP/File bytes downloaded during session 
 - Faster EntityItem lookup by EntityItemID 
 - Trying new tablet spawn position. 
 - Allow user move the cursor with the mouse for the add model URL textbox 
 - Create/Destroy Hover Overlays using hand controller lasers 
 - Fix Avatar/Audio Mixer crash 
 - Fixed not being able to delete avatar entities when switching domains
 - Use timer instead of dedicated thread to tick AC scripted avatar audio 
 - Fixed not being able to load a script url that has a white space 
 - Trying to resolve QML / Audio deadlocks 
 - Get marketplaceID into imported entities 
 - **Camera control app https://github.com/highfidelity/hifi/pull/10574**
 - Fix broken debug build 
 - Do not show lasers when editing in 2D mode. 
 - AC shutdown info + PPID watcher on Unix 
 - Fixed another instance of the tablet getting stuck on the help screen 
 - Fix potential data corruption in the FileCache
 - Fix noise reduction checkbox not always working  
 -  Add vertex color support for OBJ files. 
 - Update CONTRIBUTING.md 
 - Update sit script
 - Fix debug builds startup crash 
 - Address #21402 Added a handler to Sit.js script for the onLoadComplete
 - You can now properly grab and move the tablet in third person  
 - Save JS "Console..." history across sessions 
 - fix create tab load on OS X 
 - Change default mouse speeds for avatar 
 - Fix for audio deadlock & audio device selection
 - Fix Parent Joint in edit js
 - entitySelectionTool: use multiarg findRayIntersection instead of editOverlay. 
 - Fixed bug: Disconnected domain (no access token present) is unnecessarily hitting /api/v1/user/friends 
 - Add a "Dominant Hand" setting
 - Gravity Script

### CODE REVIEW

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2045/HighFidelity-Beta-PR11047-7e474202bdbbc7b03ed378edff100ccaf7c674be.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows2016/2049/HighFidelity-Beta-PR11047-7e474202bdbbc7b03ed378edff100ccaf7c674be.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2049/HighFidelity-Beta-PR11047-7e474202bdbbc7b03ed378edff100ccaf7c674be.dmg

**Comment by marko8904** [comment]
Looks like OS X produces crashing builds with 5.9.1. Switching OS X builds to use 5.6.2. build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2057/HighFidelity-Beta-PR11047-7e474202bdbbc7b03ed378edff100ccaf7c674be.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2057/HighFidelity-Beta-PR11047-7e474202bdbbc7b03ed378edff100ccaf7c674be.exe

**Pull request merged**
