### PR TITLE
Change emitShouldTrail to emitterShouldTrail.

### PR DESCRIPTION
**Pull request by MidnightRift**
Info
- Can be tested by a single person.

# QA

## Setup
- Install the Build that is generated by this PR.

## Steps - One Person

| | Steps | Expected results |
| --- | --- | --- |
| 1. | Create a new Particle entity  | You should have the default particles in front of you|
| 2. | In the particleExplorer windows make sure Emitter Should Trail is an option and checked | Emitter Should Trail Is checked|
| 2. | In the particleExplorer Cexport the properties and make sure  emitterShouldTrail is in it and set to true |  emitterShouldTrail is true and exists in the exported properties |

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2613/HighFidelity-Beta-PR11216-5f162c03520428b5ac829be5a06ae9748288b387.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2617/HighFidelity-Beta-PR11216-5f162c03520428b5ac829be5a06ae9748288b387.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2617/HighFidelity-Beta-PR11216-5f162c03520428b5ac829be5a06ae9748288b387.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Create a new Particle entity | Pass
You should have the default particles in front of you | Pass
In the particleExplorer windows make sure Emitter Should Trail is an option and Emitter Should Trail Is checked  | Pass
In the particleExplorer Cexport the properties and make sure emitterShouldTrail is in it and set to true | Pass

All good from here!

**Pull request merged**
