### PR TITLE
Blocks (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by elisa-lj11**
Can drag zip folder downloaded from Blocks into Interface and it will auto-add to world

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by misslivirose** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2012/HighFidelity-Beta-PR11059-bacd839d432fb525610319e856ebc07c9f604f62.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2095/HighFidelity-Beta-PR11059-25d4d4dc93fb4c099833299edbec932d702ae7a5.exe

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2179/HighFidelity-Beta-PR11059-25d4d4dc93fb4c099833299edbec932d702ae7a5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2204/HighFidelity-Beta-PR11059-c03c1c80e12909e45238d22dd99f0200f50e53f7.exe

**Pull request closed without merging**
