### PR TITLE
Working on text rendering overlays

### PR DESCRIPTION
**Pull request by jherico**
This moves the rendering of 2D text overlays into the QML rendering system, removing the need for any GL or for dual 3D / 2D text rendering pipelines with lots of shared code.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89faf85ad9e1c0ab3fae240d9409077975a37f57 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by ZappoMan** [comment]
Does this radically change the look of the text? Does it impact performance?

**Comment by jherico** [comment]
It slightly alters the font.  We may be able to find a font that's a closer match if it's important.  

original look:  
image

new look:
image

**Comment by ZappoMan** [comment]
How does it work as far as smoothing with up-close for things in world? Aren't you replacing the behavior for rendering text entities too? And avatar display text... basically all text in the system right?

What about performance?

**Comment by jherico** [comment]
As for performance, it should improve it.  text overlays are no longer part of the primary OpenGL pass.  QML offers a couple of advantages...  it only generates a new textures if something has changed in the QML scene (so as long as the QML contents remain static, the rendering load is 0).  Additionally, we'll be able to put QML rendering and main scene rendering on different threads, so even when QML does generate a new texture, it's impact on main scene rendering should still be 0.

**Comment by jherico** [comment]
TextEntities and things like the avatar nameplate are using TextRenderer3D.  I did some refactoring on that to move some classes out of the main TextRenderer3D.cpp and into their own files, but its otherwise unchanged.

**Comment by jherico** [comment]
Full image showing nameplates and a text entity.

image

**Comment by hifi-gustavo** [comment]
Build console output for commit: ae10d5814211f2f62cdefbd35bee8a76e11fec47 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e6e9f017c0d848c4c0a244f29a3a1d07544579c1 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e32bfb85e5a698ef2e83dbc8b773764d8664401 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by ZappoMan** [comment]
As far as I can tell this PR makes the whole overlays not rendered issue worse on the mac. Can you confirm? Also,  on my mac (non-retina) display the text for the users.js is really really small. Much smaller than before.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5e0298f8d07692fe940a5a75c4c4c5f8fc10658 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f998e5d28a89f8dc6772e56b9063282a7290d8e available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by ZappoMan** [comment]
still squished even with latest build...

screen shot 2015-07-17 at 1 53 56 pm

**Comment by jherico** [comment]
actually this made it worse on windows too... somehow.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 24643ca282f2d4a9c88125b4d2a3c3fba1460cff available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 914b47069b34d2f116fa6df996fcb710f2110d74 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3bfa8aae0baa8b3544f2f1ff8661e6b746285b06 available at: https://gist.github.com/018b6018193b51905666<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5349.dmg

**Pull request merged**
