### PR TITLE
allow avatar data to use full segment size

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9173/HighFidelity-Beta-PR12999-f3f29bb6611146319b3e9860ccf10cb052014314.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9173/HighFidelity-Beta-Interface-PR12999-f3f29bb6611146319b3e9860ccf10cb052014314.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9173/HighFidelity-Beta-PR12999-f3f29bb6611146319b3e9860ccf10cb052014314.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9173/HighFidelity-Beta-Interface-PR12999-f3f29bb6611146319b3e9860ccf10cb052014314.exe

**Comment by AndrewMeadows** [comment]
Needs test plan, I think.  I'm not sure what that plan would look like: How to make avatars that will pack too many bytes when calling `AvatarData::toByteArray()`?

**Comment by birarda** [comment]
### Test Plan

With this PR, connect to a server running latest master. Connect with at least two clients. Confirm that you see the other avatar and that you see expected updates to the other avatar (position changes, joint changes, etc.)

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10562/HighFidelity-Beta-PR12999-f3f29bb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10562/HighFidelity-Beta-PR12999-f3f29bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10562/HighFidelity-Beta-Interface-PR12999-f3f29bb.dmg

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Tested with a Sandbox running Master 8423. Rift and Vive both running same client and then Vive running same Master build saw no issues with avatar motions, joints, etc coming through as expected.

**Pull request merged**
