### PR TITLE
Ignore Web entities and web overlays when in interstititial screen.

### PR DESCRIPTION
**Pull request by danteruiz**
Fix the issue of web overlays blocking the interstitial overlay button 

Fixes this issue - https://highfidelity.manuscript.com/f/cases/19286/Web-entities-block-lasers-from-interstitial-page-Go-To-TheSpot-abort-button

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13783/HighFidelity-Beta-PR14180-296ea8a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13783/HighFidelity-Beta-PR14180-296ea8a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13783/HighFidelity-Beta-Interface-PR14180-296ea8a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13783/HighFidelity-Beta-PR14180-296ea8a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13783/HighFidelity-Beta-Interface-PR14180-296ea8a.exe

**Comment by danteruiz** [comment]
Test plan
1) In VR, go to a domain which causes the interstitial loading screen to appear for at least a few seconds
2) Place a web entity in front of the spawn point
3) Go to a different domain
4) Return to the first domain
5) Attempt to click the "Go To TheSpot" abort button
6) Laser should not intersect with placed web entity and you should be able to use the button.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13786/HighFidelity-Beta-PR14180-a47a1c0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13786/HighFidelity-Beta-PR14180-a47a1c0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13786/HighFidelity-Beta-Interface-PR14180-a47a1c0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13786/HighFidelity-Beta-PR14180-a47a1c0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13786/HighFidelity-Beta-Interface-PR14180-a47a1c0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13849/HighFidelity-Beta-PR14180-fa6b301.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13849/HighFidelity-Beta-PR14180-fa6b301.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13849/HighFidelity-Beta-Interface-PR14180-fa6b301.dmg

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14001/HighFidelity-Beta-PR14180-fa6b301.apk

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14007/HighFidelity-Beta-PR14180-fa6b301.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14007/HighFidelity-Beta-PR14180-fa6b301.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14007/HighFidelity-Beta-Interface-PR14180-fa6b301.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14007/HighFidelity-Beta-PR14180-fa6b301.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14007/HighFidelity-Beta-Interface-PR14180-fa6b301.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Inconclusive @conklin94122 

The defect fixed by this PR is that web entities were blocking the "Go To TheSpot" button. However, this is only reproducible after a different defect is fixed, in which ALL nearby entities fail to collide with the laser after entering through an interstitial page. That bug would be fixed by PR14161, which is not yet merged.

Since no nearby entities, including web entities, collide with the laser at any point, it isn't possible to verify that this bug is fixed until after PR14161 is merged. At the moment, this PR's behavior is no different from master (9450).

image

**Comment by wayne-chen** [comment]
merged into PR #14249.

**Pull request closed without merging**
