### PR TITLE
raise avatar 1 meter when stuck

### PR DESCRIPTION
**Pull request by sethalves**
- if the avatar spends too many frames with many collision points, assume it's stuck and raise it up 1 meter

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22496b564fff557e8cc2f1c94d861d7e2440c3f3 available at: https://gist.github.com/ed93ff0e93495d70a4d12f58430b109d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-22496b5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-22496b5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc4a8d5dbe061a391d714710cdd96f4eee7785d0 available at: https://gist.github.com/ed93ff0e93495d70a4d12f58430b109d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-bc4a8d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-bc4a8d5.dmg

**Comment by sethalves** [comment]
to test:
- put avatar in situations where it would have gotten stuck and started shaking
- generally move around and make sure this mechanism doesn't incorrectly fire too often

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1350/Get-stuck-in-ground-on-changing-desktop-Vive

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc4a8d5dbe061a391d714710cdd96f4eee7785d0 available at: https://gist.github.com/ed93ff0e93495d70a4d12f58430b109d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-bc4a8d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8455-bc4a8d5.dmg

**Comment by Nex-Pro** [comment]
#### FAIL

I thought of a simple test for this and made some geometry representative of a less than good collision hull.

I placed these blocks https://dl.dropboxusercontent.com/u/96759331/8455blocks.JSON

and tp'd to the approx center of the lower one. Doing so triggered sufficient shaking and flickering to probably induce an epileptic fit!

**Comment by sethalves** [comment]
andrew has plans that will offer a better solution than this.  closing this for now.

**Comment by ZappoMan** [comment]
actually closing this.

**Pull request closed without merging**
