### PR TITLE
Stop the menu from breaking on leaving HMD mode

### PR DESCRIPTION
**Pull request by jherico**
Right now if you enter and then leave HMD mode, the menu breaks.  This appears to be because the logic in Application::setFullscreen changes behavior based on whether 'vr enabled' is checked.  However the HMD tools dialog disables fullscreen and *then* disables VR mode, causing the problem.  

This is a simple first pass fix that corrects the problem by reversing the order of those operations in the HMD tools dialog.  

Additionally, I'm adding code that disables the menu fiddling altogether on OSX, because the OSX mechanism for application menus in fullscreen precludes the need for any effort.

### CODE REVIEW

**Comment by jherico** [comment]
Testing advice:  old code path should erroneously hide the menu after you enter and then leave VR mode.  New code should have the menu visible after you leave VR mode.  There may still be a bug involving a visible fullscreen menu on Win32 systems (and maybe linux systems) when you enter VR mode, but I can't test this at the moment.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a757a4b6e530ec8de4e9abcd2e570c584426a27 available at: https://gist.github.com/0919a83d8db6613983b3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4584.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4584.dmg

**Comment by PhilipRosedale** [comment]
@cozza13 Do you think you could test this one on win/mac with HMD?

**Comment by cozza13** [comment]
@PhilipRosedale @jherico , I tested this on PC and MAC. On PC it works. On the mac I am unable to enter VR mode.

**Comment by jherico** [comment]
will test the mac experience again.  @cozza13 how are you attempting to enter VR mode?  HMDTools dialog?

**Comment by cozza13** [comment]
@jherico I updated to 5.0.1 and everything worked

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1a1157df963c702324b6b77442f73e7cee6c8e7 available at: https://gist.github.com/0919a83d8db6613983b3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4584.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4584.dmg

**Pull request merged**
