### PR TITLE
8341 Fix Clicking on username in PAL Nearby tab teleports you on top of them.

### PR DESCRIPTION
**Pull request by Delanir**
This teleport tool was placing the user on top of the target avatar.
Fix: Corrected the target place for the teleportation.

REPRODUCE:
1. Click a user in PAL (default Nearby tab), or their glowing orb. 
2. Username will be highlighted in orange. 
3. Click the blue text of the username.
Previous behaviour:
4. Observe if you teleport on top of/inside of the user's avatar.
Expected behaviour:
4. You are teleported to a location roughly 2m in front of the other user's avatar.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5636/HighFidelity-Beta-PR11985-c8e2da1effd5f0e57ed8777c5fb1e7318a9a1485.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5636/HighFidelity-Beta-PR11985-c8e2da1effd5f0e57ed8777c5fb1e7318a9a1485.exe

**Comment by Nex-Pro** [comment]
Testing Win10

**Comment by Nex-Pro** [comment]
### PASS

Works fine. Thanks @Delanir

**Comment by changxc** [comment]
@Delanir Delanir could you please recreate this based on RC 61, so we can merge it into RC 61 please?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5646/HighFidelity-Beta-PR11985-f85fa5ef3fbc9d6c980a26bb9097fe52cd209064.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5646/HighFidelity-Beta-PR11985-f85fa5ef3fbc9d6c980a26bb9097fe52cd209064.exe

**Comment by Nex-Pro** [comment]
@thoys Ryan asked for another test on this. Is that confirmed ?

**Comment by RyanDowne** [comment]
I am going to close this PR for now. We are looking at another approach to solve the issue and will address in RC62.

**Pull request closed without merging**
