### PR TITLE
case dev-2663: Adding safeguard in case device list is empty

### PR DESCRIPTION
**Pull request by amerhifi**
https://highfidelity.atlassian.net/browse/DEV-2663

This one may be hard to reproduce but Andrew ran into this scenario. Unless his headphones are  plugged in seems like the device list is empty. this pr adds a safeguard to make sure we are enumerating an object in a populated list.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by amerhifi** [comment]
build this please

**Comment by amerhifi** [comment]
build this please

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22465/HighFidelity-Beta-PR16481-3a76416.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22465/HighFidelity-Quest-Beta-PR16481-3a76416.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22465/HighFidelity-Beta-PR16481-3a76416.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22465/HighFidelity-Beta-Interface-PR16481-3a76416.exe

**Comment by amerhifi** [comment]
build this please

**Comment by amerhifi** [comment]
build this please

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22469/HighFidelity-Beta-PR16481-3a76416.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22469/HighFidelity-Quest-Beta-PR16481-3a76416.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22469/HighFidelity-Beta-PR16481-3a76416.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22469/HighFidelity-Beta-Interface-PR16481-3a76416.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22470/HighFidelity-Beta-PR16481-35065cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22470/HighFidelity-Quest-Beta-PR16481-35065cf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22470/HighFidelity-Beta-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22470/HighFidelity-Beta-Interface-PR16481-35065cf.dmg

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22477/HighFidelity-Beta-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22477/HighFidelity-Beta-Interface-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22477/HighFidelity-Beta-PR16481-35065cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22477/HighFidelity-Quest-Beta-PR16481-35065cf.apk)

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22478/HighFidelity-Beta-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22478/HighFidelity-Beta-Interface-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22478/HighFidelity-Beta-PR16481-35065cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22478/HighFidelity-Quest-Beta-PR16481-35065cf.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22492/HighFidelity-Beta-PR16481-35065cf.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22492/HighFidelity-Quest-Beta-PR16481-35065cf.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22492/HighFidelity-Beta-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22492/HighFidelity-Beta-Interface-PR16481-35065cf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22492/HighFidelity-Beta-PR16481-35065cf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22492/HighFidelity-Beta-Interface-PR16481-35065cf.exe

**Pull request merged**
