### PR TITLE
undo mistaken change of setting name

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34deba7fffc294d27995002bc6e1821a1e95498d available at: https://gist.github.com/0c5b3232bf9a3bfcb6cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4817.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4817.dmg

**Comment by ZappoMan** [comment]
So I'm totally confused... how did we fix the preferences bug? If this was a typo? The other bug fix (related to zone scaling) wouldn't have explained why the 600 in prefs would randomly change to 60 in the prefs... was there some other PR that fixed that? I can't repro that problem anymore... so I assume it's fixed, I just don't recall seeing a PR that would have fixed that.

**Comment by sethalves** [comment]
I believe that the code that found the size of the domain was returning a ratio (in my case it was producing a box from 0,0,0 to 1,1,1 and that was being fed into code that decided if that domain was intersecting the view.  That code was expecting units of meters.  If it wasn't intersecting, it was given 0 bandwidth, which was then adjusted up to 60 and then later saved in the preferences?  I'm still confused though, because it seems like the desired 600 is divided between the number of visible jurisdictions.

Maybe it currently works until you have more than one jurisdiction?  Maybe there's another problem where the value given to setMaxOctreePacketsPerSecond is overwriting what's in preferences and shouldn't be?

**Comment by ZappoMan** [comment]
I don't think that explains it Seth, I can see how the jurisdiction/domain size/scaling issue might have caused a misallocation of PPS... but there's no code that would have saved that back into the preferences... and the original repro case was that the 600 would be in the preferences unless/until you opened up the preferences at least once. But the jurisdiction pps allocation logic would happen even if you never opened up preferences.

**Comment by sethalves** [comment]
We talked in slack for a while.  This:

_octreeQuery.setMaxOctreePacketsPerSecond(perUnknownServer);
           } else {
               _octreeQuery.setMaxOctreePacketsPerSecond(0);
           } 

in Application.cpp is wrong.  We'll have to study some more to know the correct fix.  Regardless, if you only have one jurisdiction, it seems to be accidentally working.  This PR should still be merged, I think.

**Pull request merged**
