### PR TITLE
Fix warnings on OS X

### PR DESCRIPTION
**Pull request by Atlante45**
@kencooke Can you confirm this doesn't break your code, this shows warning on OS X?

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46f0e63264ff28ae701f6328c5b8f7dd081e4cf2 available at: https://gist.github.com/b0f9ed79a73cdd09e9aa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb758ca6b4256391a68b2d603b2a8e21854483e9 available at: https://gist.github.com/b0f9ed79a73cdd09e9aa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.dmg

**Comment by Atlante45** [comment]
This PR, and @kencooke's #6546 PR will bring the warning on OS X down to 0. Whoop, whoop!

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb40f5e263106c99dc5f708678b762d16263870d available at: https://gist.github.com/b0f9ed79a73cdd09e9aa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a455cb880f0d0571f9590f2d4012884f6bd0e5a9 available at: https://gist.github.com/b0f9ed79a73cdd09e9aa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.dmg

**Comment by kencooke** [comment]
Sorry bout that, didn't see this warning.  Your fix looks great.  Thanks!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07387ab8c0a7d4240f99f3b13ad7d99b3510ddb9 available at: https://gist.github.com/b0f9ed79a73cdd09e9aa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6540.dmg

**Pull request merged**
