### PR TITLE
Case 21160: Tablet does not properly resize when scaling avatar.

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.manuscript.com/f/cases/21160/Tablet-does-not-properly-resize-when-scaling-avatar

### CODE REVIEW

**Comment by danteruiz** [comment]
note: tablet flashing is not completely fix, but it happens very less often then before

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17737/HighFidelity-Beta-PR15056-c22011e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17737/HighFidelity-Quest-Beta-PR15056-c22011e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17737/HighFidelity-Beta-PR15056-c22011e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17737/HighFidelity-Beta-Interface-PR15056-c22011e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17737/HighFidelity-Beta-PR15056-c22011e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17737/HighFidelity-Beta-Interface-PR15056-c22011e.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17755/HighFidelity-Beta-PR15056-a789fb5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17755/HighFidelity-Quest-Beta-PR15056-a789fb5.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17755/HighFidelity-Beta-PR15056-a789fb5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17755/HighFidelity-Beta-Interface-PR15056-a789fb5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17755/HighFidelity-Beta-PR15056-a789fb5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17755/HighFidelity-Beta-Interface-PR15056-a789fb5.exe

**Pull request merged**
