### PR TITLE
DNM - Test build to help determine cause of MBP clicking issues

### PR DESCRIPTION
**Pull request by Triplelexx**
I noticed some comments regarding issues for MBP users getting the UI to show.
This build might resolve the issue, but would need further attention before merging.

It needs testing to confirm that this is the cause of the issue. 
Further information is in the commit description.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by davidkelly** [comment]
ok to test

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bb45cff85f26556984b761ebe3c4e2d994a85dd available at: https://gist.github.com/443de6e74caab58a270a5610cf635a2b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9678-1bb45cf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9678-1bb45cf.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Tested on MAC.  Right-clicking mouse pad was a failure to trigger UI for tablet.  Additionally I connected a standard USB mouse and it failed as well.

**Pull request closed without merging**
