### PR TITLE
FB18573 - Other avatars' avatar entities may appear to be successfull…

### PR DESCRIPTION
**Pull request by ElderOrb**
…y deleted until edited

note: partially revert commit 888f2f64a5971b18c0dbcdac2b15d83c14deac45 / "Merge pull request #10981 from druiz17/bug/delete-avatar-entity

https://highfidelity.manuscript.com/f/cases/18573/

**Test plan**

1) Go to a domain with another tester
2) Both users import or create avatar entities
3) Delete the other user's avatar entity
4) Ensure entity wasn't deleted

Repeat 3/4 five times.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13590/HighFidelity-Beta-PR14135-84c3725.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13593/HighFidelity-Beta-PR14135-9cf94c9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13593/HighFidelity-Beta-PR14135-9cf94c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13593/HighFidelity-Beta-Interface-PR14135-9cf94c9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13593/HighFidelity-Beta-PR14135-9cf94c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13593/HighFidelity-Beta-Interface-PR14135-9cf94c9.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15094/HighFidelity-Beta-PR14135-9cf94c9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15094/HighFidelity-Beta-PR14135-9cf94c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15094/HighFidelity-Beta-Interface-PR14135-9cf94c9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15094/HighFidelity-Beta-PR14135-9cf94c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15094/HighFidelity-Beta-Interface-PR14135-9cf94c9.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Other user's avatar entities could not be deleted, temporarily or otherwise

**Pull request merged**
