### PR TITLE
DO NOT MERGE: Switch to using an RGB10_A2 buffer for normals.

### PR DESCRIPTION
**Pull request by Geenz**
RGBA8 causes slight banding artifacts with normals, which reproduces in shading in most cases.  These subtle discontinuities may not seem like much, but after switching to RGB10_A2, you quickly notice that some objects will seem smoother than before - especially with specular shading and environment maps.

Ideally, you would want RGBA16F, however given the nature of HiFi and VWs like it you'll want something that fits within 32bpp.  The extra two bits can be used for stuff like masking objects with special lighting models in the deferred renderer.

Hopefully I extended everything appropriately - you'll have to forgive some of the fudging with byte count, and defaulting to R8 and R8UI.  OpenGL doesn't have support for 10-bit scalar images - perhaps it would be better off switching to Q_UNREACHABLE?

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9698a0858ae9511f57eb02ad3f7e6fa20601c4cf available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d21612da2160d9beb84734ac97998f35b6468d10 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by Geenz** [comment]
This may end up growing in scope a bit to include a specular buffer.  I have to wonder why specular is only considered to be metallic or not + roughness - there's so much more you can do when you have a specular buffer its self.  What's the rationale behind it?

**Comment by hifi-gustavo** [comment]
Build console output for commit: a64bbbb88c503baee123980f1025bf787377dc84 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef26f436929b3947ef9ee74e52001ac14fccdc55 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dae8abb3dfdc80843b21b83a17f6d50ca441c6a7 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 404430c4c1c9f4f0a2bd9fa8036798a43cc1cdb5 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d39abe42280551f90d6ab67e6fdecbd055e18a6f available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 086ef29c97b5da4199babc4b691070445f89b5b3 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be1bee415423de4ba2b5ddae113599b6909d30b6 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c502bb4efde9786f3cd95d3764e38fdf29e7ec34 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd3bf35868406bdd852dd89d2f10dd9a2fe26f60 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by Geenz** [comment]
Alright, so! I got carried away with this one.  Sorry if this steps on anyone's toes.  There's a lot of refactoring that took place here.  I saw that Interface is using best fit normals as well - they can probably be removed at this point.  Then again, the noise effect inherent with them is actually kind of attractive looking at it - in a "beauty is in imperfection" kind of way.  This is a bit of a long one.

RGB10_A2 Normals
----
So, part one of this commit: RGB10_A2 normals!  What this does is store normal information in an RGB10_A2 buffer that provides higher precision to the normals stored within it.  In hindsight, I could have went for RGBA12 instead of RGB10_A2 and only incurred an extra 16-bits per pixel, but at the same time looking at how Interface handles PBR left me thinking that perhaps it could be a little more flexible.  I'm sure you guys made design decisions at the time to help reduce the amount of memory required for the deferred renderer by using RGBA8 + having a metallic workflow baked into the deferred renderer, but from my experience content creators don't usually like not having the option of having a specular map setup instead of just a metallic setup.  Besides, you can do more interesting things like iridescence with a specular setup, but that's something for another time.

Deferred GBuffer Refactoring
----
Now for part two: refactoring!  I suspect that this will cause concern, and rightfully so given the number of moving parts this touches.  So instead of having a GBuffer layout that looks like this:

| Name | Red | Green | Blue | Alpha | Format |
| --- | --- | --- | --- | --- | --- |
| RT0 | Depth + Stencil | Depth + Stencil | Depth + Stencil | Depth + Stencil | 32-bit Depth + Stencil |
| RT1 | Albedo Red | Albedo Green | Albedo Blue | Surface Metallic-ness | RGBA8 |
| RT2 | Normal X | Normal Y | Normal Z | Specular Roughness | RGBA8 |
| RT3 | Emissive Red | Emissive Green | Emissive Blue | Occlusion | RGBA8 |

It now looks like this:

| Name | Red | Green | Blue | Alpha | Format |
| --- | --- | --- | --- | --- | --- |
| RT0 | Depth + Stencil | Depth + Stencil | Depth + Stencil | Depth + Stencil | 32-bit Depth + Stencil |
| RT1 | Albedo Red | Albedo Green | Albedo Blue | Unused | RGBA8 |
| RT2 | Normal X | Normal Y | Normal Z | Unused | RGB10A2 |
| RT3 | Emissive Red | Emissive Green | Emissive Blue | Occlusion | RGBA8 |
| RT4 | Specular Red | Specular Green | Specular Blue | Specular Roughness | RGBA8 |

The reasoning for this is that the normal buffer's alpha channel was storing surface roughness, which a two bit alpha doesn't work well with.  I could have saved myself a lot of trouble here by simply using RGBA12, RGBA16, or even RGBA16F if I wanted a straightforward approach, but to me it made more sense to add a specular buffer instead given that in either of those it would be taking up additional bandwidth anyways.

Metallic PBR Refactoring
----
This part I suspect will cause even more concern!  That, and likely a bit of debate - there seems to be a bit of a debate about whether a metallic workflow or a specular workflow is better - really they both have their advantages, but specular at the end of the day is more flexible - even if you sacrifice more memory to support it.  I've tried to retain the same overall look from before the refactor - there is likely some spots where things don't look exactly the same, but it can probably be fixed.

So, here are my thoughts on a metallic workflow:

Metallic workflows work nicely from a performance standpoint when everything is designed around it - you can have fewer buffers, and overall leverage the extra bandwidth for other things.  However, I've found that content creators can be resistant towards it, and it's limiting for effects like iridescence which you tend to find in all sorts of places around nature.  Given that I was going to need to dive into refactoring some elements anyways, I decided that it wouldn't hurt to learn more about the deferred renderer in the process.

That being said, the existing metallic workflow should largely be left unharmed - you can still import materials that use a metallic workflow, just certain things are being applied when writing to the G-Buffer rather than when reading from it.

This has a couple of caveats:
* Bigger G-Buffer (by an extra 32-bits per pixel)
    * However, this opens the doors to a more flexible specular workflow
* Calculations for albedo, and specular color are now handled when rendering an object to the G-Buffer, not in screenspace
    * However, these operations are simple and shouldn't cause a bottleneck - best fit normals are more complex than these operations

I took the liberty of abstracting any packing operations into the GBuffer as well - now you have two new methods to do so: `packDeferredFragmentLightmapPBR` and `packDeferredFragmentPBR` - they essentially apply any requisite transformations on incoming data that's being packed into the framebuffer to keep within the metallic workflow.

Pictures!
----
Here's a couple of comparisons of RGB10A2 normals:
rgb10_a2 wall bot
golden lewis example

As far as shading, things seem to be the same.

**Comment by Geenz** [comment]
@samcake @ZappoMan This should be ready for QA and review if you guys are open to accepting it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 565729239011e91bf76bab65d1c61fc81ae976c6 available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1f8a4ac6a00e9959ad7c5dfc9f3c3e58a9dc00c available at: https://gist.github.com/7622435cbe034b449eba39120c2fcfdd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7811.dmg

**Comment by samcake** [comment]
Hi @Geenz ,

I m sorry but you are not going to be happy with my decision here.
We are not going to do these changes because this incur an extra render target and we are trying hard to stay below 4x32bits per pixels, i believe we could even get away with 3x32bits with just Depth stencil + 2 RTs for material properties and surface data. The rational there is somewhat driven by our main target being VR and the resolution and framerate we are shooting for, so using slim GBuffer pays off in terms of the pixel throughput, i would also acknowledge a personal choice for a more strict shading model.

ON the subject of improving normal quality, i think we could certainly do better, but that's not a big issue right now and the fact we loose the alpha channel there is a problem.

ON the subject of supporting a full color specular render target on top of the other properties , we are shooting for a pbr shading model first, from what i learned from the recent evolution in material models of unreal, crytek, unity, stingray and substance i do believe that we can get away with just a boolean metalicness properties instead of a more traditional specular color term.

I m open to debate these topics here. You do bring interesting questions and i welcome your critics of the current engine but for the PR  is not really solving any problem we have right now  so I am inclined to close this PR unless proven wrong.

Feel free to argument more,
Cheers

S

**Comment by Geenz** [comment]
Thanks for explaining HiFi's requirements, it makes sense! I wasn't really sure that this would be accepted, or even open a discussion.

I know best fit normals helps quite a bit with RGBA8 normal buffers, but how about RGB10A2 with normal information in the red and green channels and roughness in the blue channel? Best fit isn't quite as necessary with RGB10 as is.

As far as BRDF stuff, others still support the specular workflows in their deferred renderers for the reasons I mentioned previously, and that can still be satisfied without this via custom shaders in forward rendering.  I have thoughts on that, but I'm not sure that this is the right time for them.

**Comment by Geenz** [comment]
@samcake Would you be willing to accept an alternative that still keeps the RGB10_A2 stuff, but uses a different normal encoding to fit roughness in the blue channel?  Crytek's best fit normals technique is mostly useful for RGBA8 buffers, but doesn't add a whole lot when you have 10 bits and up.  There's other methods - Aras Pranckevičius of Unity Technologies put together a (now dated) list of some here: http://aras-p.info/texts/CompactNormalStorage.html

For the Exodus (and eventually the official) Second Life Viewer, I used the spheremap transform.  It provides decent storage of the values, with minimal performance impact.  Their GBuffer after the materials project ended up looking like this:

RT# | Red | Green | Blue | Alpha | Format
--- | --- | --- | --- | --- | ---
RT0 | Albedo R | Albedo G | Albedo B | Emissive Intensity | SRGBA8
RT1 | Normal X | Normal Y | "Shininess" | N/A | RGB10_A2
RT2 | Specular R | Specular G | Specular B | Environment Mask | SRGBA8

What I'd be thinking for Interface is: 

RT# | Red | Green | Blue | Alpha | Format
--- | --- | --- | --- | --- | ---
RT0 | Albedo R | Albedo G | Albedo B | Metallic | SRGBA8
RT1 | Normal X | Normal Y | Roughness | N/A | RGB10_A2
RT2 | Emissive R | Emissive G | Emissive B | Occlusion | SRGBA8

This way RGB10_A2 can be used for higher precision normals, while staying within a 3 RT budget.  Additionally, the spheremap transform _should_ be a bit cheaper than best fit normals (removes a texture lookup, no need for any branches).  Best fit can still be used in tandem with it, however.  Is this an acceptable alternative?

**Comment by cozza13** [comment]
Hi @Geenz , Just wanted to jump in here to manage the process and get back to you. Given this PR is not solving any current issue, I am inclined to close it out so we can focus on getting this up https://worklist.net/20901

**Comment by Geenz** [comment]
Go ahead and close it - I've stopped work on it until @samcake responds to my proposed solutions.  Even if the answer is yes to what I've proposed, I'd want to open a different PR anyways along with an actual WL item.  I'd like to circle back to it at some point as an enhancement, but only after everything assigned to me on WL has been submitted (or other priorities for HiFi, as they become available to me that is).

**Comment by samcake** [comment]
@geenz Sorry for the wait but i m focused on other topic just right now, i ll try to answer you asap

**Comment by Geenz** [comment]
@samcake Take your time!  If this isn't a priority, I'd rather focus on things that deliver more value anyways - this is something that I can accomplish in my free time.

**Comment by ZappoMan** [comment]
Closing now, we can reopen as a new PR.

**Pull request closed without merging**
