### PR TITLE
Change Collision Pick's group so it collides with MyAvatar

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/21607/Collision-Pick-with-avatar-collision-does-not-collide-with-MyAvatar
This PR changes the collision group for the Collision Pick from USER_COLLISION_GROUP_MY_AVATAR to USER_COLLISION_GROUP_AVATARS to make it collide with MyAvatar also, since USER_COLLISION_GROUP_MY_AVATAR doesn't collide with itself.

### CODE REVIEW

**Comment by SamGondelman** [comment]
You might need to update the hifi_tests collision pick test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18603/HighFidelity-Beta-PR15331-5c6dfc3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18603/HighFidelity-Beta-Interface-PR15331-5c6dfc3.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18603/HighFidelity-Beta-PR15331-5c6dfc3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18603/HighFidelity-Quest-Beta-PR15331-5c6dfc3.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18603/HighFidelity-Beta-PR15331-5c6dfc3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18603/HighFidelity-Beta-Interface-PR15331-5c6dfc3.exe

**Comment by luiscuenca** [comment]
Since we have agreed that this fix is not the appropriate one for this particular case I will close this PR and reassign the ticket

**Pull request closed without merging**
