### PR TITLE
Fix uninitialized boolean (asan warning)

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Verify PAL lists the avatars in the domain.

[ticket](https://highfidelity.manuscript.com/f/cases/14679/setRequestsDomainListData-asan-warning)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9473/app_13092_PR_cefb8457eacb47af31b32f44088bd98e9b2c0edc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9473/HighFidelity-Beta-PR13092-cefb8457eacb47af31b32f44088bd98e9b2c0edc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9473/HighFidelity-Beta-Interface-PR13092-cefb8457eacb47af31b32f44088bd98e9b2c0edc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9473/HighFidelity-Beta-PR13092-cefb8457eacb47af31b32f44088bd98e9b2c0edc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9473/HighFidelity-Beta-Interface-PR13092-cefb8457eacb47af31b32f44088bd98e9b2c0edc.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar appeared in PAL successfully.

**Pull request merged**
