### PR TITLE
Add category to log lines

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2bb2aca2beac896dec09ca7255b141c2a947c287 available at: https://gist.github.com/9d33b212cbf6757c6b759f97133dfe70<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8732-2bb2aca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8732-2bb2aca.dmg

**Comment by ZappoMan** [comment]
@huffman - do you want to make sure that ops isn't using our existing log format in their tools?

**Comment by huffman** [comment]
@ZappoMan Good call, I'll ask

**Comment by huffman** [comment]
To test:

 1. Confirm that you can see the category of each log item in interface's log window
 1. Confirm that you can see the category of each log item in the sandbox log (right click icon, "View Logs")

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Successfully viewed the category of each log item in the interface log window.  Log attached.  Successfully viewed the log of the sandbox log.  Sandbox log attached.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/512164/hifi-log.txt)
[domain-server-15252-1475695804943-stdout.txt](https://github.com/highfidelity/hifi/files/512165/domain-server-15252-1475695804943-stdout.txt)

**Pull request merged**
