### PR TITLE
Add menu checkbox to toggle collisions with other avatars

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/20296/New-Setting-to-Disable-Avatar-Avatar-Collisions

This PR modifies the avatar app to allow users to turn on/off collisions between avatars while retaining collisions with the surrounding geometry.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16267/HighFidelity-Beta-PR14659-d630fe9.apk

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16268/HighFidelity-Beta-PR14659-d630fe9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16268/HighFidelity-Beta-Interface-PR14659-d630fe9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16271/HighFidelity-Beta-PR14659-2a36750.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16271/HighFidelity-Beta-Interface-PR14659-2a36750.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16271/HighFidelity-Beta-PR14659-2a36750.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16271/HighFidelity-Beta-Interface-PR14659-2a36750.exe

**Comment by qlistephens95** [comment]
PASS. verified that "Avatar collides with other avatars" option and "Avatar collides with environment" option both function as expected.

**Pull request merged**
