### PR TITLE
Case 21911: Fix stutter/strobe effect on OpenVR

### PR DESCRIPTION
**Pull request by jherico**
[21911](https://highfidelity.manuscript.com/f/cases/21911/Hazard-Warning-Vive-HMD-Eyepiece-Strobing-Images)

The removal of the composite framebuffer has had a negative impact on the OpenVR display plugin, leading to stuttering.  I believe this is some kind of race condition between the rendering thread and the present thread, but I haven't been able to identify it.  As a result I'm restoring the composting framebuffer specifically to this plugin.

Additionally, I've discovered that the OpenVR API has been updated to allow submission of an image with the pose it was rendered for, ensuring better reprojection, and as such have removed our own threaded custom reprojection in favor of using this updated API.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18557/HighFidelity-Beta-PR15315-accb18b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18557/HighFidelity-Beta-Interface-PR15315-accb18b.dmg

**Comment by jherico** [comment]
closing in favor of #15317

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18557/HighFidelity-Beta-PR15315-accb18b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18557/HighFidelity-Beta-Interface-PR15315-accb18b.exe

**Pull request closed without merging**
