### PR TITLE
Workaround for android buffer corruption issue

### PR DESCRIPTION
**Pull request by gcalero**
Workaround for buffer corruption issue (only affects Android)

Test plan:
- On multiple phones, switch back and forth between the Home screen and a few domains multiple times.  At no point should the screen become "corrupted" with a tv-static-like effect.
- Test in the different supported versions of android (7 and 8)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10315/HighFidelity-Beta-PR13287-b2fe5a6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10315/HighFidelity-Beta-PR13287-b2fe5a6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10315/HighFidelity-Beta-Interface-PR13287-b2fe5a6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10315/HighFidelity-Beta-PR13287-b2fe5a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10315/HighFidelity-Beta-Interface-PR13287-b2fe5a6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10316/HighFidelity-Beta-PR13287-4599919.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10316/HighFidelity-Beta-PR13287-4599919.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10316/HighFidelity-Beta-Interface-PR13287-4599919.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10316/HighFidelity-Beta-PR13287-4599919.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10316/HighFidelity-Beta-Interface-PR13287-4599919.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10317/HighFidelity-Beta-PR13287-85c6202.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10317/HighFidelity-Beta-PR13287-85c6202.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10317/HighFidelity-Beta-Interface-PR13287-85c6202.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10317/HighFidelity-Beta-PR13287-85c6202.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10317/HighFidelity-Beta-Interface-PR13287-85c6202.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No strange behavior noted when switching domains on android and desktop interface.

**Pull request merged**
