### PR TITLE
fix mistaken logic-flip in recent PR

### PR DESCRIPTION
**Pull request by sethalves**
- fix mistaken logic-flip in recent PR

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- visit hifi://eschatology/ and see that you can walk on the ground near the tables

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3947/HighFidelity-Beta-PR11540-9064114ce5336676963f3fdeda690ce8a683f3c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3947/HighFidelity-Beta-PR11540-9064114ce5336676963f3fdeda690ce8a683f3c7.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Unfortunately a **Fail**, the floor does not appear and I'm only able to stand in certain invisible spots where as other areas seem to be just empty pockets.
image

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
## PASS all good.

must have been a content loading issue for @YuppyPlays  I got a solid green floor around the tables.

**Comment by sethalves** [comment]
@yuppyplays I don't know what that's about.  some other problem...

**Comment by YuppyPlays** [comment]
@sethalves  Odd, apparently floors don't wanna load for me today. 😂

**Pull request merged**
