### PR TITLE
RC70: 404 malformed agent script requests

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11408/HighFidelity-Beta-PR13639-1d02f68.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11408/HighFidelity-Beta-PR13639-1d02f68.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11408/HighFidelity-Beta-Interface-PR13639-1d02f68.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11408/HighFidelity-Beta-PR13639-1d02f68.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11408/HighFidelity-Beta-Interface-PR13639-1d02f68.dmg

**Comment by Atlante45** [comment]
## Test Plan:
- Run Sandbox
- Go to http://localhost:40100/
- Go to `Content` > `Scripts`
- Add 1 instance of this script: https://gist.githubusercontent.com/Atlante45/089b266eb11d34b3401a8f0da014337a/raw/b1f8e177efbbc9f063f32de15d1ff292d7cc09d5/testScript.js
- Click `Save and restart` in the top right
- In your toolbar, click on the High Fidelity icon and then on `View Logs`
- Select the `Assignment Clients` tab
- You should see the following message print every second: `[testScript.js] Counter is now: 216`

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 @qliacoombs @Qliemillar PASS

Loaded sandbox, loaded designated script, opened sandbox logs, found the designated lines and it incremented every second as described. Tested on Desktop and Mac.

Made sure general usage of DS worked as well and a bot script was loaded and worked without issue. Users could still connect.

**Pull request merged**
