### PR TITLE
fix AvatarInputs spawning on bottom-left

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

- Start up interface
- Move the mic level bar somewhere known on the screen
- Restart interface
- Ensure the mic level bar is where you left it

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a4b30a50bb0c3178de83b6e53fbbf2d090cb4b5 available at: https://gist.github.com/d1685e28fb22ccc26b2f0100b3fcf6f2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7940.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7940.dmg

**Comment by zzmp** [comment]
test this please

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test as I moved the microphone mute UI to the middle of the screen and closed Interface. Upon relog of Interface it was in the same spot.

**Comment by ZappoMan** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a4b30a50bb0c3178de83b6e53fbbf2d090cb4b5 available at: https://gist.github.com/d1685e28fb22ccc26b2f0100b3fcf6f2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7940.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7940.dmg

**Pull request merged**
