### PR TITLE
Add AudioNoiseGate to Agent

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
### QA Plan

#### General tests
Ensure agent audio works as expected.

#### Specific tests
Silent audio was previously not recorded. For this test, use `recorder.js` to record something with intermittent silences, while your noise reduction is turned off (`Developer > Audio > Audio Noise Reduction`) (similar to [this](https://github.com/highfidelity/hifi/files/778569/recording.hfr.txt)).
Play that using [this bot](https://github.com/highfidelity/hifi/files/778566/bot.js.txt) (you will need to tweak filepaths, and may need to put the recording on your server).
Watch your domain's audio-mixer's statistic for `silent_packets_per_frame`. You should see it increasing when the bot is silent, indicating that the bot is correctly sending silent packets.

Change the settings on the bot to `Agent.isNoiseGateEnabled = false`.
You should no longer see the silent packets sent.

Do all of those with a connected client, to ensure that the Agent sounds as it should. Verify that the noise gate strips any "fuzz" on the silent audio.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3026d140a906680f8e2cf4b1ca944d47147d6496 available at: https://gist.github.com/60fdd11dd6c64837bbf2b51c68b3f1e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-3026d14.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-3026d14.dmg

**Comment by OmegaHeron** [comment]
@zzmp does this and #9897 need to be rebuilt before testing or good to go as is?

**Comment by OmegaHeron** [comment]
@zzmp - never mind my previous question about rebuilding... working on this and 9897 now.

**Comment by ZappoMan** [comment]
@zzmp - please make sure to add your test plan to the Test Plan Library wiki on confluence. Make sure to include format of the other test plans,

**Comment by OmegaHeron** [comment]
Windows 10

General smoke tests pass

Created a recording as outlined, ran it as a bot while listening to it and watching it work - white noise in silence spaces was removed (silent packet in audio-mixer stats increased by 1 when bot was silent, decreased by 1 when not).

Seems to work as test notes indicate.

**Comment by OmegaHeron** [comment]
Hold on QA Passing this please - need to check one thing first.

**Comment by OmegaHeron** [comment]
Re-tested this after failing its companion 9897.  I *do* see silent frames stat increase/decrease both in web stats display from DS and in Interface expanded stats for audio mixer.  QA Pass.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab8d3fbab306bcbcb848eb0182445c75ddc905d6 available at: https://gist.github.com/60fdd11dd6c64837bbf2b51c68b3f1e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-ab8d3fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-ab8d3fb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: abac14ee19b37c58186e1146a68bb992512b3b1f available at: https://gist.github.com/60fdd11dd6c64837bbf2b51c68b3f1e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-abac14e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9896-abac14e.dmg

**Pull request merged**
