### PR TITLE
Adding ability for QML/JS file to be visible in QtCreator. Also chang…

### PR DESCRIPTION
**Pull request by vladest**
…ed files will be installed to destination

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by ZappoMan** [comment]
this PR only changes Unix, and so if it builds, we can merge it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d2b2094fd7d79c9c636de3f9fcd765774f400a3 available at: https://gist.github.com/32d3a2766b285da503b4f408305e2a12<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9823-2d2b209.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9823-2d2b209.dmg

**Pull request merged**
