### PR TITLE
Close tablet when switching from HMD to desktop and vice versa

### PR DESCRIPTION
**Pull request by druiz17**
Close tablet when switching from HMD to desktop and vice versa

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
open the tablet, when you switch from HMD to Desktop or vice versa. The tablet should close and stay closed

**Comment by hifi-gustavo** [comment]
Build console output for commit: b878f164fbf0a18191bb73a56d4e523141d2f2a0 available at: https://gist.github.com/9eea567b96442ee7629d308bdf60eb73<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-b878f16.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-b878f16.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a275a4f4b7dbb448a3b23a16f7cd3f30a12e7e0 available at: https://gist.github.com/9eea567b96442ee7629d308bdf60eb73<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a275a4f4b7dbb448a3b23a16f7cd3f30a12e7e0 available at: https://gist.github.com/9eea567b96442ee7629d308bdf60eb73<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.dmg

**Comment by sethalves** [comment]
test this please

**Comment by Nex-Pro** [comment]
@sethalves  ... explains the XML error

**Comment by sethalves** [comment]
our build system has a couple of sticky sprockets

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a275a4f4b7dbb448a3b23a16f7cd3f30a12e7e0 available at: https://gist.github.com/9eea567b96442ee7629d308bdf60eb73<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9840-2a275a4.dmg

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
### PASS

Works a treat. @druiz17

**Pull request merged**
