### PR TITLE
WL#21794: Modify inspect.js to work with Avatars as well as entities

### PR DESCRIPTION
**Pull request by Triplelexx**
**Test Plan:** Run this version of the script against master version. Observe that inpecting entity functionality is unchanged (alt key + modifiers is used with mouse). This version should add the ability to target avatars.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8108/app_12671_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8108/HighFidelity-Beta-PR12671-7101a37bf983e890b772adee24c357c25b28c522.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8108/HighFidelity-Beta-PR12671-7101a37bf983e890b772adee24c357c25b28c522.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8286/app_12671_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8286/HighFidelity-Beta-PR12671-7101a37bf983e890b772adee24c357c25b28c522.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8286/HighFidelity-Beta-PR12671-7101a37bf983e890b772adee24c357c25b28c522.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Passs @conklin94122 
Inspect mode has a bit of a delay when moving with the mouse with Orbital and Pan mode. For less than a second it tries to use Radial mode, but is not very noticeable. Inspect.js works on objects and Avatars as expected.

**Pull request merged**
