### PR TITLE
Wait 10m for a deadlock when debugging

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Set a breakpoint while compiled in DEBUG and RELEASE.
In release, it should only take 10 seconds to crash from a deadlock (wait >10s and then continue from the breakpoint). In debug, it should take a minute.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 054e6bf88ac7d0747c2cab0327b5b104fffc55f3 available at: https://gist.github.com/9f01a62bb7d6db22821e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ac9f6da7d43afd91716430be5d3dcf63b50e8909 available at: https://gist.github.com/9f01a62bb7d6db22821e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21719b3980a34f9c7eaaa20948fe96bce07d4748 available at: https://gist.github.com/9f01a62bb7d6db22821e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7299.dmg

**Pull request merged**
