### PR TITLE
Fix marketplacesInject.js for local Metaverse

### PR DESCRIPTION
**Pull request by zfox23**
This didn't work before because `metaverse.highfidelity.com/marketplace` automatically redirects to `highfidelity.com/marketplace`. This fix isn't very pretty, but it works. The benefits of this fix are really only for developers who use local metaverses during dev/testing, but we should verify that this change doesn't break anything.

**Test Plan:**
*PREREQ:* Don't modify your `HIFI_METAVERSE_URL` environment variable. Don't log in.
1. Open the MARKET app. Verify that you see a green banner towards the top of the app that says "LOG IN to purchase items from the Marketplace."
2. Click on a costed item to go to its individual item page. Verify that you see a green banner towards the top of the app that says "LOG IN to purchase items from the Marketplace."
3. Click on the "PURCHASE" button. Verify that you see the "HIFI COMMERCE - LOGIN" screen.
4. Quit Interface. Modify your `HIFI_METAVERSE_URL` environment variable such that the value is `https://staging.highfidelity.com`. Launch Interface and repeat steps 1-3.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5904/app_12076_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5904/HighFidelity-Beta-PR12076-25e76c668bf05eeb8eea01240c80b86b8d1c9958.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5906/app_12076_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5906/HighFidelity-Beta-PR12076-47a209dc4c5e4829641902dd2d09a2ac94746fa4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5906/HighFidelity-Beta-PR12076-47a209dc4c5e4829641902dd2d09a2ac94746fa4.exe

**Comment by davidkelly** [comment]
QA PASS - worked perfectly

**Pull request merged**
