### PR TITLE
Case 21816: don't ignore updates that originate from entityPropertiesTool itself [master]

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/21816/

### CODE REVIEW

**Comment by shanzzam** [comment]
can be merged after build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18261/HighFidelity-Beta-PR15227-19c51b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18261/HighFidelity-Beta-Interface-PR15227-19c51b2.dmg

**Comment by thoys** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18267/HighFidelity-Beta-PR15227-19c51b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18267/HighFidelity-Beta-Interface-PR15227-19c51b2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18261/HighFidelity-Beta-PR15227-19c51b2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18261/HighFidelity-Quest-Beta-PR15227-19c51b2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18267/HighFidelity-Beta-PR15227-19c51b2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18267/HighFidelity-Beta-Interface-PR15227-19c51b2.exe

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18270/HighFidelity-Beta-PR15227-19c51b2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18270/HighFidelity-Beta-Interface-PR15227-19c51b2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18270/HighFidelity-Beta-PR15227-19c51b2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18270/HighFidelity-Quest-Beta-PR15227-19c51b2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18270/HighFidelity-Beta-PR15227-19c51b2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18270/HighFidelity-Beta-Interface-PR15227-19c51b2.exe

**Pull request merged**
