### PR TITLE
fixing avatr attachments not being visible when coming out of first person

### PR DESCRIPTION
**Pull request by druiz17**
This PR addresses the issue described in this ticket - https://highfidelity.manuscript.com/f/cases/14433

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- go to the avatar > attachments page
- add an attachment to the neck or head joint
- when you go from first person -> third person. Make sure you can see the attachment.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9130/app_12985_PR_29fce488e479460437db366fdc2f5edb22e800bf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9130/HighFidelity-Beta-PR12985-29fce488e479460437db366fdc2f5edb22e800bf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9130/HighFidelity-Beta-Interface-PR12985-29fce488e479460437db366fdc2f5edb22e800bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9130/HighFidelity-Beta-PR12985-29fce488e479460437db366fdc2f5edb22e800bf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9130/HighFidelity-Beta-Interface-PR12985-29fce488e479460437db366fdc2f5edb22e800bf.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar attachment is visible from all views.

**Comment by samcake** [comment]
I m clear on that PR
Good to go in my opinion

**Pull request merged**
