### PR TITLE
RC69: avatars collide again (again)

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.fogbugz.com/f/cases/15771/Bullet-needs-protection-from-bad-mass-for-dynamic-objects
https://highfidelity.fogbugz.com/f/cases/14431/Avatars-should-not-be-able-to-walk-through-each-other

* clamp minimum dynamic mass for physics simulation stability
* compute mass of avatars more correctly (again)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10684/HighFidelity-Beta-PR13407-085130e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10684/HighFidelity-Beta-PR13407-085130e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10684/HighFidelity-Beta-Interface-PR13407-085130e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10684/HighFidelity-Beta-PR13407-085130e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10684/HighFidelity-Beta-Interface-PR13407-085130e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 @andrewd440 
All known repro methods did not cause a crash on the Mac. 
NOTE: On initial load into the qa-auto-pr-metastaging domain the Mac did crash. This may be outside the scope of the PR. Logs attached anyways
[CRASH 1 hifi-log.txt](https://github.com/highfidelity/hifi/files/2113152/CRASH.1.hifi-log.txt)

**Comment by AndrewMeadows** [comment]
Whoops, this PR was against `master` not `0.69.0-rc`.

Also, that **CRASH 1** log did indicate that it was caused by NaN in the Bullet simulation.  The last few lines looked like this:
```
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  786688
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  35852
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  349764
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  2944 
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  699280
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  699280
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  699280
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  174988
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  349764
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  2796436
[06/18 16:01:34] [DEBUG] [default] Memory storage size is:  174988
[06/18 16:01:46] [WARNING] [hifi.physics] BULLET: Overflow in AABB, object removed from simulation
```
Those `Memory storage size` lines appear to be normal debugging that don't indicate any problem.

**Pull request merged**
