### PR TITLE
Keep requesting render update until textures load

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- Download the volcano lair content set.
- The transparent lights in the submarine room and the red sphere in the middle room should render correctly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6190/app_12136_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6190/HighFidelity-Beta-PR12136-df574c6bc94e5438a064c6420e9a108be011a12a.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6193/app_12136_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6193/HighFidelity-Beta-PR12136-df574c6bc94e5438a064c6420e9a108be011a12a.exe

**Comment by SamGondelman** [comment]
BUILD THIS PLEASE

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6195/app_12136_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6195/HighFidelity-Beta-PR12136-df574c6bc94e5438a064c6420e9a108be011a12a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6195/HighFidelity-Beta-PR12136-df574c6bc94e5438a064c6420e9a108be011a12a.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed testing for PR#12136. PASSED.

**Pull request merged**
