### PR TITLE
21146

### PR DESCRIPTION
**Pull request by Triplelexx**
PR for nameTag.js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 05e3acf1a3fc87dde3a19729e2be031ad4129930 available at: https://gist.github.com/2b4026fa900eec4eab9052b765f708f0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9586-05e3acf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9586-05e3acf.dmg

**Comment by nbq** [comment]
Testing this one

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Under the script description it says `Running the script creates a text entity that will hover over the user's head showing their display name.` so I tested it does just that and slso read description of worklist item from https://worklist.net/21146 to verify it performs as requested.
* ran script: https://rawgit.com/Triplelexx/hifi/05e3acf1a3fc87dde3a19729e2be031ad4129930/scripts/system/nameTag.js
* With name already set, its still blank
* Tried changing the display name and it still shows blank (screen shot below)

**FAIL**

hifi-snap-by--on-2017-02-07_00-39-43

**Comment by Triplelexx** [comment]
Sorry for not putting test notes. It should work as per the description.
Can you confirm that MyAvatar.displayName is displaying output to the console?

**Comment by nbq** [comment]
Yes, it worked for me

**Comment by hifi-gustavo** [comment]
Build console output for commit: e7244b47a9e9b6f96e66390f5194af847dd5a307 available at: https://gist.github.com/2b4026fa900eec4eab9052b765f708f0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9586-e7244b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9586-e7244b4.dmg

**Comment by nbq** [comment]
I have tried the new version and this is a QA PASS

**Comment by Menithal** [comment]
I have a couple of questions.

- Couldn't this entity just be bound to be parented to the Avatar as a local object? instead of updated on a update thread?
- Why not make it a script that displays everything as overlays instead of entities?

**Pull request merged**
