### PR TITLE
Fix ResourceCache crash on shutdown

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19494/ResourceCache-crash-on-shutdown

Test plan:
- Go to a domain with lots of models and things.  Create and delete a model with a unique URL (one that doesn't appear elsewhere in the domain).  Close Interface.  You shouldn't crash on shutdown.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14304/HighFidelity-Beta-PR14260-78f0afd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14304/HighFidelity-Beta-Interface-PR14260-78f0afd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14304/HighFidelity-Beta-PR14260-78f0afd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14304/HighFidelity-Beta-Interface-PR14260-78f0afd.exe

**Comment by qlimnavarro** [comment]
Currently Testing PR14260

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No crash

**Pull request merged**
