### PR TITLE
Show overlay on menu popup

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Testing notes:
1) run interface
2) uncheck View > Overlays - so that the overlays are hidden
3) right click in the main window to pop up the VR menu...
4) notice that the overlays display and you can see the menu

NOTE: This PR is dependent on #7194 - so it currently looks bigger than it is, after that PR is merged, this PR will be smaller and more obvious.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b427e59ae34be73a149ecdd18bc4b3eecd6ccae available at: https://gist.github.com/362cc5382ca5c2cdefdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7208.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7208.dmg

**Comment by zzmp** [comment]
The overlays should go away when the menu is closed.

**Comment by OmegaHeron** [comment]
Other than what @zzmp brings up this works for me on Windows in screen mode (No HMD here).  Will re-test as appropriate.

**Comment by ZappoMan** [comment]
@zzmp - that's a different feature request... we currently allow people to manually hide the overlays... auto-hiding is a little tricky because you might have chosen a menu item which pops up another window... so it's not obvious that we want to hide it once the menu is hidden... so for now this is where we've landed.

**Comment by zzmp** [comment]
In that case this is fine.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44f45a3f29a42b38a879d09a364ce3626713ccdc available at: https://gist.github.com/362cc5382ca5c2cdefdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7208.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7208.dmg

**Pull request merged**
