### PR TITLE
lastEditedBy property for entities

### PR DESCRIPTION
**Pull request by sethalves**
- add a lastEditedBy property for entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use the servers from this PR
- get two interfaces logged in
- open the console on one and run `MyAvatar.sessionUUID`
- rez a cube, use edit.js to get its ID
- in the console, run `Entities.getEntityProperties("{08147863-ab57-47fc-8bf4-55fc67f92ac3}", ["lastEditedBy"]).lastEditedBy`
but replace that uuid with the cube's
- use the other interface to edit the cube (just move it slightly)
- rerun the getEntityProperties command
- see that it now reports the other avatar's ID

**Comment by sethalves** [comment]
this is part of https://highfidelity.fogbugz.com/f/cases/2254/implement-a-way-to-show-greeters-who-has-been-making-changes-to-an-entity

**Comment by hifi-gustavo** [comment]
Build console output for commit: 850361f22233501f7bf0bbcd2c958be4485d4c51 available at: https://gist.github.com/293c40a5b3ab44b0cc9eabab1dca54fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9050-850361f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9050-850361f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15c247fc5e1be025f6b96ba57f19b943476db27b available at: https://gist.github.com/293c40a5b3ab44b0cc9eabab1dca54fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9050-15c247f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9050-15c247f.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass

Able to get session UUID, see that it reflects on last edited then modify object with second av and see UUID change.  I modified object several times with both agents and last edit property followed in all attempts.  Also tested existing objects (prims/meshes/etc) that had not been edited or newly created - UUID returned 00...

**Comment by ZappoMan** [comment]
hold off on merging until ops all clear

**Pull request merged**
