### PR TITLE
Avatar network bandwidth optimization

### PR DESCRIPTION
**Pull request by hyperlogic**
Remove hand controller data, aka faux joints, from AvatarData packets if the user does not have hand controllers.  This was taking up 11% of all network traffic in hq.  In my stand alone tests with 6 bots, the savings was lower, 4%, but still significant.  This is because there are more avatars that are further away from you in hq, which causes the faux joint data to take up a larger percentage when compared to the small delta packets.

This PR also includes some work to improve the avatar data wireshark dissector.

https://highfidelity.fogbugz.com/f/cases/22186/Avatar-Network-Optimization-Culling-Faux-Joints-in-Desktop

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/22186/Avatar-Network-Optimization-Culling-Faux-Joints-in-Desktop

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18983/HighFidelity-Beta-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18983/HighFidelity-Beta-Interface-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18983/HighFidelity-Beta-PR15460-d7babe6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18983/HighFidelity-Quest-Beta-PR15460-d7babe6.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hyperlogic** [comment]
windows build failed for some reason... build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18996/HighFidelity-Beta-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18996/HighFidelity-Beta-Interface-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18996/HighFidelity-Beta-PR15460-d7babe6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18996/HighFidelity-Quest-Beta-PR15460-d7babe6.apk)

**Comment by hyperlogic** [comment]
windows build failed for some reason.  build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19021/HighFidelity-Beta-PR15460-d7babe6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19021/HighFidelity-Quest-Beta-PR15460-d7babe6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19021/HighFidelity-Beta-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19021/HighFidelity-Beta-Interface-PR15460-d7babe6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19021/HighFidelity-Beta-PR15460-d7babe6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19021/HighFidelity-Beta-Interface-PR15460-d7babe6.exe

**Pull request merged**
