### PR TITLE
Pinned UI support

### PR DESCRIPTION
**Pull request by jherico**
This took more work than I anticipated.  First off, we need the idea of 'show/hide' a window as distinct from the boolean visibility property that all items have.  This means everything that used to depend on the `visible` property now needs to depend on the `shown` property.  This meant a lot of small code changes.

Additionally, a significant amount of logic has to go into the `Window` QML type, and due to David's work on the UI redesign, there are now two `Window` types.  Instead of trying to keep the two mostly identical classes in sync, I've overwritten the old versions with the new ones.  However, this means there are a couple of places I need to tweak the look, like the address bar dialog.  

This approach should work equally well for both desktop windows and other widgets for which we're not using the window wrapper like the top of frame stats and the microphone indicator.  

Ctrl-Shift-X is set up in this PR to manually toggle the overlays on and off.  You can test the functionality by opening a dialog like the running scripts dialog and toggling the desktop, seeing that it appears and disappears.  Then pin the window by clicking on the pin icon on the frame, and toggle the desktop again.  It now remains while the other items vanish.

## Issues

* The tool window is misbehaving.  It seems to shut itself off when the desktop toggles. 
* JS based toolbar backgrounds will still appear if you mouse-over them
* The mouse cursor does not disappear (not sure whether to count this as an issue or not, since you'd need the mouse to interact with pinned elements)

## Testing

*  As with production, elements of the UI should automatically hide if you start driving your avatar, but re-appear when you stop.  
*  If you pin a window (for instance the Running Scripts dialog) by clicking on the pin icon on the frame, that window should persist even when the rest of the UI disappears.
* Pinned elements are indicated by a solid filled in pin glyph.  Unpinned elements have an outline instead

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b909ac60ff547f82ebae00340490f245f5f2cbfe available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79d3ebeb4b70a2f4ea722f9e77d768905d148a78 available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8fabce637b43d060a0f2e5519b57039d697f0825 available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by RyanDowne** [comment]
This build doesn't seem to have Howard's 'clear overlays when driving' working even though the option is avail in the settings. So, it's hard to test if the pinning is working in that context.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7036b4d5722f98414559a718568c7d0fb1db888 available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3b57ed32441d9c19e7fe8766f8047724b5e5e5a available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LfYTVYmp&#x2F;10-add-support-for-pinned-ui-elements-that-remain-visible-when-the-overlay-is-hidden"> Add support for &#39;pinned&#39; UI elements that remain visible when the overlay is hidden</a>

**Comment by howard-stearns** [comment]
We should probably get a test plan on this.

**Comment by thoys** [comment]
## QA Test results

There was not really a testing plan, but I verified that the pins worked. The pinned windows were still visible while in moving. Also edit buttons are still visible while moving around with the Vive enabled, I find this comforting.

Ctrl-Shift-X - also works, hides all unpinned Overlays.

:+1: Successfully tested, unless you come with a different plan to test, this is good to go :+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed5d904b3d87b69c39fa2812dcd5e47623a6b28c available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9b359feb1afcb7ecbc27edd15fa1c8859355422 available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Comment by jherico** [comment]
@thoys 

>  Also edit buttons are still visible while moving around with the Vive enabled, I find this comforting.

Sorry, that's considered a bug at the moment, which I've since fixed in the latest commit.  And unfortunately we don't yet have a way to pin toolbars.  I'm actually hoping to re-write toolbar.js to either work against a ToolbarScriptingInterface.qml or against a raw Qml overlay type.  Either way would allow me to specify a framing mechanism for the toolbar and provide a pinning icon so that you can retain the buttons.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e49f3f94297a54d8021cca6cf77325be1cef855 available at: https://gist.github.com/d10c7ac281c9360cb546d9327574c28a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7994.dmg

**Pull request merged**
