### PR TITLE
Quality Improvements to Avatars driven by Vive Trackers

### PR DESCRIPTION
**Pull request by hyperlogic**
Add setting to Settings > Controls > Calibrate Tab.  That determines what to do about out of range Vive tracker data.

1) Drop - The new default.  All out of range data is ignored, effectively turning off the tracker and interpolating the avatar back to its estimated position for that limb.
2) Freeze - Out of range data is frozen in place, until either it becomes ok again, or is turned off if the data is invalid.
3) None - The previous default. Out of range data is trusted and will drive the character as if it was good data.  This could result in large extrapolation errors, such as a tracker moving meters away in the wrong direction.  This is no longer a good default.

Also, 
* The behavior when a tracker becomes invalid has been improved, the avatar should no longer pop, but should smoothly interpolate back an estimated pose.
* Additional filtering is applied to body trackers to reduce the impact of glitches as the pucks go into and out of lighthouse visibility.
* A new developer debug option, `Developer > Avatar > Show Tracked Objects` will draw tracked objects as blue circles with red, green and blue axes.
* Added helper classes to keep track of smoothing between two poses. `CriticallyDampedSpringPoseHelper` and `SnapshotBlendPoseHelper`
* Added acceleration limit filter, currently unused, to controller system.
* Bug fix in exponentialSmoothingFilter, the rotation coeff was flipped.
* Added a developer accelerationFilter.js app to test the new filter type.
* Added a developer exponentialFilter.js app to test the exponential filter type.
* Updated developer puck-attach.js script so that the orientation of the puck 3d model is correct
* Added a developer filtered-puck-attach.js script that is similar to puck-attach.js but adds the ability to tune the filter on each TrackedObject.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13141/HighFidelity-Beta-PR14040-1c5fc9d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13141/HighFidelity-Beta-PR14040-1c5fc9d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13141/HighFidelity-Beta-Interface-PR14040-1c5fc9d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13307/HighFidelity-Beta-PR14040-d943a05.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13307/HighFidelity-Beta-PR14040-d943a05.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13307/HighFidelity-Beta-Interface-PR14040-d943a05.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13577/HighFidelity-Beta-PR14040-9115450.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13577/HighFidelity-Beta-PR14040-9115450.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13577/HighFidelity-Beta-Interface-PR14040-9115450.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13598/HighFidelity-Beta-PR14040-94f5707.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13598/HighFidelity-Beta-PR14040-94f5707.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13598/HighFidelity-Beta-Interface-PR14040-94f5707.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13770/HighFidelity-Beta-PR14040-c0ceb71.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13770/HighFidelity-Beta-PR14040-c0ceb71.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13770/HighFidelity-Beta-Interface-PR14040-c0ceb71.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13814/HighFidelity-Beta-PR14040-717a5ed.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13814/HighFidelity-Beta-PR14040-717a5ed.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13814/HighFidelity-Beta-Interface-PR14040-717a5ed.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13814/HighFidelity-Beta-PR14040-717a5ed.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13814/HighFidelity-Beta-Interface-PR14040-717a5ed.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13926/HighFidelity-Beta-PR14040-640ed6a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14139/HighFidelity-Beta-PR14040-3e68a1d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14139/HighFidelity-Beta-PR14040-3e68a1d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14139/HighFidelity-Beta-Interface-PR14040-3e68a1d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14139/HighFidelity-Beta-PR14040-3e68a1d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14139/HighFidelity-Beta-Interface-PR14040-3e68a1d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14151/HighFidelity-Beta-PR14040-51d767a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14151/HighFidelity-Beta-PR14040-51d767a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14151/HighFidelity-Beta-Interface-PR14040-51d767a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14151/HighFidelity-Beta-PR14040-51d767a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14151/HighFidelity-Beta-Interface-PR14040-51d767a.exe

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/19333/Quality-Improvements-to-Avatars-driven-by-Vive-Trackers

**Comment by hyperlogic** [comment]
QA Test plan:
* Wear at least 3 Vive Trackers (2 on feet, one on hips), and calibrate.
* Test out the three Advanced options for Out of Range Data, you can make a tracker become Out Of Range by covering it up, or moving it into a position where it is no longer visible from any Lighthouse.
    * Drop - The new default. All out of range data is ignored, effectively turning off the tracker and interpolating the avatar back to its estimated position for that limb.
    * Freeze - Out of range data is frozen in place, until either it becomes ok again, or is turned off if the data is invalid.
    * None - The previous default. Out of range data is trusted and will drive the character as if it was good data. This could result in large extrapolation errors, such as a tracker moving meters away in the wrong direction. This is no longer a good default.
  * Ensure that Drop is the default value.
  * Ensure that the Out of Range value is saved in preferences between runs.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14393/HighFidelity-Beta-PR14040-51d767a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14393/HighFidelity-Beta-PR14040-51d767a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14393/HighFidelity-Beta-Interface-PR14040-51d767a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14393/HighFidelity-Beta-PR14040-51d767a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14393/HighFidelity-Beta-Interface-PR14040-51d767a.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . Verified that "drop" is the default value selected and that the "Out of Range" value is saved in preferences between runs.

**Pull request merged**
