### PR TITLE
Add process and system CPU usage to traces

### PR DESCRIPTION
**Pull request by jherico**
On Win32 systems this will add CPU usage to the traces.  Three new counters are added... a global CPU usage for the system as a whole, as well as a stacked counter of kernel and user CPU usage for the interface process.

image

## Testing

Run any trace script and view the results.  There should now be counter rows for `cpuProcess` and `cpuSystem`

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test this when it builds

**Comment by Nex-Pro** [comment]
@jherico , You only need this tested on Win32 ?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2de83d42bc16a1cf98116280c09fb3c004afaded available at: https://gist.github.com/1cfd8372456092089431a152f7d22f8c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9364-2de83d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9364-2de83d4.dmg

**Comment by jherico** [comment]
@OmegaHeron yes, it's a win32 only change.

**Comment by OmegaHeron** [comment]
I think @Nex-Pro wanted to be clear it was a general Windows thing, not a specific Windows in 32 bit mode thing.  I'm just glad to see the PR, not testing it.

**Comment by jherico** [comment]
@OmegaHeron whoops... sorry.

**Comment by Nex-Pro** [comment]
Testing this now

**Comment by Nex-Pro** [comment]
Just kidding it's a win32 thing

**Comment by OmegaHeron** [comment]
Tested Windows 10

Smoke test passes.  CPU stats included in traces now and match expected values from my other method of gathering CPU.  👍

**Comment by Nex-Pro** [comment]
@jherico Your win32 statement is about as clear as mud. 
So I'll assume it does not need testing on win64

**Comment by jherico** [comment]
@Nex-Pro sorry, I meant the 'win32' in the sense of the platform (which is, like it or not, still called win32), as opposed to mac or linux.  We only build a 64 bit app anyway, so...

**Pull request merged**
