### PR TITLE
Stack tester changes

### PR DESCRIPTION
**Pull request by Atlante45**
This PR makes some changes required by the new stack tester tool:

- Adds a `StackTest` scripting interface only enable in dev and PR builds
- Cleans up old code to pass a config file to the DS via cli
- Cleans up cli processing to get a clean output that's easier to process
- Removes static prints from the code

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11702/HighFidelity-Beta-PR13720-949c7f8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11702/HighFidelity-Beta-PR13720-949c7f8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11702/HighFidelity-Beta-Interface-PR13720-949c7f8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11702/HighFidelity-Beta-PR13720-949c7f8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11702/HighFidelity-Beta-Interface-PR13720-949c7f8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11788/HighFidelity-Beta-PR13720-9c89aa9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11788/HighFidelity-Beta-PR13720-9c89aa9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11788/HighFidelity-Beta-Interface-PR13720-9c89aa9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11788/HighFidelity-Beta-PR13720-9c89aa9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11788/HighFidelity-Beta-Interface-PR13720-9c89aa9.exe

**Comment by Atlante45** [comment]
## Test Plan:

- Lanch Sandbox
- Go to http://localhost:40100/settings
- Change some settings
- Save and restart
- Make sure the settings persisted
- Download new settings: http://localhost:40100/settings/#settings_backup_group
- Change some settings again
- Restart and make sure they persist
- Restore the settings you just downloaded
- Make sure the restore worked

**Comment by Atlante45** [comment]
@jherico I removed some static logging in https://github.com/highfidelity/hifi/pull/13720/commits/333cbc99ad5bf7eeb6b0c4d2ccb2230e08610f3a
Let me know if that's ok.

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11902/HighFidelity-Beta-PR13720-9c89aa9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11902/HighFidelity-Beta-PR13720-9c89aa9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11902/HighFidelity-Beta-Interface-PR13720-9c89aa9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11902/HighFidelity-Beta-PR13720-9c89aa9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11902/HighFidelity-Beta-Interface-PR13720-9c89aa9.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Changes persist

**Pull request merged**
