### PR TITLE
BUGZ-1015: Don't store unused cpuident data arrays

### PR DESCRIPTION
**Pull request by Atlante45**
https://highfidelity.atlassian.net/browse/BUGZ-1015

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20503/HighFidelity-Beta-PR15969-7f9ad4a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20503/HighFidelity-Quest-Beta-PR15969-7f9ad4a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20503/HighFidelity-Beta-PR15969-7f9ad4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20503/HighFidelity-Beta-Interface-PR15969-7f9ad4a.dmg

**Comment by Atlante45** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20508/HighFidelity-Beta-PR15969-7f9ad4a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20508/HighFidelity-Quest-Beta-PR15969-7f9ad4a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20508/HighFidelity-Beta-PR15969-7f9ad4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20508/HighFidelity-Beta-Interface-PR15969-7f9ad4a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20508/HighFidelity-Beta-PR15969-7f9ad4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20508/HighFidelity-Beta-Interface-PR15969-7f9ad4a.dmg

**Pull request merged**
