### PR TITLE
Potentially address the crash when no vertex format is specified

### PR DESCRIPTION
**Pull request by samcake**
IN gl45Backend , if no Input Format is specified, we wouldn't necessarily deactivate all the vertex attributes just like we do in the GL41Backend.
This could  be the reason for the crash with Polyline in the current RC

Test Plan:
There shouldn't be any performance or functional change with this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1974ded0505f89f6df712156d43391142b29a1e5 available at: https://gist.github.com/7108df487750a1fcaba202417c3654fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9117-1974ded.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9117-1974ded.dmg

**Comment by samcake** [comment]
Tested on my i5 setup
it works, no problem
but cannot guaranty if it solves the crash issue

**Comment by Nex-Pro** [comment]
### FAIL

Crash on startup looking at whiteboard. Bugs posted.

**Comment by cozza13** [comment]
Report from Balpien on the same crash https://forums.highfidelity.com/t/beta-release-28-hotfix-update/11869/16?u=chris

**Comment by samcake** [comment]
Arg disappointment....
Thanks for testing
If you have a consistent repro piper i would be interested to work with you directly then
I was hopping that would fix it
We ll come back at it tomorrow morning maybe
Have a good holyday
Cheers

**Comment by samcake** [comment]
Event though the pr doesn't solve the mysterious crash around polyline, this is a real fix for a real problem
so i would advice to merge it anyway

**Comment by ZappoMan** [comment]
@samcake - what is a repro for the "real problem" this fixes? Can you describe a test plan that shows the failure in Master/Beta - and demonstrates the fix with this PR?

**Comment by PhilipRosedale** [comment]
I will try it...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 803a399bb61fd1f7a0a9c6ad47c486642d98d69a available at: https://gist.github.com/7108df487750a1fcaba202417c3654fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9117-803a399.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9117-803a399.dmg

**Comment by samcake** [comment]
This pr doesn't fix the crash related to the whiteboard polyline.
Changed the Test plan to simply expect no change.

**Comment by cozza13** [comment]
I did a smoke test and it passed

**Pull request merged**
