### PR TITLE
Create home bookmark for new content sets loaded in

### PR DESCRIPTION
**Pull request by misslivirose**

### CODE REVIEW

**Comment by misslivirose** [comment]
**Test Plan - this involves replacing your full domain content set so take appropriate precautions!:**
1) Go to your sandbox and confirm that you have permissions to [replace domain content](https://github.com/highfidelity/hifi/pull/11056) in the settings page
2) Open the in-world browser (CTRL+B) and paste in the following link: http://mpassets.highfidelity.com/ee5f41ec-5f3f-47b6-a371-ad4eed53ffe8-v1/club_Aug11.json.gz and hit enter
3) Confirm that the club appears and you are teleported to /0,-10,0
4) Move away from the location, open GO TO and hit the home icon
5) Confirm that you are back at /0,-10,0

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2717/HighFidelity-Beta-PR11238-1050141b11058ef6205724b0847acb66f63de3d4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2717/HighFidelity-Beta-PR11238-1050141b11058ef6205724b0847acb66f63de3d4.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
## Test 
Test | Result
--- | ---
Go to your sandbox and confirm that you have permissions to replace domain content in the settings page | Pass
Open the in-world browser (CTRL+B) and paste in the following link: http://mpassets.highfidelity.com/ee5f41ec-5f3f-47b6-a371-ad4eed53ffe8-v1/club_Aug11.json.gz and hit enter | Pass (See notes)
Confirm that the club appears and you are teleported to /0,-10,0 | Pass? (See notes)
Move away from the location, open GO TO and hit the home icon | Pass
Confirm that you are back at /0,-10,0 | Fail (See notes)

So - this was an interesting one. When I launched open the browser and put the .json.gz into the Address Bar, it came up the popup and loaded the content which was all fine. When it done that, the browser closed however there was a small section of the screen which I could no longer interact with. When right clicking, this showed that the browser was still running in the background but it was just invisible. Re-launching the browser didn't fix this, it only opened up a new Instance of the Browser in-game. The old one still persisted and wouldn't clear without restarting the Interface.

After loading up the new domain content, I was teleported to `-2.37531e-08, -10.0287, -1.54413e-06`, not `0,-10,0` like specified in the test plan.
When clicking on the Home Icon in GoTo, I was teleported to the same co-ordinates above.

 ***When I restarted my game, "Go Home" from the Tooltray was taking me to my original domain's home point, `0, -200, 0`.***

Let me know if this needs further testing. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by misslivirose** [comment]
I think that those notes are highlighting things outside of the scope of this PR, but I'll do some checking. It seems like address manager occasionally rounds (those coordinates you gave round to 0, -10, 0 - it's a precision thing, probably based on minor adjustments when teleporting, but the functionality is the expected behavior). As for the system tray, I'll investigate today, but I suspect 'Go Home' in the system tray is pointing to the root of the Sandbox home, rather than your Home bookmark, which I think should be consistent. If you set a new home location in Interface through the menu, does your Sandbox icon adapt? I'm seeing it take me to different places, even on the current release build.

**Comment by misslivirose** [comment]
@cain-kilgore Can you confirm that with the rounding accounted for, you are landing in the proximity of /0,-10,0?

**Comment by cain-kilgore** [comment]
@misslivirose Hey Liv! Yeah it's around that area; if you're suuuuuper picky about it being _exact_ then it might be a problem. However, visually you look close enough to the same spot.

**Pull request merged**
