### PR TITLE
Add more user activity data

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2598d27cf3d5d5a600f321cb4b9877aca6ba1f2e available at: https://gist.github.com/bb0d4d5d5526b08a193015c201fe0b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-2598d27.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-2598d27.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fbe971e730b71343dbe254a547f129b9c6d90910 available at: https://gist.github.com/bb0d4d5d5526b08a193015c201fe0b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-fbe971e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-fbe971e.dmg

**Comment by huffman** [comment]
You will need an HMD and hand controllers for this.

To test:

Start in desktop mode (HMD off)
Disable your hand controllers
Go to your home domain
Run https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?pr8448
Enable edit
Create an entity
Move an entity
Delete an entity
Wait 20 seconds
Enable HMD mode
Enable your hand controllers
Move your head around
Move your hands around
Let me know when you are done and I will confirm everything worked.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25b9d756ca8965b1a0162f8edb92e41d0ac30955 available at: https://gist.github.com/bb0d4d5d5526b08a193015c201fe0b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-25b9d75.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-25b9d75.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d46af500c195eb27b36e76174a989f10aa58f788 available at: https://gist.github.com/bb0d4d5d5526b08a193015c201fe0b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-d46af50.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8436-d46af50.dmg

**Comment by huffman** [comment]
James is QAing this

**Pull request merged**
