### PR TITLE
tablet-ui: Added 6 pixel deadspot for bringing up the tablet in desktop mode.

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test:
  * Verify that, in desktop mode, dragging the mouse slightly (< 6 pixels) will still cause the tablet to appear.
  * Verify that all 2d mouse UI still functions.  Specifically edit.js, goto, PIM. etc.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ffaf7a10e877b8196e2d8cec500c9e024e19c20d available at: https://gist.github.com/290aa298f757989dbac7c3319d943905<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9582-ffaf7a1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9582-ffaf7a1.dmg

**Comment by nbq** [comment]
Will test this one

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Verified that in desktop mode, right clicking still gave me the tablet. I tried to replicate the 6 pixel mark as best I could but was unable to do so well.
* I did verify right clicking and looking around normally did not bring up the tablet and let me mouse look around just fine
* Tested editing an object, moving the edited object around and resizing and that worked just fine
* tested goto by hitting enter and using the tablet, worked just fine
* tested clicking on peoples names in the Users Online box
* Tested snapshot
* Tested PAL
* Tested the VR button
* Tested Menu

All worked as supposed to

**PASS**

**Pull request merged**
