### PR TITLE
WL 21493 - Update the Chat.js to indicate when a message is too long

### PR DESCRIPTION
**Pull request by cain-kilgore**
> Update the Chat.js script from scripts/system/chat.js to indicate when a message is too long to send and prevent the user from entering text longer than the length. Currently, long messages are arbitrarily cut off (this may be a restriction on the amount of data that can be sent via messages?)
> 
> This task includes two parts:
> 
> - Investigate where the cutoff for message length is recurring and create a character restriction 
> - Update the text input to stop accepting text past the limit of what will appear in the text box so that the user is informed before sending them message what they will accurately be sending.
> Worklist https://worklist.net/21493

## Test Plan
- Run the script `scripts/system/chat.js`
- Write in a bunch of text and confirm that after 256 characters, text input is no longer permitted.
- Try to paste some text into the field too, ensuring it doesn't go over.

(Personally) I was able to quickly confirm abcdefghijklmnopqrstuvwxyz pasted 10 times resulted in 'wxyz' being cut off on the last paste equaling 256.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2273/HighFidelity-Beta-PR11118-f79a8b3cb59ed6dce5fe5e60e631d117a271d08e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2273/HighFidelity-Beta-PR11118-f79a8b3cb59ed6dce5fe5e60e631d117a271d08e.exe

**Comment by Nex-Pro** [comment]
Testing this on windows

**Comment by Nex-Pro** [comment]
### PASS

@cain-kilgore I'm pretty sure messages can handle very large strings.  I did QA on a PR that involved sending messages of more than 1 million chars.

**Comment by cain-kilgore** [comment]
In this case it's all good. As it's only a simple chat system I can't see more than 256 characters per message being needed. Thanks for testing!

**Pull request merged**
