### PR TITLE
fix qml crash on start up

### PR DESCRIPTION
**Pull request by druiz17**
Fix the crash introduced in this PR - https://github.com/highfidelity/hifi/pull/12989

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- interface should not crash on startup.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9710/app_13157_PR_4eba727849e4294625e31bdec2a8312b2c1445fd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9710/HighFidelity-Beta-PR13157-4eba727849e4294625e31bdec2a8312b2c1445fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9710/HighFidelity-Beta-Interface-PR13157-4eba727849e4294625e31bdec2a8312b2c1445fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9710/HighFidelity-Beta-PR13157-4eba727849e4294625e31bdec2a8312b2c1445fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9710/HighFidelity-Beta-Interface-PR13157-4eba727849e4294625e31bdec2a8312b2c1445fd.exe

**Comment by sethalves** [comment]
I've build this and no longer crash.

**Pull request merged**
