### PR TITLE
Fix update installer URLs and add installer info to user activity data

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

*Client-only installer test*

 * Install the client-only installer into a custom directory
 * Launch interface.exe from that directory
 * After a short period of time you should get an update dialog for version 9001. Click the update button
 * Your browser should open to the URL: http://highfidelity.com/standard/clientonly

*Full installer test*

 * Install the full (client + sandbox) installer into a custom directory
 * Launch interface.exe from that directory
 * After a short period of time you should get an update dialog for version 9001. Click the update button
 * Your browser should open to the URL: http://highfidelity.com/standard/full

*Client-only installer test for testcampaign*

 * Go to your custom directory for your client-only install
 * Open the FIXME file and modify the campaign line to read `campaign=testcampaign`
 * Launch interface.exe from that directory
 * After a short period of time you should get an update dialog for version 9001. Click the update button.
 * Your browser should open to the URL: http://highfidelity.com/testcampaign/clientonly

*Full installer test for testcampaign*

 * Go to your custom directory for your full install
 * Open the FIXME file and modify the campaign line to read `campaign=testcampaign`
 * Launch interface.exe from that directory
 * After a short period of time you should get an update dialog for version 9001. Click the update link button.
 * Your browser should open to the URL: http://highfidelity.com/testcampaign/full

**Comment by huffman** [comment]
Not ready for testing, I will mark it QA Ready once it is

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9199/app_13008_PR_ce6a9425ce1afe67773f7cd0a4ef456847cf3577.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9199/HighFidelity-Beta-PR13008-ce6a9425ce1afe67773f7cd0a4ef456847cf3577.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9199/HighFidelity-Beta-Interface-PR13008-ce6a9425ce1afe67773f7cd0a4ef456847cf3577.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9199/HighFidelity-Beta-PR13008-ce6a9425ce1afe67773f7cd0a4ef456847cf3577.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9199/HighFidelity-Beta-Interface-PR13008-ce6a9425ce1afe67773f7cd0a4ef456847cf3577.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9208/app_13008_PR_e95f092f90ceea7cef5e5e74b7e3e31bca8efc21.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9208/HighFidelity-Beta-PR13008-e95f092f90ceea7cef5e5e74b7e3e31bca8efc21.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9208/HighFidelity-Beta-Interface-PR13008-e95f092f90ceea7cef5e5e74b7e3e31bca8efc21.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9208/HighFidelity-Beta-PR13008-e95f092f90ceea7cef5e5e74b7e3e31bca8efc21.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9208/HighFidelity-Beta-Interface-PR13008-e95f092f90ceea7cef5e5e74b7e3e31bca8efc21.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9216/app_13008_PR_f5422c783382333233fd5ae280ab7c4d5dd2540b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9216/HighFidelity-Beta-PR13008-f5422c783382333233fd5ae280ab7c4d5dd2540b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9216/HighFidelity-Beta-Interface-PR13008-f5422c783382333233fd5ae280ab7c4d5dd2540b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9216/HighFidelity-Beta-PR13008-f5422c783382333233fd5ae280ab7c4d5dd2540b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9216/HighFidelity-Beta-Interface-PR13008-f5422c783382333233fd5ae280ab7c4d5dd2540b.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
The default links lead to the correct link. The only File I could find with campaign was the .ini file. When changing the campaign to testcampaign, the interface did not lead me to the testcampaign webpage. This occured for both client only and full. Default link for both full and client only work as expected.
Video attached
[Files.zip](https://github.com/highfidelity/hifi/files/1951741/Files.zip)

**Comment by huffman** [comment]
Thanks @qlimnavarro, looking further

**Comment by huffman** [comment]
@qlimnavarro Can you retest the next build?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9220/HighFidelity-Beta-PR13008-947fe31aac93351facdeaa04f6e069f9a8c47400.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9220/HighFidelity-Beta-Interface-PR13008-947fe31aac93351facdeaa04f6e069f9a8c47400.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9220/HighFidelity-Beta-PR13008-947fe31aac93351facdeaa04f6e069f9a8c47400.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9220/HighFidelity-Beta-Interface-PR13008-947fe31aac93351facdeaa04f6e069f9a8c47400.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Links now look good and direct to the correct place. If everything looks good on your end @huffman then this is good to pass.

**Comment by huffman** [comment]
@qlimnavarro Thanks! I will confirm everything on my end

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9224/app_13008_PR_4c8b8d8442a9ac898e9463f7c89a7a511bd5a15b.apk

**Comment by huffman** [comment]
All good, thanks @qlimnavarro !

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9224/HighFidelity-Beta-PR13008-4c8b8d8442a9ac898e9463f7c89a7a511bd5a15b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9224/HighFidelity-Beta-Interface-PR13008-4c8b8d8442a9ac898e9463f7c89a7a511bd5a15b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9224/HighFidelity-Beta-PR13008-4c8b8d8442a9ac898e9463f7c89a7a511bd5a15b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9224/HighFidelity-Beta-Interface-PR13008-4c8b8d8442a9ac898e9463f7c89a7a511bd5a15b.exe

**Pull request merged**
