### PR TITLE
DO NOT MERGE: Adding light trails feature

### PR DESCRIPTION
**Pull request by ericrius1**
work in progress- just opening PR for release build. Ignore for now please.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2d0326c02268b4cf8cd496de12d5e23888910b9 available at: https://gist.github.com/4c56ecff097089b49c29<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2336dd96dd934f5efc1832db5815bf2dc87f3c21 available at: https://gist.github.com/4c56ecff097089b49c29<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f881e765093d62d9ecc0031b3883ff31acb5505 available at: https://gist.github.com/4c56ecff097089b49c29<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6529.dmg

**Comment by ericrius1** [comment]
No longer need to open PR to run interface quickly thanks to a trick clement showed me, so will reopen when ready for review

**Pull request closed without merging**
