### PR TITLE
Add tmpRezCertified to default perms

### PR DESCRIPTION
**Pull request by Atlante45**
[Bug ID](https://highfidelity.fogbugz.com/f/cases/9460/)

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test when built

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5131/HighFidelity-Beta-PR11870-b398e235a2d83a935027280528f7d3659e06c51b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5131/HighFidelity-Beta-PR11870-b398e235a2d83a935027280528f7d3659e06c51b.dmg

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
### PASS
all good.
https://highfidelity.testrail.net/index.php?/tests/view/17011&group_by=cases:section_id&group_order=asc&group_id=448

**Pull request merged**
