### PR TITLE
Fix caching of ktx texture files (RC-61)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/12004

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5694/app_12006_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5694/HighFidelity-Beta-PR12006-c39da5094ba883d3c5edcce1c1adb6207f66477e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5694/HighFidelity-Beta-PR12006-c39da5094ba883d3c5edcce1c1adb6207f66477e.dmg

**Comment by jherico** [comment]
see my comments about mutex locking placement on #12004

**Comment by Nex-Pro** [comment]
QA in progress as per @RyanDowne

**Comment by Nex-Pro** [comment]
Win 10 test

**Comment by Nex-Pro** [comment]
### PASS on improving game rate during content load.

However this appears to have broken equirectangular skyboxes. ( Sam is aware )
In addition many of the textures do not reach full resolution for several minutes.
Particularly noticeable was the fact that the map and conduct signs at the landing point took a very long time to resolve.

**Pull request merged**
