### PR TITLE
have cmake find fbx library on Linux

### PR DESCRIPTION
**Pull request by sethalves**
- fix cmake file to find fbx library on Linux

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change

**Comment by marko8904** [comment]
test this please

**Comment by CainFoool** [comment]
Testing.

**Comment by OmegaHeron** [comment]
@sethalves -- for my own use since I haven't seen it specified elsewhere... which variant of FBX SDK is HF targeting?  I see latest is 2018.1.1  I'd like to do some baking.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/958/HighFidelity-Beta-PR10769-0d9aa8182ec00282e211cf37898f1167c55d497c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/958/HighFidelity-Beta-PR10769-0d9aa8182ec00282e211cf37898f1167c55d497c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/963/HighFidelity-Beta-PR10769-0d9aa8182ec00282e211cf37898f1167c55d497c.dmg

**Comment by sethalves** [comment]
2017.01 I think.   On phone do I can't check right now.

**Comment by CainFoool** [comment]
# Test Passed

Teleported through multiple domains and made sure everything loaded okay and looked normal, passed.

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/983/HighFidelity-Beta-PR10769-0d9aa8182ec00282e211cf37898f1167c55d497c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/983/HighFidelity-Beta-PR10769-0d9aa8182ec00282e211cf37898f1167c55d497c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/986/HighFidelity-Beta-PR10769-b1119ff46586d83b5873683f26e48837f0712cb0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/986/HighFidelity-Beta-PR10769-b1119ff46586d83b5873683f26e48837f0712cb0.exe

**Pull request merged**
