### PR TITLE
Equip via thumb

### PR DESCRIPTION
**Pull request by sethalves**
- Equip (squeeze on vive, bumper on hydra) means 'equip' and must be held down
- If object is not equippable, equip and trigger do same thing
- Distant equip is just distant grab - must bring to yourself to equip 
- optionally can use thumb button for modal equip (keep on yourself)

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- stop all scripts and load
```
https://rawgit.com/sethalves/hifi/equip-via-thumb/examples/defaultScripts.js
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e5a1e73e5d32d167a3c639b79ffba21020da6df available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b5b6f5a207a5f2aab682a7fe2a2d5bdcf7bca71 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b73b2c6d8f8846a97aed48fed71dcfee6907476 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea52c2a096bf521c37d2c5a8e7eb8ea723cbc5c8 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3108ac73b854714111498efd166dc92964e69c3e available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd4b9444587aa5d03c586ef48324e50e11f1aaf8 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40f30b9141cfafdc30c25f296a89349e717047b3 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c4c6413edb06d91989f2086e78fe545e9c8bbe6 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c4c6413edb06d91989f2086e78fe545e9c8bbe6 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a89735cb76bc431f71c8b0d285a4c5f81cafdc50 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8b4d1a379a47589b17536bc45f7cd9496d67015 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e643a1555bbe9a6ba2214b33892e2db5825dd58 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8d58483aa1276b63b67f6dcb66e3a2ecedf0dcb available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a509447cfc44c75cdb934edd16107f83ba785d3 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c8050790b3060207b0dc52ac3cc33e65d1bf38f available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c8050790b3060207b0dc52ac3cc33e65d1bf38f available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb22b5e4a7ba405e5162cdb075a30ba0b9052adc available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfa2d8f40518c9df025cd1ec45bc64e95c0f0a8a available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37b895db0a909272b02f28c379e2a190bdc4700d available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f05f283b044a1f3ba1eeffc86edb86a93b2568f9 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9f5a0ccaf7ab19227b46d0c106f01dbf5512019 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9942a5edd40dcd70628f2ceba2cd858c02006b15 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Comment by PhilipRosedale** [comment]
Tested lots with seth, and user tested on Sam and Birarda

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f3efc425035c3fffe9b8de9fda17791f5373ff8 available at: https://gist.github.com/a3999427c41292940fc9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7355.dmg

**Pull request merged**
