### PR TITLE
Fix keyboard not raising for Facebook username field

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

In the HMD...

In tablet mode:
- Open "goto" dialog and then a place's "i" card. Click the Facebook "like" button and check that keyboard displays for both username and password fields.

In toolbar mode:
- Open "goto" dialog and then a place's "i" card. Click the Facebook "like" button and check that keyboard displays for both username and password fields.
- Open Web browser (Ctrl-B) and navigate to Facebook.com. Check that keyboard displays for both username and password login fields.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 819f02a988a025c7ae33cf18d8f265c4352c0f11 available at: https://gist.github.com/5a6522b4692d3e73f546b5db3d75bbbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 819f02a988a025c7ae33cf18d8f265c4352c0f11 available at: https://gist.github.com/5a6522b4692d3e73f546b5db3d75bbbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 819f02a988a025c7ae33cf18d8f265c4352c0f11 available at: https://gist.github.com/5a6522b4692d3e73f546b5db3d75bbbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 819f02a988a025c7ae33cf18d8f265c4352c0f11 available at: https://gist.github.com/5a6522b4692d3e73f546b5db3d75bbbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10331-819f02a.exe

100% PASS:
- Did not encounter any problems. Followed all steps. Keyboards displayed at every Username and Password fields.

**Pull request merged**
