### PR TITLE
add pthread link dependency to interface for UNIX

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
A recent change broke the build on my linux laptop: unresolved symbols during link.  The symbols it is looking for are in pthread and so I came up with a cmake change that would fix my problem.  However, neither seth or the remote linux builds appear to be affected.

I'm making this change and submitting a PR to test the Jenkins linux build.  If it doesn't break anything then I'd like to have it merged.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ae20bb5fa7e4b14745ca56b329541dcef88c48e5 available at: https://gist.github.com/1772730cf37939dcbafdfd5b5721ff1c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7671.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7671.dmg

**Comment by AndrewMeadows** [comment]
Yay, it built.  Merging this would unblock me on linux going forward.

**Comment by OmegaHeron** [comment]
Tested with make of all executable on Linux and running of stack/interface.  All good.  Also tested generated Windows binary while waiting for Linux binaries to compile (and had breakfast).  All good.

QA Pass

**Pull request merged**
