### PR TITLE
Move down OctreeQueryNode::_viewMutex to OctreeQuery

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
I was getting what looked very much like a race collision on the _conicalViews vector, with it being cleared while in-use. I moved down the lock in OctreeQueryNode to the base OctreeQuery and used it for _conicalViews also. I could just use a second lock instead if that's preferable. This may be related to issue #14165:
https://highfidelity.manuscript.com/f/cases/14165/entity-server-doesn-t-always-relay-added-entities-to-clients

I set up a second machine to observe my local domain.  I was able to import the 64 cubes file in my local Interface and observe them on the remote interface. I was not able to find any obvious problem with the entity distributing logic.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9732/HighFidelity-Beta-PR13164-32e988831e360613ee2f31319cc435926f46d54f.apk

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
It is necessary to have two Interface clients connected to the same domain, and write permissions for the domain from at least one client.

1. Download the cubes2.json entities file from the linked Manuscript (you can also use the original cubes.json but the entities have a limited lifetime).

2. Setup the two avatars together in a common area.

3.  Use the Create -> Import Entities (.json) dialog to import cubes2.json.

Expected behaviour:
The block of 64 imported cubes should appear in both the importing Interface and the observing Interface promptly.

See the linked Manuscript for the original reporter's findings.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9732/HighFidelity-Beta-PR13164-32e988831e360613ee2f31319cc435926f46d54f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9732/HighFidelity-Beta-Interface-PR13164-32e988831e360613ee2f31319cc435926f46d54f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9732/HighFidelity-Beta-PR13164-32e988831e360613ee2f31319cc435926f46d54f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9732/HighFidelity-Beta-Interface-PR13164-32e988831e360613ee2f31319cc435926f46d54f.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9740/HighFidelity-Beta-PR13164-9bb966dd1dc06b4bf3dba274662ea48d990977ca.apk

**Comment by SimonWalton-HiFi** [comment]
Here is one collision over _conicalViews that I managed to trap:

`OctreeServer::handleOctreeQueryPacket()` is the registered packet handler for EntityQuery packet types.
It indirectly calls `OctreeQuery::parseData()` which clears _conicalViews.

Simultaneously an Octree Send Thread may call `OctreeQueryNode::updateCurrentViewFrustum()` which also accesses _conicalViews.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9776/HighFidelity-Beta-PR13164-454978a9c2f5300d0eaee0c7b182b0674d1e1c25.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9776/HighFidelity-Beta-PR13164-454978a9c2f5300d0eaee0c7b182b0674d1e1c25.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9776/HighFidelity-Beta-Interface-PR13164-454978a9c2f5300d0eaee0c7b182b0674d1e1c25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9776/HighFidelity-Beta-PR13164-454978a9c2f5300d0eaee0c7b182b0674d1e1c25.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9776/HighFidelity-Beta-Interface-PR13164-454978a9c2f5300d0eaee0c7b182b0674d1e1c25.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Pull request merged**
