### PR TITLE
more logging for fogbugz 11748

### PR DESCRIPTION
**Pull request by sethalves**
- more logging to help find a solution to fogbugz-11748

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change
- check to make sure your logs aren't scrolling any faster than on master

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7334/app_12446_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7334/HighFidelity-Beta-PR12446-bf73df12652955fda81749946d738e44635aeef4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7334/HighFidelity-Beta-PR12446-bf73df12652955fda81749946d738e44635aeef4.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass. @conklin94122

**Pull request merged**
