### PR TITLE
DNM: Far Distance Culling Prototype

### PR DESCRIPTION
**Pull request by amerhifi**

### CODE REVIEW

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18903/HighFidelity-Beta-PR15442-03843e8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18903/HighFidelity-Quest-Beta-PR15442-03843e8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18903/HighFidelity-Beta-PR15442-03843e8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18903/HighFidelity-Beta-Interface-PR15442-03843e8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18903/HighFidelity-Beta-PR15442-03843e8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18903/HighFidelity-Beta-Interface-PR15442-03843e8.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18936/HighFidelity-Beta-PR15442-440dd51.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18936/HighFidelity-Quest-Beta-PR15442-440dd51.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18936/HighFidelity-Beta-PR15442-440dd51.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18936/HighFidelity-Beta-Interface-PR15442-440dd51.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18936/HighFidelity-Beta-PR15442-440dd51.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18936/HighFidelity-Beta-Interface-PR15442-440dd51.exe

**Pull request closed without merging**
