### PR TITLE
fix-another-highlighting-issue

### PR DESCRIPTION
**Pull request by druiz17**
Some more highlighting fixes during edit mode

ticket - https://highfidelity.manuscript.com/f/cases/14805/In-VR-entering-Create-mode-while-an-object-is-highlighted-keeps-it-highlighted-indefinitely

https://highfidelity.manuscript.com/f/cases/14808/Overlays-like-VR-lasers-and-Create-mode-s-rotation-handles-are-hidden-when-overlapping-a-highlighted-object-s-bounding-box

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan (VR)
- have one hand in a grabbable entity ( do not grab entity)
- with the the other hand open the tablet and go into edit mode
- the entity that your hand is in should be unhighlighted.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9518/app_13105_PR_176d69444f461cdb16d3d26b9ae0f06e17db0476.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9518/HighFidelity-Beta-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9518/HighFidelity-Beta-Interface-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9527/app_13105_PR_176d69444f461cdb16d3d26b9ae0f06e17db0476.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9527/HighFidelity-Beta-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9527/HighFidelity-Beta-Interface-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9527/HighFidelity-Beta-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9527/HighFidelity-Beta-Interface-PR13105-176d69444f461cdb16d3d26b9ae0f06e17db0476.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Highlighting goes away when create app is opened.

**Pull request merged**
