### PR TITLE
VR edit UI test B

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2075/HighFidelity-Beta-PR11067-15436a74152396e18a79b519186dee00bce5facc.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2076/HighFidelity-Beta-PR11067-15436a74152396e18a79b519186dee00bce5facc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2076/HighFidelity-Beta-PR11067-15436a74152396e18a79b519186dee00bce5facc.exe

**Pull request closed without merging**
