### PR TITLE
Reset entity property fields when no selection

### PR DESCRIPTION
**Pull request by dback2**
Ensure whenever there is no selected entity that the entity properties displayed values are cleared/reset.

Addresses: https://highfidelity.fogbugz.com/f/cases/16886

Test Plan:
1. Enter Interface in desktop mode in a domain with all entity types (Model, Shape - Cube/Sphere, Light, Text, Image, Web, Zone, Particle, Material)
2. Open Create and view the Properties tab
3. Verify all properties are cleared/reset and match the images below
4. Select a Model entity in the entity list and verify the Properties for it all populate as expected
5. Attempt to modify various properties and ensure the changes are applying as expected
6. Close Create and re-open Create
7. Verify all properties are cleared/reset and match the images below
8. Repeat steps 4-7 for multiple different Model, Shape, Light, Text, Image, Web, Zone, Particle, and Material entities (preferably entities that use as many properties as possible)

No selection property state:

properties1 properties2
properties3 properties4
properties5 properties6
properties7 properties8
properties9 properties10

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11589/HighFidelity-Beta-PR13698-cb8e9f2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11589/HighFidelity-Beta-PR13698-cb8e9f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11589/HighFidelity-Beta-Interface-PR13698-cb8e9f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11589/HighFidelity-Beta-PR13698-cb8e9f2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11589/HighFidelity-Beta-Interface-PR13698-cb8e9f2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11603/HighFidelity-Beta-PR13698-7faec21.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11603/HighFidelity-Beta-PR13698-7faec21.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11603/HighFidelity-Beta-Interface-PR13698-7faec21.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

If there is no selected entity, the properties tab is not populated. 
When clicking each entity, the properties tab populated their specific information.

**Pull request merged**
