### PR TITLE
fix Linux plugins when using address-sanitizer

### PR DESCRIPTION
**Pull request by sethalves**
- on Linux when building with address-sanitizer enabled, plugins can be loaded

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- on Linux, before running cmake do: export HIFI_MEMORY_DEBUGGING=1
- run cmake, build project
- observe that you can run interface without first moving aside its plugins

**Comment by hifi-gustavo** [comment]
Build console output for commit: 92836caf57bbdd16225748ac5a2aef504293948e available at: https://gist.github.com/7deafdd8d7b905a620f1da57fe33eb38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.dmg

**Comment by ZappoMan** [comment]
```
Finished: UNSTABLE
```
?? will retest

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 92836caf57bbdd16225748ac5a2aef504293948e available at: https://gist.github.com/7deafdd8d7b905a620f1da57fe33eb38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.dmg

**Comment by sethalves** [comment]
```
FTP: Connecting with configuration [ftp.cachefly.com] ...
ERROR: Exception when publishing, exception message [Failed to log in with username [highfidelity] - check username and password]
Build step 'Send build artifacts over FTP' changed build result to UNSTABLE
```

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 92836caf57bbdd16225748ac5a2aef504293948e available at: https://gist.github.com/7deafdd8d7b905a620f1da57fe33eb38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9060-92836ca.dmg

**Comment by OmegaHeron** [comment]
Built/tested Ubuntu 16.04.1 -- general smoke test passed, was able to run DS/AC/Interface after compiling with memory debugging flag enabled.  Binaries produced without flag set also passed general smoke testing.

**Pull request merged**
