### PR TITLE
RC86: Handle HMD in input vars and remove/fix json transitions in/out of HMD strafe states

### PR DESCRIPTION
**Pull request by hyperlogic**
(cherry picked from commit f9f28fc286fde81cbf6d09ebfdd52af2b3bb87d4)

https://highfidelity.atlassian.net/browse/DEV-2741

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22517/HighFidelity-Beta-PR16489-a3de256.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22517/HighFidelity-Beta-Interface-PR16489-a3de256.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22517/HighFidelity-Beta-PR16489-a3de256.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22517/HighFidelity-Quest-Beta-PR16489-a3de256.apk)

**Comment by hyperlogic** [comment]
build this please *sigh*

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22522/HighFidelity-Beta-PR16489-a3de256.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22522/HighFidelity-Quest-Beta-PR16489-a3de256.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22522/HighFidelity-Beta-PR16489-a3de256.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22522/HighFidelity-Beta-Interface-PR16489-a3de256.dmg

**Pull request merged**
