### PR TITLE
After PR13898, joints list in Avatar app's Joint dropdown menu do not match actual joints

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.manuscript.com/f/cases/17981/After-PR13898-joints-list-in-Avatar-app-s-Joint-dropdown-menu-do-not-match-actual-joints

**Test plan**

1. Launch avatarapp, select avatar with joints, select wearable
2. Ensure joints from combobox match actual joints.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12556/HighFidelity-Beta-PR13913-0d06c54.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12556/HighFidelity-Beta-PR13913-0d06c54.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12556/HighFidelity-Beta-Interface-PR13913-0d06c54.exe

**Comment by jakram** [comment]
Currently testing

**Comment by marko8904** [comment]
build this please

**Comment by jakram** [comment]
Stopped testing. Builds not completing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12563/HighFidelity-Beta-PR13913-0d06c54.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12563/HighFidelity-Beta-PR13913-0d06c54.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12563/HighFidelity-Beta-Interface-PR13913-0d06c54.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12563/HighFidelity-Beta-PR13913-0d06c54.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12563/HighFidelity-Beta-Interface-PR13913-0d06c54.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Attachments now go where expected when a joint is selected.

**Pull request merged**
