### PR TITLE
Fix month display in commerce...

### PR DESCRIPTION
**Pull request by zfox23**
😰😰😰😰😰😰😰😰😰😰 (it used to be one month behind)

**Test Plan:**
1. If you have a wallet set up already, copy the hifikey file to this PR's AppData directory, then skip to step 3.
2. Set up your wallet and get seeded.
3. Open your Wallet and verify that the date of the transaction posted to "Recent Activity" is accurate.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5328/HighFidelity-Beta-PR11911-ebb2e50d01511396fd01db9fdb151b7d74c132fd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5328/HighFidelity-Beta-PR11911-ebb2e50d01511396fd01db9fdb151b7d74c132fd.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Having a bit of issue getting a purchase to go through, every one I try which counts as a purchase (the 0 HFC costing ones at least) throw this at me:

image

Please advise.

**Comment by YuppyPlays** [comment]
Been in contact with Dev, trying with a workaround,

Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Housten, we have liftoff.

image


Absolute **Pass**

**Pull request merged**
