### PR TITLE
fix polyvox memory leak

### PR DESCRIPTION
**Pull request by sethalves**
- fixed a memory leak in the rendering of PolyVox Entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run interface and press the "/" key so that stats are visible
- near the right side of the stats, find GPU Buffers --> Count and keep an eye on it
- use edit.js to import

  {
  "Entities": [
               {
               "collisionless": 1,
               "color": { "blue": 0, "green": 0, "red": 255 },
               "dimensions": { "x": 0.2, "y": 0.2, "z": 0.2 },
               "ignoreForCollisions": 1,
               "name": "voxel paint reset button",
               "script": "http://headache.hungry.com/~seth/hifi/voxel-paint-4/voxel-paint-init.js",
               "type": "Sphere",
               "userData": "{\"state\":\"off\",\"grabbableKey\":{\"wantsTrigger\":true}}"
               }
               ],
  "Version": 65
  }

and then click on the red ball to reset the painting platform

- with HMD and hand controllers, draw stuff, reset, etc and watch the Count not rise very much.

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/2302/Polyvox-leaking-GPU-memory

**Comment by hifi-gustavo** [comment]
Build console output for commit: d097fa798211cad4773041bc7617a7f72331e1ae available at: https://gist.github.com/ad38c9374b8b2bd5a9a1d35bdc55b03d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-d097fa7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-d097fa7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a14ff22df35e2d7b3568324224c4d37abb01fe4c available at: https://gist.github.com/ad38c9374b8b2bd5a9a1d35bdc55b03d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-a14ff22.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-a14ff22.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 697369dece77a4bb6b6227628cb34ff10ec00711 available at: https://gist.github.com/ad38c9374b8b2bd5a9a1d35bdc55b03d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-697369d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9088-697369d.dmg

**Comment by Nex-Pro** [comment]
I was able to increase the buffer count by several thousand by drawing large numbers of polyvox strokes of different colours.  The additional buffers are removed on clicking the reset sphere.
Could we get an indication of what to expect ?
I carried out the test at my sandbox with an initial buffer count of 618. I was able to get over 4000 buffers while using this, an extra 3390.

**Comment by Nex-Pro** [comment]
@seth ^

**Comment by sethalves** [comment]
That sounds like a successful run.  If you try it with master it's easy to end up with that count going to 50k or 100k.

**Pull request merged**
