### PR TITLE
Turn Commerce on by default!

### PR DESCRIPTION
**Pull request by zfox23**
IT'S HAPPENING!!! This PR turns Commerce on by default (with the ability to force it to False via the Settings API). It also removes the two DEBUG buttons from WALLET HELP.

**Test Plan:**
1. Install this PR _cleanly_. This means that there shouldn't be an Interface.json associated with your install of this PR.
2. Launch Interface and log in. Verify that you see a WALLET icon in your HUD.
3. Complete the Wallet setup process. (Ask for seeding money if you must)
4. Open the MARKET. Verify that you see a "My Purchases" link at the top of the screen.
5. Buy and spawn a Test Beach Ball. Right click it. Verify you see the (i) Context Overlay. Click the context overlay, and verify that you see the certificate.
6. In a JavaScript Console (CTRL + SHIFT + J), type `Settings.setValue("commerce", false)`, press Enter, then press CTRL + R to restart all scripts.
7. Verify that you don't see a Wallet icon anymore.
8. Right click the beach ball from (5) and verify that clicking the Context Overlay goes straight to the Marketplace page of the Test Beach Ball.
9. When the Marketplace page opens in (8), verify that you DON'T see a "My Purchases" link at the top of the page.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5059/HighFidelity-Beta-PR11848-ec16f167578dcbc73d79c3afb3e280796f6c1c43.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5065/HighFidelity-Beta-PR11848-ec16f167578dcbc73d79c3afb3e280796f6c1c43.dmg

**Comment by cain-kilgore** [comment]
test this please

Gustavooooooooo! (Testing)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5073/HighFidelity-Beta-PR11848-ec16f167578dcbc73d79c3afb3e280796f6c1c43.dmg

**Comment by marko8904** [comment]
Gustavo and Jenkins are partying too much this Friday. build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5075/HighFidelity-Beta-PR11848-ec16f167578dcbc73d79c3afb3e280796f6c1c43.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5075/HighFidelity-Beta-PR11848-ec16f167578dcbc73d79c3afb3e280796f6c1c43.dmg

**Pull request merged**
