### PR TITLE
Auto scroll go to

### PR DESCRIPTION
**Pull request by roxanneskelly**
This includes the changes in PR https://github.com/highfidelity/hifi/pull/13806 with fixes for the 'hover to pause' functionality.

### CODE REVIEW

**Comment by roxanneskelly** [comment]
Fixing issues with license agreement, etc.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12107/HighFidelity-Beta-PR13824-3c3f9f7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12107/HighFidelity-Beta-PR13824-3c3f9f7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12107/HighFidelity-Beta-Interface-PR13824-3c3f9f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12107/HighFidelity-Beta-PR13824-3c3f9f7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12107/HighFidelity-Beta-Interface-PR13824-3c3f9f7.exe

**Pull request closed without merging**
