### PR TITLE
Zero avatar velocity if protocol version mismatch so that overlays show

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Repro the problem in recent dev build.
- Setting > General > Clear overlays when moving is ticked.
- Desktop mode.
- Start in the serverless tutorial. Location: file:///~/serverless/tutorial.json
- Wait for your avatar to load.
- Walk around a bit, using the arrow or WASD keys, and check that the toolbar disappears while you're moving amd reappears shortly after you stop moving.
- 3rd person view such that you can see your avatar's limbs move as you walk.
- Walk into the "Skip Tutorial" portal. You should arrive at "welcome" and get a "protocol version mismatch" error dialog. Notice that your avatar continues "walking" (even if you're not pressing the "walk forward" key) and toolbar is not displayed.
- Ctrl-L to open the GOTO dialog.
- Press the "<" back button to return to the tutorial.
- Note that your avatar is still "walking" and the toolbar is not displayed.
- Wait a minute or so and your avatar will stop "walking" and the toolbar will display.

2) Repeat the above steps in the PR build.
- When you enter "welcome" your avatar should stop walking and the toolbar should display when you get the "protocol version mismatch" error dialog.
- When you teleport back to the serverless tutorial, you avatar should stay not walking and the toolbar should display.

https://highfidelity.manuscript.com/f/cases/15642

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10705/HighFidelity-Beta-PR13415-0e1e44a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10705/HighFidelity-Beta-PR13415-0e1e44a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10705/HighFidelity-Beta-Interface-PR13415-0e1e44a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10705/HighFidelity-Beta-PR13415-0e1e44a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10705/HighFidelity-Beta-Interface-PR13415-0e1e44a.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar stops running and switches to correct animation.

**Pull request merged**
