### PR TITLE
Auto refresh entities list upon display of Entities tab

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9d799f5e06e6edebc31c3433c78147091ba5781 available at: https://gist.github.com/a65d353b7794fe2b001e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5668.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5668.dmg

**Comment by huffman** [comment]
@cozza13 Have you tested this? I should have time tomorrow if not. The code looks good.

**Comment by RyanDowne** [comment]
functionally this works. Tested on Mac only though

**Comment by huffman** [comment]
Ok, I think this is good to merge then.

**Pull request merged**
