### PR TITLE
DEV-841: Fix oculus calibration screen crash if touch is not turned on

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21797/HighFidelity-Beta-PR16314-37aee77.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21797/HighFidelity-Quest-Beta-PR16314-37aee77.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21797/HighFidelity-Beta-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21797/HighFidelity-Beta-Interface-PR16314-37aee77.dmg

**Comment by huffman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21800/HighFidelity-Beta-PR16314-37aee77.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21800/HighFidelity-Quest-Beta-PR16314-37aee77.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21800/HighFidelity-Beta-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21800/HighFidelity-Beta-Interface-PR16314-37aee77.dmg

**Comment by huffman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21807/HighFidelity-Beta-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21807/HighFidelity-Beta-Interface-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21807/HighFidelity-Beta-PR16314-37aee77.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21807/HighFidelity-Quest-Beta-PR16314-37aee77.apk)

**Comment by huffman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21818/HighFidelity-Beta-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21818/HighFidelity-Beta-Interface-PR16314-37aee77.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21818/HighFidelity-Beta-PR16314-37aee77.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21818/HighFidelity-Quest-Beta-PR16314-37aee77.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21818/HighFidelity-Beta-PR16314-37aee77.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21818/HighFidelity-Beta-Interface-PR16314-37aee77.exe

**Comment by AndySeattle** [comment]
I know it is not listed as requiring pre-merge testing, but i tested this at Huffmans request! and it worked great! I was able to open the calibration tab while the device was still "asleep" with no crash.

**Pull request merged**
