### PR TITLE
Remove the glow effect.

### PR DESCRIPTION
**Pull request by ZappoMan**
We are in the process of standardizing our openGL implementation to not use direct/naked GL and to move to core profile for higher performance and better cross platform support. The glow feature is currently broken, and so we're removing it for now as we make this progression.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 819fa852b8ca4e74606df37357f489cf9550f722 available at: https://gist.github.com/cadca5b1bb967ed30d40<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c17794849d76fdb171b575448be12a4f60bfd9ae available at: https://gist.github.com/cadca5b1bb967ed30d40<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 849b584596c095e25c56c6d49fea90302a8cf939 available at: https://gist.github.com/cadca5b1bb967ed30d40<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5338.dmg

**Comment by samcake** [comment]
Tested on both platforms
THe 3DTV doesn't work as expected
Didn;t test occulus

**Pull request merged**
