### PR TITLE
Add some debugging to polylines

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59b726b106eaa056d19d88db10a784768e7347e9 available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbd61411078aa12786715d5f4cf62897dc7d037f available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e89f2bd34bbb0832c80d6ca9ca918717b145d7c available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 63a2b9675349b769ccc6ace78c3e462f00a655ae available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc79cbe152b367b93dc0a821612daa8d46316d92 available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: c90eb8509f6d39cfd8c7b91b43931ce013c25277 available at: https://gist.github.com/f0feb4f4161ac67b48de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6388.dmg

**Pull request closed without merging**
