### PR TITLE
change server to default to not auto-muting

### PR DESCRIPTION
**Pull request by kunalgosar**
Resolution for issue described in: https://highfidelity.fogbugz.com/f/cases/2892

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7b896f961b2f7b5d6909bd3149b433684d1c8b4e available at: https://gist.github.com/2b34b291daac8adfff9981b5d18409ca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9511-7b896f9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9511-7b896f9.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass (unless, by some chance, there's intent to modify settings to this new value for a pre-existing stack install).

From a clean stack install new defaults are reflected and honored by audio AC.  If I got my copying correct it does *not* change any previously existing settings for stack.

General smoke test = pass.  Tested that with new default I could be loud as I wanted to be and changing back to the old value results in old behavior.

**Pull request merged**
