### PR TITLE
Fix head puck broken eyes

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that was causing avatar eyes to look to the side when in HMD and not looking at another avatar.

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- partner with an observer
- person "A" use an HMD, face person "B"
- have B make sure A's eyes track B when B is in front of A
- have B make sure A's eyes look straight ahead when B is not in front of A

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/505/HighFidelity-Beta-PR10649-ce4c3e1601278f2ac5159ea549173c12604f815f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/505/HighFidelity-Beta-PR10649-ce4c3e1601278f2ac5159ea549173c12604f815f.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

[Using 2 Desktops + 1 HMD-Vive]

(My partner is acting as observer on secondary desktop.)
User A: HMD
User B: Desktop

partner with an observer - **Check**
person "A" use an HMD, face person "B" (B can use an HMD, but doesn't have to) - **Check**
have B make sure A's eyes track B when B is in front of A **Pass**
have B make sure A's eyes look straight ahead (not to the side) when B is not in front of A **Pass**

Notes: 
I did notice if it's worth mentioning that User B's eyes actually looked off to the left side when User A was out of sight, however, User A's looked ahead. (confirmed with eye vectors as well as spectating each avatar)

Please let me know if there is anything more I can do/provide to assist :)

**Comment by sethalves** [comment]
If User B was on master rather than this PR, I would expect this.

**Comment by YuppyPlays** [comment]
@sethalves - User B desktop was using same PR as user A.

Hope this helps.

**Comment by sethalves** [comment]
Hmm okay, that's not good.  Let's QA fail this and I'll have another look.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/539/HighFidelity-Beta-PR10649-197fb620d449b405a2c0248422d644a8dc1bbcc6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/539/HighFidelity-Beta-PR10649-197fb620d449b405a2c0248422d644a8dc1bbcc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/543/HighFidelity-Beta-PR10649-5b62c9e83b1261146bf3edc292c36ab41c61a358.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/543/HighFidelity-Beta-PR10649-5b62c9e83b1261146bf3edc292c36ab41c61a358.dmg

**Comment by YuppyPlays** [comment]
Testing.

[2 Desktops + 1 HMD]

**Comment by YuppyPlays** [comment]
Testing complete:

With the same parameters shown in the test plan, all passed same as before but without the issue of B looking off to the side when not looking at user A.

All **Pass**

**Pull request merged**
