### PR TITLE
Bug fix for offset of animated parts of oculus touch controller display

### PR DESCRIPTION
**Pull request by hyperlogic**
Ensure position/rotations are updated with a consistent scale and are animated correctly as the controller values change.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/8006/Build-7208-Scale-avatar-up-or-down-pause-hand-controllers-look-exploded

**Comment by hyperlogic** [comment]
QA Test plan:
  * Start interface in desktop mode.
  * Place the oculus HMD on your head.
  * While in "Paused mode" your oculus touch controllers should be visible, and should have all triggers & buttons properly attached.
  * Change your avatar's scale to var large.  Repeat steps 1-3 (or just press the ESC key to go into paused mode)
  * Change your avatar's scale to very small.  Repeat steps 1-3  (or just press the ESC key to go into paused mode)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3765/HighFidelity-Beta-PR11493-9273e0249796335dbbb9a7aa5ba0c2908da8b582.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3765/HighFidelity-Beta-PR11493-9273e0249796335dbbb9a7aa5ba0c2908da8b582.exe

**Pull request merged**
