### PR TITLE
Removal of hips offset shifting from AnimInverseKinematics node

### PR DESCRIPTION
**Pull request by hyperlogic**
With the addition of the hips IK target, the hips offset shifting code is no longer necessary.
This PR should not effect any behavior, but it removes this unused code from the animation system.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
  * please run thru the [Avatar Controls and Animation Test Plan](https://highfidelity.testrail.net/index.php?/cases/view/174)
  * please run thru the [Avatar IK Test Plan](https://highfidelity.testrail.net/index.php?/cases/view/174)
  * verify that the behavior is identical to the master branch.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6812/app_12317_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6812/HighFidelity-Beta-PR12317-b23f98b31116dd3ea0da8f8f8d45dcd3c3b5a873.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6812/HighFidelity-Beta-PR12317-b23f98b31116dd3ea0da8f8f8d45dcd3c3b5a873.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
