### PR TITLE
reinstate verified domain ownership with statically linked OpenSSL

### PR DESCRIPTION
**Pull request by birarda**
* fixed a security issue where heartbeats sent to the ice-server from domains were not verified
* added failover for keypair generation from domain-server and Interface so new keypairs are generated if domain-server/ice-server fail to verify signature enough times
* moved account information to a separate file so account information is not stored with other settings
* changed OpenSSL linking on Windows to static to avoid Qt dynamic linking collisions

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b13823d0a4cf77cf40504eec7f81db2bebe18679 available at: https://gist.github.com/364396c4641f6ddb5b7c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.dmg

**Comment by birarda** [comment]
This will require testing of all components that link to OpenSSL.

**Comment by OmegaHeron** [comment]
I'll be testing this on Linux for DS/AC platform over the next hour or two - will take some time to compile/deploy/go through all permutations of network settings and validate all works.  Does this depend upon anything at HF backend that would lead to testing issues?

**Comment by birarda** [comment]
@OmegaHeron almost impossible to test most of this without the custom ice-server it requires

**Comment by OmegaHeron** [comment]
Fair enough - will go with this.  It compiles on Linux using same setup as current production code and runs without crashing - also it works with automatic networking set to none, so, for what it's worth - that much = good.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72cbfe2dc7223b26884453d637041b9921e68d29 available at: https://gist.github.com/364396c4641f6ddb5b7c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72cbfe2dc7223b26884453d637041b9921e68d29 available at: https://gist.github.com/364396c4641f6ddb5b7c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04fd7bcdb2b3c4906d0518393c1c8e7bea2e9332 available at: https://gist.github.com/364396c4641f6ddb5b7c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7226.dmg

**Pull request merged**
