### PR TITLE
Restyle bookmark dialogs

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Restyles the bookmark dialogs:
- Navigate > Bookmark Location
- Navigate > Delete Bookmark...

Also restyles "From URL" in Running Scripts.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f91b29c062eb00f66547bdeb74b110efe10d66e available at: https://gist.github.com/290e0b9a5493cbe88bf1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 03fb6b1444fab8f0944a98e8e9091746df55a0b7 available at: https://gist.github.com/290e0b9a5493cbe88bf1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 269936f3ac6908d61a9114057f75e54f63f42a47 available at: https://gist.github.com/290e0b9a5493cbe88bf1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7269.dmg

**Comment by cozza13** [comment]
This has been tested by Alan and given a thumbs up.

**Pull request merged**
