### PR TITLE
Server side bandwidth dial

### PR DESCRIPTION
**Pull request by Atlante45**
Allow domain owner to set a maximum bandwidth per node for their asset server.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3cd94f8de262ab565bca73dbdbac254e84fe9db4 available at: https://gist.github.com/6952bca0a17ae2195b39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e5702273adf69897aba77fd1597b1739f90b8f44 available at: https://gist.github.com/6952bca0a17ae2195b39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fde8f44b715537ec2011a2107fe453a03a311abd available at: https://gist.github.com/6952bca0a17ae2195b39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd00688c92590c78994554884b12581f1ec6fac9 available at: https://gist.github.com/6952bca0a17ae2195b39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 170433997c45e9b399461c22c725d0cc9d4e799f available at: https://gist.github.com/6952bca0a17ae2195b39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7390.dmg

**Comment by OmegaHeron** [comment]
Basic smoke test Windows 7 for Interface - Linux for server side

Current production client to this PR server :+1: 
This PR client to this PR server :+1: 
This PR client to current production server :+1: 

Cleared cache - timed scene load for network before invoking ATP limit to 1/10 peak limit calculated on unrestricted.  Scene load time was approximately 10x slower for ATP calls.  :+1: 

It's unclear from testing if uploading to ATP throttles.. I think not, but, it likely should if it doesn't.

QA Pass

**Comment by OmegaHeron** [comment]
For extra credit - removed limits on ATP in domain-server then added throttle limits via Docker network config for ATP process - setting to same value used in DS I saw same result, with exception that my uploads are also 1/10 speed.

**Pull request merged**
