### PR TITLE
RC76: ensure packets are always added to loss list after estimated timeout

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15315/HighFidelity-Beta-PR14451-4f25f99.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15315/HighFidelity-Beta-PR14451-4f25f99.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15315/HighFidelity-Beta-Interface-PR14451-4f25f99.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15315/HighFidelity-Beta-PR14451-4f25f99.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15315/HighFidelity-Beta-Interface-PR14451-4f25f99.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Pausing Testing -  will pick up in the morning.  Unable to repro on master to verify that the fix works in the PR.  Getting more detailed test plan in the morning.

**Comment by qaAdamSmith82** [comment]
https://highfidelity.manuscript.com/f/cases/19958/reliable-send-queue-completely-stuck-causing-missing-avatar-URLs-kill-avatar-packets-etc

**Comment by qaAdamSmith82** [comment]
PASS @conklin94122 
On master plugging in the network emulation variables causes avatar urls to stop updating. After removing the constrictions the avatar urls never begin updating again, the user is put in an unrecoverable state.

On the PR plugging in the network emulation variables causes avatar urls to stop updating. After removing the constrictions, avatar urls begin updating again after 10-12 seconds, and the user is never put in an unrecoverable state

**Pull request merged**
