### PR TITLE
Fixing issues with unclosed groups in settings persistence

### PR DESCRIPTION
**Pull request by jherico**
My recent changes to settings broke persistence of some (possibly all?) settings changes.  There were a bunch of places in the code that were doing something like this:

    {
      Settings settings;
      settings.beginWriteArray(SETTINGS_KEY);
      settings.remove("");
    }

This was fine when the `Settings` object synchronously wrote to the INI file, because the 'prefix state' of the Settings object lived and died with it's scope.  

However, because the `Settings` object now forwards to the settings manager, by beginning an array and not making a corresponding `settings.endArray()` call, they've changed the state of the actual QSettings derived singleton we use to persist settings.  All subsequent settings get written underneath the new key, so if you examine your INI file now, you'll see things like

```
[accounts]
RunningScripts\fieldOfView=@Invalid()
```

Where the field of view has been placed underneath `accounts/RunningScripts` even though it belongs under `general`.  

This fix modifies the two existing locations where a `begin` is performed without a corresponding `end`, and additionally adds a `qFatal` call to the `Settings` destructor if someone tries to use a settings object without balancing the begin and end calls.

This probably passed QA because whether or not a value is properly read depends on when it's read from the INI file.  Screwing up the prefixes works fine if it's symmetrical, but if something is written under one prefix and then read under another, then changes to it cease to work across sessions.

### CODE REVIEW

**Comment by jherico** [comment]
Fixes https://highfidelity.fogbugz.com/f/cases/904

**Comment by jherico** [comment]
## Testing

* The starting location for the user should be persisted across sessions.
* The set of running scripts should be persisted across sessions.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9bf7977535e4780bf99cb14f97d4413927bf8b5 available at: https://gist.github.com/c740546fe73dc44fba358a6958ff7b95<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.dmg

**Comment by Nex-Pro** [comment]
**FAIL** 

The starting location for the user should be persisted across sessions. ***Fail***
The set of running scripts should be persisted across sessions. ***SUCCESS***
Snapshot directory should be remembered across sessions. ***Fail***


I went to dev-playa to the small office. Then exited. On restarting interface I was directed to localhost which was not running. Also occurred with other start locations such as dev-demo.

I removed several of the default scripts. On restart it simply reloaded them due to defaultScripts.js
I left several scripts running but removed defaultScripts.js and on restart I had no scripts running.

When I left default scripts running and added extra scripts they persisted.

I changed the default scripts directory to be a folder in my documents and loaded only two scripts from there.  They persisted across restarts.

Changing the snapshots directory did not persist.

Did all the above several times.

**Comment by sethalves** [comment]
the stuff about defaultScripts.js is annoying, but I don't think this PR attempts to address that group of problems.

**Comment by jherico** [comment]
Looks like global Setting::Handle objects still aren't saving properly on shutdown.  Investigating further.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3cac33c0121992bbf73da3ba91d8c42530b7b727 available at: https://gist.github.com/c740546fe73dc44fba358a6958ff7b95<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.dmg

**Comment by Nex-Pro** [comment]
/me is twiddling thumbs while Gustavo takes a coffee break in Hawaii.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d52a1fe6f925e448b67a4b997690514389f5ca28 available at: https://gist.github.com/c740546fe73dc44fba358a6958ff7b95<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.dmg

**Comment by OmegaHeron** [comment]
Windows 10 

With this latest build I get exactly same result as nex-pro.  Remember last location - fail.  Remember snapshot dir (after I changed it to !Desktop) - pass. Remember script state - fail.

Additionally - I removed interface.ini from /user/me/appdata/roaming/hfdir/interface.ini and ...hfdirprnum/interface.ini (I'm paraphrasing directory names here - just making clear - there was no interface.ini present for interface to see).

Started session - was at Playa as expected - battled non-stop proto mismatch warnings to get to Heron - got there - turned off all scripts, moved to a location in heron, checked snapshots dir.  Exited Interface - launched this pr again - was at playa, had default scripts running and snapshot dir was correct.

**Comment by OmegaHeron** [comment]
After repeated starts from clean state - no ini - moving to another domain - exiting I still see;

[AddressManager]
address="@Variant(\0\0\0\x11\0\0\0/hifi://playa/-17.2049,-8.08629,-19.4153/0,0,0,1)"
[RunningScripts]
1\script=file:///~/defaultScripts.js
size=1

No indication of a change to heron for address or scripts = none or scripts = something !defaultScripts.js

**Comment by jherico** [comment]
@OmegaHeron @Nex-Pro I identified a bug that was incorrectly causing the 'first run' flag to be tripped every single time, but which only happened in release builds, which is why I wasn't catching it when I was testing.  Should be fixed.

**Comment by Nex-Pro** [comment]
@jherico , this is why you should never let the flag touch the ground.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59ace0234644ee3d7e3189453b921b3bf5e20d69 available at: https://gist.github.com/c740546fe73dc44fba358a6958ff7b95<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b1c472e82b8cccc4ff3a1d500b229b74858ba016 available at: https://gist.github.com/c740546fe73dc44fba358a6958ff7b95<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8057.dmg

**Comment by cozza13** [comment]
QA Pass.

tested, Scripts, Pictures, last location and it was consistent

**Pull request merged**
