### PR TITLE
Case 17368: Fix wearables not disappearing with avatar

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/17368/When-going-away-pressing-escape-key-wearables-do-not-disappear

https://github.com/highfidelity/hifi/issues/9462

Test plan:
- Run [this script](https://gist.githubusercontent.com/SamGondelman/f18015d6dcf95c3cdf4eb02f5bc515fa/raw/80437e30f2e5848b86c69543a609883f676950cf/AwayToggleWearablesTest.js), you'll see a bunch of entities (1 box, two models, one text, one image, one web, one particle, one polyline, one polyvox, one grid, one ring gizmo, one material)
- Toggle your avatar's visibility by pressing Escape.  Your avatar will disappear but the entities will remain the same.
- Press "h".  The entities are now attached to your avatar.  They should appear the same, but they'll follow you when you move. (Note: the material entity will vanish because its parent has been set, this is fine, ignore it for the rest of the test)
- Toggle your avatar's visibility by pressing Escape.  Your avatar and all the entities will appear/disappear at the same time.
- While visible, press "h" again.  The entities won't follow you anymore and won't disappear when you press escape.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19141/HighFidelity-Beta-PR15492-0bcd8b8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19141/HighFidelity-Beta-Interface-PR15492-0bcd8b8.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19141/HighFidelity-Beta-PR15492-0bcd8b8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19141/HighFidelity-Quest-Beta-PR15492-0bcd8b8.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19141/HighFidelity-Beta-PR15492-0bcd8b8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19141/HighFidelity-Beta-Interface-PR15492-0bcd8b8.exe

**Comment by shanzzam** [comment]
@HifiExperiments Do you want to continue this work or close this one?

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by shanzzam** [comment]
@HifiExperiments do you want to continue work on this?
If so, there is a PR getting merged soon that touch the code that is currently in conflict with yours. I recommend updating this after 11/15

**Comment by HifiExperiments** [comment]
@shanzzam sure, I could revisit this at some point, if I remember, there was a problem with shadows or something.  I’ll keep it up to date

**Comment by ZappoMan** [comment]
this PR is old and has multiple conflicts, closing it, and you can reopen it if you'd like

**Pull request closed without merging**
