### PR TITLE
Add CMake flag for building only server components

### PR DESCRIPTION
**Pull request by jherico**
Some of our application library components (like QWebChannel) are difficult to build / acquire on some popular unix distributions.  Adding a server only flag for building the non-client code should make it easier for people to build the server stack for various linux based targets.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e450b0028a6fc5b7e1297ebe7346a6cc4e90e383 available at: https://gist.github.com/9727a899ae968a580172<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6722.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6722.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4b24ab14b44a4bdfc517c63acd1d4dac7b2310d available at: https://gist.github.com/9727a899ae968a580172<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6722.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6722.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 86f570de5323feabe5f409a3d780e6826723823c available at: https://gist.github.com/9727a899ae968a580172<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6722.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6722.dmg

**Comment by jherico** [comment]
test this pleasae

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 243fba461d3af418171479546b694a442ed5d415 available at: https://gist.github.com/9727a899ae968a580172<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6722.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6722.dmg

**Pull request merged**
