### PR TITLE
avoid uninitialized oculus gl calls

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA:
- Ensure oculus still works (smoketest)

**Comment by zzmp** [comment]
This fixes a crash that occurs when oculus fails to initialize. It continues to try to initialize GL (through oculus calls) with bad pointers, and results in access violations (crashes) in other parts of the program.

See https://highfidelity.fogbugz.com/f/cases/1967/crash-in-AudioClient-handleAudioInput-attempting-to-get-DependencyManager-get-AvatarManager

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3692ba0a43f3a84152822ef4eb15fcaf4347706c available at: https://gist.github.com/35068af96b024747370801921b0c8592<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-3692ba0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-3692ba0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 21919038031d6df21f567444ce093680e373925b available at: https://gist.github.com/35068af96b024747370801921b0c8592<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-2191903.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-2191903.dmg

**Comment by zzmp** [comment]
Worked in DEBUG, broken in RELEASE, still working through it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 876f70709ee1e349fb65212e09dd2e42238dc67e available at: https://gist.github.com/35068af96b024747370801921b0c8592<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-876f707.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8826-876f707.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10

Switched between DK2 and Desktop at least 10 times, slowly/rapidly using HUD, context menu from HMD right click and top menu bar.  No crashes or other issue seen.  I think it might be wise to look at this with a CV1 as well before full QA Pass grant.

**Pull request merged**
