### PR TITLE
Fix tablet up orientation for wiki planet

### PR DESCRIPTION
**Pull request by druiz17**
Make the tablet up direction be the same as the avatars up direction

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- goto wiki planet
- bring up the tablet at various places on wiki planet 
- the tablets up direction should be the same as your avatars up direction.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3467/HighFidelity-Beta-PR11414-e78d8bc13259cd991fafcaf0f7179daaee79e4ce.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

goto wiki planet **Check**
bring up the tablet at various places on wiki planet **Check**
the tablets up direction should be the same as your avatars up direction. **Check**

Tablet was always up right when going to different areas of the planet in wikiplanet. **Pass**

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3469/HighFidelity-Beta-PR11414-e78d8bc13259cd991fafcaf0f7179daaee79e4ce.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3469/HighFidelity-Beta-PR11414-e78d8bc13259cd991fafcaf0f7179daaee79e4ce.exe

**Pull request merged**
