### PR TITLE
fixing combo boxes

### PR DESCRIPTION
**Pull request by danteruiz**
This fixes the combo boxes that the avatar app broke

- tickets - https://highfidelity.manuscript.com/f/cases/16596/Exported-entity-files-no-longer-have-JSON-file-extension 
https://highfidelity.manuscript.com/f/cases/16598/File-explorer-does-not-display-file-path

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR https://github.com/highfidelity/hifi/pull/13600

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11280/HighFidelity-Beta-PR13599-1c64ebc.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11280/HighFidelity-Beta-PR13599-1c64ebc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11280/HighFidelity-Beta-Interface-PR13599-1c64ebc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11280/HighFidelity-Beta-PR13599-1c64ebc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11280/HighFidelity-Beta-Interface-PR13599-1c64ebc.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

exports and combo boxes have returned to normal

**Pull request merged**
