### PR TITLE
70.1 version of Personal space bubble is defaulted off for now.

### PR DESCRIPTION
**Pull request by howard-stearns**
Hotfix  version of https://github.com/highfidelity/hifi/pull/13305

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11496/HighFidelity-Beta-PR13669-2c98784.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11496/HighFidelity-Beta-PR13669-2c98784.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11496/HighFidelity-Beta-Interface-PR13669-2c98784.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11496/HighFidelity-Beta-PR13669-2c98784.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11496/HighFidelity-Beta-Interface-PR13669-2c98784.exe

**Comment by howard-stearns** [comment]
I don't think this needs any testing (in addition to the testing that was already completed on the PR to master).

**Pull request merged**
