### PR TITLE
remember if express or custom was selected for install

### PR DESCRIPTION
**Pull request by birarda**
- store express/custom choice in registry during install

### CODE REVIEW

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2815/HighFidelity-Beta-PR11248-6ac255dd2153c0e9fef706f29893ca95c87d1a2a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2815/HighFidelity-Beta-PR11248-6ac255dd2153c0e9fef706f29893ca95c87d1a2a.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2817/HighFidelity-Beta-PR11248-2661f92e0949bc202144f08bf2802a7c147521d3.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2820/HighFidelity-Beta-PR11248-2661f92e0949bc202144f08bf2802a7c147521d3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2820/HighFidelity-Beta-PR11248-2661f92e0949bc202144f08bf2802a7c147521d3.dmg

**Comment by OmegaHeron** [comment]
Testing this one.

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Run 1 - Installer defaulted to express - I changed to custom and completed install.
Run 2 - Installer defaulted to custom - I changed to express and completed install.
Run 3 - Installed defaulted to express - I changed to custom and completed install.

Options selected during install (I.e. install interface/sandbox/startup/launch options) persist as before.  Installed package runs as expected.

**Pull request merged**
