### PR TITLE
fix canRezTmp logic (incorrectly) resets valid lifetimes to the maximum value

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that affected dynamic entities with lifetimes (issue #8159)

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- log into a domain with an account that has tmp-rez but not rez permissions
- try the script in https://github.com/highfidelity/hifi/issues/8159

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9f9b180838a94d86c821b8d0bd6fb00b1e2ba25 available at: https://gist.github.com/c6a532513ada94e5add76e7ec123bfe7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8172.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8172.dmg

**Comment by humbletim** [comment]
for reference the #8159 test script can be loaded into the JS console as a rawgit URL using:
```javascript
Script.include('https://rawgit.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a/raw/6203867bf1e6d2b5ad26458849d916151234dd85/canResTmpTests.js');
```

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Installed PR Sandbox and set ```Rez Temporary``` for all User/Group.  Restarted domain.  As expected nothing rezzed and the console showed a series of continuous messages with ```[07/01 08:23:42] [DEBUG] Sending connect request to domain-server at "localhost"
[07/01 08:23:42] [DEBUG] Local domain-server port read from shared memory (or default) is 40102```.  Ran ```Script.include('https://rawgit.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a/raw/6203867bf1e6d2b5ad26458849d916151234dd85/canResTmpTests.js');``` in the console and a series of white entities appeared and were moving at a consistent velocity up on the Z axis.  The console reported ```canRez: true``` and ``` canRezTemp: true``` after running the script in the console.  Screen shots attached.
domain-settings
capture

**Comment by humbletim** [comment]
@kevinmthomasse -- hmm, the `canRez: true` line in the debug log seems to contradict the domain settings screenshot... it possible that you were already connected to the domain when the settings were being reconfigured (so maybe they hadn't taken effect yet at time of test)?

in any event, i think the original issue only happened in the `canRez: false` and `canRezTmp: true` scenario.

**Comment by kevinmthomasse** [comment]
@humbletim I restarted the domain with the updated settings and ran the script.  Do you want to check the code to see where this might be hung up and refactor so I may retest?

**Comment by humbletim** [comment]
@kevinmthomasse -- it really sounds like there was a domain configuration mismatch somewhere.

what i can recommend for testing is starting at the stock/default domain settings and just unchecking the one `Rez` checkbox (leaving everything else the way it is).  for me that results in this configuration:
screenshot from 2016-07-02 18 49 39

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Successfully ran domain with recommended stock values that matched the image above.  Successfully ran ```https://gist.github.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a#file-canrestmptests-js``` and then ```Script.include('https://rawgit.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a/raw/730813c04eeb678183637518702344b3abdb9b2c/canResTmpTests.js');``` in a JS console and received the following information in the console and log ```[07/03 06:53:23] [DEBUG] Logging activity "stats"
[07/03 06:53:24] [DEBUG] script:print()<< hostname:        localhost
[07/03 06:53:24] [DEBUG] script:print()<< logged in:       true
[07/03 06:53:24] [DEBUG] script:print()<< username:        KevinMThomas
[07/03 06:53:24] [DEBUG] script:print()<< canAdjustLocks:  true
[07/03 06:53:24] [DEBUG] script:print()<< canRez:          false
[07/03 06:53:24] [DEBUG] script:print()<< canRezTmp:       true
[07/03 06:53:29] [DEBUG] script:print()<< requested: undefined  / reported: -1
[07/03 06:53:29] [DEBUG] script:print()<< requested: -1  / reported: -1
[07/03 06:53:29] [DEBUG] script:print()<< requested: 0  / reported: 0
[07/03 06:53:29] [DEBUG] script:print()<< requested: 1  / reported: 1
[07/03 06:53:29] [DEBUG] script:print()<< requested: 3  / reported: 3
[07/03 06:53:29] [DEBUG] script:print()<< requested: 5  / reported: 5
[07/03 06:53:29] [DEBUG] script:print()<< requested: 3600  / reported: 3600
[07/03 06:53:29] [DEBUG] script:print()<< requested: 3601  / reported: 3601``` to which the ```canRez``` is now ```false``` and the ```canRezTmp``` is now ```true```.

**Comment by sethalves** [comment]
[07/03 06:53:29] [DEBUG] script:print()<< requested: 3601 / reported: 3601
Why was reported 3601 rather than 3600, here?  Was the ```Maximum Lifetime of Temporary Entities``` domain-server setting larger than 3600 during this test?

**Comment by humbletim** [comment]
> > [07/03 06:53:29] [DEBUG] script:print()<< requested: 3601 / reported: 3601

> Why was reported 3601 rather than 3600, here?

@sethalves - My guess is that the constraint code never actually saw these Entities...

> [07/03 06:53:29] [DEBUG] script:print()<< requested: 0 / reported: 0

This log means an Entity created with a zero lifetime was still alive +5 seconds later.  Whatever was happening, the Entities seem to have been asleep for the whole test run.  I think maybe the "Physics disabled until entity loads:..." state can exhibit that kind of behavior.

An even more peculiar situation happens when dynamic Entities are created beyond LOD. Except in that case they are deleted at the right moments, but the local tree just doesn't seem aware of any updates until "something" happens.

Here's a way to reproduce that LOD variation -- which does not seem to depend at all on canRezTmp (ie: this happens with full permissions too).  Sometimes it takes running the snippet a few times in a row to see the strangeness:

```javascript
LODManager.setAutomaticLODAdjust(false);
LODManager.setOctreeSizeScale(0);
Script.setTimeout(function() {
 Script.include('https://rawgit.com/humbletim/2672449fd7efd120ec68a0d7ab91bf0a/raw/730813c04eeb678183637518702344b3abdb9b2c/canResTmpTests.js#'+ +new Date);
}, 1000);
```

Example output:
```
[07/03 18:48:46] [DEBUG] script:print()<< requested: undefined  / reported: -1
[07/03 18:48:46] [DEBUG] script:print()<< requested: -1  / reported: -1
[07/03 18:48:46] [DEBUG] script:print()<< requested: 0  / (deleted)
[07/03 18:48:46] [DEBUG] script:print()<< requested: 1  / (deleted)
[07/03 18:48:46] [DEBUG] script:print()<< requested: 3  / (deleted)
[07/03 18:48:46] [DEBUG] script:print()<< requested: 5  / (deleted)
[07/03 18:48:46] [DEBUG] script:print()<< requested: 3600  / reported: 3600
[07/03 18:48:46] [DEBUG] script:print()<< requested: 3601  / reported: 3601
```

**Pull request merged**
