### PR TITLE
Case 20499 - Scripts that use AppUI don't call `that.onClosed()` if the script is restarted while the app is open

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/20499/Scripts-that-use-AppUI-don-t-call-that-onClosed-if-the-script-is-restarted-while-the-app-is-open

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18466/HighFidelity-Beta-PR15289-44b92c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18466/HighFidelity-Beta-Interface-PR15289-44b92c5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18466/HighFidelity-Beta-PR15289-44b92c5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18466/HighFidelity-Quest-Beta-PR15289-44b92c5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18466/HighFidelity-Beta-PR15289-44b92c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18466/HighFidelity-Beta-Interface-PR15289-44b92c5.exe

**Pull request merged**
