### PR TITLE
Interstitial bug fixes

### PR DESCRIPTION
**Pull request by danteruiz**
A round of interstitial bugs fixes.
Tickets
- https://highfidelity.manuscript.com/f/cases/19440/Mexico-dev-Fails-to-Load-with-Interstitial-Screen
- https://highfidelity.manuscript.com/f/cases/19279/Interstitial-loading-bar-doesn-t-always-look-correct
- https://highfidelity.manuscript.com/f/cases/19388/Interstitial-Teleport-parabola-collision-and-audio-become-active-when-physics-are-enabled-during-transition

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14660/HighFidelity-Beta-PR14334-b33934e.apk

**Comment by danteruiz** [comment]
Test plans.
1. You should not fail when you go to mexico or mobile-dev

The following are improvements.
2. The loading bar should look better then what it did before. Better then the images in this ticket - https://highfidelity.manuscript.com/f/cases/19279/Interstitial-loading-bar-doesn-t-always-look-correct

3. I speed up the loading bar progress interpolation once physics get enabled to help some bit for this ticket - https://highfidelity.manuscript.com/f/cases/19388/Interstitial-Teleport-parabola-collision-and-audio-become-active-when-physics-are-enabled-during-transition

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14660/HighFidelity-Beta-PR14334-b33934e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14660/HighFidelity-Beta-Interface-PR14334-b33934e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14660/HighFidelity-Beta-PR14334-b33934e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14660/HighFidelity-Beta-Interface-PR14334-b33934e.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

The issue with the audio in the serverless tutorial will be addressed in a separate PR.

**Pull request merged**
