### PR TITLE
DEMO - Hair flow (with collisions)

### PR DESCRIPTION
**Pull request by luiscuenca**
TEST PLAN
- The avatar https://s3-us-west-1.amazonaws.com/hifio/MaryKate.fst should be loaded as default avatar. If not load it manually.
- Load the script system/hairMoveVerlet.js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6762/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6762/HighFidelity-Beta-PR12303-f4ac9bb3fe18ef8e3510acb573e1bfc23e4b09bc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6762/HighFidelity-Beta-PR12303-f4ac9bb3fe18ef8e3510acb573e1bfc23e4b09bc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6768/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6768/HighFidelity-Beta-PR12303-01cd01aaa58af7e9e48e9e793e0769f13fe5c61a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6935/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6936/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6936/HighFidelity-Beta-PR12303-c975a1ad4ab59314cd5769da2ce2bd242cd42cd6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7035/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7035/HighFidelity-Beta-PR12303-5e9c67678c243858c2d8ac7f2ce79d7935809641.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7035/HighFidelity-Beta-PR12303-5e9c67678c243858c2d8ac7f2ce79d7935809641.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7193/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7193/HighFidelity-Beta-PR12303-3f1df51299fd464c45a911a3c01522601d12879b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7193/HighFidelity-Beta-PR12303-3f1df51299fd464c45a911a3c01522601d12879b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7335/app_12303_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7335/HighFidelity-Beta-PR12303-f4977c064b0d3b603aadf9c6d2d75168458fe452.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7335/HighFidelity-Beta-PR12303-f4977c064b0d3b603aadf9c6d2d75168458fe452.exe

**Comment by hyperlogic** [comment]
this will be checked into the hifi-content repo instead see: https://github.com/highfidelity/hifi-content/pull/110

**Pull request closed without merging**
