### PR TITLE
 fix android local build

### PR DESCRIPTION
**Pull request by amerhifi**
Testing requires android studio, but unable to build or sync gradle is the issue due to Ninja not supporting host=x64 arguments

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20537/HighFidelity-Beta-PR15979-bae3ebd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20537/HighFidelity-Quest-Beta-PR15979-bae3ebd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20537/HighFidelity-Beta-PR15979-bae3ebd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20537/HighFidelity-Beta-Interface-PR15979-bae3ebd.dmg

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20543/HighFidelity-Beta-PR15979-bae3ebd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20543/HighFidelity-Quest-Beta-PR15979-bae3ebd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20543/HighFidelity-Beta-PR15979-bae3ebd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20543/HighFidelity-Beta-Interface-PR15979-bae3ebd.dmg

**Comment by amerhifi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20550/HighFidelity-Beta-PR15979-bae3ebd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20550/HighFidelity-Beta-Interface-PR15979-bae3ebd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20550/HighFidelity-Beta-PR15979-bae3ebd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20550/HighFidelity-Quest-Beta-PR15979-bae3ebd.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20550/HighFidelity-Beta-PR15979-bae3ebd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20550/HighFidelity-Beta-Interface-PR15979-bae3ebd.dmg

**Pull request merged**
