### PR TITLE
Highlight tablet when it is near-grabbable

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Far grab, Web overlay, Create, and Shapes app lasers are disabled when tablet is near-grabbable.
Highlight is removed when tablet is grabbed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12424/HighFidelity-Beta-PR13884-4830ba2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12424/HighFidelity-Beta-PR13884-4830ba2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12424/HighFidelity-Beta-Interface-PR13884-4830ba2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12424/HighFidelity-Beta-PR13884-4830ba2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12424/HighFidelity-Beta-Interface-PR13884-4830ba2.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12573/HighFidelity-Beta-PR13884-9203bbc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12573/HighFidelity-Beta-PR13884-9203bbc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12573/HighFidelity-Beta-Interface-PR13884-9203bbc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12573/HighFidelity-Beta-PR13884-9203bbc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12573/HighFidelity-Beta-Interface-PR13884-9203bbc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12681/HighFidelity-Beta-PR13884-f23d93a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12681/HighFidelity-Beta-PR13884-f23d93a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12681/HighFidelity-Beta-Interface-PR13884-f23d93a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12681/HighFidelity-Beta-PR13884-f23d93a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12681/HighFidelity-Beta-Interface-PR13884-f23d93a.exe

**Comment by ctrlaltdavid** [comment]
### Test Plan

HMD mode and with the tablet open.

Knonw issue: The tablet is not highlighted the second time you enter HMD mode after starting Interface, so test just the first time you're in HMD mode.

1) Move one hand near the tablet, the other hand near the tablet, and both hands near the tablet. In each case, a blue highlight should outline the tablet indicating that it can be grabbed. This bug is https://highfidelity.manuscript.com/f/cases/17858 and is independent of this PR.

2) Check that when the tablet is highlighted, it can be grabbed with both the (primary) trigger and the (secondary) grip controls. Both hands.

3) Check that when the tablet is grabbed - by each of the (primary) trigger and (secondary) grip controls - the blue highlight disappears.

4) Check that when the tablet is grabbed by one hand, moving the other hand near the tablet causes the blue highlight to appear, indicating that it can be grabbed by the other hand. And check that it can be grabbed by the other hand, by each of the (primary) trigger and (secondary) grip controls.

5) When the tablet is highlighted the automatic blue lasers are disabled. Check this with a convenient Web screen: verify that when an automatic laser is on (comes on when pointing at Web screen even though the (primar) trigger is not pressed and you move the hand near the tablet, the automatic laser turns off.

6) When the tablet is highlighted the manual blue lasers are disabled. Check this with the blue lasers manually turned on by partially pulling the (primary) trigger.

https://highfidelity.manuscript.com/f/cases/17853

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12826/HighFidelity-Beta-PR13884-992b9f8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12826/HighFidelity-Beta-PR13884-992b9f8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12826/HighFidelity-Beta-Interface-PR13884-992b9f8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12826/HighFidelity-Beta-PR13884-992b9f8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12826/HighFidelity-Beta-Interface-PR13884-992b9f8.exe

**Comment by ctrlaltdavid** [comment]
### Test Plan

HMD mode and with the tablet open.

#### A: Using lasers (Settings > General > Prefer Stylus Over Laser unchecked).

1) Move one hand near the tablet, the other hand near the tablet, and both hands near the tablet. In each case, a blue highlight should outline the tablet indicating that it can be grabbed.

2) Check that when the tablet is highlighted, it can be grabbed with both the (primary) trigger and the (secondary) grip controls. Both hands.

3) Check that when the tablet is grabbed - by each of the (primary) trigger and (secondary) grip controls - the blue highlight disappears.

4) Check that when the tablet is grabbed by one hand, moving the other hand near the tablet causes the blue highlight to appear, indicating that it can be grabbed by the other hand. And check that it can be grabbed by the other hand, by each of the (primary) trigger and (secondary) grip controls.

5) When the tablet is highlighted the manual blue lasers are disabled. Check this with the blue lasers manually turned on by partially pulling the (primary) trigger.

6) When the tablet is highlighted the automatic blue lasers are disabled. Check this with a convenient Web screen: verify that when an automatic laser is on (comes on when pointing at Web screen even though the (primar) trigger is not pressed and you move the hand near the tablet, the automatic laser turns off.

7) Test 1 - 6 when the Create app is running. ... Known problem: You can both grab the tablet and and entity at the same time (M19345).

8) Test 1 - 6 when using the Shapes app in the attached zip file (is latest code that works with RC75 but not yet updated in the Marketplace).


#### B: Using stylus (Settings > General > Prefer Stylus Over Laser checked).

Repeat A tests 1 - 5.


[shapes.zip](https://github.com/highfidelity/hifi/files/2497581/shapes.zip)


https://highfidelity.manuscript.com/f/cases/17853

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14202/HighFidelity-Beta-PR13884-71ec5f3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14202/HighFidelity-Beta-PR13884-71ec5f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14202/HighFidelity-Beta-Interface-PR13884-71ec5f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14202/HighFidelity-Beta-PR13884-71ec5f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14202/HighFidelity-Beta-Interface-PR13884-71ec5f3.exe

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Highlight is not displayed when launching into VR mode.

Highlight starts appearing after entering VR mode from desktop mode. After the highlight starts appearing, all tests pass!

Highlight goes missing again on every launch into VR mode. Highlight does not appear after reloading scripts or changing domains



[logs.zip](https://github.com/highfidelity/hifi/files/2502135/logs.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14252/HighFidelity-Beta-PR13884-35c1241.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14252/HighFidelity-Beta-PR13884-35c1241.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14252/HighFidelity-Beta-Interface-PR13884-35c1241.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14252/HighFidelity-Beta-PR13884-35c1241.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14252/HighFidelity-Beta-Interface-PR13884-35c1241.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122

**Pull request merged**
