### PR TITLE
fix tablet resolve typo

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### QA Plan

Set Desktop Mode to use Tablet Menu.
Open Networking through Developer > Network > Networking... in the top drop-down menus (not tablet).
Open it again (or open another).

In master, it will freeze on Networking, because the function it tries to call is invalid.
In this PR, it will continue swiping in new menus.

**Comment by claudioshg** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 532284f779d1f8a99f3ec0f25361849aa16dacaf available at: https://gist.github.com/baf0bec055b59f18cca6ad1db4319471<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10293-532284f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10293-532284f.dmg

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10293-532284f.exe

PASS:
- In the Master, it does freeze.
- In this build, the dialog does continue swiping in new menus.

Tested Master build 6371

**Pull request merged**
