### PR TITLE
push AvatarData sequence number when managing identity data for agent

### PR DESCRIPTION
**Pull request by birarda**
- fix bug with identity packet sending from manageIdentityData

### CODE REVIEW

**Comment by birarda** [comment]
### Test plan

This PR will follow the test plan from the avatar whitelist PR.

Pick a single, specific allowed avatar in domain setttings (and leave replacement empty). Any other avatar you pick should go to system default (upon changing within the domain, or entering the domain wearing a different avatar).
-- Make sure other users see you as the default avatar.
-- Make sure your setting remains what picked. E.g., Settings->Avatar->Appearance shoudl be the avatar you picked in Interface (rather than what the domain sets it to). If you quit Interface and get rid of the single allowed avatar in the domain settings, and then restart both the domain server and Interface, you should be your Interface choice again.
-- Make sure that when you to to a different domain, you have your Interface choice back again, rather than what the last domain made you be.
Pick a specific replacement .fst file, and repeat the above.
-- You'll always be the replacement in the domain (for yourself and as others see you), not what you picked in Interface nor the default avatar.
-- Make sure it won't let you be the default avatar (empty Appearance field in settings).
Make a comma separated list of specifical allowed avatar .fst urls and/or domains (with no path), and repeat the above.
Try an empty string among the list (e.g., two commas together within the list) and confirm that the default avatar is now allowed.
Make sure that an empty list (not even comas) does indeed allow everything!

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1004/HighFidelity-Beta-PR10785-ccbae07170fea16badcbd70a4e83f42afd7a1523.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1004/HighFidelity-Beta-PR10785-ccbae07170fea16badcbd70a4e83f42afd7a1523.dmg

**Comment by CainFoool** [comment]
# Test Passed 
Test | Result
-------- | --------
Pick a single, specific allowed avatar in domain setttings (and leave replacement empty). Any other avatar you pick should go to system default (upon changing within the domain, or entering the domain wearing a different avatar). | ☑️
-- Make sure other users see you as the default avatar. | ☑️
-- Make sure your setting remains what picked. E.g., Settings->Avatar->Appearance should be the avatar you picked in Interface (rather than what the domain sets it to). If you quit Interface and get rid of the single allowed avatar in the domain settings, and then restart both the domain server and Interface, you should be your Interface choice again. | ☑️
-- Make sure that when you to to a different domain, you have your Interface choice back again, rather than what the last domain made you be. | ☑️
Pick a specific replacement .fst file, and repeat the above. | ☑️
-- You'll always be the replacement in the domain (for yourself and as others see you), not what you picked in Interface nor the default avatar. | ☑️
-- Make sure it won't let you be the default avatar (empty Appearance field in settings). | ☑️
Make a comma separated list of specifical allowed avatar .fst urls and/or domains (with no path), and repeat the above. | ☑️
Try an empty string among the list (e.g., two commas together within the list) and confirm that the default avatar is now allowed. | ☑️
Make sure that an empty list (not even comas) does indeed allow everything! | ☑️

Let me know if there's anything else you'd like me to check.
###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
