### PR TITLE
Login Dialog UI improvements

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for #[18366](https://highfidelity.manuscript.com/f/cases/18366/Bad-word-break-on-new-login-dialog-Show-Hide-password-glyph-moves-Login-spinner-misplaced)
## TEST PLAN

- Launch Interface
- If logged in, log out
- Click `File > Log In / Sign Up`
- Try a bad username/password combination
- [Dialog](https://user-images.githubusercontent.com/10539521/45848481-7321e780-bce3-11e8-9445-dd90288125c0.png) should look like so (with red text in between the sign in text and the username text field)
- This should look the same within HMD mode as well
- After toggling the `Show Password` eye in the password text field, the eye should not shift nor look visually distorted in any way
- Resizing the interface while login dialog is displayed should not change the contents of the login dialog

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13085/HighFidelity-Beta-PR14020-43fe98a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13085/HighFidelity-Beta-PR14020-43fe98a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13085/HighFidelity-Beta-Interface-PR14020-43fe98a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13085/HighFidelity-Beta-PR14020-43fe98a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13085/HighFidelity-Beta-Interface-PR14020-43fe98a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13128/HighFidelity-Beta-PR14020-8770c36.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13128/HighFidelity-Beta-PR14020-8770c36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13128/HighFidelity-Beta-Interface-PR14020-8770c36.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13128/HighFidelity-Beta-PR14020-8770c36.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13153/HighFidelity-Beta-PR14020-3907eaf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13153/HighFidelity-Beta-PR14020-3907eaf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13153/HighFidelity-Beta-Interface-PR14020-3907eaf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13153/HighFidelity-Beta-PR14020-3907eaf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13153/HighFidelity-Beta-Interface-PR14020-3907eaf.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13186/HighFidelity-Beta-PR14020-3f9c8a2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13186/HighFidelity-Beta-PR14020-3f9c8a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13186/HighFidelity-Beta-Interface-PR14020-3f9c8a2.exe

**Comment by wayne-chen** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13192/HighFidelity-Beta-PR14020-3f9c8a2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13192/HighFidelity-Beta-PR14020-3f9c8a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13192/HighFidelity-Beta-Interface-PR14020-3f9c8a2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13192/HighFidelity-Beta-PR14020-3f9c8a2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13192/HighFidelity-Beta-Interface-PR14020-3f9c8a2.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13504/HighFidelity-Beta-PR14020-189e7e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13504/HighFidelity-Beta-PR14020-189e7e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13504/HighFidelity-Beta-Interface-PR14020-189e7e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13504/HighFidelity-Beta-PR14020-189e7e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13504/HighFidelity-Beta-Interface-PR14020-189e7e1.exe

**Pull request merged**
