### PR TITLE
CR for Job #20807 - Fix vertically mirrored particles.

### PR DESCRIPTION
**Pull request by Nex-Pro**
Code Review for Job #20807 - Workitem available at https://www.worklist.net/20807

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
Added a script in examples/tests should display a large particle with a red arrow and L R so the orientation can be clearly viewed.
Red arrow points up. L is left green arrows indicate extents. 

https://raw.githubusercontent.com/Nex-Pro/hifi/20807/examples/tests/particleOrientationTest.js

**Comment by thoys** [comment]
ok to test

**Comment by thoys** [comment]
@cozza13 can you set this to "ok to test"  ?

**Comment by murillodigital** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6403bb60a5ea751c6bd2a41c2f35925fdf2e969b available at: https://gist.github.com/a2c19eea9073f79e8e01<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7178.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7178.dmg

**Comment by cozza13** [comment]
tested and it works per spec

**Pull request merged**
