### PR TITLE
Case 20550 - nitpick installer

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/edit/20550/Add-nitpick-to-HiFi-installer
# Description
Updates the INSTALL readme.
# Testing
Follow https://github.com/NissimHadar/hifi/blob/20550-nitpickInstaller/INSTALL.md - on a PC that hasn't been used previously to create an installer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16365/HighFidelity-Beta-PR14684-331cc21.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16365/HighFidelity-Beta-PR14684-331cc21.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16365/HighFidelity-Beta-Interface-PR14684-331cc21.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16365/HighFidelity-Beta-PR14684-331cc21.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16365/HighFidelity-Beta-Interface-PR14684-331cc21.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16723/HighFidelity-Beta-PR14684-331cc21.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16723/HighFidelity-Beta-Interface-PR14684-331cc21.exe

**Comment by qaAdamSmith82** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16728/HighFidelity-Beta-PR14684-6de5527.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16728/HighFidelity-Beta-PR14684-6de5527.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16728/HighFidelity-Beta-Interface-PR14684-6de5527.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16737/HighFidelity-Beta-PR14684-e77e2b9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16737/HighFidelity-Beta-PR14684-e77e2b9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16737/HighFidelity-Beta-Interface-PR14684-e77e2b9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16737/HighFidelity-Beta-PR14684-e77e2b9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16737/HighFidelity-Beta-Interface-PR14684-e77e2b9.exe

**Pull request merged**
