### PR TITLE
7991 Change Instances of Edit Mode to Create Mode

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Go to application's 'edit' menu
2. Ensure 'Show Lights and Particle Systems in Create Mode' and 'Show Zones in Create Mode' menu items are shown instead of 'Show Lights and Particle Systems in Edit Mode' and 'Show Zones in Edit Mode'
3. Go to tablet's help
4. Ensure all 4 help images have 'create' instead of 'edit' at the bottom right area, like on the screenshot below: 

image

https://highfidelity.manuscript.com/f/cases/7991/Change-Instances-of-Edit-Mode-to-Create-Mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5182/HighFidelity-Beta-PR11880-02684e3fedf993b0469639531dce4b6f58ea2636.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5182/HighFidelity-Beta-PR11880-02684e3fedf993b0469639531dce4b6f58ea2636.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Go to application's 'edit' menu **Check**
Ensure 'Show Lights and Particle Systems in Create Mode' and 'Show Zones in Create Mode' menu items are shown instead of 'Show Lights and Particle Systems in Edit Mode' and 'Show Zones in Edit Mode' **Check**
Go to tablet's help **Check**
Ensure all 4 help images have 'create' instead of 'edit' at the bottom right area, like on the screenshot  **Check**

**Solid Pass**

**Pull request merged**
