### PR TITLE
FB12599 - Consistent Model sizing across different import methods

### PR DESCRIPTION
**Pull request by humbletim**
... PR for test build and max dimension discussions

https://highfidelity.fogbugz.com/f/cases/12599/Different-import-methods-of-models-are-not-sized-consistently

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14193/HighFidelity-Beta-PR14244-de91737.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14193/HighFidelity-Beta-PR14244-de91737.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14193/HighFidelity-Beta-Interface-PR14244-de91737.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14193/HighFidelity-Beta-PR14244-de91737.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14193/HighFidelity-Beta-Interface-PR14244-de91737.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14206/HighFidelity-Beta-PR14244-210e2c5.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14206/HighFidelity-Beta-PR14244-210e2c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14206/HighFidelity-Beta-Interface-PR14244-210e2c5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14206/HighFidelity-Beta-PR14244-210e2c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14206/HighFidelity-Beta-Interface-PR14244-210e2c5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14344/HighFidelity-Beta-PR14244-8e1c8d5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14344/HighFidelity-Beta-PR14244-8e1c8d5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14344/HighFidelity-Beta-Interface-PR14244-8e1c8d5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14344/HighFidelity-Beta-PR14244-8e1c8d5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14344/HighFidelity-Beta-Interface-PR14244-8e1c8d5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14402/HighFidelity-Beta-PR14244-b962a30.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14402/HighFidelity-Beta-PR14244-b962a30.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14402/HighFidelity-Beta-Interface-PR14244-b962a30.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14402/HighFidelity-Beta-PR14244-b962a30.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14402/HighFidelity-Beta-Interface-PR14244-b962a30.exe

**Comment by jakram** [comment]
Per Huffman, this PR is waiting on an update from Tim.

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closing this PR because it's old and has conflicts...

**Pull request closed without merging**
