### PR TITLE
Render a different model when in first person view.

### PR DESCRIPTION
**Pull request by hyperlogic**
Currently this model is identical to the third person model, except
that the head bones have been 'cauterized' by applying a zero scale transform.
This allows us to set the near clip back to a reasonable value.

This should eliminate the problem where you can see the eyes or teeth of your avatar's head while wearing an HMD.

https://app.asana.com/0/37796130830309/35255696667092
https://app.asana.com/0/37796130830309/37633564937426

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
I'm not really a fan of this preRender() approach. Are you sure you can't implement this in the render() method?

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 080d3f8607ddd1113156adc47044bfc06cc767fe available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by hyperlogic** [comment]
Well there's a problem with trying to switch the visibility of the models during the render callback. The avatar render::Item is in the same scene bucket as the model parts render::Item.  So attempting to reset the model parts into the 'invisible' bucket while rendering isn't possible.  I agree that the pre-render thing is not ideal.  But after discussing this with @samcake, we'd like to create a separate scene that is used for the mirror render, that way we can manipulate the models scene in the update/simulate methods instead.  The separate mirror scene is something I can tackle in a future pull request.

**Comment by ZappoMan** [comment]
But we are doing this same visible/invisible manipulation in other places during the render pass and it work ok. The visibility change may be delayed by a frame but that's not readily apparent to the viewer. My main point is that your change is only done for MyAvatar and we have the same issue in entities, overlays, and other avatars. 

I guess I'm just saying I'd rather see us be consistent across all the various producers of render items. 

With respect to the issue of the mirror scene. I can see how MyAvatar is particularly problematic. Since you want two different versions of the MyAvatar to render for the two different scenes. 

If thus preRender() is only needed to solve the mirror then ok for now, but let's add a FIX ME comment and make sure we go back and remove it after we have the two separate scenes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3d850f96de286576b16752e34968336833264ab available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc1a9914e4d30ad9474e86a045252ab61db2c2ff available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by PhilipRosedale** [comment]
Where are we on this one?   Ready to merge?

**Comment by ZappoMan** [comment]
Couple of bugs we found:
1) switching from body+head to separate body/head will not reset the first person skeleton
2) the mechbot model looks messed up
3) with separate head/body the head still seems to be displayed so you can see inside your own head

**Comment by hifi-gustavo** [comment]
Build console output for commit: 617b7213c842921a8ef0927d99fbed0fc1a4da3a available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by hyperlogic** [comment]
There still is a remaining issue with switching avatars while the mirror view is not active.  The old third person avatar is still visible after the switch.  Working on a fix now.

**Comment by hyperlogic** [comment]
Alright, switching avatars should work now for all cases.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6bb9e0b26644794f52a421bb6e7d5009f67bd577 available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a015ec354c5255925a7b35855849ea4d7bd8c148 available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c480c85f85a07eabac035e5f039677ff111bc103 available at: https://gist.github.com/2e74d5d028ed22cc2959<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5175.dmg

**Pull request merged**
