### PR TITLE
Build docs and dependency fixes

### PR DESCRIPTION
**Pull request by rudi-c**
Just some small things I ran into while trying to build on Linux Mint 17.2

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
ok to test

**Comment by rudi-c** [comment]
ok to test

**Comment by sethalves** [comment]
gustavo, you jerk

**Comment by rudi-c** [comment]
Haha what is this?

**Comment by thoys** [comment]
@rudi-c , gustavo is a bot, that tests the pull requests on Mac, Windows, and Linux, and creates a nice build for you. He didn't seem to respond, probably he's off for Labor day.

**Comment by thoys** [comment]
@murillodigital does @hifi-gustavo get triggered when only cmake files are modified?

**Comment by Atlante45** [comment]
Ok to test

**Comment by Atlante45** [comment]
add to whitelist

**Comment by Atlante45** [comment]
@thoys @sethalves @rudi-c Sometimes it doesn't trigger if it's not in the whitelist.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b703ce01fb61094d0c651ba9ef2148ae43106edf available at: https://gist.github.com/71a893f8a79154e7d21a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5729.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5729.dmg

**Pull request merged**
