### PR TITLE
VR menu fixes

### PR DESCRIPTION
**Pull request by jherico**
* Fixes the text of the login/logout menu item on the VR menu
* Fixes the ability for plugins to manipulate VR menu items

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ff3784e72a9b474c66714219a2e3c5e6ae89c92 available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1122fb4d007af607948797ab15e44c3d14228cf1 available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 93161f8c215dd38ceffa9db34f5699bce0c9df98 available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by jherico** [comment]
Testing:

* basic smoke test
* Login/Logout <Username> item on in-world menu should now reflect the same state as the one on the window menu
* Menu items created by plugins, such as the sixense developer menu or the 'mono' display option from a VR plugin should now appear in the VR menu

**Comment by hifi-gustavo** [comment]
Build console output for commit: e6c24321a156f77937963ae1eb718a8e328dfa93 available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d245ca6a3465225889c0474c0e749c44e64fa8c available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by cozza13** [comment]
I crash on exit https://www.bugsplatsoftware.com/keycrash/?stackKeyId=418&database=interface_alpha

**Comment by jherico** [comment]
Testing 

* Switch to Oculus mode, verify that the mono preview option appears in the VR menu inside the HMD
* Verify that the Login / Logout <Name> option on the VR menu always reflects the state of the main widget menu

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfc1d896cd57bf826fb57a1e7c5a94b6825425db available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfc1d896cd57bf826fb57a1e7c5a94b6825425db available at: https://gist.github.com/fbd66adf2191fe610a49ed9baa7efd06<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7617.dmg

**Comment by cozza13** [comment]
QA pass. tested with the menus

**Comment by Menithal** [comment]
- Login buttons shows up under files.
- When logged in, Logout button shows up under files.

Unrelated bugs:

Cannot navigate menu up and down reliably with the vive controller touchpad.

**Pull request merged**
