### PR TITLE
Beta Release 23 - Includes up to Developer Release 5456

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

**Specific Tutorial tests**

**Preparation**

Run through this each time you want to test this PR to ensure that you are in a "clean" state.

 1. Clear out your settings. You can do so by deleting (back it up if you need it) `C:/Users/USERNAME/AppData/Roaming/High Fidelity/Interface.ini`
 1. Delete:
   1. `C:\Users\USERNAME\AppData\Local\High Fidelity`
   1. `C:\Users\USERNAME\AppData\Local\High Fidelity - PR8627` (You might not have this)
   1. `C:\Users\USERNAME\AppData\Roaming\High Fidelity - PR8627` (You might not have this)

**To test the tutorial with the Vive:**

 1. On first load you should be taken to a dark room with tatami mats on the ground. Shortly after you should see text that tells you to raise your hands above your head. If you don't get to this point there is something wrong.
 1. Follow the tutorial - it should be self-explanatory. The steps are:
   1. Raise hands above head
   1. Raise hands above head (again)
   1. Near grab
   1. Far grab
   1. Equip lighter and light fuse
   1. Unequip lighter
   1. Turn using controller
   1. Teleport
   1. Go to portal on the right
 1. You should not be able to use far grab, equip, or teleport before you get to those steps.
 1. You should not be able to open the menu using the button above the trackpad.
 1. You should not see your avatar or the HUD (other than the HUD button) during the tutorial.
   1. You can click the HUD, open the address bar, etc., if you know what you are doing, but that is OK.
 1. Try playing around in the tutorial, see if there is anything that breaks through normal use. This should not include turning the HUD on, using your keyboard, etc., though.
 1. Did you notice any major issues?
1. Did you hear: environmental sounds, the sound of advancing to next level, the sound of the lighter clicking and butane, the sound of the firework exploding in the fire, the sound of the firework spinner?
1. Did you see the firework particles? 

**If you are not on a Vive:**

 1. On first launch (by clicking "Go Home"):
   1. You should see a help window popup that looks like https://github.com/huffman/hifi/blob/951a36854fdf0e9fe34cc4d373c2f21110e53ee2/interface/resources/html/img/controls-help-gamepad.jpg
     1. You should be able to click on the 3 tabs (KB/Mouse, Hand controllers, Game Controller)
   1. You should be taken to `Welcome`
 1. On second launch (by clicking "Go Home") you should be taken to your home server

**Parts of the client that have changed and should be tested in particular:**
 1. teleport.js
 1. handControllerGrab.js
 1. ATP downloading (are atp downloads failing?) (you don't have to test this directly, but go to areas that would stress this)
 1. Script downloading (are script downloads acting oddly?) (you don't have to test this directly, but go to areas that would stress this)

* display location and connection status in address bar when it doesn't have focus 
* Support external GL textures with proper fencing
* Initial work towards making performance testing reproducible
* Remove all usage of oglplus
* Fix model overlay visibility and texture properties
* Add ability to parent overlays to MyAvatar for use across servers
* Add category to log lines
* Fix intermittent channel swapping
* Fix CMAKE warning about un-unit-testable CPP file in physics unit tests
* Add flag to interface to have it start the sandbox server
* Fix 16khz support and hot-unplugging audio devices
This PR fixes two unrelated audio issues on Windows, by updating qtaudio_wasapi.dll. 
* Fix ScriptEngine not properly resolving paths
* Trigger unequip at a more lenient angle and with the secondary trigger
* Add setMapping to ATP scripting interface and fix threading bug
* added a command-line tool for checking on health of a domain-server and ACs 
* Add retrying of script requests
* Remove QML threaded rendering
* Fix script paths not resolving correctly
* HMD Keyboard
* Kill agents in avatar mixer when they stop being avatars
* Update teleport.js to ignore invisible or collisionless objects and disallow teleporting to certain surfaces
* init the accumulator for script elapsed time
* Updated Tutorial content
* Fix page size usage in gpu buffers

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8242f02a503808230df3ff33813e5420dec26f0 available at: https://gist.github.com/eae24d7529d5d849f248c14a1c1e6ebe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-d8242f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-d8242f0.dmg

**Comment by ctrlaltdavid** [comment]
Multiple QML warnings in program log at start-up:
```[WARNING] [default] file:///C:/Program Files/High Fidelity - PR8763/resources//qml/desktop/Desktop.qml:53: TypeError: Cannot call method 'indexOf' of undefined```

**Comment by ZappoMan** [comment]
Tested on Mac with DK2 performance is reasonable (same as last beta)

**Comment by hifi-gustavo** [comment]
Build console output for commit: e4d427eb13e508ecc708431017cc6a16fd89b877 available at: https://gist.github.com/eae24d7529d5d849f248c14a1c1e6ebe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-e4d427e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-e4d427e.dmg

**Comment by thoys** [comment]
## QA Test

### Vive Tutorial
1. content loaded
2. Follow Tutorial
   1. Hands up Works
   2. Another hands up works
   3. Putting fireworks in the fire FAIL
-- Tutorial stuck ^ : Found possible relevant error in the log:
```
[10/10 13:58:06] [WARNING] [hifi.scriptengine] [UncaughtException] TypeError: Result of expression 'controllerRight.setVisible' [undefined] is not a function. in Entities 3:65
[10/10 13:58:06] [WARNING] [hifi.scriptengine] [Backtrace]
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <anonymous>(visible = true) at atp:/tutorial/viveHandsv2.js:65
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <anonymous>(channel = 'Hifi-Object-Manipulation', message = '{"action":"grab","grabbedEntity":"{713d2035-a4bb-4a95-94a6-94095708c8fe}","joint":"RightHand"}', sender = '{01ec0e03-aacd-4e94-b742-dbe2f4190427}', false) at atp:/tutorial/viveHandsv2.js:166
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <global>() at -1
[10/10 13:58:06] [DEBUG] [hifi.scriptengine] script:print()<< Got away message
[10/10 13:58:06] [DEBUG] [hifi.scriptengine] script:print()<< settings controller display to visible
[10/10 13:58:06] [DEBUG] [hifi.scriptengine] script:print()<< doign it... true
[10/10 13:58:06] [WARNING] [hifi.scriptengine] [UncaughtException] TypeError: Result of expression 'controllerRight.setVisible' [undefined] is not a function. in Entities 3:65
[10/10 13:58:06] [WARNING] [hifi.scriptengine] [Backtrace]
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <anonymous>(visible = true) at atp:/tutorial/viveHandsv2.js:65
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <anonymous>(channel = 'Hifi-Object-Manipulation', message = '{"action":"release","grabbedEntity":"{713d2035-a4bb-4a95-94a6-94095708c8fe}","joint":"RightHand"}', sender = '{01ec0e03-aacd-4e94-b742-dbe2f4190427}', false) at atp:/tutorial/viveHandsv2.js:166
[10/10 13:58:06] [WARNING] [hifi.scriptengine]     <global>() at -1
```

Test still in progress, will continue when back home, but the above requires a fix

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU
Desktop Mode - 1600x900 maximized window


On first launch (by clicking "Go Home"):
You should see a help window popup that looks like https://github.com/huffman/hifi/blob/951a36854fdf0e9fe34cc4d373c2f21110e53ee2/interface/resources/html/img/controls-help-gamepad.jpg **Yes**

You should be able to click on the 3 tabs (KB/Mouse, Hand controllers, Game Controller) **Yes**

You should be taken to Welcome  **Yes**

On second launch (by clicking "Go Home") you should be taken to your home server **Yes**

Minor, but, annoying thing that people will notice.  Walking into home - bit of decking before door opening has only a couple areas where you can walk into structure without needing to jump. Suggest modifying its physics shape to fix that.

hifi-snap-by--on-2016-10-10_11-29-06

Not a fan of on screen keyboard when in desktop mode.

For instance - instead of simply seeing the login dialog when I attempted to go to a domain requiring logged in state - I get;

hifi-snap-by--on-2016-10-10_11-47-01

Then I click on keyboard overlay and get;

hifi-snap-by--on-2016-10-10_11-47-35

Then I click on input field for User Name or Email and go back to on screen keyboard instead of just being able to fill in my credentials like normal. I can't see my user name as I type it leading me to think it's not working -- then I click outside keyboard space and see text in the box.

I have to QA Fail this right here for desktop use.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU 4G VRAM

Attempting to load dev-playa I'm getting a lot of following in log;

[10/10 12:30:59] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:30:59] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:30:59] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:30:59] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:30:59] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:30:59] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:30:59] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:30:59] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:00] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:00] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:00] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:00] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:00] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:00] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:01] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:01] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:08] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:08] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:08] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:08] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:08] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:08] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:08] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:08] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:08] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:08] [DEBUG] [hifi.gpu.gl45] No available textures to derez
[10/10 12:31:15] [DEBUG] [default] Exceeded max GPU memory
[10/10 12:31:15] [DEBUG] [hifi.gpu.gl45] No available textures to derez

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bc8cf12a07bccbf02674cdf690621fc192aa6d3 available at: https://gist.github.com/eae24d7529d5d849f248c14a1c1e6ebe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-1bc8cf1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-1bc8cf1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ffb482383f58b1e28cf6a7c949c19f958f8cc24c available at: https://gist.github.com/eae24d7529d5d849f248c14a1c1e6ebe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-ffb4823.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-ffb4823.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68a1acfdd2df6b5a15f5502db080de27d2d7a58f available at: https://gist.github.com/eae24d7529d5d849f248c14a1c1e6ebe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-68a1acf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8763-68a1acf.dmg

**Comment by OmegaHeron** [comment]
Testing for i5 performance using same standard home scene as previous i5 profiling shows no change - performance remains good in i5 machines compared to last RC.  I am tracing an issue that seems to come from #8730 where starting with an empty cache results in 100% failure to retrieve any ATP hosted assets.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAIL
**Additional Test Results + Observations**:  Clear out settings by deleting ```C:/Users/USERNAME/AppData/Roaming/High Fidelity/Interface.ini``` and deleted '''C:\Users\USERNAME\AppData\Local\High Fidelity
C:\Users\USERNAME\AppData\Local\High Fidelity - PR8627 
C:\Users\USERNAME\AppData\Roaming\High Fidelity - PR8627'''
Tested on Oculus and did get screen shot and was in Welcome and tested teleport everything worked well however I agree with @OmegaHeron that the step in front of the little hut was frustrating as I had to jump.  Ultimately when I switched back and forth from HMD to Desktop crashed.  Attempted 3x and same occurred.  Sent bugsplat.

**Comment by OmegaHeron** [comment]
Recorded and sent bugsplat on change from DK2 to Desktop as well.

**Comment by OmegaHeron** [comment]
Latest build fixes issue with on screen keyboard and login dialog 👍 

But have 100% crash when switching from DK2 to Desktop mode - QA Fail

Bugsplats sent times 3.

**Comment by hevyw8** [comment]
## QA Test

**QA Tester**: adan (hevyw8)

 **QA FAIL**

### Test system:

system: win10-64
gpu: nvidia gtx1060
cpu: i5-6500 @ 3.2
mem: 32gb ddr4
HMD: Vive

**Additional Test Results + Observations**:

# Reasons For Failure:
- If SteamVR is unloaded and Interface launches in Desktop mode, Interface crashes every time. Multiple bug reports sent.
- Crashed 2x while switching form desktop to HMD - Sent Bug Reports

# Other undesirable behavior:
- Hadto restart Interface multiple times due to intractability issues. Did not gain hand controller function when switching from desktop to HMD, multiple times.
- My initial localhost load places me in the 'space' environment that typically indicates no local host. After that clicking 'home' takes me to original home content.


# Vive Tutorial Specific Tests:
All Criteria Met

# i5 perfomance with relation to 'Remove QML threaded rendering':
Performance is substantially better than current live beta release. There is still some stuttering during load periods such as moving to a domain. And when interacting with marketplace tablet and spawning bowling balls on lane in welcome.

# Partial Smoke Test
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS

Did not get to remaining smoke tests.

**Comment by Nex-Pro** [comment]
### PR #8763

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used

**Starting conditions:**

        Fresh install of interface and sandbox.
        Requested reset of settings prior to launch.
        Steam VR renderTargetMultiplier at default setting.
**----------------------------------------------------------------------**
Clear out your settings. You can do so by deleting (back it up if you need it) C:/Users/USERNAME/AppData/Roaming/High Fidelity/Interface.ini
Delete:
C:\Users\USERNAME\AppData\Local\High Fidelity: **Check**
C:\Users\USERNAME\AppData\Local\High Fidelity - PR8627 (You might not have this): **Check**
C:\Users\USERNAME\AppData\Roaming\High Fidelity - PR8627 (You might not have this): **Check**
To test the tutorial with the Vive:

On first load you should be taken to a dark room with tatami mats on the ground.
Shortly after you should see text that tells you to raise your hands above your head.
If you don't get to this point there is something wrong. : ***Had to restart in order for this to work.***
Follow the tutorial - it should be self-explanatory. The steps are:
Raise hands above head: **SUCCESS**
Raise hands above head (again): **SUCCESS**
Near grab: **SUCCESS**
Far grab: **SUCCESS**
Equip lighter and light fuse: **SUCCESS**
Unequip lighter: **SUCCESS**
Turn using controller: **SUCCESS**
Teleport: **SUCCESS**
Go to portal on the right: **SUCCESS**


***Ran thru this multiple times***

You should not be able to use far grab, equip, or teleport before you get to those steps. : **SUCCESS**
You should not be able to open the menu using the button above the trackpad. : **SUCCESS**
You should not see your avatar or the HUD (other than the HUD button) during the tutorial. **PARTIAL SUCCESS** I had the hud half way up my view at the start of one run.
You can click the HUD, open the address bar, etc., if you know what you are doing, but that is OK.: **Check**
Try playing around in the tutorial, see if there is anything that breaks through normal use. 
This should not include turning the HUD on, using your keyboard, etc., though.
Did you notice any major issues? ***Apart from needing to restart none.***
Did you hear: environmental sounds,: **SUCCESS**
the sound of advancing to next level, : **SUCCESS**
the sound of the lighter clicking and butane, : **SUCCESS**
the sound of the firework exploding in the fire, : **SUCCESS**
the sound of the firework spinner?: **SUCCESS**
Did you see the firework particles?: **SUCCESS**

Occasionally the TP Blue circle remains after releasing the button on the hand controller.
On one run I was unable to enter the garden as I was getting cancel TP circles at the doorway between the house and garden as if hitting an invisible entity.
Occasionally the red ball that is normally at the near end of the fuse is on the floor.
As alan noticed it is possible to light the fuse a total of three times.
The Catharine-Wheel firework sound can be heard on subsequent fuse lightings after the Wheel has de-rezzed.
I really dislike the squeeze to release idea especially as it releases items held with the trigger.
This is making throwing things difficult. When I throw a ball or one of the welcome area boxes I grip the controller harder this means I now drop the held item.
This needs to be optional or abandoned IMO.

## QA Test
**QA Tester**: Unknown user
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS

**QA Pass**: SUCCESS

**Additional Test Results + Observations**: 
    Saw some objects at Dev-Playa rendered in the wrong location. 
    Looking away and back fixed it.
    Basically several of the static objects that would be at ground level were 20 or 30 metres up in the air.
    @zappoman I tried to repro this without success.( cleared cache then returned to dev-playa )
    Enabling ambient occlusion floods the log continuously with messages of the following type.(not specific to this PR)
        [10/11 00:07:30] [DEBUG] [hifi.gpu.gl45] Generating mipmaps for  LinearDepthFramebuffer::_halfLinearDepthTexture


### Domain Statistics

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |89 |90
**Present New Rate**: |90 |90 |88
**CPU Buffer Count**: |2646 |4631 |4074
**GPU Buffer Count**: |85787 |75258 |83346
**CPU Memory Usage**: |25948160 |67002368 |52248576
**GPU Memory Usage**: |361394176 |343187456 |364355584
**CPU Texture Count**: |196 |279 |285
**GPU Texture Count**: |4294873655 |4294888569 |4294881901
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |67729608 |253496864 |95098808
**GPU Texture Memory Usage**: |395247616 |934084608 |1088143360
**GPU Virtual Memory Usage**: |977376519|2206142039|1615939081
**Triangle Count**: |452758 |2789264 |1213331
**Triangle Rate**: |41159818 |253569454 |110302818
**API Drawcall Count**: |160 |378 |358
**Drawcall Count**: |5638 |826 |2516
**Drawcall Rate**: |512545 |75090 |228727
**State Changes Texture Count**:|273 |389 |445
**Pipeline Count**: |71 |40 |58
**Item Opaques**: |195 |809 |292
**Item Translucents**: |101 |47 |44
**Item Lights**: |16 |95 |16
**Timing Opaques**: |0.7 |2.472 |1.098
**Timing Translucents**: |0.17 |0.107 |0.201
**Timing Lighting**: |0.433 |0.466 |0.471
**Render Frame**: |3.125 |5.909 |4.005



teleport.js: Occasionally I get the blue ring remaining at the tp point.( I have seen this in other recent builds )

handControllerGrab.js: Seems fine apart from the drop grabbed items with squeeze which is horrible.

ATP downloading (are atp downloads failing?) : Tried uploading a known working animated FBX. When I placed in world and set up the animation it played ok.
Script downloading (are script downloads acting oddly?) (you don't have to test this directly, but go to areas that would stress this)
display location and connection status in address bar when it doesn't have focus: **SUCCESS**

Trigger unequip at a more lenient angle and with the secondary trigger: **SUCCESS** But dropping trigger-held entities this was seems a bad idea. Try throwing boxes around.

Update teleport.js to ignore invisible or collisionless objects and disallow teleporting to certain surfaces: ***This needs a re-think IMO  I can't TP up to something that I could previously leading to much frustration.***

Updated Tutorial content: **SUCCESS**

**Pull request closed without merging**
