### PR TITLE
Login dialog rework

### PR DESCRIPTION
**Pull request by vladest**
Based on true story in: https://highfidelity.fogbugz.com/f/cases/7895/HMD-Tablet-login-refactoring

Test plan:
- Try login/logout/create account in Tablet/Desktop modes
- Try getting to login dialog from Snapshot app in both Tablet/Desktop modes
- check if all controls in place and looks ok
- check virtual keyboard in HMD, ensure it's in the correct place and isn't visually clipping through any other control

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3756/HighFidelity-Beta-PR11489-d3cd034d614cc9285baf4ca7bb975c721ba07ae9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3756/HighFidelity-Beta-PR11489-d3cd034d614cc9285baf4ca7bb975c721ba07ae9.exe

**Comment by changxc** [comment]
spot one bug - virtual keyboard is cut off

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3803/HighFidelity-Beta-PR11489-bf39eb9a77dadd889f6593b9ae39c97ba2235c83.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3803/HighFidelity-Beta-PR11489-bf39eb9a77dadd889f6593b9ae39c97ba2235c83.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3884/HighFidelity-Beta-PR11489-073fa81d5bf400d43596f686d4797b9d1fc2cd71.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3884/HighFidelity-Beta-PR11489-073fa81d5bf400d43596f686d4797b9d1fc2cd71.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3887/HighFidelity-Beta-PR11489-86e8076362ce1f39547aa6845d14231c7c916df3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3887/HighFidelity-Beta-PR11489-86e8076362ce1f39547aa6845d14231c7c916df3.exe

**Comment by Nex-Pro** [comment]
T E S T I N G   this  Win10

**Comment by Nex-Pro** [comment]
Try login/logout/create account in Tablet/Desktop modes **SUCCESS**
Try getting to login dialog from Snapshot app in both Tablet/Desktop modes **SUCCESS**
check if all controls in place and looks ok **SUCCESS**
check virtual keyboard in HMD, ensure it's in the correct place and isn't visually clipping through any other control **SUCCESS**

Shortcomings.
in desktop mode there is no obvious option to log out via the menu or the toolbar->file  menu. In fact logging out is achieved by clicking on login then cancel.
In both desktop and HMD mode there is no confirmation of password apart from "Show password" option.

While interacting with the tablet I noticed that I got a blue sphere that would swell in size to fill my view. See image. Will check this against latest dev build.

hifi-snap-by-starman-on-2017-10-04_23-05-53

**Comment by zfox23** [comment]
Thanks for your test, @Nex-Pro. I'm going to call this a PASS - I feel confident that the blue sphere is not due to these code changes. I'll note your feedback. :)

**Pull request merged**
