### PR TITLE
fix crash from zero-sized copy

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

This will occasionally occur in playa on latest build. It is a crash in GL, but I think it manifests as an access violation. Load the playa and walk around a few times and make sure everything is good.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c6d5f82e1331559a9aaa4aac1e78937e72fdceb available at: https://gist.github.com/d3ff1716fc4ac6ae7c3cc8a0e76236c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30a605ef87e346b2c64cf442d0a1e7257eac4f1c available at: https://gist.github.com/d3ff1716fc4ac6ae7c3cc8a0e76236c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Signifcant lag introduced on ```playa```. Render rate average 30. Visited similar domains and same performance. Log file inclued for deeper analysis.


**Domain** | |Playa |
---|---|---|---
**Render Rate**: | |26 |
**Present Rate**: | |60 |
**Present New Rate**: | |24 |
**CPU Buffer Count**: | |4814 |
**GPU Buffer Count**: | |1364 |
**CPU Memory Usage**: | |95002624 |
**GPU Memory Usage**: | |64733184 |
**CPU Texture Count**: | |805 |
**GPU Texture Count**: | |773 |
**GPU Transfer Count**: | |0 |
**CPU Texture Memory Usage**: | |187647936 |
**GPU Texture Memory Usage**: | |4399948985 |
**GPU Virtual Memory Usage**: ||4399948985|
**Triangle Count**: | |208127 |
**Triangle Rate**: | |5781305 |
**API Drawcall Count**: | |79 |
**Drawcall Count**: | |79 |
**Drawcall Rate**: | |2194 |
**State Changes Texture Count**:| |91 |
**Pipeline Count**: | |19 |
**Item Opaques**: | |108 |
**Item Translucents**: | |2 |
**Item Lights**: | |20 |
**Timing Opaques**: | |22875 |
**Timing Translucents**: | |15 |
**Timing Lighting**: | |1488 |
**Render Frame**: | |32909 |
[hifi-log.txt](https://github.com/highfidelity/hifi/files/272339/hifi-log.txt)

**Comment by zzmp** [comment]
I believe this is due to reduced rate on master right now.
I'll rebase it once that is resolved, and we can try again.

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: fff260c2b9bcadd9d1a0d5597dd34b895edc491d available at: https://gist.github.com/d3ff1716fc4ac6ae7c3cc8a0e76236c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7930.dmg

**Comment by kevinmthomas-carpool** [comment]
re-testing

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Performance significantly improved.  Not at exactly 60 but workable and performance was not affected.  Everything worked great at ```playa``` with no issue of any kind.  

**Domain** | |Playa |
---|---|---|---
**Render Rate**: | |46 |
**Present Rate**: | |60 |
**Present New Rate**: | |46 |
**CPU Buffer Count**: | |5406 |
**GPU Buffer Count**: | |1869 |
**CPU Memory Usage**: | |98988032 |
**GPU Memory Usage**: | |73879552 |
**CPU Texture Count**: | |365 |
**GPU Texture Count**: | |682 |
**GPU Transfer Count**: | |0 |
**CPU Texture Memory Usage**: | |74673872 |
**GPU Texture Memory Usage**: | |2533633173 |
**GPU Virtual Memory Usage**: ||2671320213|
**Triangle Count**: | |1251026 |
**Triangle Rate**: | |65843473 |
**API Drawcall Count**: | |290 |
**Drawcall Count**: | |334 |
**Drawcall Rate**: | |17578 |
**State Changes Texture Count**:| |337 |
**Pipeline Count**: | |28 |
**Item Opaques**: | |374 |
**Item Translucents**: | |27 |
**Item Lights**: | |42 |
**Timing Opaques**: | |2718 |
**Timing Translucents**: | |210 |
**Timing Lighting**: | |199 |
**Render Frame**: | |4067 |

**Pull request merged**
