### PR TITLE
Fix particle uniform buffer issue

### PR DESCRIPTION
**Pull request by SamGondelman**
Particles were always using 0 as the location of their uniform buffer, which was interfering with the deferred lighting uniform buffers (possibly because there's something wrong with custom pipelines?).  This changes the location used by particles (and polylines, just in case) to avoid the issue.

https://highfidelity.fogbugz.com/f/cases/11289/Texture-rendering-changes-based-on-camera-angle

Test plan:
- Launch the sandbox from this PR so that you have the default content set.  From your starting location, look around (see the gif in the fogbugz case).  The two teleporter entities (the one on the table near you and the one that takes you to a different domain) should continue to render normally.
- The particle effects that make the smoke throughout the area should render correctly.
- Download the Fingerpaint app and draw some polylines.  They should render correctly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6202/app_12141_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6202/HighFidelity-Beta-PR12141-e9d751fd23f85b980aa47faf702b89292c01e20d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6202/HighFidelity-Beta-PR12141-e9d751fd23f85b980aa47faf702b89292c01e20d.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed. PASSED.

**Pull request merged**
