### PR TITLE
FB17161 - Avatar App Not Populating Thumbnails

### PR DESCRIPTION
**Pull request by ElderOrb**
note: attempt to resolve shader issues on Mac by reimplementing without explicit shader code

https://highfidelity.fogbugz.com/f/cases/17161/Avatar-App-Not-Populating-Thumbnails

**Test plan**

1. Open 'avatarapp' on Mac, ensure avatar thumbnails gets populated *and* still have round corners
Bonus: Ensure it also works on Windows/Linux/Android

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11782/HighFidelity-Beta-PR13734-d4584ef.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11782/HighFidelity-Beta-PR13734-d4584ef.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11782/HighFidelity-Beta-Interface-PR13734-d4584ef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11782/HighFidelity-Beta-PR13734-d4584ef.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11782/HighFidelity-Beta-Interface-PR13734-d4584ef.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11787/HighFidelity-Beta-PR13734-39767ec.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11787/HighFidelity-Beta-PR13734-39767ec.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11787/HighFidelity-Beta-Interface-PR13734-39767ec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11787/HighFidelity-Beta-PR13734-39767ec.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11787/HighFidelity-Beta-Interface-PR13734-39767ec.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11873/HighFidelity-Beta-PR13734-39767ec.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11873/HighFidelity-Beta-Interface-PR13734-39767ec.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11873/HighFidelity-Beta-PR13734-39767ec.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11873/HighFidelity-Beta-Interface-PR13734-39767ec.dmg

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11944/HighFidelity-Beta-PR13734-39767ec.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11944/HighFidelity-Beta-PR13734-39767ec.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11944/HighFidelity-Beta-Interface-PR13734-39767ec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11944/HighFidelity-Beta-PR13734-39767ec.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11944/HighFidelity-Beta-Interface-PR13734-39767ec.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 . Thumbnails do not load on Mac, but thumbnails do load on windows. No linux machine available to test on
[PR13734.zip](https://github.com/highfidelity/hifi/files/2274756/PR13734.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12445/HighFidelity-Beta-PR13734-02e6a7c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12445/HighFidelity-Beta-PR13734-02e6a7c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12445/HighFidelity-Beta-Interface-PR13734-02e6a7c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12445/HighFidelity-Beta-PR13734-02e6a7c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12445/HighFidelity-Beta-Interface-PR13734-02e6a7c.exe

**Pull request closed without merging**
