### PR TITLE
JSDoc updates

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.,

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10189/HighFidelity-Beta-PR13251-0db440931ef24f5b268fdfe82776e48996cddad9.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10190/HighFidelity-Beta-PR13251-08cb5c71918d099c55f4c261e462a6d4418b0e9a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10190/HighFidelity-Beta-PR13251-08cb5c71918d099c55f4c261e462a6d4418b0e9a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10190/HighFidelity-Beta-Interface-PR13251-08cb5c71918d099c55f4c261e462a6d4418b0e9a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10190/HighFidelity-Beta-PR13251-08cb5c71918d099c55f4c261e462a6d4418b0e9a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10190/HighFidelity-Beta-Interface-PR13251-08cb5c71918d099c55f4c261e462a6d4418b0e9a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10343/HighFidelity-Beta-PR13251-b5028a9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10343/HighFidelity-Beta-PR13251-b5028a9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10343/HighFidelity-Beta-Interface-PR13251-b5028a9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10343/HighFidelity-Beta-PR13251-b5028a9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10343/HighFidelity-Beta-Interface-PR13251-b5028a9.exe

**Pull request merged**
