### PR TITLE
Point index finger and raise thumb if not touching controller

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

In Rift with Touch controllers.
- If you raise your index finger off the trigger, your avatar's index finger points. Left and right hands independently.
- If you raise your thumb so that it's not touching any controls, your avatar's thumb raises. Left and right hands independently.
- Squeezing the grip still curls the fingers and thumbs, but index finger pointing and thumb raising overrides the curling.
- If you're painting with the fingerPaint.js script, both index fingers point regardless of whether your fingers are on the triggers or not.

Test operation in Vive with Vive controllers, also.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cc499b08b04ad84bedb845af09336f33b1b6521 available at: https://gist.github.com/64dc007538a41794cba6420547f25b56<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9756-0cc499b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9756-0cc499b.dmg

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

**TESTING USING VIVE - SOMEONE ELSE TEST WITH TOUCH**

* Did clean install and tested with Vive controllers
* Tested generic hand movements such as grabbing, squeezing, trigger and those all worked as before
* Since this test specifically mentions the Rift and Touch controllers I assume these changes are meant for this controller and not the vive and the vive tests were just to verify it still functions as it is supposed to.
* If the changes are supposed to affect the Vive also then this is a fail, if its just for the touch then it is a pass.
* I did note that on finger painting the pointer does indeed point forward and paint works well with it.

**PASS if changes are just meant for Touch controllers**

@ctrlaltdavid - are these changes supposed to work on the Vive also or is this just to verify the Vive still works as it is supposed to?

**Comment by ctrlaltdavid** [comment]
@nbq Thanks very much for testing Vive, to make sure that this PR doesn't break anything for Vive users. This PR uses the Touch controller's capacitive sensors on triggers, buttons, and joysticks. (I believe that the Vive controllers don't.)

**Comment by PhilipRosedale** [comment]
Testing on touch...  passed.  Looks great!

**Pull request merged**
