### PR TITLE
fix issue with textures with alpha as a mask

### PR DESCRIPTION
**Pull request by birarda**
- fixed an issue with incorrect processing of textures with alpha as mask

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Use this Avatar FST:
https://hifi-content.s3.amazonaws.com/ozan/dev/avatars/hifi_team/zfox/morph/zfox.fst

On master if you go into mirror (H key) you should see a very frightening sight that looks like this.

ezgif-1-5c4e55a728

The hands will also be "see-through".

On this PR, the avatar face and hands should look normal.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/210/HighFidelity-Beta-PR10560-07440e325ffdce499df865dd5109eac753c448db.exe

**Comment by StarmanF** [comment]
testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/210/HighFidelity-Beta-PR10560-07440e325ffdce499df865dd5109eac753c448db.dmg

**Comment by zfox23** [comment]
QA Pass from me - will wait to apply the label until @StarmanF confirms this is a pass as well.

**Comment by OmegaHeron** [comment]
Same for me as it fixes an issue I was seeing so I tested as well -- this and #10559 together fixes all the ills in current Master builds.

**Comment by zfox23** [comment]
I think it's safe to push the merge button, @birarda!

**Comment by StarmanF** [comment]
Yep, QA Pass from me too. Sorry for the delay.

**Pull request merged**
