### PR TITLE
A couple macOS HQ Launcher bug fixes

### PR DESCRIPTION
**Pull request by MattHardcastle**
I've pulled together a couple bug fixes here. Please let me know if you'd like them broken up.

1) Never cache the tags API
2) Use version from Interface before attempting version from settings file
3) Pin target version to 10.9
4) CMake should fail when `LAUNCHER_HMAC_SECRET` isn't set

1 and 2 are related to [BUGZ-767](https://highfidelity.atlassian.net/browse/BUGZ-767). The other two are just minor issues I noticed while working in the code. More details on the issues and my approach to solving them can be found in the commit messages.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20098/HighFidelity-Beta-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20098/HighFidelity-Beta-Interface-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20098/HighFidelity-Beta-PR15824-4f6e2c8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20098/HighFidelity-Quest-Beta-PR15824-4f6e2c8.apk)

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20100/HighFidelity-Beta-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20100/HighFidelity-Beta-Interface-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20100/HighFidelity-Beta-PR15824-4f6e2c8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20100/HighFidelity-Quest-Beta-PR15824-4f6e2c8.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20103/HighFidelity-Beta-PR15824-4f6e2c8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20103/HighFidelity-Quest-Beta-PR15824-4f6e2c8.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20103/HighFidelity-Beta-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20103/HighFidelity-Beta-Interface-PR15824-4f6e2c8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20112/HighFidelity-Beta-PR15824-9ae67c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20112/HighFidelity-Beta-Interface-PR15824-9ae67c1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20112/HighFidelity-Beta-PR15824-9ae67c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20112/HighFidelity-Beta-Interface-PR15824-9ae67c1.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20112/HighFidelity-Beta-PR15824-9ae67c1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20112/HighFidelity-Quest-Beta-PR15824-9ae67c1.apk)

**Pull request merged**
