### PR TITLE
Add @signal tag; format "Supported Script Types" 

### PR DESCRIPTION
**Pull request by ingerjm0**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17549/HighFidelity-Beta-PR15002-93ca565.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17549/HighFidelity-Beta-PR15002-93ca565.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17549/HighFidelity-Beta-Interface-PR15002-93ca565.dmg

**Comment by ctrlaltdavid** [comment]
1) The dot separator between the "available in" entries doesn't display properly in a Web browser:
image
If you replace the dot character in the script with one of, `&bull;` or `&#x25CF;` or similar, it will display OK in a Web browser.

2) I tried replacing `@function` with `@signal` in AccountServices API but that stopped the signal JSDoc from appearing at all.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17549/HighFidelity-Beta-PR15002-93ca565.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17549/HighFidelity-Beta-Interface-PR15002-93ca565.exe

**Comment by ingerjm0** [comment]
Opening separate PR from branch rather than master.

**Pull request closed without merging**
