### PR TITLE
Handshake cleanup

### PR DESCRIPTION
**Pull request by howard-stearns**
Clean handshake code and make it more robust and efficient. Give user better info for some common failure modes.

See individual commit messages.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f980d6f4358dea01e50d38f388e7d543bc0eacc6 available at: https://gist.github.com/b529c12a18f6a709e18decd5addfeed4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10333-f980d6f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10333-f980d6f.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f980d6f4358dea01e50d38f388e7d543bc0eacc6 available at: https://gist.github.com/b529c12a18f6a709e18decd5addfeed4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10333-f980d6f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10333-f980d6f.dmg

**Comment by howard-stearns** [comment]
tested in standup

**Pull request merged**
