### PR TITLE
delay NL reset on login until new username is known

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8841/app_12913_PR_898d61fcf72aaaac5bd8fc4c723f1b3b4a23113b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8841/HighFidelity-Beta-PR12913-898d61fcf72aaaac5bd8fc4c723f1b3b4a23113b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8841/HighFidelity-Beta-Interface-PR12913-898d61fcf72aaaac5bd8fc4c723f1b3b4a23113b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8841/HighFidelity-Beta-PR12913-898d61fcf72aaaac5bd8fc4c723f1b3b4a23113b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8841/HighFidelity-Beta-Interface-PR12913-898d61fcf72aaaac5bd8fc4c723f1b3b4a23113b.exe

**Comment by birarda** [comment]
#### Test Plan

This fixes https://highfidelity.fogbugz.com/f/cases/14181/Admin-Panel-Not-Showing-Up. There's a race between when Interface hears back about its username and when it attempts to re-connect to the domain after logging in. 

You can force the issue to occur by using https://jagt.github.io/clumsy/, adding an inbound lag of 500ms for a filter of `tcp and (tcp.DstPort == 443 or tcp.SrcPort == 443)`. This should cause Interface to attempt to re-connect to the domain before it hears about its username. Use this setup for testing on master and with this PR.

1. On master, be logged out and connect to a domain in which you will "Can Kick" permissions once logged in. 
2. Confirm that the "People" app does not show an "Admin" column.
3. Login while connected to the domain. Confirm that the "People" app still does not show an "Admin" column (this repros the bug).
4. Go to a different domain and then re-connect to the domain. Confirm that the "People" app shows an "Admin" column.
5. Use this PR and re-perform steps 1-3. Confirm that in step 3 the "People" app shows an "Admin" column.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
After logging in the Admin column appeared.

**Pull request merged**
