### PR TITLE
Add Interface "Home" bookmark function

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Navigate > Set Home Location: sets "Home" bookmark to current location.
"Home" button on address bar: takes user to "Home" bookmark if set, otherwise to localhost.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing notes:
- User can also set "Home" bookmark via Navigate > Bookmark Location.
- "Home" bookmark name is case-sensitive.
- There's a known bug wherein the "back", "forward", and now also "home" buttons only work once per address bar dialog display. This is addressed in https://github.com/highfidelity/hifi/pull/7767

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e00a1ef49828f490a857ee12d2aa8575f6db06d available at: https://gist.github.com/0f0bd0a9e946d1de1deb86bf30e8f7a8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7768.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7768.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7768
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** music
**Additional Test Results:**  Upon login, logged in from ```localhost``` and went to ```music``` and set home bookmark to a particular coordinate in ```music```.  Manually moved to ```localhost``` again and tested the home button and it successfully took me to the aforementioned position in ```music```.  Successfully clicked the back button to back to localhost and then the buttons were no longer workable and did not respond to a mouse click event.
**Successful Logout/Crash:** Successful logout.
home1
home2

**Comment by ctrlaltdavid** [comment]
Note: "the buttons were no longer workable and did not respond to a mouse click event" is "expected" behaviour; is being addressed in PR https://github.com/highfidelity/hifi/pull/7767 .

**Comment by ctrlaltdavid** [comment]
(Oops ... pressed the wrong button)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e00a1ef49828f490a857ee12d2aa8575f6db06d available at: https://gist.github.com/0f0bd0a9e946d1de1deb86bf30e8f7a8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7768.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7768.dmg

**Pull request merged**
