### PR TITLE
Remove Marketplace's dependency on Edit.js for REZ/WEAR

### PR DESCRIPTION
**Pull request by zfox23**
NOTE: This PR adds some code that is _duplicated_ from `edit.js`. It's up to the code reviewer to determine if I should put the effort in to pull this code out from JS and into some common C++ (say, inside the Entity Scripting Interface).

**Test Plan:**
1. Enable Commerce & set up your wallet.
2. Buy a Test Beach Ball from the Marketplace. On the Purchase Confirmation screen, click the "Rez" button. Verify that the beach ball shows up in front of you.
3. Move left a few steps. Go to My Purchases. Click the "REZ" button next to the beach ball. Verify that the beach ball from (2) disappears and that you see a new beach ball appear in your domain.
4. Buy a Purple Scarf from the Marketplace. On the Purchase Confirmation screen, click the "Wear" button. Verify that the purple scarf shows up at your hips.
5. Delete the Purple Scarf from your hips.
6. Go to My Purchases. Click the "WEAR" button next to the purple scarf. Verify that the purple scarf shows up at your hips. Close My Purchases.
7. Open your Domain Settings Page. Scroll to "Security", then UNCHECK "Rez", "Rez Temp", "Rez Certified", and "Rez Temp Certified" permissions for `localhost`. Click Save.
8. Go to My Purchases. Verify that the "REZ" button next to the test beach ball is disabled. Verify that the "WEAR" button next to the purple scarf is enabled.
9. Click the "WEAR" button next to the purple scarf. Verify that the purple scarf shows up at your hips. Close My Purchases.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Awaiting win build for QA

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4937/HighFidelity-Beta-PR11813-d6c244d1d5690e07288e0cc9b7125bed14ac4461.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4937/HighFidelity-Beta-PR11813-d6c244d1d5690e07288e0cc9b7125bed14ac4461.exe

**Comment by Nex-Pro** [comment]
### PASS

Test Plan:

Enable Commerce & set up your wallet.

Buy a Test Beach Ball from the Marketplace. 

On the Purchase Confirmation screen, click the "Rez" button. 
Verify that the beach ball shows up in front of you.

Move left a few steps.

Go to My Purchases. 

Click the "REZ" button next to the beach ball. 

Verify that the beach ball from (2) disappears and that you see a new beach ball appear in your domain. **SUCCESS**

Buy a Purple Scarf from the Marketplace. 
On the Purchase Confirmation screen, click the "Wear" button. 

Verify that the purple scarf shows up at your hips. **SUCCESS**

Delete the Purple Scarf from your hips.

Go to My Purchases. Click the "WEAR" button next to the purple scarf. 

Verify that the purple scarf shows up at your hips. **SUCCESS** 

Close My Purchases.

Open your Domain Settings Page. 
Scroll to "Security", then UNCHECK "Rez", "Rez Temp", "Rez Certified", and "Rez Temp Certified" permissions for localhost. 
Click Save.

Go to My Purchases. 

Verify that the "REZ" button next to the test beach ball is disabled. **SUCCESS** 

Verify that the "WEAR" button next to the purple scarf is enabled. **SUCCESS**

Click the "WEAR" button next to the purple scarf.

Verify that the purple scarf shows up at your hips. **SUCCESS** 

Close My Purchases.

**Pull request merged**
