### PR TITLE
Moving Sixense to external plugin

### PR DESCRIPTION
**Pull request by jherico**
Move Sixense integration for Hydras to a DLL based plugin

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6977a5f6f7b65c6cad3347fecdf8168d6f2da024 available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6977a5f6f7b65c6cad3347fecdf8168d6f2da024 available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 41ace38b302d875901bada000d4ead0f4e2c3705 available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6600-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by hyperlogic** [comment]
For consistency should we rename the oculus plugin to hifiOculus.dll?

**Comment by hyperlogic** [comment]
When running from the installer, it did not detect my hydra and the menu item for enabling it was not present.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec66c7e40be4b287989e377a6acf3acd2f0430bb available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6600-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 645695d5d546676d8963a9e3aa685c984923afcf available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6600-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by ZappoMan** [comment]
When I run this installer, I end up with a build that has no Hydra support.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09a9b978a1fc5674a7571d75eec1955060009855 available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6600-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5f5e8de60d84f5f8930ac5fc032b88d1e8b8de8 available at: https://gist.github.com/c1902eb129c79eb6752d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6600-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6600.dmg

**Comment by jherico** [comment]
@hyperlogic the only reason I named SDL2 and Sixense as 'hifiSdl2' and 'hifiSixense' is that otherwise their DLL names would directly conflict with the respective SDK provided DLLs.  An application can't easily have two different copies of sixense.dll loaded at runtime, so I renamed our DLLs.  I don't really want to mess with the naming any more than I have to though.

**Pull request merged**
