### PR TITLE
Fix tablet focus issue when property menu is open and field is selected

### PR DESCRIPTION
**Pull request by TurnMeUp-OG**
Code Review for Job #21470 - Workitem available at https://www.worklist.net/21470

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2032/HighFidelity-Beta-PR11061-33ff5917be70f26b4b5472c52661fcfd8ddfc9c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows2016/2032/HighFidelity-Beta-PR11061-33ff5917be70f26b4b5472c52661fcfd8ddfc9c5.exe

**Comment by themelissabrown** [comment]
Can I get a test plan for this so I can have it QA'd?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2174/HighFidelity-Beta-PR11061-9b28d546e037f5dc1a9b1a4cd729ea26f4deb73d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2174/HighFidelity-Beta-PR11061-9b28d546e037f5dc1a9b1a4cd729ea26f4deb73d.exe

**Comment by TurnMeUp-OG** [comment]
**Test Plan**
Launch the domain-server and interface, connect to the domain.
Create a variety of objects in the “CREATE” menu
Check the proper functioning of the “CREATE > PROPERTIES” form
Repeat the clauses 2-4 several times 
• Open CREATE > PROPERTIES
• Choose a random object
• Pick out any property
• Choose another random object
When choosing a new object in the properties editor form, the fields should have no focus.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Launch the domain-server and interface, connect to the domain. **Check**
Create a variety of objects in the “CREATE” menu **Check**
Check the proper functioning of the “CREATE > PROPERTIES” form **Check**
Repeat the clauses 2-4 several times **Check**
• Open CREATE > PROPERTIES **Check**
• Choose a random object **Check**
• Pick out any property **Check**
• Choose another random object **Check**
When choosing a new object in the properties editor form, the fields should have no focus. **Check**

Looks like a solid **Pass** to me. :)

**Pull request merged**
