### PR TITLE
DEV-2764, DEV-2113: Remove Avatar app links to AvatarIsland and BodyMart

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes:
- Removed image and link to Avatar Island in the "get more wearables" pop-up.
- Removed image and link to BodyMart in the "get more avatars" pop-up.

Also:
- Replaced "AvatarIsland" with "DomainName" in examples given in the AddressManager JSDoc.
- Removed the BodyMart tip from the interstitial page script.

Cases:
- https://highfidelity.atlassian.net/browse/DEV-2764
- https://highfidelity.atlassian.net/browse/DEV-2113

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22605/HighFidelity-Beta-PR16506-0b98885.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22605/HighFidelity-Quest-Beta-PR16506-0b98885.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22605/HighFidelity-Beta-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22605/HighFidelity-Beta-Interface-PR16506-0b98885.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22611/HighFidelity-Beta-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22611/HighFidelity-Beta-Interface-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22611/HighFidelity-Beta-PR16506-0b98885.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22611/HighFidelity-Quest-Beta-PR16506-0b98885.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22614/HighFidelity-Beta-PR16506-0b98885.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22614/HighFidelity-Quest-Beta-PR16506-0b98885.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22614/HighFidelity-Beta-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22614/HighFidelity-Beta-Interface-PR16506-0b98885.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22622/HighFidelity-Beta-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22622/HighFidelity-Beta-Interface-PR16506-0b98885.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22622/HighFidelity-Beta-PR16506-0b98885.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22622/HighFidelity-Quest-Beta-PR16506-0b98885.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22622/HighFidelity-Beta-PR16506-0b98885.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22622/HighFidelity-Beta-Interface-PR16506-0b98885.exe

**Pull request merged**
