### PR TITLE
Fixed crash when launching interface from fresh install

### PR DESCRIPTION
**Pull request by druiz17**
I commented out a line of code that sets the contextProperty for lastMousePosition for QML Tooltip. I don't understand why setContextProperty is crashing. Since Tooltip is currently not being used anywhere in QML, I just commented out the code and added a TODO comment to further investigate the issue.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan 
- download the PR and run interface.
- there should not be a crash on launch.
- relaunch interface about 5 times to make sure the crash does not happen but before you launch interface again remove the PR's high fidelity data from AppData/Local

**Comment by YuppyPlays** [comment]
Will test when built :)

**Comment by anshuman64** [comment]
@YuppyPlays please do a clean install of the PR when trying: https://docs.google.com/document/d/1DdVhgQOLkcmX4yYTcVK_lQTTpGhT0x6EFtOQ2sdGHe8/edit

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1500/HighFidelity-Beta-PR10929-cc86cda73774f810bfbd41e74aa0cb48061bea3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1500/HighFidelity-Beta-PR10929-cc86cda73774f810bfbd41e74aa0cb48061bea3d.exe

**Comment by YuppyPlays** [comment]
@anshuman64 No problem at all! will perform clean install before I install and run :)

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

[After a clean install]
**Pass** Restarted a total of 5 times, game loaded in each time without any crashes, between launches I removed data from appdata/local/ regarding the PR version.

**Pull request merged**
