### PR TITLE
Fix segfault with gxx

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes a segfault occurring when compiling with gcc in release mode.

### CODE REVIEW

**Comment by Atlante45** [comment]
Testing that one is gonna be really complicated.
A smoke test for ATP downloads/uploads would be a good start.
The only person that could test the actual fix, would be Kevin since he's the only one we know of it happens too at the moment.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ecdad191bcd44cae85c3b9df0e387886875bba3 available at: https://gist.github.com/4d763a8dbcfc1c93d7c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.dmg

**Comment by birarda** [comment]
I'll test this with @Atlante45 by dropping initial packets and confirming the processing of XORed packets succeeds.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 103c6d89f2fe1f1da0b73fcc342dcd72ed63dafb available at: https://gist.github.com/4d763a8dbcfc1c93d7c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 659d7e7335f1d10bd9377ac5a3264d2599c46fa9 available at: https://gist.github.com/4d763a8dbcfc1c93d7c7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7484.dmg

**Pull request merged**
