### PR TITLE
MS14743 again: More bandaids for preventing Snappy printouts from falling thru floor

### PR DESCRIPTION
**Pull request by zfox23**
Attempts again to fix [MS14743](https://highfidelity.manuscript.com/f/cases/edit/14743/Snappy-pics-fall-through-the-floor) by applying bandaids:

1. Removed linear and rotational velocity from printed snaps, but kept gravity. This means printed snappys will hang in the air until someone touches them.
2. Further decreased downward acceleration due to gravity on the snappy printouts.
3. Printed the Snappy a bit higher
4. Slightly increased linear damping

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Using the Snap App, print a polaroid. Ensure the polaroid entity doesn't fall through the floor, even after handling the Snappy. Try this in many domains on many floors.

I still haven't seen repro steps for getting them to fall through the floor consistently, nor have I seen a video of this happening. Please try extra hard to get this to happen.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11248/HighFidelity-Beta-PR13584-6218f80.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11248/HighFidelity-Beta-PR13584-6218f80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11248/HighFidelity-Beta-Interface-PR13584-6218f80.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11252/HighFidelity-Beta-PR13584-ee08ef9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11248/HighFidelity-Beta-PR13584-6218f80.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11248/HighFidelity-Beta-Interface-PR13584-6218f80.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11252/HighFidelity-Beta-PR13584-ee08ef9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11252/HighFidelity-Beta-Interface-PR13584-ee08ef9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11252/HighFidelity-Beta-PR13584-ee08ef9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11252/HighFidelity-Beta-Interface-PR13584-ee08ef9.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Snaps no longer fall through floor.

**Pull request merged**
