### PR TITLE
fix for mac min openGL version

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5dd33c8dce2a7368f02e56611aeb3cad2ecef57a available at: https://gist.github.com/06074977e5de13a8f862c3722a010f6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9075-5dd33c8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9075-5dd33c8.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by ZappoMan** [comment]
Test plan:
- smoke test on windows, make sure nothing breaks
- run on mac - you shouldn't see a popup about minimum OpenGL version

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5dd33c8dce2a7368f02e56611aeb3cad2ecef57a available at: https://gist.github.com/06074977e5de13a8f862c3722a010f6b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9075-5dd33c8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9075-5dd33c8.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU

General smoke test pass - works same as current master, confirmed it's selecting GL4.5 for my setup.  Tested with desktop and DK2 modes.

**Pull request merged**
