### PR TITLE
Add support for disabling incremental texture transfers

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Use the env variable `HIFI_DISABLE_INCREMENTAL_TEXTURES` to disable both sparse textures and incremental texture transfers.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9434121c0e73612ff464dd26671cd295f9c394d2 available at: https://gist.github.com/01782f4da3b8bb601ad22a2b455c6a65<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-9434121.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-9434121.dmg

**Comment by OmegaHeron** [comment]
No env vars set = very bad (as expected).
Disable Sparse = Tiny improvement but not acceptable.
Disable Incremental = Huge improvement with acceptable performance.
Disable Sparse and Incremental = Additional improvement in scene load time over disable incremental only.

Mountain of data graphs to follow shortly.

**Comment by OmegaHeron** [comment]
And here's graphic - all 5 runs each of 8673
Red = Sparse and Incremental on (no env set)
Green = Sparse Off Incremental on
Blue = Sparse On Incremental off
Yellow = Sparse Off Incremental off

8673-comps-overlayed

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7361b9a1660f676b5f9084ed29f02ff373a38555 available at: https://gist.github.com/01782f4da3b8bb601ad22a2b455c6a65<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-7361b9a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-7361b9a.dmg

**Comment by jherico** [comment]
@OmegaHeron can you test the new build?  On an i5 machine with 4 cores it should automatically behave as if it had the env variables set.  

Also bear in mind your 'blue' and 'yellow' lines should be showing the same data... disabling incremental automatically disables sparse as well (you can't do non-incremental transfers without allocating the whole texture beforehand)

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6f3011754b34927e4eb6642a0279ac3c4c51839 available at: https://gist.github.com/01782f4da3b8bb601ad22a2b455c6a65<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-b6f3011.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8673-b6f3011.dmg

**Comment by OmegaHeron** [comment]
Ok - gods of random on diff between blue/yellow ;)  Testing now for latest build.

**Comment by OmegaHeron** [comment]
Tested - insured I had no dangling env vars set.  Works as expected.  QA Pass i5.

**Pull request merged**
