### PR TITLE
Photobooth MVP - Dev tool for taking standardized product pictures

### PR DESCRIPTION
**Pull request by fayeli**
This PR contains all my work so far on the Photobooth project. It is currently at a mvp state, with basic functionalities allowing you to switch out models and take standardised pictures of the models from different camera angles.

To Test:
1) In Interface, open running script > developer > utilities > render > photobooth. Select photobooth.js and run it.
2) You should see two things: the photobooth stage appearing in front of you, and a dialog menu titled "Photobooth" popping up.
3) Test switching model: 
           - input a valid link to a FBX file of a model, then click reload button.
           - you should see the model created in centre of stage, replacing default model
           - the model might be momentarily larger than it should be, but it should automatically scale to fit
4) Test selecting camera:
          - using the drop down, select different cameras(main/left/right camera)
          - you should see your full interface view switch to the selected camera's view
          - selecting fps camera will put you back to normal view
5) Test take picture button: 
          - click the "take picture" button
          - confirm that the HUD, cursor and ui overlay disappears momentarily,  and that a new picture is saved in your screen shot folder 

Future work:
- Work with Alan to stage camera angles and backdrop
- Enable lighting presets selection (zone + light entities)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 33142d6a7f89c8daa12a5f2003d43b3f64064160 available at: https://gist.github.com/01ff93a9cdb596e0ecb7adaadc81d8b6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9174-33142d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9174-33142d6.dmg

**Comment by Nex-Pro** [comment]
In Interface, open running script > developer > utilities > render > photobooth. Select photobooth.js and run it. **CHECK**

You should see two things: the photobooth stage appearing in front of you, and a dialog menu titled "Photobooth" popping up. **SUCCESS**
Test switching model:
- input a valid link to a FBX file of a model, then click reload button. **CHECK**
- you should see the model created in centre of stage, replacing default model **SUCCESS**
- the model might be momentarily larger than it should be, but it should automatically scale to fit  **SUCCESS**
Test selecting camera:
- using the drop down, select different cameras(main/left/right camera) **SUCCESS**
- you should see your full interface view switch to the selected camera's view **SUCCESS**
- selecting fps camera will put you back to normal view **SUCCESS**
Test take picture button: **CHECK**
- click the "take picture" button **SUCCESS**
- confirm that the HUD, cursor and ui overlay disappears momentarily, and that a new picture is saved in your screen shot folder **SUCCESS**

Observations: Resize of new object did not occur on first attempt. Was fine after re-running script.

Cameras do not frame models well. I swapped to a hotdog model that is predominantly horizontal and therefore only occupied part of the view at the bottom.

hifi-snap-by-nex-on-2016-12-09_03-57-23

hifi-snap-by-nex-on-2016-12-09_03-57-33


hifi-snap-by-nex-on-2016-12-09_03-57-38

This item was in edit mode as you can see,

hifi-snap-by-nex-on-2016-12-09_04-00-11


Edit off:

hifi-snap-by-nex-on-2016-12-09_04-08-49
hifi-snap-by-nex-on-2016-12-09_04-08-30
hifi-snap-by-nex-on-2016-12-09_04-08-36
hifi-snap-by-nex-on-2016-12-09_04-08-43


I can't pass/fail as I don't know if framing should be better.

**Comment by Nex-Pro** [comment]
Perhaps calculate center of bounding box to position subject vertically. Frame to include bounding box.

**Comment by fayeli** [comment]
Thanks for testing thoroughly @Nex-Pro . The framing is a known issue and we plan on restaging the camera and models in the next sprint. As for cleaning up entities, I believe that if you stop photobooth.js in running script, all the entities should be removed from scene.

**Pull request merged**
