### PR TITLE
fix action (grab) deadlock

### PR DESCRIPTION
**Pull request by sethalves**
- fix action (grab) deadlock

### CODE REVIEW

**Comment by sethalves** [comment]
https://app.bugsplat.com/individualCrash/?debugger=1&id=15176&database=interface_alpha

**Comment by sethalves** [comment]
## Test Plan
* use wearables
* don't deadlock

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4327/HighFidelity-Beta-PR11642-2b0285adc2fdf50fa9e70827e61bc7dead647958.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4327/HighFidelity-Beta-PR11642-2b0285adc2fdf50fa9e70827e61bc7dead647958.exe

**Comment by Nex-Pro** [comment]
Testing this Win10

**Comment by Nex-Pro** [comment]
### PASS

All good. Tested with the wearables at Empty. No crashes. Interface exited cleanly.

**Pull request merged**
