### PR TITLE
DEV-625: Free Look Camera in first person mode

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-625

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21594/HighFidelity-Beta-PR16267-0fac1e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21594/HighFidelity-Beta-Interface-PR16267-0fac1e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21594/HighFidelity-Beta-PR16267-0fac1e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21594/HighFidelity-Beta-Interface-PR16267-0fac1e1.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21594/HighFidelity-Beta-PR16267-0fac1e1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21594/HighFidelity-Quest-Beta-PR16267-0fac1e1.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21603/HighFidelity-Beta-PR16267-18af7c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21603/HighFidelity-Beta-Interface-PR16267-18af7c5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21603/HighFidelity-Beta-PR16267-18af7c5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21603/HighFidelity-Quest-Beta-PR16267-18af7c5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21603/HighFidelity-Beta-PR16267-18af7c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21603/HighFidelity-Beta-Interface-PR16267-18af7c5.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21629/HighFidelity-Beta-PR16267-059bcc1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21629/HighFidelity-Beta-Interface-PR16267-059bcc1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21629/HighFidelity-Beta-PR16267-059bcc1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21629/HighFidelity-Quest-Beta-PR16267-059bcc1.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21631/HighFidelity-Beta-PR16267-75f0b4e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21631/HighFidelity-Quest-Beta-PR16267-75f0b4e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21631/HighFidelity-Beta-PR16267-75f0b4e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21631/HighFidelity-Beta-Interface-PR16267-75f0b4e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21631/HighFidelity-Beta-PR16267-75f0b4e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21631/HighFidelity-Beta-Interface-PR16267-75f0b4e.exe

**Comment by Darlingnotin** [comment]
I'm pretty sure this is the pr that caused a horrible bug. The camera in desktop no longer turns the avatar but its head. Movement with the mouse is completely destroyed. This person's code should removed from the code base immediately so it cannot cause a deep and long-lasting embarrassment for high fidelity.

**Pull request merged**
