### PR TITLE
FB18302 Remove deprecated Package Model functionality

### PR DESCRIPTION
**Pull request by humbletim**
This PR updates Interface's `Package Model as .fst...` to eliminate deprecated functionality.

Packaging models now works as-if the "Avatar Body and Head" type were always selected (beyond UI changes there should be no impact on overall application behavior or avatar use).

The main user-facing change is that Package Model => `Model Type:` dropdown and its secondary options are no more:
* _Avatar Body and Head_ (now the internal default)
* _Avatar Attachment_ (removed)
* _Entity Model_ (removed)

Change summary:
* Remove `Model Type: ` dropdown.
* Rename `Package Model as .fst...` to `Package Avatar as .fst...`
* Remove non-functional Qt "whatsthis" dialog icon.
* Eliminate unneeded code paths per above.

##### "A" testing:
1) Run current production Beta Release.
2) Selected "Edit -> Package Model as .fst" 
3) Choose an .fbx file (leaving the Model Type dropdown set to "Avatar Body with Head").
4) Pick reasonable joint options / hit OK to package the model.
5) ... take note of the generated FST and asset folders.

##### "B" testing:
1) Run this PR build.
2) Selected "Edit -> Package Avatar as .fst" 
3) Choose an .fbx file.
4) Pick reasonable joint options / hit OK to package the model.
5) ... take note of the generated FST and asset folders.

Compare A and B packaged output -- assuming identical FBX and joint options were selected then the generated FST files and folder contents should be identical too.

https://highfidelity.fogbugz.com/f/cases/18302

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14250/HighFidelity-Beta-PR14251-2cf633c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14250/HighFidelity-Beta-PR14251-2cf633c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14250/HighFidelity-Beta-Interface-PR14251-2cf633c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14250/HighFidelity-Beta-PR14251-2cf633c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14250/HighFidelity-Beta-Interface-PR14251-2cf633c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15186/HighFidelity-Beta-PR14251-d0e4c62.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15186/HighFidelity-Beta-PR14251-d0e4c62.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15186/HighFidelity-Beta-Interface-PR14251-d0e4c62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15186/HighFidelity-Beta-PR14251-d0e4c62.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15186/HighFidelity-Beta-Interface-PR14251-d0e4c62.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

The same items appear in both methods with the same joint ID's attached to them.
The items are in different listing order between the different export methods.

**Pull request merged**
