### PR TITLE
New icons for interface and server-console

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Ticket: https://highfidelity.manuscript.com/f/cases/20467/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16403/HighFidelity-Beta-PR14700-d271bcd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16403/HighFidelity-Beta-PR14700-d271bcd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16403/HighFidelity-Beta-Interface-PR14700-d271bcd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16403/HighFidelity-Beta-PR14700-d271bcd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16403/HighFidelity-Beta-Interface-PR14700-d271bcd.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
pass

**Pull request merged**
