### PR TITLE
[DO NOT MERGE] - DevOps test

### PR DESCRIPTION
**Pull request by marko8904**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6889/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6889/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6889/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6892/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6892/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6892/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6904/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6904/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6904/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6908/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6908/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6908/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6920/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6920/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6920/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6924/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6924/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6930/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6930/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6930/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6932/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6932/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6945/app_12327_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6947/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6947/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6947/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6953/app_12327_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6955/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6955/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6955/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6958/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6958/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6960/app_12327_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6960/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6960/HighFidelity-Beta-PR12327-2f17ba4a95ca42cadb5d4f73aeebdd3e0a5f3fe9.exe

**Pull request closed without merging**
