### PR TITLE
Destroy script thread on finish instead of on ScriptEngine destroyed

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.manuscript.com/f/cases/18044

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12805/HighFidelity-Beta-PR13964-3601ade.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12805/HighFidelity-Beta-PR13964-3601ade.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12805/HighFidelity-Beta-Interface-PR13964-3601ade.dmg

**Comment by huffman** [comment]
# Test Plan

This particular crash is a race condition, but it will pretty reliably occur after restarting all scripts 50-100 times. Please test this first on current stable to see it crash.

 1. Open interface
 1. With the default set of scripts running, either press ctrl-r or click "Reload All" in the Running Scripts window.
 1. Reload all of the scripts 100+ times. 
 1. Interface should not crash.

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Reloaded scripts 100+ times without crashing in localhost, Hifi Hosted Domains or Serverless

**Pull request merged**
