### PR TITLE
FogBugz 7425 - Billboard orientation and grabber move up tool are now dependent on the Avatar referential.

### PR DESCRIPTION
**Pull request by Delanir**
FogBugz
7425 IPD Secondary Task List: edit.js arrow orientation: 
    - Grabber Move Up Tool and gizmo arrow now work as expected, taking into account the orientation of the Avatar.
Update CREATE affordances to be correctly oriented on wiki-planet
    - Billboards now take into account the orientation of the Avatar.

---------------------------------------------------------------------------

Test plan:
In HMD mode:
1. Go to a domain where you have edit power.
2. Open the "Create" mode and spawn a cube.
3. Notice the presence of the "grabber move up" gizmo.
grabbermoveup

Try to look at it from different angles. 

Expected result: The gizmo should always be oriented towards you.

4. Try to use the tool to move the cube up and down.

Expected result: You are able to move the cube up and down.

-----------------------------------------------------------------------
5. Go to wikiplanet/newyork (you might need edit permission)
6. Open the "Create" mode and spawn a cube.
7. Notice the presence of the "grabber move up" gizmo. Try to look at it from different angles. 
Expected result: The gizmo should always be oriented towards you.
8. Try to use the tool to move the cube up and down.
Expected result: You are able to move the cube up and down.
-----------------------------------------------------------------------
In Desktop mode, repeat the steps for the HMD test.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4375/HighFidelity-Beta-PR11661-059c5c1806d287e3072b6f0a9b56d86fb0325a79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4375/HighFidelity-Beta-PR11661-059c5c1806d287e3072b6f0a9b56d86fb0325a79.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

[Tested all steps in HMD & Desktop]

Go to a domain where you have edit power. **Check**
Open the "Create" mode and spawn a cube. **Check**
Notice the presence of the "grabber move up" gizmo. **Check**
Try to look at it from different angles. **Check**
Expected result: The gizmo should always be oriented towards you. **Check**
Try to use the tool to move the cube up and down. **Check**
Expected result: You are able to move the cube up and down. **Check**
Go to wikiplanet/newyork (you might need edit permission) **Check**
Open the "Create" mode and spawn a cube. **Check**
Notice the presence of the "grabber move up" gizmo. Try to look at it from different angles. **Check**
Expected result: The gizmo should always be oriented towards you. **Check**
Try to use the tool to move the cube up and down. **Check**
Expected result: You are able to move the cube up and down. **Check**

Looks like a solid **Pass** to me :)

**Pull request merged**
