### PR TITLE
make avatar kill packets from mixer reliable

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12038/HighFidelity-Beta-PR13809-91365ae.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12038/HighFidelity-Beta-PR13809-91365ae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12038/HighFidelity-Beta-Interface-PR13809-91365ae.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12038/HighFidelity-Beta-PR13809-91365ae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12038/HighFidelity-Beta-Interface-PR13809-91365ae.dmg

**Comment by birarda** [comment]
#### Test Plan

For this test you will need [clumsy](https://jagt.github.io/clumsy/) as well as two interface clients.

1. Setup clumsy to drop 50% of incoming udp packets on one of the machines running interface.
2. On a master domain, connect two interface clients. Quit the interface client on the machine not running clumsy, dropping it from the domain. Repeat this step until the disconnected avatar does not disappear in the still running interface client (on the machine running clumsy).
3. Repeat step 2 with the sandbox from this PR. Confirm that you cannot get the disconnected avatar to stay stuck in the domain.

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12097/HighFidelity-Beta-PR13809-91365ae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12097/HighFidelity-Beta-PR13809-91365ae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12097/HighFidelity-Beta-Interface-PR13809-91365ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12097/HighFidelity-Beta-PR13809-91365ae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12097/HighFidelity-Beta-Interface-PR13809-91365ae.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar does disconnect, and does not stay there.

**Pull request merged**
