### PR TITLE
NOT MERGEABLE - repairs to AC/ThreadedAssignment cleanup

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d75d204ff6ef190411410bf4b2a3915485e4e393 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c8c24eb00d62f9d4e18841b9ad71a6b288c9bb5 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3ce02181e0835f160b73d7af86d69ef14aba0dd available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e0029e6e6225abb2c1e0c3c445ad66b246c0872 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by ZappoMan** [comment]
what unit tests have your run on this new model? Have we verified for example that lots of clients connecting/disconnecting from an entity server don't crash when the following different shutdown cases occur: 1) domain server restart, 2) assignment client sigterm, 3) domain server stop [and not restart] 

Each of these restart/stop cases have slightly different timing characteristics, and there may be clients at various states of "connecting" to the entity server during the shutdown process... have you tested that the new model (in particular getting rid of the shared pointer to the server) handles all these cases?

**Comment by birarda** [comment]
In all three of those cases @ZappoMan I have verified that the cleanup happens as expected.

**Comment by ZappoMan** [comment]
@birarda - just to be clear... those three cases WHILE clients are connecting/disconnecting from the server... that's where old race conditions existed which were handled by the existing code.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bab96a77117bc206657179fdd7546125d8fe34c0 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by birarda** [comment]
Going to add something to make sure that no OctreeSendThreads are created while the OctreeServer knows it should be shutting down - will test that will the rapid connect/disconnect script to make sure I get what I expect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f71e93c7f95197362ea736d9c22af45349e810d available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b080dfc1cf948738e72a2cf143c63df5e1ff7dc7 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: be58347aecdd902c05327f652432c5b88ab3e2a3 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fe1b8cc52b0e4335528973cb1365d9831bc4990f available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69143d8677a814297a8eaae25b667d73bdf059c4 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: df6ee4c7a537b4c74df55187f14b6087cf0b0486 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99a9f2df90d1d08d11c7ff18cef61df94fad18e8 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a295bada135834c321711414859f6426194dade available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88c58ea9df4ad89f8a8fffdd9f8d2d9365879660 available at: https://gist.github.com/299942efa4e2f24b189e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4797.dmg

**Pull request closed without merging**
