### PR TITLE
add suppression for ring buffer and sequence number messages

### PR DESCRIPTION
**Pull request by birarda**
- add suppression for ring buffer and sequence number messages

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc8707dc05442ef2a47848c77c16700bd0693042 available at: https://gist.github.com/d25e0232c0c7437ba64ded2d7883d838<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7535.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7535.dmg

**Comment by kevinmthomas-carpool** [comment]
Are you looking for a basic smoke test or is there a test plan?

**Comment by OmegaHeron** [comment]
Basic smoke tested Windows 7 - no issues seen nor did I record any of the messages this suppresses in log.  That said I don't often see either in production build.

**Comment by birarda** [comment]
Yeah, sorry for the absence of test notes on this. These messages don't show up often, but when they do, they bomb your log. I ended up re-compiling locally to force the conditions that cause these messages to appear. I think a smoke test is great here.

**Comment by kevinmthomas-carpool** [comment]
Smoke test complete on Windows 10. No issues as everything functions normally.  I did notice something however I am not sure if it is unique to my setup - in this PR I logged in to the Music domain.  When I did I notices for the first 8-10 seconds my render rate to go 67 when consistently it has normally stayed at 60 on every other build.  There is no error of any kind this is just new behavior that I noticed that I did not previously expect.  It did not stay consistent only for the first 8-10 seconds.  The same behavior occurred when I visited the HQ and Sandbox domains.

**Pull request merged**
