### PR TITLE
fix avatarActionHold

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1b10e79dfee32fc4c46ec4708b93b58b6dce87a available at: https://gist.github.com/b4b11d7c2dc4dbfd3dac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7181.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7181.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62ed5333e05bb023dcf59b76059c78ee1c9b0144 available at: https://gist.github.com/b4b11d7c2dc4dbfd3dac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7181.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7181.dmg

**Comment by hyperlogic** [comment]
https://app.asana.com/0/26225263936266/94046267449312

**Comment by sethalves** [comment]
to test:
get two avatars in the same place.  Have one of them use handControllerGrab.js to near-grab something while the other one is watching.  Note that the watcher doesn't crash and does see the thing moving around with the grabber's hand.

**Pull request merged**
