### PR TITLE
Toggle going to 404 redirect domain (RC73)

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for MS#[18555](https://highfidelity.manuscript.com/f/cases/18555)

This PR defaults the behavior of getting redirected to the 404 domain to be disabled.  Enabling it would be by opening the `Developer > Console` after enabling the developer menu via `Settings > Developer Menu`, and setting the mode through `Settings.setValue("enableInterstitialMode", true);`

## TEST PLAN
- Launch Interface
- Interstitial mode should be disabled by default
- Try navigating to a domain that would warrant an error (i.e. via a timeout, with an unauthorized account, or protocol mismatch)
- Dialog should display with some text related to the error
- Enable `Settings > Developer Menu`
- Open `Developer > Console`
- Enter in `Settings.setValue("enableInterstitialMode", true);`
- Try navigating to a domain that would warrant an error (i.e. via a timeout, with an unauthorized account, or protocol mismatch)
- Arrive in the redirected serverless domain

Test case:
https://highfidelity.testrail.net/index.php?/cases/view/27807

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13126/HighFidelity-Beta-PR14030-8789ba3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13126/HighFidelity-Beta-PR14030-8789ba3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13126/HighFidelity-Beta-Interface-PR14030-8789ba3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13126/HighFidelity-Beta-PR14030-8789ba3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13126/HighFidelity-Beta-Interface-PR14030-8789ba3.exe

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Connected to domain not currently active (Welcome) and received error message and did not land in serverless area. Used console command as shown, restarted interface, and attempted Welcome again and I landed in the 404 area. PR Passes.

https://highfidelity.testrail.com/index.php?/runs/view/6553&group_by=cases:section_id&group_id=5165&group_order=asc
Ran Android Smoke Test and passed.

**Pull request merged**
