### PR TITLE
7452 regression: flickering keyboard

### PR DESCRIPTION
**Pull request by ElderOrb**
note: regression was happening because of url reloading on geometry change which resulted in showing keyboard which resulted in geometry change which resulted .... 

the logic has been updated to avoid reloading. unfortunately due to Qt bug in WebEngine fix looks like this

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3126/HighFidelity-Beta-PR11321-74c7d4a4afd76c83774a579f0f8f1c04ff29abd8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3126/HighFidelity-Beta-PR11321-74c7d4a4afd76c83774a579f0f8f1c04ff29abd8.exe

**Comment by ElderOrb** [comment]
**Test plan**

before fix:

In VR:

click in the PAL -> (display name in upper left),
or click in PAL -> CONNECTIONS -> (any connection) -> "i" (info) -> (any social media button),
or click in GOTO -> "i" (info) -> (an social media button).
The virtual keyboard appears for a moment and then either goes away or flickers on and off.

after fix: 

In VR:

click in the PAL -> (display name in upper left),
or click in PAL -> CONNECTIONS -> (any connection) -> "i" (info) -> (any social media button),
or click in GOTO -> "i" (info) -> (an social media button).
The virtual keyboard should appears

note: 

Fix changes logic of FlickableViewWebCore component which is used in a lot of places. Please check for regressions at least the following areas (in VR): 

- tabs in Edit menu: "List" and "Grid" tabs should have no scrollbars, its content should fit to screen
- help button - help should fit to screen without any scrollbars

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3136/HighFidelity-Beta-PR11321-b5f4a154376f3acb70a846b3d2b4455b706f7540.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3136/HighFidelity-Beta-PR11321-b5f4a154376f3acb70a846b3d2b4455b706f7540.dmg

**Comment by skytoad** [comment]
Pass. Tested each social media function in each location mentioned in test plan.

**Comment by tapalisa** [comment]
1 user of this PR does not have their tester flag set. Please check your environment variable.

**Comment by ZappoMan** [comment]
@ElderOrb this PR needs to be rebased with master. there's a conflict.

**Comment by anshuman64** [comment]
@ElderOrb I think this issue was fixed by this PR: https://github.com/highfidelity/hifi/pull/11341

We just rolled back flickable webviews altogether. Please confirm, and then we should close this PR.

**Comment by ElderOrb** [comment]
Yes, right. My changes are not actual anymore and can be dropped.

**Comment by anshuman64** [comment]
@ElderOrb okay, closing this PR then. Thanks for looking into the issue, though!

**Pull request closed without merging**
