### PR TITLE
Case 819 - Add min-listen-port command line parameter to assignment monitor

### PR DESCRIPTION
**Pull request by roxanneskelly**
This will allow users to specify a port range for assignment client UDP ports,
allowing easier port forwarding, etc.

https://highfidelity.fogbugz.com/f/cases/819

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18648/HighFidelity-Beta-PR15353-cb6f7a4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18648/HighFidelity-Beta-Interface-PR15353-cb6f7a4.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18648/HighFidelity-Beta-PR15353-cb6f7a4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18648/HighFidelity-Quest-Beta-PR15353-cb6f7a4.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18651/HighFidelity-Beta-PR15353-68cf18e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18651/HighFidelity-Quest-Beta-PR15353-68cf18e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18651/HighFidelity-Beta-PR15353-68cf18e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18651/HighFidelity-Beta-Interface-PR15353-68cf18e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18651/HighFidelity-Beta-PR15353-68cf18e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18651/HighFidelity-Beta-Interface-PR15353-68cf18e.exe

**Comment by howard-stearns** [comment]
[sandbox option to specify ac ports](https://trello.com/c/yb6guqKB/14-sandbox-option-to-specify-ac-ports)

**Pull request merged**
