### PR TITLE
fix MyAvatar collision bug at transitions between meshes

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR to fix a collision bug where MyAvatar would sometimes pick up a very high velocity when crossing seams between two meshes.   The internal manuscript case is 17651:
https://highfidelity.manuscript.com/f/cases/17651/Physics-of-floor-transitions-can-knock-MyAvatar-airborne

The problem was introduced by the "don't collide MyAvatar against backfacing triangles" stuff in PR-13711.

**Test Plan:**

**(1)** Todo: write this testplan after lunch.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12199/HighFidelity-Beta-PR13840-3068865.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12199/HighFidelity-Beta-PR13840-3068865.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12199/HighFidelity-Beta-Interface-PR13840-3068865.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 verified that the avatar is able to pass the mesh seem without glitching diagonally.

**Pull request merged**
