### PR TITLE
Stopwatch updates

### PR DESCRIPTION
**Pull request by huffman**
Update the stopwatch spawn script so that it shows up further in front of your avatar and faces you. The spawn script will also exit when it is done now.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40bd7d9475ab0b74fb14e73dcc63fb9f973ae331 available at: https://gist.github.com/3fdac038fc69f53f496538f54f10f7c8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9636-40bd7d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9636-40bd7d9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58e3351b25dc646750fe5807eac4aded9a3df08d available at: https://gist.github.com/3fdac038fc69f53f496538f54f10f7c8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9636-58e3351.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9636-58e3351.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
Saw the watch, it responds to clicking.
I hear the ticking.
There are **no hands** on the watch.
After running the script again
I quickly grabbed the UUID of the second hand from user data and JSON.stringified from console  got an empty object back.

**Comment by Nex-Pro** [comment]
Does this need to be tested with the sandbox from this PR ?

**Comment by huffman** [comment]
@Nex-Pro Hmm, shouldn't. I'm on 6020 and it works for me. What version are you on?

**Comment by Nex-Pro** [comment]
I tried it at welcome

**Comment by Nex-Pro** [comment]
@huffman ^

**Comment by huffman** [comment]
@Nex-Pro Hmm, it is working for me. I put a stopwatch in dev-welcome to the left of the "your tablet" sign. Can you check to see if you can see the hands there? http://prntscr.com/e6bvsk

**Comment by Nex-Pro** [comment]
@huffman   This time I see the hands fine @dev-welcome and they are rotating. So works fine on the one you rezzed at dev-welcome

When I run the script in #6008 at welcome I now see hands ( cached I guess ) but they don't rotate. ( confirmed by second observer )

Got full object  back from console.

{  
   "id":"{b941c45a-23a4-43be-951d-bf32a1196b94}",
   "type":"Model",
   "created":"2017-02-09T00:48:42Z",
   "age":2337.097412109375,
   "ageAsText":"0 hours 38 minutes 57 seconds",
   "lastEdited":1486603534071815,
   "lastEditedBy":"{e99461ad-e36f-4a12-8fb8-46197e7a1c36}",
   "position":{  
      "x":11.08761215209961,
      "y":1.0561387538909912,
      "z":-10.969454765319824
   },
   "dimensions":{  
      "x":0.07047881186008453,
      "y":0.012730538845062256,
      "z":0.8038504123687744
   },
   "naturalDimensions":{  
      "x":0.008809851482510567,
      "y":0.001591317355632782,
      "z":0.1004813015460968
   },
   "naturalPosition":{  
      "x":-0.0004459992051124573,
      "y":0.10248266160488129,
      "z":-0.039095308631658554
   },
   "rotation":{  
      "x":0.6927686333656311,
      "y":-0.14168216288089752,
      "z":0.14153464138507843,
      "w":0.6927854418754578
   },
   "velocity":{  
      "x":0,
      "y":0,
      "z":0
   },
   "gravity":{  
      "x":0,
      "y":0,
      "z":0
   },
   "acceleration":{  
      "x":0,
      "y":0,
      "z":0
   },
   "damping":0.39346998929977417,
   "restitution":0.5,
   "friction":0.5,
   "density":1000,
   "lifetime":-1,
   "script":"",
   "scriptTimestamp":0,
   "serverScripts":"",
   "registrationPoint":{  
      "x":0.5,
      "y":0.5,
      "z":1
   },
   "angularVelocity":{  
      "x":0,
      "y":0,
      "z":0
   },
   "angularDamping":0.39346998929977417,
   "visible":1,
   "collisionless":0,
   "ignoreForCollisions":0,
   "collisionMask":31,
   "collidesWith":"static,dynamic,kinematic,myAvatar,otherAvatar,",
   "dynamic":0,
   "collisionsWillMove":0,
   "href":"",
   "description":"",
   "actionData":"",
   "locked":0,
   "userData":"",
   "marketplaceID":"",
   "name":"stopwatch/seconds",
   "collisionSoundURL":"",
   "modelURL":"https://raw.githubusercontent.com/huffman/hifi/58e3351b25dc646750fe5807eac4aded9a3df08d/unpublishedScripts/marketplace/stopwatch/models/Stopwatch-sec-hand.fbx",
   "animation":{  
      "url":"",
      "fps":30,
      "currentFrame":0,
      "running":0,
      "loop":1,
      "firstFrame":0,
      "lastFrame":100000,
      "hold":0
   },
   "jointRotationsSet":[  

   ],
   "jointRotations":[  

   ],
   "jointTranslationsSet":[  

   ],
   "jointTranslations":[  

   ],
   "shapeType":"none",
   "compoundShapeURL":"",
   "textures":"",
   "sittingPoints":{  
      "length":0
   },
   "boundingBox":{  
      "brn":{  
         "x":11.052701950073242,
         "y":1.0561312437057495,
         "z":-10.989137649536133
      },
      "tfl":{  
         "x":11.12269115447998,
         "y":1.8599853515625,
         "z":-10.94976806640625
      },
      "center":{  
         "x":11.087696075439453,
         "y":1.4580583572387695,
         "z":-10.969452857971191
      },
      "dimensions":{  
         "x":0.06998920440673828,
         "y":0.8038541078567505,
         "z":0.03936958312988281
      }
   },
   "originalTextures":"{\n \"Texture\": \"https://raw.githubusercontent.com/huffman/hifi/58e3351b25dc646750fe5807eac4aded9a3df08d/unpublishedScripts/marketplace/stopwatch/models/Stopwatch-sec-hand.fbx/Stopwatch-sec-hand.fbm/stopwatch-face.jpg\"\n}\n",
   "parentID":"{5ffbe6df-e8d4-44d7-b355-c20306090fcc}",
   "parentJointIndex":65535,
   "queryAACube":{  
      "x":8.803970336914062,
      "y":-0.26446330547332764,
      "z":-11.995964050292969,
      "scale":4.827885627746582
   },
   "localPosition":{  
      "x":-0.002492906991392374,
      "y":0.19695532321929932,
      "z":0.4156402349472046
   },
   "localRotation":{  
      "x":-0.0000152587890625,
      "y":-0.0000152587890625,
      "z":-0.0000152587890625,
      "w":1
   },
   "clientOnly":0,
   "owningAvatarID":"{00000000-0000-0000-0000-000000000000}",
   "renderInfo":{  
      "verticesCount":8,
      "texturesSize":0,
      "hasTransparent":true,
      "drawCalls":1,
      "texturesCount":0
   }
}

**Comment by huffman** [comment]
@Nex-Pro Are you able to rez it at dev-welcome? I confirmed that there is a bug in the beta build (fixed in latest dev release) that keeps the stopwatch from updating until the creator leaves.

**Comment by Nex-Pro** [comment]
@huffman You want me to test the script in the latest dev build at dev-welcome ?

**Comment by huffman** [comment]
@Nex-Pro Yes please, the latest dev build should have a fix for the issue you were seeing on 6008 in welcome.

**Comment by Nex-Pro** [comment]
@huffman I just ran the script in #6025 several times at dev-welcome. I get the stopwatch with no hands.
It starts and stops ticking on click. Tried a couple of times and cleared cache. Still no hands.

**Comment by Nex-Pro** [comment]
@huffman I just saw the hands ok in the current( 6008) build. There's a stopwatch aleady at welcome. Works fine.
BUT when I run the script at welcome I get a new stopwatch with hands that do not turn when the ticking starts.  ???

**Comment by huffman** [comment]
@Nex-Pro If you leave the domain and come back you should see it working. There was a bug where the user who spawned the stopwatch would become the simulation owner of the hands, so the server script would be unable to update the hands.

**Comment by huffman** [comment]
I'm a bit baffled why it isn't working on dev-welcome, though. It had worked for me.

**Comment by Nex-Pro** [comment]
@huffman another user just confirmed what I saw. And as you say when I left and returned the stopwatch functioned ok and the other user can see it.

**Comment by huffman** [comment]
@Nex-Pro Ok, the dev-welcome issue looks like a permissions issue. If I log out I can create the stopwatch but the hands don't show up. I'm going to look into it a little more to find out why.

**Comment by huffman** [comment]
@Nex-Pro I finally discovered that this was an issue with the entity filter script on dev-welcome. There is a bug with parented entities that was causing the hands to be deleted. I filed a bug report.

**Comment by huffman** [comment]
Marking this as QA Approved, I think we've identified all of the issues as unrelated bugs.

**Comment by oshaikh13** [comment]
Hi @huffman 

I've attempted to add your stopwatch. The minute and second hand appears to be rotating in an odd fashion. I'm running build 6095.

weirdclock

**Pull request merged**
