### PR TITLE
Fix ACs startup crash

### PR DESCRIPTION
**Pull request by Atlante45**
This fixes some ACs (Agent, ESS, Audio Mixer) crashing on startup.

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Launch your Sandbox
- Go to the "Nodes" page (http://localhost:40100)
- Make sure you can see the following nodes running:
    - Audio Mixer
    - Agent
    - Entity Script Server

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11028/HighFidelity-Beta-PR13510-1ab1a91.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11028/HighFidelity-Beta-PR13510-1ab1a91.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11028/HighFidelity-Beta-Interface-PR13510-1ab1a91.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Launched Sandbox and nodes are running (agent, ESS, audio). They have kept running for 10+ minutes

Connected to hifiqa-pr-metaverse-staging DS and moved around and talked with other avatars for 10 minutes, experiencing no crashing of the nodes.

**Pull request merged**
