### PR TITLE
Don't move or rotate entities if Alt or Meta keys are pressed

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

In a domain where you have edit permissions:

Windows:
- In desktop mode.
- Create an entity.
- Click and hold the entity with a left mouse click, and move your mouse: it should mode in x-z plane.
- Press and hold the Shift key and click and hold the entity with a left mouse click, and move your mouse: it should move in the y direction.
- Press and hold the Control key and click and hold the entity with a left mouse click, and move your mouse: it should rotate.
- Press and hold the Alt key and click and hold the entity with a left mouse click, and move your mouse: the entity should NOT move or rotate.

OSX:
- As above but also test the Option (Meta) key.

**Comment by YuppyPlays** [comment]
Awaiting windows build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4717/HighFidelity-Beta-PR11761-60319e8d53a3605dc5cefc0f70e275357eacf364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4717/HighFidelity-Beta-PR11761-60319e8d53a3605dc5cefc0f70e275357eacf364.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In desktop mode.
Create an entity. **Check**
Click and hold the entity with a left mouse click, and move your mouse: it should mode in x-z plane.**Check**
Press and hold the Shift key and click and hold the entity with a left mouse click, and move your mouse: it should move in the y direction. **Unsure, It seems to move along the Y axis and left/right relative to the players view direction**
Press and hold the Control key and click and hold the entity with a left mouse click, and move your mouse: it should rotate.**Check**
Press and hold the Alt key and click and hold the entity with a left mouse click, and move your mouse: the entity should NOT move or rotate.**Check**

**I assume the test plan is on about controls NOT in Edit mode, but let me know if this was incorrect**

**Notes: Except for 3rd step everything seems good, but this could be just a mis-type in the test plan?**

**Fail**

**Comment by Nex-Pro** [comment]
### PASS

Note however we still have the issue of grabbable ents acting dynamic when grabbed.

**Pull request merged**
