### PR TITLE
Avatar loading orb now indicates loading status

### PR DESCRIPTION
**Pull request by hyperlogic**
white - no url has been received yet for this avatar
purple - a url has been received for this avatar but it's content is still downloading/loading
blue - (only visible breifly) content has succesfully loaded
red - (only visible briefly) content has failed to download.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/18324/Change-color-of-avatar-orb-based-on-loading-status

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12878/HighFidelity-Beta-PR13973-bc5d9a4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12878/HighFidelity-Beta-PR13973-bc5d9a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12878/HighFidelity-Beta-Interface-PR13973-bc5d9a4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12883/HighFidelity-Beta-PR13973-23ed314.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12883/HighFidelity-Beta-PR13973-23ed314.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12883/HighFidelity-Beta-Interface-PR13973-23ed314.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12883/HighFidelity-Beta-PR13973-23ed314.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12883/HighFidelity-Beta-Interface-PR13973-23ed314.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

The blue looks green to me, but the behavior appears correct.

**Pull request merged**
