### PR TITLE
Fix falling through floor

### PR DESCRIPTION
**Pull request by danteruiz**
This PR attends to address the falling through the floor bug that this PR https://github.com/highfidelity/hifi/pull/13471 uncovered.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11164/HighFidelity-Beta-PR13558-3cc54c5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11164/HighFidelity-Beta-PR13558-3cc54c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11164/HighFidelity-Beta-Interface-PR13558-3cc54c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11164/HighFidelity-Beta-PR13558-3cc54c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11164/HighFidelity-Beta-Interface-PR13558-3cc54c5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11167/HighFidelity-Beta-PR13558-fdf58ab.apk

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11167/HighFidelity-Beta-PR13558-fdf58ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11167/HighFidelity-Beta-Interface-PR13558-fdf58ab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11167/HighFidelity-Beta-PR13558-fdf58ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11167/HighFidelity-Beta-Interface-PR13558-fdf58ab.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Could not reproduce the falling bug on a domain containing avatar island where it had occurred to me before.

Zone setting can limit flight as expected

**Pull request merged**
