### PR TITLE
Fix progressive loading of KTX cubemaps

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53e46d2768fcbfd114e7e5e0c6cf79c65ceaff6b available at: https://gist.github.com/a3702531615566cb0ed0e4b8b0e202cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10470-53e46d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10470-53e46d2.dmg

**Comment by huffman** [comment]
Test plan coming soon

**Comment by huffman** [comment]
To test:

 1. Upload https://hifi-public.s3.amazonaws.com/huffman/SKY-Forest-2-toon2.ktx to your asset server
 1. Close interface
 1. Clear your cache (ex: `C:\Users\USERNAME\AppData\Local\High Fidelity - PR10470`)
 1. Open interface, go to `localhost/garden`
  1. You should see the skybox come in relatively fast at a low resolution, and progressively increase in resolution
  1. You should see requests for `atp:/SKY-Forest-2-toon2.ktx#...` in your list of active downloads in stats as everything is loading

**Comment by CainFoool** [comment]
Testing

**Comment by CainFoool** [comment]
Test Completed

Game crashes when loading any room after a random amount of seconds, seems to be when the skybox is beginning to load though that may just be a coincidence.

Attached logs, and this is a **FAIL.
[10470-LOGS.zip](https://github.com/highfidelity/hifi/files/1005657/10470-LOGS.zip)
**

**Comment by ZappoMan** [comment]
good news is - we're getting a crash dump from these crashes...

```
interface!ktx::KTX::writeImages	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/ktx/src/ktx/writer.cpp(235)
interface!ktx::KTX::write	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/ktx/src/ktx/writer.cpp(124)
interface!ktx::KTX::create	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/ktx/src/ktx/writer.cpp(37)
interface!gpu::Texture::serialize	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/gpu/src/gpu/texture_ktx.cpp(419)
interface!ImageReader::read	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/model-networking/src/model-networking/texturecache.cpp(840)
interface!ImageReader::run	c:/jenkins/workspace/beta_pr-master/label/windows/libraries/model-networking/src/model-networking/texturecache.cpp(770)
Qt5Core
```

**Comment by CainFoool** [comment]
I'll be ready to test once any commits are sent out!

**Comment by huffman** [comment]
@CainFoool The next build should fix the issue. Thanks for waiting!

**Comment by CainFoool** [comment]
@huffman: Waiting for next build!

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0212ac32bc824de8a2345f054b6e1b7a500695f available at: https://gist.github.com/a3702531615566cb0ed0e4b8b0e202cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10470-e0212ac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10470-e0212ac.dmg

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
Test Complete

Working as intended - went to localhost/garden, set the URL of the Skybox, renamed the cache folder to cache-old and re-launched the interface to localhost/garden. Skybox loaded nearly instantly with the graphics over time increasing.

**TEST PASSED**

**Pull request merged**
