### PR TITLE
Stable -> Master

### PR DESCRIPTION
**Pull request by Atlante45**
@cozza13 There's a change in this PR because I believe @sethalves' commit 39fb94d was cherry-picked into the RC44 but never merged into master.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/883/HighFidelity-Beta-PR10750-93f667d4db906cf6db3ccc5909dcb7fcc9ac3b53.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/883/HighFidelity-Beta-PR10750-93f667d4db906cf6db3ccc5909dcb7fcc9ac3b53.dmg

**Comment by Atlante45** [comment]
@cozza13 I just updated this with the hotfix that just went out.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/923/HighFidelity-Beta-PR10750-6bd1946e96352552294fe283cd94c1dda95ef4ba.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/923/HighFidelity-Beta-PR10750-6bd1946e96352552294fe283cd94c1dda95ef4ba.dmg

**Pull request merged**
