### PR TITLE
First cut at adding "Atmosphere" support to zone

### PR DESCRIPTION
**Pull request by ZappoMan**
This PR adds the ability to change the environment/atmosphere rendering when you enter a zone. The same zone logic is in play to determine which zone is currently active. If the zone has a skyboxMode of "atmosphere" then it will adjust the environment data to allow you to over ride the default environment information.

This also introduces the idea of "PropertyGroups" which is used by the atmosphere property.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32ef0c20100a6efd4ed78d680fe4c2aa17aee8cf available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c02bfdda5534d6c54633f9ead86fd26c9e47ccb available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f8c52cdd48d533d3730a26e381a0fba245e68d8 available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b3b32c70d502d4ef0df46f7b2b8e74759fb6857 available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b9c6728e76bbae38543e38a0b031cf56de64f88 available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4422c63c791471c5fc705842b5b3e123585d73aa available at: https://gist.github.com/d9a40270b5b15d42f39e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4764.dmg

**Comment by samcake** [comment]
Ok , i tested, it "looks" like it's working but it s couldn;t validate that the result i get is coherent with the settings
the skydome indeed changed when i entered the zone, so this seems to be good

I would like to discuss hwo we should change the effect and maybe simplify a bit the settings after we merge that

**Pull request merged**
