### PR TITLE
Allow scripts to receive a visibility changed signal from their windows

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by howard-stearns** [comment]
I'll merge after it builds.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f451269cd7b67bd94554a21f85830fefd92e546 available at: https://gist.github.com/71f6ffd822ec3e6aaf92e8056d82030e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8168.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8168.dmg

**Comment by jherico** [comment]
## Testing

Currently if you attempt to connect to the visibleChanged signal of a QML or web window created from JS, your callback will never be called.  With this change your callback will be correctly called.

An example script showing this is [here](https://s3.amazonaws.com/DreamingContent/scripts/overlayTestQml.js).  When the window is made visible or invisible, either through manipulation of the window itself, or through hiding and showing the UI, the callback should be triggered and a log message produced.

**Comment by howard-stearns** [comment]
I just realized that it won't do for me to change entityList.js later, in my own upcoming PR, because in between the merge of this PR and mine, we will have a dev build in which edit.js doesn't load properly.

So,,, I think we need to have this PR:
- edit line 114 of scripts/system/libraries/entityList.js and change webView.visibilityChanged to webView.visibleChanged,
- remove the visible argument in the handler
- change if (visible) to if (webView.visible)

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfb6cb1aa340f04d4116efc8c621fa3d08f08aca available at: https://gist.github.com/71f6ffd822ec3e6aaf92e8056d82030e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8168.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8168.dmg

**Pull request merged**
