### PR TITLE
FB11123 Make the certificate GOLD (and change title to Proof of Prove…

### PR DESCRIPTION
**Pull request by ElderOrb**
…nance License)

https://highfidelity.fogbugz.com/f/cases/11123/Make-the-certificate-GOLD-and-change-title-to-Proof-of-Provenance-License
  
***Test plan***

1. Go to market
2. Buy some item & rezz (I used box of balls)
3. Inspect it by pointing half-pulled laser to item
4. Ensure certificate info has golden background and font colors like on the following sample: 

image

5. Ensure title changed from 'PROOF OF PURCHASE' to 'Proof of Provenance'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6025/app_12098_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6025/HighFidelity-Beta-PR12098-eb4da2d6c1714f56261650a4d73328d248098d55.dmg

**Comment by Qliemillar** [comment]
Build this please

**Comment by cain-kilgore** [comment]
test this please

**Comment by Nex-Pro** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6071/app_12098_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6071/HighFidelity-Beta-PR12098-eb4da2d6c1714f56261650a4d73328d248098d55.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6071/HighFidelity-Beta-PR12098-eb4da2d6c1714f56261650a4d73328d248098d55.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Stopped testing per @zfox23

**Comment by ElderOrb** [comment]
What exactly needs to be changed? I don't see any comments.

**Comment by zfox23** [comment]
@ElderOrb nothing, yet. we have to talk about who had the idea to change the language at the top of the certificate, because we're in disagreement about that change. we'll talk about it at standup in a little bit.

**Comment by changxc** [comment]
I apologize that I had a typo on the original ticket. The title should be "certificate" (first line) and "Proof of Provenance" (second line)

**Comment by ElderOrb** [comment]
Np, removed excess 'License' word

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6106/app_12098_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6106/HighFidelity-Beta-PR12098-0f6b93eaea5ff25a49b07e63f6cfd38d78f24ed9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6106/HighFidelity-Beta-PR12098-0f6b93eaea5ff25a49b07e63f6cfd38d78f24ed9.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6150/app_12098_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6150/HighFidelity-Beta-PR12098-0f6b93eaea5ff25a49b07e63f6cfd38d78f24ed9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6150/HighFidelity-Beta-PR12098-0f6b93eaea5ff25a49b07e63f6cfd38d78f24ed9.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed for PR#12098. PASSED.

**Pull request merged**
