### PR TITLE
Fix for auto-reopening of closed query dialogs (aka hack-on-top-of-hack)

### PR DESCRIPTION
**Pull request by ElderOrb**
The same as https://github.com/highfidelity/hifi/pull/12807 but for RC66

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8554/app_12808_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8555/app_12808_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8554/HighFidelity-Beta-PR12808-557b7ded668f56f641f68019620d80ee13d5fa78.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8555/HighFidelity-Beta-PR12808-557b7ded668f56f641f68019620d80ee13d5fa78.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by sethalves** [comment]
to test:
- see https://github.com/highfidelity/hifi/pull/12807

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8607/app_12808_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8607/HighFidelity-Beta-PR12808-557b7ded668f56f641f68019620d80ee13d5fa78.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8621/app_12808_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8621/HighFidelity-Beta-PR12808-557b7ded668f56f641f68019620d80ee13d5fa78.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Dialog box to import entities does not reappear and is dismissed correctly.

**Pull request merged**
