### PR TITLE
Fix audio page being set to desktop when starting in HMD.

### PR DESCRIPTION
**Pull request by danteruiz**
Fixed the issue of when you start in HMD mode, the audio page will be set to desktop page.

ticket - https://highfidelity.manuscript.com/f/cases/16933/Starting-interface-into-HMD-mode-causes-interface-audio-to-be-set-for-desktop

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- make sure you launch interface in HMD mode.
- open the audio page.
- make sure that the HMD tab is selected when you open the app.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11551/HighFidelity-Beta-PR13690-a21a475.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11551/HighFidelity-Beta-PR13690-a21a475.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11551/HighFidelity-Beta-Interface-PR13690-a21a475.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11551/HighFidelity-Beta-PR13690-a21a475.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11551/HighFidelity-Beta-Interface-PR13690-a21a475.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASSED @conklin94122 verified that when launching interface in HMD the audio page is set to VR instead of desktop.

**Pull request merged**
