### PR TITLE
[Case 4315] Edit menu color picker OK button is hard to use in HMD

### PR DESCRIPTION
**Pull request by 1P-Cusack**
* This removes the OK button which was hard to use in HMD mode in favor of having the color dynamically updating while utilizing the color picker.  For consistency, this change applies to both HMD & Desktop modes.
* Fixes issue where changing the color or hue via the color picker had input bleeding through and applied to the Edit menu in its context.
* Has various eslint/jshint fixes.

NOTE:  This was originally proposed along with other changes as PR #12058; however, it was closed in favor of submitting changes in more atomic PRs.  This is the initial atomic PR.  Known pre-existing issues found while addressing this case which will be addressed in the subsequent PRs are:

1. Color Picker original/initial color preview being black.
2. Color Picker not showing the old vs new color preview as it should
3. Color Picker original color restore not working.

**Testing**

Testing should be done in both Desktop & HMD modes.

Create or select an instance of a light, text, shape, and zone entity within the world.  Below is a listing of all known color fields:

* Light Color
* Text Color
* Text Background Color
* Shape Color
* Haze Key Light Color
* Haze Glaze Color
* Haze Glare Color

Each color field should:

- have its OK button removed.
- have the relevant color on the entity update dynamically as the user drags around the color picker hue & wheel areas.
- changing the color or hue via the color picker shouldn't scroll the Edit menu behind it

**_Before Example Light Color Field:_**
case4315_lightcolor_before

**_After Example Light Color Field:_**
case4315_lightcolor_afterok

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6553/app_12241_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6553/HighFidelity-Beta-PR12241-180be18178139099b9e42662d8c1e9282b438238.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6553/HighFidelity-Beta-PR12241-180be18178139099b9e42662d8c1e9282b438238.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by misslivirose** [comment]
I'm not convinced that removing the button entirely makes it more intuitive to a user that their change is going to immediately be applied... especially in HMD mode, where they might accidentally hover over the color changer and not have a quick way to revert it or evaluate before making the edit in real time.

**Comment by 1P-Cusack** [comment]
@misslivirose, @themelissabrown:  When clicking on the color picker the hue & color gradient sections are the most prevalent controls on the newly displayed layout and should invite the user to try them.  The intuitive/ease of use comparison is something that can be assessed during play testing sessions.  

Regarding the cancelling the color change, especially in HMD mode.  That functionality is broken on master it's just not as apparent as the submission button forces the user to have re-open the picker if they change their mind on the color after submission and seeing it applied.  There's a fix for it which is applicable in either usage case (submission/no-submission); however, it's not in this PR as it was requested that all changes from [PR #12058](https://github.com/highfidelity/hifi/pull/12058) be broken into smaller more atomic fixes.  The follow up PR for this will have all the fixes mentioned in NOTE section of this PR.

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6850/app_12241_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6850/HighFidelity-Beta-PR12241-180be18178139099b9e42662d8c1e9282b438238.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6850/HighFidelity-Beta-PR12241-180be18178139099b9e42662d8c1e9282b438238.dmg

**Pull request merged**
