### PR TITLE
JavaScript exception in toggleAdvancedMovementForHandControllers.js

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixing uncaught JavaScript exception in https://github.com/highfidelity/hifi/pull/13238.

https://highfidelity.manuscript.com/f/cases/15453/JavaScript-exception-in-toggleAdvancedMovementForHandControllers-js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10222/HighFidelity-Beta-PR13258-adaf23e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10222/HighFidelity-Beta-PR13258-adaf23e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10222/HighFidelity-Beta-Interface-PR13258-adaf23e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10222/HighFidelity-Beta-PR13258-adaf23e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10222/HighFidelity-Beta-Interface-PR13258-adaf23e.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Forward and Backward controls do not function after close/reopening application. Toggling advanced controls on/off causes forward and backward controls to work as expected.
Logs included
[PR13258.zip](https://github.com/highfidelity/hifi/files/2059486/PR13258.zip)

**Comment by wayne-chen** [comment]
Please re-test these when builds are ready.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10284/HighFidelity-Beta-PR13258-9f20d52.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10284/HighFidelity-Beta-PR13258-9f20d52.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10284/HighFidelity-Beta-Interface-PR13258-9f20d52.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10284/HighFidelity-Beta-PR13258-9f20d52.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10284/HighFidelity-Beta-Interface-PR13258-9f20d52.dmg

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Forward/Backward controls function when application is closed/reopened with Advance controls for Hand Controllers enabled.

**Pull request merged**
