### PR TITLE
Move record script files to unpublishedScripts directory

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing: For @anshuman64 to QA

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/246/HighFidelity-Beta-PR10570-d891c834ba720d59831edaa266b5f2b6aebf8364.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/246/HighFidelity-Beta-PR10570-d891c834ba720d59831edaa266b5f2b6aebf8364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/275/HighFidelity-Beta-PR10570-f0c56dac3f017f49c94219b63026a382ce0b3a8c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/275/HighFidelity-Beta-PR10570-f0c56dac3f017f49c94219b63026a382ce0b3a8c.dmg

**Pull request merged**
