### PR TITLE
Fixed issue with QTextStream in JSBaker

### PR DESCRIPTION
**Pull request by utkarshgautamnyu**
Please use testing notes from https://github.com/highfidelity/hifi/pull/11455

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4411/HighFidelity-Beta-PR11674-ff0af9f5ccf627117b82d4547072a82617ab2b17.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4411/HighFidelity-Beta-PR11674-ff0af9f5ccf627117b82d4547072a82617ab2b17.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Run the built Interface, Domain Server and Assignment Client **Check**
Launch the asset server and upload a JavaScript file **Check**
Observe that JS file appears as bakeable and its baked status is toggleable **Check**
Assignment Client logs should also reflect that JS baking has been performed. (PFA Sample logs) **Check**
Launch the Scripting Console and run the minified JS file present in the Asset Server using
command like Script.include('atp:/butterflies.js'); **Check**
a)Observe that the baked script is functionally equivalent to its original counterpart. **Check**
b)When we run the script, observe that assignment client logs indicate that the call for the script **Check**
has been redirected to the baked script. **Check**
Observe the unbaked files present in Asset Server should start baking on the launch of asset server. **Check**

All **Pass** :)

**Pull request merged**
