### PR TITLE
change handling of life-time of TabletProxy QObjects

### PR DESCRIPTION
**Pull request by sethalves**
- fix a tablet memory-handling bug that was causing an occasional crash

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4099

**Comment by sethalves** [comment]
to test:
- use the tablet, esp the PEOPLE and GOTO pages

**Comment by hifi-gustavo** [comment]
Build console output for commit: 077a4fe4ae0e4a9814eea210b401b5fe6fb51d8b available at: https://gist.github.com/dc6c35eab84a66121e3946dcea93396f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10193-077a4fe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10193-077a4fe.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10 - CV1 + Touch controllers.
QA Pass

Repeatedly brought up/dismissed tablet - made heavy use of people and places functions along with lighter use of all other options.  That said, I didn't find it easy to crash master, but, compared to master that I was able to crash once -- this PR did not crash despite greater count/length of attempting to.

**Pull request merged**
