### PR TITLE
Fix deleted action not being sent over the network correctly - RC61.1

### PR DESCRIPTION
**Pull request by druiz17**
https://github.com/highfidelity/hifi/pull/12061 - refer to this PR.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan - refer to this PR https://github.com/highfidelity/hifi/pull/12061

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5835/app_12062_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5837/app_12062_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5837/HighFidelity-Beta-PR12062-86be684d7ad5519d30acfa329cd605b8849c1a89.exe

**Comment by conklin94122** [comment]
Verified with the help of @MiladNazeri and @hyperlogic

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5843/app_12062_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5843/HighFidelity-Beta-PR12062-86be684d7ad5519d30acfa329cd605b8849c1a89.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5843/HighFidelity-Beta-PR12062-86be684d7ad5519d30acfa329cd605b8849c1a89.dmg

**Pull request merged**
