### PR TITLE
Fix interstitial page not displaying at Interface start-up

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Also fixes up interstitial JSDoc.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14423/HighFidelity-Beta-PR14284-e2ae503.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14423/HighFidelity-Beta-PR14284-e2ae503.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14423/HighFidelity-Beta-Interface-PR14284-e2ae503.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14423/HighFidelity-Beta-PR14284-e2ae503.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14423/HighFidelity-Beta-Interface-PR14284-e2ae503.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Interstitial did not appear with either method described in test plan


[Logs.zip](https://github.com/highfidelity/hifi/files/2525990/Logs.zip)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14970/HighFidelity-Beta-PR14284-aca7143.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14970/HighFidelity-Beta-Interface-PR14284-aca7143.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14970/HighFidelity-Beta-PR14284-aca7143.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14970/HighFidelity-Beta-Interface-PR14284-aca7143.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14989/HighFidelity-Beta-PR14284-aca7143.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14989/HighFidelity-Beta-PR14284-aca7143.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14989/HighFidelity-Beta-Interface-PR14284-aca7143.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14989/HighFidelity-Beta-PR14284-aca7143.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14989/HighFidelity-Beta-Interface-PR14284-aca7143.exe

**Pull request merged**
