### PR TITLE
case 15962: case 20481: Mouse grab with traits

### PR DESCRIPTION
**Pull request by sethalves**
- rework mouse-grab to use traits-based grabbing
- remove leftover grabbing code

https://highfidelity.manuscript.com/f/cases/15962/Clicking-on-colliding-objects-causes-them-to-be-dynamic-Desktop-only
https://highfidelity.manuscript.com/f/cases/20481/Non-dynamic-objects-grabbed-with-mouse-when-interpenetrating-other-objects-often-take-on-rotational-velocity

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- test hand-controller grabbing
- test mouse grabbing
- test interactions between these

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16440/HighFidelity-Beta-PR14710-403905d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16440/HighFidelity-Beta-PR14710-403905d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16440/HighFidelity-Beta-Interface-PR14710-403905d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16440/HighFidelity-Beta-PR14710-403905d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16440/HighFidelity-Beta-Interface-PR14710-403905d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16460/HighFidelity-Beta-PR14710-b532693.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16460/HighFidelity-Beta-PR14710-b532693.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16460/HighFidelity-Beta-Interface-PR14710-b532693.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16460/HighFidelity-Beta-PR14710-b532693.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16460/HighFidelity-Beta-Interface-PR14710-b532693.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16463/HighFidelity-Beta-PR14710-5259a67.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16463/HighFidelity-Beta-PR14710-5259a67.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16463/HighFidelity-Beta-Interface-PR14710-5259a67.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16470/HighFidelity-Beta-PR14710-694fc97.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16463/HighFidelity-Beta-PR14710-5259a67.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16463/HighFidelity-Beta-Interface-PR14710-5259a67.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16474/HighFidelity-Beta-PR14710-b1c34eb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16474/HighFidelity-Beta-PR14710-b1c34eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16474/HighFidelity-Beta-Interface-PR14710-b1c34eb.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16475/HighFidelity-Beta-PR14710-c4fc884.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16475/HighFidelity-Beta-PR14710-c4fc884.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16475/HighFidelity-Beta-Interface-PR14710-c4fc884.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16475/HighFidelity-Beta-PR14710-c4fc884.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16475/HighFidelity-Beta-Interface-PR14710-c4fc884.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
