### PR TITLE
RC66: use serverless content with baked skybox and help textures

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8709/app_12866_PR.apk

**Comment by birarda** [comment]
### Test Plan

This PR bakes the skybox and help textures in the tutorial.

(1) Ensure that the skybox appears in the serverless tutorial.
(2) Run the test cases under "Local Tutorial" here https://highfidelity.testrail.net/index.php?/suites/view/33&group_by=cases:section_id&group_order=asc&group_id=4891. These will specifically test the presence and readability of the right help textures for each platform.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8712/app_12866_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8712/HighFidelity-Beta-PR12866-16f6ac529536e07c524614e9ecc7325c80bcf13f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8712/HighFidelity-Beta-PR12866-16f6ac529536e07c524614e9ecc7325c80bcf13f.dmg

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Textures look good and as expected in serverless.

**Pull request merged**
