### PR TITLE
Fix for resource downloads getting capped

### PR DESCRIPTION
**Pull request by huffman**
This fixes a few bugs:

 * ResourceCache max downloads getting capped below 16
 * GPU access of ktx file not being thread-safe
 * NetworkTexture not checking if _self is null (no references) when requesting a lower mip

All of these revolve around loading KTX files and switching between domains while downloading/loading them.

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Clear cache
 2. Go into dev-welcome
 3. When you see a bunch of `.ktx#head` or `.ktx#NUMBER` files being downloaded, switch to `dev-demo`
 4. Do the same in `dev-demo`
 5. Go back to step 2. Repeat this several times.

On current master you will pretty regularly either crash or see the number of active downloads be below 16 despite there being many pending downloads. You should not see that on this PR.

**Comment by huffman** [comment]
Windows download available at: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-4b0bd80.exe

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b0bd80c270254ead7f22ffe09934a9f99bfff6d available at: https://gist.github.com/c7d2e21a8ed307f2145af977b7ab57d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-4b0bd80.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-4b0bd80.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b0bd80c270254ead7f22ffe09934a9f99bfff6d available at: https://gist.github.com/c7d2e21a8ed307f2145af977b7ab57d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-4b0bd80.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-4b0bd80.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2faa8fb671508dcf85841ba82a3fd6b0bfd1fe99 available at: https://gist.github.com/c7d2e21a8ed307f2145af977b7ab57d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-2faa8fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10307-2faa8fb.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
@huffman I can't get into dev-demo. Probably same for all QAs user Piper.Peppercorn

**Comment by huffman** [comment]
@Nex-Pro Ok, any other domain will do. I updated it to be `localhost`

**Comment by birarda** [comment]
Marking this QA approved because it's effect has been sufficiently tested for RC-38.

**Pull request merged**
