### PR TITLE
Goto close

### PR DESCRIPTION
**Pull request by howard-stearns**
Close button and frame on goto address bar.
Don't make address bar jump around in size and loose keyboard when click off of it.

fixes:
https://highfidelity.fogbugz.com/f/cases/1848/There-is-no-way-to-close-the-Goto-dialogs-without-keboard
https://highfidelity.fogbugz.com/f/cases/1523/when-address-bar-auto-opens-and-then-interface-connects-the-bar-should-auto-close (fixed with explicit close, because it should NOT auto-close)

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
Open address bar (desktop and hmd). Should be closeable with close button, which should highlight, using mouse or keyboard.
Closing with the close button, goto button toggle, or (physical or virtual) keyboard "enter" key should close and update the state of the goto button. (i.e., they should match)
Should not be draggable or resizable.
Opening a suggestion card by clicking the suggestion icon (snapshot or concurrency picture) should cover the address bar content and enough of the frame as to be not confusing.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 285ae474f51f4a2f096d0b6a6b50d30784bbe7a7 available at: https://gist.github.com/6966de4347279bd9c00a6a64aaba9ab3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8817-285ae47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8817-285ae47.dmg

**Comment by ctrlaltdavid** [comment]
Note: https://github.com/highfidelity/hifi/pull/8799 changes keyboard to be visible only in HMD mode.

**Comment by cozza13** [comment]
Check that I could close the address bar with mouse and hmd controller. Also checked I could still close the address bar the old way.

**Pull request merged**
