### PR TITLE
fix laser interaction on HUD in HMD mode

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- https://highfidelity.testrail.net/index.php?/tests/view/17492&group_by=cases:section_id&group_order=asc&group_id=69

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

**Fail** w/ notes. TestRail Results: https://highfidelity.testrail.net/index.php?/tests/view/17492&group_by=cases:section_id&group_order=asc&group_id=69

**Comment by druiz17** [comment]
@YuppyPlays this PR fixes the interaction with the HUD/toolbar mode in HMD. If you enable the toolbar option from developer settings and you can interact with the toolbar in HMD its a QA pass. Reading through the test plan and some of the cases are not clear.

**Comment by Nex-Pro** [comment]
@druiz17 Do you want me to test this. I am keen to see this working perfectly.

**Comment by druiz17** [comment]
@Nex-Pro @YuppyPlays  It doesn't matter who tests this. I just want someone to confirm that you can interact with the HUD in HMD. That is the test  plan that was in the ticket, but I think it not correct/confusing.

**Comment by Nex-Pro** [comment]
@druiz17 This is all good apart from:
 after clicking the create icon the lasers no longer interact with the hud and the create dialog cannot be closed.

**Comment by Nex-Pro** [comment]
Button state toggling and window swapping for all  buttons other than CREATE seem ok.

**Comment by druiz17** [comment]
There is a ticket created for that. Will be addressed in a separate PR.

**Comment by Nex-Pro** [comment]
@druiz17 Cool. There are a bunch of regular users keen to see this fully resolved.

**Pull request merged**
