### PR TITLE
steam gets the oculus store commerce treatment

### PR DESCRIPTION
**Pull request by howard-stearns**
@Atlante45 , please check me that this is the right way to tell if you are running from the steam store

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20604/HighFidelity-Beta-PR15994-6ef0821.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20604/HighFidelity-Beta-Interface-PR15994-6ef0821.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20604/HighFidelity-Beta-PR15994-6ef0821.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20604/HighFidelity-Beta-Interface-PR15994-6ef0821.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20604/HighFidelity-Beta-PR15994-6ef0821.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20604/HighFidelity-Quest-Beta-PR15994-6ef0821.apk)

**Comment by JeffClinton** [comment]
Pre-merge testing complete:
- Steam store build is missing wallet creation for new accounts
- Marketplace only displays free items for new and existing accounts
- Still appear to have access to my full inventory on existing account

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20647/HighFidelity-Beta-PR15994-6ef0821.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20647/HighFidelity-Beta-Interface-PR15994-6ef0821.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20647/HighFidelity-Beta-PR15994-6ef0821.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20647/HighFidelity-Beta-Interface-PR15994-6ef0821.dmg

**Pull request merged**
