### PR TITLE
fixing setting incorrect parent when grabbing entities

### PR DESCRIPTION
**Pull request by druiz17**
If an entities is parented to you. Grab the entity with both hands and ungrab in a certain. The parent id of the entity will not be set back correctly

ticket - https://highfidelity.fogbugz.com/f/cases/8552/Attached-avatar-entities-occasionally-detach-when-handled

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- run these test plans - https://highfidelity.testrail.net/index.php?/cases/view/1577&group_by=cases:section_id&group_order=asc&group_id=323
https://highfidelity.testrail.net/index.php?/cases/view/484&group_by=cases:section_id&group_order=asc&group_id=13
- perform the same tests after a person has purchased the item and is wearing the item.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5032/HighFidelity-Beta-PR11838-b66153b9cb3df27af9a4802dbc8e0442a4788443.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5032/HighFidelity-Beta-PR11838-b66153b9cb3df27af9a4802dbc8e0442a4788443.dmg

**Comment by cain-kilgore** [comment]
Testing w/Aaron.

**Comment by cain-kilgore** [comment]
# Hold
Test is pending, due to domain mismatch.
[TestRail Run 1029](https://highfidelity.testrail.net/index.php?/runs/view/1029&group_by=cases:section_id&group_order=asc)
[TestRail Run 1030](https://highfidelity.testrail.net/index.php?/runs/view/1030&group_by=cases:section_id&group_order=asc)

**Comment by ZappoMan** [comment]
@cain-kilgore - you can ALWAYS run a set of tests against the sandbox included in the PR... just install the PR, and then do the tests in the local host sandbox. This will ensure that you don't have a protocol mismatch. For PRs like this that don't have protocol changes, we don't need to confirm that the PR works with other public domains.

Consider retesting with the Sandbox. Thanks

**Comment by cain-kilgore** [comment]
@ZappoMan Can do - will get to it shortly. :)

**Comment by Nex-Pro** [comment]
dropping awaiting reply.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5111/HighFidelity-Beta-PR11838-56972d15476bb6029840973cce4f8fbeccdf9418.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5111/HighFidelity-Beta-PR11838-56972d15476bb6029840973cce4f8fbeccdf9418.dmg

**Comment by Nex-Pro** [comment]
### PASS

https://highfidelity.testrail.net/index.php?/tests/view/16897&group_by=cases:section_id&group_order=asc&group_id=323

https://highfidelity.testrail.net/index.php?/tests/view/16921&group_by=cases:section_id&group_order=asc&group_id=13

@druiz17

**Pull request merged**
