### PR TITLE
Improve text in Avatar app's pop-ups

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
#### Test Plan

- Open the Avatar app.
- Click "Add" to open the pop-up to add a wearable.
  - It should include, "Use wearables in My Purchases." (instead of "Wear wearables from My Purchases.").
  - It should include, "Visit “AvatarIsland” to get wearables." (instead of "Visit “AvatarIsland” to get wearables" without the "."). 
-  Click "Get More Avatars" to open the pop-up to get avatars.
  - It should include, "Wear avatars in My Purhcases." (instead of "Wear avatars from My Purchases.").

https://highfidelity.manuscript.com/f/cases/17208

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11848/HighFidelity-Beta-PR13752-f9d9324.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11848/HighFidelity-Beta-PR13752-f9d9324.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11848/HighFidelity-Beta-Interface-PR13752-f9d9324.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11848/HighFidelity-Beta-PR13752-f9d9324.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11848/HighFidelity-Beta-Interface-PR13752-f9d9324.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11900/HighFidelity-Beta-PR13752-f9d9324.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11900/HighFidelity-Beta-PR13752-f9d9324.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11900/HighFidelity-Beta-Interface-PR13752-f9d9324.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11900/HighFidelity-Beta-PR13752-f9d9324.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11900/HighFidelity-Beta-Interface-PR13752-f9d9324.dmg

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 verified that "." is included in "Visit "avatarisland" to get wearables." and also verified that "Wear avatars in my purchases" is also grammatically correct.

**Pull request merged**
