### PR TITLE
case 22353: Mac Game loop performances was borked

### PR DESCRIPTION
**Pull request by samcake**
https://highfidelity.manuscript.com/f/cases/22353/Mac-Resizing-the-interface-window-makes-interface-unresponsive-and-general-mac-performance-is-extremely-poor

THis was introduced in pr 15267, We just reintroduce the gl context make current and done for Macos only and the drop of performances and bad resizing is gone.

## TEST PLAN
On Macos only:
The performance of the gameloop should be back to pre-10259 build
The resizing of Interface main window should work correctly,
Nitpick on mac should work with the initial resizing of the window.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19013/HighFidelity-Beta-PR15467-5d87c4c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19013/HighFidelity-Quest-Beta-PR15467-5d87c4c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19013/HighFidelity-Beta-PR15467-5d87c4c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19013/HighFidelity-Beta-Interface-PR15467-5d87c4c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19013/HighFidelity-Beta-PR15467-5d87c4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19013/HighFidelity-Beta-Interface-PR15467-5d87c4c.exe

**Comment by samcake** [comment]
checking

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19035/HighFidelity-Beta-PR15467-d08e2e5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19035/HighFidelity-Quest-Beta-PR15467-d08e2e5.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19035/HighFidelity-Beta-PR15467-d08e2e5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19035/HighFidelity-Beta-Interface-PR15467-d08e2e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19035/HighFidelity-Beta-PR15467-d08e2e5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19035/HighFidelity-Beta-Interface-PR15467-d08e2e5.exe

**Pull request merged**
