### PR TITLE
MS18269: Fix Reloading Scripts with Create open crashes system

### PR DESCRIPTION
**Pull request by thoys**
Temporary fix for reload crash https://highfidelity.fogbugz.com/f/cases/18269/Reloading-Scripts-with-Create-open-crashes-system

## QA Test
1) Open Interface in desktop mode
2) Open the Create App (Both windows `Create Tools` and `Entity List` should appear)
4) While the windows are up use the Reload Script option ` Edit -> Running Scripts -> Reload Scripts`
5) Open Create App again  (Both windows `Create Tools` and `Entity List` should appear again)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12814/HighFidelity-Beta-PR13968-2000954.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12814/HighFidelity-Beta-PR13968-2000954.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12814/HighFidelity-Beta-Interface-PR13968-2000954.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12814/HighFidelity-Beta-PR13968-2000954.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12814/HighFidelity-Beta-Interface-PR13968-2000954.exe

**Comment by QliCknox** [comment]
We should remove the QA Ready label until PR13964 is merged to make sure the Running Script crashes I'm seeing in this PR aren't caused by MS18044 not being fixed in the current build of this PR.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12823/HighFidelity-Beta-PR13968-2000954.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12823/HighFidelity-Beta-Interface-PR13968-2000954.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12823/HighFidelity-Beta-PR13968-2000954.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12823/HighFidelity-Beta-Interface-PR13968-2000954.exe

**Comment by QliCknox** [comment]
Pass @conklin94122 

Reloading Scripts with Create open does not crash the Interface!

**Pull request merged**
