### PR TITLE
Handle drag-n-dropped .svos and using interface to open .svo files

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/c12bb36ef794483749de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Comment by huffman** [comment]
pleast test this

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/0036da9d0f4d6298564c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/c12bb36ef794483749de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/0036da9d0f4d6298564c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/c12bb36ef794483749de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76ebac118579d8a4aea348112d9dcef02bf2dbb8 available at: https://gist.github.com/c12bb36ef794483749de<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4424.dmg

**Pull request merged**
