### PR TITLE
7925 Create Mode: keyboard focused entry field is not visible

### PR DESCRIPTION
**Pull request by ElderOrb**
note: changed the way of calculation scroll value after showing virtual keyboard.
Now it doesn't require KEYBOARD_HEGHT and will always try to position focused element at vertical center of the client area

**Test plan**

1. Open tablet
2. Go to the different pages in 'Create' 
3. Select different text fields. 
4. Ensure focused element always scrolls at the vertical center of the available area when virtual keyboard appears. 
5. Check scrolling on the Create app and other apps to make sure nothing is broken

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3693/HighFidelity-Beta-PR11476-00c3dcee2fc2059320d7e89d526c1d809b6c7f15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3693/HighFidelity-Beta-PR11476-00c3dcee2fc2059320d7e89d526c1d809b6c7f15.exe

**Comment by cain-kilgore** [comment]
# Test Failed
Test | Result
--- | ---
Open tablet | Pass
Go to the different pages in 'Create' | Pass
Select different text fields. | Pass
Ensure focused element always scrolls at the vertical center of the available area when virtual keyboard appears. | Fail
Check scrolling on the Create app and other apps to make sure nothing is broken | Pass

It works - once. After scrolling down and picking a few text fields, the first one recenters itself but anything after that does not work.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by ElderOrb** [comment]
Yes, right.. I forgot to mention that it will re-center only when keyboard appears. But if keyboard is already visible - it will not re-center.

**Comment by anshuman64** [comment]
Yes, let's re-center even if the keyboard was already visible. Good catch and great suggestion, Cain.

**Comment by ElderOrb** [comment]
done, please re-test. 

Note: Just to clarify, the same behavior will apply also to the desktop presentation of the same pages because from the code prospective there is no difference between desktop/vr in this place. In both cases we request keyboard and consider it as shown, but in the case of desktop it is never shown. 

Anyway, this is not a regression, this is how it used to work. The only difference now is that re-center will happen for every field under the focus, while with original implementation it would happen only once.

**Comment by cain-kilgore** [comment]
@ElderOrb: Will give it a test once the build finishes.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3723/HighFidelity-Beta-PR11476-338a230de970010fa28f4c98d4b4c934af324435.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3723/HighFidelity-Beta-PR11476-338a230de970010fa28f4c98d4b4c934af324435.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open tablet | Pass
Go to the different pages in 'Create' | Pass
Select different text fields. | Pass
Ensure focused element always scrolls at the vertical center of the available area when virtual keyboard appears. | Pass
Check scrolling on the Create app and other apps to make sure nothing is broken | Pass

It's much better now that it recenters on each Input Box which is focused on now. The delay takes a little bit getting used to though.

**Pull request merged**
