### PR TITLE
Fix hmd js

### PR DESCRIPTION
**Pull request by druiz17**
Fix the name the HMD.js searches for.

ticket - https://highfidelity.manuscript.com/f/cases/14934/No-Enter-VR-or-Exit-VR-on-Tablet-and-Toolbar-for-Vive-HMD

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Use Vive and Oculus confirm that the switch to "Enter VR" or "Exit VR" App appears on the tablet and toolbar

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9601/app_13129_PR_1a0ded4526d7f37fd4ce25df4567b249c4859a65.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9601/HighFidelity-Beta-PR13129-1a0ded4526d7f37fd4ce25df4567b249c4859a65.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9601/HighFidelity-Beta-Interface-PR13129-1a0ded4526d7f37fd4ce25df4567b249c4859a65.dmg

**Comment by conklin94122** [comment]
Spoke with Dante, changes are very limited in scope. To save some time I'll merge the changes now and have QA test them in RC67. If all's well they'll pass this PR and continue with Acceptance; if there is a problem they'll fail this PR and fall back to the previous RC67 pr.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9601/HighFidelity-Beta-PR13129-1a0ded4526d7f37fd4ce25df4567b249c4859a65.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9601/HighFidelity-Beta-Interface-PR13129-1a0ded4526d7f37fd4ce25df4567b249c4859a65.exe

**Comment by qliacoombs** [comment]
Pass @conklin94122 
Occulus still has Enter VR/Exit VR buttons and now Vive does too

**Pull request merged**
