### PR TITLE
Properly shut down scripting thread

### PR DESCRIPTION
**Pull request by zzmp**
Fixes a crash from deleting ScriptEngine instances between domains.

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Switch domains between demo and playa (or something and playa). In current build you will crash within the native thread after getting Qt warnings about thread misuse.

Some entity scripts take a while to shut down. If you go between demo and playa you will see this in the logs:
> Script  "Entities 2"  has been running too long [ 1000002  usecs] quitting.
The thread 0x15c8 has exited with code 0 (0x0).

---

@ZappoMan you will probably want to add some tests. I removed the abortEvaluation, as I saw something just go to QThread::quit, and it flooded the log. They do the same thing, as far as I can tell (abortEvaluation should cut an eval short, and quit should also cut it short when the engine allows normal events to be processed; if you have a different understanding, we should talk). I also added a yield :).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 284feaf5d437c2c7084f147581204fe8de000de3 available at: https://gist.github.com/0f28416c900aa7c289344b61bfa5b0c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7812.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7812.dmg

**Comment by ZappoMan** [comment]
We need to think about how to test this with scripts running infinite loops.

**Comment by ZappoMan** [comment]
Note: I got a crash on exit when I ran the infinite loop script above from the console... 
https://www.bugsplatsoftware.com/individualCrash/?id=3231&database=interface_alpha

**Comment by hifi-gustavo** [comment]
Build console output for commit: 56ec0e5db0f84cc76673bcb4f275f62fed8d6915 available at: https://gist.github.com/0f28416c900aa7c289344b61bfa5b0c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7812.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7812.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7812
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |59.92     |49.98    |60.01       
Present Rate:                     |60.00     |59.99    |60.00       
Present New Rate:                 |60.01     |49.99    |60.01      
Render Stats Num Buffers:         |5128      |4334     |1856        
Render Stats gpu::Buffer Memory:  |39.3Mb    |55.4Mb   |17.5Mb      
Render Stats Num Textures:        |302       |257      |57          
Render Stats gpu::Texture Memory: |567.4Mb   |1125.0Mb |193.9Mb     
Render Stats Triangles:           |406k      |684k     |252k       
Render Stats Drawcalls:           |1399      |882      |54         
Render Stats State Changes:	  |152       |239      |43          
Render Stats Items:               |3230      |366      |50       
Render Stats Timing:              |38.9ms    |24.5ms   |12.5ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |275Mb     |275Mb    |275Mb       
GPU-Z Memory Used		  |1799Mb    |2141Mb   |623Mb      
GPU-Z Memory Load		  |25%       |24%      |15%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** Successful test. Was able to connect to ``demo``` and then ``playa`` with no issue.  Successfully ran test.js which included the script that @zzmp included with no issue.  Successfully able to start/stop Interface 8 times with no issue.
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Comment by ZappoMan** [comment]
@kevinmthomas-carpool -- did you do a rapid domain change test? so basically switching between several domains over and over again quickly while they are loading?

**Comment by kevinmthomas-carpool** [comment]
@ZappoMan yes I performed the rapid domain change test with the following domains - ```music```, ```playa```, ```sandbox```, ```playa```, ```free``` and there were no issues.  Successful logout as well.

**Pull request merged**
