### PR TITLE
Fixed unable to select items in a TreeView

### PR DESCRIPTION
**Pull request by druiz17**
The seems to be a bug with newer version of Qt regarding touch events and TreeView interaction according to blogs. This PR implements a fix of unable to select items in the TreeView.

ticket - https://highfidelity.fogbugz.com/f/cases/6908/Running-Scripts-page-does-not-work-in-Tablet-HMD

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan - (HMD and Desktop mode)
- open RunningScripts
- It should be easy to select directories and script from the second table
- open the Assest Browser and you it should also be easy to select item in the table.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2489/HighFidelity-Beta-PR11190-459f2c5cdcaf9240573df5b0732f3e62ae6451c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2489/HighFidelity-Beta-PR11190-459f2c5cdcaf9240573df5b0732f3e62ae6451c4.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
--- | --- | ---
open RunningScripts | Pass | Pass
It should be easy to select directories and script from the second table | Pass | Pass
open the Assest Browser and you it should also be easy to select item in the table. | Pass | Pass

Everything seems to be able to be clicked on!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
