### PR TITLE
Default scripts only

### PR DESCRIPTION
**Pull request by imgntn**
This PR isolates only the scripts and resources necessary to run default scripts.  I'm not sure that this will be the way things get merged, but I'm hoping for feedback.   I think we should rename this folder 'default scripts' and probably make 'examples' available wholly elsewhere since that code is not easily accessible via Interface, and entity scripts launched from the /examples folder currently won't work for others because relative references will be file:// paths on other peoples computers.  

To test:
1. Make sure all default functionality still works as expected.

### CODE REVIEW

**Comment by imgntn** [comment]
had to resolve a merge conflict about ```C:\Users\james\Desktop\high_fidelity\hifi\examples\utilities\render\stats.qml```

**Comment by ZappoMan** [comment]
The diff is unreadable because it's too large for github... what did you actually change?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f1ea69928698dab7f00a4e174986ad574dc0b2f available at: https://gist.github.com/7d26717be6963324a66d0ec020568701<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb9f24571ade6db998c1ddca44562ee52a0d290f available at: https://gist.github.com/7d26717be6963324a66d0ec020568701<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.dmg

**Comment by imgntn** [comment]
i removed all of the non-default script example files -- all that's left are the files directly related to our current 'default scripts' --  i can add them in an /archive folder in this repo, or open another repo for them.  would love your feedback on the future of default scripts, developer scripts, examples / marketplace, etc @ZappoMan  -- theres lots of great stuff in examples that should get put into docs for people to learn or marketplace for people to use

**Comment by ctrlaltdavid** [comment]
As a script dev I often refer to all the scripts for "documentation", i.e., how to use the API in practice. This typically done by grep'ing all the scripts for keywords. So would sorely miss not having them available.
As a user I often us inspect.js. Well, that's not quite true, I use my own improved version of it.

**Comment by huffman** [comment]
I think we should should:
 * delete any non-functioning scripts.
 * move actual example scripts into a separate directory and organize them a little better.
 * have a /scripts directory that contains the default scripts and maybe a few other client scripts.

IMO I'd eventually like to see us treat these client-side scripts more as plugins that you turn on/off and restart, so you wouldn't have a directory listing but instead a list of scripts/plugins, some of which will be off (not running).

**Comment by imgntn** [comment]
i'll cc something i wrote to zappoman about current /examples -- 

james [1:01 PM] 
in terms of launch i think it avoids the minefield of running a script from /examples 1) that just fails 2) has a relative entity path that is local and fails for others 3) editing a default script and breaking it 4) changes to an example getting overwritten on a new install

@ctrlaltdavid i also end up searching the repository a lot for keywords, but since that's done outside of interface, i'm not sure what the benefit of having all that stuff inside of running scripts is.  a separate database of scripts would be just as (more?) searchable from inside of interface.  a simple mongodb dump of all of them with a little api, for example.

p.s. what's inspect.js?  and if yours is better, share it up!! :) should it be a default script?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ec92604ed39063427a4fbaa294c8c8d3e59e9c2 available at: https://gist.github.com/7d26717be6963324a66d0ec020568701<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94918dc57547fad72cc9d11cacb90793b3285f2d available at: https://gist.github.com/7d26717be6963324a66d0ec020568701<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7646.dmg

**Comment by ctrlaltdavid** [comment]
@imgntn inspect.js resides (or at least used to reside prior to this PR) in the root or the \examples\ directory and was included in defaultScripts.js until recently. It enables you to alt-click and zoom / rotate / zoom your camera about a point similar to Second Life.
My improvements: https://alphas.highfidelity.io/t/inspect-js-with-persistent-camera-position/7100

**Comment by imgntn** [comment]
making good progress but i'll reopen this when its done

**Pull request closed without merging**
