### PR TITLE
Adjust pistol sensitivity

### PR DESCRIPTION
**Pull request by imgntn**
This PR adjusts the way the pistol tutorial script decides to fire so that it is compatible with oculus touches.

(any hand controller)
To test, run tutorials/createPistol.js and observe that it isn't too difficult for the gun to fire.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d258c9ed7f53fa4169f330dab652f0b99d99a63d available at: https://gist.github.com/bfe23bbedb9f2e7c1b2699bb30246543<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d258c9ed7f53fa4169f330dab652f0b99d99a63d available at: https://gist.github.com/bfe23bbedb9f2e7c1b2699bb30246543<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.dmg

**Comment by imgntn** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d258c9ed7f53fa4169f330dab652f0b99d99a63d available at: https://gist.github.com/bfe23bbedb9f2e7c1b2699bb30246543<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8425-d258c9e.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: Success
**Additional Test Results + Observations**: Ran ```createPistol.js``` and found that it was very easy for the gun to fire with the hydras.

**Pull request merged**
