### PR TITLE
Restores "Select Audio DLL at runtime"

### PR DESCRIPTION
**Pull request by Atlante45**
Reverts highfidelity/hifi#9144
Restores highfidelity/hifi#9129

Test Plan:
- Make sure C:\Program Files\High Fidelity - PR9129\audio does not exist.
- Make sure audio works correctly
- Make sure Audio > Devices only lists devices once
- Must be tested on Windows 7 and on Windows 8+

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9e55e1cc52f66cf8ea3b17dfe7b2c1b5acfc8e4 available at: https://gist.github.com/417cbedcfcf0902825025723ecc10784<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-c9e55e1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-c9e55e1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9e55e1cc52f66cf8ea3b17dfe7b2c1b5acfc8e4 available at: https://gist.github.com/417cbedcfcf0902825025723ecc10784<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-c9e55e1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-c9e55e1.dmg

**Comment by OmegaHeron** [comment]
QA Pass *Windows 10 only*  No access to < 10.

Make sure C:\Program Files\High Fidelity - PR9129\audio does not exist. - confirmed
Make sure audio works correctly - Domain sounds/voice on server echo/voice on local echo all ok
Make sure Audio > Devices only lists devices once - confirmed, no dupes.
Must be tested on Windows 7 and on Windows 8+ - *Windows 10 only for me tests*

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f2c77928ac355041c06c89eb9234d0aa391c81c available at: https://gist.github.com/417cbedcfcf0902825025723ecc10784<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-5f2c779.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9154-5f2c779.dmg

**Pull request merged**
