### PR TITLE
Revert to using overlays instead of material entities for button highlighting.

### PR DESCRIPTION
**Pull request by danteruiz**
Revert to using overlays instead of material entities for button highlighting because this caused many issues like the black and white avatar.

ticket - https://highfidelity.manuscript.com/f/cases/17228/Tablet-X-Replace-Avatar-Entities-with-Overlays

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan.
* HMD
1. open tablet 
2. laser on the x button...you should see the button highlight. The x button should be centered in the highlight circle.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11914/HighFidelity-Beta-PR13774-8c5eefc.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11916/HighFidelity-Beta-PR13774-269afb9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11916/HighFidelity-Beta-PR13774-269afb9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11916/HighFidelity-Beta-Interface-PR13774-269afb9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11916/HighFidelity-Beta-PR13774-269afb9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11916/HighFidelity-Beta-Interface-PR13774-269afb9.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
