### PR TITLE
Build server only plugins

### PR DESCRIPTION
**Pull request by sethalves**
- on Linux, if cmake is given -DSERVER_ONLY=TRUE then build server-side (audio) plugins

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5485b3ee13244ef4b8973b33e55ef79a42a3c678 available at: https://gist.github.com/6190f4cbc40a1e1ede3e965831a5fc6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8286-5485b3e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8286-5485b3e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e308914b2efa62a5dfcc6f5a6e3d8d074dbe7bd available at: https://gist.github.com/6190f4cbc40a1e1ede3e965831a5fc6a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8286-4e30891.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8286-4e30891.dmg

**Comment by OmegaHeron** [comment]
Tested on Ubuntu 16.04
Built with (clean/empty build directory)
cmake -DSERVER_ONLY=TRUE ..
make assignment-client
Results in ac binary and no plugins.

Do I need to explicitly call build step for codecs?  Seems I shouldn't since they're really not optional.

**Comment by sethalves** [comment]
no, hopefully the plugins are in build/assignment-client/plugins/

**Comment by OmegaHeron** [comment]
Let me double check I didn't fubar pulling PR branch, but, I did not get plugins first try using what I outlined above.

**Comment by sethalves** [comment]
try make rather than make assignment-client

**Comment by OmegaHeron** [comment]
Giving it a shot.  That'll then just make AC/DS and Plugins?

**Comment by sethalves** [comment]
I think so.  I did:

cmake -DCMAKE_BUILD_TYPE=Release -DSERVER_ONLY=TRUE ..
make -j4

and got everything but interface and client-side plugins.

**Comment by OmegaHeron** [comment]
Cool - thanks!  Trying it now with
cmake -DCMAKE_BUILD_TYPE=Release -DSERVER_ONLY=TRUE ..
make -j8

Will let you know in about 5ish.

**Comment by OmegaHeron** [comment]
Ok - that's a winner.  It produced AC/DS AC's folder has plugins with libhifiCodec.so and libpcmCodec.so

I usually don't build ice and vhacd-util, but, that's a small price to pay for not having to compile Interface to get plugins.  Will test they work as expected than give QA Pass.  Few minutes.

**Comment by OmegaHeron** [comment]
Tested Ubuntu 16.04
Builds expected AC/DS Binaries and codecs for AC in plugins folder :+1:
Binaries work proper and codec libs are valid

Checked Windows install and see codecs with it as well

QA Pass

**Pull request merged**
