### PR TITLE
fix kinect plugin claiming to have hands when not enabled

### PR DESCRIPTION
**Pull request by ZappoMan**
This fixes the fact that xbox controllers are not able to do "third eye laser" in current builds. The problem comes from the fact that the Kinect plugin is claiming to be a hand controller, even if it's disabled.

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- Run with an HMD and xbox controller, but *without hand controllers*
- Verify that the triggers will do a "laser" for far grab and/or for picking UI elements... it will use your head/third eye as the source of the laser.
- current master builds are broken.
- Note: verify that by default in Settings > General the "Kinect" plugin is disabled.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c68f146ec6c48a1ed5bdfff3e360ced26d40206 available at: https://gist.github.com/25b3b0261df96468671588ef6aefa3e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-0c68f14.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-0c68f14.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b4865ba8455d9e731fcc143ce02e98dfef8c624 available at: https://gist.github.com/25b3b0261df96468671588ef6aefa3e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-9b4865b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-9b4865b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 449dad00b327cea1ca94e2cfb4022762febc218d available at: https://gist.github.com/25b3b0261df96468671588ef6aefa3e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-449dad0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-449dad0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a20ce6062bf41be10e4f60a7beac9f02c23c00a available at: https://gist.github.com/25b3b0261df96468671588ef6aefa3e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-2a20ce6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9613-2a20ce6.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

With HMD (DK2) connected and no xbox controller connected I see;
HMD.isHandControllerAvailable() = false in desktop mode
HMD.isHandControllerAvailable() = false in HMD DK2 mode

Now with xbox controller plugged in I see;
HMD.isHandControllerAvailable() = false in desktop mode
HMD.isHandControllerAvailable() = false in HMD DK2 mode

Third eye laser pointer works in desktop and HMD mode as expected.

There is no option in any menu for enable Kinect.  After not finding it in general I checked all the others and even toggled advanced hand control on in case that had something to do with it.  

In general I see;
UI section
Snapshots
Scripts
Privacy
Octree
HMD
Sixense Controllers
Perception Neuron

No mention of kinect option in any of those sections.

**Comment by ZappoMan** [comment]
Hmmm that's odd. Maybe the Kinect plugin only loads if the SDK is installed. So maybe this is less of a critical fix than I thought.

**Comment by OmegaHeron** [comment]
Well, I was going to add that I could repro behavior it's aimed to fix in master -- so, yeah, maybe not.  Just thought I'd give it a go as after reading test notes 3rd time I saw I actually did have the gear to check it.  Will leave it with;

General smoke test = pass.
Specific = 99.9% pass.  :)

**Comment by OmegaHeron** [comment]
Not sure how github notifies on edits - just to not make this more confusing as I originally wrote I could repro it on master due to typo.

I could *not* reproduce bad behavior this aims to fix on master.  I suspect you do have to have the SDK installed and maybe then it would act up.

**Comment by OmegaHeron** [comment]
Yes - that's it @ZappoMan - if kinect SDK is installed then you get the option so this bug wouldn't hit anyone without said SDK.

And - now with SDK installed, DK2 and xbox controller on I get false for HMD.isHandControllerAvailable()

QA Pass

**Comment by OmegaHeron** [comment]
And it returns true on master regardless of kinect enabled or not -- so it's a critical fix for sure for anyone with SDK installed ;)  End of 12:30AM babbling.

**Pull request merged**
