### PR TITLE
RC67: Desktop equip - ignore right clicks

### PR DESCRIPTION
**Pull request by dback2**
Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/15103
Also verify you can inspect equippable entities from the marketplace.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9306/HighFidelity-Beta-PR13043-61afd12eeb91539a7fa50362aeda9276ac3fd718.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9306/HighFidelity-Beta-Interface-PR13043-61afd12eeb91539a7fa50362aeda9276ac3fd718.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9306/HighFidelity-Beta-PR13043-61afd12eeb91539a7fa50362aeda9276ac3fd718.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9306/HighFidelity-Beta-Interface-PR13043-61afd12eeb91539a7fa50362aeda9276ac3fd718.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
