### PR TITLE
Android - App freezes on opening randomly - Fix

### PR DESCRIPTION
**Pull request by Cristo86**
Previous version is having the following bug:
- After closing the app, starting it again can lead to the loading screen that doesn't advance, is frozen/crashed. It required Clearing app data to run again.
- After fixing that problem, a similar bug happened but with a black screen instead of the loading screen.
- Both problems should be solved and a quick-to-appear splash screen is shown. Our traditional loading screen adds a loading indicator.

**Test plan**

1. Start the application.
2. High Fidelity splash screen should Immediately appear (no more black screen).
3. [Technical note - When Interface starts loading] A loading indicator should appear.
4. App main screen with list of domains should appear as always.
5. Close the app by pressing back (hardware button or android bottom bar button). **Next steps are critical as there we had our crash/freeze.**
6. Launch Interface again.
7. App should load as before. (In contrast with our two bugs: Stuck on Splash screen nor Black screen).
8. Exit the app by pressing home (hardware button or android bottom bar button).
9. Launch Interface again.
10. In normal memory conditions, the app should start where we left (in this case the Domains list).

Note: There is another issue: A crash that can happen when returning from a domain. That will be addressed separately.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11332/HighFidelity-Beta-PR13614-f9baeaf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11332/HighFidelity-Beta-PR13614-f9baeaf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11332/HighFidelity-Beta-Interface-PR13614-f9baeaf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11332/HighFidelity-Beta-PR13614-f9baeaf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11332/HighFidelity-Beta-Interface-PR13614-f9baeaf.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11365/HighFidelity-Beta-PR13614-c664ce7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11365/HighFidelity-Beta-PR13614-c664ce7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11365/HighFidelity-Beta-Interface-PR13614-c664ce7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11365/HighFidelity-Beta-PR13614-c664ce7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11365/HighFidelity-Beta-Interface-PR13614-c664ce7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11386/HighFidelity-Beta-PR13614-6577a93.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11386/HighFidelity-Beta-PR13614-6577a93.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11386/HighFidelity-Beta-Interface-PR13614-6577a93.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11440/HighFidelity-Beta-PR13614-19146ef.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11442/HighFidelity-Beta-PR13614-6d239f4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11442/HighFidelity-Beta-PR13614-6d239f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11442/HighFidelity-Beta-Interface-PR13614-6d239f4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11447/HighFidelity-Beta-PR13614-021905b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11447/HighFidelity-Beta-PR13614-021905b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11447/HighFidelity-Beta-Interface-PR13614-021905b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11447/HighFidelity-Beta-PR13614-021905b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11447/HighFidelity-Beta-Interface-PR13614-021905b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11449/HighFidelity-Beta-PR13614-2dd09c1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11449/HighFidelity-Beta-PR13614-2dd09c1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11449/HighFidelity-Beta-Interface-PR13614-2dd09c1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11449/HighFidelity-Beta-PR13614-2dd09c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11449/HighFidelity-Beta-Interface-PR13614-2dd09c1.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @qliacoombs @Qliemillar 
Android app does not crash after following steps.

**Pull request merged**
