### PR TITLE
Improved functionality

### PR DESCRIPTION
**Pull request by NissimHadar**
**Auto-tester changes only.**
image
**Executive Summary**
The auto-tester supports regression testing of the Interface.  The life-cycle of testing is as follows:
1)  Test scripts are written in the tests folder hierarchy.  The results of running a script are a set of snapshots in the folder.
2)  An initial set of snapshots is stored as the _gold standard_.  Running a test will create a second set of snapshots that should be very similar to the stored snapshots.
3)  auto-tester is then used to compare these sets of images.
4)  Options are provided to automatically create a test script that will run all the tests recursively, and to evaluate tests recursively.

A tester follows the following steps:
1)  Create a recursive script at the top of the hierarchy (one click).
2)  Run the recursive script in Interface
3)  Evaluate the results (one click)
4)  If any tests have failed - send the zipped test failure folder to the development team.

**Changes**
An option has been added for running the tests interactively or in a batch mode.  The interactive (default) mode displays each failed test.  The error is now also shown as a diff image:
image

Stores all test results in a single zipped folder, if any test has failed.  This folder contains a sub-folder for each failed test - which includes:
1)  Expected image
2) Actual image
3) Difference image
4) Test failure description

image

An option has been added to delete all old test snapshots (not Expected Images) recursively.
**Usage**
The hifi_tests contains instructions for installing the test environment, as well as developer and tester specific instructions (readme files in markdown format).

**Testing**
A test suite is available at https://highfidelity.testrail.net/index.php?/suites/view/442&group_by=cases:title&group_order=asc

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5897/HighFidelity-Beta-PR12073-22c5890812f926618e644aed0e3306ed32dc2570.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5897/HighFidelity-Beta-PR12073-22c5890812f926618e644aed0e3306ed32dc2570.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5967/app_12073_PR.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5992/app_12073_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5992/HighFidelity-Beta-PR12073-e3916d8e4d02e500aefc2a15f883d239a00da029.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6011/app_12073_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6011/HighFidelity-Beta-PR12073-e3916d8e4d02e500aefc2a15f883d239a00da029.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6011/HighFidelity-Beta-PR12073-e3916d8e4d02e500aefc2a15f883d239a00da029.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Stopped testing, EoD, will resume tomorrow.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6211/app_12073_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6211/HighFidelity-Beta-PR12073-8661d8a20d7ed9ad8c2c364191d04b52d6181499.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6211/HighFidelity-Beta-PR12073-8661d8a20d7ed9ad8c2c364191d04b52d6181499.exe

**Pull request merged**
