### PR TITLE
Remove dead Octree code

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8727/app_12871_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8727/HighFidelity-Beta-PR12871-5376c18449910a64bd6a319bb25899a1f3cea30b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8727/HighFidelity-Beta-Interface-PR12871-5376c18449910a64bd6a319bb25899a1f3cea30b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8735/app_12871_PR_d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8735/HighFidelity-Beta-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8735/HighFidelity-Beta-Interface-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8739/app_12871_PR_d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8739/HighFidelity-Beta-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8739/HighFidelity-Beta-Interface-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8739/HighFidelity-Beta-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8739/HighFidelity-Beta-Interface-PR12871-d7acda399c6a8779d8fdd12f93e5fdebd4b4387c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8887/app_12871_PR_2e8a6e1961eec3f2c240cd28518504a64ef9c4bd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8887/HighFidelity-Beta-PR12871-2e8a6e1961eec3f2c240cd28518504a64ef9c4bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8887/HighFidelity-Beta-Interface-PR12871-2e8a6e1961eec3f2c240cd28518504a64ef9c4bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8887/HighFidelity-Beta-PR12871-2e8a6e1961eec3f2c240cd28518504a64ef9c4bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8887/HighFidelity-Beta-Interface-PR12871-2e8a6e1961eec3f2c240cd28518504a64ef9c4bd.exe

**Comment by birarda** [comment]
There are some comments near the code that's being cleaned up in this PR that we should adjust

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8917/HighFidelity-Beta-PR12871-a8d6a4e0b6996a57ae5128407d16e50b2982ecd9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8917/HighFidelity-Beta-Interface-PR12871-a8d6a4e0b6996a57ae5128407d16e50b2982ecd9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8917/HighFidelity-Beta-PR12871-a8d6a4e0b6996a57ae5128407d16e50b2982ecd9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8917/HighFidelity-Beta-Interface-PR12871-a8d6a4e0b6996a57ae5128407d16e50b2982ecd9.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Entity server tests pass and entities look good.

**Pull request merged**
