### PR TITLE
RC65: Don't hit certain Commerce backend endpoints when wallet isn't yet auth'd

### PR DESCRIPTION
**Pull request by zfox23**
This shouldn't change anything for the user, but prevents BugSnags on the backend.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Log into your HiFi account.
- Have a wallet set up but _do not_ authenticate it for this session.
- You've already purchased an entity item or wearable from the Marketplace (we'll call this Item A below).

### Plan
1. Open the Marketplace. Go to buy Item A again.
    - Verify that you are prompted to enter your passphrase
2. Authenticate your wallet
    - Verify that you see the Checkout screen, and that you see a button that says "BUY IT AGAIN" and a button that says "VIEW IN MY PURCHASES".

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7894/app_12599_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7894/HighFidelity-Beta-PR12599-22f18dbf56598b3644cddd9739e8e54c59856217.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7899/app_12599_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7899/HighFidelity-Beta-PR12599-22f18dbf56598b3644cddd9739e8e54c59856217.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7899/HighFidelity-Beta-PR12599-22f18dbf56598b3644cddd9739e8e54c59856217.dmg

**Comment by qlimnavarro** [comment]
Currently testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
