### PR TITLE
[BUGZ-972] :: changed root to micBar which had the gated property

### PR DESCRIPTION
**Pull request by MiladNazeri**
https://highfidelity.atlassian.net/browse/BUGZ-972

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20643/HighFidelity-Beta-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20643/HighFidelity-Beta-Interface-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20643/HighFidelity-Beta-PR16002-2ea8b9e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20643/HighFidelity-Quest-Beta-PR16002-2ea8b9e.apk)

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20651/HighFidelity-Beta-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20651/HighFidelity-Beta-Interface-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20651/HighFidelity-Beta-PR16002-2ea8b9e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20651/HighFidelity-Quest-Beta-PR16002-2ea8b9e.apk)

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20660/HighFidelity-Beta-PR16002-2ea8b9e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20660/HighFidelity-Beta-Interface-PR16002-2ea8b9e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20660/HighFidelity-Beta-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20660/HighFidelity-Beta-Interface-PR16002-2ea8b9e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20660/HighFidelity-Beta-PR16002-2ea8b9e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20660/HighFidelity-Quest-Beta-PR16002-2ea8b9e.apk)

**Pull request merged**
