### PR TITLE
Fixing the graphics setting for Ambient Occlusion

### PR DESCRIPTION
**Pull request by samcake**
The ambient occlusion setting had disappeared from the developer/graphics dialog box, it s now back.

## TEST PLAN
After enabling developer menu, make sure that the graphics dialog contains the Ambient Occlusion combo box with the 2 choices: enabled or none
And that it works.

It is broken in current master.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2480/HighFidelity-Beta-PR11185-f86f22309b6eede3425303c1d0a1b09a78337994.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2480/HighFidelity-Beta-PR11185-f86f22309b6eede3425303c1d0a1b09a78337994.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
-------- | --------
After enabling developer menu, make sure that the graphics dialog contains the Ambient Occlusion combo box with the 2 choices: enabled or none | Pass
And that it works. | Pass

All good!

##### Intel i5-7200U, 8GB DDR4, Intel 5000 Graphics

**Pull request merged**
