### PR TITLE
BUGZ-1101: Improved diagnostics for avatar-verify failures in mixer

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Jira: https://highfidelity.atlassian.net/browse/BUGZ-1101

Also change client challenge timeout from 5 s to 10 s.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20611/HighFidelity-Beta-PR15996-d9572d9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20611/HighFidelity-Quest-Beta-PR15996-d9572d9.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20611/HighFidelity-Beta-PR15996-d9572d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20611/HighFidelity-Beta-Interface-PR15996-d9572d9.dmg

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20612/HighFidelity-Beta-PR15996-d9572d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20612/HighFidelity-Beta-Interface-PR15996-d9572d9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20612/HighFidelity-Beta-PR15996-d9572d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20612/HighFidelity-Beta-Interface-PR15996-d9572d9.dmg

**Comment by howard-stearns** [comment]
Failed to upload files? Really Jenkins?
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20621/HighFidelity-Beta-PR15996-d9572d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20621/HighFidelity-Beta-Interface-PR15996-d9572d9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20621/HighFidelity-Beta-PR15996-d9572d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20621/HighFidelity-Beta-Interface-PR15996-d9572d9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20621/HighFidelity-Beta-PR15996-d9572d9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20621/HighFidelity-Quest-Beta-PR15996-d9572d9.apk)

**Pull request merged**
