### PR TITLE
Feature/tablet menu relocations

### PR DESCRIPTION
**Pull request by vladest**
AssetsBrowser for Tablet implemented

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by PhilipRosedale** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: b3262e37c12376d059275bf858d592a608273e08 available at: https://gist.github.com/da74aa58f271e51773b13bdc407bd171<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9808-b3262e3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9808-b3262e3.dmg

**Comment by AndrewMeadows** [comment]
Something went wrong with this branch.  My guess would be: a branch was cut from some old commit, changes were made, a merge was done that brought in changes from hifi/master, and then a rebase was done... which recommitted the merged changes with different commit ID's.

As such, this PR is not mergeable.  The real changes should be ported to a fresh branch and a new PR made.

**Comment by AndrewMeadows** [comment]
I checked out this branch to a local repository and looked at the logs.  I see some questionable commits where outside changes were "merged" incorrectly.

@vladest, I'm willing to help you sort through these changes to create a clean pull request.  Let me know if you need help.

**Comment by sethalves** [comment]
these changes were handled in a different PR.

**Pull request closed without merging**
