### PR TITLE
Only track stats for compatible packets

### PR DESCRIPTION
**Pull request by Atlante45**
https://highfidelity.manuscript.com/f/cases/18962/heap-buffer-overflow-in-OctreeSceneStats

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- TBD

[ticket](https://highfidelity.manuscript.com/f/cases/18962/heap-buffer-overflow-in-OctreeSceneStats)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14049/HighFidelity-Beta-PR14226-a7855dc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14049/HighFidelity-Beta-PR14226-a7855dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14049/HighFidelity-Beta-Interface-PR14226-a7855dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14049/HighFidelity-Beta-PR14226-a7855dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14049/HighFidelity-Beta-Interface-PR14226-a7855dc.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
Build this please

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Client and Server work as expected

**Pull request merged**
