### PR TITLE
Fixed bug where lack of 0 as prefix for numbers would throw an error

### PR DESCRIPTION
**Pull request by ericrius1**
Now user can just type .1 instead of 0.1 into a number field in the entity properties panel, and everything will be fine.

### CODE REVIEW

**Comment by ericrius1** [comment]
Test: http://rawgit.com/ericrius1/hifi/editPropsDecimals/examples/edit.js

From https://app.asana.com/0/31759584831097/85739911260109

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1387f5f322e529735006285d537409f57859c214 available at: https://gist.github.com/6836d580049b00f5360f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7008.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7008.dmg

**Comment by seefo** [comment]
Does this affect properties that aren't floats? Looks like any property that isn't a float will throw an error (I'm not sure if all properties are floats).

**Comment by nbq** [comment]
I am testing this one

**Comment by nbq** [comment]
Works fine, went to 0,0,0 and created a box. Changed 0.54 to .50 and it added the 0 to the front and moved the object just fine. PASSED

**Pull request merged**
