### PR TITLE
set grabbable and other checkboxes correctly if userData is blank

### PR DESCRIPTION
**Pull request by sethalves**
- grabbable, triggerable, etc checkboxes are now correct is userData is blank or malformed
- if an entity is near-triggerable, it will not be near-grabbable, even if checked thusly

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- import this json
- use CREATE app to make the entity grabbable and not triggerable
- grab it
- make the entity triggerable and not grabbable
- trigger it (see that it produces a ball)
- make it grabbable and triggerable
- trigger it
- clear userData and see that it is now grabbable and not triggerable
```javascript
{
"Entities": [
             {
             "compoundShapeURL": "http://headache.hungry.com/~seth/hifi/dropper.obj",
             "dimensions": { "x": 1.28, "y": 0.896, "z": 1.28 },
             "modelURL": "http://headache.hungry.com/~seth/hifi/dropper.obj",
             "name": "dropper",
             "queryAACube": { "scale": 2.019806146621704, "x": -1, "y": -1, "z": -1 },
             "rotation": { "w": 1, "x": 0, "y": 0, "z": 0 },
             "script": "http://headache.hungry.com/~seth/hifi/spawn-ball.js",
             "shapeType": "compound",
             "type": "Model",
             "userData": "{\"grabbableKey\":{\"wantsTrigger\":true}}"
             }
             ],
"Version": 73
}
```

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3661/HighFidelity-Beta-PR11470-ce3e5eb1a3a5420dd2a6b18b74d6fbdc021000d8.exe

**Comment by sethalves** [comment]
I hate you, gustavo

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3666/HighFidelity-Beta-PR11470-ce3e5eb1a3a5420dd2a6b18b74d6fbdc021000d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3666/HighFidelity-Beta-PR11470-ce3e5eb1a3a5420dd2a6b18b74d6fbdc021000d8.exe

**Comment by Nex-Pro** [comment]
T E S T I N G this ( at last )

**Comment by Nex-Pro** [comment]
@sethalves  3x startup crashes. Spats submitted.

**Comment by Nex-Pro** [comment]
@sethalves is "I hate you, gustavo" a system command?  If it is I want to use it and if it isn't, it should be.

**Comment by sethalves** [comment]
gustavo is my Milkman Dan.

This PR is a javascript-only change... it can't be responsible for the crashes.  I'll look at bugsplat.

**Comment by anshuman64** [comment]
As a safe measure, please perform this smoke test as well:

Hand Controller Grab Test Plan- Avatar Store
-Go to the avatar store (currently in dev-content)
-Pull an item off the shelf (you should get only one copy of the item and it should be in your hand, even if you don't have rez permissions
-put the item onto the correct joint of your avatar and let go. You should hear an audio confirmation that it has attached. 
-In front of the mirror, adjust the position of the attachment. 
-Grab the attachment and pull it off your body. You should hear an audio confirmation that it has detached
-Try resizing the attachment by pressing both grips. Try this while it's parented and while it's not parented to your avatar.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3674/HighFidelity-Beta-PR11470-eb6c99456d0e272feec2dc1c91e79d927fc617ae.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3676/HighFidelity-Beta-PR11470-eb6c99456d0e272feec2dc1c91e79d927fc617ae.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3676/HighFidelity-Beta-PR11470-eb6c99456d0e272feec2dc1c91e79d927fc617ae.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3682/HighFidelity-Beta-PR11470-eb6c99456d0e272feec2dc1c91e79d927fc617ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3682/HighFidelity-Beta-PR11470-eb6c99456d0e272feec2dc1c91e79d927fc617ae.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Pending
Test | Result
--- | ---
import this json | Pass
use CREATE app to make the entity grabbable and not triggerable | Pass
grab it | Pass
make the entity triggerable and not grabbable | Pass
trigger it (see that it produces a ball) | Pass
make it grabbable and triggerable | Pass
trigger it | Pass
clear userData and see that it is now grabbable and not triggerable | Pass

All good here - though @conklin94122 's post in Slack might have a different test outcome from the test plan in comments.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by sethalves** [comment]
I tested out the avatar/hat store with a build of this branch and it worked.

**Comment by cain-kilgore** [comment]
# Test Passed

**Pull request merged**
