### PR TITLE
switch to HMD preferred audio when mounting the HMD

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Notes:
- If you have an Oculus CV1 - this should automatically switch to the oculus audio when you put the oculus on. 
- otherwise -- it should have no effect.
- test [with this version ](https://raw.githubusercontent.com/ZappoMan/hifi/hmdAudioSwitching/examples/selectAudioDevice.js)of the script

**Comment by hifi-gustavo** [comment]
Build console output for commit: c36a5370e6e8d977d0f3e973e077cbf911c956b3 available at: https://gist.github.com/eb86213c5f00b5c59033b178f043159f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7538.dmg

**Comment by cozza13** [comment]
tested on CV1. QA pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: aee6fc9c8a1b126b70278223e9c5cfb7114b735f available at: https://gist.github.com/eb86213c5f00b5c59033b178f043159f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7538.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7538.dmg

**Pull request merged**
