### PR TITLE
Add removal of temporary files in FBXBaker

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Ensure that you don't have any `assignment-client-#########` folders in your temp directory (`C:\Users\USERNAME\AppData\Local\Temp` on Windows)
    1. If temporary assignment-client directories do exist, remove them.
 1. Upload several FBXs and at least 1 skybox to your asset server
 1. Confirm that they finish baking
 1. Ensure that you still don't have any `assignment-client-#########` folders in your temp directory (`C:\Users\USERNAME\AppData\Local\Temp` on Windows)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3668/HighFidelity-Beta-PR11472-ad6e6c2efb2e99f5dcfd031476dfc5eed5281853.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3668/HighFidelity-Beta-PR11472-ad6e6c2efb2e99f5dcfd031476dfc5eed5281853.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3671/HighFidelity-Beta-PR11472-dcb60f713a85a6e04633296c8bab7b2ee1048c41.exe

**Comment by OmegaHeron** [comment]
Testing Ubuntu 16.04

/tmp Before running stack (Showing only files owned by Stack process)

`No files`

/tmp After uploading one ATP model and seeing successful bake (Again only files owned by Stack process)

`drwxrwx---  2 o2t-hf o2t-hf  4096 Sep 27 13:07 assignment-client-1506532065590582087`
`drwxrwx---  2 o2t-hf o2t-hf  4096 Sep 27 13:07 assignment-client-1506532065590809631`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_sharedmemory_domainserverlocalhttpportf5cca9a2899a37b1c6554f41e9269344fdfedc25`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_sharedmemory_domainserverlocalhttpsportae599c7c684724facee9795f4f36c5acfb8e98de`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_sharedmemory_domainserverlocalport1dc4530fa9250ab79e958138cd565fcd39c89223`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_systemsem_domainserverlocalhttpportf5cca9a2899a37b1c6554f41e9269344fdfedc25`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_systemsem_domainserverlocalhttpsportae599c7c684724facee9795f4f36c5acfb8e98de`
`-rw-r-----  1 o2t-hf o2t-hf     0 Sep 27 13:06 qipc_systemsem_domainserverlocalport1dc4530fa9250ab79e958138cd565fcd39c89223`

/tmp After terminating stack

`drwxrwx---  2 o2t-hf o2t-hf  4096 Sep 27 13:07 assignment-client-1506532065590582087`
`drwxrwx---  2 o2t-hf o2t-hf  4096 Sep 27 13:07 assignment-client-1506532065590809631`


Note /tmp began with no files owned by stack, then stack created its ipc tmp and, when an ATP asset was added, bake tmp files.  When when stack terminated it removed ipc tmp files leaving failed to remove bakes that should have been cleaned after bake operation finished.

A few notes about AC log;

It only outputs making *one* temporary dir yet it makes *two*.
It only attempts to remove one dir (failing to do so).
The directory mentioned as being created seems to hold KTX images and is cleaned of content but fails to remove emptied directory.
Second dir seems to take the re-written FBX and is not emptied of baked FBX.

Log for ATP AC

`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] UploadAssetTask reading a file of  15004 bytes from "e06ee4d6-2096-4bb5-956a-78473a38f7ae"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Hash for uploaded file from "e06ee4d6-2096-4bb5-956a-78473a38f7ae" is: ( "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667" )`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Wrote file "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667" to disk. Upload complete`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Wrote JSON mappings to file at "/opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/map.json"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Set mapping: "/redBlock.fbx" => "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Queuing bake of:  "/redBlock.fbx"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Starting bake for:  "/redBlock.fbx" "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] FBXBaker QUrl("file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667") bake starting`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Made temporary dir  QDir( "/tmp/assignment-client-1506532065590809631" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Origin file path:  "/tmp/assignment-client-1506532065590809631/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [WARNING] [default] [14697] [asset-server] Output path "/tmp/assignment-client-1506532065590582087" already exists. Continuing.`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Local file url:  QUrl("file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667") "file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667" "//opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667" , copying to:  "/tmp/assignment-client-1506532065590809631/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] file path:  /tmp/assignment-client-1506532065590809631/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667 false`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.model-baking] [14697] [asset-server] Parsing QUrl("file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667")`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.modelformat] [14697] [asset-server] fileVersion: 7400`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.modelformat] [14697] [asset-server]  fbx material Name: "redBlock"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.model-baking] [14697] [asset-server] Exported QUrl("file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667") with re-written paths to "/tmp/assignment-client-1506532065590582087/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667.baked.fbx"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.model-baking] [14697] [asset-server] Finished baking, emitting finsihed QUrl("file:////opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/files/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667")`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Finished baking:  "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667" "/redBlock.fbx" QVector("/tmp/assignment-client-1506532065590582087/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667.baked.fbx")`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Completing bake for  "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] File path:  "/tmp/assignment-client-1506532065590582087/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667.baked.fbx"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Relative file path is:  "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667.baked.fbx"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Wrote JSON mappings to file at "/opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/map.json"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Set mapping: "/.baked/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667/asset.fbx" => "6225d2fca9e959f6e7ac7d91aa0616c1258d3d016cebd3cb2a33900634a95a36"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [default] [14697] [asset-server] Added "/.baked/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667/asset.fbx" for bake file "6225d2fca9e959f6e7ac7d91aa0616c1258d3d016cebd3cb2a33900634a95a36" from bake of "faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Wrote JSON mappings to file at "/opt/o2t-hifi/content/.local/share/High Fidelity - PR11472/assignment-client/assets/map.json"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [DEBUG] [hifi.asset-server] [14697] [asset-server] Set mapping: "/.baked/faf2b98eba4df360de13f9d8023f66409cf1261ac61a05b497c6d50575dc4667/meta.json" => "a6a22260cc93c2e5412ce9d34e70e98a02ebc918463ed99df2756780fd87236c"`
`Sep 27 13:07:45 assignment-client[14697]: [09/27 13:07:45] [WARNING] [hifi.model-baking] [14697] [asset-server] Failed to remove temporary directory: QDir( "/tmp/assignment-client-1506532065590809631" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )`

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3695/HighFidelity-Beta-PR11472-ed845c61047239d6cbf670bfcf96ddccf08a2775.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3695/HighFidelity-Beta-PR11472-ed845c61047239d6cbf670bfcf96ddccf08a2775.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Ensure that you don't have any assignment-client-######### folders in your temp directory (C:\Users\USERNAME\AppData\Local\Temp on Windows) | Pass
If temporary assignment-client directories do exist, remove them. | Pass
Upload several FBXs and at least 1 skybox to your asset server | Pass
Confirm that they finish baking | Pass
Ensure that you still don't have any assignment-client-######### folders in your temp directory (C:\Users\USERNAME\AppData\Local\Temp on Windows) | Pass

All looked good to me, however I did notice some funky activity with the Use baked checkbox, see gif below. Nothing to do with this PR, just worth noting.

47315a2b-1a29-4cbe-bc97-59ab96c74a9e

**Comment by huffman** [comment]
test this please

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3713/HighFidelity-Beta-PR11472-5d84b3c9f4b161c551365fa99505bedfcea630a7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3713/HighFidelity-Beta-PR11472-5d84b3c9f4b161c551365fa99505bedfcea630a7.dmg

**Comment by marko8904** [comment]
build this please

**Comment by huffman** [comment]
test this please

**Comment by OmegaHeron** [comment]
I'll test this again on Linux in a bit.  Compiling now.

**Comment by huffman** [comment]
Thanks @OmegaHeron - I tested it on Ubuntu 16.04

**Comment by huffman** [comment]
@cain-kilgore Would you be able to retest this on Windows?

**Comment by cain-kilgore** [comment]
@huffman: Can do!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3740/HighFidelity-Beta-PR11472-addac955c19fd78a4282d9b263d567d4035143e2.dmg

**Comment by marko8904** [comment]
build this please

**Comment by OmegaHeron** [comment]
QA Pass Ubuntu 16.04.

**Comment by OmegaHeron** [comment]
Pass for Ubuntu is with caveat that it still leaves a tmp dir on certain bake operations where bake ultimately fails.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Ensure that you don't have any assignment-client-######### folders in your temp directory (C:\Users\USERNAME\AppData\Local\Temp on Windows) | Pass
If temporary assignment-client directories do exist, remove them. | Pass
Upload several FBXs and at least 1 skybox to your asset server | Pass
Confirm that they finish baking | Pass
Ensure that you still don't have any assignment-client-######### folders in your temp directory (C:\Users\USERNAME\AppData\Local\Temp on Windows) | Pass

The same issue was persisting with the tickbox going a little funky. But functionality was working.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3741/HighFidelity-Beta-PR11472-addac955c19fd78a4282d9b263d567d4035143e2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3741/HighFidelity-Beta-PR11472-addac955c19fd78a4282d9b263d567d4035143e2.exe

**Comment by ZappoMan** [comment]
@huffman - looks like this needs to be rebased.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3915/HighFidelity-Beta-PR11472-f0c9badbd6a4912a1a4340db8945b5d39349b7d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3915/HighFidelity-Beta-PR11472-f0c9badbd6a4912a1a4340db8945b5d39349b7d6.exe

**Pull request merged**
