### PR TITLE
remove AssetResourceRequest timeout, output occasional progress to log

### PR DESCRIPTION
**Pull request by birarda**
- fixes a bug introduced in #8730 which caused ATP downloads to timeout frequently with multiple concurrent ATP downloads

### CODE REVIEW

**Comment by birarda** [comment]
**Test Plan**

Test a master Sandbox on a long route (> 100ms RTT). You should have trouble downloading ATP assets from the Sandbox since they timeout frequently and are continually re-attempted.

On this PR, you should have few to no ATP timeouts and ATP assets should successfully download from the Sandbox in this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d49711deea9fde6647acfc9020365e8621d1970 available at: https://gist.github.com/66deb0091af145fcea45243db973eaa7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-2d49711.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-2d49711.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

Tested remote domains with RTT pings of (avg) 50, 70 and 110 - all ATP assets loaded properly (from a clean cache as in clean via deleting cache manually from disk).

Now - I ran into a problem I saw before that's somewhat opposite of what this is described to fix (long RTT times) in trying to load standard home scene from LAN machine (old traditional standard home scene - not new light version).  Showing a ping time of 0 to 1 I see Interface on Windows 10 request an ATP asset - it shows in Interface log (a small block of a very large log);

[10/11 11:23:41] [DEBUG] [hifi.networking] Starting request for: atp:/tiltMaze/newmaze_tex-3.obj
[10/11 11:23:41] [DEBUG] [hifi.networking] Server unavailable for QUrl(atp:/pingPongGun/Pingpong-Gun-New.obj) - retrying asset load - attempt 7  of  8
[10/11 11:23:41] [DEBUG] [hifi.networking] Starting request for: atp:/pingPongGun/Pingpong-Gun-New.obj
[10/11 11:23:41] [DEBUG] [default] Got mapping for: "/tiltMaze/newmaze_tex-3.obj" => "6a0f609090ac368fe03895b0d499788724d289f62b74314977b1a6732cd52d5f"
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] "atp:6a0f609090ac368fe03895b0d499788724d289f62b74314977b1a6732cd52d5f" not in disk cache
[10/11 11:23:41] [DEBUG] [default] Got mapping for: "/pingPongGun/Pingpong-Gun-New.obj" => "af425c7a006d95b6bf473910649f196639b3083a16e522811923e2c266265654"
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] "atp:af425c7a006d95b6bf473910649f196639b3083a16e522811923e2c266265654" not in disk cache
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] Got size of  "6a0f609090ac368fe03895b0d499788724d289f62b74314977b1a6732cd52d5f"  :  112648  bytes
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] Requesting data from 0 to 112648 of "6a0f609090ac368fe03895b0d499788724d289f62b74314977b1a6732cd52d5f" from asset-server.
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] Got reply for asset:  "6a0f609090ac368fe03895b0d499788724d289f62b74314977b1a6732cd52d5f"
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] Got size of  "af425c7a006d95b6bf473910649f196639b3083a16e522811923e2c266265654"  :  406265  bytes
[10/11 11:23:41] [DEBUG] [hifi.networking.asset_client] Requesting data from 0 to 406265 of "af425c7a006d95b6bf473910649f196639b3083a16e522811923e2c266265654" from asset-server.
[10/11 11:23:42] [DEBUG] [hifi.interface] Physics disabled until entity loads:  QUuid("{7090848c-bb60-48e9-8805-405cce823631}") "home_model_homeset"
[10/11 11:23:42] [DEBUG] [hifi.audio] AudioRingBuffer::writeData has overflown the buffer. Overwriting old data.
[10/11 11:23:43] [DEBUG] [hifi.networking.asset_client] Got reply for asset:  "af425c7a006d95b6bf473910649f196639b3083a16e522811923e2c266265654"
[10/11 11:23:43] [WARNING] [default] Asset request timed out:  QUrl("atp:/pingPongGun/Pingpong-Gun-New.obj")
[10/11 11:23:43] [WARNING] [default] Asset request timed out:  QUrl("atp:/tiltMaze/newmaze_tex-3.obj")

Stack log shows a corresponding begin asset send for each.

If you leave scene running long enough if eventually, painfully slowly, loads items.

So - take a look at loading an ATP intense via 2 machines on same LAN, ideally Client = Windows 10 and server = Ubuntu 16.04 running 5467 stack.

**Comment by OmegaHeron** [comment]
I'm digging more with the Interface<-LAN->Stack issue - it seems I have to revert to Master 5445 on Stack and Interface to see what's been traditional normal behavior loading an ATP intense scene like standard home.  5445 Is last master push before PR8730 came into play.

What, I think, this is exposing is something I've long suspected -- ATP requests often fail to serve leading to an intense flurry of request-fail-retry events until scene loads explaining why LAN traffic looks much higher than one would think it should for content loaded (and time it takes to load is > than expected).  With 8730 adding an increasing delay per fail it makes it more apparent ATP is failing to fetch and leads to scene never loading (or virtually never since you give up).

It's interesting to do this....

Starting from a clean cache - open Interface - expose log display window then holding rotate key right arrow or D watch Interface log **and** in an SSH session watch output from assignment-client.  If you can do this it seems a very odd comparison to what Interface is doing versus what AC is doing.  Once scene loads - do same without emptying cache.

**Comment by howard-stearns** [comment]
FWIW, there is a test script that does something like this in a repeatable way. I ran it to see if this fixes https://highfidelity.fogbugz.com/f/cases/1818/loading-assets-sometimes-freezes - (see instructions in that ticket).

While this PR does not give me the failed-to-load problem of that ticket, neither does dev-download build. However, both do give crashes during asset loading. (dumps submitted.) I can't tell if master or this pr crashes during load any more than the other.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 826c2f1a9febf132c8dabcced0c67ce81e2ac860 available at: https://gist.github.com/66deb0091af145fcea45243db973eaa7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-826c2f1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-826c2f1.dmg

**Comment by birarda** [comment]
Crash reported by @howard-stearns is the same that @Atlante45 is tracking with #8778.

**Comment by OmegaHeron** [comment]
QA Pass

Tested this PR Interface (Windows 10) against Master 5469 Stack on Ubuntu Linux 16.04.1 loading home scene from empty cache works, loading once cached works.  Also tested dev-demo and dev-playa along with my other standard tests - all work as expected.  This marks first build I could successfully load home scene from an empty cache over LAN.

It should be understood a issue with why it's rather unexpectedly slow loading over LAN is being investigated separately to this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 504e92607a71736f36edf48b3c3825eb727fbf85 available at: https://gist.github.com/66deb0091af145fcea45243db973eaa7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-504e926.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8775-504e926.dmg

**Comment by birarda** [comment]
Had @OmegaHeron re-test this after the strategy change - he confirmed that with those changes, while avoiding the slow localhost download bug that I am separately looking into, gave him the correct experience. Marking this QA Approved and merging.

**Pull request merged**
