### PR TITLE
Adding separate sampler objects

### PR DESCRIPTION
**Pull request by jherico**
Separate sampler information from texture information, allowing easier creation of texture handles for bindless textures.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4de219b948e638008ba0fdda592945a848e44b35 available at: https://gist.github.com/19c936368628d125f7d48886038ffe03<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9986-4de219b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9986-4de219b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7326d6ebb3e2021793da4b6f778e861f52ebc7a available at: https://gist.github.com/19c936368628d125f7d48886038ffe03<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9986-b7326d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9986-b7326d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/563/HighFidelity-Beta-PR9986-80d7864b8da451f4e54d6a5d3cfaafe8cd83f192.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/563/HighFidelity-Beta-PR9986-80d7864b8da451f4e54d6a5d3cfaafe8cd83f192.dmg

**Comment by ZappoMan** [comment]
This PR has been marked DNM for over 3 months. Closing until developer has determined new plan.

**Pull request closed without merging**
