### PR TITLE
DNM Tutorial update

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Install build and download content set
 1. Make sure you can go through the tutorial
 1. Go to the builder grid and throw things around on the platform, making sure collisions are working as expected

**Comment by hifi-gustavo** [comment]
Build console output for commit: f1709c55b5d33994d6788524776e4ebeb608ee34 available at: https://gist.github.com/3000c96f347a3a1f4544d17a343d7a9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-f1709c5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-f1709c5.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f1709c55b5d33994d6788524776e4ebeb608ee34 available at: https://gist.github.com/3000c96f347a3a1f4544d17a343d7a9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-f1709c5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-f1709c5.dmg

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
### PASS

Threw a bunch of crates etc. All seems fine.

Tutorial works as per normal.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d6778e9cdd722ed1bef438179abb0f9014706a3 available at: https://gist.github.com/3000c96f347a3a1f4544d17a343d7a9c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-3d6778e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10342-3d6778e.dmg

**Pull request merged**
