### PR TITLE
BUGZ-131: Reduce spam from watchdog thread

### PR DESCRIPTION
**Pull request by jherico**
[BUGZ-131](https://highfidelity.atlassian.net/browse/BUGZ-131):  Because of changes in our update rate (the rate at which we call `Application::idle`) in the new design, there's been an uptick in logspam from the watchdog thread, which will warn whenever the average time between calls to the timer increases.  When the application goes from the foreground to the background you end up with a spate of messages as the average frequency slowly changes.  

The problem here is not that `Application::idle` tends to change rate where it didn't before, but rather that the watchdog update functionality is tied to `Application::idle` at all.  The watchdog update merely needs to ensure that the main thread isn't deadlocked, and to do so it can execute in response to it's own timer that will fire at a fixed rate regardless of the `idle` frequency.  This PR implements that change.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19337/HighFidelity-Beta-PR15539-0f8ddae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19337/HighFidelity-Beta-Interface-PR15539-0f8ddae.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19337/HighFidelity-Beta-PR15539-0f8ddae.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19337/HighFidelity-Quest-Beta-PR15539-0f8ddae.apk)

**Comment by jherico** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19343/HighFidelity-Beta-PR15539-0f8ddae.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19343/HighFidelity-Quest-Beta-PR15539-0f8ddae.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19343/HighFidelity-Beta-PR15539-0f8ddae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19343/HighFidelity-Beta-Interface-PR15539-0f8ddae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19343/HighFidelity-Beta-PR15539-0f8ddae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19343/HighFidelity-Beta-Interface-PR15539-0f8ddae.exe

**Pull request merged**
