### PR TITLE
MS17041: Fix for require fail when the same script loaded simultaneously from another entity script

### PR DESCRIPTION
**Pull request by thoys**
Fixes https://highfidelity.manuscript.com/f/cases/17041/require-fails-if-another-script-already-required-the-library-and-the-library-hasn-t-yet-downloaded

## QA Test Plan

1. When installing this PR, be sure to select the clean install. Don't copy. And when you re-run this PR always be sure to remove your cache folders first.
2. Go to a domain with rez permissions.
3. Check menu option `Settings -> Developer Menu`
4. Check menu option `Developer -> Verbose Logging`
5. Open the Log  (CTRL + SHIFT + L)
6. Edit -> Import Entities from URL: https://hifi-require-bug.glitch.me/require-test/require-test.json
7. Verify that the following lines show up in the log
    ```
    [DEBUG] [hifi.scriptengine.script] [about:Entities 2] QQQQ something: 0
    [DEBUG] [hifi.scriptengine.script] [about:Entities 2] QQQQ something: 1
    [DEBUG] [hifi.scriptengine.script] [about:Entities 2] QQQQ something: 2
    ```
    **Note: they could be in a different order or `[about:Entities 2]` may contain another number, which is fine**
8. Smoke test some existing entity scripts.

> special thanks to @humbletim for offering this patch

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11633/HighFidelity-Beta-PR13709-ba8d445.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11633/HighFidelity-Beta-PR13709-ba8d445.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11633/HighFidelity-Beta-Interface-PR13709-ba8d445.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11713/HighFidelity-Beta-PR13709-ba8d445.apk

**Comment by qlilaseguinolaza** [comment]
Desktop logs

[hifi-log_2018-07-31_08.36.21.txt](https://github.com/highfidelity/hifi/files/2245791/hifi-log_2018-07-31_08.36.21.txt)

**Comment by qlilaseguinolaza** [comment]
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2245793/hifi-log.txt)

**Comment by qlilaseguinolaza** [comment]
Fail @conklin94122

Step 5: Im not seeing the the lines specified in the log on Mac or Desktop

[Mac.txt](https://github.com/highfidelity/hifi/files/2245786/Mac.txt)
Win Desktop log: 
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2245806/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11713/HighFidelity-Beta-PR13709-ba8d445.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11713/HighFidelity-Beta-Interface-PR13709-ba8d445.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11713/HighFidelity-Beta-PR13709-ba8d445.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11713/HighFidelity-Beta-Interface-PR13709-ba8d445.exe

**Comment by qlilaseguinolaza** [comment]
Fail @conklin94122

Step 5: Im not seeing the the lines specified in the log on Mac or Desktop

[Mac.txt](https://github.com/highfidelity/hifi/files/2245786/Mac.txt)
Win Desktop log:
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2246083/hifi-log.txt)

**Comment by thoys** [comment]
It turns out that Verbose Logging had to be enabled. Updated the testing plan, thanks @qlilaseguinolaza

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Lines show up in the log as specified in the test plan

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11747/HighFidelity-Beta-PR13709-003e826.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11747/HighFidelity-Beta-PR13709-003e826.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11747/HighFidelity-Beta-Interface-PR13709-003e826.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11747/HighFidelity-Beta-PR13709-003e826.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11747/HighFidelity-Beta-Interface-PR13709-003e826.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Lines appeared in log.

**Pull request merged**
