### PR TITLE
Add logging of signal slot exceptions in ScriptEngine

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f60cd09b451b76a5aab9e637ab0a2fa649ac8f99 available at: https://gist.github.com/c2908ed48262fade6b54<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6759.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6759.dmg

**Comment by ZappoMan** [comment]
This looks great... can you include a sample script that demonstrates this?

**Comment by huffman** [comment]
@ZappoMan Sure, you could try this: https://gist.githubusercontent.com/huffman/c0f1e5cdabf62106cb22/raw/013cbc00bc7a55cac42dadb01482353a3fc755aa/testSignalException.js

On release builds you won't see the first exception when pressing a key (`throw("Exception in keyPressEvent 1");`)

We do check for exceptions in ScriptEngine, but this will only capture the _last_ exception, yet there are multiple exceptions that could be thrown prior.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 810da77abe4866bb57512d4d70c8e633c99dd921 available at: https://gist.github.com/c2908ed48262fade6b54<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6759.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6759.dmg

**Pull request merged**
