### PR TITLE
Some fixes for QML surfaces

### PR DESCRIPTION
**Pull request by jherico**
This attempts to address some more issues in QML surfaces.  
* Correctly destroy the Qml scene graph when destroying a surface.  Due to a misunderstanding of the object lifetime, the previous PR #12969 didn't delete the `_rootItem` which held the root of the scene graph nodes.  This lead to much bad behavior, since objects in the scene graph might process events after the QML context and engine had been destroyed, leading to crashes. 
* Fix an improper cast caused by connecting a QML object to a signal in `OffscreenQmlSurface` and not always disconnecting from it before destruction.  The connected object would be destroyed in destructor of the base class of `OffscreenQmlSurface`.  This meant that by the time of destruction, the surface was no longer of the type `OffscreenQmlSurface` since it's destructor had already executed.
* A memory leak caused by `new UrlHandler` with no corresponding accommodation for releasing the memory.  This is fixed by adding the QML context as a parent.
* Reverting a modification to the renderable web entity which attempted to change the URL to an empty string immediately before destruction.  
* Restore the WebEntity behavior of calling `stop` on the WebEngineView before destruction.  This was apparently lost at some point because the invokation looked for a QObject by name that would never exist.  

## Testing

Same testing process as listed on #12969

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9258/HighFidelity-Beta-PR13027-f2172d84a00d8add357029821c45f4d74d15d412.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9258/HighFidelity-Beta-Interface-PR13027-f2172d84a00d8add357029821c45f4d74d15d412.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9287/app_13027_PR_5f8149fd6873ca6ad1163927826283f1809a10c8.apk

**Comment by samcake** [comment]
This is built against master, so this pr can only go in rc68

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9287/HighFidelity-Beta-PR13027-5f8149fd6873ca6ad1163927826283f1809a10c8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9287/HighFidelity-Beta-Interface-PR13027-5f8149fd6873ca6ad1163927826283f1809a10c8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9287/HighFidelity-Beta-PR13027-5f8149fd6873ca6ad1163927826283f1809a10c8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9287/HighFidelity-Beta-Interface-PR13027-5f8149fd6873ca6ad1163927826283f1809a10c8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9299/HighFidelity-Beta-PR13027-575520fe3063f3d6deac5e8266b3e886ac25d88a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9299/HighFidelity-Beta-Interface-PR13027-575520fe3063f3d6deac5e8266b3e886ac25d88a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9299/HighFidelity-Beta-PR13027-575520fe3063f3d6deac5e8266b3e886ac25d88a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9299/HighFidelity-Beta-Interface-PR13027-575520fe3063f3d6deac5e8266b3e886ac25d88a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9305/app_13027_PR_405077d441353b184fcc0c8af69d78f7342d908f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9305/HighFidelity-Beta-PR13027-405077d441353b184fcc0c8af69d78f7342d908f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9305/HighFidelity-Beta-Interface-PR13027-405077d441353b184fcc0c8af69d78f7342d908f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9305/HighFidelity-Beta-PR13027-405077d441353b184fcc0c8af69d78f7342d908f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9305/HighFidelity-Beta-Interface-PR13027-405077d441353b184fcc0c8af69d78f7342d908f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9311/app_13027_PR_8e42bb8c877e693cdf29bdcb2e206316a2bc8a85.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9311/HighFidelity-Beta-PR13027-8e42bb8c877e693cdf29bdcb2e206316a2bc8a85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9311/HighFidelity-Beta-Interface-PR13027-8e42bb8c877e693cdf29bdcb2e206316a2bc8a85.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9311/HighFidelity-Beta-PR13027-8e42bb8c877e693cdf29bdcb2e206316a2bc8a85.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9311/HighFidelity-Beta-Interface-PR13027-8e42bb8c877e693cdf29bdcb2e206316a2bc8a85.exe

**Comment by samcake** [comment]
We need a test plan for this

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tested based on defects listed in the PR linked. Web entities are working as expected.

I believe my previous pass comment may have been nuked.

**Pull request merged**
