### PR TITLE
Head tracking bug fix for vive HMD users

### PR DESCRIPTION
**Pull request by hyperlogic**
Inadvertently introduced in PR #11752.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/9700/Vive-Avatar-head-no-longer-tracks-HMD

**Comment by hyperlogic** [comment]
QA Test plan:
https://highfidelity.testrail.net/index.php?/cases/view/2933&group_by=cases:section_id&group_order=asc&group_id=574

**Comment by Nex-Pro** [comment]
Awaiting win build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5212/HighFidelity-Beta-PR11888-8364700b7aa8a7b8311c04235c6570d4610f2771.exe

**Comment by Nex-Pro** [comment]
In progress

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5212/HighFidelity-Beta-PR11888-8364700b7aa8a7b8311c04235c6570d4610f2771.dmg

**Comment by Nex-Pro** [comment]
### PASS

Link for the testrail case is incorrect so I used what I believe to be the correct test. ( Matches dialog changes ) 

Test rail result here.

https://highfidelity.testrail.net/index.php?/tests/view/18141&group_by=cases:title&group_order=desc&group_id=-1

**Comment by hyperlogic** [comment]
@Nex-Pro Yeah, sorry I linked to the wrong test, I updated the comment above.

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/9690/Vive-When-the-interface-launches-VR-is-in-broken-third-person-until-Use-Vive-devices-in-desktop-mode-is-toggled

**Pull request merged**
