### PR TITLE
update to @problem's new interface icon

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
Hold on this, still confirming the converted icns files work

**Comment by hifi-gustavo** [comment]
Build console output for commit: ae87dac5230f9778305ab7ccc853e9f55d5ca276 available at: https://gist.github.com/06c7e179bb425b096c6f

**Comment by birarda** [comment]
Should be good - @murillodigital do you need to change the windows installer creator so it grabs this ico or you can do post-merge?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c7450239406e7cc680622292a37a7c56ead4bf5 available at: https://gist.github.com/d7aa9e51cd3b90762d04

**Comment by murillodigital** [comment]
Go ahead and merge - Windows will not show until I indeed change the script but I can do that at any time post merge. @birarda

**Comment by hifi-gustavo** [comment]
Build console output for commit: f78f6ab4cf9c6118217a4a99ae565d236620ba90 available at: https://gist.github.com/bfba072c760807101c9e

**Pull request merged**
