### PR TITLE
Add getter for SteamVR's buildID to SteamClient

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test plan:
- run interface on a machine with Steam installed... and notice in the log file the SteamVR version is printed to the log

**Comment by hifi-gustavo** [comment]
Build console output for commit: f26ddc6f8b447f1b5b97a2ef75019097c75e54ca available at: https://gist.github.com/29b65d5e02a950041a97074089275715<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8923-f26ddc6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8923-f26ddc6.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f26ddc6f8b447f1b5b97a2ef75019097c75e54ca available at: https://gist.github.com/29b65d5e02a950041a97074089275715<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8923-f26ddc6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8923-f26ddc6.dmg

**Pull request merged**
