### PR TITLE
disable user activity logger in DS/AC/ac-client

### PR DESCRIPTION
**Pull request by birarda**
- stop the ac-client from sending went_to activities

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1166/HighFidelity-Beta-PR10843-86eb5b14ca977fe236d34f4d5a6df73c8a805b48.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1166/HighFidelity-Beta-PR10843-86eb5b14ca977fe236d34f4d5a6df73c8a805b48.exe

**Comment by ZappoMan** [comment]
What's the test plan?

**Comment by ZappoMan** [comment]
@birarda @Atlante45 - what's the test plan for this? Is this QA Ready?

**Comment by sethalves** [comment]
I think marco is going to be QA on this, when he gets time.

**Comment by birarda** [comment]
#### Test Plan (for @marko8904)

Deploy the ac-client using this branch. Confirm that it does not send any user activities and opens no user session.

**Comment by marko8904** [comment]
building and testing now, will report on the findings

**Comment by marko8904** [comment]
@birarda when I run ac-client I get "Setting::Interface::init() for key "UserActivityLoggerDisabled" - Manager not yet created. Settings persistence disabled." Otherwise it operates as normal. These messages interfere with ac-clients normal output, though.

**Comment by birarda** [comment]
@marko8904 there isn't a great way around that without creating a settings manager, which would be overkill since we do not need the ac-client storing settings. Does that output get in your way?

**Comment by marko8904** [comment]
@birarda if there's no obvious way to do this then I can filter it out from the output. Thanks!

**Comment by birarda** [comment]
@marko8904 let me try something different here

**Comment by YuppyPlays** [comment]
Will test once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1386/HighFidelity-Beta-PR10843-916f57772bc1767168127756960f81d9a5573003.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1386/HighFidelity-Beta-PR10843-916f57772bc1767168127756960f81d9a5573003.dmg

**Comment by marko8904** [comment]
I don't see ac-client producing sessions any longer. The fix has solved that problem.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete.

Dev has been messaged and will confirm if pass/fail :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1394/HighFidelity-Beta-PR10843-bdcdff3dbc34aadaffdc75605f95f31ffd4d8516.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1394/HighFidelity-Beta-PR10843-bdcdff3dbc34aadaffdc75605f95f31ffd4d8516.exe

**Comment by birarda** [comment]
@YuppyPlays we slightly changed the behavior here, so this will need a re-test. 

Can you remove your `%APPDATA%/Romaing/High Fidelity - #10843/` folder and follow the test plan again?

**Comment by YuppyPlays** [comment]
@birarda No worries, testing now :)

**Comment by YuppyPlays** [comment]
Testing complete.

Awaiting your conclusion :) Hope all works!

**Pull request merged**
