### PR TITLE
Implement MS20187: Add trash can feature to Inventory

### PR DESCRIPTION
**Pull request by zfox23**
Implements [MS20187](https://highfidelity.manuscript.com/f/cases/20187/Set-up-a-trash-can-for-user-to-give-away-unwanted-items).

DNM til this is approved.

NOTE that the user `TrashCan` has to be set up (and probably greeter-managed) on the Metaverse containing this trash can.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15885/HighFidelity-Beta-PR14568-d74f7eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15885/HighFidelity-Beta-Interface-PR14568-d74f7eb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15887/HighFidelity-Beta-PR14568-dff7804.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15887/HighFidelity-Beta-Interface-PR14568-dff7804.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15887/HighFidelity-Beta-PR14568-dff7804.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15887/HighFidelity-Beta-Interface-PR14568-dff7804.exe

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15892/HighFidelity-Beta-PR14568-dff7804.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15892/HighFidelity-Beta-PR14568-dff7804.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15892/HighFidelity-Beta-Interface-PR14568-dff7804.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15892/HighFidelity-Beta-PR14568-dff7804.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15892/HighFidelity-Beta-Interface-PR14568-dff7804.exe

**Comment by rickcarr044** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16044/HighFidelity-Beta-PR14568-dff7804.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16044/HighFidelity-Beta-PR14568-dff7804.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16044/HighFidelity-Beta-Interface-PR14568-dff7804.dmg

**Comment by rickcarr044** [comment]
Currently testing PR14568

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16052/HighFidelity-Beta-PR14568-f407042.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16052/HighFidelity-Beta-Interface-PR14568-f407042.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16052/HighFidelity-Beta-PR14568-f407042.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16052/HighFidelity-Beta-Interface-PR14568-f407042.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16061/HighFidelity-Beta-PR14568-116edcc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16061/HighFidelity-Beta-PR14568-116edcc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16061/HighFidelity-Beta-Interface-PR14568-116edcc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16061/HighFidelity-Beta-PR14568-116edcc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16061/HighFidelity-Beta-Interface-PR14568-116edcc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16079/HighFidelity-Beta-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16079/HighFidelity-Beta-Interface-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16079/HighFidelity-Beta-PR14568-b0ce3a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16079/HighFidelity-Beta-Interface-PR14568-b0ce3a5.exe

**Comment by rickcarr044** [comment]
Retesting PR14568 with new improvement
Case 20385

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16084/HighFidelity-Beta-PR14568-b0ce3a5.apk

**Comment by shanzzam** [comment]
Merge this when complete!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16084/HighFidelity-Beta-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16084/HighFidelity-Beta-Interface-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16084/HighFidelity-Beta-PR14568-b0ce3a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16084/HighFidelity-Beta-Interface-PR14568-b0ce3a5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16092/HighFidelity-Beta-PR14568-b0ce3a5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16092/HighFidelity-Beta-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16092/HighFidelity-Beta-Interface-PR14568-b0ce3a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16092/HighFidelity-Beta-PR14568-b0ce3a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16092/HighFidelity-Beta-Interface-PR14568-b0ce3a5.exe

**Pull request merged**
