### PR TITLE
Fix import of JSON with parent-child relationships

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Attached zip file contains JSON containing parent-child-child relationships plus screen shot of what imported entities should look like.

Test: Import JSON and verify that the entities are positioned as expected. (Previously, some were positioned significantly out of place.)

[QA.zip](https://github.com/highfidelity/hifi/files/1087051/QA.zip)

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/887/HighFidelity-Beta-PR10754-513e0cd2327f02c561e1dc190299d0b2a804ec67.exe

**Comment by CainFoool** [comment]
# Test Passed 

Works as expected when importing the json.

interface_2017-06-20_06-12-14

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/890/HighFidelity-Beta-PR10754-513e0cd2327f02c561e1dc190299d0b2a804ec67.exe

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/891/HighFidelity-Beta-PR10754-513e0cd2327f02c561e1dc190299d0b2a804ec67.exe

**Comment by CainFoool** [comment]
@cozza13: This build seems to be failing quite a bit. Third times the charm?

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/893/HighFidelity-Beta-PR10754-513e0cd2327f02c561e1dc190299d0b2a804ec67.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/893/HighFidelity-Beta-PR10754-513e0cd2327f02c561e1dc190299d0b2a804ec67.dmg

**Pull request merged**
