### PR TITLE
Fix crash with BandwidthRecorder

### PR DESCRIPTION
**Pull request by Atlante45**
- Fixes a crash on current access to the BandwidthRecorders' storage.

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- TBD

[ticket](https://highfidelity.manuscript.com/f/cases/edit/19208/Per-node-bandwidth-tracking-crash-on-servers-with-high-concurrency)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13713/HighFidelity-Beta-PR14163-3eb7c80.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13713/HighFidelity-Beta-PR14163-3eb7c80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13713/HighFidelity-Beta-Interface-PR14163-3eb7c80.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13713/HighFidelity-Beta-PR14163-3eb7c80.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13713/HighFidelity-Beta-Interface-PR14163-3eb7c80.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13956/HighFidelity-Beta-PR14163-3eb7c80.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13956/HighFidelity-Beta-PR14163-3eb7c80.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13956/HighFidelity-Beta-Interface-PR14163-3eb7c80.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13956/HighFidelity-Beta-PR14163-3eb7c80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13956/HighFidelity-Beta-Interface-PR14163-3eb7c80.dmg

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by Atlante45** [comment]
@conklin94122 I linked the ticket in the first comment:
https://highfidelity.manuscript.com/f/cases/edit/19208/Per-node-bandwidth-tracking-crash-on-servers-with-high-concurrency

**Pull request merged**
