### PR TITLE
Fix for one-frame lag in the tablet stylus.

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0962a15a06dfdb68fbcb2201da4d98b486b45c02 available at: https://gist.github.com/003553eb45950d6db63f46eefaa580ca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9557-0962a15.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9557-0962a15.dmg

**Comment by hyperlogic** [comment]
I found a potential crash when deleting model entities that could be caused by this.  Looking into it.

**Comment by hyperlogic** [comment]
False alarm

**Comment by hyperlogic** [comment]
I'm going to rework this a bit.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f75668923c0632929c630cc1955764f75819650 available at: https://gist.github.com/003553eb45950d6db63f46eefaa580ca<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9557-0f75668.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9557-0f75668.dmg

**Pull request merged**
