### PR TITLE
fix 'the drop down does not shows the wearable'

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Launch avatarapp
2. Select avatar with wearables. 
3. Go to adjust wearables
4. Ensure wearables combobox is filled with items and current item is visible

https://highfidelity.manuscript.com/f/cases/edit/16826/AvatarApp-and-Avatar-Wearable-Issues

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11395/HighFidelity-Beta-PR13631-fe96ad2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11395/HighFidelity-Beta-PR13631-fe96ad2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11395/HighFidelity-Beta-Interface-PR13631-fe96ad2.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @qliacoombs @Qliemillar 
Avatars still have wearables and are able to modify them

**Pull request merged**
