### PR TITLE
Updated and Revised BUILD_LINUX.md - Includes Ubuntu 18.04 steps

### PR DESCRIPTION
**Pull request by FlameSoulis**
While working on compiling the server code (domain-server and assignment-client), I ran into a few noticeable concerns with the instructions:

- A glaring typo on the cmake step
- Missing dependencies
- Outdated versioning (change from build numbers to version numbers on tags)
- Obsolete way to find additional versions from downloads page
- Some ~~grammer~~ grammar errors

This was all done to address the original concern of https://github.com/highfidelity/hifi/issues/13924, which resulted in the appearance of a more major error. The issue resulted in the discovery of the typo on the cmake step as well as other missing components, leading to this pull request.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by AndrewMeadows** [comment]
Jenkins, build this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12615/HighFidelity-Beta-PR13926-b5f1c82.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12615/HighFidelity-Beta-PR13926-b5f1c82.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12615/HighFidelity-Beta-Interface-PR13926-b5f1c82.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12615/HighFidelity-Beta-PR13926-b5f1c82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12615/HighFidelity-Beta-Interface-PR13926-b5f1c82.dmg

**Comment by AndrewMeadows** [comment]
No QA necessary for this PR: only the build documentation has changed.

**Pull request merged**
