### PR TITLE
Recording app fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6939/app_12344_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6939/HighFidelity-Beta-PR12344-7f6471fcd189ad04feaa3cec153583bb3752df69.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6949/app_12344_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6949/HighFidelity-Beta-PR12344-7f6471fcd189ad04feaa3cec153583bb3752df69.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6949/HighFidelity-Beta-PR12344-7f6471fcd189ad04feaa3cec153583bb3752df69.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6980/HighFidelity-Beta-PR12344-75cf22ca7fe7bab1c59ca08d4d99bccf0eba9cf6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6980/HighFidelity-Beta-PR12344-75cf22ca7fe7bab1c59ca08d4d99bccf0eba9cf6.dmg

**Comment by themelissabrown** [comment]
@ctrlaltdavid can I get a test plan for this?

**Comment by ctrlaltdavid** [comment]
@themelissabrown There are potentially two further fixes to add. I'll ping the people I'm waiting on, tomorrow.

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7321/HighFidelity-Beta-PR12344-75cf22ca7fe7bab1c59ca08d4d99bccf0eba9cf6.dmg

**Comment by ctrlaltdavid** [comment]
**Test Plan**

*Setup*

Run the modified Record app with the PR build. The Record app isn't included in the installer, so a copy of it as modified by this PR is provided in the attached Zip file.

Set up several of instances of playRecordingAC.js per the instructions in the Record app dialog. There's a separate bug where if a playRecordingAC.js instance stops playing a recording then plays another one, the recording is played back sound-only, so we don't want to reuse a playRecrdingAC.js instance. (If you encounter sound-only playback, restart the domain.)


*Tests*

1) Test making a recording. It chould be automatically loaded and played (no error message box displayed).

2) Make several recordings. Open and close the dialog several times. The table in the dialog should be successfully populated with recordings, each time.

3) Test making a recording with the current release build (RC63 - with several instances of playRecordingAC.js running on it) and the Record app from this PR. It should be automatically loaded and played (no error message box displayed).

[record.zip](https://github.com/highfidelity/hifi/files/1741763/record.zip)

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Stopped testing pending further instruction.

**Comment by RyanDowne** [comment]
Is this PR meant to go into RC65?

**Comment by ctrlaltdavid** [comment]
@RyanDowne Yes, this PR can go into RC65.  Note that it only affects \unpublishedScripts\ so isn't included in the installer. Birarda may submit a separate PR for RC65 that has a fix for recording playback sometimes being sound-only; that PR will affect executable code.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7360/app_12344_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7360/HighFidelity-Beta-PR12344-fa1f2267cf9ad18fc87863427c753b944146575e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7360/HighFidelity-Beta-PR12344-fa1f2267cf9ad18fc87863427c753b944146575e.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Comment by conklin94122** [comment]
@ctrlaltdavid needs dev review

**Comment by MiladNazeri** [comment]
@conklin94122:   
@misslivirose approved earlier and I don't believe the code was changed since then.   She may have been waiting though in regards to David's comment about waiting for additional fixes coming in before adding Dev-Approved.   @misslivirose ok to add the label? 

Those additional ones will probably be on future pr.

**Pull request merged**
