### PR TITLE
Fill in the Downloads: line of the stats window

### PR DESCRIPTION
**Pull request by markej**
This fills in the Downloads: line of the stats window showing the active downloads / download limit as well as the number of pending downloads.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by OmegaHeron** [comment]
Need a trigger to build, please.

**Comment by murillodigital** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2834ff29352eab2b368c5a851e5c513d7ed5236c available at: https://gist.github.com/9938626871242c9baa96<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7363.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7363.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - in expanded stats I see items downloading and items remaining to download as proper, production build does not show this.  QA Pass

**Comment by hyperlogic** [comment]
:+1:  Thanks, this will help us debug the cause of slow site loads.  Also, it might help us determine if frame-rate judder is caused by heavy model/texture loading in the background.

Cheers

**Pull request merged**
