### PR TITLE
Fix crash when deleting objects in serverless mode

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.manuscript.com/f/cases/15806/Crash-on-Delete-Cube
This PR fixes a crash where deleting an object, such as a cube, would cause the interface the crash. The crash was caused by an unresolved invalid state in the physics engine. The resolution in this PR is to simplify the physics simulation ownership state in serverless mode. The state being simplified away is used for networking when a user is connected to a server.

Serverless mode is the mode that a user ends up in when they click on the "GOTO" button or press Ctrl+L (in desktop mode) and click on the home button, or are otherwise not logged into a server. You can see that the Interface is in serverless mode when the title bar contains "serverless".

## TEST PLAN
* In master, in serverless mode, wait for the avatar to stop floating directly above the ground. Then, create a cube and make simple changes to it such as moving it around and resizing it. After doing this, delete the cube. The program should crash.
* In this PR, in serverless mode, do the same. The program should not crash.
* In this PR, create a cube, set Dynamic to enabled in the Properties menu, and set the y value of gravity to some negative value. The cube should fall, and not snap back to a previous position.
* In this PR, create a cube, and set Dynamic to enabled in the Properties menu of the Create window. Then close the window, and have the avatar collide with the cube. The cube should bounce away as normal.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10695/HighFidelity-Beta-PR13411-67c605c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10695/HighFidelity-Beta-PR13411-67c605c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10695/HighFidelity-Beta-Interface-PR13411-67c605c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10695/HighFidelity-Beta-PR13411-67c605c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10695/HighFidelity-Beta-Interface-PR13411-67c605c.exe

**Comment by sabrina-shanman** [comment]
There's a change in behavior when the object editor is open and you set the gravity. In master, the object updates with the new position, but with this PR, the object snaps back to its previous position.

**Comment by AndrewMeadows** [comment]
This introduces a bug where: when dynamic objects come to rest they are updated to their old transform. We'll have to fix it before testing this PR.

**Comment by sabrina-shanman** [comment]
The introduced bug is no longer present in this PR.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10767/HighFidelity-Beta-PR13411-c039d20.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10767/HighFidelity-Beta-Interface-PR13411-c039d20.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10774/HighFidelity-Beta-PR13411-59833d8.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10774/HighFidelity-Beta-PR13411-59833d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10774/HighFidelity-Beta-Interface-PR13411-59833d8.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
interface does not crash.

**Pull request merged**
