### PR TITLE
Hold entity data until client is presumably reachable and has queried

### PR DESCRIPTION
**Pull request by birarda**
- fixed an issue where the initial packet(s) from the octree server could be missed

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4930/HighFidelity-Beta-PR11811-05a38a78c517db0b3c646eac24ca9b1cb7824d57.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4930/HighFidelity-Beta-PR11811-05a38a78c517db0b3c646eac24ca9b1cb7824d57.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4941/HighFidelity-Beta-PR11811-557ee458ecf01cbfcd44a8d3d3574e065c51bcc6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4941/HighFidelity-Beta-PR11811-557ee458ecf01cbfcd44a8d3d3574e065c51bcc6.dmg

**Comment by birarda** [comment]
#### Test Plan

To test this PR, you will need to use the Interface client from this DO NOT MERGE PR - https://github.com/highfidelity/hifi/pull/11818. The issue this PR fixes is occasional, but that PR has a tweak to cause it to be much more likely to occur.

1. With Interface from PR 11818, connect to dev-welcome. You may need to change away from dev-welcome and back a couple of times to reproduce the issue.
2. You should observe that occasionally large items (like the floor) never appear even though the content reports to have finished loading.
3. With the same PR 11818, connect to "sport", which is running this PR. It should have the same content as dev-welcome. You should always see the content fully appear, especially the floor. Change to a different domain and re-connect to sport 5-10 times to confirm it loads the same way every time.

**Comment by birarda** [comment]
I'll mark QA ready once the needed test build from #11818 is ready

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

I'm unable to get past step 1 of  testing as I'm having a bizarre issue with this PR (#11818 build) - Nothing but avatars load regardless of domain, including sandbox. Have tried resetting settings and performing clean install, but to no avail. Upon reinstall the only difference was "Loading content..." displayed whilst trying to connect to sandbox/other domains.

**(Tested without sandbox running initially, used sandbox to try and load areas thereafter) **

**Fail**

Screenshot of what it shows for most domains, but this specifically Dev-welcome:
image

**Comment by birarda** [comment]
@YuppyPlays it's my fault. I just realized I never pushed the right version of the hack for #11818. I'll do that now and the next build should perform properly.

**Comment by YuppyPlays** [comment]
@birarda Ah I see, no worries! I shall be stalking Gustavo in hopes he finishes it soon for retest :)

**Comment by birarda** [comment]
@YuppyPlays here is the link to the build that should correctly force the issue: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4982/HighFidelity-Beta-PR11818-c6673432d46fb769eebf39ebd3ca9f778f825963.exe

**Comment by YuppyPlays** [comment]
@birarda Thank you :) Testing now.

**Comment by YuppyPlays** [comment]
Testing complete:

With Interface from PR 11818, connect to dev-welcome. You may need to change away from dev-welcome and back a couple of times to reproduce the issue. **Check**
You should observe that occasionally large items (like the floor) never appear even though the content reports to have finished loading. **Check**
With the same PR 11818, connect to "sport", which is running this PR. It should have the same content as dev-welcome. You should always see the content fully appear, especially the floor. Change to a different domain and re-connect to sport 5-10 times to confirm it loads the same way every time. **Check, 10/10 times total.**

Happy to report this worked a charm with Sport domain, loaded in MUCH better than dev-welcome and always completely loads **Pass**

**Pull request merged**
