### PR TITLE
Fix messed up LogDialog multi-lines

### PR DESCRIPTION
**Pull request by Atlante45**
Log dialog now correctly prints multi-lines debug messages.

### CODE REVIEW

**Comment by Atlante45** [comment]
Multi-line messages used to not have a carriage return between them in the LogDialog, making it really hard to read them.
This fixes it.

**Comment by Atlante45** [comment]
https://app.asana.com/0/26225263936266/99290441458982

**Comment by Atlante45** [comment]
You can use that simple script to test:
```javascript
function a() {
	var test = {}	
	test.someMethod();
}
function b() {
	a();
}
function c() {
	b();
}
c();
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6e01bbd36e0a1670cb82652c0eb5dc1ca2cceac available at: https://gist.github.com/fad2ad17f5c9f2f21dc3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7304.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7304.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - No issues seen with existing function.  Much better log formatting!  Current code does;

`[03/10 10:05:06] [WARNING] [UncaughtException] TypeError: Result of expression 'test.someMethod' [undefined] is not a function. in JSConcole:3 [03/10 10:05:06] [WARNING] [Backtrace] [03/10 10:05:06] [WARNING] a() at JSConcole:3 [03/10 10:05:06] [WARNING] b() at JSConcole:6 [03/10 10:05:06] [WARNING] c() at JSConcole:9 [03/10 10:05:06] [WARNING] <global>() at JSConcole:11`

This does;

`[03/10 10:06:24] [WARNING] [UncaughtException] TypeError: Result of expression 'test.someMethod' [undefined] is not a function. in JSConcole:3`
`[03/10 10:06:24] [WARNING] [Backtrace]`
`[03/10 10:06:24] [WARNING]     a() at JSConcole:3`
`[03/10 10:06:24] [WARNING]     b() at JSConcole:6`
`[03/10 10:06:24] [WARNING]     c() at JSConcole:9`
`[03/10 10:06:24] [WARNING]     <global>() at JSConcole:11`

QA Pass

**Comment by Nex-Pro** [comment]
Same results as Omega posted. Nice improvement.

**Pull request merged**
