### PR TITLE
Fix crash in packet list

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes a crash that occurs when switching between several domains too fast.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40888e8042623b1493113b3dab1b4fa85d2761f8 available at: https://gist.github.com/b17969810fb9121a93ae7d94ec774a63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40888e8042623b1493113b3dab1b4fa85d2761f8 available at: https://gist.github.com/b17969810fb9121a93ae7d94ec774a63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40888e8042623b1493113b3dab1b4fa85d2761f8 available at: https://gist.github.com/b17969810fb9121a93ae7d94ec774a63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-40888e8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a7b64e87d58d2039323ea0e4fad387f71bfdc02 available at: https://gist.github.com/b17969810fb9121a93ae7d94ec774a63<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-7a7b64e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8223-7a7b64e.dmg

**Comment by birarda** [comment]
Tested hopping between dev domains and the sandbox from this PR. No crash. QA pass.

**Pull request merged**
