### PR TITLE
Fixing web tablet JavaScript error

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixing typo between function name calls
- Related to #13774

**Test Plan**
- Launch Interface in Desktop Mode
- Enable developer menu via `Settings > Developer Menu`
- De-select `Developer > UI > Desktop Tablet Becomes Toolbar`
- Open `Developer > Script Log (HMD Friendly)...`
- The error below (or something similar) should not show up in the debug window

```
[defaultScripts.js] ERROR - [UncaughtException signalHandlerException] Error: Result of expression 'this.handleHomeButtonHover' [undefined] is not a function. in file:///~/development/hifi-fork/build/interface/Release/scripts/system/libraries/WebTablet.js:622
[Backtrace]
    <anonymous>(event = [object Object]) at file:///~/development/hifi-fork/build/interface/Release/scripts/system/libraries/WebTablet.js:622
    <anonymous>(event = [object Object]) at file:///~/development/hifi-fork/build/interface/Release/scripts/system/libraries/WebTablet.js:265
    <global>() at -1
```

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11981/HighFidelity-Beta-PR13793-2a6ff90.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11981/HighFidelity-Beta-PR13793-2a6ff90.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11981/HighFidelity-Beta-Interface-PR13793-2a6ff90.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11981/HighFidelity-Beta-PR13793-2a6ff90.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11981/HighFidelity-Beta-Interface-PR13793-2a6ff90.exe

**Comment by qlimguicheteau** [comment]
Fail @conklin94122 

 Fail- Unable to activate TAB when the Script Log (HMD Friendly) is open. So unable to check for Logging.

**Comment by wayne-chen** [comment]
updated test plan.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No such error appears

**Pull request merged**
