### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6731/app_12296_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6731/HighFidelity-Beta-PR12296-bc819c698ee98eea62e3602191a9fe3568e609a5.exe

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6733/HighFidelity-Beta-PR12296-bc819c698ee98eea62e3602191a9fe3568e609a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6733/HighFidelity-Beta-PR12296-bc819c698ee98eea62e3602191a9fe3568e609a5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6873/app_12296_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6873/HighFidelity-Beta-PR12296-bc819c698ee98eea62e3602191a9fe3568e609a5.dmg

**Comment by marko8904** [comment]
build this please

**Pull request merged**
