### PR TITLE
Hand controller drives mouse, does not take over if set down

### PR DESCRIPTION
**Pull request by PhilipRosedale**
Moving hand controllers (hydra, vive, etc) will move the mouse pointer.  

If hand controllers are cradled (hydra) or not moving (Vive), they will not move the pointer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 86249cc9db6dbfa3c9f2154aa906565101f676bf available at: https://gist.github.com/df44ad6d7bedda83ebe4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b89b6be210011acbdecf7329c7e0eaf7a31784cc available at: https://gist.github.com/df44ad6d7bedda83ebe4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.dmg

**Comment by PhilipRosedale** [comment]
I am putting the QA ready and do not merge labels on because... using the script seems to cause the client to crash after moving the pointer around a while while in HMD mode.  Is that happening to our testers?  I think this is triggering some other deeper bug, so I want to see if it happens to others.

**Comment by hifi-gustavo** [comment]
Build console output for commit: efe53c1a85a037f60078ddc267c595fe5ddf5a40 available at: https://gist.github.com/df44ad6d7bedda83ebe4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.dmg

**Comment by ZappoMan** [comment]
I still see this "taking over my mouse" when it's sitting on my desk... it's much less bad than it used to be... but it seems like "sometimes" it will dramatically grab my mouse and pull it away when it's sitting on my desk. I will try to track down what causes it... it might be my desk shaking...

**Comment by PhilipRosedale** [comment]
@ZappoMan try changing MINIMUM_CONTROLLER_ANGULAR_VELOCITY  to 0.05, does that keep it from happening?  Also do you crash after a minute or so?

**Comment by ZappoMan** [comment]
@PhilipRosedale - 
1) no I am not crashing..
2) it's definitely happening when I "shake" my desk... just by placing my hands on the desk it will move it.
3) if I set MINIMUM_CONTROLLER_ANGULAR_VELOCITY  to 0.15 - it works much better, and it's not likely to grab my mouse... 
4) also.... I think we should add detection of "top level window" and only do this if interface is the active window. I can add a property that is available via script...
5) another thing to consider, do you really want this to work in desk top mode? is it reasonable for this script to disable itself UNLESS it's in an HMD?

**Comment by ZappoMan** [comment]
Also... the "click behavior" doesn't appear to be working anymore... but I'm not sure if that's from your script or not...

**Comment by PhilipRosedale** [comment]
@ZappoMan Fixed click bug.  How about the settling on your desk?

**Comment by hifi-gustavo** [comment]
Build console output for commit: e01524abbe4c6657341ee78c1037edce20c28196 available at: https://gist.github.com/df44ad6d7bedda83ebe4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.dmg

**Comment by ZappoMan** [comment]
@PhilipRosedale - I feel like you need to bump MINIMUM_CONTROLLER_ANGULAR_VELOCITY  up to at least 0.15... otherwise sitting on my desk the mouse never settles....

**Comment by hifi-gustavo** [comment]
Build console output for commit: 87e7dd9ce3088c79bd91e7d19c4be27e7122f983 available at: https://gist.github.com/df44ad6d7bedda83ebe4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7225.dmg

**Pull request merged**
