### PR TITLE
Use binary resources on OSX

### PR DESCRIPTION
**Pull request by jherico**
Switch Mac builds to using binary resources (like all other platforms)

## Testing

OSX & Windows smoke test 
* Verify UI elements load and render

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10390/HighFidelity-Beta-PR13317-5f3715a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10390/HighFidelity-Beta-PR13317-5f3715a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10390/HighFidelity-Beta-Interface-PR13317-5f3715a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10392/HighFidelity-Beta-PR13317-fa51c15.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10392/HighFidelity-Beta-PR13317-fa51c15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10392/HighFidelity-Beta-Interface-PR13317-fa51c15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10392/HighFidelity-Beta-PR13317-fa51c15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10392/HighFidelity-Beta-Interface-PR13317-fa51c15.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122  All UI elements load in and render correctly on both Windows and OSX

**Comment by samcake** [comment]
All good merging

**Pull request merged**
