### PR TITLE
Case 21720: Fix color grading/lighting of renderLayer front entities (RC81)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/21720/renderLayer-front-text-text-entity-showing-all-black-starting-in-79-1

Test plan: https://github.com/highfidelity/hifi/pull/15197

### CODE REVIEW

**Comment by antoninahifi** [comment]
Currently testing (after build)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18188/HighFidelity-Beta-PR15198-c210676.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18188/HighFidelity-Quest-Beta-PR15198-c210676.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18195/HighFidelity-Beta-PR15198-5ecf067.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18195/HighFidelity-Quest-Beta-PR15198-5ecf067.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18197/HighFidelity-Beta-PR15198-3a12dbc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18197/HighFidelity-Quest-Beta-PR15198-3a12dbc.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18197/HighFidelity-Beta-PR15198-3a12dbc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18197/HighFidelity-Beta-Interface-PR15198-3a12dbc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18197/HighFidelity-Beta-PR15198-3a12dbc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18197/HighFidelity-Beta-Interface-PR15198-3a12dbc.exe

**Comment by antoninahifi** [comment]
PASS

**Pull request merged**
