### PR TITLE
move raw bullet code from interface to physics lib

### PR DESCRIPTION
**Pull request by AndrewMeadows**
I ran into this problem when looking into the avatar collision shape and got sidetracked...

A few months ago left some bullet-specific code in the interface but I want to keep the contact between Bullet and our apps at a bare minimum (behind the **physics** lib) so I'm moving this stuff from **MyCharacterController** (interface) into the base class **CharacterController** (physics lib).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c109fd6238cf60e99fbe5e101786013e8bac356 available at: https://gist.github.com/912565baec7c559c98a1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6602-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6602.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c109fd6238cf60e99fbe5e101786013e8bac356 available at: https://gist.github.com/912565baec7c559c98a1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6602-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6602.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e99bff25016f0c2739d9ed2599b4ac701be845a available at: https://gist.github.com/912565baec7c559c98a1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6602-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6602.dmg

**Pull request merged**
