### PR TITLE
Local lights on translucent objects

### PR DESCRIPTION
**Pull request by Zvork**
With this PR translucent objects are now properly lit by all local lights (point and spot).

# Test case
A _hifi_tests/tests/render/engine/material_ update for this is proposed in [PR #59](https://github.com/highfidelity/hifi_tests/pull/59).
It is also suggested to check any domains with translucent objects potentially lit by local lights.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6319/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6319/HighFidelity-Beta-PR12180-8fb863e98c259ac16a7cc4dbaaa695229b38ee24.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6319/HighFidelity-Beta-PR12180-8fb863e98c259ac16a7cc4dbaaa695229b38ee24.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6362/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6362/HighFidelity-Beta-PR12180-e6caa83d734beed2489b1845654e526e3cd2cde4.dmg

**Comment by Zvork** [comment]
build this

**Comment by Zvork** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6364/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6364/HighFidelity-Beta-PR12180-e6caa83d734beed2489b1845654e526e3cd2cde4.exe

**Comment by Zvork** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6365/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6365/HighFidelity-Beta-PR12180-e6caa83d734beed2489b1845654e526e3cd2cde4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6365/HighFidelity-Beta-PR12180-e6caa83d734beed2489b1845654e526e3cd2cde4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6414/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6414/HighFidelity-Beta-PR12180-902bfac380334565759a49f39b6239a6f051e485.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6414/HighFidelity-Beta-PR12180-902bfac380334565759a49f39b6239a6f051e485.dmg

**Comment by Zvork** [comment]
Merge from master has broken this PR. Am trying to fix it.

**Comment by AlanZimmerman** [comment]
Cannot get any indication that transparent (alpha-mapped materials) are receiving local lighting. Tested in two different environments (see screenshots)

**Comment by Zvork** [comment]
@AlanZimmerman I agree that your first screenshot seems like the hair isn't catching the magenta light. Could you give me the domain url where I can check that? As for the second screenshot, maybe I am misinterpreting it, but it seems like the "walking" silhouette is catching the magenta point light, no?

**Comment by Zvork** [comment]
Here are two screenshots with some transparent glass in dev-avatarisland. First is without point lights, second is with point lights on. I can see some specular highlights on the glass. @AlanZimmerman can you confirm that you are seeing the same thing?

specularonwindows-nopointlights

specularonwindows

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6514/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6514/HighFidelity-Beta-PR12180-43f7bb5f56e9dbd72939a54e2cc1f63821ba2fa8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6514/HighFidelity-Beta-PR12180-43f7bb5f56e9dbd72939a54e2cc1f63821ba2fa8.exe

**Comment by samcake** [comment]
@Zvork After double checking with @AlanZimmerman, we can't seem to reproduce the issue in  dev-avatarisland...
if you go to /0, -400, 0 in  avatar island you are in a a place called "body mart" where you have a gallery of avatars to choose from.
this scene is lit with mostly local lights and most of the hair of the avatars are transparent.

**Comment by Zvork** [comment]
@samcake Well the hair seems to be lit properly, as far as I can see. Here are two screenshots, with and without the top spot lights. We can see that the hair is lit the same way as the opaque parts, no?

hair1

hair3

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6563/app_12180_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6563/HighFidelity-Beta-PR12180-c92a9975ba9b35785843328fb06148c12652b7b7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6563/HighFidelity-Beta-PR12180-c92a9975ba9b35785843328fb06148c12652b7b7.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
