### PR TITLE
fix several uninitialized reads

### PR DESCRIPTION
**Pull request by sethalves**
- fix several uninitialized reads

https://highfidelity.fogbugz.com/f/cases/18829/asan-indicates-uninitialized-reads

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- launch interface, look for anything unexpected during startup.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13349/HighFidelity-Beta-PR14087-ff2a47e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13349/HighFidelity-Beta-PR14087-ff2a47e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13349/HighFidelity-Beta-Interface-PR14087-ff2a47e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13349/HighFidelity-Beta-PR14087-ff2a47e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13349/HighFidelity-Beta-Interface-PR14087-ff2a47e.exe

**Comment by qlihifitest** [comment]
Currently testing

**Comment by qlihifitest** [comment]
PASS @conklin94122

**Pull request merged**
