### PR TITLE
Case 22183: Avatar bit-flag compression

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.fogbugz.com/f/cases/22183/Avatar-Network-Optimization-Encoding-Scheme

PR implements a custom codec for Avatar bitvectors that achieves around 4:1 lossless compression on the test dataset I was given. The algorithm is based on run-length encoding followed by Golomb codes with adaptive Rice parameter. It has already been extensively fuzzed and unit-tested on a large dataset.

Not used yet, pending integration by @hyperlogic.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19051/HighFidelity-Beta-PR15473-f1ed4e7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19051/HighFidelity-Quest-Beta-PR15473-f1ed4e7.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19051/HighFidelity-Beta-PR15473-f1ed4e7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19051/HighFidelity-Beta-Interface-PR15473-f1ed4e7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19056/HighFidelity-Beta-PR15473-9a89546.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19056/HighFidelity-Beta-Interface-PR15473-9a89546.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19056/HighFidelity-Beta-PR15473-9a89546.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19056/HighFidelity-Quest-Beta-PR15473-9a89546.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19056/HighFidelity-Beta-PR15473-9a89546.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19056/HighFidelity-Beta-Interface-PR15473-9a89546.exe

**Comment by shanzzam** [comment]
Talked to @hyperlogic who talked to @ZappoMan and this is currently stalled as "it's requires a protocol change... brad specifically called it out as not for v1.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21364/HighFidelity-Beta-PR15473-a2cc29c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21364/HighFidelity-Quest-Beta-PR15473-a2cc29c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21364/HighFidelity-Beta-PR15473-a2cc29c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21364/HighFidelity-Beta-Interface-PR15473-a2cc29c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21364/HighFidelity-Beta-PR15473-a2cc29c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21364/HighFidelity-Beta-Interface-PR15473-a2cc29c.exe

**Comment by ZappoMan** [comment]
cleaning up open PRs, we can revisit this in the future.

**Pull request closed without merging**
