### PR TITLE
fix for OAuth OPTIONS firing every XHR 302

### PR DESCRIPTION
**Pull request by birarda**
- fixed a crash with open OAuth browser clients on domain-server restart
- fixed OPTIONS request on XHR 302 from XHR requests after domain-server restart

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1172/HighFidelity-Beta-PR10845-cf921447489d06aa82f183049519d63804c5e7f7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1172/HighFidelity-Beta-PR10845-cf921447489d06aa82f183049519d63804c5e7f7.exe

**Comment by ZappoMan** [comment]
@birarda - what's the test plan for this? is this QA Ready?

**Comment by birarda** [comment]
#### Test Plan (for @marko8904)

Deploy this PR to a domain that uses OAuth to auth 40100 endpoint. Confirm that the `/` page is refreshed if the domain is restarted while looking at the `/` page.

**Comment by marko8904** [comment]
going to deploy this PR to dev-distributed right now.

**Comment by marko8904** [comment]
The fix itself got rid of the original issue! However since on DS restart a new proper connection is now automatically initiated we hit the oauth/authorize more often which causes the DS freezing bug to manifest more frequently. We may have to fix that one before this is merge or we run the risk of lots of domains becoming unresponsive for a minute after every deployment.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1418/HighFidelity-Beta-PR10845-6d98d20b129d5f69f1257e8f103898b6cb506b28.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1418/HighFidelity-Beta-PR10845-6d98d20b129d5f69f1257e8f103898b6cb506b28.dmg

**Comment by marko8904** [comment]
This is great! Two for one fix! I see the oauth/authorize storm nipped in the bud and I can't get the DS to freeze with oauth/authorize requests any longer!

**Pull request merged**
