### PR TITLE
fix crash with multiple solo nodes in closeCurrentPacket

### PR DESCRIPTION
**Pull request by birarda**
- fixed a crash in `closeCurrentPacket` due to multiple solo nodes

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

- On master, run a Sandbox and connect via Interface. On the domain-server settings page, manually kill either the audio-mixer or avatar-mixer. Could take a couple of attempts but you should crash on one of the manual kills.
- On this PR, complete the same steps as above. Perform multiple avatar-mixer and audio-mixer manual kills from domain-server settings page. Confirm you do not crash and that your audio and avatar data is correctly flowing through the new mixer (once connection is complete).

**Comment by hifi-gustavo** [comment]
Build console output for commit: f28f3d7fcf9adeb8ee841754b63e48b4f41b55ba available at: https://gist.github.com/2abbb1013c9281790f78c280a5a6e1af<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8279-f28f3d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8279-f28f3d7.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f28f3d7fcf9adeb8ee841754b63e48b4f41b55ba available at: https://gist.github.com/2abbb1013c9281790f78c280a5a6e1af<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8279-f28f3d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8279-f28f3d7.dmg

**Comment by thoys** [comment]
## QA Report

- Was able to reproduce the crash on master, after 10+ tries.
- Tried it restarting 20+ times on the PR build, no crash. Avatar and audio still working.

QA Pass

**Pull request merged**
