### PR TITLE
Commerce: Wallet Passphrase Input Modal

### PR DESCRIPTION
**Pull request by zfox23**
Don't formally test. DNM until @davidkelly finishes his work to change the wallet's passphrase.

1. Adds a modal popup window that appears when the wallet is set up, but the user hasn't input the wallet's correct passphrase (which was previously hardcoded to `pwd`).
2. Revamps the initialization flow for `Wallet`, `Checkout`, and `Purchases`. See below...
3. Adds a debug button in the Help tab to clear the cached passphrase. Useful while testing.

Apps that rely on Commerce have the following flow:
1. Check if the user is logged in to High Fidelity. If not, prompt them to log in. If so...
2. Check if there exists a `hifikey` file on the user's hard drive. If not, the wallet isn't setup, so prompt them to set it up. If so...
3. Check if there exists a Security Image. If not, the wallet isn't setup, so prompt them to set it up. If so...
4. Check if the user is authenticated to access the Wallet. If not, the user hasn't put in the correct passphrase, so prompt them to do so. If so...
5. Allow access to the app (`Wallet`, `Checkout`, or `Purchases`) normally.

This PR pretty drastically changes the flow and adds areas where things could potentially be buggy. We _really_ need to hammer on the flow during final formal testing (and do the same internally in the meantime).

### CODE REVIEW

**Comment by zfox23** [comment]
[Hookup a new signal inside `passwordCallback()` to reveal UI element](https://trello.com/c/vvkEnwN0/370-hookup-a-new-signal-inside-passwordcallback-to-reveal-ui-element)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2994/HighFidelity-Beta-PR11294-fa25c434ca64065ee8efe9222f586ad4ea87ee50.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3005/HighFidelity-Beta-PR11294-8fcdfa171d8a9703b930886697ba2d62a13b8c4b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3005/HighFidelity-Beta-PR11294-8fcdfa171d8a9703b930886697ba2d62a13b8c4b.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3027/HighFidelity-Beta-PR11294-3cf0df518ff4f07b8d7855b9775357f40698cea3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3027/HighFidelity-Beta-PR11294-3cf0df518ff4f07b8d7855b9775357f40698cea3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3030/HighFidelity-Beta-PR11294-90316e275afa39f6ba198931184a7c646889b79d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3030/HighFidelity-Beta-PR11294-90316e275afa39f6ba198931184a7c646889b79d.exe

**Comment by zfox23** [comment]
[Make balance field look non-active](https://trello.com/c/dNBAimLP/371-make-balance-field-look-non-active)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3033/HighFidelity-Beta-PR11294-47cd47f819052becaa57680422e586912e93c395.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3033/HighFidelity-Beta-PR11294-47cd47f819052becaa57680422e586912e93c395.exe

**Comment by davidkelly** [comment]
both @zfox23 and I have tested this.  We dev-approved eachothers work too.  Merging.

**Pull request merged**
