### PR TITLE
simple-compound = wrap each render part of each submesh

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* improved simple-compound convexification strategy: wrap hull around each render part of submesh

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 207ddcea3863805597f066c23efe32192fcfa02d available at: https://gist.github.com/a96aad8a2d7e7e14ba23fb36f61050c5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222.dmg

**Comment by AndrewMeadows** [comment]
This PR introduces an elaboration to the simple-compound convexification strategy in #8192: rather than wrap each submesh, parse the submeshes for render parts (typically split according to material) and wrap those instead.  This produces better collision shapes or some objects.

I'm still looking for a publicly available model with one mesh but several materials that will demonstrate the improvements so I can write up a test plan.  If anyone knows of one I can use then send me a message.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72175ae09e1510de3adef4fcb2b90e515cc05a0a available at: https://gist.github.com/a96aad8a2d7e7e14ba23fb36f61050c5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72175ae09e1510de3adef4fcb2b90e515cc05a0a available at: https://gist.github.com/a96aad8a2d7e7e14ba23fb36f61050c5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222-72175ae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222-72175ae.dmg

**Comment by AndrewMeadows** [comment]
Odd... Jenkins claims that the window build failed but does not provide errors.  I built on windows to test and verified that this branch builds without errors.  I guess we'll try again...

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72175ae09e1510de3adef4fcb2b90e515cc05a0a available at: https://gist.github.com/a96aad8a2d7e7e14ba23fb36f61050c5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222-72175ae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8222-72175ae.dmg

**Comment by AndrewMeadows** [comment]
To test:

(1) Obtain a model that has one mesh that is split into different materials (an example link pending, but the HookGun (rumored to be in the marketplace) satisfies this requirement).
(2) Create a ModelEntityItem using the model from (1)
(3) Using edit.js select "Hull Per Submesh" for the entity's "shapeType"
(4) Examine the entity's collision shape, but walking your avatar on it, throwing dynamic objects at it, or setting it dynamic and throwing it around.

(5) Repeat steps (2) through (4) using the old release candidate and note the collision shape details.
(6) Compare the apparent collision shape in (4) as in (5) -- depending on how the model was built the new collision shape in (4) should have more detail than (5) -- more concavity on some places rather than being one convex hull.

**Comment by Nex-Pro** [comment]
@AndrewMeadows  the links for the models are identical

**Comment by BingShearer** [comment]
@Nex-Pro I believe they are actually two different models - Jack and Jack2.

**Comment by AndrewMeadows** [comment]
I had accidentally written identical links and then I went back and edited the test plan to set the second one to jack2.

**Comment by Nex-Pro** [comment]
#### Tested on win10

**With both models set as "Hull Per Submesh"**


**In this pr:** 
        jack collides only on the center upright part of the mesh.
        jack2 collides correctly.

**In 5137:**
       jack collides correctly
       jack2 collides as if wrapped in a convex hull.

**Comment by RyanDowne** [comment]
excellent :)

**Pull request merged**
