### PR TITLE
remove highlight on entity when point to the sky

### PR DESCRIPTION
**Pull request by druiz17**
Ticket - https://highfidelity.manuscript.com/f/cases/14896/Moving-laser-or-cursor-from-grabbable-object-to-the-sky-keeps-the-object-highlighted-temporarily

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan in this PR https://github.com/highfidelity/hifi/pull/13123

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9579/app_13122_PR_45e996bcfae7330182fee7fd4808adc7766e56f9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9579/HighFidelity-Beta-PR13122-45e996bcfae7330182fee7fd4808adc7766e56f9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9579/HighFidelity-Beta-Interface-PR13122-45e996bcfae7330182fee7fd4808adc7766e56f9.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Pass @conklin94122

**Pull request merged**
