### PR TITLE
Fix parabola shader

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/17553/Pressing-A-or-X-button-when-above-Sandbox-creates-scrambled-view-in-HMD-and-limited-teleportation

Test plan:
- Run [this](https://gist.githubusercontent.com/SamGondelman/7bbb72ec23d3bcc1a9a2651ca5587d5c/raw/6570f92601072ad99116baaaa850f4bc3bc67cdf/ParabolaPointerTest.js).  A parabola should shoot out of your right hand.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12072/HighFidelity-Beta-PR13816-86ba8c3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12072/HighFidelity-Beta-Interface-PR13816-86ba8c3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12072/HighFidelity-Beta-PR13816-86ba8c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12072/HighFidelity-Beta-Interface-PR13816-86ba8c3.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Test script ran as expected. Parabolic teleport beams now render without extra artifacts.

**Pull request merged**
