### PR TITLE
Don't allow sorting on non-sortable columns in PAL

### PR DESCRIPTION
**Pull request by davidkelly**
In particular, the nearby tab (if you are an admin) has silence and ban buttons.  Both of which don't have 'state' and cannot really be sorted on.  Sadly if you did sort on them, nothing happened, until next time you open the PAL.  When you do, it is blank, until you modify or wipe the settings in AppData.  

So now, clicking on those column headers does nothing.

### CODE REVIEW

**Comment by davidkelly** [comment]
Test Plan

Open Pal somewhere you have admin rights.  
Click ban or silence column headers
Close PAL
Open PAL

In master, PAL will be empty.  And stay that way until you go to `C:\Users\<you>\AppData\Roaming\<whatever you are running>\Interface.json` and change `pal/nearbySortIndicatorColumn` to 0, 1 or 2.  


In this PR, clicking on the ban or silence headers should do nothing (no sort indicator arrow, etc...), and when you close and re-open PAL should look fine

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/297/HighFidelity-Beta-PR10587-f79c9ea0218c3c50580caeb5b48ec177423d9e7a.dmg

**Comment by davidkelly** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/298/HighFidelity-Beta-PR10587-f79c9ea0218c3c50580caeb5b48ec177423d9e7a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/298/HighFidelity-Beta-PR10587-f79c9ea0218c3c50580caeb5b48ec177423d9e7a.dmg

**Comment by davidkelly** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/299/HighFidelity-Beta-PR10587-f79c9ea0218c3c50580caeb5b48ec177423d9e7a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/299/HighFidelity-Beta-PR10587-f79c9ea0218c3c50580caeb5b48ec177423d9e7a.dmg

**Comment by zfox23** [comment]
This looks good to me.

I'm very surprised there isn't a boolean `sortable` property of `TableViewColumn` objects. But, I went looking through the documentation, and indeed there isn't one.

**Comment by davidkelly** [comment]
me too!  I thought I'd add it, (derive new hifi TableViewClass), but when I did this it appears sufficient.  No indicator, etc... so seems ok.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/304/HighFidelity-Beta-PR10587-b6b2f92af2440acf0d42131c216fab1f317bb38b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/304/HighFidelity-Beta-PR10587-b6b2f92af2440acf0d42131c216fab1f317bb38b.dmg

**Comment by CainFoool** [comment]
# Test Passed 

No sorting arrow was shown when clicking on the Silence / Ban tabs - however the buttons beside each player highlighted depending on which tab title you clicked. Not sure if this is still meant to be intentional.

**Pull request merged**
