### PR TITLE
tablet-ui: Added sortOrder property to buttons

### PR DESCRIPTION
**Pull request by hyperlogic**
By default user created buttons will appear after system buttons.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 35e3e2f26a39b5337de1a6d1a152cb6ccfde57d8 available at: https://gist.github.com/0539bab0b2f6c58ea08347684a7177f9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9599-35e3e2f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9599-35e3e2f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85e01e3922b1847c41c968ad0b764a350ea32fb2 available at: https://gist.github.com/0539bab0b2f6c58ea08347684a7177f9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9599-85e01e3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9599-85e01e3.dmg

**Comment by hyperlogic** [comment]
QA test plan:  run the following script, verify that the star button appears last.

    var tablet = Tablet.getTablet("com.highfidelity.interface.tablet.system");
    var button = tablet.addButton({
        icon: "http://s3.amazonaws.com/hifi-public/tony/icons/star.png",
        text: "TEST"
    });

Modify the script so that it adds the sortOrder: 0 property.  Now the button should be the first button on the tablet.


    var tablet = Tablet.getTablet("com.highfidelity.interface.tablet.system");
    var button = tablet.addButton({
        icon: "http://s3.amazonaws.com/hifi-public/tony/icons/star.png",
        text: "TEST",
        sortOrder: 0
    });

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
### PASS

**Pull request merged**
