### PR TITLE
Fix pointing at non-web overlays

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.fogbugz.com/f/cases/16476

Test Plan:
Re-run tests from PR https://github.com/highfidelity/hifi/pull/13383
In addition, also verify when pressing trigger that you can point at the Trigger to Sit overlay at any chair and the inspect overlay (as mentioned in the above bug) and that you can click on both.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11182/HighFidelity-Beta-PR13561-f815ad1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11182/HighFidelity-Beta-PR13561-f815ad1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11182/HighFidelity-Beta-Interface-PR13561-f815ad1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11182/HighFidelity-Beta-PR13561-f815ad1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11182/HighFidelity-Beta-Interface-PR13561-f815ad1.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Overlays both web and non-web now work as expected. Bug is fixed!

**Pull request merged**
