### PR TITLE
Fix MS16704: Remove worn Avatar/Wearable before updating

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS16704](https://highfidelity.manuscript.com/f/cases/16704/Remove-wearables-avatars-when-updating-them-to-newer-versions).

### CODE REVIEW

**Comment by zfox23** [comment]
**Test plan writing in progress...**

## Test Plan
1. On the Staging marketplace, purchase and wear <SOME AVATAR>. Also, purchase and wear <SOME WEARABLE>.
2. Tell Zach that you've done this. Wait for him to tell you to continue. He will post an update to both items.
3. Go to My Purchases. Verify that you have an update available to both items you purchased in (1).
4. Attempt to update the both items. Verify that you see a popup explaining that you need to take off the avatar/wearable first. Click CANCEL.
5. Manually change avatars and remove the wearable.
6. Attempt to update both items. Verify that you DO NOT see a popup explaining that you need to take action, but are instead taken to the update's Marketplace page.
7. Return to My Purchases. Re-wear both items from (1).
8. Attempt to update both items. Verify that you see a popup explaining that you need to take off the avatar/wearable first. Click CONTINUE. Verify that the avatar/wearable is taken off and that you are taken to the update's Marketplace page.
9. Update to the newest version of both items. Verify that they both can be worn correctly.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11533/HighFidelity-Beta-PR13682-eea4630.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11533/HighFidelity-Beta-Interface-PR13682-eea4630.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11533/HighFidelity-Beta-PR13682-eea4630.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11533/HighFidelity-Beta-Interface-PR13682-eea4630.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11533/HighFidelity-Beta-PR13682-eea4630.apk

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Pull request merged**
