### PR TITLE
CR for Job #21355 - Clean up and remove menu hotkeys

### PR DESCRIPTION
**Pull request by mnafees**
Code Review for Job #21355 - Workitem available at https://www.worklist.net/21355

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1316/HighFidelity-Beta-PR10878-eb354a43339d1ad8b075240eb2ceeca559e5ca33.dmg

**Comment by themelissabrown** [comment]
@mnafees can you add a test plan? Also, double check that the "x" key remains active for handshake in desktop.

**Comment by CainFoool** [comment]
Can test once a plan is available.

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1328/HighFidelity-Beta-PR10878-eb354a43339d1ad8b075240eb2ceeca559e5ca33.dmg

**Comment by mnafees** [comment]
## Test plan
All the shortcut keys have been removed for edit.js menu items. The "H" key for full screen mirror mode and "P" key for third person/first person toggle have been removed as requested. All the other menu shortcut keys have been documented here https://worklist-production.s3.amazonaws.com/attachment/0af91835-afe2-6649.txt including the Avatar size changes.

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
@mnafees Are we getting a windows build ?

**Comment by mnafees** [comment]
@Nex-Pro The Windows build Jenkins console output suggests that there is an error while building VHACD. Builds fine on macOS and Ubuntu. I wonder if one of the ops have to look into it to check what's the issue.

**Comment by Nex-Pro** [comment]
@mnafees VHACD is used to create collision hulls for imported meshes

**Comment by mnafees** [comment]
@Nex-Pro This PR is almost just about deleting stuff and builds fine on macOS and Ubuntu so I do not understand how it's failing to build on Windows. Can you try again to initiate a new build process to check?

**Comment by mnafees** [comment]
@themelissabrown Need some help here :)

**Comment by mnafees** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1374/HighFidelity-Beta-PR10878-eb354a43339d1ad8b075240eb2ceeca559e5ca33.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1374/HighFidelity-Beta-PR10878-eb354a43339d1ad8b075240eb2ceeca559e5ca33.exe

**Comment by mnafees** [comment]
@Nex-Pro Here you go :D

**Comment by Nex-Pro** [comment]
Cool

**Comment by Nex-Pro** [comment]
testing now

**Comment by Nex-Pro** [comment]
**PASS**

Shortcuts P and H have been removed.

Also removed shortcuts for:

### ENTITIES
    Entity list
    Allow selecting of large models
    Allow selecting of small models
    Allow selecting of lights
    Select all entities in box
    Select all entities touching box
    Export entities
    Import entities
    Import entities from URL

All shortcuts in the text file checked and are working.
Also enter key and del key still work.

**Comment by Nex-Pro** [comment]
@mnafees  ^

**Pull request merged**
