### PR TITLE
(RC78) Change Avatar App design for avatar collisions

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR changes the checkboxes on the Avatar App used to configure avatar collisions.
https://highfidelity.manuscript.com/f/cases/20296/New-Setting-to-Disable-Avatar-Avatar-Collisions

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Pre-merge and Post-merge plans included on the ticket:
https://highfidelity.manuscript.com/f/cases/20296/New-Setting-to-Disable-Avatar-Avatar-Collisions

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16424/HighFidelity-Beta-PR14706-da6c213.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16424/HighFidelity-Beta-PR14706-da6c213.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16424/HighFidelity-Beta-Interface-PR14706-da6c213.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16424/HighFidelity-Beta-PR14706-da6c213.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16424/HighFidelity-Beta-Interface-PR14706-da6c213.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
Fail. it seems that whenever I save an option and re open the avatar app the option does not look like it saves successfully but continues to function as though it was selected. Video attached.

[converted.zip](https://github.com/highfidelity/hifi/files/2756658/converted.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16433/HighFidelity-Beta-PR14706-958be50.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16433/HighFidelity-Beta-PR14706-958be50.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16433/HighFidelity-Beta-Interface-PR14706-958be50.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16433/HighFidelity-Beta-PR14706-958be50.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16433/HighFidelity-Beta-Interface-PR14706-958be50.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
