### PR TITLE
Case 21334: PickManager is slow when 3D keyboard mallets are enabled (0.80.0)

### PR DESCRIPTION
**Pull request by danteruiz**
ticket - https://highfidelity.manuscript.com/f/cases/21334/Tablet-Laser-performance-is-slow-when-3D-keyboard-mallets-are-enabled-0-80-0

### CODE REVIEW

**Comment by danteruiz** [comment]
perform this test plan - https://github.com/highfidelity/hifi/pull/14965

make sure that all layers of the keyboard work when raising and lowering and when going to different domains

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17462/HighFidelity-Beta-PR14969-74c8c1a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17462/HighFidelity-Beta-PR14969-74c8c1a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17462/HighFidelity-Beta-Interface-PR14969-74c8c1a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17462/HighFidelity-Beta-PR14969-74c8c1a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17462/HighFidelity-Beta-Interface-PR14969-74c8c1a.exe

**Pull request merged**
