### PR TITLE
remove renderLaserPointers()

### PR DESCRIPTION
**Pull request by ZappoMan**
Remove some dead code for six sense Hydra lasers.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f4ec09a48b935ebbef05c66d90d5c57276dd781a available at: https://gist.github.com/8c94055f41fa0f16176a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5401.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5401.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 720f6ec529d7b9f023569599651cfd2d30742b36 available at: https://gist.github.com/8c94055f41fa0f16176a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5401.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5401.dmg

**Comment by SamGondelman** [comment]
Is there a plan to replace them with something different?

**Comment by ZappoMan** [comment]
My plan is to have whoever wants them back to add them. ;)

**Comment by samcake** [comment]
To Sam's point, there is a need for a cursor representation coming from the hands.
We agree,
 we nuke the sixsense specific code
After the DisplayPLugin we can consider a unified hand cursor solution for overlay

**Comment by ZappoMan** [comment]
Yes I agree this should be in the display/input plugins.

**Pull request merged**
