### PR TITLE
Update 'model' icon in edit.js

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 712c0bdf9d2b6a4c4b2516f9e408ad5d019f7cd6 available at: https://gist.github.com/4593f2363c7d231d6f1ced23cd2a7270<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7721.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7721.dmg

**Comment by huffman** [comment]
To test:

* Run http://rawgit.com/huffman/hifi/feat/udpate-edit-model-icon/examples/edit.js and confirm that the model import icon now says "Model," example: http://prnt.sc/auoa0p

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7721
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Successful test.  Closed ``edit.js``` and ran ```http://rawgit.com/huffman/hifi/feat/udpate-edit-model-icon/examples/edit.js``` and confirmed that the model import icon now says "Model".  Screen shot enclosed. 
**Successful Logout/Crash:** Successful logout.
capture

**Comment by huffman** [comment]
Marking as QA Approved, thanks @kevinmthomas-carpool !

**Pull request merged**
