### PR TITLE
Bug fix for Users unable to Squat

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses case https://highfidelity.manuscript.com/f/cases/17996/Avatar-can-not-stay-in-a-squatted-position-while-in-VR

1 Created a new SitStandStateType  Force Standing.  When this is enabled then the user can squat down to the ground without vertical recentering being triggered.  At the same time they are still able to walk around in room scale in order to move about the room.

### Test Plan
1) start interface. 
2) go to settings controls and set the Avatar Leaning Behavior to 3. Standing
3) go into hmd mode and sit down. then go down on one knee.
4) expected result: there should be no vertical recentering. allowing users to sit on the ground with out causing recentering.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14331/HighFidelity-Beta-PR14265-36466a4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14331/HighFidelity-Beta-PR14265-36466a4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14331/HighFidelity-Beta-Interface-PR14265-36466a4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14506/HighFidelity-Beta-PR14265-5365085.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14506/HighFidelity-Beta-PR14265-5365085.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14506/HighFidelity-Beta-Interface-PR14265-5365085.exe

**Comment by shanzzam** [comment]
This was addressed in a fix included in 75. That release will go out next week. Moving this to 76 for tracking and any followup.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15050/HighFidelity-Beta-PR14265-5365085.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15050/HighFidelity-Beta-PR14265-5365085.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15050/HighFidelity-Beta-Interface-PR14265-5365085.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15054/HighFidelity-Beta-PR14265-f2f4a55.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15054/HighFidelity-Beta-PR14265-f2f4a55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15054/HighFidelity-Beta-Interface-PR14265-f2f4a55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15054/HighFidelity-Beta-PR14265-f2f4a55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15054/HighFidelity-Beta-Interface-PR14265-f2f4a55.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . verified that when users take a knee or sit down no vertical re-centering of the avatar occurs.

**Pull request merged**
