### PR TITLE
Quiet warnings

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
@jherico What's the difference between the viewFrustum and the displayViewFrustum?
Could we just have getViewFrustum() and return the correct one depending on the thread?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 940363bf2e925d2a29b0abbf9f4465421d4a8068 available at: https://gist.github.com/d2e250981d7adc314e49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4885.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4885.dmg

**Comment by Atlante45** [comment]
I hadn't noticed but Brad already add a PR up to fix it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 407d1bd013a28f4abb0a8e5d329a82dbe55df34b available at: https://gist.github.com/d2e250981d7adc314e49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4885.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4885.dmg

**Pull request merged**
