### PR TITLE
TESTING - DO NOT MERGE

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/c29b5b49588c5792c2f8<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/0c6e92419a6e7cc6d756<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/1cdb77f606ad3615f32f<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/bb0198f3bb55ddbae83b<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/0835d97331a1448ffe3a<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/ba9f1fdc736fd9de923f<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/94bf0f37dd15db6b5728<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/833eeef66968e22170a4<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/e16469cafc9aa5e7362a<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/89e893e6abc1c7678cdb<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/f177e18958cca7a27fc0<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/c82fa39390bb7cb2b080<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/4e09de634c758ae95022<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/a546273cf2400793b616<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/7aa79ca37c79b563fc47<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/87bd47c5a39d172e7f2c<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 871aa65d8135c2ad17cd44b85bc3ff56a19d8174 available at: https://gist.github.com/0e7247acb2bbaa4257c9<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4238.dmg

**Pull request closed without merging**
