### PR TITLE
snapshot bug fixes

### PR DESCRIPTION
**Pull request by druiz17**
This PR addresses some issues with snapshot in tablet and toolbar mode.
 fogbugz tickets
 - https://highfidelity.fogbugz.com/f/cases/4013/
- https://highfidelity.fogbugz.com/f/cases/4007/

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
In tablet mode and toolbar mode when not logged in
- open the tablet and take a snapshot 
- once the snapshot preview 
-  Clicking on share in feed or settings showed bring up a new page on the tablet and make sure that clicking cancel brings you back to the snapshot preview.
- now click on share feed and log in. If you check the feed you snapshot should show,  
- if you enabled "open feed after" option, the feed should open after you share the snapshot. (test this when you are logged in and logged out)

**Comment by hifi-gustavo** [comment]
Build console output for commit: df6498c67ca80c88ed989e19b57ab52d7b26a438 available at: https://gist.github.com/d8bfcf4194c2b4372a5324f9335a9028<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-df6498c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-df6498c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 382204a9a98bba7a1885ca22c2628ff81f5967b1 available at: https://gist.github.com/d8bfcf4194c2b4372a5324f9335a9028<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-382204a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-382204a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d823093ddb5f56a0a31c3bcaf817066f4e473118 available at: https://gist.github.com/d8bfcf4194c2b4372a5324f9335a9028<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-d823093.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-d823093.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10184-d823093.exe

All tests completed:
- Tablet in HMD Mode: PASS
- Tablet in Desktop Mode: PASS
- Toolbar in HMD Mode: PASS
- Toolbar in Desktop Mode: PASS

All of these steps below were completed in the above-mentioned modes.
- Open the tablet and take a snapshot: Success
- Once the snapshot preview, cicking on share in feed or settings showed bring up a new page: PASS
- Make sure that clicking cancel brings you back to the snapshot preview: PASS
- Now click on share feed and log in: Success
- If you check the feed, your snapshot should show: PASS
- if you enabled "open feed after" option, the feed should open after you share the snapshot: PASS 

Notes: 
- After a snapshot is taken, the SNAP does not show up at the top of the feed. At first I thought the snapshots were not loading up to the feed, but I later figured out they are in the feed, but I had to do a bit of searching for them.
- I had 3 crashes. I filled out the Crash Report for one, because the other two crashes failed to produce Crash Report windows. All the crashes were arbitrary. Clicking on a tab, an Icon, or the 'X' button on the tablet caused the crashes. There seemed to be no logical reasoning behind the crashes.

**Pull request merged**
