### PR TITLE
Fix audio-mixer timing for WIN32

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
### QA Plan

Run a server on WIN32 and ensure the audio sounds good. Look at the stats for the `audio-mixer` node and ensure `us_per_tic(_trailing)` is at about 10000.

Run a server on Linux and do the same.

**Comment by OmegaHeron** [comment]
Will test this on Win/Linux shortly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: abf0962cd25f79677682933f3854e65da791f7c6 available at: https://gist.github.com/d460df5584f28bae15803d0c21a6b71d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9533-abf0962.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9533-abf0962.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d82c8b251a1b3757e9833ff6b35ba3803427187e available at: https://gist.github.com/d460df5584f28bae15803d0c21a6b71d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9533-d82c8b2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9533-d82c8b2.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Windows 10
Master, highly variable us_per_tic(_trailing) and choppy audio on echo back.
This PR 9999, 9998, 10000, voice on server echoback = good.

Linux (Ubuntu 16.04.1)
Master is fine - shows 10k ticks and good audio
This PR is fine - shows 10k ticks and good audio

**Pull request merged**
