### PR TITLE
BUGZ-484: Add --setBookmark and getAddress API

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.atlassian.net/browse/BUGZ-484

### CODE REVIEW

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19919/HighFidelity-Beta-PR15741-a1b7392.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19919/HighFidelity-Quest-Beta-PR15741-a1b7392.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19919/HighFidelity-Beta-PR15741-a1b7392.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19919/HighFidelity-Beta-Interface-PR15741-a1b7392.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19919/HighFidelity-Beta-PR15741-a1b7392.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19919/HighFidelity-Beta-Interface-PR15741-a1b7392.exe

**Pull request merged**
