### PR TITLE
RC68 version of Personal space bubble is defaulted off for now.

### PR DESCRIPTION
**Pull request by howard-stearns**
See https://github.com/highfidelity/hifi/pull/13305 for test plan.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10363/HighFidelity-Beta-PR13306-bfc6fad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10363/HighFidelity-Beta-PR13306-bfc6fad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10363/HighFidelity-Beta-Interface-PR13306-bfc6fad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10363/HighFidelity-Beta-PR13306-bfc6fad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10363/HighFidelity-Beta-Interface-PR13306-bfc6fad.exe

**Comment by howard-stearns** [comment]
not going in 68, because tutorial refers to it being on

**Pull request closed without merging**
