### PR TITLE
FB19396 - QML warning qrc:///qml/hifi/tablet/WindowRoot.qml:132: Type…

### PR DESCRIPTION
**Pull request by ElderOrb**
…Error: Cannot read property of null

https://highfidelity.fogbugz.com/f/cases/19396/QML-warning-qrc-qml-hifi-tablet-WindowRoot-qml-132-TypeError-Cannot-read-property-of-null

**Test plan**

1. Clear logs
2. Launch interface
3. Ensure logs doesn't contain entries 'qrc:///qml/hifi/tablet/WindowRoot.qml:132: TypeError: Cannot read property of null'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14050/HighFidelity-Beta-PR14227-0ab8a0b.apk

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14050/HighFidelity-Beta-PR14227-0ab8a0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14050/HighFidelity-Beta-Interface-PR14227-0ab8a0b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14050/HighFidelity-Beta-PR14227-0ab8a0b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14050/HighFidelity-Beta-Interface-PR14227-0ab8a0b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14057/HighFidelity-Beta-PR14227-0ab8a0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14057/HighFidelity-Beta-Interface-PR14227-0ab8a0b.dmg

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14859/HighFidelity-Beta-PR14227-0ab8a0b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14859/HighFidelity-Beta-PR14227-0ab8a0b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14859/HighFidelity-Beta-Interface-PR14227-0ab8a0b.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
