### PR TITLE
print the metaverse session ID to the debug log

### PR DESCRIPTION
**Pull request by birarda**
Added debug to print the metaverse session ID to the debug log, once it is received.

### CODE REVIEW

**Comment by birarda** [comment]
### Test Plan

Run this PR. Confirm that in your Interface log you see a line like the following:

`Metaverse session ID is $UUID`

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/316/HighFidelity-Beta-PR10593-3d98f1b3eebc605cc2bcbed823e3c172a573e208.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/316/HighFidelity-Beta-PR10593-3d98f1b3eebc605cc2bcbed823e3c172a573e208.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Failed

Unable to see this line in hifi-log.txt.
I have attached it for convenience.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/1046094/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/328/HighFidelity-Beta-PR10593-0f22b07026be8558ba18041f8d545bf77f6f80b2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/328/HighFidelity-Beta-PR10593-0f22b07026be8558ba18041f8d545bf77f6f80b2.dmg

**Comment by CainFoool** [comment]
Retesting.

**Comment by CainFoool** [comment]
# Test Passed

Had to dig through the log a little, but found `[06/02 00:38:08] [DEBUG] [hifi.interface] Metaverse session ID is "080b263b-ef0d-460b-9182-43ad53a8e3f7"`.

**Pull request merged**
