### PR TITLE
Fix Mac crash caused by PR#15825

### PR DESCRIPTION
**Pull request by kencooke**
https://github.com/highfidelity/hifi/pull/15825 crashes on Mac due to aligned loads on unaligned memory. The AVX2 code should only use unaligned vector loads/stores and make no assumptions about QVector alignment. Fixed by this PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20138/HighFidelity-Beta-PR15838-b079e32.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20138/HighFidelity-Beta-Interface-PR15838-b079e32.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20138/HighFidelity-Beta-PR15838-b079e32.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20138/HighFidelity-Quest-Beta-PR15838-b079e32.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20141/HighFidelity-Beta-PR15838-4c5c612.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20141/HighFidelity-Beta-Interface-PR15838-4c5c612.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20141/HighFidelity-Beta-PR15838-4c5c612.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20141/HighFidelity-Beta-Interface-PR15838-4c5c612.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20141/HighFidelity-Beta-PR15838-4c5c612.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20141/HighFidelity-Quest-Beta-PR15838-4c5c612.apk)

**Pull request merged**
