### PR TITLE
Make sure that there is only one connection created for web events, s…

### PR DESCRIPTION
**Pull request by vladest**
…o downloads from CLARA IO not duplicated
Test plan:
1. Open Marketplace
2. Go to Clara.io Market
3. Select a model to import (Vans shoe)
4. Save to High Fidelity
5. Make sure in objects list in Create that only one copy of the object is added

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/231/HighFidelity-Beta-PR10565-bcee25acc7317575a668df88046f169df0462492.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/231/HighFidelity-Beta-PR10565-bcee25acc7317575a668df88046f169df0462492.dmg

**Comment by CainFoool** [comment]
@vladest Is this QA Ready?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/232/HighFidelity-Beta-PR10565-238a2b2eb8c98093b73ea3438997ba02f3875a31.dmg

**Comment by vladest** [comment]
@CainFoool I cant see whats wrong with checks, but if the build is ready then yes

**Comment by CainFoool** [comment]
@vladest: Okay, testing.

**Comment by CainFoool** [comment]
# Test Passed 

When I imported the model into my game, it only created one instance of the shoe (see screenshot)
880bbe3c-e170-4ca7-9139-5f490c3cd3ca

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/233/HighFidelity-Beta-PR10565-238a2b2eb8c98093b73ea3438997ba02f3875a31.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/265/HighFidelity-Beta-PR10565-238a2b2eb8c98093b73ea3438997ba02f3875a31.exe

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/266/HighFidelity-Beta-PR10565-238a2b2eb8c98093b73ea3438997ba02f3875a31.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/266/HighFidelity-Beta-PR10565-238a2b2eb8c98093b73ea3438997ba02f3875a31.dmg

**Pull request merged**
