### PR TITLE
Combined notifications

### PR DESCRIPTION
**Pull request by howard-stearns**
combines https://github.com/highfidelity/hifi/pull/14031 and https://github.com/highfidelity/hifi/pull/14002 for demonstration purposes.

### CODE REVIEW

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13263/HighFidelity-Beta-PR14074-56a6458.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13263/HighFidelity-Beta-PR14074-56a6458.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13263/HighFidelity-Beta-Interface-PR14074-56a6458.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13282/HighFidelity-Beta-PR14074-2d29881.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13282/HighFidelity-Beta-PR14074-2d29881.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13282/HighFidelity-Beta-Interface-PR14074-2d29881.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13282/HighFidelity-Beta-PR14074-2d29881.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13282/HighFidelity-Beta-Interface-PR14074-2d29881.dmg

**Comment by howard-stearns** [comment]
demo complete, this is now obsolete

**Pull request closed without merging**
