### PR TITLE
Fix audio overlay not working while in edit apps

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Enables the audio (mic mute) overlay to be used when the Create app or Shapes app is active.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

HMD mode.
Run the Shapes app per https://github.com/highfidelity/hifi-content/pull/201 - provided below as a zip file.

1) Check that you can use the audio overlay when in the Create app.
- Just default scripts loaded and no apps currently running.
- Check that you can use both hands' lasers to toggle the mic mute on/off using the audio overlay (mic plus VU bar) top left of HUD overlay.
- Run the Create app.
- Check that you can still use both hands' lasers to toggle the mic mute on/off using the audio overlay.
- Check that the Create app still functions: you can use its dialogs and entity manipulation handles.

2) Check that tyou can use the audio overlay when running the Shapes app.
- Just default scripts plus the Shapes app from the attached zip file loaded, and no apps currently running.
- Check that you can use both hands' lasers to toggle the mic mute on/off using the audio overlay.
- Run the Shapes app: click on the "SHAPES" tablet button and turn the Shapes app on. UI should appear on your non-dominant hand.
- Check that you can still use both hands' lasers to toggle the mic mute on/off using the audio overlay. And that there is only one laser beam that ends on the audio overlay when you do.
- Check that the Shapes app still functions: you can use Tools menu, you can create new entities using the Create menu (grab move and release 3D icons from the menu), and you can use your hands and lasers to move and resize entities.
- Check that if you open the Create app while the Shapes app is running, the lasers work for the Create app (e.g, laser clicking on an entity causes the Create app's edit handles to appear), not the Shapes app (e.g., the Shapes app UI can't be used).

3) Check that you can near grab and equip entities.
- Test per https://github.com/highfidelity/hifi/pull/14058 / https://highfidelity.manuscript.com/f/cases/18419

https://highfidelity.manuscript.com/f/cases/16440

[shapes.zip](https://github.com/highfidelity/hifi/files/2444481/shapes.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13632/HighFidelity-Beta-PR14142-3bc1c29.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13632/HighFidelity-Beta-PR14142-3bc1c29.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13632/HighFidelity-Beta-Interface-PR14142-3bc1c29.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13632/HighFidelity-Beta-PR14142-3bc1c29.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13632/HighFidelity-Beta-Interface-PR14142-3bc1c29.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13721/HighFidelity-Beta-PR14142-0b163ff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13721/HighFidelity-Beta-PR14142-0b163ff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13721/HighFidelity-Beta-Interface-PR14142-0b163ff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13721/HighFidelity-Beta-PR14142-0b163ff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13721/HighFidelity-Beta-Interface-PR14142-0b163ff.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13951/HighFidelity-Beta-PR14142-0b163ff.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13951/HighFidelity-Beta-PR14142-0b163ff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13951/HighFidelity-Beta-Interface-PR14142-0b163ff.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13951/HighFidelity-Beta-PR14142-0b163ff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13951/HighFidelity-Beta-Interface-PR14142-0b163ff.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Create and Shapes both functioned as expected, with the added ability to mute and unmute! Grabbing and equipping were not affected.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14114/HighFidelity-Beta-PR14142-490c085.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14114/HighFidelity-Beta-PR14142-490c085.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14114/HighFidelity-Beta-Interface-PR14142-490c085.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14114/HighFidelity-Beta-PR14142-490c085.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14114/HighFidelity-Beta-Interface-PR14142-490c085.exe

**Pull request merged**
