### PR TITLE
GPU identification utilities

### PR DESCRIPTION
**Pull request by howard-stearns**
see example in SharedUtil.cpp.

for use with https://github.com/highfidelity/hifi/pull/7688

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de0aadff9e170f241464da6dc48755138d33f83 available at: https://gist.github.com/1a77b754c05bcbe0a3b0d0777992a795<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.dmg

**Comment by ZappoMan** [comment]
Formatting looks broken on thess files.

**Comment by howard-stearns** [comment]
@jherico With this PR build (when it finishes), see if you can bring up any domain so that it is rendering on your dual graphics-card deslotp machine, and then in the javascript console, try Render.getVCard() and see if answers the right card.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c0a786c8384024fdd476fa6ee74df4535783ecc7 available at: https://gist.github.com/1a77b754c05bcbe0a3b0d0777992a795<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20deeb501c8727200077d426435b21087dd59d29 available at: https://gist.github.com/1a77b754c05bcbe0a3b0d0777992a795<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.dmg

**Comment by jherico** [comment]
So, I ran this on my system and it reported the following

```
[04/19 11:20:19] [DEBUG] GPU:
[04/19 11:20:19] [DEBUG]        card: "NVIDIA GeForce GTX 980 Ti"
[04/19 11:20:19] [DEBUG]        driver: "10.18.13.6472"
[04/19 11:20:19] [DEBUG]        dedicated memory: 4095 MB
```

This is correctly finding the right card, but this card has 6GB of memory, not 4.  I'm not sure if this is a limitation of the API, or because you're coercing the reported value to a 32 bit int in `var.ChangeType(CIM_UINT32);`.  

Honestly I'm not sure it matters, because as discussed, this value is likely only going to get referenced as a fallback in cases where neither the ATI or nVidia extensions work, so pretty much only on integrated cards.

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc2ceb3e926d71f01a2df1d47332958e88985568 available at: https://gist.github.com/1a77b754c05bcbe0a3b0d0777992a795<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7693.dmg

**Comment by jherico** [comment]
incorporated into https://github.com/highfidelity/hifi/pull/7688

**Pull request closed without merging**
