### PR TITLE
Vive UI bug fixes

### PR DESCRIPTION
**Pull request by howard-stearns**
accumulated fixes to vive-ui, for master:
- cannot near grab even large equipable objects
- update green quip ball as object moves
- make "nearness" for equipping match the ball size
- reticle gets stuck at lookAt
- make context menus come up under mouse rather than to the side
- reticle depth wrong on context menu
- HUD should reset when coming back from moving, but not when toggling overlays directly

### CODE REVIEW

**Comment by howard-stearns** [comment]
Not read for test yet. Accumulating plan:

### grab
- Test grab script in demo to make sure it still functions as expected.
- The green equip-hot spot spheres should now stay attached to the object as it moves.
- Test new "Developer > Grab Script > Draw Grab Boxes" menu option. This option should draw a blue sphere around your hand when you squeeze the trigger. When the blue sphere overlaps with the blue box of an entity, you will near grab it. When the green sphere overlaps the green sphere on the object you will equip it instead.
- It should be possible to near-grab the ping-pong gun by grabbing the stock or the barrel, were previously this was difficult.

### reticle
- Bring up context menu with a right mouse click in HMD. The mouse cursor should be visible at the same apparent depth as the menu.
- If the cursor is not visible before using the vive hand controller to bring up the menu, it won't be visible after either.
- A source of "reticle gets stuck to where you are lookiing" has been removed, so report if you see that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f7e9d3968af303c223f14900cfc50756dbc36a88 available at: https://gist.github.com/5fbaa995c0f12996f58133b7d8dcc272<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8134.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8134.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa8d1d097ea89988d63bb1112d18be030a5bf04e available at: https://gist.github.com/5fbaa995c0f12996f58133b7d8dcc272<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8134.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8134.dmg

**Comment by SamGondelman** [comment]
### grab
- Test grab script in demo to make sure it still functions as expected.
	- :heavy_check_mark:
	- worth mentioning that https://highfidelity.fogbugz.com/f/cases/771/Far-grab-adjusts-radius-on-body-pose-adjustment still happens
- The green equip-hot spot spheres should now stay attached to the object as it moves.
	- :heavy_check_mark:
- Test new "Developer > Grab Script > Draw Grab Boxes" menu option. This option should draw a blue sphere around your hand when you squeeze the trigger. When the blue sphere overlaps with the blue box of an entity, you will near grab it. When the green sphere overlaps the green sphere on the object you will equip it instead.
	- :x:, if you grab an object with one hand and then try to grab it with the other (near or far), it doesn't show the equip point on that object.  When you pass over overlays, the blue and green spheres stop updating their positions
- It should be possible to near-grab the ping-pong gun by grabbing the stock or the barrel, were previously this was difficult.
	- :heavy_check_mark:

### reticle
- Bring up context menu with a right mouse click in HMD. The mouse cursor should be visible at the same apparent depth as the menu.
	- :heavy_check_mark:
- If the cursor is not visible before using the vive hand controller to bring up the menu, it won't be visible after either.
	- :heavy_check_mark:
- A source of "reticle gets stuck to where you are lookiing" has been removed, so report if you see that.
	- :heavy_check_mark: (didn't see it)
- Other: when rushing through various other PRs, I got into a state after switching back to desktop in which my hardware mouse stopped responding. Please watch out for this.
	- :heavy_check_mark: (didn't happen to me after screwing around and switching back and forth between display plugins)

### hud
- Place the HUD tray or other windows to the side and position your head to the side relative to where it was at the last reset. Drive with drive keys or physically walk and you the hud should disappear (except for the hud button and anything else pinned) and come back. When it comes back the hud itself should be re-centered and re-oriented. (However, the items on the hud should still be at their previous position within the hud. The hud is re-positioned,re-centered as a whole.)
	- :heavy_check_mark:
- However, repeat the same setup and don't drive, but do toggle the HUD button on/off, or toggle View->Overlays on and off. In this case, the HUD button should not bounce around when you toggle things back on.
	- :heavy_check_mark:, nice, this makes a huge difference

Notes:

- In demo, I equipped the bubble wand and repositioned it with my other hand and it stopped blowing bubbles.  Started filling the log with errors.
- In demo, press trigger enough to show green spheres but not enough to grab.  Pass hand over an object.  Hand laser stops following hand.
- On the blocks in demo, the blue grab boxes seem to be z-fighting with the blocks.

**Comment by howard-stearns** [comment]
Looks like these aren't regressions - either present in master or limitations in new functionality that we'll look into going forward.

Pass.

**Pull request merged**
