### PR TITLE
RC63: Revert "Display both lasers on tablet and Web surfaces"

### PR DESCRIPTION
**Pull request by SamGondelman**
(cherry picked from commit 455090d2b94c6b6dd26b863bd8ec1b15936200fa)

### CODE REVIEW

**Comment by conklin94122** [comment]
To test:

Put both hands on the tablet, you should only see one laser.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6575/app_12247_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6575/HighFidelity-Beta-PR12247-1529fea9837a75bb490d4bb58c5acde1bade004f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6575/HighFidelity-Beta-PR12247-1529fea9837a75bb490d4bb58c5acde1bade004f.exe

**Comment by Qliemillar** [comment]
Tested - PASS. There is only one laser present when holding both hands over the tablet. @conklin94122

**Pull request merged**
