### PR TITLE
Fix GOTO TheSpot Button in Interstitial Page

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for MS#[18382](https://highfidelity.manuscript.com/f/cases/18382/Interstitial-Abort-button-text-is-obscured-in-HMD-mode)
- Fix for MS#[18402](https://highfidelity.manuscript.com/f/cases/18402/Interstitial-Abort-Button-is-Blurry)

### For MS#[18402](https://highfidelity.manuscript.com/f/cases/18402/Interstitial-Abort-Button-is-Blurry):
- Launch Interface in Desktop mode
- Open `GOTO` app from toolbar
- Go to any domain
- When interstitial page pops up before entering domain, `GOTO TheSpot` button should not be blurry

### For MS#[18382](https://highfidelity.manuscript.com/f/cases/18382/Interstitial-Abort-button-text-is-obscured-in-HMD-mode):
- Launch Interface in HMD mode
- Spawn tablet
- Open `GOTO` app from the tablet
- Go to any domain
- When interstitial page pops up before entering domain, `GOTO TheSpot` button should not be obscured

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12979/HighFidelity-Beta-PR13991-77d5ebf.apk

**Comment by JeffClinton** [comment]
Currently testing (once built)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12979/HighFidelity-Beta-PR13991-77d5ebf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12979/HighFidelity-Beta-Interface-PR13991-77d5ebf.exe

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Comment by JeffClinton** [comment]
Will test again on new build

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12990/HighFidelity-Beta-PR13991-53582bd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12990/HighFidelity-Beta-PR13991-53582bd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12990/HighFidelity-Beta-Interface-PR13991-53582bd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12990/HighFidelity-Beta-PR13991-53582bd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12990/HighFidelity-Beta-Interface-PR13991-53582bd.exe

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Pull request merged**
