### PR TITLE
Revert "Prevent webviews from reading arbitrary local files"

### PR DESCRIPTION
**Pull request by jherico**
Reverts highfidelity/hifi#13651

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11556/HighFidelity-Beta-PR13691-1a1940e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11556/HighFidelity-Beta-PR13691-1a1940e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11556/HighFidelity-Beta-Interface-PR13691-1a1940e.dmg

**Comment by jherico** [comment]
test this please

**Comment by qliejahner** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11560/HighFidelity-Beta-PR13691-1a1940e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11560/HighFidelity-Beta-Interface-PR13691-1a1940e.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11561/HighFidelity-Beta-PR13691-1a1940e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11561/HighFidelity-Beta-Interface-PR13691-1a1940e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11561/HighFidelity-Beta-PR13691-1a1940e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11561/HighFidelity-Beta-Interface-PR13691-1a1940e.exe

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11564/HighFidelity-Beta-PR13691-1a1940e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11564/HighFidelity-Beta-Interface-PR13691-1a1940e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11564/HighFidelity-Beta-PR13691-1a1940e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11564/HighFidelity-Beta-Interface-PR13691-1a1940e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11564/HighFidelity-Beta-PR13691-1a1940e.apk

**Comment by conklin94122** [comment]
Please test in the 0.70.1 build after it's merged.

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
