### PR TITLE
Distance grab with second hand rotates entity

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- If you distance-grab an entity with one hand you can move the entity as before.
- If you distance-grab the same entity with your second hand, you can rotate the entity with the second hand (and still move it with the first).
- If you let go with your first hand, the second hand's operation changes to moving the entity instead of rotating it.
- You cannot rotate an entity if another person has grabbed the entity.
- The rotation applied to the entity is twice the magnitude of the change in your rotating controller's rotation.
- The rotation is applied smoothly, as seen both by yourself and others.
- Near grabbing still works.
- Tablet operation still works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8d17be0e06206ce94839765d747259feba505a3 available at: https://gist.github.com/5366f5bbfd472b23e7335ce0c88a4fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-d8d17be.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-d8d17be.dmg

**Comment by Nex-Pro** [comment]
Looking at this.

**Comment by Nex-Pro** [comment]
painfully slow download.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  So far I tested this alone. I set myself the challenge of rotating a cube that had the emissive pink face on the opposite side to me through 180 degrees in yaw. I gave up. Although It is possible to rotate the object it feels a little like herding cats. You might succeed but you probably won't. If the sole intent of this is to be able to simply rotate a dynamic object in some arbitrary manner then this works. As a person that likes to feel in control of what is going on I'd only consider this a partial solution. The current reality is that manipulating objects in HMD is a hit or miss affair. Mostly miss. I appreciate the work you are doing to this but I'm not sure how useful this is. If this is a first iteration then I eagerly await the day I can actually control Ents whilst in the HMD. If you want me to check that others see this smoothly I'll need to wait until I can grab another user.

**Comment by ctrlaltdavid** [comment]
@Nex-Pro Yes, please check that other see the rotation smoothly. (I'm pretty sure they do but then my observer PC isn't up to HiFi reqs.)
This is per-spec from @PhilipRosedale and perhaps just a first pass at rotating.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid Testing this now.

**Comment by Nex-Pro** [comment]
### PASS

Tested with @PhilipRosedale

**Comment by hifi-gustavo** [comment]
Build console output for commit: 482c23ead540b0c3ca11ce39e26232c4cd7c7ae9 available at: https://gist.github.com/5366f5bbfd472b23e7335ce0c88a4fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-482c23e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-482c23e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 388a144af19afe92d238475e46e1ede68143cfb9 available at: https://gist.github.com/5366f5bbfd472b23e7335ce0c88a4fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-388a144.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9788-388a144.dmg

**Pull request merged**
