### PR TITLE
Fix multiple sessions being created for some users

### PR DESCRIPTION
**Pull request by huffman**
If a user didn't have send-data activated they don't have their session id
sent in the header of requests, but instead send it inside the request
body. The session id being sent in the request included curly braces which
the server considers invalid.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 38776fe007220cc7b57fdc68e2ac975a359ae22e available at: https://gist.github.com/ad2eef3d0c158347262346839e48efd0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49da7d9a61beae00f125694ca86dcc45c8a6b526 available at: https://gist.github.com/ad2eef3d0c158347262346839e48efd0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dd73f0c333116a1b78c8553206b8cc6262b15dec available at: https://gist.github.com/ad2eef3d0c158347262346839e48efd0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49da7d9a61beae00f125694ca86dcc45c8a6b526 available at: https://gist.github.com/ad2eef3d0c158347262346839e48efd0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8170.dmg

**Comment by huffman** [comment]
To Test:

1. Go to Settings > General, make sure `Send data` is on.
1. Run this script: `https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?pr8170`
1. Open your address bar and go to "playa"
1. Wait 20 seconds
1. Go to Settings > General, make sure `Send data` is off.
1. Open your address bar and go to "localhost"
1. Wait 20 seconds
1. Go to Settings > General, make sure `Send data` is on.
1. Open your address bar and go to "playa"
1. Wait 20 seconds

That's it. Once you have completed these steps, let me know, and I can verify things on my end.

**Comment by OmegaHeron** [comment]
Completed - I I seem to have missed installing server console with this - I subbed Heron for localhost - if that borks it let me know and I'll repeat.

**Comment by OmegaHeron** [comment]
Repeated with sandbox installed so I could use localhost.

**Comment by huffman** [comment]
Thanks @OmegaHeron !

**Pull request merged**
