### PR TITLE
Don't drop saved reliable packets upon HandshakeReq

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Ticket: https://highfidelity.manuscript.com/f/cases/21609/10-out-of-200-traits-bots-stayed-as-white-spheres-after-avatar-mixer-restart

A HandshakeReq control packet is basically a connection reset when the state is out-of-sync. In the case where a SendQueue is active this PR recycles any unacknowledged packets and preserves queued-for-sending packets. Note that this may re-order packets.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18243/HighFidelity-Beta-PR15218-b928610.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18243/HighFidelity-Quest-Beta-PR15218-b928610.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18243/HighFidelity-Beta-PR15218-b928610.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18243/HighFidelity-Beta-Interface-PR15218-b928610.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18248/HighFidelity-Beta-PR15218-19ca886.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18248/HighFidelity-Beta-Interface-PR15218-19ca886.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18248/HighFidelity-Beta-PR15218-19ca886.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18248/HighFidelity-Quest-Beta-PR15218-19ca886.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18248/HighFidelity-Beta-PR15218-19ca886.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18248/HighFidelity-Beta-Interface-PR15218-19ca886.exe

**Comment by howard-stearns** [comment]
[white spheres cases](https://trello.com/c/JJeKt5mZ/15-white-spheres-cases)

**Pull request closed without merging**
