### PR TITLE
fix a couple of resampling errors in Sound downSample

### PR DESCRIPTION
**Pull request by birarda**
- fixes addition of extra garbage sample when resampling from 48Khz to 28Khz mono
- fixes occasional requirement of extra sample for edge of stereo audio

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5da3b81d567676b6cb973cd4ce4f5c58a2faaab available at: https://gist.github.com/57e2feb6de9fc0f8682f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc716461e3be559f23d2a6b253f407eda6d7bd49 available at: https://gist.github.com/57e2feb6de9fc0f8682f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.dmg

**Comment by birarda** [comment]
Warning! Testing this will not be very comfortable for your ears. Keep your volume very low.

On master, run the following script from your interface client. You should have screeching audio as soon as the clip loops.

```
var sound = SoundCache.getSound("http://hifi-public.s3.amazonaws.com/birarda/boos.wav");

var id = Script.setInterval(function() {
    print("Checking audio...");
    if (sound.downloaded) {
        Script.clearInterval(id);
        print("Starting audio...");
        Audio.playSound(sound, {
            position: { x: 0, y: 0, z: 0 },
            volume: 0.5,
            loop: true,
            localOnly: true
        });
    }
}, 100);
```

The same script on this branch should loop properly.

**Comment by birarda** [comment]
test this please

**Comment by imgntn** [comment]
yes, that is a terrrrrible noise lol i'll download the new build as soon as it's up

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a386cdde845cd3af3e2f6d925f48dd94f19c8aa available at: https://gist.github.com/57e2feb6de9fc0f8682f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6961.dmg

**Comment by imgntn** [comment]
sounds good to me, win 8.1

**Pull request merged**
