### PR TITLE
FBX fixes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6806/app_12314_PR.apk

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Test loading of problematic FBX file.
- Put the attached FBX files on a Web server (or use the following URLs: http://ctrlaltstudio.com/downloads/hifi-dev/soldier/Soldier_2k_poly.fbx, http://ctrlaltstudio.com/downloads/hifi-dev/soldier/Soldier_2k_poly_7.fbx).
- Use Create > Model > Model URL to add the FBX models to a domain.
- The models should render per the attached image. (No text is displayed on the white square for one; this is a separate, known problem.)

2) Smoke test loading of other FBX files in general. (See Testrail 7048.)

test-snap

[soldier.zip](https://github.com/highfidelity/hifi/files/1683840/soldier.zip)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6806/HighFidelity-Beta-PR12314-a7ec4501e65396d4c7bf2316dd73188cea7a3c7d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6806/HighFidelity-Beta-PR12314-a7ec4501e65396d4c7bf2316dd73188cea7a3c7d.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
Testing Completed. PASSED.

**Pull request merged**
