### PR TITLE
Spectator Camera app icon

### PR DESCRIPTION
**Pull request by zfox23**
There's an icon for the Spectator Camera tablet now.

**Test Plan:**
Is there a tablet icon for the Spectator Camera?
- If YES, comment "SPECTATOR CAMERA IS THE BEST AND ZACH IS THE BEST DEVELOPER OR AT LEAST IN THE TOP HUNDRED AT HIFI" on this PR.
- If NO, comment "ARE YOU KIDDING ME ZACH HOW COULD YOU SCREW UP SOMETHING THIS SIMPLE" on this PR

### CODE REVIEW

**Comment by zfox23** [comment]
[spectator app button art](https://trello.com/c/kcaGuXjf/175-spectator-app-button-art)

**Comment by YuppyPlays** [comment]
😂 Will test when built

**Comment by YuppyPlays** [comment]
😂 Will test when built

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1419/HighFidelity-Beta-PR10907-1afa2d3775d4a4363c5f2b9d5ac6c46ffec9aa4d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1419/HighFidelity-Beta-PR10907-1afa2d3775d4a4363c5f2b9d5ac6c46ffec9aa4d.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
SPECTATOR CAMERA IS THE BEST AND ZACH IS THE BEST DEVELOPER OR AT LEAST IN THE TOP HUNDRED AT HIFI!

**Pass :D** 😂

**Comment by zfox23** [comment]
♥

**Pull request merged**
