### PR TITLE
Fix anim graph preference change

### PR DESCRIPTION
**Pull request by howard-stearns**
Make MyAvatar.get/setAnimGraphUrl take a url(!), work from Javascript, and make setting it actually do something. (Alphas reported that changing from preference no longer worked.)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 187c213f416bb2a29d9e5f40ea916b3dc863c281 available at: https://gist.github.com/7173716db26198dd7585<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6547.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6547.dmg

**Comment by hyperlogic** [comment]
Did I miss something, where does the preferences menu call setAnimGraphUrl when the user changes it?

**Comment by howard-stearns** [comment]
Not sure I understand the question. Do you mean the check in PreferencesDialog::savePreferences()?

**Comment by hyperlogic** [comment]
I see, it was already there, but previously it did not work, because all setAnimGraphUrl was set a local variable.

**Comment by hyperlogic** [comment]
:+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0a4f7d177934a0783a00685c6d8a0a8479149a1 available at: https://gist.github.com/7173716db26198dd7585<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6547.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6547.dmg

**Pull request merged**
