### PR TITLE
Fixing the ImageOverlay Bug

### PR DESCRIPTION
**Pull request by samcake**
- FIxing the IMageOVerlay not showing for the Edit.js button, the reason is that the rendering of the ImageOverlay need the curent glUsePRgogram to be 0 and it wasn't

- IN an effort to get ready for the migration of all the 2D overlay elements we started working on that front for ImageOverlay but testing that would work fine except in some cases so we kept the code around commented.

- Improved the gpu::StdShaderLib with a way to get a SHaderProgram as a singleton by passing the unique getters to the shaders from the lib object. this way, we avoid to create multiple versions of the same program.

- Added 2 more shaders to the gpu::StdShaderLib to draw a textured colored quad easily

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5555ccd225e185c37e935fd88edcd91b6bfde814 available at: https://gist.github.com/9d9dbe27d9f22c8ede4e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f08c608195de1a459e1039fa4de0bb69ef09c518 available at: https://gist.github.com/9d9dbe27d9f22c8ede4e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.dmg

**Comment by samcake** [comment]
OK, fixed the build and tested on mac, it should work now

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99ae0326ad754f1d0f9258f57198c418c0676272 available at: https://gist.github.com/9d9dbe27d9f22c8ede4e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5318.dmg

**Comment by PhilipRosedale** [comment]
tested on mac.

**Comment by thoys** [comment]
Works on windows too. Planky usually didn't start the buttons on startup, unless I put a timeout. This solves it :+1:

**Pull request merged**
