### PR TITLE
"Unprototype" the Spectator Camera

### PR DESCRIPTION
**Pull request by zfox23**
**QA TESTERS: DO NOT TEST** 😄

**2017-06-07 2:45PM**
As of now, this PR *just* contains my first pass at renaming some variables. I'm putting this PR up now because I want to make sure I'm renaming things "correctly" as per all of our expectations (but mostly @howard-stearns').

I will continue making changes to this PR before it'll be ready to be merged.

**2017-06-08 4:26PM**
This is ready for CR and QA.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/477/HighFidelity-Beta-PR10636-9aa867e4cc1216ff877ec0e87521e0fa2b1da159.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/477/HighFidelity-Beta-PR10636-9aa867e4cc1216ff877ec0e87521e0fa2b1da159.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/508/HighFidelity-Beta-PR10636-36aece94fe105260a2e332fa8e733c896f6978c8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/508/HighFidelity-Beta-PR10636-36aece94fe105260a2e332fa8e733c896f6978c8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/520/HighFidelity-Beta-PR10636-e21cf1c30c1832f12888779f39ef1d882d816abb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/520/HighFidelity-Beta-PR10636-e21cf1c30c1832f12888779f39ef1d882d816abb.exe

**Comment by zfox23** [comment]
["unprototype" the branch](https://trello.com/c/l4UnZgJe/173-unprototype-the-branch)

**Comment by zfox23** [comment]
[camera model instead of box](https://trello.com/c/HqM5S3y8/166-camera-model-instead-of-box)

**Comment by zfox23** [comment]
[better initial position for camera when turning it on](https://trello.com/c/8CoAR52g/181-better-initial-position-for-camera-when-turning-it-on)

**Comment by zfox23** [comment]
[full bright preview on camera](https://trello.com/c/5H16DXqO/184-full-bright-preview-on-camera)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/549/HighFidelity-Beta-PR10636-8825e9177536d6844b88152b4ae37fdecb140a34.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/549/HighFidelity-Beta-PR10636-8825e9177536d6844b88152b4ae37fdecb140a34.dmg

**Pull request merged**
