### PR TITLE
Set active button property isActive before Home menu redraw. Makes su…

### PR DESCRIPTION
**Pull request by vladest**
…re redraw will read proper value of isActive property

Test plan:
- Press Create button
- Press Home aka (X) button 
- repeat, during high system load
- make sure Create button did not stays in active mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/399/HighFidelity-Beta-PR10616-4dbe646c17000e1a58ca6c362f4f211a5b888c4a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/399/HighFidelity-Beta-PR10616-4dbe646c17000e1a58ca6c362f4f211a5b888c4a.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

I'm not exactly sure what is specified as the home button except within the GoTo section?..

I attempted Create then pressing goto, I found the first click doesn't seem to work but second does. repeated this and same result, though Create does turn inactive once goto is enabled.

Also experienced Create & Goto highlighting in the bar after clicking back to create first time, the goto screen disappears and shows create but both stay highlighted/active. other buttons don't seem to cause this for me.

**Fail?**

Please let me know if there is anything more I can do/provide to assist.

**Comment by vladest** [comment]
@YuppyPlays Home button is button on the bottom of the Tablet which is looks like (X) 
So, if you will press Create button then (X) button, create button should not be in active (selected) mode
you dont need to press Goto button

**Comment by YuppyPlays** [comment]
@vladest Ah i see, I just re-tested and can confirm this is a **Pass** for the specified criteria.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/501/HighFidelity-Beta-PR10616-dc2c79baab32e051195c143a972365c789c1296b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/501/HighFidelity-Beta-PR10616-dc2c79baab32e051195c143a972365c789c1296b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/506/HighFidelity-Beta-PR10616-b7f8cc7f0b5a6a0b5f973035472789763e390649.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/506/HighFidelity-Beta-PR10616-b7f8cc7f0b5a6a0b5f973035472789763e390649.dmg

**Pull request merged**
