### PR TITLE
QA READY: Improve address bar address entry

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2807f76e6838233bce7ebf46d384a6a5f7ae80c0 available at: https://gist.github.com/361f001d5ed515931007d32f23ee151c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-2807f76.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-2807f76.dmg

**Comment by ctrlaltdavid** [comment]
QA NOTES
- Upon opening address bar, your location should be displayed as before but without a flashing cursor.
- You can start typing an address to go to without clicking in the address bar first.
- When typing an address, your current location is hidden and the characters you type plus a flashing cursor are displayed.
- If you click into the address bar entry field a flashing cursor is displayed to indicate that it's ready for typing an address.
- If you use the backwards and forwards arrows (without manually entering an address) the location reported in the address bar is updated with your new location and connection status.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a347936b6884e24574465704a9ae1723e4748422 available at: https://gist.github.com/361f001d5ed515931007d32f23ee151c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-a347936.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-a347936.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ee931723470a6437ab4d7efd0a44605bb7896a7 available at: https://gist.github.com/361f001d5ed515931007d32f23ee151c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-1ee9317.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-1ee9317.dmg

**Comment by RyanDowne** [comment]
There is a small bug here. Repro:

Login and click Enter.
Click on one of the pictures and the field gets filled with path
When you get to the location, click Enter and you will see the path still filled in. 

I'd expect to see the helper text again and the pics above.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6221a5f833ada3e37223fbe1bbd4d2a26e15cdf available at: https://gist.github.com/361f001d5ed515931007d32f23ee151c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-b6221a5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8750-b6221a5.dmg

**Pull request merged**
