### PR TITLE
Case 20657: artist stocking inventory

### PR DESCRIPTION
**Pull request by howard-stearns**
Include your own NFS items in marketplace listings, so you can stock up.

https://highfidelity.manuscript.com/f/cases/20657/creators-stock-inventory

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16711/HighFidelity-Beta-PR14765-754f55e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16711/HighFidelity-Beta-Interface-PR14765-754f55e.exe

**Comment by howard-stearns** [comment]
Test plan is to repeat all existing marketplace tests, alas (because the state of what buttons are active are so intertwined), _plus_... 

- Put an item in marketplace that is NFS, and get it approved. 
- You should see the item as "not for sale" when you visit the marketplace in Interface. (You should not see "not for sale" items created by others.) 
- If you actually go to the individual item page, it should tell you that you can stock your inventory with this item for free. (If you go to a "not for sale" item created by others, it should still read "not for sale")
- From that individual item page, you should be able to "buy" your own NFS item for free. (Even for Avatars and Apps that you are normally only allowed to "buy" when you don't already have it, and you _do_ already have this one because you have the edition-zero/artist's-proof.)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16765/HighFidelity-Beta-PR14765-49a3a13.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16765/HighFidelity-Beta-Interface-PR14765-49a3a13.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16765/HighFidelity-Beta-PR14765-49a3a13.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16765/HighFidelity-Beta-Interface-PR14765-49a3a13.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16774/HighFidelity-Beta-PR14765-2070e9a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16774/HighFidelity-Beta-PR14765-2070e9a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16774/HighFidelity-Beta-Interface-PR14765-2070e9a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16774/HighFidelity-Beta-PR14765-2070e9a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16774/HighFidelity-Beta-Interface-PR14765-2070e9a.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlilaseguinolaza** [comment]
I'm seeing with this, if I create a marketplace item which is not for sale, the original creator can get a "Free artist's stock to inventory" and then if that user gifts it to another use, that new user can click the picture of the item in Inventory and can also get Free artist's stock for the same item. 

Also, if a user gifts an item for which there was an update submitted, so the original item is no longer for sale, the user receiving the gifted item can also get Free artist's stock to inventory for that item. Then it will tell that user that an update is available for the Free artist's stock item they just received, but the item will not update successfully. It has UPDATE THIS ITEM FOR FREE  and CONFIRM buttons on the Review page. The Update button does nothing, but the CONFIRM button gets you a new copy of the updated item but the old item is still in Inventory. Then if you try to update the item again, it works normally. User ends up with an extra copy of the updated item.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17322/HighFidelity-Beta-PR14765-490ef35.apk

**Comment by howard-stearns** [comment]
This has been updated for the marketplace-in-qml, and should also address the issues found in previous testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17322/HighFidelity-Beta-PR14765-490ef35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17322/HighFidelity-Beta-Interface-PR14765-490ef35.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17330/HighFidelity-Beta-PR14765-490ef35.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17330/HighFidelity-Beta-PR14765-490ef35.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17330/HighFidelity-Beta-Interface-PR14765-490ef35.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17330/HighFidelity-Beta-PR14765-490ef35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17330/HighFidelity-Beta-Interface-PR14765-490ef35.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17347/HighFidelity-Beta-PR14765-f16eb1c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17347/HighFidelity-Beta-PR14765-f16eb1c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17347/HighFidelity-Beta-Interface-PR14765-f16eb1c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17347/HighFidelity-Beta-PR14765-f16eb1c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17347/HighFidelity-Beta-Interface-PR14765-f16eb1c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17358/HighFidelity-Beta-PR14765-e9b323a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17358/HighFidelity-Beta-PR14765-e9b323a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17358/HighFidelity-Beta-Interface-PR14765-e9b323a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17358/HighFidelity-Beta-PR14765-e9b323a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17358/HighFidelity-Beta-Interface-PR14765-e9b323a.exe

**Pull request merged**
