### PR TITLE
Adding cast shadow control to zones and entities

### PR DESCRIPTION
**Pull request by NissimHadar**
# General
This PR enables content creator control of casting shadows.
# Requirements

1. Master shadow flag defaults to on (Menu->Developer->Graphics...) DONE
2. Add a shadow cast flag to the keylight component of the zone, defaulting to off DONE
3. Do not run shadow task when shadows are not active.
4. Add a shadow cast flag to Entity, dafaulting to on.  Entities will cast shadows iff the master & active zone & entity flags are all active NOT DONE YET
5. Avatars will always cast shadows (provided that the master & the active zone flags are on
# Testing
Tests are defined in: https://highfidelity.testrail.net/index.php?/suites/view/755&group_by=cases:title&group_order=asc

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6999/app_12355_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6999/HighFidelity-Beta-PR12355-a83b3adf690800f26348ccbab50d1ddca561bfb9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6999/HighFidelity-Beta-PR12355-a83b3adf690800f26348ccbab50d1ddca561bfb9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7059/app_12355_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7059/HighFidelity-Beta-PR12355-8fc31e4a8bd226f42e6d8689e065c5e111cc63a3.dmg

**Comment by NissimHadar** [comment]
Cancelled - done new version based on Zvork's

**Pull request closed without merging**
