### PR TITLE
Prevent webviews from reading arbitrary local files

### PR DESCRIPTION
**Pull request by jherico**
RC70 hotfix version of #13650

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11430/HighFidelity-Beta-PR13651-e1fac69.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11430/HighFidelity-Beta-PR13651-e1fac69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11430/HighFidelity-Beta-Interface-PR13651-e1fac69.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11430/HighFidelity-Beta-PR13651-e1fac69.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11430/HighFidelity-Beta-Interface-PR13651-e1fac69.dmg

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @qliacoombs @Qliemillar 

image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11456/HighFidelity-Beta-PR13651-e1fac69.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11456/HighFidelity-Beta-PR13651-e1fac69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11456/HighFidelity-Beta-Interface-PR13651-e1fac69.exe

**Pull request merged**
