### PR TITLE
avoid ambiguous RTT calcs and enable udt fast retransmit

### PR DESCRIPTION
**Pull request by birarda**
https://highfidelity.manuscript.com/f/cases/19553/Add-audio-sniper-solo-feature-to-efficiently-ask-the-mixer-for-one-or-more-specific-sources

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Test in engine-dev with 300 bots and 10% packet loss between your Interface client and the avatar-mixer (using clumsy). With the master avatar mixer, you should see white spheres or t-posed woody avatars for a long period of time when the bots are restarted. You may also see a falsely inflated count of avatars from lost kill packets. With the avatar mixer built from this PR, you should see the white spheres and t-posted woody avatars only for a short period of time. You should also see the number of avatars settle relatively quickly to the right amount.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14551/HighFidelity-Beta-PR14314-41ec026.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14551/HighFidelity-Beta-PR14314-41ec026.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14551/HighFidelity-Beta-Interface-PR14314-41ec026.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14551/HighFidelity-Beta-PR14314-41ec026.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14551/HighFidelity-Beta-Interface-PR14314-41ec026.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
PASS

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14598/HighFidelity-Beta-PR14314-41ec026.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14598/HighFidelity-Beta-PR14314-41ec026.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14598/HighFidelity-Beta-Interface-PR14314-41ec026.exe

**Pull request merged**
