### PR TITLE
Bug fix for avatar neck cauterization

### PR DESCRIPTION
**Pull request by hyperlogic**
The basic dual-quaternion skinning algorithm does not handle non-rigid transformations like scale well.
Because we only use scaling for head cauterization, we special case this by passing in a cauterization factor,
as well as a cauterization position to the vertex shader.  If a vertex is flagged as cauterized, we slam it to equal the cauterization position. Although, not as smooth as the previous method, it seems to work well enough on the avatar's I've tested.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test:
  * Select the Artemis avatar from the marketplace.
  * In desktop mode look down as far as possible.
  * You should only see a small amount of the avatar's chest and neck.   It should not look as bad as the image listed in [Bug 11651](https://highfidelity.fogbugz.com/f/cases/11651/In-first-person-we-see-stretched-out-stuff-on-the-neck)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6624/app_12266_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6624/HighFidelity-Beta-PR12266-faf8350369e26b627a1c6b574cbac2578061bef8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6624/HighFidelity-Beta-PR12266-faf8350369e26b627a1c6b574cbac2578061bef8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6644/app_12266_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6644/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6644/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing for PR#12266. FAILED. Interface crashed when attempting to launch (on Mac only). It launched fine on PC/Windows and there was no cauterization noted.  Tested using Artemis as well as wooden avatar, Matthew, and Priscilla. Testing was performed in both sandbox/home and in hifiqa-rc.

**Comment by hyperlogic** [comment]
This was already QA'ed and Dev approved on the RC63 branch.

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6680/app_12266_PR.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6685/app_12266_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6685/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6685/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.dmg

**Comment by EthanMaasdam** [comment]
Failed - Crashing on Mac platform

**Comment by conklin94122** [comment]
https://github.com/highfidelity/hifi/pull/12289 should fix the mac crash. Once it's merged to RC63, then RC63 merged back into Master, QA will rebuild and retest this PR.

**Comment by hyperlogic** [comment]
the mac crash is unrelated to this PR.  You can retest by setting the the environment variable HIFI_DISABLE_WATCHDOG=1, this will prevent crashes due to the watchdog timing out.

**Comment by conklin94122** [comment]
build this please

**Comment by conklin94122** [comment]
QA, please retest, mac crash should be fixed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6744/app_12266_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6744/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6748/app_12266_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6748/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6748/HighFidelity-Beta-PR12266-43eaa02ef069f560b8fb1d5477b2c132722026da.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed. PASSED.

**Pull request merged**
