### PR TITLE
more correct stats names

### PR DESCRIPTION
**Pull request by AndrewMeadows**
- split "ETRUpdate" out of "physics" stats
- change name of "physics" stat to "simulation"
- change name of "step" stats to "physics"

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
**Test plan:**

**(A)** Enable the following menu items:

Developer --> Timing --> Performance Timer --> Show Timing Details
Developer --> Timing --> Performance Timer --> Expand /update
Developer --> Timing --> Performance Timer --> Expand /simulate  (this is new!)
Developer --> Timing --> Performance Timer --> Expand /physics

**(B)** Click on the debug timing stats to expand the detailed stats.  You should see something like this:
debug-stats-screenshot

The significant changes have been itemized in red:
(1) new `pickManager` and `pointerManager` items in the stats summary
(2) `ETRUpdate` is no longer listed as part of `/idle/update/physics` but is instead in `/idle/update/simuation`
(3) `step/.../.../` stats are now called `/physics/.../.../`

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8830/HighFidelity-Beta-PR12907-a80cf49eb3ed1d4b6c0661851d2ea497ef296aea.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8830/HighFidelity-Beta-Interface-PR12907-a80cf49eb3ed1d4b6c0661851d2ea497ef296aea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8830/HighFidelity-Beta-PR12907-a80cf49eb3ed1d4b6c0661851d2ea497ef296aea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8830/HighFidelity-Beta-Interface-PR12907-a80cf49eb3ed1d4b6c0661851d2ea497ef296aea.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Line in stats now appear and correctly.

**Pull request merged**
