### PR TITLE
include default scripts instead of loading them

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* use Script.include() inside defaultScripts.js instead of Script.load() for performance improvements
* all default script variables are evaluated in local scope to prevent namespace collisions
* localize scope of accidental global variables in default scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a20419f2222df52af16c8805f3858ee7b3118ef available at: https://gist.github.com/a5994be47962fa45567dc5525bae85c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-4a20419.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-4a20419.dmg

**Comment by AndrewMeadows** [comment]
It is more efficient to run multiple JS scripts in a single thread (on a single ScriptEngine instance) rather than each in its own thread (multiple ScriptEngine instances).  The data I was seeing:

% profile calls in ScriptEngine::run() for defaultScripts.js:

(1) using Script.load() = 9.98%

(2) using Script.include() = 5.0%

This was on an i7-5820K @3.3GHz and 16GB RAM.  As I recall the numbers on my i5 test machine with 8GB RAM were 16% and 8.5% respectively.

**Comment by AndrewMeadows** [comment]
To test:

(1) Run defaultScripts.js  --> verify that it is the only script that shows up on the list of "running scripts".  Note that defaultScripts.js starts 19 subscripts:

scripts/system/away.js
scripts/system/controllers/grab.js
scripts/system/controllers/handControllerGrab.js
scripts/system/controllers/handControllerPointer.js
scripts/system/controllers/squeezeHands.js
scripts/system/controllers/teleport.js
scriptstoggleAdvancedMovementForHandControllers.js
scripts/system/dialTone.js
scripts/system/edit.js
scripts/system/firstPersonHMD.js
scripts/system/goto.js
scripts/system/hmd.js
scripts/system/marketplace.js
scripts/system/mod.js
scripts/system/mute.js
scripts/system/notifications.js
scripts/system/progress.js
scripts/system/selectAudioDevice.js
scripts/system/users.js

These scripts should have all loaded without syntax errors (check the logs for errors) and should all work as normal.  Try using a few of the scripts to verify they still behave as expected.

(2) Enable the developer and advanced menu options:
Settings-->Advanced Menus
Settings --> Developer Menus

(3) Look for a custom menu option that is created by defaultScripts.js:

Developer --> Debug defaultScripts.js

(4) Enable the menu option in (3) and reload defaultScripts.js
--> it should load each subscript in its own thread and all 19 subscripts should now be listed
--> look in the logs and look for entries about syntax errors (should not be any)
--> the various subscripts should still work

(5) Disable the menu option in (3) and reload defaultScripts.js
--> it should include all subscripts on its own thread --> only one script shows up as "running" again
--> the various subscripts should still work

(6) Re-enable: Developer --> Debug defaultScripts.js, then logout.

(7) Log back in, and check "running scripts"...
--> on login the debug option in (6) should have been reset so that only one script shows up as running.

**Comment by OmegaHeron** [comment]
Testing Windows 10
Test 1 - Yes, only default scripts js shows in running script list and all expected sub-script functions are present.  No syntax errors seen on load, reload or stop actions.

Test 2 ... 4 Yes - reloading with debug enabled shows each script and no errors seen in log.

Test 5 Yes - back to single defaultScripts in list and all work - no errors in log.

Test 6 ... 7 Yes - upon relog only defaultScripts in list, all sub-scripts active, no log errors and debug option shows unset.

Test 7a - Did step  6 ... 7 and added a reload scripts to yield seeing all scripts listed in running - then relogged.  Still see only defaultScripts running (I wanted to be sure there was no chance of having default with its "tree" of scripts running + individual parts running too.).

Test 8 - Scripts not in defaults that I run.  My 2 scripts I run that are not in defaults continue to load on login (or not if I've terminated) as expected.

QA Pass

That said - I'm not in love with this idea even though it's, from a speed standpoint, a good one.  Perhaps in The Glorious Future when we can have a custom default scripts that isn't overwritten on each interface reinstall...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a2e5667fc942ee217c05e719a61ec28a4607bfb available at: https://gist.github.com/a5994be47962fa45567dc5525bae85c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-1a2e566.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-1a2e566.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0911d2b9dc2fd2ada4b215e78a29447b0070a0e available at: https://gist.github.com/a5994be47962fa45567dc5525bae85c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-a0911d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8515-a0911d2.dmg

**Pull request merged**
