### PR TITLE
Case 20896: Fix continual edit handle translation when moving (RC82)

### PR DESCRIPTION
**Pull request by dback2**
Follow-up fix for https://highfidelity.manuscript.com/f/cases/20896/

Master PR https://github.com/highfidelity/hifi/pull/15367

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18674/HighFidelity-Beta-PR15366-2d2fd0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18674/HighFidelity-Beta-Interface-PR15366-2d2fd0d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18674/HighFidelity-Beta-PR15366-2d2fd0d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18674/HighFidelity-Quest-Beta-PR15366-2d2fd0d.apk)

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18680/HighFidelity-Beta-PR15366-2d2fd0d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18680/HighFidelity-Beta-Interface-PR15366-2d2fd0d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18680/HighFidelity-Beta-PR15366-2d2fd0d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18680/HighFidelity-Beta-Interface-PR15366-2d2fd0d.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18680/HighFidelity-Beta-PR15366-2d2fd0d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18680/HighFidelity-Quest-Beta-PR15366-2d2fd0d.apk)

**Pull request merged**
