### PR TITLE
No more FLat global lighting, always use one of the SPherical harmonics presets

### PR DESCRIPTION
**Pull request by samcake**
Forbid the global ambient lighting to go the simple global value and instead fallback to the first Spherical harmonics preset

Basically no more simple global ambient

### CODE REVIEW

**Comment by samcake** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: edf0ca2b06e4621afc82db46945d8d5c3fcee474 available at: https://gist.github.com/641d3d8b3201c8a896d8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 07a36158e638699fc1e1981b71baa42bc8d6d6e0 available at: https://gist.github.com/641d3d8b3201c8a896d8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74f04c0c8450fe8cff8cd406f3ab4a25ea0e12a3 available at: https://gist.github.com/641d3d8b3201c8a896d8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4545.dmg

**Comment by ZappoMan** [comment]
test on mac and my windows pc... seems fine

**Pull request merged**
