### PR TITLE
Fix crash on shutdown in domain with material

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/17851/Crash-on-shutdown-if-there-s-a-material-in-the-domain

Test plan:
- Go to engine-dev.  Close interface.  You shouldn't crash.
- Go to any domain where you have edit rights.  Make a cube and a material entity with this URL: https://hifi-content.s3.amazonaws.com/samuel/TestMaterialRelative.json.  Set the cube as the parent to the material.  Close interface.  You shouldn't crash.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12400/HighFidelity-Beta-PR13880-98d145d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12400/HighFidelity-Beta-PR13880-98d145d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12400/HighFidelity-Beta-Interface-PR13880-98d145d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12400/HighFidelity-Beta-PR13880-98d145d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12400/HighFidelity-Beta-Interface-PR13880-98d145d.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
Pass @conklin94122

**Pull request merged**
