### PR TITLE
Entity item cleanup

### PR DESCRIPTION
**Pull request by ZappoMan**
doing some cleanup work on EntityItem this is to cleanup the code and prep for having additional properties implemented as first class properties (better grabbing/laser/sitting)

- standardizing the naming for setting/getting properties methods
- removing the old "non-updating" versions of setXXX for many properties that needed the updateXXX() method to correctly mark dirty flags
- renamed all the updateXXX() methods to the standard name of setXXX()
- cleaned up SpatiallyNestable setPostion/Rotation/Velocity/AngurlarVelocity to be setWorldXXX to mirror the setLocalXXX and to remove confusion as to which frame the setXXX was in (it's in World frame)
- fixing some missing withWriteLock() cases

Test Plan:
- This should run a basic smoke test. Focusing on connecting to a server and seeing content, and doing editing. 
- If any test plans that fail in this PR, check the same test plans against latest dev-download... if they fail in both, it's not a QA fail for this PR. If it only fails in this PR, note the test case and consider it a fail.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4665/HighFidelity-Beta-PR11741-baff900839e61c7a207256d53cd767bb1f4b186a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4665/HighFidelity-Beta-PR11741-baff900839e61c7a207256d53cd767bb1f4b186a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4668/HighFidelity-Beta-PR11741-74ceab1e680f70d18084336a0e9332340c49ac4a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4668/HighFidelity-Beta-PR11741-74ceab1e680f70d18084336a0e9332340c49ac4a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5086/HighFidelity-Beta-PR11741-3b77f14f699fce57a9fd9594a7595117f31bbb5a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5086/HighFidelity-Beta-PR11741-3b77f14f699fce57a9fd9594a7595117f31bbb5a.exe

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5108/HighFidelity-Beta-PR11741-3a967ca8952365ed084cfdba2331ff70ec1b0245.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5108/HighFidelity-Beta-PR11741-3a967ca8952365ed084cfdba2331ff70ec1b0245.dmg

**Comment by YuppyPlays** [comment]
Testing complete:

This should run a basic smoke test. Focusing on connecting to a server and seeing content, and doing editing. **Check, also I'd like to note surprisingly this seemed to load better going to dev-welcome than master has been recently, not sure if part of this PR or pure coincidence**
If any test plans that fail in this PR, check the same test plans against latest dev-download... if they fail in both, it's not a QA fail for this PR. If it only fails in this PR, note the test case and consider it a fail. **No PR specific issues found.**

**Pass**

**Pull request merged**
