### PR TITLE
Fix move after import

### PR DESCRIPTION
**Pull request by sethalves**
- fix movement of hierarchical entity structures when parents and children are both in the selection

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open CREATE
- import http://mpassets.highfidelity.com/a567337a-7bba-462a-b07e-feeeca26a284-v1/piano.json
- without changing the selection, grab an affordance and translate the piano vigorously
- also vigorously rotate the piano
- observe that the keys stay in place, relative to the piano base
- also try this with http://mpassets.highfidelity.com/3809f3ac-a842-43a2-af62-acfadbb72c7c-v1/mirror%20with%20handle.json

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/13715/Complex-multi-piece-parent-child-hierarchies-children-lose-accurate-position

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8450/HighFidelity-Beta-PR12770-249a97b5d0e474f3197c17d263910bbbdf3104ce.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8450/HighFidelity-Beta-PR12770-249a97b5d0e474f3197c17d263910bbbdf3104ce.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Vigorous rotation and translation of both the piano and mirror did not cause any parts to dislodge or otherwise behave incorrectly.

**Pull request merged**
