### PR TITLE
Remove entity highlighting

### PR DESCRIPTION
**Pull request by danteruiz**
This PR remove entity highlighting ability.

Ticket - https://highfidelity.fogbugz.com/f/cases/19652/remove-the-grab-highlight

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- Entity highlighting should not happen when you near and far grab, grab with the mouse and try to equip an entity.

- For sanity check, make sure all grab modules work as before.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15264/HighFidelity-Beta-PR14429-d6fbcb1.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15264/HighFidelity-Beta-PR14429-d6fbcb1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15264/HighFidelity-Beta-Interface-PR14429-d6fbcb1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15264/HighFidelity-Beta-PR14429-d6fbcb1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15264/HighFidelity-Beta-Interface-PR14429-d6fbcb1.dmg

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15433/HighFidelity-Beta-PR14429-d6fbcb1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15433/HighFidelity-Beta-PR14429-d6fbcb1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15433/HighFidelity-Beta-Interface-PR14429-d6fbcb1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15433/HighFidelity-Beta-PR14429-d6fbcb1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15433/HighFidelity-Beta-Interface-PR14429-d6fbcb1.exe

**Pull request merged**
