### PR TITLE
RC-57: adjust tone mapping curve for 2nd camera for the mirror use case

### PR DESCRIPTION
**Pull request by samcake**
This PR adjust the curve of the tone mapping for the 2nd camera pipeline to avoid the over exposure rendering bug.

## TEST PLAN
Using the spectator camera, verify that:

With this PR, the rendering of the 2ndary camera displayed as an Overlay3DImage is now correctly displayed regarding the color space.
The colors of the 2ndary camera rendered image in world are the same as observed from the main viewport (desktop or HMD)

With current RC-57 or Master, these images generated from the 2ndary camera are rendering with an incorrect gamma correction.

In empty, the mirror of the store shows the effect:
in current RC-57:
image

in this PR
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4268/HighFidelity-Beta-PR11630-8d4616edbabd6a3ee8c2cfac760f7191a2c8d4af.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4268/HighFidelity-Beta-PR11630-8d4616edbabd6a3ee8c2cfac760f7191a2c8d4af.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
@samcake: I need access to the `empty` domain in order to confirm the gamma change. On hold for now.

**Comment by samcake** [comment]
We are going to not do a hotfix against rc-57 and instead fix it in Master branch
Thanks

**Pull request closed without merging**
