### PR TITLE
Use HMD roll angle to turn while flying or walking in HMD

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This PR makes you turn while walking or flying in the HMD depending on the amount your roll your head; this instead of turning per where you're looking.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing:

This PR makes you turn while walking or flying in the HMD depending on the amount your roll your head; this instead of turning per where you're looking.

When Interface starts up, HMD roll control is enabled by default.

Stationary: rolling head has no effect.

Walking forwards/backwards in HMD:
- Rolling your head changes your direction.
- The more you roll yoru head the faster you turn.

Flying forwards/backwards in HMD:
- Rolling your head changes your direction.
- The more you roll yoru head the faster you turn.
- You can still fly up/down per your head pitch.


Notes:

The following JavaScript API object properties are provided to control this:
- MyAvatar.useHMDRollControl boolean
- MyAvatar.rollControlDeadZone number - degrees
- MyAvatar.rollControlSpeed number - degrees/second/degree

The following developer scripts are provided to enable/disable and tweak dead zone and turn speed.
- hmdRollControlEnable.js: Use HMD roll to control avatar turning.
- hmdRollControlDisable.js: Revert to use HMD yaw to control avatar turning.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/348/HighFidelity-Beta-PR10603-3fe62475d1d172795f9fd5b1128d3a3c77d62338.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/348/HighFidelity-Beta-PR10603-3fe62475d1d172795f9fd5b1128d3a3c77d62338.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
**"Walking forwards/backwards in HMD:"**

"Rolling your head changes your direction."
**Pass**
"The more you roll yoru head the faster you turn."
**Pass**


**"Flying forwards/backwards in HMD:"**

"Rolling your head changes your direction."
**Pass**
"The more you roll yoru head the faster you turn."
**Pass**
"You can still fly up/down per your head pitch."
**Fail** - the up down pitch seems to be messed up and sending me in all kinds of directions whenever I change my heads pitch up/down.

Please let me know if there is anything else I can do/provide to help :)

**Comment by ctrlaltdavid** [comment]
@YuppyPlays How far up/down are you pitching your head? Just a little up/down and you fly along and a little up/down? Or are looking vertically up/down, and if so how does that compare with the latest dev build?

**Comment by YuppyPlays** [comment]
@ctrlaltdavid - I was tilting my head ever so slightly up and down, when I for example look slightly down it sends me flying backwards and up and backwards and down when looking slightly up, was hard to tell as it seemed erratic.

Comparing to the dev build which I don't believe had the roll features, it definitely doesn't work very well for flying so far in my opinion. For flying specifically I personally prefer just looking left or right to turn as it did before.

Hope this helps.

**Comment by ctrlaltdavid** [comment]
@YuppyPlays I haven't managed to reproduce the problem.
- Are you using your keyboard or hand controllers to fly?
- If using hand controllers, check that Settings > Advanced Movement for Hand Controllers is the same on both your PR test and dev test when comparing.
- If Advanced Movement for Hand Controllers is enabled, the left joystick button it forwards/backwards while the right joystick button is up/down.

**Comment by YuppyPlays** [comment]
@ctrlaltdavid 

Just ran the game again to have a look again, same general results my end.

"Are you using your keyboard or hand controllers to fly?"
** hand controllers [Vive]
"If using hand controllers, check that Settings > Advanced Movement for Hand Controllers is the same on both your PR test and dev test when comparing."
**Same on both (using Advanced Movement)**
"If Advanced Movement for Hand Controllers is enabled, the left joystick button it forwards/backwards while the right joystick button is up/down."
**Correct**

The issue like I said seems to be erratic when flying around and gaining/losing momentum, the best I can describe it is at random when i'm using the Forward button on touchpad [left hand] and flying across an area, if I ever so slightly tip my head down or up in direction at random it appears to either stop me mid-flight, send me backward, etc...

I can try to make a video recording my screen + First person of the controllers so you can see what I'm pressing etc? ..

**Comment by ctrlaltdavid** [comment]
@YuppyPlays Thanks for the further description. I've managed to reliably reproduce one problematic behaviour, which might be part of what you're seeing. I'll sort out a fix for it.
One other thing you might be encountering is avatar collisions with invisible entities. If  you disable Avatar > Enable Avatar Collisions this will stop any of these for the purposes of testing.

**Comment by PhilipRosedale** [comment]
@ctrlaltdavid My testing results:  

When walking, the rate of turn per roll range seems much too high.  Maybe diminish by a factor of 2 or 3.  I think at that rate it is easy to be nauseating.  

When flying yeah I was seeing the same problems - sudden abrupt change in altitude that didn't seem to make sense.

**Comment by ctrlaltdavid** [comment]
I've fixed the change-in-altitude-with-turning problem but have found some other problems which make operation seem a bit haphazard and in some cases stomach-churning.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/401/HighFidelity-Beta-PR10603-b4fe13231d3ceaa56d872cfd20db40805e571792.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/401/HighFidelity-Beta-PR10603-b4fe13231d3ceaa56d872cfd20db40805e571792.dmg

**Comment by ctrlaltdavid** [comment]
Rewrite in placement PR: https://github.com/highfidelity/hifi/pull/10617

**Pull request closed without merging**
