### PR TITLE
Make sure sort indicator is attached to the right of title

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.manuscript.com/f/cases/12522/Sorting-on-the-People-tab-under-Nearby-causes-improperly-overlaid-sort-arrows

Test plan:
- Open People app
- Make sure sort indicators does not overlap table's title

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7467/app_12489_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7467/HighFidelity-Beta-PR12489-b8102cfbd72e3323d35351670c8e5f901cb11c42.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7467/HighFidelity-Beta-PR12489-b8102cfbd72e3323d35351670c8e5f901cb11c42.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass

However, the sort arrow for the Names column is now behind the question mark that opens the display names dialog. In addition, the S in Silence is now cut in half. 

arrows
@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7497/app_12489_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7497/HighFidelity-Beta-PR12489-62f2ba0dadb6acf852966af445a1bd0f2ba04b2c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7497/HighFidelity-Beta-PR12489-62f2ba0dadb6acf852966af445a1bd0f2ba04b2c.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Checked all of the sort filters, none cause any overlaps and all work smoothly!

**Pull request merged**
