### PR TITLE
avoid div by zero when measuring RigidBody effective acceleration

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9638/app_13138_PR_b8d34f4b8fee9f754f7312f6351bc347db31ba85.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9638/HighFidelity-Beta-PR13138-b8d34f4b8fee9f754f7312f6351bc347db31ba85.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9638/HighFidelity-Beta-Interface-PR13138-b8d34f4b8fee9f754f7312f6351bc347db31ba85.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9638/HighFidelity-Beta-PR13138-b8d34f4b8fee9f754f7312f6351bc347db31ba85.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9638/HighFidelity-Beta-Interface-PR13138-b8d34f4b8fee9f754f7312f6351bc347db31ba85.exe

**Comment by samcake** [comment]
Can we ENgineering Team QA test and validate that it s good to go ?

**Comment by AndrewMeadows** [comment]
There is a **TEST PLAN** above.  The **asan** _warning_ should be fixed but the actual _problem_ that might have been introduced by the thing asan was warning about is so obscure and inconsequential that it is hard to test for.  I would describe it as follows:

"It was possible that for entities with linear **damping = 1.0**... that they might NOT correctly receive script collision events."

My take is: if **damping = 1.0** entities receive collision events in this PR going forward (as per the **TEST PLAN**) then PASS it.

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
