### PR TITLE
Don't manually highlight tablet buttons from swipeview.

### PR DESCRIPTION
**Pull request by druiz17**
Tablet button set the highlight mode themselves, so there is no reason for the tabletHome.qml to be manually setting the button highlighting.

Ticket - https://highfidelity.fogbugz.com/f/cases/11546/HMD-Multiple-tablet-buttons-become-highlighted-when-tablet-page-scrolls

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1. Open the tablet
2. Push and hold the seek laser on an app button
3. In a quick motion, "flick" the page of the tablet upward causing all the app to appear to cycle from the bottom
4. Move seek laser over different application buttons on the tablet page
5. Only one button should highlight at a time.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6581/app_12250_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6582/app_12250_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6582/HighFidelity-Beta-PR12250-c73c0487a09938c925493b406340311e4096c0a8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6582/HighFidelity-Beta-PR12250-c73c0487a09938c925493b406340311e4096c0a8.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
button highlight

Failed. Multiple buttons still highlighting.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6615/app_12250_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6615/HighFidelity-Beta-PR12250-f3e20e72cb51f032ef024c9dbbbf339b2f72d761.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6615/HighFidelity-Beta-PR12250-f3e20e72cb51f032ef024c9dbbbf339b2f72d761.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
button highlight

Failed. Multiple buttons still highlighting.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6643/app_12250_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6643/HighFidelity-Beta-PR12250-be42f0cfb1c4d66aba476ee040000104a1850b95.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6643/HighFidelity-Beta-PR12250-be42f0cfb1c4d66aba476ee040000104a1850b95.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
