### PR TITLE
Fix dde visibility

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/7789/Settings-Menus-Do-not-Update

Test plan:
- Enable Developer menus
- On tablet/toolbar, go to Menu > Developer > Avatar > Face Tracking. Notice that "Use Camera" is selected and has the options {"Binary Eyelid Control", "Couple Eyelids", "Use Audio for Mouth"... etc.}
- Select "None"
- Close the dialog or go home on tablet and close the tablet.
- Go to Menu > Developer > Avatar > Face Tracking 
- Select "Use Camera". 
- Make sure that the settings for "Use Camera" appears

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3567/HighFidelity-Beta-PR11442-5aab9bf5b0f283253e27cea4725a317621db56ea.exe

**Comment by anshuman64** [comment]
test this please

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Enable Developer menus | Pass
On tablet/toolbar, go to Menu > Developer > Avatar > Face Tracking. Notice that "Use Camera" is selected and has the options {"Binary Eyelid Control", "Couple Eyelids", "Use Audio for Mouth"... etc.} | Pass
Select "None" | Pass
Close the dialog or go home on tablet and close the tablet. | Pass
Go to Menu > Developer > Avatar > Face Tracking | Pass
Select "Use Camera". | Pass
Make sure that the settings for "Use Camera" appears | Pass

Image | Image
-- | --
c88ad852-4e20-4bfc-b86d-a153165f4816 | 936fd18f-1faa-4e3e-bd33-be229b075558

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3592/HighFidelity-Beta-PR11442-5aab9bf5b0f283253e27cea4725a317621db56ea.dmg

**Comment by anshuman64** [comment]
@cain-kilgore Can you re-test using toolbar/tablet Menu instead of the menus on the top of Interface?

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3600/HighFidelity-Beta-PR11442-5aab9bf5b0f283253e27cea4725a317621db56ea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3600/HighFidelity-Beta-PR11442-5aab9bf5b0f283253e27cea4725a317621db56ea.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
## Test Failed

The menu options appear when Use Camera is selected - however it doesn't look like there's a check to see if you've 'unchecked' the currently selected option (None or 'Use Camera') - resulting in a scenario like this. (Note: Doesn't happen on the Toolbar/Menu Bar - just the Tablet)

04dee5aa-2702-496a-971a-94ab310c3f49

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by vladest** [comment]
Ok, the problem here is that check boxes used as radio buttons which is against its purpose
@anshuman64 please check this in terms of use radio buttons there or even switch

**Comment by vladest** [comment]
@cain-kilgore does it works if you switch between None<->Use camera?

**Comment by cain-kilgore** [comment]
@vladest: Yup - same functionality. Just the whole checkbox thing needs to either be switched to Radio Boxes or you could probably do some trickery in the code.

**Comment by vladest** [comment]
ok, then, basically the issue is solved, but need to create another issue how to correctly handle radio buttons functionality in menus

**Pull request merged**
