### PR TITLE
PAL Visual Style Updates

### PR DESCRIPTION
**Pull request by zfox23**
Prettify the PAL UI! A few known issues:
- The popup text that appears when clicking "[?]" is placeholder text.
- VU meters don't work.
- User portraits are hard-coded as generic portraits.
- **"MUTE" does nothing!** Personal muting is not currently implemented.
- "ADMIN SILENCE" doesn't work on scripted agents.

Enjoy!

### CODE REVIEW

**Comment by zfox23** [comment]
Here's a screenshot of the new styling:

capture

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1eea3ed27d5ad7c176d64ff3c33934dc209c6fe3 available at: https://gist.github.com/fc782d2b299af929635febee004fbe59<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9253-1eea3ed.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9253-1eea3ed.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c51d47ae437b711798a85bf89a8489fd08ef228 available at: https://gist.github.com/fc782d2b299af929635febee004fbe59<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9253-7c51d47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9253-7c51d47.dmg

**Comment by zfox23** [comment]
[pretty pal display](https://trello.com/c/PCA7osRR/37-pretty-pal-display)

**Pull request merged**
