### PR TITLE
Fix copyAddress/copyPath (RC69.1)

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix duplicated from #13559 

**Test Plan**
For copying address in using the menu:

Launch Interface (in Desktop Mode)
- Go to any domain
- In menu, click `Navigate > Copy Address To Clipboard`
- Paste copied address somewhere (should not crash)
- Go to another, different domain
- In menu, click `Navigate > Copy Address To Clipboard`
- Paste copied address somewhere (should not crash and should be different from previously pasted result)

For copying path in using the menu:

- Launch Interface (in Desktop Mode)
- Go to any domain
- In menu, click `Navigate > Copy Path To Clipboard`
- Paste copied path somewhere (should not crash)
- Move around in the domain
- In menu, click `Navigate > Copy Path To Clipboard`
- Paste copied path somewhere (should not crash and should be different from previously pasted result)

For `location.copyAddress()`:

- Launch Interface (in Desktop Mode)
- Enable developer menus by clicking `Settings > Developer Menu`
- Open Console in `Developer > Console...`
- Go to any domain
- In Console, type `location.copyAddress()`
- Paste copied address somewhere (should not crash)
- Go to another, different domain
- In Console, type `location.copyAddress()`
- Paste copied address somewhere (should not crash and should be different from previously pasted result)

For `location.copyPath()`:

- Launch Interface (in Desktop Mode)
- Enable developer menus by clicking `Settings > Developer Menu`
- Open Console in `Developer > Console...`
- Go to any domain
- In menu, click `location.copyPath()`
- Paste copied path somewhere (should not crash)
- Move around in the domain
- In menu, click `location.copyPath()`
- Paste copied path somewhere (should not crash and should be different from previously pasted result)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11191/HighFidelity-Beta-PR13562-be8979f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11191/HighFidelity-Beta-PR13562-be8979f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11191/HighFidelity-Beta-Interface-PR13562-be8979f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11191/HighFidelity-Beta-PR13562-be8979f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11191/HighFidelity-Beta-Interface-PR13562-be8979f.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Path and address can be copied and used without crashing.

**Pull request merged**
