### PR TITLE
Revert "HOTFIX version of PR 12969: Attempt to shutdown web surfaces more consistently"

### PR DESCRIPTION
**Pull request by jherico**
Reverts highfidelity/hifi#12983

It looks like the change is causing worse behavior, with crashing occurring frequently while loading domains

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9161/app_12993_PR_ea0ef20416d44932a21421bd7be8d50a0e0b5424.apk

**Comment by samcake** [comment]
THis PR is there in case we need it as we are closing on RC66.1
If we can find a fix for the problem without reverting the work done in 12983 we will.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9161/HighFidelity-Beta-PR12993-ea0ef20416d44932a21421bd7be8d50a0e0b5424.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9161/HighFidelity-Beta-Interface-PR12993-ea0ef20416d44932a21421bd7be8d50a0e0b5424.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9161/HighFidelity-Beta-PR12993-ea0ef20416d44932a21421bd7be8d50a0e0b5424.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9161/HighFidelity-Beta-Interface-PR12993-ea0ef20416d44932a21421bd7be8d50a0e0b5424.exe

**Comment by conklin94122** [comment]
Removing DO NOT MERGE per @samcake

**Pull request merged**
