### PR TITLE
(case 21076) Fix missing normal textures on models (RC80)

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.manuscript.com/f/cases/21076/Models-are-missing-normal-textures-RC80

This PR fixes normal textures missing on models due to missing tangent space. It is the same PR as the RC79 PR https://github.com/highfidelity/hifi/pull/14872, but targeted toward master.

## TEST PLAN
- Run this test:
    - https://github.com/sabrina-shanman/hifi_tests/tree/bug_no-normal-textures/tests/content/entity/model/modelBaking/normal_texture
    - This should show a cube model consisting of a grey design on a white background. If you see just a white cube, then normal textures are not rendering, which counts as a fail.

### CODE REVIEW

**Comment by sabrina-shanman** [comment]
Build this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17130/HighFidelity-Beta-PR14874-ef529ed.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17130/HighFidelity-Beta-PR14874-ef529ed.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17130/HighFidelity-Beta-Interface-PR14874-ef529ed.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
