### PR TITLE
Fix loud screeching sound when certain users join a domain

### PR DESCRIPTION
**Pull request by kencooke**
For months now, when certain users enter a domain with a hot mic, loud audio artifacts are heard by all users in the domain. This appears to be caused by quirks in the codec negotiation protocol, which on a slow machine can result in bursts of codec resets and dropped audio during audio codec startup. Hopefully fixed in this PR.

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

1) With both the client and server from this PR, enable "Server Echo" in the audio menu and repeatedly join your local domain while already talking into the mic. You should not hear any loud screeching upon connect.

2) Go to dev-welcome and verify that mic audio still works as expected.

3) [OPTIONAL] If someone who was previously causing the "screeching noise" upon connect could test Interface from this PR, that would be extremely helpful.

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4177/HighFidelity-Beta-PR11602-bd82f47c66dfc67e29201abab1e3838a25a31a7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4177/HighFidelity-Beta-PR11602-bd82f47c66dfc67e29201abab1e3838a25a31a7a.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
With both the client and server from this PR, enable "Server Echo" in the audio menu and repeatedly join your local domain while already talking into the mic. You should not hear any loud screeching upon connect. | Pass
Go to dev-welcome and verify that mic audio still works as expected. | Pass

Everything seems to be okay, wasn't able to reproduce the screeching sound from the Mics. Tried with 3.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
