### PR TITLE
Fix Web entities

### PR DESCRIPTION
**Pull request by Atlante45**
This fixes web entities dimensions being wrong as well as being culled from the back.
I also made them emissive so that they are not affected by lighting and look bright like a screen (done the same thing for text entities)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d02c69111b97966aa463f2aa2bf1e4cda8c3230e available at: https://gist.github.com/e008270b1085e254e2e6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d02c69111b97966aa463f2aa2bf1e4cda8c3230e available at: https://gist.github.com/d3671eafa87918c1d79b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d02c69111b97966aa463f2aa2bf1e4cda8c3230e available at: https://gist.github.com/d3671eafa87918c1d79b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d02c69111b97966aa463f2aa2bf1e4cda8c3230e available at: https://gist.github.com/d3671eafa87918c1d79b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d02c69111b97966aa463f2aa2bf1e4cda8c3230e available at: https://gist.github.com/d3671eafa87918c1d79b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5221.dmg

**Pull request merged**
