### PR TITLE
DEV-457: Add HIFI_THUNDER_URL to win32 launcher

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21093/HighFidelity-Beta-PR16114-5fe7be4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21093/HighFidelity-Beta-Interface-PR16114-5fe7be4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21093/HighFidelity-Beta-PR16114-5fe7be4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21093/HighFidelity-Quest-Beta-PR16114-5fe7be4.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21093/HighFidelity-Beta-PR16114-5fe7be4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21093/HighFidelity-Beta-Interface-PR16114-5fe7be4.exe

**Pull request merged**
