### PR TITLE
Update OverlayWebWindow keyboard visibility per HMD/desktop mode changes

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
TESTING

Using the following script: http://ctrlaltstudio.com/downloads/hifi/scripts/chat.js
The keyboard should be displayed when the input field at the bottom of the dialog has focus.

Previously:
(a) If you (re)start the script in desktop mode the keyboard is not available at all, not in desktop mode nor if you close the dialog and switch to HMD mode and reopen the dialog.
(b) If you (re)start the script in HMD mode the keyboard is available, both in HNDM mode and in if you close the dialog and switch to desktop mode and reopen the dialog.

With this PR: 
(a) If you (re)start the script in desktop mode the keyboard is not available while in desktop mode, but if you close the dialog and switch to HMD mode and reopen the dialog the keyboard is available.
(b) If you (re)start the script in HMD mode the keyboard is available, but if you close the dialog and switch to desktop mode and reopen the dialog the keyboard is no longer available.

Note: Like other dialogs, the keyboard availability doesn't change between desktop/HMD modes unless you close and reopen the dialog.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34b9d3eeccaf90576e13625432e8a3cbf4950206 available at: https://gist.github.com/c0d8148629330ff92e161155b21f3ac5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8898-34b9d3e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8898-34b9d3e.dmg

**Comment by ZappoMan** [comment]
testing

**Comment by ZappoMan** [comment]
Tested: PASS

**Pull request merged**
