### PR TITLE
DNM: smarter_textures branch for test

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f564f33db2081b435b8945bf69c91c1a9c9f2741 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f564f33.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f564f33.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed7319e41f23445fa1451d7127e25fcff0e83ba5 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-ed7319e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-ed7319e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b2520cbee0071982b9aff8baf26549a23ac26bc available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-2b2520c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-2b2520c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d593f2ba9f3f9e2ad29125c1c1ec0da4dca371c available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-9d593f2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-9d593f2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f20369aa7ae908026b4c88b9523b7582b495711a available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f20369a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f20369a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0848293b658c489cafa5c4191291eb7ed53d979 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f084829.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f084829.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0848293b658c489cafa5c4191291eb7ed53d979 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f084829.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-f084829.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 67d14230c513046f3c6bd79ed078e67414e61e05 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-67d1423.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-67d1423.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9843b68878c926f46c055e1cb5d94317c3a07189 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-9843b68.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-9843b68.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0f0cc2102094d0e53e62721b7e3703f85c988e7 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-e0f0cc2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-e0f0cc2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 900615fcd5ac071eed64046c16c3f496786390d1 available at: https://gist.github.com/4c20dbb60391bb12cf9207d86a395167<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-900615f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9742-900615f.dmg

**Pull request closed without merging**
