### PR TITLE
Don't trigger entity scripts without scripting interface

### PR DESCRIPTION
**Pull request by jherico**
An entity scripting interface doesn't have to be set on the entity tree, but the tree assumes one exists anyway instead of checking for it's presence.  I'm currently working on a stripped down app that uses the entity tree for rendering, but does no networking, physics or scripting.  Attempting to load entities which reference scripts in this app will crash as is, but this PR will allow an entity tree to be used without any scripting.

### CODE REVIEW

**Comment by jherico** [comment]
## Testing

This PR should have no impact on the application, since the application always has a scripting interface attached to it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 82eb406d3e2b8fcb13fdd65961cc60b090eb7831 available at: https://gist.github.com/5e958466f12dd46e3ca0366bbe965d6c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5220b52cd9de0e8ebcd957b7829c2cda7d5c64cb available at: https://gist.github.com/5e958466f12dd46e3ca0366bbe965d6c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5220b52cd9de0e8ebcd957b7829c2cda7d5c64cb available at: https://gist.github.com/5e958466f12dd46e3ca0366bbe965d6c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8189.dmg

**Pull request merged**
