### PR TITLE
Improve font loading via QRC instead of file path

### PR DESCRIPTION
**Pull request by zfox23**
Load fonts via QRC instead of by file path. Enables the external use of HiFi's UIT text-based QML `Item`s such as `RalewaySemiBold.qml`.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. This one's simple! Open up various QML apps from within Interface in both HMD and Desktop. Verify that all of the text you see isn't garbled nonsense or visually corrupted. Examples of QML apps include Wallet, GOTO, and Spectator Camera.

If you see this (or something like it), fail this PR:
image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7663/app_12543_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7663/HighFidelity-Beta-PR12543-877fa5203444b111a8db77d307701afc99509e53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7663/HighFidelity-Beta-PR12543-877fa5203444b111a8db77d307701afc99509e53.exe

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7679/app_12543_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7679/HighFidelity-Beta-PR12543-877fa5203444b111a8db77d307701afc99509e53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7679/HighFidelity-Beta-PR12543-877fa5203444b111a8db77d307701afc99509e53.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
