### PR TITLE
refactor system html to split js/css

### PR DESCRIPTION
**Pull request by zzmp**
- create new folder in scripts/system/html for js
- move all system css to scripts/system/html/css
- move all (previously inlined) system js to scripts/system/html/js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30e26f8895fc3e1e2e473ad6afed044d31230789 available at: https://gist.github.com/4ad1ced0dacb0aa86ccb8b176a6e4ae3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8398-30e26f8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8398-30e26f8.dmg

**Comment by zzmp** [comment]
QA, please make sure that edit.js still functions and renders pretty.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5b822ddbe50fad78a2d17f086f75291e086e8a9 available at: https://gist.github.com/4ad1ced0dacb0aa86ccb8b176a6e4ae3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8398-d5b822d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8398-d5b822d.dmg

**Comment by Nex-Pro** [comment]
**PASS**

Edit JS seems to look and work fine. And having the css in one place is great. Many thanks @zzmp

**Pull request merged**
