### PR TITLE
Tablet pagination magnify

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/6617/Dynamic-Magnification-of-Buttons

Test plan:
- Open tablet
- move mouse over tablet
- Tablet's button over mouse cursor must be magnified, the rest buttons must be minified

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6016/app_12097_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6016/HighFidelity-Beta-PR12097-02972c92f045399d5b3f9a7714277f29cb505129.dmg

**Comment by luiscuenca** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6020/app_12097_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6020/HighFidelity-Beta-PR12097-02972c92f045399d5b3f9a7714277f29cb505129.exe

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6032/app_12097_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6032/HighFidelity-Beta-PR12097-02972c92f045399d5b3f9a7714277f29cb505129.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6032/HighFidelity-Beta-PR12097-02972c92f045399d5b3f9a7714277f29cb505129.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASSED @conklin94122

**Pull request merged**
