### PR TITLE
Mac Sixense/Oculus init_hid fix

### PR DESCRIPTION
**Pull request by SamGondelman**
NOTE: this is for the plugins branch, not master

In order to run without crashing:

- Run without rift attached.
- Turn off Sixense input device.
- Rerun with Rift attached

If you want to use the hydra with the Rift, do the above and then:
- Detach Rift while running.
- Enable Sixense input device.
- Switch to Oculus display mode.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1af51572afef365edbf0c94d2dbed12c4b435501 available at: https://gist.github.com/316bc2aab89045639a98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f801471dd70302dbd6364a3883588fd33b2801fd available at: https://gist.github.com/316bc2aab89045639a98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.dmg

**Comment by ZappoMan** [comment]
You forgot to mention the step where you shake a chicken bone over your head.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0aee95fe38a3d5e5ec2e1f3479139d6f18969842 available at: https://gist.github.com/316bc2aab89045639a98<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5429.dmg

**Comment by SamGondelman** [comment]
That's only necessary on linux (but if it's a turkey bone it'll improve your framerate drastically on windows).

**Pull request merged**
