### PR TITLE
Update serverless content to v2

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10345/HighFidelity-Beta-PR13296-ecd1194.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10345/HighFidelity-Beta-PR13296-ecd1194.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10345/HighFidelity-Beta-Interface-PR13296-ecd1194.dmg

**Comment by huffman** [comment]
To test:

 * Ensure that https://highfidelity.manuscript.com/f/cases/15560 is fixed
 * Testrail C15034
 * Testrail C14495 or C15035 (depending on what you have available)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10345/HighFidelity-Beta-PR13296-ecd1194.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10345/HighFidelity-Beta-Interface-PR13296-ecd1194.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Advanced movement sign is still not visible. Selecting the sign does now change controls. Basic Serverless tutorial tests with desktop and HMD pass as expected.
Video of advanced movement sign attached.
[Files.zip](https://github.com/highfidelity/hifi/files/2073241/Files.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10358/HighFidelity-Beta-PR13296-f87775c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10358/HighFidelity-Beta-PR13296-f87775c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10358/HighFidelity-Beta-Interface-PR13296-f87775c.dmg

**Comment by huffman** [comment]
@qlimnavarro this is ready again once it builds

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10358/HighFidelity-Beta-PR13296-f87775c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10358/HighFidelity-Beta-Interface-PR13296-f87775c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Sign is now visible and previous basic test pass again as well.

**Pull request merged**
