### PR TITLE
Fix MS16235: Set previously-buggy Handshake particle properties to 0

### PR DESCRIPTION
**Pull request by zfox23**
Fix [MS16235](https://highfidelity.manuscript.com/f/cases/16235/Handshake-particle-effect-is-wrong-after-recent-particle-system-changes).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
###
1. Connect to a domain. Have another avatar join that same domain. Attempt a handshake (VR or desktop mode; doesn't matter).
    - Verify that the handshake particle effect looks the same as in the currently-public beta build (i.e. from Steam).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10913/HighFidelity-Beta-PR13474-6f956ff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10913/HighFidelity-Beta-PR13474-6f956ff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10913/HighFidelity-Beta-Interface-PR13474-6f956ff.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Particles on Handshake look as expected.

**Pull request merged**
