### PR TITLE
Fix Quat.lookAt

### PR DESCRIPTION
**Pull request by howard-stearns**
Was returning inverse rotation.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/85298210681722

**Comment by howard-stearns** [comment]
testing notes: the correctedTestQuatLookAt.js attached to the asana ticket should end in "true" for each checkMumble line.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80baa5ce18af315cd6618d09e0e7e91f4877acc8 available at: https://gist.github.com/67deadd2814d61bd6858<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7096.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7096.dmg

**Comment by OmegaHeron** [comment]
Tested against production build 4190 on Windows 7.  Production build returns mixture of True/False results - this PR returns True for all.

**Pull request merged**
