### PR TITLE
Fix Interface eating memory when minimized

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Reproduce the problem on a non-PR build.
- Recent dev build.
- Windows, desktop mode.
- Open Windows' Task Manager with the "Processes" tab displayed.
- Arrange Interface and Task Manager windows so that you can see both.
- Wait for the domain and avatar content to finish loading, and the amount of Memory that Interface uses to stabilize.
- Minimize the Interface Window.
- Wait half a minute and notice the amount of memory that Interface uses is increasing.
- Wait a couple of minutes and note that the amount of memory that Interface uses keeps increasing without limit.
- Restore the Interface Window so that it is displayed again.
- The Interface Window will appear to be frozen while the amount of memory Interface uses decreases to around what it was before, then Interface resumes working.

2) Test the PR build.
- The amount of RAM that Interface uses should not increase while Interface is minimized.
- Interface should work immediately it is restored from minimized to visible.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14429/HighFidelity-Beta-PR14286-1cca975.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14429/HighFidelity-Beta-PR14286-1cca975.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14429/HighFidelity-Beta-Interface-PR14286-1cca975.dmg

**Comment by qliejahner** [comment]
PASS @conklin94122 

Unlike master, the interface did not take more memory and was responsive as soon as it had focus

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14458/HighFidelity-Beta-PR14286-1cca975.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14458/HighFidelity-Beta-PR14286-1cca975.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14458/HighFidelity-Beta-Interface-PR14286-1cca975.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14458/HighFidelity-Beta-PR14286-1cca975.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14458/HighFidelity-Beta-Interface-PR14286-1cca975.exe

**Pull request merged**
