### PR TITLE
use default avatar when avatar-url is bogus

### PR DESCRIPTION
**Pull request by sethalves**
- when someone sets their avatar url to something invalid, use the default avatar for them.
- when an avatar's head position cannot be determined (due to invalid model), use avatar's base position

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- log two avatars in and get them facing each other
- on one of the avatars, use the Settings menu to open avatar preferances.
- set the "Appearance" field to something random
- observer that the default avatar is used until the field is set to something usable.

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/533/If-bad-avatar-link-nothing-happens-and-audio-fails-to-work-correctly-need-a-more-elegant-failure-mode-there

**Comment by ZappoMan** [comment]
@sethalves - one possible problem with this -- is that it will cause the ghostly figure to return to the origin of all domains. Here are some questions/suggestions:

1) Not fix this bug this way... but instead figure out why the root problem happens of a bad URL causing the position data to not be sent/processed.
2) Or-- fix this in this way... but then we need to get an "invisible" avatar (one that is valid, but has no meshes) and replace the audio-searcher script to use that invisible avatar.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ed4b0b3589d700b532eb546cca007900826cd7a8 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-ed4b0b3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-ed4b0b3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 229b8d3b5ebd795087729bd336a5cdaa4d25a778 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-229b8d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-229b8d3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 56af36ae64f27eeddf390b1d642341e401228dca available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-56af36a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-56af36a.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 528f417f7442d1c784ce08390bd02b24b4bb4fb5 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-528f417.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-528f417.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 75f9626c2d046773c9e5ff527569db55749fe86f available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-75f9626.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-75f9626.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79121133dfc6e7528d8de0c91fe42ed20ccc4991 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-7912113.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-7912113.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 363915b836e3a327231ffed1ae859fa8a5fa6234 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-363915b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-363915b.dmg

**Comment by RyanDowne** [comment]
I think this is an edge case but when demoing remotely and not connected to a network, no avatar is visible. We might also want to include the robot avatar in the download and display that when the url is bad or there is no network connection and one is just on localhost.

**Comment by sethalves** [comment]
This code reacts to any sort of failure to download the avatar.  I haven't tried it, but I would expect everyone to end up as the being of light when running on a private network.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b48d4f6d2db90832256a019b3c5413a98ba8c72b available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-b48d4f6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-b48d4f6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad4fc8c656cb43e961f9ef9a5b48873153564bdb available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-ad4fc8c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-ad4fc8c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c743cf379ee23367924adaabf01f2e5c93b9965d available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-c743cf3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-c743cf3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 905c6147cfe01630b09cd3b58a8a0f7f6f0deed8 available at: https://gist.github.com/3df0032198477bc34a0893ad5637426a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-905c614.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8346-905c614.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: SUCCESS
**Additional Test Results + Observations**: Tested with @cozza13 as he was able to switch to default avatar with no issues that I observed.

**Pull request merged**
