### PR TITLE
CR for 20407 - Make Sixense emulate mouse only if controllers aren't at the base

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/5cb6a1a7c72022a71f18<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/5cb6a1a7c72022a71f18<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/5cb6a1a7c72022a71f18<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/5cb6a1a7c72022a71f18<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/5cb6a1a7c72022a71f18<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3de7222007e3431232ee25962156aa6070427c04 available at: https://gist.github.com/363b6cc2e0aac426c177<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4488.dmg

**Comment by Atlante45** [comment]
@murillodigital is this ok to merge?

**Comment by ctrlaltdavid** [comment]
Yes; has been tested; job status is "Code Review".

**Pull request merged**
