### PR TITLE
DEV-2701: Remove the home icon from the profile app

### PR DESCRIPTION
**Pull request by zfox23**
https://highfidelity.atlassian.net/browse/DEV-2701

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22372/HighFidelity-Beta-PR16462-ca8a61f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22372/HighFidelity-Quest-Beta-PR16462-ca8a61f.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22372/HighFidelity-Beta-PR16462-ca8a61f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22372/HighFidelity-Beta-Interface-PR16462-ca8a61f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22372/HighFidelity-Beta-PR16462-ca8a61f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22372/HighFidelity-Beta-Interface-PR16462-ca8a61f.exe

**Pull request merged**
