### PR TITLE
(Experiment) Fixing tablet spawning position when hand is to close to HMD position.

### PR DESCRIPTION
**Pull request by druiz17**
Here is the ticket for this PR https://highfidelity.fogbugz.com/f/cases/6144/Spawn-the-Tablet-at-a-Fixed-Position-Relative-to-Head

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2320/HighFidelity-Beta-PR11134-847bb8d3d649b4c6cab827892e5dfd63fe9cba20.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2320/HighFidelity-Beta-PR11134-847bb8d3d649b4c6cab827892e5dfd63fe9cba20.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2376/HighFidelity-Beta-PR11134-fb8157083ee6987edb0a01c556c567cacc093944.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2376/HighFidelity-Beta-PR11134-fb8157083ee6987edb0a01c556c567cacc093944.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2542/HighFidelity-Beta-PR11134-fb8157083ee6987edb0a01c556c567cacc093944.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2542/HighFidelity-Beta-PR11134-fb8157083ee6987edb0a01c556c567cacc093944.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2585/HighFidelity-Beta-PR11134-d628a6d8195242876139575a2af7f2219d7dd778.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2586/HighFidelity-Beta-PR11134-fb8157083ee6987edb0a01c556c567cacc093944.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2589/HighFidelity-Beta-PR11134-d628a6d8195242876139575a2af7f2219d7dd778.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2589/HighFidelity-Beta-PR11134-d628a6d8195242876139575a2af7f2219d7dd778.exe

**Pull request closed without merging**
