### PR TITLE
Fix MS7224: Add dimensions to printed Snapshot entity

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS7224](https://highfidelity.fogbugz.com/f/cases/7224/My-snapshots-are-cubes-OR-invisible-to-users).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1. Enter into a domain with create permissions and that is "open" (i.e. enterable by anonymous)
2. Using the Snapshot app, take a Still Only Snapshot
3. Press the Print button in the Snap app
4. Verify that the snapshot is not a small cube
5. Move to a new "open" domain
6. Repeat steps 2-4.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10338/HighFidelity-Beta-PR13293-cf7a3d1.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10338/HighFidelity-Beta-PR13293-cf7a3d1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10338/HighFidelity-Beta-Interface-PR13293-cf7a3d1.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Pictures are visible to all users, dimensions are always correct

**Pull request merged**
