### PR TITLE
DNM: Local Audio Bypass

### PR DESCRIPTION
**Pull request by zzmp**
Compiling for testing purposes.
Do not merge.
Do not review.
Do not QA.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3488926a11564c0d46200725228beae0cbfa5e7f available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-3488926.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-3488926.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a3df06f50e98d5888d82d1a747652c45e44dd31d available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-a3df06f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-a3df06f.dmg

**Comment by zzmp** [comment]
44610ea should show legacy behavior.
ecd81c9 should show local audio bypass behavior.

### My results

- *network audio: time (measured on oscilloscope) for a sound to be heard and sounded*
- *local audio: time (measured on oscilloscope) between hitting a key and sounding (note the JS lag)*
- *local audio via network: local audio + observed delay (on oscilloscope) with server echo*

#### Legacy

- network audio: 90ms
- local audio: 110ms
- local audio via network: 190ms

#### Local Audio Bypass

- network audio: 90ms
- local audio: 100ms
- local audio via network: 190ms

---

I'm seeing this as only marginally better than existing code.
It is cleaner in the audio stream, but it forces processing in the audio callback.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44610ea3f1c072789e33086fa0777fe383e479ac available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ecd81c9eeafb447850819e8b8e7a9b2e737d4931 available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ecd81c9eeafb447850819e8b8e7a9b2e737d4931 available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44610ea3f1c072789e33086fa0777fe383e479ac available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 44610ea3f1c072789e33086fa0777fe383e479ac available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-44610ea.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ecd81c9eeafb447850819e8b8e7a9b2e737d4931 available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-ecd81c9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1dcaca3b47b4039ee846d7e9d6aecc4401cf5f8d available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-1dcaca3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-1dcaca3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1f1f55cf22ae1c11f962c82f44afa431d278741 available at: https://gist.github.com/54150652db0b2c97d1d0288584114e0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-a1f1f55.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8679-a1f1f55.dmg

**Pull request closed without merging**
