### PR TITLE
Register the Vive inputDevice if no controllers are available 

### PR DESCRIPTION
**Pull request by druiz17**
If no hand controllers are connected the ViveControllerManager will not register the Input device, will cause  the head pose not being sent even through you are in HMD mode.

This was the issue described in this ticket - https://highfidelity.fogbugz.com/f/cases/9465/With-Vive-and-an-Xbox-controller-the-avatar-and-controls-are-misaligned

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan 
https://highfidelity.testrail.net/index.php?/tests/view/15940

**Comment by Nex-Pro** [comment]
Awaiting win build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5205/HighFidelity-Beta-PR11886-7daad29906d12b4f75178dd746ff0205296b39eb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5205/HighFidelity-Beta-PR11886-7daad29906d12b4f75178dd746ff0205296b39eb.dmg

**Comment by druiz17** [comment]
@Nex-Pro hold off on the testing. I think something in master might have broken the vive in HMD.

**Comment by Nex-Pro** [comment]
OK @druiz17

**Comment by druiz17** [comment]
@Nex-Pro this PR is ready for QA once the next build finishes

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5246/HighFidelity-Beta-PR11886-82fb58ed96b1db89a515e4b53ea4688bc96aab06.dmg

**Comment by Nex-Pro** [comment]
Build this please

**Comment by Nex-Pro** [comment]
@druiz17 Ok awaiting win build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5249/HighFidelity-Beta-PR11886-82fb58ed96b1db89a515e4b53ea4688bc96aab06.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5249/HighFidelity-Beta-PR11886-82fb58ed96b1db89a515e4b53ea4688bc96aab06.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### PASS

@druiz17 Was unable to add a test run. However the test steps matched those I used earlier today.

I was able to use the steps in the linked testrail case.

In addition I tested each step with the default avatar and a human avatar.

No issues seen. Flying control was good enough to be able to fly through the hole in the 'O' in the "your sandbox sign" at local domain.

Walking( actually driving ) forward back, turn with trackpad both ways while driving forward and back. FLying up down forward back and turning with trackpads. Flying only using HMD for turn and climb, descent. All good. Could fly and drive with tablet held in either hand and transfer tablet between hands.
Strafe, strafe and turn all good. Jump ok. Double tap to fly is ok also.

**Pull request merged**
