### PR TITLE
fix for FBX baking with external textures

### PR DESCRIPTION
**Pull request by birarda**
- fixed incorrect references to external textures while baking FBX with Oven

### CODE REVIEW

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1450/HighFidelity-Beta-PR10915-bff54d260e4db966d34bfe32ed517c33bd7ffc2e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1450/HighFidelity-Beta-PR10915-bff54d260e4db966d34bfe32ed517c33bd7ffc2e.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by CainFoool** [comment]
# Test Failed
Test | Result
-------- | --------
(1) Bake a model with embedded textures (http://hifi-public.s3.amazonaws.com/birarda/models/sphere_embedded_texture.fbx). In the results table, once done, click on the name of the model with embedded textures and ensure that the output folder contains a KTX texture. | Pass
(2) Bake a model with external textures (http://hifi-content.s3.amazonaws.com/DomainContent/Welcome%20Area/production/models/nwf_planks_narrow_ne.fbx). In the results table, once done, click on the name of the model with embedded textures and ensure that the output folder contains multiple KTX textures. | Fail

## 2
I got an error message in the console saying: `Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Metallic.png` and it only produced one folder with no additional textures.
explorer_2017-07-07_18-37-56

**Comment by Nex-Pro** [comment]
### PASS

All good If you want the output files I'll send a zip.

**Comment by birarda** [comment]
@CainFoool I updated the URL in the initial post. Would you mind trying again?

Also, if it fails, could you get me the full output log.

**Comment by Nex-Pro** [comment]
@birarda It's a pass

**Comment by CainFoool** [comment]
@birarda:

```
hifi.gpu: [TEXTURE TRANSFER SUPPORT]
        idealThreadCount: 4
        RECOMMENDED enableSparseTextures: false
hifi.shared: Settings file: "C:/Users/Cain/AppData/Roaming/High Fidelity/Oven.json"
hifi.shared: Settings thread started.
hifi.model-baking: Baking QUrl("file:///Users/Cain/Desktop/Oven - July-7-2017/textures/nwf_planks_narrow_ne.fbx")
hifi.model-baking: Creating FBX output folder "C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/"
hifi.model-baking: Imported QUrl("file:///Users/Cain/Desktop/Oven - July-7-2017/textures/nwf_planks_narrow_ne.fbx") to FbxScene
hifi.model-baking: Re-mapping C:/Users/pc/Desktop/scratch/newWoodPlanksNailed/hangarFloor2_Normal_OpenGL.png to C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/hangarFloor2_Normal_OpenGL.ktx
hifi.model-baking: Re-mapping C:/Users/pc/Desktop/scratch/newWoodPlanksNailed/hangarFloor2_Base_Color.png to C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/hangarFloor2_Base_Color.ktx
hifi.model-baking: Re-mapping C:/Users/pc/Desktop/scratch/newWoodPlanksNailed/hangarFloor2_Metallic.png to C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/hangarFloor2_Metallic.ktx
hifi.model-baking: Re-mapping C:/Users/pc/Desktop/scratch/newWoodPlanksNailed/hangarFloor2_Roughness.png to C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/hangarFloor2_Roughness.ktx
hifi.model-baking: Re-mapping C:/Users/pc/Desktop/scratch/newWoodPlanksNailed/hangarFloor2_Ambient_occlusion.png to C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/hangarFloor2_Ambient_occlusion.ktx
hifi.model-baking: Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Normal_OpenGL.png
hifi.model-baking: Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Base_Color.png
hifi.model-baking: Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Metallic.png
hifi.model-baking: Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Roughness.png
hifi.model-baking: Unable to open texture file:///Users/Cain/Desktop/Oven - July-7-2017/textures/hangarFloor2_Ambient_occlusion.png
hifi.model-baking: Exported QUrl("file:///Users/Cain/Desktop/Oven - July-7-2017/textures/nwf_planks_narrow_ne.fbx") with re-written paths to "C:/Users/Cain/Desktop/Oven - July-7-2017/textures/model_output/nwf_planks_narrow_ne/baked/nwf_planks_narrow_ne.baked.fbx"
```

**Comment by birarda** [comment]
@CainFoool please re-attempt using the URL in the model URL field, not a path to the local file. It needs to use the URL so it can find the external textures.

**Comment by CainFoool** [comment]
@birarda All good - "Model File(s)" in the GUI confused me there. Specifying Model File/URL might have saved the confusion.

**Comment by birarda** [comment]
Thanks @Nex-Pro and @CainFoool

**Comment by judasshuffle** [comment]
Great tooI but  had no luck baking a skybox with this, but I could be missunderstanding how to use it. I think it converts a jpeg to a ktx but its hung with the ones i tried

**Comment by birarda** [comment]
@judasshuffle though this tool isn't yet for external use we welcome your testing of it! Skyboxes can take a long time because we pass them through a higher quality compression called BC7. The program may look hung for a while but as long as it's still responding and the progress window still says baking it should be going.

**Comment by judasshuffle** [comment]
I want to use this tool to rebake cromptonmoor domain.I got the json for the domain via thoys so avoid any potential export issues with a large build.Ran it all through the oven which worked apart from 5 things out of 1500. The problem is on importing the json either via the domain server or import the locations and properties of the models are getting changed by the converter.The original jason works fine the converted one it messing up positions and properties.

**Pull request merged**
