### PR TITLE
put DomainServerCheckIn on NodeList thread

### PR DESCRIPTION
**Pull request by howard-stearns**
NodeList is not thread safe. Move sendDomainServerCheckIn calls to the NodeList thread.

Clean-living PR for https://highfidelity.atlassian.net/browse/BUGZ-7 and friends, but no smoking gun as to cause.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19536/HighFidelity-Beta-PR15582-f1e8343.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19536/HighFidelity-Beta-Interface-PR15582-f1e8343.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19536/HighFidelity-Beta-PR15582-f1e8343.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19536/HighFidelity-Beta-Interface-PR15582-f1e8343.exe

**Comment by howard-stearns** [comment]
It looks like sendDomainServerCheckIn originally _was_ on the NodeList thread, and that got (accidentally?) moved to main thread in this commit: https://github.com/highfidelity/hifi/pull/12510/files#diff-740cf92da8140802f67b5aac4dc2ffc0R1059

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19538/HighFidelity-Beta-PR15582-72a9017.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19538/HighFidelity-Beta-Interface-PR15582-72a9017.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19538/HighFidelity-Beta-PR15582-72a9017.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19538/HighFidelity-Beta-Interface-PR15582-72a9017.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19538/HighFidelity-Beta-PR15582-72a9017.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19538/HighFidelity-Quest-Beta-PR15582-72a9017.apk)

**Pull request merged**
