### PR TITLE
Case 22255: Add size checks for trait packets parsing

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.manuscript.com/f/cases/22255/Traits-check-we-have-enough-bytes-to-read)

### CODE REVIEW

**Comment by Atlante45** [comment]
[problems with mtu size and traits](https://trello.com/c/ETCUGP4P/91-problems-with-mtu-size-and-traits)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19012/HighFidelity-Beta-PR15466-d36fd6e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19012/HighFidelity-Quest-Beta-PR15466-d36fd6e.apk)

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19015/HighFidelity-Beta-PR15466-d36fd6e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19015/HighFidelity-Quest-Beta-PR15466-d36fd6e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19015/HighFidelity-Beta-PR15466-d36fd6e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19015/HighFidelity-Beta-Interface-PR15466-d36fd6e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19015/HighFidelity-Beta-PR15466-d36fd6e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19015/HighFidelity-Beta-Interface-PR15466-d36fd6e.exe

**Pull request merged**
