### PR TITLE
Fix for 20369

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 531bb5738f815561e18bd23d57d3cf7ac08f39c5 available at: https://gist.github.com/3aef57746041aeee4848<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4399.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4399.dmg

**Comment by ZappoMan** [comment]
I'm still not sure this is the right solution. Presumably you can have a model without a "hips" joint, so long as you add the correct mapping in the joint mapping dialog box it should still work as a skeleton.

**Comment by ctrlaltdavid** [comment]
Hmmm. The HiFi avatar standard in the docs specifies that the avatar skeleton starts with a "Hips" joint. And the "Blend Swap Girl" model which crashes interface has joint names but they're things like "circle".

An alternative solution might be to put the test after the joint mapping dialog and only let the user upload the model if they've specified a mapping for "Root joint". ... Or have a test before (are there any joints at all?) and a test after (has the root joint been specified).

**Comment by ctrlaltdavid** [comment]
@cozza13 What are your thoughts on the solution to adopt?

**Comment by ZappoMan** [comment]
I recommend the last suggestion....

1) You must have at least 1 joint at load/parse
2) You must include a map for the root joint after the joint mapping dialog.

If you don't do 2 it would be possible for a model with "hips" to still end up without a root joint mapped.

**Comment by ctrlaltdavid** [comment]
I have implemented 2), i.e.,check that the user configures a root joint.
I have not implemented 1) because think it seems a bit superfluous when even the phone booth of http://hifi-public.s3.amazonaws.com/models/content/phonebooth.fbx has 5 "joints".

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d11dde8ad44d867b1b926f822891b9630015951 available at: https://gist.github.com/3aef57746041aeee4848<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4399.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4399.dmg

**Pull request merged**
