### PR TITLE
Updating char controller

### PR DESCRIPTION
**Pull request by alexiamandeville**
Character controller updates
Mouse sensitivity to be more stable
Increasing boom speed on mousescroll

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8074/app_12659_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8074/HighFidelity-Beta-PR12659-748507f1e357b7a03177f847c63362297de9663e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8074/HighFidelity-Beta-PR12659-748507f1e357b7a03177f847c63362297de9663e.exe

**Comment by alexiamandeville** [comment]
Removed Marketplace script update

**Comment by sethalves** [comment]
to test:
- in flat-screen mode use mouse-look (right-click and drag).  movement should be a bit slower than in master.
- use the mouse scroll wheel to move the camera between 1st-person and various distances in 3rd-person.  the change should happen a bit faster than in master.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8098/app_12659_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8101/app_12659_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8101/HighFidelity-Beta-PR12659-0d6e8f349096b2b4265a9806413a2791f0f23388.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Zoom in speed with scroll wheel is significantly faster and much more satisfying. Right click and hold to move camera sensitivity is still quick and snap but much more accurate. Overall these QoL changes are very welcome.

**Pull request merged**
