### PR TITLE
Fix asan warnings

### PR DESCRIPTION
**Pull request by kencooke**
### Test Plan
Using Interface from this PR, just do a quick smoke-test of audio.
Audio processing should be unchanged (bit-exact).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9450/app_13080_PR_3071b410bff9d1370077ecad1acb2cc6e38c58a6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9450/HighFidelity-Beta-PR13080-3071b410bff9d1370077ecad1acb2cc6e38c58a6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9450/HighFidelity-Beta-Interface-PR13080-3071b410bff9d1370077ecad1acb2cc6e38c58a6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9450/HighFidelity-Beta-PR13080-3071b410bff9d1370077ecad1acb2cc6e38c58a6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9450/HighFidelity-Beta-Interface-PR13080-3071b410bff9d1370077ecad1acb2cc6e38c58a6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9458/app_13080_PR_3e77d946ea49e82fd1b22c3fbe0713aef57ac67b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9458/HighFidelity-Beta-PR13080-3e77d946ea49e82fd1b22c3fbe0713aef57ac67b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9458/HighFidelity-Beta-Interface-PR13080-3e77d946ea49e82fd1b22c3fbe0713aef57ac67b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9458/HighFidelity-Beta-PR13080-3e77d946ea49e82fd1b22c3fbe0713aef57ac67b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9458/HighFidelity-Beta-Interface-PR13080-3e77d946ea49e82fd1b22c3fbe0713aef57ac67b.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Basic Audio features works as intended.

**Pull request merged**
