### PR TITLE
fix for getSetting QVariant ref in DomainServer

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Run test https://highfidelity.testrail.net/index.php?/cases/view/2177

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7779/app_12573_PR.apk

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7786/app_12573_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7786/HighFidelity-Beta-PR12573-a83b54e10dd63f312d143b6b9ac1b850410f7900.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7786/HighFidelity-Beta-PR12573-a83b54e10dd63f312d143b6b9ac1b850410f7900.dmg

**Comment by conklin94122** [comment]
@birarda QA Ready?

**Comment by birarda** [comment]
@conklin94122 yup, labelled

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Fail - @conklin94122 
Unable to select a place name, an error appears when selecting the +.
pr12573

**Comment by birarda** [comment]
@qlimnavarro tested this locally and even with a temporary domain ID that should have succeeded.

We did just do an API deploy, possible you were unlucky enough to make a request during that time and it failed. Can you try again?

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by birarda** [comment]
@qlimnavarro from your logs it looks like this test was done against staging metaverse.

The account connection step will generate an access token for stable metaverse which is causing the error you see.

Can you test against stable metaverse by running the sandbox without the HIFI_METAVERSE_URL environment variable?

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
