### PR TITLE
user-specified animation graph

### PR DESCRIPTION
**Pull request by howard-stearns**
Provide a place in the advanced avatar section of preferences in which users can specify a different animation graph spec.

Takes effect when you save (if you have enabled the anim graph under developer->avatar).
An empty string gives you the default behavior. (Eventually, the empty-string/default behavior will come from the .fst, and everything will be script-controllable. This PR should be consistent with that future direction.)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b701b8a5b75f7f897ee5bc101e9829afbf59c6a available at: https://gist.github.com/fe717e40261b21c0ec39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b701b8a5b75f7f897ee5bc101e9829afbf59c6a available at: https://gist.github.com/fe717e40261b21c0ec39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4dd95be8c40e62638a5c332fe1008a26d24fcc41 available at: https://gist.github.com/fe717e40261b21c0ec39<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5862.dmg

**Pull request merged**
