### PR TITLE
DEV-378: Implement piecewise filmic tone curve

### PR DESCRIPTION
**Pull request by annabrewer**
- Implemented [this spec](http://filmicworlds.com/blog/filmic-tonemapping-with-piecewise-power-curves/) to add a piecewise filmic curve as a fifth shader option for the full screen tone mapping pass.
- Created a new ToneMappingPiecewise shader, and a ToneMappingCommon scribe-compatible header file for storing the common structs used by the tone mapping shaders and ToneMapAndResampleTask.
- Exposed individual R, G, and B tone curve parameters to QML, as well as a global set of curve parameters that is independent from the other three.
- These parameters are also exposed to the scripting interface as part of the config for the ToneMapping task.
- Created a UI for messing with tone curve parameters globally or by channel (R, G, B) and seeing their effects on the curve(s).
- To access the UI, run luci.js, select the Piecewise Filmic curve from the dropdown menu, then run toneCurve.js (same folder as luci).

### CODE REVIEW

**Comment by shanzzam** [comment]
build this please

**Comment by shanzzam** [comment]
build this please

**Comment by shanzzam** [comment]
build this please

**Comment by annabrewer** [comment]
Hey just wanted to check in on this! Which Jenkins builds are failing and why? I'm swamped this week because I have the GRE coming up on Saturday, but can probably find some time next week to work on it.

**Comment by shanzzam** [comment]
@annabrewer we are unsure.  someone in Engine team will need to look at this PR. It's something in this  PR and not in jenkins. OR there are dependencies that Jenkins isn't configured for.

**Comment by shanzzam** [comment]
@annabrewer if you can clean up the conflicts we'll try another build.

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by samcake** [comment]
WE will take it over the finsihing line from a coied branch,

Thanks Anna!

**Pull request closed without merging**
