### PR TITLE
allow temp domains to use access token when present

### PR DESCRIPTION
**Pull request by birarda**
- fixes a bug where connected temp domains could not leverage API services

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

On master, connect a temporary domain (does not have a registered domain ID in your account, has a temporary name) to your metaverse account.

Use a domain-server feature that requires authentication. The easiest is likely to only allow friends to connect to your domain, add another user as a friend (highfidelity.com/user/friends) and then see if they are able to connect.

On master, they will be unable to connect because the temporary domain cannot get your list of friends. With this PR, your friend should be able to connect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d098a1ae28d9a55f222f9a245951a1bfb4ebbdda available at: https://gist.github.com/63bb77fdae01f89f045cb729aead0f52<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8498-d098a1a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8498-d098a1a.dmg

**Comment by nbq** [comment]
testing this now

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1519/Friends-on-list-can-t-connect-to-sandbox

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: For this test I blocked out everyone, even localhost and no one could get in. I then allowed a Group with proper access and once I hit save, the avatar reconnected just fine.

grouponly-access

**Pull request merged**
