### PR TITLE
CR Job #21281 -- Doppleganger Mirror

### PR DESCRIPTION
**Pull request by humbletim**
This PR adds support for using a "doppleganger mirror" to reflect your Avatar's model and joint data onto a private Overlay view.  It can be used to self-test various Avatar features like how your hand controllers are performing or animations look to others.  Unlike Camera-mode mirrors, to find the right vantage point you just walk or fly around your doppleganger using your normal movement controls.

#### Testing:
* Launch Interface
* Open the `Running Scripts...` dialog and load **system/app-doppleganger.js** from the tree view.
* Verify the script loads without errors and a new tablet app icon appears:
image
* Click the icon to activate the mirror.
* Verify the doppleganger appears in front of you and automatically mimics your joint movements.
* Click the icon again to disable the mirror.
* Verify the doppleganger disappears.

#### Exception Testing
(with **app-doppleganger.js** loaded)
* Avatar model changes:
  * Wear a valid avatar model and activate the mirror / doppleganger.
  * Change your avatar to a different model.
  * Verify the mirror automatically switches off.
* Bogus models / URLs:
  * Wear a valid avatar model and activate the mirror / doppleganger.
  * Switch your avatar model to a bogus URL (eg: https://httpbin.org/delay/5)
  * Verify that after a short delay (currently ~10 seconds) the mirror pops-up an error message and automatically disables itself.
* Domain changes
  * Wear a valid avatar model and activate the mirror / doppleganger.
  * Change to a different domain.
  * Verify the mirror automatically shuts itself off.

*note: Only joint data is synchronized in this version, so for example attachments and blendshapes will still only appear on your actual Avatar.*

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 28b3eef7aa57f82f13c9682b1d9e281eb1bc2ae3 available at: https://gist.github.com/451e0f91527ef4c07fc615890e1b1bb8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-28b3eef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-28b3eef.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8339123998ec532d41146153876f860a1172f0d available at: https://gist.github.com/451e0f91527ef4c07fc615890e1b1bb8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-a833912.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-a833912.dmg

**Comment by anshuman64** [comment]
I am looking at this one

**Comment by hifi-gustavo** [comment]
Build console output for commit: 84c8b2945aff9ff130520addddcbd18a4f384041 available at: https://gist.github.com/451e0f91527ef4c07fc615890e1b1bb8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-84c8b29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-84c8b29.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e0793335642f94274c0896f4d1eea21ec6617ca available at: https://gist.github.com/451e0f91527ef4c07fc615890e1b1bb8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-6e07933.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10271-6e07933.dmg

**Pull request merged**
