### PR TITLE
fix Linux debug builds

### PR DESCRIPTION
**Pull request by sethalves**
- fix ubuntu Linux debug builds

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no functional change

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9317/app_13050_PR_a245bb2174de3e4509c97d6de37ab483c4e1f89a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9317/HighFidelity-Beta-PR13050-a245bb2174de3e4509c97d6de37ab483c4e1f89a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9317/HighFidelity-Beta-Interface-PR13050-a245bb2174de3e4509c97d6de37ab483c4e1f89a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9317/HighFidelity-Beta-PR13050-a245bb2174de3e4509c97d6de37ab483c4e1f89a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9317/HighFidelity-Beta-Interface-PR13050-a245bb2174de3e4509c97d6de37ab483c4e1f89a.exe

**Comment by AndrewMeadows** [comment]
I checked-out this branch and verified that I could build and run a debug linux version of the servers and client

**Pull request merged**
