### PR TITLE
Fix HTML controls not working properly in the tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
In particular, the up/down spin buttons in numeric fields in entity properties.

Also reinstates scrollbars to marketplace pages on the tablet.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Using tablet:
- in desktop
- in HMD

Buttons etc. highlight as expected on hover: entity properties; general preferences; in general

Scrolling dialogs and content: entities list; entity properties; general preferences; marketplace (HiFi, directory, and Clara.io pages)
- Using scrollbars (except for marketplace dialogs which don't display them)
- Dragging content

Editing dialog fields: entity properties; general preferences
- Using mouse.
- Using laser.
- Using stylus.
- Using finger.
- Using keyboard if in HMD.
- Using up/down spin controls on numeric fields.

Scrollbars are present and can be used on HiFi marketplace, marketplace directory, and Clara.io marketplace pages in the tablet.

Known issue: Scroll bar dragging can be a bit unstable in the tablet (content can jump up and down at times).

Known issue: If scrolling with scrollbar handle and you move your pointer off the tablet then release the mouse button or equivalent, the content scrolls with your mouse as you move it over the tablet again (i.e., scrolling gets stuck). To be addressed in a separate PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f397adb22a2803e80cb3b525610040940882178a available at: https://gist.github.com/778c543c60ee178f0ac44740160e712a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10091-f397adb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10091-f397adb.dmg

**Comment by cozza13** [comment]
When I switched out of edit, edit did not turn off.

**Comment by cozza13** [comment]
Testing and it worked.

**Pull request merged**
