### PR TITLE
Build 45.1 Hotfix for Entity Server Scripts

### PR DESCRIPTION
**Pull request by Atlante45**
Build 45.1 Hotfix for Entity Server Scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1194/HighFidelity-Beta-PR10852-6c487ec0afce27d889bf5ed252a312bd37028e85.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1194/HighFidelity-Beta-PR10852-6c487ec0afce27d889bf5ed252a312bd37028e85.dmg

**Comment by Nex-Pro** [comment]
Will get on this shortly.

**Comment by Nex-Pro** [comment]
Smoke testing this as per request.

**Comment by Nex-Pro** [comment]
Rc 45 hotfix #10852

Primary testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.
Audio systems:  USB headset + Vive audio.

## QA Test **FAIL**
**QA Tester: Piper.Peppercorn**

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS Used playa
FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:

Opening ATP browser via the create panel does not display the buttons  at the bottom.
This is due to the tablet being horizontal. There is no way to scroll down. 
These can be accessed only when ATP is accessed via menu.

Tutorial was very jerky.

Toolbar and tablet at same time after switching from desktop to VR.

Double buttons in toolbar after switching back to desktop mode.
Reload scripts does not fix.

    Got a popup titled "Source2 - Warning"

    message on it was. "Only one instance of the game can be running at one time."

    With an OK button. I was only running one instance.

Problem with help only displaying two pages in desktop tablet mode persists.

Script snapshot.js is throwing exceptions when the X button on the tablet is clicked while any menu is open. (discussed with Chris).

Below results are pretty much meaningless.

**Domain** |localhost | |dev-demo
---|---|---|---
**Render Rate**: |0 | |0
**Present Rate**: |90 | |90
**Present New Rate**: |0 | |0
**CPU Buffer Count**: |1829 | |283
**GPU Buffer Count**: |689 | |157
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |200 | |55
**GPU Texture Count**: |103 | |47
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |65366 | |30482
**Triangle Rate**: |5942363 | |2771090
**API Drawcall Count**: |55 | |27
**Drawcall Count**: |96 | |40
**Drawcall Rate**: |8727 | |3636
**State Changes Texture Count**:|80 | |47
**Pipeline Count**: |34 | |30
**Item Opaques**: |0 | |0
**Item Translucents**: |0 | |0
**Item Lights**: |0 | |0
**Timing Opaques**: |0 | |0
**Timing Translucents**: |0 | |0
**Timing Lighting**: |0 | |0
**Render Frame**: |0 | |0


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|demo and dev-playa are unavailable
**Test 2**|Install a fresh copy of "Home' and do tutorial|Jerky interaction with fireworks and teleport target.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|PASS
**Test 5**|Switch avatar and make sure it does not crash|PASS
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item| PASS
**Test 8**|Enrure that you can distance grab| PASS
**Test 9**|Bring up and edit an objects with hand controllers| PASS
**Test 10**|Test PAL functionality| Basic test passed.
**Test 11**|Test Tablet in 2D and 3D| PASS

doublebuttonsontoolbar
hifi-snap-by--on-2017-06-29_17-25-06

**Comment by Nex-Pro** [comment]
also just got this:

### Double icons in 2d Tablet

hifi-snap-by--on-2017-06-29_19-24-12

**Pull request merged**
