### PR TITLE
added skybox group properties to zones, wired up color to the actual skybox rendering

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cb14650b6f0069c4d2d98703ed4605e09c3f390 available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Comment by Atlante45** [comment]
`zoneAtmosphereExample.js` and `zoneSkyboxExample.js` are not functionning correctly because
both the `Atmosphere` and `Skybox` property groups are orthograped with a capital in the properties definition, but they are not in the scripts.

I think that might be confusing to have groups start with a capital, is that something we absolutely want?

**Comment by hifi-gustavo** [comment]
Build console output for commit: edb84a1a147bc1c324adb38104fc9854d9dc0540 available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f2ebb6e821fa3c2d480403cb43c68ab58471f37e available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7dfbd103ae1f33d2956bc1706a54702a86a9a9b available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: af2c3d91cfdbf9571979d8dccf45202943d09191 available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 496da6fcd5b87cef690d5147eb5ea17aa55f0571 available at: https://gist.github.com/243d01ce07e9e0698e4f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4775.dmg

**Pull request merged**
