### PR TITLE
Multichannel audio support

### PR DESCRIPTION
**Pull request by kencooke**
Add support for mono or multichannel audio output devices. Due to HRTF and reverb, the audio pipeline will always produce stereo output. The backend will now upmix/downmix to the device format, if needed. 

This PR includes updated WASAPI Qt plugins that implement multichannel support.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec53c6a0308388a0f6833efa73a7a64c40ebed03 available at: https://gist.github.com/deb532204725a2e1ba1406dc3d306a86<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-ec53c6a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-ec53c6a.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec53c6a0308388a0f6833efa73a7a64c40ebed03 available at: https://gist.github.com/deb532204725a2e1ba1406dc3d306a86<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-ec53c6a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-ec53c6a.dmg

**Comment by kencooke** [comment]
### Test Plan

This build of Interface should work with audio devices running at any sample rate and channel configuration. On a 5.1 or 7.1 channel device, the audio should appear on the left and right channels.

1) Verify that both server and loopback audio work as before, using a stereo output device.
2) Verify that audio still works on a multichannel (5.1/7.1 etc.) output device.
3) Close Interface, change the Windows "Default Format" sample rate for the audio device, restart Interface, and verify that audio still works correctly.

**Comment by OmegaHeron** [comment]
Testing Windows 10

Devices detected properly.

Devices tested

Mobo sound in 5.1 and 7.1
USB connected Logitech headset
USB connected general purpose sound device (ancient iMic USB puck)
Bluetooth stereo headset (Kinivo BTH220)

Device | Mode | Master | PR
--- | :---: | :---: | :---:
USB Headset | Stereo | Pass | Pass
Bluetooth | Stereo | Pass | Pass
Bluetooth | Mono | Fail | Pass
USB Generic | Stereo | Pass | Pass
Mobo | 5.1 | Fail | Fail
Mobo | 7.1 | Fail | Fail
Mobo | Stereo | Fail | Fail

I hadn't attempted to use Mobo sound system in a *long* time...  that it no longer seems to work is odd.  I confirmed that it plays sound from various things like VLC playing music, games and anything else I could find to make noise.  Interface logs following when it is selected.

`[11/17 12:18:46] [DEBUG] [hifi.scriptengine] script:print()<< output audio selection...Speakers (Realtek High Definition Audio)`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] DEBUG [ "Speakers (Realtek High Definition Audio)" ] [ "Speakers (Realtek High Definition Audio)" ]`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] The audio output device  "Speakers (Realtek High Definition Audio)" is available.`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(48000Hz, 16bit, channelCount=8, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.`
`[11/17 12:18:46] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  1 requested bytes: 7680 actual bytes: 7680 os default: 4096 period size: 7680`

Things to note;

If you look at Windows Volume Mixer (Windows 10 here) where you can see each audio producer and adjust volume levels per application you will **never** see Interface listed as connected to device.  Other devices on system, when selected in Interface, do show up.

Channel count is wrong - device is not in 5.1 or 7.1 mode -- it's, in this scope, attach to a single speaker pair (headphones), its control panel indicates it's in stereo 2 channel output mode.  

It will not make any sound from Interface - whether in 5.1/7.1 or stereo headphone mode.  No loopback audio, no sounds from domain objects etc etc.

Now -- look at log output from devices that *do* work;

First my bluetooth headset in "cell phone" mode - that's basically mono playback with its mic enabled.

`[11/17 12:25:57] [DEBUG] [hifi.audioclient] DEBUG [ "Headset (BTH220 Hands-Free)" ] [ "Headset (BTH220 Hands-Free)" ]`
`[11/17 12:25:58] [DEBUG] [hifi.audioclient] The audio output device  "Headset (BTH220 Hands-Free)" is available.`
`[11/17 12:25:58] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:25:58] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(8000Hz, 16bit, channelCount=1, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:25:58] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.`
`[11/17 12:25:58] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  2.2 requested bytes: 160 actual bytes: 352 os default: 4096 period size: 160`

Same bluetooth device in stereo mode -- the difference here is it disables mic and allows full range stereo playback.

`[11/17 12:27:09] [DEBUG] [hifi.audioclient] DEBUG [ "Headphones (BTH220 Stereo)" ] [ "Headphones (BTH220 Stereo)" ]`
`[11/17 12:27:09] [DEBUG] [hifi.audioclient] The audio output device  "Headphones (BTH220 Stereo)" is available.`
`[11/17 12:27:09] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:27:09] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(44100Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:27:09] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.`
`[11/17 12:27:09] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  2.19955 requested bytes: 1764 actual bytes: 3880 os default: 4096 period size: 1764`

Logitech USB headset

`[11/17 12:31:29] [DEBUG] [hifi.audioclient] DEBUG [ "Speakers (2- Logitech USB Headset)" ] [ "Speakers (2- Logitech USB Headset)" ]`
`[11/17 12:31:29] [DEBUG] [hifi.audioclient] The audio output device  "Speakers (2- Logitech USB Headset)" is available.`
`[11/17 12:31:29] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:31:29] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(44100Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:31:29] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.`
`[11/17 12:31:29] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  2.19955 requested bytes: 1764 actual bytes: 3880 os default: 4096 period size: 1764`

iMic USB sound puck

`[11/17 12:32:42] [DEBUG] [hifi.audioclient] DEBUG [ "Speakers (3- iMic USB audio system)" ] [ "Speakers (3- iMic USB audio system)" ]`
`[11/17 12:32:42] [DEBUG] [hifi.audioclient] The audio output device  "Speakers (3- iMic USB audio system)" is available.`
`[11/17 12:32:42] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:32:42] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(48000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 12:32:42] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.`
`[11/17 12:32:42] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  2.2 requested bytes: 1920 actual bytes: 4224 os default: 4096 period size: 1920`

**Comment by davidkelly** [comment]
I tried something different.  I can tell the realtek sound manager to either output stereo from the audio card or 5.1 or 7.1.  So normally I have my headset plugged in and it auto detects that as stereo.  When I do that everything works fine as always.  If I tell it I'm 5.1 for instance, I see this in the logs: 
```
[11/17 10:50:38] [DEBUG] [hifi.audioclient] The audio output device  "Speakers (Realtek High Definition Audio)" is available.
[11/17 10:50:38] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")
[11/17 10:50:38] [DEBUG] [hifi.audioclient] The format to be used for audio output is QAudioFormat(48000Hz, 16bit, channelCount=6, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")
[11/17 10:50:38] [DEBUG] [hifi.audioclient] Attemping to create a resampler for network format to output format.
[11/17 10:50:38] [DEBUG] [hifi.audioclient] Output Buffer capacity in frames:  1 requested bytes: 5760 actual bytes: 5760 os default: 4096 period size: 5760
```
so it correctly detects the 6 channels.  But -- I also got no audio.  However Ken did same and it worked for him, so more testing...

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd08936fb3c6c89e189cea39dfc543627c217510 available at: https://gist.github.com/deb532204725a2e1ba1406dc3d306a86<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-fd08936.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9091-fd08936.dmg

**Comment by kencooke** [comment]
I see the same results as David, with Realtek motherboard audio. When I plug in headphones, it detects as channels=2 and works as expected. But if I manually configure to 5.1 with only headphones plugged in, it detects as channels=6 and fails to open. This seems to be a quirk in the Realtek drivers? In this state, isFormatSupported() appears to fail regardless of the format.

**Comment by OmegaHeron** [comment]
Results with my failing mobo realtek device (which I actually don't use/care about other than being able to trigger this issue)

`[11/17 18:00:25] [DEBUG] [hifi.scriptengine] script:print()<< output audio selection...Speakers (Realtek High Definition Audio)`
`[11/17 18:00:26] [DEBUG] [hifi.audioclient] DEBUG [ "Speakers (Realtek High Definition Audio)" ] [ "Speakers (Realtek High Definition Audio)" ]`
`[11/17 18:00:26] [DEBUG] [hifi.audioclient] The audio output device  "Speakers (Realtek High Definition Audio)" is available.`
`[11/17 18:00:26] [DEBUG] [hifi.audioclient] The desired format for audio I/O is QAudioFormat(24000Hz, 16bit, channelCount=2, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm")`
`[11/17 18:00:26] [DEBUG] [hifi.audioclient] WARNING: The mix format is QAudioFormat(48000Hz, 16bit, channelCount=8, sampleType=SignedInt, byteOrder=LittleEndian, codec="audio/pcm") but isFormatSupported() failed.`

**Comment by kencooke** [comment]
@OmegaHeron I'm at a loss to explain your specific problem. But since it fails with stereo in the old version too, it seems unrelated to this PR. We should keep investigating as a separate bug report.

**Comment by OmegaHeron** [comment]
Fair enough @kencooke --  I can give it a QA Pass in that it does support one device that did not work previously (bluetooth headset in mono mode).

**Pull request merged**
