### PR TITLE
Add glow to UI hand lasers and termination points

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a4f9c5cf9b41f431409768d0f9dc5b51fc6e8e27 available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-a4f9c5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-a4f9c5c.dmg

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9DzOQHi7&#x2F;73-add-intersection-effect-to-2d-overlay-laser"> Add intersection effect to 2D overlay laser</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: e513bfae8370f44515a8cd943c73d4dfbb6fd8dd available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-e513bfa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-e513bfa.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72f93f0a306407a47dea9243520072893c29e01a available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-72f93f0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-72f93f0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 367e34d4fce123afd6930388780bf65bd895fe5e available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-367e34d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-367e34d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 367e34d4fce123afd6930388780bf65bd895fe5e available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-367e34d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-367e34d.dmg

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;MrmdglsE&#x2F;74-add-glow-support-to-the-special-case-2d-hand-lasers"> Add glow support to the special case 2D hand lasers</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 246ca0161013987cef3749d1d0e156d5d4579a8b available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-246ca01.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-246ca01.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 805cec6c25a3d38039f4e97dc51470ce40285b89 available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-805cec6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-805cec6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71f7a1f2574caca24c00d6b3750db1e0f2ad0fed available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-71f7a1f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-71f7a1f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6242816f68b47c74f20479bcc5fdabac5188f21f available at: https://gist.github.com/0da597ca6ec98cac311b62419efa62fd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-6242816.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8226-6242816.dmg

**Pull request merged**
