### PR TITLE
Fix JSDoc for MyAvatar.getLeftPalmRotation and getRightPalmRotation

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

https://highfidelity.manuscript.com/f/cases/16629

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11330/HighFidelity-Beta-PR13613-e4f13c9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11330/HighFidelity-Beta-PR13613-e4f13c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11330/HighFidelity-Beta-Interface-PR13613-e4f13c9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11330/HighFidelity-Beta-PR13613-e4f13c9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11330/HighFidelity-Beta-Interface-PR13613-e4f13c9.exe

**Pull request merged**
