### PR TITLE
Case 21288: Move Material Entity logic to render thread (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21288/

https://github.com/highfidelity/hifi/pull/14935

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17375/HighFidelity-Beta-PR14946-0a80757.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17375/HighFidelity-Beta-PR14946-0a80757.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17375/HighFidelity-Beta-Interface-PR14946-0a80757.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17375/HighFidelity-Beta-PR14946-0a80757.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17375/HighFidelity-Beta-Interface-PR14946-0a80757.exe

**Comment by qlimguicheteau** [comment]
Currently Testing

**Comment by qlimguicheteau** [comment]
PASS
--

Regressive tests passed cleanly
Ran Thoy's test script and swung the camera around in both HMD and Desktop.
image

Pushed the zone through some resizing abuse testing, using the same techniques as the original report.
No flashing or strobing was seen.

**Pull request merged**
