### PR TITLE
Fix keyboard for tablet web view in HMD

### PR DESCRIPTION
**Pull request by druiz17**
This fixes the issue of not having a keyboard for a tablet web view in HMD

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- In tablet mode and HMD mode
- click on goto and the info of a place
- once the high-fidelity web page appears...click on the tweet button
- once the twitter page appears...click on one of the text fields and a keyboard should appear

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6033c2694687170dc02538b6ee04624ed1948632 available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-6033c26.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-6033c26.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fdc2f235559b3aaec275b05093a8e8997c77e852 available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-fdc2f23.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-fdc2f23.dmg

**Comment by cozza13** [comment]
Crashed https://www.bugsplat.com/keycrash/?stackKeyId=2008&database=interface_alpha

**Comment by hifi-gustavo** [comment]
Build console output for commit: f9178dd2c9f0a1fda1f0778de1d170887b681225 available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-f9178dd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-f9178dd.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7403de43b35185e4031a5ef470929d798ebe5eeb available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-7403de4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-7403de4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4770384dd1dc37e6b7e2df704f1e962b8ea6e681 available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-4770384.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-4770384.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b50f58f2ff39a565d53bd7da281ab18ecc71f897 available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-b50f58f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-b50f58f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9dc15f3dd95e450ba57b21a268997bd4e18b0c7e available at: https://gist.github.com/569a4739e565c26625a58124f631524e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-9dc15f3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10198-9dc15f3.dmg

**Comment by cozza13** [comment]
crashed again

**Pull request closed without merging**
