### PR TITLE
Fix equip sphere not showing up

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Try equipping an item using hand controllers, and confirm that the blue equip sphere shows up
 1. Make sure that grabbing and equipping still works in general

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f5dedaa409141836307844f6c858c465afd27a2 available at: https://gist.github.com/16666a26629127e2b676169f7f3c784e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8827-5f5deda.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8827-5f5deda.dmg

**Comment by RyanDowne** [comment]
Tested with Oculus and Touch  and it works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f5dedaa409141836307844f6c858c465afd27a2 available at: https://gist.github.com/16666a26629127e2b676169f7f3c784e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8827-5f5deda.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8827-5f5deda.dmg

**Comment by ZappoMan** [comment]
oops... sorry!

**Pull request merged**
