### PR TITLE
Added workaround to enable menu bar under Linux

### PR DESCRIPTION
**Pull request by vladest**
This commit enables MenuBar under Linux
Affects only Linux builds

Test plan:
- Run Linux built Interface app
- Make sure Menu bar visible and operational

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3724/HighFidelity-Beta-PR11478-0a9bebeefc52c53577b4705de147f8d596caa3fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3724/HighFidelity-Beta-PR11478-0a9bebeefc52c53577b4705de147f8d596caa3fd.exe

**Comment by OmegaHeron** [comment]
Testing in progress (Ubuntu 16.04).

**Comment by OmegaHeron** [comment]
I jumped gun on saying I'd test this.  Once it's flagged QA ready then will do.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3733/HighFidelity-Beta-PR11478-c3225c2c761d52b5ade6a8e361189bc7f1829140.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3733/HighFidelity-Beta-PR11478-c3225c2c761d52b5ade6a8e361189bc7f1829140.exe

**Comment by OmegaHeron** [comment]
Tested Ubuntu 16.04
QA Pass

Menus work (mostly) as expected.  You have to restart after enabling Developer menu for it to show in Menu bar, but, that's not a huge deal.

**Pull request merged**
