### PR TITLE
Case 21397: Fix nametag rotation

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/21397/nametag-rotation-for-81

Test plan:
- Purchase and run the Nametags script from the marketplace.  Run it and nametags should appear above people.  They should rotate correctly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17550/HighFidelity-Beta-PR15003-37720e9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17550/HighFidelity-Beta-PR15003-37720e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17550/HighFidelity-Beta-Interface-PR15003-37720e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17550/HighFidelity-Beta-PR15003-37720e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17550/HighFidelity-Beta-Interface-PR15003-37720e9.exe

**Comment by samcake** [comment]
testing the build

**Comment by samcake** [comment]
all good

**Pull request merged**
