### PR TITLE
send session ID in AccountManager without curly braces

### PR DESCRIPTION
**Pull request by birarda**
- removed the curly braces from AccountManager session ID header

### CODE REVIEW

**Comment by birarda** [comment]
To test:

Simple change to functionality introduced in #7976. A general smoke test that causes some typical requests to the API (place name lookups, username lookups, location updates) is sufficient.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 807d47d58bdee4f76c4d952522a2a7e6e370540f available at: https://gist.github.com/385e2574b506a6e801e7d197fc110e7e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7976.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7976.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test and able to see users online however standard domains are not reachable due to recent updates, expected temporary behavior.  

**Domain** |localhost | |
---|---|---|---
**Render Rate**: |60 | |
**Present Rate**: |60 | |
**Present New Rate**: |60 | |
**CPU Buffer Count**: |3207 | |
**GPU Buffer Count**: |409 | |
**CPU Memory Usage**: |43712512 | |
**GPU Memory Usage**: |11337728 | |
**CPU Texture Count**: |166 | |
**GPU Texture Count**: |450 | |
**GPU Transfer Count**: |0 | |
**CPU Texture Memory Usage**: |234383832 | |
**GPU Texture Memory Usage**: |264910881 | |
**GPU Virtual Memory Usage**: |429370401||
**Triangle Count**: |235542 | |
**Triangle Rate**: |14721375 | |
**API Drawcall Count**: |153 | |
**Drawcall Count**: |157 | |
**Drawcall Rate**: |9812 | |
**State Changes Texture Count**:|122 | |
**Pipeline Count**: |26 | |
**Item Opaques**: |191 | |
**Item Translucents**: |3 | |
**Item Lights**: |19 | |
**Timing Opaques**: |1278 | |
**Timing Translucents**: |99 | |
**Timing Lighting**: |124 | |
**Render Frame**: |2209 | |

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ec421350d68101e6b93f01aa9ef33d5035eedd9 available at: https://gist.github.com/385e2574b506a6e801e7d197fc110e7e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7976.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7976.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test and able to see users online this time I was successful in visiting ```dev-demo``` and was able to manipulate objects and the experience was as expected.

**Pull request merged**
