### PR TITLE
Add launch.tester to user_actions

### PR DESCRIPTION
**Pull request by zzmp**
Add a flag to identify QA/Dev users for BI queries.

### CODE REVIEW

**Comment by zzmp** [comment]
If we decide to move forward on this, then QA/Dev users will be asked to add the `HIFI_TESTER` environment variable to their machines. This will mark their user sessions as `launch.tester = true` so that they can easily be filtered out of BI queries.

**Comment by zzmp** [comment]
Does not need QA.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 929079df9784d4eb27e114e29c973b022f0525f0 available at: https://gist.github.com/4dedb8cc02bfe3e6ed37b86d79e1df2e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10411-929079d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10411-929079d.dmg

**Comment by cozza13** [comment]
@zzmp is it worth using the included in stats = false flag instead of a new one?

**Comment by zzmp** [comment]
Included in stats is a field in the db, whereas this is data being sent to our servers, which is then translated in to the db. If we decide to, we can have the server check this flag and then update included in stats, but that work would happen in the server, not in this repo.

**Pull request merged**
