### PR TITLE
BUGZ-135: Edit entity icons ignorePickIntersection when not visible

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.atlassian.net/browse/BUGZ-135

Test plan:
- Go to an empty area
- Make a zone
- Run this snippet from the console:
```
Entities.mousePressOnEntity.connect(function(id, event) {
   print(JSON.stringify(Entities.getEntityProperties(id)));
});
```
- With the console open, open Create and click the zone icon that appears.  You should see a block of JSON describing the zone print in the console.
- Close create and click in the same place, where the zone icon used to be.  Nothing should print.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19310/HighFidelity-Beta-PR15536-2bb522e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19310/HighFidelity-Quest-Beta-PR15536-2bb522e.apk)

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19310/HighFidelity-Beta-PR15536-2bb522e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19310/HighFidelity-Beta-Interface-PR15536-2bb522e.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19318/HighFidelity-Beta-PR15536-2bb522e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19318/HighFidelity-Quest-Beta-PR15536-2bb522e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19318/HighFidelity-Beta-PR15536-2bb522e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19318/HighFidelity-Beta-Interface-PR15536-2bb522e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19318/HighFidelity-Beta-PR15536-2bb522e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19318/HighFidelity-Beta-Interface-PR15536-2bb522e.exe

**Pull request merged**
