### PR TITLE
gltf wip

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21463/HighFidelity-Beta-PR16234-5edb312.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21463/HighFidelity-Quest-Beta-PR16234-5edb312.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21482/HighFidelity-Beta-PR16234-4090231.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21482/HighFidelity-Quest-Beta-PR16234-4090231.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21504/HighFidelity-Beta-PR16234-89bf2ea.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21504/HighFidelity-Quest-Beta-PR16234-89bf2ea.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21519/HighFidelity-Beta-PR16234-911fd27.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21519/HighFidelity-Beta-Interface-PR16234-911fd27.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21519/HighFidelity-Beta-PR16234-911fd27.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21519/HighFidelity-Beta-Interface-PR16234-911fd27.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21519/HighFidelity-Beta-PR16234-911fd27.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21519/HighFidelity-Quest-Beta-PR16234-911fd27.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21595/HighFidelity-Beta-PR16234-9518aa9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21595/HighFidelity-Beta-Interface-PR16234-9518aa9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21595/HighFidelity-Beta-PR16234-9518aa9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21595/HighFidelity-Quest-Beta-PR16234-9518aa9.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21595/HighFidelity-Beta-PR16234-9518aa9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21595/HighFidelity-Beta-Interface-PR16234-9518aa9.exe

**Comment by sabrina-shanman** [comment]
New PR is continuation of this PR's progress:
https://github.com/highfidelity/hifi/pull/16324

**Pull request closed without merging**
