### PR TITLE
Disable sparse textures for RC

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 571984115d3889500193a46d2b8bb0b71896ce92 available at: https://gist.github.com/d8a2e8d949ea2a6753cca10ed7403a04<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-5719841.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-5719841.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 571984115d3889500193a46d2b8bb0b71896ce92 available at: https://gist.github.com/d8a2e8d949ea2a6753cca10ed7403a04<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-5719841.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-5719841.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 459326743c711ab3170cc1b685bf374d9ac980e2 available at: https://gist.github.com/d8a2e8d949ea2a6753cca10ed7403a04<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-4593267.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8633-4593267.dmg

**Pull request closed without merging**
