### PR TITLE
Export boolean entity properties properly

### PR DESCRIPTION
**Pull request by thoys**
This one liner seems to make boolean properties better discoverable in entity exports. ~Lets check backwards compatibility.~  backward compatible with stable build ✔️ 

Instead of writing `0` or `1`, it will write `true` or `false` for boolean properties to the entities JSON file.

## test plan

Use https://highfidelity.testrail.net/index.php?/cases/view/7049 with a few additional steps.

Note: Please comment results of those steps under the same number.

5a. Enable the dynamic checkbox.      (The entity is now dynamic)
14a. Open the just created `PURPLE BOX.json` in a text editor. (It should contain the line `"dynamic": true,`)
23a. (Both entities should be dynamic, try pushing them around, they should move)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7478/app_12492_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7478/HighFidelity-Beta-PR12492-a27a5a7e1f3e676b763a5729cb9f9d9ebef8dc5e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7478/HighFidelity-Beta-PR12492-a27a5a7e1f3e676b763a5729cb9f9d9ebef8dc5e.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
