### PR TITLE
Restyle HMD menus

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e175c1975464fe3a22fbf46b5509ca7ecc42f0d2 available at: https://gist.github.com/3273772a6aa18abb95df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7321.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7321.dmg

**Comment by ZappoMan** [comment]
Smoke test on Mac (note: not a merge blocker)...
- in general it looks great! Love it!
- The first menu seems to have an alpha value to make it semi-transparent... but subsequent menus appear solid.
screen shot 2016-03-11 at 1 12 25 am

**Comment by jherico** [comment]
Looks like that's explicit... see line 35 of interface/resources/qml/menus/VrMenuView.qml

**Comment by ctrlaltdavid** [comment]
Yes, the semi-transparent first level menu is intentional, per the UI Toolkit doc.

**Comment by ZappoMan** [comment]
hmmm - ok... well that sounds strange to me... I guess if that's what @RyanDowne and Alan want... then :+1: for implementing the spec!

**Comment by AlanZimmerman** [comment]
Just to clarify @ZappoMan, David is following the UI toolkit spec but the apparent opacity of this right now is displaying incorrectly because of an issue he's identified with QML. @David, is that issue a filed bug? 

This is what it's supposed to look like. Note the second level has to be 100% for the parent dialog not to show through:
screen shot 2016-03-11 at 2 00 40 pm

**Comment by ctrlaltdavid** [comment]
@AlanZimmerman Yes, the opacity issue is a filed bug. It seems to be worse at lower opacity values than higher.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b9319b29e0bd8fb9e0714eece169a7da67f6755 available at: https://gist.github.com/3273772a6aa18abb95df<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7321.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7321.dmg

**Comment by ctrlaltdavid** [comment]
This finishes restyling what was there plus adds shortcut keys and separators.
Notes:
- View menu could perhaps do with radio buttons instead of checkboxes for some items (e.g., Display menu items).
- Bookmarks list might need to be made scrollable sometime.

**Comment by ZappoMan** [comment]
Tested Windows 8 -- seems to work and match the spec. QA Passed

**Pull request merged**
