### PR TITLE
Fix auto lasering locked web entities & only auto laser tablet and web overlays

### PR DESCRIPTION
**Pull request by dback2**
Prevent automatically showing the laser when pointing at a web entity that is locked since it can't be interacted with anyway.

Also only automatically show the laser when pointing at tablet or web overlays (as opposed to all overlays with ignoreRayIntersection=false before).

Addresses: https://highfidelity.fogbugz.com/f/cases/15630/

Test Plan:
-Enter Interface in HMD.
-Open tablet and point right hand at tablet verify the laser automatically shows without holding down the trigger.
-Point right hand away from tablet and point left hand at tablet to verify the same behavior.
-Open Create and create a Web entity.
-Exit Create and point right hand and left hand individually at the Web entity to verify the laser automatically shows and pressing the trigger allows interacting with the web page.
-Open Create and select the Web entity created above and lock it.
-Point right hand and left hand individually at the Web entity to verify the laser does NOT automatically show since it is locked.
-Go to 0,0,0 in your sandbox and enter the following in Developer menu -> Console:

Overlays.addOverlay("sphere", {
                        color: { "blue": 0, "green": 0, "red": 255 },
                        position: { x:0, y:0, z:0 },
                        dimensions: { x:1, y: 1, z:1 },
                        ignoreRayIntersection: false,
                        solid: true
                    });

as well as the following:

Overlays.addOverlay("web3d", {
            url: "https://www.google.com",
            position: {x: 0, y:1, z:0},
            dimensions: {x: .8, y: .45, z: 0.1},
        });

-In HMD verify when pointing either hand at the red sphere overlay created above that the laser is not automatically shown.
-Also verify when pointing either hand at the google.com Web overlay created above that the laser does automatically show and pressing the trigger allows interacting with the web page.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10603/HighFidelity-Beta-PR13383-fcccaae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10603/HighFidelity-Beta-PR13383-fcccaae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10603/HighFidelity-Beta-Interface-PR13383-fcccaae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10603/HighFidelity-Beta-PR13383-fcccaae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10603/HighFidelity-Beta-Interface-PR13383-fcccaae.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10619/HighFidelity-Beta-PR13383-fcccaae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10619/HighFidelity-Beta-PR13383-fcccaae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10619/HighFidelity-Beta-Interface-PR13383-fcccaae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10619/HighFidelity-Beta-PR13383-fcccaae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10619/HighFidelity-Beta-Interface-PR13383-fcccaae.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10667/HighFidelity-Beta-PR13383-0c644c0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10667/HighFidelity-Beta-PR13383-0c644c0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10667/HighFidelity-Beta-Interface-PR13383-0c644c0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10667/HighFidelity-Beta-PR13383-0c644c0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10667/HighFidelity-Beta-Interface-PR13383-0c644c0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
lasers and web entities look good.

**Pull request merged**
