### PR TITLE
Consolidate BufferView ctors to cpp

### PR DESCRIPTION
**Pull request by zzmp**
Moves a lot of ctor code to the cpp file, and uses delegating ctors.
This makes them less error-prone, and reduces compile-time in case of changes while debugging.

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Make sure rendering things still works ;)

**Comment by Nex-Pro** [comment]
will check this

**Comment by hifi-gustavo** [comment]
Build console output for commit: 263dcbb535d3248ea2c17c2d2087270065f9d24b available at: https://gist.github.com/228ebc7069c9dbff79bb64b2fa58ee22<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7686.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7686.dmg

**Comment by Nex-Pro** [comment]
Seems to work fine. Tested at Playa, Sandbox and music.
However content did not load at hell.
Bump map issue on the shipping containers was apparent at Playa.

**Comment by zzmp** [comment]
@Nex-Pro Anything in the logs about the content not loading in Hell?

**Pull request merged**
