### PR TITLE
Uniform story handling

### PR DESCRIPTION
**Pull request by howard-stearns**
single feed with snapshot and concurrency, no radio buttons, mini-card has a mini-button with hover that bring up the detail card, while  clicking anywhere else on the minicard takes you "there"

### CODE REVIEW

**Comment by howard-stearns** [comment]
This is DNM because:
1. I want UX review/feedback first
2. I'm not yet sure what the plan should be as to what filtering we should do for protocol, hours, restrictions.

**Comment by howard-stearns** [comment]
code reviewers: There's a pattern in Card.qml in which there are two labels -- one for the place and the other for number of users or the word "snapshot". Each label has text with a drop shadow, and an image in the same place, and a mouse area in the same place that has enter/exit handles that switch between the text/shadow vs the image.  In the case of "snapshot", it's worse because instead of text/shadow it is itself an image.

I don't like all the repeated code, but I couldn't figure out how to refactor this into a reusable module.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e9b743515aade784c2dc615d25206cb3419af99 available at: https://gist.github.com/0a53f7293a63d4cf1c7797b092602a38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-8e9b743.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-8e9b743.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c4ed84f9a6f334aebffde3585fc90bec80edf1ec available at: https://gist.github.com/0a53f7293a63d4cf1c7797b092602a38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-c4ed84f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-c4ed84f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17549348b4a9c4bcb59a721d6961456105fa6731 available at: https://gist.github.com/0a53f7293a63d4cf1c7797b092602a38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-1754934.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-1754934.dmg

**Comment by howard-stearns** [comment]
test plan:
- address bar should show snapshots and concurrency together. No places/snapshots buttons on the right.
- should show only snapshots or concurrency that are from places that are currently matching your client protocol, and which have unrestricted access.
- should label each suggestion with either a snapshot or a concurrency icon.  (If you're having trouble finding a concurrency card matching your protocol version, start typing "concurrency" in the address bar.)
- The snapshot/concurrency icon should highlight on hover, and clicking it should bring the card up (same behavior as used to happen when you clicked anywhere on the card).  Don't worry about styling within that pop-up card at this point. That's out of scope for this PR.
- Clicking anywhere else on the card should take you to the place (the placename target for concurrency cards, or the exact position/orientation where a snapshot was taken).

**Comment by hifi-gustavo** [comment]
Build console output for commit: a5fb0c9bd5d92b669503090a08b3865b84a8fdbb available at: https://gist.github.com/0a53f7293a63d4cf1c7797b092602a38<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-a5fb0c9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8638-a5fb0c9.dmg

**Comment by howard-stearns** [comment]
heavily tested in sandbox

**Pull request merged**
