### PR TITLE
Save toolbar position when moving it only when stopped moving it

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- The toolbar should follow your mouse more responsively now rather than lagging behind.
- The toolbar position should still be remembered over script restarts and Interface restarts.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6cb5617d3b1f98b746377690324b59eb4ea3d16 available at: https://gist.github.com/fe5ff8176e2f8b4d7b7c13379f7b3647<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8017.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8017.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Dramatic improvement over current state. Literal perfect execution as toolbar follows mouse responsively and does not lag behind. Toolbar position remembers position as script restarts and Interface restarts.  Literal perfect fix to a very big problem well done.

**Pull request merged**
