### PR TITLE
RC67: MS14758: Fix avatar reset when gifting worn avatar

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14758](https://highfidelity.manuscript.com/f/cases/14758/Avatar-URL-is-not-removed-when-user-gifts-an-avatar-they-are-wearing).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan

### Prerequisites
- A Wallet set up
- You're logged in to HiFi and your wallet is auth'd
- You have a connection to whom you can send a gift.

### Tests
1. Open Marketplace and filter for Avatars
2. Select the Buy/Get button for an avatar
3. Wear recently purchased avatar
4. Select "My Purchases" link on Marketplace homepage
5. Select the Context Menu (...) button on the card of current/recently purchased avatar
6. Select "Gift" button
7. Select "Confirm" button on "Change to Default Avatar" popup
8. Send avatar to another user
9. Reload content (Edit>Reload Content)
10. Verify that your avatar is still the default "woody" avatar.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9529/app_13106_PR_4ebed7605c979eed603a1d7738730537708e3359.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9529/HighFidelity-Beta-PR13106-4ebed7605c979eed603a1d7738730537708e3359.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9529/HighFidelity-Beta-Interface-PR13106-4ebed7605c979eed603a1d7738730537708e3359.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9529/HighFidelity-Beta-PR13106-4ebed7605c979eed603a1d7738730537708e3359.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9529/HighFidelity-Beta-Interface-PR13106-4ebed7605c979eed603a1d7738730537708e3359.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Default Avatar remains even after reloading content.

**Pull request merged**
