### PR TITLE
Interstitial domain full 74

### PR DESCRIPTION
**Pull request by sethalves**
- go to error-room when failing to connect to a full domain

https://highfidelity.fogbugz.com/f/cases/19295/Interstitial-page-freezes-when-trying-to-connect-to-domain-that-has-reached-maximum-user-capacity

https://github.com/highfidelity/hifi/pull/14196

### CODE REVIEW

**Comment by sethalves** [comment]
omg git

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13844/HighFidelity-Beta-PR14197-d1a4330.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13844/HighFidelity-Beta-PR14197-d1a4330.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13844/HighFidelity-Beta-Interface-PR14197-d1a4330.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13844/HighFidelity-Beta-PR14197-d1a4330.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13844/HighFidelity-Beta-Interface-PR14197-d1a4330.dmg

**Pull request closed without merging**
