### PR TITLE
fix -- don't tell steam about serverless domain urls

### PR DESCRIPTION
**Pull request by sethalves**
- don't tell steam about serverless domain urls

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/13983

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8539/HighFidelity-Beta-PR12801-148007435e7aeb784823898fa322d5d478d7dded.dmg

**Comment by sethalves** [comment]
to test:
- visit a serverful domain
- open GOTO and enter file:///~/serverless/tutorial.json
- enable advanced menus
- use menus --> navigation --> copy address
- open a test editor and paste the address.  make sure it's a file:// url and not the previous domain's hifi:// url
- ... more to come

**Comment by howard-stearns** [comment]
cool with me, I think.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8541/HighFidelity-Beta-PR12801-8de545acdf5907a2add6f6f12fe36c33cc2281ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8541/HighFidelity-Beta-PR12801-8de545acdf5907a2add6f6f12fe36c33cc2281ae.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
Snaps cannot be shared from the serverless domain, the appropriate error message displays.

**Pull request merged**
