### PR TITLE
Implemented no connection dialog for Tablet UI

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- open Goto and enter non existing address, f.ex: hifi://123.123.123.123
- after few seconds No connection dialog should appear within Tablet
- press OK will bring Home menu

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 209de29b2afdc0590a11fd67bd6ce3fc35cd0775 available at: https://gist.github.com/3c2848a79b8968b6fb9119edcd98ad9e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10066-209de29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10066-209de29.dmg

**Comment by 68chase** [comment]
Working this one

**Comment by 68chase** [comment]
Need clarification on this one, but I don't think this is working properly.  When I put in the address 123.123.123.123  I get the message in the tablet correctly:
image

However, when I click ok, it just brings the tablet back up:

image
  
To get back home I have to click Goto and then the Home button in the toolbar...If the second image I uploaded **_is_** the "Home Menu" then it passed.   If not, it failed..

**Comment by vladest** [comment]
yes, second screen is Tablet's home screen, sorry for misleading
so, the last item in Test plan should be 
press OK will bring Tablet's Home Screen

**Comment by 68chase** [comment]
Ok, thanks for the clarification

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 209de29b2afdc0590a11fd67bd6ce3fc35cd0775 available at: https://gist.github.com/3c2848a79b8968b6fb9119edcd98ad9e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10066-209de29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10066-209de29.dmg

**Pull request merged**
