### PR TITLE
RC56 into Master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Test Plan 1:
1) Basic smoke test. Compare against latest dev-download. Make sure in particular that model based overlays still function as normal. Things to try include: stylus on tablet, hand controller models (like when you pause in the HMD)
2) a) Run this client, in any domain (or even in the void)...
    b) go to /0.465893,-0.424502,0.0257262/0,0.697909,0,0.716186
    c) Using the JS Console... run this test script:
```
 var overlayID = Overlays.addOverlay("model",
        {
            name: "cards overlay",
            url: "https://hifi-content.s3.amazonaws.com/ozan/dev/anim/deck_of_cards/animated_cards_with_faces.fbx",
            position: { x: 0, y: 0, z: 0},
            animationSettings: {
                url: "https://hifi-content.s3.amazonaws.com/ozan/dev/anim/deck_of_cards/animated_cards_with_faces.fbx",
                fps: 30,
                running: true,
                loop: true
            }
        });
```
   
 d) you should see some cards animating... these are overlays.. they will not be visible to anyone else...
 
Test Plan 2:
- When changing avatars, you should never get stuck in a T-Pose from your own perspective.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3880/HighFidelity-Beta-PR11523-a1979a260032c061930dd77b37d1535fa6087ed8.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3881/HighFidelity-Beta-PR11523-a1979a260032c061930dd77b37d1535fa6087ed8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3881/HighFidelity-Beta-PR11523-a1979a260032c061930dd77b37d1535fa6087ed8.exe

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### PASS on all points.

No stuck T-Pose

Animated overlays work and are only visible to owner.

Tablet is fine. Hand controller models show up in Pause mode.

**Pull request merged**
