### PR TITLE
DNM - techproof - remove empty line

### PR DESCRIPTION
**Pull request by dback2**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2833/HighFidelity-Beta-PR11254-89e1a2d4d6aef030f60587f302087b734394bf2e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2833/HighFidelity-Beta-PR11254-89e1a2d4d6aef030f60587f302087b734394bf2e.exe

**Pull request closed without merging**
