### PR TITLE
Expose graphics fade to javascript...

### PR DESCRIPTION
**Pull request by howard-stearns**
... and consolidate the now three uses to one utility function.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca294fba8622ee6ab34f4e7f335ecd52c602ca9f available at: https://gist.github.com/29b9ac10f9946a00b680<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5272.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5272.dmg

**Comment by ZappoMan** [comment]
couple questions:
1) why do we want to expose this to JS?
2) shouldn't we consider just deleting this function, it was originally added when we did voxel animations... but no more voxels.
3) I'm about 99% certain that this code is attempting to do a domain wide fade (a cube the size of the entire domain) and it actually only does a 1 meter cube at the origin... it's been busted for a while... hence my recommendation that we just delete it.

**Comment by howard-stearns** [comment]
Good question. The code (to be either deleted or, in this pr, refactored) is currently used when the application joins or gets disconnected. I don't know whether it is working as intended, but the perceived effect is like respectively giving or taking a hit in a fight game.  

Given that perceived effect, this pr is use that for... (wait for it....) giving or taking a hit in a fight game.

Is there a better way to do that? Is this way a good enough placeholder by which to decide if we want to either remove it or improve it?

As a vehicle of exploration, the intended interface here is, e.g., in Javascript:
Script.graphicsFade(1, 1, 0) // or some other values of r, g, b.

**Comment by ZappoMan** [comment]
Ok - so I am still pretty certain you're not getting the effect you think you are. Does it actually show a flash on the screen? or not?

**Comment by howard-stearns** [comment]
Yes. You get a transparent flash of the given color. (I would not have used the term "fade", except that I wanted the code to be recognizable to the original author.☺️) The snippet in my previous comment does work in the JavaScript console.

**Comment by ZappoMan** [comment]
the OctreeFade class needs to be fixed to not use naked GL...

```
void OctreeFade::render(RenderArgs* renderArgs) {
    DependencyManager::get<GlowEffect>()->begin(renderArgs);

    glDisable(GL_LIGHTING);
    glPushMatrix();
    glScalef(1.0f, 1.0f, 1.0f);
    glTranslatef(voxelDetails.x + voxelDetails.s * 0.5f,
                 voxelDetails.y + voxelDetails.s * 0.5f,
                 voxelDetails.z + voxelDetails.s * 0.5f);
    glLineWidth(1.0f);
    DependencyManager::get<GeometryCache>()->renderSolidCube(voxelDetails.s, glm::vec4(red, green, blue, opacity));
    glLineWidth(1.0f);
    glPopMatrix();
    glEnable(GL_LIGHTING);
    
    
    DependencyManager::get<GlowEffect>()->end(renderArgs);
    
    opacity *= (direction == FADE_OUT) ? FADE_OUT_STEP : FADE_IN_STEP;
}
```

**Comment by ZappoMan** [comment]
honestly, I don't see how it can possibly be working for you... what OS did you test this on?

**Comment by ZappoMan** [comment]
If the desired effect is to show a fullscreen quad overlay of a flash of color, it seems like there are other ways in a script to do this (overlays for example)... This code is drawing a 3D cube...  presumably over the world space of the domain (although I question whether that actually works, that was its intent... if it works correctly then you won't get a full screen flash if you're standing outside the domain and are looking away from the domain. 

I guess my point is two fold:
1) The current code which is attempting to render a cube which covers the entire domain is buggy and needs to be fixed to not use naked GL
2) even if that code was working, does it actually give you the effect you want? I can point to several examples where it will not give you the effect you want, even if it did render correctly.

**Comment by ZappoMan** [comment]
ok - I have tested it, and it does seem to flash the whole screen, but I am pretty certain it only works by dumb luck. Regardless of why it works, it definitely needs to be fixed to remove the naked GL... until we get rid of all the naked GL will won't be able to merge the Vive work into the main code base... so, I'd suggest you either fix OctreeFade to work properly without naked GL or delete the OctreeFade code and use some other technique to implement a full screen color flash.

**Comment by howard-stearns** [comment]
Ok. I'll probably close this and submit a pr that rips out the existing fade code, and separately do the fight club stuff with an overlay. (I did have inconsistent results when I tried that a week ago, but maybe it has stabilized.)

That will leave us with no visual indication of join/leave (just the audio, provided by dialtone.js), which I think is fine.

**Comment by ZappoMan** [comment]
closing this for now - since it doesn't work on windows...

**Pull request closed without merging**
