### PR TITLE
Case 20521: Unplugging headphones with hifi open causes freeze

### PR DESCRIPTION
**Pull request by kencooke**
https://highfidelity.fogbugz.com/f/cases/20521/Unplugging-headphones-with-hifi-open-causes-freeze
https://highfidelity.fogbugz.com/f/cases/22193/Unplugging-headphones-with-other-avatars-around-causes-deadlock
https://highfidelity.manuscript.com/f/cases/22396/unplugging-dongle-of-Wireless-USB-headset-crashes-interface

Hot-plugging/unplugging a USB audio device can occasionally hang the audio driver and deadlock Interface. The call stack (below) shows this was occurring when our MIDI support attempts to rescan the MIDI bus after a USB device change. Due to a flaw in the legacy (Win32) MIDI API, attempting to close a MIDI device after it's been hot-unplugged has a significant chance of deadlock.

https://support.microsoft.com/en-us/help/4460006/midi-device-app-hangs-when-former-midi-api-is-used
```
This issue may occur after a Plug and Play (PnP) removal event, 
because the former Microsoft Windows MIDI API implementation 
does not correctly handle that removal in Windows 10.
```

Fixed by disabling detection of MIDI devices added/removed after starting Interface.
To restore this functionality, MIDI support should be reimplemented using WINRT/UWP.

callstack

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19225/HighFidelity-Beta-PR15515-408fb56.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19225/HighFidelity-Quest-Beta-PR15515-408fb56.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19225/HighFidelity-Beta-PR15515-408fb56.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19225/HighFidelity-Beta-Interface-PR15515-408fb56.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19235/HighFidelity-Beta-PR15515-408fb56.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19235/HighFidelity-Beta-Interface-PR15515-408fb56.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19235/HighFidelity-Beta-PR15515-408fb56.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19235/HighFidelity-Beta-Interface-PR15515-408fb56.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19235/HighFidelity-Beta-PR15515-408fb56.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19235/HighFidelity-Quest-Beta-PR15515-408fb56.apk)

**Comment by MiladNazeri** [comment]
Just FYI, this works as described.  On opening interface, MIDI events are received as expected.  Unplugging the USB connected to the keyboard stops getting messages.  Closing and opening interface gets the messages as expected.

**Pull request merged**
