### PR TITLE
fixing still only snap in snap app

### PR DESCRIPTION
**Pull request by wayne-chen**
MS issues:
- [#14327](https://highfidelity.fogbugz.com/f/cases/14327)
- [#15860](https://highfidelity.fogbugz.com/f/cases/15860)

**TEST PLAN**:
- Launch Interface in Desktop Mode
- Open Snap App
- Select `Still Only` as capture option
- Try to click snap button (in red) many times to snap still photos
- Only one photo should be saved and the Snap App UI should reappear

### CODE REVIEW

**Comment by zfox23** [comment]
👌 nice.

**Comment by zfox23** [comment]
whoops...the "close and comment" button is so close to the "comment" button!

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11074/HighFidelity-Beta-PR13526-aefa52b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11074/HighFidelity-Beta-PR13526-aefa52b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11074/HighFidelity-Beta-Interface-PR13526-aefa52b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11074/HighFidelity-Beta-PR13526-aefa52b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11074/HighFidelity-Beta-Interface-PR13526-aefa52b.exe

**Comment by qliejahner** [comment]
PASS @conklin94122 

Could not cause any unexpected effects by attacking the snapshot button.

**Pull request merged**
