### PR TITLE
update to serverless tutorial with RC66 fixes

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by tapalisa** [comment]
Should fix 2 issues:
too loud tutorial voice
HMD instructions showing up on the "explore" station before entering the zone.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8546/app_12804_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8546/HighFidelity-Beta-PR12804-0cf109e8acdb40645e5bb0ca1763c9e28e4fbde2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8546/HighFidelity-Beta-PR12804-0cf109e8acdb40645e5bb0ca1763c9e28e4fbde2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8559/app_12804_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8559/HighFidelity-Beta-PR12804-2e3db99f7e56735a03941e039f44d52028bd9d77.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8559/HighFidelity-Beta-PR12804-2e3db99f7e56735a03941e039f44d52028bd9d77.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing Complete - PASS @conklin94122 
Tutorial audio is now a comfortable volume, HMD instructions appear when they are supposed to, not before.

**Pull request merged**
