### PR TITLE
fix infinite loop on shutdown in OctreeInboundPacketProcessor

### PR DESCRIPTION
**Pull request by birarda**
- fixes an infinite loop in `OctreeInboundPacketProcessor::sendNackPackets()` that would occur if a node was removed between `isAlive` and `nodeWithUUID`

### CODE REVIEW

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d09f7b3d185c09229d19fac0bdf2ffebe4bce325 available at: https://gist.github.com/df83f2cb46f7ee4cf07b<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 927adfecfbb237ec5f0e955c7d9e25be3d5d42c1 available at: https://gist.github.com/60a9c6591f3eb2ba0036<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 927adfecfbb237ec5f0e955c7d9e25be3d5d42c1 available at: https://gist.github.com/df83f2cb46f7ee4cf07b<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 27227181f0acb8f66f8b02601956b92b39671a2a available at: https://gist.github.com/df83f2cb46f7ee4cf07b<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 557ab315d9f991ee4fba13a227101cfa4664980c available at: https://gist.github.com/df83f2cb46f7ee4cf07b<br/><br/>No installer was built for this commit

**Pull request merged**
