### PR TITLE
RC73.2: suppress traits larger than INT16_MAX bytes

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Review the latest note on https://highfidelity.manuscript.com/f/cases/18304/.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13675/HighFidelity-Beta-PR14146-09b7d2a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13675/HighFidelity-Beta-PR14146-09b7d2a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13675/HighFidelity-Beta-Interface-PR14146-09b7d2a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13675/HighFidelity-Beta-PR14146-09b7d2a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13675/HighFidelity-Beta-Interface-PR14146-09b7d2a.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122

**Pull request merged**
