### PR TITLE
fix vsync halving fps

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

*Make sure vsync is enabled!*

- Go somewhere with enough going on that your render rate drops below 60. (I use 
[this script](https://github.com/highfidelity/hifi/files/273408/stress.txt), from @jherico; by looking at more/less entities, I can modulate the render rate.)
- Ensure the render rate does not go from 60fps to 30fps. It should be capable of sustaining intermediate values, around 45fps. (This is assuming your monitor has a vsync target of 60fps).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by zzmp** [comment]
test this please

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test. Ran ```stress.js``` on ```playa``` and ```cellscience``` and was unable to get the Render Rate under 46.70.

**Comment by ZappoMan** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09932b5c85bfa7dee5b9c46ee70b2adfff112d87 available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2026226fe2b09a7664fd5b4a7f97246c7029584c available at: https://gist.github.com/7af532aa0229e7bd8556e54717bd3aa0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7941.dmg

**Pull request merged**
