### PR TITLE
New Zone Features

### PR DESCRIPTION
**Pull request by ZappoMan**
* add center in zone button to edit.js
* when importing domain sized zones, don't move them to import location
* have the stars "fade in" as the sun drops below the horizon, even in cases where you're inside the atmosphere

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 73428ec12d15bb2af8182d620338471cf3de6807 available at: https://gist.github.com/e1d7ebb9d8f8d4104c6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.dmg

**Comment by ZappoMan** [comment]
@murillodigital - can you look at this? it seems there's a disk space problem on one of our unix build machines?

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 73428ec12d15bb2af8182d620338471cf3de6807 available at: https://gist.github.com/e1d7ebb9d8f8d4104c6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2a1bf4e8cab30984cf10716f02407b3242720f5 available at: https://gist.github.com/e1d7ebb9d8f8d4104c6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4830.dmg

**Pull request merged**
