### PR TITLE
fix metadata hours migrations for new users/version bumps

### PR DESCRIPTION
**Pull request by zzmp**
Replicates the hotfix from #8148.

### CODE REVIEW

**Comment by kevinmthomasse** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbaf44097b930837a05fee09c08c127dd0d1b037 available at: https://gist.github.com/4e81e423d2f184a2062950298f6afe0c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8151.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8151.dmg

**Comment by jherico** [comment]
Do not create PR's into master for hotfixes from the original branches.  You need to create a branch off upstream/master, merge from stable, fix any conflicts and then create a PR for that branch.

**Comment by zzmp** [comment]
Replaced with #8152

**Pull request closed without merging**
