### PR TITLE
Mouse cursor should not visible in HMD Screen in HMD Mode

### PR DESCRIPTION
**Pull request by NeetBhagat**
Fix for 
1) case 3844 : Don-t-use-computer-cursor-in-VR-mode : https://highfidelity.fogbugz.com/f/cases/3844/Don-t-use-computer-cursor-in-VR-mode
2) case 4389 : Interface-takes-over-mouse-control : https://highfidelity.fogbugz.com/f/cases/4389/Interface-takes-over-mouse-control
3) case 3009 : Cursor-sometimes-follows-HMD-gaze-position-sometimes-doesn't : https://highfidelity.fogbugz.com/f/cases/3009/Cursor-sometimes-follows-HMD-gaze-position-sometimes-doesn-t

**HMD required**

# How To Test

1. Open Interface window , switch to HMD mode.
2. Observe that, you will not see mouse in HMD, but mouse will visible in Desktop screen and you will not able to click anywhere except top menu bar of interface window.
3. switch to Desktop mode, desktop mode will as work as it is.

**Expected Result :** 

1. In HMD mode, mouse should be visible to desktop users/spectators, but not be able to click anywhere except the top menu.
2. Mouse cursor should not be visible on HMD screen.
3. Smooth transition of mouse when switching between Desktop and HMD modes.

**Note:** Dev tested on Windows 10 + Oculus Rift

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/691/HighFidelity-Beta-PR10688-85f1f0bc604d20b9b15d66c0b18e4c5ad7a759d9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/691/HighFidelity-Beta-PR10688-85f1f0bc604d20b9b15d66c0b18e4c5ad7a759d9.dmg

**Comment by CainFoool** [comment]
Hey @NeetBhagat - is this QA Ready?

**Comment by NeetBhagat** [comment]
Hi @CainFoool , Yes it is. Though someone needs to label it as "QA Ready"

**Comment by CainFoool** [comment]
Okay cool - testing now.

**Comment by CainFoool** [comment]
# Test Passed 

When in HMD Mode, the mouse does not appear in the headset and only appears on the Monitor and doesn't let you click anywhere except the Menu Bar - which functions as expected. 

Switching to Desktop Mode re-enables the mouse and lets you do normal Desktop functions.

**Comment by jherico** [comment]
I feel like this should be tied to a preference, rather than hard-coded.  There may be plenty of situations where content developers might want to be able to use a mouse and keyboard while in the HMD.

**Comment by ZappoMan** [comment]
I absolutely want to be able to use the mouse in HMD... I do it all the time.

**Comment by CainFoool** [comment]
I do have to agree on this one - I've used the mouse when I've just had my HMD on in the past.

**Comment by themelissabrown** [comment]
@NeetBhagat can you implement this as a preference instead of a hard code?

**Comment by CainFoool** [comment]
^ As a follow up to that, defaulted to the way it currently is right now?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/889/HighFidelity-Beta-PR10688-4d59a14a385c37e72ef25e1951475457e69622ac.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/900/HighFidelity-Beta-PR10688-4d59a14a385c37e72ef25e1951475457e69622ac.exe

**Comment by Nex-Pro** [comment]
How will we select the stats during Smoke testing ? I always use the mouse for this. Is there another way to select the text in the output window ?

@NeetBhagat  Killing mouse with no ability to re-enable seems like a bad Idea.

Mouse is your friend.

**Comment by cozza13** [comment]
OK to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1273/HighFidelity-Beta-PR10688-4d59a14a385c37e72ef25e1951475457e69622ac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1273/HighFidelity-Beta-PR10688-4d59a14a385c37e72ef25e1951475457e69622ac.exe

**Comment by ZappoMan** [comment]
This PR needs to be reworked... there really are a couple of root problems with it. 

1) We can't simply remove mouse support in the HMD, it's too important and useful to too many tasks.
2) Re: FogBugz 4389 - The actual bug report is: "When switching between Desktop and HMD modes, you often get into a state in Desktop mode where you cannot move your mouse" -- this PR *does not do anything to fix this reported bug*
3) Re: FogBugz 3009 - this bug is actually about the "move mouse to where you're looking feature" - the intent of that feature is to actually move the mouse to where you're looking when you first show the mouse in HMD mode. This PR does nothing to actually address the behavior of that feature.

Adding an option isn't really the right solution to this either, since it just adds one more crazy and unexplained option to our settings.

I'm going to close this PR until a more clear spec is developed to address the root issues.

**Pull request closed without merging**
