### PR TITLE
Fix deadlock from accessing an initializing tablet

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
### QA Plan

If you experienced a deadlock with scripts on startup, run those scripts, and startup/shutdown a few times. You should no longer deadlock.
If something happens, please fill out a bugsplat, including all of the scripts you attempted to run, and ping me.

This fixes a deadlock which cannot be reliably reproduced. Once merged, the deadlock should stop cropping up in bug reports.

### CR

This solves a deadlock that can be induced with the below changes. Feel free to compile with these changes to test it. The deadlock is detailed in [fogbugz 4248](https://highfidelity.fogbugz.com/f/cases/4248/DEADLOCK-CRASH-at-startup-from-getTablet-contention-between-App-and-Script).
Please try to understand the deadlock before approving it, to make sure that this resolves it, and doesn't just not break anything else :).

```
diff --git a/interface/src/ConnectionMonitor.cpp b/interface/src/ConnectionMonitor.cpp
index fcb1908994..df59fb7db0 100644
--- a/interface/src/ConnectionMonitor.cpp
+++ b/interface/src/ConnectionMonitor.cpp
@@ -19,7 +19,7 @@

 // Because the connection monitor is created at startup, the time we wait on initial load
 // should be longer to allow the application to initialize.
-static const int ON_INITIAL_LOAD_DISPLAY_AFTER_DISCONNECTED_FOR_X_MS = 10000;
+static const int ON_INITIAL_LOAD_DISPLAY_AFTER_DISCONNECTED_FOR_X_MS = 3000;
 static const int DISPLAY_AFTER_DISCONNECTED_FOR_X_MS = 5000;

 void ConnectionMonitor::init() {
diff --git a/libraries/script-engine/src/TabletScriptingInterface.cpp b/libraries/script-engine/src/TabletScriptingInterface.cpp
index aa9840b226..f3a8ac9635 100644
--- a/libraries/script-engine/src/TabletScriptingInterface.cpp
+++ b/libraries/script-engine/src/TabletScriptingInterface.cpp
@@ -42,6 +42,7 @@ QObject* TabletScriptingInterface::getSystemToolbarProxy() {
         connectionType = Qt::BlockingQueuedConnection;
     }

+    QThread::sleep(5);
     QObject* toolbarProxy = nullptr;
     bool hasResult = QMetaObject::invokeMethod(_toolbarScriptingInterface, "getToolbar", connectionType, Q_RETURN_ARG(QObject*, toolbarProxy), Q_ARG(QString, SYSTEM_TOOLBAR));
     if (hasResult) {
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62d90ae6bc8321bb6794288c3c7e7e2c24768580 available at: https://gist.github.com/039d1d6dbe56d4098200170a2456e2e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-62d90ae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-62d90ae.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70c2d7f80e482e6442996d7060952f7e512ff20e available at: https://gist.github.com/039d1d6dbe56d4098200170a2456e2e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-70c2d7f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-70c2d7f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0353940d9ebe721cb17e51f1ea1fb7d494bde917 available at: https://gist.github.com/039d1d6dbe56d4098200170a2456e2e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-0353940.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-0353940.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0353940d9ebe721cb17e51f1ea1fb7d494bde917 available at: https://gist.github.com/039d1d6dbe56d4098200170a2456e2e4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-0353940.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10354-0353940.dmg

**Comment by OmegaHeron** [comment]
Testing

**Comment by OmegaHeron** [comment]
Windows 10
General smoke test pass -- ran a variety of scripts, multiple runs of interface, multiple stop/start/restart running scripts.  I haven't had deadlock error this sets out to cleanse, so, no comment beyond it doesn't break anything I could find.

**Pull request merged**
