### PR TITLE
Fix Record app's toolbar button not highlighting when app dialog open

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
*Testing*

Run record.js from either the /unpublishedScripts/marketplace/record/ directory in a clone of https://github.com/ctrlaltdavid/hifi/tree/21546 or from the attached zip file.

[record.zip](https://github.com/highfidelity/hifi/files/1316637/record.zip)

When the Record app's dialog is open the app's button on the toolbar should be highlighted.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3461/HighFidelity-Beta-PR11411-80f56e48caff308426c4a06cbf36aa24e924a93a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3461/HighFidelity-Beta-PR11411-80f56e48caff308426c4a06cbf36aa24e924a93a.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
When the Record app's dialog is open the app's button on the toolbar should be highlighted. | Pass
When the "Stop recording automatically when reopen tablet or window" checkbox is selected, the recording is automatically stopped when you reopen the tablet or window. | Pass

All working as expected.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
