### PR TITLE
Fix AvatarManager.getPalData() returning data for just a single avatar

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
And fix up JSDoc.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

In a domain with several avatars in it (at least 3 including yourself).
Run the attached script, testPalData.js.

It should report to the program log the following:
- A list the UUIDs for all avatars in the domain.
- A list of all PAL data for all avatars in the domain.
- The PAL data for a single one of the avatars in the domain (the second in the list of avatars).

Note in particular, the third item should not be the PAL data for all avatars in the domain.

[testPalData.zip](https://github.com/highfidelity/hifi/files/2471586/testPalData.zip)

https://highfidelity.manuscript.com/f/cases/19085

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13835/HighFidelity-Beta-PR14194-2bd5605.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13835/HighFidelity-Beta-PR14194-2bd5605.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13835/HighFidelity-Beta-Interface-PR14194-2bd5605.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13835/HighFidelity-Beta-PR14194-2bd5605.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13835/HighFidelity-Beta-Interface-PR14194-2bd5605.exe

**Pull request closed without merging**
