### PR TITLE
expose position and orientation of HMD to Javascript.

### PR DESCRIPTION
**Pull request by thoys**
- HMD.orientation
- HMD.position

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8befade007bd18c47db4ee3487e6828fe6f0bd88 available at: https://gist.github.com/1f37a893c04ead505579<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.dmg

**Comment by hyperlogic** [comment]
This will give you the HMD position and orientation in sensor space.  Which isn't that useful. It might be better for scriptures to return the HMD position and orientation in world space.

To compute this multiply by the myAvatar's sensorToWorldMatrix.  Something like this:

                mat4 m = _myAvatar->getSensorToWorldMatrix() * _myAvatar->getHMDSensorMatrix();
                glm::vec3 hmdPos = extractTranslation(m));
                glm::quat hmdRot = glm::normalize(glm::quat_cast(m));

MyAvatar.getHMDSensorMatrix is just a copy of the same HMD values from the display plugin.

**Comment by thoys** [comment]
Hi HyperLogic, In my case the local position and orientation is more useful, I am offsetting a following camera with the HMD so the camera doesn't stay stale. I think this is good to have in the HMD context. As in world matrix do you mean that it would always give the position relative to the avatar?

**Comment by ZappoMan** [comment]
But doesn't the independent camera take world coordinates? It seems like you could just as easily implement what you want with world frame as well.

**Comment by hyperlogic** [comment]
@thoys The position and orientation returned by your functions are in *sensor* space, not local to the avatar.  In the Oculus DK2, on startup, the orientation usually matches, but starts to diverge if you step away from the sensor camera and turn.  In the HTC Vive, however the orientation will only match if you happen to be aligned with the room origin, which (depending on how you've calibrated things, might not line up with the avatar's local orientation.

Anyhow, if the above snippet that returns the coordinates in world space is not enough.  You can transform them into the coordinate frame of the avatar.  either in the C++ code or JavaScript. Something like this should do the trick.

    mat4 m = _myAvatar->getSensorToWorldMatrix() * _myAvatar->getHMDSensorMatrix();
    glm::vec3 hmdAvatarPos = extractTranslation(m) - _myAvatar->getPosition();
    glm::quat hmdAvatarRot = glm::inverse(_myAvatar->getOrientation()) * glm::normalize(glm::quat_cast(m));

**Comment by thoys** [comment]
hehe , my JS code is a bit longer now, instead of:
```js
        if (applyHMDOffsets) {
            Camera.position = Vec3.sum(_this.position, HMD.position);
            Camera.orientation = Quat.multiply(_this.orientation, HMD.orientation);
            return;
        }
```

I use your suggested method now:
```js
        if (applyHMDOffsets) {
            Camera.position = Vec3.sum(_this.position, Vec3.subtract(HMD.position, MyAvatar.position));
            Camera.orientation = Quat.multiply(_this.orientation, Quat.multiply(Quat.inverse(MyAvatar.orientation), HMD.orientation));
            return;
        }
```

Thanks @hyperlogic and @ZappoMan

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e8fc08458b32c396a2eb49b4ca8f6124f5a1025 available at: https://gist.github.com/1f37a893c04ead505579<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.dmg

**Comment by ZappoMan** [comment]
@thoys - you need to merge with upstream master, your branch is out of date

**Comment by thoys** [comment]
Again? ;)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e52fcb857a031e36d9e588949a7c881b231c466 available at: https://gist.github.com/1f37a893c04ead505579<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.dmg

**Comment by ZappoMan** [comment]
build failed... I think that some of the APIs you were using have been changed/removed...

**Comment by thoys** [comment]
@ZappoMan again haha, hopefully no one reverts their code that involves this PR today :+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad5a6fac626b1c6d5a119842c7c8c622687ce340 available at: https://gist.github.com/1f37a893c04ead505579<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5988.dmg

**Pull request merged**
