### PR TITLE
Sys tray osx fixes

### PR DESCRIPTION
**Pull request by roxanneskelly**
PR for systray OSX Build fixes

**_This PR will likely be closed in favor of  https://github.com/highfidelity/hifi/pull/14088, to which this content has been combined. However, it is being left open for now, for development convenience to have a reference build._**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13455/HighFidelity-Beta-PR14108-fb3205a.apk

**Comment by howard-stearns** [comment]
I think this maybe includes, of necessity, some stuff from 
https://github.com/highfidelity/hifi/pull/14088 and thus should be merged (if at all, and only when ready of course), after 14088 is merged.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13455/HighFidelity-Beta-PR14108-fb3205a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13455/HighFidelity-Beta-Interface-PR14108-fb3205a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13455/HighFidelity-Beta-PR14108-fb3205a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13455/HighFidelity-Beta-Interface-PR14108-fb3205a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13465/HighFidelity-Beta-PR14108-6393f90.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13465/HighFidelity-Beta-PR14108-6393f90.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13465/HighFidelity-Beta-Interface-PR14108-6393f90.dmg

**Comment by howard-stearns** [comment]
https://highfidelity.fogbugz.com/f/cases/18960/Tray-Notifier-OSX-Bug-Fixes

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13468/HighFidelity-Beta-PR14108-0c1bef6.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13468/HighFidelity-Beta-PR14108-0c1bef6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13468/HighFidelity-Beta-Interface-PR14108-0c1bef6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13471/HighFidelity-Beta-PR14108-edd354d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13471/HighFidelity-Beta-PR14108-edd354d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13471/HighFidelity-Beta-Interface-PR14108-edd354d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13471/HighFidelity-Beta-PR14108-edd354d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13471/HighFidelity-Beta-Interface-PR14108-edd354d.exe

**Comment by roxanneskelly** [comment]
Leaving this DNM as it needs 14088 checked in first, and it's currently undergoing test.

There may be another fix in this branch, as well.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13486/HighFidelity-Beta-PR14108-113ad3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13486/HighFidelity-Beta-PR14108-113ad3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13486/HighFidelity-Beta-Interface-PR14108-113ad3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13486/HighFidelity-Beta-PR14108-113ad3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13486/HighFidelity-Beta-Interface-PR14108-113ad3d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13527/HighFidelity-Beta-PR14108-010e209.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13527/HighFidelity-Beta-PR14108-010e209.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13527/HighFidelity-Beta-Interface-PR14108-010e209.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13550/HighFidelity-Beta-PR14108-34a7aff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13550/HighFidelity-Beta-Interface-PR14108-34a7aff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13550/HighFidelity-Beta-PR14108-34a7aff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13550/HighFidelity-Beta-Interface-PR14108-34a7aff.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13573/HighFidelity-Beta-PR14108-2852dc8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13573/HighFidelity-Beta-PR14108-2852dc8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13573/HighFidelity-Beta-Interface-PR14108-2852dc8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13573/HighFidelity-Beta-PR14108-2852dc8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13573/HighFidelity-Beta-Interface-PR14108-2852dc8.exe

**Comment by roxanneskelly** [comment]
Closing as everything of note has been moved into 14088

**Pull request closed without merging**
