### PR TITLE
WL 21400 -- Setting that lets you switch from cursor to reticle

### PR DESCRIPTION
**Pull request by humbletim**
#### Testing

* Launch this PR build of Interface.
  - (using stock settings) Verify that the mouse cursor displays as the normal arrow icon.
* Enable the new reticle override in "Settings > General...":
image
 (and hit "Save Changes").
  - Verify that the mouse cursor now displays as a circular icon:
image
* Restart the application.
  - Verify the mouse cursor is still using a circular icon after restart.
* Disable the reticle override in "Settings > General...".
  - Verify that the mouse cursor displays as the normal arrow icon again.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1080/HighFidelity-Beta-PR10808-c10475186c32bef0331a686cc3d5eb0c8603c457.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1080/HighFidelity-Beta-PR10808-c10475186c32bef0331a686cc3d5eb0c8603c457.dmg

**Comment by Nex-Pro** [comment]
Testing this

**Comment by themelissabrown** [comment]
rebuild this please

**Comment by themelissabrown** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1886/HighFidelity-Beta-PR10808-c10475186c32bef0331a686cc3d5eb0c8603c457.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1886/HighFidelity-Beta-PR10808-c10475186c32bef0331a686cc3d5eb0c8603c457.dmg

**Comment by Nex-Pro** [comment]
### FAIL 
@humbletim  I'm getting a black square rather than a currsor in desktop mode. 

hifi-snap-by--on-2017-07-24_20-43-53

**Comment by humbletim** [comment]
@Nex-Pro oops forgot to commit the cursor PNGs before -- once the new build is ready the feature should be good to go again for retesting.

**Comment by Nex-Pro** [comment]
@humbletim I figured that.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1891/HighFidelity-Beta-PR10808-de6975b22754c6deb8438d234fbb77eb972cb728.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1891/HighFidelity-Beta-PR10808-de6975b22754c6deb8438d234fbb77eb972cb728.exe

**Comment by Nex-Pro** [comment]
retesting

**Comment by Nex-Pro** [comment]
### PASS on all test criteria.

**Pull request merged**
