### PR TITLE
change docs link on Sandbox splash screen

### PR DESCRIPTION
**Pull request by birarda**
- updated docs link from Sandbox splash screen

### CODE REVIEW

**Comment by birarda** [comment]
To test, run the PR Sandbox without copying settings from production install. Instead of "To see how, check out The Basics" it should read "To get started exploring and creating, check out our Quick-start Guide". The link should go to https://docs.highfidelity.com/docs/explore.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f5fdc9e28f6ba35683c632875a0999415a821783 available at: https://gist.github.com/eb59fa51635e3406419102f507301e04<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7755.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7755.dmg

**Comment by Nex-Pro** [comment]
Win10 16gb
Test successful: Pass

**Comment by bluetoe** [comment]
works for me too on win 7

**Pull request merged**
