### PR TITLE
don't check for user membership in a null list of groups

### PR DESCRIPTION
**Pull request by sethalves**
- domain-server group-related log-spam is reduced in the case where settings mention no groups

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make sure groups are working as expected
- if the domain-server settings list no groups, make sure the domain-server does log "getIsGroupMember api call failed: QNetworkReply::NetworkError(ProtocolInvalidOperationError)" every 15 seconds

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1625/Domain-Server-getIsGroupMember-spam

**Comment by hifi-gustavo** [comment]
Build console output for commit: f546524c1f92b7cad454726a8a751ba7bda9c8a0 available at: https://gist.github.com/03a5181dc5b361de6e3400488841b832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-f546524.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-f546524.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbb0a4203b406701c450b64eaf95211ec48e2519 available at: https://gist.github.com/03a5181dc5b361de6e3400488841b832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-cbb0a42.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-cbb0a42.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbb0a4203b406701c450b64eaf95211ec48e2519 available at: https://gist.github.com/03a5181dc5b361de6e3400488841b832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-cbb0a42.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8648-cbb0a42.dmg

**Comment by OmegaHeron** [comment]
This works for me - **but** please find someone who has/uses groups and understands them 100% to do a test pass in case I missed something.  It solves log spam if you have no group defined, I'm just not qualified to say it does/does not break anything with groups function.

**Comment by OmegaHeron** [comment]
@sethalves - I think I've discovered where error on api/v1/user/friends comes from.

It's a case where DS has an access token that's not attached to a HF account as in temporary generated.  Makes sense since an access token not connected to a real person's account via HF would have difficulty fetching friends of Domain Holder's list since there isn't one...

**Comment by thoys** [comment]
## QA test report

- The error messages are not visible on empty group list
- The group permissions still work, tested with `thoys` group and `kick` permissions

QA Pass

**Pull request merged**
