### PR TITLE
Added to the whiteboard model, and some bug fixes

### PR DESCRIPTION
**Pull request by ericrius1**
The colors palette, eraser, and color indicator are now contained in models. The whiteboard surface itself now lies on an easel instead of floating in the air. Models are designed and composed to avoid problems with picking the wrong color, erasing the board accidentally, and drawing on non-surface parts of the board.

Additionally, a bug where grabbing whiteboard surface with non-painting hand was making drawing overlays invisible has been fixed.

### CODE REVIEW

**Comment by ericrius1** [comment]
TESTING URL: https://rawgit.com/ericrius1/hifi/closePaintModel/examples/painting/whiteboard/whiteboardSpawner.js

**Comment by imgntn** [comment]
@ericrius1 whoa... it's... blue?

**Comment by imgntn** [comment]
@ericrius1 the colors on the bottom don't match the colors that get painted

**Comment by imgntn** [comment]
@ericrius1 i'm not sure what the box above the board but under the 'Erase Everything' entity is?  also, erase entity is hard to read in black text on purple

**Comment by imgntn** [comment]
looks good to me -- for v2 maybe a spotlight pointed at the board so you don't see the glare on the ground, but maybe you'd see it on the board then so i don't know.  i dont think avatars cast shadows yet so having it behind you on the board might be alright.  anyhow, good stuff!!

**Pull request merged**
