### PR TITLE
Fix bug preventing 'get' buttons from working in Marketplace

### PR DESCRIPTION
**Pull request by zfox23**
😆 

**Test Plan:**
1. Point your Interface client to the staging Metaverse
    - You need an environment variable `HIFI_METAVERSE_URL` with `https://staging.highfidelity.com` as the value
2. Create a wallet if you don't already have one
3. Look for 'Staging Flare Gun' in the marketplace, and click on it
4. Verify that the button that normally is blue, and suggests you purchase it, is now grey, and says "sold out"
5. Try to click the button -- nothing happens.
6. Look for "Finnegon" in the marketplace, and click on it
7. Verify that the button says "Get Item", and that, when you click on it, you see the Confirm Purchase screen

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5736/app_12023_PR.apk

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5736/HighFidelity-Beta-PR12023-ed5da4f83b59797ed81b0706a8616a6aa38ac9f3.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Point your Interface client to the staging Metaverse | 👍 
You need an environment variable HIFI_METAVERSE_URL with https://staging.highfidelity.com as the value | 👍 
Create a wallet if you don't already have one | 👍 
Look for 'Staging Flare Gun' in the marketplace, and click on it | 👍 
Verify that the button that normally is blue, and suggests you purchase it, is now grey, and says "sold out" | 👍 
Try to click the button -- nothing happens. | 👍 
Look for "Finnegon" in the marketplace, and click on it | 👍 
Verify that the button says "Get Item", and that, when you click on it, you see the Confirm Purchase screen | 👍 

Passed with [Shooting Stars](https://www.youtube.com/watch?v=feA64wXhbjo) 🎊 ⭐️

**Comment by zfox23** [comment]
build this please

**Comment by zfox23** [comment]
👿

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5739/app_12023_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5739/HighFidelity-Beta-PR12023-ed5da4f83b59797ed81b0706a8616a6aa38ac9f3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5739/HighFidelity-Beta-PR12023-ed5da4f83b59797ed81b0706a8616a6aa38ac9f3.dmg

**Pull request merged**
