### PR TITLE
Punchlist fixes for DS

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4846/HighFidelity-Beta-PR11795-d62c98c6e2a99224461e97d76ed08cf677e549d1.exe

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4856/HighFidelity-Beta-PR11795-ecc76ab321eeec410f6bd8c56aabb43b5ef6b74a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4856/HighFidelity-Beta-PR11795-ecc76ab321eeec410f6bd8c56aabb43b5ef6b74a.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4889/HighFidelity-Beta-PR11795-b5c4517ee73e2017c18f74941a82b8ddc33b7764.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4889/HighFidelity-Beta-PR11795-b5c4517ee73e2017c18f74941a82b8ddc33b7764.dmg

**Comment by huffman** [comment]
TestRail tests for testing:
 * https://highfidelity.testrail.net/index.php?/cases/view/2179 
 * https://highfidelity.testrail.net/index.php?/cases/view/2175

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
[TestRail Result 1023](https://highfidelity.testrail.net/index.php?/runs/view/1023&group_by=cases:section_id&group_order=asc)

**Pull request merged**
