### PR TITLE
More JSDoc formatting changes

### PR DESCRIPTION
**Pull request by jennaingersoll**
Fixes a number of formatting issues reported with the API docs:

[DOC-110](https://highfidelity.atlassian.net/browse/DOC-110): Fix formatting for "spring" ActionType
[DOC-111](https://highfidelity.atlassian.net/browse/DOC-111): Fix spacing throughout API docs! See detailed changes in Jira issue
[DOC-161](https://highfidelity.atlassian.net/browse/DOC-161): Add lists to findableBy and audioListenerMode properties

Other changes in PR:

- Removed blank Description heading from Globals page (global.html)
- Changed font size of Parameters and Example heading in Method Details, Type Definitions, and Signal Details so that its larger than the text size.
- WalletScriptingInterface.limitedCommerce property - added Steam to list of limited commerce versions
- Fixed typo in MyAvatar.html#.setParentJointIndex

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
I'm preparing an alternative PR that fixes invalid HTML generation as the root cause of whitespace issues. It will also include the other JSDoc fixes in this PR.

**Comment by ctrlaltdavid** [comment]
Alternative PR: https://github.com/highfidelity/hifi/pull/16224

**Comment by jennaingersoll** [comment]
Closing in favor of PR16224

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Pull request closed without merging**
