### PR TITLE
Adding GL 4.5 backend and tests

### PR DESCRIPTION
**Pull request by jherico**
This adds the GL 4.5 backends.  The 4.5 backend will be used only if the current context version is greater than or equal to 4.5 ***and*** the environment variable HIFI_ENABLE_OPENGL_45 is set.

## Issues

* Test code needs more coverage of the GPU library (materials, simple drawing)
* Test code needs to be refactored to automatically run a series of test cases and for each one produce and publish a resulting image.  Reference images should be created and stored in a known location so that QA can be done by executing the tests on a given backend and comparing the output images with the reference images.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9edd05410639f3f31a2c80c950123e735c4447f4 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 485a9f577d79ccf8acaa5e222a0aa0a4e9cf32a2 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ef258c14279e3a454a9b29ea240981eba5546c7 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 06f5dc76cfe56030a795d5ef52350a0b71899bcf available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fadd38b92a22820ae30efc881cb8721ca9d5abeb available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 084eb6d2e7aa3d29e3baaafbcacc8a11d059764a available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2221ada8ff929a55c7c3b812e3b5ef828db32382 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1cc83075d3e90c7d2012e9ef38ecaed7412b737c available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 64bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**
All standard tests possible pass **without env var set**  - Unable to test at Playa or others due to proto mismatch.

Setting env var HIFI_ENABLE_OPENGL_45 with value TRUE results in immediate crash - 3 tries - 3 crashes - bugsplats sent.  WIndows requires a value so I just pulled TRUE from random brain since it wasn't specified if there's  a specific value it should be set to.

QA Fail - My card/driver should have no problem with OGL4.5

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80951550ce6618bc388facfcfcb6453b3e184792 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**
All possible standard tests pass.  Setting HIFI_ENABLE_OPENGL_45=TRUE gives same result - all possible tests pass.  Is there a log indication that env var was picked up and this alternate mode is in use?  I couldn't find it among all the spew if there is.  Was looking for something (other than a crash) to insure I'm actually running on alternate GL mode.

QA Pass pending clarification if I've **really** successfully ran this GL4.5 mode.

**Comment by jherico** [comment]
@OmegaHeron there's no log output that says which backend is in use.  But that will likely be something we want for debugging issues, so I'll add something.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 40564bc62d1b4b7459f03927c8597b301304cba7 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - now I see in log;
`[05/23 21:04:11] [DEBUG] OpenGL 4.5 detected`
Even though I do not have env var set.  My system env dumped below...

C:\Users\Joe>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Joe\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-6PI66GC
ComSpec=C:\WINDOWS\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\Joe
IPG_Dir=C:\Program Files\Intel\Power Gadget 3.0
IPG_Ver=3.0
LOCALAPPDATA=C:\Users\Joe\AppData\Local
LOGONSERVER=\\MicrosoftAccount
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;;C:\Program Files (x86)\NTP\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\Intel\
PUBLIC=C:\Users\Public
RANDFILE=C:\Program Files (x86)\NTP\etc\.rnd
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Joe\AppData\Local\Temp
TMP=C:\Users\Joe\AppData\Local\Temp
USERDOMAIN=DESKTOP-6PI66GC
USERDOMAIN_ROAMINGPROFILE=DESKTOP-6PI66GC
USERNAME=Joe
USERPROFILE=C:\Users\Joe
windir=C:\WINDOWS

From GUI Control Panel view

capture

**Comment by jherico** [comment]
The latest commit now enables the GL 4.5 backend unless you set a different environment variable to disable it:  `HIFI_DISABLE_OPENGL_45`

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2e9873fa62f6bd6040763f4352ae95c9fd53a7b available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
Ok - one last time.  Windows 10 - 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**

Env var HIFI_DISABLE_OPENGL_45 set
[05/24 10:58:05] [DEBUG] OpenGL 4.5 not detected / enabled, using compatibility backend
Env var not set
[05/24 11:00:44] [DEBUG] OpenGL 4.5 detected

QA Pass  **If the intent is to make OpenGL 4.5 default**  The original spec listed here seemed to indicate enabling 4.5 would be the takes effort option.

**Comment by jherico** [comment]
@OmegaHeron I've switched it back to requiring the 'enable' flag to use OpenGL 4.5.  Also if this flag is enabled it will automatically turn on OpenGL debug logging, so in the event of crashes related to the GL 4.5 code, we will hopefully get some idea of what happened.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c8dd9f3d5034366b7170548e583d98d7a2f19f0 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b3f151dc9d1d3abf83551b5801a9432a59bee1c5 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 64 bit - i5 6500 CPU - GTX970 GPU - **Desktop mode - keyboard/mouse**

Without variable set:  `[05/31 19:01:17] [DEBUG] Using OpenGL 4.1 backend` seen
With variable set:  `[05/31 19:03:31] [DEBUG] Using OpenGL 4.5 backend` seen

With 4.5 enabled I'm getting a non-stop log flood with;

`[05/31 19:04:50] [DEBUG] QOpenGLDebugMessage("APISource", 1282, "GL_INVALID_OPERATION error generated.", "HighSeverity", "ErrorType")`

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ab0365b2c2ef17bfae1169dd12ba85cb7a2bf4b available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by jherico** [comment]
@OmegaHeron the logged errors should be resolved.

**Comment by OmegaHeron** [comment]
I'll retest and do full QA battery once storms pass over.  Computer is one of few things Southern people don't care for fried.  ;)

**Comment by OmegaHeron** [comment]
Without Env Var set;

`[06/02 09:37:08] [DEBUG] GPU:`
`[06/02 09:37:08] [DEBUG] 	card: "NVIDIA GeForce GTX 970"`
`[06/02 09:37:08] [DEBUG] 	driver: "10.18.13.6822"`
`[06/02 09:37:08] [DEBUG] 	dedicated memory: 4095 MB`
`[06/02 09:37:08] [DEBUG] QOpenGLDebugMessage("APISource", 1280, "GL_INVALID_ENUM error generated. Operation is not valid from the core profile.", "HighSeverity", "ErrorType")`
`[06/02 09:37:08] [DEBUG] Status: Using GLEW 1.13.0`
`[06/02 09:37:08] [DEBUG] `
`[06/02 09:37:08] [DEBUG] V-Sync is ON`
`[06/02 09:37:08] [DEBUG] `
`[06/02 09:37:08] [DEBUG] Using OpenGL 4.1 backend`

With Env Var set;
`[06/02 09:43:30] [DEBUG] GPU:`
`[06/02 09:43:30] [DEBUG] 	card: "NVIDIA GeForce GTX 970"`
`[06/02 09:43:30] [DEBUG] 	driver: "10.18.13.6822"`
`[06/02 09:43:30] [DEBUG] 	dedicated memory: 4095 MB`
`[06/02 09:43:30] [DEBUG] QOpenGLDebugMessage("APISource", 1280, "GL_INVALID_ENUM error generated. Operation is not valid from the core profile.", "HighSeverity", "ErrorType")`
`[06/02 09:43:30] [DEBUG] Status: Using GLEW 1.13.0`
`[06/02 09:43:30] [DEBUG] `
`[06/02 09:43:30] [DEBUG] V-Sync is ON`
`[06/02 09:43:30] [DEBUG] `
`[06/02 09:43:30] [DEBUG] Using OpenGL 4.5 backend`

**As expected** - lots of debug output with 4.5 Enabled - mainly like;
`[06/02 09:49:17] [DEBUG] QOpenGLDebugMessage("APISource", 131186, "Buffer performance warning: Buffer object 369 (bound to NONE, usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.", "MediumSeverity", "PerformanceType")`

So far so good - need to do the QA standard tests in both modes then done.

**Comment by OmegaHeron** [comment]
Several bugsplats recorded and sent while in GL4.5 mode.

I was running standard tests with http://rawgit.com/cozza13/QAtesting/master/dynamicrc.js
and had ran createTestBlocks.js - blocks created and were movable as usual.  Unloaded script and went to cleanup.  While in edit mode if I clicked any of the blocks - immediate crash.

Went back to GL4.1 mode (confirmed via log output) - entered edit mode, clicked on block and no crash/able to delete.

Will hold on additional tests until you've had a chance to review bugsplats.

**Comment by jherico** [comment]
@OmegaHeron I can't reproduce a crash on clicking on blocks in edit mode.  It may have been a bug in the existing code that got fixed in the mainline.  I've rebased the PR against the current production code.  Can you please see if you still get the crash?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3624a2d5bdb0f52db10ecbb5ddf22b3278d236fa available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
It's because I'm using alternative edit.js
http://ctrlaltstudio.com/downloads/hifi/scripts/edit.js
I don't have a lot of time to follow up on this now - weekends are not typically high availability for me here due to other commitments.

Windows 10 64 Bit - Confirmed Open GL4.5 is enabled.  Using script referenced, crash,  Using HF's edit.js no crash.  Considering popularity of alternative edit.js I still consider this or any other PR that makes me go back to default edit.js a fail.  In any case - I'll be available Monday to do any additional followup if required.

**Comment by jherico** [comment]
@OmegaHeron I tried with David's script.  still didn't have any problems with edits.  I'll see if I can exercise it some more.  I'll also take a look at the crash log and see if there's more I can do to replicate your environment.

**Comment by ZappoMan** [comment]
Ball is in @jherico's court

**Comment by OmegaHeron** [comment]
I don't see this as a overall QA Fail since it works in 4.1 mode and you have to jump through hoops to enter 4.5 mode - **as long as this is just a warmup to 4.5**.  It QA passes in (default) 4.1 mode, if QA fails (for me) in 4.5 mode.

**Comment by jherico** [comment]
I'm going to do another test pass on this this morning.  I'm liable to agree with @OmegaHeron in terms of passing the PR.  Right now you have to explicitly enable OpenGL 4.5, so people who want to try it out would be able to, and we could get bugsplat reports if it causes problems on some systems / hardware / environments, while users who are having serious problems with it can fall back to the known working 4.1 renderer.

**Comment by jherico** [comment]
@OmegaHeron if you get a chance could you do another pass on this?

**Comment by OmegaHeron** [comment]
I've made a todo for it first thing tomorrow.  East Coast here so it's pushing late for tonight.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f93a91a97ff442781b8d274256d022fcda058ec4 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f93a91a97ff442781b8d274256d022fcda058ec4 available at: https://gist.github.com/825bdb0812b9b85a74ffab80f07c3c0b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7937.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Testing Windows 10 - Desktop mode and Rift DK2 mode

Passes all standard tests in GL4.1 and GL4.5 mode.  Does not crash in GL4.5 mode with ctrlaltdavid edit script.  I didn't see any obvious visible changes between 4.1/4.5 mode - everything seemed to be proper regardless.

**Comment by samcake** [comment]
Reviewed again, i m all green.Waiting for QA approve to merge

**Pull request merged**
