### PR TITLE
Interstitial page demo (WIP)

### PR DESCRIPTION
**Pull request by druiz17**
Interstitial page demo (WIP)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8442/HighFidelity-Beta-PR12766-8ed7b257a0d137dd00876a7d3df156f3a736db4e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8442/HighFidelity-Beta-PR12766-8ed7b257a0d137dd00876a7d3df156f3a736db4e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8463/HighFidelity-Beta-PR12766-489a64e8273d83354cd64322330f67ebeb9bdc75.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8486/HighFidelity-Beta-PR12766-1aef62a03431d0002acedce8c83192bc40295578.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8489/HighFidelity-Beta-PR12766-1aef62a03431d0002acedce8c83192bc40295578.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8489/HighFidelity-Beta-PR12766-1aef62a03431d0002acedce8c83192bc40295578.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8495/HighFidelity-Beta-PR12766-2a261b41869910a3b4c40c36352c7be8b24f99e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8495/HighFidelity-Beta-PR12766-2a261b41869910a3b4c40c36352c7be8b24f99e6.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8511/HighFidelity-Beta-PR12766-8c7b1eb9ff3f63ae7772e99a77dc048caabe0626.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8515/HighFidelity-Beta-PR12766-feaf514cc9554c891f696686758aa71d09e4d3c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8515/HighFidelity-Beta-PR12766-feaf514cc9554c891f696686758aa71d09e4d3c4.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8598/app_12766_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8598/HighFidelity-Beta-PR12766-feaf514cc9554c891f696686758aa71d09e4d3c4.dmg

**Comment by RyanDowne** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8642/app_12766_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8642/HighFidelity-Beta-PR12766-feaf514cc9554c891f696686758aa71d09e4d3c4.dmg

**Comment by divyaelango88** [comment]
@maspring @sethalves @druiz17 can we make sure we get some basic android testing on this PR please when we think it is ready for merge. Thanks. 

@L370 George should be able to help with the most basic test of starting an app, going to 2 - 3 domains in android.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8642/HighFidelity-Beta-PR12766-feaf514cc9554c891f696686758aa71d09e4d3c4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8798/app_12766_PR_5d8901b74fb381877660f1242f2b832518aebf8e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8798/HighFidelity-Beta-PR12766-5d8901b74fb381877660f1242f2b832518aebf8e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8798/HighFidelity-Beta-Interface-PR12766-5d8901b74fb381877660f1242f2b832518aebf8e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8926/app_12766_PR_91f1959f5823b59e765d2d0b86eefa29a264c45e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8926/HighFidelity-Beta-PR12766-91f1959f5823b59e765d2d0b86eefa29a264c45e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8926/HighFidelity-Beta-Interface-PR12766-91f1959f5823b59e765d2d0b86eefa29a264c45e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8971/HighFidelity-Beta-PR12766-5319fa3599beed21097f366b552241eb82141d61.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8971/HighFidelity-Beta-Interface-PR12766-5319fa3599beed21097f366b552241eb82141d61.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8971/HighFidelity-Beta-PR12766-5319fa3599beed21097f366b552241eb82141d61.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8971/HighFidelity-Beta-Interface-PR12766-5319fa3599beed21097f366b552241eb82141d61.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8982/app_12766_PR_5694f9e9caccedcdcaab4c15f1e93d2475c7aa0c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8982/HighFidelity-Beta-PR12766-5694f9e9caccedcdcaab4c15f1e93d2475c7aa0c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8982/HighFidelity-Beta-Interface-PR12766-5694f9e9caccedcdcaab4c15f1e93d2475c7aa0c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8982/HighFidelity-Beta-PR12766-5694f9e9caccedcdcaab4c15f1e93d2475c7aa0c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8982/HighFidelity-Beta-Interface-PR12766-5694f9e9caccedcdcaab4c15f1e93d2475c7aa0c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8990/app_12766_PR_474648429a3241dadc3ea0cb31e599d1e7b93a3f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8990/HighFidelity-Beta-PR12766-474648429a3241dadc3ea0cb31e599d1e7b93a3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8990/HighFidelity-Beta-Interface-PR12766-474648429a3241dadc3ea0cb31e599d1e7b93a3f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8990/HighFidelity-Beta-PR12766-474648429a3241dadc3ea0cb31e599d1e7b93a3f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8990/HighFidelity-Beta-Interface-PR12766-474648429a3241dadc3ea0cb31e599d1e7b93a3f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9023/app_12766_PR_914242ee69cef79b86fc38ee0bc9bd8da9670b2e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9023/HighFidelity-Beta-PR12766-914242ee69cef79b86fc38ee0bc9bd8da9670b2e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9023/HighFidelity-Beta-Interface-PR12766-914242ee69cef79b86fc38ee0bc9bd8da9670b2e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9023/HighFidelity-Beta-PR12766-914242ee69cef79b86fc38ee0bc9bd8da9670b2e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9023/HighFidelity-Beta-Interface-PR12766-914242ee69cef79b86fc38ee0bc9bd8da9670b2e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9056/app_12766_PR_9399320f1396d6a57557d860227feda612760969.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9056/HighFidelity-Beta-PR12766-9399320f1396d6a57557d860227feda612760969.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9056/HighFidelity-Beta-PR12766-9399320f1396d6a57557d860227feda612760969.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9056/HighFidelity-Beta-Interface-PR12766-9399320f1396d6a57557d860227feda612760969.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9089/app_12766_PR_3531f520107bc0fe8985cf705e5a0e4f20e135d9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9089/HighFidelity-Beta-PR12766-3531f520107bc0fe8985cf705e5a0e4f20e135d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9089/HighFidelity-Beta-Interface-PR12766-3531f520107bc0fe8985cf705e5a0e4f20e135d9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9262/app_12766_PR_e457b92a63ab2b288b13539fa1e25eefaecbff42.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9262/HighFidelity-Beta-PR12766-e457b92a63ab2b288b13539fa1e25eefaecbff42.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9262/HighFidelity-Beta-Interface-PR12766-e457b92a63ab2b288b13539fa1e25eefaecbff42.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9389/app_12766_PR_92a0b21bd4792bf59d8d668b00f405f26fc41dc9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9389/HighFidelity-Beta-PR12766-92a0b21bd4792bf59d8d668b00f405f26fc41dc9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9389/HighFidelity-Beta-Interface-PR12766-92a0b21bd4792bf59d8d668b00f405f26fc41dc9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9389/HighFidelity-Beta-PR12766-92a0b21bd4792bf59d8d668b00f405f26fc41dc9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9389/HighFidelity-Beta-Interface-PR12766-92a0b21bd4792bf59d8d668b00f405f26fc41dc9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9445/app_12766_PR_8c68afa5d7695013120fac265ccfc4f25502cec8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9445/HighFidelity-Beta-PR12766-8c68afa5d7695013120fac265ccfc4f25502cec8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9445/HighFidelity-Beta-Interface-PR12766-8c68afa5d7695013120fac265ccfc4f25502cec8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9445/HighFidelity-Beta-PR12766-8c68afa5d7695013120fac265ccfc4f25502cec8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9445/HighFidelity-Beta-Interface-PR12766-8c68afa5d7695013120fac265ccfc4f25502cec8.exe

**Pull request closed without merging**
