### PR TITLE
BUGZ-927: Allow disabling of LOD from command line

### PR DESCRIPTION
**Pull request by jherico**
[BUGZ-927](https://highfidelity.atlassian.net/browse/BUGZ-927) Allow the LOD functionality to be disabled via command line argument, to the launcher can do so.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20260/HighFidelity-Beta-PR15889-a37a59c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20260/HighFidelity-Beta-Interface-PR15889-a37a59c.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20260/HighFidelity-Beta-PR15889-a37a59c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20260/HighFidelity-Quest-Beta-PR15889-a37a59c.apk)

**Comment by ZappoMan** [comment]
I think we should go with Zach's PR version of this instead, https://github.com/highfidelity/hifi/pull/15890

**Comment by ZappoMan** [comment]
going with the alternate solution

**Pull request closed without merging**
