### PR TITLE
fix case where servers could run without settings

### PR DESCRIPTION
**Pull request by birarda**
This fixes an issue the accidentally immediately failing messages-mixer exposed yesterday. It occurred when requesting settings from a domain-server on a hostname/port combination recently used by the kicked AC.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20485b817c33f607799fa80828678463e89129f5 available at: https://gist.github.com/59211a2cd41becdf9bdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ba0c9d0424a0f480753b5ddb28d6496d974e672 available at: https://gist.github.com/59211a2cd41becdf9bdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3773995bb7f6a4fa1bc1836a0e28ac6fbc5e57bd available at: https://gist.github.com/59211a2cd41becdf9bdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 08e6b63090fe3a157f365070e5b80d184dc67623 available at: https://gist.github.com/59211a2cd41becdf9bdb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6425.dmg

**Comment by ZappoMan** [comment]
Here's my testing plan for this...

1) Download and smoke test the Mac Stack Manager... just basic test to see that as build the stack manager runs as expected
2) clone the repo, build on windows, and run the domain-server + assignment-client and smoke test it for basic usage as well
3) then, in the cloned repo, add the "pattern" for server settings to message-mixer and see how the system behaves on startup.

**Comment by birarda** [comment]
Sounds right to me - I've done (1) via local build and (3) via local build.

**Comment by ZappoMan** [comment]
Mac stack manager seems broken - 
1) I can go to the settings page

**Comment by birarda** [comment]
As we just discovered, that's an issue with the PR build of stack-manager. Use local build of components if possible to test.

**Pull request merged**
