### PR TITLE
remove expired avatarEntities from their avatars

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13680/HighFidelity-Beta-PR14150-c3478dc.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13680/HighFidelity-Beta-PR14150-c3478dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13680/HighFidelity-Beta-Interface-PR14150-c3478dc.exe

**Comment by conklin94122** [comment]
@AndrewMeadows Is this QA Ready?

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
