### PR TITLE
Scripted Blendshapes and Procedural Face Movement Flags

### PR DESCRIPTION
**Pull request by amantley**
In this pr we addressed the problem where scripted blendshapes and procedural face movement were not working correctly together.  We added flags to the avatar data packet that indicate whether:
1) Audio driven procedural jaw and eyebrow movement is enabled, 
2) Procedural Blink behaviour is enabled and 
3) Procedural eyelid movement is enabled 
These are also now properties added to MyAvatar class.
To reflect these changes to AvatarData packet the **AvatarMixerPacketVersion** was changed to  ProceduralFaceMovementFlagsAndBlendshapes.  
We do not send the procedural data in the avatar data packet and instead compute that locally.  The procedural behaviour can be enabled and disabled with either a Face Tracker device attached or with blendshapes being set by script.  
In both cases the blendshapes are added to the avatar data packet.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10456/HighFidelity-Beta-PR13338-3f58202.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10457/HighFidelity-Beta-PR13338-b1c578e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10457/HighFidelity-Beta-Interface-PR13338-b1c578e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10457/HighFidelity-Beta-PR13338-b1c578e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10457/HighFidelity-Beta-Interface-PR13338-b1c578e.exe

**Comment by amantley** [comment]
# QA test

This pr addresses https://highfidelity.manuscript.com/f/cases/12607 and https://highfidelity.manuscript.com/f/cases/12605/Custom-blendshapes-modifying-facial-expressions-are-not-visible-to-other-users in Manuscript.  A copy of this test plan can be found there.

# Setup - 
Install the pr on two separate machines and have the two clients meet on localhost domain of one of the machines.  Alternatively you could have two different testers each run the client. Then load the [facialExpressions.js](https://cdn.rawgit.com/thoys/hifi-content/346a2ae1e0a062619c7d25c48fe51adf58298ed9/Prototyping/FacialExpressions/facialExpressions.js) script for both clients.

# Test plan:
1) Check that the facial expressions from the script are being sent to the other client.  
Press:
'H' = smile
'J' = laugh
'K' = flirt
'L = sad
'V' = angry
'B' = fear
'M' = disgust
'N' = neutral
 On one machine and see if the face of the avatar changes appropriately on the other machine.  

2) At this point all of the procedural face movement should be enabled so verify that these are still occurring on both machines. Specifically, a) are the mouth and eyebrows moving with changes in audio input b) are the eyes blinking c) do the eyelids follow the eye saccades.
3) Now force the face tracker to be enabled.  In the console MyAvatar.setForceFaceTrackerConnected(true), and verify that the procedural movement in 2 is still happening.  Then press 'm' to verify that scripted blendshapes are still working.
4) Disable the face tracker MyAvatar.setForceFaceTrackerConnected(false) and then disable audio driven face movement.  MyAvatar.hasAudioEnabledFaceMovement = false;  Now verify that the mouth and eyebrows have has stopped moving with changes in audio level.  Press 'm' to verify that scripted blendshapes are still working.  Repeat this for MyAvatar.hasProceduralEyeFaceMovement and MyAvatar.hasProceduralBlinkFaceMovement.
5) Set the properties in 4 all to false and turn on and off each one individually and verify that they are each working and that the scripted blendshapes are working.
6) Press 'k' to for each machine to open the mouth of each avatar with a blendshape.   Then close the facialExpressions  script on each client.  Verify that the mouths are not being stuck in their final blend position.   Both faces should have returned to neutral.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10465/HighFidelity-Beta-PR13338-dabcd4c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10465/HighFidelity-Beta-PR13338-dabcd4c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10465/HighFidelity-Beta-Interface-PR13338-dabcd4c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10465/HighFidelity-Beta-PR13338-dabcd4c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10465/HighFidelity-Beta-Interface-PR13338-dabcd4c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10526/HighFidelity-Beta-PR13338-042f902.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10526/HighFidelity-Beta-PR13338-042f902.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10526/HighFidelity-Beta-Interface-PR13338-042f902.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10526/HighFidelity-Beta-PR13338-042f902.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10526/HighFidelity-Beta-Interface-PR13338-042f902.exe

**Comment by qligmaloney** [comment]
Currently testing

**Pull request merged**
