### PR TITLE
RC67 merge back to master

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9350/app_13060_PR_30e808e1336326ad1d6b2733d7e021215c30744a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9350/HighFidelity-Beta-PR13060-30e808e1336326ad1d6b2733d7e021215c30744a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9350/HighFidelity-Beta-Interface-PR13060-30e808e1336326ad1d6b2733d7e021215c30744a.exe

**Comment by birarda** [comment]
We may as well wait for #13064 unless any of these are desperately needed in master now.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9365/app_13060_PR_a5753c6d946b4102906d118a5f4a9cf36721496b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9365/HighFidelity-Beta-PR13060-a5753c6d946b4102906d118a5f4a9cf36721496b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9365/HighFidelity-Beta-Interface-PR13060-a5753c6d946b4102906d118a5f4a9cf36721496b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9365/HighFidelity-Beta-PR13060-a5753c6d946b4102906d118a5f4a9cf36721496b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9365/HighFidelity-Beta-Interface-PR13060-a5753c6d946b4102906d118a5f4a9cf36721496b.dmg

**Pull request merged**
