### PR TITLE
Make non-dynamic entities collisionless during far-grab

### PR DESCRIPTION
**Pull request by druiz17**
Make non-dynamic entities collisionless during far-grab
fixes fogzbug issue - https://highfidelity.fogbugz.com/f/cases/8498/Possibly-modifying-the-recent-change-https-github-com-highfidelity-hifi-pull-11560-to-make-temporary-dynamic-be-collisonless

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan 
- create to entities that are not dynamic
- when performing a far grab on one of the entities
- the entity that you are far grabbing should be collisionless (should not collide with the other entity)

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by Nex-Pro** [comment]
Testing

**Comment by cain-kilgore** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4425/HighFidelity-Beta-PR11677-8d07f2a6a3fd202b35bc893a0149ce3f766d4f9b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4425/HighFidelity-Beta-PR11677-8d07f2a6a3fd202b35bc893a0149ce3f766d4f9b.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

create to entities that are not dynamic **Check**
when performing a far grab on one of the entities **Check**
the entity that you are far grabbing should be collisionless (should not collide with the other entity) **Check**
image


**Pass**

**Pull request merged**
