### PR TITLE
Changed scale of avatar and window title.

### PR DESCRIPTION
**Pull request by annabrewer**
This is for the summer internship final assessment, to make sure I can use Git and build the Interface.

### CODE REVIEW

**Comment by shanzzam** [comment]
Hey @annabrewer :  I can't approve this merge into our master branch. If you're intending to build locally follow the instructions here https://github.com/highfidelity/hifi/blob/master/BUILD.md

**Comment by shanzzam** [comment]
apologies @annabrewer ! I didn't have the right information previously. We'll get this built for you.

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14955/HighFidelity-Beta-PR14365-8bf01b6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14955/HighFidelity-Beta-PR14365-8bf01b6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14955/HighFidelity-Beta-Interface-PR14365-8bf01b6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14955/HighFidelity-Beta-PR14365-8bf01b6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14955/HighFidelity-Beta-Interface-PR14365-8bf01b6.exe

**Pull request closed without merging**
