### PR TITLE
Optional particle explorer properties fixes

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.manuscript.com/f/cases/16125/

Also fixes 0 values for optional properties being considered the same as NaN.

Test Plan:
-Launch Interface in desktop mode
-Enable Developer menu under Settings, paste the following lines into Developer > Console, and run it:
```
var properties = { 
type: 'ParticleEffect',
position: MyAvatar.position,
isEmitting:true,
emitAcceleration: Vec3.ZERO,
particleRadius: 0.03,
lifespan:10,
maxParticles:500,
textures:'http://hifi-content.s3.amazonaws.com/alan/dev/Particles/heart-2.png',
emitRate:100,
emitSpeed:1,
speedSpread: 0,
alpha:0.5
};
Entities.addEntity(properties, true);
```

-Select the new particle entity in Create, open the particle properties tab, and verify properties all populate the window as expected
-Under Radius, change the Particle Radius a few times and ensure Radius Start and Radius Finish values copy the Particle Radius value
-Also attempt to change the Particle Radius value using it's slider back and forth very quickly and ensure that the Radius Start and Finish values stay in sync with it and the particles actual visible radius appears to match the Particle Radius property value (this was the Manuscript bug above)
-Change Radius Start value to anything, modify Particle Radius again, and ensure the Radius Start value does not follow it anymore
-Change Radius Finish value to anything, modify Particle Radius again, and ensure the Radius Finish value does not follow it anymore
-Under Alpha, change the Alpha a few times and ensure Alpha Start and Alpha Finish values copy the Alpha value
-Change Alpha Start value to anything, modify Alpha again, and ensure the Alpha value does not follow it anymore
-Change Alpha Finish value to anything, modify Alpha again, and ensure the Alpha Finish value does not follow it anymore
-Under Color, change the Color a few times and ensure Color Start and Color Finish values copy red, green, and blue values from Color
-Change Color Start values to anything, modify Color again, and ensure the Color Start values do not follow it anymore
-Change Color Finish values to anything, modify Color again, and ensure the Color Finish values do not follow it anymore
-Create a new particle from Create
-With the new particle selected in particle properties tab, select back and forth between this new particle and the particle from above and ensure the particle properties are populated appropriately for the newly selected particle
-Attempt to change Particle Radius, Alpha, and Color values on the new particle as was done above on the Console-created particle but verify that the associated Start and Finish values do not follow it

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10941/HighFidelity-Beta-PR13481-2cdda23.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10941/HighFidelity-Beta-PR13481-2cdda23.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10941/HighFidelity-Beta-Interface-PR13481-2cdda23.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10941/HighFidelity-Beta-PR13481-2cdda23.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10941/HighFidelity-Beta-Interface-PR13481-2cdda23.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10966/HighFidelity-Beta-PR13481-e74d30c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10966/HighFidelity-Beta-PR13481-e74d30c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10966/HighFidelity-Beta-Interface-PR13481-e74d30c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10966/HighFidelity-Beta-PR13481-e74d30c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10966/HighFidelity-Beta-Interface-PR13481-e74d30c.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Fail @conklin94122 

Step 13: Colour Start and Colour Finish values revert back to the Colour value when swapping between two particles. The particle entity does retain the colours previously set by the user in world though

This does not occur on Stable or Master
Tested on Windows 10, Mac OSx 10.13.4
Desktop 
[Archive.zip](https://github.com/highfidelity/hifi/files/2150019/Archive.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11025/HighFidelity-Beta-PR13481-fd4a8fd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11025/HighFidelity-Beta-PR13481-fd4a8fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11025/HighFidelity-Beta-Interface-PR13481-fd4a8fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11025/HighFidelity-Beta-PR13481-fd4a8fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11025/HighFidelity-Beta-Interface-PR13481-fd4a8fd.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Particles work as expected and no longer lose their properties when selecting a new particle entity and then reselecting the old particle

**Pull request merged**
