### PR TITLE
[DNM] Context Overlays

### PR DESCRIPTION
**Pull request by davidkelly**
This is _not_ going into master yet.  Just wanted gustavo to build this so we can have some people try it out.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1796/HighFidelity-Beta-PR11008-b236a21adc3d98f5e4b5c5525ef77c793af284e5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1800/HighFidelity-Beta-PR11008-0544c1e56173e2f12c09142b0381f88eacddebce.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1800/HighFidelity-Beta-PR11008-0544c1e56173e2f12c09142b0381f88eacddebce.dmg

**Comment by davidkelly** [comment]
served its purpose

**Pull request closed without merging**
