### PR TITLE
Fixing recording interface times

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a27a2fba51c8a778cc234ac6bf1df2b3a1e3441 available at: https://gist.github.com/69c16574546768efc82e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6400.dmg

**Comment by samcake** [comment]
test this please

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a27a2fba51c8a778cc234ac6bf1df2b3a1e3441 available at: https://gist.github.com/69c16574546768efc82e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6400.dmg

**Pull request merged**
