### PR TITLE
Send avatar-joint translations at world scale

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Fogbugz: https://highfidelity.manuscript.com/f/cases/19401/My-avatar-appears-normally-to-me-but-everyone-else-sees-my-head-in-the-floor

Specifically this entry:
https://highfidelity.manuscript.com/f/cases/19401/#BugEvent.129699

Fixes the case where a large avatar is scaled down to regular size in the Interface UI. Also bumps avatar packet-version since it's an avatar-mixer protocol change.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14845/HighFidelity-Beta-PR14363-f88168b.apk

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
See also test plan in related partial fix: https://github.com/highfidelity/hifi/pull/14331#issuecomment-436013420

Two clients and sandbox from the PR are required; it is simplest to run the sandbox and local interface on one machine and the remote interface on a second machine.

- On both clients change the avatar to the problematic one above (Avatar -> link button in top pane -> Specify Avatar URL). Check that the avatar scaling is the default 1x (Avatar -> sliders button in header).  The avatar's height is about 19 m.
- Observe the local (3rd person view) and remote avatars on both machines.
- Reduce both avatars' scales with the slider to 0.1, resulting in normal sized avatars.

At full size the avatar's position will be incorrect both with & without this PR. The actual position will depend on the status of PR 14331. Once scaled down the avatars should be positioned correctly, move correctly, etc.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14845/HighFidelity-Beta-PR14363-f88168b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14845/HighFidelity-Beta-Interface-PR14363-f88168b.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15047/HighFidelity-Beta-PR14363-f88168b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15047/HighFidelity-Beta-PR14363-f88168b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15047/HighFidelity-Beta-Interface-PR14363-f88168b.dmg

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 . verified that when the avatar is shrunken down in size the avatars movements are normal and expected but when big the avatars movements are off due to the large size of the avatar.

**Pull request merged**
