### PR TITLE
equip via parenting rather than action

### PR DESCRIPTION
**Pull request by sethalves**
- equipping an entity is handled via parenting rather than an action (grabbing is still an action)
- change name of channel where updates about held entities are sent
- cleaned up grab script messaging to grabbed entities and updated toybox toys to track these changes
- added initial version of attachedEntitiesManager.js
- dynamic entities (if unlocked) are grabbable by default, others aren't.  Either can be changed with userData.
- entityMethods and messages related to grabbing state changes are only sent by the initial grab on an entity.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 11d2f9a8fcb52608764cd5ee8a4d4ef6e23f6fbf available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b7f8ef77d36b4f639b04e61368f3e7a2d5820b2 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9ca89172f6ee6c4dc855755a235a388e0ee3b703 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 464f74fc1ba413e8a7f6b4717379e757713db932 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c5c682887f66b96f42e0a13ac08d1feb0060684 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a16bc7d22df8ed688bc5384d0821957a6725ef4 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6697b5ae5fc8cb8af1b9876a69d6db75677d17cb available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc862980978728e879800092bd531f8c95ccc052 available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a4431560f70f81d337c659961baadfdb317507d available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a4431560f70f81d337c659961baadfdb317507d available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by imgntn** [comment]
i was getting some weird behavior when equipping unequipping things multiple times, but i need to do more testing today to confirm and get a solid repro case

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c5b0ec46e030255e568b9a9d91db3f4fd9695cd available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2207588c0114f500ef176c5bd2aa8556f7e10bfa available at: https://gist.github.com/6b52e4ec12452980082b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6948.dmg

**Pull request merged**
