### PR TITLE
RC65 mergeback PR #12550 to master

### PR DESCRIPTION
**Pull request by thoys**
original PR to RC65: https://github.com/highfidelity/hifi/pull/12550

# FIX: make the grabbable checkbox function again when dynamic disabled

This PR will also respect the grabbable default true setting. Unlike the stable implementation which had 0 or 1 as default based on the value of properties.dynamic, which made the default value check completely useless.

## proposed testrail plan: 

https://highfidelity.manuscript.com/f/cases/12921/Create-Grabbable-Test-for-hifi-PR12550

1. Open create
2. Create a cube
3. Make grabbable checked    |  cube should be grabbable (by mouse or hand controllers)
4. Make grabbable un-checked | cube should not be grabbable (by mouse or hand controllers)
5. Repeat tests 3 and 4 with dynamical disabled on and off, the results should be the same.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7728/app_12560_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7728/HighFidelity-Beta-PR12560-e8e07efbb06bc13f2edd9a591218a357ddc0339b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7728/HighFidelity-Beta-PR12560-e8e07efbb06bc13f2edd9a591218a357ddc0339b.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Stopped Testing.

**Comment by Atlante45** [comment]
@thoys this should be a full RC merge back.

**Pull request closed without merging**
