### PR TITLE
Fix web entity crash

### PR DESCRIPTION
**Pull request by danteruiz**
If client creates a web entity and the server right away tells the client to delete that entity, WebEntities OffscreenSurface will delete the ShardObject while it is processing a QEvent causing a crash. This PR fixes this issue.

ticket - 
https://highfidelity.manuscript.com/f/cases/16251/Admix-billboard-creation-crashes-client-in-AvatarIsland

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
0. Put the following white list filter under the Entity script settings on a domain where you have rez rights: highfidelity.io, highfidelity.com, content.highfidelity.com, cdn.highfidelity.com, public.highfidelity.com, hifi-content.s3.amazonaws.com, mpassets.highfidelity.com/b9f920b2-13cb-48b3-bc10-4a12b189087a-v1/

1. Run http://mpassets.highfidelity.com/1775b618-fd54-4bdb-a80e-8407d9b6908e-v1/js/admixController.js - you will need to set up a log in 

2. Attempt to add a billboard. billboard should not appear (you may see it briefly) and you should not crash.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10990/HighFidelity-Beta-PR13501-8c96597.apk

**Comment by danteruiz** [comment]
test this please

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Stopped testing, build failed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11000/HighFidelity-Beta-PR13501-8c96597.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11000/HighFidelity-Beta-PR13501-8c96597.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11000/HighFidelity-Beta-Interface-PR13501-8c96597.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11000/HighFidelity-Beta-PR13501-8c96597.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11000/HighFidelity-Beta-Interface-PR13501-8c96597.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Banners were not created while the whitelist was active (but could be placed when the whitelist was removed). No crashes occurred.

**Pull request merged**
