### PR TITLE
Entity level locking

### PR DESCRIPTION
**Pull request by sethalves**
All public methods of EntityItem and subclasses are protected by a per-EntityItem lock.  Return-by-reference methods now return-by-value.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb27d03f6b0d5bdd4bb8b1dbfacb5d14cb65576b available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f7df940d48c5628db5ccc7f4d4fb4f662305c32 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4eec17eb78645109bb0bbbe227721fbab1a29792 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9381ab5573ecbe7b51e2d99a6029eec28d049860 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 024c2a70be71819fd9e5548e75e3d6774c01540d available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: dbeef4ddb13630d3efbc14724dd9c39c0c81a095 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 809240d86575d96d25342b51325dd4fd731b4e61 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7e45c4508179c968066f835d5b02853793c8b852 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3465f5ffb927c7e96330eed2d3dbf18f5d4e91e5 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 361f66750adee79651d763a17e220d87ee85902d available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22df716d151b9bdfc1be9859a14d9eda26e7020f available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 686cd259f87f25a4fc109ddd1936af340c097b06 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48029805fce35a1cc188a4e5e158f9cab2990330 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c85441401d0969a022a5c5b8f52cc4a80e9cf49 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 20c12595e50a55d5a63089f5d58ad153255e3009 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57a50109ef26cd725b1a94f0141848254b523548 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53d39bf4e46f3f547438bf4e19d0370f18d3f200 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef239bbbd290b172ea0c63f4f3ade88b89c6be37 available at: https://gist.github.com/1900de4f45ada948afec<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5294.dmg

**Comment by ZappoMan** [comment]
After further consideration, we've determined this is not the approach we want to take.

**Pull request closed without merging**
