### PR TITLE
making entities collisionless when grabbing them with grab.js

### PR DESCRIPTION
**Pull request by danteruiz**
making entities collisionless when grabbing them with grab.js i.e desktop mode.

- Ticket https://highfidelity.fogbugz.com/f/cases/9420/Non-dynamic-and-Grabbable-entities-are-movable-by-the-mouse-as-if-they-were-dynamic

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan (desktop)
- make a dynamic and non-dynamic grabbable entity
- grab the entity with you mouse cursor
- the entity should not be able to collide with other entities.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10242/HighFidelity-Beta-PR13267-6afa5b1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10242/HighFidelity-Beta-PR13267-6afa5b1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10242/HighFidelity-Beta-Interface-PR13267-6afa5b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10242/HighFidelity-Beta-PR13267-6afa5b1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10242/HighFidelity-Beta-Interface-PR13267-6afa5b1.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Toggling dynamic property of an entity to on position is not saved when Create app is closed. Dynamic property of entity is lost as entity is set to default Non-dynamic state. Defect does not occur in Master. Defect occurs on Windows 10 and OSX devices
Video clip and logs attached

[PR13267.zip](https://github.com/highfidelity/hifi/files/2059718/PR13267.zip)

**Comment by danteruiz** [comment]
I read the ticket wrong and created the wrong PR.  I am closing this PR,

**Pull request closed without merging**
