### PR TITLE
Case 21315, Case 21326, Case 21370 - QML Marketplace fixes

### PR DESCRIPTION
**Pull request by roxanneskelly**
Case 21315 - Clicking on item picture from Inventor Items list does not
always display the Marketplace item page.
Case 21326 - See All Markets page is missing its footer and the two
Explore buttons no longer work
Case 21370 - QML Marketplace - For unavailable items (no more editions
for sale), marketplace item list 'buy' button is not disabled

### CODE REVIEW

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/21315/Clicking-an-item-picture-from-the-Inventory-Items-list-does-not-always-display-the-Marketplace-item-page

https://highfidelity.manuscript.com/f/cases/21326/See-All-Markets-page-is-missing-its-footer-and-the-two-Explore-buttons-no-longer-work

https://highfidelity.manuscript.com/f/cases/21370/QML-Marketplace-For-unavailable-items-no-more-editions-for-sale-marketplace-item-list-buy-button-is-not-disabled

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17517/HighFidelity-Beta-PR14989-267f463.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17517/HighFidelity-Beta-PR14989-267f463.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17517/HighFidelity-Beta-Interface-PR14989-267f463.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17517/HighFidelity-Beta-PR14989-267f463.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17517/HighFidelity-Beta-Interface-PR14989-267f463.exe

**Comment by antoninahifi** [comment]
testing for all 3 tickets passed

**Pull request merged**
