### PR TITLE
Wizard tweaks

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4859/HighFidelity-Beta-PR11798-9cd8f372f20e43840340de7ee2632d078d2f01d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4859/HighFidelity-Beta-PR11798-9cd8f372f20e43840340de7ee2632d078d2f01d3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4860/HighFidelity-Beta-PR11798-d2d2992783b82f30307956f41050df1bb17378e4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4860/HighFidelity-Beta-PR11798-d2d2992783b82f30307956f41050df1bb17378e4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4862/HighFidelity-Beta-PR11798-8f133fc7fa7ed1b742a0063cd40d653f09683582.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4862/HighFidelity-Beta-PR11798-8f133fc7fa7ed1b742a0063cd40d653f09683582.exe

**Comment by Atlante45** [comment]
[Test Plan](https://highfidelity.testrail.net/index.php?/suites/view/258&group_by=cases:section_id&group_order=asc)

**Comment by YuppyPlays** [comment]
Testing

[was a bit late typing this, apologies]

**Comment by YuppyPlays** [comment]
Testing complete:

All **Pass**, TestRail Results: https://highfidelity.testrail.net/index.php?/runs/view/941&group_by=cases:section_id&group_order=asc

**Pull request merged**
