### PR TITLE
fix for initial send of non-instanced trait

### PR DESCRIPTION
**Pull request by birarda**
https://highfidelity.manuscript.com/f/cases/20213/white-sphere-in-9715-dev-welcome

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15799/HighFidelity-Beta-PR14549-51fd742.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15799/HighFidelity-Beta-PR14549-51fd742.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15799/HighFidelity-Beta-Interface-PR14549-51fd742.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15799/HighFidelity-Beta-PR14549-51fd742.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15799/HighFidelity-Beta-Interface-PR14549-51fd742.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Pull request merged**
