### PR TITLE
Fix typos for entity server script log

### PR DESCRIPTION
**Pull request by Triplelexx**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6819/app_12318_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6819/HighFidelity-Beta-PR12318-a8d2be045cfbec6c7cd3b2dd07d4e703465bf627.exe

**Comment by MiladNazeri** [comment]
No QA needed - only fixing typo in a comment was changed.

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6829/app_12318_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6829/HighFidelity-Beta-PR12318-a8d2be045cfbec6c7cd3b2dd07d4e703465bf627.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6829/HighFidelity-Beta-PR12318-a8d2be045cfbec6c7cd3b2dd07d4e703465bf627.exe

**Pull request merged**
