### PR TITLE
Fix crash when adding new attachment

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Before: Avatar > Attachments > New Attachment: immediate crash

After:
- Avatar > Attachments > New Attachment: doesn't crash.
- Can successfully add an attachment.
- Can attach to different joints.
- Attachment with invalid URL doesn't crash Interface.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e56e0bf18782af197a0dc475486141fa081f262 available at: https://gist.github.com/89b4b9e537f465743988f7a98aea3306<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8401-8e56e0b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8401-8e56e0b.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

Confirmed current RC instant crashes on add attachment.

This PR no crash on create new attachment.
I tried attaching to 10 joints, randomly of available - all worked.
Checked x,y,z position and rotation settings.
Toggled soft flag.
Tried with invalid URL.

No crashes recorded.

QA Pass

In the open old can or worms department (and **nothing** to do with this PR).  If one is far from domain origin when adding an attachment it does not appear, at least to self.  My first test was at 16000,16000,16000 and I thought this PR was broken until I remembered attachments get strange at large origin offsets.

**Comment by Nex-Pro** [comment]
**IMO QA PASS**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb
**Testing OS:** win 10 pro
**HMD:** HTC Vive.
**Hand Controllers:** Vive

Tested in desktop and HMD modes.0


Avatar > Attachments > New Attachment: doesn't crash. **SUCCESS**
Can successfully add an attachment. **SUCCESS**
Can attach to different joints. **SUCCESS**
Attachment with invalid URL doesn't crash Interface. **SUCCESS**

Tested persistence of attachments over restart of interface: **SUCCESS**
Checked deletion if attachments: **SUCCESS**
Interface exited cleanly: **SUCCESS**

Thanks @ctrlaltdavid

**Pull request merged**
