### PR TITLE
force DS to use new node ID if connect is re-sent

### PR DESCRIPTION
**Pull request by birarda**
- removed re-use of node ID when sockets match in domain-server

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

With this PR, connect to the Sandbox. 
(1) Connect to the domain anonymously. Ensure that logging in re-connects you to the domain and changes your session ID (you can check the session ID from the domain-server nodes page).
(2) Connect to the domain logged in. Ensure that logging out re-connects you to the domain and changes your session ID.

**Comment by birarda** [comment]
I had specifically added the code I'm removing here to remove annoying log spam for when a user is trying to connect to a domain over and over again.

That's an edge case so I'm removing the handling here to ensure that nodes that send a connect request to a domain server always re-connect with a new session ID.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd023e038406965dd9d5a69c3143ece8475fe26a available at: https://gist.github.com/e54c2502c6605e329c0255231d57f474<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-cd023e0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-cd023e0.dmg

**Comment by AndrewMeadows** [comment]
I will test this.

**Comment by AndrewMeadows** [comment]
QA_FAIL

I was getting a duplicate avatar that would briefly rendered on sign out/in.  I cloned this branch and added some debug info to watch the calls to AvatarData::setSessionUUID() and saw the following output:


```
Login
AvatarData::setSessionUUID() from {00000000-0000-0000-0000-000000000000} to {1fb228a8-fd9a-488a-9e27-b01b964ddff6} isMyAvatar = 1

Sign Out
AvatarData::setSessionUUID() from {1fb228a8-fd9a-488a-9e27-b01b964ddff6} to {00000000-0000-0000-0000-000000000000} isMyAvatar = 1
AvatarData::setSessionUUID() from {00000000-0000-0000-0000-000000000000} to {9842f87a-b2ff-4804-8a00-5fe962698c35} isMyAvatar = 1
AvatarData::setSessionUUID() from {00000000-0000-0000-0000-000000000000} to {1fb228a8-fd9a-488a-9e27-b01b964ddff6} isMyAvatar = 0

Sign In
AvatarData::setSessionUUID() from {9842f87a-b2ff-4804-8a00-5fe962698c35} to {00000000-0000-0000-0000-000000000000} isMyAvatar = 1
AvatarData::setSessionUUID() from {00000000-0000-0000-0000-000000000000} to {86474534-4d99-472a-ae2e-6d62faffaa0e} isMyAvatar = 1
AvatarData::setSessionUUID() from {00000000-0000-0000-0000-000000000000} to {9842f87a-b2ff-4804-8a00-5fe962698c35} isMyAvatar = 0
```

**Comment by ZappoMan** [comment]
interesting... I wonder if there's a race condition between when the avatar-mixer gets the `nodeKilled` and when the avatar-mixer sends out the next frame of `BulkAvatarData` -- also... it could be that there's a packet in flight that has the old avatar data.

**Comment by ZappoMan** [comment]
@AndrewMeadows - it might be that we want ignore `BulkAvatarData` for avatars we haven't yet received an identity packet for...

**Comment by birarda** [comment]
The Interface was sending a disconnect request to the domain-server, but without a node ID. So the domain-server was not processing this disconnect request.

Normally it would receive that and send it along to the avatar mixer so the avatar mixer knows to remove the disconnected node.

I have pushed a fix for that. 

You could still see the duped avatar case if the disconnect packet is lost or if you are in the period of time before the avatar mixer receives the forwarded disconnect. The likelihood should be greatly reduced now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c00dfcc7d7e0092800ff4f1bfdae90bf3b867659 available at: https://gist.github.com/e54c2502c6605e329c0255231d57f474<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-c00dfcc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-c00dfcc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c00dfcc7d7e0092800ff4f1bfdae90bf3b867659 available at: https://gist.github.com/e54c2502c6605e329c0255231d57f474<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-c00dfcc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10281-c00dfcc.dmg

**Comment by AndrewMeadows** [comment]
**QA_PASS**

Ok this final version looks good.  The dupe avatar is no longer created and the sessionUUID is definitely being changed on sign out/in.

**Pull request merged**
