### PR TITLE
Fix backwards HUD in mirror mode

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- In desktop mode, the HUD (stats, toolbar, etc.) should render properly.
- In mirror mode (ctrl+h), they should still render properly.
- In HMD in first person, the HUD sphere should render properly.
- In HMD in mirror mode, the HUD sphere should still render properly.
- In HMD in mirror mode, while facing your avatar, your avatar should mirror your movements (if you move your right hand, the avatar moves its left hand, like a mirror image).

(in mirror mode, you can rotate the camera with the arrow keys, and pan it up and down with shift + up arrow/shift + down arrow)

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4391/HighFidelity-Beta-PR11666-046e5ca7161abe121ca921f7d410bf77dc9bb231.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4393/HighFidelity-Beta-PR11666-046e5ca7161abe121ca921f7d410bf77dc9bb231.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by marko8904** [comment]
build this please

**Comment by YuppyPlays** [comment]
Testing complete:

**[Used Debug window for HMD to determine the "sphere" of the HUD for HMD.]**

In desktop mode, the HUD (stats, toolbar, etc.) should render properly. **Check**
In mirror mode (ctrl+h), they should still render properly. **Check**
In HMD in first person, the HUD sphere should render properly. **Check**
image

In HMD in mirror mode, the HUD sphere should still render properly. **Check**
image

In HMD in mirror mode, while facing your avatar, your avatar should mirror your movements (if you move your right hand, the avatar moves its left hand, like a mirror image). **Check, but worth noting avatar does not face player, he faces to the left by around 25 degrees or so**

**Notes: Unsure if this is PR specific or just a general thing, but the mirror mode is a bit sickness-inducing in terms of movement, it seems to 'shake' in a weird way when mirror mode is active.**

**Pass** Unless any previous points raised are of concern with the PR itself.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4399/HighFidelity-Beta-PR11666-046e5ca7161abe121ca921f7d410bf77dc9bb231.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4399/HighFidelity-Beta-PR11666-046e5ca7161abe121ca921f7d410bf77dc9bb231.exe

**Comment by SamGondelman** [comment]
@YuppyPlays yeah the overall mirror experience needs to be improved, but this PR was just fixing the reversed HUD.  Thanks for testing!

**Comment by conklin94122** [comment]
https://highfidelity.fogbugz.com/f/cases/8565/Mirror-View-toolbar-is-flipped-should-not-be

**Pull request merged**
