### PR TITLE
Locate faceshift in build/ not lib/Debug / lib/Release (OSX)

### PR DESCRIPTION
**Pull request by zzmp**
Compiled successfully on OSX 10.11.1 (El Capitan) with this change.
Installed all dependencies with brew or cmake (as explained in BUILD_OSX).

I did not pass `DEBUG` or `RELEASE` flags, don't know about any, and don't know if this change covers these cases. This should be checked before merging in (I couldn't find resources about this - could someone point me to some, if they exist?).

Before this change, the last succeeding `make` message (as libfaceshift.a was in the "wrong" location):
```
[ 80%] Built target faceshift
make[2]: *** No rule to make target `ext/makefiles/faceshift/project/lib/Release/libfaceshift.a', needed by `interface/interface.app/Contents/MacOS/interface'.  Stop.
make[1]: *** [interface/CMakeFiles/interface.dir/all] Error 2
make: *** [all] Error 2
```

Compilation still has (unrelated) warnings in general.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 71a8b45351a72ba766f8cd8e388d14f7d9a7ec35 available at: https://gist.github.com/2c50b4fb7801547aa470<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6488.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6488.dmg

**Comment by zzmp** [comment]
It seems like @hifi-gustavo did not have this issue. It's probably relevant that [he is running OSX 10.10](https://gist.github.com/hifi-gustavo/2c50b4fb7801547aa470#file-os-x-L59).

Maybe the fix should include a version check to maintain compatibility?

**Comment by AndrewMeadows** [comment]
This is just a guess: maybe moving the location of the installed FaceShift libraries causes cmake to be unable to find them later.  Each library "Foo" has a FindFoo.cmake module, so maybe **.../cmake/modules/FindFaceshift.cmake** also needs to be updated for this PR.

**Comment by birarda** [comment]
Odd, a number of us are on El Capitan and don't need this fix to find faceshift and build interface.

The CMakeLists for our external faceshift project is told to install the library to `lib/Debug` and `lib/Release` so that's absolutely where we'd expect to find them.

So, what we want to figure out here is, why does the install step fail on @zzmp's machine?

**Comment by zzmp** [comment]
I haven't tried to rebuild since first reporting this, and may not get a
chance to until next week, but I'll read up on CMake and see if anything is
obviously amiss on my system.

**Comment by ZappoMan** [comment]
Closing this until @zzmp can work on it again next week.

**Pull request closed without merging**
