### PR TITLE
Fix infinite loading when authing wallet during Checkout

### PR DESCRIPTION
**Pull request by zfox23**

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan

## Notes
- I can't believe I missed this. I tried to fix this bug before, but I put the bug-fixing code in the wrong part of the relevant conditional statement. >_<

## Prerequisites
- You have a High Fidelity account on the Staging backend environment
- Your environment variables are set up to point Interface/Sandbox at the Staging backend environment
    - `SETX HIFI_METAVERSE_URL https://staging.highfidelity.com`
- You have a valid Wallet that you have **NOT** yet authenticated

## Tests
1. Open the MARKET app. Click on the "FREE" or Buy button on the bottom right of any item's Card. Authenticate your wallet when prompted
    i. Verify that you see the Checkout screen corresponding to the item whose Buy button you just clicked.
2. Attempt to purchase the item.
    ii. Verify that you see the Checkout Success screen.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8261/app_12708_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8261/HighFidelity-Beta-PR12708-069f60c1a3b04e5d7c7c4b55ba0508699f66522c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8261/HighFidelity-Beta-PR12708-069f60c1a3b04e5d7c7c4b55ba0508699f66522c.exe

**Comment by conklin94122** [comment]
build this please

**Comment by Atlante45** [comment]
Can we not merge this and just do a merge back instead?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8274/app_12708_PR.apk

**Comment by Atlante45** [comment]
I made a merge back here: https://github.com/highfidelity/hifi/pull/12713

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8274/HighFidelity-Beta-PR12708-069f60c1a3b04e5d7c7c4b55ba0508699f66522c.dmg

**Pull request closed without merging**
