### PR TITLE
Improve text3d rendering

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Improves the crispness and legibility of characters.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
The "smoothing" parameter is reduced from 256 to 32.

The attached zip file has snaps of test text taken with smoothing parameters between 0 and 256. 32 looked about the sweet point to me and seems to work pretty well in my testing.

[snaps.zip](https://github.com/highfidelity/hifi/files/170361/snaps.zip)

**Comment by hifi-gustavo** [comment]
Build console output for commit: f7c6725f6319ad85292eac1c809912d84f84ba1b available at: https://gist.github.com/70648d055c8bcce06846<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7336.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7336.dmg

**Comment by ZappoMan** [comment]
Test notes:
Smoke the builds... make sure text is still readable.

**Comment by Nex-Pro** [comment]
3d text problem blue bkgrnd
3d text problem
3d text problemblack on default bkgrnd

White text is legible but ugly. Quite bad dithering. As in the snaps. Looks a mess.
Black text renders almost invisible on a blue background and lighter than the default background.
interestingly you can see that the black looks black at an angle where the other text entity is in the background.
Black text has pretty good sharp edges unlike the white.

**Comment by ctrlaltdavid** [comment]
@Nex-Pro Yeah, text3d rendering isn't very good over all. However, is this PR an improvement on the rendering currently in the production builds?

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  Doesn't seem to me to be any improvement.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  are you guys using any form of syntax highlighting for the shader code ?

**Comment by ctrlaltdavid** [comment]
@Nex-Pro I was mainly trying to improve the legibility of small text - it renders really bloated and pretty illegible in the current releases (with smoothing parameter = 256).

Syntax highlighting as in bold etc.: no, not that I know of.

**Pull request merged**
