### PR TITLE
new icon and button layout

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6497/app_12224_PR.apk

**Comment by tapalisa** [comment]
Test plan:
The Emote app now has an icon and a name in the tablet and the HUD
There are 8 buttons in 2 columns
Pressing each emote button triggers the corresponding animation once

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6497/HighFidelity-Beta-PR12224-f6062ebfccb5a3653844fd69d0b8afdf820524cb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6497/HighFidelity-Beta-PR12224-f6062ebfccb5a3653844fd69d0b8afdf820524cb.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
The Emote app now has an icon and a name in the tablet and the HUD | 👍 
When the app is open there are 8 emote buttons in 2 columns | 👍 
Pressing each emote button triggers the corresponding animation once | 👍 

## Emotes
List of Emotes |  .
--- | ---
0o96 | Crying
an7e | Surprised
bx2a | Dancing
2x8k | Cheering
e93w | Waving
2m0o | Falling
6y9x | Pointing
4v6c | Clapping

Pass from me!

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
The Emote app now has an icon and a name in the tablet and the HUD | 👍 
When the app is open there are 8 emote buttons in 2 columns | 👍 
Pressing each emote button triggers the corresponding animation once | 👍 

## Emotes
List of Emotes |  .
--- | ---
0o96 | Crying
an7e | Surprised
bx2a | Dancing
2x8k | Cheering
e93w | Waving
2m0o | Falling
6y9x | Pointing
4v6c | Clapping

Pass from me!

@conklin94122

**Pull request merged**
