### PR TITLE
Potential fix for crash for TabletScriptingInterface::getTabletWindow

### PR DESCRIPTION
**Pull request by druiz17**
This is a potential fix for a crash when the script engine decides to garbage collect the tablet proxy.

Potential fix to fogbugz
- https://highfidelity.fogbugz.com/f/cases/4268
-https://highfidelity.fogbugz.com/f/cases/4250/CRASH-when-trying-to-access-tabletShown

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- potential crash fix for the tablet, no functional changes
- Just do a smoke screen on the tablet.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbd2a532a88e2513a1c3d8e6d2af4dfa4fc2c7b1 available at: https://gist.github.com/6ace6d3fe42ef220e6be7209787d4885<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10254-cbd2a53.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10254-cbd2a53.dmg

**Comment by Nex-Pro** [comment]
Testing this.

**Comment by Nex-Pro** [comment]
No problems found apart from an issue with selecting particles which I will compare against master.

**Comment by druiz17** [comment]
@Nex-Prro I made some changes that would potentially avoid other crashes. Can I get another smoke screen test? Thanks in advance

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50ed4a61f72092de4bed0ab3b33ecc00b9083344 available at: https://gist.github.com/6ace6d3fe42ef220e6be7209787d4885<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10254-50ed4a6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10254-50ed4a6.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by Nex-Pro** [comment]
### PASS

All seems good. Went thru most items in the tablet both in HMD and desktop. Some issues seen but they are not due to this PR. Will check on FogBugz.

**Pull request merged**
