### PR TITLE
fix handleUrl helper regex

### PR DESCRIPTION
**Pull request by howard-stearns**
see https://highfidelity.atlassian.net/browse/DEV-2753

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22623/HighFidelity-Beta-PR16511-2cc39a2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22623/HighFidelity-Beta-Interface-PR16511-2cc39a2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22623/HighFidelity-Beta-PR16511-2cc39a2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22623/HighFidelity-Quest-Beta-PR16511-2cc39a2.apk)

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22630/HighFidelity-Beta-PR16511-2cc39a2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22630/HighFidelity-Quest-Beta-PR16511-2cc39a2.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22630/HighFidelity-Beta-PR16511-2cc39a2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22630/HighFidelity-Beta-Interface-PR16511-2cc39a2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22630/HighFidelity-Beta-PR16511-2cc39a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22630/HighFidelity-Beta-Interface-PR16511-2cc39a2.exe

**Pull request merged**
