### PR TITLE
Beta Release 61.1 - Includes up to Developer Release 7593

### PR DESCRIPTION
**Pull request by conklin94122**
Beta Release 61.1 includes up to Developer Release 7593. This release also contains a protocol change; you will need in order to update High Fidelity to visit domains running this version.

- Fix for invisible or stuttering avatars
- Fixes a bug that sometimes prevents certified entities from rezzing
- Fixes errors related to Ownership Challenges
- Fixes certified rezzing errors caused by a memory corruption error

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5805/app_12050_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5805/HighFidelity-Beta-PR12050-2791217e8d62c26833bddc706941fdb65c5765f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5805/HighFidelity-Beta-PR12050-2791217e8d62c26833bddc706941fdb65c5765f2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5808/app_12050_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5808/HighFidelity-Beta-PR12050-5a839ebd936548f4f1bc36c1b7b9afc832383ce8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5808/HighFidelity-Beta-PR12050-5a839ebd936548f4f1bc36c1b7b9afc832383ce8.exe

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5811/app_12050_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5811/HighFidelity-Beta-PR12050-5a839ebd936548f4f1bc36c1b7b9afc832383ce8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5811/HighFidelity-Beta-PR12050-5a839ebd936548f4f1bc36c1b7b9afc832383ce8.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5817/app_12050_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5817/HighFidelity-Beta-PR12050-072e818c9994faf49db06eb516da46e97dbbd611.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5817/HighFidelity-Beta-PR12050-072e818c9994faf49db06eb516da46e97dbbd611.dmg

**Pull request merged**
