### PR TITLE
Change the way cellscience entities intitialize & audio plays

### PR DESCRIPTION
**Pull request by imgntn**
Changelist:
- Previously, entities in cell science tried to initialize themselves using userData in their preload methods.  Since userData was sometimes inaccessible at preload, those entities would fail to do their assigned behaviors.  Now these entities wait until they are able to access userData to initialize themselves, which should help a variety of issues. 
- Previously, over 125mb of  background audio was downloaded and loaded locally by each user because audio was played through entities.  Now audio is injected on the AC, with no user download required.
- Previously, some entities had movement scripts attached where everyone tried to move the entity in its update, causing jitter.  Now only one person at a time can move any given entity in its update.
- Halved the number of vesicles and other entities for performance reasons.
- Various cleanup and minor changes, including making the entities at the cell level 'zoomable' when you enter them.

**NOTE: This script will clear content where you run it**

To test: 

1. In an empty domain, go to running scripts and import this script from url: http://hifi-content.s3.amazonaws.com/DomainContent/CellScience/importCellScience.js
2. Stop the importCellScience.js script.
3. Observe that all the buttons work, background audio is playing at a talkable volume, and that from the 'Cells' button area when you fly into an entity, you get teleported deeper into the cell,.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 720175f862779b4adb9ef64401238ed2875ac9ae available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 720175f862779b4adb9ef64401238ed2875ac9ae available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 720175f862779b4adb9ef64401238ed2875ac9ae available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0368bfc4ee20c5b963dd0050b199706b6b07ef2e available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by imgntn** [comment]
https://app.asana.com/0/search/88555662479171/87282317319774
https://app.asana.com/0/search/88555662479171/87282317319780
https://app.asana.com/0/search/88555662479171/87701135452787
https://app.asana.com/0/search/88555662479171/87701135452789
https://app.asana.com/0/search/88555662479171/83302214820483

**Comment by hifi-gustavo** [comment]
Build console output for commit: 937ba3b79665e55c6e33d9cad65d45b52a363efb available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by imgntn** [comment]
i think ryan is going to QA test this one, since it's a pretty complicated setup with the audio routing now

**Comment by hifi-gustavo** [comment]
Build console output for commit: d920a3d7214f581e33a85fd32679ca96c4a8a79c available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22c53fc395ef708300a6094587316a0b0bfd51d6 available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a34b68bffc678c08fc327bcc2f47fd771f62025 available at: https://gist.github.com/9f92fab66f3ee93fe0d3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7041.dmg

**Pull request merged**
