### PR TITLE
Entities.getEntityProperty() performance improvements

### PR DESCRIPTION
**Pull request by ZappoMan**
* Optimizes Entities.getEntityProperty() performance by only copying the properties that apply to the type of entity (so for example, animationSettings are included for Box or Sphere) - this saves about 50% over the old implementation

* Adds a new second optional parameter to `Entities.getEntityProperty(entityID, desiredProperties)` which will narrow the getEntityProperties() to only those requested properties. `desiredProperties` can be a single property name or an array of property names - this saves 70-80% over the old implementation

**Testing**

* This test script will find all the entities near your avatar and run a loop that gets the properties for all these entities, you can use it to compare new/old performance.

```
var center = MyAvatar.position;
var radius = 1000;
var entityIDs = Entities.findEntities(center, radius);
var TEST_TIMES = 1000; 

var start = Date.now();
for (var test = 0; test < TEST_TIMES; test++) {
    //print("TEST:"+test);
    entityIDs.forEach(function(id) {
        //var properties = Entities.getEntityProperties(id, ["userData", "stage.day", "skybox.color"]);
        //var properties = Entities.getEntityProperties(id, "userData");
        var properties = Entities.getEntityProperties(id);
        print(JSON.stringify(properties));
    });
}
var end = Date.now();
var elapsed = end - start;
print("entityIDs:" + entityIDs.length);
print("TEST_TIMES:" + TEST_TIMES);
print("elapsed:" + elapsed);
```

**Notes**
* Some properties area always include, namely: ID, type, created, age, ageAsText, sittingPoints, boundingBox

**Known Issues**
* Because the underlying code uses the EntityPropertyFlags, and there is some aliasing with some properties, you will sometimes get some properties you didn't ask for.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45c34e161736f42f047d8edc2ae0d15249a0bf9a available at: https://gist.github.com/97365d52781dfdbbef51<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d0a46224276fbb7e32c34941d06d07b96a76d461 available at: https://gist.github.com/97365d52781dfdbbef51<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0811da14b88c21556b6a386db8b2ace12b6d795f available at: https://gist.github.com/97365d52781dfdbbef51<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5836.dmg

**Comment by AndrewMeadows** [comment]
I used the test script above (with **print** statement commented out) to measure a time reduction of 53% in this branch.

**Comment by ZappoMan** [comment]
@AndrewMeadows - I expect about 50% if you use the `var properties = Entities.getEntityProperties(id);` and about 80% if you use `var properties = Entities.getEntityProperties(id,"position");` or `var properties = Entities.getEntityProperties(id, ["position", "rotation"]);`

**Comment by AndrewMeadows** [comment]
Oh right, I was using the one whare the desired property was not defined.  I'll go ahead and test the other one.

**Pull request merged**
