### PR TITLE
re-instate domain API connection info refresh during failure, fix localhost connection after downgrade

### PR DESCRIPTION
**Pull request by birarda**
- refresh domain connection information from API when failing to connect
- fix failure to connect to localhost after domain connection version downgrade

### CODE REVIEW

**Comment by birarda** [comment]
Re-introducing a fix for a couple of issues, and fixing the bug that was introduced that required the revert.

To test:

- Run Interface by itself and attempt to connect to your place that is not running
- Run your domain, Interface should connect (after a couple of seconds)
  - On master, depending on the ice server your domain selects you may not re-connect if Interface is started before the server
- Run Interface and attempt to connect to a domain you are not on the whitelist for - confirm that there is not a thrashing of re-requests of connection information from the API
- Run Interface and connect to your domain. Stop your server and wait until Interface shows it has disconnected. Restart your server. You should reconnect (after a couple of seconds).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32cd54aa608b454bf17c45ce7f00e7093e0d5133 available at: https://gist.github.com/1a639e07b7d62915d86cde5106a044c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.dmg

**Comment by Nex-Pro** [comment]
### Fail
see log.
[hifi-log.txt](https://github.com/highfidelity/hifi/files/304365/hifi-log.txt)

Would not connect to localhost if localhost started after interface
or if localhost restarted whilst interface running.
would not even reconnect using go home.
had to go to sandbox and back.

see log for details of non-whitelisted connection attempts.

**Comment by Nex-Pro** [comment]
@birarda #8031 failed. But thanks for looking at this issue.

**Comment by birarda** [comment]
@Nex-Pro by testing with localhost you happened to catch a separate bug that I've now fixed as well. Thank you for that!

I've tried to clarify in the testing notes what needs to be QA'ed here. There are separate blocks for tests connecting to localhost and connecting to place name (temporary or otherwise). They are separate bugs and separate fixes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d7e810687b84dbedc1e35957478264b463bb08e available at: https://gist.github.com/1a639e07b7d62915d86cde5106a044c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f21403f539baa62da4993d498b0c7749ddd4bdb available at: https://gist.github.com/1a639e07b7d62915d86cde5106a044c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.dmg

**Comment by cozza13** [comment]
**QA Fail** (Failed one test)

**ICE switchover** (**Pass**)
**Connection Denial API Thrashing** (tries to reconnect every 1 seconds, instead of several times a second. **Pass**)
**Re-connection to previously connected ICE domain** (Fail it did not reconnect)

This error `[06/08 16:42:36] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:37] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:37] [WARNING] udt::Socket error - QAbstractSocket::NetworkError

[06/08 16:42:38] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:38] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:39] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:39] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:40] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:40] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:41] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:41] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:42] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:42] [WARNING] udt::Socket error - QAbstractSocket::NetworkError
[06/08 16:42:43] [DEBUG] Limit of silent domain checkins reached
[06/08 16:42:43] [WARNING] udt::Socket error - QAbstractSocket::NetworkError`

**Localhost downgrade fixes** - (**Pass**)
**Connect version mismatch** - (**Pass**)
**Connection to/from this PR** - (**Pass**)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c4f336e728a637778dca5e1434393360bd99f56 available at: https://gist.github.com/1a639e07b7d62915d86cde5106a044c7<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8031.dmg

**Comment by cozza13** [comment]
Tested the failed area and it works

**Pull request merged**
