### PR TITLE
BUGZ-211: Don't dereference rvalue shared ptr

### PR DESCRIPTION
**Pull request by Atlante45**
[JIRA ticket](https://highfidelity.atlassian.net/browse/BUGZ-211)

### CODE REVIEW

**Comment by Atlante45** [comment]
Fixed by #15570

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19501/HighFidelity-Beta-PR15571-a5b5af0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19501/HighFidelity-Beta-Interface-PR15571-a5b5af0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19501/HighFidelity-Beta-PR15571-a5b5af0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19501/HighFidelity-Quest-Beta-PR15571-a5b5af0.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19501/HighFidelity-Beta-PR15571-a5b5af0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19501/HighFidelity-Beta-Interface-PR15571-a5b5af0.exe

**Pull request closed without merging**
