### PR TITLE
Bug fix to prevent wrists entering the avatar's torso.

### PR DESCRIPTION
**Pull request by hyperlogic**
This was inadvertently disabled in PR #11978.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6181/app_12132_PR.apk

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/11295/Avatar-hands-can-clip-inside-the-avatar-s-body

**Comment by hyperlogic** [comment]
QA Test plan:

In general, your avatar's wrists should not be able to clip into/enter the torso of your avatar.

This is one method that can cause your hand controllers to enter your body.

1) enter HMD mode while using the Vive or Oculus HMD with hand controllers
2) stand erect
3) bring your hand controllers close to your actual chest.
4) lean/bow forward

**Comment by QAadahlin** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6181/HighFidelity-Beta-PR12132-ae997928c138416744129769f9af07a40442696e.dmg

**Comment by hyperlogic** [comment]
windows pdb errors, build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6189/app_12132_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6189/HighFidelity-Beta-PR12132-ae997928c138416744129769f9af07a40442696e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6189/HighFidelity-Beta-PR12132-ae997928c138416744129769f9af07a40442696e.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing for PR#12132. PASSED.

**Pull request merged**
