### PR TITLE
New Help questions/answers/link

### PR DESCRIPTION
**Pull request by zfox23**
**Test Plan:**
1. Open the Wallet app. Create a Wallet if you haven't already.
2. Go to the Wallet app's "HELP" tab.
3. Read through all of the answers in this section. Ensure they make sense. Also, click all links in this section and verify that they go to places you'd expect.

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by Nex-Pro** [comment]
@zfox23 Isn't this a somewhat subjective test ?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5119/HighFidelity-Beta-PR11864-d2ebfbf0642917b0e954586d0f5d6c957437bc63.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5119/HighFidelity-Beta-PR11864-d2ebfbf0642917b0e954586d0f5d6c957437bc63.exe

**Comment by Nex-Pro** [comment]
@zfox23  Does 'Appdata" directory make sense on Linux and OSX ?

**Comment by zfox23** [comment]
@Nex-Pro Yes, definitely.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Little concerned about something - maybe it's just a one time thing but I got this upon entering...

I'll carry on but just thought I'd mention this.

image

**Comment by YuppyPlays** [comment]
Testing complete:
Open the Wallet app. Create a Wallet if you haven't already. **Check**
Go to the Wallet app's "HELP" tab. **Check**
Read through all of the answers in this section. Ensure they make sense. Also, click all links in this section and verify that they go to places you'd expect.  **Check, other than a few small grammatical errors, it's just about perfect in my eyes**

**Pass**

**Comment by Nex-Pro** [comment]
@zfox23 Would it be a good idea to have OS specific info on that point ? I would guess that most windows users have not even heard of Appdata because they don't need to know. Appdata is pretty much a windows term, will OSX users know about it?

**Comment by Nex-Pro** [comment]
@YuppyPlays Did you list those errors?

**Comment by zfox23** [comment]
@YuppyPlays could you please list those errors?

**Comment by zfox23** [comment]
@Nex-Pro what messaging are you referring to?

**Comment by YuppyPlays** [comment]
@zfox23 had a quick double-check, no need- I thought a comma before "and" was redundant, though supposedly it is a well talked over matter with grammar, it is acceptable from what I just had a read on, removed this from comment. All good :)

**Comment by zfox23** [comment]
@Nex-Pro I'm going to merge this particular PR.

**Pull request merged**
