### PR TITLE
Fix avatar joint rotations / translations to be set by script

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d3b300037548f26ff8e55cf82d1622fa7f68124 available at: https://gist.github.com/13ca45f17fba03525e6f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.dmg

**Comment by howard-stearns** [comment]
How should we test this?

I made a mistake earlier in not testing walk.js as we made various changes. It is intended that walk.js (in some form) should work while Developer->Avatar->Enable Rig Animations and ->Enable Anim Graph are both off. One issue is that what used to be called setJointData is now setJointRotation. But making that change alone (in walk.js and library/walkApi.js) isn't enough to make walk.js work, either with this PR or without it.

I'm wondering how this ever worked before, or put another way, at what point it started not working. For example, the thread check that this PR changes was not actually new with any of our recent changes. If we do have to make this change, don't we also have to change the other occurrences of this pattern for all the getJointMumble getters?

**Comment by thoys** [comment]
@howard-stearns made changes to walk.js to make it work again.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6da91ee35e5a76a9c89089207e6f3016173e1c5 available at: https://gist.github.com/75c46bd2bd152cf1031f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.dmg

**Comment by howard-stearns** [comment]
I don't know how to evaluate this. 
* The MyAvatar.cpp changes look correct, and functionally, they do make these methods work where they did not work before. That's the purpose of the PR, and so on that basis I think we should merge it. (I still don't know how this ever worked before, or at what point it started not working, which makes me uneasy, but as I said, these changes do seem valid.)
* The additional changes make walk.js operate, but I'm sure it's not working well. Maybe @DaveDubUK  can have a separate look?

I'll give folks a day to respond, but then I'm inclined to merge it as is.

**Comment by thoys** [comment]
@DaveDubUK this seems to fix it, good testing!. I have also tried the setAvatarData and zero_vec3 method, but this seems to compress my avatar into a ball. Just setting the rotations seems to work fine. @howard-stearns if the code looks good to you then it's ready to merge.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c99573ea64a812c417a1dc2a7a3d3f786eed653b available at: https://gist.github.com/13ca45f17fba03525e6f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6052.dmg

**Comment by howard-stearns** [comment]
Awesome. Nice work guys.

**Pull request merged**
