### PR TITLE
Add Graphics preferences to Tablet

### PR DESCRIPTION
**Pull request by vladest**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d70943dd6c37ebc36760c1bc1caeaf8a86302b02 available at: https://gist.github.com/ba6196a2a03bbe36f9ef5eaa833369e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9865-d70943d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9865-d70943d.dmg

**Comment by ctrlaltdavid** [comment]
A TabletComboBoxPreference.qml file will not be needed once https://github.com/highfidelity/hifi/pull/9863 is merged into tablet-ui. In that PR, TabletComboBox.qml and ComboBox.qml have been merged into one file, ComboBox.qml, which works on both desktop and tablet (i.e., TabletComboBox.qml has been deleted).

**Comment by vladest** [comment]
no problems. I'll adapt the PR as soon as #9863 will be merged

**Comment by sethalves** [comment]
@vladest #9863 is merged.  do you want to change this PR before it goes in?

**Comment by vladest** [comment]
yes, sure

**Comment by vladest** [comment]
Updated

**Comment by vladest** [comment]
Test plan:
- goto Menu->Develop->Graphics...
- make sure Comboboxes working
- select different options 
- press Save settings button and check changes on the screen

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0accce5337f7ed1a172f731d4364cea84b958a9e available at: https://gist.github.com/ba6196a2a03bbe36f9ef5eaa833369e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9865-0accce5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9865-0accce5.dmg

**Pull request merged**
