### PR TITLE
Give implicit access to family tree of server scripted entities in ESS 

### PR DESCRIPTION
**Pull request by birarda**
- added optional flags "includeAncestors" and "includeDescendants" to entity JSON queries
- added sending of new optional flags by default from Entity Script Server
- added handling of "includeAncestors" and "includeDescendants" flags in Entity Server via optional Octree pre-processing step

### CODE REVIEW

**Comment by birarda** [comment]
There are a couple of choices I made in designing this that I would like to highlight for commentary:

(1) I only call `preDistributionProcessing` for the `OctreeSendThread` (or subclass) if we are about to send a new scene. I wonder if the ESS could get into a state where things in its frumtumless scene are changing so frequently that we never actually finish the scene and never get to do the postprocessing. In theory this is impossible if an individual entity is only sent once per "scene".

(2) We force a full scene send if new entities (ancestors or descendants of entities matching our filter) are added to the flagged extra set. I've added this to handle the cases where an entity is added to your family tree but the entity itself has not changed (and would therefore not be included by the logic of the entity-server). Forcing the full scene send all of the time is likely overkill because it will also cause it in cases where we wouldn't need it, like when a new entity is added to the family tree. I could potentially add a check to see if the ancestor/descendant has changed since the last query time before deciding if a full scene send is required.

(3) I don't do anything to tell the ESS why it might have a stale version of an entity that used to be in the family tree of a matching filtered entity but is no longer. In conversations with @ZappoMan we agreed this was okay because it is similar to what happens to entities that go outside the view frustum for clients using frustum queries.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf3cf8179d43944aff43542993fd268dcfd908a3 available at: https://gist.github.com/ad60439e38767e2178cfd27454cb9676<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-cf3cf81.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-cf3cf81.dmg

**Comment by birarda** [comment]
#### Test Plan

For this test you will need to use this
[models.json.gz](https://github.com/highfidelity/hifi/files/781694/models.json.gz) and the following script: https://gist.githubusercontent.com/birarda/de807a7decc902b200b187615b4a3cdc/raw/7844b73a734616d9f75364935a276b5154b9cdbd/treeChecker.js.

You will need to setup a Sandbox from master and from this PR with the replacement `models.json.gz`.

Start your test at `/-29.7861,-200.531,15.297/0,-0.000705864,0,1`. You will be looking at a set of cubes.

pasted image at 2017_02_16 02_20 pm

(1). On master, add the `treeChecker.js` script to the yellow cube. In your Entity Script Server (ESS) log, you should see a number of errors because the script will be unable to get the position of the entities in the family tree.
(2) Using this PR, add the `treeChecker.js` script to the yellow cube. In your ESS log, you should see 7 positions successfully printed in the ESS log (about once a second). Attempting to print the position for the "stale grandchild" (the lowest tan cube) will cause an error in the script because your ESS doesn't yet have any knowledge about the tan cubes. You should see that changes you make to the position of the cubes are reflected in the ESS log output.
(3) Parent the top tan cube to the yellow cube, using edit.js. This causes the entity server to send you both tan cubes since one is now the child of the entity with the server script and the other is a grandchild. Your ESS log should now be successfully printing the position of the the lower tan cube (the "stale grandchild").
(4) Remove the parent from the top tan cube. You should see that you continue to print a stale position for the tan "stale grandchild". This is expected behaviour. The entity server is no longer sending you ESS updates for either of the tan cubes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7b05378225749463d5329202eccf2f59d528e636 available at: https://gist.github.com/ad60439e38767e2178cfd27454cb9676<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-7b05378.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-7b05378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d4c9fb41c5e83fcd6c4c3f661e93fce577588386 available at: https://gist.github.com/ad60439e38767e2178cfd27454cb9676<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-d4c9fb4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-d4c9fb4.dmg

**Comment by Nex-Pro** [comment]
Will test this.

**Comment by Nex-Pro** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 78301fd9477f0363767ab9d8d40849ac9b6308c5 available at: https://gist.github.com/ad60439e38767e2178cfd27454cb9676<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-78301fd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-78301fd.dmg

**Comment by Nex-Pro** [comment]
### PASS

Log output attached. All looks good. Was testing earlier build, switched to latest.

On master, add the treeChecker.js script to the yellow cube. **DONE**
In your Entity Script Server (ESS) log, you should see a number of errors because the script will be unable to get the position of the entities in the family tree. **CHECK** see attached log snippet if needed. 

Using this PR, add the treeChecker.js script to the yellow cube. **DONE**
In your ESS log, you should see 7 positions successfully printed in the ESS log (about once a second). **SUCCESS**

Attempting to print the position for the "stale grandchild" (the lowest tan cube) will cause an error in the script because your ESS doesn't yet have any knowledge about the tan cubes. You should see that changes you make to the position of the cubes are reflected in the ESS log output.
Parent the top tan cube to the yellow cube, using edit.js. **DONE**
This causes the entity server to send you both tan cubes since one is now the child of the entity with the server script and the other is a grandchild. Your ESS log should now be successfully printing the position of the the lower tan cube (the "stale grandchild"). **CHECK**
Remove the parent from the top tan cube.**DONE** 
**You should see that you continue to print a stale position for the tan "stale grandchild". **CHECK**
This is expected behaviour. The entity server is no longer sending you ESS updates for either of the tan cubes.

Would it make sense to name the ESS log ?
[ess_log_snippet_master_with_errors.txt](https://github.com/highfidelity/hifi/files/782106/ess_log_snippet_master_with_errors.txt)


[ESS_LOG_ac-20170217.02.05.36.635-stdout.txt](https://github.com/highfidelity/hifi/files/782109/ESS_LOG_ac-20170217.02.05.36.635-stdout.txt)

**Comment by ZappoMan** [comment]
@birarda we should make sure we also get some performance testing especially on an i5 setup with these changes. @OmegaHeron can you take a pass on this PR?

**Comment by OmegaHeron** [comment]
@zappoman 1st on list for tomorrow morning (Monday).

**Comment by OmegaHeron** [comment]
CPU analysis on Interface = good.

Red trace = this PR, blue = current master (6069), green = last RC (6008)

6008vs6069vs9692

You can also see how things have improved from various optimizations since 6008.  The large CPU spikes in some traces are not a problem - those come from my forcing Interface to work harder during a scene load with intent being to create deadlocks via CPU stress.

CPU use of AC running ESS and ES remain comparable to use prior to this PR.  Obviously, on low end setups like mine with i5 one would have to exercise caution in how hard the AC ESS and other script based CPU consumption is pushed, but that's not HiFi's problem.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b996f2b7fdcab5e968e9651e41db26cc63372b6 available at: https://gist.github.com/ad60439e38767e2178cfd27454cb9676<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-3b996f2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9692-3b996f2.dmg

**Pull request merged**
