### PR TITLE
quiet compiler

### PR DESCRIPTION
**Pull request by sethalves**
- fix some compiler warnings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 224aeea04406d56ae901e14d7d1216c34ff592b6 available at: https://gist.github.com/543504f8c861f6e6ad64<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5916875345dcd51d16cfc484c5762295f40feac2 available at: https://gist.github.com/543504f8c861f6e6ad64<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.dmg

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
i hate you, gustavo

**Comment by ZappoMan** [comment]
Don't blame the Latinos, I think we can place blame squarely on the Brits for this!

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5916875345dcd51d16cfc484c5762295f40feac2 available at: https://gist.github.com/543504f8c861f6e6ad64<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6257.dmg

**Pull request merged**
