### PR TITLE
Web entity

### PR DESCRIPTION
**Pull request by jherico**
Create an entity that loads HTML content

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8d343bbf1a1adb2c4fb23c23835b22464b1d9d5 available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc825f66325e6b34ca96ba93efe5c0cac589c546 available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b6c20d93c01502ab59d7876be92e8739cd5ff92 available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Comment by ZappoMan** [comment]
crash when deleting the web page entity using edit.js

```
Thread 35 Crashed:: Script Thread:edit.js
0   libsystem_kernel.dylib        	0x00007fff91fcf282 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff87dd4b73 abort + 129
2   org.qt-project.QtCore         	0x0000000112903d29 0x1128e1000 + 142633
3   org.qt-project.QtCore         	0x00000001129051e1 QMessageLogger::fatal(char const*, ...) const + 161
4   org.qt-project.QtGui          	0x000000010eeb9770 QOpenGLContext::makeCurrent(QSurface*) + 656
5   io.highfidelity.Interface     	0x000000010e4df07d OffscreenQmlSurface::~OffscreenQmlSurface() + 29
6   io.highfidelity.Interface     	0x000000010e4df1ce OffscreenQmlSurface::~OffscreenQmlSurface() + 14
7   io.highfidelity.Interface     	0x000000010e50cc00 RenderableWebEntityItem::~RenderableWebEntityItem() + 160
8   io.highfidelity.Interface     	0x000000010e50cd9e RenderableWebEntityItem::~RenderableWebEntityItem() + 14
9   io.highfidelity.Interface     	0x000000010e3ad29a EntityTree::processRemovedEntities(DeleteEntityOperator const&) + 586
10  io.highfidelity.Interface     	0x000000010e3aced3 EntityTree::deleteEntity(EntityItemID const&, bool, bool) + 963
11  io.highfidelity.Interface     	0x000000010e3a5fd4 EntityScriptingInterface::deleteEntity(EntityItemID) + 244
12  io.highfidelity.Interface     	0x000000010e370ae1 EntityScriptingInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 2321
13  io.highfidelity.Interface     	0x000000010e37188c EntityScriptingInterface::qt_metacall(QMetaObject::Call, int, void**) + 76
14  org.qt-project.QtScript       	0x000000010f79ea36 0x10f636000 + 1477174
15  org.qt-project.QtScript       	0x000000010f79b001 0x10f636000 + 1462273
16  org.qt-project.QtScript       	0x000000010f78a71d 0x10f636000 + 1394461
17  org.qt-project.QtScript       	0x000000010f789fbf 0x10f636000 + 1392575
18  org.qt-project.QtScript       	0x000000010f6d7d4d 0x10f636000 + 662861
19  org.qt-project.QtScript       	0x000000010f6b9020 0x10f636000 + 536608
20  ???                           	0x00003a5cf243a3b3 0 + 64170875921331
21  org.qt-project.QtScript       	0x000000010f679dc3 0x10f636000 + 277955
22  org.qt-project.QtScript       	0x000000010f6f768e 0x10f636000 + 792206
23  org.qt-project.QtScript       	0x000000010f6d7e2e 0x10f636000 + 663086
24  org.qt-project.QtScript       	0x000000010f795fd4 0x10f636000 + 1441748
25  org.qt-project.QtScript       	0x000000010f796199 0x10f636000 + 1442201
26  org.qt-project.QtCore         	0x0000000112b4a393 QObject::event(QEvent*) + 755
27  org.qt-project.QtWidgets      	0x00000001105cd32b QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
28  org.qt-project.QtWidgets      	0x00000001105d0648 QApplication::notify(QObject*, QEvent*) + 8136
29  org.qt-project.QtCore         	0x0000000112b1fa5b QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
30  org.qt-project.QtCore         	0x0000000112b71d9b QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 59
31  io.highfidelity.Interface     	0x000000010e46e425 ScriptEngine::run() + 389
32  org.qt-project.QtCore         	0x0000000112b513c2 QMetaObject::activate(QObject*, int, int, void**) + 1986
33  org.qt-project.QtCore         	0x0000000112915f46 0x1128e1000 + 216902
34  libsystem_pthread.dylib       	0x00007fff91eb62fc _pthread_body + 131
35  libsystem_pthread.dylib       	0x00007fff91eb6279 _pthread_start + 176
36  libsystem_pthread.dylib       	0x00007fff91eb44b1 thread_start + 13

```

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad5f1214bf0334a1e78f3dad51804f2ae60627ab available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0097bcff8256bbb7381b74bb20f409b30aa1a35 available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b7e8a69b53f16bed41a0452316caea963389f97 available at: https://gist.github.com/1370d8dcd40dbf1675c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4850.dmg

**Pull request merged**
