### PR TITLE
Add scaling to WebWindow to fix high-dpi display rendering

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
Don't merge, just trying to get a windows build from jenkins ;)

**Comment by murillodigital** [comment]
test this please

**Comment by huffman** [comment]
test this please

**Comment by ZappoMan** [comment]
test this please

**Comment by huffman** [comment]
Closing this for now - was trying to get builds from jenkins, it was only reopened because the installers weren't generated the first time around.

**Pull request closed without merging**
