### PR TITLE
changed root to micBar which had the gated property

### PR DESCRIPTION
**Pull request by MiladNazeri**
83 version of https://highfidelity.atlassian.net/browse/BUGZ-972?filter=10078

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20685/HighFidelity-Beta-PR16010-7d3ac62.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20685/HighFidelity-Beta-Interface-PR16010-7d3ac62.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20685/HighFidelity-Beta-PR16010-7d3ac62.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20685/HighFidelity-Quest-Beta-PR16010-7d3ac62.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20689/HighFidelity-Beta-PR16010-7d3ac62.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20689/HighFidelity-Beta-Interface-PR16010-7d3ac62.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20689/HighFidelity-Beta-PR16010-7d3ac62.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20689/HighFidelity-Quest-Beta-PR16010-7d3ac62.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20689/HighFidelity-Beta-PR16010-7d3ac62.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20689/HighFidelity-Beta-Interface-PR16010-7d3ac62.exe

**Pull request merged**
