### PR TITLE
0.73.0 fix MyAvatar-vs-OtherAvatar collisions

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR fixes a bug where it appears MyAvatar doesn't collide at all with OtherAvatars.

The bug is a re-occurence of a previous bug where the avatars really are colliding in the physics simulation but the mass of the OtherAvatar is so low we cannot see its effect on MyAvatar.  The fix: when the avatar's true model info is loaded we add it to the list of things that need to be updated in the physics simulation.

The internal manuscript case is 18683:
https://highfidelity.manuscript.com/f/cases/18683/Avatar-collisions-do-not-work

**Test Plan**

**(1)** Login UserA

**(2)** Login UserB (but don't move the avatar).

**(3)** UserA try to walk into UserB
--> on **hifi/master** UserA will be able to walk right through UserB
--> on **this PR** UserA will collide with into UserB

**(4)** Scale UserA and/or UserB up or down.  Make sure the two avatars still collide with each other according to their new shapes.

**(5)** Repeat steps **(1)** through **(2)** on a fresh login, then before step **(3)** UserB should change scale to be much bigger or much smaller than default size.

**(6)** UserA try to walk into UserB:
--> on **this PR** verify avatars  collide with correct shape

**(7)** Repeate steps **(1)** through **(2)** on fresh login, then before step **(3)** UserB should change avatars to one that is very different (bigger, smaller, fatter, thinner) than previous.

**(8)** UserA try to walk into UserB:
--> on **this PR** verify avatars collide with correct shape

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13241/HighFidelity-Beta-PR14070-d3447f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13241/HighFidelity-Beta-Interface-PR14070-d3447f3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13241/HighFidelity-Beta-PR14070-d3447f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13241/HighFidelity-Beta-Interface-PR14070-d3447f3.dmg

**Comment by qaAdamSmith82** [comment]
Fail @conklin94122 

Collision eventually breaks after extended movement/multiple logins

1. Log in with 2 users
2. Have the two users collide and move about/around each other
3. Collision breaks

Or

1. Log in with two users
2. Collision breaks

This is not 100% repro, it can take a few tries
hifi-snap-by-adamisawake-on-2018-09-24_14-21-51

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13269/HighFidelity-Beta-PR14070-c8543ff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13269/HighFidelity-Beta-PR14070-c8543ff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13269/HighFidelity-Beta-Interface-PR14070-c8543ff.dmg

**Comment by ZappoMan** [comment]
sorry I removed and then re-added the dev approved on accident.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Collision works consistently

**Pull request merged**
