### PR TITLE
Web Entities support isAA property

### PR DESCRIPTION
**Pull request by SamGondelman**
Adds a new entity property, isAA, which mimics the web overlay isAA property.  Only used for web entities right now but could also be used on text entities, maybe.  Defaults to false to increase readability.

Also:
- Web overlays default to isAA = false
- Tablet doesn't set isAA to true in HMD

Test plan:
- Create a web entity.
- Open edit.js and toggle the "Is Anti-aliased" property on and off.
- When it's off, text may appear clearer, especially smaller text.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2612/HighFidelity-Beta-PR11215-6b2f28225e20f1869ad76ff0395fdf0efd25b642.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2612/HighFidelity-Beta-PR11215-6b2f28225e20f1869ad76ff0395fdf0efd25b642.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2615/HighFidelity-Beta-PR11215-81c4f0c60047ea1b242e1fcea42e278f6f7df665.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2619/HighFidelity-Beta-PR11215-81c4f0c60047ea1b242e1fcea42e278f6f7df665.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2619/HighFidelity-Beta-PR11215-81c4f0c60047ea1b242e1fcea42e278f6f7df665.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Create a web entity. | Pass
Open edit.js and toggle the "Is Anti-aliased" property on and off. | Pass
When it's off, text may appear clearer, especially smaller text. | Pass

Looking all good here - text is definitely much clearer to see when it's smaller.

**Comment by OmegaHeron** [comment]
As an FYI, myself and one other user is seeing a near 100% crash on launch since this PR.  See bugsplats for DEV release 7036 and this PR.

**Comment by SamGondelman** [comment]
@OmegaHeron I'm not quite sure what you mean.  This PR hasn't been merged yet, so it can't be causing crashes in 7036.

**Comment by OmegaHeron** [comment]
Yikes - my apologies - this got added to wrong PR comment -- fixing.

**Comment by OmegaHeron** [comment]
#11157 Which I had previously tested seems to be root of all evil in regards to crash.  It's another like those seen in distant past where one day it all works fine -- then another it's 100% crash, like a non initialized var or something random.  I got my "AA" PRs crossed.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2748/HighFidelity-Beta-PR11215-eb9436ba96de981444e13d444b162609e9d2697d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2748/HighFidelity-Beta-PR11215-eb9436ba96de981444e13d444b162609e9d2697d.exe

**Pull request closed without merging**
