### PR TITLE
Leap Motion can near grab entities

### PR DESCRIPTION
**Pull request by PhilipRosedale**
When using the script leapHands,js to animate the fingers with the Leap, added using the total curl of the fingers to drive the trigger value in the standard controller.  This means you can near grab an object.  

Still broken/to-do: 

1.  hand orientation is not yet reported, so the grab lasers point wrong way. 
2.  release velocity is not yet being set at controller, so objects will often freeze in mid-air when released.

### CODE REVIEW

**Comment by ZappoMan** [comment]
:+1:

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cc1c930c55e66c43734276ceb61cacfbd0c2608 available at: https://gist.github.com/353ff62c563641b226f1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7204.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7204.dmg

**Comment by ZappoMan** [comment]
Testing notes:

1) Using a Leap
2) run this script - https://rawgit.com/PhilipRosedale/hifi/betterLeap/examples/controllers/leap/leapHands.js
3) grab something

**Comment by cozza13** [comment]
I will test this

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4845de68dd47656fb006fce2a38a5a6aa6b08813 available at: https://gist.github.com/353ff62c563641b226f1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7204.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7204.dmg

**Pull request merged**
