### PR TITLE
Pull test images from GitHub

### PR DESCRIPTION
**Pull request by NissimHadar**
Test images are now stored on GitHub.
The format is currently PNG, which is a problem due to large file sizes (hence slow downloads).
This is being researched.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7707/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7707/HighFidelity-Beta-PR12554-5a79f272f3e9ef29ed87977c586b2d7c34edc852.exe

**Comment by samcake** [comment]
@NissimHadar it s failing on macos
there:
6:35:46 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/tools/auto-tester/src/Test.cpp:357:27: error: use of undeclared identifier 'pow'
16:35:46     const int maxImages = pow(10, NUM_DIGITS);

I m guessing you need to include the correct header or use a float version specifically?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7789/app_12554_PR.apk

**Comment by NissimHadar** [comment]
You are right.  Visual Studio somehow builds correctly.  I'll add the header and check.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7798/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7798/HighFidelity-Beta-PR12554-4b3d63eea4952c46749593fdb49d1e79699172d2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7798/HighFidelity-Beta-PR12554-4b3d63eea4952c46749593fdb49d1e79699172d2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7824/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7824/HighFidelity-Beta-PR12554-2f040d00326ffa1c2d7eb5f421a79f16a7b1ee81.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7829/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7829/HighFidelity-Beta-PR12554-9bd7f31ff32b7a68bcc333e71217604194c5034f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7829/HighFidelity-Beta-PR12554-9bd7f31ff32b7a68bcc333e71217604194c5034f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7837/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7837/HighFidelity-Beta-PR12554-b47b512ab9a767039b629e26daa75b2d2528b025.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7837/HighFidelity-Beta-PR12554-b47b512ab9a767039b629e26daa75b2d2528b025.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7861/HighFidelity-Beta-PR12554-7052ea37691fbe1cd0e77095af6e5d3981a656a9.dmg

**Comment by samcake** [comment]
Just 2 warnings remainings in windows or macos

**Comment by NissimHadar** [comment]
please build me

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7917/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7917/HighFidelity-Beta-PR12554-aad41a56b228a2ea3a8d6fc69c8ee8c9ee0bc0be.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7918/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7918/HighFidelity-Beta-PR12554-77901e5089b38ae91b810d23d0b4c80f1c8c89dc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7957/app_12554_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7958/HighFidelity-Beta-PR12554-cb24fe6166bcb4be8627caba3ae5a8dfb4146b98.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7958/HighFidelity-Beta-PR12554-cb24fe6166bcb4be8627caba3ae5a8dfb4146b98.exe

**Comment by samcake** [comment]
THis PR oonly change the behavior of autotester.exe (and doesn;t touch any other code) so i m going to merge it

**Pull request merged**
