### PR TITLE
use tablet models from s3 until relative model urls work

### PR DESCRIPTION
**Pull request by sethalves**
- use tablet models from s3 until relative model urls work

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- get two avatars together
- make sure they see each others' tablets

**Comment by hifi-gustavo** [comment]
Build console output for commit: f635cd8a07cbe894be225bf60cea90876a7ca8c7 available at: https://gist.github.com/b8704316beca0ed34f44ebdc61b5657a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9610-f635cd8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9610-f635cd8.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by nbq** [comment]
Testing with @claudioshg

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

**PASS**

Tested with @nbq. 
nbq's tablet was visible to me and vice versa.

**Pull request merged**
