### PR TITLE
Fixes for JSBaker.cpp

### PR DESCRIPTION
**Pull request by simon-walton**
I was compiling interface on FreeBSD, which uses clang, and it failed on some character comparison code. Two of the failures look like character quoting mistakes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by huffman** [comment]
ok to test

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6951/app_12342_PR.apk

**Comment by birarda** [comment]
@simon-walton would you mind rebasing to remove the three commits other than 67a75eb?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6952/app_12342_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6952/HighFidelity-Beta-PR12342-e66bf5c72dd03d2d823bdfaa2453c5eaed62b58e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6952/HighFidelity-Beta-PR12342-e66bf5c72dd03d2d823bdfaa2453c5eaed62b58e.dmg

**Comment by simon-walton** [comment]
Pull request #12369.SimonOn February 6, 2018 at 11:42 AM Stephen Birarda <notifications@github.com> wrote:@simon-walton would you mind rebasing to remove the three commits other than 67a75eb?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request closed without merging**
