### PR TITLE
Beta Release 66.1 - branched at Developer Release 8108

### PR DESCRIPTION
**Pull request by conklin94122**
Bug Fixes

- Fix for an issue that was causing avatars to disappear
- Various crash fixes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8984/app_12954_PR_a529c7cfc5f7a1e38637a49c140fdd05f98e337a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8984/HighFidelity-Beta-PR12954-a529c7cfc5f7a1e38637a49c140fdd05f98e337a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8984/HighFidelity-Beta-Interface-PR12954-a529c7cfc5f7a1e38637a49c140fdd05f98e337a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8984/HighFidelity-Beta-PR12954-a529c7cfc5f7a1e38637a49c140fdd05f98e337a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8984/HighFidelity-Beta-Interface-PR12954-a529c7cfc5f7a1e38637a49c140fdd05f98e337a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9099/app_12954_PR_e44a845dffc522ce9be2e75c011811ac570f4767.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9099/HighFidelity-Beta-PR12954-e44a845dffc522ce9be2e75c011811ac570f4767.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9099/HighFidelity-Beta-Interface-PR12954-e44a845dffc522ce9be2e75c011811ac570f4767.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9099/HighFidelity-Beta-PR12954-e44a845dffc522ce9be2e75c011811ac570f4767.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9099/HighFidelity-Beta-Interface-PR12954-e44a845dffc522ce9be2e75c011811ac570f4767.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9117/app_12954_PR_497c3fac4d1515fc9c209b3f20a95799e77a2171.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9117/HighFidelity-Beta-PR12954-497c3fac4d1515fc9c209b3f20a95799e77a2171.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9117/HighFidelity-Beta-Interface-PR12954-497c3fac4d1515fc9c209b3f20a95799e77a2171.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9175/app_12954_PR_43aed664944b4d8a562677ad8af40a7980f5cafc.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9176/app_12954_PR_a69ded05d80d86729d1ff70711b1d245e97b2910.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9177/app_12954_PR_a69ded05d80d86729d1ff70711b1d245e97b2910.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9177/HighFidelity-Beta-PR12954-a69ded05d80d86729d1ff70711b1d245e97b2910.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9177/HighFidelity-Beta-Interface-PR12954-a69ded05d80d86729d1ff70711b1d245e97b2910.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9177/HighFidelity-Beta-PR12954-a69ded05d80d86729d1ff70711b1d245e97b2910.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9177/HighFidelity-Beta-Interface-PR12954-a69ded05d80d86729d1ff70711b1d245e97b2910.exe

**Pull request merged**
