### PR TITLE
Fix overlimit shader char strings

### PR DESCRIPTION
**Pull request by jherico**
Our scribe output shaders are starting exceed 65k characters, which is the upper limit for a character literal on MSVC.  This PR modifies the scribe executable to instead declare the shader variables as `static std::string` values, created by concatenating a series of individual smaller std::string values.  This ensures that no string literal larger than the allowed size is created.  

## Testing

Launch application and verify that it correctly renders.  Examine the logging output for any instances of `GLShader::compileShader` warnings that report failures.  

Combining PR 12161 from @Zvork 
This PR changes the way shader files are referenced inside the code. The scribe tool (combined with a modified cmake macro AutoScribeShader) now outputs for each shader a C++ source file (and not a header file as before). This cuts source dependencies between shader code and C++ code as shader sources are referenced through an "extern const char*" for each shader source, yielding quicker build times, especially when shader code is modified. This will enable quicker iterations when working on shaders.

Update: in latest version, shaders are now built by Scribe as a .h and .cpp file containing a static class for each shader.

Test Case
To test this PR, users should previously erase all *.h files inside all shaders directories in the build subtree to be sure there is no pollution (even though these shouldn't be referenced anymore). Building the solution should create all the shader "cpp" files and be successfull (not compilation or link errors) for all projects.

On running "interface", no shader compilation error should be launched (see developer log).

There should no visual difference between this PR and master when using "interface".

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6923/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6927/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6927/HighFidelity-Beta-PR12340-f611990b10538a0fd778be485ec9e30792efa4e2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6927/HighFidelity-Beta-PR12340-f611990b10538a0fd778be485ec9e30792efa4e2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6944/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6944/HighFidelity-Beta-PR12340-f291715f87127b1f6fcd844aca91df367218dacf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6944/HighFidelity-Beta-PR12340-f291715f87127b1f6fcd844aca91df367218dacf.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6948/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6948/HighFidelity-Beta-PR12340-f291715f87127b1f6fcd844aca91df367218dacf.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6968/app_12340_PR.apk

**Comment by samcake** [comment]
@jherico Can you talk with @conklin94122 John to explain the qa process here since it s an internal tools that only affects the build.
Thanks

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6968/HighFidelity-Beta-PR12340-f291715f87127b1f6fcd844aca91df367218dacf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6968/HighFidelity-Beta-PR12340-f291715f87127b1f6fcd844aca91df367218dacf.dmg

**Comment by jherico** [comment]
blocked on merging of #12349

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6975/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6975/HighFidelity-Beta-PR12340-0efb27015117c1f2c4f34ade0cc82ff42963bbc1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6987/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6987/HighFidelity-Beta-PR12340-6092f1503e12f220289dbe86ae8c63173236c12c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6987/HighFidelity-Beta-PR12340-6092f1503e12f220289dbe86ae8c63173236c12c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7004/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7005/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7006/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7006/HighFidelity-Beta-PR12340-ae092f6c0b53eba89f4e122a77e9b4b348172c03.dmg

**Comment by jherico** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7033/app_12340_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7033/HighFidelity-Beta-PR12340-ae092f6c0b53eba89f4e122a77e9b4b348172c03.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7033/HighFidelity-Beta-PR12340-ae092f6c0b53eba89f4e122a77e9b4b348172c03.dmg

**Comment by samcake** [comment]
##### TEST PLAN:

Have a developer review the Mac, Windows, and Android bulds, confirm there are no errors or failures.
Have a tester install each build and confirm the interface starts

**Comment by AndrewMeadows** [comment]
I built and tested on linux: everything worked fine.

**Comment by samcake** [comment]
built and tested on Mac and Windows all working, no error, nor perf differences

**Pull request merged**
