### PR TITLE
add setting to DS for asset path, handle absolute paths

### PR DESCRIPTION
**Pull request by birarda**
- added a setting to domain-server for a custom asset-server assets path

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c2d69f865f05b519d61fdb7cf0ed04260aa8a85 available at: https://gist.github.com/f490186f942cb1e40c38<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7092.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7092.dmg

**Comment by birarda** [comment]
test this please

**Comment by birarda** [comment]
Test Notes:

Use both a custom relative and custom absolute path for the asset server path option in your domain-server. You should see that uploaded assets are stored at the new path.

No migration of assets from the previous path is done automatically.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 27d338e81c2c689c958cc554820023324fd71070 available at: https://gist.github.com/f490186f942cb1e40c38<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7092.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7092.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Functions properly setting custom path to models.json.gz and assets folder.

Since some have mentioned wanting to use NAS - tested using SMB path on Windows (as in smb:\\192.168.0.7\assets) which works.  Tried setting models.json.gz to SMB path and that fails (smb:\\192.168.0.7\models\models.json.gz).

Using an SMB path for models fails.
Path:  smb:\\192.168.0.7\models\models.json.gz

results in this from log;
[02/12 12:33:59] [DEBUG] [9112] [entity-server] loading Octrees from file: "C:/Users/Joe/AppData/Roaming/High Fidelity - PR7092/assignment-client/entities/smb:\\\\192.168.0.7\\models\\models.json.gz" ...
[02/12 12:33:59] [CRITICAL] [9112] [entity-server] Cannot open gzipped json file for reading: "C:/Users/Joe/AppData/Roaming/High Fidelity - PR7092/assignment-client/entities/smb:\\\\192.168.0.7\\models\\models.json.gz"

Mapping SMB share to drive (Z) works Z:\models\models.json.gz
showing in log;
[02/12 12:35:14] [DEBUG] [9424] [entity-server] loading Octrees from file: "Z:/models/models.json.gz" ...
[02/12 12:35:14] [DEBUG] [9424] [entity-server] Loading Octree File took 16.95 milliseconds

Note, again, that ATP asset directory honors SMB style path or traditional drive:\dir\

Linux testing next.

**Comment by OmegaHeron** [comment]
Tested on Linux specifying custom ATP and model paths - works as expected.

For both Windows and Linux (other than over the top issue with SMB pathing on Windows) this works proper.  I can spec a custom asset and model path - models display proper and new models add to scene and persist.

I would like to mention it would be _nice_ to have ATP and Entity server settings closer together in web display, but that's just me being me.  :)  Thanks for adding the path setting abilities - it's most welcome.

**Pull request merged**
