### PR TITLE
MS14295: Fix lingering Gifts UI Bugs

### PR DESCRIPTION
**Pull request by zfox23**
[MS14295](https://highfidelity.fogbugz.com/f/cases/14295/UI-QA-in-Gifts-project-4-Bugs-reported)

I suppose this is a bug, but it's more of an improvement 😉.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9242/app_13020_PR_e3b14bf4786a5671d47cefc8109418b987439dcf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9242/HighFidelity-Beta-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9242/HighFidelity-Beta-Interface-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9245/app_13020_PR_e3b14bf4786a5671d47cefc8109418b987439dcf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9245/HighFidelity-Beta-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9245/HighFidelity-Beta-Interface-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9245/HighFidelity-Beta-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9245/HighFidelity-Beta-Interface-PR13020-e3b14bf4786a5671d47cefc8109418b987439dcf.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pausing testing

**Pull request merged**
