### PR TITLE
Update Avatar and MyAvatar destructors to be virtual

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
This only requires a smoke test.

**Comment by ZappoMan** [comment]
I assume this is fixing a bug? A memory leak?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 98b6551ab810295e79202eb14d4850b8befdd2c4 available at: https://gist.github.com/385476a2504fcde39c34e01b138db2c0<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7754.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7754.dmg

**Comment by huffman** [comment]
There wasn't a reported bug for this, and I'm not sure if there is a specific case where it was causing a problem. That said, I didn't realize virtual is implicit in this case, so this is unnecessary. Closing.

**Comment by ZappoMan** [comment]
virtual must be defined on the lowest base classes destructor for the
destructors to be virtual.

**Pull request closed without merging**
