### PR TITLE
Lock the script engine in EntityEditPacketSender

### PR DESCRIPTION
**Pull request by druiz17**
Lock the script engine in EntityEditPacketSender

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- shake hands with another person at least 10 times, each time should be a different way.
- make sure that you do not crash.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2181/HighFidelity-Beta-PR11097-c22e08f3e8ac3e4a550f0d7f7e4316bd090109dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2181/HighFidelity-Beta-PR11097-c22e08f3e8ac3e4a550f0d7f7e4316bd090109dc.exe

**Comment by Nex-Pro** [comment]
### Pass

We tried every combination of desktop/HMD handshake and early handshake termination without any crashes.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2207/HighFidelity-Beta-PR11097-c22e08f3e8ac3e4a550f0d7f7e4316bd090109dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2207/HighFidelity-Beta-PR11097-c22e08f3e8ac3e4a550f0d7f7e4316bd090109dc.exe

**Pull request merged**
