### PR TITLE
Rename render::PendingChanges to render::Transaction

### PR DESCRIPTION
**Pull request by samcake**
Simple renaming PR
As we learn to use our engine, some class names need to change sometimes to reflect better what they really are. 
This is what happens to PendingChanges
it is not necessarly pending, it s One package of several changes, and simply going into the database vocabulary, this is what it is, a Transaction to the scene database.

THat's it

## Test Plan 
Nothing should have changed
I would ask the dev review to be thorough and eventually catch any typo...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1a9005ed8bc439fa93f037896175d1e345dcc6d7 available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-1a9005e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-1a9005e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5629cf425ec5bb0b464ad8b3fed9908a1aecdad8 available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-5629cf4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-5629cf4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 026e7bc249d04fe12c5918f5ab5ec398564fb3f7 available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-026e7bc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-026e7bc.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8267db6ce5220422cc7d2e47568593eeb6c8005a available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-8267db6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-8267db6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19d080c4cc8b6557fa4b15acbb3733fbf1f8b236 available at: https://gist.github.com/9532ed28e3c78e0ab731abb65b059880<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19d080c4cc8b6557fa4b15acbb3733fbf1f8b236 available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 19d080c4cc8b6557fa4b15acbb3733fbf1f8b236 available at: https://gist.github.com/f6d68c1061ca94e4e0d4545dcc20c8b8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10135-19d080c.dmg

**Comment by AndrewMeadows** [comment]
I tested this and it looks good.

**Pull request merged**
