### PR TITLE
[RC71] In CCD IK chains, remove the LeftHand and RightHand constraint completely

### PR DESCRIPTION
**Pull request by hyperlogic**
When used in combination with the elbow pole vector, this was causing the hand to never properly reach its rotation target. It was also having side effects causing the elbow to never straighten properly to reach its position target.

There is possibly a bug in how this tip constraint is enforced and I've verified that there are no ill effects in removing it.

(cherry picked from commit 3fa3cd8cfdb9be2ec3f4d1c160e000a35c9cceb8)
Identical change as #13786

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/17124/HMD-Arm-Spasms-and-visual-Obstruction

**Comment by hyperlogic** [comment]
QA Test plan:
* Download [Arms Recording 1.gz](https://github.com/highfidelity/hifi/files/2272047/Arms.Recording.1.gz)
* Open GoTo and press the Home Button, this should put you into a serverless domain.
* Turn on Developer Menus
* Select the following menu item: 'Developer > Avatar > Show IK Targets'
* Enter mirror mode by pressing 2 on the keyboard
* Use the mouse wheel to pan the camera back so you can see the full body of the avatar.
* Switch to the default woody mannequin avatar.
* In the running scripts dialog load the scripts/developer/inputRecording.js APP
* Press the IRecord app button in your toolbar.
* Press the Load recording button
* Navigate to the ArmsRecording file that you downloaded in an earlier step.
* Press the Play Recording button

Expected result:
    you should see the hands more closely follow the IK targets then occurs in master.
    [FIXED_IK](https://www.youtube.com/watch?v=HnMbKsfMVYY)

Current result (master):
   The hands do not follow the IK targets closely
[FIXED_IK](https://www.youtube.com/watch?v=Blm9uapOelU)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11956/HighFidelity-Beta-PR13787-06b4a53.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11956/HighFidelity-Beta-PR13787-06b4a53.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11956/HighFidelity-Beta-Interface-PR13787-06b4a53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11956/HighFidelity-Beta-PR13787-06b4a53.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11956/HighFidelity-Beta-Interface-PR13787-06b4a53.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11961/HighFidelity-Beta-PR13787-421e9c7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11961/HighFidelity-Beta-PR13787-421e9c7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11961/HighFidelity-Beta-Interface-PR13787-421e9c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11961/HighFidelity-Beta-PR13787-421e9c7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11961/HighFidelity-Beta-Interface-PR13787-421e9c7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Hands follow IK Targets well
ikrecord

**Pull request merged**
