### PR TITLE
security settings post-oculus-store wording

### PR DESCRIPTION
**Pull request by howard-stearns**
Fix wording in Settings->Security to match changes for oculus store.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://highfidelity.manuscript.com/f/cases/19912/inconsistency-of-wallet-security-picture-under-setting-security

Test plan: tested by developer. (Trivial.)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15201/HighFidelity-Beta-PR14414-8e1785b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15201/HighFidelity-Beta-PR14414-8e1785b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15201/HighFidelity-Beta-Interface-PR14414-8e1785b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15201/HighFidelity-Beta-PR14414-8e1785b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15201/HighFidelity-Beta-Interface-PR14414-8e1785b.exe

**Pull request merged**
