### PR TITLE
Sit variants and fidgets

### PR DESCRIPTION
**Pull request by dooglifeSF**
Polish pass on sit random sit idles, additional sit idles and 8 sit fidgets to help break up the sit idles.

https://highfidelity.atlassian.net/browse/DEV-624

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21623/HighFidelity-Beta-PR16275-86e67af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21623/HighFidelity-Quest-Beta-PR16275-86e67af.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21623/HighFidelity-Beta-PR16275-86e67af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21623/HighFidelity-Beta-Interface-PR16275-86e67af.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21623/HighFidelity-Beta-PR16275-86e67af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21623/HighFidelity-Beta-Interface-PR16275-86e67af.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21644/HighFidelity-Beta-PR16275-ebd0b06.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21644/HighFidelity-Quest-Beta-PR16275-ebd0b06.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21644/HighFidelity-Beta-PR16275-ebd0b06.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21644/HighFidelity-Beta-Interface-PR16275-ebd0b06.dmg

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21649/HighFidelity-Beta-PR16275-ebd0b06.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21649/HighFidelity-Beta-Interface-PR16275-ebd0b06.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21649/HighFidelity-Beta-PR16275-ebd0b06.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21649/HighFidelity-Beta-Interface-PR16275-ebd0b06.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21649/HighFidelity-Beta-PR16275-ebd0b06.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21649/HighFidelity-Quest-Beta-PR16275-ebd0b06.apk)

**Comment by dooglifeSF** [comment]
TEST PLAN:
- As with any major animation stategraph json changes, it's worth going through all inputs to make sure they do the right thing in stand/sit, 1p/3p, and a look at HMD.
- This specific set of changes regards the sit idles and sit fidgets, so it's going to be a similar test plan to the stand version:  run this while on a sit cube in front of a mirror and periodically talk, as during a meeting.  Look for any issues as the various sit idles (5 of them) cycle through randomly and the various non-looping fidgets play randomly (there are 8 fidgets).  This will take a bit of time.  I am 98% confident on these though as I run these tests during iteration on the animations so I don't expect too many surprises, but it's probably worth some time to verify.
- This PR merged my chunk of json changes with Luis's point emote PR, so it's worth checking that stand/sit point still work as expected.
- Any subjective feedback is always welcome too.  I'm trying to get a bit of life into the sit without being conspicuously or distractingly busy, and I'm trying to avoid any weird poses that might result from, say, talks+fidgets etc.  Also trying to avoid any really bad deformation issues (twisted up neck, etc.)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21735/HighFidelity-Beta-PR16275-37afabe.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21735/HighFidelity-Quest-Beta-PR16275-37afabe.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21735/HighFidelity-Beta-PR16275-37afabe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21735/HighFidelity-Beta-Interface-PR16275-37afabe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21735/HighFidelity-Beta-PR16275-37afabe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21735/HighFidelity-Beta-Interface-PR16275-37afabe.exe

**Pull request merged**
