### PR TITLE
Additional fixes for crashing on exit

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by Atlante45** [comment]
Nice, will merge as soon as it has built.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88b1a20869923703694c70fc6a70e37ff299cf73 available at: https://gist.github.com/1ce8d531415f71f9cea6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6334.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6334.dmg

**Comment by imgntn** [comment]
@jherico the other crashes on exit PR is not merged yet -- should it be w/ this one or are they unrelated

**Comment by Atlante45** [comment]
@imgntn No it's a different problem.
The other PR is for a crash that's fixed now but it introduces a better data structure so it's more of a refactor PR now. @jherico will correct me if I'm wrong.

**Comment by jherico** [comment]
@Atlante45 is correct, this was one approach to fixing the crashes, but the changes it implements are valuable refactorings in their own right.

**Comment by jherico** [comment]
@Atlante45 is correct @imgntn ... I'm renaming the other PR for clarity.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f80135ef2b5284d04a2c570a93d55e2965c57ba2 available at: https://gist.github.com/1ce8d531415f71f9cea6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6334.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6334.dmg

**Pull request closed without merging**
