### PR TITLE
Fix potential assert exception in FBXMesh_Reader.cpp

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes a possible assert exception when loading a mesh with blendshape with normals but without tangents. This assert was introduced in PR #12033 and was due to a typo error.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6249/app_12159_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6249/HighFidelity-Beta-PR12159-c2427523ce5843939956bd0c0b6db5a06d683949.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6249/HighFidelity-Beta-PR12159-c2427523ce5843939956bd0c0b6db5a06d683949.dmg

**Comment by sethalves** [comment]
do you have an fbx that used to trigger the assert?

**Comment by Zvork** [comment]
I just asked @vladest for the model that triggered the assert or if he could test the PR. He tried the suggested fix on his machine yesterday and he confirmed that it fixed his issue, by the way.

**Comment by themelissabrown** [comment]
How are we QA'ing this PR?

**Comment by Zvork** [comment]
Mmmh... I haven't got any news from @vladest concerning the model.

**Comment by vladest** [comment]
@Zvork I cant say about model because for some weird reason I dont have debug/info logs on my Linux PC. Only warnings

**Comment by Zvork** [comment]
Hi @vladest . Did that happen on a particular domain?

**Comment by vladest** [comment]
@Zvork nope. at least on localhost (with default landscape) and dev-welcome

**Comment by Zvork** [comment]
@vladest I suppose then dev-welcome is a good place to start for testing. You don't remember, by any chance, if there was a particular position in dev-welcome where the assert was frequent? I'd really be curious to identify the mesh that was responsible...

**Comment by vladest** [comment]
@Zvork is it possible to identify the mesh by using debugger?

**Comment by Zvork** [comment]
@vladest Well... yes under certain conditions. The function FBXReader::buildModelMesh where the assert exception is launched has an url parameter that should hold the url of the model that is problematic. The slight problem is that url is of type QString which is unreadable in the debugger. Unless you use some sort of tool or extension that enables "human readable" debug info on Qt types. I'm downloading "Qt Visual Studio Tools" right now to see if that helps.

**Comment by Zvork** [comment]
@vladest I confirm. If you install "Qt Visual Studio Tools", you can inspect QString values in the debugger. I am using Visual Studio 2017 and it works.

**Comment by Zvork** [comment]
@themelissabrown So I suppose a QA for this PR would be, once we've identified what this mannequin.fbx model corresponds to (is that the default Avatar mesh?), go to dev-welcome and approach this mesh, have it in visibility and verify that, first of all, no assert is triggered, and that the mesh responds correctly to lighting.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
