### PR TITLE
Case 21549: Fix crash in vive and interleaved stereo plugins - HERO

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/21549/v0-79-HERO-Vive-HMD-cannot-launch-Crash

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17856/HighFidelity-Beta-PR15093-c5f6064.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17856/HighFidelity-Quest-Beta-PR15093-c5f6064.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17856/HighFidelity-Beta-PR15093-c5f6064.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17856/HighFidelity-Beta-Interface-PR15093-c5f6064.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17856/HighFidelity-Beta-PR15093-c5f6064.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17856/HighFidelity-Beta-Interface-PR15093-c5f6064.exe

**Comment by samcake** [comment]
NOt required for the hero branch, (fixing a problem introduced in 80 branch)

**Pull request closed without merging**
