### PR TITLE
faster-avatar-entities for 0.78 (case 20020)

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/20020/Investigate-scaling-problems-with-large-crowds-wearing-Avatar-Entities

This is a port of #145558 for 0.78, in case we want it.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16367/HighFidelity-Beta-PR14686-15ca49f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16367/HighFidelity-Beta-PR14686-15ca49f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16367/HighFidelity-Beta-Interface-PR14686-15ca49f.dmg

**Comment by AndrewMeadows** [comment]
**Test Plan**:

**Correctness**

**(1)** Verify you can create an unattached AvatarEntity then logout/login and find the unattached AvatarEntity restored on load.
**(2)** Verify you can edit an unattached AvatarEntity (i.e. using **create.js**) and logout/login to find the changes restored on load.
**(3)** Make an AvatarEntity with finite lifetime --> verify it disappears when its time runs out.  Logout/login and verify it is NOT re-loaded from settings.

**(4)** Repeat steps **(1)** and **(2)** with an AvatarEntity that is attached to MyAvatar.

**(5)** Login UserA who will watch UserB do the following:
**(5a)** UserA: login with zero AvatarEntities, create one that is NOT attached to UserA --> UserB should see the AvatarEntity show up.
**(5b)** UserA: logout --> UserB should see the non-attached AvatarEntity disappear.
**(5c)** UserA: login with unattached AvatarEntity in settings --> UserB should see the AvatarEntity show up with UserA.
**(5d)** UserA: edit unattached AvatarEntity --> UserB should see the changes.
**(5e)** UserA: delete unattached AvatarEntity --> UserB should see the entity vanish.
**(5f)** UserA: logout/login with zero AvatarEntities --> both UserA and UserB should see UserA show up in the domain with zero AvatarEntities.
**(5g)** Repeat steps **(5a)** through **(5f)** with a single AvatarEntity **attached** to UserA.
**(5h)** UserA: with attached AvatarEntity teleport to another domain --> AvatarEntity should be recreated on arrival.
**(5i)** UserA: teleport back to domain with UserB --> UserB should see UserA arrive with attached AvatarEntity.
**(5j)** UserA create 2 or more AvatarEntities and verify they are seen, survive logout/login cycle, and teleports.

Here is an example script which creates an AvatarEntity.  Modify as necessary:
```
// rezHat.js -- create a hat (maybe attached) and then stop script
Entities.addEntity({
    type: "Model",
    modelURL: "http://hifi-content.s3.amazonaws.com/alan/dev/Cowboy-hat.fbx?2",
    localPosition: { x:0, y:0.2, z:0 },
    name: "hat",
    dynamic: false,
    collisionless: true,
    //parentID: MyAvatar.sessionUUID, parentJointIndex: MyAvatar.getJointIndex("Head"), // uncomment to parent to MyAvatar
    //lifetime: 20, // uncomment to set finite lifetime
    dimensions: { x: 0.3239, y: 0.15, z: 0.3779 }
}, true);
Script.stop();
```

Note: there is a known theoretical bug where hierarchies of parented AvatarEntities will fail to load from settings.  (See Manuscript Case 20270).  Don't fail this PR for that problem.

**Performance**

**(7)** Make an army of animating bots in a domain.
**(8)** Login one or more real Avatars with constantly changing AvatarEntities (see script below for recipe on how to this).
**(9)** **Examine the performance** of the animating bots update rates (near and far) when the constantly changing AvatarEntities are in view.  The performance in this PR should not be worse than in hifi/master.

Note: what does it mean to **examine the performance**?  There are a ways:
**(a)** Take a profile trace and examine the time spent in **OtherAvatars** context.  Compare with hifi/master.
**(b)** Use the "debugAvatarMixer.js" script to examine the stats floating over the heads of avatars in the crowd.  Compare with hifi/master.
**(c)** Watch the rates at which various avatars in the crowd update their animation state (their rates will depend on where they are in the field of view).  The update rates should "fail gracefully" but faster is better.

Here is an example script to create a constantly changing AvatarEntity:
```
// thrashAvatarEntity.js -- create a hat and constantly change its name
var entityId = Entities.addEntity({
    type: "Model",
    modelURL: "http://hifi-content.s3.amazonaws.com/alan/dev/Cowboy-hat.fbx?2",
    localPosition: { x:0, y:0.2, z:0 },
    name: "hat",
    dynamic: false,
    collisionless: true,
    parentID: MyAvatar.sessionUUID, parentJointIndex: MyAvatar.getJointIndex("Head"),
    lifetime: 600,
    dimensions: { x: 0.3239, y: 0.15, z: 0.3779 }
}, true);   
var thrashCount = 0;
function thrash(dt) {
    var p = { name: "count" + thrashCount };
    ++thrashCount;
    Entities.editEntity(entityId, p);
}
Script.update.connect(thrash);
        
function teardown() {
    if (entityId !== null) {
        Entities.deleteEntity(entityId);
    }
}
Script.scriptEnding.connect(teardown);
```

**Recordings**

**(10)** Make a recording with AvatarEntities --> play it back.  (I dunno how to actually do this, but it appears that recording and playback are affected by this work).

**(11)** It should be possible to play an older recording from before this PR.

**Make sure the EntityTree bounding box is updated for OtherAvatar attached AvatarEntities**
**(12)** Two users in the same domain can see each other: UserA and UserB.  They both have edit permissions in the domain so that **create** script works.
**(13)** UserA create an AvatarEntity attached to themselves.  UserB should see it and be able to select it with **create** and examine properties.
**(14)** UserA walk a few meters to the side --> UserB should still be able to select UserA's worn AvatarEntity and examine its properties.  If the ray-cast fails and the entity can't be selected then there is a problem with updating the bounding box and position in the EntityTree.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16367/HighFidelity-Beta-PR14686-15ca49f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16367/HighFidelity-Beta-Interface-PR14686-15ca49f.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing (When Deployed to Engine-Dev)

**Comment by qaAdamSmith82** [comment]
QA Approved.  All logged bugs fixed and Avatar Entity tracking looks great

Master:
master

PR:
pr

**Pull request merged**
