### PR TITLE
Batch compile more shaders

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Move anti-aliasing, velocity buffer, linear depth down-sample shader to deferred compile scheme.
Follow on from PR12892.
https://github.com/highfidelity/hifi/pull/12892

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8970/app_12950_PR_999e5beba13b2d4bfb2d0c8e414ee971ad2f304f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8970/HighFidelity-Beta-PR12950-999e5beba13b2d4bfb2d0c8e414ee971ad2f304f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8970/HighFidelity-Beta-Interface-PR12950-999e5beba13b2d4bfb2d0c8e414ee971ad2f304f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8970/HighFidelity-Beta-PR12950-999e5beba13b2d4bfb2d0c8e414ee971ad2f304f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8970/HighFidelity-Beta-Interface-PR12950-999e5beba13b2d4bfb2d0c8e414ee971ad2f304f.exe

**Comment by SimonWalton-HiFi** [comment]
In my low-end-rig branch, which has these changes, I am getting a crash in the batch code for setting a uniform 2f, so I think there may be a problem with this PR.

**Comment by SimonWalton-HiFi** [comment]
I had taken out two makePrograms which I thought weren't necessary at that point. Looks like they are.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9015/app_12950_PR_4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9015/HighFidelity-Beta-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9015/HighFidelity-Beta-Interface-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9060/app_12950_PR_4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9060/HighFidelity-Beta-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9060/HighFidelity-Beta-Interface-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9060/HighFidelity-Beta-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9060/HighFidelity-Beta-Interface-PR12950-4973605bf7aafe09ee8b2e9f77bd451cea5d3f1f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Boot times are much better and the calls listed in the previous PR are less than 0.5s

**Pull request merged**
