### PR TITLE
Correct typo in string value.

### PR DESCRIPTION
**Pull request by Nex-Pro**
While poking around for a way to customise the mouse hover effect for grabbables  I found this typo:

"dispactherHoveringList"

Searched all files for other occurrences of this string and for the correct spelling:

"dispatcherHoveringList"

 None were found.
I believe this will have no impact. 
Should not need a QA pass. Please verify.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15256/HighFidelity-Beta-PR14427-51f3a28.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15256/HighFidelity-Beta-PR14427-51f3a28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15256/HighFidelity-Beta-Interface-PR14427-51f3a28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15256/HighFidelity-Beta-PR14427-51f3a28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15256/HighFidelity-Beta-Interface-PR14427-51f3a28.exe

**Comment by sethalves** [comment]
I agree that this change is untestable.

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15488/HighFidelity-Beta-PR14427-51f3a28.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15488/HighFidelity-Beta-PR14427-51f3a28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15488/HighFidelity-Beta-Interface-PR14427-51f3a28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15488/HighFidelity-Beta-PR14427-51f3a28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15488/HighFidelity-Beta-Interface-PR14427-51f3a28.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by sethalves** [comment]
I've pulled this change into https://github.com/highfidelity/hifi/pull/14472

**Pull request closed without merging**
