### PR TITLE
FB17023 - Make visible avatar url in the avatar app

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/17023/Make-visible-avatar-url-in-the-avatar-app

**Test plan**

1. Open avatar app
2. Open 'Select Avatar URL', ensure it shows url of currently selected avatar and this url is selected (like on the screen below)

image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11522/HighFidelity-Beta-PR13678-c13f27e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11522/HighFidelity-Beta-PR13678-c13f27e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11522/HighFidelity-Beta-Interface-PR13678-c13f27e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11522/HighFidelity-Beta-PR13678-c13f27e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11522/HighFidelity-Beta-Interface-PR13678-c13f27e.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS
@conklin94122 

Opened Avatar app and investigated the link. Links appear for the Default, Starter avatars, and Custom avatars. Also tested avatars with Certificate ID's.

(took a bit longer than needed as one of the avatars had a certificate ID change, that caused a false-alarm)

**Pull request merged**
