### PR TITLE
turn hud reset behavior on by default

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
with either existing Interface.ini in any state, or with none:
"Settings->Avatar->Clear overlays when moving" should control whether moving (with drive keys or in room-scale hmd) fades out the overlays until a moment after you stop moving, and the default should be checked.

 (Overlays being Avatar inputs, stats, overlay buttons other than the hud button or its tray, and QML windows such as Running Scripts dialog or a Web browser (ctrl-b).)

**Comment by howard-stearns** [comment]
https://trello.com/c/Fu3GN33X

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81300ec1270f1d11eda3d5a530be5d59a4ad3041 available at: https://gist.github.com/9ed86098e03b1adbfe28757b88333d24<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8099.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8099.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Fu3GN33X&#x2F;2-turn-hud-reset-behavior-on-by-default"> Turn HUD reset behavior on by default</a>

**Comment by thoys** [comment]
## Test Results

The `Clear overlays when moving` setting is on by default, even in existing config. The behavior of the setting is good, it hides the UI which isn't forcefully shown. 
Also the setting saves after restarting Interface. Which is expected.

QA Pass :+1:

**Pull request merged**
