### PR TITLE
Use system pointer2

### PR DESCRIPTION
**Pull request by howard-stearns**
Show a special system laser for the part of a hand controller laser that is inside the HUD.

Don't use a Reticle/cursor (because now we have the laser showing up on HUD windows).
Make handControllerGrab independent of whether we're using laser or Reticle.

Don't simulate a click on in-world elements (only HUD elements), and don't show the ball that was used to show where those clicks would act.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0faaeac6619b1b9613623d290c9a35dfb1e5d4c available at: https://gist.github.com/c859356e854c2745d1b018ecf1207a60<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8064.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8064.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0faaeac6619b1b9613623d290c9a35dfb1e5d4c available at: https://gist.github.com/c859356e854c2745d1b018ecf1207a60<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8064.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8064.dmg

**Comment by howard-stearns** [comment]
I'm going to go ahead and include this in vive-ui, so that the changes are available to @hyperlogic , and then we'll do the testing as part of a pro-forma merge-to-master pr.

**Pull request merged**
