### PR TITLE
Respect changed audio settings when switch displays (RC76)

### PR DESCRIPTION
**Pull request by danteruiz**
Description in this PR https://github.com/highfidelity/hifi/pull/14536

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14536

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15680/HighFidelity-Beta-PR14537-4796756.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15680/HighFidelity-Beta-PR14537-4796756.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15680/HighFidelity-Beta-Interface-PR14537-4796756.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15680/HighFidelity-Beta-PR14537-4796756.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15680/HighFidelity-Beta-Interface-PR14537-4796756.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
