### PR TITLE
Fix import from URL adding multiple copies of imported entities

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
*Test Plan*

- Use Edit > Export Entities to export one or more entities.
- Put the JSON file on a Web server.
- Use Edit > Import Entities from URL to import the JSON.
- Use Edit > Import Entities from URL again to import the JSON again.
- There should be two copies of the entities imported.

(Previously, without the fix, there would have been three copies of the entities imported - one copy imported the first time plus two copies of the entities imported the second time.)

**Comment by Nex-Pro** [comment]
Awaiting win build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4707/HighFidelity-Beta-PR11756-b272b2e6c8655862a54d63be9dc7948318d3bc56.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4707/HighFidelity-Beta-PR11756-b272b2e6c8655862a54d63be9dc7948318d3bc56.dmg

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
### PASS

All good now. Issue with ents being re-imported has now gone. Thanks for doing this so promptly @ctrlaltdavid

**Pull request merged**
