### PR TITLE
use updated 'Last Legends: Male' from Mukul

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/17062/The-favorites-should-not-use-the-fedora

**Test plan**

Ensure no one of bookmarked avatars wears old version of 'Fedora', ensure 'Last Legends: Male' wears new one.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11617/HighFidelity-Beta-PR13706-d38f0b0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11617/HighFidelity-Beta-PR13706-d38f0b0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11617/HighFidelity-Beta-Interface-PR13706-d38f0b0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11617/HighFidelity-Beta-PR13706-d38f0b0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11617/HighFidelity-Beta-Interface-PR13706-d38f0b0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Correct Fedora appears.

**Pull request merged**
