### PR TITLE
Fix comment in NetworkingConstants referencing shared.js location

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4608/HighFidelity-Beta-PR11727-edc7b91a425353b47f38a98ad94ad8ced981229d.exe

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4631/HighFidelity-Beta-PR11727-edc7b91a425353b47f38a98ad94ad8ced981229d.dmg

**Comment by kencooke** [comment]
Jenkins, test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4636/HighFidelity-Beta-PR11727-edc7b91a425353b47f38a98ad94ad8ced981229d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4636/HighFidelity-Beta-PR11727-edc7b91a425353b47f38a98ad94ad8ced981229d.exe

**Pull request merged**
