### PR TITLE
7718 Turn monitor display preview on by default

### PR DESCRIPTION
**Pull request by ElderOrb**
This PR fixes possible threading issue which could result in 'display preview' menu item not appearing / display preview disabled. 

Also it allows displaying preview even if 'v-sync' is enabled for 'dev' builds. 

**Test plan**

0. Take production build. 
1. Ensure 'v-sync' is disabled in OS
2. Launch interface 
3. Reset all the settings to default
4. Switch to VR
5. Preview should be enabled

Also, do a basic smoke test in High Fidelity, making sure everything is rendering at a normal frame rate and there are no additional crashes.

Note: for 'dev' builds preview should be enabled independently on enabled/disabled 'v-sync'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3454/HighFidelity-Beta-PR11405-bfb7e03ac38a60ae3dfe6177fb11fd7da553af69.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Take production build. **Check**
Ensure 'v-sync' is disabled in OS **Check, done within Nvidia Control Panel to turn vsync off by default**
Launch interface **Check**
Reset all the settings to default **Do not need to do this as fresh build**
Switch to VR **Do not need to do this as the interface always autostarts in VR as it's connected**
Preview should be enabled **Check, previous now shows straight away rather than disabling it**
Also, do a basic smoke test in High Fidelity, making sure everything is rendering at a normal frame rate and there are no additional crashes. **Check, no issues experienced going through UI and the stats screen seems no different to usual or unusual given the vsync being turned off**

**Pass** Looks good to me.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3464/HighFidelity-Beta-PR11405-9a6768b13fe904a40e662734e88c430f89f11b80.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3464/HighFidelity-Beta-PR11405-9a6768b13fe904a40e662734e88c430f89f11b80.exe

**Comment by ElderOrb** [comment]
Pushed updated version with fix for Mac build

**Comment by YuppyPlays** [comment]
@ElderOrb does this require further QA?

**Comment by ElderOrb** [comment]
Makes sense to check Mac because it had separate codepath

**Comment by YuppyPlays** [comment]
@ElderOrb Ah I see, I do not own a Mac so I will not be able to assist on this one.

**Comment by anshuman64** [comment]
The developers are concerned that this would cause too big of a performance hit on 4K monitor systems. The consensus is to close this PR for now and revisit it when we improve performance. 

@ElderOrb thanks for your effort on this.

**Pull request closed without merging**
