### PR TITLE
Add script that tests setting your listening position and orientation

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Run the script, /scripts/developer/utilities/tools/testEars.js. Overlays representing head will appear in front of you with a red left and a green right ear.
- Run Menithal's "Clap" app from the Marketplace.
- Clap as you walk around the head. You should hear the claps as if your physical head was positioned and oriented per the overlay head.
- When you stop the testEars.js script, your listening position should revert to what it was before running the script (e.g., your avatar head).

**Comment by Nex-Pro** [comment]
Will test when Win build shows up. As this is QA ready

**Comment by ctrlaltdavid** [comment]
QA Ready

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3954/HighFidelity-Beta-PR11543-596ce8e9c12c8a75db2a1d7092cf3f9c38ab3969.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3954/HighFidelity-Beta-PR11543-596ce8e9c12c8a75db2a1d7092cf3f9c38ab3969.exe

**Comment by Nex-Pro** [comment]
T E S T I N G   win 10

**Comment by Nex-Pro** [comment]
This is worthy of a round of applause.
### PASS

Audio correctly heard from dummy head position.

Audio heard from avatar head position when script is stopped.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid ^

**Pull request merged**
