### PR TITLE
DO NOT MERGE - OVR 0.7 support

### PR DESCRIPTION
**Pull request by jherico**
This will update us to using the Oculus 0.7 API.  However, in doing so we will end up dropping support for any user that has not updated their Oculus runtime to 0.7 as well.  Some people may be holding back on updating the runtime if they are using other Oculus apps that haven't been updated past 0.5 (which is no longer supported in the 0.7 runtime)

On the other hand, for users that want to update to windows 10, the 0.7 runtime is the ONLY thing that works on that platform.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0bd29fb892b40e2098664f519a8388727c0f4a3 available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by ctrlaltdavid** [comment]
Note that the eye tracker SDK doesn't support Oculus SDK 0.7 yet.

**Comment by thoys** [comment]
This works well on my Windows 10 :+1:

**Comment by thoys** [comment]
@jherico  Is there a way you could make the render plugin render a preview of the direct mode in the viewer window, would be great!

**Comment by jherico** [comment]
@thoys the crash on switching back to 2D displays is a known bug.  Right now to switch out of Oculus mode you actually have to edit the INI file.  

As for the preview on the main window, that should be possible, I just need to restore the code that ensures that v-sync is disabled on the window.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8d7d2cedde16f02eceb2a8021f5e832a6618694 available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6bb8766cb8afbf3f25c7e370f789d8f67800cd4d available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 145d533f3540323c5bed0644e8c258a7f79a416d available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee0c94ec82c0447e91f9f3a66aadf72b0416d1b5 available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f4f998ec084d941392f9961b70aa7677349f637 available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fbaa78984ee91cef27dd5e82b9ce4de47fdffcf0 available at: https://gist.github.com/1d5beb03b8cb4362f0d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5673.dmg

**Comment by ZappoMan** [comment]
Closing this PR until we have a version of the eye tracker SDK that works with 0.7 and/or @jherico has a solution for that.

**Pull request closed without merging**
