### PR TITLE
Fix web entities accessing the webcam

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR fixes a security problem when using web entities. 

https://highfidelity.fogbugz.com/f/cases/10420/High-Fidelity-wants-to-use-webcam#

...

## TEST PLAN
- Download and install a 30 days trial of Bitdefender TOTAL SECURITY 2018 https://www.bitdefender.com/Downloads/
- Open Bitdefender and go to privacy (top-left eye icon), and View Features. Make sure that Webcam Protection is ON.
- Install the latest dev build (7550 at this time), go to your sandbox and create a web entity.
- When the page is loaded Bitdefender should alert you that interface.exe is trying to gain access to the webcam. If not try this step again.
- Install this PR, go to sandbox and create a web entity. You should not receive any notification from Bitdefender this time.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5604/HighFidelity-Beta-PR11973-2d21f4d364ef9fb767935b37d2a938862eab4f02.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5604/HighFidelity-Beta-PR11973-2d21f4d364ef9fb767935b37d2a938862eab4f02.dmg

**Comment by Nex-Pro** [comment]
Testing Win 10

**Comment by Nex-Pro** [comment]
### PASS

No bit defender webcam warning triggered with this build.

See image below.
***Result with 7550***
defender

Now I have to totally remove bit defender :(

**Comment by Nex-Pro** [comment]
@luiscuenca ^

**Pull request merged**
