### PR TITLE
Fix potential race condition on static memory

### PR DESCRIPTION
**Pull request by Atlante45**
Test plan:
- Clear your cache and go you several different domains with ATP assets.
- Make sure everything loads fine.
- Try uploading a couple assets to an ATP server to make sure this still works too.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 573d5898ccc8a010ee6a1728d105ad520d261f46 available at: https://gist.github.com/0e97ed62552c62da16bbb365bb36ea93<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8714-573d589.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8714-573d589.dmg

**Comment by ZappoMan** [comment]
Can you explain your fix here?

**Comment by Atlante45** [comment]
It appears, we are getting a "Pure Virtual Call" on this line:
```cpp
ack2Packet->reset(); // ack2Packet appears to be null.
```

Since `ack2Packet` is a static variable local that's only local to that function and is never destroyed manually, it leave roughly 2 possibilities.
1) `new` is failing due to lack of RAM available or other reasons (Very unlikely).
2) Pointer is getting corrupted from multiple threads accessing it (Slightly less unlikely).

The interface is supposed to only have 1 udp socket that sequentially update it's connections.
So 2 connections should never touch that static memory at the same time.
After walking up the call tree, this appears to be true, but there might be a weird state we get in when we switch domain or reset/rebind the socket where 2 sockets live at the same time.

This would cause several connections to touch the same memory at the same time, so I put those static packets in the `Connection` object so that that doesn't happen.

**Comment by sethalves** [comment]
any chance this is the cause of https://highfidelity.fogbugz.com/f/cases/1779/pure-virtual-function-call-in-latest-beta ?

**Comment by Atlante45** [comment]
Seems unlikely. Did you manage to get the symbols for those couple Qt calls?

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU

All standard tests pass.  Specifically tested uploading content to ATP, all good.

Repeated cache clears in ATP heavy scene (standard home), my own content and dev-playa, dev-demo.  All good.  Completely removed cache (as in deleted from disk manually).  All good.

All content loaded as expected

QA Pass.

**Pull request merged**
