### PR TITLE
Make the flashlight brighter

### PR DESCRIPTION
**Pull request by imgntn**
This PR adds a falloff radius to the lights created by the flashlight so that they're brighter after recent changes.

To test:

1. Make a flashlight and near grab it https://rawgit.com/imgntn/hifi/flashlightbrightfix/examples/toybox/flashlight/createFlashlight.js
2. Observe that you can see the light on nearby surfaces

### CODE REVIEW

**Comment by imgntn** [comment]
https://app.asana.com/0/46580934041217/98001007643847

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9cd0762040fa7c9b87fa5e28bf24e7fe02bda305 available at: https://gist.github.com/c290bf05ecf5828b617a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7264.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7264.dmg

**Comment by RyanDowne** [comment]
The new value looks great. I assume you will change that in the master reset script?

**Comment by imgntn** [comment]
@RyanDowne fortunately we only need to change it here, since it is the entity script that actually creates the light for the flashlight.  sconces are fixed in another PR :)

**Pull request merged**
