### PR TITLE
Fix wizard wording

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Run the Sandbox
- Open the server settings, it should take you to the setup wizard
- Go to Step 2
- The last line of the help text used to be:
    `People can also use your domain's IP address (shown below) to visit your High Fidelity domain.`
    now it should be:
    `Your domain may also be reachable by IP address.`

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9455/app_13084_PR_e1c5eb9bda063367ab0af270d14505ab925af9ab.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9455/HighFidelity-Beta-PR13084-e1c5eb9bda063367ab0af270d14505ab925af9ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9455/HighFidelity-Beta-Interface-PR13084-e1c5eb9bda063367ab0af270d14505ab925af9ab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9455/HighFidelity-Beta-PR13084-e1c5eb9bda063367ab0af270d14505ab925af9ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9455/HighFidelity-Beta-Interface-PR13084-e1c5eb9bda063367ab0af270d14505ab925af9ab.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Settings page says "Your domain may also be reachable by IP address. "

**Pull request merged**
