### PR TITLE
Reverb memory leak

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 562b289c0541f98e877381d7f45000244cca3216 available at: https://gist.github.com/cdf011e082fa2f2bb7c9<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4261.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4261.dmg

**Comment by ZappoMan** [comment]
this looks like a great bug fix, But I don't think it fixes the issue Chris and I were seeing... I will test the repro with these test builds. The issue we were seeing was a constant leak of about .1MB of heap memory per second whenever the local client is "creating" audio... and another .1MB of heap/second when some other avatar is producing audio in particular places.

**Comment by birarda** [comment]
@Atlante45 I think you also want to free if it exists and we're calling init again?

**Comment by ZappoMan** [comment]
smoke test on windows and mac passed

**Pull request merged**
