### PR TITLE
trying new tablet spawn position.

### PR DESCRIPTION
**Pull request by druiz17**
trying new tablet spawn position.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- being in tablet mode and HMD mode
- bring up the tablet and it should not spawn so close to your hand. It should be near the tip of your stylus and a little above it.

**Comment by CainFoool** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1732/HighFidelity-Beta-PR10984-f5abb4a090f2b413ca36a1e2599096d18bb19e85.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1732/HighFidelity-Beta-PR10984-f5abb4a090f2b413ca36a1e2599096d18bb19e85.exe

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
being in tablet mode and HMD mode | Pass
bring up the tablet and it should not spawn so close to your hand. It should be near the tip of your stylus and a little above it. | Pass

I like the position of the tablet now, it spawns at the tip of the stylus as expected. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
