### PR TITLE
RC-59 patch - Disable mirror camera in HMD mode

### PR DESCRIPTION
**Pull request by Atlante45**
See original PR for test plan: #11747

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4891/HighFidelity-Beta-PR11807-7af1a5ca6999f74283f22f4700ddf5cd17ca7512.dmg

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4896/HighFidelity-Beta-PR11807-7af1a5ca6999f74283f22f4700ddf5cd17ca7512.dmg

**Comment by Nex-Pro** [comment]
Testing Win10 and Vive

**Comment by Nex-Pro** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4908/HighFidelity-Beta-PR11807-7af1a5ca6999f74283f22f4700ddf5cd17ca7512.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4908/HighFidelity-Beta-PR11807-7af1a5ca6999f74283f22f4700ddf5cd17ca7512.exe

**Comment by Nex-Pro** [comment]
Each time I tried this the avatar was acting in the above manner.

**Comment by luiscuenca** [comment]
@Nex-Pro I think I wasn't clear with the last step: **You should be allow to change to mirror mode while in HMD**. I meant that after using the script you should be allow to change to mirror mode while in HMD
I didn't experience crazy avatar in my testing. This has to be a problem with changing to mirror mode using the script. I'm revising the way the script change to mirror mode to see if it's skipping any step

**Comment by luiscuenca** [comment]
Ok, the code that change to mirror mode in Application not only change the camera mode but reset the avatar. I think using this script to change modes could solve the problem:
`(function() { 
         Camera.setModeString("mirror"); 
         MyAvatar.resetSensorsAndBody();
}());`

**Comment by luiscuenca** [comment]
Updated Test Plan:
Make sure the menu option view/mirror doesn't appear while in HMD mode.
Using the shortcut CTRL+H should change to mirror camera only in Desktop mode.
Change to mirror mode  while in HMD using this script:
(function() { Camera.setModeString("mirror"); MyAvatar.resetSensorsAndBody(); }());

**Comment by Nex-Pro** [comment]
Testing With Win10 and Vive

**Comment by Nex-Pro** [comment]
@Atlante45 This works most times. I did get one try where the avatar did the crazy animation thing.
I noticed that, when mirror mode is active that tilting the avatar head forward and back and rotating the avatar using the hand controllers results in ok frame updates, no judder. However as mentioned previously there is a lot of judder if the user rotates their head side to side or tilts their head side to side.

In addition, whiIe in HMD mirror mode,  am able to zoom back using the mouse-wheel and drive around using the controllers or arrow keys.

**Comment by Nex-Pro** [comment]
@luiscuenca ^

**Comment by Nex-Pro** [comment]
Cannot go to mirror mode in HMD by using ctrl+h

I guess that's a PASS.

**Comment by conklin94122** [comment]
https://highfidelity.fogbugz.com/f/cases/8495

**Pull request merged**
