### PR TITLE
Fix horizontal and vertical props in entity properties being swapped

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.manuscript.com/f/cases/19719/Vertical-and-horizontal-values-are-incorrect-in-particle-entity-of-create-app

# Test Plan

Confirm that steps 38-41 in https://highfidelity.testrail.net/index.php?/cases/view/17781 work as expected.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14668/HighFidelity-Beta-PR14335-299da83.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14668/HighFidelity-Beta-PR14335-299da83.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14668/HighFidelity-Beta-Interface-PR14335-299da83.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14668/HighFidelity-Beta-PR14335-299da83.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14668/HighFidelity-Beta-Interface-PR14335-299da83.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Particles are created with the correct Horizontal and Vertical default values.

**Pull request merged**
