### PR TITLE
Hifi 3 d connexion cmake fix

### PR DESCRIPTION
**Pull request by MarcelEdward**
The space navigator stopped working

The framework is 3DconnexionClient.framework for osx, not sure why connexion named it that way. It is a library in /Library/Frameworks, the library name is in stone.

for apple, this works in cmake/modules/Find3DConnexionClient.cmake

find_library(3DConnexionClient 3DconnexionClient)

And for windows it has to find the I3dMouseParams.h file in interface/external/3dconnexionclient/includes.
So for windows the line in Find3DConnexionClient.cmake has to be:

hifi_library_search_hints("3dconnexionclient")

### CODE REVIEW

**Comment by MarcelEdward** [comment]
From worklist https://worklist.net/20662

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ab63ba613302ccb73a6e14b2993418f9819fe92 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by MarcelEdward** [comment]
The osx build seems to go oke, but there are compile errors on the windows build

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ab63ba613302ccb73a6e14b2993418f9819fe92 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by MarcelEdward** [comment]
Ricardus has confirmed it works on windows.

**Comment by SamGondelman** [comment]
I had been messing around with the find paths because it seems to behave differently on different systems or something else strange.  For example, there's a Mac build error on this because on the build server it's looking in a completely different folder for some reason.  I don't have access to a Mac or a connexion mouse anymore but someone will need to test it on there.

**Comment by MarcelEdward** [comment]
I downloaded the dmg and it is working :)

cmake will find the framework, if it is installed with the installer.

**Comment by SamGondelman** [comment]
Hmm....try uninstalling the driver from your Mac (and make sure the framework in Libraries/Frameworks is actually gone, the uninstaller didn't always seem to remove it completely for me).  If you try running the dmg after uninstalling, I think I was seeing it crash, because it expects to find the framework but it couldn't find it on the build server (even though the driver is installed there).  I think it works if you have it installed in the default place on your computer because it'll find it there.

Again, I was seeing lots of weird behavior like that, which is why I was messing with the paths, but I have limited testing resources now so maybe the problem is gone.  That build error is mighty suspicious though.

**Comment by MarcelEdward** [comment]
It is strange that build server looks for "/Library/lib/3DconnexionClient.framework/Versions/A/3DconnexionClient" there is no /Library/lib

When building it happely takes the framework from the place where it is installed.

The 3Dconnexion installer does something more than just installing the framework, I have not got a clue what. I guess that is the reason they want a weak_framework link so It does not crash when not properly installed.

**Comment by SamGondelman** [comment]
But the weak link shouldn't be necessary because everything is ifdefed.

If you look at the console output on Mac, you can see "-- Found 3DConnexion at /Library/Frameworks/3DconnexionClient.framework."  That means it found the driver in the right place, so HAVE_3DCONNEXION will be true.  However, the "ERROR: no file at "/Library/lib/3DconnexionClient.framework/Versions/A/3DconnexionClient"" means that at some other point it started looking in the wrong place and could no longer find the driver.  I have no idea why that's happening, but it's a big issue.  If you don't have the driver installed locally, it won't be able to find the driver, even though it had found it on the build server at one point, so it'll crash, even though you shouldn't need to have the driver installed locally.

...At least, I think that's what's happening.  Not sure how to go about fixing it, since I can't figure out what's actually causing it.

**Comment by MarcelEdward** [comment]
The weak_link and extern come from the 3dconnexion documentation and forums ... but that does not seem to be oke

The #ifndef HAVE_3DCONNEXIONCLIENT part should be executed when someone does not HAVE the space navigator ... but apparently that only works when compiling ?

Maybe the solution is to somehow create a stub #include "3DconnexionClient/ConnexionClientAPI.h" header which is loaded when the one from the framework is not there. I do not know how to check if an #include exists.

Well send a mail to the 3dconnexion developers, maybe they know how to make it work as it should.

**Comment by MarcelEdward** [comment]
I hope this fixes the issues with the crashing if no 3d mouse is installed on osx

The 3Dconnexion dev replied the weak_library is required to prevent crashes when 3dconnexion is not installed.

Copied the two header files to the interface/external/3dconnexion/include dir so that they hopefully get copied in so interface will not crash cause they cannot find them.

Rewrote the cmake file to force to look into the include dir and the logic of adding and finding the framework a bit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 96f20957c38d9bc3dbae6521fa32fb92dd6aa6e8 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a53d244d333672664f560abd065e5448f6d057d6 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b70605381e4f8f97f018aa69582a88c6cb7c609 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64a8f7ebb4045ee5328a602fe9fc1326aee7f2a0 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3ecbd15f84e68e83bbbdc144d801f90b67c7f7f available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a71b31af03f813f6b7bf2af9f3b2de21f425833 available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1ddf5fc322574d73a700678b116f27a663be52a available at: https://gist.github.com/4fb206a697b04059f998<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5638.dmg

**Pull request merged**
