### PR TITLE
Fix memory accumulating while Interface is minimized

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Reproduce the memory problem on a non-PR build.
- Recent dev build.
- Windows, desktop mode.
- Domain with a significant amount of content and one or more avatars other than youself, but avatars not coming and going (so that their changing presence doesn't affect overall memory used). *
- Open Windows' Task Manager with the "Processes" tab displayed.
- Arrange Interface and Task Manager windows so that you can see both.
- Wait for the domain and avatar content to finish loading, and the amount of memory that Interface uses to stabilize.
- Minimize the Interface Window.
- Wait half a minute and notice the amount of memory that Interface uses is increasing.
- Wait a couple of minutes and note that the amount of memory that Interface uses keeps increasing without limit.
- Restore the Interface Window so that it is displayed again.
- The Interface Window will appear to be frozen while the amount of memory Interface uses decreases to around what it was before, then contente appears to reload and Interface resumes working.

* Alternative to having other avatars: use the Record app and accompanying AC script to have an avatar recording playing back on the domain.

2) Test that the PR build fixes the memory problem.
- The amount of RAM that Interface uses should not increase while Interface is minimized.
- Interface should work immediately it is restored from minimized to visible, without content freezing and appearing to reload.

3) Check that updates on the local entity tree occur while Interface doesn't have focus (but isn't minimized).
- Create an empty directory that Interface snapshots will be saved in.
- Ensure that Developer > Render > Throttle FPS If Not Focus is enabled.
- Run Interface and go to an empty area of your localhost Sandbox domain.
- Run https://raw.githubusercontent.com/NissimHadar/hifi_tests/TEST19820/tests/content/entity/zone/testRecursive.js The first time it runs, it will prompt you to select a directory - select the one you created above. It will then proceed to take 35 snapshots. This will take a while. Keep Windows focus on Interface while the script is doing this. Note: Run the script from the URL (i.e., don't download it and run it locally). The script automatically deletes itself after running.
- View the snapshots and move them to another directory.
- Clear Interface's cache: Developer > Reload Content and Developer > Network > Clear Disk Cache.
- Restart Interface.
- Run the script again, but immediately move focus onto a different window and keep it there while the script is running.
- Expected result: The two folders of snapshots should contain identical sets of images. In particular, entities should not be missing in the second set of images.

https://highfidelity.manuscript.com/f/cases/17988

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15268/HighFidelity-Beta-PR14432-7ffa70d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15268/HighFidelity-Beta-PR14432-7ffa70d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15268/HighFidelity-Beta-Interface-PR14432-7ffa70d.dmg

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15432/HighFidelity-Beta-PR14432-7ffa70d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15432/HighFidelity-Beta-PR14432-7ffa70d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15432/HighFidelity-Beta-Interface-PR14432-7ffa70d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15432/HighFidelity-Beta-PR14432-7ffa70d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15432/HighFidelity-Beta-Interface-PR14432-7ffa70d.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
Here is the public link for the script
https://raw.githubusercontent.com/highfidelity/hifi_tests/master/tests/content/entity/zone/testRecursive.js

**Pull request merged**
