### PR TITLE
Fix sparse rectification for small textures

### PR DESCRIPTION
**Pull request by Atlante45**
Make sure even textures with a dimension smaller than the sparse page size get rectified.
This causes an issue when compressing such textures that are assumed to be a multiple of the compressed block sizes (4x4).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4365/HighFidelity-Beta-PR11656-bad12e8597fb15e9eba2472a5d1b15a1308c127b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4365/HighFidelity-Beta-PR11656-bad12e8597fb15e9eba2472a5d1b15a1308c127b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4380/HighFidelity-Beta-PR11656-1216fd29154da55742c348f9237b168878ac1fca.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4380/HighFidelity-Beta-PR11656-1216fd29154da55742c348f9237b168878ac1fca.exe

**Comment by ZappoMan** [comment]
test plan?

**Comment by Atlante45** [comment]
@ZappoMan Still working through some issues with the mip sizes, this is not yet ready for QA.
Mostly made the PR to show the engine team, will close in the mean time.

**Pull request closed without merging**
