### PR TITLE
Fix web entities accessing the webcam RC-61

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR fixes a security problem when using web entities. 

https://highfidelity.fogbugz.com/f/cases/10420/High-Fidelity-wants-to-use-webcam#

To test this PR is necessary to have a webcam properly installed on the computer.

...

## TEST PLAN
- Download and install a 30 days trial of Bitdefender TOTAL SECURITY 2018 https://www.bitdefender.com/Downloads/
- Open Bitdefender and go to privacy (top-left eye icon), and View Features. Make sure that Webcam Protection is ON.
- Install the latest dev build (7550 at this time), go to your sandbox and create a web entity.
- When the page is loaded Bitdefender should alert you that interface.exe is trying to gain access to the webcam. If not try this step again.
- Install this PR, go to sandbox and create a web entity. You should not receive any notification from Bitdefender this time.

This PR passed the QA test here: https://github.com/highfidelity/hifi/pull/11973

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5607/HighFidelity-Beta-PR11975-a1f1e7b587959b541cd17c1b5ead0474a20960ac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5607/HighFidelity-Beta-PR11975-a1f1e7b587959b541cd17c1b5ead0474a20960ac.dmg

**Comment by Nex-Pro** [comment]
Testing this as per #11973

**Comment by Nex-Pro** [comment]
Testing win !0

**Comment by Nex-Pro** [comment]
### PASS this did NOT trigger the bit defender webcam warning seen in 7550

***Warning seen in 7550***  
defender

Good job @luiscuenca  Thanks.

**Pull request merged**
