### PR TITLE
Fix crash in variable allocation management

### PR DESCRIPTION
**Pull request by jherico**
Fixes a crash described in https://www.bugsplat.com/keycrash/?stackKeyId=1976&database=interface_alpha

## Testing

This fixes an intermittent crash caused by a race condition, so there's no reliable way to reproduce the error.    A simple smoke test to ensure app functionality should be sufficient.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d0cb311d60da709688f2ecaf54152a512d51a56f available at: https://gist.github.com/b7c60933b9ebc48fd40e5ef01d7e3314<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10246-d0cb311.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10246-d0cb311.dmg

**Comment by OmegaHeron** [comment]
Smoke testing - Win 10 - i5 CPU

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 - GTX970
QA Pass

Basic smoke checks pass (Looked at starter sandbox, tutorial, dev-playa, dev-welcome and my own content) in Desktop and HMD (CV1+Touch Controls).  Did quick run through of tablet, edit mode, audio on off.  No issue seen.

**Comment by jherico** [comment]
superseded by #10208

**Pull request closed without merging**
