### PR TITLE
fix traits re-send after node unignored, agent crash

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

With this PR - ignore another avatar. When they are unignored, you should see them re-appear. On current master the un-ignored avatar does not re-appear.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12341/HighFidelity-Beta-PR13868-ac8f2a8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12341/HighFidelity-Beta-PR13868-ac8f2a8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12341/HighFidelity-Beta-Interface-PR13868-ac8f2a8.dmg

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Tested by having both users go to a shared domain. Both users ignored and then unignored the other with no problems. 

To be thorough, was moving to test different logged in states, when we found if you ignore someone and then un-ignored them, then that person signed in, that the purple mesh would return and no avatar would appear after 1+ minute. This fails the PR.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12353/HighFidelity-Beta-PR13868-09065cf.apk

**Comment by birarda** [comment]
Tested the failure steps as describe and could not reproduce the issue here. The avatar I un-ignored re-appeared immediately and disappeared and re-appeared as expected when they logged in. Possible I am missing something in the failure steps.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12355/HighFidelity-Beta-PR13868-e1879bf.apk

**Comment by qlipdahlin** [comment]
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2316250/hifi-log.txt)
[ac-20180823.15.07.02.342-stdout.txt](https://github.com/highfidelity/hifi/files/2316256/ac-20180823.15.07.02.342-stdout.txt)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12355/HighFidelity-Beta-PR13868-e1879bf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12355/HighFidelity-Beta-Interface-PR13868-e1879bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12355/HighFidelity-Beta-PR13868-e1879bf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12355/HighFidelity-Beta-Interface-PR13868-e1879bf.exe

**Comment by qlipdahlin** [comment]
[domain-server-9828-1535058414795-stdout.txt](https://github.com/highfidelity/hifi/files/2316445/domain-server-9828-1535058414795-stdout.txt)

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

The added issue was not related to this PR and is a separate issue. Passing PR.

**Pull request merged**
