### PR TITLE
Fix cloned 3D overlays' dimensions

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Run the attached script, cloneOverlays.js. It creates cube, sphere, shape (cone), and model (cylinder) overlays, plus clones of them above the originals.
- The clones (top overlays) should be the same dimensions as the originals (bottom overlays).
- The shape overlay clone should be the same shape (cone) as the original shape overlay.

[cloneOverlays.zip](https://github.com/highfidelity/hifi/files/1533357/cloneOverlays.zip)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5410/HighFidelity-Beta-PR11934-e074bd85f9683cab2e21b1df4ec4948917d00b7f.exe

**Comment by Nex-Pro** [comment]
Testing Win10

**Comment by Nex-Pro** [comment]
### PASS

hifi-snap-by--on-2017-12-06_00-27-24

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5418/HighFidelity-Beta-PR11934-cafebf6a7e89653fc6af55ca84ec68902ad4bf76.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5421/HighFidelity-Beta-PR11934-cafebf6a7e89653fc6af55ca84ec68902ad4bf76.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5423/HighFidelity-Beta-PR11934-cafebf6a7e89653fc6af55ca84ec68902ad4bf76.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5423/HighFidelity-Beta-PR11934-cafebf6a7e89653fc6af55ca84ec68902ad4bf76.dmg

**Pull request merged**
