### PR TITLE
point to tribbles.js on aws

### PR DESCRIPTION
**Pull request by davidkelly**
For now, anyways. Just temporary until dev is complete.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70a63417cfc71d1218de7fe1f22f09bf4a0548a4 available at: https://gist.github.com/4817786597bd2f1c0ae9165b549a0cd2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8711-70a6341.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8711-70a6341.dmg

**Comment by howard-stearns** [comment]
I think something's gone wrong. Won't this ultimately go to http://cdn.highfidelity.com/davidkelly/production/scripts/libraries/virtualBaton.js, but that url gives me access denied.

**Comment by davidkelly** [comment]
hmm odd.  It should be available now.  I think maybe it took awhile to show up?

**Comment by howard-stearns** [comment]
Indeed, it is there now. Must have just taken a while.

**Comment by howard-stearns** [comment]
closing here and merging instead to domain-check branch

**Pull request closed without merging**
