### PR TITLE
fix auto dropping and re-grabbing loop

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by Nex-Pro** [comment]
@druiz17 typo nearParentGrabEntity.js line 190 

parantage should be parentage

**Comment by druiz17** [comment]
@Nex-Pro I fixed the spelling error. Also can you QA this to see if you experience that issue that seth said you had.

**Comment by Nex-Pro** [comment]
@druiz17 Yep I know what to test for

**Comment by Nex-Pro** [comment]
Awaiting build

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3651/HighFidelity-Beta-PR11464-5a1242a1acde2e344ba3ef3f8753ea447f7688d2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3651/HighFidelity-Beta-PR11464-5a1242a1acde2e344ba3ef3f8753ea447f7688d2.dmg

**Comment by Nex-Pro** [comment]
T E S T I N G

**Comment by Nex-Pro** [comment]
This has fixed the auto dropping and re-grabbing loop problem.

However in the course of testing I see that create/edit mode is totally broken in this build.
I created a cube to do the near grabbing test for this and realised that I was unable to manipulate the entity with the lasers as I would normally do.

I don't know if this build broke that.

**Comment by Nex-Pro** [comment]
Was unable to compare to latest dev build as I don't get lasers in 7190.

**Comment by druiz17** [comment]
the issue you described is already in master

**Pull request merged**
