### PR TITLE
Beta Release 44 - Includes up to Developer Release 6702

### PR DESCRIPTION
**Pull request by cozza13**
- Save category on Marketplace when using back button
 - Entities resize via hand controllers when they're not supposed
 - Relax hands to default position/rotation when controller tracking is lost 
 - Spline IK target support
 - Fix head puck broken eyes 
 - Oven will now give proper return codes when used via CLI 
 - Adjust the preview to avoid seeing the masked pixels in HMD mode
 - Position tablet relative to hand 
 - **Add additional primitive shapes** https://github.com/highfidelity/hifi/pull/10624
 - Fix for no-audio on clean install 
 - Set active button property isActive before Home menu redraw
 -  Create helper functions for getting into avatar coordinate space
 - Update default avatar to baked mannequin 
 - Attempt to resolve Tablet scripting interface deadlocks 
 - Simplify eventBridge mechanism exposing functionality to web pages
 - Simple Render Engine refactors coming from the Spectator Cam project
 - Simplify fileOnUrl to only look for external textures right beside FBX 
 - Fix bug in clearFramebuffer with Stencil Buffer
 - Reworked Particle Editor UI 
 - Add support for querying the desired output audio device for OpenVR
 - Start the device check timer after its setup.
 - Small rendering improvements based on spectator-camera changes 
 - Make the PAL's tab background color white 
 - Use HMD roll angle to turn while flying or walking in HMD
 - Fix SharedNodePointer leak 
 - **New advanced avatar domain settings: Avatars Allowd from, and Replacement Avatar for disallowed avatars.** https://github.com/highfidelity/hifi/pull/10684
 - Fix no audio device from previously removed audio device
 - Smoothly ease hands from uncontrolled to controlled positions

Smoke test : http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

RC functionality test: https://docs.google.com/spreadsheets/d/1F8S8a8lyze1wEczT8hc0dmz3_7QLDiHOxntKW6g0UjY/edit#gid=1080464620

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/806/HighFidelity-Beta-PR10725-a1933b535dbb28315e7eeb275c86f985af851b51.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/806/HighFidelity-Beta-PR10725-a1933b535dbb28315e7eeb275c86f985af851b51.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/825/HighFidelity-Beta-PR10725-f7721b1ad0182951e1fd33de4845cc9c2b78fbef.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/825/HighFidelity-Beta-PR10725-f7721b1ad0182951e1fd33de4845cc9c2b78fbef.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success.  I did notice a 3D sphere with the X, Y, Z axis appearing in both desktop and HMD mode.  Perhaps this is a new feature?  If it is NOT meant to be default I am alerting you it is default.  I don't believe to be unexpected however I wanted to bring it to your attention.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |407 |334 |278
**Present Rate**: |407 |336 |269
**Present New Rate**: |366 |269 |239
**CPU Buffer Count**: |827 |1108 |1112
**GPU Buffer Count**: |307 |391 |325
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |61 |71 |104
**GPU Texture Count**: |53 |56 |61
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |28496 |205095 |128154
**Triangle Rate**: |14248000 |41019000 |64077000
**API Drawcall Count**: |46 |92 |83
**Drawcall Count**: |47 |86 |88
**Drawcall Rate**: |23500 |17200 |44000
**State Changes Texture Count**:|70 |95 |94
**Pipeline Count**: |26 |36 |29
**Item Opaques**: |33 |230 |107
**Item Translucents**: |14 |39 |19
**Item Lights**: |4 |35 |15
**Timing Opaques**: |0.121 |0.844 |0.37
**Timing Translucents**: |0.031 |0.04 |0.053
**Timing Lighting**: |0.058 |0.04 |0.036
**Render Frame**: |0.66 |1.281 |0.823


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED


capture

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - gtx970 GPU - Desktop and CV1+Touch

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop mode 1600x900 maximized window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2144 |31128 |263
**GPU Buffer Count**: |740 |1271 |172
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |223 |234 |62
**GPU Texture Count**: |177 |203 |56
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |257114 |714792 |30047
**Triangle Rate**: |15124352 |44674500 |1767470
**API Drawcall Count**: |180 |204 |17
**Drawcall Count**: |1297 |246 |17
**Drawcall Rate**: |76294 |15375 |1000
**State Changes Texture Count**:|327 |250 |44
**Pipeline Count**: |48 |36 |23
**Item Opaques**: |248 |360 |3
**Item Translucents**: |82 |25 |3
**Item Lights**: |11 |37 |0
**Timing Opaques**: |0.943 |0.955 |0.038
**Timing Translucents**: |0.129 |0.036 |0.016
**Timing Lighting**: |0.047 |0.036 |0.045
**Render Frame**: |1.646 |1.491 |0.624

CV1 90/90/90

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Ok - Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass
**Test 11**|Test Tablet in 2D and 3D|Pass

**Pull request merged**
