### PR TITLE
Add Window.protocolSignature() as a replacement for location.protocolVersion()

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
A new Window.protocolVersion() API function is provided in addition to the old, deprecated location.protocolVersion() API function.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Run the attached script and check that the two protocol version values reported are identical.

Also:
- Check that announcements (e.g., connection refused when try to go to domain with protocol mismatch) are displayed.
- The camera app in the /unpublishedScripts/camera-move/ still works (in particular the settings).

[testProtocolVersion.zip](https://github.com/highfidelity/hifi/files/1637122/testProtocolVersion.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6344/app_12186_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6344/HighFidelity-Beta-PR12186-2883e242854b42dadc55b24f44f7fc24b122947e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6344/HighFidelity-Beta-PR12186-2883e242854b42dadc55b24f44f7fc24b122947e.dmg

**Comment by Atlante45** [comment]
As long as you're changing this, you should rename it `protocolSignature`.
A version implies and incrementing order, but this is a hash.
version tells me I can do `if (Window.protocolVersion() > oldVersion) ...` which I can't.

**Comment by ctrlaltdavid** [comment]
Good idea. Will do.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6436/app_12186_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6436/HighFidelity-Beta-PR12186-13bbd1fcbfa3e4b6501c661300977fef8f9cd71d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6436/HighFidelity-Beta-PR12186-13bbd1fcbfa3e4b6501c661300977fef8f9cd71d.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
