### PR TITLE
Update the name of the collision shapes used in edit.js properties

### PR DESCRIPTION
**Pull request by huffman**
Update the names to be consistent with what is shown on the add model
dialog.

### CODE REVIEW

**Comment by huffman** [comment]
The names of the collision shapes shown in edit.js have been updated to be consistent with the names that are used in the add model dialog.

The new names are:
```
None
No Collision
Box
Sphere
Compound
One Hull
Hull Per Submesh
Static Mesh
Basic - Whole model
Good - Sub-meshes
Exact - All polygons (non-dynamic only)
```

To test:

1. Ensure that the names have been updated, show up correctly, and can be selected.

**Comment by nbq** [comment]
Will test this one

**Comment by RyanDowne** [comment]
We should also check the if an entity had previously been set to dynamic and you change the hull to be exact, the dynamic checkbox gets unchecked.

**Comment by nbq** [comment]
@RyanDowne I will test that also then in the build

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6d5a59c8ae2b4a82259a846d7b15f3c537be53b available at: https://gist.github.com/ef480560108a83cde60c5d43cebb5e8d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9481-f6d5a59.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9481-f6d5a59.dmg

**Comment by nbq** [comment]
Tester: Coal
CPU: i7 6700k
GPU: GF 970
OS: Windows 10


* No Collision **(checked, worked)**
* Box **(checked, worked)**
* Sphere **(checked, worked)**
* Compound **(checked, worked, changed to `Good - Sub-meshes`)**
* Basic - Whole model **(checked, worked)**
* Good - Sub-meshes **(checked, worked)**
* Exact - All polygons (non-dynamic only) **(checked, worked)**


To test a collision hull change I brought in an EZ-Tube and set collision to be no collision and then I used edit menu to change it to exact and it worked just fine. I was able to walk through it with none and once set to exact it used the correct hull and I tested because I could not walk through it head on but I could fall through the middle so it acted as a tube.

When on `Exact` I could not check dynamic, also if I had it as dynamic on another setting, it unchecked when I set it to `Exact`, this test was for @RyanDowne 

I can say this is a QA PASS because everything was selectable and showed up appropriate on the draw collision shapes also

**Pull request merged**
