### PR TITLE
fix mouse-grab moving both an overlay and an entity at the same time

### PR DESCRIPTION
**Pull request by sethalves**
- don't mouse-grab things through an overlay

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use mouse grab (aka grab.js) to move something around
- line up an overlay (like the edge of the online-users window or the tool-bar that holds edit.js controls) with the the object
- click *through* the overlay on the object
- while still holding down the mouse button, move the mouse
- observe that the object doesn't move (though the overlay may be)

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/527/Grabbing-object-behind-edit-bar-results-in-both-object-and-edit-bar-being-dragged

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4df7cada73dc8f8b5ec6b7ea52af38fc3424100 available at: https://gist.github.com/3ebc3417371b2d1e24447721e31ec8bc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4df7cada73dc8f8b5ec6b7ea52af38fc3424100 available at: https://gist.github.com/3ebc3417371b2d1e24447721e31ec8bc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c3c9f45d156f4803c40e592ffa4e23fab3ebef3 available at: https://gist.github.com/3ebc3417371b2d1e24447721e31ec8bc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7925.dmg

**Comment by kevinmthomas-carpool** [comment]
testing - Question @sethalves the ```grab.js``` does not actually allow mouse movement of entities for me.  Is this what you were referring to?

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful creation of dymanic object and manipulation with mouse with ```grab.js```. Upon moving it behind a UI such as Users, I was not able to move the entity.

**Pull request merged**
