### PR TITLE
Make udt::Connection live as long as node connection

### PR DESCRIPTION
**Pull request by birarda**
- fixes a case where avatars would not be seen when they enter the domain or leave a bubble

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan:
1) Change your avatar a dozen times and make sure another avatar in the domain sees every change
2) Leave the domain and come back a dozen times and make sure someone in the domain sees you every time you come back.
3) Create and edit an entity and make sure someone in the domain sees your entity + edits.
4) Upload a model to the asset server and rez it in world. Make sure you can see the model load.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5649/HighFidelity-Beta-PR11992-7f948586dd09afd464f7b5bb53756a29f45abd59.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5652/HighFidelity-Beta-PR11992-7f948586dd09afd464f7b5bb53756a29f45abd59.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5652/HighFidelity-Beta-PR11992-7f948586dd09afd464f7b5bb53756a29f45abd59.dmg

**Comment by cain-kilgore** [comment]
# Test Failed
Re-pro'd with birarda

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5658/HighFidelity-Beta-PR11992-da56d4730747bfa5ff8073249694cb3f9adc0a16.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5658/HighFidelity-Beta-PR11992-da56d4730747bfa5ff8073249694cb3f9adc0a16.dmg

**Comment by birarda** [comment]
#### Test Plan

1. Run through the two test cases here: https://highfidelity.testrail.net/index.php?/suites/view/496
2. Create and edit an entity and make sure someone in the domain sees your entity + edits.
3. Upload a model to the asset server and rez it in world. Make sure you can see the model load.

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Run through the two test cases here: https://highfidelity.testrail.net/index.php?/suites/view/496 | 👍 
Create and edit an entity and make sure someone in the domain sees your entity + edits. | 👍 
Upload a model to the asset server and rez it in world. Make sure you can see the model load. | 👍 

### [TestRun Available Here](https://highfidelity.testrail.net/index.php?/runs/view/1534&group_by=cases:section_id&group_order=asc)

**Pull request merged**
