### PR TITLE
Moving shape definition to a shared location

### PR DESCRIPTION
**Pull request by jherico**
Moving shape definitions for simple solids to a shared location so it can be used by the physics engine.

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
I'll test.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c02c963d4f06b009fb54a456d6fff67e9803a69 available at: https://gist.github.com/172d89810bd9f190fc65b06ba4c77bcf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9925bb9be7b07c3af8cf5eebf4ae35492b489934 available at: https://gist.github.com/172d89810bd9f190fc65b06ba4c77bcf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.dmg

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9925bb9be7b07c3af8cf5eebf4ae35492b489934 available at: https://gist.github.com/172d89810bd9f190fc65b06ba4c77bcf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a962d7aab95b8742b7bac005cae9dbd716bc859 available at: https://gist.github.com/172d89810bd9f190fc65b06ba4c77bcf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7975.dmg

**Comment by AndrewMeadows** [comment]
I tested this and found it to be working.

Although, there is a bug (in hifi/master) where any new shape will be reset to cube on relog by interface.

**Pull request merged**
