### PR TITLE
Fix edit.js from deselecting an object when trying to delete it

### PR DESCRIPTION
**Pull request by druiz17**
Test plan
- be in desktop mode and tablet mode
- while in edit mode select an object then click on the tablet.
- The selected object should stay selected

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: de24023a2142efb227a04742a8201c50ef14d2ba available at: https://gist.github.com/3c05164bedec23724ade87b06bdb6910<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9955-de24023.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9955-de24023.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: de24023a2142efb227a04742a8201c50ef14d2ba available at: https://gist.github.com/3c05164bedec23724ade87b06bdb6910<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9955-de24023.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9955-de24023.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass
Tried it in desktop and HMD (DK2), tablet mode enabled in both.  Created a cube, selected it and then clicked tablet in various places - object remained selected, hit delete on tablet and object deleted.

**Pull request merged**
