### PR TITLE
allow equipped object to follow hand and not controller

### PR DESCRIPTION
**Pull request by hyperlogic**
They can do this by adding the following to their userData.

    grabbableKey: {
        ignoreIK: false
    }

When this is present and false, the object will follow the hand joint, otherwise it will follow the hand controller.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/edit/1562/Boxing-dummy-Glove-comes-on-right-hand-in-wrong-place

**Comment by sethalves** [comment]
I think this may need a change in edit.js also -- there's a checkbox that adjusts userData for ignore-ik

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c7a9055d1eed3fede2c42bb255b5131edbd52e0 available at: https://gist.github.com/49fbdec3039991c5259a8ffa96098b4b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8758-7c7a905.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8758-7c7a905.dmg

**Comment by hyperlogic** [comment]
@sethalves I've fixed edit.js support.

**Comment by hyperlogic** [comment]
QA testplan:
   * From the marketplace spawn the ping pong gun.
   * When the ping pong gun is equipped it should follow the controller.  To test place the controller on your desk and walk away in room scale.  Your avatar's hand should separate from the gun.
   * Enter edit mode.  Select the ping pong gun.  The Ignore IK check box should be filled.
   * Click the Ignore IK check box in edit.js, setting it to false.
   * Exit edit mode. and select the ping pong gun again.  Do the same test where you place the controller on the desk and walk away in room scale.  In this case the gun should follow your avatar's hand and not become separated from it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f76dbeeffd9ab818d3508d22be2fd00d0b7e3dcd available at: https://gist.github.com/49fbdec3039991c5259a8ffa96098b4b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8758-f76dbee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8758-f76dbee.dmg

**Comment by thoys** [comment]
## QA Testing report

- I noticed the ignorance of the hand, the pingpong gun follows the controller 👍 
- `Ignore IK` was filled filled in when I opened its properties first.
- after disabling `Ignore IK` , the gun follows the hand more nicely.
- tried de-activating it again which makes it follow the hand-controller again.

QA Pass

**Pull request merged**
