### PR TITLE
Fix PAL scrollbar; add helper popup to ADMIN tab

### PR DESCRIPTION
**Pull request by zfox23**
Test plan:

* In a domain with more than two avatars present, open the PAL. Resize it so that the scroll bar appears on its right side. Check to ensure the scroll bar appears.
* In a domain where you are an admin, open the PAL. Check to ensure the "[?]" button appears to the right of the "ADMIN" string. Click it and ensure a popup appears. Click anywhere to close the popup.

### CODE REVIEW

**Comment by zfox23** [comment]
[Scrollbar is not visible](https://trello.com/c/8ywtzcCp/48-scrollbar-is-not-visible)

**Comment by zfox23** [comment]
[Add helper text to Admin functions too](https://trello.com/c/hvXu53v3/49-add-helper-text-to-admin-functions-too)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c77ff25564dc1ad24dc7fc51b8fda23630e509b available at: https://gist.github.com/2d48e8bfa6d943a89b128c491283f8ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-0c77ff2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-0c77ff2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 083bf95917d42682cddd179ea24392d5ade3aedf available at: https://gist.github.com/2d48e8bfa6d943a89b128c491283f8ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-083bf95.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-083bf95.dmg

**Comment by howard-stearns** [comment]
Not a blocker, but we should probably abstract out this popup stuff. DRY it up.

**Comment by ZappoMan** [comment]
What's the Test plan on this?

**Comment by zfox23** [comment]
Test plan:
* In a domain with more than two avatars present, open the PAL. Resize it so that the scroll bar appears on its right side. Check to ensure the scroll bar appears.
* In a domain where you are an admin, open the PAL. Check to ensure the "[?]" button appears to the right of the "ADMIN" string. Click it and ensure a popup appears. Click anywhere to close the popup.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5713656be0b47c18c4a09f442122236200e2412 available at: https://gist.github.com/2d48e8bfa6d943a89b128c491283f8ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5713656be0b47c18c4a09f442122236200e2412 available at: https://gist.github.com/2d48e8bfa6d943a89b128c491283f8ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.dmg

**Comment by zfox23** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5713656be0b47c18c4a09f442122236200e2412 available at: https://gist.github.com/2d48e8bfa6d943a89b128c491283f8ee<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9306-b571365.dmg

**Pull request merged**
