### PR TITLE
fix setting of domain local ID from domain list

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

On master, run the Sandbox. Confirm that the Asset Server log continuously outputs `[asset-server] Packet of type 61 (AssetMappingOperation) received from unknown node with UUID 00000000-0000-0000-0000-000000000000`.

Run the Sandbox from this PR - confirm that you see no such messages.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9039/app_12968_PR_779386fbc4ffbb336d22a9ef56687e0015624003.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9039/HighFidelity-Beta-PR12968-779386fbc4ffbb336d22a9ef56687e0015624003.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9039/HighFidelity-Beta-Interface-PR12968-779386fbc4ffbb336d22a9ef56687e0015624003.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9039/HighFidelity-Beta-PR12968-779386fbc4ffbb336d22a9ef56687e0015624003.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9039/HighFidelity-Beta-Interface-PR12968-779386fbc4ffbb336d22a9ef56687e0015624003.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No such line appears in the log.

**Pull request merged**
