### PR TITLE
Billboard entity property 

### PR DESCRIPTION
**Pull request by bwent**
Added new boolean entity property billboarded and enabled billboarding in text entities (text orients itself to face camera)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by PhilipRosedale** [comment]
Ok to test

**Comment by ZappoMan** [comment]
Add to whitelist

**Comment by jherico** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99cd9bada199535b4ab6e8836fc76745bbca528c available at: https://gist.github.com/ac816d69b94a070c6907<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5200.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5200.dmg

**Comment by hyperlogic** [comment]
I think you need to add a CHECK_PROPERTY_CHANGE macro to  the EntityItemProperties::getChangedProperties() method.

**Comment by hyperlogic** [comment]
Also, I think you need to add an entry into the EntityPropertyList enum.  Located in the EntityPropertyFlags.h file.

**Comment by hyperlogic** [comment]
Oh, I see you've already added it to the EntityPropertyFlags.h file

**Comment by ZappoMan** [comment]
I think we should add this property to the TextEntityItem and not the EntityItem base class, especially since we're only currently using it there. If we add it to lots of other entity types we can consider adding it to the base class.

**Comment by hyperlogic** [comment]
@bwent You can use the ParticleEffectEntityItem PROP_EMIT_DIRECTION as a model.  This class is also a subclass of EntityItem

**Pull request closed without merging**
