### PR TITLE
Revert "WL 21664 - Window.innerHeight should not include the menu bar"

### PR DESCRIPTION
**Pull request by misslivirose**
Reverts highfidelity/hifi#12102

Breaks spectator camera, FB case 11693

### CODE REVIEW

**Comment by misslivirose** [comment]
From the original PR, the following files are affected: 

In Hifi-content the following are used:
Marketplace/camera-move/app.js
Marketplace/spectator-camera/spectatorCamera.js
Marketplace/camera-move/app-camera-move.js

In the main repo there are 22 occurances, but the ones that aren't archived and that look like they are signifigant are the following:
scripts/developer/utilities/render/debugAmbientOcclusionPass.js
scripts/developer/utilities/render/debugSubsurfaceScattering.js
interface/resources/html/raiseAndLowerKeyboard.js
scripts/system/libraries/progressDialog.js
scripts/system/libraries/WebTablet.js
scripts/system/libraries/entityCameraTool.js
scripts/system/notifications.js
scripts/system/edit.js
scripts/system/html/js/entityList.js

**Test Plan**
Run Spectator Camera test plan (526) - confirm that view on viewfinder matches the display on screen
Check the render utilities 
Confirm that raising/lowering keyboard on tablet functions properly in both desktop / hmd mode
Test the webTablet script, notifications, that they work properly in both desktop / hmd mode
Run Create Mode test plan (1938) - confirm pages look correct in desktop / hmd mode

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6899/app_12330_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6899/HighFidelity-Beta-PR12330-4e2f91f9b56b9b6fddb265954492ceab59163d46.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6899/HighFidelity-Beta-PR12330-4e2f91f9b56b9b6fddb265954492ceab59163d46.dmg

**Comment by ctrlaltdavid** [comment]
Alternative PR: https://github.com/highfidelity/hifi/pull/12333

**Pull request closed without merging**
