### PR TITLE
9706 Editing Attachments Results In Attachments Window Scrolling To Top

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Open 'Attachements' dialog in 'Avatar' menu
2. Create 3 attachements. 
3. Scroll to the bottom
4. Type '1' into field 'Y' (or use up/down spinbox arrows)
5. Ensure scrollbar didn't change its position. 

Bonus: The issue was introduced during fixing https://highfidelity.fogbugz.com/f/cases/6719/ so makes also sense to check this PR doesn't introduce any regressions to 6719

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5358/HighFidelity-Beta-PR11919-d60f0827966a9082ce19129b866edd35912690fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5358/HighFidelity-Beta-PR11919-d60f0827966a9082ce19129b866edd35912690fd.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open 'Attachements' dialog in 'Avatar' menu | Pass
Create 3 attachements. | Pass
Scroll to the bottom | Pass
Type '1' into field 'Y' (or use up/down spinbox arrows) | Pass
Ensure scrollbar didn't change its position. | Pass

**Pull request merged**
