### PR TITLE
 Further remove dependencies of marketplaces.js on edit.js

### PR DESCRIPTION
**Pull request by zfox23**
**Test Plan:**
1. If you don't already own some, buy a few different entities (wearables and not wearables) from the Marketplace
2. Open your logs (CTRL+SHIFT+L)
3. From the "My Purchases" app, use the "REZ" or "WEAR" button to spawn those entities (in a domain in which you have permission, of course).
4. Keep an eye on your logs. Verify that you do not see any errors in the logs immediately after pressing the REZ/WEAR button
5. Open and close Create mode. Verify that you don't see any errors in the logs.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5534/HighFidelity-Beta-PR11957-be737af79db7e705b5745bfd7bb3a4d6fb1e5b2b.dmg

**Comment by zfox23** [comment]
Sec, I broke `create` mode. Thanks @sethalves

**Comment by zfox23** [comment]
OK it's fixed. Thanks @sethalves

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5541/HighFidelity-Beta-PR11957-a99072622a78a8eaa8b50f1913ae24e7af796650.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5541/HighFidelity-Beta-PR11957-a99072622a78a8eaa8b50f1913ae24e7af796650.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
If you don't already own some, buy a few different entities (wearables and not wearables) from the Marketplace | Pass
Open your logs (CTRL+SHIFT+L) | Pass
From the "My Purchases" app, use the "REZ" or "WEAR" button to spawn those entities (in a domain in which you have permission, of course). | Pass
Keep an eye on your logs. Verify that you do not see any errors in the logs immediately after pressing the REZ/WEAR button | Pass
Open and close Create mode. Verify that you don't see any errors in the logs. | Pass

Other than the `[12/09 00:46:00] [WARNING] [qml] [EditTabView.qml] Unrecognized message: {"method":"inspectionCertificate_resetCert"}` error which has since been fixed in master, this is a solid pass.

**Pull request merged**
