### PR TITLE
clear wallet when picking a new one

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes "Wrong wallet displays after "Locate Other Keys" button is selected"

### CODE REVIEW

**Comment by howard-stearns** [comment]
Fixes https://highfidelity.manuscript.com/f/cases/13058/Wrong-wallet-displays-after-Locate-Other-Keys-button-is-selected

Test plan:
Unfortunately, we need to test all the wallet setup stuff. I believe the tests are:
- "end seeding" https://highfidelity.testrail.net/index.php?/cases/view/12737&group_by=cases:section_id&group_order=asc&group_id=3940
- "setup: 1st Test" https://highfidelity.testrail.net/index.php?/cases/view/2185&group_by=cases:section_id&group_order=asc&group_id=440
- "Recover from Backup Keys" https://highfidelity.testrail.net/index.php?/cases/view/6012

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7901/app_12601_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7901/HighFidelity-Beta-PR12601-9d805283d14bc31d61d19abf11fd41ee1d283015.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7901/HighFidelity-Beta-PR12601-9d805283d14bc31d61d19abf11fd41ee1d283015.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Comment by conklin94122** [comment]
@howard-stearns Needs dev review

**Pull request merged**
