### PR TITLE
File dialog crash qt59

### PR DESCRIPTION
**Pull request by vladest**
Test plan:
- Build interface with Qt 5.9
- Run application and press Ctrl-J
- Press FROM DISK button
- walk thru different folders, like scripts-archive/examples etc
- make sure no crash occurs
- do this in both Tablet and HMI modes

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1155/HighFidelity-Beta-PR10839-51b44d90213e823280233088f8b5d6c84a0a73a1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1155/HighFidelity-Beta-PR10839-51b44d90213e823280233088f8b5d6c84a0a73a1.exe

**Comment by YuppyPlays** [comment]
@vladest    does Gustavo build work for this testing or does this indefinitely require building with QT 5.9? :)

**Comment by sethalves** [comment]
@YuppyPlays go ahead and test Gustavo's build.  We'd want to know if the PR broke that, also.

**Comment by YuppyPlays** [comment]
Excellent, testing now :)

**Comment by YuppyPlays** [comment]
Run application and press Ctrl-J **Check**
Press FROM DISK button **Check**
walk thru different folders, like scripts-archive/examples etc **Check**
make sure no crash occurs **Check**
do this in both Tablet and HMI modes **Check, tested in Tablet & Taskbar modes**

No crashing occurred for me, worked perfectly. :) **Pass**

**Comment by OmegaHeron** [comment]
@sethalves - would there be any use testing this on Ubuntu compiled against Qt5.9?

**Comment by sethalves** [comment]
Sure, any test is welcome.  I did this myself, and didn't see a crash.

**Comment by OmegaHeron** [comment]
Same here - looks good for Linux and, given enough tries, I could eventually crash master compiled against 5.9 so there seems goodness in this.

**Pull request merged**
