### PR TITLE
Merge pull request #11882 from howard-stearns/the-lost-ECDSA

### PR DESCRIPTION
**Pull request by howard-stearns**
ECDSA key handling for commerce.
(Merge to RC60 of https://github.com/highfidelity/hifi/pull/11882)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5262/HighFidelity-Beta-PR11901-39afb4ab6a8ad06476f816b132c370fa6ea20a0c.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5263/HighFidelity-Beta-PR11901-39afb4ab6a8ad06476f816b132c370fa6ea20a0c.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5264/HighFidelity-Beta-PR11901-39afb4ab6a8ad06476f816b132c370fa6ea20a0c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5264/HighFidelity-Beta-PR11901-39afb4ab6a8ad06476f816b132c370fa6ea20a0c.dmg

**Pull request merged**
