### PR TITLE
Case 21771: Possible Entity Scipt Ban Incident

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.manuscript.com/f/cases/21771/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18215/HighFidelity-Beta-PR15207-5f3e31b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18215/HighFidelity-Beta-Interface-PR15207-5f3e31b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18215/HighFidelity-Beta-PR15207-5f3e31b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18215/HighFidelity-Quest-Beta-PR15207-5f3e31b.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18220/HighFidelity-Beta-PR15207-2ab8eb9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18220/HighFidelity-Beta-Interface-PR15207-2ab8eb9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18220/HighFidelity-Beta-PR15207-2ab8eb9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18220/HighFidelity-Beta-Interface-PR15207-2ab8eb9.exe

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18223/HighFidelity-Beta-PR15207-2ab8eb9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18223/HighFidelity-Beta-Interface-PR15207-2ab8eb9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18223/HighFidelity-Beta-PR15207-2ab8eb9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18223/HighFidelity-Quest-Beta-PR15207-2ab8eb9.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18223/HighFidelity-Beta-PR15207-2ab8eb9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18223/HighFidelity-Beta-Interface-PR15207-2ab8eb9.exe

**Pull request merged**
