### PR TITLE
Merge RC65 Stable to Master

### PR DESCRIPTION
**Pull request by conklin94122**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8069/app_12657_PR.apk

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8072/app_12657_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8072/HighFidelity-Beta-PR12657-0d343ee827bd597e8f7d6728b27fe6880ada6a52.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8072/HighFidelity-Beta-PR12657-0d343ee827bd597e8f7d6728b27fe6880ada6a52.dmg

**Pull request closed without merging**
