### PR TITLE
Fix for lurching walk(case 16945), when walking in hmd.    

### PR DESCRIPTION
**Pull request by amantley**
This pr implements a walking state that is set when horizontal recentering is activated.
When _isInWalkingState is true, the center of gravity calculation is not done to place the hips which stops the hips from drifting behind the head during walking with a headset on.
Also in the step detection code in prephysics update, when we are in the walking state steps will always be detected.  
So we do not try to detect leaning until we have left the walk state.

The case associated with the lurching, walking is here https://highfidelity.manuscript.com/f/cases/16945/When-people-walk-around-in-the-physical-space-the-leaning-looks-very-weird

### Test Plan
1. Open Interface and go to a domain with room to walk and a mirror,
2. Walk towards the mirror and you should see that you no longer lurch forward.
3. Leaning in all directions should behave as before.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12722/HighFidelity-Beta-PR13952-c986d55.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12722/HighFidelity-Beta-PR13952-c986d55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12722/HighFidelity-Beta-Interface-PR13952-c986d55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12722/HighFidelity-Beta-PR13952-c986d55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12722/HighFidelity-Beta-Interface-PR13952-c986d55.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Unable to lean and walk as intended.

**Pull request merged**
