### PR TITLE
fix far-grab laser-lock on entities with non-default registration point

### PR DESCRIPTION
**Pull request by sethalves**
- fix far-grab laser-lock on entities with non-default registration point

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- create an entity, change its rotation, dimensions, and registration point in various ways
- far-grab the entity between each change
- make sure the beam sticks on the entity at the point where it first touched.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12431/HighFidelity-Beta-PR13887-52bbb4d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12431/HighFidelity-Beta-PR13887-52bbb4d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12431/HighFidelity-Beta-Interface-PR13887-52bbb4d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12431/HighFidelity-Beta-PR13887-52bbb4d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12431/HighFidelity-Beta-Interface-PR13887-52bbb4d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Far Grab laser works as expected after editing various entities.

**Pull request merged**
