### PR TITLE
Fix randFloat error in ac audio searcher

### PR DESCRIPTION
**Pull request by huffman**
Previously we were including an external http file. For the tutorial everything should be available via ATP. This fixes that issue.

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Go to the garden area of your server and take note of the different sounds
 1. Upload https://raw.githubusercontent.com/huffman/hifi/c73c59baee08865717b057726ebdd0da6440de00/tutorial/ACAudioSearchAndInject_tutorial.js to your ATP server
 1. Stop your server
 1. Clear the cache (`C:/Users/USERNAME/Local/High Fidelity - PR10405`)
 1. Start your server
 1. Go to the garden area of your server and confirm that you are can hear the different audio sounds that you heard in Step 1

**Comment by hifi-gustavo** [comment]
Build console output for commit: c73c59baee08865717b057726ebdd0da6440de00 available at: https://gist.github.com/c95f818701182565a522e343335c7c08<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10405-c73c59b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10405-c73c59b.dmg

**Comment by OmegaHeron** [comment]
Will test this.

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Steps 1...5 *Done*
Step 6 - Same sounds heard.

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: c73c59baee08865717b057726ebdd0da6440de00 available at: https://gist.github.com/c95f818701182565a522e343335c7c08<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10405-c73c59b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10405-c73c59b.dmg

**Pull request merged**
