### PR TITLE
Commerce: Fix wrap mode for very long P2P memos

### PR DESCRIPTION
**Pull request by zfox23**
Ensures that very long, single-word memos are wrapped correctly for viewing in Recent Activity.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
- User must have at least one connection to carry out this test plan.
1. Open the Wallet. Go to the "Send Money" tab. Click "Connection", and select a connection. Send 1 HFC, and make the memo something very long and without spaces, like `afojisepjfaoisjefpoaijsepfoijaspoeifjaposijefpoaijsepfoijasp`. Send the money.
2. Go to Wallet Home.
3. Verify that your memo is fully displayed in Recent Activity, and that the memo text doesn't go beyond the right side of the display.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7164/app_12394_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7164/HighFidelity-Beta-PR12394-3e41229e8c674c1a568c16b4b199c5a0f1d8632f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7164/HighFidelity-Beta-PR12394-3e41229e8c674c1a568c16b4b199c5a0f1d8632f.exe

**Comment by howard-stearns** [comment]
Testing Reminder - please do not throw away HFC in production. Use staging per QA instructions.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Pass

@conklin94122

**Pull request merged**
