### PR TITLE
fix Asset browser for tablet (RC62)

### PR DESCRIPTION
**Pull request by druiz17**
fix Asset browser for tablet

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1) Start interface with HMD
2) Open tablet and click Create
3) Click "Open this domain's asset server"
4) Asset Browser page should open

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6272/app_12168_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6272/HighFidelity-Beta-PR12168-a48304b1047be440dbabf033270ff15325d550b5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6272/HighFidelity-Beta-PR12168-a48304b1047be440dbabf033270ff15325d550b5.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Start interface with HMD | 👍 
Open tablet and click Create | 👍 
Click "Open this domain's asset server" | 👍 
Asset Browser page should open | 👍 

Working all good here.

@conklin94122

**Pull request merged**
