### PR TITLE
Implement Wallet Security feature - Auto Logout checkbox

### PR DESCRIPTION
**Pull request by zfox23**
I'm going to write a big test plan that includes the plan for #13859. I'll link that below as the test plan for this one.

Implements a checkbox in the Wallet's Security tab named "Automatically Log Out when Exiting Interface". There's also a little Help "[?]" link for more information. The setting is defaulted to `false`.

If you check that box, you'll be logged out of Interface when you quit it. Next time you start it up and you go to log in, the "Username" field in the Login dialog will be pre-populated with the previously logged-in username.

If the user changes accounts, the setting resets to `false` and the saved username is cleared.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12357/HighFidelity-Beta-PR13870-dddb214.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12357/HighFidelity-Beta-PR13870-dddb214.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12357/HighFidelity-Beta-Interface-PR13870-dddb214.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12362/HighFidelity-Beta-PR13870-dc1a33b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12362/HighFidelity-Beta-PR13870-dc1a33b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12362/HighFidelity-Beta-Interface-PR13870-dc1a33b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12362/HighFidelity-Beta-PR13870-dc1a33b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12362/HighFidelity-Beta-Interface-PR13870-dc1a33b.exe

**Comment by zfox23** [comment]
# Test Plan
This test plan is designed such that the QA team can integrate it into the [existing Commerce test suite on TestRail](https://highfidelity.testrail.net/index.php?/suites/view/1128&group_by=cases:section_id&group_order=asc).

## Test 1: An existing user with a set-up wallet from before this PR who DOES NOT have their `.hifikey` file already in the right place can still access and rez their Purchases.
### Prerequisites
- You've previously verified (on another build) that you can Rez purchased items when using this account and wallet.
- You're logged in to an account associated with a wallet. That wallet was set up using a PR build or released build that isn't from this PR.
- You DO NOT have a `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity - PR13870/Interface/<your username>.hifikey`
    - However, have the `.hifikey` file associated with your previously-set-up wallet handy.
- You're standing in your Sandbox where you have at least Rez and Rez Certified rights.
- You're running an Interface client from this PR.

### Tests
1. Open the Wallet app
    - Verify that you see a message indicating you have already set up a wallet for this account.
    - Verify that you are prompted to search for wallet file on your computer.
2. Select the existing `.hifikey` wallet file on your hard drive.
    - Verify that you are prompted for your passphrase.
3. Input your passphrase.
    - Verify that you are taken to the Wallet app's main screen.
4. Open "My Purchases"
    - Verify that you see all of the purchases there that you would expect.
5. Rez one of the entities from My Purchases.
    - Verify that it appears in your Sandbox.
6. Exit Interface.
7. Delete or rename the `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity - PR13870/Interface/<your username>.hifikey`
8. Open Interface.
9. Open the Wallet app
    - Verify that you are NOT prompted for a wallet file or a passphrase.
    - Verify that you see the main Wallet app screen.
10. Open "My Purchases"
    - Verify that you see all of the purchases there that you would expect (i.e. the same ones as in (4)).
    
## Test 2: An existing user with a set-up wallet from before this PR who DOES have their `.hifikey` file already in the right place can still access and rez their Purchases.
### Prerequisites
- You're using a different account from Test 1
- You've previously verified (on another build) that you can Rez purchased items when using this account and wallet.
- You're logged in to an account associated with a wallet. That wallet was set up using a PR build or released build that isn't from this PR.
- You DO have a `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity - PR13870/Interface/<your username>.hifikey`
- You're standing in your Sandbox where you have at least Rez and Rez Certified rights.
- You're running an Interface client from this PR.

### Tests
1. Open the Wallet app
    - Verify that you are prompted for your passphrase.
2. Input your passphrase.
    - Verify that you are taken to the Wallet app's main screen.
3. Open "My Purchases"
    - Verify that you see all of the purchases there that you would expect.
4. Rez one of the entities from My Purchases.
    - Verify that it appears in your Sandbox.
5. Exit Interface.
6. Delete or rename the `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity - PR13870/Interface/<your username>.hifikey`
7. Open Interface.
8. Open the Wallet app
    - Verify that you are NOT prompted for a wallet file or a passphrase.
    - Verify that you see the main Wallet app screen.
9. Open "My Purchases"
    - Verify that you see all of the purchases there that you would expect (i.e. the same ones as in (3)).
    
## Test 3: A user who has tested this PR can revert back to a previous build, then access and rez their Purchases.
### Prerequisites
- You've gone through Test 2 above.
- You're logged in to the same account as in Test 2.
- You're running the **currently-released Beta version of Interface.**
- You DO have a `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity< - the version you choose to run>/Interface/<your username>.hifikey`
- You're standing in your Sandbox where you have at least Rez and Rez Certified rights.

### Tests
1. Open the Wallet app
    - Verify that you are prompted for your Passphrase
2. Type in your passphrase.
    - Verify that the passphrase doesn't work
3. Enter the passphrase <ACCOUNT>
    - Verify that your wallet is now authenticated and that you can see Wallet Home
4. Open "My Purchases"
    - Verify that you see all of the purchases there that you would expect.
5. Rez one of the entities from My Purchases.
    - Verify that it appears in your Sandbox.
    
## Test 4: A new user can create a new wallet, purchase items, and rez them.
### Prerequisites
- You've set up and are signed into a new High Fidelity account.
- You HAVE NOT yet set up a Wallet associated with this account.
- You are standing in your Sandbox.

### Tests
1. Open the Wallet app
    - Verify that you are taken to Wallet Home and you are NOT prompted to set up or authenticate anything
2. From the Marketplace, purchase an entity for free. Open My Purchases.
    - Verify that you see the item in My Purchases.
3. Rez the item from (2).
    - Verify that you can see the rezzed item in your Sandbox.
4. Exit Interface.
5. Delete or rename the `.hifikey` wallet file located at `%AppData%/Roaming/High Fidelity - PR13870/Interface/<your username>.hifikey`
6. Open Interface.
7. Open the Wallet app
    - Verify that you are taken to Wallet Home and you are NOT prompted to input a passphrase.
8. Open My Purchases.
    - Verify that you still see the item from (2)
9. Rez the item from (2).
    - Verify that you can see the rezzed item in your Sandbox.
    
## Test 5: A user who has previously set up a wallet using this PR can still access their wallet when using a completely clean installation
### Prerequisites
- You're either on a new machine, or have freshly reinstalled this PR such that `%AppData/Roaming/High Fidelity - PR13870` doesn't exist.
- You're signed into the same account as in Test 4.

### Tests
1. Open the Wallet app
    - Verify that you are taken to Wallet Home and you are NOT prompted to set up or authenticate anything
2. Open My Purchases.
    - Verify that you see the item you purchased in Test 4.2 in My Purchases.
3. Rez the item from (2).
    - Verify that you can see the rezzed item in your Sandbox.
    
## Test 6: A user who is concerned about security can set Interface to automatically log out of their HiFi account when exiting Interface.
### Prerequisites
- You've run one or all of Tests 1-5 above.
- You're logged into one of the accounts from any of Tests 1-5 above.
- You have an HMD.

### Tests
1. Open the Wallet app
    - Verify that you are taken to Wallet Home and you are NOT prompted to set up or authenticate anything
2. Click the "Security" tab.
    - Verify that you see the Security tab of the wallet, which allows you to change your security pic and contains a new option called "Automatically Log Out when Exiting Interface"
    - Verify that "Automatically Log Out when Exiting Interface" is UNCHECKED
3. Close then re-launch Interface.
    - Verify that you are still logged in to Interface using the same account as in (1).
4. Check the box called "Automatically Log Out when Exiting Interface" from within the Security tab of the Wallet app.
5. Close then re-launch Interface.
    - Verify that you are NOT logged in to Interface
6. Click File -> Log In while in Desktop mode
    - Verify that you see a login dialog that contains the Username field pre-filled from the account in (1).
7. Input the passphrase to your HiFi account and log in.
    - Verify that you are logged in.
8. Open the Wallet app. Click the "Security" tab.
    - Verify that "Automatically Log Out when Exiting Interface" is CHECKED
9. Close then re-launch Interface.
    - Verify that you are NOT logged in to Interface
10. Click File -> Log In while in HMD mode
    - Verify that you see a login dialog that contains the Username field pre-filled from the account in (1).
11. Log out of Interface. Close then re-launch Interface.
    - Verify that you are NOT logged in to Interface
12. Click File -> Log In while in Desktop mode
    - Verify that you see a login dialog that DOES NOT contain the Username field pre-filled from the account in (1).
13. Log in to High Fidelity using the same account as in (1).
14. Open the Wallet app
    - Verify that you are taken to Wallet Home and you are NOT prompted to set up or authenticate anything
15. Click the "Security" tab.
    - Verify that you see the Security tab of the wallet, which allows you to change your security pic and contains a new option called "Automatically Log Out when Exiting Interface"
    - Verify that "Automatically Log Out when Exiting Interface" is UNCHECKED

**Comment by rickcarr044** [comment]
build this please

**Comment by rickcarr044** [comment]
Currently testing 13870

**Comment by rickcarr044** [comment]
FAIL @conklin94122

Finished with Test Pass 1 and 6.  Will follow through with Test Pass 2-5.

**Comment by zfox23** [comment]
@rickcarr044 can you please send me a video of what you're seeing in Test 6?

**Comment by rickcarr044** [comment]
Test 3 also failed in that the passphrase was accepted in Step 5 and the wallet was restored.  However it could be because I used the same account I already used in Test 2.

**Comment by rickcarr044** [comment]
PASS @conklin94122

Test 6 was retested as PR13905 and passed.
Test 3 was retested as MS17894 and passed.

Barring any additional issues discovered it appears the new Wallet functionality will be released to stable this afternoon.

**Pull request merged**
