### PR TITLE
Save the "Mute Microphone" setting

### PR DESCRIPTION
**Pull request by orenh1**
Currently this setting isn't saved, so the user has to re-mute the microphone every time they start Interface.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by Nex-Pro** [comment]
At last!

**Comment by sethalves** [comment]
to test:
- open the AUDIO page
- mute the microphone
- exit interface
- relaunch interface
- note that the microphone is still muted
- unmute the microphone
- exit interface
- relaunch interface
- note that the microphone is unmuted

**Comment by sethalves** [comment]
build this please

**Comment by sethalves** [comment]
Apparently unmute-on-launch was a design decision.  We'll re-debate it.  Maybe we need to show the level-meter on the HUD any time interface is muted.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8814/app_12900_PR_69cca31743f068415ba7b2c295788e3d04f83e60.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8814/HighFidelity-Beta-PR12900-69cca31743f068415ba7b2c295788e3d04f83e60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8814/HighFidelity-Beta-Interface-PR12900-69cca31743f068415ba7b2c295788e3d04f83e60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8814/HighFidelity-Beta-PR12900-69cca31743f068415ba7b2c295788e3d04f83e60.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8814/HighFidelity-Beta-Interface-PR12900-69cca31743f068415ba7b2c295788e3d04f83e60.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Mute Microphone function now saves between restarts of interface.

**Comment by ZappoMan** [comment]
Closing this because it so out of date.

**Pull request closed without merging**
