### PR TITLE
Tablet Prototype #2

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5254/HighFidelity-Beta-PR11898-a012e73117cb573fa8d4de9bae3dc93a54113176.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5258/HighFidelity-Beta-PR11898-ffe4ff8efed1c5f1d2c8c4d611afd36d711b369b.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5261/HighFidelity-Beta-PR11898-ffe4ff8efed1c5f1d2c8c4d611afd36d711b369b.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5265/HighFidelity-Beta-PR11898-ffe4ff8efed1c5f1d2c8c4d611afd36d711b369b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5279/HighFidelity-Beta-PR11898-43d2b7e4cbe44c0f4d5a0350122b7498447bae71.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5279/HighFidelity-Beta-PR11898-43d2b7e4cbe44c0f4d5a0350122b7498447bae71.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5282/HighFidelity-Beta-PR11898-a7598cc849c98160a52f1dea5f8b46b0e3bcf207.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5287/HighFidelity-Beta-PR11898-48f6948cc87ceee0e85eac1ca2f2f3fc123a4888.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5297/HighFidelity-Beta-PR11898-e76653dc1989a402aac399d8783bb90d83e28dd7.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5298/HighFidelity-Beta-PR11898-e76653dc1989a402aac399d8783bb90d83e28dd7.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5304/HighFidelity-Beta-PR11898-e76653dc1989a402aac399d8783bb90d83e28dd7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5304/HighFidelity-Beta-PR11898-e76653dc1989a402aac399d8783bb90d83e28dd7.dmg

**Pull request closed without merging**
