### PR TITLE
DNM Case 21084 - removed unneeded copying of SSL DLL's.

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/21084/Clean-builds-failing-due-to-error-in-CMakeList-file

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17152/HighFidelity-Beta-PR14882-80392b1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17152/HighFidelity-Beta-PR14882-80392b1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17152/HighFidelity-Beta-Interface-PR14882-80392b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17152/HighFidelity-Beta-PR14882-80392b1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17152/HighFidelity-Beta-Interface-PR14882-80392b1.exe

**Comment by samcake** [comment]
Good to go

**Pull request merged**
