### PR TITLE
Instrument ui scripts

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1459/HighFidelity-Beta-PR10919-7493a1e9118b9136290f9f78cbadea1c3b0d99bb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1459/HighFidelity-Beta-PR10919-7493a1e9118b9136290f9f78cbadea1c3b0d99bb.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1467/HighFidelity-Beta-PR10919-033e3237b9d0612e8c78282b0d8c61789426f125.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1467/HighFidelity-Beta-PR10919-033e3237b9d0612e8c78282b0d8c61789426f125.dmg

**Comment by sethalves** [comment]
closing this to give gustavo a break

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1474/HighFidelity-Beta-PR10919-4fa3cfe9d4d8bef3366e6e9cf84e7cbc5a1e4ade.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1474/HighFidelity-Beta-PR10919-4fa3cfe9d4d8bef3366e6e9cf84e7cbc5a1e4ade.dmg

**Pull request closed without merging**
