### PR TITLE
Prototyping a way to produce a selfie and use the rendering directly

### PR DESCRIPTION
**Pull request by samcake**
Adding a selfie frame pipeline
making it available under a hard coded url "http://selfieFrame"

This can be represented by a regular OverlayImage3D setting that url for the image
and voila

run the attached "debugSelfie.js" to do exactly that

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2b2dd267e0f72ecdcd2ec53dd97bf6c912f95178 available at: https://gist.github.com/262fb7219ffb12abc8b36ecf3760b1d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-2b2dd26.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-2b2dd26.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39241bec133f90e7c018116b6a0f34f2690fb6ef available at: https://gist.github.com/262fb7219ffb12abc8b36ecf3760b1d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-39241be.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-39241be.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b53a501ed2cf1e94b0e6c01466f96f5856d1a9bf available at: https://gist.github.com/262fb7219ffb12abc8b36ecf3760b1d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-b53a501.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10448-b53a501.dmg

**Comment by howard-stearns** [comment]
I'm going to work with this as is, and we'll deal with the windows warning as part of that.
Thanks, Sam!

**Pull request merged**
