### PR TITLE
close file browser dialog immediately after selecting asset to upload

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
This prevents an Interface crash.

Testing...

Before (i.e., with non-PR build):
- Ctrl-Shift-A to open Asset Browser.
- Press "Choose File" button; file browser dialog opens.
- Select a JSON file and press "Open" button.
- "Specify Asset Path" dialog opens over the top of the file browser dialog.
- In the file browser dialog, press "Cancel" button (e.g., to try and close the dialog).
- Interface crashes.

After (i.e., with this PR build):
- As above except after pressing the "Open" button the file browser dialog closes before the "Specify Asset Path" dialog opens.

And check that assets are still uploaded OK.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 18b0ed9e8fd2070fc01bbf70da8866964e85ac93 available at: https://gist.github.com/edd9a5fb194e7d9b30d141829d34df6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8336-18b0ed9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8336-18b0ed9.dmg

**Comment by Nex-Pro** [comment]
@ctrlaltdavid I tried this with the disc hat json file which points to one of Seth's obj files.  all it did was make an entry in the asset browser. Also I observed some odd behaviour whereby double clicking on the disc-hat entry in the asset browser opened the "fan" folder.
pr8336assetbrowser

**Comment by ctrlaltdavid** [comment]
@Nex-Pro Does the "disc-hat test" work for you with a non-PR version of Interface (5213 or later)?

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  I have 5211

**Comment by Nex-Pro** [comment]
grabbing 5215

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  Uploading or using ATP for JSON files in 5125 fails also.

**Comment by ctrlaltdavid** [comment]
@Nex-Pro I can't reproduce the problem you're having. But I note that in the screensnap "disc-hat" appears without a trailing ".json". When I upload JSON files, e.g., test33.json, I get an entry, "test33.json".

**Comment by ctrlaltdavid** [comment]
I believe everything's working OK: can upload JSON and FBX files to Asset Browser OK; can add FBX files to world. ... "disc hat" JSON file issue is probably something else and it would be worth adding it in a FogBugz report to investigate further.

**Comment by imgntn** [comment]
this no longer crashes when i hit cancel; uploading json works for me.  i remember i had a malformed hat json from seth once that caused issues.  anyhoo, working well for me win10

**Pull request merged**
