### PR TITLE
Fix avatar entity locking

### PR DESCRIPTION
**Pull request by sethalves**
- fix a crash in avatar-mixer and various interface-side instabilities related to avatar-entities

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- import disc-hat
- make sure you're using servers from this build
- with someone watching (running this same build), put the hat on and take it off a bunch of times

disc-hat json follow...

```{
    "Entities": [
        {
            "clientOnly": 0,
            "collidesWith": "dynamic,otherAvatar,",
            "collisionMask": 18,
            "created": "2016-06-07T20:57:35Z",
            "dimensions": {
                "x": 1,
                "y": 0.10000000149011612,
                "z": 1
            },
            "id": "{90a19ceb-ced9-4a13-ac5f-7670cd3d0e73}",
            "modelURL": "http://headache.hungry.com/~seth/hifi/puck.obj",
            "name": "test hat",
            "owningAvatarID": "{00000000-0000-0000-0000-000000000000}",
            "queryAACube": {
                "scale": 1.4177446365356445,
                "x": -0.70887231826782227,
                "y": -0.70887231826782227,
                "z": -0.70887231826782227
            },
            "rotation": {
                "w": -0.94335854053497314,
                "x": -0.033157825469970703,
                "y": -0.33009845018386841,
                "z": 0.0037689208984375
            },
            "type": "Model",
            "userData": "{\"grabbableKey\":{\"grabbable\":true},\"wearable\":{\"joints\":{\"head\":[{\"x\":-0.023434510454535484,\"y\":0.09226718544960022,\"z\":0.05430847406387329},{\"x\":-0.289015531539917,\"y\":-0.18519480526447296,\"z\":-0.9361469745635986,\"w\":-0.07657171040773392}],\"Head\":[{\"x\":0.6244014501571655,\"y\":0.2906707525253296,\"z\":0.20051050186157227},{\"x\":0.5731832385063171,\"y\":-0.24134553968906403,\"z\":-0.781941831111908,\"w\":-0.042739368975162506}]}}}"
        }
    ],
    "Version": 60
}
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e940e1055590f5a09c4fe9df6fd64afd0925557 available at: https://gist.github.com/a75362b5ff16905ddf4fbe6ed05e2dd5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8041.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8041.dmg

**Comment by sethalves** [comment]
i hate you, gustavo

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2e940e1055590f5a09c4fe9df6fd64afd0925557 available at: https://gist.github.com/a75362b5ff16905ddf4fbe6ed05e2dd5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8041.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8041.dmg

**Comment by Nex-Pro** [comment]
@sethalves  Testing notes are unclear to a noob like me. Am I supposed to select the json file and try to wear it? Or use the link to the OBJ that is in the JSON file ? Or import it to the ATP?

**Comment by Nex-Pro** [comment]
I used the url of the puck in the JSON  and used that as the attachment. But nothing happened in my view. I had to restart interface to see it. My kid could see it from her interface.

When I detached the item it disappeared from her view but remained in my view but now unattached. 
The puck was now non editable. It persisted until I restarted interface.

**Comment by sethalves** [comment]
This PR doesn't affect attachments, only "worn" entities.  So -- after importing the puck/hat, use a hand-controller to move the center of the puck near your avatar's head.  It should sort-of stick to your avatar until you grab it and move it away from your avatar's head.  Without this PR, doing this can sometimes crash the avatar-mixer.

**Comment by Nex-Pro** [comment]
Ah ok I'll have to drop this one.

**Comment by cozza13** [comment]
Tested with Seth. QA Pass

**Pull request merged**
