### PR TITLE
go to error-room when failing to connect to a full domain

### PR DESCRIPTION
**Pull request by sethalves**
- go to error-room when failing to connect to a full domain

https://highfidelity.fogbugz.com/f/cases/19295/Interstitial-page-freezes-when-trying-to-connect-to-domain-that-has-reached-maximum-user-capacity

https://github.com/highfidelity/hifi/pull/14199

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- try the repro in the linked ticket.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13841/HighFidelity-Beta-PR14196-47d3c9b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13841/HighFidelity-Beta-PR14196-47d3c9b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13841/HighFidelity-Beta-Interface-PR14196-47d3c9b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13841/HighFidelity-Beta-PR14196-47d3c9b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13841/HighFidelity-Beta-Interface-PR14196-47d3c9b.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
