### PR TITLE
Moving OpenVR to external plugin

### PR DESCRIPTION
**Pull request by jherico**
This migrates OpenVR integration to an external DLL loaded at runtime.  It also disables the OpenVR integration for now since it's broken and seems to conflict with Oculus SDK 0.8

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f003c12ac8d3c79c8beaf019fa9983bd6f53a0b available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6f003c12ac8d3c79c8beaf019fa9983bd6f53a0b available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c3a0163e84b977a10d23cf390f83ab1c1f9709e8 available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0334fb1a1d364c72575efd335023ec1b25a26e63 available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d926742ae75dbd7f5b4c07191364e8ad1c3d4f4 available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4190216e299a10984cac38aef1688a5e026d0e32 available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa2220633fa8a53ee13ffb6eb2e75fc04148e2fa available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e8e67af9137e658abfbc8b8d5874291999dd9e3 available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd5fb3096f2eacaeddf98977be9caa06ab258c7b available at: https://gist.github.com/4842f09cd63604375bf2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6598-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6598.dmg

**Pull request merged**
