### PR TITLE
cases 20709 and 20715: wear and see mexico hats

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.manuscript.com/f/cases/20709/Unable-to-equip-hats-while-in-HMD-in-mexico-dev

https://highfidelity.manuscript.com/f/cases/20715/Wearables-parented-to-the-head-no-longer-temporarily-render-while-being-grabbed-and-adjusted-in-VR

https://highfidelity.manuscript.com/f/cases/20326/Try-on-Items-selected-while-avatar-is-moving-cause-corresponding-wearables-to-maintain-avatar-velocity

This PR fixes two bugs: (1) the ability to wear a "mexico hat" and (2) the ability to see it when grabbing it

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
to test:

- Visit hifi://mexico-dev
- In HMD mode, grab a hat and put it on your head.  It should not render while worn on your head but verify other people see it attached to your head.  Also, you should be able to see the hat on your head when you look in the mirror.
- Grab it again and make sure it is visible while it's being adjusted.

Note -- sometimes the hat seems to ignore mouse-clicks. this is due to an unrelated problem.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16531/HighFidelity-Beta-PR14731-74f9a41.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16531/HighFidelity-Beta-PR14731-74f9a41.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16531/HighFidelity-Beta-Interface-PR14731-74f9a41.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16531/HighFidelity-Beta-PR14731-74f9a41.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16531/HighFidelity-Beta-Interface-PR14731-74f9a41.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16648/HighFidelity-Beta-PR14731-74f9a41.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16648/HighFidelity-Beta-PR14731-74f9a41.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16648/HighFidelity-Beta-PR14731-74f9a41.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16648/HighFidelity-Beta-Interface-PR14731-74f9a41.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
