### PR TITLE
Purge RayPick and LaserPointers from default scripts

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR has the salvageable parts of derelict PR-12517.

(1) Fix some bugs discovered in `controllerDispatcher.js`
(2) Replace `RayPick` API in `grab.js` with `Pick`.
(3) Remove mentions of `LaserPointers` and `RayPick` from various JS scripts that don't use them.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7621/app_12531_PR.apk

**Comment by AndrewMeadows** [comment]
**Test Plan:**

**(1)** Make sure grab.js still works (it relies on Picks and Pointers script API's):
**(1a)** Can you select objects?
**(1b)** Can you grab objects and move them around?

(2) Make sure teleport.js script still works (also relies on Picks and Pointers):

(3) There were two small bugs fixed in an unused aspect of the controllerDispatcher.js.  To test the fixes you need to:

(3a) Download the script below and run it from file (it will create a sphere in front of avatar).
(3b) Switch to HMD and use the controllers triggers to "pick" the sphere: it should turn a random color on each pick.  The picking we're testing doesn't currently work with mouse in desktop mode.   This is a bug in the JS and outside the scope of this PR.
(3c) Press `i` key to insert the sphere into the pick blacklist:
--> when using this PR the sphere can no longer be "picked" because it has been added to the pick script's blacklist of entities to ignore: it won't change color
--> when using hifi/master the sphere can still be "picked" to randomize its color (this is a bug)
(3d) Press `r` key to remove sphere from pick blacklist
--> sphere can be "picked" again

```
// testPickBlacklist

var entity = null;

function createEntity() {
    var OFFSET = 1.5;
    var position = Vec3.sum(MyAvatar.position, Vec3.multiply(OFFSET, Quat.getFront(MyAvatar.orientation)));
    var properties = {
        name: "blackListEntity",
        type: "Sphere",
        position: position,
        dimensions: {x: 1, y: 1, z: 1}
    };
    if (!entity) {
        entity = Entities.addEntity(properties);
    }
}

function sendMessage(action) {
    print("message = '" + action + "'");
    var message = { action: action, id: entity };
    Messages.sendLocalMessage("Hifi-Hand-RayPick-Blacklist", JSON.stringify(message));
}

function random255() {
    return Math.floor((Math.random() * 255.9999));
}

function setRandomColor() {
    if (entity) {
        var color = { red: random255(), green: random255(), blue: random255() };
        var properties = { color: color };
        Entities.editEntity(entity, properties);
    }
}

function cleanup() {
    Entities.deleteEntity(entity);
    entity = null;
}

Entities.mousePressOnEntity.connect(function(id, event) {
    if (id === entity) {
        setRandomColor();
    }
});

Controller.keyPressEvent.connect(function(event) {
    var KEY_i = 73;
    var KEY_r = 82;
    if (event.key === KEY_i) {
        sendMessage("add");
        print("add entity to blackList " + entity);
    } else if (event.key === KEY_r) {
        sendMessage("remove");
        print("remove entity from blackList " + entity);
    }
});

createEntity();
Script.scriptEnding.connect(cleanup);
```

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7621/HighFidelity-Beta-PR12531-27c6e7915eeb0a54a5a19882a73577cf954db8f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7621/HighFidelity-Beta-PR12531-27c6e7915eeb0a54a5a19882a73577cf954db8f3.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
