### PR TITLE
Minor fix allows import glTF from Substance Painter

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR fixes the glTF importer to support Substance Painter .gltf files.

### CODE REVIEW

**Comment by luiscuenca** [comment]
# TEST
- Go to a domain where you can create.
- Create a new model with url: https://hifi-content.s3.amazonaws.com/luis/gltf/fordish_filter.gltf
- The model and textures should load correctly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9952/HighFidelity-Beta-PR13205-1130f9998d8e6e8b92d8ec709d3ad2e1ba01c159.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9952/HighFidelity-Beta-PR13205-1130f9998d8e6e8b92d8ec709d3ad2e1ba01c159.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9952/HighFidelity-Beta-Interface-PR13205-1130f9998d8e6e8b92d8ec709d3ad2e1ba01c159.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Model looks good on all platforms.

**Comment by Mn8multimedia** [comment]
This is great news. Substance Painter is a necessity nowadays! Thanks

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Model looks good on all platforms.

**Pull request merged**
