### PR TITLE
Case 20526 - update readme

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/20526/Update-nitpick-README-for-Mac
# Description
Updates the readme for Mac.
# Testing
Verify that Mac Installation procedure works as advertised.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16293/HighFidelity-Beta-PR14664-884b775.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16293/HighFidelity-Beta-PR14664-884b775.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16293/HighFidelity-Beta-Interface-PR14664-884b775.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16293/HighFidelity-Beta-PR14664-884b775.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16293/HighFidelity-Beta-Interface-PR14664-884b775.exe

**Comment by jherico** [comment]
including the version number in so many lines of text seems like a big hassle for maintenance.  Either we should avoid putting the version name in the installer executable, or we should refer to it in some generic way in the markdown.

**Comment by NissimHadar** [comment]
I agree with you.  Having the version number is useful as it allows multiple versions.  I will modify the readme as you suggested.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16334/HighFidelity-Beta-PR14664-e9c6d40.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16334/HighFidelity-Beta-PR14664-e9c6d40.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16334/HighFidelity-Beta-Interface-PR14664-e9c6d40.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16334/HighFidelity-Beta-PR14664-e9c6d40.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16334/HighFidelity-Beta-Interface-PR14664-e9c6d40.exe

**Comment by qaAdamSmith82** [comment]
Deprecated by https://github.com/highfidelity/hifi/pull/14783

**Pull request merged**
