### PR TITLE
Case 20972: Fix SendAsset.qml has wrong color

### PR DESCRIPTION
**Pull request by danteruiz**
Fix SendAsset.qml has wrong color

Ticket https://highfidelity.manuscript.com/f/cases/20908/SendAsset-qml-has-incorrect-background-color-after-PR14805

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan in this PR https://github.com/highfidelity/hifi/pull/14842

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16988/HighFidelity-Beta-PR14841-ab6048e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16988/HighFidelity-Beta-PR14841-ab6048e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16988/HighFidelity-Beta-Interface-PR14841-ab6048e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16988/HighFidelity-Beta-PR14841-ab6048e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16988/HighFidelity-Beta-Interface-PR14841-ab6048e.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
