### PR TITLE
send domain metadata to metaverse for authed domains

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

- Run a server from this PR
- Open the server settings page
- Authenticate the server with HiFi
- Make some changes to the Description section
- Save and restart the server
- Copy the Domain ID
- Navigate to https://metaverse.highfidelity.io/api/v1/domains/<DOMAIN_ID>
- Ensure your changes have propagated to the server

**Comment by zzmp** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fOZgidG8&#x2F;6-hit-metaverse-routes-from-domain-on-metadata-changes"> Hit metaverse routes from domain on metadata changes</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1ce9e96cba6427ed98d8ff0235004752fe56a43b available at: https://gist.github.com/914446de9a537a12461d4e424bc45d46<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8087.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8087.dmg

**Comment by OmegaHeron** [comment]
Testing Ubuntu 16.04 QT5.6.0 Docker Containerized

Current RC returns (formatting for easy read)
`{`
`"status":"success",`
`"domain":{"id":"26985503-e1bb-4e13-8510-ed00d5b0fbf9",`
`"ice_server_address":"54.183.200.59",`
`"online":false,`
`"owner_places":[{"name":"o2tech","path":"/1100.6,460.15,-69.367/0.0,0.1,0.0,1.0"}],`
`"description":null,`
`"capacity":0,`
`"restriction":"open",`
`"maturity":"unrated",`
`"hosts":null,`
`"tags":[],`
`"online_users":0,`
`"online_anonymous_users":0}`
`}`

This PR
`{`
`"status":"success",`
`"domain":{"id":"26985503-e1bb-4e13-8510-ed00d5b0fbf9",`
`"ice_server_address":"54.67.32.94",`
`"online":false,`
`"owner_places":[{"name":"o2tech","path":"/1100.6,460.15,-69.367/0.0,0.1,0.0,1.0"}],`
`"description":null,`
`"capacity":0,`
`"restriction":"acl",`
`"maturity":"adult",`
`"hosts":null,`
`"tags":["research"],`
`"online_users":0,`
`"online_anonymous_users":0}`
`}`

Of note - this PR gets ACL correct, not sure about "online" as it **is** online - description is not being passed.  See screen cap for what my settings appear as in DS.

ds-descrip

Not giving this pass or fail as I'm leaning toward fail, but, wish to be clear I'm failing for valid reason.  Also note there is no way to add hosts in settings - this wasn't like this when I did testing for metadata addition a few days ago.

**Comment by zzmp** [comment]
Thanks, @OmegaHeron! I'll go back to it and see why description is not going through.

**Comment by zzmp** [comment]
@OmegaHeron the problem was on the website changes that I'd made to collect this data, not in the domain-server's sending of data. I'm fixing that now, and will then set this back to QA Ready.

**Comment by zzmp** [comment]
@OmegaHeron I noticed that tags/hosts stopped working as well, not sure why, but I'll fix those in a separate PR.

**Comment by OmegaHeron** [comment]
Re-test Server on Ubuntu Linux 16.04/QT5.6.0
It's picking up description and tags now (can't test hosts until I 1) can manage hosts from web UI or 2) peek at my domain config json for other domain that has a host defined).
Restriction is **incorrect**.  It only allows 2 users by name - anonymous, logged in and localhost are **denied**.  In previous build it showed restriction as ACL.

`{`
`"status":"success",`
`"domain":{"id":"26985503-e1bb-4e13-8510-ed00d5b0fbf9",`
`"ice_server_address":"54.67.73.185",`
`"online":false,`
`"owner_places":[{"name":"o2tech","path":"/1100.6,460.15,-69.367/0.0,0.1,0.0,1.0"}],`
`"description":"O2T Internal LAN Server",`
`"capacity":0,`
`"restriction":"open",`
`"maturity":"adult",`
`"hosts":null,`
`"tags":["research"],`
`"online_users":0,`
`"online_anonymous_users":0}`
`}`

**Comment by OmegaHeron** [comment]
Using config from other domain where I had defined a host for syntax clue - I added a host to config for o2t and it does display in metadata output.  Only issue I see is in restriction field.  Compared to previous test it is now incorrect (indicates open vs ACL).

**Comment by zzmp** [comment]
Host, Tags, and Restriction are all broken because of other development. I'll need to make separate PRs to fix those. My goal here (I'll be more explicit in the future) was just to make sure the stored domain metadata was sent from the domain-server to the web-server, and stored by the web-server. That looks to be working from the QA.

**Comment by OmegaHeron** [comment]
Fair enough - I have no objections to adding QA Pass under @zzmp criteria for pass.

**Pull request merged**
