### PR TITLE
remove open hours and timezone from domain settings

### PR DESCRIPTION
**Pull request by birarda**
- remove open hours from domain server metadata

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Test changes to other domain server metadata and ensure that they persist in your local domain settings and propagate to the metaverse API. You should be able to confirm that the metadata is updated via the API by looking at the place page for a place pointing at that domain (ex: https://highfidelity.com/places/sport).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4bbd823a5a2831ea01246e3c646cb4b22b534b0c available at: https://gist.github.com/69dd84ab47c82b0dc4022bf28d396a24<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9616-4bbd823.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9616-4bbd823.dmg

**Comment by OmegaHeron** [comment]
Tested Win 10/Ubuntu 16
QA Pass

Fields for operating hours and time zone no longer present.
Changing other data fields show change via web places display.
I assume the operating hours will be removed from /place/_name_ display at a later time/not part of this PR.

**Comment by birarda** [comment]
@OmegaHeron correct, doing that now.

**Pull request merged**
