### PR TITLE
DNM Prototype: Add first-person controls to edit camera, and update keybindings

### PR DESCRIPTION
**Pull request by huffman**
This is a prototype. No milestone, DNM.

Changes:

W: move forward
A: strafe left
S: move backward
D: strafe right
E: move up
C: move down
space: move up
left: orbit left
right: orbit right
down: orbit down
up: orbit up
right-click + drag: mouse look
right-click + alt + drag: orbit
left-click + alt + drag: orbit
middle-click + drag: pan

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18885/HighFidelity-Beta-PR15440-45e4fc6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18885/HighFidelity-Quest-Beta-PR15440-45e4fc6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18885/HighFidelity-Beta-PR15440-45e4fc6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18885/HighFidelity-Beta-Interface-PR15440-45e4fc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18885/HighFidelity-Beta-PR15440-45e4fc6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18885/HighFidelity-Beta-Interface-PR15440-45e4fc6.exe

**Comment by huffman** [comment]
Closing due to DNM

**Pull request closed without merging**
