### PR TITLE
Remove unused "anchor" Overlays property

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Check that the tablet still works:
- UI displays and can be used.
- Create app's UI still displays and works.
- Rotation degrees still displays when you use a rotation grab handle.

Check that the "Shapes" app still works:
- The UI is attached to the hand.
- The UI looks the same (has the same layout) as displayed using previous, non-PR builds.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6240/app_12155_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6240/HighFidelity-Beta-PR12155-5dca387055efb3350dee2b0549698e19eb457a19.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6240/HighFidelity-Beta-PR12155-5dca387055efb3350dee2b0549698e19eb457a19.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Check that the tablet still works:
UI displays and can be used. **Check**
Create app's UI still displays and works. **Check**
Rotation degrees still displays when you use a rotation grab handle. **Check, but does not actually work for rotating**

Check that the "Shapes" app still works:
The UI is attached to the hand. **Check**
The UI looks the same (has the same layout) as displayed using previous, non-PR builds. **Check**


I'd have to say **Fail** on this unless this is strictly about UI itself working, but the handlers and rotation grabbers for objects do not seem to work in this build. Unsure as to why, but I was unable to pull on grabbers to manipulate create objects as usual. @conklin94122

**Comment by ctrlaltdavid** [comment]
@YuppyPlays I downloaded and tested the PR build and could successfully use the Create app's rotation grab handles to rotate a cube in both desktop and HMD modes. I also tested build 7685 and it looked and worked the same. ... Can you reproduce the problem you encountered? In this PR and current dev build? Are there any JavaScript errors in the program log when you reproduce it?

Note: in HMD mode the red laser goes into the distance beyond the rotate grab handle but rotation still works. (Red laser going beyond the grab handle isn't very nice. I've opened a FogBugz case about this.)

**Comment by YuppyPlays** [comment]
@ctrlaltdavid  Will try again now and will gather my logs into a zip just in-case.

Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Okay, strangely all the issues I experienced before are no longer present, I'm unsure why this randomly occurred and now is now, please see my logs from what I think are both sessions if they help shed any light.

Given the fact it's now working properly for me also, I'd give this a **Pass** though I would like to know why it did not function the first time around. Lasers were not going behind the handlers, it just would not actually 'pull' or affect the object in any way first time around. @conklin94122 

[Logs.zip](https://github.com/highfidelity/hifi/files/1630339/Logs.zip)

**Comment by conklin94122** [comment]
@ctrlaltdavid I'm giving this a QA Approved for now, please let me know if the logs find any issues that you need to address.

**Comment by ctrlaltdavid** [comment]
@conklin94122 There is a JavaScript crash in one of the log files, unrelated to this PR. I've entered a but report in FogBugz as case 11411.

**Pull request merged**
