### PR TITLE
refresh connection info for place/domain while not connected

### PR DESCRIPTION
**Pull request by birarda**
- fixes a bug where Interface would fail to connect to a domain if the server changed ICE servers after Interface had already failed to connect to it

### CODE REVIEW

**Comment by birarda** [comment]
Testing notes:

The following should fail on master/latest RC but will behave correctly on this PR. You will need a domain with a place name (temporary or otherwise) that uses full automatic networking. A default install of the Sandbox has that setup.

1. Make sure the domain-server/Sandbox is not running.
2. Start your Interface client and attempt to connect to your domain via the place name. 
3. You will, as expected, not be connected.
4. Start your domain-server/Sandbox.
5. You will likely not connect to the domain-server/Sandbox without manually re-entering the place name in the address bar. If you do connect, you got lucky to have your domain-server/Sandbox re-use the same ice-server it was previously using. Repeat the steps again and it should fail.

On this PR, you should connect (after the Interface re-queries the API and hits the correct ICE server) to your domain-server/Sandbox even though it is started after Interface.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a81798fd24b7174c30e6f6978505d11239314df available at: https://gist.github.com/0c490b1e7f8de4e5aa770f89bf75d254<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a81798fd24b7174c30e6f6978505d11239314df available at: https://gist.github.com/0c490b1e7f8de4e5aa770f89bf75d254<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.dmg

**Comment by birarda** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a81798fd24b7174c30e6f6978505d11239314df available at: https://gist.github.com/0c490b1e7f8de4e5aa770f89bf75d254<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.dmg

**Comment by murillodigital** [comment]
Last status is a real failure, on OS X:
[WARNINGS] Plug-in Result: Failed - <a href="warningsResult">6 warnings</a> exceed the threshold of 1 by 5

**Comment by hifi-gustavo** [comment]
Build console output for commit: d3304ee65c52dd589cc04ed194768e17f30650df available at: https://gist.github.com/0c490b1e7f8de4e5aa770f89bf75d254<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7943.dmg

**Comment by Nex-Pro** [comment]
## QA Test PR#7943
**QA Tester**: Piper.Peppercorn

Only tested for the requirement: **PASS**

**Connected rapidly 10/10 as per testing notes.**

note: In my case build 4904 would also connect

**Comment by ZappoMan** [comment]
This PR appears to have introduced a bug that is causing RC-12 to Fail QA. Namely, when a client is rejected from a server on connect (for example, because the logged in user is not on the whitelist) this PR causes the client to get into an infinite spamming fit...

**Comment by birarda** [comment]
@ZappoMan the bug there is likely then that we are also spamming the DS with check-ins (since that's where the re-lookup is triggered from).

Feel free to omit this from that RC via a revert unless somebody can:

(a) Fix the possible bug that is causing domain check ins to fire at too high a rate
(b) Limit the re-lookup to once every X ms

**Pull request merged**
