### PR TITLE
Log snapshot upload and user story creation errors

### PR DESCRIPTION
**Pull request by davidkelly**
Plus, if the body of the error is empty, put something in there so the script will not think it was successful.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3105299670547152d864309b0e2427658a72e0c7 available at: https://gist.github.com/85084b83bdf3c6d3425ddc6683724978<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9031-3105299.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9031-3105299.dmg

**Comment by howard-stearns** [comment]
Any reason not to check - and print if not empty - the reply.errorString()?
When we do log, any reason not to log the _filename and _inWorldLocation?

**Comment by davidkelly** [comment]
I'm already printing the reply.errorString() in the failure methods.  IIRC I didn't bother with the _filename as it is printed in `snapshot.js`, but yea maybe printing both here is a good thing.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1766ebab2c9374457b5f89a644fe23c36e6cf31e available at: https://gist.github.com/85084b83bdf3c6d3425ddc6683724978<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9031-1766eba.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9031-1766eba.dmg

**Comment by davidkelly** [comment]
# Test Plan

Given we could not reproduce this, my approach was to make the one possible issue (a failure with empty body) no longer create the problem.  So testing should be just to smoke test the snapshot feature -- take snapshots in a shareable location (like welcome, etc...), when you are logged in, and make sure they show up consistently.

**Pull request merged**
