### PR TITLE
revert HMAC packet verification for now

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Run the Sandbox from this PR and connect to it with Interface. 
Connect to the Sandbox and confirm that you successfully retrieve all assets from ATP. 
Open the expanded stats (press slash and click on the on-screen stats to toggle the expanded version). 
Spin around and confirm that eventually there are no more downloads listed in the expanded stats.
Confirm that you can open the Asset Browser (from the Edit Menu).

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9094/app_12981_PR_1ce1b245d94e684c2dcb492aa06d4e60faaf0518.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9094/HighFidelity-Beta-PR12981-1ce1b245d94e684c2dcb492aa06d4e60faaf0518.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9094/HighFidelity-Beta-Interface-PR12981-1ce1b245d94e684c2dcb492aa06d4e60faaf0518.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9094/HighFidelity-Beta-PR12981-1ce1b245d94e684c2dcb492aa06d4e60faaf0518.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9094/HighFidelity-Beta-Interface-PR12981-1ce1b245d94e684c2dcb492aa06d4e60faaf0518.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Able to connect to domain, but when connected there are no entities and opening the asset browser results in an "Unable to communicate with Asset Server" appearing every second.
Video and Logs:
[Files.zip](https://github.com/highfidelity/hifi/files/1944227/Files.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9111/app_12981_PR_63491588cbbe5d3eece780ad444e196db8c76fc0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9111/HighFidelity-Beta-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9111/HighFidelity-Beta-Interface-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9127/app_12981_PR_63491588cbbe5d3eece780ad444e196db8c76fc0.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9127/HighFidelity-Beta-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9127/HighFidelity-Beta-Interface-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9127/HighFidelity-Beta-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9127/HighFidelity-Beta-Interface-PR12981-63491588cbbe5d3eece780ad444e196db8c76fc0.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Asset browser now works as expected and sandbox loads promptly.

**Pull request merged**
