### PR TITLE
change default add to world shape for asset browser

### PR DESCRIPTION
**Pull request by misslivirose**
Default should not be to have exact collisions - can cause performance issues for high-poly models by accident.

### CODE REVIEW

**Comment by misslivirose** [comment]
Unable to test in HMD mode on master due to a different bug present outside of this PR - will investigate tomorrow

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7341/app_12449_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7341/HighFidelity-Beta-PR12449-5cd184ddc3d5403eca4bea7a70f830c2f7ef381e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7341/HighFidelity-Beta-PR12449-5cd184ddc3d5403eca4bea7a70f830c2f7ef381e.exe

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7422/app_12449_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7422/HighFidelity-Beta-PR12449-5cd184ddc3d5403eca4bea7a70f830c2f7ef381e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7422/HighFidelity-Beta-PR12449-5cd184ddc3d5403eca4bea7a70f830c2f7ef381e.dmg

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass.
Default for Asset Browser is now "Good - Sub-Meshes"
@conklin94122

**Pull request merged**
