### PR TITLE
Android - Double Click crash and dev-mobile crash with Pixel XL

### PR DESCRIPTION
**Pull request by Cristo86**
- Fix for double clicking on a domain crash.
- Only add RenderShadowTask if isDeferred. This prevents a crash that happens with dev-mobile contents in some devices (like Pixel XL). Other devices doesn't show this problem.

Test plan:
- On Android, double tap on a domain.  You shouldn't crash.
- Go to dev-mobile with various phones (including a Pixel XL if possible).  You shouldn't crash when the skybox loads.
- Shadows should work properly on desktop.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10370/HighFidelity-Beta-PR13309-b38eae3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10370/HighFidelity-Beta-PR13309-b38eae3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10370/HighFidelity-Beta-Interface-PR13309-b38eae3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10370/HighFidelity-Beta-PR13309-b38eae3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10370/HighFidelity-Beta-Interface-PR13309-b38eae3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10472/HighFidelity-Beta-PR13309-b38eae3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10472/HighFidelity-Beta-PR13309-b38eae3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10472/HighFidelity-Beta-Interface-PR13309-b38eae3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10472/HighFidelity-Beta-PR13309-b38eae3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10472/HighFidelity-Beta-Interface-PR13309-b38eae3.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No crashes.

**Pull request merged**
