### PR TITLE
Fix deleted action not being sent over the network correctly

### PR DESCRIPTION
**Pull request by druiz17**
From this PR- https://github.com/highfidelity/hifi/pull/11915
serializeActions function was begin called before we deleted the action, which caused the edit packet of an dynamic entity still have the action.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5834/app_12061_PR.apk

**Comment by druiz17** [comment]
Test plan
- perform the same test described in the PR linked above
- with two or more people
- taking turns grab and throw a dynamic object
- other people should not see the object flicker, they should show the object move smoothly in the air.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5834/HighFidelity-Beta-PR12061-fe61d7efc75854b09d5eee3ffd0107abb52f29e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5834/HighFidelity-Beta-PR12061-fe61d7efc75854b09d5eee3ffd0107abb52f29e1.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Tested with test plans from 12055 and 12061. Passed.

**Pull request merged**
