### PR TITLE
Tablet Prototype #3&4

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5256/HighFidelity-Beta-PR11900-0e398ccb3724a866afbf763e15250d9cd4818e3e.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5260/HighFidelity-Beta-PR11900-0e398ccb3724a866afbf763e15250d9cd4818e3e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5260/HighFidelity-Beta-PR11900-0e398ccb3724a866afbf763e15250d9cd4818e3e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5299/HighFidelity-Beta-PR11900-3a85c5377dd379dc18f226d14e13a34eb0c638a6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5299/HighFidelity-Beta-PR11900-3a85c5377dd379dc18f226d14e13a34eb0c638a6.dmg

**Comment by PhilipRosedale** [comment]
I felt that the icons and keyboard buttons are substantially improved in this version!  

Bugs:  

When both stylus tips are near surface, only one stylus works.  

Home button is not improved, still hard to activate.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5367/HighFidelity-Beta-PR11900-a2c01b14cf1f4c85cd679465e0a439aacc1980b9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5367/HighFidelity-Beta-PR11900-a2c01b14cf1f4c85cd679465e0a439aacc1980b9.dmg

**Pull request closed without merging**
