### PR TITLE
some more kinect work

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a4d1db1aeb218f4daafb23cd121a35c0161d205d available at: https://gist.github.com/4a4d2ea10d70579d597ec3896c2dbeb1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-a4d1db1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-a4d1db1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ed5219b57cec3076d48c922cc01c48eb31161af available at: https://gist.github.com/4a4d2ea10d70579d597ec3896c2dbeb1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-4ed5219.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-4ed5219.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 047a3b8d71759489621fe9a7dd97f7084b6510fb available at: https://gist.github.com/907dc7f76421bd9602f2104dd13ca1fc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-047a3b8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10059-047a3b8.dmg

**Comment by AndrewMeadows** [comment]
Al and I tested this: it looks good.

**Pull request merged**
