### PR TITLE
Fix edit.js upload button

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e24b66b38905a752b3970e795a03206f921b640 available at: https://gist.github.com/a9af6899c470c809172b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7297.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7297.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e24b66b38905a752b3970e795a03206f921b640 available at: https://gist.github.com/a9af6899c470c809172b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7297.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7297.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Upload works again.  QA Pass

**Pull request merged**
