### PR TITLE
Worklist #21789: Tablet notepad

### PR DESCRIPTION
**Pull request by mnafees**
# Test plan
1. Open interface.exe and open notepad.js
2. Type in the text area in the notepad using the on-screen keyboard
3. Input your GitHub username and password and click on "Save As Gist"
4. Check your own private GitHub Gists to see the newly created gist

### CODE REVIEW

**Comment by mnafees** [comment]
Currently the script loads a webpage that's hosted on my own domain. I'd like to know how to upload it to hifi's servers.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8690/HighFidelity-Beta-PR12856-77f858c9ddf6b6c21fe33751d583a88f3bf022cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8690/HighFidelity-Beta-PR12856-77f858c9ddf6b6c21fe33751d583a88f3bf022cd.exe

**Comment by themelissabrown** [comment]
@mnafees I think these types of things are all being stored as marketplace apps now. I'll message you on skype.

**Pull request closed without merging**
