### PR TITLE
fix lastEdited vs pal

### PR DESCRIPTION
**Pull request by howard-stearns**
Fix https://highfidelity.fogbugz.com/f/cases/3414/lastEdited-vs-pal-and-select-vs-filter

### CODE REVIEW

**Comment by howard-stearns** [comment]
Test plan, with two avatars:
1. With one avatar, edit an entity so that it's been last edited by you. Don't leave the domain yet.
2. With another avatar, open create tool and select the same entity. Don't actually edit it, but in the List View with the entity selected, click the small "user" button in the top row of the List view, between "Export Selection" and "Delete".  It should close the edit tool, unselect the entity, open the People app, and select the other avatar from step 1.
3. Have the avatar from step 1 leave, and repeat step 2. It should still close the edit tool, unselect the entity, and open the People app, but then it should say  "The user you attempted to select is no longer available."

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9687/app_13150_PR_50a53a5174bd3dc2a29131d0e316266c060a5d66.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9687/HighFidelity-Beta-PR13150-50a53a5174bd3dc2a29131d0e316266c060a5d66.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9687/HighFidelity-Beta-Interface-PR13150-50a53a5174bd3dc2a29131d0e316266c060a5d66.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9691/app_13150_PR_bf26aec260fe661b2391d1a92157c80c5c29b6cc.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9687/HighFidelity-Beta-PR13150-50a53a5174bd3dc2a29131d0e316266c060a5d66.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9687/HighFidelity-Beta-Interface-PR13150-50a53a5174bd3dc2a29131d0e316266c060a5d66.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9691/HighFidelity-Beta-PR13150-bf26aec260fe661b2391d1a92157c80c5c29b6cc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9691/HighFidelity-Beta-Interface-PR13150-bf26aec260fe661b2391d1a92157c80c5c29b6cc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9691/HighFidelity-Beta-PR13150-bf26aec260fe661b2391d1a92157c80c5c29b6cc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9691/HighFidelity-Beta-Interface-PR13150-bf26aec260fe661b2391d1a92157c80c5c29b6cc.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
User button works when avatar is available and when they are not available as expected.

**Pull request merged**
