### PR TITLE
Push To Talk Bugs 1207/1208

### PR DESCRIPTION
**Pull request by RebeccaStankus**
https://highfidelity.atlassian.net/browse/BUGZ-1207
https://highfidelity.atlassian.net/browse/BUGZ-1208

I added a check when unmuting to also turn off PTT if necessary.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21005/HighFidelity-Beta-PR16089-6e96b80.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21005/HighFidelity-Quest-Beta-PR16089-6e96b80.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21005/HighFidelity-Beta-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21005/HighFidelity-Beta-Interface-PR16089-6e96b80.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21007/HighFidelity-Beta-PR16089-6e96b80.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21007/HighFidelity-Quest-Beta-PR16089-6e96b80.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21007/HighFidelity-Beta-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21007/HighFidelity-Beta-Interface-PR16089-6e96b80.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21013/HighFidelity-Beta-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21013/HighFidelity-Beta-Interface-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21013/HighFidelity-Beta-PR16089-6e96b80.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21013/HighFidelity-Quest-Beta-PR16089-6e96b80.apk)

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21020/HighFidelity-Beta-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21020/HighFidelity-Beta-Interface-PR16089-6e96b80.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21020/HighFidelity-Beta-PR16089-6e96b80.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21020/HighFidelity-Beta-Interface-PR16089-6e96b80.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21020/HighFidelity-Beta-PR16089-6e96b80.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21020/HighFidelity-Quest-Beta-PR16089-6e96b80.apk)

**Pull request merged**
