### PR TITLE
Make desktop left and right mouse button actions independent

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Desktop mode. Domain without a skybox. Rez rights.

Use the Create app to rez a cube. Close the  Create app.

Summary:
- The left mouse button should translate or (with the Ctrl key) rotate the cube.
- The right mouse button should rotate the view.
- These should occur independently of each other.

In particular: In tests 3a and 3b, the cube should not keep translating with the mouse when both buttons are released.

1) Test left mouse button.
a) Sky
- Click and hold the left mouse button while the cursor is in the sky.
- Move the mouse. Nothing should happen.
- Release the mouse button(s).
b) Cube
- Click and hold the left mouse button while the cursor is on the cube.
- Move the mouse. The cube should move in the x-z plane.
- Release the mouse button(s).
c) Cube + Ctrl
- Click and hold the left mouse button while the cursor is on the cube.
- Press and hold the Ctrl key.
- Move the mouse. The cube should rotate about the world y-axis through its centre.
- Release the mouse button(s).

2) Test right mouse button.
a) Sky
- Click and hold the right mouse button while the cursor is in the sky.
- Move the mouse. The view should rotate per the mouse movement.
- Release the mouse button(s).
b) Cube
- Click and hold the right mouse button while the cursor is on the cube.
- Move the mouse. The view should rotate per the mouse movement. But the cube should not move.
- Release the mouse button(s).

3) Test left mouse button then right mouse button.
a) Sky
- Click and hold the left mouse button while the cursor is in the sky.
- Click and hold the right mouse button also.
- Move the mouse. The view should rotate per the mouse movement.
- Release the left mouse button but keep the right mouse button held.
- Move the mouse. The view should rotate per the mouse movement.
- Release the mouse button(s).
- Move the mouse. Nothing should happen.
- Repeat but release the right mouse button first.
- Nothing should happen while you move your mouse with the left mouse button held down.
- Release the mouse button(s).
- Move the mouse. Nothing should happen.
b) Cube
- Click and hold the left mouse button while the cursor is on the cube.
- Click and hold the right mouse button also.
- Move the mouse. The view should rotate and the cube should move in the x-z plane per the mouse movement.
- Release the left mouse button but keep the right mouse button held.
- Move the mouse. The view should rotate per the mouse movement. But the cube should no longer move.
- Release the mouse button(s).
- Move the mouse. Nothing should happen.
- Repeat but release the right mouse button first.
- Move the mouse. The cube should move in the x-z plane while you move your mouse.
- Release the mouse button(s).
- Move the mouse. Nothing should happen.
c) Cube + Ctrl
- Repeat b) with the Ctrl key pressed and held.
- The cube should rotation instead of translateing in the x-z plane.

4) Test right mouse button then left mouse button.
a) Sky
- Repeat 3a, except click and hold the right mouse button before the left mouse button. The same results should occur.
b) Cube
- Repeat 3b, except click and hold the right mouse button before the left mouse button. The same results should occur.
c) Cube + Ctrl
- Repeat 3c, except click and hold the right mouse button before the left mouse button. The same results should occur.

5) Standard tests, if any.
- Check the standard test plans for any relevant tests to perform.

https://highfidelity.manuscript.com/f/cases/15407

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10653/HighFidelity-Beta-PR13402-ffd66f4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10653/HighFidelity-Beta-PR13402-ffd66f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10653/HighFidelity-Beta-Interface-PR13402-ffd66f4.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10926/HighFidelity-Beta-PR13402-ffd66f4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10926/HighFidelity-Beta-PR13402-ffd66f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10926/HighFidelity-Beta-Interface-PR13402-ffd66f4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10926/HighFidelity-Beta-PR13402-ffd66f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10926/HighFidelity-Beta-Interface-PR13402-ffd66f4.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Mouse works great

**Pull request merged**
