### PR TITLE
possible fix for tablet freezing (#11971 for rc-61)

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5645/HighFidelity-Beta-PR11990-9863458fef38ca0243c6d7945e16ba7a1192d6c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5645/HighFidelity-Beta-PR11990-9863458fef38ca0243c6d7945e16ba7a1192d6c5.exe

**Comment by tapalisa** [comment]
Test plan:

Start in Sandbox in HMD
Make sure you can use your tablet

**Comment by Nex-Pro** [comment]
Testing Win10 and Vive.

**Comment by Nex-Pro** [comment]
### PASS

Tablet interactions are very good. 
Tested in HMD with lasers, stylii and finger.
Using while grabbed. Using while walking/driving and flying. 
Also tested desktop tablet. Flicking in market works in both desktop and HMD.

Good work @sethalves  Thanks.

**Pull request merged**
