### PR TITLE
use smart pointers for entity simulations

### PR DESCRIPTION
**Pull request by sethalves**
- use smart pointers to keep track of entity simulations

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- smoke test

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0771f8ee511c3f2ae0cb2d8a8ba03d1d34e32e6 available at: https://gist.github.com/99e439357d5435124288f88562f132e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7839.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7839.dmg

**Comment by OmegaHeron** [comment]
QA Fail

Windows 10 64 bit - i5 CPU - GTX970 GPU - after repeated visits to Playa I never see sky render - At forum I see skybox sky render.  Maybe an issue with procedural sky at playa?

**Comment by OmegaHeron** [comment]
Suggest additional testers.  Out of 8 attempts I failed to see sky at playa 2 times - but, I suspect it's a network issue on my end.  Better safe than sorry though.

**Comment by OmegaHeron** [comment]
All of my weirdness with skybox procedural shader not loading has nothing to do with this PR (as I thought) - Was East Coast network congestion due to a bundle of backbone fiber-optic cables being cut 800+ miles away.

Tested Windows 10 64 bit - i5 6500 CPU - GTX970 GPU **Desktop mode - keyboard/mouse**
All standard tests pass - no change to baseline CPU/GPU/RAM stats seen.  If there are any specific tests beyond the standard set, please advise.  Otherwise... QA Pass

**Comment by hifi-gustavo** [comment]
Build console output for commit: b761ecf44fec3da2570d11ea7786bbcd54334626 available at: https://gist.github.com/99e439357d5435124288f88562f132e8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7839.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7839.dmg

**Pull request merged**
