### PR TITLE
Set admin status even if QML can't find user in PAL

### PR DESCRIPTION
**Pull request by zfox23**
Related to #10903. I think that PR was good code, but I don't think it completed the fix.

This PR _ensures_ that `iAmAdmin` in the PAL QML is set to `true` iff the user is an admin when the nearbyUsers list is refreshed (i.e. when the PAL is opened).

I'm realizing now that something else fishy might be going on when a user isn't seeing the ADMIN column when they know they're an admin...I don't know what might cause that, but this should be another step in the right direction to prevent it from happening.

Same test plan as before:
1. Visit a domain where you're an Admin. Open the PAL. Verify that you see the Admin column.
2. Attempt some daft trickery, like opening the PAL as soon as you get to a domain where you're an admin. Verify that you can't break the visibility of the Admin column in the PAL when you're an Admin.
3. Visit a domain where you're not an Admin, Verify that you _can't_ see the Admin column.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1437/HighFidelity-Beta-PR10911-ee9cdaff901f40f596c423158a113bfd23fdd624.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1437/HighFidelity-Beta-PR10911-ee9cdaff901f40f596c423158a113bfd23fdd624.dmg

**Comment by CainFoool** [comment]
Testing shortly.

**Comment by CainFoool** [comment]
# Test Failed
Test | Result
-------- | --------
Visit a domain where you're an Admin. Open the PAL. Verify that you see the Admin column. | Pass
Attempt some daft trickery, like opening the PAL as soon as you get to a domain where you're an admin. | Pass
Verify that you can't break the visibility of the Admin column in the PAL when you're an Admin. | Pass
Visit a domain where you're not an Admin, Verify that you can't see the Admin column. | Fail

When switching between domains where I am and aren't admin, the admin column stays however retains no information until either closing out of PAL or switching between the Nearby and Connections tab.

**Replication Steps**:

- Go to your localhost
- Open your PAL 
- Open your Nearby Tab
- Join a friend's domain
- Quickly switch to the Connections tab
- See that the admin panel is still there.


interface_2017-07-07_09-21-44

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by zfox23** [comment]
@CainFoool - as we discussed in Slack, the behavior you mention has been present since we released the PAL. However, you have uncovered a bug that should be fixed here: the PAL is supposed to close when changing domains. I'll fix that momentarily.

**Comment by CainFoool** [comment]
Cool - will be happy to have another go when ready :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1445/HighFidelity-Beta-PR10911-ea77557e387500c6342077d6344f05cbe9a3d678.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1445/HighFidelity-Beta-PR10911-ea77557e387500c6342077d6344f05cbe9a3d678.exe

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Visit a domain where you're an Admin. Open the PAL. Verify that you see the Admin column. | Pass
Attempt some daft trickery, like opening the PAL as soon as you get to a domain where you're an admin. | Pass
Verify that you can't break the visibility of the Admin column in the PAL when you're an Admin. | Pass
Visit a domain where you're not an Admin, Verify that you can't see the Admin column. | Pass

Working beautifully.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
