### PR TITLE
Plant that blooms flowers when it is watered by a water can

### PR DESCRIPTION
**Pull request by ericrius1**

### CODE REVIEW

**Comment by ericrius1** [comment]
https://app.asana.com/0/31759584831097/82864779674833

1) Run https://rawgit.com/ericrius1/hifi/growingPlant/examples/homeContent/plant/growingPlantSpawner.js

2) Pick up the water can with your vive or hydras

3) Tilt the can like you are going to pour water out of it, and direct the water that comes out over the potted plant

4) You should see the flowers start to grow on the plant, and hear the sounds of water pouring and flowers blooming

**Comment by hifi-gustavo** [comment]
Build console output for commit: d4bc83f408c1f3fa4095501e070ca0fc73010f9e available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by imgntn** [comment]
@ericrius1 we're accidentally splitting the home content.  you've got whiteboard in /examples/homecontent, and tiltmaze is already in /unpublishedScripts/DomainContent/Home (that's where fishtank is supposed to go to).  i guess it doesn't really matter which one we pick, but they should all go in the same place.  whoever has to move may need to update relative paths.  not sure if @RyanDowne has a preference

**Comment by RyanDowne** [comment]
Please put things in DomainContent/Home

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7b69aa375e94587767e319b5b4b5e9a1eedc7ec6 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by RyanDowne** [comment]
This works cool! I am guessing you have control over the colors of the flowers? I think there is an aesthetic disconnect between the model and the flower shaders. Maybe Alan can help give you color values that tie the two together more?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 41782dbd8dde437c8243cc15b0ea916f00a1679a available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c928b9e4114d8687d3f17468850bebcfbb40d333 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c928b9e4114d8687d3f17468850bebcfbb40d333 available at: https://gist.github.com/a93f7eead21139f949ac<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17454fdb01caa24e68cb38b1a660a11a9c493895 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a236fceeadd0e668d2db967a4fcaa70122c4e7b4 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d1217e02d4705d8e16e7a3b53f8adee048a04c0 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Comment by cozza13** [comment]
I have tested this and it is great. Nice touch with the lifetime

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d1217e02d4705d8e16e7a3b53f8adee048a04c0 available at: https://gist.github.com/220a645028d2f5f4c737<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7267.dmg

**Pull request merged**
