### PR TITLE
Fix polyvox buffer size

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug in polyvox rendering that could cause a GL related crash

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- visit hifi://eschatology/105.055,1.44689,158.861/0,0.712544,0,0.701628
- log out and in a few times
- make sure you don't crash more than normal

**Comment by hifi-gustavo** [comment]
Build console output for commit: 028be0f83095b1cfe8a28126f367fdb8e0917ebd available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-028be0f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-028be0f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8530156227d675daeaf3e8a80f100ff8f4044a61 available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-8530156.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-8530156.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1714d4fe069d285337df7e749a7ce0b1e1be317c available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-1714d4f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-1714d4f.dmg

**Comment by OmegaHeron** [comment]
QA Fail
Using last RC I was able to visit test location repeatedly with no issue.  Using this PR I crashed immediately at test location.  Bugsplats sent.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a66a1d392eca54e0ec3fdfe0e45ac707d3896cf9 available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-a66a1d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-a66a1d3.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3278478a60faa8c28080ded01d58f3e3e68fa74b available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-3278478.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-3278478.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2a28147c0180eb01bb52b0bca8e0cbb88c39690 available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-b2a2814.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-b2a2814.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2a28147c0180eb01bb52b0bca8e0cbb88c39690 available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-b2a2814.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-b2a2814.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ee1fac3677a22797db171ec3a232cf25715434e available at: https://gist.github.com/ebf0dc76351ce36ecdf52696127eba16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-8ee1fac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9093-8ee1fac.dmg

**Comment by cozza13** [comment]
I have gone through this on i5.

**Pull request merged**
