### PR TITLE
add basic support for master vs stable builds

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4062571113d7c14f9b8d31b1ecbbfd224eccbbae available at: https://gist.github.com/4d355636a8709aef3ec17ea3f182dce4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-4062571.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-4062571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ebbb469a242f3240cc0ecc6e4de9804ac633cd0 available at: https://gist.github.com/4d355636a8709aef3ec17ea3f182dce4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-3ebbb46.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-3ebbb46.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e919626c885a3d357775bffe78b08aae4d78373 available at: https://gist.github.com/4d355636a8709aef3ec17ea3f182dce4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-8e91962.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-8e91962.dmg

**Comment by ZappoMan** [comment]
Test plan:
- Smoke test. Everything should work properly -- obviously this is from master so it will only work to dev-* domains.
- You will notice the following in your Interface log file (near the top)....
```
[09/19 14:21:42] [DEBUG] [VERSION] Build sequence: PR8620
[09/19 14:21:42] [DEBUG] [VERSION] MODIFIED_ORGANIZATION: "High Fidelity - PR8620"
[09/19 14:21:42] [DEBUG] [VERSION] VERSION: "PR8620"
[09/19 14:21:42] [DEBUG] [VERSION] BUILD_BRANCH: ""
[09/19 14:21:42] [DEBUG] [VERSION] BUILD_GLOBAL_SERVICES: "DEVELOPMENT"
[09/19 14:21:42] [DEBUG] [VERSION] We will use DEVELOPMENT global services.
```

- You will notice the following in your domain-server log file (near the top)....
```
[09/19 14:21:42] [DEBUG] [VERSION] Build sequence: PR8620
[09/19 14:21:42] [DEBUG] [VERSION] MODIFIED_ORGANIZATION: "High Fidelity - PR8620"
[09/19 14:21:42] [DEBUG] [VERSION] VERSION: "PR8620"
[09/19 14:21:42] [DEBUG] [VERSION] BUILD_BRANCH: ""
[09/19 14:21:42] [DEBUG] [VERSION] BUILD_GLOBAL_SERVICES: "DEVELOPMENT"
[09/19 14:21:42] [DEBUG] [VERSION] We will be using this default ICE server: dev-ice.highfidelity.com
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: fd474f63196ff7e3027c72dd0ce664b419693d3f available at: https://gist.github.com/4d355636a8709aef3ec17ea3f182dce4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-fd474f6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8620-fd474f6.dmg

**Comment by OmegaHeron** [comment]
Domain server on Linux build using my normal process for building a PR - will test on Windows once I can get download.

[09/19 21:53:52] [DEBUG] Setting up domain-server
[09/19 21:53:52] [DEBUG] [VERSION] Build sequence: PR8620
[09/19 21:53:52] [DEBUG] [VERSION] MODIFIED_ORGANIZATION: "High Fidelity - PR8620"
[09/19 21:53:52] [DEBUG] [VERSION] VERSION: "PR8620"
[09/19 21:53:52] [DEBUG] [VERSION] BUILD_BRANCH: ""
[09/19 21:53:52] [DEBUG] [VERSION] BUILD_GLOBAL_SERVICES: "DEVELOPMENT"
[09/19 21:53:52] [DEBUG] [VERSION] We will be using this default ICE server: "dev-ice.highfidelity.com"

**Comment by cozza13** [comment]
@OmegaHeron do not worry about windows. I am happy to pull the trigger on this one

**Pull request merged**
