### PR TITLE
Bug fix for sit script.

### PR DESCRIPTION
**Pull request by hyperlogic**
Make MyAvatar.pinJoint() work again as expected for the hips.  This was causing the sit script to not function properly.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6039/app_12101_PR.apk

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/11100/Sit-animation-in-HMD-is-incorrect

**Comment by hyperlogic** [comment]
QA Test plan:
https://highfidelity.testrail.net/index.php?/tests/view/28907

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6039/HighFidelity-Beta-PR12101-243dcb88ee8bfdc59ffaa9f0237e1ae1a8d6234a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6039/HighFidelity-Beta-PR12101-243dcb88ee8bfdc59ffaa9f0237e1ae1a8d6234a.exe

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing complete. PASSED.

**Pull request merged**
