### PR TITLE
Optimize and remove online dependencies for interstitial loading page

### PR DESCRIPTION
**Pull request by FlameSoulis**
This PR focuses on making the loading screen self-contained within the client itself. It doesn't make sense to have a loading screen download additional resources while downloading resources needed for the scene.

In addition, this optimization adds MP3 versions of the loading screen background music to reduce filesizes. Resolving the FBX issue was not approached due to already being a small size. If this PR is accepted, it can be reviewed again to see if the sphere is UV unwrapped for additional functionality.

Some things to note:

 - There were roughly 26 problems resulted by eslint before work commenced in this PR. 23 of them remain and are outside the scope of this PR to be resolved
 - Line 115 repeated ```backgroundAlpha```. This was corrected in a commit.
 - The script is loading the resources via "/~/". If this is not desired, I can resolve this quickly.

PS - I did remember to turn off _javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunction_ in VS Code this time.

Test plan:
Run interstitial test cases in this section on Mac/desk, Win/desk, Win/rift, Win/vive
https://highfidelity.testrail.net/index.php?/suites/view/1357&group_by=cases:section_id&group_order=asc

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14184/HighFidelity-Beta-PR14240-5db7c78.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14184/HighFidelity-Beta-PR14240-5db7c78.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14184/HighFidelity-Beta-Interface-PR14240-5db7c78.dmg

**Comment by FlameSoulis** [comment]
I have tested both desktop and VR, just in case it was any different. Not sure if that helps inspire the test plan at all.

**Comment by JeffClinton** [comment]
Removing QA ready tag since the interstitial PRs are being merged.

**Comment by wayne-chen** [comment]
merged into PR #14249.

**Comment by shanzzam** [comment]
Thanks, @FlameSoulis! See above, this has been merged into a larger PR that contains the full interstitial work. That PR has been merged into our next release, 75.

**Pull request closed without merging**
