### PR TITLE
Restart at last location after crash

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This instead of going to 0,0,0, possibly on wrong domain, as often currently happens

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e07baf916b0f65e53e837046344e5e5d1300135c available at: https://gist.github.com/61901a52301736896c0d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6989.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6989.dmg

**Comment by ctrlaltdavid** [comment]
Note: You can intentionally crash interface using the menu item, Developer > Crash Interface.

**Comment by selart** [comment]
Tested on Windows, always starts at last location.

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
Test PASSED! I am happy because this was an issue with me crashing at the meeting and kept resetting at the Sandbox/0,0,0.

I go to my domain and proper location, do a Developer > Crash, on reload I am right back where I crashed.

**Pull request merged**
