### PR TITLE
Fix handshake mode staying on when release "x" if Ctrl or Shift pressed

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Desktop mode

Before: Press and hold the "x" key, press and hold one or more of the Ctrl and Shift keys, release the "x" key. You stay in handshake mode until you release the Ctrl and Shift keys and press and release the "x" key.

After: You exit handshake mode when you release the "x" key even if one or both of Ctrl and Shift keys are still pressed.

Note: On Windows (at least) if you press and release the Alt key, focus is transferred to the menu items ("File" is highlighted in blue) and the handshake "x" won't work until the menus lose focus (press Esc or press and release the Alt key). This is expected, standard Windows behaviour.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5690/app_12005_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5690/HighFidelity-Beta-PR12005-5e194102939e558c39ea6c7a63d4ffeb3e527a8d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5690/HighFidelity-Beta-PR12005-5e194102939e558c39ea6c7a63d4ffeb3e527a8d.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Desktop mode **Check**

Before: Press and hold the "x" key, press and hold one or more of the Ctrl and Shift keys, release the "x" key. You stay in handshake mode until you release the Ctrl and Shift keys and press and release the "x" key. **Check**

After: You exit handshake mode when you release the "x" key even if one or both of Ctrl and Shift keys are still pressed. **Check**

Solid **Pass**

**Pull request merged**
