### PR TITLE
fix tablet interaction and far grab functionality

### PR DESCRIPTION
**Pull request by druiz17**
This PR fixes some issues introduction to the FarActionGrabEntity module. Also this PR will remove laser intersection with the tablet model, since reports indicate that the lasers are intersecting the tablet model instead of the tablet screen.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6073/app_12104_PR.apk

**Comment by druiz17** [comment]
Test plan
1. Search beams
- press both triggers should result in both lasers being visible
- lease triggers should make the lasers to disappear
- press and release triggers at different rates...make sure that lasers turn on and turn off.

2. Far grab interaction
- While press down on the trigger, move the laser over a grabbable object.
- the laser should lock onto and move the object.

3 Tablet interaction
- Make sure that you can use the lasers to interact with the tablet and keyboard.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6073/HighFidelity-Beta-PR12104-fd83e00df467c90ec3f891ab4c9178f47127c22b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6073/HighFidelity-Beta-PR12104-fd83e00df467c90ec3f891ab4c9178f47127c22b.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
