### PR TITLE
Fix replace content dialog not closing

### PR DESCRIPTION
**Pull request by druiz17**
The function askToReplaceDomainContent uses OffscreenUI::question and warning instead of OffscreenUI::asyncQuestion/Warning, which is the reason of why the modal dialog don't close.

### CODE REVIEW

**Comment by changxc** [comment]
Test plan: 

(1)enable commerce 
a) Add "commerce": true, in your Interface.json (with Interface not running), which is located in %\AppData\Roaming\High Fidelity folder for the particular build you are using
or
b) Open the client's Javascript console (accessible when both the advanced and developer menus are enabled, then Edit > Console), paste "Settings.setValue("commerce", true)" (without the quotes) into the console, press Enter, then restart the client




(2) in your sandbox, choose a content set from environment category, click free (hover over is get), click button get item. click yes on pop-up, the dialog box should disappear, and content set is changed in your sandbox


(3) go to a domain where you do not have permission to swap out content, repeat the above step, the error msg should say 'you do not have permission to replace the content', click ok will dismiss the pop-up

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5113/HighFidelity-Beta-PR11861-c9ad7b1db50fdf109b5c4e2dc832c8927292ff6d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5113/HighFidelity-Beta-PR11861-c9ad7b1db50fdf109b5c4e2dc832c8927292ff6d.dmg

**Comment by Nex-Pro** [comment]
Testing Win 10

**Comment by Nex-Pro** [comment]
### PASS

(1)enable commerce
a) Add "commerce": true, in your Interface.json (with Interface not running), which is located in %\AppData\Roaming\High Fidelity folder for the particular build you are using
or
b) Open the client's Javascript console (accessible when both the advanced and developer menus are enabled, then Edit > Console), paste "Settings.setValue("commerce", true)" (without the quotes) into the console, press Enter, then restart the client



(2) in your sandbox, choose a content set from environment category, click free (hover over is get), click button get item. click yes on pop-up, the dialog box should disappear, and content set is changed in your sandbox **success**

(3) go to a domain where you do not have permission to swap out content, repeat the above step, the error msg should say 'you do not have permission to replace the content', click ok will dismiss the pop-up **SUCCESS**

See attached image.
hifi-snap-by-piper-peppercorn-on-2017-11-21_22-57-18

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5115/HighFidelity-Beta-PR11861-767b0fa4af093a3402ba526ca1fa262504b90d5e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5115/HighFidelity-Beta-PR11861-767b0fa4af093a3402ba526ca1fa262504b90d5e.dmg

**Pull request merged**
