### PR TITLE
workload: stubbed prototype job for feedback to physics

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8529/HighFidelity-Beta-PR12798-bb8b546340bea50ab55fbb56bfb3b349f427544e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8529/HighFidelity-Beta-PR12798-bb8b546340bea50ab55fbb56bfb3b349f427544e.exe

**Comment by AndrewMeadows** [comment]
Something went wrong with this branch.  Closing and will try again.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8535/HighFidelity-Beta-PR12798-4f0980b94b78accaf480abb9888d931a49799cbd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8535/HighFidelity-Beta-PR12798-4f0980b94b78accaf480abb9888d931a49799cbd.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8538/HighFidelity-Beta-PR12798-8035dde5dd9f3abd99e9e92bd772e80f38dade90.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8538/HighFidelity-Beta-PR12798-8035dde5dd9f3abd99e9e92bd772e80f38dade90.dmg

**Pull request merged**
