### PR TITLE
fix ASCII art for packet headers in NLPacket

### PR DESCRIPTION
**Pull request by birarda**
- fixed the ASCII art for packet headers in NLPacket

### CODE REVIEW

**Comment by birarda** [comment]
This unfortunately truly shows how bloated our packet headers are when sourced and verified, something to improve.

**Comment by birarda** [comment]
No testing needed, change to comment in code

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7673/app_12545_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7674/app_12545_PR.apk

**Comment by SimonWalton-HiFi** [comment]
Maybe put the UUID & hash len (16 bytes) in the diagram - it wasn't clear to me whether it was 16 or 20 bytes. Maybe also a byte number as a new column.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7675/app_12545_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7677/app_12545_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7677/HighFidelity-Beta-PR12545-4f151a4237f4655e94fc356bdd054c81798462ab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7677/HighFidelity-Beta-PR12545-4f151a4237f4655e94fc356bdd054c81798462ab.exe

**Pull request merged**
