### PR TITLE
fix -- get children of animated entity joints to follow along, again

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that kept children of animated entity joints from following along

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- visit hifi://eschatology/108.445,1.51988,95.0399/0.00254564,0.55508,0.0126768,0.831697
- confirm that the raygun held by the animated character follows her hand

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7027/app_12366_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7028/app_12366_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7028/HighFidelity-Beta-PR12366-31c2b8fea92c3b01ca9d8b379ee705205a1aebc5.dmg

**Comment by sethalves** [comment]
build this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7032/app_12366_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7032/HighFidelity-Beta-PR12366-31c2b8fea92c3b01ca9d8b379ee705205a1aebc5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7032/HighFidelity-Beta-PR12366-31c2b8fea92c3b01ca9d8b379ee705205a1aebc5.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed for PR#12366. PASSED.

**Pull request merged**
