### PR TITLE
4869 entity resize issue

### PR DESCRIPTION
**Pull request by NeetBhagat**
Fix for Bug case 4869: Entities resize via hand controllers when they're not supposed to
https://highfidelity.fogbugz.com/f/cases/4869

**Oculus Rift HMD / Handcontrollers required**

Resolved 2 bugs in this PR :

Bug 1: 

1. Grab an entity with your left hand using the grip/squeeze trigger
2. Grab a different entity in your right hand using the grip trigger
3. Notice that the entity in your left hand grows/shrinks as you move your right hand.
This bug isn't reproducible when you start with an entity in your right hand.

Expected behavior for Bug 1:
1. Grab an entity with your left hand using the grip trigger
2. Grab a different entity in your right hand using the grip trigger
3. Entity in left hand should not grow/shrink as you move your right hand.

Bug 2:
1. Grab an entity with Right hand using the grip trigger.
2. Grab the same entity with Left hand using the grip trigger, You can not grow/shrink an entity by moving any hand.

Fixed behavior for Bug 2:
1. Grab an entity with Right hand using the grip trigger.
2. Grab same entity with Left hand using the grip trigger, You can now grow/shrink an entity by moving any hand.

Note: Dev tested on Windows 10 + Oculus Rift. Tested on entities of Eschatology and Dev-welcome.

Dev tested performed.

1. Grab an Entity from left Hand, then right hand, move any hand entity should grow/shrink.
2. Grab an Entity from right Hand, then left hand, move any hand entity should grow/shrink.
3. Grab an Entity from left Hand, then grab another entity from the right hand, now move any hand,any entity should not grow/shrink.
4. Grab an Entity from Right Hand, then grab another entity from the left hand, now move any hand,any entity should not grow/shrink.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
Add to whitelist

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/436/HighFidelity-Beta-PR10619-2ce72d554bd34200259ef9d8ed517c28963c92e5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/436/HighFidelity-Beta-PR10619-2ce72d554bd34200259ef9d8ed517c28963c92e5.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift + Touch Controllers

Tested: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/436/HighFidelity-Beta-PR10619-2ce72d554bd34200259ef9d8ed517c28963c92e5.exe

<!DOCTYPE html>
<html>
<body>

<h1>PASS</h1>

</body>
</html>  

- Bug 1 fix: Pass
- Bug 2 fix: Pass
- All below: Pass

 <ol>
  <li>Grab an Entity from left Hand, then right hand, move any hand entity should grow/shrink.</li>
  <li> Grab an Entity from right Hand, then left hand, move any hand entity should grow/shrink.</li>
  <li>Grab an Entity from left Hand, then grab another entity from the right hand, now move any hand,any entity should not grow/shrink.</li>
<li>Grab an Entity from Right Hand, then grab another entity from the left hand, now move any hand,any entity should not grow/shrink.</li>
</ol>

**Pull request merged**
