### PR TITLE
Page indicator visible only when pages more than one

### PR DESCRIPTION
**Pull request by vladest**
Test plan:

- Create > 12 apps. Make sure page indicator is visible
- Remove apps to make them  less or equal 12. Make sure page indicator non visible

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6089/app_12109_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6089/HighFidelity-Beta-PR12109-891663bae95df30f7ea18ea0ffc5c8099e6a47fa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6089/HighFidelity-Beta-PR12109-891663bae95df30f7ea18ea0ffc5c8099e6a47fa.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing complete. PASSED. 
Note: Slack is down for now. Will update it later.

**Pull request merged**
