### PR TITLE
RC65.1 no crash on exit

### PR DESCRIPTION
**Pull request by AndrewMeadows**
- re-order cleanup during shutdown

- disable LogHandler at some point during shutdown

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Whoops, this PR was created against the wrong branch.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8163/app_12687_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8163/HighFidelity-Beta-PR12687-d83da35c43844faec260c99053824474f89bae54.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8163/HighFidelity-Beta-PR12687-d83da35c43844faec260c99053824474f89bae54.exe

**Pull request closed without merging**
