### PR TITLE
(BUGZ-559) Improve transition debugging and transition clean-up

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.atlassian.net/browse/BUGZ-559

This PR adds additional icon colors/types when debugging transitions, and does some transition code cleanup that does not affect behavior.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19807/HighFidelity-Beta-PR15693-971d563.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19807/HighFidelity-Beta-Interface-PR15693-971d563.exe

**Comment by shanzzam** [comment]
build this please

**Comment by shanzzam** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19819/HighFidelity-Beta-PR15693-9a75fee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19819/HighFidelity-Quest-Beta-PR15693-9a75fee.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19819/HighFidelity-Beta-PR15693-9a75fee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19819/HighFidelity-Beta-Interface-PR15693-9a75fee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19819/HighFidelity-Beta-PR15693-9a75fee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19819/HighFidelity-Beta-Interface-PR15693-9a75fee.exe

**Pull request merged**
