### PR TITLE
Attempt of making the interstitial loading bar to be more accurate.

### PR DESCRIPTION
**Pull request by danteruiz**
This PR makes the attempt of making the interstitial loading bar to be more accurate,

ticket - https://highfidelity.manuscript.com/f/cases/19315/Interstitial-Progress-bar-stalls-during-long-load-times-under-low-bandwidth-conditions-making-it-appear-hanged

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan 
1) Launch interface
2) Launch netlimiter
3) Reduce bandwidth to 10Mbps (bits not bytes)
4) Travel to large domains like Ozone
5) The loading bar should be less stagnate in most domains.
Note: If its taking a long to download the last few entities the loading bar will not progress and appear stagnate.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13847/HighFidelity-Beta-PR14200-d7dc691.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13847/HighFidelity-Beta-PR14200-d7dc691.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13847/HighFidelity-Beta-Interface-PR14200-d7dc691.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13847/HighFidelity-Beta-PR14200-d7dc691.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13847/HighFidelity-Beta-Interface-PR14200-d7dc691.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by shanzzam** [comment]
Project approval as this was slated for 74 and needs to get in 75

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14224/HighFidelity-Beta-PR14200-d7dc691.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14224/HighFidelity-Beta-PR14200-d7dc691.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14224/HighFidelity-Beta-Interface-PR14200-d7dc691.exe

**Comment by JeffClinton** [comment]
Removing QA ready tag since the interstitial PRs are being merged.

**Comment by wayne-chen** [comment]
merged into PR #14249.

**Pull request closed without merging**
