### PR TITLE
Fixing stylus picking with both hands

### PR DESCRIPTION
**Pull request by jherico**
This is a hack that reverts the stylus to using a locally created pick and directly using it instead of using the `PickManager` maintained one.  For some reason the `getPrevPickResult` isn't behaving as expected and can return invalid data, breaking the logic of the stylus events.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4708/HighFidelity-Beta-PR11757-23359e7d168766190acd12f31afc1013019db819.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4708/HighFidelity-Beta-PR11757-23359e7d168766190acd12f31afc1013019db819.exe

**Comment by themelissabrown** [comment]
@jherico is this an experiment? Or are we working towards merging this? what are the use cases for it if merging?

**Comment by themelissabrown** [comment]
This code may be part of the pointers project.  Samuel is working on the stylus code now and may or may not be using the code from the PR

it was a workaround to fix a bug that occurred when both styluses were in use in the new C++ design

**Pull request closed without merging**
