### PR TITLE
minor cleanup and optimizations around EntityItem::getDimensions()

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Yes, this PR is not important, but when trying to optimize other code a few weeks ago I noticed this problem where we would sometimes call EntityItem::getDimensions() several times in one line, to get each component out of it one at a time.  Unfortunately the function call is NOT trivial under the hood: it requires locks, branching, and copies.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5ad98981128a586e2adedc05acc184e7da9e358 available at: https://gist.github.com/52be428d2f1ade1a16256b736f49e7ea<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7772.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7772.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5ad98981128a586e2adedc05acc184e7da9e358 available at: https://gist.github.com/52be428d2f1ade1a16256b736f49e7ea<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7772.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7772.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7719
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience   
----------------------------------|----------|---------|-----------
Render Rate:                      |14.40     |14.88    |14.85       
Present Rate:                     |56.00     |60.00    |60.00       
Present New Rate:                 |14.28     |15.00    |15.00      
Render Stats Num Buffers:         |4321      |4411     |2653        
Render Stats gpu::Buffer Memory:  |35.7Mb    |61.4Mb   |34.6Mb      
Render Stats Num Textures:        |280       |252      |93          
Render Stats gpu::Texture Memory: |795.8Mb   |1165.9Mb |346.9Mb     
Render Stats Triangles:           |587k      |1133k    |752k       
Render Stats Drawcalls:           |494       |360      |251         
Render Stats State Changes:	  |294       |230      |120          
Render Stats Items:               |368       |343      |763        
Render Stats Timing:              |65.8ms    |46.0ms   |30.5ms      
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      
GPU-Z Initial Memory		  |245Mb     |245Mb    |245Mb       
GPU-Z Memory Used		  |3331Mb    |3436Mb   |2463Mb      
GPU-Z Memory Load		  |8%        |11%      |7%        

**localhost ‘createTestBlocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**playa ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**cellscience ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** On all domains tested above, the ```Render Rate```, ```Present New Rate``` were significantly lower than normal however there was no effect on quality of experience.  Attaching log for further analysis if needed.
**Successful Logout/Crash:** Successful logout.
localhost performance
playa performance
cellscience performance

**Comment by Atlante45** [comment]
Confirmed with @kevinmthomas-carpool low render rates were due to out of focus throttling.
Gonna check them for safety, but this should be good to go.

**Pull request merged**
