### PR TITLE
Case 22265: Fix model bounds on resize (RC83)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/22265/Orientation-tests-fail-on-AMD-Mac-and-Windows

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19102/HighFidelity-Beta-PR15481-99d8b27.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19102/HighFidelity-Beta-Interface-PR15481-99d8b27.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by raveenajain** [comment]
Test Plan:

Running Interface:

Avatars should continue to render correctly.

Open Luci -> check off "Opaques"
(Edit -> Running Scripts -> filter "luci")

Edit Running Scripts -> https://raw.githubusercontent.com/highfidelity/hifi_tests/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/orientation/test.js

Scale the model (3 ways listed) - the rendering box should scale with the model

press n after loading the script
Open the Create Tool -> Properties -> edit the local dimension values
with the create tool open, select the model then use the scaling tools that appear on the model
Edit -> Running Scripts -> https://gist.githubusercontent.com/SamGondelman/c3851567b21ec1119279160a6593d3c0/raw/a7fb94128d6b3184103e7b3ccb6fb4d1d9d9f8d0/AnimationURLTest.js

this model should animate
follow steps 2 and 4, but applied to the model this script creates
Run Interface -> Edit -> Running Scripts

all existing hifi-test scripts should continue to work, but the following should now be fixed (i.e. the output of the testAuto.js scripts should match the ExpectedImage):
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/orientation
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/lantern
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/gltfTestSuite/embedded/metalRoughSpheres
https://github.com/highfidelity/hifi_tests/tree/master/tests/content/entity/model/modelReaders/gltfReader/glbTestSuite/engine

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19106/HighFidelity-Beta-PR15481-99d8b27.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19106/HighFidelity-Beta-Interface-PR15481-99d8b27.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19106/HighFidelity-Beta-PR15481-99d8b27.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19106/HighFidelity-Quest-Beta-PR15481-99d8b27.apk)

**Pull request closed without merging**
