### PR TITLE
Fix sliding when stopping from run.

### PR DESCRIPTION
**Pull request by dooglifeSF**
Create isNotInputSlow var  for stategraph switch when no input and speed less than 1.5 m/s.

https://highfidelity.atlassian.net/browse/DEV-2432

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by dooglifeSF** [comment]
TEST PLAN:
This is a compromise between the old behavior (transition after coming to a complete stop, which is weirdly too late) and the behavior reported here (transition the instant user lets OFF the inputs, which is too soon and causes sliding).   Now the transition happens when input is OFF and speed drops below 1.5 m/s.

Verify that when running and stopping, you no longer see yourself slide as much.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21937/HighFidelity-Beta-PR16351-a043f0a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21937/HighFidelity-Beta-Interface-PR16351-a043f0a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21937/HighFidelity-Beta-PR16351-a043f0a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21937/HighFidelity-Quest-Beta-PR16351-a043f0a.apk)

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21941/HighFidelity-Beta-PR16351-a043f0a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21941/HighFidelity-Beta-Interface-PR16351-a043f0a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21941/HighFidelity-Beta-PR16351-a043f0a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21941/HighFidelity-Quest-Beta-PR16351-a043f0a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21946/HighFidelity-Beta-PR16351-0510215.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21946/HighFidelity-Beta-Interface-PR16351-0510215.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21946/HighFidelity-Beta-PR16351-0510215.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21946/HighFidelity-Quest-Beta-PR16351-0510215.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21946/HighFidelity-Beta-PR16351-0510215.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21946/HighFidelity-Beta-Interface-PR16351-0510215.exe

**Pull request merged**
