### PR TITLE
only worry about Ubuntu major versions when selecting Qt package

### PR DESCRIPTION
**Pull request by sethalves**
- only worry about Ubuntu major versions when selecting Qt package

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19584/HighFidelity-Beta-PR15607-886772e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19584/HighFidelity-Beta-Interface-PR15607-886772e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19584/HighFidelity-Beta-PR15607-886772e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19584/HighFidelity-Quest-Beta-PR15607-886772e.apk)

**Comment by sethalves** [comment]
build this please

**Comment by sethalves** [comment]
you're going to regret this, gustavo

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19611/HighFidelity-Beta-PR15607-886772e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19611/HighFidelity-Beta-Interface-PR15607-886772e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19611/HighFidelity-Beta-PR15607-886772e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19611/HighFidelity-Quest-Beta-PR15607-886772e.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19611/HighFidelity-Beta-PR15607-886772e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19611/HighFidelity-Beta-Interface-PR15607-886772e.exe

**Comment by shanzzam** [comment]
development of health

**Pull request merged**
