### PR TITLE
undo part of #12312

### PR DESCRIPTION
**Pull request by sethalves**
- fix HMD account-name/logout-button and goto search results

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/12138/

**Comment by sethalves** [comment]
to test:
- with flat-screen, open GOTO, see that destinations are listed
- log in (if not already logged it)
- put on HMD
- open tablet
- see that name and logout button are in upper-right corner of tablet
- open GOTO, see that destinations are listed

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7021/app_12362_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7021/HighFidelity-Beta-PR12362-a63393bc55cf1d68deff6dfceda6d744a9cba214.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7021/HighFidelity-Beta-PR12362-a63393bc55cf1d68deff6dfceda6d744a9cba214.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
