### PR TITLE
Beta Release 27 - Includes up to Developer Release 5693

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Updates to the tutorial content 
* Use ConvexHull shape for irregular "spheres"
* Make sure we delete the hrtfs associated with the 
killedNode
* Tool to list and extract files from the atp assets directory. 
* Fix failed script includes from locking the ScriptEngine up
* Display "content loading" while there are pending GPU texture transfers
* Prevent Script retries when HTTP errors are irrecoverable
* Decrease the volume of the tutorial firecracker
* Logging Improvements
  * Server log files will contain 100% of the log on a proper shutdown.
* Debug tool that prints out the skeleton hierarchy of fbx files including joint indices, bindPose and defaultPoses. 
* Fix numeric keyboard for hmd Window.prompt
* Log snapshot upload and user story creation errors
* Remove scripts from avatar attached entities for other avatars
* Fixed the issue of menus not being removed from VrMenu after they have been added. 
* Add support for whitelist entity scripts
* Allow only those who have kick permissions in a domain to request an environment mute
* Disable Users Online interactions while the window is hidden.
* Fix names of model-entity joint setters
* Remove incremental texture transfers
* Fix crashes in OpenGLVersionChecker 
* Fix users.js maximize button unclickable with hand controllers
* Fixed menu out of view with HMD and Xbox controller
* Change minimum cores to 3 to enable OpenVR
* Add a min/max avatar scale in domain-server settings
* Add a stat for stutters per second (the number of additional times a frame was scanned out to the display without reprojection) 
* The GPU buffers count display on the stats should no longer always be the same number as the texture count.
* Add AC ip address whitelist to domain server
* Protect against empty packet lists
* Add a lastEditedBy property for entities
* If you have kick rights, you can also mute someone

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0876dbc809dfef9c62d3771ee437895e113c56e4 available at: https://gist.github.com/1ebd958ff452959945bfa055bb06581d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9059-0876dbc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9059-0876dbc.dmg

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU
QA Pass

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|N/A
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Retest the kick function|Pass
**Test 8**|Enrure that you can distance grab|N/A
**Test 9**|Bring up and edit an objects with hand controllers|N/A

Desktop Mode 1600x900 Maximized Window mode

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2306 |4590 |4000
**GPU Buffer Count**: |863 |1604 |1118
**CPU Memory Usage**: |41988096 |92360704 |86585344
**GPU Memory Usage**: |33034240 |69304320 |48566272
**CPU Texture Count**: |229 |319 |297
**GPU Texture Count**: |199 |275 |274
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |79604912 |171248912 |88866064
**GPU Texture Memory Usage**: |618970709 |1113012458 |1115507196
**GPU Virtual Memory Usage**: |602908281|1168002225|1096867170
**Triangle Count**: |229591 |902145 |349083
**Triangle Rate**: |15306066 |56384062 |21817687
**API Drawcall Count**: |162 |330 |204
**Drawcall Count**: |209 |374 |1107
**Drawcall Rate**: |13933 |23375 |69187
**State Changes Texture Count**:|284 |328 |292
**Pipeline Count**: |41 |39 |51
**Item Opaques**: |237 |469 |217
**Item Translucents**: |93 |50 |41
**Item Lights**: |16 |81 |15
**Timing Opaques**: |0.928 |1.688 |0.949
**Timing Translucents**: |0.175 |0.115 |0.18
**Timing Lighting**: |0.166 |0.092 |0.27
**Render Frame**: |2.331 |2.909 |2.69

DK2

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |75 |75 |75
**CPU Buffer Count**: |2459 |4261 |4002
**GPU Buffer Count**: |819 |1262 |1128
**CPU Memory Usage**: |37011456 |69234688 |86593536
**GPU Memory Usage**: |25972736 |34738176 |48861184
**CPU Texture Count**: |269 |321 |296
**GPU Texture Count**: |228 |222 |278
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |157265072 |370019600 |80018704
**GPU Texture Memory Usage**: |888989589 |1155359274 |1298903868
**GPU Virtual Memory Usage**: |870649683|1144610980|1279433678
**Triangle Count**: |512833 |1603009 |712563
**Triangle Rate**: |39448692 |123308384 |54812538
**API Drawcall Count**: |191 |305 |197
**Drawcall Count**: |3260 |678 |2205
**Drawcall Rate**: |250769 |52153 |169615
**State Changes Texture Count**:|351 |312 |285
**Pipeline Count**: |67 |39 |44
**Item Opaques**: |279 |493 |208
**Item Translucents**: |104 |64 |36
**Item Lights**: |16 |84 |12
**Timing Opaques**: |1.003 |1.822 |0.808
**Timing Translucents**: |0.248 |0.111 |0.119
**Timing Lighting**: |0.251 |0.153 |0.179
**Render Frame**: |2.812 |3.472 |2.177

CPU Analysis - 5 Runs this PR - 2 Minutes each - Loading old apartment scene.

9059overlay5

This compares will with last RC (26).  No increase in CPU/GPU/MEM use detected.
I'm now able to enable sparse texture management with i5 + GTX970.
Also re-validated assignment-client whitelist functions work from domain-server.

**Comment by kevinmthomasse** [comment]
testing

**Comment by Nex-Pro** [comment]
***In progress***

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |55 |57
**Present Rate**: |59 |60 |58
**Present New Rate**: |58 |50 |55
**CPU Buffer Count**: |2294 |2567 |2079
**GPU Buffer Count**: |685 |752 |413
**CPU Memory Usage**: |30474240 |40546304 |38543360
**GPU Memory Usage**: |14376960 |15953920 |21233664
**CPU Texture Count**: |214 |205 |203
**GPU Texture Count**: |176 |121 |122
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |74213744 |232704464 |206170576
**GPU Texture Memory Usage**: |601990337 |594435926 |445132890
**GPU Virtual Memory Usage**: |588860796|588815995|441779626
**Triangle Count**: |258740 |537277 |201413
**Triangle Rate**: |16171250 |35818466 |14386642
**API Drawcall Count**: |191 |234 |107
**Drawcall Count**: |3021 |234 |109
**Drawcall Rate**: |188812 |15600 |7785
**State Changes Texture Count**:|344 |247 |175
**Pipeline Count**: |65 |15 |56
**Item Opaques**: |259 |436 |120
**Item Translucents**: |102 |60 |71
**Item Lights**: |16 |80 |14
**Timing Opaques**: |0.922 |1.408 |0.324
**Timing Translucents**: |0.169 |0.091 |0.168
**Timing Lighting**: |0.062 |0.141 |0.146
**Render Frame**: |1.907 |2.638 |1.585

**Comment by Nex-Pro** [comment]
### PR #8959 Beta Release 27

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive


## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Stuff here

Noticed a second stationary copy of my avatar in T-Pose for part of the performance test and on one other occasion.

Frame rates went out of control again after switching to desktop. See attached images.

**NON HMD stats**

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |1592 |3875 |3283
**GPU Buffer Count**: |579 |875 |613
**CPU Memory Usage**: |19271680 |75657216 |53653504
**GPU Memory Usage**: |13582336 |24580096 |22036480
**CPU Texture Count**: |196 |282 |278
**GPU Texture Count**: |166 |156 |185
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |52259184 |396462544 |303868368
**GPU Texture Memory Usage**: |606217409 |858152794 |746664040
**GPU Virtual Memory Usage**: |593492022|851047348|738389967
**Triangle Count**: |327509 |983783 |435249
**Triangle Rate**: |20469312 |57869588 |27203062
**API Drawcall Count**: |233 |393 |199
**Drawcall Count**: |5771 |436 |1100
**Drawcall Rate**: |360687 |25647 |68750
**State Changes Texture Count**:|437 |386 |272
**Pipeline Count**: |87 |46 |41
**Item Opaques**: |247 |465 |236
**Item Translucents**: |66 |79 |42
**Item Lights**: |14 |80 |14
**Timing Opaques**: |0.829 |1.862 |1.098
**Timing Translucents**: |0.103 |0.121 |0.134
**Timing Lighting**: |0.074 |0.126 |0.086
**Render Frame**: |1.303 |3.405 |2.046


**HMD Stats**

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |89 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |80 |83
**CPU Buffer Count**: |2201 |4248 |4220
**GPU Buffer Count**: |859 |1451 |1341
**CPU Memory Usage**: |30658560 |73101312 |80203776
**GPU Memory Usage**: |20430848 |48820224 |53239808
**CPU Texture Count**: |228 |309 |343
**GPU Texture Count**: |206 |253 |326
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |32270704 |136907216 |59705808
**GPU Texture Memory Usage**: |1014633285 |1439157722 |1325129451
**GPU Virtual Memory Usage**: |1009509837|1578164614|1645894830
**Triangle Count**: |320573 |1594100 |1173973
**Triangle Rate**: |29143000 |132841666 |106724818
**API Drawcall Count**: |54 |104 |238
**Drawcall Count**: |5373 |199 |471
**Drawcall Rate**: |488454 |16583 |42818
**State Changes Texture Count**:|102 |142 |341
**Pipeline Count**: |40 |14 |63
**Item Opaques**: |43 |184 |189
**Item Translucents**: |44 |17 |37
**Item Lights**: |1 |33 |6
**Timing Opaques**: |0.19 |0.698 |0.526
**Timing Translucents**: |0.085 |0.028 |0.097
**Timing Lighting**: |0.216 |0.117 |0.208
**Render Frame**: |1.492 |1.839 |1.816

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|check
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS, also can complete with advanced movement for hand controllers
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|untested
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|untested
**Test 7**|Retest the kick function|untested
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|Was able to edit using widgets. also created some user data with controllers
**Test 11**||blank test

qa_test_1
qa_test_2

***The rates changed consistently when interface was in or out of focus. As per the images. With high frame rate in focus and super high present rate when out of focus.***

**Comment by Nex-Pro** [comment]
In addition the spheroid physics works nicely.

**Comment by Nex-Pro** [comment]
Thoys and I are doing joint tests for groups etc.

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Smoke test passed smoothly, did harmonic oscillator tests with @Piper.Peppercorn


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |58 |56
**CPU Buffer Count**: |2586 |3999 |2298
**GPU Buffer Count**: |903 |1150 |762
**CPU Memory Usage**: |36175872 |76230656 |40185856
**GPU Memory Usage**: |18288640 |35979264 |30703616
**CPU Texture Count**: |218 |368 |185
**GPU Texture Count**: |187 |237 |170
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |34576848 |125577680 |11979216
**GPU Texture Memory Usage**: |269233409 |332610068 |293943556
**GPU Virtual Memory Usage**: |263362298|325275343|289203049
**Triangle Count**: |290182 |539745 |366294
**Triangle Rate**: |20727285 |33734062 |22893375
**API Drawcall Count**: |159 |177 |68
**Drawcall Count**: |170 |381 |68
**Drawcall Rate**: |12142 |23812 |4250
**State Changes Texture Count**:|268 |212 |84
**Pipeline Count**: |12 |49 |30
**Item Opaques**: |280 |165 |67
**Item Translucents**: |88 |21 |8
**Item Lights**: |16 |34 |7
**Timing Opaques**: |1.565 |0.747 |0.328
**Timing Translucents**: |0.258 |0.044 |0.035
**Timing Lighting**: |0.312 |0.173 |0.201
**Render Frame**: |4.067 |2.206 |1.53

**Comment by Nex-Pro** [comment]
### Fail for same reason as @Thoys during kick tests we each saw orphaned kick/mute overlays which persisted. 
hifi-snap-by-piper-peppercorn-on-2016-11-12_20-26-37

**Comment by ZappoMan** [comment]
Test on my array of min machines:
- i7 980, Oculus and Vive - PASS
- i5 970, Oculus and Vive - PASS (steam non-beta)
- i5 AMD, Oculus and Vive - PASS (steam non-beta)

There was some stuttering in the dev-playa on the i5's on loading, and under graphics rendering duress when I was shooting a ton of fireworks -- but I think it's good enough to ship as "Steam Early Access"

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test on Steam with Oculus and Hydras.  Followed steps - Download High Fidelity on Steam - Right click High Fidelity - Got to the `Betas` tab - Enter the following code `PRIVATE` and click `Check Code` - If you now click the drop down you should be able to select the `rc-27` beta.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |286 |251 |247
**Present Rate**: |285 |251 |251
**Present New Rate**: |241 |154 |198
**CPU Buffer Count**: |2636 |2156 |3400
**GPU Buffer Count**: |771 |646 |701
**CPU Memory Usage**: |34328576 |33280000 |51068928
**GPU Memory Usage**: |23490560 |21712896 |24530944
**CPU Texture Count**: |306 |226 |291
**GPU Texture Count**: |252 |172 |213
**GPU Transfer Count**: |0 |1 |0
**CPU Texture Memory Usage**: |157116784 |119327184 |216181200
**GPU Texture Memory Usage**: |927904975 |680292196 |872198248
**GPU Virtual Memory Usage**: |902951176|667981694|855393210
**Triangle Count**: |294879 |429363 |319851
**Triangle Rate**: |98293000 |47707000 |106617000
**API Drawcall Count**: |152 |174 |190
**Drawcall Count**: |163 |171 |1099
**Drawcall Rate**: |54333 |19000 |366333
**State Changes Texture Count**:|259 |199 |275
**Pipeline Count**: |25 |49 |53
**Item Opaques**: |267 |343 |178
**Item Translucents**: |62 |91 |31
**Item Lights**: |16 |80 |9
**Timing Opaques**: |0.959 |1.376 |0.549
**Timing Translucents**: |0.169 |0.196 |0.114
**Timing Lighting**: |0.125 |0.108 |0.122
**Render Frame**: |2.146 |2.866 |1.543


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Success
**Test 2**|Install a fresh copy of "Home' and do tutorial|Unable to complete tutorial as I do not have a Vive.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Success - Only one in ```dev-playa``` however I heard and saw it.
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|N/A
**Test 7**|Retest the kick function|N/A
**Test 8**|Ensure that you can distance grab|Success on Hydra
**Test 9**|Bring up and edit an objects with hand controllers|Success on Hydra with everything except the ability to close a UI window clicking on the X with the Hydra does not work however it has not worked ever for that capacity.  This is not a bug I believe but a Hydra compatibility issue.

**Comment by thoys** [comment]
## QA Test - SteamVR [beta-rc27]

## QA Test
**QA Tester**: thoys
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Works all fine on SteamVR using HTC Vive on i7 with Geforce GTX980Ti

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |89 |89
**CPU Buffer Count**: |2267 |2862 |725
**GPU Buffer Count**: |830 |1083 |288
**CPU Memory Usage**: |35753984 |57982976 |24473600
**GPU Memory Usage**: |24621056 |42184704 |18477056
**CPU Texture Count**: |288 |275 |134
**GPU Texture Count**: |230 |199 |100
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |32758128 |61942224 |16820688
**GPU Texture Memory Usage**: |552942536 |592612641 |444714314
**GPU Virtual Memory Usage**: |545979133|586299182|442371344
**Triangle Count**: |650324 |4031750 |378984
**Triangle Rate**: |59120363 |366522727 |37898400
**API Drawcall Count**: |205 |447 |39
**Drawcall Count**: |1968 |963 |71
**Drawcall Rate**: |178909 |87545 |7100
**State Changes Texture Count**:|372 |456 |38
**Pipeline Count**: |72 |42 |22
**Item Opaques**: |262 |513 |79
**Item Translucents**: |94 |61 |24
**Item Lights**: |15 |91 |15
**Timing Opaques**: |1.159 |1.766 |0.313
**Timing Translucents**: |0.221 |0.107 |0.058
**Timing Lighting**: |0.156 |0.189 |0.217
**Render Frame**: |2.807 |3.47 |1.912

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Performance great.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Tutorial works fine, using vive
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Sounds are audible
**Test 4**|Launch firework, on dev-playa, can other hear?|Yes
**Test 5**|Switch avatar and make sure it does not crash|Works
**Test 6**|Test group functions|Work
**Test 7**|Retest the kick function|Same issue remains as earlier descibed, but as it got no fix between my last test on the PR-download version and now (steam rc-27) I will not mark this QA test as fail because of this impurity
**Test 8**|Enrure that you can distance grab|Works (As already done in tutorial)
**Test 9**|Bring up and edit an objects with hand controllers|Works, as it did before.



QA PASS (But please fix the issue with Kick (RC-test 7) in the next release, it looks bad)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94902106e63acc1eda20354a9a42d439499b8afe available at: https://gist.github.com/1ebd958ff452959945bfa055bb06581d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9059-9490210.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9059-9490210.dmg

**Comment by thoys** [comment]
## New Content QA - Test

- Launched High Fidelity `RC27` in steam with a fresh home.
- The tutorial worked fine.
- After leaving the tutorial I saw a sign that pointed to the welcome area teleporter. 👍 
- I flew down and saw that there was some description in the sandbox, this sign is very light colored, it hurted my eyes a little bit, but that might be the time of day. Also I found two teleporters, both take me to the location that they display on their label.

QA PASS

**Pull request merged**
