### PR TITLE
Case 20941: Goto the spot on first launch (79.0)

### PR DESCRIPTION
**Pull request by danteruiz**
Goto the spot on first launch

ticket https://highfidelity.manuscript.com/f/cases/20941/Redirect-FTUE-URL-to-Master

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan in this PR https://github.com/highfidelity/hifi/pull/14833

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16959/HighFidelity-Beta-PR14832-9082a3f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16959/HighFidelity-Beta-PR14832-9082a3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16959/HighFidelity-Beta-Interface-PR14832-9082a3f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16959/HighFidelity-Beta-PR14832-9082a3f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16959/HighFidelity-Beta-Interface-PR14832-9082a3f.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS

On clean launches, Interface attempted to go to TheSpot. Could still access tutorial, as bookmarks' behavior didn't change.

**Pull request merged**
