### PR TITLE
Protect session UUID from concurrent read/writes

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
## Test Plan:
- Run this build with its Sandbox, make sure you can connect to the Sandbox.
- Go back and forth between a few dev domains.

[Bug](https://highfidelity.manuscript.com/f/cases/12892/Node-UUID-in-LimitedNodeList-should-be-protected-with-a-read-write-lock)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7690/app_12547_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7690/HighFidelity-Beta-PR12547-85b4c3b4229ea3cf975790c123d760fe0808c39b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7690/HighFidelity-Beta-PR12547-85b4c3b4229ea3cf975790c123d760fe0808c39b.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
