### PR TITLE
faster Bullet kinematics

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* only update static Aabb's for Bullet broadphase when they move
* kinematic and static collision groups do not collide (Bullet will not cache Aabb overlap pairs between these groups)
* minor optimizations

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
I'm breaking the old "faster kinematic motion" PR #7590 into two parts: (a) the changes around how Bullet computes collisions and (b) optimizations of our custom kinematic motion code.  This is part (a) and appears to not suffer from the glitches for ballistic motion of dynamic objects.  This part contains the largest potential gains and removes a known mode for making a "physics performance bomb".

**Comment by AndrewMeadows** [comment]
Below is the benchmark script for testing.  Note that it has two "modes" for testing the two variety of performance problems that we're trying to fix.  This PR fixes the "bullet-aabb-optimizations" mode.

```
//
//  kinematicBenchmark.js -- stress test for performance bugs in kinematic motion
//
//  Created by Andrew Meadows 2016.04.07
//  Copyright 2016 High Fidelity, Inc.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//

// Here is repro recipe:
//
// (1) Enable stats, with details:
// (a) Developer --> Stats
// (b) Developer --> Timing --> Performance Timer --> Display Timing Details
//
// (2) Navigate to about <50, 50, 50> and look toward the world's origin
// (3) Run this script
// (4) Press 't' to start the objects moving.
// (5) Watch the stats in /idle/update/ as the entities move about.

// This script creates a number of non-dynamic entities randomly about a sphere.
// When the 't' key is pressed the entities start moving in a linear kinematic
// path either toward the center of the sphere or away depending on the test mode.
//
// There were two main performance problems addressed hence this test script has two
// modes: one to test the performance problem in Bullet and another to test that of
// our own custom kinematic motion calculations (entity-math).  Uncomment the mode
// of your choice and then reload the script:

var TEST_MODE = "bullet-aabb-optimizations";
//var TEST_MODE = "hifi-kinematic-optimizations";

// for the visual model we use the six-sided die, because it is relatively inexpensive to render
var HIFI_PUBLIC_BUCKET = "http://s3.amazonaws.com/hifi-public/";
var MODEL =  HIFI_PUBLIC_BUCKET + "models/props/Dice/goldDie.fbx"

// for the collision shape we use the tiltmaze because it hast a lot of vertices and produces
// a rather expensive compound shape and will stress the physics Aabb updates
var COLLISION_HULL = "http://hifi-content.s3.amazonaws.com/DomainContent/Home/tiltMaze/newmaze_tex-3.obj";

var SPHERE_CENTER = {x: 0, y: 30, z: 0};
var SPHERE_RADIUS = 20;
var PERIOD = 10.0;
var BASE_DIMENSION = 2;

var NUM_ENTITIES = 10;
var VELOCITY_SIGN = 1.0;

if (TEST_MODE == "hifi-kinematic-optimizations") {
    NUM_ENTITIES = 100;
    VELOCITY_SIGN = -1.0;
}

KinematicObject = function() {
    this.entityId = null;
    this.startPosition = {x: 0, y: 0, z: 0};
    this.endPosition = {x: 0, y: 0, z: 0};
    this.period = PERIOD;
    this.velocity = {x: 0, y: 0, z: 0};
};

var objectCount = 0;

KinematicObject.prototype.createEntity = function() {
    if (this.entityId == null) {
        var dimension = BASE_DIMENSION * (1.0 + Math.random());
        if (TEST_MODE == "bullet-aabb-optimizations") {
            this.entityId = Entities.addEntity( {
                type: "Model",
                modelURL: MODEL,
                compoundShapeURL: COLLISION_HULL,
                name: "obj" + objectCount,
                dimensions: {x: dimension, y: dimension, z: dimension},
                position: this.startPosition,
                velocity: {x: 0, y: 0, z: 0},
                gravity: {x: 0, y: 0, z: 0},
                angularVelocity: {x: 0, y: 0, z: 0},
                color: { red: Math.random() * 255, green: Math.random() * 255, blue: Math.random() * 255 },
                dynamic: false,
                collisionless: false,
                damping: 0,
                lifetime: 300
            } );
        } else {
            this.entityId = Entities.addEntity( {
                type: "Box",
                name: "obj" + objectCount,
                dimensions: {x: dimension, y: dimension, z: dimension},
                position: this.startPosition,
                velocity: {x: 0, y: 0, z: 0},
                gravity: {x: 0, y: 0, z: 0},
                angularVelocity: {x: 0, y: 0, z: 0},
                color: { red: Math.random() * 255, green: Math.random() * 255, blue: Math.random() * 255 },
                dynamic: false,
                collisionless: false,
                damping: 0,
                lifetime: 300
            } );
        }
        objectCount++;
    }
}

KinematicObject.prototype.deleteEntity = function() {
    if (this.entityId != null) {
        Entities.deleteEntity(this.entityId);
        this.entityId = null;
    }
}

KinematicObject.prototype.start = function() {
    if (this.entityId != null) {
        var travel = {
            x: this.endPosition.x - this.startPosition.x,
            y: this.endPosition.y - this.startPosition.y,
            z: this.endPosition.z - this.startPosition.z,
        };
        var period = this.period;
        this.velocity = {
            x: VELOCITY_SIGN * travel.x / period,
            y: VELOCITY_SIGN * travel.y / period,
            z: VELOCITY_SIGN * travel.z / period
        }
        var properties = {
            position: this.startPosition,
            velocity: this.velocity
        };
        Entities.editEntity(this.entityId, properties);
    }
}

KinematicObject.prototype.stop = function() {
    if (this.entityId != null) {
        var properties = {
            position: this.endPosition,
            velocity: {x: 0, y: 0, z: 0}
        };
        Entities.editEntity(this.entityId, properties);
    }
}

function randomDirection() {
    var x = Math.random() - 0.5;
    var y = Math.random() - 0.5;
    var z = Math.random() - 0.5;
    var length = Math.sqrt(x * x + y * y + z * z);
    return {x: x / length, y: y / length, z: z / length};
}

var objects = [];
var i = 0;
for (i = 0; i < NUM_ENTITIES; i++) {
    var obj = new KinematicObject;
    obj.createEntity();
    var direction = randomDirection();
    obj.startPosition = {
        x: SPHERE_CENTER.x - SPHERE_RADIUS * direction.x,
        y: SPHERE_CENTER.y - SPHERE_RADIUS * direction.y,
        z: SPHERE_CENTER.z - SPHERE_RADIUS * direction.z
    };
    obj.endPosition = {
        x: SPHERE_CENTER.x + SPHERE_RADIUS * direction.x,
        y: SPHERE_CENTER.y + SPHERE_RADIUS * direction.y,
        z: SPHERE_CENTER.z + SPHERE_RADIUS * direction.z
    };
    obj.stop();
    objects.push(obj);
}

var running = false;

function stopEverything() {
    if (running) {
        running = false;
        for (i = 0; i < NUM_ENTITIES; i++) {
            var obj = objects[i];
            obj.stop();
        }
    }
}

function pressEvent(event) {
    if (event.text == "t") {
        running = !running;
        if (running) {
            Script.setTimeout(stopEverything, 1000 * PERIOD);
            for (i = 0; i < NUM_ENTITIES; i++) {
                var obj = objects[i];
                obj.start();
            }
        } else {
            for (i = 0; i < NUM_ENTITIES; i++) {
                var obj = objects[i];
                obj.stop();
            }
        }
    }
}

function tearDown() {
    var i = 0;
    for (i = 0; i < NUM_ENTITIES; i++) {
        var obj = objects[i];
        obj.deleteEntity();
    }
}

Controller.keyPressEvent.connect(pressEvent);
Script.scriptEnding.connect(tearDown);
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 689c8248770553f4c71f4ff71ad038674ac67a10 available at: https://gist.github.com/1b5b0fce1992d6a8247b97ba3efe3818<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7643.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7643.dmg

**Comment by AndrewMeadows** [comment]
Here is another test script, for making sure that ballistic motion works correctly:

```
//
//  ballistic.js -- test ballistic motion interpolation
//
//  Created by Andrew Meadows 2016.04.12
//  Copyright 2016 High Fidelity, Inc.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//

// Test ballistic motion for PR-7643
// (1) Navigate to near origin <0, 0, 0>
// (2) Run this script
// (3) press 't' to teleport dynamic box to an offset from the origin then launch
//     ballistically back toward the origin.  Keep pressing "t" to restart the launch.
// (4) Watch the motion of the box as it moves... should be as smooth as when running
//     on the official release.
// Note: the box has a lifetime of 300 seconds

var TARGET = {x: 0, y: 0, z: 0};
var HORIZONTAL_SPEED = 10.0;
var MIN_HEIGHT = 1.0;
var entityID = null;
var GRAVITY_Y = -3.0;
var GRAVITY = {x: 0, y: GRAVITY_Y, z: 0};
var MIN_DISTANCE = 0.5;
var MIN_TIME = Math.sqrt(- 2.0 * MIN_HEIGHT / GRAVITY_Y);
var COLOR = {red: 255, green: 180, blue: 100};
var DIMENSION = {x: 1.0, y: 1.0, z: 1.0};

function init() {
    if (entityID == null) {
        entityID = Entities.addEntity( {
            type: "Box",
            name: "ballistic",
            dimensions: DIMENSION,
            position: TARGET,
            velocity: {x: 0, y: 0, z: 0},
            gravity: GRAVITY,
            angularVelocity: {x: 0, y: 0, z: 0},
            color: COLOR,
            dynamic: true,
            collisionless: false,
            damping: 0.4,
            angularDamping: 0.4,
            friction: 1.0,
            restitution: 0.0,
            lifetime: 300
        } );
    }
}

function launch() {
    var startPosition = {x: 13, y: -0.5, z: 20};
    Entities.editEntity(entityID, {position: startPosition} );
    var p = Entities.getEntityProperties(entityID, ["position"]);
    var movement = { x: 2 * (TARGET.x - p.position.x), z: 2 * (TARGET.z - p.position.z) };
    var distanceXZ = Math.sqrt(movement.x * movement.x + movement.z * movement.z);
    var speedXZ = HORIZONTAL_SPEED;
    var t = distanceXZ / HORIZONTAL_SPEED;
    if (t < MIN_TIME) {
        t = MIN_TIME;
        speedXZ = distanceXZ / t;
    }
    var halfT = 0.5 * t;
    var speedY = - GRAVITY_Y * halfT;
    var ballisticVelocity = {x: 0.0, y: 0.0, z: 0.0};
    if (distanceXZ > MIN_DISTANCE) {
        var foo = speedXZ / distanceXZ;
        ballisticVelocity = {x: foo * movement.x , y: speedY, z: foo * movement.z};
    }
    Entities.editEntity(entityID, {velocity: ballisticVelocity} );
}
function pressEvent(event) {
    if (event.text == "t") {
        launch();
    }
}
function tearDown() {
    if (entityID != null) {
        Entities.deleteEntity(entityID);
        entityID = null;
    }
}
init();
Controller.keyPressEvent.connect(pressEvent);
Script.scriptEnding.connect(tearDown);
```

**Comment by OmegaHeron** [comment]
Part One - Running second script on current production build (Windows - Interface 4678) and this PR.

Ran this many times on production build to point where I had a good feel for how it moves - then repeatedly with this PR - I couldn't see any difference in how dice move.  Took full framerate video of both via fraps and did a side by side sync playback - still couldn't really see any difference.  That seems good.  Moving on to benchmarks next.

**Comment by ZappoMan** [comment]
Note: @AndrewMeadows @sethalves - let's make sure we do a group test of this PR before we merge it... just like the last PR.

**Comment by OmegaHeron** [comment]
Part two - first script and physics time.

Current production build peaks a little over 6mS for update/physics step while this build comes in at .4 note that is point 4

update/physics/stepSimulation shows a corresponding massive decrease.

Watching things fly around I see no difference between the "quality" of movement between this PR and current production for either test.  Looking at other things reveals same equality in this PR vs release build looking same.

Wat I did **not** do was look for any changes to render rates from this as it has the stats for render/present/sim that is not reliable.

**Comment by cozza13** [comment]
reminder. Only @ZappoMan or @cozza13 will merge this post a group test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d7efbc43fa682ac7d4a8cd2dd9a49074eb7558f available at: https://gist.github.com/1b5b0fce1992d6a8247b97ba3efe3818<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7643.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7643.dmg

**Pull request merged**
