### PR TITLE
Added method to TestScriptingInterface to clear caches

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
A single scripting command has been added to the Test Scripting Interface.  This command is equivalent to the Interface menu command Reload Content.

The command is useful for testing, as it provides more consistent results.

# Testing
1. Run Interface with a long-running test script.
2. Open the Scripting Console
3. After the domain has loaded, run Test.clearCaches(); from the console
4. Verify that the content is cleared and then reloads.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8291/app_12716_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8291/HighFidelity-Beta-PR12716-4a7414322b0e43570025711579c62367943d4da8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8291/HighFidelity-Beta-PR12716-4a7414322b0e43570025711579c62367943d4da8.exe

**Comment by samcake** [comment]
This has already been done in a different PR, closing

**Pull request closed without merging**
