### PR TITLE
add debugging of active enabled controllers

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 087f0b31793340ccf62bced6700d98fc648f04a4 available at: https://gist.github.com/a8b58acdaaee7b9bf423<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6619-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6619.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e183290248573648f17f40300961e8e34da0c95 available at: https://gist.github.com/a8b58acdaaee7b9bf423<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6619-win32.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6619.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80f8934abc64e548ea47fdec07b741be2aff18e9 available at: https://gist.github.com/a8b58acdaaee7b9bf423<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6619-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6619.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f8d8c9bd66a521b14fdfe1eb991edcf40958197 available at: https://gist.github.com/a8b58acdaaee7b9bf423<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/High+Fidelity-PR-6619-win64.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6619.dmg

**Comment by ZappoMan** [comment]
closing and opening a version of the SDK change in a stand-alone PR

**Pull request closed without merging**
