### PR TITLE
DOC-212: Graphics AP JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- Graphics

Classes:
- GraphicsModel
- GraphicsMesh
- GraphicsMeshPart

Also:
- Assets API - Minor JSDox fixes.
- Entities API - Minor JSDox fixes.
- MeshProxy class - Minor JSDoc fixes.

Case: https://highfidelity.atlassian.net/browse/DOC-212

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22820/HighFidelity-Beta-PR16580-7af1845.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22820/HighFidelity-Beta-Interface-PR16580-7af1845.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22820/HighFidelity-Beta-PR16580-7af1845.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22820/HighFidelity-Quest-Beta-PR16580-7af1845.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22819/HighFidelity-Beta-PR16580-61b3b09.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22819/HighFidelity-Quest-Beta-PR16580-61b3b09.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22820/HighFidelity-Beta-PR16580-7af1845.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22820/HighFidelity-Beta-Interface-PR16580-7af1845.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22821/HighFidelity-Beta-PR16580-67bfe03.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22821/HighFidelity-Beta-Interface-PR16580-67bfe03.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22821/HighFidelity-Beta-PR16580-67bfe03.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22821/HighFidelity-Quest-Beta-PR16580-67bfe03.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22821/HighFidelity-Beta-PR16580-67bfe03.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22821/HighFidelity-Beta-Interface-PR16580-67bfe03.exe

**Comment by hd23408** [comment]
Closing in favor of https://github.com/highfidelity/hifi/pull/16583

**Pull request closed without merging**
