### PR TITLE
Created 2-key shortcut for toggling first person/third person and mirror mode/ first person

### PR DESCRIPTION
**Pull request by druiz17**
Created 2-key shortcut for toggling first person/third person and mirror mode/ first person

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- launch interface and click on interface to gain focus
- press Ctrl-F to toggle between first and third person view
- press Alt-h to toggle between mirror mode and first person view

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1837/HighFidelity-Beta-PR11018-649b974927e0deff5156d1333555b40206e4773d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1837/HighFidelity-Beta-PR11018-649b974927e0deff5156d1333555b40206e4773d.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by anshuman64** [comment]
@YuppyPlays Can you test after it rebuilds? There was a small error in the code

**Comment by YuppyPlays** [comment]
@anshuman64 No problem at all! :) I was wondering why stuff kept disappearing in comments haha, I shall await latest build :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1840/HighFidelity-Beta-PR11018-5f3b68d544d6d4e03fd54e6d9a09a28e9dd7840f.dmg

**Comment by anshuman64** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1841/HighFidelity-Beta-PR11018-5f3b68d544d6d4e03fd54e6d9a09a28e9dd7840f.dmg

**Comment by cozza13** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1847/HighFidelity-Beta-PR11018-5f3b68d544d6d4e03fd54e6d9a09a28e9dd7840f.exe

**Comment by Nex-Pro** [comment]
Testing this as per Request

**Comment by davidkelly** [comment]
looks like the macos build timed out

**Comment by davidkelly** [comment]
test this please

**Comment by Nex-Pro** [comment]
@davidkelly  The shorcuts work every time. But I'm pretty sure that HMD mirror is disallowed by design. 
Option is greyed out in master and this build do to being impractical.
Methinks this should check for HMD and disallow if present 
when CTRL+H is pressed.

**Comment by davidkelly** [comment]
@Nex-Pro  -- sorry I just noticed the mac build timed out.  If you type `test this please` into the comments, it re-runs the build.  

and I agree -- we shouldn't go into mirror mode in HMD.

**Comment by Nex-Pro** [comment]
### Fail on HMD issue with CTRL+H

@davidkelly Why isn't mirror CTRL+M ?

**Comment by Nex-Pro** [comment]
NM I forgot ctrl+m is mute

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1850/HighFidelity-Beta-PR11018-5f3b68d544d6d4e03fd54e6d9a09a28e9dd7840f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1850/HighFidelity-Beta-PR11018-5f3b68d544d6d4e03fd54e6d9a09a28e9dd7840f.exe

**Comment by Nex-Pro** [comment]
@davidkelly I see a new build but no new new commits. Has anything changed ?

**Comment by druiz17** [comment]
@Nex-Pro re-test once new build is available

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1872/HighFidelity-Beta-PR11018-06b4c53d28f0c843ab8b927bbe8ba94695dc15b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1872/HighFidelity-Beta-PR11018-06b4c53d28f0c843ab8b927bbe8ba94695dc15b3.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### PASS

 && !isHMDMode()

Has done the trick.

**Comment by AndrewMeadows** [comment]
@anshuman64, is this PR truly CRITICAL?  @druiz17 is on vacation this week.  If we need this fixed soon maybe we should merge it and find someone to fix the missing bits, or have someone clone it, fix, and submit a new PR.

**Comment by sethalves** [comment]
@andrew https://github.com/highfidelity/hifi/pull/11037

**Pull request closed without merging**
