### PR TITLE
Philip's gravity example

### PR DESCRIPTION
**Pull request by sethalves**
- Philip's gravity example

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- press ctrl-j and run makePlanets.js
- click the icon that appears
- grab the moon and toss it around the earth, observe that it acts as if under the effects of gravity
- click the - icon and see that they are deleted

**Comment by hifi-gustavo** [comment]
Build console output for commit: ced7a56e39732127ff52038fe3521ea931fa1a54 available at: https://gist.github.com/1be80c1d4bd98d87e1c9c5cd462066f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ab52b886946f3458aa742beafb667545f49349e available at: https://gist.github.com/1be80c1d4bd98d87e1c9c5cd462066f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9fe827a93bb859f787ce8b1808a0919090a33a8e available at: https://gist.github.com/1be80c1d4bd98d87e1c9c5cd462066f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7850.dmg

**Comment by Nex-Pro** [comment]
**Win 10 desktop i7 4.4ghz 16gb ram.**
**GTX770 2gb gpu.**
**HMD: None**
**Hand Controllers: None**

#### Fail

Moon does not act as if under gravity. 
Releasing the moon tangentially relative to the Earth at any speed, low or high, results in the Moon simply travelling in a straight line.

Moon has the gravity script from the PR showing in its properties.
I see the "load gravity..." and "Unload gravity..."  messages in the log. *Note the capitalization* 
I do not see the "Gravity simulation started." and "Gravity simulation stopped due to grab" messages that I think I should see. Or any of the other messages from the script.

It is not immediately apparent from reading the script whether it is necessary to use hand controllers for this task.

The res and delete icons appear at top left corner of screen initially clashing with the face and microphone Icons that were there.

The icons lagged badly behind the cursor whilst being dragged across the screen. ( also the edit bar and examples icon ) However the Mic volume indicator bar did not lag whilst being dragged.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7850
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results/Observations:** Successful test.  Loaded ```makePlanets.js``` and utilized hydras to grab the moon and toss it around the earth.  Successful observation that it acts as if it is under the effects of gravity to which a final click of the ```-``` icon removed the entities successfully.  Screen shot attached.
**Successful Logout/Crash:** Successful logout.
[https://gyazo.com/d79bf39fc0dcb2cb75cc5dd339357220](https://gyazo.com/d79bf39fc0dcb2cb75cc5dd339357220)

**Pull request merged**
