### PR TITLE
add a column to edit.js to identity baked models

### PR DESCRIPTION
**Pull request by birarda**
- added a column to edit.js to identify models with a `.baked.fbx` extension

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

This PR adds a new column to the entity list to identify models that have the extension `.baked.fbx` (which we will be adding support for soon).

The edit.js pane is no longer resizable so this may be complicated to test. There is a small disclosure arrow at the end of the header list in the entity list. You can use that to go over to the end columns and you should see a new column `Ba...` after the transparent texture column.

If you change a model in a domain to have the extension `.baked.fbx` and you reload the entity list (this may require closing Edit and re-opening it) you should see a checkmark in the 'Baked' column for that entity. If you sort by the column, you should see the baked model move to the top of the list, or to the bottom, depending on your sort order.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 924624b127f96a5985906cd9ac2637d28f61ea17 available at: https://gist.github.com/e4560643d8ad1f0dd880a0718b2a8f58<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-924624b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-924624b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d226fe6c3859160a34abbe754142a334ff479ff3 available at: https://gist.github.com/e4560643d8ad1f0dd880a0718b2a8f58<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-d226fe6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-d226fe6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3452dd025145d4254343b93ec0ab8fc63dce161e available at: https://gist.github.com/e4560643d8ad1f0dd880a0718b2a8f58<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-3452dd0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10251-3452dd0.dmg

**Comment by Nex-Pro** [comment]
Testing this now

**Comment by Nex-Pro** [comment]
**PASS**

Added a model with .baked.fbx  and it works fine.  Let's get the horizontal tablet I've been asking for ( for some months now ) 

hifi-snap-by-piper-peppercorn-on-2017-04-21_16-41-00

**Comment by jherico** [comment]
You couldn't open the 'baked' PR on 4/20?  Really?

**Pull request merged**
