### PR TITLE
Break framebuffer operations out of TextureCache, minor naked GL removal

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: fda1cb6f7b016bf0beb8cef9a7f014d9e291e483 available at: https://gist.github.com/194632d2d29265e8e150<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.dmg

**Comment by ZappoMan** [comment]
This appears to break stereo rendering.

**Comment by ZappoMan** [comment]
More details about stereo.. 
1) I tested on mac, and it's definitely totally borked.
2) the left eye and right eye appear to be rendering from different orientations. The right eye seems correct, but the left eye seems to be going off in radically wrong direction. 
3) The left eye appears to have some residual rendered content from the right eye in the background.

**Comment by PhilipRosedale** [comment]
windows-oculus-5379-borked

**Comment by ZappoMan** [comment]
On windows, you can see the following:
1) the lighting appears correct in left and right eyes.
2) there is definitely residual content in both eyes (frame buffer clear not working?)
3) the right eye appears to be shifted with some of the left eye content visible in the center (clear not working?)
4) the background has some content from the view ??? (more clear?)
5) of note: the overlays appear to be correct in both eyes

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd5da87551e6688cca469d84ca9f8d55c5cf8dc8 available at: https://gist.github.com/194632d2d29265e8e150<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: de30288b5dc1d249429d7ce4b35537cec52d0968 available at: https://gist.github.com/194632d2d29265e8e150<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.dmg

**Comment by jherico** [comment]
The stereo bug was caused because i wasn't resetting the pool of unused framebuffers on a size change.  Fixed now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f13488f116ba358c2236105e3b93ea6e1eae6ac available at: https://gist.github.com/194632d2d29265e8e150<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5379.dmg

**Pull request merged**
