### PR TITLE
fix the edit.js toolbar buttons so they don't vanish when moused-over or clicked

### PR DESCRIPTION
**Pull request by sethalves**
- fix the edit.js toolbar buttons so they don't vanish when moused-over or clicked

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open edit.js
- mouse over the edit.js buttons (for example, the "sphere" button)
- make sure the button doesn't vanish
- also try this with hmd+hand-controllers and using the half-squeezed lasers on these same buttons

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6671324a33bff4c2426591a856e66b1561b0090b available at: https://gist.github.com/8c5125f6227db52ea4274391e208725b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9583-6671324.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9583-6671324.dmg

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
I think for this pr this is a pass but please read note.

In normal use the tool bar icons behave well.(HMD and desktop)

Note:
In HMD if the avatar is moving in any way via hand controllers and a toolbar icon is clicked eg: sphere or cube the toolbar icon becomes toggled to the 'over' condition ( 50% or so transparent ) subsequent pressing of the trigger clears it.

To repro:
 Drive backwards with left controller click cube or sphere icon on toolbar.
Observe Icon remains toggled.

Also happens with up/down etc.

**Comment by sethalves** [comment]
okay, I'll make a note about the button-state problem.

**Pull request merged**
