### PR TITLE
JSDoc Entity preload, unload, startFarTrigger, etc.

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9351/app_13061_PR_2482da3c259752b670fc4f2acbf3c087073b80ad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9351/HighFidelity-Beta-PR13061-2482da3c259752b670fc4f2acbf3c087073b80ad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9351/HighFidelity-Beta-Interface-PR13061-2482da3c259752b670fc4f2acbf3c087073b80ad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9351/HighFidelity-Beta-PR13061-2482da3c259752b670fc4f2acbf3c087073b80ad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9351/HighFidelity-Beta-Interface-PR13061-2482da3c259752b670fc4f2acbf3c087073b80ad.exe

**Pull request merged**
