### PR TITLE
Remove stopwatch source in favor of using source in hifi-content repo

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Source is already in hifi-content repo, and is identical to source being removed here.

No QA required.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4451/HighFidelity-Beta-PR11689-7cb6bae1e6ab6f9aeaccbd9c7242e2fea5dad433.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4451/HighFidelity-Beta-PR11689-7cb6bae1e6ab6f9aeaccbd9c7242e2fea5dad433.exe

**Comment by misslivirose** [comment]
@nimisha20 Do we reference the stop watch being part of the source anywhere in the documentation that we need to update?

**Comment by nimisha20** [comment]
No, we don't reference it anywhere @misslivirose

**Pull request merged**
