### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes a couple warnings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5230b805d28328bddeaf781288e5ad40c8e1dac9 available at: https://gist.github.com/a7e157bf42c1c001ed5c<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54b3dbe39eb7a62dc63fe05218f47f302e645d13 available at: https://gist.github.com/008463340735a8c8cc14<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by Atlante45** [comment]
@murillodigital can you checkout that PR?
Looks like something went wrong with Qt.

**Comment by murillodigital** [comment]
i think this may be associated to the merge done yesterday that moved glm over to the new external handling mechanism --- curious why other PRs havent failed though but it may be that they have yet to pull that merge from upstream. checking

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
OS X Yosemite functional test completed with errors
Download recording here:
https://s3.amazonaws.com/hifi-public/pr-builds/recordings/4307.mov

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54b3dbe39eb7a62dc63fe05218f47f302e645d13 available at: https://gist.github.com/dac14e51b650d22ac392<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4307.dmg

**Pull request merged**
