### PR TITLE
RC66: Fix infinite loading when authing wallet during Checkout

### PR DESCRIPTION
**Pull request by zfox23**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8262/HighFidelity-Beta-PR12709-a588776b47f864655df5a8e2d1eaf3335e5b0e77.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8262/HighFidelity-Beta-PR12709-a588776b47f864655df5a8e2d1eaf3335e5b0e77.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Purchase success screen is displayed after authenticating wallet.

**Comment by conklin94122** [comment]
@howard-stearns Needs your approval

**Pull request merged**
