### PR TITLE
DNM -- Tablet ui stable

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ea2ca1fcc90e594083c842424153bf31af897dc available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-2ea2ca1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-2ea2ca1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7032793d3d9a71f70e2c4c480ed6d01980a62037 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-7032793.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-7032793.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eab8348ed620b4d597ef2096eebcdfd054b0f18c available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-eab8348.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-eab8348.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd7b094fffae5c9473913ac9da5c3460c4cb687a available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-bd7b094.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-bd7b094.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 404a89ec30a6941fa7742befb6457ceaf3b170f4 available at: https://gist.github.com/c7ad9d747ac5717808583a518cc7987c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-404a89e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-404a89e.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 404a89ec30a6941fa7742befb6457ceaf3b170f4 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-404a89e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-404a89e.dmg

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested with Oculus and Oculus Touch utilizing hand controllers and successfully brought up the tablet by clicking 'Y'/'X' buttons on the Oculus Touch.  Immediately a very responsive stylus appeared on both hands and was very intuitive to interact with the tablet.  I was able to browse the market with ease with very intuitive scrolling and selecting and manipulate objects very naturally.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 820e42694c05e25363616b343ee85b06bc27fca2 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-820e426.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-820e426.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 390c101609fa681d41efb9e30d39e99340255a1b available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-390c101.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-390c101.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6cd19d3e1965aca5ab50fe2cc03c27d89cfac41 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-b6cd19d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-b6cd19d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f1ecd074d5dfb5a2e6ca526d29056f3cf992a23 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-2f1ecd0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-2f1ecd0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 958da3083e61f1ac955dd8321663e3cc1c7ef067 available at: https://gist.github.com/7a3be9a2148a2fab517854f156f6721c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-958da30.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9422-958da30.dmg

**Pull request closed without merging**
