### PR TITLE
Added First Run Checks for Flight Enable/Disable

### PR DESCRIPTION
**Pull request by r3tk0n**
Addresses MS#16206. Tested in desktop and HMD mode (with Vive Gen1) on Windows 10.

Added first-run checks for default flight behavior.

Flight should be enabled on first run in desktop mode.

Flight should be disabled on first run in HMD mode.

All subsequent runs should respect user preferences defined through system menu.

### CODE REVIEW

**Comment by r3tk0n** [comment]
**Test Plan:**
_Objective(s) and Expected Behavior:_ Confirm that flight is enabled on first run for users starting in desktop mode, while it is disabled on first run for users starting in HMD mode. Changes to preferences for flight should be respected after first run.

_Pre-requisites:_ Clean install of this build, with all folders in %appdata% purged (High Fidelity* folders in Local and Roaming).

**Part 1.)**
- Make sure headset is disconnected.
- Launch Interface.exe
- Confirm user can fly by double-tapping and holding the space bar.

**Part 2.)**
- Make sure headset is connected.
- Purge all High Fidelity files from %appdata% (Local and Roaming).
- Launch Interface.exe
- Confirm user cannot fly by double-tapping and holding the jump button on Oculus or Vive.
- Go into Menu -> Controls and enable flight by checking tick box.
- Exit Interface.exe
- Restart Interface.exe and confirm that the setting was preserved.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11076/HighFidelity-Beta-PR13527-4b9bc00.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11076/HighFidelity-Beta-PR13527-4b9bc00.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11076/HighFidelity-Beta-Interface-PR13527-4b9bc00.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11076/HighFidelity-Beta-PR13527-4b9bc00.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11076/HighFidelity-Beta-Interface-PR13527-4b9bc00.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

On machines with no HMD connected, interface started in desktop mode but flying was still disabled.

**Comment by r3tk0n** [comment]
Wondering if that had to do with Dante's PR, since I wrote this on an older branch. Going to investigate when I get into the office.

**Comment by wayne-chen** [comment]
closing this PR - recreating one without conflicts on the tip of master.

**Comment by wayne-chen** [comment]
Opened this [PR](https://github.com/highfidelity/hifi/pull/13533) as the replacement.

**Pull request closed without merging**
