### PR TITLE
some settings cleanup

### PR DESCRIPTION
**Pull request by ZappoMan**
- adds a description to the Send Data setting... the UI/layout is a little less than desirable.
- removes a setting that was not longer in use (HMD/UI horizontal angular size (degrees))
- moves another developer option into the hidden developer section (Octree/Max Packets per second)
- removes the LOAD DEFAULT SCRIPTS from the General settings, since this option is already on Running Scripts
- removes the Load Scripts from this directory setting, that didn't appear to actually do anything
- moves some obscure items for field of view and tablet in desktop scaling to the Developer/Advanced Settings preferences instead of being front and center

Addresses these recommendations: https://highfidelity.fogbugz.com/f/cases/11624/

# Test Plan:
- Make sure default scripts still work
- Make sure that if you've loaded your own custom scripts, they still work as expected on startup
- Make sure the items noted in fogbugz 11624 are moved or removed
- Make sure the Send Data setting has a description.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6508/app_12227_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6509/app_12227_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6509/HighFidelity-Beta-PR12227-ab9041bcab20c61468b83bd51202bba98df39c7f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6512/app_12227_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6512/HighFidelity-Beta-PR12227-4ad5d34a1078aabaf04743d607ebc1b0698117fb.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6595/app_12227_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6595/HighFidelity-Beta-PR12227-cb01bd14b955dc8967f00c148451eba20e807403.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6595/HighFidelity-Beta-PR12227-cb01bd14b955dc8967f00c148451eba20e807403.exe

**Pull request merged**
