### PR TITLE
Reworked wizard congratulation page.

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5071/HighFidelity-Beta-PR11851-1f23664c2f64e1dffda1350bacc6e7b80b0d16e7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5071/HighFidelity-Beta-PR11851-1f23664c2f64e1dffda1350bacc6e7b80b0d16e7.dmg

**Comment by Atlante45** [comment]
# Test Plan:
https://highfidelity.testrail.net/index.php?/cases/view/2192&group_by=cases:section_id&group_order=asc&group_id=447

Replace steps 18 & 19 with:
- Step: Click the `Copy` button.
    - Expected: the domain link is copied to your clipboard
- Step: Click the link
    - Expected: If Interface is installed, it should open and go to your domain.
                        If not, you should be sent to the High Fidelity download page in a new tab.
- Step: Click the `Visit Your VR World` button
    - Expected: If Interface is installed, it should open and go to your domain.
                        If not, you should be sent to the High Fidelity download page in a new tab.
- Step: Click the `Open Domain Settings` button
    - Expected: You should be taken to the domain settings page.

**Comment by Nex-Pro** [comment]
I have marked the testrail as PASSED but please read notes at step 18.

https://highfidelity.testrail.net/index.php?/tests/view/16610&group_by=cases:section_id&group_order=asc&group_id=447

I have previously mentioned that issue.

**Pull request merged**
