### PR TITLE
Squeezing bumper while distance grabbing now brings object to your hand in all cases

### PR DESCRIPTION
**Pull request by ericrius1**
If object has spatial key, it will come to your hand with correct position and rotation offset, as before. If it has no spatial key, it will appear in your hand with the rotation it had at the time of squeezing the bumper

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: eb44e54d87b15b8bc3846db3789dfbd01c6768b4 available at: https://gist.github.com/64b1a5dea0bfc2f92e76<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6771.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6771.dmg

**Comment by PhilipRosedale** [comment]
@ericrius1 - this works well in terms of bringing to the hand, but can we make it so that the object comes to the hand in the 'grabbed' state, rather than the 'equipped' state?  I think that if you are squeezing the trigger, you should be able to briefly touch the equip button to bring it to yourself.  If the object is equippable (like the gun) it should actually equip, but if it's just a normal physical thing, you should be able to release the bumper and then release the trigger, for example to throw it.  

Another thing we might want to try is to have a 'double grab' bring it to you as well... so that you can point at something and 'double tab' the trigger to bring it to you.  This seems worth trying as well.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb03eda6d1309c416168784734132ce222adec1b available at: https://gist.github.com/64b1a5dea0bfc2f92e76<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6771.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6771.dmg

**Comment by PhilipRosedale** [comment]
When I bumper grab, there is an abandoned overlay sphere.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 67f4c250fdd7e4e04012596bcab871926d44db48 available at: https://gist.github.com/64b1a5dea0bfc2f92e76<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6771.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6771.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f6e45d135effafe574782812beb0d122338bb45 available at: https://gist.github.com/64b1a5dea0bfc2f92e76<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6771.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6771.dmg

**Pull request merged**
