### PR TITLE
Maximum capacity

### PR DESCRIPTION
**Pull request by sethalves**
Add a domain-server setting which limits the number of users which can be connected at any point in time.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 610607e8e603ef2185ac41c2c2eb4fd7c024bba6 available at: https://gist.github.com/f401e61d95d1af181a2d<br/><br/>No installer was built for this commit

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4412ba916ea5b8a813b725f5308d63a517dc4544 available at: https://gist.github.com/f401e61d95d1af181a2d<br/><br/>No installer was built for this commit

**Comment by jherico** [comment]
Tested with my local server and a max connections of 1.  if I connect from my laptop first, I'm still able to connect from my desktop where I'm running the server.  If I connect from the desktop first, the laptop is unable to connect.  

However, there's no indication from the laptop of why the connection isn't completing, and based on the logs on the server, it retries every second.  I'd suggest opening a new issue to update interface both with UI feedback that a connection couldn't be made (ideally with information as to why) and that interface switch to an exponential falloff on the retries so that a bunch of clients trying to connect to a full server don't end up spamming them with connection requests, thus making a resource constrained system suffer even more.

**Comment by sethalves** [comment]
I see that the domain server sends a PacketTypeDomainConnectionDenied 
packet when it declines to let an interface connect.  Maybe that message 
would be modified to include a reason?

     -seth

**Comment by cozza13** [comment]
I was testing this. Is there a way to give the user some visual indication that the domain is over capacity? Also leave the person in their current location.

**Comment by sethalves** [comment]
--> https://github.com/highfidelity/hifi/pull/4478

**Pull request merged**
