### PR TITLE
fixed log spamming from windowRoot.qml in toolbar mode

### PR DESCRIPTION
**Pull request by druiz17**
prevent windowRoot.qml from spamming the login toolbar mode

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in toolbar mode and open up you logs
- with no app windows open...your logs should not be getting spammed from windowRoot.qml

**Comment by YuppyPlays** [comment]
Will test when built :)

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1412/HighFidelity-Beta-PR10904-b0130896d1f8b68a069df9f56526859e4f0dd870.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1412/HighFidelity-Beta-PR10904-b0130896d1f8b68a069df9f56526859e4f0dd870.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

No spamming in logs relating to what I can see :) **Pass**

**Pull request merged**
