### PR TITLE
Stuttering: Upgrade GLM & add GLI integration

### PR DESCRIPTION
**Pull request by jherico**
This PR integrates the GLI framework by the same group that created and maintains GLM.  GLI is a wrapper for encapsulating texture data with good support for many formats as well as for loading and saving KTX and DDS formats (which can store textures in a format much easier to load into the GPU without pre-processing).

In order to support GLI, the version of GLM needed to be updated requiring some minor tweaks to the existing GLM usage.  

## Testing

Functionality should be identical to the existing production build.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d5028932bbbbd88a52d843416b7c11a374b872ca available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-d502893.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-d502893.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b5ced4568778aa315afc63d1ef834a78fa47cc6 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-1b5ced4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-1b5ced4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25303ad56e2a51d4661546766d01c16f0a2c95e0 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-25303ad.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-25303ad.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6598610067fc5fb9b256a266a5a1b860a13f989 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a659861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a659861.dmg

**Comment by Nex-Pro** [comment]
Noticed that the avatar now has a blue sphere at it's center that becomes visible when jumping or changing avatar. 

I disabled rendering of avatar mesh and observed that the sphere diappears when the mouse pointer is over a U.I. element or the stats. I could not locate a debug setting in the advanced menus for this.

In hmd mode each hand was accompanied by a blue sphere at the laser start position.

Apart from that nothing else noticed. 

hifi-snap-by-piper-peppercorn-on-2016-09-07_14-48-52
Are there any more specific tests required.

Also left this running for about an hour without issue.

Interface exited cleanly.

8569_blue_sphere

**Comment by hifi-gustavo** [comment]
Build console output for commit: a458d699b931a452003690db8a093449dffa3c05 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a458d69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a458d69.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6598610067fc5fb9b256a266a5a1b860a13f989 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a659861.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-a659861.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3ca3b0cbb61cf09793abde2cf1285d613d0984f available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-f3ca3b0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-f3ca3b0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b9213751fb78e95ecd81f6635077c764758cdd19 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-b921375.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-b921375.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cd12656940ecacf5d439b88d8e28776d8f9584f available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-0cd1265.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-0cd1265.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9e4bd55794c862df53e96da0d8c36077e644266 available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-e9e4bd5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-e9e4bd5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3d703b02fc8a446608b10c6fbf2aca9009c3fdd available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-e3d703b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-e3d703b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5963aaad3211fd7377c346155813d3fc70f613fe available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-5963aaa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-5963aaa.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbde3af0d427655cb197dc7e69519f8f1840c3ae available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-bbde3af.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-bbde3af.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ecfe56085db9314c3b7f65d7ddd8f414e8b88b9d available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-ecfe560.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-ecfe560.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ecfe56085db9314c3b7f65d7ddd8f414e8b88b9d available at: https://gist.github.com/c4dc2fae51fcfce9dac6370121e47fde<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-ecfe560.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8569-ecfe560.dmg

**Pull request merged**
