### PR TITLE
Android - Refresh domains list with swipe

### PR DESCRIPTION
**Pull request by Cristo86**
One of the proposals for the domains list.

**Test Plan:**

1. Start the app
2. Should load a list of domains
3. (Optional but recommended) untag one of the appearing domains in its server settings page (remove 'mobile' tag)
4. Refresh by swiping down (Android standard way to refresh lists)
5. List should reload
6. (Optional but recommended) if any domain had removed its mobile tag, a domain was deleted or a new domain (tagged with mobile) was created, that change should be reflected in the list.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11306/HighFidelity-Beta-PR13609-bdd6f3c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11306/HighFidelity-Beta-PR13609-bdd6f3c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11306/HighFidelity-Beta-Interface-PR13609-bdd6f3c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11306/HighFidelity-Beta-PR13609-bdd6f3c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11306/HighFidelity-Beta-Interface-PR13609-bdd6f3c.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Pass @conklin94122 @Qliemillar @qliacoombs 

Domains refresh with a swipe.
Sandbox with 'mobile' tag appears and disappears correctly.

Android Smoke passed
Windows Smoke passed

**Pull request merged**
