### PR TITLE
Changed laser appearance threshold and oculus touch click threshold

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2536/HighFidelity-Beta-PR11199-556f7c1cb3d04bbe080422620308f0af9a51ff28.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2536/HighFidelity-Beta-PR11199-556f7c1cb3d04bbe080422620308f0af9a51ff28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2540/HighFidelity-Beta-PR11199-5c772d60cd744ce9604b6b7bf26d9fcba138bedd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2540/HighFidelity-Beta-PR11199-5c772d60cd744ce9604b6b7bf26d9fcba138bedd.exe

**Comment by samcake** [comment]
@druiz17 is behind my shoulder and tells me we can close this one...

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3189/HighFidelity-Beta-PR11199-ff8790fa938aee6f450c6056d0171d577d2ab122.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3189/HighFidelity-Beta-PR11199-ff8790fa938aee6f450c6056d0171d577d2ab122.exe

**Pull request closed without merging**
