### PR TITLE
Disable viewpoint menus in hmd

### PR DESCRIPTION
**Pull request by howard-stearns**
When in HMD, the menu items for views other than first-person are disabled. You can still use the keyboard toggles ('h', and 'p') to go in and out of different points of view.

Also exposes menu enable/disable to scripts.

### CODE REVIEW

**Comment by howard-stearns** [comment]
Partially addresses https://highfidelity.fogbugz.com/f/cases/2259/in-HMD-3rd-person-lasers-can-t-reach-the-HUD

**Comment by howard-stearns** [comment]
test plan:

In HMD, the sub menu items above the separator, within the View menu, should all be disabled -- except for "First Person".   (This should apply in both the application menu that you can't really see in HMD, and to the right click menu.) However, the keyboard toggles (h for mirror, p for 1st/3rd person) should still work in hmd, as well as the mouse wheel.
Switching to desktop should allow them again.

It should not matter whether the HMD switching is done via the "switch" toolbar button or the Display menu.

Note: if you go to any non-first-person view while in desktop, the act of switching should put you back in first-person.  That's true in master, and this PR doesn't change that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b20d4a4b030b526e93587ad3a7adc40e7652693a available at: https://gist.github.com/1cb5dfc7365e0aa56f8b5c81fe0e490a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9048-b20d4a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9048-b20d4a4.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: b20d4a4b030b526e93587ad3a7adc40e7652693a available at: https://gist.github.com/1cb5dfc7365e0aa56f8b5c81fe0e490a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9048-b20d4a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9048-b20d4a4.dmg

**Comment by zfox23** [comment]
Code looks good to me; QAing now.

**Comment by zfox23** [comment]
QA passes. Tried lots of combinations of going in/out of HMD and attempting to select various View modes - all successful.

**Pull request merged**
