### PR TITLE
Trying to resolve QML / Audio deadlocks

### PR DESCRIPTION
**Pull request by jherico**
Something in the QML interaction with the Audio scripting interface seems to be triggering a deadlock.  On the suspicion that it has something to do with the manual interaction with the QML bindings, I've produced an alternative method of interaction.  Instead of the QML explicitly assigning to the 'selected' member of the item from the `AudioDeviceList`, it now calls a new function `Audio.setInputDevice()` and relies entirely on the feedback from the AudioClient when the device changes to modify the UI (specifically the checkbox in the Audio dialog).

Note, the exact nature of the deadlock is not well understood other than that it doesn't seem to occur on Qt 5.9 and it seems to be tied to assigning to values of the objects fetched from the AudioDeviceList.

Additionally, this fixes the issue with non-default audio devices not persisting between sessions.

## Testing

Open the Audio settings dialog on a system that has been experiencing deadlocks in this fashion.  Try switching between inputs and outputs.  On this build it should not deadlock.  

Also, once in the Audio dialog, selecting non-default audio devices and exiting the application should retain those selections when restarting the application.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1734/HighFidelity-Beta-PR10985-aab56cf2a9c6e741a8bb782ec3382bdd15048feb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1734/HighFidelity-Beta-PR10985-aab56cf2a9c6e741a8bb782ec3382bdd15048feb.exe

**Comment by sethalves** [comment]
On jazmin's machine, with a Qt 5.6 build, master deadlocks every single time I change audio input devices.  With this PR, there's no deadlock.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1740/HighFidelity-Beta-PR10985-d43432bd7127c5ec08959cbd2d7fb6ef5149e809.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1740/HighFidelity-Beta-PR10985-d43432bd7127c5ec08959cbd2d7fb6ef5149e809.dmg

**Comment by ZappoMan** [comment]
Note to QA -- this PR changes how several different objects interact with each other across threads... to the best of your ability, you should smoke test this PR while hitting it from all directions... for example, you should 
- try writing a bunch of scripts that use the published audio APIs to set and get values... 
- add/remove audio devices from Windows (unplug them, disable them in the control panel)
- switch the UI settings
Try to do all of this at the same time... pound on it!

**Comment by CainFoool** [comment]
Testing now.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
try writing a bunch of scripts that use the published audio APIs to set and get values... | Pass
add/remove audio devices from Windows (unplug them, disable them in the control panel) | Pass
switch the UI settings | Pass

This is a Pass - however I did notice that when you had an Audio Device set as the default and unplug and replug it, it doesn't get re-initialized. This applies to both the input and output devices. 

As I can replicate this bug in Master, this isn't a QA Fail from me but something which should probably be fixed in the future.

I didn't write a script but I was going through some of the methods in the Audio.cpp class in the console ensuring that values were getting and setting correctly and persisting upon restarts - all was good from there.

I stress tested unplugging and replugging in devices with the Audio Dialog open and closed, everything was working as expected and showing up the devices after about a second or so of a delay. Assuming this is just the timer which is checking for plugged in devices.

In addition I did the same in HMD, and functionality was the same.

Let me know if this needs to be dug into deeper.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by ZappoMan** [comment]
@CainFoool - I want to confirm that you tried REALLY HARD to cause deadlocks...

The recipe for this that I'm recommending is that you need to attempted to do all of the following things **at the same time**....

- multiple scripts running in tight loop or update accessing the Audio API
- windows changing devices underneath you (this will cause timers on audio thread, and spawned thread pool jobs [random threads])
- QML for Audio Settings visible (theoretically these checkboxes will be changing on you visually)
- Clicking on the Audio Settings

Some how manage to do all that at the same time, over and over again, trying to catch a race condition.

How long did you hammer on this?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1749/HighFidelity-Beta-PR10985-9f13533560bc6e425ba688b632e1827cad7edc4b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1749/HighFidelity-Beta-PR10985-9f13533560bc6e425ba688b632e1827cad7edc4b.dmg

**Pull request merged**
