### PR TITLE
RC69: avatars collide again (again, for reals this time)

### PR DESCRIPTION
**Pull request by AndrewMeadows**
https://highfidelity.fogbugz.com/f/cases/14431/Avatars-should-not-be-able-to-walk-through-each-other

* clamp minimum dynamic mass for physics simulation stability
* compute mass of avatars more correctly (again)

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
**Test Plan:**

**(1)** Login with Mac to a domain with other avatars and try see if you crash

**(2)** Use **Edit--> Reload Content (Clears all caches)** several times to force rebuilding of other avatars in the physics simulation.  Do you crash?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10696/HighFidelity-Beta-PR13412-085130e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10696/HighFidelity-Beta-PR13412-085130e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10696/HighFidelity-Beta-Interface-PR13412-085130e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10696/HighFidelity-Beta-PR13412-085130e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10696/HighFidelity-Beta-Interface-PR13412-085130e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Mac does not crash!!!

**Comment by AndrewMeadows** [comment]
I did see one crash on Mac at EOD yesterday when I logged in with a second user.  After I added some debugging code I was unable to reproduce the crash.

**Comment by AndrewMeadows** [comment]
I may have a repro for this crash: UserA may crash when UserB shows up using HMD.  The NaN I saw is being introduced by `SpatiallyNestable::getWorldAngularVelocity()`.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10736/HighFidelity-Beta-PR13412-4680ba1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10736/HighFidelity-Beta-PR13412-4680ba1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10736/HighFidelity-Beta-Interface-PR13412-4680ba1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10736/HighFidelity-Beta-PR13412-4680ba1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10736/HighFidelity-Beta-Interface-PR13412-4680ba1.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Did not crash when user join and when reloading content.

**Pull request merged**
