### PR TITLE
Added tablet notifications.

### PR DESCRIPTION
**Pull request by druiz17**
post a notification when a modal dialog is created for the tablet

### CODE REVIEW

**Comment by druiz17** [comment]
Test Plan
- Be in tablet mode in either desktop or HMD
- open up goto screen and enter an incorrect location
- you should see a notification saying "tablet needs your attention"

**Comment by hifi-gustavo** [comment]
Build console output for commit: a5f1fb9e9a3124b73f751c167fb1a7147e840c8f available at: https://gist.github.com/7c475e6f6c43e77e894b855a44aefa59<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9904-a5f1fb9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9904-a5f1fb9.dmg

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9904-a5f1fb9.exe

FAIL:
- The notification does not say, "tablet needs your attention".
- The notification says, "There is no address information for that user or place".

**Comment by druiz17** [comment]
@claudioshg I should have been more specific. The notification does not appear on the tablet. The notification appears on the top right window in desktop mode.

**Comment by claudioshg** [comment]
@druiz17 
I looked at it again, and yes there is a notification that appears on the top right window area in desktop mode that says, "tablet needs your attention".

**Pull request merged**
