### PR TITLE
Fix and improve currentAPI.js

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.fogbugz.com/f/cases/9234/
https://highfidelity.fogbugz.com/f/cases/8149/
https://highfidelity.fogbugz.com/f/cases/9311/

The script <b>currentAPI.js</b> was failing due to the limitations on the maximum size allowed by javascript strings. 
This PR fixes this problem, and provides some user interaction with the current API methods using a QML interface.

currentapi
# Features
- Search bar
- Fast filter by parent object
- Method evaluation
- Real-time debugging
- Script debugging 
 
# Test Plan

## Open script
- Activate the <b>Developer Menus</b> and open <b>Developer > API Debugger</b>. A window should appear on the screen showing a list of the different available methods. 

## Copy to clipboard
- Click on the <b>Copy to clipboard</b> button (left-bottom side).
- Paste on an empty text file and it should show all the methods on the list.

## Search
- Add <b>“camera orientation”</b> (without quotes) to the search field and press enter on your keyboard. The list should be filtered appropriately. 

## Navigation and Reload
- Double click on <b>Camera.frustum.orientation.x</b>. The list should now show only this method.
- Click on the <b>◄</b> button. This should go up the tree and show <b>Camera.frustum.orientation.x</b>, <b>Camera.frustum.orientation.y</b>, <b>Camera.frustum.orientation.z</b> and <b>Camera.frustum.orientation.w</b>. 
- Look around to change the camera’s orientation and click the <b>Reload</b> button to update the values on the list.

## Live debugging
- Click the <b>Play</b> button. Look around to change the camera’s coordinates and make sure the <b>Camera.frustum.position</b> values update live on the list.
- While debugging, open the log. All these updates should be written to the log.

## Add new lines of code
- Search for the expression <b>“can ori”</b> (without quotes) by clicking the search button.
- Double click on <b>Camera.getOrientation</b> to isolate it.
- On the search bar, write <b>Camera.getOrientation().x</b> and click the plus button. A new line should be added to the list. Do the same with <b>Camera.getOrientation().y</b> and <b>Camera.getOrientation().z</b>
- Look around to change the camera’s orientation and click the <b>Reload</b> button. This should update the values of the new lines added to the list.
- Click the <b>Play</b> button. Look around to change the camera’s coordinates and make sure the values continuously update.

## Script debugging
- Create a file called <b>debugging_test.js</b> and add this code to it:
```
(function(){
	var varsToDebug = {
		increase: 0,
		decrease: 0
	}
	Script.registerValue("GlobalDebugger", varsToDebug);
	Script.update.connect(function(){
		varsToDebug.increase += 1;
		varsToDebug.decrease -= 1;
	});
}());
```
- Click <b>Debug Script</b> and select the file <b>debugging_test.js</b>. The list should update and display the increase and decrease variables.
- Click <b>Reload</b> to update the values.
- Click <b>Play</b> for live update.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5778/app_12039_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5778/HighFidelity-Beta-PR12039-54297e00a8038c3f6e9e15d0f53be85918ee9209.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5778/HighFidelity-Beta-PR12039-54297e00a8038c3f6e9e15d0f53be85918ee9209.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5798/app_12039_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5798/HighFidelity-Beta-PR12039-38bfddf78647d8e0c1ce9af533f5348fe86e4201.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5798/HighFidelity-Beta-PR12039-38bfddf78647d8e0c1ce9af533f5348fe86e4201.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed

## Open Script
Test | Result
--- | ---
Activate the Developer Menus and open Developer > API Debugger. A window should appear on the screen showing a list of the different available methods. | 👍 

## Copy to clipboard
Test | Result
--- | ---
Click on the Copy to clipboard button (left-bottom side). | 👍 
Paste on an empty text file and it should show all the methods on the list. | 👍 

## Search
Test | Result
--- | ---
Add “camera orientation” (without quotes) to the search field and press enter on your keyboard. The list should be filtered appropriately. | 👍 

## Navigation and Reload
Test | Result
--- | ---
Double click on Camera.frustum.orientation.x. The list should now show only this method. | 👍 
Click on the ◄ button. This should go up the tree and show Camera.frustum.orientation.x, Camera.frustum.orientation.y, Camera.frustum.orientation.z and Camera.frustum.orientation.w. | 👍 
Look around to change the camera’s orientation and click the Reload button to update the values on the list. | 👍 

## Live debugging
Test | Result
--- | ---
Click the Play button. Look around to change the camera’s coordinates and make sure the Camera.frustum.position values update live on the list. | 👍 
While debugging, open the log. All these updates should be written to the log. | 👍 

## Add new lines of code
Test | Result
--- | ---
Search for the expression “can ori” (without quotes) by clicking the search button. | 👍 
Double click on Camera.getOrientation to isolate it. | 👍 
On the search bar, write Camera.getOrientation().x and click the plus button. A new line should be added to the list. Do the same with Camera.getOrientation().y and Camera.getOrientation().z | 👍 
Look around to change the camera’s orientation and click the Reload button. This should update the values of the new lines added to the list. | 👍 
Click the Play button. Look around to change the camera’s coordinates and make sure the values continuously update. | 👍 

## Script debugging
Test | Result
--- | ---
Create a file called debugging_test.js and add this code to it: `...` | 👍 
Click Debug Script and select the file debugging_test.js. The list should update and display the increase and decrease variables. | 👍 
Click Reload to update the values. | 👍 
Click Play for live update. | 👍 

### Solid Pass!

**Comment by misslivirose** [comment]
Implementation of new developer tools should align with the style guidelines that we have for windows and dialog boxes - functionality looks good, though without reading all the testing steps individually it's not clear what each of the buttons do or how to use it currently without a reference.

**Comment by tapalisa** [comment]
http://hifi-content.s3.amazonaws.com/alan/dev/UI%20Toolkit%2020160505.pdf

**Comment by sethalves** [comment]
@tapalisa do you want specific changes made before this is merged?

**Pull request merged**
