### PR TITLE
add account sign up to Interface

### PR DESCRIPTION
**Pull request by birarda**
- added a button to Log In dialog that allows creation of a High Fidelity account
- added a spinner to Log In and Sign Up dialogs

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

This PR leverages a new API for account creation so that users can create new High Fidelity accounts from Interface. It also touches some of the existing Log In / Steam Sign Up flow.

##### Basic Sign Up
1. Test the creation of an account by clicking on the "Sign Up" button that is now present on the Log In dialog. You should be able to successfully create an account and you should be logged in.
2. Enter invalid or non-unique data in the email/username fields and confirm that you see form errors at the top of the sign up form.
3. Confirm that you see a spinner while you signing up, after clicking the "Sign Up" button.
4. Log out and log back in with your newly created account.
5. Confirm that you receive an email to confirm the email for your new account.

#### Log In

1. Log in with an existing account. Confirm all works as expected and that you briefly see a spinner while waiting after clicking the "Log In" button. 

#### Steam
1. Test log in and fresh account creation from Steam. Contact me if you need assistance removing a connection between your Steam account and High Fidelity account so that you can test fresh account creation from Steam.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80699e826a2cc557a775eb1b760a452e3c3295f9 available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-80699e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-80699e8.dmg

**Comment by Nex-Pro** [comment]
In progress.

**Comment by Nex-Pro** [comment]
Basic Sign Up

Test the creation of an account by clicking on the "Sign Up" button that is now present on the Log In dialog. You should be able to successfully create an account and you should be logged in. **SUCCESS**

Enter invalid or non-unique data in the email/username fields and confirm that you see form errors at the top of the sign up form.  **SUCCESS**

Confirm that you see a spinner while you signing up, after clicking the "Sign Up" button.  **SUCCESS**

Log out and log back in with your newly created account.  **SUCCESS**

Confirm that you receive an email to confirm the email for your new account.
Log In  **SUCCESS**

Log in with an existing account. Confirm all works as expected and that you briefly see a spinner while waiting after clicking the "Log In" button.  **SUCCESS**

@birarda  Let me know what I need to do to complete Steam part.
Steam

Test log in and fresh account creation from Steam. Contact me if you need assistance removing a connection between your Steam account and High Fidelity account so that you can test fresh account creation from Steam.

**Comment by RyanDowne** [comment]
Signing up with Touch controllers worked

**Comment by Nex-Pro** [comment]
### PASS

Completed tests with Birada

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0f10d837cee60e96d6d89158c6babe7195e1f01 available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-f0f10d8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-f0f10d8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 691ce4312eeef75e479fc95abcc954044d85e2b8 available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-691ce43.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-691ce43.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0663bdf3161618d2ffc6e01dfe519ea682035c5 available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-a0663bd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-a0663bd.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0473ed29f6a6b8e2bebdd3e63f1b7078dc2162be available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-0473ed2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-0473ed2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5111256a9ed2793abb78e7669702102959a4bf94 available at: https://gist.github.com/5cf97aef3c28db96dfcc34b2dc168157<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-5111256.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9175-5111256.dmg

**Pull request merged**
