### PR TITLE
DO NOT MERGE: Work in progress, optimizing the gpu::Buffer transfer

### PR DESCRIPTION
**Pull request by samcake**
Work in progress, early tests together with Howard

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1edf043dd418896f84f6097a9a4e0710870b1251 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54612b79640804c65730265260f7d3d847fb2de2 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c88fe3594c74e43dd6c52bc0050900b183dd7fc3 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfa55f87eee11ad2ba2737f3adcc8e8f070744a7 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4f61ef52bd5110ce1adf1d65fe600bae76fbceac available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4d45a359b7936397b34eb6e9a33db778f18384d5 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 60ffab7fc18fd951a1c4d409b84acbb1a91eaa65 available at: https://gist.github.com/459c5604c6177d890f06<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6358.dmg

**Comment by ZappoMan** [comment]
Closing until Sam has time to work on this again.

**Pull request closed without merging**
