### PR TITLE
Beta Release 31 - Includes up to Developer Release 5876

### PR DESCRIPTION
**Pull request by ZappoMan**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

- People Action List
- Fix competition between seek mouse and lasers 
- Log dialog doesn't float on top 
- Simple chair script 
- Use a higher thread priority for Oculus present 
- High Dynamic Range Audio injectors 
- Script to push things with your hands 
- Add support for new Touch grip mappings to tutorial 
- Fix settings hitch 
- Expose dropped frames count to stats UI 
- Personal mute; Quasi-ignore; Reversible PAL actions 
- Improve performance of Entities.callEntityMethod() 
- Factor out render item fetch/sort/cull 
- Faster HRTF 
- Add background to forward rendering path 
- more precise use of timers 
- Use supplied libquazip5.so for Debug builds 
- fix bitrot in unit tests 
- Track dropped frames as reported by the Oculus SDK 
- Improved audio resampler 
- Optimizations: using SIMD matrix operations to improve skinned model calculations 
- fix animated entities 
- quiet some warnings 
- Ambisonic limiter 
- optimization of incoming avatar joint data in interface client 
- fix a crash and a memory leak in vhacd-util 
- Fix "Running Scripts" window being inaccessible 
- Ambisonic rotation 
- fix GL 4.5 when glTextureSubImage2DEXT unavailable 
- Halve the space bubble audio volume 
- less noisy measure of avatar processing performance metric 
- Working on test/trace script interface 
- debug window enhancements 
- cleanup avatar data code to include better documentation 
- Optimize avatar-mixer bandwidth for out of view avatars 
- measure avatar processing stats in Chrome trace framework 
- Only send machine fingerprint when not logged in 
- add Oculus Touch friendly grab and equip 
- Fix idententity packet in AC 
- Entity script for ambisonic sound emitter 
- Additional work on tracing
- Show Usernames to Admins in PAL
- Adding Machine Fingerprint to Domain Server permissions
- Introducing a fix for the overlayered model drawn in front
- Clara.io marketplace improvements
- Expose Machine Fingerprint in PAL
- Session display names
- Updates to tracing, removing log spam
- Logging improvements

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b432ffa78d3714001d8243295a81bffc11297885 available at: https://gist.github.com/661d1622d6c521bb88dd10cfbc8a1a2c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9330-b432ffa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9330-b432ffa.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SERVER DOWN
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** UNTESTED
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. Unable to test on ```dev-demo``` as server was down but it is not a fail. Ignore the values in the below chart as I forced the test anyway to see the results however domain was offline.  Brillant execution of the new welcome tutorial for VR. Successfully tested on the Oculus and Oculus Touch.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |293 |415 |504
**Present Rate**: |292 |415 |502
**Present New Rate**: |240 |202 |390
**CPU Buffer Count**: |2251 |2130 |679
**GPU Buffer Count**: |694 |406 |177
**CPU Memory Usage**: |28988688 |22126992 |15697680
**GPU Memory Usage**: |16348592 |8865200 |7706032
**CPU Texture Count**: |244 |114 |79
**GPU Texture Count**: |209 |73 |66
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |70427644 |79047952 |42216720
**GPU Texture Memory Usage**: |636945047 |230671435 |216340902
**GPU Virtual Memory Usage**: |636945047|230671435|216340902
**Triangle Count**: |262130 |390719 |50809
**Triangle Rate**: |43688333 |78143800 |25404500
**API Drawcall Count**: |167 |132 |20
**Drawcall Count**: |173 |175 |20
**Drawcall Rate**: |28833 |35000 |10000
**State Changes Texture Count**:|332 |145 |44
**Pipeline Count**: |57 |40 |27
**Item Opaques**: |257 |294 |10
**Item Translucents**: |100 |24 |28
**Item Lights**: |10 |48 |0
**Timing Opaques**: |0.925 |1.189 |0.078
**Timing Translucents**: |0.162 |0.062 |0.058
**Timing Lighting**: |0.015 |0.029 |0.025
**Render Frame**: |1.825 |2.431 |0.842


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Grab objects in dev-demo|SUCCESS

**Comment by Nex-Pro** [comment]
Still testing

**Comment by cozza13** [comment]
I just changed test 10 to be testing of PAL

**Comment by OmegaHeron** [comment]
CPU/GPU/Memory utilization complete with no negative changes detected.  Will come back with QA Script results in a bit.

**Comment by OmegaHeron** [comment]
QA Fail 

Desktop mode, keyboard mouse.  Open asset browser - attempt to use mouse to select a model - won't select making it available for add to world action.

It's a very odd fail - you can double click a folder in ATP browser and it will expand/contract it.

**Comment by OmegaHeron** [comment]
Disregard fail - it was a bad interaction between having virtual desktop application running while Interface is active (I had forgotten virtual desktop was running -- it's an app that projects your desktop into HMD space).  Continuing onward with QA script now.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Desktop mode - 1600x900 maximized window

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |60 |60 |
**Present Rate**: |60 |60 |
**Present New Rate**: |60 |60 |
**CPU Buffer Count**: |2614 |4145 |
**GPU Buffer Count**: |800 |1285 |
**CPU Memory Usage**: |35190736 |63689808 |
**GPU Memory Usage**: |20633712 |43542640 |
**CPU Texture Count**: |325 |292 |
**GPU Texture Count**: |268 |251 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |116501680 |172231952 |
**GPU Texture Memory Usage**: |761549086 |1114350105 |
**GPU Virtual Memory Usage**: |761549086|1114350105|
**Triangle Count**: |265524 |835634 |
**Triangle Rate**: |16595250 |52227125 |
**API Drawcall Count**: |181 |265 |
**Drawcall Count**: |1717 |308 |
**Drawcall Rate**: |107312 |19250 |
**State Changes Texture Count**:|371 |310 |
**Pipeline Count**: |61 |35 |
**Item Opaques**: |263 |446 |
**Item Translucents**: |107 |38 |
**Item Lights**: |11 |45 |
**Timing Opaques**: |1.114 |1.751 |
**Timing Translucents**: |0.211 |0.054 |
**Timing Lighting**: |0.021 |0.02 |
**Render Frame**: |1.918 |3.142 |

DK2

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |75 |75 |
**Present Rate**: |75 |75 |
**Present New Rate**: |74 |75 |
**CPU Buffer Count**: |2792 |4240 |
**GPU Buffer Count**: |867 |1247 |
**CPU Memory Usage**: |36653904 |64930896 |
**GPU Memory Usage**: |21944432 |36915312 |
**CPU Texture Count**: |331 |296 |
**GPU Texture Count**: |278 |233 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |74181808 |219745552 |
**GPU Texture Memory Usage**: |999602684 |1295431150 |
**GPU Virtual Memory Usage**: |999602684|1295431150|
**Triangle Count**: |549302 |1729547 |
**Triangle Rate**: |42254000 |133042076 |
**API Drawcall Count**: |188 |284 |
**Drawcall Count**: |5988 |640 |
**Drawcall Rate**: |460615 |49230 |
**State Changes Texture Count**:|384 |330 |
**Pipeline Count**: |61 |37 |
**Item Opaques**: |271 |475 |
**Item Translucents**: |111 |49 |
**Item Lights**: |11 |47 |
**Timing Opaques**: |1.164 |1.804 |
**Timing Translucents**: |0.211 |0.07 |
**Timing Lighting**: |0.02 |0.03 |
**Render Frame**: |2.024 |3.524 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|dev-demo no longer exists.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested.
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Covered basics of PAL using 2nd AV from LAN machine -- it works as expected from my previous testing of PAL and the new features I'm familiar with work as described.

Secondary tests.  Ubuntu Linux Interface/Stack, compile/install/run = Pass

QA Pass overall.

**Comment by nbq** [comment]
Testing this now

**Comment by claudioshg** [comment]
Windows 10 - Oculus CV1 - i7 6700k CPU - GTX1070 GPU 

## QA Test
**QA Tester**: claudioshg
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:


**Domain** | |dev-playa |
---|---|---|---
**Render Rate**: | |0 |
**Present Rate**: | |0 |
**Present New Rate**: | |0 |
**CPU Buffer Count**: | |1098 |
**GPU Buffer Count**: | |359 |
**CPU Memory Usage**: | |7783504 |
**GPU Memory Usage**: | |5064816 |
**CPU Texture Count**: | |79 |
**GPU Texture Count**: | |53 |
**GPU Transfer Count**: | |0 |
**CPU Texture Memory Usage**: | |37784848 |
**GPU Texture Memory Usage**: | |238170022 |
**GPU Virtual Memory Usage**: ||234876672|
**Triangle Count**: | |234382 |
**Triangle Rate**: | |78127333 |
**API Drawcall Count**: | |103 |
**Drawcall Count**: | |146 |
**Drawcall Rate**: | |48666 |
**State Changes Texture Count**:| |96 |
**Pipeline Count**: | |34 |
**Item Opaques**: | |303 |
**Item Translucents**: | |36 |
**Item Lights**: | |41 |
**Timing Opaques**: | |0.726 |
**Timing Translucents**: | |0.04 |
**Timing Lighting**: | |0.022 |
**Render Frame**: | |1.879 |


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|SUCCESS
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|undefined
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|SUCCESS

QA Pass

**Comment by Nex-Pro** [comment]
**PR #9330 Beta RC 31**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

**Leap Motion:** Not used


## QA Test

**QA Tester**: Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: ** SUCCESS **
**localhost ATP Upload + Edit Result**: ** SUCCESS **
**Echo Server Audio**:  ** SUCCESS **
**localhost 'harmonicOscillator.js' Result**: UNTESTED
**localhost 'reverbTest.js' Result**: ** SUCCESS **
**localhost 'playaPerformanceTest.js' ** SUCCESS **
**dev-playa 'playaPerformanceTest.js' ** SUCCESS **
**dev-demo 'playaPerformanceTest.js' DOMAIN UNAVAILABLE
**QA Pass**: ** SUCCESS **
**Additional Test Results + Observations**: 

Mouse pointer appears unexpectedly on multiple occasions when using lasers.



**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |89 |90
**Present New Rate**: |89 |90 |87
**CPU Buffer Count**: |2599 |4349 |687
**GPU Buffer Count**: |837 |1334 |183
**CPU Memory Usage**: |39296048 |67548240 |13425104
**GPU Memory Usage**: |21678192 |45226096 |7948400
**CPU Texture Count**: |263 |285 |78
**GPU Texture Count**: |220 |248 |72
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |119975088 |207490320 |13831440
**GPU Texture Memory Usage**: |917846937 |1390458414 |495924782
**GPU Virtual Memory Usage**: |926966745|1404089492|517540575
**Triangle Count**: |523121 |273309 |54460
**Triangle Rate**: |58124555 |24846272 |4950909
**API Drawcall Count**: |184 |96 |16
**Drawcall Count**: |3342 |420 |18
**Drawcall Rate**: |371333 |38181 |1636
**State Changes Texture Count**:|356 |141 |36
**Pipeline Count**: |68 |34 |23
**Item Opaques**: |260 |144 |3
**Item Translucents**: |112 |14 |2
**Item Lights**: |11 |28 |0
**Timing Opaques**: |1.067 |0.772 |0.114
**Timing Translucents**: |0.19 |0.025 |0.042
**Timing Lighting**: |0.031 |0.025 |0.038
**Render Frame**: |2.085 |2.206 |1.358


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|CHECK: dev-demo down
**Test 2**|Install a fresh copy of "Home' and do tutorial|** SUCCESS **
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|** SUCCESS **
**Test 4**|Launch firework, on dev-playa, can other hear?|** SUCCESS **
**Test 5**|Switch avatar and make sure it does not crash|** SUCCESS **
**Test 6**|Test group functions| **SUCCESS**
**Test 7**|Test Ambisonic audio with markeplace item|** SUCCESS **
**Test 8**|Enrure that you can distance grab|** SUCCESS **
**Test 9**|Bring up and edit an objects with hand controllers| **FAIL**
**Test 10**|Grab objects in dev-demo| domain unavailable
**Test 11**|Test PAL functionality| **SUCCESS**


Avatar scaling via Vive grips works as expected.

Dev demo unavailable for Stats.

Clara IO from market works fine. Assets downloaded to ATP and appear in domain and asset list.

### PAL tests:

mute: ** SUCCESS **
ignore: ** SUCCESS **
silence: ** SUCCESS **
ban: ** SUCCESS **

last edited orange bounding box highlighting: **SUCCESS**

Error message for multiple editors ( pal icon in edit panel ) : **SUCCESS**
last editor by entity ( pal icon in edit panel ) : **SUCCESS**
last edited by avatar ( click on avatar sphere) : **SUCCESS**
last edited by avatar (click on PAL list entry) : **SUCCESS**


Group tests: Extensive tests of group functions no issues seen.

Additional: Some tests carried out on AMD processor PC. worked fine (third client ) ( desktop mode )


### FAILS:

Editing an entity with hand controllers: No qml keyboard so unable to enter text.

Grip entity scaling only works with entities held in left hand. CONFIRMED with 2 separate accounts/PCs.

**Pull request merged**
