### PR TITLE
Redesign and enable hand's Pole Vectors for elbow simulation

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR redesign and enables the pole vector's that determine the correct position of the elbows.
It fixes the issue where the arms end up inside the body when the user crosses arms or they leave the controls on the desk.

 https://highfidelity.manuscript.com/f/cases/16758/Elbows-Penetrating-the-Body-of-Humanoid-Avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11499/HighFidelity-Beta-PR13672-9d2d7c3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11499/HighFidelity-Beta-PR13672-9d2d7c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11499/HighFidelity-Beta-Interface-PR13672-9d2d7c3.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11505/HighFidelity-Beta-PR13672-4a27189.apk

**Comment by qlistephens95** [comment]
FAIL @conklin94122 When using HMD and the avatar is crossing its arms, the elbows do not move forward and they still penetrate the torso.
Steps to reproduce:
1: Launch build
2: Select avatar and go in front of mirror
3: Move arms around with selected avatar and try to cross arms
4: Arms still penetrate the torso when trying to cross arms
[pentratingarms.zip](https://github.com/highfidelity/hifi/files/2221197/pentratingarms.zip)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11505/HighFidelity-Beta-PR13672-4a27189.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11505/HighFidelity-Beta-Interface-PR13672-4a27189.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11510/HighFidelity-Beta-PR13672-94bb8fc.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11510/HighFidelity-Beta-PR13672-94bb8fc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11510/HighFidelity-Beta-Interface-PR13672-94bb8fc.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by qligmaloney** [comment]
Build this now

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11517/HighFidelity-Beta-PR13672-e7d70a8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11517/HighFidelity-Beta-PR13672-e7d70a8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11517/HighFidelity-Beta-Interface-PR13672-e7d70a8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11517/HighFidelity-Beta-PR13672-e7d70a8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11517/HighFidelity-Beta-Interface-PR13672-e7d70a8.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASS @conklin94122 verified that elbows move appropriately when in HMD mode and that when crossing arms elbows do not penetrate the torso.

**Pull request merged**
