### PR TITLE
Find nearby entities at login

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This fixes a bug where sometimes on login it takes a long time before physics will be enabled --> the avatar remains collisionless and sometimes (depending on Zone settings?) cannot move.

**Test Plan:**

**(1)** Using an interface from hifi/master (NOT from this PR) log into some domain that is not dev-welcome and then teleport to dev-welcome.
--> Notice how long it takes for your avatar to be able to move or walk on the floor
Wait at least 10 seconds but if you still can't collide with objects at the end of that try this workaround: spin your avatar around one full rotation and then wait three seconds.  Hopefully that will unjam the blocked logic.

**(2)** Perform the same experiment as **(1)** using the interface from this PR
--> Notice how long it takes for your avatar to be able to move or walk on the floor.  It should be shorter time than in **(1)**.

**(3)** The code change in this PR is limited to this "is physics ready?" poll at login so no other behaviors should change.  However the new rules require me to say:  This PR changes code around "login".  Please run all existing acceptance tests that relate to "login".

**Comment by AndrewMeadows** [comment]
This is a more proper fix for the problem that #11522 was trying to workaround.

**Comment by Nex-Pro** [comment]
@AndrewMeadows Can we get an outline of  ***Please run all existing acceptance tests that relate to "login".***

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3919/HighFidelity-Beta-PR11531-a26683a9eada977ac9f28177c24165e708068d88.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3919/HighFidelity-Beta-PR11531-a26683a9eada977ac9f28177c24165e708068d88.exe

**Comment by AndrewMeadows** [comment]
@Nex-Pro, good question...  I was under the assumption that it would make sense to a QA tester.  I will have to investigate what it is supposed to mean.

**Comment by AndrewMeadows** [comment]
@Nex-Pro, I removed those confusing instructions from the test plan.  This is ready for QA.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
@andrewd440 Using the current Hifi Master build I get the following error trying to go to dev-welcome
image

How should I proceed?

**Comment by YuppyPlays** [comment]
Testing complete:

(1) Using an interface from hifi/master (NOT from this PR) log into some domain that is not dev-welcome and then teleport to dev-welcome.
--> Notice how long it takes for your avatar to be able to move or walk on the floor
Wait at least 10 seconds but if you still can't collide with objects at the end of that try this workaround: spin your avatar around one full rotation and then wait three seconds. Hopefully that will unjam the blocked logic. **Check**

(2) Perform the same experiment as (1) using the interface from this PR
--> Notice how long it takes for your avatar to be able to move or walk on the floor. It should be shorter time than in (1). **Check**

**Master build 7150:     Mismatch error when trying to connect to Dev-Welcome**
**Dev-master build 7249:    14 Sec(s) til walking/movement was achieved.**
**PR 11531:    12 Sec(s) til walking/movement was achieved, however appeared mine disconnected during initial connection, I've noticed this happens from time to time with dev-welcome with all builds for me so I don't believe this is a PR related issue.**


**Pass**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3966/HighFidelity-Beta-PR11531-bbde1bcd632767466478fdc001350f7257f5cd80.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3966/HighFidelity-Beta-PR11531-bbde1bcd632767466478fdc001350f7257f5cd80.exe

**Pull request merged**
