### PR TITLE
Port avatar settings to tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Ports Settings > Avatar to the tablet.

Also:
- Ports Developer > Audio > Buffers to the tablet.
- Ports Developer > Network > Networking to the tablet.
- Displays the general settings page from the tablet menu, in the tablet.
- Adds a dialog heading to the general settings page.
- Adds keyboard to general settings page.
- Makes the Save and Cancel buttons work in the general settings page.

Known issue:
- "Browse" button for avatar preferences doesn't work.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62f91b4af696e573ed3e1517899510a4d3f043a5 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62f91b4af696e573ed3e1517899510a4d3f043a5 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 62f91b4af696e573ed3e1517899510a4d3f043a5 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-62f91b4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b592205f7e01a247c5d3bfb0739943e828962c3d available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-b592205.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-b592205.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9384dfd89c6f160be1e0025c2bd667f9112a749e available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-9384dfd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-9384dfd.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 48ee661f021fb7983250747ecd224cde01e64356 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-48ee661.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-48ee661.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6385bb2b8003031c1dbb568d22867527cfed6652 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-6385bb2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-6385bb2.dmg

**Comment by ctrlaltdavid** [comment]
QA:
- Settings > Avatar menu item in HMD works in tablet; in desktop mode works in dialog.
- Settings > General menu item in HMD works in tablet; in desktop mode works in dialog.

Note: "Browse" button for avatar preferences doesn't work at present.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 09ecb1251087453a67eafb6188c1621c3df4e0da available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-09ecb12.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-09ecb12.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: af4bdd5943a63689ffc4c1d046c7c7611c22b149 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-af4bdd5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-af4bdd5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fb1ff5be8941833ad47dcb2028db31c1820ced30 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-fb1ff5b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-fb1ff5b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 950f91965d40c70f9f2112e3cc199f566d9cf049 available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-950f919.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-950f919.dmg

**Comment by OmegaHeron** [comment]
Windows 10
QA Pass for desktop/mouse DK2/xbox controller.

Desktop calling from HUD bar
Avatar, Increase size, decrease size and reset size = pass.
Settings->General gives secondary UI element for settings.
Developer->Audio->Buffers gives secondary UI element for settings.
Developer->Network->Networking gives secondary UI element for settings.

HMD DK2
Avatar, Increase size, decrease size, reset size = pass.  Attachments selector spawns as discrete secondary dialog (same as desktop).
Settings->General displays in tablet and functions.
Developer->Audio->Buffers displays in tablet and functions.
Developer->Network->Networking displays in tablet and functions.

**Comment by OmegaHeron** [comment]
Desktop mode
Menu button on HUD->Settings->Avatar gives secondary UI element for settings.

DK2
Bring up tablet->Menu->Settings->Avatar gives avatar settings in tablet.

I had a crash and filed bugsplat the first time I tried to trigger from desktop/hud bar, but it's not happening on repeat so is, more likely than not, nothing to do with this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0069569e96719ff632d2fbb39ef12555d66a8ace available at: https://gist.github.com/232d62543c400186e73062c55e0453c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-0069569.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9795-0069569.dmg

**Pull request merged**
