### PR TITLE
Alpha 1 for edit handles

### PR DESCRIPTION
**Pull request by dback2**
Addresses: https://highfidelity.manuscript.com/f/cases/17475/

Test Plan:
- Enter Interface in desktop mode
- Open Create and select any entity
- Observe the edit handles from different camera angles to verify all overlays (or specifically the translation arrows, scale corner cubes, stretch spheres, and bounding box edges) are fully opaque

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11976/HighFidelity-Beta-PR13791-a6d944e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11976/HighFidelity-Beta-PR13791-a6d944e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11976/HighFidelity-Beta-Interface-PR13791-a6d944e.dmg

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
PASS @conklin94122 

Test Plan passes.  User is able to confirm that the edit handles are opaque at all times.

**Pull request merged**
