### PR TITLE
don't show users border when hover mouse if logged out

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- If you're logged in, hovering your mouse over the users window makes the border/background display (so that you can click and drag on it to move the users window).
- If you're logged out, hovering your mouse over the position where the users window was has no effect. (Previously, the border/background still displayed.)

https://forums.highfidelity.com/t/empty-overlay-users-js/11074/3

**Comment by hifi-gustavo** [comment]
Build console output for commit: 760f4366e13e357a66603d81e64c2e2a98087f84 available at: https://gist.github.com/e0b5cc9f5e545bde4e0acb9b08bbc650<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8180.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8180.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 760f4366e13e357a66603d81e64c2e2a98087f84 available at: https://gist.github.com/e0b5cc9f5e545bde4e0acb9b08bbc650<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8180.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8180.dmg

**Comment by nbq** [comment]
## QA Test
**QA Tester**: Coal
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Worked as described, no border on mouse over when logged out - it does show when logged in.

**Pull request merged**
