### PR TITLE
Fix rotation and position of avatar meshes attached to eye joints

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Using a current master or release build, reproduce the problems so that you know what you're looking for.
- Two users, both using the following avatar: http://hifi-content.s3.amazonaws.com/caitlyn/production/kamioAvatar/kamio.fst
- User scales different, e.g. one a 0.95 and the other at 1.05.
- Rotate avatars so that they're not looking at each other but you can still see the each other's avatar, in particular their eyes. Note how the eyes on the observed avatar render OK (are looking straight ahead).
- Rotate avatars so that they look at each other. Notice how the eyes "pop" on the observed avatar as it starts looking at your avatar: the eyes either retreat into the skull or pop out the front of the skull, depending on whether the avatar is looking up or looking down.
- Rotate avatars so that they're no longer looking at each. Notice how the eyes resume their proper positions.
- Stand face-to-face and adjust the scale of your avatar. Notice how the other avatar's eye pop out in front of their avatar when it tries looking up at yours, and receded into the other avatar's skull when it tries looking down at yours.

2) Repeat the tests in 1) using this PR's build.
- The eyes should render in their correct positions and look up/down without popping out of / receding into the skulll.
- You should see the other avatar's eyes move amongst looking at your left eye, your right eye, and your mouth.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7965/app_12620_PR.apk

**Comment by ctrlaltdavid** [comment]
https://highfidelity.fogbugz.com/f/cases/12603/Avatar-eyes-outside-of-head

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7965/HighFidelity-Beta-PR12620-957d39b0b13e9647f624c6bdd5147445eb1441df.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7965/HighFidelity-Beta-PR12620-957d39b0b13e9647f624c6bdd5147445eb1441df.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7967/app_12620_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7967/HighFidelity-Beta-PR12620-5acc605ba029aadca7eeba4e248e46ede94023a9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7967/HighFidelity-Beta-PR12620-5acc605ba029aadca7eeba4e248e46ede94023a9.exe

**Comment by hyperlogic** [comment]
Hey, great find, I'm glad the fix did not require a change to the FBX reader.  Could you please change to use std::vector<int> instead of QVector.  In general, unless performance is an issue (like with QString) we prefer the use of std containers over qt containers.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7984/app_12620_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7984/HighFidelity-Beta-PR12620-945858876ebab1979da7f929d9780409fe333c37.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7987/app_12620_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7987/HighFidelity-Beta-PR12620-75189e292d62945570cd28e46280a1c4748cc571.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7987/HighFidelity-Beta-PR12620-75189e292d62945570cd28e46280a1c4748cc571.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Eyes no longer pop and now look more natural.

**Pull request merged**
