### PR TITLE
Fix location.protocol value for serverless domains

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8713/app_12867_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8713/HighFidelity-Beta-PR12867-b82f2510f2addbde1ddf636fe3a4e2df8bb0d674.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8713/HighFidelity-Beta-PR12867-b82f2510f2addbde1ddf636fe3a4e2df8bb0d674.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Script shows correct location property.

**Pull request merged**
