### PR TITLE
Don't use invalidated iterators

### PR DESCRIPTION
**Pull request by Atlante45**
Fixes the crash @sethalves found when reloading content.

https://app.asana.com/0/26551373415487/113339865053884

### CODE REVIEW

**Comment by Atlante45** [comment]
Testing plan: Clear cache many times in a domain with any ATP assets (ie. home content)

**Comment by hifi-gustavo** [comment]
Build console output for commit: dfc3e5d4886d6d16ccc3f0889e2e7ae552ebfef2 available at: https://gist.github.com/6a89d2f8205901cd400ddb6f662c5217<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7680.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7680.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7680
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost                              
**Smoke Test Results:** Successful test.
**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**Successful Logout/Crash:** Failure.  After 8 rapid attempts to clear cache with ATP assets on ```localhost```, Interface crashed.  Log file included for deeper analysis
[attachments.zip](https://github.com/highfidelity/hifi/files/224250/attachments.zip)
.

**Comment by Atlante45** [comment]
@kevinmthomas-carpool reading the log, that crash is due to a deadlock, which could not have been introduced by this PR.
Would you mind retesting only the clear cache, and I'll file a bug about that deadlock.

**Comment by kevinmthomas-carpool** [comment]
## QA Re-Test
**PR Build:** 7680
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, Music
**Additional Test Results Requested:** Partially successful test.  After clearing the cache on the first attempt no content would load back.  Attempted to clear cache several more times and it did not clear.  Logged out of Interface and relogged and no content appeared.  Visited ```music``` and re-visited ```localhost``` and all content appeared normally.  Cleared cache again and all content appeared normally again.  Log file included.
**Successful Logout/Crash:** Successful logout.
[attachments.zip](https://github.com/highfidelity/hifi/files/224912/attachments.zip)

**Pull request merged**
