### PR TITLE
tablet or HUD-window, but not both

### PR DESCRIPTION
**Pull request by sethalves**
Don't show the tablet when a HUD-based widow is open, and vice versa.

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use the tablet to open a HUD-based window, such as help, edit, etc.
- make sure the tablet auto-closes
- while the HUD-based window is open, summon the tablet
- make sure the HUD-based window closes

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9c5083bc631b4de2c8fd4241e79ce7a1b3755815 available at: https://gist.github.com/59b5ee65b1c9bdacabc2add50a18d6c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-9c5083b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-9c5083b.dmg

**Comment by nbq** [comment]
Testing

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Used the tablet to open HUD-based windows: Help, Edit, PAL, GoTo, SnapShot
* Verified that for each of those the tablet auto closed
* While using the HUD-Based window, I opened the tablet to verify the HUD-Based window closed

**I found that when you RIGHT CLICK a button on the tablet VERY FAST (as in click then let up as quick as you can), the tablet stays open while the other HUD-Based window stays open. This did NOT seem to affect LEFT CLICK.**

**PASS WITH A NOTE**

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7ce89db529a8575b51db9ffe9c957bf383489dc available at: https://gist.github.com/59b5ee65b1c9bdacabc2add50a18d6c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-a7ce89d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-a7ce89d.dmg

**Comment by sethalves** [comment]
@nbq I've changed things to avoid the problem you mentioned in your note.  Would you mind retesting?

**Comment by nbq** [comment]
Retesting this now

**Comment by nbq** [comment]
On the retest I clicked all the buttons again using left and right click and no matter how fast I clicked the button the tablet went away as supposed to. I would say this is now fixed and a full

**PASS** 👍

**Comment by hifi-gustavo** [comment]
Build console output for commit: feb2e10a74812241b65de8cd8958552b5399c3f4 available at: https://gist.github.com/59b5ee65b1c9bdacabc2add50a18d6c1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-feb2e10.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9626-feb2e10.dmg

**Pull request closed without merging**
