### PR TITLE
When HMD is at rest, re-center the body under the avatar.

### PR DESCRIPTION
**Pull request by hyperlogic**
This should help the case when a user avatar is stuck in an
uncomfortable pose for a long period of time.  If they stop
moving their head, the body should recenter itself and
appear more natural.

Added an AtRestDetector class, that tracks the average and variance
of both position and rotation (quaternion logarithms), then
detects when the variance falls under a threshold.

Also, renamed variables with the straighting prefix to straightening.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dabe69341e234aaba12904b72c7402390ea8100 available at: https://gist.github.com/575b5d3164537394788b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.dmg

**Comment by howard-stearns** [comment]
I'm going to DNM this for a bit while we test #6012 (which will probably conflict because of the spelling changes).

**Comment by cozza13** [comment]
I tested this. It seemed like my avatar was recentered horizontally but my view point was at the base of my neck. Using Albert. https://hifi-public.s3.amazonaws.com/ozan/avatars/albert/_test/albert.fst

**Comment by cozza13** [comment]
I QA'ed this and it worked.

**Comment by cozza13** [comment]
sorry. I accidentally clicked "close"

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dabe69341e234aaba12904b72c7402390ea8100 available at: https://gist.github.com/f4f17cc40f2a8b3ef965<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c489e3afd6e93ff3170022e27514a02b9def1dc available at: https://gist.github.com/575b5d3164537394788b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6011.dmg

**Comment by howard-stearns** [comment]
I'm not sure what circumstances we would and would not want this, but I do think it's working as asked for: "if you put the HMD down on the table, your avatar won't become some horrow show looking thing, and after a few secs should return to looking normal."

I was able to hold my HMD still enough, though that the reset triggered even when not on the table.

**Pull request merged**
