### PR TITLE
Discovery: April 2018 (Huge PR; see description)

### PR DESCRIPTION
**Pull request by zfox23**
This PR contains the following five changes:
- Commerce: Gifts! (#12736)
- Reduce logging from some Commerce/Discovery features (#12849)
- Finally fix the grey security pic bug! (#12840)
- Prevent the Bubble icon from ever blinking as per MS14026 (#12822)
- Cleanup 'Private' HMD Preview State Machine Logic (#12805)

Because of how long some of the above changes have remained unmerged, and because the varying merge order of the above changes would cause frustrating merge conflicts, it is better to merge all of theses changes in one PR.

### CODE REVIEW

**Comment by zfox23** [comment]
# Test Plan
### Notes
This test plan is a massive concatenation of test plans from the following five PRs (with minor notation additions):
- Commerce: Gifts! (#12736)
- Reduce logging from some Commerce/Discovery features (#12849)
- Finally fix the grey security pic bug! (#12840)
- Prevent the Bubble icon from ever blinking as per MS14026 (#12822)
- Cleanup 'Private' HMD Preview State Machine Logic (#12805)

**Please note that the test plan for the Gifts PR must be added to the Acceptance Test.**

## Test Plan - Commerce: Gifts! #12736

## Notes
The main feature addition in this PR is **the ability to gift marketplace items that you own to connections or people nearby!**

This PR makes a number of changes, some of which are not explicitly related to the Gifting feature. These other changes include:
    1. A refreshed UI for a few Commerce elements:
        - Brand new "My Purchases" UI
        - Tweaked `CommerceLightbox` QML item
    2. New `hifi-glyphs` font
    3. A refactor of the way functions are executed from the `CommerceLightbox` QML item
    4. A new `connectionUtils.js` file to DRY up code that gets a user's Connection data
    5. My Purchases/My Items no longer auto-refreshes

## Prerequisites
- You have a High Fidelity account on the Staging backend environment
- Your environment variables are set up to point Interface/Sandbox at the Staging backend environment
    - `SETX HIFI_METAVERSE_URL https://staging.highfidelity.com`
- You have a valid Wallet that you have authenticated
- You have at least one Connection on the Staging backend environment
    - At one noted point during the test, you will have to be present in a domain along with a Connection.
- You are connected to your Sandbox where you **DO NOT** have "Replace Content" permissions.
- You have purchased the following items from the Marketplace:
    1. 2x Wearables (i.e. "Monztur Hat vX.X" on Staging)
    2. 2x Apps (i.e. "HRTF App vX.X" and "App vX.X - BLUE VERSION" on Staging)
    3. 1x Avatars (i.e. "Finnigon vX.X" on Staging)
    4. 1x Content Set (i.e. "Oasis vX.X" on Staging)
    5. 1x Entity (i.e. "Drum Set vX.X" on Staging)
- At one point during the test, you will need to test certain UI elements for legibility from within an HMD.

## Tests
- Unless otherwise mentioned, perform all below tests in Desktop mode.

### "My Purchases" Smoke Tests
- Perform this test in both HMD mode and desktop mode.

1. Open My Purchases
    i. Verify that everything is legible.
    ii. Verify that the buttons on each Card contain a glyph and text corresponding to the type of Purchase on that card (for example, "Wearables" say "Wear" and have a "Hat" glyph)
    iii. Verify that clicking an image takes you to the corresponding Marketplace Item page.
    iv. Verify that the button on the card corresponding to the Content Set that you purchased is *Disabled* and that there is a red (i) icon to the right of the button.
2. Click on the disabled button on the card corresponding to the Content Set that you purchased.
    i. Verify that that card flips over to reveal an explanation as to why you can't Replace that content set.
3. Click the "Learn More" link on the flipped card.
    i. Verify that you see a lightbox popup. Verify that the button on the popup closes the popup.
4. Click the (x) button on the flipped card.
    i. Verify that the card flips over to its front.
5. Click the "three dots" button on the top right of any card (henceforth referred to as the "context menu button").
    i. Verify that the card flips over to reveal three buttons: "View Certificate", "View in Marketplace", and "Gift"
6. Click the "View Certificate" button.
    i. Verify that the correct certificate is displayed, then click the "x" in the top right of the cert to return to My Purchases.
7. Click the "three dots" button on the top right of any card, then click the "View in Marketplace" button.
    i. Verify that you are taken to the correct Marketplace Item page.

### Gifting Tests
- At this point, ensure that a Connection is also present in your Sandbox.

#### Test A: Wearables

1. Click "Wear" on the card corresponding to any ONE of the Wearables you have purchased.
    i. Verify that the Wearable appears on your avatar.
2. Click the context menu button on that card, then click "Gift"
    i. Verify that you see a "Remove Wearable" popup.
    ii. Verify that the text in the popup makes sense.
3. Click "Confirm" on the "Remove Wearable" popup.
    i. Verify that your avatar is no longer wearing the wearable.
    ii. Verify that you are now on a screen that says "Gift <Wearable Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
4. Click the "Connection" button.
    i. Verify that you are prompted to choose a recipient.
5. Click "CHOOSE" next to the Connection that is present in your Sandbox.
    i. Verify that you are taken to a screen that says "Gift <Wearable Name>" with a "Gift to" field corresponding to your Connection's username, a "CHANGE" button, an "Optional Public Message" text field, a "CANCEL" button, and a "SUBMIT" button.
6. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<Wearable Name>", "Sent To:", the name of the Connection to whom you sent the Gift, and a "CLOSE" button.
7. Click the "CLOSE" button.
    i. Verify that you are returned to the Purchases page, and that the Wearable you just gifted no longer appears in your Purchases.
    ii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
8. Click the context menu button on the card corresponding to the other wearable that you purchased, then click "Gift"
    i. Verify that you do NOT see a "Remove Wearable" popup and that you are taken directly to the screen that says "Gift <Wearable Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
9. Click the "Someone Nearby" button.
    i. Verify that you are prompted to choose a recipient.
10. Click on the orb overlaid on top of the Connection in your domain.
    i. Verify that the person's display name appears in the window and that their orb turns orange.
11. Click "CHOOSE".
    i. Verify that you are taken to a screen that says "Gift <Wearable Name>" with a "Gift to" field corresponding to your recipient's display name, a "CHANGE" button, an "Optional Public Message" text field, a CHECKED "Show Effect" checkbox, a "CANCEL" button, and a "SUBMIT" button.
12. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<Wearable Name>", "Sent To:", the name of your Gift recipient, and a "CLOSE" button.
    ii. Verify that you see a particle effect between you and the recipient whose graphic is the one corresponding to the item you just Gifted.
    iii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
    
#### Test B: Apps
1. Click "Install" on the card corresponding to any ONE of the Apps you have purchased.
    i. Open Running Scripts (CTRL+J) and verify that the associated script is running, then close Running Scripts.
2. Click the context menu button on that card.
    i. Verify that you see four buttons: "Uninstall", "Show in Marketplace", "View Certificate", and "Gift".
3. Click "Gift"
    i. Verify that you see an "Uninstall App" popup.
    ii. Verify that the text in the popup makes sense.
4. Click "Confirm" on the "Uninstall App" popup.
    i. Open Running Scripts (CTRL+J) and verify that the associated script is no longer running.
    ii. Verify that you are now on a screen that says "Gift <App Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
5. Click the "Connection" button.
    i. Verify that you are prompted to choose a recipient.
6. Click "CHOOSE" next to the Connection that is present in your Sandbox.
    i. Verify that you are taken to a screen that says "Gift <App Name>" with a "Gift to" field corresponding to your Connection's username, a "CHANGE" button, an "Optional Public Message" text field, a "CANCEL" button, and a "SUBMIT" button.
7. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<App Name>", "Sent To:", the name of the Connection to whom you sent the Gift, and a "CLOSE" button.
8. Click the "CLOSE" button.
    i. Verify that you are returned to the Purchases page, and that the App you just gifted no longer appears in your Purchases.
    ii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
9. Click the context menu button on the card corresponding to the other App that you purchased, then click "Gift"
    i. Verify that you do NOT see an "Uninstall App" popup and that you are taken directly to the screen that says "Gift <App Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
10. Click the "Someone Nearby" button.
    i. Verify that you are prompted to choose a recipient.
11. Click on the orb overlaid on top of the Connection in your domain.
    i. Verify that the person's display name appears in the window and that their orb turns orange.
12. Click "CHOOSE".
    i. Verify that you are taken to a screen that says "Gift <App Name>" with a "Gift to" field corresponding to your recipient's display name, a "CHANGE" button, an "Optional Public Message" text field, a CHECKED "Show Effect" checkbox, a "CANCEL" button, and a "SUBMIT" button.
13. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<App Name>", "Sent To:", the name of your Gift recipient, and a "CLOSE" button.
    ii. Verify that you see a particle effect between you and the recipient whose graphic is the one corresponding to the App you just Gifted.
    iii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
    
#### Test C: Avatars
1. Click "Wear" on the card corresponding to the Avatar you have purchased.
    i. Zoom out and verify that you are wearing that avatar now.
    ii. Verify that the button on that card now says "CURRENT"
2. Click the context menu button on that card, then click "Gift"
    i. Verify that you see a "Change Avatar" popup.
    ii. Verify that the text in the popup makes sense.
3. Click "Confirm" on the "Change Avatar" popup.
    i. Verify that your avatar is now "Woody"
    ii. Verify that you are now on a screen that says "Gift <Avatar Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
4. Click the "Connection" button.
    i. Verify that you are prompted to choose a recipient.
5. Click "CHOOSE" next to the Connection that is present in your Sandbox.
    i. Verify that you are taken to a screen that says "Gift <Avatar Name>" with a "Gift to" field corresponding to your Connection's username, a "CHANGE" button, an "Optional Public Message" text field, a "CANCEL" button, and a "SUBMIT" button.
6. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<Avatar Name>", "Sent To:", the name of the Connection to whom you sent the Gift, and a "CLOSE" button.
7. Click the "CLOSE" button.
    i. Verify that you are returned to the Purchases page, and that the Avatar you just gifted no longer appears in your Purchases.
    ii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
    
#### Test D: Content Sets
1. Click the context menu button on a card corresponding to a Content Set you have purchased, then click "Gift"
    i. Verify that you are now on a screen that says "Gift <Content Set Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
2. Click the "Connection" button.
    i. Verify that you are prompted to choose a recipient.
3. Click "CHOOSE" next to the Connection that is present in your Sandbox.
    i. Verify that you are taken to a screen that says "Gift <Content Set Name>" with a "Gift to" field corresponding to your Connection's username, a "CHANGE" button, an "Optional Public Message" text field, a "CANCEL" button, and a "SUBMIT" button.
6. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<Content Set Name>", "Sent To:", the name of the Connection to whom you sent the Gift, and a "CLOSE" button.
7. Click the "CLOSE" button.
    i. Verify that you are returned to the Purchases page, and that the Content Set you just gifted no longer appears in your Purchases.
    ii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.

#### Test E: Entities
1. Click the context menu button on a card corresponding to an Entity you have purchased, then click "Gift"
    i. Verify that you are now on a screen that says "Gift <Entity Name> To:" with a "Connection" button, a "Someone Nearby" button, and a "Back" button.
2. Click the "Connection" button.
    i. Verify that you are prompted to choose a recipient.
3. Click "CHOOSE" next to the Connection that is present in your Sandbox.
    i. Verify that you are taken to a screen that says "Gift <Entity Name>" with a "Gift to" field corresponding to your Connection's username, a "CHANGE" button, an "Optional Public Message" text field, a "CANCEL" button, and a "SUBMIT" button.
6. Click the "SUBMIT" button.
    i. Verify that you see a popup that says "<Entity Name>", "Sent To:", the name of the Connection to whom you sent the Gift, and a "CLOSE" button.
7. Click the "CLOSE" button.
    i. Verify that you are returned to the Purchases page, and that the Entity you just gifted no longer appears in your Purchases.
    ii. Your Connection should verify that they have received your Gift by checking their My Purchases page as well as their Wallet's Recent Activity.
    
### `CommerceLightbox` Smoke Tests
Because the `CommerceLightbox` QML item has undergone some refactoring, please perform a functional smoke test of the `CommerceLightbox` by checking a couple instances of that Item.

Here are the areas where the `CommerceLightbox` is used:
- The "Security Pic" popup that appears when clicking the small security pic icon in the top right of various Commerce pages, like "My Purchases" and the Wallet.
- The popup that appears when trying to purchase a Content Set when you don't have "Replace Content" permissions
- The popup that appears when clicking on the "PENDING... [?]" link in Purchases on a pending purchase's card
- The popups in tests A.2.i, B.3.i, and C.2.i above
- The popup that appears when you don't have a .hifikey file locally but have set up your wallet before, then click "CREATE NEW WALLET" or "CONTINUE WITH THESE KEYS"


## Test Plan - Reduce logging from some Commerce/Discovery features #12849

### Notes
- This PR should not _functionally_ change any features, so this test plan will be light on details.

### Tests
Perform a general smoke test of the following features, looking for visual and functional changes:
- Wallet authentication screen
- PAL sphere overlay selection ("sphere overlays" === "the bubbles that appear on top of avatars when the PAL is open")
- Wallet "Send Money" sphere overlay selection
- Inspection Certificates (try inspecting a few rezzed entities. additionally, try bringing up the inspection cert of a few items in Purchases.)


## Test Plan - Finally fix the grey security pic bug! #12840
### Prerequisites
- You EITHER:
    1. DO NOT already have a wallet associated with your HiFi account OR
    2. Have renamed the `.hifikey` file associated with your account to `<xxx>.hifikey.backup` (if you choose this option, it's assumed that you know how to set up a new wallet from the Wallet Setup screen)
- You must have an HMD

### Tests
- The goal of this test plan is to attempt (unsuccessfully) to get the Wallet Security Pic to show up as a grey square or not show up at all. You must attempt to do so in both HMD and Desktop modes.
- There is no way to reliably reproduce the "grey security pic" bug. Thus, navigating throughout the Commerce system is the only way to attempt to reproduce the bug.

Spend some time doing the following (as well as anything else that you can think of) in both HMD and Desktop modes in an attempt to reproduce the "grey security pic" bug:
- Creating a new wallet
- Changing your security pic
- Changing your password
- Viewing out the Wallet, Checkout, and My Purchases screens
- Switching between HMD and Desktop modes in the same session
- Switching High Fidelity account logins
- Switching domains


## Test Plan - Prevent the Bubble icon from ever blinking as per 14026 #12822
### Prerequisites
- Testing this PR requires the use of two clients controlling one avatar each (Avatar A and Avatar B).

### Tests
Perform the tests below in Desktop mode.

1. Have Avatar A turn their bubble on.
    i. Verify that the BUBBLE icon in the HUD does not blink, but rather immediately turns to the ACTIVE state (white).
2. Have Avatar B turn their bubble off. Have Avatar B walk into Avatar A's bubble.
    i. Have Client A verify that the BUBBLE icon in the HUD does not blink, but rather stays in the ACTIVE state (white).


## Test Plan - Cleanup 'Private' HMD Preview State Machine Logic #12805
### Notes
I present to you, my favorite QA tester, a challenge.

This test plan is all about trying (and hopefully failing) to get a user's Wallet Passphrase visible on the user's main display. I've outlined the basic way to test this PR below, but I leave it up to you to try to break the system... Good luck. 😈

The test plan below is very similar to the plan of #12276, but not the same. 

### Prerequisites
- You EITHER:
    1. DO NOT already have a wallet associated with your HiFi account OR
    2. Have renamed the `.hifikey` file associated with your account to `<xxx>.hifikey.backup` (if you choose this option, it's assumed that you know how to set up a new wallet from the Wallet Setup screen)
- You are wearing an HMD.

### Tests
Perform all of the below tests in HMD.

1. Open the tablet. Select the Wallet app. Select the "Set Up Wallet" button.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is NOT showing, but instead you see the HMD preview.
2. Select a security picture, then press NEXT.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is showing.
    ii. Verify that you see your security image on the "Tip" page of the Wallet setup wizard.
3. Press "GOT IT".
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is showing.
    ii. Verify that you see your security image on the "Select Passphrase" step of the Wallet setup wizard.
4. Click the "Next" button 
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is NOT showing, but instead you see the HMD preview.
5. Finish Wallet setup, then restart Interface. Open the Wallet app.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is showing.
6. Input your Passphrase, then go to the "SECURITY" tab of the Wallet. Click on the button to change your passphrase.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is showing.
7. Close the "Change Passphrase" screen.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is NOT showing, but instead you see the HMD preview.
8. Click on the button to change your security pic.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is NOT showing, but instead you see the HMD preview.
9. Close the "Change Security Pic" screen.
    i. Peek beneath your HMD at the computer screen, and verify that the "PRIVATE" image is NOT showing, but instead you see the HMD preview.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8697/app_12862_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8697/HighFidelity-Beta-PR12862-539fd4232409265d3c767de59e803361bad908a0.dmg

**Comment by howard-stearns** [comment]
Hold off on testing until we update from the massive https://github.com/highfidelity/hifi/pull/12068 PR, which also requires that we resolve conflicts from other stuff that got merged today.

**Comment by howard-stearns** [comment]
closed in favor of https://github.com/highfidelity/hifi/pull/12883, because I couldn't push the merge-resolving pull from master (and I don't know why).

**Comment by zfox23** [comment]
Reopening to make it easier for me to fix bugs (since this is my own branch).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8821/app_12862_PR_ee9519bf1b2c65f31a3b83a6d7dd4cb00408450a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8821/HighFidelity-Beta-PR12862-ee9519bf1b2c65f31a3b83a6d7dd4cb00408450a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8821/HighFidelity-Beta-Interface-PR12862-ee9519bf1b2c65f31a3b83a6d7dd4cb00408450a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8821/HighFidelity-Beta-PR12862-ee9519bf1b2c65f31a3b83a6d7dd4cb00408450a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8821/HighFidelity-Beta-Interface-PR12862-ee9519bf1b2c65f31a3b83a6d7dd4cb00408450a.exe

**Comment by zfox23** [comment]
I've fixed the clientside bugs reported by QA.

The bug related to gift messages not appearing in Recent Activity is a backend bug - @davidkelly will have a backend fix shortly.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8824/app_12862_PR_02aa8ac56613c8671355234b1828cc5855bcab56.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8824/HighFidelity-Beta-PR12862-02aa8ac56613c8671355234b1828cc5855bcab56.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8824/HighFidelity-Beta-Interface-PR12862-02aa8ac56613c8671355234b1828cc5855bcab56.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8827/app_12862_PR_05042201714a09038f0a49de1bfd5bd8542e0436.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8827/HighFidelity-Beta-PR12862-05042201714a09038f0a49de1bfd5bd8542e0436.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8827/HighFidelity-Beta-Interface-PR12862-05042201714a09038f0a49de1bfd5bd8542e0436.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8827/HighFidelity-Beta-PR12862-05042201714a09038f0a49de1bfd5bd8542e0436.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8827/HighFidelity-Beta-Interface-PR12862-05042201714a09038f0a49de1bfd5bd8542e0436.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
FAIL @conklin94122 
Commerce: Gifts! (12736) | Fail - When sending a Gift via the someone nearby tab, no information is placed in the Wallet app.  Item does appear in my purchases and user is able to use the gift, but there are no records of the exchange in the wallet app for both the sender and recipient.

Reduce Logging from some Commerce/Discovering Features (12849) | Pass - Previous hiccups no longer occur and overlays function as expected.

Finally fix grey security pic bug! (12840) | Pass - Picture appeared as intended.

Prevent Bubble Icon from ever blinking (12822) | Pass - Bubble icon does not blink when active. It now performs solidly.

Cleanup 'Private' HMD Preview State Machine Logic (12805) | Pass - Wallet and My Purchases was tested to see if Privacy block could be beaten. Block worked as expected.

Notes: Crash on log in no longer occurs!
[Files.zip](https://github.com/highfidelity/hifi/files/1921649/Files.zip)

**Comment by zfox23** [comment]
Thank you for your QA, @qlimnavarro.

@conklin94122: @howard-stearns, @davidkelly, and I have determined that the noted failure is a purely backend failure. Dave will be looking at the failure ASAP. Because the noted failure is the only one, and because it is not something that needs to be fixed on the client, I'm merging this PR now.

**Comment by conklin94122** [comment]
@zfox23 Works for me. Would you please note the bugs filed for backend to work from in this PR? Thanks.

**Comment by zfox23** [comment]
@conklin94122: https://highfidelity.fogbugz.com/f/cases/14294/Sending-a-gift-to-a-nearby-recipient-results-in-no-message-being-recorded-in-History

**Comment by conklin94122** [comment]
You're the awesomest, thanks @zfox23

**Pull request merged**
