### PR TITLE
Fixed out of range error in AnimTwoBoneIK

### PR DESCRIPTION
**Pull request by amantley**
There was an error in the two bone IK code that could lead to a NAN error and a corruption of the avatar joint data.

### TEST PLAN
1. The only way to test this is to go into HMD mode and put your right hand on your right shoulder or your left hand on your left shoulder.  It can take awhile but without this fix your body will disappear into the floor. 

I will add a test case to cover this

https://highfidelity.manuscript.com/f/cases/22248/Out-of-range-error-in-AnimTwoBoneIK

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18627/HighFidelity-Beta-PR15344-09e2da4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18627/HighFidelity-Beta-Interface-PR15344-09e2da4.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18627/HighFidelity-Beta-PR15344-09e2da4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18627/HighFidelity-Quest-Beta-PR15344-09e2da4.apk)

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18744/HighFidelity-Beta-PR15344-09e2da4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18744/HighFidelity-Beta-Interface-PR15344-09e2da4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18744/HighFidelity-Beta-PR15344-09e2da4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18744/HighFidelity-Quest-Beta-PR15344-09e2da4.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18744/HighFidelity-Beta-PR15344-09e2da4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18744/HighFidelity-Beta-Interface-PR15344-09e2da4.exe

**Pull request merged**
