### PR TITLE
Tutorial fixes

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e0778e466794ce4b40015a44dbaccb3bccc332c6 available at: https://gist.github.com/a81aa3cd4bcb15bd4a395ccc7636a832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-e0778e4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-e0778e4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ab4cfb8919601c1646b21ae45d0a52b58eda3d3 available at: https://gist.github.com/a81aa3cd4bcb15bd4a395ccc7636a832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-2ab4cfb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-2ab4cfb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c711ee7723ef76aaef6ad371c4a22f1d5bbc8e45 available at: https://gist.github.com/a81aa3cd4bcb15bd4a395ccc7636a832<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-c711ee7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8838-c711ee7.dmg

**Comment by howard-stearns** [comment]
test plan?

**Comment by huffman** [comment]
I need to push some changes to resolve the merge conflicts. @howard-stearns I can see about pushing a content set with this to make it testable, but all of these changes are present in the tests we've been doing on M/W/F

**Pull request closed without merging**
