### PR TITLE
DO NOT MERGE - Update cmake for Leap Motion SDK 2.2.4

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Interface is currently built with Leap Motion SDK 2.2.1.

SDKs 2.2.2 and 2.2.3 provide a few minor fixes. The main change is in the 2.2.3 driver which provides better hand initialization.

Interface built with SDK 2.2.1 works OK with 2.2.3 drivers installed, so updating the build environment to 2.2.3 is perhaps optional.

If updating the build environment to SDK 2.2.3:
- SDK 2.2.3 no longer has a Leapd.dll for Windows. Instead, use Leap.dll for Debug builds. This PR updates the cmake file for this.
- SDK 2.2.3 removes libstdc++ version of libLeap.dylib from the OS X SDK, but I believe Interface OSX is built with libc++ so no change required.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53e207e971cc5d6febac1c31cfb42b0d8075de81 available at: https://gist.github.com/e081d3907a3dcd9aa476<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4487.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4487.dmg

**Comment by ctrlaltdavid** [comment]
This update also works as-is with the just-released SDK 2.2.4.
SDK 2.2.4 includes lowered CPU use. It's not clear whether this is in the driver or the linked library.

**Comment by ZappoMan** [comment]
What's the status on this PR? Why is it "DO NOT MERGE"? @murillodigital @ctrlaltdavid

**Comment by ctrlaltdavid** [comment]
It's do-not-merge because it needs to be coordinated with updating the build environment. Also, it's not strictly needed as 2.2.2 seems to work pretty well. I was actually intending to delete this PR today.

Note: There's now an SDK 2.2.5, released yesterday, which I haven't tried out.

**Pull request closed without merging**
