### PR TITLE
Second attempt at fixing the HMD eye projections, without breaking the camera this time.

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 41d587bd2e65fd62590dfc609222daf8ba207e1e available at: https://gist.github.com/947cc549686ffe5e61c5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.dmg

**Comment by samcake** [comment]
it fixes the ui buttons but the flickering of the skybox is there though
Looking at it

**Comment by samcake** [comment]
@ZappoMan  Could it be due to the way we detect which zone we are in ?
THe fact that the background oscillate between skybox and atmosphere ?
COuld it be connected to this code change on the viewFrustum ?

**Comment by jherico** [comment]
I'll do some testing locally with skyboxes and see if I can resolve the issue.

**Comment by ZappoMan** [comment]
@samcake @jherico - I think we agreed to use the camera position as the location which we use to determine "inside" of a zone... so... if the camera position is unstable, I could imagine we'd oscillate. Note: I haven't tested, I'm just answering based on reading your questions/comments to the PR.

**Comment by jherico** [comment]
@ZappoMan there shouldn't be any oscillation in non-stereo modes.  Perhaps in stereo contexts we need to provide a mechanism for fetching the base camera as well as the 'rendering camera'.  But I don't think that mechanism is putting eye offsets in the camera / frustum classes.  

We already have something like this in Application where it distinguishes between the _viewFrustum and _displayViewFrustum.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c94b8b6e30fdb2347fd729d48dbf264f3c03f5fa available at: https://gist.github.com/947cc549686ffe5e61c5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e20d2ffb15a32ccb3f09fd4deaa62fcbf239c52c available at: https://gist.github.com/947cc549686ffe5e61c5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 827d7f622147b3f9f9a97828b8accc214c045e73 available at: https://gist.github.com/947cc549686ffe5e61c5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4846.dmg

**Comment by jherico** [comment]
I can't find any issues with the skybox rendering while using this code.  Perhaps it was an unrelated bug that just happened to show up at the same time?  If you can find a repro case, please let me know so i can track it down.

**Pull request merged**
