### PR TITLE
73.1: remove hifiSixense DLL on install

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13400/HighFidelity-Beta-PR14097-817caa5.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13403/HighFidelity-Beta-PR14097-cba20fb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13403/HighFidelity-Beta-PR14097-cba20fb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13403/HighFidelity-Beta-Interface-PR14097-cba20fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13403/HighFidelity-Beta-PR14097-cba20fb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13403/HighFidelity-Beta-Interface-PR14097-cba20fb.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13420/HighFidelity-Beta-PR14097-5d80143.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13420/HighFidelity-Beta-PR14097-5d80143.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13420/HighFidelity-Beta-Interface-PR14097-5d80143.exe

**Comment by jakram** [comment]
Currently testing

**Comment by jakram** [comment]
@conklin94122 PASS

Test plan followed:
`scenario1.0:
clean install of 0.72
- inerface launches successfully
close interface and sandbox
add old plugins/hifiSixense.dll to the plugins directory in your install directory
add old sixense_x64.dll, msvcr100.dll, msvcp100.dll to the root of your install directory (beside Interface.exe)
install 0.73
- inerface is not launched (every attempt to launch is unsuccessful)
close sandbox
install 0.73.1
- interface launches successfully
- plugins/hifiSixense.dll is removed from program files folder
- sixense_x64.dll, msvcr100.dll, msvcp100.dll remain in program files folder

scenario1.1:
clean install of 0.72
- inerface launches successfully
close interface and sandbox
add new plugins/hifiSixense.dll to the plugins directory in your install directory
add new sixense_x64.dll, msvcr100.dll, msvcp100.dll to the root of your install directory (beside Interface.exe)
install 0.73
- inerface launches successfully
- plugins/hifiSixense.dll remain in program files folder
- sixense_x64.dll, msvcr100.dll, msvcp100.dll remain  in program files folder
close sandbox
install 0.73.1
- interface launches successfully
- plugins/hifiSixense.dll remain in program files folder
- sixense_x64.dll, msvcr100.dll, msvcp100.dll remain  in program files folder

scenario2.0:
express install of 0.73.1
- inerface launches successfully
- plugins/hifiSixense.dll is absent in plugins folder

scenario2.1:
custom install of 0.73.1
- inerface launches successfully
- plugins/hifiSixense.dll is absent in plugins folder

scenario3:
clean install of 0.72
- inerface launches successfully
close interface and sandbox
install 0.73.1
- inerface launches successfully
- plugins/hifiSixense.dll is absent in plugins folder

scenario4:
clean install of  0.73
- inerface launches successfully
close interface and sandbox
install 0.73.1
- inerface launches successfully
- plugins/hifiSixense.dll is absent in plugins folder'

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13440/HighFidelity-Beta-PR14097-5d80143.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13440/HighFidelity-Beta-PR14097-5d80143.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13440/HighFidelity-Beta-Interface-PR14097-5d80143.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13440/HighFidelity-Beta-PR14097-5d80143.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13440/HighFidelity-Beta-Interface-PR14097-5d80143.dmg

**Pull request merged**
