### PR TITLE
Update BUILD_WIN.md

### PR DESCRIPTION
**Pull request by Nex-Pro**
Added dot backslash to avoid error in windows powershell at line 42. (worked for me)

### CODE REVIEW

**Comment by Nex-Pro** [comment]
This is a documentation change only. No need to use the build.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11127/HighFidelity-Beta-PR13545-09b21d3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11127/HighFidelity-Beta-PR13545-09b21d3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11127/HighFidelity-Beta-Interface-PR13545-09b21d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11127/HighFidelity-Beta-PR13545-09b21d3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11127/HighFidelity-Beta-Interface-PR13545-09b21d3.exe

**Comment by kencooke** [comment]
Looks good. Docs only, no QA needed.

**Comment by Nex-Pro** [comment]
@kencooke Is there a way to prevent the automatic build for this kind of docs change ?

**Pull request merged**
