### PR TITLE
Fix transition (ex-fade) debugging scripts

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes the broken debugFade.js debugging script (now renamed debugTransition.js with this PR). The script now creates a tablet app.

The debugTransition.js script in _scripts\developer\utilities\render_ can be used to tweak the fade effect on the 4 supported events, the above two being the only ones processed in the application at this time. Checking the "Edit" checkbox applies cyclicly the selected fade event to the object in front of you. To manually control the threshold value, click on "Manual" under "Edit". In this mode, the "Threshold" slider controls the value.

All changes to the various fade parameters apply to the currently selected event.

## Save

This feature will only work if the **HIFI_USE_SOURCE_TREE_RESOURCES** environment variable is set to 1.
Clicking on the save button saves a JSON configuration file under _interface/resources/config_ with name corresponding to the currently edited event. This file contains the current settings only for the edited event.

## Load

Clicking on the load button loads back the settings stored in the JSON configuration file under _interface/resources/config_ with name corresponding to the currently edited event.

Note: the JSON configuration files are not automatically loaded at launch time.

# TEST PLAN

As this is an internal debugging tool, no automatic test case can be used for this PR. For this test, the debugTransition.js script must be running and the "Transition" tablet app be opened.

1. checking the "Edit" checkbox should apply the event selected to the combobox at the right side of the checkbox on the object in front of you.
2. With the "Edit" checkbox checked, modifying any parameter of the edit window should modify the fade event accordingly (notably the two color pickers).
3. With the "Edit" checkbox checked, switching to another selected event should modify the fade's visual appearance.
4. With the "Edit" checkbox checked, switching to another object by changing the point of view should remove the fade event from the previous object and apply it to the new one.
5. With both the "Edit" and "Manual" checkboxes checked, moving the "Threshold" slider should modify the fade gradient's threshold value.
6. If the "Edit" checkbox was checked, unchecking it should remove the fade event from the object in front of you
7. Clicking save with the HIFI_USE_SOURCE_TREE_RESOURCES environment variable set to 1 should create a Json file under _interface/resources/config_ with a name corresponding to the transition event name.
8. Clicking on load should load back the file saved in the previous step.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6942/app_12346_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6942/HighFidelity-Beta-PR12346-d248e1ed79c4098cf4d2f819f775698492961001.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6942/HighFidelity-Beta-PR12346-d248e1ed79c4098cf4d2f819f775698492961001.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
