### PR TITLE
Add size and position properties, methods, and events to WebWindow

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Read/write properties added:
- position : { x, y }
- size : { width, height }

New methods added:
- { x, y } getPosition()
- void setPosition( { x, y } )
- { width, height } getSize()
- void setSize( { width, height } )
- void setSize( width, height )

New events added:
- moved( { x, y } );
- resized( { width, height } );

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb2c48e3eddbcfd0ee03f932b48caeb035626f6e available at: https://gist.github.com/1cfd6b37be403ed228fc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5569.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5569.dmg

**Comment by ctrlaltdavid** [comment]
@DaveDubUK You may be interested in this PR for your walkTooks script.

**Comment by PhilipRosedale** [comment]
@jherico Can you review this?

**Comment by DaveDubUK** [comment]
@ctrlaltdavid  - yep, very cool, thank you - I will be able to prevent window resizing using those events. Is there currently an event for window->close?

**Comment by ctrlaltdavid** [comment]
@DaveDubUK Yes, there's already a closed() event.

**Pull request merged**
