### PR TITLE
Fix isHazeEnabled() checks with 0.0 to fix GLES compiler error

### PR DESCRIPTION
**Pull request by Cristo86**
Test plan:
- Shaders should compile on desktop and android without log warnings.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9935/HighFidelity-Beta-PR13200-c7edf72f719aa73ff5ad648131d5f92363bc3e04.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9935/HighFidelity-Beta-PR13200-c7edf72f719aa73ff5ad648131d5f92363bc3e04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9935/HighFidelity-Beta-Interface-PR13200-c7edf72f719aa73ff5ad648131d5f92363bc3e04.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9935/HighFidelity-Beta-PR13200-c7edf72f719aa73ff5ad648131d5f92363bc3e04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9935/HighFidelity-Beta-Interface-PR13200-c7edf72f719aa73ff5ad648131d5f92363bc3e04.exe

**Comment by qligmaloney** [comment]
Currently testing Desktop and Android Interfaces

**Comment by Cristo86** [comment]
It wasn't happening in OSX before this PR?
(Due to the nature of this change, this seems strange to originate from this. But with shaders we never know)

**Comment by samcake** [comment]
we confirmed that the same failure happens on mac os with master, this is due to the macbook  / AMD gpu and the Qt shaders
Not a new bug
otherwise, there are no failed shader from us
Good to go,
We (ENGINE TEAM) qa approve

**Pull request merged**
