### PR TITLE
(!!! DO NOT MERGE !!!) Interview build competency proof for Nick Shaffner

### PR DESCRIPTION
**Pull request by NickShaffner**
Adds the phrase "NJS interview build proof" to the title bar of interface.

Notes:
* Extremely low risk, low value change.   Changes the contents of a single string.
* Requested by Thomas Schofield re: standardized 'build proof' email.

Test Plan:
* Ensure that the phrase "NJS interview build proof" appears in the title bar of interface.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
ok to build

**Comment by themelissabrown** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3061/HighFidelity-Beta-PR11309-bcc9df6a39ed5e07e02dbbe7c33ac54f9caa4de1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3061/HighFidelity-Beta-PR11309-bcc9df6a39ed5e07e02dbbe7c33ac54f9caa4de1.exe

**Pull request closed without merging**
