### PR TITLE
Working on improved unit testing, adding texture transfer testing

### PR DESCRIPTION
**Pull request by jherico**
This PR moves all non-unit tests out of the `tests` folder and into `tests-manual`.  It also adds a new QTest based test to verify the behavior of the GPU texture transfer system.

## Testing

No QA required.  This only impacts unit test code which isn't currently run as part of the build process.  

### Command Line
In your build directory, execute the following command to build the gpu texture transfer test

` cmake --build . --target gpu-TextureTest --config Release`

Next, change to the tests subdirectory and execute the test using ctest with the command

`ctest -R gpu-TextureTest`

### Visual Studio

Go to the `hidden/test-executables` folder in the hifi solution and set `gpu-TextureTest` as the startup project.  Right click and select 'Build` (you must force the build because by default Visual Studio will not build any of the test executables).  In the TextureTest.cpp file place a breakpoint in `cleanupTestCase`.  Execute the program.  When the breakpoint is hit, look at the console window in which the app is running.  It should have some logging along with a final pass or failure message.  If there is a failure, it will indicate the line of the failure.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9586/app_13125_PR_25ce14d2bb4fcc6201adcb8bdd3a8562fc001353.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9586/HighFidelity-Beta-PR13125-25ce14d2bb4fcc6201adcb8bdd3a8562fc001353.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9586/HighFidelity-Beta-Interface-PR13125-25ce14d2bb4fcc6201adcb8bdd3a8562fc001353.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9586/HighFidelity-Beta-PR13125-25ce14d2bb4fcc6201adcb8bdd3a8562fc001353.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9586/HighFidelity-Beta-Interface-PR13125-25ce14d2bb4fcc6201adcb8bdd3a8562fc001353.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9603/app_13125_PR_0725210b7c8a6d234e7b66db9943878c1d29c610.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9603/HighFidelity-Beta-PR13125-0725210b7c8a6d234e7b66db9943878c1d29c610.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9603/HighFidelity-Beta-Interface-PR13125-0725210b7c8a6d234e7b66db9943878c1d29c610.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9603/HighFidelity-Beta-PR13125-0725210b7c8a6d234e7b66db9943878c1d29c610.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9603/HighFidelity-Beta-Interface-PR13125-0725210b7c8a6d234e7b66db9943878c1d29c610.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9615/app_13125_PR_2042e9143a26424e0633e48b377994abd53590dc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9615/HighFidelity-Beta-PR13125-2042e9143a26424e0633e48b377994abd53590dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9615/HighFidelity-Beta-Interface-PR13125-2042e9143a26424e0633e48b377994abd53590dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9615/HighFidelity-Beta-PR13125-2042e9143a26424e0633e48b377994abd53590dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9615/HighFidelity-Beta-Interface-PR13125-2042e9143a26424e0633e48b377994abd53590dc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9628/app_13125_PR_d4a8747d339f14113a68a87bcce87221e83b89a4.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9631/app_13125_PR_f17f1de721ff45a6fd7d2c22ef41986165d7bd38.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9631/HighFidelity-Beta-PR13125-f17f1de721ff45a6fd7d2c22ef41986165d7bd38.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9631/HighFidelity-Beta-Interface-PR13125-f17f1de721ff45a6fd7d2c22ef41986165d7bd38.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9640/app_13125_PR_51a478fc4cb39755d0864a056a57462eab43f19f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9640/HighFidelity-Beta-PR13125-51a478fc4cb39755d0864a056a57462eab43f19f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9640/HighFidelity-Beta-Interface-PR13125-51a478fc4cb39755d0864a056a57462eab43f19f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9640/HighFidelity-Beta-PR13125-51a478fc4cb39755d0864a056a57462eab43f19f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9640/HighFidelity-Beta-Interface-PR13125-51a478fc4cb39755d0864a056a57462eab43f19f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9644/app_13125_PR_57691d5d66cafb7cf55216f96f3b32426fee3a20.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9644/HighFidelity-Beta-PR13125-57691d5d66cafb7cf55216f96f3b32426fee3a20.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9644/HighFidelity-Beta-Interface-PR13125-57691d5d66cafb7cf55216f96f3b32426fee3a20.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9644/HighFidelity-Beta-PR13125-57691d5d66cafb7cf55216f96f3b32426fee3a20.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9644/HighFidelity-Beta-Interface-PR13125-57691d5d66cafb7cf55216f96f3b32426fee3a20.exe

**Comment by AndrewMeadows** [comment]
`gpu-TextureTest` does not successfully build on linux for this error:
```
tests/gpu/src/TextureTest.cpp: In member function ‘void TextureTest::testTextureLoading()’:
tests/gpu/src/TextureTest.cpp:209:34: error: ‘uint64’ was not declared in this scope
         reportEvery(lastReport, (uint64-t)4, reportLambda);
                                  ^~~~~~
```
The problem appears to be: `usecTimestampNow()` returns `quint64` which cannot be combined with a `uint64_t` in a templated version of `reportEvery()`

**Comment by AndrewMeadows** [comment]
When I fix the compile errors the new unit test gpu-TextureTest does run successfully:
```
$ ctest -R gpu-TextureTest
Test project /home/andrew/work/hifi/build/tests
    Start 6: gpu-TextureTest-test
1/1 Test #6: gpu-TextureTest-test .............   Passed    1.61 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.61 sec
```

**Comment by Atlante45** [comment]
Build command failed on mac, but I was able to build it from Xcode by selecting the target directly.
Tests runs successfully:
```
> $ ctest -R gpu-TextureTest
Test project /Users/clement/hifi/build/tests
    Start 6: gpu-TextureTest-test
1/1 Test #6: gpu-TextureTest-test .............   Passed   12.40 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =  12.40 sec
```

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9663/app_13125_PR_cb336bdeab4b0400af37fdf62073566f8106bd35.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9663/HighFidelity-Beta-PR13125-cb336bdeab4b0400af37fdf62073566f8106bd35.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9663/HighFidelity-Beta-Interface-PR13125-cb336bdeab4b0400af37fdf62073566f8106bd35.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9663/HighFidelity-Beta-PR13125-cb336bdeab4b0400af37fdf62073566f8106bd35.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9663/HighFidelity-Beta-Interface-PR13125-cb336bdeab4b0400af37fdf62073566f8106bd35.exe

**Comment by samcake** [comment]
Alright this has been qa ed by  several devs on all the platform
we think we are good to go
merging

**Pull request merged**
