### PR TITLE
Bloom and Temporal Anti-Aliasing improvements

### PR DESCRIPTION
**Pull request by Zvork**
This PR improves on both the temporal antialiasing and bloom effects by modifying the sequencing of a number of rendering passes:
- The TAA (antialiasing) pass is moved before the Bloom to stabilize high color intensity pixels and thus drastically reduce the bloom flickering. Bloom is now temporarily stable and thus perfectly usable (IMHO) in HMD mode.
- The in-front overlay rendering pass has been moved before the TAA pass so in-front overlays benefit from some anti-aliasing. This is not totally perfect as these in-front overlays, like transparent objects, do not update the velocity buffer (yet). The side effect is that in-front overlays potentially participate in the bloom effect if they have particularly high intensity pixels.
- The highlight pass has also been moved before the TAA / Bloom passes so as to be still before the in-front overlays. The nice side effect is that highlights are now also anti-aliased but they are also potentially "bloomed", although this is hardly noticeable.

# TAA technical update (for the graphics geeks out there)
The TAA pass performs antialising on a tonemapped version of the rendering. As the bloom, which is the following pass, should be applied to a non-tonemapped HDR image, the antialiasing shader performs a "on the fly" rapid tonemap when reading color values followed by a rapid inverse tone map when writing back the antialiased result.
Also, the texture fetches for the GBuffer material (albedo, normal, metal, roughness, etc...) have now a fixed LOD bias to force fetching of a lower (higher resolution) mip level. Since TAA performs some kind of super sampling (and thus texture filtering), this is used to try to extract some more resolution during rendering.

# Test plan
As the order of a number of rendering passes have been changed, this PR should be thoroughly tested on all platforms and devices, especially on HMD and both NVidia and AMD GPUs.
Automatic test plans pertaining to this PR are:
- The TAA test plan proposed in [hifi_tests PR #70](https://github.com/highfidelity/hifi_tests/pull/70)
- The new Bloom test plan proposed in [tests/engine/render/effect/bloom](https://github.com/highfidelity/hifi_tests/tree/master/tests/engine/render/effect/bloom)
- The highlight test in [hifi_tests/tests/engine/render/effect/highlight](https://github.com/highfidelity/hifi_tests/tree/master/tests/engine/render/effect/highlight)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8695/app_12861_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8695/HighFidelity-Beta-PR12861-9ca0b39f7476b392c717b8dd26b6ac02ca79a4a9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8695/HighFidelity-Beta-PR12861-9ca0b39f7476b392c717b8dd26b6ac02ca79a4a9.exe

**Comment by Zvork** [comment]
Added a number of improvement that reduces the overral "blurry" look of the TAA.
- Reduced the jitter extents (was previously bizarelly 2 pixels, and now only 1)
- Correct reprojection with "unjittered" matrices.

TAA has also been removed on all "Web browser" objects, such as the Tablet to try to fix bug [#13741.](https://highfidelity.manuscript.com/f/cases/13741/) With the reduced jitter, it less distracting but the edges of these objects are now aliased again.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8851/app_12861_PR_0800c5eeb9e2820582823b627f222dd37dfe410c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8851/HighFidelity-Beta-PR12861-0800c5eeb9e2820582823b627f222dd37dfe410c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8851/HighFidelity-Beta-Interface-PR12861-0800c5eeb9e2820582823b627f222dd37dfe410c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8851/HighFidelity-Beta-PR12861-0800c5eeb9e2820582823b627f222dd37dfe410c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8851/HighFidelity-Beta-Interface-PR12861-0800c5eeb9e2820582823b627f222dd37dfe410c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8979/HighFidelity-Beta-PR12861-46a1ff4dd277c5dd9735a1a1457d356c9f8b2307.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8979/HighFidelity-Beta-Interface-PR12861-46a1ff4dd277c5dd9735a1a1457d356c9f8b2307.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8979/HighFidelity-Beta-PR12861-46a1ff4dd277c5dd9735a1a1457d356c9f8b2307.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8979/HighFidelity-Beta-Interface-PR12861-46a1ff4dd277c5dd9735a1a1457d356c9f8b2307.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9018/app_12861_PR_fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9018/HighFidelity-Beta-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9018/HighFidelity-Beta-Interface-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9018/HighFidelity-Beta-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9018/HighFidelity-Beta-Interface-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9071/app_12861_PR_fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9071/HighFidelity-Beta-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9071/HighFidelity-Beta-Interface-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9071/HighFidelity-Beta-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9071/HighFidelity-Beta-Interface-PR12861-fbd06f7d5ecce65aa6a1c470f38c23438ad2971a.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
Build will not run on Mac OS (crashes on launch). Logs of this are attached in folder. Windows results:

1) On the first script, 2 of our machines (GTX 1070,  1080) the spheres on the left did not appear. In addition the top wire frame sphere is visible through the tablet. Video and log attached.
2) Interface crashed immediately when script was loaded. (Logs attached)
3) Interface crashed immediately  when script was loaded. (Logs attached)

Bonus Crash:
Walking into mirror activation zone causes crash. Video and logs attached.
[Files.zip](https://github.com/highfidelity/hifi/files/1943325/Files.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9150/app_12861_PR_c0b5bc8ffd9facb00616870655ae9aeae0f2a263.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9150/HighFidelity-Beta-PR12861-c0b5bc8ffd9facb00616870655ae9aeae0f2a263.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9150/HighFidelity-Beta-Interface-PR12861-c0b5bc8ffd9facb00616870655ae9aeae0f2a263.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9150/HighFidelity-Beta-PR12861-c0b5bc8ffd9facb00616870655ae9aeae0f2a263.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9150/HighFidelity-Beta-Interface-PR12861-c0b5bc8ffd9facb00616870655ae9aeae0f2a263.exe

**Comment by Zvork** [comment]
Tests should be extended to text entities and text overlays.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9154/app_12861_PR_e37b18336a63213ba0fbffcbdc9dcd2a4b941398.apk

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9154/HighFidelity-Beta-Interface-PR12861-e37b18336a63213ba0fbffcbdc9dcd2a4b941398.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9154/HighFidelity-Beta-PR12861-e37b18336a63213ba0fbffcbdc9dcd2a4b941398.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9154/HighFidelity-Beta-Interface-PR12861-e37b18336a63213ba0fbffcbdc9dcd2a4b941398.exe

**Comment by samcake** [comment]
Good  to go

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Scripts run and and look good. Mac crash no longer occurs.

**Pull request merged**
