### PR TITLE
DO NOT MERGE  --> EXPERIMENTAL: ELBOWS RESPOND TO WRIST ORIENTATION

### PR DESCRIPTION
**Pull request by amantley**
This pr enables the elbow pole vector to compensate for the orientation of the hand so that we can avoid painful wrist contortions.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18621/HighFidelity-Beta-PR15341-df357a2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18621/HighFidelity-Quest-Beta-PR15341-df357a2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18621/HighFidelity-Beta-PR15341-df357a2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18621/HighFidelity-Beta-Interface-PR15341-df357a2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18630/HighFidelity-Beta-PR15341-3ce5988.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18630/HighFidelity-Beta-Interface-PR15341-3ce5988.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18630/HighFidelity-Beta-PR15341-3ce5988.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18630/HighFidelity-Quest-Beta-PR15341-3ce5988.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18630/HighFidelity-Beta-PR15341-3ce5988.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18630/HighFidelity-Beta-Interface-PR15341-3ce5988.exe

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18745/HighFidelity-Beta-PR15341-3ce5988.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18745/HighFidelity-Beta-Interface-PR15341-3ce5988.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18745/HighFidelity-Beta-PR15341-3ce5988.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18745/HighFidelity-Quest-Beta-PR15341-3ce5988.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18745/HighFidelity-Beta-PR15341-3ce5988.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18745/HighFidelity-Beta-Interface-PR15341-3ce5988.exe

**Pull request closed without merging**
