### PR TITLE
Remove tabs from oculus store inventory, and rename to match

### PR DESCRIPTION
**Pull request by howard-stearns**
https://highfidelity.atlassian.net/wiki/spaces/HOME/pages/414187673/Get+rid+of+tabs+in+oculus+store+version+of+assets+app

### CODE REVIEW

**Comment by howard-stearns** [comment]
DNM until:
- [ ] #14261 is merged. (The stuff specific to this PR is actually quite tiny, so the diff will be much smaller once that is merged.)
- [ ] #14317 is merged. (Which relocates a tab to settings, containing things that are still necessary.)
- [ ] The .svg and glyph assets are incorporated.
- [ ] The design is approved.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14584/HighFidelity-Beta-PR14319-3e2d6c3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14584/HighFidelity-Beta-PR14319-3e2d6c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14584/HighFidelity-Beta-Interface-PR14319-3e2d6c3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14602/HighFidelity-Beta-PR14319-8256bfb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14602/HighFidelity-Beta-PR14319-8256bfb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14602/HighFidelity-Beta-Interface-PR14319-8256bfb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14602/HighFidelity-Beta-PR14319-8256bfb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14602/HighFidelity-Beta-Interface-PR14319-8256bfb.exe

**Comment by changxc** [comment]
1. minor change: could we remove 'shopping' on both oculus store and non-oclulus store version
image
2. minor change: could we say 'Date acquired', ‘Original Price', 'Free' on the certificates, on both oculus store and non-oclulus store version
image
I will continue to explore but it looks pretty good to me mostly 👍

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14693/HighFidelity-Beta-PR14319-7115f0e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14693/HighFidelity-Beta-Interface-PR14319-7115f0e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14693/HighFidelity-Beta-PR14319-7115f0e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14693/HighFidelity-Beta-Interface-PR14319-7115f0e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14726/HighFidelity-Beta-PR14319-f10b9ae.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14726/HighFidelity-Beta-PR14319-f10b9ae.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14726/HighFidelity-Beta-Interface-PR14319-f10b9ae.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14726/HighFidelity-Beta-PR14319-f10b9ae.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14726/HighFidelity-Beta-Interface-PR14319-f10b9ae.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14749/HighFidelity-Beta-PR14319-3359475.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14749/HighFidelity-Beta-PR14319-3359475.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14749/HighFidelity-Beta-Interface-PR14319-3359475.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14749/HighFidelity-Beta-PR14319-3359475.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14749/HighFidelity-Beta-Interface-PR14319-3359475.exe

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14757/HighFidelity-Beta-PR14319-89656ea.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14757/HighFidelity-Beta-PR14319-89656ea.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14757/HighFidelity-Beta-Interface-PR14319-89656ea.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14757/HighFidelity-Beta-PR14319-89656ea.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14757/HighFidelity-Beta-Interface-PR14319-89656ea.exe

**Pull request merged**
