### PR TITLE
Made handControllerPointer into modules in hope of preventing mouse cursor interference with tablet

### PR DESCRIPTION
**Pull request by druiz17**
handControllerPointer would at time my the mouse cursor right on your tablet. This caused may focus issues with the tablet. I finally move handControllerPointer to a module to try prevent this interference.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3571/HighFidelity-Beta-PR11444-ee9ac3e7f9c4b9d92090b29a6ea9b8af32b7562e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3571/HighFidelity-Beta-PR11444-ee9ac3e7f9c4b9d92090b29a6ea9b8af32b7562e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3576/HighFidelity-Beta-PR11444-b8ee60a394d01cdf4b3813e495924345c081e33e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3576/HighFidelity-Beta-PR11444-b8ee60a394d01cdf4b3813e495924345c081e33e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3598/HighFidelity-Beta-PR11444-b1b31444f0859c8a864369134009791cc10ecfcc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3598/HighFidelity-Beta-PR11444-b1b31444f0859c8a864369134009791cc10ecfcc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3603/HighFidelity-Beta-PR11444-ec40df711d8f2b9a3165bd07f43a0bcfcf78b5e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3603/HighFidelity-Beta-PR11444-ec40df711d8f2b9a3165bd07f43a0bcfcf78b5e1.exe

**Comment by anshuman64** [comment]
To test:
Try your best to break the tablet in HMD mode. Press buttons, scroll, etc. using a combination of the stylus, lasers, and mouse pointer. Let us know of unexpected behavior you find.

**Comment by anshuman64** [comment]
Here is the list of issues I found (to be addressed in future PR): 
- Go to Menu > Settings and using both styluses, rapidly switch between tapping "Advanced Menus" and "Developer" menus. Very shortly, you will get in a state where clicking and highlighting completely breaks.
- When under heavy load (ex. when loading a domain), open the tablet. The stylus is frequently in the wrong place on the avatar.
- Try typing "dfdfdfdfdfdfdfdfdf" by quickly switching between the letters. Comes out as "fffffffffff"
- Use mouse in HMD mode and place the cursor on the tablet. The cursor continues to highlight the item even after you tap something with the laser or stylus

**Comment by PhilipRosedale** [comment]
Some notes on using this PR: 

using either the keyboard or the main tablet buttons, it is possible to 'break' individual keys and cause them to stop responding to clicks.  The way to do this is to press the stylus through one key, and then at the same time press the stylus through another key.  By doing this a couple times, you will break one or both of the keys and they will not respond anymore until you close and re-open the keyboard.   It isn't possible to break the keyboard in this way using the lasers, it seems to be a problem with having two active styluses at the same time.

**Pull request merged**
