### PR TITLE
Tuned haptic pulses for grab, release, equip, de-quip

### PR DESCRIPTION
**Pull request by PhilipRosedale**
For Vive, tuned haptic pulses for grab script: 

Near and Far grab/release now make a very slight pulse.
When the hand is in an equip sphere, there will be a textured feeling - very small vibrates as you move.
When turning upside down to release, you will feel a smaller pulse than before. 

TEST PLAN: 

Near and Far grab and equip/drop multiple things with both hands.  You should feel haptics as described above.   When showing and releasing search beam when nothing is grabbed, you should NOT feel anything.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0f7f9990c2d70b59414c60d5eff28e7cc4d8def2 available at: https://gist.github.com/c7f6a23f611a0d46ba0b498ee76d1a2c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-0f7f999.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-0f7f999.dmg

**Comment by SkimiMission** [comment]
## QA Pass

I like the new haptics feedback when grab, equip/drop. Works fine with single or both hands.

**Comment by PhilipRosedale** [comment]
Removed extra pulse on release.   See edit to test plan above.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f37570dc9ac574db3cb28565abbbc482915e094c available at: https://gist.github.com/c7f6a23f611a0d46ba0b498ee76d1a2c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-f37570d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-f37570d.dmg

**Comment by PhilipRosedale** [comment]
@sethalves @imgntn Can one of you test the release behavior for near and far grab on hydra?  I switched to use the click detent for release, which is better on the Vive but I am not sure how the controller maps this on the hydra.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 516780934230e1d9ec4914b1e4ad2f607873cf15 available at: https://gist.github.com/c7f6a23f611a0d46ba0b498ee76d1a2c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-5167809.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-5167809.dmg

**Comment by imgntn** [comment]
testing

**Comment by imgntn** [comment]
didn't notice anything particular about near + far grabbing the home content with the hydra

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 516780934230e1d9ec4914b1e4ad2f607873cf15 available at: https://gist.github.com/c7f6a23f611a0d46ba0b498ee76d1a2c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-5167809.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8327-5167809.dmg

**Pull request merged**
