### PR TITLE
Beta Release 60 - Includes up to Developer Release 7493

### PR DESCRIPTION
**Pull request by ZappoMan**
- Commerce: A cryptocurrency-based content protection and payment system that facilitates a vibrant virtual economy for digital goods and services
- Fix: stylus interaction is still very glitchy
- Fixed an issue that caused local entities to disappear for others after a while.
- Fixed a parenting issue where movement stops if an entity is parented while in motion
- Quickly switching domain can result in domain not loading
- Fixed inconsistency in seeing avatar entities
- Tablet home button highlight size incorrect when you change avatar scale
- Reflection in mirror should work when avatar is close to mirror
- Added a collapse button on the tablet keyboard
- fixed the use of the tablet in 3rd person view in VR
- Fixed issue of not being able to bring up Hifi Log
- Fixed minor bug where the keyboard would not dismiss after hitting enter
- Fixed a scripting issue where My.Avatar.getEyeHeight() always returned the same value
- Fixed an issue with the Display menu where it was possible for no option to be selected.
- Fixed issue with the Enter key opening the wrong window in Desktop mode.
- The Info overlay on marketplace items looks correct even when the avatar is large or small.
- Lasers appear at the correct size when the avatar is scaled up or down.
- Notifications appear at the correct size even when the avatar is scaled up or down.  
- Added ability to turn up or down all avatar volume
- This PR improves the interaction of laser pointers and stylus with the tablet to be faster and more responsive.
- Fix for lighting being rotated by 90 degrees.
- Assets do not reload after network disconnect
- Fixes the issue where sometimes assignment clients don't get killed after quitting the domain server.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5207/HighFidelity-Beta-PR11887-e6c6e5f23923cab3d05fb906ed0d7816475c7d67.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5210/HighFidelity-Beta-PR11887-e6c6e5f23923cab3d05fb906ed0d7816475c7d67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5210/HighFidelity-Beta-PR11887-e6c6e5f23923cab3d05fb906ed0d7816475c7d67.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5231/HighFidelity-Beta-PR11887-8eb8cb099488aba90cae880392fa103f34c513e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5231/HighFidelity-Beta-PR11887-8eb8cb099488aba90cae880392fa103f34c513e5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5267/HighFidelity-Beta-PR11887-be083664fb36e4a25d3f2b136559cb8c6c9daa54.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5270/HighFidelity-Beta-PR11887-be083664fb36e4a25d3f2b136559cb8c6c9daa54.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5271/HighFidelity-Beta-PR11887-be083664fb36e4a25d3f2b136559cb8c6c9daa54.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5272/HighFidelity-Beta-PR11887-be083664fb36e4a25d3f2b136559cb8c6c9daa54.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5272/HighFidelity-Beta-PR11887-be083664fb36e4a25d3f2b136559cb8c6c9daa54.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5289/HighFidelity-Beta-PR11887-785eedfb1ce796508b52ecae8216b6b875c09ca6.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5293/HighFidelity-Beta-PR11887-785eedfb1ce796508b52ecae8216b6b875c09ca6.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5295/HighFidelity-Beta-PR11887-785eedfb1ce796508b52ecae8216b6b875c09ca6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5295/HighFidelity-Beta-PR11887-785eedfb1ce796508b52ecae8216b6b875c09ca6.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5333/HighFidelity-Beta-PR11887-3fb1df88cb0139f4f0f3077440bc9c904f6bec3f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5333/HighFidelity-Beta-PR11887-3fb1df88cb0139f4f0f3077440bc9c904f6bec3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5341/HighFidelity-Beta-PR11887-fe16cc3fab764e898c74a3562bf33d4365dad92e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5341/HighFidelity-Beta-PR11887-fe16cc3fab764e898c74a3562bf33d4365dad92e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5348/HighFidelity-Beta-PR11887-b2c5154cb646ff18fa0328a99b51fb6acb71c42c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5348/HighFidelity-Beta-PR11887-b2c5154cb646ff18fa0328a99b51fb6acb71c42c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5351/HighFidelity-Beta-PR11887-218b4635b2eb3aca3381fcdee4a0ff742a97aeb2.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5352/HighFidelity-Beta-PR11887-218b4635b2eb3aca3381fcdee4a0ff742a97aeb2.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5353/HighFidelity-Beta-PR11887-218b4635b2eb3aca3381fcdee4a0ff742a97aeb2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5353/HighFidelity-Beta-PR11887-218b4635b2eb3aca3381fcdee4a0ff742a97aeb2.dmg

**Pull request merged**
