### PR TITLE
Update WASAPI audio plugin for Qt5.6.2

### PR DESCRIPTION
**Pull request by kencooke**
This version rebases the WASAPI plugin on release code from qtmultimedia 5.7.1 (the final version that is binary compatible with the 5.6 framework) instead of a pre-5.7 dev branch for WINRT. It's been compiled and linked against the Qt5.6.2 msvc2013_64 framework.

It's now much closer to the standard Qt plugin, but these fixes/enhancements are still needed:
- bugfix to reduce the latency
- bugfix to avoid leaking memory when polling for device changes
- support for hot-unplugging of in-use audio devices without crashing
- support for multichannel audio devices
- revert Qt threading changes that cause deadlock
 
The changes are checked in here: https://github.com/kencooke/qtmultimedia/commits/5.7

### CODE REVIEW

**Comment by kencooke** [comment]
### Test Plan

General test of Interface audio functionality. There should be no observable differences.

Test both recording and playback.
Test switching between audio devices using the main menu.
Test hot-unplugging a USB device, then plug back in and reselect it from main menu.

NOTE: there are issues with the tablet audio menu that are unrelated to this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e77771c997838f3fd7d10ca3efba695c50b1a6a available at: https://gist.github.com/7aa045af59b108a6e151f2350d896943<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-9e77771.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-9e77771.dmg

**Comment by cozza13** [comment]
I keep crashing with a deadlock on start. Here is the splat https://www.bugsplat.com/individualCrash/?id=11598&database=interface_alpha

**Comment by hifi-gustavo** [comment]
Build console output for commit: 807a6d583197a40a5cf04f977cde593d133fb5e2 available at: https://gist.github.com/7aa045af59b108a6e151f2350d896943<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-807a6d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-807a6d5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 746ae6dfd3696d063bc2a0fb8107e4c8cb86fb29 available at: https://gist.github.com/7aa045af59b108a6e151f2350d896943<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-746ae6d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-746ae6d.dmg

**Comment by kencooke** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 807a6d583197a40a5cf04f977cde593d133fb5e2 available at: https://gist.github.com/7aa045af59b108a6e151f2350d896943<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-807a6d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10320-807a6d5.dmg

**Comment by Nex-Pro** [comment]
Testing this with two audio devices.

**Comment by Nex-Pro** [comment]
### PASS

In addition I added an extra test.

My USB headset has a mode switch allowing it to connect to Xbox.  I was able to use this switch to disable the USB headset. Selecting an alternate output updated the available devices correctly. Re-enabling PC mode on the USB headset did not make the list of devices update but selecting one of the other options forced an update. The USB device then was displayed and functioned correctly.

Unrelated problem with HMD audio menu confirmed. I assume that has been posted.

Good work @kencooke

**Pull request merged**
