### PR TITLE
Expose Window.getDeviceSize()

### PR DESCRIPTION
**Pull request by SamGondelman**
Window.getDeviceSize() returns the dimensions of the display to which we are rendering.

Related to [FB8859](https://highfidelity.fogbugz.com/f/cases/8859).

Test plan:
- Desktop: https://highfidelity.testrail.net/index.php?/cases/view/1817
- Vive/Rift: https://highfidelity.testrail.net/index.php?/cases/view/1816

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5230/HighFidelity-Beta-PR11892-c5ebb8a279b57feb981709568b61cbbec9bce836.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5230/HighFidelity-Beta-PR11892-c5ebb8a279b57feb981709568b61cbbec9bce836.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
Tested on VIVE only.

test rail Pass.  Please read comment on testrail.

https://highfidelity.testrail.net/index.php?/tests/view/21519&group_by=cases:section_id&group_order=asc&group_id=71

**Pull request merged**
