### PR TITLE
avoid static_casting void* of class hierarchies of motion-states

### PR DESCRIPTION
**Pull request by sethalves**
- possible fix for physics related crash

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/4414/CRASH-in-EntityMotionState-handleDeactivation

**Comment by sethalves** [comment]
to test:
- smoke test physics and collisions and actions (near and grabbing)

**Comment by CainFoool** [comment]
Will test once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/145/HighFidelity-Beta-PR10540-65d060a69cf200946cda86c93ad57dcafe849b51.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/145/HighFidelity-Beta-PR10540-65d060a69cf200946cda86c93ad57dcafe849b51.dmg

**Comment by Nex-Pro** [comment]
@cain you can't test this without hand controllers

**Comment by CainFoool** [comment]
@Nex-Pro I was asked in PM to pretty much just try and break any physics.

**Comment by Nex-Pro** [comment]
@CainFoool 
read it again  you can't do near and far grabbing

**Comment by CainFoool** [comment]
@Nex-Pro Go ahead then.

**Comment by Nex-Pro** [comment]
@CainFoool  check with @sethalves  if this can be completed without a vive or oculus

**Comment by CainFoool** [comment]
@Nex-Pro Just checked, mouse grab is all good. :)

**Comment by CainFoool** [comment]
# Test Passed 

Everything seems to be working okay in regards to physics cross-domains.

**Comment by sethalves** [comment]
Andrew is going to try a different approach.  We'll remember this PR for reference, but wont merge it.

**Pull request closed without merging**
