### PR TITLE
Fix tablet webview showing incorrect url.

### PR DESCRIPTION
**Pull request by druiz17**
make the TabletWebView show the correct url

### CODE REVIEW

**Comment by zfox23** [comment]
I like this. One less duplicated piece of the WebEngineView pie. Thanks.

**Comment by druiz17** [comment]
Test plan
- In goto, click on the (i) for a location or snapshot
- once the web page is loaded check if the URL displayed is correct.
- now click on the hostname or snapshot taker (depending if you clicked on a snapshot or location), once the web pages changes check that the URL is correct.
- do the same for other the facebook and twitter link.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5390a29859df2d7ce7a19247494b5074190f5be5 available at: https://gist.github.com/c27b3120508d5351bc5ecb8a73d6337b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10369-5390a29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10369-5390a29.dmg

**Comment by zfox23** [comment]
testing now

**Comment by zfox23** [comment]
Back button _behavior_ is still wonky (i.e. I can get stuck in a loop where pressing back over and over brings me between the same two pages), but this PR fixes what it was supposed to. Approved!

**Pull request merged**
