### PR TITLE
add a timeout for ICE server DNS lookup

### PR DESCRIPTION
**Pull request by birarda**
- time out ICE server DNS lookups that don't callback in 5 seconds

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2765/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.dmg

**Comment by birarda** [comment]
test this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2791/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.dmg

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2802/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2807/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2807/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.dmg

**Comment by birarda** [comment]
#### Test Plan

1. Run the Sandbox from this PR and confirm that you get a temporary place name.
2. Connect to that temporary place name from your local Interface client.
3. Confirm that another user (who can use dev-download build or this PR build) is able to connect via your temporary place name.

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2816/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2816/HighFidelity-Beta-PR11244-3003f64514de62bdf43c5a8afd338404ca718abf.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Run the Sandbox from this PR and confirm that you get a temporary place name. **Pass**
Connect to that temporary place name from your local Interface client. **Pass**
Confirm that another user (who can use dev-download build or this PR build) is able to connect via your temporary place name. **Pass, Used PR build**

**Notes: Did experience an insta-crash upon first time running on 1st computer, 2nd computer had no crashes. Sent bug report just in-case.**

**Pull request merged**
