### PR TITLE
remove chat from default scripts

### PR DESCRIPTION
**Pull request by sethalves**
- remove chat from default scripts, for now

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- reset settings
- run interface, look at toolbar or open tablet, see that chat button is no longer there

**Comment by CainFoool** [comment]
Will test shortly.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/750/HighFidelity-Beta-PR10704-023ca8562301eb3fbd7c235afb1d7b17112b969b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/750/HighFidelity-Beta-PR10704-023ca8562301eb3fbd7c235afb1d7b17112b969b.dmg

**Comment by CainFoool** [comment]
# Test Passed

Chat button is gone from toolbar.

**Pull request merged**
