### PR TITLE
Reinstate Overlays.getOverlayObject API function

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

- Run the attached script.
- An overlay should appear in front of your avatar with the text, "HELLO" in the top right corner.
- In your program log you should see the following message from the script every 2 seconds: "hello".

[testWeb3d.zip](https://github.com/highfidelity/hifi/files/1831917/testWeb3d.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8173/app_12689_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8173/HighFidelity-Beta-PR12689-8df6cd58c67bb649f7140872b32f100a2a18f471.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8173/HighFidelity-Beta-PR12689-8df6cd58c67bb649f7140872b32f100a2a18f471.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8278/app_12689_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8278/HighFidelity-Beta-PR12689-8df6cd58c67bb649f7140872b32f100a2a18f471.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Script runs, overlay displays, and text in log displays.

**Pull request merged**
