### PR TITLE
Support for the 3ds Max object offset feature

### PR DESCRIPTION
**Pull request by hyperlogic**
FBXReader now supports the GeometricTranslation, GeometricRotation and GeometricScaling FBX fields.
These offsets are applied directly to the mesh vertices, as they are never animated and the rest of our
rendering and animation system would have difficulty supporting them otherwise.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/edit/473/3ds-max-exported-FBX-files-do-not-display-correctly

**Comment by hyperlogic** [comment]
QA test:
* add this model into a domain: https://s3.amazonaws.com/hifi-public/tony/object-offset-test.fbx
* It should display as 5 roughly equal sized cubes aligned in a row.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e96676fea41751f51ed611c57c1d3cfbd5e489ac available at: https://gist.github.com/1fd51bbb0d03dc1aaae4a8795100d1df<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9138-e96676f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9138-e96676f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 68b103b46b72d0775e890cabea62358d39cfe0f4 available at: https://gist.github.com/1fd51bbb0d03dc1aaae4a8795100d1df<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9138-68b103b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9138-68b103b.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass

Compared to Master (5744) where I get;

hifi-snap-by-omegaheron-on-2016-12-01_22-12-37

This PR;

hifi-snap-by-omegaheron-on-2016-12-01_22-14-32

General smoke test (Checked models I have exported from Blender and MayaLT 2017, dev-playa and dev-demo, everything looks right) = pass.

**Comment by OmegaHeron** [comment]
Hold QA Pass - I'm running into an issue I need to isolate to this PR or something recently introduced.  When I reset sensors with `'` my avatar is returned to its rez in location in domain.  It may be morning before I can sort this out, getting late in my local time zone.

**Comment by OmegaHeron** [comment]
QA Pass restored

It's from 5749 #8691 
Will document in fogbugz as I can't imagine what I'm seeing is intended behavior for desktop mode use.

**Pull request merged**
