### PR TITLE
Case 22467: Fix material target tooltip

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.manuscript.com/f/cases/22467/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19189/HighFidelity-Beta-PR15508-0da318f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19189/HighFidelity-Quest-Beta-PR15508-0da318f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19189/HighFidelity-Beta-PR15508-0da318f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19189/HighFidelity-Beta-Interface-PR15508-0da318f.exe

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19226/HighFidelity-Beta-PR15508-0da318f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19226/HighFidelity-Quest-Beta-PR15508-0da318f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19226/HighFidelity-Beta-PR15508-0da318f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19226/HighFidelity-Beta-Interface-PR15508-0da318f.exe

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19246/HighFidelity-Beta-PR15508-0da318f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19246/HighFidelity-Quest-Beta-PR15508-0da318f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19246/HighFidelity-Beta-PR15508-0da318f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19246/HighFidelity-Beta-Interface-PR15508-0da318f.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19323/HighFidelity-Beta-PR15508-0da318f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19323/HighFidelity-Beta-Interface-PR15508-0da318f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19323/HighFidelity-Beta-PR15508-0da318f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19323/HighFidelity-Beta-Interface-PR15508-0da318f.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19323/HighFidelity-Beta-PR15508-0da318f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19323/HighFidelity-Quest-Beta-PR15508-0da318f.apk)

**Pull request merged**
