### PR TITLE
make marketplace button state match whether tablet is being shown

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes https://highfidelity.fogbugz.com/f/cases/1615/Market-icon-does-not-remain-lit-when-market-tablet-is-active

### CODE REVIEW

**Comment by howard-stearns** [comment]
to test:
- in desktop, toggle the marketplace button on and off, and also turn it on but kill the 2d overlay marketplace window with the close/x button.  No matter what, the marketplace button should be "lit" IFF the marketplace window is visible.
- in hmd, toggle the marketplace button on and off. The button should be 'lit' IFF the marketplace table is visible.

(The behavior when switching between hmd and desktop while 'lit' is undefined, but recoverable. For example, if you switch from desktop to hmd while the window is open, you don't necessarily get a tablet, and vice versa. However, after switching and then toggling the button a bit, you should get back to a known state.)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 333ec388a86fe8c6703cd73816ac6c9f657ca919 available at: https://gist.github.com/a6ac17e72a77904cad4b199b72aa4066<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8773-333ec38.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8773-333ec38.dmg

**Comment by RyanDowne** [comment]
I can't test this because my client crashes immediately when trying to get to desktop mode

**Comment by howard-stearns** [comment]
The PR is pure javascript. So:
  - you must be crashing with master. If you pull the latest dev-download build you should be seeing the same behavior. 
  - you can test with any working build if you like, but it's a little convoluted:
      1. Developer->debug defaultScripts, and reload all scripts, to get them spread out.
      2. Manually kill the system-supplied marketplace.js
      3. Run the one from this pr. e.g., https://raw.githubusercontent.com/howard-stearns/hifi/333ec388a86fe8c6703cd73816ac6c9f657ca919/scripts/system/marketplaces/marketplace.js
      4. Test.
      5. To clean up, stop all scripts. Turn off developer->debug defaultScripts, and load defaults.

**Comment by ZappoMan** [comment]
I can test...

**Comment by ZappoMan** [comment]
Tested: works as described, Desktop and HMD.

**Pull request merged**
