### PR TITLE
Serverless tutorial rc66

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8265/app_12711_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8267/app_12711_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8267/HighFidelity-Beta-PR12711-60ed0336673f62f036620dfb33579734f70f2641.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8267/HighFidelity-Beta-PR12711-60ed0336673f62f036620dfb33579734f70f2641.dmg

**Comment by sethalves** [comment]
to test:
- make sure you are not running sandbox from some other installation
- when installing this PR, use "install custom" and don't install sandbox
- once interface starts, follow `https://highfidelity.fogbugz.com/f/cases/13693/Add-Local-Tutorial-test-plan-to-Acceptance-test`

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tutorial appeared and functioned as expected.

**Comment by conklin94122** [comment]
@sethalves ok to merge this into RC66 or not yet?

**Pull request merged**
