### PR TITLE
Fix materials to honor png texture opacity

### PR DESCRIPTION
**Pull request by zzmp**
Adds support for materials with PNG textures to use the alpha channel of the texture to determine if the item should be rendered as an opaque or translucent item.

### CODE REVIEW

**Comment by zzmp** [comment]
Adding DNM so that I can be the first to test this. Will remove when it is ready for QA.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2b3b931a81c9d6d2277214e7ade791918ebde46 available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbe8258aced9b07ba3d8feb71d13ea4dbaa5f27b available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by zzmp** [comment]
https://app.asana.com/0/74051501495175/83239698768106

#### Intents

Allow models using PNG textures with an alpha channel to be rendered as translucents.

#### Testing

Use this model: half of it should be transparent: https://s3-us-west-1.amazonaws.com/hifi-content/eric/models/boxTest.fbx (thanks to @ericrius1 for making it).
Please load a bunch of models to stress-test, as some model logic has changed.

**Comment by bluetoe** [comment]
This fails for me on win 7 nvidia gpu. This does make the box translucent but almost everything else has no textures except skyboxes, translucent things, web entities and a small number of models.

**Comment by bluetoe** [comment]
pr7281

**Comment by zzmp** [comment]
Thanks @bluetoe. I hadn't updated the shaders to reflect the new bit in the render key. It should be better now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9428e6f17f1fb8f293b0b98931f39c5ec60e7bbe available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2e0fe79aae95d646cdfb66a46cc6c918708f6a9 available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by bluetoe** [comment]
That last one seems to have fixed everything as far as I've seen. And the box is translucent now too. Looking good.

**Comment by bluetoe** [comment]
I have noticed one problem. attachments don't render the same. 
same model uploaded inworld looks good, translucent etc. but when you attach it to an avatar it reverts to old way:  alpha channel cuts off at 50% either on or off

**Comment by bluetoe** [comment]
Also, it would be nice if emissive would work with this. And glossiness/hardness, but that might be harder

**Comment by OmegaHeron** [comment]
Also checked on Windows 7 against some existing content I have that contain PNG+Alpha and have no issues - and I'm seeing the difference in render result for attachments as well.  Probably !pass until that's investigated more

**Comment by zzmp** [comment]
Thanks guys. Good catch with the avatar attachment notice. Marking DNM until I can fix that.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 812cc71c537c4e3c0d0c6661cae7da2469be6da6 available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a89a76dc4b8034833bea89fa6c011ffd91eb62bd available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9dcdf26567f5829b9973ede55b5c27b47988eb05 available at: https://gist.github.com/de8b319af0a4bda69512<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7281.dmg

**Comment by zzmp** [comment]
@bluetoe @OmegaHeron this one is finally ready for another go

**Comment by OmegaHeron** [comment]
Will take a look and report back after dinner.  :) :+1:

**Comment by bluetoe** [comment]
I have been using this PR a bit today and the alpha channel in .png textures look OK if they are just the albedo texture map. Also the problem with them not rendering correctly when in attachments is fixed, at least on the MAC. I had someone else show me what I looked like when having a .png alpha channel attachment.

I have not been able to see if attachments render correctly on WIN because at this point I only have one account and the other bug with attachments not rendering at all for stuff attached to yourself means that I can not see it, but I suspect it works too.

I will try to test this more tomorrow but one thing I have noticed is that when using other PBR stuff with it, I don't always get what I expect. Example is when using alpha png albedo texture and then using the same png for emmisive map, it shows as alpha but not emmisive.

Another one is using a png with alpha for albedo and using a different png for normal seems to make the albedo map revert back to the old binary alpha issue, either transparent or opaque.

I am not sure the PB rendering stuff is even part of this PR and to test it I have to make things to test it with.  Anyway, just feedback on what I've seen so far.

**Comment by zzmp** [comment]
@bluetoe can you give me your test models for the albedo/emissive and albedo/normal cases?

**Comment by zzmp** [comment]
I tried to test the albedo/normal case with my own model (https://s3-us-west-1.amazonaws.com/hifi-content/eric/models/boxTest2.fbx) and could not repro the issue that you had.

**Comment by zzmp** [comment]
@bluetoe marking this QA Approved, but please comment back when you can on your edge case. I'll log another issue when I know how to repro it and we can work on fixing it.

**Comment by Menithal** [comment]
Hey Guys,
as a heads up this broke a few things https://alphas.highfidelity.io/t/build-4441-issues-since-build-4439-related-to-alpha-transparency/10383

**Comment by zzmp** [comment]
Thanks @menithal! @samcake is already working on fixing up transparent shaders. I've seen the issue where an alpha channel is detected when none is present while breaking through code, though I didn't realize it was apparent anywhere. It's good to have a better example for it.

**Pull request merged**
