### PR TITLE
Fix for avatar recordings not playing back blendshapes

### PR DESCRIPTION
**Pull request by hyperlogic**
https://highfidelity.atlassian.net/browse/DEV-2621

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22344/HighFidelity-Beta-PR16456-da7b835.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22344/HighFidelity-Beta-Interface-PR16456-da7b835.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22369/HighFidelity-Beta-PR16456-da7b835.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22369/HighFidelity-Quest-Beta-PR16456-da7b835.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22369/HighFidelity-Beta-PR16456-da7b835.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22369/HighFidelity-Beta-Interface-PR16456-da7b835.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22369/HighFidelity-Beta-PR16456-da7b835.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22369/HighFidelity-Beta-Interface-PR16456-da7b835.exe

**Pull request merged**
