### PR TITLE
fix bookmarks, don't put :0 in urls

### PR DESCRIPTION
**Pull request by sethalves**
- fix bookmarks, don't put :0 in urls

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/14090/Navigate-Bookmarks-does-not-take-you-to-bookmarked-location

**Comment by sethalves** [comment]
to test:
- go someplace recognizable and bookmark the location
- go to some other domain
- activate the bookmark, make sure you're back where you expect to be
- enable advanced menus
- under the navigation menu, copy address to clipboard
- paste the clipboard into an editor
- make sure the url doesn't have :0 in it, meaning it should look like

hifi://hifiqa-rc/501.171,498.532,488.7/0,0.999842,0,-0.0177565

and not like

hifi://hifiqa-rc:0/501.171,498.532,488.7/0,0.999842,0,-0.0177565

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8844/HighFidelity-Beta-PR12914-515c185887163294238ffa36be942a3a2090031e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8844/HighFidelity-Beta-Interface-PR12914-515c185887163294238ffa36be942a3a2090031e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8844/HighFidelity-Beta-PR12914-515c185887163294238ffa36be942a3a2090031e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8844/HighFidelity-Beta-Interface-PR12914-515c185887163294238ffa36be942a3a2090031e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Attempted various URLs and none appeared with :0.

**Pull request merged**
