### PR TITLE
Make shaders GLES compatible

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Smoke Test.  Should not change application behavior.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test this.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3466/HighFidelity-Beta-PR11413-319b6c58c398c47951dfe1662d0466d70a39b901.exe

**Comment by YuppyPlays** [comment]
Testing complete:

Smoke Test. Should not change application behavior.
**Pass; general smoke test going through UI on desktop/HMD reveals no additional differences in behaviour and the performance appears to be normal.**

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3480/HighFidelity-Beta-PR11413-319b6c58c398c47951dfe1662d0466d70a39b901.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3480/HighFidelity-Beta-PR11413-319b6c58c398c47951dfe1662d0466d70a39b901.dmg

**Pull request closed without merging**
