### PR TITLE
upgrade bullet from 2.82 to 2.83.6

### PR DESCRIPTION
**Pull request by AndrewMeadows**
Bullet **2.82** was released back in May-2013 and Bullet **2.83.6** was released August-2015.  Most of the changes are in the demo-browser framework (which we're not using) but there are a few changes that we can use.  In particular the data members of **btCompoundShape** are **protected** instead of **private** which I expect to come in handy when experimenting with a dynamic compound shape for the avatar collisions.

The good news is that there were zero API changes for the features we're using.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37b22567151594efb4054f287bf5af15fec08173 available at: https://gist.github.com/31aa38fc061ac52af89f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5956.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5956.dmg

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37b22567151594efb4054f287bf5af15fec08173 available at: https://gist.github.com/31aa38fc061ac52af89f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5956.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5956.dmg

**Comment by AndrewMeadows** [comment]
Closing this: it builds fine for me on linux but breaks on Windows.  I'll work on this in my copious spare time and then test Mac.

**Pull request closed without merging**
