### PR TITLE
Fix for avatar flashing on fade out

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19846/Avatar-quickly-flashes-back-after-log-out-fade-effect

Test plan:
- Follow the steps from the ticket.
- You shouldn't see the other avatar flash after fading out.
- Try it multiple times.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15184/HighFidelity-Beta-PR14411-cddaa8b.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15184/HighFidelity-Beta-PR14411-cddaa8b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15184/HighFidelity-Beta-Interface-PR14411-cddaa8b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15187/HighFidelity-Beta-PR14411-ce9ed05.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15187/HighFidelity-Beta-PR14411-ce9ed05.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15187/HighFidelity-Beta-Interface-PR14411-ce9ed05.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Attempted 15 times. No longer occurs.
hifi-snap-by--on-2018-11-15_08-24-36

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15195/HighFidelity-Beta-PR14411-597ff77.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15195/HighFidelity-Beta-PR14411-597ff77.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15195/HighFidelity-Beta-Interface-PR14411-597ff77.exe

**Comment by qlimnavarro** [comment]
Currentyl Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar does not pop in after fade.

**Pull request merged**
