### PR TITLE
Add method to check entities joint hierarchy

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR add a new method that return the parent of a specific entity joint.
This is needed to compute the joint hierarchy of avatars when added as entities.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15580/HighFidelity-Beta-PR14517-ad42f6a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15580/HighFidelity-Beta-PR14517-ad42f6a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15580/HighFidelity-Beta-Interface-PR14517-ad42f6a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15580/HighFidelity-Beta-PR14517-ad42f6a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15580/HighFidelity-Beta-Interface-PR14517-ad42f6a.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to a domain where you can create. 
- Open the console and run this lines of code:

`var entityID = Entities.addEntity({ type: "Model", modelURL: "http://mpassets.highfidelity.com/469c8b66-e3c2-47fb-9820-e306b1dd15c4-v1/optical_interpreter/optical_interpreter.fbx", position: Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, { x: 0, y: 0, z: -5 })) });`

`var headParentPosition = Entities.getAbsoluteJointTranslationInObjectFrame(entityID, Entities.getJointParent(entityID, Entities.getJointIndex(entityID, "Head")));`

`var entityPosition = Entities.getEntityProperties(entityID, "position")["position"]`

- You should see the optical interpreter model in front. 
- This line of code:
`Entities.addEntity({"type": "Sphere", "radius": 0.2, "position": Vec3.sum(headParentPosition, entityPosition)})`
should create a sphere on the avatar neck (parent of "Head" joint)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15743/HighFidelity-Beta-PR14517-ad42f6a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15746/HighFidelity-Beta-PR14517-37854ab.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15746/HighFidelity-Beta-PR14517-37854ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15746/HighFidelity-Beta-Interface-PR14517-37854ab.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
Pause on testing

**Comment by qlistephens95** [comment]
Resuming Testing

**Comment by qlistephens95** [comment]
PASS. Verified that all scripting works as expected.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15761/HighFidelity-Beta-PR14517-37854ab.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15761/HighFidelity-Beta-PR14517-37854ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15761/HighFidelity-Beta-Interface-PR14517-37854ab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15761/HighFidelity-Beta-PR14517-37854ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15761/HighFidelity-Beta-Interface-PR14517-37854ab.exe

**Comment by qlistephens95** [comment]
PASS. Verified that all scripting works as expected.

**Comment by shanzzam** [comment]
Ticket MS https://highfidelity.manuscript.com/f/cases/20207/Create-an-API-method-that-provide-information-of-the-joints-hierarchy-of-entities

**Pull request merged**
