### PR TITLE
Revert "DEV-1811: apply deletion rules to linked entities"

### PR DESCRIPTION
**Pull request by ZappoMan**
Reverts highfidelity/hifi#16307

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21870/HighFidelity-Beta-PR16333-51669e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21870/HighFidelity-Beta-Interface-PR16333-51669e1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21870/HighFidelity-Beta-PR16333-51669e1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21870/HighFidelity-Quest-Beta-PR16333-51669e1.apk)

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21874/HighFidelity-Beta-PR16333-51669e1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21874/HighFidelity-Quest-Beta-PR16333-51669e1.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21874/HighFidelity-Beta-PR16333-51669e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21874/HighFidelity-Beta-Interface-PR16333-51669e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21874/HighFidelity-Beta-PR16333-51669e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21874/HighFidelity-Beta-Interface-PR16333-51669e1.exe

**Pull request merged**
