### PR TITLE
cleanup debug for safe web entity URLs

### PR DESCRIPTION
**Pull request by birarda**
- cleanup debug for safe web entity setting

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Launch an entity-server that has web entities with good URLs. Confirm that `Changed web entity source URL to ` does not appear in the entity server log.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8118e83ff880f9dd4fc95cb964f9211b1c3b95b available at: https://gist.github.com/82467b29d8c5efda4e0091341fbe3445<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9480-a8118e8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9480-a8118e8.dmg

**Comment by nbq** [comment]
@birarda are you meaning to say to place a web entity? I am ready to run this test now but I notice you say create an entity-server that has web entities and I am unsure as to what that means?

**Comment by nbq** [comment]
Will test this PR

**Comment by nbq** [comment]
Tester: Coal
CPU: i7 6700k
GPU: GF 970
OS: Windows 10

In my sandbox, I created web entities and changed them to various urls including `google.com`, `youtube.com` and `reddit.com`

I did not notice the message in the Assignment Clients log but I did notice it in the Interface logs:

`[01/23 19:28:35] [DEBUG] [hifi.entities] Changing web entity source URL to  "http://youtube.com"`

This is showing where it is supposed to now so this is a PASS

**Pull request merged**
