### PR TITLE
Marketplace window

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ef1964a526b27ed41d136c5427a4b9160c83b2b available at: https://gist.github.com/7870cdaf9d36c0ceaa6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53b5c7e9718ac1206bdd50b0974e3ab6707af614 available at: https://gist.github.com/7870cdaf9d36c0ceaa6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1193d86d7b9ce233a5ee9b9e287e48ff5531950a available at: https://gist.github.com/7870cdaf9d36c0ceaa6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Comment by birarda** [comment]
I killed all but the last PR here

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47e63719ee5129a198572f90d8d8bc33c5bc62c3 available at: https://gist.github.com/2e05b08203647bd26128<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d5c0cf4e3d19c368050f224092fcb60040fcd8a available at: https://gist.github.com/7870cdaf9d36c0ceaa6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 235b5d77ae72000cc25360a05a05c8a74001f4f1 available at: https://gist.github.com/7870cdaf9d36c0ceaa6c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4446.dmg

**Pull request merged**
