### PR TITLE
Fix keyboard related crash.

### PR DESCRIPTION
**Pull request by druiz17**
This PR address the keyboard related crash. Link to fogzbug - https://highfidelity.fogbugz.com/f/cases/8528/CRASH-when-adding-a-model-entity-with-bad-URL-or-GOOD-URL#

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4394/HighFidelity-Beta-PR11667-f29937fb88a96461b6e5bbb3ee94a292afabd8b1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4394/HighFidelity-Beta-PR11667-f29937fb88a96461b6e5bbb3ee94a292afabd8b1.exe

**Comment by druiz17** [comment]
Test plan.
1.
  
- in desktop
- click "Create"
- clock Model
- in URL type 
- click Add or Cancel
- repeat a few times to make sure you do not crash
2.
 
- be logged in and HMD mode
- enable commerce mode.
- bring up the tablet and click on wallet app
- go through the wallet setup
- when typing in your password, the keyboard show not show your password unless you have the the "Show passphrase" box check.
- once you have your wallet set up, go to the security tab, click change passphrase
- when typing in old passphrase or new passphrase, the keyboard show not show your password unless you have the the "Show passphrase" box check.

3.
- be in HMD mode
- go back to the home screen for the tablet 
- click on the goto app
- click on the 'i' for a place card
- click on the facebook share button
- on the login page. click on the username field and type something, the keyboard should show what you are typing 
- click on the password field and type something. the keyboard should not show what you are typing

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
### 1.
Test | Result
--- | --- 
in desktop | Pass
click "Create" | Pass
clock Model | Pass
in URL type | Pass
click Add or Cancel | Pass
repeat a few times to make sure you do not crash | Pass

### 2.
Test | Result
--- | ---
be logged in and HMD mode | Pass
enable commerce mode. | Pass
bring up the tablet and click on wallet app | Pass
go through the wallet setup | Pass
when typing in your password, the keyboard show not show your password unless you have the the "Show passphrase" box check. | Pass
once you have your wallet set up, go to the security tab, click change passphrase | Pass
when typing in old passphrase or new passphrase, the keyboard show not show your password unless you have the the "Show passphrase" box check. | Pass
### 3.
Test | Result
--- | ---
be in HMD mode | Pass
go back to the home screen for the tablet | Pass
click on the goto app | Pass
click on the 'i' for a place card | Pass
click on the facebook share button | Pass
on the login page. click on the username field and type something, the keyboard should show what you are typing | Pass
click on the password field and type something. the keyboard should not show what you are typing | Pass

All good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
