### PR TITLE
adding surface normals to ray intersection

### PR DESCRIPTION
**Pull request by ZappoMan**
* updated rayPickExample.js to display the surface normal of where the ray hits

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 430cbcca7ed0043a0f0a3d8a80a3f3578a3684e5 available at: https://gist.github.com/5db7c36d181dc5bc3dc6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5911.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5911.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e758f3c6b89738f046bdbed318c34ef244dec64 available at: https://gist.github.com/5db7c36d181dc5bc3dc6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5911.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5911.dmg

**Comment by jherico** [comment]
Why?

**Comment by ZappoMan** [comment]
@jherico - because Philip and Eric asked for it, because they want the spray paint can to know what surface they actually hit. There's no other way for them to do this.

**Comment by PhilipRosedale** [comment]
Right.... there will be many cases where we want to know the surface normal that we hit so that we can orient another primitive to 'paint' onto it.

**Pull request merged**
