### PR TITLE
don't send avatar-entity updates for queryCube-changes

### PR DESCRIPTION
**Pull request by sethalves**
- don't send avatar-entity updates for queryCube-changes

### CODE REVIEW

**Comment by sethalves** [comment]
## Test Plan
- run interface, press the / key and click on the stats to expand them
- take note of the Avatar Mixer In and Out values, roughly
- use the test plan from https://github.com/highfidelity/hifi/pull/11614
- put on a lot of stuff
- check that the Avatar Mixer In and Out value haven't greatly changed

**Comment by ZappoMan** [comment]
@RyanDowne @conklin94122 @misslivirose -- Seth and I think this is a fix to the avatar-mixer spamming bug... this is demo blocker... let's get some testing on this!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4246/HighFidelity-Beta-PR11621-f1abb0cd5510bf563f69670a869776377aae2405.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4246/HighFidelity-Beta-PR11621-f1abb0cd5510bf563f69670a869776377aae2405.exe

**Comment by skytoad** [comment]
Testing

**Comment by skytoad** [comment]
Before: Avatar Mixer In 34 kbps/48pps. Avatar Mixer Out 70 kbps/48pps. 

After: Avatar Mixer In 40 kbps/48pps. Avatar Mixer Out 75 kbps/48pps. 

I say Pass because ~10 kbps seems to be standard fluctuation. 

NOTE: When another avatar is in field of view, Avatar Mixer In/Out shoots to about 300kbps/120kbps. As long as this is intended functionality, #11621 is a pass.

**Comment by thoys** [comment]
@skytoad are you sure you've tested this with avatar entities? Also @sethalves I don't think that the test-plan of https://github.com/highfidelity/hifi/pull/11614 includes any avatar-entities, the attachments are adjustable by other people too, only when you really check them out of the shop (buy them), they become avatar-entities, which is not the case for all the items yet iirc.

**Comment by themelissabrown** [comment]
@thoys do you have more info for @skytoad on how to be sure he's testing this correctly?

**Comment by thoys** [comment]
we will test this one internally, thanks

**Comment by thoys** [comment]
Tested this with @Liv , in release incoming packets was about 2000 kbps incoming,  in this version it went down to around 200

**Pull request merged**
