### PR TITLE
Handle sold out items a bit better

### PR DESCRIPTION
**Pull request by davidkelly**
This depends on https://github.com/highfidelity/data-web/pull/1259 being in production.  Then, whenever we are viewing a limited edition item which is sold out, we will see that it is sold out, and cannot attempt to purchase.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5642/HighFidelity-Beta-PR11988-a49ee46f541cfae25fd3b2fb4b229e070db366b9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5642/HighFidelity-Beta-PR11988-a49ee46f541cfae25fd3b2fb4b229e070db366b9.dmg

**Comment by davidkelly** [comment]
Test Plan

* point to staging (you need an environment variable HIFI_METAVERSE_URL with https://staging.highfidelity.com as the value)
* create a wallet
* look for 'Staging Flare Gun' in the marketplace
* click on it
* the button that normally is blue, and suggests you purchase it, is now grey, and says "sold out"
* try to click the button -- nothing happens.
* that's it :beers:

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Results
--- | ---
point to staging (you need an environment variable HIFI_METAVERSE_URL with https://staging.highfidelity.com as the value) | Pass
create a wallet | Pass
look for 'Staging Flare Gun' in the marketplace | Pass
click on it | Pass
the button that normally is blue, and suggests you purchase it, is now grey, and says "sold out" | Pass
try to click the button -- nothing happens. | Pass


### Notes
If the item is sold out then the blue buy button on the Marketplace (as seen in gif) should also be grayed out.

f584171f-44ae-4261-a6de-b649403e5d96

**Comment by davidkelly** [comment]
agree -- we will do more with this later for sure, as part of a general styling pass.  calling it qa pass

**Pull request merged**
