### PR TITLE
Finalize work on MS14295 and MS14559

### PR DESCRIPTION
**Pull request by zfox23**
The pull requests associated with MS14295 (#13020) and MS14559 (#13019) were merged because we were rushing. But, this morning, I found more bugs associated with those tickets in Master. This PR should finalize the work to fix those two bugs.

### CODE REVIEW

**Comment by zfox23** [comment]
# Test Plans
## Tests for Gifts UI Bugfixes
### Prerequisites
- A wallet setup on the Staging Metaverse
- A second Avatar present in the same domain as you.

### Tests
Because these changes are UI-only and aren't functional changes, a thorough QA isn't required for this PR.

Please perform a quick general smoke test of:
1. Sending HFC to a Connection
2. Sending HFC to someone Nearby
3. Sending a Gift to a Connection
4. Sending a Gift to someone Nearby

and note any UI horribleness or bugs (hopefully there aren't any). 😄 

If, by any chance, you notice any problems during any of the four smoke tests, please note them.

## Tests for Nearby Orb Fixes
### Prerequisites
- Two avatars (Avatar A and Avatar B) must be present in Domain A.
    - The tester controlling Avatar A will be performing all of the below tests; Avatar B will just be required to idle in the Domain.
- Both avatars must be logged in and have an authenticated Wallet.
- The tester controlling Avatar A will be asked to wear an HMD at one point during this test, but should start in Desktop mode.
- Avatar A must have purchased something from the Marketplace (even if it's free).

### Tests
1. Open the Wallet. Click "Send Money". Click "Nearby".
    i. Verify that a blue orb appears over Avatar B
2. Click on the blue orb
    i. Verify that the orb turns orange
    ii. Verify that the "Send Money" UI shows Avatar B's display name
3. Click on the orange orb
    i. Verify that the orb turns blue
    ii. Verify that the "Send Money" UI shows instructions for selecting a nearby avatar
4. Attempt, by any means, to get Steps 2 and 3 to fail. You never have to actually send money. For example, attempt the following:
    i. Select the Avatar, click "CHOOSE", then close the Wallet and try again
    ii. Select the Avatar, click "CHOOSE", then click "CHANGE" and try again
    iii. Do something crazy that I haven't thought of.
5. Attempt steps 1-4 in HMD.
6. Open "My Purchases". Click the 3-dots context menu on the card associated with any of your Purchases. Click "Gift". Click "Nearby".
    i. Verify that a blue orb appears over Avatar B
7. Click on the blue orb
    i. Verify that the orb turns orange
    ii. Verify that the "Send Gift" UI shows Avatar B's display name
8. Click on the orange orb
    i. Verify that the orb turns blue
    ii. Verify that the "Send Gift" UI shows instructions for selecting a nearby avatar
9. Attempt, by any means, to get Steps 7 and 8 to fail. You never have to actually send a gift.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9270/app_13030_PR_bbc15cdc63b32fc0f14f78f9ca61092990341916.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9270/HighFidelity-Beta-PR13030-bbc15cdc63b32fc0f14f78f9ca61092990341916.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9270/HighFidelity-Beta-Interface-PR13030-bbc15cdc63b32fc0f14f78f9ca61092990341916.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9270/HighFidelity-Beta-PR13030-bbc15cdc63b32fc0f14f78f9ca61092990341916.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9270/HighFidelity-Beta-Interface-PR13030-bbc15cdc63b32fc0f14f78f9ca61092990341916.exe

**Comment by zfox23** [comment]
Do not test externally (@howard-stearns and I will test).

**Pull request merged**
