### PR TITLE
fix crash on shutdown related to entity scripts connecting to signals

### PR DESCRIPTION
**Pull request by ZappoMan**
The avatarMover.js script is connecting to scriptEnding... which is not a safe thing to do since the scriptEnding signal isn't sent for the Entities script engine until application shutdown. Since we can't prevent script writers from doing this, we need to make sure we disconnect any entityScript object from all engine signals when they are cleared.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: aac824fb993a4b69e108e8ea393abbce7cad5c37 available at: https://gist.github.com/da75975c9e00252d7691<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7188bac0bc5ccd39713f14fd701da4ebb1b52fe available at: https://gist.github.com/da75975c9e00252d7691<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c66db5d8e4510207ae2eb26ab90779ecce4e810a available at: https://gist.github.com/da75975c9e00252d7691<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d87fe9efffbb730432b15fd8468daf24271ad798 available at: https://gist.github.com/da75975c9e00252d7691<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4574.dmg

**Comment by AndrewMeadows** [comment]
I tested this on linux using the following script on an entity (copied to a local we server):

https://files.slack.com/files-pri/T025Q3X6R-F047UCV3E/minimalrepro.js

The interface crashed for upstream/master but did not for zappoman/crashOnExit.

**Pull request merged**
