### PR TITLE
Windows 64 bit updates

### PR DESCRIPTION
**Pull request by jherico**
* RealSense and MIDI support removed
* Leap motion CMake fix
* GPU changes

I've updated the GPU library to change a number of members and locals to size_t, which is 64 bit on 64 bit platforms.  This reduces the warnings noise of doing 64 bit builds, but by no means eliminates it.  I tried doing more, but every change made ends up requiring more downstream changes, and eventually I'm sure I'll change something that will break the build (perhaps by putting a 64 bit value into a packet).  

I'm surprised we're not seeing these warnings on OSX and Linux.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a05a664f4e05d1d6334d625060afd2353a6c001 available at: https://gist.github.com/069586c3130fa47b3efd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 55799403c99dffebddcf4ecafed0423d20bbcad4 available at: https://gist.github.com/069586c3130fa47b3efd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 38545237872ecb47ed7a2528c8b6ecd7cf80a52d available at: https://gist.github.com/069586c3130fa47b3efd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e05d8ede7d6d42f93f5be779acb5e611f878781e available at: https://gist.github.com/069586c3130fa47b3efd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2cea593fbdaa4cb2f673cfed9b82d60372d5e556 available at: https://gist.github.com/069586c3130fa47b3efd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6534.dmg

**Comment by thoys** [comment]
Hiya, any reason for dropping MIDI and RealSense?

**Pull request merged**
