### PR TITLE
Working on new android toolchain & sample

### PR DESCRIPTION
**Pull request by jherico**
* Import minor code fixes from the Android / Climax branches
* Fix a number of shaders that don't compile under GLES due to implicit int / float conversions
* Add the GPU-GLES backend
* Add a new android application for improving the android toolchain
* Globally replace all tabs with spaces in the source code.  
* Consolidate the mechanisms used to add GL dependencies in CMake

## Testing

Smoke test.  This PR should not actually change the behavior of the existing applications.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3272/HighFidelity-Beta-PR11348-bfb684862c5ba02c4e8eb355856c9ed8a63b7800.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3272/HighFidelity-Beta-PR11348-bfb684862c5ba02c4e8eb355856c9ed8a63b7800.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3285/HighFidelity-Beta-PR11348-6f36366f7129c166fae04a0d0dc3ba0804be6133.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3285/HighFidelity-Beta-PR11348-6f36366f7129c166fae04a0d0dc3ba0804be6133.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3384/HighFidelity-Beta-PR11348-097ae2d631e227311389df85bfaa3d24d54f2a9d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3389/HighFidelity-Beta-PR11348-8013ba28123a03d286dcbe51314141c82aea076c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3389/HighFidelity-Beta-PR11348-8013ba28123a03d286dcbe51314141c82aea076c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3446/HighFidelity-Beta-PR11348-882818677afa0e7c94019351ec426835d9e343b4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3446/HighFidelity-Beta-PR11348-882818677afa0e7c94019351ec426835d9e343b4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3450/HighFidelity-Beta-PR11348-b93e91b9f3b757ce76411eb1380f41dc459d3f6b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3453/HighFidelity-Beta-PR11348-bc4193f2769ef05215bd1342a61f76657b2cfbeb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3453/HighFidelity-Beta-PR11348-bc4193f2769ef05215bd1342a61f76657b2cfbeb.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

General smoke test going through the main apps on the toolbar, didn't see anything out of the ordinary and the performance doesn't seem noticeably better or worse.

**Pass**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3649/HighFidelity-Beta-PR11348-e42068f6817b734f088b01d579970c480888922c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3649/HighFidelity-Beta-PR11348-e42068f6817b734f088b01d579970c480888922c.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3656/HighFidelity-Beta-PR11348-9d18fd3a46ec62505e21c919e41d6c9a3b2c6921.exe

**Pull request merged**
