### PR TITLE
Beta Release 13 - Includes up to Developer Release 5027

### PR DESCRIPTION
**Pull request by cozza13**
- Add audio peak limiter to audio mixer
- Fix the jittering reflection bug and more Normal improvements
- vhacd-util improvements
- Fix domain max capacity to only count users (not scripted agents)
- Make navigating directories in file browser dialog possible without double-clicking
- Fix Avatar collision sounds triggering all the time
- Make the application of redundant physics update idempotent to improve action glitches
- Fix crash on shutdown of SteamVR
- Fix crash on click on non-visible web-entity 
- Update the build docs for a better OpenSSL security posture.
- Do not send stale vive data as valid after deactivating
- Save toolbar position when moving it only when stopped moving it
- Add leap hands to /system
- Replace the linear interpolation embedded in the .WAV/.RAW loader with high quality polyphase resampling.
- Fix bad convex hull simplification
- Revert "Update the build docs for a better OpenSSL security posture."
- Eliminate file IO contentions for settings
- Removed innocuous "AvatarData packet size mismatch" warning
- Add version number to avatar recording frame
- Add Clipboard.getContentsDimensions() JavaScript method
- Eliminate extraneous writes for unchanged values
- Add Entities.getChildrenIDs() method
- Camera steers avatar when walking
- Fixed constant turn of 22.5 degrees in comfort mode
- Add "Load Defaults" button to Running Scripts dialog and rename "Stop All" to "Remove All"
- Select/Disable plugins via command line args
- Fix OS X warning
- Fix colors of buttons in Asset Browser dialog
- AVX2 optimized audio resampler 
- New home content
- Corrected Oculus Touch coordinate system so that hands track properly
- Fix for models exported from Daz3D
- Expose haptics to JS
- Game pads work after falling asleep and being reactivated
- Add support for ambient occlusion texture and lightmap texture for fbx exported from Blender
- Fix height of Load Defaults button in Running Scripts dialog
- Added MyAvatar.hmdLeanRecenterEnabled property used to disable the 'room-scale' avatar re-centering code. Disabling this can prevent sliding when the avatar is supposed to be sitting or mounted on a stationary object. 
- Add basic metadata to domains
- Attempt to get better logging from pure virtual call crashes
- Use shared CPUDetect.h for CPU detection
- Re-instate domain API connection info refresh during failure, fix localhost connection after downgrade
- Rework domain-level permissions 
- Fix some permissions-grid bugs
- Fix import of invalid JSON file failing silently
- Fix model export
- Update BUILD_OSX.md
- Fix avatar entity locking
- Fix problem related to server-side extrapolation of children of avatars
- Fix image2d overlay color property
- Fix tabbing behavior in edit.js
- Exposed orientation and eye position to procedural entity shaders
- More verbose messaging about incorrect case in entity types
- Reset Vive grip buttons to 0 if not pressed
- Only signal once on a protocol mismatch with DS
- Fixing issues with unclosed groups in settings persistence

# **QA testing**  

http://rawgit.com/cozza13/QAtesting/master/dynamicrc.js

Full **Smoke test** - **HMD RC test** with **Eye tests** and **RC test**

This PR has a protocol change. Therefore you will only see content on you updated locahost, dev-playa and dev-demo. I have updated the server stats to pull from those locations

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ed972257fa856b7c51822eff09d620d7180c616 available at: https://gist.github.com/3e500e8db81ffca226f6168d6181f9d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8078.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8078.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 64 bit - i5 6500 CPU - GTX 970 GPU **Desktop mode - keyboard/mouse**
ACL and connection messages testing to localhost - pass
ACL and connection messages testing to  2nd machine LAN - pass
ACL and connection messages testing to 2nd machine INet - pass
ACL and connection messages testing to known proto mismatched domain - pass
Returns to last location visited - pass
Remembers running script list - pass

Maximize window is not restored - this may be an ancient bug only revealed by starting with fresh ini today.  Run interface - maximize window - "do stuff" - close interface - run again - note window is not in maximized state.
Full screen mode is restored proper.
Position and size of Interface window is persisted and restored proper.  Note - if, say, you had window set to some fraction of full desktop size - hit maximize window control then exit/relaunch Interface - Window will restore as previous not maximized size.
** Only maximized window state is not persisted/restored** - Unsure if this is new so not going to flag fail - notice only.

Scripted agent does not count against max capacity value - pass (It still counts as avatars present in stats - but not as eval for users when doing max capacity eval) - Pass

Notifications still shows the initial connection refused message for user signature - **cosmetic only**

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:
For "playaPerformanceTest.js" I run 3 times at each location.  Typically, as usual, first 2 passes are always good - no spikes above yellow line, 3rd pass have 90%+ plus fail rate with spikes well above red line.  GPU-Z shows texture RAM at near 4G and Interface is in active texture culling mode.  Nothing new.

Stats only copied after rotation of AV by 360 degrees AND seeing no pending assets to DL

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |6133 |6219 |4638
**GPU Buffer Count**: |1863 |2037 |1119
**CPU Memory Usage**: |103514112 |119103488 |85192704
**GPU Memory Usage**: |77312000 |92151808 |48730112
**CPU Texture Count**: |399 |446 |326
**GPU Texture Count**: |2608 |2984 |3038
**GPU Transfer Count**: |4 |4 |4
**CPU Texture Memory Usage**: |111238004 |112572104 |257721712
**GPU Texture Memory Usage**: |1377074366 |2360493225 |1081575602
**GPU Virtual Memory Usage**: |1577778366|2561197225|1282279602
**Triangle Count**: |743860 |326379 |311207
**Triangle Rate**: |46491250 |20398687 |19450437
**API Drawcall Count**: |164 |130 |141
**Drawcall Count**: |219 |132 |141
**Drawcall Rate**: |13687 |8250 |8812
**State Changes Texture Count**:|215 |162 |201
**Pipeline Count**: |29 |23 |24
**Item Opaques**: |207 |193 |134
**Item Translucents**: |20 |11 |23
**Item Lights**: |22 |21 |3
**Timing Opaques**: |1509 |1705 |1141
**Timing Translucents**: |173 |86 |297
**Timing Lighting**: |124 |223 |125
**Render Frame**: |2537 |3126 |2221

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Pass
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Pass

**Comment by Nex-Pro** [comment]
### PASS

**PR Build:** #8078
**Testing Architecture:** Desktop PC
**CPU:** 4.0 ghz i7
**RAM:** 16 GB
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**HMD:** None
**Hand Controllers:** None

**Tester:** Piper.Peppercorn

**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**:  SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS

**Additional Test Results + Observations**: 
Saw messages: 
"Connection refused insufficient data"
"Connection refused error decrypting signature"

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |59 |60
**CPU Buffer Count**: |4107 |5545 |3902
**GPU Buffer Count**: |516 |461 |665
**CPU Memory Usage**: |63094784 |102461440 |77582336
**GPU Memory Usage**: |20889600 |29593600 |40394752
**CPU Texture Count**: |207 |371 |301
**GPU Texture Count**: |1552 |1766 |1750
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |205753504 |1043861696 |488565984
**GPU Texture Memory Usage**: |477954915 |952386244 |794622312
**GPU Virtual Memory Usage**: |694285155|1168716484|1010952552
**Triangle Count**: |177771 |333800 |601608
**Triangle Rate**: |11110687 |19635294 |54691636
**API Drawcall Count**: |151 |107 |223
**Drawcall Count**: |154 |230 |224
**Drawcall Rate**: |9625 |13529 |20363
**State Changes Texture Count**:|118 |129 |244
**Pipeline Count**: |20 |21 |34
**Item Opaques**: |204 |164 |214
**Item Translucents**: |3 |4 |47
**Item Lights**: |15 |18 |25
**Timing Opaques**: |1028 |1521 |3131
**Timing Translucents**: |56 |71 |1272
**Timing Lighting**: |106 |188 |389
**Render Frame**: |1764 |2688 |8280

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|PASS
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|PASS


New content working fine burned a lot of stuff. Nice touch.
Portal works apart from sending avatar to incompatible server. ( expected )

Good job guys.

**Comment by hifi-gustavo** [comment]
Build console output for commit: edbb7b74bffc283968d054598171dadc15822080 available at: https://gist.github.com/3e500e8db81ffca226f6168d6181f9d6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8078.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8078.dmg

**Comment by thoys** [comment]
## QA Test
**QA Tester**: thoys

Tested with HTC Vive and Oculus

**EYE-01 Test Result**: **EYE-01 Test** SUCCESS
**EYE-02 Test Result**: **EYE-02 Test** SUCCESS
**EYE-03 Test Result**: **EYE-03 Test** SUCCESS
**EYE-04 Test Result**: **EYE-04 Test** SUCCESS
**EYE-05 Test Result**: **EYE-05 Test** SUCCESS
**EYE-06 Test Result**: **EYE-06 Test** SUCCESS
**EYE-07 Test Result**: **EYE-07 Test** SUCCESS
**Additional Test Results + Observations**: The eye-tests all worked as expected


**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: No performance errors found. Works great with Vive + 2 monitors enabled.




**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |100 |100 |63
**Present Rate**: |99 |100 |101
**Present New Rate**: |50 |99 |58
**CPU Buffer Count**: |3745 |4056 |4109
**GPU Buffer Count**: |923 |681 |1081
**CPU Memory Usage**: |56279040 |74850304 |72241152
**GPU Memory Usage**: |13791232 |24256512 |37687296
**CPU Texture Count**: |210 |307 |270
**GPU Texture Count**: |1719 |1730 |1743
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |265563580 |873503680 |330445112
**GPU Texture Memory Usage**: |387780999 |648070463 |977728321
**GPU Virtual Memory Usage**: |608872839|869162303|1198820161
**Triangle Count**: |285877 |248869 |631638
**Triangle Rate**: |28587700 |24886900 |70182000
**API Drawcall Count**: |167 |46 |227
**Drawcall Count**: |172 |168 |228
**Drawcall Rate**: |17200 |16800 |25333
**State Changes Texture Count**:|145 |49 |258
**Pipeline Count**: |27 |22 |39
**Item Opaques**: |205 |101 |216
**Item Translucents**: |7 |2 |49
**Item Lights**: |16 |16 |26
**Timing Opaques**: |2414 |748 |2868
**Timing Translucents**: |128 |72 |535
**Timing Lighting**: |282 |179 |353
**Render Frame**: |4070 |1829 |5150

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Pass
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Pass

**Pull request merged**
