### PR TITLE
fix some data-races in logging system

### PR DESCRIPTION
**Pull request by sethalves**
- fix some data-races in the logging system

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: af5be8d1d91546a37aa4ef6358b4666adf56af4e available at: https://gist.github.com/98fbe309fccc3c5ffb3e881e2a4402fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-af5be8d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-af5be8d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 10907d9fb92740db9310c7a5930a07824550187a available at: https://gist.github.com/98fbe309fccc3c5ffb3e881e2a4402fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-10907d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-10907d9.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a801f27c7ca0e93ab6b4518eca458f1dcaf37150 available at: https://gist.github.com/98fbe309fccc3c5ffb3e881e2a4402fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-a801f27.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-a801f27.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by thoys** [comment]
@kevinmthomasse  are you still testing this

@sethalves what is the testplan?

**Comment by sethalves** [comment]
to test:
- use servers and interface from this PR
- get a group of avatars together and make sure the servers do okay

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ac799ddaff79bcbf5f5cd9f846b2e4c974c126c available at: https://gist.github.com/98fbe309fccc3c5ffb3e881e2a4402fb<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-8ac799d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8847-8ac799d.dmg

**Comment by thoys** [comment]
## QA Testing Report

Tested with @kevinmthomasse and another machine, server seems to behave normal.

QA Pass

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Installed server and tested with @thoys as he brought in two avatars on the ```localhost``` to which everything worked properly.

**Pull request merged**
