### PR TITLE
FB11511 - position of log windows should be persistent between invocations of interface

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Open log window
2. Resize/move it
3. Close it. 
4. Open HMD-friendly log window
5. Resize/move it
6. Restart interface
7. Ensure log / HMD-friendly log windows remember their positions

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6791/app_12311_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6791/HighFidelity-Beta-PR12311-1ed7d164c45dcb45be34d8a0633372bbe47502dc.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6802/app_12311_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6802/HighFidelity-Beta-PR12311-1ed7d164c45dcb45be34d8a0633372bbe47502dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6802/HighFidelity-Beta-PR12311-1ed7d164c45dcb45be34d8a0633372bbe47502dc.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
