### PR TITLE
Moving more to external plugins

### PR DESCRIPTION
**Pull request by jherico**
Move Sixense, SDL2, & OpenVR to external plugins

Needs testing on the vive hardware.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3fd0de13c5ae15e18abbad52b0ab07116b6256c available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 280cf8ea998b176abc6d6baebe5b18efe264d2d4 available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 345281c747c1b2669c788a66b9f97776bdf85a90 available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4fbb7bb19947621cfe34243a3e7382c0505fe3fb available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e10deb4e726ae6c3a5955fdab456cba99d276ce1 available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6db1aa3ff6424dd19ebce2795abdfdccb78453ac available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fdd981caa61fbd40cb98eab2902ef218d519442b available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8c9e19baa1deab8aeff3fc6268122a23be05a21 available at: https://gist.github.com/420fc035a4c256018e9b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 043606e39bee89308ac11a2d9bb42a270515c305 available at: https://gist.github.com/759c78dff4d2ac62b8cd<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6438.dmg

**Comment by ZappoMan** [comment]
Closing... @jherico will reopen different PR's for each of the various plugins.

**Pull request closed without merging**
