### PR TITLE
Remove some deprecated JavaScript API items

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
The following API items and associated code are removed because they're unused:
- Window.customPrompt()
- Overlays.getOvelrayObject()
- Overlays.findRayIntersectionVector()
- Overlays "borderSize" property
- Menu.addActionGroup() and removeActionGroup()
- Menu.isInfoViewVisible() and closeInfoView()

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Check:
- The Asset Browser dialog still works.
- You can use the toolbar in desktop mode.
- You can use the tablet in HMD mode.
- Using the Create app, the grab handles look as they should: corner, edge, face, and clone.
- In HMD mode, the keyboard focus highlight is correct.
- Interface window's menu items are present and (some) work.
- The "Help" icon displays  the help page, on desktop and in HMD.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6911/app_12334_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6911/HighFidelity-Beta-PR12334-615e54620b3a0e8da9160a37b956ff012b5943d2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6911/HighFidelity-Beta-PR12334-615e54620b3a0e8da9160a37b956ff012b5943d2.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7138/app_12334_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7138/HighFidelity-Beta-PR12334-033b85a3a87ef63a31b84a1f95f7bbf3e92c35bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7138/HighFidelity-Beta-PR12334-033b85a3a87ef63a31b84a1f95f7bbf3e92c35bf.exe

**Comment by misslivirose** [comment]
This looks good to me but touches enough of the main code that it would be great to get a client team set of eyes on it for an additional once-over

**Pull request merged**
