### PR TITLE
Don't refresh Inventory or Recent Activity if data hasn't changed

### PR DESCRIPTION
**Pull request by zfox23**
_Guessing this goes in RC61 since it isn't critical? That may change..._

**Test Plan:**
1. Is your wallet set up? If it is, rename your `<username>.hifikey` file to `<uername>.hifikey.backup` for now. If it's not set up, set it up, making sure you're NOT on the list to get seeded.
2. Open the Wallet app. Wait on the "Recent Activity" screen. Verify that the "how to get seeded" text doesn't flash every 4 seconds.
3. If you hadn't previously set up a wallet, get seeded. If you _have_ previously set up a wallet. remove the `.backup` from your `hifikey`'s filename.
3. Buy 6 Test Beach Balls from the Marketplace. Wait 30 seconds.
4. Open the Wallet app. Scroll all the way to the bottom of "Recent Activity". Wait 10 seconds. Verify that you don't get auto-scrolled to the top of "Recent Activity" and that there is no "flashing" of the "Recent Activity" display every ~4 seconds.
5. Open "My Purchases". Scroll all the way to the bottom of "My Purchases". Wait 10 seconds. Verify that you don't get auto-scrolled to the top of "My Purchases" and that there is no "flashing" of the "My Purchases" display every ~4 seconds.
6. Perform these steps quickly:
    1. Buy a 7th Test Beach Ball
    2. Open the Wallet app.
    3. Scroll all the way to the bottom of "Recent Activity".
    4. Wait 40 seconds.
    5. Verify that, somewhere within those 40 seconds, your scroll position only _slightly_ changed (because the "1 Pending" text had been removed and replaced with a new entry at the top)
7. Perform these steps quickly:
    1. Buy an 8th Test Beach Ball
    2. Open My Purchases.
    3. Scroll all the way to the bottom of "My Purchases".
    4. Wait 40 seconds.
    5. Verify that you don't get auto-scrolled to the top of "Recent Activity".

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5233/HighFidelity-Beta-PR11893-3c892920e3f3dfa8a9b98d943627e945ad13a106.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5233/HighFidelity-Beta-PR11893-3c892920e3f3dfa8a9b98d943627e945ad13a106.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
On hold - backend issue.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5283/HighFidelity-Beta-PR11893-b0dda3de33988cd45db5adc244c5dd6494f5c4c6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5283/HighFidelity-Beta-PR11893-b0dda3de33988cd45db5adc244c5dd6494f5c4c6.dmg

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Is your wallet set up? If it is, rename your <username>.hifikey file to <uername>.hifikey.backup for now. If it's not set up, set it up, making sure you're NOT on the list to get seeded. | Pass
Open the Wallet app. Wait on the "Recent Activity" screen. Verify that the "how to get seeded" text doesn't flash every 4 seconds. | Pass
If you hadn't previously set up a wallet, get seeded. If you have previously set up a wallet. remove the .backup from your hifikey's filename. | Pass
Buy 6 Test Beach Balls from the Marketplace. Wait 30 seconds. | Pass
Open the Wallet app. Scroll all the way to the bottom of "Recent Activity". Wait 10 seconds. Verify that you don't get auto-scrolled to the top of "Recent Activity" and that there is no "flashing" of the "Recent Activity" display every ~4 seconds. | Pass
Open "My Purchases". Scroll all the way to the bottom of "My Purchases". Wait 10 seconds. Verify that you don't get auto-scrolled to the top of "My Purchases" and that there is no "flashing" of the "My Purchases" display every ~4 seconds. | Pass
Perform these steps quickly: | 
Buy a 7th Test Beach Ball | Pass
Open the Wallet app. | Pass
Scroll all the way to the bottom of "Recent Activity". | Pass
Wait 40 seconds. | Pass
Verify that, somewhere within those 40 seconds, your scroll position only slightly changed (because the "1 Pending" text had been removed and replaced with a new entry at the top) | Pass
Perform these steps quickly: | 
Buy an 8th Test Beach Ball | Pass
Open My Purchases. | Pass
Scroll all the way to the bottom of "My Purchases". | Pass
Wait 40 seconds. | Pass
Verify that you don't get auto-scrolled to the top of "Recent Activity". | Pass

Finally! :smile: 🎉

**Pull request merged**
