### PR TITLE
tablet scale and position changes

### PR DESCRIPTION
**Pull request by druiz17**
This PR sets the tabet scale at 70% instead of 100% and also adjust the tablet 20 degrees in the direction of you domain hand when opening the tablet.

PR - https://highfidelity.fogbugz.com/f/cases/12941/Reposition-and-Resize-Tablet-Default

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in HMD
- open the tablet
- the tablet scale should at 70% (it should looks smaller than what it was before)
- the tablet should be positioned more towards your dominant hand...(dominant hand can be changed in the avatar settings page).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7819/app_12585_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7819/HighFidelity-Beta-PR12585-2d448d7208ae90a8bdea3ba45d30865b78f80864.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7819/HighFidelity-Beta-PR12585-2d448d7208ae90a8bdea3ba45d30865b78f80864.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
NOTE: The front of the tablet kind of "floats" above the rest of the tablet. The intractable screen of the tablet is raised above the physical tablet that is held. When looked at close it enough the user can see inside the tablet.
[Files.zip](https://github.com/highfidelity/hifi/files/1795111/Files.zip)

**Pull request merged**
