### PR TITLE
Fix out of bounds computing KDOPs when the model url is incorrect

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/22087/Out-of-bounds-crash-in-HFMModel-computeKdops-MASTER

This PR fixes the crash that occurs when visiting dev-content.

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to dev-content and make sure interface doesn't crash while loading the domain's content

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18638/HighFidelity-Beta-PR15347-0d92ec1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18638/HighFidelity-Beta-Interface-PR15347-0d92ec1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18638/HighFidelity-Beta-PR15347-0d92ec1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18638/HighFidelity-Quest-Beta-PR15347-0d92ec1.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18638/HighFidelity-Beta-PR15347-0d92ec1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18638/HighFidelity-Beta-Interface-PR15347-0d92ec1.exe

**Comment by qlimnavarro** [comment]
Pre merge pass, did not crash in dev content

**Pull request merged**
