### PR TITLE
BUGZ-1275 Additional Grapics API info was added to the system info, which overflowed the amount of info that could be sent in a packet.

### PR DESCRIPTION
**Pull request by roxanneskelly**

### CODE REVIEW

**Comment by SimonWalton-HiFi** [comment]
Alternatively we could add an option to platform::getAll() to return an shorter list that will fit in a packet.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20980/HighFidelity-Beta-PR16080-8ac185a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20980/HighFidelity-Quest-Beta-PR16080-8ac185a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20980/HighFidelity-Beta-PR16080-8ac185a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20980/HighFidelity-Beta-Interface-PR16080-8ac185a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20980/HighFidelity-Beta-PR16080-8ac185a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20980/HighFidelity-Beta-Interface-PR16080-8ac185a.exe

**Pull request merged**
