### PR TITLE
Support for stereo audio input/mic

### PR DESCRIPTION
**Pull request by kencooke**
This PR adds the plumbing for stereo avatar audio streams, using audio codecs.

By default, a stereo input device gets downmixed to mono, streamed to the audio-mixer using a mono codec, and rendered as an HRTF point-source located at the avatar.

With this PR, you can explicitly enable the "isStereoInput" property on a stereo input device. This will disable downmixing, stream to the audio-mixer using a stereo codec, and render as "head locked" stereo that bypasses the HRTF.

A checkbox/GUI for this feature can be added in a future PR.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6255/app_12162_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6255/HighFidelity-Beta-PR12162-dfc8c86571397146c3dd53db06ed7fe9586f8bc2.dmg

**Comment by kencooke** [comment]
### Test Plan

NOTE: you must have a stereo microphone or audio input device, to test this PR.

1) Using Interface from this PR, connect to existing dev-domains and verify that microphone audio works as before. By default, stereo input is disabled and nothing has changed.

2) Using both Interface and Sandbox from this PR:
 - Go to your local domain.
 - Select an audio input device that is configured to be stereo. This can be a stereo mic, audio input jack wired as stereo, or a stereo virtual audio device.
 - Open the audio scope (under Developer/Audio/Show Scope) and toggle one of the "Output" checkboxes, to enable server echo. The audio from the server should be clean.
 - Open the Javascript console (ctrl-alt-J) and type ```Audio.setStereoInput(true)``` to switch the stream to stereo mode. The audio from the server should still be clean. Verify you are sending and receiving a stereo stream, by talking into one side of the mic, adjusting left/right gains, or sending music.
 - type ```Audio.setStereoInput(false)``` to switch the steam back to mono mode.

NOTES:
Calling Audio.setStereoInput(true) when a mono input device is selected, will fail and select the dummy (silent) input. This is expected.

With stereo enabled, joining a domain not running this PR will result in garbage audio, as before.

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed fro PR#12162. PASSED.

**Pull request merged**
