### PR TITLE
Case 20060: Grab correct stencil masks from display plugins

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/20060/We-are-artificially-clipping-Oculus-FOV

Also updated LibOVR to 1.35

Test plan:
- Using a Rift, go into HMD.  You shouldn't see extra black borders around your field of view.  In the desktop preview, you should see black borders around the edges.
- Using a Vive, go into HMD.  You shouldn't see extra black borders around your field of view.  In the desktop preview, you should see black borders around the edges.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18400/HighFidelity-Beta-PR15266-0b6313d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18400/HighFidelity-Beta-Interface-PR15266-0b6313d.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18404/HighFidelity-Beta-PR15266-4ed7c09.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18404/HighFidelity-Quest-Beta-PR15266-4ed7c09.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18404/HighFidelity-Beta-PR15266-4ed7c09.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18404/HighFidelity-Beta-Interface-PR15266-4ed7c09.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18406/HighFidelity-Beta-PR15266-4ed7c09.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18406/HighFidelity-Quest-Beta-PR15266-4ed7c09.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18406/HighFidelity-Beta-PR15266-4ed7c09.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18406/HighFidelity-Beta-Interface-PR15266-4ed7c09.exe

**Comment by SamGondelman** [comment]
build this please?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18409/HighFidelity-Beta-PR15266-4ed7c09.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18409/HighFidelity-Quest-Beta-PR15266-4ed7c09.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18409/HighFidelity-Beta-PR15266-4ed7c09.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18409/HighFidelity-Beta-Interface-PR15266-4ed7c09.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18480/HighFidelity-Beta-PR15266-06f53fe.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18480/HighFidelity-Quest-Beta-PR15266-06f53fe.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18480/HighFidelity-Beta-PR15266-06f53fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18480/HighFidelity-Beta-Interface-PR15266-06f53fe.exe

**Comment by NissimHadar** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18484/HighFidelity-Beta-PR15266-33b3e2a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18484/HighFidelity-Quest-Beta-PR15266-33b3e2a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18484/HighFidelity-Beta-PR15266-33b3e2a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18484/HighFidelity-Beta-Interface-PR15266-33b3e2a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18490/HighFidelity-Beta-PR15266-4e4526f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18490/HighFidelity-Beta-Interface-PR15266-4e4526f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18490/HighFidelity-Beta-PR15266-4e4526f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18490/HighFidelity-Quest-Beta-PR15266-4e4526f.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18490/HighFidelity-Beta-PR15266-4e4526f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18490/HighFidelity-Beta-Interface-PR15266-4e4526f.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18500/HighFidelity-Beta-PR15266-8d2495e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18500/HighFidelity-Quest-Beta-PR15266-8d2495e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18500/HighFidelity-Beta-PR15266-8d2495e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18500/HighFidelity-Beta-Interface-PR15266-8d2495e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18500/HighFidelity-Beta-PR15266-8d2495e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18500/HighFidelity-Beta-Interface-PR15266-8d2495e.exe

**Comment by samcake** [comment]
Good to go,
Can we rename the file and enum "StencilMode" by "StencilMaskMode" 
THanks

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18571/HighFidelity-Beta-PR15266-8d2495e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18571/HighFidelity-Beta-Interface-PR15266-8d2495e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18571/HighFidelity-Beta-PR15266-8d2495e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18571/HighFidelity-Beta-Interface-PR15266-8d2495e.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18571/HighFidelity-Beta-PR15266-8d2495e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18571/HighFidelity-Quest-Beta-PR15266-8d2495e.apk)

**Pull request merged**
