### PR TITLE
makeUserConnection.js Fix for alternative skeletons

### PR DESCRIPTION
**Pull request by thoys**
Allows avatars which have an alternative bone structure to make connections. (Hands are still required)

Fixes https://highfidelity.fogbugz.com/f/cases/4360/handshake-fails-for-non-standard-avatars-that-don-t-have-Left-RightHandMiddle1-joint

## QA Test
- Test with two avatars.
- Test with and without HMD.
- One avatar should use this avatar http://mpassets.highfidelity.com/1b7e1e7c-6c0b-4f20-9cd0-1d5ccedae620-v1/bb64e937acf86447f6829767e958073c.fst
- Try to make a connection using the X key.
- Try to make a connection using the grip button on your handcontroller.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d05229d3b45a09775353e1de839a259d8024b383 available at: https://gist.github.com/6d58db9d5f1e87a2c0ca2bb61acb7378<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-d05229d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-d05229d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf81ae78b9dba608870bbea4e550cbb6ffb9d44a available at: https://gist.github.com/6d58db9d5f1e87a2c0ca2bb61acb7378<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-bf81ae7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-bf81ae7.dmg

**Comment by howard-stearns** [comment]
QA fail: 
One default avatar, one robot avatar as specified in instructions.
The robot avatar gets the connection.
The default avatar gets "expired" against the robot.

Investigating...

**Comment by howard-stearns** [comment]
(didn't mean to close it. hit wrong button)

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf81ae78b9dba608870bbea4e550cbb6ffb9d44a available at: https://gist.github.com/6d58db9d5f1e87a2c0ca2bb61acb7378<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-bf81ae7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10292-bf81ae7.dmg

**Comment by howard-stearns** [comment]
ok, test fail was because of a different bug: can't reliably shake hands with an avatar that is also logged in to a different place.

**Pull request merged**
