### PR TITLE
Fix orphaned particles left after making a user connection.

### PR DESCRIPTION
**Pull request by Nex-Pro**
Fix particles that are occasionally left over after user makes a connection.

To test:

Needs more than one avatar.

Both or all should run this pr.

Make multiple connection attempts using either or both controllers/extend hand with 'x' key.

Mess with the hand positions to break the connection early. Grip and quickly release etc.

Test with existing connections and avatars that are not connected.

Have an observer check that no orphan particles are left after making a connection or confirming a connection. 

I think this issue should be on Manuscript but I don't have full access.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15912/HighFidelity-Beta-PR14571-bf9d929.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15912/HighFidelity-Beta-PR14571-bf9d929.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15912/HighFidelity-Beta-Interface-PR14571-bf9d929.exe

**Comment by Nex-Pro** [comment]
The diff shows a lot of changes. A lot of that is due to linting. In essence I took the approach of storing the particle IDs in an array. When the script terminates it iterates through the array and deletes the particle Ents. by those IDs.
 I suspect that what was happening was that the IDs for 'particleEffect' and 'makingConnectionParticleEffect' were being set to undefined. This meant that when the Script.ending event happened it wasn't possible to clean up any  rogue particles as their IDs were effectively lost.

**Comment by zfox23** [comment]
Thanks for this PR, @Nex-Pro! The bug some users were seeing was occurring even before the `makeUserConnection.js` script was terminating for either party. I think the fix for deleting the particle entities when the script goes down is great! However, I'm not sure it'll actually fix the bug. I think the bug is actually somewhere in the script's main state machine, but I haven't looked too closely.

It seems to me like this PR also introduces the possibility of having multiple particle effects around, but without Timers associated with those effects. Those timers are necessary to update the properties of those entities. I don't think that _not_ having those timers will actually _break_ anything, but it does seem to me like we'll introduce other problems by decoupling the effects and the timers.

**Comment by Nex-Pro** [comment]
@zfox23 Yep but this is a more robust way of cleaning up.

**Comment by zfox23** [comment]
@Nex-Pro You're right that your method of cleanup is a more robust method of cleanup than what was there. However, you took out the `lifetime` property of the particle emitters and not fixed the root cause of the bug, so the bug can still happen with this PR.

If you re-introduce the `lifetime` property, I will take another look at this PR from the lens of properly cleaning up the entities. Alternatively, you could have another crack at fixing the root cause of the bug!

**Comment by Nex-Pro** [comment]
I repeat I didn't remove that, that would not make sense. I notice that they are both missing from the current distro! I'll add them here.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16029/HighFidelity-Beta-PR14571-478e893.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16029/HighFidelity-Beta-PR14571-478e893.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16029/HighFidelity-Beta-Interface-PR14571-478e893.dmg

**Comment by zfox23** [comment]
Closing this PR after Slack discussion.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16029/HighFidelity-Beta-PR14571-478e893.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16029/HighFidelity-Beta-Interface-PR14571-478e893.exe

**Pull request closed without merging**
