### PR TITLE
Add support for oculus touch in help menu

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f166d82ce000bce14590e2f1f797bcbc2b02e4d available at: https://gist.github.com/808602933d2a76d4b3820cf4b23d78f5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-9f166d8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-9f166d8.dmg

**Comment by birarda** [comment]
I believe that buttons for Oculus home and menu are switched in the diagram. Button for Oculus Home is right hand.

**Comment by birarda** [comment]
Do the console logs you have for query string testing print in the Interface log? If so, I think we should remove them.

**Comment by huffman** [comment]
Thanks for pointing that out, I didn't mean to leave those. I will leave the one error though, that should never be reached.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3e5d67f28b23693b103c5d41a0ef6f6b08e6320e available at: https://gist.github.com/808602933d2a76d4b3820cf4b23d78f5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-3e5d67f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-3e5d67f.dmg

**Comment by huffman** [comment]
To test:

1. Clear your settings
2. Launch with Oculus Touch
3. You should see the help window pop up with the Hand Controllers tab activated and instructions on how to use the Oculus Touch

I've tested the other cases a couple of times.

**Comment by birarda** [comment]
Tested with cleared settings, showed Oculus Touch instructions. QA Pass.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c441ac3ee68e1f291095bf67462443d68784219 available at: https://gist.github.com/808602933d2a76d4b3820cf4b23d78f5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-7c441ac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9189-7c441ac.dmg

**Pull request merged**
