### PR TITLE
start device check timer

### PR DESCRIPTION
**Pull request by zzmp**
Start the device check timer after its setup.

### CODE REVIEW

**Comment by zzmp** [comment]
QA: make sure that when you plug and unplug audio devices, they show up correctly in the menus.

**Comment by CainFoool** [comment]
Hey @zzmp: Is this QA Ready?

**Comment by zzmp** [comment]
@CainFoool definitely

**Comment by CainFoool** [comment]
Testing once built! :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/662/HighFidelity-Beta-PR10679-9017738a8d81fc1fed66bab98364aa6d950e4f13.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/662/HighFidelity-Beta-PR10679-9017738a8d81fc1fed66bab98364aa6d950e4f13.dmg

**Comment by CainFoool** [comment]
# Testing Passed 

Output and Input Devices re-appear once unplugged and unplugged, and they also appear to re-check themselves once plugged back in. However one thing I did notice however was with Local and Server Audio Playback enabled, I had to tick a different input/output device and go back to the device I started with in order to get it to work again.

**Pull request merged**
