### PR TITLE
Replacing jump_takeoff.fbx and jump_land.fbx animations to fix transition to fly bug 

### PR DESCRIPTION
**Pull request by amantley**
This pr fixes bug with tpose in the transition to fly.
The bug is here: https://highfidelity.manuscript.com/f/cases/17588/Avatar-goes-to-T-pose-while-trying-to-fly-when-walking-running

### Test plan:  
1) open interface and start walking and then press the pg up key to fly.
You should no longer see a t-pose happening in the transition to and from flying
2) repeat 1 with running and flying.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12117/HighFidelity-Beta-PR13827-0a1a75f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12117/HighFidelity-Beta-PR13827-0a1a75f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12117/HighFidelity-Beta-Interface-PR13827-0a1a75f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12117/HighFidelity-Beta-PR13827-0a1a75f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12117/HighFidelity-Beta-Interface-PR13827-0a1a75f.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No T-Pose animation occurred.

**Pull request merged**
