### PR TITLE
Fix tablet scripting interface setting its internal state to home when switching between toolbar and tablet mode

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- make sure that your domain is not running
- make sure that you clear all your domain settings
- Have your HMD on your head, start interface...automatically switch to desktop mode (you should be in away mode)
- one in desktop don't do anything to get out of away mode.. carefully switch to tablet mode
- bring up the tablet and you should be on the help screen. 
- then click on the x button on the tablet. It should bring you to the home screen and close the tablet.

**Comment by YuppyPlays** [comment]
Will test once built :)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1638/HighFidelity-Beta-PR10959-e07b067d7b0be083bb8301005d44cb9c01563f8c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1638/HighFidelity-Beta-PR10959-e07b067d7b0be083bb8301005d44cb9c01563f8c.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

make sure that your domain is not running **Check**
make sure that you clear all your domain settings **Check**
Have your HMD on your head, start interface...automatically switch to desktop mode (the help button should be highlighted but not displayed) **Check, though not sure how I'd confirm in taskbar view that it's highlighted.**
switch over to tablet mode **Check**
bring up the tablet and you should be on the help screen. **Check**
then click on the x button on the tablet. It should bring you to the home screen and close the tablet. **Initially this failed but upon retesting seemed to work? See notes below**

Note: I did a full clean of all HF versions and clean install instructions to accompany this after a fail in the final step mentioned, but upon the 2nd attempt the Help was displayed in taskbar but from what I gather should not have been visible? Up to dev to decide if this is an overall pass/fail.

**Comment by themelissabrown** [comment]
@YuppyPlays can you do a clean install and test this again and provide results?

**Comment by YuppyPlays** [comment]
@themelissabrown No problem at all, doing this now :)

**Comment by YuppyPlays** [comment]
Testing complete:

Clean installed (again), but taskbar still shows the help icon which I don't believe is intended especially not highlighted?
image

when in tablet mode on desktop, it still brings up the help scree after pressing the X on the tablet
image

**Fail**

**Comment by druiz17** [comment]
@YuppyPlays Can I get a re-test of this PR. I modified the test plan to be less ambiguous than what I had before.

**Comment by YuppyPlays** [comment]
Sure thing, will confirm shortly.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

make sure that your domain is not running **Check**
make sure that you clear all high fidelity data from the roaming and local folders in your AppData directory **Check**
When you start interface you should be in HMD mode, switch into desktop mode right away **Check, using the top menu bar of the application of course**
Once you are in desktop, use the menu bar to switch to tablet mode, do not use the toolbar to switch **Check, previously I was using the top menu bar on the application, this time used the Menu bar in-game**
Once you are in tablet mode, bring up the tablet and you should be on the help screen. **Check**
Press the X button on the tablet, you should be brought back to the home screen. Pressing it again  **Check** 
should close the tablet.  **Check** 
open the tablet and you should be on the home screen...not the help screen.**Pass!**

**Notes: I think it should be fixed so that doing it from either "In-game toolbar menu" or the "applications toolbar menu (located at the top of the actual window) - both should work in my opinion as users are more than likely going to be using either method depending on familiarity with the software and we don't want their tablets to be locked on help screen  if they happen to do it in the 2nd mentioned way.**

**Comment by druiz17** [comment]
@YuppyPlays I agree with you. The test plan that I provided was the only way I got the help screen locked on the tablet. I tried to repro the issue different ways and had no success. If you have another exact repo please let me know.

**Pull request merged**
