### PR TITLE
Fix QT typo

### PR DESCRIPTION
**Pull request by MiladNazeri**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8878/app_12926_PR_40e311fe1ee640c68ab87eeae71aa1ffff44e74f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8878/HighFidelity-Beta-PR12926-40e311fe1ee640c68ab87eeae71aa1ffff44e74f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8878/HighFidelity-Beta-Interface-PR12926-40e311fe1ee640c68ab87eeae71aa1ffff44e74f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8878/HighFidelity-Beta-PR12926-40e311fe1ee640c68ab87eeae71aa1ffff44e74f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8878/HighFidelity-Beta-Interface-PR12926-40e311fe1ee640c68ab87eeae71aa1ffff44e74f.exe

**Comment by conklin94122** [comment]
Missed RC66, moving to RC67.

**Pull request merged**
