### PR TITLE
Trying to fix/clean up 3DConnexion stuff

### PR DESCRIPTION
**Pull request by SamGondelman**
Mostly style fixes, trying to fix up crash on exit on windows.

This is just a first pass mostly meant to fix up some linking/crashing issues.  There are lots of style changes that still need to be made but that will be later.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b8f7d4b8c8a25124b0382378bdf00570597dd981 available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a01a4f929f50d99e4e45406ce3072991821b3e66 available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Comment by ctrlaltdavid** [comment]
Tested on Windows. ... It does not crash on exit whereas the latest official Windows build always does.

**Comment by SamGondelman** [comment]
Just to make absolutely sure, when you tested that, did cmake say it found the 3DConnexionClient or not?  If it didn't find the client (which I'm finding doesn't happen on windows in certain situations), it won't call the supposedly broken destroy method.  If it is finding the framework, then it's actually fixed.

**Comment by ctrlaltdavid** [comment]
@SamGondelman I just downloaded and installed the build that Gustavo provided.

**Comment by SamGondelman** [comment]
Ah ok gotcha.  Thanks.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25e75bcc7938f04203330501cc05c8048c7b7ec8 available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8daee013e80178230580754537222f41422c5b6 available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8908c7c1417525477a9f9a79b9a5c6375565847f available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95232920f109e0d2fdff0612b87e46100b4eb66a available at: https://gist.github.com/270f22d4574d12d063c4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5465.dmg

**Pull request merged**
