### PR TITLE
Don't sort recordings

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Run record.js
Recordings displayed in the table are not necessarily displayed in alphabetical order.

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb8f75394d51282ebea2508de615573742a51fbe available at: https://gist.github.com/4d9372c2f02c7aa56f7abdd70396533c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10348-cb8f753.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10348-cb8f753.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb8f75394d51282ebea2508de615573742a51fbe available at: https://gist.github.com/4d9372c2f02c7aa56f7abdd70396533c<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10348-cb8f753.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10348-cb8f753.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10348-cb8f753.exe

PASS:
- I produced 6 recordings and then unloaded them from the table. I then loaded all 6 recordings back, but this time making sure they were not in alphabetical order. The recordings displayed on the table are not in alphabetical order.
apr10348

**Pull request merged**
