### PR TITLE
Beta Release 16 - Includes up to Developer Release 5179

### PR DESCRIPTION
**Pull request by cozza13**
Testing script: http://cdn.rawgit.com/cozza13/QAtesting/master/QAofRC.js

* Don't show user’s border when hover mouse if logged out
* Improved audio pipeline: remove all hard clipping and improve audio quality.
* Prevent users window from being dragged off screen
* Snapshot takes picture of HMD window instead of preview
* Fix TypedArray byte ordering and .subarray indexing. Fixes a few small but critical bugs in the JS TypedArrays implementation: 
* Fix canRezTmp logic (incorrectly) resets valid lifetimes to the maximum value
* Fix export entities by region
* Fix modTouchscreen camera input for Interface
* Fixes a crash that occurs when switching between several domains too fast.
* Add teleportation to the array of movement options. 
* Support alpha and color gradients in circle overlays
* New javascript for ray picking against avatars
* Various snapshot improvements
* Fix MyAvatar name and url accessors.
* Expand frame decoration when mouse is over a window in HMD mode
* Fix orientation being reset to 0,0,0,1
* Audio codecs support.
* Update max request limit and number of processing threads
* Spatialization and HRTF for local audio injectors
* Ignore Avatar featureel overlays not correctly scaling
* Basic hand-controller editing
* Added Mac preview image if VSync is enabled
* Add missing loading images for Asset Browser
* Various performance optimizations
* Fix rendering of overlay spheres with alpha
* Ensure newly shown windows are popped to the top of the zorder
* Fixed issues in some popup windows
* New entity collision shape options
* Support for glowing 3D line overlays
* Interface changes for new Marketplace
* Refresh feature/grab script polish
* * Support for scale property on model overlays.
* Improved throwing with hand-controllers.
* Improved HRTF
* Update all asset server responses to be reliable
* Menu & hand controller polish
* Toolbar improvements
* Delete old Interface logs
* Fix the AudioMixer distance attenuation.
* Fix hover states for toolbar buttons
* Make search line termination a circle, like 2D UI
* Grab Script Improvements
* Fix decoration inflation
* Grab Script Polish
* Make search line termination a circle, like 2D UI
* Fix hover states for toolbar buttons
* Fix the AudioMixer distance attenuation.
* Support triangle and hexagon shapes, add shape support to overlays.
* Injectors now always play locally, and send to server without echo
* Actually delete textures we're not using
* improve throwing release velocity
* Changes for hifiCodec plugin building on Linux
* Cleanup resources used by offscreen GL surfaces 
* Ensure the pause overlay is unlit (emissive)
* Far-grabbed objects no longer fly away when the avatar body shifts
* fix crash with multiple solo nodes in closeCurrentPacket
* Show up to three suggested domains when you bring up the GoTo address bar. Clicking on picture takes you there. Can filter results by typing.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc4c21e8995cae56cb81d83b4ba7911ee43de841 available at: https://gist.github.com/1c8764f271182c4301e18345c2a2050f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8289-cc4c21e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8289-cc4c21e.dmg

**Comment by OmegaHeron** [comment]
## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:

Notable improvements;

playaPerformanceTest.js managed to pass at localhost and dev-demo without having to run test move to next test location and restart interface.  dev-playa failed, barely, but, it continues to be a dumping ground for "stuff" and its FPS seems to grow worse day by day regardless of Interface version.  Again - it would be ~nice~ if dev-playa was just a little more in sync with playa.

Standard Home Scene (aka "localhost") no longer memory leaks filling GPU VRAM after a few enters/exits.

Textures no longer in scope that can be deleted are being deleted as shown by substantial drops in VRAM use via GPU-Z on domain changes.

Audio works every time everywhere tested (dev-*, standard home, heron)/

No buzzsaw from resetting sensors.

Less improved but starting to show a little improvement;

Loading Standard home scene or other fairly heavy scenes is getting better on my i5 CPU - it's not good, but it's less bad (barely).

ATP now tends to always finish requests - though it's hard to say if that's 100% or not as known issues with my machine and standard home leads to it often disconnecting/reconnecting before it could, possibly, show a fail to fetch -- it all starts over.

Multiple visits to standard home scene in a single run session no longer utterly memory leaks (GPU VRAM) to death, but, there's still a continual degradation of performance I see directly tied to being at standard home, going other places, returning "home" more than once or twice.  It's likely there's still some oddities being triggered with its contents related to the (corrected) issue discovered of failure to delete culled textures and massive resource leak in GPU VRAM in home scene.  @jherico Investigated and offered fixes that allows it to be... less fatal.

Not improved at all;

Refreshing standard complaint that this is basically unusable on a machine with somewhat greater capacity than published base specs and remains utterly totally unusable if running Interface **and** stack on same machine.  It's all a known issue, but, I am going to keep refreshing it each RC until it changes so we don't lose sight of (i5 CPU issue).

Recorded 1 bugsplat event - While in another window typing these notes Interface started disconnecting/reconnecting to domain, I left it to do whatever it wanted... apparently that was crash.  Not reproduced after 3 tries.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok (via confirming I have current tarball for and installing its content on second machine)
**Test 3**|Retest that creating physicshulls is working|Ok
**Test 4**|Test Ignore and make sure it works|Ok
**Test 5**|test audio with multiple people|Ok (2 AVs - myself and my 2nd self with 2nd self on Linux laptop)

**Desktop 1600x900 maximized window, vsync unlocked **

**o2tech = localhost for content, unable to run stack and interface on same machine - o2tech is content server console downloads at second machine on LAN**

**Domain** |o2tech |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |136 |118 |142
**Present Rate**: |1632 |2348 |2585
**Present New Rate**: |136 |118 |142
**CPU Buffer Count**: |5075 |5412 |5038
**GPU Buffer Count**: |1568 |1850 |1215
**CPU Memory Usage**: |75567104 |93007872 |91766784
**GPU Memory Usage**: |56610816 |68530176 |50311168
**CPU Texture Count**: |309 |387 |385
**GPU Texture Count**: |647 |1375 |1525
**GPU Transfer Count**: |5 |5 |5
**CPU Texture Memory Usage**: |43057956 |71780288 |280517072
**GPU Texture Memory Usage**: |1107684977 |2322130479 |1455646605
**GPU Virtual Memory Usage**: |1230560177|2450348079|1583864205
**Triangle Count**: |283199 |800500 |626481
**Triangle Rate**: |56639800 |100062500 |89497285
**API Drawcall Count**: |184 |289 |249
**Drawcall Count**: |186 |353 |1147
**Drawcall Rate**: |37200 |44125 |163857
**State Changes Texture Count**:|201 |349 |289
**Pipeline Count**: |37 |38 |39
**Item Opaques**: |227 |459 |256
**Item Translucents**: |32 |55 |51
**Item Lights**: |30 |43 |25
**Timing Opaques**: |1706 |4590 |2888
**Timing Translucents**: |478 |421 |371
**Timing Lighting**: |200 |595 |302
**Render Frame**: |3741 |7267 |4804

**DK2**

**Domain** |o2tech |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |47 |75
**Present Rate**: |75 |47 |75
**Present New Rate**: |75 |45 |75
**CPU Buffer Count**: |6066 |6158 |5052
**GPU Buffer Count**: |2235 |2184 |1313
**CPU Memory Usage**: |87801856 |119422976 |91791360
**GPU Memory Usage**: |64507904 |83730432 |50970624
**CPU Texture Count**: |318 |397 |384
**GPU Texture Count**: |2204 |1903 |1569
**GPU Transfer Count**: |10 |5 |5
**CPU Texture Memory Usage**: |56199044 |63687712 |257235408
**GPU Texture Memory Usage**: |1230744334 |2360255166 |1486688295
**GPU Virtual Memory Usage**: |1620259726|2791301310|1805906343
**Triangle Count**: |490657 |2399177 |1366574
**Triangle Rate**: |40888083 |199931416 |105121076
**API Drawcall Count**: |201 |381 |309
**Drawcall Count**: |375 |773 |2359
**Drawcall Rate**: |31250 |64416 |181461
**State Changes Texture Count**:|161 |380 |308
**Pipeline Count**: |36 |41 |42
**Item Opaques**: |218 |511 |308
**Item Translucents**: |47 |64 |52
**Item Lights**: |28 |55 |25
**Timing Opaques**: |1425 |3166 |2081
**Timing Translucents**: |185 |237 |527
**Timing Lighting**: |198 |366 |255
**Render Frame**: |2729 |5031 |3894

**Comment by SkimiMission** [comment]
I have still the same problem like in the previously build. Desktop mode works fine, when I switch to my Vive, the screen freeze, the log just spawn this openGL error:

`[07/21 06:20:50] [WARNING] OpenGL error in presentation:  Invalid OpenGL operation`

**Comment by SkimiMission** [comment]
Okay, now I've installed all available releases from 8289 down to 8260. The OpenGL error happens in every release from 8261. The last release I can use with my Vive is 8260.

Hope that helps somehow. Thanks

**Comment by cozza13** [comment]
I have been using the system for the last hour and it is performing well.

**Pull request merged**
