### PR TITLE
log purge

### PR DESCRIPTION
**Pull request by howard-stearns**
Make script debugging more more obtuse.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://highfidelity.manuscript.com/f/cases/20527/Logs-showing-full-URLs

Test plan: see ticket

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16398/HighFidelity-Beta-PR14697-62ed84a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16398/HighFidelity-Beta-PR14697-62ed84a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16398/HighFidelity-Beta-Interface-PR14697-62ed84a.dmg

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
Pass

**Pull request merged**
