### PR TITLE
improve comment in domain settings

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- run sandbox
- go to domain settings
- Show Advanced
- Metaverse/Networking -- see the help/comment for the Local UDP Port and see if it makes sense and doesn't have spelling mistakes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e49e8025ab84d11a8363e058ee5b837961e5b68 available at: https://gist.github.com/0fa64b828d11d8ccebeffc8e854138ff<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9405-5e49e80.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9405-5e49e80.dmg

**Comment by Nex-Pro** [comment]
checking this

**Comment by Nex-Pro** [comment]
## PASS

This is the local port your domain-server binds to for UDP connections.
Depending on your router, this may need to be changed to unique values for each domain-server in order to run multiple full automatic networking domain-servers in the same network. You can use the value 0 to have the domain-server select a random port, which will help in preventing port collisions.

Seems ok to me.

**Pull request merged**
