### PR TITLE
evolve the Transform stack away from the legacy GL to the brand new shader way

### PR DESCRIPTION
**Pull request by samcake**
- for the rendering of Avatar and Model we removed the glTransform legacy interface from all the shaders, the transform stack is defined by setProjectionTransform, setViewTransform & setModelTransform on the gpu::Batch

- Added the gpu/Transform.slh shader to be included and providing the functions to rely on the gpu::Batch/Backend Transform stack in user shader.

- Totaly removed the glTransform (for windows, sorry Mac) from the GLBackend

- modified the cmake to support the shaders includes from several libraries

- in order to render the avatar properly i we had to pass around the viewFrustum in use (to apply correctly the transform stack) and this exhibited a bug with the Head not updating it's bounding box in the model, this is now fixed hopefully

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ab3cbb7ecca4d736ea936f4875c0f96769b1f5b available at: https://gist.github.com/80ecbb6aeef9b364a231<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5652852d1a42e19db6f66e4a4fb1c376fad1aa94 available at: https://gist.github.com/63ebeeaeffe2babf5267<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f92efa13c8a415190a57ef03e820496c49ecf806 available at: https://gist.github.com/c1e1c97f0f41ad26f539<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.dmg

**Comment by PhilipRosedale** [comment]
@samcake @ZappoMan is this one ready to go?

**Comment by samcake** [comment]
The build is apparently failing on linux
I ll check it tomorrow

S

**Comment by hifi-gustavo** [comment]
Build console output for commit: 598b791aeed5c2139a5b2906d7885fc0df6885c1 available at: https://gist.github.com/523a01b60813a4f4ddeb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cad21849275b821b33eb4b81635dd5747e5e19ec available at: https://gist.github.com/523a01b60813a4f4ddeb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4361.dmg

**Pull request merged**
