### PR TITLE
Default to darker reverb settings

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f6e9718399f1c38e5db103a578f39be6dfc04e6 available at: https://gist.github.com/ae9e559c7a8ca20957c846493097f049<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7967.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7967.dmg

**Comment by ZappoMan** [comment]
@kencooke - can you provide a testing plan for this?

**Comment by kencooke** [comment]
To test, go can go to Demo and enable Server Echo.  You should notice that reverb sounds slightly less bright, as if a carpet were added to the hardwood floors.

**Comment by cozza13** [comment]
@kencooke , this needs to be updated with master to grab new protocol changes

**Pull request closed without merging**
