### PR TITLE
RC66: Possible fix for QML texture leak

### PR DESCRIPTION
**Pull request by SamGondelman**
See https://github.com/highfidelity/hifi/pull/12809 for test plan

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8578/app_12816_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8578/HighFidelity-Beta-PR12816-d38dadaf58e193a53cb002b4960e922e92123b3b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8578/HighFidelity-Beta-PR12816-d38dadaf58e193a53cb002b4960e922e92123b3b.exe

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

On all systems, if the testers let the script run without moving, numbers would remain stable and no crashes occurred. On 3/4 systems, if the testers moved while the script was running, the interface would crash approximately 2/5 times. After clarification from @SamGondelman (relayed via George), this is expected behavior as the script is designed to stress the system so crashes are not necessarily a concern. With that being said, we're comfortable calling this a pass.

**Comment by samcake** [comment]
Approved

**Pull request merged**
