### PR TITLE
DEV-266: Add serverless tutorial

### PR DESCRIPTION
**Pull request by huffman**
Do the work to re-enable serverless tutorial on the client, 
https://highfidelity.atlassian.net/browse/DEV-266

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20525/HighFidelity-Beta-PR15976-982835a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20525/HighFidelity-Quest-Beta-PR15976-982835a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20525/HighFidelity-Beta-PR15976-982835a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20525/HighFidelity-Beta-Interface-PR15976-982835a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20525/HighFidelity-Beta-PR15976-982835a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20525/HighFidelity-Beta-Interface-PR15976-982835a.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20529/HighFidelity-Beta-PR15976-cf71d6c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20529/HighFidelity-Quest-Beta-PR15976-cf71d6c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20529/HighFidelity-Beta-PR15976-cf71d6c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20529/HighFidelity-Beta-Interface-PR15976-cf71d6c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20529/HighFidelity-Beta-PR15976-cf71d6c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20529/HighFidelity-Beta-Interface-PR15976-cf71d6c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20545/HighFidelity-Beta-PR15976-7f3fdf0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20545/HighFidelity-Beta-Interface-PR15976-7f3fdf0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20545/HighFidelity-Beta-PR15976-7f3fdf0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20545/HighFidelity-Beta-Interface-PR15976-7f3fdf0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20553/HighFidelity-Beta-PR15976-2ec87f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20553/HighFidelity-Beta-Interface-PR15976-2ec87f4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20553/HighFidelity-Beta-PR15976-2ec87f4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20553/HighFidelity-Quest-Beta-PR15976-2ec87f4.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20565/HighFidelity-Beta-PR15976-2ec87f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20565/HighFidelity-Beta-Interface-PR15976-2ec87f4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20565/HighFidelity-Beta-PR15976-2ec87f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20565/HighFidelity-Beta-Interface-PR15976-2ec87f4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20565/HighFidelity-Beta-PR15976-2ec87f4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20565/HighFidelity-Quest-Beta-PR15976-2ec87f4.apk)

**Pull request merged**
