### PR TITLE
Fix teleporting to another user from the PAL

### PR DESCRIPTION
**Pull request by zfox23**
Previously, teleporting to another user using the PAL would frequently result in your avatar's orientation being skewed. If you were in HMD, this was especially nauseating.

Now, that doesn't happen :)

**Test Plan:**
1. In Desktop mode, navigate to a domain with at least one other avatar in it. The other avatar's availability must be set such that you can see their username in the PAL.
2. Click on their display name or username.
3. Verify that you are teleported in front of that user and that the orientation of your avatar is correct.
4. Switch to HMD mode and perform steps (2) and (3) again.
5. Scale your avatar wayyyy up so that you're a giant compared to the other avatar! Then repeat steps (2) and (3) again.
6. Scale your avatar wayyyy down so that you're tiny compared to the other avatar! Then repeat steps (2) and (3) again.

### CODE REVIEW

**Comment by zfox23** [comment]
[fix goto in pal](https://trello.com/c/9JiZOqlQ/194-fix-goto-in-pal)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/808/HighFidelity-Beta-PR10726-6b659101d583c3d64fbcf7be8e28d5c1397d5082.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/808/HighFidelity-Beta-PR10726-6b659101d583c3d64fbcf7be8e28d5c1397d5082.dmg

**Comment by zfox23** [comment]
Thanks to @thoys for helping me implement and test this fix 😄

**Comment by CainFoool** [comment]
Testing :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/816/HighFidelity-Beta-PR10726-6230dcf93ddd2d818757941880deee953d7df40b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/816/HighFidelity-Beta-PR10726-6230dcf93ddd2d818757941880deee953d7df40b.exe

**Comment by CainFoool** [comment]
# Test Passed

I teleported in the right orientation when clicking on a username in the PAL list on both Desktop and HMD.

**Pull request merged**
