### PR TITLE
fix fresh MinSizeRel and RelWithDebugInfo builds

### PR DESCRIPTION
**Pull request by birarda**
- updated locations for external libraries for fresh MinSizeRel and RelWithDebugInfo builds

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

From this PR, starting with an empty build folder on Windows:

(1) Empty your build folder.
(2) Run CMake.
(3) Build ALL_BUILD using the "MinSizeRel" configuration. It should succeed.
(4) Test the same process on master. It will fail to find some of our external libraries.
(5) Repeat 1-4 for "RelWithDebugInfo".

**Comment by hifi-gustavo** [comment]
Build console output for commit: a7987734251ab53807cdac97296249a3d235688b available at: https://gist.github.com/0534591daedab3b2dee0de41dd7d47df<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9989-a798773.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9989-a798773.dmg

**Comment by OmegaHeron** [comment]
Testing this (have been working on it a bit) - Just want to be sure no other wastes half a day getting setup and running this test.

**Comment by OmegaHeron** [comment]
Tested Windows 10 - VS 2013 Community Edition

Started from a system with no VS Install or per-requisites in place to compile HF.  Setup everything as outlined in build guide.

QA Pass.

**Master**
MinSizeRel (Fail, as expected)
========== Build: 65 succeeded, 14 failed, 0 up-to-date, 0 skipped ==========
RelWithDebugInfo (Fail, as expected)
========== Build: 65 succeeded, 14 failed, 0 up-to-date, 0 skipped ==========
Debug (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Release (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Pulled source this PR 9989 (Also confirmed Interface binary produced works for each build type)

**PR**
MinSizeRel (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
RelWithDebugInfo (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Debug (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Release (Pass)
========== Build: 79 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Tested HiFi produced PR Installer.  Pass

Also tested that PR compiles proper for Linux with my PR build system.  Pass

**Pull request merged**
