### PR TITLE
D NOT MERGE - Test change - Testing build environment

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/09950dcd773febe3a87bf110baa57a88<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8889-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8889-271a871.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 271a871c9c98ea754efa8320ac4288400b88675f available at: https://gist.github.com/09950dcd773febe3a87bf110baa57a88<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8889-271a871.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8889-271a871.dmg

**Comment by hifi-gustavo** [comment]
This is just a test

**Comment by ZappoMan** [comment]
closing this old "test" PR

**Pull request closed without merging**
