### PR TITLE
fix -- don't honor gravity in simple extrapolation on entities equipped by others

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that caused items equipped by others appear to fall through the floor

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- with HMD and hand controllers, find an equippable item with gravity on it
- get a second person logged in and watching
- equip the item, have second person confirm that they see it in your hand rather than falling through the floor

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6b44f6298262f08669d7d163bb0b1cdcddfc1008 available at: https://gist.github.com/6c6074af9f88591e85f9b33108af36d2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9596-6b44f62.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9596-6b44f62.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by claudioshg** [comment]
Testing with Kevin

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested with Oculus and Oculus Touch utilizing hand controllers and successfully and equipped clown hammer physical item with gravity on it.  @claudioshg tested with me and verified that he saw me equip the item and saw it in my hand rather than falling through the floor.  Images attached.
image

**Comment by sethalves** [comment]
I think the clown hammer isn't properly "equippable".  The test requires something that shows the blue sphere around the grab point when your hand gets close.  Try this with the flare gun.

**Comment by kevinmthomasse** [comment]
@sethalves sorry about that the hammer I was able to grab and hold.  Isnt that what you mean by equippable?

**Comment by sethalves** [comment]
You can "grab" something without "equipping" it.  When something is grabbed, you release the trigger and it falls.  When something is equipped, you release the trigger and it stays stuck to your hand until you unequip it.  Equippable things show a blue sphere when your hand moves close to the equip point, and they will snap to a pre-programmed position when you squeeze the trigger.

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested with Oculus and Oculus Touch utilizing hand controllers and successfully and equipped the flare gun physical item with gravity on it.  @claudioshg tested with me and verified that he saw me equip the item and saw it in my hand rather than falling through the floor.  Images attached.
kevin_flare

**Pull request merged**
