### PR TITLE
Move Shapes app from hifi to hifi-content

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9716/app_13160_PR_ae23a63ca8586c390ab023e924ecc642cb8dd2e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9716/HighFidelity-Beta-PR13160-ae23a63ca8586c390ab023e924ecc642cb8dd2e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9716/HighFidelity-Beta-Interface-PR13160-ae23a63ca8586c390ab023e924ecc642cb8dd2e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9716/HighFidelity-Beta-PR13160-ae23a63ca8586c390ab023e924ecc642cb8dd2e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9716/HighFidelity-Beta-Interface-PR13160-ae23a63ca8586c390ab023e924ecc642cb8dd2e1.exe

**Comment by hyperlogic** [comment]
@ctrlaltdavid please fix merge conflict

**Pull request closed without merging**
