### PR TITLE
Stand-alone Tagging: tagged places not coming first in GOTO list

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.manuscript.com/f/cases/21790/Stand-alone-Tagging-tagged-places-not-coming-first-in-GOTO-list

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18239/HighFidelity-Beta-PR15215-b6e5830.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18239/HighFidelity-Quest-Beta-PR15215-b6e5830.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18239/HighFidelity-Beta-PR15215-b6e5830.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18239/HighFidelity-Beta-Interface-PR15215-b6e5830.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18239/HighFidelity-Beta-PR15215-b6e5830.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18239/HighFidelity-Beta-Interface-PR15215-b6e5830.exe

**Comment by rickcarr044** [comment]
QA approved to merge this and test in staging

**Pull request merged**
