### PR TITLE
Playa fireworks and associated tutorial

### PR DESCRIPTION
**Pull request by ericrius1**
This PR adds a fireworks experience where you can spawn a launch button, and on click or trigger, launch fireworks into the sky.

It also adds the code as a series of chapters for a tutorial that walks new content creators through the process of creating the fireworks (https://docs.highfidelity.com/docs/fireworks-scripting-tutorial)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2029532070edca6ec1067332d47dafc29bc3bcb9 available at: https://gist.github.com/362c7f4572894bbf6869<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.dmg

**Comment by cozza13** [comment]
I have tested this and it works

**Comment by imgntn** [comment]
@ericrius1 can you please add headers to all of these files w/ license and i'll dev approve & merge?   thanks!!

**Comment by ericrius1** [comment]
@imgntn done!

**Comment by hifi-gustavo** [comment]
Build console output for commit: caca60c0390770c66e82f8c5def0639be06837c6 available at: https://gist.github.com/362c7f4572894bbf6869<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ca747bb4e95bf31bc2b624fb37057dac151eb6c8 available at: https://gist.github.com/362c7f4572894bbf6869<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7249.dmg

**Pull request merged**
