### PR TITLE
Fix offset when UI transform is not identity

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 975c70ef719d0124632506121d4028fb98e981c8 available at: https://gist.github.com/e1257c53c22b9cfe444a8b1b6da8195e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12a260135455f4b903eb38a7f8e820823c2b5601 available at: https://gist.github.com/e1257c53c22b9cfe444a8b1b6da8195e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.dmg

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GkMpj61l&#x2F;21-make-laser-appear-on-overlays-and-be-able-to-press-buttons-etc"> Make laser appear on overlays and be able to press buttons etc</a>

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3c47acbb240871a9889606fe1b0f6127dd3f160 available at: https://gist.github.com/e1257c53c22b9cfe444a8b1b6da8195e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3c47acbb240871a9889606fe1b0f6127dd3f160 available at: https://gist.github.com/e1257c53c22b9cfe444a8b1b6da8195e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8062.dmg

**Comment by howard-stearns** [comment]
nice. Passes.

**Pull request merged**
