### PR TITLE
RC67: Allow gifting of Pending items; remove PoP verification rescheduling on Pending items

### PR DESCRIPTION
**Pull request by zfox23**
67 version of #13028 

The latest push into this includes https://github.com/highfidelity/hifi/pull/13031 for testing purposes.

Fixes:
- https://highfidelity.fogbugz.com/f/cases/14603/domain-server-deletes-delays-dynamic-ownership-challenge-by-90-seconds-if-transaction-still-pending
- https://highfidelity.fogbugz.com/f/cases/14606/Cannot-gift-while-pending
- https://highfidelity.fogbugz.com/f/cases/14295/UI-QA-in-Gifts-project-4-Bugs-reported (2nd try)
- https://highfidelity.fogbugz.com/f/cases/14559/Clicking-on-a-nearby-orb-when-sending-money-or-gifts-to-someone-nearby-sometimes-yields-no-result (2nd try)

### CODE REVIEW

**Comment by zfox23** [comment]
Do not test externally.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9277/HighFidelity-Beta-PR13035-684d2b08ba6206ff1e1f49f925a7e651004a36d9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9277/HighFidelity-Beta-Interface-PR13035-684d2b08ba6206ff1e1f49f925a7e651004a36d9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9277/HighFidelity-Beta-PR13035-684d2b08ba6206ff1e1f49f925a7e651004a36d9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9277/HighFidelity-Beta-Interface-PR13035-684d2b08ba6206ff1e1f49f925a7e651004a36d9.exe

**Comment by howard-stearns** [comment]
tested by howard and Zach

**Pull request merged**
