### PR TITLE
DEV-2840: Fix z-fighting issues in Smartboard and enable quicker positional iteration in the future

### PR DESCRIPTION
**Pull request by zfox23**
[DEV-2840](https://highfidelity.atlassian.net/browse/DEV-2840)

See ticket for more details.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22722/HighFidelity-Beta-PR16547-8be866e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22722/HighFidelity-Beta-Interface-PR16547-8be866e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22722/HighFidelity-Beta-PR16547-8be866e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22722/HighFidelity-Quest-Beta-PR16547-8be866e.apk)

**Comment by ZappoMan** [comment]
The build failure on the Jenkins build looks like a build machine problem, not a code problem, If the GHA windows build finishes (as I expect it will) I think we can safely assume this is a build, and "force merge" it as we see fit.

**Pull request merged**
