### PR TITLE
if something is locked but in motion, make it kinematic rather than static

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Will test this when available/required @sethalves

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/90/HighFidelity-Beta-PR10521-3825830fac860f157193932463ace3a9e47616e1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/90/HighFidelity-Beta-PR10521-3825830fac860f157193932463ace3a9e47616e1.dmg

**Comment by sethalves** [comment]
to test:
- rez a cube
- use *create* to set its angular damping to zero
- give it angular velocity
- make sure it keeps spinning
- relog
- make sure it's still spinning

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Testing Passed 

The cube rotates around as expected with pitch, yaw and roll and the chest functions as you would expect. The lid opens and closes with the body locked into place, unable to move.

**Pull request merged**
