### PR TITLE
use MachineGuid for slightly safer windows machine fingerprint

### PR DESCRIPTION
**Pull request by birarda**
- changed windows machine fingerprinting strategy to use machine guid

### CODE REVIEW

**Comment by birarda** [comment]
I'd like to have left a clearer comment in the code about why this is still a problematic strategy, but that may lead potential griefers down a valuable path. This still has its limitations, but I believe it will lead to far fewer unintentional connection refusals than the current strategy.

**Comment by birarda** [comment]
#### Test Plan

1. With this PR, connect to a domain-server you are running. Make sure you are not logged in in Interface.
2. Watch the log of the domain-server. When you connect, you should see it debug your machine fingerprint. Note it down.
3. Close Interface and relaunch it. Ensure that the logged machine fingerprint is the same.
4. Connect to your domain-server from the Interface client from this PR using a different machine. The second Interface client should also not be logged in. Ensure that the reported machine fingerprint is different than the one you noted for the first machine.
5. Block either of the machine fingerprints from connecting to your domain and ensure that the blocked Interface client is unable to connect. The easiest way to do this is to use the PAL to kick the other avatar. You may also copy the machine fingerprint from your log and put it manually in the Security section of your domain-server settings. If you do it manually, you must surround the ID with curly braces.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c22a353b38846cce541b985bcac708511efc6a8 available at: https://gist.github.com/2e01169d6e7c2707b8c5735dd9bd4c33<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1c22a35.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1c22a35.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c22a353b38846cce541b985bcac708511efc6a8 available at: https://gist.github.com/2e01169d6e7c2707b8c5735dd9bd4c33<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1c22a35.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1c22a35.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f0c5a81b97abbaf7ba432819f74a23b846f9f69 available at: https://gist.github.com/2e01169d6e7c2707b8c5735dd9bd4c33<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-2f0c5a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-2f0c5a8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1857b297e091bf0441526c5420436e13f8bc9582 available at: https://gist.github.com/2e01169d6e7c2707b8c5735dd9bd4c33<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1857b29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1857b29.dmg

**Comment by OmegaHeron** [comment]
Testing now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1857b297e091bf0441526c5420436e13f8bc9582 available at: https://gist.github.com/2e01169d6e7c2707b8c5735dd9bd4c33<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1857b29.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10349-1857b29.dmg

**Comment by OmegaHeron** [comment]
Testing now.

**Comment by OmegaHeron** [comment]
Tested windows 10 and Ubuntu 16.04
QA Pass

Machine 1 Win 10 running this PR sandbox and Interface.  Machine 2 running Ubuntu and this PR interface connecting to machine 1.

With this PR, connect to a domain-server you are running. Make sure you are not logged in in Interface.
Watch the log of the domain-server. When you connect, you should see it debug your machine fingerprint. Note it down.  *Completed*

Close Interface, remove the settings file for the Interface from this PR and relaunch it... Reconnect to the domain and ensure that the logged machine fingerprint is the same.  *Completed/pass*

Connect to your domain-server from the Interface client from this PR using a different machine... *Completed/pass* (And cleaned settings and confirmed same fingerprint was generated for machine 2)

Block either of the machine fingerprints... *Pass*

Remove the blocked machine fingerprint in the domain server settings and ensure the Interface client can connect again. *Pass*

**Pull request merged**
