### PR TITLE
Reverb smoothing

### PR DESCRIPTION
**Pull request by Atlante45**
- Damp reverb next to audio zones walls
- Reverb done at input level now, not received audio.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/71ca3eeeeac8cca298a6<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/3ca0bf89fa15cb9d2578<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by Atlante45** [comment]
@murillodigital You should take a look at the first build. It lloks like [that bug](https://issues.jenkins-ci.org/browse/JENKINS-24753?page=com.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel)

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/505e53660525f2d998d4<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/883f8c6abc46c9cfe892<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/d5554ba041377ff1ac30<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/77ff5eca48a138d214fb<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/8cc24ef506d2e91acb64<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17ce2e820fe9bf06bb054305f49d029662f90b80 available at: https://gist.github.com/86923ea8c1f405fe80a1<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4291.dmg

**Comment by Atlante45** [comment]
Tested with Freddy, good to merge.

**Comment by PhilipRosedale** [comment]
I've tested that this behavior is correct, with the windows build, and am pulling it.  An item for future work: 

Audio injectors should also apply reverb to injected sources if told by the mixer, where currently only interface does.

**Pull request merged**
