### PR TITLE
allow ATP scripts to be used by scripted Agent

### PR DESCRIPTION
**Pull request by birarda**
- use ResourceRequest in Agent so ATP scripts can be used

### CODE REVIEW

**Comment by birarda** [comment]
This is part of the work required for new home set to be fully ATP. I changed the Agent assignment-client to use ResourceRequest so that we can use ATP scripts in domain-server settings for persistent scripts.

Here is what you should test:

- HTTP scripts should still work, exactly as they did before
- ATP scripts should now work, even if you aren't connected to the Asset Server by the time the Agent wants to download the script
- file scripts should NOT work

**Comment by hifi-gustavo** [comment]
Build console output for commit: bf3324fc6bad5e0cbfac6a6a4803b8766a1ba485 available at: https://gist.github.com/3b36acd91e68979acb03e076df9a4af8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7624.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7624.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 76af3efe73eb29a8601d44329b10477d65d3b8b3 available at: https://gist.github.com/3b36acd91e68979acb03e076df9a4af8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7624.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7624.dmg

**Comment by OmegaHeron** [comment]
@birarda - What's a good test method for this?  I've deployed this on my stack test box and am a little unsure exactly how to test it.

**Comment by birarda** [comment]
@OmegaHeron recopying from above but I'll add some more explanation since I wasn't very clear.

Here is what you should test:

- HTTP scripts should still work, exactly as they did before
- ATP scripts should now work, even if you aren't connected to the Asset Server by the time the Agent wants to download the script
- file scripts should NOT work

These will be scripts you put in your domain-server settings in the persistent scripts table.

The "even if you aren't connected to the Asset Server by the time the Agent wants to download the script" will be obvious since the agent will print that it is waiting for an active socket for the Asset Server to download the script.

**Comment by OmegaHeron** [comment]
Thanks @birarda - that cleared it up so I didn't feel like I was doing a little bit of guessing.  Will get a test on this shortly.

**Comment by OmegaHeron** [comment]
Tested Linux running stack - Windows running Interface.
Added persistent scripts using ATP and HTTP references - works as expected.
Referenced scripts that **do not** exist via HTTP/ATP - errors logged, but, did not create crash or other issues.
Attempted to use a file:\ reference - fails as notes indicates it should.

QA Pass

**Pull request merged**
