### PR TITLE
WL 21666 - Window.domainChanged() isn't emitted if domain isn't running

### PR DESCRIPTION
**Pull request by cain-kilgore**
> The address in the Interface title bar changes but the signal isn't emitted.
> 
> function onDomainChanged(domain) {
> print("Domain changed: " + domain);
> }
> 
> Window.domainChanged.connect(onDomainChanged);
> 
> Task
> -------
> Make sure that if a domain is changed to a domain that isn't running that it still gives back a signal.
> Worklist [21666](https://worklist.net/21666)

## Test Plan
1. Install this PR, and enable Advanced/Developer Menus
2. Open the Console and run: `Window.domainChanged.connect(function(e) { print("Domain Changed: " + e)});`
2. Start connecting back and forth from different domains, confirm that a new console entry fires when you _disconnect_ from a domain as well as _connect_.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6132/app_12120_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6132/HighFidelity-Beta-PR12120-773461bd30dd9de6f05c8a14cd62f6cc028ff5d2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6132/HighFidelity-Beta-PR12120-773461bd30dd9de6f05c8a14cd62f6cc028ff5d2.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing complete. FAILED. When going to a domain that isn't running, it does not emit a new signal. It only emits a signal for domain that are currently running. Please observe and refer to the following video file:
https://drive.google.com/drive/u/1/folders/1u38Uz-fRrEfmnSptHF8rvcL28nD4URU6

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122  Re-tested. This passed.

**Pull request merged**
