### PR TITLE
Fix memory leak when reloading scripts

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Cannot rely in call to removeScriptEngine() in ScriptEngine::~ScriptEngine() because the QSet updated in removeScriptEngine() has a handle to the script engine, preventing it from being deleted.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10495/HighFidelity-Beta-PR13345-9338c21.apk

**Comment by ctrlaltdavid** [comment]
### Test Plan

The attached script soaks up about 100MB of RAM.

1) Verify that memory leaks each time the script is reloaded on a non-PR build.
- Run a recent build of Interface.
- Note Interface's memory usage reported by Windows' Task Manager.
- Run the attached script. The amount of memory Interface uses increases by ~100MB.
- Reload the script several times by pressing the "reload" icon beside its entry in the Running Scripts dialog. Each time it is reloaded, the amount of memory Interface uses increases by ~100MB.
- Reload all scripts by pressing the "Reload All" button in the Running Scripts dialog. The amount of memory Interface uses increases by ~100MB or more.
- Stop the attached script by pressing the "stop" icon beside its entry in teh Running Scripts dialog. The amount of memory Interface uses does not decrease by the expected ~100MB.

2) Check that memory does not leak in the PR build.
- Run the PR build of Interface.
- Note Interface's memory usage reported by Windows' Task Manager.
- Run the attached script. The amount of memory Interface uses increases by ~100MB.
- Reload the script several times by pressing the "reload" icon beside its entry in the Running Scripts dialog. Each time it is reloaded, the amount of memory Interface uses decrease then increases again, so that there isn't a net increase.
- Reload all scripts by pressing the "Reload All" button in the Running Scripts dialog. The amount of memory Interface uses decrease then increases again, so that there isn't a net increase.
- Stop the attached script by pressing the "stop" icon beside its entry in teh Running Scripts dialog. The amount of memory Interface uses decreases by the ~100MB.

[testMemoryLeak.zip](https://github.com/highfidelity/hifi/files/2086656/testMemoryLeak.zip)

https://highfidelity.manuscript.com/f/cases/9075

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10495/HighFidelity-Beta-PR13345-9338c21.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10495/HighFidelity-Beta-Interface-PR13345-9338c21.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10495/HighFidelity-Beta-PR13345-9338c21.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10495/HighFidelity-Beta-Interface-PR13345-9338c21.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

1. Reload script - Desktop/Mac PASS - Reloading the script multiple times caused the memory to go down and then back to the point it was at before, so it doesn't continuously leak memory.

2. Reload All - Desktop/Mac PASS - Reloading All would reduce the memory before it goes back up, no continuous leaks.

3. Remove script - Desktop FAIL / Mac PASS - Removing the script does not release the memory. Selecting the script again does release the memory before it goes back up, so it can't stack leak memory, but it doesn't release it. The Mac however did release the memory, so the failure is just with desktop.

-------------------------
Desktop Tests - 

STABLE:
Interface: 1.04GB
Script running: 1.18GB
Script reloaded: 1.32GB
Script reloaded x5: 1.87GB
Script stopped: 1.87GB

MASTER:
Interface: 1.03GB
Script running: 1.18GB
Script reloaded: 1.31GB
Script reloaded x5: 2.02GB
Script stopped: 2.02GB

PR13345:
Interface: .98GB
Script running: 1.12GB
Script reloaded: 1.12GB
Script reloaded x5: 1.13GB
Script stopped: 1.13GB

-----------------------------
Mac Tests - 

STABLE:
Interface: 677.4MB
Script running: 918.1MB
Script reloaded: 1.13GB
Script stopped: 1.13GB

MASTER:
Interface: 787.4MB
Script running: 1.17GB
Script reloaded: 1.32GB
Script stopped: 1.3 GB

PR13345:
Interface: 1.6GB (in Eschatology)
Script running: 2.02GB
Script reloaded: 2.02GB
Script stopped: 1.93GB

**Comment by ctrlaltdavid** [comment]
@conklin94122 I've submitted the following Manuscript case for script memory not always immediate being released when a script is stopped: https://highfidelity.manuscript.com/f/cases/15944/Script-memory-sometimes-not-immediately-released-when-script-stopped ... i.e., the "Windows desktop FAIL" case, above.

I've not managed to fix / work around this problem for Windows, however the current behaviour is, I think, benign: memory doesn't leak with each script stopped; it just sometimes isn't immediately released when a script is stopped. So, I think that this PR can be accepted by QA.

**Comment by conklin94122** [comment]
@ctrlaltdavid If I'm reading the situation right, this PR is blocked by the other bug, which means we can't verify this until that is fixed. I'd prefer to ere on the side of caution and and not deviate from our usual process here, but I'm open to discussing.

**Comment by ctrlaltdavid** [comment]
@conklin94122 This PR is not blocked by the other bug. There are two bugs: 1) memory continually increases each script reload; 2) the release of a script's memory is delayed if it was the last script loaded when it is terminated. This PR fixes bug 1. Bug 2 requires this PR's fix. ... So, bug 2 is blocked by this PR.

**Pull request merged**
