### PR TITLE
Fix particle bug by having lifetimes increase

### PR DESCRIPTION
**Pull request by Atlante45**
Fix particle bug causing a crash in debug mode

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1da68e02146056ce922d853db8a68c6ea7a86820 available at: https://gist.github.com/23d1b8010d59c6c007d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6102.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6102.dmg

**Comment by ZappoMan** [comment]
What's the repro case for the bug this fixes?

**Comment by Atlante45** [comment]
@ZappoMan Just seen that. Repro was (in debug mode) start an emiter then set the lifespan property to a smaller value than it is. Lifetime was not guaranteed to be smaller than lifespan anymore which was causing an assert to fail.

**Comment by ericrius1** [comment]
shnurp

**Comment by ericrius1** [comment]
bdurp

**Pull request merged**
