### PR TITLE
WL 21374: Allow lights/particles to be dragged by icon

### PR DESCRIPTION
**Pull request by amvmoody**
# Info
- Check with desktop and HMD.

# QA

## Setup
- Install HiFi from the latest build below from the CI server. 

## Steps - Single Person
1. Enter Create mode.
2. Create an a light and particle entity.
3. Select one of the entities and verify it can be dragged by the Icon.
4. Repeat step 3 but with the other entity and verify that is can be dragged.
5. Close out of create mode, then reopen it and repeat tests 3 and 4.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1438/HighFidelity-Beta-PR10912-d9706452ac4c781a87cc1cf261c1fa27ef2b0924.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1438/HighFidelity-Beta-PR10912-d9706452ac4c781a87cc1cf261c1fa27ef2b0924.exe

**Comment by Nex-Pro** [comment]
I will test this

**Comment by Nex-Pro** [comment]
testing this  Woot !

**Comment by Nex-Pro** [comment]
@amvmoody This seems to be a fail as it breaks the ability to select lights and particles by laser or mouse on the icon. Surely that isn't intended ?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1483/HighFidelity-Beta-PR10912-53f581c3d418a246809e019668361dc7a4601bc9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1483/HighFidelity-Beta-PR10912-53f581c3d418a246809e019668361dc7a4601bc9.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by Nex-Pro** [comment]
Will also re-check this

**Comment by YuppyPlays** [comment]
Testing complete:

Desktop:
Dragging light after selecting from list: **Pass**
Dragging Particles after selecting from list **Pass**
HMD:
Dragging light after selecting from list: **Pass**from list works as specified.**
Dragging Particles after selecting from list:  **Pass**

Notes: Without using the list first, it seems sometimes icons are a hit/miss with dragging, but when selected in list work as expected.

**Comment by Nex-Pro** [comment]
Will also test this.

**Comment by Nex-Pro** [comment]
### Fail.
 Unable to drag light or particle entities by their icons in HMD. Have to move pointer target off the icon to enable dragging. 
Can drag lights and particles by their icons in 2d mode.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1770/HighFidelity-Beta-PR10912-c56450b986e59270730b1de48df087fa5f35ce39.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1770/HighFidelity-Beta-PR10912-c56450b986e59270730b1de48df087fa5f35ce39.exe

**Comment by amvmoody** [comment]
build this please

**Comment by themelissabrown** [comment]
build this please

**Comment by themelissabrown** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1774/HighFidelity-Beta-PR10912-c56450b986e59270730b1de48df087fa5f35ce39.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1774/HighFidelity-Beta-PR10912-c56450b986e59270730b1de48df087fa5f35ce39.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1889/HighFidelity-Beta-PR10912-a4585b9400c6e057d08e8e65c57548e94e51e919.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1889/HighFidelity-Beta-PR10912-a4585b9400c6e057d08e8e65c57548e94e51e919.exe

**Comment by skytoad** [comment]
Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1896/HighFidelity-Beta-PR10912-7de164f1ab6804dedec413320415bcde8784da55.exe

**Comment by themelissabrown** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1898/HighFidelity-Beta-PR10912-7de164f1ab6804dedec413320415bcde8784da55.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1904/HighFidelity-Beta-PR10912-036a16c0b384f69cf5949645315f0e266b24a0fc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1904/HighFidelity-Beta-PR10912-036a16c0b384f69cf5949645315f0e266b24a0fc.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Desktop | HMD
-------- | -------- | --------
Enter Create mode. | Pass | Pass
Create an a light and particle entity. | Pass | Pass
Select one of the entities and verify it can be dragged by the Icon. | Pass | Pass
Repeat step 3 but with the other entity and verify that is can be dragged. | Pass | Pass
Close out of create mode, then reopen it and repeat tests 3 and 4. | Pass | Pass

I did notice a new bug during this, which isn't related to this PR so this is a **QA Pass** from me, however the Tablet's Create Tabs (Properties, List etc) are appearing white for me when in Tablet Mode. This includes opening the Tablet in Desktop Mode.

If this needs further testing let me know. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
