### PR TITLE
Case 19740: Improve startup times by pre-compiling shaders with splash screen (RC76.1)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/14419

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15573/HighFidelity-Beta-PR14514-832d621.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15573/HighFidelity-Beta-PR14514-832d621.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15573/HighFidelity-Beta-Interface-PR14514-832d621.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15573/HighFidelity-Beta-PR14514-832d621.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15573/HighFidelity-Beta-Interface-PR14514-832d621.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
