### PR TITLE
[DNM] CreateLite Object Manipulation prototype

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18824/HighFidelity-Beta-PR15423-12fe649.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18824/HighFidelity-Beta-Interface-PR15423-12fe649.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18824/HighFidelity-Beta-PR15423-12fe649.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18824/HighFidelity-Quest-Beta-PR15423-12fe649.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18824/HighFidelity-Beta-PR15423-12fe649.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18824/HighFidelity-Beta-Interface-PR15423-12fe649.exe

**Comment by huffman** [comment]
Closing due to DNM

**Pull request closed without merging**
