### PR TITLE
disable interstitial by default and fix crash

### PR DESCRIPTION
**Pull request by danteruiz**
This PR disables the interstitial by default. You enable it by setting a settings value. This PR also fixes a crash that Andrew encountered.

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
A.
1. run interface.
2. switch to new domain. The interstitial page should not come up. Also you should be able to use you keyboard short cuts and look around with the mouse.
3. check that physics is enabled for domain that you entered.

B.
1. open the console from interface and type `Settings.setValue("enableInterstitialMode", true);`
2. restart interface.
3. The interstitial screen should appear when switching domains.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12938/HighFidelity-Beta-PR13983-d76a2c1.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12938/HighFidelity-Beta-PR13983-d76a2c1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12938/HighFidelity-Beta-Interface-PR13983-d76a2c1.exe

**Comment by sethalves** [comment]
SafeLanding.cpp:178, GNU C Compiler 4 (gcc), Priority: Normal 
unused variable ‘isVisuallyReady’ [-Wunused-variable]

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12953/HighFidelity-Beta-PR13983-dca34c7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12953/HighFidelity-Beta-PR13983-dca34c7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12953/HighFidelity-Beta-Interface-PR13983-dca34c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12953/HighFidelity-Beta-PR13983-dca34c7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12953/HighFidelity-Beta-Interface-PR13983-dca34c7.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

**Comment by JeffClinton** [comment]
Test plan that was used:
https://highfidelity.testrail.net/index.php?/cases/view/25299

**Pull request merged**
