### PR TITLE
Hide mini tablet immediately upon near grabbing an entity

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13925/HighFidelity-Beta-PR14215-c9919ff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13925/HighFidelity-Beta-PR14215-c9919ff.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13925/HighFidelity-Beta-Interface-PR14215-c9919ff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13925/HighFidelity-Beta-PR14215-c9919ff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13925/HighFidelity-Beta-Interface-PR14215-c9919ff.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
