### PR TITLE
Update HiFi glyphs font file

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Has some new, soon to be used characters, but no other changes.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Recently restyled dialogs - like Running Scripts, Add Bookmark, and settings - should still look the same.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c3f374f02002d3d39ec17de8a131142af539e13 available at: https://gist.github.com/8b9af6b52f756689dacb<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7307.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7307.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - No difference seen between dialogs this PR and current production build.  QA Pass

**Comment by Nex-Pro** [comment]
Seems ok on WIN 10 64bit. Appearance appears to be identical.

**Pull request merged**
