### PR TITLE
hacked event experience

### PR DESCRIPTION
**Pull request by howard-stearns**
Hardcodes --url arg to zaru, and firstRun setting to false. Logs some values.

For use in internal evaluation of experience.
Note: I can no longer compile on mac, so it is not dev-tested.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/886/HighFidelity-Beta-PR10753-3bf200ef221cfa06e54e78e7a496be3f0ed2e449.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/897/HighFidelity-Beta-PR10753-3bf200ef221cfa06e54e78e7a496be3f0ed2e449.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/897/HighFidelity-Beta-PR10753-3bf200ef221cfa06e54e78e7a496be3f0ed2e449.dmg

**Comment by ZappoMan** [comment]
I believe this was just a demo... and the features have been added elsewhere

**Pull request closed without merging**
