### PR TITLE
updates for deprecating cmake policies and MacOS 10.14 build

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
These changes should not affect the build in anyway, except that our minimum supported OS X version becomes 10.9. That ensures that `libc++` is used as the default, working around an issue with Xcode 10 because clang will no longer will link to `libstdc++`.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13162/HighFidelity-Beta-PR14052-eb7b744.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13162/HighFidelity-Beta-PR14052-eb7b744.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13162/HighFidelity-Beta-Interface-PR14052-eb7b744.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13162/HighFidelity-Beta-PR14052-eb7b744.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13162/HighFidelity-Beta-Interface-PR14052-eb7b744.exe

**Comment by birarda** [comment]
#### Test Plan

Smoke test that the Mac build from this PR runs (as well as it does today on master).

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
@conklin94122  PASS

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13817/HighFidelity-Beta-PR14052-eb7b744.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13817/HighFidelity-Beta-Interface-PR14052-eb7b744.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13817/HighFidelity-Beta-PR14052-eb7b744.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13817/HighFidelity-Beta-Interface-PR14052-eb7b744.exe

**Pull request merged**
