### PR TITLE
Toggle going to 404 redirect domain (RC73.1)

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for MS#[18555](https://highfidelity.manuscript.com/f/cases/18555)

This PR defaults the behavior of getting redirected to the 404 domain to be disabled.  Enabling it would be by opening the `Developer > Console` after enabling the developer menu via `Settings > Developer Menu`, and setting the mode through `Settings.setValue("enableInterstitialMode", true);`

## TEST PLAN
- Launch Interface
- Interstitial mode should be disabled by default
- Try navigating to a domain that would warrant an error (i.e. via a timeout, with an unauthorized account, or protocol mismatch)
- Dialog should display with some text related to the error
- Enable `Settings > Developer Menu`
- Open `Developer > Console`
- Enter in `Settings.setValue("enableInterstitialMode", true);`
- Try navigating to a domain that would warrant an error (i.e. via a timeout, with an unauthorized account, or protocol mismatch)
- Arrive in the redirected serverless domain

Test case:
https://highfidelity.testrail.net/index.php?/cases/view/27807

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13127/HighFidelity-Beta-PR14032-7031fa2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13127/HighFidelity-Beta-PR14032-7031fa2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13127/HighFidelity-Beta-Interface-PR14032-7031fa2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13127/HighFidelity-Beta-PR14032-7031fa2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13127/HighFidelity-Beta-Interface-PR14032-7031fa2.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Redirected serverless domain is off by default. 

Turning on the redirected serverless domain with the command: Settings.setValue("enableInterstitialMode", true);

Using the command results in no redirect, even after restarting the interface. PR fails.

**Pull request closed without merging**
