### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4427/HighFidelity-Beta-PR11676-ff547f4e4f6e4781a08e239528389cac94fecd37.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4431/HighFidelity-Beta-PR11676-ff547f4e4f6e4781a08e239528389cac94fecd37.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4431/HighFidelity-Beta-PR11676-ff547f4e4f6e4781a08e239528389cac94fecd37.exe

**Pull request merged**
