### PR TITLE
Add back ambientURL listener in editor

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent

Support for ambient url was accidentally removed in #7353. This adds it back.

#### Testing

Ensure ambient url can be changed form the editor (edit.js).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 105b4e16a98db5945c558a776132f716349768b9 available at: https://gist.github.com/fe4ca4ca510cbecc0031<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7397.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7397.dmg

**Comment by judasshuffle** [comment]
This pr got flagged by kaspersky https://i.gyazo.com/e199a34e65768ae90c26e2502881439d.png

**Comment by ZappoMan** [comment]
Note to testers: This PR doesn't actually change the EXE... and so you can actually test it with the released interface...[ just run this version of edit.js...](https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/edit.js)

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 105b4e16a98db5945c558a776132f716349768b9 available at: https://gist.github.com/fe4ca4ca510cbecc0031<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7397.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7397.dmg

**Comment by judasshuffle** [comment]
using https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/edit.js
I cant get any entities to appear in the entities list in order to select a zone to test the ambient url
Using the default edit script I can in the pr build.
Also tried the script in the normal build with the same result.
(re kaspersky I know its not a virus lol, I Just thought I should mention that it happened.

**Comment by OmegaHeron** [comment]
Really can't test this as using reference links to script you can't load edit.js properly.  Looking at log it's indicating it can't load portions of what's needed.  A common thing with trying to test these types.  A small subset of errors thrown blocking this from working included below.

[03/21 11:07:30] [WARNING] Could not find tab for https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/gridControls.html

[03/21 11:07:30] [WARNING] Could not find tab for https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/gridControls.html 0 Mixed Content: The page at 'https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/gridControls.html' was loaded over HTTPS, but requested an insecure script 'qrc:///qtwebchannel/qwebchannel.js'. This request has been blocked; the content must 

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html 0 Mixed Content: The page at 'https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html' was loaded over HTTPS, but requested an insecure resource 'qrc:///qtwebchannel/qwebchannel.js'. This request has been blocked; the content must be served over HTTPS.

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/gridControls.html 0 [blocked] The page at 'https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/gridControls.html' was loaded over HTTPS, but ran insecure content from 'ws://localhost:51016/': this content should also be loaded over HTTPS.

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html 0 Mixed Content: The page at 'https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html' was loaded over HTTPS, but requested an insecure script 'qrc:///qtwebchannel/qwebchannel.js'. This request has been blocked; the content must be served over HTTPS.

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/eventBridgeLoader.js 38 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html 0 [blocked] The page at 'https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/entityList.html' was loaded over HTTPS, but ran insecure content from 'ws://localhost:51016/': this content should also be loaded over HTTPS.

[03/21 11:07:31] [DEBUG] Web Window JS message: https://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/html/eventBridgeLoader.js 38 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by imgntn** [comment]
@OmegaHeron @judasshuffle we need to leave the ```s``` off of the url for edit.js  -- the inclusion of a self served QT script (qrc://qrcwebchannel) prevents the whole thing from being served over https.  we need to either secure the QRC channel or secure the websockets channel after linking that qrc file without self-serving .... in the meantime just chop the s off the link http://rawgit.com/zzmp/hifi/fix/ambient-url-listener/examples/edit.js

**Comment by ZappoMan** [comment]
sorry - yeah... my bad... it's http: not https:

**Comment by OmegaHeron** [comment]
Tested Windows 7 - Am able to modify ambient URL and have it persist.  I used to have a link for a model that showed clearly if ambient is applying, but can't find link now.  With content I currently have it's kind of hard to tell if it's actually applying ambient, but, I do see it loading from log output.  QA Pass

**Pull request merged**
