### PR TITLE
Make type name hash static const

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6228/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6228/HighFidelity-Beta-PR12150-849cc2e07e571f618f02c9084ecfb45da8ecffe5.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6231/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6231/HighFidelity-Beta-PR12150-849cc2e07e571f618f02c9084ecfb45da8ecffe5.exe

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6234/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6234/HighFidelity-Beta-PR12150-849cc2e07e571f618f02c9084ecfb45da8ecffe5.exe

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6274/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6274/HighFidelity-Beta-PR12150-849cc2e07e571f618f02c9084ecfb45da8ecffe5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6274/HighFidelity-Beta-PR12150-849cc2e07e571f618f02c9084ecfb45da8ecffe5.dmg

**Comment by birarda** [comment]
#### Test Plan

Download Interface and Sandbox from this PR. From Interface, confirm you can connect to any domain on current master (dev domains). Also confirm you can connect to the Sandbox from this PR.

In every domain you connect to, confirm you have audio/avatar/entities as you expect.

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Stopped testing per instruction. Will resume when server has been updated.

**Comment by QAadahlin** [comment]
Resumed testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed testing. FAILED. 
For hifiqa-rc, we got the following error message: "Protocol version mismatch - Domain version: DISTRIBUTED-162"
For hifiqa-master and all dev- builds, we got the following error message: "Protocol version mismatch - Domain version: 7701"
Logs are attached. 
[hifi-log.txt](https://github.com/highfidelity/hifi/files/1640702/hifi-log.txt)

**Comment by birarda** [comment]
@QAadahlin the protocol version mismatch against hifiqa-rc is expected.
We'll need to get this PR up to date with master so that you can connect to master (7701) domains.

@Atlante45 is out today, I will bug him tomorrow to rebase and we can re-test.

**Comment by conklin94122** [comment]
Thanks much @birarda

**Comment by Atlante45** [comment]
@QAadahlin @conklin94122 @birarda Done.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6418/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6418/HighFidelity-Beta-PR12150-482ca3f03801326cbf06252522f604b17fd46aea.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6423/app_12150_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6423/HighFidelity-Beta-PR12150-482ca3f03801326cbf06252522f604b17fd46aea.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6423/HighFidelity-Beta-PR12150-482ca3f03801326cbf06252522f604b17fd46aea.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Completed Testing. PASSED. As expected per @birarda, hifiqa-rc had a protocol version mismatch. I was able to successfully go to hifiqa-master, Dev-welcome, Dev-avatarisland, and Dev-content.

**Pull request merged**
