### PR TITLE
Tablet Prototype #1

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5255/HighFidelity-Beta-PR11899-7b95cd091b03a0bbfa5dbeeee427b4576590dc53.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5259/HighFidelity-Beta-PR11899-7b95cd091b03a0bbfa5dbeeee427b4576590dc53.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5259/HighFidelity-Beta-PR11899-7b95cd091b03a0bbfa5dbeeee427b4576590dc53.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5278/HighFidelity-Beta-PR11899-9f3de8f3c2b3089102fc86aebf3599a13d69aac5.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5281/HighFidelity-Beta-PR11899-9f3de8f3c2b3089102fc86aebf3599a13d69aac5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5281/HighFidelity-Beta-PR11899-9f3de8f3c2b3089102fc86aebf3599a13d69aac5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5286/HighFidelity-Beta-PR11899-cbaf59d99ee15181ed84494b4c4f8fe1443a8a60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5286/HighFidelity-Beta-PR11899-cbaf59d99ee15181ed84494b4c4f8fe1443a8a60.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5296/HighFidelity-Beta-PR11899-b9f60aff2a5e8b8c21a6e490689cfe435139122d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5296/HighFidelity-Beta-PR11899-b9f60aff2a5e8b8c21a6e490689cfe435139122d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5557/HighFidelity-Beta-PR11899-2ff18a87afb7ca80413975fc27ad2deb8387b4de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5557/HighFidelity-Beta-PR11899-2ff18a87afb7ca80413975fc27ad2deb8387b4de.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5584/HighFidelity-Beta-PR11899-fba06a74aad09313292ab542ca02401713a7cee3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5584/HighFidelity-Beta-PR11899-fba06a74aad09313292ab542ca02401713a7cee3.dmg

**Pull request closed without merging**
