### PR TITLE
Selection Scripting Interface

### PR DESCRIPTION
**Pull request by zfox23**
Implements a "Selection Scripting Interface", which allows JS or C++ to group gameplay items (entities, avatars, overlays) into a "selection", which then may or may not be pushed to the Scene.

There are a few parts to this PR:
1. Remove the old method of drawing a bounding box around "highlighted" entities (which used entity properties to determine whether or not an entity should be highlighted)
2. Add a new Selection Scripting Interface: Allow JS and C++ to pass a list name and entity/avatar/overlay IDs to the interface, then act on them by pushing them to the Scene.
3. Add a new Job to the Main Scene rendering task to take what's in the `"contextOverlayHighlightList"` Render Selection and draw a bounding box around the render item.

Eventually, (blocked on 11160) we need to hook in the outline shader.

**Test Plan:**
1. Run Interface, then close it.
2. Open `Interface.json`. Add `"inspectionMode": true,` to that file.
3. Open Interface.
4. Open the scripting console. Paste this in: `Render.getConfig("RenderMainView.DrawSelectionBounds").enabled = true`
5. Spawn an entity from the Marketplace
6. Verify that hoving over the entity with your mouse or hand controller lasers causes a bounding box to appear around the entity. (the bounding box will be replaced by the outline shader _"soon"_)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2676/HighFidelity-Beta-PR11232-69364f2ecd7137d54c736e3125096b8618897e1e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2676/HighFidelity-Beta-PR11232-69364f2ecd7137d54c736e3125096b8618897e1e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2684/HighFidelity-Beta-PR11232-f01d9ddbe78fa79656ea8d74af0968a38507ee86.dmg

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2688/HighFidelity-Beta-PR11232-f01d9ddbe78fa79656ea8d74af0968a38507ee86.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2688/HighFidelity-Beta-PR11232-f01d9ddbe78fa79656ea8d74af0968a38507ee86.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2696/HighFidelity-Beta-PR11232-88c24c16d70d153affdf147d0df9350397b9eed1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2696/HighFidelity-Beta-PR11232-88c24c16d70d153affdf147d0df9350397b9eed1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2709/HighFidelity-Beta-PR11232-52ef0f20376dd8cbc313ae5c8eebe0d23e16b922.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2709/HighFidelity-Beta-PR11232-52ef0f20376dd8cbc313ae5c8eebe0d23e16b922.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2730/HighFidelity-Beta-PR11232-d370eeea2fc96f7adfd17600e68647179b92edcb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2730/HighFidelity-Beta-PR11232-d370eeea2fc96f7adfd17600e68647179b92edcb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2738/HighFidelity-Beta-PR11232-baad5f195ee47a9cf65f22d6eef15576382f8b81.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2738/HighFidelity-Beta-PR11232-baad5f195ee47a9cf65f22d6eef15576382f8b81.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2752/HighFidelity-Beta-PR11232-3c7fadb1cee8f6e3cf11fec427622720f8147118.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2752/HighFidelity-Beta-PR11232-3c7fadb1cee8f6e3cf11fec427622720f8147118.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2851/HighFidelity-Beta-PR11232-0cdef28cfdfe47a8fa9cafac8d44a676be2e82cb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2851/HighFidelity-Beta-PR11232-0cdef28cfdfe47a8fa9cafac8d44a676be2e82cb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2917/HighFidelity-Beta-PR11232-fdcc149c34f78231f076bd7d0a7399a9402e9afc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2917/HighFidelity-Beta-PR11232-fdcc149c34f78231f076bd7d0a7399a9402e9afc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2923/HighFidelity-Beta-PR11232-3f0d44990ada9173ca87b62da0dfa7bcc4361272.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2923/HighFidelity-Beta-PR11232-3f0d44990ada9173ca87b62da0dfa7bcc4361272.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2934/HighFidelity-Beta-PR11232-913618ded5746fc6cbca10df5cc8c41e381112d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2934/HighFidelity-Beta-PR11232-913618ded5746fc6cbca10df5cc8c41e381112d4.exe

**Comment by zfox23** [comment]
[Selection Scripting Interface + Basic Outline Hook](https://trello.com/c/nrzJzpXb/366-selection-scripting-interface-basic-outline-hook)

**Comment by zfox23** [comment]
[Selection Scripting Interface + Basic Outline Hook](https://trello.com/c/nrzJzpXb/366-selection-scripting-interface-basic-outline-hook)

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
## PASS

**Got red and white bounding box for desktop and HMD. See images.**

hifi-snap-by-piper-peppercorn-on-2017-08-31_16-42-55
hifi-snap-by-piper-peppercorn-on-2017-08-31_16-44-52

**Pull request merged**
