### PR TITLE
Fade dissolve effect  JUST AVATARS

### PR DESCRIPTION
**Pull request by Zvork**
This PR extends the dissolve fade entity appear events introduced in PR #10964 to voxel, primitive shape and polyline entities.

### Limitations
At this time, models, voxels, primitives and polylines will potentially have a fade effect applied to them when built with the Create menu. The code where the fade event is hooked on doesn't discriminate between entity creation due to domain loading and entity creation due to user interaction with the Create menu, for instance.

# TEST PLAN 01
1. Check that each model based entity that appears in the world has a correct dissolve fade event applied to it, especially with a scale matching the dissolve effect of model entities.
2. When switching back and forth between to worlds, the model based entity should have a fade in event 3. Check that each voxel based entity that appears in the world has a correct dissolve fade event applied to it, especially with a scale matching the dissolve effect of model entities.
4. When switching back and forth between to worlds, the voxel based entity should have a fade in event triggered each time (no fade out is expected).
5. Check that each primitive based entity (box, sphere, etc...) that appears in the world has a correct dissolve fade event applied to it, especially with a scale matching the dissolve effect of model entities.
6. When switching back and forth between to worlds, the primitive based entity should have a fade in event triggered each time (no fade out is expected).
7. Primitives of same color should fade independently (this may be difficult to visualize but can happen based on network load)
8. Check that each polyline based entity that appears in the world has a correct dissolve fade event applied to it, especially with a scale matching the dissolve effect of model entities.
9. When switching back and forth between to worlds, the polyline based entity should have a fade in event triggered each time (no fade out is expected).
10. Check that each avatar that appears in a location has a correct fade event applied to it, different from the model / voxel / shape / polyline based entities.
11. Check that each avatar (except your avatar) that leaves a location has a correct fade event applied to it that is the inverse of the "avatar appear" event.

This PR should be tested on various GPU (Intel, AMD and NVidia) platforms.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1845/HighFidelity-Beta-PR11021-b08e2598c2ad61dcda9e5bcd0b0e90e0f8620cf7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1845/HighFidelity-Beta-PR11021-b08e2598c2ad61dcda9e5bcd0b0e90e0f8620cf7.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1846/HighFidelity-Beta-PR11021-22acf1aeaf2e43b768c1b8bd0be97bf14266702d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1846/HighFidelity-Beta-PR11021-22acf1aeaf2e43b768c1b8bd0be97bf14266702d.dmg

**Comment by Nex-Pro** [comment]
Checking this

**Comment by cain-kilgore** [comment]
Testing w/GTX 1050ti.

**Comment by Nex-Pro** [comment]
### Testing platform: Intel workstation.
### OS: Win10 pro 64
### CPU: i7 4.0 ghz
### RAM: 16gb
### GPU: Nvidia GTX1070 8gb VRam + GTX1080 + GTX970 + RADEON
### HMD: Htc Vive.

**Tester Piper.Peppercorn**

### TEST PLAN

Check that each model based entity that appears in the world has a correct dissolve fade event applied to it, 
especially with a scale matching the dissolve effect of model entities. **Not sure what is meant by correct fade effect but stuff has an effect on it.**

When switching back and forth between to worlds, the model based entity should have a fade in event **DOES fade but looks terrible if there is a lot of content**

Check that each voxel based entity that appears in the world has a correct dissolve fade event applied to it, 
especially with a scale matching the dissolve effect of model entities. **This makes using voxel paint impractical. Voxel paint demands instant visual feedback that is broken by this PR. Users cannot see what they have painted until after the stroke is completed and the pseudo-random fade effect has completed.**

When switching back and forth between to worlds, the voxel based entity should have a fade in event triggered each time (no fade out is expected). **PASS**

Check that each primitive based entity (box, sphere, etc...) that appears in the world has a correct dissolve fade event applied to it, 
especially with a scale matching the dissolve effect of model entities.**NEEDS clarification**

When switching back and forth between two worlds, 
the primitive based entity should have a fade in event triggered each time (no fade out is expected).**PASS**

Primitives of same color should fade independently (this may be difficult to visualize but can happen based on network load) **Tried this at localost with a bunch of red cuboids of vastly different scale but they all looked to be doing the same thing at the same time**

Check that each polyline based entity that appears in the world has a correct dissolve fade event applied to it, especially with a scale matching the dissolve effect of model entities. **FAIL breaks finger paint for same reason as voxel-paint**

When switching back and forth between two worlds, 
the polyline based entity should have a fade in event triggered each time (no fade out is expected).**PASS**

Check that each avatar that appears in a location has a correct fade event applied to it, 
different from the model / voxel / shape / polyline based entities. **SUCCESS kinda cool and is double sided**

Check that each avatar (except your avatar) that leaves a location has a correct fade event applied to it that is the inverse of the "avatar appear" event. **SUCCESS**

This PR should be tested on various GPU (Intel, AMD and NVidia) platforms. Testd on NVidia gtx1070.

This breaks shortbow as the enemies become invisible or never appear.
Polyline drawing is impractical with this.
Polyvox is also effectively unusable.
Avatar transition is pretty cool.
This is breaking fragment shaders. Checked on GTX1080 and GTX1070 and GTX970
Also crashes each time spectator cam is started. ( turn camera on ) Works fine in Master.

**Comment by Zvork** [comment]
> Primitives of same color should fade independently (this may be difficult to visualize but can happen based on network load) Tried this at localost with a bunch of red cuboids of vastly different scale but they all looked to be doing the same thing at the same time

@Nex-Pro  It doesn't really depend on the size of the primitives unfortunately. I suppose the simplest way to test this is too "rapidly" create multiple primitives from the Create menu and check that they all fade in sequence independently.

**Comment by Nex-Pro** [comment]
Additionally any time an entity that is both moving and fading in seems to show that in some way the effect is world based and not local to the entity.

**Comment by Zvork** [comment]
> Check that each primitive based entity (box, sphere, etc...) that appears in the world has a correct dissolve fade event applied to it,
especially with a scale matching the dissolve effect of model entities.NEEDS clarification

@Nex-Pro The size of the fade noise should be consistent whatever the entity type. Hope this is clearer.

**Comment by Zvork** [comment]
> Additionally any time an entity that is both moving and fading in seems to show that in some way the effect is world based and not local to the entity.

@Nex-Pro That shouldn't be the case. Is there a place / object where this is really apparent?

**Comment by Nex-Pro** [comment]
Play shortbow in HMD at dev-welcome @Zvork

**Comment by Nex-Pro** [comment]
observe the enemies

**Comment by Zvork** [comment]
@Nex-Pro What do you mean by "it is breaking fragment shaders"?

**Comment by Nex-Pro** [comment]
It breaks fragment shaders

**Comment by Nex-Pro** [comment]
in the market there are some shaders available
They don't work correctly with this build. Checked this on two geographically separate PCs.

**Comment by Nex-Pro** [comment]
They either don't display at all or interact in a stange way with other entities both mesh and primitives

**Comment by Nex-Pro** [comment]
@Zvork Try the second of the water shaders available in the market.

**Comment by Nex-Pro** [comment]
here's a link to the shader http://mpassets.highfidelity.com/9be979b6-5a44-4aba-84ab-462b68617fc6-v1/Water.fs

**Comment by Nex-Pro** [comment]
#line 2

// Modified from: https://www.shadertoy.com/view/MdlXz8

// Found this on GLSL sandbox. I really liked it, changed a few things and made it tileable.
// :)
// by David Hoskins.


// Water turbulence effect by joltz0r 2013-07-04, improved 2013-07-07


// Redefine below to see the tiling...
//#define SHOW_TILING

#define TAU 6.28318530718
#define MAX_ITER 5

float getProceduralColors(out vec3 diffuse, out vec3 specular, out float shininess) {

	// Defaults
	diffuse = _color.rgb;
	specular = vec3(1.0, 1.0, 1.0);
	shininess = DEFAULT_SHININESS;

	// Map to ShaderToy inputs
	vec2 fragCoord = _position.xy * iWorldScale.xy;
	vec4 fragColor = vec4(1.0, 1.0, 1.0, 1.0);









	float time = iGlobalTime * .5+23.0;
    // uv should be the 0-1 uv of texture...
	vec2 uv = fragCoord.xy / iResolution.xy;

#ifdef SHOW_TILING
	vec2 p = mod(uv*TAU*2.0, TAU)-250.0;
#else
    vec2 p = mod(uv*TAU, TAU)-250.0;
#endif
	vec2 i = vec2(p);
	float c = 1.0;
	float inten = .005;

	for (int n = 0; n < MAX_ITER; n++)
	{
		float t = time * (1.0 - (3.5 / float(n+1)));
		i = p + vec2(cos(t - i.x) + sin(t + i.y), sin(t - i.y) + cos(t + i.x));
		c += 1.0/length(vec2(p.x / (sin(i.x+t)/inten),p.y / (cos(i.y+t)/inten)));
	}
	c /= float(MAX_ITER);
	c = 1.17-pow(c, 1.4);
	vec3 colour = vec3(pow(abs(c), 8.0));
    colour = clamp(colour + vec3(0.0, 0.35, 0.5), 0.0, 1.0);


	#ifdef SHOW_TILING
	// Flash tile borders...
	vec2 pixel = 2.0 / iResolution.xy;
	uv *= 2.0;

	float f = floor(mod(iGlobalTime*.5, 2.0)); 	// Flash value.
	vec2 first = step(pixel, uv) * f;		   	// Rule out first screen pixels and flash.
	uv  = step(fract(uv), pixel);				// Add one line of pixels per tile.
	colour = mix(colour, vec3(1.0, 1.0, 0.0), (uv.x + uv.y) * first.x * first.y); // Yellow line

	#endif
	fragColor = vec4(colour, 1.0);







	// Map back to HiFi inputs
	diffuse = fragColor.rgb;
	return 1.0;

}

**Comment by Zvork** [comment]
Mmh... ok. I wasn't aware you could import your own custom shaders. I'll take a look.

**Comment by Nex-Pro** [comment]
@Zvork That's what we are here for.

**Comment by Zvork** [comment]
> Play shortbow in HMD at dev-welcome

@Nex-Pro Arg. Unfortunately I don't have and HMD. I also don't understand how to plat shortbow with just keyboard and mouse, it that is at all possible. I can't even figure out how to start the game.

**Comment by Zvork** [comment]
> Also crashes each time spectator cam is started.

@Nex-Pro It seems the spectator cam also needs and HMD. Am I right? If this is the case then that is bit troublesome as I won't be able to debug this myself.

**Comment by Nex-Pro** [comment]
@Zvork The spectator cam uses a shader for the viewfinder AFAIK.

You can't play shortbow without HMD but you can observe. I can trigger it for you or one of the devs at dev-welcome can get it working.

You also need HMD to use polyvox. And trust me this has made that basically unusable.

**Comment by Nex-Pro** [comment]
@Zvork Sorry about that. I had no controllers had to re-calibrate and reboot. Also could not hear what you were saying. But nice to meet you.

**Comment by Zvork** [comment]
@Nex-Pro Thanks for the help on the shortbow!

**Comment by AndrewMeadows** [comment]
@Zvork, it would be nice to get the `Transition` stuff merged without actually breaking anything.  Perhaps progress toward merge could be achieved by temporarily disabling `Transitions` for all `EntityItems` but leaving it in for `Avatars`.  We could then fix the `EntityItem` related transitions in future PR's.  I'm just thinking out loud here, dunno how easy it would be to transition one and not the other.  Meanwhile, breaking the shader scripts on the market place is probably a blocker.

**Comment by Zvork** [comment]
@AndrewMeadows It should be fairly easy to do what you describe. Each entity class that supports fade has it's own small code to decide when to launch it. Yep, not very easy to maintain but since each class manages its render and it's "ready to render" state... Anyway, in RenderableModelEntity, RenderableVoxelEntity, RenderableShapeEntity and RenderablePolyLineEntitiy we can comment out (or remove) the one or two places where a call to addTransitionToItem is made. That would prevent fade on these types. Unfortunately, I'm on vacation starting... now and for a week so I probably won't be able to do this myself.

But be aware that this PR, even with fade disabled will possibly still break the custom shaders on shape entities. I suspect that it is the custom shader pipeline system introduced by @samcake 's #10950 PR and applied to these shape entities that breaks them although I am not totally sure. So to merge safely, that would mean reverting back the RenderableShapeEntity class to that #10950 PR state or even the master branch state.

**Comment by Zvork** [comment]
Deactivated fading on all entity items but kept it on Avatars.

# TEST PLAN
1. Check that each avatar that appears in a location has a correct fade event applied to it, different from the model / voxel / shape / polyline based entities.
2. Check that each avatar (except your avatar) that leaves a location has a correct fade event applied to it that is the inverse of the "avatar appear" event.
3. All other entity items should have no fade effect whatsoever in any circumstances especially when:
  a. User is painting with voxels,
  b. User is painting with paint poly lines
  c. Items are instantiated dynamically such as in the "Shortbow" game in the Welcome domain.
4. All custom shaders should work properly.
5. Using the spectator camera script should work properly.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2138/HighFidelity-Beta-PR11021-5f1d45d4decfe98cae2a40f5f9df06731f2d2ca7.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2148/HighFidelity-Beta-PR11021-e85bb6fd0841f3fe4185b196ca1498f4594f461d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2148/HighFidelity-Beta-PR11021-e85bb6fd0841f3fe4185b196ca1498f4594f461d.exe

**Comment by Zvork** [comment]
Tested locally with new build settings on Windows : Qt 5.9.1 and Visual Studio 2017.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2176/HighFidelity-Beta-PR11021-7322fdeb7951104ea5ae9b7ef76f966e0fad2aaf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2176/HighFidelity-Beta-PR11021-7322fdeb7951104ea5ae9b7ef76f966e0fad2aaf.exe

**Comment by tapalisa** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2338/HighFidelity-Beta-PR11021-7322fdeb7951104ea5ae9b7ef76f966e0fad2aaf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2338/HighFidelity-Beta-PR11021-7322fdeb7951104ea5ae9b7ef76f966e0fad2aaf.exe

**Comment by conklin94122** [comment]
**# TESTERS: Please only execute the last test plan (currently 03) in this PR.**

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
### PASS

Check that each avatar that appears in a location has a correct fade event applied to it, different from the model / voxel / shape / polyline based entities. **Will assume that the effect seen is correct**

Check that each avatar (except your avatar) that leaves a location has a correct fade event applied to it that is the inverse of the "avatar appear" event. **PASS**

All other entity items should have no fade effect whatsoever in any circumstances especially when:
a. User is painting with voxels,**PASS**
b. User is painting with paint poly lines**PASS**
c. Items are instantiated dynamically such as in the "Shortbow" game in the Welcome domain.**PASS**
All custom shaders should work properly.**PASS** includes shader skyboxes
Using the spectator camera script should work properly.**PASS**

**Pull request merged**
