### PR TITLE
Show Connection instructions in Send Money when 0 connections

### PR DESCRIPTION
**Pull request by zfox23**
If you don't have any Connections, and you attempt to Send Money to a Connection, you'll now see instructions for how to make a Connection.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Log into a HiFi account that doesn't have any connections (or forget all of the ones you currently have via the PAL)
- Authenticate your Wallet

### Plan
1. In Desktop mode, open the Wallet. Click the Send Money tab. Click "Connection".
    - Verify that you see instructions related to Desktop mode OR HMD mode (depending on which mode you're in) about how to make a Connection
2. Close the Wallet. Make a connection with another user. Open the Wallet. Click the Send Money tab. Click "Connection".
    - Verify that you see a "filter bar" at the top of the window. Verify that you are able to Choose the Connection you just made.
3. Forget that connection via the PAL, then repeat steps 1 and 2 in HMD mode.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7775/app_12572_PR.apk

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7787/app_12572_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7787/HighFidelity-Beta-PR12572-48aa862c16799a054d5c8c3bd1ddb026990006e4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7787/HighFidelity-Beta-PR12572-48aa862c16799a054d5c8c3bd1ddb026990006e4.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
