### PR TITLE
DEV-62: Add getHomeLocationAddress to bookmark API

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.atlassian.net/browse/DEV-62

Adds this so portals or other scripts can set/get the Home location

### CODE REVIEW

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19691/HighFidelity-Beta-PR15646-344410e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19691/HighFidelity-Beta-Interface-PR15646-344410e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19691/HighFidelity-Beta-PR15646-344410e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19691/HighFidelity-Beta-Interface-PR15646-344410e.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19691/HighFidelity-Beta-PR15646-344410e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19691/HighFidelity-Quest-Beta-PR15646-344410e.apk)

**Pull request merged**
