### PR TITLE
Remove LipsUpperOpen and LipsLowerOpen, the last of the legacy blendshapes

### PR DESCRIPTION
**Pull request by hyperlogic**
These blendshapes are not present in ARKit and are not used by any of our procedural face animations (talking, blinking etc).  This change should have been part of #16400 but was accidentally left out.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22294/HighFidelity-Beta-PR16445-101ec9d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22294/HighFidelity-Beta-Interface-PR16445-101ec9d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22294/HighFidelity-Beta-PR16445-101ec9d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22294/HighFidelity-Quest-Beta-PR16445-101ec9d.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22297/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22297/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22305/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22305/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22305/HighFidelity-Beta-PR16445-821a466.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22305/HighFidelity-Beta-Interface-PR16445-821a466.exe

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22319/HighFidelity-Beta-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22319/HighFidelity-Beta-Interface-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22319/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22319/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22324/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22324/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22324/HighFidelity-Beta-PR16445-821a466.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22324/HighFidelity-Beta-Interface-PR16445-821a466.exe

**Comment by hyperlogic** [comment]
for some reason macos failed to build.

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22339/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22339/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22339/HighFidelity-Beta-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22339/HighFidelity-Beta-Interface-PR16445-821a466.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22342/HighFidelity-Beta-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22342/HighFidelity-Beta-Interface-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22342/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22342/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22357/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22357/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22357/HighFidelity-Beta-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22357/HighFidelity-Beta-Interface-PR16445-821a466.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22361/HighFidelity-Beta-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22361/HighFidelity-Beta-Interface-PR16445-821a466.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22361/HighFidelity-Beta-PR16445-821a466.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22361/HighFidelity-Beta-Interface-PR16445-821a466.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22361/HighFidelity-Beta-PR16445-821a466.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22361/HighFidelity-Quest-Beta-PR16445-821a466.apk)

**Pull request merged**
