### PR TITLE
Earthquakes Live 1.0: Visualization of USGS Earthquake Data for Past Day

### PR DESCRIPTION
**Pull request by imgntn**
This PR is an example of using the USGS live feed to populate a scale model of the earth with data points. It updates every five minutes, which is as frequently as the data. The color indicates the strength of the quake.  I adapt the tinycolor library which is a useful library for color space conversions.  Plan to add more features, etc. but feedback is welcome.  To test: https://rawgit.com/imgntn/hifi/earthquakes_live/examples/data_visualization/earthquakes_live.js 
capture

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a5b9bd523391320a08aa203091c24b74779c2fa available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7fc3d0f34edebde14f630bfea9c608fa3e382142 available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d518def97477cd11e45fecdc842e47c220b68f39 available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 945b5bd00f5c9d0a1caf2c5bf90347ac125411fe available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a899fe0e1b3eacca35d79c2cd0b4ce889d0dae5f available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ade32cbf6137fada8eb5661c846779ccd88bc015 available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30b32765b915f7e4f5947883fdfc601e4bae9f86 available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by Atlante45** [comment]
Wow, nice job man, looks good!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7859241ad31d1ad467eb22e1b4512f6178f57e10 available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 378b71d7011a097262f5f31764981c99551606fa available at: https://gist.github.com/2a0f4bb07c00b0bbd421<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6571.dmg

**Pull request merged**
