### PR TITLE
add version code for increasing android appVersionCode

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
This is the RC70/master version of #13503, which we discovered was needed when testing new stable build flow.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11061/HighFidelity-Beta-PR13522-91db8fa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11061/HighFidelity-Beta-PR13522-91db8fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11061/HighFidelity-Beta-Interface-PR13522-91db8fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11061/HighFidelity-Beta-PR13522-91db8fa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11061/HighFidelity-Beta-Interface-PR13522-91db8fa.exe

**Comment by birarda** [comment]
This was tested prior to build process change. Does not need QA.

**Pull request merged**
