### PR TITLE
Fix overlay toggling

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Test toggling via script call.
- Display some overlays, e.g., stats (press "/" key), script log (Developer > Script Log).
- Run the attached script, testScriptCall.js.
- After 2s, the overlays should disappear.
- After 4s, the overlays should reappear.

2) Test toggling via controller mapping.
- Run the attached script, testControllerMapping.
- In HMD mode, press and release your right controller trigger several times.
- The overlays should toggle between displaying and being hidden with each trigger press.

[21843.zip](https://github.com/highfidelity/hifi/files/1910023/21843.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8803/app_12893_PR_df31d20430d9eb5d445a178e2fe5289de8a6c8ef.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8803/HighFidelity-Beta-PR12893-df31d20430d9eb5d445a178e2fe5289de8a6c8ef.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8803/HighFidelity-Beta-Interface-PR12893-df31d20430d9eb5d445a178e2fe5289de8a6c8ef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8803/HighFidelity-Beta-PR12893-df31d20430d9eb5d445a178e2fe5289de8a6c8ef.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8803/HighFidelity-Beta-Interface-PR12893-df31d20430d9eb5d445a178e2fe5289de8a6c8ef.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Overlays disappear and reappear as expected.

**Pull request merged**
