### PR TITLE
Build 56.1 Hotfix texture referencing in fst files

### PR DESCRIPTION
**Pull request by cozza13**
Build 56.1 Hotfix texture referencing in fst files

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4052/HighFidelity-Beta-PR11572-6a90beb4aac31e2b397f6de1aa8db828eaec7505.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4052/HighFidelity-Beta-PR11572-6a90beb4aac31e2b397f6de1aa8db828eaec7505.exe

**Comment by Nex-Pro** [comment]
T E S T I N G

**Comment by conklin94122** [comment]
QA PASSED

**Pull request merged**
