### PR TITLE
Beta Release Candidate 6 - including up to Development Release 4759

### PR DESCRIPTION
**Pull request by ZappoMan**
- tweaks to LOD
- fix to audio & avatar mixers with changing system clocks
- fix to crash in network sending
- fix to reset scripting state when changing domains
- fix to log spam related to GL version in QML
- added MyAvatar onLoadComplete callback for scripts
- render performance improvement
- memory leak fixes
- fix rendering text3dt overlays with transparent text
- fix to gcc5.3.1/Ubuntu 16.04 builds
- fix to crashes in reload cache content
- fix to application name in installer
- fix to lag in avatar attachments
- fix to initial placement of windows and tool bars in the HMD
- fix to open file for OSX
- performance and memory improvements in rendering the star skybox
- fix to crash in entity server with entities moving off the domain
- performance improvement to texture loading
- fix crash in texture loading and texture cache
- generate normal maps from bump maps

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cbb76013c4d41c10dfae2b8f2647adcfd3eaf4bb available at: https://gist.github.com/e2ef51d40bf1b47a772769a1c949b0e1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7713.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7713.dmg

**Comment by OmegaHeron** [comment]
This turns up another issue with GCC 5.3 and I hadn't seen this in my previous successful compiles so it must be some PR I hadn't yet attempted to compile with GCC 5.3.1

error: converting to ‘bool’ from ‘std::nullptr_t’

First instance of this is in libraries/gpu/src/gpu/GLBackendShader.cpp where you see starting at line 37;
`    // Create the shader object`
`    GLuint glshader = glCreateShader(shaderDomain);`
`    if (!glshader) {`
`        qCDebug(gpulogging) << "GLShader::compileShader - failed to create the gl shader object";`
`        return nullptr;`
`    }`

Apparently it no longer allows returning a nullptr but, instead, wants you to return false.  Numerous other programs have had to adopt to this behavior.  Where I was comfortable adding namespace to isnan instances - I'm not sure this is as simple as replacing nullptr with false though, honestly, it seems it should be.  A nullptr is a "pointer" to 0 and a false is 0 if this still works as I think it does.

**Comment by kevinmthomas-carpool** [comment]
Thank @OmegaHeron I am testing as well on a Windows 10 Laptop. I assume you are on 15.10?

**Comment by OmegaHeron** [comment]
No Kevin - I'm on 16.04 as 15.10 is nearing its rapid end of life with release of long term support 16.04.  16.04 offers us the first chance to have a linux basis that's close to HiFi's cutting edge choices.  That's why I'm spending time to be sure it works well with it.

**Comment by kevinmthomas-carpool** [comment]
@OmegaHeron great news!  That will be a great test and we can compare notes.

**Comment by OmegaHeron** [comment]
Yeah - I'm just testing compiles right now.  It's going to work fine with 15.10 and I'm not saying this needs to be addressed now.  I can sort out a future PR to correct that one function for compat with GCC5.3/Ubuntu 16.04.

**Comment by OmegaHeron** [comment]
Good news is - looking at the diff - it seems most cases of return nulptr have already been changed to false in that file.  Seems it will likely be safe to update it as well and that allows make all to work properly.

**Comment by kevinmthomas-carpool** [comment]
That is good news and will make this smoother for the upgrade.

**Comment by OmegaHeron** [comment]
Actually - it's failing on Ubuntu 15.10 as well.  Going to need that fixed sooner than later or several domans running on Linux will be unhappy.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7713
**Testing Architecture:** 64-bit PC Laptop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience, forum
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience |forum  
----------------------------------|----------|---------|------------|-----
Render Rate:                      |49.90     |51.91    |49.35       |48.93    
Present Rate:                     |59.87     |59.85    |59.85       |59.85   
Simrate:                          |49.85     |50.85    |49.80       |47.88    
Render Stats Num Buffers:         |3304      |2669     |2026        |3834   
Render Stats gpu::Buffer Memory:  |35.7Mb    |62.8Mb   |36.1Mb      |58.1Mb        
Render Stats Num Textures:        |332       |310      |57          |269    
Render Stats gpu::Texture Memory: |1154.4Mb  |912.6Mb  |357.7Mb     |857.8Mb         
Render Stats Triangles:           |56k       |141k     |213k        |556k    
Render Stats Drawcalls:           |26        |129      |68          |440   
Render Stats Items:               |24        |202      |106         |536
GPU-Z Memory Size                 |2048Mb    |2048Mb   |2048Mb      |2048Mb
GPU-Z Initial Memory		  |280Mb     |280Mb    |280Mb       |280Mb
GPU-Z Memory Used		  |1739Mb    |1559Mb   |1216Mb      |1861Mb
GPU-Z Memory Load		  |51%       |62%      |49%         |82%

**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**Additional Test Results Requested:** (none)
**Successful Logout/Crash:** Successful test.

**Comment by OmegaHeron** [comment]
Testing on Windows 7 for Interface reveals no obvious problems.  Stack is not going to compile on Ubuntu Linux 15.10 or 16.04 (or any other using similar versions of GCC 5.2/5.3 respectively) until issue with returning nullptr vs false is addressed.  Apparently HiFi's buildbox is still on 14.04 using an older GCC that allows nullptr as a return.

**Comment by OmegaHeron** [comment]
@samcake - I **think** this came with a PR of yours - but I'm not at a place where I can properly look at it, but;

libraries/gpu/src/gpu/GLBackendShader.cpp line 37;
// Create the shader object
GLuint glshader = glCreateShader(shaderDomain);
if (!glshader) {
qCDebug(gpulogging) << "GLShader::compileShader - failed to create the gl shader object";
return nullptr;
}

This is failing to compile on Linux with GCC 5.2 or GCC 5.3 - I see other cases were changed to return false instead of nullptr - any chance of getting this updated so my jenkins build box will quit screaming at me while I'm driving?  And so there won't be pitchforks and flames in alpha group when the linux domain runners can't compile this....

**Comment by ZappoMan** [comment]
We're going to close this, and get 2 small fixes in...

**Pull request closed without merging**
