### PR TITLE
Master qml bugfixes

### PR DESCRIPTION
**Pull request by vladest**
Test plan:
- make sure there is no QML errors/warnings in the app logs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 990e1379e3cc66e04e36c2f372b57713c65fb2a4 available at: https://gist.github.com/58c7ce47a1572db3f4791a463d442a7f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10103-990e137.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10103-990e137.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa487faad17d10b222e84b83011ffe43390f0088 available at: https://gist.github.com/58c7ce47a1572db3f4791a463d442a7f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10103-aa487fa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10103-aa487fa.dmg

**Comment by anshuman64** [comment]
Few more errors on Windows in Desktop mode clicking around in the tablet:

[hifi-log.txt](https://github.com/highfidelity/hifi/files/893842/hifi-log.txt)
[04/04 09:35:02] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR10103/resources//qml/hifi/tablet/WindowRoot.qml:51: TypeError: Cannot call method 'hasOwnProperty' of null
[04/04 09:37:25] [WARNING] [qml] Warning: StackView: cannot transition an item that is anchored!
[04/04 09:37:58] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR10103/resources//qml/hifi/Card.qml:246:5: QML DropShadow: Cannot anchor to an item that isn't a parent or sibling.
[04/04 09:38:46] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR10103/resources//qml/controls-uit/ComboBox.qml:219: TypeError: Property 'get' of object  is not a function
[04/04 09:39:00] [WARNING] [default] QQmlExpression: Expression file:///C:/Program Files/High Fidelity - PR10103/resources//qml/hifi/Pal.qml:897:23 depends on non-NOTIFYable properties:
[04/04 09:39:00] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR10103/resources//qml/hifi/ComboDialog.qml:50:19: Unable to assign [undefined] to QString
[04/04 09:39:05] [WARNING] [default] file:///C:/Program Files/High Fidelity - PR10103/resources//qml/hifi/Pal.qml:27: TypeError: Cannot read property of null

**Comment by sethalves** [comment]
I'm going to Merge this one and make a new task for these other errors.

**Comment by howard-stearns** [comment]
BE ADVISED IN CHERRYPICKING: Please see https://highfidelity.fogbugz.com/f/cases/4056/qml-sendToScript-doesn-t-work-in-tablet

**Pull request merged**
