### PR TITLE
PAL Tablet UI modifications [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by vladest**
interface: Added C++ models for users, refresh and [?] stays in place now, UI modified to be adopted for screen size
Build: QML files are visible in QtCreator and deployed on changing to build folder

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
Ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7a325419d85eb907e036a43098b3688d33fc22a available at: https://gist.github.com/fd68b33a4d6a19ac08864b7004c1ae48<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9705-c7a3254.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9705-c7a3254.dmg

**Comment by sethalves** [comment]
I know some of this has already gone in via other PRs.  I'm going to close this one -- if there's something more we should keep here, let's bring it over to a new PR.

**Pull request closed without merging**
