### PR TITLE
fix audio stream logging

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
This was totally wrong, sorry..

**Comment by zzmp** [comment]
We don't seem to have anything better in place to maintain logging (we don't use filter rules, which would allow run-time toggling), so I just took out the info logging in PR/Dev builds, as other devs will probably not want to see them.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bcb39a86ab24731e9f4005d0908b40c780037647 available at: https://gist.github.com/5dba9a01a48bf7861d22d8ad4e39050a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-bcb39a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-bcb39a8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d765ec818c6b6c024f554cac8eb533c1255acb60 available at: https://gist.github.com/5dba9a01a48bf7861d22d8ad4e39050a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-d765ec8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-d765ec8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 706af08c84cc5e696fb3c18ac9451d82d155e0c2 available at: https://gist.github.com/5dba9a01a48bf7861d22d8ad4e39050a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-706af08.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-706af08.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d765ec818c6b6c024f554cac8eb533c1255acb60 available at: https://gist.github.com/5dba9a01a48bf7861d22d8ad4e39050a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-d765ec8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-d765ec8.dmg

**Comment by cozza13** [comment]
QA tested

**Comment by hifi-gustavo** [comment]
Build console output for commit: 912db1c0e169732cf2491f0430bf97cb0498e34c available at: https://gist.github.com/5dba9a01a48bf7861d22d8ad4e39050a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-912db1c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8651-912db1c.dmg

**Pull request merged**
