### PR TITLE
DO NOT MERGE : Adding support for sub surface scattering to improve skin renderingskin

### PR DESCRIPTION
**Pull request by samcake**
Just make it public so we can review and test.
Nothing final

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72c362f7b069a53a767ff52fca4c29ba1a4f1662 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c882832bf11827323e7f22a8113d7115b589a84 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd28498833d72686b92e31c8dda5dacbd3cc9192 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ec14fd746a88abc3984397505a84a5aeea6ba47 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 884b9211c620b3b1655a5c699036cc2f6f7c715c available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e95a31f7601207f795a2403a483cabf29383de55 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec68eba3cb1aef28c198bb1bf1e918f7386457d2 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a619a142ed3ac771670ff27a2fef7743bd493276 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bc8441c735e5cee13a1c242236c11aa10b9cb6a available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 938bc77b1f5b356932b12dfec75f5c46b1094bce available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 197d49fc03ddfff3b06f77638084233306bebc9c available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d128af48db49f07ef5575b2d93a11ea9e6224822 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f5e22d0eb18d698432310fd30b87fb8c0a0cde7 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab21a5a5d5a260765ab886d016c3972a44d9b56a available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a604d0eded421fc25eb8bf8c1576a703bbf928d available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9281b28d43ebc164020db059ac809861cc63f31a available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9281b28d43ebc164020db059ac809861cc63f31a available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab98614dd47887d85f8c204eacbe3e0c617b27a4 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f6c441b22a21fe70d13b2034abf941decbdab2d available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a52f1db7f3881b7cb3ec2a91febddac70f4ddd3 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 16c5a085d8693ab9e4afae1cd59ec130e41c396d available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 66b65391a46502d6186533f57b946108c7cf7cb4 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f2bf2b4238570b691c4ae4fc3ea40b25230e924 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f2bf2b4238570b691c4ae4fc3ea40b25230e924 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1eb4acf8159dec8346296d5415cd9fbee4a34b3c available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5827993125670a20ea5bb4fbce8181f82f8b8de8 available at: https://gist.github.com/bd9a23ccd8cf44250fe0a1c271c707f3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8104.dmg

**Pull request closed without merging**
