### PR TITLE
Fixed Particle Editor Update event

### PR DESCRIPTION
**Pull request by Menithal**
Particle Editor was agressively refreshing when ever a particle entity was being up dated

This fixes the issue of the entity editor updating to the particle editor on update.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2106/HighFidelity-Beta-PR11081-734330dc063311990e8308bed080582b8655fbc7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2106/HighFidelity-Beta-PR11081-734330dc063311990e8308bed080582b8655fbc7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2132/HighFidelity-Beta-PR11081-5fab6c37a3daec1beb0302af43fff7ce2f46f05a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2152/HighFidelity-Beta-PR11081-60201548670ca5549691dbab2091b93e14e4042d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2152/HighFidelity-Beta-PR11081-60201548670ca5549691dbab2091b93e14e4042d.exe

**Comment by themelissabrown** [comment]
@Menithal can I get a test plan for this?

**Comment by Menithal** [comment]
Test plan

Create particle entity.
Particle settings visible.
Move entity
Particle at settings visible.
Switch to entity properties. 
Move entity. 

Window should stay on entity properties and not switch back to Particles.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Create particle entity. **Check**
Particle settings visible. **Check**
Move entity **Check**
Particle at settings visible. **Check**
Switch to entity properties. **Check**
Move entity. **Check**

Window should stay on entity properties and not switch back to Particles. **Check & Pass!**

All looks good here as per test plans instruction.

**Pull request merged**
