### PR TITLE
(RC 74) Fix: Interstitial page restoring ignored entities

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for restoring entity interaction with ignored entities in interstitial page

### CODE REVIEW

**Comment by wayne-chen** [comment]
TEST PLAN:
- Launch interface in HMD mode
- Go to a domain that has entities blocking the abort button (i.e. hifi://gigs)
- Try to hover over the abort button without clicking it
- Land in attemped domain (i.e. hifi://gigs)
- Entity originally attempted should be clickable with lasers

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13709/HighFidelity-Beta-PR14160-ea8229f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13709/HighFidelity-Beta-PR14160-ea8229f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13709/HighFidelity-Beta-Interface-PR14160-ea8229f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13709/HighFidelity-Beta-PR14160-ea8229f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13709/HighFidelity-Beta-Interface-PR14160-ea8229f.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

I regret to leave this result because it makes no sense to me.

The following domains no longer exhibit this bug:
Serverless (tutorial), default sandbox content, BodyMart, Avatar Island, Mexico, Eschatology

However, in Gigs, the bug still occurs.

image

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2457941/hifi-log.txt)
[hifi-log_2018-10-08_15.11.45.txt](https://github.com/highfidelity/hifi/files/2457942/hifi-log_2018-10-08_15.11.45.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13732/HighFidelity-Beta-PR14160-6f9593d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13732/HighFidelity-Beta-PR14160-6f9593d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13732/HighFidelity-Beta-Interface-PR14160-6f9593d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13732/HighFidelity-Beta-PR14160-6f9593d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13732/HighFidelity-Beta-Interface-PR14160-6f9593d.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

On all domains tested, the abort button isn't blocked, and lasers collide as expected with all nearby entities once loaded

**Pull request merged**
