### PR TITLE
Discovery cleanup

### PR DESCRIPTION
**Pull request by howard-stearns**
see commit messages

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b62332058079cd0779657de3a12316b8b92688c available at: https://gist.github.com/29d8fc51e4ab49aedcffd2c70a8593b5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8424-1b62332.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8424-1b62332.dmg

**Comment by howard-stearns** [comment]
DNM because something got skewed in our changes. Snapshots are not being saved...

**Comment by howard-stearns** [comment]
fixed it

**Comment by hifi-gustavo** [comment]
Build console output for commit: afe376a0a26c6859301a404c3cd44eb265486308 available at: https://gist.github.com/29d8fc51e4ab49aedcffd2c70a8593b5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8424-afe376a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8424-afe376a.dmg

**Pull request merged**
