### PR TITLE
Renaming the env variable to enable Material Procedural Shaders

### PR DESCRIPTION
**Pull request by samcake**
Refining the name we used to describe the feature "MaterialProceduralShaders"

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22298/HighFidelity-Beta-PR16446-a469699.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22298/HighFidelity-Quest-Beta-PR16446-a469699.apk)

**Comment by hd23408** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22301/HighFidelity-Beta-PR16446-a469699.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22301/HighFidelity-Quest-Beta-PR16446-a469699.apk)

**Pull request merged**
