### PR TITLE
Beta Release 11 - includes up to Developer Release 4901

### PR DESCRIPTION
**Pull request by cozza13**
Beta Release 11 - includes up to Developer Release 4901

**Test Notes:**

This is a combination of overall smoke testing, combined with specific tests. 

There is a QA script that you can use for general testing : http://rawgit.com/cozza13/QAtesting/master/qaTest20.js

Within this script there is a help section they you should take a look at, As a first step you can run through the smoketesting section. 

capture

**Release Notes**

- Show debug icons when someone else is the simulation owner
- Defer mipmap generation to GPU
- Fixing the bad color format on skymaps
- Switch OctreeSendThread and OctreePersistThread to use std::this_thread::sleep_for() instead of usleep()
- Make ResourceCache::resetResourceCounters threadsafe
- Fixes the collision sounds not playing for avatar and entities
- Add state changes to the ScriptableResource
- Updates to improve Grab script
- Linux client updates
- Use sleep_until for ScriptEngine
- Add an example gravity script
- Remove the recurring deadlock status log message
- Fix Script.include(/~/system/libraries/utils.js) to work from web
- Resurrection of threadsafe ViewFrustum
- Clean up resource cache's encapsulation of asynchronous loading
- Updates to default idle and turn animations
- Use smart pointers for entity simulations
- Enabling the use of QScriptEngineDebugger in Interface for script debugging
- Control the mouse with hand controllers (Razer Hydra and Vive) 
- Don't show help or login on first run
- Fix for Vive controllers sometimes not working
- Eye tracking bug fix and debug rendering improvements
- Updates to Home content
- Introduce the "Unlit" shading model support and apply it to Web Entities
- Check vector access in fbx reader
- Fix reticle position offset
- Defaulting the color formats used in the rendering pipeline to sRGB
- Fix invisible default avatars
- Fix for better out of Away mode in Vive
- Fix procedural rendering on primitives
- Support partial CPU->GPU buffer transfers
- Fix texture sampler calculation
- Fix hang on exit from dying scripts
- Remove the last of the avatar billboard code
- When a ModelEntityItem moves, also update its meta-render-item
- Wait and cleanly exit the scripting thread

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2ece6f4a7adb1545a0c07ab0a6d25ab48136287 available at: https://gist.github.com/aac122f180e0f00721c2613736104584<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7907.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7907.dmg

**Comment by kevinmthomas-carpool** [comment]
[qaTest 2.0.zip](https://github.com/highfidelity/hifi/files/267882/qaTest.2.0.zip)

**Comment by kevinmthomas-carpool** [comment]
Additional files needed.
[qaTest 2.0.zip](https://github.com/highfidelity/hifi/files/267899/qaTest.2.0.zip)

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Edit** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Models which had a shiny appearance no longer exhibit such. Attached are two screen shots, the first with the PR build, the second with the current release.

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |5745 |4606 |3047
**GPU Buffer Count**: |1259 |774 |700
**CPU Memory Usage**: |82178048 |82219008 |53104640
**GPU Memory Usage**: |30081024 |25968640 |18665472
**CPU Texture Count**: |306 |144 |130
**GPU Texture Count**: |195 |74 |113
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |309436736 |162395208 |49425480
**GPU Texture Memory Usage**: |746447858 |331373192 |313136928
**GPU Virtual Memory Usage**: |746447858|331373192|313136928
**Triangle Count**: |109083 |646059 |275804
**Triangle Rate**: |6817687 |43070600 |16223764
**API Drawcall Count**: |66 |224 |46
**Drawcall Count**: |69 |222 |46
**Drawcall Rate**: |4312 |14800 |2705
**State Changes Texture Count**:|68 |154 |29
**Pipeline Count**: |19 |29 |14
**Item Opaques**: |79 |358 |36
**Item Translucents**: |2 |14 |17
**Item Lights**: |12 |40 |0
**Timing Opaques**: |723 |4906 |370
**Timing Translucents**: |12 |63 |135
**Timing Lighting**: |139 |261 |35
**Render Frame**: |1578 |6516 |1014
pr7907 - lacking shine
build 4878

**Comment by Nex-Pro** [comment]
## QA Test PR#7907

**Platform: Desktop PC**
**CPU: 4.0 i7**
**Memory: 16gb**
**GPU Nvidia gtx770 2gb**
**OS: Win 10 64 pro.**
**HMD: none**
**Hand Controllers / other controllers: none**

**QA Tester: Piper.Peppercorn**

**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP Upload + Edit** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations: No other tasks undertaken**

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |60 |51
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |51
**CPU Buffer Count**: |4847 |5323 |3232
**GPU Buffer Count**: |937 |787 |716
**CPU Memory Usage**: |78741504 |103530496 |64663552
**GPU Memory Usage**: |29298688 |45555712 |31543296
**CPU Texture Count**: |248 |333 |199
**GPU Texture Count**: |163 |206 |173
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |301708476 |1044628624 |350564752
**GPU Texture Memory Usage**: |789263750 |1215586386 |747886167
**GPU Virtual Memory Usage**: |789263750|1215586386|747886167
**Triangle Count**: |427569 |768396 |411068
**Triangle Rate**: |26723062 |48024750 |25691750
**API Drawcall Count**: |211 |245 |133
**Drawcall Count**: |211 |291 |133
**Drawcall Rate**: |13187 |18187 |8312
**State Changes Texture Count**:|201 |264 |85
**Pipeline Count**: |25 |29 |21
**Item Opaques**: |249 |376 |667
**Item Translucents**: |9 |51 |26
**Item Lights**: |23 |40 |1
**Timing Opaques**: |1541 |2143 |1610
**Timing Translucents**: |81 |169 |276
**Timing Lighting**: |115 |187 |78
**Render Frame**: |2401 |3413 |2780

**Comment by OmegaHeron** [comment]
QA Pass
Windows 10 64 bit - i5 6500 CPU - GTX970 GPU **Desktop mode only - keyboard/mouse**
Compile/deploy stack with Linux - Pass
Comparison to previous RC for CPU/GPU/Memory/FPS (Pass = improved or no change) - Pass

## QA Test
**QA Tester**: Omega Heron
**localhost 'createTestBlocks.js' Result**: Pass
**localhost ATP Upload + Edit Result**: Pass
**Echo Server Audio**: Pass
**localhost 'harmonicOscillator.js' Result**: Pass
**localhost 'reverbTest.js' Result**: Pass
**localhost 'playaPerformanceTest.js' Result**: Pass
**playa 'playaPerformanceTest.js' Result**: Pass
**cellscience 'playaPerformanceTest.js' Result**: Pass

My table of stats looks too much like Kevin's or Piper's - seems no need to clog thread with more.

**Comment by cozza13** [comment]
Failed based on issue with Metalic

**Comment by samcake** [comment]
@kevinmthomas-carpool 
I see a difference in the Roughness value displayed for the metallic parts of the drums
In the new build there at 1.0 meaning NOT shinny
They are at .5 in the current master.
Investigating...

**Comment by jherico** [comment]
@samcake could the shiny issue be related to the filter fix that was recently merged?

**Comment by samcake** [comment]
@austin i doubt it
THis is a simple material with no texture
I think it s maybe a change in the way the roughness gets interpreted from the FBX material

**Comment by samcake** [comment]
We  know where it s broken http://builds.highfidelity.com/HighFidelity-Beta-4884.exe , trying to debug
I have notice a first bug already...

**Comment by Menithal** [comment]
Ill do a pass on some of my objects to check the values as well if there is an issue. My Pitchforks and Torches should be a good reference to test those. 

http://www.norteclabs.com/HF/objects/PitchFork.fst
http://www.norteclabs.com/HF/objects/Torch.fst

**Comment by Menithal** [comment]
Yeah, can confirm, Metal seems to be completely ignored, AND shinyness cutoff is at 50%. 

Here is a test object that shows this roughness gradient issue http://www.norteclabs.com/HF/experiment/RoughnessGradient2.fbx

**Comment by samcake** [comment]
I think i have the fix here:
https://github.com/highfidelity/hifi/pull/7910

**Pull request closed without merging**
