### PR TITLE
more context for update performance stats

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6152/app_12124_PR.apk

**Comment by AndrewMeadows** [comment]
We had a debug stat called `/idle/update/misc` which was not very helpful for devs who were wondering where time was being spent in the "game loop".  It was put there to capture new "work" that is added to the `/idle/update/` context: devs tend to add new code to `/idle/update/` but neglect to add a `PerformanceTimer` for it and then debug stats might no longer show where interesting amounts of time is being spent.

I've gone through and added more informative names to the various contexts that consume CPU resources/time in what used to be called `/idle/update/misc/`, to make it a little easier to debug poor game loop performance.

**Test Plan:**

**(1)** Enable the debug stats dashboard.  Either press the `/` key or enable this menu option:

**Developer --> Stats**

**(2)** Enable the following menu options:

**Developer --> Timing --> Performance Timer --> Display Timing Details** = Enabled
**Developer --> Timing --> Performance Timer --> Expand /update** = Enabled

**(3)** Disable the following menu options (just to keep the volume of stats to a reasonable level):

**Developer --> Timing --> Performance Timer --> Expand /paintGL** = Disabled
**Developer --> Timing --> Performance Timer --> Expand /physics** = Disabled

**(4)** Show detailed stats by toggling the mouse inside one of the debug dashboard columns.  Note the names of the various `/idle/update/` stats contexts.

--> On `hifi/master` you should see a context called `/idle/update/misc/`.
--> On this PR the old `misc` context is gone.  In its place you'll probably see `/idle/update/pickManager` and `/idle/update/pointerManager` which are new.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6152/HighFidelity-Beta-PR12124-8c6edc749afe4274399860c4741873980800086a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6152/HighFidelity-Beta-PR12124-8c6edc749afe4274399860c4741873980800086a.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing completed for PR#12124. PASSED

**Pull request merged**
