### PR TITLE
Revert safe landing "fix"

### PR DESCRIPTION
**Pull request by hyperlogic**
This was introduced via this PR #16479 

https://highfidelity.atlassian.net/browse/DEV-2762

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22541/HighFidelity-Beta-PR16494-929e829.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22541/HighFidelity-Beta-Interface-PR16494-929e829.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22541/HighFidelity-Beta-PR16494-929e829.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22541/HighFidelity-Quest-Beta-PR16494-929e829.apk)

**Comment by hyperlogic** [comment]
build this please *sigh*

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22544/HighFidelity-Beta-PR16494-929e829.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22544/HighFidelity-Quest-Beta-PR16494-929e829.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22544/HighFidelity-Beta-PR16494-929e829.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22544/HighFidelity-Beta-Interface-PR16494-929e829.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22547/HighFidelity-Beta-PR16494-929e829.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22547/HighFidelity-Beta-Interface-PR16494-929e829.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22547/HighFidelity-Beta-PR16494-929e829.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22547/HighFidelity-Quest-Beta-PR16494-929e829.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22547/HighFidelity-Beta-PR16494-929e829.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22547/HighFidelity-Beta-Interface-PR16494-929e829.exe

**Pull request merged**
