### PR TITLE
Make console log more robust

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5f1a159e1dc7a867af08643de50a68bd3de87703 available at: https://gist.github.com/23fa0d48e5dc8dae51f7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7055.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7055.dmg

**Comment by huffman** [comment]
What this fixes:
- Log window should now open more quickly for long-running servers
- Logs should show up correctly for newly connected ACs

To test:

- Run these scripts:
 - https://gist.githubusercontent.com/huffman/704fc87ea8c2b44cb0c1/raw/e4904e98cc48303ff9e8f724ef4529d855623777/loggerA.js
 - https://gist.githubusercontent.com/huffman/40e9a5196214f3f872da/raw/7f597e4793d4350e77e8cea7d1ae41446204d41f/loggerB.js
 - https://gist.githubusercontent.com/huffman/c20eb80290faca1c9f01/raw/f9608dfa774d067439e574b82480c8dab8fa54ac/loggerC.js
- Open the logs, see a bunch of text
- Confirm that you see log lines starting with "A", "B", and "C".
- Wait a few minutes
- Open the logs again. It should be quick.

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
I can confirm this makes the log window work more smoothly than before. I used to have issues where it was sluggish and ran slower. I say this passes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ef95fafabe3a9a4783cdeab5dc488e993b4dc6c7 available at: https://gist.github.com/23fa0d48e5dc8dae51f7<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7055.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7055.dmg

**Pull request merged**
