### PR TITLE
fix crash on shutdown in debug

### PR DESCRIPTION
**Pull request by zzmp**
Fix crash on shutdown from failure to check thread validity in thread. Only occurs if thread has time to quit, as when another exception is handled in debug builds.

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Run the same test suite as #7882.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c480dcfddd740a939c60e0ef477256591612e8b2 available at: https://gist.github.com/6bd52b5330d967996ebd4d431832664f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.dmg

**Comment by zzmp** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: c480dcfddd740a939c60e0ef477256591612e8b2 available at: https://gist.github.com/6bd52b5330d967996ebd4d431832664f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c8ff557dbbe5a27b5b94531fe4b904c2abd1d3c available at: https://gist.github.com/6bd52b5330d967996ebd4d431832664f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7926.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Successful test. ```test.js``` caused no issue of any kind and ```loop.js``` was loaded into an entity which had no issue of any kind as well as ```unload.js```.

**Pull request merged**
