### PR TITLE
avoid a crash during domain change while wearing something

### PR DESCRIPTION
**Pull request by sethalves**
- avoid a crash during domain change while wearing something

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- wear something from the store
- change domains a few times
- don't crash

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5134/HighFidelity-Beta-PR11873-9ccc416e80288253b9bdfa232092b101080003a1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5134/HighFidelity-Beta-PR11873-9ccc416e80288253b9bdfa232092b101080003a1.dmg

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
@sethalves Unable to wear anything at A&J . Was able to do so earlier today in another build.

**Comment by sethalves** [comment]
@Nex-Pro the important thing is to have an avatar entity on.  It doesn't actually matter how that happens.  If switching to another build until the thing is worn works, that should be fine for this test.

**Comment by Nex-Pro** [comment]
@sethalves Ok will do.

**Comment by Nex-Pro** [comment]
### PASS

30 hops to other domains with avatar ent attached. Interface exited cleanly.

**Pull request merged**
