### PR TITLE
modified version of mod.js that leaves icon stationary and connects line between icon and avatar

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 972b39e880f6c69bd3e14de5c0bb30647251f418 available at: https://gist.github.com/1e5bdf4f6546f608c2cb08525f0ef1d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9097-972b39e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9097-972b39e.dmg

**Comment by ZappoMan** [comment]
Test Plan:
- smoke test
- test kick/mute in a domain you have kick rights in... it should show a line between kick icons and the avatar and keep the icons stationary
- everything should work as before

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass

hifi-snap-by-omegaheron-on-2016-11-20_11-44-20


hifi-snap-by-omegaheron-on-2016-11-20_11-44-08

**Comment by Nex-Pro** [comment]
Strange I pasted results for this yesterday and they are not here ?

### QA Fail 

There is an issue with orphaned lines to avatars if the avatar leaves the domain while lines are active.
The old lines persist and are not removed if that avatar returns. 
They exist in 3d space and they can be observed to be stationary as you move around.

See images below.

hifi-snap-by-piper-peppercorn-on-2016-11-20_14-30-13
hifi-snap-by-piper-peppercorn-on-2016-11-20_14-18-09
hifi-snap-by-piper-peppercorn-on-2016-11-20_14-18-09
hifi-snap-by-piper-peppercorn-on-2016-11-20_14-22-30
hifi-snap-by-piper-peppercorn-on-2016-11-20_14-27-55
hifi-snap-by-piper-peppercorn-on-2016-11-20_14-27-55

**Pull request closed without merging**
