### PR TITLE
Put current address to location instead of inputfield

### PR DESCRIPTION
**Pull request by vladest**
Test plan
- goto different addresses
- make sure addresses not filtered out when you arrive to new world

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d207dae5b7bdf8b295e20a37da3cbc49d5606f26 available at: https://gist.github.com/cfc1c6e971b843cf3e324be547ba5898<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10102-d207dae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10102-d207dae.dmg

**Comment by sharsein** [comment]
Testing

**Comment by sharsein** [comment]
Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive
Tested Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10102-d207dae.exe

Use input field to navigate to different locations in HMD-PASS with minor issues
When I navigate to a new location, the tablet exits go to mode. When I go back to the go to menu, the current address is in grey and other locations are not filtered out. Typing in the input field to filter results, then selecting a result from a thumbnail will result in multiple "your tablet needs attention" messages near my feet after the world loads, but these go away.

Use input field to navigate to different locations in Desktop mode-PASS with issues
When I type part of a location to start filtering, then click the thumbnail for that location, I get multiple "There is no address information for that user or place" even though the world loads as expected. I had to close out of this error message around 10 times after I had already closed the Go To menu

**Comment by anshuman64** [comment]
QA Passing this and creating new tickets regarding sharsein's comments.

**Pull request merged**
