### PR TITLE
minimal time handshake

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
**Test plan**:
Regression tests for making a connection.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13425/HighFidelity-Beta-PR14103-f96c7f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13425/HighFidelity-Beta-Interface-PR14103-f96c7f4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13425/HighFidelity-Beta-Interface-PR14103-f96c7f4.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13458/HighFidelity-Beta-PR14103-f96c7f4.apk

**Comment by rickcarr044** [comment]
Currently testing PR14103

**Comment by howard-stearns** [comment]
https://highfidelity.fogbugz.com/f/cases/18722/handshake-tuning

**Comment by rickcarr044** [comment]
PASS @conklin94122

Tested with MAC and Windows 10 w/Rift.  Passed steps in test case 'Handshake (HMD + Desktop) - Revised' with minor modification due to the quicker pace before making connection.  Observer/Tester 3 did not prevent the connection.

(https://highfidelity.testrail.net/index.php?/cases/view/17929&group_by=cases:section_id&group_order=asc&group_id=6495)

**Pull request merged**
