### PR TITLE
close tablet when taking a snapshot

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d84aae6701f786b91b3469791329cb45fe2dec0 available at: https://gist.github.com/4a38ab5a0d1ef6af2dfd55e44c6bbcf5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d84aae6701f786b91b3469791329cb45fe2dec0 available at: https://gist.github.com/4a38ab5a0d1ef6af2dfd55e44c6bbcf5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d84aae6701f786b91b3469791329cb45fe2dec0 available at: https://gist.github.com/4a38ab5a0d1ef6af2dfd55e44c6bbcf5<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9365-7d84aae.dmg

**Pull request merged**
