### PR TITLE
Support ETC2/EAC compressed textures

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- No way to test the new functionality until we add support for ETC2 baking or local compression on mobile.  Until then, this new code will never be triggered, so there is no functional change to test.
- As a sanity check, go to your local sandbox and verify that everything is textured correctly and that the skybox shows up.

The networking and engine teams will do full tests of the new functionality once we are generating these texture formats during baking.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8571/app_12812_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8571/HighFidelity-Beta-PR12812-44ea5a2e84460c227e9f52a5c43be2d30f94ffa7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8571/HighFidelity-Beta-PR12812-44ea5a2e84460c227e9f52a5c43be2d30f94ffa7.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8602/app_12812_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8602/HighFidelity-Beta-PR12812-6ffdae0500fd7575baa501c4d720fa6367b11196.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8606/HighFidelity-Beta-PR12812-6ffdae0500fd7575baa501c4d720fa6367b11196.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8608/app_12812_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8608/HighFidelity-Beta-PR12812-6ffdae0500fd7575baa501c4d720fa6367b11196.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8627/app_12812_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8627/HighFidelity-Beta-PR12812-6ffdae0500fd7575baa501c4d720fa6367b11196.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8627/HighFidelity-Beta-PR12812-6ffdae0500fd7575baa501c4d720fa6367b11196.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Textures and skybox look good.

**Pull request merged**
