### PR TITLE
Expose the Render api to the tablet js context and update render engine tool

### PR DESCRIPTION
**Pull request by samcake**
This PR does two things:
1/ it adds the "Render" scripting interface to the tablet js context so we can access the various render engine component from there like we do from standalone qml surfaces

2/ Benefiting that change and the fact that we can now access the hifi library of qml components i have updated the tool script that i use all the time to debug problems regarding rendering "debugDeferredLighting.js" and i have made a cool App with it called Luci. Luci.js is located in the developer/utilities/render folder of scripts and provide the same features as deferredLighting.js but integrated in the tablet and using the hifi widgets.

## TEST PLAN
Make sure that when running the script developer/utilities/render/luci.js you get a new app in the tablet
Verify that when running this app from the tablet (or from the toolbar) it represent the similar dui as  the old debugDeferredRendering.js (in master)
Verify that the enabling disabling features  appears to be working properly

The tool aspect of this PR makes it much less risky to break something in the normal usage of Interface.exe,
We need this as developer to help us debug issues

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4517/HighFidelity-Beta-PR11708-715cf301d5db1f0f548c2e8ebca22f8414cd3608.exe

**Comment by Nex-Pro** [comment]
Awaiting win build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4530/HighFidelity-Beta-PR11708-7e149fe30d6682847e3be71b6e05ce1474b583a0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4530/HighFidelity-Beta-PR11708-7e149fe30d6682847e3be71b6e05ce1474b583a0.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
### FAIL 


Make sure that when running the script developer/utilities/render/luci.js you get a new app in the tablet **SUCCESS**

Verify that when running this app from the tablet (or from the toolbar) it represent the similar dui as the old debugDeferredRendering.js (in master)

( will assume you meant gui)

Verify that the enabling disabling features appears to be working properly **Mostly ok see note**

The tool aspect of this PR makes it much less risky to break something in the normal usage of Interface.exe,
We need this as developer to help us debug issues


**NOTE:** Unable to access lower part of debug framebuffer dropdown.


Dropdown extends behind lower frame of tablet. As we can only use one laser or stylus at a time on the tablet it is not possible ( AFAIK ) to access the last four or five options.

**Comment by Nex-Pro** [comment]
d35144-hifi-snap-by--on-2017-10-28_00-19-45

**Comment by samcake** [comment]
Thanks for the test and feedback Piper,
I ll adjust the combo in future pr.
like i said it s a tool not part of the standard experience so i m fine with that bug.
Cheers

**Pull request merged**
