### PR TITLE
Fix for sliding feet when leaning in HMD mode.

### PR DESCRIPTION
**Pull request by hyperlogic**
QA Test:
  * while in HMD mode.
  * stand still and lean left and right.
  * your feet should stay planted on the ground.  On master they slide underneath your hips.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c58fdb590a170008847fe7ccef0ee436e97edeea available at: https://gist.github.com/d4037b81ecb7b45332bd0c5491bf3385<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10122-c58fdb5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10122-c58fdb5.dmg

**Comment by StarmanF** [comment]
testing

**Comment by StarmanF** [comment]
**Desktop PC - Windows 10 Education - CPU 4.0 GHz Intel i7 - GTX 1080 - RAM 16 GB - Vive**

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10122-c58fdb5.exe

**Fail**

Fix for sliding feet is only partially functional.

Notes:

- To test I put on HMD on the fresh install on the default sandbox and leaned left and right.

- As intended the avatar was planted and leaned along with me, but only when the user is looking straight forward in any direction. Forward, meaning, looking along one of the grid lines on the default sandbox.

- If I were to turn left or right 45 degrees from where it would be working perfectly, the body would adjust to my new look direction, but then not stay planted to the ground at all. If I were to turn 45 degrees again (in any direction) it would work perfectly once again since the user would be looking forward again. 

- The issue seemed easy to replicate, meaning this feature seems to work only half the time. I imagine this partial functionality might be noticeable in interactions with other people.

**Comment by PhilipRosedale** [comment]
QA FAIL: 

@hyperlogic Feet look better to me, but I can't grab the tablet, and once I've tried to grab it (closed my hand on it), it starts following me in that crazy way where it slews around with my avatar's yaw.

**Comment by hyperlogic** [comment]
@PhilipRosedale are you talking about using the tablet in third-person camera mode?  Yeah, I noticed that stopped working at some point.

**Comment by hyperlogic** [comment]
@StarmanF So this PR doesn't make foot placement perfect, it just restores the functionality that was broken from this PR #10080

**Pull request merged**
