### PR TITLE
Rename getpos3

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open the javascript console and run this:
```javascript
var entityID = Entities.addEntity({
  type: "Model",
  position: Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, {x: 0, y: 0.1, z: -3})),
  collisionless: true,
  name: "test model",
  modelURL: "http://headache.hungry.com/~seth/hifi/wow/wow-exports/world/wmo/brokenisles/araknashal/generalchairloend01.obj.gz",
  lifetime: 20
});
Script.setTimeout(function () {
    Entities.getMeshes(entityID, function(meshes, success) {
       var trans = Entities.getEntityTransform(entityID);
       meshes.forEach(function(mesh) {
           var transedMesh = Model.transformMesh(trans, mesh);
           var numVertices = transedMesh.getNumVertices();
           for (var i = 0; i < numVertices; i++) {
               var vertex = transedMesh.getPos(i);
               Entities.addEntity({
                   name: "debug vertex point",
                   color: { blue: 30, green: 200, red: 40 },
                   dimensions: { x: 0.06, y: 0.06, z: 0.06 },
                   position: vertex,
                   type: "Sphere",
                   lifetime: 20,
                   dynamic: false
               });
           }
       });
    });
}, 3000);
```
- look for a chair, and 3 seconds later, small spheres near every vertex of the chair

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/12553/MeshProxy-s-getPos3-function-would-be-better-named-getPos

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8033/app_12645_PR.apk

**Comment by conklin94122** [comment]
@sethalves Needs milestone

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8033/HighFidelity-Beta-PR12645-ee515a44e71911b23c8d6d8a6976af7996e391ce.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8033/HighFidelity-Beta-PR12645-ee515a44e71911b23c8d6d8a6976af7996e391ce.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

Chair and spheres appeared as expected, then disappeared as expected when their lifespan expired.

**Pull request merged**
