### PR TITLE
Fix the Space Bubble button flash behavior; Rate limit sound

### PR DESCRIPTION
**Pull request by zfox23**
The bubble button is supposed to flash on and off upon activation. Fixes [MS11365](https://highfidelity.manuscript.com/f/cases/11365/Bubble-icon-does-not-flash-when-bubble-is-activated).

Also, the sound is really annoying when it plays too often. Fix that, and address [MS7338](https://highfidelity.manuscript.com/f/cases/7338/Limit-the-times-the-bubble-audio-plays). Finally.

## Test Plan
1. In desktop mode, enable your Space Bubble. Verify that the Space Bubble icon flashes when you click on the icon to enable it (since it brings up the bubble and plays the sound when you first turn it on).
2. Have another avatar walk into your Space Bubble. Verify that the Space Bubble icon flashes when your Bubble is activated.
3. Have that avatar leave your Space Bubble.
4. Have that avatar enter your Space Bubble. As soon as your Space Bubble is activated, click on the BUBBLE icon to turn off your Bubble. Verify that the other avatar appears very close to you and that the BUBBLE Icon stops flashing.
5. Have that avatar rapidly enter and leave your Space Bubble. Verify that the sound doesn't play every time the Bubble is activated, but that it only plays, at minimum, once every 15 seconds.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6424/app_12208_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6424/HighFidelity-Beta-PR12208-1bda3faaf277d928b9d211211c89e76893524f45.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6424/HighFidelity-Beta-PR12208-1bda3faaf277d928b9d211211c89e76893524f45.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6428/app_12208_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6428/HighFidelity-Beta-PR12208-13d8d643f7f284c3d38183aab3a820efc85cbcc1.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6441/app_12208_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6441/HighFidelity-Beta-PR12208-13d8d643f7f284c3d38183aab3a820efc85cbcc1.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6450/app_12208_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6450/HighFidelity-Beta-PR12208-13d8d643f7f284c3d38183aab3a820efc85cbcc1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6450/HighFidelity-Beta-PR12208-13d8d643f7f284c3d38183aab3a820efc85cbcc1.dmg

**Comment by QAadahlin** [comment]
Currently testing

**Comment by QAadahlin** [comment]
Testing Completed for PR#12208. PASSED.

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12208. PASSED.

**Pull request merged**
