### PR TITLE
Fix animation crash, make last frame inclusive

### PR DESCRIPTION
**Pull request by SamGondelman**
same as https://github.com/highfidelity/hifi/pull/12175

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6308/app_12176_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6308/HighFidelity-Beta-PR12176-f1253e3c6cdcca4c348c4a5a7e6af4560211bdf3.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6312/app_12176_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6312/HighFidelity-Beta-PR12176-f1253e3c6cdcca4c348c4a5a7e6af4560211bdf3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6312/HighFidelity-Beta-PR12176-f1253e3c6cdcca4c348c4a5a7e6af4560211bdf3.dmg

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
