### PR TITLE
BUGZ-1503: Don't move unused Connection class upon address change

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Jira: https://highfidelity.atlassian.net/browse/BUGZ-1503

Don't move an unused Connection class for a changed address - it may have been created just for the stats tracking.
Make the handshake-request debugging active in regular builds - this is actually an error event.
Also some miscellaneous debugging clean-up.

### CODE REVIEW

**Comment by SimonWalton-HiFi** [comment]
Cherry-picked Clément's 96b58756 to allow testing.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21510/HighFidelity-Beta-PR16244-5067729.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21510/HighFidelity-Quest-Beta-PR16244-5067729.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21510/HighFidelity-Beta-PR16244-5067729.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21510/HighFidelity-Beta-Interface-PR16244-5067729.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21510/HighFidelity-Beta-PR16244-5067729.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21510/HighFidelity-Beta-Interface-PR16244-5067729.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21521/HighFidelity-Beta-PR16244-6d7f711.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21521/HighFidelity-Beta-Interface-PR16244-6d7f711.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21521/HighFidelity-Beta-PR16244-6d7f711.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21521/HighFidelity-Quest-Beta-PR16244-6d7f711.apk)

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21525/HighFidelity-Beta-PR16244-6d7f711.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21525/HighFidelity-Quest-Beta-PR16244-6d7f711.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21525/HighFidelity-Beta-PR16244-6d7f711.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21525/HighFidelity-Beta-Interface-PR16244-6d7f711.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21528/HighFidelity-Beta-PR16244-6ccfc37.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21528/HighFidelity-Quest-Beta-PR16244-6ccfc37.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21528/HighFidelity-Beta-PR16244-6ccfc37.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21528/HighFidelity-Beta-Interface-PR16244-6ccfc37.dmg

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21537/HighFidelity-Beta-PR16244-6ccfc37.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21537/HighFidelity-Beta-Interface-PR16244-6ccfc37.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21537/HighFidelity-Beta-PR16244-6ccfc37.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21537/HighFidelity-Quest-Beta-PR16244-6ccfc37.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21537/HighFidelity-Beta-PR16244-6ccfc37.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21537/HighFidelity-Beta-Interface-PR16244-6ccfc37.exe

**Pull request merged**
