### PR TITLE
fix keys getting stuck

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by jherico** [comment]
## Testing

* open edit UI
* click on the edit window anywhere
* press and release the left arrow
* click off the edit window in empty space
* press and release the left arrow

In the current production build, your avatar will now be stuck spinning counterclockwise until you press and release the left arrow again.  In this PR build you should no longer be stuck spinning.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f2f9da01911001914953503bfae11eda6d9e3d7 available at: https://gist.github.com/9d0deaee55089c0efaf7dfef52c342d8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7958.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7958.dmg

**Comment by Nex-Pro** [comment]
####QA PASS on Win 10

**Comment by Nex-Pro** [comment]
**Repeated attempts to trigger the spinning, previously seen, failed to do so. Thanks. You saved a lot of users from wrenching their headsets off.**

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f2f9da01911001914953503bfae11eda6d9e3d7 available at: https://gist.github.com/9d0deaee55089c0efaf7dfef52c342d8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7958.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7958.dmg

**Pull request merged**
