### PR TITLE
Make it Easier to Change Audio Settings in the Tablet UI

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- Lists of input and output audio devices are displayed directly under "Audio" settings page in the menus and in the tablet, rather than being a level further down.
- Mute / Unmute tablet button in the tablet has been replaced with an "Audio" button that opens the audio settings page.
- The microphone icon before the level meter in the tablet displays mic muted / not muted state.
- Hovering the microphone icon or level meter changes teh mic icon to indicate that you can change the mic mute state.
- You can click the microphone icon or level meter to toggle the mute state.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 77f0fb14912b0546fbc6c6b2392ae47d7d809fe7 available at: https://gist.github.com/c15a4681ec8912ef26636a84179ddc87<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9651-77f0fb1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9651-77f0fb1.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass

Selection via desktop mode using menus = pass.

Tablet - in desktop mode.
Works as expected.  (Not within PR control - but the long audio device names get severely clipped).
Able to select devices properly, able to toggle audio, mouseover indicates toggle ability as described.

Tablet with DK2/Xbox controller
Same as above - able to select devices with mouse and xbox+third eye laser.

I did encounter a oddity once or twice while toggling audio while in HMD where icon changed to indicate audio was hot (on) but didn't actually engage (no echo back heard).  I suspect it was just a fluke as I can't reproduce it other than 2 times.  Something to watch for, just in case.

General smoke test = pass

Noticed that master shows output devices then input devices in menu selection method (not tablet) where this reverses it, not a problem, just threw me for a second when it didn't look "right".

**Comment by hifi-gustavo** [comment]
Build console output for commit: 625f5efdf8f4511b6d05fbc60a267fcf6958e634 available at: https://gist.github.com/c15a4681ec8912ef26636a84179ddc87<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9651-625f5ef.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9651-625f5ef.dmg

**Pull request merged**
