### PR TITLE
Add Window.raise() as replacement for Window.raiseMainWindow()

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Test scripts: 
[21677.zip](https://github.com/highfidelity/hifi/files/1849916/21677.zip)

On Windows...

Run the script hasFocusRepeat.js. This repeatedly reports the current value of Window.hasFocus() to the program log - best viewed using Developer > Script Log.

1) The script raiseDelayed.js calls Window.raise() after a 5 second delay. Use it (reload it as necessary) to test:
a) Leave the Interface window with focus, and wait for the raiseMainWindow() call to be made: Interface window continues to have focus and Window.hasFocus() continues to report true.
b) Minimize Window to the taskbar but don't use any other application, and wait for the raiseMainWindow() call to be made: the Interface window should open and get focus, with Window.hasFocus() reporting true. ... Test minimizing and raising Interface window both when window is normal (windowed) and when it is maximized.
c) Minimize Window to the taskbar and use another application, and wait for the raiseMainWindow() call to be made: the Interface window should open and get focus, with Window.hasFocus() reporting true. ... Test minimizing and raising Interface window both when window is normal (windowed) and when it is maximized.

2) The script raiseMainWindowDelayed.js calls Window.raiseMainWindow() after a 5 second delay. Repeat the three tests of 1).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8290/app_12715_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8290/HighFidelity-Beta-PR12715-d1d58eceab9c8f97fa43cd0e7ee2ffe3e01846d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8290/HighFidelity-Beta-PR12715-d1d58eceab9c8f97fa43cd0e7ee2ffe3e01846d7.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Scripts work as intended.

**Pull request merged**
