### PR TITLE
fix crash on shutdown from script timers

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Fixes a very intermittent crash where timers may trigger script methods after a ScriptEngine is destroyed. You will not be able to repro it.

Test scripts with timers, and make sure shutdown still works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8025a3f14cb7602204c02e08a7c5cafaa1ab2eb5 available at: https://gist.github.com/28b4a6368b554861fafc1568c006de78<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7927.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7927.dmg

**Comment by Nex-Pro** [comment]
**PR Build: #7853**
**Testing Architecture:** Desktop PC
**CPU:** 4.0 ghz i7
**GPU:** Nvidia gtx770 2gb
**Testing OS:** win 10 pro
**Testing Locations:**  sandbox

**PASS**  *on specific test requirements*.

**Scripts used in testing:** toolWindowStressTest.js recorder.js rapidProceduralChangeTest.js

Scripts were run simultaneously.

Scripts persisted across restarts.

Started and closed interface approx 25 times, with the scripts running, whilst observing the task manager.
Interface exited cleanly on every occasion. Using any of  the close icon,  ctr+Q or the file menu quit option.

-----------------------------------------------------------------------------

Notes: Again unassociated graphics issues as previously mentioned. 
( texture missing on default avatar and very low frame rates.)

In addition I noticed a sluggish response to keyboard combinations such as ctrl+Q and ctrl+J
Sometimes needed 3 attempts to get scripts window up or exit via ctrl+Q.
I'll keep you posted on that on further PRs if it is of importance.

**Comment by Nex-Pro** [comment]
Ignore comment regarding sluggish keyboard above, it was due to the toolWindowStressTest.js script.

**Pull request merged**
