### PR TITLE
RC75: Fix tablet culling

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/17284/Tablet-frame-model-disappears-when-looking-away-from-area-where-tablet-was-last-grabbed-or-opened

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14882/HighFidelity-Beta-PR14368-954e32f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14882/HighFidelity-Beta-PR14368-954e32f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14882/HighFidelity-Beta-Interface-PR14368-954e32f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14882/HighFidelity-Beta-PR14368-954e32f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14882/HighFidelity-Beta-Interface-PR14368-954e32f.exe

**Comment by qaAdamSmith82** [comment]
Test Plan 1

**Comment by qliejahner** [comment]
Currently testing

**Pull request merged**
