### PR TITLE
Look at whole tex for alpha mask

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Intent

The image reader was incorrectly seeing opaque textures with an alpha mask as having valid alpha values, and rendering them as transparent.

#### Testing

Load an avatar that was buggy, like Albert. Albert's coat is currently transparent.
In this PR's build, his coat should be opaque.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7e09e4aff26cd7b6010cf74526743f01100d311 available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7e09e4aff26cd7b6010cf74526743f01100d311 available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ad0045cd36c9842bf45a9aa95a95da5c0139ce5 available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5d583bf9208aba82c75f433e24a0e5c9c46e2b0e available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e1224fe0d5fff7e8d6620ec64749af99fdfd9a51 available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0ba5d3c290920d78c829836eedb47216189b8d6 available at: https://gist.github.com/7f50501f790bff8b81c2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7391.dmg

**Comment by samcake** [comment]
checked with success

**Pull request merged**
