### PR TITLE
fix desktop press-x handshake

### PR DESCRIPTION
**Pull request by sethalves**
- fix desktop press-x handshake

https://highfidelity.manuscript.com/f/cases/14416/
https://highfidelity.manuscript.com/f/cases/17282/Unable-to-handshake-in-desktop-mode

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- using desktop mode, press X to shake hands with someone

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12074/HighFidelity-Beta-PR13818-b2f79a1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12074/HighFidelity-Beta-PR13818-b2f79a1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12074/HighFidelity-Beta-Interface-PR13818-b2f79a1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12074/HighFidelity-Beta-PR13818-b2f79a1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12074/HighFidelity-Beta-Interface-PR13818-b2f79a1.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Desktop users can press x to handshake with other users

**Pull request merged**
