### PR TITLE
Fix overlays text size

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a527bd85baf210811b3b9a2e9e19a4d5d34aac1a available at: https://gist.github.com/01c99ccccb85d19f93a8<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.dmg

**Comment by huffman** [comment]
Hold off on this please - There seems to a crash bug when a script that's loaded with interface calls textSize()

**Comment by hifi-gustavo** [comment]
Build console output for commit: 51ff897ee513f4327ac7415bcf37be8560772061 available at: https://gist.github.com/3afa97c36648fa8175bf<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 341e31a074ee2ae60ccbc1d05fff0a4810c95c73 available at: https://gist.github.com/13d4f432db998aa0cb44<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4271.dmg

**Comment by huffman** [comment]
This is ready to be reviewed

**Pull request merged**
