### PR TITLE
New model dialog fix

### PR DESCRIPTION
**Pull request by RebeccaStankus**
This fixes the custom query dialog box to allow for 3 lines of warning message instead of 2 so the message will not be cut off.

https://highfidelity.fogbugz.com/f/cases/12831/ADD-TO-WORLD-dialog-is-not-displaying-all-text-related-to-using-Exact-All-polygons-option

TESTING

- Open interface in desktop and go to your sandbox
- Open Menu>Edit>Asset Browser, select any fbx or obj file and "Add to World"
- A popup dialog box appears. Set automatic collisions to "Exact- All Polygons"
- A warning message should appear. It should be 3 lines long and not cut off: "Models with 'Exact' automatic collisions cannot be dynamic, and should not be used as floors"
- Open interface in HMD and go to your sandbox
- Open Tablet and Menu>Edit>Asset Browser, select any fbx or obj file and "Add to World"
- A popup dialog box appears. Set automatic collisions to "Exact- All Polygons"
- A warning message should appear. It should be 3 lines long and not cut off: "Models with 'Exact' automatic collisions cannot be dynamic, and should not be used as floors"
- Repeat test for Android...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9295/app_13041_PR_269a7f0e155b42c880c543c959154b1b0d17e6de.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9295/HighFidelity-Beta-PR13041-269a7f0e155b42c880c543c959154b1b0d17e6de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9295/HighFidelity-Beta-Interface-PR13041-269a7f0e155b42c880c543c959154b1b0d17e6de.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tested on Windows 10, the text looks good and is wrapped well.

**Pull request merged**
