### PR TITLE
fix configuration page

### PR DESCRIPTION
**Pull request by danteruiz**
Display the correct information on the vive configuration page.

ticket - https://highfidelity.manuscript.com/f/cases/16407/Input-Calibration-Screen-shows-undefined-HMD

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan (vive required)
- Open Settings > Control > Calibration
- The Head option should not show undefined HMD. 

image

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11065/HighFidelity-Beta-PR13524-603ab87.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11065/HighFidelity-Beta-PR13524-603ab87.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11065/HighFidelity-Beta-Interface-PR13524-603ab87.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11065/HighFidelity-Beta-PR13524-603ab87.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11065/HighFidelity-Beta-Interface-PR13524-603ab87.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
HMD is now correctly labeled.

**Pull request merged**
