### PR TITLE
remove expired avatarEntities from their avatars 0.73.2

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
This PR fixes a bug where avatarEntities with finite lifetime do not get removed from the avatar's settings when they are deleted on expiry.  The internal manuscript case is 18739:

https://highfidelity.manuscript.com/f/cases/18739/Avatar-entity-particle-effects-do-not-respect-their-lifetime-property-and-stay-with-a-user

**Test Plan**

**(1)** Examine your `Interface.json` file and make sure there aren't any previously existing avatar entities in there.  Specifically you want a line like this with zero value:
```
    "Avatar/avatarEntityData/size": 0,
```
If that is not true then edit your I`nterface.json` file and remove the two lines that start like this:
```
    "Avatar/avatarEntityData/1/id":
    "Avatar/avatarEntityData/1/properties":
```
And change the `Avatar/avatarEntityData/size` line to be `0`.

**(2)** Login to a domain and run this code via console or local file script:
```
var forward = Quat.getFront(MyAvatar.orientation);
var forwardOffset = Vec3.multiply(2.0, forward);
var objectPosition = Vec3.sum(MyAvatar.position, forwardOffset);
var id = Entities.addEntity( {
            type: "Box",
            name: "fubar",
            dimensions: {x: 0.6, y: 0.8, z: 1.0},
            position: objectPosition,
            color: {red: 255, green: 100, blue: 10},
            dynamic: true,
            lifetime: 10 }, true);
```
That will create a temporary orange avatarEntity box about 2.0 meters in front of your avatar that will live for 10 seconds.

**(3)** After  10 seconds it should vanish.  At this point: logout.

**(4)** Log back in.
--> on **0.73.1** the orange box will reappear on login and will live for another 10 seconds before vanishing
--> on **this PR** the orange box will not reappear

**(5)** Examine your `Interface.json` file:
--> on **0.73.1** you'll see:
```
    "Avatar/avatarEntityData/size": 1,
```
And some gobbledygook non-human-readable data for the `Avatar/avatarEntityData` itself.

--> on **this PR** you'll see:
```
    "Avatar/avatarEntityData/size": 0,
```
With no `Avatar/avatarEntityData`.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13682/HighFidelity-Beta-PR14151-963a7bf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13682/HighFidelity-Beta-PR14151-963a7bf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13682/HighFidelity-Beta-Interface-PR14151-963a7bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13682/HighFidelity-Beta-PR14151-963a7bf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13682/HighFidelity-Beta-Interface-PR14151-963a7bf.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by jakram** [comment]
@qaAdamSmith82 and I are testing the Win version

**Pull request merged**
