### PR TITLE
BUGZ-712 potential fix for crash in NLPacket::localHeaderSize()

### PR DESCRIPTION
**Pull request by AndrewMeadows**
This PR uses a `switch` rather than `QSet<>::contains()` to answer the question: "Is this enum value in such-and-such group or not?"  If the callstack on the BUGZ-712 crash mode is to be believed then I would expect this to fix it.

https://highfidelity.atlassian.net/browse/BUGZ-712

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20127/HighFidelity-Beta-PR15835-8245018.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20127/HighFidelity-Quest-Beta-PR15835-8245018.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20131/HighFidelity-Beta-PR15835-c5bda6e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20131/HighFidelity-Quest-Beta-PR15835-c5bda6e.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20134/HighFidelity-Beta-PR15835-acf98e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20134/HighFidelity-Beta-Interface-PR15835-acf98e0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20134/HighFidelity-Beta-PR15835-acf98e0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20134/HighFidelity-Quest-Beta-PR15835-acf98e0.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20134/HighFidelity-Beta-PR15835-acf98e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20134/HighFidelity-Beta-Interface-PR15835-acf98e0.exe

**Comment by AndrewMeadows** [comment]
Sigh.  I'm going to close this PR.  While it would be a step toward the Glorious Future, it doesn't actually fix the bug.  The real fix is in PR-15841.

**Pull request closed without merging**
