### PR TITLE
Remove #line from starsGrid.slf

### PR DESCRIPTION
**Pull request by huffman**
Fails to compile with certain drivers.

### CODE REVIEW

**Comment by huffman** [comment]
See logs in https://app.asana.com/0/26224634468389/113476676812389 to see the problem

**Comment by huffman** [comment]
To test:

* Smoke test
* Ensure that you see the grid lines and stars in an area without a skybox.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f90e1aaa236cb0da12c3c29aa875123d1ca51fe3 available at: https://gist.github.com/a0941b63d17f61ddb57345a4ba4f753a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7724.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7724.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 (Nvidia GTX660M)
Stars generate proper with grid lines.  No changes seen to skyboxes once loaded, looks good to me.  QA Pass

**Pull request merged**
