### PR TITLE
MoCap wide stance fix for calibration

### PR DESCRIPTION
**Pull request by druiz17**
Fix the issue of avatars having a wide stance after performing a calibration.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- have vive trackers on your feet
- bring up the calibration UI
- have a configuration the has feet
- calibrate with feet together (check that everything looks ok)
- then calibrate with feet wide - check that your feet look ok

- note when performing the wide stance  calibration make sure your feet are pointing forward

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1033/HighFidelity-Beta-PR10793-c3b6b2ad5169b7470072e4fdf51c56db50c8c388.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1033/HighFidelity-Beta-PR10793-c3b6b2ad5169b7470072e4fdf51c56db50c8c388.dmg

**Comment by anshuman64** [comment]
This is great. Calibrating with feet together still results in a perfect 1:1 mapping of feet regardless of avatar.

**Pull request merged**
