### PR TITLE
[DNM] MS16303 - Adding Leap Motion gesture recognition

### PR DESCRIPTION
**Pull request by wayne-chen**
- Feature addition for MS[#16303](https://highfidelity.manuscript.com/f/cases/16303)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11586/HighFidelity-Beta-PR13697-6eb6860.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11586/HighFidelity-Beta-PR13697-6eb6860.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11586/HighFidelity-Beta-Interface-PR13697-6eb6860.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11586/HighFidelity-Beta-PR13697-6eb6860.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11586/HighFidelity-Beta-Interface-PR13697-6eb6860.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11738/HighFidelity-Beta-PR13697-30e8fe9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11738/HighFidelity-Beta-PR13697-30e8fe9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11738/HighFidelity-Beta-Interface-PR13697-30e8fe9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11738/HighFidelity-Beta-PR13697-30e8fe9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11738/HighFidelity-Beta-Interface-PR13697-30e8fe9.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
