### PR TITLE
Fix for crash bug in web entities

### PR DESCRIPTION
**Pull request by hyperlogic**
Guard against nullptrs in RenderableWebEntitItem and WebEntityAPIHelper. These pointers can go null if the webEntity is deleted on the main thread. Also, the backing offscreen qml surface can be destroyed if the webEntity has not been rendered for 30 seconds due to frustum culling.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1791/crash-in-OffscreenQmlSurface-getRootItem

**Comment by hyperlogic** [comment]
QA Test plan:
* In HMD mode, Create and destroy the marketplace tablet repeatedly.
* In HMD mode, turn away from marketplace tablet for more than 30 seconds, and then return to it.  It must be totally outside of your view. i.e. behind your head.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a79485f8c2bf84f0140b479959ffea2362a72b88 available at: https://gist.github.com/ef69c7dd6cda35df52a5d88566f3d271<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8703-a79485f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8703-a79485f.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  In HMD mode, created and destroyed the marketplace tablet repeatedly with no issue of any kind.  It immediately returned without any issue.  In HMD mode I was able to do that behavior with the mouse as the buttons on the Hydra did not trigger any of the menus to click however it did work with the mouse.  The issue with the Hydra I believe is unrelated to this PR.  In HMD mode, I successfully turned away from marketplace tablet for more than 30 seconds, and then returned to it. It was totally outside of my view.  Tested several 30 second increments and each time the table was present when I turned back around.   No issue of any kind.

**Comment by cozza13** [comment]
potential fail. if @hyperlogic thinks that the crash log it related to this PR. It may not be

**Comment by hyperlogic** [comment]
I looked at the [stack trace](https://www.bugsplat.com/individualCrash/?id=6205&database=interface_alpha), it doesn't seem to be related.  However, I'm not set up to investigate this further, I'll know more on monday when I look at the minidump.

**Comment by ZappoMan** [comment]
I am pretty sure this crash is not related to this PR...

I'm going to call this a QA Pass.

**Pull request merged**
