### PR TITLE
DONT LOOK AT ME

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85104b442f1a802f6833a47459ce127b1c2aa7bd available at: https://gist.github.com/0ec17a2cbc6afc6c192d9c9efc49c393<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9383-85104b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9383-85104b4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9fd86de47c60549b11434ae8d53933e11d01c486 available at: https://gist.github.com/0ec17a2cbc6afc6c192d9c9efc49c393<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9383-9fd86de.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9383-9fd86de.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested with HMD Oculus and Oculus Touch.  The wands or stylus wands integrated brilliantly with the new menu system that i was able to select by pressing B on the Touch.  The new menu system responded perfectly with the wands which in my opinion works more naturally than trying to use the narrow position beam that was often difficult on a menu system.  Tested the manipulation of items as well and that worked successfully as well as editing entities.

**Pull request closed without merging**
