### PR TITLE
add suppressions for log-spam caused by idle assignment-client

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 01cac7445a2cee96522e1dd180adf508a35ed40c available at: https://gist.github.com/e989c304f28a3893f5c6<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4354.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4354.dmg

**Comment by OmegaHeron** [comment]
There has to be a better way to handle this - now instead of the once per second message we get every 5 seconds in domain-server log/console.  Approx 400 characters (assuming written as single byte characters) every 5 seconds (24*60*60)/5= 17280 entries per 24 hours =  6,912,000 bytes saved to log files.

`[SUPPRESS] [02/27 14:04:30] 4 repeated log entries matching "Received a request for assignment type [^ ]+ from [^ ]+" - Last entry: "Received a request for assignment type 7 from 127.0.0.1:61150"`
`[DEBUG] [02/27 14:04:30] Received a request for assignment type 7 from 127.0.0.1:61150`
`[DEBUG] [02/27 14:04:30] Unable to fulfill assignment request of type 7 from 127.0.0.1:61150`

**Comment by sethalves** [comment]
Should we simply not log this stuff?

**Comment by OmegaHeron** [comment]
It seems overkill to log it - but there may be good reasons to do so I'm not catching.  I personally don't see the need to know I have spare AC processes hanging about with no work - unless I have more than -n # --min # --max # allow.

**Pull request merged**
