### PR TITLE
Android - Make sure we call Interface enterBackground when opening

### PR DESCRIPTION
**Pull request by Cristo86**
Test plan:
- Open Interface.  You should be brought to the Home screen.
- Go to a domain.  The UI (joystick, etc.) should render properly.
- Go back to Home and click on a different domain.  The UI should still render properly.
- Repeat a few times.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10433/HighFidelity-Beta-PR13330-2b0ac6a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10433/HighFidelity-Beta-PR13330-2b0ac6a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10433/HighFidelity-Beta-Interface-PR13330-2b0ac6a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10433/HighFidelity-Beta-PR13330-2b0ac6a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10433/HighFidelity-Beta-Interface-PR13330-2b0ac6a.exe

**Comment by SamGondelman** [comment]
@Cristo86 I've tested this and it seems to work, and I don't see any danger to it.  Let's get rid of the prints and merge it.

**Comment by Cristo86** [comment]
@SamGondelman Cool, logs removed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10490/HighFidelity-Beta-PR13330-26a9364.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10490/HighFidelity-Beta-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10490/HighFidelity-Beta-Interface-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10490/HighFidelity-Beta-PR13330-26a9364.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10490/HighFidelity-Beta-Interface-PR13330-26a9364.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10494/HighFidelity-Beta-PR13330-26a9364.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10494/HighFidelity-Beta-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10494/HighFidelity-Beta-Interface-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10494/HighFidelity-Beta-PR13330-26a9364.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10494/HighFidelity-Beta-Interface-PR13330-26a9364.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10583/HighFidelity-Beta-PR13330-26a9364.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10583/HighFidelity-Beta-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10583/HighFidelity-Beta-Interface-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10583/HighFidelity-Beta-PR13330-26a9364.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10583/HighFidelity-Beta-Interface-PR13330-26a9364.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10656/HighFidelity-Beta-PR13330-26a9364.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10656/HighFidelity-Beta-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10656/HighFidelity-Beta-Interface-PR13330-26a9364.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10656/HighFidelity-Beta-PR13330-26a9364.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10656/HighFidelity-Beta-Interface-PR13330-26a9364.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
UI Loads and looks good on all platforms.

**Pull request merged**
