### PR TITLE
Don't warn that recording didn't start playing if you stop it

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Make a recording and immediately it starts playing, stop it.
You should no longer get a warning dialog, "Didn't start playing recording".

**Comment by hifi-gustavo** [comment]
Build console output for commit: dd739d73a01d8d4a178c4a7659a04914262d9e28 available at: https://gist.github.com/bd8665d0d2f0085ff6793db59203028e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10347-dd739d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10347-dd739d7.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10347-dd739d7.exe

Pass:
- As a recording was happening, I clicked on the STOP button, to stop recording, a long beep occurred. Immediately I waited for the new recording to show up on the table. Once the file was displayed, I unloaded it before it got a chance to playback the recording. I also let the recording play for half a second before unloading the file. I repeated these steps several times, and never once received the "Didn't start playing recording" warning dialog.

**Pull request merged**
