### PR TITLE
8213 Keyboard Input Field: Reveals Passwords (RC-57)

### PR DESCRIPTION
**Pull request by ElderOrb**
Note: this is the same as https://github.com/highfidelity/hifi/pull/11582#pullrequestreview-69315904 but for RC-57 branch

*** Test Plan ***

Click "Login" on the tablet
Select the password field
Begin typing your password
before the changes: The password is revealed above the keyboard
after the changes: The password is shown as black dots

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4186/HighFidelity-Beta-PR11606-f83040c572249d9a823d7b3f50b8f8f043ddda13.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4186/HighFidelity-Beta-PR11606-f83040c572249d9a823d7b3f50b8f8f043ddda13.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Click "Login" on the tablet | Pass
Select the password field | Pass
Begin typing your password | Pass
before the changes: The password is revealed above the keyboard | Pass
after the changes: The password is shown as black dots | Pass

All good.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
