### PR TITLE
Address bar text area changes

### PR DESCRIPTION
**Pull request by howard-stearns**
display location and connection status in address bar when it doesn't have focus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dfc5ca268ee785055126e98e9c2c8c34173c292 available at: https://gist.github.com/44cbec46104d31dc8d9a39c2e5c826c8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8663-2dfc5ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8663-2dfc5ca.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2dfc5ca268ee785055126e98e9c2c8c34173c292 available at: https://gist.github.com/44cbec46104d31dc8d9a39c2e5c826c8<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8663-2dfc5ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8663-2dfc5ca.dmg

**Comment by howard-stearns** [comment]
test plan:
- When the address bar is brought up, it should not have keyboard focus. Clicking the text field should make the desktop cursor change to indicate input, and bring up the Vive keyboard for input.
- Clicking/triggering off the address bar should remove keyboard focus.
- Whenever the text field has keyboard focus, it should give you a prompt of what to enter.
- Whenever the text field does not have keyboard focus, it should tell you where you are, or are trying to be. If not connected to that location, it should tell you.  The location/connectivity message should update whenever the information is presented (when gaining and then losing focus, or when the address bar disappears/reappears when driving). However, it is not expected to update when just sitting there on display.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  When the address bar is brought up, it does not have keyboard focus.  When I clicked the text field it made the desktop cursor change to indicate input.  When i clicked off the address bar it removed keyboard event focus.  Whenever the text field has keyboard focus, it gave me a prompt of what to enter.  Whenever the text field does not have keyboard focus, it indicated my coordinates where I was. The location/connectivity message updates whenever the information is presented (when gaining and then losing focus, or when the address bar disappears/reappears when driving). Information does not change until you move your avatar to which it will update the coordinates of where the avatar is in addition to showing location info.

**Comment by Nex-Pro** [comment]
#### Pass 

I started testing this Before Kevin as posted in Slack.

**Pull request merged**
