### PR TITLE
Fix several styling/alignment/overlapping issues in 'Add to world' and 'Rename' dialogs in Asset Browser

### PR DESCRIPTION
**Pull request by ElderOrb**
image

### CODE REVIEW

**Comment by ElderOrb** [comment]
https://highfidelity.fogbugz.com/f/cases/13143/HMD-Add-to-World-page-of-Asset-Browser-misaligned

*** Test plan ***


1) Switch to VR:
2) Open the Asset Browser (ctrl+shift+A)
3) Choose a file that can be added to the world (FBX file , json) 
4) Once the file has been added to the asset browser select 'add to world'
5) Ensure page controls on page looks aligned and there is no overlapping
6) Click input field to get on-screen keyboard visible, ensure UI elements are still aligned/not overlapped
7) Repeat steps 2-6 for Desktop mode

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8104/app_12669_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8104/HighFidelity-Beta-PR12669-c2be4d4c0d6ab439d7bb3a667428b73bc06de896.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8104/HighFidelity-Beta-PR12669-c2be4d4c0d6ab439d7bb3a667428b73bc06de896.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8280/app_12669_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8280/HighFidelity-Beta-PR12669-c2be4d4c0d6ab439d7bb3a667428b73bc06de896.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8294/app_12669_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8294/HighFidelity-Beta-PR12669-c2be4d4c0d6ab439d7bb3a667428b73bc06de896.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8294/HighFidelity-Beta-PR12669-c2be4d4c0d6ab439d7bb3a667428b73bc06de896.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Stopped Testing

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - FAIL @conklin94122 

In HMD, the word 'Specifying' in the 'Specify Asset Path' instructional text spills outside of the menu. Log and screenshot attached.

pr12669screen

[PR12669hifi-log.txt](https://github.com/highfidelity/hifi/files/1872508/PR12669hifi-log.txt)

**Comment by ElderOrb** [comment]
Please recheck

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8574/app_12669_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8574/HighFidelity-Beta-PR12669-d5420e09f414fb458556df7f529462a6b7514011.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8574/HighFidelity-Beta-PR12669-d5420e09f414fb458556df7f529462a6b7514011.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8575/app_12669_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8575/HighFidelity-Beta-PR12669-25a44edfce2bd91241799e673376b880120ac8c8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8575/HighFidelity-Beta-PR12669-25a44edfce2bd91241799e673376b880120ac8c8.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No overlapping or weird text seen. We did notice the keyboard has a big gap at the top and almost no space at the bottom.
uploadimage

**Pull request merged**
