### PR TITLE
Beta Release 8 - including up to Development Release 4808

### PR DESCRIPTION
**Pull request by ZappoMan**
- installers named beta
- improve eye tracking when face to face
- installed scripts cleanup: tutorials, tools, default scripts
- fix auto-resize of models on import
- support for equi-rectangular skybox images
- fix bug in rendering Text3DOverlay
- fix bugs in placement and resizing of overlay windows
- position default toolbars on bottom of screen
- reset avatar tracking on exit from away mode
- fix crash during model loading
- fix memory leak in asset download
- fix avatar eye gaze in HMDs
- improve eye contact and saccade behavior

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b6bd02aea6bf090cd0a767ab7b02bafe9a9c2777 available at: https://gist.github.com/4673b51342849ebc19a6796ce2b05f14<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7778.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7778.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7778
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, music, cellscience
**Smoke Test Results:** Partially successful test.

                                  |localhost    
----------------------------------|----------|---------|-----------
Render Rate:                      |45.99         
Present Rate:                     |60.03          
Simrate:                          |47.00      
Render Stats Num Buffers:         |4482              
Render Stats gpu::Buffer Memory:  |36.0Mb         
Render Stats Num Textures:        |272              
Render Stats gpu::Texture Memory: |863.7Mb      
Render Stats Triangles:           |546k          
Render Stats Drawcalls:           |341               
Render Stats State Changes:	  |276             
Render Stats Items:               |326             
Render Stats Timing:              |20.3ms         
GPU-Z Memory Size                 |4096Mb         
GPU-Z Initial Memory		  |228Mb           
GPU-Z Memory Used		  |1940Mb         
GPU-Z Memory Load		  |23%       
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Partially successful test.  Successful execution of script and reverb dynamic worked when speaking into the mic however the UI did not load.  Log revealed the following - ```[04/28 06:30:14] [WARNING] [UncaughtException] ReferenceError: Can't find variable: Panel in file:///c:/program files/high fidelity - pr7778/scripts/developer/utilities/tools/reverbTest.js:42```.
**localhost ‘playaPerformanceTest.js’ Result:** Successful test.  Test results significantly beneath the red line.  Screen shot enclosed in attachments.
**Additional Test Results:** Failure upon attempt to teleport to ```music``` domain.  Failure to attempt to teleport to any additional domain either.  Upon typing the enter key, the UI loaded and allowed me to type a keyPress event into it however upon pressing enter to complete the teleport, the action failed and no behavior occurred.  Closed Interface successfully and re-logged.  Same behavior occurred.  Screen shot indicates such.  Attaching log for deeper analysis.
**Successful Logout/Crash:** Successful logout.
localhost performance
localhost 1
[hifi-log.txt](https://github.com/highfidelity/hifi/files/240323/hifi-log.txt)

**Comment by kevinmthomas-carpool** [comment]
Tested a second time.  Same behavior.  I can't teleport anywhere.  Attached log for deeper analysis.

@OmegaHeron are you seeing the same result?

[04/28 12:57:31] [DEBUG] Called LoadAddress with address  "sandbox"
[04/28 12:57:31] [DEBUG] Trying to go to URL "hifi://sandbox"
[04/28 12:57:31] [DEBUG] DEADLOCK WATCHDOG STATUS: lastHeartbeatAge: 966 elapsedMovingAverage: 3 maxElapsed: 3120721 maxElapsedAverage: 862 samples: 1037827
[04/28 12:57:32] [DEBUG] Total allocation  "328.81 MB"
[hifi-log.txt](https://github.com/highfidelity/hifi/files/241031/hifi-log.txt)

**Comment by RyanDowne** [comment]
Directory.js is still in the default scripts and it shouldn't be.

**Comment by RyanDowne** [comment]
Will current users have to delete those lines in interface.ini for the overlays to appear in the new location? Is there a way to avoid needing to do that?

**Comment by RyanDowne** [comment]
In RC8 when I run edit.js and look at the entities list, objects that are 'locked', don't have the locked icon showing. I think this is the same for the visible icon.

**Pull request closed without merging**
