### PR TITLE
Fix mini tablet JavaScript crash

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) Check that JavaScript crash no longer occurs:
- Desktop mode.
- Developer > Log window open.
- Grabbable entity nearby.
- Click on entity with mouse and move it.
- The following error should not be reported in the log:
    [UncaughtException signalHandlerException] Error: Result of expression 'ui' [null] is not an object. in file:///.../miniTablet.js:1009
    [Backtrace]
        onMessageReceived(channel = 'Hifi-Object-Manipulation', data = '...', localOnly = true) at file:///.../miniTablet.js:1009
        <global>() at -1

2) Check that you can grab items in HMD mode without the mini tablet displaying:
- HMD mode.
- Far-grab an entity. Turn your palm to face you. The mini tablet should not appear.
- Near-grab an entity. Turn your palm to face you. The mini tablet should not appear.
- Display the full-sized tablet and grab it. Turn your palm to face you. The mini tablet should not appear.

https://highfidelity.manuscript.com/f/cases/19761

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14795/HighFidelity-Beta-PR14357-629559e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14795/HighFidelity-Beta-PR14357-629559e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14795/HighFidelity-Beta-Interface-PR14357-629559e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14795/HighFidelity-Beta-PR14357-629559e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14795/HighFidelity-Beta-Interface-PR14357-629559e.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
