### PR TITLE
Include JSDoc Web pages in the install

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8809/app_12897_PR_06bb873e8d946ff456d11350b70b9fe99593edd9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8809/HighFidelity-Beta-PR12897-06bb873e8d946ff456d11350b70b9fe99593edd9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8809/HighFidelity-Beta-Interface-PR12897-06bb873e8d946ff456d11350b70b9fe99593edd9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8809/HighFidelity-Beta-PR12897-06bb873e8d946ff456d11350b70b9fe99593edd9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8809/HighFidelity-Beta-Interface-PR12897-06bb873e8d946ff456d11350b70b9fe99593edd9.exe

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Install each of the following builds:
- Windows 
- Windows client-only
- OSX
- OSX client-only

For each build, check that the JSDoc pages are available:
- Windows: C:\Program Files\High Fidelity - PR12897\jsdoc\index.html
- Windows: C:\Program Files\High Fidelity Interface - PR12897\jsdoc\index.html
- OSX: TODO

The index.html pages should display in a Web browser OK, with clickable items in a column on the right.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
html files appear and the local website works as expected.

**Pull request merged**
