### PR TITLE
Fix tablet home button highlight overlay dimensions

### PR DESCRIPTION
**Pull request by SamGondelman**
[FB9368](https://highfidelity.fogbugz.com/f/cases/9368)

The highlight overlay was not handling its dimensions properly.  The radii automatically scale with dimensions, so only the dimension needed to be changed, but circle overlays currently render at the wrong size ([FB9365](https://highfidelity.fogbugz.com/f/cases/9365)), so the dimensions were off.

Test plan:
- Hover over the tablet home button with the lasers or stylus.  It should highlight properly.
- Change size.  The size of the home button highlight should still be correct.  (The position might be slightly off sometimes, that is a separate bug)

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5031/HighFidelity-Beta-PR11837-b252c81d8484127119b682c6fe9102e2598c15f5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5031/HighFidelity-Beta-PR11837-b252c81d8484127119b682c6fe9102e2598c15f5.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Hover over the tablet home button with the lasers or stylus. It should highlight properly. | Pass
Change size. The size of the home button highlight should still be correct. (The position might be slightly off sometimes, that is a separate bug) | Pass

All good!

**Pull request merged**
