### PR TITLE
Don't do fade effect once physics kick in

### PR DESCRIPTION
**Pull request by SamGondelman**
Once physics have loaded, entities should not fade anymore.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ccca6d935faffc6f9f06f7613472d360fa68abeb available at: https://gist.github.com/15439329475e40255e5207719a2c2b74<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8429-ccca6d9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8429-ccca6d9.dmg

**Comment by ZappoMan** [comment]
**Test Plan:**
- regular smoke test
- verify that the entities fade is only happening when the domain is "still loading"
- verify that once "physics starts" -- e.g. the avatar is able to stand on the ground, then the fades stop happening.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Verified entity fade is only happening when the domain is "still loading".   Once the avatar is able to stand on the ground the fades stop happening.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |4653 |2270 |2018
**GPU Buffer Count**: |1015 |782 |494
**CPU Memory Usage**: |72101888 |30703616 |30969856
**GPU Memory Usage**: |28647424 |17641472 |20144128
**CPU Texture Count**: |255 |186 |198
**GPU Texture Count**: |902 |951 |1029
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |340060964 |220506712 |187408648
**GPU Texture Memory Usage**: |627008145 |553097425 |491531154
**GPU Virtual Memory Usage**: |798039313|724128593|662562322
**Triangle Count**: |527170 |613023 |128126
**Triangle Rate**: |32948125 |38313937 |8007875
**API Drawcall Count**: |261 |262 |81
**Drawcall Count**: |350 |259 |81
**Drawcall Rate**: |21875 |16187 |5062
**State Changes Texture Count**:|243 |257 |189
**Pipeline Count**: |35 |47 |29
**Item Opaques**: |290 |416 |9
**Item Translucents**: |16 |76 |67
**Item Lights**: |19 |78 |1
**Timing Opaques**: |840 |1136 |68
**Timing Translucents**: |22 |134 |212
**Timing Lighting**: |47 |61 |81
**Render Frame**: |1464 |2264 |751

**Pull request merged**
