### PR TITLE
Fix lasers going through tablet to drawInFrontOverlays

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
In particular, this fixes the laser going through to tablet to Create app edit handles behind the tablet.
Also makes the mouse pointer use the same code instead of its own.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14079/HighFidelity-Beta-PR14231-e339f96.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14079/HighFidelity-Beta-Interface-PR14231-e339f96.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14109/HighFidelity-Beta-PR14231-9b4c5e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14109/HighFidelity-Beta-Interface-PR14231-9b4c5e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14109/HighFidelity-Beta-PR14231-9b4c5e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14109/HighFidelity-Beta-Interface-PR14231-9b4c5e1.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14116/HighFidelity-Beta-PR14231-9b4c5e1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14116/HighFidelity-Beta-PR14231-9b4c5e1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14116/HighFidelity-Beta-Interface-PR14231-9b4c5e1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14116/HighFidelity-Beta-PR14231-9b4c5e1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14116/HighFidelity-Beta-Interface-PR14231-9b4c5e1.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 


image

**Pull request merged**
