### PR TITLE
Limits for alpha sliders in particle explorer

### PR DESCRIPTION
**Pull request by misslivirose**
Fixes the following manuscript case: 

https://highfidelity.fogbugz.com/f/cases/4518/Particle-system-values-unclear-whether-or-not-0-1-or-0-256-or-0-infinity

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9226/app_13012_PR_ef275485c0c40f15fd6fb662e609589f20329240.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9226/HighFidelity-Beta-PR13012-ef275485c0c40f15fd6fb662e609589f20329240.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9226/HighFidelity-Beta-Interface-PR13012-ef275485c0c40f15fd6fb662e609589f20329240.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9226/HighFidelity-Beta-PR13012-ef275485c0c40f15fd6fb662e609589f20329240.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9226/HighFidelity-Beta-Interface-PR13012-ef275485c0c40f15fd6fb662e609589f20329240.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
