### PR TITLE
TAA fix for highlight

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes a bug with the Highlight effect when TAA was enabled which could display a highly distracting flickering bug on objects highlighted with a fill color.

This fixes one of the bugs identified by _jyoum_ in [issue 15110](https://highfidelity.fogbugz.com/f/cases/15110/Users-reporting-blurring-issues-with-the-new-TAA-feature-desktop-and-HMD).

Bug 15122

# TEST PLAN
Use _hifi_tests\tests\engine\render\effect\highlight_. Filled highlights should be stable and shouldn't display any z-fighting type effect. This should also be checked on HMD.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9802/HighFidelity-Beta-PR13173-d10b5a16f291b860a0c213f1ad0636cf0b94f55b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9802/HighFidelity-Beta-Interface-PR13173-d10b5a16f291b860a0c213f1ad0636cf0b94f55b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9813/HighFidelity-Beta-PR13173-0941e02523e94af94971535e95d4103cd2ba877c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9813/HighFidelity-Beta-Interface-PR13173-0941e02523e94af94971535e95d4103cd2ba877c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9813/HighFidelity-Beta-PR13173-0941e02523e94af94971535e95d4103cd2ba877c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9813/HighFidelity-Beta-Interface-PR13173-0941e02523e94af94971535e95d4103cd2ba877c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No flickering when highlighting.

**Pull request merged**
