### PR TITLE
Switch to nvtt with no openmp dependency (remove vcomp140.dll dependency)

### PR DESCRIPTION
**Pull request by jherico**
RC 78 version of #14767

manuscript here https://highfidelity.manuscript.com/f/cases/20818/Missing-VCOMP140-dll

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16720/HighFidelity-Beta-PR14769-5f8e084.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16720/HighFidelity-Beta-PR14769-5f8e084.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16720/HighFidelity-Beta-PR14769-5f8e084.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16720/HighFidelity-Beta-Interface-PR14769-5f8e084.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
