### PR TITLE
Fix haze on Mac (bug #15515)

### PR DESCRIPTION
**Pull request by Zvork**
This PR fixes the haze that wasn't showing up on Mac, as desribed in [bug report #15515](https://highfidelity.fogbugz.com/f/cases/15515/Mac-Haze-does-not-appear-to-be-showing-up-on-Mac). It potentially could fix other haze issues on other platforms.

Also added two more GPU stats : frame buffer resolution and a per-pixel GPU frame timing to try to have a resolution free metric of GPU performance (stats are available by pressing the '/' key).

# TEST PLAN
Run all the tests/render/engine/effect/haze tests on Mac.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11125/HighFidelity-Beta-PR13544-d276384.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11125/HighFidelity-Beta-PR13544-d276384.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11125/HighFidelity-Beta-Interface-PR13544-d276384.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11161/HighFidelity-Beta-PR13544-74a6c25.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11161/HighFidelity-Beta-PR13544-74a6c25.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11161/HighFidelity-Beta-Interface-PR13544-74a6c25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11161/HighFidelity-Beta-PR13544-74a6c25.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11161/HighFidelity-Beta-Interface-PR13544-74a6c25.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11243/HighFidelity-Beta-PR13544-74a6c25.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11243/HighFidelity-Beta-PR13544-74a6c25.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11243/HighFidelity-Beta-Interface-PR13544-74a6c25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11243/HighFidelity-Beta-PR13544-74a6c25.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11243/HighFidelity-Beta-Interface-PR13544-74a6c25.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Haze looks good on Mac

**Pull request merged**
