### PR TITLE
Octree shared pointers

### PR DESCRIPTION
**Pull request by sethalves**
- Octree uses shared pointers.

### CODE REVIEW

**Comment by ZappoMan** [comment]
interesting... what's the goal of this PR? is there any change in functionality? What should the testing be? a thorough smoke test of the end to end system?

**Comment by sethalves** [comment]
It's changes pulled from a bigger project.  Hopefully there is no change in functionality.  I'd like to get this into master separately from the bigger project to break up the reviews into smaller parts.

**Comment by sethalves** [comment]
I'm going to rebase and reopen this PR

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6127a6455062245c53c8b838ec510a6cc86f0386 available at: https://gist.github.com/4105e0cd158d3e08e384<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5733.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5733.dmg

**Pull request closed without merging**
