### PR TITLE
remove highlight on entity when point to the sky (RC67)

### PR DESCRIPTION
**Pull request by druiz17**
Ticket - https://highfidelity.manuscript.com/f/cases/14896/Moving-laser-or-cursor-from-grabbable-object-to-the-sky-keeps-the-object-highlighted-temporarily

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- with laser or mouse point at an entity - entity should highlight
- then point at the sky (make sure you do not intersect other object) - the entity should unhighlight

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9580/app_13123_PR_a593209ec132ee828f454d6f505ee7ee9cc0ea38.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9580/HighFidelity-Beta-PR13123-a593209ec132ee828f454d6f505ee7ee9cc0ea38.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9580/HighFidelity-Beta-Interface-PR13123-a593209ec132ee828f454d6f505ee7ee9cc0ea38.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Object stops being highlighted once the cursors or laser is moved away from the object.

**Pull request merged**
