### PR TITLE
Build 42.1 Hotfix Update server-console to watch interface via pid rather than marker

### PR DESCRIPTION
**Pull request by cozza13**
Build 42.1 Hotfix Update server-console to watch interface via pid rather than marker

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/479/HighFidelity-Beta-PR10637-2146f96091a4b0462eb61d0ee3e33a47b72ee61d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/479/HighFidelity-Beta-PR10637-2146f96091a4b0462eb61d0ee3e33a47b72ee61d.dmg

**Comment by birarda** [comment]
To test:

-Run special test build of this PR from steam (@atlante45 has the details)
-Sandbox should start
-Close interface after 30 seconds
-Sandbox should close shortly thereafter

**Comment by Atlante45** [comment]
To get the PR build via Steam:
- Open Steam.
- Right click `High Fidelity` in your Library.
- Click on `Properties`.
- Select the `Betas` tab.
- Enter the following beta access code `c2cyX6Lu6Mt32t4P` and click `Check Code`.
- Select `test-build - Testing branch` for the drop down list.
- The PR build should start downloading.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
SUCCESS 

    Open Steam.
    Right click High Fidelity in your Library.
    Click on Properties.
    Select the Betas tab.
    Enter the following beta access code c2cyX6Lu6Mt32t4P and click Check Code.
    Select test-build - Testing branch for the drop down list.
    The PR build should start downloading.

success worked with @Atlante45 and verified each step

**Comment by kevinmthomasse** [comment]
-Run special test build of this PR from steam (@Atlante45 has the details)
-Sandbox should start
-Close interface after 30 seconds
-Sandbox should close shortly thereafter
SUCCESS

**Pull request merged**
