### PR TITLE
Orient particles to face camera but not roll with it

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2c7b3bcc9ff863ad8f361c6cdeb537cbd13dec0 available at: https://gist.github.com/e37ba0b9df8dde510ae5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5890.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5890.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a2c7b3bcc9ff863ad8f361c6cdeb537cbd13dec0 available at: https://gist.github.com/e37ba0b9df8dde510ae5<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5890.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5890.dmg

**Comment by cozza13** [comment]
I have tested and it looks good

**Pull request merged**
