### PR TITLE
Hands face emotes

### PR DESCRIPTION
**Pull request by dooglifeSF**
Hands and face gesture support using HMD controllers.

### CODE REVIEW

**Comment by hyperlogic** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17416/HighFidelity-Beta-PR14962-22e1b2f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17416/HighFidelity-Beta-PR14962-22e1b2f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17416/HighFidelity-Beta-Interface-PR14962-22e1b2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17416/HighFidelity-Beta-PR14962-22e1b2f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17416/HighFidelity-Beta-Interface-PR14962-22e1b2f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17433/HighFidelity-Beta-PR14962-c3ffd8d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17433/HighFidelity-Beta-PR14962-c3ffd8d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17433/HighFidelity-Beta-Interface-PR14962-c3ffd8d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17433/HighFidelity-Beta-PR14962-c3ffd8d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17433/HighFidelity-Beta-Interface-PR14962-c3ffd8d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17471/HighFidelity-Beta-PR14962-67a484b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17471/HighFidelity-Beta-PR14962-67a484b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17471/HighFidelity-Beta-Interface-PR14962-67a484b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17471/HighFidelity-Beta-PR14962-67a484b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17471/HighFidelity-Beta-Interface-PR14962-67a484b.exe

**Comment by dooglifeSF** [comment]
USAGE:  the hand gestures work by default with rift controllers.  Vive controllers haven't been test. 

To get the face emotes to trigger via controller as well, run the facialExpressions.js script in the script app's developer folder.  Thumb/Index/Grip inputs trigger face emotes.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17617/HighFidelity-Beta-PR14962-a1f9560.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17617/HighFidelity-Quest-Beta-PR14962-a1f9560.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17617/HighFidelity-Beta-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17617/HighFidelity-Beta-Interface-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17617/HighFidelity-Beta-PR14962-a1f9560.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17617/HighFidelity-Beta-Interface-PR14962-a1f9560.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18178/HighFidelity-Beta-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18178/HighFidelity-Beta-Interface-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18178/HighFidelity-Beta-PR14962-a1f9560.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18178/HighFidelity-Beta-Interface-PR14962-a1f9560.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18178/HighFidelity-Beta-PR14962-a1f9560.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18178/HighFidelity-Quest-Beta-PR14962-a1f9560.apk)

**Comment by dooglifeSF** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18574/HighFidelity-Beta-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18574/HighFidelity-Beta-Interface-PR14962-a1f9560.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18574/HighFidelity-Beta-PR14962-a1f9560.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18574/HighFidelity-Quest-Beta-PR14962-a1f9560.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18574/HighFidelity-Beta-PR14962-a1f9560.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18574/HighFidelity-Beta-Interface-PR14962-a1f9560.exe

**Comment by hyperlogic** [comment]
Closing this prototype

**Pull request closed without merging**
