### PR TITLE
Improved audio quality for streaming music

### PR DESCRIPTION
**Pull request by kencooke**
Streaming to the audio mixer requires resampling from the native rate to 24khz and back. As a result, high quality music can sound slightly dull. This PR increases resampling quality to preserve as much of the spectrum as possible (to 11.5khz). Because the filter is minimum-phase, there is no increase in audio latency.

### CODE REVIEW

**Comment by kencooke** [comment]
Transition band of the resampling filter is shown below.
src_kernel_128

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7962/app_12619_PR.apk

**Comment by kencooke** [comment]
### Test Plan

1) With Interface from this PR, verify that audio sounds clean as before. NOTE: The added brightness is very subtle and not noticeable on voices.
2) Open the JS console (ctrl-alt-J) and load a music clip. For example, you can type:
```sound = SoundCache.getSound("http://hifi-content.s3.amazonaws.com/ken/samples/Brahms_ambiX.wav");```
Wait a few seconds for it to finish loading, then play the sound with:
```Audio.playSound(sound);```
Verify that it sounds very clean.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7962/HighFidelity-Beta-PR12619-c06d28ee5fae9c69f1ebd558252fd878721e9fa1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7962/HighFidelity-Beta-PR12619-c06d28ee5fae9c69f1ebd558252fd878721e9fa1.exe

**Comment by conklin94122** [comment]
@kencooke Needs milestone

**Comment by qlimnavarro** [comment]
Currently testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Audio sounds crisp and clean.

**Comment by conklin94122** [comment]
@kencooke Needs dev review

**Pull request merged**
