### PR TITLE
Add location.domainID as a synonym for location.domainId

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
And deprecate location.domainId.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Run the attached script. Check its output is as per comments in the script.

2) Check the following scripts which have been updated with location.domainID:
- pal.js - i.e. "People" app.
- snapshot.js - i.e., "Snap" app.

3) Check that the PR's Sandbox works.

[test21729.zip](https://github.com/highfidelity/hifi/files/1676738/test21729.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6706/app_12288_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6706/HighFidelity-Beta-PR12288-280264d7edec00af0dd7309fca5ad6937287920a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6706/HighFidelity-Beta-PR12288-280264d7edec00af0dd7309fca5ad6937287920a.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
