### PR TITLE
DEV-444 - OAuth administration improvements

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.atlassian.net/browse/DEV-444

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21245/HighFidelity-Beta-PR16173-a0ad1f3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21245/HighFidelity-Quest-Beta-PR16173-a0ad1f3.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21245/HighFidelity-Beta-PR16173-a0ad1f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21245/HighFidelity-Beta-Interface-PR16173-a0ad1f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21245/HighFidelity-Beta-PR16173-a0ad1f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21245/HighFidelity-Beta-Interface-PR16173-a0ad1f3.exe

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21264/HighFidelity-Beta-PR16173-0f242de.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21264/HighFidelity-Quest-Beta-PR16173-0f242de.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21264/HighFidelity-Beta-PR16173-0f242de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21264/HighFidelity-Beta-Interface-PR16173-0f242de.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21269/HighFidelity-Beta-PR16173-4a4f86d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21269/HighFidelity-Quest-Beta-PR16173-4a4f86d.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21276/HighFidelity-Beta-PR16173-9a7de10.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21276/HighFidelity-Quest-Beta-PR16173-9a7de10.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21276/HighFidelity-Beta-PR16173-9a7de10.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21276/HighFidelity-Beta-Interface-PR16173-9a7de10.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21282/HighFidelity-Beta-PR16173-9a7de10.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21282/HighFidelity-Quest-Beta-PR16173-9a7de10.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21282/HighFidelity-Beta-PR16173-9a7de10.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21282/HighFidelity-Beta-Interface-PR16173-9a7de10.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21282/HighFidelity-Beta-PR16173-9a7de10.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21282/HighFidelity-Beta-Interface-PR16173-9a7de10.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21337/HighFidelity-Beta-PR16173-ac472a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21337/HighFidelity-Beta-Interface-PR16173-ac472a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21337/HighFidelity-Beta-PR16173-ac472a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21337/HighFidelity-Beta-Interface-PR16173-ac472a5.exe

**Comment by JeffClinton** [comment]
Pre-merge testing complete. QA approved for merge.

Able to:
Enable OAuth
Verify validation errors
Configure OAuth
Edit permissions
And migrate from 2.3

**Pull request merged**
