### PR TITLE
Fix Goto app clicks not working

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Includes better card highlighting fix.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Goto app.
Test desktop and HMD.

A) Check that each card type can be clicked.

B) Check that a card's highlight doesn't stick.
- GOTO app.
- Mouse over a place or a snap image. The place or snap's rectangle highlights.
- Click down and drag horizontally to move the list.
- Keep holding mouse down and move cursor horizontally off the dialog then release the mouse. The place or snap's rectangle should not be highlighted.
- Repeat but this time click the left-most item and release the mouse when the cursor is not quite off the dialog. The original place or snap's rectangle should not be highlighted. And if the cursor ends up over another place or snap rectangle, that snap or rectangle should be highlighted.
- Repeat but this time release the mouse when the cursor is still over the original place or snap. The original place or snap's rectangle shouild end up highlighted.
- Test the above with different grab points on the card: near the left, the center, and near the right side of cards.

C) General test of the Goto app.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15136/HighFidelity-Beta-PR14395-010f712.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15136/HighFidelity-Beta-PR14395-010f712.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15136/HighFidelity-Beta-Interface-PR14395-010f712.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15136/HighFidelity-Beta-PR14395-010f712.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15136/HighFidelity-Beta-Interface-PR14395-010f712.exe

**Comment by qliejahner** [comment]
FAIL @conklin94122 
Also blocked: HMD testing cannot be done due to MS19873

When the mouse is released, and the tile which was clicked and dragged remains under the mouse, it does not highlight. This does not occur in master.


[hifi-log.txt](https://github.com/highfidelity/hifi/files/2581839/hifi-log.txt)

However, unlike master, GoTo is fully functional (in desktop mode).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15161/HighFidelity-Beta-PR14395-9c5d318.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15161/HighFidelity-Beta-Interface-PR14395-9c5d318.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15161/HighFidelity-Beta-PR14395-9c5d318.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15161/HighFidelity-Beta-Interface-PR14395-9c5d318.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
Paused testing, need #14401 to be merged to test HMD

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15168/HighFidelity-Beta-PR14395-9c5d318.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15168/HighFidelity-Beta-PR14395-9c5d318.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15168/HighFidelity-Beta-Interface-PR14395-9c5d318.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15178/HighFidelity-Beta-PR14395-9c5d318.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15178/HighFidelity-Beta-Interface-PR14395-9c5d318.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15178/HighFidelity-Beta-PR14395-9c5d318.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15178/HighFidelity-Beta-Interface-PR14395-9c5d318.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

GoTo in both desktop and VR functioned, and highlighting did not stick.

**Pull request merged**
