### PR TITLE
Fix entity list search case-sensitivity and allow id search

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.manuscript.com/f/cases/18386 (new since RC72)

Test Plan:
- Enter Interface in desktop mode in a domain with as many different entity types as possible
- Open Create and search with the different entity type names using both uppercase and lowercase for the first letter as well as other letters
- Verify search terms are not case-sensitive and expected matching results are shown
- Search with other queries of names, file paths, and entity IDs with varying uppercase vs lowercase
- Verify search terms are not case-sensitive, that entity IDs are valid search terms, and expected matching results are shown

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12980/HighFidelity-Beta-PR13992-4bc0461.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12980/HighFidelity-Beta-PR13992-4bc0461.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12980/HighFidelity-Beta-Interface-PR13992-4bc0461.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12991/HighFidelity-Beta-PR13992-b65bd67.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12991/HighFidelity-Beta-PR13992-b65bd67.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12991/HighFidelity-Beta-Interface-PR13992-b65bd67.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12991/HighFidelity-Beta-PR13992-b65bd67.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12991/HighFidelity-Beta-Interface-PR13992-b65bd67.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12994/HighFidelity-Beta-PR13992-f9480c2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12994/HighFidelity-Beta-Interface-PR13992-f9480c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12994/HighFidelity-Beta-PR13992-f9480c2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12994/HighFidelity-Beta-Interface-PR13992-f9480c2.exe

**Comment by thoys** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12999/HighFidelity-Beta-PR13992-f9480c2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12999/HighFidelity-Beta-PR13992-f9480c2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12999/HighFidelity-Beta-Interface-PR13992-f9480c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12999/HighFidelity-Beta-PR13992-f9480c2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12999/HighFidelity-Beta-Interface-PR13992-f9480c2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13003/HighFidelity-Beta-PR13992-296e2ba.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13003/HighFidelity-Beta-PR13992-296e2ba.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13003/HighFidelity-Beta-Interface-PR13992-296e2ba.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13003/HighFidelity-Beta-PR13992-296e2ba.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13003/HighFidelity-Beta-Interface-PR13992-296e2ba.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

User is able to type search terms into the search bar and populate the correct results by ignoring case-sensitivity

**Pull request merged**
