### PR TITLE
simple Render Engine refactors coming from the Spectator Cam project

### PR DESCRIPTION
**Pull request by samcake**
This PR simply reorganize the code for the main frame rendering task in a more integrated one.
THis is work that we learned from the spectatro project and that we want to bring over to master.

There is also a little nice fix.... shadows are now working in the HMD.

## TEST PLAN

THe rendering behavior should work normally
Turning on and off the Graphics settings (ao, shadow) should behave normally (resume correctly on the next sessions).

Shadows are now working in hmd...

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/565/HighFidelity-Beta-PR10659-bb389385341bb4bc90a43b3348801de9c9459289.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete: 

I can confirm everything in the test plan works perfectly, however, I would like to point out the Cancel button does not seem to function on the graphics menu, whether this is already known or not i'm not sure.


**Pass**

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/568/HighFidelity-Beta-PR10659-bb389385341bb4bc90a43b3348801de9c9459289.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/568/HighFidelity-Beta-PR10659-bb389385341bb4bc90a43b3348801de9c9459289.dmg

**Pull request merged**
