### PR TITLE
404 malformed agent script requests

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11409/HighFidelity-Beta-PR13640-499aa4a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11409/HighFidelity-Beta-PR13640-499aa4a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11409/HighFidelity-Beta-Interface-PR13640-499aa4a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11409/HighFidelity-Beta-PR13640-499aa4a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11409/HighFidelity-Beta-Interface-PR13640-499aa4a.dmg

**Comment by birarda** [comment]
We will just merge this to master if #13639 passes QA

**Pull request merged**
