### PR TITLE
Build openvr plugin on linux

### PR DESCRIPTION
**Pull request by Codes4Fun**
This fixes compiling issues and disables windows specific code in the openvr plugin with a linux target, and adds support to the openvr vcpkg for linux #10098 . Modified build instruction as solution for #15826 and to build faster.

The vcpkg CONTROL files while they support '&' for triplets they do not support '|'. I verified this in their source code. So 'openvr (windows|linux)' would not work, instead it worked to just have both 'openvr (windows), openvr (linux)'.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20269/HighFidelity-Beta-PR15885-4b438d3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20269/HighFidelity-Quest-Beta-PR15885-4b438d3.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20269/HighFidelity-Beta-PR15885-4b438d3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20269/HighFidelity-Beta-Interface-PR15885-4b438d3.exe

**Comment by ZappoMan** [comment]
Build related failures:

### *On MacOS*
```
08:02:56 CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
08:02:56 Please set them or make sure they are set and tested correctly in the CMake files:
08:02:56 OPENVR_LIBRARY
08:02:56     linked by target "openvr" in directory /Users/jenkins/Jenkins/workspace/pr-build/label/macos/plugins/openvr
08:02:56 
08:02:56 -- Configuring incomplete, errors occurred!
```

### *On Ubuntu*
```

OpenVrHelpers.h:79 | build/plugins/openvr/openvr_autogen/UVLADIE3JM/../../../../../plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:sign-compare
-- | -- | -- | -- | --
OpenVrHelpers.h:90 | build/plugins/openvr/openvr_autogen/UVLADIE3JM/../../../../../plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:sign-compare
ViveControllerManager.h:55 | build/plugins/openvr/openvr_autogen/UVLADIE3JM/../../../../../plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:suggest-override
OpenVrHelpers.cpp:408 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-result
OpenVrHelpers.h:79 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:sign-compare
OpenVrHelpers.h:90 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:sign-compare
ViveControllerManager.cpp:46 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-variable
ViveControllerManager.cpp:49 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-variable
ViveControllerManager.cpp:50 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-variable
ViveControllerManager.cpp:51 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-variable
ViveControllerManager.cpp:117 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-function
ViveControllerManager.cpp:373 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:sign-compare
ViveControllerManager.cpp:448 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:449 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:458 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:459 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:493 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:494 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:double-promotion
ViveControllerManager.cpp:711 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-but-set-variable
ViveControllerManager.cpp:712 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-but-set-variable
ViveControllerManager.cpp:810 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:unused-variable
ViveControllerManager.h:55 | plugins/openvr/src | Normal | GNU C Compiler 4 (gcc) | Warning:suggest-override

```

**Comment by Codes4Fun** [comment]
build this please

**Comment by Codes4Fun** [comment]
So the UNIX target includes MacOS, so I modified it to target only windows and linux. I verified it still builds both windows and linux, and it should now not produce an error for MacOS.

**Comment by Codes4Fun** [comment]
The warning I don't think are a big deal there all benign, and I was thinking those can be cleaned up later when/if the openvr plugin is updated to use steamvr's new VRInput, action manifests files, to get better index controller support... I was looking into doing that myself if no one else is trying to get index controllers working?

**Comment by ZappoMan** [comment]
@Codes4Fun 

We have a strict no warnings policy on the code base. All compilers are set to treat warnings as errors.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20303/HighFidelity-Beta-PR15885-1bb4abd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20303/HighFidelity-Beta-Interface-PR15885-1bb4abd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20303/HighFidelity-Beta-PR15885-1bb4abd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20303/HighFidelity-Beta-Interface-PR15885-1bb4abd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20303/HighFidelity-Beta-PR15885-1bb4abd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20303/HighFidelity-Quest-Beta-PR15885-1bb4abd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20327/HighFidelity-Beta-PR15885-e64a7bb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20327/HighFidelity-Beta-Interface-PR15885-e64a7bb.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20327/HighFidelity-Beta-PR15885-e64a7bb.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20327/HighFidelity-Quest-Beta-PR15885-e64a7bb.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20327/HighFidelity-Beta-PR15885-e64a7bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20327/HighFidelity-Beta-Interface-PR15885-e64a7bb.dmg

**Pull request closed without merging**
