### PR TITLE
Remove a line of old code in Clara.io download

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing: Downloading models from Clara.io should still work (desktop and HMD).

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1fe908380642b73c1601f764943e5a235376def available at: https://gist.github.com/5131e8ddf76ef0c68512017bbc444f64<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9402-a1fe908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9402-a1fe908.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a1fe908380642b73c1601f764943e5a235376def available at: https://gist.github.com/5131e8ddf76ef0c68512017bbc444f64<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9402-a1fe908.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9402-a1fe908.dmg

**Comment by Nex-Pro** [comment]
It is possible to download a model from Clara.io in both HMD and desktop which is what this PR is about.

However I crashed at least 4 times each time while attempting to download a model from Clara.io. 
Splats submitted

This may be due to bad models. Bad fbx parsing or just bad luck that I chose more bad models than good.

Laser interaction with the tablet was poor with the right hand laser often falling short as if hitting something. ( might be due to the avatar ) 
When lasers were working it seemed hit or miss whether or not some trigger input would have an effect on dragging the page, the scroll bars or hitting a button.

Also the first page of Markets  only shows the high fidelity marketplace and one has to observe the fact that there is a scroll bar on the right to deduce that one should drag the page or scroll bar. This is not part of this PR but is bad design.

hifi-snap-by-piper-peppercorn-on-2017-01-17_15-54-38

**Comment by Nex-Pro** [comment]
Tested win 10 desktop and HTC Vive. ^

**Comment by ctrlaltdavid** [comment]
You can download from Clara.io in both desktop and HMD? ... Yes.

Does it crash more often than without this code change? ... I'm not getting crashes, with the particular models I've tried.

Laser interactions and UI aren't addressed by this PR.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid "Laser interactions and UI aren't addressed by this PR." Covered that in the first line of my comment. Rest was jsut what happened.

**Comment by Nex-Pro** [comment]
@ctrlaltdavid  Yes I could download in HMD and desktop.

**Pull request merged**
