### PR TITLE
Fix heap alignment of MyAvatar

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes the following Windows build warning:
warning C4316: 'MyAvatar' : object allocated on the heap may not be aligned 16

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8915d9ae6df8686727520d567134f9a155166de available at: https://gist.github.com/bfe12ac380957ae95c21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4953.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4953.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 97d2732c858347fae7e41ebcef7644afc56e770d available at: https://gist.github.com/bfe12ac380957ae95c21<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4953.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4953.dmg

**Comment by AndrewMeadows** [comment]
@samcake, you're more window-centric than the rest of us.  Could you please review this PR and merge if it looks good to you?

**Comment by samcake** [comment]
Will do

**Comment by samcake** [comment]
SO after investigating the question, we think it might be better to just make the DynamicCharacterController a pointer because we beleive it's the one that gets its alignment enforced on 16 because it comes from Bullit.
By making it a pointed member and not one per value, we avoid that constraint of alignement to apply to MyAvatar anymore

Finally the reasoning for not being in favor of a platform specific new and delete for MyAvatar is because it would be platform specific...

Cheers

**Comment by AndrewMeadows** [comment]
@ctrlaltdavid, yes we've decided to not accept this PR because we want to fix it a different way, but thanks for submitting this as a possible solution -- closing all warnings is a goal that we support.  The track we'll take is to make **MyAvatar** keep a pointer to its **DynamicCharacterController**.  The default responsibility for this work falls to me, since I added DynamicCharacterController, but if you'd like to take a swing at it then you're welcome to it, just let me know.

**Pull request closed without merging**
