### PR TITLE
grab script bumper is an equip toggle

### PR DESCRIPTION
**Pull request by sethalves**
- grab script uses trigger for grab and bumper as "equip item" toggle

### CODE REVIEW

**Comment by sethalves** [comment]
I think something may be blowing away userData's grabbableKey sometimes.  I'll need to figure that out before this is ready.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b062d23f612e780abee293bf5483d53a2b5ade33 available at: https://gist.github.com/bab1f63e028ea206e142<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d21a2fee203b087d952bd6f76696668978a175ff available at: https://gist.github.com/bab1f63e028ea206e142<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c6051bb3253234113d2323b9ca328e810b1a0bfc available at: https://gist.github.com/bab1f63e028ea206e142<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ae3c5aea0429014863b018550a0137616540d2b available at: https://gist.github.com/bab1f63e028ea206e142<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.dmg

**Comment by imgntn** [comment]
so far so good on my testing with blocks and in demo; haven't really tried stuff with spatialkeys yet -- we should get some more testing on this before merging.  it also makes me want to do invertSolidWhileHeld:true by default for most things you equip

**Comment by imgntn** [comment]
and one observation is that the far grab with the bumper feels broken, since it only works with stuff with spatialkeys.  so you get the beams going through stuff with no result @PhilipRosedale

**Comment by hifi-gustavo** [comment]
Build console output for commit: 94f18672d42ac8db2e5617605ffd85d1e62d3432 available at: https://gist.github.com/bab1f63e028ea206e142<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6402.dmg

**Comment by PhilipRosedale** [comment]
tested, windows and mac

**Pull request merged**
