### PR TITLE
Update dice location in toybox

### PR DESCRIPTION
**Pull request by imgntn**
This PR updates the location of the dice in toybox.  

To test, run this in toybox (then you can click the reset entities, etc).  Observe the dice at their new location.
https://raw.githubusercontent.com/imgntn/hifi/dicelocation/unpublishedScripts/immediateClientReset.js

Please make sure to re-run the original script when finished!!!
https://raw.githubusercontent.com/highfidelity/hifi/master/unpublishedScripts/immediateClientReset.js

https://app.asana.com/0/46580934041217/84142451666177

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64cb053c161da00d3f2ca483b0925cbe834207ea available at: https://gist.github.com/a7391893249977d30f73<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6941.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6941.dmg

**Comment by nbq** [comment]
Plan to test this one momentarily

**Comment by nbq** [comment]
I have tested the first script and it creates this horribly scratchy sound that lingers, the position did seem to reset though. I ran the resetter script back to its original position but something makes a HORRIBLE sound like a record skipping

**Comment by cozza13** [comment]
Thanks @nbq , the scratchy sound is something else. I am moving this to QA approved

**Pull request merged**
