### PR TITLE
adding python baking scripts

### PR DESCRIPTION
**Pull request by druiz17**
I am adding some python script tools that will bake all the FBX files in a directory and output them in a directory of your choosing. Another file that will replace the urls in the models.json file to relative to the directory you specify.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8258/app_12706_PR.apk

**Comment by druiz17** [comment]
Test plan
- build the oven tool
- set the environment variable HIFI_OVEN to be the oven executable.
- using the hifi-tutorial directory 
- use bake.py to bake a the src directory 
- use the convertToRelativePaths.py on the models.json file to update urls paths.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8258/HighFidelity-Beta-PR12706-0c6f5bb04d525c7649469517492835a05bcf959a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8258/HighFidelity-Beta-PR12706-0c6f5bb04d525c7649469517492835a05bcf959a.exe

**Comment by sethalves** [comment]
These scripts are for use by people packaging up serverless-domains.  There's no change to code that users run, so I'm going to skip QA on this one.

**Pull request merged**
