### PR TITLE
fix STUN failover for offline machines

### PR DESCRIPTION
**Pull request by birarda**
- fix for STUN failover when machine is not connected to the internet

### CODE REVIEW

**Comment by birarda** [comment]
On current release, you should not be able to run a local stack when not connected to the internet since your local ACs will fail to connect to the DS. That is fixed with these changes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6ba8dd8e54f4d9262254ef43ba5d5808bbfe08e available at: https://gist.github.com/5f6bbeb4da2e2463c851<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7088.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7088.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a6ba8dd8e54f4d9262254ef43ba5d5808bbfe08e available at: https://gist.github.com/5f6bbeb4da2e2463c851<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7088.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7088.dmg

**Comment by bluetoe** [comment]
I just tried this and seemed to work but, when I plugged back in network cable and tried to go to sandbox I crashed.. but It might have been a different issue.

So: I tried it.. went to local host and the non internet assets loaded. As in boxes, spheres etc. I don't happen to have any ATP stuff on the local domain so I don't know it that works but everything else seems to have.

**Comment by Triplelexx** [comment]
Connection to DS without internet works for me.

**Pull request merged**
