### PR TITLE
Gabriel Calero's fix (78.0)

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
Fix Android build

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16621/HighFidelity-Beta-PR14754-54f6635.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16621/HighFidelity-Beta-PR14754-54f6635.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16621/HighFidelity-Beta-Interface-PR14754-54f6635.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16621/HighFidelity-Beta-PR14754-54f6635.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16621/HighFidelity-Beta-Interface-PR14754-54f6635.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16626/HighFidelity-Beta-PR14754-54f6635.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16626/HighFidelity-Beta-PR14754-54f6635.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16626/HighFidelity-Beta-Interface-PR14754-54f6635.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16626/HighFidelity-Beta-PR14754-54f6635.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16626/HighFidelity-Beta-Interface-PR14754-54f6635.exe

**Pull request merged**
