### PR TITLE
Allow empty web entities to be rendered

### PR DESCRIPTION
**Pull request by dback2**
If a web entity is added via script, the sourceUrl for it can be set to empty, which makes it's content type ContentType::NoContent. With this content type the entity was previously invisible, so this allows it to be rendered as an empty white panel in this case.

Fixes: https://highfidelity.manuscript.com/f/cases/15963

Test Plan:
- Enter Interface in desktop mode
- Open Create and create a Web entity
- Verify the web entity is visible and shows the High Fidelity site by default
- On the Properties tab, change the source URL to any other website like http://google.com and verify it is shown as expected
- Change the source URL to a single letter, verify once clicking away from the source URL box that the http:// is amended to the single letter, and verify the Web entity shows the site can't be reached
- In Developer menu -> Console enter the following line and press Enter:
Entities.addEntity({ type : "Web", sourceUrl : "", position: MyAvatar.position, dimensions: {x:1.6, y:0.9, z:0.01}});
- Verify the new Web entity is a blank white panel on both sides
- In the Properties tab for the new Web entity, change the source URL to a website like http://google.com and verify it is shown as expected
- Change the source URL for the new Web entity to a single letter, verify once clicking away from the source URL box that the http:// is amended to the single letter, and verify the Web entity shows the site can't be reached

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11228/HighFidelity-Beta-PR13577-878a78f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11228/HighFidelity-Beta-PR13577-878a78f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11228/HighFidelity-Beta-Interface-PR13577-878a78f.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11228/HighFidelity-Beta-Interface-PR13577-878a78f.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qligmaloney** [comment]
Build this please

**Comment by qlimnavarro** [comment]
Build this please

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11550/HighFidelity-Beta-PR13577-878a78f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11550/HighFidelity-Beta-PR13577-878a78f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11550/HighFidelity-Beta-Interface-PR13577-878a78f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11550/HighFidelity-Beta-PR13577-878a78f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11550/HighFidelity-Beta-Interface-PR13577-878a78f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Web entity looks good.

**Pull request merged**
