### PR TITLE
fix scaling of worn shape entities

### PR DESCRIPTION
**Pull request by sethalves**
- fix scaling of worn shape entities

https://highfidelity.fogbugz.com/f/cases/17489/Parented-shape-type-avatar-entities-are-scaling-wrong

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open the console and run this:
```javascript
Entities.addEntity({
  type: "Sphere",
  localPosition: { x: 0, y: 0.2, z: 1 },
  dimensions: { x: 0.5, y: 0.5, z: 0.5 },
  collisionless: true,
  name: "sphere",
  parentID: MyAvatar.sessionUUID,
  parentJointIndex: MyAvatar.getJointIndex("Head") > -1 ? MyAvatar.getJointIndex("Head") : MyAvatar.getJointIndex("head"),
}, true);
```
- use the AvatarApp to change the size of your avatar
- note that the sphere scales with the avatar
- use CREATE to create spheres and change their dimensions.  look for anything unexpected.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13030/HighFidelity-Beta-PR14009-1e8ae1a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13030/HighFidelity-Beta-PR14009-1e8ae1a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13030/HighFidelity-Beta-Interface-PR14009-1e8ae1a.dmg

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13236/HighFidelity-Beta-PR14009-1e8ae1a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13236/HighFidelity-Beta-Interface-PR14009-1e8ae1a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13236/HighFidelity-Beta-PR14009-1e8ae1a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13236/HighFidelity-Beta-Interface-PR14009-1e8ae1a.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
PASS @conklin94122 

The attached entity scales appropriately with avatar size.

**Pull request merged**
