### PR TITLE
21458 - Fix Shortbow

### PR DESCRIPTION
**Pull request by MiladNazeri**
Fix Shortbow
- Created didRootPositionMove and checkRootPosition in
shortbowGameManager to handle updating spawn positions if board is moved
during game play

- Created for functions for creating and deleting bows and enemy spawn
positions

- Fixed lives check

- Fixed error causing pieces to fall off board.  This was being caused
by a jump in velocity during a random time which was interfering with
where the entity was being redrawn

- Added a try/catch in handControllerGrab.js to fix problem with trying
to get properties from cache that were being deleted when too many
arrows at one time were being thrown.

Test Plan : 
For Section 1 :
-------------------------------------------------------------
Re:
1) Laser/stylus become unusable
Steps to reproduce:
1) Get the bow from the marketplace
2) When you first get it, the laser/stylus works, you can drop it and use the grip or trigger to pick it up with either hand
3) Very rapidly shoot multiple arrows (I think I did around 10) in the same general direction--I didn't even bother pulling back all the way
-------------------------------------------------------------
- If you are able to shoot multiple arrows as fast as you can shoot, then this problem should be fixed. 

My computer was giving me issues at first around 7-10 but the number would change depending on system resources available. 

For Section 2:
-------------------------------------------------------------
Re:

2) Stops spawning balls and bows
Steps to reproduce:
1) Go to marketplace and add the shortbow game to your domain
2) Hit play
3) Enter Create/edit mode and move the game 

The spawn points don't move with the game. For some shortbow games the balls spawn, behind the avatar shop instead of in the pit and will freely roll anywhere in the domain. Since the game itself is not a locked asset, this is probably from it getting moved after being placed the first time. However, no balls spawned and the start sign failed to appear after wave 10, so it may be losing the ability to keep track of how many balls are still present.
-------------------------------------------------------------

- run spawnShortBow.js
- Most of this problem had to do with the randomized jump on the enemy balls after being initiated too quickly after spawning.  There seems to be a general problem related to disappearing models when Entities.getEntityProperties get called. 
- Moving the board around while playing should reset the wave and spawn positions
- No balls should be outside of the play area
- Lives should be tracking fine despite the wave number.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2723/HighFidelity-Beta-PR11239-2446fd002f575815a0a1ee421e09c10d85bdedc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2723/HighFidelity-Beta-PR11239-2446fd002f575815a0a1ee421e09c10d85bdedc6.exe

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
## FAIL with some successes.

### Section 1 :

Laser/stylus become unusable
Steps to reproduce:
Get the bow from the marketplace
When you first get it, the laser/stylus works, you can drop it and use the grip or trigger to pick it up with either hand
Very rapidly shoot multiple arrows (I think I did around 10) in the same general direction--I didn't even bother pulling back all the way

**PASS: Rapidly shot dozens of arrows. Lasers and stylii continued to work after dropping bow.**

Sometimes arrows get stuck at the bow.
hifi-snap-by--on-2017-08-29_11-37-19

hifi-snap-by--on-2017-08-29_11-03-03



### Section 2:

Re:

Stops spawning balls and bows
Steps to reproduce:
Go to marketplace and add the shortbow game to your domain
Hit play
Enter Create/edit mode and move the game
The spawn points don't move with the game. For some shortbow games the balls spawn, behind the avatar shop instead of in the pit and will freely roll anywhere in the domain. Since the game itself is not a locked asset, this is probably from it getting moved after being placed the first time. However, no balls spawned and the start sign failed to appear after wave 10, so it may be losing the ability to keep track of how many balls are still present.

run spawnShortBow.js
Most of this problem had to do with the randomized jump on the enemy balls after being initiated too quickly after spawning. There seems to be a general problem related to disappearing models when Entities.getEntityProperties get called.
Moving the board around while playing should reset the wave and spawn positions: **FAIL** Did not reset the wave.
No balls should be outside of the play area: **PASS**
Lives should be tracking fine despite the wave number. **Moving the castle walls can prevent lives being lost. Ok if the Parent is moved.**

Disappearing enemies still a problem.
Often the enemies would simply disappear for no apparent reason.

After level 15 arrows would often bounce off the enemy. Enemies and arrows would react as if a simple physical collision had occurred. This may happen with several arrow hits on any particular enemy entity.

Dancing arrows would litter the play area after they bounced off enemies.

On many occasions I could see the green bounding box for missing ents. This would persist for several seconds before the enemy entity appeared.

Achieved level 20 when I got beat attempting to grab a screenshot.

After moving the main castle a couple of metres the enemies could no longer reach the kill zone. Therefore I could no longer lose any lives. This points to a design flaw. Maybe the largest part ( the walls )  should be the parent. Alternatively if moved re-arrange children relative to the main part.

Arrows would randomly disappear when loosed(fired) from the bow.


hifi-snap-by--on-2017-08-29_10-54-04

hifi-snap-by--on-2017-08-29_10-54-41

hifi-snap-by--on-2017-08-29_10-58-51

**Comment by MiladNazeri** [comment]
@Nex-Pro Hi, I think the actual shortbow game wasn't the right version being tested if it came from Market place.  Can you run console and type 'Script.include("https://s3-us-west-1.amazonaws.com/shortbow/spawnShortbow.js");'

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3216/HighFidelity-Beta-PR11239-8b4e49b83b178390dcf66d582e479913f67fae43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3216/HighFidelity-Beta-PR11239-8b4e49b83b178390dcf66d582e479913f67fae43.exe

**Comment by Nex-Pro** [comment]
@MiladNazeri What is the current status ?

**Comment by MiladNazeri** [comment]
@Nex-Pro  Ok you can test again with this link 
https://s3-us-west1.amazonaws.com/shortbow/spawnShortbow.js and the above build.

You may also want to test with the handControllerGrab Js branch refactor:
https://github.com/highfidelity/hifi/pull/11279
Although that one is still being worked on, but the last time I tried it, it solved the initial issue with entityPropertyCache

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3223/HighFidelity-Beta-PR11239-6443a5ea53efcfb777b4c82dd281ecf644299e6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3223/HighFidelity-Beta-PR11239-6443a5ea53efcfb777b4c82dd281ecf644299e6f.exe

**Comment by Nex-Pro** [comment]
Will test this in #11279

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
## FAIL

Besides the test plan issues  the castle for some reason is grabbable !  
Fortunately I was sitting down when I grabbed the whole thing rather than the bow.  I would probably have lost my balance.

### Second attempt to play the game I somehow had 60 lives.

hifi-snap-by-piper-peppercorn-on-2017-09-15_13-42-15

Ignore the teleport in the castle, that's just where it rezzed behind me !!!!

The first wave felt more like one of the higher levels with fast balls and a lot of them. Some of the balls were stationary after spawning.

Test Plan :
For Section 1 :

Re:

### Laser/stylus become unusable:

#### Steps to reproduce:

Get the bow from the marketplace
When you first get it, the laser/stylus works, you can drop it and use the grip or trigger to pick it up with either hand

***Had to obtain bow via marketplace link and import entities via URL as marketplace purchases are failing. This should be the identical bow.

Very rapidly shoot multiple arrows (I think I did around 10) in the same general direction--I didn't even bother pulling back all the way: **FAIL** ***Tried with 5 bows. First bow Got 5 arrows in succession then it stopped working. Second and third bows worked fine. Fourth bow failed after a few arrows with two arrows parked sideways at the bow. Fifth simply did not work at all. In early testing of shortbow I was able to fire many dozens of arrows before any issues.***

If you are able to shoot multiple arrows as fast as you can shoot, then this problem should be fixed.

My computer was giving me issues at first around 7-10 but the number would change depending on system resources available.


### For Section 2:

### Re: Stops spawning balls and bows

#### Steps to reproduce:

Go to marketplace and add the shortbow game to your domain


Hit play
Enter Create/edit mode and move the game

The spawn points don't move with the game. For some shortbow games the balls spawn, behind the avatar shop instead of in the pit and will freely roll anywhere in the domain. Since the game itself is not a locked asset, this is probably from it getting moved after being placed the first time. However, no balls spawned and the start sign failed to appear after wave 10, so it may be losing the ability to keep track of how many balls are still present.


run spawnShortBow.js Had to use the raw link as AWS s3 appeared to be down. 

**Please confirm that https://raw.githubusercontent.com/MiladNazeri/hifi/94f1e8b757adeb3a5091ba309744e049201f84ad/unpublishedScripts/marketplace/shortbow/spawnShortbow.js  is correct.***

Most of this problem had to do with the randomized jump on the enemy balls after being initiated too quickly after spawning. There seems to be a general problem related to disappearing models when Entities.getEntityProperties get called.

### Dropped the test at this point. No reason to continue.

Also discovered another system bug which I will check for on fogbugz.

Moving the board around while playing should reset the wave and spawn positions

No balls should be outside of the play area

Lives should be tracking fine despite the wave number.

**Comment by Nex-Pro** [comment]
@MiladNazeri 60 lives issue repro'd on running the spawn script again.

**Comment by ZappoMan** [comment]
this PR is waaaaaay out of date - closing it

**Pull request closed without merging**
