### PR TITLE
21274 Fade out effect prototype work

### PR DESCRIPTION
**Pull request by Zvork**
This PR adds a prototype version of the fade effect described in https://madewith.unity.com/en/stories/dissolving-the-world-part-1 and responds to the Worklist job 21274. The effect replaces the progressive transparency based fade currently used when an item has been loaded by a dissolve based on a noise based pattern.

**Shader modifications**
The PR contains a new shader header « Fade.slh » that holds the shader code for both vertex and fragment shader. Variations of the standard "model*" shaders are created using this new shader header. In its prototype state, only two variations have been created : model and model with normal map which are sufficient for testing. In consequence, the prototype currently doesn’t work for transparent objects, for instance, and has been added only to the deferred rendering engine.
The noise is evaluated as a 3D function based on a 2D texture map « fadeMask.png » added as an image ressource. It is evaluated in fade space. This space is equivalent to world space in rotation and scale but is local to each object in translation.

**Engine modifications**
On the engine side, a new shape key « Fade » has been added. ModelMeshPartPayloads which need to fade return this new key along with all its regular shape keys. In turn, dedicated « fade » pipelines are selected with these new shape key combinations in the « DrawOpaqueDeferred » job. The configuration of the fade shader for each ModelMeshPartPayload is done in the object’s render function with a specific uniform buffer bind for each object.

**Test plan**
A script « debugFade.js » in scripts/developer/utilities/render has a been added which, when the « Debug Fade » checkbox is enabled, lets the user manually control the fade progress on all objects of the scene.

**Remarks**

_Noise function_
The 3D function used for the dissolve cut-out effect needs to be discussed a bit more. In its current prototype state, it is a pseudo random function without much artistic control and based on a 2D texxture. Compromises and choices can be made based on the degree of artistic control wanted, performance (especially the number of texture fetches – texture-less noise being a possibility) and visual repetitiveness (« true » random noise or periodic-random noise).
The space in which this fade dissolve function is also an important discussion to have : should the dissolve effect be invariant to rotation, scale, translation ?
Other subjects of discussion concerns the quality of the effect, especially aliasing issues. What is the target quality ?

_Shader configuration_
Configuring the shader for each ModelMeshPartPayload render is not done in an optimised manner as a uniform buffer is created for each object and bound at each object render.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by samcake** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2af98831cfb28f90d336d84177fbf51329256853 available at: https://gist.github.com/65479737f616cf46ac4efad73ed79af4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10334-2af9883.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10334-2af9883.dmg

**Comment by samcake** [comment]
Very cool!
I m going to test / review show around to gather some feedback, staty tuned

**Comment by hifi-gustavo** [comment]
Build console output for commit: ff3cf7801a6aeef161868510b9656a7e1836fe75 available at: https://gist.github.com/65479737f616cf46ac4efad73ed79af4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10334-ff3cf78.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10334-ff3cf78.dmg

**Comment by samcake** [comment]
This work has been moved to a different branch
we can close this PR

**Pull request closed without merging**
