### PR TITLE
Remove FBX.cpp and other cleanup

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3428/HighFidelity-Beta-PR11402-59500061116f856b3b8c6a45bd01ec0a6dc35368.dmg

**Comment by huffman** [comment]
test this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3437/HighFidelity-Beta-PR11402-59500061116f856b3b8c6a45bd01ec0a6dc35368.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3437/HighFidelity-Beta-PR11402-59500061116f856b3b8c6a45bd01ec0a6dc35368.exe

**Pull request merged**
