### PR TITLE
Resorting Developer menu organization

### PR DESCRIPTION
**Pull request by alexiamandeville**
Relates to this bug: https://highfidelity.manuscript.com/f/cases/16869

Organizing the developer menu into a more logical manner.
Adding a Scripting sub menu to hold all the scripting related options and dialogs.

Testing: 
1. Turn on Settings > Developer Menu
2. Review the following menu items to make sure they are placed in their correct spot.
3. Make sure they all function correctly.

Items that were moved from Developer:
Crash > Display Crash Options

UI > Show Overlays

Scripting > Console...
Scripting > API Debugger
Scripting > Entity Script Server Log
Scripting > Verbose Logging
Scripting > Enable Speech Control API
Scripting > Script Log (HMD Friendly)
Scripting > Debug defaultScripts.js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12497/HighFidelity-Beta-PR13904-9267919.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12497/HighFidelity-Beta-PR13904-9267919.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12497/HighFidelity-Beta-Interface-PR13904-9267919.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12497/HighFidelity-Beta-PR13904-9267919.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12497/HighFidelity-Beta-Interface-PR13904-9267919.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12523/HighFidelity-Beta-PR13904-7bc860c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12523/HighFidelity-Beta-PR13904-7bc860c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12523/HighFidelity-Beta-Interface-PR13904-7bc860c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12539/HighFidelity-Beta-PR13904-1233c2e.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12539/HighFidelity-Beta-PR13904-1233c2e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12539/HighFidelity-Beta-Interface-PR13904-1233c2e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12539/HighFidelity-Beta-PR13904-1233c2e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12539/HighFidelity-Beta-Interface-PR13904-1233c2e.dmg

**Comment by alexiamandeville** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12610/HighFidelity-Beta-PR13904-200d862.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12610/HighFidelity-Beta-PR13904-200d862.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12610/HighFidelity-Beta-Interface-PR13904-200d862.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12610/HighFidelity-Beta-PR13904-200d862.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12610/HighFidelity-Beta-Interface-PR13904-200d862.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13746/HighFidelity-Beta-PR13904-d769f83.apk

**Comment by qligmaloney** [comment]
Build this please

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13998/HighFidelity-Beta-PR13904-d769f83.apk

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14194/HighFidelity-Beta-PR13904-d769f83.apk

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14222/HighFidelity-Beta-PR13904-d769f83.apk

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14264/HighFidelity-Beta-PR13904-d769f83.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14267/HighFidelity-Beta-PR13904-3cc7889.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14267/HighFidelity-Beta-PR13904-3cc7889.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14267/HighFidelity-Beta-Interface-PR13904-3cc7889.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14267/HighFidelity-Beta-PR13904-3cc7889.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14267/HighFidelity-Beta-Interface-PR13904-3cc7889.dmg

**Comment by ZappoMan** [comment]
Currently testing

**Comment by ZappoMan** [comment]
QA Fail - "Console..." appears twice.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14305/HighFidelity-Beta-PR13904-178b8ef.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14305/HighFidelity-Beta-PR13904-178b8ef.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14305/HighFidelity-Beta-Interface-PR13904-178b8ef.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14305/HighFidelity-Beta-PR13904-178b8ef.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14305/HighFidelity-Beta-Interface-PR13904-178b8ef.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
FAIL @conklin94122 

Display Crash Options appears twice.

image
[hifi-log.txt](https://github.com/highfidelity/hifi/files/2508032/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14319/HighFidelity-Beta-PR13904-68ab547.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14319/HighFidelity-Beta-PR13904-68ab547.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14319/HighFidelity-Beta-Interface-PR13904-68ab547.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14319/HighFidelity-Beta-PR13904-68ab547.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14319/HighFidelity-Beta-Interface-PR13904-68ab547.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Menu options are where they belong.

**Pull request merged**
