### PR TITLE
Fix avatars remain stuck in place for other users intermittently

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.manuscript.com/f/cases/19536/Avatars-remain-stuck-in-place-for-other-users-intermittently

This PR fixes the bug that was introduced by https://github.com/highfidelity/hifi/pull/14187, where the avatar mixer send incorrect position information, making avatars remain stuck in place for the observer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14431/HighFidelity-Beta-PR14288-62e4b3f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14431/HighFidelity-Beta-PR14288-62e4b3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14431/HighFidelity-Beta-Interface-PR14288-62e4b3f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14431/HighFidelity-Beta-PR14288-62e4b3f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14431/HighFidelity-Beta-Interface-PR14288-62e4b3f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14432/HighFidelity-Beta-PR14288-767f4e9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14432/HighFidelity-Beta-Interface-PR14288-767f4e9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14432/HighFidelity-Beta-PR14288-767f4e9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14432/HighFidelity-Beta-Interface-PR14288-767f4e9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14434/HighFidelity-Beta-PR14288-056fe33.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14434/HighFidelity-Beta-Interface-PR14288-056fe33.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14434/HighFidelity-Beta-PR14288-056fe33.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14434/HighFidelity-Beta-Interface-PR14288-056fe33.exe

**Comment by luiscuenca** [comment]
## TEST PLAN
- Download the build with the server console and install both.
- Setup the domain.
- Two testers should connect that that domain using this build. (or open 2 interface instances)
- Observe each other walking, teleporting and flying around. Make sure none of the avatars get stuck.
- When spawning near the 0,0,0 point of the domain make sure your avatar appears correctly to others and it is not stuck on the 0,0,0 position.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14447/HighFidelity-Beta-PR14288-e49e9cd.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14447/HighFidelity-Beta-PR14288-e49e9cd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14447/HighFidelity-Beta-Interface-PR14288-e49e9cd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14447/HighFidelity-Beta-PR14288-e49e9cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14447/HighFidelity-Beta-Interface-PR14288-e49e9cd.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
Pass @conklin94122 . Verified that neither avatar gets stuck while walking, running, jumping, and teleporting and also that no avatar gets stuck while in coordinates /0,0,0.

**Pull request merged**
