### PR TITLE
Improve punctuation on README.md

### PR DESCRIPTION
**Pull request by cmpt376edits**
- improved wording
- improved spacing of text for consistent readability in editing
- improved sentence structure with punctuation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by wayne-chen** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11193/HighFidelity-Beta-PR13551-b1801c6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11193/HighFidelity-Beta-PR13551-b1801c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11193/HighFidelity-Beta-Interface-PR13551-b1801c6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11193/HighFidelity-Beta-PR13551-b1801c6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11193/HighFidelity-Beta-Interface-PR13551-b1801c6.exe

**Pull request merged**
