### PR TITLE
Fix Window.setFocus() unsetting focus if Interface has focus

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7655/app_12540_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7655/HighFidelity-Beta-PR12540-287ea8eff2b2635ef953bf5029fc16fdf65fbf9b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7655/HighFidelity-Beta-PR12540-287ea8eff2b2635ef953bf5029fc16fdf65fbf9b.exe

**Comment by themelissabrown** [comment]
Does this need a test plan for QA?

**Comment by ctrlaltdavid** [comment]
When the "do not merge" label is taken off. There are still code changes to come.

**Pull request closed without merging**
