### PR TITLE
remove scripts from avatar attached entities for other avatars

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- smoke test, things should work as normal.
- open console and run this script:
```
Entities.addEntity(
    {
        type: "Box", 
        position: MyAvatar.position, 
        parentID: MyAvatar.sessionUUID,
        visible: true,
        collisionless:true,
        name: "avatar entity",
        dimensions: { x: 1, y: 1, z: 1},
        color: { red: 0, green: 255, blue: 0},
        script: "https://raw.githubusercontent.com/highfidelity/hifi/master/scripts/developer/tests/basicEntityTest/myEntityScript.js"
    },true
);
```
- you should get a box around your avatar, and when you go from domain to domain the box should stay with you (this is an avatar entity)
- verify that in your local client you see the following message in your log file: (note the number at end is random)
```
[11/09 12:23:47] [DEBUG] [hifi.scriptengine] script:print()<< PRELOAD ENTITY SCRIPT!!! 0.060
```
- connect another client (from this PR) to the same domain... 
- verify that you see the green box around the first avatar
- verify that the following message DOES NOT appear in your log...
```
[11/09 12:23:47] [DEBUG] [hifi.scriptengine] script:print()<< PRELOAD ENTITY SCRIPT!!! 0.060
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: cf3d1011f463e5d471f2e0500796764fd41a0e14 available at: https://gist.github.com/a484412b54c3f2598edc79b2e72c3e20<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9038-cf3d101.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9038-cf3d101.dmg

**Comment by OmegaHeron** [comment]
Windows 10

Client 1 with entity script I see in log;

`[11/09 16:16:37] [DEBUG] [hifi.scriptengine] script:print()<< PRELOAD ENTITY SCRIPT!!! 0.155`

Client 2 I see the box and do not see PRELOAD message in its log.

Box entity remains with AV across domain changes.

Client 2 following AV to alternate locations continues to see entity (an no PRELOAD message)

General smoke test passes.

One question.  How in the $*^$)^*@)*@^ do I get the blasted box off me?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 770bf35d2b57253e1eaba9a63746223ffe068f3f available at: https://gist.github.com/a484412b54c3f2598edc79b2e72c3e20<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9038-770bf35.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9038-770bf35.dmg

**Comment by Menithal** [comment]
Just a comment on this:

What if you want to make an Entity that is attached to an avatar that other users can interact with?

**Pull request merged**
