### PR TITLE
Improve positioning of assets when added / imported

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
This PR makes the positioning of entities created and imported more predictable: when it makes sense, they're rezzed such that their bounding boxes are 2m in front of your avatar/camera (this rather than sometimes appearing on top of or even behind your avatar).

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

Entities editor "create" buttons:
- Cube, sphere, text, Web: Creates in front of your avatar/camera (depending on mode - see below) such that their bounding box is 2m in front of you.
- Zone, light, particle effect: Creates in front of your avatar/camera (depending on mode) at a distance of 2m (i.e., registration point is 2m in front of you).
- Model: Creates in front of your avatar/camera (depending on mode) at a position 2m in front, then after it's been auto-resized its position is adjusted so that its bounding box is 2m in front of you.
- If in first person, third person, or mirror view mode, the import position is raised by 0.5m.
- If snap-to-grid is enabled, the entity is snapped to the grid.

Entities editor "Import entities (JSON)" button; add model from Marketplace:
- Imports in front of you/camera (depending on camera mode) at a position 2m in front.
- If the first entity is not a zone, light, or particle effect entity, then after import the position of the combined entities are adjusted so that their bounding boxes are at least 2m in front and their geometric mean is perpendicularly centered on the rez position.
- If in first person, third person, or mirror view mode, the import position is raised by 0.5m.
- If snap-to-grid is enabled, the entities are snapped to the grid based on the first entity in the JSON file.

Notes:
- Entities are created horizontally in front of you if you're in first person, third person, or mirror view modes.
- Entities are created (not necessarily horizontally) in front of your camera if you're in entity or independent view modes.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/242/HighFidelity-Beta-PR10569-8de93d9651f0924c9630ca9a25b819575c2e6ae0.exe

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/243/HighFidelity-Beta-PR10569-8de93d9651f0924c9630ca9a25b819575c2e6ae0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/243/HighFidelity-Beta-PR10569-8de93d9651f0924c9630ca9a25b819575c2e6ae0.dmg

**Comment by CainFoool** [comment]
# Test Passed 

All of the objects and models appear to spawn in as expected, followed the testing steps with a pass on every one of them. Snap to Grid is also working just fine too when spawned in a new model/entity.

**Comment by PhilipRosedale** [comment]
Also looks great to me.

**Pull request merged**
