### PR TITLE
keep qml text fields up to date with vive virtual keyboard

### PR DESCRIPTION
**Pull request by howard-stearns**
make the qml input fields match the vive virtual keyboard as each key is inputted

### CODE REVIEW

**Comment by howard-stearns** [comment]
This does NOT address the issue where the vive doesn't drive html input. Just qml.

**Comment by howard-stearns** [comment]
test plan (requires Vive):
Bring up the vive keyboard by lasering in a qml input field such as Running Scripts filter, or GoTo address bar.  As you type, the QML display should match. In the case of the GoTo address bar, the suggestions should change as you type (and delete) each key.

Make sure that "done" still works as you expect.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e7b8282033a794285b5769119424eafee190cb9 available at: https://gist.github.com/2874fe76943a0c10a8f9d09a256ece34<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8347-6e7b828.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8347-6e7b828.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by howard-stearns** [comment]
testers: the builds should be ok. There's a new build started, but that has to do with jenkins issues, not code changes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e7b8282033a794285b5769119424eafee190cb9 available at: https://gist.github.com/2874fe76943a0c10a8f9d09a256ece34<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8347-6e7b828.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8347-6e7b828.dmg

**Comment by howard-stearns** [comment]
This will need QA when merged back to master, so for discovery branch, I'm just going to go ahead and merge now.

**Pull request merged**
