### PR TITLE
fixing the scattering bad ambient lighting

### PR DESCRIPTION
**Pull request by samcake**
The normal used for ambient lighting for scattering surface needed to be expressed in the correct space

## TEST PLAN

IN current master, looking at pricilia should show bad ugly shadows on the face
it s gone in this pr

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7103/app_12379_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7103/HighFidelity-Beta-PR12379-e64c029424c6a7cc023e49452790268fe71210db.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7103/HighFidelity-Beta-PR12379-e64c029424c6a7cc023e49452790268fe71210db.dmg

**Comment by ZappoMan** [comment]
isn't this also a bug in the RC64 branch?

**Comment by samcake** [comment]
good point, working on it

**Comment by druiz17** [comment]
Test this and it fixes the issue.

**Pull request merged**
