### PR TITLE
FarGrab Entity Rotation with Off-Hand

### PR DESCRIPTION
**Pull request by r3tk0n**
Experiment involving the ability to rotate the entity that you're fargrabbing with your off hand. In order to test:

1.) FarGrab an entity with either hand.
2.) On your offhand controller (i.e. the one that is _not_ performing a FarGrab) pull the trigger.
3.) Rotate your wrist to rotate the object. Release the offhand controller trigger when done.

ticket is found here https://highfidelity.fogbugz.com/f/cases/21487/Feature-Manipulate-Rotate-FarGrabbed-Item-with-Off-Hand

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17673/HighFidelity-Beta-PR15043-52d8047.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17673/HighFidelity-Quest-Beta-PR15043-52d8047.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17673/HighFidelity-Beta-PR15043-52d8047.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17673/HighFidelity-Beta-Interface-PR15043-52d8047.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17673/HighFidelity-Beta-PR15043-52d8047.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17673/HighFidelity-Beta-Interface-PR15043-52d8047.exe

**Comment by r3tk0n** [comment]
The builds above this comment are at a 1:1 ratio for controller rotation to entity rotation. The builds below are at a 1:2 ratio for controller:entity rotation.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17676/HighFidelity-Beta-PR15043-ca740c6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17676/HighFidelity-Quest-Beta-PR15043-ca740c6.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17676/HighFidelity-Beta-PR15043-ca740c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17676/HighFidelity-Beta-Interface-PR15043-ca740c6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17676/HighFidelity-Beta-PR15043-ca740c6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17676/HighFidelity-Beta-Interface-PR15043-ca740c6.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17732/HighFidelity-Beta-PR15043-a72b02c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17732/HighFidelity-Quest-Beta-PR15043-a72b02c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17732/HighFidelity-Beta-PR15043-a72b02c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17732/HighFidelity-Beta-Interface-PR15043-a72b02c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17732/HighFidelity-Beta-PR15043-a72b02c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17732/HighFidelity-Beta-Interface-PR15043-a72b02c.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17815/HighFidelity-Beta-PR15043-a72b02c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17815/HighFidelity-Quest-Beta-PR15043-a72b02c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17815/HighFidelity-Beta-PR15043-a72b02c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17815/HighFidelity-Beta-Interface-PR15043-a72b02c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17815/HighFidelity-Beta-PR15043-a72b02c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17815/HighFidelity-Beta-Interface-PR15043-a72b02c.exe

**Pull request merged**
