### PR TITLE
HMD eye correction

### PR DESCRIPTION
**Pull request by howard-stearns**
When looking at me, adjust for proper HMD camera vs avatar scaling

Most of this is functionally the same as what was there, just annotated and broken out step by step. The only real change is the use of getEyeOffset() rather than a constant, and doing a bit more in world coordinates.

### CODE REVIEW

**Comment by howard-stearns** [comment]
I'm not convinced that this is right wrt to head pitch, but I do think it's got left vs right down,
and it raises the baseline for any required improvements.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f26849c7e15a25b836308f9c3a613e43ef48eded available at: https://gist.github.com/b9754bec0d3f0df0a510<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea02583875178380c429046fd5e8ef3fcfb8258a available at: https://gist.github.com/b9754bec0d3f0df0a510<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 642e56903329bbbe3c70d0795f40a2fc3f7913f7 available at: https://gist.github.com/b9754bec0d3f0df0a510<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5613.dmg

**Pull request merged**
