### PR TITLE
Rollback PR 12888 by deleting alternative +android files

### PR DESCRIPTION
**Pull request by Cristo86**
As we updated Android to use Qt 5.11.1, these files should be deleted.

**Test plan:**

- Execute App, it should not crash.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11264/HighFidelity-Beta-PR13591-b1d39e4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11264/HighFidelity-Beta-PR13591-b1d39e4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11264/HighFidelity-Beta-Interface-PR13591-b1d39e4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11264/HighFidelity-Beta-PR13591-b1d39e4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11264/HighFidelity-Beta-Interface-PR13591-b1d39e4.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
App does not crash.

**Pull request merged**
