### PR TITLE
Show outline for zones when rotating

### PR DESCRIPTION
**Pull request by misslivirose**
Fixes case 11446: Zone outlines disappear when rotating

### CODE REVIEW

**Comment by misslivirose** [comment]
Test Plan: https://highfidelity.testrail.net/index.php?/cases/view/10658

Ensure that when rotating Zones only, the outlines stay in place so you are able to see how your zone is moving. Verify visually that deselecting and reselecting the zone is accurate to where you left it after rotating.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7250/app_12422_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7250/HighFidelity-Beta-PR12422-175532c444ea0dfd8b807c9e1ce91b72c85529cc.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7274/app_12422_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7274/HighFidelity-Beta-PR12422-175532c444ea0dfd8b807c9e1ce91b72c85529cc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7274/HighFidelity-Beta-PR12422-175532c444ea0dfd8b807c9e1ce91b72c85529cc.dmg

**Comment by qlimnavarro** [comment]
Currently being tested.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
