### PR TITLE
Beta Release Candidate 5 - including up to Development Release 4729

### PR DESCRIPTION
**Pull request by ZappoMan**
- Fix to render rate stats
- Fixes to resource cache stats
- Fix to crash in MyAvatar.addAnimationStateHandler()
- Automatically leave Away mode if you walk a short distance
- Fix to animations getting stuck in away mode
- Fix memory leak in text rendering
- Clear ATP cache when changing domains
- New App name on OSX
- Fix to crashes related to reloading the resource cache
- Fix export and duplicate of animated entities
- Improve ICE server redundancy
- Performance improvements to physics
- Improvements to BugSplat crash handling to catch more crashes
- Fix to occasional invisible avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7b495520664668132e06d1b615b5e0b696cd9acd available at: https://gist.github.com/e038b413e934a44fda30345877057f16<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7687.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7687.dmg

**Comment by hyperlogic** [comment]
Isn't this RC5?

**Comment by ZappoMan** [comment]
whoops! yep!

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7687
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience, forum
**Smoke Test Results:** Partially successful test.

                                  |localhost |playa    |cellscience |forum  
----------------------------------|----------|---------|------------|-----
Render Rate:                      |58.15     |56.06    |55.00       |50.96    
Present Rate:                     |60.00     |60.02    |60.00       |60.02   
Simrate:                          |55.10     |57.06    |54.09       |55.99    
Render Stats Num Buffers:         |1644      |3573     |3168        |3599   
Render Stats gpu::Buffer Memory:  |35.1Mb    |64.5Mb   |32.4Mb      |50.5Mb        
Render Stats Num Textures:        |393       |582      |203         |934    
Render Stats gpu::Texture Memory: |1079.1Mb  |1400.1Mb |509.0Mb     |1766.8Mb         
Render Stats Triangles:           |997k      |1100k    |568k        |1342k    
Render Stats Drawcalls:           |204       |372      |204         |852   
Render Stats Items:               |91        |387      |808         |448
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb      |4096Mb
GPU-Z Initial Memory		  |219Mb     |219Mb    |219Mb       |219Mb
GPU-Z Memory Used		  |1160Mb    |1628Mb   |989Mb       |1618Mb
GPU-Z Memory Load		  |8%        |10%      |7%          |10%

**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Partially successful test.  The ```Echo Local Audio``` was successful however when testing server audio on ```localhost```, it did not successfully echo back, upon visiting ```playa```, worked successfully upon revisiting ```localhost``` successful test.  Identical behavior in prior PR's and have reported such.  Unsure if this is a real issue but wanted to bring it up for potential further analysis.  Enclosed is the log for further inspection.
**localhost ‘reverbTest.js’ Result:** Successful test.
**Additional Test Results Requested:** (none)
**Successful Logout/Crash:** Failure.  Upon visit of ```forum``` clicked on the tidy up button and it caused an instant crash.  Upon relog, repeated test of the tidy up button and crash occurred again.  Bugsplat successfully set on both crashes as well as the log file for each crash included for deeper analysis.
[attachments.zip](https://github.com/highfidelity/hifi/files/222140/attachments.zip)

**Comment by cozza13** [comment]
QA Pass. 

Went through with the DK2

**Pull request merged**
