### PR TITLE
Add js line library for drawing infinite poly lines

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by imgntn** [comment]
@huffman do you have an example script for this one so i can test it out?  or maybe a link to the baseball script where it is so i can see how you use it and write my own test? ty

**Comment by huffman** [comment]
@imgntn Sure, I will write an example script

**Comment by huffman** [comment]
@imgntn You should be able to test https://raw.githubusercontent.com/huffman/hifi/line-js/examples/example/lineExample.js now

**Comment by huffman** [comment]
@imgntn I added a lifetime parameter

**Comment by imgntn** [comment]
@huffman nice -- looks good to me in testing  -- just need to add headers & we're good to go

**Comment by huffman** [comment]
@imgntn Whoops, added headers

**Pull request merged**
