### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by sethalves**
- 10 months of ignoring boostrapping is enough.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by sethalves** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21896/HighFidelity-Beta-PR16341-0a01c3c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21896/HighFidelity-Beta-Interface-PR16341-0a01c3c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21896/HighFidelity-Beta-PR16341-0a01c3c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21896/HighFidelity-Quest-Beta-PR16341-0a01c3c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21896/HighFidelity-Beta-PR16341-0a01c3c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21896/HighFidelity-Beta-Interface-PR16341-0a01c3c.exe

**Pull request merged**
