### PR TITLE
require a valid access token and expiry to attempt token refresh

### PR DESCRIPTION
**Pull request by birarda**
- check for refresh token and actual expiry before attempting access token refresh

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

The domain-server on master is spitting out `AccountManager: failed to refresh access token -  QNetworkReply::NetworkError(AuthenticationRequiredError)` because it does not have a refresh token and thinks its current access token is expired (which it is not).

With a domain-server connected to your High Fidelity account, run master. Confirm you see the above error in your log. With a domain-server connected to your High Fidelity account, run this PR. Confirm you do not see any messages about refreshing access tokens in your log.

**Comment by CainFoool** [comment]
Will test when ready.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/151/HighFidelity-Beta-PR10544-14ff6a06b42ae3706c1058387b9d43d1529b89ac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/151/HighFidelity-Beta-PR10544-14ff6a06b42ae3706c1058387b9d43d1529b89ac.dmg

**Comment by CainFoool** [comment]
# Test Passed 

Error message no longer appears (`[05/24 21:46:19] [DEBUG] [hifi.networking] AccountManager: failed to refresh access token - QNetworkReply::NetworkError(AuthenticationRequiredError)`) in the Domain Server when connected to a High Fidelity account. 

Re-doing test from #10525: 
All steps passed - authentication works as expected when the file is copied over into the directory and the interface is launched.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/152/HighFidelity-Beta-PR10544-9cd11a32e2c7e7d494a2237cf4b31caa0d1da7b6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/152/HighFidelity-Beta-PR10544-9cd11a32e2c7e7d494a2237cf4b31caa0d1da7b6.dmg

**Pull request merged**
