### PR TITLE
Added accessor to get Avatar default pose in avatar space

### PR DESCRIPTION
**Pull request by hyperlogic**
Also fixed a bug when transmitting quaternions from JS to the animation system via the animationStateHandler

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA test:
Open the console and type the following command
<pre>> JSON.stringify(MyAvatar.getAbsoluteDefaultJointTranslationInObjectFrame(MyAvatar.getJointIndex("Hips")))
</pre>
You should see a result that is close to zero in x, y and z.  For example:
<pre>
< {"x":0,"y":0,"z":5.820766091346741e-11}
</pre>
Then try the following command for rotation:
<pre>JSON.stringify(MyAvatar.getAbsoluteDefaultJointRotationInObjectFrame(MyAvatar.getJointIndex("Hips")))</pre>
You should see a result that is closed to the identity quaternions (0, 0, 0, 1) or (0, 0, 0, -1)
</pre>
< {"x":-0.00000456699717688025,"y":1,"z":6.15703391049216e-11,"w":-1.4069672715777415e-7}
<pre>

**Comment by hifi-gustavo** [comment]
Build console output for commit: a06df1a400686a62a3db7801286a4516bbb79d2f available at: https://gist.github.com/251c36c501629f605e01dfa379f0baa9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10169-a06df1a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10169-a06df1a.dmg

**Comment by 68chase** [comment]
Testing

**Comment by 68chase** [comment]
Passed 
image

**Pull request merged**
