### PR TITLE
Update crash 3Dconnexion

### PR DESCRIPTION
**Pull request by MarcelEdward**
On windows when exiting interface crashes when the 3Dconnexion device was not enabled in the menu.

Added a check to see if it is enabled in the menu, to be sure to only try to do the removeNativeEventFilter when it is initialized.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0e1ccb585cfe904d22e0d6fb7917ee5e13f40d1d available at: https://gist.github.com/cc511c445a2ee8da224d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5480.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5480.dmg

**Comment by ctrlaltdavid** [comment]
Tested OK on Windows. ... No SpaceNavigator connected. ... Other builds crash on exit but this one doesn't.

**Comment by SamGondelman** [comment]
Isn't the event filter already removed in ConnexionClient::destroy?  In that case, the destructor doesn't need to do anything.  This PR handles that and a number of other issues: https://github.com/highfidelity/hifi/pull/5465

**Comment by MarcelEdward** [comment]
True the event filter will clear automatic when interface quits, the remove should not be called when not initialized but will be removed when the object is set to null.  
Missed it cause I clicked the stop button in the debug build visual studio, that appears to be different than a normal quit. 

void ConnexionClient::destroy() is called when the enable 3Dconnexion is disabled in the menu. It should clean up the event filter there.

**Comment by SamGondelman** [comment]
ConnexionClient::destroy() is also called from within ~Application(), so the event filter will get removed there.

**Comment by MarcelEdward** [comment]
yes the destructor ConnexionClient::~ConnexionClient() can be removed completely

**Comment by SamGondelman** [comment]
Great, you can close this PR and I'll fix it up in the other one :D

**Pull request closed without merging**
