### PR TITLE
actually delete resources... even on windows

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ded035094a5286dbc1116c51a2e289d4340b03af available at: https://gist.github.com/835029fe0e16ce81ee59<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by birarda** [comment]
is this going to cause a crash on windows alpha builds?

**Comment by ZappoMan** [comment]
@birarda - once it builds, lets do some testing. I think the "crash" is only on "shutdown", but we don't have a historical record of what the actual crash is. I am hot on the trail of fixing the crash on shutdown, which also happens sometimes on mac.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ded035094a5286dbc1116c51a2e289d4340b03af available at: https://gist.github.com/6b0b691c366b963d9a59<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ded035094a5286dbc1116c51a2e289d4340b03af available at: https://gist.github.com/d9e1238cad420aeb24f6<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4225.dmg

**Comment by ZappoMan** [comment]
@PhilipRosedale or @birarda do one of you want to merge this?

**Pull request merged**
