### PR TITLE
Pr 11581 for rc 57

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4282/HighFidelity-Beta-PR11633-2c8c5e214cec55ba95f5ae52f192d88d1a24e78a.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4294/HighFidelity-Beta-PR11633-2c8c5e214cec55ba95f5ae52f192d88d1a24e78a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4294/HighFidelity-Beta-PR11633-2c8c5e214cec55ba95f5ae52f192d88d1a24e78a.exe

**Comment by misslivirose** [comment]
**Use test plan from 11581**

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
run the servers from this PR | Pass
visit domain settings page -- http://localhost:40100/settings/ or whatever | Pass
click "show advanced", "entity-server settings", enable "Edit Logging (Terse)", save | Pass
go someplace in the domain with a lot of open space | Pass
create a cube, make it blue | Pass
create a cube, make it dynamic and green | Pass
get someone to watch you (running interface from this PR) | Pass
make sure nobody else is in the domain | Pass
on both interfaces, open running-scripts window and run queryAACubeInspector.js (and then close running-scripts windows) | Pass
arrange for someone to be "tailing" the entity-server log | Pass
with hmd and hand-controllers, grab the blue (non-dynamic) cube | Pass
see that the queryAACube puffs out | Pass
see that the entity-server is not receiving constant edits (a few are expected, we don't want constant 60 Hz edits) | Pass
when the cube touches the side of the puffed queryAACube, it should update and the server should get some edits | Pass
confirm that both the grabber and the watcher are seeing the same thing | Pass
release the cube and see that the queryAACube shrinks down to snugly fit around the cube | Pass
do this all again with the green (dynamic) cube | Pass
gently toss the green cube and see that the queryAACube puffs-out and updates anytime it's touched by the cube | Pass
observe that the queryAACube shrinks down once the green cube has stopped drifting | Pass
remember to turn off terse edit logging and stop the queryAACubeInspector scripts | Pass

I noticed an issue where far grabbing the cubes only worked occasionally.. sometimes not at all. This seems to be a problem with the queryAACubeInspector.js script and persists in Master.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by sethalves** [comment]
yes, far-grabbing wont work right with that script running, because the ray intersects the overlay (the blue cube) rather than the entity.

**Pull request merged**
