### PR TITLE
fix grid shader

### PR DESCRIPTION
**Pull request by ChristophHaag**
this shader is used for example in
developer - audio - audio scope - show scope

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by sethalves** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7134d2bfd4baff5b19040c3a9373c41443186d57 available at: https://gist.github.com/b3bd70761b8f402af41977c81ebab883<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8304-7134d2b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8304-7134d2b.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10

Using last RC I looked at Devel->Audio Scope, made note of its appearance.
Using this PR, did same as above.

Scope works proper and looks same in both RC and this PR - saw no change to FPS/CPU use and no error messages in log.  I'm not sure if this is a pass or not - since I can't see a change between current code and this PR I'm unsure how to validate it fixes anything.  More testing notes?

**Comment by ChristophHaag** [comment]
Maybe I should have elaborated. This is the full shader code that is generated:
```
#version 410 core
#define GPU_PIXEL_SHADER

//410 core
//  Generated on Fri Jul 22 00:30:17 2016
//  grid.slf
//  fragment shader
//
//  Created by Zach Pomerantz on 2/16/2016.
//  Copyright 2016 High Fidelity, Inc.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//

float paintStripe(float value, float offset, float scale, float edge) {
    float width = fwidth(value);
    float normalizedWidth = width * scale;

    float x0 = (value + offset) * scale - normalizedWidth / 2;
    float x1 = x0 + normalizedWidth;

    float balance = 1.0 - edge;
    float i0 = edge * floor(x0) + max(0.0, fract(x0) - balance);
    float i1 = edge * floor(x1) + max(0.0, fract(x1) - balance);
    float strip = (i1 - i0) / normalizedWidth;

    return clamp(strip, 0.0, 1.0);
}

float paintGrid(vec2 value, vec2 offset, vec2 scale, vec2 edge) {
    return max(
        paintStripe(value.x, offset.x, scale.x, edge.x),
        paintStripe(value.y, offset.y, scale.y, edge.y));
}

float paintGridMajor(vec2 value, vec2 offset, vec2 scale, vec2 edge) {
    return paintGrid(value, offset, scale, edge);
}

float paintGridMajorMinor(vec2 value, vec4 offset, vec4 scale, vec4 edge) {
    return max(
        paintGrid(value, offset.xy, scale.xy, edge.xy),
        paintGrid(value, offset.zw, scale.zw, edge.zw));
}

struct Grid {
    vec4 period;
    vec4 offset;
    vec4 edge;
};

uniform gridBuffer { Grid grid; };
Grid getGrid() { return grid; };

in vec2 varTexCoord0;
in vec4 varColor;

out vec4 outFragColor;

void main(void) {
    Grid grid = getGrid();

    float alpha;
    if (grid.edge.z == 0.0) {
        alpha = paintGrid(varTexCoord0, grid.offset.xy, grid.period.xy, grid.edge.xy);
    } else {
        alpha = paintGridMajorMinor(varTexCoord0, grid.offset, grid.period, grid.edge);
    }
    if (alpha == 0.0) {
        discard;
    }

    outFragColor = vec4(varColor.xyz, varColor.w * alpha);
}
```
mesa doesn't like that shader:
```
mesa/src/compiler/glsl_compiler --v=410 shader_136.frag                                                                             :(
Info log for shader_136.frag:
0:54(32): error: syntax error, unexpected ';', expecting $end
```

And glslangValidator doesn't like it:
```
$ glslangValidator shader_136.frag
shader_136.frag
Warning, version 410 is not yet complete; most version-specific features are present, but some are missing.
ERROR: 0:54: '' :  syntax error
ERROR: 1 compilation errors.  No code generated.
```
I don't know much about GLSL but I think it's safe to say that the `;` in line 54 is misplaced and just happens to work on compilers that tolerate some errors.

**Comment by OmegaHeron** [comment]
Pending any other comments - then - QA Pass as the fix wouldn't generate a visible change unless it's ran on a machine where shader compile failed.

**Pull request merged**
