### PR TITLE
Clean Interface.ini after a crash

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b27d25b46edc0f0dd1b047f1d7eda8f5604718c8 available at: https://gist.github.com/1b8816dd6ca5efe325da<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.dmg

**Comment by jherico** [comment]
I tried this on windows.  When I crashed the interface and restarted I got the dialog... selected the option to clean my ini but retain my login and avatar information.  The dialog went away, but interface.exe was still in my process list.  I had to kill it manually.  When i restarted, it looked as though my ini was completly wiped as I had to log in again.  

Tested on windows.

**Comment by ctrlaltdavid** [comment]
The Interface.ini.lock file was not deleted earlier enough. In which case Interface.exe execution is blocked for 10-20 seconds. And if start up a second copy of Interface during this time bad things happen to Interface.ini content and could get an Interface.exe process running that needed manual deletion.
Additionally, crash options were occasionally not displayed after a crash if crashed with Interface.ini containing only avatar and login info from previous crash (before complete set of new settings was written to the file).
Fixing by deleting Interface.ini.lock earlier and assuming default setting for Display Crash Options if value not present in Interface.ini.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7c8ff4dcbdce6cb676f2ed341f32d2b64b63533c available at: https://gist.github.com/1b8816dd6ca5efe325da<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.dmg

**Comment by cozza13** [comment]
I tested this on OSX and it worked. The text for what is happening doing does not really describe what we are trying to fix. I wonder if there is some better wording on the panel? Maybe "What would you like to do" could be "If you are having trouble restarting, we can reset your Interface.ini"

**Comment by ctrlaltdavid** [comment]
The current title and text of the dialog box that displays at start-up after a crash...

Interface Crashed Last Run
What would you like to do?
- Delete Interface.ini
- Delete Interface.ini but retain login and avatar info.
- Continue with my current Interface.ini

Possible change...

Interface Crashed Last Run
If you are having trouble starting would you like to reset your Interface.ini?
- Delete Interface.ini
- Delete Interface.ini but retain login and avatar info.
- Continue with my current Interface.ini

Or...

Interface Crashed Last Run
If you are having trouble starting would you like to reset your settings?
- Reset all my settings
- Reset my settings but retain login and avatar info.
- Continue with my current settings

**Comment by cozza13** [comment]
@ctrlaltdavid I like C:

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1f541832b69f26bdd223e2fe19b098a52e0d5d2a available at: https://gist.github.com/1b8816dd6ca5efe325da<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5648.dmg

**Pull request merged**
