### PR TITLE
RC73.2: avoid backwards seek for skipped trait deletes

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13683/HighFidelity-Beta-PR14152-04cee36.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13683/HighFidelity-Beta-PR14152-04cee36.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13683/HighFidelity-Beta-Interface-PR14152-04cee36.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by birarda** [comment]
#### Test Plan

1. Enable [clumsy](https://jagt.github.io/clumsy/). Add 5% out of order and dropped packets on all receiving traffic.
2. From 73.1, connect to distributed2. Switch to a different domain and reconnect to distributed2. Repeat that process until you crash.
3. With clumsy still on, repeat those steps with this PR. You should not crash.

**Comment by antoninahifi** [comment]
@conklin94122  PASS
verified that “in a domain, wear and delete some avatar entities and make sure another user sees you delete them”

**Comment by conklin94122** [comment]
I double checked and @antoninahifi confirms that this is indeed ready to be merged.

**Pull request merged**
