### PR TITLE
DOC-235: DriveKeys JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Namespaces:
- DriveKeys

Also:
- Type MyAvatar.DriveKeys renamed to (global) type DriveKey.
- MyAvatar.disableDriveKey() example updated to use DriveKeys API.

Case: https://highfidelity.atlassian.net/browse/DOC-235

Note: No executable code changes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22775/HighFidelity-Beta-PR16556-064e97a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22775/HighFidelity-Beta-Interface-PR16556-064e97a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22775/HighFidelity-Beta-PR16556-064e97a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22775/HighFidelity-Quest-Beta-PR16556-064e97a.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22776/HighFidelity-Beta-PR16556-064e97a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22776/HighFidelity-Beta-Interface-PR16556-064e97a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22776/HighFidelity-Beta-PR16556-064e97a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22776/HighFidelity-Quest-Beta-PR16556-064e97a.apk)

**Comment by jennaingersoll** [comment]
Build me please.

**Pull request merged**
