### PR TITLE
allow sending interface-local messsages

### PR DESCRIPTION
**Pull request by sethalves**
- from js, Messages.sendLocalMessage will send a message that only arrives at interface-local subscribers

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- create a box
- set it's script to http://headache.hungry.com/~seth/hifi/message-test/a.js
- create a second box
- set the second box's script to http://headache.hungry.com/~seth/hifi/message-test/b.js
- log in two interfaces running the build from this PR, get them near the 2 boxes
- open the log window on both interfaces
- click on the boxes and make sure what you see makes sense

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee55721f79bf7b319aaf1cba621fb17d529559bc available at: https://gist.github.com/d1b8c84b1ea53cd05dff<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7266.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7266.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee55721f79bf7b319aaf1cba621fb17d529559bc available at: https://gist.github.com/d1b8c84b1ea53cd05dff<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7266.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7266.dmg

**Comment by thoys** [comment]
:+1:

**Comment by thoys** [comment]
I will test this as soon as its QA ready :)

**Comment by cozza13** [comment]
Knock yourself out @thoys

**Comment by thoys** [comment]
tested and looks good @sethalves 

Clicked both boxes a few times to get this result:
```
[03/08 02:11:15] [DEBUG] script:print()<< object-a received: a message from b
[03/08 02:11:15] [DEBUG] script:print()<< object-b received: a message from b
[03/08 02:11:16] [DEBUG] script:print()<< object-a received: a message from b
[03/08 02:11:16] [DEBUG] script:print()<< object-b received: a message from b
[03/08 02:11:18] [DEBUG] script:print()<< object-a received: a local-only message from a
[03/08 02:11:18] [DEBUG] script:print()<< object-b received: a local-only message from a
[03/08 02:11:18] [DEBUG] script:print()<< object-a received: a local-only message from a
[03/08 02:11:18] [DEBUG] script:print()<< object-b received: a local-only message from a
[03/08 02:11:20] [DEBUG] script:print()<< object-a received: a local-only message from a
[03/08 02:11:20] [DEBUG] script:print()<< object-b received: a local-only message from a
[03/08 02:11:22] [DEBUG] script:print()<< object-a received: a message from b
[03/08 02:11:22] [DEBUG] script:print()<< object-b received: a message from b
[03/08 02:11:23] [DEBUG] script:print()<< object-a received: a message from b
[03/08 02:11:23] [DEBUG] script:print()<< object-b received: a message from b
````

**Pull request merged**
