### PR TITLE
Case 19446 - Update via Sandbox Popup -- opens Old Interface

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.manuscript.com/f/cases/19446/Update-via-Sandbox-Popup-opens-Old-Interface

### CODE REVIEW

**Comment by howard-stearns** [comment]
Test plan is to make sure that it fixes the ticket.

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14269/HighFidelity-Beta-PR14253-91f9227.apk

**Comment by roxanneskelly** [comment]
Test Plan
Setup:
* Install Interface + Sandbox (uncheck 'start interface' and 'start sandbox')
* Edit c:/Program Files/High Fidelity PR14253/server-console/build-info.json
* Change the releaseType value to "PRODUCTION"
* Change the buildNumber to "9400"

For OSX, the location is /Applications/High Fidelity PR14253/Sandbox.app/Contents/Resources/build-info.json

Test Upgrade Notification:
* Start Sandbox
* Validate "Update Version" notification appears
* Click on notification and validate web browser comes up and download of the installer commences

Test Connection Notification:
* Wait for friend/connection notification to pop up
* Click friend/connection notification and validate the interface starts and you're teleported to your connection's location.

Test Gift Notification:
* Give a gift to the user
* Validate notification comes up
* Click on notification, and validate that the Wallet app comes up when the interface starts.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14269/HighFidelity-Beta-PR14253-91f9227.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14269/HighFidelity-Beta-Interface-PR14253-91f9227.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14269/HighFidelity-Beta-PR14253-91f9227.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14269/HighFidelity-Beta-Interface-PR14253-91f9227.dmg

**Comment by rickcarr044** [comment]
Currently testing PR14253

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14296/HighFidelity-Beta-PR14253-91f9227.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14298/HighFidelity-Beta-PR14253-a6fcf79.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14298/HighFidelity-Beta-PR14253-a6fcf79.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14298/HighFidelity-Beta-Interface-PR14253-a6fcf79.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14298/HighFidelity-Beta-PR14253-a6fcf79.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14298/HighFidelity-Beta-Interface-PR14253-a6fcf79.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14321/HighFidelity-Beta-PR14253-10ee5ac.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14321/HighFidelity-Beta-PR14253-10ee5ac.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14321/HighFidelity-Beta-Interface-PR14253-10ee5ac.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14321/HighFidelity-Beta-PR14253-10ee5ac.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14321/HighFidelity-Beta-Interface-PR14253-10ee5ac.exe

**Pull request merged**
