### PR TITLE
Case 21167: When using Oculus HMD, continue to track hand position and movement when focus is off High Fidelity

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.manuscript.com/f/cases/21167/When-using-Oculus-HMD-continue-to-track-hand-position-and-movement-when-focus-is-off-High-Fidelity

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan 
- under settings > controls, in the calibration tab...the is now a Oculus plugin configuration settings which looks like this 
image

- when that button is enable, your hand controllers should still track when you press the oculus home button.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17849/HighFidelity-Beta-PR15090-be79ad1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17849/HighFidelity-Quest-Beta-PR15090-be79ad1.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17849/HighFidelity-Beta-PR15090-be79ad1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17849/HighFidelity-Beta-Interface-PR15090-be79ad1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17857/HighFidelity-Beta-PR15090-1fd70af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17857/HighFidelity-Beta-Interface-PR15090-1fd70af.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17857/HighFidelity-Beta-PR15090-1fd70af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17857/HighFidelity-Quest-Beta-PR15090-1fd70af.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17857/HighFidelity-Beta-PR15090-1fd70af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17857/HighFidelity-Beta-Interface-PR15090-1fd70af.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17891/HighFidelity-Beta-PR15090-1941e53.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17891/HighFidelity-Quest-Beta-PR15090-1941e53.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17891/HighFidelity-Beta-PR15090-1941e53.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17891/HighFidelity-Beta-Interface-PR15090-1941e53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17891/HighFidelity-Beta-PR15090-1941e53.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17891/HighFidelity-Beta-Interface-PR15090-1941e53.exe

**Pull request merged**
