### PR TITLE
fix a confusing comment about min cores required

### PR DESCRIPTION
**Pull request by birarda**
- fix a comment in min spec check

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Notes

Read the code. Test that your brain is not confused by new comment.

**Comment by Atlante45** [comment]
Read code. Brain confused. QA Fail.

**Comment by birarda** [comment]
@Atlante45 that sounds like French user error

**Comment by Atlante45** [comment]
Does not compute

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c1f99954b5983ad96e8d2374b7f41a1a93435eb available at: https://gist.github.com/e180ab31ea9d75f5d59958e8bfadefe1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9216-4c1f999.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9216-4c1f999.dmg

**Pull request merged**
