### PR TITLE
add a tablet contextual mode flag to HMDScriptingInterface used to keep tablet in place

### PR DESCRIPTION
**Pull request by dback2**
- add default false _tabletContextualMode flag to HMDScriptingInterface and expose property
- set _tabletContextualMode to passed in flag contextualMode (which is default false) in openTablet()
- reset _tabletContextualMode back to false in closeTablet()
- block attachment updates in showTabletUI() in tabletUI.js when tablet is in contextual mode

This will fix issues where we hijack the tablet for contextual purposes (i.e. avatar store checkout zone) and where the position and rotation that we force it to sometimes get reset to default attachment settings after opening the tablet.

Testing:

Behavior without the fix:
- Import JSON file - https://hifi-content.s3.amazonaws.com/davidback/development/avatarshop/checkoutZone_noContextualMode.json
- Enter HMD mode and approach the front of the checkout scanner to see tablet open
- Move away from checkout scanner to exit checkout zone and which will close tablet and then re-enter checkout zone to see tablet open again
- After entering and leaving the checkout zone a few times you should see the tablet sometimes reset back to default attachment settings (directly in front of camera and facing camera) as opposed to being forced into place angled over the right side of the checkout scanner

Behavior with the fix:
- Import JSON file - https://hifi-content.s3.amazonaws.com/davidback/development/avatarshop/checkoutZone_contextualMode.json
- Enter and leave this new checkout zone a few times and notice the tablet should now be forced into place angled over the right side of the checkout scanner every time you enter the checkout zone
- Closing/opening the tablet in HMD mode using the controller menu buttons while remaining in the checkout zone will reset the tablet to default attachment settings (directly in front of camera and facing camera) upon re-opening it instead of placing it over the right side of the checkout scanner
- Opening the tablet in HMD mode using controller menu buttons after leaving the checkout zone should put it back to default attachment settings

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4363/HighFidelity-Beta-PR11655-80dc98b2c2403c71f1011fed6134292dd5dcae28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4363/HighFidelity-Beta-PR11655-80dc98b2c2403c71f1011fed6134292dd5dcae28.exe

**Comment by Nex-Pro** [comment]
T E S T I N G

**Comment by Nex-Pro** [comment]
### PASS

Within the zone the ablet acts in the prescribed manner.

After leaving the zone it reverts to the default behaviour.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4401/HighFidelity-Beta-PR11655-08a6eb4dd399ef4f5cdeca95ae4ab8fb50efe97f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4401/HighFidelity-Beta-PR11655-08a6eb4dd399ef4f5cdeca95ae4ab8fb50efe97f.exe

**Comment by dback2** [comment]
Changes to test:

- Closing/opening the tablet in HMD mode using the controller menu buttons while remaining in the checkout zone will reset the tablet to default attachment settings (directly in front of camera and facing camera) upon re-opening it instead of placing it over the right side of the checkout scanner

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Closing/opening the tablet in HMD mode using the controller menu buttons while remaining in the checkout zone will reset the tablet to default attachment settings (directly in front of camera and facing camera) upon re-opening it instead of placing it over the right side of the checkout scanner | Pass

All good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by misslivirose** [comment]
@nimisha20 this reads on the HMDScriptingInterface docs

**Pull request merged**
