### PR TITLE
Close 'goto' app on pressing 'forward' / 'backward' buttons

### PR DESCRIPTION
**Pull request by ElderOrb**
https://github.com/highfidelity/hifi/pull/12832 for RC66

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8620/app_12833_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8620/HighFidelity-Beta-PR12833-faddc556d7fa0c277e5fede9ea70ae75d5149c07.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8620/HighFidelity-Beta-PR12833-faddc556d7fa0c277e5fede9ea70ae75d5149c07.exe

**Comment by sethalves** [comment]
**Test plan**

0) Switch to desktop
1) Open Go To and navigate to a different domain
2) Open Go To and select the back button to navigate back to previously visited domain
3) Ensure Go To window closed
4) Open Go To and select forward to navigate to previously visited domain
3) Ensure Go To window closed

https://highfidelity.manuscript.com/f/cases/14015/Go-To-app-does-not-close-when-selecting-forward-and-back-arrows-on-desktop

**Comment by howard-stearns** [comment]
It would be cool if we'd take this opportunity to fix https://highfidelity.fogbugz.com/f/cases/13974/return-key-broken-again

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Forward and backward arrows in the goto app will now close the app after teleporting the user.

**Pull request merged**
