### PR TITLE
Opened up setForceFaceTrackerConnected

### PR DESCRIPTION
**Pull request by Menithal**
As per @humbletim's suggestion. Opened this up for some interesting applications.  enabling setForceFaceTrackerConnected allows set blendshapes to be transmitted to other users. This allows for interesting control of the avatar's face, and probably allowing avatars to emote again.

https://www.youtube.com/watch?v=oCDC_EA2yWE

And this is especially interesting when paired with the camera, and a control method for the avatar face expressions.

https://www.youtube.com/watch?v=pXfK2tlsjhI

This is an Experimental Non Worklist item.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2114/HighFidelity-Beta-PR11083-9ec14057f01a67f98fa9bb27bdef3dcddec8d9b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2114/HighFidelity-Beta-PR11083-9ec14057f01a67f98fa9bb27bdef3dcddec8d9b3.exe

**Comment by Menithal** [comment]
Discussion is open for renaming the function as well (setForceFaceTrackerConnected is a bit unwieldy, and I think its not used elsewhere) Perhaps setTransmitBlendshape()?

**Comment by themelissabrown** [comment]
@Menithal Can you add a test plan?

**Comment by Menithal** [comment]
Test Requirements:

You need to have a friend or able to turn on two clients:
One client to set the shapes at (Client A), another to see that they get transmitted (Client B).

Test Plan:
Use Wood Mannequin Avatar on A

1. A: in Script Console:`MyAvatar.setForceFaceTrackerConnected(true);`
2. A: in Script Console: `MyAvatar.setBlendshape("JawOpen", 1.0);`
3. A: in Script Console: `MyAvatar.setBlendshape("LipsFunnel", 1.0);`
4. Client B should see User A should have their mouth open and in O shape-ish

**Comment by cain-kilgore** [comment]
Hey @Menithal: Just waiting for the QA Ready tag for this and I'll be happy to have a go.

**Comment by YuppyPlays** [comment]
Testing. (w/ Cain)

**Comment by YuppyPlays** [comment]
@Menithal  It seems the build is broken (will not download, brings up XML error page)

Can we get a re-build?, thank you :)

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2447/HighFidelity-Beta-PR11083-9ec14057f01a67f98fa9bb27bdef3dcddec8d9b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2447/HighFidelity-Beta-PR11083-9ec14057f01a67f98fa9bb27bdef3dcddec8d9b3.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by cain-kilgore** [comment]
a2cc186d-83d7-4945-a889-0393b1d579c5

**Pull request merged**
