### PR TITLE
cleanly log failed entity adds, and tell the client to delete his copy

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
- Add an entity without having rez or rez-temp rights. Should log on server, and you shouldn't see the added entity for more than a moment on the client.
- With rez rights restored, but without lock rights, add an entity server filter that rejects something completely. E.g., function filter() { return false; } will do.  Now add something that triggers the filter. Should log on server, and you shouldn't see the added entity for more than a moment on the client.
- Give yourself lock rights or remove the filter, and everything should add normally.

**Comment by hifi-gustavo** [comment]
Build console output for commit: e42853a96c0237a95866c248b81c850956893e25 available at: https://gist.github.com/0c3d68057fb5b343fc72b1d3df090b55<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9574-e42853a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9574-e42853a.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e42853a96c0237a95866c248b81c850956893e25 available at: https://gist.github.com/0c3d68057fb5b343fc72b1d3df090b55<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9574-e42853a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9574-e42853a.dmg

**Pull request merged**
