### PR TITLE
loopback local injectors on server echo

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
QA:

Create a sound using:
```
var sound = SoundCache.getSound("https://s3.amazonaws.com/hifi-public/philip/short440.wav");
```

Wait a moment (it needs to load), then start an injector:
```
Audio.playSound(sound);
```

On the current build, this cannot be echoed from the server.
On this build, you should be able to echo it (and hear it twice). Enable server echo using `Developer > Audio > Echo Server Audio`.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 768354e49f915cd29bfa0c4a698b7840099778f9 available at: https://gist.github.com/ac260d2b1fc2d32b3e2b97b49349e28e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8687-768354e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8687-768354e.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:  Enabled Server Audio.  Opened up console and typed ```var sound = SoundCache.getSound("https://s3.amazonaws.com/hifi-public/philip/short440.wav");``` and then ```Audio.playSound(sound);```.  Attempted it several times.  No sound was echoed.  SEE ATTACHMENT.
capture

**Comment by zzmp** [comment]
Sorry @kevinmthomasse, this appears to have lost a commit when I rebased it. I'll fix it up right now.

**Comment by zzmp** [comment]
@kevinmthomasse did you hear any sound at all?

**Comment by zzmp** [comment]
QA (@kevinmthomasse):

I believe the issue is that the sound was too far away from you, especially if you were in standard home space.

Try this:
```
var sound = SoundCache.getSound("https://s3.amazonaws.com/hifi-public/philip/short440.wav");
var injector = Audio.playSound(sound, { position: Vec3.sum(MyAvatar.position, Quat.getFront(MyAvatar.orientation)) });
```

Also, there is currently a separate bug (fixed in #8688) where non-local audio injectors will buzz. This will happen for the echo. You may not be able to hear the double-beep (if you have good latency), but you will be able to hear the horrible buzzing sound that the audio-mixer adds after the injector. This will be a sign of a pass. Do not fail because of buzzing, it is fixed separately.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Enabled Server Audio.  Opened up console and typed ```var sound = SoundCache.getSound("http://xiph.org/~xiphmont/demo/1kHz-0-dither.wav");
Audio.playSound(sound, { position: Vec3.sum(MyAvatar.position, Quat.getFront(MyAvatar.orientation)), loop: true, localOnly: false, volume: 1.0 });``` to which a 1kHz sustained tone was heard.

**Pull request merged**
