### PR TITLE
fix skybox bake assert on HDR_FORMAT static order initialization

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8685/app_12854_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8685/HighFidelity-Beta-PR12854-cd650f7bd1e7e2b3e70fde81a75f375713e23971.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8685/HighFidelity-Beta-PR12854-cd650f7bd1e7e2b3e70fde81a75f375713e23971.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10548/HighFidelity-Beta-PR12854-016a6dc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10548/HighFidelity-Beta-PR12854-016a6dc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10548/HighFidelity-Beta-Interface-PR12854-016a6dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10548/HighFidelity-Beta-PR12854-016a6dc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10548/HighFidelity-Beta-Interface-PR12854-016a6dc.exe

**Comment by birarda** [comment]
This doesn't require QA - a local macOS oven in debug crashes while baking a skybox without the change.

**Pull request merged**
