### PR TITLE
Fix script engine crashes when reloading scripts.

### PR DESCRIPTION
**Pull request by danteruiz**
This PR addresses the crashes on mac when user restarts scripts.

ticket - https://highfidelity.manuscript.com/f/cases/20036/Mac-Crashes-when-relaoding-scripts

duplicate ticket - https://highfidelity.manuscript.com/f/cases/resolve/20036/Mac-Crashes-when-relaoding-scripts

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- interface should not crash on windows or mac when reloading all script or an individual script

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15424/HighFidelity-Beta-PR14478-c4b6474.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15424/HighFidelity-Beta-PR14478-c4b6474.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15424/HighFidelity-Beta-Interface-PR14478-c4b6474.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15431/HighFidelity-Beta-PR14478-c4a9ca3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15431/HighFidelity-Beta-PR14478-c4a9ca3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15431/HighFidelity-Beta-Interface-PR14478-c4a9ca3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15431/HighFidelity-Beta-PR14478-c4a9ca3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15431/HighFidelity-Beta-Interface-PR14478-c4a9ca3.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
