### PR TITLE
Additional work on splash screen

### PR DESCRIPTION
**Pull request by jherico**
This PR is additional work to support a splash screen frame (either on HMD or desktop).  Currently the splash frame is disabled due to stuttering issues, but the remainder of the work should be tested and merged.

## Testing

This code should have no visible effect on the application as it just changes the order of some startup code.  

* Verify startup / shutdown without crashing
* Verify display plugin setting properly preserved on shutdown / startup
* Verify that the Oculus HMD view is stable and does not judder (any more than master) as you turn your head in a typical domain.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8964/HighFidelity-Beta-PR12947-dafa23b8700223ecb150dfeb860d5270fdea5442.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8964/HighFidelity-Beta-Interface-PR12947-dafa23b8700223ecb150dfeb860d5270fdea5442.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8964/HighFidelity-Beta-PR12947-dafa23b8700223ecb150dfeb860d5270fdea5442.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8964/HighFidelity-Beta-Interface-PR12947-dafa23b8700223ecb150dfeb860d5270fdea5442.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8994/app_12947_PR_d00b0c9e846b9513ebacaf74da06b13c597597bf.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8994/HighFidelity-Beta-PR12947-d00b0c9e846b9513ebacaf74da06b13c597597bf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8994/HighFidelity-Beta-Interface-PR12947-d00b0c9e846b9513ebacaf74da06b13c597597bf.exe

**Comment by samcake** [comment]
Just testing latest build, i get a crash on start :(

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9133/app_12947_PR_79bfe896008cda99efacdd969bfee14c6f368d7b.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9142/app_12947_PR_79bfe896008cda99efacdd969bfee14c6f368d7b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9142/HighFidelity-Beta-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9142/HighFidelity-Beta-Interface-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9142/HighFidelity-Beta-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9142/HighFidelity-Beta-Interface-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.exe

**Comment by samcake** [comment]
build this please

**Comment by samcake** [comment]
I keep crashing when i try to run the build from 2 days ago

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9236/app_12947_PR_79bfe896008cda99efacdd969bfee14c6f368d7b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9236/HighFidelity-Beta-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9236/HighFidelity-Beta-Interface-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9236/HighFidelity-Beta-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9236/HighFidelity-Beta-Interface-PR12947-79bfe896008cda99efacdd969bfee14c6f368d7b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9385/app_12947_PR_a22db103dc588dc5e3b060e7c6306edf5b910057.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Startup and shutdown look good, plugin state is saved successfully, and there is no jittering in HMD.

**Comment by samcake** [comment]
@conklin94122 Can we green QA and MERge ?

**Comment by conklin94122** [comment]
@samcake Does it require Android testing? If it does I need a little time to make that happen. @divyaelango88 ?

**Comment by conklin94122** [comment]
@divyaelango88 Is going to handle this testing today.

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9511/app_12947_PR_a22db103dc588dc5e3b060e7c6306edf5b910057.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9511/HighFidelity-Beta-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9511/HighFidelity-Beta-Interface-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9511/HighFidelity-Beta-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9511/HighFidelity-Beta-Interface-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9530/app_12947_PR_a22db103dc588dc5e3b060e7c6306edf5b910057.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9530/HighFidelity-Beta-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9530/HighFidelity-Beta-Interface-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.exe

**Comment by divyaelango88** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9530/HighFidelity-Beta-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9530/HighFidelity-Beta-Interface-PR12947-a22db103dc588dc5e3b060e7c6306edf5b910057.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9537/app_12947_PR_38f43bdc6802e695cb78470eb65a75c62fd027de.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9537/HighFidelity-Beta-PR12947-38f43bdc6802e695cb78470eb65a75c62fd027de.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9537/HighFidelity-Beta-Interface-PR12947-38f43bdc6802e695cb78470eb65a75c62fd027de.exe

**Comment by qlimnavarro** [comment]
Pass on Android @conklin94122 
https://highfidelity.testrail.net/index.php?/plans/view/4161 Smoke passes.

**Pull request merged**
