### PR TITLE
Case 20625: On avatar project creation, the .fbx filter for selecting an FBX is case-sensitive.

### PR DESCRIPTION
**Pull request by thoys**
https://highfidelity.manuscript.com/f/cases/20625/On-avatar-project-creation-the-fbx-filter-for-selecting-an-FBX-is-case-sensitive

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18472/HighFidelity-Beta-PR15292-7e21a3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18472/HighFidelity-Beta-Interface-PR15292-7e21a3f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18472/HighFidelity-Beta-PR15292-7e21a3f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18472/HighFidelity-Quest-Beta-PR15292-7e21a3f.apk)

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18491/HighFidelity-Beta-PR15292-7e21a3f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18491/HighFidelity-Beta-Interface-PR15292-7e21a3f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18491/HighFidelity-Beta-PR15292-7e21a3f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18491/HighFidelity-Beta-Interface-PR15292-7e21a3f.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18491/HighFidelity-Beta-PR15292-7e21a3f.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18491/HighFidelity-Quest-Beta-PR15292-7e21a3f.apk)

**Pull request merged**
