### PR TITLE
Improvements to gracefulControls.js

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/214/HighFidelity-Beta-PR10562-ef1efa58d3f1683e91044f30f8c2909c68300bcf.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/214/HighFidelity-Beta-PR10562-ef1efa58d3f1683e91044f30f8c2909c68300bcf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/220/HighFidelity-Beta-PR10562-ae55e3969eacfb318bfdb88faff700d6753491bb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/220/HighFidelity-Beta-PR10562-ae55e3969eacfb318bfdb88faff700d6753491bb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/245/HighFidelity-Beta-PR10562-e562ea197b085a8ea70057f923b99ce0dfcd4e0c.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/247/HighFidelity-Beta-PR10562-b95a2180e832df62bc7c77e616c32106f2d7c3fb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/247/HighFidelity-Beta-PR10562-b95a2180e832df62bc7c77e616c32106f2d7c3fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/313/HighFidelity-Beta-PR10562-2680fb15948e68eeea452ec2d4d63bbe3da89cec.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/313/HighFidelity-Beta-PR10562-2680fb15948e68eeea452ec2d4d63bbe3da89cec.dmg

**Comment by huffman** [comment]
To test:

 1. Run https://raw.githubusercontent.com/huffman/hifi/2680fb15948e68eeea452ec2d4d63bbe3da89cec/script-archive/gracefulControls.js
 2. Press `space` to toggle the graceful controls mode.
 3. Move around, mouse look and avatar motion should be smooth.
 4. Pressing `space` again should toggle it off.
 5. Try breaking it. Press different keys while moving, etc... We really want to avoid having keys get stuck where you can't stop moving.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Run script provided. **Pass**
Press space to toggle the graceful controls mode.**Pass**
Move around, mouse look and avatar motion should be smooth.**Pass**
Pressing space again should toggle it off.**Pass**
Try breaking it. Press different keys while moving, etc... We really want to avoid having keys get stuck where you can't stop moving.**Pass** Tried to break it but I couldn't find anything that made it act unexpected, though should be mentioned if it's not intentional is the fly button does not function.

Notes: Mouse stays overlaid on screen when graceful controls was enabled.

Hope this helps.

**Comment by huffman** [comment]
Thanks @YuppyPlays !

**Pull request merged**
