### PR TITLE
Add eslintrc file

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
Added an eslint config file to the root of `scripts/` directory.  It is configured to enforce the official coding standard.

To Test:

1. [Install][integrations] the eslint plugin for your favorite text editor
2. Open a script file, it should highlight code style violations

**OR**

1. [Install][cli] the command line interface
2. Run `eslint -c .eslintrc.js --color path/to/your/script.js` from the `scripts/` directory, replacing `path/to/your/script.js` with any script you suspect of violating the coding standard.

[integrations]: http://eslint.org/docs/user-guide/integrations
[cli]: http://eslint.org/docs/user-guide/command-line-interface

### CODE REVIEW

**Comment by ZappoMan** [comment]
this should probably be in script-archive not in scripts

**Comment by AlexanderOtavka** [comment]
@ZappoMan Are we still making changes to script-archive?  I thought it was just old scripts.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 15fbff4ffb1ebc2225d7234ee820c2334978a755 available at: https://gist.github.com/8bcd1d55672a13aa25621f06bb81c262<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8132.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8132.dmg

**Comment by ZappoMan** [comment]
scripts gets published with the installer... we don't want this script to
be included in the installer

**Comment by AlexanderOtavka** [comment]
@ZappoMan could I put it in the project root then, or do we want to keep that clean?  If I put it in `script-archive/`, most plugins won't use it when linting `scripts/`.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 55c2466249d65875f2a65e04a520de976edb4f34 available at: https://gist.github.com/8bcd1d55672a13aa25621f06bb81c262<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8132.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8132.dmg

**Comment by AndrewMeadows** [comment]
The root directory seems like the right place for the .eslint.js file.  It is a resource that specifies our javascript rules.  Developers who have properly configured their editor/IDE for eslint support should be able to find and use it.

**Pull request merged**
