### PR TITLE
reduce log spam

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by ZappoMan** [comment]
Test Plan:
- Smoke Test
- Make sure to use hand controllers to control the mouse
- verify that the messages: "Cannot seek without lookAt position" and "Controller is parallel to HUD" do not spam your log.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53956c8210b1f93363e5c3f12deee002bb4234e7 available at: https://gist.github.com/79a86959c43c8461e21a250de59ec8fe<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7935.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7935.dmg

**Comment by howard-stearns** [comment]
Under what circumstances are these messages spamming the log? They should be exceedingly rare, and are intended to indicate a possible problem. 

Maybe it's some cross condition, such as not being the focused window or some such, which could be guarded rather than losing the diagnostics all together?

**Comment by ZappoMan** [comment]
These were spamming Philip's logs this morning on his "high end Vive
capable laptop"...

He was using the Vive.

I can imagine that he would be outside the HUD and these would spam? I'm
guessing from looking at the code.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Microphone UI in bottom right hand corner, also seen in other recent PRs as well. Successful smoke test. Successfully utilized hand controllers to control the mouse and when placing down controllers the mouse acts normally and verified that the messages: "Cannot seek without lookAt position" and "Controller is parallel to HUD" do not spam log.

**Domain** |localhost |Playa |cellscience
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |58 |60
**CPU Buffer Count**: |3048 |3553 |989
**GPU Buffer Count**: |622 |370 |238
**CPU Memory Usage**: |47460352 |67506176 |23805952
**GPU Memory Usage**: |13979648 |12685312 |9420800
**CPU Texture Count**: |287 |325 |160
**GPU Texture Count**: |193 |192 |145
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |198488820 |835807232 |23135304
**GPU Texture Memory Usage**: |1654729180 |1664349311 |1459667046
**GPU Virtual Memory Usage**: |1654729180|1664349311|1459667046
**Triangle Count**: |246364 |295632 |230220
**Triangle Rate**: |15397750 |18477000 |14388750
**API Drawcall Count**: |188 |107 |46
**Drawcall Count**: |192 |228 |46
**Drawcall Rate**: |12000 |14250 |2875
**State Changes Texture Count**:|155 |127 |36
**Pipeline Count**: |23 |22 |18
**Item Opaques**: |234 |159 |44
**Item Translucents**: |7 |4 |16
**Item Lights**: |20 |17 |0
**Timing Opaques**: |1458 |1144 |511
**Timing Translucents**: |90 |83 |243
**Timing Lighting**: |126 |237 |70
**Render Frame**: |2408 |2399 |1626

**Pull request merged**
