### PR TITLE
Updating to the new version of the sixense library

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5902758e94d4508b1cf21f42c78d9781fa3fbbd6 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 354bb1d895f6c9d25dc4505c39973788b3e07d1c available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 18f9ea7b67e723c701f8faf5ba1399663a681367 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39ad5cf1c9f1f242682dc18bc9be3c15cd9ec505 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by jherico** [comment]
test this please

**Comment by howard-stearns** [comment]
This seems to fix the recently introduced problem in which cmake was not finding my sixsense library. Yay!

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39ad5cf1c9f1f242682dc18bc9be3c15cd9ec505 available at: https://gist.github.com/caa2f148aac57eb02cd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39ad5cf1c9f1f242682dc18bc9be3c15cd9ec505 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by sethalves** [comment]
I built this on windows and it didn't seem to make anything worse.

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa6f3f3b261fa7cf39197ca975be52427573da1e available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 054ec90ca7d81c5d81271599e7561057056e9c83 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59863ee6e5113649241e65e7197316fad6be5a1e available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b484db575951cab71c67c74842b506e87381cae6 available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7f09df1d0ba4877a6a9c7b032dab6bc25e8f389c available at: https://gist.github.com/7f45a7770c65a75eb4d4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5582.dmg

**Comment by OmegaHeron** [comment]
Did this PR intentionally (or unintentionally) make six sense libraries a requirement to build?  I'm now getting a cmake error trying to build assignment-client/domain-server on linux due to missing six sense libraries.

**Pull request merged**
