### PR TITLE
Fix AddressManager copyAddress/copyPath functionality

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fix for MS[#16444](https://highfidelity.manuscript.com/f/cases/16444/)

**Test Plan**
For copying address in using the menu:
- Launch Interface (in Desktop Mode)
- Go to any domain
- In menu, click `Navigate > Copy Address To Clipboard`
- Paste copied address somewhere (should not crash)
- Go to another, different domain
- In menu, click `Navigate > Copy Address To Clipboard`
- Paste copied address somewhere (should not crash and should be different from previously pasted result)

For copying path in using the menu:
- Launch Interface (in Desktop Mode)
- Go to any domain
- In menu, click `Navigate > Copy Path To Clipboard`
- Paste copied path somewhere (should not crash)
- Move around in the domain
- In menu, click `Navigate > Copy Path To Clipboard`
- Paste copied path somewhere (should not crash and should be different from previously pasted result)

For `location.copyAddress()`:
- Launch Interface (in Desktop Mode)
- Enable developer menus by clicking `Settings > Developer Menu`
- Open Console in `Developer > Console...`
- Go to any domain
- In Console, type `location.copyAddress()`
- Paste copied address somewhere (should not crash)
- Go to another, different domain
- In Console, type `location.copyAddress()`
- Paste copied address somewhere (should not crash and should be different from previously pasted result)

For `location.copyPath()`:
- Launch Interface (in Desktop Mode)
- Enable developer menus by clicking `Settings > Developer Menu`
- Open Console in `Developer > Console...`
- Go to any domain
- In menu, click `location.copyPath()`
- Paste copied path somewhere (should not crash)
- Move around in the domain
- In menu, click `location.copyPath()`
- Paste copied path somewhere (should not crash and should be different from previously pasted result)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11168/HighFidelity-Beta-PR13559-cb89b04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11168/HighFidelity-Beta-Interface-PR13559-cb89b04.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11168/HighFidelity-Beta-PR13559-cb89b04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11168/HighFidelity-Beta-Interface-PR13559-cb89b04.exe

**Comment by qlistephens95** [comment]
Currently Testing

**Comment by qlistephens95** [comment]
PASSED. Verified that "navigate>copy address to clipboard" and "navigate>copy path to clipboard" properly function along with "developer>console: location.copyAddress()" and "developer>console: location.copypath()"

**Comment by Qliemillar** [comment]
@conklin94122 ^^^

**Pull request merged**
