### PR TITLE
Fix tablet not disappearing

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.fogbugz.com/f/cases/15665/HMD-Buggy-Tablet-Behavior

Test plan:
- Perform the steps in the ticket.  The tablet should behave normally.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10448/HighFidelity-Beta-PR13334-c7007c0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10448/HighFidelity-Beta-PR13334-c7007c0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10448/HighFidelity-Beta-Interface-PR13334-c7007c0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10448/HighFidelity-Beta-PR13334-c7007c0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10448/HighFidelity-Beta-Interface-PR13334-c7007c0.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Tablet is removed and disappears as expected. Defect no longer occurs.

**Pull request merged**
