### PR TITLE
Various changes to installer

### PR DESCRIPTION
**Pull request by murillodigital**
1) Scripts are now copied next to interface.exe in a scipts/ directory, this is a step towards using local scripts when available.

2) A single uninstall entry in Programs and Features was created, thus the most recent PR build install clobbered the previous PR uninstall entry, this is also fixed.

3) PR vs Release builds now get correct icons (red vs blue) and a red icon was introduced for the stack manager.

4) Lots of changes to installer, option to choose install components, unprivileged install directory for Stack Manager and stack, fixed uninstaller, etc.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1bac2f9bd61df4841e03bf8f5a550a30a6f80da available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aca60e23c27acd4ff762f5da6a89937e89c94312 available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by murillodigital** [comment]
pushing some additional changes to this same branch

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ead1de3ab90713a5d5b4dd30f3b617e0fc9f5da available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by murillodigital** [comment]
@PhilipRosedale please take a look at the installer in that last comment and let me know what you think.

**Comment by imgntn** [comment]
the installer works for me on win 8 at home

**Comment by PhilipRosedale** [comment]
The installer works for me.  We need some changes to contemplate the changes to get the installer in final beta form, I have created a list for Leo.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ea6850c42385bd83a0883ece1573472d9c4115f8 available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2bad5437a9f82c6b0483c62aeefd24aab358f425 available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0bd823e20ca107f96737bce2afab9a5979a7b2bd available at: https://gist.github.com/c29dcf82e3413e08fcd3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6694.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6694.dmg

**Comment by birarda** [comment]
Closing this since it goes with #6750 now.

**Pull request closed without merging**
