### PR TITLE
Improve seated rotation

### PR DESCRIPTION
**Pull request by DouglasWilcox**
Add support for acceleration in seated rotation, and trigger lean animation with inputs as well as transition and settle back to seated idle.  Remove deadspot beyond 90 degrees where Q/E don't work.  

https://highfidelity.atlassian.net/browse/DEV-2372

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22572/HighFidelity-Beta-PR16498-d9065af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22572/HighFidelity-Quest-Beta-PR16498-d9065af.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22572/HighFidelity-Beta-PR16498-d9065af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22572/HighFidelity-Beta-Interface-PR16498-d9065af.dmg

**Comment by DouglasWilcox** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22577/HighFidelity-Beta-PR16498-d9065af.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22577/HighFidelity-Beta-Interface-PR16498-d9065af.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22577/HighFidelity-Beta-PR16498-d9065af.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22577/HighFidelity-Quest-Beta-PR16498-d9065af.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22577/HighFidelity-Beta-PR16498-d9065af.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22577/HighFidelity-Beta-Interface-PR16498-d9065af.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22592/HighFidelity-Beta-PR16498-ddbb8d7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22592/HighFidelity-Quest-Beta-PR16498-ddbb8d7.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22592/HighFidelity-Beta-PR16498-ddbb8d7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22592/HighFidelity-Beta-Interface-PR16498-ddbb8d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22592/HighFidelity-Beta-PR16498-ddbb8d7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22592/HighFidelity-Beta-Interface-PR16498-ddbb8d7.exe

**Pull request merged**
