### PR TITLE
Keep textureBaseUrl for fst models

### PR DESCRIPTION
**Pull request by zzmp**
With #7533, fst models no longer load textures, as the textures are reloaded from a bare filepath. The base URL (the fst) is not persisted between the geometry definition and the mapping.

This fixes that by resolving the _textureBaseUrl in the GeometryMappingResource so that reloaded textures are loaded from the correct, qualified filepath.

### CODE REVIEW

**Comment by zzmp** [comment]
@Menithal sorry we broke .fst in #7533 :(.

It looked like this is where I broke it in that PR. Hopefully this fixes it. I'm home on my wimpy laptop so I can't actually test this until tomorrow morning, but if it builds please run your model through it and make sure its ok.

**Comment by Menithal** [comment]
@zzmp, Thanks!
 Ill test this as soon as I get home for work.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2028a1c8bb6f2a9b212a5b75b0af693b7f1e465 available at: https://gist.github.com/523797dcd82f8898a52a99fd591b2ea8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7537.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7537.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - This does **not** fix issue with my Blender created avatar.  Prior to PR7533 I would see this as my AV loads

`[04/01 11:06:12] [DEBUG] Finished loading: https://my-asset-server-obfuscated/av/tex/Hair_Specular.png`
 
Since 7533 and including this one I only see

`[04/01 11:08:28] [DEBUG] Error loading  QUrl("Hair_Specular.png")`
`[04/01 11:08:28] [DEBUG] Failed to load: Hair_Specular.png`

Same with a model having embedded textures -  I see this 

`[04/01 11:09:38] [DEBUG] Finished loading: atp:/skyisland1.fbx`
`[04/01 11:09:38] [DEBUG] Error loading  QUrl("Grass.jpg")`
`[04/01 11:09:38] [DEBUG] Failed to load: Grass.jpg`

Grass.jpg is an embedded texture with fbx

All models in question created with Blender.

**Comment by OmegaHeron** [comment]
Before 7533 Sky Island load looks like this;

`[04/01 11:29:30] [DEBUG] Starting request for: atp:/skyisland1.fbx`
`[04/01 11:29:30] [DEBUG] Got mapping for: "/skyisland1.fbx" => "231b8be587807496ffca25c884446df1ee0a92e826a1e57ab26edcce27737e42"`
`[04/01 11:29:30] [DEBUG] "atp:231b8be587807496ffca25c884446df1ee0a92e826a1e57ab26edcce27737e42" loaded from disk cache.`
`[04/01 11:29:30] [DEBUG] Request finished for atp:/skyisland1.fbx`
`[04/01 11:30:36] [DEBUG] Starting request for: atp:/Rock.jpg`
`[04/01 11:30:36] [DEBUG] Starting request for: atp:/noSpecular.png`
`[04/01 11:30:36] [DEBUG] Starting request for: atp:/Grass.jpg`
`[04/01 11:30:36] [DEBUG] Finished loading: atp:/skyisland1.fbx`
`[04/01 11:30:36] [DEBUG] Got mapping for: "/Rock.jpg" => "bf799250324526bcb97f539ef833cfa4dad77e787b732e502e266c5d62b34812"`
`[04/01 11:30:36] [DEBUG] "atp:bf799250324526bcb97f539ef833cfa4dad77e787b732e502e266c5d62b34812" loaded from disk cache.`
`[04/01 11:30:36] [DEBUG] Got mapping for: "/noSpecular.png" => "f62ffe8884e2c1658b933fba97b1dabb386604411f5b2513e182d0ed54f121bb"`
`[04/01 11:30:36] [DEBUG] "atp:f62ffe8884e2c1658b933fba97b1dabb386604411f5b2513e182d0ed54f121bb" loaded from disk cache.`
`[04/01 11:30:36] [DEBUG] Got mapping for: "/Grass.jpg" => "b769140c2b3ed3835b5cd308cf0738bb901593492cc11c23017cd4245235aa04"`
`[04/01 11:30:36] [DEBUG] "atp:b769140c2b3ed3835b5cd308cf0738bb901593492cc11c23017cd4245235aa04" loaded from disk cache.`
`[04/01 11:30:36] [DEBUG] Request finished for atp:/Rock.jpg`
`[04/01 11:30:36] [DEBUG] Request finished for atp:/noSpecular.png`
`[04/01 11:30:36] [DEBUG] Request finished for atp:/Grass.jpg`
`[04/01 11:30:36] [DEBUG] Finished loading: atp:/noSpecular.png`
`[04/01 11:30:37] [DEBUG] Finished loading: atp:/Rock.jpg`
`[04/01 11:30:37] [DEBUG] Finished loading: atp:/Grass.jpg`

Everything since shows

`[04/01 11:37:19] [DEBUG] Starting request for: atp:/skyisland1.fbx`
`[04/01 11:37:19] [DEBUG] Got mapping for: "/skyisland1.fbx" => "231b8be587807496ffca25c884446df1ee0a92e826a1e57ab26edcce27737e42"`
`[04/01 11:37:19] [DEBUG] "atp:231b8be587807496ffca25c884446df1ee0a92e826a1e57ab26edcce27737e42" loaded from disk cache.`
`[04/01 11:38:26] [DEBUG] Starting request for: Grass.jpg`
`[04/01 11:38:26] [DEBUG] Starting request for: noSpecular.png`
`[04/01 11:38:26] [DEBUG] Starting request for: Rock.jpg`
`[04/01 11:38:26] [DEBUG] Finished loading: atp:/skyisland1.fbx`
`[04/01 11:38:26] [DEBUG] Error loading  QUrl("Grass.jpg")`
`[04/01 11:38:26] [DEBUG] Failed to load: Grass.jpg`
`[04/01 11:38:26] [DEBUG] Error loading  QUrl("noSpecular.png")`
`[04/01 11:38:26] [DEBUG] Failed to load: noSpecular.png`
`[04/01 11:38:26] [DEBUG] Error loading  QUrl("Rock.jpg")`
`[04/01 11:38:26] [DEBUG] Failed to load: Rock.jpg`

And if the careful reader notices the tremendous lag from load of model time to start of texture load time it's due to - as far as I can tell - a unique to me issue.  That's a red herring in this case as it has no bearing on failure to load textures.

**Comment by zzmp** [comment]
I guess midnight coding wasn't super effective. Marking this DNM until I can fix and test it properly myself.

**Comment by zzmp** [comment]
Ok, ready for retesting.

@Menithal, @OmegaHeron thanks for your logs - immensely helpful to debug this.
It turned out I'd added the base url to the Geometry constructor but forgotten to add it to the implementation :tired_face:.

**Comment by zzmp** [comment]
https://app.asana.com/0/74051501495175/107448718339730

**Comment by hifi-gustavo** [comment]
Build console output for commit: 489a2fd0b97303def20b8fcbca6c8f7f02088099 available at: https://gist.github.com/523797dcd82f8898a52a99fd591b2ea8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7537.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7537.dmg

**Comment by OmegaHeron** [comment]
@zzmp - AV loads textures as does models with embedded and URL referenced.  :+1:

**Comment by Menithal** [comment]
Giving this a whirl.

**Comment by Menithal** [comment]
Can confirm, this is now working again, thanks for the quick fix.

**Pull request merged**
