### PR TITLE
Fixes for collisionless entities

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Fixes:
- Make collisionless entities able to be far grabbed.
- Keep collisionless property on collisionless entity after it's far grabbed.
- Fix HMD mouse pointer displaying at depth behind collisionless entities.
- Fix desktop mouse highlights collisionless, grabbable entities.
- Fix collisionless entities not able to be selected with lasers in Create app in HMD mode.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Create 4 entities:
a) Non-grabbable
b) Grabbable
c) Non-grabble, collisionless
d) Grabbable, collisionless

Tests:

1) Check collisionless entities can be far grabbed: Entities b and d should be able to be far grabbed (but a and c not).

2) Check that entity remains collisionless after far grabbing: Check that entity d is still collisionless after being far grabbed.

3) Check HMD mouse pointer goes on top of collisionless entities: In HMD mode, move your mouse so that the mouse pointer is displayed. The mouse should display at a depth just in front of each entity (i.e., not at a far distance for the collisionless entities).

4) Check the desktop mouse highlights grabbable, collisionless entities: In desktop mode, both entities b and d should be highlighted as you move the mouse pointer over them (i.e., not just entity b).

5) Check that you can use lasers to select all 4 entities in the Create app in HMD mode (i.e., edit handles display on them after you laser click them).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13856/HighFidelity-Beta-PR14204-7d3eca5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13856/HighFidelity-Beta-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13856/HighFidelity-Beta-Interface-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13856/HighFidelity-Beta-PR14204-7d3eca5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13856/HighFidelity-Beta-Interface-PR14204-7d3eca5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13890/HighFidelity-Beta-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13890/HighFidelity-Beta-Interface-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13905/HighFidelity-Beta-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13905/HighFidelity-Beta-Interface-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13905/HighFidelity-Beta-PR14204-7d3eca5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13905/HighFidelity-Beta-Interface-PR14204-7d3eca5.exe

**Comment by ctrlaltdavid** [comment]
Built this please

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13907/HighFidelity-Beta-PR14204-7d3eca5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13907/HighFidelity-Beta-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13907/HighFidelity-Beta-Interface-PR14204-7d3eca5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13907/HighFidelity-Beta-PR14204-7d3eca5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13907/HighFidelity-Beta-Interface-PR14204-7d3eca5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14126/HighFidelity-Beta-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14126/HighFidelity-Beta-Interface-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14126/HighFidelity-Beta-PR14204-3e49d55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14126/HighFidelity-Beta-Interface-PR14204-3e49d55.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14134/HighFidelity-Beta-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14134/HighFidelity-Beta-Interface-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14134/HighFidelity-Beta-PR14204-3e49d55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14134/HighFidelity-Beta-Interface-PR14204-3e49d55.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14324/HighFidelity-Beta-PR14204-3e49d55.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14324/HighFidelity-Beta-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14324/HighFidelity-Beta-Interface-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14324/HighFidelity-Beta-PR14204-3e49d55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14324/HighFidelity-Beta-Interface-PR14204-3e49d55.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14450/HighFidelity-Beta-PR14204-3e49d55.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14450/HighFidelity-Beta-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14450/HighFidelity-Beta-Interface-PR14204-3e49d55.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14450/HighFidelity-Beta-PR14204-3e49d55.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14450/HighFidelity-Beta-Interface-PR14204-3e49d55.exe

**Comment by qlimguicheteau** [comment]
Currently Testing

**Comment by qlimguicheteau** [comment]
Experiencing a few crashes with this build, currently investigating.

**Comment by qlimguicheteau** [comment]
Pausing for BVT

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14472/HighFidelity-Beta-PR14204-791ee04.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14472/HighFidelity-Beta-PR14204-791ee04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14472/HighFidelity-Beta-Interface-PR14204-791ee04.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14472/HighFidelity-Beta-PR14204-791ee04.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14472/HighFidelity-Beta-Interface-PR14204-791ee04.exe

**Comment by qlimguicheteau** [comment]
Resuming

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

Pass - Cubes can all be selected and manipulated in Create menu via the far-grab Laser.
Pass - Grabbable properly affects both settings of cube. Far-grab works.
Pass - No properties change on the cubes when being far-grabbed.
Pass - HMD and Desktop mouse react as expected.

**Pull request merged**
