### PR TITLE
don't build oculus-legacy plugin on Linux

### PR DESCRIPTION
**Pull request by sethalves**
- don't build oculus-legacy plugin on Linux

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make sure Windows + oculus still works.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d036e0618d88e1338de8af3e5b0d5a147ba02906 available at: https://gist.github.com/943eb390d12929c366a8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7337.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7337.dmg

**Comment by ZappoMan** [comment]
The OSX support for oculus has been dubious for a while, and we're officially not claiming that mac support is beta ready at MVP... so I'm gonna say we only have to verify that windows is still good.

**Comment by ZappoMan** [comment]
The interface build runs fine... but for some inexplicable reason, the console with this build will not allow servers to start. The console runs, but it doesn't auto-start servers, and when you choose "start server" they don't run.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 29fd3e4ea62ffa8cdeacd212e8f9323da6751cf5 available at: https://gist.github.com/943eb390d12929c366a8<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7337.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7337.dmg

**Comment by sethalves** [comment]
the trouble with the console was from a different PR.  I've pulled from master, and hopefully that problem is no longer in this PR.

**Comment by ZappoMan** [comment]
tested on windows... oculus still works.

**Pull request merged**
