### PR TITLE
Fix for avatar recording playback on avatars with many joints

### PR DESCRIPTION
**Pull request by hyperlogic**
Before this fix, playback of avatar recording frames could overflow the maximum UDP packet size (MTU).
This is playback of a recording was causing all the rotations and translations to be transmitted,
even if the translations were not any different then the avatar default pose.

This explicitly records the rotationIsDefaultPose and translationIsDefaultPose in the recording stream.
This does not break backwards compatibility.
However, it does require new recordings for avatars with large numbers of bones.

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/14041/Bug-Avatar-Recording-Playback-Issues-for-some-Avatars

**Comment by hyperlogic** [comment]
QA Test plan:
* Follow the directions in this [page](https://docs.highfidelity.com/create-and-explore/marketplace-apps/record-app) for how to set up the avatar recording and playback app.
* Once that is set up make a recording of the following avatars:
    * http://mpassets.highfidelity.com/4682daff-c36c-4395-9d9c-b5b554521d3c-v1/AthauxanAvatars/Cat_Mechsuit/CatBlack_MechSuit.fst
    * https://hifi-content.s3.amazonaws.com/jimi/avatar/Niconico/Jene_5.fst
    * https://hifi-content.s3.amazonaws.com/jimi/avatar/Mannequin/hairTest/mannequinHairTest6.fst

Expected Result:
Playback of recordings should look exactly like the original avatar.  The joints should all be the correct length and positioned at the expected location.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8747/app_12877_PR_568af7a0721f3febdff5bd82561c28e2e650b073.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8747/HighFidelity-Beta-PR12877-568af7a0721f3febdff5bd82561c28e2e650b073.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8747/HighFidelity-Beta-Interface-PR12877-568af7a0721f3febdff5bd82561c28e2e650b073.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8747/HighFidelity-Beta-PR12877-568af7a0721f3febdff5bd82561c28e2e650b073.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8747/HighFidelity-Beta-Interface-PR12877-568af7a0721f3febdff5bd82561c28e2e650b073.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8763/HighFidelity-Beta-PR12877-da319b9af62f51a815ce8319491528366d30e688.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8763/HighFidelity-Beta-Interface-PR12877-da319b9af62f51a815ce8319491528366d30e688.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8763/HighFidelity-Beta-PR12877-da319b9af62f51a815ce8319491528366d30e688.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8763/HighFidelity-Beta-Interface-PR12877-da319b9af62f51a815ce8319491528366d30e688.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar recording look and playback as expected.

**Pull request merged**
