### PR TITLE
Add wait when terminating script threads

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21945/HighFidelity-Beta-PR16354-36f429c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21945/HighFidelity-Quest-Beta-PR16354-36f429c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21945/HighFidelity-Beta-PR16354-36f429c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21945/HighFidelity-Beta-Interface-PR16354-36f429c.dmg

**Comment by huffman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21955/HighFidelity-Beta-PR16354-36f429c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21955/HighFidelity-Beta-Interface-PR16354-36f429c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21955/HighFidelity-Beta-PR16354-36f429c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21955/HighFidelity-Quest-Beta-PR16354-36f429c.apk)

**Comment by huffman** [comment]
@jherico That was one concern I had, at least that the termination time doesn't have an upper bound that I know about.

So `QThread::terminate` may not be successful in all scenarios? My understanding is that it _would_ terminate, it just may not have terminated by the time the function call has returned.

After a discussion in bug triage, the decision was to not process events on shutdown on Mac. We only do it there, and it's a large source of these bugs.

**Pull request closed without merging**
