### PR TITLE
Tablet Prototype - No hover

### PR DESCRIPTION
**Pull request by SamGondelman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5376/HighFidelity-Beta-PR11923-d21a53847882a3d8bbd15c539c7a80e39fec2e57.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5385/HighFidelity-Beta-PR11923-d21a53847882a3d8bbd15c539c7a80e39fec2e57.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5385/HighFidelity-Beta-PR11923-d21a53847882a3d8bbd15c539c7a80e39fec2e57.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5399/HighFidelity-Beta-PR11923-5998a932ba84c6b589b8d1dd13bda0058994e35e.dmg

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5400/HighFidelity-Beta-PR11923-5998a932ba84c6b589b8d1dd13bda0058994e35e.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5404/HighFidelity-Beta-PR11923-5998a932ba84c6b589b8d1dd13bda0058994e35e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5404/HighFidelity-Beta-PR11923-5998a932ba84c6b589b8d1dd13bda0058994e35e.dmg

**Pull request closed without merging**
