### PR TITLE
Do not open help on first run

### PR DESCRIPTION
**Pull request by misslivirose**
Keeping the showHelp() function in as it is called elsewhere, but removing the call on first run as we have the serverless tutorial in place now.

https://highfidelity.manuscript.com/f/cases/14646/Help-menu-should-not-be-shown-to-users-when-they-land-in-the-serverless-tutorial

### CODE REVIEW

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9413/app_13055_PR_b994776ebd98314025ecdc86fdffc91ebb42eba1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9413/HighFidelity-Beta-PR13055-b994776ebd98314025ecdc86fdffc91ebb42eba1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9413/HighFidelity-Beta-Interface-PR13055-b994776ebd98314025ecdc86fdffc91ebb42eba1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9413/HighFidelity-Beta-PR13055-b994776ebd98314025ecdc86fdffc91ebb42eba1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9413/HighFidelity-Beta-Interface-PR13055-b994776ebd98314025ecdc86fdffc91ebb42eba1.exe

**Comment by misslivirose** [comment]
Mini merge conflict in Application.cpp, fixed now

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9520/app_13055_PR_ee0af079cf8fabad4bcd3d1f9748851bce0246f9.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9520/HighFidelity-Beta-PR13055-ee0af079cf8fabad4bcd3d1f9748851bce0246f9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9520/HighFidelity-Beta-Interface-PR13055-ee0af079cf8fabad4bcd3d1f9748851bce0246f9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9520/HighFidelity-Beta-PR13055-ee0af079cf8fabad4bcd3d1f9748851bce0246f9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9520/HighFidelity-Beta-Interface-PR13055-ee0af079cf8fabad4bcd3d1f9748851bce0246f9.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Help menu does not appear in serverless

**Pull request merged**
