### PR TITLE
Add resizable flag. Use the flag for Create only

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/7639/Make-the-Desktop-Create-Dialog-Resizable

Test plan:
- Switch to Toolbar mode
- open Create window. 
- Make sure Create window resizable
- Switch to another windows
- Make sure the windows not resizable and set to default size
- Switch back to Create window
- Make sure Create window resized to its size, set last time

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3366/HighFidelity-Beta-PR11377-de4f34aacb37d7857586fb06fbc7cbd06fc1ae98.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3366/HighFidelity-Beta-PR11377-de4f34aacb37d7857586fb06fbc7cbd06fc1ae98.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Switch to Toolbar mode **Check**
open Create window. **Check**
Make sure Create window resizable **Check**
Switch to another windows **Check**
Make sure the windows not resizable and set to default size **Check**
Switch back to Create window **Check**
Make sure Create window resized to its size, set last time **Check**

Notes: Tried to see if I could create any issues by going back and fourth through menus and opening/closing them in different ways, not once did the Create size change to something not specifically set. All good!

**Pass**

**Pull request merged**
