### PR TITLE
7469 Mouse Pointer Depth is Incorrect in HMD Mode

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. In HMD, open the tablet
2. Move your mouse so that it is over the tablet
3. The depth of the mouse should be drawn correctly so that the mouse appears on top of the tablet

Note: this fix is not about fixing tablet only, in general it should fix mouse depth for other interactive objects (if such exists).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3212/HighFidelity-Beta-PR11339-8366e5d8f3fbdd473655ec7544afe51b5acc84ce.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3212/HighFidelity-Beta-PR11339-8366e5d8f3fbdd473655ec7544afe51b5acc84ce.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3214/HighFidelity-Beta-PR11339-deee6aab1a9ecf1d70439fa630038dc7240d8f5e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3214/HighFidelity-Beta-PR11339-deee6aab1a9ecf1d70439fa630038dc7240d8f5e.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

In HMD, open the tablet **Check**
Move your mouse so that it is over the tablet **Check**
The depth of the mouse should be drawn correctly so that the mouse appears on top of the tablet **Check**

**Note: did experience one thing which I am unsure would Fail this, but moving head back or forward without touching the mouse after it's on the tablet appears to move the mouses depth depending on head back/fourth movement. Though corrects when mouse is moved again. Please let me know if this is intentional or a fault.**

**Pass**

**Comment by ElderOrb** [comment]
hmm... well... such a behavior is definitely not a result of my changes. I'm afraid such a use-case was never implemented (or another regression which needs to be fixed). It probably deserves separate issue. 

@anshuman64 what are you thoughts on this?

**Comment by anshuman64** [comment]
I'd say this is enough of an improvement to call it a QA Pass

**Pull request merged**
