### PR TITLE
Shapes now render at the correct size.

### PR DESCRIPTION
**Pull request by hyperlogic**
Shape Entities now render at the correct size.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA Test plan:
  * Enter create mode.
  * Create a sphere entity.
  * Change the dimensions of the sphere.
  * Ensure the sphere size matches the desired dimensions.
  * Change the shape type to Cube, Hexagon etc.
  * Ensure that all shape types are rendered with the correct dimensions.

**Comment by YuppyPlays** [comment]
Awaiting build.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3403/HighFidelity-Beta-PR11396-73ad9051a42ba93f5d7f1d62ce3fae2e9144ec2f.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by anshuman64** [comment]
build this please

**Comment by hyperlogic** [comment]
I think there still might be an issue here, I'm looking at the log cabin in dev-welcome, it's not completely rendering correctly, but I'm not sure if that's because it's rendering incorrectly, or some of the elements are missing.

**Comment by hyperlogic** [comment]
Nevermind, I think someone recently restored the domain, It looks correct now.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3413/HighFidelity-Beta-PR11396-73ad9051a42ba93f5d7f1d62ce3fae2e9144ec2f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3413/HighFidelity-Beta-PR11396-73ad9051a42ba93f5d7f1d62ce3fae2e9144ec2f.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Enter create mode. **Check**
Create a sphere entity. **Check**
Change the dimensions of the sphere. **Check**
Ensure the sphere size matches the desired dimensions. **Check**
Change the shape type to Cube, Hexagon etc. **Check**
Ensure that all shape types are rendered with the correct dimensions. **Check**

All appears to be working like it should. **Pass**

**Pull request merged**
