### PR TITLE
Continue Touchpad test work started on PR16433

### PR DESCRIPTION
**Pull request by luiscuenca**
This PR continues the work started on https://github.com/highfidelity/hifi/pull/16433
In addition to the changes made on that PR, this PR fixes a bug that times out the touch event on mac when orbiting the camera using the touch pad and it adds code that interpret wheel events coming from the touch pad in order to use those values to orbit the camera.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22588/HighFidelity-Beta-PR16503-e55d4cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22588/HighFidelity-Quest-Beta-PR16503-e55d4cd.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22588/HighFidelity-Beta-PR16503-e55d4cd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22588/HighFidelity-Beta-Interface-PR16503-e55d4cd.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22591/HighFidelity-Beta-PR16503-f1c82e7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22591/HighFidelity-Beta-Interface-PR16503-f1c82e7.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22591/HighFidelity-Beta-PR16503-f1c82e7.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22591/HighFidelity-Quest-Beta-PR16503-f1c82e7.apk)

**Comment by luiscuenca** [comment]
I've created a clean PR here:
https://github.com/highfidelity/hifi/pull/16505

**Pull request closed without merging**
