### PR TITLE
CR for Job #20280 - Warn if Interface and Stack have incompatible build level

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Code Review for Job #20280 - Workitem available at https://www.worklist.net/20280

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c7cdc16ce3adc189caa890a750aa0ffd697d20b available at: https://gist.github.com/e0d0f6837e073f5d7cfc

**Comment by ctrlaltdavid** [comment]
I can't work out what the OSX build problem might be; build log isn't very informative on the matter. Windows and Linux built OK, and @cozza13 built the 20280 branch on OSX OK.

**Comment by cozza13** [comment]
I built this on my OSX machine and it worked fine. @murillodigital may know why?

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
retesting for sanity - if it flunks again ill dig

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c7cdc16ce3adc189caa890a750aa0ffd697d20b available at: https://gist.github.com/c9f700fb37971f10cc85

**Comment by murillodigital** [comment]
Ok so yeah fail is real ill look into it later today when back at keyboard

**Comment by murillodigital** [comment]
Yeah this fail is my doing - caused by some changes Im working on the mac slave to have multiple versions of Qt easily pickable in preparation for the soon to 5.4 switch. Working on it.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c7cdc16ce3adc189caa890a750aa0ffd697d20b available at: https://gist.github.com/b197a5823db0b3b9694b

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3c7cdc16ce3adc189caa890a750aa0ffd697d20b available at: https://gist.github.com/7796e788c1b1714703c5

**Comment by ZappoMan** [comment]
@ctrlaltdavid - can you merge with upstream? thanks.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9e353e498349e378ae6d4bb2bc3f4a5045ca38a available at: https://gist.github.com/047b3d6a355b02ac533f<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4210.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4210.dmg

**Pull request merged**
