### PR TITLE
Fix missed revert of PR 12969 for RC67

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9266/app_13029_PR_acb21cc96a459721bf51638bba15855e36892cd2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9266/HighFidelity-Beta-PR13029-acb21cc96a459721bf51638bba15855e36892cd2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9266/HighFidelity-Beta-Interface-PR13029-acb21cc96a459721bf51638bba15855e36892cd2.exe

**Comment by conklin94122** [comment]
No testing needed per Sam.

**Pull request merged**
