### PR TITLE
Prevent the Bubble icon from ever blinking as per 14026

### PR DESCRIPTION
**Pull request by zfox23**
PR #12653 was one step towards this, but Design wants the bubble to never blink, so it shan't!

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Testing this PR requires the use of two clients controlling one avatar each (Avatar A and Avatar B).

### Tests
Perform the tests below in Desktop mode.

1. Have Avatar A turn their bubble on.
    i. Verify that the BUBBLE icon in the HUD does not blink, but rather immediately turns to the ACTIVE state (white).
2. Have Avatar B turn their bubble off. Have Avatar B walk into Avatar A's bubble.
    i. Have Client A verify that the BUBBLE icon in the HUD does not blink, but rather stays in the ACTIVE state (white).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8594/app_12822_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8594/HighFidelity-Beta-PR12822-0e258e82aa5a4d17eb5dde1c274a4af01505affc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8594/HighFidelity-Beta-PR12822-0e258e82aa5a4d17eb5dde1c274a4af01505affc.exe

**Comment by howard-stearns** [comment]
closed in favor of https://github.com/highfidelity/hifi/pull/12862

**Pull request closed without merging**
