### PR TITLE
Polyvox improvements (Warning: protocol change)

### PR DESCRIPTION
**Pull request by sethalves**
Fix bug in polyvox setAll that caused an assert.  Add a texture-url property for each axis.  Connect the 3 textures to the renderer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b88500735c582852c3ee3230ea5b7df05edd73e available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b318c1122c5875658735a766c7f43bf79a2237a8 available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: efe61a1520555e84adee2dd676a5604dffcd4e07 available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c07119c30bd92792dc3481d1ea7b39c2c60a205e available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f9685efa4b083a124fd96503de14381b04a6e1a5 available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a5ed0eb9b7ed1ebf24ab44f80e492caddb9fb4b available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 732f9ceca58989fab9087441c322ad48b848105a available at: https://gist.github.com/640fc679749e87060f37<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5467.dmg

**Comment by AndrewMeadows** [comment]
I tested: was able to load a legacy SVO file with a polyvox and a few entities into the new system -- it worked.  Editing the textures on the polyvox was a little wonky -- sometimes I'd have to logout and back in to see the change.  Dunno if it is a problem with edit.js or the C++.

**Pull request merged**
