### PR TITLE
RC75: Fix ResourceCache mutex issues

### PR DESCRIPTION
**Pull request by SamGondelman**
https://github.com/highfidelity/hifi/pull/14354

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14776/HighFidelity-Beta-PR14355-54ccea7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14776/HighFidelity-Beta-PR14355-54ccea7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14776/HighFidelity-Beta-Interface-PR14355-54ccea7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14776/HighFidelity-Beta-PR14355-54ccea7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14776/HighFidelity-Beta-Interface-PR14355-54ccea7.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14788/HighFidelity-Beta-PR14355-fc5ab32.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14788/HighFidelity-Beta-PR14355-fc5ab32.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14788/HighFidelity-Beta-Interface-PR14355-fc5ab32.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14788/HighFidelity-Beta-PR14355-fc5ab32.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14788/HighFidelity-Beta-Interface-PR14355-fc5ab32.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Loaded server-less domain and took off and put on VR headset 40 times with no crashes. Went to hifiqa-master-metaverse-staging which is using the AvatarIsland content set and put on and removed headset 20 times with no crash. Launched and quit the interface 5 times with no hanging shutdowns. PR Passes.

**Pull request merged**
