### PR TITLE
78.1: Fix errors and intermittent failures in Android gradle builds in containers

### PR DESCRIPTION
**Pull request by jherico**
RC78 version of #14793

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16878/HighFidelity-Beta-PR14800-2771212.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16878/HighFidelity-Beta-Interface-PR14800-2771212.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16878/HighFidelity-Beta-PR14800-2771212.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16878/HighFidelity-Beta-Interface-PR14800-2771212.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16892/HighFidelity-Beta-PR14800-2771212.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16892/HighFidelity-Beta-PR14800-2771212.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16892/HighFidelity-Beta-Interface-PR14800-2771212.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16892/HighFidelity-Beta-PR14800-2771212.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16892/HighFidelity-Beta-Interface-PR14800-2771212.exe

**Pull request merged**
