### PR TITLE
Fixing logging errors on initial load of controller routes

### PR DESCRIPTION
**Pull request by jherico**
The errors are caused because the route endpoints in the standard control routes don't exist when the routes are parsed.  This PR adds a mechanism to define the state route endpoint names before the routes are parsed, even if you can't define the lambdas that return proper values yet.

### CODE REVIEW

**Comment by jherico** [comment]
https://app.asana.com/0/27650181942747/108661828643063

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ac26d7094216477bbda2c7737ebeb2fd8bd2289 available at: https://gist.github.com/c07b18051eee61fd628cac562fc51e7d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9315c8757cf8aac9657866ea75948725d6fb1d4a available at: https://gist.github.com/c07b18051eee61fd628cac562fc51e7d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3a55fe1efee40279329f99c14bd256ceb03c5a4 available at: https://gist.github.com/c07b18051eee61fd628cac562fc51e7d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7605.dmg

**Comment by ZappoMan** [comment]
Test plan?

**Comment by OmegaHeron** [comment]
Was just about to ask that myself... At the moment I'm doing a comparison of "route spam" between this and current code via log review.

**Comment by ZappoMan** [comment]
@OmegaHeron - for sure we need a smoke test, one that focuses on input controllers, make sure mouse, keyboard, and hydra, still work.

**Comment by OmegaHeron** [comment]
Mouse - keyboard ok.  No HMD or hydra here.

My XBox controller works in production 4635  - it does not work properly in this PR.  This PR the thumb sticks do not control movement, production left thumb controls move - right thumb lets you jump if pushed up - rotate left right.  So this def breaks something at least with that.

**Comment by ZappoMan** [comment]
@jherico - see notes above - xbox controller is broken with this build

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4c78c0b3301871d58053f5a0f4670d542fd1b70f available at: https://gist.github.com/c07b18051eee61fd628cac562fc51e7d<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7605.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7605.dmg

**Comment by cozza13** [comment]
tested on xbox controller and it works.

**Comment by OmegaHeron** [comment]
XBox controller works again here as well - no spam about routes seen.

**Comment by ZappoMan** [comment]
Did this PR get tested with Hydras? With Vive?

Did we test HMD menus? Did we test all the possible routes that use these "state" items... namely snapturn vs non-snapturn for all the various turning modes?

**Pull request merged**
