### PR TITLE
updated connection instructions

### PR DESCRIPTION
**Pull request by davidkelly**
Red text to indicate you need to login, if you are not logged in.

### CODE REVIEW

**Comment by davidkelly** [comment]
Test Plan:
forget all your connections
log out
open PAL, go to connections tab
you should see the red text indicating you need to login to make connections
instructions should be appropriate for this mode (HMD or desktop)
now dismiss PAL
login
open PAL
go to connections tab
you should not see the red text this time
instructions should be appropriate for this mode (HMD or desktop)

Now repeat this test, but in HMD if you were in desktop, or in desktop if you were in HMD.  Same thing should happen, except you see the appropriate instructions for your new mode (HMD vs desktop).

**Comment by davidkelly** [comment]
Addresses [this](https://highfidelity.fogbugz.com/f/cases/3995/On-the-Connection-Menu-when-the-user-has-no-connections-note-that-you-must-be-logged-in) bug

**Comment by hifi-gustavo** [comment]
Build console output for commit: 179a445f597e25feec658b35eb1f2d132c41223c available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-179a445.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-179a445.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-179a445.exe

<!DOCTYPE html>
<html>
<body>

<h5>Desktop Mode</h5>



</body>
</html>

-  **PASS**: forget all your connections
log out
open PAL, go to connections tab
you should see the red text indicating you need to login to make connections
-  **PASS**: instructions should be appropriate for this mode (HMD or desktop)
-  **PASS**: now dismiss PAL
login
open PAL
go to connections tab
you should not see the red text this time
-  **PASS**: instructions should be appropriate for this mode (HMD or desktop)

<!DOCTYPE html>
<html>
<body>

<h5>HMD Mode</h5>



</body>
</html>

- **FAIL**: forget all your connections
log out
open PAL, go to connections tab
you should see the red text indicating you need to login to make connections

note: Connections would not load. "This is taking longer than normal. if you get stuck, try refreshing the Connections tab."
apr10154

- **FAIL**: instructions should be appropriate for this mode (HMD or desktop)
note: Connections dialog does not load, so unable to confirm if instructions are correct.
- **FAIL**: now dismiss PAL
login
open PAL
go to connections tab
you should not see the red text this time
note: Once again, Connections would not load. "This is taking longer than normal. if you get stuck, try refreshing the Connections tab."
- **FAIL**: instructions should be appropriate for this mode (HMD or desktop)
note: Connections dialog does not load, so unable to confirm if instructions are correct.

**Comment by howard-stearns** [comment]
Do we know if this had https://github.com/highfidelity/hifi/pull/10152 merged in?
If not, we should update and retest.
If it did, then we have a P1 problem. Please work with @claudioshg to repro.

**Comment by davidkelly** [comment]
No -- 10152 not merged :(

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb092d67dd80a37ae0f6b265cf35a846da66f51a available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-cb092d6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-cb092d6.dmg

**Comment by howard-stearns** [comment]
Does appear to be broken in HMD. I don't know why.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 948a821824b1ee0e7c7aefdb52dedf592dcc88b8 available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-948a821.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-948a821.dmg

**Comment by howard-stearns** [comment]
I still get the permanent spinning in connections tab, only in HMD

**Comment by howard-stearns** [comment]
The failure is from a different PR (see https://highfidelity.fogbugz.com/f/cases/4056/qml-sendToScript-doesn-t-work-in-tablet). I will test with a local build that has a local fix for #4056.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3ea6cac45aac79ee125ead7dc5702c11eb02634e available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-3ea6cac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-3ea6cac.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46b6903b93cf8b6c998b01dae85301f369d5c6eb available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-46b6903.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-46b6903.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 082d0964d26859c77140205527557ff9c7cf3835 available at: https://gist.github.com/97f797d6eef4079904adacaa22085265<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-082d096.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10154-082d096.dmg

**Pull request merged**
