### PR TITLE
fix edit.js to handle userData that's not in JSON

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
Test plan:

With old edit.js:
- Create entity
- Set script URL to something (ex: "http://invalid-url")
- Set userData to `true`
- Click on a different entity
- Click back on the one you created
- Notice userData and script URL are empty
- Set userData to `{}`
- Click on a different entity
- Click back on the one you created
- Notice script URL is back and userData is correctly set to `{}`

With new edit.js:
- Create entity
- Set script URL to something (ex: "http://invalid-url")
- Set userData to `true`
- Click on a different entity
- Click back on the one you created
- Notice userData and script URL are correctly set

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1abd8ef6c65f4c681d01e911f1bd63674d883b85 available at: https://gist.github.com/8860793cc3302d929181db6a1e5718ae<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1abd8ef6c65f4c681d01e911f1bd63674d883b85 available at: https://gist.github.com/8860793cc3302d929181db6a1e5718ae<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1abd8ef6c65f4c681d01e911f1bd63674d883b85 available at: https://gist.github.com/8860793cc3302d929181db6a1e5718ae<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0353e562e4589e83322fd36a3e0f9c6c2f4e27a1 available at: https://gist.github.com/8860793cc3302d929181db6a1e5718ae<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7944.dmg

**Comment by thoys** [comment]
## Test report

- Tried to reproduce the bug as describe and it is quite annoying to have the properties disappear :+1: 
- I've applied your changes and notice that I was able to read the previous bugged entity properties now. Also I have created another entity with these properties as you described and it all works fine  :white_check_mark: 

QA test passed successfully !

**Pull request merged**
