### PR TITLE
Add explicit layout to textured particle shader

### PR DESCRIPTION
**Pull request by zzmp**
Fixes particle systems on the AMD.

### CODE REVIEW

**Comment by zzmp** [comment]
See https://app.asana.com/0/74051501495175/106417477357536.

#### Testing

Testing on nVidia: Make sure particle systems work as they did.
Testing on AMD: Particles systems will render unpredictably on current build. In forum, the fire smoke usually renders as black boxes. This should be fixed in this PR to actually look like smoke.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4e3ab7394135741c6889e3e89ca973d44ade0cbe available at: https://gist.github.com/ec70927cd56f7fb31e5242d9e2a4cb7b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7615.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7615.dmg

**Comment by imgntn** [comment]
particles looking good on my amd r9 390 at home
capture

**Comment by cozza13** [comment]
I will test on Nvidia

**Pull request merged**
