### PR TITLE
BUGZ-628 - Add quasi-MTBF logging to track disconnects

### PR DESCRIPTION
**Pull request by roxanneskelly**
Track last connect and disconnect time on the client and report the delta (last login uptime) to the server, along with the reason (connect/silent domain reconnect) to the domain server, which will log the data.

https://highfidelity.atlassian.net/browse/BUGZ-628?filter=-1

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19928/HighFidelity-Beta-PR15746-8704a36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19928/HighFidelity-Beta-Interface-PR15746-8704a36.dmg

**Comment by roxanneskelly** [comment]
build me please

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19930/HighFidelity-Beta-PR15746-8704a36.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19930/HighFidelity-Quest-Beta-PR15746-8704a36.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19930/HighFidelity-Beta-PR15746-8704a36.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19930/HighFidelity-Beta-Interface-PR15746-8704a36.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19930/HighFidelity-Beta-PR15746-8704a36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19930/HighFidelity-Beta-Interface-PR15746-8704a36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19940/HighFidelity-Beta-PR15746-ca0c9e2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19940/HighFidelity-Beta-Interface-PR15746-ca0c9e2.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19940/HighFidelity-Beta-PR15746-ca0c9e2.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19940/HighFidelity-Quest-Beta-PR15746-ca0c9e2.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19940/HighFidelity-Beta-PR15746-ca0c9e2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19940/HighFidelity-Beta-Interface-PR15746-ca0c9e2.exe

**Comment by qlipdahlin** [comment]
Pre-merge test passed.

**Pull request merged**
