### PR TITLE
remove an unused qxmpp external

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: de9e03a3794ac7a6567e498b23930440756500e3 available at: https://gist.github.com/eebfc5af538080f7f7b9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6695.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6695.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: de9e03a3794ac7a6567e498b23930440756500e3 available at: https://gist.github.com/eebfc5af538080f7f7b9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6695.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6695.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: de9e03a3794ac7a6567e498b23930440756500e3 available at: https://gist.github.com/eebfc5af538080f7f7b9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6695.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6695.dmg

**Pull request merged**
