### PR TITLE
fix logic that resets own-avatar collisions after a parenting grab is released

### PR DESCRIPTION
**Pull request by sethalves**
see https://github.com/highfidelity/hifi/pull/12015

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5720/app_12018_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5720/HighFidelity-Beta-PR12018-63ac426bf27c9782c0406224275862790aed1c3f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5720/HighFidelity-Beta-PR12018-63ac426bf27c9782c0406224275862790aed1c3f.dmg

**Comment by conklin94122** [comment]
QL ran all tests from https://github.com/highfidelity/hifi/pull/12015, all tests passed.

**Pull request merged**
