### PR TITLE
V0.70.0 rc Change default search radius in entity list.

### PR DESCRIPTION
**Pull request by Nex-Pro**
Reducing the default search radius from 100m to 10m  makes population and use of the entity list more likely in domains with large numbers of entities. ( e.g. Maker ) Currently the entity list can take a very long time or fail to populate at all.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
Ignore this.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11385/HighFidelity-Beta-PR13626-7a950b5.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11385/HighFidelity-Beta-PR13626-7a950b5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11385/HighFidelity-Beta-Interface-PR13626-7a950b5.exe

**Pull request closed without merging**
