### PR TITLE
BUGZ-1363: crash when checking for web content restrictions

### PR DESCRIPTION
**Pull request by jherico**
[BUGZ-1363](https://highfidelity.atlassian.net/browse/BUGZ-1363)

The existing codebase needs to ensure that server scripts can't access local files via web content.  The existing mechanism assumes that the check that we do in `ContextAwareProfile::isRestricted`, executed as part of a `QWebEngineUrlRequestInterceptor` callback,  will be done on the main thread, but this appears to be incorrect.  Instead it's happening on another thread, which is handling the network request.  This makes the existing useage of `QQmlContext::contextProperty` unsafe, because it can manipulate internal data structures and is not thread safe.  

The solution is to use a mechanism to ensure that the contextProperty call is left to the main thread.  However, because we don't want every last network request to block the main thread, I've added caching of the value of up to 1 second, so that in theory most requests should hit the cached value instead.  

Note this does not fix [BUGZ-1365](https://highfidelity.atlassian.net/browse/BUGZ-1365), a related bug which points out that we don't have the protection against local file access in our InteractiveWindow class.

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21092/HighFidelity-Beta-PR16113-5a6e2e5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21092/HighFidelity-Beta-Interface-PR16113-5a6e2e5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21092/HighFidelity-Beta-PR16113-5a6e2e5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21092/HighFidelity-Beta-Interface-PR16113-5a6e2e5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21097/HighFidelity-Beta-PR16113-af22ab5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21097/HighFidelity-Beta-Interface-PR16113-af22ab5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21097/HighFidelity-Beta-PR16113-af22ab5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21097/HighFidelity-Beta-Interface-PR16113-af22ab5.dmg

**Comment by AndrewMeadows** [comment]
There is still some Android fencing to be done.  The latest crash is for:
```16:09:24   /home/jenkins/hifi/libraries/ui/src/ui/types/ContextAwareProfile.cpp:24:5: error: member initializer 'QQuickWebEngineProfile' does not name a non-static data member or base class
16:09:24       QQuickWebEngineProfile(context), _context(context) { 
16:09:24       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21101/HighFidelity-Beta-PR16113-36be00b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21101/HighFidelity-Beta-Interface-PR16113-36be00b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21101/HighFidelity-Beta-PR16113-36be00b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21101/HighFidelity-Quest-Beta-PR16113-36be00b.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21101/HighFidelity-Beta-PR16113-36be00b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21101/HighFidelity-Beta-Interface-PR16113-36be00b.exe

**Pull request merged**
