### PR TITLE
Case 21341: Fix billboard mode in secondary camera

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21341/Billboard-test-failing

Test plan:
- run the content/entity/text/billboardMode test from hifi_tests

### CODE REVIEW

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17485/HighFidelity-Beta-PR14972-4fdf556.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17485/HighFidelity-Beta-PR14972-4fdf556.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17485/HighFidelity-Beta-Interface-PR14972-4fdf556.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17485/HighFidelity-Beta-PR14972-4fdf556.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17485/HighFidelity-Beta-Interface-PR14972-4fdf556.exe

**Pull request merged**
