### PR TITLE
Fix UBSan warnings due to SIMD intrinsics

### PR DESCRIPTION
**Pull request by kencooke**
Fix benign warnings and code cleanup. The compiler output is unchanged.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20018/HighFidelity-Beta-PR15788-ce7571d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20018/HighFidelity-Beta-Interface-PR15788-ce7571d.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20018/HighFidelity-Beta-PR15788-ce7571d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20018/HighFidelity-Quest-Beta-PR15788-ce7571d.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20020/HighFidelity-Beta-PR15788-ce7571d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20020/HighFidelity-Quest-Beta-PR15788-ce7571d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20020/HighFidelity-Beta-PR15788-ce7571d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20020/HighFidelity-Beta-Interface-PR15788-ce7571d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20020/HighFidelity-Beta-PR15788-ce7571d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20020/HighFidelity-Beta-Interface-PR15788-ce7571d.exe

**Pull request merged**
