### PR TITLE
Beta Release 13 - Includes up to Developer Release 5026

### PR DESCRIPTION
**Pull request by cozza13**
- Add audio peak limiter to audio mixer
- Fix the jittering reflection bug and more Normal improvements
- vhacd-util improvements
- Fix domain max capacity to only count users (not scripted agents)
- Make navigating directories in file browser dialog possible without double-clicking
- Fix Avatar collision sounds triggering all the time
- Make the application of redundant physics update idempotent to improve action glitches
- Fix crash on shutdown of SteamVR
- Fix crash on click on non-visible web-entity 
- Update the build docs for a better OpenSSL security posture.
- Do not send stale vive data as valid after deactivating
- Save toolbar position when moving it only when stopped moving it
- Add leap hands to /system
- Replace the linear interpolation embedded in the .WAV/.RAW loader with high quality polyphase resampling.
- Fix bad convex hull simplification
- Revert "Update the build docs for a better OpenSSL security posture."
- Eliminate file IO contentions for settings
- Removed innocuous "AvatarData packet size mismatch" warning
- Add version number to avatar recording frame
- Add Clipboard.getContentsDimensions() JavaScript method
- Eliminate extraneous writes for unchanged values
- Add Entities.getChildrenIDs() method
- Camera steers avatar when walking
- Fixed constant turn of 22.5 degrees in comfort mode
- Add "Load Defaults" button to Running Scripts dialog and rename "Stop All" to "Remove All"
- Select/Disable plugins via command line args
- Fix OS X warning
- Fix colors of buttons in Asset Browser dialog
- AVX2 optimized audio resampler 
- New home content
- Corrected Oculus Touch coordinate system so that hands track properly
- Fix for models exported from Daz3D
- Expose haptics to JS
- Game pads work after falling asleep and being reactivated
- Add support for ambient occlusion texture and lightmap texture for fbx exported from Blender
- Fix height of Load Defaults button in Running Scripts dialog
- Added MyAvatar.hmdLeanRecenterEnabled property used to disable the 'room-scale' avatar re-centering code. Disabling this can prevent sliding when the avatar is supposed to be sitting or mounted on a stationary object. 
- Add basic metadata to domains
- Attempt to get better logging from pure virtual call crashes
- Use shared CPUDetect.h for CPU detection
- Re-instate domain API connection info refresh during failure, fix localhost connection after downgrade
- Rework domain-level permissions 
- Fix some permissions-grid bugs
- Fix import of invalid JSON file failing silently
- Fix model export
- Update BUILD_OSX.md
- Fix avatar entity locking
- Fix problem related to server-side extrapolation of children of avatars
- Fix image2d overlay color property
- Fix tabbing behavior in edit.js
- Exposed orientation and eye position to procedural entity shaders
- More verbose messaging about incorrect case in entity types
- Reset Vive grip buttons to 0 if not pressed
- Only signal once on a protocol mismatch with DS
- Fixing issues with unclosed groups in settings persistence

# **QA testing**  

http://rawgit.com/cozza13/QAtesting/master/dynamicrc.js

Full **Smoke test** - **HMD RC test** with **Eye tests** and **RC test**

This PR has a protocol change. Therefore you will only see content on you updated locahost, dev-playa and dev-demo. I have updated the server stats to pull from those locations

### CODE REVIEW

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 35254985507ea77c49eec235dafd2806d1f611c5 available at: https://gist.github.com/769a2b194dad93cf6d83d8e7b0f3c84d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8073.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8073.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**playa 'playaPerformanceTest.js' Result**: **playa 'playaPerformanceTest.js'** SUCCESS
**cellscience 'playaPerformanceTest.js' Result**: **cellscience 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Success however old issue of mouse fighting with hydra issue resurfaced.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |50
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |49
**CPU Buffer Count**: |218 |543 |773
**GPU Buffer Count**: |94 |176 |166
**CPU Memory Usage**: |6238208 |17625088 |19066880
**GPU Memory Usage**: |5246976 |12398592 |6504448
**CPU Texture Count**: |51 |85 |75
**GPU Texture Count**: |338 |376 |369
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |23543444 |49141396 |73746068
**GPU Texture Memory Usage**: |26650026 |158241249 |35068367
**GPU Virtual Memory Usage**: |156687786|288279009|165106127
**Triangle Count**: |55472 |299837 |118135
**Triangle Rate**: |3263058 |17637470 |6949117
**API Drawcall Count**: |23 |58 |55
**Drawcall Count**: |27 |60 |56
**Drawcall Rate**: |1588 |3529 |3294
**State Changes Texture Count**:|27 |60 |43
**Pipeline Count**: |20 |20 |21
**Item Opaques**: |69 |112 |66
**Item Translucents**: |3 |2 |25
**Item Lights**: |15 |21 |25
**Timing Opaques**: |363 |910 |606
**Timing Translucents**: |14 |12 |153
**Timing Lighting**: |122 |148 |183
**Render Frame**: |1515 |1861 |1897

**EYE-01 Test Result**: **EYE-01 Test** SUCCESS
**EYE-02 Test Result**: **EYE-02 Test** SUCCESS
**EYE-03 Test Result**: **EYE-03 Test** SUCCESS
**EYE-04 Test Result**: **EYE-04 Test** SUCCESS
**EYE-05 Test Result**: **EYE-05 Test** SUCCESS
**EYE-06 Test Result**: **EYE-06 Test** SUCCESS
**EYE-07 Test Result**: **EYE-07 Test** SUCCESS
**Additional Test Results + Observations**:Successful test.  To reiterate issue with mouse and hydra as hydra hijacks mouse again.

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
Successfully see content on updated locahost, dev-playa and dev-demo.

**Comment by OmegaHeron** [comment]
This may be a vestige from working with PR to correct saving settings... but

hf-login-dialog- while-loogedin

**Note the title bar - I am logged in** and I double confirmed this by moving to a domain only allowing OmegaHeron entry via ACL controls.  This **only** happens on localhost - if I move to Heron or my other domain, exit and return I don't see message.  If I then move from one of those to localhost I immediately get popup for login credentials.

Domain running on Linux version 5026 (connected to via remote inet) is fine - I don't see popup when visiting it
Domain running on Linux this PR version is fine (second machine on LAN)  - I don't see popup when visiting it
Domain running on Windows this PR localhost - Every time I enter it I get popup to login

**Comment by ZappoMan** [comment]
I saw the same thing omega is seeing. It's definitely a bug. I'm not sure I'd consider it a blocker. But we should get it filed if we have a solid repro case.

**Comment by OmegaHeron** [comment]
It's 100% for me - I have **not** tried actually entering credentials when it pops up - figured it might be best to dismiss that and preserve my ini/setup as is for debug.  What I can't determine is if it's a Windows thing + localhost only or Windows + any entry method as I don't have a second windows machine on LAN or Net to try.

**Comment by OmegaHeron** [comment]
Also - localhost shows a count of 1 avatar instead of expected 0.  It's still showing AV created by ACAudioSearchAndInject.js as an agent presence.  I thought that behavior was changed or was that just the count for max users and nothing to do with display count?  Just checking....

**Comment by OmegaHeron** [comment]
QA Fail.

Starting with **no interface.ini** I am sent to localhost (since it's present) and that's fine, no pop-up to login etc... attempted to move to Heron which requires logged in users - popup presented saying I can't get in and reason (correct) but it went into infinite loop of periodic popups.

Repro - delete initerface.ini (or simply log out) attempt to connect to hifi://heron

**Comment by OmegaHeron** [comment]
@birarda - Infinite popups for proto mismatch were solved by your PR (and still works in this merge), but, it seems deny for ACL reason popup is not covered by that - you continue to get ACL deny popups about every 3 seconds.

**Pull request closed without merging**
