### PR TITLE
Fix display name z-fighting

### PR DESCRIPTION
**Pull request by Atlante45**
Sometimes, the display names disappear behind their backgrounds, this fixes it.
Billboarding for text entities was not done correctly, this is now fixed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: c76bd477553c803563488551a60944920930d155 available at: https://gist.github.com/319aff7b7749def1cfe1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.dmg

**Comment by ZappoMan** [comment]
I tested this on Mac and windows and it doesn't appear to render the avatar display name any better...

Here are some screen shots...

screen shot 2015-07-02 at 4 26 33 pm

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85df510b4b75f05f4d5115c7d959c8a3894fc337 available at: https://gist.github.com/319aff7b7749def1cfe1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.dmg

**Comment by Atlante45** [comment]
Changed that PR to use proper depth bias in order to counter z-fighting on display names, text entities and text3d overlays. (That's the only 3 spots I could find where we used that z offset trick)
This is the result on my machine:
hifi-snap-by-atlante45-on-2015-07-04_18-45-31

I also made the display names backgrounds emissive so that they don't get all black when the camera is facing the main light.

**Comment by ZappoMan** [comment]
it still doesn't work on windows in 3rd person
windows-3rd-person

**Comment by ZappoMan** [comment]
Actually, it works on mac and windows if your location is "closer to the origin" things start to go sideways on windows when you're around the 10,000 range in position.

**Comment by ZappoMan** [comment]
largeposition

**Comment by ZappoMan** [comment]
btw - I did a little googling on DepthBias and it basically said the following... be wary using it because:

* it's implementation specific, different drivers can implement it differently
* it has problems with floating point errors when positions are large
* some other warnings about potential weirdness

So... I think what I'm seeing on windows is basically exactly what they say is problematic with depth bias. You might be able to solve this by simply making a different transform that doesn't cause the position to be so far out, maybe if you made a camera relative transform that was always within a couple 100 "world" units.

**Comment by Atlante45** [comment]
Yes, I didn't have access to a machine to test on windows. Just went to 1,000,000 x/y/z on mac though and it was fine.
hifi-snap-by-atlante45-on-2015-07-05_01-53-22
Where did you read those things about depth bias?
This it what Sam called it, but we actually use OpenGL's polygon offset which, as I understand is in clip space. So how far you are from the origin should not matter at all.
I could do a combination off both the depth bias and some Z-offset to cover all grounds.

@samcake thoughts?

**Comment by ZappoMan** [comment]
It did work for me on the mac... I got the correct behavior, but that's the point of it being different implementations on different OSes and video drivers.

**Comment by ZappoMan** [comment]
from: https://www.opengl.org/discussion_boards/showthread.php/172204-Slope-scale-depth-bias-in-OpenGL-3-2-core


>Be aware that polygon offset sucks because of a number of factors:
> * The spec allows it to be implementation-dependent (clicky) so the same values may give different results on different hardware.
> * You may encounter floating point precision problems when moving between 16-bit and 24-bit depth buffers.
> * The depth buffer is non-linear so the same values will give different results at different depths.
>If you can find values that work well for you, then great, but it's not a general solution and you shouldn't expect it to be one.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 687f9dda4a20c2d3041f1e8a6fbe6b08cc3c78c4 available at: https://gist.github.com/319aff7b7749def1cfe1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.dmg

**Comment by Atlante45** [comment]
Previous build was good on Windows all the way to the server boundaries but then was starting to z-fight again around 17000 x/y/z so I just double the offset applied which should give us a pretty good error margin.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ba6bd3afcb873d81488c5103d9fc48336f05580 available at: https://gist.github.com/319aff7b7749def1cfe1<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5256.dmg

**Comment by Atlante45** [comment]
@ZappoMan that last build looks good all the way up to 30,000 for me on the windows laptop, can you confirm?
Tested on mac too and it still looks good.

**Comment by ZappoMan** [comment]
I will test and merge later tonight.

**Pull request merged**
