### PR TITLE
Fix texture MB column not sorting correctly in entity list

### PR DESCRIPTION
**Pull request by huffman**
https://highfidelity.fogbugz.com/f/cases/19696/Create-app-Entity-List-TEXT-MB-column-does-not-sort-correctly

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16145/HighFidelity-Beta-PR14638-9c60b09.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16145/HighFidelity-Beta-PR14638-9c60b09.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16145/HighFidelity-Beta-Interface-PR14638-9c60b09.dmg

**Comment by QliCknox** [comment]
Pass

Texture/Texture size columns sort correctly
I wanna make note that the Name and file columns still sort incorrectly.

**Pull request merged**
