### PR TITLE
Update Nvidia texture tools to fix baking crash

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
The oven crashes occasionally when baking textures to DXT1 (aka BC1). Turns out the Nvidia texture tools lib can read outside of the image when a dimension is not a multiple of four (the compression tile-size). This includes mip levels, so minified textures probably have artifacts even if the bake doesn't crash. The bug is fixed in nvtt 2.1.1 so this PR upgrades nvtt.
For Windows we distribute nvtt as prebuilt binaries, for other platforms we distribute a copy of the source tree.

https://highfidelity.fogbugz.com/f/cases/19046/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14335/HighFidelity-Beta-PR14266-5195352.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14339/HighFidelity-Beta-PR14266-3e65fff.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14335/HighFidelity-Beta-PR14266-5195352.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14335/HighFidelity-Beta-Interface-PR14266-5195352.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14335/HighFidelity-Beta-PR14266-5195352.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14335/HighFidelity-Beta-Interface-PR14266-5195352.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14339/HighFidelity-Beta-PR14266-3e65fff.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14339/HighFidelity-Beta-Interface-PR14266-3e65fff.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14359/HighFidelity-Beta-PR14266-fd2c723.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14359/HighFidelity-Beta-PR14266-fd2c723.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14359/HighFidelity-Beta-Interface-PR14266-fd2c723.exe

**Comment by SimonWalton-HiFi** [comment]
Zombies scene (subject of original issue report):

https://files.slack.com/files-pri/T025Q3X6R-FDG0Q60Q0/download/autobackup-daily_rolling-2018-10-18_00-05-37.content.zip

**Comment by SimonWalton-HiFi** [comment]
## Test Plan
- Run the oven from the PR (`/Program Files/High Fidelity - PR14266/oven.exe` on Windows).
- For Entities File extract the Zombies scene above (or any scene with sufficient textures) and select the Models.json.gz file.
- Enter anything for Domain Name, Destination URL Path and a suitable Output Directory. Select Re-bake originals.
- Click on Bake

Results: before this PR the bake will eventually crash. It occurs randomly and it may need 2 or 3 complete bakes. The Windows error is something like `Exception thrown at 0x0000000180001A3E (nvtt.dll) in oven.exe: 0xC0000005: Access violation reading location 0x...`. With this PR there should be no crash and the baked result should be usable.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14374/HighFidelity-Beta-PR14266-9a05ef7.apk

**Comment by SimonWalton-HiFi** [comment]
### Notes
For the Windows binaries I included debug & release libs with debug pdb. I did not included 32-bit as I assume they are no longer required.
Source ball is released 2.1.1 with [Clement's fix](https://github.com/castano/nvidia-texture-tools/commit/24e63456c6cd41b50fd5187ec1570ed0d38facca#diff-fd13267a8b140dc145129988bbae9be5) and [static assert fix](https://github.com/castano/nvidia-texture-tools/commit/e442d6d390d97e6b919dd42d8798492512fa0de0#diff-f11a30afdf9833b0f468a81898582557), both for MacOS. It also has data/ removed (large and unrequired) and the nvtt tests removed (doesn't build on Linux with shared libs).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14376/HighFidelity-Beta-PR14266-1c7ea19.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14376/HighFidelity-Beta-PR14266-1c7ea19.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14376/HighFidelity-Beta-Interface-PR14266-1c7ea19.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14376/HighFidelity-Beta-Interface-PR14266-1c7ea19.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14451/HighFidelity-Beta-PR14266-1c7ea19.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14451/HighFidelity-Beta-PR14266-1c7ea19.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14451/HighFidelity-Beta-Interface-PR14266-1c7ea19.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14451/HighFidelity-Beta-PR14266-1c7ea19.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14451/HighFidelity-Beta-Interface-PR14266-1c7ea19.exe

**Comment by qlimnavarro** [comment]
Stopped Testing, moved to RC75 Release testing.

**Comment by SimonWalton-HiFi** [comment]
[rock-0.zip](https://github.com/highfidelity/hifi/files/2527381/rock-0.zip)

This OBJ file causes a crash in the PR build, though not a local release build of the branch. It prints the message `DependencyManager::get(): No instance available for class ResourceRequestObserver` before crashing. This class does not exist in this branch - only in master - so something strange is happening with the PR build.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14465/HighFidelity-Beta-PR14266-0fee8f4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14465/HighFidelity-Beta-PR14266-0fee8f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14465/HighFidelity-Beta-Interface-PR14266-0fee8f4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14465/HighFidelity-Beta-PR14266-0fee8f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14465/HighFidelity-Beta-Interface-PR14266-0fee8f4.exe

**Comment by SimonWalton-HiFi** [comment]
The latest Windows PR build runs ok for me now on the zombies scene. The OBJ reader was requiring the new ResourceRequestObserver class. I'm not not sure why a PR build was using code from master but it needed to be fixed for the merge anyway.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15030/HighFidelity-Beta-PR14266-0fee8f4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15030/HighFidelity-Beta-PR14266-0fee8f4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15030/HighFidelity-Beta-Interface-PR14266-0fee8f4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15030/HighFidelity-Beta-PR14266-0fee8f4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15030/HighFidelity-Beta-Interface-PR14266-0fee8f4.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Paused, waiting on Dev input. (Slack file is inaccessible via the given link)

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

Pass- Bake Content
Ran the Zombies domain content through the bake process 5 times, and did not find the word Exception, in the command window output. 
  Several files stated they were unable to link to a URL, but it did not crash.
Pass- Bake item
Also attempted to bake the rock from the later post and did not get the dependency warning.

**Comment by SimonWalton-HiFi** [comment]
The vcpkg build mechanism is pulling the correct version of nvtt (2.1.1) in the windows build. I have merged  master and reverted the cmake change. The ResourceRequestObserver change is still in.
I haven't tested the changes on MacOS.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15062/HighFidelity-Beta-PR14266-eeb3eb5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15062/HighFidelity-Beta-Interface-PR14266-eeb3eb5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15062/HighFidelity-Beta-PR14266-eeb3eb5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15062/HighFidelity-Beta-Interface-PR14266-eeb3eb5.exe

**Comment by SimonWalton-HiFi** [comment]
The crash with OBJ files fix has been moved to https://github.com/highfidelity/hifi/pull/14389; the remainder of this PR is no longer required.

**Pull request closed without merging**
