### PR TITLE
fixing grabbing and tablet bugs

### PR DESCRIPTION
**Pull request by druiz17**
This PR address the following tickets
https://highfidelity.fogbugz.com/f/cases/7909/double-stylus-confusion-breaks-keyboard
https://highfidelity.fogbugz.com/f/cases/7052/Grip-Trigger-doesn-t-work-to-equip-item-lighter-won-t-light
https://highfidelity.fogbugz.com/f/cases/7778/FarActionGrabModule-does-not-have-sphere-at-the-end-of-the-laser

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
1. 
- import the flare gun from the market place
- press the grip button on the hand controller to equip the gun
- press the grip button to drop the item.

2. 
- check that the far grab laser has a sphere at the end of it when intersecting with entities 

3. 
- When under heavy load (ex. when loading into dev-welcome), open the tablet. The stylus should not be in a wrong place on the avatar

4.
- open the tablet
- press down on a button with the stylus but DO NOT release
- the other second stylus should not be able to activate button while the first is still pressing on the tablet button

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3727/HighFidelity-Beta-PR11479-3b05317db67af35cffc6e46ca205a8fddea92fa0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3727/HighFidelity-Beta-PR11479-3b05317db67af35cffc6e46ca205a8fddea92fa0.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
import the flare gun from the market place **Check**
press the grip button on the hand controller to equip the gun **Check**
press the grip button to drop the item. **Check**
check that the far grab laser has a sphere at the end of it when intersecting with entities **Check, although unsure if this is referring to the below as what normally shows with the laser, or if referring to the other blue sphere which is a blue wireframe shown when grabbing items? Please let me know if this is not the correct sphere.**
image
When under heavy load (ex. when loading into dev-welcome), open the tablet. The stylus should not be in a wrong place on the avatar **Check, although it does need to load in the stylus first, but once this happens they remain in the correct place**
open the tablet **Check**
press down on a button with the stylus but DO NOT release **Check**
the other second stylus should not be able to activate button while the first is still pressing on the tablet button **Check**

I'd call this a **Pass** unless the image above is not what was being referred to, in which case please do let me know.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3735/HighFidelity-Beta-PR11479-1947f2ba9980b2d77834d166ccd07657ad7bf32c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3735/HighFidelity-Beta-PR11479-1947f2ba9980b2d77834d166ccd07657ad7bf32c.exe

**Comment by conklin94122** [comment]
QA FAIL

Testing in RC56 (PR11510), the grip trigger is unreliable at best.

**Comment by conklin94122** [comment]
Also, this PR addresses three distinct issues, please break it into three distinct PRs.

Having them bundled together complicates testing, prioritization, and release planning.

An example: I failed the grip button change, but as they're bundled, the entire PR is at issue, instead of just the grip button's PR.

**Pull request merged**
