### PR TITLE
[v0.75.0] Add audio soloing feature

### PR DESCRIPTION
**Pull request by Atlante45**
https://highfidelity.manuscript.com/f/cases/19553/Add-audio-sniper-solo-feature-to-efficiently-ask-the-mixer-for-one-or-more-specific-sources

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14792/HighFidelity-Beta-PR14356-a10ba6f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14792/HighFidelity-Beta-PR14356-a10ba6f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14792/HighFidelity-Beta-Interface-PR14356-a10ba6f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14792/HighFidelity-Beta-PR14356-a10ba6f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14792/HighFidelity-Beta-Interface-PR14356-a10ba6f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14801/HighFidelity-Beta-PR14356-403d3b9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14801/HighFidelity-Beta-PR14356-403d3b9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14801/HighFidelity-Beta-Interface-PR14356-403d3b9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14801/HighFidelity-Beta-PR14356-403d3b9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14801/HighFidelity-Beta-Interface-PR14356-403d3b9.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14812/HighFidelity-Beta-PR14356-9383228.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14812/HighFidelity-Beta-PR14356-9383228.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14812/HighFidelity-Beta-Interface-PR14356-9383228.dmg

**Comment by Atlante45** [comment]
## Test Plan:

Pre-requisite: You will need 3 people for this test.
Person `A` is running the test.
Person `B` will be the solo target.
Person `C` will act as a control

1) Run the Sandbox and gather all 3 people in the domain.
2) `B` should change their display name to "SoloTarget" (the case matters)
3) `A` should make sure that everyone can hear each other.
4) `A` should now start the following script:
https://gist.githubusercontent.com/Atlante45/4e2f433e580eb84334a7d7e92da75199/raw/29ddf8b80dda33d1325c148085d03519dbf166d5/SoloTest.js
5) From now on `A` should only be able to hear `B`
6) `B` should not be attenuated. (Move away from `B` and they should stay at the max volume.
7) Kill the script and you should now hear both `B` and `C` again.

Note: A couple more things to test while the solo is on in step 6):
- If `B` ignores(/mutes) `A`, `A` should not hear `B` even if they are soloing `B`, except if `A` is an admin.
- The bubble should not affect the soloing.

**Comment by qligmaloney** [comment]
Android Smoke Test: https://highfidelity.testrail.com/index.php?/plans/view/7495

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

B was always audible, except when ignoring A (except when A was an admin and had the PAL open). C was inaudible while script was running. Audio returned to normal when the script was stopped.

**Comment by Atlante45** [comment]
## Test Plan for new change:

Pre-requisite: You will need 3 people for this test.
Person `A` is running the test.
Person `B` will be the solo target.
Person `C` will act as a control

1) Run the Sandbox and gather all 3 people in the domain.
2) `B` should change their display name to "SoloTarget" (the case matters)
3) `A` should make sure that everyone can hear each other.
4) `A` should now start the following script:
https://gist.githubusercontent.com/Atlante45/4e2f433e580eb84334a7d7e92da75199/raw/29ddf8b80dda33d1325c148085d03519dbf166d5/SoloTest.js
5) From now on `A` should only be able to hear `B`
6) Got to the nodes tab of the domain settings webpage (http://localhost:40100)
7) Kill the audio mixer by clicking the x next to it
8) When the mixer comes back, `B` should still be soloed

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14866/HighFidelity-Beta-PR14356-f9e78bf.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14866/HighFidelity-Beta-PR14356-f9e78bf.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14866/HighFidelity-Beta-Interface-PR14356-f9e78bf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14866/HighFidelity-Beta-PR14356-f9e78bf.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14866/HighFidelity-Beta-Interface-PR14356-f9e78bf.exe

**Comment by qlipdahlin** [comment]
Currently Testing - Birarda okayed testing.

**Comment by qlipdahlin** [comment]
@conklin94122 FAIL

Setup domain and connected 3 clients to domain. Everyone could hear each other. Client B changed Display Name to SoloTarget and Client A loaded the script. Client A could only hear Client B at this point. Audio-Mixer was reset and Client A could hear Client C again. PR Fails.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14891/HighFidelity-Beta-PR14356-cfbebbc.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14898/HighFidelity-Beta-PR14356-5fba3d6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14891/HighFidelity-Beta-PR14356-cfbebbc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14891/HighFidelity-Beta-Interface-PR14356-cfbebbc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14891/HighFidelity-Beta-PR14356-cfbebbc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14891/HighFidelity-Beta-Interface-PR14356-cfbebbc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14898/HighFidelity-Beta-PR14356-5fba3d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14898/HighFidelity-Beta-Interface-PR14356-5fba3d6.dmg

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14898/HighFidelity-Beta-Interface-PR14356-5fba3d6.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Setup domain and connected 3 clients to domain. Everyone could hear each other. Client B changed Display Name to SoloTarget and Client A loaded the script. Client A could only hear Client B at this point. Only the Audio-Mixer was reset and Client A could not hear Client C, but could still hear Client B. PR passes.

**Pull request merged**
