### PR TITLE
Case 21132: Add "Avatar Script" classification to relevant JSDoc APIs

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Also fixes a couple of "Client Entity" classifications.

https://highfidelity.manuscript.com/f/cases/21132/JSDoc-Indicate-which-APIs-are-available-to-avatar-scripts

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17193/HighFidelity-Beta-PR14895-8e0ff9b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17193/HighFidelity-Beta-PR14895-8e0ff9b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17193/HighFidelity-Beta-Interface-PR14895-8e0ff9b.dmg

**Comment by ctrlaltdavid** [comment]
###Test Plan

There are no executable code changes so no testing required.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17193/HighFidelity-Beta-PR14895-8e0ff9b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17193/HighFidelity-Beta-Interface-PR14895-8e0ff9b.exe

**Pull request merged**
