### PR TITLE
Case 20700: Add missing pulse properties to certain Entity types

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/20700/Add-missing-color-alpha-pulse-properties-to-entities

Adds a new group of properties - "pulse" - to Shape, Image, Text, Web, Grid, and ParticleEffect entities.

These properties start off as deprecated.  The need for them is an unfortunate result of their existence in Overlay properties, but it's not a feature that was ever fully planned out or needed.  They could be removed at some point.

Test plan:
- Run [this](https://gist.githubusercontent.com/SamGondelman/d1016d3a160d325d41bb840ed34cf535/raw/ae46cd408c3fdac11e4005c2d63a3429865de7b2/PulseTest.js).  You'll see:
hifi-snap-by-samgondelman-on-2019-01-18_12-52-38
- Press "o".  The colors will pulse a little less:
hifi-snap-by-samgondelman-on-2019-01-18_12-53-00
- Press "i".  The alpha will pulse instead of the color:
hifi-snap-by-samgondelman-on-2019-01-18_12-53-11
- Press "o".  The alpha will pulse more:
hifi-snap-by-samgondelman-on-2019-01-18_12-53-22

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16491/HighFidelity-Beta-PR14725-611998f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16492/HighFidelity-Beta-PR14725-3835796.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16492/HighFidelity-Beta-PR14725-3835796.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16492/HighFidelity-Beta-Interface-PR14725-3835796.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16497/HighFidelity-Beta-PR14725-3008395.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16497/HighFidelity-Beta-PR14725-3008395.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16497/HighFidelity-Beta-Interface-PR14725-3008395.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16497/HighFidelity-Beta-PR14725-3008395.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16497/HighFidelity-Beta-Interface-PR14725-3008395.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16500/HighFidelity-Beta-PR14725-5c4eef3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16500/HighFidelity-Beta-PR14725-5c4eef3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16500/HighFidelity-Beta-Interface-PR14725-5c4eef3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16500/HighFidelity-Beta-PR14725-5c4eef3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16500/HighFidelity-Beta-Interface-PR14725-5c4eef3.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16504/HighFidelity-Beta-PR14725-ad2fa9e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16504/HighFidelity-Beta-PR14725-ad2fa9e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16504/HighFidelity-Beta-Interface-PR14725-ad2fa9e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16504/HighFidelity-Beta-PR14725-ad2fa9e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16504/HighFidelity-Beta-Interface-PR14725-ad2fa9e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16506/HighFidelity-Beta-PR14725-77f9f9c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16506/HighFidelity-Beta-PR14725-77f9f9c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16506/HighFidelity-Beta-Interface-PR14725-77f9f9c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16508/HighFidelity-Beta-PR14725-62b8538.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16508/HighFidelity-Beta-PR14725-62b8538.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16508/HighFidelity-Beta-Interface-PR14725-62b8538.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16508/HighFidelity-Beta-PR14725-62b8538.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16508/HighFidelity-Beta-Interface-PR14725-62b8538.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16766/HighFidelity-Beta-PR14725-a10f52c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16766/HighFidelity-Beta-PR14725-a10f52c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16766/HighFidelity-Beta-Interface-PR14725-a10f52c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16766/HighFidelity-Beta-PR14725-a10f52c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16766/HighFidelity-Beta-Interface-PR14725-a10f52c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass
Pulse looks good

**Pull request merged**
