### PR TITLE
Fix lasers going to origin when trying to far grab.

### PR DESCRIPTION
**Pull request by druiz17**
Fix lasers going to origin when trying to far grab.

ticket - https://highfidelity.fogbugz.com/f/cases/12098/Laser-points-in-random-location-when-tablet-is-open

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- start interface
- while switching domain...far grab object
- when far grabbing the laser should be pointing on the object that you are grabbing or about to grab

- note: there is a current bug that temporarily moves grabbed object away from you and then slowly bring them back.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6965/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6965/HighFidelity-Beta-PR12348-365a1fcdab228fddc399a89680a1455526c36882.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6965/HighFidelity-Beta-PR12348-365a1fcdab228fddc399a89680a1455526c36882.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7038/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7038/HighFidelity-Beta-PR12348-a0ec0f10b4d05960d3b4dee1397fdcb2f729720b.dmg

**Comment by sbennett77** [comment]
Failed. Issue seems to still exist per the videos below.

@conklin94122 

https://drive.google.com/open?id=1ySHxgwDEwwWd1HifQo-K4s5R1Dzn2BHJ

https://drive.google.com/open?id=1Tm2ERzpq36-il1pzsLVUEa7mMSTdQTgC

**Comment by druiz17** [comment]
test this please

**Comment by conklin94122** [comment]
@druiz17 Also need a version of this PR rebased on RC64.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7039/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7039/HighFidelity-Beta-PR12348-a0ec0f10b4d05960d3b4dee1397fdcb2f729720b.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7053/app_12348_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7075/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7075/HighFidelity-Beta-PR12348-a0ec0f10b4d05960d3b4dee1397fdcb2f729720b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7075/HighFidelity-Beta-PR12348-a0ec0f10b4d05960d3b4dee1397fdcb2f729720b.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7086/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7087/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7089/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7089/HighFidelity-Beta-PR12348-2ae976d2566223bf3c79481a63e8d4eb25de6fec.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7093/app_12348_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7093/HighFidelity-Beta-PR12348-2ae976d2566223bf3c79481a63e8d4eb25de6fec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7093/HighFidelity-Beta-PR12348-2ae976d2566223bf3c79481a63e8d4eb25de6fec.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
