### PR TITLE
DNM : Sam Test build

### PR DESCRIPTION
**Pull request by samcake**
Testing New texture managment with mip map generation

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 981c300524fea96b6099273230c741d9ac5b8369 available at: https://gist.github.com/443820f98656abc34a02adf578793bbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-981c300.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-981c300.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b14eac28a9b220e05134d4d30d19f3e08e520ba available at: https://gist.github.com/443820f98656abc34a02adf578793bbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-4b14eac.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-4b14eac.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5a89cafe96453f40bbd80564192e2aec9742e4f available at: https://gist.github.com/443820f98656abc34a02adf578793bbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-c5a89ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-c5a89ca.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c5a89cafe96453f40bbd80564192e2aec9742e4f available at: https://gist.github.com/443820f98656abc34a02adf578793bbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-c5a89ca.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9649-c5a89ca.dmg

**Comment by samcake** [comment]
not really useful anymore

**Pull request closed without merging**
