### PR TITLE
RC73.1 fix equip

### PR DESCRIPTION
**Pull request by danteruiz**
Description and Test plan in this PR https://github.com/highfidelity/hifi/pull/14058

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13197/HighFidelity-Beta-PR14059-41e7267.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13197/HighFidelity-Beta-PR14059-41e7267.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13197/HighFidelity-Beta-Interface-PR14059-41e7267.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Created web entity and used tablet, had blue laser on entity/tablet, and was able to near grab objects nearby with other hand. Can also near grab tablet while laser is pointed at tablet with same hand or the other.

Tested equipping and behavior is same as before defect occurred. PR Passes.

**Pull request closed without merging**
