### PR TITLE
Misc servers debug asserts fixes

### PR DESCRIPTION
**Pull request by Atlante45**
- Fixed `sendEvent called on the wrong thread` assert during the Agent and ESS startup.
- Fixed `QThread destroyed while running` assert during the Agent and EntityServer shutdown.
- Fixed `invalid read access` during Audio/Avatar Mixer shutdown.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1477/HighFidelity-Beta-PR10924-7160fca4f726044b5a4ee216be5bbe54d8f740c2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1477/HighFidelity-Beta-PR10924-7160fca4f726044b5a4ee216be5bbe54d8f740c2.exe

**Comment by Atlante45** [comment]
@AndrewMeadows Yes, this is why. I'll add a comment so that's clearer.

**Comment by Atlante45** [comment]
## Test Plan:
1) Start the Sandbox
2) Start 2 Interfaces
3) Make sure the 2 clients can see and hear each other in your sandbox.
4) Go to the Sandbox Nodes page http://localhost:40100 and kill all the nodes.
    - There's a red button for that at the bottom
5) Make sure all the servers come back.

**Comment by CainFoool** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1606/HighFidelity-Beta-PR10924-b3d73fd0dfdebfae602fc99970326b8d54482829.dmg

**Comment by CainFoool** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1622/HighFidelity-Beta-PR10924-b3d73fd0dfdebfae602fc99970326b8d54482829.dmg

**Comment by CainFoool** [comment]
@Atlante45: doesn't look like this is building on Windows.

**Comment by Atlante45** [comment]
@CainFoool Yeah, Jenkins is having issues.

**Comment by Atlante45** [comment]
test this please

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1628/HighFidelity-Beta-PR10924-b3d73fd0dfdebfae602fc99970326b8d54482829.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1628/HighFidelity-Beta-PR10924-b3d73fd0dfdebfae602fc99970326b8d54482829.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
Start the Sandbox | Pass
Start 2 Interfaces | Pass
Make sure the 2 clients can see and hear each other in your sandbox. | Pass
Go to the Sandbox Nodes page http://localhost:40100 and kill all the nodes. | 
There's a red button for that at the bottom | Pass
Make sure all the servers come back. | Pass

All working good!

Let me know if this needs further testing.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by Atlante45** [comment]
Thanks @CainFoool!

**Pull request merged**
