### PR TITLE
Enable user connection with "x" key when capslock is on

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

In desktop mode, check that you can make a user connection with "x" key, both when capslock is on and when capslock is off

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

@ctrlaltdavid Do I need to confirm the connection is made with 2 clients, or just ensure hand goes up to handshake to make the connection?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5613/HighFidelity-Beta-PR11977-627ce8ab87ffa252be83fca5f4851d0d0ecd550f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5613/HighFidelity-Beta-PR11977-627ce8ab87ffa252be83fca5f4851d0d0ecd550f.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by ctrlaltdavid** [comment]
@YuppyPlays Best to check that you can make a connection

**Comment by YuppyPlays** [comment]
@ctrlaltdavid 
No problem, I'll setup my 2nd client now :)

**Comment by YuppyPlays** [comment]
Testing complete:

Using 2 clients and 2 login accounts, used a mix of caps lock and non-caps lock on each computer to handshake and make a connection, all of them went through as expected. **Pass**

**Pull request merged**
