### PR TITLE
Migrating to scribe program descriptors

### PR DESCRIPTION
**Pull request by jherico**
## TEST PLAN 
It must compile on every platforms obviously
It must run without any shader error on every platforms (windows-[gpu vendors], mac, android

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12014/HighFidelity-Beta-PR13802-f03370c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12014/HighFidelity-Beta-PR13802-f03370c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12014/HighFidelity-Beta-Interface-PR13802-f03370c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12014/HighFidelity-Beta-PR13802-f03370c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12014/HighFidelity-Beta-Interface-PR13802-f03370c.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by samcake** [comment]
@qlimnavarro  Can you please confirm no shader error on all platforms
windows - [gpu vendors]   (nvidia, amd)
mac
THanks

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12190/HighFidelity-Beta-PR13802-f03370c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12190/HighFidelity-Beta-PR13802-f03370c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12190/HighFidelity-Beta-Interface-PR13802-f03370c.dmg

**Comment by qaAdamSmith82** [comment]
Currently testing Mac

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12190/HighFidelity-Beta-PR13802-f03370c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12190/HighFidelity-Beta-Interface-PR13802-f03370c.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
PASS @conklin94122 
Build ran with no shader errors on Win10 AMD GPU

**Comment by qaAdamSmith82** [comment]
@conklin94122  PASS on Mac also

**Pull request merged**
