### PR TITLE
Fix mouse disappearing when switching to desktop mode from HMD

### PR DESCRIPTION
**Pull request by druiz17**
Fix mouse disappearing when switching to desktop mode from HMD

ticket to this issue https://highfidelity.fogbugz.com/f/cases/8114

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- be in HMD mode
- move your mouse around until you see the cursor
- switch over to desktop mode and DO NOT move the mouse for about 5 - 10 seconds, your mouse cursor should still be visible

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3931/HighFidelity-Beta-PR11535-3139f5ef2a2b29c4b6e4328b59bf7679256bec54.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3931/HighFidelity-Beta-PR11535-3139f5ef2a2b29c4b6e4328b59bf7679256bec54.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
be in HMD mode | Pass
move your mouse around until you see the cursor | Pass
switch over to desktop mode and DO NOT move the mouse for about 5 - 10 seconds, your mouse cursor should still be visible | Pass

All good!

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
