### PR TITLE
Allow farGrab module to run when stylus is visible

### PR DESCRIPTION
**Pull request by druiz17**
Allow farGrab module to run when stylus is visible

This PR fixes this https://highfidelity.fogbugz.com/f/cases/8106/If-stylus-are-visible-the-laser-doesn-t-show-unless-aiming-directly-at-tablet

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- bring up the tablet
- when the stylus is showing and not pointing at the tablet.
- you should be able to far grab objects.

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3893/HighFidelity-Beta-PR11526-4f0dd72971b482ad27adc4fda4712664ff53bda7.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

bring up the tablet **Check**
when the stylus is showing and not pointing at the tablet you should be able to far grab objects. **Check**

**Notes: probably intentional but I notice now the stylus disappears even when using the laser pointing on the tablets screen.**

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3898/HighFidelity-Beta-PR11526-4f0dd72971b482ad27adc4fda4712664ff53bda7.dmg

**Comment by conklin94122** [comment]
QA needs to retest the next build, which has the fix in RC56, not master.

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3905/HighFidelity-Beta-PR11526-4f0dd72971b482ad27adc4fda4712664ff53bda7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3905/HighFidelity-Beta-PR11526-4f0dd72971b482ad27adc4fda4712664ff53bda7.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

bring up the tablet **Check**
when the stylus is showing and not pointing at the tablet you should be able to far grab objects.  **Check**

I've run into an issue which I believe is related though not certain, but noted by John in PR 11527,  an issue where the laser would stay active when not pressed, I am seeing when entering Create mode- at random it seems whilst flicking in and out of the Create app is the end-laser sphere is large and stuck along with the laser, in image I am not holding the trigger at all, just pointing it at the tablet whilst taking a screenshot.
image

**Fail**

**Pull request closed without merging**
