### PR TITLE
[DNM] Worklist Item #21698:  A-Frame to High Fidelity Import

### PR DESCRIPTION
**Pull request by 1P-Cusack**
This is the current progress for the A-Frame to High Fidelity Import functionality. The ticket can be found [here](https://worklist.net/21698). There's a fundamental difference in the level of control of geometry that users will see between the two systems, and the initial plan was to look to see what level of effort would be needed to try to have a 1:1 level control for the conversion. It didn't appear to be cost effective, instead a higher level conversion in HiFi was elected to get a close approximation for the common shapes and types that could be converted.  Most of the basic functionality of the A-Frame types are in:

- 11/15 of the requested entity types have importing supported
    - `a-gltf-model`, while requested, hifi doesn't appear to support this model type and thus can't be implemented.
    - `a-sky` needs some attention and may not be convertible between the two systems
    - `a-triangle`, given the difference in level of control for geometry between the 2 systems, isn't likely worth the effort to convert as it's usage isn't likely that high. If that's not the case, it can be added at a later though there will likely be caveats based on approach and type of triangle.
- Support for the following is also in; however, limited to supported primitive A-Frame types and components:
    - `a-entity`
    - `a-asset-image`
    - `a-asset-item`
    - `img`
    - `a-mixin`: This is currently exclusive to a-entity support; however, could be expanded to primitive types if desired.
- Supported file types for A-Frame import:  html, htm, HTML, HTM

- Remaining Known Items:
    - Rotation is off, may be a combination of handedness and units or something else
    - Scale isn't currently handled, it needs some additional investigation. The `EntityItem `doesn't explicitly have the concept of scale save for scaled & un-scaled dimensions, though it does inherit transform from `SpatiallyNestable`. It's not clear currently if direct manipulation of that is allowed or if it's expected that the internal management pipeline should be touching that data; nothing plumbs through to it from the Interface to the `EntityItem `that I've been able to find thus far.

** Testing **
- Using either:
    - Create Menu -> Create Tab -> Import Entities
    - Edit Menu -> Import Entities
- From the resulting file explorer, navigate to the branch's test/entities/aframe directory and elect one of the _non_Web_ html files to import.
    - Note:  Within the file browser json, html, htm, HTML, & HTM files will show up as viable options for import.  To trigger the A-Frame importing behavior elect a file with an extension that's one of the html variants.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9479/HighFidelity-Beta-PR13095-2629083e16807721c9ed6f1385207b5d5383df28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9479/HighFidelity-Beta-Interface-PR13095-2629083e16807721c9ed6f1385207b5d5383df28.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9513/HighFidelity-Beta-PR13095-be3a283e62436c2e7b8b80c8cb91ad3b914ece30.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9513/HighFidelity-Beta-Interface-PR13095-be3a283e62436c2e7b8b80c8cb91ad3b914ece30.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9567/HighFidelity-Beta-PR13095-dbc9a211f1036ddebddb57dd47245b6a119830d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9567/HighFidelity-Beta-Interface-PR13095-dbc9a211f1036ddebddb57dd47245b6a119830d4.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9761/HighFidelity-Beta-PR13095-243371ee0175b6f2f145ad5c2faf3d1ef86caf57.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9761/HighFidelity-Beta-Interface-PR13095-243371ee0175b6f2f145ad5c2faf3d1ef86caf57.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9814/HighFidelity-Beta-PR13095-f3f6cf4ea0e8b160c57b6c7344fe336d23cc0086.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9814/HighFidelity-Beta-Interface-PR13095-f3f6cf4ea0e8b160c57b6c7344fe336d23cc0086.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
