### PR TITLE
fix Tablet webview issues of not loading correct url.

### PR DESCRIPTION
**Pull request by druiz17**
Refactored the way we load and store the navigation history, which fixes the issues of loading the incorrect web URL

This PR fixes this fogbugz issue - https://highfidelity.fogbugz.com/f/cases/4079/Cannot-seem-to-share-from-address-bar

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- In tablet mode, go to the  goto page
- click the (i) icon of a location or snapshot
- once the webpage shows up click facebook share button.
- the facebook page should appear (If you want...do the necessary actions to share, check your facebook feed to confirm the post on your feed)
- do the same with the twitter tweet button

**Comment by hifi-gustavo** [comment]
Build console output for commit: a08b55d5f560e21373bca67d08ec938b096b5573 available at: https://gist.github.com/2be479b7b7d508da1386fc101c7ee68f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10343-a08b55d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10343-a08b55d.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10343-a08b55d.exe

PASS:
- I tested in HMD and in Desktop
- Went to the goto page
- Clicked the (i) icon of dev-welcome
- Once the web page showed up, I clicked the Facebook share button.
- The Facebook page appeared. 
- I shared and checked my Facebook feed. The message did post in feed.
- I did the same with the Twitter. My message also posted.

FAILS:
-In HMD, the numbers on the keyboard did not work when I was trying to write a message in the Facebook or Twitter message field. The dialog that shows the numbers right above the keyboard was not showing up.

**Comment by druiz17** [comment]
I will create a FogBugz ticket for the issues relating to the keyboard.

**Pull request merged**
