### PR TITLE
suppress repeated 'item could not be rendered' messages

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- make sure that 'Item could not be rendered with invalid key" isn't filling up your interface log file

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3178/HighFidelity-Beta-PR11332-967d3f69d3dfa7ff54faedf358f761bc75eb33f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3178/HighFidelity-Beta-PR11332-967d3f69d3dfa7ff54faedf358f761bc75eb33f2.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
make sure that 'Item could not be rendered with invalid key" isn't filling up your interface log file | Pass

All good from here. 

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
