### PR TITLE
BUGZ-781: Additional debugging for dropped avatar data

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Ticket: https://highfidelity.atlassian.net/browse/BUGZ-781

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20246/HighFidelity-Beta-PR15881-5974776.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20246/HighFidelity-Beta-Interface-PR15881-5974776.dmg

**Comment by SimonWalton-HiFi** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20250/HighFidelity-Beta-PR15881-5974776.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20250/HighFidelity-Beta-Interface-PR15881-5974776.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20250/HighFidelity-Beta-PR15881-5974776.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20250/HighFidelity-Beta-Interface-PR15881-5974776.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20250/HighFidelity-Beta-PR15881-5974776.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20250/HighFidelity-Quest-Beta-PR15881-5974776.apk)

**Pull request merged**
