### PR TITLE
update fs-extra for dependency update of brace-expansion

### PR DESCRIPTION
**Pull request by birarda**
- updated server-console dependency fs-extra

### CODE REVIEW

**Comment by birarda** [comment]
No breaking API changes for fs-extra from this update (per https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md).

#### Test Plan

Install the Sandbox from this PR. Run it. Ensure it downloads the home content set and that you see when you you "Go Home" from the menu. Ensure that you can view the logs of the domain-server and assignment-clients from your Sandbox tray option.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7567/app_12512_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7567/HighFidelity-Beta-PR12512-4f995690465e6d73f577a76ca812a6bdf748652c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7567/HighFidelity-Beta-PR12512-4f995690465e6d73f577a76ca812a6bdf748652c.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass 
Home content is downloaded and logs are displayed when accessed through the sandbox tray icon as expected.
@conklin94122

**Comment by conklin94122** [comment]
@birarda needs milestone and dev review

**Pull request merged**
