### PR TITLE
Entity Script Server memory leak when taking down EntityTree

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
The EntityTree held by EntityTreeHeadlessViewer has a couple of shared_ptr cycles preventing it from being deallocated: The EntityTreeElements hold pointers to the owning EntityTree. ~EntityTree calls eraseAllOctreeElements() to remove all elements, which should remove the cycles, but ~EntityTree itself never gets called. SimpleSimulation holds a pointer to its EntityTree, which also holds a pointer to its simulation.

This PR fixes the first cycle by calling eraseAllOctreeElements() from ~OctreeProcessor, its owner, instead. Using weak pointers for the back pointers also worked; I don't know which is preferable.  ~EntityTreeHeadlessViewer clear the simulation's pointer to break the second cycle. The simulation destructor doesn't require the tree. Weak pointers would also work.

The PR also fixes an uninitialized LocalID use that valgrind found.

### CODE REVIEW

**Comment by SimonWalton-HiFi** [comment]
https://highfidelity.manuscript.com/f/cases/7791/Entity-Server-memory-leak-while-clients-connected

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10541/HighFidelity-Beta-PR13357-9ae3411.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10541/HighFidelity-Beta-PR13357-9ae3411.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10541/HighFidelity-Beta-Interface-PR13357-9ae3411.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10541/HighFidelity-Beta-PR13357-9ae3411.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10541/HighFidelity-Beta-Interface-PR13357-9ae3411.exe

**Comment by SimonWalton-HiFi** [comment]
## Test Plan

The entity script server can be reset from the domain-server web interface by going to the Nodes page and clicking on the X in the Kill column and entity-script-server row. This will not terminate the process but simply get it to restart.

1. Run the domain server, assignment clients and interface on a domain in which some entities are running server scripts (indicated in Create -> Properties -> Server Script URL) .

2. Repeatedly restarting the entity script server should not cause its memory footprint (as indicated in Task Manager, for example) to increase (with this PR).

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10788/HighFidelity-Beta-PR13357-9ae3411.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10788/HighFidelity-Beta-PR13357-9ae3411.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10788/HighFidelity-Beta-Interface-PR13357-9ae3411.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10788/HighFidelity-Beta-PR13357-9ae3411.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10788/HighFidelity-Beta-Interface-PR13357-9ae3411.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No Memory leaks.

**Pull request merged**
