### PR TITLE
Fix for Oculus reset view issue

### PR DESCRIPTION
**Pull request by jherico**
RC77 version of #14570

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16171/HighFidelity-Beta-PR14648-8a3f1d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16171/HighFidelity-Beta-Interface-PR14648-8a3f1d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16171/HighFidelity-Beta-PR14648-8a3f1d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16171/HighFidelity-Beta-Interface-PR14648-8a3f1d6.exe

**Comment by jherico** [comment]
build this please

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16176/HighFidelity-Beta-PR14648-8a3f1d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16176/HighFidelity-Beta-Interface-PR14648-8a3f1d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16176/HighFidelity-Beta-PR14648-8a3f1d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16176/HighFidelity-Beta-Interface-PR14648-8a3f1d6.exe

**Pull request merged**
