### PR TITLE
(case 19302) Rename HFMGeometry to HFMModel and adjust related variables

### PR DESCRIPTION
**Pull request by sabrina-shanman**
https://highfidelity.manuscript.com/f/cases/19302/improve-model-loading-tool-chain-project-Phase-1

As part of Phase 1 of the Model Improvement project, this PR corrects an oversight in https://github.com/highfidelity/hifi/pull/14308 and re-names HFMGeometry to HFMModel.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14676/HighFidelity-Beta-PR14338-cbca77b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14676/HighFidelity-Beta-PR14338-cbca77b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14676/HighFidelity-Beta-Interface-PR14338-cbca77b.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14716/HighFidelity-Beta-PR14338-30eb360.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14716/HighFidelity-Beta-PR14338-30eb360.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14716/HighFidelity-Beta-Interface-PR14338-30eb360.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14723/HighFidelity-Beta-PR14338-30eb360.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14723/HighFidelity-Beta-PR14338-30eb360.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14723/HighFidelity-Beta-Interface-PR14338-30eb360.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14723/HighFidelity-Beta-PR14338-30eb360.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14723/HighFidelity-Beta-Interface-PR14338-30eb360.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Build works as expected

**Comment by samcake** [comment]
Thanks, all good, merging

**Pull request merged**
