### PR TITLE
Fixes for handling hostnames

### PR DESCRIPTION
**Pull request by caitlynmeeks**
Added some functionality in handleLookupString in AddressManager.cpp so that it can use port numbers.  This isn't supported normally.  For example:

`hifi://hifi.cutelab.space:50002`

would not connect to that host and port.  We need this to work for our server configuration. The fix uses regex to identify host, port and path, and sets setPort on the qurl passed to handleURL, defaults to 40102 if not provided.  It strips out the port from the final string and appends the path back on to it and sends it as a correctly formatted lookupUrl

https://highfidelity.atlassian.net/browse/BUGZ-1495

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21356/HighFidelity-Beta-PR16198-65578cc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21356/HighFidelity-Beta-Interface-PR16198-65578cc.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21356/HighFidelity-Beta-PR16198-65578cc.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21356/HighFidelity-Quest-Beta-PR16198-65578cc.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21356/HighFidelity-Beta-PR16198-65578cc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21356/HighFidelity-Beta-Interface-PR16198-65578cc.exe

**Comment by ZappoMan** [comment]
@caitlynmeeks - we're looking at code now, and trying to better understand the pros and cons of it.

Here are some things we could use from you to help us out:
- can you include a set of example URLs you tested this with?
- do you know why QUrl isn't already handling port? it should be?
- are you only trying to get this to work with IP/DNS names? and not place names?

We think by inspection, that this code as written might break automatic networking with ICE based place names.

We are also trying to better understand where the port is being dropped... and why QUrl doesn't handle it properly to being with.

Can you give us a list of URLs that aren't working prior to this change. With Servers running so we can test the existing code as well as this PR.

Thanks

**Comment by caitlynmeeks** [comment]
Hey there,

Thanks for taking the time to look into this.

*Can you include a set of example URLs you tested this with?*
Gladly:

hifi://hifi.cutelab.space:50022  (aka makerbox)
hifi://hifi.cutelab.space:50082 (aka Silence)
hifi://hifi.cutelab.space:50062 (aka Caitlyn)


*Do you know why QUrl isn't already handling port? it should be?*
QUrl handles ports fine f you use IP addresses, but it isn't parsed out
when you use a DNS name.


*Are you only trying to get this to work with IP/DNS names? and not place
names?  *Right

Cheers
Caitlyn

**Comment by shanzzam** [comment]
@caitlynmeeks we are closing this PR in favor of https://github.com/highfidelity/hifi/pull/16273

**Pull request closed without merging**
