### PR TITLE
FB18069 - rc73

### PR DESCRIPTION
**Pull request by jherico**
rc73 version of #14073

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13334/HighFidelity-Beta-PR14082-658c1d7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13334/HighFidelity-Beta-Interface-PR14082-658c1d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13334/HighFidelity-Beta-PR14082-658c1d7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13334/HighFidelity-Beta-Interface-PR14082-658c1d7.exe

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13339/HighFidelity-Beta-PR14082-658c1d7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13339/HighFidelity-Beta-PR14082-658c1d7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13339/HighFidelity-Beta-Interface-PR14082-658c1d7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13339/HighFidelity-Beta-PR14082-658c1d7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13339/HighFidelity-Beta-Interface-PR14082-658c1d7.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
