### PR TITLE
reduce log spam for the deadlock watchdog

### PR DESCRIPTION
**Pull request by ZappoMan**
Cleans up the deadlock watchdog messages a little bit. Adds a developer menu to suppress some of these messages.

### CODE REVIEW

**Comment by ZappoMan** [comment]
Testing Notes:
- Smoke test
- Check the Developer > Timing > Suppress Deadlock Watchdog Stats
- verify that the 5 second status messages don't send.

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2c3aeddbe4fd8bc6992b64e0a4ce1c51f2d3bba8 available at: https://gist.github.com/9e1af487348ae0dcbd7c620a21994add<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7609.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7609.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
[Repeatedly]
Turning off deadlock messages - good.
Turning on deadlock messages - good.

Persisting of setting across launches - good.

QA Pass 

I recorded several crash on close events with this via BugSplat, but... there was a cluster of 3 crashes then it went back to not crashing on close.  It doesn't "feel" like it's coming from this PR.

**Comment by ZappoMan** [comment]
Actually @OmegaHeron - I just checked the bugsplats and at least one of those crashes was from this PR... let me check this out.

**Comment by ZappoMan** [comment]
@OmegaHeron - ok - I fixed that crash... should be better in this next build.

**Comment by OmegaHeron** [comment]
@ZappoMan - cool - will retest once available, be just a few before I can get to it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bd1eb5842a17b4b03121f697f411bb8861ec27f2 available at: https://gist.github.com/9e1af487348ae0dcbd7c620a21994add<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7609.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7609.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1a2a30c024e922484ac09766ef82ee7109e7b82 available at: https://gist.github.com/9e1af487348ae0dcbd7c620a21994add<br/><br/>Installers available for download at: <br/>Windows: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7609.exe<br/>OS X: http://s3-us-west-1.amazonaws.com/hifi-pr-builds/HighFidelity-Alpha-PR7609.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7 - repeated steps that led me to crashlandia before - no crash on exit logged.  Suppression of timer messages works and persists across run sessions.  :+1: 

QA Pass

**Pull request merged**
