### PR TITLE
when in serverless mode, short-circuit simulation ownership bids

### PR DESCRIPTION
**Pull request by sethalves**
- when in serverless mode, short-circuit simulation ownership bids

https://highfidelity.manuscript.com/f/cases/14927

this is the rc-67 version of https://github.com/highfidelity/hifi/pull/13134

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- go to serverless tutorial (if you don't start there, open GOTO and visit file:///~/serverless/tutorial.json )
- use CREATE to rez a cube and make it dynamic
- close CREATE
- grab the cube and gently throw it
- wait until the cube has stopped moving for 2 seconds
- note that the cube doesn't snap back to where it was when you released it
- go to a serverfull domain
- rez a cube, make it dynamic, throw it
- generally toss around some dynamic entities and make sure they act as you expect

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9633/app_13137_PR_db03265a6b8e0f2fa4873929fc5ec3c932e71d71.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9633/HighFidelity-Beta-PR13137-db03265a6b8e0f2fa4873929fc5ec3c932e71d71.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9633/HighFidelity-Beta-Interface-PR13137-db03265a6b8e0f2fa4873929fc5ec3c932e71d71.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9633/HighFidelity-Beta-PR13137-db03265a6b8e0f2fa4873929fc5ec3c932e71d71.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9633/HighFidelity-Beta-Interface-PR13137-db03265a6b8e0f2fa4873929fc5ec3c932e71d71.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
