### PR TITLE
enable compression in image library from Asset Server

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2968/HighFidelity-Beta-PR11288-6dec61019b8612268811d440e0bafddde7204746.exe

**Comment by OmegaHeron** [comment]
@birarda 
I'm guessing this autobake is in early stages, but, lest I get caught unaware... Is fbx sdk about to become a requirement or will final version of this gracefully not use these new features if fbx sdk is not available at compile time or something else?

I have a hand full of people using my Ubuntu packages and would like to either get them up to spec on having fbx sdk installed or finding another solution for their Interface/Stack supplier.

**Comment by birarda** [comment]
The final version of this (a couple of weeks yet) won't use the FBX SDK. 

On Thu, Aug 31, 2017 at 12:29 PM "Joe Large [Omega Heron]"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/birarda
I'm guessing this autobake is in early stages, but, lest I get caught unaware... Is fbx sdk about to become a requirement or will final version of this gracefully not use these new features if fbx sdk is not available at compile time or something else?

I have a hand full of people using my Ubuntu packages and would like to either get them up to spec on having fbx sdk installed or finding another solution for their Interface/Stack supplier.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/highfidelity/hifi/pull/11288#issuecomment-326397473
, or

**Comment by OmegaHeron** [comment]
Thank you

**Comment by BillWindwalker** [comment]
Is image compression part of an asset server ?

**Comment by OmegaHeron** [comment]
It seems a logical place to do the conversion from native jpg/png/etc to ktx as it has a light workload and handles mapping from user provided assets by name to hash.  As such it is, imho, the best place to do any conversions and remap the user provided assets to the "baked" asset collection.

**Comment by birarda** [comment]
@OmegaHeron + @BillWindwalker this is a merge into our `feat/auto-bake` branch, which is for an ongoing project to add asset optimization into the Asset Server (including the compression of asset textures).

More to come as we complete the project and release it.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2978/HighFidelity-Beta-PR11288-0d034a9f13cc55fd2a72fe695b31f6a671509336.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3037/HighFidelity-Beta-PR11288-07f472f7f31208b45a7d2673440918390ec053ed.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3099/HighFidelity-Beta-PR11288-5e105a9f45cfe10c76fcb137653f1524f993eda5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3124/HighFidelity-Beta-PR11288-bd36ba19b32775b3e4079091452b1bd8bea14321.exe

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3140/HighFidelity-Beta-PR11288-8e122101bf3abb0ce67937cbe134d2461843a7c5.exe

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3159/HighFidelity-Beta-PR11288-8e122101bf3abb0ce67937cbe134d2461843a7c5.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3239/HighFidelity-Beta-PR11288-bd36ba19b32775b3e4079091452b1bd8bea14321.exe

**Pull request merged**
