### PR TITLE
Beta Release Candidate 6 - including up to Development Release 4761

### PR DESCRIPTION
**Pull request by ZappoMan**
- correctly detect latest oculus runtime
- tweaks to LOD
- fix to audio & avatar mixers with changing system clocks
- fix to crash in network sending
- fix to reset scripting state when changing domains
- fix to log spam related to GL version in QML
- added MyAvatar onLoadComplete callback for scripts
- render performance improvement
- memory leak fixes
- fix rendering text3dt overlays with transparent text
- fix to gcc5.3.1/Ubuntu 16.04 builds
- fix to crashes in reload cache content
- fix to application name in installer
- fix to lag in avatar attachments
- fix to initial placement of windows and tool bars in the HMD
- fix to open file for OSX
- performance and memory improvements in rendering the star skybox
- fix to crash in entity server with entities moving off the domain
- performance improvement to texture loading
- fix crash in texture loading and texture cache
- generate normal maps from bump maps

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8631fa6cd3720fdba3e8a5c4772604672b6f674f available at: https://gist.github.com/1f2fcc6c24a844aa071a4240115cbb0e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7717.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7717.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8631fa6cd3720fdba3e8a5c4772604672b6f674f available at: https://gist.github.com/1f2fcc6c24a844aa071a4240115cbb0e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7717.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7717.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7717
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost, playa, cellscience
**Smoke Test Results:** Successful test.

                                  |localhost |playa    |cellscience  
----------------------------------|----------|---------|-----------
Render Rate:                      |60.00     |59.87    |60.27
Present Rate:                     |60.02     |60.00    |60.00
Simrate:                          |60.03     |60.01    |60.06
Render Stats Num Buffers:         |3439      |2698     |2427
Render Stats gpu::Buffer Memory:  |38.4Mb    |69.9Mb   |46.0Mb
Render Stats Num Textures:        |321       |278      |66
Render Stats gpu::Texture Memory: |1204.6Mb  |1051.0Mb |408.6Mb
Render Stats Triangles:           |1400k     |478k     |475k
Render Stats Drawcalls:           |692       |270      |179
Render Stats State Changes:	  |578       |324      |84
Render Stats Items:               |377       |244      |771
Render Stats Timing:              |5.9ms     |5.2ms    |7.1ms
GPU-Z Memory Size                 |4096Mb    |4096Mb   |4096Mb
GPU-Z Initial Memory		  |239Mb     |239Mb    |239Mb
GPU-Z Memory Used		  |1921Mb    |2275Mb   |852Mb
GPU-Z Memory Load		  |32%       |33%      |9%

**localhost ‘createtestblocks.js’ Result:** Successful test.
**localhost ATP Upload (kelectricguitar10.fbx):** Successful test.
**localhost ‘harmonicOscillator.js’ Result:** Successful test.
**localhost Echo Server Audio Result:** Successful test.
**localhost ‘reverbTest.js’ Result:** Successful test.
**Additional Test Results Requested:** (none)
**Successful Logout/Crash:** Successful test.

**Comment by OmegaHeron** [comment]
Tested domain-server/assignment-client Ubuntu 15.10/QT5.5.1 :+1: 
Tested domain-server/assignment-client Ubuntu 16.04/QT5.5.1 :+1: 
Tested domain-server/assignment-client Ubuntu 16.04/QT5.6.0 :+1: 
Interface, ice-server and vhacd-util compile and work under all combos of above as well.

Windows 7 Interface works as expected - crashes not covered by this PR still exist (as expected)

**Comment by ZappoMan** [comment]
I wanted to do a quick test to compare the "render/loading" performance of RC5 vs this RC6 build... here are the results -- running `playaPerformance.js`

RC5:
pr-7720-rc5ish-a
pr-7720-rc5ish-c
pr-7720-rc5ish-b

This PR:
pr-7717-a
pr-7717-d
pr-7717-c
pr-7717-b

**Pull request merged**
