### PR TITLE
Beta Release 57 - Includes up to Developer Release 7288

### PR DESCRIPTION
**Pull request by cozza13**
- Create Mode: keyboard focused entry field is not https://github.com/highfidelity/hifi/pull/11476
 - Fix interface crash in Debug build https://github.com/highfidelity/hifi/pull/11476
 - Bugfix: edit.js dialog callback events stacking up https://github.com/highfidelity/hifi/pull/11482
 - Disable grab.js in HMD https://github.com/highfidelity/hifi/pull/11484
 - Fix entity add after incomplete rezCertified implementation https://github.com/highfidelity/hifi/pull/11483
 - Fixing grabbing and tablet bugs https://github.com/highfidelity/hifi/pull/11479
 - Server only deletes an entity if it's still the child of an avatar, not if it has ever been https://github.com/highfidelity/hifi/pull/11488
 - Oculus: Bug fix for head offset on large/small scaled avatars. https://github.com/highfidelity/hifi/pull/11485
 - Support animation of model overlays https://github.com/highfidelity/hifi/pull/11481
 - Entity-server uses differential Octree traversal and priority-queued EntityItems https://github.com/highfidelity/hifi/pull/11141
 - Fix getting stuck in T-Pose on avatar switch https://github.com/highfidelity/hifi/pull/11492
 - Fix ModelOverlay visible change https://github.com/highfidelity/hifi/pull/11497
 - Bug fix for offset of animated parts of oculus touch controller display https://github.com/highfidelity/hifi/pull/11493
 - Remove mouse area for text fields. use activeFocusOnPress property in 
stead https://github.com/highfidelity/hifi/pull/11490
 - Disable watchdog with environment variable https://github.com/highfidelity/hifi/pull/11491
 - Asset Browser tweaks https://github.com/highfidelity/hifi/pull/11471
 - Fix reload button in Running Scripts dialog stops script https://github.com/highfidelity/hifi/pull/11503
 - Hud module. check if the laser is pointing at UI element without moving the reticle first https://github.com/highfidelity/hifi/pull/11509
 - Tweak debug stats for more clarity https://github.com/highfidelity/hifi/pull/11504
 - Added workaround to enable menu bar under Linux https://github.com/highfidelity/hifi/pull/11478
 - Bug fix for deadlock https://github.com/highfidelity/hifi/pull/11513
 - Fix hudOverlayPointer logic https://github.com/highfidelity/hifi/pull/11516
 - Fix calling AvatarManager.findRayIntersection() from script https://github.com/highfidelity/hifi/pull/11518
 - Login dialog rework https://github.com/highfidelity/hifi/pull/11489
 - Updating placeholder.js to use a url that points to example scripts https://github.com/highfidelity/hifi/pull/11502
 - Expose performance hot spot in stats details https://github.com/highfidelity/hifi/pull/11512
 - Moving Camera update and render frame to Game Loop (Main thread) https://github.com/highfidelity/hifi/pull/11499
 - Update macOS build guide https://github.com/highfidelity/hifi/pull/11528
 - Add removal of temporary files in FBXBaker https://github.com/highfidelity/hifi/pull/11472'
 - Fix alignment of audio devices input header https://github.com/highfidelity/hifi/pull/11529
 - Fix and improve laser pointer locking https://github.com/highfidelity/hifi/pull/11506
 - Fix microphone audio on the Mac https://github.com/highfidelity/hifi/pull/11530
 - Fix mouse disappearing when switching to desktop mode from HMD https://github.com/highfidelity/hifi/pull/11535
 - Improve log naming https://github.com/highfidelity/hifi/pull/11326
 - **VR edit app** https://github.com/highfidelity/hifi/pull/10892
 - Fix rendering transform for text3d overlays https://github.com/highfidelity/hifi/pull/11545
 - Make building tools (besides 'scribe') optional https://github.com/highfidelity/hifi/pull/11291
 - Fix DQT_CMAKE_PREFIX_PATH being overwritten https://github.com/highfidelity/hifi/pull/11536
 - Add script that tests setting your listening position and orientation https://github.com/highfidelity/hifi/pull/11543
 - Move Shapes app files from scripts directory to marketplace directory https://github.com/highfidelity/hifi/pull/11548
 - Fixed typo in qWarning message https://github.com/highfidelity/hifi/pull/11539
 - Fixed looping sample sound bug https://github.com/highfidelity/hifi/pull/11550
 - Find nearby entities at login https://github.com/highfidelity/hifi/pull/11531
 - Remainder of entitySelectionTool clean up https://github.com/highfidelity/hifi/pull/11338
 - Add uploading to asset server event https://github.com/highfidelity/hifi/pull/11451
 - Fix the error in the Asset Browser https://github.com/highfidelity/hifi/pull/11557
 - Under the hood support for HDR cube maps https://github.com/highfidelity/hifi/pull/11349
 - Far grab non-dynamic entities https://github.com/highfidelity/hifi/pull/11560
 - Move HUD and HUD overlay rendering out of display plugin https://github.com/highfidelity/hifi/pull/11542
 - On Domains without Edit Access, Create Button Text still Highlights https://github.com/highfidelity/hifi/pull/11383
 - More correct use of BufferView in GeometryCache https://github.com/highfidelity/hifi/pull/11561
 - Allow project to be built with clang on Linux https://github.com/highfidelity/hifi/pull/11549
 - Remove unnecessary blocking call https://github.com/highfidelity/hifi/pull/11570
 - Remove unused HFMetaEvents https://github.com/highfidelity/hifi/pull/11576
 - Fix the HDR generation of cube maps from equirect images (1x2) https://github.com/highfidelity/hifi/pull/11577
 - Keyboard Input Field: Pressing Space should Clear Field https://github.com/highfidelity/hifi/pull/11580
 - Import av entities https://github.com/highfidelity/hifi/pull/11554
 - Leveraging the new auto-baking in the Asset Server to bake JS files by minifying them. https://github.com/highfidelity/hifi/pull/11455
 - Crash/Deadlock fix: Web3DOverlay could be destroyed on wrong thread.  https://github.com/highfidelity/hifi/pull/11578

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4129/HighFidelity-Beta-PR11589-4dcce6ef45e53eececf063e8f53043552385aceb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4129/HighFidelity-Beta-PR11589-4dcce6ef45e53eececf063e8f53043552385aceb.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4168/HighFidelity-Beta-PR11589-c25008cff3d25dc725afb23500d64adea7b794fc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4168/HighFidelity-Beta-PR11589-c25008cff3d25dc725afb23500d64adea7b794fc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4179/HighFidelity-Beta-PR11589-46f0189ab49110cf9992dbf528f8ccb8165769f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4179/HighFidelity-Beta-PR11589-46f0189ab49110cf9992dbf528f8ccb8165769f2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4197/HighFidelity-Beta-PR11589-42a018c2c5034c26b3c0e51e03a2385694310582.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4197/HighFidelity-Beta-PR11589-42a018c2c5034c26b3c0e51e03a2385694310582.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4257/HighFidelity-Beta-PR11589-38de88bb6882fa98f74fbbae890e0693139a8750.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4261/HighFidelity-Beta-PR11589-2ab606a98b4588ef5c436c2f27101600ea86484d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4303/HighFidelity-Beta-PR11589-f8a01dffb09b388f4c15bd3cd481bc2d38713b9f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4303/HighFidelity-Beta-PR11589-f8a01dffb09b388f4c15bd3cd481bc2d38713b9f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4305/HighFidelity-Beta-PR11589-352243c01bf42b7b4199dc7061a71efa4e8c2ba6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4305/HighFidelity-Beta-PR11589-352243c01bf42b7b4199dc7061a71efa4e8c2ba6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4318/HighFidelity-Beta-PR11589-c77fbe1a9d44fc0c73ae5c137257e2c138d59901.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4318/HighFidelity-Beta-PR11589-c77fbe1a9d44fc0c73ae5c137257e2c138d59901.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4323/HighFidelity-Beta-PR11589-d255b36236fadfd2a955ebea87becc6b1dfd74d3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4323/HighFidelity-Beta-PR11589-d255b36236fadfd2a955ebea87becc6b1dfd74d3.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4333/HighFidelity-Beta-PR11589-6607be5b5804cba930543d0e6cfc73169996c501.exe

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4346/HighFidelity-Beta-PR11589-6607be5b5804cba930543d0e6cfc73169996c501.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4346/HighFidelity-Beta-PR11589-6607be5b5804cba930543d0e6cfc73169996c501.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4357/HighFidelity-Beta-PR11589-f90060afab28ec6f5327d2099dacb7a896f80f73.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4357/HighFidelity-Beta-PR11589-f90060afab28ec6f5327d2099dacb7a896f80f73.exe

**Comment by RyanDowne** [comment]
the golden path has been tested with the latest version and it all works. DO NOT MERGE anything else into this branch until after the demo is done without checking with Ryan

**Comment by RyanDowne** [comment]
bitmoji

**Pull request merged**
