### PR TITLE
stop drawing ignored avatars, even if PAL is still open

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- see plan in https://github.com/highfidelity/hifi/pull/11731

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4645/HighFidelity-Beta-PR11733-e77b9e0e97786015e39989155ff5f11f77a14f7f.dmg

**Comment by Nex-Pro** [comment]
Awaiting win build for Test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4645/HighFidelity-Beta-PR11733-e77b9e0e97786015e39989155ff5f11f77a14f7f.exe

**Comment by Nex-Pro** [comment]
Testing win10

**Comment by Nex-Pro** [comment]
### PASS

**Comment by Nex-Pro** [comment]
get a frenemy to log into the same domain as you
open the PEOPLE window
ignore your frenemy
make sure you can no longer hear them talk or see their avatar. **SUCCESS**
you should still see a dot showing where they are. **SUCCESS**
you should still see their audio-level meter move. **SUCCESS**
close the PEOPLE window
you should no longer be aware of them at all. **SUCCESS**
open the PEOPLE window
unignore them
make sure you can now see and hear them. **SUCCESS**

**Pull request merged**
