### PR TITLE
VIVE can now auto-detect hmd and desktop modes

### PR DESCRIPTION
**Pull request by amantley**
This pr addresses case https://highfidelity.manuscript.com/f/cases/20245 where users head is disturbing when taking off the headset in hmd mode.

### Test Plan.
1) Start Interface and put on the VIVE headset.  You should automatically go to VR mode.  Go to 3rd person view and verify that IK works as normal in head and hands.
2) Take off the headset and you should switch to desktop mode automatically.  Verify that animations play as normal on the avatar.
3) Calibrate pucks for head, feet with controllers for hands. The VIVE HMD is attached but not used for tracking. When the calibration succeeds you should see that the avatar head moves as you would expect.
4) Disconnect the VIVE and connect the Oculus Rift and verify that auto switching between HMD mode and desktop takes places as normal.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16075/HighFidelity-Beta-PR14620-bc78ebe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16075/HighFidelity-Beta-PR14620-bc78ebe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16075/HighFidelity-Beta-Interface-PR14620-bc78ebe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16075/HighFidelity-Beta-PR14620-bc78ebe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16075/HighFidelity-Beta-Interface-PR14620-bc78ebe.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Testing Paused


???
--
On startup if the pucks are enabled, they can be injected in place of the controllers. There seems to be nothing to validate whether the tracker is actually a puck or a controller.

This strange attachment is also found in Master, so it does not come from this PR, however it blocks the calibration of devices outside of "Desktop Mode". 
pucks instead of controllers

Head Puck will not work unless "use in Desktop Mode" is active, this disables the tracking of the 
headset making observation not possible without assistance.

1- Pass- Head and hand IK work as expected when they do not have a puck injected into their feed.
2- Pass- Switching effect happens properly.
3- Pass- Pucks track in "Use in Desktop mode" with the headset plugged in.
4- Not tested yet.

Note:  This will probably be hated by livestreamers who do stunts with their headset. Or they will tape over the sensor so it cannot activate.

**Comment by qlimguicheteau** [comment]
Resumed testing

**Comment by qlimguicheteau** [comment]
FAIL
--

4. FAIL -- Oculus must be restarted every time the headset falls across to Desktop mode. The recent problematic Oculus "update" has caused strain on the transition, it seems.
-Controllers become fully paralyzed whenever the Headset is tracking, headset completely blacks out, but desktop view shows that it is still responding.
-When in desktop mode, the headset no longer tracks but the controllers re-awaken and allow control of the avatar. No hand tracking (as it is desktop mode).

I am unsure if this is a Hifi-able to fix situation, or if it is just the ruined Oculus drivers that were released recently. The environment is not sterile enough on this end to tell.

**Comment by amantley** [comment]
@qlimguicheteau 
Hi I made a mistake including the oculus testing in the test plan.  This code doesn't touch the oculus behavior at all.  
Could you test with master to verify that the oculus bug pre-dates this pr?
If so we need to write a separate bug up for the oculus bug.

**Comment by qlimguicheteau** [comment]
The Oculus bug is on its OS level, so I can't determine if any of the issue comes from HiFi or not.

**Comment by qlimguicheteau** [comment]
PASS
--
Changed due to Oculus will need fixing regardless, wasn't needed, and all of the other points clearly passed their tests.

**Comment by hyperlogic** [comment]
@qlimguicheteau With regard to the issue you've discovered with the pucks taking the place of the controllers.  This is a known issue with SteamVR.  Recently, they've added the ability to "Manage Vive Trackers" if you right click on the green tracker icon in SteamVR you will be presented with the following screen:
manage-trackers
You can use this screen to change "Select Role:" to Disabled.  Then the vive tracker can be used with High Fidelity.

**Pull request merged**
