### PR TITLE
Added items to the developer menu for debugging physics

### PR DESCRIPTION
**Pull request by hyperlogic**
Hooked up Bullet's internal debug draw functionality to our client.
Under the Developer > Physics Menu there are five new items:

  * Show Bullet Collision - will draw all collision shapes in wireframe. WARNING: can be slow on large scenes.
  * Show Bullet Bounding Boxes - will draw axis aligned bounding boxes around all physics shapes.
  * Show Bullet Contact Points - will draw all contact points where two or more objects are colliding.
  * Show Bullet Constraints - will render wire frame axes for each constraint connecting bodies together.
  * Show Bullet Constraint Limits - will render the joint limits for each constraint.

### CODE REVIEW

**Comment by hyperlogic** [comment]
QA test plan:
* Go to Eschatology
* Try out each menu item.
* View the connected blue chain, when testing the Show Bullet Constraints menu item.
* NOTE: Show Bullet Collision Limits does nothing at the moment, because there are no set of constraints in that domain.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9013/HighFidelity-Beta-PR12960-9b037d00fa5f3307010324f49e4cf6e5eb2a42fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9013/HighFidelity-Beta-Interface-PR12960-9b037d00fa5f3307010324f49e4cf6e5eb2a42fe.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9041/app_12960_PR_ca94a2b31b84cec41f4fcc82bd3621341bcc2387.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9041/HighFidelity-Beta-PR12960-ca94a2b31b84cec41f4fcc82bd3621341bcc2387.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9041/HighFidelity-Beta-Interface-PR12960-ca94a2b31b84cec41f4fcc82bd3621341bcc2387.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9061/app_12960_PR_9535597df24b1dd33fffef25d649e2d63e0c81ee.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9061/HighFidelity-Beta-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9061/HighFidelity-Beta-Interface-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.dmg

**Comment by hyperlogic** [comment]
build this please

**Comment by hyperlogic** [comment]
Mysterious windows build failure, build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9126/HighFidelity-Beta-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9126/HighFidelity-Beta-Interface-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9126/HighFidelity-Beta-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9126/HighFidelity-Beta-Interface-PR12960-9535597df24b1dd33fffef25d649e2d63e0c81ee.exe

**Comment by hyperlogic** [comment]
This is only testable after #12986 has been merged. PENDING

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9421/app_12960_PR_4fa9af5534b483b7b53a794e9d0c36ea723c3a4f.apk

**Comment by hyperlogic** [comment]
QA Test plan:
  * enter a mostly empty domain.
  * run the script/developer/tests/dynamics/dynamicsTests.js app.
  * Use the bottom button to rez a ragdoll.  NOTE: the ragdoll has a short lifetime so you may have to re-rez it during the test.
  * Select the Developer > Physics > Show Bullet Collision menu item.
  * Verify that you see the following:
ragdoll-with-show-collision

  * Deselect Developer >Physics > Show Bullet Collision
  * Verify that the lines disappear.
  * Select Developer > Physics > Show Bullet Bounding Boxes.
  * Verify that you see the following:
ragdoll-with-show-bounding-boxes

  * Deselect Developer > Physics > Show Bullet Bounding Boxes.
  * Verify that the lines disappear.
  * Select Developer > Physics > Show Bullet Contact Points.
  * Verify that you see the following:  Note: the x's underneath the ragdoll's feet.
ragdoll-with-show-contact-points

   * Deselect Developer > Physics > Show Bullet Contact Points.
   * Verify that the lines disappear.
   * Select Developer > Physics > Show Bullet Constraints
   * Verify that you see the following:
ragdoll-with-show-constraints

   * Deselect Developer > Physics > Show Bullet Constraints
   * Verify that the lines disappear.
   * Select Developer > Physics > Show Bullet Constraint Limits
   * Verify that you see the following:
ragdoll-with-show-constraint-limits

   * Deselect Developer > Physics > Show Bullet Constraint Limits
   * Verify that the lines disappear.

**Comment by hyperlogic** [comment]
windows build failure, build this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9434/HighFidelity-Beta-PR12960-4fa9af5534b483b7b53a794e9d0c36ea723c3a4f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9434/HighFidelity-Beta-Interface-PR12960-4fa9af5534b483b7b53a794e9d0c36ea723c3a4f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9434/HighFidelity-Beta-PR12960-4fa9af5534b483b7b53a794e9d0c36ea723c3a4f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9434/HighFidelity-Beta-Interface-PR12960-4fa9af5534b483b7b53a794e9d0c36ea723c3a4f.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Lines appear and disappear when selected.

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/14736/Add-support-for-rendering-Bullet-s-internal-Debug-Draw-Interface

**Pull request merged**
