### PR TITLE
CR for 20287 - Don't show the application menu bar when in full screen 

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by problem** [comment]
Thanks @ctrlaltdavid, will wait on auto build and test.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 032896f75c69f0bb9b1aa1f4f537034996e94036 available at: https://gist.github.com/6e3c1abc6f7af4573196<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4390.dmg

**Comment by problem** [comment]
@nbq can you test this on Windows when you get a chance?

**Comment by problem** [comment]
Working as expected on Windows 8.1

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2df3eed31ee5d12c787295c5bd472c3f4f623aae available at: https://gist.github.com/6e3c1abc6f7af4573196<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4390.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4390.dmg

**Pull request merged**
