### PR TITLE
Build Test

### PR DESCRIPTION
**Pull request by upennzhang**
hifi Client Build Test Proof

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2980/HighFidelity-Beta-PR11262-c90794fd27a8cf3c353f758f5875f52df6b171e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2980/HighFidelity-Beta-PR11262-c90794fd27a8cf3c353f758f5875f52df6b171e6.exe

**Pull request closed without merging**
