### PR TITLE
DOC-115: Comfort mode JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Adds JSDoc for the new comfort mode HMD API properties.

Case: https://highfidelity.atlassian.net/browse/DOC-115

Note: No executable code changes.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Wait for https://github.com/highfidelity/hifi/pull/15533 to be merged. This PR adds the new comfort mode HMD API properties.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20380/HighFidelity-Beta-PR15926-8a82ea5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20380/HighFidelity-Beta-Interface-PR15926-8a82ea5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20380/HighFidelity-Beta-PR15926-8a82ea5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20380/HighFidelity-Quest-Beta-PR15926-8a82ea5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20380/HighFidelity-Beta-PR15926-8a82ea5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20380/HighFidelity-Beta-Interface-PR15926-8a82ea5.exe

**Pull request merged**
