### PR TITLE
handle camera-relative controller joints for other avatars

### PR DESCRIPTION
**Pull request by sethalves**
- handle camera-relative controller joints for other avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4217/HighFidelity-Beta-PR11614-aaf3c24a44ba8aad0149f0fd540ac46b103b0571.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4217/HighFidelity-Beta-PR11614-aaf3c24a44ba8aad0149f0fd540ac46b103b0571.exe

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/8001/Build-7208-When-held-non-dynamic-entities-appear-attached-to-your-hip-to-observers

**Comment by sethalves** [comment]
## Test Plan

Setup: Enter the 'Trendy Shop' in hifi://dev-content. You should not require rez permissions to spawn clones of the wearable entities on the shelves. Note that wearables have pre-defined joints that are supported and will not attach to all avatars if the specified joint is missing from the skeleton - e.g. a skeleton without HeadTop_End will not be able to wear hats. Requires hand controllers. Suggest testing against the default wooden avatar to reduce likelihood of running into joint issues while testing.

* Grab an item off of the shelf in the Trendy Shop. Confirm that a clone is created.
* Stand in front of the mirror and confirm that it turns on and you can see your avatar
* Attaching: Move the cloned item close to the area of the body where it should be worn - e.g a hat on top of the head, backpack on spine, skirt on hips
    * Confirm that you are able to do these steps without rez or rez-temp permissions
    * Confirm that a slight haptic pulse plays on the controller that is holding the object
    * Confirm that an audible "ping" plays
    * Confirm that the object is now attached to your avatar, and moves where you move
* Attaching on hands: Confirm that you are only able to attach items to your right or left arm when you are not holding the entity in that same hand
* Adjusting: Using your hand controllers, modify the rotation, position, and scale of your wearable
    * Scaling is done by squeezing the grips (not triggers) on hand controllers and moving them apart.
    * Steps 2 and 3 should be able to be performed in either order - that is, you can adjust before or while your entity is attached to you
    * Confirm that a second person is able to adjust your wearable
* Removing: Using your hand controllers, grab a wearable that has been attached and pull it away from your avatar
    * Confirm that at about arm's length away:
        * An audible "ping" plays
        * A slight haptic pulse plays on the controller that is holding the object
        * The wearable is no longer attached and does not move with the avatar
    * Confirm that a second user can remove your wearable by pulling it far away
* Cleanup: After step #4, confirm that after 60 seconds of not re-attaching the object, it is deleted
* Recycling: Confirm that after step #4, another avatar is able to pick up and use the object if they grab it before 60 seconds

**Pull request merged**
