### PR TITLE
Blocks app accommodates updated Blocks website

### PR DESCRIPTION
**Pull request by elisa-lj11**
## Test Plan

1. Load blocksApp.js from here: https://hifi-content.s3.amazonaws.com/elisalj/blocks/blocksApp.js
2. Open Blocks app
3. Blocks tablet button should turn white and icon should turn black
4. Choose one of the featured models listed by clicking on it
5. Click the "Download" button: model should appear in front of you
6. Click the upper left menu icon
7. Click "Sign in", then sign in (User: hifi.blocks, Password: downloadz4dayz)
8. Click on the menu icon again, and click "Your Published Items"
9. Click on "purple block"
10. Click on "Download"; a purple block should appear in front of you
11. Click on the Blocks tablet button; tablet should disappear and button should return to black background/white icon

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2812/HighFidelity-Beta-PR11251-4c40e3bdf4dc90213cb151a06eeb47ae1e3b2989.dmg

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2818/HighFidelity-Beta-PR11251-4c40e3bdf4dc90213cb151a06eeb47ae1e3b2989.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2819/HighFidelity-Beta-PR11251-4c40e3bdf4dc90213cb151a06eeb47ae1e3b2989.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2819/HighFidelity-Beta-PR11251-4c40e3bdf4dc90213cb151a06eeb47ae1e3b2989.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Load blocksApp.js from here: https://hifi-content.s3.amazonaws.com/elisalj/blocks/blocksApp.js **Pass**
Open Blocks app **Pass**
Blocks tablet button should turn white and icon should turn black **Pass**
Choose one of the featured models listed by clicking on it **Pass**
Click the "Download" button: model should appear in front of you **Pass**
Click the upper left menu icon **Pass**
Click "Sign in", then sign in (User: hifi.blocks, Password: downloadz4dayz) **Pass**
Click on the menu icon again, and click "Your Published Items" **Pass**
Click on "purple block" **Pass**
Click on "Download"; a purple block should appear in front of you **Pass**
Click on the Blocks tablet button; tablet should disappear and button should return to black background/white icon **Pass**

**Notes: Not sure if PR specific but when moving tablet quickly back and forward, it would show the underlaying texture of the "Private Tablet" screen, sort of clipping through.**

**Pull request merged**
