### PR TITLE
BUGZ-814: DNM/WIP: Draft of Updating the graphics setting dialog

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20268/HighFidelity-Beta-PR15895-9fbfde8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20268/HighFidelity-Beta-Interface-PR15895-9fbfde8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20268/HighFidelity-Beta-PR15895-9fbfde8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20268/HighFidelity-Beta-Interface-PR15895-9fbfde8.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20268/HighFidelity-Beta-PR15895-9fbfde8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20268/HighFidelity-Quest-Beta-PR15895-9fbfde8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20326/HighFidelity-Beta-PR15895-644f753.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20326/HighFidelity-Beta-Interface-PR15895-644f753.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20326/HighFidelity-Beta-PR15895-644f753.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20326/HighFidelity-Quest-Beta-PR15895-644f753.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20326/HighFidelity-Beta-PR15895-644f753.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20326/HighFidelity-Beta-Interface-PR15895-644f753.exe

**Comment by zfox23** [comment]
I am closing this in favor of #15918

**Pull request closed without merging**
