### PR TITLE
send ignoring avatar removal to ignored avatar

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

You will need two avatars for this test. You will need to connect to the sandbox from this PR.

From Interface client A, ignore the avatar from Interface client B. Confirm that neither of the avatars are able to each other. Without this fix, client B continues to see client A in a frozen position.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12545/HighFidelity-Beta-PR13916-07b24b4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12545/HighFidelity-Beta-PR13916-07b24b4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12545/HighFidelity-Beta-Interface-PR13916-07b24b4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12545/HighFidelity-Beta-PR13916-07b24b4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12545/HighFidelity-Beta-Interface-PR13916-07b24b4.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12616/HighFidelity-Beta-PR13916-07b24b4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12616/HighFidelity-Beta-PR13916-07b24b4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12616/HighFidelity-Beta-Interface-PR13916-07b24b4.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Fail @conklin94122 

Pass- standard ignore no longer leaves afterimage.
Fail- Admin viewpoint leaves afterimage if PAL is closed.

The Admin state of the PAL menu reveals everyone who are ignored. If they are invisible to the Admin's standard view, the Admin PAL will leave an afterimage of the ignored user when the PAL closes.
This is regardless of if the Admin, or Other user triggered the ignore.

[UserA_hifi-log.txt](https://github.com/highfidelity/hifi/files/2350187/UserA_hifi-log.txt)
[Server_Logs.zip](https://github.com/highfidelity/hifi/files/2350188/Server_Logs.zip)
[UserB_hifi-log.txt](https://github.com/highfidelity/hifi/files/2350191/UserB_hifi-log.txt)

**Comment by howard-stearns** [comment]
In terms of the fogbugz ticket, that fail part would be a fail for resolving the ticket. See https://highfidelity.fogbugz.com/f/cases/12330/When-a-user-has-been-ignored-via-the-PAL-Ignore-Option-they-can-still-see-the-user-that-ignored-them#BugEvent.74957  So one option would be to take another run at solving the whole shebang.

However, since this is already such an improvement, I have no objection to merging as is, if someone creates a separate ticket (referencing the first) for the admin case.

Up to you, @birarda

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12741/HighFidelity-Beta-PR13916-a908c15.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12741/HighFidelity-Beta-PR13916-a908c15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12741/HighFidelity-Beta-Interface-PR13916-a908c15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12741/HighFidelity-Beta-PR13916-a908c15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12741/HighFidelity-Beta-Interface-PR13916-a908c15.exe

**Comment by birarda** [comment]
I agree that the issue that occurs if the PAL is open should be viewed separately - marking this as QA pass.

**Pull request merged**
