### PR TITLE
Re-adding removed toggleSpaceMode function

### PR DESCRIPTION
**Pull request by wayne-chen**
There was an uncaught exception in scripts/system/edit.js called `selectionDisplay.toggleSpaceMode()` but is not defined anymore in the tip of master.  I caught this while looking at the log window fixing some other ticket.  I'm re-adding this function so that this exception will not occur.

### CODE REVIEW

**Comment by wayne-chen** [comment]
To test:

- Get tip of master on highfidelity/hifi
- Launch Interface
- Enable Settings->Developer Menu
- Open Developer->Log
- See UncaughtException in defaultScripts.js for `toggleSpaceMode`

- In fixed build 
    - Get tip of master on highfidelity/hifi
    - Launch Interface
    - Enable Settings->Developer Menu
    - Open Developer->Log
    - UncaughtException in defaultScripts.js for `toggleSpaceMode` disappears

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10085/HighFidelity-Beta-PR13231-3d0e0da42f0b3f9af1956a13bfaf4347d8a99a6d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10085/HighFidelity-Beta-PR13231-3d0e0da42f0b3f9af1956a13bfaf4347d8a99a6d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10085/HighFidelity-Beta-Interface-PR13231-3d0e0da42f0b3f9af1956a13bfaf4347d8a99a6d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10085/HighFidelity-Beta-PR13231-3d0e0da42f0b3f9af1956a13bfaf4347d8a99a6d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10085/HighFidelity-Beta-Interface-PR13231-3d0e0da42f0b3f9af1956a13bfaf4347d8a99a6d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10098/HighFidelity-Beta-PR13231-b86d74b4b74358170d72e6be74f7286df9801970.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10098/HighFidelity-Beta-PR13231-b86d74b4b74358170d72e6be74f7286df9801970.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10098/HighFidelity-Beta-Interface-PR13231-b86d74b4b74358170d72e6be74f7286df9801970.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10112/HighFidelity-Beta-PR13231-534341ef62f72c60c6b50c934f32fec3737ab370.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10112/HighFidelity-Beta-PR13231-534341ef62f72c60c6b50c934f32fec3737ab370.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10112/HighFidelity-Beta-Interface-PR13231-534341ef62f72c60c6b50c934f32fec3737ab370.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10112/HighFidelity-Beta-PR13231-534341ef62f72c60c6b50c934f32fec3737ab370.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10112/HighFidelity-Beta-Interface-PR13231-534341ef62f72c60c6b50c934f32fec3737ab370.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10121/HighFidelity-Beta-PR13231-ef756f7041a8efdd26273c810becddfbb2915ceb.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10122/HighFidelity-Beta-PR13231-b2f3131262d4f3f1922b7a9bc7d5b4da33a9ae11.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10122/HighFidelity-Beta-PR13231-b2f3131262d4f3f1922b7a9bc7d5b4da33a9ae11.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10122/HighFidelity-Beta-Interface-PR13231-b2f3131262d4f3f1922b7a9bc7d5b4da33a9ae11.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10122/HighFidelity-Beta-PR13231-b2f3131262d4f3f1922b7a9bc7d5b4da33a9ae11.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10122/HighFidelity-Beta-Interface-PR13231-b2f3131262d4f3f1922b7a9bc7d5b4da33a9ae11.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10134/HighFidelity-Beta-PR13231-67d24408cf83e0895e328fcf04a620cfe80b6bc6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10134/HighFidelity-Beta-PR13231-67d24408cf83e0895e328fcf04a620cfe80b6bc6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10134/HighFidelity-Beta-Interface-PR13231-67d24408cf83e0895e328fcf04a620cfe80b6bc6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10134/HighFidelity-Beta-PR13231-67d24408cf83e0895e328fcf04a620cfe80b6bc6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10134/HighFidelity-Beta-Interface-PR13231-67d24408cf83e0895e328fcf04a620cfe80b6bc6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10150/HighFidelity-Beta-PR13231-35755369cd269011fba46a61b2e06c4e231b8f46.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10150/HighFidelity-Beta-PR13231-35755369cd269011fba46a61b2e06c4e231b8f46.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10150/HighFidelity-Beta-Interface-PR13231-35755369cd269011fba46a61b2e06c4e231b8f46.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10150/HighFidelity-Beta-PR13231-35755369cd269011fba46a61b2e06c4e231b8f46.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10150/HighFidelity-Beta-Interface-PR13231-35755369cd269011fba46a61b2e06c4e231b8f46.exe

**Comment by wayne-chen** [comment]
re-creating PR for this as this branch is unstable.

**Pull request closed without merging**
