### PR TITLE
Update Oculus SDK

### PR DESCRIPTION
**Pull request by jherico**
## Testing notes

Must be tested on Windows with an Oculus HMD using the Oculus display plugin.  Preferably with both DK2 and CV1, as well as testing with Touch controllers.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0482039cbec33c5d60b871e4acebe889839c3d00 available at: https://gist.github.com/f09de75be113439fdd52b57fa206fc4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8618-0482039.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8618-0482039.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
Had high hopes this would fix issue I've been seeing with DK2 since last, I believe it was, Thursday's Oculus software update.

My setup is - Oculus DK2 with its motion tracking sensor - Windows 10 - xbox controller and not other peripherals.  If I have Oculus attached to my computer Interface loses control of my arms regardless of being in Desktop or HMD mode as shown below;

hifi-snap-by-omegaheron-on-2016-09-19_14-09-29

I also tested with being of light AV and same thing.

**Comment by OmegaHeron** [comment]
And when switched to HMD it adds additional arm crazies - I'm also used to how AV moves from HMD tracking input - it seems very different since last update in that I can make lateral head movements that have a far greater level of input down the AV than I recall prior to Oculus update - I mean - like if I move head left/right laterally the AV's hips seem to get a **lot** more input than prior.  This is probably (or not) why it's good to listen to music that makes you chair dance a bit while testing.

hifi-snap-by-omegaheron-on-2016-09-19_14-11-45

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49a91e3a0417f6a47aaaa18a40c95b5e6f3bca10 available at: https://gist.github.com/f09de75be113439fdd52b57fa206fc4a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8618-49a91e3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8618-49a91e3.dmg

**Pull request merged**
