### PR TITLE
cleanup EncodeBitstreamParams to use nodeData when possible

### PR DESCRIPTION
**Pull request by birarda**
- cleaned up parameter passing with EncodeBitstreamParams
- removed unused SVO models file saving/reading

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Rigorously test the entity server. You should not see any change in behaviour while interacting with entities in your domain (adding/deleting/manipulating).

This PR removes an old now-untouched code path for entity tree storage in binary format. Ensure that the persistence and loading of the stored entity tree on your filesystem work as expected for the entity server in this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53e6a77fcc613cfde2042686b646338f1db587f4 available at: https://gist.github.com/946fc7514da3efa2a59181efebe10148<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10001-53e6a77.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10001-53e6a77.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass for everything I can think of...  If there's anything to test I didn't catch @birarda , please advise.

Test 1 - Loading of default sandbox content with verified no cached data so all has to load via ATP:  Pass
Test 2 - ATP Browsing:  Pass
Test 3 - ATP Upload no "folder" prefix:  Pass
Test 4 - ATP Browser Select model and place in scene:  Pass
Test 5 - ATP Browser Rename model:  Pass
Test 6 - ATP Browser Delete asset: Pass
Test 7 - ATP Upload with folder prefix:  Pass
Test 8 - ATP Browser Select model and place in scene (asset in folder):  Pass
Test 9 - ATP Browser Rename model (asset in folder):  Pass
Test 10 - ATP Browser Delete asset (asset in folder): Pass

Also tested having multiple assets in a folder and deleting only 1 asset of X, insuring others remained.  Pass

For glorious future work -- I noticed something in trying to think of all permutation to test... you can't rename a folder (or for create an "empty" one).  Both have been complained about in forums a time or two, just mentioning in case it's something that can be added for future devel.

**Comment by birarda** [comment]
@OmegaHeron I could have been clearer in my test plan, but these changes touch the Entity Server and not the Asset Server. It looks like you did a fairly rigorous test of the Asset Server.

**Comment by OmegaHeron** [comment]
@birarda - my fault, facepalms! Welcome to my first day back after a week off + Monday.

That said - ES seems to pass as well as I exercised placing, moving, resizing and deleting models via my ATP testing.  I'll give it another go over, but, I suspect it's still a pass.  Apologies again for testing that which did not need testing.

**Comment by OmegaHeron** [comment]
Exercised everything I could think of with entities - added, removed, edited, checked persistence across server restarts, changed params related to dynamic, physics shapes, adding script for entity (local and server), removing script for entity, creating linked entity set...  all worked as expected -- I feel like I might not have thought of everything.

**Pull request merged**
