### PR TITLE
add scripted/qml debug UI for render LOD

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* faster LOD auto adjust response
* new script for debugging LOD autoadjust: `developer/utilities/render/lod.js`

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6244/app_12157_PR.apk

**Comment by AndrewMeadows** [comment]
**Test Plan:**

**(1)** Login to a domain that has plenty of objects: enough to impact frame rate such that the rendering LOD-auto-adjust logic needs to reduce the number of visible objects.  Avatar Island may work well

**(2)** From the **Running Scripts..." widget run the following script:

**developer --> utilities --> render --> lod.js**

That should load a new icon into the "Tablet" system.

**(3)** Click on the new button.
--> a new widget should appear with some moving graphs:

The top graph shows three measured times for various parts of the render pipeline.

The middle graph shows the theoretical max possible frame rate given the three times above (in white) and a high green line (fps threshold where LOD is relaxed) ad a low red line (fps threshold where LOD limits are applied.

The bottom graph shows a numerical representation of the LOD (in blue) in the range between 1.0 = max automatic LOD visible, and 0.0 = minimum automatic LOD.

**(4)** Turn your view to alternatively look at lots of objects and few objects: the LOD autoadjust should kick in and it should be evident on the the graphs when it does.  In particular, the when the white line in the middle graph hits the green or red thresholds the blue LOD line at the bottom should move (if it isn't already pegged at one of its limits).

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6254/app_12157_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6254/HighFidelity-Beta-PR12157-b1fddbc10add581452376c168e287a09a457005f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6254/HighFidelity-Beta-PR12157-b1fddbc10add581452376c168e287a09a457005f.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
I can't seem to continue as all domains don't seem to be compatible?

I need some assistance before I can continue.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
I was unable to test due to protocol mismatch error on all but sandbox domain

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6409/app_12157_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6409/HighFidelity-Beta-PR12157-2c43138e1493483c163b61214e475c4b622aa0b2.dmg

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6417/app_12157_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6417/HighFidelity-Beta-PR12157-2c43138e1493483c163b61214e475c4b622aa0b2.dmg

**Comment by AndrewMeadows** [comment]
The windows build appears to be failing for issues unrelated to C++ compile errors or warnings.  Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6419/app_12157_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6419/HighFidelity-Beta-PR12157-2c43138e1493483c163b61214e475c4b622aa0b2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6419/HighFidelity-Beta-PR12157-2c43138e1493483c163b61214e475c4b622aa0b2.dmg

**Comment by samcake** [comment]
@sbennett77 Ready for QA again, thanks

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Pass. 

@conklin94122

**Pull request merged**
