### PR TITLE
Fix skeleton switching bug

### PR DESCRIPTION
**Pull request by SamGondelman**
This should fix the "you sometimes look wonky to other people after switching to an avatar with a different skeleton" bug, as well as a crash that occurred very rarely if, after switching your avatar, you happened to immediately send a full avatar packet.

### CODE REVIEW

**Comment by SamGondelman** [comment]
Testing:

- start up a server, making sure that you're using the version of Sandbox from this PR
- have someone else who is also running this build come to your domain
- both of you switch between avatars many many times.  I found that going from Simple Robot -> Will was a good repro case for the bug, but try lots of other avatars with weird skeletons.
- you should both look normal to the other person.  Let me know if you ever look weird for a second but then snap back to normal, but the main fix here is that you shouldn't get stuck in crazy poses.
- test other ways of modifying joints, like hand controllers and animations.  The other person should still see you appear normally.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7d602986cdd9688172cc739901096aa5ed4febe9 available at: https://gist.github.com/2697fbe02e9b41998521ada538ba22e6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8095.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8095.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: caf4a9fa34f0a52b9f4e89293f1106af248f1bb7 available at: https://gist.github.com/2697fbe02e9b41998521ada538ba22e6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8095.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8095.dmg

**Comment by thoys** [comment]
## QA Test report

Tested with @Nex-Pro , we've gone through different avatars, also Will and the Robot. This fixes the behavior that we've encountered before. Also tested using the Vive, and the animations still display accurate.

QA Pass :+1:

**Comment by thoys** [comment]
P.s. We didn't look weird for a second after switching. Couldn't reproduce this.

**Pull request merged**
