### PR TITLE
fix progress bar / stats reference to pending transfer count

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug with progress and render stats reading pending texture transfer count

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

On master, load a domain with a cold cache. Make sure you are running `defaultScripts.js` so that you are running `progress.js` Notice that once you have 0 active/pending downloads and 0 active/pending processing your progress bar should still be visible. It will not go away unless you switch domains.

On this PR, load a domain with a cold cache. You should see the progress bar go away once downloads are complete.

**Comment by CainFoool** [comment]
Will test.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/217/HighFidelity-Beta-PR10564-6c2758e4eaa0d063b45fc96eb865394c9d65d4ac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/217/HighFidelity-Beta-PR10564-6c2758e4eaa0d063b45fc96eb865394c9d65d4ac.dmg

**Comment by CainFoool** [comment]
# Test Passed 

The progress bar at the bottom disappears when the pending/active downloads has finished and set to 0.

**Pull request merged**
