### PR TITLE
Choose avatar and set display name

### PR DESCRIPTION
**Pull request by gcalero**
This PR adds a screen in Android that allows

1. Set the user's name to display
2. Choose the avatar to use in a list of 7 preselected avatars

*Test plan*
1. Test navigation in general for the new screen (Menu > Option *Avatar*)
2. If you've set a display name previously it has to be restored when you go back to this new screen
3. Users connected to the same domain than you should be able to see your display name
4. After loading, users should be able to see the selected avatar

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16649/HighFidelity-Beta-PR14757-fd185f2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16649/HighFidelity-Beta-PR14757-fd185f2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16649/HighFidelity-Beta-Interface-PR14757-fd185f2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16649/HighFidelity-Beta-PR14757-fd185f2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16649/HighFidelity-Beta-Interface-PR14757-fd185f2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16653/HighFidelity-Beta-PR14757-618b27c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16653/HighFidelity-Beta-Interface-PR14757-618b27c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16653/HighFidelity-Beta-PR14757-618b27c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16653/HighFidelity-Beta-Interface-PR14757-618b27c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16716/HighFidelity-Beta-PR14757-68feea2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16716/HighFidelity-Beta-PR14757-68feea2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16716/HighFidelity-Beta-Interface-PR14757-68feea2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16716/HighFidelity-Beta-PR14757-68feea2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16716/HighFidelity-Beta-Interface-PR14757-68feea2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16722/HighFidelity-Beta-PR14757-4a345a5.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16722/HighFidelity-Beta-PR14757-4a345a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16722/HighFidelity-Beta-Interface-PR14757-4a345a5.exe

**Comment by gcalero** [comment]
build this please

**Comment by amerhifi** [comment]
two errors when trying to display avatar list:
2019-01-25 10:11:22.887 13044-13044/io.highfidelity.hifiinterface E/Interface: Failed retrieving avatar JSON
   java.io.FileNotFoundException: avatars.json
       at android.content.res.AssetManager.openAsset(Native Method)
       at android.content.res.AssetManager.open(AssetManager.java:388)
       at android.content.res.AssetManager.open(AssetManager.java:362)
       at io.highfidelity.hifiinterface.provider.AvatarProvider.loadJSONFromAssets(AvatarProvider.java:62)
       at io.highfidelity.hifiinterface.provider.AvatarProvider.retrieve(AvatarProvider.java:40)
       at io.highfidelity.hifiinterface.view.AvatarAdapter.loadAvatars(AvatarAdapter.java:60)
       at io.highfidelity.hifiinterface.fragment.ProfileFragment.onCreateView(ProfileFragment.java:64)
       at android.app.Fragment.performCreateView(Fragment.java:2611)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1276)
       at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2421)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2154)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2055)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
is the json file missing?
second error:
2019-01-25 10:14:21.958 13044-13044/io.highfidelity.hifiinterface E/ActivityThread: Performing stop of activity that is already stopped: {io.highfidelity.hifiinterface/io.highfidelity.hifiinterface.InterfaceActivity}
   java.lang.RuntimeException: Performing stop of activity that is already stopped: {io.highfidelity.hifiinterface/io.highfidelity.hifiinterface.InterfaceActivity}
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4200)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4288)
       at android.app.ActivityThread.-wrap25(Unknown Source:0)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2019-01-25 10:14:21.958 13044-13044/io.highfidelity.hifiinterface E/ActivityThread: ActivityClientRecord{paused=true, stopped=true, hideForNow=false, startsNotResumed=false, isForward=true, pendingConfigChanges=0, onlyLocalRequest=false, preserveWindow=false, Activity{resumed=false, stopped=true, finished=false, destroyed=false, startedActivity=false, temporaryPause=false, changingConfigurations=false, visibleBehind=false}

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16748/HighFidelity-Beta-PR14757-4a345a5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16748/HighFidelity-Beta-PR14757-4a345a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16748/HighFidelity-Beta-Interface-PR14757-4a345a5.dmg

**Comment by amerhifi** [comment]
missing json fixed but Avatar title stays on domains after selecting an Avatar.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16748/HighFidelity-Beta-PR14757-4a345a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16748/HighFidelity-Beta-Interface-PR14757-4a345a5.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16749/HighFidelity-Beta-PR14757-3a3bd59.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16749/HighFidelity-Beta-PR14757-3a3bd59.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16749/HighFidelity-Beta-Interface-PR14757-3a3bd59.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16749/HighFidelity-Beta-PR14757-3a3bd59.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16749/HighFidelity-Beta-Interface-PR14757-3a3bd59.exe

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
Build this please

**Comment by JeffClinton** [comment]
Not seeing any domains due to protocol change, so I'm kicking off a rebuild.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16810/HighFidelity-Beta-PR14757-3a3bd59.apk

**Comment by JeffClinton** [comment]
Stopped testing until the PR gets back on the protocol.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16810/HighFidelity-Beta-PR14757-3a3bd59.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16810/HighFidelity-Beta-Interface-PR14757-3a3bd59.dmg

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16810/HighFidelity-Beta-PR14757-3a3bd59.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16810/HighFidelity-Beta-Interface-PR14757-3a3bd59.exe

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16816/HighFidelity-Beta-PR14757-3a3bd59.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16816/HighFidelity-Beta-Interface-PR14757-3a3bd59.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16816/HighFidelity-Beta-PR14757-3a3bd59.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16816/HighFidelity-Beta-Interface-PR14757-3a3bd59.exe

**Comment by gcalero** [comment]
build this please

**Comment by gcalero** [comment]
build this please

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16847/HighFidelity-Beta-PR14757-1d1ae90.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16847/HighFidelity-Beta-PR14757-1d1ae90.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16847/HighFidelity-Beta-Interface-PR14757-1d1ae90.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16854/HighFidelity-Beta-PR14757-1d1ae90.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16854/HighFidelity-Beta-PR14757-1d1ae90.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16854/HighFidelity-Beta-Interface-PR14757-1d1ae90.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16854/HighFidelity-Beta-PR14757-1d1ae90.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16854/HighFidelity-Beta-Interface-PR14757-1d1ae90.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
