### PR TITLE
Snapshot dialog into tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing

The snapshot dialog opens:
- In the tablet if the tablet is being used (both in desktop and HMD modes).
- In a window if the tablet is not being used (both in desktop and HMD modes).

The windowed dialog works the same as previously, with the following exceptions:
- If you select "don't share" the dialog closes whereas it didn't previously.

The tablet dialog works the same as the windowed dialog.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a3dea030e0f7a2e6710e020aedd7126da6a1361 available at: https://gist.github.com/14dfbbfcbd92dbcbaf981fd619da0858<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10029-6a3dea0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10029-6a3dea0.dmg

**Comment by Nex-Pro** [comment]
Checking this.

**Comment by Nex-Pro** [comment]
## PASS


Testing

The snapshot dialog opens:

TABLET MODE:

DESKTOP: **SUCCESS**
HMD:**SUCCESS**


HUD MODE:

DESKTOP: **SUCCESS**
HMD:**SUCCESS**


In a window if the tablet is not being used (both in desktop and HMD modes).

The windowed dialog works the same as previously, with the following exceptions:

If you select "don't share" the dialog closes whereas it didn't previously: **SUCCESS**


The tablet dialog works the same as the windowed dialog:**SUCCESS**


***Note:  Selecting 'don't share' closes tablet.***

**Pull request merged**
