### PR TITLE
MS14615: Prevent memory overuse when minimized

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14615](https://highfidelity.manuscript.com/f/cases/14615).

### CODE REVIEW

**Comment by zfox23** [comment]
### Test Plan
1. Start Interface and Task Manager. Connect to localhost _without a sandbox running_ (so that your environment doesn't contain any other game objectsc). Ensure Interface is not minimized.
2. Note Interface's memory usage in Task Manager.
3. Minimize Interface. Verify that Interface's memory usage does not increase over time.
4. Wait 60 seconds. Verify that Interface doesn't crash.
5. Maximize Interface. Verify that Interface's memory usage does not drastically change, and verify that Interface is still usable.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10266/HighFidelity-Beta-PR13272-259803f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10266/HighFidelity-Beta-PR13272-259803f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10266/HighFidelity-Beta-Interface-PR13272-259803f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10266/HighFidelity-Beta-PR13272-259803f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10266/HighFidelity-Beta-Interface-PR13272-259803f.exe

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10414/HighFidelity-Beta-PR13272-259803f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10414/HighFidelity-Beta-PR13272-259803f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10414/HighFidelity-Beta-Interface-PR13272-259803f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10414/HighFidelity-Beta-PR13272-259803f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10414/HighFidelity-Beta-Interface-PR13272-259803f.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Memory usage did not increase while minimized.

**Pull request merged**
