### PR TITLE
Fix Controller.getActions(), .getHardware(), and .getStandard()

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8572/app_12813_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8572/HighFidelity-Beta-PR12813-8d25a745f0f942662bfde4894cc76374b926619d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8572/HighFidelity-Beta-PR12813-8d25a745f0f942662bfde4894cc76374b926619d.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 

In each pair, the two items were identical, none returned as 'undefined'.

**Comment by conklin94122** [comment]
Seth ok'd merge via Slack.

**Pull request merged**
