### PR TITLE
Increase max heartbeat time to 10 sec on mac

### PR DESCRIPTION
**Pull request by davidkelly**
Of course this fixes nothing.  But it helps _just for now_ with not getting a bunch of crash bugs where we chase our tails and discover it is this.  As we dial in the mac (and windows) performance doubtless we can move this back down to 2 soon.

https://highfidelity.manuscript.com/f/cases/22395/

### CODE REVIEW

**Comment by davidkelly** [comment]
please build this

**Comment by davidkelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19155/HighFidelity-Beta-PR15496-02b960d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19155/HighFidelity-Quest-Beta-PR15496-02b960d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19155/HighFidelity-Beta-PR15496-02b960d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19155/HighFidelity-Beta-Interface-PR15496-02b960d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19155/HighFidelity-Beta-PR15496-02b960d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19155/HighFidelity-Beta-Interface-PR15496-02b960d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19173/HighFidelity-Beta-PR15496-0b2d11a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19173/HighFidelity-Beta-Interface-PR15496-0b2d11a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19173/HighFidelity-Beta-PR15496-0b2d11a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19173/HighFidelity-Beta-Interface-PR15496-0b2d11a.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19173/HighFidelity-Beta-PR15496-0b2d11a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19173/HighFidelity-Quest-Beta-PR15496-0b2d11a.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19239/HighFidelity-Beta-PR15496-0b2d11a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19239/HighFidelity-Quest-Beta-PR15496-0b2d11a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19239/HighFidelity-Beta-PR15496-0b2d11a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19239/HighFidelity-Beta-Interface-PR15496-0b2d11a.exe

**Pull request merged**
