### PR TITLE
Re-host crashpad archive

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8615/app_12829_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8615/HighFidelity-Beta-PR12829-4af2cd6cfdd014f7e256dbeaffaeb88265cf88d3.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8633/HighFidelity-Beta-PR12829-4af2cd6cfdd014f7e256dbeaffaeb88265cf88d3.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8644/app_12829_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8644/HighFidelity-Beta-PR12829-15ec7641a829aaf079fe61dd508560375abd6c92.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8663/app_12829_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8663/HighFidelity-Beta-PR12829-15ec7641a829aaf079fe61dd508560375abd6c92.dmg

**Pull request closed without merging**
