### PR TITLE
Add performance commands

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
A number of Script commands have been added, to facilitate performance tests.  These commands return various aspects of the computer system and may be useful for other purposes, such as verifying that minimum requirements are met and providing more information in bug reports.

In addition - the commands are used by auto-tester to generate a test matrix in the `test.md` files associated with each relevant test.

# Details
The following commands are provided in the `Window` class:

1. `isWindows64()`
2. `isMacOS()`
3. `isLinux()`
4. `isAndroid()`
5. `hasRift()` - actually looks for the Oculus Touch controller
6. `hasVive()` - actually looks for the HTC Vive controller
7. `isI5()` - verifies that the number of logical cores is 4
8. `isI7()` - verifies that the number of logical cores is 8
9. `isNvidia()`
10. `isAMD()`
11. `int physicalMemoryGB()`

# Testing
Each command can be run as `Window.<command name>();` in the Java Script console (CTRL ALT J).  The tests should be run as per the following list:

1-4 on Windows, Mac and Linux, and on Android, if possible
5-6 should be run on Windows, with a Vive, a Rift, and neither
7-8 should be run on both I5 and I7 PCs, any OS.
9-10 should be run with any NVidia and AMD graphics cards, on any OS
11 should be run on Windows, MacOS and Linux, with both 8 GB and 16 GB of memory (e.g. - Windows with 16GB, MacOS with 8 GB and Linux with 8 GB.  Full coverage is not required.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8991/HighFidelity-Beta-PR12955-ddff99fe389f537eea925453f105c3508cd9e84f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8991/HighFidelity-Beta-Interface-PR12955-ddff99fe389f537eea925453f105c3508cd9e84f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8995/app_12955_PR_f3407b496e3d71ebafa68477201ecce809040f0a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8995/HighFidelity-Beta-PR12955-f3407b496e3d71ebafa68477201ecce809040f0a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8995/HighFidelity-Beta-Interface-PR12955-f3407b496e3d71ebafa68477201ecce809040f0a.exe

**Comment by samcake** [comment]
let s close this please

**Pull request closed without merging**
