### PR TITLE
Revert "Pack all non-instanced traits"

### PR DESCRIPTION
**Pull request by hyperlogic**
This reverts commit 5b7d7b88331e0d5607cb6676b52b5056d7846cca.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17235/HighFidelity-Beta-PR14908-eee41bc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17235/HighFidelity-Beta-PR14908-eee41bc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17235/HighFidelity-Beta-Interface-PR14908-eee41bc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17235/HighFidelity-Beta-PR14908-eee41bc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17235/HighFidelity-Beta-Interface-PR14908-eee41bc.exe

**Comment by hyperlogic** [comment]
https://highfidelity.manuscript.com/f/cases/21133/Avatar-eyes-are-popping-strangely-for-other-avatars

**Pull request merged**
