### PR TITLE
keyboard address some feedback

### PR DESCRIPTION
**Pull request by danteruiz**
Address some of the keyboard feedback and fixing some bugs

- https://highfidelity.manuscript.com/f/cases/19812/3D-keyboard-A-keyboard-will-spawn-and-remain-in-the-serverless-domain-if-you-immediately-exit-HMD-after-clean-install

- https://highfidelity.manuscript.com/f/cases/19850/3D-keyboard-typing-sound-is-too-loud

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15179/HighFidelity-Beta-PR14409-bd263cc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15179/HighFidelity-Beta-Interface-PR14409-bd263cc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15179/HighFidelity-Beta-PR14409-bd263cc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15179/HighFidelity-Beta-Interface-PR14409-bd263cc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15203/HighFidelity-Beta-PR14409-680a502.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15203/HighFidelity-Beta-PR14409-680a502.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15203/HighFidelity-Beta-Interface-PR14409-680a502.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15229/HighFidelity-Beta-PR14409-a77121a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15229/HighFidelity-Beta-PR14409-a77121a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15238/HighFidelity-Beta-PR14409-a77121a.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15238/HighFidelity-Beta-PR14409-a77121a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15238/HighFidelity-Beta-Interface-PR14409-a77121a.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15246/HighFidelity-Beta-PR14409-a77121a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15246/HighFidelity-Beta-Interface-PR14409-a77121a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15246/HighFidelity-Beta-PR14409-a77121a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15246/HighFidelity-Beta-Interface-PR14409-a77121a.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Keyboard disappeared when switching to desktop mode
Backspace and enter have been moved as described
New drumsticks are easier to distinguish from the keys behind them
New key press sound is nice and quiet

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15276/HighFidelity-Beta-PR14409-a77121a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15276/HighFidelity-Beta-PR14409-a77121a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15276/HighFidelity-Beta-Interface-PR14409-a77121a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15276/HighFidelity-Beta-PR14409-a77121a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15276/HighFidelity-Beta-Interface-PR14409-a77121a.exe

**Pull request merged**
