### PR TITLE
[WIP] Dance application prototyping

### PR DESCRIPTION
**Pull request by ElderOrb**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7730/app_12563_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7730/HighFidelity-Beta-PR12563-8ecaeeeacfbb4ee68b362e8811b765ad2200a271.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7730/HighFidelity-Beta-PR12563-8ecaeeeacfbb4ee68b362e8811b765ad2200a271.exe

**Comment by changxc** [comment]
pending design assets

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9151/app_12563_PR_b2c39e6b5323f70ae007b2f70aa90d141484878f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9151/HighFidelity-Beta-PR12563-b2c39e6b5323f70ae007b2f70aa90d141484878f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9151/HighFidelity-Beta-Interface-PR12563-b2c39e6b5323f70ae007b2f70aa90d141484878f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9151/HighFidelity-Beta-PR12563-b2c39e6b5323f70ae007b2f70aa90d141484878f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9151/HighFidelity-Beta-Interface-PR12563-b2c39e6b5323f70ae007b2f70aa90d141484878f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14026/HighFidelity-Beta-PR12563-5241cdc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14026/HighFidelity-Beta-Interface-PR12563-5241cdc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14026/HighFidelity-Beta-PR12563-5241cdc.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14026/HighFidelity-Beta-Interface-PR12563-5241cdc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14054/HighFidelity-Beta-PR12563-5241cdc.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14054/HighFidelity-Beta-PR12563-5241cdc.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14054/HighFidelity-Beta-Interface-PR12563-5241cdc.dmg

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
