### PR TITLE
Share a single GLCanvas for all the QMLSurfaces

### PR DESCRIPTION
**Pull request by samcake**
In order to avoid allocating a GLContext  for every OffscreenQMLSurfaces created (every time there is a new WebENtity) we tried to share the OffscreenGLCanvas among the QMLSurfaces.

SO far so good, couldn't find a crash or any glitches in  my test.

I tried this in the quest for a particular crash that happens when running Interface for a while in a domain with potentially a lot of Web entities being created and destroyed.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 299cb91760b6d0e7f7388d22b3957701e3d658ff available at: https://gist.github.com/1aa1de0c7c38f3a1d8d921b6d19f0047<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-299cb91.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-299cb91.dmg

**Comment by samcake** [comment]
Test Plan:
Make sure that UI and web entities are rendering correcly 
Performance shoudn't be degraadded.
THe goal of this PR is to avoid allocating more resource for each web entities. THis means that the GPU memory allocation observed from an external tool (PRocess Explorer) should stay stable or at the minimum consumes less than with Master.
WOrking on rpoviding a tool script to stress it

**Comment by hifi-gustavo** [comment]
Build console output for commit: d77912e056ab06910ecac4a320769e2f3acce9f5 available at: https://gist.github.com/1aa1de0c7c38f3a1d8d921b6d19f0047<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-d77912e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-d77912e.dmg

**Comment by jherico** [comment]
The backend code for QML expects that a single QSGContext corresponds to a single QOpenGLContext.  This will violate that expectation.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1d8f0910164a4bb4c8337ee98ccd2276e17e21f9 available at: https://gist.github.com/720ba47210e60fce65fcfcba93a7ea47<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-1d8f091.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-1d8f091.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e3023a5c1629058a49a89ba69baf732c6a06aa60 available at: https://gist.github.com/1aa1de0c7c38f3a1d8d921b6d19f0047<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-e3023a5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9072-e3023a5.dmg

**Pull request closed without merging**
