### PR TITLE
Typo in tablet avatar preference qml file

### PR DESCRIPTION
**Pull request by annabrewer**
No Jira bug, but I corrected a typo in one of the qml files.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19844/HighFidelity-Beta-PR15709-9d7b4ca.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19844/HighFidelity-Beta-Interface-PR15709-9d7b4ca.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19844/HighFidelity-Beta-PR15709-9d7b4ca.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19844/HighFidelity-Quest-Beta-PR15709-9d7b4ca.apk)

**Comment by annabrewer** [comment]
Closing, will fix issue where commits aren't connected to my GH account

**Pull request closed without merging**
