### PR TITLE
BUGZ-1161: Report count of dropped packets in Socket::checkForReadyReadBackup()

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Jira: https://highfidelity.atlassian.net/browse/BUGZ-1161

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20798/HighFidelity-Beta-PR16044-77740f1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20798/HighFidelity-Beta-Interface-PR16044-77740f1.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20798/HighFidelity-Beta-PR16044-77740f1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20798/HighFidelity-Quest-Beta-PR16044-77740f1.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20798/HighFidelity-Beta-PR16044-77740f1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20798/HighFidelity-Beta-Interface-PR16044-77740f1.exe

**Comment by SimonWalton-HiFi** [comment]
I think the signal stack hack is currently Windows-only, so wouldn't help in this case. I could include it anyway.

**Comment by howard-stearns** [comment]
good point

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20813/HighFidelity-Beta-PR16044-dbc2a67.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20813/HighFidelity-Beta-Interface-PR16044-dbc2a67.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20813/HighFidelity-Beta-PR16044-dbc2a67.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20813/HighFidelity-Quest-Beta-PR16044-dbc2a67.apk)

**Comment by SimonWalton-HiFi** [comment]
I enabled the event-queue size reach-around on Linux and it compiled ok.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20817/HighFidelity-Beta-PR16044-4de720a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20817/HighFidelity-Beta-Interface-PR16044-4de720a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20817/HighFidelity-Beta-PR16044-4de720a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20817/HighFidelity-Quest-Beta-PR16044-4de720a.apk)

**Comment by SimonWalton-HiFi** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20819/HighFidelity-Beta-PR16044-4de720a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20819/HighFidelity-Beta-Interface-PR16044-4de720a.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20819/HighFidelity-Beta-PR16044-4de720a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20819/HighFidelity-Quest-Beta-PR16044-4de720a.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20819/HighFidelity-Beta-PR16044-4de720a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20819/HighFidelity-Beta-Interface-PR16044-4de720a.dmg

**Pull request merged**
