### PR TITLE
FB15569 - Debug default scripts no longer on developer menu (for RC68)

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/15569/Debug-default-scripts-no-longer-on-developer-menu

*** Test plan ***

Ensure 'Developer' menu has menu item 'Debug defaultScripts.js'

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10388/HighFidelity-Beta-PR13316-9b91f7b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10388/HighFidelity-Beta-PR13316-9b91f7b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10388/HighFidelity-Beta-Interface-PR13316-9b91f7b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10388/HighFidelity-Beta-PR13316-9b91f7b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10388/HighFidelity-Beta-Interface-PR13316-9b91f7b.exe

**Comment by qligmaloney** [comment]
Currently testing

**Pull request merged**
