### PR TITLE
Enabled AEC by default (bug 19210)

### PR DESCRIPTION
**Pull request by gcalero**
https://highfidelity.manuscript.com/f/cases/19210/

This PR turns on AEC by default for all build types (debug, release). Debug builds will still be able to access the setting through **Menu > Settings > AEC.**

Acoustic Echo Cancellation is a feature present in some android phones like Google Pixel 2, Samsung S8, Samsung S9. Other devices like Huawei Mate 9 Pro don't support it.

AEC must be disabled when a headset is plugged in (1)

**UPDATE**: it also mute the microphone when entering a domain

Test plan
Check that AEC setting is enabled by default (on devices that support it)
Check audio quality with regards to master
Try starting HighFidelity app in both condition: plugged and unplugged headset
Switch AEC setting and check that the right input device is used each time
Plug/unplug the headset and check that that the right input device is used each time
Check that echo cancelation is enabled (2)
Check that AEC option only appears in debug builds (not in release ones)
When user enters a domain the mic is muted by default
**(1)** You can check input device switching in logcat, simply filter by "[hifi.audioclient] switchInputToAudioDevice". voicerecognition is an opensl es preset that uses the audio input with minimum or no processing (without AEC). voicecommunication is a preset that uses AEC and, if supported, noise reduction too.
**(2)** Echo cancelation performance depends on the device implementation. It may cancel echo at max volume or not. In all cases you can appreciate a difference between AEC enabled and disabled (voicecommunication and voicerecognition).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14268/HighFidelity-Beta-PR14252-5a8a5bb.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14268/HighFidelity-Beta-PR14252-5a8a5bb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14268/HighFidelity-Beta-Interface-PR14252-5a8a5bb.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14709/HighFidelity-Beta-PR14252-58c135a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14709/HighFidelity-Beta-PR14252-58c135a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14709/HighFidelity-Beta-Interface-PR14252-58c135a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14709/HighFidelity-Beta-PR14252-58c135a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14709/HighFidelity-Beta-Interface-PR14252-58c135a.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14714/HighFidelity-Beta-PR14252-db45ace.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14714/HighFidelity-Beta-Interface-PR14252-db45ace.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14730/HighFidelity-Beta-PR14252-611881e.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14730/HighFidelity-Beta-PR14252-611881e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14730/HighFidelity-Beta-Interface-PR14252-611881e.dmg

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15033/HighFidelity-Beta-PR14252-611881e.apk

**Comment by qlimnavarro** [comment]
Currently Testing Pre-Merge Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15033/HighFidelity-Beta-PR14252-611881e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15033/HighFidelity-Beta-Interface-PR14252-611881e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15033/HighFidelity-Beta-PR14252-611881e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15033/HighFidelity-Beta-Interface-PR14252-611881e.exe

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Option is enabled by default

**Pull request merged**
