### PR TITLE
Hotfix, avatars disappear on quick reconnect

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8983/app_12953_PR_9cf133cff216c710cb71c9a0411ce098c199766c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8983/HighFidelity-Beta-PR12953-9cf133cff216c710cb71c9a0411ce098c199766c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8983/HighFidelity-Beta-Interface-PR12953-9cf133cff216c710cb71c9a0411ce098c199766c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8983/HighFidelity-Beta-PR12953-9cf133cff216c710cb71c9a0411ce098c199766c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8983/HighFidelity-Beta-Interface-PR12953-9cf133cff216c710cb71c9a0411ce098c199766c.exe

**Comment by huffman** [comment]
You will need at least 2 users to test. 
  * Connect to your sandbox with 2 users
  * Ensure that you can both see each other
    * Have one user leave and come back. Ensure that you can both see each other.
  * Ensure that you can create and move entities around, and both users see the changes
  * Run through Avatar Mixer test suite on your sandbox: https://highfidelity.testrail.net/index.php?/suites/view/499

**Comment by ZappoMan** [comment]
Note: AFAICT -- this is a protocol change... and will have the side effect that we will force people to upgrade. We need to be aware of that as we consider if we want to include this in a hot fix or not.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Avatar Mixer tests pass, and protocol mismatch error appears as expected.

**Pull request merged**
