### PR TITLE
HOTFIX 63.3

### PR DESCRIPTION
**Pull request by ZappoMan**
Includes fixes for:
- spectator camera preview not working
- LOD not recovering on HMDs after LOD downshift

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6992/app_12353_PR.apk

**Comment by ZappoMan** [comment]
TEST PLAN
**LOD:**
    - In an heavy scene, once LOD has decreased to the minimum, it should increase again as soon as the fps reach 10HZ above the minimum FPS picked from
    - The behavior of the LOD manager can be monitored using the app "LOD.js" located in scripts/developer/utilities/render

**Spectator Camera:**

- Run Spectator Camera test plan (526) - confirm that view on viewfinder matches the display on screen with pixel perfection (not cropped).
- Check the render utilities.
- Confirm that raising/lowering keyboard on tablet functions properly in both desktop / hmd mode.
- Test the webTablet script, notifications, that they work properly in both desktop / hmd mode.
- Run Create Mode test plan (1938) - confirm pages look correct in desktop / hmd mode.
- Use the attached script to confirm the correct Interface window dimensions are reported.

[testWindowDimensions.zip](https://github.com/highfidelity/hifi/files/1701194/testWindowDimensions.zip)

**Comment by RyanDowne** [comment]
bitmoji

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6992/HighFidelity-Beta-PR12353-0b6dea3d10e85916be82e207cbe380e418e9b64b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6992/HighFidelity-Beta-PR12353-0b6dea3d10e85916be82e207cbe380e418e9b64b.exe

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6997/app_12353_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6997/HighFidelity-Beta-PR12353-0b6dea3d10e85916be82e207cbe380e418e9b64b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6997/HighFidelity-Beta-PR12353-0b6dea3d10e85916be82e207cbe380e418e9b64b.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7002/app_12353_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7002/HighFidelity-Beta-PR12353-5e02d67d8cd78059ce5b1801690a7d497c08ec07.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7002/HighFidelity-Beta-PR12353-5e02d67d8cd78059ce5b1801690a7d497c08ec07.exe

**Comment by Qliemillar** [comment]
Testing complete, solid pass @conklin94122

**Pull request merged**
