### PR TITLE
DEV-2217: Fix MyAvatar::isInAir() so takes into account the new seated state

### PR DESCRIPTION
**Pull request by luiscuenca**
https://highfidelity.atlassian.net/browse/DEV-2217

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21668/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21668/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21671/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21671/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21671/HighFidelity-Beta-PR16283-e0d0ec5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21671/HighFidelity-Beta-Interface-PR16283-e0d0ec5.exe

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21678/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21678/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21680/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21680/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21680/HighFidelity-Beta-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21680/HighFidelity-Beta-Interface-PR16283-e0d0ec5.dmg

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21693/HighFidelity-Beta-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21693/HighFidelity-Beta-Interface-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21693/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21693/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by luiscuenca** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21705/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21705/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21705/HighFidelity-Beta-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21705/HighFidelity-Beta-Interface-PR16283-e0d0ec5.dmg

**Comment by luiscuenca** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21724/HighFidelity-Beta-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21724/HighFidelity-Beta-Interface-PR16283-e0d0ec5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21724/HighFidelity-Beta-PR16283-e0d0ec5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21724/HighFidelity-Quest-Beta-PR16283-e0d0ec5.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21724/HighFidelity-Beta-PR16283-e0d0ec5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21724/HighFidelity-Beta-Interface-PR16283-e0d0ec5.exe

**Pull request merged**
