### PR TITLE
fix enableHighlightList  and disableHihglightList function for Selection API

### PR DESCRIPTION
**Pull request by druiz17**
- fix enableHighlightList  and disableHihglightList function for Selection API

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- run the debugHighlight.js script under develeper > utilities > render
- open the app
- click on the `Highlight Hovered`
- When you move you mouse over entities, they should highlight.
- Stop running the scripts and any highlight entities should not longer be highlighted.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8597/app_12823_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8597/HighFidelity-Beta-PR12823-00713ab2250ab18c167485fbd437e582e37a95a3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8597/HighFidelity-Beta-PR12823-00713ab2250ab18c167485fbd437e582e37a95a3.exe

**Comment by samcake** [comment]
THanks Dante!

**Comment by samcake** [comment]
Tested and QA pass

**Pull request merged**
