### PR TITLE
Additional cleanup of audio noise gate

### PR DESCRIPTION
**Pull request by kencooke**
Code cleanup to eliminate clang warnings on the Mac build. The functionality is unchanged.

### Test Plan
Using the Mac build of Interface, verify that audio "Noise Reduction" works as expected.
There should be no audio distortion, whether Noise Reduction is enabled or disabled.

The action of the noise gate can be seen on the level meter.  After talking loudly, when the mic audio becomes quiet again, the meter should fade from low level to zero, and the packet type (shown in Developer/Stats) should become all Silent packets.

image

### CODE REVIEW

**Comment by Nex-Pro** [comment]
awaiting windows build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3943/HighFidelity-Beta-PR11538-4f193663495d2852d994b6801257f8ea4dcfc7cc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3943/HighFidelity-Beta-PR11538-4f193663495d2852d994b6801257f8ea4dcfc7cc.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4000/HighFidelity-Beta-PR11538-b026a0461d77ee3f58b870dcac0ebc8e2ce02082.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4000/HighFidelity-Beta-PR11538-b026a0461d77ee3f58b870dcac0ebc8e2ce02082.exe

**Comment by conklin94122** [comment]
I'll test this tomorrow, sorry for the delay.

**Comment by AndrewMeadows** [comment]
The compile warnings falsely being identified as new in the ubuntu build have been fixed in hifi/master so you can merge or rebase this PR to solve that problem.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4033/HighFidelity-Beta-PR11538-22f38f296534097252048088d21511910611c61d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4033/HighFidelity-Beta-PR11538-22f38f296534097252048088d21511910611c61d.exe

**Pull request merged**
