### PR TITLE
Fix entities with registration points rendering in the wrong place

### PR DESCRIPTION
**Pull request by SamGondelman**
[FB8038](https://highfidelity.fogbugz.com/f/cases/8038/Entities-with-non-center-registration-display-in-wrong-position)

The calculation for getTransformToCenter() included scale, but not dimensions.  Also: web and text entities were using the opposite of the registration point for one calculation.

Test plan:
- With every type of entity: modify their registration point using edit.  The entity should properly update to follow its bounding boxes (as shown by the edit outline).  Resize the entity.  They should still be in the right place.
- Make sure web/text entities are properly selectable with edit after you change the registration point.

### CODE REVIEW

**Comment by Nex-Pro** [comment]
will test when built

**Comment by Nex-Pro** [comment]
@SamGondelman I'm familiar with this issue, I discussed this with CtrlAltDavid

**Comment by Nex-Pro** [comment]
Awaiting updated build. Will use updated test plan.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3865/HighFidelity-Beta-PR11517-fc6e5df2cbb52a105a9b8118126a9148fdadf145.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3865/HighFidelity-Beta-PR11517-fc6e5df2cbb52a105a9b8118126a9148fdadf145.exe

**Comment by Nex-Pro** [comment]
T E S T I N G  this

**Comment by Nex-Pro** [comment]
### PASS

**Comment by sethalves** [comment]
is this a fix for https://highfidelity.fogbugz.com/f/cases/8038/Entities-with-non-center-registration-display-in-wrong-position ?

**Comment by SamGondelman** [comment]
@sethalves yeah

**Pull request merged**
