### PR TITLE
Beta Release 63 - includes up to Developer Release 7741

### PR DESCRIPTION
**Pull request by conklin94122**
- New Commerce feature: If you’ve set up your wallet and have positive HFC balance, you can now send HFC to an existing connection (people you have shaken hands before), or somebody nearby (people near you in the same domain) (Doc)
- New app called Emote lets you choose various responses to emote. (Doc)
- Log filters now available (Doc)
- Changes in Zone entity properties now include inherited properties and an on and off feature. (Doc)
- Fixed issue where grabbable objects stop colliding with avatars after being near grabbed, far grabbed, or clicked with the mouse
- Fixed an issue where downloaded tablet apps get sorted above the default apps
- Fixed an issue when the avatar is in 3rd person and it glitches
- Fixed issue of the asset browser window not appearing in HMD
- Fixed issue where the avatars head would look odd to others when going in and out of HMD
- Expanded MIDI support to include sending channel, velocity, status, and note data and other related MIDI helper functions. Currently Windows only.
- Improvement in the avatar's appearance when they twist their wrists or raise their arms
- Make zones, lights and particles not grabbable by default in edit.js
- Bug fix on snapshot social sharing
- Adding spacial audio cue upon rezzing purchased items
- Fixed bubble icon activation bug and limited bubble audio play rate
- Fixed bubble icon activation bug and limited bubble audio play rate
- updated preview disabled image in the case of privacy protection
- Updated gold Proof of Provenance image

**Known Issue**

Those with an i5 + AMD system are experiencing crashes with this build. We know about it and are working on a fix. Sorry for the inconvenience! We'll let you know when an update is available.

**New Docs**

[Send HFC to connections or someone nearby](https://docs.highfidelity.com/high-fidelity-commerce/basics/hfc/wallet-setup/send-money) (Beta Release 63)
[Emote App](https://docs.highfidelity.com/create-and-explore/explore-interface/menu/emote) (Beta Release 63)
[Logs](https://docs.highfidelity.com/build-guide/log-filters) (Beta Release 63)
[Zone Lighting Properties](https://docs.highfidelity.com/create-and-explore/entities/zone-entities/zone-properties) (Beta Release 63)
[Avatar Entities vs Attachments](https://docs.highfidelity.com/high-fidelity-commerce/avatar-wearables/entities-differences)
[Watch Synced Videos in High Fidelity](https://docs.highfidelity.com/create-and-explore/extras/syncing-services/video-syncing)
[Watch Synced Presentations in High Fidelity](https://docs.highfidelity.com/create-and-explore/extras/syncing-services/slide-syncing

**Updated Docs**

[Setting Up a Theater Domain](https://docs.highfidelity.com/create-and-explore/start-working-in-your-sandbox/setting-up-a-theater-domain)
[PoP License and Certificate](https://docs.highfidelity.com/high-fidelity-commerce/basics/pop)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6524/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6524/HighFidelity-Beta-PR12229-4697c5f92c823019e0d0cc447406f236a9e122a0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6524/HighFidelity-Beta-PR12229-4697c5f92c823019e0d0cc447406f236a9e122a0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6527/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6527/HighFidelity-Beta-PR12229-5bd0cc1a972f0744104e4d564a35a8bff40389b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6527/HighFidelity-Beta-PR12229-5bd0cc1a972f0744104e4d564a35a8bff40389b8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6536/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6579/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6579/HighFidelity-Beta-PR12229-a2f6f25f590aa970409d65c37547a74c2c71c702.dmg

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6580/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6580/HighFidelity-Beta-PR12229-a2f6f25f590aa970409d65c37547a74c2c71c702.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6580/HighFidelity-Beta-PR12229-a2f6f25f590aa970409d65c37547a74c2c71c702.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6592/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6593/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6594/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6594/HighFidelity-Beta-PR12229-e081808ace7c06aa67351b47fac11a2673208dcf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6594/HighFidelity-Beta-PR12229-e081808ace7c06aa67351b47fac11a2673208dcf.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6629/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6629/HighFidelity-Beta-PR12229-dd628a4d953bf8b59d7abfc32dd9c06be2367038.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6629/HighFidelity-Beta-PR12229-dd628a4d953bf8b59d7abfc32dd9c06be2367038.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6646/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6646/HighFidelity-Beta-PR12229-00773b4b12552a088dd858eec2b1af97f0969553.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6646/HighFidelity-Beta-PR12229-00773b4b12552a088dd858eec2b1af97f0969553.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6669/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6669/HighFidelity-Beta-PR12229-97d9fe0ea71229bb0f258a7fa557d9e40e49c53c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6669/HighFidelity-Beta-PR12229-97d9fe0ea71229bb0f258a7fa557d9e40e49c53c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6673/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6673/HighFidelity-Beta-PR12229-92b9290294010da5303bddbf83c0ac5c76a58ead.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6673/HighFidelity-Beta-PR12229-92b9290294010da5303bddbf83c0ac5c76a58ead.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6688/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6688/HighFidelity-Beta-PR12229-1220ad6b50261e5eb6ac1958cc31a742a2f51194.dmg

**Comment by conklin94122** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6695/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6696/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6698/app_12229_PR.apk

**Comment by conklin94122** [comment]
@zfox23 Maybe a coincidence, but we haven't had a successful windows build since I merged your PR. Can you take a peek, please?

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6698/HighFidelity-Beta-PR12229-dc3823374a7a697042ce936ec97d34848e45c666.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6698/HighFidelity-Beta-PR12229-dc3823374a7a697042ce936ec97d34848e45c666.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6720/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6720/HighFidelity-Beta-PR12229-0b03632437be0515310ee5c0c1be2c391eabe5a4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6720/HighFidelity-Beta-PR12229-0b03632437be0515310ee5c0c1be2c391eabe5a4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6725/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6727/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6727/HighFidelity-Beta-PR12229-215d03c4ced805fe79c10e7127ca28e24fbe7a43.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6727/HighFidelity-Beta-PR12229-215d03c4ced805fe79c10e7127ca28e24fbe7a43.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6730/app_12229_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6730/HighFidelity-Beta-PR12229-215d03c4ced805fe79c10e7127ca28e24fbe7a43.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6730/HighFidelity-Beta-PR12229-215d03c4ced805fe79c10e7127ca28e24fbe7a43.dmg

**Pull request merged**
