### PR TITLE
Avoid DS heartbeats with non-metaverse domain ID

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug with domain-server sending heartbeats for non-metaverse domains

### CODE REVIEW

**Comment by birarda** [comment]
This is a fix for https://highfidelity.fogbugz.com/f/cases/1373/new-temporary-domain-from-PR8362-failed-to-enable-auto-networking.

There was a race in domain-server startup that could cause the domain-server to request a new temporary name and not update its ice server information for the new temporary name. This made some Sandbox installs unreachable.

#### Test Plan

1. Run Sandbox off of master with no previous domain settings. This will require a clear of `%APPDATA%/High Fidelity/domain-server/config.json`. In the log of the domain-server, you should see `[WARNING] Domain not found, getting a new temporary domain.`.
2. Run Sandbox off of this PR. You should not see that message in the log on first run (do not copy settings from production).
3. Confirm that the temporary domain from your PR install is reachable from an Interface client inside and outside your network by the temporary name (you can click Share in the Sandbox menu to get a copiable link).
4. Ping me so I can confirm we are getting heartbeats for your temporary domain.
5. Connect your High Fidelity account and a place name to the PR domain. Confirm that the domain is reachable via the place name from inside and outside your network.
6. Ping me so I can confirm we are getting heartbeats for your domain.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f3e30221f0553fe33ed772d06c0a95e0274edf30 available at: https://gist.github.com/9db1bda5903df8c0684d353b5a06df7f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8363-f3e3022.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8363-f3e3022.dmg

**Comment by ZappoMan** [comment]
what is a "non-metaverse domain"?

**Comment by birarda** [comment]
A non-metaverse domain is a domain with a randomly generated UUID that does not correspond to a Domain or TemporaryDomain in our API. This occurs if you start a domain-server with no ID in settings without asking it to get a temporary name.

**Comment by nbq** [comment]
I will test this one

**Comment by zzmp** [comment]
Confirmed the heartbeat was being set in the db

**Pull request merged**
