### PR TITLE
don't save joint information for avatar entities in avatarbookmarks.json

### PR DESCRIPTION
**Pull request by danteruiz**
This PR makes sure that joints rotations and translations information is not saved for avatar entities that get saved ion the avatarbookmark.

Ticket - https://highfidelity.manuscript.com/f/cases/19618/Soft-attachments-on-Avatar-s-contain-too-much-data

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- open avatar app
- select an avatar
- apply a soft entity - https://hifi-content.s3.amazonaws.com/jimi/avatar/photo-real/Clothes/TShirt.fbx
- save avatar as favorite.
- now open up the avatarbookmarks.json in the text editor and make sure that the new avatar entry entities do not contain this data
```
 "jointRotations": [
                    ],
                    "jointRotationsSet": [
                    ],
                    "jointTranslations": [
                    ],
                    "jointTranslationsSet": [
                    ],
```

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15484/HighFidelity-Beta-PR14488-8be775c.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15484/HighFidelity-Beta-PR14488-8be775c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15484/HighFidelity-Beta-Interface-PR14488-8be775c.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
