### PR TITLE
Change default mode to My View in Android

### PR DESCRIPTION
**Pull request by gcalero**
Change default mode in android to My View, instead of Radar

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8028/app_12642_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8028/HighFidelity-Beta-PR12642-04decfa89c6a10e429f9254e3a0383735b1e110a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8028/HighFidelity-Beta-PR12642-04decfa89c6a10e429f9254e3a0383735b1e110a.exe

**Comment by SamGondelman** [comment]
Tested and works 👍

**Pull request merged**
