### PR TITLE
hook pal audio meter up again

### PR DESCRIPTION
**Pull request by sethalves**
- fix audio meter in PAL window

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- open tablet
- click on the PEOPLE button
- observe that the mic audio-level meter works

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ae163ac60bf3484032298483b80c398bdd4d206 available at: https://gist.github.com/46216c530e7b461f67a74277ec233205<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9590-4ae163a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9590-4ae163a.dmg

**Comment by nbq** [comment]
Will test this

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

* Opened tablet
* Clicked on People button
* Saw mic level worked on my end and the other Interface's voice could be see on the meter

**PASS**

**Pull request merged**
