### PR TITLE
FB11855 - Change bubble icon on tablet

### PR DESCRIPTION
**Pull request by ElderOrb**
*** Test plan *** 

Ensure new bubble icon is shown on tablet instead of old one: 

image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6718/app_12292_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6719/app_12292_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6792/app_12292_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6792/HighFidelity-Beta-PR12292-a0c41f26d1fd80131ad1a2e8bde18ccd7b2b4955.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6792/HighFidelity-Beta-PR12292-a0c41f26d1fd80131ad1a2e8bde18ccd7b2b4955.dmg

**Comment by themelissabrown** [comment]
@ElderOrb is there a test plan for this?

**Comment by ElderOrb** [comment]
This is just an images update, but sure, I'll add a few steps

**Comment by changxc** [comment]
can we get some CR and QA pls

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122

**Pull request merged**
