### PR TITLE
fix a crash in ESS on ES shutdown

### PR DESCRIPTION
**Pull request by birarda**
- fixed a crash in EntityScriptServer when EntityServer goes away

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

Put a server entity script on an entity. Kill your Entity Server using your domain web interface (http://localhost:40100). Your Entity Script Server should crash on master, but not on this PR.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f213b32167792b51cf2df7434ff2af2c337b8c94 available at: https://gist.github.com/09a5c03fa67fb0956cd82b29e704bf71<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9760-f213b32.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9760-f213b32.dmg

**Comment by nbq** [comment]
Testing this

**Comment by nbq** [comment]
Tester: Coal
System: i7 6700k, GeForce 970, Windows 10

## Build 6008

* Created Entity Cube
* Put an ESS script in the entity (a timer than ran every 5 seconds)
* Killed Entity Server using web interface.
* Noticed via Uptime that Entity Script Server crashed and restarted

## PR 9760

* Created Entity Cube and put script in it same as above
* Went to web interface and killed Entity Server
* Noticed via uptime that Entity Script Server did not crash and stayed up while the Entity Server restarted

**SUCCESS PASS**

**Pull request merged**
