### PR TITLE
Case 20833: Fix procedural skybox depth testing

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/20833/Transparent-objects-are-not-showing-up-over-procedural-skybox

Test plan:
- Create a Procedural skybox, like the day/night cycle from the marketplace.  Create an object with transparency.  The transparent object should render over the skybox.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16912/HighFidelity-Beta-PR14810-93e32f1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16912/HighFidelity-Beta-PR14810-93e32f1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16912/HighFidelity-Beta-Interface-PR14810-93e32f1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16912/HighFidelity-Beta-PR14810-93e32f1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16912/HighFidelity-Beta-Interface-PR14810-93e32f1.exe

**Comment by qliejahner** [comment]
PASS

Translucent images and models once again display in front of procedural skies.

**Pull request merged**
