### PR TITLE
RC66 - move file ~ expansion from AddressManager to DomainHandler

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8585/app_12820_PR.apk

**Comment by birarda** [comment]
#### Test Plan 

On Mac and Windows, test the following configurations. After each step before cleaning the settings file for the next test, check that the "AddressManager/address" in your settings file is `file:///~/serverless/tutorial.json`.

The settings file for this PR on Windows is `%APPDATA%/Roaming/High Fidelity - PR12820/Interface.json`. On Mac it is `~/.config/highfidelity.io/Interface.json`.

- First time launch of Interface with no Sandbox running. You should get the serverless tutorial. Quit Interface and relaunch and confirm that you end up at the serverless tutorial.
- First time launch of Interface with Sandbox running. You should get the serverless tutorial. Quit Interface and relaunch and confirm that you end up at the serverless tutorial.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8585/HighFidelity-Beta-PR12820-1ff79397356306837776acbfeb462466705087dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8585/HighFidelity-Beta-PR12820-1ff79397356306837776acbfeb462466705087dc.exe

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Testing complete - PASS @conklin94122 
Initial launch for both Windows and Mac landed in the serverless tutorial, and all subsequent launches also landed in the serverless tutorial regardless of whether or not the sandbox was installed/running. Solid pass!

**Pull request merged**
