### PR TITLE
Agent Avatars sending loudness in AvatarData

### PR DESCRIPTION
**Pull request by davidkelly**
We may want to add more AvatarData in the future, but this is sufficient for PAL to show the audio levels for agents, when isAvatar is set.  

Since this probably could effect recording, we need to hold off on this until #9714 has landed, and then figure out if this is problematic at that point.

### CODE REVIEW

**Comment by ZappoMan** [comment]
This looks like it will work for non-recorded bots, but not for ones using recordings. You need to add support in `Frame::registerFrameHandler(AUDIO_FRAME_TYPE...` around line 374 of Agent.cpp

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d7fab40530c781ffed6f6b6506352c678435033 available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-6d7fab4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-6d7fab4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 397eb89c143d2e746ca6e5ecd3980c210ea95e04 available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-397eb89.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-397eb89.dmg

**Comment by davidkelly** [comment]
We do register a frame handler for AvatarData (line 355 of Agent.cpp), so I'm assuming that is all that is necessary to support the loudness as it is part of that data.  But I know nothing about the recording interface.

**Comment by davidkelly** [comment]
Test Plan

Bring up some avatars using `crowd-agent.js` and `summon.js` in the usual fashion.  On master, you will see no VU meter movement, even though they are happily playing sounds.  In this branch, you should see the VU meters working as expected.

A second thing to test is that this works with recorded agents, but I'm not sure how to do that yet, stay tuned.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0b8624aa6ff2b5e7fc3ca4ba6a1af386016c888f available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-0b8624a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-0b8624a.dmg

**Comment by howard-stearns** [comment]
oh hell. I had too tabs open and they weren't from the same pr. revoking approval without prejudice.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2635657456a097bfc99d28eb44711f3b7a6b0797 available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-2635657.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-2635657.dmg

**Comment by davidkelly** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2635657456a097bfc99d28eb44711f3b7a6b0797 available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-2635657.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-2635657.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e8b48eb3aa1cb9ca84c75527d2987af1b7f3d7bf available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-e8b48eb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-e8b48eb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81451191c1fef266e2b78b9549b1bb855710caea available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-8145119.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-8145119.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 29f263a29668e5901865c8d60aadf772183b4026 available at: https://gist.github.com/1329186a9dd19e4b0f4a4090663807c2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-29f263a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9722-29f263a.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10
QA Pass

Compared to Master (6110) - works as advertised.  Used crowd and recorded agents scripts, noted VU movement for all types in this PR, none in master.  Smoke tests pass as well.

Will this be a packet version changer?  Noted it will connect to current stacks but without its meter displays working (obviously since it's not getting data to meter).

**Comment by ZappoMan** [comment]
This is not a protocol change just a bug fix. :)

**Pull request merged**
