### PR TITLE
Only render equip-hotspots for objects with attach points.

### PR DESCRIPTION
**Pull request by hyperlogic**
Quick bug fix to the equip-hotspot rendering.  Instead of every grabbable object lighting up with an equip-hotspot, only the ones with attach-points will.  For example: ping-pong gun, flashlight in demo.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 42068cf2dd04bb7e4f4b3e8827f4bafbb4b0c82b available at: https://gist.github.com/b4fa76aa14822acc759a09cf84bca86b<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8040.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8040.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OTcrUdOQ&#x2F;26-only-render-equip-hotspots-for-objects-with-attach-points"> Only render equip-hotspots for objects with attach points</a>

**Comment by hyperlogic** [comment]
Test plan:
 * When the Vive trigger is pressed, a green ball should appear around any objects that are "equippable"
 * Check the ping pong gun to ensure that a green ball appears around the guns handle.
 * Check the blocks in demo to ensure that a green ball does not appear around each block.

**Comment by howard-stearns** [comment]
I've tested this. Pass.

**Pull request merged**
