### PR TITLE
Add HMD and processor info to stats and launch events

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
You will need an HMD to test this.

To test:

 1. Run https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?PR8716
 1. Go into HMD mode
 1. Go out of HMD mode
 1. When you are done, report your results here, and include your machine's specific CPU model number

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5eb943c1d906017045024c899b8d9309d9694de available at: https://gist.github.com/c445eedf2e546a622412c5f73786342e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-b5eb943.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-b5eb943.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0b2def6013156cc8fdf23acbfe02df63a0f42004 available at: https://gist.github.com/c445eedf2e546a622412c5f73786342e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-0b2def6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-0b2def6.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e213a478141197aae5218d381eabbba5d52332ce available at: https://gist.github.com/c445eedf2e546a622412c5f73786342e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-e213a47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8716-e213a47.dmg

**Pull request merged**
