### PR TITLE
Preliminary da_DK translation of Interface

### PR DESCRIPTION
**Pull request by larsnaesbye**
Added a Qt Linguist .ts file for a Danish translation of Interface and translated a few words. If this kind of contribution should be made in a different way than through pull requests, please let me know :smile:

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by jherico** [comment]
ok to test

**Comment by larsnaesbye** [comment]
I suppose when we get a little further with translation efforts, we will move the .ts files to a separate folder and maybe run "lupdate" during builds :)

**Comment by cozza13** [comment]
@larsnaesbye , thank you for putting this up. If you are interested, we also sponsor work via the website www.worklist.net . Feel free to email me, chris at highfidelity if you have questions.

**Pull request merged**
