### PR TITLE
CR for Job #20628 - JS Stream Player For Domain-Zone

### PR DESCRIPTION
**Pull request by kevinmthomas-carpool**
Code Review for Job #20628 - Workitem available at https://www.worklist.net/20628

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by cozza13** [comment]
ok to test

**Comment by cozza13** [comment]
add to whitelist

**Comment by cozza13** [comment]
ok to test

**Pull request merged**
