### PR TITLE
Enable sparse textures and incremental transfer on i5

### PR DESCRIPTION
**Pull request by jherico**
## Testing

On an i5 system, clear out the `Interface.ini` file and then start this build.  Both the 'Enable Dynamic Texture Management' and 'Enable Incremental Texture Transfer' should be checked. 

Following the same procedure on the current production build will see those items unchecked.

_Bear in mind_, any value set in the INI file will supersede the defaults.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2226e5ce80657abd09bb1c2fffbc09a3326dd261 available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-2226e5c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-2226e5c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 988072a64fe2c51667850cdccea5d542f11c085f available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-988072a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-988072a.dmg

**Comment by ZappoMan** [comment]
@OmegaHeron - We'd love to get your feedback on this... does this build impact your i5 experience in a positive or negative way?

**Comment by OmegaHeron** [comment]
@ZappoMan - giving it the eval shortly.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

Desktop mode, maximized window 1600x900 - Old standard home scene used for consistency.  5 Runs 8922, red traces -- 5 Runs 5622, blue traces.

5622vs8922r5

8922 With 'Enable Dynamic Texture Management' and 'Enable Incremental Texture Transfer' confirmed on you see a dramatically longer scene load time and scene is not usable during (long) loading.  I would not want this build on my setup compared to those not using sparse/incremental tech.

**Comment by OmegaHeron** [comment]
It's also worth mentioning that this isn't so bad at dev-demo, dev-playa, dev-welcome.  It's really the old standard home scene that brings it to its knees.  Viewing hifi://o2tech in desktop mode would allow a comparison to what I'm seeing.

It was suggested that Incremental transfer is possibly what leads to long load times, and, yes disabling incremental transfers brings it back in line with current RC for cached load times, longer but not unreasonably so.  Problem is - with incremental off/dynamic on I get an unlit scene and no mouse cursor.

**Comment by jherico** [comment]
@OmegaHeron I've made some modifications to the PR.  Can you retest?  Also, when you say the scene is not usable, can you provide a little more detail?  Does the scene stutter, or is it more of an issue that the scene is slow to respond to head movement, keyboard input (but without stutter in the HMD)?

**Comment by hifi-gustavo** [comment]
Build console output for commit: 30c182550674279e2c72a4ca86ddc89fb0fd158e available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-30c1825.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-30c1825.dmg

**Comment by OmegaHeron** [comment]
@jherico 

It'll be several hours before I can get to this - primary job in the way and it's running late tonight so it may be tomorrow (East coast US) before I can get to it.  This is the test I've used since the beginning.  Using standard home scene (old) -- hifi:/o2tech has it.

Enter scene in desktop mode - soon as connection is achieved begin rotating AV until scene is fully loaded - usually indicated by zone texture visibility.  Exit Interface and repeat with scene fully in cache noting cpu load and time to complete load.

Comparing that load process with sparse/incremental enabled and disabled on i5 with GTX970 should be more than enough to illustrate how far apart in performance the two tests are and explain my reservations.

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

Latest build is improved - if I understand the trade-offs here correctly, it would seem this is a acceptable now - especially if further optimization is anticipated later.

Red Trace, this PR first try, Green Trace this PR latest code, Blue Trace last RC.  CPU Time filtered to Interface only - 2 minute runs with 5 runs each.

This PR latest code and last RC compare favorably overall for CPU use.

5585vs8958r5t2

The downside is a scene like dev-demo is very slow to compose - it's a difference of seeming to compose and be lit almost instantly to being nearly a minute.  Old standard home goes from 20-30 seconds to fully compose showing zone texture to nearer 2 minutes with this where all of scene has composed except zone texture.

**Comment by ZappoMan** [comment]
We should also compare total load time for this PR with or without incremental transfer enabled.

**Comment by ZappoMan** [comment]
This PR needs to be rebased... it has the problem of not playing well with the Steam aysnch reprojection.

**Comment by OmegaHeron** [comment]
The problem with testing without incremental transfer enabled is that is does not work.  If I have enable dynamic on, incremental off I get no visible mouse cursor and things look like;

hifi-snap-by-omegaheron-on-2016-11-01_12-13-09

Compared to following with incremental/dynamic on (or both off);

hifi-snap-by-omegaheron-on-2016-11-01_12-15-24

**Comment by ZappoMan** [comment]
The incremental transfer is what causes things to load slower. The disabling incremental transfer should not cause problems like you're reporting, so we need to fix those bugs.

**Comment by ZappoMan** [comment]
I have confirmed that texture loading appears to "stop" after about 15 seconds when you disable incremental texture loading. and/or some textures just randomly don't load. The result is as Joe describes.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0cd73d4652835761fe4e911f93fa198ff738cecd available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-0cd73d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-0cd73d4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 137b671a05bcf8e85879a110149d5a130fdc674b available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-137b671.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-137b671.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9657e77dc256c262028a612415243ce8ad9d9d25 available at: https://gist.github.com/06da2ed2e4731dbb4f66d8a84a9f7dc1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-9657e77.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8958-9657e77.dmg

**Comment by OmegaHeron** [comment]
Looking at last build shows favorable performance with Enable Dynamic Texture Management *on* and Enable Incremental Texture Transfer *off*.  I didn't run the full analysis, but, visiting a few domains showed much better load times and seemed usable.  I can run the full tests once this is finalized, if wanted.

**Comment by ZappoMan** [comment]
@OmegaHeron - yes it would be helpful...

**Comment by OmegaHeron** [comment]
After running through all permutations of Dynamic on/Incremental on or off for #8958 and #8970 I find that 8970 with dynamic on/incremental off gives best performance with i5 6500/GTX970.

All tend to give more stutter during initial scene load compared to dynamic and incremental off, but, 8970 with dynamic only loads a cached scene fastest and once loaded I had no stutter in either PR regardless of enabled options.

8958 Shows long duration erratic CPU loads as scene loads with Incremental and Dynamic on (Blue trace) While somewhat shorter "pain" window with Incremental off (Red trace).

8958comparison

8970 is more subtle - again - Red trace = dynamic on/incremental off, Blue trace = dynamic on/incremental on.  On first glance there looks to be little difference here, but, incremental increases scene load time greatly (see worksheet values) and, as in all of these, is subject to stutters during load phase.

8970comparison

**Pull request closed without merging**
