### PR TITLE
Fix invalid QML surface cache interaction

### PR DESCRIPTION
**Pull request by jherico**
Development branch version of #12667 

Refer to #12667 for testing and details.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8089/app_12666_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8095/app_12666_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8095/HighFidelity-Beta-PR12666-1dfde86680bbcb47fc51575e9fc8b8501baba6f5.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8095/HighFidelity-Beta-PR12666-1dfde86680bbcb47fc51575e9fc8b8501baba6f5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8116/app_12666_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8116/HighFidelity-Beta-PR12666-2f5928305393a6ddf16c75cb31877b959e4c18e2.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8116/HighFidelity-Beta-PR12666-2f5928305393a6ddf16c75cb31877b959e4c18e2.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
All machines produced considerably more than 2 overlays without crashing.

**Pull request merged**
