### PR TITLE
Haptic Vest-- DO NOT MERGE

### PR DESCRIPTION
**Pull request by mikeperrotta**
Do not merge

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7244/app_12418_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7244/HighFidelity-Beta-PR12418-15ebacc3142919eccbc01268f08d630357e443ec.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7244/HighFidelity-Beta-PR12418-15ebacc3142919eccbc01268f08d630357e443ec.exe

**Comment by birarda** [comment]
Closing this, we are removing the stable branch

**Pull request closed without merging**
