### PR TITLE
Fix white textures on android

### PR DESCRIPTION
**Pull request by SamGondelman**
Broken here: https://github.com/highfidelity/hifi/pull/12921

https://highfidelity.manuscript.com/f/cases/14575

Test plan:
- On Android, textures should appear.  Try a few domains.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9360/app_13066_PR_bb13bed6728114e31ba50498142fb24cc1d8d3d4.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9363/app_13066_PR_2a03e52bdcad54fad4b8324549ee271ace3bbe3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9363/HighFidelity-Beta-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9363/HighFidelity-Beta-Interface-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9363/HighFidelity-Beta-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9363/HighFidelity-Beta-Interface-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Interface Passes @conklin94122 
All basic features of the interface work as expected.

**Comment by conklin94122** [comment]
@L370 Your turn

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9563/app_13066_PR_2a03e52bdcad54fad4b8324549ee271ace3bbe3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9563/HighFidelity-Beta-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9563/HighFidelity-Beta-Interface-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9563/HighFidelity-Beta-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9563/HighFidelity-Beta-Interface-PR13066-2a03e52bdcad54fad4b8324549ee271ace3bbe3d.exe

**Comment by divyaelango88** [comment]
fails on Android. Whites textures on the woody avatar and in world

**Comment by qliacoombs** [comment]
Verified fail on Android using Samsung Galaxy S8 on Android 8.0.0 and Nexus 6P on Android 7.1.2

pr13066screenshot
@divyaelango88  @conklin94122

**Pull request closed without merging**
