### PR TITLE
make the server plugins a dependency of AC too

### PR DESCRIPTION
**Pull request by birarda**
- made server plugins a build dependency of assignment-client

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

This will need to be tested by somebody with a build environment (paging @OmegaHeron).

On master, building just the AC will not build the pcmCodec and hifiCodec plugins. On this PR, they are built as a dependency when building the AC.

**Comment by OmegaHeron** [comment]
On it @birarda

**Comment by hifi-gustavo** [comment]
Build console output for commit: b57bf956e20e92b4f2494639883c989d59c3bf4b available at: https://gist.github.com/968474649388cef0813a1f12ae271b0d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10180-b57bf95.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10180-b57bf95.dmg

**Comment by OmegaHeron** [comment]
Windows 10;
Windows = QA Pass

Ubuntu 16.04;
Linux = QA Pass

Checked out this branch, ran cmake as usual - opened SLN in VS and ran build *only* on assignment-client.

Result;
========== Build: 34 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
Looking at directory for AC I see;
assignment-client.exe and in plugins I see;
hifiCodec.dll and pcmCodec.dll

With master;
========== Build: 31 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
assignment-client.exe and *no* plugins.

Linux, Ubuntu 16.04
Normal cmake command issued
make -j8 assignment-client
PR makes AC + plugins, Master makes only AC.

**Pull request merged**
