### PR TITLE
Simplified UI: Updates! (See Description)

### PR DESCRIPTION
**Pull request by zfox23**
- Improved spacing between settings ([BUGZ-267](https://highfidelity.atlassian.net/browse/BUGZ-267))
- Improved Audio settings (fixed not seeing all I/O devices) ([BUGZ-267](https://highfidelity.atlassian.net/browse/BUGZ-267))
- Integrated Status Indicator into Top Bar ([BUGZ-266](https://highfidelity.atlassian.net/browse/BUGZ-266))
- New background color for top bar, settings app, avatar app (#000000) ([BUGZ-267](https://highfidelity.atlassian.net/browse/BUGZ-267))
- Fixed HMD icon ([BUGZ-246](https://highfidelity.atlassian.net/browse/BUGZ-246))

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19573/HighFidelity-Beta-PR15601-5749392.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19573/HighFidelity-Beta-Interface-PR15601-5749392.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19573/HighFidelity-Beta-PR15601-5749392.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19573/HighFidelity-Quest-Beta-PR15601-5749392.apk)

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19575/HighFidelity-Beta-PR15601-5749392.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19575/HighFidelity-Quest-Beta-PR15601-5749392.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19575/HighFidelity-Beta-PR15601-5749392.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19575/HighFidelity-Beta-Interface-PR15601-5749392.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19575/HighFidelity-Beta-PR15601-5749392.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19575/HighFidelity-Beta-Interface-PR15601-5749392.exe

**Pull request merged**
