### PR TITLE
ignore unbakeable textures in FBXBaker

### PR DESCRIPTION
**Pull request by birarda**
- bake FBX files even when they reference textures that cannot be baked

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4138/HighFidelity-Beta-PR11592-dabfec94367c41b183fb7a5914ea4d0d18fe2c60.dmg

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4140/HighFidelity-Beta-PR11592-dabfec94367c41b183fb7a5914ea4d0d18fe2c60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4140/HighFidelity-Beta-PR11592-dabfec94367c41b183fb7a5914ea4d0d18fe2c60.exe

**Comment by birarda** [comment]
Test plan: https://highfidelity.testrail.net/index.php?/cases/view/1805

**Comment by Nex-Pro** [comment]
### PASS See testrail.

**Comment by themelissabrown** [comment]
https://highfidelity.testrail.net/index.php?/tests/view/6277&group_by=cases:section_id&group_order=asc&group_id=366

**Pull request merged**
