### PR TITLE
Case 21595: Oculus SDK Update

### PR DESCRIPTION
**Pull request by jherico**
[21595](https://highfidelity.manuscript.com/f/cases/edit/21595/Update-the-Oculus-Mobile-SDK-version)

* Update Oculus Mobile SDK from 1.19 to 1.22
* Support KHR_no_error for performance in the Oculus Mobile wrapper library
* Enable KHR_no_error in the questFramePlayer build

We can't currently enable KHR_no_error  in the main interface build because we have no way to enable it in the Qt created contexts we use, and you can't mix contexts with the feature enabled with ones without the feature.  

We _can_ enable it in the Quest version of the frame player app, and toggle it between enabled and not enabled in the code to compare the performance and see if it would be valuable to pursue enabling it in the main application.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17920/HighFidelity-Beta-PR15116-de1513a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17920/HighFidelity-Beta-Interface-PR15116-de1513a.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17920/HighFidelity-Beta-PR15116-de1513a.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17920/HighFidelity-Quest-Beta-PR15116-de1513a.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17920/HighFidelity-Beta-PR15116-de1513a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17920/HighFidelity-Beta-Interface-PR15116-de1513a.exe

**Comment by jherico** [comment]
build this please

**Pull request merged**
