### PR TITLE
expose getJointNames for entities to js

### PR DESCRIPTION
**Pull request by sethalves**
- allow javascript to ask for a list of joint-names in a given entity: Entities.getjointNames(uuid);

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: f265656e741eff9da126e1d63933bb1f58b91d64 available at: https://gist.github.com/fd18c42bdbcd9597bcd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6864.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6864.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a515d6debe563e5d08342fd272776eace79c6431 available at: https://gist.github.com/fd18c42bdbcd9597bcd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6864.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6864.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: edea0320e6d83959d50a1599c6d473f2a2fec87e available at: https://gist.github.com/fd18c42bdbcd9597bcd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6864.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6864.dmg

**Comment by sethalves** [comment]
Okay, maybe I've found a way to get this information to scripts without a thread race.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0064ee6ab2e01a6a6ba4f9a5c492336ddfd358f7 available at: https://gist.github.com/fd18c42bdbcd9597bcd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6864.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6864.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 28d673cb97740dc9e71b540beadecd48b6c5b81f available at: https://gist.github.com/fd18c42bdbcd9597bcd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6864.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6864.dmg

**Pull request merged**
