### PR TITLE
reduce warnings about truncated kinematic timesteps

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* reduce warnings about kinematic timesteps

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
A recent change introduced a warning about "truncated kinematic timesteps" and we found out that we were seeing a lot of them.  The dire nature of the warnings did not properly reflect what was actually going on: most of those warnings were for non-moving objects that hadn't been changed for a long time --> kinematic extrapolation of their movement is a no-op.

This PR moves things around so that we don't get the warning so much and also properly initializes the `EntityServer::_lastSimulated` data member whenever an object is added to the list of non-physical kinematic objects (in EntitySimulation).

The warning still shows up at login sometimes for moving objects -- I think what is happening is either the packets really do sit for several seconds or there is an unknown clock skew between the client and server at that point which is eventually properly measured and goes away.  We'll leave it at "warning" level for now and consider dropping it to "debug" later.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d984ce47922594e5cc993e0d48869a0539973528 available at: https://gist.github.com/3565bc695edd0b6eb6d342605cc0b601<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7746.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7746.dmg

**Comment by AndrewMeadows** [comment]
To test:

(1) Log into any domain
(2) Bring up the interface log window (I think it is ctrl+alt+shift+L)
(3) Check for a burst of logs that look like this:
```
[04/22 22:07:23] [WARNING] kinematic timestep = 80661.9 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 80661.9 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 80661.9 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 32607.6 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 80662 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 80662 truncated to 1
[04/22 22:07:23] [WARNING] kinematic timestep = 80662.1 truncated to 1
```
(4) This PR reduces the big burst to just a few -- one for each kinematic object in view.  There appears to still be some long timesteps computed as the interface and entity-server figure out their clock skew.  We'll look into those later, but all of the innocuous warnings have been removed.

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**PR Build:** 7746
**Testing Architecture:** 64-bit PC Desktop
**Testing OS:** Windows 10
**Testing Locations:** localhost
**Additional Test Results Requested:** Successful test.  Log shows no trace of any mention of ```kinematic timestep``` occurrences.  Log file included for deeper inspection.
**Successful Logout/Crash:** Failure.  Crash upon logout of interface.  Log file included for deeper inspection.  
[attachments.zip](https://github.com/highfidelity/hifi/files/233027/attachments.zip)

**Comment by ZappoMan** [comment]
The crash that Kevin had was unrelated to this PR... so I'm going to call this QA Pass

**Pull request merged**
