### PR TITLE
Hotfix: fix null candidate ice-server QHostAddress

### PR DESCRIPTION
**Pull request by birarda**
- stop null QHostAddress from being used for ice-server address

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4430/HighFidelity-Beta-PR11682-946cda02b1f28184319af739e54e0d5640be6300.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4433/HighFidelity-Beta-PR11682-9345f4545f29cb24112bd76a012142a479769391.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4433/HighFidelity-Beta-PR11682-9345f4545f29cb24112bd76a012142a479769391.exe

**Comment by birarda** [comment]
#### Test Plan

1. Confirm you can connect to the temporary place name for the Sandbox from this PR.
2. Confirm somebody outside your network can connect to the temporary place name for the Sandbox from this PR.
2. Connect your High Fidelity account to the domain server running from this PR.
3. Create a domain ID and attach a place name you own to the domain server running from this PR.
4. Confirm you can connect to the place name for the domain server from this PR.
5. Confirm somebody outside your network can connect to the place name for the domain server from this PR.
6. Co-ordinate with me to confirm that when the ice-server that your domain-server is using is brought down the log shows it connect to a new ice server and you are able to be connected to via your place name.

**Comment by Nex-Pro** [comment]
Testing by request.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4440/HighFidelity-Beta-PR11682-e450ac5bd3b5fd13357b85a1d31ded73aa9dbe7a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4440/HighFidelity-Beta-PR11682-e450ac5bd3b5fd13357b85a1d31ded73aa9dbe7a.exe

**Comment by Nex-Pro** [comment]
Testing win10

**Comment by Nex-Pro** [comment]
Tested win 10

## PASS   all good

Confirm you can connect to the temporary place name for the Sandbox from this PR. **SUCCESS**

Confirm somebody outside your network can connect to the temporary place name for the Sandbox from this PR.**SUCCESS**

Connect your High Fidelity account to the domain server running from this PR. **DONE**

Create a domain ID and attach a place name you own to the domain server running from this PR.**DONE**

Confirm you can connect to the place name for the domain server from this PR. **SUCCESS**
Confirm somebody outside your network can connect to the place name for the domain server from this PR.**SUCCESS**
Co-ordinate with me to confirm that when the ice-server that your domain-server is using is brought down the log shows it connect to a new ice server and you are able to be connected to via your place name.  **DONE**

**Pull request merged**
