### PR TITLE
Update Dialog - changed old interface icon with new interface  icon

### PR DESCRIPTION
**Pull request by druiz17**

### CODE REVIEW

**Comment by druiz17** [comment]
On the auto updater alert, I changed the old interface icon to the new interface icon

fogbugz link - https://highfidelity.fogbugz.com/f/cases/2128/High-Fidelity-Updater-alert-has-old-Interface-Icon

**Comment by ZappoMan** [comment]
Is there a way to test this? I don't think there is, since PR builds (I believe) don't ever auto-update.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a948e03ed8d831dfbffa0dfbb06c7ebeb9d2bd06 available at: https://gist.github.com/8cbe4301b52898dea35532ebac719f8f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8983-a948e03.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8983-a948e03.dmg

**Comment by druiz17** [comment]
I did a hack on dev build to test it and it worked. I also talked to Andrew and he said we could merge it and see if it works when there is a new update on an official build, since there doesn't seem a way for PR to test it

**Comment by AndrewMeadows** [comment]
I removed the QA_READY label.  There is no easy way to test this -- it would have to be a HACK test or we'd have to artificially bump the version number just to test.  Meanwhile the change is simple and the risk of breakage is small.  I vote we just merge it and pay attention to the icon on next version update.

**Comment by RyanDowne** [comment]
I think the risk to merge this and see is low  - I am gonna mark it QA passed.

**Pull request merged**
