### PR TITLE
Improvements to wireshark plugin

### PR DESCRIPTION
**Pull request by hyperlogic**
* properly decodes AvatarData packets embedded within BulkAvatarData packets
* Keeps a running total of all the different types of data within the AvatarData packet.
  This is useful for breaking down how much bandwidth is consumed by each sub-section.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18722/HighFidelity-Beta-PR15389-f8bca69.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18722/HighFidelity-Beta-Interface-PR15389-f8bca69.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18722/HighFidelity-Beta-PR15389-f8bca69.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18722/HighFidelity-Quest-Beta-PR15389-f8bca69.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18722/HighFidelity-Beta-PR15389-f8bca69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18722/HighFidelity-Beta-Interface-PR15389-f8bca69.exe

**Comment by hyperlogic** [comment]
closing, these improvements will be rolled into another PR.

**Pull request closed without merging**
