### PR TITLE
DEV-611: Ensure that entities with the link property set can be clicked in Desktop and VR modes

### PR DESCRIPTION
**Pull request by zfox23**
https://highfidelity.atlassian.net/browse/DEV-611

Pre-merge testing required because I didn't actually test this (I don't have hand controllers at the moment). I'm _pretty_ sure that this code will achieve the desired result :)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21411/HighFidelity-Beta-PR16221-88d42aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21411/HighFidelity-Quest-Beta-PR16221-88d42aa.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21411/HighFidelity-Beta-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21411/HighFidelity-Beta-Interface-PR16221-88d42aa.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21413/HighFidelity-Beta-PR16221-88d42aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21413/HighFidelity-Quest-Beta-PR16221-88d42aa.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21413/HighFidelity-Beta-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21413/HighFidelity-Beta-Interface-PR16221-88d42aa.dmg

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21416/HighFidelity-Beta-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21416/HighFidelity-Beta-PR16221-88d42aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21416/HighFidelity-Quest-Beta-PR16221-88d42aa.apk)

**Comment by ZappoMan** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21419/HighFidelity-Beta-PR16221-88d42aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21419/HighFidelity-Quest-Beta-PR16221-88d42aa.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21419/HighFidelity-Beta-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21419/HighFidelity-Beta-Interface-PR16221-88d42aa.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21423/HighFidelity-Beta-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21423/HighFidelity-Beta-Interface-PR16221-88d42aa.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21423/HighFidelity-Beta-PR16221-88d42aa.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21423/HighFidelity-Quest-Beta-PR16221-88d42aa.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21423/HighFidelity-Beta-PR16221-88d42aa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21423/HighFidelity-Beta-Interface-PR16221-88d42aa.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21602/HighFidelity-Beta-PR16221-45c95fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21602/HighFidelity-Beta-Interface-PR16221-45c95fe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21602/HighFidelity-Beta-PR16221-45c95fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21602/HighFidelity-Beta-Interface-PR16221-45c95fe.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21602/HighFidelity-Beta-PR16221-45c95fe.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21602/HighFidelity-Quest-Beta-PR16221-45c95fe.apk)

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21665/HighFidelity-Beta-PR16221-5f1c389.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21665/HighFidelity-Quest-Beta-PR16221-5f1c389.apk)

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21696/HighFidelity-Beta-PR16221-5f1c389.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21696/HighFidelity-Quest-Beta-PR16221-5f1c389.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21696/HighFidelity-Beta-PR16221-5f1c389.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21696/HighFidelity-Beta-Interface-PR16221-5f1c389.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21736/HighFidelity-Beta-PR16221-5f1c389.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21736/HighFidelity-Quest-Beta-PR16221-5f1c389.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21736/HighFidelity-Beta-PR16221-5f1c389.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21736/HighFidelity-Beta-Interface-PR16221-5f1c389.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21736/HighFidelity-Beta-PR16221-5f1c389.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21736/HighFidelity-Beta-Interface-PR16221-5f1c389.exe

**Comment by shanzzam** [comment]
waiting for qa testing until we merge this

**Pull request merged**
