### PR TITLE
Case 20942: Goto the spot on first launch (80.0/master)

### PR DESCRIPTION
**Pull request by danteruiz**
Goto the spot on first launch 

Ticket - https://highfidelity.manuscript.com/f/cases/20942/Redirect-FTUE-URL-To-Master

### CODE REVIEW

**Comment by danteruiz** [comment]
test plan in this PR https://github.com/highfidelity/hifi/pull/14833

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16958/HighFidelity-Beta-PR14831-778ddad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16958/HighFidelity-Beta-PR14831-778ddad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16958/HighFidelity-Beta-Interface-PR14831-778ddad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16958/HighFidelity-Beta-PR14831-778ddad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16958/HighFidelity-Beta-Interface-PR14831-778ddad.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
