### PR TITLE
Experimental shader update: Metallic from Binary to Gradient

### PR DESCRIPTION
**Pull request by Menithal**
This is non-worklist experimental shader change By someone not versed in graphics engines who got tired of waiting. And this is to make the behavior of metallic more closer to other engines, and be less confusing for someone comming in from those engines.

 Updated metallic logic to not be a boolean value. Instead, the fresnel value is generated from the combination of the metallic and the diffuse color, with the metallic being a multiplier value. 

This allows the metallicness to blend on pixel level, when metallic starts and ends on a texture and makes it less jarring. Avoids also setting of the frag.metallic, instead using the clamped defined values from the unpacking.

CC: @samcake and decision of Hifi if this gets implemented like this, or a proper solution is done for these.

### CODE REVIEW

**Comment by Menithal** [comment]
Here are also some test items you can compare between versions

https://s3.eu-west-2.amazonaws.com/norteclabs.com/HF/experiment/Torch.json
https://s3.eu-west-2.amazonaws.com/norteclabs.com/HF/experiment/FlareGunImproved.json

And some items from sketchfab (may require conversion, but since they ask not to upload else where)
https://sketchfab.com/models/35deff5251eb432485c5a252d96040ea

Specifically this allows for -Blender- models to have the parity of stingray, but I am unable to test this with stingray models so that will also be needed to be tested. (because there is a whole bunch of logic that makes that different from  blender, as found out with FBXReader).

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1132/HighFidelity-Beta-PR10830-0f4306aa35395eed443cf70ad7c9f6f52451ae5f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1132/HighFidelity-Beta-PR10830-0f4306aa35395eed443cf70ad7c9f6f52451ae5f.dmg

**Comment by CainFoool** [comment]
Hey @Menithal: Is this ready for QA?

**Comment by Menithal** [comment]
@Cainfool this is not really worklist or approved PR. Unless it's been dev approved it's more of an experiment for others to try and open for feedback.

**Comment by SkimiMission** [comment]
Much better as what we have at moment,@menithal. Wished that could be fixed that way!!

**Comment by samcake** [comment]
This is cool @Menithal !
i need some time to make sure that has the correct behavior accrosss the board
I ll try to validate that  next week

**Comment by Menithal** [comment]
@samcake any update?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1704/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.dmg

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by AndrewMeadows** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1933/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1933/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.dmg

**Comment by AndrewMeadows** [comment]
FYI: @samcake is on vacation until the end of July and then he'll be at siggraph 2017.

**Comment by Menithal** [comment]
Any update @samcake? :)

**Comment by samcake** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2729/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.exe

**Comment by themelissabrown** [comment]
keep this PR open. @samcake will be addressing the work done in it

**Comment by Menithal** [comment]
Whats the status of this?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4549/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4549/HighFidelity-Beta-PR10830-ed6183593bd7d5089c8bc3b1ed4bd3b71b302303.exe

**Comment by Menithal** [comment]
@themelissabrown  / @samcake  ?

**Comment by samcake** [comment]
@Menithal 
Haven;t forgoten you, don;t worry
i actually drafted the gltf2 shader pipeline in a branch.
it s not just code complete yet, it s just a WIP.
It s based on this PR though.
i keep it as a public reminder.

**Comment by samcake** [comment]
ANd we finally did it @Menithal 
@Zvork 's pr got merged this morning and it goes over the shadiing code to be on parwith gltf2
THanks for your patience and your work to get that to ship

**Pull request closed without merging**
