### PR TITLE
Attempt to resolve Tablet scripting interface deadlocks

### PR DESCRIPTION
**Pull request by jherico**
This PR releases the locks on `_tabletMutex` in a few cases where previously they were held during a call to  `QMetaObject::invokeMethod`.  If the target thread for the invocation was already waiting on `_tabletMutex` this would cause the two threads to deadlock.  

## Testing

Smoke test.  As far as I know there's no reliable way to trigger the deadlock explicitly, although it happened twice in one day when I was running in debug builds.  It's likely much rarer in release builds.

### CODE REVIEW

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/555/HighFidelity-Beta-PR10657-30c86ff321d5880accf360deae2be64453821b57.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/555/HighFidelity-Beta-PR10657-30c86ff321d5880accf360deae2be64453821b57.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Complete

Smoke tested - game appears to run normally. Did not experience any deadlocks.

**Pull request merged**
