### PR TITLE
Reset pending domain check-in count more frequently 

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
The domain connection is reset when the number of outstanding check-ins reaches five. Sending of check-in packets can be initiated by a periodic 1 s counter, by the local or public ICE sockets being created, by successful lookup of the domain's hostname, by an account key-pair being generated and other reasons.

In a low-end environment the various triggers might conspire to push the pending check-ins over the limit.

This PR resets the count when other packets are received from the domain server, since they indicate that the DS is still alive, and when the ICE sockets are activated.

https://highfidelity.manuscript.com/f/cases/14394/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9310/app_13045_PR_bfbded7beca85e58c1b87801f715d3cee678f027.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9310/HighFidelity-Beta-PR13045-bfbded7beca85e58c1b87801f715d3cee678f027.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9310/HighFidelity-Beta-Interface-PR13045-bfbded7beca85e58c1b87801f715d3cee678f027.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9310/HighFidelity-Beta-PR13045-bfbded7beca85e58c1b87801f715d3cee678f027.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9310/HighFidelity-Beta-Interface-PR13045-bfbded7beca85e58c1b87801f715d3cee678f027.exe

**Comment by SimonWalton-HiFi** [comment]
I think one semantic issue is are the check-in responses indicating that the domain server and intervening network just still alive, or is the limit specifically for the domain list reply. If the former then any response from the DS indicates it's still alive.

**Comment by birarda** [comment]
@SimonWalton-HiFi the limit should specifically be for the domain list reply (or an action the DS takes directly related to that, like sending a connection token packet)

**Comment by SimonWalton-HiFi** [comment]
I've taken out the other places I'd cleared the pending count. There's not really much left of the PR.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9330/app_13045_PR_cfc5892d63f342949bf886dc45e99e07809aa0db.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9330/HighFidelity-Beta-PR13045-cfc5892d63f342949bf886dc45e99e07809aa0db.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9330/HighFidelity-Beta-Interface-PR13045-cfc5892d63f342949bf886dc45e99e07809aa0db.dmg

**Comment by birarda** [comment]
QA not needed here - renaming of existing methods and addition of a clear that requires local dev build debugging to test.

**Pull request merged**
