### PR TITLE
WL 21542 - Allow Scripts to change Avatar Gravity [Experimental]

### PR DESCRIPTION
**Pull request by cain-kilgore**
> It should be possible via script to change the avatar's gravity. Write a script that would allow the avatar's gravity to be changed especailly to do things such as jumping weightlessly.
> 
> This is experimental and might not get merged.

## Test Plan

- Install this PR
- Run the script `scripts/developer/tests/gravityScript.js`
- Use the Gravity Menu button to change your Avatar Gravity (Default is `-5`)
- Confirm that it does indeed change. (You might need to jump (E) if you set it to a negative value after setting it to a positive value)
- Use the Console and confirm `MyAvatar.setGravity(value)` works as expected. (eg. `MyAvatar.setGravity(-1)`
- Use the Console and confirm `MyAvatar.getGravity()` returns the current Avatar's Gravity.
- Restarting the Interface should put the Avatar back to default Gravity.

[WL 21542](https://worklist.net/21542)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3345/HighFidelity-Beta-PR11371-794f3ca69ffc812ad3829998c2f77dcbc105cdb6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3345/HighFidelity-Beta-PR11371-794f3ca69ffc812ad3829998c2f77dcbc105cdb6.exe

**Comment by Nex-Pro** [comment]
Having to restart interface to clear this seems like an oversight.

**Comment by cain-kilgore** [comment]
If the behaviour needs to be changed then I can, however it says nothing about needing to persist.

**Comment by Nex-Pro** [comment]
Testing this with my magnetic boots on.

**Comment by Nex-Pro** [comment]
### Pass with some reservations.

getter and setter work fine.

handles floats as expected.

#### FEEDBACK:
Strange that we need to jump up while going up in order to go down when the gravity is changed. I think this is an oversight. Seems to me that new gravity should kick in when set.

**Comment by cain-kilgore** [comment]
@hyperlogic Could you take a look at this when you get a chance? Thanks!

**Comment by Nex-Pro** [comment]
characterController.cpp  lines 23 and 371 var name

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3472/HighFidelity-Beta-PR11371-4d904bd5ce7d7b1a805c2f8fbdda630afc27576f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3472/HighFidelity-Beta-PR11371-4d904bd5ce7d7b1a805c2f8fbdda630afc27576f.dmg

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3478/HighFidelity-Beta-PR11371-4d904bd5ce7d7b1a805c2f8fbdda630afc27576f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3478/HighFidelity-Beta-PR11371-4d904bd5ce7d7b1a805c2f8fbdda630afc27576f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3495/HighFidelity-Beta-PR11371-45f79b43412344f2eff7a9c66a2072e5f594599e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3495/HighFidelity-Beta-PR11371-45f79b43412344f2eff7a9c66a2072e5f594599e.exe

**Comment by cain-kilgore** [comment]
Ready for another QA.

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Install this PR **Check**
Run the script scripts/developer/tests/gravityScript.js **Check**
Use the Gravity Menu button to change your Avatar Gravity (Default is -5) **Check**
Confirm that it does indeed change. (You might need to jump (E) if you set it to a negative value after setting it to a positive value) **Check**
Use the Console and confirm MyAvatar.setGravity(value) works as expected. (eg. MyAvatar.setGravity(-1) **Check**
Use the Console and confirm MyAvatar.getGravity() returns the current Avatar's Gravity. **Check**
Restarting the Interface should put the Avatar back to default Gravity. **Check**

**Pass** All looks good to me :)

**Notes: Gravity does not reflect changes until user has gone back to a surface point, though I assume this is by design**

**Comment by PhilipRosedale** [comment]
I'd like to see the change to gravity instantly affect the motion of the avatar, is this possible?  Needing to restart would cause confusion.  Inotherwards:  The motion of the avatar should not ever be inconsistent with the value returned by the getGravity() call, and the value should change immediately when set.

**Comment by cain-kilgore** [comment]
@PhilipRosedale and @AndrewMeadows: The changes have been made to work in real time now once this build finishes. :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3540/HighFidelity-Beta-PR11371-0d33976035fd2e96a0aec69e3993f9cbbf5be328.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3540/HighFidelity-Beta-PR11371-0d33976035fd2e96a0aec69e3993f9cbbf5be328.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

All previous checks successful as before with the addition of gravity now being changeable and having an immediate effect mid-air / at any time, as opposed to needing to touch a surface mentioned before. **Pass**

**Pull request merged**
