### PR TITLE
better scrolling and fixed button touching

### PR DESCRIPTION
**Pull request by druiz17**
Test
- when the tablet is up...stick your stylus through it (stab it)  when you move the stylus the tablet should scroll (up or down)
- ensure that clicking on tablet buttons is still easy

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ec8071288b55546fbe668521fd59b27427793a2 available at: https://gist.github.com/42b7281d3c9202459eed926684ff4f0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9597-0ec8071.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9597-0ec8071.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0ec8071288b55546fbe668521fd59b27427793a2 available at: https://gist.github.com/42b7281d3c9202459eed926684ff4f0a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9597-0ec8071.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9597-0ec8071.dmg

**Comment by claudioshg** [comment]
Testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift and Oculus Touch

Tested Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9597-0ec8071.exe

**PASS**
- when the tablet is up...stick your stylus through it (stab it) when you move the stylus the tablet should scroll (up or down): **PASS**
- ensure that clicking on tablet buttons is still easy: **PASS**

NOTE
- The Stylus and Tablet behaved as intended.

**Pull request merged**
