### PR TITLE
fix JSDOC typo rule -> role

### PR DESCRIPTION
**Pull request by thoys**

### CODE REVIEW

**Comment by MiladNazeri** [comment]
Doc change - no QA needed

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7805/app_12582_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7805/HighFidelity-Beta-PR12582-866bec0b34da3dc8da1c7ffd741d08e86ed919be.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7805/HighFidelity-Beta-PR12582-866bec0b34da3dc8da1c7ffd741d08e86ed919be.dmg

**Pull request merged**
