### PR TITLE
DEV-220: Lilypad Launcher: (Mac) Add versioning info to Launcher screen

### PR DESCRIPTION
**Pull request by danteruiz**
Ticket - https://highfidelity.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=BUGZ&modal=detail&selectedIssue=DEV-220&assignee=557058%3A56835251-5116-4703-a5d3-30bccdb21af4

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20449/HighFidelity-Beta-PR15955-1d1b1a9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20449/HighFidelity-Beta-Interface-PR15955-1d1b1a9.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20449/HighFidelity-Beta-PR15955-1d1b1a9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20449/HighFidelity-Beta-Interface-PR15955-1d1b1a9.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20449/HighFidelity-Beta-PR15955-1d1b1a9.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20449/HighFidelity-Quest-Beta-PR15955-1d1b1a9.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20491/HighFidelity-Beta-PR15955-08bfe00.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20491/HighFidelity-Quest-Beta-PR15955-08bfe00.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20491/HighFidelity-Beta-PR15955-08bfe00.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20491/HighFidelity-Beta-Interface-PR15955-08bfe00.dmg

**Comment by danteruiz** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20495/HighFidelity-Beta-PR15955-08bfe00.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20495/HighFidelity-Beta-Interface-PR15955-08bfe00.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20495/HighFidelity-Beta-PR15955-08bfe00.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20495/HighFidelity-Quest-Beta-PR15955-08bfe00.apk)

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20506/HighFidelity-Beta-PR15955-9c33454.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20506/HighFidelity-Quest-Beta-PR15955-9c33454.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20506/HighFidelity-Beta-PR15955-9c33454.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20506/HighFidelity-Beta-Interface-PR15955-9c33454.dmg

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20509/HighFidelity-Beta-PR15955-9c33454.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20509/HighFidelity-Quest-Beta-PR15955-9c33454.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20509/HighFidelity-Beta-PR15955-9c33454.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20509/HighFidelity-Beta-Interface-PR15955-9c33454.dmg

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20513/HighFidelity-Beta-PR15955-9c33454.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20513/HighFidelity-Quest-Beta-PR15955-9c33454.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20513/HighFidelity-Beta-PR15955-9c33454.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20513/HighFidelity-Beta-Interface-PR15955-9c33454.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20513/HighFidelity-Beta-PR15955-9c33454.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20513/HighFidelity-Beta-Interface-PR15955-9c33454.exe

**Pull request merged**
