### PR TITLE
update-orbitingSound.js

### PR DESCRIPTION
**Pull request by howard-stearns**
Update orbitingSound.js to use a sample file that exists and setOptions function.

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/89145607667591

**Comment by hifi-gustavo** [comment]
Build console output for commit: 25671fbefe06f7e1b11a7cee03be06a8be902f1a available at: https://gist.github.com/fe6613040960e8bf86f3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7104.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7104.dmg

**Comment by ZappoMan** [comment]
I don't hear anything when I run this script.

**Comment by ZappoMan** [comment]
After a little more testing... here's what I discovered... if you run the script a second time, you do hear orbiting sounds... but I think that it fails the first time, related to the sound file still downloading. I think you have to code support to verify that the sound has been downloaded before calling play or else it never starts playing the loop.

**Comment by howard-stearns** [comment]
Ah. ok fair enough. But that would be a different bug, wouldn't it? :-)

**Comment by ZappoMan** [comment]
well - the bug report from Philip was "the script doesn't work" -- and with the newest version -- it still "doesn't work" apparently on the first run. So if I merge this, the same described bug still manifests... me thinks.

**Comment by howard-stearns** [comment]
I have to make my smiley faces larger.
Newest version adds test for being downloaded.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a3972c43ffca3c5c309b33926bab36c6dec7627 available at: https://gist.github.com/fe6613040960e8bf86f3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7104.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7104.dmg

**Comment by bluetoe** [comment]
Seemed to work for me first time. But it took me awhile to find the script.. .not that that would have much to do with it except that I was idle for a bit before I ran it. And yes probably newest version.

**Pull request merged**
