### PR TITLE
Case 21402: Don't send a KillAvatar packet on kick

### PR DESCRIPTION
**Pull request by Atlante45**
[Manuscript Ticket](https://highfidelity.manuscript.com/f/cases/21402/Kicking-lock-the-reliable-traffic-between-the-DS-and-the-Avatar-Mixer)

The DS already takes cares of removing nodes no longer allowed when the permissions are updated.
So remove the KillAvatar logic and let the DS send the disconnect packets by itself.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17552/HighFidelity-Beta-PR15004-f12eb6e.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17568/HighFidelity-Beta-PR15004-f173c5d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17568/HighFidelity-Beta-PR15004-f173c5d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17568/HighFidelity-Beta-Interface-PR15004-f173c5d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17568/HighFidelity-Beta-PR15004-f173c5d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17568/HighFidelity-Beta-Interface-PR15004-f173c5d.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by shanzzam** [comment]
Closing this per conversation with @howard-stearns, bridie, and @Atlante45

**Pull request closed without merging**
