### PR TITLE
Fix MS15103: Interface crashes on snap if snap dir is deleted

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS15103](https://highfidelity.manuscript.com/f/cases/15103/If-snap-save-folder-is-deleted-taking-snap-crashes-interface).

The behavior of what happens when you attempt to take a Still + GIF snapshot and the still snapshot fails to write to disk is not optimal, but the bug bug above is fixed in all cases.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9838/HighFidelity-Beta-PR13181-c34605f686a5daccf757e200c4b989073b1ecad6.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9839/HighFidelity-Beta-PR13181-c3ea176b5811f4f6ba1c15b95e6e97fdaf0ead29.apk

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Ensure your Snapshots directory is an invalid directory (i.e. `C:\fjpaoisjefpoiasjepfoijaspeoifj`)
    - You can set this in Settings -> General
- Ensure Interface is running.

### Tests
1. Press the P key on your keyboard.
    - Verify that you see a directory chooser appear, and that its title is `Write Error - Choose New Snapshots Directory`
    - Verify that Interface hasn't crashed
2. Click the "Cancel" button.
    - Verify that Interface hasn't crashed
3. Press the P key again.
    - Verify that you see a directory chooser appear, and that its title is `Write Error - Choose New Snapshots Directory`
    - Verify that Interface hasn't crashed
4. Use the directory chooser to choose a new snapshots directory - be wary of bug [MS6054](https://highfidelity.manuscript.com/f/cases/6054/Snapshot-directory-selection-issue) when choosing a directory and don't fail this PR because of that bug. Click CHOOSE.
    - Verify that a .jpg snapshot has been placed in that directory
    - Verify that you see a notification in the top right of your screen about your newly-taken snapshot
    - Verify that Interface hasn't crashed
5. Reset your Snapshots directory to an invalid directory. Open the SNAP app. Ensure you're set to capture "GIF + STILL". Click the red button.
    - Verify that you see a directory chooser appear, and that its title is `Write Error - Choose New Snapshots Directory`
    - Verify that Interface hasn't crashed
6. Use the directory chooser to choose a new snapshots directory. Click CHOOSE.
    - Verify that a .jpg snapshot has been placed in that directory
    - Verify that, after a few seconds, a .gif snapshot has been placed in that directory
    - Verify that you see a notification in the top right of your screen about your newly-taken snapshots
    - Verify that Interface hasn't crashed

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9841/HighFidelity-Beta-PR13181-f8215b59993629f77069921c5335981ed35c9039.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9841/HighFidelity-Beta-Interface-PR13181-f8215b59993629f77069921c5335981ed35c9039.dmg

**Comment by qlikmorales** [comment]
Working on Desktop

**Comment by qlikmorales** [comment]
Passes @conklin94122

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9849/HighFidelity-Beta-PR13181-486f33b4bdd20772e30f93410d1fa5fe4f26756a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9849/HighFidelity-Beta-Interface-PR13181-486f33b4bdd20772e30f93410d1fa5fe4f26756a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9849/HighFidelity-Beta-PR13181-486f33b4bdd20772e30f93410d1fa5fe4f26756a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9849/HighFidelity-Beta-Interface-PR13181-486f33b4bdd20772e30f93410d1fa5fe4f26756a.exe

**Pull request merged**
