### PR TITLE
Case 21128: AccountServices, HifiAbout, and WalletScriptingInterface JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
https://highfidelity.manuscript.com/f/cases/21128

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

There are no executable code changes so no testing required.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17281/HighFidelity-Beta-PR14918-6a00834.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17281/HighFidelity-Beta-PR14918-6a00834.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17281/HighFidelity-Beta-Interface-PR14918-6a00834.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17281/HighFidelity-Beta-PR14918-6a00834.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17281/HighFidelity-Beta-Interface-PR14918-6a00834.exe

**Pull request merged**
