### PR TITLE
Qt image compare

### PR DESCRIPTION
**Pull request by NissimHadar**
**Auto-tester changes only.**
image

**Executive Summary**
The auto-tester supports regression testing of the Interface.  The life-cycle of testing is as follows:
1)  Test scripts are written in the tests folder hierarchy.  The results of running a script are a set of snapshots in the folder.
2)  An initial set of snapshots is stored as the _gold standard_.  Running a test will create a second set of snapshots that should be very similar to the stored snapshots.
3)  auto-tester is then used to compare these sets of images.
4)  Options are provided to automatically create a test script that will run all the tests recursively, and to evaluate tests recursively.

A tester follows the following steps:
1)  Create a recursive script at the top of the hierarchy (one click).
2)  Run the recursive script in Interface
3)  Evaluate the results (one click)
4)  If any tests have failed - send the zipped test failure folder to the development team.

**Changes**
An option has been added for running the tests interactively or in a batch mode.  The interactive (default) mode displays each failed test.  The error is now also shown as a diff image:
image

Stores all test results in a single zipped folder, if any test has failed.  This folder contains a sub-folder for each failed test - which includes:
1)  Expected image
2) Actual image
3) Difference image
4) Test failure description

image

**Usage**
The hifi_tests contains instructions for installing the test environment, as well as developer and tester specific instructions (readme files in markdown format).

**Testing**
A test suite is available at https://highfidelity.testrail.net/index.php?/suites/view/442&group_by=cases:title&group_order=asc

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5674/HighFidelity-Beta-PR12000-bd5e2c9ab6cd30419d53076b9fddc3fdc303483e.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5676/HighFidelity-Beta-PR12000-0e7bc29649cc023e860f6d940a02276d2b3e11c0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5676/HighFidelity-Beta-PR12000-0e7bc29649cc023e860f6d940a02276d2b3e11c0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5697/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5697/HighFidelity-Beta-PR12000-8038f2bd9f60603c60f51b1db9c683e612a4bbef.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5697/HighFidelity-Beta-PR12000-8038f2bd9f60603c60f51b1db9c683e612a4bbef.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5737/app_12000_PR.apk

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5759/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5884/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5885/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5888/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5889/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5890/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5891/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5891/HighFidelity-Beta-PR12000-0265068342a488041ab069e10ed7dd349c005488.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5891/HighFidelity-Beta-PR12000-0265068342a488041ab069e10ed7dd349c005488.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5893/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5893/HighFidelity-Beta-PR12000-4feb95f582f68fbeceb6e396cae3a7edb80b80e8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5893/HighFidelity-Beta-PR12000-4feb95f582f68fbeceb6e396cae3a7edb80b80e8.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5894/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5895/app_12000_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5895/HighFidelity-Beta-PR12000-5efc0a18a7a4c084531c7b731ee69a668318affe.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5895/HighFidelity-Beta-PR12000-5efc0a18a7a4c084531c7b731ee69a668318affe.dmg

**Pull request closed without merging**
