### PR TITLE
[rc69.1]  The client should render "something" for an avatar even if mesh or identity is not available

### PR DESCRIPTION
**Pull request by hyperlogic**
Same logical change as PR #13478

This pr implements an overlay that is created while an Avatar is discovered by the AvatarManager but the geometry is not loaded.  Alternatively it will display while the model is changing for an Avatar that is already in the domain.

The associated FogBugz is 16105.

For this pr the class OtherAvatar was moved from avatars-renderer to interface.  This allows the OtherAvatar class to access the application list of overlays.

### Test Plan
1. Start interface and go to a domain with other avatars in it, preferably 'rust-experiments'.  While the other avatar models are loading you should see a purple orb overlay in the place of the loading avatars.
2. Go to a domain with two different clients.  On one client, change the existing path of the avatar by typing the letter 'x' at the end of the current url.  When you click save, watch the other client to see that there is an orb for a moment while the avatar is searching the bad url and changing to default avatar.

### CODE REVIEW

**Comment by Qliemillar** [comment]
Build this please

**Comment by amantley** [comment]
It looks like we are getting a build complaint because this constant is not being resolved in OtherAvatar.cpp
OTHERAVATAR_LOADING_PRIORITY

I think it just needs Avatar::OTHERAVATAR_LOADING_PRIORITY

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11211/HighFidelity-Beta-PR13565-eee1a1a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11215/HighFidelity-Beta-PR13565-d4b95bb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11215/HighFidelity-Beta-PR13565-d4b95bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11215/HighFidelity-Beta-Interface-PR13565-d4b95bb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11215/HighFidelity-Beta-PR13565-d4b95bb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11215/HighFidelity-Beta-Interface-PR13565-d4b95bb.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Purple Orb is visible.

**Pull request merged**
