### PR TITLE
turn off hand-controller pointer when Interface doesn't have focus

### PR DESCRIPTION
**Pull request by howard-stearns**

### CODE REVIEW

**Comment by howard-stearns** [comment]
Fix fogbugzid:546.

**Comment by kevinmthomas-carpool** [comment]
Test plan?  I would assume load Interface, enable hand controllers, lose focus of interface to ensure the mouse has proper control and is not stuck in a non-controllable state?

**Comment by howard-stearns** [comment]
Test plan:
This doesn't purport to fix all cases of mouse-vs-hand-controller fighting -- just the one reported by https://highfidelity.fogbugz.com/f/cases/546/interface-captures-mouse-sometimes-when-it-shouldnt

1. pick up hand-controller. (As reported, keep the hand-controller aimed at a (perhaps large) overlay window. I don't think that part is actually required, but try both ways.)
2. alt-tab to another window (while still keeping the hand-controller "live", e.g., not cradled).
3. The cursor should behave normally for the other app, and not be warped back to Interface even when the hand-controller gets moved around.

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa90d823d5b403072c1ccd6271c8edef1b3123cf available at: https://gist.github.com/58f98e55c9bb616f2f9534eaa67a3988<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7921.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7921.dmg

**Comment by kevinmthomas-carpool** [comment]
build failed

**Comment by howard-stearns** [comment]
test this please.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa90d823d5b403072c1ccd6271c8edef1b3123cf available at: https://gist.github.com/58f98e55c9bb616f2f9534eaa67a3988<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7921.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7921.dmg

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Very successful test and significant improvement regarding the relationship between the mouse and the hand controllers. Successfully alt-tabbed through many overlays and even minimized Interface and brought back to focus with no issue. The cursor behaves completely normal for other applications and does not warp back to Interface even when the hand-controller gets moved around. Successful test of placing hand-controllers on floor. No issue of any kind. Small issue of Microphone UI located in bottom right of screen upon login to Interface.

**Pull request merged**
