### PR TITLE
Improved HRTF

### PR DESCRIPTION
**Pull request by kencooke**
Adds a distance filter to model the frequency-dependent attenuation of sound propagation in open air.
Optimized using SIMD and computing all biquads in parallel. Performance impact is almost zero.
Filter updates are continuously interpolated and clean to -90dB.

Enabled by default in Interface and AudioMixer.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7399f5781b30db31796f1d9e475b60df2fec03f available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-d7399f5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-d7399f5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7a4bdc1779affed20fc0111689211bb2d5b23062 available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-7a4bdc1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-7a4bdc1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7c02d7a59b70c2f85f183a0fff535426d2fc4e4 available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-c7c02d7.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-c7c02d7.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa55fc84f5942c4e6b4dcac523c7f28d816ad22e available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-fa55fc8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-fa55fc8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d84c7524bf76efd09a213d9557573d22232aa70b available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-d84c752.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-d84c752.dmg

**Comment by kencooke** [comment]
The new HRTF adds a sound-propagation model that attenuates high frequencies based on distance.

### TEST PLAN
1) Ensure that other avatars in a domain are still audible and spatialized as before.
2) Run this script from Interface, to create a spatialized local injector:
```
var sound = SoundCache.getSound("https://s3.amazonaws.com/hifi-public/philip/memories.wav");

Audio.playSound(sound, { position: Vec3.sum(MyAvatar.position, Quat.getFront(MyAvatar.orientation)), loop: true, localOnly: true, volume: 100.0 });
```
Note that the amplitude (+40dB over fullscale) is intentionally very loud (rock-concert loud!) and will carry a very long distance. Verify that it spatializes correctly, and as you fly far away, it should become realistically more muffled.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2674df6095382bc6894265e3810c4ceb1aad9824 available at: https://gist.github.com/33c353c60c39f1b98ab6fb80d6ed2b53<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-2674df6.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8242-2674df6.dmg

**Comment by thoys** [comment]
##  QA Testing result

1. I lost my hearing as expected (Appointed with an ear doctor right away) :+1: 
2. The regular audio injectors and talking with other avatars still work as expected :+1: 
3. A feature that I was vowing for last week (localOnly with position support)  has been added in this PR, which is great!! Very Happy. :+1: 
4. Going more distant (far away) of the memory song stream makes it realistically muffled. :+1: 
5. QA passed

Tested with @Nex-Pro as other avatar


QA Passed

**Pull request merged**
