### PR TITLE
don't try to build convex hulls with nan data

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
We've been seeing a crash for bad data submitted to Bullet's `btConvexHullShape`.  Unfortunately we don't have a repro recipe for the content that tickles that crash.  This is a theoretical fix which is bolstered by evidence found in the visual studio `dmp` filed of one of the recorded crashes.

So nothing has changed and the **test plan** is to make sure objects that use convex hull collision shapes still collide correctly:

**(1)** Make a model entity item and for shape select either **Basic - Whole model** or else **Good - Sub-meshes** for the collision shape type.

**(2)** Make sure the model collides as one big convex hull around its shape (**Basic**) or as convex hulls around each of its various sub-meshes (**Good**).  That is, bump the object with your avatar, or grab a dynamic box and bump that into the model to measure its effective collision boundary.

**Comment by AndrewMeadows** [comment]
For those who have access to it: the link to the relevant bug is:  https://highfidelity.manuscript.com/f/cases/14383/crash-in-createConvexHull-ShapeFactory-createShapeFromInfo

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9057/app_12974_PR_ae186d46c68ea442d84f97937857caa60f193f3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9057/HighFidelity-Beta-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9057/HighFidelity-Beta-Interface-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9057/HighFidelity-Beta-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.exe

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9073/app_12974_PR_ae186d46c68ea442d84f97937857caa60f193f3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9073/HighFidelity-Beta-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9073/HighFidelity-Beta-Interface-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9108/app_12974_PR_ae186d46c68ea442d84f97937857caa60f193f3d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9108/HighFidelity-Beta-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9108/HighFidelity-Beta-Interface-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9108/HighFidelity-Beta-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9108/HighFidelity-Beta-Interface-PR12974-ae186d46c68ea442d84f97937857caa60f193f3d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Models react well to their appropriate collisions.

**Pull request merged**
