### PR TITLE
Add missing loading images for Asset Browser

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

 1. Connect to your local server
 2. Open the asset browser and upload a large enough file that it will take a few seconds to upload
 3. Confirm that a loading indicator (animated circle with an H in it) is displayed in the bottom left of the asset browser window

**Comment by hifi-gustavo** [comment]
Build console output for commit: d2fedee6563ff9b27b23f844a5a030e130436d79 available at: https://gist.github.com/a45a10205882b39c4876f57cdc623152<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8201.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8201.dmg

**Comment by OmegaHeron** [comment]
QA Pass
Testing Windows 10 64 bit
Opening file from dialog buttons results in animated "doing something" image.
Drag/Dropping file into interface works proper as well.
Animated image removes once transfer completes.

**Comment by Nex-Pro** [comment]
@jherico , does this need testing on OSX ?

**Pull request merged**
