### PR TITLE
DO NOT MERGE: Testing build

### PR DESCRIPTION
**Pull request by samcake**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b1ff877af1a5d1d96a09fcb00b4668efce8068ed available at: https://gist.github.com/90a9113f1d087da96987<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d1ac3148f025c4fc0f05552f05b13334977d0761 available at: https://gist.github.com/90a9113f1d087da96987<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cc65ad3ffb87dc5bc3bba61dc617fb37aed10d65 available at: https://gist.github.com/03ec74c852dac767c1e0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5133.dmg

**Comment by ZappoMan** [comment]
close for now.

**Pull request closed without merging**
