### PR TITLE
Sandbox entity includes

### PR DESCRIPTION
**Pull request by howard-stearns**
Prohibit entity script file includes from outside the original entity script's directory (unless its in our resources).

### CODE REVIEW

**Comment by howard-stearns** [comment]
https://app.asana.com/0/32622044445063/106994769319867

Note that this does NOT fix https://app.asana.com/0/26225263936266/108157111077754, which could effect testing.

**Comment by howard-stearns** [comment]
Testing notes:

This is a bit of a logic exercise, and I don't want to lead QA down a garden path by dicting the test process too narrowly.
The idea is that every possible use of Script.include should prevent loading a file url from outside the directory (or subsdirectories) of the that which the entity script itself was loaded from -- except that file urls to our pre-installed scripts is allowed. Including http(s) and ftp should be ok (even, for now, those on different hosts).

Note that Script.include can occur directly with the entity script function definition, within any method, within a timer callback defined from any of these, within a Script.addEventHandler callback defined within any of these, within a callback added by Script.addEventhandler within any of these, or within the callback argument to Script.include itself.  Also see note above.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22d2d2b69db0f08a4f201ad1156999d0770f072d available at: https://gist.github.com/9f995f1e24a5c41be072575244fb5f04<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7571.dmg

**Comment by thoys** [comment]
## QA Test

I have tested using the following script
```js
(function() {
    Script.include("scriptInDirBelow/script.js");
    // This might work?
    Script.include("../scriptInDirDown.js");
    // This should not work:
    Script.include("file:///C:/testEntityScript.js");
    Script.include("sameDirScript.js");
    print("done");
})
```

and got the following output:

```
[04/06 17:09:37] [DEBUG] Done downloading script at: "https://dl.dropboxusercontent.com/u/14997455/hifi/qatest/scriptfolder/entityScript.js"
[04/06 17:09:37] [DEBUG] Loading script at  QUrl("https://dl.dropboxusercontent.com/u/14997455/hifi/qatest/scriptfolder/scriptInDirBelow/script.js")
[04/06 17:09:38] [DEBUG] script:print()<< This is a script in a child directory
[04/06 17:09:38] [DEBUG] Loading script at  QUrl("https://dl.dropboxusercontent.com/u/14997455/hifi/qatest/scriptInDirDown.js")
[04/06 17:09:38] [DEBUG] script:print()<< This is a script in a directory up
[04/06 17:09:38] [WARNING] Script.include() ignoring file path QUrl("file:///C:/testEntityScript.js") outside of original entity script QUrl("https://dl.dropboxusercontent.com/u/14997455/hifi/qatest/scriptfolder/entityScript.js")
[04/06 17:09:38] [DEBUG] Loading script at  QUrl("https://dl.dropboxusercontent.com/u/14997455/hifi/qatest/scriptfolder/sameDirScript.js")
[04/06 17:09:38] [DEBUG] script:print()<< script in same dir
[04/06 17:09:38] [DEBUG] script:print()<< done
```

This QA is successful depending on if you want to be able to go a directory up and include a file from there. If not then I call this a QA fail for now.

**Comment by thoys** [comment]
Ah, sorry holdon, I noticed why it did access. I am testing it through weblinks DOH!

**Comment by thoys** [comment]
Re-testing with direct file links

**Comment by thoys** [comment]
Retested with local file links. This is definitely secure, but got the following ignore messages. While some of them are in the same folder.
```
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/scriptInDirBelow/script.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptInDirDown.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/testEntityScript.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/sameDirScript.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
````

**Comment by thoys** [comment]
@howard-stearns file:/// links were ignored in the same path ^ , QA fail for now

**Comment by howard-stearns** [comment]
Well that's weird.
As you noted @thoys, the first test was ok because it was through an http(s) url.
The second test should have rejected only "../scriptInDirDown.js" (which is really "up"), and "file:///C:/testEntityScript.js". Indeed, I get exactly the expected behavior (below).

I can't figure out how you got the log that you did in your "direct file links" test.
Can you post the actual section of the log, comparable to the span I have below? (i.e., from "Done downloading..." the entity script through "script:print()<< done")

[04/06 13:35:04] [DEBUG] Done downloading script at: "file:///c:/Users/howar/howardHiFi/examples/loader-test/thoys.js"
[04/06 13:35:04] [DEBUG] Loading script at  QUrl("file:///c:/Users/howar/howardHiFi/examples/loader-test/scriptInDirBelow/script.js")
[04/06 13:35:04] [DEBUG] script:print()<< This is a script in a child directory
[04/06 13:35:04] [WARNING] Script.include() ignoring file path QUrl("file:///c:/Users/howar/howardHiFi/examples/scriptInDirDown.js") outside of original entity script QUrl("file:///c:/Users/howar/howardHiFi/examples/loader-test/thoys.js")
[04/06 13:35:04] [WARNING] Script.include() ignoring file path QUrl("file:///C:/testEntityScript.js") outside of original entity script QUrl("file:///c:/Users/howar/howardHiFi/examples/loader-test/thoys.js")
[04/06 13:35:04] [DEBUG] Loading script at  QUrl("file:///c:/Users/howar/howardHiFi/examples/loader-test/sameDirScript.js")
[04/06 13:35:04] [DEBUG] script:print()<< script in same dir
[04/06 13:35:04] [DEBUG] script:print()<< done

**Comment by thoys** [comment]
Hi @howard-stearns , looking for it now.

**Comment by thoys** [comment]
Found it! At last!

```
[04/06 17:24:52] [DEBUG] Done downloading script at: "file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752"
[04/06 17:24:52] [DEBUG] Starting request for: https://s3.amazonaws.com/hifi-public/eric/models/shootingRange/monster1.fbx
[04/06 17:24:52] [DEBUG] Request finished for https://hifi-public.s3.amazonaws.com/models/content/SlidingDoorFrame2.fbx
[04/06 17:24:52] [DEBUG] Request finished for https://hifi-public.s3.amazonaws.com/models/content/SlidingGlassDoor.fbx
[04/06 17:24:52] [DEBUG] Request finished for https://s3.amazonaws.com/hifi-public/eric/models/shootingRange/monster1.fbx
[04/06 17:24:52] [DEBUG] Already downloading script at: "https://hifi-public.s3.amazonaws.com/eric/scripts/slidingdoor.js"
[04/06 17:24:52] [DEBUG] Already downloading script at: "https://hifi-public.s3.amazonaws.com/eric/scripts/slidingdoor.js"
[04/06 17:24:52] [DEBUG] Already downloading script at: "https://hifi-public.s3.amazonaws.com/eric/scripts/lightController3.js"
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/scriptInDirBelow/script.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptInDirDown.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/testEntityScript.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/sameDirScript.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/06 17:24:52] [DEBUG] script:print()<< done
```

**Comment by thoys** [comment]
That brings me to another issue. It seems that restarting or duplicating an entity with the same script ignore's includes.

**Comment by howard-stearns** [comment]
The overzealousness in rejecting includes was caused by our edit script adding query fragments to file urls (a separate ticket). I think it will work for you with the new build being generated.

Note however, that this PR does NOT address a separate lower-priority issue, in that the resolution of relative pathnames is essentially undefined. (There is a behavior, but it's so hard to explain that it might as well be undefined.) Thus, for your testing, you probably want to include full urls either directly or by using Script.resolvePath at top level (i.e., not in a callback).  When making use of the undefined behavior for unresolved relative pathnames, this PR should run on the side of caution. If it rejects a path that would be acceptable if resolved the way you might mean it (but which is perhaps not resolved that way in practice), it's still a pass. If the PR loads something it shouldn't, then that's a problem.

Note also that part of the intention of the PR is to catch some really crazy cases such as includes that happen inside timer callbacks, event handler callbacks, and the optional callback that can appear as the second argument of Script.include itself. Here you have found issues before even getting to the fancy stuff, which is great. Just sayin' that there's fancy stuff to cover, too.

Regarding the ignore of includes: It made debugging hard here, and it's a pain, but it is intentional in the case of two entity scripts that both include the same library file. It is intended to only include it once. On the other hand, not reloading includes (recursively) when you click "reload" is (in my opinion) a bug, but one that is difficult to fix and not a high priority.

**Comment by hifi-gustavo** [comment]
Build console output for commit: f35c59ce5f26b3258cb0369bc8f03b103321ddd3 available at: https://gist.github.com/9f995f1e24a5c41be072575244fb5f04<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7571.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7571.dmg

**Comment by thoys** [comment]
Will test now :)

**Comment by thoys** [comment]
great fix @howard-stearns 
```
[04/07 02:10:55] [DEBUG] Done downloading script at: "file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752"
[04/07 02:10:55] [WARNING] Invalid shader URL:  QUrl("")
[04/07 02:10:55] [WARNING] Invalid shader URL:  QUrl("")
[04/07 02:10:55] [DEBUG] Loading script at  QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/scriptInDirBelow/script.js")
[04/07 02:10:55] [DEBUG] script:print()<< This is a script in a child directory
[04/07 02:10:55] [WARNING] Script.include() ignoring file path QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptInDirDown.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/07 02:10:55] [WARNING] Script.include() ignoring file path QUrl("file:///C:/testEntityScript.js") outside of original entity script QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/entityScript.js?HFTime=14599561361752")
[04/07 02:10:55] [DEBUG] Loading script at  QUrl("file:///C:/Users/Thijs/Documents/Dropbox/Public/hifi/qatest/scriptfolder/sameDirScript.js")
[04/07 02:10:55] [DEBUG] script:print()<< script in same dir
[04/07 02:10:55] [DEBUG] script:print()<< done
```
QA pass :+1: , can we still add that bug post mvp?

**Pull request merged**
