### PR TITLE
more reticle improvements

### PR DESCRIPTION
**Pull request by ZappoMan**
- depth reticle added to defaultScripts
- If you haven't moved your mouse for over 3 seconds, and you're not pointing at some system window (like a dialog box, or menu) we will auto-hide it
- If you move your mouse again, we will show the reticle, and if in the HMD we will automatically "seek the mouse" to your HMD look at position.
- even if the reticle is visible, but you're in HMD, if you move your mouse quickly (shaking it) it will "seek the mouse" to your HMD look at position.
- fixes Reticle.visible in the desktop mode which wasn't working

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8de4a5907861d689c450bfc4f5ab45d9bb57e917 available at: https://gist.github.com/59db054baab738408bd2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4009f03c384a553dcb708941958f84df30da410f available at: https://gist.github.com/59db054baab738408bd2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.dmg

**Comment by ZappoMan** [comment]
I've noticed some weirdness with auto-hide...

**Comment by ZappoMan** [comment]
Fixes the following bugs:
- https://app.asana.com/0/26320649018758/92628920509298
- https://app.asana.com/0/26320649018758/95036254781064
- https://app.asana.com/0/26320649018758/95036254781059
- https://app.asana.com/0/26320649018758/94093626116232

**Comment by hifi-gustavo** [comment]
Build console output for commit: dc4c4e8c945ff284919e04877d2ffaa5c8a31425 available at: https://gist.github.com/59db054baab738408bd2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7222.dmg

**Comment by imgntn** [comment]
@ZappoMan this is amazing!  two observations:

1. it would be neat if after the mouse disappears and i'm looking away, a right click brought the mouse into view with the context menu open.  Moving seems to do this but not clicking
2. The time to settle down from the shaking might be a smidge long, before I knew that's what was happening i ran into it once and thought my mouse was freaking out (I had moved it in big movements and then small ones and it kept springing back to the same place).  I think if there's any downward wiggle room shortening that could help.

**Comment by ZappoMan** [comment]
Good feedback @imgntn - do you think the current behavior is acceptable? and your two suggestions can be treated as further bugs/refinements? Or do you believe the behaviors you describe are objectionable enough that it should block merging?

**Comment by imgntn** [comment]
i think they're non-blocking, although i bet the right click one will come up pretty quickly.

**Pull request merged**
