### PR TITLE
Add main & render thread ids to crashpad annotations

### PR DESCRIPTION
**Pull request by hyperlogic**
Also, make sure the username annotation is updated more frequently.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10600/HighFidelity-Beta-PR13381-8460144.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10600/HighFidelity-Beta-PR13381-8460144.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10600/HighFidelity-Beta-Interface-PR13381-8460144.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10600/HighFidelity-Beta-PR13381-8460144.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10600/HighFidelity-Beta-Interface-PR13381-8460144.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10613/HighFidelity-Beta-PR13381-2468922.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10613/HighFidelity-Beta-PR13381-2468922.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10613/HighFidelity-Beta-Interface-PR13381-2468922.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10618/HighFidelity-Beta-PR13381-8ddcff6.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10622/HighFidelity-Beta-PR13381-2feecf6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10618/HighFidelity-Beta-PR13381-8ddcff6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10618/HighFidelity-Beta-Interface-PR13381-8ddcff6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10622/HighFidelity-Beta-PR13381-2feecf6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10622/HighFidelity-Beta-Interface-PR13381-2feecf6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10622/HighFidelity-Beta-PR13381-2feecf6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10622/HighFidelity-Beta-Interface-PR13381-2feecf6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10618/HighFidelity-Beta-PR13381-8ddcff6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10618/HighFidelity-Beta-Interface-PR13381-8ddcff6.exe

**Comment by sethalves** [comment]
to test:
- use developer menu to force a crash
- find the crash in backtrace
- make sure the main and render threads are indicated in the attributes

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Crash appeared.

**Comment by conklin94122** [comment]
Both of the new attributes are present.

**Pull request merged**
