### PR TITLE
Remove mouse area for text fields. use activeFocusOnPress property in…

### PR DESCRIPTION
**Pull request by vladest**
…stead

Based on: https://highfidelity.fogbugz.com/f/cases/7973/Keyboard-focus-problems-within-Tablet-HUD

Test 
- Enable Commerce as described in the case
- Try to setup Wallet in Desktop mode
- on step 3 of 4 with "Got it" button 1st press outside wallet setup window (loose focus)
- Press "Got it"
- Press inside password input fileds
- Make sure input fields gained focus

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3757/HighFidelity-Beta-PR11490-01a0b26b90e4146857797f49f173ab9b2f7bc9b8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3757/HighFidelity-Beta-PR11490-01a0b26b90e4146857797f49f173ab9b2f7bc9b8.exe

**Comment by zfox23** [comment]
This is not the correct approach. Both of these properties are set to true by default; this is not the source of the focus problems.

Additionally, removing the messaging will prevent the keyboard from appearing in HMD, no?

**Comment by vladest** [comment]
@zfox23 the approach worked for me, is I understood way for reproduce correctly. If its still reproducible in some other way, please let me know

**Comment by zfox23** [comment]
@vladest it is not 100% reproducible; I do not have perfect reproduction steps. Restarting the Wallet setup process over and over (while attempting to switch focus) will absolutely eventually reproduce the problem, I just don't know when.

Additionally, this problem is not limited to the Wallet - I've seen it in the PAL as well (in the top left TextInput). I wish I could think of other examples right now.

I'm positive that this change is not a solution; this is something I tried during my development as well.

**Comment by vladest** [comment]
@zfox23 if you'll follow approach I've described in test steps, its 100% reproducible and provided patch fixed this. Now I'll check it on HMD as well. If its reproduced in some other way, probably there is more than one issue with focus and those issues must be fixed as well

**Comment by zfox23** [comment]
@vladest: Well, I'll be darned. I can't get it to break after your fix. I'm sorry for doubting you. Hopefully this will be all that is necessary.

The one thing this doesn't fix is that, after lowering the keyboard, the user can't raise the keyboard again without toggling focus or selecting another text field.

If you please, could you put semicolons after each line you added? I know that's not up to QML spec, but it's a style choice we made a while ago and we are trying to be consistent.

After you make that small change, I will merge this. Thanks.

**Comment by vladest** [comment]
@zfox23 yes, I've noticed this (rising keyboard an already focused textfield) as well. do you want me to work on this?

**Comment by zfox23** [comment]
@vladest That would be great, since this PR fixes one bug but creates a regression.

**Comment by vladest** [comment]
@zfox23 can you please then define requirements to the keyboard behavior to make sure I'll implement exactly what you want

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3763/HighFidelity-Beta-PR11490-7f6773b1f48925c84a940311cb204fcd41687dcd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3763/HighFidelity-Beta-PR11490-7f6773b1f48925c84a940311cb204fcd41687dcd.exe

**Comment by zfox23** [comment]
@vladest: Apologies for the delay - team lunch!

The behavior should be: If a text field is in focus, and the user presses the "lower keyboard" button, and then the user taps on the same text field that is currently in focus, the keyboard should be raised.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3780/HighFidelity-Beta-PR11490-9a00468ea9414e635fa99c072faab2e80720cb53.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3780/HighFidelity-Beta-PR11490-9a00468ea9414e635fa99c072faab2e80720cb53.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Enable Commerce as described in the case | Pass
Try to setup Wallet in Desktop mode | Pass
on step 3 of 4 with "Got it" button 1st press outside wallet setup window (loose focus) | Pass (Assume you mean 'Next'?)
Press "Got it" | Pass (Same as above)
Press inside password input fileds | Pass
Make sure input fields gained focus | Pass

One thing I noticed which seems to be fixed in a different PR #11495 was the Gray Security Image.

Additionally - I'm pretty sure this PR hasn't caused this but when in HMD Mode and enabling the Desktop Preview, clicking on buttons on the Wallet would sometimes (often) reset that option and I would have to go back in the menu to re-enable it. Clicking through other menus etc did not have this happen.

bug

**Comment by zfox23** [comment]
@cain-kilgore: The behavior you noticed is by design. When a user is entering their passphrase in HMD, we do not want snooping third parties to be able to get that passphrase by looking at the user's monitor (or worse, stream). The setting should revert to what it was before after passing the passphrase screen.

Thanks for the QA. 😊

**Comment by changxc** [comment]
thank u @vladest and @cain-kilgore !

**Pull request merged**
