### PR TITLE
Don't highlight entities during edit mode

### PR DESCRIPTION
**Pull request by druiz17**
Don't highlight entities during edit mode

Ticket - https://highfidelity.manuscript.com/f/cases/14774

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan (Desktop mode)
-    Navigate to a domain where you can create something
 -   Create a cube
  -  Note that it can be rotated on x and y coordinates at the default size
  -  Grab one of the resize cubes located at the corners of the cube.
  -  Increase the cube to a size larger than the area the direct-manipulators occupy
  -  You should be able to rotate the cube on X or Y axis using the direct manipulator

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9496/app_13100_PR_a57c72df6e4754e497f38827bfa888f954325212.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9496/HighFidelity-Beta-PR13100-a57c72df6e4754e497f38827bfa888f954325212.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9496/HighFidelity-Beta-Interface-PR13100-a57c72df6e4754e497f38827bfa888f954325212.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Able to edit cube when it's dimensions exceed the editing controls.

**Pull request merged**
