### PR TITLE
Validate user-supplied avatar height range before accepting

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Basic js sanity-checking of min & max heights.

https://highfidelity.manuscript.com/f/cases/15666/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11240/HighFidelity-Beta-PR13580-7455f9f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11240/HighFidelity-Beta-PR13580-7455f9f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11240/HighFidelity-Beta-Interface-PR13580-7455f9f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11240/HighFidelity-Beta-PR13580-7455f9f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11240/HighFidelity-Beta-Interface-PR13580-7455f9f.exe

**Comment by SimonWalton-HiFi** [comment]
I put the check in the settings.js file - I couldn't see a cleaner location for such input validation.

I've also fixed a couple of typos in the error strings and update the description to refer to height not scale.

The error alerting probably needs some design from the UX folk.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11251/HighFidelity-Beta-PR13580-beb878f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11251/HighFidelity-Beta-PR13580-beb878f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11251/HighFidelity-Beta-Interface-PR13580-beb878f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11251/HighFidelity-Beta-PR13580-beb878f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11251/HighFidelity-Beta-Interface-PR13580-beb878f.exe

**Comment by SimonWalton-HiFi** [comment]
## Test Plan

- Run the domain server locally.
- Access its web interface via the URL http://localhost:40100/ .
- Go to Settings -> Avatars.
- Enter invalid height limits, ie. some combination of max < min, min < 0.009, max > 1755, as well as valid height limits.
- Click on `Save and restart`.

Before this PR Save and restart will work for invalid values with no diagnostics presented. With this PR Save and restart will not proceed for such values; an alert box will be brought up detailing the issue(s); the invalid fields will be highlighted. Min equal to max should be allowed. Valid limits should work as before.

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Alert box appears and stops the invalid values.

**Comment by divyaelango88** [comment]
🎉

**Comment by SimonWalton-HiFi** [comment]
There was some question about where the limits come from. Previously avatar heights were handled as scales rather than absolute amounts and scales are still used in the avatar render library. The max comes from 1000 x 175.5 cm (average male height). This is given in libraries/shared/src/AvatarConstants.h.

**Pull request merged**
