### PR TITLE
fix new model path(RC63)

### PR DESCRIPTION
**Pull request by druiz17**
fix new model path

ticket - https://highfidelity.manuscript.com/f/cases/11849/RC63-New-Model-dialog-fails-to-appear

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
2) Go to the sandbox or another domain in which you can edit
3) Open Create
4) Click Model
5) New model dialog should load.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6692/app_12282_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6692/HighFidelity-Beta-PR12282-08511a2a2ef779874154519c2c80ed0dc912903f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6692/HighFidelity-Beta-PR12282-08511a2a2ef779874154519c2c80ed0dc912903f.exe

**Comment by EthanMaasdam** [comment]
*PASS*

**Pull request merged**
