### PR TITLE
BUGZ-363: Remove 20dB output attenuation during PTT

### PR DESCRIPTION
**Pull request by zfox23**
[BUGZ-363](https://highfidelity.atlassian.net/browse/BUGZ-363)

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
:heart:

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20172/HighFidelity-Beta-PR15847-7c189d4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20172/HighFidelity-Beta-Interface-PR15847-7c189d4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20172/HighFidelity-Beta-PR15847-7c189d4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20172/HighFidelity-Beta-Interface-PR15847-7c189d4.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20172/HighFidelity-Beta-PR15847-7c189d4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20172/HighFidelity-Quest-Beta-PR15847-7c189d4.apk)

**Pull request merged**
