### PR TITLE
Prevent avatars with missing "Hips" joints from causing crashes

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://highfidelity.fogbugz.com/f/cases/1279/avatar-related-crashes-in-alpha-meeting

**Comment by hyperlogic** [comment]
Testplan: 
  * open avatar settings and switch to the following avatar: http://blackbear.dnsalias.com/public/a_horse_white04.fst
  * your client should no longer crash.
  * other clients should also no longer crash when viewing the horse avatar

:warning: you will likely have to work around this [bug](https://highfidelity.fogbugz.com/f/cases/1245/Crash-on-Avatar-Change), which is being addressed seperately.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3b14988577f511f598db433717c80ba95c371f12 available at: https://gist.github.com/9720912cdffdea4fd05fa1326d947e6e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8299-3b14988.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8299-3b14988.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Testing Windows 10

Test 1 - Test AV model on RELEASE-5193

With test AV specified, current release either crashes on launch, or, loads but presents a distorted horse AV that eventually crashes.

Test 2 - Test AV model on PR-8299

No crash on launch, move or close.  I'm guessing this AV is meant to have default animations overridden.  

Test 3 - Viewing test AV from second client.  I was unable to crash my second client (on different machine in same domain) while viewing test model with release or this PR.  It *will* crash second client when changing AV as it will primary - related to other bug.

**Pull request merged**
