### PR TITLE
Fix a bug when using the gpu::Batch::_glUniform*() calls  with a bad location

### PR DESCRIPTION
**Pull request by samcake**
When using the _glUnfirm calls on the gpu::Batch with a bad location (unknown from the shader uniforms) then in the corresponding glBackend::do_glUniform*() we are going through the uniform bindding mapping table in the GLShader looking for the invalid location. this would return 0 by default which could cause bad effects,
Did a more conservative test instead to avoid the behavior.

Test Plan:
Smoke test in desktop and hmd should be good.

Potentially this is the root cause for some of the recent bugs happening in the current RC.
SInce i don;t have a definitive repro for it (try going to eschatology...?) i wasn;'t able to confirm that theory.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3d291871565ca77e0ed0e1df4d3c08dc22a3da72 available at: https://gist.github.com/e6d1766e60fb3e2c2fc4e3ff0f0dce4f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9134-3d29187.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9134-3d29187.dmg

**Comment by Nex-Pro** [comment]
### PR #9134

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive



## QA Test
**QA Tester**: **Piper.Peppercorn**
**localhost 'createTestBlocks.js' Result**:  **SUCCESS**
**localhost ATP Upload + Edit Result**: **SUCCESS**
**Echo Server Audio**: **Echo Server Audio** **FAILURE**
**localhost 'harmonicOscillator.js' Result**: **UNTESTED**
**localhost 'reverbTest.js' Result**: **SUCCESS**
**localhost 'playaPerformanceTest.js' Result**: **SUCCESS**
**dev-playa 'playaPerformanceTest.js' Result**: **SUCCESS**
**dev-demo 'playaPerformanceTest.js' Result**: **SUCCESS**

**QA Pass**: 
### FAIL

**Additional Test Results + Observations**:
 **Unable to get Echo server audio to work. Works fine in current release. Tried multiple times including checking all audio settings.**


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |89 |90 |90
**Present New Rate**: |89 |90 |89
**CPU Buffer Count**: |3010 |4450 |4200
**GPU Buffer Count**: |917 |1002 |897
**CPU Memory Usage**: |45645072 |77534064 |70803984
**GPU Memory Usage**: |18786416 |33941616 |24111216
**CPU Texture Count**: |272 |275 |282
**GPU Texture Count**: |230 |188 |202
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |58174640 |303533328 |271494416
**GPU Texture Memory Usage**: |966771605 |1164197418 |1002917688
**GPU Virtual Memory Usage**: |1213795980|1418813326|1257222432
**Triangle Count**: |554235 |2416359 |769552
**Triangle Rate**: |46186250 |219669000 |69959272
**API Drawcall Count**: |195 |315 |232
**Drawcall Count**: |6000 |702 |654
**Drawcall Rate**: |500000 |63818 |59454
**State Changes Texture Count**:|372 |361 |317
**Pipeline Count**: |70 |39 |53
**Item Opaques**: |271 |563 |267
**Item Translucents**: |100 |75 |78
**Item Lights**: |11 |54 |44
**Timing Opaques**: |0.831 |1.408 |0.868
**Timing Translucents**: |0.17 |0.111 |0.143
**Timing Lighting**: |0.024 |0.019 |0.017
**Render Frame**: |2.181 |3.49 |2.073

**Comment by Nex-Pro** [comment]
I realise that this should likely not touch the audio but it should be checked by other testers. I have not had a fail to echo server audio before. I could see my mic level and hear local sounds during the tests. With the correct ( normal for my system ) settings echo server audio worked in the current RC.
So this is an odd one.

**Comment by OmegaHeron** [comment]
Testing Windows 10

Unable to reproduce audio issue - works as expected for me on server echo back.  Checked that all my audio devices show up as normal and looked at some other audio diagnostic data -- all looks normal here.  Should probably get a few more test persons on it to be sure, but, likely culprit - if there's a problem, is recent PR that touched how DLLs are installed for audio #9129.

**Pull request merged**
