### PR TITLE
Move crash menu items to submenu and add new crash types

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c1277ae7a21bbe58cfede88ff3349e06762e965 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0c1277ae7a21bbe58cfede88ff3349e06762e965 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91da4229ace5f76a9887f2345aff9e9e0d53a1c5 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by huffman** [comment]
For whoever tests this, I will need you to also test https://github.com/highfidelity/hifi/pull/7639 after this PR is merged. This adds a bunch of different crash types to the developer menu. It would be great if you could take note of which crashes cause the BugSplat crash reporter to be shown, and which don't. Later we will compare those results against https://github.com/highfidelity/hifi/pull/7639 

To test:
1. For each crash type in Developer -> Crash -> ..., (other than deadlock) run interface and take note of whether executing that crash shows the BugSplat crash reporter.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fa49c213cc59ed4cafc7bbed1d9a305b758b3055 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e563de9ef8f1d16532df238fea3a36431f7984f2 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by huffman** [comment]
fixing...

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc247ec0580fc083152051c115cdaf9255ab4c89 available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 47c2a1722b23d68cddadf16d3a73e9e717f4d04e available at: https://gist.github.com/aef1103271a863bfe80831637c5da411<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7652.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7

New crash menu shows proper under Developer.

Pure Virtual Function Call - Leads to Windows message box, no bugsplat
Pure Virtual Function Call Threaded - Leads to Windows message box, no bugsplat
Double Free - Leads to Windows message box, no bugsplat
Double Free Threaded - Leads to Windows message box, no bugsplat
Abort - Presented bugsplat
Abort Threaded - Leads to Windows message box, no bugsplat
Null Dereference - Presented bugsplat
Null Dereference Threaded - Leads to Windows message box, no bugsplat
Out of Bounds Vector Access - Presented bugsplat
Out of Bounds Vector Access Threaded - Leads to Windows message box, no bugsplat
New Fault - Presented bugsplat
New Fault Threaded - Presented bugsplat

**Comment by huffman** [comment]
Interesting, that mostly matches up with what I saw other than abort being caught and new fault (threaded) being caught. The latter would depend on whether certain web elements are initialized, which registers a new fault handler. The abort is likely a similar scenario.

re: previous settings, I suspect this is an existing bug. I'll report it.

**Pull request merged**
