### PR TITLE
case 20919: Fix edit in release grab

### PR DESCRIPTION
**Pull request by sethalves**
https://highfidelity.manuscript.com/f/cases/20919/position-edits-inside-releaseGrab-entity-method-fail
http://roadmap.highfidelity.com/bugs/p/entity-properties-not-set-in-vr

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16926/HighFidelity-Beta-PR14814-30d9fe7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16926/HighFidelity-Beta-PR14814-30d9fe7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16926/HighFidelity-Beta-Interface-PR14814-30d9fe7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16926/HighFidelity-Beta-PR14814-30d9fe7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16926/HighFidelity-Beta-Interface-PR14814-30d9fe7.exe

**Comment by JeffClinton** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17042/HighFidelity-Beta-PR14814-30d9fe7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17042/HighFidelity-Beta-PR14814-30d9fe7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17042/HighFidelity-Beta-Interface-PR14814-30d9fe7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17042/HighFidelity-Beta-PR14814-30d9fe7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17042/HighFidelity-Beta-Interface-PR14814-30d9fe7.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
