### PR TITLE
fix bug: interface sends too many updates on settle

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9227/app_13013_PR_03e03727dbfa7ca30996419821faf7f65f6a1678.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9227/HighFidelity-Beta-PR13013-03e03727dbfa7ca30996419821faf7f65f6a1678.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9227/HighFidelity-Beta-Interface-PR13013-03e03727dbfa7ca30996419821faf7f65f6a1678.exe

**Comment by AndrewMeadows** [comment]
The internal bug is here: https://highfidelity.manuscript.com/f/cases/14617

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Upload and download icons respond accordingly and look good to all users.

**Comment by AndrewMeadows** [comment]
It is a little late, but I submitted an internal "test case" for this issue:

https://highfidelity.testrail.net/index.php?/cases/view/16179

**Pull request merged**
