### PR TITLE
TEAM TEACHING : Improving the transparent rendering

### PR DESCRIPTION
**Pull request by samcake**
- THis work move the rendering of the transparent objects after the gBuffer opaque layer is fully lit.
THis provide a clean correct rendering of the opaque layer
THe transparent objects are blended from back to front according to the opacity blending. There still would be issues with resolving transparency within one transparent object with overlapping but this will be solved in a future sprint.

- The transparent object are rendered and lit solely by the key light and not affected by the spherical harmonics yet.

- Moved the definition of GPUObject to Format.h for visibility of all the gpu classes more easily

- Removed the "post LIghting Objects" from the deferred lighting effect as this has never been used and won;t work with the new technique used 

- the Glowing effect is maybe affected by this, will need to be checked

### CODE REVIEW

**Comment by samcake** [comment]
This won't work correctly on Mac currently fixing on Mac

**Comment by hifi-gustavo** [comment]
Build console output for commit: c47cee3f3bdc14ec8788b859ce823d1d6d16256b available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7d88e264210b807d9489cf32f7e9600f6398961 available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 862d6abd796d486014c05b872be52fec6de7532f available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a93db6f5abfb82a286fcb2779b2e3e2a1a32506 available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bff9a17e180bec94f6621929b8d71e74ea79c87 available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Comment by samcake** [comment]
good to go

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e351c032896b6b5d47c25925ebb732d9b860c58 available at: https://gist.github.com/31c01ff98102fc95d015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5069.dmg

**Pull request merged**
