### PR TITLE
triggering change

### PR DESCRIPTION
**Pull request by howard-stearns**
Remove hysteresis in triggering on HUD elements, so that when you get the "up" event when you feel the detent while letting go.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd1780efefc1f0ad1a8cbad53e98f08631ecfbb0 available at: https://gist.github.com/a12e4126e0b7baf5f0b373ee0ba8e8e1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8106.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8106.dmg

**Comment by howard-stearns** [comment]
test plan
Click and drag on hud elements when using vive or hydra hand controllers.
Buttons and such are still as they were with mouse (action on release), but the release is just a little release, around where the vive detent is.

**Comment by howard-stearns** [comment]
Code review note: most of this was no-op cleanup. That was the first checkin, if you want to look at that separately from the "No hysteresis" checkin.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bfb697bc7789f5cd6dbb073be47f846fc39a66da available at: https://gist.github.com/a12e4126e0b7baf5f0b373ee0ba8e8e1<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8106.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8106.dmg

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yfPiz3sT&#x2F;33-add-equip-hotspots"> Add Equip-Hotspots</a>

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;S1dbA1Lg&#x2F;32-remove-the-grip-button"> Remove the Grip Button</a>

**Comment by RyanDowne** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HzeSGxgB&#x2F;46-what-to-do-about-buttons-acting-on-trigger-vs-release-different-answers-for-our-tray-buttons-vs-inside-of-qml-or-do-we-need-to-r"> what to do about buttons acting on trigger vs release? Different answers for our tray buttons vs inside of qml, or do we need to rethink all qml refs?</a>

**Pull request merged**
