### PR TITLE
16683 Avatar App - Add to Favorites Button Not Working

### PR DESCRIPTION
**Pull request by sethalves**
to test, see https://github.com/highfidelity/hifi/pull/13605

https://highfidelity.fogbugz.com/f/cases/16660/avatar-settings-not-accessible
https://highfidelity.fogbugz.com/f/cases/16683/Avatar-App-Add-to-Favorites-Button-Not-Working
https://highfidelity.fogbugz.com/f/cases/16661/Avatar-App-Older-avatar-favorites-do-not-appear-in-the-avatar-app

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11300/HighFidelity-Beta-PR13607-0ceb7c7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11300/HighFidelity-Beta-PR13607-0ceb7c7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11300/HighFidelity-Beta-Interface-PR13607-0ceb7c7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11300/HighFidelity-Beta-PR13607-0ceb7c7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11300/HighFidelity-Beta-Interface-PR13607-0ceb7c7.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Avatar app works as expected when using the avatar bookmarks in the test plan!

I had not previously seen these issues, so I tried the same file on the current RC70 build, whic broke.

**Pull request merged**
