### PR TITLE
Disable the ability for a user to edit default scripts if developer settings is not enabled

### PR DESCRIPTION
**Pull request by druiz17**
Disable the ability for a user to edit default scripts if developer settings is not enabled

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan (test in toolbar mode and tablet mode)
- Do not have developer menu selected
- Open RuningScripts dialog
- add some extra scripts running
- controller.js and defaultScripts.js should have a lock icon on them.
- Click on the icon and a window should pop up describing why they are lock (note: Tablet mode-the message pops up in the tablet. Toolbar mode, it pops up in a new window)
- close the message, and click reload all and remove all buttons. controller.js and defaultScripts.js should not be reloaded or deleted.
- reload some extras scripts
- enable developer menu
- see that the reload and delete icons appear for controller.js and defaultScripts.js, Also the reload default button should appear as well.
- reloading and deleting controller.js and defaultScripts individually should work and also with the reload all and remove all buttons

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1873/HighFidelity-Beta-PR11026-95299244cff15e8e418603f46a0e274eaf2d9351.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1873/HighFidelity-Beta-PR11026-95299244cff15e8e418603f46a0e274eaf2d9351.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Do not have developer menu selected
Open RuningScripts dialog **Check**
add some extra scripts running **Check (Request.js and Vec3.js)**
controller.js and defaultScripts.js should have a lock icon on them. **Check**
Click on the icon and a window should pop up describing why they are lock (note: Tablet mode-the message pops up in the tablet. Toolbar mode, it pops up in a new window) **Check**
close the message, and click reload all and remove all buttons. controller.js and defaultScripts.js should not be reloaded or deleted. **Check**
reload some extras scripts **Check (previous + actioninspector.js)**
enable developer menu **Check**
see that the reload and delete icons appear for controller.js and defaultScripts.js, Also the reload default button should appear as well. **Check**
reloading and deleting controller.js and defaultScripts individually should work and also with the reload all and remove all buttons **Check, also reloading defaults brings back the 2 primary .js' as expected**

**Pass?. (See Notes!!)**

Notes: Experienced 2 crashes on start to black screen which I believe is a current master issue as-well but also crashed when I selected the mute button on tablet? (Logs attached at bottom of this comment) I know the black screen is a current issue but not sure if crashing with mute button was a fluke, master or PR related. The issue occurred after changing the toolbar to tablet, all apps were missing and just the audio was clickable, clicked Mute on it and insta-crash. @druiz17 Please let me know your thoughts as not sure if that could be PR specific.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2182/HighFidelity-Beta-PR11026-51652482a46a5b09a5eec80cbb7573524ab38bb4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2182/HighFidelity-Beta-PR11026-51652482a46a5b09a5eec80cbb7573524ab38bb4.exe

**Comment by anshuman64** [comment]
@YuppyPlays Can you please retest this? We merged in a fix for the blank tablet, so that shouldn't happen anymore. Let us know if you crash again--we'll find the bugsplat and troubleshoot--or if there are any other problems with this PR.

**Comment by YuppyPlays** [comment]
No problem, as soon as Windows build becomes available I will be on it :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2203/HighFidelity-Beta-PR11026-90db4aa9c039f65475668f6f842699146a0c0265.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2203/HighFidelity-Beta-PR11026-90db4aa9c039f65475668f6f842699146a0c0265.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:
Everything passed except this time after removing all and then pressing reload all, it doesn't bring up the 2 primary scripts, not sure if this is an issue or not given it's a developer feature.

Tried to repro the issue in this new build, appears to be resolved. No more crash :)

**Comment by anshuman64** [comment]
@druiz17 Everything works great, but we also want the "Load Defaults" button to be on the top row in the same line as "Reload All" and "Remove All". See the mock-up on the ticket: https://highfidelity.fogbugz.com/f/cases/4874/Default-Scripts-shouldn-t-be-easy-to-delete

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2217/HighFidelity-Beta-PR11026-1e1ddf294154d80eec082a44bf30562f5edc303c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2217/HighFidelity-Beta-PR11026-1e1ddf294154d80eec082a44bf30562f5edc303c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2261/HighFidelity-Beta-PR11026-9be60ee6584e4479ca31f80ef8f42abad0f7bfd7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2261/HighFidelity-Beta-PR11026-9be60ee6584e4479ca31f80ef8f42abad0f7bfd7.exe

**Comment by anshuman64** [comment]
Closed in favor of #11120

**Pull request closed without merging**
