### PR TITLE
Experimental HRTF with distance-based lowpass filter (do not merge)

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21487/HighFidelity-Beta-PR16184-c1bae99.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21487/HighFidelity-Quest-Beta-PR16184-c1bae99.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21487/HighFidelity-Beta-PR16184-c1bae99.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21487/HighFidelity-Beta-Interface-PR16184-c1bae99.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21487/HighFidelity-Beta-PR16184-c1bae99.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21487/HighFidelity-Beta-Interface-PR16184-c1bae99.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21657/HighFidelity-Beta-PR16184-7440ac1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21657/HighFidelity-Quest-Beta-PR16184-7440ac1.apk)

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21670/HighFidelity-Beta-PR16184-7440ac1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21670/HighFidelity-Quest-Beta-PR16184-7440ac1.apk)

**Comment by kencooke** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21702/HighFidelity-Beta-PR16184-7440ac1.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21702/HighFidelity-Quest-Beta-PR16184-7440ac1.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21702/HighFidelity-Beta-PR16184-7440ac1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21702/HighFidelity-Beta-Interface-PR16184-7440ac1.dmg

**Pull request closed without merging**
