### PR TITLE
Avatarapp: base 'SquareLabel' on button from Uit

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/16990/Avatar-app-make-the-two-blue-buttons-conform-with-UI-toolkit-and-add-sound

**Test plan**

1. Open avatarapp
2. Ensure 'specify avatar URL' button and 'adjust wearables button' looks / behaves like ordinary button (has hover/click states, has sound on hover/click)

image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11493/HighFidelity-Beta-PR13668-e151bd4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11493/HighFidelity-Beta-Interface-PR13668-e151bd4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11493/HighFidelity-Beta-PR13668-e151bd4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11493/HighFidelity-Beta-Interface-PR13668-e151bd4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11710/HighFidelity-Beta-PR13668-e151bd4.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11710/HighFidelity-Beta-PR13668-e151bd4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11710/HighFidelity-Beta-Interface-PR13668-e151bd4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11710/HighFidelity-Beta-PR13668-e151bd4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11710/HighFidelity-Beta-Interface-PR13668-e151bd4.dmg

**Comment by qlimguicheteau** [comment]
PASS
@conklin94122 
Buttons properly Highlight, Trigger, and have standardized Sounds for
-HMD Mouse
-HMD Laser
-Desktop Mouse

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11732/HighFidelity-Beta-PR13668-6e6eae2.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11732/HighFidelity-Beta-PR13668-6e6eae2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11732/HighFidelity-Beta-Interface-PR13668-6e6eae2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11732/HighFidelity-Beta-PR13668-6e6eae2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11732/HighFidelity-Beta-Interface-PR13668-6e6eae2.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Button works well across all views.

**Pull request merged**
