### PR TITLE
BUGZ-820: Remove QT_CMAKE_PREFIX_PATH prod hack

### PR DESCRIPTION
**Pull request by Atlante45**
[Jira ticket](https://highfidelity.atlassian.net/browse/BUGZ-820)

This also updates the qt 5.12.3 archive for ubuntu 16.04 to one that contains symbols.

**NEEDS** to be merged at the same time as https://github.com/highfidelity/hifi-ci/pull/1459

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20220/HighFidelity-Beta-PR15873-c7442e3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20220/HighFidelity-Beta-Interface-PR15873-c7442e3.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20220/HighFidelity-Beta-PR15873-c7442e3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20220/HighFidelity-Quest-Beta-PR15873-c7442e3.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20220/HighFidelity-Beta-PR15873-c7442e3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20220/HighFidelity-Beta-Interface-PR15873-c7442e3.exe

**Comment by shanzzam** [comment]
@Atlante45 is still doing work on this. Please don't merge until a convo has been had in a dev channel.

**Pull request merged**
