### PR TITLE
Allow scripts to force a refresh of a resource URL

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Any cache that is exposed to the scripting layer should now be able to have an item cleared from the cache and potentially re-downloaded.  You can trigger the refresh of an item by using the function `refresh` on a cache object inside a script or inside the console.

For instance 

    ModelCache.refresh(
        "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/" +
        "Junkyard/Models/neonSigns/austinsatomiceats.fbx")

or

    ModelCache.refresh("atp:/terrain/TileLrg120x120_2.fbx")

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0397a22ecbf1f3173f8495b083cc3e41b7d3876a available at: https://gist.github.com/cef7abf1bc2325c17dc1ea4fe1a71b57<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8262-0397a22.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8262-0397a22.dmg

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Ran ```ModelCache.refresh(
    "https://s3-us-west-1.amazonaws.com/hifi-content/DomainContent/" +
    "Junkyard/Models/neonSigns/austinsatomiceats.fbx")``` and attempted several times to recache the object however it did not work.  Gyazo included.  If there is something I am missing please let me know and I can re-test.
[https://gyazo.com/95bf487fda852cef28d36c16824268ad](https://gyazo.com/95bf487fda852cef28d36c16824268ad)

**Comment by jherico** [comment]
@kevinmthomasse  I'm fairly certain this isn't a valid test, because the actual network asset isn't changing.  Bear in mind that what is most likely happening is that the network asset is being ejected from the resource cache, which is then requesting it again.  I believe that until it has the 'new asset' it will continue to render the old one.  However, the client is going to ask S3 for the asset and S3 is going to tell the client that it hasn't changed, so it's just going to reload the same file from the disk cache.  

I'm doing a test right now using my personal S3 bucket to verify it works as expected if the server object has changed.

**Comment by jherico** [comment]
@kevinmthomasse never mind, it's not behaving quite the way I expect, so I'll have to take a look at it in more detail later.

**Comment by kevinmthomasse** [comment]
@jherico no problem I will standby to re-test.

**Pull request closed without merging**
