### PR TITLE
Increase ping interval for unconnected Nodes

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Current rate of 40 Hz seems overkill for keeping NAT holes open.

https://highfidelity.fogbugz.com/f/cases/22178/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18699/HighFidelity-Beta-PR15375-a5e94ee.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/18699/HighFidelity-Beta-Interface-PR15375-a5e94ee.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18699/HighFidelity-Beta-PR15375-a5e94ee.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/18699/HighFidelity-Beta-Interface-PR15375-a5e94ee.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18699/HighFidelity-Beta-PR15375-a5e94ee.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/18699/HighFidelity-Quest-Beta-PR15375-a5e94ee.apk)

**Comment by howard-stearns** [comment]
[Hero Improvements @ scale](https://trello.com/c/vJoTwMci/1-hero-improvements-scale)

**Pull request merged**
