### PR TITLE
Case 21397: Trying to fix overlay rotation

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21397/nametag-rotation-for-81

Test plan:
- Verify that the nametag script from the marketplace works.
- Verify that the tablet is rotated properly when you open it.
- Verify that notifications appear correctly in HMD

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17571/HighFidelity-Beta-PR15012-8058ad8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17571/HighFidelity-Beta-Interface-PR15012-8058ad8.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17577/HighFidelity-Beta-PR15012-8058ad8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17577/HighFidelity-Beta-Interface-PR15012-8058ad8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17577/HighFidelity-Beta-PR15012-8058ad8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17577/HighFidelity-Beta-Interface-PR15012-8058ad8.exe

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17597/HighFidelity-Beta-PR15012-8058ad8.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17597/HighFidelity-Quest-Beta-PR15012-8058ad8.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17597/HighFidelity-Beta-PR15012-8058ad8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17597/HighFidelity-Beta-Interface-PR15012-8058ad8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17597/HighFidelity-Beta-PR15012-8058ad8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17597/HighFidelity-Beta-Interface-PR15012-8058ad8.exe

**Pull request merged**
