### PR TITLE
fix the rendering of wireframe for model entities with bad model URLs

### PR DESCRIPTION
**Pull request by ZappoMan**
test plan - https://highfidelity.testrail.net/index.php?/tests/view/6116

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4316/HighFidelity-Beta-PR11638-ef0ff96a4432fa223a03b0e89073943b4d422f67.dmg

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4317/HighFidelity-Beta-PR11638-27ffb97a076ada763178c439db05e0e6f0485198.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4317/HighFidelity-Beta-PR11638-27ffb97a076ada763178c439db05e0e6f0485198.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Results added to TestRail (**Fail**)

**Comment by ZappoMan** [comment]
"Nothing appears and the properties shows everything greyed out with no wireframe/bounding box in sight, nor any models showing in CREATE list."

@YuppyPlays er... this seems weird.. I sounds like you didn't actually create a model. What exactly did you do?

That sounds like you basically don't have an object selected

**Comment by YuppyPlays** [comment]
@ZappoMan 

Apologies about that, just gave it another go, it appears my initial thought of having an empty URL still create a model was unfounded :joy:
Re-tested, I can't seem to edit the TestRail results (Still learning how it work) but can confirm here all steps are a **Pass**

**Pull request merged**
