### PR TITLE
raise max mesh count for static collision entities from 500 to 1000

### PR DESCRIPTION
**Pull request by sethalves**
- raise max mesh count for static collision entities from 500 to 1000

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- same test as https://github.com/highfidelity/hifi/pull/9994

**Comment by sethalves** [comment]
I fell down the git-hole and accidentally made https://github.com/highfidelity/hifi/pull/10005 useless.  I'm relaying clement's dev-approval over to this one.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c21b8b4eacb52ece02c655fb15cf72543364b727 available at: https://gist.github.com/ad560169b219f37319b5f3dc5bbdf510<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10012-c21b8b4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10012-c21b8b4.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Repeated test of 9994 + general smoke tests.

**Pull request merged**
