### PR TITLE
Fix 'Import Entities' causing error when cancelling

### PR DESCRIPTION
**Pull request by huffman**
https://app.asana.com/0/26224634468389/83411498395212

### CODE REVIEW

**Comment by huffman** [comment]
Repro on Windows 10:
Load script at https://rawgit.com/huffman/hifi/fix-edit-import-cancel/examples/edit.js
Edit > Import Entities
File browser should pop up, click "Cancel"
The dialog should go and you should *not* get an error

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9a2af26906c9340c216efa21465d821fe397a34f available at: https://gist.github.com/cf31940dbddb25c76015<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6984.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6984.dmg

**Comment by selart** [comment]
Tested, works correctly

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
Works fine for me, tested with the mentioned edit.js and then did edit > import entities and then I hit cancel. I received no error. I say PASSED

**Pull request merged**
