### PR TITLE
Context Overlay (i) Position Fix

### PR DESCRIPTION
**Pull request by zfox23**
order of operations lol

# What's New
- Fix a bug that caused (i) Context Overlay to sometimes appear off-screen

# Known Issues/Incomplete
- N/A

# Future Work
- N/A

# Test Plan

## Prerequisites

Currently, you must manually enable "commerce" by adding `"commerce": true,` in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating `Settings.setValue("commerce", true)` and restarting.

If your wallet is already set up OR if you have previously set up a wallet on a different build (and thus you have a record of your wallet on the backend), you must perform the following steps to rest your wallet:
1. Open the Wallet app. If you're just resetting your wallet because there's a record of a previous wallet on the backend, go through setup.
2. Go to the "Help" tab in the Wallet app
3. Press the red "DBG: RST Wallet" button at the top of the window

If your wallet is set up but broken (e.g., from testing something that didn't work) such that you are prompted for a passphrase that is never accepted, you need to:
1. Quit interface and delete `%appdata%/Interface <build #>/<username.hifikey>`
2. Restart Interface, set up wallet, and then press the red `DBG: RST WALLET` button as above. Now you are in a truly clean state for wallet setup.

## Tests
1. Launch Interface
2. Set up your Wallet if it isn't already set up
3. Buy the "Test Beach Ball" from the Marketplace, then rez it in front of you
4. In Desktop mode, right click the Test Beach Ball entity. Verify that you see an orange edge highlight around the entity, and that you see an (i) Context Overlay very close to (but not completely obscuring) the Test Beach Ball
5. In Desktop mode, move around the Test Beach Ball - get big, get small, move far away, move close - and right click the Test Beach Ball as you move around. Verify that the position of the (i) Context Overlay is always "reasonable".
6. Don your HMD.
7. Move around the Test Beach Ball - grab it and inspect it, get big, get small, move far away, move close - and use your blue laser to hover over the Test Beach Ball for a half second as you move around. Verify that the position of the (i) Context Overlay is always "reasonable".

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4319/HighFidelity-Beta-PR11639-61a12a70c0dd6d1b5f7d51878e95354875c11178.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4319/HighFidelity-Beta-PR11639-61a12a70c0dd6d1b5f7d51878e95354875c11178.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by Nex-Pro** [comment]
@zfox23 I've been nagging you about this one !  lol

**Comment by zfox23** [comment]
@Nex-Pro YOU'RE TOTALLY RIGHT AND *I'M SORRY*!!! :joy:

An unnecessary explanation: I thought you were always referring to (i) problems due to the fact that the (i) sometimes appears in the "wrong" spot because there are edge cases we specifically DIDN'T design for. HOWEVER, you were right the whole time - I implemented the design incorrectly from the start, causing the (i) to appear in the wrong spot because of a *bug*.

Well, it's fixed now, in any case. :)

**Comment by YuppyPlays** [comment]
Testing complete:

Launch Interface **Check**
Set up your Wallet if it isn't already set up **Check**
Buy the "Test Beach Ball" from the Marketplace, then rez it in front of you **Check**
In Desktop mode, right click the Test Beach Ball entity. Verify that you see an orange edge highlight around the entity, and that you see an (i) Context Overlay very close to (but not completely obscuring) the Test Beach Ball **Check**
In Desktop mode, move around the Test Beach Ball - get big, get small, move far away, move close - and right click the Test Beach Ball as you move around. Verify that the position of the (i) Context Overlay is always "reasonable". **Check**
Don your HMD. **Check**
Move around the Test Beach Ball - grab it and inspect it, get big, get small, move far away, move close - and use your blue laser to hover over the Test Beach Ball for a half second as you move around. Verify that the position of the (i) Context Overlay is always "reasonable". **Check**

**Notes: The "i" context overlay always resizes to be the same size relative to player view/distance, but always goes in the same place, I personally feel this is correct but wanted to note it in-case this is considered incorrect.**
image

**Pass** :D

**Comment by zfox23** [comment]
you da man, @YuppyPlays !

**Pull request merged**
