### PR TITLE
Beta Release 45 - Includes up to Developer Release 6767 

### PR DESCRIPTION
**Pull request by cozza13**
- Fixed a bug where custom port wasn't used in AC when passed through CLI 
 - Remove /tutorial in favor of new repo 
 - Revamp audio device selection
 - Fixed a bug where you could not print polaroids if you took a gif 
 - Ensure desktop dialogs' title bars are visible 
 - Fix teleporting to another user from the PAL 
 - Prevent deadlocks from different locking orders in FileCache 
 - Fix tablet buttons qt59
 - Baked shortBow's textures. 
 - Domain server settings will now tell user if saving will restart DS 
* Move `RenderArgs` out of `shared` and into `render`
  * `RenderArgs` required bizarre amounts of forward declarations because the concept of rendering was baked into the `OctreeRenderer` class (see below).
* Remove `RenderArgs::_whiteTexture`
  * This member was used in a few places to 'reset' a texture slot, but it was nowhere initialized, so it was always empty.  Where it was previously referenced, we're now explicitly setting the texture to nothing.
* Remove `QSharedPointer<OctreeRenderer> RenderArgs::_renderer;` in favor of `        `QSharedPointer<QObject> RenderArgs::_renderData;`
  * The `_renderer` type was always cast to a `QSharedPointer<EntityTreeRenderer>` in places where it was used, so there's no need to have this forward declaration anymore.
* Remove the concept of rendering from `octree` entirely
  * The class `OctreeRenderer` has been renamed `OctreeProcessor` (for lack of a better idea)
  * Move the `OctreeHeadlessViewer` and `EntityTreeHeadlessViewer` out of `octree` and `entities` and into `assignment-client`
  * Remove `OctreeRenderer::_viewFrustum`.  It was assigned in several places but never read, with clients using `RenderArgs::_viewFrustum` instead
  * Remove `OctreeRenderer::render()`.  It was used in only one place, the `LocalModelsOverlay` but ultimately it traversed the octree but did nothing, because it called `OctreeRenderer::renderElement` which had a default empty implementation as was never overridden.  
* Remove the concept of rendering from `entities` almost entirely
  * Ultimately I had to leave an opaque type `RenderableEntityInterface` in the `EntityItem` class, because I could not get dynamic casting from `EntityItem*` to `RenderableEntityInterface` to work in `entities-renderer`
* Remove `LocalModelsOverlay` and `Application::_entityClipboard`.  As mentioned above, these ultimately performed no rendering and weren't used for anything else.
 - Fixes performance issues related to KTX processing on the main thread during progressive loading. 
 - Spectator Camera - Mergeable Rendering Components 
 - Fixed a bug where range requests for small KTX files would always fail
 - Added a restart button to domain server settings page 
 - Ignore remote update younger than recent ownership bid 
 - Emphasize mute state with red 
 - Implement parts of the JS "console" object 
 - Fix import of JSON with parent-child relationships 
 - Add "Play sample sound" to audio setting 
 - Update chrome for the audio input level meter 
 - Give audio menu mute checkbox its own row 
 - Add a VU meter to the active mic selection 
 - Fix crash when cache entry lifetime exceeds cache lifetime 
 - Adding Profiling for script engine timer callback 
 - Expose location scripting interface to Agent (AC script) 
 - Bug Fixes for Eyeless Avatars 
 - Add entity script for balloon spawner and sample json entity with us 
 - Improvements to gracefulControls.js 
 - Sort Running Scripts... list alphabetically 
 - Fix skyboxes sometimes not showing 
 - Event installer interface options
 - Ad broadcasting/replication to downstream avatar mixers and audio mixers
 - Hand pucks and Calibration UI 
 - Make broadcasting settings advanced in DS settings 
 - We have 2 new command-line switches: --avatarURL and --replaceAvatarURL
 - Have cmake find fbx library on Linux 
 - Fix reload content for baked skyboxes 
 - Adding support for loading obj.gz files in ModelCache. 
 - Push AvatarData sequence number when managing identity data for agent 
 - Use existing node ID during repeated connect requests 
 - HRTF optimizations: Improve Audio-Mixer scalability on the latest Intel CPUs (Core i9 and Skylake-SP Xeon). The framework is added to detect and use AVX512 instructions
 - Installer allows /nSandboxIfNew command line switch
 - Added Support to Disabling flight from client side 
 - ShortBow Improvements 
 - Added confirmation to domain server webpage before restarting 
 - Fixed a bug where restart modal was shown when it shouldn't be 
 - Add upstream nodes to NL and verify replicated packet sender 
 - Add a /forceNoLaunch switch to the installer 
 - Prevent replication flat loops 
 - Check for codec changes for replicated agents 
 - Fix the messages printed by domain-server about which name it's using to find ice-servers 
 - Log audio selections 
 - Command line switch to override default scripts location
 - Trying to fix QtQml/QtScript crashes

Smoke test : http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

RC functionality test: https://docs.google.com/spreadsheets/d/1F8S8a8lyze1wEczT8hc0dmz3_7QLDiHOxntKW6g0UjY/edit#gid=1080464620

### CODE REVIEW

**Comment by CainFoool** [comment]
Hey @cozza13: The RC Sheet you linked is a bit out dated. Have you got a link to the latest?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1082/HighFidelity-Beta-PR10810-5da43257f70ce701e09fb54e4d760357d9173969.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1084/HighFidelity-Beta-PR10810-5da43257f70ce701e09fb54e4d760357d9173969.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1084/HighFidelity-Beta-PR10810-5da43257f70ce701e09fb54e4d760357d9173969.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** UNTESTED
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: FAIL. ReverbTest did not load. I did not find anything in the logs to give a deeper insight. Everything else worked as expected.


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |64
**Present Rate**: |52 |60 |64
**Present New Rate**: |60 |60 |69
**CPU Buffer Count**: |580 |1336 |1426
**GPU Buffer Count**: |195 |577 |397
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |86 |112 |95
**GPU Texture Count**: |52 |87 |53
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |30060 |247740 |123878
**Triangle Rate**: |1878750 |15483750 |7742375
**API Drawcall Count**: |47 |188 |64
**Drawcall Count**: |48 |196 |69
**Drawcall Rate**: |3000 |12250 |4312
**State Changes Texture Count**:|72 |213 |59
**Pipeline Count**: |27 |34 |27
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|SUCCESS
**Test 2**|Install a fresh copy of "Home' and do tutorial|SUCCESS
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|SUCCESS
**Test 4**|Launch firework, on dev-playa, can other hear?|UNABLE - dev-playa had a theater in it however worked functionally.  This is NOT a failure as the firework button was simply not on the new build.
**Test 5**|Switch avatar and make sure it does not crash|SUCCESS
**Test 6**|Test group functions|UNTESTED
**Test 7**|Test Ambisonic audio with markeplace item|SUCCESS
**Test 8**|Enrure that you can distance grab|SUCCESS
**Test 9**|Bring up and edit an objects with hand controllers|SUCCESS
**Test 10**|Test PAL functionality|UNTESTED

**Comment by ctrlaltdavid** [comment]
Desktop toolbar doesn't work: clicking on any of the buttons has no effect.

**Comment by jherico** [comment]
@cozza13 we'll need to cherry pick #10815 to fix the toolbar buttons.

**Comment by OmegaHeron** [comment]
Waiting to test more once issue with desktop HUD is fixed.

I experience same as @kevinmthomasse in respect to reverb test - QA script no longer loads reverb test script or presents its UI.  That seems a fail too...

dev-playa being no more seems a problem as well.  It was the last benchmark to compare against with known characteristics...  I think it's important that we have such a thing that so many of us have looked at over and over and over such that we notice if something changes visually or in respect to performance.

**Comment by cozza13** [comment]
@kevinmthomasse @OmegaHeron I have updated with the fix

**Comment by kevinmthomasse** [comment]
@cozza13 will do.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1092/HighFidelity-Beta-PR10810-b1b26bc8a52094f9d6dae502718f896e0072d41e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1092/HighFidelity-Beta-PR10810-b1b26bc8a52094f9d6dae502718f896e0072d41e.dmg

**Comment by OmegaHeron** [comment]
Picking up testing again.

**Comment by OmegaHeron** [comment]
Reverb test is now throwing log issue (still won't work)

I'm not sure if this is a major issue or an API change meaning reverbTest.js needs updating...  since reverb has always been a critical test - it's a QA Fail until this can be worked out.

`[06/25 17:35:03] [DEBUG] [hifi.scriptengine] loadURL "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js" "Cached" QThread(0x21caa767f30, name = "Main Thread")`
`[06/25 17:35:03] [INFO] [hifi.scriptengine] Script Engine starting:reverbTest.js`
`[06/25 17:35:03] [DEBUG] [hifi.scriptengine] Loading script at  QUrl("http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/cookies.js")`
`[06/25 17:35:03] [DEBUG] [hifi.scriptengine] Found script in cache: "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/cookies.js"`
`[06/25 17:35:03] [DEBUG] [hifi.scriptengine] Loaded:  "http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/cookies.js"`
`[06/25 17:35:03] [CRITICAL] [hifi.scriptengine] [UncaughtException evaluate] Error: Can't find variable: AudioDevice in http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38`
`[06/25 17:35:03] [CRITICAL] [hifi.scriptengine] [Backtrace]`
`[06/25 17:35:03] [CRITICAL] [hifi.scriptengine]     <global>() at http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38`

**Comment by kevinmthomasse** [comment]
@OmegaHeron @cozza13 I concur with the above.  Here is my error upon running ```reverbtest.js``` 
[06/25 17:42:31] [WARNING] [default] Setting::Manager::registerHandle(): Key registered more than once, overriding:  "com.highfidelity.experimental.enableExtendedJSExceptions"
[06/25 17:42:31] [CRITICAL] [hifi.scriptengine] [UncaughtException evaluate] Error: Can't find variable: AudioDevice in http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38
[06/25 17:42:31] [CRITICAL] [hifi.scriptengine] [Backtrace]
[06/25 17:42:31] [CRITICAL] [hifi.scriptengine]     <global>() at http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

RC will likely pass once we can be _assured_ reverb isn't broken and exercise its functions.

RC Script needs some serious work; dev-demo has been "gone" forever, dev-playa is no longer same dev-playa.  Suggest it be updated to use locations localhost/garden, dev-welcome and some other stable location with good testing content QA people can access.

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS (Meaningless though as it's no long comparable to past dev-playa build)
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS (Again, meaningless as you can't connect so you're measuring "empty space")
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Reverb test fails

Desktop mode 1600x900 Maximized Window

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |70 |52
**CPU Buffer Count**: |2533 |1350 |749
**GPU Buffer Count**: |862 |587 |247
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |264 |102 |97
**GPU Texture Count**: |214 |86 |85
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |245659 |255276 |9662
**Triangle Rate**: |15353687 |15954750 |603875
**API Drawcall Count**: |184 |190 |15
**Drawcall Count**: |1103 |198 |15
**Drawcall Rate**: |68937 |12375 |937
**State Changes Texture Count**:|330 |213 |34
**Pipeline Count**: |48 |35 |21
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0

CV1 90/90/90

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Pass
**Test 4**|Launch firework, on dev-playa, can other hear?|No such object, dev-playa is no more.
**Test 5**|Switch avatar and make sure it does not crash|Pass
**Test 6**|Test group functions|Pass
**Test 7**|Test Ambisonic audio with markeplace item|Pass
**Test 8**|Enrure that you can distance grab|Pass
**Test 9**|Bring up and edit an objects with hand controllers|N/A
**Test 10**|Test PAL functionality|Pass (basic tests)
**Test 11**|Test Tablet in 2D and 3D|Pass (Basic tests)

**Comment by kevinmthomasse** [comment]
All of the other tests passed as stated in my prior PR.  I agree with @OmegaHeron once we fix the ```reverbtest.js``` error can't find variable: AudioDevice in http://s3.amazonaws.com/hifi-public/scripts/utilities/tools/reverbTest.js:38

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |355 |404 |227
**Present Rate**: |354 |406 |228
**Present New Rate**: |219 |219 |219
**CPU Buffer Count**: |2514 |1277 |1464
**GPU Buffer Count**: |925 |519 |410
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |223 |101 |108
**GPU Texture Count**: |176 |83 |57
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |27947 |255706 |145358
**Triangle Rate**: |9315666 |85235333 |36339500
**API Drawcall Count**: |31 |190 |92
**Drawcall Count**: |2668 |198 |98
**Drawcall Rate**: |889333 |66000 |24500
**State Changes Texture Count**:|60 |213 |93
**Pipeline Count**: |29 |36 |25
**Item Opaques**: |0 |0 |0
**Item Translucents**: |0 |0 |0
**Item Lights**: |0 |0 |0
**Timing Opaques**: |0 |0 |0
**Timing Translucents**: |0 |0 |0
**Timing Lighting**: |0 |0 |0
**Render Frame**: |0 |0 |0

**Comment by Nex-Pro** [comment]
Testing this as per @cozza13 request.

**Comment by Nex-Pro** [comment]
RC Beta Release 45 - Includes up to Developer Release 6767

Primary testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.
Audio systems:  USB headset + Vive audio.

## QA Test : FAIL

**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** FAILURE
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** FAILURE
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** FAILURE
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**:

On first run was located in a blank room with sound effects from the VR tutorial.
Hand animations of default avatar were triggered by Y rotation ( yaw ).
Raising hands did not trigger first stage of tutorial.

Able to quit via tablet menu.

Tutorial entry point appeared on second run.

Far grab jerky motion noted.

As previously noted grbbing the vase in the middle room moves the adjacent dynamic objects to 0,0,0

Pressing ctrl + s to grab a snapshot triggers a "Tablet needs attention" notice. Tablet is, at this stage, unavailable.

Additional observations: 
Cylinder primitive has no smoothing. It appears faceted. Fortunately it can be made to be 0.1mm thick. This permits a two-sided disc.
Circle is mis-named should be disc. Also is single sided.

We need tube with internal and external radii. This will give us a type of circle/ring.

Also Torus would be good.

If an entity is edited to be minimal height in the 'Y' dimension the green 'clone' handle becomes unuseable.

Large number of script errors from utils.js in log.

Regular dev-playa content unavailable.. Seems to be copy of Zaru.


**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |0 |0 |
**Present Rate**: |0 |0 |
**Present New Rate**: |0 |0 |
**CPU Buffer Count**: |2580 |1692 |
**GPU Buffer Count**: |823 |810 |
**CPU Memory Usage**: | | |
**GPU Memory Usage**: | | |
**CPU Texture Count**: |258 |114 |
**GPU Texture Count**: |193 |101 |
**GPU Transfer Count**: | | |
**CPU Texture Memory Usage**: | | |
**GPU Texture Memory Usage**: | | |
**GPU Virtual Memory Usage**: |||
**Triangle Count**: |423420 |354952 |
**Triangle Rate**: |42342000 |32268363 |
**API Drawcall Count**: |167 |140 |
**Drawcall Count**: |4522 |278 |
**Drawcall Rate**: |452200 |25272 |
**State Changes Texture Count**:|266 |144 |
**Pipeline Count**: |43 |32 |
**Item Opaques**: |0 |0 |
**Item Translucents**: |0 |0 |
**Item Lights**: |0 |0 |
**Timing Opaques**: |0 |0 |
**Timing Translucents**: |0 |0 |
**Timing Lighting**: |0 |0 |
**Render Frame**: |0 |0 |

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Dev-playa does not have the previously used content.
**Test 2**|Install a fresh copy of "Home' and do tutorial|Pass. Slight jerkiness on far grab.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Success
**Test 4**|Launch firework, on dev-playa, can other hear?|Untested.
**Test 5**|Switch avatar and make sure it does not crash|Success
**Test 6**|Test group functions|Untested
**Test 7**|Test Ambisonic audio with markeplace item|Success
**Test 8**|Enrure that you can distance grab|Success
**Test 9**|Bring up and edit an objects with hand controllers|Success
**Test 10**|Test PAL functionality|Only basic functions tested.
**Test 11**|Test Tablet in 2D and 3D|Basic testing Success.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1102/HighFidelity-Beta-PR10810-2260c0965c55c8e15ef3477ca385d65dc7a9f26b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1102/HighFidelity-Beta-PR10810-2260c0965c55c8e15ef3477ca385d65dc7a9f26b.dmg

**Comment by OmegaHeron** [comment]
Running reverbTest.js manually now works - reverb settings apply as expected.  This + previous tests = Pass for me.
After starting with a clean cache QAofRC.js still won't load reverbTest.js, but, I suspect that's because QAofRC needs updating as well.

**Comment by kevinmthomasse** [comment]
I have installed 2260c09 and I have received the EXACT experience as @OmegaHeron as ```reverbtest.js``` did NOT load with the QA Script however it did loaded independently and worked normally.  I agree that the QA script once updated should fix.  THIS IS A PASS.
capture

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1134/HighFidelity-Beta-PR10810-827fa98baaa68448882b1780399410a81a2f7729.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1134/HighFidelity-Beta-PR10810-827fa98baaa68448882b1780399410a81a2f7729.exe

**Pull request merged**
