### PR TITLE
Speed up entity list update after deleting entities

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

Test deleting an entity:
- Go to a domain with lots (600+) of entities.
- Open Entity List from create.
- Choose an entity from the list.
- Press the "Delete" button.
- The entity list is immediately updated with the deleted entity removed.

Test using the "Delete" key keyboard shortcut.

Test using Edit > Delete menu item.

Test deleting an entity with children: the entity and child entities should all be removed from the list.

Check that the number of entities in the list is updated.


Previously: The entity list cleared completely and took 5-10 sec to redraw.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4720/HighFidelity-Beta-PR11762-fadbf09cdd659569b4f8df988a9e23a48571c111.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4720/HighFidelity-Beta-PR11762-fadbf09cdd659569b4f8df988a9e23a48571c111.exe

**Comment by YuppyPlays** [comment]
Testing complete:

Go to a domain with lots (600+) of entities. **Check**
Open Entity List from create. **Check**
Choose an entity from the list. **Check**
Press the "Delete" button. **Check**
The entity list is immediately updated with the deleted entity removed. **Check**
Test using the "Delete" key keyboard shortcut. **Check**
Test using Edit > Delete menu item. **Check**
Test deleting an entity with children: the entity and child entities should all be removed from the list. **Check**
Check that the number of entities in the list reported in the footer is updated. **Check**
(Previously: The entity list cleared completely and took 5-10 sec to redraw.)

**Tested in Dev-welcome which has around 950 entities, experienced moments where the list would disappear and come back as well as footer text showing 0 during this, though I've had this happen previously in other builds when in Dev-welcome, so I don't believe it's related to PR.**

**Pass**

**Pull request merged**
