### PR TITLE
Improve Pointer performance

### PR DESCRIPTION
**Pull request by SamGondelman**
Simple cleanup for performance

Test plan:
- Run [this](https://gist.githubusercontent.com/SamGondelman/82e5674727142bf1105db131f67a4ad3/raw/24156d8cadfb8cb14cbac66c432814e8989a5d1b/PointerPerfTest.js).  Press and hold 6 until the blue pointer stops changing.  Open the expanded stats and look at the pointerManager time in the first column.  It should be fairly low (mine was around 0.3 ms in engine-dev).
- Repeat on master.  The time should be higher, maybe around 1.6 ms.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12481/HighFidelity-Beta-PR13899-cda8b82.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12481/HighFidelity-Beta-PR13899-cda8b82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12481/HighFidelity-Beta-Interface-PR13899-cda8b82.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12485/HighFidelity-Beta-PR13899-cda8b82.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12485/HighFidelity-Beta-PR13899-cda8b82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12485/HighFidelity-Beta-Interface-PR13899-cda8b82.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12485/HighFidelity-Beta-PR13899-cda8b82.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12485/HighFidelity-Beta-Interface-PR13899-cda8b82.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by qaAdamSmith82** [comment]
PASS @conklin94122 

Master PointerManager= 2.5ms
PR13899 PointerManager= 0.5ms

**Pull request merged**
