### PR TITLE
call saveRecordingToAsset callback on correct thread

### PR DESCRIPTION
**Pull request by sethalves**
- fix crash when uploading an avatar recording to asset-server

https://highfidelity.manuscript.com/f/cases/18292/QTJSC-Interpreter-privateExecute-QTJSC-Interpreter-ExecutionFlag-QTJSC-RegisterFile-QTJSC-24f4fb23f21492f0cd539046397

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use the avatar recording app from the marketplace

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13336/HighFidelity-Beta-PR14083-87a67a3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13336/HighFidelity-Beta-PR14083-87a67a3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13336/HighFidelity-Beta-Interface-PR14083-87a67a3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13336/HighFidelity-Beta-PR14083-87a67a3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13336/HighFidelity-Beta-Interface-PR14083-87a67a3.dmg

**Comment by JeffClinton** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

Only one crash seen in 50+ recordings, and it was determined by the backtrace to be unrelated.

**Pull request merged**
