### PR TITLE
Don't render wire geometry with lighting effects

### PR DESCRIPTION
**Pull request by jherico**
Wireframes should be unaffected by lighting.  Currently hand lasers in the Vive UI are very hard to see in playa because of the lighting.

### CODE REVIEW

**Comment by jherico** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JDDawVqJ&#x2F;86-make-seek-and-select-lasers-non-lit-this-should-also-be-true-for-the-pause-overlay"> Make seek and select lasers non-lit. This should also be true for the Pause overlay</a>

**Comment by jherico** [comment]
## Testing 

In an area with low lighting effects like Playa, using the edit system or something else to create wire box or line overlays should now render with the exact color specified.  In the production build, such wire overlays will render with the color plus any lighting effects, often making them much darker than intended.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b7926b8582829bc3ac444b401b5548f7872c21d8 available at: https://gist.github.com/836e9fa224fb51e3857932be90f9f5ab<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8174.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8174.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
@jherico can you allow me access tmprez access so I can use edit in ```playa``` so that I can test thanks!

**Comment by howard-stearns** [comment]
additional testing note: 
- Please also view the blue search beam and red grab beam that happens when you partially or fully squeeze the hand controller trigger. The lasers should be visible. 
- Compare the long in-world lasers (both blue and red) to the short "inside-the-hud" lasers that appear when partially/fully squeezing the triggers while pointing towards a HUD element. The short and long lasers should match in appearance (if not necessarily exact tracking).

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Upon clicking the hydras both the left and right hydras when slightly pressed, a matched blue line appears.  When fully squeezed, a matched red line appears.  The lasers match in appearance for both long and short whether pointing toward a HUD or not.

**Comment by jherico** [comment]
@kevinmthomasse I've updated the PR a little bit.  You can see the effect fairly strikingly by running [this script](http://s3.amazonaws.com/DreamingContent/scripts/testOverlays.js) in playa.  Note the coloring of the wireframe box on production vs this PR.  This version should be much brighter after all the lighting has loaded.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5288d983763ea57e4e1d33f37cc21384a82c5ba5 available at: https://gist.github.com/836e9fa224fb51e3857932be90f9f5ab<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8174.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8174.dmg

**Comment by kevinmthomasse** [comment]
## QA Re-Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Ran ```http://s3.amazonaws.com/DreamingContent/scripts/testOverlays.js``` in ```playa``` and after the lighting has fully loaded, noticed a dramatic difference in the coloring of the wireframe box as it was extremely bright light blue

**Pull request merged**
