### PR TITLE
Quiet logging

### PR DESCRIPTION
**Pull request by sethalves**
- enable or disable "debug" and "info" logging with menu-item in developer menu

https://highfidelity.fogbugz.com/f/cases/14488/Implement-Quite-Logging

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run Interface and open the logging window
- note that considerably less logging is happening
- enable developer menus
- check menus --> developers --> Verbose Logging (2nd to last)
- note that more logging happens
- exit interface and relaunch it
- note that Verbose Logging is still checked and logging is verbose
- uncheck Verbose Logging
- note that logging is reduced

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9003/app_12957_PR_e26475ce30cc1d6a22c35dbcefd8f356ca24a4a8.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9003/HighFidelity-Beta-PR12957-e26475ce30cc1d6a22c35dbcefd8f356ca24a4a8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9003/HighFidelity-Beta-Interface-PR12957-e26475ce30cc1d6a22c35dbcefd8f356ca24a4a8.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9003/HighFidelity-Beta-PR12957-e26475ce30cc1d6a22c35dbcefd8f356ca24a4a8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9003/HighFidelity-Beta-Interface-PR12957-e26475ce30cc1d6a22c35dbcefd8f356ca24a4a8.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9007/app_12957_PR_84e71a9bca36eb81f1607ad6ba5cb7976532c9c4.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9007/HighFidelity-Beta-PR12957-84e71a9bca36eb81f1607ad6ba5cb7976532c9c4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9007/HighFidelity-Beta-Interface-PR12957-84e71a9bca36eb81f1607ad6ba5cb7976532c9c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9007/HighFidelity-Beta-PR12957-84e71a9bca36eb81f1607ad6ba5cb7976532c9c4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9007/HighFidelity-Beta-Interface-PR12957-84e71a9bca36eb81f1607ad6ba5cb7976532c9c4.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9027/app_12957_PR_1dbcbbccedf10d19956677e3416d13c3850b8049.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9027/HighFidelity-Beta-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9027/HighFidelity-Beta-Interface-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9052/app_12957_PR_1dbcbbccedf10d19956677e3416d13c3850b8049.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9052/HighFidelity-Beta-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9052/HighFidelity-Beta-Interface-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9052/HighFidelity-Beta-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9052/HighFidelity-Beta-Interface-PR12957-1dbcbbccedf10d19956677e3416d13c3850b8049.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Pull request merged**
