### PR TITLE
Adding fix for enabling saved front/back advanced controls. (RC68)

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixing forward and backward HMD controls to work after restarting interface

https://highfidelity.manuscript.com/f/cases/15324

### CODE REVIEW

**Comment by wayne-chen** [comment]
To test:

- Mount HMD
- Launch Interface
- Go to Settings > Controls
- Enable Advanced Movement
- Verify controls work
- Close Interface
- Launch Interface
- Verify controls work

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10123/HighFidelity-Beta-PR13239-720b0a896323a309e71486d1bc0193e337aad3b3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10123/HighFidelity-Beta-PR13239-720b0a896323a309e71486d1bc0193e337aad3b3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10123/HighFidelity-Beta-Interface-PR13239-720b0a896323a309e71486d1bc0193e337aad3b3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Controls work even after closing and crashing.

**Pull request merged**
