### PR TITLE
fix grab entity methods + jshint cleanups

### PR DESCRIPTION
**Pull request by sethalves**
- fix grab entityMethod calls: startNearGrab, startDistanceGrab, etc

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/7673/startNearGrab-and-startDistanceGrab-no-longer-work

**Comment by sethalves** [comment]
to test:

```javascript
(function() { 
    var _this = this;

    _this.preload = function(entityID) {
        print("Loading test script"); 
        _this.entityID = entityID; 
    };

    _this.startNearGrab = function(entityID, args) {
    	print("hey");
    };

    _this.startNearGrab = function(entityID, args) {
    	print("hello");
    };

    _this.unload = function(entityID) {
        
    };
})
```

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3351/HighFidelity-Beta-PR11374-39e6605f6f5c68dbde22e13d14cc881e7e5e87f4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3351/HighFidelity-Beta-PR11374-39e6605f6f5c68dbde22e13d14cc881e7e5e87f4.exe

**Comment by jfcarter** [comment]
StartNearGrab and StartDistanceGrab are only working once per entity with a script on it that uses the callbacks

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3354/HighFidelity-Beta-PR11374-df80b7ecfa8bf0abf4451c1e48439dc1297c2a77.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3354/HighFidelity-Beta-PR11374-df80b7ecfa8bf0abf4451c1e48439dc1297c2a77.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3364/HighFidelity-Beta-PR11374-0816a8af273631b6c5bce24820f0d48e7b239a25.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3364/HighFidelity-Beta-PR11374-0816a8af273631b6c5bce24820f0d48e7b239a25.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
@sethalves 
I'm having a bit of issue combining the script to the dynamic object?

Usually it requires a file or URL, not sure if I can just copy/paste this into the required file format via Notepad++?

**Comment by YuppyPlays** [comment]
Testing complete:

(Cain helped me by putting the script into a .js)

put this script on a dynamic entity. **Check**
open the hmd-friendly script log window **Check**
near-grab the entity, look for "startNearGrab" and "releaseGrab" in the log **Check**
far-grab the entity, look for "startDistanceGrab" and "releaseGrab" in the log **Check**
make the entity non-dynamic, test near-grab again (far-grab wont work on non-dynamic) **Fail, Non-dynamic seems to create strange behaviour such as cloning the object and making the new clone the intractable object whilst the original one is static and does nothing**
generally smoke-test other grab and equip functionality **Check**


**Fail**

**Comment by Nex-Pro** [comment]
@sethalves **PASS**

No issues seen apart from equip sphere not showing up immediately. ( showed up eventually, but that isn't due to this PR )

Near and far grab messages in script log consistent at all times.

Near grab for both dynamic and non-dynamic ents is fine.

Cloneable dynamic and non dynamic fine.

Cloneable respects clone lifespan and total number.

Equip works fine.

Trigger ok

**Comment by sethalves** [comment]
@YuppyPlays I'm going to merge this, but I'd like to better understand what you were seeing with non-dynamic entities.  I'll find you on slack.

**Pull request merged**
