### PR TITLE
Fix MS17811: Prevent frozen avatars in certain ignore cases

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS17811](https://highfidelity.manuscript.com/f/cases/17811).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15879/HighFidelity-Beta-PR14566-d46b8d6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15879/HighFidelity-Beta-PR14566-d46b8d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15879/HighFidelity-Beta-Interface-PR14566-d46b8d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15879/HighFidelity-Beta-PR14566-d46b8d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15879/HighFidelity-Beta-Interface-PR14566-d46b8d6.exe

**Comment by qlilaseguinolaza** [comment]
Currently testing

**Comment by qlilaseguinolaza** [comment]
PR14566 PASS
Avatar no longer freezes after being ignored and then opening and closing the People app.

**Pull request merged**
