### PR TITLE
temp hack to Image3DOverlay

### PR DESCRIPTION
**Pull request by davidkelly**
This should fix the drift between the camera entity and the image overlay.  But, it breaks billboarding.  Which we can live with until I really fix the overlays.  Note this is going into our branch (not master), so it will only be this branch with this issue for now.  Allows us to make progress on other stuff in meantime.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/463/HighFidelity-Beta-PR10631-fdfba76a4dc6b14761cfdf3a7fcc8c7df6253b2a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/463/HighFidelity-Beta-PR10631-fdfba76a4dc6b14761cfdf3a7fcc8c7df6253b2a.dmg

**Comment by howard-stearns** [comment]
dev-approved for now, per description.

**Comment by davidkelly** [comment]
Test Plan

rez the camera, select it with edit.js and give it some angular velocity (with 0 angularDamping perhaps), watch it spin.  The overlay should stay in place.  Set it back to 0, watch it stay there.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/467/HighFidelity-Beta-PR10631-ed8c3bc1bbb2ad71de5f424d7df789a2885a031c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/467/HighFidelity-Beta-PR10631-ed8c3bc1bbb2ad71de5f424d7df789a2885a031c.exe

**Comment by davidkelly** [comment]
closing as we switched to avatar entities which (surprisingly) don't show this issue.

**Pull request closed without merging**
