### PR TITLE
Add domain to record script user activity logging

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
For @anshuman64 to QA.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04fcdfc4a2ccaa214bdba8ac71d17050c3cfaac0 available at: https://gist.github.com/a2c3694edb6ad4a279431b1d9ffcccec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10480-04fcdfc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10480-04fcdfc.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 04fcdfc4a2ccaa214bdba8ac71d17050c3cfaac0 available at: https://gist.github.com/a2c3694edb6ad4a279431b1d9ffcccec<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10480-04fcdfc.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10480-04fcdfc.dmg

**Pull request merged**
