### PR TITLE
Improve AnimPose support for negative scale

### PR DESCRIPTION
**Pull request by hyperlogic**
AnimPose constructor from a mat4 now handles matrices with mirroring a.k.a. negative scale better.
Previously the rotations would be incorrect.

https://highfidelity.manuscript.com/f/cases/20965/A-few-external-avatars-appear-differently-for-remote-observers-vs-local-user

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17928/HighFidelity-Beta-PR15119-c5e9a7d.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17928/HighFidelity-Quest-Beta-PR15119-c5e9a7d.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17928/HighFidelity-Beta-PR15119-c5e9a7d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17928/HighFidelity-Beta-Interface-PR15119-c5e9a7d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17928/HighFidelity-Beta-PR15119-c5e9a7d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17928/HighFidelity-Beta-Interface-PR15119-c5e9a7d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17962/HighFidelity-Beta-PR15119-0cf8f3e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17962/HighFidelity-Beta-Interface-PR15119-0cf8f3e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17962/HighFidelity-Beta-PR15119-0cf8f3e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17962/HighFidelity-Quest-Beta-PR15119-0cf8f3e.apk)

**Comment by hyperlogic** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17968/HighFidelity-Beta-PR15119-0cf8f3e.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17968/HighFidelity-Beta-Interface-PR15119-0cf8f3e.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17968/HighFidelity-Beta-PR15119-0cf8f3e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17968/HighFidelity-Quest-Beta-PR15119-0cf8f3e.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17968/HighFidelity-Beta-PR15119-0cf8f3e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17968/HighFidelity-Beta-Interface-PR15119-0cf8f3e.exe

**Pull request merged**
