### PR TITLE
IK tuning and bug fixes

### PR DESCRIPTION
**Pull request by hyperlogic**
* Bug fix for ik targets with end effectors that lie on the same chain as other ik targets, i.e. the chest. The bug was that the end-effector rotation was set AFTER all ik iterations were performed.  As a result, it would tend to pull the other IK chains off their target positions. In the case of the chest/spine2 target, it would cause the head and arms to never reach their intended targets, even with a large number of iterations. Now we rotate the tip joint at the start of each iteration, resulting in better convergence.
* Bug fix for elliptical swing constraints, both for debug rendering and computation.
* Flex coefficients are used for tip rotations as well.
* Arm flex coefficients are tuned to not affect the chest and lower back as much.  This reduces the amount of spine buckling when the hands cannot reach their targets.
* "Show IK Chain" developer option that draws each IK chain before they are accumulated.  This is useful in determining which IK chain is exerting undue influence over the chest/spine joints.  Also, the links between joints will be drawn in RED when that joint hits a constraints.  This is useful to when IK constraints are preventing the joint from bending naturally.
* "Show IK Constraints" are now rotated with post IK pose, instead of the pre-IK "solution" pose.
* Opened up hip constraints, this improves quality of bending and sitting poses.
* Embiggened Head constraints, but narrowed and stiffened the neck.  This results in more natural poses for the head and neck under large swings and twists.  For example, lateral bends and bending backwards.

### CODE REVIEW

**Comment by marko8904** [comment]
github still occasionally triggers builds on the old cluster. This PR resulted in a duplicate. Please ignore the incoming "All checks failed" message. The real build will update the status within the next 30min. It seems that github still has some stale data on its servers.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ae2e6778e33dd1b27ac9797659b0dcbd3798c92 available at: https://gist.github.com/239610959199db164eeb9f76d665392e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10513-6ae2e67.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10513-6ae2e67.dmg

**Comment by hyperlogic** [comment]
QA test:
  * Ensure that in desktop mode walking, jumping look natural
  * Ensure that in desktop mode using looking up and down causes the avatar's head to bend up and down.
  * Ensure that in HMD mode with hand controllers the avatar follows the motions of the head and hands.  In this case the result won't necessarily be any better, but should not be any worse the current master.

QA test with pucks:
  * When wearing the chest puck, the hands should shake/jitter less than current master.
  * In general, when doing side to side bends the hands should look more natural and the neck should look more natural. (However there will still be some unnatural twists in the spine. that will be addressed later)
  * Sitting on the floor with legs outstretched and touching toes poses should look more natural (except for bowing of the spine, which will be addressed later)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/43/HighFidelity-Beta-PR10513-6ae2e6778e33dd1b27ac9797659b0dcbd3798c92.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/43/HighFidelity-Beta-PR10513-6ae2e6778e33dd1b27ac9797659b0dcbd3798c92.dmg

**Comment by OmegaHeron** [comment]
QA In progress.

**Comment by OmegaHeron** [comment]
Windows 10
Tested desktop and HMD (CV1 + Touch controls).
Tested with default AV, photo real male and my custom Mixamo based AV.

Passes smoke test and HMD/desktop/normal hand controls.  Unable to test with whatever pucks are - none to test with.  One crash recorded in dev-welcome, splat sent and could not repro it.

Desktop mode - no difference I can see between master and PR for movement (walking, flying, landing, jumping -- head follows lookat using shift + arrow keys and holding of right mouse button while "panning".

HMD - arms follow controllers, head follows HMD, fingers behave as expected for state of open, fist, pointing and thumbs up as expected with CV1+Touch.

Used 2nd agent on another machine (over LAN) and agents appeared as expected to each other while idle, moving and under HMD control.

**Comment by anshuman64** [comment]
Videos of changes linked below. Admittedly, some of the poses can be considered a "regression" because they are less visually pleasing. However, Tony is well aware of these and I am confident these will be addressed by his next task, Spine Spline. The other poses have definitely been improved.

Without PR: https://drive.google.com/open?id=0B_nmInIG19-ucVBGa0MzbFZlQWM
With PR: https://drive.google.com/open?id=0B_nmInIG19-uMlJBdmw4UlRqcDg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/116/HighFidelity-Beta-PR10513-06c26f029a2690a572a15f9c2ee785e4b38b9015.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/116/HighFidelity-Beta-PR10513-06c26f029a2690a572a15f9c2ee785e4b38b9015.dmg

**Pull request merged**
