### PR TITLE
Re-parent entities after duplicating and duplicate children with parents

### PR DESCRIPTION
**Pull request by dback2**
When duplicating entities, store the entities that had parents and will need re-parenting, and also store the mapping of original entity ID to new duplicated entity ID. After duplicating, for each newly duplicated entity whose parent was also duplicated, re-parent them to the new duplicate of the original parent entity. Also ensure any unselected children of selected parent entities get duplicated.

Fixes: https://highfidelity.manuscript.com/f/cases/13845

Test Plan:

The new duplicating parent/child rules will mainly follow these guidelines:
-Duplicating an entity who is a parent will always duplicate with all it's children (including children of children and so on downward), whether those children are selected at time of duplication or not
-Duplicating an entity who is a child will only duplicate with it's parent if it's parent is also selected at time of duplication
-Duplicating an entity who is a child will cause the new duplicate to be parented to the parent of the original entity being duplicated

Test Steps:
-Enter Interface in desktop mode
-Open Create and create several entities of any type
-Select any entity and verify when holding Alt to drag it that a single-selected entity copies as expected
-Select any entity to find and copy it's ID in the properties tab
-Select any other entity and assign it's parent ID to the copied ID above
-Select both entities and hold Alt to drag and duplicate them, verifying the same parent/child relationship is maintained between the new duplicated entities
-Select only the child entity and hold Alt to drag and duplicate it, verifying the original entity and the new duplicated entity are parented to the same parent
-Parent more entities together linearly (i.e. entity D parented to entity C parented to entity B parented to entity A)
-Select the top-level parent (entity A in the example in the step above) and hold Alt to drag and duplicate it, verifying any unselected children of the original selected entity are also duplicated and the same parent/child relationship is maintained between the new set of duplicated entities and the original set of entities
-Select an entity in the middle of the linear hierarchy from above, and hold Alt to drag and duplicate it, verifying any unselected children (and not the parent) of the original selected entity are also duplicated, and the same parent/child relationship is maintained between the new set of duplicated entities and the original set of entities which includes parenting the duplicate of the original selected entity to the same parent as the original
-Select all of the linearly parented entities above and hold Alt to drag and duplicate them, verifying the same parent/child relationship is maintained between the new set of duplicated entities and the original set of entities
-Parent more entities together in a random/non-linear fashion (i.e. entity E parented to entity A, entity D parented to entity A, entity C parented to entity B, entity B parented to entity A, etc.)
-Select an entity or entities anywhere in the hierarchy and hold Alt to drag and duplicate it/them, verifying any unselected children (and not the parent) of the original selected entity are also duplicated, and the same parent/child relationship is maintained between the new set of duplicated entities and the original set of entities which includes parenting the duplicate of the original selected entity to the same parent as the original
-Select all the non-linear parented entities above and hold Alt to drag and duplicate them, verifying the same parent/child relationship is maintained between the new set of duplicated entities and the original set of entities

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11136/HighFidelity-Beta-PR13549-1cc79f0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11136/HighFidelity-Beta-PR13549-1cc79f0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11136/HighFidelity-Beta-Interface-PR13549-1cc79f0.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11138/HighFidelity-Beta-PR13549-fbe670d.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11139/HighFidelity-Beta-PR13549-2bcc962.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11139/HighFidelity-Beta-PR13549-2bcc962.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11139/HighFidelity-Beta-Interface-PR13549-2bcc962.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11139/HighFidelity-Beta-PR13549-2bcc962.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11139/HighFidelity-Beta-Interface-PR13549-2bcc962.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Fail @conklin94122 

When testing step 9, once I attempted to copy (Alt+drag) the linearly parented group (Entities A. B. C and D), Child entities C and D disappeared from the original linearly parented group.

Steps to reproduce:

1. Create four distinguishable entities - Entity A, B, C, and D
2. Select the first entity (Entity A) and copy its ID
3. Select the second entity and paste the first entities ID into the second entities "Parented ID" text box
4. Copy the ID of Entity B and paste it into Entity Cs "Parented ID" text box
5. Repeat the above steps for parenting Entity D to Entity C
6. Select Entity A 
7. Alt + Select Entity A to duplicate the linearly parented group
8. The entities are duplicated but the original linear group are now missing two of their entities (C and D)

[hifi-log_2018-07-06_13.41.29.txt](https://github.com/highfidelity/hifi/files/2172024/hifi-log_2018-07-06_13.41.29.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11176/HighFidelity-Beta-PR13549-a546d8b.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11176/HighFidelity-Beta-PR13549-a546d8b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11176/HighFidelity-Beta-Interface-PR13549-a546d8b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11176/HighFidelity-Beta-PR13549-a546d8b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11176/HighFidelity-Beta-Interface-PR13549-a546d8b.exe

**Comment by QliCknox** [comment]
Currently testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

Reparenting entities after duplication works as expected

**Pull request merged**
