### PR TITLE
fix far-trigger

### PR DESCRIPTION
**Pull request by sethalves**
- far triggering works, again
- far triggering no longer quickly cycles -- it will call start, continue repeatedly, and once the beam leaves the object (or the trigger is released), stop
- search line no longer freezes during a far-trigger

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 69caf1df4d5f3e9bff615e0a56d264c3f4aa955c available at: https://gist.github.com/ded2f6a9429fddb1c10a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7127.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7127.dmg

**Comment by sethalves** [comment]
to test:
- create an entity and set its userData to {"grabbableKey": {"wantsTrigger": true}}
- set the entityScript to http://headache.hungry.com/~seth/hifi/debug-trigger.js
- open the log
- attempt to near and far trigger the entity and see that the messages in the log match what you're doing

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/90582582645391

**Comment by hifi-gustavo** [comment]
Build console output for commit: 64e50c532938b75980adc428be4b0e16482ba4ef available at: https://gist.github.com/ded2f6a9429fddb1c10a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7127.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7127.dmg

**Comment by ericrius1** [comment]
Test link: https://rawgit.com/sethalves/hifi/BUGS/examples/controllers/handControllerGrab.js

**Pull request merged**
