### PR TITLE
Decrease Cell Science Volume

### PR DESCRIPTION
**Pull request by imgntn**
This PR reduces the volume of the music playing in cell science.

**NOTE: This script will clear content where you run it**

To test: 

1. In an empty domain, go to running scripts and import this script from url: http://hifi-content.s3.amazonaws.com/DomainContent/CellScience/importCellScience.js
2. Stop the importCellScience.js script.
3. Observe that the volume is at a reasonable level.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 822a64a08b7366923e01705369274f139c4b91f0 available at: https://gist.github.com/182da021bb0101ae68c0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7010.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7010.dmg

**Comment by nbq** [comment]
Testing this one now

**Comment by nbq** [comment]
I will admit with headphones the background music still seems a little loud to me but not unbearable. Almost makes you feel like you are in an auditorium watching it.

**Comment by RyanDowne** [comment]
Did you try to have a conversation with someone while in there? I think what we want is for the volume to be loud enough to hear but not so loud so to make having a conversation impossible.

**Comment by RyanDowne** [comment]
I tested this with Chris. Please reduce a further 10% and then we are good!

Thanks

**Comment by hifi-gustavo** [comment]
Build console output for commit: 51b335c9020d20686c25d8658068367e39f39edb available at: https://gist.github.com/182da021bb0101ae68c0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7010.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7010.dmg

**Pull request merged**
