### PR TITLE
Delete parentless entities redux

### PR DESCRIPTION
**Pull request by sethalves**
- when a parent of entities (either an avatar or another entity) is deleted, clean up the children

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- use the servers from this PR
- log two interfaces into the same domain and get them facing each other
- enabled Advanced Menus: Settings --> Advanced Menus
- open the javascript console: Edit --> Console
- paste this:
```Entities.addEntity({
  type: "Box",
  name: "child",
  position: Vec3.sum(MyAvatar.position, {x: 0.0, y: 0.4, z: 1.0}),
  dimensions: {x: 0.4, y: 0.4, z: 0.4},
  color: {red: 0, green: 0, blue: 255 },
  script: "http://headache.hungry.com/~seth/hifi/unload-test.js",
  parentID: Entities.addEntity({
    type: "Box",
    name: "parent",
    position: Vec3.sum(MyAvatar.position, {x: 1.0, y: 0.4, z: 0.0}),
    dimensions: {x: 0.4, y: 0.4, z: 0.4},
    color: {red: 0, green: 255, blue: 0 },
    script: "http://headache.hungry.com/~seth/hifi/unload-test.js",
    parentID: MyAvatar.sessionUUID
  })
});```
- make sure the avatar gets children boxes that move along with it
- log the avatar which children out
- check the observer's log for UNLOAD messages for both parent and child

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/84152686140798
https://app.asana.com/0/26485730907942/97602053089715

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7641b1e99d6d649e97da3795a18a36bc753e9480 available at: https://gist.github.com/a8f96a246fd754a1c20a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7641b1e99d6d649e97da3795a18a36bc753e9480 available at: https://gist.github.com/a8f96a246fd754a1c20a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7641b1e99d6d649e97da3795a18a36bc753e9480 available at: https://gist.github.com/a8f96a246fd754a1c20a<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7345.dmg

**Comment by Nex-Pro** [comment]
Ok here is the result of the test. Looks ok.

[03/14 02:25:53] [DEBUG] Already downloading script at: "http://headache.hungry.com/~seth/hifi/unload-test.js"
[03/14 02:25:53] [DEBUG] Done downloading script at: "http://headache.hungry.com/~seth/hifi/unload-test.js"
[03/14 02:25:53] [DEBUG] script:print()<< PRELOAD for {351bd07b-3f71-4ac7-88b1-97f75c82dc0b} : child
[03/14 02:25:53] [DEBUG] script:print()<< PRELOAD for {80c87af5-d208-454e-836d-ac7e76ba69a2} : parent
[03/14 02:26:42] [DEBUG] Removed avatar with UUID "7b637d14-1e54-4d0a-8846-9357b1e4a0aa" from AvatarHashMap
[03/14 02:26:42] [DEBUG] script:print()<< UNLOAD for {80c87af5-d208-454e-836d-ac7e76ba69a2} : parent
[03/14 02:26:42] [DEBUG] script:print()<< UNLOAD for {351bd07b-3f71-4ac7-88b1-97f75c82dc0b} : child
[03/14 02:26:43] [DEBUG] Optimizing QUuid("{7b637d14-1e54-4d0a-8846-9357b1e4a0aa}") for visibility 0

**Comment by ZappoMan** [comment]
I can't smoke test this on windows, because I'm away from my desktop... but I will smoke it on my mac laptop. It looks like it's been tested by @Nex-Pro -- I assume on windows.

**Comment by ZappoMan** [comment]
smokes ok on mac...

**Comment by ZappoMan** [comment]
based on Nex-Pro's tests and my smoke test, I think we can call this QA Approved

**Pull request merged**
