### PR TITLE
8992 Login window is small in tablet

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5664/HighFidelity-Beta-PR11996-a4696cc2b3ac311739b43266aa4f876b2b056e2d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5664/HighFidelity-Beta-PR11996-a4696cc2b3ac311739b43266aa4f876b2b056e2d.exe

**Comment by Nex-Pro** [comment]
@sethalves Same as the other PR ?

**Comment by RyanDowne** [comment]
@piper yes. Thanks

**Comment by Nex-Pro** [comment]
### PASS 

On each occasion that the login dialog auto-loaded it was full width of tablet screen.
>20x Loaded successfully.
hifi-snap-by--on-2017-12-15_03-30-12

**Pull request merged**
