### PR TITLE
7722 Add onHover Outline to Tablet "X" Button

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

1. Open tablet
2. Ensure 'close' button gets highlighted with white if hover with mouse (and highlight disappears if move mouse away)
3. Ensure the same is true if hover with stylus
4. Ensure the same is true if hit 'close' button with a blue laser

https://highfidelity.fogbugz.com/f/cases/7722/Add-onHover-Outline-to-Tablet-X-Button

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3584/HighFidelity-Beta-PR11450-0b95ff1876913257233db4cae845f377a6bb42c4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3595/HighFidelity-Beta-PR11450-0b95ff1876913257233db4cae845f377a6bb42c4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3604/HighFidelity-Beta-PR11450-0b95ff1876913257233db4cae845f377a6bb42c4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3604/HighFidelity-Beta-PR11450-0b95ff1876913257233db4cae845f377a6bb42c4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3652/HighFidelity-Beta-PR11450-ef732fb5475ad3711943c6b9d45d8326578e9d7e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3652/HighFidelity-Beta-PR11450-ef732fb5475ad3711943c6b9d45d8326578e9d7e.exe

**Comment by anshuman64** [comment]
Needs design feedback before going to QATesters

**Comment by cain-kilgore** [comment]
@anshuman64: Is this good to test?

**Comment by anshuman64** [comment]
@cain-kilgore Not yet, I'll let you know when

**Comment by anshuman64** [comment]
@ElderOrb the outline flickers a lot if you have it highlighted and move the tablet around. Is there any way to make it flicker less?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3990/HighFidelity-Beta-PR11450-ef732fb5475ad3711943c6b9d45d8326578e9d7e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3990/HighFidelity-Beta-PR11450-ef732fb5475ad3711943c6b9d45d8326578e9d7e.exe

**Comment by ElderOrb** [comment]
Looks like flickering happens due to overlays overlapping. I'm going to raise highlight above button overlay a bit to solve it

**Comment by ElderOrb** [comment]
Raising outline above tablet button overlay eliminated flickering in 'idle' state (button hovered, tablet grabbed) but I still see some occasional flickering if move tablet closer/farther fast. In general it seems like engine just to capable to recalculate all the positions fast enough.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4078/HighFidelity-Beta-PR11450-9c15af9fbebe8d8fac43f84b4bbe4e9ecf2ac030.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4078/HighFidelity-Beta-PR11450-9c15af9fbebe8d8fac43f84b4bbe4e9ecf2ac030.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4093/HighFidelity-Beta-PR11450-8c7462f01250b069ef14bed3e6ffa8a580390861.dmg

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4097/HighFidelity-Beta-PR11450-8c7462f01250b069ef14bed3e6ffa8a580390861.dmg

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4106/HighFidelity-Beta-PR11450-8c7462f01250b069ef14bed3e6ffa8a580390861.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4106/HighFidelity-Beta-PR11450-8c7462f01250b069ef14bed3e6ffa8a580390861.exe

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
### FAIL

This is easy to  break and I'd post a snapshot if it would let me show you how.

Works for lasers and with mouse

Stylus can be broken easily and repeatedly.

**Comment by Nex-Pro** [comment]
basically hold the tablet in the left hand as if gripping between thumb and index finger 

the right hand stylus will not highlight the X anymore

**Comment by anshuman64** [comment]
@Nex-Pro Do you think it's because your left stylus is inside the tablet as you are grabbing the tablet? This would render all highlighting to be dysfunctional

**Comment by Nex-Pro** [comment]
@anshuman64  Probably but it's a problem.

 Should be solvable.  if grabbing disable stylus , seems pretty obvious.

**Pull request merged**
