### PR TITLE
Updating OpenVR SDK, moving to plugin

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6d20d835e464ff05b7cccf5fb07bf83cb02fe13f available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hyperlogic** [comment]
I'll check this out, if you can fix the windows build.

    (ClCompile target) -> 
         ..\..\..\plugins\openvr\src\OpenVrDisplayPlugin.cpp(12): fatal error C1083: Cannot open include file: 'QMainWindow': No such file or directory [D:\jenkins\workspace\pull-request-win\build\plugins\openvr\openvr.vcxproj]
         D:\jenkins\workspace\pull-request-win\libraries\networking\src\UserActivityLogger.h(20): fatal error C1083: Cannot open include file: 'QNetworkReply': No such file or directory (..\..\..\plugins\openvr\src\ViveControllerManager.cpp) [D:\jenkins\workspace\pull-request-win\build\plugins\openvr\openvr.vcxproj]

**Comment by hifi-gustavo** [comment]
Build console output for commit: 211e53735a03145f3647110d988317beaf20f5e6 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by jherico** [comment]
@hyperlogic I think I've fixed it, however, there's a small issue.  Because the main app no longer links against the main OpenVR library, the bundle fixup doesn't copy the openvr_api.dll into the executable directory.  I'm working on figuring out how to make cmake detect that it's required.  If you want to test it you'll have to grab the 0.9.11 zip file and copy over the openvr_api.dll into the main interface directory manually.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4049cf5e5bc9988d7fe0f8764494ffea8aab72e3 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7c3b6da3c7818eb024c96b87732772d7a9ea79f available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ad5fa1b6a38825b222fdaa006ad13ce0156e784b available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f322b4dfef893687972dab71526b1cdf689d58f4 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hyperlogic** [comment]
Crashes on startup, log attached.  I don't have time right now to checkout the code and debug it manually on this machine, perhaps later today.

[hifi-log.txt](https://github.com/highfidelity/hifi/files/25753/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8948ce8176ba8408987b501e70d2a36e9911a1ad available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53e3ff04967137d9fe8a2e46df0c4d38a87e0be2 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4ff9a8ed5c99c875fb0eab56589da57d395b3458 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 590563670f09c2c48ce12a0a2277ce955d123f17 available at: https://gist.github.com/697b061296667c70ae95<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6273.dmg

**Pull request closed without merging**
