### PR TITLE
if not already logged in, show login dialog at launch-time

### PR DESCRIPTION
**Pull request by sethalves**
- if not already logged in, show login dialog at launch-time

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12667/HighFidelity-Beta-PR13940-1bea6c9.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12667/HighFidelity-Beta-PR13940-1bea6c9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12667/HighFidelity-Beta-Interface-PR13940-1bea6c9.dmg

**Comment by JeffClinton** [comment]
Hey @sethalves , either Evan or I will be working on the test cases for the login prompt.  It seems pretty straightforward for the most part, but if I recall you had some concerns about launching into certain areas?

If you have some examples of what you were thinking of I can make sure they get built into the test cases.

**Comment by sethalves** [comment]
closing this in favor of wayne's upcoming PR

**Pull request closed without merging**
