### PR TITLE
Fix and fill in JSDoc for MyAvatar flying-related functions

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

Proof read the JSDoc for the following MyAvatar functions:
- getFlyingDesktopPref
- getFlyingEnabled
- getFlyingHMDPref
- isFlying
- isInAir
- setFlyingDesktopPref
- setFlyingEnabled
- setFlyingHMDPref

You can view these at: http://ctrlaltstudio.com/downloads/hifi-dev/jsdoc/MyAvatar.html


https://highfidelity.manuscript.com/f/cases/17222

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13669/HighFidelity-Beta-PR14144-ea8e02a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13669/HighFidelity-Beta-Interface-PR14144-ea8e02a.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13674/HighFidelity-Beta-PR14144-ea8e02a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13674/HighFidelity-Beta-PR14144-ea8e02a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13674/HighFidelity-Beta-Interface-PR14144-ea8e02a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13674/HighFidelity-Beta-PR14144-ea8e02a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13674/HighFidelity-Beta-Interface-PR14144-ea8e02a.exe

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13950/HighFidelity-Beta-PR14144-ea8e02a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13950/HighFidelity-Beta-Interface-PR14144-ea8e02a.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13966/HighFidelity-Beta-PR14144-ea8e02a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13966/HighFidelity-Beta-PR14144-ea8e02a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13966/HighFidelity-Beta-Interface-PR14144-ea8e02a.dmg

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14027/HighFidelity-Beta-PR14144-ea8e02a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14027/HighFidelity-Beta-Interface-PR14144-ea8e02a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14027/HighFidelity-Beta-PR14144-ea8e02a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14027/HighFidelity-Beta-Interface-PR14144-ea8e02a.exe

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14055/HighFidelity-Beta-PR14144-ea8e02a.apk

**Pull request merged**
