### PR TITLE
Controllers Branch - Get conditional routes working

### PR DESCRIPTION
**Pull request by jherico**
This adds support for conditional routes, right now supporting the form...

`{ "from": "Keyboard.D", "when": "Keyboard.Shift", "to": "Actions.LATERAL_RIGHT" }`

I've also simplified the processing of mapping routes.  Rather than sorting by source and storing a `map<source, list<route>>` the routes are now stored as a simple `list<route>`.  This means that the order they're defined in the file is the order they will be processed.  For device mapping JSON files, which are all loaded into the `_defaultMapping` at the bottom of the mapping stack, the standard -> action mappings are loaded first, so they will be processed last.  

This also means that conditional routes need to be defined BEFORE non-conditional ones.  For instance, if I did this:

```
{ "from": "Keyboard.D", "to": "Actions.YAW_RIGHT" },
{ "from": "Keyboard.D", "when": "Keyboard.Shift", "to": "Actions.LATERAL_RIGHT" }
```

The conditional action would never be taken because the Keyboard.D input would always be consumed by the first line. This PR updates the keyboard mapping to reflect this.  I'm going to go through the rest of the commented C++ mapping and JSON files to update them, and they will either go in this PR or a later one.  We're approaching the point of parity with the current production build (discounting updating the scripts we've broken), so hopefully we should be able to drop this work branch soon.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cb05d3f003dc109d21466f077c69bb259aae280c available at: https://gist.github.com/8b16e06354795ba1829f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: eacd6af03232c15e5fc5220d046700eb52427fa3 available at: https://gist.github.com/8b16e06354795ba1829f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cd940325c2a9400a87fe860c2321207b176104e8 available at: https://gist.github.com/8b16e06354795ba1829f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a124d3b4332205436b73997079600f52c3dd03c0 available at: https://gist.github.com/8b16e06354795ba1829f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f0edc302bf351a8be5b22d6d2c60c10e3886ee8f available at: https://gist.github.com/8b16e06354795ba1829f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6128.dmg

**Comment by ZappoMan** [comment]
```
In file included from /data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/controllers/src/controllers/Route.h:13:0,
                 from /data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/controllers/src/controllers/Route.cpp:9:
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/controllers/src/controllers/Endpoint.h:44:35: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
         virtual const bool isPose() { return _input.isPose(); }
                                   ^
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/controllers/src/controllers/Endpoint.h:42:22: warning: ‘virtual void controller::Endpoint::apply(const controller::Pose&, const controller::Pose&, const Pointer&)’ was hidden [-Woverloaded-virtual]
         virtual void apply(const Pose& newValue, const Pose& oldValue, const Pointer& source) {}
                      ^
/data/jenkins/Jenkins/workspace/hifi-pull-request-ubuntu/libraries/controllers/src/controllers/Endpoint.h:58:22: warning:   by ‘virtual void controller::LambdaEndpoint::apply(float, float, const Pointer&)’ [-Woverloaded-virtual]
         virtual void apply(float newValue, float oldValue, const Pointer& source) override { _writeLambda(newValue); }

```

**Pull request merged**
