### PR TITLE
update some server console dependencies after npm audit

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13158/HighFidelity-Beta-PR14049-0381630.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13158/HighFidelity-Beta-PR14049-0381630.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13158/HighFidelity-Beta-Interface-PR14049-0381630.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13158/HighFidelity-Beta-PR14049-0381630.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13158/HighFidelity-Beta-Interface-PR14049-0381630.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by birarda** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14258/HighFidelity-Beta-PR14049-0381630.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14258/HighFidelity-Beta-PR14049-0381630.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14258/HighFidelity-Beta-Interface-PR14049-0381630.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14258/HighFidelity-Beta-PR14049-0381630.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14258/HighFidelity-Beta-Interface-PR14049-0381630.dmg

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by antoninahifi** [comment]
@conklin94122  PASS

**Pull request merged**
