### PR TITLE
 Prevent adding the same tablet url to the tabletApps list

### PR DESCRIPTION
**Pull request by druiz17**
For tableRoot.qml functions loadWebConent and loadQmlOnTop, prevent loading the new page if its already loaded

-Ticket - https://highfidelity.manuscript.com/f/cases/12290/HMD-Logging-in-to-High-Fidelity-account-through-the-Wallet-app-directs-user-to-login-sign-up-dialog

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Open the tablet
- Select the "Wallet" application
- Select the "Login" button.
- Enter valid credentials
- Select "log in" button

Test for both of these cases.
1) If wallet is NOT set up, user should be directed to the wallet setup wizard
2) If wallet IS set up, user should be directed to the homepage of the wallet application

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7168/app_12395_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7168/HighFidelity-Beta-PR12395-119a7554ee663cb8a01675d7f62fd9a875791354.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7168/HighFidelity-Beta-PR12395-119a7554ee663cb8a01675d7f62fd9a875791354.exe

**Comment by QAadahlin** [comment]
Currently Testing

**Comment by QAadahlin** [comment]
@conklin94122 Testing Completed for PR#12395. PASSED.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7248/app_12395_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7248/HighFidelity-Beta-PR12395-a194c8bc03852a89cd826bd53654bbfecd69735c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7248/HighFidelity-Beta-PR12395-a194c8bc03852a89cd826bd53654bbfecd69735c.dmg

**Pull request merged**
