### PR TITLE
78.1: Fix erroneous 'CMAKE_TOOLCHAIN_FILE has changed' errors on Jenkins

### PR DESCRIPTION
**Pull request by jherico**
RC 78.1 version of #14798

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16876/HighFidelity-Beta-PR14799-c710868.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16876/HighFidelity-Beta-Interface-PR14799-c710868.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16876/HighFidelity-Beta-PR14799-c710868.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16876/HighFidelity-Beta-Interface-PR14799-c710868.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16876/HighFidelity-Beta-PR14799-c710868.apk

**Comment by JeffClinton** [comment]
Currently testing

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16887/HighFidelity-Beta-PR14799-c710868.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16887/HighFidelity-Beta-PR14799-c710868.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16887/HighFidelity-Beta-Interface-PR14799-c710868.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16887/HighFidelity-Beta-PR14799-c710868.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16887/HighFidelity-Beta-Interface-PR14799-c710868.exe

**Pull request merged**
