### PR TITLE
fix domain-server permissions-grid usernames to be case insensitive

### PR DESCRIPTION
**Pull request by sethalves**
- usernames in domain-server permissions-grid are now case insensitive

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- experiment with capitalization in permissions-grid on domain-server settings page

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8a67850f2108fae22898d9b6dc87c71ed9adcc7 available at: https://gist.github.com/c07bc5a42c95d17181b0f4e34e03f46e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8097.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8097.dmg

**Comment by kevinmthomas-carpool** [comment]
testing

**Comment by kevinmthomas-carpool** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Successful.  Utilized various spellings of avatar name with various capital letters and lower case to which functioned normally when testing in ```localhost``` in combination with updating the settings page and relaunching server.

**Pull request merged**
