### PR TITLE
JavaScript exception in toggleAdvancedMovementForHandControllers.js (RC68)

### PR DESCRIPTION
**Pull request by wayne-chen**
- Fixing uncaught JavaScript exception in https://github.com/highfidelity/hifi/pull/13239.
https://highfidelity.manuscript.com/f/cases/15453/JavaScript-exception-in-toggleAdvancedMovementForHandControllers-js

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10224/HighFidelity-Beta-PR13260-19308c3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10224/HighFidelity-Beta-PR13260-19308c3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10224/HighFidelity-Beta-Interface-PR13260-19308c3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10224/HighFidelity-Beta-PR13260-19308c3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10224/HighFidelity-Beta-Interface-PR13260-19308c3.dmg

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
FAIL @conklin94122 Forward and Backward controls still do not function after Interface is relaunched with Advanced controls are enabled. toggling on/off Advanced controller settings does not reset movement controls
Log Included
[PR13260 hifi-log.txt](https://github.com/highfidelity/hifi/files/2058850/PR13260.hifi-log.txt)

**Comment by wayne-chen** [comment]
@qligmaloney I'm able to run this successfully on the PR build.  Can you please re-test this?

**Comment by wayne-chen** [comment]
Please re-test these when ready.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10283/HighFidelity-Beta-PR13260-1a128ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10283/HighFidelity-Beta-Interface-PR13260-1a128ab.exe

**Comment by wayne-chen** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10307/HighFidelity-Beta-PR13260-1a128ab.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10307/HighFidelity-Beta-PR13260-1a128ab.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10307/HighFidelity-Beta-Interface-PR13260-1a128ab.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10307/HighFidelity-Beta-PR13260-1a128ab.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10307/HighFidelity-Beta-Interface-PR13260-1a128ab.exe

**Comment by qligmaloney** [comment]
Currently testing

**Comment by qligmaloney** [comment]
PASS @conklin94122 Forward/Backward controls work after rebooting application with advanced movement option saved

**Pull request merged**
