### PR TITLE
[Worklist #21420] Implement Create button disabled state (details below).

### PR DESCRIPTION
**Pull request by 1P-Cusack**
* The create button icon is set to its disabled resource when the user
enters a domain where they have _neither_ Rez or TempRez permissions.
** If the user has either of the Rez permission levels then the normal edit-i.svg
icon is used and the user is able to create items as before.

* When the user clicks the button in this state, the INSUFFICIENT_PERMISSIONS_ERROR_MSG
is shown and creation menu is not shown.

* The disabled icon, edit-disabled.svg, is based on the edit-i.svg and is set to 33% opacity.

Item Ticket Link: https://worklist.net/21420

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1349/HighFidelity-Beta-PR10886-38b17eccc2f580821444dfafe7b76686dea8df67.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1349/HighFidelity-Beta-PR10886-38b17eccc2f580821444dfafe7b76686dea8df67.dmg

**Comment by CainFoool** [comment]
Testing shortly.

**Comment by CainFoool** [comment]
# Test Failed
Test | Result
-------- | --------
The create button icon is set to its disabled resource when the user enters a domain where they have neither Rez or TempRez permissions. | Fail
When the user clicks the button in this state, the INSUFFICIENT_PERMISSIONS_ERROR_MSG is shown and creation menu is not shown. | Pass

The Create Button only grabs it's permission when the Toolbar is loaded, therefore when switching the domains the enabled/disable state remains until you either Reload All Scripts or restart the Interface.

Let me know once this needs re-testing.
###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by 1P-Cusack** [comment]
@CainFoool and @AndrewMeadows: I've updated the pull request with a fix for the domain switching issue.  So it should be ready to re-testing.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1399/HighFidelity-Beta-PR10886-85111131da25995b14f4d636581311433fa227a1.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1399/HighFidelity-Beta-PR10886-85111131da25995b14f4d636581311433fa227a1.dmg

**Comment by CainFoool** [comment]
Testing.

**Comment by CainFoool** [comment]
# Test Passed
Test | Result
-------- | --------
The create button icon is set to its disabled resource when the user enters a domain where they have neither Rez or TempRez permissions. | Pass
When the user clicks the button in this state, the INSUFFICIENT_PERMISSIONS_ERROR_MSG is shown and creation menu is not shown. | Pass

Working all good now with the Domain Switching.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by CainFoool** [comment]
Update on this:

During another PR, I noticed an issue where the disabled Create icon wasn't appearing in HMD regardless of permission, and when you did not have permission and clicked an object, the bounding box would appear to let you edit.

**Comment by 1P-Cusack** [comment]
I saw that @CainFoool had mentioned that while testing another PR the create button at times wouldn't show up.  Locally, I'd been seeing issues with the buttons on the toolbar loading in general.  The buttons would take a while to load and at times appearing to pop in quite some time after entering a locations. I didn't think to much about it as I'd been seeing it before my having touched this area.  

After @CainFoool's comment, I took another look and nothing was immediately apparent when looking through the code which could be causing the issue.  Running a lint pass on the edit.js script showed a number items including some related to positioning and property retrieval.  The 3ee9d8b commit has those lint fixes; I've tested locally and I've not seen the issues I was seeing previously with the toolbar buttons loading/popping in.

@CainFoool:  Could you test with these changes and see if it helps what you were seeing? If you do see it again, could you note what other PR/changes you were testing with when you see the behavior?  Also what places?  Any additional detail you could provide should the issue re-occur will be useful.  Thanks!

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1498/HighFidelity-Beta-PR10886-3ee9d8b76640e8206722bd3d12fed649f2a23b8f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1498/HighFidelity-Beta-PR10886-3ee9d8b76640e8206722bd3d12fed649f2a23b8f.dmg

**Comment by CainFoool** [comment]
Hey @1P-Cusack: I'll give this a go now and let you know of the results.

**Comment by 1P-Cusack** [comment]
@CainFoool:  Thanks for re-testing!  When you say actively changing the permissions, do you mean altering the permissions of the user while the user is currently in that domain?

**Comment by CainFoool** [comment]
@1P-Cusack: Yup, changing the permissions on the Sandbox Server didn't update the icon when I switched permissions.

**Comment by 1P-Cusack** [comment]
Ah, okay.  The ticket specified that the only time that the status should be verified and enforced is when the user switches domains, so should the permissions change while they're within the domain to be affected nothing should occur.  The user will retain whatever permissions they had until the next time they trigger a session in that area.

**Comment by CainFoool** [comment]
That wasn't the case - the permissions had changed live without me having to re-switch, it was just the icon which wasn't updating.

**Comment by CainFoool** [comment]
@1P-Cusack: There was a change some time ago which led to some settings in the Sandbox not requiring a reboot of the server, this included Permissions as they were able to be updated live.

**Comment by themelissabrown** [comment]
"The ticket specified that the only time that the status should be verified and enforced is when the user switches domains,"
This ticket may have been written up prior to live changes being possible. I'm going to mark it QA passed and have the PM in charge assess if we also want to have you make that change to check permissions throughout. If so, we'll open a new WL task for it.

**Comment by CainFoool** [comment]
Sounds good!

**Comment by 1P-Cusack** [comment]
@themelissabrown:  Ok, thanks!

**Pull request merged**
