### PR TITLE
fix entity importing

### PR DESCRIPTION
**Pull request by sethalves**
- fix entity importing (broken by serverless-domain PR)

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- test importing entities
- run the tests from the serverless-domains PR (I'll copy them into a comment following this one)

**Comment by sethalves** [comment]
Serverless Domain Test Plan

Before testing
- unzip the folder and place all contents in AppData/High Fidelity PR#/Interface
http://headache.hungry.com/~seth/hifi/tutorial.zip
- rename models.json to models.domain.js and use this file as the serverless domain file

1. Loading serverless domain files (json and json.gz) using Goto address bar
   - type or copy a http/https url into the address bar
   - type file:///~/models.domain.json into the adddress bar

   * result - see #3
   
1. Going to a serverless domain from normal domain or startup. (your position in the serverless domain will always be (/0, -10, 0))
   - content should load (physics should be enabled once loaded)
   - should not be prompted by "unable to connect to domain" dialog
   - you should have edit rights in serverless-domain (create and delete entities).
   - test a script with local audio
   - test that you are able to bookmark serverless domains.
   * perform a smoke-tests (use testrail suites if applicable)

1. Going from serverless domain to normal domain
   - serverless domain content should deleted and not appear at the origin of the domain you just entered.
   - Once connected, make sure that you edit so entites are being relayed to everyone else.
   - if owner of domain check that you are able to replace content in entity-server
   * perform a smoke-tests (use testrail suites if applicable)

1. Test tablet applications that are domain dependent
   - People
     * should be still teleport to friends location/domain unless they are in serverless domain
     * have a friend make sure you appear unavailable while visiting a serverless domain and that you become available again once switching back to a normal domain

   - Goto
     * Clicking the home button or typing localhost in the address should take you to your sandbox

1. Check entity hyperlink functionality
   - Go to your sandbox
   - create an entity and set its link url to file:///~/models.domain.json
   - close CREATE
   - click on the entity with your mouse
   - confirm that you're now in the serverless domain

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8313/app_12724_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8313/HighFidelity-Beta-PR12724-bb101956a69ad5186bb854741f3c081839d2a73e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8313/HighFidelity-Beta-PR12724-bb101956a69ad5186bb854741f3c081839d2a73e.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Entity appears and server-less domain tests pass.

**Comment by conklin94122** [comment]
@sethalves Needs dev review

**Pull request merged**
