### PR TITLE
DO_NOT_MERGE: sanity-check for NaN avatar data in RC68

### PR DESCRIPTION
**Pull request by AndrewMeadows**
* debug PR just in case it is useful for tracking down crashes on Mac
* crash as soon as NaN is submitted to Bullet for any avatar

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10520/HighFidelity-Beta-PR13349-fa8468f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10520/HighFidelity-Beta-PR13349-fa8468f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10520/HighFidelity-Beta-Interface-PR13349-fa8468f.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10522/HighFidelity-Beta-PR13349-3b7f9b3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10522/HighFidelity-Beta-PR13349-3b7f9b3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10522/HighFidelity-Beta-Interface-PR13349-3b7f9b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10522/HighFidelity-Beta-PR13349-3b7f9b3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10522/HighFidelity-Beta-Interface-PR13349-3b7f9b3.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
@AndrewMeadows 
Here is 4 logs from 2 different macs. 
[Mac 1 Crash 1 hifi-log.txt](https://github.com/highfidelity/hifi/files/2095098/Mac.1.Crash.1.hifi-log.txt)
[Mac 1 Crash 2 hifi-log.txt](https://github.com/highfidelity/hifi/files/2095099/Mac.1.Crash.2.hifi-log.txt)
[Crash1111.txt](https://github.com/highfidelity/hifi/files/2095100/Crash1111.txt)
[Crash1105.txt](https://github.com/highfidelity/hifi/files/2095101/Crash1105.txt)

**Comment by AndrewMeadows** [comment]
None of those crashes hit the traps I laid.  Only Crash1105.txt looked like it had clues about the crash mode that was actually hit.

**Pull request closed without merging**
