### PR TITLE
RC 72 Tutorial - MS17378

### PR DESCRIPTION
**Pull request by misslivirose**
Change audio format to hopefully address volume / positional issue in MS 17378
https://highfidelity.manuscript.com/f/cases/17378/New-voice-over-in-the-Bubble-section-of-the-serverless-tutorial-is-directional-and-very-quiet

Test Plan: 
- Install client-only Interface from this build
- Go to Bubble station and verify that the audio now plays like the other stations

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12198/HighFidelity-Beta-PR13839-5ffe539.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12198/HighFidelity-Beta-Interface-PR13839-5ffe539.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12198/HighFidelity-Beta-PR13839-5ffe539.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12198/HighFidelity-Beta-Interface-PR13839-5ffe539.exe

**Comment by misslivirose** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12204/HighFidelity-Beta-PR13839-5ffe539.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12204/HighFidelity-Beta-PR13839-5ffe539.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12204/HighFidelity-Beta-Interface-PR13839-5ffe539.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12204/HighFidelity-Beta-PR13839-5ffe539.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12204/HighFidelity-Beta-Interface-PR13839-5ffe539.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

All audio zones are generally of the same volume, and cover the range of the zone without changing volume noticeably.

**Pull request merged**
