### PR TITLE
Tablet ui quick summon

### PR DESCRIPTION
**Pull request by sethalves**
- overlay tablets are pre-created and made invisible so that they appear quickly when summoned
- this has the side effect of the tablet not resetting to home screen when dismissed and resummoned

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6aac2eb338be3e7c66f6b378a6dd1f1124c33370 available at: https://gist.github.com/8b8d72aac9aeb72f6e4f2077142bb2d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-6aac2eb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-6aac2eb.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6aac2eb338be3e7c66f6b378a6dd1f1124c33370 available at: https://gist.github.com/8b8d72aac9aeb72f6e4f2077142bb2d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-6aac2eb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-6aac2eb.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9435c58c2cc4b0e91d32e7078fafc84b7f586aa6 available at: https://gist.github.com/8b8d72aac9aeb72f6e4f2077142bb2d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-9435c58.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-9435c58.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 023b01814eac118965ec5ebb455287190817b8cf available at: https://gist.github.com/8b8d72aac9aeb72f6e4f2077142bb2d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-023b018.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-023b018.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b1079d3719bd9aa7d9d679b4ef68ba5d8275ef17 available at: https://gist.github.com/8b8d72aac9aeb72f6e4f2077142bb2d9<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-b1079d3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9839-b1079d3.dmg

**Pull request closed without merging**
