### PR TITLE
fix washed out white ambient (by restoring tex)

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
I had thought that this ambient texture caused flickering, but on a retest it appears I had fixed it with other code juggling :circus_tent:.

QA:
- Make sure there is no flicker, with or without a zone set (see #https://github.com/highfidelity/hifi/pull/8444 for a description of this flickering).
- Make sure things in a default ambient (i.e. no zone) no longer appear washed out.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 372c52fea55b01469c8c99a8fa50384a87f71f3e available at: https://gist.github.com/f713715bcd22ecc3f5adb77ba3fe7002<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-372c52f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-372c52f.dmg

**Comment by Nex-Pro** [comment]
**PR #8550**

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**QA FAIL**


**Starting condition:** 
    Ensured no previous install of this PR.
    Ran Dev build and requested a reset of settings.
    Proceeded with installation.
    deleted interface ini.
    Selected not to copy content ensuring fresh content at localhost.
    Launched this build of interface by using the 'go home'.
    Searched entity list for "zone" to ensure there were no zones that I was unaware of.


QA:

**Make sure there is no flicker, with or without a zone set (see #8444 for a description of this flickering).: FAIL**

1. I rotated my view and observed no flickering.

2. I set the default home skybox to invisible. Rotated view and no flickering was apparent. Textures became washed out.

3. Created a new zone at my local position via edit toolbar. Rotated my view and observed very strong flickering( like lightning illuminating all the textures).

3a. I rotated my view slowly to observe if the flickering was related to specific yaw angles. This could not be determined. The flickering frequency  seemes related to speed of camera viewing angle change.

4. Set the new zone as skybox. Rotated view. No flickering was apparent.



8850b


**Make sure things in a default ambient (i.e. no zone) no longer appear washed out.: FAIL** See above.

**Comment by Nex-Pro** [comment]
@zzmp ^ :(

**Comment by hifi-gustavo** [comment]
Build console output for commit: 441005bba02aaa2195b8e9a32e58e08329f0ea5b available at: https://gist.github.com/f713715bcd22ecc3f5adb77ba3fe7002<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-441005b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-441005b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c8ff6ee4cc7108e3bf84f813e692522e509372a3 available at: https://gist.github.com/f713715bcd22ecc3f5adb77ba3fe7002<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-c8ff6ee.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8550-c8ff6ee.dmg

**Pull request merged**
