### PR TITLE
fixing tablet in 3d person

### PR DESCRIPTION
**Pull request by druiz17**
Allow the laser to work on the tablet in 3d person view

ticket - https://highfidelity.fogbugz.com/f/cases/8675/The-tablet-doesn-t-work-in-third-person-camera

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
 - https://highfidelity.testrail.net/index.php?/cases/view/115&group_by=cases:section_id&group_order=asc&group_id=27 (please perform this in first and 3rd person view)

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4971/HighFidelity-Beta-PR11822-9564b7567b941b0c1bbc2cd749c14b5948b00eec.dmg

**Comment by YuppyPlays** [comment]
@druiz17  Gustavo failed.

**Comment by SamGondelman** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4976/HighFidelity-Beta-PR11822-9564b7567b941b0c1bbc2cd749c14b5948b00eec.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4976/HighFidelity-Beta-PR11822-9564b7567b941b0c1bbc2cd749c14b5948b00eec.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Solid **Pass** - TestRail Results: https://highfidelity.testrail.net/index.php?/tests/view/13379&group_by=cases:section_id&group_order=asc&group_id=27

**Pull request merged**
