### PR TITLE
RC64: Commerce: Inspection Certificate Redesign (Fixed!)

### PR DESCRIPTION
**Pull request by zfox23**
Redesigns the Inspection Certificates for clarity and visual appeal. Also adds "Purchase Price" to the cert.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
- You'll need two people for this test plan.

1. Have Avatar A _and_ Avatar B rez the following entities in Domain A (you should rez a total of 8 entities):
    1. A regular entity that the avatar owns
    2. An avatar entity (wearable) that the avatar owns
    3. An avatar entity (wearable) that is rezzed by the avatar that fails static cert verification
        - You can achieve this by rezzing a regular wearable, then modifying the ModelURL of that entity.
    4. An avatar entity (wearable) that is rezzed by the avatar that it doesn't own 
        - You can achieve this by exporting the JSON of someone else's wearable, then rezzing it yourself.
2. Have Avatar A and Avatar B each pull up the Inspection Certificate all eight of these entities. Inspect each entity one at a time, verifying that there are no visual glitches with the certificates and that they display information pertinent to the validity of the certificate. For example, verify that the certificate associated with the entity rezzed in (3) mentions that the entity was modified and displays a grey background.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7046/app_12372_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7049/app_12372_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7065/app_12372_PR.apk

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7068/app_12372_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7068/HighFidelity-Beta-PR12372-ecc0a2f43bb98974fea6623e1fa1a31d73afa545.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7068/HighFidelity-Beta-PR12372-ecc0a2f43bb98974fea6623e1fa1a31d73afa545.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. Certificates missing information for items in My Purchases, and items can become invisible in the domain (see attached video).

@conklin94122 

https://drive.google.com/open?id=1qB5ZvW38ZlMz-lDCmvGUnR2P0WQtFOzS

**Comment by zfox23** [comment]
@sbennett77 - I watched your video. The certificate present in the old video is of the old style. The JPG that defines that background is not even present in the repository anymore. I am not sure how you are seeing that certificate. Do you have any idea how that's possible?

The fact that "items can become invisible in the domain" seems problematic, but is not due to this PR. This PR does not affect rezzing behavior, nor does it touch rezzing code.

**Comment by zfox23** [comment]
@sbennett77 i just downloaded [the latest build](https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7068/HighFidelity-Beta-PR12372-ecc0a2f43bb98974fea6623e1fa1a31d73afa545.exe) from this PR and cannot get the cert to display the old style.

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by QAadahlin** [comment]
Passed.

@conklin94122

**Pull request merged**
