### PR TITLE
avatar preferences chooser modal web

### PR DESCRIPTION
**Pull request by howard-stearns**
When the avatar marketplace is chosen from avatar preferences, let it be moveable so that the user can move it aside to see their avatar.

https://app.asana.com/0/32622044445063/83808273856060

### CODE REVIEW

**Comment by howard-stearns** [comment]
To test:
0. Click on market button (from edit.js) and observe that the marketplace Web page can be moved and resized. Dismiss it.
1. Go to Settings -> Avatar -> Avatar Basics -> Appearance Browse. Observe that this window is now also moveable and resizable as well. However, it stays modal in that you cannot put the preferences window on to top of it. Make sure the Wear buttons still work.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 91b0f6931238ae9b9c061ff9fc97a9828f6fccca available at: https://gist.github.com/05c341b2c2cc62b1fcef<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6952.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6952.dmg

**Comment by nbq** [comment]
Testing this now

**Comment by nbq** [comment]
I have tested 0 and 1 and both work as described. For 1 I found that the avatar listing page was modal and the preferences window always went behind it. The Wear buttons worked just fine.

**Comment by imgntn** [comment]
looks good to me,  win10

**Pull request merged**
