### PR TITLE
FB11569 Avatar island checkout brings empty tablet view

### PR DESCRIPTION
**Pull request by ElderOrb**
fix for https://highfidelity.fogbugz.com/f/cases/11569/Avatar-island-checkout-brings-empty-tablet-view

** Test plan **

1. Join 'AvatarIsland' domain
2. Go to checkout station get close to checkout terminal
3. Tablet should appear 
4. Ensure it *doesn't* show empty blue screen but instead shows one of the following (dependently on whether wallet was configured or not, you are logged in or not etc. ): 

- prompt to set up wallet
- purple check out instruction page

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6485/app_12219_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6486/app_12219_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6486/HighFidelity-Beta-PR12219-5cba17f304568caea4103f8ada63b482114a7175.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6490/app_12219_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6490/HighFidelity-Beta-PR12219-5cba17f304568caea4103f8ada63b482114a7175.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6490/HighFidelity-Beta-PR12219-5cba17f304568caea4103f8ada63b482114a7175.dmg

**Comment by changxc** [comment]
** Test plan **

    Join 'hifiqa-master' domain
    in HMD, grab a wearable and put on your avatar. 
    Open your tablet 
 (1) make sure you are not logged in
    Go to checkout station get close to checkout terminal
    Tablet should appear
    Ensure it shows purple check out instruction page
    scan the small item, it brings to marketplace page, which ask you to sign in / set up wallet. please complete the process as instructed
(2) now log out, close and reopen interface and log in / set up wallet, make sure you have HFC
    then grab item, go to checkout station
    Tablet should appear
    Ensure it shows purple check out instruction page
    scan the small item, it brings to marketplace page, and you can complete the purchase

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:


Join 'hifiqa-master' domain **Can only do this when logged in**
in HMD, grab a wearable and put on your avatar.  **Check**
Open your tablet **Check**

(1) make sure you are not logged in**Cannot connect when not logged in, says lack of permissions**
Go to checkout station get close to checkout terminal **Cannot do this due to (1)**
Tablet should appear **Cannot do this due to (1)**
Ensure it shows purple check out instruction page **Cannot do this due to (1)**
scan the small item, it brings to marketplace page, which ask you to sign in / set up wallet. please complete the process as instructed **Cannot do this due to (1)**
(2) now log out, close and reopen interface and log in / set up wallet, make sure you have HFC
then grab item, go to checkout station **Bit confused as I was already logged out for initial test, when logging in this all works as expected.**
Tablet should appear **Check**
Ensure it shows purple check out instruction page **Check, after wallet password is entered and re-enter the zone to trigger purple checkout.**
scan the small item, it brings to marketplace page, and you can complete the purchase **Check**


**Fail** @conklin94122

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by changxc** [comment]
Please do no merge this PR

Proposing different approach - could we Fix external script (@misslivirose ? )Thank you

**Pull request closed without merging**
