### PR TITLE
Add stutter tracking

### PR DESCRIPTION
**Pull request by jherico**
Add a stat for stutters per second (the number of additional times a frame was scanned out to the display without reprojection)

## Testing

On an AMD system, or on an nVidia system running release Steam, or running Steam Beta with asyncronous reprojection turned off, load up a scene.  The stutter rate should occasionally rise above 0 indicating the number of stutters per second that you're encountering.  

You can also test by going to `hifi://dreaming` and moving your head so close to the procedural balls that they fill your field of view.  The shaders will consume so much GPU that it will trigger stutter on any hardware.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9d8e4d89823a8797456d5fa89fed0952c872de68 available at: https://gist.github.com/9c6e5263c354ed02d938aec07691c526<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-9d8e4d8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-9d8e4d8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c7d68aa9cf16a3e5433246858267ca5cb48ed21d available at: https://gist.github.com/9c6e5263c354ed02d938aec07691c526<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-c7d68aa.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-c7d68aa.dmg

**Comment by cozza13** [comment]
testing

**Comment by hifi-gustavo** [comment]
Build console output for commit: 162f24decd7cb736cc722c933374aebeb0ad7f7a available at: https://gist.github.com/9c6e5263c354ed02d938aec07691c526<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-162f24d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9047-162f24d.dmg

**Comment by cozza13** [comment]
testing

**Comment by cozza13** [comment]
confirmed

**Pull request merged**
