### PR TITLE
Fix non self-sufficient headers

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by Atlante45** [comment]
This doesn't change any logic code. It merely re-orders headers and adds/removes some forward declarations.
No QA needed.

[ticket](https://highfidelity.manuscript.com/f/cases/14824/Lots-of-headers-in-the-codebase-are-not-self-sufficient)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9535/app_13108_PR_da9fb9c751a20b8d915ed657c5056cb4fe030d37.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9535/HighFidelity-Beta-PR13108-da9fb9c751a20b8d915ed657c5056cb4fe030d37.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9535/HighFidelity-Beta-Interface-PR13108-da9fb9c751a20b8d915ed657c5056cb4fe030d37.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9539/app_13108_PR_5303d2abdc46c80d1a677cb994e17ce56cd7643a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9541/app_13108_PR_845630212c3b4cb1484eb1d5d687aae32648e197.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9541/HighFidelity-Beta-PR13108-845630212c3b4cb1484eb1d5d687aae32648e197.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9541/HighFidelity-Beta-Interface-PR13108-845630212c3b4cb1484eb1d5d687aae32648e197.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9542/app_13108_PR_5a3773ba72811d8dfbe04ad0c2703adc87147764.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9542/HighFidelity-Beta-PR13108-5a3773ba72811d8dfbe04ad0c2703adc87147764.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9542/HighFidelity-Beta-Interface-PR13108-5a3773ba72811d8dfbe04ad0c2703adc87147764.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9542/HighFidelity-Beta-PR13108-5a3773ba72811d8dfbe04ad0c2703adc87147764.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9542/HighFidelity-Beta-Interface-PR13108-5a3773ba72811d8dfbe04ad0c2703adc87147764.exe

**Pull request merged**
