### PR TITLE
fix the last of the current override warnings for OS X

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7738a0a346535f92b1fc5c0a429e0969edf85528 available at: https://gist.github.com/6f08e5225c63dac16f9b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7006.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7006.dmg

**Comment by huffman** [comment]
@birarda This has merge conflicts

**Comment by nbq** [comment]
Tested this PR as is (even with conflicts) and it runs fine on my mac. I was able to TP, create objects, edit objects, etc. In overall usage it seems to work just fine and exits with no crashes.

**Comment by huffman** [comment]
I will merge once it compiles

**Comment by hifi-gustavo** [comment]
Build console output for commit: 93530fca72fa36ff5422cc5d8d97f4f25c034d6c available at: https://gist.github.com/6f08e5225c63dac16f9b<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7006.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7006.dmg

**Pull request merged**
