### PR TITLE
WL 21540 - Make Rotation using Vive Controller Work

### PR DESCRIPTION
**Pull request by cain-kilgore**
> In desktop mode:
> 1. Enable advanced movement with handcontrollers
> 2. Open Settings > Controller Settings
> 3. Enable "Use Vive devices in desktop mode"
> 4. Try using the thumbpad on your left Vive controller to move around. It should work
> 5. Try using the thumbpad on your right Vive controller to rotate your avatar. DOES NOT WORK.
> 
> Make the rotation work as expected.

[WL 21540](https://worklist.net/21540)

## Test Plan
1. Enabled Advanced Movement with Hand Controllers
2. Open Settings > Controller Settings and enable "Use Vive Devices in Desktop Mode"
3. Try using the Thumbpad on your Left Controller to Move Around - it should work as expected.
4. Try using the Thumbpad on your Right Controller to Snap Rotate - it should work as expected.
5. Confirm that movement still works normally in HMD

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3406/HighFidelity-Beta-PR11399-320c6e6769f7d8c0bb156acf49f2c1cf22b08c0e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3406/HighFidelity-Beta-PR11399-320c6e6769f7d8c0bb156acf49f2c1cf22b08c0e.exe

**Comment by cain-kilgore** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3408/HighFidelity-Beta-PR11399-320c6e6769f7d8c0bb156acf49f2c1cf22b08c0e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3408/HighFidelity-Beta-PR11399-320c6e6769f7d8c0bb156acf49f2c1cf22b08c0e.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by anshuman64** [comment]
Go ahead and look @YuppyPlays . I checked too and it works well. Nice job!

**Comment by cain-kilgore** [comment]
Woot @anshuman64 :D

**Comment by YuppyPlays** [comment]
Testing complete:

Enabled Advanced Movement with Hand Controllers **Check**
Open Settings > Controller Settings and enable "Use Vive Devices in Desktop Mode" **Check**
Try using the Thumbpad on your Left Controller to Move Around - it should work as expected. **Check**
Try using the Thumbpad on your Right Controller to Snap Rotate - it should work as expected. **Check**
Confirm that movement still works normally in HMD **Check**

All looks good to me, **Pass** Handy to have the mouse not taken away using this :)

**Comment by cain-kilgore** [comment]
Sweet!

**Pull request merged**
