### PR TITLE
WorkList #21794: Modify inspect.js to work with Avatars as well as entities

### PR DESCRIPTION
**Pull request by Triplelexx**
Following on from previous merged PR it was suggested the script should be moved from archive.

Does this location seem more suitable? @RyanDowne @MiladNazeri 
Let me know if anything further is desired.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8829/app_12906_PR_86cfb1448a19eee833920804515a55eccd2c3698.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8829/HighFidelity-Beta-PR12906-86cfb1448a19eee833920804515a55eccd2c3698.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8829/HighFidelity-Beta-Interface-PR12906-86cfb1448a19eee833920804515a55eccd2c3698.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8829/HighFidelity-Beta-PR12906-86cfb1448a19eee833920804515a55eccd2c3698.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8829/HighFidelity-Beta-Interface-PR12906-86cfb1448a19eee833920804515a55eccd2c3698.exe

**Comment by hyperlogic** [comment]
No QA is necessary for this.

**Pull request merged**
