### PR TITLE
Make avatar's mouths move again

### PR DESCRIPTION
**Pull request by zfox23**
Oh no...

Test Plan:
1. Avatars A and B should enter a domain and look at each other.
2. Make Avatar B speak by speaking into the microphone.
3. Avatar A should see Avatar B's mouth move.
4. Slap me for missing this in code review.

### CODE REVIEW

**Comment by OmegaHeron** [comment]
Will QA this.

**Comment by birarda** [comment]
I hate myself. This is what you get for committing code at 10pm.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 39587d53084a4349b7b6c21b9e18c392239e8f36 available at: https://gist.github.com/bf4599e4a73fc1874d10521f28bcb79a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10203-39587d5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10203-39587d5.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10 and Ubuntu 16.04
QA Pass

Interface A this PR Win 10, Interface B this PR Ubuntu

Interface A speaks, Interface B sees mouth move
Interface B speaks, Interface A sees mouth move
Checked that I could see my own mouth movement on A and B with mirror mode as well.
Interface A with HMD and Touch controls slaps Interface B -- removing necessity of slapping any real peoples.

All kidding aside - as a note for future testing... it helps to remind that we should, at some point, use an AV that has a mouth that can move.  Starting from clean installs (as we should do) we end up with stick figure... it's easy to overlook something like this in all the bazillion other things that are outlined for testing.

**Comment by zfox23** [comment]
Great point, @OmegaHeron. I'll make sure to include that in any related future test plans.

**Comment by zfox23** [comment]
...Build failed because of some strange directory error on Jenkins. I'm merging this.

**Pull request merged**
