### PR TITLE
Fixing the default value for the TOneMapping curve

### PR DESCRIPTION
**Pull request by samcake**
and cleaning the code into the ToneMappingEffect file

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5863e340af253586217bf4ef18eae36205b3fa1e available at: https://gist.github.com/549b9bc7f801dcd1c1dc<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6974.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR6974.dmg

**Comment by judasshuffle** [comment]
Just tried it  the shadows aa and ao disappear in rift mode.

**Comment by zzmp** [comment]
@judasshuffle can you confirm that that wasn't happening already?

**Comment by judasshuffle** [comment]
was happening already well it is in the normal 4069 build

**Comment by zzmp** [comment]
Ok, documented it as a bug. I believe I introduced it when shadow/AO was added to the graphics menu. Thanks for checking.

**Pull request merged**
