### PR TITLE
Case 20816: install on android (Mac and Windows installers)

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/20816/
# Description
Updates the INSTALL readme.

nitpick is now installed by the High Fidelity installer on Windows AND Mac.
Nitpick is part of the development and PR builds, and is not part of the production build.
# Testing
Windows
1.  Download PR.
2.  Verify that a folder named nitpick is located in the installation folder
3.  Enter that folder and verify that nitpick.exe exists
4.  Double click on that file and verify that nitpick runs.
Mac
1.  Download the PR
2.  Verify that the DMG file contains the nitpick app
3.  Verify that the app runs

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16778/HighFidelity-Beta-PR14783-ce90b62.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16778/HighFidelity-Beta-Interface-PR14783-ce90b62.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16778/HighFidelity-Beta-PR14783-ce90b62.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16778/HighFidelity-Beta-Interface-PR14783-ce90b62.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16779/HighFidelity-Beta-PR14783-79f096f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16781/HighFidelity-Beta-PR14783-8871621.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16781/HighFidelity-Beta-PR14783-8871621.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16781/HighFidelity-Beta-Interface-PR14783-8871621.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16783/HighFidelity-Beta-PR14783-7a957d8.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16783/HighFidelity-Beta-PR14783-7a957d8.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16783/HighFidelity-Beta-Interface-PR14783-7a957d8.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16783/HighFidelity-Beta-PR14783-7a957d8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16783/HighFidelity-Beta-Interface-PR14783-7a957d8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16784/HighFidelity-Beta-PR14783-e9ffa05.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16784/HighFidelity-Beta-PR14783-e9ffa05.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16784/HighFidelity-Beta-Interface-PR14783-e9ffa05.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16785/HighFidelity-Beta-PR14783-8223e04.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16785/HighFidelity-Beta-Interface-PR14783-8223e04.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16790/HighFidelity-Beta-PR14783-bee8623.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16790/HighFidelity-Beta-PR14783-bee8623.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16790/HighFidelity-Beta-Interface-PR14783-bee8623.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16791/HighFidelity-Beta-PR14783-94d7414.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16795/HighFidelity-Beta-PR14783-f248beb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16795/HighFidelity-Beta-PR14783-f248beb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16795/HighFidelity-Beta-Interface-PR14783-f248beb.dmg

**Comment by qaAdamSmith82** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17076/HighFidelity-Beta-PR14783-f248beb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17076/HighFidelity-Beta-PR14783-f248beb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17076/HighFidelity-Beta-Interface-PR14783-f248beb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17076/HighFidelity-Beta-PR14783-f248beb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17076/HighFidelity-Beta-Interface-PR14783-f248beb.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing (For 2 hours, forgot to tag)

**Comment by qaAdamSmith82** [comment]
QA Fail - The Mac version of Nitpick that comes with the installer does not work.  Users get this message
screen shot 2019-02-06 at 1 40 00 pm
Expected results:
User follows instructions on the Readme and the version of Nitpick included with the installer runs

Actual results:
User follows instructions on the Readme and the Mac version of Nitpick included with the installer does not run.

Once the readme is corrected I will pass

**Comment by NissimHadar** [comment]
Readme has been updated - the adb download link has been cruelly changed.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17098/HighFidelity-Beta-PR14783-89eff91.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17098/HighFidelity-Beta-PR14783-89eff91.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17098/HighFidelity-Beta-Interface-PR14783-89eff91.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17098/HighFidelity-Beta-PR14783-89eff91.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17098/HighFidelity-Beta-Interface-PR14783-89eff91.exe

**Comment by qaAdamSmith82** [comment]
Currently Testing - Mac

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17133/HighFidelity-Beta-PR14783-03ad14c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17133/HighFidelity-Beta-PR14783-03ad14c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17133/HighFidelity-Beta-Interface-PR14783-03ad14c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17133/HighFidelity-Beta-PR14783-03ad14c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17133/HighFidelity-Beta-Interface-PR14783-03ad14c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17140/HighFidelity-Beta-PR14783-cf83124.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17140/HighFidelity-Beta-PR14783-cf83124.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17140/HighFidelity-Beta-Interface-PR14783-cf83124.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17140/HighFidelity-Beta-PR14783-cf83124.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17140/HighFidelity-Beta-Interface-PR14783-cf83124.exe

**Pull request merged**
