### PR TITLE
add support for avatar licenses in FST files

### PR DESCRIPTION
**Pull request by ZappoMan**
Some avatar FST files might contain special licenses, if so, when you attempt to wear them, we will display the license and ask you to agree to the license.

### CODE REVIEW

**Comment by ZappoMan** [comment]
Testing Notes:
- smoke test
- wear an avatar from the examples/browse... notice that it doesn't do anything differently... and still works
- to test the license behavior: Drag this link onto the interface window... it should pop up the license and ask if you want to wear the avatar.  [example](http://hifi-content.s3.amazonaws.com/Avatars/production/priscilla/priscilla.fst)

Implements this feature: https://app.asana.com/0/26320649018758/110205531285831

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4b3b917af67e92118c0ea5b15a1d6db9959e3c2e available at: https://gist.github.com/6e4f984f621526fe1827ab488caf7172<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7657.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7657.dmg

**Comment by Nex-Pro** [comment]
testing this

**Comment by Nex-Pro** [comment]
This works if you drag the link into the interface window. Avatar does not load if licence is declined. Avatar loads if licence is accepted.

However pasting the link into the avatar settings dialog bypasses the licence screen and loads the avatar regardless.

In addition the agreement to the licence does not persist across avatar changes. 
User has to agree to the licence each time.

Subsequent dragging of the link whilst wearing the avatar prompts another licence pop-up which you can decline leaving you wearing the avatar.

The avatar persists on restart and no licence pops up.

It is possible to load this avatar whilst logged out agree to the licence and then log in. This might potentially be a problem.

Let me know if this is sufficient testing.

**Comment by howard-stearns** [comment]
@RyanDowne us know if it is NOT ok that, e.g., license must be answered each session.
In the mean time, merging based on your QAApproved label.

**Pull request merged**
