### PR TITLE
Fix MS16088: Prevent long usernames from overlapping HFC logo in Wallet Home

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS16088](https://highfidelity.fogbugz.com/f/cases/16088).

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
1) Create a new High Fidelity account with a username that is 17+ characters long 
2) Select the Wallet app from the toolbar
3) Go through the steps to complete the wallet setup wizard
4) Verify that the HFC logo DOES NOT overlap the ellipses on Wallet homepage

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10841/HighFidelity-Beta-PR13446-6fce643.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10841/HighFidelity-Beta-PR13446-6fce643.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10841/HighFidelity-Beta-Interface-PR13446-6fce643.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10841/HighFidelity-Beta-PR13446-6fce643.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10841/HighFidelity-Beta-Interface-PR13446-6fce643.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
wallet

**Pull request merged**
