### PR TITLE
Use key codes for entity camera keys

### PR DESCRIPTION
**Pull request by dback2**
Fixes: https://highfidelity.manuscript.com/f/cases/edit/17125

Test Plan:
- Enter Interface in desktop mode
- Open Create app and select any entity
- Press F on keyboard to focus camera on selected entity
- While in entity camera, press and hold the following keys to verify their expected behavior:

A:  orbit left
D:  orbit right
W:  orbit forward
S:  orbit backward
E:  orbit up
C:  orbit down
Left arrow:  orbit left
Right arrow:  orbit right
Up arrow:  orbit forward
Down arrow:  orbit backward

- For each above key, press and hold the key and verify that once clicking away from the Interface window the key is considered released

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11786/HighFidelity-Beta-PR13735-cdbf756.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11786/HighFidelity-Beta-PR13735-cdbf756.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11786/HighFidelity-Beta-Interface-PR13735-cdbf756.exe

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11869/HighFidelity-Beta-PR13735-cdbf756.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11869/HighFidelity-Beta-PR13735-cdbf756.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11869/HighFidelity-Beta-Interface-PR13735-cdbf756.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11869/HighFidelity-Beta-PR13735-cdbf756.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11869/HighFidelity-Beta-Interface-PR13735-cdbf756.exe

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Paused Testing

**Comment by QliCknox** [comment]
Resuming Testing

**Comment by QliCknox** [comment]
Pass @conklin94122 

User is able to control their view with the aforementioned keys and not see their view spin when clicking out of the Interface.

**Pull request merged**
