### PR TITLE
Make Connection class a Qt-child of Socket class

### PR DESCRIPTION
**Pull request by SimonWalton-HiFi**
Ticket: https://highfidelity.manuscript.com/f/cases/20564/

This ensures the Connection class's associated thread is the NodeList thread so slots (etc) run there.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16487/HighFidelity-Beta-PR14723-b53fcb2.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16487/HighFidelity-Beta-PR14723-b53fcb2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16487/HighFidelity-Beta-Interface-PR14723-b53fcb2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16488/HighFidelity-Beta-PR14723-024cb70.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16488/HighFidelity-Beta-PR14723-024cb70.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16488/HighFidelity-Beta-Interface-PR14723-024cb70.exe

**Comment by antoninahifi** [comment]
currently testing

**Comment by antoninahifi** [comment]
Pass
Tested:
- 5 different bots in sandbox (2 run using pool and manually run ac)
- ac/mixers restart
- connect/disconnect to sandbox
- avatars/wearables change including rWatch

**Pull request merged**
