### PR TITLE
fix crash on startup

### PR DESCRIPTION
**Pull request by sethalves**
- fix a crash-on-startup

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- smoke test

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/2025/crashes-in-CharacterController-postSimulation

**Comment by hifi-gustavo** [comment]
Build console output for commit: b31acc421a7eb38607910f678a95d082ce81dd8c available at: https://gist.github.com/bbf80d4e72fdac2670410057e127c99a<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8866-b31acc4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8866-b31acc4.dmg

**Comment by Nex-Pro** [comment]
In progress.

**Comment by Nex-Pro** [comment]
### PR #8866

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive


## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** FAILURE
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: crazy frame rates in Desktop mode.


Clicking go home was I was sent to /0,0,0 see screengrab
Hitting the house(home) icon on the destination bar or typing localhost sent me to localhost correctly.
Restarting interface while at localhost invoked the same 'unable to connect to this domain' popup.
Saw ridiculous framerates in desktop mode. See below.


HMD
**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |89 |90 |90
**Present New Rate**: |90 |90 |88
**CPU Buffer Count**: |2308 |4476 |2746
**GPU Buffer Count**: |877 |1479 |667
**CPU Memory Usage**: |29990912 |71081984 |36188160
**GPU Memory Usage**: |18518016 |47464448 |17330176
**CPU Texture Count**: |195 |301 |324
**GPU Texture Count**: |168 |267 |147
**GPU Transfer Count**: |0 |0 |7
**CPU Texture Memory Usage**: |52511624 |567927312 |846038064
**GPU Texture Memory Usage**: |440762368 |1433567232 |372424704
**GPU Virtual Memory Usage**: |991245317|2304381631|1150134794
**Triangle Count**: |123110 |469388 |490887
**Triangle Rate**: |11191818 |46938800 |44626090
**API Drawcall Count**: |41 |127 |137
**Drawcall Count**: |5922 |480 |263
**Drawcall Rate**: |538363 |48000 |23909
**State Changes Texture Count**:|79 |157 |194
**Pipeline Count**: |40 |39 |39
**Item Opaques**: |29 |156 |136
**Item Translucents**: |24 |37 |26
**Item Lights**: |0 |30 |8
**Timing Opaques**: |0.218 |0.506 |0.544
**Timing Translucents**: |0.061 |0.03 |0.108
**Timing Lighting**: |0.145 |0.115 |0.132
**Render Frame**: |1.272 |1.558 |1.56

Desktop.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |408 |90 |388
**Present Rate**: |405 |90 |383
**Present New Rate**: |249 |90 |214
**CPU Buffer Count**: |2098 |4476 |4271
**GPU Buffer Count**: |670 |1479 |962
**CPU Memory Usage**: |22257664 |71081984 |65855488
**GPU Memory Usage**: |12845056 |47464448 |27283456
**CPU Texture Count**: |195 |301 |346
**GPU Texture Count**: |162 |267 |248
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |87217480 |567927312 |360166832
**GPU Texture Memory Usage**: |448757760 |1433567232 |728907776
**GPU Virtual Memory Usage**: |751906676|2304381631|999165022
**Triangle Count**: |235353 |469388 |483059
**Triangle Rate**: |78451000 |46938800 |161019666
**API Drawcall Count**: |219 |127 |345
**Drawcall Count**: |5847 |480 |2145
**Drawcall Rate**: |1949000 |48000 |715000
**State Changes Texture Count**:|379 |157 |547
**Pipeline Count**: |114 |39 |104
**Item Opaques**: |216 |156 |258
**Item Translucents**: |90 |37 |59
**Item Lights**: |16 |30 |13
**Timing Opaques**: |0.97 |0.506 |0.709
**Timing Translucents**: |0.199 |0.03 |0.197
**Timing Lighting**: |0.459 |0.115 |0.167
**Render Frame**: |2.976 |1.558 |2.053

as you can see at some moment after leaving dev-playa and switching to desktop my (reported) framerates went through the roof.

connection issue
connection issue 2

**Pull request merged**
