### PR TITLE
Pr 11614 for rc 57

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4222/HighFidelity-Beta-PR11615-5e6c0870e7d20cfd43a1a78531bd5dd2676d9ee6.dmg

**Comment by marko8904** [comment]
build this please

**Comment by marko8904** [comment]
build this please

**Comment by sethalves** [comment]
## Test Plan
- same plan as https://github.com/highfidelity/hifi/pull/11614

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4227/HighFidelity-Beta-PR11615-5e6c0870e7d20cfd43a1a78531bd5dd2676d9ee6.dmg

**Comment by thoys** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4229/HighFidelity-Beta-PR11615-5e6c0870e7d20cfd43a1a78531bd5dd2676d9ee6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4229/HighFidelity-Beta-PR11615-5e6c0870e7d20cfd43a1a78531bd5dd2676d9ee6.exe

**Pull request merged**
