### PR TITLE
Open feed in tablet after sharing snapshot from tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
- If using the tablet in desktop mode. after sharing a snapshot the feed is opened in the tablet, otherwise it is opened in a window.
- If using the tablet in HMD mode. ditto.

**Comment by hifi-gustavo** [comment]
Build console output for commit: c618e8e0018217c8867320ee6a0598686d602337 available at: https://gist.github.com/a8ef9249f02354cfd0dcb857b56bfa32<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10048-c618e8e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10048-c618e8e.dmg

**Comment by claudioshg** [comment]
testing

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10048-c618e8e.exe

PASS:
- Using the tablet in Desktop Mode, and sharing a SNAP, brings up the feed in the tablet.
- The same happens in HMD Mode.

**Pull request merged**
