### PR TITLE
Avatar animations are now stored locally

### PR DESCRIPTION
**Pull request by hyperlogic**
Improves FTUE, by no longer going over the network to download default avatar animations.
This also includes support for relative animation urls within the animation.json

### CODE REVIEW

**Comment by hyperlogic** [comment]
https://app.asana.com/0/45663370065758/113091805553692

**Comment by hifi-gustavo** [comment]
Build console output for commit: 506033a5d89a93e3e33d965fcb57a5f1632903a6 available at: https://gist.github.com/2325443f36664d44668094755287f648<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7714.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7714.dmg

**Comment by hyperlogic** [comment]
I'm at a loss about why the build failed, I did not touch any of the code that is failing.  Let's roll the dice.

test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 506033a5d89a93e3e33d965fcb57a5f1632903a6 available at: https://gist.github.com/2325443f36664d44668094755287f648<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7714.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7714.dmg

**Comment by OmegaHeron** [comment]
General smoke test Windows 7
AV animations now load from disk - confirmed from log output.
All default animations work - idle, walk, fly, jump, land, hands while audio on.
Other standard tests show no change from RC6

QA Pass

**Pull request merged**
