### PR TITLE
BUGZ-1459 for 0.84: don't rely on final simulation update for kinematic entities

### PR DESCRIPTION
**Pull request by AndrewMeadows**
This PR fixes a bug introduced by PR-16146 when we stopped requiring a simulation owner for kinematic entities. When such entities are deactivated in the physics simulation we can't expect a final authoritative simulation update for them, so we should not use the values stored in `EntityMotionState::_serverPosition()` and friends.

https://highfidelity.atlassian.net/browse/BUGZ-1459

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21315/HighFidelity-Beta-PR16191-e0c09fb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21315/HighFidelity-Beta-Interface-PR16191-e0c09fb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21315/HighFidelity-Beta-PR16191-e0c09fb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21315/HighFidelity-Beta-Interface-PR16191-e0c09fb.exe

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21319/HighFidelity-Beta-PR16191-e0c09fb.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21319/HighFidelity-Quest-Beta-PR16191-e0c09fb.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21319/HighFidelity-Beta-PR16191-e0c09fb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21319/HighFidelity-Beta-Interface-PR16191-e0c09fb.dmg

**Pull request merged**
