### PR TITLE
temporary fix to crash on startup

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ec5ff9ad07f5b98ff798cdaab3f4d3606bb472f available at: https://gist.github.com/10123045937d6cc0c901<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6813.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ec5ff9ad07f5b98ff798cdaab3f4d3606bb472f available at: https://gist.github.com/10123045937d6cc0c901<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6813.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ec5ff9ad07f5b98ff798cdaab3f4d3606bb472f available at: https://gist.github.com/10123045937d6cc0c901<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6813.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6ac9b737d25b94e513e13cdfb7ed8c2075ebe8a3 available at: https://gist.github.com/10123045937d6cc0c901<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6813.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5b9607ca29baa2dedd6cf636bc314dfb85778ca5 available at: https://gist.github.com/10123045937d6cc0c901<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/pr-interface-win64-PR-6813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6813.dmg

**Pull request merged**
