### PR TITLE
Touchpad testing: pinch gesture to zoom camera in or out. (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by danteruiz**
Touchpad testing: pinch gesture to zoom camera in or out. (DO NOT MERGE)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22258/HighFidelity-Beta-PR16433-305b8d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22258/HighFidelity-Beta-Interface-PR16433-305b8d6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22258/HighFidelity-Beta-PR16433-305b8d6.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22258/HighFidelity-Quest-Beta-PR16433-305b8d6.apk)

**Comment by danteruiz** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22271/HighFidelity-Beta-PR16433-305b8d6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22271/HighFidelity-Beta-Interface-PR16433-305b8d6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22271/HighFidelity-Beta-PR16433-305b8d6.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22271/HighFidelity-Beta-Interface-PR16433-305b8d6.exe

**Comment by ZappoMan** [comment]
This is great! This is exactly how we should be implementing this. Nice work Dante.

**Comment by ZappoMan** [comment]
this PR is superceded by PR #16505

**Pull request closed without merging**
