### PR TITLE
Add Entities materialData JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8845/app_12915_PR_f36a5289c9ac6a79880dc0cc10bb84daf3608929.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8845/HighFidelity-Beta-PR12915-f36a5289c9ac6a79880dc0cc10bb84daf3608929.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8845/HighFidelity-Beta-Interface-PR12915-f36a5289c9ac6a79880dc0cc10bb84daf3608929.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8845/HighFidelity-Beta-PR12915-f36a5289c9ac6a79880dc0cc10bb84daf3608929.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8845/HighFidelity-Beta-Interface-PR12915-f36a5289c9ac6a79880dc0cc10bb84daf3608929.exe

**Pull request merged**
