### PR TITLE
request sim-ownership of entire dynamics-linked set at once

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5865/app_12069_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5865/HighFidelity-Beta-PR12069-2b1baab0ca4039694ac1fd9b0b8a55c49c335216.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5865/HighFidelity-Beta-PR12069-2b1baab0ca4039694ac1fd9b0b8a55c49c335216.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5871/app_12069_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5871/HighFidelity-Beta-PR12069-cf6bc4b09b018c59ba9f8f1d02f679b24c74ebf6.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5871/HighFidelity-Beta-PR12069-cf6bc4b09b018c59ba9f8f1d02f679b24c74ebf6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5873/app_12069_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5873/HighFidelity-Beta-PR12069-ea831560165785098d079fd0ce7e84ddd3d0fb05.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5873/HighFidelity-Beta-PR12069-ea831560165785098d079fd0ce7e84ddd3d0fb05.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5874/app_12069_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5874/HighFidelity-Beta-PR12069-3235328a14723110f0eb7553088c271c2ff0300e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5874/HighFidelity-Beta-PR12069-3235328a14723110f0eb7553088c271c2ff0300e.exe

**Comment by AndrewMeadows** [comment]
As I understand it, the problem this PR is attempting to solve is as follows:

UserA grabs a chain of objects with constraints between them.
UserB grabs (or owns the simulation for) the opposite end of the chain.
Disaster ensues (energy is pumped into the system because the constraints are constantly violated).

I would like to try to solve the problem using a system similar to how we currently do "ownership infection" between colliding objects.  Contact points are basically solved as constraints in the Bullet simulation so the two objects constrained to each other are more or less "colliding" with each other every frame.

**Comment by sethalves** [comment]
closing this -- andrew is thinking about possible solutions.

**Pull request closed without merging**
