### PR TITLE
Merge stable back into master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by conklin94122** [comment]
No testing needed, adding QA Approved for process.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7044/app_12371_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7047/app_12371_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7047/HighFidelity-Beta-PR12371-632390e6b075a0c002aa7a8a7271abf84c08244c.dmg

**Comment by Atlante45** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7069/app_12371_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7069/HighFidelity-Beta-PR12371-632390e6b075a0c002aa7a8a7271abf84c08244c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7069/HighFidelity-Beta-PR12371-632390e6b075a0c002aa7a8a7271abf84c08244c.exe

**Pull request merged**
