### PR TITLE
Fix domain id getting set to empty when adding place name

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4664/HighFidelity-Beta-PR11740-b1fe3699f99cd239b7f14aa598fe10086d1372fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4664/HighFidelity-Beta-PR11740-b1fe3699f99cd239b7f14aa598fe10086d1372fa.exe

**Comment by Nex-Pro** [comment]
testing

**Comment by huffman** [comment]
Test rail tests:

https://highfidelity.testrail.net/index.php?/cases/view/2177
https://highfidelity.testrail.net/index.php?/cases/view/2178
https://highfidelity.testrail.net/index.php?/cases/view/2179

**Comment by Nex-Pro** [comment]
### PASS  see testrail results.

**Comment by conklin94122** [comment]
https://highfidelity.fogbugz.com/f/cases/8899/

**Pull request merged**
