### PR TITLE
tablet webview navigation bar redesigned

### PR DESCRIPTION
**Pull request by druiz17**
Reworked the tablet web view navigation to the design doc that alan gave me.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- Click on the information of card in goto.
- Once the web browser click on a link and a new page should open.
- press the back button and it should bring you back to the previous page
- pressing the close button should bring you back to the goto page.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 31b61c3225ed4609fc4abfdc385b68df046ce902 available at: https://gist.github.com/d8fabf764d047d4a49d516d958cd96cd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10234-31b61c3.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10234-31b61c3.dmg

**Comment by sharsein** [comment]
Testing

**Comment by sharsein** [comment]
QA Failed. 

Desktop PC - Windows 10 Home - CPU 3.5GHz Intel i5-6600K - GTX1060 - RAM 16GB - Tested with HTC Vive
Tested Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10234-31b61c3.exe

In both Desktop and HMD mode:
-On info page the Back button is not visually disabled, but clicking it does nothing. Close works.
- Wording of this step" Once the web browser click on a link and a new page should open" is a little confusing. Nothing happened when I tried to click on the full address link on the info page, for example https://metaverse.highfidelity.com/place/dev-welcome/
- Clicked on the blue button ex "Visit Dev-Welcome". I am taken to the world, but get a "This webpage is not available. ERR_UNKNOWN_URL_SCHEME" message. The Back button will successfully take me back to the info page, and the Close button will still successfully bring me back to the Go To page

**Comment by druiz17** [comment]
@sharsein 
- The back button is disbaled but the difference is hard to see
- Sorry about the miss wording of the second task. I was asking to click on links and confirm, that you can goto to that page. Also the url below the back and close button is not clickabe, it is just there to let you know what page you are on.
- The chrome web browser wont be able to visually display  https://metaverse.highfidelity.com/place/dev-welcome/ , so what we care about is that it took you to the location.
- You being able to go back to the information page and goto page is the behavior I was expecting to hear.

**Pull request merged**
