### PR TITLE
[RC77] MS20114 [CreateApp] ignore createApp shortcut keys while TEXTAREA elements are in focus

### PR DESCRIPTION
**Pull request by thoys**
This PR addresses https://highfidelity.manuscript.com/f/cases/20114/Pressing-Delete-or-F-while-editing-user-data-triggers-create-shortcuts

Original RC76 PR to be found here https://github.com/highfidelity/hifi/pull/14520

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15589/HighFidelity-Beta-PR14522-f38f39c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15589/HighFidelity-Beta-PR14522-f38f39c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15589/HighFidelity-Beta-Interface-PR14522-f38f39c.dmg

**Comment by QliCknox** [comment]
Currently Testing

**Comment by QliCknox** [comment]
Pass

Shortcuts no longer trigger in UserData

**Pull request merged**
