### PR TITLE
Revert can cast shadow work

### PR DESCRIPTION
**Pull request by SamGondelman**
Reverts https://github.com/highfidelity/hifi/pull/12407 because it wasn't supposed to make it into the RC

Test plan:
1. Load the Paradise Island environment from the market
2. Verify there are no shadows
2. Select Menu->Settings->Developer->Menus
3. Select Developr->Graphics..
4. Verify both "Ambient occlusion" and "Shadows" combos show None.
5. Set "Shadows" to Enabled
6. Click "SAVE CHANGES" and verify that all objects in the scene have shadows.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7570/app_12513_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7570/HighFidelity-Beta-PR12513-0fca56eef06609e9624ab9571ebcf1d9deef4a5e.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7570/HighFidelity-Beta-PR12513-0fca56eef06609e9624ab9571ebcf1d9deef4a5e.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - Default for graphics settings are: None. Enabling Shadows works as expected. @conklin94122

**Pull request merged**
