### PR TITLE
Input recorder/ input playback system  for all input actions

### PR DESCRIPTION
**Pull request by druiz17**
Added system that records Input actions and playback recorded actions. The system has the ability to save/load recorded session to a compressed json file and load from a compressed json file

### CODE REVIEW

**Comment by druiz17** [comment]
To use the input recording you must run the inputRecorder.js file location in scripts/developer/debugging

**Comment by hifi-gustavo** [comment]
Build console output for commit: 249862141a16342b485b2fd44355b300389c3bff available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-2498621.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-2498621.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b023356fb78ad6a6aca7ed50f6cdbefb518597a8 available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-b023356.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-b023356.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8705db07e542bb7f63d491b52d8e6c479f0ee64f available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-8705db0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-8705db0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2a997f2a4d4ba5e1bcff7a8c257fe93b83cb5572 available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-2a997f2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-2a997f2.dmg

**Comment by hyperlogic** [comment]
Overall this is pretty cool and will be very useful for testing.  Here is some UI/UX feedback:
* The description text on the tablet is cut off.  It wasn't obvious to me what Alt-B did, because the first part of the sentence is not visible.
* When you start a recording and re-open the tablet, and press the IRecord button, the first button in the upper right says, play recording.  It should say stop recording.
* It should not take two steps to browse then load the recording.
* The file browser should start in the same directory that the recordings are saved in.
* We should probably save the recordings in a different place, I think only admin accounts can write directly to the user folder.  Instead write to the same location that our logs are saved.  User/AppData/Local/High Fidelity/Interface

**Comment by anshuman64** [comment]
Very cool! Works well too. Agree with Tony's recommendations, and one more thing I would add:

- After clicking "Stop Recording," the recording URL should update to "<Unsaved Recording>" as a reminder that an unsaved recording is currently on deck.

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d8e6e8e7d06db17565773078b69227f1f35e571a available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-d8e6e8e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-d8e6e8e.dmg

**Comment by druiz17** [comment]
Test Plan
- test in HMD mode with hand controllers
- Load inputRecorder.js under the developer folder.
- On the tablet home screen click on the IRecord button... this should bring you to the input recorder UI screen
- click on start recording (the button should now say "stop recording") then perform some movements with your arms.
- Once you are ready to stop recording, click the stop recording button( it should now say "start recording")
- Now click on the play recording button and see your hands perform the actions you recorded
- To stop a recording press Alt-B
- now press the save recording button to save the recording.
- confirm that the file is saved...press the load button and you should be brought to the location of the saved file.
- record another performance and save the recording.
- load your previous recording file and press the play recording button (wait for a second to ensure the file finished loading)...you should see your avatar perform the actions from your previous recording session

**Comment by Nex-Pro** [comment]
Testing this

**Comment by Nex-Pro** [comment]
Tested this on win10 and Vive

### PASS

Test plan works fine.****

#### Feedback:

This is fun and I can see it being useful.

Clearly the use of Alt+B is a big issue here.  Even spacebar would have been better but we don't want to use the keyboard in HMD at all.   Some sort of hand controller method to stop the playback needs to be implemented.

Would be nice to have some kind of trimming facility as the recording is pretty much going to start and end with the hand movements of the tablet interaction.

Good work! @druiz17

**Comment by anshuman64** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4df953d5100891f215e8ec578153533644d07a5b available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-4df953d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-4df953d.dmg

**Comment by anshuman64** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95d6a451c69f666ffacfebbc6938fed60808cb63 available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-95d6a45.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-95d6a45.dmg

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95d6a451c69f666ffacfebbc6938fed60808cb63 available at: https://gist.github.com/9087df0a852b22150cff02761981e201<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-95d6a45.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10268-95d6a45.dmg

**Comment by anshuman64** [comment]
Yea sorry, two green labels tricked me. Thanks for reviewing anyway @seth

**Pull request merged**
