### PR TITLE
Restoring Emote app to stable build state, adding sit and love emotes

### PR DESCRIPTION
**Pull request by alexiamandeville**
These changes add Sit and Love emotes to the app, without any other changes to functionality within the Emote app. It restores the app to a state where it is in stable, with the two animations added.

When input is provided when sitting, the avatar's animation state gets restored. In any other emote, the avatar will slide while animating.

### CODE REVIEW

**Comment by alexiamandeville** [comment]
Test Plan in Desktop:

1. Open Emote app
2. Test each animation other than sit. When providing input (WASD), the animation should continue until the end of the frames, and restore the idle/walk animation.
3. Test the "sit" animation by clicking the "Sit" button. 
4. Provide input (WASD) while the avatar is sitting. This should cause the avatar to get up and start walking. Otherwise, no input will allow the avatar to sit there indefinitely.

Test Plan in VR:

1. Enter HMD
2. Open Emote app
3. Test each animation other than sit. When providing input (joystick, buttons on VR controller), the animation should continue until the end of the frames, and restore the idle/walk animation.
4. Test the "sit" animation by clicking the "Sit" button. 
5. Provide input (joystick, buttons on VR controller) while the avatar is sitting. This should cause the avatar to get up and start walking. Otherwise, no input will allow the avatar to sit there indefinitely.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10915/HighFidelity-Beta-PR13475-4c78d26.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10915/HighFidelity-Beta-PR13475-4c78d26.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10915/HighFidelity-Beta-Interface-PR13475-4c78d26.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Fail @conklin94122 
 Emote app fails to load. Does not occur on Stable and Master. Error in log shows:

[06/27 09:17:58] [CRITICAL] [hifi.scriptengine] [emote.js] [UncaughtException evaluate(lint)] Error:  in file:///C:/Program Files/High Fidelity - PR13475/scripts/system/emote.js:8

[hifi-log.txt](https://github.com/highfidelity/hifi/files/2141887/hifi-log.txt)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10938/HighFidelity-Beta-PR13475-49269d1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10938/HighFidelity-Beta-PR13475-49269d1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10938/HighFidelity-Beta-Interface-PR13475-49269d1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10938/HighFidelity-Beta-PR13475-49269d1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10938/HighFidelity-Beta-Interface-PR13475-49269d1.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
Fail @conklin94122 

Pass - Emotes fully play out when stationary in both HMD and Desktop
Pass - Desktop permits action emotes to slide with user motion.
Pass - Desktop Sit emote is interrupted by motion.
Pass - HMD Sit emote is interrupted by motion.
Fail - HMD action emotes are all cancelled by controller motion. (NO in Stable8483, YES in Master 8502)

Note: Following occurs in Stable and Master for both Oculus and Vive
semiFail - (occurs in both Stable and Master) HMD Keyboard motions while using emote will lock that movement as active. Character will continue moving in keyboard direction even through Away mode.

-However, there is an extra problem, as the condition is more severe in this PR for the Vive.  In Master and Stable you can cancel the trapped motion by tapping the same directional button after closing the Tablet fully (x button). But in this PR the Vive cannot cancel the action as easily. (extra problem does not affect Oculus)


[hifi-log.txt](https://github.com/highfidelity/hifi/files/2142951/hifi-log.txt)

**Comment by alexiamandeville** [comment]
I will check with @qlimguicheteau tomorrow about the notes/semifails for clarification.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10963/HighFidelity-Beta-PR13475-db1dfe1.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10963/HighFidelity-Beta-PR13475-db1dfe1.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10963/HighFidelity-Beta-Interface-PR13475-db1dfe1.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10963/HighFidelity-Beta-PR13475-db1dfe1.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10963/HighFidelity-Beta-Interface-PR13475-db1dfe1.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Previously failed steps now pass all other steps pass.

**Pull request merged**
