### PR TITLE
Possible polyline crash fix

### PR DESCRIPTION
**Pull request by jherico**
The current code uses a `QReadWriteLock` to protect access to the Polyline points, normals and widths...  however, this lock isn't used around the code that reads these members and uses them to update the vertex buffer.  If there's a race condition and one of the points, normals or widths are being modified while the renderable geometry is being updated then pretty much anything could happen.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 909a9189a2122ee2fe1827f2115e53a33f2285c2 available at: https://gist.github.com/88e682871cfe633d87a5080f1be83341<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-909a918.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-909a918.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bade2ef9aabb89dc4f9e63d420afabfb6c1e057 available at: https://gist.github.com/88e682871cfe633d87a5080f1be83341<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-5bade2e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-5bade2e.dmg

**Comment by ZappoMan** [comment]
@jherico - @PhilipRosedale tested this and he reports that "it doesn't crash... but it also doesn't render the whiteboard polylines."

**Comment by jherico** [comment]
@ZappoMan let's call it a 'qualified success'

**Comment by hifi-gustavo** [comment]
Build console output for commit: 12ccbdac0b2ac601225c2dd793a77bd6e362ec23 available at: https://gist.github.com/88e682871cfe633d87a5080f1be83341<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-12ccbda.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9140-12ccbda.dmg

**Comment by samcake** [comment]
Tested for real on philip's machine and no issues anymore

It s a pass,
bravo Austin

**Pull request merged**
