### PR TITLE
Fix login fail twice call

### PR DESCRIPTION
**Pull request by wayne-chen**
- fixing loginFailed signal to be only emitted once when a login actually fails

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12957/HighFidelity-Beta-PR13989-96ab7d4.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12961/HighFidelity-Beta-PR13989-8738594.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12961/HighFidelity-Beta-PR13989-8738594.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12961/HighFidelity-Beta-Interface-PR13989-8738594.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12961/HighFidelity-Beta-PR13989-8738594.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12961/HighFidelity-Beta-Interface-PR13989-8738594.exe

**Comment by birarda** [comment]
@wayne-chen we should still QA this even if it means they can look in the log and confirm there are not the two messages (but that there is at least one).

**Comment by wayne-chen** [comment]
Updated with a test plan.

**Comment by qliejahner** [comment]
Currently testing

**Comment by JeffClinton** [comment]
PASS @Conklin94122

I retested this again per dev request, and it appears to be working as expected.  I was just getting the one loginFailed signal.  Tested on clean installs in stable and staging metas.

**Comment by JeffClinton** [comment]
Note: Additional testing was able to reproduce the initial fail.  Approved tag removed, and revert process started.

**Pull request merged**
