### PR TITLE
[experiment/feedback] Include script name with all JS/QML debug output

### PR DESCRIPTION
**Pull request by humbletim**
Here's a patch that updates `print()` and `console.*()` to include the script name (specifically as part of the main application logs) -- making it easier track down where messages come from and perform despam passes.  It works transparently with existing `.qml` and `.js` scripts.

Before example (ie: where do these messages come from?):
```
[09/29 08:24:07] [DEBUG] [qml] Connecting JS messaging to Hifi Logging
[09/29 08:24:07] [WARNING] [qml] Controller not yet available... can't reposition targetWindow
[09/29 08:24:27] [DEBUG] [qml] Load default scripts
[09/29 08:25:06] [DEBUG] [qml] user stories update announcement ok 0 filtered to 0
[09/29 08:25:09] [DEBUG] [hifi.scriptengine.script] No avatar identity data for null
[09/29 08:25:09] [DEBUG] [qml] This user's data was not found in the user list. PAL will not function properly.
[09/29 08:26:12] [DEBUG] [qml] Web Entity JS message: https://connect.facebook.net/en_US/fbevents.js 24 Facebook Pixel Error
[09/29 08:27:41] [DEBUG] [hifi.scriptengine.script] Refreshing Connections...
```

After example (as it turns out, from 7+ source files!):
```
[09/29 08:40:02] [DEBUG] [qml] [BaseWebView.qml] Connecting JS messaging to Hifi Logging
[09/29 08:40:02] [WARNING] [qml] [Desktop.qml] Controller not yet available... can't reposition targetWindow
[09/29 08:40:10] [DEBUG] [qml] [RunningScripts.qml] Load default scripts
[09/29 08:40:22] [DEBUG] [qml] [Feed.qml] user stories update announcement ok 0 filtered to 0
[09/29 08:40:38] [DEBUG] [hifi.scriptengine.script] [defaultScripts.js] No avatar identity data for null
[09/29 08:40:38] [DEBUG] [qml] [Pal.qml] This user's data was not found in the user list. PAL will not function properly.
[09/29 08:41:45] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: https://connect.facebook.net/en_US/fbevents.js 24 Facebook Pixel Error
[09/29 08:42:00] [DEBUG] [hifi.scriptengine.script] [defaultScripts.js] Refreshing Connections...
```
... not entirely sure about wrapping the script name in square brackets, but overall idea?

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3766/HighFidelity-Beta-PR11494-fd917917c40004ecfc8125981502bccaad969180.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3766/HighFidelity-Beta-PR11494-fd917917c40004ecfc8125981502bccaad969180.exe

**Comment by themelissabrown** [comment]
@humbletim what's a good test plan for this?

**Comment by ZappoMan** [comment]
@humbletim - I love it! Approved.

*TEST PLAN*
- Run the build, make sure that the log files include script and qml file names for all the log output.

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
[10/05 18:22:45] [WARNING] [hifi.scriptengine] [defaultScripts.js] Script.timerFired() while shutting down is ignored... parent script:defaultScripts.js | Pass

Looks all good to me - the formatting is perfect in my opinion.

**Pull request merged**
