### PR TITLE
MS14878: Prevent wallet passphrase leak in specific case

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [MS14878](https://highfidelity.manuscript.com/f/cases/14878/After-entering-passphrase-in-VR-desktop-preview-reveals-passphrase-for-one-frame).

In VR mode, when entering the wallet's passphrase, the preview is disabled for privacy. However, without this PR, when submitting it, the preview is re-enabled too early. The completed passphrase screen was thus shown for one frame.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prereqs
- A HiFi account with or without a wallet set up

### Tests
#### Account without a wallet:

1) Enter interface in HMD
2) Enable desktop preview
3) Log into an account without a wallet
4) Begin recording the screen
5) Set up the wallet. Upon reaching step 3, the desktop preview is hidden with a lock icon
6) Enter a valid passphrase in both fields, and click "Show passphrase"
7) Click Next
8) Save the recording and review it. Seek to where the preview is enabled.
9) Verify that the wallet setup's step 3, including the complete passphrase, is NOT visible for one frame

#### Account with a wallet:

1) Enter interface in HMD
2) Enable desktop preview
3) Log into an account
4) Begin recording the screen
5) Click Wallet. Desktop preview is hidden with a lock icon
6) Enter your passphrase, and click "Show passphrase"
7) Click Next
8) Save the recording and review it. Seek to where the preview is enabled
9) Verify that the passphrase is NOT visible for one frame

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9572/app_13119_PR_646c0ec987eb285e641ef1ca9a75bfc45f888136.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9572/HighFidelity-Beta-PR13119-646c0ec987eb285e641ef1ca9a75bfc45f888136.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9572/HighFidelity-Beta-Interface-PR13119-646c0ec987eb285e641ef1ca9a75bfc45f888136.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9572/HighFidelity-Beta-PR13119-646c0ec987eb285e641ef1ca9a75bfc45f888136.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9572/HighFidelity-Beta-Interface-PR13119-646c0ec987eb285e641ef1ca9a75bfc45f888136.exe

**Comment by qlimnavarro** [comment]
@zfox23 Will retest.

**Comment by zfox23** [comment]
@qlimnavarro, this doesn't make any sense. I just tried your repro steps on a local build and can't get them to work. I'm installing the Gustavo build now.

**Comment by zfox23** [comment]
Yes, this seems like a strange Gustavo bug??? This is a problem in the Gustavo build but not a problem in mine. Will rebuild...

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9583/app_13119_PR_c5ebc436ce689825192debeff3f222e011eaf725.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9583/HighFidelity-Beta-PR13119-c5ebc436ce689825192debeff3f222e011eaf725.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9583/HighFidelity-Beta-Interface-PR13119-c5ebc436ce689825192debeff3f222e011eaf725.exe

**Comment by zfox23** [comment]
@qlimnavarro: This was a Gustavo bug the whole time. I just needed to rebuild the PR. Please re-test.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Comment by zfox23** [comment]
Thanks.

**Pull request merged**
