### PR TITLE
RC 75: Fix shape not getting marked changed

### PR DESCRIPTION
**Pull request by SamGondelman**
See https://github.com/highfidelity/hifi/pull/14295

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14470/HighFidelity-Beta-PR14296-a5f0ea3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14470/HighFidelity-Beta-PR14296-a5f0ea3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14470/HighFidelity-Beta-Interface-PR14296-a5f0ea3.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Imported shapes render in the correct shape type noted in the json.

**Pull request merged**
