### PR TITLE
Disable gridTool in edit.js

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: dad36b73fc3edaea1ea271403be8b44583dbdc63 available at: https://gist.github.com/f2e51a38bb91b8542eda<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7014.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7014.dmg

**Comment by huffman** [comment]
To test:

- Load script: https://rawgit.com/huffman/hifi/disable-edit-grid/examples/edit.js
- Turn edit on
- Confirm that there is no longer a "Grid" tab in tool window

**Comment by hifi-gustavo** [comment]
Build console output for commit: 57d92bcfa6faaa11beafdae07ff914a6b53014b1 available at: https://gist.github.com/f2e51a38bb91b8542eda<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7014.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7014.dmg

**Comment by nbq** [comment]
Testing this one

**Comment by nbq** [comment]
I stop the running edit.js and load the one from the instructions above. I get this in the log, along with some other blocks:
[02/02 14:09:52] [DEBUG] Web Window JS message: https://rawgit.com/huffman/hifi/disable-edit-grid/examples/html/entityProperties.html 0 [blocked] The page at 'https://rawgit.com/huffman/hifi/disable-edit-grid/examples/html/entityProperties.html' was loaded over HTTPS, but ran insecure content from 'ws://localhost:51016/': this content should also be loaded over HTTPS.

In world, I can create an object but when I try to edit it, the tools window shows nothing nearby under Entities and when you click on the object you created, Entity Properties does not load any information about it. This fails for me.

**Comment by nbq** [comment]
PASSED - Tested with http instead of https and it worked fine, there is no longer a Grid tab in the Tools dialog.

**Pull request merged**
