### PR TITLE
Beta Release 23 - Includes up to Developer Release 5505

### PR DESCRIPTION
**Pull request by cozza13**
http://rawgit.com/cozza13/QAtesting/master/QAofRC.js

RC smoke test

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 72d3a594b2cab447d4652fdc0d021daa8aa4ccad available at: https://gist.github.com/f294ff3ba7343aa6b645b0ebdb43c0bc<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8820-72d3a59.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8820-72d3a59.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** FAILURE
**Additional Test Results + Observations**: Crash when doing TP while utilizing the ```playa-performance``` test.  Sent bugsplat.  The crash occurred after running the test and stopping then TP to another domain.

**Comment by judasshuffle** [comment]
Testing this pr
If I search for my shop domain coffeeshop appears before it despite being empty and alphabetically later
https://i.gyazo.com/ed837359255dfd197cd5c559bfc066db.gif. 
It crashed visiting a down domain-  I sent a report.
I got decent performance with my rift on it, seems to be more comfortable than the previous rc.
Also the texture blurring I was getting on the last build seems to have stopped with default settings.
I have 6 sound emitters on my domain I can only hear 4 of them in this build but all 6 in the previous version?

Do I really need a onscreen keyboard on the location bar when I'm not wearing a hmd?
Skybox reflections seem to be working again yay

**Comment by Nex-Pro** [comment]
testing

**Comment by ctrlaltdavid** [comment]
@judasshuffle There's a PR to make on-screen keyboards only display if in HMD. Didn't quite make it into this RC, though.

**Comment by nbq** [comment]
testing this now

**Comment by nbq** [comment]
PASS For Me

## QA Test
**QA Tester**: Coal
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Everything worked as usual

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |59 |58 |60
**CPU Buffer Count**: |2240 |3776 |3179
**GPU Buffer Count**: |758 |898 |893
**CPU Memory Usage**: |35483648 |75444224 |56664064
**GPU Memory Usage**: |21913600 |30461952 |35028992
**CPU Texture Count**: |210 |273 |308
**GPU Texture Count**: |163 |157 |220
**GPU Transfer Count**: |0 |7 |0
**CPU Texture Memory Usage**: |109641864 |1253266024 |293811752
**GPU Texture Memory Usage**: |443219968 |423952384 |692060160
**GPU Virtual Memory Usage**: |626343616|1186285287|899614636
**Triangle Count**: |264107 |850921 |569913
**Triangle Rate**: |16506687 |53182562 |35619562
**API Drawcall Count**: |155 |308 |240
**Drawcall Count**: |2967 |351 |240
**Drawcall Rate**: |185437 |21937 |15000
**State Changes Texture Count**:|293 |315 |331
**Pipeline Count**: |68 |44 |56
**Item Opaques**: |216 |822 |255
**Item Translucents**: |86 |48 |44
**Item Lights**: |16 |81 |15
**Timing Opaques**: |0.619 |1.376 |0.659
**Timing Translucents**: |0.102 |0.07 |0.102
**Timing Lighting**: |0.082 |0.112 |0.092
**Render Frame**: |1.47 |2.818 |1.508

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Ok
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Ok
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Ok
**Test 4**|Launch firework, on dev-playa, can other hear?|Ok
**Test 5**|Switch avatar and make sure it does not crash|Ok
**Test 6**|Test group functions|Ok
**Test 7**|Retest the kick function|Ok
**Test 8**|Enrure that you can distance grab|NA
**Test 9**|Being up and edit an objects with hand controllers|NA
**Test 10**|Modify a models userdata and make sure it works|OK
**Test 11**|Grab objects in dev-demo|NA

**Comment by Nex-Pro** [comment]
### PR #8820

**Testing Architecture:** Desktop PC
**CPU:** 4.4 ghz Intel i7
**RAM:** 16 GB
**GPU:** Nvidia gtx 1070 8gb

**Testing OS:** win 10 pro

**HMD:** HTC Vive.
**Hand Controllers:** Vive

Important please read notes.

## QA Test
**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: SUCCESS
**QA Pass**: SUCCESS

**Additional Test Results + Observations**:
lighting issues with head angle relative to light sources see screen grabs


**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |90 |90 |90
**Present Rate**: |90 |90 |90
**Present New Rate**: |90 |89 |89
**CPU Buffer Count**: |1499 |4239 |4046
**GPU Buffer Count**: |16723 |7637 |13973
**CPU Memory Usage**: |25174016 |70348800 |58343424
**GPU Memory Usage**: |84967424 |69242880 |84729856
**CPU Texture Count**: |128 |284 |293
**GPU Texture Count**: |121 |219 |259
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |26493976 |277008144 |200188952
**GPU Texture Memory Usage**: |388136960 |1259864064 |844120064
**GPU Virtual Memory Usage**: |913205013|2131508771|1378268105
**Triangle Count**: |249669 |2808371 |1453992
**Triangle Rate**: |22697181 |255306454 |132181090
**API Drawcall Count**: |27 |392 |307
**Drawcall Count**: |31 |847 |2405
**Drawcall Rate**: |2818 |77000 |218636
**State Changes Texture Count**:|45 |382 |436
**Pipeline Count**: |38 |49 |64
**Item Opaques**: |4 |915 |301
**Item Translucents**: |2 |53 |44
**Item Lights**: |0 |87 |13
**Timing Opaques**: |0.129 |2.163 |1.434
**Timing Translucents**: |0.038 |0.145 |0.114
**Timing Lighting**: |0.23 |0.189 |0.182
**Render Frame**: |1.641 |4.127 |2.061


**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Check
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|**SUCCESS** used the new home content tutorial.
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|**SUCCESS**
**Test 4**|Launch firework, on dev-playa, can other hear?|**SUCCESS**
**Test 5**|Switch avatar and make sure it does not crash|**SUCCESS**
**Test 6**|Test group functions|untested
**Test 7**|Retest the kick function|untested
**Test 8**|Enrure that you can distance grab|enrued! **SUCCESS**
**Test 9**|Being up and edit an objects with hand controllers|works but is basically hopeless.
**Test 10**|Modify a models userdata and make sure it works|**SUCCESS**
**Test 11**|Grab objects in dev-demo|**SUCCESS**

Notes:

Frame rate issues.
Observed poor frame rates in areas with multiple lights. Spot and point.
This got worse the longer interface was running.
See screenshots of welcome showing 15fps and present rate near 200 in desktop mode during a long run of more than an hour and a half in HMD.
This made it necessary to restart.

Locations visited in testing this PR:
Welcome.
good-times.
mini-golf(multiple areas) Many local teleports.
mexico.

Small object culling:

Culling of small objects is over-enthusiastic and inconsistent. Surely we should be Lodding not culling.
See screenshots. I compared this to 5407 which was far more consistent and did not show near culling of entities. 

The frame rate recovered on restart.( Clement thinks this may be a memory leak.)
Frame rate drop off occurred on subsequent long runs. More restarts needed.

Two crash reports were submitted in close succession but when interface sucessfully restarted several of the other users present stated that they had also crashed at the same time. The location was out the front of the good-times apartment.

Edit js.
When edit.js is in particle explorer tab i``t is not dismissed via the edit icon.(not related to this PR).

Exporting entities:
While using the export entities dialog no mouse pointer is visible. The task can be achieved but is difficult and unreliable. ( not due to this PR)

Particle issues:
Large backround particles at home location move relative to scene with head movement looks odd( not sure how you can fix that ). As viewer's head is rotated the large particles are seen to maintain Vertical Y orientation to the HMD but Y position changes relative to rest of scene as head is rolled side to side in Z axis. I gives the effect that the particles are not part of the scene but attached to the HMD. Time for volumetric effects ?
It is still possible to light the fuse a second time in the vive tutorial.

**Lights being culled with small head movements see lit/unlit rock. Images taken moments apart in this rc.**

light culling
lightculling2

**Incorrect small object culling. Image with more oranges is 5407**
rc23

**Comment by OmegaHeron** [comment]
Windows 10 i5 6500 CPU - GTX970 GPU

CPU use comparison to last RC (Build 5429).  This PR Red, Last RC Blue

5429v8820r5

This PR compares with near equality to last.  Given enough runs (more than 5 used for this sample set) this PR will sometimes run at lower CPU use as blue traces for last RC shows.  Why this happens is still a mystery, but not material to current context.

Additional testing to come for standard tests.

**Comment by OmegaHeron** [comment]
Sanity check for system memory use.  Windows 10 - i5 6500 CPU - GTX970 GPU

Following graph shows system memory available - Interface ran and visited my 2 test domains, dev-demo and dev-playa twice each letting scene fully load.  Was looking for any memory leakage over short term.  None seen.

8820memuse

**Comment by OmegaHeron** [comment]
Windows 10 - i5 6500 CPU - GTX970 GPU

## QA Test
**QA Tester**: OmegaHeron
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'harmonicOscillator.js' Result**: **localhost 'harmonicOscillator.js'** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: 

**RC Specific tests**

**Test** | **Description** | **Results**
---|---|---
**Test 1**|For performance testing use. Localhost - dev-playa - dev-demo|Yes
**Test 2**|Install a fresh copy of "Home' and ensure that the content works|Yes
**Test 3**|Go to localhost - Make sure you can hear the background sounds.|Yes
**Test 4**|Launch firework, on dev-playa, can other hear?|Not tested
**Test 5**|Switch avatar and make sure it does not crash|Ok
**Test 6**|Test group functions|Ok
**Test 7**|Retest the kick function|Ok
**Test 8**|Enrure that you can distance grab|Not tested
**Test 9**|Being up and edit an objects with hand controllers|N/A
**Test 10**|Modify a models userdata and make sure it works|Not tested
**Test 11**|Grab objects in dev-demo|Ok

Desktop mode 1600x900 maximized window (vsync enabled)

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |60 |60 |60
**CPU Buffer Count**: |2489 |3908 |4293
**GPU Buffer Count**: |845 |1338 |1184
**CPU Memory Usage**: |32927744 |63684608 |72753152
**GPU Memory Usage**: |21725184 |43778048 |39698432
**CPU Texture Count**: |205 |292 |360
**GPU Texture Count**: |177 |254 |325
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |70420568 |157304920 |90424400
**GPU Texture Memory Usage**: |0 |0 |0
**GPU Virtual Memory Usage**: |632618623|1901925886|1343565851
**Triangle Count**: |227035 |580078 |311338
**Triangle Rate**: |13355000 |36254875 |19458625
**API Drawcall Count**: |176 |168 |169
**Drawcall Count**: |1856 |168 |1068
**Drawcall Rate**: |109176 |10500 |66750
**State Changes Texture Count**:|310 |212 |258
**Pipeline Count**: |59 |53 |43
**Item Opaques**: |227 |588 |177
**Item Translucents**: |99 |27 |33
**Item Lights**: |16 |31 |7
**Timing Opaques**: |1.022 |0.653 |0.635
**Timing Translucents**: |0.196 |0.068 |0.134
**Timing Lighting**: |0.161 |0.168 |0.149
**Render Frame**: |2.428 |2 |1.781

DK2 HMD

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |75 |75 |75
**Present Rate**: |75 |75 |75
**Present New Rate**: |74 |75 |74
**CPU Buffer Count**: |2600 |4116 |4577
**GPU Buffer Count**: |1050 |1564 |1538
**CPU Memory Usage**: |32665600 |65253376 |71004160
**GPU Memory Usage**: |22437888 |46108672 |41955328
**CPU Texture Count**: |191 |293 |303
**GPU Texture Count**: |165 |261 |294
**GPU Transfer Count**: |0 |0 |0
**CPU Texture Memory Usage**: |62453016 |90832656 |61285400
**GPU Texture Memory Usage**: |0 |0 |0
**GPU Virtual Memory Usage**: |788952131|2232536575|1442252302
**Triangle Count**: |458656 |1762069 |846040
**Triangle Rate**: |35281230 |146839083 |70503333
**API Drawcall Count**: |174 |286 |244
**Drawcall Count**: |4386 |555 |2294
**Drawcall Rate**: |337384 |46250 |191166
**State Changes Texture Count**:|309 |331 |349
**Pipeline Count**: |51 |28 |63
**Item Opaques**: |229 |509 |267
**Item Translucents**: |86 |51 |43
**Item Lights**: |15 |83 |13
**Timing Opaques**: |0.859 |1.656 |0.779
**Timing Translucents**: |0.207 |0.077 |0.141
**Timing Lighting**: |0.078 |0.105 |0.096
**Render Frame**: |1.916 |3.11 |1.995

Unlocked vsync FPS rates in desktop mode show no notable change in maximum attainable FPS vs previous RC.

Select text in a QML window like ones that generate stat reports above -- right click selected test and not you get an unusable and irremovable popup menu for option to copy text.  Only way to dismiss popup is to close QML window.  Not a fail - but should eventually be addressed.

**Comment by OmegaHeron** [comment]
I would like to refresh my generalized sense of displeasure with how switches between desktop mode and HMD corrupt placement of on screen elements like HUD, edit windows, asset browser and anything else you may have given a placement you like in Desktop mode only to find them wherever they may be after a Desktop->HMD->Desktop cycle.  As a QA tester it's not a fail as it's simply the way it works.  As a consumer of Interface as a product - it makes me want to write angry letters of complaint.

**Pull request closed without merging**
