### PR TITLE
Build 39.3 Hotfix for T-Pose avatars

### PR DESCRIPTION
**Pull request by cozza13**
Build 39.3 Hotfix for T-Pose avatars

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: df5928c04a9f5c08eb3401a08377169e4c227eb9 available at: https://gist.github.com/cc21f93acfa767c5943d26aba5cb30c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10498-df5928c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10498-df5928c.dmg

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
the state set was incorrect. rebuilding to ensure proper status is posted.

**Comment by hifi-gustavo** [comment]
Build console output for commit: df5928c04a9f5c08eb3401a08377169e4c227eb9 available at: https://gist.github.com/cc21f93acfa767c5943d26aba5cb30c4<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10498-df5928c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10498-df5928c.dmg

**Pull request merged**
