### PR TITLE
Hooked up seated version of aim offset animation

### PR DESCRIPTION
**Pull request by hyperlogic**
https://highfidelity.atlassian.net/browse/DEV-2313

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22264/HighFidelity-Beta-PR16435-4b34311.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22264/HighFidelity-Quest-Beta-PR16435-4b34311.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22264/HighFidelity-Beta-PR16435-4b34311.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/22264/HighFidelity-Beta-Interface-PR16435-4b34311.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22264/HighFidelity-Beta-PR16435-4b34311.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/22264/HighFidelity-Beta-Interface-PR16435-4b34311.exe

**Comment by DouglasWilcox** [comment]
TEST NOTES:
This should not happen at the same time as the stand version, or at the same time as a point aimoffset.  The best way to verify this is to turn on Anim stats to screen and record yourself going in/out of seated.

the standing aimoffset shows as "lookBlendAlpha" in debug stats
seated aimoffset is "seatedLookBlendAlpha".

These should not play at 1.0 influence at the same time.  

Visually, you should see yourself sitting with your hands in your lap and they stay in place as you look around.  They would noticably wander using the stand version of the aimoffset.

**Pull request merged**
