### PR TITLE
Fix avatars transit on domain enter

### PR DESCRIPTION
**Pull request by luiscuenca**
Fix for this PR:
https://github.com/highfidelity/hifi/pull/14079
This PR avoid triggering the avatar transit effect on other avatars that are located at a distance less than 30 meters from the domain origin, when entering a new domain

### CODE REVIEW

**Comment by luiscuenca** [comment]
## TEST PLAN
- Go to engine-dev (make sure it has bots). All the avatars (or its sphere) should be rendered on their final destination (no transit).
- Go through the test plan on this PR: https://github.com/highfidelity/hifi/pull/14079

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13625/HighFidelity-Beta-PR14141-bb98457.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13625/HighFidelity-Beta-PR14141-bb98457.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13625/HighFidelity-Beta-Interface-PR14141-bb98457.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13629/HighFidelity-Beta-PR14141-a05e493.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13629/HighFidelity-Beta-Interface-PR14141-a05e493.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13629/HighFidelity-Beta-PR14141-a05e493.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13629/HighFidelity-Beta-Interface-PR14141-a05e493.exe

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 

No warp transitions were seen on any of the bots. Avatars started and loaded in on the spots they stayed at.

**Comment by divyaelango88** [comment]
@conklin94122 looks like this is ready to merge.

**Comment by divyaelango88** [comment]
All 3 labels are in. Merging as per the process.

**Pull request merged**
