### PR TITLE
Try to make application responsive on i5 systems

### PR DESCRIPTION
**Pull request by jherico**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3bf49e454ffe4f8e7938dff84c4fc3f8a2f5b3d6 available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-3bf49e4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-3bf49e4.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3bf49e454ffe4f8e7938dff84c4fc3f8a2f5b3d6 available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-3bf49e4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-3bf49e4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 18635d2e9b409bc592dd3b848479a3d5e795fe36 available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-18635d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-18635d2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 310e95f991d054964382124088c322d053cab1f8 available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-310e95f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-310e95f.dmg

**Comment by OmegaHeron** [comment]
Time to load standard home scene, Interface<->Stack same machine.  All lights in scene set on.

First build (Only attempt to use all cores)
113, 137, 111, 123, 141, 140, 142, 108, 142, 137 = 129.4 AVG 2M 9.4S

Second build (+ Reduce min thread pool)
One run resulted in a deadlock bringing my entire system to frozen state, not just Interface - entire system.
Run after system lockup resulted in NV driver crash, no bugsplat.
Two runs had multiple system lockups with saturated CPU resulting in AC procs crashing - leading to scene load times of > 6 minutes.

155, 156, 150, 150, 146 = 121.4 AVG 2M 1.4S

I can't get 10 runs for average scene load on second build - it repeatedly brings system to unresponsive - AC processes crash and entire load chain has to start over once ACs return.

Neither build offers any improvement over failed RC build - it shifts some of the problems to other places in load sequence, but, it still remains unusable while moving or with an HMD on until scene has fully loaded and you've rotated at least twice to pick up any stragglers -- then you can put on HMD or move around in desktop mode without dire consequence.

Another interesting bit is a almost 100% repeatable effect of - first 1M 45S you see just a few items - like shelves on (not there) wall, the base cube primitive and a web entity.  Then everything starts rezzing in and instabilities begin at high levels.

Again - be clear on my test proc.  I am loading standard home scene, all lights on and holding down key to rotate AV non-stop while scene constructs.  This is **fine* in 5308 and 5353.  Also - it's just as bad if you begin in HMD mode - every microscopic twitch of head movement results in same behavior.

Audio continue to buzz and click while CPU is too busy to deal with audio.  Secondary issue for sure.

**Comment by OmegaHeron** [comment]
I also tried latest build with stack on second machine - it's more or less same results as seen with stack<->interface on same machine.  When it works it's about same time to fully realize scene and same experience as to stuttering, freezes etc.  It also still shows a tendency to crash on launch as it negotiates connection to domain - solid white screen -- windows dialog for interface has stopped working - no bugsplat (not even hidden behind frozen interface window).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9586f4fb5bff4b7e881ef8bc3c340aaa5c268b3c available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-9586f4f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-9586f4f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fe8691408fd1688fa6fdff898292bd4d9170b677 available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-fe86914.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-fe86914.dmg

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9586f4fb5bff4b7e881ef8bc3c340aaa5c268b3c available at: https://gist.github.com/ab5d3343f659dbd7d7d04b197c54d461<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-9586f4f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8659-9586f4f.dmg

**Comment by jherico** [comment]
@OmegaHeron can you try to test the latest build after setting the environment variable `HIFI_DISABLE_SPARSE_TEXTURES` ?

**Comment by OmegaHeron** [comment]
Will do

**Comment by OmegaHeron** [comment]
@jherico does this tie in with #8668 -- if so I'm guessing I can test function without needing to set env vars and save some time?

**Comment by ZappoMan** [comment]
@OmegaHeron - test my PR #8668 - independent of this PR... my PR is automatic... no need to set environment variables.

**Comment by jherico** [comment]
However, bear in mind that #8668 does not include the framerate logic changes, so it will likely still starve the main thread from handling non-rendering work.

**Comment by OmegaHeron** [comment]
@jherico for this PR, with environment var set, should there be an indication in log that it's using alternative methods?  I want to be clear it's actually seeing env var set before commenting further.

**Comment by ZappoMan** [comment]
@OmegaHeron - no -- there's no log on this PR...

**Comment by ZappoMan** [comment]
@OmegaHeron - although... if sparse textures are enabled, you will see the following in your log file... 

```
[09/27 10:32:13] [DEBUG] Don't enable sparse texture for explicitly generated mipmaps on texture  TextureCache::_whiteTexture
```

And if it's disabled you will not see that.

**Comment by OmegaHeron** [comment]
ty @jherico - I'm confident now it was picked up env both via your info and how it behaves.  I'll need some time to compile my findings cross referencing this PR findings, #8668 and RC20 (5353).

**Comment by OmegaHeron** [comment]
Ok - Testing with Windows 10 - i5 6500 CPU - GTX970 GPU

Desktop Mode 1600x900, full screen using standard home scene with all lights on and insured same content for all tests.  LOD adjustment set to 0 so it **does not** invoke LOD culling as trying to LOD adjust while scene is loading adds another layer of hell to life on i5.

The following graphics are not meant to display specific metrics other than offer a abstract view of how my system responds to RC20 (5353), #8659 with and without environment var set and #8668.

8659, 8668 take from 50-75% longer to compose same home scene to completion vs 5353 - so keep that in mind that 5353's graphic represents much shorter intervals for bad looking things.

5 Runs of 5353 loading home scene.  Each jumbled line represents one test - the key is - how often does it stay flat topped vertically at CPU max.

5353overlayed

5 Runs of 8659 without special env var set

8659noenvoverlayed

5 runs of 8659 with env var set

8659envoverlayed

5 runs of 8668

8668overlayed

This PR (8659) with env set has most promising result, but, that said it still is an awful experience compared to 5353.  5353 Usually (usually -- not always) will load scene without ever showing any freezes in Interface or stuttering.  If 5353 does lock up it tends to be very short duration (less than 1 second to 1.5 seconds max) where 8659 and 8668 lock many many many times if one moves during load and with duration often exceeding 3 seconds.

Short of sitting in front of a machine with an i5 and seeing it for yourself... I'm not sure how to convey experience beyond trying to do the graph thing above.  It's interesting to note overall consistency between runs with 5353 and 8659 sans sparse texture bits.  8659 without sparse textures is best of 8668 vs 8659, but, 5353 still wildly outperforms 8668.

**Comment by ZappoMan** [comment]
closing this for now

**Pull request closed without merging**
