### PR TITLE
Fix JSDoc for Users.requestUsernameFromID

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because there are no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9506/app_13102_PR_a35517d9851aad3ea1c324840912670a3c54bcd0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9506/HighFidelity-Beta-PR13102-a35517d9851aad3ea1c324840912670a3c54bcd0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9506/HighFidelity-Beta-Interface-PR13102-a35517d9851aad3ea1c324840912670a3c54bcd0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9506/HighFidelity-Beta-PR13102-a35517d9851aad3ea1c324840912670a3c54bcd0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9506/HighFidelity-Beta-Interface-PR13102-a35517d9851aad3ea1c324840912670a3c54bcd0.exe

**Pull request merged**
