### PR TITLE
New address bar with forward and back buttons

### PR DESCRIPTION
**Pull request by venkatn93**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 428b80a50d11fda3b3c33e90e53f14c793759bcf available at: https://gist.github.com/c0f9697fbc1b20c7c689<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.dmg

**Comment by ctrlaltdavid** [comment]
Hi. Some initial suggestions:
- Rename address-bar.001.svg to address-bar.svg (i.e., just overwrite the old .svg file with the new one).
- Looks like arrowcontainer.svg isn't going to be used? Delete it and commented out code referencing it in AddressBarDialog.qml.
- You should use SVG files for the arrows, not PNGs, because the SVGs will render better.
- You can probably just use one colour of arrow SVG, and simply adjust the opacity to make it lighter when you need to display it greyed out.
- A QML Rectangle should be used instead of a SVG or PNG for the separator bar.
- Check that the reduced font size in the input box is OK by Ryan; if you need more width to display text at the original font size I can make the background SVG wider.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a24e0f7b1423953baf4237be7f5f3935471742e0 available at: https://gist.github.com/c0f9697fbc1b20c7c689<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: de13fe85fe6a58f18b04ec5c2fe235cd32baeeb5 available at: https://gist.github.com/c0f9697fbc1b20c7c689<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1328ea619971967dee5362b43fd45251e7aca35a available at: https://gist.github.com/d28aef9af35676b40e54<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 225e2ebfdc8003be22124f221f26bdce927c6738 available at: https://gist.github.com/c0f9697fbc1b20c7c689<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5124.dmg

**Pull request merged**
