### PR TITLE
fill in linked node data for avatar identity packets, also

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that kept AC agents from seeing other avatars

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- run avatar mixer from this PR and see if ACAudioSearchAndInject.js works

**Comment by sethalves** [comment]
https://highfidelity.fogbugz.com/f/cases/1509/AC-Audio-sometimes-just-cannot-be-found-and-fails-to-play

**Comment by hifi-gustavo** [comment]
Build console output for commit: f34f0f51ec9711991a71e00448953ef8e267972b available at: https://gist.github.com/8b7c6bf3b5b14323a8ad45f32ff836db<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8563-f34f0f5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8563-f34f0f5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 014190a1bfc6162e68ea7d84c2c69db8b6ad891f available at: https://gist.github.com/8b7c6bf3b5b14323a8ad45f32ff836db<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8563-014190a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8563-014190a.dmg

**Pull request merged**
