### PR TITLE
don't assert when unserializing a 'spring' action

### PR DESCRIPTION
**Pull request by sethalves**
- don't assert when unserializing a 'spring' action

https://highfidelity.fogbugz.com/f/cases/6089/

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- no testing needed, only affects debug builds

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9713/app_13159_PR_85a6e2555fcec45ce812fd898088913b1e206089.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9713/HighFidelity-Beta-PR13159-85a6e2555fcec45ce812fd898088913b1e206089.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9713/HighFidelity-Beta-Interface-PR13159-85a6e2555fcec45ce812fd898088913b1e206089.exe

**Pull request merged**
