### PR TITLE
fix metadata hours parsing on mac

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
#### Testing

Must be tested on both Windows and Mac.

- Ensure hours are transmitted. This should be visible in the domain-server logs. Search for `Domain metadata users set`.
- Ensure the ac does not freeze by making sure you can connect to your domain via Interface and access its settings page in a browser (http://localhost:40100).

**Comment by hifi-gustavo** [comment]
Build console output for commit: 80fceccb7e6042ab0fdc5c9c06a9cc51516569a6 available at: https://gist.github.com/eba4687cc319250272b41ed6824ec90d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8160.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8160.dmg

**Comment by birarda** [comment]
Fail on OS X. Settings not accessible, ACs complaining about reaching DS.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b87e902de0c66dd2aea0eaef336a95abc50c720 available at: https://gist.github.com/eba4687cc319250272b41ed6824ec90d<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8160.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8160.dmg

**Comment by birarda** [comment]
Pass. Launches DS with no crash, ACs connect, DS Settings accessible. DS metadata confirmed in log.

**Comment by kevinmthomasse** [comment]
testing

**Comment by ZappoMan** [comment]
Make sure to test a clean install as well as a re-install over an older beta.

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**:  Tested on Windows commit: 1b87e9 old beta.  Launched DS no crash and all AC's connect.  Successfully able to view settings page.  Hours appear in the server log.  Tested on Windows commit: 80fcecc.  Launched DS no crash and all AC's connect. Successfully able to view settings page. Hours appear in the server log.  Tested on Windows after a re-install over old beta.  Successfully able to view settings page.Launched DS no crash and all AC's connect.  Hours appear in the server log.

**Pull request merged**
