### PR TITLE
replace interface/server-console icons with new set from Alan

### PR DESCRIPTION
**Pull request by birarda**
- changed the release/beta/PR icons for Server Console and Interface

### CODE REVIEW

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb95aec52814bd4dea17db4ffed91e70cbde2cdf available at: https://gist.github.com/774c2c5b7730ee18eb3e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7478.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7478.dmg

**Comment by birarda** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: bb95aec52814bd4dea17db4ffed91e70cbde2cdf available at: https://gist.github.com/774c2c5b7730ee18eb3e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7478.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7478.dmg

**Pull request merged**
