### PR TITLE
Add a /forceNoLaunch switch to the installer

### PR DESCRIPTION
**Pull request by zfox23**
Does what it says on the tin.

**Test Plan:**
1. Run the latest installer from http://highfidelity.com/dev-download. When installing, make sure to check the box corresponding to "Launch High Fidelity Interface after install" AND checkbox next to "Launch High Fidelity Sandbox after install". Let the installer complete. Close Interface.
2. Run the installer from this PR built by Gustavo.
3. Press "Next" until you see the screen about choosing components. Select Interface AND Sandbox.
4. Press "Next" until you see the screen about desktop shortcuts and automatically launching Interface. CHECK the checkbox next to "Launch High Fidelity Interface after install" is CHECKED. ALSO CHECK the checkbox next to "Launch High Fidelity Sandbox after install"
5. Press "Cancel" on the installer.
6. Run the same installer from step (2), except, this time, do it from the command line and specify the `/forceNoLaunchClient` switch AND the `/forceNoLaunchServer` switch, i.e. `interface_installer.exe /forceNoLaunchClient /forceNoLaunchServer`
7. Press "Next" until you see the screen about choosing components. Select Interface and Sandbox.
8. Press "Next" until you see the screen about desktop shortcuts and automatically launching Interface. Verify that the checkbox next to "Launch High Fidelity Interface after install" is UNCHECKED. Also verify that the checkbox next to "Launch High Fidelity Sandbox after install" is UNCHECKED.

### CODE REVIEW

**Comment by CainFoool** [comment]
Testing when ready :)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1035/HighFidelity-Beta-PR10794-2318b6aef81e2d597192053ada5c57311c5ee357.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1035/HighFidelity-Beta-PR10794-2318b6aef81e2d597192053ada5c57311c5ee357.exe

**Comment by zfox23** [comment]
@CainFoool - I just updated the code and the test plan. Please test once the latest build completes. Thanks!

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1042/HighFidelity-Beta-PR10794-e5666fbb2f9e0e7fa403cb3eafc74a386e253597.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1042/HighFidelity-Beta-PR10794-e5666fbb2f9e0e7fa403cb3eafc74a386e253597.exe

**Comment by CainFoool** [comment]
# Test Failed

`Install the latest from dev-download (as of now, 6755)` **Pass**


`Run the Installer without the flag - confirm Launch Interface after install is checked` **Pass**


`Run the Installer with the flag - confirm Launch Interface after Install is unchecked` **Fail**


@zfox23 I feel like I might be doing something stupid here - feel free to glance over the gifs to see if I'm doing it all correctly.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by zfox23** [comment]
@CainFoool - Please refresh this page and re-read the test procedure - you have to specify the `/forceNoLaunchClient` switch AND the `/forceNoLaunchServer` switch.

**Comment by zfox23** [comment]
Damn GitHub and their not-auto-refreshing text! 😂

**Comment by CainFoool** [comment]
@zfox23: Ah damnit! Haha, checking now :)

**Comment by CainFoool** [comment]
# Test Passed 

All good from here!


###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by zfox23** [comment]
Thank youuuu! <3

**Comment by CainFoool** [comment]
Anytime <3

**Pull request merged**
