### PR TITLE
when trigger is squeezed, check for things stuck to hand and unhook them

### PR DESCRIPTION
**Pull request by sethalves**
- when trigger is squeezed, check for things stuck to hand and unhook them

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- equip something
- use edit.js to find the equipped item's parentID and parentJointIndex.  copy these and save them
- unequip the thing
- use edit.js to set the things parentJointIndex and then its parentID back to the saved values
- at this point the thing should be stuck to your hand
- squeeze trigger on that hand and confirm that the thing is released
- confirm that further manipulation of the thing goes as expected

**Comment by sethalves** [comment]
I hate you, gustavo

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
test this please

**Comment by sethalves** [comment]
https://app.asana.com/0/26485730907942/92650380521248

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c9cf386a698422ac4f03c777981a0e702ffebac available at: https://gist.github.com/c4b411e0571594d08bfa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5594f1e4e586fbc3967c1ce13526915cfcc457cd available at: https://gist.github.com/c4b411e0571594d08bfa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.dmg

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5594f1e4e586fbc3967c1ce13526915cfcc457cd available at: https://gist.github.com/c4b411e0571594d08bfa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bf8670bc2e3f6def32d4fddf237b1c1c490a040 available at: https://gist.github.com/c4b411e0571594d08bfa<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7209.dmg

**Comment by PhilipRosedale** [comment]
tested and works as described.

**Pull request merged**
