### PR TITLE
initial separation of DS into domain settings and content settings

### PR DESCRIPTION
**Pull request by birarda**
- split the settings in domain server into "domain settings" and "content settings"
- added a settings backup section to "domain settings" that allows download or restore of JSON file
- changed settings styling to put groups/badging on dropdown in navbar
- fixed some bugs related marking settings as changed and able to be saved

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6729/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6729/HighFidelity-Beta-PR12295-fe146d6dcce945ee84da5291b587ea1dcabb0f40.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6729/HighFidelity-Beta-PR12295-fe146d6dcce945ee84da5291b587ea1dcabb0f40.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6732/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6732/HighFidelity-Beta-PR12295-b7f9e05dd7e9a53ed20f883e8663a10ae3a0a55d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6732/HighFidelity-Beta-PR12295-b7f9e05dd7e9a53ed20f883e8663a10ae3a0a55d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6737/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6738/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6738/HighFidelity-Beta-PR12295-c4962bc78a1e389070c49229496d6bbc8c1b6685.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6738/HighFidelity-Beta-PR12295-c4962bc78a1e389070c49229496d6bbc8c1b6685.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6849/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6857/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6857/HighFidelity-Beta-PR12295-a64ec1aef7394ecbb08f7acc5a3e1fb3e1ed1cbd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6857/HighFidelity-Beta-PR12295-a64ec1aef7394ecbb08f7acc5a3e1fb3e1ed1cbd.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6931/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6931/HighFidelity-Beta-PR12295-12490b7e06ae8da5ed2901c0c3b616aa73b3d7e6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6931/HighFidelity-Beta-PR12295-12490b7e06ae8da5ed2901c0c3b616aa73b3d7e6.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6982/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6983/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6984/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6985/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6985/HighFidelity-Beta-PR12295-3955d40c23fa5e8145df6d41a46eb9122e55c571.exe

**Comment by birarda** [comment]
#### Test Plan

Run each of the cases in the following test suite: https://highfidelity.testrail.net/index.php?/suites/view/751&group_by=cases:section_id&group_id=3390&group_order=asc

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6990/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6990/HighFidelity-Beta-PR12295-3e66b8a047a395502370d06f1d6f01de3ab80bc3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6990/HighFidelity-Beta-PR12295-3e66b8a047a395502370d06f1d6f01de3ab80bc3.dmg

**Comment by Qliemillar** [comment]
Currently being tested

**Comment by Qliemillar** [comment]
Tested - FAIL @conklin94122 

Attempting to open the domain server settings in a web browser leads to a (mostly) empty page. Does not occur on Master.

sandbox

**Comment by birarda** [comment]
@Qliemillar fixing, thanks. Meant to include test plans for wizard as well.

I'll update the test plan as well once I push a fix.

**Comment by birarda** [comment]
Pushed fix and added some additional tests to the test plan

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7022/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7022/HighFidelity-Beta-PR12295-d54b09997152bb736be9bfb4fdc17b435d15c525.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7022/HighFidelity-Beta-PR12295-d54b09997152bb736be9bfb4fdc17b435d15c525.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7182/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7182/HighFidelity-Beta-PR12295-37b8fa2c0c84af04bb259d969c9a89c3d5c708ff.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7182/HighFidelity-Beta-PR12295-37b8fa2c0c84af04bb259d969c9a89c3d5c708ff.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7196/app_12295_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7196/HighFidelity-Beta-PR12295-4d4b42848b2b12adb53954cac675391978ee2b71.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7196/HighFidelity-Beta-PR12295-4d4b42848b2b12adb53954cac675391978ee2b71.exe

**Pull request merged**
