### PR TITLE
Fix environment volume slider (BUGZ-213); optimize sliders

### PR DESCRIPTION
**Pull request by zfox23**
Fixes [BUGZ-213](https://highfidelity.atlassian.net/browse/BUGZ-213).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19585/HighFidelity-Beta-PR15608-30c13fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19585/HighFidelity-Beta-Interface-PR15608-30c13fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19585/HighFidelity-Beta-PR15608-30c13fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19585/HighFidelity-Beta-Interface-PR15608-30c13fd.exe

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19588/HighFidelity-Beta-PR15608-30c13fd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/19588/HighFidelity-Beta-Interface-PR15608-30c13fd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19588/HighFidelity-Beta-PR15608-30c13fd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/19588/HighFidelity-Beta-Interface-PR15608-30c13fd.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19588/HighFidelity-Beta-PR15608-30c13fd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/19588/HighFidelity-Quest-Beta-PR15608-30c13fd.apk)

**Pull request merged**
