### PR TITLE
Commerce: Zachs Punchlist 01

### PR DESCRIPTION
**Pull request by zfox23**
Don't formally test.

Huge list of things completed with this PR. Important things are in **bold**.
- Properly make use of `NetworkingConstants::METAVERSE_SERVER_URL` (thanks @howard-stearns 😄)
- **"ui: unhide price (or zero) in html marketplace pages"**
- "ui: BUY => OWN on marketplace pages maybe?"
- **"Determine what to do about "Welcome! Let's get you some spending money.""**
- SET UP MY WALLET should be a blue button
- Disable preview when passphrase OR security image screen is up
- **Show virtual keyboard in the following places:**
    - Passphrase selection
    - Passphrase input (not implemented yet, so didn't do)
- **In Purchases, show "empty purchases" UI element with button to Marketplace if purchases list is empty**
- Don't insert "buy item" button on marketplace item page if it's already injected
- "art: "lock" image and image overlay application to security image"

### CODE REVIEW

**Comment by zfox23** [comment]
[Zach's Punchlist of Random Things (see desc)](https://trello.com/c/g0SHpa8q/353-zachs-punchlist-of-random-things-see-desc)

**Comment by zfox23** [comment]
[Determine what to do about "Welcome! Let's get you some spending money." SEE DESC](https://trello.com/c/d9Ry4tLk/355-determine-what-to-do-about-welcome-lets-get-you-some-spending-money-see-desc)

**Comment by zfox23** [comment]
[ui: BUY => OWN on marketplace pages maybe?](https://trello.com/c/RqYoMqY6/349-ui-buy-own-on-marketplace-pages-maybe)

**Comment by zfox23** [comment]
[ui: unhide price (or zero) in html marketplace pages](https://trello.com/c/B0DkeGHU/345-ui-unhide-price-or-zero-in-html-marketplace-pages)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2878/HighFidelity-Beta-PR11267-a9c99854f9da5a300a9c1daeeb0022c411895cbd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2878/HighFidelity-Beta-PR11267-a9c99854f9da5a300a9c1daeeb0022c411895cbd.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2882/HighFidelity-Beta-PR11267-5d1170c5d604b2ec1956afc67bcb727a51465905.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2882/HighFidelity-Beta-PR11267-5d1170c5d604b2ec1956afc67bcb727a51465905.dmg

**Comment by zfox23** [comment]
[art: "lock" image and image overlay application to security image](https://trello.com/c/ELeB4eEK/339-art-lock-image-and-image-overlay-application-to-security-image)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2890/HighFidelity-Beta-PR11267-6ee634b90ae43295388512abea9273a157b46cb4.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2890/HighFidelity-Beta-PR11267-6ee634b90ae43295388512abea9273a157b46cb4.exe

**Pull request merged**
