### PR TITLE
Rapid uniform change test

### PR DESCRIPTION
**Pull request by ericrius1**
This script and fragment shader file provide a test for a primitive with a fragment shader attached, with a rapidly changing uniform.

### CODE REVIEW

**Comment by ericrius1** [comment]
Run https://rawgit.com/ericrius1/hifi/uniformBugRepro/examples/tests/rapidUniformChange/rapidUniformChangeTest.js

You should see a box appear in front of you- if things work correctly, the box should change color over time. Currently, interface will crash almost every time after running for a few seconds or more

Right now interface crashes when a uniform is updated frequently, (https://app.asana.com/0/inbox/31759584831096/96943843100173/98022172055918)

so this test can be used to repro this and can be run with new changes, to ensure this doesn't happen again in the future.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 170dd418f84d9c2668fd957997dffda64805ccd4 available at: https://gist.github.com/dfb1f2a49f6c68a5230f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.dmg

**Comment by OmegaHeron** [comment]
Just to be clear - this is just a test script to reproduce crash or is it a test script **and** a fixed Interface to prevent crash?

**Comment by imgntn** [comment]
i agree i don't think its a good idea to merge this while it crashes interface

**Comment by ericrius1** [comment]
Agreed- I added a DO NOT MERGE LABEL. Zach can use this to test his fix, and once he fixes and merges that change, we can merge this so it's available as a continuous integration test

**Comment by OmegaHeron** [comment]
Will add it to my torture test kit when its time comes.  +1:

**Comment by zzmp** [comment]
Can you add `print` calls to it, so that if it fails it is easier to debug?
I was thinking of one before the call to `addEntity`, and one before the call to `editEntity`.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2af4dd90e19a86eb5b958cf30e4e95c5b376d4bf available at: https://gist.github.com/dfb1f2a49f6c68a5230f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8fe926e5351ef70ba082ff6431f287082a72aa19 available at: https://gist.github.com/dfb1f2a49f6c68a5230f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5ba96cb07c5390173345c0533e0a00ee1fe71dad available at: https://gist.github.com/dfb1f2a49f6c68a5230f<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7291.dmg

**Comment by ericrius1** [comment]
Now that Zach's fix has been merged, this test is ready to merge as well

**Pull request merged**
