### PR TITLE
OpenVR sensor reset fix

### PR DESCRIPTION
**Pull request by hyperlogic**
fixed OpenVRDisplayPlugin::resetSensors (' should work now)

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6c40b48204c89ec09169f443ac311d044c56717e available at: https://gist.github.com/a8aaa322502bdc05ca34<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85f4d1bfa7eb37ec129d32273336c3d93fe9bc4e available at: https://gist.github.com/a8aaa322502bdc05ca34<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
@hyperlogic the failure on Ubuntu and OS X on this PR is valid. Please check build console output to identify problems.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 85f4d1bfa7eb37ec129d32273336c3d93fe9bc4e available at: https://gist.github.com/a8aaa322502bdc05ca34<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5238.dmg

**Comment by hyperlogic** [comment]
@murillodigital This branch is a PR into the plugins branch not master.  The plugins branch yet build on MacOSX or Linux, as it contains WIP changes by @jherico.

**Pull request merged**
