### PR TITLE
CR for Job #20315 - Update contents of the "welcome to Interface" dialog

### PR DESCRIPTION
**Pull request by Triplelexx**
Code Review for Job #20315 - Workitem available at https://www.worklist.net/20315

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by problem** [comment]
ok to test

**Comment by problem** [comment]
Trying to get Jenkins to build me Interface ...

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bcb3f7c75587a51272f3d5191e02cd8b04c6f58 available at: https://gist.github.com/bd1087a4cc1fa96d8286<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.dmg

**Comment by problem** [comment]
@murillodigital for this to be merged you'll need to update the packager to look for the images in interface/resources/html/img/ -- any objection to that?

CC @nbq

**Comment by murillodigital** [comment]
@nbq not sure I follow, resources/** gets copied into release already (that is, all in resources recursively) which means it should just work as is?

**Comment by problem** [comment]
@murillodigital if the Jenkins build process is different for PR/Test builds, then that makes sense and I follow, but if you install one of the builds above and check the welcome/about dialog, you'll see the images missing ... CC @nbq

**Comment by murillodigital** [comment]
@problem @nbq nope its basically the same build process, and there's an img file (not a directory) of zero bytes inside html/ in that PR build so something's definitely not right. Will look at pr shortly, since evidently it is copying everything recursively but img/ as a directory is not seen as such, ping you back in a bit

**Comment by nbq** [comment]
Here is the commit showing the images added and their location: https://github.com/Triplelexx/hifi/commit/ffc6a6883eeec2c3ff4819f4b9b5e95ab7c3f6b2

Here is the image of how it looks from OS X: http://i.gyazo.com/8c22671f00ba94c231a59e59eaf9f761.png

Here is the image of the directory structure of the Jenkins output showing it missing the files but it has a blank file there, its not picking up the folder/contents: http://i.gyazo.com/01feed890c51662a19724db152e1da49.png

**Comment by nbq** [comment]
Thanks @murillodigital and @problem !

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bcb3f7c75587a51272f3d5191e02cd8b04c6f58 available at: https://gist.github.com/65de46e5434b7ce0a38c<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by nbq** [comment]
Checking now

**Comment by murillodigital** [comment]
@nbq I aborted that build, triggered again --- found something interesting, all PR builds have faulty directories on anything that is 3 levels deep from resources/ not something happening on release build. There was one difference, Pr builds I still had to switch from using Makefiles/make to Xcodebuild. Curious if thats the case and wonder if this is an issue *nix users using make would experience even on a release build.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bcb3f7c75587a51272f3d5191e02cd8b04c6f58 available at: https://gist.github.com/8d90ccfd782dcf45ea7d<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by problem** [comment]
There we go, works great. Ready for a CR as far as I can tell. @murillodigital @nbq

**Comment by nbq** [comment]
Mac one is blank.

**Comment by murillodigital** [comment]
yeah still testing hold on to your horses, I haven't gotten a single build out :P will let you know when ready to test.

**Comment by nbq** [comment]
ROFL @murillodigital - we gotta wait till the pony is out of the stables! @problem we are just giving him a hard time aren't we? :+1:

**Comment by problem** [comment]
LOL! I swear the Windows build worked @murillodigital @nbq

**Comment by murillodigital** [comment]
yeah i dont think windows was ever a problem --- this is mac specific

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1bcb3f7c75587a51272f3d5191e02cd8b04c6f58 available at: https://gist.github.com/61e1e2896a5be8f60821<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4308.dmg

**Comment by problem** [comment]
FWIW, you must have changed something. I wasn't getting the images before (been testing only on Windows for the entirety of the job). @murillodigital

**Comment by murillodigital** [comment]
ok that last Mac build will work @nbq @problem please try -- and on Windows swear I haven't changed anything

**Comment by nbq** [comment]
Looking like we have a winner with the images! http://i.gyazo.com/b3f20503b8373bbe70d187f9a7959f64.png

**Comment by problem** [comment]
Can you do a CR on this @Atlante45 ?

**Comment by Atlante45** [comment]
@problem On it.

**Pull request merged**
