### PR TITLE
Fix osx undefined static class symbols

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by zzmp** [comment]
Do not merge until this builds - I am not sure why the OSX build has undefined symbols, but I think this will solve it: referencing static class members by their class scope.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88b8d76032efb2fadae594b4fa10cc8f98b020dc available at: https://gist.github.com/f890db2dbf3158451dbaa98003778488<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9844-88b8d76.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9844-88b8d76.dmg

**Comment by samcake** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 88b8d76032efb2fadae594b4fa10cc8f98b020dc available at: https://gist.github.com/f890db2dbf3158451dbaa98003778488<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9844-88b8d76.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9844-88b8d76.dmg

**Pull request closed without merging**
