### PR TITLE
[DO_NOT_MERGE] Handshake demo

### PR DESCRIPTION
**Pull request by hyperlogic**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8080/app_12662_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8080/HighFidelity-Beta-PR12662-f489ec2b128794a3ee374db71b1857271c9e90dc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8080/HighFidelity-Beta-PR12662-f489ec2b128794a3ee374db71b1857271c9e90dc.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8092/app_12662_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8092/HighFidelity-Beta-PR12662-3eabd2a242cbb7969efff68255e3060447d75e28.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8092/HighFidelity-Beta-PR12662-3eabd2a242cbb7969efff68255e3060447d75e28.dmg

**Comment by hyperlogic** [comment]
Superseded by handshake v2 #12730

**Pull request closed without merging**
