### PR TITLE
Remove scripts 'Tip' label and fix tool window heights

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e5438a4aded7f440b1cd5a10dccd3fb6791fd66 available at: https://gist.github.com/cd9402383bc6416c432c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4853.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4853.dmg

**Comment by huffman** [comment]
Hold off on this for one moment please

**Comment by huffman** [comment]
Ok, free to review

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7ff9422717e1c23257ebcce3a801e6bd673873e9 available at: https://gist.github.com/cd9402383bc6416c432c<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4853.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4853.dmg

**Pull request merged**
