### PR TITLE
BUGZ-491: Fix tablet.loadWebScreenOnTop()

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Compared with the QML functions, tablet.loadQMLSource() and tablet.loadQMLScreenOnTop(), tablet.gotoWebScreen() already implemented expected tablet.loadWebScreenOnTop() behavior.

(There is no tablet.loadWebScreen() function because it hasn't been needed to date.)

Case: https://highfidelity.atlassian.net/browse/BUGZ-491 / https://highfidelity.atlassian.net/browse/DEV-1821

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21570/HighFidelity-Beta-PR16261-c79581e.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21570/HighFidelity-Quest-Beta-PR16261-c79581e.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21570/HighFidelity-Beta-PR16261-c79581e.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21570/HighFidelity-Beta-Interface-PR16261-c79581e.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21574/HighFidelity-Beta-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21574/HighFidelity-Beta-Interface-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21574/HighFidelity-Beta-PR16261-3b9884c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21574/HighFidelity-Quest-Beta-PR16261-3b9884c.apk)

**Comment by ctrlaltdavid** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21578/HighFidelity-Beta-PR16261-3b9884c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21578/HighFidelity-Quest-Beta-PR16261-3b9884c.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21578/HighFidelity-Beta-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21578/HighFidelity-Beta-Interface-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21578/HighFidelity-Beta-PR16261-3b9884c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21578/HighFidelity-Beta-Interface-PR16261-3b9884c.exe

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21785/HighFidelity-Beta-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21785/HighFidelity-Beta-Interface-PR16261-3b9884c.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21785/HighFidelity-Beta-PR16261-3b9884c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21785/HighFidelity-Quest-Beta-PR16261-3b9884c.apk)

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21785/HighFidelity-Beta-PR16261-3b9884c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21785/HighFidelity-Beta-Interface-PR16261-3b9884c.exe

**Pull request merged**
