### PR TITLE
Cases 10632 and 10633 Particle Explorer UI

### PR DESCRIPTION
**Pull request by Delanir**
[Case 10632](https://highfidelity.fogbugz.com/f/cases/10632/Particle-Emitter-Show-Properties-button-should-change-to-Hide-Properties-when-properties-are-already-visible)
Particle Emitter 'Show Properties' button should change to 'Hide Properties' when properties are already visible

[Case 10633](https://highfidelity.fogbugz.com/f/cases/10633/Particle-Effect-drop-downs-should-be-more-obvious)
Particle Effect dropdowns should be more obvious

particleexplorer

## Test

1. Go to a domain where you have edit/create rights.
2. Open "Create" and create a Particle.
3. On the "Particle Explorer" tab click on the "Show Properties" button.
Expected result: 
A properties text area appears and the text on the "Show Properties" button now reads "Hide Properties".
4. Press the "Hide Properties" button.
Expected result: 
The particle properties disappear and the text of the button now reads "Show Properties".

5. Notice the tabs "General", "Emit", "Radius", etc. Try to open and close the tabs.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5707/app_12012_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5707/HighFidelity-Beta-PR12012-3f8d1516de8f2520aee9921e9e1965dca248006c.dmg

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5715/app_12012_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5715/HighFidelity-Beta-PR12012-3f8d1516de8f2520aee9921e9e1965dca248006c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5715/HighFidelity-Beta-PR12012-3f8d1516de8f2520aee9921e9e1965dca248006c.dmg

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Go to a domain where you have edit/create rights. | 👍 
Open "Create" and create a Particle. | 👍 
On the "Particle Explorer" tab click on the "Show Properties" button. | 👍 
Expected result: | 
A properties text area appears and the text on the "Show Properties" button now reads "Hide Properties". | 👍 
Press the "Hide Properties" button. | 👍 
Expected result: | 
The particle properties disappear and the text of the button now reads "Show Properties". | 👍 
Notice the tabs "General", "Emit", "Radius", etc. Try to open and close the tabs. | 👍 

All working solid. 🎈

**Pull request merged**
