### PR TITLE
Add rolled log files to BugSplat

### PR DESCRIPTION
**Pull request by huffman**
Changes to logfile rolling to allow the first log file of a session to be included in the bugsplat in the event of a crash.

### CODE REVIEW

**Comment by huffman** [comment]
This PR adds rolled log files to BugSplat. Log files are rolled after they reach 1MB or are more than an hour old.

To test:
- Open log file directory, on Windows this will be in`C:\Users\USERNAME\AppData\Local\High Fidelity\Interface\Logs`. You can delete these log files if you don't need them, it will make it easier to see what files are being created later.
- Run interface. You should see hifi-log.txt get created if it isn't already there.
- Stop all scripts. Run https://gist.githubusercontent.com/huffman/603e357a7030ceaa3c2c91a4a214f0f4/raw/3d0782cb7d780d442cb87c782a26a29b4e3ebcf6/spam.js
- That script will spam your log.
- Once hifi-log.txt reaches 1MB it should be rolled and you should see another log file added to the directory.
- Deliberately crash interface. Enable `Settings -> Developer Menus`. Click `Developer-> Crash Interface`
- In the bugsplat window that pops up click `View Report Details` and confirm that you see hifi-log.txt and your rolled log file(s), similar to `hifi-log_10.0.0.40_2016-04-06_10.32.39.txt`.
- Don't send the bug report.

**Comment by jherico** [comment]
You don't have to put a class into a header in order to emit signals / have a Q_OBEJCT macro.  If you put the following

**Comment by jherico** [comment]
whoops.... wrong button.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5fb898de74e39be226f1aaa2485a3885248f4529 available at: https://gist.github.com/0c12f2be7a1af0a5ae1d59d8153fc36e<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7594.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7594.dmg

**Comment by huffman** [comment]
Updated original test procedure to reflect changes.

**Comment by huffman** [comment]
@jherico I think your comment was lost when the PR was closed, and for whatever reason the code portion didn't show up in my email

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6232c82f6665ca8ee16de0884bfc19c5903aecd0 available at: https://gist.github.com/0c12f2be7a1af0a5ae1d59d8153fc36e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7594.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Alpha-PR7594.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Started with no logs present.  Initial log was created, subsequent logs were created on 512K boundaries, bugsplat offered to send correct set of logs.  Content of logs matches what I'm used to seeing.

**Comment by ZappoMan** [comment]
This is the original comment from @huffman about this PR - I moved this out of the description so it won't end up in the release notes.

Note to reviewer: A large portion of the changes is splitting FilePersistThread between the header and source to work with the Qt MOC compiler.

**Pull request merged**
