### PR TITLE
Revert 11728 and fix marketplace JS injection - should revisit

### PR DESCRIPTION
**Pull request by zfox23**
It appears as though #11728 is actually not working, and it was merged before being tested.

**Test Plan:**
1. Enable Commerce
2. Set up your Wallet
3. Open the MARKET app
4. Verify that you see "My Purchases" at the top of the page

### CODE REVIEW

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4785/HighFidelity-Beta-PR11777-33b6a13a4d67a1d9b09c0746a9d2f9c0000f16d2.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Enable Commerce **Check**
Set up your Wallet **Check**
Open the MARKET app **Check**
Verify that you see "My Purchases" at the top of the page **Check**
image

**Pass** Good work :)

**Pull request merged**
