### PR TITLE
disable the bearer poll timeout

### PR DESCRIPTION
**Pull request by birarda**
- set bearer poll timeout to -1 so the timer never starts

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

- On master, run Interface on wireless. Every ~32 seconds you should see your pings to all mixers jump up.
- On this PR, you should not see drastic ping spikes every 32 seconds.

**Comment by CainFoool** [comment]
Testing when Ready

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ac5fbf91dda6e86de6b051835f0e0919fae503f available at: https://gist.github.com/0c3cb4515b28b281c9cb1b8c345c84e3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10491-2ac5fbf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10491-2ac5fbf.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 26d5879ddac239692cb049a28efb2fa415777193 available at: https://gist.github.com/0c3cb4515b28b281c9cb1b8c345c84e3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10491-26d5879.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10491-26d5879.dmg

**Comment by CainFoool** [comment]
Test Complete

Ran Master & this PR - **Passed**! No spikes.

**Pull request merged**
