### PR TITLE
TEAM TEACHING  - primitive (non-model) entities rendering using new engine.

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2f6a3a61d78c0b12bfe8405dfd258a945cdf8257 available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2516066e1dc0e15502acdade327b7287aeeb6280 available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4654ed95ac679605037c40076460a4afaa83006e available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 007aed7a0a674ad54fc3ca52d5cd8f98a9952dde available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8c9cf480f3428b4e1932e49c65507045512d0bce available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a56e0d80b63700a172d5241f3365f773b319ded6 available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 37a291275d32de8f0c63c844c3410179afc648da available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b0cc536f53d8410faa354d027523750dba63dc2f available at: https://gist.github.com/45991597cdafdef4b484<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4966.dmg

**Comment by samcake** [comment]
Brilliant!

**Pull request merged**
