### PR TITLE
Dev319 - Show user who installed content in 'Installed Content' section of domain admin pages

### PR DESCRIPTION
**Pull request by roxanneskelly**
https://highfidelity.atlassian.net/browse/DEV-319

### CODE REVIEW

**Comment by roxanneskelly** [comment]
build me please

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20661/HighFidelity-Beta-PR16004-e4e8fe4.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20661/HighFidelity-Beta-Interface-PR16004-e4e8fe4.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20661/HighFidelity-Beta-PR16004-e4e8fe4.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20661/HighFidelity-Quest-Beta-PR16004-e4e8fe4.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20661/HighFidelity-Beta-PR16004-e4e8fe4.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20661/HighFidelity-Beta-Interface-PR16004-e4e8fe4.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20679/HighFidelity-Beta-PR16004-de1aa68.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20679/HighFidelity-Quest-Beta-PR16004-de1aa68.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20679/HighFidelity-Beta-PR16004-de1aa68.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20679/HighFidelity-Beta-Interface-PR16004-de1aa68.dmg

**Comment by roxanneskelly** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20682/HighFidelity-Beta-PR16004-de1aa68.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20682/HighFidelity-Beta-Interface-PR16004-de1aa68.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20682/HighFidelity-Beta-PR16004-de1aa68.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20682/HighFidelity-Beta-Interface-PR16004-de1aa68.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20682/HighFidelity-Beta-PR16004-de1aa68.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20682/HighFidelity-Quest-Beta-PR16004-de1aa68.apk)

**Comment by antoninahifi** [comment]
currently testing

**Pull request merged**
