### PR TITLE
RC- fixing grabbing and tablet bugs

### PR DESCRIPTION
**Pull request by druiz17**
This PR address the following tickets
https://highfidelity.fogbugz.com/f/cases/7909/double-stylus-confusion-breaks-keyboard
https://highfidelity.fogbugz.com/f/cases/7052/Grip-Trigger-doesn-t-work-to-equip-item-lighter-won-t-light
https://highfidelity.fogbugz.com/f/cases/7778/FarActionGrabModule-does-not-have-sphere-at-the-end-of-the-laser

### CODE REVIEW

**Comment by anshuman64** [comment]
Test plan
1. 
- import the flare gun from the market place
- press the grip button on the hand controller to equip the gun
- press the grip button to drop the item.

2. 
- check that the far grab laser has a sphere at the end of it when intersecting with entities 

3.
- open the tablet
- press down on a button with the stylus but DO NOT release
- the other second stylus should not be able to activate button while the first is still pressing on the tablet button

4.
- Go to the avatar store (currently in dev-content)
- Pull an item off the shelf (you should get only one copy of the item and it should be in your hand, even if you don't have rez permissions
- Put the item onto the correct joint of your avatar and let go. You should hear an audio confirmation that it has attached. 
- In front of the mirror, adjust the position of the attachment. 
- Grab the attachment and pull it off your body. You should hear an audio confirmation that it has detached
- Try resizing the attachment by pressing both grips. Try this while it's parented and while it's not parented to your avatar.

**Comment by Nex-Pro** [comment]
Awaiting Win Build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3869/HighFidelity-Beta-PR11519-13feec89c272736c03b129b8ac1de0354d45f1e7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3869/HighFidelity-Beta-PR11519-13feec89c272736c03b129b8ac1de0354d45f1e7.exe

**Comment by Nex-Pro** [comment]
T E S T I N G  this win10

**Comment by thoys** [comment]
build this please

**Comment by thoys** [comment]
test this please

**Comment by Nex-Pro** [comment]
pass on 1 2 and 3

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3872/HighFidelity-Beta-PR11519-13feec89c272736c03b129b8ac1de0354d45f1e7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3872/HighFidelity-Beta-PR11519-13feec89c272736c03b129b8ac1de0354d45f1e7.exe

**Comment by conklin94122** [comment]
QA Failed #2, please break this into 3 separate PRs.

**Pull request merged**
