### PR TITLE
CR for 20640 - Add DDE option to couple eyelids

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Use the most "open" value for both eyes.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46b48171550455ef465f7d471f529fbe02bf19eb available at: https://gist.github.com/0f0fee9093be053e4c53<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5463.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5463.dmg

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by ctrlaltdavid** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 46b48171550455ef465f7d471f529fbe02bf19eb available at: https://gist.github.com/0f0fee9093be053e4c53<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5463.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5463.dmg

**Comment by ctrlaltdavid** [comment]
Note: Chris has tested this PR.

**Pull request merged**
