### PR TITLE
Add BC7 compression support

### PR DESCRIPTION
**Pull request by Atlante45**
- Adds High Quality BC7 compression support
- Compressed default skybox using BC7

## Test Plan:
- With a clean cache, make sure the textures render correctly
- Check that the default skybox shows and has no aberrant artefacts.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9044cb40d506fdba20ab0f26e6b81e1e75a0488b available at: https://gist.github.com/5e74cf683db56ba067d110c510798c90<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10500-9044cb4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10500-9044cb4.dmg

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9044cb40d506fdba20ab0f26e6b81e1e75a0488b available at: https://gist.github.com/5e74cf683db56ba067d110c510798c90<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10500-9044cb4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10500-9044cb4.dmg

**Comment by claudioshg** [comment]
testing

**Comment by YuppyPlays** [comment]
Will test this.

**Comment by claudioshg** [comment]
### Desktop PC - Windows 10 Home - CPU 4.0GHz Intel i7 - GTX1070 - RAM 16GB - Tested with Oculus Rift

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10500-9044cb4.exe

PASS:
- Cleared all cache.
- Tested in localhost, Welcome, Dev-Welcome, Dev-playa
- All textures rendered normally, and the skybox didn't show any unusual artifacts.

**Pull request merged**
