### PR TITLE
Fix for stuck ATP downloads

### PR DESCRIPTION
**Pull request by huffman**
- fixed a race in signal connection for asset downloads

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

- Load local baked domain from ATP. On master, about 1/20 loads from clean cache you will see some of the KTX requests get stuck. They will never download and they will only switch to fail once you disconnect from the Asset Server.
- On this PR, you should never get into that state.

**Comment by birarda** [comment]
I will test this.

**Comment by birarda** [comment]
Test locally with a dev environment. I ran from a cold cache > 30 times. Never got a stuck download.
Can easily reproduce without this fix.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 89fb0a917b469592ed0d4587dbe70d0a738e5b3e available at: https://gist.github.com/33b6a5923a2955a626ff37e18bc2371e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10325-89fb0a9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10325-89fb0a9.dmg

**Pull request merged**
