### PR TITLE
Case 21489: Fix chat.js textSize (RC80)

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/21489/Chat-app-does-not-display-text-box-wide-enough-to-show-chat-message

https://github.com/highfidelity/hifi/pull/15063

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17757/HighFidelity-Beta-PR15062-289f3f3.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17757/HighFidelity-Quest-Beta-PR15062-289f3f3.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17757/HighFidelity-Beta-PR15062-289f3f3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17757/HighFidelity-Beta-Interface-PR15062-289f3f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17757/HighFidelity-Beta-PR15062-289f3f3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17757/HighFidelity-Beta-Interface-PR15062-289f3f3.exe

**Comment by qlilaseguinolaza** [comment]
Pre merge testing passed.

**Pull request merged**
