### PR TITLE
Fix getting stuck in T-Pose on avatar switch

### PR DESCRIPTION
**Pull request by SamGondelman**
[FB7989](https://highfidelity.fogbugz.com/f/cases/7989/build-7208-Change-avatar-stuck-in-T-pose-until-you-close-and-reopen-client)

Test plan:
- Switch avatars (try a couple, including default avatar)
- Shouldn't get stuck in T-Pose

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3761/HighFidelity-Beta-PR11492-fcfac9efc0b4787872eda616165cc70f43be093c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3761/HighFidelity-Beta-PR11492-fcfac9efc0b4787872eda616165cc70f43be093c.exe

**Comment by cain-kilgore** [comment]
# Test Plan
Test | Result
--- | ---
Switch avatars (try a couple, including default avatar) | Pass
Shouldn't get stuck in T-Pose | Pass

Tried with 10+ avatars from the Marketplace. All worked perfect.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by conklin94122** [comment]
Needs code review.

**Pull request merged**
