### PR TITLE
CR for #20518 - Mute camera button next to mute audio button

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
Retrying as new PR to see if Jenkins will build.

### CODE REVIEW

**Comment by birarda** [comment]
From Jenkins:

```
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.util.Properties.loadConvert(Properties.java:569)
	at java.util.Properties.load0(Properties.java:392)
	at java.util.Properties.load(Properties.java:319)
	at
```

**Comment by birarda** [comment]
That's not your fault - looks like Jenkins having issues - let's see what a retry does

**Comment by birarda** [comment]
test this please

**Comment by murillodigital** [comment]
guys I need to do some more testing to solve this, I won't have time until later tonight, will update the funked PRs then.

**Comment by PhilipRosedale** [comment]
@murillodigital did you get a chance to look at this one?

**Comment by murillodigital** [comment]
@PhilipRosedale did not, but will do that first thing tomorrow - will retest once ready.

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e689b6a86939c3d461754f7e399ca5a9f363030b available at: https://gist.github.com/feb5ff4757452ec94dd4<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e689b6a86939c3d461754f7e399ca5a9f363030b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e689b6a86939c3d461754f7e399ca5a9f363030b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by murillodigital** [comment]
@ctrlaltdavid the original issue is solved however now the PR is running into GLM install issues in ubuntu only, troubleshooting

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: e689b6a86939c3d461754f7e399ca5a9f363030b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e689b6a86939c3d461754f7e399ca5a9f363030b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by murillodigital** [comment]
@cozza13 @PhilipRosedale @ctrlaltdavid good for review/merge

**Comment by cozza13** [comment]
Thanks @murillodigital 

@ctrlaltdavid few things
-The camera does not go off when I click the icon to mute the camera. Let's start with camera off by default. 
-Reset works well. 
-We should try with the other SVG. 
-Update with master. Austin made some DDE tweaks last night.

**Comment by ctrlaltdavid** [comment]
@cozza13 Re the SVG:The graphics design s/w that I have doesn't import SVGs so I just created a couple of OKish SVGs as placeholders. These can easily be replaced with better SVGs from whomever at HiFi does graphics. ... The "other" SVG needs to be enclosed in a red circle, and two SVGs produced: one with a red line crossing the face "out". ... If there's no one at HiFi that does graphics, I'll have a look at getting some software or editing the SVGs in a text editor.

I'll address the other two items shortly.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 35dbb9491c5f9d0e5fbfeeed5c1bf8f6cca1da22 available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by ctrlaltdavid** [comment]
@cozza13 
- I've merged master in.
- Yes, the webcam light stays in because DDE is still running when webcam face tracking is enabled; muting face tracking currently simply skips applying DDE and Faceshift tracker data. For DDE, you would prefer that DDE be stopped when face tracking is muted?
- At start up the camera is muted if Interface was shut down while muted, and it starts up unmuted if Interface was shut down while unmuted. This is the same behaviour as microphone muting. So no change?

**Comment by cozza13** [comment]
@ctrlaltdavid 

* If face tracking is muted then the webcam should turn off. I think it could confuse people if they have muted face tracking but still see their web cam enabled. *
* Correct, keep state at previous shutdown. *

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c21874f000ca4d6af1933b181c0588702050c6b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by ctrlaltdavid** [comment]
@murillodigital It looks like Windows and OSX built OK but not Linux?

**Comment by ctrlaltdavid** [comment]
Test this please

**Comment by murillodigital** [comment]
test this please

**Comment by murillodigital** [comment]
@ctrlaltdavid this PR is not with the best of luck, that last fail on Linux was due to the box unable to get the repo (likely momentary github unavailability) - retesting

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1c21874f000ca4d6af1933b181c0588702050c6b available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Comment by cozza13** [comment]
This looks great @ctrlaltdavid

**Comment by ctrlaltdavid** [comment]
@cozza13 I've updated the mute icons with the files you sent me.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 333da936429f9de01f988f6c41ed7029a9cb9af7 available at: https://gist.github.com/01b86bade828fef10467<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4740.dmg

**Pull request merged**
