### PR TITLE
Handheld Marketplace Tablet

### PR DESCRIPTION
**Pull request by hyperlogic**
Clicking the marketplace icon while wearing an HMD with hand controllers will spawn the marketplace web site within a handheld tablet, instead of on the overlay UI sphere.  When not actively held, the marketplace tablet should follow the user as they navigate the world by teleporting or using the arrow keys.

:warning: This PR introduces a protocol change

* web-entities now have a dpi property.  This property is available using the Entities.getEntityProperties() and Entities.editEntity(), as well as using the edit.js script.
* The maximum texture dimension for webEntities is capped at a 4096.  This prevents physically large entities from consuming gpu memory.
* All entities can now be parented to an avatar's sensor space, by using the "magic" joint number -2 or 65534.  This is the mechanism that the tablet uses to follow the user when moving in the world.
* scripts/system/libraries/WebTablet.js can be used to create web tablets that follow the user in sensor space.
* All QmlOffscreenSurfaces now generate mipmaps and use tri-linear anisotropic filtering to improve legibility.  This includes the main desktop UI overlay and web-entities.
* web-entities should now be easier to click on when using shaky hand controllers.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: aac28b56491c70061c5426543fbc3c163a09c278 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-aac28b5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-aac28b5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 17e8a3c766138cd168c8e5a9ffa38df28aa385e3 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-17e8a3c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-17e8a3c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0a568571b29a99c01689179b7629c0de25bac410 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-0a56857.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-0a56857.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c9720a4cf518e85645f97487a291bb2ea6c73b64 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c9720a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c9720a4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3cdddf14599d6911089854b014f9623753077552 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-3cdddf1.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-3cdddf1.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 43f3e2ef71fb88b6d9e1d18a94895a42fa7f6a8b available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-43f3e2e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-43f3e2e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2dff8aa77f28c130efddc474f330d940b790752 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-b2dff8a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-b2dff8a.dmg

**Comment by hyperlogic** [comment]
Test plan:
  * When in desktop mode or when using oculus without hand controllers.  Clicking the marketplace icon in the main HUD should function as it does in master.  i.e. the marketplace should appear on the UI overlay.
  * When using an oculus or vive with hand controllers.  Clicking the marketplace icon in the main HUD should spawn a tablet in front of the user, which should show the marketplace.
  * The marketplace should be fully functional.
  * When you teleport by using the hand controllers, the tablet should follow you in the world.  It should also follow you if you move in the world using the arrow keys.
  * The tablet can be dismissed by clicking the marketplace icon in the main HUD.
  * Go into edit mode and create a web-entity.  Change the web-entities DPI using the properties panel in the edit.js UI.  It should be a field towards the bottom of the panel.
  * Verify that it's easier to click buttons on web entities, both large and small.

**Comment by thoys** [comment]
## QA report

- When in desktop mode or when using oculus without hand controllers. Clicking the marketplace icon in the main HUD should function as it does in master. i.e. the marketplace should appear on the UI overlay. :+1: 
- If you open the marketplace in desktop, switch to HMD mode. When you click on the marketplace icon a second time, it should hide the marketplace. If you click it a third time it should bring up the tablet marketplace, not the overlay sphere marketplace. :+1: 
- If you open the marketplace in HMD mode and switch to desktop. When you click on the marketplace icon a second time, it should hide the tablet. If you click it a third time it should bring up the marketplace in a 2D window. :+1: 
- When using an oculus or vive with hand controllers. Clicking the marketplace icon in the main HUD should spawn a tablet in front of the user, which should show the marketplace. :+1: 
- The marketplace should be fully functional. :+1: 
- When you teleport by using the hand controllers, the tablet should follow you in the world. It should also follow you if you move in the world using the arrow keys. :+1: 
- The tablet can be dismissed by clicking the marketplace icon in the main HUD. :+1: 
- Go into edit mode and create a web-entity. Change the web-entities DPI using the properties panel in the edit.js UI. It should be a field towards the bottom of the panel. :+1: 
Verify that it's easier to click buttons on web entities, both large and small. :-1:  (See Bugs below)

# Bugs

- If in 2D mode, and you close the market place with the X , the toggle button does not react anymore.
- The toggling button of `Market Place` does not activate while the tablet is active in HMD mode.
- Wasn't able to click buttons on highfidelity.com website while DPI was set to `200`,  was able to when set back to 30.

QA Fail

**Comment by hyperlogic** [comment]
@thoys - thanks for finding these issues with marketplace toggling.  They should be fixed now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1939c6915aee67d19b85701915d0aec8dee1a25d available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-1939c69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-1939c69.dmg

**Comment by hyperlogic** [comment]
WTF, ubuntu fail when only JS has changed?  test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1939c6915aee67d19b85701915d0aec8dee1a25d available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-1939c69.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-1939c69.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: fce207ba5daf9d2219d5edb895f1099b2ab07f92 available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-fce207b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-fce207b.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c2af948e25f23f86f021c6041e78fb610a91fe8d available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c2af948.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c2af948.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c234f1b65deaa5a035a4a88bce395ee389d1ec9c available at: https://gist.github.com/729d894f9735fb70d8616e7ed33278e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c234f1b.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8457-c234f1b.dmg

**Comment by thoys** [comment]
# QA Update

- The marketplace button now functions after pressing the X on the web-window in Desktop mode.
- I don't see the market button toggle when in HMD mode, but I guess we can live without that for now, would have been nice.

QA Pass

**Pull request merged**
