### PR TITLE
new images for My Purchases rez tutorial

### PR DESCRIPTION
**Pull request by howard-stearns**
https://highfidelity.fogbugz.com/f/cases/12410/We-need-a-new-tutorial-for-My-Purchases

### CODE REVIEW

**Comment by howard-stearns** [comment]
**Test Plan:**

On a clean/new install (or removing isFirstUseOfPurchases line in Interface.json), open (market or wallet) => My Purchases. Should see the two images from in the ticket, instead of the old ones.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13825/HighFidelity-Beta-PR14191-6c6d291.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13825/HighFidelity-Beta-PR14191-6c6d291.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13825/HighFidelity-Beta-Interface-PR14191-6c6d291.dmg

**Comment by rickcarr044** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13945/HighFidelity-Beta-PR14191-6c6d291.apk

**Comment by rickcarr044** [comment]
Currently testing PR14191

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13945/HighFidelity-Beta-PR14191-6c6d291.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13945/HighFidelity-Beta-Interface-PR14191-6c6d291.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13945/HighFidelity-Beta-PR14191-6c6d291.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13945/HighFidelity-Beta-Interface-PR14191-6c6d291.exe

**Pull request merged**
