### PR TITLE
Merge Stable back into Master

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/420/HighFidelity-Beta-PR10621-6cc6cd3bf6cf938d1cc26e1bbb30dbc802eb6538.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/420/HighFidelity-Beta-PR10621-6cc6cd3bf6cf938d1cc26e1bbb30dbc802eb6538.exe

**Comment by Atlante45** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/426/HighFidelity-Beta-PR10621-6cc6cd3bf6cf938d1cc26e1bbb30dbc802eb6538.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/426/HighFidelity-Beta-PR10621-6cc6cd3bf6cf938d1cc26e1bbb30dbc802eb6538.dmg

**Pull request merged**
