### PR TITLE
TEAM TEACHING: Culling, LOD and Depth sort added to DrawSceneTask

### PR DESCRIPTION
**Pull request by samcake**
- Introducing the "Job" in the Task, the reason for this is that we want to arrange the order of job operations as a data driven pipeline. this provides us modularity

- Fix a bug on the ItemFilter on the LEss operator, now working fine

- Create a different key for lights so they go in the light bucket

- Defining a DrawSceneTask with 3 jobs DrawOpaque, Draw Light, DrawTransparent
each of the true draw jobs ( Opaque and Transparent) actually cull and LOD items
WE are missing a LOD information to reproduce the test done by LODManager, so it's a no op for now
 Then visible items are then depth sort ( front to back for opaque and back to front for transparent)
And rendered

Ideally we would like to have a a communication mechanism between jobs, still searching...

- Added performance watch at the displaySIde level to check how we perform.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: dd9cafcd095f5807c980b0a2c08e62c71dc863c0 available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3f8bdc14c4e8bf82b64346be416dfd10f9ecfced available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: dd9cafcd095f5807c980b0a2c08e62c71dc863c0 available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Comment by ZappoMan** [comment]
@samcake build errors on unix???

```
/mnt/ebs1/jenkins/jobs/hifi-pull-request-ubuntu/workspace/libraries/render/src/render/DrawTask.cpp:243:73:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:2287:35: error: no match for call to ‘(render::depthSortItems(const SceneContextPointer&, const RenderContextPointer&, bool, const ItemIDs&, render::ItemIDs&)::FrontToBackSort) (render::depthSortItems(const SceneContextPointer&, const RenderContextPointer&, bool, const ItemIDs&, render::ItemIDs&)::ItemBound&, const render::depthSortItems(const SceneContextPointer&, const RenderContextPointer&, bool, const ItemIDs&, render::ItemIDs&)::ItemBound&)’
    while (__comp(*__first, __pivot))
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: eef80774175b60c8a50a87c0f1f6e61769fcbe18 available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 98160c8d604f9f3efd71370c9abf447c819ded03 available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 81396ae5aa92d13bd670a2c677b1e64b4986dc05 available at: https://gist.github.com/fe53602a5b850a245ca2<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4996.dmg

**Pull request merged**
