### PR TITLE
Added AVX detection for Mac/Linux

### PR DESCRIPTION
**Pull request by kencooke**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 27494e54c5b9ad8692dd6a714ecbe45d9f2d04d1 available at: https://gist.github.com/4c91c39d6dd6af15e0f6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a49c4b833bfb212b170c86e65d5432596c532e8 available at: https://gist.github.com/4c91c39d6dd6af15e0f6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a71222237015f81596c74fc6d52ffd7dc3a563fb available at: https://gist.github.com/4c91c39d6dd6af15e0f6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: aef770fcbad123f870e0d210397ac6c9983b0c94 available at: https://gist.github.com/4c91c39d6dd6af15e0f6<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7085.dmg

**Comment by AndrewMeadows** [comment]
@kencooke: how best to test this on linux?

**Comment by OmegaHeron** [comment]
I'm going with a just does it compile test on Linux to start with.

**Comment by OmegaHeron** [comment]
Got a good compile on Linux so, now, will wait for some test cases to see how to QA beyond

**Comment by AndrewMeadows** [comment]
@OmegaHeron: looking at it again I think the only way to test is to make sure the HRTF (head-related transfer function) code still works.  That is, if you have a nearby noise source, as you rotate in place the noise should sound like it is moving around you -- you can tell where it is even when you shut your eyes and listen.

**Comment by OmegaHeron** [comment]
@AndrewMeadows - thanks and that sounds a reasonable test.  Will give it a try this evening after dinner.

**Comment by kencooke** [comment]
Right now the only thing using AVX instructions is the audio-mixer.  To test, run the assignment-client on Linux, make sure no crash on startup (when the AVX detection is done) and make sure the domain still has working audio (which is rendered via AVX dispatched code).

**Comment by OmegaHeron** [comment]
Then this one passes for me - AC running as audio server runs and produces audio same as current production code.

**Pull request merged**
