### PR TITLE
make building tools (besides 'scribe') optional

### PR DESCRIPTION
**Pull request by ElderOrb**
Again, purely to speedup dev builds. Unfortunately it turned out 'scribe' tool is required for build so it is not excluded at the moment.

### CODE REVIEW

**Comment by ElderOrb** [comment]
for QA: 

The following build configuration should include all the tools (like it used to be) 
cmake .. -G "Visual Studio 15 Win64" 

And this one should exclude all the tools besides 'scribe' from build
cmake .. -G "Visual Studio 15 Win64" -DBUILD_TOOLS=OFF

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/2987/HighFidelity-Beta-PR11291-4edda6284da7712703f9e6d44001ae43ea3f224b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/2987/HighFidelity-Beta-PR11291-4edda6284da7712703f9e6d44001ae43ea3f224b.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3322/HighFidelity-Beta-PR11291-04305155d098365f8753a4ec315d6d1f75cb4bac.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3329/HighFidelity-Beta-PR11291-04305155d098365f8753a4ec315d6d1f75cb4bac.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3329/HighFidelity-Beta-PR11291-04305155d098365f8753a4ec315d6d1f75cb4bac.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10/VS2k17 + Linux

QA Pass

Works as advertised, makes no problematic change to existing compile cycle that I can determine (I.e. if not passed flag cmake's output is = to current output).

**Pull request merged**
