### PR TITLE
Replace permission error messages with login window

### PR DESCRIPTION
**Pull request by kunalgosar**
Resolution for: https://highfidelity.fogbugz.com/f/cases/2830/Swap-the-necessary-permissions-message-for-a-login-button 

Add showLoginDialog to Scripting Interface. Open login prompt on permissions error if user is not logged in. Affects the errors: INSUFFICIENT_PERMISSIONS_IMPORT_ERROR_MSG and INSUFFICIENT_PERMISSIONS_ERROR_MSG.

Test by triggering these errors while logged out, and while logged in. Login window should open on these errors, when logged out only.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: cdc5e3d1a782224e979d456c0cb25018e397854c available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-cdc5e3d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-cdc5e3d.dmg

**Comment by OmegaHeron** [comment]
Fogbugz reference is missing (say case removed or something like)

I'm guessing this would need to be tested like;
User not logged in
User goes to domain and tries to import something or tries to edit something
Look at how that works with master vs this PR

Is that, essentially, correct for testing?  It's less than clear how to test this specifically from its test process method.

**Comment by kunalgosar** [comment]
Fogbugz reference seems to be working for me. 

Right, that is correct for testing. Expected results are: 
- When user not logged in and tries to import something or edit, a login window opens.
- When user is logged in and imports something or edits, where they do not have permission, no login window should open.

**Comment by davidkelly** [comment]
So if I've setup my domain so only certain users can edit/rez, when an anonymous user comes in, and tries to edit, will they get a message telling them to login?  Cuz, after they do, they still cannot edit unless they are one of the special people.  Or perhaps I've set it up where only the client on localhost can edit.  Same thing assuming they are not local.  Seems we need to look at the permissions and determine _if_ logging in will be all that is necessary, perhaps.

**Comment by cozza13** [comment]
@kunalgosar is going to get some more guidance on options.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5bce38e9a459ad06b804c772ceaaf929160aaec8 available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-5bce38e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-5bce38e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b5644a4f7fcfac89c7824b75299ede98f2b59e44 available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-b5644a4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-b5644a4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: cda07269cee2fc5034db33c195254e5c9c3740c6 available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-cda0726.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-cda0726.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79ce5d439df0ad230b5b3e1a0271593b765a6b2e available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-79ce5d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-79ce5d4.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58128a844b87868c37e256460f1f7fe0ce7e617b available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-58128a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-58128a8.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 79ce5d439df0ad230b5b3e1a0271593b765a6b2e available at: https://gist.github.com/7e5035f3f3d4262120e6db0dca069d3f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-79ce5d4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9568-79ce5d4.dmg

**Comment by ZappoMan** [comment]
Do we need to close this PR? What PM owns this issue/feature? @cozza13 @RyanDowne ??

**Pull request closed without merging**
