### PR TITLE
Remove all usage of oglplus

### PR DESCRIPTION
**Pull request by jherico**
## Testing

Application functionality should be unchanged.  There were substantial changes to the OpenVR implementation, so it should be tested on Vive headsets on both AMD and nVidia systems for stability.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ddcb5cd0a1b5e9faae255f4a63d749af8dabc849 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ddcb5cd.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ddcb5cd.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f6abbf5d7800c67030efc3e9e7fd5763f6d14e60 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-f6abbf5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-f6abbf5.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 120068fe668c95a132ecb2fdfe0ebb8c42b4942a available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-120068f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-120068f.dmg

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 120068fe668c95a132ecb2fdfe0ebb8c42b4942a available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-120068f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-120068f.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU

Desktop Mode 1600x900 maximized window.
General smoke test passes - I noticed no visual changes between this PR and current RC 5407

5 Runs of this PR vs 5 Runs of RC21 (5407).  New data logging procedure - only reporting Interface CPU use and each run at same duration of 2 minutes.  Standard home scene, all lights on via localhost.  5407 = Red This PR 8686 = Black

8683overlayed5407

As shown by graphs there's no large change to CPU use and my tests shows no real difference to feel of loading standard home scene.

It's interesting to note that sometimes after scene loads and I stop rotating AV that CPU use drops to lower level - other times staying, comparatively, high.  Will be watching that more ongoing.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a6f41173ae6171855a69a32698de8e742a76280 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-6a6f411.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-6a6f411.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2d9ee0e485191f6d3ba3989d71ea959d313dbef4 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-2d9ee0e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-2d9ee0e.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: e293ab00366a09b21e7cfb0c0c99a46ac319be2b available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-e293ab0.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-e293ab0.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53f358d77a746d651791a131ca78a8b7813894bc available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-53f358d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-53f358d.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9bc0f2477702da1d2ba5dbee6dcfac58bf5f9fd6 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-9bc0f24.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-9bc0f24.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce8fcfed36aa0e6237d9a3ba6f4b31d3d75d1116 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ce8fcfe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ce8fcfe.dmg

**Comment by ZappoMan** [comment]
Needs to be tested on array of HMDs and OSs.

Win/Mac/CV1/DK2/Vive

**Comment by OmegaHeron** [comment]
There seems to be no binary build of this to do final testing on...

**Comment by jherico** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: ce8fcfed36aa0e6237d9a3ba6f4b31d3d75d1116 available at: https://gist.github.com/58d1d1d2a5f5b2d3d5dd48274ca34057<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ce8fcfe.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8683-ce8fcfe.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX 970 GPU

Standard home scene, desktop mode - scene appears/loads/works same as master.  Performance unchanged from 5407.

Standard home scene, DK2 - scene appears/loads/works same as master.  Performance unchanged from 5407.

Also looked at dev-playa and dev-demo both in Desktop/DK2 modes.  Looks/works same as 5407.

**Pull request merged**
