### PR TITLE
put back old-style avatar-attachments menu-item

### PR DESCRIPTION
**Pull request by sethalves**
- put back old-style avatar-attachments menu-item

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- activate Settings --> Attachments menu and exercise its functionality

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11417/HighFidelity-Beta-PR13644-08fced9.apk

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/16865

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11417/HighFidelity-Beta-PR13644-08fced9.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11417/HighFidelity-Beta-Interface-PR13644-08fced9.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11417/HighFidelity-Beta-PR13644-08fced9.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11417/HighFidelity-Beta-Interface-PR13644-08fced9.exe

**Comment by qlihifitest** [comment]
Currently Testing

**Comment by qlihifitest** [comment]
Passes
@Qliemillar @qliacoombs @conklin94122

**Pull request merged**
