### PR TITLE
Fixup PR13870: Make the feature work in Master

### PR DESCRIPTION
**Pull request by zfox23**
The code in #13870 worked when I merged it. Now it doesn't. This PR fixes the code.

### CODE REVIEW

**Comment by zfox23** [comment]
Test plan for this PR is Test 6 from [this comment](https://github.com/highfidelity/hifi/pull/13870#issuecomment-415901438).

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12498/HighFidelity-Beta-PR13905-b8cd5dd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12498/HighFidelity-Beta-Interface-PR13905-b8cd5dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12498/HighFidelity-Beta-PR13905-b8cd5dd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12498/HighFidelity-Beta-Interface-PR13905-b8cd5dd.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 @zfox23 
Logged in state behaves as expected in Step 6.

**Pull request merged**
