### PR TITLE
DO NOT MERGE! - Actions over wire

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6e34678a593746308175fb0392d7db784abded1a available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a46e8ed14cb64f72726e72884845e6087fa6457c available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 50d852546012b440d2fa088482279256d749b06e available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c95db5672a32dc837adf46e6348b2b323b643db6 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d09588b7fafbf81ac1f7fac7bc17f45aecc35c49 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e8113a63c913f99563dfa08fdefff93c27127d6 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e8113a63c913f99563dfa08fdefff93c27127d6 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9e8113a63c913f99563dfa08fdefff93c27127d6 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: bc7271769c1e34e2e0f3e56155eebb0b5053baa2 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 70aa762f61b820d0e6b83cdea485234f5b458a1c available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b4537b081ff7f7b912ea22b98916ce79e8ffa5dc available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 13267915029e855c6ad1371692784cbb56231cce available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5e6597226556887ce9d6bd6f6a24c0c8fc732c08 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7def9c2e28ab9507e4ecde057269c011ac04d801 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0739c462491fd82ff35c7d22461411850ab26eee available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9f6ec4120dc93bf9238f31598a66cc29c4b661db available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0970f010a4e57a5a335e5af17293753fac626c75 available at: https://gist.github.com/b15aa01544a2491306e3<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5195.dmg

**Pull request closed without merging**
