### PR TITLE
BUGZ-1456/HMD-audio-setting-shows-up-when-desktop-mode (84)

### PR DESCRIPTION
**Pull request by MiladNazeri**
https://highfidelity.atlassian.net/browse/BUGZ-1456

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21328/HighFidelity-Beta-PR16195-67254bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21328/HighFidelity-Beta-Interface-PR16195-67254bb.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21328/HighFidelity-Beta-PR16195-67254bb.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21328/HighFidelity-Quest-Beta-PR16195-67254bb.apk)

**Comment by shanzzam** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21331/HighFidelity-Beta-PR16195-67254bb.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21331/HighFidelity-Quest-Beta-PR16195-67254bb.apk)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21331/HighFidelity-Beta-PR16195-67254bb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21331/HighFidelity-Beta-Interface-PR16195-67254bb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21331/HighFidelity-Beta-PR16195-67254bb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/21331/HighFidelity-Beta-Interface-PR16195-67254bb.exe

**Pull request merged**
