### PR TITLE
Fix near trigger

### PR DESCRIPTION
**Pull request by sethalves**
- fix a bug that caused near-trigger to fire repeatedly

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- import this json
- use HMD and hand controllers to "near trigger" the dropper
- observer that is produces one ball per click
```javascript
{
    "Entities": [
        {
            "compoundShapeURL": "http://headache.hungry.com/~seth/hifi/dropper.obj",
            "dimensions": { "x": 1.28, "y": 0.896, "z": 1.28 },
            "modelURL": "http://headache.hungry.com/~seth/hifi/dropper.obj",
            "name": "dropper",
            "queryAACube": { "scale": 2.019806146621704, "x": -1, "y": -1, "z": -1 },
            "rotation": { "w": 1, "x": 0, "y": 0, "z": 0 },
            "script": "http://headache.hungry.com/~seth/hifi/spawn-ball.js",
            "shapeType": "compound",
            "type": "Model",
            "userData": "{\"grabbableKey\":{\"wantsTrigger\":true}}"
        }
    ],
    "Version": 73
}
```

**Comment by Nex-Pro** [comment]
@sethalves  Will test when windows build shows up

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3658/HighFidelity-Beta-PR11467-8180acbffcac123e05e21a5ab5c90618f53addf5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3658/HighFidelity-Beta-PR11467-8180acbffcac123e05e21a5ab5c90618f53addf5.exe

**Comment by Nex-Pro** [comment]
PASS.

Another issue reported but not due to this PR.

**Pull request merged**
