### PR TITLE
Don't hit certain Commerce backend endpoints when wallet isn't yet auth'd

### PR DESCRIPTION
**Pull request by zfox23**
This shouldn't change anything for the user, but prevents BugSnags on the backend.

### CODE REVIEW

**Comment by zfox23** [comment]
## Test Plan
### Prerequisites
- Log into your HiFi account.
- Have a wallet set up but _do not_ authenticate it for this session.
- You've already purchased an entity item or wearable from the Marketplace (we'll call this Item A below).

### Plan
1. Open the Marketplace. Go to buy Item A again.
    - Verify that you are prompted to enter your passphrase
2. Authenticate your wallet
    - Verify that you see the Checkout screen, and that you see a button that says "BUY IT AGAIN" and a button that says "VIEW IN MY PURCHASES".

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7895/HighFidelity-Beta-PR12600-b273d78729d7f6922a8e87d85ccdb262fc66cbcd.dmg

**Comment by howard-stearns** [comment]
test this please

**Comment by howard-stearns** [comment]
and fuck you

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7921/app_12600_PR.apk

**Comment by murillodigital** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7922/app_12600_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7922/HighFidelity-Beta-PR12600-b273d78729d7f6922a8e87d85ccdb262fc66cbcd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7922/HighFidelity-Beta-PR12600-b273d78729d7f6922a8e87d85ccdb262fc66cbcd.exe

**Comment by qlimnavarro** [comment]
Currently testing.

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
