### PR TITLE
clear wallet when picking a new one

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes "Wrong wallet displays after "Locate Other Keys" button is selected"

### CODE REVIEW

**Comment by howard-stearns** [comment]
Fixes https://highfidelity.manuscript.com/f/cases/13058/Wrong-wallet-displays-after-Locate-Other-Keys-button-is-selected

Test plan:
Unfortunately, we need to test all the wallet setup stuff. I believe the tests are:

"end seeding" https://highfidelity.testrail.net/index.php?/cases/view/12737&group_by=cases:section_id&group_order=asc&group_id=3940
"setup: 1st Test" https://highfidelity.testrail.net/index.php?/cases/view/2185&group_by=cases:section_id&group_order=asc&group_id=440
"Recover from Backup Keys" https://highfidelity.testrail.net/index.php?/cases/view/6012

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7903/app_12603_PR.apk

**Comment by conklin94122** [comment]
@howard-stearns Can I mark as QA Ready, or not yet?

**Comment by howard-stearns** [comment]
yes @conklin94122, you can mark qa ready.  (I try to wait until it's built, but I have no objection to having the label mean that it will be ready. Easier for me!)

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7903/HighFidelity-Beta-PR12603-883528488cde5c3acc41c23a2c289065a70aa121.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7903/HighFidelity-Beta-PR12603-883528488cde5c3acc41c23a2c289065a70aa121.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122

**Pull request merged**
