### PR TITLE
RC73: fix for deadlock in other avatar entity removal from tree

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13078/HighFidelity-Beta-PR14017-f985c69.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13078/HighFidelity-Beta-PR14017-f985c69.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13078/HighFidelity-Beta-Interface-PR14017-f985c69.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13078/HighFidelity-Beta-PR14017-f985c69.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13078/HighFidelity-Beta-Interface-PR14017-f985c69.exe

**Comment by birarda** [comment]
#### Test Plan

1.  Follow the same rigorous test for avatar entities used on #13907.
2. Test the removal of many avatars at once, either by stopping an avatar mixer or by co-ordinating the removal of bots with me in engine-dev. When many avatars are removed you should not experience a deadlock.

**Comment by antoninahifi** [comment]
FAILED @conklin94122 

Interface is crashing on connect/disconnect to domain, on internet connection disconnect, login/logout, no deadlock observed

**Comment by birarda** [comment]
Amended and pushed a fix in `a63430c`

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13091/HighFidelity-Beta-PR14017-a63430c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13091/HighFidelity-Beta-PR14017-a63430c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13091/HighFidelity-Beta-Interface-PR14017-a63430c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13091/HighFidelity-Beta-PR14017-a63430c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13091/HighFidelity-Beta-Interface-PR14017-a63430c.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

The avatar entities tests passed (quit interface, login/out, change domains, network disconnects, and ignores). 

Second part of test ended up being more difficult, but we verified it was resolved. Worked with Birarda to go to Engine-dev with the 400~ bots. Took a bit to verify repeat steps to cause defect, but we finally got the deadlock to occur on Master-9366 and PR14006 (RC73). 

Birarda's step: use supervisor on the box to wrangle the agent processes and then just `stop all` or `start all`

This PR did not deadlock the interface the 4 times we attempted it. PR passes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13139/HighFidelity-Beta-PR14017-a63430c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13139/HighFidelity-Beta-PR14017-a63430c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13139/HighFidelity-Beta-Interface-PR14017-a63430c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13139/HighFidelity-Beta-PR14017-a63430c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13139/HighFidelity-Beta-Interface-PR14017-a63430c.exe

**Pull request merged**
