### PR TITLE
Case 20653: QmlMarketplace - disable links if 3dhtml surfaces are not available

### PR DESCRIPTION
**Pull request by roxanneskelly**
* don't show for-hfc items when running from the oculus store

### CODE REVIEW

**Comment by roxanneskelly** [comment]
Test Plan:
1) In staging marketplace, bring up an item with attributions (both with link and without) and validate that the attributions with links a) Look blue, and b) open the link when clicked.

2) Bring up an item with a description containing a link and validate that the link shows as 'blue'

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17137/HighFidelity-Beta-PR14876-c775a9b.apk

**Comment by roxanneskelly** [comment]
https://highfidelity.manuscript.com/f/cases/20653/marketplace-api

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17137/HighFidelity-Beta-PR14876-c775a9b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17137/HighFidelity-Beta-Interface-PR14876-c775a9b.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17145/HighFidelity-Beta-PR14876-4bbb030.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17145/HighFidelity-Beta-PR14876-4bbb030.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17145/HighFidelity-Beta-Interface-PR14876-4bbb030.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17145/HighFidelity-Beta-PR14876-4bbb030.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17145/HighFidelity-Beta-Interface-PR14876-4bbb030.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17164/HighFidelity-Beta-PR14876-93665fa.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17164/HighFidelity-Beta-PR14876-93665fa.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17164/HighFidelity-Beta-Interface-PR14876-93665fa.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17164/HighFidelity-Beta-PR14876-93665fa.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17164/HighFidelity-Beta-Interface-PR14876-93665fa.exe

**Comment by roxanneskelly** [comment]
Also fixes: https://highfidelity.manuscript.com/f/cases/edit/21085/Changing-domains-scripting-APIs-no-longer-work-in-scripts-or-scipt-console

**Pull request merged**
