### PR TITLE
Fix unreachable eye blink code

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Reinstates original logic to force an eye blink after finish speaking.

**Comment by ctrlaltdavid** [comment]
Testing

Look at your own avatar in fullscreen mirror.
Talk then stop talking.
Your avatar should blink.

**Comment by hifi-gustavo** [comment]
Build console output for commit: a0bc8ae2eeaa0d32adea3d43bb7d1b7f691368a4 available at: https://gist.github.com/ee6f0115713914699f3944bffe4f9e4e<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10430-a0bc8ae.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10430-a0bc8ae.dmg

**Comment by YuppyPlays** [comment]
Testing

**Comment by YuppyPlays** [comment]
Testing complete:

Stared at my character in mirror mode, eyes blinked after every sentence or general sequence of words.

Passed, Issue resolved.

**Pull request merged**
