### PR TITLE
BUGZ-1017: fix bug that caused comfort-mode to be active at all times in HMD

### PR DESCRIPTION
**Pull request by sethalves**
- fix bug that caused comfort-mode to be active at all times in HMD

https://highfidelity.atlassian.net/browse/BUGZ-1017

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20396/HighFidelity-Beta-PR15935-22a913b.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/20396/HighFidelity-Beta-Interface-PR15935-22a913b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20396/HighFidelity-Beta-PR15935-22a913b.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/20396/HighFidelity-Beta-Interface-PR15935-22a913b.exe

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20396/HighFidelity-Beta-PR15935-22a913b.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/20396/HighFidelity-Quest-Beta-PR15935-22a913b.apk)

**Comment by AndySeattle** [comment]
This passed Pre-merge QA Testing :)

**Pull request merged**
