### PR TITLE
Removed rescaling of dragged-dropped zipped models (bug 12599).

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
This "bug" was causing large models that have been dropped into Interface to be very small.  This was actually a feature that was implemented for specific models that were in cm/mm instead of metres.  The effect was that the models were way too big.

PLEASE READ - https://highfidelity.manuscript.com/f/cases/12599/

# Testing
Use this file for testing:  https://hifi-content.s3.amazonaws.com/elisalj/models/whale.zip

1. Drag and drop zip file: size is correct (a 30m blue whale (note that the model is not blue).
2. Find the unzipped file in the asset browser and add to world: same size
3. Add via Model in Create menu (using https://hifi-content.s3.amazonaws.com/elisalj/models/whale/whale.obj): comes in same size.

### CODE REVIEW

**Comment by ZappoMan** [comment]
hmmm - why are we removing this?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7529/app_12504_PR.apk

**Comment by NissimHadar** [comment]
Elisa opened the bug, as she had problems importing a whale model.  I spoke
with David Rowe who did the change, and also with Alan; Alan, like me,
thinks it would be best to remove this.

Wavefront .obj files have no concept of units, but both Blender and Unity
assume the units are metres.  I think we should do the same.

**Comment by ZappoMan** [comment]
but this has the side effect of changing how ALL models are imported... this is pretty much a core feature that was intentionally built to do this. I want to see the PM and TL for edit tools sign off on this change before it's merged.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7529/HighFidelity-Beta-PR12504-3cac899cf9729dcf5192ad8987539d6060acbaf0.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7529/HighFidelity-Beta-PR12504-3cac899cf9729dcf5192ad8987539d6060acbaf0.dmg

**Comment by misslivirose** [comment]
In the event that we're not properly able to attain the dimensions right off the bat, what is the failure case in this scenario? Is the root cause with this that the OBJ files are never properly giving new dimensions because they don't have that concept by default? Does this bug repro with FBX models?

**Comment by NissimHadar** [comment]
OK.  It only impacts "drag and drop" of zipped models.  And, the previous
implementation was wrong - all models larger than some limit are rescaled
so their maximum dimension is 1.0.  And - models that are imported from the
asset browser or through the Create menu, are not rescaled.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7551/app_12504_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7551/HighFidelity-Beta-PR12504-401829979b13f3644ceb10c9826a2af3750b015c.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7551/HighFidelity-Beta-PR12504-401829979b13f3644ceb10c9826a2af3750b015c.dmg

**Comment by AndrewMeadows** [comment]
It sounds like this really is removing behavior that we DON'T want:  all three "create" paths now produce the same correct results.  The QA test will confirm or not.

The code looks good.

**Comment by misslivirose** [comment]
I would like to see this run with test plans for: 
* FBX models
* OBJ models
Both added to world from the Create menu and compared to their result from putting those same models in the Asset Browser and adding from that method. They should all have the exact same results for dimensions, let's include that in the test plan.

**Comment by ZappoMan** [comment]
I am going to close this PR... this is not the proper fix to the originally reported bug.

The Content (tools) team owns determining the correct spec and test plans for importing of models, and they should probably be the ones to fix this when it comes around to that. I am also reassigning the bug.

**Pull request closed without merging**
