### PR TITLE
Introduce gpu::Shader, Pipeline and State

### PR DESCRIPTION
**Pull request by samcake**
- add the shader class in gpu, the shader is the abstraction of the actual underneath gl shader and/or glprogram. the Shader is defined from glsl source

- add the State object in gpu which is for now an empty shell, it will contain the full description of the fixed states of the gpu context (blend, rasterization, depth, stencil, scissor etc) this is a work in progress just so i could move forward

- add the pipeline class in gpu. The pipeline is the full description of an operational state and shader ready to be assigned in a batch and ready to draw primitives with it.
 THe pipeline is a static object defined at creation from a shader(program) and a state object

- added support for the pipeline in the Batch flow of command, this is going THE way to assign both shaders and states in a single call, can't wait to use that

- playing with the atmosphere effect to test the design, nothing operational yet :)
Please don't spend much time on that.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee5409b0a8c4a9e8e6d4d7b89872ed6a90ddec6a available at: https://gist.github.com/d068540a3ba3e4e8dc49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d9c071a2a9a6ed4c471a0efa498330b942724baf available at: https://gist.github.com/d068540a3ba3e4e8dc49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.dmg

**Comment by samcake** [comment]
Allright, i messed up because the commits since last night should have been in a different branch
so i m making a last commit that brings back the code to end of day monday

**Comment by hifi-gustavo** [comment]
Build console output for commit: 853cf75f606e919781eac42ea19d043b42619eb9 available at: https://gist.github.com/d068540a3ba3e4e8dc49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: c1a0d767c926ac4e820a47fb7b0b92ef0d8abfff available at: https://gist.github.com/d068540a3ba3e4e8dc49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.dmg

**Comment by samcake** [comment]
Ready for review

**Comment by hifi-gustavo** [comment]
Build console output for commit: da16baf0ca2d9e409600d481f8f15351c1dd7c2f available at: https://gist.github.com/d068540a3ba3e4e8dc49<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4400.dmg

**Comment by ZappoMan** [comment]
smoke tested on mac and windows. looks good.

**Pull request merged**
