### PR TITLE
Fix old log files not being cleaned up

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9239/app_13018_PR_d3fa3b15f16a7ba644818383615e348fae6d0d60.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9239/HighFidelity-Beta-PR13018-d3fa3b15f16a7ba644818383615e348fae6d0d60.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9239/HighFidelity-Beta-Interface-PR13018-d3fa3b15f16a7ba644818383615e348fae6d0d60.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9239/HighFidelity-Beta-PR13018-d3fa3b15f16a7ba644818383615e348fae6d0d60.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9239/HighFidelity-Beta-Interface-PR13018-d3fa3b15f16a7ba644818383615e348fae6d0d60.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9241/app_13018_PR_5ea701a406c1cf0957dc77fc2a097723063f490d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9241/HighFidelity-Beta-PR13018-5ea701a406c1cf0957dc77fc2a097723063f490d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9241/HighFidelity-Beta-Interface-PR13018-5ea701a406c1cf0957dc77fc2a097723063f490d.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9308/app_13018_PR_29b00f9b0737123de7a9201a881ab021fa2b4e86.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9308/HighFidelity-Beta-PR13018-29b00f9b0737123de7a9201a881ab021fa2b4e86.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9308/HighFidelity-Beta-Interface-PR13018-29b00f9b0737123de7a9201a881ab021fa2b4e86.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9333/app_13018_PR_0b5747963bb470bef8f194dc563fe14b9556a776.apk

**Comment by huffman** [comment]
To test: https://highfidelity.testrail.net/index.php?/cases/view/16115

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9336/app_13018_PR_73cea112eefa7541a05394426f74e0652cb07efb.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9336/HighFidelity-Beta-PR13018-73cea112eefa7541a05394426f74e0652cb07efb.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9336/HighFidelity-Beta-Interface-PR13018-73cea112eefa7541a05394426f74e0652cb07efb.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9336/HighFidelity-Beta-PR13018-73cea112eefa7541a05394426f74e0652cb07efb.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9336/HighFidelity-Beta-Interface-PR13018-73cea112eefa7541a05394426f74e0652cb07efb.exe

**Comment by birarda** [comment]
This code looks good, but I'm wondering if we shouldn't remove the age check. If the file size limit is working properly a 1 hour limit on log age seems pretty extreme.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9386/app_13018_PR_86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9386/HighFidelity-Beta-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9386/HighFidelity-Beta-Interface-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9409/HighFidelity-Beta-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9409/HighFidelity-Beta-Interface-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9411/app_13018_PR_86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9411/HighFidelity-Beta-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9411/HighFidelity-Beta-Interface-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9411/HighFidelity-Beta-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9411/HighFidelity-Beta-Interface-PR13018-86986e0a8ab99af3cea26654ac93ed6ab5cb39fe.exe

**Comment by huffman** [comment]
@Qliemillar It's rebuilding now. There was a build warning before.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9415/app_13018_PR_b29984ab2c8f7efec889c001db5efe58bfeed161.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9415/HighFidelity-Beta-PR13018-b29984ab2c8f7efec889c001db5efe58bfeed161.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9415/HighFidelity-Beta-Interface-PR13018-b29984ab2c8f7efec889c001db5efe58bfeed161.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9415/HighFidelity-Beta-PR13018-b29984ab2c8f7efec889c001db5efe58bfeed161.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9415/HighFidelity-Beta-Interface-PR13018-b29984ab2c8f7efec889c001db5efe58bfeed161.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Files were deleted.

**Pull request merged**
