### PR TITLE
Output Buffer Size  - Default Audio Reliability Improvement

### PR DESCRIPTION
**Pull request by kevinmthomas-carpool**
Change the default value of output buffer size frames to 20 (instead of 1 default) and add functionality to increase maximum buffer to 40.  This dramatically increases the audio performance at a small cost of latency.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
Ok to test

**Comment by ZappoMan** [comment]
I think this will introduce increased latency. We will need to test to make sure that with this change we still get the latency we want.

**Comment by PhilipRosedale** [comment]
Yes Kevin we need a test of how many milliseconds this adds.  Also what is the problem you are seeing?  Skipping and drops?  Possibly we need to do a better job dynamically adjusting buffer depth when we see drops happening.

**Comment by kevinmthomas-carpool** [comment]
One of the problems facing brand-new users is the fact they tend to experience "choppy" sound quality.  This default, which can be dialed back, allows a new default value of 20 to which can be increased to 40 or reduced back to 1.

**Comment by PhilipRosedale** [comment]
any update?  gotta check latency and not increase default case (unless we determine that a fast machine connecting to a typical server is experiencing stuttering).

**Pull request closed without merging**
