### PR TITLE
Possible fix for yet another blendshape crash

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/19508/Crash-in-ModelBlender-setBlendedVertices

Test plan:
- Go to a domain with someone else running this PR.  Both of you run facialExpressions.js.  Press the keys (h j k l v b n m) to modify your blendshapes.  The other person should see your face changing.
- While playing with your blendshapes, quit Interface.  The other person shouldn't crash.  Try multiple times.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14368/HighFidelity-Beta-PR14269-a3c4236.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14368/HighFidelity-Beta-PR14269-a3c4236.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14368/HighFidelity-Beta-Interface-PR14269-a3c4236.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14368/HighFidelity-Beta-PR14269-a3c4236.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14368/HighFidelity-Beta-Interface-PR14269-a3c4236.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
No crash seen with blendshapes.

**Pull request merged**
