### PR TITLE
Fix Asset Browser's "Copy URL" context menu

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
*Test Plan*

In desktop mode:
- Open the Asset Browser (Edit > Asset Browser).
- Right-click on an item (e.g., "portal.js") and select the "Copy URL" context menu item.
- Paste the current clipboard contents into at text document.
- The clipboard contents should be the ATP URL for the item you selected "Copy URL" on (e.g., "atp:/portal.js").

Test this for a few assets.

Check that the rest of the Asset Browser dialog still works OK.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4692/HighFidelity-Beta-PR11754-9db0dd6fea01773b03f83fc65c6766b8da9952e2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4692/HighFidelity-Beta-PR11754-9db0dd6fea01773b03f83fc65c6766b8da9952e2.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open the Asset Browser (Edit > Asset Browser). | Pass
Right-click on an item (e.g., "portal.js") and select the "Copy URL" context menu item. | Pass
Paste the current clipboard contents into at text document. | Pass
The clipboard contents should be the ATP URL for the item you selected "Copy URL" on (e.g., "atp:/portal.js"). | Pass

```
atp:/portal.js
atp:/ACAudioSearchAndInject_tutorial.js
atp:/1592e15e-c822-41aa-b314-4ef261e5d843-v1/builder-grid.fbx
```

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by Nex-Pro** [comment]
@ctrlaltdavid Thanks for fixing this one it has been hanging around a long time. Now I don't have to use rename to grab part of the atp url.

**Pull request merged**
