### PR TITLE
use fromUserInput to avoid web entity crashes with bad URLs

### PR DESCRIPTION
**Pull request by birarda**
- parse new URLs for web entities with QUrl::fromUserInput to avoid using bad URLs that can crash interface

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

On master: 
(1) create a web entity with "google.com" (no HTTP) as the URL - this should crash your interface. 
(2) create a web entity with "http://192.168.0.100:\\" as the URL - this should crash your interface.

Try (1) and (2) with this PR. In both cases you should end up with valid URLs. The first should render google.com and the second is likely to not be a reachable page.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 99e0c8c0e744e76571994728ace9f16556b7d342 available at: https://gist.github.com/8f79097667099e82c4310dac22cbe2e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-99e0c8c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-99e0c8c.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: d7651e98381ca7b3a2288cc3629745d7e2e4c905 available at: https://gist.github.com/8f79097667099e82c4310dac22cbe2e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-d7651e9.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-d7651e9.dmg

**Comment by RyanDowne** [comment]
On master:
(1) create a web entity with "google.com" (no HTTP) as the URL - this should crash your interface. 
This crashed my client on Master
(2) create a web entity with "http://192.168.0.100:\\" as the URL - this should crash your interface.
This did not crash my client on master

Try (1) and (2) with this PR. In both cases you should end up with valid URLs. The first should render google.com and the second is likely to not be a reachable page.

Neither of these crashed my client in the PR build.

QA pass.

**Comment by nbq** [comment]
Testing this one when compiled

**Comment by hifi-gustavo** [comment]
Build console output for commit: f02832ca71ba4b8a5a88fbdc8412f9a1bf253b8f available at: https://gist.github.com/8f79097667099e82c4310dac22cbe2e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-f02832c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-f02832c.dmg

**Comment by RyanDowne** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: f02832ca71ba4b8a5a88fbdc8412f9a1bf253b8f available at: https://gist.github.com/8f79097667099e82c4310dac22cbe2e2<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-f02832c.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9474-f02832c.dmg

**Pull request merged**
