### PR TITLE
Remove unused uniform buffer from polylines

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/17507/Remove-unused-PolyLine-uniform-buffer

Test plan:
- Download the fingerpaint app from the market.
- Use it to draw polylines.  They should render correctly.  Check various color/texture options.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11986/HighFidelity-Beta-PR13795-bd4a3a5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11986/HighFidelity-Beta-PR13795-bd4a3a5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11986/HighFidelity-Beta-Interface-PR13795-bd4a3a5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11986/HighFidelity-Beta-PR13795-bd4a3a5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11986/HighFidelity-Beta-Interface-PR13795-bd4a3a5.exe

**Comment by qlimguicheteau** [comment]
Now Testing

**Comment by qlimguicheteau** [comment]
PASS @conklin94122 
Manuscript ticket requested and being created.

Ran the Fingerpaint App from the market, and all seemed to be in good order.
Tried various colors first, then the hues, then the textures, and a few of the dynamic paint options together. Also tested the color picker with the sliders and the textures.

**Pull request merged**
