### PR TITLE
7926 Create Mode: the keyboard tray is not styled correctly

### PR DESCRIPTION
**Pull request by ElderOrb**
**Test plan**

0. Switch to VR. 
1. Open tablet, go to the 'create'
2. Select any text field with as stylus to make keyboard appear
3. Ensure keyboard is styled correctly (see sample of incorrect styling below)

image

4. Go to the 'market' 
5. Select the search input field with a stylus to make keyboard appear
6. Ensure keyboard is styled correctly 
7. Type in "robot" and hit enter. Make sure it goes to the next screen correctly and the input field gets cleared.

### CODE REVIEW

**Comment by cain-kilgore** [comment]
Testing once built.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3679/HighFidelity-Beta-PR11473-3677718e48ca2e50b4bee8401e0514766257cb24.exe

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Switch to VR. | Pass
Open tablet, go to the 'create' | Pass
Select any text field with as stylus to make keyboard appear | Pass
Ensure keyboard is styled correctly (see sample of incorrect styling below) | Pass
Go to the 'market' | Pass
Select the search input field with a stylus to make keyboard appear | Pass
Ensure keyboard is styled correctly | Pass
Type in "robot" and hit enter. Make sure it goes to the next screen correctly and the input field gets cleared. | Pass

## Images
Image | Image
--- | ---
ab12613c-77a4-47a6-8bdd-8af207fe43c1 | 6982f0a7-9a3b-41d7-9dec-2a497d76293a

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Comment by anshuman64** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3691/HighFidelity-Beta-PR11473-3677718e48ca2e50b4bee8401e0514766257cb24.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3691/HighFidelity-Beta-PR11473-3677718e48ca2e50b4bee8401e0514766257cb24.exe

**Pull request merged**
