### PR TITLE
2017-10-13 Commerce frontend tweaks

### PR DESCRIPTION
**Pull request by zfox23**
Here are five small fixes/tweaks to Commerce code.

# Test Plan

## Prerequisites

Currently, you must manually enable "commerce" by adding `"commerce": true,` in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating `Settings.setValue("commerce", true)` and restarting.

If your wallet is already set up OR if you have previously set up a wallet on a different build (and thus you have a record of your wallet on the backend), you must perform the following steps to rest your wallet:
1. Open the Wallet app. If you're just resetting your wallet because there's a record of a previous wallet on the backend, go through setup.
2. Go to the "Help" tab in the Wallet app
3. Press the red "DBG: RST Wallet" button at the top of the window

If your wallet is set up but broken (e.g., from testing something that didn't work) such that you are prompted for a passphrase that is never accepted, you need to:
1. Quit interface and delete `%appdata%/Interface <build #>/<username.hifikey>`
2. Restart Interface, set up wallet, and then press the red `DBG: RST WALLET` button as above. Now you are in a truly clean state for wallet setup.

## Backup Instructions Test
1. Open the Wallet app
2. Go through setup. On the "Back Up Your Private Keys" page, make sure that clicking the "OPEN BACKUP INSTRUCTIONS FOR LATER" button opens up:
    1. Your default browser to an `.html` page explaining backup instructions AND
    2. Your file browser to the folder containing your `.hifikey` file.
3. Finish setup. Close Interface.
4. In your file explorer, navigate to `%appdata%/Interface <build #>/` and **delete** `backup_instructions.html`
5. Start Interface. Open the Wallet app
6. Authenticate using your passphrase
7. Go to the "Security" tab of the wallet
8. Click the "VIEW BACKUP INSTRUCTIONS" button.
9. Verify that the following opens up:
    1. Your default browser to an `.html` page explaining backup instructions AND
    2. Your file browser to the folder containing your `.hifikey` file.

## Marketplace Injection - Long Username Test
1. Log In to Interface with an account whose username is >= 14 characters in length
2. Open the Market app
3. Verify that your username at the top right of the page is elided and that the "My Purchases" link is on the same line as the dropdown containing your username

## Entity Certificate - Long Username Test
1. Purchase the "Test Beach Ball" from the Marketplace
2. Rez the Test Beach Ball
3. Right click the Test Beach Ball, then click on the (i)
4. Verify that the "Owner" field of the certificate displays: `<Your Long Username> (Private)`

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4143/HighFidelity-Beta-PR11594-5be9f2022e60864b4c161d9922a1f93468f6231c.dmg

**Comment by zfox23** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4146/HighFidelity-Beta-PR11594-5be9f2022e60864b4c161d9922a1f93468f6231c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4146/HighFidelity-Beta-PR11594-5be9f2022e60864b4c161d9922a1f93468f6231c.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
## PASS

All good.

Test Plan

Prerequisites

Currently, you must manually enable "commerce" by adding 
"commerce": true, 
in your Interface.json (with Interface not running), or by opening Interface Javascript console and evaluating 

Settings.setValue("commerce", true) 

and restarting.


If your wallet is already set up OR if you have previously set up a wallet on a different build 
(and thus you have a record of your wallet on the backend), 
you must perform the following steps to rest your wallet:

Open the Wallet app. 
If you're just resetting your wallet because there's a record of a previous wallet on the backend, go through setup.

Go to the "Help" tab in the Wallet app

Press the red "DBG: RST Wallet" button at the top of the window
If your wallet is set up but broken (e.g., from testing something that didn't work) such that you are prompted for a passphrase that is never accepted, you need to:

Quit interface and delete %appdata%/Interface <build #>/<username.hifikey>

Restart Interface, set up wallet, and then press the red DBG: RST WALLET button as above.

Now you are in a truly clean state for wallet setup.

Backup Instructions Test

### Open the Wallet app

Go through setup.

On the "Back Up Your Private Keys" page, 
make sure that clicking the "OPEN BACKUP INSTRUCTIONS FOR LATER" button opens up: **SUCCESS**
Your default browser to an .html page explaining backup instructions AND **SUCCESS**
Your file browser to the folder containing your .hifikey file. **SUCCESS**

Finish setup. Close Interface. **DONE**

In your file explorer, navigate to %appdata%/Interface <build #>/ and delete backup_instructions.html

Start Interface. Open the Wallet app

Authenticate using your passphrase

Go to the "Security" tab of the wallet

Click the "VIEW BACKUP INSTRUCTIONS" button. **DONE**

Verify that the following opens up:
Your default browser to an .html page explaining backup instructions AND
Your file browser to the folder containing your .hifikey file. **SUCCESS**


### Marketplace Injection - Long Username Test

Log In to Interface with an account whose username is >= 14 characters in length
Open the Market app

Verify that your username at the top right of the page is elided and that the "My Purchases" link is on the same line as the dropdown containing your username **SUCCESS**

d47656-hifi-snap-by-piper-peppercorn-on-2017-10-14_03-05-01

## Entity Certificate - Long Username Test

Purchase the "Test Beach Ball" from the Marketplace

Rez the Test Beach Ball

Right click the Test Beach Ball, then click on the (i)

Verify that the "Owner" field of the certificate displays: <Your Long Username> (Private) **SUCCESS**

i47656-hifi-snap-by-piper-peppercorn-on-2017-10-14_03-03-10

**Pull request merged**
