### PR TITLE
Improved Haze UI in Create menu

### PR DESCRIPTION
**Pull request by NissimHadar**
Replaces the UI for Haze.
Current UI:
image

New UI:
image

The changes are to two checkboxes and the Background Blend field.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4709/HighFidelity-Beta-PR11758-650df247611fe83ab1b6c4e2035f42d410ce4e02.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4709/HighFidelity-Beta-PR11758-650df247611fe83ab1b6c4e2035f42d410ce4e02.exe

**Comment by Nex-Pro** [comment]
@NissimHadar This is tidier. However should these sections be separate and collapsible.

**Comment by NissimHadar** [comment]
The current collapsible sections are:  Zone/Physical/Spatial/Behaviour.
The Haze is part of the Zone, together with Keylight and Ambient light.
The whole Zone is going to be changed:  there will be "inherit" options for
the keylight and ambient light and I think the Stage will be removed.
I don't think it would be right to separate the Haze from the rest of the
Zone at this stage.

**Comment by samcake** [comment]
@nissim,2 comments:
Can you replace the Blend controller by a slider?
Can we make sure that the color picker shows the correct values when initiating the picker with the actual value?

**Comment by NissimHadar** [comment]
I will see if a slider is an option.
I am not clear about your second remark.  Have you seen a problem?

**Comment by samcake** [comment]
When you pick the color picker, the current value you start with doesn;t always match the actual values for the color (the color you started with when clicking on the color picker widget)

**Comment by NissimHadar** [comment]
Understood - I will check.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4792/HighFidelity-Beta-PR11758-7cb9514feb96eb5440f42001009f17a040cd58f3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4792/HighFidelity-Beta-PR11758-7cb9514feb96eb5440f42001009f17a040cd58f3.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

New UI appears as expected and works as I'd expect (Had a quick fiddle with the settings and their purposes)

**Pass**

image

**Comment by Nex-Pro** [comment]
Ouch. Those sliders took a large dose of ugly pills.

**Comment by Nex-Pro** [comment]
Do the sliders allow exact settings ?

**Comment by Nex-Pro** [comment]
Font or weight for HAZE label is incorrect.

**Comment by themelissabrown** [comment]
@NissimHadar this needs to follow our design requirements found in the style guide: https://docs.highfidelity.com/write-for-us/style-guide

**Comment by conklin94122** [comment]
https://highfidelity.fogbugz.com/f/cases/9321/Change-UI-for-Haze-from-an-input-field-to-a-slider

**Pull request merged**
