### PR TITLE
Fullscreen webview

### PR DESCRIPTION
**Pull request by LeonCrew**
Full screen take over of any web entity clicked

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
ok to test

**Comment by sethalves** [comment]
This PR appears to redo most of the whitespace in the file.  Would it be possible to get a new PR without the whitespace changes?

**Comment by sethalves** [comment]
this still doesn't look right, to me.  compare:

https://github.com/highfidelity/hifi/pull/10391/files

vs

https://github.com/highfidelity/hifi/pull/10391/files?w=1

the second one instructs github to ignore whitespace differences.

**Comment by LeonCrew** [comment]
Whitespaces and tabs updated

**Comment by hifi-gustavo** [comment]
Build console output for commit: bbbd491036afc9d33a6ebaad0c6e673fd2f6202c available at: https://gist.github.com/b6f8149d055c568aa1cf9887a2aaebbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-bbbd491.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-bbbd491.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1dab4b2a2f0180394adefb287039a3600b273a44 available at: https://gist.github.com/b6f8149d055c568aa1cf9887a2aaebbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-1dab4b2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-1dab4b2.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 61ecff4d52a0248c4e4df92130bedeed150dac98 available at: https://gist.github.com/b6f8149d055c568aa1cf9887a2aaebbf<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-61ecff4.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10391-61ecff4.dmg

**Pull request closed without merging**
