### PR TITLE
Add AnimationCache to agent scripts

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: d84e2fb048d9029cbb56291e19160173121941c9 available at: https://gist.github.com/6e540e354f47bdc1a27c22438b6a1914<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-d84e2fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-d84e2fb.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: d84e2fb048d9029cbb56291e19160173121941c9 available at: https://gist.github.com/6e540e354f47bdc1a27c22438b6a1914<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-d84e2fb.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-d84e2fb.dmg

**Comment by huffman** [comment]
This PR exposes `AnimationCache` to agent scripts. To test:

 1. Run the agent script `https://gist.githubusercontent.com/huffman/85dd64e7855ba80d42a7292e0be268a0/raw/6fac6915ce2fc5b45d02f1322f4a245fbded646b/animationCacheTest.js` on your domain
 1. You should see the being of light avatar at 0,0,0
 1. In the server logs you should find:
    1. `LOADING ANIMATIONS` (this means the avatar animations are being preloaded)
    1. Something like `[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of idle:  301
[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of walk:  36`
 1. You should see the avatar switch between the walking and idle animations every 10 seconds.

**Comment by Nex-Pro** [comment]
Eagerly looking at this.

**Comment by Nex-Pro** [comment]
## FAIL

Messages succeeded animations did not show. 

Run the agent script 

https://gist.githubusercontent.com/huffman/85dd64e7855ba80d42a7292e0be268a0/raw/6fac6915ce2fc5b45d02f1322f4a245fbded646b/animationCacheTest.js **: DONE**

on your domain


You should see the being of light avatar at 0,0,0 **: SUCCESS**

In the server logs you should find:

LOADING ANIMATIONS (this means the avatar animations are being preloaded)

Something like 

[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of idle: 301 **: SUCCESS**

[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of walk: 36 **: SUCCESS**

You should see the avatar switch between the walking and idle animations every 10 seconds. **: FAIL**

**Comment by huffman** [comment]
@Nex-Pro thanks for testing - was the avatar in a t pose the entire time?

**Comment by hifi-gustavo** [comment]
Build console output for commit: aa8d231e82757a762596215eaffabedcded85aec available at: https://gist.github.com/6e540e354f47bdc1a27c22438b6a1914<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-aa8d231.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10021-aa8d231.dmg

**Comment by huffman** [comment]
@Nex-Pro Can you re-test? I changed the url to `https://gist.githubusercontent.com/huffman/85dd64e7855ba80d42a7292e0be268a0/raw/75806fa6b0cb81379fd2b4e7e731ab2fc03fabe7/animationCacheTest.js`

**Comment by Nex-Pro** [comment]
Retesting this now.

**Comment by Nex-Pro** [comment]
#10021

Testing platform: Intel workstation.
OS: Win10 pro 64
CPU: i7 4.0 ghz
RAM: 16gb
GPU: Nvidia GTX1070 8gb VRam
HMD: Htc Vive.
Controllers: Htc Vive.
Leap motion: Not used.

## PASS

You should see the being of light avatar at 0,0,0 : SUCCESS

In the server logs you should find:

LOADING ANIMATIONS (this means the avatar animations are being preloaded)

Something like

[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of idle: 301 : **SUCCESS**

[03/27 15:41:35] [DEBUG] [hifi.scriptengine.script] [73884] [agent] script:print()<< Length of walk: 36 : **SUCCESS**

### LOG OUTPUT from this build.

**[03/30 12:01:26] [DEBUG] [hifi.scriptengine.script] [8864] [agent] script:print()<< {"entities":187,"sounds":8,"playing":7,"getEntityPropertiesPerUpdate":6.88,"millisecondsPerUpdate":101}
[03/30 12:01:28] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of idle: 301
[03/30 12:01:28] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of walk: 36
[03/30 12:01:33] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Switching to: http://howard-stearns.github.io/models/resources/avatar/animations/walk_fwd.fbx
[03/30 12:01:33] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of idle: 301
[03/30 12:01:33] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of walk: 36
[03/30 12:01:36] [DEBUG] [hifi.scriptengine.script] [8864] [agent] script:print()<< {"entities":187,"sounds":8,"playing":7,"getEntityPropertiesPerUpdate":6.88,"millisecondsPerUpdate":101}
[03/30 12:01:38] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of idle: 301
[03/30 12:01:38] [DEBUG] [hifi.scriptengine.script] [17580] [agent] script:print()<< Length of walk: 36
[03/30 12:01:40] [DEBUG] [hifi.octree] [13828] [entity-server] pruning Octree before saving...**


You should see the avatar switch between the walking and idle animations every 10 seconds. : **SUCCESS**


## QA Test

**QA Tester**: Piper.Peppercorn
**localhost 'createTestBlocks.js' Result**: SUCCESS
**localhost ATP Upload + Edit Result**: SUCCESS
**Echo Server Audio**: SUCCESS
**localhost 'harmonicOscillator.js' Result**: SUCCESS
**localhost 'reverbTest.js' Result**: SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** : SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** : SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **N/A**
**QA Pass**: **QA Pass** SUCCESS

**Additional Test Results + Observations**:


HMD stats:

**Domain** |localhost |dev-playa |
---|---|---|---
**Render Rate**: |90 |90 |
**Present Rate**: |89 |99 |
**Present New Rate**: |89 |74 |
**CPU Buffer Count**: |2106 |1932 |
**GPU Buffer Count**: |702 |487 |
**CPU Memory Usage**: |21407888 |34530992 |
**GPU Memory Usage**: |12760496 |9422256 |
**CPU Texture Count**: |223 |184 |
**GPU Texture Count**: |160 |93 |
**GPU Transfer Count**: |0 |0 |
**CPU Texture Memory Usage**: |0 |0 |
**GPU Texture Memory Usage**: |589643797 |300109673 |
**GPU Virtual Memory Usage**: |0|0|
**Triangle Count**: |84258 |374954 |
**Triangle Rate**: |7659818 |28842615 |
**API Drawcall Count**: |34 |122 |
**Drawcall Count**: |56 |236 |
**Drawcall Rate**: |5090 |18153 |
**State Changes Texture Count**:|63 |142 |
**Pipeline Count**: |27 |27 |
**Item Opaques**: |22 |188 |
**Item Translucents**: |12 |7 |
**Item Lights**: |2 |34 |
**Timing Opaques**: |0.127 |0.671 |
**Timing Translucents**: |0.04 |0.016 |
**Timing Lighting**: |0.024 |0.018 |
**Render Frame**: |0.936 |1.88 |

Dev demo is unavailable for testing. 

@huffman

**Pull request merged**
