### PR TITLE
Prevent race on internal client traits members

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13831/HighFidelity-Beta-PR14192-1bcbda7.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13831/HighFidelity-Beta-PR14192-1bcbda7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13831/HighFidelity-Beta-Interface-PR14192-1bcbda7.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13831/HighFidelity-Beta-PR14192-1bcbda7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13831/HighFidelity-Beta-Interface-PR14192-1bcbda7.exe

**Comment by birarda** [comment]
I wonder if we couldn't have kept calls to ClientTraitsHandler from a single thread - that was my assumption about the state were were in (which is why we didn't have the locks) but clearly I missed at least one.

Bit of a bummer to add these if it's only one case that is otherwise avoidable.

Otherwise looks good though.

**Comment by conklin94122** [comment]
QA Ready? @Atlante45

**Comment by Atlante45** [comment]
@conklin94122 I just need to write a test plan.

**Comment by qligmaloney** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14307/HighFidelity-Beta-PR14192-1bcbda7.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14307/HighFidelity-Beta-PR14192-1bcbda7.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14307/HighFidelity-Beta-Interface-PR14192-1bcbda7.exe

**Comment by qlipdahlin** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14307/HighFidelity-Beta-PR14192-1bcbda7.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14307/HighFidelity-Beta-Interface-PR14192-1bcbda7.dmg

**Comment by qlipdahlin** [comment]
@conklin94122 PASS

Antonina assisted with running the two test cases (C17718, C17719). Changed avatars rapidly and changed domains repeatably. No issues. PR Passes.

**Pull request merged**
