### PR TITLE
fix several warnings

### PR DESCRIPTION
**Pull request by ZappoMan**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7669f9ed2c82d26b7231de7b861099fa22a8212d available at: https://gist.github.com/48e5910940be2677d183<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0068af4cb6f10849ad5d6d3286d90b602d308321 available at: https://gist.github.com/48e5910940be2677d183<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9acff9497ca3c9e0ad2311590a097736ef59e70f available at: https://gist.github.com/48e5910940be2677d183<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9acff9497ca3c9e0ad2311590a097736ef59e70f available at: https://gist.github.com/48e5910940be2677d183<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6117.dmg

**Pull request merged**
