### PR TITLE
Case 19930: Entity List - add select/clear all to entity type dropdown

### PR DESCRIPTION
**Pull request by dback2**
https://highfidelity.manuscript.com/f/cases/19930/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17282/HighFidelity-Beta-PR14919-113e56c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17282/HighFidelity-Beta-PR14919-113e56c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17282/HighFidelity-Beta-Interface-PR14919-113e56c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17282/HighFidelity-Beta-PR14919-113e56c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17282/HighFidelity-Beta-Interface-PR14919-113e56c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17305/HighFidelity-Beta-PR14919-e944e28.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17305/HighFidelity-Beta-PR14919-e944e28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17305/HighFidelity-Beta-Interface-PR14919-e944e28.dmg

**Comment by huffman** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/17312/HighFidelity-Beta-PR14919-e944e28.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17312/HighFidelity-Beta-PR14919-e944e28.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/17312/HighFidelity-Beta-Interface-PR14919-e944e28.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17312/HighFidelity-Beta-PR14919-e944e28.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/17312/HighFidelity-Beta-Interface-PR14919-e944e28.exe

**Pull request merged**
