### PR TITLE
allow near grabbing of entities while stylus module is running.

### PR DESCRIPTION
**Pull request by druiz17**
allow near grabbing of entities while stylus module is running.

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- https://highfidelity.testrail.net/index.php?/cases/view/37&group_by=cases:section_id&group_order=asc&group_id=13

- run is test when your stylus is showing and your are trying to grab an object.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5045/HighFidelity-Beta-PR11844-4bbf2ff482d7255e4dddb8675762845eec77b261.dmg

**Comment by YuppyPlays** [comment]
Awaiting build for QA.

**Comment by YuppyPlays** [comment]
@druiz17 It appears Gustavo is not being cooperative today, may want to give him a kick to build :P

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5051/HighFidelity-Beta-PR11844-4bbf2ff482d7255e4dddb8675762845eec77b261.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5051/HighFidelity-Beta-PR11844-4bbf2ff482d7255e4dddb8675762845eec77b261.exe

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Tested w/ Cain as observer.

Special note from dev for reference:
run is test when your stylus is showing and your are trying to grab an object.

Solid **Pass**

TestRail Results: https://highfidelity.testrail.net/index.php?/tests/view/14522&group_by=cases:section_id&group_order=asc&group_id=13

**Pull request merged**
