### PR TITLE
Get the correct device name connect to OpenVr

### PR DESCRIPTION
**Pull request by druiz17**
Add microsoft data to logging.

https://highfidelity.manuscript.com/f/cases/12214/Add-new-hardware-HMDs-and-input-devices-to-our-data

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8820/app_12903_PR_5af1ea54d370471bad777b6815e27ab12778dc36.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8820/HighFidelity-Beta-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8820/HighFidelity-Beta-Interface-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8820/HighFidelity-Beta-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.exe

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8822/app_12903_PR_5af1ea54d370471bad777b6815e27ab12778dc36.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8822/HighFidelity-Beta-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8822/HighFidelity-Beta-Interface-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8822/HighFidelity-Beta-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8822/HighFidelity-Beta-Interface-PR12903-5af1ea54d370471bad777b6815e27ab12778dc36.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8835/app_12903_PR_aa985fa6826d6518c4390484d702d760fa310445.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8835/HighFidelity-Beta-PR12903-aa985fa6826d6518c4390484d702d760fa310445.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8835/HighFidelity-Beta-Interface-PR12903-aa985fa6826d6518c4390484d702d760fa310445.dmg

**Comment by druiz17** [comment]
Test plan

1. 
- Use a Microsoft Mix Reality Headset using steamvr.
- check that when you click on the display menu option, `WindowsMS` is displayed as one of the display options

2.
- Using a HTC Vive headset
 check that when you click on the display menu option, `HTC Vive` is displayed as one of the display options

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8835/HighFidelity-Beta-PR12903-aa985fa6826d6518c4390484d702d760fa310445.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8835/HighFidelity-Beta-Interface-PR12903-aa985fa6826d6518c4390484d702d760fa310445.exe

**Comment by druiz17** [comment]
Test plan
- using a Microsoft headset and openvr
- check that you see WindowsMS as a display option
- check that WindowsMS headset data is being sent in the userActivityData

**Comment by conklin94122** [comment]
@L370 Please test this PR.

**Pull request merged**
