### PR TITLE
Electron debug mv

### PR DESCRIPTION
**Pull request by MiladNazeri**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by MiladNazeri** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22153/HighFidelity-Beta-PR16412-6c8d13c.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22153/HighFidelity-Quest-Beta-PR16412-6c8d13c.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22154/HighFidelity-Beta-PR16412-683ddd0.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22154/HighFidelity-Quest-Beta-PR16412-683ddd0.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22155/HighFidelity-Beta-PR16412-1900496.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22155/HighFidelity-Quest-Beta-PR16412-1900496.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22157/HighFidelity-Beta-PR16412-ce62490.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22157/HighFidelity-Quest-Beta-PR16412-ce62490.apk)

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22159/HighFidelity-Beta-PR16412-12b47cd.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/22159/HighFidelity-Quest-Beta-PR16412-12b47cd.apk)

**Pull request closed without merging**
