### PR TITLE
clean up tablet material entities  and don't display them in create menu

### PR DESCRIPTION
**Pull request by danteruiz**
Since the tablet now uses material entities for highlighting, There are some issues of the material entities persisting after crashes and also being able to see your own tablet material entities in the create app. This PR addresses these two issues.

tickets - https://highfidelity.manuscript.com/f/cases/16517/Material-entities-from-tablet-get-stuck-at-origin

https://highfidelity.manuscript.com/f/cases/16510/VR-users-get-invisible-materialData-objects-attached-to-the-tablet

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/13570

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11227/HighFidelity-Beta-PR13576-e34c440.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11227/HighFidelity-Beta-PR13576-e34c440.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11227/HighFidelity-Beta-Interface-PR13576-e34c440.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11227/HighFidelity-Beta-PR13576-e34c440.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11227/HighFidelity-Beta-Interface-PR13576-e34c440.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Script never indicated more than 2 material entities, and these entities were not listed in Create.

**Pull request closed without merging**
