### PR TITLE
Case 20200: Update EntityScriptingInterface to not find local entities

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/20200/Update-EntityScriptingInterface-to-support-local-entities

Test plan:
- run all the engine/interaction tests from hifi_tests
- Run [this](https://gist.githubusercontent.com/SamGondelman/33da7f2cb8d798f934aa6c11ee68bd64/raw/68cdfb200c626495cfdb17c22d2b6f275be67cdf/FindEntitiesTest.js).  You'll see this:
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15784/HighFidelity-Beta-PR14547-98ceb6a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15812/HighFidelity-Beta-PR14547-9908ce2.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15815/HighFidelity-Beta-PR14547-6aac596.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15815/HighFidelity-Beta-PR14547-6aac596.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15815/HighFidelity-Beta-Interface-PR14547-6aac596.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15815/HighFidelity-Beta-PR14547-6aac596.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15815/HighFidelity-Beta-Interface-PR14547-6aac596.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15821/HighFidelity-Beta-PR14547-f13457f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15821/HighFidelity-Beta-PR14547-f13457f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15821/HighFidelity-Beta-Interface-PR14547-f13457f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15824/HighFidelity-Beta-PR14547-7054188.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15824/HighFidelity-Beta-PR14547-7054188.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15824/HighFidelity-Beta-Interface-PR14547-7054188.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15824/HighFidelity-Beta-PR14547-7054188.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15824/HighFidelity-Beta-Interface-PR14547-7054188.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15846/HighFidelity-Beta-PR14547-5eccaad.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15846/HighFidelity-Beta-PR14547-5eccaad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15846/HighFidelity-Beta-Interface-PR14547-5eccaad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15846/HighFidelity-Beta-PR14547-5eccaad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15846/HighFidelity-Beta-Interface-PR14547-5eccaad.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16057/HighFidelity-Beta-PR14547-5eccaad.apk

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16057/HighFidelity-Beta-PR14547-5eccaad.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16057/HighFidelity-Beta-Interface-PR14547-5eccaad.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16057/HighFidelity-Beta-PR14547-5eccaad.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16057/HighFidelity-Beta-Interface-PR14547-5eccaad.exe

**Comment by qlimnavarro** [comment]
Pass
PreMerge testing complete

**Pull request merged**
