### PR TITLE
MS20921: Oculus login button not appearing (RC79)

### PR DESCRIPTION
**Pull request by wayne-chen**
MS#[20921](https://highfidelity.manuscript.com/f/cases/20921/Oculus-login-Oculus-login-button-no-longer-appears-when-launching-through-the-oculus-store)

# TEST PLAN
- Setup metaverse environment to staging
- Get this PR uploaded into Oculus store
- Launch PR through Oculus store
- Make sure Oculus login button appears
- Ensure Oculus login flow is successful 
- Test cases:
https://highfidelity.testrail.net/index.php?/cases/view/35637
https://highfidelity.testrail.net/index.php?/cases/view/40465

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16933/HighFidelity-Beta-Interface-PR14819-03789e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16933/HighFidelity-Beta-PR14819-03789e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16933/HighFidelity-Beta-Interface-PR14819-03789e0.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
