### PR TITLE
Add sound cues to create app

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/8355/Add-Sound-Cues-to-Create-Marketplace

Test steps:
- Open Tablet
- Open Create app
- Hover/Click on objects buttons. Make sure hover/click sound appears

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/4335/HighFidelity-Beta-PR11647-b791dcba7f492772842bf10b4ea88cca327a2660.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/4335/HighFidelity-Beta-PR11647-b791dcba7f492772842bf10b4ea88cca327a2660.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed
Test | Result
--- | ---
Open Tablet | Pass
Open Create app | Pass
Hover/Click on objects buttons. Make sure hover/click sound appears | Pass

All good from here.

###### Intel i5 7600K @ 4Ghz, 16GB DDR4 2133Mhz Corsair Vengeance, Asus Strix GTX 1050Ti 3GB, HTC Vive

**Pull request merged**
