### PR TITLE
use singleShot timers to avoid calls to checkPeakValues overlapping

### PR DESCRIPTION
**Pull request by sethalves**
- fix a crash in checkPeakValues

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- enable the audio-level meter
- make sure the audio-level meter works
- open the audio panel and make sure the level-meters work

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7748/app_12568_PR.apk

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/11310/crash-in-interface-AudioClient-checkPeakValues

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7749/app_12568_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7749/HighFidelity-Beta-PR12568-1a11c0194b24fa8c657b5d5bb4c9825f772f84a6.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7766/app_12568_PR.apk

**Comment by marko8904** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7773/app_12568_PR.apk

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7794/app_12568_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7794/HighFidelity-Beta-PR12568-1a11c0194b24fa8c657b5d5bb4c9825f772f84a6.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7794/HighFidelity-Beta-PR12568-1a11c0194b24fa8c657b5d5bb4c9825f772f84a6.exe

**Comment by sethalves** [comment]
closing in favour of https://github.com/highfidelity/hifi/pull/12586

**Pull request closed without merging**
