### PR TITLE
Fix up script editor's "reload scripts?" message box

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
- Icon should be a question mark.
- Title should be "Reload Script".
- Text should be...
 The following file has been modified outside of the Interface editor:
 [filename]
 Do you want to reload it?

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab963b4a4b5b9057626b120bd34d227d266ec37d available at: https://gist.github.com/8290bc26e967f8f5ecd9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7351.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7351.dmg

**Comment by OmegaHeron** [comment]
Testing Windows 7

What qualifies as a external change to file that would trigger notice?  I edited a file open in script editor from an external program, saved it and saw no indication in Interface.  I have option selected in script editor to auto reload externally changed files.

**Comment by OmegaHeron** [comment]
Also - if you have closed script editor window to find that hidden QML dialog for reloading, it seems to crash interface if you try to dismiss it.

**Comment by ctrlaltdavid** [comment]
There's already an Asana bug report about the "reload?" dialog appearing behind the script editor window. In fact, there are two open bug reports on this.
I've added a bug report on Interface crashing if you close the script editor window before the modal dialog.

**Comment by OmegaHeron** [comment]
Yes, I saw all, but it's often difficult to zero in on specific scope of these PRs - at its most narrow interpretation, this passes QA.

**Comment by Atlante45** [comment]
@ctrlaltdavid You need to update with master.

**Comment by ctrlaltdavid** [comment]
Note: After the merge with master each line of the message is centred in the dialog.

**Comment by hifi-gustavo** [comment]
Build console output for commit: bef8c5a807c9fe55fd75743dc43af3590ca92c29 available at: https://gist.github.com/8290bc26e967f8f5ecd9<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7351.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7351.dmg

**Pull request merged**
