### PR TITLE
Set ambient mode to inherit if no URLs have been entered.

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
This PR corrects the behaviour when no ambient URL AND no skybox URL have been defined.  In this case - the ambient mode should be set to Inherit, as this is the old behaviour.
# Testing
The first stage of testing requires the creation of content using the released version 7607.  The models.json.gz files should be stored in different folders, named 1, 2, 3 and so on.
After creating each domain - the file can be found in `~/High Fidelity/assignment-client/entities/`.
1.  Delete all content from the domain.  This may be done by  Market->Environments->Empty Domain Set.  This is domain #1.

2.  Add a sphere - leave all values as default.  This is domain #2.

3.  Add a default zone - leave all values as default.  This is domain #3

4.  Set the ambient URL to `http://hifi-content.s3.amazonaws.com/DomainContent/baked/island/Sky_Day-Sun-Mid-photo.ktx`.  This is domain #4.

5.  Set the Background Mode to Skybox.  This is domain #5

6.  Set the Skybox URL to `http://hifi-content.s3.amazonaws.com/DomainContent/baked/island/Sky_Day-Sun-Mid-photo.ktx`.  This is domain #6.

7.  Delete the Ambient URL - this is domain #7. (Same image as 6).
8.  Set the ambient URL to `http://hifi-content.s3.amazonaws.com/DomainContent/baked/hideout/SKY-Fullmoon-w-Sea.jpg`

9.  Delete the ambient URL and set the ambient intensity to 3.0.  This is zone #9.

10.  Delete the skybox URL.  This is zone #10.

To verify that the content can be read correctly, perform the following steps for each of the domains that have been created:

1.  Close Interface
2.  Stop the Server
3.  Copy the next models.json.gz to the `~/High Fidelity - PR12147/assignment-client/entities/` folder
4.  Start the Server
5.  Start Interface (i.e. Go Home)
6.  Verify the content looks like that described above.  Note that you may need to turn left/right until you see the sphere.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6310/app_12177_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6310/HighFidelity-Beta-PR12177-a1415e28ff97e3744e27bea1662022056304cf8e.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6316/app_12177_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6316/HighFidelity-Beta-PR12177-f2d272b6fe20d2d892a4dfe1508e1c969fe844f4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6316/HighFidelity-Beta-PR12177-f2d272b6fe20d2d892a4dfe1508e1c969fe844f4.dmg

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Fail. The first three zones loaded slowly, but did load. From the fourth zone on, the interface would freeze and crash every time. I've attached the logs and model files for reference.

[domain-server-8956-1516133900615-stdout.txt](https://github.com/highfidelity/hifi/files/1636687/domain-server-8956-1516133900615-stdout.txt)

[models.json.gz](https://github.com/highfidelity/hifi/files/1636691/models.json.gz)


@conklin94122

**Comment by sbennett77** [comment]
Retested with files supplied my Nissim, and was able to successfully load all domain files. Passed.

@conklin94122

**Pull request merged**
