### PR TITLE
fix code that was using old raypickInfo.properties field

### PR DESCRIPTION
**Pull request by sethalves**
- fix a crash in handControllerGrab.js

### CODE REVIEW

**Comment by sethalves** [comment]
to test:
- generally test near and far grabbing, esp with other people present and interacting with the same entities

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/177/HighFidelity-Beta-PR10550-de40604042c52902d8b03fe5e9d230458322d247.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/177/HighFidelity-Beta-PR10550-de40604042c52902d8b03fe5e9d230458322d247.dmg

**Comment by YuppyPlays** [comment]
Testing.

**Comment by YuppyPlays** [comment]
Testing complete:

Tested the near and far grab features in Welcome with 6 users in the local area, seemed to work as normal in all fields if not possibly more responsive? (Though this could just be servers performance dependant)

Pass?..

**Pull request merged**
