### PR TITLE
case 19991 - implement AppData for Mac

### PR DESCRIPTION
**Pull request by NissimHadar**
https://highfidelity.fogbugz.com/f/cases/19991/Implement-AppData-interface-for-nitpick-on-Mac

# Description
This is required to improve the robustness of testing on Mac.  An "empty" AppData folder is copied over the existing AppData folder (the original data is saved and restored after testing.
# Testing
1.  Install the latest Mac installer from https://hifi-qa.s3.amazonaws.com/nitpick/Mac/nitpick-installer-v1.1.dmg and run an automatic test.
2.  Install the latest Windows installer from https://hifi-qa.s3.amazonaws.com/nitpick/Windows/nitpick-installer-v1.1.exe

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15322/HighFidelity-Beta-PR14454-2b71a82.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15322/HighFidelity-Beta-PR14454-2b71a82.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15322/HighFidelity-Beta-Interface-PR14454-2b71a82.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15322/HighFidelity-Beta-PR14454-2b71a82.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15322/HighFidelity-Beta-Interface-PR14454-2b71a82.exe

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15357/HighFidelity-Beta-PR14454-f62fd97.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15357/HighFidelity-Beta-Interface-PR14454-f62fd97.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15362/HighFidelity-Beta-PR14454-e173b29.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15363/HighFidelity-Beta-PR14454-6313ab8.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15363/HighFidelity-Beta-Interface-PR14454-6313ab8.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15367/HighFidelity-Beta-PR14454-f4f1ac8.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15370/HighFidelity-Beta-PR14454-48fabf5.apk

**Comment by qaAdamSmith82** [comment]
Currently Testing

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15370/HighFidelity-Beta-PR14454-48fabf5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15370/HighFidelity-Beta-Interface-PR14454-48fabf5.exe

**Comment by qaAdamSmith82** [comment]
Testing Passed.  Waiting for update to documentation to reflect improvements before giving green.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15395/HighFidelity-Beta-PR14454-e943504.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15399/HighFidelity-Beta-PR14454-c211dc3.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15395/HighFidelity-Beta-PR14454-e943504.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15395/HighFidelity-Beta-Interface-PR14454-e943504.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15404/HighFidelity-Beta-PR14454-f995499.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15412/HighFidelity-Beta-PR14454-4700b94.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15412/HighFidelity-Beta-Interface-PR14454-4700b94.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15412/HighFidelity-Beta-PR14454-4700b94.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15412/HighFidelity-Beta-Interface-PR14454-4700b94.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15475/HighFidelity-Beta-PR14454-59a030a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15475/HighFidelity-Beta-PR14454-59a030a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15475/HighFidelity-Beta-Interface-PR14454-59a030a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15475/HighFidelity-Beta-PR14454-59a030a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15475/HighFidelity-Beta-Interface-PR14454-59a030a.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15550/HighFidelity-Beta-PR14454-8973b7c.apk

**Pull request merged**
