### PR TITLE
fix logic that resets own-avatar collisions after a parenting grab is released

### PR DESCRIPTION
**Pull request by sethalves**

### CODE REVIEW

**Comment by sethalves** [comment]
https://highfidelity.manuscript.com/f/cases/10733/Created-objects-stop-colliding-with-avatar-when-grabbed-in-HMD

**Comment by sethalves** [comment]
# test plan
## 1
- create two dynamic entities and parent one to the other. Have entities close to each other but not touching.
- near grab the entities with both hand.
- bring the entities into our avatar and your avatar should not go flying.
- While the entities are still intersecting your body....release one of your hands from the entities.....your body should not go flying.
- also equip an equip-able entity (ping pong gun is good), intersect the entity into your body and make sure you don't go flying
## 2
- run this script - https://gist.github.com/druiz17/135cf33ac0209a81fa90b5d13220c6c7
- grab the pair of entities the are brought up.
- after a second, the blue cube should be un-parented.
- walk in to the blue cube and it should bounce off your avatar.

- Here is the original test plan https://highfidelity.testrail.net/index.php?/tests/view/16090 that exposed the issue that this PR. Look at this or the ticket for more information if needed.
## 3
- with HMD on open CREATE and rez a cube.  Close CREATE and the tablet
- attempt to walk through the cube, notice that it stops you
- grab the cube, move it slightly, release it
- attempt to walk through the cube, confirm that it still stops you

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5716/app_12015_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5716/HighFidelity-Beta-PR12015-ca45c4e8dac8ad9c1162ab2d1f20095de7eccb74.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5716/HighFidelity-Beta-PR12015-ca45c4e8dac8ad9c1162ab2d1f20095de7eccb74.exe

**Comment by cain-kilgore** [comment]
Testing.

**Comment by cain-kilgore** [comment]
# Test Passed

### 1
Test | Result
--- | ---
create two dynamic entities and parent one to the other. Have entities close to each other but not touching. | 👍 
near grab the entities with both hand. | 👍 
bring the entities into our avatar and your avatar should not go flying. | 👍 
While the entities are still intersecting your body....release one of your hands from the entities.....your body should not go flying. | 👍 
also equip an equip-able entity (ping pong gun is good), intersect the entity into your body and make sure you don't go flying | 👍 

### 2
Test | Result
--- | ---
run this script - https://gist.github.com/druiz17/135cf33ac0209a81fa90b5d13220c6c7 | 👍 
grab the pair of entities the are brought up. | 👍 
after a second, the blue cube should be un-parented. | 👍 
walk in to the blue cube and it should bounce off your avatar. | 👍 

### 3
Test | Result
--- | ---
with HMD on, open CREATE and rez a cube. Close CREATE and the tablet | 👍 
attempt to walk through the cube, notice that it stops you | 👍 
grab the cube, move it slightly, release it | 👍 
attempt to walk through the cube, confirm that it still stops you | 👍 

Everything looks good to me! 🎉

**Pull request merged**
