### PR TITLE
DEV-648: Add flag for account settings feature

### PR DESCRIPTION
**Pull request by Atlante45**
https://highfidelity.atlassian.net/browse/DEV-648

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21506/HighFidelity-Beta-PR16243-96b5875.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21506/HighFidelity-Beta-Interface-PR16243-96b5875.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21506/HighFidelity-Beta-PR16243-96b5875.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21506/HighFidelity-Quest-Beta-PR16243-96b5875.apk)

**Comment by howard-stearns** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21520/HighFidelity-Beta-PR16243-96b5875.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21520/HighFidelity-Quest-Beta-PR16243-96b5875.apk)

**Comment by ZappoMan** [comment]
This build seemed to fail for some kind of a "build machine" problem (AFAICT)

On Mac, the error in in the JSDoc step of the build... (not changed by the developer)
```
09:46:29 /Users/jenkins/Jenkins/workspace/pr-build/label/macos/tools/jsdoc/node_modules/jsdoc/jsdoc.js:8
09:46:29     let env;
09:46:29     ^^^
09:46:29 
09:46:29 SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
09:46:29     at exports.runInThisContext (vm.js:53:16)
09:46:29     at Module._compile (module.js:404:25)
09:46:29     at Object.Module._extensions..js (module.js:432:10)
09:46:29     at Module.load (module.js:356:32)
09:46:29     at Function.Module._load (module.js:313:12)
09:46:29     at Function.Module.runMain (module.js:457:10)
09:46:29     at startup (node.js:138:18)
09:46:29     at node.js:974:3
09:46:29 make: *** [jsdoc_buildpart_0] Error 1
09:46:29 Command /bin/sh failed with exit code 2
09:46:29 
09:46:29 ** BUILD FAILED **
09:46:29 
09:46:29 
09:46:29 The following build commands failed:
09:46:29 	PhaseScriptExecution CMake\ PostBuild\ Rules build/tools/jsdoc/hifi.build/Release/jsdoc.build/Script-3B35A00433EA4A6D833F28E8.sh
09:46:29 (1 failure)
09:46:29 Build step 'Conditional step (single)' marked build as failure
09:46:29 Strings match run condition: string 1=[macos], string 2=[windows]
```

On windows, the error seems more obscure, I don't see any indication to what actually failed...  but interestingly at the bottom it does mention "splunk" which seems problematic?? 

**...test.log] to splunk in 49 events...**

```
build\label\windows\build\ext\vc14\wasapi\project\src\wasapi-stamp\wasapi-download-err.log, C:\jenkins\workspace\pr-build\label\windows\build\ext\vc14\wasapi\project\src\wasapi-stamp\wasapi-download-out.log, C:\jenkins\workspace\pr-build\label\windows\server-console\node_modules\spdx-exceptions\test.log] to splunk in 49 events
10:25:33 Finished: FAILURE
```

cc: @joy-highfidelity @MattHardcastle

**Pull request merged**
