### PR TITLE
Photobooth Improvements: Using Tablet & Ability to Rotate Model

### PR DESCRIPTION
**Pull request by fayeli**
This PR contains my work on getting the Photobooth to use the tablet API and adding support to rotate the model in photobooth:

- tablet button that toggles on/off for the photobooth
- using tablet event bridge
- slider bar UI that rotates model clockwise and anti-clockwise

Note: currenly there is a bug on tablet event handling which make slider bar UI works funny. It is however working great when you have tablet in toolbar mode so we recommend using that.

Test Plan:
1) Turn on toolbar tablet mode in desktop mode. (Settings > General... > Check Destop Tablet Becomes Toolbar
2) Run photoboothApp.js
3) Confirms there is now a Photobooth button on the tool bar, clicking that will bring up the UI screen and a photobooth set up will appear in world.
4) Try all functionalities and make sure it works ok.
5) Click the Photobooth button will remove all entities from Photobooth. Same happens when you end the script from Running Script.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 405be471c32e8dbd8448329af0fcb5b070514c5a available at: https://gist.github.com/8f5562e1a0c32d9fc0049080176b4822<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-405be47.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-405be47.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8cb771d9a8917d3dcc7f9f7a1d5ae7654cdae41f available at: https://gist.github.com/8f5562e1a0c32d9fc0049080176b4822<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-8cb771d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-8cb771d.dmg

**Comment by StarmanF** [comment]
testing

**Comment by StarmanF** [comment]
**Desktop PC - Windows 10 Education - CPU 4.0GHz Intel i7 - GTX1080 - RAM 16GB**

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-8cb771d.exe

Testing in a default sandbox.

Notes:

- Photobooth button appears on the toolbar, clicking it brings up the UI screen and a photobooth set up. Though if the user is standing on the floor of a default sandbox, as I was, the photobooth is partially submerged into the floor causing the models to only be visible from the main camera and only half of the backdrop to be visible. This can be avoided by flying when clicking the photobooth button.

- First Person, Main, Left and Right cameras all take take photos as expected, assuming the user was flying while enabling the photo booth.

- Loading a model from the asset store works too, with all the pictures being accurately taken with the new model (I tried this link leading to the flying robot avatar http://mpassets.highfidelity.com/1b7e1e7c-6c0b-4f20-9cd0-1d5ccedae620-v1/bb64e937acf86447f6829767e958073c.fst).

- If the link is then removed from the "Model URL" entry area and the refresh button is clicked then a wire frame cube is placed where a model would go.

- The "Rotate Model" slider works as expected, but when the model is reloaded the slider has to be moved around a bit for it to affect the new model. Though this doesn't seem like much of a problem, since the slider is still functional.

Fails:

- Clicking the photo booth button (to close the booth) removes all elements if the camera is set to First Person, otherwise it locks the user in a state where the camera can't be moved. This state can be escaped using the button if the photo booth is reactivated and closed again with a first person camera mode. Removing the script breaks the user out of the locked camera and removes everything effectively, no matter what the camera settings are.

An image of the locked state can be seen below, it looks quite a bit different than the default Sandbox for some reason.



- Otherwise the submerged effect for the photobooth elements when the user is standing on the ground causes smaller models to be invisible and the default model to be only half visible. It also makes the backdrop kind of useless since it's only visible behind at best, half of the default model. An image below shows what the submerging effect looks like from the right camera perspective.

**Comment by cozza13** [comment]
@fayeli see the comment on the part that made it fail

**Comment by fayeli** [comment]
Thanks for the thorough testing! I'm on to fixing them now.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ca4203d85c9eece148743b7bc83ea2a9b0aa607 available at: https://gist.github.com/8f5562e1a0c32d9fc0049080176b4822<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-2ca4203.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-2ca4203.dmg

**Comment by StarmanF** [comment]
testing

**Comment by StarmanF** [comment]
**Desktop PC - Windows 10 Education - CPU 4.0GHz Intel i7 - GTX1080 - RAM 16GB - Vive**

Tested: Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10002-2ca4203.exe

**Pass**

Notes:

- As before, the photobooth button appears on the toolbar and clicking it does bring up the same photobooth UI and set. It is no longer submerged, instead it's hovering in midair and is therefore functional.

- Once again I tested left, right, main and first person cameras which all behave as expected.

- The rotating slider is also still functional.

- I loaded the same model as in the previous test and a different too for some diversity. And they behaved as expected both in rendering and in the final photo. The models are again from the high fidelity avatars listing, linked below.

[same model from before, tested](http://mpassets.highfidelity.com/f14bf7c9-49a1-4249-988a-0a577ed78957-v1/beingOfLight.fst)
[new model, tested](http://mpassets.highfidelity.com/1b7e1e7c-6c0b-4f20-9cd0-1d5ccedae620-v1/bb64e937acf86447f6829767e958073c.fst)

- Clicked the photobooth button to close, all entities were removed and the camera was once again under the users control regardless of what camera mode was selected before closing the photobooth. The same happens when the script is ended from the Running Scripts dialog.

**Pull request merged**
