### PR TITLE
Settings API JSDoc

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
QA not required because no executable code changes.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/8325/app_12729_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/8325/HighFidelity-Beta-PR12729-c3df741c6218c5f7758174585e21fcbeebb037e2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/8325/HighFidelity-Beta-PR12729-c3df741c6218c5f7758174585e21fcbeebb037e2.exe

**Pull request merged**
