### PR TITLE
add socketActivated signal to NetworkPeer for punch success

### PR DESCRIPTION
**Pull request by birarda**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34b8fca83befa4c561dfbd40839f3915582a6b14 available at: https://gist.github.com/7c7ff00a280b20c84000<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.dmg

**Comment by ZappoMan** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 34b8fca83befa4c561dfbd40839f3915582a6b14 available at: https://gist.github.com/7c7ff00a280b20c84000<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 3906a747b8b5515935e3c5b87a05bdc1d9f7a6e1 available at: https://gist.github.com/7c7ff00a280b20c84000<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: f5ec458a5eb0cae74d78b78df5d5fca64a710149 available at: https://gist.github.com/7c7ff00a280b20c84000<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-6406.dmg

**Pull request merged**
