### PR TITLE
an objective test of basic performance on struggling machines

### PR DESCRIPTION
**Pull request by howard-stearns**
A script to characterise the performance of heavily loaded or struggling machines.

There is no point in running this on a machine that producing the target 60 or 90 hz rendering rate.

The script examines several source of load, including each running script and a couple of Entity types.
It turns all of these off, as well as LOD management, and twirls in place to get a baseline render rate.
Then it turns each load on, one at a time, and records a new render rate.
At the end, it reports the ordered results (in a popup), restores the original loads and LOD management, and quits.

Small performance changes are not meaningful.
If you think you find something that is significant, you should probably run again to make sure that it isn't random variation.
You can also compare (e.g., the baseline) for different conditions such as domain, version, server settings, etc.
This does not profile scripts as they are used -- it merely measures the effect of having the script loaded and running quietly.

### CODE REVIEW

**Comment by howard-stearns** [comment]
test plan:
Find a machine that consistenly runs High Fidelity Home at leass than 60fps.
Run the standard defaultScripts and the default Home content, with the lights on.
(You can just the url  https://raw.githubusercontent.com/howard-stearns/hifi/8ef9f48221fae9a8978882140319d15e722c73b7/scripts/developer/tests/loadedMachine.js)

Open and run this script. It will do 10 turns in place for each script, plus lights, particle effects, a baseline (and one extra at the beginning to get everything loaded).
After reporting the results in a popup, all the initial scripts should be loaded again, entity visibility restored, and LOD automation the same as when the script started.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8ef9f48221fae9a8978882140319d15e722c73b7 available at: https://gist.github.com/b656897af13e827c315ff3d837679561<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8196.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8196.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 74ef82f800b3fe3b409e6f8c327f058c25c21312 available at: https://gist.github.com/b656897af13e827c315ff3d837679561<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8196.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8196.dmg

**Comment by OmegaHeron** [comment]
QA Pass

Tested Windows 10 64 bit - i5 6500 CPU - GTX 970 GPU - Desktop mode and DK2

Works as advertised, no errors noted and Interface configuration returns to same as pre-test state once completed.  No interesting things found as my desktop doesn't struggle with FPS if a scene gets to point where this test can run.  I'll be trying it on my Laptop with GTX660M/i7 CPU later - it might show some more interesting things there.

**Pull request merged**
