### PR TITLE
Revert "Fix GoTo app in HMD mode"

### PR DESCRIPTION
**Pull request by sethalves**
This reverts commit 29dd24b05f1a060c1f2700a57e00ffe61c1d2988.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6606/app_12262_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6606/HighFidelity-Beta-PR12262-a79e947d4d2de645527e958cd90dec5a7d39eadf.dmg

**Comment by conklin94122** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6611/app_12262_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6611/HighFidelity-Beta-PR12262-a79e947d4d2de645527e958cd90dec5a7d39eadf.dmg

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6617/app_12262_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6617/HighFidelity-Beta-PR12262-a79e947d4d2de645527e958cd90dec5a7d39eadf.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6617/HighFidelity-Beta-PR12262-a79e947d4d2de645527e958cd90dec5a7d39eadf.exe

**Pull request closed without merging**
