### PR TITLE
7385 - Collect Stats on "Exit VR" button

### PR DESCRIPTION
**Pull request by ElderOrb**
https://highfidelity.fogbugz.com/f/cases/7385/Collect-Stats-on-Exit-VR-button

### CODE REVIEW

**Comment by ElderOrb** [comment]
For QA: 

This change should have zero impact on user experience. Every time 'Exit VR' clicked, 'exit_vr' action will be submitted to the stats DB.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3055/HighFidelity-Beta-PR11306-c0e7e5a8b2fa4c3e26cf500e0fb7cef45e483633.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3055/HighFidelity-Beta-PR11306-c0e7e5a8b2fa4c3e26cf500e0fb7cef45e483633.exe

**Comment by anshuman64** [comment]
testing this...

**Comment by anshuman64** [comment]
Hmm... I'm not seeing the data coming through. I will double check with engineers tomorrow to make sure I'm searching in the right place.

**Comment by anshuman64** [comment]
Engineer has helped me confirm this works :) Merging.

**Pull request merged**
