### PR TITLE
Prereq work for 'Reduce User Friction'

### PR DESCRIPTION
**Pull request by RebeccaStankus**
https://highfidelity.atlassian.net/browse/DEV-585

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21479/HighFidelity-Beta-PR16238-982bdf5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/21479/HighFidelity-Beta-Interface-PR16238-982bdf5.dmg

**Comment by hifi-gustavo** [comment]
Android build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21479/HighFidelity-Beta-PR16238-982bdf5.apk).  Quest build is available [here](https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/21479/HighFidelity-Quest-Beta-PR16238-982bdf5.apk)

**Comment by RebeccaStankus** [comment]
Build this please

**Pull request merged**
