### PR TITLE
refresh/close the asset browser dialog on domain switch

### PR DESCRIPTION
**Pull request by birarda**
- renamed "My Asset Server" dialog to "Asset Browser"
- fixed an issue where the dialog would show the previous Asset Server contents on a domain switch

### CODE REVIEW

**Comment by birarda** [comment]
Fix for https://app.asana.com/0/26225263936266/107459015439987.

To test, open the Asset Browser from the edit menu in a domain that you can rez models in. Switch to a new domain.

On master, the contents of the dialog will not refresh and you will be looking at the mappings for the Asset Server you are no longer connected to.

On this PR, it will either refresh to update to the contents of the new Asset Server you connect to, or close the dialog if you don't have permissions to rez models in that domain.

**Comment by hifi-gustavo** [comment]
Build console output for commit: ee7bee95f8a94e67ff596c5bdbe81426248ff2ed available at: https://gist.github.com/029602c270df6bed33f13f9c53d1ab15<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7542.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7542.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 7
Open ATP browser at Heron - moved to Sandbox asset browser changed available models content - moved to Alpha and Asset Browser closed.  :+1: 

Used Asset Browser to place a model and uploaded a new one after exercising above.  :+1: 

Does it make sense to change menu name to same "Asset Browser" as well?

QA Pass

**Comment by birarda** [comment]
It does @OmegaHeron, thank you.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 309d327a3789239f285d492fdfc3875c30d0c879 available at: https://gist.github.com/029602c270df6bed33f13f9c53d1ab15<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7542.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/HighFidelity-Alpha-PR7542.dmg

**Pull request merged**
