### PR TITLE
Don't Delete Whiteboard When Spawner Script Closes

### PR DESCRIPTION
**Pull request by ericrius1**
This PR makes the whiteboard created by whtieboardSpawner.js persistent, instead of deleting it when the script closes. https://rawgit.com/ericrius1/hifi/whiteboardCleanupFix/examples/painting/whiteboard/whiteboardSpawner.js

### CODE REVIEW

**Comment by imgntn** [comment]
@ericrius1 can you plz include a testing link?  title was a little confusing so i updated it and description so update notes in interface aren't blank for this

**Comment by imgntn** [comment]
https://rawgit.com/ericrius1/hifi/whiteboardCleanupFix/examples/painting/whiteboard/whiteboardSpawner.js

**Comment by imgntn** [comment]
I have some notes:

1. My aiming dot disappears when I release the trigger of my opposite hand (i.e. painting with left, click right trigger and release)
2. Still very easy to get too close to the board and have my beams go through and do nothing
3. The black square turns white when I get my aiming dot near the edges of the board
4. I can paint on the wooden bevel of the whiteboard, which feels wrong

**Comment by ericrius1** [comment]
opening another PR which fixes this and more

**Pull request closed without merging**
