### PR TITLE
Beta Release 28 Hotfix - Windows 7 audio fix

### PR DESCRIPTION
**Pull request by cozza13**
This will fix the issue that people on windows 7 are having with audio

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: b24c81e334c8ea5801ef2eeb0462fe4ef2c554fc available at: https://gist.github.com/f07beeb24c2dec1ff3a1d137aeb18e5f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9112-b24c81e.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9112-b24c81e.dmg

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**localhost 'createTestBlocks.js' Result**: **localhost 'createTestBlocks.js'** SUCCESS
**localhost ATP Upload + Edit Result**: **localhost ATP** SUCCESS
**Echo Server Audio**: **Echo Server Audio** SUCCESS
**localhost 'reverbTest.js' Result**: **localhost 'reverbTest.js'** SUCCESS
**localhost 'playaPerformanceTest.js' Result**: **localhost 'playaPerformanceTest.js'** SUCCESS
**dev-playa 'playaPerformanceTest.js' Result**: **dev-playa 'playaPerformanceTest.js'** SUCCESS
**dev-demo 'playaPerformanceTest.js' Result**: **dev-demo 'playaPerformanceTest.js'** SUCCESS
**QA Pass**: **QA Pass** SUCCESS
**Additional Test Results + Observations**: Success. Audio worked as expected.  Successfully heard environment sounds in, ```localhost```, ```dev-demo``` and ```dev-playa```.

**Domain** |localhost |dev-playa |dev-demo
---|---|---|---
**Render Rate**: |60 |60 |60
**Present Rate**: |60 |60 |60
**Present New Rate**: |58 |60 |59
**CPU Buffer Count**: |788 |498 |325
**GPU Buffer Count**: |138 |120 |132
**CPU Memory Usage**: |10412032 |6406144 |6316032
**GPU Memory Usage**: |4579328 |3899392 |4194304
**CPU Texture Count**: |117 |63 |57
**GPU Texture Count**: |61 |43 |41
**GPU Transfer Count**: |0 |2 |0
**CPU Texture Memory Usage**: |123917544 |39061968 |26479056
**GPU Texture Memory Usage**: |299443294 |180723542 |180723542
**GPU Virtual Memory Usage**: |295609234|185638720|180046316
**Triangle Count**: |69968 |91609 |68828
**Triangle Rate**: |4373000 |5725562 |4301750
**API Drawcall Count**: |40 |70 |63
**Drawcall Count**: |2682 |66 |68
**Drawcall Rate**: |167625 |4125 |4250
**State Changes Texture Count**:|81 |46 |46
**Pipeline Count**: |29 |32 |26
**Item Opaques**: |33 |210 |70
**Item Translucents**: |10 |65 |45
**Item Lights**: |1 |83 |41
**Timing Opaques**: |0.154 |0.45 |0.197
**Timing Translucents**: |0.042 |0.09 |0.038
**Timing Lighting**: |0.049 |0.092 |0.049
**Render Frame**: |0.608 |1.565 |0.92

**Comment by OmegaHeron** [comment]
Testing Windows 10 - i5 6500 CPU - GTX970 GPU

All tests pass - same results as last RC.  Unable to specifically test Win 7 fix.

**Pull request merged**
