### PR TITLE
Final Assessment - Raymond Huang

### PR DESCRIPTION
**Pull request by ray10102**
Changed the window title of Interface

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14457/HighFidelity-Beta-PR14290-f6589b5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14457/HighFidelity-Beta-PR14290-f6589b5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14457/HighFidelity-Beta-Interface-PR14290-f6589b5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14457/HighFidelity-Beta-PR14290-f6589b5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14457/HighFidelity-Beta-Interface-PR14290-f6589b5.exe

**Comment by huffman** [comment]
Thanks @ray10102, just wanted to confirm that it compiled, and it did 👍

**Pull request closed without merging**
