### PR TITLE
Change AudioDevices.cpp

### PR DESCRIPTION
**Pull request by Tingjin**
Remove two lines of unnecessary code.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Can one of the admins verify this patch?

**Comment by sethalves** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1581/HighFidelity-Beta-PR10948-80916b62bb2558c0e4db063bf4cd637f4f0cbda2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1581/HighFidelity-Beta-PR10948-80916b62bb2558c0e4db063bf4cd637f4f0cbda2.exe

**Pull request merged**
