### PR TITLE
Fix potential reliable connection lockup.

### PR DESCRIPTION
**Pull request by Atlante45**
This PR fixes a lockup that can potentially occur in very rare circumstances where all packets or ACKs for the current full congestion window get lost.

It also cleans up a lot of old dead UDT code.
While cleaning that code, I've spotted a very small memory leak that was most likely the cause of slowly growing server memory usage over very long periods of time, which the PR fixes as well.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11397/HighFidelity-Beta-PR13632-dcb27d0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11397/HighFidelity-Beta-PR13632-dcb27d0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11397/HighFidelity-Beta-Interface-PR13632-dcb27d0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11397/HighFidelity-Beta-PR13632-dcb27d0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11397/HighFidelity-Beta-Interface-PR13632-dcb27d0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11480/HighFidelity-Beta-PR13632-db2297d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11480/HighFidelity-Beta-PR13632-db2297d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11480/HighFidelity-Beta-Interface-PR13632-db2297d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11480/HighFidelity-Beta-PR13632-db2297d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11480/HighFidelity-Beta-Interface-PR13632-db2297d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pause Testing

**Comment by qliacoombs** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11903/HighFidelity-Beta-PR13632-db2297d.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11903/HighFidelity-Beta-PR13632-db2297d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11903/HighFidelity-Beta-Interface-PR13632-db2297d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11903/HighFidelity-Beta-PR13632-db2297d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11903/HighFidelity-Beta-Interface-PR13632-db2297d.dmg

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Files uploaded and avatar changed successfully.

**Comment by conklin94122** [comment]
build this please

**Comment by conklin94122** [comment]
QA Approval is stale, retesting.

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12142/HighFidelity-Beta-PR13632-db2297d.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12142/HighFidelity-Beta-PR13632-db2297d.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12142/HighFidelity-Beta-Interface-PR13632-db2297d.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12142/HighFidelity-Beta-PR13632-db2297d.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12142/HighFidelity-Beta-Interface-PR13632-db2297d.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Files uploaded successfully and avatar switched.

**Pull request merged**
