### PR TITLE
Tablet Main Screen UI Prototype

### PR DESCRIPTION
**Pull request by fayeli**
This qml prototype now:
- Make use of qml inheritance for tablet buttons, set color and text at instantiation
- Drop shadow effects on tablet buttons
- Glow high lights around buttons on hover

Screenshot:
image

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 53263789a0b56b4521d0873bc2d39e3e5c58922f available at: https://gist.github.com/c81d1745d3d217a0b931b992d3089121<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-5326378.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-5326378.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a651e19bddd8c459f57d85d817612d4104596888 available at: https://gist.github.com/c81d1745d3d217a0b931b992d3089121<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-a651e19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-a651e19.dmg

**Comment by hyperlogic** [comment]
It's unclear why the windows build failed.  Let's try this again.  test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: a651e19bddd8c459f57d85d817612d4104596888 available at: https://gist.github.com/c81d1745d3d217a0b931b992d3089121<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-a651e19.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9203-a651e19.dmg

**Pull request merged**
