### PR TITLE
Remove the avatarEntitiesBookmark menu option

### PR DESCRIPTION
**Pull request by druiz17**
Instead of have a avatarEntitesBookmark menu option, avatar entities will instead be saved when you bookmark avatars.

previous saved avatar entities files will no longer work

ticket - https://highfidelity.manuscript.com/f/cases/resolve/12583/Bookmarking-Avatar-Entities-to-be-changed-to-Bookmarking-Avatars-in-Menu-UI

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
-  wear some avatar entities and adjust them
-  bookmark your avatar by clicking Avatar > Bookmark Avatar.
-  add bookmarks for different types of avatar and avatar entities together
-  select a saved bookmark of your avatar from, Avatar > Avatar Bookmarks
-  mark sure that the bookmark loads the correct avatar and avatar entities with the correct adjustment
-  relaunch interface an preform the previous two tests

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7484/app_12494_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7484/HighFidelity-Beta-PR12494-d0ec84b6c8739ad6eab55eefe7bc6efd71038eb2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7484/HighFidelity-Beta-PR12494-d0ec84b6c8739ad6eab55eefe7bc6efd71038eb2.exe

**Comment by qlimnavarro** [comment]
Currently Testing.

**Comment by qlimnavarro** [comment]
Pass - @conklin94122

**Pull request merged**
