### PR TITLE
Add the ability to get the context that a script is running in

### PR DESCRIPTION
**Pull request by huffman**
Open to feedback on naming and the way in which you get the current context. Strings often feel fragile, so I added convenience functions: `isClientScript()`, `isEntityClientScript()` etc.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 59913ffdb972e3b69d14ded028df5c235ee0f487 available at: https://gist.github.com/cb397114e5d2542081b0b66dab74df8f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-59913ff.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-59913ff.dmg

**Comment by Nex-Pro** [comment]
@huffman Does this hint at a fourth type of script ?

**Comment by huffman** [comment]
@Nex-Pro 😃 😄 😃

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2ccb61f9b47884b73150f39e50052bd55f0882aa available at: https://gist.github.com/cb397114e5d2542081b0b66dab74df8f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-2ccb61f.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-2ccb61f.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b1cd52fb493162f6ced94a50e3585a6e3ea8485 available at: https://gist.github.com/cb397114e5d2542081b0b66dab74df8f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-9b1cd52.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-9b1cd52.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 95024d2b8092f2798f49a251778699682ffb1d25 available at: https://gist.github.com/cb397114e5d2542081b0b66dab74df8f<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-95024d2.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9374-95024d2.dmg

**Pull request closed without merging**
