### PR TITLE
Case 19495: zero velocities of non-dynamic entities on nearGrab release

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
https://highfidelity.fogbugz.com/f/cases/19495/In-VR-mode-grabbed-non-dynamic-entities-retain-linear-velocity-if-released-while-avatar-is-moving

**Test Plan:**
**(1)** Make a non-dynamic Entity
**(2)** In HMD: near-grab Entity
**(3)** While walking avatar around: release grab on Entity
**-->** on bugged version: entity leaves grab with non-zero velocity
**-->** on fixed version: entity leaves grab and has zero velocity

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14520/HighFidelity-Beta-PR14305-90e944f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14520/HighFidelity-Beta-PR14305-90e944f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14520/HighFidelity-Beta-Interface-PR14305-90e944f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14520/HighFidelity-Beta-PR14305-90e944f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14520/HighFidelity-Beta-Interface-PR14305-90e944f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14530/HighFidelity-Beta-PR14305-225e8e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14530/HighFidelity-Beta-PR14305-225e8e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14530/HighFidelity-Beta-Interface-PR14305-225e8e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14530/HighFidelity-Beta-PR14305-225e8e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14530/HighFidelity-Beta-Interface-PR14305-225e8e0.exe

**Comment by qaAdamSmith82** [comment]
Per discussion with Dev, this PR will require more than happy path testing

**Comment by qaAdamSmith82** [comment]
Test Plan 2

**Comment by rickcarr044** [comment]
build this please

**Comment by rickcarr044** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14988/HighFidelity-Beta-PR14305-225e8e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14988/HighFidelity-Beta-PR14305-225e8e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14988/HighFidelity-Beta-Interface-PR14305-225e8e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14988/HighFidelity-Beta-PR14305-225e8e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14988/HighFidelity-Beta-Interface-PR14305-225e8e0.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
