### PR TITLE
fix crash on exit

### PR DESCRIPTION
**Pull request by danteruiz**
Fix crash on exit.

ticket - https://highfidelity.fogbugz.com/f/cases/17172/Interface-Crashed-Last-Run-shows-on-every-launch

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan
- launch interface
- exit interface and you should not crash and/or  should not be prompted with a reset settings dialog

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/11716/HighFidelity-Beta-PR13723-fee1049.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11716/HighFidelity-Beta-PR13723-fee1049.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/11716/HighFidelity-Beta-Interface-PR13723-fee1049.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11716/HighFidelity-Beta-PR13723-fee1049.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/11716/HighFidelity-Beta-Interface-PR13723-fee1049.exe

**Pull request closed without merging**
