### PR TITLE
Fix collapse headers in edit.js

### PR DESCRIPTION
**Pull request by misslivirose**
This fixes FB Case 11575

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7017/app_12359_PR.apk

**Comment by misslivirose** [comment]
**Test Plan:** 
Confirm (in desktop and HMD modes) that the properties appear as listed, and that clicking or triggering on the drop down icon on the collapsible section headers collapses the appropriate selections, updates the state of the drop down arrow, and does not affect the top icon.

Run the following tests as a regression suite to confirm that properties are appearing as they should be, with at least one test completed in desktop mode and one in HMD mode 

- C6767 
- C6769 
- C6768 
- C6771

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7017/HighFidelity-Beta-PR12359-be4a009e119159ade0e93096c34ba7d03ccd9506.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7017/HighFidelity-Beta-PR12359-be4a009e119159ade0e93096c34ba7d03ccd9506.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Pull request merged**
