### PR TITLE
drop empty parts when splitting script whitelist

### PR DESCRIPTION
**Pull request by birarda**
- fixed a bug with empty entity script whitelist not skipping script check

### CODE REVIEW

**Comment by birarda** [comment]
#### Test Plan

test script -> https://gist.githubusercontent.com/birarda/641b466704dac409b53aa75d89935ac3/raw/61c75befce101f66b84b87e244b51f4b001dc3e5/test-ess-1.js

(1) Add `gist.githubusercontent` to your script whitelist in domain-server settings. Add an entity that uses the test script. On master this script should run (since gist.githubusercontent.com starts with gist.githubusercontent) but on this PR it should be rejected, since the host does not match exactly.

(2) Change the URL for whitelist in domain-server settings to `gist.githubusercontent.com` and ensure that this PR allows the test script to run.

(3) Change the URL for whitelist in domain-server settings to `gist.githubusercontent.com/birarda` and ensure that this PR allows the test script to run.  

(4) Change the URL for whitelist in domain-server settings to `gist.githubusercontent.com/Atlante45` and ensure that this PR does not allow the test script to run.

(5) Ensure that a whitelist with multiple domains works as expected.

(6) Ensure that all scripts are allowed with an empty whitelist.

**Comment by hifi-gustavo** [comment]
Build console output for commit: d4a161041ee5e14c6f816296176057dad3b9eccb available at: https://gist.github.com/281598308166180fc1703014de2e6ef3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9573-d4a1610.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9573-d4a1610.dmg

**Comment by cozza13** [comment]
testing

**Comment by cozza13** [comment]
I have tested this with a Marketplace asset and that works again. @davidkelly where you testing the other areas, or need someone else?

**Comment by davidkelly** [comment]
I was going through the test plan above, but didn't finish.  Should have pulled off the qa in progress last night, just in case someone else had time.  Finishing now

**Comment by davidkelly** [comment]
I believe this is a QA pass.  But, if I have an _existing_ entity I can put this script on it, and it runs on a second interface even when (as in step 4 above) I've not allowed that domain.  Is this expected behavior?

**Comment by davidkelly** [comment]
QA pass.  One thing I noticed is that this doesn't disallow the scripts if they already are on the object when you change the filter.  That seems to be why I thought there were issues this morning.

**Comment by ZappoMan** [comment]
The behavior you describe is consistent with the spec. The filter only checks edits while the filter is in place.

**Pull request merged**
