### PR TITLE
Improvements to overlays.

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
## Changes

  * Certain `Base3DOverlay`s can now be grouped into `FloatingUIPanel`s.
    * They must subclass from `PanelAttachable` in order to position themselves relative to the panel.
  * New script `controlPanel.js` added.
    * When script is running, right click to see a 3D control panel.
    * Toggle mic mute, face mute, and address bar.
  * New script `floatingUIExample.js` added in `example/ui/`.
    * Demonstrates new functionality.
  * New script `overlayManager.js` added in `libraries`.
    * Replaces `Overlays` for managing overlays in scripts.
    * Takes an object oriented approach to overlays and panels.
    * Including it will remove `Overlays` from the global scope for your script, but all of the functionality is still there.

**Note:** we are aware of the rendering issues with `BillboardOverlay` and `.svg` images as seen in `controlPanel.js` and are working to fix them.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: e9b423668864c2526e0b2b2460309edb0e46dbe1 available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by ZappoMan** [comment]
Build errors on Windows and Unix

**Comment by PhilipRosedale** [comment]
build not working?

**Comment by AlexanderOtavka** [comment]
Not on Linux or Windows.

**Comment by hifi-gustavo** [comment]
Build console output for commit: fc904338f9c9bc067feb6a8778d20ef7a016b38d available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 32887c4533273c0ffce2daf11896ba6ffac84583 available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7973c2d469f1be8747488cfbe690476887e922a6 available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 055c9dc59b5e064bfde03281dd894148cf487a21 available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by OmegaHeron** [comment]
Is there a specific setup for running these PR builds on windows in so far as script source directory structure?  In this case it's attempting to load two included files from floatingUI.js - globals.js and overlayManager.js - it references those as relative paths "../../libraries/glabals.js" and "../../libraries/overlayManager.js" but Interface is resolving those to; [DEBUG] [08/03 14:22:44] Error loading file: QUrl( "c:/Users/x/libraries/overlayManager.js" ) line: 867

**Comment by hifi-gustavo** [comment]
Build console output for commit: d24006e71593ae6db7d03b921d6b6dca011eb462 available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1b4ba75b5a597313576940810833cb5f2a59d82c available at: https://gist.github.com/c5b300adf8891296875d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5430.dmg

**Comment by AlexanderOtavka** [comment]
I'm not sure why the relative includes wouldn't work on windows.  There is another script that uses relative includes at `hifi/examples/example/solarsystem.js`.  Try running that.  If it doesn't error, then I'll look into the differences between our scripts.

**Comment by OmegaHeron** [comment]
Yeah - it's odd that launching script from PR installer script directory resolves ../../something to what it does.  May be a windows 10 issue.  For now I've worked around by creating what it wants and placing includes there.  Will dig more into it when I have time.  Thanks for reply though!

**Comment by AlexanderOtavka** [comment]
No problem.  I'm afraid I work on mac so I can't really help you.

**Pull request merged**
