### PR TITLE
Application dpi scale

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: ab542c3599e180a09abaac2b2773d679dde51c21 available at: https://gist.github.com/51edeefead5a91d4c618<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 18a92464b5666f909b0575924215fdbad9552d3d available at: https://gist.github.com/13f7b349b28f15d7ba67<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by huffman** [comment]
Ignore this PR for now - getting builds so we can test on Windows

**Comment by hifi-gustavo** [comment]
Build console output for commit: f44ec6da1295363b3643c94706fe358dd0606750 available at: https://gist.github.com/35a727837dc6a9e4ca7b<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a069a2f21c95500b5154f7b83440cdba09183412 available at: https://gist.github.com/92f394bcc1d6f492ed6b<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a383ff17723d472b61d6ead1ef96f622b2fd453 available at: https://gist.github.com/d46ec3c1425adc5c1234<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ff1fb07b2d2241ed760e27ef9eb9f62deea6ce32 available at: https://gist.github.com/86573c9edec7de22ca30<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 7dab39a2f19d3ed3336baf4fcb873764f67f65a5 available at: https://gist.github.com/05028ea9cbfc0465e040<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: ec1087e806851a46afc9b04f5ad9153ac90ef186 available at: https://gist.github.com/6b04a907a49e18debd77<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b2e1d8a38c6941e82641c65e1298cd53cf8664f4 available at: https://gist.github.com/18f2af49a57b47933858<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 51f5719e0ff90577f6d6e07a38e7bb9da2ce0674 available at: https://gist.github.com/34af0a4f5a4312e31721<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 2828b65bea550500bdcde6b8523278cd6ab4d278 available at: https://gist.github.com/ae1c9847d7d955268649<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 9b719273ab1aa2e8fe3e9111d390d512aad6cc51 available at: https://gist.github.com/05559ecae6a1000c9ece<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 22d46e3e6ba239407f5d8c49fe18b6815e679be9 available at: https://gist.github.com/9e0807a4b8bdb9ef68b7<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4751974c459ac25f5e29ec4b60037bdcd32b82cb available at: https://gist.github.com/ccd1aebf68a97f93300d<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: a8999964f6dbb266e8bbf5bc9eba8aed13d6b024 available at: https://gist.github.com/cc0c95843c84e62f7690<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by huffman** [comment]
This is ready to review

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4a8e3193a9c44292df6458fc63106b4605179f6e available at: https://gist.github.com/5b5a6488648c8c95d7a7<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4dfe7257214925bc4a7a91f2e52ad8d31ca8fe6d available at: https://gist.github.com/a2bd00bf87dfdb0b6355<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Comment by AndrewMeadows** [comment]
Huffman, can you resolve the conflicts for this merge?

**Comment by huffman** [comment]
@AndrewMeadows Ack, yep, sorry about that!

**Comment by huffman** [comment]
@AndrewMeadows Merged, now waiting for jenkins

**Comment by hifi-gustavo** [comment]
OS X Yosemite functional test completed with errors
Download recording here:
https://s3.amazonaws.com/hifi-public/pr-builds/recordings/4311.mov

**Comment by hifi-gustavo** [comment]
Build console output for commit: e6d9a1b251ff7f3589120adfc19236b6b7fcc3fb available at: https://gist.github.com/b15d7c374e8ef5384727<br/><br/>Installers available for download at:<br>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.exe<br>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4311.dmg

**Pull request merged**
