### PR TITLE
fix motion of collisionless avatar in desktop mode

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
While looking into some reports of avatar movement problems when setting the avatar collisionless (disable Developer-->Avatar-->EnableAvatarCollisions) in HMD I noticed some problems when trying to move a collisionless avatar in desktop mode:

(1) avatar would fall with gravity when standing above ground even when collisionless
(2) avatar could not easily transition into hover mode when collisionless and standing over a floor

This PR fixes these problems.  To test:

(1) Login in desktop-mode (no HMD)
(2) Disable avatar collisions:  uncheck Developer-->Avatar-->EnableAvatarCollisions
(3) Using arrow keys try to navigate:
(3a) forward and back
(3b) up and down
(3c) through objects

The expected fixed behavior: the avatar should be able to move around as expected when collisionless.  Its animation state will either be "hover" when moving or "standing" to when stopped.

(4) Re-enable avatar collisions --> verify that the avatar's walking/hovering motion still works as expected.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b3ac44796d0b03c9431b0f80c12fdce9b7ddd8de available at: https://gist.github.com/6683801550abaeec605120dbbc433080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-b3ac447.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-b3ac447.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: b1b3654f5bfba2be2453b5df5b1008a5ff9833cb available at: https://gist.github.com/6683801550abaeec605120dbbc433080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-b1b3654.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-b1b3654.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 49ca44a5a5b175a6d0be6399eebc30570552dd9c available at: https://gist.github.com/6683801550abaeec605120dbbc433080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-49ca44a.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-49ca44a.dmg

**Comment by AndrewMeadows** [comment]
The branch for this PR is probably the right place to start any salvage of the out-of-body-experience (OOBE) project.  I'll rebase onto master where the rest of the OOBE fixes were merged and then close this PR until we get back to it.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8f9e3e51d76bcc09dd453cbc4fb0f43abb80a1bd available at: https://gist.github.com/6683801550abaeec605120dbbc433080<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-8f9e3e5.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9152-8f9e3e5.dmg

**Comment by AndrewMeadows** [comment]
Closing this.  We'll probably salvage in the future.

**Pull request closed without merging**
