### PR TITLE
Keyboard menu option in general settings (RC76)

### PR DESCRIPTION
**Pull request by danteruiz**
Move the keyboard toggle option from developers to Settings > general

ticket - https://highfidelity.manuscript.com/f/cases/20042/Add-toggle-to-turn-off-on-3D-Keyboard

### CODE REVIEW

**Comment by danteruiz** [comment]
Test plan in this PR - https://github.com/highfidelity/hifi/pull/14483

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15449/HighFidelity-Beta-PR14484-b3e85e0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15449/HighFidelity-Beta-PR14484-b3e85e0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15449/HighFidelity-Beta-Interface-PR14484-b3e85e0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15449/HighFidelity-Beta-PR14484-b3e85e0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15449/HighFidelity-Beta-Interface-PR14484-b3e85e0.exe

**Comment by JeffClinton** [comment]
Currently testing

**Pull request merged**
