### PR TITLE
Prevent edit press events when pointing at tablet or desktop windows

### PR DESCRIPTION
**Pull request by dback2**
Send data from inEditMode module to entitySelectionTool that indicates whether either the left or right hand is pointing at either a desktop window or the tablet. EntitySelectionTool stores these flags per hand, and upon triggering will verify the given trigger hand is not pointing at either before allowing it's mouse press events.

Fixes: https://highfidelity.manuscript.com/f/cases/15198/

Test Plan:
-Enter Interface in HMD mode
-Open Create app in the tablet, create any entity, and then select it
-Place the tablet between you and the selected entity
-Attempt to use the entity edit handles on the selected entity when pointing through the tablet at them
-Verify you can not trigger the edit handles to initiate any rotation/translation/stretching/scaling edits when pointing through the tablet
-Open the Script Log (HMD-Friendly) under Menu -> Developer in the tablet
-Adjust so that the entity from above can be behind the Script Log window
-Open Create and select the entity from above again
-Attempt to use the entity edit handles on the selected entity when pointing through the Script Log window at them
-Verify you can not trigger the edit handles to initiate any rotation/translation/stretching/scaling edits when pointing through the Script Log window

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10616/HighFidelity-Beta-PR13390-bc06b88.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10616/HighFidelity-Beta-PR13390-bc06b88.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10616/HighFidelity-Beta-Interface-PR13390-bc06b88.dmg

**Comment by Qliemillar** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/10859/HighFidelity-Beta-PR13390-bc06b88.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10859/HighFidelity-Beta-PR13390-bc06b88.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/10859/HighFidelity-Beta-Interface-PR13390-bc06b88.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10859/HighFidelity-Beta-PR13390-bc06b88.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/10859/HighFidelity-Beta-Interface-PR13390-bc06b88.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Lasers cannot go through things.

**Pull request merged**
