### PR TITLE
Move Toybox Domain to Production s3

### PR DESCRIPTION
**Pull request by imgntn**
This PR collects all of the toybox scripts into unpublishedScripts/domainContent, collects all assets and scripts and changes references to the production version of our s3 bucket so things will be cached.

Due to access restrictions this will need to be QA'd by Hifi employees.

To test

1. go to demo
2. try the toys
3. press the hidden reset on the arcade machine
4. go to another domain.
5. come back (things should load quickly from cache

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 45bb91cb0bf8f7fbca1bb314485e6578df745d4e available at: https://gist.github.com/da781e8ada09546802d3709bf9813ed3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7793.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7793.dmg

**Comment by hifi-gustavo** [comment]
Build console output for commit: 4fd6647d0bcd7efcc6c6299414c343447d33694c available at: https://gist.github.com/da781e8ada09546802d3709bf9813ed3<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7793.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR7793.dmg

**Comment by nbq** [comment]
I have access, I will test this in a moment

**Comment by nbq** [comment]
I tested the reset prim with my mouse and my hydra and even checked to make sure it was in the right place. Clicking it did nothing for me so I am going say either this failed or I am doing something wrong.

**Comment by imgntn** [comment]
hmm okay thanks let me check

**Comment by imgntn** [comment]
@hyperlogic made it a bit bigger, should be working now! 
capture

**Comment by nbq** [comment]
I tested again today and even cleaned out interface.ini to make sure it was not a setting I changed but I cannot get the resetter to work on click for me like it used to. I am using the Interface build from this PR. I will put this for someone else to test but for some reason I cannot click it and I have verified I am clicking in the right place by using edit to verify its in the right place.

**Comment by imgntn** [comment]
soooo the caching on the production bucket is super aggressive.  if you got a bad script for some reason you may be stuck with it... can you try doing a 'Developer -> Network --> Clear content"?  And then in running scripts, a "Reload All"?  And finally, send me your log (you can look for hiddenEntityReset) and let me know if there are errors.  Thanks again.

**Comment by nbq** [comment]
I just tested this and after reloading the scripts and clearing content it now works as described and it loaded very fast when I went to sandbox and came back. I say it PASSES for me now.

**Pull request merged**
