### PR TITLE
Delete orphan QML file

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
TabletFileDialog,qml currently used is in /qml/dialogs.

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
Testing
Thorough test of tablet that file/directory selection dialogs all work, e.g., Running Scripts > From Disk, Settings > General > Put my snapshots here.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 1436525a1e5cc54e16213e53d2376f31cd1e71ed available at: https://gist.github.com/96a7de6c8849492fa3b841cdc9602523<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10233-1436525.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10233-1436525.dmg

**Comment by 68chase** [comment]
Testing

**Comment by 68chase** [comment]
Fail.  When I select my users/documents directory as the snapshot location, it doesn't react the same as my current non-testing build.

This picture shows what happens when I change Snapshot Location in the current (Version - 6291) build
hifi-snap-by-68chase-on-2017-04-17_19-49-29




This picture shows what happens when I change Snapshot Location in the PR 10233 Version



hifi-snap-by-68chase-on-2017-04-17_19-52-14

**Pull request closed without merging**
