### PR TITLE
Handle tablet entities and overlays not being available

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
**Test Plan**

1) Test default scripts' tablet usage:
- Audio app interaction with the tablet: opening, operating dialog content, and "x" button.
- Create app interaction with the tablet: opening, operating dialog content, and "x" button.
- Create app editing an entity (moving, rotating, scaling).
- Help app interaction with the tablet: opening, operating dialog content, and "x" button.
- Menu app interaction with the tablet: opening, operating dialog content, and "x" button.
- People app interaction with the tablet: opening, operating dialog content, and "x" button.
- Market app interaction with the tablet: opening, operating dialog content, and "x" button.
- Lasering on and grabbing the tablet.
- Using stylus's with the tablet.

2) Test the Shapes app's interaction with the tablet: opening and closing the app. Run the Shapes app from zip file attached. (Is a copy from the "unpublishedScripts" directory from source control as at this PR.)

[shapes.zip](https://github.com/highfidelity/hifi/files/1704704/shapes.zip)

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7014/app_12356_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7014/HighFidelity-Beta-PR12356-adb6f66a05a7ce4d9181712e5c24b8222983e70b.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7014/HighFidelity-Beta-PR12356-adb6f66a05a7ce4d9181712e5c24b8222983e70b.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Failed. While the stylus interacted as expected with the tablet, it would only highlight items on the shapes app, and would not allow selection of any item on the app.

@conklin94122

**Comment by ctrlaltdavid** [comment]
The styli not working with the Shapes app is per current functionality / design - styli don't appear when hands are near the Shapes app UI, and even if they are present if the tablet happens to be nearby they don't interact with the Shapes app UI. I confirmed this with current Interface release and Shape app, and have added a Manuscript case on the idea of making the Shapes app work with styli: https://highfidelity.fogbugz.com/f/cases/12179/Shapes-app-doesn-t-support-using-stylus

@conklin94122

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/7141/app_12356_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/7141/HighFidelity-Beta-PR12356-2ff78493dbf68bd3d988aebfef44614e4e5a6b36.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/7141/HighFidelity-Beta-PR12356-2ff78493dbf68bd3d988aebfef44614e4e5a6b36.exe

**Pull request merged**
