### PR TITLE
[Case 4315]  Edit menu color picker OK button is hard to use in HMD

### PR DESCRIPTION
**Pull request by 1P-Cusack**
* Fixes the issue scrolling versus color selection in HMD mode while the color picker is up.
* Has various ESLint & JSHint fixes.
* Adds a means of cancelling color alterations via the current color preview tile.
* Fixes issue with the color pickers where the current color started as black as opposed to the expected color of the entity selected.
* Shape color picker has been changed to use the picker's <code>rgbhex</code> mode as opposed to <code>hex</code> used by the other color fields to be tested against the other fields to see which is preferred.
    * Fixed color channel increment/decrement buttons.  Previously, clicking them wouldn't have any influence on the indicated channel values.  The user was forced to directly edit the value via the keyboard.
    * Fixed some layout issues with <code>rgbhex</code> mode

**Testing**

**Phase 1:**  Though this applies to both Desktop & HMD mode, I found it easier to test in Desktop mode where it was easier to grab and select objects within the world.

Create or select an instance of a light, text, shape, and zone entity within the world.  For the following fields the color portrayed in the color picker element  should also be shown in the color preview area when clicked as opposed to starting out black. 

* Light Color
* Text Color
* Text Background Color
* Shape Color
* Haze Key Light Color
* Haze Glaze Color
* Haze Glare Color

**_Before Example using Light Color Field:_**
case4315_lightcolor_before

**_After Example using Light Color Field:_**
case4315_lightcolor_after

**Phase 2:**  This must be tested in both HMD & Desktop Mode.

* Create or select an instance of a light object.
* Select the Light Color field to open the color picker.
* In HMD:  
    * Confirm that when moving the cursor around in the gradient square, that the Properties page which contains the picker doesn't scroll.  The page is stationary and the user is able to tweak the color by using the gradient square. 
    * Confirm the same is true for the Hue strip located to the right of the gradient square in the color picker.
* In Desktop:
    * Confirm that the picker operated as it did before, and that the fixes to the HMD mode didn't alter or have an ill effect the Desktop implementation.

**Phase 3:**  This can be tested in either Desktop or HMD mode.

Part 1:
* Create or select an instance of a shape object.
* Select the Entity Color field to open the color picker.
* Observe that this picker opens in a different mode containing the following items:
    * Color picker gradient square
    * Color picker hue strip
    * R Channel Input Field
    * G Channel Input Field
    * B Channel Input Field
    * Hex (#) Color Input Field
* Confirm that manipulating the cursor along the color gradient square updates the color of the shape entity dynamically.
* Confirm that the user is able to tweak any of the RGB channels without closing the picker.
    * Using the increment/decrement arrows in the field input box.
    * Clicking the input box and directly altering the field value.
        * Input number between 0 and 255.  The range being inclusive.
        * Input number greater than 255.  Observe that the field is capped at 255.

Part 2:

Contrast the user interaction with the Shape's Entity Color field, to that of the Light's Light Color field which uses the set up previously utilized by the Shape's color field.  Which is preferred.

**Screenshots of Shape Color Field:**
    Note:  See above screenshots for visuals of the Light Color Field

Before:

case4315_before

After:

case4315_after

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/5829/app_12058_PR.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5829/HighFidelity-Beta-PR12058-466e8781dde385533bd7c71263630bde420629cc.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5829/HighFidelity-Beta-PR12058-466e8781dde385533bd7c71263630bde420629cc.exe

**Comment by sbennett77** [comment]
Currently Testing.

**Comment by sbennett77** [comment]
Passed.

@conklin94122

**Comment by misslivirose** [comment]
I don't think it makes sense to have differently styled color pickers in the menu. The original bug for this was around the OK button usability, which I would expect to have changes in terms of providing visual feedback. I like the new color picker but it's outside of scope for the original task and I think it should be in a separate PR that applies to all color fields in Edit.

**Comment by LaShonda1P** [comment]
@misslivirose:  It wasn't my intent to have the 2 versions merged in simultaneously.  Addressing the issue with the Ok button and the subsequent issues with the removal of it, led to the different style.  The Shape Color field usage of it here was intended to allow for an easier compare/contrast for the issues addressed and the usage in general.   

Based on that comparison, all color fields would be switched over to the preferred version.  Apologies for the misunderstanding, I thought that I mentioned it in my PR Description; however, I may have been unclear regarding that.   I can switch the Shape color field back, and submit another PR with them all converted to the variant style if that's the preference.

**Comment by themelissabrown** [comment]
@LaShonda1P two PR's makes the most sense. The 1st one should fix the OK button issue so it matches the fogbugz ticket. The second one should be the color field changes.

**Comment by 1P-Cusack** [comment]
@themelissabrown, @misslivirose:  Ok, I'll split this up into 2 PRs.

**Comment by 1P-Cusack** [comment]
@themelissabrown, @misslivirose:  Looking into splitting this up, to keep the PRs as atomic as possible this PR will be split into 3 as opposed to the initially proposed 2:

1. Fix for the OK Button Fix (Case 4315)
2. Fix for the black color preview box, which I noticed while working on this bug
3.Fixes for the Color Picker to allow it to be a single control

I'm going to close this PR out and resubmit.

**Pull request closed without merging**
