### PR TITLE
Make tablet page indicators clickable to scroll tablet

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
### Test Plan

1) HMD mode
- Load sufficent app so that there are two or more pages of apps in the tablet.
- Note the circles at the bottom of the home page: large circle indicates current page shown; small circle indicate extra page.
- Hover your laser over the circles. The small circle should enlarge and display as green when hovered; the large circlel shouldn't change when hovered.
- Click the enlarged green circle. The tablet should swipe to that circle's page. And the circles should be updated to reflect the current page.
- Check that you can still click and drag the home page content to change pages also, and the circles reflect the current page displayed.

2) Desktop mode
- Disable Developer > UI > Desktop Tablet Becomes Toolbar, so that tablet is used on desktop instead of toolbar.
- Press Tab key to display tablet.
- Repeat tests in 1.

https://highfidelity.manuscript.com/f/cases/14836

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14417/HighFidelity-Beta-PR14283-51d56dd.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14417/HighFidelity-Beta-Interface-PR14283-51d56dd.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14417/HighFidelity-Beta-PR14283-51d56dd.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14417/HighFidelity-Beta-Interface-PR14283-51d56dd.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

Green circles can be clicked to go to tablet pages; current page is reflected accurately

**Pull request merged**
