### PR TITLE
fix multi-line sessionDisplayName

### PR DESCRIPTION
**Pull request by howard-stearns**
fixes https://highfidelity.fogbugz.com/f/cases/4052/PAL-shouldn-t-accept-multi-line-display-names

### CODE REVIEW

**Comment by howard-stearns** [comment]
The fix is taken as part of stripping the user-supplied displayName, before the result is compared against other names for uniqueness. However, it does not alter the semantics or use of displayName itself.

Test plan: Try setting MyAvatar.displayName = "foo pr10172 bar_123\nred white   \nblue"
In open (or re-open) the PAL. The session display name should be one line, and not end in _n+ (unless there are other "foo pr10172 bar" present!)

**Comment by hifi-gustavo** [comment]
Build console output for commit: c32879d807d573fa78a2ac23ccc7081b37fdf588 available at: https://gist.github.com/11e8d9c970b51bdb8286c0c6d4ba4626<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10172-c32879d.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10172-c32879d.dmg

**Comment by davidkelly** [comment]
This works perfectly for a display name with <whatever>_XXX\nYYY.  However, what about something like foo\nbar?  That will still show on multiple lines.  I think what we need is to strip new lines out, _then_ strip the _XXX off the end of that, to solve this issue in general.  Calling it QA Fail, but it is just another edge case.  It would be great to formulate one RegEx that can do this, but it can be easily done with 2...

**Comment by howard-stearns** [comment]
doh! I'll fix.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 54888f85bec049e0ffb35439af39de7cae42fd83 available at: https://gist.github.com/11e8d9c970b51bdb8286c0c6d4ba4626<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10172-54888f8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR10172-54888f8.dmg

**Comment by davidkelly** [comment]
Everything I tried seems to have worked 👍

**Pull request merged**
