### PR TITLE
wait 10s before growing jitter in a new session/domain

### PR DESCRIPTION
**Pull request by zzmp**

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 58916bf34c052ecae3a04bd3601430690335fb80 available at: https://gist.github.com/518296a9885896bca2ac09802edf8ebd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8612-58916bf.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8612-58916bf.dmg

**Comment by zzmp** [comment]
@Atlante45 needs reapproval

**Comment by hifi-gustavo** [comment]
Build console output for commit: 0d3a9af6a6a053d551568b0f65e4b8ef4e9878d9 available at: https://gist.github.com/518296a9885896bca2ac09802edf8ebd<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8612-0d3a9af.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8612-0d3a9af.dmg

**Comment by zzmp** [comment]
QA:

Developer > Audio > Audio Network Stats > Downstream mixed audio stats > Ringbuffer frames avg_available should be lower after startup with this PR than with the current build, on a session that starts up connected to localhost.

**Comment by kevinmthomasse** [comment]
testing

**Comment by kevinmthomasse** [comment]
## QA Test
**QA Tester**: KevinMThomas
**QA Pass**: SUCCESS
**Additional Test Results + Observations**: Ringbuffer frames average is lower on startup compared to current build..  Screen Shot enclosed.
build 5353
pr

**Pull request merged**
