### PR TITLE
Android - Daydream integration

### PR DESCRIPTION
**Pull request by Cristo86**
**Test plan**

Mode switching
- Test the app allows enter and exit VR mode
- The app should remember last mode the user has been in
- Entering VR mode should be always preceded by the daydream transition that ask the user to place the phone into the headset
- If the app needs to perform some operation in 2D while being in VR mode it must show the daydream transition that ask the user to remove the phone from the headset. i.e. starting from Daydream App when some permission is not granted

Controller
Info about the controller  >  https://support.google.com/daydream/answer/7184597?hl=en
- Clicking the touchpad left and right must rotate my avatar 
- Clicking the touchpad down and up must move/walk back and forward
- Clicking the center of the touchpad can be used to drag objects
- Use the app button to teleport
- Hold daydream button to re-center, in case you've not started pointing out forward

Head tracking
- Head rotation must be tracked and reflected in my avatar

---

How to use:
- In this PR (temporarily) the "MY VIEW" button switches to VR mode. Can't restore afterwards, see "Pending features and tasks".

Pending features and tasks:
- Upload gvr library to use in precompiled folder (with current version, we should copy by hand `gvr-android-sdk-1.170` into hifi_externals/precompiled folder) - DONE
- Correct eyes _focus_ or fov (maybe stop using rotate and interpret head pose correctly) - DONE
- Bring back the controller - Currently we don't have the UI that asks the user to 'turn on' the controller, but behind scenes we still need the user to activate the controller pressing the Home Button for some seconds. We *need* to implement our own version of this kind of instructions as that's given by GvrLayout that we are not using. 
- UI for selecting daydream mode
- Way to exit daydream mode (now, the only way is to clear data after setting it up pressing 'View' ) - DONE close button
- Extra daydream UI: close and settings are not present in our view. We'd use GvrLayout or make a similar thing to simulate it, with a catch, it should be after the daydream or hifi stencils are _drawn_.  - DONE settings button (goes to hifi settings)
- This may crash when switching to VR by the following assert: `A/libc: /Users/cduarte/dev/workspace-hifi/hifinw/libraries/gpu/src/gpu/Buffer.cpp:102: void gpu::Buffer::Update::apply() const: assertion "buffer._applyUpdateCount == updateNumber" failed` We need to find out why's that. - STILL PENDING BUT ONLY HAPPENS ON DEV BUILDS
- Crash in devices with no support of (vertex) shader storage blocks: `The number of vertex shader storage blocks (1) is greater than the maximum number allowed (0)` -- Addressed in PR https://github.com/highfidelity/hifi/pull/14379 - DONE

DO NOT MERGE yet

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13729/HighFidelity-Beta-PR14168-49f1d66.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13729/HighFidelity-Beta-Interface-PR14168-49f1d66.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13729/HighFidelity-Beta-PR14168-49f1d66.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13729/HighFidelity-Beta-Interface-PR14168-49f1d66.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13764/HighFidelity-Beta-PR14168-51e76d2.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13764/HighFidelity-Beta-Interface-PR14168-51e76d2.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13764/HighFidelity-Beta-PR14168-51e76d2.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13764/HighFidelity-Beta-Interface-PR14168-51e76d2.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/13773/HighFidelity-Beta-PR14168-8f5fac0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13773/HighFidelity-Beta-PR14168-8f5fac0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/13773/HighFidelity-Beta-Interface-PR14168-8f5fac0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13773/HighFidelity-Beta-PR14168-8f5fac0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/13773/HighFidelity-Beta-Interface-PR14168-8f5fac0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14164/HighFidelity-Beta-PR14168-f3727c5.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14164/HighFidelity-Beta-PR14168-f3727c5.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14164/HighFidelity-Beta-Interface-PR14168-f3727c5.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14164/HighFidelity-Beta-PR14168-f3727c5.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14164/HighFidelity-Beta-Interface-PR14168-f3727c5.exe

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14245/HighFidelity-Beta-PR14168-237294c.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14249/HighFidelity-Beta-PR14168-237294c.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14249/HighFidelity-Beta-PR14168-237294c.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14249/HighFidelity-Beta-Interface-PR14168-237294c.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14249/HighFidelity-Beta-PR14168-237294c.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/14249/HighFidelity-Beta-Interface-PR14168-237294c.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/14283/HighFidelity-Beta-PR14168-b3d3276.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/14283/HighFidelity-Beta-PR14168-b3d3276.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15073/HighFidelity-Beta-PR14168-1ec3615.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15073/HighFidelity-Beta-PR14168-1ec3615.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15073/HighFidelity-Beta-Interface-PR14168-1ec3615.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15073/HighFidelity-Beta-PR14168-1ec3615.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15073/HighFidelity-Beta-Interface-PR14168-1ec3615.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15090/HighFidelity-Beta-PR14168-1bcccbc.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15092/HighFidelity-Beta-PR14168-ddce6d0.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15160/HighFidelity-Beta-PR14168-a8f4276.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15418/HighFidelity-Beta-PR14168-1bf546f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15452/HighFidelity-Beta-PR14168-c7e1367.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15464/HighFidelity-Beta-PR14168-364fe52.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15479/HighFidelity-Beta-PR14168-8d8efe6.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15490/HighFidelity-Beta-PR14168-f1474e8.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15524/HighFidelity-Beta-PR14168-cb25d5b.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15536/HighFidelity-Beta-PR14168-6dcc4f5.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15591/HighFidelity-Beta-PR14168-47b665d.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15694/HighFidelity-Beta-PR14168-996be36.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15745/HighFidelity-Beta-PR14168-b4c57b3.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15788/HighFidelity-Beta-PR14168-e6fe18a.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15792/HighFidelity-Beta-PR14168-a1b724d.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15842/HighFidelity-Beta-PR14168-3be0d38.apk

**Comment by gcalero** [comment]
build this please

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15925/HighFidelity-Beta-PR14168-dbcfe99.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15942/HighFidelity-Beta-PR14168-e503d60.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15946/HighFidelity-Beta-PR14168-329ce8f.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15946/HighFidelity-Beta-PR14168-329ce8f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15946/HighFidelity-Beta-Interface-PR14168-329ce8f.exe

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15957/HighFidelity-Beta-PR14168-329ce8f.apk

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15961/HighFidelity-Beta-PR14168-0453cd0.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15961/HighFidelity-Beta-PR14168-0453cd0.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15961/HighFidelity-Beta-Interface-PR14168-0453cd0.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15961/HighFidelity-Beta-PR14168-0453cd0.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15961/HighFidelity-Beta-Interface-PR14168-0453cd0.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15980/HighFidelity-Beta-PR14168-53ce632.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15980/HighFidelity-Beta-PR14168-53ce632.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15980/HighFidelity-Beta-Interface-PR14168-53ce632.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15980/HighFidelity-Beta-PR14168-53ce632.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15980/HighFidelity-Beta-Interface-PR14168-53ce632.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/15985/HighFidelity-Beta-PR14168-6d894b3.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15985/HighFidelity-Beta-PR14168-6d894b3.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/15985/HighFidelity-Beta-Interface-PR14168-6d894b3.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15985/HighFidelity-Beta-PR14168-6d894b3.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/15985/HighFidelity-Beta-Interface-PR14168-6d894b3.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16012/HighFidelity-Beta-PR14168-a30a400.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16012/HighFidelity-Beta-Interface-PR14168-a30a400.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16012/HighFidelity-Beta-PR14168-a30a400.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16012/HighFidelity-Beta-Interface-PR14168-a30a400.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16013/HighFidelity-Beta-PR14168-8290043.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16013/HighFidelity-Beta-PR14168-8290043.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16013/HighFidelity-Beta-Interface-PR14168-8290043.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16013/HighFidelity-Beta-PR14168-8290043.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16013/HighFidelity-Beta-Interface-PR14168-8290043.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16015/HighFidelity-Beta-PR14168-878f756.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16015/HighFidelity-Beta-PR14168-878f756.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16015/HighFidelity-Beta-Interface-PR14168-878f756.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16015/HighFidelity-Beta-PR14168-878f756.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16015/HighFidelity-Beta-Interface-PR14168-878f756.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16030/HighFidelity-Beta-PR14168-ebd92c6.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16030/HighFidelity-Beta-PR14168-ebd92c6.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16030/HighFidelity-Beta-Interface-PR14168-ebd92c6.dmg

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16037/HighFidelity-Beta-PR14168-1e96e3a.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16037/HighFidelity-Beta-PR14168-1e96e3a.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16037/HighFidelity-Beta-Interface-PR14168-1e96e3a.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16037/HighFidelity-Beta-PR14168-1e96e3a.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16037/HighFidelity-Beta-Interface-PR14168-1e96e3a.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16064/HighFidelity-Beta-PR14168-2a2859f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16064/HighFidelity-Beta-Interface-PR14168-2a2859f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16064/HighFidelity-Beta-PR14168-2a2859f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16064/HighFidelity-Beta-Interface-PR14168-2a2859f.exe

**Comment by gcalero** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16071/HighFidelity-Beta-PR14168-2a2859f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16071/HighFidelity-Beta-PR14168-2a2859f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16071/HighFidelity-Beta-Interface-PR14168-2a2859f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16071/HighFidelity-Beta-PR14168-2a2859f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16071/HighFidelity-Beta-Interface-PR14168-2a2859f.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16133/HighFidelity-Beta-PR14168-3f3963f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16133/HighFidelity-Beta-PR14168-3f3963f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16133/HighFidelity-Beta-Interface-PR14168-3f3963f.dmg

**Comment by Cristo86** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16184/HighFidelity-Beta-PR14168-3f3963f.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16184/HighFidelity-Beta-PR14168-3f3963f.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16184/HighFidelity-Beta-Interface-PR14168-3f3963f.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16184/HighFidelity-Beta-PR14168-3f3963f.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16184/HighFidelity-Beta-Interface-PR14168-3f3963f.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16208/HighFidelity-Beta-PR14168-e84ec15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16208/HighFidelity-Beta-Interface-PR14168-e84ec15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16208/HighFidelity-Beta-PR14168-e84ec15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16208/HighFidelity-Beta-Interface-PR14168-e84ec15.exe

**Comment by Cristo86** [comment]
Build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16218/HighFidelity-Beta-PR14168-e84ec15.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16218/HighFidelity-Beta-PR14168-e84ec15.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16218/HighFidelity-Beta-Interface-PR14168-e84ec15.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16218/HighFidelity-Beta-PR14168-e84ec15.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16218/HighFidelity-Beta-Interface-PR14168-e84ec15.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16226/HighFidelity-Beta-PR14168-6f2e587.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16226/HighFidelity-Beta-Interface-PR14168-6f2e587.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16226/HighFidelity-Beta-PR14168-6f2e587.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16226/HighFidelity-Beta-Interface-PR14168-6f2e587.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16292/HighFidelity-Beta-PR14168-6764d24.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16292/HighFidelity-Beta-PR14168-6764d24.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16292/HighFidelity-Beta-Interface-PR14168-6764d24.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16292/HighFidelity-Beta-PR14168-6764d24.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/16292/HighFidelity-Beta-Interface-PR14168-6764d24.exe

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/16339/HighFidelity-Beta-PR14168-b899319.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16339/HighFidelity-Beta-PR14168-b899319.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/16339/HighFidelity-Beta-Interface-PR14168-b899319.dmg

**Comment by hifi-gustavo** [comment]
Can someone from High Fidelity approve this PR?

**Comment by ZappoMan** [comment]
Closed for being really old/out of date.

**Pull request closed without merging**
