### PR TITLE
Fix framebuffer debugging

### PR DESCRIPTION
**Pull request by SamGondelman**
https://highfidelity.manuscript.com/f/cases/18051/luci-js-debug-framebuffers-broken

Test plan:
- Open luci.js
- Go through all the Debug Framebuffers and confirm that they work (it's not immediately obvious what each one should do, feel free to ask me if you have questions).

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12634/HighFidelity-Beta-PR13932-dff8292.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12634/HighFidelity-Beta-PR13932-dff8292.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12634/HighFidelity-Beta-Interface-PR13932-dff8292.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12634/HighFidelity-Beta-PR13932-dff8292.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12634/HighFidelity-Beta-Interface-PR13932-dff8292.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 
Debug framebuffers work as expected.

**Pull request merged**
