### PR TITLE
Image overlay uses bounds property

### PR DESCRIPTION
**Pull request by vladest**
https://highfidelity.fogbugz.com/f/cases/11117/Loading-Content-Bar-not-animating

Test plan
- Open an domain
- check progress bar. It should be animated

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6785/app_12308_PR.apk

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6835/app_12308_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6835/HighFidelity-Beta-PR12308-87ab8a5840dc5d55d7755afe7488eab230313a3d.exe

**Comment by sethalves** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/6877/app_12308_PR.apk

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/6877/HighFidelity-Beta-PR12308-87ab8a5840dc5d55d7755afe7488eab230313a3d.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/6877/HighFidelity-Beta-PR12308-87ab8a5840dc5d55d7755afe7488eab230313a3d.dmg

**Comment by QAadahlin** [comment]
Currently Testing

**Pull request merged**
