### PR TITLE
fix far grab to equip transition

### PR DESCRIPTION
**Pull request by druiz17**
Fix the transition from far grab to equip. 
- https://highfidelity.fogbugz.com/f/cases/7621/Far-Grab-to-Near-Equip-Doesn-t-Always-Work

### CODE REVIEW

**Comment by druiz17** [comment]
Test plan
- https://highfidelity.testrail.net/index.php?/cases/view/73&group_by=cases:section_id&group_order=asc&group_id=13

- make sure that step one works

**Comment by Nex-Pro** [comment]
Awaiting build for Windows

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5407/HighFidelity-Beta-PR11933-bbc022da2d0cc24ab0c147be7256959051950c87.dmg

**Comment by Nex-Pro** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5409/HighFidelity-Beta-PR11933-bbc022da2d0cc24ab0c147be7256959051950c87.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5409/HighFidelity-Beta-PR11933-bbc022da2d0cc24ab0c147be7256959051950c87.dmg

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
IMO Fail this mostly doesn't work. Ie on most occasions when attempting to equip from far grab the item does not equip. With a very fast pull back it will occasionally equip. The reliability is very poor. In addition on one attempt the far grabbed ping-pong gun fell to the ground and the laser followed it despite the hand pointing in another direction. See image. Other observer saw same thing.

p37236-hifi-snap-by--on-2017-12-06_00-05-04

**Comment by druiz17** [comment]
@Nex-Pro this PR is ready for QA testing

**Comment by themelissabrown** [comment]
build this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5458/HighFidelity-Beta-PR11933-32fca16c8579badef6036ceb633547360848a384.exe

**Comment by Nex-Pro** [comment]
Testing

**Comment by Nex-Pro** [comment]
@druiz17 sorry for the delay. Try poking me in slack next time.

**Comment by Nex-Pro** [comment]
### FAIL


Tester: Piper.Peppercorn

System information.
CPU: Intel i7 4.0 ghz.
RAM: 16gb
GPU: Nvidia GTX1070 8gb
HMD: HTC Vive.
Controllers: Vive hand controllers.
Audio: USB headset.

Testing conditions:

Fresh installation of this build.(any previous installation completely removed)

Ran two clients ( one in desktop mode as observer )

First attempt to equip a pingpong gun from far to near grab resulted in:

Equipee seeing the gun initially in the correct position.
Observer not seeing the gun.
After dropping to pause mode the equipee also could not see the gun on un-pausing.
When pulling the trigger it was immediately apparent that the gun was now behind and some distance away from the hand of the holder. Moving the hand around and looking over my shoulder I could locate the gun as being equipped approx 15m away behind and to my left depending on my hand orientation.


The above situation was repeatable. Several times.

I won't post the videos here as github isn't suitable for such large files.

Also I found that after I had dropped the gun, on more than one attempt, the observer still showed it as equipped. I made a video of this where the empty hand of the HMD avatar is in shot and moving and the observer is seeing the gun in the hand. Again this was repeatable.


**Here the equipped gun is above the head of the observer**
f38968-hifi-snap-by--on-2017-12-07_16-28-43

**Comment by druiz17** [comment]
test this please

**Comment by druiz17** [comment]
test this please

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5490/HighFidelity-Beta-PR11933-32fca16c8579badef6036ceb633547360848a384.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5493/HighFidelity-Beta-PR11933-41102956779d60062b350b3adc6c54747882d008.dmg

**Comment by druiz17** [comment]
test this please

**Comment by druiz17** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/5501/HighFidelity-Beta-PR11933-41102956779d60062b350b3adc6c54747882d008.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/5501/HighFidelity-Beta-PR11933-41102956779d60062b350b3adc6c54747882d008.dmg

**Comment by Nex-Pro** [comment]
Previous test results posted in testrail and slack

**Comment by Nex-Pro** [comment]
Retest with latest build and updated test instructions.

**Comment by Nex-Pro** [comment]
### PASS.

Both avatars observed same when tested within the parameters.

**Pull request merged**
