### PR TITLE
CR for 20532 - Default face tracking to Use Camera for first time users 

### PR DESCRIPTION
**Pull request by ctrlaltdavid**
And automatically do a DDE calibration first time Use Camera face tracking is turned on during a program run.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Build console output for commit: 5092e385b10b0ab16d9cabe4eb64fde8bb8166ca available at: https://gist.github.com/8b967e523b98c3cd00d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4813.dmg

**Comment by cozza13** [comment]
@ctrlaltdavid this works well for me.

**Comment by cozza13** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8a3c8e0d9a03231f61c73be45164b79feaa41895 available at: https://gist.github.com/8b967e523b98c3cd00d0<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4813.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-4813.dmg

**Pull request merged**
