### PR TITLE
Add version to launch user activity

### PR DESCRIPTION
**Pull request by huffman**

### CODE REVIEW

**Comment by huffman** [comment]
To test:

1. Run script: `https://gist.githubusercontent.com/huffman/1aad59b6c1b43ffdd666a8da095f989e/raw/aa84b84718705995d84e3a95c12a86acd3e717ec/nullScript.js?pr8146`
2. That's all. Let me know when you've done this and I will confirm that everything has worked.

**Comment by hifi-gustavo** [comment]
Build console output for commit: b36a39b2bcda94de87fdc831da884611f8a85eea available at: https://gist.github.com/ead038d77c450e4abe8a7a805dc05f57<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8146.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR8146.dmg

**Comment by OmegaHeron** [comment]
@huffman - ran script.

**Comment by huffman** [comment]
Looks good, thanks @OmegaHeron !

**Pull request merged**
