### PR TITLE
[DO NOT MERGE] Disable PlaySampleSound item, which creates resource for the test sou…

### PR DESCRIPTION
**Pull request by vladest**
…nd, blocking UI thread

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1277/HighFidelity-Beta-PR10869-a59f732ee68c6765d751e1db665203c5ea3237df.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1277/HighFidelity-Beta-PR10869-a59f732ee68c6765d751e1db665203c5ea3237df.dmg

**Comment by cozza13** [comment]
Jazmin has been crashing with Audio switching. https://highfidelity.fogbugz.com/f/cases/5842/DeadlockWatchdogThread-run-350-Settings-Audio-Crash . I am not able to repro the crash, I will get her to repro the crash then try this PR.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/1455/HighFidelity-Beta-PR10869-b115ae1b70c4a547b5c18d6b7261325f5b26f1d4.exe

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/1455/HighFidelity-Beta-PR10869-b115ae1b70c4a547b5c18d6b7261325f5b26f1d4.dmg

**Comment by cozza13** [comment]
this has been resolved in another PR

**Pull request closed without merging**
