### PR TITLE
Don't auto-action entry in HMD file dialog when single-click

### PR DESCRIPTION
**Pull request by ctrlaltdavid**

### CODE REVIEW

**Comment by ctrlaltdavid** [comment]
#### Test Plan

- HMD mode.
- Edit > Import Entities.
- Using laser.

A) Using laser.

1) Click a directory selects that row and enables the "OPEN" button; clicking the button navigates into the selected directory.
2) Double-clicking a directory immediately navigates into that directory.
3) Click a file selects that file and enables the "OPEN" button; clicking the button imports the selected file.
4) Double-clicking a file immediately imports that file.

B) Using mouse.
Repeat the tests in A). Known bug: To double-click you have to click 3 times.

Example JSON file attached, or you can create your own using Edit > Export Entities.
[cube-and-sphere.zip](https://github.com/highfidelity/hifi/files/2279556/cube-and-sphere.zip)

https://highfidelity.manuscript.com/f/cases/11360

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/12045/HighFidelity-Beta-PR13810-3a356de.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12045/HighFidelity-Beta-PR13810-3a356de.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/12045/HighFidelity-Beta-Interface-PR13810-3a356de.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12045/HighFidelity-Beta-PR13810-3a356de.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/12045/HighFidelity-Beta-Interface-PR13810-3a356de.exe

**Comment by qliejahner** [comment]
Currently testing

**Comment by qliejahner** [comment]
PASS @conklin94122 

File dialog no longer treats single clicks as double clicks in VR mode, making it much more pleasant to use. No side effects seen in desktop mode.

**Pull request merged**
