### PR TITLE
21232 - Remove Mini Mirror from View menu

### PR DESCRIPTION
**Pull request by Triplelexx**
**Test Plan:**

The Mini Mirror option should be removed from the View menu.
The Mirror option should still be available with no change to behavior, the audio level meter should also have no change to behavior.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by ZappoMan** [comment]
add to whitelist

**Comment by hifi-gustavo** [comment]
Build console output for commit: a9b1a3866587ecb01a33577faa1a1d9ad92e0485 available at: https://gist.github.com/eb3543ecac700e53e599562111ac31b6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-a9b1a38.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-a9b1a38.dmg

**Comment by ZappoMan** [comment]
errors....
```
   InterfaceActionFactory.cpp
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2909): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2909): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2919): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2919): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2923): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2923): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2933): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2933): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2943): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2943): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2946): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2946): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2957): error C2360: initialization of 'isMirrorChecked' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2957): error C2360: initialization of 'previousMode' is skipped by 'case' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2968): error C2361: initialization of 'isMirrorChecked' is skipped by 'default' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2895) : see declaration of 'isMirrorChecked'
    58>C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2968): error C2361: initialization of 'previousMode' is skipped by 'default' label [C:\jenkins\workspace\beta_pr-master\label\windows\build\interface\interface.vcxproj]
                 C:\jenkins\workspace\beta_pr-master\label\windows\interface\src\Application.cpp(2871) : see declaration of 'previousMode'
         InterfaceLogging.cpp
```

**Comment by ZappoMan** [comment]
unix/mac errors...

```
[100%] Building CXX object interface/CMakeFiles/interface.dir/interface_automoc.cpp.o
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp: In member function ‘void Application::keyPressEvent(QKeyEvent*)’:
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2909:22: error: jump to case label [-fpermissive]
             case Qt::Key_P: {
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2919:22: error: jump to case label [-fpermissive]
             case Qt::Key_Slash:
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2923:22: error: jump to case label [-fpermissive]
             case Qt::Key_Plus: {
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2933:22: error: jump to case label [-fpermissive]
             case Qt::Key_Minus: {
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2943:22: error: jump to case label [-fpermissive]
             case Qt::Key_Equal:
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2946:22: error: jump to case label [-fpermissive]
             case Qt::Key_Space: {
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2957:22: error: jump to case label [-fpermissive]
             case Qt::Key_Escape: {
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2968:13: error: jump to case label [-fpermissive]
             default:
             ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2895:22: error:   crosses initialization of ‘bool isMirrorChecked’
                 bool isMirrorChecked = Menu::getInstance()->isOptionChecked(MenuOption::FullscreenMirror);
                      ^
/data/jenkins/Jenkins/workspace/beta_pr-master/label/ubuntu/interface/src/Application.cpp:2871:22: error:   crosses initialization of ‘CameraMode previousMode’
                 auto previousMode = _myCamera.getMode();
                      ^
make[2]: *** [interface/CMakeFiles/interface.dir/src/Application.cpp.o] Error 1
```

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8e086a8fc8b20c78f185b0065e8446ea8dfffcd7 available at: https://gist.github.com/eb3543ecac700e53e599562111ac31b6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-8e086a8.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-8e086a8.dmg

**Comment by ZappoMan** [comment]
warnings...

```
FramebufferCache.cpp:32, GNU C Compiler 4 (gcc), Priority: Normal
variable ‘colorFormat’ set but not used [-Wunused-but-set-variable]

FramebufferCache.cpp:33, GNU C Compiler 4 (gcc), Priority: Normal
unused variable ‘width’ [-Wunused-variable]

FramebufferCache.cpp:34, GNU C Compiler 4 (gcc), Priority: Normal
unused variable ‘height’ [-Wunused-variable]
```

**Comment by Triplelexx** [comment]
hmm, didn't notice those ones.

**Comment by ZappoMan** [comment]
@Triplelexx - No worries- they don't show up on windows, only mac/unix - but we need to fix them before Jenkins will complete a build.

**Comment by Triplelexx** [comment]
Even tried setting warning level to /Wall. Ok, np.

**Comment by ZappoMan** [comment]
@Triplelexx the gcc compiler is far more picky than VStudio

**Comment by Triplelexx** [comment]
@ZappoMan Seems you could lose createPrimaryFramebuffer entirely for now. The file scares me... I think Jenkins should be happier though.

**Comment by hifi-gustavo** [comment]
Build console output for commit: 8b845658e2418cf147bb43f88a338bc696ff467a available at: https://gist.github.com/eb3543ecac700e53e599562111ac31b6<br/><br/>Installers available for download at: <br/>Windows: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-8b84565.exe<br/>OS X: http://cachefly.highfidelity.com/HighFidelity-Beta-PR9941-8b84565.dmg

**Comment by OmegaHeron** [comment]
Tested Windows 10
QA Pass

Mini-mirror option no longer appears in menus.  Tested from application top menu bar, desktop HUD menu call and Tablet menu call.

Full screen mirror mode (and 1st/3rd p) view works as expected.  General smoke test passes.

**Pull request merged**
