### PR TITLE
Fix T-Pose, again

### PR DESCRIPTION
**Pull request by SamGondelman**
Test plan:
- Switch avatars a lot, in desktop and HMD
- Should never get stuck in a T-Pose, from your perspective or others'

### CODE REVIEW

**Comment by Nex-Pro** [comment]
awaiting build

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3814/HighFidelity-Beta-PR11505-3dafbf586d3cf278aaf2b6b12d14f8eb82761e20.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3814/HighFidelity-Beta-PR11505-3dafbf586d3cf278aaf2b6b12d14f8eb82761e20.exe

**Comment by Nex-Pro** [comment]
In progress

**Comment by Nex-Pro** [comment]
@SamGondelman  This looks good with regard to the T-Pose issue. But there seems to be another bug ( also in latest dev build ) where the observer does not see the other avatar change. Plus occasionally the observer sees the other avatar with a distorted pose. ( I don't think they are due to this PR. )

**Comment by SamGondelman** [comment]
@Nex-Pro Is the observer also running this build?  Those all sound related enough that I'd like to fix them in this PR.

**Comment by Nex-Pro** [comment]
@SamGondelman  Yes both on same build

**Comment by ZappoMan** [comment]
@SamGondelman - I wonder if you shouldn't be doing this PR against the RC... not master... because if there's a side effect in master not in the RC branch you'll be fighting shadows...

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3843/HighFidelity-Beta-PR11505-af8718c798fb57e7d7820e5618a2b8736a51e477.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3843/HighFidelity-Beta-PR11505-af8718c798fb57e7d7820e5618a2b8736a51e477.exe

**Comment by howard-stearns** [comment]
Is this going to spam the logs?

**Comment by SamGondelman** [comment]
@howard-stearns the logging is just for testing, I'll get rid of it once we figure out the networking issue

**Comment by ZappoMan** [comment]
@cozza13 - sounds like the additional issue discovered by @Nex-Pro also reproduces in the current beta - so it shouldn't be a QA fail for this PR. My 2 cents.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3854/HighFidelity-Beta-PR11505-846e7b855c2655e1d7ca62c2514368f0ef7d9642.dmg

**Comment by SamGondelman** [comment]
I'm going to close this and put up a PR against RC-56 per @conklin94122's request.

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3854/HighFidelity-Beta-PR11505-846e7b855c2655e1d7ca62c2514368f0ef7d9642.exe

**Pull request closed without merging**
